### PR TITLE
Changed the word 'swell' to the word 'well' in Basic Javascript challenge

### LINKED ISSUE #12576: Typo in the instruction
#### Issue Description
There is a spelling mistake in the instruction given.

* Here is the extract of the **Instruction:**

>Set myName to a string equal to your name and build myStr with myName between the strings "My name is " and " and I am swell!"

- Expected last word in the instruction: well
- Actual last word in the instruction: swell

Here _**well**_ is expected instead of _**swell**_ because, the context is set in the starting of the code as:
```// Example
var ourName = "Free Code Camp";
var ourStr = "Hello, our name is " + ourName + ", how are you?";

// Only change code below this line
var myName;
var myStr;
```

#### Browser Information

* Browser Name, Version: 
* Operating System: 
* Mobile, Desktop, or Tablet: 

#### Your Code

```js
 
 
 
```

### PR DESCRIPTION
**Pull request by TheeMattOliver**
#### Pre-Submission Checklist

- [x] Your pull request targets the `staging` branch of freeCodeCamp.
- [x] Branch starts with either `fix/`, `feature/`, or `translate/` (e.g. `fix/signin-issue`)
- [x] You have only one commit (if not, [squash](http://forum.freecodecamp.com/t/how-to-squash-multiple-commits-into-one-with-git/13231) them into one commit).
- [x] All new and existing tests pass the command `npm test`. Use `git commit --amend` to amend any fixes.

#### Type of Change

- [x] Small bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds new functionality)
- [ ] Breaking change (fix or feature that would change existing functionality)
- [ ] Add new translation (feature adding new translations)

#### Checklist:

- [x] Tested changes locally.
- [x] Closes currently open issue (replace XXXX with an issue no): Closes #12576

#### Description

Changed the word 'swell' to the word 'well' in Basic Javascript challenge "Constructing Strings with Variables." While the usage of 'swell' is probably fine, non-native English speakers may find it less unnatural to use the word 'well', and 'swell' is just uncommon enough in modern usage for 'well' to be a better word choice for native speakers.

All tests passing on local issue branch.

### CODE REVIEW

**Review by raisedadead — APPROVED** [review]
#### :sparkles: :sparkles: **LGTM.** :sparkles: :sparkles: 

Thanks @TheeMattOliver and congrats on your first contribution.

Next time, requesting you to have a look at our [Guidelines for Contributing](https://github.com/FreeCodeCamp/FreeCodeCamp/blob/staging/CONTRIBUTING.md) and do not add issue nos anywhere other than stated. 
In this case the branch name.

**Comment by dhcodes** [comment]
Lol, was going to say the same @raisedadead. Beat me to it!

**Comment by raisedadead** [comment]
@dhcodes 😉..!

**Comment by TheeMattOliver** [comment]
@raisedadead @dhcodes Thanks guys. I saw that after I'd pushed....next time, no issue number in branch name.

👍

**Pull request merged**
