### PR TITLE
feat(gitpod): Add env variables to .bashrc so they can be accessed globally

### PR DESCRIPTION
**Pull request by KartikSoneji**
Checklist:

- [x] I have read [freeCodeCamp's contribution guidelines](https://contribute.freecodecamp.org).
- [x] My pull request has a descriptive title (not a vague title like `Update index.md`)
- [x] My pull request targets the `master` branch of freeCodeCamp.
- [x] All the files I changed are in the same world language, for example: only English changes, or only Chinese changes, etc.

Closes #XXXXX

As discussed on Gitter, running `npm run seed` or `npm run develop` does not work on GitPod since the required environment variables (`COOKIE_DOMAIN`, `HOME_LOCATION` and `API_LOCATION`) are not set.
Adding an extra task to `.gitpod.yml` that writes these variables to `~/.bashrc` makes them available in new terminals as well.

### CODE REVIEW

**Review by ShaunSHamilton — DISMISSED** [review]
Thank you, for getting this out so quick. It looks good to me, and works from what I have tested. 👍 

Only thing that might be worthwhile is removing the `'` (single quotes), and adding an extra `;` (semicolon) to end the echo. This just helps the syntax highlighting.

**Comment by KartikSoneji** [comment]
@Sky020 You're welcome!

I am quite sure that escape sequences need to be enclosed in quotes to work. Does the patch work if you remove them?
Also, can you please point out where you want me to add an extra semicolon?

**Review by Gimhan-minion — DISMISSED** [review]

**Comment by ojeytonwilliams** [comment]
There are a few ways to `echo` newlines, discussed [here](https://stackoverflow.com/questions/8467424/echo-newline-in-bash-prints-literal-n), probably the most concise being `\\n`.

Since this makes the variables available in every terminal, can we get rid of the other `before`s?

**Comment by KartikSoneji** [comment]
> There are a few ways to `echo` newlines, discussed [here](https://stackoverflow.com/questions/8467424/echo-newline-in-bash-prints-literal-n), probably the most concise being `\\n`.

Changing `>` to `|` seems the most intuitive way to me.

> Since this makes the variables available in every terminal, can we get rid of the other `before`s?

Unfortunately, no.
GitPod runs tasks in [parallel](https://www.gitpod.io/docs/config-start-tasks/#:~:text=They,parallel.), so if we remove the `before`s from the other tasks then they won't get access to the variables.

**Comment by ojeytonwilliams** [comment]
> Changing `>` to `|` seems the most intuitive way to me.

Agreed, that works nicely.  It seems to confuse the syntax highlighter, but that's not a huge problem.

> Unfortunately, no.
> GitPod runs tasks in [parallel](https://www.gitpod.io/docs/config-start-tasks/#:~:text=They,parallel.), so if we remove the `before`s from the other tasks then they won't get access to the variables.

That's a shame. It would be nice if there was a global `before`.

**Review by ojeytonwilliams — APPROVED** [review]
LGTM :+1: Nice work, @KartikSoneji 

@Sky020 could you give this one last look and merge if you're happy?

**Review by ShaunSHamilton — APPROVED** [review]
This LGTM 👍 , and appears to work. @ojeytonwilliams , you are going to have to merge. I am unable to, whilst the merge block is active.

**Comment by ojeytonwilliams** [comment]
Sorry Shaun, I assumed you'd be able to once I'd reviewed.

@KartikSoneji thanks again for fixing this so quickly.

**Pull request merged**
