### PR TITLE
test(e2e,playwright):progress-bar improvement(added test for auth users, particularly for progress bar's visibility)

### PR DESCRIPTION
**Pull request by weilirs**
Checklist:

- [x] I have read and followed the [contribution guidelines](https://contribute.freecodecamp.org).
- [x] I have read and followed the [how to open a pull request guide](https://contribute.freecodecamp.org/#/how-to-open-a-pull-request).
- [x] My pull request targets the `main` branch of freeCodeCamp.
- [x] I have tested these changes either locally on my machine, or GitPod.

https://github.com/freeCodeCamp/freeCodeCamp/issues/51705

### CODE REVIEW

**Comment by moT01** [comment]
Looks like some of the tests are failing. Do you want to take a look at those when you get a chance @weilirs. Let us know if you need any assistance.

**Comment by weilirs** [comment]
> Looks like some of the tests are failing. Do you want to take a look at those when you get a chance @weilirs. Let us know if you need any assistance.

In debug mode the tests can pass but I don't know why it doesn't pass without `--debug`. Could you please take a look?

**Comment by rahulsuresh-git** [comment]
Can I take a look at this? @weilirs @moT01

**Comment by Sembauke** [comment]
Thank you for working on this.

Due to inactivity we have decided to close this pr. Feel free to re-open if you feel like working on this again.

**Pull request closed without merging**
