### PR TITLE
chore: use english challenges as fallback

### PR DESCRIPTION
**Pull request by naomi-lgbt**
Checklist:

- [X] I have read [freeCodeCamp's contribution guidelines](https://contribute.freecodecamp.org).
- [X] My pull request has a descriptive title (not a vague title like `Update index.md`)
- [X] My pull request targets the `main` branch of freeCodeCamp.
- [X] All the files I changed are in the same world language, for example: only English changes, or only Chinese changes, etc.

Closes #XXXXX

When attempting to pull down #40906 I ran in to build errors on the `espanol` curriculum. Thanks to @ojeytonwilliams we discovered that the build still requires that all files are present in the language directory. This PR brings the English files over for the non-responsive-web-design superblocks to allow #40906 to build when merged.

### CODE REVIEW

**Comment by RandellDawson** [comment]
Any reason to pull over the v7 files?  Also, why not do the same for Chinese?

**Comment by nhcarrigan** [comment]
> Any reason to pull over the v7 files?

Likely just a copy-paste. I'll try removing those and verify the build.

> Also, why not do the same for Chinese?

The Chinese build succeeds because the files (at least most of them) already exist. The build step traverses the directory and looks for the superBlocks and blocks, so missing everything was throwing errors on the Espanol build.

**Comment by ojeytonwilliams** [comment]
I'm not sure why the tests failed, given that they should just run on the English challenges.

Thinking about it, could setting up tests for Chinise and Spanish be a good issue to open up to contributors?

**Comment by nhcarrigan** [comment]
I think it was a timeout issue - some of the tests (especially the Euler and Rosetta Code ones) can get sluggish and exceed our timeout.

Setting up tests for other languages is a good idea, though our exact implementation is as of yet undefined. Mrugesh and I were talking about starting with a workflow we could trigger manually, for now.

**Comment by RandellDawson** [comment]
@nhcarrigan   Earlier @ojeytonwilliams and I were discussing having the challenge builder to start in the English folder and as it is building, it checks to see if there is a corresponding file in the specified language.  If there is, it uses it instead.  This way, you do not have to copy all the files into the folders like this PR is doing.

**Comment by nhcarrigan** [comment]
I'm all for that approach - this is more a hot-fix to ensure nothing is delayed. If we can implement a better method for handling this situation, I'm on board. 🙂

**Comment by ojeytonwilliams** [comment]
Originally an edit by Randy (I think he meant to reply!):

> Oliver mapped out his strategy for me in a call earlier today.  He did not think it would take long to implement.

**Comment by raisedadead** [comment]
Closing as discussed in chat.

**Comment by ojeytonwilliams** [comment]
It was a lot of chat, so just give context for @nhcarrigan : Randy got the download workflow working in https://github.com/freeCodeCamp/freeCodeCamp/pull/40922, so we're pretty confident that we can rely on it to give us all the fallbacks.

**Pull request closed without merging**
