### PR TITLE
Closes issue #2552

### PR DESCRIPTION
**Pull request by srodman7689**
closes issue #2552.

### CODE REVIEW

**Comment by benschenker** [comment]
:+1:

**Comment by benschenker** [comment]
@BerkeleyTrue will probably ask you to change the description to comply with:
https://github.com/FreeCodeCamp/FreeCodeCamp/wiki/Writing-great-git-commit-message
and to use:
https://help.github.com/articles/closing-issues-via-commit-messages/#keywords-for-closing-issues
by explicitly changing the description above to say `closes #2552`

**Comment by srodman7689** [comment]
I think that should fix the stuff from above. Please let me know if I need to fix it more. Thanks.

**Comment by benmcmahon100** [comment]
There's no need to have closes in both the description and the title but thanks for the added effort to make everything conform! More importantly thanks for the fix!

**Pull request merged**
