### PR TITLE
fix: add spacing between profile picture and social icons

### LINKED ISSUE #37324: Space between the profile and the social links
image

### PR DESCRIPTION
**Pull request by DerrykBoyd**
- [x] I have read [freeCodeCamp's contribution guidelines](https://github.com/freeCodeCamp/freeCodeCamp/blob/master/CONTRIBUTING.md).
- [x] My pull request has a descriptive title (not a vague title like `Update index.md`)
- [x] My pull request targets the `master` branch of freeCodeCamp.
- [x] None of my changes are plagiarized from another source without proper attribution.
- [x] All the files I changed are in the same world language (for example: only English changes, or only Chinese changes, etc.)
- [x] My changes do not use shortened URLs or affiliate links.

Closes #37324

### CODE REVIEW

**Comment by dboydgit** [comment]
image

**Review by raisedadead — CHANGES_REQUESTED** [review]
I think we could use even more space in between the avatar and also we could use some space in between the icons themselves. They look too squished with eachother

**Comment by raisedadead** [comment]
Much nicer. Thanks for working on this.

**Comment by dboydgit** [comment]
No problem, I'll push that. I realised working on it that there is a css file for the icons, so I moved changed in there.

**Review by raisedadead — APPROVED** [review]

**Pull request merged**
