### PR TITLE
added a test to challenge:falsy-bouncer

### LINKED ISSUE #37972: An incorrect solution would still pass all the tests
**Describe your problem and how to reproduce it:**
Below is an incorrect solution that would still pass all the tests.
```javascript
function bouncer(arr) {
// Don't show a false ID to this bouncer.
for(let i=0;i<arr.length;i++){
  if(!arr[i]){ 
    arr.splice(i,1);
    i=0}
}
if(arr[0]==null) arr.splice(0,1); //this solved my problem but isn't the correct solution.
console.log(arr)
return arr;
}
```
But this would not pass the below test which should return `[true,1]`. Therefore the students who haven't understood the problem correctly would still pass the tests.
```javascript
bouncer(["", NaN, true, 0, 1]) //returns [ NaN, true, 1 ]
```
I have also created a pull request to this that would solve the problem
**Add a Link to the page with the problem:**
[Challenge with Issue](https://www.freecodecamp.org/learn/javascript-algorithms-and-data-structures/basic-algorithm-scripting/falsy-bouncer)
[Discussion on forum about the issue](https://www.freecodecamp.org/forum/t/basic-algorithm-scripting-falsy-bouncer-null-issue/332331)
**Tell us about your browser and operating system:**
* Browser Name: Chrome
* Browser Version: 
* Operating System: Windows 10 Home

### PR DESCRIPTION
**Pull request by SavvyShah**
- [x] I have read [freeCodeCamp's contribution guidelines](https://github.com/freeCodeCamp/freeCodeCamp/blob/master/CONTRIBUTING.md).
- [x] My pull request has a descriptive title (not a vague title like `Update index.md`)
- [x] My pull request targets the `master` branch of freeCodeCamp.
- [x] None of my changes are plagiarized from another source without proper attribution.
- [x] All the files I changed are in the same world language (for example: only English changes, or only Chinese changes, etc.)
- [x] My changes do not use shortened URLs or affiliate links.

Closes #37972

### CODE REVIEW

**Review by moT01 — APPROVED** [review]
LGTM 🎉

**Comment by ShubhamCanMakeCommit** [comment]
Thanks. It's incredible to have a review from you. @moT01

**Comment by RandellDawson** [comment]
Instead of adding a new test, why not just flip the position of the 1st and 3rd elements to handle this edge case.
```
  - text: <code>bouncer([null, NaN, 1, 2, undefined])</code> should return <code>[1, 2]</code>.
    testString: assert.deepEqual(bouncer([null, NaN, 1, 2, undefined]), [1, 2]);
```

**Comment by ShubhamCanMakeCommit** [comment]
Yes that's a great point.

**Review by RandellDawson — APPROVED** [review]
@moT01 If you are fine with the latest changes, I am fine with them, so you can merge them.

**Review by Manish-Giri — APPROVED** [review]
LGTM

**Review by moT01 — APPROVED** [review]
You're welcome @ShubhamCanMakeCommit - Congratulations on your first contribution to freeCodeCamp! 🎉 We welcome future PR's 🎉

**Pull request merged**
