### PR TITLE
Fix disappearing star upon completion of required challenge

### LINKED ISSUE #9779: The star disappear from required, when done.
#### Issue Description

Maybe it's a small thing. But in the Map link you can see an overview of everything. And there is the text on top of the page: "**Challenges required for certifications are marked with a *.**". It's nice but as soon as you have done a challenge marked with a * it's marked as done but the star disappear. The star that tells you it's required for certifications.

Just nice if the star was still there. :) 

#### Browser Information

I use Chrome on Windows and did not try any other. Don't think that matters?

### PR DESCRIPTION
**Pull request by dhcodes**
#### Pre-Submission Checklist

- [x] Your pull request targets the `staging` branch of FreeCodeCamp.
- [x] Branch starts with either `fix/`, `feature/`, or `translate/` (e.g. `fix/signin-issue`)
- [x] You have only one commit (if not, [squash](https://github.com/FreeCodeCamp/FreeCodeCamp/wiki/Git-Squash) them into one commit).
- [x] All new and existing tests pass the command `npm run test-challenges`. Use `git commit --amend` to amend any fixes.
#### Type of Change

- [x] Small bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds new functionality)
- [ ] Breaking change (fix or feature that would change existing functionality)
- [ ] Add new translation (feature adding new translations)
#### Checklist:

- [x] Tested changes locally.
- [x] Closes currently open issue (replace XXXX with an issue no): Closes #9779 
#### Description

Added 

```
span.text-primary &thinsp; &thinsp;  
   strong *
```

to server/views/map/show.jade, to keep the star on required challenges after completion.

### CODE REVIEW

**Comment by bugron** [comment]
@dhcodes thanks for the PR. You have a typo on line 40 (a plus symbol). Remove it, amend your commit and we're good to merge.

**Comment by dhcodes** [comment]
@bugron I updated this but couldn't get amend to work properly so I ended up recreating the whole branch and change. It appears the fix is correct now, but it's failing at snyk. Is there something I need to fix on my end?

**Comment by bugron** [comment]
Just ignore snyk errors. Please make `strong *` a child of `span.text-primary` for consistency.

**Comment by dhcodes** [comment]
@bugron done.

**Comment by bugron** [comment]
And last thing, sorry for this, but give your commit a better name, please. Your PR's title suits well.

**Comment by dhcodes** [comment]
@bugron done. Sorry for all the meh.

**Comment by bugron** [comment]
@dhcodes verified and merged! Thanks for your contribution :+1:

**Comment by raisedadead** [comment]
ProTip: To avoid synk errors, always keep your staging branch synced from main repo.

```
git checkout staging
git pull --rebase upstream staging
git push origin staging -f
```

Then start with your new branch and fixes

**Pull request merged**
