### PR TITLE
Fix/update hint and test for cat photo app course

### PR DESCRIPTION
**Pull request by texas2010**
Checklist:

- [X] I have read [freeCodeCamp's contribution guidelines](https://contribute.freecodecamp.org).
- [X] My pull request has a descriptive title (not a vague title like `Update index.md`)
- [X] My pull request targets the `main` branch of freeCodeCamp.
- [ ] I have tested these changes either locally on my machine, or GitPod.

This PR is on purpose to improve hints and testing in the lesson.

# Step 3:

Somehow test allows the user to write anything before the start of the p element's text
So I fixed one test that won't accept anything at the start of the string.

<details>
  <summary>Step 3 screenshot</summary>
  
  ### Before change:
  
Screen Shot 2022-07-13 at 2 17 25 PM
  
  ### After change:
  
Screen Shot 2022-07-13 at 2 18 42 PM

</details>

---

# Step 5:

When the user could put the main opening and closing tag anywhere as test accept. So, I fixed that and ensured the main opening and closing tag is in the right place to pass.
By the way, there has more explanation in the screenshot.

<details>
  <summary>Step 5 screenshot</summary>
  
## About Main opening tag:
When the user puts the main opening tag in the wrong place, it will tell the user that it needs to have a closing tag. It is not very clear to them.

  ### Before change:

Screen Shot 2022-07-13 at 2 38 40 PM
  
  ### After change:
 
Screen Shot 2022-07-13 at 2 40 53 PM

## About main closing tag:
When the user puts the main closing tag in the wrong place. and tests will pass. since there doesn't have regex to check the closing tag.

### Before Change:

Screen Shot 2022-07-13 at 2 49 55 PM

### After Change: 

Screen Shot 2022-07-13 at 2 50 36 PM

</details>

---

# Step 9: 

When the user makes a typo at the start of the alt's value. The test will pass.
So I fixed one test that won't accept anything at the start of the string.

<details>
  <summary>Step 9 screenshot</summary>

### Before change:  

Screen Shot 2022-07-13 at 3 08 30 PM

### After change: 

Screen Shot 2022-07-13 at 3 09 12 PM

</details>

---

# Step 10:

Somehow test passed when the user write href's value without using quotes on the value. I fixed it, and it was the wrong URL. So I have to correct it.

This lesson is about how to create an anchor element first time. So I added a test to tell the user to remove any extra anchor element. Since many users create extra anchor elements. The test focus on the first anchor element and not the additional element. So I am not sure if this need to be there.

---

# Step 12:

When the user deletes the anchor element early, tests do not tell the user that the anchor element is missing. Somehow, it keeps saying remove any extra anchor element. 

So I added some tests to tell users to create the anchor element when it does not exist since the lesson asks the user to move or make the anchor element into the p element. 

Another thing is p element allows the user to make any typo at the start of the string. So I fixed one test that won't accept anything at the start of the string.

<details>
  <summary>Step 12 screenshot</summary>

  ### Before Change:

Screen Shot 2022-07-13 at 4 46 34 PM

  ### After Change:

Screen Shot 2022-07-13 at 4 47 17 PM

</details>

### CODE REVIEW

**Comment by RandellDawson** [comment]
@texas2010 You did not explain why the changes were made. Why were these changes necessary?

**Comment by texas2010** [comment]
@RandellDawson Hello, I was going to explain when I am done with this PR and update my PR comment. (but I am still in the process of work and checking some lessons) but I can answer this. I did not know it was on purpose to ask users to write text anywhere if they did not put it in the h1 element.

At first, I thought test don't need to be there because there is the last test to check and ensure the `CatPhotoApp` text exists in the h1 element. Another reason I removed it because that test was blocked when the h1 element did not exist if users decided to delete the h1 element or change it. And it will ask the user to write the `CatPhotoApp` text.

And now, I realize it is a mistake to do that. As you explained, asking users to write it first if they did not use the element or put text into the h1 element is better.

I will revert it.

**Comment by RandellDawson** [comment]
@texas2010 Yeah these hints have to be written in a particular order unlike the old curriculum, since only the first one that fails the tests shows up.  I wrote most of the tests for the first two projects in RWD section.  I spent extra time on the first half of the first project as evident with all the hints.  I did that to try "guide" the users to the solution taking in consideration the kinds of mistakes we have all seen on the forum as moderators over the past several years of the older RWD section.  I hope the hints/tests being written for the first half of the first JS project will be written with extreme beginners in mind or we will see mass confusion on the forum.

I will say that a lot of the projects that appear later in the RWD section seem to be more "Do x, y, and z" when new concepts are introduced and less explanation of why, but that is my opinion.  Those kinds of steps are fine if the user is forced to apply the same concept multiple times in a project, but if they are one-off without much explanation why, I do not think users will really "learn" the concepts.  Many of the more advanced CSS topics/concepts included in the later projects in the new RWD probably need 25% to 50% more steps to get more repetition of the concepts we currently see frustrating users in the current RWD curriculum.

**Comment by raisedadead** [comment]
Closing as discussed.

**Pull request closed without merging**
