### PR TITLE
Fixes broken link to 'undefined is a keyword'

### LINKED ISSUE #38895: Link to "undefined is a keyword" is broken
**Describe your problem and how to reproduce it:**
1. Visit https://www.freecodecamp.org/learn/javascript-algorithms-and-data-structures/basic-javascript/return-early-pattern-for-functions
2. Click on the link to undefined in Hint section.
3. It opens https://www.freecodecamp.org/challenges/understanding-uninitialized-variables 
4. 404 is shown on the opened page.

**Add a Link to the page with the problem:**
https://www.freecodecamp.org/learn/javascript-algorithms-and-data-structures/basic-javascript/return-early-pattern-for-functions

**Tell us about your browser and operating system:**
* Browser Name: Firefox
* Browser Version: 76.0.1
* Operating System: macOS

**If possible, add a screenshot here (you can drag and drop, png, jpg, gif, etc. in this box):**
Screenshot 2020-05-25 at 8 39 04 PM
Screenshot 2020-05-25 at 8 39 31 PM

### PR DESCRIPTION
**Pull request by JapneetSingh5**
Checklist:

- [x] I have read [freeCodeCamp's contribution guidelines](https://contribute.freecodecamp.org).
- [x] My pull request has a descriptive title (not a vague title like `Update index.md`)
- [x] My pull request targets the `master` branch of freeCodeCamp.
- [x] All the files I changed are in the same world language, for example: only English changes, or only Chinese changes, etc.

Closes #38895

### CODE REVIEW

**Comment by vipranarayan14** [comment]
Checked the pull request with Gitpod. The link under **Hint** section correctly opens [Basic JavaScript: Understanding Uninitialized Variables](https://www.freecodecamp.org/learn/javascript-algorithms-and-data-structures/basic-javascript/understanding-uninitialized-variables) page.

**Review by vipranarayan14 — APPROVED** [review]
Checked the pull request with Gitpod. The link under **Hint** section correctly opens [Basic JavaScript: Understanding Uninitialized Variables](https://www.freecodecamp.org/learn/javascript-algorithms-and-data-structures/basic-javascript/understanding-uninitialized-variables) page.

**Review by vipranarayan14 — APPROVED** [review]

**Comment by Sky020** [comment]
We are just confirming which link should be used for the lesson. Once this is done, either changes will need to be made, or this will be given the go-ahead.

**Comment by JapneetSingh5** [comment]
Thanks a lot!

**Review by scissorsneedfoodtoo — APPROVED** [review]
:sparkles: :sparkles: :sparkles: Awesome! Congratulations on your first contribution to freeCodeCamp! :sparkles: :sparkles: :sparkles:

Thank you for submitting a PR for this, @JapneetSingh5. We're all really looking forward to your next contribution.

**Pull request merged**
