### PR TITLE
fix: disable button after submission

### LINKED ISSUE #38052: Lag on donate page may cause a 2nd duplicate donation
A small percentage of donors accidentally create a second duplicate donation (when they intend to only create one monthly-recurring donation).

I suspect this may be due to some sort of input lag when they are on a less reliable connection. We should create some sort of debounce to ensure people don't accidentally create two donations instead of one.

### PR DESCRIPTION
**Pull request by ahmaxed**
- [x] I have read [freeCodeCamp's contribution guidelines](https://github.com/freeCodeCamp/freeCodeCamp/blob/master/CONTRIBUTING.md).
- [x] My pull request has a descriptive title (not a vague title like `Update index.md`)
- [x] My pull request targets the `master` branch of freeCodeCamp.
- [x] None of my changes are plagiarized from another source without proper attribution.
- [x] All the files I changed are in the same world language (for example: only English changes, or only Chinese changes, etc.)
- [x] My changes do not use shortened URLs or affiliate links.

This pr will disable the submission button after the form is submitted and enable it during the donation processing.

Closes #38052

### CODE REVIEW

**Review by raisedadead — COMMENTED** [review]
This is just a cosmetic change, we should also debounce the actual calls to the API (both client and server side).

**Comment by ahmadabdolsaheb** [comment]
@raisedadead, 
I was wondering if you have any preferences for this implementation.
Would you like to debounce the leading call for a certain number of seconds on client and on the api using lodash/rx,  or should I just keep a state on both sides to make sure a new call is only executed when there is no payment being processed?

**Comment by raisedadead** [comment]
I do not have a preference, personally. I would defer to your best judgement. What I do want is that it should be the best of UX and safeguard. I think state replication is a better idea. I would let you decide though.

**Comment by raisedadead** [comment]
How is this coming along, since we still have this on the donate modal?

**Comment by ahmadabdolsaheb** [comment]
Thanks for your patience on this. I will get around to it right after submitting the amazon integration pr.

**Pull request closed without merging**
