### PR TITLE
feat(learn): Move American British Translator tests

### PR DESCRIPTION
**Pull request by naomi-lgbt**
Signed-off-by: nhcarrigan <nhcarrigan@gmail.com>

Checklist:

- [X] I have read [freeCodeCamp's contribution guidelines](https://contribute.freecodecamp.org).
- [X] My pull request has a descriptive title (not a vague title like `Update index.md`)
- [X] My pull request targets the `master` branch of freeCodeCamp.
- [X] All the files I changed are in the same world language, for example: only English changes, or only Chinese changes, etc.

Closes #XXXXX

Moves the functional test descriptions out of the boilerplate and into the `/learn` page for translation purposes.

### CODE REVIEW

**Review by kbakdev — DISMISSED** [review]

**Comment by RandellDawson** [comment]
Should those values in double quotes actually be surrounded by `<code>` and `</code>` instead?

**Comment by nhcarrigan** [comment]
Sure, I can do that. 🙂

Honestly this feels very much like a wall of text, and I'd love to determine a better approach for this one.

**Comment by RandellDawson** [comment]
It is a wall of text, but it is a project and not a curriculum challenge, so I am less concerned about it.

**Review by moT01 — APPROVED** [review]
LGTM @nhcarrigan 🎉 Yea, I don't think I mind the wall of text here either, but I am certainly open to suggestions/ideas - I don't know how else to go about it.

**Review by RandellDawson — APPROVED** [review]
LGTM

**Comment by RandellDawson** [comment]
Thank you for your contribution to the page! 👍
We're happy to accept these changes, and look forward to future contributions. 🎉

**Pull request merged**
