### PR TITLE
chore: update to beta of react-instantsearch-dom

### PR DESCRIPTION
**Pull request by ojeytonwilliams**
This performs the migration @scissorsneedfoodtoo talked about here: https://github.com/freeCodeCamp/freeCodeCamp/issues/36821#issuecomment-534048754

### CODE REVIEW

**Review by raisedadead — COMMENTED** [review]
Not a need for this PR, but since you are at this, will you be interested in getting the keys from the build env instead? 

This is so that we are able to build it for other languages that will have a different index and app id.

**Comment by ojeytonwilliams** [comment]
Sure. Do you want that in a separate PR?

**Comment by raisedadead** [comment]
> Do you want that in a separate PR?

It can come along with this PR, if it's all the same for you.

**Review by raisedadead — APPROVED** [review]
Hi @ojeytonwilliams can I get quick merge conflict resolution. Please merge as well when you have.

**Pull request merged**
