### PR TITLE
feat: use en as i18n fallback

### PR DESCRIPTION
**Pull request by naomi-lgbt**
Checklist:

- [X] I have read [freeCodeCamp's contribution guidelines](https://contribute.freecodecamp.org).
- [X] My pull request has a descriptive title (not a vague title like `Update index.md`)
- [X] My pull request targets the `main` branch of freeCodeCamp.
- [X] All the files I changed are in the same world language, for example: only English changes, or only Chinese changes, etc.

Closes #XXXXX

Loads the English versions of the files as a "fallback" language to avoid displaying keys when a translation is missing.

### CODE REVIEW

**Review by moT01 — COMMENTED** [review]
I pointed this out [here](https://github.com/freeCodeCamp/freeCodeCamp/blob/main/config/i18n/all-langs.js#L11), but using `fallback` as the key seems to stop us from being able to use certain features, mainly the `_plural` in some keys I've noticed. Most likely the same for all of our keys that use the underscore in some way - which is very few.

Using `fallback`:
Screen Shot 2021-02-24 at 10 54 28 AM

Using `en`:
Screen Shot 2021-02-24 at 10 54 36 AM

^^ notice the spelling of `point/points`. 

I can't find an explanation in their docs, other than that they say to use those codes. They actually say to use a `en-US` format, but `en` seems to work. Could probably delete the `i18nextCodes` object from file I linked at the top and just use the `langCodes` object. That's a side issue I suppose.

I don't think this is much of a problem since we don't use many keys with the underscores, and they would only show up when when those keys are missing from the default language. What do you think @nhcarrigan? We could probably just change `fallback` to `en` - I don't think it would cause any problems.

**Comment by nhcarrigan** [comment]
My only question with using `en` as the fallback is:

Will that create issues with loading resources for the `en` key twice when we build the English client?

**Comment by moT01** [comment]
It doesn't seem to, I just tested it. Could we possibly conditionally load the fallback language only when the default isn't English?

**Comment by nhcarrigan** [comment]
If it won't cause any build errors, then it might be simplest to use `en` as the fallback in all cases. Shouldn't be a problem.

**Comment by nhcarrigan** [comment]
Alright I've switched it to use `en` as the fallback value.

**Review by moT01 — APPROVED** [review]
LGTM 🎉

**Pull request merged**
