### PR TITLE
Fixed old style "Free Code Camp" to "freeCodeCamp" in seed/challenges/ json files

### PR DESCRIPTION
**Pull request by Dazler**
#### Pre-Submission Checklist

- [x] Your pull request targets the `staging` branch of freeCodeCamp.
- [ ] Branch starts with either `fix/`, `feature/`, or `translate/` (e.g. `fix/signin-issue`)
- [ ] You have only one commit (if not, [squash](http://forum.freecodecamp.com/t/how-to-squash-multiple-commits-into-one-with-git/13231) them into one commit).
- [ ] All new and existing tests pass the command `npm test`. Use `git commit --amend` to amend any fixes.

#### Type of Change

- [ ] Small bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds new functionality)
- [ ] Breaking change (fix or feature that would change existing functionality)
- [ ] Add new translation (feature adding new translations)

#### Checklist:

- [ ] Tested changes locally.
- [ ] Closes currently open issue (replace XXXX with an issue no): Closes #XXXX

### CODE REVIEW

**Comment by Dazler** [comment]
@BerkeleyTrue what is problem??? Why the pull request got rejected????

**Comment by systimotic** [comment]
@Dazler Thanks for the PR, I'm closing this in favour of your new PR #12714

**Comment by Dazler** [comment]
i think my pull request didnt get merged?? Explain me please,,,Thanx anyway

**Comment by systimotic** [comment]
@Dazler You opened another PR that does the same, but without the problem in this one. This one was indeed not merged, so we can merge the other one if that turns out to work OK

**Pull request closed without merging**
