### PR TITLE
fix(client): get translationPending in video chals

### PR DESCRIPTION
**Pull request by ojeytonwilliams**
Checklist:

- [x] I have read [freeCodeCamp's contribution guidelines](https://contribute.freecodecamp.org).
- [x] My pull request has a descriptive title (not a vague title like `Update index.md`)
- [x] My pull request targets the `main` branch of freeCodeCamp.
- [x] All the files I changed are in the same world language, for example: only English changes, or only Chinese changes, etc.

The added prop is used to show the "Help us translate." text

### CODE REVIEW

**Comment by ojeytonwilliams** [comment]
This was brought up by @ShaunSHamilton here https://github.com/freeCodeCamp/freeCodeCamp/pull/41565#issuecomment-805230116

**Review by raisedadead — DISMISSED** [review]

**Comment by ShaunSHamilton** [comment]
@ojeytonwilliams I am still encountering this error:
```
Warning: Failed prop type: The prop `translationPending` is marked as required in `Project`, but its value is `undefined`.
    in Project (created by withI18nextTranslation(Project))
    in withI18nextTranslation(Project) (created by Connect(withI18nextTranslation(Project)))
    in Connect(withI18nextTranslation(Project)) (created by HotExportedConnect(withI18nextTranslation(Project)))
```
Steps to reproduce:
1) Navigate to: `/learn/scientific-computing-with-python/scientific-computing-with-python-projects/probability-calculator`
2) Submit any solution
3) See error, once navigated to next superblock

**Comment by ShaunSHamilton** [comment]
Now, I am struggling to get the error back, but I did come across this:
```
Warning: Failed prop type: Invalid prop `user.completedChallenges[0].files` of type `object` supplied to `CertChallenge`, expected `array`.
    in CertChallenge (created by withI18nextTranslation(CertChallenge))
    in withI18nextTranslation(CertChallenge) (created by Connect(withI18nextTranslation(CertChallenge))
```

**Comment by ojeytonwilliams** [comment]
Thanks, Shaun, I've pushed another commit to fix that.

**Review by ShaunSHamilton — APPROVED** [review]
This LGTM 👍 
Thank you, Oliver.

**Review by raisedadead — APPROVED** [review]

**Pull request merged**
