### PR TITLE
expanded description of 'Where art thou' bonfire

### PR DESCRIPTION
**Pull request by butterthebuddha**
For issue: #2842

### CODE REVIEW

**Comment by benmcmahon100** [comment]
Thanks @awesomeaniruddh !

**Comment by abhisekp** [comment]
@benmcmahon100 contradicts/conflicts with PR #1756

**Comment by benmcmahon100** [comment]
@abhisekp This is the correct description though to my knowledge. I'll go and check my solution and confirm it matches up but I'd rather change the description then modify the tests. That way it's a lot less likely to deviate from what the bonfire was initially about. Both prs are appreciated though and depending in whether or not people are satisfied with the results we may end up using both although quincy is currently going through all the bonfires and changing them from expects to asserts

**Comment by abhisekp** [comment]
@benmcmahon100 The current bonfire description says
> Make a function that looks through an array (first argument) and returns an array of all objects that have equivalent **property values** (second argument).

It could have just said this instead
> Make a function that looks through an array (first argument) and returns an array of all objects that have equivalent **properties** (in second argument).

**Comment by benmcmahon100** [comment]
Is that on production? Or is that what the change says?

**Comment by abhisekp** [comment]
It's on production

**Comment by abhisekp** [comment]
@benmcmahon100 
The current assertion also doesn't match up with the description (in production)
```js
assert.deepEqual(where([{ first: 'Romeo', last: 'Montague' }, { first: 'Mercutio', last: null }, { first: 'Tybalt', last: 'Capulet' }], { last: 'Capulet' }), [{ first: 'Tybalt', last: 'Capulet' }], 'should return an array of objects');
```

**Comment by benmcmahon100** [comment]
Yeah this pr hasn't been deployed yet (I don't think)

**Comment by abhisekp** [comment]
@benmcmahon100 this PR isn't compatible with the actual purpose of the challenge and the change in description doesn't match with current assertion in the production.

**Comment by benmcmahon100** [comment]
It looks perfect to me

**Comment by benmcmahon100** [comment]
Unless you can find the point where the new desc contradicts the challenge asserts I'm happy that this is the most simplistic solution

**Comment by abhisekp** [comment]
@benmcmahon100 what?
How can the description (in this PR)
> For example, if the first argument is <code>[{ first: 'Romeo', last: 'Montague' }, { first: 'Mercutio', last: null }, { first: 'Tybalt', last: 'Capulet' }]</code>, and the second argument is <code>{ last: 'Capulet' }</code>, then you must return the first and the third objects from the array (the first argument), because they contain the property that was passed on as the second argument.

The description suggests there will be two objects in the array i.e. `[{ first: 'Romeo', last: 'Montague' }, { first: 'Tybalt', last: 'Capulet' }]`

match up with the assertion in the production? http://www.freecodecamp.com/challenges/bonfire-where-art-thou

```js
assert.deepEqual(where([{ first: 'Romeo', last: 'Montague' }, { first: 'Mercutio', last: null }, { first: 'Tybalt', last: 'Capulet' }], { last: 'Capulet' }), [{ first: 'Tybalt', last: 'Capulet' }], 'should return an array of objects');
```
Here it expects only one object in the array ` [{ first: 'Tybalt', last: 'Capulet' }]`

**Comment by abhisekp** [comment]
@benmcmahon100 moreover according to this PR's description, i.e. 
> because they contain the property that was passed on as the second argument

all the three objects should be in the output as all the three contain the `last` property even if the second object has the value of `null`.

**Comment by benmcmahon100** [comment]
Good catch, I'll correct that now

**Comment by abhisekp** [comment]
@benmcmahon100 I wonder why you don't accept my PR :worried: #1756

**Comment by benmcmahon100** [comment]
There it's merged but I just hope it doesn't cause an issues with completing the bonfire. I'd rather have clarifications rather than tests to old challenges that have proven fairly solid over the test of time

**Comment by abhisekp** [comment]
close #2842

**Pull request merged**
