### PR TITLE
Removed "custom keys" from article 

### PR DESCRIPTION
**Pull request by binarygalwalkin**
- [x] I have read [freeCodeCamp's contribution guidelines](https://github.com/freeCodeCamp/freeCodeCamp/blob/master/CONTRIBUTING.md).
- [x] My pull request has a descriptive title (not a vague title like `Update index.md`)
- [x] My pull request targets the `master` branch of freeCodeCamp.
- [x] None of my changes are plagiarized from another source without proper attribution.
- [x] My article does not contain shortened URLs or affiliate links.

If your pull request closes a GitHub issue, replace the XXXXX below with the issue number.

Closes #29826

### CODE REVIEW

**Comment by binarygalwalkin** [comment]
@raisedadead Thanks for your hard work 👍

**Review by binarygalwalkin — COMMENTED** [review]
I deleted the "title" attribute when I deleted the custom keys - I suspect this is why the build is failing tests.

**Review by cmccormack — COMMENTED** [review]
Thank you for your contribution.  At this time we have decided not to merge your pull request.  We welcome future pull requests from you.

**Explanation**
The changes in this PR conflict with several files on the master branch.  The file(s) edited in this commit have since been edited and/or moved.  Please feel free to update your fork of the freeCodeCamp master branch and submit your edits in a new Pull Request.

When you submit a Pull Request, please only include changes to a single file for each branch.  It is difficult to review files in order when some PRs touch multiple files.  You can @ mention myself in your PRs and I will review them personally.

Happy Coding!

**Comment by binarygalwalkin** [comment]
@cmccormack - sorry, this got awfully wonky towards the end of #Hacktober. Will do!

**Pull request closed without merging**
