### PR TITLE
refactor: Replace .com with .org

### PR DESCRIPTION
**Pull request by systimotic**
#### Pre-Submission Checklist
- [x] Your pull request targets the `staging` branch of freeCodeCamp.
- [x] Branch starts with either `fix/`, `feature/`, or `translate/` (e.g. `fix/signin-issue`)
- [x] You have only one commit (if not, [squash](http://forum.freecodecamp.com/t/how-to-squash-multiple-commits-into-one-with-git/13231) them into one commit).
- [x] All new and existing tests pass the command `npm test`. Use `git commit --amend` to amend any fixes.

#### Type of Change
- [x] Small bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds new functionality)
- [ ] Breaking change (fix or feature that would change existing functionality)
- [ ] Add new translation (feature adding new translations)

#### Checklist:
- [ ] Tested changes locally.
- [ ] Closes currently open issue (replace XXXX with an issue no): Closes #XXXX

#### Description
This is a port of the changes made by @BerkeleyTrue in #15554 to the staging branch. Because of the differences between the branches, I didn't copy his changes, but ran a replace myself.

### CODE REVIEW

**Comment by JosephLivengood** [comment]
LGTM, I don't see any missing ones!

**Review by JosephLivengood — APPROVED** [review]

**Review by dhcodes — APPROVED** [review]

**Comment by dhcodes** [comment]
**LGTM** as well. Thanks for making these changes @systimotic 🌮 💯 :octocat:

**Comment by BerkeleyTrue** [comment]
@dhcodes Thanks!

@systimotic Nice work!!

**Comment by systimotic** [comment]
Thanks for reviewing everybody!

**Pull request merged**
