### PR TITLE
fix: Updated instructions of  Step 78 of the JavaScript Platformer Game 

### LINKED ISSUE #53538: unclear instructions platformer game step 78
### Describe the Issue

following task ask for : 
` Inside that array, add a boolean expression that checks if the player's y position plus the player's height is less than or equal to the platform's y position. `

reading this line suggests/ indicates to me writing an "if" statement inside of the array although that could be my understanding of the sentence

### Affected Page

https://www.freecodecamp.org/learn/javascript-algorithms-and-data-structures-v8/learn-intermediate-oop-by-building-a-platformer-game/step-78

### Your code

```




```

### Expected behavior

my suggestion would be to update the sentence to the following 

` Populate this array with a boolean expression that evaluates whether the sum of the player's y position and height is less than or equal to the platform's y position `

### Screenshots

_No response_

### System

- Device: [macBook pro]
- OS: [Ventura 13.4.1 ]
- Browser: [chrome ]
- Version: [121.0]

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by developwithabhinav**
Updated the Instructions for step 78 of the platformer game as it was unclear for some learners. Instead of using the *if* statement in the line: 

`Inside that array, add a boolean expression that checks if the player's y position plus the player's height is less than or equal to the platform's y position.`

and changed it to *whether* so, it's not confusing for learners that they have to use it if statement or not

Checklist:

- [x] I have read and followed the [contribution guidelines](https://contribute.freecodecamp.org).
- [x] I have read and followed the [how to open a pull request guide](https://contribute.freecodecamp.org/#/how-to-open-a-pull-request).
- [x] My pull request targets the `main` branch of freeCodeCamp.
- [x] I have tested these changes either locally on my machine, or GitPod.

Closes #53538

### CODE REVIEW

**Review by jdwilkin4 — APPROVED** [review]

**Comment by jdwilkin4** [comment]
HI @developwithabhinav ! 

The changes look good.

Please make sure to fill out the PR template though.
Screenshot 2024-02-06 at 10 56 27 AM

It is important to have complete PRs with all information filled out especially when it comes to larger PR's.

**Comment by developwithabhinav** [comment]
Ok, Jessica, I will fill this in next time. Thank you very much

**Comment by developwithabhinav** [comment]
Ok, I fill in that and will also make sure I don't miss next time. Thank you very much

**Review by Ksound22 — COMMENTED** [review]
I only see a change made to the hint text, not the description.

**Comment by jdwilkin4** [comment]
That's a good catch @Ksound22 ! 

I think we can still keep the change in the hint text

@developwithabhinav  Please update the actual description too

**Pull request closed without merging**
