### PR TITLE
fix(curriculum): stop tests running after navigating away

### LINKED ISSUE #38135: Tests running after navigating away from challenge
**Describe the bug**
Test continue running after the user has left the challenge

**To Reproduce**
1. Go to https://www.freecodecamp.org/learn/coding-interview-prep/algorithms/find-the-symmetric-difference (any js challenge will do, but this one makes it obvious since it has many tests)
2. Enter
```js
for (let i = 0; i < 100000000; i++) {

}
```
3. Click 'Run the Tests'
4. Navigate to any other challenge (click on /learn, then navigate via the curriculum tree)
5. See the test results in the new challenge's console

**Expected behavior**
The tests should be terminated, without console feedback, when the user leaves the challenge.  

**Screenshots**
TestsContinuing

### PR DESCRIPTION
**Pull request by vanya829**
- [x] I have read [freeCodeCamp's contribution guidelines](https://github.com/freeCodeCamp/freeCodeCamp/blob/master/CONTRIBUTING.md).
- [x] My pull request has a descriptive title (not a vague title like `Update index.md`)
- [x] My pull request targets the `master` branch of freeCodeCamp.
- [x] None of my changes are plagiarized from another source without proper attribution.
- [x] All the files I changed are in the same world language (for example: only English changes, or only Chinese changes, etc.)
- [x] My changes do not use shortened URLs or affiliate links.

Closes #38135

### CODE REVIEW

**Review by ojeytonwilliams — APPROVED** [review]
Hey @vanya829 thanks for creating this so quickly.  It's a very elegant solution to the problem.

The only thing I noticed was that the test-evaluator keeps going until it times out.  Ideally it should be terminated when you cancel the task.  It's not really a big problem, though, so please only do it if you think it's a quick and easy fix - what you've done already is already a huge improvement.

**Comment by vanya829** [comment]
> Hey @vanya829 thanks for creating this so quickly. It's a very elegant solution to the problem.
> 
> The only thing I noticed was that the test-evaluator keeps going until it times out. Ideally it should be terminated when you cancel the task. It's not really a big problem, though, so please only do it if you think it's a quick and easy fix - what you've done already is already a huge improvement.

Thanks @ojeytonwilliams . Unfortunately, I'm not familiar with how test-evaluator works. I can investigate it and fix, but can't predict how much time it will take. 
If this fix is not urgent, I can try to fix that. 

Also not sure if it's relevant, but here is the link to docs with the recommendation of how to cancel tasks in sagas https://redux-saga.js.org/docs/advanced/TaskCancellation.html.

**Comment by ojeytonwilliams** [comment]
> If this fix is not urgent, I can try to fix that.

It's not urgent, it's just something that would be nice if possible (I'm not 100% sure it is).  If you're curious, though, the test-evaluator spawns a web worker to run evaluate the tests in.  If the task cancellation could also terminate the worker, that would be ideal.

Worry about it if it proves difficult, since it would only be a small improvement over simply cancelling the task.

**Comment by vanya829** [comment]
Hi @ojeytonwilliams . I checked codebase and found out that we have two different methods for test runners `getJSTestRunner` and `getDOMTestRunner` for different types of challenges. Unfortunately, they don't implement any common interface and don't support any public method for force termination. So I don't see a fast and convenient way to stop them.  Please correct me, if I missed something.

**Comment by ojeytonwilliams** [comment]
Thanks for taking a look and, no, I don't think you're missing anything.  Unfortunately it just is a bit convoluted.

@raisedadead this looks good to me.  If you're happy with it I think it can be merged.

**Review by raisedadead — APPROVED** [review]

**Pull request merged**
