### PR TITLE
chore(i8n,client): processed translations

### PR DESCRIPTION
**Pull request by RandellDawson**
Latest Learn UI translations

### CODE REVIEW

**Comment by RandellDawson** [comment]
@nhcarrigan I ran the download first, then the upload.  I then notice the PR created from the download had the above linting issue.  Since the upload should have pushed the correct files up (I thought), when I ran the download again, I expected the files to have all the same keys.  I must be missing something.

**Comment by nhcarrigan** [comment]
Did you run the download the second time (after the upload?) I'm only seeing one recent Client UI download.

**Comment by RandellDawson** [comment]
I re-ran it by clicking `Re-run jobs`, so I think it just overwrites the last run in history?

**Comment by RandellDawson** [comment]
I will run the download workflow manually one more time now, just to make sure.

**Comment by RandellDawson** [comment]
@nhcarrigan Can this be merged?

**Review by naomi-lgbt — APPROVED** [review]

**Pull request merged**
