### PR TITLE
Format the 'Accessibility Tools for Web Developers' guide article

### PR DESCRIPTION
**Pull request by huyenltnguyen**
- [x] I have read [freeCodeCamp's contribution guidelines](https://github.com/freeCodeCamp/freeCodeCamp/blob/master/CONTRIBUTING.md).
- [x] My pull request has a descriptive title (not a vague title like `Update index.md`)
- [x] My pull request targets the `master` branch of freeCodeCamp.
- [x] None of my changes are plagiarized from another source without proper attribution.
- [x] All the files I changed are in the same world language (for example: only English changes, or only Chinese changes, etc.)
- [x] My changes do not use shortened URLs or affiliate links.

---

This PR formats and fixes some typos in the `Accessibility Tools for Web Developers` guide article.

### CODE REVIEW

**Comment by RandellDawson** [comment]
I don't like the colons at the end.  We don't do that on most headers.

**Comment by huyenltnguyen** [comment]
@RandellDawson I'm not sure what you mean by 'headers'. I thought the colons could be useful as a separator between the tool name and its description

Untitled

**Review by moT01 — COMMENTED** [review]
I was about to close this, but I think it could probably be added - It looks like it improves the article to me. I'll leave it for now.

**Comment by huyenltnguyen** [comment]
The PR includes some capitalization error corrections, so if you're not okay with the colons, I'm happy to revert those changes to get the PR approved.

**Comment by moT01** [comment]
I don't mind the colons

**Review by moT01 — APPROVED** [review]
Looks good @huyenltnguyen - I don't think the colons are a big deal, it looks good either way. Thanks for contributing to freeCodeCamp! 🎉

**Pull request merged**
