### PR TITLE
fixes a test in bonfire-return-largest-numbers-in-arrays

### LINKED ISSUE #2874: [ISSUE] Bonfire: Return Largest Numbers in Arrays
Hi,

Challenge http://www.freecodecamp.com/challenges/bonfire-return-largest-numbers-in-arrays has an issue. Unit tests cannot be executed.

### LINKED ISSUE #2876: Cannot read property 'eql' of undefined
Challenge http://freecodecamp.com/challenges/bonfire-return-largest-numbers-in-arrays has an issue.
The console outputs 'Cannot read property 'eql' of undefined' and the user cant run the code.
I am using chrome.

capture d ecran 2015-08-30 a 13 52 05

### LINKED ISSUE #2882: Can't run this challenge :(
Challenge http://www.freecodecamp.com/challenges/bonfire-return-largest-numbers-in-arrays has an issue. Please describe how to reproduce it, and include links to screenshots if possible.

It doesn't matter what code you write, your get the same error:
Cannot read property 'eql' of undefined

Even chopping the function call to a straight text string gives the same error.

screenshot 2015-08-30 16 52 24

### LINKED ISSUE #2883: Cannot run code on Bonfire: return largest number in arrays
Challenge http://www.freecodecamp.com/challenges/bonfire-return-largest-numbers-in-arrays has an issue. 
The code just outputs: "Cannot read property "should" of undefined. My code is ok.
image

### LINKED ISSUE #2889: There is no user test defined to run the code
numberinarrays
Challenge http://www.freecodecamp.com/challenges/bonfire-return-largest-numbers-in-arrays has an issue. Please describe how to reproduce it, and include links to screenshots if possible.

### PR DESCRIPTION
**Pull request by kamiranoff**
closes #2874 
closes #2876 
closes #2882
closes #2883
closes #2889

### CODE REVIEW

**Comment by BerkeleyTrue** [comment]
Please remove issue numbers from title

see [Pull-Request-Contribute](https://github.com/FreeCodeCamp/FreeCodeCamp/wiki/Pull-Request-Contribute)

**Comment by zoorz** [comment]
The pull-request seems not not work! Maybe you can throught alter the javascript by yourself to going on the challenge!
For Chrome. `F12` and choose the `console` tab. Enter the code below
```
var tests = ["expect(largestOfFour([[4, 5, 1, 3], [13, 27, 18, 26], [32, 35, 37, 39], [1000, 1001, 857, 1]])).to.be.a('array');","assert(largestOfFour([[13, 27, 18, 26], [4, 5, 1, 3], [32, 35, 37, 39], [1000, 1001, 857, 1]]).should.eql([27,5,39,1001]));","assert(largestOfFour([[4, 9, 1, 3], [13, 35, 18, 26], [32, 35, 97, 39], [1000000, 1001, 857, 1]]).should.eql([9,35,97,1000000]));"];

```
after that, run your code!

**Comment by kamiranoff** [comment]
@zoorz it seems to work for me
capture d ecran 2015-08-31 a 17 44 46

**Comment by BerkeleyTrue** [comment]
This has been fixed.

Happy Coding!

**Pull request closed without merging**
