### PR TITLE
fix: project 25 + 5

### PR DESCRIPTION
**Pull request by RandellDawson**
Checklist:

- [x] I have read [freeCodeCamp's contribution guidelines](https://contribute.freecodecamp.org).
- [x] My pull request has a descriptive title (not a vague title like `Update index.md`)
- [x] My pull request targets the `master` branch of freeCodeCamp.
- [x] All the files I changed are in the same world language, for example: only English changes, or only Chinese changes, etc.

@moT01 @scissorsneedfoodtoo @raisedadead @ojeytonwilliams Read about this PR in the team chat.

### CODE REVIEW

**Review by moT01 — CHANGES_REQUESTED** [review]
I was getting `http://localhost:8000/learn/front-end-libraries/front-end-libraries-projects/build-a-25--5-clock` as the URL when running locally. I have made suggestions to adjust it if needed. Not sure if you were getting the same thing or not.

I also noticed the title was not showing up properly in the settings legacy cert area...
Screen Shot 2020-09-07 at 6 52 16 PM

I did some digging and found that [the titles are turned into "start case" here](https://github.com/freeCodeCamp/freeCodeCamp/blob/master/client/src/components/formHelpers/FormFields.js#L48) - which seems to be removing the `+`. Removing that method fixes the issue. I looked around and didn't find and negative side effects of removing the method.

Other than those, I think this looks good 🎉

**Comment by RandellDawson** [comment]
> I did some digging and found that the titles are turned into "start case" here - which seems to be removing the +. Removing that method fixes the issue. I looked around and didn't find and negative side effects of removing the method.

@moT01 Per https://github.com/lodash/lodash/issues/3383, it appears that the method does remove symbol characters.

@ojeytonwilliams @moT01 The lodash `startCase` method was implemented to make sure each first letter of a word was capitalized.  We could use the workaround suggested in the GitHub issue (above) for that repo and use something like the following for [this line of our code](https://github.com/freeCodeCamp/freeCodeCamp/blob/ff8db8ce9e8413f490626e1572e7fd09825db39c/client/src/components/formHelpers/FormFields.js#L48):
```jsx
{name.replace(/\w+/g, _.capitalize)}
```
Let me know and I can push another commit to this PR.

**Comment by ojeytonwilliams** [comment]
Nice catch, Tom.  

> Let me know and I can push another commit to this PR.

Sure, that looks like a good fix.

**Comment by RandellDawson** [comment]
We had to end up reverting back to using `startCase` due to [the issue described here](https://github.com/freeCodeCamp/freeCodeCamp/issues/39546) once PR #39544 was merged.  In order to get these changed merged faster, we will temporarily live with the issue [pointed out by Tom above](https://github.com/freeCodeCamp/freeCodeCamp/pull/39526#pullrequestreview-483738910) for this one particular challenge.

**Review by moT01 — APPROVED** [review]
LGTM 🎉

**Review by ojeytonwilliams — APPROVED** [review]
LGTM :+1: 

@raisedadead I think this is ready to be deployed when you are.

**Pull request merged**
