### PR TITLE
Temporary Fix for voting endpoints

### PR DESCRIPTION
**Pull request by ghost**
Please MERGE ASAP
If you go to either of these routes (**don't**), you lose challenges solutions and your brownie points.

### CODE REVIEW

**Comment by alayek** [comment]
I have tested this manually with a friends account, as well as with campers from main chatroom.

The list of people who has lost their brownie points and progress because of this:

- @atjonathan 
- @brainyfarm
- @keishaSrose
- @KingPixil
- @Siedge
- @alayek
- @ranjanasish

**Comment by bugron** [comment]
Confirmed this bug in my local setup. `/vote1` erased all my brownies and progress.
Merging this PR.

**Comment by brainyfarm** [comment]
Here is screenshots!

before

after

**Comment by Siedge** [comment]
(Additional Screenshots)
Before (Picture I took of reaching 100)
oldstats

After! Yay!!
newstats

**Comment by KingPixil** [comment]
Yeah, I lost my progress, :(

**Comment by BerkeleyTrue** [comment]
EVERYONE
When a security issue has been found (this is a good example)
Do NOT post about it in the public rooms (this room included)
Do NOT test it using the production site.
Do NOT ask others to test it on the production site.
Do NOT create a public PR on main repo until we are ready to test and push to production.
If you see others posting the security issue in public ask them to delete it IMMEDIATELY.
DO inform @QuincyLarson and I PRIVATELY. 
If you have a fix ready please wait for our input before opening up a PR.
It is not a trivial thing for us to restore users data and there is always going to be data loss because we only back up once a day.

**Comment by Siedge** [comment]
@BerkeleyTrue Alright so my 50 something challenges I did today... what will happen to those? :(

**Comment by KingPixil** [comment]
Hey guys, please don't restore my progress, its ok. I just started and had barely done anything anyway 

Just leave it how it is for me, @KingPixil.

**Pull request merged**
