### PR TITLE
Update links to style guide in english/guide/certification stubs

### LINKED ISSUE #35490: Stub links point to the freeCodeCamp/guide repo
**Describe your problem and how to reproduce it:**

Go to a stub page e.g. [this](https://guide.freecodecamp.org/certifications/information-security-and-quality-assurance). The "Help our community expand it." link points to a currently archived repo whereas it should be pointing to `freeCodeCamp/freeCodeCamp/guide`. Same with the "This quick style guide will help ensure your pull request gets accepted." link.

**Add a Link to the page with the problem:**

https://guide.freecodecamp.org/certifications/apis-and-microservices
https://guide.freecodecamp.org/certifications/apis-and-microservices/apis-and-microservices-projects

etc

**Tell us about your browser and operating system:**
* Browser Name: 
* Browser Version: 
* Operating System: 

**If possible, add a screenshot here (you can drag and drop, png, jpg, gif, etc. in this box):**

### PR DESCRIPTION
**Pull request by ryantimjohn**
Stubs link to archived page that does not show style guide. Updated all links.

- [x] I have read [freeCodeCamp's contribution guidelines](https://github.com/freeCodeCamp/freeCodeCamp/blob/master/CONTRIBUTING.md).
- [x] My pull request has a descriptive title (not a vague title like `Update index.md`)
- [x] My pull request targets the `master` branch of freeCodeCamp.
- [x] None of my changes are plagiarized from another source without proper attribution.
- [x] All the files I changed are in the same world language (for example: only English changes, or only Chinese changes, etc.)
- [x] My changes do not use shortened URLs or affiliate links.

Closes #35490

### CODE REVIEW

**Comment by RandellDawson** [comment]
@raisedadead I suggest this gets broken up into multiple PRs, so that the max number of files touched on any PR is 300.  Otherwise, our Moderators tool will not identify all the files affected by this PR.  The GitHub API has a limit of 300 files we can retrieve per PR.

**Comment by raisedadead** [comment]
Even if we broke this up. We would not be able to merge the resulting PRs without conflicting something or the other correct? Which means this may have to wait for thousands of other PRs before going in?

**Comment by raisedadead** [comment]
Hey @ryantimjohn how is this PR different from https://github.com/freeCodeCamp/freeCodeCamp/pull/35599

**Comment by ryantimjohn** [comment]
I resolved merge conflicts that GitHub pointed out; don't know why it
created a separate PR, though.

**Comment by RandellDawson** [comment]
@raisedadead Which is worse, merging one PR and having hundreds of PRs with merge conflicts to resolve or merging thousands of PRs without merge conflicts first and dealing with hundreds merge conflicts on a single PR?  These kinds of PRs which make changes which potentially could result in many PR merge conflicts, should wait until we get the number of PRs down to at least below 500.  This is just my opinion though.

**Comment by RandellDawson** [comment]
@ryantimjohn As we merge earlier PRs than this one, you are going to be fixing merge conflicts for a very long time.  See my last comment.

**Comment by raisedadead** [comment]
> https://github.com/freeCodeCamp/freeCodeCamp/pull/35600#issuecomment-473062421

Yes, I agree with you on this. My question was more of, there is no reason we should split this into multiple PRs, when we are most likely ending up with a conflict anyways.

**Comment by RandellDawson** [comment]
@raisedadead Just to be clear, are you agreeing that we should close this particular PR for now and keep the issue active until we have fewer PRs which would be affected before a PR is created for the issue?

If that is the case, would it not make sense to just fix it at the system level (auto addition of the correct GitHub article and documentation links) and have a PR delete vs. change the existing links?

**Comment by ryantimjohn** [comment]
Makes sense, happy to drop the pull request.

**Comment by raisedadead** [comment]
Hi @ryantimjohn 

Thanks a lot for taking the time to work on this. But it looks like we would have to take a different approach here. Your PR while making a valid change is bit difficult for us to be able to merge at the minute.

We look forward to more contributions from you.

Thanks and happy contributing!

**Pull request closed without merging**
