### PR TITLE
feat(curriculum): set upcoming change flags from blocks 1-4 of the B1 cert to false

### PR DESCRIPTION
**Pull request by DanielRosa74**
Checklist:

- [X] I have read and followed the [contribution guidelines](https://contribute.freecodecamp.org).
- [X] I have read and followed the [how to open a pull request guide](https://contribute.freecodecamp.org/how-to-open-a-pull-request/).
- [X] My pull request targets the `main` branch of freeCodeCamp.
- [X] I have tested these changes either locally on my machine, or GitPod.

### CODE REVIEW

**Review by nieldakarla — APPROVED** [review]

**Review by ojeytonwilliams — CHANGES_REQUESTED** [review]
I see a runtime error, locally. Let me investigate.

**Review by ojeytonwilliams — APPROVED** [review]
I'm approving so I'm not in the way, but please don't merge until https://github.com/freeCodeCamp/freeCodeCamp/pull/57602 is in.

**Comment by ojeytonwilliams** [comment]
Damn you, automerge.

**Comment by ojeytonwilliams** [comment]
Okay, I'm not going to force everyone to go revert and recreate the PR, I'll just let people know not to deploy :cold_face:

**Pull request merged**
