### PR TITLE
Show flash message on every page when cheater is logged in

### LINKED ISSUE #9905: Show Cheater flag on everypage
When a user is flagged as `isCheater` A flash message is shown on their profile when ever someone visits that page. 

We would like to add a the same flash message to every page if the user is marked as a cheater while they are logged in.

### PR DESCRIPTION
**Pull request by bugron**
#### Pre-Submission Checklist

- [x] Your pull request targets the `staging` branch of FreeCodeCamp.
- [x] Branch starts with either `fix/`, `feature/`, or `translate/` (e.g. `fix/signin-issue`)
- [x] You have only one commit (if not, [squash](https://github.com/FreeCodeCamp/FreeCodeCamp/wiki/Git-Squash) them into one commit).
- [x] All new and existing tests pass the command `npm run test-challenges`. Use `git commit --amend` to amend any fixes.
#### Type of Change

- [ ] Small bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds new functionality)
- [ ] Breaking change (fix or feature that would change existing functionality)
- [ ] Add new translation (feature adding new translations)
#### Checklist:

- [x] Tested changes locally.
- [x] Closes currently open issue (replace XXXX with an issue no): Closes #9905
#### Description

Here is a brief explanation of the code:
`ALLOWED_METHODS`: we only care about `GET`, this is an array in case we want to add other methods. Can be replaced by a string if you want.
`EXCLUDED_PATHS`: All those are excluded so we don't flash anything. We hit `/api/flyers/findOne` on every page request and this is excluded as well as `/challenges/current-challenge` because those will lead to duplicate flash messages. `/signout` is excluded to not to show a flash message after a cheater logs out.
`req.url !== '/'` is immediately after `req.user` because when a user is logged in `/` redirects to `/challenges/current-challenge` and that redirects to the current challenge. So we get three `GET` requests and thus three flash messages.
Below are some screenshots:
**Cheaters profile page, cheater is not logged in.**

**Immediately after cheater logged in.**

**Page `About`**

**Page `Shop`**

**Cheaters profile page, cheater is logged in.**

And the same for `Commit` page, setting page and so on.

### CODE REVIEW

**Comment by raisedadead** [comment]
@bugron 

Thanks for the pull request, this looks solid to me. However, can we exclude the map aside from the check?

image


This looks a bit odd to me.

**Comment by raisedadead** [comment]
Also when I move to next challenge after solving it (without dismissing the previous alert) I get this:

image


Somehow we could clear the queue if its the same message?

**Comment by raisedadead** [comment]
And on the `/map` it's positioned bit weirdly:

image

**Comment by raisedadead** [comment]
Debug info:

Windows 7 Professional - Chrome Version 52.0.2743.82 m
Windows 7 Professional - Firefox 45.2 ESR

**Comment by bugron** [comment]
@raisedadead first and second issues are fixed by excluding `/map-aside` and `/challenges/next-challenge`. Not sure what to do with third issue. Flash messages (like `Oops, something went wrong`) are always shown on that position on `/map`. Maybe we need some CSS magic here.

**Comment by raisedadead** [comment]
@bugron oh in that case we will maybe take that in a separate pr. Thanks for updating this. Will check and let you know.

**Comment by raisedadead** [comment]
Other than that CSS issue, LGTM, tested the functional use cases. 
Will let @BerkeleyTrue merge after he has look.

**Comment by BerkeleyTrue** [comment]
LGTM. If QA'd please merge

**Comment by raisedadead** [comment]
@bugron @BerkeleyTrue thanks.

**Comment by bugron** [comment]
@raisedadead @BerkeleyTrue thanks for QA'ing and merging :+1:

**Pull request merged**
