### PR TITLE
Added semicolons to calculator.js

### LINKED ISSUE #15237: Missing semi-colon in calculator.js
#### Issue Description

Missing semi-colons on the below lines of file `public/js/calculator.js`:

https://github.com/freeCodeCamp/freeCodeCamp/blob/staging/public/js/calculator.js#L186
https://github.com/freeCodeCamp/freeCodeCamp/blob/staging/public/js/calculator.js#L203
https://github.com/freeCodeCamp/freeCodeCamp/blob/staging/public/js/calculator.js#L246

Note: Beginner friendly only.

### PR DESCRIPTION
**Pull request by AnishHota**
#### Pre-Submission Checklist

- [x] Your pull request targets the `staging` branch of freeCodeCamp.
- [x] Branch starts with either `fix/`, `feature/`, or `translate/` (e.g. `fix/signin-issue`)
- [x] You have only one commit (if not, [squash](http://forum.freecodecamp.com/t/how-to-squash-multiple-commits-into-one-with-git/13231) them into one commit).
- [x] All new and existing tests pass the command `npm test`. Use `git commit --amend` to amend any fixes.

#### Type of Change

- [x] Small bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds new functionality)
- [ ] Breaking change (fix or feature that would change existing functionality)
- [ ] Add new translation (feature adding new translations)

#### Checklist:

- [x] Tested changes locally.
- [x] Closes currently open issue (replace XXXX with an issue no): Closes #15237

#### Description

Added semicolons on the line 186,203, and 246. This commit doesn't fix a bug as the code works fine without the semicolons but it maintains the consistency.

### CODE REVIEW

**Comment by raisedadead** [comment]
@AnishHota 

Once again thanks for the pull request, but the commit message still needs to be better, removing the reference to line nos.

> 	Added semicolons on line 186,203,246

to maybe:

Add missing semicolons to Calculator.js

Try amending the commit, instead of closing the Pull request this time. Sorry for being picky. But I hope will take this in good spirit.

```sh
git checkout fix/calculator.js
git commit --amend
Edit the commit message
git push origin fix/calculator.js --force
```

Keep up the good work!

**Comment by AnishHota** [comment]
@raisedadead I made the PR through Github interface.Sorry,my fault.Is there any way i can change the commit message?

**Comment by raisedadead** [comment]
@AnishHota you would need to make the change through a local setup.

You can still do that, by cloning your fork as mentioned in the guidelines and then following the steps in the previous comment.

That will update this PR automatically

**Comment by AnishHota** [comment]
@raisedadead Will do it as soon as possible. Thank you for helping me so much.

**Comment by AnishHota** [comment]
@raisedadead I updated the commit message as instructed.Should i make any more changes? Thanks for your help.

**Review by raisedadead — APPROVED** [review]
#### :sparkles: :sparkles: **PERFECT.** :sparkles: :sparkles: 

Thanks @AnishHota 

And congratulations on your first contribution to freeCodeCamp!

Hope to see more from you in future.

**Comment by AnishHota** [comment]
@raisedadead Thank you for guiding me with such patience.Looking forward to contributing more.

**Comment by raisedadead** [comment]
Sure thing @AnishHota always happy to help! Good luck and happy coding!

**Pull request merged**
