### PR TITLE
Easier language for description of Waypoint: Passing Values to Functions with Arguments

### LINKED ISSUE #5800: Use of jargon in Waypoint: Passing Values to Functions with Arguments
This Waypoint uses jargon in a way that newcomers find inaccessible and frustrating.

1) First of all, the explanation uses the term "local variable," which hasn't been defined yet in any of the prior Waypoints. If my recall of the new map serves me, you define it in the *next* Waypoint, so you're essentially using it before you define it. That's a no-no for the purposes of comprehension.

2) The paragraph "Functions can take input with parameters. Parameters are local variables that take on the value of the arguments which are passed into the function" is full of jargon. For seasoned programmers, terms like "take input," "local variables" (see #1 above), "take on the value," and "passed into the function" are straightforward terms; to newcomers who are just seeing an explanation of functions for the first time, this is incomprehensible. Also, it doesn't *clearly* differentiate between parameters and arguments, which I've found that many seasoned programmers confuse or can't distinguish. 

A more straightforward rewriting of the paragraph for newcomers would be something like: "**Parameters** are *variables* that act as placeholders for the values that are to be input to a function when it is called. When a function is defined, it is typically defined along with one or more parameters. The actual *values* that are input (or "passed") into a function when it is called are known as **arguments.**"

This should, of course, be preceded somewhere in the Waypoints by a discussion of functions as input-output machines, rather like the standard explanation of functions in math.

### PR DESCRIPTION
**Pull request by krisgesling**
Replaced existing first sentence:
"Functions can take input with parameters. Parameters are local variables that take on the value of the arguments which are passed into the function."

With user suggested sentence:
"Parameters are variables that act as placeholders for the values that are to be input to a function when it is called. When a function is defined, it is typically defined along with one or more parameters. The actual values that are input (or "passed") into a function when it is called are known as arguments."

closes #5800

### CODE REVIEW

**Comment by SaintPeter** [comment]
It looks like the original first sentence is still there, making it pretty redundant?

**Comment by krisgesling** [comment]
Damn sorry, I've removed the old line now. 

I went through it all a few times as I was figuring out the commit process. Didn't realise you couldn't use the browser editor so went and did it from scratch in c9.io and obviously missed a pretty crucial point.

**Comment by SaintPeter** [comment]
Please [squash your commits](https://github.com/FreeCodeCamp/FreeCodeCamp/wiki/git-rebase#squashing-multiple-commits-into-one).

**Comment by krisgesling** [comment]
woah, I clearly did something wrong - maybe easiest to just reject this PR outright?

I was trying to rebase and clean up the different branches I'd made while messing around in my own repo. Don't really understand how I've pulled in other peoples commits but I don't want to mess with them without knowing 100% what I'm doing is right. 

Very sorry for the mess around everyone!

**Comment by SaintPeter** [comment]
@krisgesling Been there, done that.  Wrote the guide:
https://github.com/FreeCodeCamp/FreeCodeCamp/wiki/How-To-Fork-And-Maintain-a-Local-Instance-of-Free-Code-Camp

Hope that will help!

**Pull request closed without merging**
