### PR TITLE
fix(tools): crowdin log response error

### PR DESCRIPTION
**Pull request by alexandear**
Checklist:

- [x] I have read and followed the [contribution guidelines](https://contribute.freecodecamp.org).
- [x] I have read and followed the [how to open a pull request guide](https://contribute.freecodecamp.org/#/how-to-open-a-pull-request).
- [x] My pull request targets the `main` branch of freeCodeCamp.
- [x] I have tested these changes either locally on my machine, or GitPod.

This PR fixes logging of an Crowdin API response error.

According to the [Crowdin API](https://developer.crowdin.com/api/v2/#operation/api.projects.directories.get), error object consists of `code` and `message`:

image

### CODE REVIEW

**Review by naomi-lgbt — CHANGES_REQUESTED** [review]
These are the old script files - we've been using freecodecamp/crowdin-action for a while now, so I think these files should just be removed.

**Comment by alexandear** [comment]
@naomi-lgbt So, should I just close this PR?

**Comment by naomi-lgbt** [comment]
Yep - this can be closed.

**Comment by Sboonny** [comment]
Although this wasn't merged, you have highlighted an area that was unnecessary, thank you @alexandear.

**Pull request closed without merging**
