### PR TITLE
fix: workflow run errors

### PR DESCRIPTION
**Pull request by naomi-lgbt**
Checklist:

- [X] I have read [freeCodeCamp's contribution guidelines](https://contribute.freecodecamp.org).
- [X] My pull request has a descriptive title (not a vague title like `Update index.md`)
- [X] My pull request targets the `main` branch of freeCodeCamp.
- [X] I have tested these changes either locally on my machine, or GitPod.

Closes #XXXXX

Couple of errors in the workflow runs.

### CODE REVIEW

**Comment by raisedadead** [comment]
Is this ready? Can we remove the comments, etc. if yes?

**Comment by nhcarrigan** [comment]
When https://github.com/freeCodeCamp/crowdin-action/pull/4 is done, I can uncomment the delete step and will be good to go.

**Review by raisedadead — DISMISSED** [review]

**Comment by raisedadead** [comment]
In that case do you want this now?

**Comment by nhcarrigan** [comment]
@raisedadead I've just pushed an update to this to reflect some other fixes in https://github.com/freeCodeCamp/crowdin-action/pull/4 - we would need that one merged prior to landing this.

**Review by raisedadead — APPROVED** [review]

**Pull request merged**
