### PR TITLE
Adjusted comments for Seed to be more clear

### PR DESCRIPTION
**Pull request by CaseyBennington**
- [x] I have read [freeCodeCamp's contribution guidelines](https://github.com/freeCodeCamp/freeCodeCamp/blob/master/CONTRIBUTING.md).
- [x] My pull request has a descriptive title (not a vague title like `Update index.md`)
- [x] My pull request targets the `master` branch of freeCodeCamp.
- [x] None of my changes are plagiarized from another source without proper attribution.
- [x] My article does not contain shortened URLs or affiliate links.

If your pull request closes a GitHub issue, replace the XXXXX below with the issue number.

Closes #XXXXX

### CODE REVIEW

**Comment by RandellDawson** [comment]
After looking at the `Challenge Seed`, it might be as simple as removing the `ourDecimal = 5.7` and just leave the original comment `// Add your code below this line`.  Let's see what other reviewers think.

**Comment by Nirajn2311** [comment]
@RandellDawson The main reason behind `ourDecimal` is to show an example. I think that it's better to remove the `// Example` comment.

**Comment by RandellDawson** [comment]
@Nirajn2311 Maybe the example should be in the Description section and not in the code section?  If we leave the example in the code section, then I think the `// Example` would be a good addition.  Personally, I do not think there even needs to be an example, because I believe the instructions are already clear.

**Comment by Nirajn2311** [comment]
> @Nirajn2311 Maybe the example ... the instructions are already clear.

@RandellDawson You're right, we don't need an example.

<br>

> Maybe the last part of the sentence should be `(example: 5.7).` Not everyone may be familiar with what `e.g.` means.

This could be done 👍 .

**Comment by RandellDawson** [comment]
Thank you for opening this pull request.

This is a standard message notifying you that we’ve reviewed your pull request and have decided not to merge it. We would welcome future pull requests from you.

**Reason:**  Based on the discussion above, your current changes are not needed.   Feel free to create a new PR with the changes suggested above.

Thank you and happy coding.

**Pull request closed without merging**
