### PR TITLE
[Guide]  Functional Programming: Sort an Array Alphabetically using t…

### PR DESCRIPTION
**Pull request by lednhatkhanh**
…he sort Method. Fixes and enhancements.

- [x] I have read [freeCodeCamp's contribution guidelines](https://github.com/freeCodeCamp/freeCodeCamp/blob/master/CONTRIBUTING.md).
- [x] My pull request has a descriptive title (not a vague title like `Update index.md`)
- [x] My pull request targets the `master` branch of freeCodeCamp.
- [x] None of my changes are plagiarized from another source without proper attribution.
- [x] All the files I changed are in the same world language (for example: only English changes, or only Chinese changes, etc.)
- [x] My changes do not use shortened URLs or affiliate links.

### CODE REVIEW

**Comment by lasjorg** [comment]
Should reverseAlpha in the guide be fixed as well?


```
function reverseAlpha(arr) {
  // Add your code below this line
  return arr.sort(function(a,b) {
    return a !== b ? a > b ? -1 : 1 : 0;
  });
  // Add your code above this line
}
```

**Comment by lednhatkhanh** [comment]
@lasjorg Thanks for pointing it out, I'm updating to adapt the change.

**Comment by drecali** [comment]
Hi @lednhatkhanh 

I just noticed that `ascendingOrder` on the challenge page doesn't work in Chrome 70+. If it's changed to a version using a ternary operator similar to `reverseAlpha`, it will work. 

Also, noticed the `ascendingOrder` example in the guide similarly doesn't work in Chrome 70+. The same change as above will make it work.

**Comment by lednhatkhanh** [comment]
@drecali  Sorry but I don't quite understand you.

I'm using Chrome 71 and using the fix in the PR to solve the challenge, I'm using MacOS by the way.

**Comment by lednhatkhanh** [comment]
@drecali I saw your comment in #34543, so since this works on both Chrome and Firefox, should this be accepted or do I need to change anything, thanks.

**Comment by drecali** [comment]
@lednhatkhanh Any code similar to the code below doesn't seem to work for sorting strings on Chrome 70+.

```js
function ascendingOrder(arr) {
  return arr.sort(function(a, b) {
    return a - b;
  });
}
```

I think any code that uses only `a - b`, `a + b`, `a < b` or `a > b` will not for work sorting strings on Chrome 70+. This is why I think all code examples should include the ternary operator ` ? : `, which will also work in Chrome. This would apply to the challenge page and the guide. I would update any code that includes `a - b`, `a + b`, `a < b` or `a > b` to code that instead uses ` ? : `.

### On the challenge page:
__Current:__
```js
function ascendingOrder(arr) {
  return arr.sort(function(a, b) {
    return a - b;  // Doesn't work for strings in Chrome 70+
  });
}
ascendingOrder([1, 5, 2, 3, 4]);
// Returns [1, 2, 3, 4, 5]
```

__Suggestion:__
```js
function ascendingOrder(arr) {
  return arr.sort(function(a, b) {
    return a === b ? 0 : a > b ? 1 : -1;  // Works for strings in Chrome 70+
  });
}
ascendingOrder([1, 5, 2, 3, 4]);
// Returns [1, 2, 3, 4, 5]
```
/curriculum/challenges/english/02-javascript-algorithms-and-data-structures/functional-programming/sort-an-array-alphabetically-using-the-sort-method.english.md

### In the guide:
__Current:__
 ```javascript
 function reverseAlpha(arr) {
   return arr.sort(function(a, b) {
     return a < b;  // Doesn't work for strings in Chrome 70+
   });
 }
 reverseAlpha(['l', 'h', 'z', 'b', 's']);
 // Returns ['z', 's', 'l', 'h', 'b']
```
__Suggestion:__
 ```javascript
 function reverseAlpha(arr) {
   return arr.sort(function(a, b) {
     return a === b ? 0 : a < b ? 1 : -1;  // Works for strings in Chrome 70+
   });
 }
 reverseAlpha(['l', 'h', 'z', 'b', 's']);
 // Returns ['z', 's', 'l', 'h', 'b']
```



/guide/english/certifications/javascript-algorithms-and-data-structures/functional-programming/sort-an-array-alphabetically-using-the-sort-method/index.md

**Comment by lasjorg** [comment]
@lednhatkhanh 

I'm so confused I thought this PR was for the Hint code given when you press the "Get a hint" button and not the actual assignment text. That is what I meant by the guide, not the assignment text, which (i think) has been fixed already by https://github.com/freeCodeCamp/freeCodeCamp/pull/25978 sorry for any confusion I have caused.

@drecali see my response here https://github.com/freeCodeCamp/freeCodeCamp/issues/25829

Can somebody help me understand where the guides from the now archived guides repo are in this new monorepo? Surely the "Get a hint" text needs updating as well.

**Review by ezioda004 — APPROVED** [review]

**Pull request merged**
