### PR TITLE
Feat(Nav): Responsive Nav with promonent Bin buttons

### LINKED ISSUE #15710: JSBin-like pane control navigation button bar
Currently the beta navigation looks like this: 

basic_html_and_html5__headline_with_the_h2_element___freecodecamp

We want to overhaul the navigation buttons control what's shown to look more like JSBin.com:

js_bin_-_collaborative_javascript_debugging_

This should be right-adjusted in the navbar to make room for the forthcoming search bar.

This style of button is also commonly referred to as "pills." These would need to be able to change to an active state when the pane is open.

### PR DESCRIPTION
**Pull request by Bouncey**
#### Pre-Submission Checklist

- [x] Your pull request targets the `staging` branch of freeCodeCamp.
- [x] Branch starts with either `fix/`, `feature/`, or `translate/` (e.g. `fix/signin-issue`)
- [ ] You have only one commit (if not, [squash](http://forum.freecodecamp.org/t/how-to-squash-multiple-commits-into-one-with-git/13231) them into one commit).
- [x] All new and existing tests pass the command `npm test`. Use `git commit --amend` to amend any fixes.

#### Type of Change

- [ ] Small bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds new functionality)
- [ ] Breaking change (fix or feature that would change existing functionality)
- [ ] Add new translation (feature adding new translations)

#### Checklist:

- [x] Tested changes locally.
- [ ] Addressed currently open issue (replace XXXXX with an issue no in next line)

Closes #15710

#### Description

anim

### CODE REVIEW

**Comment by sdd67** [comment]
Чт

**Comment by QuincyLarson** [comment]
@BerkeleyTrue How does this look from your end? Functionality looks fine to me.

**Comment by BerkeleyTrue** [comment]
I'm curious about the choice to use a react component for this instead of using plain old css media queries. Css is an order of magnitude less expensive and much faster than waiting for a react render cycle.

**Comment by QuincyLarson** [comment]
@BerkeleyTrue This sounds like something we should refactor after we ship beta. If it otherwise looks good, can we merge and deploy?

**Comment by Bouncey** [comment]
I used `react-media` because I couldn't think of a cleaner way to move
components around in the dom.

There is nothing magic going on, it just wraps `window.matchMedia` for
consumption in react.

With respect to waiting on render cycles, how often are we expecting the
user to resize their window? It is possible that we can guestimate the
correct nav on the server by sniffing the user-agent. But I think that
should be a follow up PR.

**Review by BerkeleyTrue — APPROVED** [review]

**Pull request merged**
