### PR TITLE
Added Step to depict issues with API Calls and CodePen Live Updating

### LINKED ISSUE #5460: Advise users to turn off autorun on Codepen when doing Ajax Ziplines
By default, Codepen reloads the page automatically when your code changes. While this is usually a useful feature, when doing Ajax requests it can easily lead to an external API being hammered unintentionally, often resulting in the developer being blocked temporarily from making further successful requests (may have to wait an hour or two, or even a day before it works again, depending on the API).

After diagnosing someone having this issue in the chat, and after having it myself in the past, it seems a good idea to advise users to turn off this feature for Ziplines where Ajax calls are being made, in order to prevent the frustration and confusion that can result. This can be achieved by going to "Settings" > "Behavior" and unchecking "AUTO UPDATE PREVIEW". Doing this makes a "run" button appear where the pen can be reloaded manually instead.

If we want to go a step further, it should also be mentioned that using local sample data when possible during development is a good practice, save for when actual requests are needed.

### PR DESCRIPTION
**Pull request by matthewfortier**
#### Pre-Submission Checklist

- [x] Your pull request targets the `staging` branch of FreeCodeCamp.
- [x] Branch starts with either `fix/`, `feature/`, or `translate/` (e.g. `fix/signin-issue`)
- [x] You have only one commit (if not, [squash](https://github.com/FreeCodeCamp/FreeCodeCamp/wiki/git-rebase#squashing-multiple-commits-into-one) them into one commit).
- [x] All new and existing tests pass the command `npm run test-challenges`. Use `git commit --amend` to amend any fixes.
#### Type of Change

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] Add new translation (feature adding new translations)
#### Checklist:

- [x] Tested changes locally.
- [x] Closes currently open issue (`Closes #XXXX`): Closes 
#### Description

I first made a gif using LICEcap v1.26 showing how to disable automatic preview updating in CodePen, and uploaded it to imgur http://imgur.com/NU1KOzR. I then edited the basic-ziplines.json file under seed/challenges/01-front-end-development-certification. Here I added a note about why APIs shouldn't be called over and over, and detailed how to turn off automatic updating in CodePen so that doesn't happen. I ran all the tests locally and everything passed with flying colors. Have yet to add additional languages.

closes #5460

### CODE REVIEW

**Comment by raisedadead** [comment]
@matthewfortier Thanks for the PR.

This looks good but, just being picky, shouldn't the GIFcontain explicitly saving the Pen as well, and not just clicking `Run` ?

**Comment by matthewfortier** [comment]
I can remake the GIF with the user saving as well and resubmit the PR a little later. Thanks for the reply!

**Comment by matthewfortier** [comment]
Should be all set!

**Comment by raisedadead** [comment]
#### :sparkles: :sparkles: **Awesome.** :sparkles: :sparkles: 

Thanks for the PR @matthewfortier .

**Pull request merged**
