### PR TITLE
Fix capitalization

### PR DESCRIPTION
**Pull request by SudhakarKuma**
- [x] I have read [freeCodeCamp's contribution guidelines](https://github.com/freeCodeCamp/freeCodeCamp/blob/master/CONTRIBUTING.md).
- [x] My pull request has a descriptive title (not a vague title like `Update index.md`)
- [x] My pull request targets the `master` branch of freeCodeCamp.
- [x] None of my changes are plagiarized from another source without proper attribution.
- [x] My article does not contain shortened URLs or affiliate links.

If your pull request closes a GitHub issue, replace the XXXXX below with the issue number.

Closes #XXXXX

### CODE REVIEW

**Comment by lynxlynxlynx** [comment]
Thanks for going through the texts. Two notes:
1. There are several thousands of similar PRs before yours, so the work may be in vain in the end (someone may have already done it, conflicts could arise). I suggest you wait with your contributions while we deal with the backlog.
2. You can push several commits to the same PR, there's no need to have 10, all with small typo fixes.

**Comment by farisoft** [comment]
Good contribution, and merging this up! @SudhakarKuma 
Also, do take into consideration of what @lynxlynxlynx is mentioning on the Squash PRs.

**Comment by SudhakarKuma** [comment]
@lynxlynxlynx Thank you for your comments. Can you please educate me on how to push several commits to the same PR?

**Comment by lynxlynxlynx** [comment]
You just push to the same branch you created the first one on. So unless you moved away (checked out another one), you'd just continue your work in the same way as before.

**Comment by SudhakarKuma** [comment]
@lynxlynxlynx Thank you for your suggestions. I will follow this for next commits.

**Pull request merged**
