### PR TITLE
fix(cypress): disable electron due to timeouts

### PR DESCRIPTION
**Pull request by raisedadead**

### CODE REVIEW

**Comment by ShaunSHamilton** [comment]
Mrugesh, what is the thought with this being a draft? Can we continue to ignore it when QAing PRs?

**Comment by raisedadead** [comment]
I prefer starting off as a draft ("Open PR as Draft" button) to help prevent bothering the team. The checks have passed this is good to go.

Now please bless it with a merge so I am not getting those Cypress notifications which are all @ojeytonwilliams's fault.

**Comment by nhcarrigan** [comment]
It's been a while, but I vaguely remember adding electron to catch specific edge cases that didn't show up on firefox/chrome.

**Comment by raisedadead** [comment]
> Or... we could fix them?

By all means, if you can in a follow-up PR. 

At this very moment it's gotten very noisy as you may have seen with my repeated requests in the Chat (over the long weekend) 😞

**Review by naomi-lgbt — APPROVED** [review]
TODO: fix it

**Review by ShaunSHamilton — APPROVED** [review]
chore(cypress): fix tests by removing tests

**Pull request merged**
