### PR TITLE
update directions on guide files location

### PR DESCRIPTION
**Pull request by ajwallacemusic**
changed 'pages' folder to the 'guide' folder within the repo per the guide index restructure. Also including gif in PR comment.

how-to-edit-guides-github-web-interface

- [x] I have read [freeCodeCamp's contribution guidelines](https://github.com/freeCodeCamp/freeCodeCamp/blob/master/CONTRIBUTING.md).
- [x] My pull request has a descriptive title (not a vague title like `Update index.md`)
- [x] My pull request targets the `master` branch of freeCodeCamp.
- [x] None of my changes are plagiarized from another source without proper attribution.
- [x] My article does not contain shortened URLs or affiliate links.

If your pull request closes a GitHub issue, replace the XXXXX below with the issue number.

Closes #XXXXX

### CODE REVIEW

**Comment by RandellDawson** [comment]
What do you mean by "Also including gif in PR comment."?

**Comment by ajwallacemusic** [comment]
@RandellDawson I noticed there is a TODO to update the gif showing how to navigate and edit a document in the github interface, but I'm not sure where to upload images in the code, so I attached it to the PR comment. Happy to open a different PR for the gif if I know where to upload.

**Comment by moT01** [comment]
looking at the other image in this file, it looks like someone just posted it on gitter and used that link...
`GIF - Squash and merge` - im not sure if that's the best solution, perhaps gitter deletes them after some time or something

**Comment by moT01** [comment]
@ajwallacemusic can you add the gif to the PR? use the link from this post... https://user-images.githubusercontent.com/24554274/47116186-82cf1600-d226-11e8-90b1-a26d3ded404d.gif

**Review by ajwallacemusic — COMMENTED** [review]
added gif copied from medium post for how to use github interface to edit guides

**Comment by ajwallacemusic** [comment]
Thanks @moT01, that medium post gif is perfect, added to PR.

**Comment by cmccormack** [comment]
This looks great to me.  Thank you for your contribution!

**Pull request merged**
