### PR TITLE
Update create-a-row-gap-using-grid-row-gap.md

### PR DESCRIPTION
**Pull request by Dev-Bhojak**
updated sentence structure for clarity

Checklist:

- [x] I have read [freeCodeCamp's contribution guidelines](https://contribute.freecodecamp.org).
- [ ] My pull request has a descriptive title (not a vague title like `Update index.md`)
- [x] My pull request targets the `main` branch of freeCodeCamp.
- [ ] I have tested these changes either locally on my machine, or GitPod.

Closes #XXXXX

### CODE REVIEW

**Review by moT01 — COMMENTED** [review]
I'm not sure this change is necessary - I think it's fine how it is. I would vote to not add this change.

**Review by gikf — COMMENTED** [review]
One advantage would be having the same wording as in the preceding challenge -https://www.freecodecamp.org/learn/responsive-web-design/css-grid/create-a-column-gap-using-grid-column-gap

But I'd agree current wording is also fine.

**Comment by moT01** [comment]
I'm fine with adding it, too. If you are leaning that way @gikf, we can just add it. Either way works for me.

**Comment by Sembauke** [comment]
Please read our [contributor's guide](https://contribute.freecodecamp.org) and update the title.

Have a nice day and happy coding :)

**Comment by raisedadead** [comment]
I am going to go ahead and close this as is. The current verbiage seems OK to me. Thanks for your contributions. Looking forward to more.

**Pull request closed without merging**
