### PR TITLE
fix(curriculum): fixed typo in task 61 in conversation starters

### LINKED ISSUE #53777: typo - English for developers - 3rd chapter, Task 61 - happen not happens
### Describe the Issue

In task 61, the last word of the first sentence is missing the letter S at the end.
Should read happens, not happen.

### Affected Page

https://www.freecodecamp.org/learn/a2-english-for-developers/learn-conversation-starters-in-the-break-room/task-61

### Steps to Reproduce

-proceed to 3rd chapter, task 61
-observe the first sentence

### Recommended fix or suggestions

Please change the first sentence to:
There are some words you can use in your sentence to express how often something happens.

### Screenshots

happens

### PR DESCRIPTION
**Pull request by ssenthilnathan3**
changed "happen" to "happens"

Checklist:

- [x] I have read and followed the [contribution guidelines](https://contribute.freecodecamp.org).
- [x] I have read and followed the [how to open a pull request guide](https://contribute.freecodecamp.org/#/how-to-open-a-pull-request).
- [x] My pull request targets the `main` branch of freeCodeCamp.
- [x] I have tested these changes either locally on my machine, or GitPod.

Closes #53777

### CODE REVIEW

**Comment by jdwilkin4** [comment]
@ssenthilnathan3 

Please update your PR title to something more descriptive.
Here is a better title to use:

```md
fix(curriculum): fixed typo in task 61 in conversation starters
```

**Comment by ssenthilnathan3** [comment]
Sorry, this is my first PR. Thanks for the guidance.

**Review by gikf — APPROVED** [review]

**Review by jdwilkin4 — APPROVED** [review]
Congrats on your first contribution to our repository. 🎉
We look forward to future contributions. 👍

**Comment by ssenthilnathan3** [comment]
Thank you so much 👍🏾

**Pull request merged**
