### PR TITLE
fix(curriculum): look for inlined filter function

### LINKED ISSUE #41951: Stacked Methods Do Not Pass with removeJSComments
Challenge: https://www.freecodecamp.org/learn/javascript-algorithms-and-data-structures/functional-programming/use-the-filter-method-to-extract-data-from-an-array

Forum post: https://forum.freecodecamp.org/t/bug-found-in-this-challenge/458226

Is some part of the code processing chain causing this challenge to fail with the following code?

This fails

```
var filteredList = watchList.map(movie => ({
   title: movie["Title"],
   rating: movie["imdbRating"]
}))
.filter(r => {
  return parseFloat(r.rating) >= 8.0;
})
```

This passes:
```
var filteredList = watchList.map(movie => ({title: movie["Title"],rating: movie["imdbRating"]})).filter(r => {
  return parseFloat(r.rating) >= 8.0;
})
```

The match for .filter is failing. But it doesn't seem to me like it should be the regex that is the issue `assert(code.match(/\.filter/g));` so maybe we inadvertently broke something, somehow?

### PR DESCRIPTION
**Pull request by Sembauke**
Checklist:

- [x] I have read [freeCodeCamp's contribution guidelines](https://contribute.freecodecamp.org).
- [x] My pull request has a descriptive title (not a vague title like `Update index.md`)
- [x] My pull request targets the `main` branch of freeCodeCamp.
- [x] All the files I changed are in the same world language, for example: only English changes, or only Chinese changes, etc.

Closes #41951

### CODE REVIEW

**Review by naomi-lgbt — APPROVED** [review]
It makes 0 sense to me that the original regex wasn't working (it even works for the code snippet on tools like Regex101).

But the new regex does work for the linked issue's code snippet, so LGTM.

**Comment by Sembauke** [comment]
> It makes 0 sense to me that the original regex wasn't working (it even works for the code snippet on tools like Regex101).
> 
> But the new regex does work for the linked issue's code snippet, so LGTM.

Yes it's very weird I don't understand it either

**Comment by ShaunSHamilton** [comment]
Sorry all, I should have seen this coming: https://github.com/freeCodeCamp/freeCodeCamp/issues/39925

**Comment by Sembauke** [comment]
> Sorry all, I should have seen this coming: #39925

@ShaunSHamilton  What do you suggest here?

**Comment by lasjorg** [comment]
I'm not sure "fixing" this by masking what is actually causing the bug is such a good idea. Shouldn't the root cause be fixed instead?

**Comment by ShaunSHamilton** [comment]
@lasjorg and @Sembauke If you look at the linked issue, it is labelled with _won't fix_. Unfortunately, without diving deep into Babel's AST and reconfiguring it, it is best just to use the smaller fixes - like this. I suggest we reopen this PR.

**Comment by nhcarrigan** [comment]
My review seems to still be in effect 😉

**Review by ShaunSHamilton — APPROVED** [review]
TLGTM 👍 . I am approving because it resolves the issue.

The `\s*` before the `.` really should not be necessary, unless I missed something weird.

**Pull request merged**
