### PR TITLE
Adding docs for Ruby

### PR DESCRIPTION
**Pull request by asbarron**
- [x] I have read [freeCodeCamp's contribution guidelines](https://github.com/freeCodeCamp/freeCodeCamp/blob/master/CONTRIBUTING.md).
- [x] My pull request has a descriptive title (not a vague title like `Update index.md`)
- [x] My pull request targets the `master` branch of freeCodeCamp.
- [x] None of my changes are plagiarized from another source without proper attribution.
- [x] My article does not contain shortened URLs or affiliate links.

If your pull request closes a GitHub issue, replace the XXXXX below with the issue number.

Closes #XXXXX

### CODE REVIEW

**Comment by RandellDawson** [comment]
Why have you tried to add a folder named mock-guide?
> mock-guide/english/ruby/index.md

**Comment by mztriz** [comment]
@RandellDawson I didn't add a folder named mock-guide, that already exists. https://github.com/mztriz/freeCodeCamp/tree/master/mock-guide/english

**Comment by honmanyau** [comment]
@RandellDawson I found a few unlabelled files that target the `mock-guide` directory and I'm fairly convinced it was introduced into production by mistake. Waiting for a response on it and will provide an update!

In any case, @mztriz I have closed this PR because most of the content is copied verbatim from other sources and mostly covered in the article for Ruby in the `guide` directory.

**Comment by honmanyau** [comment]
Note for collaborators: this PR was not reviewed in order because it was not labelled by the bot.

**Pull request closed without merging**
