### PR TITLE
Fixed broken img link

### PR DESCRIPTION
**Pull request by drecali**
Just changed URL from http to https. Before this, the image link did not work.

- [x] I have read [freeCodeCamp's contribution guidelines](https://github.com/freeCodeCamp/freeCodeCamp/blob/master/CONTRIBUTING.md).
- [x] My pull request has a descriptive title (not a vague title like `Update index.md`)
- [x] My pull request targets the `master` branch of freeCodeCamp.
- [x] None of my changes are plagiarized from another source without proper attribution.
- [x] My article does not contain shortened URLs or affiliate links.

### CODE REVIEW

**Comment by honmanyau** [comment]
@drecali Thank you very much for submitting a pull request (PR) to change an image URL from using the HTTP protocol to using the preferred HTTPS protocol. I have merged the PR but, in light of the series of PRs that you have submitted, and for future reference, please combine minor changes of the same type into one PR to make things easier for maintainers. That way it also makes things fairer for other contributors during Hacktoberfest:

> ### Quality Standards
> In line with Hacktoberfest value `#2` (Quantity is fun, Quality is key), we have provided examples of the quality standards we encourage. This applies mainly to beginners.
> 
> - PRs that are automated e.g. scripted opening PRs to remove whitespace / optimize images.
> - PRs that are disruptive e.g. taking someone else's branch/commits and making a PR.
> - PRs that are regarded by a project maintainer as a hindrance vs. helping.
> - Something that's clearly an attempt to simply +1 your PR count for October.

Learn more at https://hacktoberfest.digitalocean.com/details

**Comment by drecali** [comment]
@honmanyau Do you mean that I can make multiple changes across different files in different folders and submit them together as one PR? I didn't know that was possible. Sorry, I will do that from now on. Thanks for the heads up!

**Comment by honmanyau** [comment]
@drecali Yup! You can indeed submit a PR that contains changes in multiple files! And no need to be sorry! Happy Hacktoberfest! ☀️

**Comment by drecali** [comment]
@honmanyau Thanks! I was using the web interface to do my PRs. Do you know if it's possible to do a PR with multiple changed files that way, or do I have to do it the old-fashioned way with a local copy of the repository?

**Comment by honmanyau** [comment]
@drecali Many apologies for the late reply! Another issue came up on something related to this and I suddenly remembered that I read your message when I was in the middle of something and forgot to reply!

You can indeed combine commits into a single PR through using only the GitHub interface by doing the following:

1. Navigating to your fork's home page
2. Select a branch that you have created using the drop down menu on (either by creating it yourself or created as a result of editing a file)
3. While under that branch, you can edit other files and commit those changes to the same branch
4. Once you are done editing, navigate back to your fork's home page
5. Make sure that you are still on the branch that you want to submit a PR with
6. Click on "Create Pull Request"

I think a local copy is probably easier in most cases, though, if you are already familiar with using the git CLI. :)

I hope that helps! Happy coding!

**Comment by drecali** [comment]
@honmanyau Thanks so much! I'll try that. Once more potentially silly question: do I need to do something to ensure my branch is up to date with the `master` branch (except for my edits?) If there are other PRs that get accepted into the `master` branch after I create my branch, will they be reflected in my branch, or do I need to do something to update my branch before submitting the PR with the changes I've made. Sorry for all the questions. I'm very new to Git collaboration. Mostly I've just used it on my own, so never had to deal with these issues.

**Comment by honmanyau** [comment]
@drecali Not a silly question at all, it's probably something I should have mentioned as updating your fork is important.

You can do this locally (which I feel is easier) by following the instructions in the **Making changes to your clone of freeCodeCamp locally** section in [this guide](https://github.com/freeCodeCamp/freeCodeCamp/blob/master/docs/how-to-setup-freecodecamp-locally.md).

You could also do this using the GitHub interface in a similar fashion to the steps described in my previous message. In this case, you press the "New Pull Request" button either in your fork or the main repo and you'll be brought to the same interface that you see in Step 7. Instead of creating a PR from your fork to the main repo, you simply switch `freeCodeCamp/freeCodeCamp: master` and `drecali/freeCodeCamp: fix/my-branch-name` around (if you don't get to select forks and branches, click on "compare across forks" close to the top of the page).

Once you have created a PR, go back to your own fork and you should see it under the "Pull requests" tab (from memory a notification also pops up). From there, simply double check the PR and merge it into your own fork. Your fork should then be up to date. :)

I hope that helps!

**Comment by drecali** [comment]
@honmanyau thanks again! Your explanation and the link are very helpful. Thank you got taking the time to explain :-D

**Comment by honmanyau** [comment]
@drecali You are welcome. :)

**Pull request merged**
