### PR TITLE
Added hints and solutions to Redux exercises

### PR DESCRIPTION
**Pull request by RamyasreeSiri**
solution to Redux exercise: Copy an Object with Object.assign

- [x] I have read [freeCodeCamp's contribution guidelines](https://github.com/freeCodeCamp/freeCodeCamp/blob/master/CONTRIBUTING.md).
- [x] My pull request has a descriptive title (not a vague title like `Update index.md`)
- [x] My pull request targets the `master` branch of freeCodeCamp.
- [x] None of my changes are plagiarized from another source without proper attribution.
- [x] All the files I changed are in the same world language (for example: only English changes, or only Chinese changes, etc.)
- [x] My changes do not use shortened URLs or affiliate links.

Closes #XXXXX

### CODE REVIEW

**Comment by RandellDawson** [comment]
@RamyasreeSiri Thank you for creating this PR.  Please add the full code for the solution and not just the part that needs to be added.  We want the user to be able to copy/paste the solution into the FCC editor and the solution pass.  Plus, this makes it easier for us to validate the provided code works as we will do the same thing when reviewing to validate the solution passes all the tests

Thank you.

**Comment by RamyasreeSiri** [comment]
@RandellDawson thankyou for reviewing, added the full code in the solution.

**Comment by RamyasreeSiri** [comment]
@RandellDawson, excuse me for questioning, but may I know if there is any mistakes in the committed code since it is not being merged.

**Comment by RandellDawson** [comment]
@RamyasreeSiri We have a backlog of 3800+ PRs, so the final review will take place at some point in the future.  Some PRs are 2-3 months old.

**Comment by RandellDawson** [comment]
Congrats @RamyasreeSiri on your first pull request (PR)! 🎉

Thank you for your contribution to the page! 👍
We're happy to accept these changes, and look forward to future contributions. 📝

**Pull request merged**
