### PR TITLE
fix: fixed responsiveness of certificate in small devices

### LINKED ISSUE #51926: Certificate is not responsive for small screen devices
### Describe the Issue

# Certificate is not responsive for small screen devices

here is screenshot of this certificate on small device
d

### Affected Page

https://www.freecodecamp.org/certification/Chetan-KK/javascript-algorithms-and-data-structures

### Steps to Reproduce

1. Go to '[certificate page](https://www.freecodecamp.org/certification/Chetan-KK/javascript-algorithms-and-data-structures)'
3. Scroll down to 'Certificate'

### Expected behavior

- certificate should not need to be responsive it should be in same format for all screen sizes

### Screenshots

d

### System

- Device: [Realme X2]
- OS: [android 11]
- Browser: [Chrome]
- Version: [116.0.5845.164]

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by Chetan-KK**
fix: 

Checklist:

- [x] I have read and followed the [contribution guidelines](https://contribute.freecodecamp.org).
- [x] I have read and followed the [how to open a pull request guide](https://contribute.freecodecamp.org/#/how-to-open-a-pull-request).
- [x] My pull request targets the `main` branch of freeCodeCamp.
- [x] I have tested these changes either locally on my machine, or GitPod.

Closes #51926 

### screenshot
Untitled

- updated media query to change sizes of fonts to perfect size
- signature doesn't overlap now

### CODE REVIEW

**Comment by Sembauke** [comment]
Hey @Chetan-KK,

please read [how to open a pull request](https://contribute.freecodecamp.org/#/how-to-open-a-pull-request) 

hint: title

**Comment by Chetan-KK** [comment]
hello, @Sembauke, i've updated title of PR

**Comment by Chetan-KK** [comment]
hello @Sembauke

**Comment by lasjorg** [comment]
I'm not sure if we can accept this solution. 

https://www.w3.org/WAI/WCAG21/Techniques/failures/F94.html

If we do use fluid typography it should be using a better method and it should be tested with page and text zoom/enlargement.

https://adrianroselli.com/2019/12/responsive-type-and-zoom.html

https://www.w3.org/WAI/WCAG21/Understanding/resize-text


---


If we want to use a font-size solution I think just lowering them a bit in the media query would work as well. The page content (table at the bottom) is already overflowing at 360px.


Example suggestion:
```
.certification-namespace .information {
  min-height: 380px;
  text-align: center;
}

.certification-namespace .information-container {
  padding-top: 4rem;
  margin: 0px 100px;
}


@media screen and (max-width: 675px) {
  .certification-namespace header {
    height: 100px;
  }

  .certification-namespace h3,
  .certification-namespace h4 {
    font-size: 1rem;
  }

  .certification-namespace h1 {
    font-size: 1.2rem;
  }
}
```

**Comment by bbsmooth** [comment]
I agree with @lasjorg, I would stay away from using view port units for font sizes. I know that we might want this text to center nicely at all times and look exactly the same no matter what view port width or zoom factor the page is being viewed with, but I think we need to let go of being "pixel perfect", especially for the extreme situations. As suggested, we can definitely make the font size smaller for narrow view ports (there is no minimum font size requirement in WCAG).

Just to give a concrete example of how this PR currently fails SC 1.4.4 Resize Text. If you narrow your browser window all the way in (mine goes to `450px`) and then start zooming in, you will notice that most of the text at the top of the certificate never gets bigger due to it being tied to the view port width. Thus, there is no way for the user to increase the text size by 200%.

**Comment by Amit-Morade** [comment]
Can I work on this?

**Comment by lasjorg** [comment]
@Amit-Morade It is already being worked on in this PR.

**Pull request closed without merging**
