### PR TITLE
breaking(curriculum): add scientific-computing to /learn (#53143)

### PR DESCRIPTION
**Pull request by ShaunSHamilton**
Moves all scientific-and-computing-python certification projects to be completable on `/learn`.

New challenge type (`multifilePythonCertProject`) is `23`.

As far as I am aware, because we guarantee the api is built/released before the client, this change should be fine to include in one release, because an old client can still _hit_ the new API without error.

### CODE REVIEW

**Comment by ojeytonwilliams** [comment]
https://github.com/freeCodeCamp/freeCodeCamp/pull/53377 and  https://github.com/freeCodeCamp/freeCodeCamp/pull/53375 together should fix the failing tests in this PR.

https://github.com/freeCodeCamp/freeCodeCamp/pull/53377 is unrelated to this PR (it's broken in main) and  https://github.com/freeCodeCamp/freeCodeCamp/pull/53375 is only indirectly related, so I figured they both deserved to be in their own PRs.

**Review by ojeytonwilliams — CHANGES_REQUESTED** [review]
@ShaunSHamilton the project block was displaying as a grid, hence my latest commit.

It's looking good, though. Just one tiny thing:

**Comment by ShaunSHamilton** [comment]
Test passed locally. So, I am running them again.

**Review by ojeytonwilliams — APPROVED** [review]
LGTM :crossed_fingers:

**Review by moT01 — COMMENTED** [review]
I didn't give this a full review, but I checked it out and ran it - it seems to introduce some weird scrolling behavior on the superblock pages. When I go to one of the superblock pages and scroll down so that the top of my page is in the middle of one of the blocks, it auto-scrolls to the top of the block. I think it would be a frustrating experience.

**Comment by ojeytonwilliams** [comment]
I believe that's been around for a while.

@ShaunSHamilton didn't you look into that once?

**Comment by moT01** [comment]
I couldn't reproduce it on production or main.

**Comment by ShaunSHamilton** [comment]
> @ShaunSHamilton didn't you look into that once?

Yes, I looked into it years ago when we made a huge feature claiming certs from the superblock page, but that got reverted after a bit, and the issue disappeared.

But I have reproduced this on `main` before (this week and last). I still suspect this is an issue with our state and the donation modal.

**Comment by moT01** [comment]
I know there's some other scrolling issues on those pages from time to time - like maybe when you finish a project and get taken back there or when the donation modal shows up or something. To be sure we are talking about the same thing, this is what I see (I only ever scroll down the page - all the scrolling up is not from me):

<details><summary>gif</summary>

Jan-31-2024 13-59-49

</details>

I reverted the changes in `block.tsx` and the issue went away.

**Comment by ojeytonwilliams** [comment]
> I reverted the changes in block.tsx and the issue went away.

Huh. I meant that to be a trivial refactor. We can revert that, it doesn't matter much.

**Comment by ShaunSHamilton** [comment]
Ah. Thanks for the gif. I was not talking about that. I never noticed that before.

**Review by moT01 — APPROVED** [review]
🎉

**Pull request merged**
