### PR TITLE
fix:guide - Changed the users to obj

### PR DESCRIPTION
**Pull request by Vikas-KM**
- [x] I have read [freeCodeCamp's contribution guidelines](https://github.com/freeCodeCamp/freeCodeCamp/blob/master/CONTRIBUTING.md).
- [x] My pull request has a descriptive title (not a vague title like `Update index.md`)
- [x] My pull request targets the `master` branch of freeCodeCamp.
- [x] None of my changes are plagiarized from another source without proper attribution.
- [x] All the files I changed are in the same world language (for example: only English changes, or only Chinese changes, etc.)
- [x] My changes do not use shortened URLs or affiliate links.

Closes #XXXXX

### CODE REVIEW

**Comment by RandellDawson** [comment]
@Vikas-KM Thank you for opening this pull request.

Your changes to the Guide article for the `Check if an Object has a Property` challenge do not change the solution for the better, because the existing solutions (1 and 2) and your change do not actually fulfill the challenge instruction requirements.  The tests do pass with the solutions, due to a bug in the tests for the challenge.  PR (#19477) is working on a fix for the challenge, so that it will correctly test for a valid solution to this particular challenge.  Once that PR is merged, feel free to update the Guide article with a valid solution.

As far as your changes to the `Use the Map Method to Extract Data from an Array` challenge, can you explain why you think this helps the challenge?

**Comment by Vikas-KM** [comment]
> @Vikas-KM Thank you for opening this pull request.
> 
> Your changes to the Guide article for the `Check if an Object has a Property` challenge do not change the solution for the better, because the existing solutions (1 and 2) and your change do not actually fulfill the challenge instruction requirements. The tests do pass with the solutions, due to a bug in the tests for the challenge. PR (#19477) is working on a fix for the challenge, so that it will correctly test for a valid solution to this particular challenge. Once that PR is merged, feel free to update the Guide article with a valid solution.
> 
> As far as your changes to the `Use the Map Method to Extract Data from an Array` challenge, can you explain why you think this helps the challenge?

The changes to the guide article 'Check if an Object has a Property' doesnot not change solution, I just replaced the users with obj since the function received obj as an argument. I checked the solution once again and i see that hasOwnProperty with all 4 arguments will return true even if one property name matches.
I am attaching a solution with screenshot to improve it.

about : `Use the Map Method to Extract Data from an Array` challenge
I am little confused as i had opened a PR for that, I don't understand how it is also here, I am doing this all PR for first time any help regarding that would be helpful.
as far the changes proposed, if we used [ctrl + /] to comment it uses line comment and that solution was to escape for loop if it is commented using single line comment.
It wont work for multiple line comment as discussed in that PR(#34810)


screenshot 102 _li

**Comment by RandellDawson** [comment]
>  I checked the solution once again and i see that hasOwnProperty with all 4 arguments will return true even if one property name matches.

@ The hasOwnProperty method will use the first argument ('Alan') in your second solution, which is why it shows **true**.  There is a bug in the tests, which is being worked on in another PR.

For the challenge testString, if other mods feel we should allow commented "for", then the regex would need to cover both single line and multi-line comments.

**Comment by RandellDawson** [comment]
@Vikas-KM I am closing this PR based on what I have already stated above and I will be making a comment on your PR #34810 which makes the same change to the `map` challenge file as this one does.

**Pull request closed without merging**
