### PR TITLE
test(challenges): Corrected a test case for challenge

### LINKED ISSUE #17134: Improve tests for challenge
#### Issue Description

We need to improve tests because if I type props *without curly braces* it pass the challenge
` <p>Your temporary password is: <strong>this.props.tempPassword</strong></p>`

### PR DESCRIPTION
**Pull request by manjeet5**
For the last test case in 'Access Props using this.props' challenge, I updated the test condition to check that the value of the tempPassword prop is the same as the content within the <strong/> tags. This test case will ensure that there is text present in the strong tag and its value is as expected.

BREAKING CHANGE: none

Closes #17134

#### Pre-Submission Checklist

- [x] Your pull request targets the `staging` branch of freeCodeCamp.
- [x] Branch starts with either `fix/`, `feature/`, or `translate/` (e.g. `fix/signin-issue`)
- [x] You have only one commit (if not, [squash](http://forum.freecodecamp.org/t/how-to-squash-multiple-commits-into-one-with-git/13231) them into one commit).
- [x] All new and existing tests pass the command `npm test`. Use `git commit --amend` to amend any fixes.

#### Type of Change

- [x] Small bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds new functionality)
- [ ] Breaking change (fix or feature that would change existing functionality)
- [ ] Add new translation (feature adding new translations)

#### Checklist:

- [x] Tested changes locally.
- [x] Addressed currently open issue (replace XXXXX with an issue no in next line)

Closes #17134

#### Description
Issue: 
We need to improve tests because if user types props without curly braces it pass the challenge
<p>Your temporary password is: <strong>this.props.tempPassword</strong></p>

Solution:
For the last test case in Access Props Using this.props challenge, I updated the test condition to check that the value of the tempPassword prop is the same as the content within the <strong/> tags. This test case will ensure that there is text present in the strong tag and its value is as expected.

### CODE REVIEW

**Review by Bouncey — DISMISSED** [review]
Hi @manjeet5, thanks for the fix. Could you make the changes again but without all the extra formatting please.

**Comment by raisedadead** [comment]
Is this still WIP?

**Comment by manjeet5** [comment]
@raisedadead nope this PR is no longer WIP

**Comment by raisedadead** [comment]
@manjeet5 apologies for the delay. we have refactored the seed a little bit. Do you think you can re-visit these?

**Pull request merged**
