### PR TITLE
fix(ci): add seed:exams to e2e playwright

### LINKED ISSUE #51841: [CI] Adjust github actions with db command to populate exam questions for playwright e2e tests
### Is your feature request related to a problem? Please describe.

The db exam details is empty on CI, should be execeuted pnpm run seed:exam.

### Describe the solution you'd like

The same as we already have with pnpm run seed:certified-user, should be added one more command "pnpm run seed:exams"
Снимок экрана 2023-10-06 в 16 05 44
It is not possible to test exam pages without populating db with exam details

### Describe alternatives you've considered

-

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by dzmdre**
Checklist:

- [x] I have read and followed the [contribution guidelines](https://contribute.freecodecamp.org).
- [x] I have read and followed the [how to open a pull request guide](https://contribute.freecodecamp.org/#/how-to-open-a-pull-request).
- [x] My pull request targets the `main` branch of freeCodeCamp.
- [x] I have tested these changes either locally on my machine, or GitPod.

Closes #51841

### CODE REVIEW

**Review by huyenltnguyen — COMMENTED** [review]
@dzmdre Thanks for the PR!

Have you tested this on the failing PRs? We would want to be sure this change addresses the issue before merging it in.

**Comment by dzmdre** [comment]
> Could you try cherry-picking this commit onto one of the failing PRs and see if CI passes?

Works as expected.

**Review by huyenltnguyen — APPROVED** [review]
Thanks @dzmdre! Confirmed that this change fixes the failing PRs.

Ref: https://github.com/freeCodeCamp/freeCodeCamp/pull/51796/commits/1a49a33fd49f57f26e505e8186c76c09835435bb

**Comment by dzmdre** [comment]
Thank you  @huyenltnguyen. Waiting for another reviewer

**Review by naomi-lgbt — APPROVED** [review]

**Pull request merged**
