### PR TITLE
fix(curriculum): Read-search-ask link now point to correct url as noted in the issue

### LINKED ISSUE #37751: Read-search-ask links are broken
Many of the challenges say something like this...

Remember to use [Read-Search-Ask](http://forum.freecodecamp.org/t/how-to-get-help-when-you-are-stuck/19514) if you get stuck. Try to pair program. Write your own code.

The link there is broken. Many challenges have this problem. Here's the working link:
https://www.freecodecamp.org/forum/t/the-read-search-ask-methodology-for-getting-unstuck/137307

### PR DESCRIPTION
**Pull request by Mozar10**
- [x] I have read [freeCodeCamp's contribution guidelines](https://github.com/freeCodeCamp/freeCodeCamp/blob/master/CONTRIBUTING.md).
- [x] My pull request has a descriptive title (not a vague title like `Update index.md`)
- [x] My pull request targets the `master` branch of freeCodeCamp.
- [x] None of my changes are plagiarized from another source without proper attribution.
- [x] All the files I changed are in the same world language (for example: only English changes, or only Chinese changes, etc.)
- [x] My changes do not use shortened URLs or affiliate links.

Closes #37751

### CODE REVIEW

**Review by moT01 — COMMENTED** [review]
Seems like there's a lot more files with this issue. You searched for the `https` version of the link, but it looks like there are a number of `http` versions as well, along with maybe others?

And there's at least [one more spot](https://github.com/freeCodeCamp/freeCodeCamp/blob/master/client/src/templates/Challenges/components/HelpModal.js#L25) in the `ask for help` modal - when you are on a challenge and click the `ask for help` button, a modal pops up with a broken link as well.

I'm not sure how many files are affected or the best way to split up the PR's - perhaps we should look at merging this one, and make another for replacing the `http` links.

**Comment by Mozar10** [comment]
Why are there http  links? Shouldn't everything be served over https? I can make a very quick adjustment to the script so it picks up http as well, not sure it makes sense to split up PRs. Let me know

**Comment by RandellDawson** [comment]
@Mozar10 Go ahead and make all the links `https`.

**Comment by Mozar10** [comment]
@RandellDawson @moT01 updated.

**Comment by raisedadead** [comment]
Hi @moT01 @RandellDawson can we get a merge on this?

**Comment by RandellDawson** [comment]
@raisedadead I wish these changes were not mixed across all languages.  There is a reason we have the 5th bullet in the checklist.  It makes it much easier to review the same language for the same changes.  Many of the non-English ones are all on a single line, and the GitHub view does not clearly show the changes.  I end up having to use a site like diffchecker to validate the only thing changed was the link.

**Review by moT01 — COMMENTED** [review]
I pointed out one other spot that is missed...
> And there's at least [one more spot](https://github.com/freeCodeCamp/freeCodeCamp/blob/master/client/src/templates/Challenges/components/HelpModal.js#L25) in the `ask for help` modal - when you are on a challenge and click the `ask for help` button, a modal pops up with a broken link as well.

I can make a separate PR for that one if needed.

Other than that, I scanned through the diffs of the english files and it LGTM 🎉  - This should make all the links work in theory. But I didn't go test them all.

**Comment by RandellDawson** [comment]
> I can make a separate PR for that one if needed.

@moT01 Maybe just add a commit to this PR for the one missed?

**Comment by Mozar10** [comment]
> I pointed out one other spot that is missed...
> 
> > And there's at least [one more spot](https://github.com/freeCodeCamp/freeCodeCamp/blob/master/client/src/templates/Challenges/components/HelpModal.js#L25) in the `ask for help` modal - when you are on a challenge and click the `ask for help` button, a modal pops up with a broken link as well.
> 
> I can make a separate PR for that one if needed.
> 
> Other than that, I scanned through the diffs of the english files and it LGTM  - This should make all the links work in theory. But I didn't go test them all.

Ooh right, my bad. The script didn't pick that one up because of the concatenation. Thanks for fixing it

**Review by raisedadead — APPROVED** [review]

**Review by moT01 — APPROVED** [review]
🎉 LGTM 🎉

**Review by Manish-Giri — APPROVED** [review]
LGTM

**Pull request merged**
