### PR TITLE
Update improved article, fixed references

### PR DESCRIPTION
**Pull request by shreyas1599**
- [x] I have read [freeCodeCamp's contribution guidelines](https://github.com/freeCodeCamp/freeCodeCamp/blob/master/CONTRIBUTING.md).
- [x] My pull request has a descriptive title (not a vague title like `Update index.md`)
- [x] My pull request targets the `master` branch of freeCodeCamp.
- [x] None of my changes are plagiarized from another source without proper attribution.
- [x] All the files I changed are in the same world language (for example: only English changes, or only Chinese changes, etc.)
- [x] My changes do not use shortened URLs or affiliate links.

Closes #XXXXX

### CODE REVIEW

**Review by RandellDawson — CHANGES_REQUESTED** [review]
See requested changes.

**Comment by shreyas1599** [comment]
I have made the requested changes.

**Review by RandellDawson — APPROVED** [review]

**Comment by shreyas1599** [comment]
(I'm still new to this) Umm.. Why hasn't it been merged yet? Does the merging take place automatically once reviewed or do I have to do something?

**Comment by raisedadead** [comment]
> (I'm still new to this) Umm.. Why hasn't it been merged yet? Does the merging take place automatically once reviewed or do I have to do something?

Everything is usually in a QA, and sometimes it takes days before pull requests are merged. Someone eventually will come around and merge your PR. We request your patience :)

**Comment by shreyas1599** [comment]
Oh ok thanks for replying. As I said, I'm new to all this :)

**Pull request merged**
