### PR TITLE
Add hint and solution

### PR DESCRIPTION
**Pull request by ailyntang**
- [ x] I have read [freeCodeCamp's contribution guidelines](https://github.com/freeCodeCamp/freeCodeCamp/blob/master/CONTRIBUTING.md).
- [ x] My pull request has a descriptive title (not a vague title like `Update index.md`)
- [ x] My pull request targets the `master` branch of freeCodeCamp.
- [ x] None of my changes are plagiarized from another source without proper attribution.
- [ x] My article does not contain shortened URLs or affiliate links.

### CODE REVIEW

**Comment by RandellDawson** [comment]
@ailyntang Thanks for creating this PR. Your solution should include all of the original challenge seed code with the changes needed to make the solution pass. The idea is the user should be able to copy the entire code and replace everything in the editor and it should pass the tests.

Just update your changes to include all code and then we can test your solution.

Thanks for understanding.

**Comment by RandellDawson** [comment]
Hi @ailyntang Thank you for doing that.  We try to merge PRs based on who creates an acceptable PR first.  There is one other PR before yours (#28499) which added a solution and hints for this same challenge.  The other PR had a full solution to this challenge, but did not have a full solution for another challenge on the same PR.  We requested both of you to add a full solution. If we do not hear back from the other PR soon, we will close it and merge yours instead.

**Comment by ailyntang** [comment]
@RandellDawson No worries, thanks for letting me know how the process works.

**Comment by RandellDawson** [comment]
Thank you for your contribution to the page! 👍
We're happy to accept these changes, and look forward to future contributions. 🎉

**Pull request merged**
