### PR TITLE
fix(curriculum): fix method listings to improve readability of description

### LINKED ISSUE #45482: Readability of method listing
## Affected page

[/coding-interview-prep/data-structures/create-an-es6-javascript-map](https://www.freecodecamp.org/learn/coding-interview-prep/data-structures/create-an-es6-javascript-map)

## Screenshots

Screenshot_1

## Suggestion

- readability, flow and understanding might be impacted **negatively** by not differentiating or listing these `methods` properly
- make a proper list with each `method` as an list item

Screenshot_2

### PR DESCRIPTION
**Pull request by freeZe2511**
Checklist:

- [x] I have read [freeCodeCamp's contribution guidelines](https://contribute.freecodecamp.org).
- [x] My pull request has a descriptive title (not a vague title like `Update index.md`)
- [x] My pull request targets the `main` branch of freeCodeCamp.
- [x] I have tested these changes either locally on my machine, or GitPod.

Closes #45482

Improves readability, flow and understanding by properly listing all methods associated to class
Tested with GitPod

### CODE REVIEW

**Review by wongruiyang — APPROVED** [review]
Lgtm, however there are multiple languages and I am unsure if it is necessary to change them too.

**Comment by raisedadead** [comment]
@freeZe2511 

Thanks for the PR. Someone will look into reviewing and getting this in soon.

@wongruiyang 

Thanks for the review. 

> Lgtm, however there are multiple languages and I am unsure if it is necessary to change them too.

No - it is not required by you to make the change in languages other than English. Localization happens outside of GitHub on our translations platform: https://contribute.freecodecamp.org/#/index?id=translations

**Review by lynxlynxlynx — APPROVED** [review]
Thanks and congratulations on your first submission!

**Review by naomi-lgbt — APPROVED** [review]
Looks good to me.

**Comment by nhcarrigan** [comment]
Congrats on your first pull request (PR)! 🎉

Thank you for your contribution to the page! 👍
We are happy to accept these changes and look forward to future contributions. 📝

**Comment by freeZe2511** [comment]
Thanks! 👍

**Pull request merged**
