### PR TITLE
feat: make it easier to make changes to profile

### PR DESCRIPTION
**Pull request by Sembauke**
Checklist:

- [x] I have read and followed the [contribution guidelines](https://contribute.freecodecamp.org).
- [x] I have read and followed the [how to open a pull request guide](https://contribute.freecodecamp.org/#/how-to-open-a-pull-request).
- [x] My pull request targets the `main` branch of freeCodeCamp.
- [x] I have tested these changes either locally on my machine, or GitPod.

This makes it easier to make new changes to the profile for #48234 .

I have made a custom page for development in the pages directory called `developmentuser`. Now when clicking on the profile it will directly go to the profile page.

Let me know if this is something we want.

### CODE REVIEW

**Review by moT01 — COMMENTED** [review]
This is a neat little hack @Sembauke - I kinda like it. I would be fine adding it. I wonder if we should add `developmentuser` to the blocklisted usernames. I don't see it in there - it's in `shared/config/constants.ts`.

**Comment by Sembauke** [comment]
I thought about that, but I just wanted to make sure.

If we actually want this, the test need to be updated too.

**Comment by moT01** [comment]
> the test need to be updated too

I thought about that - that some tests need to click that "preview" button, but none of them are failing?

**Comment by ojeytonwilliams** [comment]
What problem is this solving? Just that you need to click through the 404 page when specifically working on the /developmentuser profile? It doesn't seem worth creating a special case in the client for that.

**Comment by Sembauke** [comment]
It is not solving a problem, this makes the development environment mirror the production build. Instead of needing to go to a weird custom 404 page.

As stated a lot needs to be done before we can merge this.

**Comment by raisedadead** [comment]
> It is not solving a problem, this makes the development environment mirror the production build.

Unfortunately that's not true [or how it works](https://v3.gatsbyjs.com/docs/how-to/adding-common-features/add-404-page/#:~:text=Gatsby%20uses%20a%20default%20404%20page%20that%20overrides%20your%20custom%20404%20page.). 

The code is trying to override the override.

That is:

1. Gatsby, when in production uses the `custom 404` - which redirect to user profiles.
2. Gatsby, when in development presents its own  `debug 404` - before the `custom 404` with the debug info and the button - clicking the button activates the `custom 404` - the next thing in the lifecycle.

The code is essentially, preventing the `debug 404`. 

It's not "mirroring" the production but "mocking" it – meaning I would not expect it to behave **logically** like the production routing does.

Example: It will obviously fail when you add another user into the development workflow, example lets say we create `developmentuser2` with different dataset than `developmentuser` for say some debugging needs.

The point being:

- It tries to hide the Gatsby Dev Servers behaviors. 
- It could surprise uninitiated devs (when the do see the `debug 404`) to believe something is not correct - since they are used to the `/developmentuser` page "just working"?
- It has a potential need for "special" case handling in tests (like you said). 
- It adds complexity without solving "the mirroring" - because it is not?

Now, do we need the trick: Say as a convenient way for debugging? That's another story and discussion - but lets be clear on what the code is doing at the very least.

Hope this makes sense.

**Comment by Sembauke** [comment]
My original intention is indeed to make debugging the profile page a little less inconvenient.

You are correct, "mirroring" was a poor choice of words. Instead I should've used mocking. The Gatsby's `debug 404` should still be available, just not for the profile page. 

> Example: It will obviously fail when you add another user into the development workflow, example lets say we create developmentuser2 with different dataset than developmentuser for say some debugging needs.

Yep this is correct, but for simplicity, let's keep it this way.

My suggestion is: Add a route for both seeded users, one being `developmentuser` and the other `certifieduser`.

My questions are:
> It adds complexity without solving "the mirroring" - because it is not?

If we replace this word by mocking, does it make a difference?

**Pull request closed without merging**
