### PR TITLE
detailed article on pandas data visualization.

### PR DESCRIPTION
**Pull request by harikrishnand**
- [x] I have read [freeCodeCamp's contribution guidelines](https://github.com/freeCodeCamp/freeCodeCamp/blob/master/CONTRIBUTING.md).
- [x] My pull request has a descriptive title (not a vague title like `Update index.md`)
- [x] My pull request targets the `master` branch of freeCodeCamp.
- [x] None of my changes are plagiarized from another source without proper attribution.
- [x] My article does not contain shortened URLs or affiliate links.

If your pull request closes a GitHub issue, replace the XXXXX below with the issue number.

Closes #XXXXX

### CODE REVIEW

**Comment by harikrishnand** [comment]
Follow up to my pandas articles. detailed article on pandas data visualization.

**Review by Nirajn2311 — CHANGES_REQUESTED** [review]
Please follow the style guide properly.

**Comment by harikrishnand** [comment]
@Nirajn2311 : Could you please kindly elaborate style guide(reference). Please give some instances in the article.

**Comment by svmi3195** [comment]
It's this guide, as I understand: https://github.com/freeCodeCamp/freeCodeCamp/blob/master/docs/style-guide-for-guide-articles.md
Check your title metadata, it should be
```
---
title: Your Title
---
```

**Comment by harikrishnand** [comment]
Hi both,
@Nirajn2311 , @svmi3195 : I have made the changes as per your guidance. Can you please review it.  This is first time I am posting an article and it will be really helpful that you share your valuable comments and approval.  

Thanks,
Hari.

**Comment by paulywill** [comment]
@harikrishnand Nicely done!

 Krammer impressed

**Pull request merged**
