### PR TITLE
Created Italian translation for the freeCodeCamp README.MD file.

### PR DESCRIPTION
**Pull request by lindakovacs**
Created Italian translation for the freeCodeCamp README.MD file.

- [X] I have read [freeCodeCamp's contribution guidelines](https://github.com/freeCodeCamp/freeCodeCamp/blob/master/CONTRIBUTING.md).
- [X] My pull request has a descriptive title (not a vague title like `Update index.md`)
- [X] My pull request targets the `master` branch of freeCodeCamp.
- [X] None of my changes are plagiarized from another source without proper attribution.
- [X] My article does not contain shortened URLs or affiliate links.

If your pull request closes a GitHub issue, replace the XXXXX below with the issue number.

Closes #XXXXX

### CODE REVIEW

**Comment by RandellDawson** [comment]
Closed and Reopened this PR in an attempt to attempt to break out of the Travis build pending status.

**Comment by RandellDawson** [comment]
Closed and Reopened this PR in an attempt to attempt to break out of the Travis build pending status.

**Comment by QuincyLarson** [comment]
@lindakovacs Awesome! Thank you for translating the readme into Italian! And thank you for all the other great translations you're doing for the community!

**Comment by lindakovacs** [comment]
@QuincyLarson I'm glad I can give some contributions back to freeCodeCamp community as a thank you to having the opportunity to polish my skills using the platform. Other translations that I'm working on are coming soon. Also, I saw that other community members started to fix my translations which I think is inspiring them to contribute to the Curriculum as I do.

**Pull request merged**
