### PR TITLE
fix(a11y): add tabstop on info panel

### PR DESCRIPTION
**Pull request by bbsmooth**
Checklist:

- [x] I have read [freeCodeCamp's contribution guidelines](https://contribute.freecodecamp.org).
- [x] My pull request has a descriptive title (not a vague title like `Update index.md`)
- [x] My pull request targets the `main` branch of freeCodeCamp.
- [x] I have tested these changes either locally on my machine, or GitPod.

Closes #XXXXX

My previous PR removed the tab stop on the Code panel in the mobile layout because it was unnecessary. This PR adds a tab stop on the Info panel because it is definitely necessary in several situations.

- Some Info panels do not have any focusable elements in them and thus it is currently impossible for a keyboard user to scroll the content of the Info panel when needed. See the [Stand in Line challenge](https://www.freecodecamp.org/learn/javascript-algorithms-and-data-structures/basic-javascript/stand-in-line).
- As suggested by the [ARIA Authoring Practices Guide](https://www.w3.org/WAI/ARIA/apg/patterns/tabpanel/#keyboard-interaction-21), unless the first element in the tab panel is focusable then the tab panel itself should be a tab stop. This will be particularly helpful for screen reader users as it will guarantee they always get dropped into the tab panel at the very beginning of the content.

### CODE REVIEW

**Comment by raisedadead** [comment]
You should just be able to toggle the "draft" feature while you are still working on something :)

**Comment by bbsmooth** [comment]
My bad. It's ready for review.

**Review by Sboonny — APPROVED** [review]
LGTM 🎉, thank you for your contribution to the page! 👍.

**Review by raisedadead — APPROVED** [review]
> My bad. It's ready for review.

No worries, it's just a recommendation :)

Thanks for the PR and your excellent contributions. Cheers and happy coding!

**Pull request merged**
