### PR TITLE
fixed arrow function with no curly braces failing IIFE test

### LINKED ISSUE #38542: arrow function without curly braces fail IIFE test
**Describe your problem and how to reproduce it:**
ref: #35573
The code below does not pass as an anonymous immediately invoked function expression (IIFE).
`(()=> console.log("A cozy nest is ready"))();`

**Add a Link to the page with the problem:**
https://www.freecodecamp.org/learn/javascript-algorithms-and-data-structures/object-oriented-programming/understand-the-immediately-invoked-function-expression-iife

**Tell us about your browser and operating system:**
* Browser Name: Google Chrome
* Browser Version: Version 80.0.3987.163 (Official Build) (32-bit)
* Operating System: Windows 10 Enterprise Build 18363.752

**If possible, add a screenshot here (you can drag and drop, png, jpg, gif, etc. in this box):**
arrow-function

### PR DESCRIPTION
**Pull request by piouson**
Checklist:

- [x] I have read [freeCodeCamp's contribution guidelines](https://github.com/freeCodeCamp/freeCodeCamp/blob/master/CONTRIBUTING.md).
- [x] My pull request has a descriptive title (not a vague title like `Update index.md`)
- [x] My pull request targets the `master` branch of freeCodeCamp.
- [x] All the files I changed are in the same world language, for example: only English changes, or only Chinese changes, etc.

Closes #38542

### CODE REVIEW

**Comment by scissorsneedfoodtoo** [comment]
Tested locally with the following:

```js
(function () {
  console.log("A cozy nest is ready");
})();
```

```js
(() => {
  console.log("A cozy nest is ready");
})();
```

```js
(() => console.log("A cozy nest is ready"))();
```

The first two pass with the current `testString`'s, but the third solution fails. This PR makes it so the third solution also passes.

**Comment by piouson** [comment]
> Tested locally with the following:
> 
> ```js
> (function () {
>   console.log("A cozy nest is ready");
> })();
> ```
> 
> ```js
> (() => {
>   console.log("A cozy nest is ready");
> })();
> ```
> 
> ```js
> (() => console.log("A cozy nest is ready"))();
> ```
> 
> The first two pass with the current `testString`'s, but the third solution fails. This PR makes it so the third solution also passes.

Tested locally, all three pass..

**Comment by scissorsneedfoodtoo** [comment]
@piouson, awesome, thank you for confirming everything is working on your end. We just need another maintainer to review your PR and make sure we didn't miss anything. Then we'll be able to merge your fix.

**Review by snigo — CHANGES_REQUESTED** [review]
1. Include support for white spaces: `function () {`
2. IIFE functions could be also structured as follows:
```
(function() {
  statements
}());
```

**Comment by ojeytonwilliams** [comment]
> 1. Include support for white spaces: `function () {`

White spaces are stripped from the code before attempting to match, so that should be fine.

> 2. IIFE functions could be also structured as follows:
> 
> ```
> (function() {
>   statements
> }());
> ```

Good point, that should pass.  However, the existing changes are already a nice improvement, so I'd be happy merging as is and handling this in another PR.  @piouson do you think you'll have a chance to implement @snigo's request?

**Comment by piouson** [comment]
> Edit: while
> 
> ```js
> (() =>{console.log('called')})();
> ```
> 
> is valid and
> 
> ```js
> (() =>{console.log('called')}());
> ```
A new PR would be a good idea for what @snigo suggested, which I'd love to implement.
The change may require complete rewrite of original regex and kinda merging both testStrings into one cos as you pointed out, explicit regexes would be required for normal vs arrow functions.

that is, change
> ```
> testString: assert(/\((function|\(\))(=>|\(\)){?/.test(code.replace(/\s/g, "")));
> ```
and
> ```
> testString: assert(/}?\)\(\)/.test(code.replace(/\s/g, "")));
> ```
to something like
```
 testString: assert(/\(function\(\){.*}(\)\(\)|\(\)\))|\(\(\)=>{?.*}?(?<=\)|\})\)\(\)/.test(code.replace(/\s/g, "")));
```
what do you think? @ojeytonwilliams

**Comment by ojeytonwilliams** [comment]
Okay, cool.  I'd like to wait a little to see if @snigo has any input, but assuming he's fine with this, I'm happy to merge.

Regarding the regex for the different syntax:

> explicit regexes would be required for normal vs arrow functions.

I may be missing something, but I don't think so.  If we check for 

```js
(function() {
 // statements
}());
```

```js
(function() {
 // statements
})();
```

```js
(() => {
  // statements
}());
```

```js
(() => {
 // statements
})();
```

with the optional curly braces implemented here, I think that's okay.  The 3rd one is not valid syntax, but you'll see

```
SyntaxError: unknown: Unexpected token, expected "," (3:1)

  1 | (() => {
  2 |   // statements
> 3 | }());
    |  ^
```

in the console and be unable to run the tests.  No need to catch that with the regex.

**Comment by snigo** [comment]
Sorry I missed `.replace()`...

My suggestions:
1. Function should be anonymous should not be flagged if function anonymous without iife
```
/function\(|\(\)=>/
```

2. Function should be iife, considering other combination will throw anyway:
```
/\((?:function)?(\(\))(?:=>)?{?console\.log\([\w'"`]+\)\}?(?:\1\)|\)\1)/.test(code.replace(/[\s;]+/g, ''));
```

**Comment by piouson** [comment]
I think @snigo pretty much covers everything now, except the 3rd example from @scissorsneedfoodtoo without curly braces is not iife and also not syntax error?
> Not IIFE without curly braces, but No Error in console
> 
>   1 | (() => 
>   2 |   // statements
>   3 | ());

**Comment by scissorsneedfoodtoo** [comment]
Oh boy, this was not as straightforward as I originally thought! Thank you for catching the alternative syntax and your suggestions @snigo, and also for your review @ojeytonwilliams.

@piouson, that's a good point, `(() => console.log("A cozy nest is ready")());` is not a syntax error, but shouldn't pass because it's not an IIFE without curly braces with this alternative sytax.

Rather than check the entire function with the second test, it might be better just to check the last few characters since there are only so many valid combinations.

If we change the second test string to something like `assert(/}?\)\(\);?$|}\(\)\);?$/.test(code.replace(/\s/g, "")));`, then it will match the following:

```js
(function() {
  console.log("A cozy nest is ready");
})();

(function() {
  console.log("A cozy nest is ready");
}());

(() => console.log("A cozy nest is ready"))();
```

But won't match:

```js
(() => console.log("A cozy nest is ready")());
```

Of course, I'm pretty bad with regex and tend to go for the simplest solution. What do you all think?

**Comment by piouson** [comment]
I've gotta say a big thank you to everyone, I've learned more about regex with Js and test cases! I look forward to reading more comments, but can I add;

@scissorsneedfoodtoo your idea of simplicity is very favourable, the first test case asserts *anonymous functions*, the second test case asserts *iife* which may only require checking the last few characters for **immediate invocation** like you've indicated `/}?\)\(\);?$|}\(\)\);?$/` considering wrong code will throw.

Still on simplicity tho, since @snigo already suggested also stripping out semicolons with `replace`, this obviates the need to regex them `;?`
> code.replace(/[\s;]+/g, '')

**Comment by ojeytonwilliams** [comment]
> except the 3rd example from @ojeytonwilliams without curly braces is not iife and also not syntax error?

Good catch! I completely forgot about that one.

I've checked @scissorsneedfoodtoo's regex, with @snigo's replace 
```js
assert(/}?\)\(\)$|}\(\)\)$/.test(code.replace(/[\s;]/g, "")));
```
and everything looks good.

So, to review, we have 4 cases we want the regex to pass:

```js
(function () {
  console.log("A cozy nest is ready");
})();
```

```js
(function () {
  console.log("A cozy nest is ready");
}());
```

```js
(() => {
  console.log("A cozy nest is ready");
})();
```

```js
(() =>
  console.log("A cozy nest is ready")
)();
```

we want the regex to fail:

```js
(() => console.log("A cozy nest is ready")());
```
because it's valid syntax, but not an IIFE and we don't care about:

```js
(() => {
  console.log("A cozy nest is ready")
}());
```
because it's not valid syntax.

We should try and prevent future modifications breaking this by adding the valid solutions to the Solution section: 

````html
## Solution
<section id='solution'>

```js
(function () {
  console.log("A cozy nest is ready");
})();
```

```js
(function () {
  console.log("A cozy nest is ready");
}());
```

```js
(() => {
  console.log("A cozy nest is ready");
})();
```

```js
(() =>
  console.log("A cozy nest is ready")
)();
```

</section>
````

**Comment by piouson** [comment]
added second test
> I've checked @scissorsneedfoodtoo's regex, with @snigo's replace
> 
> ```js
> assert(/}?\)\(\)$|}\(\)\)$/.test(code.replace(/[\s;]/g, "")));
> ```

and solutions
> We should try and prevent future modifications breaking this by adding the valid solutions to the Solution section:

--
The first test works fine already without implementing the simpler request from @snigo 
Is there still a need to amend this..?

**Comment by scissorsneedfoodtoo** [comment]
@piouson, thank you for mentioning that -- using replace to get rid of all possible semicolons like @snigo suggested is a much cleaner solution. And I really like the idea of adding all the possible valid solutions @ojeytonwilliams. I had no idea you could do that!

Unless I missed something, I don't think it's necessary to make any changes to the first test. It should pass with all of the valid solutions that @ojeytonwilliams mentioned in his last post. It wouldn't hurt to make things simpler, but if it's not causing any issues, we could probably just leave it the way it is for now.

**Comment by scissorsneedfoodtoo** [comment]
@piouson, thanks for making all those updates. Checked locally and everything LGTM.

I don't think we missed anything, but could you take another look and confirm @snigo and @ojeytonwilliams? If everything looks good I think this is ready to merge.

**Review by scissorsneedfoodtoo — APPROVED** [review]

**Comment by ojeytonwilliams** [comment]
@piouson Congrats on your first pull request (PR)! 🎉

Thank you for your contribution to the page! 👍
We're happy to accept these changes, and look forward to future contributions. 📝

**Comment by ojeytonwilliams** [comment]
Just to confirm, I think this is fine as is.  We can always revisit it, if needed!

**Comment by piouson** [comment]
> @piouson Congrats on your first pull request (PR)! 🎉
> 
> Thank you for your contribution to the page! 👍
> We're happy to accept these changes, and look forward to future contributions. 📝

Many thanks @ojeytonwilliams and thanks to everyone for holding my hand through this one..

**Comment by scissorsneedfoodtoo** [comment]
@piouson, thank you for all of your hard work here! Looking forward to your next contribution.

**Pull request merged**
