### PR TITLE
made checkpoint: profile-lookup

### LINKED ISSUE #5795: Caesar Replacement Checkpoint - Profile Lookup
Me and @SaintPeter have discussed the replacement for the Caesar checkpoint. 

It's going to be a Camper Lookup Checkpoint:

Make a function that takes a "camper" and a property as parameters and if that property exists, return that property is in. If the camper does not exist, return "No such Camper". If the property doesn't exist, return "Camper has no such property".

```javascript
var campers = [
    {
        "username": "SaintPeter",
        "title": "The Chosen One",
        "HP": 3000,
        "likes": ["Pizza", "Coding", "Brownie Points"]
    },
     {
        "username": "AkiraLaine",
        "title": "Time Traveler",
        "HP": 2000,
        "likes": ["Magic", "Javascript", "Cookies"]

    }
]

function lookUp(camper, prop){
    var answer;

    return answer;
}

lookUp("AkiraLaine", "likes");
```

@SaintPeter gave me the green light to make it. I'm currently setting up FCC locally and will start working on it.

### PR DESCRIPTION
**Pull request by AkiraLaine**
closes #5795 

Commits stashed as per @SaintPeter recommendation:

modified code and added new test cases

final revisions

fixed semicolon bug

fixed typo

repositioned checkpoint

### CODE REVIEW

**Comment by BerkeleyTrue** [comment]
This PR is failing travis build.

**Comment by SaintPeter** [comment]
@AkiraLaine Looks like there is a problem with your solution:
>  Profile Lookup: ReferenceError: contacts is not defined

You need to run `npm run test-challenges` to test that your solution works.  My suspicion is you forgot a variable declaration.

**Comment by abhisekp** [comment]
@AkiraLaine something isn't right. There are ** 457 additions and 111 deletions.**

**Comment by AkiraLaine** [comment]
I'm gonna look into it now.

**Pull request closed without merging**
