### PR TITLE
fix: remove unneeded assert text in rosetta section

### PR DESCRIPTION
**Pull request by moT01**
I noticed that many of the rosetta code challenges still had the assert text in the `textString` area. This PR removes the remaining messages for that section.

It appears as though prettier also formatted all the files as I saved them, adding spaces and such. I didn't notice that as I was going through them and it wasn't intentional. I know it makes this harder to review, so let me know if there's an issue with that and I can revert all those.

- [x] I have read [freeCodeCamp's contribution guidelines](https://github.com/freeCodeCamp/freeCodeCamp/blob/master/CONTRIBUTING.md).
- [x] My pull request has a descriptive title (not a vague title like `Update index.md`)
- [x] My pull request targets the `master` branch of freeCodeCamp.
- [x] All the files I changed are in the same world language, for example: only English changes, or only Chinese changes, etc.

### CODE REVIEW

**Comment by RandellDawson** [comment]
@ojeytonwilliams Why is prettier adding an extra line after the headers like (`## Description`)?

**Comment by moT01** [comment]
There's a chance it's some local setting I have.

**Review by RandellDawson — APPROVED** [review]
There were a lot of code formatting changes, but I was still able to review and conclude the actual intended changes are fine.  I was not aware that prettier supposed to automatically make those changes when committing.  I did not notice this on my recent PR.  I was thinking this would not happen until @ojeytonwilliams' PR #37912  was merged.

**Comment by moT01** [comment]
I changed a local setting of mine to format files on save when I was playing around with it, so that's probably why they formatted themselves. I'm not sure if the formatting on these files is okay for the repo or not - they look fine, it would be nice to keep them consistent though.

**Comment by RandellDawson** [comment]
@moT01 When @ojeytonwilliams updates his PR, it will reformat everything in one swoop.  Also, I assume the linter will complain or autofix any code that needs to be fixed when new PRs are created after that.

**Comment by raisedadead** [comment]
So just to reconfirm this is good for a merge?

**Comment by ojeytonwilliams** [comment]
Just to confirm, don't worry about the linter in my PR. It should automatically fix most things it doesn't like.

**Review by ojeytonwilliams — APPROVED** [review]
LGTM :+1:

**Pull request merged**
