### PR TITLE
fixes issue Add a hat symbol to babel-eslint version

### LINKED ISSUE #9776: Add a hat symbol to babel-eslint version
A carat (aka hat) symbol, `^` needs to be added [here](https://github.com/FreeCodeCamp/FreeCodeCamp/blob/staging/package.json#L35). So the result should look like this:
`"babel-eslint": "^6.1.2",`.

### PR DESCRIPTION
**Pull request by LeeWarnock**
#### Pre-Submission Checklist

- [x] Your pull request targets the `staging` branch of FreeCodeCamp.
- [x] Branch starts with either `fix/`, `feature/`, or `translate/` (e.g. `fix/signin-issue`)
- [x] You have only one commit (if not, [squash](https://github.com/FreeCodeCamp/FreeCodeCamp/wiki/Git-Squash) them into one commit).
- [ ] All new and existing tests pass the command `npm run test-challenges`. Use `git commit --amend` to amend any fixes.
#### Type of Change

- [x] Small bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds new functionality)
- [ ] Breaking change (fix or feature that would change existing functionality)
- [ ] Add new translation (feature adding new translations)
#### Checklist:

- [ ] Tested changes locally.
- [x] Closes currently open issue (replace XXXX with an issue no): Closes #9776

### CODE REVIEW

**Comment by LeeWarnock** [comment]
:information_desk_person: second try at first-time PR! :dancers:

**Comment by raisedadead** [comment]
@LeeWarnock: 

Thanks a lot for the pull request, and glad to hear that you are contributing to FCC for first time!
Here are a couple of things that you would want to change before we can accept the PR:

- Do not add issue nos anywhere other than specified.
1. Edit the PR title on the top of this thread and change it from
    > `fixes issue Add a hat symbol to babel-eslint version #9776`

    to
    > fixes issue Add a hat symbol to babel-eslint version

2. Next amend your commit and push to this sam branch again
```
git checkout fix/#9776
git commit --amend -m "fixes issue Add a hat symbol to babel-eslint version"
git push origin fix/#9776 --force
```

Next time, please follow the [Guidelines for Contributing](https://github.com/FreeCodeCamp/FreeCodeCamp/blob/staging/CONTRIBUTING.md). If you are stuck and need any assistance we are happy to help in the [Contributors Chat room](https://gitter.im/FreeCodeCamp/HelpContributors).

Happy Fixing!

**Comment by raisedadead** [comment]
Also replace the XXXX in the PR description as mentioned with issue no.

**Comment by LeeWarnock** [comment]
thank you, @raisedadead! I have completed your requested amendments!

I really appreciate you taking the time to help a first-timer! I'd love to become a Free Code Camp member one day, so anything I can do to work toward that, I'll do!

Thanks!

**Comment by raisedadead** [comment]
@LeeWarnock I have added the closes tag in the description. :wink:

**Comment by raisedadead** [comment]
#### :sparkles: :sparkles: **LGTM.** :sparkles: :sparkles: 

@LeeWarnock Thanks a lot for the contribution, and welcome to contributing to Free Code Camp.

**Comment by LeeWarnock** [comment]
WOOO! Thank you so much! It's an honor to help! Thank you guys for being so great!

**Pull request merged**
