### PR TITLE
9 Commands every Linux user should know

### PR DESCRIPTION
**Pull request by swetasharma**
- [x] I have read [freeCodeCamp's contribution guidelines](https://github.com/freeCodeCamp/freeCodeCamp/blob/master/CONTRIBUTING.md).
- [x] My pull request has a descriptive title (not a vague title like `Update index.md`)
- [x] My pull request targets the `master` branch of freeCodeCamp.
- [x] None of my changes are plagiarized from another source without proper attribution.
- [x] My article does not contain shortened URLs or affiliate links.

If your pull request closes a GitHub issue, replace the XXXXX below with the issue number.

Closes #XXXXX

### CODE REVIEW

**Comment by CodingSolo** [comment]
the text comes from the article [10 commands every Linux user should know](https://opensource.com/article/18/4/10-commands-new-linux-users)

**Comment by tchaffee** [comment]
Closed as plagiarized from another source without proper attribution.

**Comment by swetasharma** [comment]
@raisedadead why did you marked PR as invalid?

**Comment by RandellDawson** [comment]
@swetasharma Read the previous comments.

**Pull request closed without merging**
