### PR TITLE
docs: Remove chinese files from sidebar

### PR DESCRIPTION
**Pull request by naomi-lgbt**
Checklist:

- [X] I have read [freeCodeCamp's contribution guidelines](https://contribute.freecodecamp.org).
- [X] My pull request has a descriptive title (not a vague title like `Update index.md`)
- [X] My pull request targets the `master` branch of freeCodeCamp.
- [X] All the files I changed are in the same world language, for example: only English changes, or only Chinese changes, etc.

Closes #XXXXX

This PR removes the Chinese translation files from the sidebar. 

- I changed the English `_sidebar.md` - that should roll out to the other languages as part of the translation flow right? Or should I remove from all?
- Do we want to keep the actual files themselves? Or remove them.

### CODE REVIEW

**Review by raisedadead — APPROVED** [review]

**Comment by raisedadead** [comment]
These changes look good, let me confirm this with others in the team before I merge this.

**Comment by nhcarrigan** [comment]
Sounds good - my only concern would be that, since Crowdin will roll these changes out to the localization files, how do we keep the links present specifically for the Chinese sidebar? Or is that not a concern?

**Comment by raisedadead** [comment]
> ... how do we keep the links present specifically for the Chinese sidebar?

I am still exploring this.

**Comment by ieahleen** [comment]
I'm putting on the blocked label, while the response from the team gets back

**Comment by raisedadead** [comment]
We will probably go with a miscellaneous list of resources which have these guides. For now, I think we can remove the items from sidebar for consistency.

**Pull request merged**
