### PR TITLE
Added test case to Bonfire Drop It

### LINKED ISSUE #4741: Bonfire: Drop It - Add additional Test Cases
Ever since we added the last test case to [Drop It](http://www.freecodecamp.com/challenges/bonfire-drop-it), there have been questions about it.

We either need to add several additional test cases which have a later number which does not meet the test criteria retained, or alter earlier test cases to have that same condition.

Relevant Text (Emphasis added):
< Drop the elements of an array (first argument), starting from the front, **until** the predicate (second argument) returns true.

Existing Test Case:
`drop([1, 2, 3, 9, 2], function(n) {return n > 2;}) should return [3, 9, 2].`

We do believe that this "early exit" solution is important and should be supported by test cases.

### PR DESCRIPTION
**Pull request by alan1001110**
Closes #4741

### CODE REVIEW

**Comment by bugron** [comment]
@alan1001110 please, move `Closes #4741` to the PR's description.

**Comment by alan1001110** [comment]
Thanks @bugron Is that better?

**Comment by bugron** [comment]
Yes, awesome.

**Comment by ltegman** [comment]
Looks good! Thanks for the PR :+1:

**Pull request merged**
