### PR TITLE
Commented full solution

### PR DESCRIPTION
**Pull request by InaSLew**
- [x] I have read [freeCodeCamp's contribution guidelines](https://github.com/freeCodeCamp/freeCodeCamp/blob/master/CONTRIBUTING.md).
- [x] My pull request has a descriptive title (not a vague title like `Update index.md`)
- [x] My pull request targets the `master` branch of freeCodeCamp.
- [x] None of my changes are plagiarized from another source without proper attribution.
- [x] All the files I changed are in the same world language (for example: only English changes, or only Chinese changes, etc.)
- [x] My changes do not use shortened URLs or affiliate links.

Closes #XXXXX

### CODE REVIEW

**Review by thecodingaviator — CHANGES_REQUESTED** [review]
Please add the full solution i.e. the challenge seed code + the changes required to pass the challenge

**Comment by InaSLew** [comment]
Hello! I just realized I have got the solutions to two challenges mixed up! Just fixed it, and thanks for the feedback!

**Review by thecodingaviator — APPROVED** [review]
LGTM! 👍

**Comment by thecodingaviator** [comment]
We try to merge PRs based on who creates an acceptable PR first. There are two other PR before yours (#28499 and #34430 ) which added a solution and hints for this same challenge. If we do not hear back from the other PR soon, we will close it and merge yours instead.

**Comment by InaSLew** [comment]
Thank you! Appreciate it ✨

**Comment by RandellDawson** [comment]
Congrats @InaSLew on your first pull request (PR)! 🎉

Thank you for your contribution to the page! 👍
We're happy to accept these changes and look forward to future contributions. 📝

**Pull request merged**
