### PR TITLE
Update index.md , adding for loop examples

### PR DESCRIPTION
**Pull request by kushan2018**
- [x] I have read [freeCodeCamp's contribution guidelines](https://github.com/freeCodeCamp/freeCodeCamp/blob/master/CONTRIBUTING.md).
- [x] My pull request has a descriptive title (not a vague title like `Update index.md`)
- [x] My pull request targets the `master` branch of freeCodeCamp.
- [x] None of my changes are plagiarized from another source without proper attribution.
- [x] My article does not contain shortened URLs or affiliate links.

If your pull request closes a GitHub issue, replace the XXXXX below with the issue number.

Closes #XXXXX

### CODE REVIEW

**Comment by kushan2018** [comment]
Adding for loop code for print A-Z.

**Comment by sergeyradov** [comment]
Tried to run this code sample in online C++ IDE and got the expected result.
Thank you for contribution, it looks good.

**Comment by RandellDawson** [comment]
LGTM

**Review by Manish-Giri — APPROVED** [review]
Hi @kushan2018 

Thank you for your contribution to the page! 👍

For future pull requests, please add the necessary formatting to your changes. Please review the [style guide for guide articles](https://github.com/freeCodeCamp/freeCodeCamp/blob/master/docs/style-guide-for-guide-articles.md) if you have any questions.

**Pull request merged**
