### PR TITLE
feat: border on avatar and badge for donating campers

### PR DESCRIPTION
**Pull request by ahmaxed**
Checklist:

- [x] I have read [freeCodeCamp's contribution guidelines](https://github.com/freeCodeCamp/freeCodeCamp/blob/master/CONTRIBUTING.md).
- [x] My pull request has a descriptive title (not a vague title like `Update index.md`)
- [x] My pull request targets the `master` branch of freeCodeCamp.
- [x] None of my changes are plagiarized from another source without proper attribution.
- [x] All the files I changed are in the same world language (for example: only English changes, or only Chinese changes, etc.)
- [x] My changes do not use shortened URLs or affiliate links.

image

### CODE REVIEW

**Comment by ahmadabdolsaheb** [comment]
Additionally, we could display an icon with the word "supporter " similar to the way we handle top contributors.

for reference:
Screen Shot 2020-03-24 at 6 25 13 PM

**Comment by raisedadead** [comment]
I would make the border golden, and I would also like to see a badge similar to the top contributor.

**Comment by ahmadabdolsaheb** [comment]
image

**Comment by raisedadead** [comment]
Looks much nicer, I would change the badge icon for the supporter.

**Comment by ahmadabdolsaheb** [comment]
changed with the a heart.
image

**Comment by raisedadead** [comment]
Looks great, just a quick check if this respects the privacy settings.

**Review by raisedadead — APPROVED** [review]

**Pull request merged**
