### PR TITLE
Overhauled Certificates

### LINKED ISSUE #9449: Certifications Overhaul
The current certifications are built using an image and overlaid text. We should have this completely made with css and html, along with mobile responsiveness. We are going to try and make the overall design similar also.

**References:**
:point_up: [June 29, 2016 7:34 PM](https://gitter.im/FreeCodeCamp/CoreTeam?at=577414d0cd7efd7714980861)
:point_up: [June 29, 2016 7:48 PM](https://gitter.im/FreeCodeCamp/CoreTeam?at=577417f78a12aa4d563e2c24)
:point_up: [June 29, 2016 8:24 PM](https://gitter.im/FreeCodeCamp/CoreTeam?at=5774205e50501d830ba38718)

cc/ @QuincyLarson @BerkeleyTrue

### PR DESCRIPTION
**Pull request by ghost**
#### Pre-Submission Checklist
- [x] Your pull request targets the `staging` branch of FreeCodeCamp.
- [x] Branch starts with either `fix/`, `feature/`, or `translate/`
- [x] You have only one commit.
- [x] All new and existing tests pass the command `npm run test-challenges`.
#### Type of Change
- [x] Breaking change (fix or feature that would change existing functionality)
#### Checklist:
- [x] Tested changes locally.
- [x] Closes currently open issue: Closes #9449

### CODE REVIEW

**Comment by Rafase282** [comment]
Could it be printed?

**Comment by atjonathan** [comment]
@Rafase282, currently yes. But it looks like garbage:
[https://gyazo.com/29d6d0e130c114f900e7acd231da6bd9](https://gyazo.com/29d6d0e130c114f900e7acd231da6bd9).

cc/ @FreeCodeCamp/issue-moderators, I suggest we disable printing.

**Comment by Trion129** [comment]
I think if the background of "This certifies...." was made black with 0.6-0.7 opacity it would look better. 

Also do not disable printing some people would like to show the printed certificate to someone :smile_cat: The page should have a print specific formatting to it. using print media 
`<link rel="stylesheet" type"text/css" href="/css/print.css" media="print">`

**Comment by QuincyLarson** [comment]
@atjonathan wow - these look great. I'll try and find my signature and @CodeNonprofit's signature.

**Comment by atjonathan** [comment]
@QuincyLarson, yeh that's the only component I need :+1: Also, do you want these to be printed? I vote No.

**Comment by Bouncey** [comment]
Printable :-1:  no thanks.

**Comment by atjonathan** [comment]
@QuincyLarson @CodeNonprofit @BerkeleyTrue thoughts? Should we let campers print certificates?

**Comment by atjonathan** [comment]
@QuincyLarson @CodeNonprofit, ready for a `QA` :stuck_out_tongue_winking_eye:

**Comment by raisedadead** [comment]
@atjonathan the indentation looks off for all the files, can you check?

**Comment by atjonathan** [comment]
@raisedadead, sure :+1:

**Comment by atjonathan** [comment]
@raisedadead, look any better?

**Comment by raisedadead** [comment]
Sweet.

**Comment by atjonathan** [comment]
@quincylarson @codenonprofit any update on this being QAed?

**Comment by QuincyLarson** [comment]
@atjonathan thanks for your patience. I should have commented earlier. I think we should roll this out once we roll out the new platform. I worry that it will be controversial (many campers may be attached to the old versions of these certs which look fancier. 

Though these new certs are more practical, I feel like we should release them once we've ironed out the inevitable bugs associated with the big move to React. So I'm going to add the label "blocked" to this.

**Comment by atjonathan** [comment]
Np :smiley:, I agree :+1:

**Comment by raisedadead** [comment]
@atjonathan a rebasing off staging should fix the build errors.

**Comment by atjonathan** [comment]
@raisedadead, I will try and remember to do this when I get back from holidays :wink;

**Comment by alayek** [comment]
@atjonathan can't stay away from GitHub even on holidays, can you :wink:

**Comment by ramir141974** [comment]
I think everything is going  back OK thank you to all of you if posible is getting done and I hope.

**Comment by atjonathan** [comment]
@alayek :wink:

**Comment by atjonathan** [comment]
@QuincyLarson, are we looking to ship this with the rectification? If so, this could probably be merged.

**Comment by QuincyLarson** [comment]
@atjonathan Let's QA and deploy React first. Otherwise, we'll be adding additional complexity to the QA process. We can ship this shortly afterward.

**Comment by atjonathan** [comment]
Should this be shipped?

**Comment by QuincyLarson** [comment]
@atjonathan We are getting close to finishing the curriculum expansion effort (thanks in part to your help!)

I recommend we wait until that's shipped, then incorporate this, because we'll need to change the challenge structure a bit to accommodate these new certificates.

**Review by marekszewczak — APPROVED** [review]

**Pull request merged**
