### PR TITLE
Create git rm

### PR DESCRIPTION
**Pull request by Will-1-Am**
Create git rm description, syntax and general use cases with link to authoritative documentation.

- [x] I have read [freeCodeCamp's contribution guidelines](https://github.com/freeCodeCamp/freeCodeCamp/blob/master/CONTRIBUTING.md).
- [x] My pull request has a descriptive title (not a vague title like `Update index.md`)
- [x] My pull request targets the `master` branch of freeCodeCamp.
- [x] None of my changes are plagiarized from another source without proper attribution.
- [x] My article does not contain shortened URLs or affiliate links.

If your pull request closes a GitHub issue, replace the XXXXX below with the issue number.

Closes #XXXXX

### CODE REVIEW

**Comment by Will-1-Am** [comment]
I see checks have failed because the file was named incorrectly?  It would be helpful to have a little guidance with this as it is the first time I submit a new file.

**Comment by Will-1-Am** [comment]
.

**Comment by RandellDawson** [comment]
Changed filename on user's behalf.

**Comment by RandellDawson** [comment]
Thank you for your contribution to the page! 👍
We're happy to accept these changes, and look forward to future contributions. 🎉

**Pull request merged**
