### PR TITLE
added a space between . and word

### PR DESCRIPTION
**Pull request by DiggyShants**
In the text, there was no space where needed. I added the space.

- [x] I have read [freeCodeCamp's contribution guidelines](https://github.com/freeCodeCamp/freeCodeCamp/blob/master/CONTRIBUTING.md).
- [x] My pull request has a descriptive title (not a vague title like `Update index.md`)
- [x] My pull request targets the `master` branch of freeCodeCamp.
- [x] None of my changes are plagiarized from another source without proper attribution.
- [x] My article does not contain shortened URLs or affiliate links.

If your pull request closes a GitHub issue, replace the XXXXX below with the issue number.

Closes #XXXXX

### CODE REVIEW

**Comment by RandellDawson** [comment]
I made a couple extra edits on your behalf.

**Comment by RandellDawson** [comment]
@paulywill Did you assign yourself to test if closing/reopening allowed being able to merge?

**Comment by paulywill** [comment]
@DiggyShants 

WELL DONE

**Comment by paulywill** [comment]
@RandellDawson The article was failing on a lint error for the frontmatter:

```
Error: 
  The article at: /home/travis/build/freeCodeCamp/freeCodeCamp/guide/english/3d/blender/index.md is missing frontmatter.
  Example:
  ---
  title: The Article Title
  localeTitle: The Translated Title # Only required for translations
  ---
  < The Article Body >

```
I did close and reopen to trigger the Travis CI build thinking perhaps the issue was something unrelated to the PR, however it was the article starting with a leading blank line.

**Comment by RandellDawson** [comment]
OK.  I was just checking.  I am glad you caught it.

**Pull request merged**
