### PR TITLE
fix(curriculum): add backticks in role playing game project

### LINKED ISSUE #48870: Step 62 of new js course (build and rpg) is missing some backticks
### Describe the Issue

Step 62’s instructions say:
The `locations` array contains two locations: the town square and the store.

The words “town square” and “store” should be in backticks as they are code and must not be translated.

Also in this sentence:
Currently you are passing that entire array into the update functions. 

The word update should be in backticks as it is the name of a function.
And incidentally the word functions should be singular not plural.

### Affected Page

curriculum/challenges/english/15-javascript-algorithms-and-data-structures-22/learn-basic-javascript-by-building-a-role-playing-game/62a8b6536156c51500739b41.md

### Your code

```

```

### Expected behavior

Use backticks to surround the words that are part of the code.
(and one grammar issue in this step)

### Screenshots

_No response_

### System

N/A

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by marktlinn**
Put words representing code, which should not be translated, inside backticks  Also corrected typo "functions" for "function", as it is singular

Checklist:

- [x] I have read [freeCodeCamp's contribution guidelines](https://contribute.freecodecamp.org).
- [x] My pull request has a descriptive title (not a vague title like `Update index.md`)
- [x] My pull request targets the `main` branch of freeCodeCamp.
- [x] I have tested these changes either locally on my machine, or GitPod.

Closes #48870

### CODE REVIEW

**Comment by raisedadead** [comment]
As a new contributor, we encourage you to read our [contributing guidelines](https://contribute.freecodecamp.org).

We expect our contributors to be aware of the process specific to this project. Following the guidelines religiously earns you the respect of fellow maintainers and saves everyone time.

Some examples of this are:

1. Do not edit files directly through GitHub – while you can, it's not a good idea.
2. Make sure you follow the PR checklist and not just tick things off; otherwise, we won't take you seriously.
3. Use the correct way to link issues in the description of the PR by updating the `XXXXXX`. Do not just add issue numbers everywhere and anywhere you feel like.
4. Keep mentions and review requests to a minimum. We understand you are excited about contributing, and our maintainers will get back to you as soon as they get a chance.
5. Do not work directly off your `main` branch - create a new branch for the changes you are working on.

We appreciate you taking the time to help us, and we hope to see more contributions from you.

Happy Contributing.

**Comment by marksist300** [comment]
> As a new contributor, we encourage you to read our [contributing guidelines](https://contribute.freecodecamp.org).
> 
> We expect our contributors to be aware of the process specific to this project. Following the guidelines religiously earns you the respect of fellow maintainers and saves everyone time.
> 
> Some examples of this are:
> 
>     1. Do not edit files directly through GitHub – while you can, it's not a good idea.
> 
>     2. Make sure you follow the PR checklist and not just tick things off; otherwise, we won't take you seriously.
> 
>     3. Use the correct way to link issues in the description of the PR by updating the `XXXXXX`. Do not just add issue numbers everywhere and anywhere you feel like.
> 
>     4. Keep mentions and review requests to a minimum. We understand you are excited about contributing, and our maintainers will get back to you as soon as they get a chance.
> 
>     5. Do not work directly off your `main` branch - create a new branch for the changes you are working on.
> 
> 
> We appreciate you taking the time to help us, and we hope to see more contributions from you.
> 
> Happy Contributing.

Hi @raisedadead I Have made changes to the title, if there is something in particular you would like me to change to get this reviewed, I'd be happy to. Just let me know 🙂👍

**Review by Sboonny — APPROVED** [review]
LGTM 🎉, thank you for your contribution to the page! 👍.

**Review by raisedadead — APPROVED** [review]
I encourage you to revise the "how to open a pull-request" section of the contributing guide. 

Thanks for the PR.

**Pull request merged**
