### PR TITLE
fix(client): remove multiple redirects after account deletion

### LINKED ISSUE #39508: Account deletion redirects too quickly
**Describe the bug**
Deleting your account works as expected, but it also redirects users to /signin immediately after signing them out. This means the "Your account has successfully been deleted" message only appears for a split second before it disappears. I knew to look for it, but most users would not. Meaning they might misunderstand and think their account has not been deleted successfully.

**To Reproduce**
1. Go to the bottom of /settings
2. Click the "delete my account" button and confirm.
3. You will be redirected twice – once to the unauthenticated landing page, and then immediately afterward to /signin

### PR DESCRIPTION
**Pull request by Prathamesh010**
Checklist:

- [x] I have read [freeCodeCamp's contribution guidelines](https://contribute.freecodecamp.org).
- [x] My pull request has a descriptive title (not a vague title like `Update index.md`)
- [x] My pull request targets the `main` branch of freeCodeCamp.
- [x] I have tested these changes either locally on my machine, or GitPod.

Closes #39508

### CODE REVIEW

**Review by Sboonny — COMMENTED** [review]
Bruh, I wanted to solve it, after I have finished external links issue.  

Anyway nicely done 👍

**Review by raisedadead — APPROVED** [review]

**Comment by raisedadead** [comment]
Nice work @Prathamesh010, on fixing this long pending issue - I will wait on someone from @freeCodeCamp/dev-team to confirm and merge this.

**Review by naomi-lgbt — APPROVED** [review]
This looks good on my end. Thanks for fixing this!

**Comment by nhcarrigan** [comment]
Thank you for your contribution to the page! 👍
We are happy to accept these changes and look forward to future contributions. 🎉

**Pull request merged**
