### PR TITLE
fix(CI): Remove Friendly Date Ranges

### LINKED ISSUE #12305: Challenge - Friendly Date Ranges: Solution breaks build
The current solution for `Friendly Date Ranges` currently breaks the build.

A PR is needed to update the solution in the seed files to be more robust.

The code for the challenge can be found [here](https://github.com/FreeCodeCamp/FreeCodeCamp/blob/4598f5b42141a1d72e3f727059302e6eefb50f72/seed/challenges/01-front-end-development-certification/advanced-bonfires.json#L383)

### PR DESCRIPTION
**Pull request by raisedadead**
Fixes build. 
/cc @Bouncey @QuincyLarson 

Tested on my fork 
https://travis-ci.org/raisedadead/FreeCodeCamp/builds/188193673

Closes #12305

### CODE REVIEW

**Review by systimotic — APPROVED** [review]
👍 LGTM! What would be the best way to re-run the tests on the other open PR's? Once this is merged, would pulling in the latest changes and force-pushing them work?

**Comment by raisedadead** [comment]
@systimotic that's unnecessary, triggering the re-builds on should be enough.

**Comment by BerkeleyTrue** [comment]
@raisedadead @systimotic You would need to rebase your PR's on latest staging for test to get passing again

**Comment by systimotic** [comment]
Based on what Mrugesh said, I went exploring and found out you can indeed restart builds, if you log in with GitHub on Travis CI 🎉 All builds are now passing

**Pull request merged**
