### PR TITLE
Replace jsonlint with jsonlint-cli

### PR DESCRIPTION
**Pull request by systimotic**
#### Pre-Submission Checklist

- [x] Your pull request targets the `staging` branch of FreeCodeCamp.
- [x] Branch starts with either `fix/`, `feature/`, or `translate/` (e.g. `fix/signin-issue`)
- [x] You have only one commit (if not, [squash](http://forum.freecodecamp.com/t/how-to-squash-multiple-commits-into-one-with-git/13231) them into one commit).
- [x] All new and existing tests pass the command `npm run test-challenges`. Use `git commit --amend` to amend any fixes.
#### Type of Change

- [x] Small bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds new functionality)
- [ ] Breaking change (fix or feature that would change existing functionality)
- [ ] Add new translation (feature adding new translations)
#### Checklist:

- [x] Tested changes locally.
- [ ] Closes currently open issue (replace XXXX with an issue no): Closes #XXXX
#### Description

Part one of fixing `npm test` on Windows (#10885). By replacing `jsonlint` with `jsonlint-cli` (as suggested by @BerkeleyTrue) we fix the json linting on Windows. `jsonlint` was failing because it doesn't handle glob paths (paths with a \* in them). This is one of the main things mentioned by `jsonlint-cli`, it seems we're not the only ones with this issue 😄
The `-q` option is removed. `jsonlint-cli` does not support this option, rather it doesn't log anything by default as long as there are no errors.

### CODE REVIEW

**Comment by BerkeleyTrue** [comment]
Please us the snyk protect utility to add the patch to this module

**Comment by systimotic** [comment]
On it!

**Comment by systimotic** [comment]
I'm sorry, it seems like I just broke something. Snyk really doesn't want to be friends with me. I'm trying to figure it out...

**Comment by BerkeleyTrue** [comment]
Hmm... how did you go down in version? Maybe you need to update your global snyk?

**Comment by systimotic** [comment]
@BerkeleyTrue Both that, and another issue with Snyk on Windows. It fails in both the default Windows console and their recommended console, Git Bash. I managed to make it work in Cmder. Should be good to go now, sorry for the hassle!

**Comment by BerkeleyTrue** [comment]
@systimotic Nice work!

**Comment by ivantedja** [comment]
@systimotic  so `npm test` works on Windows now? 💯

**Comment by systimotic** [comment]
@ivantedja Indeed it does! This PR combined with #11409 fixes the test suite on Windows.

**Pull request merged**
