### PR TITLE
fix map header and scrolling

### LINKED ISSUE #10621: Full screen map view should not scroll independently
The freecodecamp.com/map view has two independently scrolling sections. See screenshot below.

- As a user, when I scroll down - with mouse anywhere in the view - the map should scroll. Currently, I have to mouse over the central column.

- As a user, the top map navigation component should always remain fixed at the top (and not be scrollable like in the above picture).

### PR DESCRIPTION
**Pull request by dhcodes**
#### Pre-Submission Checklist

- [X] Your pull request targets the `staging` branch of FreeCodeCamp.
- [X] Branch starts with either `fix/`, `feature/`, or `translate/` (e.g. `fix/signin-issue`)
- [X] You have only one commit (if not, [squash](http://forum.freecodecamp.com/t/how-to-squash-multiple-commits-into-one-with-git/13231) them into one commit).
- [X] All new and existing tests pass the command `npm run test-challenges`. Use `git commit --amend` to amend any fixes.
#### Type of Change

- [X] Small bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds new functionality)
- [ ] Breaking change (fix or feature that would change existing functionality)
- [ ] Add new translation (feature adding new translations)
#### Checklist:

- [X] Tested changes locally.
- [X] Closes currently open issue (replace XXXX with an issue no): Closes #10621 
#### Description

I updated the Map.jsx file with a variable that changes depending on if the map is generated in a drawer or not. I updated the CSS to apply the fixed classes to the map when it's not in the drawer. The margins are a bit hackish but it's the only way I could get it to work since both the drawer map and full page map use the same module.

### CODE REVIEW

**Comment by hallaathrad** [comment]
Looks ok to me :1:

**Comment by dhcodes** [comment]
I tested it on Chrome, Safari, and Firefox, but not on IE.

**Comment by hallaathrad** [comment]
Ditto. I'll test on windows later tonight when I get home

**Comment by systimotic** [comment]
I just tested it in Edge and IE, works fine!

**Comment by hallaathrad** [comment]
So had I but forgot to update it here... lol
Let's git-r-done!

**Pull request merged**
