### PR TITLE
New feature to allow users to easily pair with each other

### PR DESCRIPTION
**Pull request by MrRenter**
Adds a feature to allow users to easily pair for live coding. They can create a status and be visibly available. When someone wants to pair up they can click on the users post and instantly be put into a gitter chat with that person.

This was done with the help of @aldraco Either of us can be contacted with questions or for an explanation.

### CODE REVIEW

**Comment by terakilobyte** [comment]
Sorry to get back so late. Looks ok, but the code style is vastly different from what we use. What is your indent set at? Please reformat these files to use 2 spaces for all indents (original and continuation). CC @aldraco

**Comment by aldraco** [comment]
Actually, we should fix the README as well. Just saw that.

**Comment by aldraco** [comment]
As we have abandoned Gitter, some of the implementation will have to change to use Slack.

What does everyone think about perhaps using a bot type system where when users 'go online,' it posts an automatic message in slack? either the main channel or the help channel?

The pair channel is usually just a little dead, so the main channel might get a little more traction. On the other hand, it could get annoying really fast.

Thoughts?

**Comment by MrRenter** [comment]
Public announcements can be made with https://api.slack.com/slackbot
Chats can be embed with using urls such as https://freecode.slack.com/messages/@aldraco/ instead of the gitter ones.

**Comment by aldraco** [comment]
right - we would need to set up a remote integration for the bot. (or use one that is already set up - either way it requires an API key)

**Comment by aldraco** [comment]
A new PR was made to another branch. #322

**Pull request closed without merging**
