### PR TITLE
fix: resolve typos in catdog classifier

### PR DESCRIPTION
**Pull request by naomi-lgbt**
Checklist:

- [X] I have read [freeCodeCamp's contribution guidelines](https://contribute.freecodecamp.org).
- [X] My pull request has a descriptive title (not a vague title like `Update index.md`)
- [X] My pull request targets the `main` branch of freeCodeCamp.
- [X] I have tested these changes either locally on my machine, or GitPod.

Closes #XXXXX

### CODE REVIEW

**Comment by RandellDawson** [comment]
@naomi-lgbt Looks good, however I noticed on [the boilerplate PR](https://github.com/freeCodeCamp/boilerplate-cat-and-dog-image-classifier/pull/2/files#), there were two other changes:
1. On line 102 of the boilerplate PR, the user changed `floating point` to `floating-point`.  Which is correct?
2. On line 177 of the boilerplate PR, the user added a comma after the words `training examples`.  I think the comma should be there too.

**Comment by naomi-lgbt** [comment]
Thanks for catching those - I've pushed those up.

I'm not sure if `floating-point` is the standard - Wikipedia seems to include the hyphen most of the time, so I went with including it here too.

**Review by RandellDawson — APPROVED** [review]
OK, everything looks good now!

**Review by Sboonny — APPROVED** [review]
LGTM 🎉, thank you for your contribution to the page! 👍.

**Pull request merged**
