### PR TITLE
fix(client): update middleware names of helmet.js tests

### LINKED ISSUE #39190: Broken tests on multiple challenges in the Information Security with HelmetJS
**Describe your problem and how to reproduce it:**
Multiple challenge tests fail for no obvious reasons related to the challenge -
1. Mitigate the Risk of Clickjacking with helmet.frameguard()
2. Prevent IE from Opening Untrusted HTML with helmet.ieNoOpen()
3. Disable DNS Prefetching with helmet.dnsPrefetchControl()

**Add a Link to the page with the problem:**
https://glitch.com/edit/#!/busy-rambunctious-tern
this server fails the tests for reasons beyond my understanding.
I tried to replicate the server on a different service and tweak the tests and I still don't understand the cause.
https://repl.it/@obsessedyouth/DiligentAnchoredObservation#package.json

**Tell us about your browser and operating system:**
* Browser Name: 
Google Chrome
* Browser Version: 
Version 83.0.4103.116 (Official Build) (64-bit)
* Operating System: 
Windows 10 Enterprise

**If possible, add a screenshot here (you can drag and drop, png, jpg, gif, etc. in this box):**
Screenshot (330)
Screenshot (329)
Screenshot (328)

### PR DESCRIPTION
**Pull request by hailelagi**
Checklist:

- [x] I have read [freeCodeCamp's contribution guidelines](https://contribute.freecodecamp.org).
- [x] My pull request has a descriptive title (not a vague title like `Update index.md`)
- [x] My pull request targets the `master` branch of freeCodeCamp.
- [x] All the files I changed are in the same world language, for example: only English changes, or only Chinese changes, etc.

Closes #39190

Updated the names of renamed helmet.js middleware breaking tests

### CODE REVIEW

**Review by ShaunSHamilton — DISMISSED** [review]
Thank you, for getting this out. I was able to pass all of the challenges, using the latest version of _helmetjs_. This LGTM 👍 

I will leave it to you @RandellDawson to decide if we need to introduce some sort of backwards compatibility.

**Review by naomi-lgbt — DISMISSED** [review]
LGTM! Unless the decision is made to add backwards compatibility.

**Comment by moT01** [comment]
I have changed this to pin the version of helmet as was the consensus in the issue. [My project is here](https://tidy-roadway.glitch.me/) if anyone wants to use it for testing. 

I also added a PR on the boilerplate for these changes linked above

**Review by ShaunSHamilton — APPROVED** [review]
This LGTM 👍 

Thanks, for providing your project, Tom.

**Review by naomi-lgbt — APPROVED** [review]
LGTM!

**Comment by Sky020** [comment]
Congratulations on your first PR, @obsessedyouth!

We look forward to future contributions.

**Comment by obsessedyouth** [comment]
oh wow I'm so happy! I was not expecting this to eventually get merged! ❤ looking forward to making future contributions

**Pull request merged**
