### PR TITLE
[WIP] Feat: challenge file validators

### LINKED ISSUE #36740: [curriculum] Commented code is getting accepted in a challenge
**Describe your problem and how to reproduce it:**
After commenting the code in a [challenge](https://www.freecodecamp.dev/learn/responsive-web-design/responsive-web-design-principles/make-typography-responsive), the tests are passing. I think the issue is with this particular challenge only as I have solved many challenges and I haven't observed this bug in any of them.

bug

**Add a Link to the page with the problem:**
https://www.freecodecamp.dev/learn/responsive-web-design/responsive-web-design-principles/make-typography-responsive

**Tell us about your browser and operating system:**
* Browser Name: Chrome
* Browser Version: 76.0.3809.132 (Official Build) (32-bit)
* Operating System: Windows 10 Pro

### PR DESCRIPTION
**Pull request by Bouncey**
- [x] I have read [freeCodeCamp's contribution guidelines](https://github.com/freeCodeCamp/freeCodeCamp/blob/master/CONTRIBUTING.md).
- [x] My pull request has a descriptive title (not a vague title like `Update index.md`)
- [x] My pull request targets the `master` branch of freeCodeCamp.
- [x] None of my changes are plagiarized from another source without proper attribution.
- [x] All the files I changed are in the same world language (for example: only English changes, or only Chinese changes, etc.)
- [x] My changes do not use shortened URLs or affiliate links.

Closes #36740

A PR to introduce a new challenge testing mechanism to do away with horrible RegEx tests we currently use for checking users code for correctness.

In all the `.md` changes, these files are they only ones to use the new validators

`basic-html-and-html5/say-hello-to-html-elements.english.md`
`responsive-web-design-principles/make-typography-responsive.english.md`

The rest of the `.md` files change test functions from
`testString: getUserInput => ` to `testString: ({ getUserInput }) => `

## TODO
- [ ] Docs

### CODE REVIEW

**Comment by RandellDawson** [comment]
@Bouncey Shouldn't there be more files affected?  I see English and non-English challenges in the mix, but there are 1462 English challenges, so I expected to see more total files affected.

**Comment by Bouncey** [comment]
Only the `testString`'s that use `getUserInput` should be affected by this api change

**Comment by Bouncey** [comment]
@RandellDawson, sorry for the confusion, I have been editing the description like a mad-man and it is likely you missed on of my recent edits.

**Comment by ojeytonwilliams** [comment]
@Bouncey this looks really cool, it's going make the tests much easier to understand!  One thing I was wondering, though, could we pass in the validators in such a way that we can destructure them?  Namely instead of

```js
({ getFileValidator }) => {
  const validator = getFileValidator();
  const css = validator.getCssValidator();
  // stuff
}
```
we'd have something like
```js
({ validators: {css, validator}}) => {
  // stuff
}
```

As far as I can see this would mean we'd have to pass in the results of `getFileValidator()` and `getCssValidator()`. There would be a problem if the `fileName` was not `'index'`, but I think it always is.

**Comment by Bouncey** [comment]
@ojeytonwilliams I wrestled with this question myself. The main goal was to have this compatible with a multi-file editor, and having a function to pass a filename too (`getFileValidator`) made the most sense. Bear in mind that the html/css challenges are going to be the only challenges with two different syntax's to deal with, so this should be less of an issue once one is created for javascript.

**Comment by Bouncey** [comment]
I have hit an issue with the automated challenge tests and the puppeteer API. 

Only Serializable types can be passed to the `evaluate` method, which is a big no to the Validator. I'll see what I can come up with.

It is only the testing method that is failing. The validators work irl, I promise :neckbeard:

**Comment by ojeytonwilliams** [comment]
@Bouncey if filename's actually going to get used, that's fine - it just seemed superfluous at first glance. But, yeah, extra boilerplate isn't the end of the world.

**Comment by raisedadead** [comment]
Closing older PRs as decayed, please re-open afresh if still relevant.

**Pull request closed without merging**
