### PR TITLE
Update modals.less

### LINKED ISSUE #13764: The "challenge completed" dialog could use a better overlay effect
#### Issue Description

The "challenge completed" dialog seems to just change the background color, which does not loook pretty at all, even suggesting you can still interact with some elements like `inputs` and `buttons` (see screenshot below)
The best thing would be using a proper overlay that darkens the whole page, not just the background. A solution could be a full page div with a bit of transparency.
The screenshot was taken on the beta website but it applies also to the public curriculum, with some variations (the overlay effect is not applied to the code editor and the phone browser output).

#### Browser Information

* Browser Name, Version: Chrome 56.0.2924.87 (64-bit)
* Operating System: Windows 7 64bit
* Mobile, Desktop, or Tablet: desktop

#### Screenshot

overlay

### PR DESCRIPTION
**Pull request by SlyTy7**
#### Pre-Submission Checklist

- [x] Your pull request targets the `staging` branch of freeCodeCamp.
- [x] Branch starts with either `fix/`, `feature/`, or `translate/` (e.g. `fix/signin-issue`)
- [x] You have only one commit (if not, [squash](http://forum.freecodecamp.com/t/how-to-squash-multiple-commits-into-one-with-git/13231) them into one commit).
- [x] All new and existing tests pass the command `npm test`. Use `git commit --amend` to amend any fixes.

#### Type of Change

- [x] Small bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds new functionality)
- [ ] Breaking change (fix or feature that would change existing functionality)
- [ ] Add new translation (feature adding new translations)

#### Checklist:

- [x] Tested changes locally.
- [x] Closes currently open issue (replace XXXX with an issue no): Closes #13764

#### Description

Added a z-index property to the modal-backdrop class.  It now covers the proper element.  closes #13764

### CODE REVIEW

**Review by systimotic — COMMENTED** [review]
Hi @SlyTy7! Thanks a lot for this change. Sorry for the long wait, we're all very busy.

There's one thing I'm not sure about. Should the navigation bar be in front of or behind the overlay? The navbar has a z-index of 1030. The modal has a z-index of 1040. Apart from that, the maximum z-index on the page is 4.
If the current level is the level we want this to display at, anything over 4 would work. 500 may be a bit excessive. I would also be fine with 1020, as that would stick to the range of the other manually set z-indexes.

**Comment by SlyTy7** [comment]
Hi @systimotic. No worries, I understand! Yeah I wasn't sure if you wanted the overlay over the top navbar or not. Personally, I think it looks better with the overlay in front of the navbar. So maybe I should set it to 1035. How you feel about that?

**Comment by Atomk** [comment]
@SlyTy7 That's an interesting point, personally I would not cover the navbar since it's not related to the main content of the page (the challenge), it's kind of a "reference point" in the interface and should probably always be present. I'd like to hear a more informed opinion though, how do professional web apps handle this?

**Comment by raisedadead** [comment]
@Atomk Going by the UX philosophy, modals are "actionable" or "decision points" for a user, meaning, the app requires the user to interact with modal to take some decision, before any further actions are done.

So its okay to have them on top off everything else (including nav).

The reasoning, being the user should take an action on the modal, then choose to interact with the UI in any other way.

**Comment by SlyTy7** [comment]
@Atomk That makes sense to me!  So when I set the z-index to 1030, the backdrop covers everything except the modal.  I think that looks good and it will be in the same range as other z-indexes.

@systimotic Should I create a new commit with the proper z-index or should I just edit this one?

**Comment by raisedadead** [comment]
> Should I create a new pull request with the proper z-index or should I just edit this one?

@SlyTy7 you should update this pull request itself. If you need assistance, please feel free to reach out to [Contributors Chat room](https://gitter.im/FreeCodeCamp/Contributors).

**Comment by SlyTy7** [comment]
Closed PR due to not being able to squash commits when PR was submitted through the browser.  Created a new PR (#14186) through git command line with suggested changes.  Thanks everyone for the help!

**Pull request closed without merging**
