### PR TITLE
fix: Type Json and PNG file.

### PR DESCRIPTION
**Pull request by RobertoMSousa**
Checklist:

- [x] I have read [freeCodeCamp's contribution guidelines](https://contribute.freecodecamp.org).
- [x] My pull request has a descriptive title (not a vague title like `Update index.md`)
- [x] My pull request targets the `main` branch of freeCodeCamp.
- [x] I have tested these changes either locally on my machine, or GitPod.

While on navigating and refactoring some code realized that there was bo types for .json and  .png files that caused the refactor of the landing page to be harder with a bunch of error.
There was also the same issue for the json files that can be seen [here](https://github.com/freeCodeCamp/freeCodeCamp/blob/main/client/src/templates/Challenges/utils/build.js#L2).

This PR solves that and allows to remove those disable across the codebase and the use the json and png files in a safer and easier way.

### CODE REVIEW

**Comment by ojeytonwilliams** [comment]
Hi @RobertoMSousa thanks for your efforts cleaning up the code. I'm not sure this is quite the right direction, though, since we want the safety that `import/no-unresolved` provides.

What I would suggest instead is to deal with the root of the problem and make sure these files exist before the linting runs.  This should just be a matter of modifying https://github.com/freeCodeCamp/freeCodeCamp/blob/main/.github/workflows/node.js-tests.yml to use `npm run build-workers` immediately after `npm run ensure-env` in the lint step.

**Comment by RobertoMSousa** [comment]
> Hi @RobertoMSousa thanks for your efforts cleaning up the code. I'm not sure this is quite the right direction, though, since we want the safety that `import/no-unresolved` provides.
> 
> What I would suggest instead is to deal with the root of the problem and make sure these files exist before the linting runs. This should just be a matter of modifying https://github.com/freeCodeCamp/freeCodeCamp/blob/main/.github/workflows/node.js-tests.yml and https://github.com/freeCodeCamp/freeCodeCamp/blob/main/.github/workflows/node.js-tests-upcoming.yml to use `npm run build-workers` immediately after `npm run ensure-env` in the lint step.

This PR do not remove the `no-unresolved` but only disable them on the JSON files just like doing it on the files but without the extra line. All the other files still use the no-unresolved.

**Comment by ojeytonwilliams** [comment]
> This PR do not remove the no-unresolved but only disable them on the JSON files just like doing it on the files but without the extra line. All the other files still use the no-unresolved.

Sure, I understand.  The problem is that we import a lot of JSON files, not just the ones we currently have to ignore.  So, rather than disabling the linting entirely, we should enable it everywhere and fix the real problem.

To reiterate, the real problem is that some JSON files are not in version control because they're dynamically generated. To make the linter pass we should move the generation step to before the linting step.

**Comment by RobertoMSousa** [comment]
> Sure, I understand. The problem is that we import a lot of JSON files, not just the ones we currently have to ignore. So, rather than disabling the linting entirely, we should enable it everywhere and fix the real problem.
> 
> To reiterate, the real problem is that some JSON files are not in version control because they're dynamically generated. To make the linter pass we should move the generation step to before the linting step.

I don't think that's the solution because the lint is already the last thing to [run](https://github.com/freeCodeCamp/freeCodeCamp/blob/main/.github/workflows/node.js-tests.yml#L35)  but I get the idea of not removing the json no-unresolved.
Do you think we can/should at least introduce the type [here](https://github.com/freeCodeCamp/freeCodeCamp/pull/43722/files#diff-fdaa1835755ec12573ee3b1986bbe129b70196fda997234ae2df54aa99ae0059R13-R21)?

**Comment by ojeytonwilliams** [comment]
It is the last thing to run, but `build-workers` isn't currently run at all. That's why the files are missing when the linting happens

> Do you think we can/should at least introduce the type here?

I'm not 100% sure. Could you expand a little on what problem that solves?

**Comment by ojeytonwilliams** [comment]
> yes, but that would cause the build to run every time forcing every dev to have the whole repo with .env file and mongo running. Personally, I think it's a big overhead that would kill the dev experience.

I'm not quite with you.  Devs already need to do that if they want to start the site locally.  Unless you're working on the files that import generated files, not even Husky will complain when you try to commit.

That said, automatically copying `sample.env` to `.env` if the latter is missing could help. That's definitely something that trips people up.

> This whole refactor came because during the migration from JS to TS of the files I found lacking interfaces. For example, here or on any other file that uses images if we migrate to TS the lint and typecheck will fail.

Ah, nice, thanks for explaining.  Your change to the .png declaration looks like the best solution :+1:

**Comment by Sembauke** [comment]
Hey @RobertoMSousa,

I am working on #43769 to migrate the landing components to typescript.

I see that there are some conflicted files we have been migrating.

**Pull request closed without merging**
