### PR TITLE
feat: migrate filenames to IDs

### PR DESCRIPTION
**Pull request by naomi-lgbt**
Checklist:

- [X] I have read [freeCodeCamp's contribution guidelines](https://contribute.freecodecamp.org).
- [X] My pull request has a descriptive title (not a vague title like `Update index.md`)
- [X] My pull request targets the `main` branch of freeCodeCamp.
- [X] I have tested these changes either locally on my machine, or GitPod.

Closes #XXXXX

This is going to be one heck of an ugly diff. (They're all git moves, but it's a LOT of files).

A couple of things:
- This is currently blocked by #45048 - once that lands I'll rebase this and rename those files as well.
- We should merge this concurrently with #44769 so the tooling doesn't break.
- Once this lands, the steps will automatically upload to crowdin as they won't match the exclusion pattern anymore.

### CODE REVIEW

**Comment by moT01** [comment]
We should probably try to get in all the other curriculum PR's that touch RWD beta before this as well

**Comment by nhcarrigan** [comment]
image

For the sake of reviewing, the new RWD directory has 1032 files in it :)

**Review by majestic-owl448 — DISMISSED** [review]
image

let's say I trust that

**Review by ShaunSHamilton — COMMENTED** [review]
Are we wanting to rename the certification project files? I assumed not.

**Comment by nhcarrigan** [comment]
I'm fine either way.

The argument for renaming them is consistency with the file structure for the rest of the superblock.

The argument against is that they don't really need to be renamed because they're not step files.

**Review by moT01 — COMMENTED** [review]
I looked over this pretty good, I would be fine merging it.

I could go either way on renaming the cert projects. I'm fine with whatever is decided.

**Review by ShaunSHamilton — DISMISSED** [review]
LGTM 👍 
The only reviewing I could think reasonable to do is double-check we did not miss any challenges.

**Review by moT01 — CHANGES_REQUESTED** [review]
Looks like there was a typo when reverting one of the cert projects:
Screen Shot 2022-03-01 at 5 26 41 PM

**Review by moT01 — APPROVED** [review]
LGTM 🎉

**Review by ShaunSHamilton — APPROVED** [review]
LGTM 👍

**Comment by ShaunSHamilton** [comment]
I presume we can merge this now, provided #44769 gets merged soon after?

**Comment by nhcarrigan** [comment]
Should be good to go, yeah.

**Pull request merged**
