### PR TITLE
fix(curriculum): remove whitespace typo

### LINKED ISSUE #39007: JS concatenation example typo
**Describe your problem and how to reproduce it:**
Example on the page has a double space instead of a single.

`var ourStr = "I come first._" + "I come second."
// ourStr is "I come first.__I come second."`

**Add a Link to the page with the problem:**
https://www.freecodecamp.org/learn/javascript-algorithms-and-data-structures/basic-javascript/concatenating-strings-with-plus-operator

**Tell us about your browser and operating system:**
* Browser Name: Safari
* Browser Version: 13.1.1
* Operating System: macOS

**If possible, add a screenshot here (you can drag and drop, png, jpg, gif, etc. in this box):**
Skjermbilde 2020-06-04 kl  21 13 12

### PR DESCRIPTION
**Pull request by naomi-lgbt**
Checklist:

- [X] I have read [freeCodeCamp's contribution guidelines](https://contribute.freecodecamp.org).
- [X] My pull request has a descriptive title (not a vague title like `Update index.md`)
- [X] My pull request targets the `master` branch of freeCodeCamp.
- [X] All the files I changed are in the same world language, for example: only English changes, or only Chinese changes, etc.

Closes #39007 

This is my first PR so I am hoping I did this correctly. This corrects the typo pointed out in the linked issue.

### CODE REVIEW

**Comment by Twaha-Rahman** [comment]
LGTM!

**Review by crossphoton — APPROVED** [review]
The edit satisfies the issue.

**Review by ShaunSHamilton — APPROVED** [review]
LGTM 👍

**Comment by ojeytonwilliams** [comment]
@nhcarrigan Congrats on your first pull request (PR)! 🎉

Thank you for your contribution to the page! 👍
We're happy to accept these changes, and look forward to future contributions. 📝

**Pull request merged**
