### PR TITLE
fix: add backend placeholder to solution form

### LINKED ISSUE #39375: Confusing Placeholder at Backend Challenges
i found a problem that cause confusion when first trying backend challenges because at the first introduction of the challenges we were instructed to use `glitch` to solve the problem, then at the challenges, the solution placeholder shown the `codepen` link. it's kinda confusing at first! i think it will be better that the placeholder shown the glitch link for better clarity. 

https://www.freecodecamp.org/learn/apis-and-microservices/basic-node-and-express/get-route-parameter-input-from-the-client

Browser Name: Firefox 
Browser Version: 79
Operating System: Windows 10

issue1

Regards.

### LINKED ISSUE #39425: Change solution placeholder to user repl.it url
Replace codepen placeholder URL's with Repl.it URL's. I believe the only place they need to be replaced is the backend lessons. I haven't audited, but the backend projects all use the repl.it placeholders already, I believe. The backend lessons are using codepen still - they should be changed.

Screen Shot 2020-08-17 at 5 49 45 PM

### PR DESCRIPTION
**Pull request by ShaunSHamilton**
Checklist:

- [x] I have read [freeCodeCamp's contribution guidelines](https://contribute.freecodecamp.org).
- [x] My pull request has a descriptive title (not a vague title like `Update index.md`)
- [x] My pull request targets the `master` branch of freeCodeCamp.
- [x] All the files I changed are in the same world language, for example: only English changes, or only Chinese changes, etc.

Closes #39425 
Closes #39375 

One challenge type was missing in the switch

### CODE REVIEW

**Review by sudiptog81 — COMMENTED** [review]
lgtm

**Review by naomi-lgbt — DISMISSED** [review]
LGTM! Tested locally, lessons and projects reflect correct links.

**Review by RandellDawson — CHANGES_REQUESTED** [review]
@Sky020 After discussing the names of the variables with @ojeytonwilliams, I have the following suggestions to make things a bit more readable and clear:

* Rename `challengeAndFrontEndFields` to `solutionField` and then add a comment above the initialization of the variable:
  ```
  // back end challenges and front end projects use a single form field
  ``` 
* Rename `solutionFormFields` to `formFields`

The reasoning behind these suggestions is that it was a bit confusing to see a variable named `challengeAndFrontEndFields` in the following code section for the case `backend`.  In general, I have always thought this section's variable names were a bit confusing, so this is a good opportunity to fix them.
```
      case backend:
        solutionFormFields = challengeAndFrontEndFields;
        solutionLink = solutionLink + 'https://project-name.camperbot.repl.co/';
        break;
```

If you have any questions/concerns, just let me know.

**Comment by Sky020** [comment]
@RandellDawson Done and done. I am not very adept, when it comes to variable names 🤷‍♂️

**Comment by RandellDawson** [comment]
Screenshot from 2020-09-03 12-54-50

@Sky020 Thanks for making those changes.  I was testing out everything using GitPod and then realized the text above the text for these two fields could use some clean up:

I am suggesting:

Solution Link

GitHub Link (notice the capital "H" here)

Then the placeholder text for the first field should not include the "Link, " at the beginning.

If there is a reason discussed somewhere else of why this particular text was chosen, please let me know.  What are your thoughts on my suggestions?

**Comment by Sky020** [comment]
> If there is a reason discussed somewhere else of why this particular text was chosen, please let me know.

@RandellDawson , I cannot speak for this. I do not know of any such discussion.

>What are your thoughts on my suggestions?

I will definitely go ahead an add those. They are an improvement.

**Comment by Sky020** [comment]
@RandellDawson I have changed the labels as requested. However, the current implementation is convoluted, and makes it impossible to have a simple fix for changing `Github` to `GitHub`.

So, I would recommend we move ahead with the PR as is, and I will open another draft PR to refactor for the other change. It involves changing the way` FormFields.js` works, which is used by many components. So, tests will need to change along with a few other components.

**Comment by RandellDawson** [comment]
> @RandellDawson I have changed the labels as requested. However, the current implementation is convoluted, and makes it impossible to have a simple fix for changing `Github` to `GitHub`.
> 
> So, I would recommend we move ahead with the PR as is, and I will open another draft PR to refactor for the other change. It involves changing the way` FormFields.js` works, which is used by many components. So, tests will need to change along with a few other components.

@ojeytonwilliams @ahmadabdolsaheb Any thoughts here?

**Comment by RandellDawson** [comment]
@Sky020 On second thought, I am OK with the current changes as the main goal of this PR was to fix the placeholder values and that is now accomplished with your latest changes.

I will go ahead and approve this PR.  Can you please add a new GitHub issue to track the needed change from `Github Link` to `GitHub Link`?

**Review by RandellDawson — APPROVED** [review]

**Comment by RandellDawson** [comment]
@ojeytonwilliams If you want to give this another look and merge, that would be great!  Thanks.

**Comment by Sky020** [comment]
Thanks, Randell. I have submitted #39520

**Pull request merged**
