### PR TITLE
feat(client): add hotkey 'r' to focus on instructions panel

### LINKED ISSUE #38842: Keyboard Shortcut to go back and forth between reading area and editor.
**Is your feature request related to a problem? Please describe.**
I'm always frustrated when I have to reach my mouse to go back and forth between reading area and editor, just because I'm using a small screen, I can't read the whole thing and need to scroll down and then go back to editor using mouse. This causes frustration which often prevents me from coding, for long hours.

**Describe the solution you'd like**
A keyboard shortcut to go back and forth would definitely help. 

**Describe alternatives you've considered**
I have tried to scale down my browser window, but it creates readability issues, which not only makes it hard to read but it's difficult for the eyes too.  

**Screenshot**

### PR DESCRIPTION
**Pull request by gikf**
- Adds 'r' hotkey to focus on the instructions panel, when in the escape/navigation mode.
- I haven't added test for it, I recall seeing somewhere tests for hotkeys, but couldn't find them. So maybe make separate PR adding cypress tests for all hotkeys?

Checklist:

- [x] I have read [freeCodeCamp's contribution guidelines](https://contribute.freecodecamp.org).
- [x] My pull request has a descriptive title (not a vague title like `Update index.md`)
- [x] My pull request targets the `main` branch of freeCodeCamp.
- [x] I have tested these changes either locally on my machine, or GitPod.

Closes #38842

### CODE REVIEW

**Comment by raisedadead** [comment]
> * I haven't added test for it, I recall seeing somewhere tests for hotkeys, but couldn't find them. So maybe make separate PR adding cypress tests for all hotkeys?

Yes - that should be OK. Mind creating an issue and assigning it to yourself?

**Comment by Sembauke** [comment]
Hey @gikf,

If you need any help making the tests, I am here 😄

**Review by raisedadead — CHANGES_REQUESTED** [review]
LGTM. Can you drop the first commit that changes the the client package.json and lockfiles?

**Comment by gikf** [comment]
@raisedadead yes, sorry about that. I somehow botched rebasing when fixing merge conflicts, should be good now.

**Review by raisedadead — DISMISSED** [review]

**Comment by raisedadead** [comment]
Because @ojeytonwilliams forgets.

**Comment by ojeytonwilliams** [comment]
I never forget.  I just assume other people are taking care of things.

**Comment by ojeytonwilliams** [comment]
https://hitchhikers.fandom.com/wiki/Somebody_Else%27s_Problem_Field

Anyway... sorry for the delay @gikf, I'll take a look at this today :)

**Review by ojeytonwilliams — CHANGES_REQUESTED** [review]
One minor nitpick, but this is nice work.

**Review by ojeytonwilliams — APPROVED** [review]
Perfect, thanks for taking care of that extra type issue.

LGTM 👍

**Review by raisedadead — APPROVED** [review]

**Pull request merged**
