### PR TITLE
fix(curriculum): adjusted code comment in css-grid challenge to enable current validation checks

### LINKED ISSUE #38310: CSS Grid: Comment in the CSS
**Describe your problem and how to reproduce it:**

The code is listed as 
```css
  .container {
    font-size: 40px;
    min-height: 300px;
    width: 100%;
    background: LightGray;
    display: grid;
    grid-template-columns: 1fr 1fr 1fr;
    grid-template-rows: 1fr 1fr 1fr;
    grid-gap: 10px;
    grid-template-areas:
    /* Only change code below this line */
      "header header header"
      ". content content"
      "footer footer footer";
    /* Only change code above this line */
  }
``` 
When you try to submit it is failing because there is a comment in the `grid-template-areas`. If you move the comment outside of the `grid-template-areas` the code will pass. I believe it would be better to have put it as:
```css
  .container {
    font-size: 40px;
    min-height: 300px;
    width: 100%;
    background: LightGray;
    display: grid;
    grid-template-columns: 1fr 1fr 1fr;
    grid-template-rows: 1fr 1fr 1fr;
    grid-gap: 10px;
    /* Only change code below this line */    <-- This will cause the test to pass
    grid-template-areas:
      "header header header"
      ". content content"
      "footer footer footer";
    /* Only change code above this line */
  }
```
**Add a Link to the page with the problem:**
[https://www.freecodecamp.org/learn/responsive-web-design/css-grid/divide-the-grid-into-an-area-template](https://www.freecodecamp.org/learn/responsive-web-design/css-grid/divide-the-grid-into-an-area-template)

**Tell us about your browser and operating system:**
* Browser Name: Firefox Developer Edition
* Browser Version: 74.0b9
* Operating System: macOS Mojave 10.14.6

**If possible, add a screenshot here (you can drag and drop, png, jpg, gif, etc. in this box):**
image

### PR DESCRIPTION
**Pull request by hassaanp**
Checklist:

- [x] I have read [freeCodeCamp's contribution guidelines](https://github.com/freeCodeCamp/freeCodeCamp/blob/master/CONTRIBUTING.md).
- [x] My pull request has a descriptive title (not a vague title like `Update index.md`)
- [x] My pull request targets the `master` branch of freeCodeCamp.
- [x] All the files I changed are in the same world language, for example: only English changes, or only Chinese changes, etc.

Closes #38310 

The code comment is not handled in the regex. I thought it would be better to simply position the comment as suggested in the issue to get it to work.

### CODE REVIEW

**Comment by raisedadead** [comment]
Blocked by #38308

**Comment by lasjorg** [comment]
This PR https://github.com/freeCodeCamp/freeCodeCamp/pull/38256 moved the comment.

Here is the diff https://github.com/freeCodeCamp/freeCodeCamp/commit/41718abf76a6b6c53b893291cbb2d1466e364a67#diff-bccda97cc24e5954eef61a0918673dd1

Not sure if we just move it back or fix the regex.

@RandellDawson What do you think?

**Review by thecodingaviator — APPROVED** [review]
LGTM. Will be merged when code freeze is lifted

**Comment by tsabunkar** [comment]
Why is this merged block ? Currently there is an open issue #38310 which is blocking me to complete my to get Responsive Web Design Certification

**Comment by RandellDawson** [comment]
@tsabunkar We are still reviewing.  There is currently a code freeze for this section, so it may be a bit before the challenge is fixed.

FYI - You do not have to complete any of the challenges to get the certification.  You only have to complete the projects.

**Comment by tsabunkar** [comment]
> @tsabunkar We are still reviewing. There is currently a code freeze for this section, so it may be a bit before the challenge is fixed.
> 
> FYI - You do not have to complete any of the challenges to get the certification. You only have to complete the projects.

Thanks for response, I wan't aware about it, Sure I will be completeing my projects !!

**Comment by RandellDawson** [comment]
@hassaanp This fix is just a band-aid.  The true fix is ignoring the comments during the tests.  I have a PR that does this using a helper function that will be introduced in another PR very soon.  Once I have the helper function available globally, you can create another PR which uses it in the `testString`.  I am going to close this PR for now, but the issue will remain open.

**Pull request closed without merging**
