### PR TITLE
Text in Basic Data Structures lesson is better clarified.

### LINKED ISSUE #40412: Text in Basic Data Structures lesson can be better clarified.
**Describe your problem and how to reproduce it:**
The lesson Basic Data Structures: Add Items Using splice() has an introductory text which has an implication that allows for misinterpretation of the `splice()` function. We discussed this in the FCC Discord under the software development channel.

The text: "We then pass the following to splice(). The index at which to begin deleting elements (3), the number of elements to be deleted (1), and the elements (13, 14) to be inserted at that same index" implies we insert two elements in the same index. This is (to my understanding) incorrect within the context of the given example. 

The text can be improved to clarify that we _**start**_ to insert the elements from that index. 

**Add a Link to the page with the problem:**
https://www.freecodecamp.org/learn/javascript-algorithms-and-data-structures/basic-data-structures/add-items-using-splice

My apologies if I glossed over something or misinterpreted what was written in the introduction text.

### PR DESCRIPTION
**Pull request by jagadeeshg16**
Checklist:

- [x] I have read [freeCodeCamp's contribution guidelines](https://contribute.freecodecamp.org).
- [x] My pull request has a descriptive title (not a vague title like `Update index.md`)
- [x] My pull request targets the `master` branch of freeCodeCamp.
- [x] All the files I changed are in the same world language, for example: only English changes, or only Chinese changes, etc.

Closes #40412

### CODE REVIEW

**Review by RandellDawson — CHANGES_REQUESTED** [review]
@GJ-16 Your PR should only be changing the following file:
> curriculum/challenges/english/02-javascript-algorithms-and-data-structures/basic-data-structures/add-items-using-splice.md

For some reason you have also changed:
> tools/dashboard/one-off-scripts/prs-with-merge-conflicts.js

Please revert the changes to the 2nd file listed above, so we can approve this PR.

Thank you.

**Comment by RandellDawson** [comment]
@GJ-16 You deleted the file instead of reverting your changes to the file.

To revert the changes to that file, do the followiing:
```
git checkout 3af3a2e6fe~1 -- tools/dashboard/one-off-scripts/prs-with-merge-conflicts.js
git add .
git commit -m "fix: reverted changes to prs-with-merge-conflicts.js"
git push origin dsa_a_text_changes
```
The above checks out the file in one commit earlier than your original first commit.  This effectively recreates the file as it was before any of your changes. Then you just add the file to be committed and create a new commit explaining you reverted the changes.  Finally, you push the new commit back to your forked branch.

In the end you will have 3 commits but only show one file changed (the curriculum file).

Let me know if you run into any problems with the above commands.

**Comment by GJ-16** [comment]
Sorry, I messed somethings at my end. Will open new PR. Sorry again.

**Comment by GJ-16** [comment]
@RandellDawson I have some issue. 

I didn't change any other file except ```curriculum/challenges/english/02-javascript-algorithms-and-data-structures/basic-data-structures/add-items-using-splice.md```

Now I deleted the repo and forked again made change only to this file ```curriculum/challenges/english/02-javascript-algorithms-and-data-structures/basic-data-structures/add-items-using-splice.md``` then made a commit and push. 

But still changes are made to this file (```tools/dashboard/one-off-scripts/prs-with-merge-conflicts.js```) as well.

Initially I thought I made some mistake while changing the file but I'm sure I ain't do any change to this file ```tools/dashboard/one-off-scripts/prs-with-merge-conflicts.js```.

what I can do is just to edit and do a PR via Browser, but local development is not possible at moment.

Can you please help me with this?

**Comment by GJ-16** [comment]
@RandellDawson I have opened a new PR can you please check that #40492.

Thank you.

**Pull request closed without merging**
