### PR TITLE
feat: simplify development setup

### PR DESCRIPTION
**Pull request by ojeytonwilliams**
- [x] I have read [freeCodeCamp's contribution guidelines](https://github.com/freeCodeCamp/freeCodeCamp/blob/master/CONTRIBUTING.md).
- [x] My pull request has a descriptive title (not a vague title like `Update index.md`)
- [x] My pull request targets the `master` branch of freeCodeCamp.
- [x] None of my changes are plagiarized from another source without proper attribution.
- [x] All the files I changed are in the same world language (for example: only English changes, or only Chinese changes, etc.)
- [x] My changes do not use shortened URLs or affiliate links.

Warns if .env is missing. Combines the three docker installation commands into one, updating the docs accordingly.

Also removes the libcimp patch as npm already has it: 

https://github.com/npm/libcipm/blob/b66d520b12bc1ef42e6a7a51a72f2cdbdffe4d8c/index.js#L138-L141

Related to #37846

### CODE REVIEW

**Comment by ojeytonwilliams** [comment]
@raisedadead the tests are failing because Travis doesn't have .env and doesn't have `FREECODECAMP_NODE_ENV=production`.  Could this be set for Travis?

I tried it locally and the only oddity I found was that the `--inspect` port has to be specified or it will clash on `npm run develop`.  Once you do it seems fine.  Not that that matter for the tests, of course.

**Comment by raisedadead** [comment]
I have added this to the settings. Thanks for letting me know.

**Comment by raisedadead** [comment]
> I have added this to the settings. Thanks for letting me know.

Oh, wait I realised that the env var should be enable a lot of other errors. Will take a look and let you know. removed the var for now.

**Comment by ojeytonwilliams** [comment]
> Oh, wait I realised that the env var should be enable a lot of other errors

It does, but I think they only trigger when you try to start the server or the client.  Neither of which Travis should be doing.

**Comment by raisedadead** [comment]
And you would be correct, I think it cries about the missing location and keys when `ensure-env` script is run.

**Comment by ojeytonwilliams** [comment]
Oh, of course. 

```js
    throw new Error(`One or more locations are missing, all are required.

    api: ${api}
    newsProxy: ${newsProxy}
    forumProxy: ${forumProxy}

    `);
```

 I'll see if I can work around that.

**Comment by ojeytonwilliams** [comment]
@raisedadead well, this worked! Can you think of a reason not to do this?

**Comment by raisedadead** [comment]
> Can you think of a reason not to do this?

I do not this its going to be a problem for now or these specific vars.

**Pull request merged**
