### PR TITLE
Added solution for English/Data-Visualization/Hover-tod3-element

### PR DESCRIPTION
**Pull request by dbsimeonov**
- [x] I have read [freeCodeCamp's contribution guidelines](https://github.com/freeCodeCamp/freeCodeCamp/blob/master/CONTRIBUTING.md).
- [x] My pull request has a descriptive title (not a vague title like `Update index.md`)
- [x] My pull request targets the `master` branch of freeCodeCamp.
- [x] None of my changes are plagiarized from another source without proper attribution.
- [x] All the files I changed are in the same world language (for example: only English changes, or only Chinese changes, etc.)
- [x] My changes do not use shortened URLs or affiliate links.

### CODE REVIEW

**Review by RandellDawson — CHANGES_REQUESTED** [review]
@dbsimeonov You must provide a full working solution of the code.  This means you must include **all** the challenge seed code plus and changes to pass the tests.

**Comment by dbsimeonov** [comment]
@RandellDawson  I've made the requested changes, ready for preview.

**Review by moT01 — APPROVED** [review]
LGTM

**Review by RandellDawson — APPROVED** [review]
@dbsimeonov Thanks for making the changes.  LGTM

**Comment by RandellDawson** [comment]
Thank you for your contribution to the page! 👍
We're happy to accept these changes, and look forward to future contributions. 🎉

**Pull request merged**
