### PR TITLE
Update index.md

### PR DESCRIPTION
**Pull request by priteshpk**
Added other ways to print data

- [x] I have read [freeCodeCamp's contribution guidelines](https://github.com/freeCodeCamp/freeCodeCamp/blob/master/CONTRIBUTING.md).
- [x] My pull request has a descriptive title (not a vague title like `Update index.md`)
- [x] My pull request targets the `master` branch of freeCodeCamp.
- [x] None of my changes are plagiarized from another source without proper attribution.
- [x] My article does not contain shortened URLs or affiliate links.

If your pull request closes a GitHub issue, replace the XXXXX below with the issue number.

Closes #XXXXX

### CODE REVIEW

**Comment by bubblebenj** [comment]
Were you serious when you checked?
> My pull request has a descriptive title (not a vague title like Update index.md)

**Comment by CodingSolo** [comment]
Please use PR titles which explain what you are changing instead of "Update index.md." 
**Preview your change** before you submit a pull request and format your article correctly with [Markdown](https://guides.github.com/features/mastering-markdown/)

Thank you

**Review by Manish-Giri — CHANGES_REQUESTED** [review]
Hi @priteshpk

Please provide code samples explaining the usage of the other ways to print data that you mentioned.

**Review by Manish-Giri — COMMENTED** [review]
Hi,

As there has been no response from your end for a while, I am closing this PR.

Feel free to re-open it if you wish to apply the suggested changes.

Happy Coding!

**Pull request closed without merging**
