### PR TITLE
Fixes a typo in target a specfic child of an element waypoint

### LINKED ISSUE #5334: Typo in "Target a Specific Child of an Element" waypoint
I've found a typo in [Waypoint: Target a Specific Child of an Element Using jQuery](http://www.freecodecamp.com/challenges/waypoint-target-a-specific-child-of-an-element-using-jquery) in the following paragraph:

> Here's how you would give the third element in each well bounce:

In my opinion "give" needs to be replaced with "make" because the expression is "make bounce" and not "give bounce". Or it could be "give a bounce", so only an "a" would be missing in this case.

The two corrections could therefore be:

1:
> Here's how you would make the third element in each well bounce:

2: 
> Here's how you would give the third element in each well a bounce:

I'm not a native English speaker, so native speakers please correct me if I'm wrong.

### PR DESCRIPTION
**Pull request by raisedadead**
closes #5334 

The current text now reads:

> Here's how you would give the third element in each well the bounce class

I have tested locally.

### CODE REVIEW

**Comment by BerkeleyTrue** [comment]
Please change the title to be descriptive of the changes you have made.

Also state which issues, if any, that this PR closes in the description each on its own line. For example: `closes #1337`

see [Pull-Request-Contribute](https://github.com/FreeCodeCamp/FreeCodeCamp/wiki/Pull-Request-Contribute)

**Comment by raisedadead** [comment]
@BerkeleyTrue : Sorry messed up the first PR! Will take care next time. Do you want me to close this and do a new one? Github will not close the issue right?

**Comment by BerkeleyTrue** [comment]
No it is fine now. Thanks for making those changes.

**Comment by ltegman** [comment]
Thanks! :+1:

**Pull request merged**
