### PR TITLE
fix(curriculum): typos in BETA  Piano Build section

### PR DESCRIPTION
**Pull request by Kernix13**
Checklist:

- [x] I have read [freeCodeCamp's contribution guidelines](https://contribute.freecodecamp.org).
- [x] My pull request has a descriptive title (not a vague title like `Update index.md`)
- [x] My pull request targets the `main` branch of freeCodeCamp.
- [x] I have tested these changes either locally on my machine, or GitPod.

Steps 11, 13, and 16 all include the hash or period when mentioning the id or class name. I believe you want the users to know that they need to add that, so I removed the `#` and `.` in those steps. I also added the word `element` in step 13 to stay consistent with the other steps.

### CODE REVIEW

**Comment by nhcarrigan** [comment]
> I believe you want the users to know that they need to add that, so I removed the # and . in those steps.

Actually, we use that syntax to indicate that we are referring to an element by its class/id. There is no `piano` element, but a `#piano` element would be the element with the `id="piano"` attribute.

**Comment by Kernix13** [comment]
I've been running through all the sections, and if my memory is correct, that is the first time the # or . symbols were used. In the text, it mentions "id" and "class" along with the name of each that is in the HTML, but previous lessons did not actually include the CSS symbols in front of the id/class names. 

If you want I'll go back to a previous section and see if I can find a similar lesson where those symbols are not included. Or if you are positive, then I can undo those changes and do another `push`.

**Comment by Kernix13** [comment]
Actually, here is an example from the Picasso Painting section. I had just finished this one when I went through the Piano section: 

https://www.freecodecamp.org/learn/2022/responsive-web-design/learn-intermediate-css-by-building-a-picasso-painting/step-46

On the first line, you can see that `#` is not in front of `white-paper`.

**Comment by nhcarrigan** [comment]
Hmm, in the ones I wrote I used the symbol - I'm pretty sure @ShaunSHamilton did too. 🤔

**Comment by Kernix13** [comment]
I don't care either way, but that is what I remember from previous steps in other sections. However, I am working from top to bottom and I just started the Skyline section. After that, I have the Magazine, Penguin, and Ferris Wheel sections. Are they some of the ones that you and Shaun did? If so, I don't want to make changes if I'll be undoing them later. 

I'll sit tight. I only changed 3 steps so reversing them is no big deal.

**Comment by ShaunSHamilton** [comment]
My opinion is, once the Camper has been taught the selector syntax, it should be used to refer to the element(s).

As such, the only thing I would have in this PR is the addition of the word "elements", after `.keys`.

Using the programming terminology early on is useful because:
a) It is common to see out in the wild
b) It helps Campers think in terms of HTML/CSS
c) It is the common language we devs all speak across the globe

**Comment by Kernix13** [comment]
Ok, so I'll set those to steps back to what they were and push those leaving just the `element` add.

**Review by ShaunSHamilton — APPROVED** [review]
Thank you, @Kernix13 

LGTM 👍

**Review by Sembauke — APPROVED** [review]

**Pull request merged**
