### PR TITLE
Add the GitHub Stars count

### PR DESCRIPTION
**Pull request by raisedadead**
image

**Description :**
Done with a jQuery AJAX Client side request.

Tested locally.

### CODE REVIEW

**Comment by raisedadead** [comment]
Refers #6387

**Comment by BerkeleyTrue** [comment]
You'll need to add a comma to that number.

**Comment by raisedadead** [comment]
@BerkeleyTrue Yup. Thanks, just an oversight! Should be good now!

**Comment by QuincyLarson** [comment]
@raisedadead thank you for implementing this. I had forgotten that I had even mentioned this on #6387. I do not think we should show our star count on the About page. Sorry for the unnecessary work.

**Pull request closed without merging**
