### PR TITLE
test(e2e,playwright): Flash

### PR DESCRIPTION
**Pull request by rohitrai3**
Checklist:

- [x] I have read and followed the [contribution guidelines](https://contribute.freecodecamp.org).
- [x] I have read and followed the [how to open a pull request guide](https://contribute.freecodecamp.org/#/how-to-open-a-pull-request).
- [x] My pull request targets the `main` branch of freeCodeCamp.
- [x] I have tested these changes either locally on my machine, or GitPod.

Solves "UI Components/Flash" >  #51705

camperbot cant code

### CODE REVIEW

**Comment by rohitrai3** [comment]
Waiting for https://github.com/freeCodeCamp/freeCodeCamp/pull/51893 to get merge as it contains tthe solution for CI error.

**Comment by ojeytonwilliams** [comment]
Hi, unfortunately we need to keep the code that's deleting the csrf_token cookie for the foreseeable future. It seems to be necessary for some users and we won't have time to dig into why for a while. Since that means this spec will not pass on webkit, could you [skip it](https://playwright.dev/docs/api/class-test#test-skip-3) for that `browserName`?

**Review by naomi-lgbt — APPROVED** [review]

**Comment by rohitrai3** [comment]
> Hi, unfortunately we need to keep the code that's deleting the csrf_token cookie for the foreseeable future. It seems to be necessary for some users and we won't have time to dig into why for a while. Since that means this spec will not pass on webkit, could you [skip it](https://playwright.dev/docs/api/class-test#test-skip-3) for that `browserName`?

Fixed it by skipping test for webkit as described by you.

**Review by huyenltnguyen — COMMENTED** [review]
Hey @rohitrai3, thank you for the PR!

We have already merged https://github.com/freeCodeCamp/freeCodeCamp/pull/51886 and will need to close this one unfortunately. However, we are going to label this PR with `hacktoberfest-accepted` still, so that your efforts are counted. We hope you won't be discouraged by this, and we look forward to your future contributions.

Happy contributing!

**Pull request closed without merging**
