### PR TITLE
fix: correct Rosetta Code Knight's tour solution

### LINKED ISSUE #40055: Rosetta Code: Knight's tour tests likely don't output correct values
**Describe your problem and how to reproduce it:**
In my opinion, I would recommend for this problem that only one path for an 8x8 chessboard is found.  See the official challenge: https://rosettacode.org/wiki/Knight's_tour

**The known issue though** is that one line of code says `knightTour(6, 6) should return 35`.  However, a 6x6 chessboard contains a closed tour, so the answer should be 36.  Here is one example: https://www.markkeen.com/knight/images/Untitled7.gif

Because of the symmetric nature of a chessboard, this number wouldn't make sense anyway, as it claims that only one square can't be a starting point.  It could also be that the other results are not correct.

**Add a Link to the page with the problem:**
https://forum.freecodecamp.org/t/freecodecamp-challenge-guide-knights-tour/302297 and
https://www.freecodecamp.org/learn/coding-interview-prep/rosetta-code/knights-tour

**Tell us about your browser and operating system:**
* Browser Name: Firefox
* Browser Version: 82
* Operating System: Linux

### PR DESCRIPTION
**Pull request by gikf**
* Corrects expected answers in tests and test descriptions
* Replaces sample solution with solution giving correct answers
* Corrects small typo with missing space
* Changes were tested on the local fork

More information about problem can be found on the issue page, which this pull request can close.

Checklist:

- [x] I have read [freeCodeCamp's contribution guidelines](https://contribute.freecodecamp.org).
- [x] My pull request has a descriptive title (not a vague title like `Update index.md`)
- [x] My pull request targets the `master` branch of freeCodeCamp.
- [x] All the files I changed are in the same world language, for example: only English changes, or only Chinese changes, etc.

Closes #40055

### CODE REVIEW

**Comment by gikf** [comment]
I'm not sure why that check is failing...

Locally now it's also behaving strange, one time `npm run test:curriculum --superblock=coding-interview-prep` is passing, the next one it's failing. Could the reason be timeout when running that one failing test case?

**Comment by nhcarrigan** [comment]
Looks like it could be a timeout issue, yes - I'll go ahead and re-run the check. 🙂

**Comment by gikf** [comment]
Thanks :), result was the same, as kind of expected. Latest commit stops problem from occurring.

**Review by naomi-lgbt — APPROVED** [review]
Looks good to me.

**Review by moT01 — APPROVED** [review]
LGTM @gikf 🎉 Thanks for fixing this up, we look forward to future contributions 🎉 

I updated the forum post to use this solution.

**Pull request merged**
