### PR TITLE
feat: add code highlighting to descriptions in the new editor

### PR DESCRIPTION
**Pull request by scissorsneedfoodtoo**
Checklist:

- [x] I have read [freeCodeCamp's contribution guidelines](https://contribute.freecodecamp.org).
- [x] My pull request has a descriptive title (not a vague title like `Update index.md`)
- [x] My pull request targets the `main` branch of freeCodeCamp.
- [x] I have tested these changes either locally on my machine, or GitPod.

Closes #XXXXX

This PR adds Prism highlighting to descriptions in the editor for the new project-based curriculum. It shouldn't affect the editor for older challenges.

Here's a screenshot of an HTML snippet from Part 20 of the new Cat Photo App project after these changes:

image

### CODE REVIEW

**Review by ojeytonwilliams — APPROVED** [review]
LGTM :+1: Cheers, @scissorsneedfoodtoo!

**Review by Nirajn2311 — APPROVED** [review]
LGTM 👍

**Comment by scissorsneedfoodtoo** [comment]
Happy to help! Thank you both for the review.

**Comment by ojeytonwilliams** [comment]
Not at all, I'm really happy you found such a neat solution.

**Pull request merged**
