### PR TITLE
added description about a nonallowed method

### PR DESCRIPTION
**Pull request by Atakannbal**
Checklist:

- [x] I have read [freeCodeCamp's contribution guidelines](https://contribute.freecodecamp.org).
- [x] My pull request has a descriptive title (not a vague title like `Update index.md`)
- [x] My pull request targets the `master` branch of freeCodeCamp.
- [x] All the files I changed are in the same world language, for example: only English changes, or only Chinese changes, etc.

### CODE REVIEW

**Comment by nhcarrigan** [comment]
This is mentioned in a test case - is there a need to mention it in the description as well?

**Comment by Atakannbal** [comment]
> This is mentioned in a test case - is there a need to mention it in the description as well?

It is mentioned both in the test case and description on a previous challange called "confirm the ending".
It'd add consistency and remove an extra step towards completion & indirectly teach that you <em> could </em> use it.

so in terms of user experience - since I missed it myself - I thought it could be better.

**Review by naomi-lgbt — APPROVED** [review]
LGTM~! 🥳 Congratulations on your first pull request!

As a note, our workflow requires at least one additional approval before this can be merged.

**Review by majestic-owl448 — APPROVED** [review]
LGTM! and I am going to merge this, so congratulations on your first contribution!

**Pull request merged**
