### PR TITLE
Update Certifications Pages Button Text

### LINKED ISSUE #8261: Update Certifications Pages
#### Challenge Name
[Claim Your Front End Development Certificate](https://www.freecodecamp.com/challenges/claim-your-front-end-development-certificate)

#### Issue Description
At the URL: 
`https://www.freecodecamp.com/challenges/claim-your-front-end-development-certificate` in step 2 

there is supposed to have a link about Plagiarism, probably this one: 
`https://en.wikipedia.org/wiki/Plagiarism`

instead there is an empty anchor and doesn't open anything:
`https://www.freecodecamp.com/challenges/claim-your-front-end-development-certificate#`

#### Browser Information
Google Chrome 

* Browser Name, Version: 49.0.2623.112 m
* Operating System: Windows 10
* Mobile, Desktop, or Tablet: Desktop

### PR DESCRIPTION
**Pull request by hangaebal**
#### Pre-Submission Checklist

- [x] Your pull request targets the `staging` branch of FreeCodeCamp.
- [x] Branch starts with either `fix/`, `feature/`, or `translate/` (e.g. `fix/signin-issue`)
- [x] You have only one commit (if not, [squash](https://github.com/FreeCodeCamp/FreeCodeCamp/wiki/git-rebase#squashing-multiple-commits-into-one) them into one commit).
- [x] All new and existing tests pass the command `npm run test-challenges`. Use `git commit --amend` to amend any fixes.
#### Type of Change

- [x] Small bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds new functionality)
- [ ] Breaking change (fix or feature that would change existing functionality)
- [ ] Add new translation (feature adding new translations)
#### Checklist:

- [x] Tested changes locally.
- [ ] Closes currently open issue (e.g. `Closes #XXXX`): Closes 
#### Description

- Certifications Page's Button "Open link in new tab" to "Confirm" 
- Other Page's Link Button is not change
  (ex: https://www.freecodecamp.com/challenges/create-a-github-account-and-join-our-chat-rooms)

Edit by @raisedadead:
I have removed the `Fix #8261 First part` because this does not completely address the issue.
Instead for PR addressing part of the issue it should be. 

Refer #8261

### CODE REVIEW

**Comment by raisedadead** [comment]
@hangaebal I have made some changes to your PR description to avoid accidental closing of the original issue, which is not the case with PR.

**Comment by raisedadead** [comment]
#### :sparkles: :sparkles: **LGTM.** :sparkles: :sparkles: 

/cc @BerkeleyTrue any potential corner cases?

**Comment by BerkeleyTrue** [comment]
LGTM

**Comment by raisedadead** [comment]
@hangaebal Thanks for contributing!

**Pull request merged**
