### PR TITLE
chore(curriculum) : Added backticks and class reference to bar word

### LINKED ISSUE #49309: visualize-data-with-a-bar-chart: "The bar elements'" in user stories 7/8/9, should place `.bar` in backticks
### Describe the Issue

Should the word 'bar' in this sentence be in a code block? 
<strong x-id="1">User Story #8:</strong> The bar elements' <code>data-gdp</code> properties should match the order of the provided data.
 The context is this project: 
https://www.freecodecamp.org/learn/data-visualization/data-visualization-projects/visualize-data-with-a-bar-chart 

Asking for translation purposes as I'm not familiar with this project.
(same question for all the user-stories with similar phrases 7/8/9)

### Affected Page

https://www.freecodecamp.org/learn/data-visualization/data-visualization-projects/visualize-data-with-a-bar-chart

### Your code

```

```

### Expected behavior

references to elements whose class is bar should use backticks around the name of the class or use the phrase ".bar" in backticks

### Screenshots

_No response_

### System

N/A

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by Vansh-Baghel**
Checklist:

- [x] I have read and followed the [contribution guidelines](https://contribute.freecodecamp.org).
- [x] I have read and followed the [how to open a pull request guide](https://contribute.freecodecamp.org/#/how-to-open-a-pull-request).
- [x] My pull request targets the `main` branch of freeCodeCamp.
- [x] I have tested these changes either locally on my machine, or GitPod.

Closes #49309

* Changed the bar text as discussed in the commit.
* Added backticks and dots to show that bar is the class.

### CODE REVIEW

**Comment by Sboonny** [comment]
The PR name doesn't follow the PR convention, you can find about it here [how to open a pull request guide](https://contribute.freecodecamp.org/#/how-to-open-a-pull-request).

It should be chore: add...

About closing the PR, you can revert the changes or undo them, this is cleaner than dealing with 3 or more PR, and we don't mind.

Normally in places that do mind, they would ask to squash the commits in the contribution guidelines. So don't worry about it

**Comment by Vansh-Baghel** [comment]
> The PR name doesn't follow the PR convention, you can find about it here [how to open a pull request guide](https://contribute.freecodecamp.org/#/how-to-open-a-pull-request).
> 
> It should be chore: add...
> 
> About closing the other PRs, you can revert the changes or undo them, this is cleaner than dealing with 3 or more PR, and we don't mind.
> 
> Normally in places that do mind, they would ask to squash the commits in the contribution guidelines. So don't worry about it and create the habit of focusing on one PR

Done 👍✅

**Review by Sboonny — APPROVED** [review]
#### :sparkles: :tada: **AWESOME!** :tada: :sparkles:

 Hi @Vansh-Baghel, thanks for this pull request and for contributing to the code-base for the first time. We are looking forward to more contributions from you in the future.

 Cheers & happy contributing!

**Review by jeremylt — APPROVED** [review]
LGTM

**Pull request merged**
