### PR TITLE
Updated index.md with new resources.

### PR DESCRIPTION
**Pull request by moingshaikh**
Added three new JS books for beginners and also added a resource/link to the FreeCodeCamp's Medium blog-post aimed for beginners to help them with their JS study plan.

- [x] I have read [freeCodeCamp's contribution guidelines](https://github.com/freeCodeCamp/freeCodeCamp/blob/master/CONTRIBUTING.md).
- [x] My pull request has a descriptive title (not a vague title like `Update index.md`)
- [x] My pull request targets the `master` branch of freeCodeCamp.
- [x] None of my changes are plagiarized from another source without proper attribution.
- [x] My article does not contain shortened URLs or affiliate links.

If your pull request closes a GitHub issue, replace the XXXXX below with the issue number.

Closes #XXXXX

### CODE REVIEW

**Comment by moinshaikh** [comment]
Added three JS books and a blog post link for JS study plan.

**Comment by b3u** [comment]
LGTM

**Comment by moinshaikh** [comment]
@b3u Hi! Apologies for any inconvenience for asking this but I created three PRs and they all seem to go failed due to some Travis CI build error. Do I have to redo everything to re-create the PR?

**Comment by b3u** [comment]
I don't think so. We are encountering errors. Sorry for the wait.

**Comment by moinshaikh** [comment]
No worries, thanks for the updates :) will create new PRs for all the failed ones. :+1:

**Comment by RandellDawson** [comment]
Closed and Reopened this PR to attempt to resolve a specific Travis build failure.

**Pull request closed without merging**
