### PR TITLE
fix(curriculum): typos in Beta Registration Form

### PR DESCRIPTION
**Pull request by Kernix13**
Checklist:

- [x] I have read [freeCodeCamp's contribution guidelines](https://contribute.freecodecamp.org).
- [x] My pull request has a descriptive title (not a vague title like `Update index.md`)
- [x] My pull request targets the `main` branch of freeCodeCamp.
- [x] I have tested these changes either locally on my machine, or GitPod.

Steps 5, 8, 9, 28, 37, & 39 Removed unnecessary comma
Step 23 Removed unnecessary word `of`
Step 32 Added the missing word `not` to the third sentence.
Step 36 Nested the final sentence inside parentheses and added it to the end of the previous sentence.

### CODE REVIEW

**Review by ejcheng — DISMISSED** [review]

**Review by ShaunSHamilton — CHANGES_REQUESTED** [review]
Thank you, for taking the time to contribute.

The only change I agree with is the removal of a word in `step-023.md`. Please remove all other changes.

Specifically, `step-032.md` should **not** add anything - it is correct, as is. Otherwise, the change for `step-036.md` appears personal preference above anything else. So, we should rather have an issue opened about this so we can decide on a dedicated style for the type of content.

**Comment by Kernix13** [comment]
Ok, so just keep the change for Step 23. I'm new to this so I asking on the forum for the git commands and steps to do this. I believe I have to use `git revert <commit_hash>` and then make the Step 23 change and push that change. I'm waiting for a reply from the person who replied to my post but I have to go. If it is okay I'll make the change when I get back. I want to make sure that I am doing it correctly.

**Comment by ShaunSHamilton** [comment]
@Kernix13 No worries. Thank you, for taking the time, and I hope this is useful to you.

To confirm: Yes, the only change you should be making is that to `step-023.md`.

Feel free to reach out on the forum, or on [Chat](https://chat.freecodecamp.org/) if you need any help.

**Comment by Kernix13** [comment]
I got another response that said to use `git revert HEAD` and maybe with `--hard` added. And for the push to use `git push --force`. My reply to the person on the forum was to definitely use `--hard` or not, and if that is all I need for the push because I normally use `git push origin branch_name`. Do you know which method is best?

**Comment by Kernix13** [comment]
I'm lost. I used `git reset --hard 1a9a48911f2a5316bd4e1180edcfb73a9fcb49de` to get the files back in their original state. Then I made the change to Step 23, added and committed it then tried to use `git push --force` but that didn't work. Then I tried all of these:
```
git push --force origin fix/rothkopainting-typos 
git push --set-upstream origin fix/registrationfo
git push --set-upstream --force origin fix/registrationform-typos
```
I keep getting the message "Everything up-to-date". I've been trying to figure this out for 2 hours. So I have no idea what I am doing or how to push the change.

**Comment by ShaunSHamilton** [comment]
@Kernix13 I have replied on the [forum post](https://forum.freecodecamp.org/t/need-help-on-how-to-remove-a-file-from-a-pr/490914/25) with the steps I would have taken.

**Review by gikf — APPROVED** [review]
LGTM :+1:

**Review by ShaunSHamilton — APPROVED** [review]
LGTM 👍

**Comment by ShaunSHamilton** [comment]
Thank you, for your contribution to the page! 👍
We are happy to accept these changes, and look forward to future contributions. 🎉

**Pull request merged**
