### PR TITLE
fix(client): remove odd snap of editor panels

### LINKED ISSUE #42924: Split screen snaps back/forward when adjusted forward/backward
**Affected page**
All pages with code editors

**To Reproduce**
Steps to reproduce the behaviour:

1. Go to 'https://www.freecodecamp.org/learn/data-visualization/json-apis-and-ajax/access-the-json-data-from-an-api.'
2. Slide the adjustable split screens
3. Split screen snaps back or forward if the split-screen was pulled forward or back respectively

Related behaviour:

1. Go to 'https://www.freecodecamp.org/learn/data-visualization/json-apis-and-ajax/access-the-json-data-from-an-api.'
2. Slide the adjustable split screens
3. Now click the Code Editor
4. Type a character
5. Split screen snaps back or forward again

**Expected behaviour**
Split-screen should not snap backwards or forwards 

**Screenshots**
(https://imgur.com/a/IURLxOX)

**System (please complete the following information):**
 - Device: [HP laptop]
 - OS: [Windows 10]
 - Browser: [Chrome]
 - Version: [Version 91.0.4472.124 (Official Build) (64-bit)]

**Additional context**
Was able to reproduce Error on MS EDGE on the Same device
Was able to reproduce Error on Chrome on an Ubuntu device

### PR DESCRIPTION
**Pull request by victor-duarte**
Checklist:

- [x] I have read [freeCodeCamp's contribution guidelines](https://contribute.freecodecamp.org).
- [x] My pull request has a descriptive title (not a vague title like `Update index.md`)
- [x] My pull request targets the `main` branch of freeCodeCamp.
- [x] I have tested these changes either locally on my machine, or GitPod.

Closes #42924

Moved layout information to be stored in the state so that on stop resize triggers a re-render of the component with the new values of each panel.

**Alternate solutions**

- Keep `react-reflex` on `4.0.1`
- Add a new `cooldown` prop on state and update it on resize stop method so it causes a re-render. Similar to the suggested approach but less invasive 🤷🏻 since it is just a string

**Notes**

The issue became visible after the `react-reflex` package got updated to version `4.0.2` in [fix(deps): update dependency react-reflex to v4.0.2](https://github.com/freeCodeCamp/freeCodeCamp/commit/e97c302c3d69325afab22491d026dd0f3c8c1762)

Internally they fixed some state management regarding how props were being handled and cause some conflicts with the implementation in place.

### CODE REVIEW

**Review by ShaunSHamilton — DISMISSED** [review]
This LGTM 👍 . Kudos, on figuring out what was causing the issue - I was stuck assuming it had to do with the TS migration.

This works, and I am happy with the logic, but what is the difference between this and the second alternative you suggested?

**Comment by victor-duarte** [comment]
> This works, and I am happy with the logic, but what is the difference between this and the second alternative you suggested?

Hey @ShaunSHamilton, technically speaking there is no difference since both are triggering the  render due to the state update when the values are coming in. The suggestion is in case the PR does not make sense and wanted to keep changes at a minimum. But if moving the layer content to the state is a good way to move forward and everything seems to be ok then the second suggestion can be ignored. :+1:

**Comment by victor-duarte** [comment]
@ShaunSHamilton , made a small code change to avoid `setState` being called twice for when `name` is defined.

**Review by ShaunSHamilton — APPROVED** [review]
Even better 👍 . Thank you, Victor.

**Review by Sembauke — APPROVED** [review]
Thank you for this pr @victor-duarte, 
I would like to say that I am learning a lot from your PR myself.

This LGTM 👍 
Thank you for your contributions!

**Comment by victor-duarte** [comment]
> I would like to say that I am learning a lot from your PR myself.

@Sembauke I would say is the other way around! 👍🏻

**Pull request merged**
