### PR TITLE
Added section "Relationship to pointers", fixed misspelled "Initializiation"

### PR DESCRIPTION
**Pull request by UberschallSamsara**
- [x] I have read [freeCodeCamp's contribution guidelines](https://github.com/freeCodeCamp/freeCodeCamp/blob/master/CONTRIBUTING.md).
- [x] My pull request has a descriptive title (not a vague title like `Update index.md`)
- [x] My pull request targets the `master` branch of freeCodeCamp.
- [x] None of my changes are plagiarized from another source without proper attribution.
- [x] My article does not contain shortened URLs or affiliate links.

If your pull request closes a GitHub issue, replace the XXXXX below with the issue number.

Closes #XXXXX

### CODE REVIEW

**Comment by UberschallSamsara** [comment]
On the details page for the alleged CI failure, the error message is:

 The article at: /home/travis/build/freeCodeCamp/freeCodeCamp/guide/spanish/blockchain/features/index.md is missing frontmatter.

But that's not the article in my pull request. Looks like something in CI is broken to me.

**Comment by edgeowner** [comment]
- [x] I have read [freeCodeCamp's contribution guidelines](https://github.com/freeCodeCamp/freeCodeCamp/blob/master/CONTRIB was UTING.md).
- [x] My pull request has a descriptive title (not a vague title like `Update index.md`)
- [x] My pull request targets the `master` branch of freeCodeCamp.
- [x] None of my changes are plagiarized from another source without proper attribution.
- [x] My article does not contain shortened URLs or affiliate links.
123131
and 

If your pull request closes a GitHub issue, replace the XXXXX below with the issue number.

Closes #XXXXX

**Comment by edgeowner** [comment]
- [x] I have read [freeCodeCamp's contribution guidelines](https://github.com/freeCodeCamp2 is my 
you 
/freeCodeCamp/blob/master/CONTRIB was UTING.md).
- [x] My pull req uest has a descriptive title (not a vague title like `Update index.md`)
- [x] My pull request targets the `master` branch of freeCodeCamp.
- [x] None of my changes are plagiarized from another source without proper attribution.
- [x] My article does not contain shortened URLs or affiliate links.
123131
and 

If your pull request closes a GitHub issue, replace the XXXXX below with the issue number.

Closes #XXXXX

**Comment by edgeowner** [comment]
- [x] I have read [freeCodeCamp's contribution guidelines](https://github.com/freeCodeCamp2 is my 
you 
/freeCodeCamp/blob/master/CONTRIB was UTING.md).
- [x] My pull req uest has a descriptive title (not a vague title like `Update index.md`)
- [x] My pull request targets the `master` branch of freeCodeCamp.
- [x] None of my changes are plagiarized from another source without proper attribution.
- [x] My article does not contain shortened URLs or affiliate links.
123131
and 

If your pull request closes a GitHub issue, replace the XXXXX below with the issue number.

Closes #XXXXX
[](url)[](url)

**Comment by edgeowner** [comment]
- [x] I have read this 
[freeCo deCamp's contribution guidelines](https://github.com/freeCodeCamp2
 is my 
you 
/freeCodeCamp/blob/master/CONTRIB was UTING.md).
- [x] My pull req uest has a descriptive title (not a vague title like `Update index.md`)
- [x] My pull request targets the `master` branch of freeCodeCamp.
- [x] None of my changes are plagiarized from another source without proper attribution.
- [x] My article does not contain shortened URLs or affiliate links.
123131
and 

If your pull request closes a GitHub issue, replace the XXXXX below with the issue number.

Closes #XXXXX
[](url)[](url)

**Comment by RandellDawson** [comment]
Thank you for your contribution to the page! 👍
We're happy to accept these changes, and look forward to future contributions. 🎉

**Pull request merged**
