### PR TITLE
Fix(learn): corrected the typo in a QA with Chai lesson

### PR DESCRIPTION
**Pull request by hernandoagf**
Checklist:

- [x] I have read [freeCodeCamp's contribution guidelines](https://contribute.freecodecamp.org).
- [x] My pull request has a descriptive title (not a vague title like `Update index.md`)
- [x] My pull request targets the `master` branch of freeCodeCamp.
- [x] All the files I changed are in the same world language, for example: only English changes, or only Chinese changes, etc.

Closes #XXXXX

Updated run-functional-tests-using-a-headless-browser.md to correct the typo

### CODE REVIEW

**Comment by ShaunSHamilton** [comment]
Thanks, for this fix, @hernandoagf .

I am just confused why GitHub is showing this change:
image

**Comment by nhcarrigan** [comment]
For what it's worth, viewing the file shows that change isn't actually a change. 🤔

**Comment by hernandoagf** [comment]
Hmmm, it's weird that GitHub is highlighting that, though. Would you like me to create another fork and try again?

**Review by ShaunSHamilton — DISMISSED** [review]
This LGTM 👍 

That should not be necessary, @hernandoagf . I will report it to GitHub, and suspect it is a UI bug.

**Review by naomi-lgbt — APPROVED** [review]
Looks good to me.

**Review by RandellDawson — APPROVED** [review]

**Comment by RandellDawson** [comment]
Thank you for your contribution to the page! 👍
We're happy to accept these changes, and look forward to future contributions. 🎉

**Pull request merged**
