### PR TITLE
Updates find the length of a string challenge instructions per issue #45486

### LINKED ISSUE #45486: Suboptimal wording for JS: Find the Length of a String
One of my students got stuck on this exercise, but it turned out to be a spoken language issue, not one of programming.

> Use the `.length` property to count the number of characters in the `lastName` variable and assign it to `lastNameLength`.

They understood the task as being to find the length of `lastName`, but then to still assign `lastName` itself to `lastNameLength`. So exactly the pedantry we want to teach, uncovering undefined behaviour. :)

I suggest changing the text to be more explicit:
> Use the `.length` property to count the number of characters in the `lastName` variable, then assign that length to `lastNameLength`.

## Affected page
https://www.freecodecamp.org/learn/javascript-algorithms-and-data-structures/basic-javascript/find-the-length-of-a-string

### PR DESCRIPTION
**Pull request by archibongn1**
Checklist:

- [x] I have read [freeCodeCamp's contribution guidelines](https://contribute.freecodecamp.org).
- [x] My pull request has a descriptive title (not a vague title like `Update index.md`)
- [x] My pull request targets the `main` branch of freeCodeCamp.
- [x] I have tested these changes either locally on my machine, or GitPod.

Closes #45486

### CODE REVIEW

**Comment by jdwilkin4** [comment]
HI @archibongn1 ! 

I read through the issue that you mentioned and it doesn't look like the freeCodeCamp moderators decided on what change or if they were going to change it. 

Issues that are labeled with `good first issue` or `first timers only` are ready for people to submit PRs.
I would suggest commenting on that original issue and checking on the status of what changes will be made.

Hope that helps! 👍

**Comment by moT01** [comment]
I think this is an improvement and we can open it up for review.

**Review by moT01 — APPROVED** [review]
LGTM @archibongn1 🎉

**Review by naomi-lgbt — APPROVED** [review]
I'm good with this. This was the clearest verbiage we landed on, IMHO.

**Comment by nhcarrigan** [comment]
Congrats on your first pull request (PR)! 🎉

Thank you for your contribution to the page! 👍
We are happy to accept these changes and look forward to future contributions. 📝

**Pull request merged**
