### PR TITLE
Fix missing date parameter

### PR DESCRIPTION
**Pull request by OsakaStarbux**
Checklist:

- [x ] I have read [freeCodeCamp's contribution guidelines](https://contribute.freecodecamp.org).
- [x ] My pull request has a descriptive title (not a vague title like `Update index.md`)
- [x ] My pull request targets the `master` branch of freeCodeCamp.
- [x ] All the files I changed are in the same world language, for example: only English changes, or only Chinese changes, etc.

The missing date parameter is not part of the test or the learning objective. It tends to cause a 400 error while setting up the exercises for the log test.

### CODE REVIEW

**Comment by Sky020** [comment]
@OsakaStarbux , thank you, for helping contribute to the freeCodeCamp community. It is taking a while to get through QAing PRs. So, thank you, for the ping.

I might be forgetting something, but I am not sure there is any reason to add a date parameter to the request, as the project description does specify:
>I can add an exercise to any user by posting form data userId(_id), description, duration, and optionally date to /api/exercise/add

So, the camper's `/add` logic should account for creating the date object if one is not provided. So, I believe this test was purposefully written to take advantage of this.

**Comment by OsakaStarbux** [comment]
You're right. Although, because the test is not actually using the form,
that parameter is not just empty, it's missing. It means that I can pass
the test for the /add route and then silently fail the /add route during
the log test. Also, it would be better if that were a separate test so that
campers know what they are failing.

**Comment by scissorsneedfoodtoo** [comment]
Hi @OsakaStarbux, thanks for your contribution.

Like @Sky020 mentioned, I'm not sure if adding a date parameter there is necessary. I tried the example project at https://exercise-tracker--freecodecamp.repl.co/ both with the form on the page and with Postman, and leaving the date out works as expected in both cases.

The actual `assert` statement for that test is quite forgiving as well, and really just checks that an array with a length of 1 is returned.

Could you give us some examples of when the API could silently fail in the /add route you modified?

**Comment by OsakaStarbux** [comment]
@scissorsneedfoodtoo Thanks for trying it out. I don't know if you passed an empty string or no parameter at all but I'm glad it works as you expect.

**Comment by scissorsneedfoodtoo** [comment]
@OsakaStarbux, I tried it with both an empty string and no parameter and got the current date in the response. That's not to say that all projects work that way, though, just the example.

I do agree that the test text for this and the other backend projects could use some clarification, though. And I do like the idea about splitting some of the tests up to test for specific functionality like you mentioned. Dates and times are notoriously tricky to test for, but it would be good to have more granular tests.

**Pull request closed without merging**
