### PR TITLE
fix(curriculum): allow optional spacing for assignment operator

### LINKED ISSUE #53704: update tests to allow for optional spacing around assignment operator in date formatter project
### Describe the Issue

It looks like a few tests in this project require spacing around the assignment operator.

### Affected Page

multiple

### Your code

see explanation above

### Expected behavior

see explanation above

### Screenshots

_No response_

### System

- Device: [e.g. iPhone 6, Laptop]
- OS: [e.g. iOS 14, Windows 10, Ubuntu 20.04]
- Browser: [e.g. Chrome, Safari]
- Version: [e.g. 22]

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by jdwilkin4**
## Summary
This PR goes through and updates the tests to allow for optional spacing around the assignment operator. 

Checklist:

- [x] I have read and followed the [contribution guidelines](https://contribute.freecodecamp.org).
- [x] I have read and followed the [how to open a pull request guide](https://contribute.freecodecamp.org/#/how-to-open-a-pull-request).
- [x] My pull request targets the `main` branch of freeCodeCamp.
- [x] I have tested these changes either locally on my machine, or GitPod.

Closes #53704

### CODE REVIEW

**Comment by gikf** [comment]
There's few similar cases in other projects, would you want to include them in this PR?

**Comment by jdwilkin4** [comment]
@gikf 

I did a quick global search and found one python project step with the same issue.
Are you referring to that?

Or were there other JS projects?

**Comment by jdwilkin4** [comment]
When checking for `\s+=` globally I found a few more for the platform and todo app.
So since that is small we can add it to this PR

**Comment by gikf** [comment]
Hanoi:
https://github.com/freeCodeCamp/freeCodeCamp/blob/main/curriculum/challenges/english/07-scientific-computing-with-python/learn-recursion-by-solving-the-tower-of-hanoi-puzzle/64ddd65848a12919d7e1c7d0.md

Luhn (` += +`):
https://github.com/freeCodeCamp/freeCodeCamp/blob/main/curriculum/challenges/english/07-scientific-computing-with-python/learn-how-to-work-with-numbers-and-strings-by-implementing-the-luhn-algorithm/65687da2e60409c45595bbe1.md

Password generator (` <=`):
https://github.com/freeCodeCamp/freeCodeCamp/blob/main/curriculum/challenges/english/07-scientific-computing-with-python/learn-regular-expressions-by-building-a-password-generator/6565bd4265158360de8e2ae7.md
https://github.com/freeCodeCamp/freeCodeCamp/blob/main/curriculum/challenges/english/07-scientific-computing-with-python/learn-regular-expressions-by-building-a-password-generator/6565c084627071646f94c4b0.md

Music player (`\s=`):
https://github.com/freeCodeCamp/freeCodeCamp/blob/main/curriculum/challenges/english/15-javascript-algorithms-and-data-structures-22/learn-basic-string-and-array-methods-by-building-a-music-player/653635c731206b718659d3d5.md

Todo app (`\s=`):
https://github.com/freeCodeCamp/freeCodeCamp/blob/main/curriculum/challenges/english/15-javascript-algorithms-and-data-structures-22/learn-localstorage-by-building-a-todo-app/64fad07f43a101779cb8692a.md

**Review by gikf — APPROVED** [review]

**Review by moT01 — APPROVED** [review]
LGTM 🎉

**Pull request merged**
