### PR TITLE
fix(curriculum): correct spelling error

### LINKED ISSUE #44726: Text says RBG instead of RGB
## Affected page
https://www.freecodecamp.org/learn/2022/responsive-web-design/learn-css-colors-by-building-a-set-of-colored-markers/step-37

image

### PR DESCRIPTION
**Pull request by ReubenMenezes**
Changed the incorrect spelling (rbg) to the correct spelling (rgb)

Checklist:

- [x ] I have read [freeCodeCamp's contribution guidelines](https://contribute.freecodecamp.org).
- [x ] My pull request has a descriptive title (not a vague title like `Update index.md`)
- [x ] My pull request targets the `main` branch of freeCodeCamp.
- [x ] I have tested these changes either locally on my machine, or GitPod.

Closes #44726

### CODE REVIEW

**Review by naomi-lgbt — APPROVED** [review]
Looks good to me!

**Review by gikf — APPROVED** [review]
LGTM :+1:

**Comment by gikf** [comment]
Hi @ReubenMenezes. Congrats on your first pull request (PR)! 🎉

Thank you for your contribution to the page! 👍
We are happy to accept these changes and look forward to future contributions. 📝

**Comment by ReubenMenezes** [comment]
Thanks a lot! Enjoy your day!

**Pull request merged**
