### PR TITLE
repair broken regexp in "Confirm the ending"

### LINKED ISSUE #14077: endsWith() is letting you go through, though it shouldn't
#### Challenge Name
Confirm the Ending

#### Issue Description
One of the clauses forbids you from using the endsWith method:
"Do not use the built-in method .endsWith() to solve the challenge."

However, this code let's you pass to the next stage:

function confirmEnding(str, target) {
  // "Never give up and good luck will find you."
  // -- Falcor
  if (str.endsWith(target)){
  return true;
  } else {
    return false;
  }
}

confirmEnding("Bastian", "n");

#### Browser Information

* Browser Name, Version: 
* Operating System: 
* Mobile, Desktop, or Tablet: 

#### Your Code

```js



```

### PR DESCRIPTION
**Pull request by JoolsMcFly**
#### Pre-Submission Checklist

- [ ] Your pull request targets the `staging` branch of freeCodeCamp.
- [x] Branch starts with either `fix/`, `feature/`, or `translate/` (e.g. `fix/signin-issue`)
- [x] You have only one commit (if not, [squash](http://forum.freecodecamp.com/t/how-to-squash-multiple-commits-into-one-with-git/13231) them into one commit).
- [x] All new and existing tests pass the command `npm test`. Use `git commit --amend` to amend any fixes.

#### Type of Change

- [x] Small bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds new functionality)
- [ ] Breaking change (fix or feature that would change existing functionality)
- [ ] Add new translation (feature adding new translations)

#### Checklist:

- [x] Tested changes locally.
- [x] Closes currently open issue: Closes #14077

#### Description

The regexp in `Confirm the ending` challenge that checks if user is using `endsWith()` function is not correct.
It does not account for spaces and expects a `;` at the end.
`/\.endsWith\(.*?\)\s*?;/`

So `if (str.endsWith('dude'))` is considered a valid solution.

My commit adds a regexp that checks spaces/carriage return and prevents above issue.
See it in action.
image

Thanks!

### CODE REVIEW

**Comment by raisedadead** [comment]
@JoolsMcFly can you clarify why this is opened against `backup/master` instead of staging? Was this discussed?

/cc @BerkeleyTrue

**Comment by JoolsMcFly** [comment]
Hi,

I opened it against `backup/master` because I thought the issue was legit and I could not repro it on `staging`, although the regexp is very similar there: `/\.endsWith\(.*?\)\s*?;?/`

Should I have discussed it on gitter channel for contributors beforehand? Sorry!

**Comment by raisedadead** [comment]
@JoolsMcFly hey, its alright... I was just seeking, if this is required at all. Thanks for confirming. I believe if this is fixed on `staging` then we needn't do it on the `backup/staging`.

The beta site will be release at some point. Unless this is blocking issue for the current main website, we might just close the original issue.

Can you confirm that the regex is good for whatever we have on `staging`?

/cc @freeCodeCamp/moderators

**Comment by JoolsMcFly** [comment]
It's not a blocking issue as per say but users​ can use `endsWith`, which is against the rules. 

Feel free to close this PR if you think it's not a real issue.
I'll make PRs against `staging` next time.

Bye.

**Comment by raisedadead** [comment]
@JoolsMcFly thanks a lot, and we value your contribution, only thing is we are keeping current production for critical issues only.

I'll mark the issue as resolved in staging.

Thanks a lot once again for your work on this, keep those PRs coming. Happy fixing! 😄

**Pull request closed without merging**
