### PR TITLE
fix: make recursion challenge more intuitive

### PR DESCRIPTION
**Pull request by ojeytonwilliams**
- [x] I have read [freeCodeCamp's contribution guidelines](https://github.com/freeCodeCamp/freeCodeCamp/blob/master/CONTRIBUTING.md).
- [x] My pull request has a descriptive title (not a vague title like `Update index.md`)
- [x] My pull request targets the `master` branch of freeCodeCamp.
- [x] None of my changes are plagiarized from another source without proper attribution.
- [x] All the files I changed are in the same world language (for example: only English changes, or only Chinese changes, etc.)
- [x] My changes do not use shortened URLs or affiliate links.

@RandellDawson noticed that the way I wrote 'Replace Loops using Recursion' was needlessly complicated.  He suggested that it would be easier to reason about if the functions simply multiplied/summed the first `n` elements, rather than 0 to `n` inclusive.

This PR is adjusts the wording and tests accordingly.

### CODE REVIEW

**Review by Qondor — APPROVED** [review]
Looks better and more intuitive.

**Comment by moT01** [comment]
In my opinion, this still feels a little complex - if this were my first introduction to recursion, I feel like I would be confused.

**Comment by ojeytonwilliams** [comment]
> In my opinion, this still feels a little complex - if this were my first introduction to recursion, I feel like I would be confused.

I found it a bit tricky to introduce recursion while keeping the challenge to a reasonable length.  Any ideas about how it could be introduced more gently?

> There's an open issue with this challenge @ojeytonwilliams - I made a PR for it #37419 - if you want to tack those changes onto this, I can close my PR and then this one will close the issue.

Let's just merge your PR first, since you're actually fixing a bug.

**Comment by RandellDawson** [comment]
Where are we on this PR?

**Comment by ojeytonwilliams** [comment]
We stalled a bit.  @moT01 pointed out that it's still a bit hard to understand, and I agree, but I'm not sure how to improve it.

If you and Tom think it's an improvement (albeit only a slight one) we could use it, otherwise it can be shelved.

**Comment by raisedadead** [comment]
Bump @RandellDawson

**Comment by raisedadead** [comment]
Bump @moT01

**Review by RandellDawson — APPROVED** [review]
I say it is an improvement.

**Pull request merged**
