### PR TITLE
test(e2e,playwright): Donate Page

### PR DESCRIPTION
**Pull request by Tauseef-Hilal**
Checklist:

- [x] I have read and followed the [contribution guidelines](https://contribute.freecodecamp.org).
- [x] I have read and followed the [how to open a pull request guide](https://contribute.freecodecamp.org/#/how-to-open-a-pull-request).
- [x] My pull request targets the `main` branch of freeCodeCamp.
- [x] I have tested these changes either locally on my machine, or GitPod.

Refers: #51705

### CODE REVIEW

**Comment by Tauseef-Hilal** [comment]
@camperbot cant code

**Comment by Tauseef-Hilal** [comment]
Failed tests pass on my machine 😕

**Comment by Tauseef-Hilal** [comment]
Ouch! I didn't push all the files

**Comment by Tauseef-Hilal** [comment]
Please review this

**Review by huyenltnguyen — COMMENTED** [review]
Hey @Tauseef-Hilal, thank you for the PR!

We have already approved a PR that adds tests for this page (#51768), but yours has a test case for the display of the `CampersImage`, which is a great addition. 

I'd suggest waiting until #51768 is merged and update your branch with the `main` branch. We will then treat this PR as an improvement to the test suite, instead of an initialization of the test suite. How does that sound? 🙂

**Comment by Tauseef-Hilal** [comment]
That sounds like a reasonable plan (even though I wrote the tests first 😅)! I'll wait for #51768 to be merged.

Should I also update the PR title?

**Comment by Tauseef-Hilal** [comment]
@huyenltnguyen 

That sounds like a reasonable plan (even though I wrote the tests first 😅)! I'll wait for #51768 to be merged.

Should I also update the PR title?

**Comment by Tauseef-Hilal** [comment]
Oh! I didn't notice that. I'll wait.

**Comment by Tauseef-Hilal** [comment]
You can close this PR. I will create a new one after I make changes.

**Comment by naomi-lgbt** [comment]
Closing in favour of #51783

**Pull request closed without merging**
