### PR TITLE
changed expects to assert style tests

### LINKED ISSUE #3316: Refactor Advanced Bonfires to use Assert instead of Expect
Please see basic-bonfires.json where I have refactored all the old expect-style tests into assert-style tests. Please do your best to make the test style match no-nonsense style I used here.

### PR DESCRIPTION
**Pull request by natac13**
closes #3316

### CODE REVIEW

**Comment by ahstro** [comment]
There was no need to close your old pull request. Next time, use `git commit --amend` and `git push --force`.
The only change is `deepEqual` to `strictEqual` right?

**Comment by natac13** [comment]
that is the difference from the PR I closed I deleted yep

**Comment by ahstro** [comment]
Sorry about the late answer. I'm thinking we should sort of standardize the return string? So instead of `You should return`, `A X should be returned` and `Should return`, pick one. I'm not sure if there's one that's been more frequently used across the curriculum though.

**Comment by natac13** [comment]
Sounds good @ahstro I looked at #3347 which seems to be closer to the ` fn should return y` string and looking at some of the other test from basic bonfires it seems they do the same. So I can change to them all to follow that pattern.

**Comment by natac13** [comment]
@ahstro can I rename branch without messing the PR up? Just because I this one does not follow the correct format of `fix/...`

**Comment by natac13** [comment]
I looked into changing the name and it seems I would need to delete and redo PR let me know if you would like me to do this

**Comment by ahstro** [comment]
Like you said, you'd have to create a new PR to change the branch name. I don't think this is necessary as long as you try to follow the naming scheme in the future; there's bound to be some time of overlap between a style decision and it's full implementation.

The PR looks good now, so I'll go ahead and merge it.

**Pull request merged**
