### PR TITLE
fix: add strict check for css styling

### LINKED ISSUE #51330: Tests for Cat Painting Step 8 Too Strict
### Describe the Issue

You can only pass this step if you put everything on one line and have a space after the comma.

P.S. You cannot have a space before the first color either, or after the last percentage.

### Affected Page

https://www.freecodecamp.org/learn/2022/responsive-web-design/learn-intermediate-css-by-building-a-cat-painting/step-8

### Your code

For example, this will not pass:

```
background: linear-gradient(
  #5e5e5e 85%,
  #45454f 100%
);
```

### Expected behavior

Any valid CSS should be able to pass.

### Screenshots

_No response_

### System

N/A

### Additional context

This has come up several times in the forum in the past few ~~days~~hours.

### PR DESCRIPTION
**Pull request by rockypukar**
Checklist:

- [ x] I have read and followed the [contribution guidelines](https://contribute.freecodecamp.org).
- [x ] I have read and followed the [how to open a pull request guide](https://contribute.freecodecamp.org/#/how-to-open-a-pull-request).
- [x ] My pull request targets the `main` branch of freeCodeCamp.
- [x ] I have tested these changes either locally on my machine, or GitPod.

Closes #51330

### CODE REVIEW

**Comment by RockyPukar1** [comment]
In my local test the curriculum works perfectly fine with Firefox but int CI test if fails. I could not figure out why?

**Review by naomi-lgbt — CHANGES_REQUESTED** [review]
The linked issue has been triaged and opened for contribution. Please update this PR to apply the agreed-upon fix.

**Comment by RockyPukar1** [comment]
Now I have made only requested change in the issue. Please

**Comment by bbsmooth** [comment]
@RockyPukar1 The agreed upon fix is to use the computed styles via the `CSSHelp` helper function. @lasjorg outlined how it would work in the issue. You need to convert these two tests to use that method.

**Comment by raisedadead** [comment]
Thanks for taking the time to contribute. We have decided to go with another PR that satisfies the needs of the issue. 

We are grateful for your help and look forward to future contributions. 

Happy coding!

**Pull request closed without merging**
