### PR TITLE
fix(challenges): Change of text in Introduction to the basic node a

### LINKED ISSUE #15796: Text doesn't change when going to next/previous step
#### Challenge Name

https://beta.freecodecamp.com/en/challenges/basic-node-and-express/introduction-to-the-basic-node-and-express-challenges

#### Issue Description

1. When going to step 2/2, the last 3 paragraphs of step 1/2 are still displayed
2. If I click "Go to my previous step", the same 3 paragraphs are displayed twice, with different font

#### Browser Information

* Browser Name, Version: Chrome 60.0.3112.90
* Operating System: Windows NT 10.0; Win64; x64
* Mobile, Desktop, or Tablet: Desktop

### PR DESCRIPTION
**Pull request by vivek28111992**
Text was not getting changed going from step 1 to step 2 because ul
cannot be child node of p tag so I changed p tag to div in Introduction
to the basic node and express challenges. For ref.
https://stackoverflow.com/questions/10601345/ul-element-can-never-be-a-child-of-p-element

edit(berkeleytrue): this is not a breaking change

Closes #15796

#### Pre-Submission Checklist

- [x] Your pull request targets the `staging` branch of freeCodeCamp.
- [x] Branch starts with either `fix/`, `feature/`, or `translate/` (e.g. `fix/signin-issue`)
- [x] You have only one commit (if not, [squash](http://forum.freecodecamp.com/t/how-to-squash-multiple-commits-into-one-with-git/13231) them into one commit).
- [x] All new and existing tests pass the command `npm test`. Use `git commit --amend` to amend any fixes.

#### Type of Change

- [x] Small bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds new functionality)
- [ ] Breaking change (fix or feature that would change existing functionality)
- [ ] Add new translation (feature adding new translations)

#### Checklist:

- [x] Tested changes locally.
- [x] Closes currently open issue (replace XXXX with an issue no): Closes #XXXX

### CODE REVIEW

**Comment by vivek28111992** [comment]
Solved text change issue in Introduction to the basic node and express challenges

**Comment by systimotic** [comment]
@Bouncey Could you look at this and how it is related to #14181?

**Comment by Bouncey** [comment]
@systimotic I will take a look at this when I get a chance. I haven't played in this code base for a long time, so I will need time to poke around to see what has changed.

**Comment by BerkeleyTrue** [comment]
@vivek28111992 thanks for finding that reference. I was not aware of that. Always glad to learn something new.

Happy Coding!!

**Pull request merged**
