### PR TITLE
fix(curriculum): removed typo

### PR DESCRIPTION
**Pull request by farshed**
Checklist:

- [x] I have read and followed the [contribution guidelines](https://contribute.freecodecamp.org).
- [x] I have read and followed the [how to open a pull request guide](https://contribute.freecodecamp.org/#/how-to-open-a-pull-request).
- [x] My pull request targets the `main` branch of freeCodeCamp.
- [x] I have tested these changes either locally on my machine, or GitPod.

### CODE REVIEW

**Review by gikf — APPROVED** [review]

**Review by huyenltnguyen — APPROVED** [review]

**Review by Sembauke — APPROVED** [review]

**Review by gikf — CHANGES_REQUESTED** [review]
:eyes: Thanks @camperbot 

@farshed Please make the change to the English file. Other languages, if needed will be updated using the translation workflow.

**Comment by farshed** [comment]
@gikf I'm sorry I don't get it. The change is only in a single English file.

**Comment by gikf** [comment]
Change is made in the German version of the curriculum, albeit not yet translated. This is the path:

curriculum/challenges/**german**/07-scientific-computing-with-python/learn-algorithm-design-by-building-a-shortest-path-algorithm/6578b13757611e2825beb8a5.md

Edited should be file from English curriculum:
curriculum/challenges/**english**/07-scientific-computing-with-python/learn-algorithm-design-by-building-a-shortest-path-algorithm/6578b13757611e2825beb8a5.md

**Comment by farshed** [comment]
@gikf thanks. It's done.

**Review by gikf — APPROVED** [review]

**Pull request merged**
