### PR TITLE
fix(challenges): Add top-margin & change comment color of challenges-log

### PR DESCRIPTION
**Pull request by vkWeb**
### Pre-Submission Checklist
- [x] Your pull request targets the `staging` branch of freeCodeCamp.
- [x] Branch starts with either `fix/`, `feature/`, or `translate/` (e.g. `fix/signin-issue`)
- [x] You have only one commit (if not, [squash](http://forum.freecodecamp.org/t/how-to-squash-multiple-commits-into-one-with-git/13231) them into one commit).
- [x] All new and existing tests pass the command `npm test`. Use `git commit --amend` to amend any fixes.

### Type of Change
- [x] Small bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds new functionality)
- [ ] Breaking change (fix or feature that would change existing functionality)
- [ ] Add new translation (feature adding new translations)

### Checklist:

- [x] Tested changes locally.
- [ ] Addressed currently open issue (replace XXXXX with an issue no in next line)

### Description
I've added 24px top-margin to the challenges-log and I've changed the comment color only of challenges-log from `#a50500` (default) to `#006400` (brand-primary). The change doesn't affect the night mode.

**Before:**
before

**After:**
after

### CODE REVIEW

**Review by raisedadead — CHANGES_REQUESTED** [review]
Thanks for the PR, but the syntax highlight is to be handled via the theme, and this is already the case. The margin looks good though.

**Comment by vkWeb** [comment]
@raisedadead Yes - the syntax highlighting in the editor will not be disturbed by this change. Only the comment color of the challenges-log will be affected.

**Comment by raisedadead** [comment]
Hi, thanks for the clarification, we are of the opinion that the comment color should be left what the theme is. Maybe we can add support for more themes in future.

This should be as generic as possible. 

Could you please update the PR to have only the margin change?

Thanks.

**Comment by vkWeb** [comment]
@raisedadead Okay if that's the case. I'll update my PR.

**Comment by vkWeb** [comment]
@raisedadead PR updated as per your request. 

By the way, I have a question, like when I make the requested changes should I `--amend` the commit or commit with the different message and then squash it into a single commit. Which one you think is better? I'll follow that in my future PRs.

**Review by raisedadead — APPROVED** [review]

**Comment by raisedadead** [comment]
Usually we are squashing commits, but its preferred to `--amend` also, you could use `--amend --no-edit` to avoid editing message.

Thanks

**Comment by vkWeb** [comment]
@raisedadead Okay. I'll keep that in mind. Thanks for the merge . 😃.

**Pull request merged**
