### PR TITLE
fix: Removed reply template from flight manuals children

### LINKED ISSUE #40063: docs: Multiple H1 elements on a page show children from each other
image

⬆️ _Moderator Handbook_ children end up as _Reply Template_ children. Not a big deal; nothing breaks.

_Originally posted by @Sky020 in https://github.com/freeCodeCamp/freeCodeCamp/issues/39785#issuecomment-714520138_

### PR DESCRIPTION
**Pull request by dhanush1909**
Checklist:

- [x] I have read [freeCodeCamp's contribution guidelines](https://contribute.freecodecamp.org).
- [x] My pull request has a descriptive title (not a vague title like `Update index.md`)
- [x] My pull request targets the `master` branch of freeCodeCamp.
- [x] All the files I changed are in the same world language, for example: only English changes, or only Chinese changes, etc.

Closes #40063 

Reply templates should not be a subfolder of flight manuals because it's a subfolder of Moderator Handbook.

### CODE REVIEW

**Comment by nhcarrigan** [comment]
Heya~!

Thanks for the catch! I do see there is a duplicate link issue. I'm not sure, though, if leaving the Reply Templates in the bottom of the Moderator Handbook is the best approach - it might be better to separate the templates into their own `.md` file and keep this link?

**Comment by dhanush1909** [comment]
Hey @nhcarrigan, reply templates were part of a different .md file but was moved to ModeratorHandbook.md to get rid of relative linking. @raisedadead can you check this once?
thank you.

**Comment by raisedadead** [comment]
Hi @nhcarrigan 

I think I agree with you on this, while consolidating I might have had the oversight of merging this with the handbook.

However, at minute there is a consistency issue with the replies in the templates and the handbook instructions. I think you are the best person to rejig this a little bit. Ideally, we want fewer files.

I will let you advise us here. Thanks.

@dhanush1909 thanks for your patience and the PR, we will follow up with further instructions.

**Comment by nhcarrigan** [comment]
Alright - if the goal is fewer files, then I don't see an issue with having reply templates at the bottom of the moderator handbook (they are very closely related, after all). 

I will go ahead and run through the handbook and make sure the templates match up with the instructions - PR will come soon.

**Review by naomi-lgbt — APPROVED** [review]
I'm still not sure if we need to update the translated versions through GitHub, or if Crowdin will update them for us when we modify the base English file. 

But this looks good to me. 🥳

**Review by moT01 — APPROVED** [review]
LGTM @dhanush1909 🎉 Thank you for your contribution to the page! 👍
We are happy to accept these changes and look forward to future contributions. 🎉

I noticed that Mrugesh merged your other PR @nhcarrigan, so I think we are safe to merge this. I took a look, and those changes don't appear to be on the crowdin files to be translated yet, so I'm not quite sure how it works. I did notice [a file with some github actions](https://github.com/freeCodeCamp/freeCodeCamp/blob/c5e4beaac99dd94fdf2281c3613e2e93703f36c5/.github/workflows/crowdin-i18n.yml) that seem to interact with crowdin - perhaps it's still being worked on.

**Pull request merged**
