### PR TITLE
Added content to stub

### PR DESCRIPTION
**Pull request by BTmathic**
Gave definition, examples, two methods to compute as well as a JavaScript algorithm, and some generalizations.

- [x] I have read [freeCodeCamp's contribution guidelines](https://github.com/freeCodeCamp/freeCodeCamp/blob/master/CONTRIBUTING.md).
- [x] My pull request has a descriptive title (not a vague title like `Update index.md`)
- [x] My pull request targets the `master` branch of freeCodeCamp.
- [x] None of my changes are plagiarized from another source without proper attribution.
- [ ] My article does not contain shortened URLs or affiliate links.

If your pull request closes a GitHub issue, replace the XXXXX below with the issue number.

Closes #XXXXX

### CODE REVIEW

**Comment by farisoft** [comment]
I am OK with these changes, but kindly reduce the links to external websites and I advise to provide internal links instead as the external websites contents may change frequently and that would impact our Freecodecamp's viewers' abilities to learn from one single site.

So could you change the external links to point to internal Freecodecamp's site, perhaps?

@BTmathic

**Comment by BTmathic** [comment]
I don't think Wikipedia links will impact someone's ability to learn in a negative way, but I have removed all the external links and added internal links where possible.

(I'm pretty sure I checked all the boxes, but in case it needs clarification Wikipedia is not an affiliate of mine.)

**Comment by ezioda004** [comment]
@BTmathic @farisoft FYI linking to Wikipedia articles is fine and there is no hard requirement about using internal fcc links. If the article in fcc exists then sure you can link that but you can also link Wikipedia or any other reliable source too.

**Comment by farisoft** [comment]
Ah okay, got it @ezioda004.

I was afraid that if the Wiki links are messed then the Reader would have a hard time reading thru the guides misleading the readers. 

But anyways, thanks.

Merging this PR anyways.

**Pull request merged**
