### PR TITLE
Changed the faulty/confusing test message

### LINKED ISSUE #7069: Change the font Size - Lesson has a bug
In the mean while when I was working with this problem, it occurs that the second p tag ( which do not containing any class attribute) shows an error of having a class attribute. please fix this issue.
freecodecampbug

### PR DESCRIPTION
**Pull request by justincorrigible**
The current error message is not descriptive as to why it fails when people remove the class from the first paragraph.

Closes #7069

### CODE REVIEW

**Comment by BerkeleyFalse** [comment]
@hallaathrad thanks for the PR.
Do not include issue numbers and following [keywords](https://help.github.com/articles/closing-issues-via-commit-messages/#keywords-for-closing-issues) in commit messages.
Please, review our [**Guidelines for Contributing**](https://github.com/FreeCodeCamp/FreeCodeCamp/blob/staging/CONTRIBUTING.md), thank you!.

**Comment by hallaathrad** [comment]
@bugron your brainchild is giving me sass! help!

**Comment by BerkeleyFalse** [comment]
@hallaathrad updated the pull request.

**Comment by BerkeleyFalse** [comment]
@hallaathrad updated the pull request.

**Pull request merged**
