### PR TITLE
fix: data analysis links

### PR DESCRIPTION
**Pull request by beaucarnes**
Checklist:

- [x] I have read [freeCodeCamp's contribution guidelines](https://contribute.freecodecamp.org).
- [x] My pull request has a descriptive title (not a vague title like `Update index.md`)
- [x] My pull request targets the `master` branch of freeCodeCamp.
- [x] All the files I changed are in the same world language, for example: only English changes, or only Chinese changes, etc.

Closes #XXXXX

### CODE REVIEW

**Comment by RandellDawson** [comment]
@beaucarnes These changes look fine.  However, you will need to update the `README.md`'s on GitHub, because they still reference using Microsoft Azure Notebooks as the recommendation for setting them up.

**Comment by raisedadead** [comment]
> will need to update the `README.md`'s on GitHub, because they still reference using Microsoft Azure Notebooks as the recommendation for setting them up.

Can we get a list? Maybe we can get help from the contributors?

**Comment by nhcarrigan** [comment]
> > will need to update the `README.md`'s on GitHub, because they still reference using Microsoft Azure Notebooks as the recommendation for setting them up.
> 
> Can we get a list? Maybe we can get help from the contributors? Anyways, I still think we should land and push this PR to production. This being a hotfix essentially?

I'm not sure which readme files, but I'd be happy to help! 🙂

**Comment by RandellDawson** [comment]
@nhcarrigan @raisedadead  The README.md files are in each repo. For example, the first file refers to:

https://github.com/ine-rmotr-curriculum/FreeCodeCamp-Pandas-Real-Life-Example

The problem is these do not appear to be in a repo we directly control.

I spot checked to make sure each repo url actually existed and they do, so I think it is fine to merge as is, but I do not know how to deal with the changes that need to be made in the `ine-rmotr-curriculum` account.

**Comment by raisedadead** [comment]
> but I do not know how to deal with the changes that need to be made in the `ine-rmotr-curriculum` account.

because they are the course creator and the maintainer, we would need make PR against those source repos.

**Comment by nibble0101** [comment]
I have noticed all the `a` tags have `target="_blank"` attribute without `rel = "noopener"` and `rel="noreferrer"`.  Doesn't that create a security issue? Because i have noticed some of the `a` tags are linking to external pages.

**Comment by RandellDawson** [comment]
@raisedadead  After looking at this a bit more, the only repo where the README.md file need to be updated to remove the link to Azure Notebooks is:

* https://github.com/ine-rmotr-curriculum/data-cleaning-rmotr-freecodecamp

The other repos either do not have a README.md file or one that does not have the link to Azure Notebooks.

**Review by moT01 — COMMENTED** [review]
If we don't want or need to add `rel="noopener"` and `rel="noreferrer"`, it LGTM 🎉 

If we want to add them, I can make those changes if needed.

**Comment by RandellDawson** [comment]
For consistency, would it make sense to surround all the attributes of the anchor elements with double quotes?  Currently, the `href` attribute uses double quotes and the other attributes (`rel` and `target`) use single quotes.  I know it does not change the functionality, but thought while we are changing things, it might make sense to do it now.

**Review by RandellDawson — APPROVED** [review]
@beaucarnes Thanks for adding these links

@moT01 Thanks for making the additional updates.

**Pull request merged**
