### PR TITLE
Fixed grammar, among other things.

### PR DESCRIPTION
**Pull request by hegdenischay**
Since `#include <bits/stdc++.h>` is not a part of the C++ Standard, it was changed to more appropriate headers.
Also fixed the grammatical errors here.
Added a few helpful links.
- [x] I have read [freeCodeCamp's contribution guidelines](https://github.com/freeCodeCamp/freeCodeCamp/blob/master/CONTRIBUTING.md).
- [x] My pull request has a descriptive title (not a vague title like `Update index.md`)
- [x] My pull request targets the `master` branch of freeCodeCamp.
- [x] None of my changes are plagiarized from another source without proper attribution.
- [x] My article does not contain shortened URLs or affiliate links.

If your pull request closes a GitHub issue, replace the XXXXX below with the issue number.

Closes #XXXXX

### CODE REVIEW

**Comment by RandellDawson** [comment]
Closed and Reopened this PR to attempt to resolve a specific Travis build failure.

**Comment by hegdenischay** [comment]
I believe it has happened because someone else had an open PR before I did where they edited this page.

Please close this PR so that I can edit the latest page.

**Comment by hegdenischay** [comment]
Okay, then!

**Review by Manish-Giri — APPROVED** [review]
Hi @hegdenischay 

Thank you for your contribution to the page! 👍

We're happy to accept these changes and look forward to future contributions. 🎉

**Pull request merged**
