### PR TITLE
chore(i18n,docs): processed translations

### PR DESCRIPTION
**Pull request by camperbot**
This PR was opened auto-magically by Crowdin.

### CODE REVIEW

**Review by raisedadead — DISMISSED** [review]

**Review by sidemt — COMMENTED** [review]
These links in how-to-add-cypress-tests.md don't work with translated documents. I suppose they should be something like `how-to-add-cypress-tests.md#cypress-gitpod-setup` (I guess it needs file extention) I haven't tested on my end yet, though.
See also: #45187

**Comment by sidemt** [comment]
OK, I tested it. (With Japanese)

When the target is within the same page, the link have to be either:
`how-to-add-cypress-tests.md#Cypress-と-GitPod-の設定`
`#Cypress-と-GitPod-の設定`

When the target is in different page, the link have to be:
`how-to-setup-freecodecamp-locally.md#ステップ-3-MongoDBを起動し、データベースをシードする`

So I think the English source string should be:
- no `/` at start
- requires `.md` after filename

Then, on Crowdin, we can change the heading text after `#` to match the translated heading. 

I can open a PR to fix the English file tomorrow if needed.

**Comment by ieahleen** [comment]
@sidemt that would be awesome if you can do that

**Comment by raisedadead** [comment]
@sidemt this is my bad, I had oversight to not check the docs in localization subfolders. You are correct we should have a standard linking pattern that works across the English and localized versions.

**Comment by sidemt** [comment]
@raisedadead No problem. The links weren't working in the first place (they were missing `.md`) so it was good we found this issue thanks to this change. 🙂

**Pull request merged**
