### PR TITLE
feat(api): remove unused eslint errors in the codebase

### PR DESCRIPTION
**Pull request by Sboonny**
Checklist:

- [x] I have read [freeCodeCamp's contribution guidelines](https://contribute.freecodecamp.org).
- [x] My pull request has a descriptive title (not a vague title like `Update index.md`)
- [x] My pull request targets the `main` branch of freeCodeCamp.
- [x] I have tested these changes either locally on my machine, or GitPod.

While adding RTL layout, I found enlist which weren't used, so I removed them.

This doesn't change code, so I don't think it will harm anything to remove them. not like my previous `make sign out harder` pr

This isn't all of them, because the server stop working after so many eslint error removed 🤣, restarting typescript and eslint servers didn't help as well.

### CODE REVIEW

**Review by raisedadead — CHANGES_REQUESTED** [review]
Please spread the changes over multiple atomic PRs (one per package/app is OK) and reduce the blast radius.

**Comment by Sboonny** [comment]
Sure 👍, althought I don't think there is blast because I am removing comments not code. but I don't mind making 3 prs 👍

**Comment by raisedadead** [comment]
> althought I don't think there is blast ...

Mind explaining what you mean here?

**Comment by Sboonny** [comment]
Sure enlist comment are used to disable their ruling, we are originally implementing them to help us to tell the code base, "oh you think there is a "mistake" here, but this is intentional, ignore it".

What happen if there is no mistake, then the comment became useless, and it isn't ignoring a "mistake". 

its existing is confusing for newbies (I think I still one of them) that don't know eslint, and worse if the comment stay and newbie add a "mistake" that we don't want but the eslint doesn't warn us, because he was told to ignore it.

**Comment by raisedadead** [comment]
Thanks - I know what eslint does. What I am asking is very specific. Why do you thing there is no impact in removing these comments in a single PR?

**Comment by Sboonny** [comment]
> Sure 👍, althought I don't think there is blast because I am removing comments not code. but I don't mind making 3 prs

I think there is a miscommunication, I didn't think there was a need for multiple PRs, because this doesn't change code base, so there was no blast.

If there is a blast, I don't mind creating 3 PRs 👍

**Comment by raisedadead** [comment]
>  because this doesn't change code base ...

Correct, while you are only removing comments, it is critical to understand what that means. When removing ESLint comments, you engage with the tool to validate code. That is, do static code analysis. 

While you assume there will be no impact, it's still an assumption - because you are the OP. 

When we break this into independent PRs, we limit the scope of review (also known as blast radius or impact area in software engineering), look at each ESLint comment, and what it is doing before and after. 

Keeping it atomic makes everyone's life easier. 

It was not a question of will the code break, it was about the collaborative review process. I hope it clears up any confusion you have.

**Pull request closed without merging**
