### PR TITLE
update Data Structures to es6

### LINKED ISSUE #37820: Inconsistent code in Data Structures
**Describe your problem and how to reproduce it:**

Code in Data Structure challanges is inconsistent.

I believe we should use es6 class syntax across all Data Structures challenges since they are less verbose and emphasize the code in each method rather than the methods themselves.

I started a PR (#37819) to update the code.

**Add a Link to the page with the problem:**

[Create a Set Class](https://www.freecodecamp.org/learn/coding-interview-prep/data-structures/create-a-set-class) uses an es6 class
[Perform an Intersection on Two Sets of Data](https://www.freecodecamp.org/learn/coding-interview-prep/data-structures/perform-an-intersection-on-two-sets-of-data) uses a function object

**Tell us about your browser and operating system:**
* Browser Name: Chrome
* Browser Version: 78
* Operating System: Windows 10

### PR DESCRIPTION
**Pull request by UziTech**
- [x] I have read [freeCodeCamp's contribution guidelines](https://github.com/freeCodeCamp/freeCodeCamp/blob/master/CONTRIBUTING.md).
- [x] My pull request has a descriptive title (not a vague title like `Update index.md`)
- [x] My pull request targets the `master` branch of freeCodeCamp.
- [x] None of my changes are plagiarized from another source without proper attribution.
- [x] All the files I changed are in the same world language (for example: only English changes, or only Chinese changes, etc.)
- [x] My changes do not use shortened URLs or affiliate links.

Update Data Structures code to es6 classes to be more consistent.

Closes #37820

### CODE REVIEW

**Comment by RandellDawson** [comment]
@UziTech To be more consistent with what?

**Comment by UziTech** [comment]
To be more consistent with the other code in the Data Structures group. Right now some are using functions and some are using classes. I am also making the comments and other parts more consistent with each other.

**Comment by RandellDawson** [comment]
@UziTech Again, it would be better to create an issue first, so these kinds of changes can be discussed and agreed upon before a PR is created.  I personally don't see any reason to make these changes.  I think it is good to show different ways of approaching these problems (i.e. different syntax).  The user can choose to code the challenges the way they want as long as the tests pass.

**Comment by UziTech** [comment]
@RandellDawson I created issue #37820 to discuss this

**Pull request closed without merging**
