### PR TITLE
fix: errors with multiple editor tabs

### PR DESCRIPTION
**Pull request by ojeytonwilliams**
- fix: enforce multifile tab order
- fix: sort challengeFiles to prevent remounts
- fix: make editor tabs and panes match

### CODE REVIEW

**Review by naomi-lgbt — APPROVED** [review]
TBH I'm not entirely sure what this is fixing, but it works 🙂

**Comment by ojeytonwilliams** [comment]
Sorry, you're quite right, I should have explained. The issues were:

- The editor pane order didn't match the order of the tabs that open them
- Typing anywhere in the multi-file editor would shift focus to the editable region
- Typing would cause the tabs to reorder

All of them stemming from the same mistake.

**Comment by nhcarrigan** [comment]
> Typing anywhere in the multi-file editor would shift focus to the editable region

Is this the issue I've been seeing where I type one character in the editable region and get my cursor sent to the beginning of the first line?

**Comment by ojeytonwilliams** [comment]
> Is this the issue I've been seeing where I type one character in the editable region and get my cursor sent to the beginning of the first line?

Yes, that should be resolved.

**Review by ShaunSHamilton — APPROVED** [review]
Thank you, Oliver. Finally, a PR with <10 additions.

**Pull request merged**
