### PR TITLE
 converted nav log svg to functional component

### PR DESCRIPTION
**Pull request by Sanskar95**
- [ ] I have read [freeCodeCamp's contribution guidelines](https://github.com/freeCodeCamp/freeCodeCamp/blob/master/CONTRIBUTING.md).
- [ ] My pull request has a descriptive title (not a vague title like `Update index.md`)
- [ ] My pull request targets the `master` branch of freeCodeCamp.
- [ ] None of my changes are plagiarized from another source without proper attribution.
- [ ] All the files I changed are in the same world language (for example: only English changes, or only Chinese changes, etc.)
- [ ] My changes do not use shortened URLs or affiliate links.

Closes #XXXXX

### CODE REVIEW

**Comment by raisedadead** [comment]
Hi @Sanskar95 

Once again, do not edit off of GitHub. I would urge you to respect the maintainers time. 

Have you tested this locally?

**Comment by Sanskar95** [comment]
I tested it on gitpod

**Comment by raisedadead** [comment]
> I tested it on gitpod

Great, and now you should fix the linting errors and follow the guidelines on how to open a PR. It's important as a process.

**Comment by Sanskar95** [comment]
sure will do that

**Pull request closed without merging**
