### PR TITLE
fix(learn): Change width for piano on step 28

### PR DESCRIPTION
**Pull request by RafaelDavisH**
Checklist:

- [x] I have read [freeCodeCamp's contribution guidelines](https://contribute.freecodecamp.org).
- [x] My pull request has a descriptive title (not a vague title like `Update index.md`)
- [x] My pull request targets the `main` branch of freeCodeCamp.
- [ ] I have tested these changes either locally on my machine, or GitPod.

Closes n/a

### CODE REVIEW

**Comment by RafaelDavisH** [comment]
For the 768px max-width media query, the Piano's width is too small to fit the keys. 

Its just a cosmetic adjustment to have the keys centered properly. 

The Piano preview also needs the adjustment for mobile view. I could find it on the docs to correct it. 


image

**Comment by moT01** [comment]
Typically, we would probably want to make an issue to discuss it and find the appropriate fix. It's fine for this one - we can just give it a review and discuss it here.

**Comment by nhcarrigan** [comment]
> The Piano preview also needs the adjustment for mobile view. I couldn't find it on the docs to correct it.

The preview is pulled from the `# --solution--` value of the final step, if I remember correctly.

**Comment by RafaelDavisH** [comment]
Sorry for jumping creating Issue and discussion part. So, since the preview needs to be fixed as well, can I go head and make the changes?

Or should I create an issue for it?

**Comment by nhcarrigan** [comment]
Go ahead and make the changes 🙂

**Comment by RafaelDavisH** [comment]
@nhcarrigan, the preview was also fixed in this PR.

For the first time, I ran fcc locally with Gitpod to make sure the preview look good, and it does! Now I can sleep happy.
Thanks for the help.

**Review by naomi-lgbt — CHANGES_REQUESTED** [review]
The last file has the value updated in the solution but not the seed.

**Review by naomi-lgbt — APPROVED** [review]
This should be good to go!

**Review by moT01 — APPROVED** [review]
LGTM @RafaelDavisH 🎉

**Pull request merged**
