### PR TITLE
Fix stack trace error in javascript challenge

### LINKED ISSUE #5560: RangeError with correct solution on Waypoint: Passing Values to Functions with Arguments
Challenge [Waypoint: Passing Values to Functions with Arguments](http://www.freecodecamp.com/challenges/waypoint-passing-values-to-functions-with-arguments#?solution=%2F%2F%20Example%0Afunction%20ourFunction(a%2C%20b)%20%7B%0A%20%20console.log(a%20-%20b)%3B%0A%7D%0AourFunction(10%2C%205)%3B%20%2F%2F%20Outputs%205%0A%0A%2F%2F%20Only%20change%20code%20below%20this%20line.%0A%0Afunction%20myFunction(c%2C%20d)%7B%0A%20%20console.log(c%20%2B%20d)%3B%0A%7D%0AmyFunction(2%2C%203)%3B%0A) has an issue.
User Agent is: <code>Mozilla/5.0 (Macintosh; Intel Mac OS X 10_11_2) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/47.0.2526.106 Safari/537.36</code>.

Running tests outputs `RangeError: Maximum call stack size exceeded` and no tests pass.

My code:
```javascript
// Example
function ourFunction(a, b) {
  console.log(a - b);
}
ourFunction(10, 5); // Outputs 5

// Only change code below this line.

function myFunction(c, d){
  console.log(c + d);
}
myFunction(2, 3);

```

### PR DESCRIPTION
**Pull request by DDaems**
- added a additional check to make sure the function exists

close #5560

### CODE REVIEW

**Comment by KrisVos130** [comment]
This shouldn't fix #5560 since that error still displays even if you don't modify anything and click submit or when you add myFunction and it actually is a function.

**Comment by DDaems** [comment]
I have tested it thoroughly on my local copy.

**Comment by ShaggyTech** [comment]
@DDaems I tested your changes on my local copy and can confirm that this fixes #5560

**Comment by ltegman** [comment]
Woot! Good work getting to the bottom of this! :+1:

**Pull request merged**
