### PR TITLE
fix(learn): Consolidated comments for Front End Libraries challenges

### PR DESCRIPTION
**Pull request by RandellDawson**
Checklist:
- [x] I have read [freeCodeCamp's contribution guidelines](https://github.com/freeCodeCamp/freeCodeCamp/blob/master/CONTRIBUTING.md).
- [x] My pull request has a descriptive title (not a vague title like `Update index.md`)
- [x] My pull request targets the `master` branch of freeCodeCamp.
- [x] All the files I changed are in the same world language, for example: only English changes, or only Chinese changes, etc.

Related to PR #38040

This PR consolidates/removes comments in the challenge seed code in the `Front End Libraries` certification challenges, to be able to create a small translation lookup object for translating the English comments to other languages.  It consolidates/removes the remaining comments.

### CODE REVIEW

**Review by moT01 — APPROVED** [review]
I'm fine with this PR 🎉 

One thing I wanted to point out that's probably a separate issue - I noticed that a number of the challenges remove the comments in the solution and some of them leave the comments in the solution. Seems like we could just remove all comments from solutions in all the challenges.

**Comment by RandellDawson** [comment]
> Seems like we could just remove all comments from solutions in all the challenges.

I sometimes removed the comments from the solutions, but sometimes did not.  Since the solutions are not displayed anywhere, it really does not make any difference.  However, if we wanted to shorten the code a bit, I have helper functions that I can use in a script and remove all of them in one swoop.  I do think this should be documented in a separate issue though.

**Review by thecodingaviator — APPROVED** [review]
LGTM

**Comment by thecodingaviator** [comment]
Thank you for your contribution to the page! 👍
We're happy to accept these changes, and look forward to future contributions. 📝

**Pull request merged**
