### PR TITLE
Create subarray.cpp

### PR DESCRIPTION
**Pull request by DSK2307**
Checklist:

- [x] I have read and followed the [contribution guidelines](https://contribute.freecodecamp.org).
- [x] I have read and followed the [how to open a pull request guide](https://contribute.freecodecamp.org/how-to-open-a-pull-request/).
- [ ] My pull request targets the `main` branch of freeCodeCamp.
- [x] I have tested these changes either locally on my machine, or GitPod.

Closes #XXXXX

### CODE REVIEW

**Comment by DSK2307** [comment]
please remove the spam label I dont know all about it I made contribution by mistake I am completely new to this.
please i request you

**Comment by ilenia-magoni** [comment]
You added a random file to the repo, this is the definition of spam PR. The spam label here stays

**Comment by DSK2307** [comment]
I am very new to open source contribution . I dont know all about there . Basically I am in learnig phase how to contribute to open source

> You added a random file to the repo, this is the definition of spam PR. The spam label here stays

**Comment by naomi-lgbt** [comment]
You have created two pull requests which do not follow our contributor guidelines.

We appreciate that you are trying to learn how to contribute to open source, but our process is clearly and thoroughly documented.

When you create pull requests like this one, which are meaningless, low-effort, and bring no actual value to the project, all you are achieving is creating extraneous noise for our maintainer team - many of whom generously donate their time as volunteers to help our mission.

By definition, that's spam. The `spam` label was accurately applied to your pull requests, and will not be removed.

**Pull request closed without merging**
