### PR TITLE
Modified Spanish endings and sentences.

### PR DESCRIPTION
**Pull request by thisislola**
Some of the Spanish endings needed a change from the Usted form (formal) to the informal form (since that is how the article should be written in Spanish). 
Modified briefly some sentences to make it more understandable for Spanish readers.

- [x] I have read [freeCodeCamp's contribution guidelines](https://github.com/freeCodeCamp/freeCodeCamp/blob/master/CONTRIBUTING.md).
- [x] My pull request has a descriptive title (not a vague title like `Update index.md`)
- [x] My pull request targets the `master` branch of freeCodeCamp.
- [x] None of my changes are plagiarized from another source without proper attribution.
- [x] My article does not contain shortened URLs or affiliate links.

If your pull request closes a GitHub issue, replace the XXXXX below with the issue number.

Closes #XXXXX

### CODE REVIEW

**Comment by lynxlynxlynx** [comment]
Is this a difference between European Spanish and LATAM Spanish?

**Comment by thisislola** [comment]
Not really. The modifications I made were based on the original article. The author gives advice such as "go alone", but the translation to Spanish was set to "to go alone", which can be confusing

**Review by joshalling — APPROVED** [review]
This LGTM! 👍 👍

**Comment by joshalling** [comment]
Thanks @thisislola! 👍 🌋

**Pull request merged**
