### PR TITLE
Feat/add progress indicators for blocks

### PR DESCRIPTION
**Pull request by matthew-beaty**
- [X] I have read [freeCodeCamp's contribution guidelines](https://github.com/freeCodeCamp/freeCodeCamp/blob/master/CONTRIBUTING.md).
- [X] My pull request has a descriptive title (not a vague title like `Update index.md`)
- [X] My pull request targets the `master` branch of freeCodeCamp.
- [X] None of my changes are plagiarized from another source without proper attribution.
- [X] My article does not contain shortened URLs or affiliate links.

Partially addresses #17869 by adding progress indicators to the Curriculum.
screenshot 2018-11-14 13 23 29

Here's examples of videos for completing a single challenge and completing all challenges in a section. Also included open and close behavior in video 2. 

https://www.dropbox.com/sh/fbopqytlk03ottu/AABm0ByCsjCVBP2ZIIlhkCmya?dl=0

### CODE REVIEW

**Comment by utsab** [comment]
@matthewchase, sorry I am behind on the progress for this PR.  Thanks for working on the [issue ](https://github.com/freeCodeCamp/freeCodeCamp/issues/17869) I opened about this.   Were you able to fix up the conflicting files with this PR?  Let me now if you'd like help with this.  I can hop on a zoom session to pair program with you.

**Comment by QuincyLarson** [comment]
@matthewchase This looks really cool and clean! Could you address the conflicts and record a short video demoing the functionality, and what these look like in various stages of completion?

**Comment by matthewchase** [comment]
@utsab, no problem! Thanks for letting me figure this one out, this is my first external diff, and it was a lot of fun =) 

@QuincyLarson, you got it, dude!

**Comment by matthewchase** [comment]
@QuincyLarson, updated the diff with the suggested changes and included videos of the behavior.

**Review by raisedadead — APPROVED** [review]

**Comment by raisedadead** [comment]
#### :sparkles: :sparkles: **LGTM.** :sparkles: :sparkles: 

Thanks @matthewchase 

Happy Contributing!

**Pull request merged**
