### PR TITLE
test(e2e, playwright): added test case for email-signup

### PR DESCRIPTION
**Pull request by lalithasj**
modified:   client/src/pages/email-sign-up.tsx
	new file:   e2e/email-sign-up.spec.ts

Checklist:

- [X ] I have read and followed the [contribution guidelines](https://contribute.freecodecamp.org).
- [ X] I have read and followed the [how to open a pull request guide](https://contribute.freecodecamp.org/#/how-to-open-a-pull-request).
- [ X] My pull request targets the `main` branch of freeCodeCamp.
- [ X] I have tested these changes either locally on my machine, or GitPod.

Closes #XXXXX

camperbot cant code

### CODE REVIEW

**Comment by moT01** [comment]
Looks like a number of failing tests here @lalithasj. Do you want to take a look at those? Let us know if you need any guidance.

**Comment by lalithasj** [comment]
Hi @moT01,
Can you suggest how to add useTranslator() and apiLocation. 
Thanks

**Comment by lalithasj** [comment]
Yes, I am trying to fix these errors. Sure, if any help is required, I'll ask for guidance

**Comment by moT01** [comment]
The tests I've seen [import the translation file directly,](https://github.com/freeCodeCamp/freeCodeCamp/blob/main/e2e/certification.spec.ts#L2) [here's an example.](https://github.com/freeCodeCamp/freeCodeCamp/blob/main/e2e/certification.spec.ts#L38)

And here's an example of [a test using the env variables.](https://github.com/freeCodeCamp/freeCodeCamp/blob/main/e2e/staging-warning-modal.spec.ts#L13) You would want `process.env.API_LOCATION`

**Comment by lalithasj** [comment]
Thanks a lot

**Pull request closed without merging**
