### PR TITLE
[Fix] Make streak counter show 0 if no streak

### PR DESCRIPTION
**Pull request by thecodingaviator**
- [x] I have read [freeCodeCamp's contribution guidelines](https://github.com/freeCodeCamp/freeCodeCamp/blob/master/CONTRIBUTING.md).
- [x] My pull request has a descriptive title (not a vague title like `Update index.md`)
- [x] My pull request targets the `master` branch of freeCodeCamp.
- [x] None of my changes are plagiarized from another source without proper attribution.
- [x] My article does not contain shortened URLs or affiliate links.

If your pull request closes a GitHub issue, replace the XXXXX below with the issue number.

### CODE REVIEW

**Comment by RaspberryLime** [comment]
How does this fix #17822? That isn't about changing a "1" to a "0".

**Review by raisedadead — COMMENTED** [review]
Please elaborate how your fix fixes the issue?

**Comment by thecodingaviator** [comment]
No, it doesn’t fix the issue, that is a severe mistake on my part, what it does is that it sets the steak to 0 if it 0 is instead of 1 which it shows now

**Comment by raisedadead** [comment]
Thanks for the clarification.

> what it does is that it sets the steak to 0 if it 0 is instead of 1 which it shows now

I think we do not want that. 

Creating an account on freeCodeCamp.org counts as one point. This is quite common of platform like GitHub where you will see the map, show one green square when you joined.

So in reality 1 is actually a valid point. 

Maybe adding a tooltip on the UI to showcase, this might make more sense.

Anyways thanks for the PR. And closing this on that note.

**Pull request closed without merging**
