### PR TITLE
sample 404 page

### PR DESCRIPTION
**Pull request by AEA2002**
This refers to: #1504
don't know if you still need this, but I created a 404 page: _notFound.html_ 
There is also _main.png_ and a _fonts_ folder.

Any comments, suggestions, requests are welcome.
No worries, if you don't need it, it was good practice for me.

Thanks!

### CODE REVIEW

**Comment by BerkeleyTrue** [comment]
@AEA2002 Thanks. Can you squash your commits into one? https://github.com/FreeCodeCamp/FreeCodeCamp/wiki/git-rebase

**Comment by AEA2002** [comment]
@BerkeleyTrue Sure, I was trying to merge only the commit titled *page suggestion 404.* Can you tell me how to do that?

**Comment by BerkeleyTrue** [comment]
Sure, take a look at https://github.com/FreeCodeCamp/FreeCodeCamp/wiki/git-rebase

**Comment by AEA2002** [comment]
I looked at the **git-rebase**. However, I was inquiring about merging only 1 of the commits. 
The other commits will send information/files that are not needed. Unless, I misunderstood, the rebase article was about **combining** the commits. If the extra/unnecessary data is okay, then I have no problem doing git-rebase.

**Comment by awesomeaniruddh** [comment]
@AEA2002 To combine or squash the last `n` commits, you must run 
```
git rebase -i HEAD~n
```
and follow the rest of the instructions on the wiki article. Let me know if they're not clear enough and I'll fix it :)

**Comment by BerkeleyTrue** [comment]
You can remove commits using during a rebase as well.

**Comment by AEA2002** [comment]
@awesomeaniruddh I understood for the most part. Hover, I was trying to use only one out of the six commits listed above. (@BerkeleyTrue, also), It was not clear in the article how to select one commit out of many. 
I am submitting a new pull request because I made a mess of this one. It has multiple copies of commits.

**Comment by awesomeaniruddh** [comment]
@AEA2002 Yeah, I didn't cover that.

Also, I'm closing this PR because you opened a new one :) Why don't you rename *that* to Sample 404 page so that people don't have to refer to this one?

**Comment by AEA2002** [comment]
@awesomeaniruddh 
okay, will do

**Pull request closed without merging**
