### PR TITLE
Move video/jobs to redux

### PR DESCRIPTION
**Pull request by BerkeleyTrue**
- [x] finish job board move (in progress)
- [x] update react-router
- [x] update history
- [x] update react-router-redux
- [x] Fix hikes issues
- [x] Update eslint/gulp-eslint

### CODE REVIEW

**Comment by BerkeleyFalse** [comment]
@BerkeleyTrue updated the pull request.

**Comment by BerkeleyFalse** [comment]
@BerkeleyTrue updated the pull request.

**Comment by BerkeleyTrue** [comment]
@ltegman Good idea, I'll do that.

**Comment by BerkeleyTrue** [comment]
Now live beta!

**Comment by ltegman** [comment]
Great stuff! Can't wait to look over the redux code more when I have more time. Tested out videos and jobs and didn't run into problems with either :+1:

**Pull request merged**
