### PR TITLE
Fix re-declared dataset/variable issue

### LINKED ISSUE #12762: Const can't be redeclared in challenges

### LINKED ISSUE #13936: `dataset` is already declared
Challenge [work-with-dynamic-data-in-d3](http://beta.freecodecamp.com/en/challenges/data-visualization-with-d3/work-with-dynamic-data-in-d3) has an issue.
User Agent is: <code>Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/55.0.2883.75 Safari/537.36</code>.

```html


<body>
  <script>
    const dataset = [12, 31, 22, 17, 25, 18, 29, 14, 9];
    
    d3.select("body").selectAll("h2")
      .data(dataset)
      .enter()
      .append("h2")      
      .text((d) => d + " USD");
      
      // Add your code above this line
  </script>
</body>

```
This would be the right solution, but it says `dataset` is already declared. The issue is resolved by renaming the variable.

### PR DESCRIPTION
**Pull request by zixu-zhao**
#### Pre-Submission Checklist

- [x] Your pull request targets the `staging` branch of freeCodeCamp.
- [x] Branch starts with either `fix/`, `feature/`, or `translate/` (e.g. `fix/signin-issue`)
- [x] You have only one commit (if not, [squash](http://forum.freecodecamp.com/t/how-to-squash-multiple-commits-into-one-with-git/13231) them into one commit).
- [x] All new and existing tests pass the command `npm test`. Use `git commit --amend` to amend any fixes.

#### Type of Change

- [x] Small bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds new functionality)
- [ ] Breaking change (fix or feature that would change existing functionality)
- [ ] Add new translation (feature adding new translations)

#### Checklist:

- [x] Tested changes locally.
- [x] Closes currently open issue (replace XXXX with an issue no): Closes #XXXX

#### Description

This issue is variable re-declaration that causes unsuccessful submit.

The problem is:
1. Once completing first submit, the test frame left in the iframe without deleting or cleaning.
2. The previous cleaning of test frame doesn't work becasue it remove document in the iframe.
3. It requires to remove the iframe itself before the new test injection to aviod the issue.

How to fix:
Remove the iframe each time before a set of tests injection; aviod synchronous problem as well.
This approach should not break any original logic of the test processes.

Closes #12762

### CODE REVIEW

**Comment by systimotic** [comment]
Hi @ZZhaoTireless! Can you make this PR refer to #12762 instead of #13936?

@BerkeleyTrue Can you QA? Is this a valid way to solve this issue?

**Comment by ZZhaoTireless** [comment]
Hi @systimotic, changing finished. Thanks!

**Comment by BerkeleyTrue** [comment]
> Set the content in the iframe to be blank page each time after a set of tests finished

This assumes all tests are synchronous. Why not blank the frame before the source code is injected?

**Comment by ZZhaoTireless** [comment]
HI @BerkeleyTrue, your approach is more stable. I would change my code and resubmit. Thanks!

**Comment by ZZhaoTireless** [comment]
Hi @BerkeleyTrue, I found the way to solve this issue. The problem is we need to delete all iframe to prevent the re-declaration existing.

**Comment by BerkeleyTrue** [comment]
Yes, that would fix the issue, but it might introduce others. I can't remember why but there was a reason why I did not opt to delete the iframes per tests.

**Comment by BerkeleyTrue** [comment]
Please see my comments in the issue

**Comment by erfe1** [comment]
ارجو مراسلتي بلغة العربية

**Comment by ZZhaoTireless** [comment]
@BerkeleyTrue Hi, I have no clue how to fix the issue. This issue may beyond my ability. Thanks for the help.

**Pull request closed without merging**
