### PR TITLE
ifconfig

### PR DESCRIPTION
**Pull request by Joe-Lalama**
added an explanation of the ifconfig command.

- [x] I have read [freeCodeCamp's contribution guidelines](https://github.com/freeCodeCamp/freeCodeCamp/blob/master/CONTRIBUTING.md).
- [x] My pull request has a descriptive title (not a vague title like `Update index.md`)
- [x] My pull request targets the `master` branch of freeCodeCamp.
- [x] None of my changes are plagiarized from another source without proper attribution.
- [x] My article does not contain shortened URLs or affiliate links.

If your pull request closes a GitHub issue, replace the XXXXX below with the issue number.

Closes #XXXXX

### CODE REVIEW

**Comment by Joe-Lalama** [comment]
hope this is helpful

**Comment by RandellDawson** [comment]
@Asjas I fixed the title, folder name and file name.  Feel free to merge if you want.

**Review by skyemorgan0907 — CHANGES_REQUESTED** [review]
Incongruity

**Comment by procode200** [comment]
@RandellDawson Cool!

**Review by moT01 — APPROVED** [review]
Looks good @Joe-Lalama, thanks for contributing to freeCodeCamp!

**Pull request merged**
