### PR TITLE
Made code consistent in challenge Basic JS - Comparison with strict inequality operator 

### LINKED ISSUE #18893: Comparison with the Inequality Operator and Comparison with the Strict Inequality Operator inconsistent formatting
**Describe your problem and how to reproduce it:**
These task has inconsistent code where task is pretty much the same. I would believe that freecode camp should use same code style everywhere. If one task has comments, second should have them too.
Basic JavaScript: Comparison with the Inequality Operator
Basic JavaScript: Comparison with the Strict Inequality Operator

**Add a Link to the page with the problem:**
https://learn.freecodecamp.org/javascript-algorithms-and-data-structures/basic-javascript/comparison-with-the-inequality-operator
https://learn.freecodecamp.org/javascript-algorithms-and-data-structures/basic-javascript/comparison-with-the-strict-inequality-operator

image
image

### PR DESCRIPTION
**Pull request by Nirajn2311**
- [x] I have read [freeCodeCamp's contribution guidelines](https://github.com/freeCodeCamp/freeCodeCamp/blob/master/CONTRIBUTING.md).
- [x] My pull request has a descriptive title (not a vague title like `Update index.md`)
- [x] My pull request targets the `master` branch of freeCodeCamp.
- [x] None of my changes are plagiarized from another source without proper attribution.
- [x] My article does not contain shortened URLs or affiliate links.

If your pull request closes a GitHub issue, replace the XXXXX below with the issue number.

Closes #18893

### CODE REVIEW

**Comment by lynxlynxlynx** [comment]
LGTM

**Comment by lynxlynxlynx** [comment]
This one has an open bug attached ...

**Comment by RandellDawson** [comment]
@Nirajn2311 Would you be willing to recreate this PR to resolve issue https://github.com/freeCodeCamp/freeCodeCamp/issues/18893 ?

**Comment by Nirajn2311** [comment]
@RandellDawson I have restored the branch and you may merge this PR.

**Comment by RandellDawson** [comment]
@lynxlynxlynx What was the open bug you referred to above?

**Comment by lynxlynxlynx** [comment]
See the first post ...

**Comment by RandellDawson** [comment]
Do you mean your `LGTM` comment?  So you are saying there is no bug and we should merge this PR as is?

**Comment by lynxlynxlynx** [comment]
oh come on, you even referenced it yourself.

**Review by RandellDawson — APPROVED** [review]
I am fine with the current changes.  Let's get this merged.

**Review by Manish-Giri — APPROVED** [review]
LGTM. Thank You for your contribution.

**Pull request merged**
