### PR TITLE
Remove Confusing Word-Blank Test

### LINKED ISSUE #5661: Test "At least 30 characters with empty inputs" on Waypoint: Word Blanks
Challenge [Waypoint: Word Blanks](http://www.freecodecamp.com/challenges/waypoint-word-blanks) has an issue.
User Agent is: <code>Mozilla/5.0 (Macintosh; Intel Mac OS X 10_11_2) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/48.0.2564.48 Safari/537.36</code>.
Please describe how to reproduce this issue, and include links to screenshots if possible.

This test is tripping up a disproportionate amount of campers. I find it to be a tedious task without educational merit, as they've already proven the knowledge of concatenating strings by creating spaces between the word blanks. We should remove this test IMO.

### PR DESCRIPTION
**Pull request by arialaurel**
Closes #5661

### CODE REVIEW

**Comment by SaintPeter** [comment]
What, then, is this mini-bonfire about?  If all they're doing is concatenating strings, then at VERY least we should update the tests to ensure they have `\b` to either side of each word, to make sure they're adding in spaces between words.

Also, the descriptive text should be updated to reflect the change.

**Comment by ltegman** [comment]
I'm open to adding a different test that's slightly less arbitrary. Maybe a test that _something_ was inserted in between the inputs or a minimum length of 3 characters when inputs are blank?

**Comment by SaintPeter** [comment]
One of the points that I made in earlier concatenation challenges was that you need to add your own spaces.  I think that by checking for `\bword\b` on each word we force that issue.  Note that `\b` matches beginning and ending of the string.  Have the requirment that they have something "non word" between each string.  We're not just going to let them smoosh it all together.

I agree the 30 is arbitrary, but we need them to something more than just `+` a list of variables together.  Even if all they did was `word1 + " " + word2 + " " + word3` etc, and we ENFORCED that, I'd be good with it.  Otherwise there is not much problem to solve.

**Comment by ltegman** [comment]
Sounds good, I'll do that and update this PR.

**Comment by ltegman** [comment]
Sorry for the delay,  fixed this up now. Let me know if you have a suggestion for the how the tests could be better worded. I'm not in love with `should contain all of the passed words in a space-separated sentence.`

**Comment by SaintPeter** [comment]
`separated by non-word characters`?

**Comment by ltegman** [comment]
Updated. Hopefully that's better. There's not really any super elegant way to explain that test case :/

**Comment by SaintPeter** [comment]
:+1: 
We'll see how it goes.

**Pull request merged**
