### PR TITLE
fix(curriculum): spreadsheet description

### LINKED ISSUE #56663: Spreadsheet project step 98 needs minor clarification
### Describe the Issue

In the step 98 of the js beta spreadsheet project, the instructions fail to specify the order of the numbers to be returned in the result array(s). For eg does it want the first two numbers in the order they are given in the input array? And does it want the last two numbers in the order they are given in the input array? This lack of information can lead to code like the one below being rejected without a clear explanation why.
It would be good to be explicit in the instructions about the expected order of the numbers in the final array.

### Affected Page

https://www.freecodecamp.org/learn/javascript-algorithms-and-data-structures-v8/learn-functional-programming-by-building-a-spreadsheet/step-98

### Your code

```
lasttwo : nums => [nums[nums.length-1], nums[nums.length-2]]

```

### Expected behavior

Directly state that the expected array needs to retain the same order of elements as the input array.

### Screenshots

_No response_

### System

N/A

### Additional context

Original forum post that revealed the issue 
https://forum.freecodecamp.org/t/learn-functional-programming-by-building-a-spreadsheet-step-98/716040?u=hbar1st

### PR DESCRIPTION
**Pull request by Xolicle**
Checklist:

- [x] I have read and followed the [contribution guidelines](https://contribute.freecodecamp.org).
- [x] I have read and followed the [how to open a pull request guide](https://contribute.freecodecamp.org/how-to-open-a-pull-request/).
- [x] My pull request targets the `main` branch of freeCodeCamp.
- [x] I have tested these changes either locally on my machine, or GitPod.

Closes #56663

### CODE REVIEW

**Comment by Xolicle** [comment]
fixed the description.

**Comment by gikf** [comment]
Hey @Xolicle,

is this PR related to some existing issue? If yes, please link it properly.

**Comment by Xolicle** [comment]
It is an existing issue. I will try to link it, this was my first time in open source.

**Comment by ilenia-magoni** [comment]
> Closes #XXXXX

to link you need to put here in the first post the number of the issue

**Comment by Xolicle** [comment]
#56663. This is the number

**Comment by ilenia-magoni** [comment]
> Closes #XXXXX

please edit the first post and add the issue number here

**Comment by Xolicle** [comment]
I did, hope it's fine now

**Review by gikf — APPROVED** [review]

**Review by a2937 — APPROVED** [review]
Hi @Xolicle. Congrats on your first pull request (PR)! 🎉

Thank you for your contribution to the page! 👍
We are happy to accept these changes and look forward to future contributions. 📝

**Pull request merged**
