### PR TITLE
feat(client): ts-migrate client/src/pages

### PR DESCRIPTION
**Pull request by awu43**
Checklist:

- [x] I have read [freeCodeCamp's contribution guidelines](https://contribute.freecodecamp.org).
- [x] My pull request has a descriptive title (not a vague title like `Update index.md`)
- [x] My pull request targets the `main` branch of freeCodeCamp.
- [x] I have tested these changes either locally on my machine, or GitPod.

Refers #42256

Migrated files:
```
/client/src/pages/404.js
/client/src/pages/certification.js
/client/src/pages/challenges.js
/client/src/pages/challenges.test.js
/client/src/pages/donate.js
/client/src/pages/email-sign-up.js
/client/src/pages/index.js
/client/src/pages/learn.js
/client/src/pages/search.js
/client/src/pages/settings.js
/client/src/pages/unsubscribed.js
/client/src/pages/update-email.js
/client/src/pages/user.js
```

Some issues:
* There are imported components with a `default={true}` prop that doesn't seem to be used anywhere. I decided to leave them be at the moment because of how many there were.
* Multiple `Router` children have a TS error from the `path` prop.
* The props passed to `Redirect` in `challenges.tsx` don't match with `toLearnPath()` parameters, not sure what to do about this one.
* The original `DonatePage` component had a spread operator on `props`, not sure what effect that had.
```jsx
class DonatePage extends Component {
  constructor(...props) {
    super(...props);
```
* The `Spacer` component from `src/components/helpers` causes a TS error `'Spacer' cannot be used as a JSX component.`.

### CODE REVIEW

**Review by raisedadead — COMMENTED** [review]
Hey there,

Thank you for taking the time to contribute to the TypeScript migration. 

The main issue has been updated a lot over the last few days, and so we suggest you re-read it and update this pull request to match if you have the time.

The main goals for a PR are:
- [ ] Changing the filename from `PascalCase` to `kebab-case` and ensuring that the imports in code are all still valid.
- [ ] Changing the file extension to .tsx (if a file has React JSX syntax)
- [ ] Fixing as many TypeScript and Eslint errors as you can while refactoring the code.

If you need any assistance, please reach out in our [contributing chat room](https://chat.freecodecamp.org/channel/contributors).

**Review by ShaunSHamilton — APPROVED** [review]
I am happy with merging this, and typing the `.test.ts` file failing the test on `next`. Although, I am unsure why Git has shown `client/package.json` as having been altered 🤷‍♂️ 

👍

**Comment by moT01** [comment]
should be good to go 🤞

**Comment by awu43** [comment]
>  I am unsure why Git has shown `client/package.json` as having been altered

That would be from the type definition packages I added. Should I not have done that?

**Comment by ShaunSHamilton** [comment]
> Should I not have done that?

@awu43 No, you did what was expected. The issue came after a rebase  where GitHub showed an unexpected diff.

**Pull request merged**
