### PR TITLE
fix(curriculum): build a city skyline step 20 instruction updated

### PR DESCRIPTION
**Pull request by denquinlan**
Checklist:

- [x] I have read [freeCodeCamp's contribution guidelines](https://contribute.freecodecamp.org).
- [x] My pull request has a descriptive title (not a vague title like `Update index.md`)
- [x] My pull request targets the `main` branch of freeCodeCamp.
- [x] I have tested these changes either locally on my machine, or GitPod.

Addresses https://github.com/freeCodeCamp/freeCodeCamp/issues/47555

### CODE REVIEW

**Comment by ieahleen** [comment]
Hey there, is this for a certain issue? Please link the issue. Otherwise, please explain your changes  please.

**Comment by denquinlan** [comment]
This is for issue #47555, link here: https://github.com/freeCodeCamp/freeCodeCamp/issues/47555

Specifically I fixed the wording in step 20 to make it less hand-holdy. I wanted to make sure the wording I used was alright before attempting to fix any additional steps listed in this issue.

**Review by naomi-lgbt — APPROVED** [review]
banger pr, thanks for contributing!

**Review by Sboonny — APPROVED** [review]
#### :sparkles: :tada: **AWESOME!** :tada: :sparkles:

 Hi @denquinlan, thanks for this pull request and for contributing to the code-base for the first time. We are looking forward to more contributions from you in the future.

 Cheers & happy contributing!

**Pull request merged**
