### PR TITLE
Fib corrections. Additional example added.

### PR DESCRIPTION
**Pull request by MFry**
- [x] I have read [freeCodeCamp's contribution guidelines](https://github.com/freeCodeCamp/freeCodeCamp/blob/master/CONTRIBUTING.md).
- [x] My pull request has a descriptive title (not a vague title like `Update index.md`)
- [x] My pull request targets the `master` branch of freeCodeCamp.
- [x] None of my changes are plagiarized from another source without proper attribution.
- [x] My article does not contain shortened URLs or affiliate links.

### CODE REVIEW

**Comment by RandellDawson** [comment]
@MFry You can not add image files to the directory.  You will need to link from another source containing the images you want to link in the article.  Please remove these added files from your PR and link to external images.

Thank you.

**Comment by MFry** [comment]
@RandellDawson that seems like an oversight, especially for mathematical symbols. 
 I would think it would be useful to have all of the common ones added to a shared folder for reference. Makes the math based text much more approachable.

**Comment by mjasnowski** [comment]
Looks like build is still failing due to a file naming convention check:

<code>
    The below occured in:
    /home/travis/build/freeCodeCamp/freeCodeCamp/guide/english/computer-science/dynamic-programming/img/Big_O_of_N.gif
  
Error: Big_O_of_N.gif is not a valid file name, please use 'index.md'
      Found in:
        /home/travis/build/freeCodeCamp/freeCodeCamp/guide/english/computer-science/dynamic-programming/img/Big_O_of_N.gif
    
    at Promise (/home/travis/build/freeCodeCamp/freeCodeCamp/tools/scripts/ci/ensure-guide-page-naming.js:97:9)
    at new Promise (<anonymous>)
    at checkFileName (/home/travis/build/freeCodeCamp/freeCodeCamp/tools/scripts/ci/ensure-guide-page-naming.js:94:10)
    at checkFile (/home/travis/build/freeCodeCamp/freeCodeCamp/tools/scripts/ci/ensure-guide-page-naming.js:33:10)
    at EventEmitter.readdirp.on.file (/home/travis/build/freeCodeCamp/freeCodeCamp/tools/scripts/ci/ensure-guide-page-naming.js:51:5)
    at EventEmitter.emit (/home/travis/build/freeCodeCamp/freeCodeCamp/node_modules/eventemitter3/index.js:116:35)
    at filter (/home/travis/build/freeCodeCamp/freeCodeCamp/node_modules/readdirp-walk/index.js:54:15)
    at Object.options.filterIter (/home/travis/build/freeCodeCamp/freeCodeCamp/node_modules/walk-filtered/index.js:48:61)
    at /home/travis/build/freeCodeCamp/freeCodeCamp/node_modules/walk-filtered/index.js:22:35
    at /home/travis/build/freeCodeCamp/freeCodeCamp/node_modules/graceful-fs/polyfills.js:287:18
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! @freecodecamp/freecodecamp@0.0.1 test:guide-directories: `node ./tools/scripts/ci/ensure-guide-page-naming.js`
npm ERR! Exit status 1
</code>

**Comment by RandellDawson** [comment]
Hi @MFry,

As there has been no response from your end for a while, I am closing this PR.

Feel free to request this PR to be reopened, if you still wish to make the changes you originally added.  Also, remember to update your fork, so you have the latest version of master in case it has changed significantly.

Happy Coding!

**Pull request closed without merging**
