### PR TITLE
Add test cases for Bonfire: Where art thou

### LINKED ISSUE #2793: Need more assertion examples
Challenge http://www.freecodecamp.com/challenges/bonfire-where-art-thou has an issue. Please describe how to reproduce it, and include links to screenshots if possible.

There are not enough assertion examples for someone to understand what they're supposed to do.

### PR DESCRIPTION
**Pull request by abhisekp**
Added further test case to check for adhering to the instructions in bonfire properly.

close #2793

### CODE REVIEW

**Comment by abhisekp** [comment]
Campers are solving the Bonfire: Where art thou in a wrong way due to lack of good test cases. You can google "Bonfire: Where art thou solutions" to check that the solutions made by different people, pass the tests even if they don't adhere to the instructions completely.
Please update the test cases. And check [https://gist.github.com/abhisekp/7af3c084978f99cf824e](https://gist.github.com/abhisekp/7af3c084978f99cf824e)

**Comment by benmcmahon100** [comment]
I can't see any issue with those solutions and this has never come up as a problem before. I'm going to close this for now but if you want to create some test case that you think are correct and submit them in a pr we can review them for use!

**Comment by benmcmahon100** [comment]
It may also be more prudent just to clarify the instructions

**Comment by abhisekp** [comment]
I asked you to check this page https://gist.github.com/abhisekp/7af3c084978f99cf824e for the issue.

for the test case,

```js
where([{ 'a': 5 }, { 'a': 5 }, { 'a': 5, 'b': 10 }], { 'a': 5, 'b': 10 });
```

should output `[ { a: 5, b: 10 } ] `

But the popular solutions such as in here http://wulkan.me/bonfire-where-art-thou/ give output as
 `[ { a: 5 }, { a: 5 }, { a: 5, b: 10 } ] ` which do not completely abide by the instructions.

The instructions asks to 
> returns an array of all objects that have equivalent property values (second argument).

The output `{ a: 5 }, { a: 5 }` doesn't seem to be equivalent to `{ a: 5, b: 10 }` but `{a : 5, b: 10, c: 15}` can be said equivalent.

And the solutions in https://gist.github.com/abhisekp/7af3c084978f99cf824e use the `Object.prototype.hasOwnProperty` method.

Please consider these test cases as genuine instead of updating the instructions; for making the campers learn about the use case of `Object.prototype.hasOwnProperty` method properly.

**Comment by benmcmahon100** [comment]
I did check the link and it provided no information as to how the code returned something undesirable. The point of the bonfires is not to "teach" any method's of doing things it's merely a test of solving an issue via an algorithm. So the face that the use of Object.prototype.hasOwnProperty is not correct doesn't effect much. Right now we are trying to do issues that are easy or important and this will require testing or consulting with the bonfires creator as to the correct way to precede with this and @terakilobyte is away at the moment so this will most likely be left on the back burner for now

**Comment by abhisekp** [comment]
I looked at the solution of this bonfire in @terakilobyte profile and he solves it in the same way others have solved it popularly in general.

**Comment by benmcmahon100** [comment]
Yeah and his solution would have been used a lot as a template.

**Comment by abhisekp** [comment]
@benmcmahon100 could you please assign @terakilobyte on this issue so that he takes a look when he is back?

**Comment by abhisekp** [comment]
Thanks @benmcmahon100

**Comment by abhisekp** [comment]
@benmcmahon100 I guess the description needs to be updated from
> Make a function that looks through an array (first argument) and returns an array of all objects that have equivalent **property values** (second argument).

to this
> Make a function that looks through an array (first argument) and returns an array of all objects that have equivalent **property and value pair** (**in** second argument).

for better clarrification.

**Comment by abhisekp** [comment]
@benmcmahon100 @BerkeleyTrue The bonfire **where art thou** is more advanced and needs to be moved to some advanced sections.

**Comment by ArielLeslie** [comment]
The new text has a confusing grammatical error.  
>objects that have equivalent property and value pair 

could mean either "**a**(single) equivalent property and value pair" OR  "(all) equivalent property and value pair**s**"
It should be the latter.

**Pull request merged**
