### PR TITLE
updated to use alternate to openweathermap api

### LINKED ISSUE #9145: Show the Local Weather - getCurrentPosition not working over http
#### Challenge Name
Show the Local Weather

https://www.freecodecamp.com/challenges/show-the-local-weather

#### Issue Description

getCurrentPosition does not work over http. I think that changing the url to codepen.io in that particular challenge would help others campers not thinking their code isn't correct.

#### Browser Information

* Browser Name, Version: Chrome 51.0.2704.84 m
* Operating System: Windows 10
* Mobile, Desktop, or Tablet: Desktop

#### Your Code

```js
// If relevant, paste all of your challenge code in here

```

#### Screenshot

image

### PR DESCRIPTION
**Pull request by edm00se**
#### Pre-Submission Checklist

- [x] Your pull request targets the `staging` branch of FreeCodeCamp.
- [x] Branch starts with either `fix/`, `feature/`, or `translate/` (e.g. `fix/signin-issue`)
- [x] You have only one commit (if not, [squash](http://forum.freecodecamp.com/t/how-to-squash-multiple-commits-into-one-with-git/13231) them into one commit).
- [x] All new and existing tests pass the command `npm run test-challenges`. Use `git commit --amend` to amend any fixes.
#### Type of Change

- [x] Small bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds new functionality)
- [ ] Breaking change (fix or feature that would change existing functionality)
- [ ] Add new translation (feature adding new translations)

It's really just a documentation change.
#### Checklist:

- [x] Tested changes locally.
- [x] Closes currently open issue: **I believe** Closes #9145
#### Description

The Open Weather Map API was not serving over HTTPS, leading to mixed content issues, since geolocation requires HTTPS. Forecast.io's API is also free, requires sign up, but up to 1k hits per day w/ no charge or card on file.

I'm (unsurprisingly) not the first person to notice this. Seems to intersect w/ #7853 and #9145, the latter I believe it closes, at least accounts for it from the documentation side of things (as the currently recommended open weather map API leads to a funny experience, at least for Chrome users).

### CODE REVIEW

**Comment by edm00se** [comment]
This is a re-submitted version of PR #10334, which I had started prior to reading the contribution guide (and wound up w/ a branch of `patch-1`, thanks to GitHub's in browser editing, that is now corrected to use `fix/` per docs).

**Comment by erictleung** [comment]
@edm00se thanks for the PR! Sorry for the delayed QA. Looks like `forecast.io` is being rebranded as `https://darksky.net/`. Can you verify that the API still works as expected? https://darksky.net/dev/ Thanks!

**Comment by edm00se** [comment]
Good catch, I hadn't seen the change from forecast.io to darksky.net (as I hadn't checked it since the last time I dealt with it). In any case, I've updated my branch to change the references in name and point to the new docs page for the api.

As far as the changes, it looks to basically be a rebrand only, as the terms still provide for a thousand free calls a day without charge.

**Review by ghost — COMMENTED** [review]
#### LGTM 👍

@edm00se, could you [squash](http://forum.freecodecamp.com/t/how-to-squash-multiple-commits-into-one-with-git/13231) your commits?

**Comment by edm00se** [comment]
Aha, I knew I forgot something. I'll take care of it.

**Comment by edm00se** [comment]
Done. Thanks for the link @atjonathan.

**Comment by atjonathan** [comment]
@edm00se, no problem! Thanks for contributing 🎉

**Comment by smiller171** [comment]
I believe the forcast.io API has stopped working due to CORS changes since this PR was merged, and it hasn't made it to Master yet. May I suggest giving FCC users an API proxy instead? I put one up at `https://weather.millergeek.xyz/` that sits in front of the openweathermap API.

**Comment by edm00se** [comment]
Considering that this PR was changed to use the Dark Sky API (rebranded from forecast.io), I can confirm it works as expected on codepen.

https://codepen.io/edm00se/pen/pbXypE

**Comment by smiller171** [comment]
Thanks for that @edm00se The people I saw complaining about it probably hadn't figured out JSONP

**Comment by davidtaylorjr** [comment]
I'm using the DarkSky API with no issues as well. Is the actual challenge going to be updated?

**Comment by edm00se** [comment]
@davidtaylorjr This PR was merged on [11 October 2016](https://github.com/FreeCodeCamp/FreeCodeCamp/commit/00ca76971f8ad4d96cfaaebfd58ea07498171dbe).

**Comment by atjonathan** [comment]
@davidtaylorjr, as @edm00se said, this PR was merged to staging. We will hopefully be merging staging soon to master (production) alongside our react refactor and curriculum updates. Sorry for the wait!

**Comment by davidtaylorjr** [comment]
@atjonathan awesome. I had to find it on my own. This definitely would have saved a lot of time but it was good problem solving experience.

**Comment by thoragio** [comment]
FYI, I can confirm that the wunderground.com API is still working fine. My CodePen for it is [here](https://codepen.io/thoragio/pen/BzdNKv).

**Pull request merged**
