### PR TITLE
fix(learn): `isSorted` returning true on empty arrays which passes the test

### LINKED ISSUE #40163: Data Structures: Implement Heap Sort with a Min Heap (Passing)
Hey there,

Here is what the challenge description says regarding the sort method.
"The sort method should return an array of all the elements in the min heap sorted from smallest to largest."

I am literally returning an empty array and the challenge keeps on passing.

[Data Structures: Implement Heap Sort with a Min Heap](https://www.freecodecamp.org/learn/coding-interview-prep/data-structures/implement-heap-sort-with-a-min-heap)

* Browser Name: Chrome
* Browser Version: Version 86.0.4240.111 (Official Build) (64-bit)
* Operating System: Windows 10 Home

ezgif com-gif-maker

### PR DESCRIPTION
**Pull request by farhankk360**
Checklist:

- [x] I have read [freeCodeCamp's contribution guidelines](https://contribute.freecodecamp.org).
- [x] My pull request has a descriptive title (not a vague title like `Update index.md`)
- [x] My pull request targets the `master` branch of freeCodeCamp.
- [x] All the files I changed are in the same world language, for example: only English changes, or only Chinese changes, etc.

Closes #40163

Added extra checks to ensure this #40163

### CODE REVIEW

**Comment by RandellDawson** [comment]
@KartikSoneji I believe this is one of the challenges you modified 3 months.  Any thoughts about the issue and this PR?

**Comment by nhcarrigan** [comment]
Is modifying the seed code the right approach here? Or should the related test be adjusted to strengthen it instead?

**Comment by KartikSoneji** [comment]
Hi @RandellDawson , @nhcarrigan 

@nhcarrigan is right, the `isSorted` method should not be modified in this case.
It violates the principle of least surprise: An array of length 0 (or 1) **is** considered sorted by default.

https://github.com/freeCodeCamp/freeCodeCamp/blob/b82c6fd0301e9f86f58f0b2f211eec4070e134c2/curriculum/challenges/english/10-coding-interview-prep/data-structures/implement-heap-sort-with-a-min-heap.md#L44-L45

Besides, hardcoding a sorted array (`[0, 1, 2]`) will also pass the test.

I think the tests need to be improved, something like this should be good.
(This might be a good time to replace all the single-line test code with YAML multiline strings (`|+`))
```diff
diff --git a/curriculum/challenges/english/10-coding-interview-prep/data-structures/implement-heap-sort-with-a-min-heap.md b/curriculum/challenges/english/10-coding-interview-prep/data-structures/implement-heap-sort-with-a-min-heap.md
index 656caba3d5..998813896a 100644
--- a/curriculum/challenges/english/10-coding-interview-prep/data-structures/implement-heap-sort-with-a-min-heap.md
+++ b/curriculum/challenges/english/10-coding-interview-prep/data-structures/implement-heap-sort-with-a-min-heap.md
@@ -30,7 +30,24 @@ tests:
   - text: MinHeap should have a method called sort.
     testString: assert((function() { var test = false; if (typeof MinHeap !== 'undefined') { test = new MinHeap() } else { return false; }; return (typeof test.sort == 'function')})());
   - text: The sort method should return an array containing all items added to the min heap in sorted order.
-    testString: assert((function() { var test = false; if (typeof MinHeap !== 'undefined') { test = new MinHeap() } else { return false; }; test.insert(3); test.insert(12); test.insert(5); test.insert(10); test.insert(1); test.insert(27); test.insert(42); test.insert(57); test.insert(5); var result = test.sort(); return (isSorted(result)); })());
+    testString: |+
+      assert((() => {
+        if(typeof MinHeap === 'undefined')
+          return false;
+
+        let heap = new MinHeap();
+
+        let a = createRandomArray(25);
+        for(let i of a)
+          heap.insert(i);
+
+        let result = heap.sort();
+        a.sort((a, b) => a - b);
+        for(let i = 0; i < a.length; i++)
+          if(a[i] !== result[i])
+            return false;
+        return true;
+      })());

 
 </section>
@@ -48,11 +65,15 @@ function isSorted(a){
   return true;
 }
 // Generate a randomly filled array
-var array = new Array();
-(function createArray(size = 5) {
-  array.push(+(Math.random() * 100).toFixed(0));
-  return size > 1 ? createArray(size - 1) : undefined;
-})(25);
+function createRandomArray(size = 5){
+  let a = new Array(size);
+  for(let i = 0; i < size; i++)
+    a[i] = Math.floor(Math.random() * 100);
+  
+  return a;
+}
+let array = createRandomArray(25);
+
 var MinHeap = function() {
   // Only change code below this line
```

**Comment by farhankk360** [comment]
@nhcarrigan Agreed.
@KartikSoneji That is exactly what I am playing around with, Thanks for the multiline tip.

**Comment by farhankk360** [comment]
Instead of the loop, I tried to use `assert.deepEqual` to compare the arrays. But it's not working.

**Comment by KartikSoneji** [comment]
@farhankk360 
`assert.deepEquals` is for objects (`{a: 0, b: 1}`), use `assert.arrayEquals` to compare two arrays.

---
While this issue was simple enough to resolve, please note that just saying something is "not working" is not very helpful.
Try to include as much information as possible.
Some good questions to ask are:
- What was the issue?
- Did you get an error message?
- What did you try?
- Did an alternative solution work?
- What do you think might be causing the issue?

More information will allow others to help you debug and fix the issue faster.

**Review by moT01 — APPROVED** [review]
I think I'm fine with these changes - it looks like it fixes the issue. LGTM 🎉

**Review by naomi-lgbt — APPROVED** [review]
LGTM~! 🥳 Tested locally, the code provided in the linked issue no longer erroneously passes the test. Hard coding a sorted array also does not pass.

Congratulations on your first pull request to this project! We look forward to future contributions!

**Comment by farhankk360** [comment]
@KartikSoneji Thanks for the help, @nhcarrigan @moT01 @RandellDawson Thank you, guys.
Sure will definitely keep an eye out for future contribution opportunities.

**Pull request merged**
