### PR TITLE
[ImgBot] Optimize images

### PR DESCRIPTION
**Pull request by MichaelDeBoey**
## Beep boop. Your images are optimized!

Your image file size has been reduced by **26%** 🎉

<details>
<summary>
Details
</summary>

| File | Before | After | Percent reduction |
|:--|:--|:--|:--|
| /docs/images/devops/travis-build.png | 65.11kb | 46.87kb | 28.02% |
| /api-server/public/images/freeCodeCamp-puck.svg | 2.03kb | 2.03kb | 0.05% |
| /client/src/assets/images/freeCodeCamp-404.svg | 3.66kb | 3.66kb | 0.03% |
| | | | |
| **Total :** | **70.80kb** | **52.55kb** | **25.77%** |
</details>

---

[📝docs](https://imgbot.net/docs) | [:octocat: repo](https://github.com/dabutvin/ImgBot) | [🙋issues](https://github.com/dabutvin/ImgBot/issues) | [🏅swag](https://goo.gl/forms/1GX7wlhGEX8nkhGO2) | [🏪marketplace](https://github.com/marketplace/imgbot)

### CODE REVIEW

**Comment by MichaelDeBoey** [comment]
If you want, you can install https://imgbot.net in this repo (or in the full organization).
It will automatically send PRs for image optimization 🙂

**Comment by ojeytonwilliams** [comment]
Hey @MichaelDeBoey the travis-build change looks good, but the other two just seem to be noise. Is it possible to set a cut-off % below which it doesn't create a PR?

**Comment by MichaelDeBoey** [comment]
@ojeytonwilliams This is not my bot, I just like it and thought it would be something helpful to use.

From looking into the [docs](https://imgbot.net/docs), it seems that it's possible to [ignore files](https://imgbot.net/docs/#ignoring-files), but it's not possible to set a threshold.

**Comment by ojeytonwilliams** [comment]
@MichaelDeBoey sorry, didn't mean to imply it was yours!  I was just hoping I'd missed that feature somewhere in the docs. Guess not, though.

@raisedadead this does look promising.

**Review by raisedadead — APPROVED** [review]

**Comment by raisedadead** [comment]
I will look into getting this integrated, however we do not have many image changes going on in this repository.

**Comment by MichaelDeBoey** [comment]
It's handy for each image you have, so that's why I wanted to suggest it 🙂

**Comment by raisedadead** [comment]
Yup, I do use it on my personal side projects. It's a nifty tool however, I do not see it to be a good fit on this project. Thanks a lot for your suggestions.

**Pull request merged**
