### PR TITLE
refactor(client): Refactor menu to use refs

### LINKED ISSUE #37025: Refactor menu to use refs
As discussed in https://github.com/freeCodeCamp/freeCodeCamp/pull/36956#pullrequestreview-296784289 the menu uses a mixture of ids and refs to figure out if a click should close the menu or not.

This issue is just a reminder that we were considering refactoring `handleClickOutside` as follows:

```js
  handleClickOutside(event) {
    if (
      this.state.displayMenu &&
      this.menuButtonRef.current &&
      !this.menuButtonRef.current.contains(event.target) &&
      this.searchBarRef.current &&
      !this.searchBarRef.current.contains(event.target)
    ) {
      this.toggleDisplayMenu();
    }
  }
```

### PR DESCRIPTION
**Pull request by ismaelgt**
- [x] I have read [freeCodeCamp's contribution guidelines](https://github.com/freeCodeCamp/freeCodeCamp/blob/master/CONTRIBUTING.md).
- [x] My pull request has a descriptive title (not a vague title like `Update index.md`)
- [x] My pull request targets the `master` branch of freeCodeCamp.
- [x] None of my changes are plagiarized from another source without proper attribution.
- [x] All the files I changed are in the same world language (for example: only English changes, or only Chinese changes, etc.)
- [x] My changes do not use shortened URLs or affiliate links.

Closes #37025

### CODE REVIEW

**Comment by ojeytonwilliams** [comment]
Hey @ismaelgt, I rather liked your idea of having a universal nav ref, as it simplifies the logic and provides a nicer UX.  At least I prefer it.  If you're okay with that, please float that idea in the issue since it would no longer be a pure refactor.

**Comment by ismaelgt** [comment]
@ojeytonwilliams I started implementing the UniversalNav ref solution and then I realised that it doesn't work exactly the same. For example, clicking on some navigation items will not close the menu. That's why I ended up using the suggested approach with multiple references.

**Comment by ojeytonwilliams** [comment]
I see, the when the links don't go anywhere nothing gets unmounted.  Thanks for clarifying.  Multiple refs it is, then!

**Comment by ojeytonwilliams** [comment]
Also, it would be great if we could do away with `forwardRef`, if you have the time.  Just passing them as props simplifies things somewhat.

**Comment by ismaelgt** [comment]
Done. I used `forwardRef` initially for consistency with the current codebase. The main benefit is that you can transparently pass a `ref` down. Without `forwardRef` you need to give the prop a different name. But I agree that it simplifies things.

**Review by ojeytonwilliams — APPROVED** [review]
Thanks, @ismaelgt, this is exactly what I had in mind.

@ahmadabdolsaheb could you give this a quick look?

**Comment by ahmadabdolsaheb** [comment]
@ismaelgt Thanks for the pull request.

**Pull request merged**
