### PR TITLE
Added solution to D3 use dynamic scales challenge

### PR DESCRIPTION
**Pull request by thecodingaviator**
- [x] I have read [freeCodeCamp's contribution guidelines](https://github.com/freeCodeCamp/freeCodeCamp/blob/master/CONTRIBUTING.md).
- [x] My pull request has a descriptive title (not a vague title like `Update index.md`)
- [x] My pull request targets the `master` branch of freeCodeCamp.
- [x] None of my changes are plagiarized from another source without proper attribution.
- [x] My article does not contain shortened URLs or affiliate links.

If your pull request closes a GitHub issue, replace the XXXXX below with the issue number.

Closes #XXXXX

### CODE REVIEW

**Comment by RandellDawson** [comment]
@thecodingaviator The solution passes the tests.  The solution would look much better with 2 space indentation as well as the challenge seed code (which is beyond the scope of this PR).  Would you mind reformatting the solution for the article.  I will create a separate PR to indent all of these D3 challengess' seed code.

**Comment by thecodingaviator** [comment]
@RandellDawson how does it look now?

**Review by moT01 — APPROVED** [review]
LGTM 🎉

**Comment by RandellDawson** [comment]
@moT01 Please don't merge yet.  I am checking something.

**Comment by RandellDawson** [comment]
@thecodingaviator If the goal is to have the right brackets line up, then you will need to make a change.  See below how it currently shows locally:
image

Changing lines 38 thru 47 to the following:
```
      [ 34,   78 ],
      [ 109, 280 ],
      [ 310, 120 ],
      [ 79,  411 ],
      [ 420, 220 ],
      [ 233, 145 ],
      [ 333,  96 ],
      [ 222, 333 ],
      [ 78,  320 ],
      [ 21,  123 ]
```
will render it like:
image

**Comment by thecodingaviator** [comment]
I’ll  make the change on both PRs tomorrow.

**Comment by RandellDawson** [comment]
I can make them on your behalf if you are ok with that.

**Comment by thecodingaviator** [comment]
Please do, I’m fine with that

**Review by RandellDawson — APPROVED** [review]
@thecodingaviator I think this looks good now.  Thank you.

**Pull request merged**
