### PR TITLE
feat(Profile): Reactify profile page

### LINKED ISSUE #16270: MY PROFILE: Previously Completed Challenges showing as NA
#### Challenge Name

My Profile -> Show me my public profile

#### Issue Description

Some previously completed challenged are not loading correctly.
They are listed in the profile as 'NA'
Screenshot is below.

#### Browser Information

* Browser Name, Version:  
* Operating System: FireFox 57.0 (64-bit)  and Chrome Version 63.0.3239.84 (Official Build) (64-bit)
* Mobile, Desktop, or Tablet: Laptop Windows 10 Professional 64-bit 

#### Your Code

```js



```
#### Screenshot

image

### LINKED ISSUE #16283: Public Profile - Social Media Buttons look and behave differently
#### Challenge Name
https://beta.freecodecamp.org/<username>
Privacy Settings must be turned off and a social media account linked to verify

GitHub Button: By Default is Green instead of white and turns a different shade of light grey on hover
Twitter Button: By Default is White and turns a different shade of dark green (not the FCC green) on hover
LinkedIn: unknown since there is an issue in an inability to remove social accounts, due to privacy not linking my linkedin. Please verify

For UX consistency, the buttons should appear and behave the same.

#### Browser Information

* Browser Name, Version:  
* Operating System: FireFox 57.0 (64-bit)  and Chrome Version 63.0.3239.84 (Official Build) (64-bit)
* Mobile, Desktop, or Tablet: Laptop Windows 10 Professional 64-bit

#### Your Code

```js



```
#### Screenshot

image

image

image

### LINKED ISSUE #16598: Report user button
As a user, if I'm authenticated and viewing someone else's profile, I should be able to report them by clicking a "report user profile" button.

### LINKED ISSUE #16661: Completed Beta Certification (Javascript Algorithms and Data Structures), but Not Seeing Certificate
#### Claim Your JavaScript Algorithms and Data Structures Certificate
https://beta.freecodecamp.org/en/challenges/claim-your-javascript-algorithms-and-data-structures-certificate/claim-your-javascript-algorithms-and-data-structures-certificate

#### Issue Description
I'm able to go through all of the steps for claiming my certificate, and then FCC tells me it has been added to my profile page. 

But, in looking at my profile page, I'm not able to find the certificate. It might be on my end, but there seems to be no place that it's listed.

Potential issue: I linked my github account after claiming the certificate for the first time. 

#### Browser Information
Chrome: 64.0.3282.140

* Browser Name, Version: 
* Operating System:  Windows 10.0.14393
* Mobile, Desktop, or Tablet: Laptop

#### Your Code

```js



```
#### Screenshot

image

### LINKED ISSUE #16746: [BETA] The navbar "Map" link does not work from the User Profile / Settings page
#### Issue Description
1. Go to https://beta.freecodecamp.org/en/settings
1. Click on the "Map" link in the navbar.
1. Nothing happens. The href attribute is set to #.

#### Screenshot

image

### PR DESCRIPTION
**Pull request by Bouncey**
The profile page, but in react.

closes #16270
closes #16283
closes #16598
closes #16661
closes #16746

### CODE REVIEW

**Comment by QuincyLarson** [comment]
@Bouncey This looks great.

I noticed there's an extra horizontal rule at the bottom of the page.

profile___freecodecamp_and_rm_-rf_node_modules____npm_install____node_seed____gulp_ _node_ _gulp_term_program_apple_terminal_ _159x45

I also noticed that when I'm on either the Settings or Profile pages, the "Map" button in the navbar no longer works.

**Review by QuincyLarson — CHANGES_REQUESTED** [review]
@Bouncey This is off to a great start.

I noticed there's an extra horizontal rule at the bottom of the page.

profile___freecodecamp_and_rm_-rf_node_modules____npm_install____node_seed____gulp_ _node_ _gulp_term_program_apple_terminal_ _159x45

I also noticed that when I'm on either the Settings or Profile pages, the "Map" button in the navbar no longer works.

**Comment by Bouncey** [comment]
Have you pulled down the correct version?

**Note:** This is is on a fresh branch **feat/profile**

Here is what I have

Entire page screen grab

GIF showing the Map button working correctly on profile and settings page

**Comment by QuincyLarson** [comment]
@Bouncey Thank you for fixing the bug I discovered regarding user records that contained solutions for challenges that are no longer existed in the curriculum. 

I just ran everything and it works great!

**Pull request merged**
