### PR TITLE
Add more falsy values for "Bonfire: Falsy Bouncer"

### LINKED ISSUE #3121: Bonfire: Falsey Bouncer, tests do not catch all null/NaN
The Bonfire: Falsey Bouncer does not catch all null/NaN.
The code below leaves a null at the end that gets past the tests (if a NaN is added in falsey it catches it).

```javascript
function bouncer(arr) {

  var falsey = [false, null, 0, '', undefined];
  
  for (i=0; i < arr.length; i++) {

    for (j=0; j < falsey.length; j++) {
      
      if (arr[i] == falsey[j] || (arr[i] !== arr[i]) ) {
        
        arr.splice(i, 1);
        
      }
      
    }
    
  }
  
  return arr;
  
}

bouncer([7, 'ate', '', 9, false, null, 0, "", undefined, 0 / "word"]);
```
Can anyone else confirm this?

### PR DESCRIPTION
**Pull request by abhisekp**
Include more falsy values to the existing test case

close #3121

### CODE REVIEW

**Comment by ahstro** [comment]
Not quite sure why there are merge conflicts, but you'll need to fix them before a merge, because I'm too lazy to manually merge ;)

**Comment by abhisekp** [comment]
@ahstro It's my duty to resolve those conflicts. Thanks for notifying me. I asked for the PR, 2 days back.

**Comment by ahstro** [comment]
Good luck @abhisekp :) No biggie if you don't figure it out, I've slept now so I'm more than ready to learn how to manually merge, but give it a shot yourself first.

**Comment by abhisekp** [comment]
@ahstro I don't understand the difference between these lines apart from the last line I changed. LOLz :smile: 
> git has gone mad! :-1: 

```js
<<<<<<< HEAD
        "assert.deepEqual(bouncer([7, 'ate', '', false, 9]), [7, 'ate', 9], 'should remove falsey values');",
        "assert.deepEqual(bouncer(['a', 'b', 'c']), ['a', 'b', 'c'], 'should return full array if no falsey elements');",
        "assert.deepEqual(bouncer([false, null, 0, NaN, undefined, '']), [], 'should return empty array if all elements are falsey');"
=======
        "assert.deepEqual(bouncer([7, 'ate', '', false, 9]), [7, 'ate', 9], 'should remove falsy values');",
        "assert.deepEqual(bouncer(['a', 'b', 'c']), ['a', 'b', 'c'], 'should return full array if no falsy elements');",
        "assert.deepEqual(bouncer([false, null, 0]), [], 'should return empty array if all elements are falsy');"
>>>>>>> upstream/staging
```

**Comment by abhisekp** [comment]
@ahstro Good to go. :+1:

**Comment by ahstro** [comment]
It's weird how we train our eyes to spot minor differences in what seems likejus strings of random characters to non-programmers, but finding a grammatical error is exceedingly hard :sweat_smile: 

The code seems to work fine in both Firefox and Chromium, I'll go ahead and merge.

**Pull request merged**
