### PR TITLE
fix(curriculum): Add solutions to CSS challenges

### PR DESCRIPTION
**Pull request by Manish-Giri**
- [x] I have read [freeCodeCamp's contribution guidelines](https://github.com/freeCodeCamp/freeCodeCamp/blob/master/CONTRIBUTING.md).
- [x] My pull request has a descriptive title (not a vague title like `Update index.md`)
- [x] My pull request targets the `master` branch of freeCodeCamp.
- [x] None of my changes are plagiarized from another source without proper attribution.
- [x] All the files I changed are in the same world language (for example: only English changes, or only Chinese changes, etc.)
- [x] My changes do not use shortened URLs or affiliate links.

For #35751

### CODE REVIEW

**Review by RandellDawson — APPROVED** [review]
LGTM, but wait until PR #35849 has been reviewed/merged before merging this one.  I have added the `blocked` label until PR #35849 has been merged.

**Comment by RandellDawson** [comment]
PR #35849 has been merged now, so once it has been reviewed/approved by another mod, it can be merged.

**Review by thecodingaviator — APPROVED** [review]
LGTM

**Comment by thecodingaviator** [comment]
Thank you for your contribution to the page! 👍
We're happy to accept these changes, and look forward to future contributions. 📝

**Pull request merged**
