### PR TITLE
fix(client): outline and padding in the footer

### LINKED ISSUE #49605: Footer tending guides' links outline is touching the text
**Describe the bug**
While navigating the footer using the keyboard, the outline is touching the text, which doesn't look visually clean.

[rec-tab (12).webm](https://user-images.githubusercontent.com/88248797/223161344-0a5b3a5e-a8cc-4b4c-8fa0-2387fcc41ec0.webm)

**To Reproduce**
1. Go to https://www.freecodecamp.org/
2. Click on <kbd>tab</kbd> until you reach the footer 
3. See outline

**Expected behavior**
the outline shouldn't touch the text

**Screenshots**
image

**Additional context**
the outline is touching the text because of this property

```css
 .footer-col a {
    padding: 5px 0;
}
```

we can remove the `0` or add offset to the outline in the footer if it's a link. yes it's affect the tax link

image

### PR DESCRIPTION
**Pull request by Sboonny**
Checklist:

- [x] I have read and followed the [contribution guidelines](https://contribute.freecodecamp.org).
- [x] I have read and followed the [how to open a pull request guide](https://contribute.freecodecamp.org/#/how-to-open-a-pull-request).
- [x] My pull request targets the `main` branch of freeCodeCamp.
- [x] I have tested these changes either locally on my machine, or GitPod.

Ref freeCodeCamp/news#622

This doesn't close the issue, because we need to apply the same changes to other platforms.

### CODE REVIEW

**Comment by raisedadead** [comment]
> feat(client): fix outline and padding in the footer 

It's either a new feature (new as in never before seen in any context) or a fix to an existing issue. It can never be both.

Learn more: https://www.conventionalcommits.org/en/v1.0.0/#summary

**Comment by raisedadead** [comment]
> Reading is hard

Respectfully, contributing to the repo is serious business. We should hold ourselves to the same standards as we expect any contributor to. 🙂

**Comment by bbsmooth** [comment]
Would there be any objection to wrapping each of the trending guide links in a `span`? That would allow the link to be inline and then only the link text would be an active target.

**Comment by Sboonny** [comment]
that is a good solution, I have tried CSS, and it always didn't look correct. This makes sense 👍

**Review by Sembauke — APPROVED** [review]

**Review by moT01 — COMMENTED** [review]
One thing I don't really like is that there always seems to be some titles that don't fit and have to wrap:
<details>
<summary>images</summary>
At a wide width, several article titles are wrapped:


On production, all the titles have room to fit and don't wrap at any width:


At a certain width, there's five columns trying to fit:

</details>

Things just feel a little cluttered in spots. I would try and give a little more room for the titles so they don't wrap so often - and possibly add a little more padding so things don't feel so squished together. I'm not sure, maybe we want it more condensed - my opinion.

**Comment by Sboonny** [comment]
the set in stone width of `1170px` and now `1300px` was a blocker for this, I didn't add much because freeCodeCamp always take `1170px` of width, but I don't know how to solve these without using more space and not using position absolute.

**Review by moT01 — APPROVED** [review]
I'm good with this 👍

**Pull request merged**
