### PR TITLE
Track challenge submissions count

### LINKED ISSUE #14881: Track challenge submissions count
Modify this bit here to add a count of number of times use has submitted this challenge:

https://github.com/freeCodeCamp/freeCodeCamp/blob/staging/server/boot/challenge.js#L32-L36

Something like this:
```js
 finalChallenge = {
    ...completedChallenge,
    completedDate: oldChallenge.completedDate,
    lastUpdated: completedChallenge.completedDate,
    numOfAttempts: oldChallenge.numOfAttempts + 1
 };
```

Happy Coding!

### PR DESCRIPTION
**Pull request by dakshshah96**
#### Pre-Submission Checklist

- [x] Your pull request targets the `staging` branch of freeCodeCamp.
- [x] Branch starts with either `fix/`, `feature/`, or `translate/` (e.g. `fix/signin-issue`)
- [x] You have only one commit (if not, [squash](http://forum.freecodecamp.com/t/how-to-squash-multiple-commits-into-one-with-git/13231) them into one commit).
- [x] All new and existing tests pass the command `npm test`. Use `git commit --amend` to amend any fixes.

#### Type of Change

- [ ] Small bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds new functionality)
- [ ] Breaking change (fix or feature that would change existing functionality)
- [ ] Add new translation (feature adding new translations)

#### Checklist:

- [x] Tested changes locally.
- [x] Closes currently open issue (replace XXXX with an issue no): Closes #14881 

#### Description

Add a count of number of times user has submitted this challenge.

### CODE REVIEW

**Review by BerkeleyTrue — APPROVED** [review]

**Comment by BerkeleyTrue** [comment]
@dakshshah96 Where you able to verify that the number of submissions actually increases?

**Comment by dakshshah96** [comment]
@BerkeleyTrue Not really sure how to do that. Some help please?

**Comment by BerkeleyTrue** [comment]
@dakshshah96 Submitting a challenge, check the database and see the count on the challenge, submit the same challenge, check the database again to see if the count has increased

**Comment by raisedadead** [comment]
@dakshshah96 can you confirm, if you were able to test as suggested?

**Comment by BerkeleyTrue** [comment]
Closing as stale

**Pull request closed without merging**
