### PR TITLE
Fixed link to bootstrap css

### PR DESCRIPTION
**Pull request by TechnologyClassroom**
#### Pre-Submission Checklist

- [Y ] Your pull request targets the `staging` branch of FreeCodeCamp.
- [Y ] Branch starts with either `fix/`, `feature/`, or `translate/` (e.g. `fix/signin-issue`)
- [Y ] You have only one commit (if not, [squash](http://forum.freecodecamp.com/t/how-to-squash-multiple-commits-into-one-with-git/13231) them into one commit).
- [Y ] All new and existing tests pass the command `npm run test-challenges`. Use `git commit --amend` to amend any fixes.
#### Type of Change

- [Y ] Small bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds new functionality)
- [ ] Breaking change (fix or feature that would change existing functionality)
- [ ] Add new translation (feature adding new translations)
#### Checklist:

- [Y ] Tested changes locally.
- [Y ] Closes currently open issue (replace XXXX with an issue no): Closes #XXXX
#### Description

After trying the example in my own html file, I found that the provided link did not work.  http://getbootstrap.com/dist/css/bootstrap.min.css worked.  Removing // led my browser to http://maxcdn.bootstrapcdn.com/bootstrap/3.3.1/css/bootstrap.min.css which also worked.  I applied the change to all six instances in bootstrap.json which fixes links to bootstrap and font-awesome css files.

### CODE REVIEW

**Comment by erictleung** [comment]
@TechnologyClassroom your browser should have been able to find the correct web resource without the scheme (http or https). [Here's](http://stackoverflow.com/questions/550038/is-it-valid-to-replace-http-with-in-a-script-src-http) a discussion on the topic. What browser are you using? In response to your PR, I don't think this is a necessary change.

**Comment by TechnologyClassroom** [comment]
Firefox 49.0.1 and Chrome 53.0.2785.116 m (64-bit) for Windows 7 Pro apparently are not URI syntax complaint from the RFC.  According to that link they should be.

To test, try to run these html files in your browser.  WithScheme works for me.  WithoutScheme does not.
[HTML.zip](https://github.com/FreeCodeCamp/FreeCodeCamp/files/491438/HTML.zip)

**Comment by erictleung** [comment]
@TechnologyClassroom thanks for the code and browser specs. I was able to reproduce your issue. However, I think the real issue is that when you run your web pages directly in web browsers, it has some restrictions on it. 

Usually, web pages are served by servers and so to really test your web pages, you should serve it on some servers. Here I've set up a server locally (I've used MAMP) to show the code you have it works fine.

screen shot 2016-09-24 at 20 59 05

I've even [copied the code onto CodePen](http://codepen.io/erictleung/pen/YGkjbR/) and it works just fine.

**Comment by TechnologyClassroom** [comment]
I learned something from this pull request.  I will test my code with my local Nginx server in the future.  I had never seen a difference between a local page and a local server.  You showed me RFC 3986 and CodePen.  Thank you, Eric!

**Pull request closed without merging**
