### PR TITLE
Documentation patch to provide a workaround to an issue many people are having while setting up fCC locally without Docker

### PR DESCRIPTION
**Pull request by jsilvao**
- [x] I have read [freeCodeCamp's contribution guidelines](https://github.com/freeCodeCamp/freeCodeCamp/blob/master/CONTRIBUTING.md).
- [x] My pull request has a descriptive title (not a vague title like `Update index.md`)
- [x] My pull request targets the `master` branch of freeCodeCamp.
- [x] None of my changes are plagiarized from another source without proper attribution.
- [x] All the files I changed are in the same world language (for example: only English changes, or only Chinese changes, etc.)
- [x] My changes do not use shortened URLs or affiliate links.

### CODE REVIEW

**Comment by RandellDawson** [comment]
This seems unnecessary to me.  You should instead run `npm run clean-and-develop`.  There should not be a reason to ever execute any of the npm commands outside of the root folder.

**Comment by ojeytonwilliams** [comment]
There was a conversation in Gitter where someone was having problems due to missing `sharp`, but everything worked when they went through the normal troubleshooting steps.  We never did find out what went wrong in the first place.

I think *something* needs to change, though, because people are coming to Gitter fairly regularly with problems setting up the site.

**Comment by jshaolin** [comment]
@RandellDawson what I'm proposing is just a *conditional side note* to the documentation, not a radical change to the setup workflow. Besides, this has proven to be a solid workaround to the issue while the real reason for the issue is found. This could take *some* time, right now there's no conclusive theory as why it happens to some and not to others, even when they follow the instructions to the letter. Do you really want folster frustration for new contributors? Plus, this happened to me also, and I assure you I did **everything** as described, even issuing `npm run clean-and-develop` didn't work.

It's just a sidenote to help people in case it happens to them, what's the big deal?

Like @ojeytonwilliams said, something needs to change. I agree this doesn't address the root of the issue, but it enables others to complete setting up fCC.

**Comment by ojeytonwilliams** [comment]
> Do you really want to folster frustration for new contributors?

No one wants it to be difficult to contribute.  We want it to be as simple and reliable as possible.

> It's just a sidenote to help people in case it happens to them, what's the big deal?

Well, if the instructions don't work when followed perfectly, it's a symptom of a deeper problem.  Perhaps their version of npm or node isn't compatible with fcc and they haven't realised, we just don't know.  Manually deleting a module and reinstalling fixes a symptom, not the root cause.  We have no idea if their local site will behave correctly after this fix.

Personally, I think the installation needs condensing where possible.  Also we should warn people when they seem not to have followed it.  For example, rather than 3 commands to install the Docker version, there should be a single command like `npm run docker-install-run-once` which invokes those commands in order.  Also, if someone forgets to copy `sample.env` to `.env` (which someone reported in Gitter) we should tell them.  i.e. try to make it impossible to not follow the instructions.

**Comment by jshaolin** [comment]
@ojeytonwilliams I agree with everything you said, and I repeat, this doesn't address the real cause of the issue. However, do you want to continue talking in gitter about this issue for weeks/months until the cause is found or the installation get's more condensed/refactored/revised? Or do you prefer people to have a quick fix to apply without having to resort to gitter **for this specific problem**.

**Comment by RandellDawson** [comment]
> Or do you prefer people to have a quick fix to apply without having to resort to gitter for this specific problem.

We don't know your suggested addition will help anyone else, because we don't know the root cause.

**Comment by jshaolin** [comment]
@RandellDawson just because we don't know the root of the issue it doesn't mean it wouldn't help. Do we know the cause of Parkinson's disease? No. Can we help? Yes, a lot, in the meantime we find the cause.

There's people out there wasting hours dealing with this, and from a quick Google search you'll see this aint't new, there's has been others that faced it (and others that will).

Look, I've already dealt with this, so as far as I'm concerned I'm all set up and good to go. I know that what I'm proposing is not a *mainstream contribution* and perhaps not even a contribution at all. I just have come to love fCC and would like others to do so, but don't want them to go away in dissapointment at their very first steps.

With all that said, if you and/or others think this is a waste of time then please say so and I'll close it. No harm done, really.😊

**Comment by RandellDawson** [comment]
>  just because we don't know the root of the issue it doesn't mean it wouldn't help. 

It could be pure coicendence in some other steps you took that actually solved the issue.  You may only think the last steps you took (the ones you wrote about in the extra note in this PR) solved it, but in actuality, some other steps you took did.  My point is we don't want to document everyone's individual "fixes" every time someone has trouble getting setup and then attempts some set of steps which finally "solves" the problem for them.  It would clutter up the documentation.  Instead, we want to understand the true root cause and fix the installation process, so we don't have a collection of "bandaid" notes that may or may not help someone's unique situation.

I say we close this PR and instead create a GitHub issue that can be used to discuss these unique issues users are having in an attempt to collect enough data to conclude on a better approach for getting setup locally across multiple platforms.

**Comment by jshaolin** [comment]
That sounds great to me! Creating issue and closing PR. Cheers!

**Pull request closed without merging**
