### PR TITLE
remove "use strict" from various JavaScript challenges

### PR DESCRIPTION
**Pull request by majestic-owl448**
Checklist:

- [x] I have read [freeCodeCamp's contribution guidelines](https://contribute.freecodecamp.org).
- [x] My pull request has a descriptive title (not a vague title like `Update index.md`)
- [x] My pull request targets the `master` branch of freeCodeCamp.
- [x] All the files I changed are in the same world language, for example: only English changes, or only Chinese changes, etc.

Various challenges have already been updated to remove the "use strict" declaration, as strict mode is on by default, this change goes in that same direction

### CODE REVIEW

**Comment by RandellDawson** [comment]
@ieahleen Would you mind expanding this PR (and modifying the title) to include the other 9 files with "use strict" in the challenge seed code?
- `/curriculum/challenges/english/02-javascript-algorithms-and-data-structures/basic-javascript/local-scope-and-functions.md`
- `/curriculum/challenges/english/02-javascript-algorithms-and-data-structures/es6/compare-scopes-of-the-var-and-let-keywords.md`
- `/curriculum/challenges/english/02-javascript-algorithms-and-data-structures/es6/declare-a-read-only-variable-with-the-const-keyword.md`
- `/curriculum/challenges/english/02-javascript-algorithms-and-data-structures/es6/explore-differences-between-the-var-and-let-keywords.md`
- `/curriculum/challenges/english/02-javascript-algorithms-and-data-structures/es6/mutate-an-array-declared-with-const.md`
- `/curriculum/challenges/english/02-javascript-algorithms-and-data-structures/es6/prevent-object-mutation.md`
- `/curriculum/challenges/english/02-javascript-algorithms-and-data-structures/es6/prevent-object-mutation.md`
- `/curriculum/challenges/english/02-javascript-algorithms-and-data-structures/es6/use-arrow-functions-to-write-concise-anonymous-functions.md`
- `/curriculum/challenges/english/02-javascript-algorithms-and-data-structures/es6/use-destructuring-assignment-with-the-rest-parameter-to-reassign-array-elements.md`

**Review by RandellDawson — CHANGES_REQUESTED** [review]
@ieahleen See my request regarding the other challenge with the "use strict".

**Comment by ieahleen** [comment]
how should I deal with this in the challenge description:
https://github.com/freeCodeCamp/freeCodeCamp/blob/master/curriculum/challenges/english/02-javascript-algorithms-and-data-structures/es6/explore-differences-between-the-var-and-let-keywords.md#L32

**Comment by ieahleen** [comment]
I also just noticed I did not use my own fork, I am really really sorry about that

**Pull request closed without merging**
