### PR TITLE
feat(curriculum): adding node and express challenges to cert

### LINKED ISSUE #559: chore: node and express challenges to frontend cert in main repo
The frontend cert will have a brief section to talk about and practice working with node and express.

Instead of a traditional workshop here, we will use the existing node and express challenges.

https://www.freecodecamp.org/learn/back-end-development-and-apis/#basic-node-and-express

### PR DESCRIPTION
**Pull request by jdwilkin4**
Checklist:

- [x] I have read and followed the [contribution guidelines](https://contribute.freecodecamp.org).
- [x] I have read and followed the [how to open a pull request guide](https://contribute.freecodecamp.org/how-to-open-a-pull-request/).
- [x] My pull request targets the `main` branch of freeCodeCamp.
- [x] I have tested these changes either locally on my machine, or GitPod.

Closes https://github.com/freeCodeCamp/CurriculumExpansion/issues/559

### CODE REVIEW

**Review by moT01 — COMMENTED** [review]
LGTM 🎉

Looks like there's a conflict.

**Comment by ilenia-magoni** [comment]
now there is merge conflict, @moT01 can you fix the test so we don't have to do that?

**Review by moT01 — APPROVED** [review]

**Comment by zairahira** [comment]
I went through the individual sections, they seem good to go.
However, this is how the "Basic Node and Express" section is showing on the main page:

image

**Comment by jdwilkin4** [comment]
@zairahira 

That is because some recent UI changes broken the the design for these challenges.
there is already a PR in the works to fix this

**Review by zairahira — APPROVED** [review]

**Pull request merged**
