### PR TITLE
fix(curriculum) correct "an" to "a"

### PR DESCRIPTION
**Pull request by danielveazey**
- [x] I have read [freeCodeCamp's contribution guidelines](https://github.com/freeCodeCamp/freeCodeCamp/blob/master/CONTRIBUTING.md).
- [x] My pull request has a descriptive title (not a vague title like `Update index.md`)
- [x] My pull request targets the `master` branch of freeCodeCamp.
- [x] None of my changes are plagiarized from another source without proper attribution.
- [x] All the files I changed are in the same world language (for example: only English changes, or only Chinese changes, etc.)
- [x] My changes do not use shortened URLs or affiliate links.

### CODE REVIEW

**Comment by RandellDawson** [comment]
@danielveazey Why did you close the PR?

**Comment by danielveazey** [comment]
I closed the pull request because I am somewhat confused by the process. When I created it, there was a message stating that my pull request was pending two checks. Once I had changed the title, one of the checks passed. The other had not passed, and I was not sure what it needed to pass that second check. So I closed the pull request. Once I understand the process better I will either reopen the pull request or create a new one or, if you think I should take another action, I'll do that. As for the checks that it said needed to be passed, I have not yet figured out exactly what the second check requires.

**Comment by RandellDawson** [comment]
I have reopened the PR, so I can look at the checks.

**Review by RandellDawson — APPROVED** [review]

**Comment by RandellDawson** [comment]
Thank you for your contribution to the page! 👍
We're happy to accept these changes, and look forward to future contributions. 🎉

**Pull request merged**
