### PR TITLE
bug fix / test of Spread Operator javascript challenge / english 

### LINKED ISSUE #35742: Solution passes on current production but fails on beta site for Copy an Array with the Spread Operator challenge
The following code passes all the tests on the current production site, but fails the last test on the current beta site (freecodecamp.rocks) and when tested locally (`npm run test:curriculum`).  I discovered the issue while adding solutions to challenges currently missing a solutions on `master`.  I compared the tests in the archived `curriculum` repo and they appear to be the same tests.

```js
function copyMachine(arr, num) {
  let newArr = [];
  while (num >= 1) {
    // change code below this line
    newArr.push([...arr]);
    // change code above this line
    num--;
  }
  return newArr;
}
```

**Add a Link to the page with the problem:**
https://www.freecodecamp.rocks/learn/javascript-algorithms-and-data-structures/basic-data-structures/copy-an-array-with-the-spread-operator

**Tell us about your browser and operating system:**
* Browser Name: Chrome
* Browser Version: Version 73.0.3683.86 (Official Build) (64-bit)
* Operating System: Windows 10 Home

**If possible, add a screenshot here (you can drag and drop, png, jpg, gif, etc. in this box):**
**See below the failing test on freecodecamp.rocks**
image

**See below the same code passes on production**
****
image

### PR DESCRIPTION
**Pull request by sil3nthill**
- [x] I have read [freeCodeCamp's contribution guidelines](https://github.com/freeCodeCamp/freeCodeCamp/blob/master/CONTRIBUTING.md).
- [x] My pull request has a descriptive title (not a vague title like `Update index.md`)
- [x] My pull request targets the `master` branch of freeCodeCamp.
- [x] None of my changes are plagiarized from another source without proper attribution.
- [x] All the files I changed are in the same world language (for example: only English changes, or only Chinese changes, etc.)
- [x] My changes do not use shortened URLs or affiliate links.

Closes #35742

### CODE REVIEW

**Comment by sil3nthill** [comment]
hello @RandellDawson as we discussed this yesterday , i found out that the test doesnt pass on the beta version because it will test after babel transform , so i changed that to check the user code 
   ` testString: assert.notStrictEqual(code.toString().indexOf('newArr.push([...arr])'), -1, 'The <code>copyMachine</code> function should utilize the <code>spread operator</code> with array <code>arr</code>');`
and now the tests pass on beta with the solution you provided ,( tested locally ), tell me if you need further details . cheers

**Comment by pratipb** [comment]
my comment

**Comment by pratipb** [comment]
first comment

**Comment by pratipb** [comment]
abc

**Comment by pratipb** [comment]
second comment

**Comment by pratipb** [comment]
my comment

**Comment by pratipb** [comment]
12

**Comment by pratipb** [comment]
12

**Comment by pratipb** [comment]
12

**Comment by RandellDawson** [comment]
Your test is too specific.  You need to be able to handle all the various ways in which a user could write their code to accomplish the task.  Also, the `toString` is not necessary as `code` is already a string.  The `push` method not the only method to use the spread syntax.  In fact, you can solve this without using any methods at all.  Plus, what if the user uses white space (see below)?

```
newArr.push( [ ...arr ] );
```

**Comment by sudhanshu-kumar** [comment]
123

**Comment by sil3nthill** [comment]
Yes no need for the toString method , so i am guessing i need to use a regex in this case but i cant see how we can handle all user inputs , the only thing i see here is : having a regex with many cases possible ,or adding another rule to the challenge that the user must do it wih push since the most important part is using the spread operator ? Whad do you think about this

**Comment by sudhanshu-kumar** [comment]
gjhjn

**Comment by sil3nthill** [comment]
i looked into the problem again and as i said cant see a way to cover all the user inputs , he may even declare variables change content of them even declare a function or anything , here the problem will change to create a compiler and i dont think thats what we want , we can give the user the choice between using push or another function , so we can create a regex that control this such as :  
`\.push\s*?=\s*?\(\s*?\[\s*?\.\.\.\s*?\]\s*?)`

**Comment by Ashuanuj** [comment]
Hello World

**Comment by Ashuanuj** [comment]
Hello World

**Comment by Ashuanuj** [comment]
first comment

**Comment by Ashuanuj** [comment]
second comment

**Comment by Ashuanuj** [comment]
third comment

**Comment by Ashuanuj** [comment]
fourth comment

**Comment by Ashuanuj** [comment]
fifthcomment

**Comment by Ashuanuj** [comment]
sixthComment

**Comment by Ashuanuj** [comment]
seventhComment

**Comment by Ashuanuj** [comment]
asdfsdf

**Comment by Ashuanuj** [comment]
asd

**Comment by Ashuanuj** [comment]
sdfsfdsfg

**Comment by Ashuanuj** [comment]
sfsdfddg

**Comment by madurachanna** [comment]
Login to comment!!

**Comment by Ashuanuj** [comment]
first comment

**Comment by Ashuanuj** [comment]
first comment

**Comment by Ashuanuj** [comment]
second comment

**Comment by sil3nthill** [comment]
@RandellDawson  any updated for this PR ? what do you think about my solution above

**Comment by RandellDawson** [comment]
@sil3nthill Still thinking we should not be so specific with the `push` method.  I think you could use a helper function that I have created for other challenges which strips out comments in the code (to prevent someone from just writing a comment like `// ...arr` and passing a test which looks for `...arr`.  Since the user is only supposed to change the one line, we could look for that after the code has been stripped of comments.

To strip the comments, put the following in the challenge file:
````
### After Test
<div id='js-teardown'>

```js
const removeJSComments = str => str.replace(/\/\*[\s\S]*?\*\/|\/\/.*$/gm, '');
```

</div>
````

To figure out where to put it, look at [How to work on coding challenges](https://github.com/freeCodeCamp/freeCodeCamp/blob/master/docs/how-to-work-on-coding-challenges.md) to see where the `After Test` section needs to be.

Then I think the `testString` for the last test could be as simple as:
```
testString: assert(removeJSComments(code).match(/\.\.\.arr/));
```
If you don't mind, go ahead and remove all of the assert message arguments for the other tests in the same PR as they are no longer needed.  The `text` is used in place of the assert message argument value.

**Comment by sil3nthill** [comment]
test1local
test2local
@RandellDawson  i edited the files , and tested locally with different cases ( using push , using concat , declare another variable ... ) and all  the tests passes just fine .
also i removed the second argument from the testString as u wanted since we dont use it anymore

**Comment by sil3nthill** [comment]
@RandellDawson  is it okey as a solution ? if yes i would like to know its getting merged soon ? so i can passe and help with other issues , thank you

**Comment by sil3nthill** [comment]
hello guys , any review or update for this PR ?

**Comment by RandellDawson** [comment]
@sil3nthill You have to be patient.  We have many other PRs which are much older that require our review also.  It can take a while sometimes.  At least two other mods must review/approve before a curriculum PR can be merged.

**Review by ojeytonwilliams — APPROVED** [review]
LGTM :+1: 

@sil3nthill I understand that it can be frustrating to not get PRs merged (I have 11 open myself!).  However, you shouldn't feel like you have to wait for this one to be merged.  If you have other things you want to work on, issues and PRs are always welcome.

**Comment by sil3nthill** [comment]
@ojeytonwilliams  thanks for your approving this , yes i agree with you its a big project and not  a small one so it need more time to treat all those PRs  !

**Review by moT01 — APPROVED** [review]
LGTM! Congratulations on your first contribution to freeCodeCamp @sil3nthill!

**Pull request merged**
