### PR TITLE
feat(guide): Added the `cat` command & external resources.

### PR DESCRIPTION
**Pull request by m-alani**
- [x] I have read [freeCodeCamp's contribution guidelines](https://github.com/freeCodeCamp/freeCodeCamp/blob/master/CONTRIBUTING.md).
- [x] My pull request has a descriptive title (not a vague title like `Update index.md`)
- [x] My pull request targets the `master` branch of freeCodeCamp.
- [x] None of my changes are plagiarized from another source without proper attribution.
- [x] My article does not contain shortened URLs or affiliate links.

If your pull request closes a GitHub issue, replace the XXXXX below with the issue number.

Closes #XXXXX

### CODE REVIEW

**Comment by lynxlynxlynx** [comment]
cat's purpose is conCATenation, not display. You can use grep, sed or practically any filtering program to do the same.

Mentioning pipes is also bad. Using cat with pipes is a famous antipattern, so it shouldn't be promoted! (most tools can read files themselves)

**Comment by m-alani** [comment]
From the `man` page: "_cat - concatenate files and print on the standard output_"

The most common use case that I know of is to give one file as input to display the content on screen. It is also widely used by System Admins (based on my personal experience) along with pipe and redirections.

**Comment by lynxlynxlynx** [comment]
More than 20 years ago a mock award was created for the very same reason:
http://porkmail.org/era/unix/award.html

**Comment by QuincyLarson** [comment]
@m-alani Thanks for your contribution.

@lynxlynxlynx Thanks for sharing that article. I know that `cat` has some other uses, but the main thing me and most developers I've observed use it for is just quickly outputting the contents of a file :)

**Pull request merged**
