### PR TITLE
fix: run comment translation logic on english builds

### PR DESCRIPTION
**Pull request by naomi-lgbt**
Checklist:

- [X] I have read [freeCodeCamp's contribution guidelines](https://contribute.freecodecamp.org).
- [X] My pull request has a descriptive title (not a vague title like `Update index.md`)
- [X] My pull request targets the `main` branch of freeCodeCamp.
- [X] I have tested these changes either locally on my machine, or GitPod.

Closes #XXXXX

This *might* be cheating. But this passes the English challenges through the comment translator - which shouldn't cause any new issues (I hope?) but *will* catch new comments added to seed code that aren't present in the known comment dictionary.

### CODE REVIEW

**Review by ojeytonwilliams — COMMENTED** [review]
Is the idea just to trigger the error when the comment isn't in the dictionary?

That's fine (bit cheaty, but fine).  I would try to make the intention clear, though, since that's not obvious from the code itself.

With that in mind, how about this

```js
// We always try to translate comments (even English ones) to confirm that translations exist.
const translateComments = isAuditedCert(lang, meta.superBlock) && fs.existsSync(getFullPath(lang, filePath));
```

and then flip the ternary.

**Comment by naomi-lgbt** [comment]
> Is the idea just to trigger the error when the comment isn't in the dictionary?

Yes. I had landed a PR that added a comment which wasn't in the dictionary, and broke the i18n build - the hope is to catch the comments before they merge so we can discuss whether adding them is the right approach.

**Comment by ojeytonwilliams** [comment]
Cool, that makes sense.  Does the refactor seem reasonable?

**Comment by raisedadead** [comment]
We are officially on Node.js 18 now. We have changed the merge requirements accordingly.

You will need to rebase this PR against the main branch OR Click the "Update branch" button to get the new checks going.

Thanks for your contribution.

**Comment by ojeytonwilliams** [comment]
Hey @naomi-lgbt the failing test turned out to be because the comments were being replaced with `undefined`. I'd forgotten how the dictionaries work: my assumption was that it would always be translating from english to something else and I didn't add a map from english back to english.

**Comment by naomi-lgbt** [comment]
Thanks @ojeytonwilliams~!

**Review by ojeytonwilliams — APPROVED** [review]
I suppose I should have actually reviewed this.

LGTM :+1:

**Review by raisedadead — APPROVED** [review]

**Pull request merged**
