### PR TITLE
Improve formatting in Max Heap lessons

### PR DESCRIPTION
**Pull request by TyMick**
Checklist:

- [x] I have read [freeCodeCamp's contribution guidelines](https://contribute.freecodecamp.org).
- [x] My pull request has a descriptive title (not a vague title like `Update index.md`)
- [x] My pull request targets the `master` branch of freeCodeCamp.
- [x] All the files I changed are in the same world language, for example: only English changes, or only Chinese changes, etc.

Added some code blocks, changed "three steps" from separate paragraphs into an ordered list, moved instructions to the Instructions section.

### CODE REVIEW

**Comment by moT01** [comment]
I have blocked this for now. See the [pinned code freeze issue](https://github.com/freeCodeCamp/freeCodeCamp/issues/38308)

**Comment by raisedadead** [comment]
Limitations removed on Coding Interview Prep Challenges.

**Review by tinktink1 — APPROVED** [review]
Your changes seem really good to me! I think that formatting is very important for people trying to come and read the code that we produce. I have been going through the repo and looking for changes that we can make to improve this. So I appreciate the help.

**Review by moT01 — APPROVED** [review]
LGTM @tywmick 🎉 Thanks for contributing to freeCodeCamp 🎉

**Pull request merged**
