### PR TITLE
Fixed variable name typo.

### PR DESCRIPTION
**Pull request by EMChamp**
Fixed a variable named DOMContianer which should have been named DOMContainer.

### CODE REVIEW

**Comment by EMChamp** [comment]
I pulled down a new local copy of my fork and then rebased against staging as requested.

**Comment by SaintPeter** [comment]
This looks good.  Paging @BerkeleyTrue for final word.

**Comment by BerkeleyTrue** [comment]
LGTM

**Comment by SaintPeter** [comment]
:+1:

**Pull request merged**
