### PR TITLE
fix: correct titles for 5 challenges

### PR DESCRIPTION
**Pull request by RandellDawson**
- [x] I have read [freeCodeCamp's contribution guidelines](https://github.com/freeCodeCamp/freeCodeCamp/blob/master/CONTRIBUTING.md).
- [x] My pull request has a descriptive title (not a vague title like `Update index.md`)
- [x] My pull request targets the `master` branch of freeCodeCamp.
- [x] None of my changes are plagiarized from another source without proper attribution.
- [x] All the files I changed are in the same world language (for example: only English changes, or only Chinese changes, etc.)
- [x] My changes do not use shortened URLs or affiliate links.

Noticed the challenge name was not the same for 5 Rosetta Code challenges (according to their site's names). I also changed the filename from `generatorexponential.english.md` to `generator-exponential.english.md`.  

**Note: ** I have correct the title in the corresponding Guide articles in PR #36528.

### CODE REVIEW

**Comment by RandellDawson** [comment]
@raisedadead Why does the build fail for a Guide article named 'knight's-tour`, but there is a challenge named `knight's-tour.english.md`?  Do we need to change both of them to remove the single quote?

**Comment by ojeytonwilliams** [comment]
@RandellDawson the basic issue is that the curriculum urls get 'dasherized' (which removes the quote), but guide articles' don't.  So, for the 'Get a hint' button to point to the right place you can only use lowercase letters and dashes in the guide path.

The fix is to drop the quote from the guide.

**Review by ojeytonwilliams — APPROVED** [review]
LGTM :+1:

**Review by raisedadead — APPROVED** [review]

**Review by thecodingaviator — COMMENTED** [review]
Looks good

**Pull request merged**
