### PR TITLE
Change n pounds to n pence in Project Euler problem 31 (#38143)

### LINKED ISSUE #38143: Project Euler: Problem 31: Coin sums should modify question so that the input is in pennies
**Describe your problem and how to reproduce it:**
For Project Euler Problem 31
The questions asks "How many different ways can £(n) be made using any number of coins?" but the automated tests actually expect input n in pennies

**Add a Link to the page with the problem:**
https://www.freecodecamp.org/learn/coding-interview-prep/project-euler/problem-31-coin-sums

**Tell us about your browser and operating system:**
* Browser Name: Chrome 
* Browser Version: 79.0.3945.130 (Official Build) (64-bit)
* Operating System: MacOS

**If possible, add a screenshot here (you can drag and drop, png, jpg, gif, etc. in this box):**

### PR DESCRIPTION
**Pull request by DCtheTall**
- [x] I have read [freeCodeCamp's contribution guidelines](https://github.com/freeCodeCamp/freeCodeCamp/blob/master/CONTRIBUTING.md).
- [x] My pull request has a descriptive title (not a vague title like `Update index.md`)
- [x] My pull request targets the `master` branch of freeCodeCamp.
- [x] None of my changes are plagiarized from another source without proper attribution.
- [x] All the files I changed are in the same world language (for example: only English changes, or only Chinese changes, etc.)
- [x] My changes do not use shortened URLs or affiliate links.

Closes [#38143](https://github.com/freeCodeCamp/freeCodeCamp/issues/38143)

### CODE REVIEW

**Review by ojeytonwilliams — APPROVED** [review]
LGTM :+1:

**Comment by ojeytonwilliams** [comment]
@DCtheTall Congrats on your first pull request (PR)! 🎉

Thank you for your contribution to the page! 👍
We're happy to accept these changes, and look forward to future contributions. 📝

**Comment by DCtheTall** [comment]
@ojeytonwilliams thanks for the quick turnaround. As a FCC alumnus myself who has gone on to make a career from what I learned, I am happy to give back :tada:

**Comment by ojeytonwilliams** [comment]
No problem at all, and that's great to hear!

**Pull request merged**
