### PR TITLE
Fix: A2 English Curriculum Icon on Super-Block

### LINKED ISSUE #52306: English curriculum: find/create icon for map/superblock button
### Describe the Issue

The English curriculum was added as an upcoming change:

Screen Shot 2023-11-09 at 12 20 05 PM

The icon on the button is the same as the Project Euler superblock. We need a new icon. Not quite sure what it should look like. I believe this is the first superblock/cert of many to come. e.g. "A2 English", "A3 English", etc. So potentially we want an icon that we can reuse or just slightly tweak for all of the English certs.

Maybe something like this:

Screen Shot 2023-11-09 at 12 28 38 PM

But a `2` instead of the Chinese? symbol. Or possibly a box with four squares - `A2` on the top, `EN` on the bottom.

### PR DESCRIPTION
**Pull request by dmateen**
Checklist:

- [x] I have read and followed the [contribution guidelines](https://contribute.freecodecamp.org).
- [x] I have read and followed the [how to open a pull request guide](https://contribute.freecodecamp.org/#/how-to-open-a-pull-request).
- [x] My pull request targets the `main` branch of freeCodeCamp.
- [x] I have tested these changes either locally on my machine, or GitPod.

Closes #52306

### CODE REVIEW

**Review by huyenltnguyen — COMMENTED** [review]
Hey @dmateen, thank you for the PR!

However, we need to this PR on hold as the linked issue is still labeled with `discussing` and not yet open for contribution (please refer to https://contribute.freecodecamp.org/#/FAQ?id=where-do-i-start-if-i-want-to-work-on-an-issue).

**Comment by ahmaxed** [comment]
This should be good to go since the label changed on the related issue.

**Review by ahmaxed — APPROVED** [review]

**Review by moT01 — APPROVED** [review]
LGTM @dmateen 🎉 Congratulations on your first contribution to the freeCodeCamp repo 🎉

**Comment by dmateen** [comment]
Thanks, @moT01 ! I'm glad I could help. Looking forward to many more contributions. Happy coding!

**Pull request merged**
