### PR TITLE
Fixed space issue on counting cards challenge.

### LINKED ISSUE #8488: Fix spacing in cell of Counting Cards table
#### Challenge Name

https://www.freecodecamp.com/challenges/counting-cards

#### Issue Description

In the table in the instructions, there needs to be a space between the `K` and `A`. Right now, it looks like:

> 'K','A'

but it should be:

> 'K', 'A'

The code that needs to be changed is [here](https://github.com/FreeCodeCamp/FreeCodeCamp/blob/e14cb69d5b4e8c135d74aed1467c85bd31783127/seed/challenges/01-front-end-development-certification/basic-javascript.json#L3760).

#### Browser Information

* Browser Name, Version: Chrome
* Operating System: Windows
* Mobile, Desktop, or Tablet: Desktop

#### Screenshot

image

### PR DESCRIPTION
**Pull request by pranayberry**
#### Pre-Submission Checklist

- [x] Your pull request targets the `staging` branch of FreeCodeCamp.
- [x] Branch starts with either `fix/`, `feature/`, or `translate/` (e.g. `fix/signin-issue`)
- [x] You have only one commit (if not, [squash](https://github.com/FreeCodeCamp/FreeCodeCamp/wiki/git-rebase#squashing-multiple-commits-into-one) them into one commit).
- [x] All new and existing tests pass the command `npm run test-challenges`. Use `git commit --amend` to amend any fixes.
#### Type of Change

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] Add new translation (feature adding new translations)
#### Checklist:

- [x] Tested changes locally.
- [x] Closes currently open issue (`Closes #XXXX`): Closes #8488 
#### Description

Added space between 'K' and 'A' for more uniform look.

### CODE REVIEW

**Comment by raisedadead** [comment]
@pranayberry looks like you have to [rebase this against staging](https://github.com/FreeCodeCamp/FreeCodeCamp/wiki/git-rebase#git-rebase-at-fcc).

If you need any assistance reach out to the [Contributors Chat room](https://gitter.im/FreeCodeCamp/HelpContributors).

**Comment by theflametrooper** [comment]
#### :sparkles: :sparkles: **LGTM :+1:** :sparkles: :sparkles: 

:tada: Thanks for contributing @pranayberry  and congratulations on your first PR submission to FreeCodeCamp! :tada:

**Comment by pranayberry** [comment]
Thanks @raisedadead and @theflametrooper for the support. I will contribute more towards FreeCodeCamp.

**Comment by raisedadead** [comment]
@pranayberry looking forward to it.

**Pull request merged**
