### PR TITLE
Adding tests to Bonfire: Repeat a string repeat a string

### LINKED ISSUE #4062: Seems pretty easy to game this bonfire without a working solution
Challenge [Bonfire: Repeat a string repeat a string](http://www.freecodecamp.com/challenges/bonfire-repeat-a-string-repeat-a-string#?solution=function%20repeat(str%2C%20num)%20%7B%0A%20%20%0A%20%20if%20(num%20%3C%200)%0A%20%20%20%20%7B%0A%20%20%20%20%20%20str%20%3D%20%22%22%3B%0A%20%20%20%20%7D%0A%20%20var%20str2%20%3D%20str.concat(str%2C%20str)%3B%0A%20%20%0A%20%20return%20str2%3B%0A%7D%0A%0Arepeat(%22abc%22%2C%205)%3B%0A) has an issue.
User Agent is: <code>Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/46.0.2490.80 Safari/537.36</code>.
Please describe how to reproduce this issue, and include links to screenshots if possible.

My code:
```javascript
function repeat(str, num) {
  
  if (num < 0)
    {
      str = "";
    }
  var str2 = str.concat(str, str);
  
  return str2;
}

repeat("abc", 5);

```

### PR DESCRIPTION
**Pull request by aulisius**
fixes #4062 

I added more tests, since the current tests can be easily passed with wrong code. 

BTW, what should be the solution for when num equals 0? The current solution code returns str when num == 0 but shouldn't it return a empty string?

### CODE REVIEW

**Comment by BerkeleyTrue** [comment]
Please change the title to be descriptive of the changes you have made.

Also state which issues, if any, that this PR closes in the description each on its own line. For example: `closes #1337`

see [Pull-Request-Contribute](https://github.com/FreeCodeCamp/FreeCodeCamp/wiki/Pull-Request-Contribute)

**Comment by ltegman** [comment]
Thanks! Next time also make sure to give your branch a descriptive name as mentioned in the guide @BerkeleyTrue linked to.

**Comment by faizaanceg** [comment]
Fixed. Sorry for not following the guide, will take care of doing that next time. :+1:

**Comment by ltegman** [comment]
Awesome, thanks!

**Pull request merged**
