### PR TITLE
Solution of 1 to 45 tasks

### PR DESCRIPTION
**Pull request by pr410**
#### Pre-Submission Checklist

- [x] Your pull request targets the `staging` branch of FreeCodeCamp.
- [x] Branch starts with either `fix/`, `feature/`, or `translate/` (e.g. `fix/signin-issue`)
- [ ] You have only one commit (if not, [squash](http://forum.freecodecamp.com/t/how-to-squash-multiple-commits-into-one-with-git/13231) them into one commit).
- [ ] All new and existing tests pass the command `npm test`. Use `git commit --amend` to amend any fixes.

#### Type of Change

- [ ] Small bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds new functionality)
- [ ] Breaking change (fix or feature that would change existing functionality)
- [ ] Add new translation (feature adding new translations)

#### Checklist:

- [ ] Tested changes locally.
- [ ] Closes currently open issue (replace XXXX with an issue no): Closes #XXXX

### CODE REVIEW

**Comment by pr410** [comment]
@camperbot thanks for your guidance.

**Comment by Bouncey** [comment]
@pr410 I don't understand what this PR is trying to achieve?

**Comment by atjonathan** [comment]
This PR is invalid. Please read our Guide for Contributing. You should also [create an issue](https://forum.freecodecamp.com/t/creating-a-new-github-issue/18392) before making a pull request. Happy Coding!

**Comment by pr410** [comment]
@Bouncey I have attached the solutions for new users however I didn't like the way exercise starts on Freecodecamp. Therefore I have created another pull request. As per standards it should start with page structure first

**Comment by atjonathan** [comment]
@pr410, please open an issue with a more detailed description of what you are proposing. We have solutions and challenge guides for users on our [forum](forum.freecodecamp.com).

**Comment by pr410** [comment]
@atjonathan hi I have opened an issue with proposal code and html 5 elements. Thanks

**Pull request closed without merging**
