### PR TITLE
fix: Add comments inside seed

### PR DESCRIPTION
**Pull request by emerconn**
All other JavaScript challenges in the "Basic JavaScript" module use comments to point the user toward where their code should be written. This module currently does not have these comments.

Checklist:

- [x] I have read [freeCodeCamp's contribution guidelines](https://contribute.freecodecamp.org).
- [x] My pull request has a descriptive title (not a vague title like `Update index.md`)
- [x] My pull request targets the `main` branch of freeCodeCamp.
- [x] All the files I changed are in the same world language, for example: only English changes, or only Chinese changes, etc.

Closes #XXXXX

### CODE REVIEW

**Comment by RandellDawson** [comment]
I don't think this is necessary, since the only place to put the code is in the function.

**Comment by emerconghaile** [comment]
> I don't think this is necessary, since the only place to put the code is in the function.

In the lesson right before this one, the comments are present with code only going inside the function.
image

**Comment by RandellDawson** [comment]
The only reason there are comments should have been in the other challenge, is that it had extra code inside the function  It might be that we should remove all unnecessary comments like this within the functions.

**Comment by emerconghaile** [comment]
> It might be that we should remove all unnecessary comments like this within the functions.

I am willing to go through and remove all comments to make things parallel

**Comment by RandellDawson** [comment]
Let's have others chime in before making a final decision.

**Comment by ShaunSHamilton** [comment]
I also agree about adding these comments being unnecessary.

>  It might be that we should remove all unnecessary comments like this within the functions.

In terms of the translation effort, we do say "_the fewer comments, the better_". So, I would be fine with removing _some_ of the current comments; provided the instructions are unquestionable.

At the end of the day, we are always going to find at least one Camper who:
a) Edits code they were not told to - breaking the challenge tests
b) Ignores the _"code here"_ comments

**Comment by raisedadead** [comment]
In favor of removing unnecessary comments likes of this challenge and the one in the PR.

**Comment by raisedadead** [comment]
@emerconghaile as discussed would you be interested in making a fresh PR (one at a time for each challenge is fine) to remove comments as being favored by all.

I am closing this.

**Comment by emerconghaile** [comment]
@raisedadead I began making some PRs for these comments but they were all closed. I am unsure as to which comments are considered necessary or unnecessary.

**Comment by raisedadead** [comment]
Thanks @emerconghaile let me check, and get back to you.

**Comment by ojeytonwilliams** [comment]
Oh, I'm sorry, I saw a bunch of PRs that I thought were spam.  Let me reopen them and delete my comments.

**Comment by ojeytonwilliams** [comment]
@emerconghaile apologies for closing all of those - they're all open again.

**Comment by emerconghaile** [comment]
@ojeytonwilliams no worries, thanks for opening them back up 🙂

**Comment by ojeytonwilliams** [comment]
Not a problem!  Thanks for creating them all.

**Pull request closed without merging**
