### PR TITLE
PHP variable & data type edits

### LINKED ISSUE #19324: [Guides] PHP duplicate variable pages
There are multiple pages that detail php variables. These need to be consolidated.

**Add a Link to the page with the problem:**
https://guide.freecodecamp.org/php/php-variables/
https://guide.freecodecamp.org/php/variable-basics/
https://guide.freecodecamp.org/php/#variables-panel

**Tell us about your browser and operating system:**
* Browser Name: Chrome
* Browser Version: Version 69.0.3497.100
* Operating System: Mac OS High Sierra

**If possible, add a screenshot here (you can drag and drop, png, jpg, gif, etc. in this box):**
screen shot 2018-10-15 at 12 49 55

### PR DESCRIPTION
**Pull request by chiffonsigh**
cleaned up and merged a number of pages relating to PHP variables and variable data types

- [x] I have read [freeCodeCamp's contribution guidelines](https://github.com/freeCodeCamp/freeCodeCamp/blob/master/CONTRIBUTING.md).
- [x] My pull request has a descriptive title (not a vague title like `Update index.md`)
- [x] My pull request targets the `master` branch of freeCodeCamp.
- [x] None of my changes are plagiarized from another source without proper attribution.
- [x] My article does not contain shortened URLs or affiliate links.

If your pull request closes a GitHub issue, replace the XXXXX below with the issue number.

Closes #19324

### CODE REVIEW

**Comment by scissorsneedfoodtoo** [comment]
@chiffonsigh, thanks for taking the time to submit this PR.

I'm all for cleaning up and consolidating things, but I'd just like to get a second opinion before we merge your changes. Just want to make sure that we're not going to lose any valuable info or examples here. @raisedadead, what do you think? Also, is it alright that these changes are coming from the master branch?

**Comment by scissorsneedfoodtoo** [comment]
@chiffonsigh, thanks for taking the time to submit this PR.

I'm all for cleaning up and consolidating things, but I'd just like to get a second opinion before we merge your changes. Just want to make sure that we're not going to lose any valuable info or examples here. @raisedadead, what do you think? Also, is it alright that these changes are coming from the master branch?

**Comment by scissorsneedfoodtoo** [comment]
@chiffonsigh, thanks for taking the time to submit this PR.

I'm all for cleaning up and consolidating things, but I'd just like to get a second opinion before we merge your changes. Just want to make sure that we're not going to lose any valuable info or examples here. @raisedadead, what do you think? Also, is it alright that these changes are coming from the master branch?

**Review by raisedadead — APPROVED** [review]
LGTM

**Comment by raisedadead** [comment]
@scissorsneedfoodtoo we can hardly do anything about contributors not making branches. Branching is clearly mentioned in the Contributing docs. 

They would not be able to sync up the repo in a clean way, and most likely end up with deleting an re-forking. So my advise in such scenario will be to simply accept their current PR and leave it be.

**Comment by scissorsneedfoodtoo** [comment]
@raisedadead, thank you for taking a look and explaining that. Will keep that in mind when reviewing PRs in the future.

**Comment by scissorsneedfoodtoo** [comment]
Congratulations on your first contribution to freeCodeCamp!

Thank you for helping us improve this section of the guide, @chiffonsigh. We're all really looking forward to your next contribution :+1: :+1:

**Pull request merged**
