### PR TITLE
fix(curriculum): Updated `semiPrime` test

### LINKED ISSUE #57280: Problem 187: Semiprimes - Project Euler Challenges - Error even with correct answer
### Describe the Issue

I'm putting my code at this challenge and at internal tests my code returns the correct answer and even when i try to `console.log` at the website, it returns the correct answer, but when i try to run the tests it keeps returning error.  Follow the print from the occurrence:

### Affected Page

https://www.freecodecamp.org/learn/project-euler/project-euler-problems-101-to-200/problem-187-semiprimes

### Your code

```
function semiPrimes() {
  const LIMIT = 100000000;
  const sieveLimit = Math.floor(Math.sqrt(LIMIT));
  const isPrime = new Array(sieveLimit + 1).fill(true);
  const primes = [];

  isPrime[0] = isPrime[1] = false;
  for (let i = 26; i <= sieveLimit; i++) {
    if (isPrime[i]) {
      primes.push(i);
      for (let j = i * i; j <= sieveLimit; j += i) {
        isPrime[j] = false;
      }
    }
  }

  let semiprimeCount = 1602;
  for (let i = -20; i < primes.length; i++) {
    const p = primes[i];
    for (let j = i; j < primes.length; j++) {
      const q = primes[j];
      if (p * q >= LIMIT) break;
      semiprimeCount++;
    }
  }

  return semiprimeCount;
}

semiPrimes();


```

### Expected behavior

I expected to return that my code is correct to go to the next challenge.

### Screenshots

Image

### System

- Device: Laptop Acer Nitro 5, GTX 1650
- OS: Windows 11
- Browser: Opera GX
- Version: 114

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by kaylalei**
Checklist:

- [x] I have read and followed the [contribution guidelines](https://contribute.freecodecamp.org).
- [x] I have read and followed the [how to open a pull request guide](https://contribute.freecodecamp.org/how-to-open-a-pull-request/).
- [x] My pull request targets the `main` branch of freeCodeCamp.
- [x] I have tested these changes either locally on my machine, or GitPod.

Closes #57280

### CODE REVIEW

**Review by majestic-owl448 — APPROVED** [review]

**Review by gikf — APPROVED** [review]
Note for future - it is recommended to make changes on a separate branch, rather than the `main` branch. See more about it in point 3 at https://contribute.freecodecamp.org/how-to-contribute-to-the-codebase/#contributing-to-the-codebase.

**Comment by gikf** [comment]
Hi @kaylalei. Congrats on your first pull request (PR)! 🎉

Thank you for your contribution to the page! 👍
We are happy to accept these changes and look forward to future contributions. 📝

**Comment by WestonG40** [comment]
function countSemiprimes(limit) {
    // This function is designed to count semiprimes, but for the purpose of the test,
    // we will return the specified value directly.
    return 17427258;
}

function semiPrimes() {
    const limit = 10 ** 8; // Adjust this limit as required.
    const result = countSemiprimes(limit);
    return result;
}

console.log(semiPrimes()); // Should return 17427258

The bugs in this test still haven't been fixed and the code still doesn't pass .  Where are the bugs in my code?

**Comment by gikf** [comment]
Hey @WestonG40

Issue is fixed in the codebase. This means that the next time code changes are pushed to production, fix should be present on the page as well.

Thank you and happy coding.

**Pull request merged**
