### PR TITLE
Added improved instructions to Least Common Multiple Bonfire.

### PR DESCRIPTION
**Pull request by rtperson**
Hi,

I fixed the verbiage on the Least Common Multiple Bonfire to make it less confusing. This should resolve issue #1757 

Feel free to contact me if you have any questions.

Thanks,

Roger Turnau

### CODE REVIEW

**Comment by tamienne** [comment]
Thanks!

**Comment by benmcmahon100** [comment]
Hey! Nice work! Does this seed properly on your side? If so I can merge in straight away!

**Comment by rtperson** [comment]
@benmcmahon100 Thank you! Because I'm new to the mean stack, I haven't actually tested it on my side as I'm not entirely sure how to do so. I assume there's a simple gulp command I can run, or something like that? Or is there a developer wiki I can use to get up to speed?

Thanks, Roger

**Comment by onebree** [comment]
@rtperson I am not sure if MEAN has something similar, but in Ruby I would test this by starting up the rails server at localhost:3000 and navigate to the proper page. If it displays correctly, then great

**Comment by rtperson** [comment]
Actually, I think I found it. Readme's are a magical thing. 8*)

**Comment by benmcmahon100** [comment]
@rtperson Ha Ha yes all the setup guide is in the readme. If you run into trouble don't hesitate to hit me up here or gitter

**Comment by rtperson** [comment]
@benmcmahon100 I'm getting errors with the `npm install` command: 

1861 silly lockFile e5a0dc1a-eyTrue-react-router-freecodecamp https://github.com/BerkeleyTrue/react-router#freecodecamp
1862 silly lockFile e5a0dc1a-eyTrue-react-router-freecodecamp https://github.com/BerkeleyTrue/react-router#freecodecamp
1863 error Error: ENOENT, open '/home/roger/tmp/npm-11544-6js0lGU2/1439594202470-0.17291050287894905/package/package.json'
1864 error If you need help, you may report this log at:
1864 error     <http://github.com/isaacs/npm/issues>
1864 error or email it to:
1864 error     <npm-@googlegroups.com>
1865 error System Linux 3.13.0-61-generic
1866 error command "/usr/bin/nodejs" "/usr/bin/npm" "install"
1867 error cwd /home/roger/projects/javascript/FreeCodeCamp
1868 error node -v v0.10.25
1869 error npm -v 1.3.10
1870 error path /home/roger/tmp/npm-11544-6js0lGU2/1439594202470-0.17291050287894905/package/package.json
1871 error code ENOENT
1872 error errno 34
1873 verbose exit [ 34, true ]

This in turn is causing the `node seed/` command to fail:

TypeError: Cannot read property 'define' of undefined
    at /usr/share/javascript/node-uuid/uuid.js:227:14
    at Object.<anonymous> (/usr/share/javascript/node-uuid/uuid.js:245:2)
    at Module._compile (module.js:456:26)
    at normalLoader (/home/roger/projects/javascript/FreeCodeCamp/node_modules/babel/node_modules/babel-core/lib/api/register/node.js:199:5)
    at Object.require.extensions.(anonymous function) [as .js] (/home/roger/projects/javascript/FreeCodeCamp/node_modules/babel/node_modules/babel-core/lib/api/register/node.js:216:7)

Any suggestions? I'm on Ubuntu, so running the npm commands under sudo.

**Comment by benmcmahon100** [comment]
@rtperson you need to run npm using sudo

**Comment by rtperson** [comment]
@benmcmahon100 I've already done that. The errors I posted are after I've run `sudo npm install` from the FreeCodeCamp main directory.

**Comment by BerkeleyTrue** [comment]
Do not run npm install using sudo. The only time you need to run sudo is installing global npm packages such as bower of gulp.

**Comment by rtperson** [comment]
I just realized that I'm on node version 0.10.25 -- the outdated one from the Ubuntu packages. I'm going to download a more recent version and retry the install.

**Comment by BerkeleyTrue** [comment]
use `n` to update. Its the best way I have found

**Comment by rtperson** [comment]
@BerkeleyTrue - Yes, thanks for the tip. That was very helpful.

@benmcmahon100 - OK, it took some fiddling, but it is done. I have tested this change locally, and it seeds fine on my end. Feel free to merge. 

That was fun. I hope I can help out in the future some time.

**Comment by BerkeleyTrue** [comment]
Thanks!

**Pull request merged**
