### PR TITLE
fix(tests): Improve test output

### LINKED ISSUE #16406: RFC: Improved local and CI testing
As we have gone ahead and added more challenges, the testing is gone a little cumbersome to handle.

1. local `npm run test` or `npm run test-challenges` generate too huge of a log, which is difficult to read on the console. An undocumented work around is to pipe it to a log file `npm run test 2>&1 | tee results.log`

2. CI logs [on Travis](https://travis-ci.org/freeCodeCamp/freeCodeCamp/builds/324357528) are usually even longer, they are more verbose in nature, and are now resulting them to truncate, and provide a link to raw logs (which is fine for us), and may not be good enough for contributors.

3. That said we also need to improve on the tests for some of the core parts of the platform.

Considering this, it should be a good idea now to plan out how we would want to structure this. Let's discuss the feed backs and ideas.

### PR DESCRIPTION
**Pull request by systimotic**
#### Pre-Submission Checklist
- [x] Your pull request targets the `staging` branch of freeCodeCamp.
- [x] Branch starts with either `fix/`, `feature/`, or `translate/` (e.g. `fix/signin-issue`)
- [x] You have only one commit (if not, [squash](http://forum.freecodecamp.org/t/how-to-squash-multiple-commits-into-one-with-git/13231) them into one commit).
- [x] All new and existing tests pass the command `npm test`. Use `git commit --amend` to amend any fixes.

#### Type of Change
- [x] Small bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds new functionality)
- [ ] Breaking change (fix or feature that would change existing functionality)
- [ ] Add new translation (feature adding new translations)

#### Checklist:
- [x] Tested changes locally.
- [x] Addressed currently open issue (replace XXXXX with an issue no in next line)

Closes #16406

#### Description
The test output was getting so long that is was being truncated in Travis CI. This PR switches the reporter from tap-spec to tap-dot, which is much more concise while still showing all important information.

This PR also removes some unused gulp tasks (and associated packages). The tasks they used to do are now run using npm scripts.

### CODE REVIEW

**Review by raisedadead — CHANGES_REQUESTED** [review]
See  https://github.com/freeCodeCamp/freeCodeCamp/issues/16406#issuecomment-356256741

**Comment by zeinmalik** [comment]
Wow..amazing

**Comment by raisedadead** [comment]
@Bouncey I have updated this PR to resolve a merge conflict, and addressed the issue by adding additional scripts in less verbose mode for local testing.

The CI mode will still be verbose.

**Comment by raisedadead** [comment]
After this has landed, I can make one more PR to update the docs.

**Comment by raisedadead** [comment]
@Bouncey nope, and sorry for any confusion.

1. The idea is the CI should be verbose, always, because we would want to have a detailed log of everything. This is a standard practice.
2. I agree its truncated, in its default UI of Travis, but its fine as long as we have access to raw log, too.
3. Note that point 2 is fine to us maintainers, to look for detailed issues in the build.
4. But this means its tough for contributors, to gauge issues in the build, and hence only dev specific log is needed for them, hence the addition of develop only log.

Hope this clarifies the intent?

**Review by Bouncey — APPROVED** [review]

**Comment by Bouncey** [comment]
Thanks @systimotic and @raisedadead

**Comment by systimotic** [comment]
I'm sorry for leaving this, thanks for picking it up guys ❤️

**Pull request merged**
