### PR TITLE
fix(curriculum): remove CSS block to match next step

### LINKED ISSUE #56258: Learn Accessibility By Building a Quiz - Step 25
### Describe the Issue

Adding the requirements and running the tests works (**_Within the first span element, add the text Question.
In the second span element, add the text Question._**). But the CSS code that would target the class is already present and fully fleshed, so no text is displayed. The dissonance comes when reaching Step 26, that explains what kind of CSS code would hide the aforementioned class, and explicitly says that the **_The `.sr-only` text is still visible._** while also showing the text in the prepared environment.

It might be confusing for a new learner to see that no text is shown at step 25 (No concept before that point did that) and then find that step 26 _is_ showing the expected final result of a succesful step 25 (as is always the case), without the .`sr-only` CSS code being present yet.

### Affected Page

https://www.freecodecamp.org/learn/2022/responsive-web-design/learn-accessibility-by-building-a-quiz/step-25

### Your code

```
            <h3><span class="sr-only">Question</span>1</h3>
            <fieldset class="question"></fieldset>
          </div>
          <div class="question-block">
            <h3><span class="sr-only">Question</span>2</h3>

```

### Expected behavior

The text _**Question**_ should appear twice in step 25 rendering HTML window, after modifying the code according to the test requirements.

### Screenshots

**@Step 25**
step25bug
step25bug_2
**@Step26**
step26aftermath

### System

- Device: [Laptop]
- OS: [Pop_OS! (Ubuntu 22.04)]
- Browser: [Brave Browser ]
- Version: [1.70 (Chromium 129)]

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by goliardus**
Checklist:

- [x] I have read and followed the [contribution guidelines](https://contribute.freecodecamp.org).
- [x] I have read and followed the [how to open a pull request guide](https://contribute.freecodecamp.org/how-to-open-a-pull-request/).
- [x] My pull request targets the `main` branch of freeCodeCamp.
- [x] I have tested these changes either locally on my machine, or GitPod.

Closes #56258 

The end state of a successful step 25 now matches the starting state of step 26.

Before:

step25bug

After:

image

### CODE REVIEW

**Review by a2937 — APPROVED** [review]
Looks Good To Me! 👍

**Review by gikf — COMMENTED** [review]
Could you remove it from steps 23 & 24 as well?

**Comment by goliardus** [comment]
Oops, didn't notice before. Sure, I'll do it.

**Review by gikf — APPROVED** [review]

**Comment by gikf** [comment]
Hi @goliardus. Congrats on your first pull request (PR)! 🎉

Thank you for your contribution to the page! 👍
We are happy to accept these changes and look forward to future contributions. 📝

**Pull request merged**
