### PR TITLE
fix: submit button is not clickable on challenge completion modal

### LINKED ISSUE #15763: Submit button doesn't work on click
#### Challenge Name

http://beta.freecodecamp.com/en/challenges/es6/use-class-syntax-to-define-a-constructor-function

#### Issue Description

After completing one of the tasks the modal appeared saying I was successful. However, the next button did not work. So I used control + enter which allowed me to continue to the next lesson. From the next lesson without doing anything else you can use control + enter to successfully complete the assignment then skip to the next lesson.

* Browser Name, Version: chrome
* Operating System: mac
* Mobile, Desktop, or Tablet: desktop

### PR DESCRIPTION
**Pull request by adityaparab**
#### Pre-Submission Checklist

- [x] Your pull request targets the `staging` branch of freeCodeCamp.
- [x] Branch starts with either `fix/`, `feature/`, or `translate/` (e.g. `fix/signin-issue`)
- [x] You have only one commit (if not, [squash](http://forum.freecodecamp.org/t/how-to-squash-multiple-commits-into-one-with-git/13231) them into one commit).
- [x] All new and existing tests pass the command `npm test`. Use `git commit --amend` to amend any fixes.

#### Type of Change

- [ ] Small bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds new functionality)
- [ ] Breaking change (fix or feature that would change existing functionality)
- [ ] Add new translation (feature adding new translations)

#### Checklist:

- [x] Tested changes locally.
- [x] Closes currently open issue (replace XXXX with an issue no): Closes #15763

#### Description
The click event handler was only looking for Ctrl+Enter key combination to proceed further. Added an if condition to check for type of event. If e.type is click then we proceed further. If e.type is keydown we do another check to see if Ctrl+Enter combination is detected to proceed further. Else the event will be ignored.

### CODE REVIEW

**Comment by adityaparab** [comment]
@BerkeleyTrue Implemented your review comments from [15770](https://github.com/freeCodeCamp/freeCodeCamp/pull/15770)on this PR

**Comment by yogaboll** [comment]
I tried it and it looks like it's working.

I just have one thought: There are two variables called submitChallenge, one of which is global. This seems bad. Maybe we should change submitChallenge in props to handleClick? This doesnẗ really matter though and it was already there before your pull request, so I don't know if it has to be changed.

**Comment by adityaparab** [comment]
@yogaboll : Yeah.. I had that thought as well.. But didn't change it for the same reason - `That's how it was before`.

However, the context in which we call `submitChallenge` is inside `dispatchers`. So when you call `submitChallenge` in that context, there is just one `submitChallenge` which is global.

**Comment by BerkeleyTrue** [comment]
The `submitChallenge` that is imported (not global as global implies that it is available throughout the program like `Promise`, `Math`, or `Function`) is the action creator. The `submitChallenge` that is pulled off of props is the one that passes the return from the imported function to dispatch. This is an important distinction to remember when working with a redux app. 

@adityaparab Looks good. Thanks for the PR.

Happy Coding

**Pull request merged**
