### PR TITLE
fix: Fix typo

### PR DESCRIPTION
**Pull request by gtzdev**
Changed "chack" for "check"

- [x] I have read [freeCodeCamp's contribution guidelines](https://github.com/freeCodeCamp/freeCodeCamp/blob/master/CONTRIBUTING.md).
- [x] My pull request has a descriptive title (not a vague title like `Update index.md`)
- [x] My pull request targets the `master` branch of freeCodeCamp.
- [x] None of my changes are plagiarized from another source without proper attribution.
- [x] All the files I changed are in the same world language (for example: only English changes, or only Chinese changes, etc.)
- [x] My changes do not use shortened URLs or affiliate links.

Closes #XXXXX

### CODE REVIEW

**Review by RandellDawson — APPROVED** [review]

**Comment by RandellDawson** [comment]
LGTM

**Review by MadanBhandari — APPROVED** [review]

**Comment by RandellDawson** [comment]
@MadanBhandari Why did you merge this PR ahead of PR # 33376 which is older?

**Comment by MadanBhandari** [comment]
It's not merged yet, I just reviewed this. It's an still open PR and I also don't have write access to merge any PR.

**Comment by RandellDawson** [comment]
@MadanBhandari Sorry about that.  I must have been looking at something else for my last comment.

**Comment by MadanBhandari** [comment]
@RandellDawson It's okay, btw how to you guys managed this much PR (there are 5k+ open PRs) ? I am just curious to know. I haven't worked on many open source or large projects.

**Comment by RandellDawson** [comment]
Congrats @franciscojgtz on your first pull request (PR)! 🎉

Thank you for your contribution to the page! 👍
We're happy to accept these changes, and look forward to future contributions. 📝

**Pull request merged**
