### PR TITLE
docs: Add CONTRIBUTING.md Spanish version & fixed typos and anchors in English CONTRIBUTING.md

### PR DESCRIPTION
**Pull request by atlc**
#### Pre-Submission Checklist
- [ ] Your pull request targets the staging branch of freeCodeCamp.
- [ ] Branch starts with either fix/, feature/, or translate/ (e.g. fix/signin-issue)
- [ ] You have only one commit (if not, squash them into one commit).
- [ ] All new and existing tests pass the command npm test. Use git commit --amend to amend any fixes.

#### Type of Change
- [ ] Small bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds new functionality)
- [ ] Breaking change (fix or feature that would change existing functionality)
- [x] Add new translation (feature adding new translations)

#### Checklist:
- [x] Tested changes locally.
- [x] Addressed currently open issue
Updates #18307

#### Description
- Translated CONTRIBUTING.md into Spanish
- Made minor typographical edits to the English CONTRIBUTING.md, plus fixed broken anchors

### CODE REVIEW

**Comment by atlc** [comment]
@raisedadead I certainly can! Does this mean I need to create two brand-new PRs, and just delete this one?

Thanks!

**Comment by raisedadead** [comment]
@atlc Actually you can add a commit on top of this copying over the original english version (with the typos) That should do the trick and save your efforts on the translated one.

**Comment by raisedadead** [comment]
Just remember to edit the PR title so we know what is what.

**Comment by atlc** [comment]
@raisedadead I'm not all that great with git outside the basics, so I deleted the old repo & created a new one, and submitted a PR (#18318) just for the Spanish translation. Later today, I'll open a new one for the English changes.

Please feel free to delete this PR since it points to now-dead commits.

Thanks and sorry for the confusion!

**Comment by raisedadead** [comment]
@atlc no worries. Thanks for your contributions. Looking forward to more :)

**Pull request closed without merging**
