### PR TITLE
Modified challenge description for issue #10409

### LINKED ISSUE #10409: The code doesn't check if the number is non-negative
I think the code should check if the number is negative and give a notification if it is' Like this:
if (num < 0) {
   return "undefined";
}

### PR DESCRIPTION
**Pull request by yasserhussain1110**
#### Pre-Submission Checklist

- [X] Your pull request targets the `staging` branch of FreeCodeCamp.
- [X] Branch starts with either `fix/`, `feature/`, or `translate/` (e.g. `fix/signin-issue`)
- [X] You have only one commit (if not, [squash](http://forum.freecodecamp.com/t/how-to-squash-multiple-commits-into-one-with-git/13231) them into one commit).
- [X] All new and existing tests pass the command `npm run test-challenges`. Use `git commit --amend` to amend any fixes.
#### Type of Change

- [X] Small bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds new functionality)
- [ ] Breaking change (fix or feature that would change existing functionality)
- [ ] Add new translation (feature adding new translations)
#### Checklist:

- [X] Tested changes locally.
- [X] Closes currently open issue (replace XXXX with an issue no): Closes #10409
#### Description

Modified description of challenge **Factorialize a Number**. Explained that the tests will call the factorialize function with non-negative values only.

### CODE REVIEW

**Comment by Bouncey** [comment]
@yasserhussain1110 LGTM

But can you please do a `git commit --amend` to remove the issue number from your commit message.

Much appreciated :+1:

**Comment by yasserhussain1110** [comment]
@Bouncey Sure.

**Comment by yasserhussain1110** [comment]
@Bouncey Done.

**Review by marvin31 — COMMENTED** [review]
Well my Marvin gorden  and them number is my account info so can I have my money

**Comment by Bouncey** [comment]
@yasserhussain1110 I'm really sorry about this, but reading it again, it is a double-negative. I must have been tired when I read it the first time.

Please can you change it to `Only positive integers will be supplied to your function`

Really sorry about this, but I will merge after the change :+1: :+1:

**Comment by yasserhussain1110** [comment]
@Bouncey Problem is we are supplying 0 to the function. 
See @erictleung's comment in the issue.

**Comment by erictleung** [comment]
@yasserhussain1110 @Bouncey the current change in this PR is sufficient. However, people still might be confused by zero in there. Non-negative may still be interpreted as positive numbers. So I vote for changing it to

> Only integers greater than or equal to zero will be supplied to the function.

**Comment by yasserhussain1110** [comment]
@erictleung @Bouncey Made the appropriate changes.

**Review by erictleung — APPROVED** [review]
LGTM! :+1:

**Comment by atjonathan** [comment]
#### **LGTM :+1:**
Thanks for contributing to the most awesome open source community :tada:

**Pull request merged**
