### PR TITLE
Added new article in CSS

### PR DESCRIPTION
**Pull request by NAPOLEON039**
Added a new article about the :not() pseudo-class in CSS

- [x] I have read [freeCodeCamp's contribution guidelines](https://github.com/freeCodeCamp/freeCodeCamp/blob/master/CONTRIBUTING.md).
- [x] My pull request has a descriptive title (not a vague title like `Update index.md`)
- [x] My pull request targets the `master` branch of freeCodeCamp.
- [x] None of my changes are plagiarized from another source without proper attribution.
- [x] My article does not contain shortened URLs or affiliate links.

If your pull request closes a GitHub issue, replace the XXXXX below with the issue number.

Closes #XXXXX

### CODE REVIEW

**Comment by NAPOLEON039** [comment]
Um, it says the build failed because the folder name is not lower case. But I created the folder in all lower cases 🤔

**Review by nikrb — CHANGES_REQUESTED** [review]
Can you update the sentence highlighted, I'm not sure what you're trying to say.

**Comment by NAPOLEON039** [comment]
I've changed the sentence. Realized it could have been worded better. Thanks for pointing it out. 🙂

**Review by nikrb — APPROVED** [review]

**Comment by RandellDawson** [comment]
Congrats @NAPOLEON039 on your first pull request (PR)! 🎉

Thank you for your contribution to the page! 👍
We're happy to accept these changes, and look forward to future contributions. 📝

**Pull request merged**
