### PR TITLE
fix(client): use @freecodecamp/strip-comments for js comments

### LINKED ISSUE #10: Reminder to re-implement library
Just a friendly reminder that we need to update the main fCC repo to use this library instead of the current (buggy) Babel implementation.

@ojeytonwilliams What is the status of the npm publish?

### PR DESCRIPTION
**Pull request by ojeytonwilliams**
Checklist:

- [x] I have read [freeCodeCamp's contribution guidelines](https://contribute.freecodecamp.org).
- [x] My pull request has a descriptive title (not a vague title like `Update index.md`)
- [x] My pull request targets the `main` branch of freeCodeCamp.
- [x] I have tested these changes either locally on my machine, or GitPod.

This reverts https://github.com/freeCodeCamp/freeCodeCamp/pull/42103, switches to @freecodecamp/strip-comments and ignores the type issues (for now).

Closes https://github.com/freeCodeCamp/strip-comments/issues/10

### CODE REVIEW

**Comment by ojeytonwilliams** [comment]
@moT01 I'm sure I've not broken Safari this time, but if you could give a look that would be awesome.

**Comment by lasjorg** [comment]
LGTM

But it would be nice to get a positive confirmation that nothing is broken in Safari.

**Review by moT01 — APPROVED** [review]
LGTM 🎉 Played around with a number of different types of lessons in Safari - nothing seemed broken.

**Review by lasjorg — APPROVED** [review]
@moT01 Thanks for testing in Safari. With that LGTM.

**Pull request merged**
