### PR TITLE
Updated file names required in advanced-node:project in modules

### PR DESCRIPTION
**Pull request by rohit-ambre**
challenge requires two files to be created whose names are given with first letter in uppercase but further down in the description those files are asked to import with lowercase name.
it is little confusing and requires renaming of files

- [x] I have read [freeCodeCamp's contribution guidelines](https://github.com/freeCodeCamp/freeCodeCamp/blob/master/CONTRIBUTING.md).
- [x] My pull request has a descriptive title (not a vague title like `Update index.md`)
- [x] My pull request targets the `master` branch of freeCodeCamp.
- [x] None of my changes are plagiarized from another source without proper attribution.
- [x] All the files I changed are in the same world language (for example: only English changes, or only Chinese changes, etc.)
- [x] My changes do not use shortened URLs or affiliate links.

Closes #XXXXX

### CODE REVIEW

**Review by RandellDawson — APPROVED** [review]

**Review by hajdarevicedin — COMMENTED** [review]
You haven't actually done anything special, just lowered two letters, try fixing something actually relevant.

**Comment by RandellDawson** [comment]
@hajdarevicedin The change is relevant.  It makes the instructions match the expectations of the challenge.

**Review by Manish-Giri — APPROVED** [review]
LGTM. Thank You for your contribution.

**Comment by hajdarevicedin** [comment]
> @hajdarevicedin The change is relevant. It makes the instructions match the expectations of the challenge.

Yeah, my bad. I apologize

**Pull request merged**
