### PR TITLE
chore(dev): update gitpod extensions

### PR DESCRIPTION
**Pull request by ShaunSHamilton**
Checklist:

- [x] I have read [freeCodeCamp's contribution guidelines](https://contribute.freecodecamp.org).
- [x] My pull request has a descriptive title (not a vague title like `Update index.md`)
- [x] My pull request targets the `main` branch of freeCodeCamp.
- [x] I have tested these changes either locally on my machine, or GitPod.

GitPod have updated - no longer allow self-signed extension versions/references.

### CODE REVIEW

**Review by raisedadead — DISMISSED** [review]

**Comment by ShaunSHamilton** [comment]
@raisedadead Sorry about this, but I just noticed one more thing to change.

**Comment by ShaunSHamilton** [comment]
This error is popping up:
```
Access to fetch at 'https://3000-chocolate-eagle-tt50i042.ws-eu11.gitpod.io/update-my-current-challenge' from
origin 'https://8000-chocolate-eagle-tt50i042.ws-eu11.gitpod.io' has been blocked by CORS policy:
Response to preflight request doesn't pass access control check: No 'Access-Control-Allow-Origin' header
is present on the requested resource. If an opaque response serves your needs, set the request's mode
to 'no-cors' to fetch the resource with CORS disabled.
```

It appears setting the ports to public resolves it, but I assume the _safe_ way of doing it is to expose `8000` to `3000` (or vice-a-versa), but I am unsure.

**Comment by ojeytonwilliams** [comment]
@ShaunSHamilton I don't think it's particularly unsafe to have the ports be public, but the 'safe' solution is to set GITPOD_WORKSPACE_URL as the `Access-Control-Allow-Origin` value.  As long as that only happened if `FREECODECAMP_NODE_ENV==development` then we could do that.

**Review by ojeytonwilliams — COMMENTED** [review]
Squiggly lines are back :+1: 

If @raisedadead is fine with my suggestion re: cors, could you do add that instead of making them public?  Otherwise, LGTM.

**Comment by raisedadead** [comment]
I am happy with @ojeytonwilliams 's recomendations.

**Comment by ShaunSHamilton** [comment]
@ojeytonwilliams I am a bit confused, because it looks like we are doing it already: https://github.com/freeCodeCamp/freeCodeCamp/blob/main/api-server/src/server/middlewares/constant-headers.js#L13

**Comment by ojeytonwilliams** [comment]
> @ojeytonwilliams I am a bit confused, because it looks like we are doing it already: https://github.com/freeCodeCamp/freeCodeCamp/blob/main/api-server/src/server/middlewares/constant-headers.js#L13

Oh, you're quite right, we are. I'd forgotten that we were already setting `homeLocation` during initialization of GitPod.

I investigated a little more and it seems that private ports are only accessible inside that tab.  If you try to access them from another browser tab, they never even reach the server.

Since we're setting the CORS headers correctly and the gitpod URLs aren't publically accessibly by default, I'm reasonably confident this is fine.

**Review by ojeytonwilliams — APPROVED** [review]

**Review by raisedadead — APPROVED** [review]

**Pull request merged**
