### PR TITLE
Added new jQuery waypoint on modifying text/html

### LINKED ISSUE #4457: New jQuery Waypoint: Modifying Html
I think it would be useful preparation for the pomodoro and calculator projects to introduce .html() and .text() in the jQuery waypoint section

### PR DESCRIPTION
**Pull request by fraziern**
Adds a new Waypoint in the jQuery section of the map, covering .html() and .text().  closes #4457

### CODE REVIEW

**Comment by bugron** [comment]
@fraziern thanks for the PR. Please, remove "closes #4457" from the title and add it to the description.

**Comment by fraziern** [comment]
@bugron Done, thanks.

**Comment by SaintPeter** [comment]
Brilliant.  A solid contribution.  :+1:

**Comment by fraziern** [comment]
@SaintPeter Much appreciated, thanks for the quick review!

**Comment by SaintPeter** [comment]
Just as an aside, and I didn't think it was worth holding this up, but the `i`, `b`, and `u` tags are not really used anymore, except as an icon holder.  `em` has replaced `i`, and `strong` has replaced `b`.

It's probably fine for this sort of example, but it's part of the larger move to make HTML more structural, rather than structure and display.  `em` for "emphasis" is more of a classifier than specific display direction.

Kinda, anyway.  More here:
http://programmers.stackexchange.com/a/255588/199820

**Pull request merged**
