### PR TITLE
Created a file for "Basics of Raspberry Pi Stuffs"

### PR DESCRIPTION
**Pull request by kunal768**
The code contains two parts:
First part is simply blinking led (Blink time can be set by time.sleep(x) x for the number of seconds)
Second part is for pwm control for led brightness

- [x] I have read [freeCodeCamp's contribution guidelines](https://github.com/freeCodeCamp/freeCodeCamp/blob/master/CONTRIBUTING.md).
- [x] My pull request has a descriptive title (not a vague title like `Update index.md`)
- [x] My pull request targets the `master` branch of freeCodeCamp.
- [x] None of my changes are plagiarized from another source without proper attribution.
- [x] My article does not contain shortened URLs or affiliate links.

If your pull request closes a GitHub issue, replace the XXXXX below with the issue number.

Closes #XXXXX

### CODE REVIEW

**Comment by kunal768** [comment]
How do I merge this with the original branch and contribute to open-source??

**Review by kunal768 — COMMENTED** [review]
Just commented the second part of the code for proper running and understanding

**Comment by RandellDawson** [comment]
I reformatted to 2 space indention and added the correct folder name and index.md file.

**Comment by RandellDawson** [comment]
LGTM

**Comment by RandellDawson** [comment]
Thank you for your contribution to the page! 👍
We're happy to accept these changes, and look forward to future contributions. 🎉

**Comment by kunal768** [comment]
Thanks a lot sir !!!

**Pull request merged**
