### PR TITLE
Add: add forumTopicId to the rosetta-code challenge.

### LINKED ISSUE #38629: Add forum topic ID to rosetta challenges
I noticed that @NitronR has added a ton of content to mostly the rosetta code section (thanks BTW). You can see a [list of his PR's here](https://github.com/freeCodeCamp/freeCodeCamp/pulls?q=is%3Apr+author%3AnitronR+is%3Aclosed). I did forum search for a couple of the challenges and it looks like guide pages have been created, but I noticed that the `forumTopicId` wasn't added to many of the challenges. We should go through those PR's and add the `forumTopicId` field to the frontmatter and make sure a guide page is created. If the PR is getting large, it might be a good idea to break it up into several.

### PR DESCRIPTION
**Pull request by kushagra010**
Checklist:

- [x] I have read [freeCodeCamp's contribution guidelines](https://contribute.freecodecamp.org).
- [x] My pull request has a descriptive title (not a vague title like `Update index.md`)
- [x] My pull request targets the `master` branch of freeCodeCamp.
- [x] All the files I changed are in the same world language, for example: only English changes, or only Chinese changes, etc.

Closes #38629

### CODE REVIEW

**Comment by kushagra010** [comment]
Hi,
I am a beginner and wanted to contribute to this issue, I have made the required changes regarding forumTopicId. Please review it @moT01.
Thankyou.

**Comment by moT01** [comment]
Hey @kushagra010, thanks for the PR. Unfortunately, there's already a PR open to fix this and since it was in first, I think we should go with that one. We are just waiting on one last change for it. This PR does look good at first glance, but I haven't given it a proper review. You should look for issues labelled "help wanted", or ones that don't have a PR to fix them.

**Comment by kushagra010** [comment]
Thank you @moT01 for your review and guidance.

**Comment by raisedadead** [comment]
Hi @kushagra010 

I agree with Tom and I am going to have to close this, we understand you are interested in contributing, I recommend you start by giving the [guidelines for contributing](https://contribute.freecodecamp.org) a good read. This will ensure that your contributions follow our recommendations.

If you need help you can find us in the  [chat room](https://gitter.im/FreeCodeCamp/Contributors) or [subforum](https://www.freecodecamp.org/forum/c/contributors) for contributors.

**Comment by kushagra010** [comment]
Thank you @raisedadead for your review and guidance.

**Pull request closed without merging**
