### PR TITLE
fix: Update html tags to fix misalignment

### PR DESCRIPTION
**Pull request by kundan59**
- [x] I have read [freeCodeCamp's contribution guidelines](https://github.com/freeCodeCamp/freeCodeCamp/blob/master/CONTRIBUTING.md). yes
- [x] My pull request has a descriptive title (not a vague title like `Update index.md`) yes
- [x] My pull request targets the `master` branch of freeCodeCamp. yes
- [x] None of my changes are plagiarized from another source without proper attribution. yes
- [x] All the files I changed are in the same world language (for example: only English changes, or only Chinese changes, etc.) yes
- [x] My changes do not use shortened URLs or affiliate links. yes

Closes #XXXXX

### CODE REVIEW

**Comment by moT01** [comment]
Hmm, the tests should have completed by now.

**Comment by RandellDawson** [comment]
Closed/Reopened to re-trigger Travis.

**Comment by RandellDawson** [comment]
@raisedadead Any idea why Travis is taking so long?

**Comment by raisedadead** [comment]
Looks like somehow the webhooks did not fire or something. If the code is good, I can still override the status. The CI itself has completed. Let me know.

**Comment by RandellDawson** [comment]
@raisedadead Yes, this PR is good to go.

**Review by RandellDawson — APPROVED** [review]

**Comment by moT01** [comment]
In the future @kundan59, you should put the issue that your PR will close in the description area where it says "closes ######".  Just type the issue number in there and, when your PR gets merged, that issue will automatically be closed. Thanks 🎉

**Pull request merged**
