### PR TITLE
Correct both Snape's quote and translation

### PR DESCRIPTION
**Pull request by giuliannosbrugnera**
Quotation was a bit off and there were remaining English words in between the translated quote.

- [x] I have read [freeCodeCamp's contribution guidelines](https://github.com/freeCodeCamp/freeCodeCamp/blob/master/CONTRIBUTING.md).
- [x] My pull request has a descriptive title (not a vague title like `Update index.md`)
- [x] My pull request targets the `master` branch of freeCodeCamp.
- [x] None of my changes are plagiarized from another source without proper attribution.
- [x] My article does not contain shortened URLs or affiliate links.

If your pull request closes a GitHub issue, replace the XXXXX below with the issue number.

Closes #XXXXX

### CODE REVIEW

**Review by thecodingaviator — DISMISSED** [review]
Please fix merge conflict

**Comment by RandellDawson** [comment]
@thecodingaviator This PR has gone stale.

**Comment by giuliannosbrugnera** [comment]
Sorry for the delay @thecodingaviator and @RandellDawson. Merge conflict is fixed.

**Review by thecodingaviator — APPROVED** [review]
LGTM! Thanks!

**Comment by thecodingaviator** [comment]
Thanks for contributing to the freeCodeCamp repository. Congratulations on your first PR! 🎊 

Look forward to more contributions from you! ✈️

**Pull request merged**
