### PR TITLE
fix(client): unify keyboard shortcut for running tests

### LINKED ISSUE #46423: On macOS keyboard shortcut is shown as Ctrl+Enter instead of Cmd+Enter
### Describe the Issue

Even though on macOS it would seem that Ctrl+Enter does not work & Cmd+Enter does; website still tells you to use Ctrl+Enter.

I think this might end up being confusing for some - and should be fairly straightforward of a change.

### Affected Page

All coding pages

### Steps to Reproduce

You must use macOS for this issue.

1. Go to any coding challenge
2. Type your changes
3. You will see button underneath says "Check your code (Ctrl + Enter)"
4. Press Ctrl + Enter
5. Nothing will happen.
6. Press Cmd + Enter
7. Expected behaviour will occur.

### Expected behavior

It should tell the user correct shortcut (Cmd + Enter) instead of (Ctrl + Enter) depending on the platform.

### Screenshots

Screenshot 2022-06-09 at 16 52 28

### System

- Device: M1 MacBook Pro
- OS: macOS 12.0.1
- Browser: Safari
- Version: 15.1

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by tukantje**
Checklist:

- [X] I have read [freeCodeCamp's contribution guidelines](https://contribute.freecodecamp.org).
- [X] My pull request has a descriptive title (not a vague title like `Update index.md`)
- [X] My pull request targets the `main` branch of freeCodeCamp.
- [X] I have tested these changes either locally on my machine, or GitPod.

Closes #46423

### CODE REVIEW

**Comment by tugkankibar** [comment]
I've updated non English translations as well in here to use dynamic values; however not really sure how to align it with the crowdin. Since updated translations should coincide with this change; any opinions on this?

**Comment by raisedadead** [comment]
@tugkankibar thanks for reporting the issue and this PR. I am blocking this while we come to a consensus on the main issue, meanwhile please feel free to work on this PR as you see fit. 

Cheers :)

**Comment by ieahleen** [comment]
Hey @tugkankibar, are you still interested in continuing working on this? If so, please update the PR to solve the merge conflicts.

**Comment by tugkankibar** [comment]
@ieahleen unfortunately due to IRL commitments it is really hard to find the time for any open source work at this moment; happy to hand it over.

As far as the discussion goes on the issue itself this seems to need quite some time on it to figure it out and not a simple fix as this PR tries.

**Pull request closed without merging**
