### PR TITLE
feat(api): add :email unsubscribe/:email to the deprecated

### PR DESCRIPTION
**Pull request by Sboonny**
Checklist:

- [x] I have read and followed the [contribution guidelines](https://contribute.freecodecamp.org).
- [x] I have read and followed the [how to open a pull request guide](https://contribute.freecodecamp.org/#/how-to-open-a-pull-request).
- [x] My pull request targets the `main` branch of freeCodeCamp.
- [x] I have tested these changes either locally on my machine, or GitPod.

These endpoints are depercated in the old api too, so I have added them.

### CODE REVIEW

**Review by ojeytonwilliams — CHANGES_REQUESTED** [review]
They don't get much use, but they are still getting traffic so I think it's worth keeping the custom response, `unsubscribeDeprecated`

**Review by ojeytonwilliams — DISMISSED** [review]
These endpoints do not respond with JSON. They redirect the browser to the client with a query param that includes the flash message.


There's some discussion here: https://github.com/freeCodeCamp/freeCodeCamp/issues/50426 but I think we should talk about it again in today's meeting.

**Comment by ojeytonwilliams** [comment]
@Sboonny since we've confirmed the "clone the old api wherever possible" plan, we should use the redirects here.

If you like, I'd be happy to create a quick PR/push a commitw `redirectWithFlash`.

**Comment by ojeytonwilliams** [comment]
Once https://github.com/freeCodeCamp/freeCodeCamp/pull/50525 is in, we can update this to use `redirectWithMessage`

**Review by Sembauke — APPROVED** [review]

**Review by moT01 — APPROVED** [review]

**Pull request merged**
