### PR TITLE
fix(learn): Add tab text hover color on mobile

### LINKED ISSUE #37137: tab text should be visible on mobile
to reproduce, view any lesson in a screen narrower than 750px and hover on a tab

Screen Shot 2019-10-09 at 11 21 29 AM

### PR DESCRIPTION
**Pull request by ghost**
- [x] I have read [freeCodeCamp's contribution guidelines](https://github.com/freeCodeCamp/freeCodeCamp/blob/master/CONTRIBUTING.md).
- [x] My pull request has a descriptive title (not a vague title like `Update index.md`)
- [x] My pull request targets the `master` branch of freeCodeCamp.
- [x] None of my changes are plagiarized from another source without proper attribution.
- [x] All the files I changed are in the same world language (for example: only English changes, or only Chinese changes, etc.)
- [x] My changes do not use shortened URLs or affiliate links.

Closes #37137 by adding `var(--secondary-background)` color on hover state via specific selector. I had tested this on my local dev.

### CODE REVIEW

**Comment by scissorsneedfoodtoo** [comment]
Thank you for working on this @rickysyamsi.

Everything looks good in night mode:

image

But unfortunately, the text is now washed out while hovering over the tabs in day mode:

image

The problem seems to be that the tabs at the top break convention in day mode. Instead of acting like the buttons at the bottom of the screen (Help, Video, and so on) where hovering causes a dark blue background with white text, the hovering over the tabs at the top results in a light grey background and dark text. That said, I do like how subtle the light grey is at the top.

An easy fix would be to set the color when hovering to `var(--gray-85)`, which should look fine in both day and night mode. Or we could consider reworking the tabs to to behave more like the buttons at the bottom.

What do you think, @rickysyamsi and @ahmadabdolsaheb?

**Comment by rickysyamsi** [comment]
@scissorsneedfoodtoo My bad, I'm sorry. I forgot to test it again in day mode. Thank you for testing it :)

I had followed your suggestion to change the color to `var(--gray-85)`. I had tested it on both day and night mode this time. It looks great on both mode.

I think that reworking the tabs to behave and look more like buttons at the bottom is not a good idea. I think this current implementation is already aligned with most users' expectation when interacting with it.

Those tabs are already looking like tabs with subtler border. Users should expect it to change display on screen (navigating between Info, Code, Tests, and Preview screens) instead of doing action like buttons.

Vice versa, those buttons at the bottom are already looking like buttons with thicker border. Users should expect it to do action (seek Help, open Video, get Hint, Reset editor, Run code) or open related modal window.

In my opinion, tabs and buttons should behave and look different because they are serving different purpose.

**Comment by ahmadabdolsaheb** [comment]
LGTM

**Comment by scissorsneedfoodtoo** [comment]
@rickysyamsi, no need to apologize! I almost missed it myself.

I agree with your assessment about the tabs and that we should leave them the way they are now. Very good points all around.

Thank you for your quick fix here, @rickysyamsi. Happy coding :100: :1st_place_medal:

**Pull request merged**
