### PR TITLE
Solution using RegExp

### PR DESCRIPTION
**Pull request by spassaro80**
I think it can be interesting to propose a solution using RegExp.

- [ x] I have read [freeCodeCamp's contribution guidelines](https://github.com/freeCodeCamp/freeCodeCamp/blob/master/CONTRIBUTING.md).
- [ x] My pull request has a descriptive title (not a vague title like `Update index.md`)
- [ x] My pull request targets the `master` branch of freeCodeCamp.
- [x ] None of my changes are plagiarized from another source without proper attribution.
- [ x] All the files I changed are in the same world language (for example: only English changes, or only Chinese changes, etc.)
- [ x] My changes do not use shortened URLs or affiliate links.

Closes #XXXXX

### CODE REVIEW

**Review by thecodingaviator — COMMENTED** [review]
I don't think we're accepting any more guide PRs

**Comment by thecodingaviator** [comment]
cc: @RandellDawson close at discretion

**Comment by RandellDawson** [comment]
Congrats @spassaro80  on your first pull request (PR)! 🎉

Thank you for your contribution to the page! 👍
We're happy to accept these changes, and look forward to future contributions. 📝

**Review by RandellDawson — APPROVED** [review]

**Comment by RandellDawson** [comment]
@spassaro80 We merged this PR, but the solution may or may not be used in the hints/solutions.  The current guide folder no longer reflects what will appear in the guide.  All the hints/solutions have been moved to the forum and will show up on challenges once the master branch has been deployed to production.

**Pull request merged**
