### PR TITLE
fix(e2e): reduce test flakiness

### PR DESCRIPTION
**Pull request by gikf**
Checklist:

- [x] I have read and followed the [contribution guidelines](https://contribute.freecodecamp.org).
- [x] I have read and followed the [how to open a pull request guide](https://contribute.freecodecamp.org/#/how-to-open-a-pull-request).
- [x] My pull request targets the `main` branch of freeCodeCamp.
- [x] I have tested these changes either locally on my machine, or GitPod.

Ref #49966

---

- The test flakiness I've found was caused by test navigating via UI to _second_ page and then back to _first_ page. However if test attempt failed when being on the _second_ page, in next attempts test tried on the _second_ page assertions intended for the _first_ page, which would fail. Moving `cy.visit` to `beforeEach` ensures, that in case of failed attempt, test will start next attempt on the _first_ page.
- Second issue is addressed in comment below.

### CODE REVIEW

**Comment by gikf** [comment]
I've tried various things to get test fail locally for the same reason, but unsuccessfully:
- Using development build: `pnpm run develop` + `pnpm run cypress:dev:watch`.
- Using production build: `pnpm run build` then `pnpm start` + `pnpm run cypress:dev:watch`.
- Using different node versions (cypress uses v16.16 as runner).

I haven't had a single issue with test failing due to saved text, not being there. Once monaco editor was loaded (`.react-monaco-editor-container`), expected text always was present.

In the CI run, expected api requests are being made, editor is displayed, but text somehow is still missing.

Baffling. Any ideas?

**Comment by raisedadead** [comment]
Yeah - running tests locally has been tricky lately (since the pnpm) move. @ojeytonwilliams, do you know the best way to address the query above?

**Comment by gikf** [comment]
> Yeah - running tests locally has been tricky lately (since the pnpm) move.

I figured that out already, tests are failing specifically on headless firefox. To run that locally `--browser firefox` needs to be added to cypress run command, ie.:
`pnpm run cypress:dev:run --browser firefox`

**Comment by ojeytonwilliams** [comment]
I'm afraid I hardly ever used `cypress run` locally - I relied on `open` pretty much exclusively, so I never noticed the change when we moved to `pnpm`. If you can give me a little more context about what seems to have changed, I can dig into it.

> I figured that out already, tests are failing specifically on headless firefox.

They're failing like they do in CI? Or some (unhelpful) new way?

**Review by ojeytonwilliams — APPROVED** [review]
LGTM :+1: 

I won't pretend to understand why Firefox is having issues, but the changes all seem reasonable. Cheers, @gikf!

**Review by Sembauke — APPROVED** [review]

**Pull request merged**
