### PR TITLE
fix(curriculum) ignore spacing around binary operator

### LINKED ISSUE #54506: Test too strict in step 27 of Luhn Algorithm project
### Describe the Issue

The test for this step requires to add spaces around the comparison operator:
```py
if number >= 10:
    print(number)
```

### Affected Page

https://www.freecodecamp.org/learn/scientific-computing-with-python/learn-how-to-work-with-numbers-and-strings-by-implementing-the-luhn-algorithm/step-27

### Your code

```py
if number>=10:
    print(number)
```

### Expected behavior

The test should pass even when there's no space around `>=`.

### Screenshots

_No response_

### System

- Device: [e.g. iPhone 6, Laptop]
- OS: [e.g. iOS 14, Windows 10, Ubuntu 20.04]
- Browser: [e.g. Chrome, Safari]
- Version: [e.g. 22]

### Additional context

It would be nice to rewrite the test using the new [ast-based helpers](https://opensource.freecodecamp.org/curriculum-helpers/python.html#ast-based-helpers).

### PR DESCRIPTION
**Pull request by Supravisor**
Checklist:

- [x] I have read and followed the [contribution guidelines](https://contribute.freecodecamp.org).
- [x] I have read and followed the [how to open a pull request guide](https://contribute.freecodecamp.org/#/how-to-open-a-pull-request).
- [x] My pull request targets the `main` branch of freeCodeCamp.
- [] I have tested these changes either locally on my machine, or GitPod.

Closes #54506

Received an error message.  Regex works on www.regex101.com

### CODE REVIEW

**Comment by ilenia-magoni** [comment]
instead of using regex, would you feel up to using the ast-based helpers? it can be a bit complex, but it would avoid any of these spacing issues and making sure that the regex account for any valid way of writing that

**Review by majestic-owl448 — CHANGES_REQUESTED** [review]
please use ast based helpers

**Comment by Supravisor** [comment]
Used ast helper tool to work out escape characters are removed

**Comment by zairahira** [comment]
The ast-based test would look like this:

````md
You should have `if number >= 10:` within the `for` loop.

```js
({
    test: () => 
    {
        assert(runPython(`_Node(_code).find_function("verify_card_number").find_for_loops()[1].find_ifs()[0].find_conditions()[0].is_equivalent("number >= 10")`));
    }
})

```
````

**Comment by Supravisor** [comment]
Passing tests for spacing, failing 4 CI checks
image
image

**Review by Supravisor — COMMENTED** [review]
Receiving four CI Node.js errors.
image

**Pull request closed without merging**
