### PR TITLE
refactor(challenges): Change "Hashing Your Password" desc

### LINKED ISSUE #16072: [Beta] Regarding Best Practice in Hashing Your Passwords
#### Hashing Your Passwords

https://beta.freecodecamp.org/en/challenges/advanced-node-and-express/hashing-your-passwords

#### Issue Description
I think the following should be reviewed as, if I'm not mistaken, they are not considered best practice for implementing password hashing:

* A cost factor of 8 is apparently too small nowadays
* `bcrypt.hashSync()`, as the challenge points out, is thread-blocking. Given that `bcrypt.hash()` is async (also recommended in the bcrypt documentation) and available out of the box, it doesn't seem to make much sense to not introduce the latter in the challenge instead. In fact, asynchronous hashing is introduced in an [earlier challlenge](https://beta.freecodecamp.org/en/challenges/information-security-with-helmetjs/hash-and-compare-passwords-asynchronously) using a cost factor of 12

#### Reference
https://hackernoon.com/your-node-js-authentication-tutorial-is-wrong-f1a3bf831a46

### PR DESCRIPTION
**Pull request by QuentinGibson**
Change description of "Hashing Your Passwords" to use the async API
of Bcrypt and updated the cost to 12

#### Pre-Submission Checklist

- [x] Your pull request targets the `staging` branch of freeCodeCamp.
- [x] Branch starts with either `fix/`, `feature/`, or `translate/` (e.g. `fix/signin-issue`)
- [x] You have only one commit (if not, [squash](http://forum.freecodecamp.org/t/how-to-squash-multiple-commits-into-one-with-git/13231) them into one commit).
- [x] All new and existing tests pass the command `npm test`. Use `git commit --amend` to amend any fixes.

#### Type of Change

- [ ] Small bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds new functionality)
- [ ] Breaking change (fix or feature that would change existing functionality)
- [ ] Add new translation (feature adding new translations)

#### Checklist:

- [x] Tested changes locally.
- [x] Addressed currently open issue (replace XXXXX with an issue no in next line)

Closes #16072 

#### Description

Change description of "Hashing Your Passwords" to use the aysnc API
of Bcrypt and updated the cost to 12

### CODE REVIEW

**Comment by QuentinGibson** [comment]
I use "commit" npm script to write my commit. Should I ignore the camperbot message?

**Comment by raisedadead** [comment]
> I use "commit" npm script to write my commit. Should I ignore the camperbot message?

Yes, looks like our camper-gh-bot has not been deployed to the latest version, thanks for the reminder.
/cc @BerkeleyTrue

**Comment by BerkeleyTrue** [comment]
@raisedadead Thanks for letting me know. It was indeed way out of date. I've updated it to our fork. Keep up the good work!

**Comment by QuincyLarson** [comment]
@QuentinGibson Thanks for fixing this aspect of the tutorial. 

@Em-Ant @JosephLivengood do we need to update the Glitch.com project to reflect these changes?

**Comment by Em-Ant** [comment]
I'm not up-to-date anymore on this projects (sorry @QuincyLarson ), and this was originally made by Angelos, but I've had a look at the relative glitch app and I think that it is in the 'starting point' state, so no code using bcrypt is added there. You probably need to change the glitch projects for the following steps, because they should contain that section.

**Pull request merged**
