### PR TITLE
fix(curriculum): alter description of build a city skyline step 102

### LINKED ISSUE #47555: feedback on Learn Css Variables By Building A City Skyline
### Describe the Issue

this project assumes you haven't worked with Flexbox yet hence it just givesyou the code without it being a real challenge/test.

### Affected Page

https://www.freecodecamp.org/learn/2022/responsive-web-design/learn-css-variables-by-building-a-city-skyline

### Your code

```
none
```

### Expected behavior

just to be given directions about what to do (as per usual) without giving you all the lines of code.

### Screenshots

Screenshot at 2022-09-18 15-46-28

### System

- Device: Zenbook
- OS: Linux Mint 20.3
- Browser: Brave
- Version: v1.43.93

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by wizardlekic**
Checklist:

- [x] I have read [freeCodeCamp's contribution guidelines](https://contribute.freecodecamp.org).
- [x] My pull request has a descriptive title (not a vague title like `Update index.md`)
- [x] My pull request targets the `main` branch of freeCodeCamp.
- [x] I have tested these changes either locally on my machine, or GitPod.

Ref #47555

Changes the description in build a city skyline to be less direct with the solution, as the learner is expected to already be familiar with flexbox from a previous project.

### CODE REVIEW

**Review by naomi-lgbt — APPROVED** [review]
banger pr, thanks for contributing!

**Comment by naomi-lgbt** [comment]
Heya @WizardLemon it looks like this was accidentally closed?

**Comment by WizardLemon** [comment]
@naomi-lgbt I was clearing up some older repositories I commited to and accidentally deleted the freeCodeCamp fork as well 🤦 

I'll put it back up and reopen it again, my bad 😅

**Review by Sboonny — APPROVED** [review]
LGTM 🎉, thank you for your contribution to the page! 👍.

**Pull request merged**
