### PR TITLE
feat(tools): Flex and Spacer components - UI Components

### PR DESCRIPTION
**Pull request by sirasitxp**
Checklist:

- [X] I have read [freeCodeCamp's contribution guidelines](https://contribute.freecodecamp.org).
- [X] My pull request has a descriptive title (not a vague title like `Update index.md`)
- [X] My pull request targets the `main` branch of freeCodeCamp.
- [X] I have tested these changes either locally on my machine, or GitPod.

This is related to issue #44668 

Clear part of Chapter components https://github.com/freeCodeCamp/chapter/issues/1143

### CODE REVIEW

**Review by Sboonny — CHANGES_REQUESTED** [review]
Can you delete client/core.3149 file from the commit? these aren't needed in the repo

**Comment by hisnameispum** [comment]
> Can you delete client/core.3149 file from the commit? these aren't needed in the repo

Just did! Let me know if there is anything else to be done.

**Comment by raisedadead** [comment]
#### :sparkles: :sparkles: **AWESOME!** :sparkles: :sparkles: 

LGTM.

Thanks for this pull request and for contributing to the codebase for the first time. We will be looking forward to more contributions in the future.

Happy contributing.

**Comment by ahmadabdolsaheb** [comment]
Thanks for the pull request. 

We are focusing on completing the https://github.com/freeCodeCamp/freeCodeCamp/issues/44668 requirements list for the first phase of the component library. 

If you are still interested in contributing to component library, I suggest developing to the remaining components on the list first.

Note: the component library will be used in Chapter. As a result, building any component count as contributing to Chapter.

**Review by ahmaxed — APPROVED** [review]

**Pull request merged**
