### PR TITLE
fix(styling): update class name of challenge wrapper to new convention

### PR DESCRIPTION
**Pull request by no-stack-dub-sack**
#### Pre-Submission Checklist

- [x] Your pull request targets the `staging` branch of freeCodeCamp.
- [x] Branch starts with either `fix/`, `feature/`, or `translate/` (e.g. `fix/signin-issue`)
- [x] You have only one commit (if not, [squash](http://forum.freecodecamp.com/t/how-to-squash-multiple-commits-into-one-with-git/13231) them into one commit).
- [x] All new and existing tests pass the command `npm test`. Use `git commit --amend` to amend any fixes.

#### Type of Change

- [x] Small bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds new functionality)
- [ ] Breaking change (fix or feature that would change existing functionality)
- [ ] Add new translation (feature adding new translations)

#### Checklist:

- [x] Tested changes locally.
- [ ] Closes currently open issue (replace XXXX with an issue no): Closes #XXXX

#### Description

This PR updates a fix I made in a previous PR: #13164 to make styling of backend challenges consistent with the rest of the app. 

In the linked PR, the class name "challenge-instructions" was added to give `code`, `dfn` and `blockquote` tags the right styling. But that classname has been changed to "classic-instructions" so the change I made was rendered ineffective. 

This updates the className to the new naming convention and fixes the styles again (in both regular and night-mode). 

Current:
image

Updated:
image

### CODE REVIEW

**Comment by BerkeleyTrue** [comment]
@no-stack-dub-sack This will couple the backend challenges view to closely to the challenges style file.

That recent refactor some of the styles and I was not able to find the places where css was defined in relation to the components. Many css classes where no longer used. That PR was a step in the direction of eventually using css modules.

If the description of the backend challenges is the same used in the classic view, then we should abstract out the description into it's own component into the challenge directory and import it in this file.

**Comment by no-stack-dub-sack** [comment]
@BerkeleyTrue for the record, I almost got tricked and @mentioned @BerkeleyFalse 

Ok, cool - I see where you're going with the namespacing and think I can implement this. They are not quite the same, but really they are. The classic descriptions nested inside 
```
<Row><Col>...</Col></Row>
````
while the backend description is not, but this shouldn't make a difference to the Backend challenges layout. 

I'll close this PR in favor of the new one when I have it worked out. 

Only question would be, should I just import the namespace from the classic directory? That will keep the styles consistent but the namespace itself will be misleading. That's the simpler solution, but we could also move all of these styles to `challenges.less` and use that namespace since this would really apply to all challenges now, not just classic.  Thoughts?

**Comment by BerkeleyTrue** [comment]
Sounds good

**Comment by no-stack-dub-sack** [comment]
closing this PR in favor of #15022

**Pull request closed without merging**
