### PR TITLE
Update to Construct JavaScript Objects with Functions 

### LINKED ISSUE #4525: Issue with test suite description
Challenge [Waypoint: Construct JavaScript Objects with Functions](http://www.freecodecamp.com/challenges/waypoint-construct-javascript-objects-with-functions#?solution=var%20Car%20%3D%20function()%20%7B%0A%20%20this.wheels%20%3D%204%3B%0A%20%20this.engines%20%3D%201%3B%0A%20%20this.seats%20%3D%201%3B%0A%7D%3B%0A%0Avar%20myCar%20%3D%20new%20Car()%3B%0A%0A%2F%2F%20Only%20change%20code%20below%20this%20line.%0A%0Avar%20MotorBike%20%3D%20function()%20%7B%0A%20%20this.engines%20%3D%201%3B%0A%20%20this.wheels%20%3D%202%3B%0A%20%20this.seats%20%3D%201%3B%0A%7D%3B%0A) has an issue.
User Agent is: <code>Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/46.0.2490.86 Safari/537.36</code>.
Please describe how to reproduce this issue, and include links to screenshots if possible.

My code:
```javascript
var Car = function() {
  this.wheels = 4;
  this.engines = 1;
  this.seats = 1;
};

var myCar = new Car();

// Only change code below this line.

var MotorBike = function() {
  this.engines = 1;
  this.wheels = 2;
  this.seats = 1;
};

```

The user isn't required to instantiate an object of `MotorBike` as `myMotorBike` (like the `Car` example above) to proceed. I would have expected the code below in order to pass:
```javascript
var Car = function() {
  this.wheels = 4;
  this.engines = 1;
  this.seats = 1;
};

var myCar = new Car();

// Only change code below this line.

var MotorBike = function() {
  this.engines = 1;
  this.wheels = 2;
  this.seats = 1;
};

var myMotorBike = new MotorBike();

```

### PR DESCRIPTION
**Pull request by shadowfool**
fixes #4525

### CODE REVIEW

**Comment by SaintPeter** [comment]
@shadowfool Please change your title to be related to the issue you are fixing.  Also, your branch should be named in the format `fix/short-description-of-fix`.

Please review our [Contributing Guidelines](https://github.com/FreeCodeCamp/FreeCodeCamp/blob/staging/CONTRIBUTING.md).

**Comment by shadowfool** [comment]
Thanks @SaintPeter , I'll fix this and update the branching naming convention.

**Comment by bugron** [comment]
@shadowfool, please `squash` your commits info one commit.

**Comment by shadowfool** [comment]
@bugron, understood. Will practice this when I create the update with the proper naming convention.

**Comment by bugron** [comment]
OK. Also, note, that you can rewrite your last commit with `git commit --amend` command.

**Pull request closed without merging**
