### PR TITLE
feat(client): TypeScript via Merge-Party 🎉

### PR DESCRIPTION
**Pull request by raisedadead**
To be merged fast-forward. This PR is here to prevent any accidental deletions.

### CODE REVIEW

**Comment by ShaunSHamilton** [comment]
There is a very good chance we will want to revert #42285 . Not that I am doubting your PR-ability, Tom. Just that the changes we more extensive than a pure JS -> TS.

**Comment by moT01** [comment]
Everything seemed to be working. Is there anything more specific you are thinking of or concerned about? Probably the changes in the editor file, I suppose.

**Comment by ShaunSHamilton** [comment]
> Is there anything more specific you are thinking of or concerned about?

The refactor from class to functional component is what was most likely to go wrong.

**Comment by moT01** [comment]
I made a quick [draft PR](https://github.com/freeCodeCamp/freeCodeCamp/pull/42672) in case we want to revert it. But I'm not sure if it's necessary.

**Pull request merged**
