### PR TITLE
feat(client): change create store to legacy create store

### PR DESCRIPTION
**Pull request by Sboonny**
Checklist:

- [x] I have read and followed the [contribution guidelines](https://contribute.freecodecamp.org).
- [x] I have read and followed the [how to open a pull request guide](https://contribute.freecodecamp.org/#/how-to-open-a-pull-request).
- [x] My pull request targets the `main` branch of freeCodeCamp.
- [x] I have tested these changes either locally on my machine, or GitPod.

Redux errors in the tests are annoying to decipher, this PR reduces the noice in the test errors, doesn't improve anything tho

### CODE REVIEW

**Comment by ojeytonwilliams** [comment]
I've not looked into this in detail, but it looks like this PR will hide the problem rather than fixing it.

Since we can't be the only people running into this issue in testing, I recommend looking for some documentation on best practices for testing redux.

**Comment by Sboonny** [comment]
Installing redux/tooltip, that's the recommendation. to be honest, I am waiting for API to finish, to bring the topic about moving away from redux because it's providing terrible developer experience so far.

**Comment by ojeytonwilliams** [comment]
I'm not sure I understand the context. Is the issue you're describing currently the case on `main`? Also, could you share some of the confusing logs?

**Comment by Sboonny** [comment]
The issue isn't the main, I just want it to be similar to chapter, which I don't see deprecated message in every failed test.

You can see the issue in me, because I can't ignore these messages 🤔, if you want me to close this, I don't mind.

**Comment by raisedadead** [comment]
Is this moving forward?

**Comment by Sboonny** [comment]
I think if we using redux/tooltips, we need to migrate to react 17 or 18, I am closing it for now and will come back to it when React is updated

**Pull request closed without merging**
