### PR TITLE
fix(curriculum): clarify instructions for cafe menu step 41

### PR DESCRIPTION
**Pull request by bbsmooth**
Checklist:

- [x] I have read [freeCodeCamp's contribution guidelines](https://contribute.freecodecamp.org).
- [x] My pull request has a descriptive title (not a vague title like `Update index.md`)
- [x] My pull request targets the `main` branch of freeCodeCamp.
- [x] I have tested these changes either locally on my machine, or GitPod.

Closes #XXXXX

I've been seeing confusion on this step for a while now. I think it is similar to cat photo app step 6 in that they are not expecting the solution to be as easy as just moving an element up a line and thus are trying to make it more complicated than it really is. Spelling it out in the instructions should hopefully alleviate any misunderstandings.

### CODE REVIEW

**Comment by Sembauke** [comment]
Hey Bruce,

I am not sure about this change, the reason is that the 'price' and 'flavor' class are now translatable. Also saying that the user needs to use the backspace key seems a bit excessive to me.

> Instead, use the back space key on your keyboard to move the price `p` element so that it is on the same line as the flavor `p` element. 

I will make the following suggestion:
> Instead, move the `p` element with the class `price` next to the `p` element with the class `flavor` so that they are displayed on the same line.

**Comment by bbsmooth** [comment]
I was just using the wording that the current step uses. It uses "move the price `p` element". But changing that to "move the `p` element with the class price" is fine with me.

> Also saying that the user needs to use the backspace key seems a bit excessive to me.

Agreed, but that's the intent. I wouldn't think we would need to spell it out like this, but from the posts I've seen in the forums, I think we do. We did the same thing for cat photo app step 6. This step is so simple that I think people make it harder than it is because they don't believe that the solution is that easy. So spelling it out for them is just a way to clarify that it is indeed that easy.

> "...so that they are displayed on the same line."

I think this has the potential to be confusing. They are displayed on the same line in the preview window. I think this phrase leaves ambiguity between whether we mean the editor or the preview window. Perhaps something like:

> Instead, use the back space key on your keyboard to move the `p` element with the class `price` next to the `p` element with the class `flavor` so that they are on the same line in the editor.

**Comment by Sembauke** [comment]
> Instead, use the back space key on your keyboard to move the p element with the class price next to the p element with the class flavor so that they are on the same line in the editor.

This sounds good to me.

**Review by Sembauke — APPROVED** [review]

**Comment by Sembauke** [comment]
Thank you for taking this on Bruce, hopefully the learners will now understand the full context of this challenge.

**Review by moT01 — APPROVED** [review]
I'm fine with this change for now. I remember this step - seems like this maybe needs a slight rework or something. There's gotta be a way to do it without this goofy step. Maybe another time.

LGTM @bbsmooth 🎉

**Comment by bbsmooth** [comment]
@moT01 Agreed, kind of goofy, and you would probably never use this approach, but rather flexbox. But I understand that flexbox isn't introduced until a later course and so they couldn't use it here.

**Pull request merged**
