### PR TITLE
Added the missing "to" to fix issue.

### LINKED ISSUE #14403: Missing "to" from "less than or equal the"
Challenge [Comparison with the Less Than Or Equal To Operator](https://www.freecodecamp.com/challenges/comparison-with-the-less-than-or-equal-to-operator) has an issue.
User Agent is: <code>Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:52.0) Gecko/20100101 Firefox/52.0</code>.
Please describe how to reproduce this issue, and include links to screenshots if possible.

This line is missing "to":
If the number to the left is less than or equal the number to the right, it returns true.

It should be worded like this:
If the number to the left is less than or equal to the number to the right, it returns true.

Screenshot:
screenshot

### PR DESCRIPTION
**Pull request by Ellyria**
#### Pre-Submission Checklist

- [*] Your pull request targets the `staging` branch of freeCodeCamp.
- [*] Branch starts with either `fix/`, `feature/`, or `translate/` (e.g. `fix/signin-issue`)
- [*] You have only one commit (if not, [squash](http://forum.freecodecamp.com/t/how-to-squash-multiple-commits-into-one-with-git/13231) them into one commit).
- [x] All new and existing tests pass the command `npm test`. Use `git commit --amend` to amend any fixes.

NOTE: I wasn't able to check off this last box because I did the change on-line rather than on my computer. For the record, the only change made to the file was the addition of one word of text in an area that contains text. I didn't change any JavaScript or other code.

#### Type of Change

- [*] Small bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds new functionality)
- [ ] Breaking change (fix or feature that would change existing functionality)
- [ ] Add new translation (feature adding new translations)

#### Checklist:

- [x] Tested changes locally.
- [*] Closes currently open issue (replace XXXX with an issue no): Closes #14403

#### Description

Added "to" to the sentence in question in issue 14403.

### CODE REVIEW

**Comment by dhcodes** [comment]
@Ellyria Tested locally and **LGTM**. Congratulations on making your first contribution to freeCodeCamp! 👍 💯 🎉

**Comment by Ellyria** [comment]
Yay, thanks to everyone for all the help!

**Comment by Ellyria** [comment]
When does the fix show up? If I go to the https://www.freecodecamp.com/challenges/comparison-with-the-less-than-or-equal-to-operator page, it's still the way it was. Do these bug fixes go to a future version that won't go live until later?

**Comment by dhcodes** [comment]
@Ellyria the beta site is updated every couple of weeks based on the newly merged PRs. It will be there eventually.

**Pull request merged**
