### PR TITLE
Edit Intermediate Solution

### PR DESCRIPTION
**Pull request by akhilomar**
There is a bug for "https://guide.freecodecamp.org/certifications/javascript-algorithms-and-data-structures/intermediate-algorithm-scripting/pig-latin/" for intermediate solution. I have provide the correction of the issue in this repo. Please consider this issue and edit accordingly.

- [x] I have read [freeCodeCamp's contribution guidelines](https://github.com/freeCodeCamp/freeCodeCamp/blob/master/CONTRIBUTING.md).
- [x] My pull request has a descriptive title (not a vague title like `Update index.md`)
- [x] My pull request targets the `master` branch of freeCodeCamp.
- [x] None of my changes are plagiarized from another source without proper attribution.
- [x] All the files I changed are in the same world language (for example: only English changes, or only Chinese changes, etc.)
- [x] My changes do not use shortened URLs or affiliate links.

Closes #XXXXX

### CODE REVIEW

**Comment by RandellDawson** [comment]
@akhilomar First please read and check the boxes above to let us know you have read them.

Also, if you are making a "fix" to the code, just make the fix.  Instead, you have explained what is wrong with the code and added more code instead of just replacing the code you believe has an issue.

**Comment by akhilomar** [comment]
Sir, I have read and checked all the boxes.
In the present repo. of this question, the intermediate solution provided in repository is different from the intermediate hint present on "https://guide.freecodecamp.org/certifications/javascript-algorithms-and-data-structures/intermediate-algorithm-scripting/pig-latin/", due to which I have to explained it 
separately. 
Now I have fix the intermediate code with recursion condition. You can review it.

**Comment by moT01** [comment]
I don't see a bug in the current intermediate solution.. Am I missing something?

[This is a preview of your changes](https://github.com/freeCodeCamp/freeCodeCamp/blob/3e50c7ee15003b212ab5299a22153b1a5d374185/guide/english/certifications/javascript-algorithms-and-data-structures/intermediate-algorithm-scripting/pig-latin/index.md) - Your code does not look good. See the [style guide](https://github.com/freeCodeCamp/freeCodeCamp/blob/master/docs/style-guide-for-guide-articles.md#code-blocks)

**Comment by akhilomar** [comment]
> I don't see a bug in the current intermediate solution.. Am I missing something?
> 
> [This is a preview of your changes](https://github.com/freeCodeCamp/freeCodeCamp/blob/3e50c7ee15003b212ab5299a22153b1a5d374185/guide/english/certifications/javascript-algorithms-and-data-structures/intermediate-algorithm-scripting/pig-latin/index.md) - Your code does not look good. See the [style guide](https://github.com/freeCodeCamp/freeCodeCamp/blob/master/docs/style-guide-for-guide-articles.md#code-blocks)

**Comment by akhilomar** [comment]
Please refer intermediate solution of this link instead of repo solution: https://guide.freecodecamp.org/certifications/javascript-algorithms-and-data-structures/intermediate-algorithm-scripting/pig-latin/

In the above links solution you will find the solution using recursion in intermediate section. There terminating condition in recursion function is not provided due to which "Maximum call stack size exceeded" occurs.
 
That's what I want to convey by this PR

**Comment by moT01** [comment]
I see - well, it is no longer a problem on the master branch of the repo. But I don't mind adding your solution if you want since all the other solutions use regex. But you will need to format the code using backticks like described in the link I gave above.

**Pull request closed without merging**
