### PR TITLE
 refactor(server): Remove opbeat from dev tools

### LINKED ISSUE #17176: Remove all Opbeat Logging
opbeat-closing

We still have Opbeat on the server, we should remove it as it will not be very helpful next week.

This issue is a good fit for anyone that can delete code :grin:

### PR DESCRIPTION
**Pull request by tamj0rd2**
Closes #17176

#### Pre-Submission Checklist

- [X] Your pull request targets the `staging` branch of freeCodeCamp.
- [X] Branch starts with either `fix/`, `feature/`, or `translate/` (e.g. `fix/signin-issue`)
- [X] You have only one commit (if not, [squash](http://forum.freecodecamp.org/t/how-to-squash-multiple-commits-into-one-with-git/13231) them into one commit).
- [X] All new and existing tests pass the command `npm test`. Use `git commit --amend` to amend any fixes.

#### Type of Change

- [x] Small bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds new functionality)
- [ ] Breaking change (fix or feature that would change existing functionality)
- [ ] Add new translation (feature adding new translations)

#### Checklist:

- [X] Tested changes locally.
- [X] Addressed currently open issue (replace XXXXX with an issue no in next line)

Closes #17176

### CODE REVIEW

**Comment by Bouncey** [comment]
@tamj0rd2 I looks like you've had some git issues. Try doing a rebase on your changes

`git pull --rebase upstream staging`

**Review by josecarlos0706 — APPROVED** [review]

**Comment by raisedadead** [comment]
Ready for QA.

**Review by raisedadead — CHANGES_REQUESTED** [review]
Hmm this does not seemingly update the lockfile. I'll do that in a while

**Comment by Bouncey** [comment]
@tamj0rd2 you would need to run the command `npm remove opbeat` so the lock file can be updated :+1:

**Comment by tamj0rd2** [comment]
@Bouncey hey, I did run that command but it only updated the package.json and not the lock file.

**Review by Bouncey — APPROVED** [review]

**Comment by Bouncey** [comment]
Thanks @tamj0rd2 @raisedadead :+1:

**Pull request merged**
