### PR TITLE
chore(curriculum): strandize links in projects

### PR DESCRIPTION
**Pull request by Sboonny**
Checklist:

- [x] I have read [freeCodeCamp's contribution guidelines](https://contribute.freecodecamp.org).
- [x] My pull request has a descriptive title (not a vague title like `Update index.md`)
- [x] My pull request targets the `main` branch of freeCodeCamp.
- [x] I have tested these changes either locally on my machine, or GitPod.

<s> this pr will be focus on the rest of the projects</s> for #39739

### CODE REVIEW

**Comment by raisedadead** [comment]
The OP says:

> this pr will be focus on the rest of the projects for ...

Are you done with it?

**Comment by Sboonny** [comment]
Yes it's ready, hopefully I didn't miss anything

**Review by raisedadead — APPROVED** [review]
LGTM. We should be able to add some form of custom linting at some point to make our lives easier.

**Comment by raditotev** [comment]
Hi @Sboonny. I found some links still using the markdown style:
```
[here](https://gist.github.com/camperbot/<commit-number>)
[tutorial](https://www.freecodecamp.org/news/get-started-with-mongodb-atlas/)
[OAuth applications](https://github.com/settings/developers)
[this GitHub repo](https://github.com/freeCodeCamp/boilerplate-advancednode/)
[our Replit starter project](https://replit.com/github/freeCodeCamp/boilerplate-advancednode)
[Replit](https://replit.com/github/freeCodeCamp/boilerplate-mochachai)
[GitHub](https://github.com/freeCodeCamp/boilerplate-mochachai/)
[Falsy Bouncer](https://www.freecodecamp.org/learn/javascript-algorithms-and-data-structures/basic-algorithm-scripting/falsy-bouncer)
```
The above are from `curriculum/challenges/english/06-quality-assurance/**/*.md`.
Is this intentional?

**Comment by raditotev** [comment]
Thanks @Sboonny. I wasn't sure what `the rest of the projects` mean. Now I think I do. This means all the files in the following folders:
```
curriculum/challenges/english/06-quality-assurance/quality-assurance-projects/
curriculum/challenges/english/07-scientific-computing-with-python/scientific-computing-with-python-projects/
curriculum/challenges/english/08-data-analysis-with-python/data-analysis-with-python-projects/
curriculum/challenges/english/09-information-security/information-security-projects/
curriculum/challenges/english/11-machine-learning-with-python/machine-learning-with-python-projects/
```
If I am correct in my assumption then it all looks good.

**Review by raditotev — APPROVED** [review]

**Comment by Sboonny** [comment]
> If I am correct in my assumption then it all looks good.

Yes, you are 

thanks for checking it out. It makes me happy knowing that I didn't miss something 💚

**Pull request merged**
