### PR TITLE
feat: update learn intro

### LINKED ISSUE #37701: font should look the same on /news and /learn
Although fonts in learn and news share the same size, and weight, they look different on learn and on news.

the Navigation is a good example
image

a good place to start the investigation would be the global and screen css files for the ghost theme.

https://github.com/freeCodeCamp/news-theme/blob/master/assets/css/global.css
https://github.com/freeCodeCamp/news-theme/blob/master/assets/css/screen.css

### PR DESCRIPTION
**Pull request by raisedadead**

### CODE REVIEW

**Review by ojeytonwilliams — DISMISSED** [review]
LGTM :+1: 

Would it be worth showing this to signed in users until they've completed a few challenges?  I.e. what we do for `If you are new to coding, we recommend you start at the beginning.`.

**Comment by ahmadabdolsaheb** [comment]
just changed it to Lato for readability and made it wider on smaller screens.
Screen Shot 2020-08-11 at 12 24 47 PM

As Oliver said. new users who sign in will completely miss this info. Should we have it in an expandable div on /learn for singed in users and have it around until the user completes a certain number of challenges?

**Review by ahmaxed — DISMISSED** [review]

**Review by fear018 — DISMISSED** [review]

**Comment by raisedadead** [comment]
@ojeytonwilliams @ahmadabdolsaheb 

For the queries, please ping @QuincyLarson who seems to be less active on GitHub and misses the clarifications needed. 

Merge when you are happy.

**Comment by QuincyLarson** [comment]
@raisedadead I just met with @ahmadabdolsaheb on this, and he is going to make the text a bit larger like it is on Ghost.

We are also going to make this an additional step for campers during the new account creation flow. It will go like this:

1. Sign in (Auth0)
2. Check boxes for TOS, Privacy Policy, and weekly email blasts.
3. "Welcome to freeCodeCamp's curriculum" view
4. Normal /learn authenticated page

**Comment by raisedadead** [comment]
Sure, I will leave the PR as is for Ahmad to push updates to this. Thanks for confirming.

**Comment by ahmadabdolsaheb** [comment]
The last commit closes #37701;

**Comment by ahmadabdolsaheb** [comment]
image

**Review by ahmaxed — APPROVED** [review]

**Comment by raisedadead** [comment]
> We are also going to make this an additional step for campers during the new account creation flow. It will go like this:
> 
> 1. Sign in (Auth0)
> 2. Check boxes for TOS, Privacy Policy, and weekly email blasts.
> 3. "Welcome to freeCodeCamp's curriculum" view
> 4. Normal /learn authenticated page

These requirements were not satified?

**Comment by ahmadabdolsaheb** [comment]
These are to be addressed in another pr.

**Comment by raisedadead** [comment]
So do we block deployment? How long before the PR the next PR is ready?

**Comment by ahmadabdolsaheb** [comment]
No we don't need to block deployment. We would include the next features when they are ready. I will create issues with description.

**Comment by raisedadead** [comment]
Understood. Could you drop that these features are deffered in the team chat. This PR could have landed yesterday, but I was under the impression that these features are being worked upon.

**Pull request merged**
