### PR TITLE
fix(curriculum): added 3 new tests to mutations challenge

### PR DESCRIPTION
**Pull request by RandellDawson**
- [x] I have read [freeCodeCamp's contribution guidelines](https://github.com/freeCodeCamp/freeCodeCamp/blob/master/CONTRIBUTING.md).
- [x] My pull request has a descriptive title (not a vague title like `Update index.md`)
- [x] My pull request targets the `master` branch of freeCodeCamp.
- [x] None of my changes are plagiarized from another source without proper attribution.
- [x] All the files I changed are in the same world language (for example: only English changes, or only Chinese changes, etc.)
- [x] My changes do not use shortened URLs or affiliate links.

This PR is a result of reading through a [forum post](https://www.freecodecamp.org/forum/t/mutations-right-answer-but-dumb-code/317540/2) that had a solution suggested by a user which passed all the current challenge tests but did not meet the requirements of the challenge; instructions.  I have added 3 new tests which I believe make the challenge correctly reject invalid solutions such as the one below:
```js
function mutation(arr) {

  const smallerWord = arr[0].length <= arr[1].length
    ? arr[0]
    : arr[1]
  const biggerWord = smallerWord >= arr[0].length
    ? arr[1]
    : arr[0]
  const biggerWordArr = biggerWord.split('')
  const smallerWordArr = smallerWord.split('')

  return smallerWordArr
    .every(char => 
      biggerWordArr.indexOf(char) >= 0
    )
}
```

The above solution would correctly fail the 3 new tests.

### CODE REVIEW

**Review by ojeytonwilliams — APPROVED** [review]
LGTM :+1:

**Review by Manish-Giri — APPROVED** [review]
LGTM 👍

**Comment by eduardoflorendo** [comment]
#36947

**Comment by eduardoflorendo** [comment]
#36975

**Comment by eduardoflorendo** [comment]
#36926

**Pull request merged**
