### PR TITLE
Correct a typo.

### PR DESCRIPTION
**Pull request by shlomif**
#### Pre-Submission Checklist

- [x] Your pull request targets the `staging` branch of FreeCodeCamp.
- [x] Branch starts with either `fix/`, `feature/`, or `translate/` (e.g. `fix/signin-issue`)
- [x] You have only one commit (if not, [squash](http://forum.freecodecamp.com/t/how-to-squash-multiple-commits-into-one-with-git/13231) them into one commit).
- [npm generates an error] All new and existing tests pass the command `npm run test-challenges`. Use `git commit --amend` to amend any fixes.
#### Type of Change

- [x] Small bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds new functionality)
- [ ] Breaking change (fix or feature that would change existing functionality)
- [ ] Add new translation (feature adding new translations)
#### Checklist:

- [ ] Tested changes locally.
- [ ] Closes currently open issue (replace XXXX with an issue no): Closes #XXXX
#### Description

See https://github.com/FreeCodeCamp/FreeCodeCamp/issues/11034 .

### CODE REVIEW

**Comment by karuppiah7890** [comment]
Actually speaking you shouldn't have received any errors while doing tests using `npm run test`. Can you tell what errors you received ?

And your pull request does target the staging branch. Just put a tick there in the first item in the checklist.

**Comment by shlomif** [comment]
The output of npm run test is:

```

> freecodecamp@0.1.0 pretest /home/shlomif/Download/unpack/to-del/FreeCodeCamp
> npm run create-rev && npm run lint


> freecodecamp@0.1.0 create-rev /home/shlomif/Download/unpack/to-del/FreeCodeCamp
> node -e "var fs = require('fs'); fs.access('./server/rev-manifest.json', function(err) { if (err) { console.log('\n\ncreating manifest\n\n'); return fs.writeFileSync('server/rev-manifest.json', '{}'); } console.log('\n\nrev-manifest present\n\n'); });"



rev-manifest present



> freecodecamp@0.1.0 lint /home/shlomif/Download/unpack/to-del/FreeCodeCamp
> npm run lint-js && npm run lint-json


> freecodecamp@0.1.0 prelint-js /home/shlomif/Download/unpack/to-del/FreeCodeCamp
> npm run create-rev


> freecodecamp@0.1.0 create-rev /home/shlomif/Download/unpack/to-del/FreeCodeCamp
> node -e "var fs = require('fs'); fs.access('./server/rev-manifest.json', function(err) { if (err) { console.log('\n\ncreating manifest\n\n'); return fs.writeFileSync('server/rev-manifest.json', '{}'); } console.log('\n\nrev-manifest present\n\n'); });"



rev-manifest present



> freecodecamp@0.1.0 lint-js /home/shlomif/Download/unpack/to-del/FreeCodeCamp
> eslint --ext=.js,.jsx server/ common/ config/ client/

sh: eslint: command not found

npm ERR! Linux 4.7.5-desktop-1.mga6
npm ERR! argv "/usr/bin/node" "/usr/bin/npm" "run" "lint-js"
npm ERR! node v4.5.0
npm ERR! npm  v2.15.9
npm ERR! file sh
npm ERR! code ELIFECYCLE
npm ERR! errno ENOENT
npm ERR! syscall spawn
npm ERR! freecodecamp@0.1.0 lint-js: `eslint --ext=.js,.jsx server/ common/ config/ client/`
npm ERR! spawn ENOENT
npm ERR! 
npm ERR! Failed at the freecodecamp@0.1.0 lint-js script 'eslint --ext=.js,.jsx server/ common/ config/ client/'.
npm ERR! This is most likely a problem with the freecodecamp package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     eslint --ext=.js,.jsx server/ common/ config/ client/
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs freecodecamp
npm ERR! Or if that isn't available, you can get their info via:
npm ERR! 
npm ERR!     npm owner ls freecodecamp
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /home/shlomif/Download/unpack/to-del/FreeCodeCamp/npm-debug.log

npm ERR! Linux 4.7.5-desktop-1.mga6
npm ERR! argv "/usr/bin/node" "/usr/bin/npm" "run" "lint"
npm ERR! node v4.5.0
npm ERR! npm  v2.15.9
npm ERR! code ELIFECYCLE
npm ERR! freecodecamp@0.1.0 lint: `npm run lint-js && npm run lint-json`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the freecodecamp@0.1.0 lint script 'npm run lint-js && npm run lint-json'.
npm ERR! This is most likely a problem with the freecodecamp package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     npm run lint-js && npm run lint-json
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs freecodecamp
npm ERR! Or if that isn't available, you can get their info via:
npm ERR! 
npm ERR!     npm owner ls freecodecamp
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /home/shlomif/Download/unpack/to-del/FreeCodeCamp/npm-debug.log

npm ERR! Linux 4.7.5-desktop-1.mga6
npm ERR! argv "/usr/bin/node" "/usr/bin/npm" "run" "test"
npm ERR! node v4.5.0
npm ERR! npm  v2.15.9
npm ERR! code ELIFECYCLE
npm ERR! freecodecamp@0.1.0 pretest: `npm run create-rev && npm run lint`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the freecodecamp@0.1.0 pretest script 'npm run create-rev && npm run lint'.
npm ERR! This is most likely a problem with the freecodecamp package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     npm run create-rev && npm run lint
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs freecodecamp
npm ERR! Or if that isn't available, you can get their info via:
npm ERR! 
npm ERR!     npm owner ls freecodecamp
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /home/shlomif/Download/unpack/to-del/FreeCodeCamp/npm-debug.log

```

I'm on Mageia v6 x86-64.

**Comment by hristijankiko** [comment]
You might need to update your Node to 6+ and npm to 3+

**Comment by karuppiah7890** [comment]
@shlomif I think @hristijankiko is right. It's also mentioned over [here](https://github.com/FreeCodeCamp/FreeCodeCamp/issues/11007#issuecomment-250949323) that you need Node > 6 and NPM > 3. If you are on Linux/Unix system I recommend you use [nvm](https://github.com/creationix/nvm) and install the latest version of node. nvm just makes life easier. And [here](https://github.com/creationix/nvm#installation) are the installation instructions.

**Comment by ltegman** [comment]
Thanks for the PR and congrats on your first FCC contribution! 🎉 

The previous comments are right that you'll need node 6 and npm 3. After you upgrade you'll want to delete your node_modules folder inside the FCC repo by doing 'rm -rf node_modules` and then a fresh `npm install`, which also may help resolve this problem.

**Pull request merged**
