### PR TITLE
Remove `add` method test from "Reverse a Doubly Linked List"

### PR DESCRIPTION
**Pull request by TyMick**
Checklist:

- [x] I have read [freeCodeCamp's contribution guidelines](https://contribute.freecodecamp.org).
- [x] My pull request has a descriptive title (not a vague title like `Update index.md`)
- [x] My pull request targets the `master` branch of freeCodeCamp.
- [x] All the files I changed are in the same world language, for example: only English changes, or only Chinese changes, etc.

The second test for [Reverse a Doubly Linked List](https://www.freecodecamp.org/learn/coding-interview-prep/data-structures/reverse-a-doubly-linked-list) reads "The DoublyLinkedList should have a method called add." At this point, the student had just written an `add` method in the previous lesson, [Create a Doubly Linked List](https://www.freecodecamp.org/learn/coding-interview-prep/data-structures/create-a-doubly-linked-list), and this test name suggests that they will have to write another from scratch, since an `add` method is not provided in the challenge seed. This is not necessary, though, since the `js-teardown` script creates an `add` method and assigns it to `DoublyLinkedList.prototype` before the tests are run.

### CODE REVIEW

**Comment by moT01** [comment]
I have blocked this for now. See the [pinned code freeze issue](https://github.com/freeCodeCamp/freeCodeCamp/issues/38308)

**Comment by raisedadead** [comment]
Limitations removed on Coding Interview Prep Challenges.

**Review by naomi-lgbt — APPROVED** [review]
LGTM!

**Review by RandellDawson — APPROVED** [review]

**Comment by RandellDawson** [comment]
Thank you for your contribution to the page! 👍
We're happy to accept these changes, and look forward to future contributions. 🎉

**Pull request merged**
