### PR TITLE
feat: migrate setting modals

### PR DESCRIPTION
**Pull request by Sembauke**
Checklist:

- [x] I have read and followed the [contribution guidelines](https://contribute.freecodecamp.org).
- [x] I have read and followed the [how to open a pull request guide](https://contribute.freecodecamp.org/#/how-to-open-a-pull-request).
- [x] My pull request targets the `main` branch of freeCodeCamp.
- [x] I have tested these changes either locally on my machine, or GitPod.

- [x] `client/src/components/profile/components/time-line.tsx`
- [x] `client/src/components/settings/delete-modal.tsx`
- [x] `client/src/components/settings/reset-modal.tsx`
- [x] `client/src/components/signout-modal/index.tsx`
- [x] `client/src/components/SolutionViewer/exam-results-modal.tsx`
- [x] `client/src/components/SolutionViewer/project-modal.tsx`
- [x] `client/src/components/staging-warning-modal/index.tsx`

### Tests
- [x] `client/src/components/profile/components/time-line.tsx` (Tested solution modal on `solution-viewer.spec.ts` )
- [x] `client/src/components/settings/delete-modal.tsx` (Tested on `delete-modal.spec.ts`)
- [x] `client/src/components/settings/reset-modal.tsx` (Tested on `reset-modal.spec.ts`)
- [x] `client/src/components/signout-modal/index.tsx` (Tested on `signout-modal.spec.ts`)
- [x] `client/src/components/SolutionViewer/exam-results-modal.tsx` (Tested on `exam-reslts.spec.ts`)
- [x] `client/src/components/SolutionViewer/project-modal.tsx` (Tested solution modal on `solution-viewer.spect.ts`)
- [x] `client/src/components/staging-warning-modal/index.tsx` (Tested on `staging-warning-modal.spec.ts`)

Ref #52759

### CODE REVIEW

**Review by huyenltnguyen — COMMENTED** [review]
Did a quick test locally and the modals LGTM 👍 

I'll do another round of testing once #54139 is in.

**Review by huyenltnguyen — APPROVED** [review]
Merged the latest main and the changes work great.

---
~~Though I noticed that when the modal is open, the close button is focused, but there is no focus outline around it. This issue cannot be reproduce in `ui-components` / Storybook, so I think it has something to do with /learn and its CSS overrides.~~

~~I'll create a ticket to track the issue separately.~~

**Updated:** Scratch this, I mixed up the interaction during testing. The modal is behaving as expected:
- If the user opens the modal via mouse click, the close button is automatically focused but there is no focus outline (it's expected that the focus outline doesn't show up)
- If the user opens the modal via keyboard, the close button is focused and there is a focus outline
---

Also, the Modal component currently aligns its body content to the left. I have created #54161 to allow customizing modal body alignment. We mostly want the body content to center, but there are some cases where the content should be left-aligned.

**Comment by ahmaxed** [comment]
Thank you for the hard work. I had to review this in a couple of rounds. Here are the suggestions for the first round:

client/src/components/SolutionViewer/project-modal.tsx
Close button should be on the left.

client/src/components/settings/delete-modal.tsx
Head text color, and Text weight
Close button should be on the left. (why do we have three close buttons. :) )

client/src/components/settings/reset-modal.tsx
Head text color, and Text weight

client/src/components/signout-modal/index.tsx
Head text color, and Text weight

client/src/templates/Challenges/components/reset-modal.tsx
Head text color, and Text weight

**Comment by ahmaxed** [comment]
the close button on the footer is on the right in some instances and on the left in some.

**Review by ahmaxed — APPROVED** [review]

**Pull request merged**
