### PR TITLE
Confirm the Ending: Add test case

### PR DESCRIPTION
**Pull request by ahstro**
Add a test case that makes sure the user can't just check the last character or word, as suggested by @ltegman in [#3587](https://github.com/FreeCodeCamp/FreeCodeCamp/issues/3587#issuecomment-145521199).

### CODE REVIEW

**Comment by Joqr** [comment]
Not sure what you mean by your concern. The challenge literally asks for the user to verify if either 1) the last word in the first string matches the word in the second string, or 2) the last character in the first string matches the character in the second string.

If this is not what the challenge was meant to ask, then the directions need to be rewritten.

**Comment by ahstro** [comment]
Where do you find those words? From what I can found, the instructions say `Check if a string (first argument) ends with the given target string (second argument).`, i.e., not just last word or character, but the last characters matching the length of the `target`.

**Comment by Joqr** [comment]
It's not simply the words by themselves, but rather the information inferred from the context of the challenge. In-fact, your question, to me, furthers my initial point about this challenge.

At the start of the Bonfire Challenges, the user is instructed to consider not only the description, but also the tests that the user's code must pass. 

Since we know that in JavaScript, strings are usually sentences or words (they can be other characters, I know), we know that we need to write a code that can, at the very least, parse through words. 

Next, we may consider that our code should work for any characters, but when one looks at the tests that the code needs to pass, it is clear that the description is referring to strings of the word-type only. 

Also, nowhere in the description does the challenge state that the user must write a code that bases its returned value off of the length of the target. That would be redundant code because if the last characters in the str match the characters in the target, then by nature their character-lengths match because they are identical.

**Comment by ltegman** [comment]
The fact that the tests allowed the student to infer that they only needed to look for words or single characters is part of the problem. Writing the function to work for any string input is far more robust code, which is what the tests should be encouraging students to write when possible.

**Comment by Joqr** [comment]
No. The student infers only what they are led to believe in the description. From that line of thought, one could infer almost anything. 

I submitted two commits to improve this challenge. They are #3674 & #3676.

**Comment by ahstro** [comment]
The way I see it, the point of this exercise is to practically to figure out how to write a function that does what `.endsWith()` does, not just to supply a function that does it. I understand where you're coming from, from a "clean solution" point-of-view, but this should, in my opinion, be more than that.

**Comment by BerkeleyTrue** [comment]
@ahstro Thanks! Keep up the hard work!

Happy Coding!

**Pull request merged**
