### PR TITLE
feat(api): swap to immobiliarelabs sentry plugin

### PR DESCRIPTION
**Pull request by Sboonny**
Checklist:

- [x] I have read and followed the [contribution guidelines](https://contribute.freecodecamp.org).
- [x] I have read and followed the [how to open a pull request guide](https://contribute.freecodecamp.org/#/how-to-open-a-pull-request).
- [x] My pull request targets the `main` branch of freeCodeCamp.
- [x] I have tested these changes either locally on my machine, or GitPod.

Discussed in the API meeting, the current sentry plugin doesn't provide a good way to interact with the client, and making it do so isn't straight forward, we are moving to the package because it's well maintained.

~~I haven't tested it, so I will test it and open it to review.~~

image

### CODE REVIEW

**Comment by raisedadead** [comment]
> the current sentry plugin doesn't provide a good way to interact with the client

Could you list them here?

**Comment by Sboonny** [comment]
I will cc @ojeytonwilliams, because this is based on his request.

**Comment by ojeytonwilliams** [comment]
@raisedadead it's nothing overly complicated. One example is that I'd like to have access to the Sentry object to, say, `captureException`. While that's trivial, implementing tracing looks to be a little more involved.

We could just add features we need as we need them, but it looks like we'd just be gradually recreating immobiliare's plugin. I think we'd be better off just using it.

**Review by raisedadead — APPROVED** [review]

**Review by naomi-lgbt — APPROVED** [review]
okie dokie

**Pull request merged**
