### PR TITLE
speedup npm dependency installation in Dockerfile

### PR DESCRIPTION
**Pull request by jhonDoe15**
save time while installing npm dependencies with no npm progress bar

Checklist:

- [x] I have read [freeCodeCamp's contribution guidelines](https://contribute.freecodecamp.org).
- [x] My pull request has a descriptive title (not a vague title like `Update index.md`)
- [x] My pull request targets the `main` branch of freeCodeCamp.
- [x] I have tested these changes either locally on my machine, or GitPod.

### CODE REVIEW

**Comment by ojeytonwilliams** [comment]
Hi @jhonDoe15 this looks interesting. Would you mind giving us the times before and after this change, so we can see if it's significant?

**Comment by jhonDoe15** [comment]
I've used it when building a frontend image, with react I've seen a reduction in half the original time (17-28 vs 59-80 seconds) and with angular less because it's not a library like react but more framework like (32 vs 47 seconds), the main reason is the shorter package lookup time and the version consistency. Will check shortly

**Comment by jhonDoe15** [comment]
sorry mixed up with `npm install vs npm ci` regarding the previous comment, the difference is small but when paying for the build time it might be worthwhile

=> [builder 4/6] RUN npm ci                                                                                     125.5s

=> [builder 4/6] RUN npm ci --no-progress                                                                                                                                                                  117.1s

these results were from my win10 laptop with fast SSD, when ran from desktop with better CPU and network but sata SSD took longer (around 145 seconds) so surprisingly this workload is more disk related.

checked the difference with the build stage install command but similar results were noticed with the second stage commands

**Review by ojeytonwilliams — APPROVED** [review]
That's a decent speed up. Thanks for the profiling (and the PR!)

LGTM 👍

**Review by naomi-lgbt — APPROVED** [review]
Thanks for taking care of this!

**Pull request merged**
