### PR TITLE
fix(curriculum): correct misspelling

### LINKED ISSUE #44596: RWD Beta, Create Cafe Menu, Cinnamon is spelled wrong.
## Affected page

Problem begins at Step 53 and continues throughout the rest of the tutorial (Step 92)
https://www.freecodecamp.org/learn/2022/responsive-web-design/learn-basic-css-by-building-a-cafe-menu/step-53

## To reproduce

Am able to see in private browsing mode too. 

## Recommended fix, suggestions

Wherever the code is located that has the word "Cinammon", fixing the spelling error so it's "Cinnamon". 

## Screenshots
First page it's incorrect.
Screen Shot 2021-12-27 at 10 34 39 AM

Last page, showing it's still incorrect.
Screen Shot 2021-12-27 at 10 35 17 AM

### PR DESCRIPTION
**Pull request by ghost**
Checklist:

- [x] I have read [freeCodeCamp's contribution guidelines](https://contribute.freecodecamp.org).
- [x] My pull request has a descriptive title (not a vague title like `Update index.md`)
- [x] My pull request targets the `main` branch of freeCodeCamp.
- [x] I have tested these changes either locally on my machine, or GitPod.

Closes #44596

### CODE REVIEW

**Review by gikf — CHANGES_REQUESTED** [review]
Hey @najmieh

This change will need to be made in the further steps of the section. However before that there's need to sync your fork with the `freecodecamp:main` - currently `part-053.md` file exists in different directory, with changed name.

---

We would love to be able to merge your changes, but it looks like the branch is not up to date. ⚠️

To resolve this error, you will have to sync the latest changes from the `main` branch of the `freeCodeCamp/freeCodeCamp` repo.

Using the command line, you can do this in three easy steps:

```bash
git remote add upstream git://github.com/freeCodeCamp/freeCodeCamp.git

git fetch upstream

git pull upstream main
```

If you're using a GUI, you can simply `Add a new remote...` and use the link `git://github.com/freeCodeCamp/freeCodeCamp.git` from above.

Once you sync your fork and pass the build, we will be able to review your PR and merge it. 😊

---

Feel free to reference the [Syncing a Fork](https://help.github.com/articles/syncing-a-fork/) article on GitHub for more insight on how to keep your fork up-to-date with the upstream repository. 🔄

**Comment by najmieh** [comment]
@gikf Thank you for the feedback. I revise it ^^ and ask for a review soon. :paw_prints:

**Comment by najmieh** [comment]
> Hey @najmieh
> 
> This change will need to be made in the further steps of the section. However before that there's need to sync your fork with the `freecodecamp:main` - currently `part-053.md` file exists in different directory, with changed name.
> 
> We would love to be able to merge your changes, but it looks like the branch is not up to date. ⚠️
> 
> To resolve this error, you will have to sync the latest changes from the `main` branch of the `freeCodeCamp/freeCodeCamp` repo.
> 
> Using the command line, you can do this in three easy steps:
> 
> ```shell
> git remote add upstream git://github.com/freeCodeCamp/freeCodeCamp.git
> 
> git fetch upstream
> 
> git pull upstream main
> ```
> 
> If you're using a GUI, you can simply `Add a new remote...` and use the link `git://github.com/freeCodeCamp/freeCodeCamp.git` from above.
> 
> Once you sync your fork and pass the build, we will be able to review your PR and merge it. 😊
> 
> Feel free to reference the [Syncing a Fork](https://help.github.com/articles/syncing-a-fork/) article on GitHub for more insight on how to keep your fork up-to-date with the upstream repository. 🔄

@gikf I Synced my fork with the main. However, when I tried the command `git fetch upstream I faced  `error: invalid argument`
What other changes do I need to make this fully ready for a merge? :)

**Comment by gikf** [comment]
Could you paste the complete output from the terminal? Both with commands used and the results of it.

**Comment by najmieh** [comment]
@gikf apparently, I already had the remote name **upstream** on my local branch.  

So, I tried to use the commands above but, with the `git fetch upstream` step I'd get `fatal error: invalid argument`
I removed the upstream with `git remote rm` and followed the above steps this time I'd get: 


Maybe it is because of my directory or branch?
PS: I used this https://docs.github.com/en/pull-requests/collaborating-with-pull-requests/working-with-forks/syncing-a-fork  and synced my fork.

**Comment by gikf** [comment]
This is weird, error suggests there might be some problem with account permissions to the `.git` folder.

**Comment by najmieh** [comment]
@gikf I think I covered all of them.
Appreciate any feedbacks.

**Comment by gikf** [comment]
Yeah, although that's also for files that were since renamed and moved.

**Comment by gikf** [comment]
Currently they are in `/curriculum/challenges/english/14-responsive-web-design-22/learn-basic-css-by-building-a-cafe-menu` with `part` in file name changed to `step`. However because PR branch is based on older `main` branch, these files won't be there, what creates merge conflict.

**Comment by najmieh** [comment]
> Currently they are in `/curriculum/challenges/english/14-responsive-web-design-22/learn-basic-css-by-building-a-cafe-menu` with `part` in file name changed to `step`. However because PR branch is based on older `main` branch, these files won't be there, what creates merge conflict.

I covered all the steps from 53 to the rest. I checked the precedents and those didn't have the word **cinnamon**.
I synced my fork with the option `fetch upstream` and I can see that I have still the older version of the curriculum on my clone. 
Not sure how to do the further edits if a file is left out, or make this fully compatible to merge.

**Comment by gikf** [comment]
Do you have local `main` branch up to date? I should be more explicit that after syncing fork it's needed to rebase PR branch. Sorry about that.


If local `main` branch is synced, rebasing can be done with commands:

```bash
git checkout FCC-edit
git rebase main
```
This however won't be as easy right now, because each of the changed files, will require manual resolving in this case (what means removing `part-0xx.md` file and then editing `step-0xx.md`).

The quickest way to resolve it right now, that I can think of, might be kind of starting afresh - bringing `FCC-edit` local branch to the state of local `main` branch (if it's synced), again making necessary changes to the `step-0xx.md` files, pushing `FCC-edit` branch back to the fork, with `--force` option.

```bash
git checkout FCC-edit
git reset --hard main
(make necessary changes on local branch and commit them)
git push --force origin FCC-edit
```
Note that changes to all files can be done in a single commit, it doesn't need to be one file - one commit.

**Comment by najmieh** [comment]
Maybe it is because this is the beta version and I don't have the privilege to see its content on GitHub. Therefore I can not clone it. Because I can not even see the beta version on the freeCodeCamp GitHub account itself. 
 @gikf If that is the case, It might be a better idea to close this PR.

**Comment by gikf** [comment]
You definitely should have rights to see it on GitHub, they are here: https://github.com/freeCodeCamp/freeCodeCamp/tree/main/curriculum/challenges/english/14-responsive-web-design-22

**Comment by najmieh** [comment]
> You definitely should have rights to see it on GitHub, they are here: https://github.com/freeCodeCamp/freeCodeCamp/tree/main/curriculum/challenges/english/14-responsive-web-design-22

Thank you for your patience, generous time, and knowledge. It definitely made a difference for me.
I am stuck in this one. 
I rather not go further with the PR.  If it is possible close it.

**Comment by gikf** [comment]
If you'd change your mind, or will need other assistance with contributing, you can come to [Contributor's chat room](https://chat.freecodecamp.org/channel/contributors), there's many helpful people there. I'm using "sanity" username on it.

**Pull request closed without merging**
