### PR TITLE
[Fix] Bug in Get JSON with the JavaScript XMLHTTPrequest method

### LINKED ISSUE #13999: Test 4 fails in "Get JSON with the JavaScript XMLHttpRequest Method"
Challenge [get-json-with-the-javascript-xmlhttprequest-method](https://beta.freecodecamp.com/en/challenges/json-apis-and-ajax/get-json-with-the-javascript-xmlhttprequest-method) has an issue.
User Agent is: <code>Mozilla/5.0 (Macintosh; Intel Mac OS X 10_11_6) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/56.0.2924.87 Safari/537.36</code>.

Solution below fails for same reason as reported in #13571 (extra spacing in function assignment to `req.onload`). Solution proposed in said ticket sounds solid and I am happy to file a PR for this one.

```html


<script>
  document.addEventListener('DOMContentLoaded',function(){
    document.getElementById('getMessage').onclick=function(){
      // Add your code below this line
      var req = new XMLHttpRequest();
      req.open("GET", '/json/cats.json', true);
      req.send();
      req.onload = function(){
        var json = JSON.parse(req.responseText);
        document.getElementsByClassName('message')[0].innerHTML=JSON.stringify(json);
      };
      
      // Add your code above this line
    };
  });
</script>
<style>
  body {
    text-align: center;
    font-family: "Helvetica", sans-serif;
  }
  h1 {
    font-size: 2em;
    font-weight: bold;
  }
  .box {
    border-radius: 5px;
    background-color: #eee;
    padding: 20px 5px;
  }
  button {
    color: white;
    background-color: #4791d0;
    border-radius: 5px;
    border: 1px solid #4791d0;
    padding: 5px 10px 8px 10px;
  }
  button:hover {
    background-color: #0F5897;
    border: 1px solid #0F5897;
  }
</style>
<h1>Cat Photo Finder</h1> 
<p class="message box">
  The message will go here
</p>
<p>
  <button id="getMessage">
    Get Message
  </button>
</p>

```

### PR DESCRIPTION
**Pull request by thecodingaviator**
- [x] I have read [freeCodeCamp's contribution guidelines](https://github.com/freeCodeCamp/freeCodeCamp/blob/master/CONTRIBUTING.md).
- [x] My pull request has a descriptive title (not a vague title like `Update index.md`)
- [x] My pull request targets the `master` branch of freeCodeCamp.
- [x] None of my changes are plagiarized from another source without proper attribution.
- [x] My article does not contain shortened URLs or affiliate links.

If your pull request closes a GitHub issue, replace the XXXXX below with the issue number.

Closes #13999

### CODE REVIEW

**Comment by QuincyLarson** [comment]
@thecodingaviator Awesome - thank you.

Hi @ValeraS could you take a look at this and see whether it addresses issue #13999 ?

**Comment by ValeraS** [comment]
@QuincyLarson It resolves an issue with spaces between a keyword `function` and parentheses. But if we use an arrow function, it will still fail. In this challenge, we can not use tests such as proposed in #13999 because we don't have access to a local variable.

IMO, checking this challenge by regex is not right. We can mock an `XMLHttpRequest` and get the needed information from it.

But this challenge is solved by paste code snippet from the description. And I do not sure what we need to bother about right testing here.

@thecodingaviator I recommend also providing a solution.

**Comment by ezioda004** [comment]
@ValeraS Can we not simply check `typeof onload`? Even with arrow/function declaration/function expression it'll always return `"function"`.


On a side note regarding:
>But this challenge is solved by paste code snippet from the description. And I do not sure what we need to bother about right testing here.

I think we should update this challenge to something like `fetch` or `axios`. As `XMLHttpRequest` is considered legacy at this point.

**Comment by ValeraS** [comment]
@ezioda004 
if `req` declared with `let` or `const` then we do not have access to this variable.

And about legacy. Axios uses `XMLHttpRequest` under the hood.

**Comment by ezioda004** [comment]
@ValeraS 
>Axios uses `XMLHttpRequest` under the hood.

Yes, ofcourse. My point was that in day to day basis developers usually use `fetch/axios` instead of `XML` Object. I think we should atleast have a challenge based on `fetch` as its natively supported by [most](https://caniuse.com/#feat=fetch) browsers now.

**Comment by thecodingaviator** [comment]
@ValeraS We can

1. Check for it to be a function and then maybe check for function content.
2. We can setup to ask for a mock call and check for return on the call
3. We can change the tests to get the user to copy paste the code on the left and check that

**Comment by moT01** [comment]
I tested this locally and it fixes the spacing issue - If we want to change these challenges to a fetch request or change the tests to accommodate arrow functions, we should open a new issue and continue the discussion there. This PR fixes the issue that was opened so I'm going to merge and close that issue. Nice job and thanks @thecodingaviator!

**Pull request merged**
