### PR TITLE
better solution to redux spread operator

### PR DESCRIPTION
**Pull request by andrew-ma**
2 step -> 1 step

- [x ] I have read [freeCodeCamp's contribution guidelines](https://github.com/freeCodeCamp/freeCodeCamp/blob/master/CONTRIBUTING.md).
- [ x] My pull request has a descriptive title (not a vague title like `Update index.md`)
- [ x] My pull request targets the `master` branch of freeCodeCamp.
- [ x] None of my changes are plagiarized from another source without proper attribution.
- [ x] All the files I changed are in the same world language (for example: only English changes, or only Chinese changes, etc.)
- [ x] My changes do not use shortened URLs or affiliate links.

Closes #XXXXX

### CODE REVIEW

**Comment by RandellDawson** [comment]
How is it "better"?

**Comment by andrew-ma** [comment]
It's not better but it does saves a step. It also shows how the spread operator can be used for concatenation and not just making a copy of the array. Maybe put both solutions.

**Comment by thecodingaviator** [comment]
@RandellDawson IMO this might confuse some users who might not be familiar with how the syntax works. Agreed, this was taught in the ES6 part but we should try and keep it simple. Right?

**Comment by RandellDawson** [comment]
@thecodingaviator There is an open issue (#35453) regarding what the Guide solutions should look like.  I think your points should be discussed there.  We have never formally decided if solutions for individual challenges should show methods or concepts which would not have already been taught/learned at the point the challenge is introduced into the curriculum.  I believe the whole concept of Intermediate, and Advanced solutions spawned out of the fact that people wanted to post solutions which use ES6 syntax at a time when we were not teaching those methods.

**Review by moT01 — APPROVED** [review]
I'm thinking this can be merged. The way he shows with this change is sort of suggested in the challenge instructions - I think this is more often how you would see this done with redux - It's taught in ES6 and mentioned again here. And I think it's a better solution. 

Thanks for contributing to freeCodeCamp @andrew-ma!

**Pull request merged**
