### PR TITLE
fix(learn): additional clarification when switching to a new boilerplate

### PR DESCRIPTION
**Pull request by theforbiddenpool**
**Checklist:**

- [x] I have read [freeCodeCamp's contribution guidelines](https://contribute.freecodecamp.org).
- [x] My pull request has a descriptive title (not a vague title like `Update index.md`)
- [x] My pull request targets the `master` branch of freeCodeCamp.
- [x] All the files I changed are in the same world language, for example: only English changes, or only Chinese changes, etc.

**Description:**
In the [Set Up The Environment challenge](https://www.freecodecamp.org/learn/information-security-and-quality-assurance/advanced-node-and-express/implementation-of-social-authentication) we change to a new boilerplate. There are multiple steps that need to be taken to set up this boilerplate, but they were not referred anywhere. I added a new paragraph that explains what needs to be changed.

### CODE REVIEW

**Comment by Sky020** [comment]
I am busy refactoring the _Advanced Node and Express_ challenges, and just started the discussion of combining everything into one project.

**Comment by theforbiddenpool** [comment]
@Sky020 I would love to help, what can I do?

**Comment by Sky020** [comment]
Sure. Well, it is still under discussion, but I have a draft PR going to change the boilerplate here: https://github.com/freeCodeCamp/boilerplate-advancednode/pull/11

The details are in the PR. The main thing is to get a discussion going for input from different people, and then a few will need to test the write-up.

**Review by moT01 — COMMENTED** [review]
Thanks for the PR @theforbiddenpool 🎉  - However, I am going to vote that we close it in favor of the new boilerplate @Sky020 is working on which combines all the boilerplates in this section.

**Review by Manish-Giri — COMMENTED** [review]
+1 for closing in favor of the new boilerplate.

**Comment by RandellDawson** [comment]
Thank you for opening this pull request.

This is a standard message notifying you that we’ve reviewed your pull request and have decided not to merge it. We have decided to move forward with changes in another PR.

We still would welcome future pull requests from you.

Thank you and happy coding.

**Pull request closed without merging**
