### PR TITLE
bug: make links open in new window as per issue #10969

### LINKED ISSUE #10969: Record Collection URLs open in current window
#### Challenge Name
https://www.freecodecamp.com/challenges/record-collection

#### Issue Description
`Mozilla Developer Network` and `Manipulating Complex Objects` URLs do not open in a new tab. I assume opening in a new tab is the desired behaviour based on previous challenges I have encountered. Also, I always assumed the icon that appears after the URL name suggested this behaviour.

* Browser Name, Version:  Chrome, Version 53.0.2785.116 m (64-bit)
* Operating System: Windows 10
* Mobile, Desktop, or Tablet: Desktop

### PR DESCRIPTION
**Pull request by alexanderholman**
#### Pre-Submission Checklist

- [x] Your pull request targets the `staging` branch of FreeCodeCamp.
- [x] Branch starts with either `fix/`, `feature/`, or `translate/` (e.g. `fix/signin-issue`)
- [x] You have only one commit (if not, [squash](http://forum.freecodecamp.com/t/how-to-squash-multiple-commits-into-one-with-git/13231) them into one commit).
- [x] All new and existing tests pass the command `npm run test-challenges`. Use `git commit --amend` to amend any fixes.
#### Type of Change

- [x] Small bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds new functionality)
- [ ] Breaking change (fix or feature that would change existing functionality)
- [ ] Add new translation (feature adding new translations)
#### Checklist:

- [x] Tested changes locally.
- [x] Closes currently open issue (replace XXXX with an issue no): Closes #10969 
#### Description

Added `target="blank"` to anchors on lines 4914 and 4915

### CODE REVIEW

**Comment by dhcodes** [comment]
@alexanderholman please change your branch name to remove the issue number and then push it again with -f

**Comment by alexanderholman** [comment]
no problem

**Comment by alexanderholman** [comment]
@ dhcodes I've opened a new PR ([#10978](https://github.com/FreeCodeCamp/FreeCodeCamp/pull/10978)) with the new branch name, not sure if I've done that correctly? changed the name using `git branch -m ...` locally and pushed to my own repo... was there a better way to do it? e.g. a way to update the PR itself?

**Comment by dhcodes** [comment]
That's fine. We'll just close this one. I'm not sure there was a better way since [according to this](http://stackoverflow.com/questions/20007578/renaming-a-branch-while-on-pull-request) you can't really use the same PR. If you deleted the branch it would remove the PR.

**Pull request closed without merging**
