### PR TITLE
feat(client): create editor system theme

### PR DESCRIPTION
**Pull request by Sboonny**
Checklist:

- [x] I have read and followed the [contribution guidelines](https://contribute.freecodecamp.org).
- [x] I have read and followed the [how to open a pull request guide](https://contribute.freecodecamp.org/#/how-to-open-a-pull-request).
- [x] My pull request targets the `main` branch of freeCodeCamp.
- [x] I have tested these changes either locally on my machine, or GitPod.

Setting the default theme for the editor disabled the ability to add system theme, because it requires magic 🤷. I don't know how to word it.

Anyway, this should sort it, to test it:

- visit /learn/2022/responsive-web-design/learn-html-by-building-a-cat-photo-app/step-23
- set your prefered-scheme to light nothing should look weird
- set your preferred-scheme to dark, nothing should look weird
- log in
- set your theme to default, nothing should look weird
- set your theme to night, nothing should look weird
- maybe I missed something, if you think there is more, please check it. 

Ref #48757

### CODE REVIEW

**Comment by Sboonny** [comment]
this is so fragile, if theme change to anything anywhere, while the user is logged out, they will have two different states of the theme

**Comment by raisedadead** [comment]
Please add E2E tests to cover all the scenarios; that is the best way to keep this PR moving.

**Comment by Sboonny** [comment]
Created issue for it #49784

**Comment by Sboonny** [comment]
@raisedadead, the e2e test can be addressed by different person in a different PR.

If you are worried that a code can break the theme can be added, as I mentioned above, don't merge a PR that set a initial value for theme while there is redux store for the theme.

A good example for what I mean is the `attempt` logic in the same file, if someone set initial value `3` for attempts while we are storing it in redux, all the logic around it become useless.

**Comment by Sboonny** [comment]
> Unfortunately, we can't have busy maintainers on the lookout for a PR that accidentally breaks things.

Unfortunately, you already do https://github.com/freeCodeCamp/freeCodeCamp/issues/48936. 

The fragility do exist the moment, someone allowed a code that change the theme stored state, in a local scope, you are just blocking a PR that is small part of the system theme, and blocking my work that is following the PR, that fragility I have pointed out exist already.

True maintainers are busy, so to save some of my busy and productive time, because I could have finished the system PR, if this wasn't blocked for months, I will assign you to add the test, and if you can't add it the next week, I will remove the block label.

Of course, you can ask Naomi, Tom, Shaun, Niraj, Sem, Oliver and Ahmad for help.

But don't block my work and waste my productivity, in an issue that shouldn't be there in the first place.

**Comment by Sboonny** [comment]
You are clearly not aware of what this PR and its code trying to achieve, and again this isn't adding fragility or fixing something, it's enabling the changes in that will allow for easier themes changes in the future.

The test you want shouldn't be related to the work I am doing in this PR.

**Pull request merged**
