### PR TITLE
fix(settings): Add method to user to update email

### LINKED ISSUE #36604: [.dev] Unable to change email address on settings page
I can't change my email address on the settings page. Anyone one else want to confirm this?

### PR DESCRIPTION
**Pull request by lancerutkin**
- [X] I have read [freeCodeCamp's contribution guidelines](https://github.com/freeCodeCamp/freeCodeCamp/blob/master/CONTRIBUTING.md).
- [X] My pull request has a descriptive title (not a vague title like `Update index.md`)
- [X] My pull request targets the `master` branch of freeCodeCamp.
- [X] None of my changes are plagiarized from another source without proper attribution.
- [X] All the files I changed are in the same world language (for example: only English changes, or only Chinese changes, etc.)
- [X] My changes do not use shortened URLs or affiliate links.

Closes #36604

Note: when a user updates his or her email, that goes through on the server and the put is successful. However, I still need to figure out how to get the new email to render on the settings page upon success. Working on that now.

### CODE REVIEW

**Comment by ojeytonwilliams** [comment]
I don't think it should be possible to change an email address without ensuring they have access to the existing address.  Shouldn't we send them an email to their current address with a link to change it?

**Comment by ahmadabdolsaheb** [comment]
@raisedadead thoughts on @ojeytonwilliams 's proposal?

**Comment by Bouncey** [comment]
We had this before, but seems like I deleted it by mistake. I will be raising a PR in the next day or so reinstating this functionality. 

My bad, sorry.

**Comment by raisedadead** [comment]
Resolved in https://github.com/freeCodeCamp/freeCodeCamp/pull/36776

**Pull request closed without merging**
