### PR TITLE
Fix job board copy

### PR DESCRIPTION
**Pull request by BerkeleyTrue**

### CODE REVIEW

**Comment by ltegman** [comment]
I'm getting some lint errors and warnings. On line 169 and 170 I'm getting errors that `value`, `type`, and `valid` are missing in props validation. I think this is an error with how eslint handles accessing properties of Object props and the rule should just be disabled for that block.

I'm also getting react/jsx-boolean-value warnings on lines 337, 347, 356, 382, 407, and 470 that the "Value must be omitted for boolean attributes".

**Comment by BerkeleyTrue** [comment]
Which version of eslint are you using?

**Comment by ltegman** [comment]
1.8.0

**Comment by BerkeleyTrue** [comment]
@ltegman Can you give it a spin now? All the lint issue's should be fixed.

**Comment by ltegman** [comment]
Looks great! No lint errors and everything still works as expected! :+1:

**Pull request merged**
