### PR TITLE
fix(curriculum): updated wording on understanding uninitialized variables 

### LINKED ISSUE #45853: tips is wrong at  page   https://www.freecodecamp.org/learn/javascript-algorithms-and-data-structures/basic-javascript/understanding-uninitialized-variables
## Affected page
https://www.freecodecamp.org/learn/javascript-algorithms-and-data-structures/basic-javascript/understanding-uninitialized-variables

## Screenshots
image
but 
image

first  it say  `Initialize the three variables a, b, and c with 5, 10, and "I am a" respectively so that they will not be undefined.`
but,   following tips  is Conflicts.  Beginners don't know  which is right.

### PR DESCRIPTION
**Pull request by lharrison1313**
Checklist:

- [x] I have read [freeCodeCamp's contribution guidelines](https://contribute.freecodecamp.org).
- [x] My pull request has a descriptive title (not a vague title like `Update index.md`)
- [x] My pull request targets the `main` branch of freeCodeCamp.
- [x] I have tested these changes either locally on my machine, or GitPod.

Closes #45853

This is my first time contributing to an open source project! I work as a full stack developer, so let me know if you need any help. I've included a screenshot below even though its a simple change.

Screenshot 2022-05-03 185258

### CODE REVIEW

**Comment by luojiyin1987** [comment]
@lharrison1313     
`b` should be defined and have a final value of `15`.

**Comment by lharrison1313** [comment]
> @lharrison1313 `b` should be defined and have a final value of `15`.
✅

**Review by naomi-lgbt — CHANGES_REQUESTED** [review]
I can't reach it, but we should update the third hint:

```md
`c` should not contain `undefined` and should have a final value of the string `I am a String!`
```

Just for consistency.

**Review by naomi-lgbt — APPROVED** [review]
This looks good to me!

**Review by gikf — APPROVED** [review]
Looks good :+1: 

---

Note for future - it is recommended to make changes on a separate branch, than the `main` branch. See more about it in point 3 at https://contribute.freecodecamp.org/#/how-to-setup-freecodecamp-locally?id=making-changes-locally.

**Comment by gikf** [comment]
Hi @lharrison1313. Congrats on your first pull request (PR)! 🎉

Thank you for your contribution to the page! 👍
We are happy to accept these changes and look forward to future contributions. 📝

**Pull request merged**
