### PR TITLE
feat(curriculum): use id's for dashed names in fsd

### PR DESCRIPTION
**Pull request by moT01**
Some of the dashed names for the lecture challenges were quite long - so I thought that we could just use the ID's instead.

Checklist:

- [x] I have read and followed the [contribution guidelines](https://contribute.freecodecamp.org).
- [x] I have read and followed the [how to open a pull request guide](https://contribute.freecodecamp.org/how-to-open-a-pull-request/).
- [x] My pull request targets the `main` branch of freeCodeCamp.
- [x] I have tested these changes either locally on my machine, or GitPod.

Closes https://github.com/freeCodeCamp/fCC10/issues/16

### CODE REVIEW

**Comment by ilenia-magoni** [comment]
are you also going to add to the tests a verification that id, dashed name and file name should match? that would be a useful addition

**Comment by moT01** [comment]
yup, the test is there - in the `challenge-schema.js` file 👍

**Comment by jdwilkin4** [comment]
> I can keep updating it, but maybe we can find a time between adding other challenges to get this in and then we will have to update the other PR's - I can help with that if needed.

Here are my thoughts

The following PR's here are almost ready to be merged in. They are either looking for a second approval or small PR's and will probably be approved within the next day or so. So IMO, those can go in before yours. 

- https://github.com/freeCodeCamp/freeCodeCamp/pull/57269
- https://github.com/freeCodeCamp/freeCodeCamp/pull/57265
- https://github.com/freeCodeCamp/freeCodeCamp/pull/57264
- https://github.com/freeCodeCamp/freeCodeCamp/pull/57050
- https://github.com/freeCodeCamp/freeCodeCamp/pull/57153 (looks like this is just waiting the CI)
- https://github.com/freeCodeCamp/freeCodeCamp/pull/57045

Then we have this open Quiz PR.

https://github.com/freeCodeCamp/freeCodeCamp/pull/57188

It just received another set of reviews. Usually in the past, the quiz PR's take a while before there are approvals and it gets merged in. So we have two options 

Option 1: Push up a commit to resolve any outstanding reviews or additional changes needed.
Option 2: Update their branch once your PR goes in.

There are a couple of other quiz PR's open but Huyen is working on getting those resolved. So she can make the necessary updates to the branch and resolve any conflicts. 

As for the rest of the PR's under the `full stack cert` label, it looks like there are either in draft status or still going through multiple reviews and updates. So IMO we could merge yours in first, and the team members assigned to the PR's can update them accordingly

**Comment by moT01** [comment]
I don't mind waiting on this. We can check back in the next couple days and see if we can get most of those in. I will post a message in chat as well letting people know about this change. Maybe some people can use the id's on new PR's or make changes on existing ones.

**Comment by naomi-lgbt** [comment]
I have concerns with this approach:

- First, this makes the URLs very ugly and removes the human-readable component (which is a key piece of URL structure and can impact SEO)
- Second, what does this mean for people helping campers on the forum? I understand the goal is to avoid people typing `step-20` into the address bar to advance their progress, but we need to be able to visit an arbitrary step to debug users' code.

**Comment by moT01** [comment]
This has been on the roadmap for a while I think. It was something Oliver was trying to do with next.js so that the ID in the URL would determine which challenge gets loaded - and we could use the same challenge in multiple places based on the ID. Not sure exactly how that was intended - this doesn't do that obviously, but it's a step in that direction.

This came about because as I was creating the lecture challenges, some of them had really long dashed names. So I thought we could take that step towards doing the above.

> First...

The challenges aren't indexed, I believe? So this shouldn't affect SEO. It does affect some of the readability - here's a few examples:
`https://freecodecamp.org/learn/full-stack-developer/exam-certified-full-stack-developer/exam-certified-full-stack-developer`
vs
`https://freecodecamp.org/learn/full-stack-developer/exam-certified-full-stack-developer/645147516c245de4d11eb7ba`
and
`https://freecodecamp.org/learn/full-stack-developer/lecture-importance-of-semantic-html/how-do-you-display-abbreviations-and-acronyms-in-html`
vs
`https://freecodecamp.org/learn/full-stack-developer/lecture-importance-of-semantic-html/672995d673bd3237200b9e7c`

I guess it's less readable - but shorter. Perhaps it points out an issue with our naming conventions or curriculum structure - there's a lot of repeated parts in some URL's.

> Second...

I'm not sure I understand the problem here. Can't users just share a URL or just tell us what step it is. Maybe a little harder to find if they just tell us the step number I guess.

If it's not something we want, I'm fine with discarding this - but I think I like it at the moment, and would like to get some more input before we do that.

**Comment by ilenia-magoni** [comment]
> * chore(curriculum): add missing comprehension check questions for css grid lectures  #57269

this is changing an existing file, it should not have issues

the PRs that need looking at should be those that add new files, which are mostly staff's competence anyway

**Review by majestic-owl448 — APPROVED** [review]

**Comment by moT01** [comment]
We've decided to hold off on this for now.

**Pull request closed without merging**
