### PR TITLE
split and simplified learn map

### PR DESCRIPTION
**Pull request by kabindrashrsth**
Checklist:

- [x] I have read [freeCodeCamp's contribution guidelines](https://contribute.freecodecamp.org).
- [x] My pull request has a descriptive title (not a vague title like `Update index.md`)
- [] My pull request targets the `master` branch of freeCodeCamp.
- [x] All the files I changed are in the same world language, for example: only English changes, or only Chinese changes, etc.

Closes #39154

### CODE REVIEW

**Comment by nhcarrigan** [comment]
Hey there~!

Was this PR opened in response to @moT01's comment on your other PR? If so, I believe (rather than opening a PR) you should be able to edit that PR to target the `next-i18n-client` branch.

**Comment by kabindrashrsth** [comment]
@nhcarrigan oh I see. Should I delete this PR then?

**Comment by nhcarrigan** [comment]
Yes, I would close this in favour of your existing PR. 🙂

**Comment by kabindrashrsth** [comment]
@nhcarrigan Thanks! Sorry, I didn't know that I could simply edit a PR to target a different branch.

**Pull request closed without merging**
