### PR TITLE
feat(api): improve performance with profanity filter replacement

### PR DESCRIPTION
**Pull request by Topener**
Checklist:

- [X] I have read and followed the [contribution guidelines](https://contribute.freecodecamp.org).
- [X] I have read and followed the [how to open a pull request guide](https://contribute.freecodecamp.org/#/how-to-open-a-pull-request).
- [X] My pull request targets the `main` branch of freeCodeCamp.
- [X] I have tested these changes either locally on my machine, or GitPod.

The `bad-words` package hasn't been updated in a few years, and contains a massive flaw regarding performance, there's a for-loop for every word to be filtered. The `no-profanity` filter is created to be a backwards compatible replacement and is many times faster as it uses a single regex. Especially for the usecase of checking profanities against usernames this should be as fast as possible. (I tested it going down to 1-2ms from 25-30ms) per check.

Furthermore the no-profanity package contains an updated list of profanities directly included in the package.

### CODE REVIEW

**Comment by raisedadead** [comment]
Hey 👋🏽 !

Thanks for creating this PR. 

> The no-profanity filter is created to be a backwards compatible replacement and is many times faster as it uses a single regex

Please point us to the code. 

We are asking because we noticed that this is a new package, which is a rewrite of the original, and it hasn't received significant adoption yet. However, we appreciate your efforts in reviving the popular and now unmaintained library.

To ensure production readiness, it is required by us to conduct more testing or utilize tools such as https://socket.dev to obtain the necessary insights for establishing stability.

Thanks for your understanding and happy coding!

**Comment by Sembauke** [comment]
Hey @Topener,

Again thank you for making this. We recommend not working from your main branch. 

Please read: https://contribute.freecodecamp.org/#/how-to-open-a-pull-request

**Comment by Topener** [comment]
Hi @raisedadead, thanks for reviewing! I did notice some tests breaking and wasn't sure yet how this was happening. 

The source code for the package is here: https://github.com/Topener/no-profanity/blob/main/lib/no-profanity.js

The mentioned regex is on line 31. The package also contains a more extensive list of profanities not in the original bad-words package as well.

The comparison test for speed can be found here: https://github.com/Topener/no-profanity/blob/main/other-packages.md#compared-to-bad-words. Keep in mind I ran these tests with a smaller word-count for bad-words than for the no-profanity package, meaning the actual performance of `bad-words` is even worse than mentioned in my test, as it slows down even more with more words, where `no-profanity` has little to no performance decrease with a bigger set.

The package can be run using `npm test`.

@Sembauke Also thanks for pointing that out! Do you want me to branch off locally?

**Comment by raisedadead** [comment]
> I did notice some tests breaking and wasn't sure yet how this was happening.

No worries, we are here to help you get it working. Can you confirm the API/usage changes between this package and `bad-words`? That would help us recommend changes in the PR.

Pointing to some docs should be fine.

> Also thanks for pointing that out! Do you want me to branch off locally?

It is OK for now, but it will soil your fork, so future PRs might become messy. We recommend branching for repeat contributions.

**Comment by Topener** [comment]
Ok perfect, thanks!

The changes are simple, `bad-words` is class-based where `no-profanity` is not. This means the options `bad-words` accepts should be provided in every call, instead of once in the beginning.

However, the options themselves are the same, as can be seen in this `jest` test: https://github.com/Topener/no-profanity/blob/main/test/badWordsCompatible.test.js

There will be deprecation warnings for certain names, but other than that it's the same. 

`bad-words` used `filter.isProfane()` where `no-profanity` simply exports `isProfane()` as a function.

There are a few other functions too, but those are not used in the code, nor the `options` actually. So for this integration the only difference is the filter declaration and the import change.

And one extra difference, `no-profanity` uses a file to provide the profanities, though I've been recommended to change this to a separate package (and a JS file instead of a txt file) for easy inter-exchangeability. If you prefer that integration (that won't change any logic on the integration side of things) then I can push that version first so you can immediately start to use this.

**Comment by Topener** [comment]
I've just pushed the version that doesn't use file-api's that seem to have complicated things unnecessarily. One of the failed errors seemed to point at that section specifically so this is why I thought this might fix things, alongside it being better in the first place.

**Comment by raisedadead** [comment]
Thanks @Topener!

Would someone from @freeCodeCamp/dev-team mind help us further here? We are specifically looking at:

> The error  SyntaxError: Cannot use import statement outside a module is weird to me as the package is a module.

**Comment by naomi-lgbt** [comment]
Just a hunch here, but I think that might be because **we** aren't a module.

That is, your package is written to support ESM syntax. We build to CJS syntax, so when it runs your module it sees an ESM import and explodes.

**Comment by raisedadead** [comment]
Oh - right! Sorry, I missed this totally.

And as much as we would like to go ESM, we can't because we have dependencies that won't make the switch. JavaScript is a unified, democratic country they said 😅 !!

**Comment by Topener** [comment]
Ah thanks. How could it be changed to be compatible?

**Comment by Topener** [comment]
I've updated the package to compile a commonjs version as well using babel.

https://github.com/Topener/no-profanity/blob/e0b6b97319615a64905c274eed7b749628b3113c/package.json#L17

And then both export options here: https://github.com/Topener/no-profanity/blob/e0b6b97319615a64905c274eed7b749628b3113c/package.json#L7-L9

Tests seem to succeed now! Hope this is well. Let me know if any further changes need to be made

**Comment by Topener** [comment]
Hi @raisedadead, I _think_ problems are resolved now and all is good? Though some tests are failing I feel like that's outside of my PR's scope?

**Comment by Topener** [comment]
Thanks for the insight @ojeytonwilliams. I'll try to investigate how that can be solved, unless you have ideas that can point me in the right direction? They should be able to require the correct version directly as both are shipped in the package now as you can see here: 

https://github.com/Topener/no-profanity/blob/main/package.json#L9

**Comment by ojeytonwilliams** [comment]
It seems like the problem is that ts-node sees that `no-profanity` has `"type": "module"` in the package.json and so assumes that `commonjs/no-profanity.js` is a module.

I'm afraid I don't know the best way to fix this, but I think it's possible with the right bundler.

Otherwise, I do intend to move the new api to use ESM at some point, but it's a big job that I do not see my self getting to soon.

**Comment by ShaunSHamilton** [comment]
Just to mention before moving forward with this:

Seeing as this contains a different list (new words), we would need to double-check and confirm there would be no issues with existing Campers.

**Comment by Topener** [comment]
Hi all! Thanks again for taking your time with me to look through this.

I've simplified the package to be compatible, and the tests succeeded on the 6th push. I just pushed again for the simple reason to address @ShaunSHamilton's concern. I've merged both wordlist to form a new and complete wordlist of profanities in version 1.4.1. All the words from `bad-words` are now included alongside the list already present.

This does introduce _new_ words to the profanity list, but none of the the original words are removed. The only concern now is if someone has a word _in_ the new list as username of course.

Let me know if you need anything from me

**Comment by raisedadead** [comment]
> Seeing as this contains a different list (new words), we would need to double-check and confirm there would be no issues with existing Campers.

Existing users should not be affected at all. 

I believe any validations we have (API side, I mean) will trigger only on a username change, so if you already have a profane name, you bypassed the "new" checks we just implemented; Congrats! 

But you can't change into a profane username any longer. That is, of course, assuming we don't have any "valid" names in the list – which is a problem for the underlying list, so to speak.

Other than that we are good!

**Comment by Topener** [comment]
Hi all,

I tried merging in main to resolve conflicts but I'm getting many linting errors if I try. Is there anything I can do or is it okay from my side and you can take over?

Let me know!

**Comment by raisedadead** [comment]
Yes - someone will help resolve it. Thanks for letting us know.

**Comment by naomi-lgbt** [comment]
Hey @Topener, I've pushed a commit to resolve the conflicts - didn't see any lint errors locally.

A quick note that you should generally avoid working on your `main` branch directly.

**Review by raisedadead — APPROVED** [review]

**Review by naomi-lgbt — APPROVED** [review]
Gave this a quick test locally, didn't see any concerns, functionality mirrors production.

**Comment by naomi-lgbt** [comment]
Congrats on your first pull request (PR)! 🎉

Thank you for your contribution to the page! 👍
We are happy to accept these changes and look forward to future contributions. 📝

**Pull request merged**
