### PR TITLE
fix(curriculum): add test for number of keyframe waypoints

### LINKED ISSUE #49841: Step 96-New Web design Certificate
### Describe the Issue

Step 96Passed
Give wave four waypoints starting at 10%, and incrementing by 10%.

1.The tests allow duplicate waypoints for the four required percentages.
2.The tests allow other waypoint values not specified in the instructions.

### Affected Page

https://www.freecodecamp.org/learn/2022/responsive-web-design/learn-css-transforms-by-building-a-penguin/step-96

### Your code

```

```
@keyframes wave {
  10% {  

  }
  20% {

  }
  10% { 

  }
  30% {

  }
  10% {

  }
  40% {

  }
  10% {

  }
  50% {
    
  }
}

### Expected behavior

When I read the instructions, I thought it said do four wave points starting at ten and add ten to each one. Once I failed. I calculated it to do each ten and add ten percent to each one after. I guess even though I did not read the instructions the way they were adviced I found a bug. I passed and when I went to next step it automatically fixed my mistake and removed the 50% also.

### Screenshots

_No response_

### System

- Device: [e.g. iPhone 6, Laptop]
- OS: [e.g. iOS 14, Windows 10, Ubuntu 20.04]
- Browser: [e.g. Chrome, Safari]
- Version: [e.g. 22]

### Additional context

The instructions from what I read confused me to do four tens and add ten percent under each one. I was able to find the bug due to this so yay I am pleased to help. By doing a total of four I was able to add 50 percent, on the last one too. My suggestion to fix the sentence on instructions, would be to not say make four waves starting at ten. Instead maybe you could say make four waves start at 10 percent and then for the rest add ten percent to each one for a total of four waves only.

### PR DESCRIPTION
**Pull request by ArslanYM**
Checklist:
- [x] I have read and followed the [contribution guidelines](https://contribute.freecodecamp.org).
- [x] I have read and followed the [how to open a pull request guide](https://contribute.freecodecamp.org/#/how-to-open-a-pull-request).
- [x] My pull request targets the `main` branch of freeCodeCamp.
- [x] I have tested these changes either locally on my machine, or GitPod.

Closes  #49841 

Added another test with a hint for better understanding of the challenge given for wave points

### CODE REVIEW

**Review by naomi-lgbt — APPROVED** [review]
As a quick aside, when a review includes suggested changes you can commit them directly to your branch (or through GitHub's `Commit Suggestion` button) rather than having to make a new PR. 💜

**Review by gikf — APPROVED** [review]
LGTM :+1:

**Comment by gikf** [comment]
Hi @ArslanYM. Congrats on your first pull request (PR)! 🎉

Thank you for your contribution to the page! 👍
We are happy to accept these changes and look forward to future contributions. 📝

**Comment by ArslanYM** [comment]
> As a quick aside, when a review includes suggested changes you can commit them directly to your branch (or through GitHub's `Commit Suggestion` button) rather than having to make a new PR. 💜

Understood. Thankyou for the suggestion. I wasnt aware of it.

**Pull request merged**
