### PR TITLE
fix(curriculum): use DOM for link element tests

### PR DESCRIPTION
**Pull request by lasjorg**
Checklist:

- [x] I have read [freeCodeCamp's contribution guidelines](https://contribute.freecodecamp.org).
- [x] My pull request has a descriptive title (not a vague title like `Update index.md`)
- [x] My pull request targets the `main` branch of freeCodeCamp.
- [x] I have tested these changes either locally on my machine, or GitPod.

Closes #XXXXX

Switch to DOM queries for the `link` element test, fixing the `/>` requirement for the element.

Note: there currently seems to be a bug with the `head > link` test see issue https://github.com/freeCodeCamp/freeCodeCamp/issues/47207

### CODE REVIEW

**Review by hanswang123456 — COMMENTED** [review]
Does getting "link.dataset.href" work? Isnt dataset for "data-*" attributes? I think it'd be more consistent to just get the href attribute with "getAttribute."

**Comment by lasjorg** [comment]
@hanswang123456 I pretty much just copied the code as found in all the other PRs made with this fix. For now, I have reverted back to a regex (with the `/` as optional).

You can look at the issue I linked to in the initial post to see how many other challenges this is affecting at the moment.

**Review by moT01 — APPROVED** [review]
LGTM @lasjorg 🎉 

For some context, we remove the href attribute when adding these links to the dom to avoid network requests, and set the url in the dataset.href so we can still reference it. See [PR](https://github.com/freeCodeCamp/freeCodeCamp/pull/45890)

**Review by naomi-lgbt — APPROVED** [review]
Should be good to go!

__
[sema-logo](https://semasoftware.com/gh) &nbsp;**Summary:** :ok_hand: This code looks good

**Pull request merged**
