### PR TITLE
fix(curriculum): Fix sentence construction

### LINKED ISSUE #49324: Invalid instruction: Step 53 learn typography by building a nutrition label
### Describe the Issue

The text below is referring to a span that doesn’t exist:

Finally, nest the Cholesterol and 0mg span elements inside an additional span element for alignment.

There is no 0mg span element in the code at this point.

### Affected Page

https://www.freecodecamp.org/learn/2022/responsive-web-design/learn-typography-by-building-a-nutrition-label/step-53

### Your code

```

```

### Expected behavior

Change the text to:
Finally, nest the Cholesterol span element and 0mg inside an additional span element for alignment.

### Screenshots

_No response_

### System

N/A

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by Sriparno08**
Checklist:

- [x] I have read and followed the [contribution guidelines](https://contribute.freecodecamp.org).
- [x] I have read and followed the [how to open a pull request guide](https://contribute.freecodecamp.org/#/how-to-open-a-pull-request).
- [x] My pull request targets the `main` branch of freeCodeCamp.
- [x] I have tested these changes either locally on my machine, or GitPod.

Closes #49324

### CODE REVIEW

**Comment by jeremylt** [comment]
Thanks for your eagerness to contribute, however, this issue has not been marked as ready for contributions yet.

**Comment by Sriparno08** [comment]
Alright, @jeremylt 👍

**Comment by raisedadead** [comment]
Hi @Sriparno08, thanks for making this PR. We just opened it up for first-timers. We look forward to your contributions to other help-wanted issues.

**Comment by Sriparno08** [comment]
Okay, @raisedadead 👍

**Pull request closed without merging**
