### PR TITLE
German Translation of Gear up for Success

### LINKED ISSUE #8150: German translation of Gear up for Success
- [x] Join our LinkedIn Alumni Network Complete
- [x] Join our Subreddit Complete
- [x] Read Coding News on our Medium Publication Complete
- [x] Watch Coding Videos on our YouTube Channel Complete
- [x] Commit to a Goal and a Nonprofit

### PR DESCRIPTION
**Pull request by 5k9m**
I completed the german translation of Gear up for Success. Would be nice if someone could proofread the changes :-)

Closes #8150

### CODE REVIEW

**Comment by theflametrooper** [comment]
@5k9m Please ask someone in the german chat room to proof read this. If no one has proofread in a week or so, then we will just merge!

**Comment by theflametrooper** [comment]
@5k9m please make sure you get the latest changes from the staging branch as you currently have conflicts.

See here: https://github.com/FreeCodeCamp/FreeCodeCamp/wiki/git-rebase#preventing-merge-conflicts

Thanks!

**Comment by raisedadead** [comment]
@5k9m @theflametrooper any updates on this?

**Comment by 5k9m** [comment]
@raisedadead sorry, I missed that there were conflicts! do I have to delete the PR and re-submit?

**Comment by theflametrooper** [comment]
@5k9m Please check my previous post (http://i654.photobucket.com/albums/uu263/Glass16/IMG_4418i.jpg~original) :wink:

**Comment by raisedadead** [comment]
@5k9m You just need to rebase this. No need to close this at all.
https://github.com/FreeCodeCamp/FreeCodeCamp/wiki/git-rebase#preventing-merge-conflicts

If you need any assistance reach out to the [Contributors Chat room](https://gitter.im/FreeCodeCamp/HelpContributors).

**Comment by 5k9m** [comment]
@theflametrooper @raisedadead I resolved the issues, tested and rebased. But what's the next step? Thank's for you help :-)

**Comment by raisedadead** [comment]
@5k9m I am on the chat, hit me up there.

**Comment by theflametrooper** [comment]
@5k9m Could you find someone to verify this translation? Try the `Translators` Chat Room.

**Comment by 5k9m** [comment]
@theflametrooper I wrote to the German translation channel - but I'm not overly confident that the response rate will be satisfactory...

**Comment by theflametrooper** [comment]
@5k9m We will wait 2 days, then i'll merge anyway ;)

**Comment by theflametrooper** [comment]
@5k9m Ok, it's been two days! If someone finds a misspelling, then can create a new PR with the changes.

Thanks for the PR!

**Pull request merged**
