### PR TITLE
fix(challenges): Edit Description, Add Tests and Solution for Project Euler 47

### PR DESCRIPTION
**Pull request by scissorsneedfoodtoo**
#### Pre-Submission Checklist

- [x] Your pull request targets the `staging` branch of freeCodeCamp.
- [x] Branch starts with either `fix/`, `feature/`, or `translate/` (e.g. `fix/signin-issue`)
- [x] You have only one commit (if not, [squash](http://forum.freecodecamp.org/t/how-to-squash-multiple-commits-into-one-with-git/13231) them into one commit).
- [x] All new and existing tests pass the command `npm test`. Use `git commit --amend` to amend any fixes.

#### Type of Change

- [x] Small bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds new functionality)
- [ ] Breaking change (fix or feature that would change existing functionality)
- [ ] Add new translation (feature adding new translations)

#### Checklist:

- [x] Tested changes locally.
- [ ] Addressed currently open issue (replace XXXXX with an issue no in next line)

Closes #XXXXX

#### Description

Edited the description to more closely match the spacing and line breaks
from projecteuler.net. Added more tests, updated the challenge seed,
and added a solution from user @elliotjz contributed to the fCC
Arcade Mode.

BREAKING CHANGE: None

Solution for QA:

```
// noprotect

function distinctPrimeFactors(targetNumPrimes, targetConsecutive) {
  
  function isPrime(num) {
    for (let i = 2, s = Math.sqrt(num); i <= s; i++) {
      if (num % i === 0) {
        return false;  
      }
    }
    return num !== 1;
  }
  
  function getPrimeFactors(num) {
    const factors = [];
    for (let i = 2; i <= Math.sqrt(num); i++) {
      if (num % i === 0) {
        // found a factor
        if (isPrime(i)) {
          factors.push(i);
        }
        if (isPrime(num / i) && i !== Math.sqrt(num)) {
          factors.push(num / i);
        }
      }
    }
    return factors;
  }
  
  function findConsecutiveNumbers() {
    let number = 0;
    let consecutive = 0;
    while (consecutive < targetConsecutive) {
      number++;
      if (getPrimeFactors(number).length >= targetNumPrimes) {
        consecutive++;
      } else {
        consecutive = 0;
      }
    }
    return (number - targetConsecutive) + 1;
  }

  return findConsecutiveNumbers();
}
```

### CODE REVIEW

**Comment by mstellaluna** [comment]
Currently working on this PR

**Review by mstellaluna — CHANGES_REQUESTED** [review]
Infinite Loop warning

**Comment by mstellaluna** [comment]
@scissorsneedfoodtoo I am trying out your solution and it's giving me a infinite loop warning for line 32 which is the while loop in the findConsecutiveNumbers function.

**Comment by scissorsneedfoodtoo** [comment]
@mstellaluna, sorry about that! Had trouble finding a working solution that doesn't trip the infinite loop warning in the editor. When you have a chance, could you try adding `// noprotect` to the first line? I've updated the solution above to include that line, too.

**Review by mstellaluna — APPROVED** [review]

**Comment by mstellaluna** [comment]
@scissorsneedfoodtoo I just tried it with `//noprotect` at the top. It's not working on the PR before your change. I deleted my local branch and grabbed your latest update, it's working now. I will go ahead and approve this PR. Thank you kindly for providing the answers, its greatly appreciated :) Thanks for your contribution. Happy Coding.

**Comment by scissorsneedfoodtoo** [comment]
@mstellaluna, as always, thank you for taking the time to QA and merge this! Sorry for the trouble you went through. Glad the solution worked in the end!

**Comment by mstellaluna** [comment]
@scissorsneedfoodtoo No trouble at all. I always check before and after pulling down a PR to see the difference in behavior :)

**Pull request merged**
