### PR TITLE
fix(client): add if private warning to the name

### PR DESCRIPTION
**Pull request by raisedadead**
With the updated cert claiming UX, we should add the warning for name to not be private like for others

### CODE REVIEW

**Comment by raisedadead** [comment]
image

**Comment by ShaunSHamilton** [comment]
@raisedadead I am fine with adding this, but sooner-or-later someone is going to point out that you can still (technically) claim and view a certificate with `name` set to `private`. _just cannot claim from the superblock_ , and the name will not appear on the certificate.

**Comment by ojeytonwilliams** [comment]
We need new copy, then.  How about:

"Your name will not appear on your certifications, if this is set to private"

**Comment by raisedadead** [comment]
> @raisedadead I am fine with adding this, but sooner-or-later someone is going to point out that you can still (technically) claim and view a certificate with `name` set to `private`. _just cannot claim from the superblock_ , and the name will not appear on the certificate.

I agree, there is a flaw in the whole UX and I think the discussions in #42893 are going to help address some of that.

With this PR I wanted to quick fix the confusion that they already are seeing. 3 items in this page are on the requirement list, and only two have the warnings. Normalizing it somewhat saves them the roundtrip of going back to that list, only to come back here again.

**Comment by raisedadead** [comment]
> We need new copy, then. How about:
> 
> "Your name will not appear on your certifications, if this is set to private."

Possibly, a good idea. I will update the PR.

**Review by ojeytonwilliams — APPROVED** [review]
LGTM :+1:

**Comment by ShaunSHamilton** [comment]
I thought we had an automated workflow to handle i18n .json?

**Comment by ojeytonwilliams** [comment]
We do, but I'm not 100% sure that the client will default to English properly if keys are missing, so it's safer to add them to all languages.

**Review by ShaunSHamilton — APPROVED** [review]
LGTM 👍

**Pull request merged**
