### PR TITLE
add: content for challenge: match whitespace

### PR DESCRIPTION
**Pull request by mariokandut**
- [x] I have read [freeCodeCamp's contribution guidelines](https://github.com/freeCodeCamp/freeCodeCamp/blob/master/CONTRIBUTING.md).
- [x] My pull request has a descriptive title (not a vague title like `Update index.md`)
- [x] My pull request targets the `master` branch of freeCodeCamp.
- [x] None of my changes are plagiarized from another source without proper attribution.
- [x] My article does not contain shortened URLs or affiliate links.

### CODE REVIEW

**Comment by RandellDawson** [comment]
Closed and Reopened this PR to attempt to resolve a specific Travis build failure.

**Comment by iepur1lla** [comment]
The Travis CI build passed. What are you trying to resolve or what is the error?

**Comment by RandellDawson** [comment]
Hi @iepur1lla,

There were about 3,100 PRs during Hacktoberfest which had build failures, but had nothing to do with the PR content.  It was a problem we had on our end.  The easiest way we found to resolve the issue was to close and reopen the PR.  Before the close/reopen the PR showed something like beloow instead of the message "All checks have passed" (like the PR now shows above).

image

**Comment by RandellDawson** [comment]
Congrats @iepur1lla  on your first pull request (PR)! 🎉

Thank you for your contribution to the page! 👍
We're happy to accept these changes, and look forward to future contributions. 📝

**Pull request merged**
