### PR TITLE
fix(client): combine donate & donate-other pages into a single page

### LINKED ISSUE #35667: Make other ways to donate expandable on the donation page instead of a separate page

### PR DESCRIPTION
**Pull request by webdevdaemon**
- [x] I have read [freeCodeCamp's contribution guidelines](https://github.com/freeCodeCamp/freeCodeCamp/blob/master/CONTRIBUTING.md).
- [x] My pull request has a descriptive title (not a vague title like `Update index.md`)
- [x] My pull request targets the `master` branch of freeCodeCamp.
- [x] None of my changes are plagiarized from another source without proper attribution.
- [x] All the files I changed are in the same world language (for example: only English changes, or only Chinese changes, etc.)
- [x] My changes do not use shortened URLs or affiliate links.

---
Closes #35667 

This is what I came up with for a first draft, I am sure there will need to be revisions - but I think this is at least a decent starting point.

Thanks for the opportunity to contribute,

{cm}

### CODE REVIEW

**Review by raisedadead — CHANGES_REQUESTED** [review]
Early feedback: 
- [x] We would want to turn the `/pages/donate-other.js` into a component instead. Gatsby is going to automatically treat anything in the `pages` directory as a page, and will generate a route for it. We do not want that.
- [x] This verbiage should be updated:
   ```diff
   -<Link to='/donate'>Return to Credit/Debit Form</Link>
   +<Link to='/donate'>Donate using a Credit or Debit card</Link>
   ```
- [x] The above `link` will cause a unnecessary re render of the entire page? We want a more simpler scroll to top or something on the likes of that IMHO.

**Comment by webdevdaemon** [comment]
__Copy That. Thanks for the Speedy Response.__
I didn't know if I was supposed to be moving around files or messing with the routes or structure at all, so I refrained.
Good to know that is not forbidden.

__Regarding Page Re-Render @ `<Link/>` click__:
I believe that the `Link` is smart enough to not re-render because when I was testing it locally, it just jumped back to the top, and left the extra options section OPEN. If it would have triggered a re-render, then the extra options should have gone back to it's default state, CLOSED. I think the gatsby Link has already solved this by jumping back to the top if `to={path}` points to the current page.

As I brainstorm other methods, this really seems to be the simplest, I don't even have to add an id tag to the form or something to target with `<a href="#top"/>`. Trust me, I would have went another "route" (pun intended) if the link was triggering a re-render every time.

Do you still want me to change it? Or, if it truly behaves as I described, is this a suitable solution?

__I'll work on the other items in the meantime.__

I really appreciate your time,

{cm}

**Comment by webdevdaemon** [comment]
I somehow screwed up a commit or something on my end, and had to figure it out. It seems ok on my end now, but I fear it may have messed up this PR somehow. All the checks have passed though, so I'm thinking I fixed it.

Sorry, some parts of this github thing still get me every now and again...

Anyways, I have updated the PR with your requested text edit and moved 
`.../pages/donate-other.js` to `.../components/Donations/DonateOther.js`
so that route/page will no longer be generated. `<DonateOther/>` is now a component.

__So, at this moment, all I am waiting for is your approval of my edits, and your thoughts regarding the use of 
`<Link to="/donate"/>`
after learning that it doesn't seem to cause a re-render and seamlessly jumps back to the form @ the top of the page
(described in further detail in my last comment).__

Thanks,

{cm}

**Comment by raisedadead** [comment]
Thanks for these changes, I think we are looking good w.r.t the link. Sorry about the confusion. I dropped that suggestion of the top of my head. 

Someone from @freeCodeCamp/dev-team will QA this soon. As you may know we have a huge backlog of PRs, thanks for your hard work and time in preparing the PR.

You should hangout with us in [Contributors Chat room](https://gitter.im/FreeCodeCamp/Contributors) to learn more about contributing to freeCodeCamp.

Happy coding.

**Comment by webdevdaemon** [comment]
Hey, no rush! I know y'all are busy, busy, busy!

I will join you guys in the chat for sure!

**Review by raisedadead — APPROVED** [review]
#### :sparkles: :sparkles: **AWESOME! LGTM.** :sparkles: :sparkles: 

Thanks @webdevdaemon, for this pull request and contributing to the code-base for the first time.
We will be looking forward for more contributions in future.

Cheers and happy contributing!

**Comment by webdevdaemon** [comment]
The pleasure's all mine. 

I'll definitely be making more PRs in the future.

Thanks again for your time and guidance.
{cm}

**Pull request merged**
