### PR TITLE
fix: restrict-usernames-that-have-redirects-or-are-page-names

### LINKED ISSUE #36708: Restrict usernames
I was able to change my username to `learn` - and when I try to view my profile, I get the learn page. We should probably not allow that, or usernames of any other pages.

Screen Shot 2019-08-28 at 10 21 18 AM

### PR DESCRIPTION
**Pull request by moT01**
I think this covers all of them. There was a typo in the `create-redirects` file that I assume was a typo.

- [x] I have read [freeCodeCamp's contribution guidelines](https://github.com/freeCodeCamp/freeCodeCamp/blob/master/CONTRIBUTING.md).
- [x] My pull request has a descriptive title (not a vague title like `Update index.md`)
- [x] My pull request targets the `master` branch of freeCodeCamp.
- [x] None of my changes are plagiarized from another source without proper attribution.
- [x] All the files I changed are in the same world language (for example: only English changes, or only Chinese changes, etc.)
- [x] My changes do not use shortened URLs or affiliate links.

Closes #36708

### CODE REVIEW

**Review by raisedadead — COMMENTED** [review]
Early comment:

Can you sort the list in the array alphabetically? I think would be useful.

**Comment by moT01** [comment]
Is it not sorted?

**Comment by moT01** [comment]
What happened here

**Comment by raisedadead** [comment]
Hold on! https://github.com/freeCodeCamp/freeCodeCamp/issues/36718

**Comment by raisedadead** [comment]
Fixed.

**Comment by moT01** [comment]
Reviewers: take a close look at the `create-redirects` file - make sure that typo I changed was actually a typo and not deliberate - also, it says `"WARNING: The order of this list is very important."` - it doesn't say anything about what the order should be, I put my changes where I thought they should be.

**Comment by raisedadead** [comment]
Is this ready for QA? You want to run `npm run test:client -- -u` to update the client snapshots that are broken.

**Comment by moT01** [comment]
I ran the suggested command from my error and it looks like it updated it...
Screen Shot 2019-08-29 at 11 20 19 AM
`npm run test:client -- -u` changed nothing else - I'm not sure why travis is failing here.

**Comment by raisedadead** [comment]
You are correct! This is in the tools now.

`npm run test:tools -- -u`

The CI says so!

**Comment by raisedadead** [comment]
Commit your changes and push the snapshot.

**Comment by moT01** [comment]
Okay, there was some struggles for me on this one - but it looks like it's ready to go.

**Review by raisedadead — APPROVED** [review]

**Pull request merged**
