### PR TITLE
Add top action row to editor

### PR DESCRIPTION
**Pull request by ahmaxed**
This pr makes tabs independent and show them in action row when ERM's are detected.

- [x] I have read [freeCodeCamp's contribution guidelines](https://contribute.freecodecamp.org).
- [x] My pull request has a descriptive title (not a vague title like `Update index.md`)
- [x] My pull request targets the `master` branch of freeCodeCamp.
- [x] All the files I changed are in the same world language, for example: only English changes, or only Chinese changes, etc.

Closes #XXXXX

### CODE REVIEW

**Review by ojeytonwilliams — APPROVED** [review]
LGTM :+1:

**Review by RandellDawson — APPROVED** [review]

**Comment by RandellDawson** [comment]
@ojeytonwilliams Do we merge it with the DEBUG commit or does it need to be removed from this PR?  If so, then we should not Squash and merge, correct?  I am fine with the changes, so merge how you like.

**Comment by ojeytonwilliams** [comment]
The DEBUG commit is just there to facilitate QA, so it can go (I'll do that).  Since you've started adding the ERMs to steps, I think we can stop creating DEBUG commits and just use those steps for QA.

**Comment by ojeytonwilliams** [comment]
Nice one, @ahmadabdolsaheb, this is really taking shape.

**Pull request merged**
