### PR TITLE
 fix test so it does not match code not in the answer

### LINKED ISSUE #3533: It is getting validated other than given description value of $($(".slot")[0]).html(slotOne);
Challenge [Waypoint: Bring your JavaScript Slot Machine to Life](http://www.freecodecamp.com/challenges/waypoint-bring-your-javascript-slot-machine-to-life) has an issue.
User Agent is: <code>Mozilla/5.0 (Windows NT 6.3; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/45.0.2454.93 Safari/537.36</code>.
Please describe how to reproduce this issue, and include links to screenshots if possible.

I have used $($(".slot")[0]).text(slotOne);  instead of $($(".slot")[0]).html(slotOne); as per the description it should be used but anyhow after using text also it is getting validated. But when i try to change for the remaining next two slots it is getting failed. I don't no why it is accepting for slot 1 alone. Please look at it and advice me on it.

If it is not bug sorry for creating it.

My code:
```html
<script>
  function runSlots(){
    var slotOne;
    var slotTwo;
    var slotThree;
    
    var images = ["http://i.imgur.com/9H17QFk.png", "http://i.imgur.com/9RmpXTy.png", "http://i.imgur.com/VJnmtt5.png"];
    
    slotOne = Math.floor(Math.random() * (3 - 1 + 1)) + 1;
    slotTwo = Math.floor(Math.random() * (3 - 1 + 1)) + 1;
    slotThree = Math.floor(Math.random() * (3 - 1 + 1)) + 1;
    
    $(".logger").html("");
    $(".logger").html("Not A Win")
    
    // Only change code below this line.
    $($(".slot")[0]).text(slotOne);
    $($(".slot")[1]).html(slotTwo);
    $($(".slot")[2]).html(slotThree);
    
    
    // Only change code above this line.
    
    if(slotOne !== slotTwo || slotTwo !== slotThree){
      return null;
    }
    
    if(slotOne !== undefined && slotTwo !== undefined && slotThree !== undefined){
      $(".logger").html(slotOne);
      $(".logger").append(" " + slotTwo);
      $(".logger").append(" " + slotThree);
    }
    
    return [slotOne, slotTwo, slotThree];
  }

  $(document).ready(function(){
     $(".go").click(function(){
       runSlots();
     });
   });
</script>
 
<div>
 <div class = "container inset">
   <div class = "header inset">
     <img src="https://s3.amazonaws.com/freecodecamp/freecodecamp_logo.svg.gz" alt="learn to code javascript at Free Code Camp logo" class="img-responsive nav-logo">
     <h2>FCC Slot Machine</h2>
   </div>
   <div class = "slots inset">
     <div class = "slot inset">
       
     </div>
     <div class = "slot inset">
       
     </div>
     <div class = "slot inset">
       
     </div>
   </div>
   <br/>
   <div class = "outset">
     <button class = "go inset">
       Go
     </button>
   </div>
   <br/>
   <div class = "foot inset">
     <span class = "logger"></span>
   </div>
 </div>
</div>

<style>
 .container {
   background-color: #4a2b0f;
   height: 400px;
   width: 260px;
   margin: 50px auto;
   border-radius: 4px;
 }
 .header {
   border: 2px solid #fff;
   border-radius: 4px;
   height: 55px;
   margin: 14px auto;
   background-color: #457f86
 }
 .header h2 {
   height: 30px;
   margin: auto;
 }
 .header h2 {
   font-size: 14px;
   margin: 0 0;
   padding: 0;
   color: #fff;
   text-align: center;
 }
 .slots{
   display: flex;
   background-color: #457f86;
   border-radius: 6px;
   border: 2px solid #fff;
 }
 .slot{
   flex: 1 0 auto;
   background: white;
   height: 75px;
   margin: 8px;
   border: 2px solid #215f1e;
   border-radius: 4px;
   text-align: center;
   padding-top: 25px;
 }
 .go {
   width: 100%;
   color: #fff;
   background-color: #457f86;
   border: 2px solid #fff;
   border-radius: 2px;
   box-sizing: none;
   outline: none!important;
 }
 .foot {
   height: 150px;
   background-color: 457f86;
   border: 2px solid #fff;
 }
 
 .logger {
   color: white;
   margin: 10px;
 }
 
 .outset {
   -webkit-box-shadow: 0px 0px 15px -2px rgba(0,0,0,0.75);
   -moz-box-shadow: 0px 0px 15px -2px rgba(0,0,0,0.75);
     box-shadow: 0px 0px 15px -2px rgba(0,0,0,0.75);
 }
 
 .inset {
   -webkit-box-shadow: inset 0px 0px 15px -2px rgba(0,0,0,0.75);
   -moz-box-shadow: inset 0px 0px 15px -2px rgba(0,0,0,0.75);
   box-shadow: inset 0px 0px 15px -2px rgba(0,0,0,0.75);
 }
</style>

```

### PR DESCRIPTION
**Pull request by natac13**
closes #3533

### CODE REVIEW

**Comment by bugron** [comment]
@natac13 could you, please, do the same thing for other Slot machine challenges? Just to be sure that this part of code is the same in these challenges, thanks.

**Comment by natac13** [comment]
@bugron I believe I messed up with the last rebase.
I ran these commands:
```
git checkout staging
git fetch upstream
git merge upstream/staging
git checkout [the branch that is the PR]
git rebase staging
// resolved the conflicts and pushed
```

**Comment by bugron** [comment]
@natac13 that's the way I resolve merge conflicts so it'll work.

**Comment by QuincyLarson** [comment]
@bugron @natac13 I went ahead and fixed the second instance, myself. I've merged this. Thank you for your help.

**Pull request merged**
