### PR TITLE
feat(client): modify breadcrumb design

### LINKED ISSUE #40832: Optimizing challenge breadcrumb UI
In the upcoming iteration of the Ui, the breadcrumb seems squeezed and crowded. 

Although the underline clearly indicates the functionality of the breadcrumb elements, separating the interactive breadcrumb text from the challenge title with an underline will allow us to get away with not adding underlines.

We could consider the following options:
- since we have associated an icon with the superblocks, we could use that instead of the superblock's name to save space.
- text could be smaller since those navigation items are not used as often.

Here are a few alternatives:
(left is the current iteration and right seems to be the easiest to implement) 

Screen Shot 2021-01-29 at 4 00 09 PM

### PR DESCRIPTION
**Pull request by naomi-lgbt**
Checklist:

- [X] I have read [freeCodeCamp's contribution guidelines](https://contribute.freecodecamp.org).
- [X] My pull request has a descriptive title (not a vague title like `Update index.md`)
- [ ] My pull request targets the `master` branch of freeCodeCamp.
- [X] All the files I changed are in the same world language, for example: only English changes, or only Chinese changes, etc.

Closes #40832 

@ahmadabdolsaheb I took your suggestion of using the superblock icon for the breadcrumbs to allow more space for the block name - helps a bit with responsiveness.

### CODE REVIEW

**Review by raisedadead — COMMENTED** [review]
Thanks for the PR. 

Currently this:

image

IMHO, we almost never use "only icons" as a navigation element for a11y reasons. 

I think I am in favor of @ahmadabdolsaheb [second proposal in his screenshot](https://user-images.githubusercontent.com/4591597/106278931-a0d0b100-624c-11eb-916e-5ce01754bc77.png) which looks aesthetically pleasing. 

As for managing space I think we could 'trim' the items safely assuming that the users can make an educated guess of the page they will go back to.

Here is an example of a long bread crumb:


`Responsive Web Design >> Responsive Web Design Principles >> Use a Retina Image for Higher Resolution Displays`

which could be trimmed like so

```
    Res... > Responsive Web Design Principles 
---------------------------------------------------
 Use a Retina Image for Higher Resolution Displays
```

where the elements are the full names of the superblocks and blocks, but are clipped with css.

**Comment by nhcarrigan** [comment]
Sounds good - I will update this in the morning 🙂

**Comment by raisedadead** [comment]
Thanks @nhcarrigan - do not worry about rushing this in. This can wait till Monday or even after we have shipped. BTW, I have re-targeted and re-base this branch.

**Comment by nhcarrigan** [comment]
Okay I think I've got this locked down:

Large screen
image

Small screen:
image

Mobile:
image

**Review by raisedadead — APPROVED** [review]
Being nitpicky: I think we could do some white spacing between the two lines, which to me look a tad odd versus rest of the instruction panel. But I will defer that to be looked at by @ahmadabdolsaheb later.

For now, this looks good. Nice work.

Waiting for the tests to pass, which stalled for some reason earlier.

**Pull request merged**
