### PR TITLE
Fixes '$(...).css(...) is undefined' error

### LINKED ISSUE #3242: $(...).css(...) is undefined in task item
Challenge http://freecodecamp.com/challenges/waypoint-inherit-styles-from-the-body-element has an issue. User Agent is: <code>Mozilla/5.0 (Windows NT 10.0, WOW64
screenshot

### PR DESCRIPTION
**Pull request by bugron**
Closes #3242. More info about the fix be found [here](http://stackoverflow.com/questions/784929/what-is-the-not-not-operator-in-javascript).

### CODE REVIEW

**Comment by BerkeleyTrue** [comment]
I don't think this is the root cause of that issue or it would be popping up everywhere. Assert already detects if a value is truey or falsey by its nature. Casting it to a bool shouldn't make a difference to assert.

**Comment by bugron** [comment]
@BerkeleyTrue It seems in this case for some reason `assert` is not detecting `undefined` as a falsey value. I can reproduce this issue when I open the challenge in my browser only first time. After `F5` or clicking 'Run tests' this error vanishes. I tried in my local `!!` and it worked so I created a PR.

**Comment by ahstro** [comment]
Sorry to dissapoint, but this doesn't resolve the issue for me. See [my comment](https://github.com/FreeCodeCamp/FreeCodeCamp/issues/3242#issuecomment-139799537) in #3242 for more details.

**Comment by bugron** [comment]
@ahstro yeah, seems this a problem only in FF. I'll leave this PR open for some time. If there won't be any suggestions, I'll close it.

**Comment by BerkeleyTrue** [comment]
@bugron Thanks but we need to find the root cause of this in FF.

**Comment by bugron** [comment]
@BerkeleyTrue OK, no problem.

**Pull request closed without merging**
