### PR TITLE
fix(learn): Strengthen another test in "Remove Elements from a Linked List"

### PR DESCRIPTION
**Pull request by TyMick**
Checklist:

- [x] I have read [freeCodeCamp's contribution guidelines](https://contribute.freecodecamp.org).
- [x] My pull request has a descriptive title (not a vague title like `Update index.md`)
- [x] My pull request targets the `master` branch of freeCodeCamp.
- [x] All the files I changed are in the same world language, for example: only English changes, or only Chinese changes, etc.

In a sequel to #39977, I have found another bug in my original code for this challenge: when my `remove` method was passed an element that was present in the list but wasn't the list's `head`, it would remove every node from `head.next` through the node containing that element. I was using a `while` loop with `currentNode` and `previousNode` variables but was forgetting to update `previousNode` at the end of the loop, so when it found the element, it would link `head` all the way to `currentNode.next` no matter how far it had traveled.

Anyway, here's an update to test #&zwnj;4 ("Your <code>remove</code> method should reassign the reference of the previous node of the removed node to the removed node&apos;s <code>next</code> reference.") that'll catch mistakes like mine in the future, by having the test remove the third node of four in the list instead of the second node of three.

### Updated test:

```js
assert(
  (function () {
    var test = new LinkedList();

    test.add("cat");
    test.add("dog");
    test.add("snake");
    test.add("kitten");

    test.remove("snake");
    return test.head().next.next.element === "kitten";
  })()
);
```

-----

All tests are passing on my end. 👍🏼

```shell
freeCodeCamp % cd curriculum
curriculum % npm run test -- -g "Remove Elements from a Linked List"
...
  22 passing (5s)
```

### CODE REVIEW

**Review by moT01 — APPROVED** [review]
LGTM 🎉

**Comment by RandellDawson** [comment]
@tywmick Just to clarify the intent of this PR, are you saying you had code that would pass all the existing tests but not fulfill the challenge instructions?  If so, can you provide the code that did this?

**Comment by tywmick** [comment]
@RandellDawson Yep, sure thing! Here's the solution I previously submitted to this challenge:

```js
function LinkedList() {
  var length = 0;
  var head = null;

  var Node = function (element) {
    this.element = element;
    this.next = null;
  };

  this.size = function () {
    return length;
  };

  this.head = function () {
    return head;
  };

  this.add = function (element) {
    var node = new Node(element);
    if (head === null) {
      head = node;
    } else {
      var currentNode = head;

      while (currentNode.next) {
        currentNode = currentNode.next;
      }

      currentNode.next = node;
    }

    length++;
  };

  this.remove = function (element) {
    // Only change code below this line
    if (head.element === element) {
      head = head.next;
      length--;
    } else {
      // Search for element
      let currentNode = head.next;
      let previousNode = head;
      while (currentNode) {
        if (currentNode.element === element) {
          previousNode.next = currentNode.next;
          length--;
          break;
        }
        currentNode = currentNode.next;
      }
    }
    // Only change code above this line
  };
}
```

I forgot to include `previousNode = currentNode;` on the line before `currentNode = currentNode.next;` at the end of my loop.

If you paste that into the [current version](https://www.freecodecamp.org/learn/coding-interview-prep/data-structures/remove-elements-from-a-linked-list) of this challenge, it passes all five tests, but if you add the following lines to the bottom of the file...

```js
var test = new LinkedList();
test.add("cat");
test.add("dog");
test.add("snake");
test.add("kitten");
test.remove("snake");
console.log(test.head());
```

...here's what the console shows:

```
{ element: 'cat', next: { element: 'kitten', next: null } }
```

So my old `remove` method removes both `"dog"` and`"snake"` when it's only supposed to remove `"snake"`.

**Review by RandellDawson — APPROVED** [review]

**Comment by RandellDawson** [comment]
Thank you @tywmick for your contribution to the page! 👍
We're happy to accept these changes, and look forward to future contributions. 🎉

**Pull request merged**
