### PR TITLE
fix : Unclear test output use-array.map-to-dynamically-render-elements

### LINKED ISSUE #38170: Unclear test output - use-array.map-to-dynamically-render-elements
**Describe your problem and how to reproduce it:**

**1) Go to:** https://www.freecodecamp.org/learn/front-end-libraries/react/use-array.map-to-dynamically-render-elements
**2) Then:** look for the third expected test output on the left-bottom UI of the challenge.

**3) What it says:** 

> The third child of MyToDoList should be a button element.

**4) what it should says:**

> The second child of MyToDoList should be a button element.

**Add a Link to the page with the problem:**
https://www.freecodecamp.org/learn/front-end-libraries/react/use-array.map-to-dynamically-render-elements

**Tell us about your browser and operating system:**
* Browser Name: Chrome
* Browser Version: 79
* Operating System: Mac OS 10.13.6

**If possible, add a screenshot here (you can drag and drop, png, jpg, gif, etc. in this box):**
Captura-de-pantalla-2020-02-05-a-la(s)-10 59 39-p -m

### PR DESCRIPTION
**Pull request by kundan59**
- [x] I have read [freeCodeCamp's contribution guidelines](https://github.com/freeCodeCamp/freeCodeCamp/blob/master/CONTRIBUTING.md).
- [x] My pull request has a descriptive title (not a vague title like `Update index.md`)
- [x] My pull request targets the `master` branch of freeCodeCamp.
- [x] None of my changes are plagiarized from another source without proper attribution.
- [x] All the files I changed are in the same world language (for example: only English changes, or only Chinese changes, etc.)
- [x] My changes do not use shortened URLs or affiliate links.

Closes #38170

### CODE REVIEW

**Comment by kundan59** [comment]
Hi, @ojeytonwilliams @raisedadead @RandellDawson I think I didn't have correct forked codebase and it's very complex to analyze this because of my work on the master branch so, I have created this new pull request hope it will work. Please close this Pr https://github.com/freeCodeCamp/freeCodeCamp/pull/38172

**Comment by RandellDawson** [comment]
@kundan59 You still need to resolve the issue mentioned in [the comment of the other PR](https://github.com/freeCodeCamp/freeCodeCamp/pull/38172#issuecomment-584206358).  I closed the other since you deleted the branch.

**Comment by kundan59** [comment]
Hi @raisedadead Travis support clear that of my flagged account. could you please push force to tigger travis.

**Comment by raisedadead** [comment]
Great, thanks for confirming. I think you should be able to force push yourself to that the CI will work correctly:

```
git checkout <you pr branch name>
git pull --rebase upstream master
git push --force
```

**Comment by kundan59** [comment]
Hi, @raisedadead I am a bit confused locally npm run lint successful. but at Travis ignore this. Do you have any idea?
image

**Comment by ojeytonwilliams** [comment]
So, Travis is testing the Arabic challenges (which fail) since it's missing repository environment variables.  I pushed a copy to my fork and saw:
> Setting environment variables from repository settings
$ export LOCALE=english
$ export TEST_CHALLENGES_FOR_LANGS=english

but that doesn't appear on @kundan59's.

Compare my copy of this branch https://travis-ci.com/ojeytonwilliams/freeCodeCamp/jobs/286248778
to https://travis-ci.com/kundan59/freeCodeCamp/jobs/286231989

I'm not sure *why* this is happening, but that seems to be the problem.

**Comment by kundan59** [comment]
@ojeytonwilliams right these two environment variables of repository settings are missing. But how this happened?

**Comment by kundan59** [comment]
Hi, @raisedadead @ojeytonwilliams when I provide these environment variables externally, Travis successfully build this job.
image

**Comment by raisedadead** [comment]
@kundan59 

That is build that you have on your fork. It's optional and not required by us. Those variables do not affect this PR. The CI checks are done on our own account, but your user account was flagged by Travis for some reason, which prevented us from running the builds. 

Please follow the instructions that I gave you in the previous comment and rebase. That should be enough from your side.

**Comment by kundan59** [comment]
@raisedadead I am done with push force as you mention above let see whether it work or not.

**Comment by raisedadead** [comment]
@kundan59 I think you account is still flagged by Travis for some reason:

List of build requests from freeCodeCamp:
image

Corresponding commit:
image

**Comment by raisedadead** [comment]
OK - I have sent a request to travis support. I will update on the status.

**Pull request merged**
