### PR TITLE
feat: show sign in button for unauthenticated users

### PR DESCRIPTION
**Pull request by raditotev**
- [x] I have read [freeCodeCamp's contribution guidelines](https://contribute.freecodecamp.org).
- [x] My pull request has a descriptive title (not a vague title like `Update index.md`)
- [x] My pull request targets the `main` branch of freeCodeCamp.
- [x] I have tested these changes either locally on my machine, or GitPod.

* Add Sign up to save progress button above all elements in the lower jaw for un-auth users in  #46178

### CODE REVIEW

**Review by raisedadead — DISMISSED** [review]
LGTM. And thanks for fixing those typos.

**Comment by raditotev** [comment]
At a second glance I am even tempted to do one more change:

```diff
{earliestAvailableCompletion ? (
+            <button
+             id='submit-button'
-            aria-hidden={!earliestAvailableCompletion}
+              className='btn-block btn'
+              onClick={tryToSubmitChallenge}
+             ref={submitButtonRef}
+            >
+              {t('buttons.submit-and-go')}
+            </button>
          ) : (
            <button
              id='test-button'
              className={`btn-block btn`}
              aria-hidden={testBtnariaHidden}
              onClick={tryToExecuteChallenge}
            >
              {showDesktopButton
                ? t('buttons.check-code')
                : t('buttons.check-code-2')}
            </button>
          )}
```

**Comment by raditotev** [comment]
I have decided to go ahead and make the changes I suggested in the previous comment. You can see the changes in isolation in the last [commit](https://github.com/freeCodeCamp/freeCodeCamp/pull/46401/commits/63135d6dc732fa7b6f9f36f454b7f9cbd55b2f16).
I think it is more elegant but I might be biased 😄 If you don't share my thoughts let me know and I will remove it.

**Comment by bbsmooth** [comment]
I hate to be the bearer of bad news but these changes have broken focus management for screen readers when they complete the step. Originally, when the user sets the focus on the check your code button and activates it with the keyboard then the congratulations message would be announce first, the focus would be set on the submit button, and then the screen reader would announce the submit button (after the congrats message had completed). With the changes in this PR, the congratulations message is still being announced but the submit button is not being announced at all. This is happening in both NVDA and JAWS so I think it is being caused by a change on our end.

My guess is that this is a result of this PR changing how the submit button is injected into the DOM. Originally it was always there but hidden with `aria-hidden` until needed. Now it is being injected only after the user has successfully completed the step and the accessibility tree does not have enough time to update before focus is being set on the submit button. I think we will need to go back to the original `aria-hidden` version. We may also need to add the `setTimeout` back in to make sure focus on the submit button is delayed a little to give the aria live region a chance to start.

**Comment by raditotev** [comment]
Thanks @bbsmooth. I'll revert the changes. I have made one more change with the intention to improve screen readers experience. This is the `check-code` button and this is the change:
```diff
 <button
          id='test-button'
          className={`btn-block btn 
-                                  ${earliestAvailableCompletion ? 'sr-only' : ''}
                                `}
          aria-hidden={testBtnariaHidden}
          onClick={tryToExecuteChallenge}
        >
          {showDesktopButton
            ? t('buttons.check-code')
            : t('buttons.check-code-2')}
        </button>
```
My thinking was that if the button is 'visible' on screen readers only when challenge is complete it may be confusing and annoying to users. What is your take on this?

**Comment by ojeytonwilliams** [comment]
The a11y regression sounds like something we could have caught with a Cypress test, since it involves tracking focus. @bbsmooth you're probably the best person for this, since you have the clearest understanding of the requirements. Would you be up for creating that test?

**Comment by raditotev** [comment]
Manually tested latest changes on screen reader and it looks like it works like it does in production.
Submit challenge > Test complete; "Congratulations ...." > Focus on `submit-and-go` button; "Press Option+Control+Space to click button"

**Comment by raditotev** [comment]
> During the rework I saw sr-only bootstrap class used to hide the check-code button upon challenge completion. In my opinion this could be confusing and/or annoying for people using screen readers, therefore I have changed the logic used to toggle this button's visibility.

`sr-only` class is needed because we want this element to be available for screen readers half a second after a challenge is completed but we don't want to be visible. If removed button is visible for half a second before it is hidden which results in an unpleasant flick.

**Comment by bbsmooth** [comment]
@raditotev the reversions are working fine now, the submit button is being read again.

Unfortunately, I have discovered other issues that I must have missed when I originally tested the accessibility fixes we put in place in the lower jaw :-( To be clear, these issues already exist on production, they are not a side effect of this PR. I'm all for going ahead with this PR and then I can start another PR to fix these missed issues I am finding.

@ojeytonwilliams I think we should hold off on the cypress tests until we have these additional issues fixed.

**Review by raisedadead — APPROVED** [review]

**Comment by Sembauke** [comment]
image

**Review by Sembauke — APPROVED** [review]

**Pull request merged**
