### PR TITLE
fix(UI): Prevent overlapping of 'Read-Search-Ask' link in 'Ask for Help' Modal

### PR DESCRIPTION
**Pull request by Sriparno08**
Checklist:

- [x] I have read and followed the [contribution guidelines](https://contribute.freecodecamp.org).
- [x] I have read and followed the [how to open a pull request guide](https://contribute.freecodecamp.org/#/how-to-open-a-pull-request).
- [x] My pull request targets the `main` branch of freeCodeCamp.
- [x] I have tested these changes either locally on my machine, or GitPod.

Closes #52233

I have changed the link styles to prevent it from overlapping.

Screenshot 2023-11-06 143026

Tested on: Chrome 119

### CODE REVIEW

**Review by huyenltnguyen — COMMENTED** [review]
Hey @Sriparno08, thank you for the PR!

Unfortunately CI failed because of the code formatting, so please help revert the formatting changes. Additionally, please help specify in the PR description which browser you have tested the change on.

Let us know if you need any assistance from us.

**Comment by Sriparno08** [comment]
Hey @huyenltnguyen, I have done the necessary changes. Have a look.

**Review by asdotdev — COMMENTED** [review]
The PR resolves the overlapping underline issue and shows underline on the default position.


However, if needed offset then it shouldn't be set to 1em as it is offset from the default position so when text wraps it overlaps the text following line.
```
text-underline-position: under;
```
```
@supports not (text-underline-position: under) {
  a {
    text-underline-offset: 1em;
  }
}
```
"%" is not supported by Safari so either a fixed "px" value or some fraction of the "em" value can be used.

**Comment by Sriparno08** [comment]
If we're not using:

```css
text-underline-position: under;
``` 

Then, do we need the following?

```css
@supports not (text-underline-position: under) {
  a {
    text-underline-offset: 1em;
  }
}
```

If we need an offset, we can simply include `text-underline-offset` under the `a` selector:
```css
a {
  color: inherit;
  text-decoration: underline;
  text-underline-offset: 1em;
}
```

Also, a value of `0.1em` looks good:

Screenshot 2023-11-08 143335

**Comment by moT01** [comment]
Just for reference, I found where this got added: https://github.com/freeCodeCamp/freeCodeCamp/pull/50571. The linked issue in that PR says that the underlines weren't very visible in Arabic - so we could try to make sure this doesn't reintroduce that problem.

**Comment by Sriparno08** [comment]
According to the linked PR, the following code solves underline problems in all languages:

```css
a {
  color: inherit;
  text-decoration: underline;
  text-underline-position: under;
}

@supports not (text-underline-position: under) {
  a {
    text-underline-offset: 1em;
  }
}
```

Now, there are two things that can be done.

If we want to keep the underline and prevent it from overlapping, we can go for the following:

```css
a {
  color: inherit;
  text-decoration: underline;
  text-underline-position: under;
  text-underline-offset: -0.2em;
}
```

The above code puts the underline in the `under` position but then offsets it upwards, which prevents it from overlapping.

Moreover, since we are using:

```css
text-underline-position: under;
```

We can keep the `@supports` block but set `text-underline-position` to `0.1em` or some other value to prevent the underline from overlapping:

```css
@supports not (text-underline-position: under) {
  a {
    text-underline-offset: 0.1em;
  }
}
```

**Comment by Sriparno08** [comment]
Hey, I have tested it locally.

Let's take the following code:

```css
a {
  color: inherit;
  text-decoration: underline;
  text-underline-position: under;
}

@supports not (text-underline-position: under) {
  a {
    text-underline-offset: 1em;
  }
}
```

**Heading Elements:**

If `text-underline-position` is supported and the `line-height` of all the heading elements is set to `1.4`:



If `text-underline-position` is unsupported, the `line-height` of all the heading elements is set to `1.4` and `text-underline-offset` is set to `3.5px`:



**Paragraph Elements:**

If `text-underline-position` is supported:



If `text-underline-position` is unsupported and `text-underline-offset` is set to `3.5px`:

**Comment by Sriparno08** [comment]
Hey @huyenltnguyen, @amitabh-sahu and @moT01, take a look at the test results. They are looking fine to me.

**Pull request closed without merging**
