### PR TITLE
Clarify Make a Person instructions & add ES trans

### LINKED ISSUE #7366: Make a Person: no definition of "arity"
It's strange that the description for this exercise says "All functions that take an argument have an **arity **of 1, and the argument will be a string.", when it's simpler just to say something like "All functions that take arguments, take one argument that is a string". Also I feel that the word "arity" is an outdated word after googling the word and finding out that it used to be a property of functions but is now [deprecated](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Function/arity)

### PR DESCRIPTION
**Pull request by erictleung**
Tested locally. Passes `npm run test-challenges`. Closes #7366.
- Remove use of arity and rewrite with better description
- Change use of "function" to "method" for consistency
- Put methods into blockquote tags
- Update Spanish translation of challenge (as suggested in #7380) -- Let me know if the translation needs any update

### CODE REVIEW

**Comment by vtamara** [comment]
You deleted the translation of:  "These methods must be the only available means of interacting with the object.", that was "Estos métodos deben ser el único medio para interactuar con el objeto"

**Comment by erictleung** [comment]
Thanks @vtamara! I put that sentence back now.

**Comment by erictleung** [comment]
Welp, the "Update branch" button didn't do what I thought it was going to do. I'll locally just force push it onto my branch to get rid of that merge branch.

**Comment by vtamara** [comment]
Good job @erictleung

**Pull request merged**
