### PR TITLE
docs: add docsify tabs to how-to-setup-freecodecamp-locally.md

### PR DESCRIPTION
**Pull request by goetsche101**
Checklist:

- [x] I have read [freeCodeCamp's contribution guidelines](https://contribute.freecodecamp.org).
- [x] My pull request has a descriptive title (not a vague title like `Update index.md`)
- [x] My pull request targets the `main` branch of freeCodeCamp.
- [x] I have tested these changes either locally on my machine, or GitPod.

Closes #XXXXX

Added tabs to macOS/Linux & Windows commands in the "how-to-setup-freecodecamp-locally.md"
Changes were made to the index.html to facilitate the additional functionality.
Changes were viewed and tested locally on MacOS

### CODE REVIEW

**Review by ojeytonwilliams — APPROVED** [review]
Nice!  This is much tidier.

LGTM :+1:

**Review by ShaunSHamilton — APPROVED** [review]
This LGTM 👍 

---

General notes, though:
- The tabs are not great for accessibility
  - Maybe there are settings to improve this?
- @nhcarrigan What will happen to the `<!-- tabs:xxx -->` comments in Crowdin?
  - I will leave it to you to merge or not, based on this.

**Comment by nhcarrigan** [comment]
I will have to do some investigation on this one.

**Comment by goetsche101** [comment]
I do not see any settings specific to accessibility in the documents page for docsify/tabs.  Nor' anywhere else in docsify documents really.  --What access features are we worried about here?  Maybe the "screen reader" ?  Not certain I can resolve anything, but at least I could understand what happens.

I also briefly looked at the Spanish translation and it came out pretty unusual.  Does translation work in the local environment?  Or require some additional setup.?
This is what it looked like local:
image

**Comment by ieahleen** [comment]
@goetsche101 what’s Wrong with it? Do you mean the parts in English? The file has not all strings translated and approved, it will be in future when the Spanish translation team will have finished with that

**Comment by ieahleen** [comment]
@goetsche101 yeah, it's different files. The spanish files are inside docs/i18n/espanol

**Comment by goetsche101** [comment]
Ahh!  lol.  I failed to notice the /espanol/ portion of the URL.   

Would setting it up in the spanish folder be helpful?

**Comment by ShaunSHamilton** [comment]
> do we think the accessibility is noticeably worse with the introduction of the tabs?

Personally, no. My approval is still valid, all pending whether we want to merge this, and deal with Crowdin issues as they arise, or beforehand.

**Review by raisedadead — APPROVED** [review]

**Pull request merged**
