### PR TITLE
chore: update deps for preparing migration

### PR DESCRIPTION
**Pull request by raisedadead**

### CODE REVIEW

**Comment by raisedadead** [comment]
Note: I am experimenting a better way of doing `npm audit` with https://github.com/freeCodeCamp/freeCodeCamp/commit/54bafb877ff090d312682b5406b85305a07da965, this is not run currently. Maybe kept or dropped.

**Comment by raisedadead** [comment]
I am removing the snapshot testing because they are different every time.
 https://github.com/freeCodeCamp/freeCodeCamp/commit/d3e4788116d027ab635878bf859821a77dbc6185

Kept beating around the bush, before realising. @moT01 may have more idea hopefully.

**Comment by raisedadead** [comment]
I am removing the snapshot testing because they are different every time.
 https://github.com/freeCodeCamp/freeCodeCamp/commit/d3e4788116d027ab635878bf859821a77dbc6185

@moT01 may have more idea hopefully.

**Comment by moT01** [comment]
If it's just the one test on the one component, I don't have a problem with removing it. Could maybe add some other tests to make up for it.

Not sure why Travis is failing, you deleted the snapshot and removed the test.

**Comment by raisedadead** [comment]
Thanks Tom, I just dropped that experimental commit as well. This should be good to go.

**Pull request merged**
