### PR TITLE
fix(client,server): usernames should not be a http error code

### PR DESCRIPTION
**Pull request by raisedadead**
Handle username restrictions

### CODE REVIEW

**Review by ojeytonwilliams — COMMENTED** [review]
@raisedadead Everything looks fine, but it occurs to me that it's a tiny bit better to have it reject invalid characters before rejecting short usernames.

If you agree, I can update the tests, otherwise it's good to go.

**Comment by raisedadead** [comment]
Sure go ahead.

**Review by ojeytonwilliams — APPROVED** [review]
LGTM, but I then just changed it, so I'll not merge it.

**Comment by picoPWR** [comment]
So this is the reason my `404` username stopped working. I was so proud of it too! 😆

**Pull request merged**
