### PR TITLE
Added Gordon Zhu's Practical JavaScript

### PR DESCRIPTION
**Pull request by michaelwright74**
Added Gordon Zhu's Practical JavaScript - Watch and Code to Video Tutorials section

- [x ] I have read [freeCodeCamp's contribution guidelines](https://github.com/freeCodeCamp/freeCodeCamp/blob/master/CONTRIBUTING.md).
- [x ] My pull request has a descriptive title (not a vague title like `Update index.md`)
- [x ] My pull request targets the `master` branch of freeCodeCamp.
- [x ] None of my changes are plagiarized from another source without proper attribution.
- [ x] My article does not contain shortened URLs or affiliate links.

If your pull request closes a GitHub issue, replace the XXXXX below with the issue number.

Closes #XXXXX

### CODE REVIEW

**Comment by moT01** [comment]
Links are supposed to use the format described in the [style guide](https://github.com/freeCodeCamp/freeCodeCamp/blob/master/docs/style-guide-for-guide-articles.md) - see the `links` area - how about you fix up this whole page?

**Comment by michaelwright74** [comment]
Challenge accepted, but what should I do with links that don't work with https?

**Comment by moT01** [comment]
awesome @michaelwright74 !
use `http` i suppose?
this one looks like it doesn't exist anymore - https://devchat.tv/js-jabber
Should I reopen this, or do you want to make a new PR?

**Comment by michaelwright74** [comment]
The style guide says to always use https so I wasn't sure. I did ask in the forum about it but didn't really get a conclusive answer. 
I'm checking all the links as I edit them so I'll delete any that don't work anymore.
Since I've already made a start I'll just make a new PR.

**Comment by moT01** [comment]
I would say to leave them in there as `http` - many of those links are relevant and it seems like a dumb reason to remove them - perhaps the guide should be updated to say to use HTTPS whenever possible.

**Comment by michaelwright74** [comment]
I think I've messed up (I'm still new to all this). Seems I've only updated my own master rather than the actual FCC one.

**Comment by moT01** [comment]
That's how you're supposed to do it - change the code on your fork, and create a PR into the FCC one - at the top of the PR it says "michaelwright74 wants to merge 1 commit into freeCodeCamp:master from michaelwright74:patch-3" - that's correct - thanks for fixing it up, it looks great!

**Pull request closed without merging**
