### PR TITLE
correct grammar in description for PrioriyQueue challenge

### PR DESCRIPTION
**Pull request by JoolsMcFly**
#### Pre-Submission Checklist

- [x] Your pull request targets the `staging` branch of freeCodeCamp.
- [x] Branch starts with either `fix/`, `feature/`, or `translate/` (e.g. `fix/signin-issue`)
- [x] You have only one commit (if not, [squash](http://forum.freecodecamp.com/t/how-to-squash-multiple-commits-into-one-with-git/13231) them into one commit).
- [x] All new and existing tests pass the command `npm test`. Use `git commit --amend` to amend any fixes.

#### Type of Change

- [x] Small bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds new functionality)
- [ ] Breaking change (fix or feature that would change existing functionality)
- [ ] Add new translation (feature adding new translations)

#### Checklist:

- [x] Tested changes locally.
- [ ] Closes currently open issue (replace XXXX with an issue no): Closes #XXXX

#### Description

changed _We've start**ing** writing_ to _We've start**ed** writing_ in challenge's description.

### CODE REVIEW

**Review by erictleung — APPROVED** [review]
LGTM! 👍 Thanks for contributing! 🎉

**Comment by QuincyLarson** [comment]
@JoolsMcFly thanks for fixing this!

**Comment by JoolsMcFly** [comment]
Np!

**Comment by sshepanski7** [comment]
It's been way to long this way I just got out of a cell with no moving air
no running water a camera faceing the toilet for 12 hours for another sum
afence with proof I didn't do it I had my hands smashed by a cop with a
clip board and threaten to have my face smashed in this is the 5th time I
got tons more !!!

Spanky
Show quoted text


Spanky

**Pull request merged**
