### PR TITLE
Fix/overflow

### PR DESCRIPTION
**Pull request by IsmaelEzequiel**
#### Pre-Submission Checklist

- [x] Your pull request targets the `staging` branch of freeCodeCamp.
- [x] Branch starts with either `fix/`, `feature/`, or `translate/` (e.g. `fix/signin-issue`)
- [x] You have only one commit (if not, [squash](http://forum.freecodecamp.com/t/how-to-squash-multiple-commits-into-one-with-git/13231) them into one commit).
- [x] All new and existing tests pass the command `npm test`. Use `git commit --amend` to amend any fixes.

#### Type of Change

- [x] Small bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds new functionality)
- [x] Breaking change (fix or feature that would change existing functionality)
- [x] Add new translation (feature adding new translations)

#### Checklist:

- [x] Tested changes locally.
- [x] Closes currently open issue (replace XXXX with an issue no): Closes #XXXX

### CODE REVIEW

**Comment by dhcodes** [comment]
@IsmaelEzequiel what is this fixing? You also should [squash your commits](https://forum.freecodecamp.org/t/how-to-squash-multiple-commits-into-one-with-git/13231).

**Comment by texas2010** [comment]
Please add issue number too. thanks

**Comment by IsmaelEzequiel** [comment]
Sorry, I'll close this. That's my first time trying to contribute.
When I'm on challenges page, the page are more bigger then my screen and show an overflow at bottom. With overflow-x: hidden, the content appears normal.

**Comment by BerkeleyTrue** [comment]
@IsmaelEzequiel Please open an issue first so that we may address the issue before opening a PR.

Happy Coding

**Pull request closed without merging**
