### PR TITLE
Fix randomly failing test on conditional logic waypoint

### LINKED ISSUE #1974: Waypoint: Use Conditional Logic with IfElse Statements fails at random
The first test case fails at random, even with a right solution. Reported in Gitter

### PR DESCRIPTION
**Pull request by benschenker**
closes #1974.
Need to save function invocation in variable and check both possible values.

Had some issues deploying locally to test but was able to show that improved function works 100% of the time vs the 75% of the old one: https://jsbin.com/xojobe/edit?js,console

Is there a reason that the formatting in the challenges JSON files is so wonky?

### CODE REVIEW

**Comment by BerkeleyTrue** [comment]
Please change the title to be descriptive of the changes you have made.

Also state which issues, if any, that this PR closes in the description each on its own line. For example: `closes #1337`

**Comment by BerkeleyTrue** [comment]
What is wrong with the json formating?

**Comment by benschenker** [comment]
Well it seems a bit kludgey to stuff an assertion function with regex into a string.  That requires escaping of all the slashes and makes the code much harder to follow/spot bugs in.  Why is it an array of string and not an array of functions?

**Comment by benschenker** [comment]
See 4de75fc9e71d4e86f0d071d85f8ee5fa839bf66d as a perfect example of how this makes the tests really difficult to read/debug/fix

**Comment by bugron** [comment]
@benschenker I have a similar open PR https://github.com/FreeCodeCamp/FreeCodeCamp/pull/2921, but it seems your's is better. Would you mind to integrate some changes from my PR so I can close that PR? For example, we need to check the value of `flip` variable too, because if we don't campers can pass the challenge with incorrect code as mentioned in this issue: https://github.com/FreeCodeCamp/FreeCodeCamp/issues/2803. Plus I've added some `<code>` tags and also dots at the end of sentences. Thanks!

**Comment by benschenker** [comment]
Hey @bugron I think these are addressing two different problems and can remain 2 different pull requests...one of us will just have to rebase after the other's gets merged.

**Comment by bugron** [comment]
OK, @benschenker, in that case I'll leave in my PR only "cosmetic" changes. And what about `flip` variable?

**Comment by benschenker** [comment]
Done

**Comment by bugron** [comment]
@benschenker `flip is not defined`.

**Comment by benschenker** [comment]
Very confused with what you are saying.  Feel free to just use my edited test in your PR and close this one.

**Comment by ahstro** [comment]
This is just a suggestion, but wouldn't it be a bit cleaner to write the tests like this...
```javascript
function () {
  var result = myFunction();
  return result === 'heads' || result === 'tails';
}
```
...and this?
```javascript
function () {
  var result = myFunction();
  return result === 'heads' && !flip || result === 'tails' && flip;
}
```

**Comment by benschenker** [comment]
Yep @ahstro that will do... @bugron do you want to incorporate this into your PR so we can close this one out?

**Comment by bugron** [comment]
@benschenker done. Please, check https://github.com/FreeCodeCamp/FreeCodeCamp/pull/2921 to be sure that everything is OK.
P.S. Apologies for the inconvenience. Really. I read a lot about better Git workflow past two days (`rebase`ing, `amend`ing and so on). Next time I'll be more attentive before creating a PR.

**Pull request closed without merging**
