### PR TITLE
feat: bundle sass.js with a worker

### PR DESCRIPTION
**Pull request by ValeraS**
- [x] I have read [freeCodeCamp's contribution guidelines](https://github.com/freeCodeCamp/freeCodeCamp/blob/master/CONTRIBUTING.md).
- [x] My pull request has a descriptive title (not a vague title like `Update index.md`)
- [x] My pull request targets the `master` branch of freeCodeCamp.
- [x] None of my changes are plagiarized from another source without proper attribution.

### CODE REVIEW

**Comment by Bouncey** [comment]
`client -> build:frame-runner` (which I would argue should be renamed now), is taking a long time and has the feeling that the process has hung. Could we get some sort of cli spinner to indicate that things are still happening.

I also ran in to a few memory dumps, meaning that the process that webpack was running on ran out of memory. Setting `devtool` to `false` in the webpack config fixed this, but it means there will be no souremaps for the worker files.

**Comment by ValeraS** [comment]
> Could we get some sort of cli spinner to indicate that things are still happening.

I've added a `--progress` option to webpack, should be better. 

> I also ran in to a few memory dumps, meaning that the process that webpack was running on ran out of memory.

I can't reproduce this behavior. What versions of node and webpack are you using?

**Comment by Bouncey** [comment]
I could only get this to work consistently with node@10

@raisedadead is it OK to push the [required node version](https://github.com/freeCodeCamp/freeCodeCamp/blob/master/docs/how-to-setup-freecodecamp-locally.md#installing-prerequisites) to 10? Perhaps you could investigate at your end?

Turning sourcemaps off made it work in node@8

**Comment by raisedadead** [comment]
We are already on Node@10.x which is the LTS for master.

**Review by raisedadead — APPROVED** [review]

**Comment by raisedadead** [comment]
I will bump the version in the documentation.

**Comment by Bouncey** [comment]
Awesome!

**Comment by Bouncey** [comment]
I will attempt to resolve the conflicts

**Pull request merged**
