### PR TITLE
Add Cash Register Challenge

### PR DESCRIPTION
**Pull request by brandenbyers**
Design a cash register drawer function that accepts purchase price as the first argument, payment as the second argument, and cash-in-drawer (cid) as the third argument. cid is a 2d array listing available currency. Return the string "Insufficient Funds" if change due is less than the cash-in-drawer. Return the string "Closed" if cash-in-drawer is equal to the change due. Otherwise, return change in coin and bills, sorted in highest to lowest order.

### CODE REVIEW

**Comment by terakilobyte** [comment]
Please provide a valid solution to the challenge so that we can quickly test in production.

**Comment by brndnb** [comment]
I'll submit test for these challenges and others in the future, but is it necessary? Shouldn't valid tests be all that is needed? If not, what is the solution actually testing in production? My solution will only be one out of a possible many. If one solution is needed, wouldn't all possible solutions be needed (if that were even possible)? What benefit does a solution provide?

**Comment by QuincyLarson** [comment]
The copy and the valid tests are all that's needed, but in this case, we'd like to see how you go about solving it so we can better determine how difficult it is. As a general rule, if @terakilobyte and I have a hard time solving it in less than an hour, that means it may be of limited use to our campers and could probably stand to be broken down into a problem with fewer steps.

**Comment by brndnb** [comment]
Here is my solution. I know I could definitely refactor the changeDue function, but this is a working solution. However, I could not get it to successfully run within bonfire. But I ran the script in a browser and manually checked it against the assertions (I found one typo in a test though).

```javascript
function totalDrawer(arr){
  var total = 0;
  for(var i = 0; i < arr.length; i += 1) {
    total += arr[i][1];
  }
  return Math.round(total * 100) / 100;
}

function changeDue(change, drawer, arr) {
  var newArr = [],
      balance = 0,
      newDrawer = Math.round((drawer - change) * 100) / 100;
  // Will channge require $100?
  if(Math.floor(change / 100) > 0 && arr[8][1] > 0) {
    balance = Math.round((change % 100) * 100) / 100;
    newArr.push(['ONE HUNDRED', Math.round((change - balance) * 100) / 100]);
    change = balance;
  }
  // Will change require $20?
  if(Math.floor(change / 20) > 0 && arr[7][1] > 0) {
    balance = Math.round((change % 20) * 100) / 100;
    newArr.push(['TWENTY', Math.round((change - balance) * 100) / 100]);
    change = balance;
  }
  // 10?
  if(Math.floor(change / 10) > 0 && arr[6][1] > 0) {
    balance = Math.round((change % 10) * 100) / 100;
    newArr.push(['TEN', Math.round((change - balance) * 100) / 100]);
    change = balance;
  }
  // $5?
  if(Math.floor(change / 5) > 0 && arr[5][1] > 0) {
    balance = Math.round((change % 5) * 100) / 100;
    newArr.push(['FIVE', Math.round((change - balance) * 100) / 100]);
    change = balance;
  }
  // $1?
  if(Math.floor(change / 1) > 0 && arr[4][1] > 0) {
    balance = Math.round((change % 1) * 100) / 100;
    newArr.push(['ONE', Math.round((change - balance) * 100) / 100]);
    change = balance;
  }
  // $0.25?
  if(Math.floor(change / 0.25) > 0 && arr[3][1] > 0) {
    balance = Math.round((change % 0.25) * 100) / 100;
    newArr.push(['QUARTER', Math.round((change - balance) * 100) / 100]);
    change = balance;
  }
  // $0.10?
  if(Math.floor(change / 0.10) > 0 && arr[2][1] > 0) {
    balance = Math.round((change % 0.10) * 100) / 100;
    newArr.push(['DIME', Math.round((change - balance) * 100) / 100]);
    change = balance;
  }
  // $0.05?
  if(Math.floor(change / 0.05) > 0 && arr[1][1] > 0) {
    balance = Math.round((change % 0.05) * 100) / 100;
    newArr.push(['NICKEL', Math.round((change - balance) * 100) / 100]);
    change = balance;
  }
  // $0.01?
  if(Math.floor(change / 0.01) > 0 && arr[0][1] > 0) {
    newArr.push(['PENNY', change]);
  }
  return newArr;
}

function drawer(price, cash, cid) {
  var totalCashInDrawer = totalDrawer(cid),
      change = Math.round((cash - price) * 100) / 100;
  if(change > totalCashInDrawer) {
    return 'Insufficient Funds';
  }
  if(change === totalCashInDrawer) {
    return 'Closed';
  }
  return changeDue(change, totalCashInDrawer, cid);
}

drawer();
```

**Comment by terakilobyte** [comment]
Closing this PR after with brndnb to conform the challenge format and tests to bonfire.

**Pull request closed without merging**
