### PR TITLE
Clarify error message in basic-javascript challenge

### LINKED ISSUE #8850: Escaping Literal Quotes challenge test is unclear
Challenge [Escaping Literal Quotes in Strings](https://www.freecodecamp.com/challenges/escaping-literal-quotes-in-strings#?solution=%0Avar%20myStr%20%3D%20%22(I%20am%20a%20%5C%22double%20quoted%5C%22%20string%20inside%20%5C%22double%20quotes%5C%22).%22%3B%0A%0A%0A%0A) has an issue.
User Agent is: <code>Mozilla/5.0 (Windows NT 10.0; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/50.0.2661.102 Safari/537.36</code>.
Please describe how to reproduce this issue, and include links to screenshots if possible.

My code:
```javascript

var myStr = "(I am a \"double quoted\" string inside \"double quotes\").";




```

### PR DESCRIPTION
**Pull request by daniel-chung**
#### Pre-Submission Checklist

- [x] Your pull request targets the `staging` branch of FreeCodeCamp.
- [x] Branch starts with either `fix/`, `feature/`, or `translate/` (e.g. `fix/signin-issue`)
- [x] You have only one commit (if not, [squash](https://github.com/FreeCodeCamp/FreeCodeCamp/wiki/git-rebase#squashing-multiple-commits-into-one) them into one commit).
- [x] All new and existing tests pass the command `npm run test-challenges`. Use `git commit --amend` to amend any fixes.
#### Type of Change

- [x] Small bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds new functionality)
- [ ] Breaking change (fix or feature that would change existing functionality)
- [ ] Add new translation (feature adding new translations)
#### Checklist:

- [x] Tested changes locally.
- [x] Closes currently open issue (replace XXXX with an issue no): Closes #8850
#### Description

Removes the enclosing parentheses in the second assert error message for the basic-javascript challenge 'Escaping Literal Quotes'.

Previous error message was:
Variable myStr should equal to (I am a "double quoted" string inside "double quotes").

The new error message is now:
Variable myStr should contain the string: I am a "double quoted" string inside "double quotes".

Resolves: #8850

### CODE REVIEW

**Comment by erictleung** [comment]
@daniel-chung looks mostly good to me, but can you remove the second period at the very end of the test message? It might look confusing to have two periods, one within the actual string that is needed to pass the challenge, and then the one to stop the sentence. 

So instead of 

```
...inside \"double quotes\".</code>.');"
```

make it

```
...inside \"double quotes\".</code>');"
```

**Comment by daniel-chung** [comment]
@erictleung thanks for the feedback! Just made the updates.

**Comment by erictleung** [comment]
@daniel-chung thanks for the changes. Looks good to me. But first, please squash your two commits into one and then we can merge them. There's a link up above in your PR on how to squash commits if you are not familiar with squashing.

**Comment by daniel-chung** [comment]
@erictleung I had a question about that in my other PR. Is it appropriate it to have two very different commits in a same PR?

In the other commit, I added a new test for a completely different challenge (Chunky Monkey).

One caveat--I had preemptively revert my commit in that PR once I saw the message about having one commit per PR. It might be easier to delete the other commit/PR, merge this one, and then revisit the other commit; but I'm still learning how to contribute on GitHub so would love to hear your thoughts.

**Comment by erictleung** [comment]
@daniel-chung the beauty of `git` and GitHub is that yes, you can have two different commits, as long as they are in different branches.

For this one, you'll need to squash your commits. Using the command line, here's how to do it:

```bash
cd where-your-freecodecamp-folder-is
git checkout fix/assert-message
git rebase -i HEAD~2 # change ONLY one of the `pick`s to `squash`
git commit --amend # Remove the duplicate text
git push origin fix/assert-message --force
```

Feel free to visit the [Contributors Help](https://gitter.im/FreeCodeCamp/HelpContributors) chat room if you have any questions about helping.

**Comment by daniel-chung** [comment]
@erictleung appreciate the detailed response on the branches & instructions on how to squash commits!

Unfortunately, I wasn't able to squash my two commits. Not positive but it might be due to the `git reset` commands I ended up using. My two PRs each have a single commit now, but let me know if this is still an issue.

**Comment by erictleung** [comment]
@daniel-chung no problem on helping over here as well! It looks like you were able to squash your commits. There is only one commit in this PR. So everything looks good to me! 👍  Congrats on your second PR to FreeCodeCamp! ✨ 🎉 ✨

**Pull request merged**
