### PR TITLE
test rendered output instead of state in react write a simple counter…

### LINKED ISSUE #36782: Write a Simple Counter: Preview failing to update, tests are passing
**Describe your problem and how to reproduce it:**
I have added increment and decrement functions as per instruction, and it passes all tests and  lets me go to the next page.However, in the preview, clicking on increment and decrement doesn't update the count.
Modified code:
```
class Counter extends React.Component {
  constructor(props) {
    super(props);
    this.state = {
      count: 0
    };
    // change code below this line
  this.increment = this.increment.bind(this);
   this.decrement = this.decrement.bind(this);
     this.reset = this.reset.bind(this);
    // change code above this line
  }
  // change code below this line
  increment(){
    this.state.count = this.state.count + 1;
  }
  decrement(){
    this.state.count = this.state.count - 1;
  }

  reset(){
    this.state.count = 0;
  }
  // change code above this line
  render() {
    return (
      <div>
        <button className='inc' onClick={this.increment}>Increment!</button>
        <button className='dec' onClick={this.decrement}>Decrement!</button>
        <button className='reset' onClick={this.reset}>Reset</button>
        <h1>Current Count: {this.state.count}</h1>
      </div>
    );
  }
};
```
**Add a Link to the page with the problem:**
https://learn.freecodecamp.org/front-end-libraries/react/write-a-simple-counter/

**Tell us about your browser and operating system:**
* Browser Name: Chrome
* Browser Version: Chrome 76
* Operating System: Windows 10
bug

**Errors in Console**
(index):1 Failed to execute 'postMessage' on 'DOMWindow': The target origin provided ('https://js.stripe.com') does not match the recipient window's origin ('https://learn.freecodecamp.org').

**If possible, add a screenshot here (you can drag and drop, png, jpg, gif, etc. in this box):**

### PR DESCRIPTION
**Pull request by jzabala**
… challenge

- [x] I have read [freeCodeCamp's contribution guidelines](https://github.com/freeCodeCamp/freeCodeCamp/blob/master/CONTRIBUTING.md).
- [x] My pull request has a descriptive title (not a vague title like `Update index.md`)
- [x] My pull request targets the `master` branch of freeCodeCamp.
- [x] None of my changes are plagiarized from another source without proper attribution.
- [x] All the files I changed are in the same world language (for example: only English changes, or only Chinese changes, etc.)
- [x] My changes do not use shortened URLs or affiliate links.

Closes #36782

### CODE REVIEW

**Comment by scissorsneedfoodtoo** [comment]
@jzabala, thank you for taking the time to improve this challenge. Just checked this out locally and everything LGTM. The code from #36782 that mutates the state directly no longer passes the tests. With these changes users must use `setState` like they were taught in previous lessons.

**Comment by jzabala** [comment]
> @jzabala, thank you for taking the time to improve this challenge. Just checked this out locally and everything LGTM. The code from #36782 that mutates the state directly no longer passes the tests. With these changes users must use `setState` like they were taught in previous lessons.

Thank you very much @scissorsneedfoodtoo for taking the time to do the test on this one 👍🏼

**Review by moT01 — APPROVED** [review]
LGTM @jzabala 🎉 Thanks for fixing this and congratulations on your first contribution to freeCodeCamp! 🎉

**Comment by jzabala** [comment]
> LGTM @jzabala 🎉 Thanks for fixing this and congratulations on your first contribution to freeCodeCamp! 🎉

That is awesome. Thank you very much @moT01 for merging it 😁

**Pull request merged**
