### PR TITLE
Change in the word Telegram

### PR DESCRIPTION
**Pull request by RonanFelipe**
The word Telegram doesn't need to be translated to portuguese, since it is App name, and also the translation was in portuguese plural. I changed it to the original App name 'Telegram'.

- [x] I have read [freeCodeCamp's contribution guidelines](https://github.com/freeCodeCamp/freeCodeCamp/blob/master/CONTRIBUTING.md).
- [x] My pull request has a descriptive title (not a vague title like `Update index.md`)
- [x] My pull request targets the `master` branch of freeCodeCamp.
- [x] None of my changes are plagiarized from another source without proper attribution.
- [x] My article does not contain shortened URLs or affiliate links.

If your pull request closes a GitHub issue, replace the XXXXX below with the issue number.

Closes #XXXXX

### CODE REVIEW

**Comment by RonanFelipe** [comment]
Change in the word Telegram, since it is the App name, I don't think it need to be translated.

**Comment by RandellDawson** [comment]
Manually restarted build.  Will back later on this one.

**Review by thecodingaviator — APPROVED** [review]

**Comment by thecodingaviator** [comment]
I believe `Bots de Telegram` means `Telegram Bots` while `Bots do Telegram` means `Bots of Telegram`. Is that correct @freeCodeCamp/portuguese-language-editors ?

**Comment by RonanFelipe** [comment]
Exactly.

**Comment by thecodingaviator** [comment]
Thank you for opening this pull request.

This is a standard message notifying you that we’ve reviewed your pull request and have decided not to merge it. We would welcome future pull requests from you.

Thank you and happy coding. ✈️

**Pull request closed without merging**
