### PR TITLE
Fix/update challenges for sass spanish

### LINKED ISSUE #34743: Possible Typo in "SASS Challenge: Use @if and @else to Add Logic to your Styles"
**Issue Description**
Following the given instructions. The test will fail for the @else 
`  @mixin border-stroke($val) { 
  @if $val === light { border: 1px solid black; 
                      }
@else if $val === medium { border: 3px solid black; 
                          }
@else if $val === heavy { border: 6px solid black; 
                          }
@else { border: none; 
      }
}`

The checkmark at the bottom left says: "Your mixin should have an @else statement to set the border to none." and it will pass if using "none" but not "no border" as suggested. 

My suggestion is to replace "no border" from the instructions with "none"

**Link to the page with the problem:**
https://learn.freecodecamp.org/front-end-libraries/sass/use-if-and-else-to-add-logic-to-your-styles

**browser and operating system:**
* Browser Name: Chrome
* Browser Version:  Version 71.0.3578.98 (Official Build) (64-bit)
* Operating System: MacOs Sierra Version 10.12.6

### PR DESCRIPTION
**Pull request by aditijoshi14**
- [X] I have read [freeCodeCamp's contribution guidelines](https://github.com/freeCodeCamp/freeCodeCamp/blob/master/CONTRIBUTING.md).
- [X] My pull request has a descriptive title (not a vague title like `Update index.md`)
- [X] My pull request targets the `master` branch of freeCodeCamp.
- [X] None of my changes are plagiarized from another source without proper attribution.
- [X] All the files I changed are in the same world language (Spanish)
- [X] My changes do not use shortened URLs or affiliate links.

Closes #34743 (Language: Spanish)
Associated with #35031

### CODE REVIEW

**Comment by RandellDawson** [comment]
@aditijoshi14 LGTM.  

However, I just noticed that the challenge Description section's code block do not match the current English version.  The code blocks should match 100% (with the exception of maybe commented code).

Here are the two code blocks in the English version:
<blockquote>@mixin make-bold($bool) {<br>&nbsp;&nbsp;@if $bool == true {<br>&nbsp;&nbsp;&nbsp;&nbsp;font-weight: bold;<br>&nbsp;&nbsp;}<br>}</blockquote>

<blockquote>@mixin text-effect($val) {<br>&nbsp;&nbsp;@if $val == danger {<br>&nbsp;&nbsp;&nbsp;&nbsp;color: red;<br>&nbsp;&nbsp;}<br>&nbsp;&nbsp;@else if $val == alert {<br>&nbsp;&nbsp;&nbsp;&nbsp;color: yellow;<br>&nbsp;&nbsp;}<br>&nbsp;&nbsp;@else if $val == success {<br>&nbsp;&nbsp;&nbsp;&nbsp;color: green;<br>&nbsp;&nbsp;}<br>&nbsp;&nbsp;@else {<br>&nbsp;&nbsp;&nbsp;&nbsp;color: black;<br>&nbsp;&nbsp;}<br>}</blockquote>

Here is the same code blocks in the Spanish version.  You will notice, this version does not even have valid code syntax (i.e. missing colons after property names).

<blockquote> @mixin make-bold ($ bool) { <br> @if $ bool == true { <br> font-weight: negrita; <br> } <br> } </blockquote>

<blockquote> @mixin efecto-texto ($ val) { <br> @if $ val == peligro { <br> color rojo; <br> } <br> @else if $ val == alert { <br> color amarillo; <br> } <br> @else if $ val == éxito { <br> color verde; <br> } <br> @else { <br> de color negro; <br> } <br> } </blockquote>

Would you be interested in tackling this issue?  Also, would you be interested in reviewing other Spanish challenges and comparing them to the latest English version on the `master`?  If so, send me a note via Gitter and I can discuss an approach to help you find them easier.

**Comment by aditijoshi14** [comment]
@RandellDawson 
Thank you for reviewing!

I can create a separate PR regarding this issue.  For "font-weight: negrita;" or "color rojo;", do we have to change it to "font-weight: bold" or "color: red" as it looks like an actual code. I am actually not familiar with the Spanish language so I am afraid that I will not be able to review other Spanish challenges and compare them to the Latest English version in the master.

**Comment by RandellDawson** [comment]
@aditijoshi14 Just pull up [the latest English version on the master branch](https://github.com/freeCodeCamp/freeCodeCamp/blob/master/curriculum/challenges/english/03-front-end-libraries/sass/use-if-and-else-to-add-logic-to-your-styles.english.md) on hand, so you can see what the code should actually be.

**Comment by aditijoshi14** [comment]
@ lynxlynxlynx Just wanted to check if you have time to review this PR for Spanish.

**Comment by aditijoshi14** [comment]
@lynxlynxlynx  Just wanted to check if you have time to review this PR for Spanish.

**Comment by lynxlynxlynx** [comment]
The instructions are incomplete now — one has to look at the test errors to see what is to be done. I think that's bad form. Plus, the new text suggests only two different outcomes, which is not true.

**Review by RandellDawson — APPROVED** [review]
LGTM - As these changes were already accepted for the English version, we can merge this.

**Comment by RandellDawson** [comment]
Thank you for your contribution to the page! 👍
We're happy to accept these changes, and look forward to future contributions. 🎉

**Pull request merged**
