### PR TITLE
Added podcast to "Our community also has:" section

### PR DESCRIPTION
**Pull request by Hahlh**
- [x] I have read [freeCodeCamp's contribution guidelines](https://github.com/freeCodeCamp/freeCodeCamp/blob/master/CONTRIBUTING.md).
- [x] My pull request has a descriptive title (not a vague title like `Update index.md`)
- [x] My pull request targets the `master` branch of freeCodeCamp.
- [x] None of my changes are plagiarized from another source without proper attribution.
- [x] All the files I changed are in the same world language (for example: only English changes, or only Chinese changes, etc.)
- [x] My changes do not use shortened URLs or affiliate links.

The podcast is very valuable and is missing from this list.
 
I looked up the short description on Spotify and the web page, but the one provided there doesn't fit here, so I consider it best to add it without description. 
It would be a good idea to include the frequency with which podcasts are released, if that is something that is very unlikely to change in the future.

All the best and have a great day!

Leo

### CODE REVIEW

**Review by raisedadead — COMMENTED** [review]
Hmm I think we do need a description. 

Hey @AbbeyRenn what do you think, would be a good one liner description that suits?

**Comment by Hahlh** [comment]
What about:

A podcast providing insight into the world of programming through guides, interviews and inspirational personal stories.

**Comment by AbbeyRenn** [comment]
How about "The official podcast of the freeCodeCamp open source community, bringing you developer interviews, expert advice and insights, and inspirational stories." Thoughts @raisedadead ? I could double-check with Quincy, as well, to see if he has a specific one-liner he'd prefer...

**Comment by QuincyLarson** [comment]
@Hahlh Thanks for thinking to add this.

@AbbeyRenn I've used a slightly shorter version of your recommended copy.

**Pull request merged**
