### PR TITLE
Remove browser recommendation text

### LINKED ISSUE #11153: Note Due to browser implementation differences, you may need to be at 100% zoom to pass the tests on this challenge.
Challenge [Change the Font Size of an Element](https://www.freecodecamp.com/challenges/change-the-font-size-of-an-element#?solution=%0A%3Cstyle%3E%0A%20%20.red-text%20%7B%0A%20%20%20%20color%3A%20red%3B%0A%20%20%7D%0A%20%20p%20%7B%0A%20%20%20%20font-size%3A%2016px%3B%0A%20%20%7D%0A%3C%2Fstyle%3E%0A%0A%3Ch2%20class%3D%22red-text%22%3ECatPhotoApp%3C%2Fh2%3E%0A%0A%3Cp%20class%3D%22red-text%22%3EKitty%20ipsum%20dolor%20sit%20amet%2C%20shed%20everywhere%20shed%20everywhere%20stretching%20attack%20your%20ankles%20chase%20the%20red%20dot%2C%20hairball%20run%20catnip%20eat%20the%20grass%20sniff.%3C%2Fp%3E%0A%3Cp%3EPurr%20jump%20eat%20the%20grass%20rip%20the%20couch%20scratched%20sunbathe%2C%20shed%20everywhere%20rip%20the%20couch%20sleep%20in%20the%20sink%20fluffy%20fur%20catnip%20scratched.%3C%2Fp%3E) has an issue.
User Agent is: <code>Mozilla/5.0 (Windows NT 10.0; WOW64; rv:49.0) Gecko/20100101 Firefox/49.0</code>.
Please describe how to reproduce this issue, and include links to screenshots if possible.

My code:
```html

<style>
  .red-text {
    color: red;
  }
  p {
    font-size: 16px;
  }
</style>

<h2 class="red-text">CatPhotoApp</h2>

<p class="red-text">Kitty ipsum dolor sit amet, shed everywhere shed everywhere stretching attack your ankles chase the red dot, hairball run catnip eat the grass sniff.</p>
<p>Purr jump eat the grass rip the couch scratched sunbathe, shed everywhere rip the couch sleep in the sink fluffy fur catnip scratched.</p>
```
Can we please remove the text in the instructions:

>Note
>Due to browser implementation differences, you may need to be at 100% zoom to pass the tests on >this challenge.

It is extremely confusing for new campers. They keep trying to figure out what they should do. We field 3-4 questions about this text every day. It would be way easier to fix the issue if they have it because of the setting in the browser than having them ask when there is no issue to begin with.
Thank you

### PR DESCRIPTION
**Pull request by tadake**
#### Pre-Submission Checklist

- [x] Your pull request targets the `staging` branch of FreeCodeCamp.
- [x] Branch starts with either `fix/`, `feature/`, or `translate/` (e.g. `fix/signin-issue`)
- [x] You have only one commit (if not, [squash](http://forum.freecodecamp.com/t/how-to-squash-multiple-commits-into-one-with-git/13231) them into one commit).
- [x] All new and existing tests pass the command `npm run test-challenges`. Use `git commit --amend` to amend any fixes.
#### Type of Change

- [x] Small bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds new functionality)
- [ ] Breaking change (fix or feature that would change existing functionality)
- [ ] Add new translation (feature adding new translations)
#### Checklist:

- [x] Tested changes locally.
- [x] Closes currently open issue (replace XXXX with an issue no): Closes #11153 
#### Description

removed "Note Due to browser implementation differences, you may need to be at 100% zoom to pass the tests on this challenge." text from "Change the Font Size of an Element" challenge. Other translations were fixed by using google translate.

### CODE REVIEW

**Comment by systimotic** [comment]
I think something went wrong with git. The entire file has been replaced. Maybe a line ending issue?

**Comment by dhcodes** [comment]
@tadake as @systimotic has pointed out, this is not coming through correctly. If you still have this branch, do a `git pull --rebase upstream staging`. Then open the file in your text-editor of choice and make your modifications again. Save the file, run `git add [your file]` and then `git commit --amend --no-edit`. Finally, run `git push origin fix/[your branch name] -f` to force it to override the original commit.

**Comment by dhcodes** [comment]
@tadake mostly there, but the remnants of that last file are still here. Hmm, I'm not sure how to remove it. Anyone know? cc @FreeCodeCamp/issue-moderators

**Comment by tadake** [comment]
I've been having lots of issues with this @dhcodes . I previously had another PR and when I tried to squash my commits somehow my commits went from 2 to 10 and not all were mine. After trying numerous things I decided to re-fork the FreeCodeCamp and restart from scratch and something went wrong haha. I believe its fixed now after I ran your commands. I can view my changes now and everything seems good. Thanks for your help guys! I'm going to be more careful next time I mess with git hahaha.

**Comment by tadake** [comment]
ahh I see @dhcodes  I'm not sure how to remove the remnants.

**Comment by dhcodes** [comment]
@tadake no worries; I've been in the same boat before and I'm sure I will again. What do you get when you run `git status` on your branch now? Does it show the deletion unstaged?

**Comment by tadake** [comment]
I know the issue @dhcodes . I copied the file I changed and put it back in the wrong spot. To fix this I should delete the file and redo the steps from your comment above correct?

**Comment by dhcodes** [comment]
correct I believe @tadake but shouldn't need to rebase again.

**Comment by tadake** [comment]
I believe it's fixed now @dhcodes . hahaha Node schools git-it didn't cover this hahaha

**Comment by dhcodes** [comment]
Tested locally and LGTM 👍 . Thanks for contributing to FreeCodeCamp 🎉 . Also, fwiw Git Immersion is the best git tutorial I've found: http://gitimmersion.com/

**Comment by atjonathan** [comment]
@dhcodes

**Pull request merged**
