### PR TITLE
fix(learn): updated catphotoapp links

### PR DESCRIPTION
**Pull request by RandellDawson**
Checklist:

- [x] I have read [freeCodeCamp's contribution guidelines](https://contribute.freecodecamp.org).
- [x] My pull request has a descriptive title (not a vague title like `Update index.md`)
- [x] My pull request targets the `master` branch of freeCodeCamp.
- [x] All the files I changed are in the same world language, for example: only English changes, or only Chinese changes, etc.

This PR fixes two bugs that have been present for quite a while relating to invalid urls being used as links in the Basic HTML section.  

The first such bug is introduced in the [Link to External Pages with Anchor Elements](https://www.freecodecamp.org/learn/responsive-web-design/basic-html-and-html5/link-to-external-pages-with-anchor-elements) challenge.  The user is told to create an anchor element that links to `http://freecatphotoapp.com`.  I went ahead and changed it to use `https:`.

The second fix relates to a url that is introduced in the [Create a Form Element](https://www.freecodecamp.org/learn/responsive-web-design/basic-html-and-html5/create-a-form-element) challenge.  The user is told to add `action="/submit-cat-photo"` to the form element.  The issue arises when the user clicks on the Submit button in the next challenge ([Add a Submit Button to a Form](https://www.freecodecamp.org/learn/responsive-web-design/basic-html-and-html5/add-a-submit-button-to-a-form)).  Currently, nothing actually happens which is a problem in itself. I have created a new html file located at `client/static/submit-cat-photo/index.html` that contains a generic thank you message to simulate what a user might see if they were actually submitting the form.  

I believe the change makes the app being created more realistic.  Also, we plan on using these same URLs for the project-based curriculum's `Basic HTML Cat Photo App`.

**Note to reviewers:**
I will create separate PRs for the other languages to make them easier to review.  I know I will have to deal with a Husky issue where it complains about several of the non-English files not having an extra line between the the last set of triple backticks and last closing `</section>` tag.  I wanted to deal with that separately.

### CODE REVIEW

**Comment by raisedadead** [comment]
We do control the domain, its config seemed to have been changed during a move from one registrar to another. 

We have pointed it to freecodecamp.org for now, but I assume we should be able to point it to independent static pages like we had in the past.

**Comment by RandellDawson** [comment]
@raisedadead In that case, where can I see the source code for that site.  Would rather use that domain for the links or would it be fine to proceed with just putting them in the static folder as I have already done (they appear to work locally)?

**Comment by raisedadead** [comment]
> where can I see the source code for that site.

The old code was lost in the move, but it was only a image and embedded in a html file. We can create a new repository and put static files in there. We could use netlify to host the site.

If you would like that let me know, I can setup an empty repo for you to work with and hook up the deployment on netlify once you are ready.

**Comment by ojeytonwilliams** [comment]
I prefer the cdn approach if possible, just so we can keep /learn focused.

**Comment by RandellDawson** [comment]
Let's use Netlify for these two static pages.  We may have a use for the same site for other pages as we work through designing the content for the next curriculum. Should we also move the [cats.json](https://github.com/freeCodeCamp/freeCodeCamp/blob/master/client/static/json/cats.json) file to the Netlify site?

**Comment by raisedadead** [comment]
This repo is ready: https://github.com/freeCodeCamp/freeCatPhotoApp. I will deploy it once you have something in there.

**Comment by ojeytonwilliams** [comment]
> Should we also move the cats.json file to the Netlify site?

Ideally, yes.  I'll just check if any tests depend on the location, but it should be an easy migration.

**Comment by raisedadead** [comment]
Okay the site is live (with a maintenance page), feel free to make a PR and remove it.

**Pull request merged**
