### PR TITLE
fix: test catch if function is empty

### LINKED ISSUE #54596: Test in step 13 of Password Generator project not checking for function body content
**Describe the bug**
Step 13 asks to declare a function and move the existing lines of code after the imports inside it. There's only one test that checks that the function exists. Therefore, one can pass this step declaring an empty function.

**To Reproduce**
1. Go [here](https://www.freecodecamp.org/learn/scientific-computing-with-python/learn-regular-expressions-by-building-a-password-generator/step-13)
2. Add `def generate_password():  pass`
3. Run the tests

**Expected behavior**
`def generate_password():  pass` should not be enough to pass this step.
Another tests should check that the lines of code inside the editable region are inside the function body.

**Additional context**
ast-based helpers docs https://contribute.freecodecamp.org/#/curriculum-help?id=ast-based-helpers

### PR DESCRIPTION
**Pull request by majestic-owl448**
Checklist:

- [x] I have read and followed the [contribution guidelines](https://contribute.freecodecamp.org).
- [x] I have read and followed the [how to open a pull request guide](https://contribute.freecodecamp.org/#/how-to-open-a-pull-request).
- [x] My pull request targets the `main` branch of freeCodeCamp.
- [x] I have tested these changes either locally on my machine, or GitPod.

Closes #54596

### CODE REVIEW

**Review by Dario-DC — APPROVED** [review]
LGTM :+1:

**Review by zairahira — CHANGES_REQUESTED** [review]
This code still passes if variables are present outside:

```python
import secrets
import string

# Define the possible characters for the password
letters = string.ascii_letters
digits = string.digits
symbols = string.punctuation

# Combine all characters
all_characters = letters + digits + symbols

def generate_password():  
    # Define the possible characters for the password
    letters = string.ascii_letters
    digits = string.digits
    symbols = string.punctuation

    # Combine all characters
    all_characters = letters + digits + symbols

```

Here is the hint and test to fix this:

````md
The four variable declarations shouldn't exist outside the function.

```js
({
  test: () => assert.isFalse(runPython(`
  
  _Node(_code).find_variable('letters').is_equivalent('letters = string.ascii_letters') and \\
  _Node(_code).find_variable('digits').is_equivalent('digits = string.digits') and \\
  _Node(_code).find_variable('symbols').is_equivalent('symbols = string.punctuation') and \\
  _Node(_code).find_variable('all_characters').is_equivalent('all_characters = letters + digits + symbols')
  `))
})
```
````

**Comment by ilenia-magoni** [comment]
Yes, I am checking the new function is defined correctly only, not if the variables are outside @zairahira

**Review by zairahira — APPROVED** [review]
Looking good 👍️

**Pull request merged**
