### PR TITLE
fix(curriculum): Modify test in one of the Javascript challenges

### LINKED ISSUE #35793: Test failure in 'Basic Data Structures: Check For The Presence of an Element With indexOf()'
**Describe your problem and how to reproduce it:**
For [this challenge](https://learn.freecodecamp.org/javascript-algorithms-and-data-structures/basic-data-structures/check-for-the-presence-of-an-element-with-indexof/), the correct answer should be something like:
```
...
return arr.indexOf(elem) >= 0
...
```

But this code will also pass all the tests, even when it is incorrect:
```
...
return arr.indexOf(elem) > 0
...
```

This can be solved by simply changing the order of the variables in the second test, so that `elem` is at index 0, thus disabling the incorrect answer, like this
```
// Before fix
quickCheck(["squash", "onions", "shallots"], "onions") should return true

// After fix
quickCheck(["onions", "shallots", "squash"], "onions") should return true
```

I'd be glad to contribute and fix this myself if the issue is confirmed and the solution approved.

**Add a Link to the page with the problem:**
https://learn.freecodecamp.org/javascript-algorithms-and-data-structures/basic-data-structures/check-for-the-presence-of-an-element-with-indexof/

**Tell us about your browser and operating system:**
* Browser Name: Chrome
* Browser Version: 73.0.3683.86 (Official Build) (64-bit)
* Operating System: macOS Sierra v10.12.5

**If possible, add a screenshot here (you can drag and drop, png, jpg, gif, etc. in this box):**
Here's a screenshot taken after running all the tests. As you can see, all the tests passed, even when the answer is incorrect.

95zjpcvQ

### PR DESCRIPTION
**Pull request by guayom**
- [x] I have read [freeCodeCamp's contribution guidelines](https://github.com/freeCodeCamp/freeCodeCamp/blob/master/CONTRIBUTING.md).
- [x] My pull request has a descriptive title (not a vague title like `Update index.md`)
- [x] My pull request targets the `master` branch of freeCodeCamp.
- [x] None of my changes are plagiarized from another source without proper attribution.
- [x] All the files I changed are in the same world language (for example: only English changes, or only Chinese changes, etc.)
- [x] My changes do not use shortened URLs or affiliate links.

I found an error in a challenge. I explain everything in the issue #35793.
I rearranged the variables in one of the tests. That would fix the issue.

I just changed the english file. Should I change the rest of the languages as well?

Note: This is my first contribution. I did this change through github's API, because I couldn't run the project locally so I haven't actually tested it.

Closes #35793

### CODE REVIEW

**Review by ojeytonwilliams — APPROVED** [review]
I've checked it out locally and it looks good to me.

**Review by thecodingaviator — APPROVED** [review]
Tested locally, LGTM! 👍

**Comment by thecodingaviator** [comment]
Thanks for contributing to the freeCodeCamp repository. Congratulations on your first PR! 🎊 

Look forward to more contributions from you! ✈️

Great work @guayom

**Comment by guayom** [comment]
Woo! Thanks. Of course, I'll try to keep contributing :)

**Pull request merged**
