### PR TITLE
added recursive implemenation in c++ in index.md

### PR DESCRIPTION
**Pull request by isha2812**
- [x] I have read [freeCodeCamp's contribution guidelines](https://github.com/freeCodeCamp/freeCodeCamp/blob/master/CONTRIBUTING.md).
- [x] My pull request has a descriptive title (not a vague title like `Update index.md`)
- [x] My pull request targets the `master` branch of freeCodeCamp.
- [x] None of my changes are plagiarized from another source without proper attribution.
- [x] My article does not contain shortened URLs or affiliate links.

If your pull request closes a GitHub issue, replace the XXXXX below with the issue number.

Closes #XXXXX

### CODE REVIEW

**Review by kmanish31 — APPROVED** [review]

**Review by kmanish31 — APPROVED** [review]

**Comment by RandellDawson** [comment]
@Manish-Giri I believe this is the one you were going to possibly respond to as to the validity of the code?

**Review by cmccormack — APPROVED** [review]
Looks good to me, and congratulations on your first Pull Request!  🎉🎉🎉
We look forward to future contributions!

In the future please be aware that the text after the three backticks \``` determines how the code block syntax will be highlighted - it is not used to describe the code.  [Github Markdown Reference](https://help.github.com/en/articles/creating-and-highlighting-code-blocks#syntax-highlighting)

**Comment by Manish-Giri** [comment]
@RandellDawson Correct. I had compiled and executed this code in repl.it. Among the several things I had intended to ask the OP to fix, one of them was - 
```
if (k != index) swap(a[k], a[index]);
```

As the OP didn't provide their own implementation of `swap()`, I'm assuming the meant to use the in-built `swap()` function. In this case, it requires the import of specific header files, which are not there in this PR.

Additionally, the PR doesn't have a "main" method which should ideally call the sort algorithm, and demonstrate the before + after outputs. It just provides the sort algorithm.

Here's my [repl.it code](https://repl.it/@Manish_Giri/InsignificantPrestigiousSystemintegrator) that I made to test the PR.

**Comment by RandellDawson** [comment]
@Manish-Giri Would you mind adding that correct solution to close out issue #https://github.com/freeCodeCamp/freeCodeCamp/issues/35391 ?

**Pull request merged**
