### PR TITLE
fix(curriculum): use `#<name>` for element id reference

### LINKED ISSUE #49274: updates needed to 'getMessage element' phrase in json apis and ajax course
### Describe the Issue

curriculum/course/step: 04-data-visualization/json-apis-and-ajax/handle-click-events-with-javascript-using-the-onclick-property.md

This file contains the following test message:
Your code should use the document.getElementById method to select the getMessage element.

However, the reference to "getMessage element" in the test message should instead refer to #getMessage element as getMessage is the value of an id attribute.

While we're here also, I noticed that this sentence in the same challenge can be made simpler:
You can implement an onclick event handler which triggers when the user clicks on the element with id getMessage, by adding the following code:

Instead of 'the element with id getMessage' we can just say 'the #getMessage element'? 2 words less but it also makes translating it a lot less wordier for Arabic at least.

### Affected Page

https://www.freecodecamp.org/learn/data-visualization/json-apis-and-ajax/handle-click-events-with-javascript-using-the-onclick-property

### Your code

```

```

### Expected behavior

use #getMessage element as described above

### Screenshots

_No response_

### System

N/A

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by midikaif**
Checklist:

- [x] I have read and followed the [contribution guidelines](https://contribute.freecodecamp.org).
- [x] I have read and followed the [how to open a pull request guide](https://contribute.freecodecamp.org/#/how-to-open-a-pull-request).
- [x] My pull request targets the `main` branch of freeCodeCamp.
- [x] I have tested these changes either locally on my machine, or GitPod.

Closes #49274

### CODE REVIEW

**Comment by midikaif** [comment]
Why these 2 tests failed? Can anyone help please?

**Comment by ShaunSHamilton** [comment]
@midikaif PRs that are marked as Drafts are often ignored by maintainers, **unless** you explicitly request help/review.

---

The tests failed, because of a network issue. I have re-run them; hopefully that issue has passed.

**Comment by midikaif** [comment]
@ShaunSHamilton, I have removed the PR from the draft. what I have to do next, please guide me

**Comment by ShaunSHamilton** [comment]
@midikaif Now, maintainers need to review your changes.

Please do not click the "Update Branch" button, unless told to. Doing so delays this PR from being merged, because it causes the tests to re-run.

**Review by Sboonny — APPROVED** [review]
#### :sparkles: :tada: **AWESOME!** :tada: :sparkles:

 Hi @midikaif, thanks for this pull request and for contributing to the code-base for the first time. We are looking forward to more contributions from you in the future.

 Cheers & happy contributing!

**Review by Sembauke — APPROVED** [review]

**Comment by midikaif** [comment]
Thanks @ShaunSHamilton @Sboonny @Sembauke , you guys are amazing.

**Pull request merged**
