### PR TITLE
added solution to d3 challenge add-labels-to-d3-elements

### PR DESCRIPTION
**Pull request by prayagd**
- [x] I have read [freeCodeCamp's contribution guidelines](https://github.com/freeCodeCamp/freeCodeCamp/blob/master/CONTRIBUTING.md).
- [x] My pull request has a descriptive title (not a vague title like `Update index.md`)
- [x] My pull request targets the `master` branch of freeCodeCamp.
- [x] None of my changes are plagiarized from another source without proper attribution.
- [x] All the files I changed are in the same world language (for example: only English changes, or only Chinese changes, etc.)
- [x] My changes do not use shortened URLs or affiliate links.

Closes #XXXXX

### CODE REVIEW

**Review by RandellDawson — APPROVED** [review]
LGTM

**Comment by raisedadead** [comment]
Interesting why the dev team was flagged as a codeowner here.

**Comment by ojeytonwilliams** [comment]
@raisedadead when the PR was opened it touched a whole bunch of files, so I assume it was that.

**Comment by raisedadead** [comment]
Ah, that makes sense. Thanks for the clarification.

**Pull request merged**
