### PR TITLE
feat: move profile settings to profile page

### LINKED ISSUE #55258: Move the portfolio edit functionality from the settings page to the portfolio
### Is your feature request related to a problem? Please describe.

To improve the user experience, the edit functionally should be as close to the section that it is editing. As a result, the following sections should be ported from settings page to a modal that opens by clicking the edit button on the portfolio page:

- Username
- Personal Information
	- name
	- location
	- picture
	- about
- Your Internet Presence
	- Github
	- Twitter
	- Linkedin (x)
	- Personal website

Screenshot 2024-06-21 at 4 53 07 PM

### PR DESCRIPTION
**Pull request by Sembauke**
Checklist:

- [x] I have read and followed the [contribution guidelines](https://contribute.freecodecamp.org).
- [x] I have read and followed the [how to open a pull request guide](https://contribute.freecodecamp.org/how-to-open-a-pull-request/).
- [x] My pull request targets the `main` branch of freeCodeCamp.
- [x] I have tested these changes either locally on my machine, or GitPod.

Closes #55258

### CODE REVIEW

**Review by huyenltnguyen — COMMENTED** [review]
I tested the changes locally, and found a couple issues:
- When the username is changed and saved successfully, the dialog isn't closed (the success flash is behind the dialog)
- Similarly, when a portfolio item is added or removed successfully, the dialog isn't closed
- When I add or remove a social media link
  - I got redirected to the Gatsby.js development 404 page, with these errors in the console:
    - Screenshot 2024-09-24 at 02 08 56
  - The page apparently could even crash (I can't reproduce this issue consistently)
    - Screenshot 2024-09-24 at 02 01 41

---

Unrelated to the PR changes, but I'm not sure if I prefer having the fields in a modal. 

One issue with it is the modal would sit on top of the flash, preventing campers from reading it. We can close the modal when the Save button is clicked, but then the user would need to reopen the modal if they haven't finished updated their profile. I guess we could fix this by keeping the modal open and changing the z-index so that flash would be on top.

Another issue is modals can be closed when the user presses Escape or clicks outside, and the user would lose the changes if they accidentally close the modal. We could prevent that by perhaps showing another modal on top, asking the users if they want to discard the changes. But I think that's more work for us and probably not a good UX.

An alternative I can think of is conditionally rendering the profile info and profile inputs using modes:

```tsx
const [isViewMode, setIsViewMode] = useState(true)

return (
  isViewMode ? (
    <>
      <ViewProfile />
      <EditProfileButton onClick={() => setViewMode(false)} />
    </>
  ) : (
    <>
      <EditProfile />
	  <ViewProfileButton onClick={() => setViewMode(true)} />
    </>
  )
)
```

**Comment by Sembauke** [comment]
Thank you @huyenltnguyen for the thorough review.

> When I add or remove a social media link
 I am unable to confirm the behaviour with the social links. 
 
 > One issue with it is the modal would sit on top of the flash, preventing campers from reading it. We can close the modal when the Save button is clicked, but then the user would need to reopen the modal if they haven't finished updated their profile. I guess we could fix this by keeping the modal open and changing the z-index so that flash would be on top.
 
 This is the behaviour @ahmaxed suggested. We might be able to change it to something different.

**Comment by ahmaxed** [comment]
I completely understand. We have similar forums on modal on learn and this pattern reflects what others such as Linkedin is doing. Maybe it needs a bit getting used to.

Screenshot 2024-09-24 at 9 36 56 AM

**Comment by ahmaxed** [comment]
Here are a few notes (some might be un related):
- The project cards should have an edit button of their own: [mock](https://github.com/freeCodeCamp/freeCodeCamp/issues/48234#issuecomment-1838175064)
-  The button should preferably be the icon itself.
-  The icon could be changed to 'faPen'.
-  The icon button should be as tall as its contents.
- The form labels should be left aligned similar to the settings page.
- The cards section should be after the activity graph.
- The forms should have client and api validation (github link fails after the closure of the modal)
- We could explore other forms or notifying the user of a faulty submission: alert on the forum, etc.

**Comment by Sembauke** [comment]
Thanks Ahmad, I completely missed this mock.

**Comment by Sembauke** [comment]
Hey @ahmaxed,
I have implemented these suggestions:

1. The button should preferably be the icon itself.
2. The icon could be changed to 'faPen'.
3. The icon button should be as tall as its contents.
4. The form labels should be left aligned similar to the settings page.
5. The modal is too wide. It should have a similar column configurations as the rest of the modals.
6. The cards section should be after the activity graph.

**Comment by ahmaxed** [comment]
Thanks for the heard work here. Here are some feedback on the current state of the pr:
- I still get the double flash components on the latest commit
- Wondering if we should leave a note in the settings page since we are moving a large chunk to the profile page.
- Portfolio section in the modal needs a spacer similar to other sections
- Since the if (!process.env.CI) block is repeated multiple, feel free to make a function and reuse it.

**Review by huyenltnguyen — COMMENTED** [review]
I'm not sure if we still need to iterate more on this PR or we'll have further iterations in the follow-up PRs, so I'm not clicking the Approve button yet (but ping me if you need my stamp).

---

I don't think you enjoy modifying tests, so I went ahead and updated a couple things 😄 You can see the changes in my commits, but here is the summary:
- Added `aria-label` to the icon button (the button needs to have a label text in order to be accessible)
- Improved the test setup of `internet-presence-settings.spec.ts` (this isn't your code, but I came across it as I was reviewing the tests)
  - Previously, the test body includes additional simulation to reset the input values to the original state. This makes the test more complicated and polluted since resetting test data isn't its responsibility (not to mention the test would take longer to run).
  - I removed the irrelevant code and run `seed` in the `beforeEach` block instead
- Swapped `getByTestId()` with better queries

**Comment by Sembauke** [comment]
Stamp it! @huyenltnguyen

**Review by huyenltnguyen — APPROVED** [review]

**Review by ahmaxed — APPROVED** [review]

**Pull request merged**
