### PR TITLE
fix: type error in drop down

### LINKED ISSUE #51364: [ui-components]: type error
Going to any bonfire challenge, this error appears in the browser console:

```console
Warning: Received `true` for a non-boolean attribute `dropup`.

If you want to write it to the DOM, pass a string instead: dropup="true" or dropup={value.toString()}.
    in button (created by ForwardRef)
    in ForwardRef
    in Unknown (created by ToolPanel)
    in div (created by ForwardRef)
    in oe (created by ForwardRef)
    in ForwardRef (created by Dropdown)
    in Dropdown (created by ToolPanel)
    in div (created by ToolPanel)
    in ToolPanel (created by Connect(ToolPanel))
```

- /learn/javascript-algorithms-and-data-structures/es6/use-destructuring-assignment-with-the-rest-parameter-to-reassign-array-elements

Also, there is a TS error in the `tool-panel.tsx` file which is not caught by our linter.

It seems like the ui-components package is not generating types, which is how the error got through.

### PR DESCRIPTION
**Pull request by Sboonny**
Checklist:

- [x] I have read and followed the [contribution guidelines](https://contribute.freecodecamp.org).
- [x] I have read and followed the [how to open a pull request guide](https://contribute.freecodecamp.org/#/how-to-open-a-pull-request).
- [x] My pull request targets the `main` branch of freeCodeCamp.
- [x] I have tested these changes either locally on my machine, or GitPod.

Closes #51364

### CODE REVIEW

**Comment by naomi-lgbt** [comment]
Quick question - do we want to leave the linked issue open so we can address the type generation issue?

**Review by naomi-lgbt — APPROVED** [review]
I see no change in behaviour between this and production, so should be good to merge.

**Comment by Sboonny** [comment]
> Quick question - do we want to leave the linked issue open so we can address the type generation issue?

No need, it should be closed.

Oliver generated the types in one of his old PRs, the component was used before the types were added, which cased the confusion.

**Comment by naomi-lgbt** [comment]
Awesome, thanks for clarifying!

**Review by ojeytonwilliams — APPROVED** [review]
LGTM :+1:

**Pull request merged**
