### PR TITLE
feat(tools, challenge-editor): add script to create challenges

### PR DESCRIPTION
**Pull request by moT01**
This adds a script to create challenges with the markdown included. See comments in the script.

Checklist:

- [x] I have read and followed the [contribution guidelines](https://contribute.freecodecamp.org).
- [x] I have read and followed the [how to open a pull request guide](https://contribute.freecodecamp.org/#/how-to-open-a-pull-request).
- [x] My pull request targets the `main` branch of freeCodeCamp.
- [x] I have tested these changes either locally on my machine, or GitPod.

Closes #XXXXX

### CODE REVIEW

**Review by ojeytonwilliams — APPROVED** [review]
Looks good. Thanks, Tom.

Since this is purely a dev facing thing, I'm happy to merge as is. If there are any bugs, we can fix them as we find them.

**Review by naomi-lgbt — CHANGES_REQUESTED** [review]
Rather than having a hard-coded template that we have to edit (which is version controlled and may result in extraneous noise), we should use the `get-challenge-template.ts` utility to pick a template.

**Comment by moT01** [comment]
I'm not sure I understand how that would work - can you elaborate a little @naomi-lgbt? For some more context, the English team has created all (most of?) the challenges in google docs with the markdown headings and stuff. So the idea with this script is that we can just copy/paste the markdown from there, and run the script to create each challenge - and they (ideally) shouldn't have to adjust the markdown after that.

**Review by naomi-lgbt — APPROVED** [review]
Okay, that makes some sense. I'm still worried about the template changes being committed erroneously, but we can land this.

**Pull request merged**
