### PR TITLE
Clarify when bracket notation is necessary

### PR DESCRIPTION
**Pull request by bhagerty**
Currently, the exercises about objects do not explain that you must use bracket notation when accessing a property by a variable name. This creates confusion in a later exercise, https://www.freecodecamp.org/learn/javascript-algorithms-and-data-structures/basic-javascript/testing-objects-for-properties, because it fails if you use dot notation, and there's no explanation about this. This has confused not just me but also other users (see https://forum.freecodecamp.org/t/basic-javascript-testing-objects-for-properties/347697).

One way to remove the confusion is to include an explanation here that bracket notation is required not just when there's a space in a property name, but also when you're trying to access a property with a variable name.

Checklist:

- [x ] I have read [freeCodeCamp's contribution guidelines](https://contribute.freecodecamp.org).
- [ x] My pull request has a descriptive title (not a vague title like `Update index.md`)
- [ x] My pull request targets the `master` branch of freeCodeCamp.
- [ x] All the files I changed are in the same world language, for example: only English changes, or only Chinese changes, etc.

Closes #XXXXX

### CODE REVIEW

**Comment by RandellDawson** [comment]
@bhagerty The very [next lesson](https://www.freecodecamp.org/learn/javascript-algorithms-and-data-structures/basic-javascript/accessing-object-properties-with-variables) does cover this distinction.  If you believe the next lesson does not make this clear, then I suggested first creating a [GitHub issue](), so the contributor community can discuss it further.

For now I am closing this PR as any such changes referenced in this PR would probably belong in the next lesson.

**Comment by bhagerty** [comment]
@RandellDawson Thanks for the quick response. I understand your point, but the next lesson doesn't actually address the issue that I'm raising. The next lesson tells you that you *may* use bracket notation to index into an object using a variable name. It doesn't say that you *must* do so. The lack of this information—that bracket notation is mandatory for variables, not optional—created confusion both for me and for the commenter whose post I linked to in my original PR, and that confusion arose in an exercise downstream from both this exercise and the next one. In other words, if the next exercise addressed the issue, neither I nor that other person would have been confused.

The first time that the instructions make the point about mandatory use of brackets for variables is several exercises further along, in a "Hint" in the [record collection](https://www.freecodecamp.org/learn/javascript-algorithms-and-data-structures/basic-javascript/record-collection) exercise. That hint says "Use bracket notation when accessing object properties with variables." That hint comes too late; it's needed, at the latest, in [the testing-objects-for-properties exercise](https://www.freecodecamp.org/learn/javascript-algorithms-and-data-structures/basic-javascript/testing-objects-for-properties). 

But I still think that *this* exercise is the right place to make the point, since this exercise is specifically about bracket notation, and it identifies one situation in which brackets are mandatory (when there's a space in a name). A reader would naturally expect that this exercise would identify *all* the situations in which bracket notation is mandatory. By identifying only *one* situation where it is mandatory, the exercise implies that this is the *only* situation in which such notation is mandatory.

Please let me know how you suggest I proceed. I would think that community conversation could happen in connection with this pull request rather than as a separate issue. But if you would prefer that I open an issue, I am happy to do that. I am just trying to be helpful.

**Comment by RandellDawson** [comment]
> The next lesson tells you that you may use bracket notation to index into an object using a variable name. It doesn't say that you must do so.

@bhagerty Not following what you are talking about.  The next lesson is [Accessing Object Properties with Variables](https://www.freecodecamp.org/learn/javascript-algorithms-and-data-structures/basic-javascript/accessing-object-properties-with-variables). In the first paragraph it states:
> Another use of bracket notation on objects is to access a property which is stored as the value of a variable. This can be very useful for iterating through an object's properties or when accessing a lookup table.  I am not seeing anywhere in the next lesson that the word "may" is used.  In fact, the main reason the next lesson was created, was to make the case for the user to use bracket notation when attempting to access an object's property using a variable name.

**Comment by bhagerty** [comment]
Thanks again @RandellDawson for responding. You're right, the next lesson doesn't say "may use" bracket notation. But it also doesn't say "must use" bracket notation. It just says "here's 'another use of bracket notation.'" Since bracket notation is sometimes interchangeable with dot notation, the "another use" language is confusing, and can be read to imply that bracket notation is simply permissive, not mandatory. The proof that it's confusing is that at least two people (me and the commenter I linked to) were confused after reading this and tried to use dot notation rather than bracket notation to access a property by variable name. 

But you are right that the confusion could be eliminated in the following lesson by clarifying that bracket notation is mandatory when accessing a property by variable name. I will make an appropriate PR on that lesson. Thanks.

**Comment by nibble0101** [comment]
@bhagerty  I don't know whether you are following the lessons in order. 

> Currently, the exercises about objects do not explain that you must use bracket notation when accessing a property by a variable name. 

That explanation has already been made in a previous lesson.  [Accessing object properties with variables](https://www.freecodecamp.org/learn/javascript-algorithms-and-data-structures/basic-javascript/accessing-object-properties-with-variables) clearly explains how to access object properties with variables. The first sentence of the lesson states:

> Another use of bracket notation on objects is to access a property which is stored as the value of a variable.

Nowhere does it say you can use dot notation to access object properties using a variable. I think the lesson assumes you already know how to access object properties with variables by using bracket notation like `obj[variableName]` and not dot notation like `obj.variableName`  because it has already been explained in a previous lesson. Though it doesn't hurt to give a hint or a reminder.

**Comment by bhagerty** [comment]
@nibble0101 Yes, I am following the lessons in order. I am very surprised at both your and @RandellDawson's responses to my PR. Basically, I came in saying "I and one other person found this lesson confusing. Here's a fix.," And both of you have responded by saying, in essence,, "The lessons are not confusing, you're just reading them wrong." Neither of you identified anything wrong or misleading in my PR. But rather than accept a harmless PR that, at worst, clarifies something that you don't think is confusing, you both are explaining to me why I shouldn't have been confused. If you are trying to turn off a potential contributor, you are off to a good start.

**Comment by nibble0101** [comment]
> If you are trying to turn off a potential contributor, you are off to a good start.

I am sorry if that is how you look at it. That has never been my intention or @RandellDawson 's because he is among the people encouraging beginners to start contributing to OSS. I am a beginner myself. My understanding of how things work here is that if there is a PR made, members give their opinions about it and those with merge access can merge it if they see fit. I have seen people give their opinions on PRs and i think it is a good thing to incorporate divergent views on pull requests before merging. I am simply giving my own opinion and trying to help you see it from the way i see it. I am saying this because there are sections on FCC that i found confusing but after someone explained it to me, it became clear.

**Comment by RandellDawson** [comment]
To give a little background here.  Typically, when proposing verbiage changes to a challenge, most user create an issue first, where it is hashed out among the mods and other contributors.  Once there is a consensus, we label the issue as `help wanted`.

The reason we prefer users to create an issue first, is to avoid someone spending the time to create a PR for something where the consensus would not be gained.  It is difficult to satisfy everyone's opinion about how the challenges are worded.  If only one or two people want a change and the mods do not believe the change is beneficial, an issue may be closed.

**Pull request closed without merging**
