### PR TITLE
Asterisk problem solved for all the input labels 

### PR DESCRIPTION
**Pull request by uditjainstjis**
- [x] I have read and followed the [contribution guidelines](https://contribute.freecodecamp.org).
- [ ] I have read and followed the [how to open a pull request guide](https://contribute.freecodecamp.org/how-to-open-a-pull-request/).
- [x] My pull request targets the `main` branch of freeCodeCamp.
- [x] I have tested these changes either locally on my machine, or GitPod.

Closes #56714

Changed 

```<label for="full-name">Name*:</label>
<label for="email">Email address*:</label>
```
To 

```<label for="full-name" required>Name:</label>
<label for="email" required>Email address:</label>
```
for all the files.

### CODE REVIEW

**Comment by jdwilkin4** [comment]
As mentioned earlier by the camper-chan bot, make sure not to work on issues that haven't been triaged yet. Otherwise you will end up making the wrong changes.

The issue is now open for contribution.

Your PR does not make the correct changes though.

Please re read through the issue and update the PR accordingly. Thanks

**Comment by jdwilkin4** [comment]
Also, please re read through the contributing guide because your PR title doesn't match the convention laid out in the guide.

https://contribute.freecodecamp.org/how-to-open-a-pull-request/

**Comment by Himanshu145505** [comment]
> * [x]  I have read and followed the [contribution guidelines](https://contribute.freecodecamp.org).
> * [x]  I have read and followed the [how to open a pull request guide](https://contribute.freecodecamp.org/how-to-open-a-pull-request/).
> * [x]  My pull request targets the `main` branch of freeCodeCamp.
> * [x]  I have tested these changes either locally on my machine, or GitPod.
> 
> Closes #56714
> 
> Changed
> 
> ```
> <label for="email">Email address*:</label>
> ```
> 
> To
> 
> ```
> <label for="email" required>Email address:</label>
> ```
> 
> for all the files.




Hii, Can you please share the repository link for the affected file (Issue no : 56719). as i am not able to find that in repository.

**Comment by jdwilkin4** [comment]
@Himanshu145505 

The issue here shares the link you need to start with. You need to look in the section titled `Affected Pages` 
https://github.com/freeCodeCamp/freeCodeCamp/issues/56714

If you have further questions on how to contribute to the issue, it is best to discuss it in the contributors room on discord instead of this PR

**Comment by ilenia-magoni** [comment]
An other PR that solves the issue has been accepted.

**Pull request closed without merging**
