### PR TITLE
Corrected some mistakes in the translation

### PR DESCRIPTION
**Pull request by arsts**
- [x] I have read [freeCodeCamp's contribution guidelines](https://github.com/freeCodeCamp/freeCodeCamp/blob/master/CONTRIBUTING.md).
- [x] My pull request has a descriptive title (not a vague title like `Update index.md`)
- [x] My pull request targets the `master` branch of freeCodeCamp.
- [x] None of my changes are plagiarized from another source without proper attribution.
- [x] My article does not contain shortened URLs or affiliate links.

If your pull request closes a GitHub issue, replace the XXXXX below with the issue number.

Closes #XXXXX

### CODE REVIEW

**Comment by RandellDawson** [comment]
Manually restarted build. Will check back later.

**Comment by RandellDawson** [comment]
@greggubarev Can you review this one?

**Comment by greggubarev** [comment]
@RandellDawson yes ofc, in the near future I will reach it - I go in chronological order

**Comment by RandellDawson** [comment]
@greggubarev I know.  I just wanted to make sure you knew that it was ready to be QAed.  I had originally assigned it to myself, because it had some other issue.

**Comment by greggubarev** [comment]
### LGTM! Congrats on your first contribution! 
Image of Office

**Pull request merged**
