### PR TITLE
fix: Correct paths in English exercises by prefixing "/" before "learn"

### LINKED ISSUE #38005: 404 From Lesson Instructions
**The Issue**

Whilst going through the ReactJS lessons the link to: 

'the way you apply classes to JSX elements.' Isn't working, thus giving a 404. The link it tries to go to is this:

https://www.freecodecamp.org/learn/front-end-libraries/react/learn/front-end-libraries/react/define-an-html-class-in-jsx

I've tested the link in Chrome, Firefox, Safari, Opera, Tor, Chrome Canary and Firefox Dev Edition and same 404.

**The lesson**:

https://www.freecodecamp.org/learn/front-end-libraries/react/introducing-inline-styles

**Screenshots**
Screenshot 2020-01-02 at 11 01 13

and:

Screenshot 2020-01-02 at 11 00 59

Cheers!

### PR DESCRIPTION
**Pull request by AshNaz87**
languages

- [x] I have read [freeCodeCamp's contribution guidelines](https://github.com/freeCodeCamp/freeCodeCamp/blob/master/CONTRIBUTING.md).
- [x] My pull request has a descriptive title (not a vague title like `Update index.md`)
- [x] My pull request targets the `master` branch of freeCodeCamp.
- [x] None of my changes are plagiarized from another source without proper attribution.
- [x] All the files I changed are in the same world language (for example: only English changes, or only Chinese changes, etc.)
- [x] My changes do not use shortened URLs or affiliate links.

Closes #38005

### CODE REVIEW

**Review by RandellDawson — APPROVED** [review]
LGTM.  I have validated there are only 5 such links in the `curriculum/challenges/english` directory.

@raisedadead A quick search in the other languages reveals at additional 27 instances that need to be fixed.
Should we add those to this PR or separate PRs (one for each language)?

**Review by RandellDawson — CHANGES_REQUESTED** [review]
I spoke to soon.  I found one additional challenge that needs to be fixed:

`curriculum/challenges/english/02-javascript-algorithms-and-data-structures/basic-javascript/generate-random-fractions-with-javascript.english.md`

**Comment by raisedadead** [comment]
> A quick search in the other languages reveals at additional 27 instances that need to be fixed.
> Should we add those to this PR or separate PRs (one for each language)?

Lets add the changes in this PR, if its trivial.

**Comment by AshNaz87** [comment]
@RandellDawson Amended the other file (in English)

@raisedadead What should our approach be when a particular exercise has a common issue in all languages?

**Comment by AshNaz87** [comment]
@RandellDawson Added changes to files in other languages

**Review by raisedadead — APPROVED** [review]
Approved from dev team. @RandellDawson please review and merge if happy

**Review by RandellDawson — APPROVED** [review]
Accounted for all 33 instances in the 28 files.  LGTM

**Comment by RandellDawson** [comment]
@AshNaz87 
Thank you for your contribution to the page! 👍
We're happy to accept these changes, and look forward to future contributions. 🎉

**Pull request merged**
