### PR TITLE
Challenge - ES6: Use Destructuring Assignment to Assign Variables from Arrays - Added solution

### PR DESCRIPTION
**Pull request by alanpaulprice**
- [x] I have read [freeCodeCamp's contribution guidelines](https://github.com/freeCodeCamp/freeCodeCamp/blob/master/CONTRIBUTING.md).
- [x] My pull request has a descriptive title (not a vague title like `Update index.md`)
- [x] My pull request targets the `master` branch of freeCodeCamp.
- [x] None of my changes are plagiarized from another source without proper attribution.
- [x] My article does not contain shortened URLs or affiliate links.

If your pull request closes a GitHub issue, replace the XXXXX below with the issue number.

Closes #XXXXX

### CODE REVIEW

**Comment by ValeraS** [comment]
@nikrb Solution is OK. This is a problem with the used babel presets in the client application. Could you make an issue with this screenshot and link to the challenge?

But I think we should remove a function from this challenge.
```js
let a = 8, b = 6;
// change code below this line

// change code above this line
console.log(a); // should be 6
console.log(b); // should be 8
```

**Comment by nikrb** [comment]
@alanpaulprice would you like to update the pr as per valera's preceding comment?

**Comment by ezioda004** [comment]
@ValeraS I've updated this and other ES6 challenges to remove unnecessary IIFE's in this PR: https://github.com/freeCodeCamp/freeCodeCamp/pull/34538

**Comment by alanpaulprice** [comment]
@nikrb done!

**Comment by RandellDawson** [comment]
I just tested this challenge locally.  If you just run the Challenge Seed code, it will show a green check mark on the the last test `Use array destructuring to swap a and b.`, even though no destructuring was used.

image

**Comment by nikrb** [comment]
`code` variable holds user code, from the [docs](https://github.com/freeCodeCamp/freeCodeCamp/blob/master/docs/style-guide-for-curriculum-challenges.md#writing-tests)

**Comment by ValeraS** [comment]
@RandellDawson Client app does not use solutions. Solutions are used only in CI tests.

**Comment by nikrb** [comment]
@RandellDawson I just uncommented the last test and the challenge now seems to work for me. Can you try uncommenting and retesting?

**Comment by RandellDawson** [comment]
@paulywill For the curriculum related PRs, make sure at least 2 other people have approved the PR before merging.  If unsure, just ask before merging in a comment or over on the Gitter channel.

**Comment by paulywill** [comment]
@RandellDawson copy that.

**Pull request merged**
