### PR TITLE
chore: utils/index.js is updated to .ts

### PR DESCRIPTION
**Pull request by palashgdev**
Checklist:

- [x] I have read [freeCodeCamp's contribution guidelines](https://contribute.freecodecamp.org).
- [x] My pull request has a descriptive title (not a vague title like `Update index.md`)
- [x] My pull request targets the `main` branch of freeCodeCamp.
- [x] I have tested these changes either locally on my machine, or GitPod.

Part of https://github.com/freeCodeCamp/freeCodeCamp/issues/43778

### CODE REVIEW

**Comment by scissorsneedfoodtoo** [comment]
Hi @palashgdev, thanks for your patience and for your help with this migration.

Everything is looking good so far, though I think the reason why we're getting linting errors here is that Prettier is checking the `utils/index.js` file that gets created.

Looking at the changed files in [this PR](https://github.com/freeCodeCamp/freeCodeCamp/pull/44921/files), it seems like we need to add `utils/index.js` to [`.gitignore`](https://github.com/freeCodeCamp/freeCodeCamp/pull/44921/files#diff-bc37d034bad564583790a46f19d807abfe519c5671395fd494d8cce506c42947R168-R170) and [`.prettierignore`](https://github.com/freeCodeCamp/freeCodeCamp/pull/44921/files#diff-b640b344ee7f3f03d2a443795a5d0708ef50e2e6e34214109ab2aad13ad6ba98R12-R13).

That seems to fix the problem, at least when running `npm run lint` locally.

**Comment by palashgdev** [comment]
> Hi @palashgdev, thanks for your patience and for your help with this migration.
> 
> Everything is looking good so far, though I think the reason why we're getting linting errors here is that Prettier is checking the `utils/index.js` file that gets created.
> 
> Looking at the changed files in [this PR](https://github.com/freeCodeCamp/freeCodeCamp/pull/44921/files), it seems like we need to add `utils/index.js` to [`.gitignore`](https://github.com/freeCodeCamp/freeCodeCamp/pull/44921/files#diff-bc37d034bad564583790a46f19d807abfe519c5671395fd494d8cce506c42947R168-R170) and [`.prettierignore`](https://github.com/freeCodeCamp/freeCodeCamp/pull/44921/files#diff-b640b344ee7f3f03d2a443795a5d0708ef50e2e6e34214109ab2aad13ad6ba98R12-R13).
> 
> That seems to fix the problem, at least when running `npm run lint` locally.

Sure let me add to `.gitignore`

**Comment by scissorsneedfoodtoo** [comment]
Hi @palashgdev, thanks for these updates. Glad to see the tests are passing now.

Minor nitpick, but would you be able to move your additions of `utils/index.js` in both `.prettierignore` and `.gitignore`?

In `.gitignore`, we have a section for generated files in the `utils` directory here: https://github.com/freeCodeCamp/freeCodeCamp/blob/f0e4131f9dac8ec449cec6289e6227382739d8d7/.gitignore#L168

And while we don't have separate sections in `.prettierignore`, a couple of the generated files in `utils` are on lines 12 and 13: https://github.com/freeCodeCamp/freeCodeCamp/blob/f0e4131f9dac8ec449cec6289e6227382739d8d7/.prettierignore#L12

If you could move the `utils/index.js` line to the "Generated utils files" section in `.gitignore`, and up to around line 12 or 13 in `.prettierignore`, that'd be a big help.

Other than those minor details, everything LGTM.

**Comment by palashgdev** [comment]
No worries @scissorsneedfoodtoo let me update this one

**Comment by palashgdev** [comment]
@scissorsneedfoodtoo can you please check

**Review by scissorsneedfoodtoo — APPROVED** [review]
Awesome, everything LGTM. Thanks again for all of your hard work on this @palashgdev.

This should be ready for another round of review. I'll post this in our team chat to see if someone else can take a look at this.

**Review by ojeytonwilliams — APPROVED** [review]
LGTM. Thanks @palashgdev :+1:

**Pull request merged**
