### PR TITLE
feat(client): show error, warn, and info in FCC debug console

### LINKED ISSUE #48744: FreeCodeCamp Debugging Console iPadOS Support
### Is your feature request related to a problem? Please describe.

Since Covid lots of students have gotten iPads to do their schoolwork. For most of them their iPad is their only device with a large viewport. Their possibility to learn coding is very dependent on browser support. Most of freecodecamp fulfills this requirement, but debugging is quite challenging, because things like console.warn() and the console timer don’t work. This is particularly evident when working on “JavaScript Algorithms and Data Structures” > Debugging.

### Describe the solution you'd like

Allow console to interpret and show:
console.warn(), console.error(), console.time(), console.count(), console.debug(), console.clear() and message grouping.

### Describe alternatives you've considered

Give students on iPad the possibility to use a remote desktop for coding.

### Additional context

You could only show the improved console on iPads to encourage campers on desktop to use the browsers console.

### PR DESCRIPTION
**Pull request by a2937**
Checklist:

- [X] I have read and followed the [contribution guidelines](https://contribute.freecodecamp.org).
- [X] I have read and followed the [how to open a pull request guide](https://contribute.freecodecamp.org/#/how-to-open-a-pull-request).
- [X] My pull request targets the `main` branch of freeCodeCamp.
- [X] I have tested these changes either locally on my machine, or GitPod.

Closes #48744

### CODE REVIEW

**Comment by bbsmooth** [comment]
@a2937 Would you provide some instructions on how to test your fixes.

**Comment by a2937** [comment]
> @a2937 Would you provide some instructions on how to test your fixes.

Manual testing:

Step One: Start up the local FreeCodeCamp client and server with MongoDB database running in the background,
Step Two: Navigate to the client on port 8000 in your preferred web browser. 
Step Three: Open up the curriculum
Step Four: Navigate JavaScript Algorithms and Data Structures  
Step Five: Open a random challenge
Step Six: Find the text box to type the code in
Step Seven: In the text box type `console.log("Hello");` to have something to compare it to.  Notice in the output it says "Hello" 
Step Eight: Type `console.info("Hello");` into the text box. Notice it should say "Hello" in the output as well. 
Step Nine: Type `console.warn("Warning");` into the text box. Notice it should say "Warning" in the output.
Step Ten: Type `console.error("Error");` into the text box. Notice it should say "Error" in the output.

As for automated testing, I would be happy to provide some. However I had difficulty finding unit tests for the proxy logger.

**Comment by Sboonny** [comment]
> As for automated testing, I would be happy to provide some. However I had difficulty finding existing unit tests for the proxy logger.

I don't think it's needed, there are no steps that requires using them, and when there will be one, the step itself will act as the unit test

**Comment by a2937** [comment]
Understandable.

**Review by naomi-lgbt — APPROVED** [review]
image


I wish we could DRY this out a bit, but it works as is!

**Comment by a2937** [comment]
> image
> 
> I wish we could DRY this out a bit, but it works as is!

I could create a new method in test-evaluator called "postLogs" that would take care of the biggest offender.

**Review by naomi-lgbt — APPROVED** [review]
Works for me!

**Review by Sembauke — APPROVED** [review]

**Pull request merged**
