### PR TITLE
feat(e2e): adding playwright e2e tests for /learn page

### PR DESCRIPTION
**Pull request by Ahmadkashif**
Checklist:

- [x] I have read and followed the [contribution guidelines](https://contribute.freecodecamp.org).
- [x] I have read and followed the [how to open a pull request guide](https://contribute.freecodecamp.org/#/how-to-open-a-pull-request).
- [x] My pull request targets the `main` branch of freeCodeCamp.
- [x] I have tested these changes either locally on my machine, or GitPod.

Closes #XXXXX

### CODE REVIEW

**Comment by Ahmadkashif** [comment]
Hi @raisedadead :wave: 

This PR contains a simple rewrite of e2e tests in playwright, of the existing cypress tests for /learn page.

**Review by naomi-lgbt — COMMENTED** [review]
Are we able to include the test that asserts the quote appears correctly for an authenticated user?

**Review by raisedadead — CHANGES_REQUESTED** [review]
@Ahmadkashif, when you get a chance can you confirm the expansion requested here: https://github.com/freeCodeCamp/freeCodeCamp/pull/51276#pullrequestreview-1579595645

That is do you want to address that here or in a new PR? If later, please add an issue to track this.

Thanks.

**Comment by Ahmadkashif** [comment]
Hi @raisedadead @naomi-lgbt 👋 

The login functionality is a bigger feature as it will require a global job setup for login. I suggest we roll with this much progress first and track the remaining in an issue, if you guys see that fit.

**Comment by Ahmadkashif** [comment]
@raisedadead @naomi-lgbt 

I have added an issue to track this request of yours. Rest assured, setting up a login job for playwright is next task in our to-do list.

**Review by naomi-lgbt — APPROVED** [review]

**Review by raisedadead — APPROVED** [review]

**Comment by rahulsuresh-git** [comment]
> Are we able to include the test that asserts the quote appears correctly for an authenticated user?

I've added a test for this on this PR https://github.com/freeCodeCamp/freeCodeCamp/pull/52449
Do take a look :)

**Pull request merged**
