### PR TITLE
Bump loopback component passport

### PR DESCRIPTION
**Pull request by BerkeleyTrue**
Steps to QA
1. create account with GitHub
2. sign out
3. create account with Twitter
4. Attempt to link Github

You should see a flash message letting you know that account is already taken.

### CODE REVIEW

**Comment by BerkeleyTrue** [comment]
@FreeCodeCamp/issue-moderators please QA and merge (should be pretty simple)

**Comment by SaintPeter** [comment]
We would need to have our own Twitter API key to test this, yes?

**Comment by BerkeleyTrue** [comment]
No I believe you can swap twitter for email

**Comment by ltegman** [comment]
Sorry for the delay on this -- took me a while to get the Github and Twitter OAuth stuff setup correctly in my dev environment. Looks great -- I get a flash message telling me what's wrong and how to resolve it!

**Comment by BerkeleyTrue** [comment]
Woot!

**Pull request merged**
