### PR TITLE
Description of "Filter Arrays with .filter" updated

### LINKED ISSUE #10695: Filter: Rewrite double negative
Challenge [Filter Arrays with filter](https://www.freecodecamp.com/challenges/filter-arrays-with-filter) has an issue.

The intro sentence uses a double negative:

> The filter method is used to iterate through an array and filter out elements where a given condition is not true.

I suggest re-writing in the positive because it's easier to read and understand. Also, it's how I happen to think of `filter`, and maybe others do too. Here I made that change, plus removed "filter" from its own definition, and changed it from passive to active voice:

_The filter method iterates through an array and selects elements where a given condition is true._

### PR DESCRIPTION
**Pull request by theshubhamp-zz**
#### Pre-Submission Checklist

- [x] Your pull request targets the `staging` branch of FreeCodeCamp.
- [x] Branch starts with either `fix/`, `feature/`, or `translate/` (e.g. `fix/signin-issue`)
- [x] You have only one commit (if not, [squash](http://forum.freecodecamp.com/t/how-to-squash-multiple-commits-into-one-with-git/13231) them into one commit).
- [x] All new and existing tests pass the command `npm run test-challenges`. Use `git commit --amend` to amend any fixes.
#### Type of Change

- [x] Small bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds new functionality)
- [ ] Breaking change (fix or feature that would change existing functionality)
- [ ] Add new translation (feature adding new translations)
#### Checklist:

- [x] Tested changes locally.
- [x] Closes currently open issue (replace XXXX with an issue no): Closes #10695
#### Description

Fixes issue #10695
The description of the challenge "Filter Arrays with .filter" was updated to remove double negatives from the description as pointed out in the issue #10695

### CODE REVIEW

**Comment by dhcodes** [comment]
@shubham1996 Can you amend this to make the beginning of the sentence be `The <code>filter</code> method`...

Sorry for not being more explicit in the issue thread. Otherwise, looks good.

**Comment by shubham1996** [comment]
Yeah,  Sure 👍

**Comment by shubham1996** [comment]
I have updated the Pull Request.

Sorry for the previous pull request btw, I didn't amend the commit and realized it later. :smile:

**Comment by dhcodes** [comment]
No worries, I do that all the time. Look gtg to me @shubham1996 

Thanks for contributing! 👍 👍

**Pull request merged**
