### PR TITLE
DF Operation, follow up article on DataFrame

### PR DESCRIPTION
**Pull request by harikrishnand**
Comprehensive article on Pandas DataFrame basic operation and methods.

- [x] I have read [freeCodeCamp's contribution guidelines](https://github.com/freeCodeCamp/freeCodeCamp/blob/master/CONTRIBUTING.md).
- [x] My pull request has a descriptive title (not a vague title like `Update index.md`)
- [x] My pull request targets the `master` branch of freeCodeCamp.
- [x] None of my changes are plagiarized from another source without proper attribution.
- [x] My article does not contain shortened URLs or affiliate links.

If your pull request closes a GitHub issue, replace the XXXXX below with the issue number.

Closes #XXXXX

### CODE REVIEW

**Comment by RandellDawson** [comment]
Closed and Reopened this PR to attempt to resolve a specific Travis build failure.

**Comment by paulywill** [comment]
@harikrishnand Where is this article referenced and linked to?

**Comment by harikrishnand** [comment]
@paulywill : Thank you so much for reviewing them. This article is about DataFrame operations. The base article is on DataFrame is #31801 and it is still pending for merge.

Please let me know anymore question.

Thanks,
Hari.

**Comment by paulywill** [comment]
@harikrishnand Well done!

**Pull request merged**
