### PR TITLE
feat(donation): simplify donation client

### PR DESCRIPTION
**Pull request by ahmaxed**
This PR restructure the client side of our donation and increases the donation test coverage.
Here are the stripe cards for testing. https://stripe.com/docs/testing#regulatory-cards

Checklist:

Checklist:

- [x] I have read [freeCodeCamp's contribution guidelines](https://contribute.freecodecamp.org).
- [x] My pull request has a descriptive title (not a vague title like `Update index.md`)
- [x] My pull request targets the `main` branch of freeCodeCamp.
- [x] I have tested these changes either locally on my machine, or GitPod.

Closes #XXXXX

### CODE REVIEW

**Review by moT01 — COMMENTED** [review]
I gave this some testing, overall it looks good (I think). Didn't look through it too hard - but I did find one issue...

Dec-09-2022 10-50-17
I kind of hangs at this "processing" spot when I close the patreon window without doing anything. I didn't get this far, but I presume it would do the same if I completed the donation in patreon as well - since it kind of just opens that window and you do everything in there I think. Not sure though.

**Comment by bbsmooth** [comment]
The FAQ disclosure buttons could use a little help as far as accessibility is concerned. Is that out of scope for this PR?

**Comment by moT01** [comment]
My general philosophy is that if the behavior was preexisting, then it is outside the scope - but can still be fixed here if the PR author wants to. If this PR added that item or caused it to behave problematic, then it probably should be fixed here.

**Comment by bbsmooth** [comment]
> My general philosophy is that if the behavior was preexisting, then it is outside the scope

Makes sense. The FAQ button issue is pre-existing, so I will address it in a separate PR.

**Comment by ahmadabdolsaheb** [comment]
@moT01 @bbsmooth thanks for looking into the pr and catching the Patreon issue. 
While I am fixing up the issue, feel free to give the pr a thorough review. 🙌

**Comment by moT01** [comment]
I gave it about as good of a look as I could - I just say "Didn't look through it too hard" in case I missed something. The only other thing I noticed was that you're passing a lot of strings around, e.g. `paymentProvider: 'stripe card'` and `paymentContext='donate page'`. You could maybe turn those into an enum or something so they're less prone to typos.

**Comment by ahmadabdolsaheb** [comment]
@moT01 as soon as I turned the settings file into .ts to add the enum, the whole repo lit up with errors. 🙌

**Comment by moT01** [comment]
Let us know when this is ready for another look @ahmadabdolsaheb

**Comment by ahmadabdolsaheb** [comment]
@moT01 yes please.

**Review by moT01 — APPROVED** [review]
LGTM 🎉

**Review by ojeytonwilliams — COMMENTED** [review]
Hey @ahmadabdolsaheb, this all works nicely, but I'm not 100% convinced that this is the best way to combine the logic.

Reason being we have to have this argument type

```ts
interface PostPayment {
  paymentProvider: PaymentProvider;
  data?: DonationApprovalData;
  token?: Token;
  payerEmail?: string | undefined;
  payerName?: string | undefined;
  paymentMethodId?: string;
  handleAuthentication?: HandleAuthentication;
}
```

but if you look at the usage, we have 

```ts
{ 
  paymentProvider: PaymentProvider.Patreon
}
```

```ts
{ 
  paymentProvider: PaymentProvider.Paypal,
  data 
}
```

```ts
{  
  paymentProvider: PaymentProvider.StripeCard,
  paymentMethodId: paymentMethod.id,
  handleAuthentication
}
```

and

```ts
{
  paymentProvider: PaymentProvider.Stripe,
  token,
  payerEmail,
  payerName
}
```
           
Which is to say, they're all very different. In isolation this isn't too bad, but now consider `postCharge`.  That gets called with

```
{
      paymentProvider,
      paymentContext,
      amount,
      duration,
      data,
      token,
      email: email || payerEmail,
      name: payerName,
      paymentMethodId,
      handleAuthentication
    }
```

and we end up having to pick apart these properties inside the `postChargeSaga`. At that point it's not at all obvious which properties belong with which api calls and further processing. 

So, what I'm wondering is this: can we keep the nice bits of this refactor without ramping up the complexity of `postChargeSaga`?

One possible approach would be to split the data like so

```ts
type PaypalData = DonationApprovalData
type StripeData = {
  token?: Token;
  payerEmail?: string | undefined;
  payerName?: string | undefined;
}
type StripeCardData = {
  paymentMethodId?: string;
  handleAuthentication?: HandleAuthentication;
}
```
And then the saga could do things like this

```ts
if(paymentProvider === PaymentProvider.StripeCard) yield call(handleStripeCard, stripeCardData);
if(paymentProvider === PaymentProvider.Stripe) yield call(handleStripe, stripeData)
```

that way it's obvious both what the data is for and that it is getting used correctly.

**Comment by ojeytonwilliams** [comment]
@ahmadabdolsaheb yeah, that sounds good. We can handle that in a follow-up PR.

**Comment by raisedadead** [comment]
We are officially on Node.js 18 now. We have changed the merge requirements accordingly.

You will need to rebase this PR against the main branch OR Click the "Update branch" button to get the new checks going.

Thanks for your contribution.

**Pull request merged**
