### PR TITLE
fix(learn): updated challenge text to clarify when to start using new boilerplates

### PR DESCRIPTION
**Pull request by tmonks**
Updating challenge text to make it more clear that learners need to switch to new boilerplate.

When going through the Advanced Node & Express challenges, it's not very clear that there are two points where you should switch to a new boilerplate, which causes all kinds of problems with passing the tests. I didn't find an issue for this specifically, but I did find other people who struggled with this in the forum and several issues:

- [Advanced Node and Express - Implementation of Social Authentication Issues with the testing](https://www.freecodecamp.org/forum/t/advanced-node-and-express-implementation-of-social-authentication-issues-with-the-testing/236670)
- [Issue 17763](https://github.com/freeCodeCamp/freeCodeCamp/issues/17763)
- [Issue 17068](https://github.com/freeCodeCamp/freeCodeCamp/issues/17068)
- [Issue 36050](https://github.com/freeCodeCamp/freeCodeCamp/issues/36050)

This is my first ever pull request, so please let me know if there's anything I improve upon. Thanks!

- [x] I have read [freeCodeCamp's contribution guidelines](https://github.com/freeCodeCamp/freeCodeCamp/blob/master/CONTRIBUTING.md).
- [x] My pull request has a descriptive title (not a vague title like `Update index.md`)
- [x] My pull request targets the `master` branch of freeCodeCamp.
- [x] None of my changes are plagiarized from another source without proper attribution.
- [x] All the files I changed are in the same world language (for example: only English changes, or only Chinese changes, etc.)
- [x] My changes do not use shortened URLs or affiliate links.

Closes #XXXXX

### CODE REVIEW

**Review by moT01 — COMMENTED** [review]
Feels a little strange to start the paragraph off with a `Note`. There's another challenge which had the same issue and the wording was changed to what is [in this file](https://github.com/freeCodeCamp/freeCodeCamp/blob/master/curriculum/challenges/english/06-information-security-and-quality-assurance/information-security-with-helmetjs/understand-bcrypt-hashes.english.md). The text reads: `"For the following challenges, you will be working with a new starter project that is different from earlier challenges. This project is being built upon the following starter project on Glitch, or cloned from GitHub."` I think these should say that, although I would prefer it to say `"different from the previous one"` instead of `"different from earlier challenges"`

> This is my first ever pull request, so please let me know if there's anything I improve upon. Thanks!

Looks like you made the PR correctly and gave it a good title and everything as far as I can tell. 👍 My only suggestion would be to make an issue first so the changes can be discussed. We would have been able to figure out the verbiage we wanted before a PR was made. For now, it's fine to finish the discussion here.

Anyway, to be clear, I would like this PR to change these two files and the one I linked above to read: `"For the following challenges, you will be working with a new starter project that is different from the previous one. This project is being built upon the following starter project on Glitch, or cloned from GitHub."`

Hmm, still sounds a little weird to me. Specifically, the last sentence, but good enough I suppose. Mainly, I would like to see these three files use the same wording.

**Comment by scissorsneedfoodtoo** [comment]
@moT01, thank you for your review and for pointing out the changes in the other challenge. I agree that changing the text here to more closely match the text in the other challenge makes the most sense. 

I agree that the last sentence does sound a bit strange given that it's using a totally new boilerplate. Perhaps it could read:

`"Use the new starter project on Glitch, or clone it from GitHub."`

Or:

`"You can find the new starter project on Glitch, or clone it from GitHub."`

**Comment by tmonks** [comment]
Excellent, thanks for the feedback guys. I like the suggested wording better.  So I'll update all 3 files with the following text and update my PR today:

`"For the following challenges, you will be working with a new starter project that is different from the previous one. You can find the new starter project on Glitch, or clone it from GitHub."`

**Comment by tmonks** [comment]
Okay, I made and committed the improvements discussed. Please let me know if there's anything else I can do to improve it.

**Comment by scissorsneedfoodtoo** [comment]
Awesome, thank you for making those updates so quickly @tmonks. Everything LGTM. 

Please go ahead and merge this if everything checks out @moT01.

**Review by moT01 — APPROVED** [review]
LGTM @tmonks 🎉 Congratulations on your first contribution to the freeCodeCamp codebase 🎉 We look forward to future contributions. Thanks and happy coding!

**Comment by tmonks** [comment]
Thanks so much @moT01 & @scissorsneedfoodtoo! Really appreciate the guidance and help with my first PR. Looking forward to making more contributions.

**Pull request merged**
