### PR TITLE
Emphasize that solution links need to be of form https:// especially …

### PR DESCRIPTION
**Pull request by rokujohaven**
…for Glitch users

I found out about this the frustrating way. The URL I pasted from glitch was of the form http:// and that's why my solution was not able to pass the tests, even though it worked. 
Once I changed the URL to https:// it passed the tests. 
I think other students should be very aware of this to not cause unnecessary confusion about their solutions.

Checklist:

- [x] I have read [freeCodeCamp's contribution guidelines](https://contribute.freecodecamp.org).
- [x] My pull request has a descriptive title (not a vague title like `Update index.md`)
- [x] My pull request targets the `main` branch of freeCodeCamp.
- [x] All the files I changed are in the same world language, for example: only English changes, or only Chinese changes, etc.

Closes #XXXXX

### CODE REVIEW

**Comment by RandellDawson** [comment]
Not sure this is really needed as the placeholder for the solution link shows `ex: https://project-name.camperbot.repl.co`.

Also, not sure how you would copy/paste an `http` version from Glitch because when you preview the site it is always in `https`.

**Comment by miku86** [comment]
> Not sure this is really needed as the placeholder for the solution link shows `ex: https://project-name.camperbot.repl.co`.
> 
> Also, not sure how you would copy/paste an `http` version from Glitch because when you preview the site it is always in `https`.

I think that's a tricky one, because the new browser security features require you to not have mixed content, so actually **every** lesson where you have to add an URL should have this hint, if we add this.

**Review by moT01 — COMMENTED** [review]
> every lesson where you have to add an URL should have this hint, if we add this.

I agree that this is not a good place for this message, as it would only make sense here if we add it to all the other lessons - which seems like overkill.

The first lesson in each section seems to have a little intro that might be a good spot for a message like this...

Screen Shot 2021-02-18 at 8 18 03 AM

Perhaps, "Then submit the `https` version of the URL to it in the `Solution Link` field." Then we would only need one per section and it's a very minimal addition. 

I am curious how many people make this mistake, has anyone noticed many forum posts around this? I feel like the more common problem is that people try to submit the URL to their code instead of the live demo.

We could attempt to accept http submissions, but I'm guessing there's a reason we don't - or can't. I guess we could maybe replace the `http` with `https` on our end for them before running the tests.

Typically, it is best to open an issue before making a PR @rokujohaven so we can have this discussion first. No big deal though.

**Comment by rokujohaven** [comment]
Yeah after submitting the request I realized it would actually apply to
each of the challenges in this series.

But I think the http (instead of https) was copied because we were playing
around with the API query calls. Along the way I think Glitch just ended up
taking away the 's' in https which would normally be there.

So I didn't have this issue until this exercise. It tripped me up for a few
hours. Just didn't want anyone else to experience the same.

**Comment by nhcarrigan** [comment]
Should this be added to the solution form validator instead?

**Comment by raisedadead** [comment]
> Should this be added to the solution form validator instead?

That is correct. Hey @rokujohaven we think @nhcarrigan is correct here, this is something that should be added to the URL validator.

Do you mind closing this PR and creating a GitHub issue thread instead?

**Comment by moT01** [comment]
I added a post about this on the related issue I linked, so I think it's safe to close. Thanks for bringing this to our attention @rokujohaven. We won't be solving this problem with the solution here, you are free to try and tackle it with the suggested solution.

**Pull request closed without merging**
