### PR TITLE
Move the comment on line 71 to its own line

### PR DESCRIPTION
**Pull request by monicaleep**
The comment "use function argument destructuring" was on the same line as some code, and when displayed as a challenge it returned to a new line and was not commented out.

- [x] I have read [freeCodeCamp's contribution guidelines](https://github.com/freeCodeCamp/freeCodeCamp/blob/master/CONTRIBUTING.md).
- [x] My pull request has a descriptive title (not a vague title like `Update index.md`)
- [x] My pull request targets the `master` branch of freeCodeCamp.
- [x] None of my changes are plagiarized from another source without proper attribution.
- [x] All the files I changed are in the same world language (for example: only English changes, or only Chinese changes, etc.)
- [x] My changes do not use shortened URLs or affiliate links.

Closes #XXXXX

https://www.freecodecamp.org/learn/javascript-algorithms-and-data-structures/es6/use-destructuring-assignment-to-pass-an-object-as-a-functions-parameters

### CODE REVIEW

**Comment by RandellDawson** [comment]
@monicaleep Unless the color of the commented code is not `green`, then it is not an issue.  The code is just wrapping in the editor.  This is not really an issue.  Can you post a screenshot of the comment that you think is not commented out?

Also, can you please add a link to the challenge?  It makes it easier for reviewers to link directly to the challenge, instead of having to find the challenge on the site.

Thank you.

**Comment by monicaleep** [comment]
Hi @RandellDawson 
This is the link to challenge I also updated original comment [challenge](https://www.freecodecamp.org/learn/javascript-algorithms-and-data-structures/es6/use-destructuring-assignment-to-pass-an-object-as-a-functions-parameters)


I just checked again the challenge and it is strange. The code is acting OK as if comment is working, but color is NOT green.
Capture

**Review by thecodingaviator — APPROVED** [review]

**Review by Manish-Giri — CHANGES_REQUESTED** [review]
@monicaleep Thank You for your contribution. While I like this change, would it perhaps be better to reverse the order of the comments, such that the `// change code below this line` reflects the actual code to be changed, and not the new comment, like so -

Screenshot_2020-01-13 Learn ES6 Use Destructuring Assignment to Pass an Object as a Function's Parameters freeCodeCamp org

**Review by monicaleep — COMMENTED** [review]
Hi, yes I agree!

**Comment by Manish-Giri** [comment]
Cool, feel free to make the change in your PR and re-submit!

**Review by thecodingaviator — CHANGES_REQUESTED** [review]
See @Manish-Giri 's review

**Comment by monicaleep** [comment]
Thank you @Manish-Giri it is my first ever pull request (outside of tutorials) so I'm still learning the terminology.

**Review by RandellDawson — APPROVED** [review]

**Comment by RandellDawson** [comment]
@Manish-Giri, @thecodingaviator What do you think about the changes now?

**Review by Manish-Giri — APPROVED** [review]
LGTM 💯

**Review by thecodingaviator — APPROVED** [review]

**Comment by thecodingaviator** [comment]
Thanks for contributing to the freeCodeCamp repository. Congratulations on your first PR! 🎊 

Look forward to more contributions from you! ✈️

**Pull request merged**
