### PR TITLE
I created a tool for easy creating / editing challenges.

### PR DESCRIPTION
**Pull request by 777genius**
I worked a lot on this and I hope not in vain. In the future I plan to add test launches and more. It all depends on how many people will use this tool.

- [x] I have read [freeCodeCamp's contribution guidelines](https://github.com/freeCodeCamp/freeCodeCamp/blob/master/CONTRIBUTING.md).
- [x] My pull request has a descriptive title (not a vague title like `Update index.md`)
- [x] My pull request targets the `master` branch of freeCodeCamp.
- [x] None of my changes are plagiarized from another source without proper attribution.
- [x] All the files I changed are in the same world language (for example: only English changes, or only Chinese changes, etc.)
- [x] My changes do not use shortened URLs or affiliate links.

### CODE REVIEW

**Comment by raisedadead** [comment]
#### This is amazing. 

I like what you have here. I think we would need to have it under freeCodeCamp though before we can officially recommend it in our docs. Would you be interested in this?

If yes, we could add this to our contributors tools.

Let us know. You can also hit us up on on the [Contributors Chat room](https://gitter.im/FreeCodeCamp/Contributors).

**Comment by thecodingaviator** [comment]
WOW, excellent work @iliyaZelenko

**Comment by RandellDawson** [comment]
In the future, you should probably create an issue first to discuss your ideas.  The only problem I see with the tool, is that you are suggesting copying/pasting the challenge seed, solutions, tests section via the GitHub site.  The problem with this, is it really needs to be tested locally first and if you had already tested it locally first, you would already created the entire file.

Maybe the app should stick to creating the template and then copying/pasting it to the local development where they would actually write the tests and test their code locally.  Also, we no longer need the assert message arguments in the testString section.  They can simply be in the `text` section and will display appropriately.  For all new challenges and existing challenges being changed, we are actually removing those from the asserts.

**Comment by iliyaZelenko** [comment]
@raisedadead 

> I like what you have here. I think we would need to have it under freeCodeCamp though before we can officially recommend it in our docs. Would you be interested in this?

Do you mean to add to your site and maybe add it to your repository? I would like this project to be on my github repo, it will be easier for me to receive feedback messages through issuess, receive PR's, I can easily follow this and react quickly, I would also like to receive stars for this project.

What if I make updates to this tool, how will I send them to you if it is on your hosting? I would like to improve a lot more and I will need to correct mistakes.

---

@RandellDawson 

> In the future, you should probably create an issue first to discuss your ideas. 

I created the [topic on your forum](https://www.freecodecamp.org/forum/t/tool-for-for-easy-creation-challenges-in-the-browser/262573), for 10 days there were no clear answers, I thought you should first see the prototype to understand it better.

> Maybe the app should stick to creating the template and then copying/pasting it to the local development where they would actually write the tests and test their code locally.

Those who develop locally can create / update the challange with my tool, then copy the project to themselves in the forked local project and check the work there, nothing seems to prevent them from doing so.

In the future, I plan to run tests right in my tool. Thus, testing locally will not be required. But I'm not 100% sure that my tool generates a file without a single error (it’s unlikely there is an error). Interestingly, you have CI runs tests for checking the challenges that there are no errors? If yes, then nothing to worry about. If not, then there is an idea to make on your site the REST API endpoin to which my tool would send the generated file and your backend will check everything for validity, if there are errors, they would be displayed to the user. Such an error can occur if the user enters something wrong or the tool does not correctly generate the file (unlikely), the user will need to do a bug report in this case.

>  Also, we no longer need the assert message arguments in the testString section.

Didn't know it, I will make my generator remove the unnecessary part.

---

I also noticed that often the description, tests, etc. are written without conveniently readable indents, I could fix it using [prettier](https://prettier.io/docs/en/api.html) and save it without any problems in the yaml or the usual html markup. You can specify your style preferences in the prettier configuration file, I can read them.

I have more ideas, I will be very motivated if people really start using my tool.

**Comment by RandellDawson** [comment]
>I created the topic on your forum, for 10 days there were no clear answers, I thought you should first see the prototype to understand it better.

@iliyaZelenko Not everyone reads posts on the forum.  When creating new concepts, it is best to create an issue on GitHub to discuss and make sure you do not potentially go down a path which is not seen as useful.  

> Those who develop locally can create / update the challange with my tool, then copy the project to themselves in the forked local project and check the work there, nothing seems to prevent them from doing so.

Again, I am not seeing the benefit if they are doing this locally, they can copy/paste the template from the [How to Work on Coding Challenges](https://github.com/freeCodeCamp/freeCodeCamp/blob/master/docs/how-to-work-on-coding-challenges.md#challenge-template) doc.  

Like I said in my previous comment.  I think the idea of generating a template (locally or on a site) is fine, but outside of maybe creating new challenges (auto-generating challenge ID is a nice feature), I don't see any advantage (especially not for existing challenges).   Why?  Because you will still want to run the tests (`npm run test:curriculum`) to validate nothing introduced into the challenge file breaks anything before creating a PR.

That being said, Maybe it is possible to integrate some/all of this in our contribute.freecodecamp.org site (@raisedadead )? 

@raisedadead Correct me if I am wrong, but we will really not be focused on creating new challenges in the current curriculum which this template uses, because the new curriculum (which is being developed now)?  If so, then it might be best to wait until the new curriculum team gets a couple working challenges to see how such a template tool could work with them.

**Comment by RandellDawson** [comment]
@raisedadead I think this whole discussion should be put on an issue, seeing that we are not going to merge this PR as is (with a link to an unofficial outside tool).

**Comment by raisedadead** [comment]
@RandellDawson 

I see your concern, and thanks a lot for your views.

But, just to be clear for all intents and purposes pull requests are exactly like issues. GitHub literally doesn't differentiate between them (take a look at the issue no and pr no that are generated, when any issue or pr is created).  PRs have everything that any issue has, with the added ability to share code that the OP and maintainers can test. 

There is no reason to not discuss over a PR. Creating an issue is *highly recommended*, but I don't see any value in moving discussions over once it has started and is going ahead in a meaningful way. 

Or to look at it differently, a PR brings in more responsibility (because of an actionable purpose), while going through the discussion on it.

To be clear, we have not decided yet, we want to close this PR or not. If the discussion goes like intended, the OP is able to update a PR.

Hope, that makes sense 🙂!

@iliyaZelenko 

> Do you mean to add to your site and maybe add it to your repository? I would like this project to be on my github repo, it will be easier [...]

Thanks for your reply.

You have done some incredible job with this tool, and it's great to know you are interested in developing it further.

But, I see where you are coming from. I am assuming this (contributing to open source) is new for you in general? 

IMHO, we are unable recommend a tool to our contributors, that we do not have any control over.

There are some simple reasons:

- We want to invest our time and efforts in a tool that we recommend, just like you who are creating it.
- We understand that you are motivated. But, neither us and nor you can guarantee once people start using the tools you will be able to dedicate yourself to fix and add things. People become busy and life happens. Its, literally how open source works. We as a community can avoid that, though. Even after you are no longer able to maintain it, the community will keep developing it.
- Having it under our umbrella, we would be able to seek help from hundreds of contributors and the entire core team (maintainers/moderators and freeCodeCamp employees alike) to drive development and maintenance.
- If you are worried about due credit, Open Source makes it very easy to debunk that myth. Take a look at the [README file on our Testable projects](https://github.com/freeCodeCamp/testable-projects-fcc#credits).
- We can have you onboard the org, and give you all the access that you need, to be able to contribute. Review contributions from fellow contributors to the tool. 
- As for hosting, that's literally the job of freeCodeCamp Dev team. They are responsible for deploying and upkeep for all applications. So that is covered.
- There are a few other technical gotchas here (namely license issues, etc.), but I am not going to go over those here.

I hope that makes sense.

You can [reach me on Gitter](https://get.ms/chat) for a more private realtime chat, and I am happy to hop on a call to clarify any of your reservations in person.

Again thanks a lot for your hard work on this tool, and we would love to be able to use it.

**Comment by iliyaZelenko** [comment]
@raisedadead 

Thank you very much for the good explanation, it was very intelligible. I do not have more experience in organizations and I did not understand something, but you explained to me what I needed.

As far as I understand, my repository with the project will be added to your organization and I will be a member of the organization and will be able to manage the repository like other members (maybe I will have more rights). This is cool! I like it. 

Maybe I should do something now to get my project in the organization?

@RandellDawson 

Did I understand correctly? You do not see the point in this tool if you need to make some small changes (for example, change the title and / or description), because you can make them on the Github itself and be sure that nothing breaks. If the changes are not simple (for example, test changes), then they need to be tested locally, and in this case it is not convenient to constantly copy the generated file from my tool to the local project.

---

@raisedadead 
@RandellDawson 

I have an idea. I could make my tool through the package for npm (package.json), that is, it will be a dependency in your project. 

This dependency will have a console command, for example, `npx curriculum-manager`, what happens after the launch of this command (my package as CLI)? The server is started on any port, for example, `localhost:7777`, when opening this server, the browser shows what you have already seen on the site of my tool, when editing you need to select a challenge, the choice will be slightly different, you will not need to enter a link, there will be an interactive tree (the tree is generated from folders and files in the `curriculum\challenges` directory). 

After selecting the desired challenge (challenge file) in the tree, the editing page is displayed, and then an **important point**: when changing the form (which you have already seen on the site), the corresponding challenge file on the local project changes (**my tool will edit the file itself**). 

That is, there will be no need to constantly copy from site to file on a local project. In essence, this is editing the same local file, but more conveniently via the UI (form, etc.), which can contain additional features. 

You understand what through UI is more convenient than through a file? In fact, challenge files no longer need to be changed by users. The creation is essentially the same, but my tool will still create a new file before it.

This option, by the way, solves the problem with hosting as the site of my tool will be launched locally!

Most likely this can be done using Node.js, I have experience with it. Should I redo my tool for this variant?

**Comment by raisedadead** [comment]
Hi @iliyaZelenko 

Thanks for your reply and understanding.

There are a couple of different approaches that we can take for this. How about you, me and @RandellDawson jump on a call to coordinate this? If you are open, [please DM me on Gitter](https://get.ms/chat).

Thanks.

**Comment by raisedadead** [comment]
I am closing this PR itself because we would not need the change here, however we are still interested in the tool as its own independent application. Probably a nice way to go about this would be to discuss on a separate issue thread instead

**Pull request closed without merging**
