### PR TITLE
fix: size your images challenge

### LINKED ISSUE #39569: Learn: Size your images challenge not working in Safari
[This challenge](https://www.freecodecamp.org/learn/responsive-web-design/basic-css/size-your-images) is not working in Safari. 

See [this thread](https://github.com/freeCodeCamp/freeCodeCamp/pull/38770#issuecomment-691682076)

I suppose a fix would be to rewrite the regex.

### PR DESCRIPTION
**Pull request by moT01**
Checklist:

- [x] I have read [freeCodeCamp's contribution guidelines](https://contribute.freecodecamp.org).
- [x] My pull request has a descriptive title (not a vague title like `Update index.md`)
- [x] My pull request targets the `master` branch of freeCodeCamp.
- [x] All the files I changed are in the same world language, for example: only English changes, or only Chinese changes, etc.

Closes #39569

### CODE REVIEW

**Comment by RandellDawson** [comment]
Still need to make sure the applicable css appears inside the `style` element some how.

**Comment by Sky020** [comment]
> Still need to make sure the applicable css appears inside the style element some how.

This was the whole idea of the first PR that got out of hand. Because the test ensures there is this code:
```
.smaller-img {
  width: 100px;
}
```
If the code is in the correct place (within the `style` tags), then the image will be `.width() < 200`
If the code is not in the correct place, then the image will not be `.width() < 200`

_At least to what I would call a-reasonably-degree-of-certainty_

**Comment by moT01** [comment]
> Still need to make sure the applicable css appears inside the `style` element some how.

I'm not convinced that's necessary.

**Comment by RandellDawson** [comment]
@moT01 @Sky020  If you wanted to make sure the correct CSS was within the `style` element, you could do:
```
const $styleElem = $('style'); assert($("img").width() < 200 && $styleElem && $styleElem.html().match(/\.smaller-image\s*{\s*width\s*:\s*100px\s*(;\s*}|})/i));
```
but I am fine with the current solution as close enough.

**Review by RandellDawson — APPROVED** [review]

**Review by ShaunSHamilton — APPROVED** [review]
LGTM 👍  I still could not test on Safari, but am happy to accept it as it does not include the lookbehinds.

Thanks, Tom.

**Pull request merged**
