### PR TITLE
migrate certain files in __mocks__/

### PR DESCRIPTION
**Pull request by KitaPDev**
Checklist:

- [x] I have read [freeCodeCamp's contribution guidelines](https://contribute.freecodecamp.org).
- [x] My pull request has a descriptive title (not a vague title like `Update index.md`)
- [x] My pull request targets the `main` branch of freeCodeCamp.
- [x] I have tested these changes either locally on my machine, or GitPod.

Is part of [#43778](https://github.com/freeCodeCamp/freeCodeCamp/issues/43778)

### CODE REVIEW

**Review by huyenltnguyen — COMMENTED** [review]
The changes look good to me. 

However, with `fileMock` and `styleMock` being converted to TypeScript, we need to update the file extension in the Jest config file. The change should be made to [this file](https://github.com/freeCodeCamp/freeCodeCamp/blob/main/jest.config.js) on line 5 and 9.

**Review by huyenltnguyen — APPROVED** [review]
LGTM 👍 

@KitaPDev Thank you for your contribution!

**Review by ojeytonwilliams — APPROVED** [review]
@KitaPDev Congrats on your first pull request (PR)! 🎉

Thank you for your contribution to the site! 👍
We're happy to accept these changes, and look forward to future contributions. 📝

**Comment by ieahleen** [comment]
in the other PR you had also changed the docs to reflect this change, that was a good change, the issue was the translated files

**Pull request merged**
