### PR TITLE
chore(tools): control Cypress installation

### LINKED ISSUE #38636: Skip Cypress installation locally?
Should we provide a way to skip installing cypress locally by default? This could save some bandwidth and time for users who do not want to install it / will not be working on e2e tests

### PR DESCRIPTION
**Pull request by ojeytonwilliams**
It's oddly difficult to configure `npm install`.  `npm set config` is lower priority than `.npmrc` and it only takes effect the *next* time you use `npm install`.  As a result you can't use `preinstall` to disable the installation and you can't overwrite config set in `.npmrc` via `npm config`.

However, environment variables that are passed to the process supersede  `.npmrc`, which is why I went with spawn a new process with the desired variable.

Closes #38636

### CODE REVIEW

**Comment by ojeytonwilliams** [comment]
@raisedadead if we want to stop crash reports going to Cypress, we can, but it'll need to use `cross-env` for `cypress` and `cypress:run`.  It doesn't work on `precypress`.

**Comment by raisedadead** [comment]
> if we want to stop crash reports going to Cypress

Won't that be the case only where we have the CI env configured with the keys? Everywhere else it will just fail? Which is fine. Or I am missing something.

**Comment by ojeytonwilliams** [comment]
Sounds like they get error reports when Cypress itself crashes, so I think it'll send them regardless of keys, but I'm not sure.   The docs are [here](https://docs.cypress.io/guides/getting-started/installing-cypress.html#Opt-out-of-sending-exception-data-to-Cypress) if you want to take a look.

**Comment by raisedadead** [comment]
A quick look tells me this is mostly for analytics for their product? IDK to be honest, lets give this a go as is, unless you have any more changes to the PR.

**Comment by ojeytonwilliams** [comment]
I think so, too. And, yes, I'm happy with the PR.

**Review by raisedadead — APPROVED** [review]

**Pull request merged**
