### PR TITLE
chore: typescript migration of components/settings/Honesty.test.js

### PR DESCRIPTION
**Pull request by matheuspor**
Checklist:

- [x] I have read [freeCodeCamp's contribution guidelines](https://contribute.freecodecamp.org).
- [x] My pull request has a descriptive title (not a vague title like `Update index.md`)
- [x] My pull request targets the `main` branch of freeCodeCamp.
- [x] I have tested these changes either locally on my machine, or GitPod.

Is part of [#43778](https://github.com/freeCodeCamp/freeCodeCamp/issues/43778)

***
Hey folks, this is my first contribution, any feedback is appreciated :+1:

### CODE REVIEW

**Comment by ojeytonwilliams** [comment]
Hi @matheuspor thanks for taking this on. The tests are failing at the moment, so could you update the snapshot?  `npm run test:source -- -u` should do the trick.

**Comment by matheuspor** [comment]
Hi @ojeytonwilliams! Thanks for the reply, I think the snapshot is updated now.

**Review by ojeytonwilliams — APPROVED** [review]
Perfect, thanks! LGTM 👍

**Review by naomi-lgbt — APPROVED** [review]
This should be good to go.

**Comment by nhcarrigan** [comment]
Congrats on your first pull request (PR)! 🎉

Thank you for your contribution to the page! 👍
We are happy to accept these changes and look forward to future contributions. 📝

**Pull request merged**
