### PR TITLE
Add test to profile lookup challenge

### LINKED ISSUE #10718: Profile lookup passes invalid code.
#### Challenge Name

Profile Lookup
#### Issue Description

The test for no such property passes even when the code does check firstName value.
Because the test for no such property uses the first contact in the array the test will 
pass even if the code does not check for matching first name
#### Browser Information

Chrome on windows - 52.0.2743.116
#### Your Code

This code passes but shouldn't per instructions

``` js
 function lookUpProfile(firstName, prop){
// Only change code below this line
for(var i = 0; i< contacts.length; i++){
   if(contacts[i].firstName == firstName && contacts[i].hasOwnProperty(prop)) {
      return contacts[i][prop];
    }
   if(contacts[i].hasOwnProperty(prop) === false) {
       return "No such property";
   }
}

return "No such contact";
// Only change code above this line
}


```

### PR DESCRIPTION
**Pull request by tearingItUp786**
#### Pre-Submission Checklist

- [x] Your pull request targets the `staging` branch of FreeCodeCamp.
- [x] Branch starts with either `fix/`, `feature/`, or `translate/` (e.g. `fix/signin-issue`)
- [x] You have only one commit (if not, [squash](http://forum.freecodecamp.com/t/how-to-squash-multiple-commits-into-one-with-git/13231) them into one commit).
- [x] All new and existing tests pass the command `npm test`. Use `git commit --amend` to amend any fixes.

#### Type of Change

- [x] Small bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds new functionality)
- [ ] Breaking change (fix or feature that would change existing functionality)
- [ ] Add new translation (feature adding new translations)

#### Checklist:

- [x] Tested changes locally.
- [x] Closes currently open issue (replace XXXX with an issue no): Closes #10718

#### Description

Added another test to profile lookup challenge. The code shared in the issue generated "No such property" but should have produced a "No such contact" in the case of a non present contact with a non present property.

### CODE REVIEW

**Review by systimotic — APPROVED** [review]
# LGTM 👍 
I paired with Taran to take this on, so I would appreciate another moderator looking at this as well 🙂

**Comment by Bouncey** [comment]
Thanks for contributing @tearingItUp786 :tada:

**Comment by systimotic** [comment]
Hi @sjames1958gm! I think you may have misread the changes here.
The test case checking the `profileLookup("Bob", "number")` should return "No such contact" was left intact. This test checks whether the message is returned when the property does exist, but the contact doesn't.
A new test case was added, `profileLookup("Bob", "potato")`. This test case functions the same as the one you suggested. We used "potato" instead of "email" to make it easy to see this is not a property that exist on the object.
This new test makes it so your example code provided in the issue no longer passes, but the proper solution still does.
If you think this change is otherwise incorrect, I'd love to hear!

Have a great day!

**Comment by sjames1958gm** [comment]
I missed the second change - my bad.

**Comment by systimotic** [comment]
@sjames1958gm No worries, I'm glad you're on top of things and checking out the fix!

**Pull request merged**
