### PR TITLE
chore: remove guide

### PR DESCRIPTION
**Pull request by raisedadead**
>  Good bye guide. Your new location is: https://github.com/freeCodeCamp/guide/tree/archive-articles-2019

### CODE REVIEW

**Comment by raisedadead** [comment]
This will not reduce the size of the repo per say. I am going to see if git filter -branch can come to our help later.

**Comment by raisedadead** [comment]
I am not sure, if writing the entire repo history is a very good idea. But here is what I am doing now that the Guide has been yanked.

```sh
~/DEV/freeCodeCamp master
❯ git count-objects -v
count: 230
size: 1296
in-pack: 233789
packs: 1
size-pack: 127107
prune-packable: 0
garbage: 0
size-garbage: 0

~/DEV/freeCodeCamp master
❯ git filter-branch --index-filter 'git rm --cached --ignore-unmatch guide/**/*' -- --all
Rewrite 6fdf5c61a7a6ec88053cfcf6e9195160b5071e1e (8592/24762) (652 seconds passed, remaining 1227 predicted)
```

I will next verify if the size-pack has indeed reduced. If yes, then it means a force push on all the branches. Which also means ⚠️ broken PRs ⚠️ and out of sync forks?

**Comment by lynxlynxlynx** [comment]
The guire repo README and/or https://github.com/freeCodeCamp/guide landing need to be updated as well. Now they're sending readers in a void, back to the main repo that has nothing.

**Comment by raisedadead** [comment]
I know, the removal of the documentation on contributing is also temporary. @RandellDawson has been working on some of the guidelines about how to contribute on the forum.

@RandellDawson I would love if you could share whatever progress you have made on the relevant issue thread. We could take it from there, (because you are on a vacation, in a few days)?

Thanks.

**Comment by RandellDawson** [comment]
See my draft PR #36735 for an update on a WIP of the new guidelines.

**Pull request merged**
