### PR TITLE
Cleanup Code Template For Word Blanks

### PR DESCRIPTION
**Pull request by jonathanihm**
Fix for #15137, placement of results variable moved inside comments to be more helpful and intuitive for newcomers.

### CODE REVIEW

**Review by nehatrajan — APPROVED** [review]

**Comment by JBallin** [comment]
I propose to reject and close both this PR #15142 and it's corresponding Issue #15137.

I've provided my reasons why in the issue.

**Review by raisedadead — APPROVED** [review]
#### :sparkles: :sparkles: **LGTM.** :sparkles: :sparkles: 

Thanks @jonathanihm !

And congrats on your first contribution freeCodeCamp! ✨ ✨ ✨

**Comment by raisedadead** [comment]
@jonathanihm just a tip, it would be great if you fill up the PR template which is a just checklist for moderators to know if the contributor got everything verified.

Thanks, and please keep contributing.

**Comment by jonathanihm** [comment]
Thanks @raisedadead,

I will do better on future PRs!  I wil do what I can :-)

**Pull request merged**
