### PR TITLE
Correcting a spelling mistake

### PR DESCRIPTION
**Pull request by Chandel13**
- [x] I have read [freeCodeCamp's contribution guidelines](https://github.com/freeCodeCamp/freeCodeCamp/blob/master/CONTRIBUTING.md).
- [x] My pull request has a descriptive title (not a vague title like `Update index.md`)
- [x] My pull request targets the `master` branch of freeCodeCamp.
- [x] None of my changes are plagiarized from another source without proper attribution.
- [x] My article does not contain shortened URLs or affiliate links.

If your pull request closes a GitHub issue, replace the XXXXX below with the issue number.

Closes #XXXXX

### CODE REVIEW

**Comment by tbushman** [comment]
@SAKSHI-CHANDEL Please provide reasoning for removing the C++ example. We may only be able to accept the spelling correction in this case.

**Comment by SAKSHI-CHANDEL** [comment]
@tbushman The code had been repeated, but it got fixed now. Please accept the other commits.

**Comment by tbushman** [comment]
@SAKSHI-CHANDEL OK I see that now. Thank you for the info. I'll get this merged soon!

**Comment by tbushman** [comment]
@raisedadead I'm having trouble rebasing this, sorry.

**Comment by raisedadead** [comment]
Hi @SAKSHI-CHANDEL @tbushman 

I can help with this. Can you confirm which commits need to go in? You can post screenshots from the 
https://github.com/freeCodeCamp/freeCodeCamp/pull/19845/files tab?

**Comment by tbushman** [comment]
@raisedadead All of the commits. You can omit mine if that's the problem because I was only trying to match the style of the other code snippets.

**Comment by tbushman** [comment]
@raisedadead WOW Thank you!!  
@SAKSHI-CHANDEL Thank you for your work on this! Congratulations on your first merged PR for this repository! LGTM!

**Pull request merged**
