### PR TITLE
feat(full-stack): Full Stack Certification

### LINKED ISSUE #17258: Add option to claim "Full Stack Developer Certification" to options
We want to create one more certification view - the "Full Stack Developer Certification."

This can be claimed with a single click from the settings interface upon having already earned the following certifications. The button for claiming this should be below the new certifications and above the legacy certifications. And should have the following text:

Once you've earned the following freeCodeCamp certifications, you'll be able to claim this The Full Stack Developer Certification:
- Responsive Web Design
- Algorithms and Data Structures
- Front End Libraries
- Data Visualization
- APIs and Microservices
- Information Security and Quality Assurance

[ Claim your Full Stack Developer Certification ]

### PR DESCRIPTION
**Pull request by NitronR**
#### Pre-Submission Checklist

- [x] Your pull request targets the `staging` branch of freeCodeCamp.
- [ ] Branch starts with either `fix/`, `feature/`, or `translate/` (e.g. `fix/signin-issue`)
- [ ] You have only one commit (if not, [squash](http://forum.freecodecamp.org/t/how-to-squash-multiple-commits-into-one-with-git/13231) them into one commit).
- [x] All new and existing tests pass the command `npm test`. Use `git commit --amend` to amend any fixes.

#### Type of Change

- [ ] Small bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds new functionality)
- [ ] Breaking change (fix or feature that would change existing functionality)
- [ ] Add new translation (feature adding new translations)

#### Checklist:

- [x] Tested changes locally.
- [x] Addressed currently open issue (replace XXXXX with an issue no in next line)

Closes #17258

#### Description

Added the Full Stack Certification section at the required position. Tested the implementation by claiming required certifications and finally claiming the Full Stack Certification.

### CODE REVIEW

**Comment by QuincyLarson** [comment]
@NitronR This is off to a good start.

I'm a bit confused by the "legacyFullStack" - there is no legacy full stack certification. We have never issued one of these before, so no need to account for them. Instead, we should just call the certification the "Full Stack Development Certification" and should use variable names accordingly.

**Comment by NitronR** [comment]
@QuincyLarson I added that because there were some instances of it in the code. I will remove those now. Thanks for the clarification!!

**Comment by NitronR** [comment]
Have removed the legacy full-stack code. Will fix code to pass the Travis build now.

**Review by sittirac1234 — APPROVED** [review]

**Comment by QuincyLarson** [comment]
@raisedadead since you're the most knowledgable person on how the current certifications work, could you help QA this and make the necessary changes to get this merged?

**Comment by Angiecnich** [comment]
How do I use this ???

**Comment by NitronR** [comment]
@Angiecnich You can setup a local freeCodeCamp environment using my forked repository and switching to the feat/full-stack branch. Then you can login to the local web application and then claim the 6 certifications. You can then claim the Full Stack Certification and view it.

**Comment by raisedadead** [comment]
Hi @NitronR can you beat me to rebasing this, please? If not, do not worry, I'll do it by tonight.

**Review by raisedadead — COMMENTED** [review]
LGTM

**Pull request merged**
