### PR TITLE
fix: enlarges console pane for project steps

### PR DESCRIPTION
**Pull request by ojeytonwilliams**
Checklist:

- [x] I have read [freeCodeCamp's contribution guidelines](https://contribute.freecodecamp.org).
- [x] My pull request has a descriptive title (not a vague title like `Update index.md`)
- [x] My pull request targets the `main` branch of freeCodeCamp.
- [x] I have tested these changes either locally on my machine, or GitPod.

Closes #XXXXX

### CODE REVIEW

**Comment by ShaunSHamilton** [comment]
This might be fine - I have no preference. But the issue I was seeing with the appearance of the console was it was clipping into/behind the footer.

**Comment by ojeytonwilliams** [comment]
Oh, right, I wasn't sure.

Anyways, it depends on the viewport size, but I think it's better to be slightly bigger. Since it's hidden by default.

**Comment by ShaunSHamilton** [comment]
Again, do you actually suggest this change, because this is still what I see (on this branch):
image

**Comment by ojeytonwilliams** [comment]
This branch doesn't have the footer fix, though. It should look good once that's in.

**Review by ShaunSHamilton — APPROVED** [review]
Sure 👍

**Review by ahmaxed — APPROVED** [review]

**Pull request merged**
