### PR TITLE
Remove user story from Twitch.tv project (backup/master)

### LINKED ISSUE #5321: Content Security Policy Disables Browser Sync
Only effects the autorefresh from browser-sync when running FCC in a local dev environment.

@BerkeleyTrue Not sure if you feel this is important enough to add an exception to the security policy for it or if you'd rather just ditch the feature.

a_map_to_learn_to_code_and_become_a_software_engineer___free_code_camp

### LINKED ISSUE #15321: Example given doesn't follow one of the user stories
Challenge [Use the Twitchtv JSON API](https://www.freecodecamp.com/challenges/use-the-twitchtv-json-api) has an issue.
User Agent is: <code>Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/59.0.3071.86 Safari/537.36</code>.

I added "brunofin", a user that doesn't exist and it says that it's offline. data.stream === undefined doesn't work anymore.

### PR DESCRIPTION
**Pull request by padulam**
#### Pre-Submission Checklist

- [ ] Your pull request targets the `staging` branch of freeCodeCamp.
- [x] Branch starts with either `fix/`, `feature/`, or `translate/` (e.g. `fix/signin-issue`)
- [x] You have only one commit (if not, [squash](http://forum.freecodecamp.com/t/how-to-squash-multiple-commits-into-one-with-git/13231) them into one commit).
- [x] All new and existing tests pass the command `npm test`. Use `git commit --amend` to amend any fixes.

#### Type of Change

- [x] Small bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds new functionality)
- [ ] Breaking change (fix or feature that would change existing functionality)
- [ ] Add new translation (feature adding new translations)

#### Checklist:

- [x] Tested changes locally.
- [x] Closes currently open issue (replace XXXX with an issue no): Closes #15321

#### Description

Removes user story to handle inactive/closed accounts from the Twitch.tv project. Removed the user story in all translations of the project.

### CODE REVIEW

**Review by raisedadead — COMMENTED** [review]
#### :sparkles: :sparkles: **LGTM.** :sparkles: :sparkles: 

Thanks @padulam

**Comment by raisedadead** [comment]
@padulam sorry about this. But could you please resolve the merge conflicts, please hit us up int [Contributors Chat room](https://gitter.im/FreeCodeCamp/Contributors), should you need any assistance.

**Comment by padulam** [comment]
@raisedadead No worries. Just submitted the updated pull request.

**Comment by raisedadead** [comment]
@padulam awesome, thanks.

**Pull request merged**
