### PR TITLE
Increment or Decrement Operator instruction modification

### PR DESCRIPTION
**Pull request by abhisekp**
**Waypoint: Increment a Number with Javascript**
_minor modification request_ 

> [](http://i.imgur.com/Ex7qgP6.png)

---

**Waypoint: Decrement a Number with Javascript**
_minor modification request_

> [](http://i.imgur.com/JOG1efy.png)

cc: @SaintPeter

> Arising from the comment by @Mr-Kumar-Abhishek https://github.com/FreeCodeCamp/FreeCodeCamp/issues/5632#issuecomment-168168475

Follow the discussion here :point_right: [**`[FreeCodeCamp/CurriculumDevelopment]`**](https://gitter.im/FreeCodeCamp/CurriculumDevelopment?at=5686a13566a282570f90520f)

### CODE REVIEW

**Comment by ltegman** [comment]
Waiting to hear @SaintPeter's thoughts, but I've been convinced. Don't see a reason this needs to be two separate commits though.

**Comment by SaintPeter** [comment]
I think we need to include some sort of explanation of what the difference is between the two.  I think just throwing it out there without explanation is going to cause confusion.

**Comment by ltegman** [comment]
@abhisekp Any plans to implement @SaintPeter's suggestions? If not I'm going to close this this PR since explaining the difference (while subtle) is quite important.

**Comment by SaintPeter** [comment]
I have spoken with @abhisekp and here is what we're going to do:
1) Close this PR for the moment
2) Modify the descriptions to name the pre/post operators.
3) Come up with a 3rd Waypoint that talks about pre and post increment/decrement

**Pull request closed without merging**
