### PR TITLE
fix(client): replace notifications with toasts

### PR DESCRIPTION
**Pull request by raisedadead**

### CODE REVIEW

**Comment by raisedadead** [comment]
demo

**Comment by ojeytonwilliams** [comment]
I noticed that the reset message appears three times:
ResetProgress

I don't think this PR created the bug, just that now all messages appear on the screen, you can see it.

**Comment by raisedadead** [comment]
Yeah, this is really something I was throwing in together because I hate the way we have our current notifications. More of a spike. :)

We'll probably never land this.

**Comment by raisedadead** [comment]
> I don't think this PR created the bug, just that now all messages appear on the screen, you can see it.

Regardless of what this PR intended. There is a memory leak somewhere, I believe. Worth investigating.

**Pull request closed without merging**
