### PR TITLE
add more specific tests for username regex challenge

### LINKED ISSUE #17733: Wrong Accepted Answer in Regular Expressions: Restrict Possible Usernames
#### Problem:
The following code was accepted as a resolution of Regular Expressions: Restrict Possible Usernames
`let userCheck = /[a-zA-Z][a-zA-Z][a-zA-Z]+[0-9]*$/; // Change this line` 
Obs.: no modifications were applied to the other lines.

This code works for the test cases but it's not the correct answer to the challenge of Restrict Possible Usernames, due to the fact that usernames have to be at least two characters long.
After submitting this answer I realized how wrong it was, it should be (or some variation of):
`let userCheck = /[a-zA-Z][a-zA-Z]+[0-9]*$/;`

#### Link to the page with the problem
Page: [Restrict Possible Usernames][1]

#### Browser and operating system:
* Browser Name: Chrome
* Browser Version: 67.0.3396.99 (Official Build) (64-bit)
* Operating System: Windows 10

[1]: https://learn.freecodecamp.org/javascript-algorithms-and-data-structures/regular-expressions/restrict-possible-usernames

### PR DESCRIPTION
**Pull request by thornjad**
Since the instructions state that usernames can be two characters long, but if
so it must be alphabetic, we should test for these conditions.

These new tests should also be added to the translated versions, but I don't
have the knowledge for that.

- [x] I have read [freeCodeCamp's contribution guidelines](https://github.com/freeCodeCamp/freeCodeCamp/blob/master/CONTRIBUTING.md).
- [x] My pull request has a descriptive title (not a vague title like `Update index.md`)
- [x] My pull request targets the `master` branch of freeCodeCamp.
- [x] None of my changes are plagiarized from another source without proper attribution.
- [x] My article does not contain shortened URLs or affiliate links.

If your pull request closes a GitHub issue, replace the XXXXX below with the issue number.

Closes #17733

### CODE REVIEW

**Comment by nikrb** [comment]
@huyenltnguyen successfully tested this locally, though `npm run test:curriculum` fails

**Comment by huyenltnguyen** [comment]
@nikrb Thanks for letting me know.

I haven't had a chance to set up fCC locally so I can't test this PR. However, since this PR changes the curriculum code, I think @scissorsneedfoodtoo is the right person to QA it.

**Comment by scissorsneedfoodtoo** [comment]
@huyenltnguyen, thanks for the heads up! Will check this out once I get local development running.

**Comment by scissorsneedfoodtoo** [comment]
@thornjad, unfortunately it seems like we can't trigger the Travis CI build needed to merge your additional tests. I believe this is because your changes are coming from the master branch of your fCC fork. I'll have to close this, but please feel free to make another PR with your changes! I've edited your tests slightly to be more in line with the current format:

```
  - text: Your regex should not match <code>J6</code>
    testString: assert(!userCheck.test("J6"), 'Your regex should not match <code>J6</code>');
  - text: Your regex should match <code>Jo</code>
    testString: assert(userCheck.test("Jo"), 'Your regex should match <code>Jo</code>');
```

Please let us know when you can make another PR and someone will be happy to review it. Thanks!

**Pull request closed without merging**
