### PR TITLE
chore(client): disable sentry on client

### PR DESCRIPTION
**Pull request by ShaunSHamilton**
Checklist:

- [x] I have read [freeCodeCamp's contribution guidelines](https://contribute.freecodecamp.org).
- [x] My pull request has a descriptive title (not a vague title like `Update index.md`)
- [x] My pull request targets the `main` branch of freeCodeCamp.
- [x] I have tested these changes either locally on my machine, or GitPod.

Disables sentry, until we can resolve the chunk errors

### CODE REVIEW

**Review by raisedadead — APPROVED** [review]

**Review by raisedadead — CHANGES_REQUESTED** [review]
Ah - hold on. Why can't we disable (remove the key) this from the builds and still have all this code in place?

**Comment by ShaunSHamilton** [comment]
@raisedadead That would be too reasonable.

Do you want to keep around the bloat, though? (e.g. `@sentry/gatsby`)

**Comment by raisedadead** [comment]
> Do you want to keep around the bloat, though?

Considering we want to resolve the chunk errors after all. P.S, Oliver is working on something that I can't disclose yet. But having the logic around (even if you want to comment it out) should help him.

**Comment by raisedadead** [comment]
Let's leave it to @ojeytonwilliams 😄

**Pull request closed without merging**
