### PR TITLE
Improve test on jQuery disable challenge

### LINKED ISSUE #10410: Disable an Element Using JQuery passes without JQuery
#### Challenge Name
https://www.freecodecamp.com/challenges/disable-an-element-using-jquery

#### Issue Description
Test passes with only HTML changes and no JQuery.

#### Browser Information
* Browser Name, Version: Chrome, Version 52.0.2743.116 m (64-bit)
* Operating System: Win 10
* Mobile, Desktop, or Tablet: Desktop

#### Screenshot
jquery error1

jquery error2

### PR DESCRIPTION
**Pull request by dhcodes**
#### Pre-Submission Checklist

- [X] Your pull request targets the `staging` branch of FreeCodeCamp.
- [X] Branch starts with either `fix/`, `feature/`, or `translate/` (e.g. `fix/signin-issue`)
- [X] You have only one commit (if not, [squash](http://forum.freecodecamp.com/t/how-to-squash-multiple-commits-into-one-with-git/13231) them into one commit).
- [X] All new and existing tests pass the command `npm run test-challenges`. Use `git commit --amend` to amend any fixes.
#### Type of Change

- [X] Small bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds new functionality)
- [ ] Breaking change (fix or feature that would change existing functionality)
- [ ] Add new translation (feature adding new translations)
#### Checklist:

- [X] Tested changes locally.
- [X] Closes currently open issue (replace XXXX with an issue no): Closes #10410 
#### Description

Updated the third test to look for `disabled\s?=` whereas before it looked for `disabled>`

### CODE REVIEW

**Comment by ltegman** [comment]
Thanks for the PR @dhcodes. One thing about this approach is that it will now no longer catch cases where someone simply uses `disabled` without an `=` (which is valid syntax for boolean properties in HTML). I can also say after seeing a lot of test related bugs that you should always account for more than 1 character of whitespace. Perhaps the following regex might be more flexible?
```
disabled[^<]*>
```
There might be some edge cases I missed, but basically this will look for any instance of `disabled` inside the open and close bracket of an HTML tag.

**Comment by dhcodes** [comment]
@ltegman good idea, I hadn't considered that. I'll update this today (hopefully).

**Comment by dhcodes** [comment]
Okay. Sorry if you got notifications for all that @ltegman. Should be good to go now. Sorry it took so long. I need even more git practice apparently.

**Comment by ltegman** [comment]
Not a problem -- only way you get good at git is by making mistakes with git! 😆  Looks good! 👍

**Pull request merged**
