### PR TITLE
update the number of articles for Chinese publication searchbar

### PR DESCRIPTION
**Pull request by miyaliu666**
Checklist:

- [x] I have read [freeCodeCamp's contribution guidelines](https://contribute.freecodecamp.org).
- [x] My pull request has a descriptive title (not a vague title like `Update index.md`)
- [x] My pull request targets the `main` branch of freeCodeCamp.
- [x] I have tested these changes either locally on my machine, or GitPod.

### CODE REVIEW

**Comment by miyaliu666** [comment]
@sidemt Thanks for reminding me. The traditional Chinese should be updated automatically with the simple Chinese version. Now I'm confused about camperbot's reply above. It seems I shouldn't make such a change here. I asked Kris about this just now.

**Comment by ojeytonwilliams** [comment]
Fair enough. So we just handle it by letting proofreaders/translators know that this is one of the few special cases?

**Comment by nhcarrigan** [comment]
Precisely. If we were to change it through GitHub, Camperbot would overwrite it in the next download anyway.

**Comment by miyaliu666** [comment]
Thanks for your help! @nhcarrigan @ojeytonwilliams

**Pull request closed without merging**
