### PR TITLE
feat: edit 2nd test description for clarity

### PR DESCRIPTION
**Pull request by mchsch**
current description logically fits, yet fails this solution: myVar = ++myVar;

Checklist:

- [x] I have read [freeCodeCamp's contribution guidelines](https://contribute.freecodecamp.org).
- [x] My pull request has a descriptive title (not a vague title like `Update index.md`)
- [x] My pull request targets the `master` branch of freeCodeCamp.
- [x] All the files I changed are in the same world language, for example: only English changes, or only Chinese changes, etc.

Closes #XXXXX

### CODE REVIEW

**Comment by Sky020** [comment]
Just to add information: [Here](https://www.freecodecamp.org/forum/t/confusing-test-description/378187) is the discussion of this on the forum.

**Review by ShaunSHamilton — CHANGES_REQUESTED** [review]
<s>Ignore this</s>

**Review by ShaunSHamilton — APPROVED** [review]
LGTM 👍

**Review by moT01 — APPROVED** [review]
LGTM @michaelsndr 🎉 Congratulations on your first contribution to freeCodeCamp 🎉 

For future reference, it's best to create a branch for your PR and not make changes to your own master branch. See [here in the docs](https://github.com/freeCodeCamp/freeCodeCamp/blob/master/docs/how-to-setup-freecodecamp-locally.md#making-changes-locally)

**Comment by michaelsndr** [comment]
@moT01 Cool. Thanks for the link!

**Pull request merged**
