### PR TITLE
fix: fixed security hall of fame list hyperlink

### LINKED ISSUE #50907: Fix Security Hall of Fame hyperlink
### Describe the Issue

The 3rd point within the [Guidelines](https://github.com/freeCodeCamp/freeCodeCamp/security#guidelines) subsection of [freeCodeCamp's Security Policy](https://github.com/freeCodeCamp/freeCodeCamp/security), contains a hyperlink to the Hall of Fame list which seems to be broken at the moment because when the user clicks on that hyperlink, they end up with a [404 - page not found](https://github.com/freeCodeCamp/freeCodeCamp/blob/main/security-hall-of-fame.md) error.

> 3. While we do not offer any bounties or swags at the moment, we'll be happy to list your name in our [Hall of Fame](https://github.com/freeCodeCamp/freeCodeCamp/blob/main/security-hall-of-fame.md) list, provided the reports are not low-effort.

### Affected Page

https://github.com/freeCodeCamp/freeCodeCamp/security

### Steps to Reproduce

In order to reproduce the error, the user can simply click the **Hall of Fame** hyperlink within the 3rd point of the [Guidelines](https://github.com/freeCodeCamp/freeCodeCamp/security#guidelines) subsection of [freeCodeCamp's Security Policy](https://github.com/freeCodeCamp/freeCodeCamp/security):

> 3. While we do not offer any bounties or swags at the moment, we'll be happy to list your name in our [Hall of Fame](https://github.com/freeCodeCamp/freeCodeCamp/blob/main/security-hall-of-fame.md) list, provided the reports are not low-effort.

### Recommended fix or suggestions

The Hall of Fame hyperlink should be configured to redirect the users to the following link:

> (/docs/security-hall-of-fame.md) i.e. https://github.com/freeCodeCamp/freeCodeCamp/blob/main/docs/security-hall-of-fame.md

### PR DESCRIPTION
**Pull request by anmxls**
Checklist:

- [x] I have read and followed the [contribution guidelines](https://contribute.freecodecamp.org).
- [x] I have read and followed the [how to open a pull request guide](https://contribute.freecodecamp.org/#/how-to-open-a-pull-request).
- [x] My pull request targets the `main` branch of freeCodeCamp.
- [x] I have tested these changes either locally on my machine, or GitPod.

Closes #50907

### CODE REVIEW

**Comment by moT01** [comment]
I think @gikf is correct with the comment on the issue @AnonSar. I opened this PR and clicked on the hall of fame link in the docs and got a 404:
Screen Shot 2023-07-06 at 2 52 06 PM

So we shouldn't do this. We could change it to https://contribute.freecodecamp.org/#/security-hall-of-fame which should make both links go to the correct place - the down side is that the link in the docs opens the hall of fame in a new tab. I'm not sure which is better. I think I would be fine changing it to that - it's either that or leave it how it is I think. So you could probably change it to that on this PR and we can let reviewers discuss if we want it like that or not.

**Comment by naomi-lgbt** [comment]
I would leave it how it is. I'd rather have a broken link on the GitHub view than have it break the i18n links on the hosted docs site.

**Comment by moT01** [comment]
Yea, good call @naomi-lgbt - I didn't think of that. I would vote to leave it as-is then as well.

**Comment by moT01** [comment]
I changed this to blocked while we discuss a solution on the issue.

**Comment by raisedadead** [comment]
The behavior is intentional. The docs are not supposed to be used via GitHub. They have special formating and markup.

**Pull request closed without merging**
