### PR TITLE
Solution added to exercise 'Use the s tag to strikethrough text '

### PR DESCRIPTION
**Pull request by luane-aquino**
- [x] I have read [freeCodeCamp's contribution guidelines](https://github.com/freeCodeCamp/freeCodeCamp/blob/master/CONTRIBUTING.md).
- [x] My pull request has a descriptive title (not a vague title like `Update index.md`)
- [x] My pull request targets the `master` branch of freeCodeCamp.
- [x] None of my changes are plagiarized from another source without proper attribution.
- [x] My article does not contain shortened URLs or affiliate links.

Closes #XXXXX

### CODE REVIEW

**Comment by luane91** [comment]
Solution for exercise of applied visual design

**Review by RandellDawson — CHANGES_REQUESTED** [review]
You must add the full solution and not just the line which needs to be changed.

**Comment by ezioda004** [comment]
@Bouncey @ValeraS Can you clarify if we need the challenge seed's code too in the solution? Example: in this one the challenges seed code isnt used but still passes the CI but I was under the impression that the CI checks the "solution" against the tests to verify.

**Comment by ValeraS** [comment]
IMO, using the seed code in the solution ensures that Campers can pass tests by following challenge instructions.

**Comment by Bouncey** [comment]
OK, @luane91, could you please edit this PR and copy the seed code into the solution, then make the required changes. Just like it would be for a real challenge. Many thanks

**Review by Bouncey — APPROVED** [review]
Great Work @luane91!!

**Comment by Bouncey** [comment]
Congratulations on your first accepted Pull Request for freeCodeCamp!!

Thank you!!!

**Comment by Bouncey** [comment]
Congratulations on your first accepted Pull Request for freeCodeCamp!!

Thank you!!!

**Comment by luane91** [comment]
> Congratulations on your first accepted Pull Request for freeCodeCamp!!
> 
> Thank you!!!

Thank you so much! I am happy to be part of this community

**Pull request merged**
