### PR TITLE
chore: upgrade husky to v9

### PR DESCRIPTION
**Pull request by Sembauke**
Checklist:

- [x] I have read and followed the [contribution guidelines](https://contribute.freecodecamp.org).
- [x] I have read and followed the [how to open a pull request guide](https://contribute.freecodecamp.org/#/how-to-open-a-pull-request).
- [x] My pull request targets the `main` branch of freeCodeCamp.
- [x] I have tested these changes either locally on my machine, or GitPod.

Closes #XXXXX

### CODE REVIEW

**Review by raisedadead — APPROVED** [review]

**Review by ojeytonwilliams — CHANGES_REQUESTED** [review]
This doesn't look quite right, @Sembauke. husky has zero dependencies, so the pnpm-lock changes should be tiny (just a couple of lines that refer specifically to husky).

I'm not sure why this has happened, but just to rule things out: which pnpm version are you using?

**Comment by Sembauke** [comment]
@ojeytonwilliams I am using v8.15.4

**Comment by raisedadead** [comment]
> ... so the pnpm-lock changes should be tiny (just a couple of lines that refer specifically to husky)

Not quite, `pnpm` will try to "normalize" lock-files when it can. Its a common and known behavior.

**Comment by Sembauke** [comment]
> Not quite, `pnpm` will try to "normalize" lock-files when it can. Its a common and known behavior.

Could you cite a source for this @raisedadead ?

**Comment by raisedadead** [comment]
Read somewhere once in their issues list. If you have time feel free to go through them.

**Comment by ojeytonwilliams** [comment]
Alrighty, Tom tried `pnpm add`ing this and ended up with essentially the same diff as the PR, so it seems like it's something that Macs do. Unclear why. It doesn't seem like it's doing any harm, though.

**Review by ojeytonwilliams — APPROVED** [review]

**Pull request merged**
