### PR TITLE
Update Challenge.jsx issue #16239 

### LINKED ISSUE #16239: Remove * required code from map
learn_to_code___freecodecamp

Note that the names of these projects have a * behind them. That means they are required.

We no longer need this logic, since each certificate consistently requires completion of its 5 required projects. So we want to get rid of: 
- [ ] the "isRequired" property in the challenge seed files, and 
- [ ] the logic that renders these * on the map

### PR DESCRIPTION
**Pull request by Jahrkor**
#### Pre-Submission Checklist

- [x] Your pull request targets the `staging` branch of freeCodeCamp.
- [ ] Branch starts with either `fix/`, `feature/`, or `translate/` (e.g. `fix/signin-issue`)
- [ ] You have only one commit (if not, [squash](http://forum.freecodecamp.org/t/how-to-squash-multiple-commits-into-one-with-git/13231) them into one commit).
- [ ] All new and existing tests pass the command `npm test`. Use `git commit --amend` to amend any fixes.

#### Type of Change

- [ ] Small bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds new functionality)
- [x] Breaking change (fix or feature that would change existing functionality)
- [ ] Add new translation (feature adding new translations)

#### Checklist:

- [ ] Tested changes locally.
- [x] Addressed currently open issue (replace 16239 with an issue no in next line)

Closes #16239

#### Description

Remove * required code from map #16239 
Removing the "isRequired" property in the challenge seed files and the logic that renders these * on the map.

### CODE REVIEW

**Comment by QuincyLarson** [comment]
@Jahrkor Thanks for your PR. It looks like @camperbot automatically closed it because you didn't create a separate branch. Would you be interested in opening another PR? This is still an outstanding issue.

**Comment by Jahrkor** [comment]
yes i will open a new PR

**Comment by Jahrkor** [comment]
@QuincyLarson i'm having issues trying to make the new PR, but i'm still workingon it

**Comment by QuincyLarson** [comment]
@Jahrkor Thanks for your patience - were you able to make your new PR?

**Pull request closed without merging**
