### PR TITLE
Changes order of padding, border, margin in introductory sentence.

### PR DESCRIPTION
**Pull request by bycdiaz**
Checklist:

- [X ] I have read [freeCodeCamp's contribution guidelines](https://contribute.freecodecamp.org).
- [ X] My pull request has a descriptive title (not a vague title like `Update index.md`)
- [ X] My pull request targets the `master` branch of freeCodeCamp.
- [X ] All the files I changed are in the same world language, for example: only English changes, or only Chinese changes, etc.

Closes #XXXXX

Just a minor adjustment to the sentence that introduces padding, margin and border. When I think about the three, what helped me memorize them was thinking about what was inside and going outward. Perhaps trivial, but recalling them as padding, border, then margin could help establish that thinking for new learners.

### CODE REVIEW

**Review by lasjorg — APPROVED** [review]
Makes sense to me. Inner to outer (or outer to inner) and not the order it is now.

**Comment by lasjorg** [comment]
Side note: I'm wondering why the [box model](https://developer.mozilla.org/en-US/docs/Learn/CSS/Building_blocks/The_box_model) is never officially introduced in the curriculum? I would think having a challenge that shows the classic box model images would be useful.

**Comment by RandellDawson** [comment]
@lasjorg The project-based curriculum does introduce it

**Review by moT01 — APPROVED** [review]
LGTM 🎉 

I have blocked this for now. See the [pinned code freeze issue](https://github.com/freeCodeCamp/freeCodeCamp/issues/38308) - The PR can still be reviewed, just not merged at the moment.

**Review by moT01 — APPROVED** [review]
Congratulations on your first contribution to freeCodeCamp @bycdiaz 🎉

**Pull request merged**
