### PR TITLE
fix(client): migrate DonateCompletion to TypeScript

### PR DESCRIPTION
**Pull request by nicorr-05**
Checklist:

- [x] I have read [freeCodeCamp's contribution guidelines](https://contribute.freecodecamp.org). 
- [x] My pull request has a descriptive title (not a vague title like `Update index.md`) 
- [x] My pull request targets the `main` branch of freeCodeCamp. 
- [x] I have tested these changes either locally on my machine, or GitPod.

### CODE REVIEW

**Review by thecodingaviator — DISMISSED** [review]
I believe you'll need to remove the package and package-lock files and go with the .d.ts file route instead.
Also, I'm not sure whether we're doing away with the .displayNameproperty too. Some other contributor will have more on this.
I'll cc @ojeytonwilliams for more info.

**Comment by ojeytonwilliams** [comment]
It's totally fine to import type definitions from DefinitelyTyped.  If they don't exist we can always add our own, but I'd prefer if we imported them since they're already being maintained and updated.

**Comment by Nrestrepo05** [comment]
Hello! I'm trying to do what you asked for but I having some problems. I'll keep working on that!

**Comment by Nrestrepo05** [comment]
sorry, I think I should not be able to finish this task, can I close this or and try to contribute later?

**Review by naomi-lgbt — CHANGES_REQUESTED** [review]
Why are we deleting the package.json and package-lock.json files?

**Comment by thecodingaviator** [comment]
> Why are we deleting the package.json and package-lock.json files?

From what I understood at the time, I had asked for the changes to be removed from the PR not the files deleted entirely (although, my wording wasn’t the best). However, as I understand now, those changes were to be left there

**Comment by ShaunSHamilton** [comment]
Hey there,

Thank you for taking the time to contribute to the TypeScript migration. 

The main issue has been updated a lot over the last few days, and so we suggest you re-read it and update this pull request to match if you have the time.

The main goals for a PR are:
- [ ] Changing the filename from `PascalCase` to `kebab-case` and ensuring that the imports in code are all still valid.
- [x] Changing the file extension to .tsx (if a file has React JSX syntax)
- [x] Fixing as many TypeScript and Eslint errors as you can while refactoring the code.

If you need any assistance, please reach out in our [contributing chat room](https://chat.freecodecamp.org/channel/contributors).

**Pull request closed without merging**
