### PR TITLE
add `map` function to haskell section

### PR DESCRIPTION
**Pull request by german1608**
Add `map` function to haskell section of guide.freecodecamp.org

- [x] My pull request has a descriptive title (not a vague title like `Update index.md`)
- [x] I have read [freeCodeCamp's contribution guidelines](https://github.com/freeCodeCamp/freeCodeCamp/blob/master/CONTRIBUTING.md).
- [x] My pull request targets the `master` branch of freeCodeCamp.
- [x] None of my changes are plagiarized from another source without proper attribution.
- [x] My article does not contain shortened URLs or affiliate links.

If your pull request closes a GitHub issue, replace the XXXXX below with the issue number.

Closes #XXXXX

### CODE REVIEW

**Comment by RandellDawson** [comment]
Closed and Reopened this PR in an attempt to attempt to break out of the Travis build pending status.

**Comment by moT01** [comment]
Why is this part in there...
```
import Data.Char (toLower) # to get the toLower
map toLower "HELLO WORLD HASKELL RULEZ!"
-- "hello world haskell rulez!"
```
?

**Comment by german1608** [comment]
@moT01 I added it as an example of the `map` function.

**Review by QuincyLarson — APPROVED** [review]
@german1608 Excellent example. Thanks for adding this.

**Pull request merged**
