### PR TITLE
change node-uuid to uuid

### LINKED ISSUE #12272: Refactor node-uuid to uuid
Looks like `node-uuid` was renamed to `uuid` a while back and the `node-uuid` was left to stagnate. This should be a straight forward refactor. Make sure their have not been significant changes to the api.

Happy Coding!

### PR DESCRIPTION
**Pull request by dhcodes**
#### Pre-Submission Checklist

- [X] Your pull request targets the `staging` branch of FreeCodeCamp.
- [X] Branch starts with either `fix/`, `feature/`, or `translate/` (e.g. `fix/signin-issue`)
- [X] You have only one commit (if not, [squash](http://forum.freecodecamp.com/t/how-to-squash-multiple-commits-into-one-with-git/13231) them into one commit).
- [X] All new and existing tests pass the command `npm test`. Use `git commit --amend` to amend any fixes.

#### Type of Change

- [X] Small bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds new functionality)
- [ ] Breaking change (fix or feature that would change existing functionality)
- [ ] Add new translation (feature adding new translations)

#### Checklist:

- [X] Tested changes locally.
- [X] Closes currently open issue (replace XXXX with an issue no): Closes #12272

#### Description

Updated this and tested it with a short code snippet. Seems to work fine. Interestingly, the recommendation on the uuid readme.md to use `require('uuid/v4')` instead of `require('uuid')` doesn't seem to work so I left it as the latter. Also, `1.4.3` was not an acceptable version number for the package.json so I made it `^1.4.2`

### CODE REVIEW

**Comment by BerkeleyTrue** [comment]
This PR use the latest version of uuid.

**Comment by dhcodes** [comment]
@BerkeleyTrue what change should I make? Change `^1.4.2` to `1.4.2` ?

**Comment by BerkeleyTrue** [comment]
the latest version is 3.0.1 so `^1.4.2` to `^3.0.1`

You can see the latest version of a package using the `view` command and the `version` modifier of npm

`npm view uuid version` or `npm view uuid versions` to return a list of all the versions available.

You can also force npm to install and update the `package.json` with the latest version using the at tag

`npm install --save uuid@latest`

careful with the above as this will install betas or alphas if they are the latest for that package

**Comment by dhcodes** [comment]
Thanks. I wasn't sure if we should stick closer to the version listed in the past. Updated now.

**Pull request merged**
