### PR TITLE
fix(curriculum): typos in building a Dice Game Step 13

### LINKED ISSUE #55772: Typos in Building a Dice Game Step 13
## Description

There a some typos in step 13 of Building a Dice Game.

- In the description, there is a sentence with an extra period:
```diff
--- If not, it should update the last radio button to display a score of 0, with the correct attributes..
+++ If not, it should update the last radio button to display a score of 0, with the correct attributes.
```

- In the hints, the word "span" not being wrapped within backticks (there are two instances of this)
```diff
--- and set the third span to display the text
+++ and set the third `span` to display the text
```

## Affected page

https://www.freecodecamp.org/learn/javascript-algorithms-and-data-structures-v8/review-algorithmic-thinking-by-building-a-dice-game/step-13

### PR DESCRIPTION
**Pull request by AbdulMuqsit112**
Checklist:

- [x] I have read and followed the [contribution guidelines](https://contribute.freecodecamp.org).
- [x] I have read and followed the [how to open a pull request guide](https://contribute.freecodecamp.org/how-to-open-a-pull-request/).
- [x] My pull request targets the `main` branch of freeCodeCamp.
- [x] I have tested these changes either locally on my machine, or GitPod.

Closes #55772 

This Pr fixes the typos in building a Dice Game Step 13

**Affected page**

https://www.freecodecamp.org/learn/javascript-algorithms-and-data-structures-v8/review-algorithmic-thinking-by-building-a-dice-game/step-13

### CODE REVIEW

**Review by huyenltnguyen — COMMENTED** [review]
@AbdulMuqsit112 Thanks for the PR.

There is an instance of `span` that needs to be fixed. It's on line 34.

**Comment by AbdulMuqsit112** [comment]
> @AbdulMuqsit112 Thanks for the PR.
> 
> There is an instance of `span` that needs to be fixed. It's on line 34.

@huyenltnguyen  Thanks for highlighting i have updated it.

**Review by huyenltnguyen — APPROVED** [review]
LGTM 👍

**Review by jdwilkin4 — APPROVED** [review]
Congrats on your first contribution to our repository. 🎉
We look forward to future contributions. 👍

**Comment by AbdulMuqsit112** [comment]
@jdwilkin4 Thank you! I'm excited to contribute more in the future. 😊

**Pull request merged**
