### PR TITLE
fix: back button targets preview page

### LINKED ISSUE #41865: Back-button targets preview-page in coding challenge
**Describe your problem and how to reproduce it:**
1. Go [here](https://www.freecodecamp.org/learn/responsive-web-design/basic-html-and-html5/create-a-form-element).
2. Create the requested form.
3. Enter something in that text field and press enter.
4. A `Thank you!`-page appears in the preview section. **(see first screenshot)**

Everything is great up until now. Here comes the problem.

5. The user can now press BACK in the browser (or on the Mouse or via a keyboard shortcut). This, however doesn't go to the previous full page. Instead, it messes up the preview panel. **(see second screenshot)**
6. The user can then repeat steps 1-6 as often as he wants. It's kind of janky and doesn't seem like it should exist. **(see third screenshot)**

**Add a Link to the page with the problem:**
https://www.freecodecamp.org/learn/responsive-web-design/basic-html-and-html5/create-a-form-element

**Tell us about your browser and operating system:**
* Browser Name: Firefox
* Browser Version: 88.0 (64bit)
* Operating System: Linux (Mint)

**If possible, add a screenshot here (you can drag and drop, png, jpg, gif, etc. in this box):**
freeWeirdCodeBehaviour0

freeWeirdCodeBehaviour1

freeWeirdCodeBehaviour2

### PR DESCRIPTION
**Pull request by Sembauke**
Checklist:

- [x] I have read [freeCodeCamp's contribution guidelines](https://contribute.freecodecamp.org).
- [x] My pull request has a descriptive title (not a vague title like `Update index.md`)
- [x] My pull request targets the `main` branch of freeCodeCamp.
- [x] All the files I changed are in the same world language, for example: only English changes, or only Chinese changes, etc.

Closes #41865

Opens submitted form in new tab, I would like to hear opinion.

### CODE REVIEW

**Review by ShaunSHamilton — DISMISSED** [review]
I am happy with this behaviour 👍

**Review by moT01 — COMMENTED** [review]
I'm not sure on this one. I like the behavior for the problematic lesson, but there's at least a few other lessons with forms that behave a little goofy now. [This one](http://freecodecamp.org/learn/front-end-libraries/react/create-a-controlled-form/) now opens a new page when clicking submit... 
May-17-2021 07-55-21
It's not horrible, but it's not great either. I'm not sure if it's worth introducing this problem to fix the existing one. There may be other lessons with forms that don't behave as intended with this.

**Comment by Sembauke** [comment]
Thanks, @moT01  I will look for another solution.

**Comment by raisedadead** [comment]
While you are at it some cypress tests will help confirm that the behaviour is not changed elsewhere.

**Review by raisedadead — CHANGES_REQUESTED** [review]
While you are at it some cypress tests will help confirm that the behaviour is not changed elsewhere.

**Comment by Sembauke** [comment]
> While you are at it some cypress tests will help confirm that the behaviour is not changed elsewhere.

Can't really wrap my head around what it should test. What do you have on your mind?

**Comment by ojeytonwilliams** [comment]
It should be enough to test any challenge which has this behaviour. This PR should fix all of them, right?

**Comment by raisedadead** [comment]
Well, the initial commit in the PR managed to fix something at one place but broke something elsewhere, this is usually what we call no-intentional regressions. 

So we should cover these bases with tests when we discover such outomes.  

As for this specific change, I think the context should cover a user using at least the two use cases (even though the code that covers the use cases is literally the same).

The golden rule with testing is creating test cases that are dumb and covering as many (at the very least a couple) scenarios - without being biased on the code implementation. That essentially guarantees whosoever is changing code covers use cases.

**Comment by Sembauke** [comment]
I fully agree with adding more tests.  Though I've some concerns.

Cypress does not have [Multiple-tab support,](https://docs.cypress.io/guides/references/trade-offs#Multiple-tabs) so it can't check if the submitted form actually opens a new tab.  The target attribute gets added while submitting the form if an action attribute is present. So looking for `target="_blank"`  is also not an [option.](https://glebbahmutov.com/blog/cypress-tips-and-tricks/#deal-with-target_blank).

@ojeytonwilliams, Any ideas?

**Comment by raisedadead** [comment]
IMHO, we should discuss the implementation prior to going about the tests. I am personally not a fan of the [monkey-patching](https://www.google.com/search?q=monkey+patching) approach (both, this PR and existing logic) which certainly can have side effects.

We should avoid updating the browser history instead. I am not sure how to achieve this but that is what is the underlying issue in the OP.

**Comment by Sembauke** [comment]
I'll close this one. Until I figure out what's going on.

**Pull request closed without merging**
