### PR TITLE
fix(seed): Chall seed and test are modified to allow better testing

### LINKED ISSUE #16356: ES6: Use * to Import Everything from a File - import name ambiguity
#### Challenge Name
[ES6: Use * to Import Everything from a File](https://beta.freecodecamp.org/en/challenges/es6/use--to-import-everything-from-a-file)

#### Issue Description

~The challenge fails with 'require not defined' when importing from capitalize_string using the * wildcard.~ (edited by @systimotic: this part has been resolved)

Also the instructions is missing the object name to use myStringModule as the the 'as' name so it follows the editor. Currently the examples in the lesson state to use a name of your choice but that will fail since in the editor it is setup as myStringModule.capitalize("foo");

#### Browser Information

Browser Name, Version:
Operating System: FireFox 57.0 (64-bit) and Chrome Version 63.0.3239.84 (Official Build) (64-bit)
Mobile, Desktop, or Tablet: Laptop Windows 10 Professional 64-bit

#### Your Code

```js
"use strict";
import * as myStringModule from "capitalize_strings";
myStringModule.capitalize("foo");
myStringModule.lowercase("Foo");`


```
#### Screenshot

image

### PR DESCRIPTION
**Pull request by ahmaxed**
es6.json seed file changed

Closes #16356

#### Pre-Submission Checklist

- [x] Your pull request targets the `staging` branch of freeCodeCamp.
- [x] Branch starts with either `fix/`, `feature/`, or `translate/` (e.g. `fix/signin-issue`)
- [x] You have only one commit (if not, [squash](http://forum.freecodecamp.org/t/how-to-squash-multiple-commits-into-one-with-git/13231) them into one commit).
- [x] All new and existing tests pass the command `npm test`. Use `git commit --amend` to amend any fixes.

#### Type of Change

- [x] Small bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds new functionality)
- [ ] Breaking change (fix or feature that would change existing functionality)
- [ ] Add new translation (feature adding new translations)

#### Checklist:

- [x] Tested changes locally.
- [x] Addressed currently open issue (replace XXXXX with an issue no in next line)

Closes #XXXXX

### CODE REVIEW

**Comment by raisedadead** [comment]
@mstellaluna when you have a moment could you please test

**Comment by mstellaluna** [comment]
I am currently reviewing this PR

**Review by mstellaluna — APPROVED** [review]
LGTM

**Comment by mstellaluna** [comment]
@ahmadabdolsaheb It LGTM! approving.

**Pull request merged**
