### PR TITLE
fix: proxy console logs during test evaluation

### LINKED ISSUE #37805: curriculum bug - explicit console.log statements in code should show in both FCC console and browser console
When PR #37621 was recently merged, the overall user experience with the FCC and browser consoles was improved. I originally assumed (but did not test) when I approved that PR, that explicit console.log statements would show both in the FCC console and in the browser console.  However, some of them now only show in the browser console due, if they appear in the running of the first test case.

### PR DESCRIPTION
**Pull request by ojeytonwilliams**
- [x] I have read [freeCodeCamp's contribution guidelines](https://github.com/freeCodeCamp/freeCodeCamp/blob/master/CONTRIBUTING.md).
- [x] My pull request has a descriptive title (not a vague title like `Update index.md`)
- [x] My pull request targets the `master` branch of freeCodeCamp.
- [x] None of my changes are plagiarized from another source without proper attribution.
- [x] All the files I changed are in the same world language (for example: only English changes, or only Chinese changes, etc.)
- [x] My changes do not use shortened URLs or affiliate links.

Closes #37805

It also fixes some incorrect comments.

### CODE REVIEW

**Review by RandellDawson — APPROVED** [review]
LGTM.  I am still going to continue working on "fixing" all the challenge testStrings which short-circuit and error out based on how the test is written, because I ultimately want to see errors like "Reference Errors" of the user's code that do not show up until all the tests have been run (vs. just the first test).

**Comment by ojeytonwilliams** [comment]
Sure.  As we discussed, this is easy enough to change if we're confident all the errors will be meaningful.  All that needs to change is 

https://github.com/freeCodeCamp/freeCodeCamp/blob/5ea745d61fa4c4b2650c05f28fb1f63f0e8751b6/client/src/client/workers/test-evaluator.js#L102

and it just needs deleting.

**Comment by raisedadead** [comment]
So this PR can land as is?

**Comment by ojeytonwilliams** [comment]
Yep.  Right now this is how it should be, given how the current state of the challenge tests.

**Review by raisedadead — APPROVED** [review]

**Pull request merged**
