### PR TITLE
Fix/caesars cipher broken link char code at

### PR DESCRIPTION
**Pull request by LouisDell**
#### Pre-Submission Checklist

- [x] Your pull request targets the `staging` branch of FreeCodeCamp.
- [x] Branch starts with either `fix/`, `feature/`, or `translate/` (e.g. `fix/signin-issue`)
- [x] You have only one commit (if not, [squash](https://github.com/FreeCodeCamp/FreeCodeCamp/wiki/git-rebase#squashing-multiple-commits-into-one) them into one commit).
- [x] All new and existing tests pass the command `npm run test-challenges`. Use `git commit --amend` to amend any fixes.
#### Type of Change

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] Add new translation (feature adding new translations)
#### Checklist:

- [x] Tested changes locally.
- [ ] Closes currently open issue (`Closes #XXXX`): Closes

### CODE REVIEW

**Comment by theflametrooper** [comment]
## LGTM :+1:

Thanks @LouisDell :smiley:

**Comment by LouisDell** [comment]
Well thats a bummer

**Comment by theflametrooper** [comment]
@LouisDell Please check the HelpContributors Chat room!

**Comment by theflametrooper** [comment]
@LouisDell https://gitter.im/FreeCodeCamp/HelpContributors?at=5727eef3aa92b14772cb470a

**Comment by LouisDell** [comment]
i'll try again

**Pull request closed without merging**
