### PR TITLE
Update specify-how-fonts-should-degrade.md

### PR DESCRIPTION
**Pull request by impirios**
Added a period at the end of the second sentence "These generic font families include monospace, serif and sans-serif".

Checklist:

- [ ] I have read [freeCodeCamp's contribution guidelines](https://contribute.freecodecamp.org).
- [ ] My pull request has a descriptive title (not a vague title like `Update index.md`)
- [ ] My pull request targets the `main` branch of freeCodeCamp.
- [ ] I have tested these changes either locally on my machine, or GitPod.

Closes #XXXXX

### CODE REVIEW

**Comment by impirios** [comment]
Added a period at the end of the second sentence "These generic font families include monospace, serif and sans-serif"

**Comment by SethFalco** [comment]
Hey, and welcome to the repository! :wave:

Just a heads-up, you can populate the "Closes" field in the PR description with "Closes #42331", and it'll automatically close that issue when or if this gets merged.

**Review by SethFalco — APPROVED** [review]
Looks good to me! 👍🏽

**Review by Nirajn2311 — APPROVED** [review]
LGTM 👍

**Comment by Nirajn2311** [comment]
Hi @impirios. Congrats on your first pull request (PR)! 🎉

Thank you for your contribution to the page! 👍
We are happy to accept these changes and look forward to future contributions. 📝

**Pull request merged**
