### PR TITLE
fix(seed): fixed bug in Accessing Object Properties with Variables

### LINKED ISSUE #16827: [Beta] Basic JavaScript - Mistake in example code
#### Challenge
Javascript Algorithms And Data Structures - Basic JavaScript: Accessing Object Properties with Variables
https://beta.freecodecamp.org/en/challenges/basic-javascript/accessing-object-properties-with-variables 

#### Issue Description
There's a minor mistake in the second example. 
The example code says
```javascript
var someObj = {
  propName: "John"
};
function propPrefix(str) {
  var s = "prop";
  return s + str;
}
var someProp = propPrefix("Name"); // someProp now holds the value 'propName'
console.log(obj[someProp]); // "John"
```
fcc-basic-js-example-code

If you tried to run the code, it wouldn't print "John" in the console as variable _obj_ is not defined. 
I guess the last line was supposed to be 
```javascript
console.log(someObj[someProp]); // "John"
```

### PR DESCRIPTION
**Pull request by timdamra**
changed the "obj" variable to "someObj" to fix bug

Closes #16827

#### Pre-Submission Checklist

- [/ ] Your pull request targets the `staging` branch of freeCodeCamp.
- [x] Branch starts with either `fix/`, `feature/`, or `translate/` (e.g. `fix/signin-issue`)
- [ ] You have only one commit (if not, [squash](http://forum.freecodecamp.org/t/how-to-squash-multiple-commits-into-one-with-git/13231) them into one commit).
- [ ] All new and existing tests pass the command `npm test`. Use `git commit --amend` to amend any fixes.

#### Type of Change

- [/ ] Small bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds new functionality)
- [ ] Breaking change (fix or feature that would change existing functionality)
- [ ] Add new translation (feature adding new translations)

#### Checklist:

- [/ ] Tested changes locally.
- [ /] Addressed currently open issue (replace XXXXX with an issue no in next line)

Closes #16829

#### Description

"obj" was used in the place of "someObj" and was therefore throwing an exception when it is console.log'd.  I changed it to "someObj" and tested it locally, everything was good!

### CODE REVIEW

**Comment by timdamra** [comment]
Hey, 
Just realized I didn't squash previous commits into one.  Should I do that and resubmit a pull request?

**Comment by raisedadead** [comment]
Hi @timdamra you would need a rebase against staging and have only your changes in the pull request.

**Comment by timdamra** [comment]
Got it! thanks @raisedadead

**Comment by raisedadead** [comment]
Hi @timdamra how is this going? If you need assistance please reach out to the 
[Contributors Chat room](https://gitter.im/FreeCodeCamp/Contributors)

**Comment by timdamra** [comment]
ok I updated, and hope everything works this time.  thanks for the help @raisedadead !

**Comment by raisedadead** [comment]
Hi @timdamra 

This still is in a bad shape. 
See https://github.com/freeCodeCamp/freeCodeCamp/pull/16849/files

Can you proceed to the help chat or forum seeking guidance?

**Comment by timdamra** [comment]
yes, I'm there now @raisedadead, what is the issue?

**Comment by ojongerius** [comment]
@timdamra you are almost there! Do a rebase, fix one merge conflict, continue rebase, push and you should be all good.

Here is the gist I shared in Gitter, hope it's not too cryptic: https://gist.github.com/ojongerius/d84d8cffd52db8afd2a584a01c970055

**Comment by raisedadead** [comment]
Hi @timdamra we have accepted the other PR opened for the issue. But please do not be disappointed, we have plenty of other issues where we could use your help.

**Comment by timdamra** [comment]
No worries @raisedadead, i'm sure theres other issues I can tackle, thanks for all your help!

**Pull request closed without merging**
