### PR TITLE
fix(deps): downgrade lerna to v3

### PR DESCRIPTION
**Pull request by raisedadead**
See: https://github.com/lerna/lerna/issues/2845

### CODE REVIEW

**Review by ojeytonwilliams — APPROVED** [review]
This doesn't seem to work locally, but I'm happy to give it a go in case I'm doing something silly.

**Review by naomi-lgbt — APPROVED** [review]
Looks like it's fixed the issue for a couple of other projects. Worth a shot!

**Comment by ojeytonwilliams** [comment]
> Looks like it's fixed the issue for a couple of other projects. Worth a shot!

Agreed. The probability of silliness on my part is quite high.

**Comment by nhcarrigan** [comment]
So I told Renovate to rebase #44131 and either it doesn't properly rebase or the issue isn't fixed 😢

**Comment by ojeytonwilliams** [comment]
Back to the drawing board, then.

Modifying prettier is one option for a quick fix.

**Comment by raisedadead** [comment]
Thanks, gentlemen, let's give the prettier configs a go.

**Pull request merged**
