### PR TITLE
fix: Submit button click is not functional on Challenge Completion modal

### LINKED ISSUE #15763: Submit button doesn't work on click
#### Challenge Name

http://beta.freecodecamp.com/en/challenges/es6/use-class-syntax-to-define-a-constructor-function

#### Issue Description

After completing one of the tasks the modal appeared saying I was successful. However, the next button did not work. So I used control + enter which allowed me to continue to the next lesson. From the next lesson without doing anything else you can use control + enter to successfully complete the assignment then skip to the next lesson.

* Browser Name, Version: chrome
* Operating System: mac
* Mobile, Desktop, or Tablet: desktop

### PR DESCRIPTION
**Pull request by adityaparab**
#### Pre-Submission Checklist

- [x] Your pull request targets the `staging` branch of freeCodeCamp.
- [x] Branch starts with either `fix/`, `feature/`, or `translate/` (e.g. `fix/signin-issue`)
- [x] You have only one commit (if not, [squash](http://forum.freecodecamp.com/t/how-to-squash-multiple-commits-into-one-with-git/13231) them into one commit).
- [x] All new and existing tests pass the command `npm test`. Use `git commit --amend` to amend any fixes.

#### Type of Change

- [x] Small bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds new functionality)
- [ ] Breaking change (fix or feature that would change existing functionality)
- [ ] Add new translation (feature adding new translations)

#### Checklist:

- [x] Tested changes locally.
- [x] Closes currently open issue (replace XXXX with an issue no): Closes #15763 

#### Description
The click event handler was only looking for `Ctrl+Enter` key combination to proceed further. Added an if condition to check for type of event. If `e.type` is `click` then we proceed further. If `e.type` is `keydown` we do another check to see if `Ctrl+Enter` combination is detected to proceed further. Else the event will be ignored.

### CODE REVIEW

**Comment by BerkeleyTrue** [comment]
A more redux way of doing this is to instead create two action creators, one for click and one for button down. This will reduce the need for complex nested if/else blocks.

**Comment by adityaparab** [comment]
@BerkeleyTrue Thanks. Will update the PR soon

**Comment by yogaboll** [comment]
@adityaparab Are you still working on it? I feel like this is a very major bug that should be fixed asap. If you don't have the time I can do it instead.

**Comment by adityaparab** [comment]
@yogaboll : Sorry.. Been travelling lately so didn't get chance to push the latest changes. Will do this today.

**Comment by adityaparab** [comment]
@BerkeleyTrue @yogaboll 
I locally merged staging into my branch and now it shows tons of commits when I try to squash them.

Do I have to squash all the commits that I see there?

**Comment by adityaparab** [comment]
Closing this PR as I've raised another one. Not sure how to squash merged commits.
New PR can be [found here](https://github.com/freeCodeCamp/freeCodeCamp/pull/15834)

**Pull request closed without merging**
