### PR TITLE
fix(client): Remove horizontal scrollbar from donation page

### LINKED ISSUE #36127: [beta] There is an unexpected horizontal scrollbar on /donate
**Describe the bug**
There is an unexpected horizontal scrollbar on `/donate`.

The beta site is being down for maintenance at the moment. Here is a screenshot of my local fCC.

Untitled

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser: Firefox (66.0.5), Chrome (74.0.3729.169)

### PR DESCRIPTION
**Pull request by ojeytonwilliams**
- [x] I have read [freeCodeCamp's contribution guidelines](https://github.com/freeCodeCamp/freeCodeCamp/blob/master/CONTRIBUTING.md).
- [x] My pull request has a descriptive title (not a vague title like `Update index.md`)
- [x] My pull request targets the `master` branch of freeCodeCamp.
- [x] None of my changes are plagiarized from another source without proper attribution.
- [x] All the files I changed are in the same world language (for example: only English changes, or only Chinese changes, etc.)
- [x] My changes do not use shortened URLs or affiliate links.

Removes the horizontal scrollbar by wrapping the row in a container.  This made the form a little small. To fix this I adjusted the column classes.  At the same time, I tried to smooth out the transition from small to large screens

Closes #36127

### CODE REVIEW

**Review by moT01 — APPROVED** [review]
LGTM @ojeytonwilliams! 🎉  - looks like the grid just got forgotten here when the component was refactored.

Looks like another PR touches this file https://github.com/freeCodeCamp/freeCodeCamp/pull/36137

**Comment by ojeytonwilliams** [comment]
@moT01 So it does.  There may not even be a conflict - it looks like they don't touch that bit of the code.

**Comment by raisedadead** [comment]
Hi @ojeytonwilliams looks like we got into a merge conflict. Can you rebase this?

**Comment by ojeytonwilliams** [comment]
@raisedadead That'll teach me to make predictions.

I made three commits because they cover slightly different things. The first commit just merges, the second is a tweak to the style and the final one deals with a warning from the donate-other component. Apparently, even though the buttons aren't `<li>`s, React wants them to have keys.

**Review by raisedadead — APPROVED** [review]

**Pull request merged**
