### PR TITLE
feat(client): remove test logs from challenges

### PR DESCRIPTION
**Pull request by moT01**
When looking into a challenge - I noticed that logs were always showing up twice when running tests. One for the preview and once when running the test...
Screen Shot 2021-07-28 at 8 14 40 AM

It doesn't seem necessary. This removes all logs when running tests. The changes to `execute-challenge-saga` remove them from javascript style challenges - the `frame-runner` remove them from all others. I can't think of any negative side-effects from this.

Checklist:

- [x] I have read [freeCodeCamp's contribution guidelines](https://contribute.freecodecamp.org).
- [x] My pull request has a descriptive title (not a vague title like `Update index.md`)
- [x] My pull request targets the `main` branch of freeCodeCamp.
- [x] I have tested these changes either locally on my machine, or GitPod.

Closes #XXXXX

### CODE REVIEW

**Comment by ieahleen** [comment]
> I can't think of any negative side-effects from this.

there is maybe still a few challenges that have obscured tests, without the logs from the tests it makes difficult being able to find all function inputs.
Maybe this is more of a point for unobscuring those tests instead.

**Review by naomi-lgbt — APPROVED** [review]
I think this is good. @ieahleen provides a good point, but I agree that the challenges themselves should be adjusted for clarity.

**Comment by moT01** [comment]
Perhaps this issue needed some discussion first - after taking another look, this still shows logs from tests when they are in a function - specifically, if that function is called in a test (pretty sure anyway). It only removes logs from tests if the logs are not part of a function that is called. So, I suppose I'm wondering what you all think the behavior should be. My initial thought was that logs should only be shown if their code would log something when it's ran - which would mean this PR could remove those logs in functions when the tests are run. If we do want to keep those, then maybe this PR just isn't necessary.

**Comment by moT01** [comment]
I'm going close this so we can discuss it in an issue further.

**Pull request closed without merging**
