### PR TITLE
Fixed wording in Global Scope and Functions challenge instructions

### LINKED ISSUE #9755: Global Scope and Functions
Global Scope and Functions

https://www.freecodecamp.com/challenges/global-scope-and-functions#?solution=%0A%2F%2F%20Declare%20your%20variable%20here%0Avar%20myGlobal%20%3D%2010%3B%0A%0Afunction%20fun1()%20%7B%0A%20%20%2F%2F%20Assign%205%20to%20oopsGlobal%20Here%0A%20%20oopsGlobal%20%3D%205%3B%0A%7D%0A%0A%2F%2F%20Only%20change%20code%20above%20this%20line%0Afunction%20fun2()%20%7B%0A%20%20var%20output%20%3D%20%22%22%3B%0A%20%20if%20(typeof%20myGlobal%20!%3D%20%22undefined%22)%20%7B%0A%20%20%20%20output%20%2B%3D%20%22myGlobal%3A%20%22%20%2B%20myGlobal%3B%0A%20%20%7D%0A%20%20if%20(typeof%20oopsGlobal%20!%3D%20%22undefined%22)%20%7B%0A%20%20%20%20output%20%2B%3D%20%22%20oopsGlobal%3A%20%22%20%2B%20oopsGlobal%3B%0A%20%20%7D%0A%20%20console.log(output)%3B%0A%7D%0A

#### Issue Description

You just have to go to the Global Scope and Functions Challenge,
It says "Variables which are used without the var keyword are automatically created in the global scope"
But the instructions then say, 
" Declare a global variable myGlobal outside of any function. Initialize it to have a value of 10", so i declare it not using the var keyword.

But the problem is one of the steps says
"myGlobal should be declared using the var keyword"

#### Browser Information

* Browser Name, Version: 
* Operating System: 
* Mobile, Desktop, or Tablet: 

#### Your Code

```js
 
```

### PR DESCRIPTION
**Pull request by jaikamat**
#### Pre-Submission Checklist

- [X] Your pull request targets the `staging` branch of FreeCodeCamp.
- [X] Branch starts with either `fix/`, `feature/`, or `translate/` (e.g. `fix/signin-issue`)
- [X] You have only one commit (if not, [squash](https://github.com/FreeCodeCamp/FreeCodeCamp/wiki/Git-Squash) them into one commit).
- [X] All new and existing tests pass the command `npm run test-challenges`. Use `git commit --amend` to amend any fixes.
#### Type of Change

- [X] Small bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds new functionality)
- [ ] Breaking change (fix or feature that would change existing functionality)
- [ ] Add new translation (feature adding new translations)
#### Checklist:

- [X] Tested changes locally.
- [X] Closes currently open issue (replace XXXX with an issue no): #9755 
#### Description

Fixed the wording under the Global Scope and Functions challenge to reflect changes in original issue. Also added a period to the end of the sentence and changed `to have a value of` to `with a value of`.

### CODE REVIEW

**Comment by alayek** [comment]
# LGTM :+1: 

At least from my side. @erictleung how do we add translations?

**Comment by erictleung** [comment]
@jaikamat thanks for the PR! As @camperbot has pointed out, please remove the `Closes #9755` from your git commit message. A little confusing but we ask that the actual git commit message not have this statement. But the GitHub PR message should have it. So to remove it, you can run these commands to help

```sh
git checkout fix/global-scope-wording
git commit --amend
# Remove `Closes #9755` from your message
git push origin fix/global-scope-wording --force
```

@alayek we can either add them here or in another PR. [This line](https://github.com/FreeCodeCamp/FreeCodeCamp/blob/75bba05718dc0bb288beafb154ecc4b0181e8d64/seed/challenges/01-front-end-development-certification/basic-javascript.json#L2276) would need to be changed.

**Comment by jaikamat** [comment]
Thanks guys! @erictleung, I performed that update. Apologies for that.

As far as the translation is concerned, since I don't know other languages I'm useless in that regard 😦

**Comment by erictleung** [comment]
@jaikamat thanks! LGTM! 👍  Thanks for your contribution to FreeCodeCamp! ✨ 🎉 ✨

**Pull request merged**
