### PR TITLE
Update challenge descriptions with code tags

### PR DESCRIPTION
**Pull request by jneidel**
Adds missing code tags to multiple challanges in the category "Information Security with HelmetJS"

### CODE REVIEW

**Comment by moT01** [comment]
I am unable to checkout this locally due to the PR creator deleting his fork of the fcc repo. As you can see, the branch trying to be merged says "unknown repository" - I am not sure if we can still review/merge this.

**Comment by moT01** [comment]
I am going to close this since you have deleted the fork and branch @jneidel, which makes it difficult to review and merge. If you want these changes, you will have to make a new PR. Thanks and happy coding!

**Comment by jneidel** [comment]
@moT01 I'll reopen it will a new fork.

**Comment by moT01** [comment]
hey @jneidel, that PR I linked above will affect some of the same files. I'm wondering if it would be best to wait until that gets merged and then you make your changes to avoid conflicts later. If you want to just make the PR, that's fine, we can resolve conflicts when we get there. Either way works. I will try and get the other PR reviewed ASAP.

**Pull request closed without merging**
