### PR TITLE
Added Time Complexity of std::sort() to C++ Vector Guide

### PR DESCRIPTION
**Pull request by johncgenere**
- [x] I have read [freeCodeCamp's contribution guidelines](https://github.com/freeCodeCamp/freeCodeCamp/blob/master/CONTRIBUTING.md).
- [x] My pull request has a descriptive title (not a vague title like `Update index.md`)
- [x] My pull request targets the `master` branch of freeCodeCamp.
- [x] None of my changes are plagiarized from another source without proper attribution.
- [x] All the files I changed are in the same world language (for example: only English changes, or only Chinese changes, etc.)
- [x] My changes do not use shortened URLs or affiliate links.

### CODE REVIEW

**Comment by johncgenere** [comment]
Is there a specific reason my pull request has been open for some time?

**Comment by RandellDawson** [comment]
We have many PRs which are from November which have yet to be reviewed, so it will probably take some time before we get to this one.  Don't worry though, we will eventually review it.

**Comment by johncgenere** [comment]
Got it, thank you! I just wanted to make sure that had nothing to do with the changes I made to the file

**Comment by RandellDawson** [comment]
We'll let you know if there are any issues or changes which need to be made.

**Comment by RandellDawson** [comment]
Thank you for opening this pull request.

This is a standard message notifying you that we’ve reviewed your pull request and have decided not to merge it. We would welcome future pull requests from you.

**Reason:** This PR currently has merge conflicts and since you deleted the fork/branch, we can not easily resolve. Please create a new fork and review the file on master to see if the modifications made in this PR are still needed. If so, please create a new pull request.

Thank you and happy coding.

**Pull request closed without merging**
