### PR TITLE
fix(curriculum): changed instructions for clarity 

### LINKED ISSUE #48582: Two variables which are same
### The issue is in _Backend Development and APIs Course, MongoDB and Mongoose section_ challenge "Create a Model" 

In the instructions, we are asked to create a model called `Person` from `personSchema` by the code:
```js
const Person = mongoose.model("Person", personSchema);
```
However in the folder `boilerplate-mongomongoose`, there is already an empty variable:
```js
let Person;
```
Following the instructions gives a bug as the Person variable is already declared.
We have to delete the empty variable in order to continue with the instructions. Maybe the hints should be corrected for the challenge or the variable name in the instruction should be changed.

### Affected Page

https://www.freecodecamp.org/learn/back-end-development-and-apis/mongodb-and-mongoose/create-a-model

### Your code

```

```

### Expected behavior

We should not get an error after running the code.

### Screenshots

_No response_

### System

- Device: [e.g. iPhone 6, Laptop]
- OS: [e.g. iOS 14, Windows 10, Ubuntu 20.04]
- Browser: [e.g. Chrome, Safari]
- Version: [e.g. 22]

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by Dave2188**
Checklist:

- [x ] I have read and followed the [contribution guidelines](https://contribute.freecodecamp.org).
- [ x] I have read and followed the [how to open a pull request guide](https://contribute.freecodecamp.org/#/how-to-open-a-pull-request).
- [ x] My pull request targets the `main` branch of freeCodeCamp.
- [x ] I have tested these changes either locally on my machine, or GitPod.

Closes #48582 

Screenshot 2023-02-26 at 6 10 00 PM

### CODE REVIEW

**Comment by gikf** [comment]
Hey @Dave2188,

Could you remove the `package-lock.json` files from the PR?

**Comment by Dave2188** [comment]
@gikf Yeah, no problem they are deleted. I had a feeling that they shouldn't be there and now I know for next time.

**Review by gikf — APPROVED** [review]
LGTM :+1:

**Review by naomi-lgbt — APPROVED** [review]

**Comment by naomi-lgbt** [comment]
Thank you for your contribution to the page! 👍
We are happy to accept these changes and look forward to future contributions. 🎉

**Pull request merged**
