### PR TITLE
Add checks for number of items in returned array

### LINKED ISSUE #11798: Array with null values passing the testcases
Challenge [Diff Two Arrays](https://www.freecodecamp.com/challenges/diff-two-arrays) has an issue.

My solution for this algorithm is not correct yet, but the test cases are passing.

For this test:
```
["diorite", "andesite", "grass", "dirt", "pink wool", "dead shrub"], ["diorite", "andesite", "grass", "dirt", "dead shrub"]
```
Should return:
```
["pink` wool"]
```
I'm getting:
```
[null,null,null,null,null,null,null,null,null,null,"pink wool"]
```
My code:
```javascript

function diffArray(arr1, arr2) {
  var newArr = arr1.concat(arr2).sort();
  
  // Same, same; but different.
  newArr.filter(function(value, index, arr) {
    if (value === arr[index + 1]) {
      delete arr[index];
      delete arr[index + 1];
      return false;
    }
    return true;
  });
  return newArr;
}

diffArray(["diorite", "andesite", "grass", "dirt", "pink wool", "dead shrub"], ["diorite", "andesite", "grass", "dirt", "dead shrub"]);

```

### PR DESCRIPTION
**Pull request by Manish-Giri**
#### Pre-Submission Checklist

- [x] Your pull request targets the `staging` branch of FreeCodeCamp.
- [x] Branch starts with either `fix/`, `feature/`, or `translate/` (e.g. `fix/signin-issue`)
- [x] You have only one commit (if not, [squash](http://forum.freecodecamp.com/t/how-to-squash-multiple-commits-into-one-with-git/13231) them into one commit).
- [x] All new and existing tests pass the command `npm test`. Use `git commit --amend` to amend any fixes.

#### Type of Change

- [x] Small bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds new functionality)
- [ ] Breaking change (fix or feature that would change existing functionality)
- [ ] Add new translation (feature adding new translations)

#### Checklist:

- [x] Tested changes locally.
- [x] Closes currently open issue (replace XXXX with an issue no): Closes #11798 

#### Description

Added assertions using `assert.lengthOf()` to ensure that the returned array has the expected number of elements.

This change doesn't seem to pass the tests at my end, it might be an issue with my local environment. Submitting the PR to see if it passes here.

closes #11798

### CODE REVIEW

**Comment by Manish-Giri** [comment]
As with my local environment, the tests don't seem to pass here as well. This is the problem - 

` ✖ TypeError: assert.lengthOf is not a function`

If anyone has any tips on how to fix this, would be much appreciated!

**Comment by dhcodes** [comment]
Tested, but I'm not getting any output. Is that a staging issue? Also, I might recommend that you combine the .length tests into the existing tests instead of duplicating them, but maybe I don't know enough context.

**Comment by Manish-Giri** [comment]
@dhcodes So I just resolved the issues with mongodb in my local windows machine, and ran these changes. I'm not quite sure what you mean by "no output". When I run these changes locally, I can see all the new checks I've added, and I tried running the algo. with one of the proposed solutions from the bonfire wiki. The new tests pass. Here are the screenshots (first three are screenshots of the new tests, last one is of the challenge passing) - [one](https://www.dropbox.com/s/6xrp8e1c4xx5mcs/%2311912-a.png?dl=0),  [two](https://www.dropbox.com/s/xals5feal3l1xme/%2311912-b.png?dl=0), [three](https://www.dropbox.com/s/mitv1yf3l3m47rg/%2311912-c.png?dl=0), [four](https://www.dropbox.com/s/lpg4sy31v7uukw9/%2311912-d.png?dl=0).

Not sure what I'm missing!

**Comment by dhcodes** [comment]
@Manish-Giri update on this. It works! I think the output issue has to do with https://github.com/FreeCodeCamp/FreeCodeCamp/issues/9363. I do, however, think you should combine your tests with the existing ones via `&&`. Are you good with that?

**Comment by Manish-Giri** [comment]
@dhcodes Of course! I'll do the changes. Thanks a bunch for looking at it again 😃

**Comment by Manish-Giri** [comment]
@dhcodes I tried merging the two checks for each test into a single one, but I ran into some unexpected results. It looks like if you merge the two tests into one, something like - 
`assert.sameMembers(x,y,'message one') && assert(x.length === 1, 'message two');`

Only the message in the last test is rendered on the screen. This could mean either of two things - 
- The message in the first test is absorbed and only the message in the last one is considered, or
- The first test is completely ignored. 

For instance, for the first test, which originally was - 
```
"assert.sameMembers(diffArray([\"diorite\", \"andesite\", \"grass\", \"dirt\", \"pink wool\", \"dead shrub\"], [\"diorite\", \"andesite\", \"grass\", \"dirt\", \"dead shrub\"]), [\"pink wool\"], 'message: <code>[\"diorite\", \"andesite\", \"grass\", \"dirt\", \"pink wool\", \"dead shrub\"], [\"diorite\", \"andesite\", \"grass\", \"dirt\", \"dead shrub\"]</code> should return <code>[\"pink wool\"]</code>.');"
```
if you add the check of the length of the returned array with an `&&` to this, so that it looks like - 
```
"assert.sameMembers(diffArray([\"diorite\", \"andesite\", \"grass\", \"dirt\", \"pink wool\", \"dead shrub\"], [\"diorite\", \"andesite\", \"grass\", \"dirt\", \"dead shrub\"]), [\"pink wool\"], 'message: <code>[\"diorite\", \"andesite\", \"grass\", \"dirt\", \"pink wool\", \"dead shrub\"], [\"diorite\", \"andesite\", \"grass\", \"dirt\", \"dead shrub\"]</code> should return <code>[\"pink wool\"]</code>.') && assert(diffArray([\"diorite\", \"andesite\", \"grass\", \"dirt\", \"pink wool\", \"dead shrub\"], [\"diorite\", \"andesite\", \"grass\", \"dirt\", \"dead shrub\"]).length === 1, 'message: <code>[\"diorite\", \"andesite\", \"grass\", \"dirt\", \"pink wool\", \"dead shrub\"], [\"diorite\", \"andesite\", \"grass\", \"dirt\", \"dead shrub\"]</code> should return an array with one item.');",
```
the only output shown on screen is - 
`["diorite", "andesite", "grass", "dirt", "pink wool", "dead shrub"], ["diorite", "andesite", "grass", "dirt", "dead shrub"] should return an array with one item.`

If you reverse the order of the tests such that the test for length of the returned array comes first, followed by the `sameMembers` test, like - 
```
"assert(diffArray([\"diorite\", \"andesite\", \"grass\", \"dirt\", \"pink wool\", \"dead shrub\"], [\"diorite\", \"andesite\", \"grass\", \"dirt\", \"dead shrub\"]).length === 1, 'message: <code>[\"diorite\", \"andesite\", \"grass\", \"dirt\", \"pink wool\", \"dead shrub\"], [\"diorite\", \"andesite\", \"grass\", \"dirt\", \"dead shrub\"]</code> should return an array with one item.') && assert.sameMembers(diffArray([\"diorite\", \"andesite\", \"grass\", \"dirt\", \"pink wool\", \"dead shrub\"], [\"diorite\", \"andesite\", \"grass\", \"dirt\", \"dead shrub\"]), [\"pink wool\"], 'message: <code>[\"diorite\", \"andesite\", \"grass\", \"dirt\", \"pink wool\", \"dead shrub\"], [\"diorite\", \"andesite\", \"grass\", \"dirt\", \"dead shrub\"]</code> should return <code>[\"pink wool\"]</code>.');",
```
 this is the output - 
`["diorite", "andesite", "grass", "dirt", "pink wool", "dead shrub"], ["diorite", "andesite", "grass", "dirt", "dead shrub"] should return ["pink wool"]` 

I had both these lines in my code (in this order), and this is the output when tested on my local instance - 
1c

I'm not sure if this is the expected behavior when combining multiple tests. Maybe you could run these two code snippets in your local instance and check if it produces the same results?

Thanks!

**Comment by dhcodes** [comment]
cc @FreeCodeCamp/moderators. @Manish-Giri has done an excellent job of adding working assert tests for array length to this exercise to quash the issue. Originally, I had requested that he combine the tests with the existing ones, but we can't seem to get them to work then since one is an `assert` test and the other is an `assert.sameMembers` test. 

My question is: I've been reading some testing best practices that suggest only using one `assert` per test. So I'm tempted to retract my recommendation for him to combine the tests and merge it as-is (thereby duplicating the number of tests). Thoughts?

**Comment by dhcodes** [comment]
Tagging @Bouncey and @erictleung since you guys commented on the original issue. See above. Good to merge even though the number of tests will be doubled?

**Comment by Manish-Giri** [comment]
Any thoughts/decision on this, anyone?

**Comment by dhcodes** [comment]
@raisedadead can you give your expert opinion on this? It's sort of frozen at the moment and I'd like to merge it.

**Comment by raisedadead** [comment]
@Manish-Giri @dhcodes Thanks for the pull request and looking in-depth into this change.

Sorry about the delay in the QA, I have been swamped with getting my todo's cleared. This is definitely on the list as well.
I will take a look as soon as I am able. Please bear with me.

**Comment by dhcodes** [comment]
I'm going to merge this one in. I have no issues with adding to the number of tests to net the right outcomes. 

Thanks @Manish-Giri 👍  :eagle: 🌮

**Comment by raisedadead** [comment]
Thanks @dhcodes @Manish-Giri for the awesome, work, sorry once again for being late to the party! Hope you will forgive..! 😓

**Comment by dhcodes** [comment]
np @raisedadead just needed a third brain. Hopefully we won't have to reopen it anytime soon...

**Pull request merged**
