### PR TITLE
fix(seed): Eliminate regex bug for async assertions

### LINKED ISSUE #16312: React Challenge shouldComponentUpdate
#### Challenge Name
React Optimize Re-Renders with shouldComponentUpdate

#### Issue Description
It seems submitted code true but there is a problem in last two tests resulting regular expression errors.
[Problem 1 async last part, assert](https://github.com/freeCodeCamp/freeCodeCamp/blob/16dcfb41833498e0a6efd788735b413900970817/seed/challenges/03-front-end-libraries/react.json#L2132)
[Problem 2 async last part, assert](https://github.com/freeCodeCamp/freeCodeCamp/blob/16dcfb41833498e0a6efd788735b413900970817/seed/challenges/03-front-end-libraries/react.json#L2133)

#### Browser Information
* Browser Name, Version: Opera 49.0.2725.64
* Operating System: Ubuntu 16.04
* Mobile, Desktop, or Tablet: Desktop

#### Your Code
```js
class OnlyEvens extends React.Component {
  constructor(props) {
    super(props);
  }
  shouldComponentUpdate(nextProps, nextState) {
    console.log('Should I update?');
     // change code below this line
    return !(nextProps['value'] % 2);
     // change code above this line
  }
  componentWillReceiveProps(nextProps) {
    console.log('Receiving new props...');
  }
  componentDidUpdate() {
    console.log('Component re-rendered.');
  }
  render() {
    return <h1>{this.props.value}</h1>
  }
};

class Controller extends React.Component {
  constructor(props) {
    super(props);
    this.state = {
      value: 0
    };
    this.addValue = this.addValue.bind(this);
  }
  addValue() {
    this.setState({
      value: this.state.value + 1
    });
  }
  render() {
    return (
      <div>
        <button onClick={this.addValue}>Add</button>
        <OnlyEvens value={this.state.value}/>
      </div>
    );
  }
};
```
#### Screenshot
image

### PR DESCRIPTION
**Pull request by StephenMayeux**
BREAKING CHANGE: Reseeding the database is required

#### Pre-Submission Checklist

- [x] Your pull request targets the `staging` branch of freeCodeCamp.
- [x] Branch starts with either `fix/`, `feature/`, or `translate/` (e.g. `fix/signin-issue`)
- [x] You have only one commit (if not, [squash](http://forum.freecodecamp.org/t/how-to-squash-multiple-commits-into-one-with-git/13231) them into one commit).
- [x] All new and existing tests pass the command `npm test`. Use `git commit --amend` to amend any fixes.

#### Type of Change

- [x] Small bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds new functionality)
- [ ] Breaking change (fix or feature that would change existing functionality)
- [ ] Add new translation (feature adding new translations)

#### Checklist:

- [x] Tested changes locally.
- [x] Addressed currently open issue (replace XXXXX with an issue no in next line)

Closes #16312

#### Description

There were two (2) tests that were failing for the React `shouldComponentUpdate` challenge, and the output referenced a regex error. Upon inspection, the test were written correctly but the final argument of the `assert()` method (i.e. the string displayed if the test fails) was malformed as there was some text outside the single quotes.

### CODE REVIEW

**Review by no-stack-dub-sack — CHANGES_REQUESTED** [review]
@StephenMayeux This looks good to me, but as discussed in #16312, let's update this to include fixes for the other broken tests as well (#16314, #16316), which may be slightly different issues, but similarly simple to fix. Thanks! This will be a sweet first PR!

**Comment by no-stack-dub-sack** [comment]
@StephenMayeux are you up for making the requested changes?

**Comment by raisedadead** [comment]
@StephenMayeux how is it going?

**Review by raisedadead — APPROVED** [review]

**Comment by raisedadead** [comment]
#### :sparkles: :sparkles: **AWESOME! LGTM.** :sparkles: :sparkles: 

Thanks @StephenMayeux , for this pull request and contributing to the code-base for the first time.
We will be looking forward for more contributions in future.

Cheers and happy contributing!

**Pull request merged**
