### PR TITLE
fix Big-o-notation from exponential time to polynomial time in videos/big-o-notation-a-few-examples

### LINKED ISSUE #9655: videos/big-o-notation-a-few-examples "exponential time" -> "polynomial time"
#### Challenge Name

https://www.freecodecamp.com/videos/big-o-notation-a-few-examples

#### Issue Description

In the discussion and questions concerning big-o notation, O(N^2) is referred to as "exponential time", which is wrong. 

O(N^C), where C is any constant greater than 1 (e.g. 2) is called "polynomial time". 

Exponential time looks like O(C^N), where the input variable (N) is in the exponent.

Roughly speaking, the complexity class P (polynomial time solvable) is what we (or complexity theorists) consider "easy" - or at least solvable.

Exponential time algorithms typically have no hope of being solved on large inputs (and therefore are good candidates for heuristics, or approximations).

For a bit more intuition, an algorithm with O(N^2) complexity may not be a good candidate for real-time processing in your web app - but it may be perfectly suitable for less time critical tasks. With an algorithm like this, you might decide to pre-compute some solutions as a workaround.

With an exponential time algorithm O(C^N), on the other hand, the sun may burn out before your computation ends.

Concerning O(infinity) - notice the lack of an input variable (N), and that infinity isn't a number. It's probably best to replace that idea with a statement about non-terminating routines. This might lead into a discussion about the halting problem, for example.

### PR DESCRIPTION
**Pull request by RP99**
#### Pre-Submission Checklist

- [x] Your pull request targets the `staging` branch of FreeCodeCamp.
- [x] Branch starts with either `fix/`, `feature/`, or `translate/` (e.g. `fix/signin-issue`)
- [x] You have only one commit (if not, [squash](http://forum.freecodecamp.com/t/how-to-squash-multiple-commits-into-one-with-git/13231) them into one commit).
- [x] All new and existing tests pass the command `npm run test-challenges`. Use `git commit --amend` to amend any fixes.
#### Type of Change

- [x] Small bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds new functionality)
- [ ] Breaking change (fix or feature that would change existing functionality)
- [ ] Add new translation (feature adding new translations)
#### Checklist:

- [x] Tested changes locally.
- [x] Closes currently open issue (replace 9655 with an issue no): Closes #9655 
#### Description

Editied the question concerning big-o-notation from exponential time(previous incorrect reference) to polynomial time.

### CODE REVIEW

**Comment by ltegman** [comment]
@RP99 Thanks for the PR -- however, I have concerns about making the lesson text and quiz diverge from the video which I have expressed [here](https://github.com/FreeCodeCamp/FreeCodeCamp/issues/9655#issuecomment-245463456). I'm going to mark this as blocked until we get some more input in there.

Thanks for your patience!

**Comment by Bouncey** [comment]
@atjonathan was this covered by your hikes recording session the other day?

**Comment by atjonathan** [comment]
@Bouncey, no. I don't believe we need to worry about diverging, these kind of changes have been made before.

**Review by ghost — COMMENTED** [review]
### LGTM 👍

Congratulations on your first open source contribution @RP99 🎉

**Pull request merged**
