### PR TITLE
fix: Update example metric imperial converter project URLs

### LINKED ISSUE #34504: Information Security and Quality Assurance Projects - Metric-Imperial Converter : example app not functioning
**Describe your problem and how to reproduce it:**
The example app (hard-twilight) is not working properly, neither with Firefox nor with Chrome. Instead I get an explorer with the public source files.

**Add a Link to the page with the problem:**
https://learn.freecodecamp.org/information-security-and-quality-assurance/information-security-and-quality-assurance-projects/metric-imperial-converter
Direct link to the app: 
https://hard-twilight.glitch.me/

**Tell us about your browser and operating system:**
* Browser Name: Firefox and Brave
* Browser Version: latest
* Operating System: Ubuntu 18.04
challenge

**If possible, add a screenshot here (you can drag and drop, png, jpg, gif, etc. in this box):**

### PR DESCRIPTION
**Pull request by scissorsneedfoodtoo**
Changes URLs to a working fCC example project in all languages (except Arabic where the description doesn't exist for some reason).

As noted in https://github.com/freeCodeCamp/freeCodeCamp/pull/23953, the project at https://incongruous-beard.glitch.me/ fails with certain inputs. 

I've remixed the project and updated the code at https://excited-nyala.glitch.me/. Inputs like 13/13/13 now returns 'no unit', and 13/13/13[unit] works as expected. Obviously broken inputs like 1a3lbs and 1a3lbz should also return invalid number and invalid number and unit, respectively.

But let's get the working project in this PR (https://incongruous-beard.glitch.me/) in as soon as we can. Now that it's in the fCC Glitch account, we can always improve the functionality later.

- [x] I have read [freeCodeCamp's contribution guidelines](https://github.com/freeCodeCamp/freeCodeCamp/blob/master/CONTRIBUTING.md).
- [x] My pull request has a descriptive title (not a vague title like `Update index.md`)
- [x] My pull request targets the `master` branch of freeCodeCamp.
- [x] None of my changes are plagiarized from another source without proper attribution.
- [ ] All the files I changed are in the same world language (for example: only English changes, or only Chinese changes, etc.)
- [x] My changes do not use shortened URLs or affiliate links.

Closes https://github.com/freeCodeCamp/freeCodeCamp/issues/34504

### CODE REVIEW

**Comment by moT01** [comment]
What is it you want tested here @scissorsneedfoodtoo? The project you put in the files still has the issues. You saying to just add it somewhat broken like that and you will replace it with your remix when you can?

**Comment by scissorsneedfoodtoo** [comment]
@moT01, could you take a look at this remix?: https://excited-nyala.glitch.me/

I believe I fixed the problems outlined in #23953 with the project at https://incongruous-beard.glitch.me/

Once we confirm everything is working as expected, I'll update the code in https://incongruous-beard.glitch.me/ before we merge this.

**Comment by moT01** [comment]
https://incongruous-beard.glitch.me/api/convert?input=1a3lbs
returns the conversion - not sure what it should return, since there is a valid number and unit. 

https://incongruous-beard.glitch.me/api/convert?input=13/13/13
returns "invalid number" - it should probably return "invalid number and unit" 

https://excited-nyala.glitch.me/api/convert?input=1a3lbs
returns "invalid number" - however, there is a valid number - but I guess this is probably better than the conversion?

https://excited-nyala.glitch.me/api/convert?input=13/13/13
returns "no unit" - seems like that number should be invalid and it should return "invalid number and unit"

https://excited-nyala.glitch.me/api/convert?input=13/13/13mi
returns the conversion - seems like numbers like this should not be valid. I know the instructions say `fractions, decimals or both` - but 13/13/13, not sure that qualifies as a fraction, but more of a mathematical equation.

https://excited-nyala.glitch.me/api/convert?input=13*13mi
returns the conversion for `13mi` and ignores the multiply.

Overall, your new project (excited-nyala) works better - these are edge cases that can probably have a little bit of leeway. I'm not sure instructions are clear enough to say what should happen in some of these cases.

On another note: I have been looking at making some tests for the backend projects and could probably use some help. [it was said](https://github.com/freeCodeCamp/freeCodeCamp/pull/35673#issuecomment-500215954) to just add tests in the challenge files. But some of the projects don't have specific routes to hit. This project, for instance, it would be nice to just hit the `/api/convert` route with the `input` parameter. But the instructions don't specifically say to use the `input` parameter; so campers could use any name there. This is similar on a lot of other projects, I believe. It would be nice to have a little discussion about how we can go about this. I think the quickest fix would be to just go through the projects and specify what routes/parameters campers need to use, and we just hit those in the tests. It wouldn't allow us to check if they completed all the functional/unit tests, but it would be something so they can't just submit any URL and pass.

**Comment by scissorsneedfoodtoo** [comment]
@moT01, thank you for your thorough review of both Glitch projects. 

I agree that it's difficult to design around every edge case and that there should be some leeway, especially for learners. While it would be nice for the example project to handle many, if not all of these cases, I don't think we should expect the projects that learners to submit to do the same. As you mentioned, the instructions here don't specify what should happen for these types of input. If it did, the instructions would be way too long.

For the tests, I think you're right that we should specify which routes and parameters to use in each project. Definitely seems like the most straightforward solution to check that each project is working as expected.

**Comment by scissorsneedfoodtoo** [comment]
Merging this to get the updated project URL in before we go live. Will update the project on Glitch in a moment. Big thank you again to @doubleUTF for overhauling this project :100: :1st_place_medal:

**Comment by doubleUTF** [comment]
@scissorsneedfoodtoo Thank you for helping wrap up this loose end. I felt like my efforts were fruitless until you picked up where I left off. Hope to see it merged into production in the near future so the campers don't see a broken project anymore!

**Comment by scissorsneedfoodtoo** [comment]
@doubleUTF, thousands of learners will benefit from your efforts, so it was definitely not fruitless. Thank you again for all your hard work getting this project running again. All I really did was copy and paste what you did over into our Glitch project :)

Please keep an eye out for it in the next day or two!

**Pull request merged**
