### PR TITLE
Correct footer and header order description

### PR DESCRIPTION
**Pull request by mdwcrft**
Header & footer swapped to refer to top and bottom respectively

- [x] I have read [freeCodeCamp's contribution guidelines](https://github.com/freeCodeCamp/freeCodeCamp/blob/master/CONTRIBUTING.md).
- [x] My pull request has a descriptive title (not a vague title like `Update index.md`)
- [x] My pull request targets the `master` branch of freeCodeCamp.
- [x] None of my changes are plagiarized from another source without proper attribution.
- [x] My article does not contain shortened URLs or affiliate links.

If your pull request closes a GitHub issue, replace the XXXXX below with the issue number.

Closes #XXXXX

### CODE REVIEW

**Review by RandellDawson — APPROVED** [review]
@mdwcrft This change in the test text definitely makes the test make more sense.  Good catch!

**Review by moT01 — CHANGES_REQUESTED** [review]
The line above the one you changed should also be changed to match...
screen shot 2019-02-22 at 8 35 04 am

**Comment by moT01** [comment]
@RandellDawson, I pushed the changes I requested - if you want to take another quick look, I think this can be merged.

**Review by moT01 — APPROVED** [review]

**Comment by mdwcrft** [comment]
@moT01 Didn't see that, thanks

**Review by RandellDawson — APPROVED** [review]
I agree these changes make the challenge tests text match the original instructions.

**Comment by RandellDawson** [comment]
Congrats @mdwcrft on your first pull request (PR)! 🎉

Thank you for your contribution to the page! 👍
We're happy to accept these changes, and look forward to future contributions. 📝

**Pull request merged**
