### PR TITLE
chore(utils): migrate block-nameify to TS and add unit tests

### PR DESCRIPTION
**Pull request by Kroustille**
Checklist:

- [x] I have read [freeCodeCamp's contribution guidelines](https://contribute.freecodecamp.org).
- [x] My pull request has a descriptive title (not a vague title like `Update index.md`)
- [x] My pull request targets the `main` branch of freeCodeCamp.
- [x] I have tested these changes either locally on my machine, or GitPod.

### CODE REVIEW

**Comment by ieahleen** [comment]
Hey there! Can you take a moment and align the title with the [contributing guidelines](https://contribute.freecodecamp.org/#/how-to-open-a-pull-request?id=prepare-a-good-pr-title)?

**Comment by Kroustille** [comment]
> Hey there! Can you take a moment and align the title with the [contributing guidelines](https://contribute.freecodecamp.org/#/how-to-open-a-pull-request?id=prepare-a-good-pr-title)?

Yeah sure, I wanted to ask: would this be a `fix` or `feat` ? It adds new unit tests and typings so it can be a `feat`, but can also be considered as a `fix` since it's improving existing code 🤔

**Comment by ieahleen** [comment]
it could be chore — it's migrating to typescript, not changing how it works
or it could be feat for the new tests

**Review by raisedadead — APPROVED** [review]

**Review by ShaunSHamilton — APPROVED** [review]
👍  LGTM

Thank you for taking the time to contribute

**Comment by Sboonny** [comment]
#### :sparkles: :tada: **AWESOME!** :tada: :sparkles:

 Hi @Kroustille, thanks for this pull request and for contributing to the code-base for the first time. We are looking forward to more contributions from you in the future.

 Cheers & happy contributing!

**Pull request merged**
