### PR TITLE
fix(api, client): update Gatsby, webpack & related things

### PR DESCRIPTION
**Pull request by raisedadead**
Need to resolve a lot of compatibility issues I believe before this can be opened for QA and review: https://www.gatsbyjs.com/docs/reference/release-notes/migrating-from-v2-to-v3

### CODE REVIEW

**Comment by raisedadead** [comment]
Hey @ojeytonwilliams 

I am going to need some help with this one. 

Here is a list of things:

- [ ] Resolve the errors with [GraphQL](https://www.gatsbyjs.com/docs/reference/release-notes/migrating-from-v2-to-v3/#graphql-__typename-field-is-no-longer-added-automatically) - I looked for the source but could not wrap my head around it.
- [ ] I understand we do not need to update the `webpack` or `webpack-cli` which we use for our frame runner packages. If yes, that could be done in a separate PR, but its high-priority regardless (we are on webpack-cli v3) of this migration. 
- [ ] More errors with sitemap plugin that is third-party and unsupported that I will update later.

**Comment by ojeytonwilliams** [comment]
> I understand we do not need to update the webpack or webpack-cli which we use for our frame runner packages. If yes, that could be done in a separate PR, but its high-priority regardless (we are on webpack-cli v3) of this migration.

I ran into some weird problems related to this - I'm not 100% sure why, but *both* clis were installed and conflicted with each other.  It's odd.

Regardless, I think we should get on with updating webpack now.

Also, I updated to the v2 lockfile again, since that got reverted.

**Comment by ojeytonwilliams** [comment]
@raisedadead I've run into the weirdest bugs with this one - randomly the api stopped passing :man_shrugging:.  Assuming it all works, I'll try removing the `/` from the `require.resolve` and update the linting to include the stuff Gatsby now checks for.

**Comment by raisedadead** [comment]
> I've run into the weirdest bugs with this one - randomly the api stopped passing

I would scope the PR to only the gatsby upgrade only and not the API if avoidable. I would not want to get carried away because a rewrite is in works all/most of the API code may change.

**Comment by ojeytonwilliams** [comment]
The api failing was, I think, a random glitch.  All I'm doing is finishing the Gatsby and webpack migrations and fixing any warnings that arise because of that.

There are a *lot* of warnings, though, so I had to refactor a bunch of things.

**Comment by ojeytonwilliams** [comment]
@raisedadead I didn't touch the sitemap, since I figured this PR had ballooned enough.

**Review by naomi-lgbt — DISMISSED** [review]
This looks good to me. Pulled down locally, built the client, poked around. Submitted some google.com projects, claimed a cert, did some JS challenges, changed my settings, did some video questions...

I didn't see any issues. Unfortunate about the no-named-imports thing, though.

**Comment by ojeytonwilliams** [comment]
> Unfortunate about the no-named-imports thing, though.

It is. I'm not sure if it's just a [webpack thing](https://webpack.js.org/migrate/5/#using-named-exports-from-json-modules), but I guess we need to change regardless.

**Comment by raisedadead** [comment]
@ojeytonwilliams mind fixing the rebase?

**Comment by ahmadabdolsaheb** [comment]
I am getting the following warnings when developing
image

**Comment by raisedadead** [comment]
Could you provide detailed steps for reproducing these errors?

**Comment by ojeytonwilliams** [comment]
@ahmadabdolsaheb I think these are existing issues that used to only be logged when we built the client.  See, for example https://github.com/freeCodeCamp/freeCodeCamp/runs/2185405260?check_suite_focus=true#step:10:239

**Comment by ahmadabdolsaheb** [comment]
> Could you provide detailed steps for reproducing these errors?

`npm run clean-and-develop`

@ojeytonwilliams, you are right. Those seem to be pre existing.

**Comment by moT01** [comment]
Can we get a rebase on this? I got a conflict locally.

**Comment by ojeytonwilliams** [comment]
Sure.  I don't know why GitHub didn't flag it up, but it should be fine now.

**Review by moT01 — COMMENTED** [review]
I was getting this warning with `npm run build`...
```sh
warn Unsafe builtin method was used, future builds will need to rebuild all pages
warn WebpackError: Unsafe builtin usage https.Agent
    at @freecodecamp/client/node_modules/algoliasearch/src/server/builds/get-agent.js:69:1
    at @freecodecamp/client/node_modules/algoliasearch/src/server/builds/get-agent.js:24:1
    at @freecodecamp/client/node_modules/algoliasearch/src/server/builds/node.js:85:1
    at @freecodecamp/client/node_modules/algoliasearch/src/server/builds/node.js:68:1
    at @freecodecamp/client/src/components/search/WithInstantSearch.js:29:21
    at @freecodecamp/client/webpack/bootstrap:19:1
    at @freecodecamp/client/webpack/bootstrap:19:1
    at @freecodecamp/client/webpack/bootstrap:19:1
    at @freecodecamp/client/webpack/bootstrap:19:1
    at @freecodecamp/client/webpack/bootstrap:19:1
    at @freecodecamp/client/.cache/api-runner-ssr.js:11:15
    at @freecodecamp/client/webpack/bootstrap:19:1

  67 |     });
  68 |   } else if (protocol === 'https:') {
> 69 |     keepAliveAgent = new https.Agent({
     | ^
  70 |       keepAlive: true,
  71 |       maxSockets: Infinity
  72 |     });
```

Nobody else mentioned it, so maybe it's something on my end. Although, I didn't see it when building `main`. It doesn't seem to affect anything, the site still builds and everything seems to work. Not sure if this is something we want to look into or hold up this PR for. Other than that, I played around with it quite a bit, and it LGTM 🎉

**Comment by ojeytonwilliams** [comment]
@moT01 what I've noticed is that Gatsby doesn't clear the cache before building and this can be the source of some weird errors.  Could you try again after running `npm run clean:client`?

**Comment by moT01** [comment]
Just for record, I tried a number of things.

Same warning after `npm run clean:client`
or manually deleting the `client/.cache` and `client/public` folders

I'm on High Sierra 10.13.6
Node 14.4.0
tried npm 6.14.5 and 7.7.4

Found this https://github.com/algolia/algoliasearch-client-javascript/issues/1261

Tried two different sets of algolia keys, and the non-keys from the sample.env

Upgraded the algoliasearch package and got a similar error:
```sh
warn Unsafe builtin method was used, future builds will need to rebuild all pages
warn WebpackError: Unsafe builtin usage http.Agent
    at @freecodecamp/client/node_modules/@algolia/requester-node-http/dist/requester-node-http.esm.js:9:1
    at @freecodecamp/client/webpack/bootstrap:19:1
    at @freecodecamp/client/node_modules/algoliasearch/dist/algoliasearch.cjs.js:10:25
    at @freecodecamp/client/webpack/bootstrap:19:1
    at @freecodecamp/client/node_modules/algoliasearch/index.js:2:23
    at @freecodecamp/client/webpack/bootstrap:19:1
    at @freecodecamp/client/webpack/bootstrap:19:1
    at @freecodecamp/client/webpack/bootstrap:19:1
    at @freecodecamp/client/webpack/bootstrap:19:1
    at @freecodecamp/client/webpack/bootstrap:19:1
    at @freecodecamp/client/webpack/bootstrap:19:1

   7 | /* eslint functional/prefer-readonly-type: 0 */
   8 | const agentOptions = { keepAlive: true };
>  9 | const defaultHttpAgent = new Agent(agentOptions);
     | ^
  10 | const defaultHttpsAgent = new Agent$1(agentOptions);
  11 | function createNodeHttpRequester({ agent: userGlobalAgent, httpAgent: userHttpAgent, httpsAgent: userHttpsAgent,
requesterOptions = {}, } = {}) {
  12 |     const httpAgent = userHttpAgent || userGlobalAgent || defaultHttpAgent;

warn WebpackError: Unsafe builtin usage https.Agent
    at @freecodecamp/client/node_modules/@algolia/requester-node-http/dist/requester-node-http.esm.js:10:1
    at @freecodecamp/client/webpack/bootstrap:19:1
    at @freecodecamp/client/node_modules/algoliasearch/dist/algoliasearch.cjs.js:10:25
    at @freecodecamp/client/webpack/bootstrap:19:1
    at @freecodecamp/client/node_modules/algoliasearch/index.js:2:23
    at @freecodecamp/client/webpack/bootstrap:19:1
    at @freecodecamp/client/webpack/bootstrap:19:1
    at @freecodecamp/client/webpack/bootstrap:19:1
    at @freecodecamp/client/webpack/bootstrap:19:1
    at @freecodecamp/client/webpack/bootstrap:19:1
    at @freecodecamp/client/webpack/bootstrap:19:1

   8 | const agentOptions = { keepAlive: true };
   9 | const defaultHttpAgent = new Agent(agentOptions);
> 10 | const defaultHttpsAgent = new Agent$1(agentOptions);
     | ^
  11 | function createNodeHttpRequester({ agent: userGlobalAgent, httpAgent: userHttpAgent, httpsAgent: userHttpsAgent,
requesterOptions = {}, } = {}) {
  12 |     const httpAgent = userHttpAgent || userGlobalAgent || defaultHttpAgent;
  13 |     const httpsAgent = userHttpsAgent || userGlobalAgent || defaultHttpsAgent;
```

**Comment by ojeytonwilliams** [comment]
It took me a while, but I finally realised I wasn't seeing the problem because I'm using dummy keys (from sample.env) for Algolia.  Thanks for helping me figure that out, Tom.

The latest version of Gatsby, which includes https://github.com/gatsbyjs/gatsby/pull/30216, suppresses the warnings.  So, I think we should just trust their judgement, use the latest version and keep an eye on search.

**Review by moT01 — APPROVED** [review]
LGTM 🎉 The warning went away with the latest commit. I built it again, and played around with it some more - everything seems to be working.

**Review by naomi-lgbt — APPROVED** [review]
This looks good to me.

I tested with English and `npm run build` environment, and everything appeared to work as desired.

I tested with Espanol and `npm run develop` environment, and everything appeared to work as desired.

**Pull request merged**
