### PR TITLE
fix(curriculum): add test to check if the original variable is edited

### LINKED ISSUE #43788: Remove whitespace challenge can be passed by editing variable directly
## Affected page

https://www.freecodecamp.org/learn/javascript-algorithms-and-data-structures/regular-expressions/remove-whitespace-from-start-and-end

## Your code

```
let hello = "Hello, World!";
let wsRegex = /change/; // Change this line
let result = hello; // Change this line
```

## Expected behavior

The challenge shouldn't pass as the user is directly editing the `hello` variable. Another test should be added to this [file](https://github.com/freeCodeCamp/freeCodeCamp/blob/main/curriculum/challenges/english/02-javascript-algorithms-and-data-structures/regular-expressions/remove-whitespace-from-start-and-end.md) to check if the user has changed the value of `hello` or not.

## Bug report source
https://forum.freecodecamp.org/t/remove-whitespace-from-start-and-end-challenge-bug/480586

### PR DESCRIPTION
**Pull request by Prathamesh010**
Checklist:

- [x] I have read [freeCodeCamp's contribution guidelines](https://contribute.freecodecamp.org).
- [x] My pull request has a descriptive title (not a vague title like `Update index.md`)
- [x] My pull request targets the `main` branch of freeCodeCamp.
- [x] I have tested these changes either locally on my machine, or GitPod.

Closes #43788

### CODE REVIEW

**Review by Nirajn2311 — DISMISSED** [review]
LGTM 👍

**Review by naomi-lgbt — DISMISSED** [review]
Small wording tweak.

**Comment by Prathamesh010** [comment]
I have applied the given suggestion. Please check.

**Review by gikf — APPROVED** [review]
Looks good! :+1:

**Review by Sembauke — APPROVED** [review]

**Pull request merged**
