### PR TITLE
fix(client): allow editor links for Py submissions

### LINKED ISSUE #41033: i18n-launch: SolutionForm disallowing Python projects
image

Included in the i18n launch was PR #40225 which added validation that campers are submitting the link to the live URL for their backend projects. This is great for the Node.js projects, but has broken the ability to submit Python projects. 

This should be adjusted to pull the Python projects out of the scope of this validation.

Related forum post: https://forum.freecodecamp.org/t/problem-submitting-solution/445429?u=nhcarrigan

### PR DESCRIPTION
**Pull request by ShaunSHamilton**
Checklist:

- [x] I have read [freeCodeCamp's contribution guidelines](https://contribute.freecodecamp.org).
- [x] My pull request has a descriptive title (not a vague title like `Update index.md`)
- [x] My pull request targets the `main` branch of freeCodeCamp.
- [x] All the files I changed are in the same world language, for example: only English changes, or only Chinese changes, etc.

Closes #41033 

Sorry, again 🙈

### CODE REVIEW

**Comment by ShaunSHamilton** [comment]
This was a bit rushed. So, it is likely not the best way to pass the specific data I am looking for, but it works as far as I can see.

**Review by ojeytonwilliams — DISMISSED** [review]
LGTM :+1: 

One thing I noticed, presumably unrelated to this PR, was that we strip off the `#main.py` from the URL.  Is that intentional?

**Comment by ShaunSHamilton** [comment]
> Is that intentional?

<s>Nothing I wrote intentionally does this</s> -> Nothing I intentionally wrote does this.

I assume this is done by the `normalise-url` library. However, I do not actually know what this is doing.

**Comment by ShaunSHamilton** [comment]
I forgot to add the `isEditorLinkAllowed` prop to the propTypes in `FormFields.js`. I am going to add that, now.

**Comment by ojeytonwilliams** [comment]
Thanks for taking a look at that.  I know it's not a result of your changes, I just spotted it while I was QAing.

**Review by raisedadead — APPROVED** [review]

**Comment by ShaunSHamilton** [comment]
@raisedadead Thanks, for that. Is it possible for this to be cherry-picked into production? Or, are we likely going to need to wait ~1 week?

**Comment by raisedadead** [comment]
Hi @ShaunSHamilton 

We are going to be deploying daily to production now for a bit in light of the major release and as the activity reduces, we will adjust the deployments schedules.

Also please note you can request a deployment to prod anytime in case of emergencies and showstopper issues like these.

I will land this on prod in few hours from now.

**Comment by raisedadead** [comment]
@ShaunSHamilton I just pushed this to staging, should be available for test in ~45 mins from now. Once I validate it there I will push further to prod right after.

**Comment by ShaunSHamilton** [comment]
@raisedadead Thank you, for letting me know. I will check up on it thoroughly, in about an hour.

**Comment by raisedadead** [comment]
Staging is ready. I tested the fix.

**Comment by nhcarrigan** [comment]
Gave it a poke on staging. Was able to submit the edit URL for the python arithmetic formatter with no issue, and generated the flash message as expected when I tried to submit that same URL for the node metric-imperial converter.

**Pull request merged**
