### PR TITLE
Changed the wording for Rule 3 in build a personal portfolio challenge 

### LINKED ISSUE #8340: Better project rule wording
#### Challenge Name

https://www.freecodecamp.com/challenges/build-a-personal-portfolio-webpage
(this applies to tribute page and portfolio page projects)

#### Issue Description

Some users in the help chat got confused by the project rule:
_You may use your own CSS and frameworks other than Bootstrap._
They thought you must not use Bootstrap, due to ambigue wording. I'd suggest to use something like "You can use Bootstrap, or any other framework of your choice".

### PR DESCRIPTION
**Pull request by BrianZ1**
#### Pre-Submission Checklist

- [X] Your pull request targets the `staging` branch of FreeCodeCamp.
- [X] Branch starts with either `fix/`, `feature/`, or `translate/` (e.g. `fix/signin-issue`)
- [X] You have only one commit (if not, [squash](https://github.com/FreeCodeCamp/FreeCodeCamp/wiki/git-rebase#squashing-multiple-commits-into-one) them into one commit).
- [X] All new and existing tests pass the command `npm run test-challenges`. Use `git commit --amend` to amend any fixes.
#### Type of Change

- [X] Bug fix (non-breaking change which fixes an issue)

*It was a wording change, but this seemed like the best match.
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] Add new translation (feature adding new translations)
#### Checklist:

- [X] Tested changes locally.
- [X] Closes currently open issue (`Closes #XXXX`): Closes #8340
#### Description

I changed the wording of rule 3 from "You may use your own CSS and frameworks other than Bootstrap" to "You can use Bootstrap, or any other framework of your choice." as suggested.

### CODE REVIEW

**Comment by erictleung** [comment]
@BrianZ1 thanks for the PR! One small change though, can you change your git commit message to something like `Fixed wording ambiguity for Personal Portfolio`? We ask that issue numbers not be in the commit message. Keep the issue number within the checklist above though. Thanks!

**Comment by BrianZ1** [comment]
I changed the message and I think it worked

**Comment by erictleung** [comment]
@BrianZ1 thanks again! One more tiny change, can you add in a period at the end of Rule 3 right before the quotation?

```
"<strong>Rule #3:</strong> You can use Bootstrap, or any other framework of your choice.",
```

**Comment by BrianZ1** [comment]
Uh, should I squash the commits too?

**Comment by erictleung** [comment]
@BrianZ1 yes. Thanks!

**Comment by BrianZ1** [comment]
I'm not entirely sure what I did, but I'm trying to fix it right now

**Comment by erictleung** [comment]
@BrianZ1 you can reach out to the [Contributors Help](https://gitter.im/FreeCodeCamp/HelpContributors) if you have any questions.

**Comment by BrianZ1** [comment]
Do you mind if I start over from the beginning with a new pull request tomorrow morning? I feel like I messed up too much and starting over will be easier.

**Comment by erictleung** [comment]
@BrianZ1 one quick question, are you using the command line to git commit? If so, I think I have the sequence of commands to help you out. You haven't messed up too much. Thanks for being persistent.

**Comment by BrianZ1** [comment]
Yea, I am. I've been trying to use the rebase command and using squash, but I keep getting errors with that. Any help would be appreciated, but I'm too tired to think right now; I'll try it tomorrow morning if that's alright.

**Comment by erictleung** [comment]
@BrianZ1 no worries. Whenever you get to it, here are the commands you can run that'll hopefully fix things. I checked out this PR and tested it myself. I'm assuming you've got the remote (`upstream`) and your local working branch (`staging`) setup correctly.

```shell
git checkout fix/rule-wording 
git pull --rebase upstream staging
git rebase staging
git log # check if the last two commits are yours, if so proceed
git reset HEAD~2
git add basic-ziplines.json
git commit -m "	Fix wording ambiguity for Personal Portfolio"
git push origin fix/rule-wording --force
```

**Comment by BrianZ1** [comment]
Hey, thanks for all the help. I'm not sure why it still shows the commit message of someone else though; will that be a problem? If it is, how would I go about fixing it?

**Comment by erictleung** [comment]
@BrianZ1 yeah, it shouldn't say you've committed with another person, as that other commit has already been added. I'm out of ideas for how to fix it as I just tried fixing it again and it shows up for me too that you have that other commit. It might easier to close this PR and make another one. Visit the Gitter [Contributors Help](https://gitter.im/FreeCodeCamp/HelpContributors) if you have any more questions. Thanks!

**Comment by BrianZ1** [comment]
It only shows that I have one commit now, so I think whatever I did worked. Just to be sure, there's no way for me to change what the previous person commited, even if it doesn't show up anymore, right?

**Comment by raisedadead** [comment]
#### :sparkles: :sparkles: **LGTM.** :sparkles: :sparkles: 

Thanks @BrianZ1 and @erictleung .

**Pull request merged**
