### PR TITLE
Reorder projects and challenges from newest to oldest

### PR DESCRIPTION
**Pull request by mtaner**
#### Pre-Submission Checklist
- [x] Your pull request targets the `staging` branch of FreeCodeCamp.
- [x] Branch starts with either `fix/`, `feature/`, or `translate/` (e.g. `fix/signin-issue`)
- [x] You have only one commit (if not, [squash](http://forum.freecodecamp.com/t/how-to-squash-multiple-commits-into-one-with-git/13231) them into one commit).
- [x] All new and existing tests pass the command `npm test`. Use `git commit --amend` to amend any fixes.

#### Type of Change
- [ ] Small bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds new functionality)
- [ ] Breaking change (fix or feature that would change existing functionality)
- [ ] Add new translation (feature adding new translations)

#### Checklist:
- [x] Tested changes locally.
- [x] Closes currently open issue: Closes: #10335

#### Description
Reverse the order of the projects and challenges displayed.

### CODE REVIEW

**Comment by Bouncey** [comment]
@mtaner thanks for the PR.

I am putting this on hold for now whilst we wait for opinions

**Comment by marhyorh** [comment]
# LGTM! :+1:

**Comment by atjonathan** [comment]
@QuincyLarson, tagging for approval.

**Comment by ygt-abooth** [comment]
LGTM 😄

**Comment by raisedadead** [comment]
Tested, and LGTM. @mtaner thanks and sorry about the delay in QA! 😄 

/cc @QuincyLarson I am merging. Please let me know for changes if any.

**Comment by QuincyLarson** [comment]
Awesome - thanks for submitting this PR, @mtaner and thanks to @ygt-abooth and @raisedadead for QA'ing it. Excited to get this live when we ship staging 😄

**Pull request merged**
