### PR TITLE
Grammatical error

### PR DESCRIPTION
**Pull request by MattSchwartzkopf**
- [ x] I have read [freeCodeCamp's contribution guidelines](https://github.com/freeCodeCamp/freeCodeCamp/blob/master/CONTRIBUTING.md).
- [ x] My pull request has a descriptive title (not a vague title like `Update index.md`)
- [ x] My pull request targets the `master` branch of freeCodeCamp.
- [x ] None of my changes are plagiarized from another source without proper attribution.
- [ x] My article does not contain shortened URLs or affiliate links.

If your pull request closes a GitHub issue, replace the XXXXX below with the issue number.

Closes #76ce5fb

### CODE REVIEW

**Review by RandellDawson — APPROVED** [review]

**Comment by RandellDawson** [comment]
LGTM

Closed and reopened PR to resolve a specific Travis build failure.

**Comment by RandellDawson** [comment]
LGTM

Closed and reopened PR to resolve a specific Travis build failure.

**Comment by QuincyLarson** [comment]
LGTM - @RandellDawson could you merge once build passes?

**Comment by RandellDawson** [comment]
Congrats @MattSchwartzkopf  on your first pull request (PR)! 🎉

Thank you for your contribution to the page! 👍
We're happy to accept these changes, and look forward to future contributions. 📝

**Pull request merged**
