### PR TITLE
fix: third-party cookie issues with CodeAlly login

### PR DESCRIPTION
**Pull request by moT01**
Opening this up for review, but have also blocked it. I believe we want to synchronize deploys with CodeAlly on this one.

- [x] I have read [freeCodeCamp's contribution guidelines](https://contribute.freecodecamp.org).
- [x] My pull request has a descriptive title (not a vague title like `Update index.md`)
- [x] My pull request targets the `main` branch of freeCodeCamp.
- [x] I have tested these changes either locally on my machine, or GitPod.

Closes #https://github.com/freeCodeCamp/CodeAlly-CodeRoad-freeCodeCamp/issues/42

### CODE REVIEW

**Review by ojeytonwilliams — APPROVED** [review]
LGTM :+1:

**Comment by raisedadead** [comment]
Per discussion, this is pending an orchestrated deployment with the CodeAlly team.

**Comment by moT01** [comment]
Alright, we're clear to deploy this at will.

**Comment by AdamZaczek** [comment]
Looks good 🔥

**Comment by AdamZaczek** [comment]
Looks good 🔥 We're ready to test this. Our changes are already live.

**Review by raisedadead — APPROVED** [review]

**Pull request merged**
