### PR TITLE
Blender beginners index.md

### PR DESCRIPTION
**Pull request by dkempdesigns**
Additional information to get beginners started.

- [x] I have read [freeCodeCamp's contribution guidelines](https://github.com/freeCodeCamp/freeCodeCamp/blob/master/CONTRIBUTING.md).
- [x] My pull request has a descriptive title (not a vague title like `Update index.md`)
- [x] My pull request targets the `master` branch of freeCodeCamp.
- [x] None of my changes are plagiarized from another source without proper attribution.
- [x] My article does not contain shortened URLs or affiliate links.

If your pull request closes a GitHub issue, replace the XXXXX below with the issue number.

Closes #XXXXX

### CODE REVIEW

**Comment by dkempdesigns** [comment]
Hello Randell,

Please explain further how my submission applies to any of the values in
#2. I simply expanded on the topic as I felt it need more clarification for
those new to the topic. I added original content and links to helpful sites
(not paid, affiliate or in any other way spam).

As I am new to this process, please help me understand fully so that I can
get the most from participating. The email you sent is not clear to me on
how I have somehow violated the values.

Thank you
Dorthea Kemp

**Comment by RandellDawson** [comment]
All 5 of the checkboxes must be checked.  Your PR was marked invalid almost automatically, becuase you did not check box #2 (shown below) and do as it stated.
```
 My pull request has a descriptive title (not a vague title like Update index.md)
```
Update your title and checkoff that box.  These help us understand that you have read the requirements.  Commits should have short but useful descriptions of what you are doing.  It helps us in the review process.  With the sheer volume of PRs we are getting right now, we focus on the ones where the conttributor has made the effort to follow the process.  You have no idea how many of the "update index.md" are just a bot making a one character change.

Just update your PR title and tag me and I will review it personally.

**Comment by dkempdesigns** [comment]
Thanks for the response. I actually tried to update my title, but when I
went back, there was no way to edit it. Maybe page was still updating.
I will go in today and update.

Thank you,
Dorthea

**Comment by dkempdesigns** [comment]
Hi, I updated the title but did not know how to tag you.
Not sure how to refer you, but this is the page that lists my update;
https://github.com/freeCodeCamp/freeCodeCamp/pull/20613

Thanks

**Pull request closed without merging**
