### PR TITLE
feat(tools): add LightHouse CI to the GitHub workflows

### LINKED ISSUE #39354: Add LightHouse to GitHub workflows
**Is your feature request related to a problem? Please describe.**

As of now, the FCC site's performance metrics are not measured by any sort of site analyzing tools. But it is becoming increasingly important to keep an eye out on the UI/UX, a11y etc scores.

**Google Webmasters** announced on May 28, 2020 that they'll be starting to incorporate [Core Web Vitals](https://web.dev/vitals/) to the SEO and site ranking. Here's [the link](https://twitter.com/googlewmc/status/1266036796485332992) to the announcement. That's not all, Google developers announced on [Web Dev Live](https://web.dev/live/)(Web Dev Live is a Google dev conference of sorts in replacement of Google IO 2020 due to worldwide pandemic) that starting from next year they'll be adding more **Performance Metrics** like these and they recommend to use LightHouse to start optimizing from now on (Click [here](https://youtu.be/yDHfrhCGFQw?t=284) to learn more).

**Describe the solution you'd like**

As such, it's crucial to give importance to a site's Core Web Vitals scores and optimize them. There's no better way to do so than using LightHouse. LightHouse is a Google developed site analyzing tool that'll score a site for it's **Performance**, **Accessibility**, **SEO** etc criterias. LightHouse measures _Core Web Vitals_ and shows the results.  LightHouse will also point out the problems in these sectors and it'll show the steps necessary to fix them.

### PR DESCRIPTION
**Pull request by Twaha-Rahman**
Checklist:

- [x] I have read [freeCodeCamp's contribution guidelines](https://contribute.freecodecamp.org).
- [x] My pull request has a descriptive title (not a vague title like `Update index.md`)
- [x] My pull request targets the `master` branch of freeCodeCamp.
- [x] All the files I changed are in the same world language, for example: only English changes, or only Chinese changes, etc.

Closes #39354

This PR adds [LightHouse](https://developers.google.com/web/tools/lighthouse) CI to the Github workflows. LightHouse CI is a Google developed site analyzer. Please read #39354 to understand the reasoning behind the PR.

### CODE REVIEW

**Review by raisedadead — CHANGES_REQUESTED** [review]
We would rather make this run once every other week (14 days). Checking LH scores every push is quite moot other than adding delays to the TAT on a development. 

The likelilness for the pages changing is quite low in each push. 

We can get this to shorter durations when needed. Also GitHub now allows workflow events too (for manual triggers). We would like to see that added as an option as well because it would fit the need of on-off runs too.

**Comment by Twaha-Rahman** [comment]
> We would rather make this run once every other week (14 days). Checking LH scores every push is quite moot other than adding delays to the TAT on a development.
> 
> The likelilness for the pages changing is quite low in each push.
> 
> We can get this to shorter durations when needed. Also GitHub now allows workflow events too (for manual triggers). We would like to see that added as an option as well because it would fit the need of on-off runs too.

We can easily make the tests to run every 14 days or so (or even manually), that shouldn't be a problem.

**Comment by Twaha-Rahman** [comment]
I just changed the workflow to run on every 14th day with Cron job. Any thoughts?

**Comment by raisedadead** [comment]
Looks good so far, any progress in enabling the one-off runs via workflow events?

**Comment by Twaha-Rahman** [comment]
@raisedadead Triggering manual workflow can be done with a simple POST request to the GitHub API. Is this what you're looking for?

https://docs.github.com/en/actions/reference/events-that-trigger-workflows#manual-events

**Comment by Twaha-Rahman** [comment]
Done! Added the manual workflow triggering feature to the workflow.

You can now run the workflow manually by following these steps here ->

https://docs.github.com/en/actions/configuring-and-managing-workflows/configuring-a-workflow#manually-running-a-workflow

**Review by raisedadead — APPROVED** [review]
Lets give this a try.

**Comment by raisedadead** [comment]
It was showing up in the list, and I realised we had a similar name in the past. I added a commit on master to resolve it. Executing a run now.

**Comment by raisedadead** [comment]
Looks like its failing. Although I was able to run the workflow manually. Can you investigate?

**Comment by Twaha-Rahman** [comment]
> Looks like its failing. Although I was able to run the workflow manually. Can you investigate?

Sure. I'm on it.

**Comment by Twaha-Rahman** [comment]
@raisedadead I found the reason why the workflow failed.

According to the workflow run, it was clear that NPM install failed cause it was not finding a package in the package registry.

image

So I did I quick Google search and my suspicion was right. NPM was down at that time, that's why the workflow failed. (I think other builds in the CI for other PRs would fail too as they won't be able to install the dependency.)

image

(Link to [NPM status](https://status.npmjs.org/))

So... just run the workflow again and it should work just fine.

**Pull request merged**
