### PR TITLE
typo fix

### PR DESCRIPTION
**Pull request by Siddharth1698**
- [x] I have read [freeCodeCamp's contribution guidelines](https://github.com/freeCodeCamp/freeCodeCamp/blob/master/CONTRIBUTING.md).
- [x] My pull request has a descriptive title (not a vague title like `Update index.md`)
- [x] My pull request targets the `master` branch of freeCodeCamp.
- [x] None of my changes are plagiarized from another source without proper attribution.
- [x] All the files I changed are in the same world language (for example: only English changes, or only Chinese changes, etc.)
- [x] My changes do not use shortened URLs or affiliate links.

Closes #XXXXX

### CODE REVIEW

**Review by RandellDawson — APPROVED** [review]

**Comment by Siddharth1698** [comment]
Hii.. @RandellDawson @QuincyLarson  I would love to be a part of freecodecamp. Please help me add me as a part of the freecodecamp community. Thanks

**Comment by raisedadead** [comment]
Hi @Siddharth1698 you already are a part of the community. Thanks for opening up this pull request. Join us here [Contributors Chat room](https://gitter.im/FreeCodeCamp/Contributors)

**Comment by moT01** [comment]
I'm not sure there's a typo here - it is defined in [webster's dictionary](https://www.merriam-webster.com/dictionary/scatterplot) along with elsewhere on the web. Also, there is no space in the word on our `learn` page or on the page for the challenge itself. So I'm thinking we can probably leave this as is.

**Comment by RandellDawson** [comment]
@QuincyLarson Since this is the main README.md file, what are your thoughts?  I searched also across various dictionaries and found it to be about 50/50 regarding the space between "scatter" and "plot".  I think this is really your decision.

**Comment by raisedadead** [comment]
I agree, we should leave it as is. Thanks a lot @Siddharth1698 for preparing the PR. We have lots of other issues that we could use your help with.

Thanks and happy contributing.

**Pull request closed without merging**
