### PR TITLE
removed console.log() from execute-challenge-saga file for production

### PR DESCRIPTION
**Pull request by rootFaheem**
Checklist:

- [x] I have read [freeCodeCamp's contribution guidelines](https://contribute.freecodecamp.org).
- [x] My pull request has a descriptive title (not a vague title like `Update index.md`)
- [x] My pull request targets the `master` branch of freeCodeCamp.
- [x] All the files I changed are in the same world language, for example: only English changes, or only Chinese changes, etc.

Closes #XXXXX

### CODE REVIEW

**Review by ojeytonwilliams — CHANGES_REQUESTED** [review]
Hi @rootFaheem, that console log should be there.  The idea is that a user should be able to see all the errors in the browser console, if they're interested.

I think a comment would help clarifying that, though.  How about the following?

```js
// Report the error to the browser console...
console.log(err)
// ...and the editor console
yield put(updateConsole(escape(err)));
```

**Comment by ojeytonwilliams** [comment]
We currently show the errors in the panel below the editor and have the pass/failing state to in the tool panel (on the left).  So, to some extent, we already do this.

> Because we can't expect a user to check the browser's console for the errors, especially in the production.

The browser console is a useful tool and one we [encourage people to use](https://www.freecodecamp.org/learn/javascript-algorithms-and-data-structures/debugging/use-the-javascript-console-to-check-the-value-of-a-variable).  The idea behind the log below the editor is to give people most of the information they need, with the understanding that they should check the browser console if they need more detail.

**Comment by ojeytonwilliams** [comment]
Having said all that, improvements are always welcome.  If you have something in mind, it would be great if you could flesh it out in an issue. Then we could discuss it further.

**Comment by rootFaheem** [comment]
Definitely, I will create an issue for the same, that would be a great place to start.

Also, I am closing this, as the issue has been resolved.

**Pull request closed without merging**
