### PR TITLE
Add a settings skeleton

### LINKED ISSUE #14612: Replace settings loading wave with skeleton view
We currently use a loading icon for the setting's page. I'd like to see this replaced with a skeleton page.

see: https://github.com/freecodecamp/freecodecamp/blob/staging/common/app/routes/settings/components/Settings.jsx#L12

Check out this article for more on skeletons: https://www.mobify.com/designing-appearance-speed/

### PR DESCRIPTION
**Pull request by Bouncey**
#### Pre-Submission Checklist

- [x] Your pull request targets the `staging` branch of freeCodeCamp.
- [x] Branch starts with either `fix/`, `feature/`, or `translate/` (e.g. `fix/signin-issue`)
- [x] You have only one commit (if not, [squash](http://forum.freecodecamp.com/t/how-to-squash-multiple-commits-into-one-with-git/13231) them into one commit).
- [x] All new and existing tests pass the command `npm test`. Use `git commit --amend` to amend any fixes.

#### Type of Change

- [ ] Small bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds new functionality)
- [ ] Breaking change (fix or feature that would change existing functionality)
- [ ] Add new translation (feature adding new translations)

#### Checklist:

- [x] Tested changes locally.
- [x] Closes currently open issue (replace XXXX with an issue no): Closes #14612

#### Description

Adds a skeleton view of the settings page. Removes `SKWave.jsx`

### CODE REVIEW

**Comment by raisedadead** [comment]
I tested this, and it looks great.. for starters, how are we planning this animation duration to be dynamic?

**Comment by Bouncey** [comment]
Does it need to be dynamic? And in response to what?

**Comment by raisedadead** [comment]
> Does it need to be dynamic? And in response to what?

Well I think this could be extended to the public profile of the user, which would have their complete portfolio?

Or that's something completely unrelated?

**Comment by Bouncey** [comment]
The profile page is not reactified yet. It's an interesting idea about displaying a campers portfolio though. Would definitely require a separate issue/PR

**Comment by BerkeleyTrue** [comment]
Code LGTM. @Bouncey Thanks!

**Pull request merged**
