### PR TITLE
fix: broken get a hint links [english]

### PR DESCRIPTION
**Pull request by moT01**
This renames guide folders to align with lesson titles by changing the dashes(`-`) back to periods(`.`) where they have been previously replaced.

- [x] I have read [freeCodeCamp's contribution guidelines](https://github.com/freeCodeCamp/freeCodeCamp/blob/master/CONTRIBUTING.md).
- [x] My pull request has a descriptive title (not a vague title like `Update index.md`)
- [x] My pull request targets the `master` branch of freeCodeCamp.
- [x] None of my changes are plagiarized from another source without proper attribution.
- [x] All the files I changed are in the same world language (for example: only English changes, or only Chinese changes, etc.)
- [x] My changes do not use shortened URLs or affiliate links.

Related to https://github.com/freeCodeCamp/freeCodeCamp/issues/35155

Reviewers, make sure there are no other PR's to these files before merging. Check the [contributor tools](https://contribute.freecodecamp.org/dashboard/).  Use the `Filename` Search option and search for the old filename.

### CODE REVIEW

**Comment by RandellDawson** [comment]
Reviewers be aware you should not attempt to merge this PR before validating there are no other PRs affecting the old file name, because you will create a merge conflict on the PR.

For example, PR was created of the 6 files on this PR, the following PRs have changes to the old filename.

https://github.com/freeCodeCamp/freeCodeCamp/pull/29731

**Comment by lipis** [comment]
@RandellDawson Do you guys have a tool or something that checks automatically other PRs for affected files? How does it work? #justcurious

**Comment by moT01** [comment]
@lipis, there's a link the description up there to contributor tools - it can list all the PR's by files changed, or you can search for files that have an open PR.

**Comment by lipis** [comment]
RTFM :)

**Comment by RandellDawson** [comment]
LGTM - I first checked there are currently no open PRs making changes to the old filename. I was also finally able to test this locally and confirm that the 6 challenges now can correctly link to these corresponding Guide articles when clicking the "Get a Hint" link.

**Comment by moT01** [comment]
Thanks for reviewing all these @RandellDawson!

**Comment by RandellDawson** [comment]
That review took quite a long time.

**Pull request merged**
