### PR TITLE
Added BASH books

### PR DESCRIPTION
**Pull request by amitech**
Added links of BASH and unix programming books

- [x] I have read [freeCodeCamp's contribution guidelines](https://github.com/freeCodeCamp/freeCodeCamp/blob/master/CONTRIBUTING.md).
- [x] My pull request has a descriptive title (not a vague title like `Update index.md`)
- [x] My pull request targets the `master` branch of freeCodeCamp.
- [x] None of my changes are plagiarized from another source without proper attribution.
- [x] My article does not contain shortened URLs or affiliate links.

If your pull request closes a GitHub issue, replace the XXXXX below with the issue number.

Closes #XXXXX

### CODE REVIEW

**Comment by lynxlynxlynx** [comment]
Looks ok, but adding readable link text would improve it. Check the previous entries.

**Comment by amitech** [comment]
@lynxlynxlynx thanks, I made suggested changes.

**Comment by amitech** [comment]
Corrected it now. Thanks.

**Comment by lynxlynxlynx** [comment]
LGTM

**Pull request merged**
