### PR TITLE
Fixed mismatch between text and practice projects sequence [Issue #47740]

### LINKED ISSUE #47740: Mismatch between text and practice projects sequence
https://github.com/freeCodeCamp/freeCodeCamp/blob/main/curriculum/challenges/english/14-responsive-web-design-22/learn-css-variables-by-building-a-city-skyline/5d822fd413a79914d39e98d5.md

In this step it says 
> You will learn about [flexbox] in more detail on another project.

but the flexbox practice project comes before this one. This has to be removed or changed to indicate a previosu project.

### PR DESCRIPTION
**Pull request by rahulraheja49**
Checklist:

- [ x] I have read [freeCodeCamp's contribution guidelines](https://contribute.freecodecamp.org).
- [ x] My pull request has a descriptive title (not a vague title like `Update index.md`)
- [ x] My pull request targets the `main` branch of freeCodeCamp.
- [ x] I have tested these changes either locally on my machine, or GitPod.

Closes #47740

I have linked the previous challenge in which we learnt flexbox.

### CODE REVIEW

**Comment by ieahleen** [comment]
Thank you for your PR. Please notice that the issue was labeled with stats: discussing; please look at issues with labels https://github.com/freeCodeCamp/freeCodeCamp/labels/first%20timers%20only or https://github.com/freeCodeCamp/freeCodeCamp/labels/help%20wanted

**Comment by rahulraheja49** [comment]
Extremely sorry, it's my first time contributing and I jumped the gun when I saw the issue

**Comment by raisedadead** [comment]
As a new contributor, we encourage you to read our contributing guidelines. 

We expect our contributors to be aware of the process specific to this project. Following the guidelines religiously earns you the respect of fellow maintainers and saves everyone time.

Some examples of this are:

1. Make sure you are not editing off of GitHub (while you can, it's not a good idea).
2. Makes sure you actually follow the PR checklist and not just tick things off; we won't take you seriously otherwise.
3. Use the correct way to link PRs in the description of the PR by updating the `XXXXXX`.
4. ... and similar things.

We appreciate you taking the time to help us, and we hope to see more contributions from you.

Cheers & Happy Coding!

**Comment by raisedadead** [comment]
The orginal thread has not reached consensus. Closing

**Pull request closed without merging**
