### PR TITLE
fix: add tests for metric-imperial-converter (infosec tests)

### PR DESCRIPTION
**Pull request by Aadhar3**
- [x] I have read [freeCodeCamp's contribution guidelines](https://github.com/freeCodeCamp/freeCodeCamp/blob/master/CONTRIBUTING.md).
- [x] My pull request has a descriptive title (not a vague title like `Update index.md`)
- [x] My pull request targets the `master` branch of freeCodeCamp.
- [x] None of my changes are plagiarized from another source without proper attribution.
- [x] All the files I changed are in the same world language (for example: only English changes, or only Chinese changes, etc.)
- [x] My changes do not use shortened URLs or affiliate links.

Contributes to #37185

I added tests to Information Security and Quality Assurance Projects - Metric-Imperial Converter
I ran this on gitpod, and it seems to build and work there. However, i am noticing some inconsistencies with the assert.equal statement. I changed some tests intentionally while testing so that they would fail, and it failed once, but then after some time they all passed regardless of what was in the assert statements.

### CODE REVIEW

**Review by thecodingaviator — COMMENTED** [review]
I wonder why all the spaces seem different. The spacebar character has been replaced by some other whitespace.

**Comment by RandellDawson** [comment]
@Aadhar3 For some reason, you have replaced several space characters (ASCII code 32) with non-breaking space characters (ASCII code 160) that creates invalid yaml syntax in the frontmatter of the challenge.  This is causing the failure in Travis .  Please revert all of these non-breaking spaces back to space characters.

Thank you.

**Comment by RandellDawson** [comment]
@Aadhar3 You still have the same problem.  You have non-breaking space characters instead of normal space characters scattered through your changes.  I suggest closing this PR and creating a new branch from master and try again.

**Review by thecodingaviator — CHANGES_REQUESTED** [review]
Please update/close as per comments above

**Comment by Aadhar3** [comment]
> @Aadhar3 You still have the same problem. You have non-breaking space characters instead of normal space characters scattered through your changes. I suggest closing this PR and creating a new branch from master and try again.

Hi, I am not sure exactly what is happening but that sounds like a good idea. I will close this PR and branch off master again.

**Pull request closed without merging**
