### PR TITLE
test(e2e): exam results

### PR DESCRIPTION
**Pull request by dzmdre**
Checklist:

- [x] I have read and followed the [contribution guidelines](https://contribute.freecodecamp.org).
- [x] I have read and followed the [how to open a pull request guide](https://contribute.freecodecamp.org/#/how-to-open-a-pull-request).
- [x] My pull request targets the `main` branch of freeCodeCamp.
- [x] I have tested these changes either locally on my machine, or GitPod.

 [#51705](https://github.com/freeCodeCamp/freeCodeCamp/issues/51705)

### CODE REVIEW

**Comment by dzmdre** [comment]
camperbot cant code

**Comment by dzmdre** [comment]
Looks like I have no "pnpm run seed:exams" on ci and can not click on the Start exam button
https://discord.com/channels/692816967895220344/715074489422970962/1159520223645409321

**Comment by dzmdre** [comment]
Blocked by #51841

**Comment by dzmdre** [comment]
Waiting for  https://github.com/freeCodeCamp/freeCodeCamp/pull/51931

**Review by naomi-lgbt — APPROVED** [review]

**Comment by dzmdre** [comment]
> Hmm I'm not sure why the tests are failing. Could you try updating the branch with the latest `main`?
@huyenltnguyen  updated with the last changes; locally its working

**Comment by dzmdre** [comment]
Thanks @huyenltnguyen.
I have changed getBytestId to another locators, but it didn't help a lot.
I can not reproduce it locally, so I skipped tests for safari(webkit)
Please take a look and it can be merged after https://github.com/freeCodeCamp/freeCodeCamp/pull/52028

**Review by huyenltnguyen — APPROVED** [review]
LGTM 👍 Thanks for the tests @dzmdre!

**Pull request merged**
