### PR TITLE
fix(curriculum): Update description for step 22 of calorie counter project

### LINKED ISSUE #53550: Update description for step 22 of calorie counter project
### Describe the Issue

We still have a lot of confusion on how to do step 22 of the calorie counter.

https://forum.freecodecamp.org/search?q=step%2022%20calorie%20counter%20%23javascript

We should refactor the code example to better match what is expected in the lesson.
And we should update the 3rd hint text to more explicitly show the right answer for that if statement because that is where people are getting tripped up.

## updated step 22 description
````md
You will need to check if the array `["+", "-", " "]` does not include the current character. You can use a combination of the <dfn>includes()</dfn> method and the <dfn>!</dfn> operator to do this.

The `.includes()` method returns `true` if the array contains the character, and `false` if not. The logical NOT operator (`!`) will return the opposite of the value of the `.includes()` method.

Here is an example checking if the current character is not in the vowels array. If it is not, that current character is pushed into the `consonantArray`:

```js
const inputString = "Hello World";
const charArray = inputString.split('');
const consonantArray = [];

for (let i = 0; i < charArray.length; i++) {
  if (!['a', 'e', 'i', 'o', 'u'].includes(charArray[i])) {
    consonantArray.push(charArray[i]);
  }
}
```

Within your loop, you need to check if the character in `strArray` at index `i` is not a `+`, `-`, or a space. If it is not, `push` it to the `cleanStrArray`.
````

## revised 3rd hint text
````md
Your `for` loop should see if `!["+", "-", " "].includes(strArray[i])`.

```js
assert.match(code, /for\s*\(\s*(let|var)\s+i\s*=\s*0\s*;\s*i\s*<\s*strArray\.length\s*;\s*i\s*\+\+\s*\)\s*\{\s*if\s*\(\s*!\s*\[\s*("|')\+\2\s*,\s*("|')-\3\s*,\s*("|')\s\4\s*\]\s*\.includes\(\s*strArray\s*\[\s*i\s*\]\s*\)\s*\)(\s*\{)?/);
```
````

### Affected Page

https://www.freecodecamp.org/learn/javascript-algorithms-and-data-structures-v8/learn-form-validation-by-building-a-calorie-counter/step-22

### Your code

see explanation above

### Expected behavior

see explanation above

### Screenshots

_No response_

### System

- Device: [e.g. iPhone 6, Laptop]
- OS: [e.g. iOS 14, Windows 10, Ubuntu 20.04]
- Browser: [e.g. Chrome, Safari]
- Version: [e.g. 22]

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by zishpanchal**
Checklist:

- [x] I have read and followed the [contribution guidelines](https://contribute.freecodecamp.org).
- [x] I have read and followed the [how to open a pull request guide](https://contribute.freecodecamp.org/#/how-to-open-a-pull-request).
- [x]  My pull request targets the `main` branch of freeCodeCamp.
- [x] I have tested these changes either locally on my machine, or GitPod.

Closes #53550

### CODE REVIEW

**Comment by ilenia-magoni** [comment]
Please make sure your PR title follows [our convention](https://contribute.freecodecamp.org/#/how-to-open-a-pull-request?id=prepare-a-good-pr-title)

**Review by jdwilkin4 — APPROVED** [review]
Changes look good 👍

**Comment by zishpanchal** [comment]
> Please make sure your PR title follows [our convention](https://contribute.freecodecamp.org/#/how-to-open-a-pull-request?id=prepare-a-good-pr-title)

Sorry about that Its been a long night trying to fix my past PR mistakes. Thank you for bringing that to my attention.

**Comment by zishpanchal** [comment]
> Changes look good 👍

Amazing you have been a very good help. I will make sure to be proper in my future PRs and will try to contribute better in the future.

**Review by zairahira — APPROVED** [review]

**Pull request merged**
