### PR TITLE
fix: surround tags with code tags

### PR DESCRIPTION
**Pull request by leokorrr**
Fixed tags markup

- [ ] I have read [freeCodeCamp's contribution guidelines](https://github.com/freeCodeCamp/freeCodeCamp/blob/master/CONTRIBUTING.md).
- [ ] My pull request has a descriptive title (not a vague title like `Update index.md`)
- [ ] My pull request targets the `master` branch of freeCodeCamp.
- [ ] None of my changes are plagiarized from another source without proper attribution.
- [ ] My article does not contain shortened URLs or affiliate links.

If your pull request closes a GitHub issue, replace the XXXXX below with the issue number.

Closes #XXXXX

### CODE REVIEW

**Comment by lynxlynxlynx** [comment]
Please use more descriptive titles of your PRs.

**Comment by raisedadead** [comment]
@lynxlynxlynx 

I think we can fairly close PRs that ignore the issue template. It very clearly says:

```txt
...Please follow this checklist... It will ensure that our team takes your pull request seriously...
```

It very very short.

**Comment by raisedadead** [comment]
Okay, in that case I am re-opening as an exception. Please merge if no changes are required.

**Comment by lynxlynxlynx** [comment]
I don't have that kind of access, so go ahead. The change is fine.

**Review by ezioda004 — DISMISSED** [review]
Please make changes as requested.

**Pull request merged**
