### PR TITLE
Feat(Map): Performance is king

### LINKED ISSUE #15696: Increase Map performance

### PR DESCRIPTION
**Pull request by BerkeleyTrue**
Map performance is abysmal. Let's fix it.
[WIP]

"Life is not a problem to solve but a reality to experience" - Frank Herbert  
  

closes #15696

### CODE REVIEW

**Comment by BerkeleyTrue** [comment]
Baseline performance on opening a superblock.

baseline

.4 seconds!!! Let's get this under 16 ms, ya?

**Comment by BerkeleyTrue** [comment]
Removing the isHidden selector logic was a huge gain! We no longer use this logic so away it goes!

basic_html_and_html5__say_hello_to_html_elements___freecodecamp

**Comment by BerkeleyTrue** [comment]
Conditionally rendering the content of the superblock/block on isOpen is also a win! (I just keep on winning).

Down to 23ms. We can do better, we have the technology.

basic_html_and_html5__say_hello_to_html_elements___freecodecamp

Interestingly, closing a superblock is way fast! 7.3ms. That's my kind of fast.

basic_html_and_html5__say_hello_to_html_elements___freecodecamp

**Comment by raisedadead** [comment]
WOOOT!

**Comment by raisedadead** [comment]
And I have a tip to throw in, could we defer the interview-prep section loading which is a huge chunk by the no of challenges and probably the least used, by most users? I mean the majority ratio of the users maybe using the main coding super blocks, while a small ratio could be using the interview-prep.

Could we have a gain there too?

**Comment by vkWeb** [comment]
@raisedadead I disagree with that because campers should know that we have got a huge interview prep section for them so they'll be kinda motivated and feel confident throughout their journey. 

@Bouncey Perhaps, the most **required** update of Beta! Incredible work.

**Comment by raisedadead** [comment]
> I disagree with that because campers should know that we have got a huge interview prep section for them so they'll be kinda motivated and feel confident throughout their journey.

I am suggesting deferred loading, not moving / removing it anywhere. Its a perf suggestion, nothing is supposed to change in the UI.

**Comment by vkWeb** [comment]
> I am suggesting deferred loading, not moving / removing it anywhere. Its a perf suggestion, nothing is supposed to change in the UI.

@raisedadead Oh, I got it. But won't it take longer when a camper clicks on the interview prep section as we're loading it lazily? We should optimize the performance with interview sec as a whole if we can.

**Comment by QuincyLarson** [comment]
@BerkeleyTrue This pull request is a joy to read. Love your quotes and your blow-by-blows! Eager to QA and merge this once everything's your kind of fast. :)

**Comment by BerkeleyTrue** [comment]
I've tried various approaches to get this down further.

* Using a deferred render.
* Conditionally rending the list content on open.
* Extracting the rendering of the lists into their own components (effectively creating a memoized func).
* Using SCU/connect/PureComp in various combinations

The best I've found with consistent results was refactoring the rendering of the lists (renderBlocks and renderChallenges) into their own components with a special SCU that only checks that the lists are referentially equal. 

We've got it to be ~20ms(+-2) and opening 14ms consistently. The challenges are a worse a but mostly due to size. It seems like this is very size dependent. 

Regex takes about 70ms while something small like debug only takes 14ms. We could incorporate react-virtualized here, but that might be overkill. Consider that the camper is going to spend their time working on challenges and not scrolling through the map.


basic_html_and_html5__learn_how_freecodecamp_works___freecodecamp

**Comment by raisedadead** [comment]
Just pulled down and tested this. And Holy cow this is fast! Nice work. 

**Unrelated:**
I am unsure why we keep hitting the `/service` route though. On the beta monitoring, I see that this route is taking some really long times.

What I understand that this is checking for a user session.

Should I log a new issue?

**Comment by BerkeleyTrue** [comment]
I'll go through and speed up endpoints in the near future. If you see something you can fix feel free to create a pr. I don't think we should create an issue for these just now, though.

**Comment by raisedadead** [comment]
Sure thing. I'll take more deeper look. Is this ready for a merge? So far whatever I tested worked good(i.e I was randomly navigating challenges from different sections).

**Comment by BerkeleyTrue** [comment]
Yeah it's ready

**Comment by raisedadead** [comment]
Awesome! 

Thanks for taking the time to improve on the perf. "paying off" some of the technical debt always feels good!

Cheers.

**Pull request merged**
