### PR TITLE
feat(seed): Japanese translation of basic html challenges

### PR DESCRIPTION
**Pull request by t-cool**
#### Pre-Submission Checklist

- [*] Your pull request targets the `staging` branch of freeCodeCamp.
- [*] Branch starts with either `fix/`, `feature/`, or `translate/` (e.g. `fix/signin-issue`)
- [*] You have only one commit (if not, [squash](http://forum.freecodecamp.org/t/how-to-squash-multiple-commits-into-one-with-git/13231) them into one commit).
- [*] All new and existing tests pass the command `npm test`. Use `git commit --amend` to amend any fixes.

#### Type of Change

- [ ] Small bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds new functionality)
- [ ] Breaking change (fix or feature that would change existing functionality)
- [*] Add new translation (feature adding new translations)

#### Checklist:

- [*] Tested changes locally.
- [ ] Addressed currently open issue (replace XXXXX with an issue no in next line)

Closes #XXXXX

#### Description

Japanese translation of basic html challenges

### CODE REVIEW

**Comment by t-cool** [comment]
@raisedadead 
I appreciated your advice. I made a new PR.

**Comment by t-cool** [comment]
@raisedadead 
Was this commit too small to be merged?
If so, I'll translate a whole chapter and send it again.
At first, I'll translate "basic-html-and-html5.json" and send a PR.

And if you need some reviews from Japanese, I'll ask some of my friends with the long JS experience and check if my translation is correct.

Please tell me any other factors to add Japanese translation if there are any concerns.

**Comment by raisedadead** [comment]
Hi @t-cool 

Thanks for your PR and patience, we are sorry about the delay in getting back to you.

As for your queries, yes it would be awesome first of all if you could have this peer-reviewed from some one who is a native speaker of Japanese.

You can translate as much as time and efforts permit, there is no restriction that.

Thanks,

Happy contributing!

**Comment by raisedadead** [comment]
Hi @t-cool we thank you for the efforts, we are keeping out translation efforts on hold for now.

**Comment by t-cool** [comment]
@raisedadead 
Thank you for letting me know about it.
I'll translate all of it and run it locally around my city.
I hope we'll get together some day.

**Pull request closed without merging**
