### PR TITLE
Fix Text

### PR DESCRIPTION
**Pull request by kmmelcher**
Fix text portuguese

- [x] I have read [freeCodeCamp's contribution guidelines](https://github.com/freeCodeCamp/freeCodeCamp/blob/master/CONTRIBUTING.md).
- [x] My pull request has a descriptive title (not a vague title like `Update index.md`)
- [x] My pull request targets the `master` branch of freeCodeCamp.
- [x] None of my changes are plagiarized from another source without proper attribution.
- [x] All the files I changed are in the same world language (for example: only English changes, or only Chinese changes, etc.)
- [x] My changes do not use shortened URLs or affiliate links.

Closes #XXXXX

### CODE REVIEW

**Comment by kmmelcher** [comment]
Fix text portuguese

**Review by gugacavalieri — APPROVED** [review]
LGTM :smile:

**Comment by RandellDawson** [comment]
@CleoAguiar Can you check which version (the old version or the changes presented in this PR) match the [current English version of the challenge](https://www.freecodecamp.org/learn/responsive-web-design/basic-html-and-html5/add-a-submit-button-to-a-form)?

Thanks in advance.

**Comment by CleoAguiar** [comment]
> @CleoAguiar Can you check which version (the old version or the changes presented in this PR) match the [current English version of the challenge](https://www.freecodecamp.org/learn/responsive-web-design/basic-html-and-html5/add-a-submit-button-to-a-form)?
> 
> Thanks in advance.

The changes presented in this PR match the current English version of the challenge

**Review by CleoAguiar — APPROVED** [review]
LGTM

**Review by RandellDawson — APPROVED** [review]

**Comment by RandellDawson** [comment]
@kmmelcher 
Thank you for your contribution to the page! 👍
We're happy to accept these changes, and look forward to future contributions. 🎉

@CleoAguiar Thanks for reviewing the PR!

**Pull request merged**
