### PR TITLE
fix(tools): multiple workflow fixes

### PR DESCRIPTION
**Pull request by naomi-lgbt**
Checklist:

- [x] I have read [freeCodeCamp's contribution guidelines](https://contribute.freecodecamp.org).
- [x] My pull request has a descriptive title (not a vague title like `Update index.md`)
- [x] My pull request targets the `main` branch of freeCodeCamp.
- [x] All the files I changed are in the same world language, for example: only English changes, or only Chinese changes, etc.

Closes #XXXXX

- [X] Resolve failure code when nothing to commit
~~Thanks to @ojeytonwilliams for this fix - resolves the issue where having nothing to commit would trigger a non-zero exit code on the action. Here's a demo of the run: https://github.com/nhcarrigan/actions-testing/runs/2289277740?check_suite_focus=true~~
Thanks to StackOverflow: Using the `diff-index` command first to check that there are changes to be committed seems to resolve the issue. Now generates a commit if needed, skips the commit if nothing to commit, and no exit codes are thrown. [Example with commit](https://github.com/nhcarrigan/actions-testing/runs/2290036677?check_suite_focus=true#step:8:18) and [example without commit](https://github.com/nhcarrigan/actions-testing/runs/2290036677?check_suite_focus=true#step:8:18)
Unfortunately, when a commit was successful the `grep` fallback threw an exit code. Will need to investigate a better approach.
- [X] Update commit names to include scope
Mistakenly left the scope out (i.e. `docs`, `i18n`) of the commit message. Resolving that as well.
- [X] Use Camperbot PAT to push
By passing the PAT to the actions/checkout script, `git` authenticates Camperbot as the user and allows the push event to come from Camperbot - demonstrated with this PR: https://github.com/nhcarrigan/actions-testing/pull/39

### CODE REVIEW

**Review by ojeytonwilliams — DISMISSED** [review]
LGTM :+1: 

The "Unpredicted error occurred when trying to create the PR." message is a bit alarming, though! Might be good if that action could just warn in that case and generate a real (action stopping) error if something genuinely unexpected happens. 

Anyway, random tangents aside, this looks good.

**Comment by nhcarrigan** [comment]
Bad news on this one, by the way.

Testing some other tweaks, and turns out that if the commit actually succeeds, the `grep` will throw an exit code. 😅

**Review by raisedadead — DISMISSED** [review]

**Review by ojeytonwilliams — CHANGES_REQUESTED** [review]
The git commit solution is nice. For your amusement, this what I came up with.

```bash
text=$(git commit);[ $? = 1 ] && echo $text | grep -q "nothing to commit, working tree clean"
```

Could you explain the reason we're replacing `GITHUB_TOKEN` with camperbot's PAT? It isn't obvious to me what problem this solves, so it might be worth adding an explanatory comment to the yml.

One minor thing .github/workflows/crowdin-i18n-docs-download..yml has two dots.  Might as well fix this here, if that's okay.

**Comment by ojeytonwilliams** [comment]
Note to my future self (and anyone else puzzled by this): the reason that the `run` command 
```bash
git commit -m "chore: update translations"
git push -u origin i18n-sync-client -f
```
fails, despite the last command setting the error code to 0, is the [action passes `pipefail` to bash](https://docs.github.com/en/actions/reference/workflow-syntax-for-github-actions#using-a-specific-shell).  The commit fails, and the error code is piped to the end failing the action.

**Comment by nhcarrigan** [comment]
> Could you explain the reason we're replacing GITHUB_TOKEN with camperbot's PAT? 

So a GitHub event such as `pull_request` cannot trigger actions if the `actor` *is* an action. The repo token results in the actor being `github actions` bot, which causes our CI to never trigger.

We resolved this by having Camperbot open the PR, but if we do not review + merge that PR before the next run, `github actions` does the push to the existing PR and locks up our CI.

> One minor thing .github/workflows/crowdin-i18n-docs-download..yml has two dots

That was my snack for later 😉 Will fix shortly.

**Comment by ojeytonwilliams** [comment]
> So a GitHub event such as pull_request cannot trigger actions if the actor is an action. The repo token results in the actor being github actions bot, which causes our CI to never trigger.

I have so much to learn. Do you happen to know where this is documented?

**Comment by nhcarrigan** [comment]
https://docs.github.com/en/actions/reference/events-that-trigger-workflows#example-using-multiple-events-with-activity-types-or-configuration here is the docs

image

**Comment by ojeytonwilliams** [comment]
Great, thanks - that clears it up.

**Review by ojeytonwilliams — APPROVED** [review]

**Review by raisedadead — APPROVED** [review]

**Pull request merged**
