### PR TITLE
add target in challeges link

### LINKED ISSUE #41861: Link in challenge doesn't respect `target="_blank"`
**Describe your problem and how to reproduce it:**
In the **Nest an Anchor Element within a Paragraph**-challenge, in the description there's an example text+link. It is explicitly said that there's a `target="_blank"` attribute being used.
However, at the bottom of the example, the link after `"The final output of the example will look like this:"` doesn't take you to a new tab. This seems wrong to me.

**Add a Link to the page with the problem:**
https://www.freecodecamp.org/learn/responsive-web-design/basic-html-and-html5/nest-an-anchor-element-within-a-paragraph

**Tell us about your browser and operating system:**
* Browser Name: Firefox
* Browser Version: 88.0 (64-bit)
* Operating System: Linux

### PR DESCRIPTION
**Pull request by sa-ritesh**
Checklist:

- [x] I have read [freeCodeCamp's contribution guidelines](https://contribute.freecodecamp.org).
- [x] My pull request has a descriptive title (not a vague title like `Update index.md`)
- [x] My pull request targets the `main` branch of freeCodeCamp.
- [x] All the files I changed are in the same world language, for example: only English changes, or only Chinese changes, etc.

Closes #41861 

Sir,
I am new to git, by mistake, I deleted the previous PR rather than making changes in that only.
I have made all the requested changes in this PR. 
1. Changed all HTTP links to HTTPS.
2. Removed Extra Lines.
3. Changed target="_blank" to target="..."
Sorry for the inconvenience.

### CODE REVIEW

**Comment by Glitchy-Tozier** [comment]
Very nice changes, but I suggest not adding `.www` on every link. ( = removing all of them from the pull-request.)

1. It's inconsistent with the way links are portrayed in all other HTML-challenges I have seen.
2. Also it makes the text students have to read longer.

**Comment by sa-ritesh** [comment]
> Very nice changes, but I suggest not adding `www.` on every link. ( = removing all of them from the pull-request.)
> 
> 1. It's inconsistent with the way links are portrayed in all other HTML-challenges I have seen.
> 2. Also it makes the text students have to read longer.

Sure, but @huyenltnguyen sir asked me in the previous PR, so I did it.

**Comment by Glitchy-Tozier** [comment]
> > Very nice changes, but I suggest not adding `www.` on every link. ( = removing all of them from the pull-request.)
> > 
> > 1. It's inconsistent with the way links are portrayed in all other HTML-challenges I have seen.
> > 2. Also it makes the text students have to read longer.
> 
> Sure, but @huyenltnguyen sir asked me in the previous PR, so I did it.

Pretty sure his main message was adding the **s** to http… adding `www.` doesn't make much sense, looking at all the other challenges.
But let's see what he replies!  :)

**Comment by nhcarrigan** [comment]
> Pretty sure his main message was adding the s to http… Adding www. doesn't make much sense, looking at all the other challenges.

For both `freecodecamp.org` and `freecatphotoapp.com`, the root domain redirects to the `www.` subdomain so it does make sense, IMHO, to use that here. :)

**Review by naomi-lgbt — APPROVED** [review]
I'm good with this. 

@huyenltnguyen do you want to take another look?

**Comment by Glitchy-Tozier** [comment]
@nhcarrigan But that clashes with almost every other HTML-challenge.
I don't know what the best practice is with links, but I suggest sticking to one style **across all HTML-challenges**. No matter whether `https://asdf.com` or `https://www.asdf.com`.

The problem with using `www.` is that you'd need to change all the following challenges in the HTML-program alone:
- https://www.freecodecamp.org/learn/responsive-web-design/basic-html-and-html5/link-to-external-pages-with-anchor-elements
- https://www.freecodecamp.org/learn/responsive-web-design/basic-html-and-html5/link-to-internal-sections-of-a-page-with-anchor-elements
1. https://www.freecodecamp.org/learn/responsive-web-design/basic-html-and-html5/nest-an-anchor-element-within-a-paragraph
1. https://www.freecodecamp.org/learn/responsive-web-design/basic-html-and-html5/make-dead-links-using-the-hash-symbol
1. https://www.freecodecamp.org/learn/responsive-web-design/basic-html-and-html5/turn-an-image-into-a-link
1. https://www.freecodecamp.org/learn/responsive-web-design/basic-html-and-html5/create-a-bulleted-unordered-list
1. https://www.freecodecamp.org/learn/responsive-web-design/basic-html-and-html5/create-an-ordered-list
1. https://www.freecodecamp.org/learn/responsive-web-design/basic-html-and-html5/create-a-text-field
1. https://www.freecodecamp.org/learn/responsive-web-design/basic-html-and-html5/add-placeholder-text-to-a-text-field
1. https://www.freecodecamp.org/learn/responsive-web-design/basic-html-and-html5/create-a-form-element
1. https://www.freecodecamp.org/learn/responsive-web-design/basic-html-and-html5/add-a-submit-button-to-a-form
1. https://www.freecodecamp.org/learn/responsive-web-design/basic-html-and-html5/use-html5-to-require-a-field
1. https://www.freecodecamp.org/learn/responsive-web-design/basic-html-and-html5/create-a-set-of-radio-buttons
1. https://www.freecodecamp.org/learn/responsive-web-design/basic-html-and-html5/create-a-set-of-checkboxes
1. https://www.freecodecamp.org/learn/responsive-web-design/basic-html-and-html5/use-the-value-attribute-with-radio-buttons-and-checkboxes
1. https://www.freecodecamp.org/learn/responsive-web-design/basic-html-and-html5/check-radio-buttons-and-checkboxes-by-default
1. https://www.freecodecamp.org/learn/responsive-web-design/basic-html-and-html5/nest-many-elements-within-a-single-div-element

That's 15 out of 28.
(As a comparison, there are 2 challenges I could find that show a `www.`-link:
1. https://www.freecodecamp.org/learn/responsive-web-design/basic-html-and-html5/add-images-to-your-website
1. https://www.freecodecamp.org/learn/responsive-web-design/basic-html-and-html5/link-to-external-pages-with-anchor-elements)

**Comment by nhcarrigan** [comment]
Hmm, you're right - I do agree that we would want consistency. 

I still lean more toward using the accurate link, personally, and updating the other challenges in a separate PR. But if others disagree, I'm fine either way.

**Review by raisedadead — APPROVED** [review]

**Review by huyenltnguyen — APPROVED** [review]

**Comment by huyenltnguyen** [comment]
@sa-ritesh Thank you for the PR and congratulations on your first contribution to this repo ✨ 🎉
We look forward to your next.

Happy coding!

**Pull request merged**
