### PR TITLE
Make Slot Machine functions unique and lint

### LINKED ISSUE #7085: Unique Names for Algorithm Function Challenges
@SaintPeter
In order to facilitate follow up in our chatrooms, better:
* to stick ALWAYS to unique names for the functions (specifically check those named "convert" and "where")
* names should be totally identifiable, perhaps adding a number in order to avoid any similarity with natural language (example "function repeats(..." is not a good naming)

### PR DESCRIPTION
**Pull request by erictleung**
Tested locally. Passes `npm run test-challenges`. Closes #7085. I believe this covers the rest of the functions that needed to be unique ✨ ✨ ✨

### CODE REVIEW

**Comment by BerkeleyTrue** [comment]
@erictleung Thanks for the PR

We've had issues where challenges with renames throw off people who are in the middle of completing the challenge. Can you add a test to these challenges that checks to make sure they have the correct named function?

I'm guessing  `typeof runSlots !== 'function' || typeof runSlotMachine !== 'undefined'` ?

**Comment by erictleung** [comment]
@BerkeleyTrue no worries. Someone has created an issue just for that #7944. I can start by changing these functions first.

**Comment by erictleung** [comment]
@SaintPeter So I'm changing the slot machine function names, but I just now realized the slot machine challenges are building on top of the same code over a few challenges.

Right now, I'm changing the function names for each slot machine challenge, which may seem confusing that the function changes even though the task of building a slot machine is constant. What are your thoughts?

**Comment by SaintPeter** [comment]
The slot machine challenges are not live and have not been for a while.  They're flagged "beta", but should probably be removed entirely.

**Comment by erictleung** [comment]
@SaintPeter alright, do I have your green light to just delete the slot machine challenges? If so, I'll close this PR and then open another one which removes all four slot machine challenges all together.

**Comment by SaintPeter** [comment]
Yeah, let's just get rid of them.  If we need them in the future we have the git history.

**Pull request closed without merging**
