### PR TITLE
Fix wording of the tests in Waypoint: Create Bootstrap Wells

### LINKED ISSUE #3260: First test of 'Create Bootstrap Wells' waypoint has slight phrasing error
screenshot 7

`elements` (last word of the test) shouldn't be inside the code block. Also, it could be rephrased to say each of your `div` element with the class `col-xs-6`.

### PR DESCRIPTION
**Pull request by ghost**
Use precise wording to clearly differentiate code and other parts of the instructions. 

(Couldn't preview changes locally due to slow Internet connection. I'll happily rework it if anything is amiss.)

closes #3260

### CODE REVIEW

**Comment by ahstro** [comment]
Thank you! :) Would you mind [rebasing](https://github.com/FreeCodeCamp/FreeCodeCamp/wiki/git-rebase) this into a single commit?

**Comment by leonfeng** [comment]
Finally sorted it out… Didn't know git could do that~

**Comment by ahstro** [comment]
Cool! Yeah, git can do lots of amazing stuff. If you want more rebase magic, I definitely recommend reading [this](https://github.com/edx/edx-platform/wiki/How-to-Rebase-a-Pull-Request).

Regarding the PR: It looks good, but I'm going to leave the creative decisions to the @FreeCodeCamp/owners, so I won't merge this personally. Thank you though! :) Let's hope someone merges it soon.

**Comment by BerkeleyTrue** [comment]
@leonfeng This gets The Berks Seal of Approval.

berks_approves

**Comment by awesomeaniruddh** [comment]
WHY DON'T MY PRs GEDDIT? JUST A MERGE FOR ME?

**Comment by ahstro** [comment]
Really tempted to make a "Your phone gets The ahstro Seal of Approval"-photo. I still get excited when someone has the same phone as I do. @BerkeleyTrue :phone: :+1:

**Pull request merged**
