### PR TITLE
Decrease whitespace dependencies in checkoffs

### LINKED ISSUE #8960: Challenge [Modify Array Data With Indexes]
(https://www.freecodecamp.com/challenges/modify-array-data-with-indexes#?solution=%0A%2F%2F%20Example%0Avar%20ourArray%20%3D%20%5B1%2C2%2C3%5D%3B%0AourArray%5B1%5D%20%3D%203%3B%20%2F%2F%20ourArray%20now%20equals%20%5B1%2C3%2C3%5D.%0A%0A%2F%2F%20Setup%0Avar%20myArray%20%3D%20%5B1%2C2%2C3%5D%3B%0A%2F%2F%20Only%20change%20code%20below%20this%20line.%0AmyArray%5B0%5D%20%20%3D%203%3B%0A) has an issue.
User Agent is: <code>Mozilla/5.0 (Windows NT 10.0; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/50.0.2661.102 Safari/537.36</code>.
Please describe how to reproduce this issue, and include links to screenshots if possible.

My code:
```javascript

// Example
var ourArray = [1,2,3];
ourArray[1] = 3; // ourArray now equals [1,3,3].

// Setup
var myArray = [1,2,3];
// Only change code below this line.
myArray[0]  = 3;

```
This is the challenge .

1. myArray should now be [3,2,3].
2. You should be using correct index to modify the value in myArray.

The first one is correct but the second one seems to be bug because i have given the correct index to achieve the first one.

### PR DESCRIPTION
**Pull request by JacksonKearl**
#### Pre-Submission Checklist

- [ x] Your pull request targets the `staging` branch of FreeCodeCamp.
- [ x] Branch starts with either `fix/`, `feature/`, or `translate/` (e.g. `fix/signin-issue`)
- [ x] You have only one commit (if not, [squash](https://github.com/FreeCodeCamp/FreeCodeCamp/wiki/git-rebase#squashing-multiple-commits-into-one) them into one commit).
- [ x] All new and existing tests pass the command `npm run test-challenges`. Use `git commit --amend` to amend any fixes.
#### Type of Change

- [ x] Small bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds new functionality)
- [ ] Breaking change (fix or feature that would change existing functionality)
- [ ] Add new translation (feature adding new translations)
#### Checklist:

- [ ] Tested changes locally.
- [ x] Closes currently open issue (replace XXXX with an issue no): Closes #8960 
#### Description

Change most `\s?` to `\s*\` in tests, to allow for multiple whitespace characters in places where whitespace does not matter.

### CODE REVIEW

**Comment by erictleung** [comment]
@JacksonKearl as @camperbot has pointed out, your commit message should not have any keywords. In this case it is pointing at the `Fixes #8960`. Please remove them from the commit message so that we can merge you PR. Everything else looks good to me 👍

**Comment by JacksonKearl** [comment]
Its both says to not include any issue numbers, and to "replace XXX with the issue number this closes", so I'm not sure what to do.

**Comment by erictleung** [comment]
@JacksonKearl understandably, it is a bit confusing. Specifically, you'll need to remove the `fixes` statement from your actual git commit statement you made locally shown here.

image

You shouldn't see the `Fixes` statement here. However, in the GitHub PR message you filled out above in the GitHub website, you'll need the `Closes` statement there. I hope that makes more sense. Let me know if any of that was unclear.

**Comment by erictleung** [comment]
@JacksonKearl LGTM :+1: Congrats on your first PR to Free Code Camp! :sparkles: :tada: :sparkles:

**Pull request merged**
