### PR TITLE
fix(api): getChallenges helper function

### PR DESCRIPTION
**Pull request by Nirajn2311**
Checklist:

- [x] I have read and followed the [contribution guidelines](https://contribute.freecodecamp.org).
- [x] I have read and followed the [how to open a pull request guide](https://contribute.freecodecamp.org/#/how-to-open-a-pull-request).
- [x] My pull request targets the `main` branch of freeCodeCamp.
- [x] I have tested these changes either locally on my machine, or GitPod.

Closes #XXXXX

### CODE REVIEW

**Comment by Nirajn2311** [comment]
Oh look it has tests now. Someones gonna be happy.

On a serious note, is that test enough or do I need to add more?

**Review by ojeytonwilliams — APPROVED** [review]
LGTM :+1:

**Review by ojeytonwilliams — CHANGES_REQUESTED** [review]
Sure, an extra test is a good idea. Given that we make use of the `challengeType` I'd check that that exists and is a number. EDIT: and ids.

**Review by ojeytonwilliams — APPROVED** [review]
Thanks for the tests, Niraj.

LGTM :+1:

**Review by Sembauke — APPROVED** [review]

**Pull request merged**
