### PR TITLE
fix(Var-CI): Remove the Var-CI bot integration

### PR DESCRIPTION
**Pull request by raisedadead**
The bot has been annoying lately with more false positives recently.

We have already manged to reduce the noise on the issue tracker by switching help issue to 
forum.

This change removes the bot.

/cc @BerkeleyTrue please remove the same on their dashboard if need be as well, and/or delete any hooks that might be present.

### CODE REVIEW

**Comment by raisedadead** [comment]
Also just to note that the bot is no longer actively maintained as seen on their tracker.

**Comment by BerkeleyTrue** [comment]
@raisedadead Can you link to the issue tracker?

**Comment by raisedadead** [comment]
Well it's not said so by them, but I am guessing by looking at the activity on the tracker
https://github.com/VarCI/support/issues

**Comment by BerkeleyTrue** [comment]
Well, it looks like I can't even log into their dashboard either.

**Comment by raisedadead** [comment]
Yeah, that should suffice, I think. As long as the bot does not receive events we should be good.

**Pull request merged**
