### PR TITLE
fix(curriculum): remove extra "\" from description

### PR DESCRIPTION
**Pull request by JackHowa**
Noticed an extra "\\" in the text file on cat photo step description on beta course 

https://www.freecodecamp.org/learn/2022/responsive-web-design/learn-html-by-building-a-cat-photo-app/step-4

before 

Screen Shot 2021-12-29 at 4 42 04 PM

after (removed excess "\\")

Screen Shot 2021-12-29 at 5 10 55 PM

To test: 

- I updated the `.env` variable of `SHOW_NEW_CURRICULUM=true`

Checklist:

- [x] I have read [freeCodeCamp's contribution guidelines](https://contribute.freecodecamp.org).
- [x] My pull request has a descriptive title (not a vague title like `Update index.md`)
- [x] My pull request targets the `main` branch of freeCodeCamp.
- [x] I have tested these changes either locally on my machine, or GitPod.

### CODE REVIEW

**Review by gikf — APPROVED** [review]
LGTM :+1:

**Comment by JackHowa** [comment]
Thanks for the review @gikf -- let me know who else would need to approve?

**Comment by gikf** [comment]
@JackHowa another moderator, or staff. Generally merging PR requires two approvals from reviewers with write access.

**Review by ejcheng — APPROVED** [review]

**Comment by JackHowa** [comment]
codeql issue?

**Review by jdwilkin4 — APPROVED** [review]
LGTM! 👍

**Comment by gikf** [comment]
Hi @JackHowa. Congrats on your first pull request (PR)! 🎉

Thank you for your contribution to the page! 👍
We are happy to accept these changes and look forward to future contributions. 📝

**Pull request merged**
