### PR TITLE
fix(curriculum): make it easier to understand what to do and fix a typo

### PR DESCRIPTION
**Pull request by Vinnie-Rinella**
changes the wording to make it easier to understand what to put in the h1 elements as many people were confused by this it should help that!

Checklist:

- [x] I have read [freeCodeCamp's contribution guidelines](https://contribute.freecodecamp.org).
- [x] My pull request has a descriptive title (not a vague title like `Update index.md`)
- [x] My pull request targets the `main` branch of freeCodeCamp.
- [x] I have tested these changes either locally on my machine, or GitPod.

Closes #XXXXX

### CODE REVIEW

**Comment by hvinnieg** [comment]
if this passes i will update the rest of the files

**Review by raisedadead — CHANGES_REQUESTED** [review]
Did you get a chance to discuss this first on the forum with others?

**Comment by raisedadead** [comment]
Never mind, I found the related discussion is #46052 

--

As a new contributor, we encourage you to read our contributing guidelines. 

We expect our contributors to be aware of the process specific to this project. Following them religiously earns you the respect of fellow maintainers and saves everyone time.

Some examples of this are:

1. Make sure you are not editing off of GitHub (while you can, it's not a good idea).
2. Makes sure you actually follow the PR checklist and not just tick things off; we won't take you seriously otherwise.
3. Use the correct way to link PRs in the description of the PR by updating the `XXXXXX`.
4. ... and similar things.

We appreciate you taking the time to help us, and we hope to see more contributions from you.

Cheers & Happy Coding!

**Comment by hvinnieg** [comment]
what do you want to do

**Comment by moT01** [comment]
Go through the first part of this Cat Photo project (or maybe the whole thing) and change any instructions where what the user needs to add is at the end of the sentence - and put that on its own line. e.g.
Step 2 is:
```
Add an h2 element below the h1 element that says Cat Photos.
```
It should be changed to 
````
Add an h2 element below the h1 element that says:
Cat Photos
````

But you only need to change it where it's text the user adds, not if the sentence ends with like "`div`." or something. I could go through and get a list of the steps if you want.

**Comment by hvinnieg** [comment]
nah i get it ill change it now

**Comment by hvinnieg** [comment]
is this more what you guys wanted

**Comment by hvinnieg** [comment]
im new to github srry gtg

**Comment by raisedadead** [comment]
> im new to github srry gtg

No worries, we all start somewhere, and trust me, we all share the feeling.

This particular PR is currently trying to do more things than it should. You should ideally be making separate PRs because the two issues you are addressing are unrelated.

In the interest of time and letting others contribute, I am going to go ahead and close this.

If you are interested in working on code or curriculum we encourage you to give our contributing guide a good read, they everything you will need to understand how it all works.

Thanks for your time and happy coding.

**Pull request closed without merging**
