### PR TITLE
Fix: Clarify title for "Basic Data Structures: Copy an Array with slice()"

### LINKED ISSUE #13110: [beta] Clarify title for "Basic Data Structures: Copy an Array with slice()"
### Welcome first-time open source contributors! :trophy: 
Challenge [copy-an-array-with-slice](http://beta.freecodecamp.com/en/challenges/basic-data-structures/copy-an-array-with-slice) has an issue.

The title says "Copy an Array with slice()", but the challenge could be better described as "Copy Array items using slice()" as `Array.slice()` not only can copy whole arrays, but can copy individual items as well.

If you want to help fixing this, the [contribution guidelines](https://github.com/freeCodeCamp/freeCodeCamp/blob/staging/CONTRIBUTING.md) can help you get started.

[This is the line](https://github.com/freeCodeCamp/freeCodeCamp/blob/staging/seed/challenges/02-javascript-algorithms-and-data-structures/basic-data-structures.json#L235) where you can make this change.

Feel free to come chat with us in the [Contributors chat room](https://gitter.im/FreeCodeCamp/Contributors) if you have any questions - or just want to say hi!

Good luck & Happy coding! :smile: :+1:

---

### Already resolved:
:white_check_mark: <strike>1. The test for this challenge does not run properly. The console gives me plenty of "Minified React Error #32", Similar to the message reported in #12656.</strike>

:white_check_mark: <strike>2. I originally thought the second test case just had a problem with formatting, but since there's nothing wrong with it, I suspect it has to do with the React error. However, I noticed that the second test could be improved with a cleaner assertion.
I suggest [this line](https://github.com/freeCodeCamp/freeCodeCamp/blob/staging/seed/challenges/02-javascript-algorithms-and-data-structures/basic-data-structures.json#L259) gets replaced with 
`"assert(/\\.slice\\(/.test(code), 'message: The <code>forecast</code> function should utilize the <code>slice()</code> method');"`</strike>

### PR DESCRIPTION
**Pull request by davidmgisbert**
Clarify title for "Basic Data Structures: Copy an Array with slice()"

#### Pre-Submission Checklist

- [x] Your pull request targets the `staging` branch of freeCodeCamp.
- [x] Branch starts with either `fix/`, `feature/`, or `translate/` (e.g. `fix/signin-issue`)
- [x] You have only one commit (if not, [squash](http://forum.freecodecamp.com/t/how-to-squash-multiple-commits-into-one-with-git/13231) them into one commit).
- [x] All new and existing tests pass the command `npm test`. Use `git commit --amend` to amend any fixes.

#### Type of Change

- [x] Small bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds new functionality)
- [ ] Breaking change (fix or feature that would change existing functionality)
- [ ] Add new translation (feature adding new translations)

#### Checklist:

- [x] Tested changes locally.
- [x] Closes currently open issue (replace XXXX with an issue no): Closes #13110

#### Description

Change the title for challenge from "Copy an Array with slice()" to "Copy Array Items Using slice()"

### CODE REVIEW

**Comment by systimotic** [comment]
@davidmgisbert Thanks for the PR!

@Greenheart Do you have input on how this should be cased?

**Comment by Greenheart** [comment]
Perhaps `Copy Array Items Using slice()` - @davidmgisbert @systimotic What do you think? :blush:

**Review by Greenheart — COMMENTED** [review]
I just noticed that the PR title, branch name and the commit message reference the issue number. According to [this section](https://github.com/freeCodeCamp/freeCodeCamp/blob/staging/CONTRIBUTING.md#common-steps)  of the contributing guide, this shouldn't be allowed. 

But I'm not sure about this - @systimotic Do you know why this is seen as a bad practice?

**Comment by systimotic** [comment]
@Greenheart When looking at the git history, it's good to have an idea of what everything is about without having to follow links. Renaming the commit would definitely be a good idea. If the casing has to be amended, we can hit two birds with one stone.

**Comment by davidmgisbert** [comment]
@systimotic @greenheart i can do it when i get home if you let me. And sorry for the inconveniences.

**Comment by systimotic** [comment]
@davidmgisbert Awesome! No problem, I still have to fix up my PR's way more than this a lot of the time. I'm just really thankful that you're taking time out of your day to contribute!

**Review by systimotic — CHANGES_REQUESTED** [review]
These changes look great to me! As per our guidelines, can you please [squash your commits](http://forum.freecodecamp.com/t/how-to-squash-multiple-commits-into-one-with-git/13231)?

**Review by systimotic — APPROVED** [review]
# LGTM 👍
Thanks a lot for contributing, and for updating so quickly!
I'll pass the final judgement on this to @Greenheart

**Comment by davidmgisbert** [comment]
@systimotic thanks to you for letting me start to contribute to open source 😄

**Comment by Greenheart** [comment]
Sorry for the delay, I've been pretty busy with my new job... :relaxed:

@davidmgisbert Thanks for fixing this! Welcome to open source :smile:

**Review by Greenheart — APPROVED** [review]

**Comment by Greenheart** [comment]
@systimotic What do you think about the branch name? I feel like we could forget about it for this time so we can get this fix merged :blush:

**Comment by QuincyLarson** [comment]
@davidmgisbert thanks for paying attention to these small details. This is an important clarification.

**Pull request merged**
