### PR TITLE
fix(seed): fixed 'use-strict' warnings and test cases to include both…

### LINKED ISSUE #16348: ES6 - Compare Scopes of the var and let keywords - console not defined error
#### Challenge Name
https://beta.freecodecamp.org/en/challenges/es6/compare-scopes-of-the-var-and-let-keywords

#### Issue Description
There are two errors that appear in the challenge on the editor.
First is for the "use strict", the warning states "use the function form of use strict"
Second error is console.log having a red X stating console is not defined. 
The challenge still passes.

if I put the use strict into function form, the errors on the editor disappear

#### Browser Information

Browser Name, Version:
Operating System: FireFox 57.0 (64-bit) and Chrome Version 63.0.3239.84 (Official Build) (64-bit)
Mobile, Desktop, or Tablet: Laptop Windows 10 Professional 64-bit

#### Your Code

```js



```
#### Screenshot

image

Use Strict in Function Form: 
image

### PR DESCRIPTION
**Pull request by saurishkar**
… single and double quotes

#### Pre-Submission Checklist

- [x] Your pull request targets the `staging` branch of freeCodeCamp.
- [x] Branch starts with either `fix/`, `feature/`, or `translate/` (e.g. `fix/signin-issue`)
- [x] You have only one commit (if not, [squash](http://forum.freecodecamp.org/t/how-to-squash-multiple-commits-into-one-with-git/13231) them into one commit).
- [x] All new and existing tests pass the command `npm test`. Use `git commit --amend` to amend any fixes.

#### Type of Change

- [x] Small bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds new functionality)
- [ ] Breaking change (fix or feature that would change existing functionality)
- [ ] Add new translation (feature adding new translations)

#### Checklist:

- [x] Tested changes locally.
- [x] Addressed currently open issue (replace XXXXX with an issue no in next line)

Closes #16348 

#### Description

This PR fixes the errors in **es6.json under ES6 challenges** from `Understand the Differences Between import and require` to `Import a Default Export`.

- Fixes code to use the functional form of `use strict`
- Test cases updated to include single-quotes as well along with double-quotes wherever necessary.

### CODE REVIEW

**Comment by raisedadead** [comment]
Hey @Ethan-Arrowood mind taking a look?

**Review by Ethan-Arrowood — COMMENTED** [review]
LGTM

I’ve been a little out of the loop,  but did we resolve the import/export test issues (something about import/export not being supported by our browser repl)? If so then as long as these are QA’d to run and pass I’m happy to merge. If not then we should probably hold off on making changes to these until that above mentioned issue is resolved.

**Comment by raisedadead** [comment]
Okay, I am also unaware of these I guess, then... I was planning to pull down and QA. 
Maybe @systimotic or @Bouncey can guide if we resolved the `import/export` use in tests?

If you confirm, we can proceed with QA.

**Comment by raisedadead** [comment]
Perfect, thanks for the reference to issues.

**Review by Bouncey — CHANGES_REQUESTED** [review]
I don't like the idea of having to wrap the challenge code in an IIFE. Could you see if it still works if we move `"use strict";` in to the head of the challenge seed

**Comment by Bouncey** [comment]
@saurishkar did you get round to trying `use-strict` in the `head` instead of the IIFE?

**Comment by raisedadead** [comment]
@saurishkar Please open a fresh PR when ready. We are trying to get as many fixes done before beta.

**Pull request closed without merging**
