### PR TITLE
fix(curriculum,i18n): issues in the source string

### PR DESCRIPTION
**Pull request by fhsinchy**
Checklist:

- [x] I have read [freeCodeCamp's contribution guidelines](https://contribute.freecodecamp.org).
- [x] My pull request has a descriptive title (not a vague title like `Update index.md`)
- [x] My pull request targets the `main` branch of freeCodeCamp.
- [x] I have tested these changes either locally on my machine, or GitPod.

Added missing code formatting tags to `textarea` and removed the dots from `P.S.` otherwise it breaks the emphasis tags. Postscript can also be written as PS instead of P.S. so I did just that. Please correct me if I'm wrong.

### CODE REVIEW

**Comment by gikf** [comment]
@fhsinchy Could you clarify what is right now wrong with the postscriptum? I'm not seeing anything clearly broken with it.

**Comment by fhsinchy** [comment]
> @fhsinchy Could you clarify what is right now wrong with the postscriptum? I'm not seeing anything clearly broken with it.

When we write the postscriptum as `P.S`, crowdin treats it as a a separate line. You may have seen that the entire postscriptum is within an emphasis tag. Thay tag gets broken and when translating, crowdin throws warning.

Writing the postscriptum as `PS` will make crowdin treat the entire sentence as one line. Correct me if I'm wrong here.

**Comment by gikf** [comment]
Thanks for the clarification, I was missing that it's creating issues in crowdin.

**Review by raisedadead — APPROVED** [review]

**Review by ArielLeslie — APPROVED** [review]

**Comment by nhcarrigan** [comment]
Thank you for your contribution to the page! 👍
We are happy to accept these changes and look forward to future contributions. 🎉

**Pull request merged**
