### PR TITLE
feat: curriculum-basic-html-form-element-solution

### PR DESCRIPTION
**Pull request by paulywill**
Added solution for https://learn.freecodecamp.org/responsive-web-design/basic-html-and-html5/create-a-form-element

- [x] I have read [freeCodeCamp's contribution guidelines](https://github.com/freeCodeCamp/freeCodeCamp/blob/master/CONTRIBUTING.md).
- [x] My pull request has a descriptive title (not a vague title like `Update index.md`)
- [x] My pull request targets the `master` branch of freeCodeCamp.
- [x] None of my changes are plagiarized from another source without proper attribution.
- [x] All the files I changed are in the same world language (for example: only English changes, or only Chinese changes, etc.)
- [x] My changes do not use shortened URLs or affiliate links.

### CODE REVIEW

**Review by RandellDawson — APPROVED** [review]
Tested and LGTM.

**Review by Manish-Giri — COMMENTED** [review]
Nitpicking, but maybe we could have html code formatting (```html) for the solution (Line 73) instead of js.

**Comment by RandellDawson** [comment]
@Manish-Giri I am ok with that.  Just add it.

**Comment by Manish-Giri** [comment]
@RandellDawson Fork repository has probably been deleted, so there's no way to make changes.

**Comment by RandellDawson** [comment]
I say close it and I will duplicate the PR myself.  Give me about 5 minutes.

**Comment by Manish-Giri** [comment]
Let's accept this PR and you can then make a PR to make the change. That way @paulywill would still get his contribution merged.

**Comment by RandellDawson** [comment]
Good point.  Go ahead and merge!

**Review by Manish-Giri — APPROVED** [review]
@paulywill LGTM. Thank You for your contribution.

[PS: Please refrain from deleting your fork of the repo until your PRs have been merged!]

**Comment by paulywill** [comment]
@Manish-Giri @RandellDawson Thank you. :)

**Pull request merged**
