### PR TITLE
feat(client): conditionally hide preview for new js project

### PR DESCRIPTION
**Pull request by naomi-lgbt**
Checklist:

- [X] I have read and followed the [contribution guidelines](https://contribute.freecodecamp.org).
- [X] I have read and followed the [how to open a pull request guide](https://contribute.freecodecamp.org/#/how-to-open-a-pull-request).
- [X] My pull request targets the `main` branch of freeCodeCamp.
- [X] I have tested these changes either locally on my machine, or GitPod.

I need this for #54305 - there's nothing to preview there it's a console app.

I'm sure @ojeytonwilliams is gonna see this and say there's a much smarter way to do it

### CODE REVIEW

**Review by ojeytonwilliams — COMMENTED** [review]
I'm not sure about smarter, but I think it's preferable to have the rendering depend on some meaningful property of the challenge. E.g. a challenge type `jsConsole` or a flag `consoleOnly`.

@ShaunSHamilton and @moT01 have been thinking about this stuff recently.

**Comment by ShaunSHamilton** [comment]
This is something we have been mulling-over a lot now. On one hand, if this does what you need, go for it 👍 

On the other, what we are thinking of doing is something like `javascript_stdout` and `default_javascript_stdout` features on a per-challenge basis. So, if, for whatever reason, you wanted the console to be open for one lesson, optional for the next, then not even available for the one after that, you can.

**Comment by ojeytonwilliams** [comment]
What were you thinking for `javascript_stdout`? I was thinking that `consoleOnly` (or a better name) would be a flag analogous to `translationPending` and used in place of `block !== 'learn-introductory-javascript-by-building-a-pyramid-generator'`.

**Comment by ShaunSHamilton** [comment]
I have replied off the PR, because a lot of this is off-topic.

**Review by ojeytonwilliams — APPROVED** [review]
Heya, turns out I don't have a smart solution. Not one that's worth blocking this for, anyway!

So we don't randomly break this, could you create an e2e test on https://github.com/freeCodeCamp/freeCodeCamp/pull/54305 once this is merged?

**Review by ShaunSHamilton — APPROVED** [review]

**Comment by ojeytonwilliams** [comment]
@naomi-lgbt I got so hung up on the "right way" to do this that I didn't entirely check what this is doing.

Is the plan to remove the preview, preview portal and the buttons in another PR?

**Review by ojeytonwilliams — CHANGES_REQUESTED** [review]
Just adding a "request changes" until we've clarified what the plan is!

**Comment by naomi-lgbt** [comment]
I didn't even think to remove them - I just wanted the modal gone haha

**Comment by naomi-lgbt** [comment]
@ojeytonwilliams other PR got automerged, added e2e tests here

**Review by ojeytonwilliams — APPROVED** [review]
This introduces a small UI issue, 
image and it would be better if this showed the console by default, but I think this is overall an improvement.

I'll create PRs for those separately.

**Pull request merged**
