### PR TITLE
Stop inject from mangling label when offset from loop

### LINKED ISSUE #7465: Using labeled statements in the 'Pig Latin' exercise throws an "Undefined label" Error
#### Issue Description
* The issue happens when you use a [labeled statement](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Statements/label) in the Pig Latin exercise. I have been unable to confirm whether this issue happens in other exercises as well.
* To reproduce:

1. Visit the [Pig Latin algorithm exercise](http://www.freecodecamp.com/challenges/pig-latin)
2. Use a labeled statement followed by a for loop. 
3. Observe the difference between the FreeCodeCamp output and Chrome's console. FreeCodeCamp throws an "**SyntaxError: Unlabeled statement**" error but works flawlessly if you use Chrome's console.

#### Browser Information
* Google Chrome, 48.0.2564.116 (Official Build) m (64-bit)
* Windows 7

#### Your Code

```js
function translate(str) {
  var isVowel = "aeiou";
  var newStr = "test";
  
label1:
  for (var i = 0; i < 2; i++) {
    for (var j = 0; j < 3; j++) {
      break label1;
    }
  }
  return newStr;
}

translate("california");
```

#### Screenshot
**FreeCodeCamp output**: http://i.imgur.com/f3ETnch.png
**Chrome Console output**: http://i.imgur.com/QEntg6O.png

### PR DESCRIPTION
**Pull request by wdimac**
#### Pre-Submission Checklist

- [x] Your pull request targets the `staging` branch of FreeCodeCamp.
- [x] Branch starts with either `fix/`, `feature/`, or `translate/` (e.g. `fix/signin-issue`)
- [x] You have only one commit (if not, [squash](https://github.com/FreeCodeCamp/FreeCodeCamp/wiki/git-rebase#squashing-multiple-commits-into-one) them into one commit).
- [x] All new and existing tests pass the command `npm run test-challenges`. Use `git commit --amend` to amend any fixes.
#### Type of Change

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] Add new translation (feature adding new translations)
#### Checklist:

- [x] Tested changes locally.
- [x] Closes currently open issue (`Closes #XXXX`): Closes #7465
#### Description

Insert reset code at actual label index, rather than assuming it is aligned with loop

### CODE REVIEW

**Comment by BerkeleyTrue** [comment]
Bump for QA

**Comment by raisedadead** [comment]
Okay, so first of all apologies in the delay for QA'ing this... :sweat_smile: 

But this does work, I am not very sure that I can come up with more test scenarios that will break this but currently the LoopProtect output with the original code from the issue seems to be non-conflicting.

```js
function translate(str) {
  var isVowel = "aeiou";
  var newStr = "test";

;loopProtect.protect({ line: 10, reset: true }); label1:
  for (var i = 0; i < 2; i++) {;
if (loopProtect.protect({ line: 10 })) break;

    ;loopProtect.protect({ line: 11, reset: true }); for (var j = 0; j < 3; j++) {;
if (loopProtect.protect({ line: 11 })) break;

      break label1;
    }
  }
  return newStr;
}

translate("california");
```

Since this definitely addresses the label handling issue, I'll probably test this PR with some other challenges for "non-regression", and we should be good to go.

**Comment by raisedadead** [comment]
cc/ @ltegman for a look, but mostly this is good.

**Comment by jthrons69** [comment]
Cancel me from getting Githug had anything to do with freecodecamp.

Sent from Yahoo Mail on Android 
 
  On Fri, May 27, 2016 at 10:36 PM, Berkeley Martinez<notifications@github.com> wrote:   
Bump for QA

**Comment by raisedadead** [comment]
@jthrons69 

Hello!

Looks like you may have accidentally subscribed to all notifications for the [FreeCodeCamp](https://github.com/FreeCodeCamp/FreeCodeCamp) repository. To stop receiving notifications please visit the [subscriptions page](https://github.com/FreeCodeCamp/FreeCodeCamp/subscription) or click on the image below and select **"Not watching"**.

[image](https://github.com/FreeCodeCamp/FreeCodeCamp/subscription)


We are sorry for your inconvenience!

**Comment by ltegman** [comment]
I'll echo @raisedadead's apologies for the slow QA. Looks good to me as well. Thanks for the contribution!

**Pull request merged**
