### PR TITLE
feat: update editable region behaviour

### PR DESCRIPTION
**Pull request by ojeytonwilliams**
- refactor: remove ambiguity about editable region
- fix: make jaws follow the highlighted region
- fix: update the jaws on all content changes
- feat: make editable region 'absorb' text

NewEditorBehaviour

### CODE REVIEW

**Comment by ojeytonwilliams** [comment]
@nhcarrigan @ahmadabdolsaheb what do you reckon to this behaviour?  I think it's pretty intuitive, but I'd love to hear your feedback.

**Review by ShaunSHamilton — APPROVED** [review]
Brilliant, Oliver! After playing with this a bit, this definitely seems like the most intuitive behaviour, and I cannot imagine many Campers expecting elsewise.

Keep this up, and this file will get below 1,000 lines.

**Comment by ojeytonwilliams** [comment]
> After playing with this a bit, this definitely seems like the most intuitive behaviour, and I cannot imagine many Campers expecting elsewise.

I hope so, it'll be interesting to see how people interact with it.

> Keep this up, and this file will get below 1,000 lines.

Hahaha, should do, actually.

**Comment by ahmadabdolsaheb** [comment]
Solid work.

**Review by ahmaxed — APPROVED** [review]

**Pull request merged**
