### PR TITLE
Updated mongodb running command in c9.io

### LINKED ISSUE #12379: MongoDB Runnning Problem using the instruction
Challenge [Store Data in MongoDB](https://www.freecodecamp.com/challenges/store-data-in-mongodb) has an issue.
User Agent is: <code>Mozilla/5.0 (Windows NT 10.0; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/55.0.2883.87 Safari/537.36</code>.

When we try to run mongodb in c9 using the command: mongod --port 27017 , we get error "ERROR: Insufficient free space for journal files". The screenshot is included:
mongo

To run mongodb successfully in c9 within the provided memory we should run mongodb using the following command: mongod --port 27017 --smallfiles

### PR DESCRIPTION
**Pull request by arsho**
#### Type of Change

- [x] Small bug fix (non-breaking change which fixes an issue)

#### Checklist:

- [ ] Tested changes locally.
- [ ] Closes currently open issue (replace 12379 with an issue no): Closes #12379

#### Description

For free users, c9.io provide only 2GB memory for single workspace. But to run mongodb it requires at least 3379MB in journal. So we should use mongod --port 27017 --smallfiles to allow run mongodb within the provided 2GB memory.

### CODE REVIEW

**Review by raisedadead — APPROVED** [review]

**Comment by aguyinmontreal** [comment]
What am I doing wrong?

I type:

$ ./mongod --port 27017
$ learnyoumongo verify
And I get:

✗ Error connecting to mongo. failed to connect to server [localhost:27017] on first connect

Thanks!

**Comment by breakpoint25** [comment]
I disagree with this change, the instructions state to use ./mongod ... command on c9 in step 13.

If you use the basic mongo ... command you will run into this issue if you ignore step 13. 

You are not following the instructions of step 13.

**Comment by raisedadead** [comment]
@breakpoint25 Can you please raise a separate issue, with details of the concern? Thanks.

**Comment by breakpoint25** [comment]
I have opened  #14507

**Pull request merged**
