### PR TITLE
fix(docs): Fixed Chinese broken link and markdown

### PR DESCRIPTION
**Pull request by nella17**
- [x] I have read [freeCodeCamp's contribution guidelines](https://github.com/freeCodeCamp/freeCodeCamp/blob/master/CONTRIBUTING.md).
- [x] My pull request has a descriptive title (not a vague title like `Update index.md`)
- [x] My pull request targets the `master` branch of freeCodeCamp.
- [x] None of my changes are plagiarized from another source without proper attribution.
- [x] All the files I changed are in the same world language (for example: only English changes, or only Chinese changes, etc.)
- [x] My changes do not use shortened URLs or affiliate links.

### CODE REVIEW

**Comment by RandellDawson** [comment]
@nella17 Thank you for submitting changes to this document.  The current version of this document does not reflect the most recent version of the [English CONTRIBUTING.md file](https://github.com/freeCodeCamp/freeCodeCamp/blob/master/CONTRIBUTING.md).  Can you please review the English version and remove/add/change all parts of it to make it match the current content of it?

Thank you.

**Comment by nella17** [comment]
@RandellDawson I finished translation most recent version of the English CONTRIBUTING.md file.

**Comment by RandellDawson** [comment]
@miyaliu666 Can you review this PR?

**Comment by miyaliu666** [comment]
@RandellDawson Sorry, I just noticed your message. The translation is ok. I'll update some words and links later, for example, the repository to YouTube video translation.
Thank you for translating it @nella17 You may also be interested in the [articles](https://github.com/freeCodeCamp/news-translation) or [videos](https://github.com/freeCodeCamp/videos-translation) translating collaboration:)

**Pull request merged**
