### PR TITLE
fix(challenge): fix the last test of the Cash Register Project

### LINKED ISSUE #52688: New Cash Register Project test bug
### Describe the Issue

It looks like the expected array is wrong in the last test.

Also, I'm not sure if it should only account for what is the same. Just because the output _does_ contain the expected doesn't mean it can't contain _more_ than the expected.

### Affected Page

https://www.freecodecamp.org/learn/javascript-algorithms-and-data-structures-v8/build-a-cash-register-project/build-a-cash-register

### Your code

```

const expected = ['Status: OPEN', 'QUARTER: $0', 'DIME: $0', 'NICKEL: $0', 'PENNY: $0.5'];

let text = 'Status: OPEN ONE HUNDRED: $0 TWENTY: $0 TEN: $0 FIVE: $0 DOLLAR: $0 ONE: $0 QUARTER: $0 DIME: $0 NICKEL: $0 PENNY: $0.5'

let result = expected.every(str => text.trim().toLowerCase().includes(str.toLowerCase()))
console.log(result); // true

```

### Expected behavior

Test not to pass with the wrong code.

### Screenshots

_No response_

### System

- Device: [e.g. iPhone 6, Laptop]
- OS: [e.g. iOS 14, Windows 10, Ubuntu 20.04]
- Browser: [e.g. Chrome, Safari]
- Version: [e.g. 22]

### Additional context

Forum: https://forum.freecodecamp.org/t/cash-register-bug/657207

### PR DESCRIPTION
**Pull request by weilirs**
Checklist:

- [x] I have read and followed the [contribution guidelines](https://contribute.freecodecamp.org).
- [x] I have read and followed the [how to open a pull request guide](https://contribute.freecodecamp.org/#/how-to-open-a-pull-request).
- [x] My pull request targets the `main` branch of freeCodeCamp.
- [x] I have tested these changes either locally on my machine, or GitPod.

Closes [#52688](https://github.com/freeCodeCamp/freeCodeCamp/issues/52688)

### CODE REVIEW

**Comment by weilirs** [comment]
I change the last test's status to `CLOSED` and since it only returned $0.5 back to the customer I removed other denominators.

**Review by majestic-owl448 — CHANGES_REQUESTED** [review]
Please change also the solution project to match this. The solution project must always pass the tests

**Comment by weilirs** [comment]
> Please change also the solution project to match this. The solution project must always pass the tests

I modified the solution and description accordingly

**Comment by gikf** [comment]
> Please change also the solution project to match this. The solution project must always pass the tests

At some point demo project also will need to be updated with changed solution - https://github.com/freeCodeCamp/demo-projects/blob/main/apps/cash-register/public/script.js

**Comment by weilirs** [comment]
> > Please change also the solution project to match this. The solution project must always pass the tests
> 
> At some point demo project also will need to be updated with changed solution - [freeCodeCamp/demo-projects@`main`/apps/cash-register/public/script.js](https://github.com/freeCodeCamp/demo-projects/blob/main/apps/cash-register/public/script.js?rgh-link-date=2024-01-04T19%3A39%3A20Z)

Do you want me to do this now or after this PR has been reviewed and merged?

**Comment by gikf** [comment]
I'd say let's wait until this is finalized and merged.

**Review by huyenltnguyen — COMMENTED** [review]
@scissorsneedfoodtoo I think you'd want to review this PR as well, since you're the original author 🙂

**Comment by scissorsneedfoodtoo** [comment]
Thank you for these fixes, @weilirs. And thank you for the @ mention, @huyenltnguyen – I'm still getting caught up on notifications :)

Tested locally and everything LGTM.

@weilirs, if you could just make those changes that @huyenltnguyen suggested, we should be able to get this in. You can make the changes manually in your editor and push a commit, or you can use the handy "Commit suggestion" dropdowns above to do that.

**Comment by weilirs** [comment]
> > Please change also the solution project to match this. The solution project must always pass the tests
> 
> At some point demo project also will need to be updated with changed solution - [freeCodeCamp/demo-projects@`main`/apps/cash-register/public/script.js](https://github.com/freeCodeCamp/demo-projects/blob/main/apps/cash-register/public/script.js?rgh-link-date=2024-01-04T19%3A39%3A20Z)

I think this PR is about to finalized. For this update you mentioned, do I need to create an issue or I can just make a PR?

**Review by huyenltnguyen — APPROVED** [review]

**Review by scissorsneedfoodtoo — APPROVED** [review]
Thanks for making those updates, @weilirs, and for opening the PR in the demo-projects repo. I'll take a look at that PR now.

@ieahleen, could you take another look and approve this if everything looks good?

**Review by majestic-owl448 — APPROVED** [review]
LGTM :+1:

**Comment by bbsmooth** [comment]
This was merged 3 weeks ago but we are still getting complaints in the forum. Has this code made it to production?

**Comment by gikf** [comment]
> This was merged 3 weeks ago but we are still getting complaints in the forum. Has this code made it to production?

Looks like it went in today, so that shouldn't be an issue anymore :tada:

**Pull request merged**
