### PR TITLE
fix(curriculum): instructions and tests for a11y quiz step 56

### LINKED ISSUE #47588: accessibility quiz step 56 is confusing
This step is confusing to many people

https://www.freecodecamp.org/learn/2022/responsive-web-design/learn-accessibility-by-building-a-quiz/step-56

Specifically the
> Also, align the text to the right.

You write the code required
```css
.info > label, .info > input {
  display: inline-block;
  text-align: right;
}
```

and then it says
> You should set the text-align: right property before the .info input rule.

It uses precedence rules without talking about them.
The end result needs to be that the labels have `text-align: right;` and the inputs `text-align: left` so why are we asking yo add the `text-align: right` to a selector list that includes both and then rely on precedence rules to have them assigned property?

### PR DESCRIPTION
**Pull request by Insidiae**
Checklist:

- [x] I have read [freeCodeCamp's contribution guidelines](https://contribute.freecodecamp.org).
- [x] My pull request has a descriptive title (not a vague title like `Update index.md`)
- [x] My pull request targets the `main` branch of freeCodeCamp.
- [x] I have tested these changes either locally on my machine, or GitPod.

Closes #47588

### CODE REVIEW

**Review by majestic-owl448 — DISMISSED** [review]
Thank you for your PR, but it is not enough to change this step. 

Please test the changes locally using Cypress tests.

You will need to change also all the following steps.

The final code for this step has changed, so the solution (the next step seed code also has to change), and to keep things consistent, also the seed code for all the following steps and the final solution has to change.

Current output is
<details>
<summary>Cypress tests output (click to show/hide)</summary>

```
> @freecodecamp/freecodecamp@0.0.1 test:curriculum
> cd ./curriculum && npm test


> @freecodecamp/curriculum@0.0.0-next.4 test
> ts-node ../node_modules/mocha/bin/mocha --delay --exit --reporter progress --bail

⠧ Populate tests.
block being tested: learn-accessibility-by-building-a-quiz



  566 passing (7s)
  1 failing

  1) Check challenges
       Check challenges (english)
         learn-accessibility-by-building-a-quiz
           Step 56
             Check tests against solutions
               Solution 1 must pass the tests:

      Check next step for solution!
Test text: <p>You should give the <code>label</code> element a <code>text-align</code> of <code>right</code>.</p>
      + expected - actual

      +right
      
  AssertionError: expected '' to equal 'right'
      at eval (eval at <anonymous> (http://127.0.0.1:8080/js/frame-runner-642a757b341d450c4c22.js:22141:45), <anonymous>:3:8)
      at HTMLDocument.<anonymous> (http://127.0.0.1:8080/js/frame-runner-642a757b341d450c4c22.js:22141:45)
      at mightThrow (http://127.0.0.1:8080/js/frame-runner-642a757b341d450c4c22.js:13564:29)
      at process (http://127.0.0.1:8080/js/frame-runner-642a757b341d450c4c22.js:13632:12)



npm ERR! Lifecycle script `test` failed with error: 
npm ERR! Error: command failed 
npm ERR!   in workspace: @freecodecamp/curriculum@0.0.0-next.4 
npm ERR!   at location: /workspace/freeCodeCamp/curriculum 
```

</details>

**Comment by Insidiae** [comment]
I wasn't able to run the tests on Gitpod, so I missed the part where I had to edit the next step 😅

I updated all solution/seed codes for steps 57-67 to fix the failing tests (and to keep the code consistent along the subsequent steps). I also ran the tests on my local machine (with `--superblock="2022/responsive-web-design"`) and was able to have all tests passing for now!

**Comment by ieahleen** [comment]
> I wasn't able to run the tests on Gitpod

Yeah, for that you need to follow the guide and install cypress first https://contribute.freecodecamp.org/#/how-to-add-cypress-tests?id=cypress-gitpod-setup

I have started the tests on the PR now

**Comment by Insidiae** [comment]
> I have started the tests on the PR now

The tests seem to be passing now, both on my local copy and this PR's GitHub Actions. Is there anything else that needs to be thon before this can be merged?

**Comment by ieahleen** [comment]
it needs to be manually reviewed

**Review by moT01 — APPROVED** [review]
LGTM @Insidiae 🎉 

I was thinking that we should maybe split this up into two steps since now we are having campers add a new selector with one property, then another property in a different selector. So I thought it felt a little strange at first - but they are quite related, so I'm fine with it.

**Review by Sembauke — APPROVED** [review]

**Pull request merged**
