### PR TITLE
Remove CSS from HTML section

### LINKED ISSUE #12659: [beta] Basic HTML - challenge "Add Images to your Website" feels out of place
#### Challenge Name

[Add Images to your Website](http://beta.freecodecamp.com/en/challenges/basic-html-and-html5/add-images-to-your-website)

#### Issue Description

After completing [Basic HTML - Fill in the blank with placeholder text](http://beta.freecodecamp.com/en/challenges/basic-html-and-html5/fill-in-the-blank-with-placeholder-text), I get redirected to the challenge linked above.

This challenge feels out of place since this is one of the first 10 coding challenges that a camper will see. The code changes too much from the last challenge. Additionally, the template code contains things not yet mentioned.

Will the content of this image-challgenge be changed to just teach how to add an image (and skip the CatPhotoApp example)?
Or, should this be moved to a later point?

I like the idea of separating the HTML-course from the CSS-course. The problem is just that the challenges right now follow the format of the previous CatPhotoApp example, where both technologies were taught at once.

#### Browser Information

* Browser Name, Version: Chrome 55
* Operating System: Ubuntu 16.04
* Mobile, Desktop, or Tablet: Desktop

### LINKED ISSUE #12688: [Beta] Remove CSS, Fix Sequencing Issues in Basic HTML & HTML5 Section
#### Challenge Name

This applies to ~2/3 of the challenges in the beta site Basic HTML and HTML5 section.

#### Issue Description

Now that the HTML and CSS challenges are in their own sections (with the HTML section sequenced first), the HTML challenges shouldn't show any CSS since it hasn't been taught yet. Also, there are some sequencing issues around the new challenges - the seed code doesn't quite fit with the challenges before/after, or they introduce something new that isn't carried to following challenges. For example, the `Introduction to HTML5 Elements` challenge's seed code doesn't quite match with the previous challenge, then it adds a `main` tag that isn't carried forward. Here's a list of all the challenges in the section and what should be fixed:

- Say Hello to HTML Elements
- Headline with the h2 Element
- Inform with the Paragraph Element
- Introduction to HTML5 Elements
  - Initial seed code should match the previous challenge (add `h1`, change `p` text)
- Fill in the Blank with Placeholder Text
  - Carry the `main` tag from previous exercise (this applies to every challenge after this one)
- Add Images to your Website
  - Remove CSS (won't affect tests or instructions)
  - Move this challenge so it's after Delete HTML Elements challenge
- Uncomment HTML
  - Paragraph text should carry Kitty Ipsum change from prior challenges
- Comment out HTML
  - Paragraph text should carry Kitty Ipsum change from prior challenges
- Delete HTML Elements
  - Move Add Images challenge after this one
- Link to External Pages with Anchor Elements
  - Remove CSS (won't affect tests or instructions)
- Link to Internal Sections of a Page with Anchor Elements
  - Remove CSS (won't affect tests or instructions)
- Nest an Anchor Element within a Paragraph
  - Note that editor switched back to using the external link
  - Remove CSS (won't affect tests or instructions)
- Make Dead Links using the Hash Symbol
  - Remove CSS (won't affect tests or instructions)
- Turn an Image into a Link
  - Remove CSS (won't affect tests or instructions)
- Create a Bulleted Unordered List
  - Remove CSS (won't affect tests or instructions)
- Create an Ordered List
  - Remove CSS (won't affect tests or instructions)
- Create a Text Field
  - Remove CSS (won't affect tests or instructions)
- Add Placeholder Text to a Text Field
  - Remove CSS (won't affect tests or instructions)
- Create a Form Element
  - Remove CSS (won't affect tests or instructions)
- Add a Submit Button to a Form
  - Remove CSS (won't affect tests or instructions)
- Use HTML5 to Require a Field
  - Remove CSS (won't affect tests or instructions)
- Create a Set of Radio Buttons
  - Remove CSS (won't affect tests or instructions)
- Create a Set of Checkboxes
  - Remove CSS (won't affect tests or instructions)
- Check Radio Buttons and Checkboxes by Default
  - Remove CSS (won't affect tests or instructions)
- Nest Many Elements within a Single Div Element
  - Remove sentence in challenge copy about CSS (this will impact translations)
  - Remove CSS (won't affect tests or instructions)
- Declare the Doctype of an HTML Document
- Define the Head and Body of an HTML Document

I removed `link` tags, everything in the `style` tags, and references to classes on elements when I ran through the challenges on Beta - one very good thing is it doesn't change any of the instructions for the challenges, and the tests still worked. These changes should have minimal impact on the translations.

### PR DESCRIPTION
**Pull request by HKuz**
#### Pre-Submission Checklist

- [x] Your pull request targets the `staging` branch of freeCodeCamp.
- [x] Branch starts with either `fix/`, `feature/`, or `translate/` (e.g. `fix/signin-issue`)
- [x] You have only one commit (if not, [squash](http://forum.freecodecamp.com/t/how-to-squash-multiple-commits-into-one-with-git/13231) them into one commit).
- [x] All new and existing tests pass the command `npm test`. Use `git commit --amend` to amend any fixes.

#### Type of Change

- [x] Small bug fix (non-breaking change which fixes an issue)

#### Checklist:

- [x] Tested changes locally.
- [x] Closes currently open issue (replace XXXX with an issue no): Closes #12688 and Closes #12659 

#### Description

- Removes all CSS in seed code and one reference to CSS that was in a challenge's text (adjusts the translations, too)
- Adds an `<hr>` to delineate instructions part of challenge copy per [this comment](https://github.com/freeCodeCamp/freeCodeCamp/issues/12688#issuecomment-274316858)
- Carries a `main` tag that's introduced with a new challenge through the seed code
- Fixed one test in `Turn an Image into a Link` challenge to remove the class name reference
- Makes a re-order edit as suggested in #12659 and also moves the `Introduction to HTML5 Elements` challenge back a bit to flow more logically with the other challenges
- for good measure, changes "Free Code Camp" to "freeCodeCamp" 😄

### CODE REVIEW

**Comment by dhcodes** [comment]
@HKuz you may need to rebase your branch (`git pull --rebase upstream staging`) and then push this again with `-f` to get resolve the conflict.

**Comment by HKuz** [comment]
Thanks @dhcodes - I'll fix these now. I thought this might happen if the 'change Instructions to hr' PR got merged first 😄

**Review by raisedadead — APPROVED** [review]
#### :sparkles: :sparkles: **LGTM.** :sparkles: :sparkles: 

Thanks @HKuz

**Comment by HKuz** [comment]
Thanks for the QA @raisedadead!  👍 🎇

**Comment by lebanon777** [comment]
Tanx

**Pull request merged**
