### PR TITLE
Add pronunciation note for IIFE

### PR DESCRIPTION
**Pull request by bhagerty**
Beginners won't be sure how to pronounce "IIFE." It's helpful to provide pronunciation information in situations like this.

Checklist:

- [X] I have read [freeCodeCamp's contribution guidelines](https://contribute.freecodecamp.org).
- [X] My pull request has a descriptive title (not a vague title like `Update index.md`)
- [X] My pull request targets the `master` branch of freeCodeCamp.
- [X] All the files I changed are in the same world language, for example: only English changes, or only Chinese changes, etc.

Closes #XXXXX

### CODE REVIEW

**Comment by Sky020** [comment]
Whilst I find the name humorous to say, I do not think `IIFE` is supposed to be pronounced, as much as spelled-out. The only reference to `iffy` I can find is a blog post from a Wikipedia article.

If others are fine with the inclusion of this, then sure (it will make some chuckle), but I do not see it bringing any clarity/useful information to the lesson.

**Comment by RandellDawson** [comment]
It really is irrelevant how it is pronounced.  What is important, is what it does and the existing wording already takes care of that.  I think this PR should be closed, but will see what other mods think.

**Comment by nhcarrigan** [comment]
I'm in favour of closing this as well. (Also, I've always read it as an acronym, not "iffy").

**Comment by RandellDawson** [comment]
Thank you for opening this pull request.

This is a standard message notifying you that we’ve reviewed your pull request and have decided not to merge it. We would welcome future pull requests from you.

Thank you and happy coding.

**Pull request closed without merging**
