### PR TITLE
chore: format curriculum

### PR DESCRIPTION
**Pull request by ojeytonwilliams**
- [x] I have read [freeCodeCamp's contribution guidelines](https://github.com/freeCodeCamp/freeCodeCamp/blob/master/CONTRIBUTING.md).
- [x] My pull request has a descriptive title (not a vague title like `Update index.md`)
- [x] My pull request targets the `master` branch of freeCodeCamp.
- [x] None of my changes are plagiarized from another source without proper attribution.
- [x] All the files I changed are in the same world language (for example: only English changes, or only Chinese changes, etc.)
- [x] My changes do not use shortened URLs or affiliate links.

Provides a script, `formatCurriculum`, that takes the existing English curriculum, parses each challenge and transforms the instructions and descriptions into standard GFM.  In addition, where possible, it 

- re-writes html entities as their corresponding characters
- wraps bare-urls in code blocks (unless they're intentionally bare)
- converts html into markdown

The result is that the challenges are much easier to read.  Also, this is PR is a necessary step before #36879 can be fixed - as all challenges need to be in this format before the parser can be changed.

This isn't the prettiest script, but it's quite well tested!

### CODE REVIEW

**Comment by ojeytonwilliams** [comment]
@raisedadead the linter is failing this, but the errors are either stylistic or just plain wrong (like claiming a url is bare when it isn't.  I'm planning to shift to `remark-lint` anyway (because it has a -fix option!), but for the time being, that's what's going on .

**Comment by ojeytonwilliams** [comment]
I just discovered it messes up when dealing with the Word Blanks challenge. It doesn't escape the _s properly, so I've blocked this until I figure out what I've done wrong.

**Comment by ojeytonwilliams** [comment]
@raisedadead it's been a bit of windy road getting here, but it seems to be in a good spot.  It's possible that some challenges look slightly odd after this if they made heavy use of html, but none that I've found.

I'd still like to change how the linter is called - it's hard-coded to English for the time being.  Also, lint-staged still checks all languages (same as master), so those challenges will need formatting before that's particularly useful.

Nonetheless I think it's worth looking at, since I'm not planning to change how the formatter behaves unless a bug is found.

**Comment by raisedadead** [comment]
Yes, we would be wanting to configure the linter and even the markdown parser to be able to use other languages. Chinese curriculum is our focus next.

I will take a look at the code soon.

**Comment by thecodingaviator** [comment]
@ojeytonwilliams I am wondering if this is something we're still thinking of doing

**Comment by RandellDawson** [comment]
@thecodingaviator Yes it is.  We are just keeping it blocked until a few more things are implemented first.

**Comment by RandellDawson** [comment]
@ojeytonwilliams What do you think about turning `tools/scripts/formatter/README.txt` into a markdown file?

**Comment by ojeytonwilliams** [comment]
@RandellDawson I don't want to invest too much more time into this, since it's only going to be used once, but I think it's okay now.

**Review by raisedadead — APPROVED** [review]

**Pull request merged**
