### PR TITLE
Modify if statement

### PR DESCRIPTION
**Pull request by nataliecardot**
Change the solution so an empty string is returned when num is less than 1 rather than less than 0 for consistency with instructions.

- [x] I have read [freeCodeCamp's contribution guidelines](https://github.com/freeCodeCamp/freeCodeCamp/blob/master/CONTRIBUTING.md).
- [x] My pull request has a descriptive title (not a vague title like `Update index.md`)
- [x] My pull request targets the `master` branch of freeCodeCamp.
- [x] None of my changes are plagiarized from another source without proper attribution.
- [x] All the files I changed are in the same world language (for example: only English changes, or only Chinese changes, etc.)
- [x] My changes do not use shortened URLs or affiliate links.

Closes #XXXXX

### CODE REVIEW

**Comment by RandellDawson** [comment]
@nataliecardot Please check all the boxes above to let us know your PR meets all the specified requirements.

Thank you.

**Review by nataliecardot — COMMENTED** [review]
Added a test

**Comment by nataliecardot** [comment]
Okay, I think I'm finished making the changes for the if statement change/new test. Not sure if I did everything right (this is my first experience submitting a pull request), so let me know if something is amiss.

**Comment by RandellDawson** [comment]
@nataliecardot One more thing while you are at it.  I noticed the [Intermediate Challenge in the Guide](https://github.com/freeCodeCamp/freeCodeCamp/blob/master/guide/english/certifications/javascript-algorithms-and-data-structures/basic-algorithm-scripting/repeat-a-string-repeat-a-string/index.md) will return an incorrect result, so maybe you could add that file change to the same branch, so it shows up on this PR?

**Comment by nataliecardot** [comment]
I wasn't sure how to add that file change to this branch, so I submitted a new pull request for that change.

**Comment by RandellDawson** [comment]
@nataliecardot When you made your other changes to the file, then under Commit changes, you would have just selected the first option (see below).
image
Can you make the commit to this current PR instead and close the other PR?

Thank you.

**Comment by nataliecardot** [comment]
I just did so. Thanks for all your help!

**Comment by RandellDawson** [comment]
@nataliecardot Thank you for updating those changes.  I went ahead and made one other commit here instead of asking you to do it.  We made a recent change which allows us to remove the assert message argument values, so I went ahead and removed them since we are working on this file anyway.

**Review by RandellDawson — APPROVED** [review]
This PR looks good to me now.

**Review by Manish-Giri — APPROVED** [review]
@nataliecardot LGTM. Thank You for your contribution.

**Comment by IsadoraFerrao** [comment]
:)

**Pull request merged**
