### PR TITLE
chore: drop lerna

### PR DESCRIPTION
**Pull request by ojeytonwilliams**
- chore: use workspaces, fix deps
- chore: install core-js@2 (required by babel)

### CODE REVIEW

**Comment by ojeytonwilliams** [comment]
I'll fix the conflicts whenever we're ready to give this a go.

**Review by raisedadead — COMMENTED** [review]
To be clear this does not change anything about how we install & develop or build currently? Let's land this on Monday morning (your's and mine) when you are arround.

**Comment by ojeytonwilliams** [comment]
It shouldn't change anything about deployment, no. I'm cautiously optimistic.

The main thing I'm curious about is how renovate handles workspaces.

**Review by ahmaxed — DISMISSED** [review]
It builds, it develops, and I checked most of the components where the code has been altered. LGMT

**Pull request merged**
