### PR TITLE
fix : replace test cases' string to make more sense

### LINKED ISSUE #36119: Incorrect Test Cases: Match All Numbers and Match All Non-Numbers Lessons
**Describe your problem and how to reproduce it:**
1. Click Javascript Algorithms And Data Structures Certification (300 hours)
2. Click Regular Expressions section
3. Click Match All Numbers lesson
4. Exercise instructions and test cases written below do not match the code template on the right. Under the hood tests run correctly and consistent with the code template. 
5. The exercise instruction sentence and test cases explanations under it should be changed to match the real case. It is causing confusion.
6. Same thing is present in the next lesson: Match All Non Numbers. 

**Add a Link to the page with the problem:**

https://learn.freecodecamp.org/javascript-algorithms-and-data-structures/regular-expressions/match-all-numbers

**Tell us about your browser and operating system:**
* Browser Name: Google Chrome
* Browser Version: Version 74.0.3729.169 (Official Build) (64-bit)
* Operating System: Linux Mint 18.3 Cinnamon 64-bit

**If possible, add a screenshot here (you can drag and drop, png, jpg, gif, etc. in this box):**

### PR DESCRIPTION
**Pull request by siddhant034**
- [x] I have read [freeCodeCamp's contribution guidelines](https://github.com/freeCodeCamp/freeCodeCamp/blob/master/CONTRIBUTING.md).
- [x] My pull request has a descriptive title (not a vague title like `Update index.md`)
- [x] My pull request targets the `master` branch of freeCodeCamp.
- [x] None of my changes are plagiarized from another source without proper attribution.
- [x] All the files I changed are in the same world language (for example: only English changes, or only Chinese changes, etc.)
- [x] My changes do not use shortened URLs or affiliate links.

Closes #36119

### CODE REVIEW

**Review by moT01 — APPROVED** [review]
LGTM @siddhant034! 🎉

**Comment by RandellDawson** [comment]
I don't see how this improves the challenge.  The tests are just passing strings with letters and numbers in them.  They are not all movie names.

**Comment by moT01** [comment]
They are all movie titles. The issue describes how the challenges say to test "movie titles" then gives `"Your sandwich will be $5.00";` in the seed code. So it was sort of contradictory to have that string there and not a movie title.

**Comment by RandellDawson** [comment]
@moT01 I guess I should have read the instructions closer.  To my defense, I never heard of the movies "9" or "One, Two, Three", but I guess they are movies.

**Review by RandellDawson — APPROVED** [review]

**Comment by RandellDawson** [comment]
Congrats @siddhant034 on your first pull request (PR)! 🎉

Thank you for your contribution to the page! 👍
We're happy to accept these changes, and look forward to future contributions. 📝

**Comment by moT01** [comment]
Yea, I had to look them up to see if they were actually movie titles.

**Pull request merged**
