### PR TITLE
fix(client): refactor to use correct i18n t type

### PR DESCRIPTION
**Pull request by ShaunSHamilton**
Checklist:

- [x] I have read [freeCodeCamp's contribution guidelines](https://contribute.freecodecamp.org).
- [x] My pull request has a descriptive title (not a vague title like `Update index.md`)
- [x] My pull request targets the `main` branch of freeCodeCamp.
- [x] I have tested these changes either locally on my machine, or GitPod.

Imports TFunction from `i18n-react` into `prop-types`, and replaces current incorrect typedefs _before it is too late_

### CODE REVIEW

**Review by ojeytonwilliams — COMMENTED** [review]
Silly question, probably, but why introduce `TFunc` instead of just `TFunction`?

It makes it seem like `TFunc` has something to do with `prop-types`, which is a little misleading.

**Comment by ShaunSHamilton** [comment]
> why introduce TFunc instead of just TFunction?

Silly answer, probably, what if we want to change it from `TFunction<'translation'>`? Also, it is shorter.

> It makes it seem like TFunc has something to do with prop-types, which is a little misleading.

It does. In the same way `ChallengeFile` has something to do with `prop-types` - universal truth for common types - no need to look externally for a common way to type something (we do plan on moving (and probably renaming) `prop-types`, once we no longer use `PropTypes....`)

**Comment by ojeytonwilliams** [comment]
> what if we want to change it from TFunction<'translation'>? Also, it is shorter.

Well, in that case we can figure out a solution.  I'm not sure we should be solving problems we don't even anticipate having! And, yes, it *is*, but it's also suddenly unfamiliar to someone that's used to `i18n-react`.

**Comment by ShaunSHamilton** [comment]
> > what if we want to change it from TFunction<'translation'>? Also, it is shorter.
> 
> Well, in that case we can figure out a solution. I'm not sure we should be solving problems we don't even anticipate having! And, yes, it _is_, but it's also suddenly unfamiliar to someone that's used to `i18n-react`.

🤷‍♂️ Should this PR just correctly type to `t: TFunction<'translation'>` ?

**Comment by ojeytonwilliams** [comment]
>  Should this PR just correctly type to `t: TFunction<'translation'>` ?

Yes :+1:

**Review by ojeytonwilliams — APPROVED** [review]
LGTM :+1:

**Review by naomi-lgbt — APPROVED** [review]
Looks good to me.

**Pull request merged**
