### PR TITLE
Changed description for challenge Filter Arrays with filter

### LINKED ISSUE #10912: The description is wrog
Challenge [Filter Arrays with filter](https://www.freecodecamp.com/challenges/filter-arrays-with-filter#?solution=%0Avar%20oldArray%20%3D%20%5B1%2C2%2C3%2C4%2C5%2C6%2C7%2C8%2C9%2C10%5D%3B%0A%0A%2F%2F%20Only%20change%20code%20below%20this%20line.%0A%0Avar%20newArray%20%3D%20oldArray.filter(function(val)%7B%0A%20%20return%20val%3C6%3B%0A%7D)%3B%0A) has an issue.
User Agent is: <code>Mozilla/5.0 (Windows NT 6.3; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/31.0.1650.63 Safari/537.36</code>.
Please describe how to reproduce this issue, and include links to screenshots if possible.

My code:
```javascript

var oldArray = [1,2,3,4,5,6,7,8,9,10];

// Only change code below this line.

var newArray = oldArray.filter(function(val){
  return val<6;
});

```

---------------------
The right code he less than six but  the test case  said : You should have filtered out all values from the array that are greater than 5.

### PR DESCRIPTION
**Pull request by ktajpuri**
#### Pre-Submission Checklist

- [x] Your pull request targets the `staging` branch of FreeCodeCamp.
- [x] Branch starts with either `fix/`, `feature/`, or `translate/` (e.g. `fix/signin-issue`)
- [x] You have only one commit (if not, [squash](http://forum.freecodecamp.com/t/how-to-squash-multiple-commits-into-one-with-git/13231) them into one commit).
- [x] All new and existing tests pass the command `npm run test-challenges`. Use `git commit --amend` to amend any fixes.
#### Type of Change

- [x] Small bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds new functionality)
- [ ] Breaking change (fix or feature that would change existing functionality)
- [ ] Add new translation (feature adding new translations)
#### Checklist:

- [x] Tested changes locally.
- [x] Closes currently open issue (10912): Closes #10912
#### Description

Changed description of the test cases for challenge https://www.freecodecamp.com/challenges/filter-arrays-with-filter from 
" You should have filtered out all values from the array that are greater than 5 " to "You should have filtered out all values from the array that are less than 6 "

### CODE REVIEW

**Comment by Bouncey** [comment]
Discussing in #10912

**Comment by Bouncey** [comment]
Thanks @ktajpuri, please [squash](http://forum.freecodecamp.com/t/how-to-squash-multiple-commits-into-one-with-git/13231) your commits into one so we can get this merged!

Great work!

**Comment by ktajpuri** [comment]
@bouncey done. Cheers !

**Comment by Bouncey** [comment]
Great work @ktajpuri 

## Thanks for contributing :tada:

**Pull request merged**
