### PR TITLE
.navbar padding tweaks

### PR DESCRIPTION
**Pull request by chrisroselli**
Hey @hallaathrad, @QuincyLarson pointed me in your direction for a padding suggestion for the gravatar in the righthand corner of the navbar. Thought it might look cleaner flush with the right side of the viewport.

FreeCodeCamp rules!

### CODE REVIEW

**Comment by chrisroselli** [comment]
Hey @hallaathrad, just thought it might look cleaner, strictly from a design prospective. Thanks for reviewing it though. As I'm sure you can see I'm a noob with Git/Github and am also excited about successfully pushing my first pull request!

Thanks again!

**Comment by hallaathrad** [comment]
you have indeed made me notice something. how about we make it padding-left:15px, and leave the avatar alone? Thus, there's 30px on both sides of the navbar. I dunno why there was an additional 15px to the left, and that does indeed look awkward.

What do you think, @chrisroselli?

**Comment by chrisroselli** [comment]
Sure ya, that sounds good. That way both sides will be even.

**Comment by hallaathrad** [comment]
Terrific!, so make the change, squash or amend your PR and we'll be good to go :)

**Comment by hallaathrad** [comment]
Cool, just commit those changes, squash and we're good to go for merging

**Comment by chrisroselli** [comment]
Tried to figure out how to squash the commits and made a bit of a mess, sorry.

**Comment by hallaathrad** [comment]
I've hit you up on gitter. Let's get it fixed together

**Pull request merged**
