### PR TITLE
chore(curriculum): add transcript to what is HTML lecture

### PR DESCRIPTION
**Pull request by jdwilkin4**
## Summary of changes

Each lecture video will have a transcript below the video and just before the questions.

Checklist:

- [x] I have read and followed the [contribution guidelines](https://contribute.freecodecamp.org).
- [x] I have read and followed the [how to open a pull request guide](https://contribute.freecodecamp.org/how-to-open-a-pull-request/).
- [x] My pull request targets the `main` branch of freeCodeCamp.
- [x] I have tested these changes either locally on my machine, or GitPod.

## Result

Screenshot 2024-10-31 at 11 45 08 AM

### CODE REVIEW

**Comment by moT01** [comment]
Wonder if we should add a new heading for transcripts - and maybe make the transcripts collapsible so they don't take up so much room.

**Comment by jdwilkin4** [comment]
@moT01 

Here is what it looks like with the `h2` and collapsible section
Screenshot 2024-10-31 at 9 52 18 AM


Here is what it looks like with just the collapsible section

Screenshot 2024-10-31 at 9 53 23 AM

I like the second option. It seems to fit better than the first IMO

**Comment by jdwilkin4** [comment]
Here is what the text looks like for the collapsible section

Screenshot 2024-10-31 at 10 56 41 AM

**Comment by moT01** [comment]
Working on adding the transcript. Hoping to get https://github.com/freeCodeCamp/freeCodeCamp/pull/56825 in first, so I can use the generic challenge with the transcripts. Also, I wouldn't consider this MVP - the curriculum content is more priority I think. But we'll get it in so we can start adding transcripts.

**Comment by jdwilkin4** [comment]
Adding a note here.

But we decided to not include transcripts for the MVP.
The transcripts will be added started in 2025

**Pull request closed without merging**
