### PR TITLE
Fix broken link for local campsites in the challenge join-a-campsite-in-your-city

### LINKED ISSUE #8637: Facebook campsite group link is very hard to find
#### Challenge Name
Challenge - [Join Campsite in your city](https://www.freecodecamp.com/challenges/join-a-campsite-in-your-city)

#### Issue Description
This challenge says that we must find campsite city on the list, but when I open link, there is not any list of campsites. It redirects to camperbot page, which redirects to gitter

### PR DESCRIPTION
**Pull request by nishant-tomer**
#### Pre-Submission Checklist

- [x] Your pull request targets the `staging` branch of FreeCodeCamp.
- [x] Branch starts with either `fix/`, `feature/`, or `translate/` (e.g. `fix/signin-issue`)
- [x] You have only one commit (if not, [squash](https://github.com/FreeCodeCamp/FreeCodeCamp/wiki/git-rebase#squashing-multiple-commits-into-one) them into one commit).
- [x] All new and existing tests pass the command `npm run test-challenges`. Use `git commit --amend` to amend any fixes.
#### Type of Change

- [x] Small bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds new functionality)
- [ ] Breaking change (fix or feature that would change existing functionality)
- [ ] Add new translation (feature adding new translations)
#### Checklist:

- [x] Tested changes locally.
- [x] Closes currently open issue: Closes #8637
#### Description

Updated this [line](https://github.com/FreeCodeCamp/FreeCodeCamp/blob/staging/seed/challenges/00-getting-started/getting-started.json#L664): 

Changes:
Old Link : https://github.com/FreeCodeCamp/freecodecamp/wiki/List-of-Free-Code-Camp-city-based-Campsites
New link: https://github.com/FreeCodeCamp/FreeCodeCamp/wiki/LocalGroups-List

### CODE REVIEW

**Comment by raisedadead** [comment]
Closing because this is not your first PR. Please look into some of the help wanted issues. We appreciate the hard work and the contribution, sincerely but "first timers only" issues are to be resolved only once per contributor.

**Comment by nishant-tomer** [comment]
Sure, sure. I understand now.

**Comment by nishant-tomer** [comment]
And please tell me one more thing, Where do i find out what all the labels mean? 
I couldn't find a source of explanation.

**Comment by raisedadead** [comment]
https://github.com/FreeCodeCamp/FreeCodeCamp/wiki/FreeCodeCamp-Issue-Labels

Well the one that says "easy" is now renamed as "first-timers-only", which reminds us that the wiki itself needs to be updated. :wink:

**Pull request closed without merging**
