### PR TITLE
fix(i18n): update chinese translation of applied accessibility

### PR DESCRIPTION
**Pull request by ZhichengChen**
- [x] I have read [freeCodeCamp's contribution guidelines](https://github.com/freeCodeCamp/freeCodeCamp/blob/master/CONTRIBUTING.md).
- [x] My pull request has a descriptive title (not a vague title like `Update index.md`)
- [x] My pull request targets the `master` branch of freeCodeCamp.
- [x] None of my changes are plagiarized from another source without proper attribution.
- [x] All the files I changed are in the same world language (for example: only English changes, or only Chinese changes, etc.)
- [x] My changes do not use shortened URLs or affiliate links.

Closes #XXXXX

### CODE REVIEW

**Comment by ZhichengChen** [comment]
@RandellDawson  Because there are so many files in PR(#36368), so I decide to split is to some small PR. Maybe we should close PR(#36368) and focus on those small changes. thanks for your patient.

**Comment by RandellDawson** [comment]
@ZhichengChen If you want to work with fewer files, then feel free to close the other PR.

**Comment by ZhichengChen** [comment]
@RandellDawson @raisedadead thanks, I have closed PR(#36368 )

**Comment by raisedadead** [comment]
Hi @ZhichengChen can we get some to peer review the code please?

**Comment by ZhichengChen** [comment]
@raisedadead sure,

**Review by NoraZheng — APPROVED** [review]
@raisedadead  Hi! First timer here and would love to contribute to freeCodeCamp. Can I review and approve other people's PR without seeking permission?

**Comment by raisedadead** [comment]
> Can I review and approve other people's PR without seeking permission?

Absolutely. And on that note we would love your help, please get in touch with @miyaliu666 to help you with this.

We have a chinese forum: https://chinese.freecodecamp.org/forum/ which you should join and connect with other contributors.

Happy contributing.

**Comment by miyaliu666** [comment]
Hi @NoraZheng, happy to know you're interested in contributing:) Here's some background for you https://chinese.freecodecamp.org/forum/t/chinese-translation-and-contributors-meeting-on-20th-sept-2019/502, https://chinese.freecodecamp.org/forum/t/topic/250. Could you send me an email (miya@freecodecamp.org) or add me WeChat (Hello_MrT), so I can introduce you to the group of contributors discussing collaboration details?

**Pull request closed without merging**
