### PR TITLE
replace a test with correct code and …

### PR DESCRIPTION
**Pull request by JoolsMcFly**
…change 'function' to 'selector' in description

#### Pre-Submission Checklist

- [x] Your pull request targets the `staging` branch of freeCodeCamp.
- [x] Branch starts with either `fix/`, `feature/`, or `translate/` (e.g. `fix/signin-issue`)
- [x] You have only one commit (if not, [squash](http://forum.freecodecamp.com/t/how-to-squash-multiple-commits-into-one-with-git/13231) them into one commit).
- [x] All new and existing tests pass the command `npm test`. Use `git commit --amend` to amend any fixes.

#### Type of Change

- [x] Small bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds new functionality)
- [ ] Breaking change (fix or feature that would change existing functionality)
- [ ] Add new translation (feature adding new translations)

#### Checklist:

- [x] Tested changes locally.

#### Description

`Target Elements by id Using jQuery` challenge incorrectly references `:even` selector as a `function`.

I've also changed the third test from
```
"assert(code.match(/<button class=\"btn btn-default target\" id=\"target2\">/g), 'message: Only use jQuery to add these classes to the element.');"
```
to
```
"assert(code.match(/\\$\\(\".target:nth-child\\(2\\)\"\\)/g) || code.match(/\\$\\('.target:nth-child\\(2\\)'\\)/g) || code.match(/\\$\\(\".target\"\\).filter\\(\":nth-child\\(2\\)\"\\)/g) || code.match(/\\$\\('.target'\\).filter\\(':nth-child\\(2\\)'\\)/g), 'message: Only use jQuery to add these classes to the element.');"
```

which allows the use if `filter` method.

Thanks!

### CODE REVIEW

**Comment by JoolsMcFly** [comment]
Hey guys,

any update on this? Anything I need to change?

Thanks.

**Review by Annajane88 — CHANGES_REQUESTED** [review]
How i need do

**Comment by JoolsMcFly** [comment]
?

**Review by erictleung — APPROVED** [review]
LGTM! :+1: Thanks for contributing! :sparkles:

**Comment by JoolsMcFly** [comment]
👍

**Pull request merged**
