### PR TITLE
Enable newlines in Authentication with Socket.IO, test 3

### PR DESCRIPTION
**Pull request by Relsig**
Both my original formatting and glitch's "format this file" button add a newline between "io.use("  and  "passport.authorize"

`.+` catches one or more of anything that isn't a newline.
`[^]+` catches one or more of anything including newlines. 

This change updates the test accordingly so people who use glitch's formatting don't get left searching for assistance

With this change both:
```
io.use(
  passportSocketIo.authorize(
```

and

```
io.use(passportSocketIo.authorize(
```

will be caught

---

- [x] I have read [freeCodeCamp's contribution guidelines](https://github.com/freeCodeCamp/freeCodeCamp/blob/master/CONTRIBUTING.md).
- [x] My pull request has a descriptive title (not a vague title like `Update index.md`)
- [x] My pull request targets the `master` branch of freeCodeCamp.
- [x] None of my changes are plagiarized from another source without proper attribution.
- [x] All the files I changed are in the same world language (for example: only English changes, or only Chinese changes, etc.)
- [x] My changes do not use shortened URLs or affiliate links.

### CODE REVIEW

**Comment by Relsig** [comment]
Or perhaps

```
/io\.use\(\s*\w+\.authorize\(/gi
```

 would be a less permissive match which would prevent some potential but unlikely to ever occur false positives. This would prevent someone from adding comments inbetween the two but I'm not sure anyone would reasonably do that.

I still prefer [^] but the aforementioned regex is also a decent candidate for the test.

**Comment by ojeytonwilliams** [comment]
>  I'm not sure anyone would reasonably do that.

People are rather unpredictable, I think it's best to err on the side of caution. 
```js
/io\.use\(\s*\w+\.authorize\(/
```
(no flags needed) should be fine, since it passes what we want to pass.  @RandellDawson any weird edge cases you can think of where this would fail?

**Comment by Relsig** [comment]
I updated it to the less permissive match per your request. This still won't catch someone adding a comment between io.use( and passportSocketIo.authorize( but the original didn't either and [^]+ is far too permissive.

accounting for comments is dirty business and if you choose to do so I'll defer to my betters for that regular expression

**Comment by ojeytonwilliams** [comment]
@Relsig thanks for making those changes.  We've been using the following:

````md
### After Test
<div id='js-teardown'>

```js
const removeJSComments = str => str.replace(/\/\*[\s\S]*?\*\/|\/\/.*$/gm, '');
```

</div>
````
to remove comments and it hasn't caused any problems we're aware of.

**Review by ojeytonwilliams — APPROVED** [review]
LGTM :+1: 

I don't think we need to worry too much about comment removal.

**Review by moT01 — APPROVED** [review]
LGTM @Relsig 🎉 Congratulations on your first contribution to freeCodeCamp 🎉 We look forward to future contributions.

For future reference, you should try and give your branch a more descriptive name. Thanks and happy coding!

**Pull request merged**
