### PR TITLE
fix: remove algolia indices and urls from translations

### LINKED ISSUE #41029: Algolia 404 error showing in console when Spanish home page loads.
When the [Spanish home page](https://www.freecodecamp.org/espanol) loads, I see an Algolia 404 error.

The English and Chinese home page do not appear to have this error.  I also test incognito on Chrome and the error still persists.

image

### PR DESCRIPTION
**Pull request by scissorsneedfoodtoo**
Checklist:

- [x] I have read [freeCodeCamp's contribution guidelines](https://contribute.freecodecamp.org).
- [x] My pull request has a descriptive title (not a vague title like `Update index.md`)
- [x] My pull request targets the `main` branch of freeCodeCamp.
- [ ] All the files I changed are in the same world language, for example: only English changes, or only Chinese changes, etc.

Closes #41029

This PR moves the Algolia index names and News search page URLs out of the `translation.json` files to prevent accidental changes on CrowdIn.

It also adds some basic tests for the search bar.

### CODE REVIEW

**Review by raisedadead — APPROVED** [review]
LGTM. 

@RandellDawson This would be a good test of what happens we delete stuff on a translated file both the source and translation.

**Comment by RandellDawson** [comment]
@raisedadead   @nhcarrigan and I have a plan.

1. Merge any PR with changes to the English source (when they are ready)
2. Upload the English source via the normal Crowdin upload workflow
3. I will manually add all the translations that were made two the `intros.json` and `translations.json` (Nick will approve)
4. Run the download for these files (after a small tweak to the config to allow both files to be downloaded but only approved strings come down).  

This is the easiest way to bring us back into sync.  Hopefully, we will not be making any further changes to the non-English versions of these files outside of Crowdin in the future.

**Comment by scissorsneedfoodtoo** [comment]
@RandellDawson, looking at the `translations.json` file, it seems like there are about 12 links there. I think 11 of them are related to the footer, and one is for an error message.

Would it be better to extract those footer links from the `translations.json` file and merge them with the ones in `trending.json`? We'd probably have to rename `trending.json` to something like `footer-links.json`, too. That's assuming we'll handle all the footer links and text localization in house.

I'm thinking this might be the way to go because we've had some issues with text overflow on News, and need to make changes before updating the theme.

If we'll handle those on Crowdin as well, is it possible to hide those links so they're not accidentally changed?

**Comment by RandellDawson** [comment]
> If we'll handle those on Crowdin as well, is it possible to hide those links so they're not accidentally changed?

@scissorsneedfoodtoo We can hide any string in the JSON files by creating a special action to hide specific keys' values by key name (i.e. `footer.links.about`).  I count 11 urls in the `translations.json` file.  9 are in apart of `footer.links`, one is `donate.other-ways-url`, and the last is `flash.really-weird`.

**Comment by scissorsneedfoodtoo** [comment]
@RandellDawson, awesome, that sounds like a plan. Looking over the file again we shouldn't need to remove any other keys, at least as far as I can tell.

**Comment by ojeytonwilliams** [comment]
Let's not mix translatable and untranslatable content in one file if we can avoid it.  We already have files like `trending.json` for content that differs between the languages, but does not want translating.  I think we should do the same here.

**Pull request merged**
