### PR TITLE
fix(actions): typo in workflow title

### LINKED ISSUE #46500: Typo (translions) in workflow title
One of the workflows has title with "translions" instead of "translations"

image

---

This looks something that can be fixed by "first time" code contributors to this repository. Here are the files that you should be looking at to work on a fix:

File: https://github.com/freeCodeCamp/freeCodeCamp/blob/main/.github/workflows/no-prs-to-translation.yml

The fix would simply be to fix translions -> translations

Please make sure you read [our guidelines for contributing](https://contribute.freecodecamp.org/#/), we prioritize contributors following the instructions in our guides. Join us in [our chat room](https://chat.freecodecamp.org/channel/contributors) or [the forum](https://forum.freecodecamp.org/c/contributors/3) if you need help contributing, our moderators will guide you through this.

Sometimes we may get more than one pull requests. We typically accept the most quality contribution followed by the one that is made first.

Happy contributing.

### PR DESCRIPTION
**Pull request by mikailaliyev**
fixed typo "translions" in workflow title to "translations"

Checklist:

- [ x] I have read [freeCodeCamp's contribution guidelines](https://contribute.freecodecamp.org).
- [ x] My pull request has a descriptive title (not a vague title like `Update index.md`)
- [x ] My pull request targets the `main` branch of freeCodeCamp.
- [x ] I have tested these changes either locally on my machine, or GitPod.

Closes #46500

### CODE REVIEW

**Review by raisedadead — APPROVED** [review]

**Review by moT01 — APPROVED** [review]
LGTM @mikailaliyev 🎉 Congratulations on your first contribution to the freeCodeCamp repo 🎉

**Comment by mikailaliyev** [comment]
> LGTM @mikailaliyev 🎉 Congratulations on your first contribution to the freeCodeCamp repo 🎉

Thanks!

**Comment by moT01** [comment]
I spoke too soon - let's see if these tests pass

**Comment by mikailaliyev** [comment]
> I spoke too soon - let's see if these tests pass.
> 
> Edit: I didn't mean it doesn't look good - just need to get the tests passing. There should be nothing else you need to do here.

I see. Well it was my first contribution, so it is very interesting!

**Review by Sboonny — APPROVED** [review]
Whether it pass or not, thanks for taking time for it, and your contribution 🎉.

**Pull request merged**
