### PR TITLE
Fixed grammatical error in Manipulate Arrays with push

### LINKED ISSUE #8563: grammatical error in description
#### Challenge Name

https://www.freecodecamp.com/challenges/manipulate-arrays-with-push#?solution=%0A%2F%2F%20Example%0Avar%20ourArray%20%3D%20%5B%22Stimpson%22%2C%20%22J%22%2C%20%22cat%22%5D%3B%0AourArray.push(%5B%22happy%22%2C%20%22joy%22%5D)%3B%20%0A%2F%2F%20ourArray%20now%20equals%20%5B%22Stimpson%22%2C%20%22J%22%2C%20%22cat%22%2C%20%5B%22happy%22%2C%20%22joy%22%5D%5D%0A%0A%2F%2F%20Setup%0Avar%20myArray%20%3D%20%5B%5B%22John%22%2C%2023%5D%2C%20%5B%22cat%22%2C%202%5D%5D%3B%0A%0A%2F%2F%20Only%20change%20code%20below%20this%20line.%0AmyArray.push(%5B%22dog%22%2C%203%5D)%3B%0A%0A

#### Issue Description

"takes one or more parameter "  should read
"takes one or more parameters " 

#### Browser Information

* Browser Name, Version: *
* Operating System: *
* Mobile, Desktop, or Tablet: *

#### Your Code

```js
// If relevant, paste all of your challenge code in here

```

### PR DESCRIPTION
**Pull request by saahilk**
#### Pre-Submission Checklist

- [ x] Your pull request targets the `staging` branch of FreeCodeCamp.
- [x ] Branch starts with either `fix/`, `feature/`, or `translate/` (e.g. `fix/signin-issue`)
- [x ] You have only one commit (if not, [squash](https://github.com/FreeCodeCamp/FreeCodeCamp/wiki/git-rebase#squashing-multiple-commits-into-one) them into one commit).
- [x ] All new and existing tests pass the command `npm run test-challenges`. Use `git commit --amend` to amend any fixes.
#### Type of Change

- [x ] Small bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds new functionality)
- [ ] Breaking change (fix or feature that would change existing functionality)
- [ ] Add new translation (feature adding new translations)
#### Checklist:

- [ ] Tested changes locally.
- [x ] Closes currently open issue (e.g. `Closes #XXXX`): Closes  
#### Description

Changed "parameter" to "parameters" and "it" to "them".
Closes  #8563

### CODE REVIEW

**Comment by raisedadead** [comment]
@saahilk Please, check our [**Guidelines for Contributing**](https://github.com/FreeCodeCamp/FreeCodeCamp/blob/staging/CONTRIBUTING.md).

You have added issue nos to the PR Title and the commits.

Edit your PR title
> Fixed grammatical error(issue #8563)

to
> Fixed grammatical error in Manipulate Arrays with push

Same goes for your commit message. One your local machine:

1. `git commit --amend`
2. Change the commit message to remove the issue nos.
3. `git push origin fix/grammatical-error --force`

**Comment by saahilk** [comment]
@raisedadead 
I made the changes as told.Please tell if anything else needs to be done.Sorry for the trouble.

**Comment by raisedadead** [comment]
@saahilk You have to edit your commit message also.

> Same goes for your commit message. One your local machine:
> 1. git commit --amend
> 2. Change the commit message to remove the issue nos.
> 3. git push origin fix/grammatical-error --force

If you need any assistance reach out to the [Contributors Chat room](https://gitter.im/FreeCodeCamp/HelpContributors).

**Comment by saahilk** [comment]
@raisedadead 
I'm currently using github interface only.Will i have to download git on my pc to make the changes?

**Comment by raisedadead** [comment]
@saahilk Yes. 

> Please, check our [**Guidelines for Contributing**]
> If you need any assistance reach out to the [Contributors Chat room](https://gitter.im/FreeCodeCamp/HelpContributors).

**Comment by raisedadead** [comment]
Closed by #8642

@saahilk This has been resolved in another PR. 

Please have a look at the other open issues and see what you can work on, looking forward to your contribution.

**Pull request closed without merging**
