### PR TITLE
Adjust text formatting per Chinese copywriting guidelines

### PR DESCRIPTION
**Pull request by ihavecoke**
### Description

Refined text formatting to follow the recommendations from: https://sparanoid.com/note/chinese-copywriting-guidelines/

Checklist:

- [x] I have read and followed the [contribution guidelines](https://contribute.freecodecamp.org).
- [x] I have read and followed the [how to open a pull request guide](https://contribute.freecodecamp.org/#/how-to-open-a-pull-request).
- [x] My pull request targets the `main` branch of freeCodeCamp.
- [x] I have tested these changes either locally on my machine, or GitPod.

### Motivation

This change aims to improve the readability and professionalism of the copy by following the best practices outlined in the CJK Copywriting Guidelines. Specifically, it addresses:

- Adding spaces between English and Chinese words
- Adding spaces between numbers and units
- Using fullwidth punctuation for Chinese text
- Using halfwidth Arabic numerals
- Using halfwidth punctuation for English sentences
- Using correct casing for proper nouns
- Avoiding jargons and abbreviations

These adjustments will enhance the overall reading experience for both Chinese and English audiences.

### CODE REVIEW

**Comment by ilenia-magoni** [comment]
why did you change Korean and Japanese files? you said it is about improving *Chinese* text formatting

**Review by majestic-owl448 — CHANGES_REQUESTED** [review]
why did you change Korean and Japanese files? you said it is about improving Chinese text formatting

the Chinese-Traditional files are generated through a script, so please do not change those.

**Review by naomi-lgbt — CHANGES_REQUESTED** [review]
In addition to Ilenia's comment, both intro.json and translations.json are edited through Crowdin, and should not be changed manually through GitHub.

**Comment by miyaliu666** [comment]
Thank you for adjusting these formats @ihavecoke 

You may fill out [this form](https://docs.google.com/forms/d/e/1FAIpQLSdWC609yj1_2afEX0G8AGQyrkGj7bhj1J4XWgCt4BJGuzQk5g/viewform) to receive the guidelines we send to Chinese translation contributors, including how to edit intro.json and translations.json on Crowdin.

**Comment by ihavecoke** [comment]
Thank you, @miyaliu666 @ilenia-magoni @naomi-lgbt, for reviewing the changes. Based on your feedback, I will be closing this pull request and making the necessary modifications as per your suggestions.

**Pull request closed without merging**
