### PR TITLE
chore(package): Update Font Awesome and remove Ionicon dependency

### LINKED ISSUE #13798: Replace Ionic icons with their Font Awesome equivalents and remove Ionic as a dependency

### PR DESCRIPTION
**Pull request by rachelsinclair**
#### Pre-Submission Checklist

- [x] Your pull request targets the `staging` branch of freeCodeCamp.
- [x] Branch starts with either `fix/`, `feature/`, or `translate/` (e.g. `fix/signin-issue`) **[well, `chore/`]**
- [x] You have only one commit (if not, [squash](http://forum.freecodecamp.org/t/how-to-squash-multiple-commits-into-one-with-git/13231) them into one commit).
- [x] All new and existing tests pass the command `npm test`. Use `git commit --amend` to amend any fixes.

#### Type of Change

- [ ] Small bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds new functionality)
- [x] Breaking change (fix or feature that would change existing functionality)
- [ ] Add new translation (feature adding new translations)

#### Checklist:

- [x] Tested changes locally.
- [x] Addressed currently open issue (replace XXXXX with an issue no in next line)

#### Description

Update Font Awesome from 4.7 to 5. Update existing Font Awesome icon
references to match version 5 syntax. Replace all Ionicon references
with Font Awesome icons and remove all files relating to Ionicon.

Closes #13798

### CODE REVIEW

**Review by raisedadead — APPROVED** [review]
Hi @hctpscl we should probably add the built files out of the version control?

i.e ADD the `public/js/lib/fontawesome` to `.gitignore`

Isn't that a build step?

**Comment by hctpscl** [comment]
Those files aren't built, they're just a static assets. Is there a better place for them to be? Any pointers you can give me regarding the file structure would be much appreciated.

**Comment by raisedadead** [comment]
Oh in that case they are where they should be. Thanks. I was confused as to we would have them from the package already. Don't worry I'll pull this down and get back to you?

**Comment by hctpscl** [comment]
I've made a change to SocialIcons.jsx - unfortunately I can't check this component locally because of the auth0 issue.

**Comment by raisedadead** [comment]
Okay cool do not worry about the auth setup. I'll test those parts and leave a feedback. Nice work BTW.

**Comment by raisedadead** [comment]
@hctpscl thanks a lot for the PR. Sorry about the delay in getting this merged.

**Pull request merged**
