### PR TITLE
fix(curriculum): update solution to match seed

### LINKED ISSUE #38829: curriculum-challenges-solution-update
**Describe your problem and how to reproduce it:**
Challenge criteria are updated but solution is not updated yet.
Here's the [challenge](https://www.freecodecamp.org/learn/javascript-algorithms-and-data-structures/functional-programming/pass-arguments-to-avoid-external-dependence-in-a-function)

and hers's the [solution](https://github.com/freeCodeCamp/freeCodeCamp/blob/master/curriculum/challenges/english/02-javascript-algorithms-and-data-structures/functional-programming/pass-arguments-to-avoid-external-dependence-in-a-function.english.md) on GitHub which is currently unable to pass all the tests for the challenge.

**Add a Link to the page with the problem:**

**Tell us about your browser and operating system:**
* Browser Name: Google Chrome
* Browser Version: 81.0.4044.138
* Operating System: Windows OS

**If possible, add a screenshot here (you can drag and drop, png, jpg, gif, etc. in this box):**
Screenshot (132)

### PR DESCRIPTION
**Pull request by vsasvipul0605**
…ish.md

Checklist:

- [x] I have read [freeCodeCamp's contribution guidelines](https://contribute.freecodecamp.org).
- [x] My pull request has a descriptive title (not a vague title like `Update index.md`)
- [x] My pull request targets the `master` branch of freeCodeCamp.
- [x] All the files I changed are in the same world language, for example: only English changes, or only Chinese changes, etc.

Closes #38829

According to recent changes on site, the arrow function is not there. So, here's the updated solution for the updated challenge.

### CODE REVIEW

**Review by ojeytonwilliams — APPROVED** [review]
LGTM :+1:

**Review by erictleung — APPROVED** [review]
LGTM! 👍

**Comment by ojeytonwilliams** [comment]
@vsasvipul0605 Congrats on your first pull request (PR)! 🎉

Thank you for your contribution to the page! 👍
We're happy to accept these changes, and look forward to future contributions. 📝

**Comment by ojeytonwilliams** [comment]
By the way, @vsasvipul0605, if you want to keep using your fork you'll need to get a new version of master from upstream, since it will be out of sync now this PR has been merged.

**Comment by vsasvipul0605** [comment]
@ojeytonwilliams okay and thanks for merging the pull request. This will motivate me to contribute more and more.

**Comment by vsasvipul0605** [comment]
and can anyone please tell me how can I become contributor in freecodecamp?
after how many PR's or any such criteria?

**Comment by ojeytonwilliams** [comment]
Well, you're already a contributor now that this PR has been merged.  As for anything beyond that, it's not really something I can talk about with any authority.  Personally I just contributed PRs and helped out a bit in Gitter, but I don't think there's a formal process.

**Pull request merged**
