### PR TITLE
Fixed Typographical Error in guide/english/react/index.md

### PR DESCRIPTION
**Pull request by iamrajiv**
- [x] I have read [freeCodeCamp's contribution guidelines](https://github.com/freeCodeCamp/freeCodeCamp/blob/master/CONTRIBUTING.md).
- [x] My pull request has a descriptive title (not a vague title like `Update index.md`)
- [x] My pull request targets the `master` branch of freeCodeCamp.
- [x] None of my changes are plagiarized from another source without proper attribution.
- [x] All the files I changed are in the same world language (for example: only English changes, or only Chinese changes, etc.)
- [x] My changes do not use shortened URLs or affiliate links.

### CODE REVIEW

**Review by theNaut1lus — CHANGES_REQUESTED** [review]
@iamrajiv 

`Your first argument is going to be your JSX`

instead of this it will be more suitable to change it to 

`Your first argument is going to be your JSX code`

followed by the code and then the explanation

`your JSX` sounds odd. 

for example:- we don't say your JavaScript, we say your JavaScript Code.
Hopefully this makes some sense

**Comment by iamrajiv** [comment]
> @iamrajiv
> 
> `Your first argument is going to be your JSX`
> 
> instead of this it will be more suitable to change it to
> 
> `Your first argument is going to be your JSX code`
> 
> followed by the code and then the explanation
> 
> `your JSX` sounds odd.
> 
> for example:- we don't say your JavaScript, we say your JavaScript Code.
> Hopefully this makes some sense

**Comment by iamrajiv** [comment]
> @iamrajiv
> 
> `Your first argument is going to be your JSX`
> 
> instead of this it will be more suitable to change it to
> 
> `Your first argument is going to be your JSX code`
> 
> followed by the code and then the explanation
> 
> `your JSX` sounds odd.
> 
> for example:- we don't say your JavaScript, we say your JavaScript Code.
> Hopefully this makes some sense

thankyou

**Comment by iamrajiv** [comment]
thankyou @co16353sidak for pointing out

**Review by cmccormack — APPROVED** [review]
This looks good to me 👍.  Thank you for your contribution!

**Pull request merged**
