### PR TITLE
fix(client): Insufficient color contrast on highlighted code block

### LINKED ISSUE #42405: Insufficient color contrast on highlighted code block in Dark Mode
**Affected page**
[https://www.freecodecamp.org/learn/javascript-algorithms-and-data-structures/object-oriented-programming/define-a-constructor-function](https://www.freecodecamp.org/learn/javascript-algorithms-and-data-structures/object-oriented-programming/define-a-constructor-function)

**To Reproduce**

1. Go to [https://www.freecodecamp.org/learn/](https://www.freecodecamp.org/learn/). Login & switch to Dark mode from Menu.
2. Click on **Java Script Algorithm and Data Structure Certification**course
3. Scroll down to **'Object Oriented Programming'** module & open '**Define Constructor Function**' page.
4. Highlight the code block in the theory section by selecting & dragging with the mouse.

**Expected behavior**
On highlighting, the code becomes unreadable due to failing color contrast. This is a WCAG violation. There should be sufficient color contrast ratio (4.5:1) between text and background even when highlighted.

**Screenshots**
image

**System:**
 - Device: Laptop
 - OS: Windows 10
 - Browser: Edge (chromium based)
 - Version: 91.0.864.41 (Official build) (64-bit)

### PR DESCRIPTION
**Pull request by PrashantSakre**
…Dark Mode

Checklist:

- [x] I have read [freeCodeCamp's contribution guidelines](https://contribute.freecodecamp.org).
- [x] My pull request has a descriptive title (not a vague title like `Update index.md`)
- [x] My pull request targets the `main` branch of freeCodeCamp.
- [x] I have tested these changes either locally on my machine, or GitPod.

Closes #42405

I think this solves the issue.

### CODE REVIEW

**Comment by PrashantSakre** [comment]
This is the result I got after

Before
Screenshot

After
Screenshot 2021-06-09 at 11 43 57 AM

**Review by huyenltnguyen — COMMENTED** [review]
Hi @PrashantSakre, thanks for the PR!

The current selection color is `#b3d4fc`, which appears to be from the default prismjs stylesheet (https://github.com/PrismJS/prism/blob/master/themes/prism.css#L40).

I'm guessing that their CSS selector is more specific than ours, so it overrides our `selection-color`. I wonder if we can set the selection color in our custom stylesheets instead.

That would be adding the following code to [prism.css](https://github.com/freeCodeCamp/freeCodeCamp/blob/main/client/src/components/layouts/prism.css) and [prism-night.css](https://github.com/freeCodeCamp/freeCodeCamp/blob/main/client/src/components/layouts/prism-night.css) and not having to use the `!important` rule:

```css
pre[class*="language-"]::selection, pre[class*="language-"] ::selection,
code[class*="language-"]::selection, code[class*="language-"] ::selection {            
  background: var(--selection-color);    
}
```

**Comment by PrashantSakre** [comment]
Hi @huyenltnguyen 

As in the above images the code you mention is already written but it's taking default prismjs stylesheet because it's in higher priority. So I think adding the !importent rule is required

And also I tried adding the above code to both files it's still the same case.

**Comment by huyenltnguyen** [comment]
Ah! Sorry, I didn't test it locally before I made the suggestion.

So I just got a chance to try it now.

In the stylesheet for dark mode (`prism-night.css`), we will need to add `.night` to the selectors add to achieve higher specificity. For light mode (`prism.css`) though, we will need to add `.default` to beat prism. `night` and `default` are the values we use for theme preferences, btw. 

The correct code should be:

```css
/* prism-night.css */
.night pre[class*='language-']::selection,
.night pre[class*='language-'] ::selection,
.night code[class*='language-']::selection,
.night code[class*='language-'] ::selection {
  background: var(--selection-color);
}

/* prism.css */
.default pre[class*='language-']::selection,
.default pre[class*='language-'] ::selection,
.default code[class*='language-']::selection,
.default code[class*='language-'] ::selection {
  background: var(--selection-color);
}
```

And here is the result:

| Dark | Light |
| --- | --- |
Screen Shot 2021-06-10 at 02 25 20 | Screen Shot 2021-06-10 at 02 26 45 |

Notice that the selection color on light mode is a bit darker, it is the `blue-dark-translucent` from our [color lists](https://github.com/freeCodeCamp/freeCodeCamp/blob/main/client/src/components/layouts/variables.css#L64).

**Comment by PrashantSakre** [comment]
Oo yes I understand and,  Thank you so much for your time

And I updated the files

**Review by huyenltnguyen — APPROVED** [review]
@PrashantSakre LGTM! Thank you for helping improve the accessibility of FCC 👍 

I really appreciate the cross browser testing (I'm very lazy when it comes to this).

**Review by raisedadead — APPROVED** [review]

**Pull request merged**
