### PR TITLE
docs(i18n): reviewing current italian translation of README.md

### PR DESCRIPTION
**Pull request by majestic-owl448**
Checklist:

- [x] I have read [freeCodeCamp's contribution guidelines](https://contribute.freecodecamp.org).
- [x] My pull request has a descriptive title (not a vague title like `Update index.md`)
- [x] My pull request targets the `master` branch of freeCodeCamp.
- [x] All the files I changed are in the same world language, for example: only English changes, or only Chinese changes, etc.

Closes #XXXXX

### CODE REVIEW

**Comment by Ieahleen** [comment]
to do: 
[] Integrate updates from #39170/#39381

**Comment by raisedadead** [comment]
Ping.

**Comment by Ieahleen** [comment]
sorry, will let someone faster work on it

**Comment by RandellDawson** [comment]
@Ieahleen There is no rush.  Please feel free to open this PR back up and work on it at your own pace.  Any change that improves a document's translation is better than no change at all.

**Comment by raisedadead** [comment]
Hi @Ieahleen I left a post on the forum Staff category about this.

**Pull request closed without merging**
