### PR TITLE
fix(curriculum): add regex to chai assertions for double and single quotes

### LINKED ISSUE #37611: Style sensitivity in QA Functional Tests
**Describe your problem and how to reproduce it:**
**Tell us what's happening:**
Test is failing on FCC while passing in the testrunner output. 
The FCC system requires you to use ' (single quotes) in your test case, while the test runner and language obviously do not. Worse still, using the built in formatter on Glitch changes single quotes to double quotes. So formatting your Glitch code will cause test failures on FCC.

**Your code so far**
Failing code excerpt (note the double quotes):
```js
assert.equal(
  res.body.surname,
  "Colombo",  // This line is problematic
  'res.body.surname should be "Colombo"'
);
```        
Passing code (change to single quotes. meaning is unchanged, purely a style difference):
```js
assert.equal(
  res.body.surname,
  'Colombo',  // This line works
  'res.body.surname should be "Colombo"'
);
```

Similar problem with destructuring. This code passes in the testrunner output, fails on FCC.
```js
test('send {surname: "da Verrazzano"}', function(done) {
        /** place the chai-http request code here... **/
        chai
          .request(server)
          .put("/travellers")
          .send({ surname: "da Verrazzano" })
          .end((err, { status, type, body }) => {  // This proves problematic
            /** place your tests inside the callback **/
            assert.equal(status, 200, "response status should be 200");
            assert.equal(type, 'application/json');

            assert.equal(body.name, 'Giovanni');
            assert.equal(body.surname, 'da Verrazzano');
            done();
          });
      });
```
Adjusting it to remove destructuring passes on FCC:
```js
test('send {surname: "da Verrazzano"}', function(done) {
        /** place the chai-http request code here... **/
        chai
          .request(server)
          .put("/travellers")
          .send({ surname: "da Verrazzano" })
          .end((err, res) => {     // Remove destructuring to pass on FCC
            /** place your tests inside the callback **/
            assert.equal(res.status, 200, "response status should be 200");
            assert.equal(res.type, 'application/json');

            assert.equal(res.body.name, 'Giovanni');
            assert.equal(res.body.surname, 'da Verrazzano');
            done();
          });
      });
```

**Add a Link to the page with the problem:**
https://www.freecodecamp.org/learn/information-security-and-quality-assurance/quality-assurance-and-testing-with-chai/run-functional-tests-on-an-api-response-using-chai-http-iii---put-method

**Tell us about your browser and operating system:**
* Browser Name: Chrome 
* Browser Version: 77.0.3865.120
* Operating System: Win10

**If possible, add a screenshot here (you can drag and drop, png, jpg, gif, etc. in this box):**

### PR DESCRIPTION
**Pull request by ShaunSHamilton**
Checklist:

- [x] I have read [freeCodeCamp's contribution guidelines](https://contribute.freecodecamp.org).
- [x] My pull request has a descriptive title (not a vague title like `Update index.md`)
- [x] My pull request targets the `master` branch of freeCodeCamp.
- [x] All the files I changed are in the same world language, for example: only English changes, or only Chinese changes, etc.

Closes #37611

Following on from this thread on the forum, it has been determined that the tests failed due to the assertions testing only for a response with single quotes: https://www.freecodecamp.org/forum/t/quality-assurance-and-testing-with-chai-run-functional-tests-on-an-api-response-using-chai-http-iii-put-method/381400/12

I am not sure if I should remove the check for quotes completely with something like this:
```
/Colombo/
```

### CODE REVIEW

**Comment by Sky020** [comment]
Could possibly close:
Closes #17744

**Comment by Sky020** [comment]
Solves part of #38837

**Comment by moT01** [comment]
Blocked because of the [pinned code freeze issue](https://github.com/freeCodeCamp/freeCodeCamp/issues/38308) - The PR can still be fixed up and reviewed, just not merged at the moment.

**Comment by raisedadead** [comment]
Limitations removed on Coding Interview Prep Challenges.

**Pull request closed without merging**
