### PR TITLE
fix(curriculum): update hotel feedback form

### LINKED ISSUE #56098: step 22 hotel feedback form small fixes
https://github.com/freeCodeCamp/freeCodeCamp/blob/db5854ecf6900af4ce952b4d2bd536ea75aa9671/curriculum/challenges/english/25-front-end-development/workshop-hotel-feedback-form/66a96127422411756204bc1b.md?plain=1#L10-L12

Needed fixes:
```md
Below the label element => Below the `label` element
another checkbox input => another checkbox `input`
Add another label => Add another `label`
```

---

This looks like something that can be fixed by "first-time" code contributors to this repository. The files you should look at to work on a fix are those linked above.

Please make sure you read our [guidelines for contributing](https://contribute.freecodecamp.org/#/), we prioritize contributors following the instructions in our guides. Join us in our [chat room](https://discord.gg/PRyKn3Vbay) or our [forum](https://forum.freecodecamp.org/c/contributors/3) if you need help contributing; our moderators will guide you through this.

Sometimes we may get more than one pull request. We typically accept the most quality contribution followed by the one that is made first.

Happy contributing.

### PR DESCRIPTION
**Pull request by trulyabdullah**
Checklist:

- [x] I have read and followed the [contribution guidelines](https://contribute.freecodecamp.org).
- [x] I have read and followed the [how to open a pull request guide](https://contribute.freecodecamp.org/how-to-open-a-pull-request/).
- [x] My pull request targets the `main` branch of freeCodeCamp.
- [ ] I have tested these changes either locally on my machine, or GitPod.

Closes #56098

Updated the 66a96127422411756204bc1b.md file in hotel feedback form.

### CODE REVIEW

**Review by majestic-owl448 — CHANGES_REQUESTED** [review]
Those are not backticks

**Comment by trulyabdullah** [comment]
My apologies. I have made the necessary changes.

**Review by majestic-owl448 — APPROVED** [review]
LGTM 👍

**Comment by trulyabdullah** [comment]
Thanks.

**Review by gikf — APPROVED** [review]

**Comment by gikf** [comment]
Hi @trulyabdullah. Congrats on your first pull request (PR)! 🎉

Thank you for your contribution to the page! 👍
We are happy to accept these changes and look forward to future contributions. 📝

**Comment by trulyabdullah** [comment]
Hi @gikf 

Thank you a lot. I was really nervous this time since I was contributing to such a large codebase even though the change was very small. 

I am looking forward to making more good contributions in the future.

Thanks for merging the PR.

**Pull request merged**
