### PR TITLE
Added Awk Guide

### PR DESCRIPTION
**Pull request by bauripalash**
- [x] I have read [freeCodeCamp's contribution guidelines](https://github.com/freeCodeCamp/freeCodeCamp/blob/master/CONTRIBUTING.md).
- [x] My pull request has a descriptive title (not a vague title like `Update index.md`)
- [x] My pull request targets the `master` branch of freeCodeCamp.
- [x] None of my changes are plagiarized from another source without proper attribution.
- [x] My changes do not use shortened URLs or affiliate links.
- [x] All the files I changed are in the same world language (for example: only English changes, or only Chinese changes, etc.)

### CODE REVIEW

**Review by moT01 — CHANGES_REQUESTED** [review]
Thanks for the PR @bauripalash - we are moving away from using images in these articles. If you remove that, we can merge this. Thanks.

**Comment by bauripalash** [comment]
@moT01 Please Take A Look

**Comment by RandellDawson** [comment]
@bauripalash You still have a link to an image.  Someone with a screen reader will not be able to make any use of the image.

**Comment by bauripalash** [comment]
Done! @RandellDawson Take A Look

**Review by moT01 — APPROVED** [review]
Looks good @bauripalash - thanks for contributing to freeCodeCamp! 🎉

**Pull request merged**
