### PR TITLE
fixed create-decimal-numbers-with-javascript challenge external link

### LINKED ISSUE #42795: wrong external link in Create Decimal Numbers with JavaScript
The `href` of the external link in the challenge is `https://en.wikipedia.org/wiki/Floating_point#Accuracy_problems` but it points to a page of a music album, the `href` should be `https://en.wikipedia.org/wiki/Floating-point_arithmetic#Accuracy_problems`

Issue #40749 was asking what to do of external links to avoid such issues, if we have an article talking of this topic I would suggest we use that instead of a wikipedia link

Challenge link: https://www.freecodecamp.org/learn/javascript-algorithms-and-data-structures/basic-javascript/create-decimal-numbers-with-javascript
Challenge file: curriculum/challenges/english/02-javascript-algorithms-and-data-structures/basic-javascript/create-decimal-numbers-with-javascript.md

### PR DESCRIPTION
**Pull request by vhlnd**
Checklist:

- [x ] I have read [freeCodeCamp's contribution guidelines](https://contribute.freecodecamp.org).
- [ x] My pull request has a descriptive title (not a vague title like `Update index.md`)
- [x ] My pull request targets the `main` branch of freeCodeCamp.
- [x] I have tested these changes either locally on my machine, or GitPod.

Closes #42795

### CODE REVIEW

**Comment by gikf** [comment]
Hey @randomvi,

non-English files should not be changed directly. When needed they will be updated using the translation workflow. Could you revert those changes, leaving just link change for English?

**Review by gikf — APPROVED** [review]
Looks good to me! :+1:

**Review by moT01 — APPROVED** [review]
LGTM @randomvi 🎉 Thanks for contributing and congratulations on your first contribution to the freeCodeCamp repository 🎉 We welcome future contributions 👍

**Comment by randomvi** [comment]
> LGTM @randomvi 🎉 Thanks for contributing and congratulations on your first contribution to the freeCodeCamp repository 🎉 We welcome future contributions 👍

awesome 👍

**Comment by scissorsneedfoodtoo** [comment]
Thanks for updating this link @randomvi. We don't seem to have a good article on accuracy problems when using floating point numbers, so this is a good alternative for now.

**Pull request merged**
