### PR TITLE
fix(a11y): search input

### PR DESCRIPTION
**Pull request by bbsmooth**
Checklist:

- [x] I have read and followed the [contribution guidelines](https://contribute.freecodecamp.org).
- [x] I have read and followed the [how to open a pull request guide](https://contribute.freecodecamp.org/#/how-to-open-a-pull-request).
- [x] My pull request targets the `main` branch of freeCodeCamp.
- [x] I have tested these changes either locally on my machine, or GitPod.

Closes #XXXXX

While working on another PR that involves the search feature, I noticed that the search input did not have a proper accessible name set on it, and it wasn't being completely hidden from screen readers (the label text was still able to be accessed even when the search was hidden). So I got rid of the `label` as it wasn't performing its intended function since its `for` attribute did not point to the search input, and added an `aria-label` to the search input instead.

I know that using `componentDidMount` to add an `aria-label` to the search input is probably causing some of you to roll your eyes, but I wasn't able to find an (easy) way to do this using the API for the search widget. I believe we might be able to create our own custom search widget using the API, but that seems like a lot of work for just adding an attribute. Or, it appears that the most recent versions of algolia React InstantSearch have better accessibility support and we might not need this hack if we upgrade.

### CODE REVIEW

**Comment by naomi-lgbt** [comment]
Should I see a difference in behaviour from production?

I tested this with NVDA and tabbed to the search box, and heard the same messages on this PR as I do in production.

**Comment by bbsmooth** [comment]
Try using the up/down arrow keys to navigate instead. 

In narrow view (when the search input only shows when the menu is expanded), use the down arrow key to navigate from the Menu button to the avatar button. You will hear the word "search" between those two buttons. This is the search `label` that is not being hidden properly when the menu is not expanded.

Also, that `label` element has a `for` attribute that is not pointing correctly to the search input because the search input doesn't have an `id` for it to point to in the first place. So the `label` is really useless here.

Also, I just noticed that on the main landing page the search input is coded differently than when you are on the curriculum pages and the search label is actually pointing to the search input because the input has an `id`. So perhaps the real solution here is to make the search that is used on the main landing page is used everywhere.

P.S. I just tested the donate, profile, and settings pages as well and they are all using the broken search label as well. So it seems that just the main landing page has this coded correctly and all other pages have the bad search label.

**Comment by bbsmooth** [comment]
Good search implementation on main landing page:

```
<form action="" class="ais-SearchBox-form" data-cy="ais-SearchBox-form" role="search">
  <label class="sr-only" for="ais-SearchBox-input">Search</label>
  <input autocapitalize="none" autocomplete="off" autocorrect="off" id="ais-SearchBox-input" class="ais-SearchBox-input" maxlength="512" placeholder="Search 9,000+ tutorials" spellcheck="false" type="search" value="">
  <button class="ais-SearchBox-submit" type="submit">
    <span class="sr-only">Submit search terms</span>
    <svg class="ais-SearchBox-submitIcon" height="10" viewBox="0 0 40 40" width="10" xmlns="http://www.w3.org/2000/svg"><path d="M26.804 29.01c-2.832 2.34-6.465 3.746-10.426 3.746C7.333 32.756 0 25.424 0 16.378 0 7.333 7.333 0 16.378 0c9.046 0 16.378 7.333 16.378 16.378 0 3.96-1.406 7.594-3.746 10.426l10.534 10.534c.607.607.61 1.59-.004 2.202-.61.61-1.597.61-2.202.004L26.804 29.01zm-10.426.627c7.323 0 13.26-5.936 13.26-13.26 0-7.32-5.937-13.257-13.26-13.257C9.056 3.12 3.12 9.056 3.12 16.378c0 7.323 5.936 13.26 13.258 13.26z"></path>
    </svg>
  </button>
</form>
```

Bad search implementation on all other pages:

```
<div class="fcc_search_wrapper">
  <label class="fcc_sr_only" for="fcc_instantsearch">Search</label>
<div>
<div role="textbox"><div class="ais-SearchBox">
  <form novalidate="" class="ais-SearchBox-form" action="" role="search">
    <input type="search" placeholder="Search 9,000+ tutorials" autocomplete="off" autocorrect="off" autocapitalize="none" spellcheck="false" required="" maxlength="512" class="ais-SearchBox-input" value="">
    <button type="submit" title="Submit search terms" class="ais-SearchBox-submit">
    <svg class="ais-SearchBox-submitIcon" xmlns="http://www.w3.org/2000/svg" width="10" height="10" viewBox="0 0 40 40" aria-hidden="true"><path d="M26.804 29.01c-2.832 2.34-6.465 3.746-10.426 3.746C7.333 32.756 0 25.424 0 16.378 0 7.333 7.333 0 16.378 0c9.046 0 16.378 7.333 16.378 16.378 0 3.96-1.406 7.594-3.746 10.426l10.534 10.534c.607.607.61 1.59-.004 2.202-.61.61-1.597.61-2.202.004L26.804 29.01zm-10.426.627c7.323 0 13.26-5.936 13.26-13.26 0-7.32-5.937-13.257-13.26-13.257C9.056 3.12 3.12 9.056 3.12 16.378c0 7.323 5.936 13.26 13.258 13.26z"></path></svg></button>
    </form>
  </div>
</div>
```

**Review by naomi-lgbt — APPROVED** [review]
Thanks for the explanation - I see the issue now.

I'd be happy to land this as-is.

**Review by raisedadead — APPROVED** [review]

**Pull request merged**
