### PR TITLE
Fix missing "currentNode" variable declaration in data structures linked list challenges (English)

### PR DESCRIPTION
**Pull request by ZebulanStanphill**
## Description

This PR fixes an issue where the `currentNode` variable in the following challenges is not declared before usage like it should be:

- https://learn.freecodecamp.org/coding-interview-prep/data-structures/remove-elements-from-a-linked-list/
- https://learn.freecodecamp.org/coding-interview-prep/data-structures/search-within-a-linked-list/
- https://learn.freecodecamp.org/coding-interview-prep/data-structures/remove-elements-from-a-linked-list-by-index/
- https://learn.freecodecamp.org/coding-interview-prep/data-structures/add-elements-at-a-specific-index-in-a-linked-list/
- https://learn.freecodecamp.org/coding-interview-prep/data-structures/search-within-a-linked-list

## Checklist

- [x] I have read [freeCodeCamp's contribution guidelines](https://github.com/freeCodeCamp/freeCodeCamp/blob/master/CONTRIBUTING.md).
- [x] My pull request has a descriptive title (not a vague title like `Update index.md`)
- [x] My pull request targets the `master` branch of freeCodeCamp.
- [x] None of my changes are plagiarized from another source without proper attribution.
- [x] All the files I changed are in the same world language (for example: only English changes, or only Chinese changes, etc.)
- [x] My changes do not use shortened URLs or affiliate links.

## Sibling PRs
- Arabic: #35636
- Chinese: #35637
- Portuguese: #35639
- Russian: #35640
- Spanish: #35641

### CODE REVIEW

**Comment by thecodingaviator** [comment]
Was this discussed somewhere?

**Comment by thecodingaviator** [comment]
image

**Comment by RandellDawson** [comment]
Unless @ZebulanStanphill can explain why the extra `var` is needed (which I do not believe it is) to solve this challenge, these 6 PRs should be closed.

**Comment by ZebulanStanphill** [comment]
@thecodingaviator Ah, I did not see that declaration. Note that it is only https://github.com/freeCodeCamp/freeCodeCamp/blob/master/curriculum/challenges/english/08-coding-interview-prep/data-structures/remove-elements-from-a-linked-list.english.md that contains this declaration. Note that the other challenges still lack it.

Notably, it seems inconsistent and bad practice to declare `currentNode` at the top level of the function, since it is only used in the `add` function. (Having it declared at the top-level causes its state to be persisted across method calls, which is not desirable and could lead to confusing/buggy behavior in a practical application.)

I will revise this PR and its siblings to remove the earlier declaration to improve consistency and prevent any unwanted behavior. (Since the Spanish PR is already merged, I'll have to create a new one to fix the duplicated declaration there.)

I created this PR because I noticed errors in the built-in log on some of the challenges, indicating some mistakes in the challenge seeds. So I made PRs to fix these issues, one for each language since the contribution guidelines seem to say that you should only modify the files corresponding to one language in a single PR. There was no prior discussion on these issues; I searched but was unable to find any existing tickets or PRs relating to them, so I assume I am the first to discover them.

**Comment by ZebulanStanphill** [comment]
I have updated this PR to remove the duplicate variable declaration.

Upon further inspection, it appears that the English version of that particular challenge was the only one with the top-level `currentNode` declaration, so the other PRs don't have to be updated.

On a side note, I find it odd that the challenges all use entirely separate files for each language. I would think that a single base file for each challenge could be made with placeholders for the comments and variable names. The final localized versions of the challenges could be generated from these base files, filling in the placeholders with comments and variable names appropriate for each language. It seems like bad practice to me to have all this duplicate code, though I'm afraid I'm not experienced enough to be able to implement a technical solution.

**Comment by thecodingaviator** [comment]
@ZebulanStanphill If we did that, it'll cause huge chaos since all languages would be on the same file so we'd have to wait for translators to check other languages' PRs before we can do anything

**Comment by RandellDawson** [comment]
> On a side note, I find it odd that the challenges all use entirely separate files for each language. I would think that a single base file for each challenge could be made with placeholders for the comments and variable names. The final localized versions of the challenges could be generated from these base files, filling in the placeholders with comments and variable names appropriate for each language. It seems like bad practice to me to have all this duplicate code, though I'm afraid I'm not experienced enough to be able to implement a technical solution.

This is something that is going to be addressed before translations go into production.  There are definitely ways to reuse most of the code in the files (testString, solution, challenge seed).

**Comment by thecodingaviator** [comment]
@ZebulanStanphill I saw that, seems good to me now. Locally scoped variables should be fine too and since we've to add it anyway, this PR already does it

**Review by thecodingaviator — APPROVED** [review]
LGTM! 👍

**Comment by ojeytonwilliams** [comment]
@ZebulanStanphill Thank you for your contribution to the page! :+1:
We're happy to accept these changes, and look forward to future contributions. :memo:

**Pull request merged**
