### PR TITLE
fix(curriculum): Find Characters with Lazy Matching

### LINKED ISSUE #19344: Regular Expressions: Find Characters with Lazy Matching html example
**Describe your problem and how to reproduce it:**
Why the given example uses html snippet? Like it gives idea that regex is good for html parsing. Where is this  https://stackoverflow.com/a/1732454

**Add a Link to the page with the problem:**
https://learn.freecodecamp.org/javascript-algorithms-and-data-structures/regular-expressions/find-characters-with-lazy-matching

### PR DESCRIPTION
**Pull request by hilliarj**
- [x] I have read [freeCodeCamp's contribution guidelines](https://github.com/freeCodeCamp/freeCodeCamp/blob/master/CONTRIBUTING.md).
- [x] My pull request has a descriptive title (not a vague title like `Update index.md`)
- [x] My pull request targets the `master` branch of freeCodeCamp.
- [x] None of my changes are plagiarized from another source without proper attribution.
- [x] All the files I changed are in the same world language (for example: only English changes, or only Chinese changes, etc.)
- [x] My changes do not use shortened URLs or affiliate links.

Closes #19344

### CODE REVIEW

**Review by Manish-Giri — APPROVED** [review]
LGTM.

**Review by RandellDawson — CHANGES_REQUESTED** [review]
While I have zero problem with the actual verbiage being added, I believe the note should go in the Description section and not the Instructions section, since the note is more of a general note and not specific to the Instructions/solving the challenge.

**Comment by chaomt** [comment]
@RandellDawson 
Thanks! Will fix this soon.

**Comment by RandellDawson** [comment]
@hilliarj Why did you close and delete your branch?  We did not get a chance to merge the PR.

**Comment by hilliarj** [comment]
@RandellDawson Apologies, it was an accident.

**Review by RandellDawson — APPROVED** [review]

**Comment by RandellDawson** [comment]
Congrats @hilliarj on your first pull request (PR)! 🎉

Thank you for your contribution to the page! 👍
We're happy to accept these changes, and look forward to future contributions. 📝

**Pull request merged**
