### PR TITLE
feat: update footer

### PR DESCRIPTION
**Pull request by ahmaxed**

### CODE REVIEW

**Comment by ahmadabdolsaheb** [comment]
Screen Shot 2019-10-23 at 2 41 28 PM

**Comment by ahmadabdolsaheb** [comment]
Screen Shot 2019-10-23 at 2 41 28 PM

**Comment by ahmadabdolsaheb** [comment]
Screen Shot 2019-10-23 at 4 52 58 PM

**Comment by raisedadead** [comment]
Light version:

image

**Review by raisedadead — APPROVED** [review]
LGTM

**Pull request merged**
