### PR TITLE
chore(server): Deleted outdated explanation file of how-nonprofit

### LINKED ISSUE #17065: Redirect old nonprofit project path to new description
We need to delete this outdated explanation of our nonprofit projects: `https://www.freecodecamp.org/how-nonprofit-projects-work`

And instead forward the `how-nonprofit-projects-work` tab to this with a 301 redirect: `https://medium.freecodecamp.com/open-source-for-good-1a0ea9f32d5a`

### PR DESCRIPTION
**Pull request by abhikulshrestha22**
changed for the issue #17065

Closes #17065

#### Pre-Submission Checklist

- [x] Your pull request targets the `staging` branch of freeCodeCamp.
- [x] Branch starts with either `fix/`, `feature/`, or `translate/` (e.g. `fix/signin-issue`)
- [x] You have only one commit (if not, [squash](http://forum.freecodecamp.org/t/how-to-squash-multiple-commits-into-one-with-git/13231) them into one commit).
- [x] All new and existing tests pass the command `npm test`. Use `git commit --amend` to amend any fixes.

#### Type of Change

- [ ] Small bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds new functionality)
- [x] Breaking change (fix or feature that would change existing functionality)
- [ ] Add new translation (feature adding new translations)

#### Checklist:

- [x] Tested changes locally.
- [x] Addressed currently open issue (replace XXXXX with an issue no in next line)

Closes #17065

#### Description
Deleted server/views/resources/how-nonprofit-projects-work.jade
Redirected the link /how-nonprofit-projects-work to https://medium.freecodecamp.com/open-source-for-good-1a0ea9f32d5a

### CODE REVIEW

**Review by raisedadead — CHANGES_REQUESTED** [review]
Why are you adding the lock file, in this commit?

**Comment by raisedadead** [comment]
Hi @abhikulshrestha22 yes, sure please visit the contributors chat room [Contributors Chat room](https://gitter.im/FreeCodeCamp/Contributors) we should be able to walk you through it.

**Comment by abhikulshrestha22** [comment]
@raisedadead removed the file package-lock.json.

**Comment by QuincyLarson** [comment]
@raisedadead Ok - could you take another look and verify whether this is ready to merge?

**Review by raisedadead — APPROVED** [review]

**Comment by QuincyLarson** [comment]
@abhikulshrestha22 Thanks again for your help with this!

**Pull request merged**
