### PR TITLE
feat(client): add contribute button on header's navbar

### PR DESCRIPTION
**Pull request by lalshubham**
It's better to have a `Contribute` button for open-source contribution too.
Additionally, translated languages have been added for the `Contribute` button, along with their respective translated documentation page links.

Checklist:

- [x] I have read and followed the [contribution guidelines](https://contribute.freecodecamp.org).
- [x] I have read and followed the [how to open a pull request guide](https://contribute.freecodecamp.org/#/how-to-open-a-pull-request).
- [x] My pull request targets the `main` branch of freeCodeCamp.
- [x] I have tested these changes either locally on my machine, or GitPod.

Closes #XXXXX

Gitpod preview:
Screenshot (389)

Screenshot (387)

### CODE REVIEW

**Review by naomi-lgbt — CHANGES_REQUESTED** [review]
You should not modify the `translation.json` files directly - these are updated in the crowdin flow after a PR is merged.

**Comment by CERTIFIED2003** [comment]
So, should I remove all the changes I made in non-English `translations.json` files, right?

**Review by naomi-lgbt — APPROVED** [review]
Okie dokie, I'm good with this. Would love to get Ahmad's feedback.

**Review by Sboonny — APPROVED** [review]
LGTM 🎉, thank you for your contribution to the page! 👍.

**Comment by ahmadabdolsaheb** [comment]
Thanks for trying to encourage users to contribute by including a button in the navigation. I will monitor the change to see if it will affect clickthrough of other links. The dropdown might have a few other items such as `help` and we might need to drop some of the items to reduce the paradox of choice; however, having a contribute item seems like a good idea for the time being. It would be great if it could go to the bottom of the external links. Additionally, we would appreciate opening an issue before creating a pr so the spec could be finalized before the implementation.

**Comment by CERTIFIED2003** [comment]
Got it @ahmadabdolsaheb

**Pull request merged**
