### PR TITLE
feat(client): center login button

### PR DESCRIPTION
**Pull request by ahmaxed**
Checklist:

- [x] I have read [freeCodeCamp's contribution guidelines](https://contribute.freecodecamp.org).
- [x] My pull request has a descriptive title (not a vague title like `Update index.md`)
- [x] My pull request targets the `main` branch of freeCodeCamp.
- [x] I have tested these changes either locally on my machine, or GitPod.

Closes #XXXXX

### CODE REVIEW

**Review by ojeytonwilliams — COMMENTED** [review]
Can login.css go?  It only targets the login button, to my knowledge (unless there's some react bootstrap stuff that uses it).

**Review by ojeytonwilliams — DISMISSED** [review]
It seemed fairly centred before, but there's a little more padding now:

image

Is that what I should be seeing?

**Comment by ahmadabdolsaheb** [comment]
the big one on the landing page was off.

**Review by ojeytonwilliams — APPROVED** [review]
LGTM :+1:

**Review by ShaunSHamilton — APPROVED** [review]
I see no difference. It still looks off **for one breakpoint**:
image

Although, this seems like just a rounding error that we cannot control without fixing the width of the button/container.

**Pull request merged**
