### PR TITLE
fix: Test fails with comments

### LINKED ISSUE #34861: Use Clockwise Notation - Tests fail if you add any comment code.
On the Basic CSS: Use Clockwise Notation to Specify the Padding of an Element Lesson.

If you fulfil the course as instructed but also add comments in a multi-line format  such as: 
/* 
aaaa
*/
Placed outside of the relevant style block and also within it will cause one of the tests will fail and state 'You should use the clockwise notation to set the padding of blue-box class.' 

Even though the provided  answer is correct, the commenting breaks the test, this is not the case on previous CSS lessons as I usually add comments.
screenshot 2019-01-12 at 20 41 28
screenshot 2019-01-12 at 20 41 28

https://learn.freecodecamp.org/responsive-web-design/basic-css/use-clockwise-notation-to-specify-the-padding-of-an-element

**Tell us about your browser and operating system:**
* Browser Name:  Google Chrome
* Browser Version: Version 71.0.3578.98 (Official Build) (64-bit)
* Operating System: Mac OSX Mojave

**If possible, add a screenshot here (you can drag and drop, png, jpg, gif, etc. in this box):**

### PR DESCRIPTION
**Pull request by ronaldcs**
- [X] I have read [freeCodeCamp's contribution guidelines](https://github.com/freeCodeCamp/freeCodeCamp/blob/master/CONTRIBUTING.md).
- [X] My pull request has a descriptive title (not a vague title like `Update index.md`)
- [X] My pull request targets the `master` branch of freeCodeCamp.
- [X] None of my changes are plagiarized from another source without proper attribution.
- [X] All the files I changed are in the same world language (for example: only English changes, or only Chinese changes, etc.)
- [X] My changes do not use shortened URLs or affiliate links.

Closes #34861

### CODE REVIEW

**Comment by RandellDawson** [comment]
@ronaldcs You missed an edge case.  If I put:
```
/* padding-top: 40px;
```
on last line of code, the challenge fails and it should not, because it is a valid comment.

Personally, I do not think we should be trying to prevent all of these edge cases.

**Review by RandellDawson — CHANGES_REQUESTED** [review]
See my comment regarding edge case which regex does not handle.

**Comment by ronaldcs** [comment]
@RandellDawson I changed it to only look within the `<style>` tag (since, technically, the test will fail if you have `padding-*` within the html) and changed the regex to account for your edge case. Let me know what you think. I agree, probably shouldn't look at every edge case, but this probably gets most use cases.

**Comment by RandellDawson** [comment]
@ronaldcs One other thing I notice is that if you start the challenge from the beginning (Reset) and run the tests, the new test you added lights up green, even if no clockwise notation for the padding of the `blue-box` class div is used.  That should not be checked off when no clockwise notation is used.

**Comment by ronaldcs** [comment]
@RandellDawson got it. Looks like that issue existed before this fix; added a check to ensure user is actually using clockwise notation for that particular test, in addition to not allowing user to use padding-left, etc.

**Comment by RandellDawson** [comment]
If I add the following to the style section, the last test fails.  It is supposed to ignore comments.
```css
/*
  .blue-box {
    background-color: blue;
    color: #fff;
    padding-top: 40px;
  }
*/
```

**Comment by paulywill** [comment]
> @ronaldcs Now, If I add the following to the style section, the last test fails. It is supposed to ignore comments.
> 
> ```css
> /*
>   .blue-box {
>     background-color: blue;
>     color: #fff;
>     padding-top: 40px;
>   }
> */
> ```

I am able to reproduce this.

image

image

**Comment by ronaldcs** [comment]
Doesn't that go against the spirit of what the student is trying to solve?

**Comment by RandellDawson** [comment]
@ronaldcs You are still not ignoring css within a comment in the `style` element.  If you test the following locally, it will fail incorrectly for the last test.   My suggestion is to strip out any comments in the `style` section first and then validate the correct clock-wise notation is being used.  

Also, it may be best to create an additional test which specifically tests that the user is NOT using the padding-xxxx syntax anywhere in the CSS section (once the comments have been stripped of course).

The main idea of the challenge is that the user is:
1. Not using padding-xxxx syntax in the CSS
2. Using clockwise notation in the CSS

If the PR can accomplish the two tasks above while ignoring comments in the CSS, I think that will work.

**Comment by ronaldcs** [comment]
@RandellDawson did you re-pull? My last comment and my last push seem to be out of order. I tried both yours and @paulywill's use cases and it seems to be WAI?

image

**Comment by ronaldcs** [comment]
@RandellDawson your solution in https://github.com/freeCodeCamp/freeCodeCamp/pull/35342 is a better implementation, so we should use it.

**Comment by RandellDawson** [comment]
@ronaldcs Yes, I was testing out something and if it was approved by others, I was going to suggest using something similar in this.  

While we are waiting, would you mind adding a full working solution to the `Solution` section?  Make sure to include all original challenge seed code plus the actual code which solves the challenge.  That needs to be in there anyway so the tests can be validated as passing for a known working solution.

Thanks.

**Comment by ronaldcs** [comment]
> While we are waiting, would you mind adding a full working solution to the `Solution` section? Make sure to include all original challenge seed code plus the actual code which solves the challenge. That needs to be in there anyway so the tests can be validated as passing for a known working solution.

Sure, I will take a look.

**Review by paulywill — APPROVED** [review]
LGTM!

Testing locally, fix appears to working good.

**Review by RandellDawson — APPROVED** [review]
I am fine with these final changes.  After thinking about it, we really don't care if the camper put the padding-xxxx version as long as the clockwise notation is found in the css (outside of comments of course).     The other tests validates the element has the correct values and the last test just makes sure the clockwise notation is used.

**Comment by RandellDawson** [comment]
@ronaldcs Thank you for your patience.  Actually @moT01 found a couple of edge cases that I missed in the regex I recommended.  The original allows the camper to omit the closing } for the blue-box class definition.  I am requesting the following to be used for the last test of this challenge which fixes that issue and a couple other edge cases.
```yml
    testString: const removeCssComments = str => str.replace(/\/\*[\s\S]+?\*\//g, '');assert(/\.blue-box\s*{[\s\S]*padding[\s]*:\s*\d+px\s+\d+px\s+\d+px\s+\d+px(;\s*[^}]+\s*}|;?\s*})/.test(removeCssComments($('style').text())));
```

Also, if you don't mind, could you update the last test for the other  similar challenge (margin clock-wise notation) to:
```yml
    testString: const removeCssComments = str => str.replace(/\/\*[\s\S]+?\*\//g, '');assert(/\.blue-box\s*{[\s\S]*margin[\s]*:\s*\d+px\s+\d+px\s+\d+px\s+\d+px(;\s*[^}]+\s*}|;?\s*})/.test(removeCssComments($('style').text())));
```

**Comment by ronaldcs** [comment]
Got it, sure, I can take care of both @RandellDawson.

**Comment by ronaldcs** [comment]
@RandellDawson @paulywill @moT01 let me know if there are any issues with this last update.

**Review by moT01 — APPROVED** [review]
Tested pretty thoroughly locally, LGTM @ronaldcs!

**Comment by cmccormack** [comment]
Is a function like `remove[Language]Comments` something we could include as a pre-check for all tests where we want to ignore comments?  Might make it a lot easier than requiring we add this per-challenge.

**Comment by RandellDawson** [comment]
@cmccormack I suppose it is possible.  We would have to create our own, as they really do not want to add anymore packages.  Also, I am not sure where the best place to put globally available functions.

**Review by Manish-Giri — APPROVED** [review]
@ronaldcs LGTM. Thank You for your contribution.

**Pull request merged**
