### PR TITLE
build(tools): add node_modules cleanup script

### PR DESCRIPTION
**Pull request by raisedadead**

### CODE REVIEW

**Comment by paulywill** [comment]
@raisedadead What does the clean-up script do?

**Comment by raisedadead** [comment]
We are soon going to update to node 10.x which went into LTS  a couple days ago. This would be a pain for all working locally because we would need to re-install all the dependencies. I am trying to make the setup to be seemless for everyone. 

This particular change should delete all the `node_modules` in all of the packages. I'll update the docs shortly once I have figured out the correct steps.

For now you should be able to merge it though.

I think the steps should just be `npm run clean` followed by `npm  install`, but I'll update the exact steps in a bit on the docs.

**Comment by ValeraS** [comment]
Should we also delete `node_modules` in the root?

**Comment by raisedadead** [comment]
> Should we also delete node_modules in the root?

It really depends, I would delete them? At the minute the root of the repo doesn't have much stuff. So we really don't care. I am just trying to land this in hopes of avoiding my local setup failed at npm install type issues, because we are switching to 10.x

Some binaries get compiled with `node-gyp` like Gatsby. To the best of what I can tell right now, is all the devDeps will move to the root eventually.

**Comment by raisedadead** [comment]
Anyways the point of this script is mostly going to be use it one-off. Instead of asking collaborators, to recursively delete `node_modules`

**Comment by raisedadead** [comment]
P.S Can I get a merge?

**Comment by raisedadead** [comment]
Yes, we can. 

The point is to abstract away the inner tooling which most contributors don't care about. For them steps would be like:

```
npm install
```

```
npm run develop
```

```
npm test
```

Troubleshoot an installation?

```
npm run clean
```

Rinse and repeat! It's more consistent that way? So, while its run mostly once. But it's run by many contributors who are new and reducing any complexity helps. I tend to add simplicity on a ongoing basis.

**Comment by Nirajn2311** [comment]
@raisedadead the “Keep It Simple” method, I like it.

**Pull request merged**
