### PR TITLE
docs(polish): create how to open pull request

### PR DESCRIPTION
**Pull request by mathias3**
- [ x] I have read [freeCodeCamp's contribution guidelines](https://github.com/freeCodeCamp/freeCodeCamp/blob/master/CONTRIBUTING.md).
- [x ] My pull request has a descriptive title (not a vague title like `Update index.md`)
- [x ] My pull request targets the `master` branch of freeCodeCamp.
- [x ] None of my changes are plagiarized from another source without proper attribution.
- [x ] All the files I changed are in the same world language (for example: only English changes, or only Chinese changes, etc.)
- [x ] My changes do not use shortened URLs or affiliate links.

Closes #XXXXX

### CODE REVIEW

**Comment by raisedadead** [comment]
Can you get someone (who speaks the language) to peer review this please, thanks.

**Comment by mathias3** [comment]
> Can you get someone (who speaks the language) to peer review this please, thanks.

I am already accepting PR and fixes to this translated file, but they are rather minor things like typos

**Comment by mathias3** [comment]
> Can you get someone (who speaks the language) to peer review this please, thanks.

there will be always ongoing discussion : should some words be translated or left in English as they are often left untranslated in technical discussion in polish

**Comment by raisedadead** [comment]
I am not sure what you mean, you need to reachout to someone other you who speaks polish to peer review this for us, before we are able to merge this.

**Comment by mathias3** [comment]
> I am not sure what you mean, you need to reachout to someone other you who speaks polish to peer review this for us, before we are able to merge this.

I understand. I have this person doing this right now. She will create PR with her corrections to my PR with translation. She will let you know in this thread when she is done

**Comment by raisedadead** [comment]
> She will create PR with her corrections to my PR with translation. She will let you know in this thread when she is done.

Thanks for letting us know that someone else is working on this.

Regardless of that, you need to ask them to approve and/or request changes to this PR.

See: https://help.github.com/en/github/collaborating-with-issues-and-pull-requests/about-pull-request-reviews#about-pull-request-reviews

**Comment by mathias3** [comment]
closing as changes moved to make Contributing.md in polish #37350

**Pull request closed without merging**
