### PR TITLE
Minor aesthetic changes

### PR DESCRIPTION
**Pull request by justincorrigible**
Subtle but effective.
Changing some of the "bonfire" classes for "challenge" (nothing broken as far as I could tell.
Plus a bit of reorganising in the less files.

### CODE REVIEW

**Comment by SaintPeter** [comment]
Can you please be more specific about what was changed vs. what was merely rearranged?

Did you check all of the different challenge types?  Are you certain the `bonfire-instructions` are not used elsewhere?

**Comment by hallaathrad** [comment]
screen shot 2016-02-04 at 13 33 43

In regards to bonfire-instructions, I went through all show.jade files I could find and changed it.

To be fair and honest, I doubt it'll break anything as it originally only had some nesting for an inner h4. 
I was the one who added all of those classes inside.

A lot of the changes are just me bringing challenge related stuff out of main, and into challenge.less (where as far I understand is where they belong).

**Comment by SaintPeter** [comment]
Groovy.  @QuincyLarson will need to check it out, of course.

**Comment by QuincyLarson** [comment]
@hallaathrad wow - so many improvements! I'm QA'ing now.

**Comment by QuincyLarson** [comment]
@hallaathrad A couple notes on this:
The scroll bar now always shows on the sidebar. Is that intentional?


It looks like you inadvertantly increased the amount of whitespace between elements on the map:

**Comment by hallaathrad** [comment]
@quincylarson the scrollbar has been happening to a few people (Shawna herself being the latest known before you), who solved it by updating both OS and browser to their most recent versions. For the sake of certainty, would you please verify for these? I cannot replicate here.

And I'll check on the paragraph spacing, but I don't recall changing those. Will correct if something is amiss.

**Comment by QuincyLarson** [comment]
@hallaathrad Looks good, except the title elements on various show views have different heights: 

Be sure to check the showZipline and showVideo challenges.

Also, are the tests supposed to be written in monospace font? 

Finally,

**Comment by hallaathrad** [comment]
Fixed the issues with the two jades (some stray bonfire styling I hadn't accounted for) and increased the size of the step descriptions (by taking them into em instead of px).

The test outputs are in the same font they've always been. I've merely changed their spacing and the size of the check/error icons. No fix needed there.

**Pull request merged**
