### PR TITLE
Added Swift Implementation of Counting Sort

### LINKED ISSUE #26859: Need to add implementation for counting sort in Swift
**Describe your problem and how to reproduce it:**
demonstration of counting sort is available but the implementation in specific languages is missing.

**Add a Link to the page with the problem:**
https://github.com/freeCodeCamp/freeCodeCamp/blob/master/guide/english/algorithms/sorting-algorithms/counting-sort/index.md

**Tell us about your browser and operating system:**
* Browser Name: 
* Browser Version: 
* Operating System: 

**If possible, add a screenshot here (you can drag and drop, png, jpg, gif, etc. in this box):**

### PR DESCRIPTION
**Pull request by ayushjain9501**
- [x] I have read [freeCodeCamp's contribution guidelines](https://github.com/freeCodeCamp/freeCodeCamp/blob/master/CONTRIBUTING.md).
- [x] My pull request has a descriptive title (not a vague title like `Update index.md`)
- [x] My pull request targets the `master` branch of freeCodeCamp.
- [x] None of my changes are plagiarized from another source without proper attribution.
- [x] All the files I changed are in the same world language (for example: only English changes, or only Chinese changes, etc.)
- [x] My changes do not use shortened URLs or affiliate links.

Closes #26859

### CODE REVIEW

**Comment by madurachanna** [comment]
I have read freeCodeCamp's contribution guidelines.

**Comment by madurachanna** [comment]
My pull request has a descriptive title (not a vague title like Update index.md)

**Comment by madurachanna** [comment]
magician is here

**Comment by madurachanna** [comment]
No comment

**Review by moT01 — APPROVED** [review]
Looks good @Ayushjain9501! Congratulations on your first contribution to freeCodeCamp!

**Pull request merged**
