### PR TITLE
Fixed typos and edited for clarity

### PR DESCRIPTION
**Pull request by zevski**
- [x ] I have read [freeCodeCamp's contribution guidelines](https://github.com/freeCodeCamp/freeCodeCamp/blob/master/CONTRIBUTING.md).
- [ x] My pull request has a descriptive title (not a vague title like `Update index.md`)
- [ x] My pull request targets the `master` branch of freeCodeCamp.
- [ x] None of my changes are plagiarized from another source without proper attribution.
- [ x] My article does not contain shortened URLs or affiliate links.

If your pull request closes a GitHub issue, replace the XXXXX below with the issue number.

Closes #XXXXX

### CODE REVIEW

**Comment by RandellDawson** [comment]
Closed and Reopened this PR to attempt to resolve a specific Travis build failure.

**Comment by RandellDawson** [comment]
@zevski Thank you for  creating this PR.  However, since it was created, the underlying document has changed.  Can you please review and resolve the current merge conflicts?  It could be the changes to the underlying document are so significant that your changes are no longer relevant.  If the latter is the case, it might be easier to just close this PR and create a new PR with any changes you still feel are important to make.

If you need any assistance or have questions about resolving the merge conflicts, please reply back or contact someone in the [Contributors Room on Gitter](https://gitter.im/FreeCodeCamp/Contributors).

Thank you.

**Comment by zevski** [comment]
@RandellDawson, thanks for reaching out. I'm not sure I understand what the conflict is, nor how to resolve it. Is the underlying document you are referring to the English version?

**Comment by RandellDawson** [comment]
@zevski The underlying document refers to the same document you originally changed.  If you click on the button above "Resolve conflicts", you will see something which looks like the following:
````
<<<<<<< patch-5
=======

Finalmente, cabe destacar que GNU / Linux es compatible con una gran cantidad de shells o terminales como pueden ser `bash` (suele ser la utiliza por defecto), `sh`, `ksh`, `csh`, `zsh`, etc. Cada una de ellas ofrece una serie de características propias que facilitan la introducción de comandos.
Para saber que shell estamos utilizando podemos teclear el siguiente comando:

`user_name@machine_name:~$ echo $0`
>>>>>>> master
````

There is a conflict because the current version of the document has the part between the  `======` and the `>>>>>>> master` and your version did not have this.  It is just wanting you to validate if it should be empty (like yours) or if the new part is ok to leave in.  I assume we can use the part of the current master and if so, let me know and I will resolve it for you.

**Review by RandellDawson — APPROVED** [review]

**Comment by RandellDawson** [comment]
Congrats @zevski on your first pull request (PR)! 🎉

Thank you for your contribution to the page! 👍
We're happy to accept these changes, and look forward to future contributions. 📝

**Pull request merged**
