### PR TITLE
fix(client): donation-error-handler

### PR DESCRIPTION
**Pull request by Nirajn2311**
Checklist:

- [x] I have read and followed the [contribution guidelines](https://contribute.freecodecamp.org).
- [x] I have read and followed the [how to open a pull request guide](https://contribute.freecodecamp.org/#/how-to-open-a-pull-request).
- [x] My pull request targets the `main` branch of freeCodeCamp.
- [x] I have tested these changes either locally on my machine, or GitPod.

I've temporarily changed the code in the backend for it to be able to handle requests from the stripe card form to the normal stripe handler. Before merging that has to be reverted.

### CODE REVIEW

**Comment by ahmaxed** [comment]
Thanks for the pr, not sure how the token was related to testing, but I get an error if createStripeDonation fails.

**Comment by ahmaxed** [comment]
@Nirajn2311, let me know if there is anything else you wanna add. Otherwise, we can get this in as is.

**Comment by Nirajn2311** [comment]
> not sure how the token was related to testing, but I get an error if createStripeDonation fails.

I think I was hardcoding the value here, don't remember exactly what the workaround was.

Also there's nothing else remaining in this PR, it's good to go.

**Review by raisedadead — APPROVED** [review]

**Review by Sembauke — APPROVED** [review]

**Review by ojeytonwilliams — APPROVED** [review]
LGTM :+1:

**Pull request merged**
