### PR TITLE
fix(curriculum): added test to allow any order solution

### LINKED ISSUE #38769: for Euler Problem 43 - numbers must be in a certain order to pass the tests (but it is not specified)
challenge link: https://www.freecodecamp.org/learn/coding-interview-prep/project-euler/problem-43-sub-string-divisibility
file link: https://github.com/freeCodeCamp/freeCodeCamp/blob/master/curriculum/challenges/english/08-coding-interview-prep/project-euler/problem-43-sub-string-divisibility.english.md

for this challenge it asks for array `[ 1430952867, 1460357289, 1406357289, 4130952867, 4160357289, 4106357289 ]` as result to pass the tests
and in fact the following pass the tests:
```
function substringDivisibility() {
  // Good luck!
  return  [ 1430952867, 1460357289, 1406357289, 4130952867, 4160357289, 4106357289 ];
}

substringDivisibility();
```

but if I take that array and change the order of the numbers, like for example the below, the tests do not pass anymore:
```
function substringDivisibility() {
  // Good luck!
  return  [ 1406357289, 1430952867, 1460357289, 4106357289, 4130952867, 4160357289 ];
}

substringDivisibility();
```

there is not written anything about a required order.

suggestions: request the array to be sorted in some way, or sort the array in the tests before comparing it to keep using `assert.deepEqual` or change the tests to be a bit less rigid

### PR DESCRIPTION
**Pull request by ShaunSHamilton**
Checklist:
- [x] I have read [freeCodeCamp's contribution guidelines](https://contribute.freecodecamp.org).
- [x] My pull request has a descriptive title (not a vague title like `Update index.md`)
- [x] My pull request targets the `master` branch of freeCodeCamp.
- [x] All the files I changed are in the same world language, for example: only English changes, or only Chinese changes, etc.

Closes #38769 

Changed test to include all solution orders. Added test to prevent simple cheating.

### CODE REVIEW

**Review by majestic-owl448 — APPROVED** [review]

**Review by majestic-owl448 — APPROVED** [review]

**Review by majestic-owl448 — APPROVED** [review]

**Comment by Ieahleen** [comment]
Sorry, it seems I did something wrong... I am starting to learn how this works.

**Comment by Sky020** [comment]
@Ieahleen , no worries. I appreciate the extra approval 😃

**Review by moT01 — COMMENTED** [review]
Do you think someone might have those numbers (from the new test) in their code as comments @Sky020? Preventing them from passing. Probably not, I guess. You could use the [removeJSComments](https://github.com/freeCodeCamp/freeCodeCamp/blob/50f15886b85259d589df4b20b1052df7dae4a8d2/curriculum/challenges/english/02-javascript-algorithms-and-data-structures/es6/use-destructuring-assignment-to-extract-values-from-objects.english.md#after-test) thing to ensure it doesn't cause a problem.

Side note - almost all of the Euler problems can be passed by simply returning the expected result and not creating any algorithm. Wonder if we should add a quick test for many of the others that check for something similar? Maybe an issue is in order for that.

**Comment by Sky020** [comment]
@moT01, yes, the comments could be a problem, for some. I will look into adding the removeJSComments, as we do get some forum posts of users not passing because of comments.

>Maybe an issue is in order for that.

Sure, let us get that up so we can list the culprit challenges.

**Review by moT01 — APPROVED** [review]
LGTM @Sky020 🎉

I like the extra test for checking that users aren't directly returning the expected results. But I'm having second thoughts about how easy it is to get around it, and wondering if it's worth it. It's fine for this one, better than nothing. But it's pretty easy to get around, and I was thinking more about the rest of the Euler challenges that we were talking about.

**Comment by Sky020** [comment]
@moT01 , I cannot think of a decent method to test for cheating without some sort of comparison to the/a solution. That is, looking for the use of specific methods...

**Comment by ojeytonwilliams** [comment]
Given that this is intended to help with interviews, people really would be shooting themselves in the foot if they cheat.  It seems fine to use simple checks like this, but ultimately we can't stop users, say, copying other people's solutions.

**Review by ojeytonwilliams — APPROVED** [review]
LGTM :+1:

**Pull request merged**
