### PR TITLE
Add a example to Reverse Arrays waypoint

### LINKED ISSUE #5757: no reverse example
Challenge [Waypoint: Reverse Arrays with reverse](http://www.freecodecamp.com/challenges/waypoint-reverse-arrays-with-reverse) has an issue.
User Agent is: <code>Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/47.0.2526.106 Safari/537.36</code>.
Please describe how to reproduce this issue, and include links to screenshots if possible.

My code:
```javascript
var array = [1,2,3,4,5,6,7];

// Only change code below this line.

var newArray = array;

// Only change code above this line.


```
No reverse example given.

screenshot from 2016-01-02 18-25-21

### PR DESCRIPTION
**Pull request by DDaems**
close #5757

### CODE REVIEW

**Comment by SaintPeter** [comment]
You can use `<blockquote>` like this:
```
"<blockquote>var myArray = [1, 2, 3];<br>myArray.reverse();<br>// returns [3, 2, 1]</blockquote>",
```
image

Switched to numbers to make them fix on narrow screens.

**Comment by DDaems** [comment]
Changed it, i didn't like how the 
>blockqoute  

looked to be honest

**Comment by SaintPeter** [comment]
It'll do.  Honestly, these all need the same love as the Basic Javascript challenges got.

Thanks!

**Comment by toutnue12300** [comment]
2016-01-02 16:07 UTC−08:00, Dieter Daems <notifications@github.com>:

**Comment by TridevGuha** [comment]
[reversastring.txt](https://github.com/FreeCodeCamp/FreeCodeCamp/files/78016/reversastring.txt)

**Comment by TridevGuha** [comment]
[reverseastring.txt](https://github.com/FreeCodeCamp/FreeCodeCamp/files/78017/reverseastring.txt)

**Comment by toutnue12300** [comment]
Join toutnue12300 to Video Chat on ooVoo
	
	
		p { margin: 1em 0;} /*Yahoo paragraph fix*/
		.ExternalClass { width: 600px; }  /*Outlook.com, Hotmail fix*/
		.ExternalClass * { line-height: 110%; }  /*Outlook.com, Hotmail fix*/
		table td { border-collapse: collapse;}  /*This resolves the Outlook 07, 10, and Gmail td padding issue fix*/
		img {outline:none;} /* Remove the borders that appear when linking images with "border:none" and "outline:none" */
		a img {border:none;} 
		@-ms-viewport{  width: device-width;} /*outlook.com responsive bug fix */
		a:link, a:visited, a:active, a:hover { color: #eeaf00; }  /*Set default link color*/
		.appleLinks a { color: #1e1e1e; text-decoration: none; }
		.appleLinks_gray a { color: #1e1e1e; text-decoration: none; }  /*set dates, times, phone numbers, etc... to normal text color*/
		body[yahoo] .content {max-width:600px;}
		.content {max-width: 600px;}
		body[yahoo] a {text-decoration: none;}
		
		body[yahoo] .footer a {color:#fff; text-decoration:none; font-weight:bold;}
		body[yahoo] .footer a:hover {color:#fff; text-decoration:none; font-weight:bold;}
		body[yahoo] .footer a:visited {color:#fff; text-decoration:none; font-weight:bold;}
		body[yahoo] .footer a:active {color:#fff; text-decoration:none; font-weight:bold;}
		/* 
			!!! YOU MUST UN-COMMENT THE STYLE BELOW BEFORE SENDING OUT !!!  (Apple mail fix)
		*/
		@media only screen and (min-device-width: 601px) { .content { width: 600px !important;}}
	


	
		
				
				
					
						

























	
	
		
			
				
					
				
			
		
	
	














	
		
			
				
					
						Hi,
					
				
			
		
	














	
	
		
			
				
					
						
							
								
									
										
											
										
										 
										
											I’d like to video chat with you. Click below to get ooVoo and hit me back.- toutnue12300
										
									
								
							
						
					
				
			
		
	
	














	
	
		
			
				
			
			
				
					
				
				
					Download ooVoo
				
				
					
				
			
			
				
			
		
	
	









	
	
		
			
				
					
						
							
								
							
							
							
								
							
							
							
								
							
							
							
								
							
						
					
				
			
		
	
	
















	
	
		
			
				
					
						This email was sent by: ooVoo 44 East 30th Street New York, NY, 10016, USA
						
						
					


					Unsubscribe
					 | 
					Help
					 | 
					Add us to your address book

**Pull request merged**
