### PR TITLE
feat: add preview popout window

### LINKED ISSUE #46058: More Flexible Configuration of Panels in HTML/CSS Projects
### Describe the Issue

Adding the ability for users to more flexibly configure the panels in the may be beneficial. Possible options include:

* Adding a toggle for the instructions/test output (users can do this manually by sliding the width of this panel, but not all users find this adequate) 

* Adding the ability to control how the source and possibly preview panels are laid out. The ability to vertically stack the source tabs would be nice for the projects. I'm not sure if it would work as well for the challenges/steps but it would be nice for the projects.

I'm ambivalent about the first part, but the second would be a nice option.

### Affected Page

https://www.freecodecamp.org/learn/2022/responsive-web-design/build-a-survey-form-project/build-a-survey-form

### System

All

### LINKED ISSUE #46126: Improve multifile cert project preview
### Is your feature request related to a problem? Please describe.

There's been a few comments on issues and other areas about how we could improve things with the multifile editor, and specifically, the cert projects using it. One of the issues is that the preview is stuck in the preview pane. You can't resize it very well to see responsiveness, and it takes up a lot of space.

### Describe the solution you'd like

I dug around a little and found this: https://codepen.io/davidgilbertson/pen/xPVMqp. It opens a component in a new window. I propose making the preview behave this way for the new cert projects. Then users can see the responsiveness of their project and have more space for the instructions and code.

### PR DESCRIPTION
**Pull request by moT01**
Checklist:

- [x] I have read [freeCodeCamp's contribution guidelines](https://contribute.freecodecamp.org).
- [x] My pull request has a descriptive title (not a vague title like `Update index.md`)
- [x] My pull request targets the `main` branch of freeCodeCamp.
- [x] I have tested these changes either locally on my machine, or GitPod.

Closes #46126
Closes #46058

### CODE REVIEW

**Comment by moT01** [comment]
Thanks for the input @bbsmooth - I added the sr-only text, let me know if it's not correct. I can see a need for having it in the mobile layout now. I'm thinking of someone with a single small screen - and they want the fCC site on half of it and a separate window with the preview along side of it or something. These scenarios seem quite rare, but I'm sure they happen. Even on my 13" screen, the mobile view doesn't show up until the window shrinks to a good amount less than half the screen. This PR is in a pretty good state, I'm wondering if we should save that for another PR. I'm going to open it up for review and see what others think.

Another thing is that the state of the challenge UI isn't preserved between steps - that includes the preview, console, pane sizes, etc. I'm thinking we should be able to move all that to redux and we could keep the users layout when moving  from step to step. Could take it further and add to local storage so it's preserved between sessions. Another discussion/PR.

**Comment by bbsmooth** [comment]
> These scenarios seem quite rare 

Agreed, but accessibility is all about the edge cases, so that's where I'm coming from. Also, vision impairment is one of the more common disabilities, especially as we get older, so I think it may not be quite as rare as we think. I'll admit, I'm an old guy and I am constantly zooming in, so perhaps I am a little biased here.

> I'm wondering if we should save that for another PR.

Definitely. Don't let the perfect be the enemy of the good as they say.

Button sr-only text looks good. Can't wait to see this in production.

**Comment by Sembauke** [comment]
Hey @moT01,

This looks fantastic, the only thing I do not like is that the window closes on every challenge submission.
If we can improve this that would be great.

But this LGTM 👍

**Review by Sembauke — DISMISSED** [review]

**Review by ojeytonwilliams — DISMISSED** [review]
I'm afraid there's a bit of a issue - it can't run scripts. Since we're setting the html after the page is up and running, any scripts you inject will be ignored.

This isn't a problem for RWD, but the next superblock and on will (I'm 99% sure) just fail.

I think this is fixable, though.  If we create an iframe in the new window and pass that to frame.ts, we should be able to make that iframe behave like all the other previews.

**Comment by moT01** [comment]
Finally got around to fixing this up, it should be good to 🤞

**Comment by bbsmooth** [comment]
Hey @moT01 this is looking cool. One request. Can you add an appropriate title to the pop-up window. Something like "Preview | [Name of course] [Step number]".

**Comment by bbsmooth** [comment]
Another thought. I don't think I realized that the preview could only be displayed in one location (either in the iframe in the step or in a separate pop-up window). So I didn't realize that clicking the original Preview button while the pop-up window is open would close the pop-up window (and vice-versa). Really, we have a control with three different states: no preview, preview in iframe, preview in pop-up. I'm wondering if instead of using two buttons for this, we should have a single input that would toggle these three states. Could be a `select` or a three-way switch. 

Another observation. Since we don't move the keyboard focus into the iframe when the original Preview button is activated, I'm not sure we should do so when the pop-up window is activated.

**Comment by moT01** [comment]
Alright, I added a title:
Screen Shot 2022-08-10 at 4 37 18 PM

> we should have a single input that would toggle these three states...

I originally had it like that and was told to make them separate buttons, like this. We could potentially adjust the behavior. I think it's pretty good, but could possibly be better.

> Since we don't move the keyboard focus into the iframe when the original Preview button is activated, I'm not sure we should do so when the pop-up window is activated...

I didn't look into it, but I feel like that might not be possible since we're opening a new window.

**Comment by bbsmooth** [comment]
> like maybe make it so they toggle independently so you can open them both at the same time.

If we are going to leave them as separate buttons then I think this would be a good idea.

**Comment by moT01** [comment]
Yea, that might be the way to go - not sure. I do kind of like how it auto-closes the preview, as well. Let see what another person thinks, it would be nice to get this out there (aka - not have to do more work on it).

**Comment by bbsmooth** [comment]
> I originally had it like that and was told to make them separate buttons, like this.

OK, I'll stop hassling you about it since it wasn't your idea :smile:

Technically, with the way we have it working now, the two button solution may be completely accessible under WGAG, or eventually with a few minor adjustments (I'll have to do more research).

> I do kind of like how it auto-closes the preview

No disagreement there. I think it makes sense to only have one official preview window showing at a time. My concern is only how the control to do that is implemented.

**Comment by ojeytonwilliams** [comment]
@moT01 this is working beautifully, nice one. 

My one concern is that by using `srcDoc` rather than calling on `frame.ts` means we lose the functionality it adds. Most obviously, the console.  For RWD that doesn't matter much, but for the JavaScript certification, losing access to the console could be more frustrating.

**Comment by ahmadabdolsaheb** [comment]
Buttons are placed nicely and works beautifully. There is a double border between the two buttons. Other than Bruce's and Oliver's considerations, LGMT.

**Review by ojeytonwilliams — DISMISSED** [review]
Nice work, @moT01. This all looks good to me.

@bbsmooth is this okay from an a11y perspective?

**Comment by bbsmooth** [comment]
> is this okay from an a11y perspective?

There are a few concerns here. The first two should probably be addressed before we merge this. The third one is a bit more technical and may not even need to be fixed. The last one is sort of a separate issue and needs to be fixed, but perhaps not in this PR.

- We need to let screen reader users know that activating one button while the other is activated will automatically undo the the other. For example, if the preview is showing in the current window and the "show preview in separate window button" is clicked, then the preview in the current window will be removed. We need to do this with text. I'll offer one possible solution soon.
- I'm not crazy that focus is automatically moved to the new preview window, since we don't do that for the original preview button. But at the same time, I understand why we want the new window to open on top of the current window and thus it makes sense to move focus into the new window. If this were an ordinary link to a different web page then this would be the expected behavior. But I'm not sure it is expected when using a button. I think perhaps the solution here is to make it clear to screen reader users that their focus will be moved to the new window. This needs to be done in text as well and I'll combine it with my suggested solution to the previous issue.
- I'm not sure whether `aria-expanded` or `aria-pressed` is the best attribute to use for these buttons. These buttons definitely control the display of content, so `aria-expanded` seems appropriate. But the buttons are acting together as a three-state toggle control, which would make `aria-pressed` more appropriate. Ultimately, we can probably use either one and be OK. But I'm going to do a little more research to see if one is "more correct". I wouldn't let my indecisiveness stop this PR. I can always submit a new PR just for this issue if I can make a convincing case for `aria-pressed`.
- On a sort of unrelated note, I'm noticing that both the original preview button and the new "show preview in separate window" button are being skipped by NVDA when navigating by arrow keys. That seems weird. I'll see if I can figure out what is causing it, but let's don't let it stop this PR.

**Comment by moT01** [comment]
Thanks for the feedback @bbsmooth. Not sure exactly what you had in mind - I tried to add some things to help that will hopefully take care of the first two concerns you brought up. Mind taking a look?

I tested the aria-pressed, it took some of the style away from the buttons. Probably not a difficult fix, but I just put it back for now.

> ...skipped by NVDA

Kind of strange. I didn't test NVDA, I need to download it. So you can still tab to the buttons, but it doesn't read anything for them or what? If this is the current behavior for the preview button on production, I would say to leave it. If this PR is the cause, then maybe we should look into it.

**Comment by bbsmooth** [comment]
@moT01 
> So you can still tab to the buttons, but it doesn't read anything for them or what?

Yes, you can still tab to them and you can use the `b` shortcut to get to them, but you can't use the up/down arrow keys to get to them for some reason using NVDA. This is not a problem in JAWS, so it appears to be a strange behavior with NVDA only. I wouldn't let this hold up the PR. I will look into it more and see if there is something we can do to fix this NVDA behavior (I've already tried a few things but no luck yet). Or who knows, I may end up opening a bug report on this.

As for the various button states and sr-only text, I think this is great. I would recommend we tighten up the text a little. Most screen reader users are used to very terse text and adding filler words just creates unnecessary noise. Also, I think we need to be a little more consistent in the wording we use for the sr-only text for the sake of people who may be using voice control software, since the sr-only text is going to be the accessible name for these buttons. I need a little more time to work up some good suggestions.

**Comment by moT01** [comment]
Sounds good @bbsmooth - take your time. Here's an attempt at simplifying what I added a little further in case we want to use any of it:

| 3 states | Main Preview Button - SR Text | New Window Button - SR text |
|---------|----------------------|----------------------|
|Main preview open|Hide preview|Move preview and focus to new window|
|External window open|Move preview to this window|Close external preview window|
|None open|Show preview in this window|Open and focus preview in new window|

**Comment by bbsmooth** [comment]
> We could go with it as-is

Yes, go with it as is. I can open a new PR later if I have any improvement.

I apologize for the delay. I have been unavailable for the past week and a half and likely will last into early next week.

**Review by bbsmooth — APPROVED** [review]

**Comment by moT01** [comment]
No worries @bbsmooth - I know how things can come up. Thanks again for the feedback and help on this 👍

**Review by Sboonny — APPROVED** [review]
LGTM 🎉, thank you for your contribution to the page! 👍.

----

Just wondering, is it possible to make preview window persistence after submit the code and moving to the next step.

And would that affect accessibility?

**Pull request merged**
