### PR TITLE
Remove multiple redundant new lines

### PR DESCRIPTION
**Pull request by frdmn**
#### Pre-Submission Checklist

- [X] Your pull request targets the `staging` branch of freeCodeCamp.
- [X] Branch starts with either `fix/`, `feature/`, or `translate/` (e.g. `fix/signin-issue`)
- [X] You have only one commit (if not, [squash](http://forum.freecodecamp.com/t/how-to-squash-multiple-commits-into-one-with-git/13231) them into one commit).
- [X] All new and existing tests pass the command `npm test`. Use `git commit --amend` to amend any fixes.

#### Type of Change

- [X] Small bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds new functionality)
- [ ] Breaking change (fix or feature that would change existing functionality)
- [ ] Add new translation (feature adding new translations)

#### Checklist:

- [X] Tested changes locally.
- [ ] Closes currently open issue (replace XXXX with an issue no): Closes #XXXX

#### Description

I noticed the three redundant empty lines between the function and the call of it so I removed 2 of them.

### CODE REVIEW

**Comment by texas2010** [comment]
which issue number?  did they asked you removed it?

**Comment by frdmn** [comment]
There is no existing issue for this. I just noticed the inconsistency.

Von meinem iPhone gesendet

**Review by erictleung — APPROVED** [review]
LGTM! 👍  I'm all for consistency 😄  Thanks for contributing! 🎉

**Comment by QuincyLarson** [comment]
@frdmn Thanks for your contribution!

**Comment by frdmn** [comment]
Very welcome! I'll try to get through the previous (and following) exercises as well to keep up the consistency when I have some more free time.

**Pull request merged**
