### PR TITLE
update blockNameify preformattedBlocks for beta

### LINKED ISSUE #12643: [beta] "CSS" spelled "Css" - Change the color of text (Basic CSS)
#### Challenge Name

[Basic Css: Change the Color of Text](http://beta.freecodecamp.com/en/challenges/basic-css/change-the-color-of-text)

#### Issue Description

The title of the challenge spells "Css" which i think is wrong. Should probably be changed to "CSS".
 
#### Screenshot

basic css name

### LINKED ISSUE #12657: [beta] "HTML" spelled "Html" - Basic HTML Challenges
### Challenge Name

Most, if not all, of the basic HTML challenges.

#### Issue Description
The challenge title displayed in the top left corner as well as the page title in the browser are using "Html" instead of "HTML".

I think all occurances of "Html" should be changed to "HTML" for consistency. Since HTML is an abbreviation, it feels natural to use all caps.

This is similar to #12643 

#### Browser Information

* Browser Name, Version: N/A
* Operating System: N/A
* Mobile, Desktop, or Tablet: N/A

### PR DESCRIPTION
**Pull request by dhcodes**
#### Pre-Submission Checklist

- [X] Your pull request targets the `staging` branch of freeCodeCamp.
- [X] Branch starts with either `fix/`, `feature/`, or `translate/` (e.g. `fix/signin-issue`)
- [X] You have only one commit (if not, [squash](http://forum.freecodecamp.com/t/how-to-squash-multiple-commits-into-one-with-git/13231) them into one commit).
- [X] All new and existing tests pass the command `npm test`. Use `git commit --amend` to amend any fixes.

#### Type of Change

- [X] Small bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds new functionality)
- [ ] Breaking change (fix or feature that would change existing functionality)
- [ ] Add new translation (feature adding new translations)

#### Checklist:

- [X] Tested changes locally.
- [X] Closes currently open issue (replace XXXX with an issue no): 

Closes #12643 
Closes #12657

#### Description

I noticed with the new challenges that the titles weren't always correct. For example, `Basic CSS` was showing as `Basic Css`. I've updated the blockNameify file to correct all of these and I also alphabetized them.

### CODE REVIEW

**Comment by Greenheart** [comment]
@dhcodes Thanks for doing this. This will hopefully solve #12643 and #12657

**Comment by dhcodes** [comment]
np. Should fix all the case issues. 👍

**Review by raisedadead — APPROVED** [review]
LGTM

**Comment by raisedadead** [comment]
#### :sparkles: :sparkles: **LGTM.** :sparkles: :sparkles: 

Thanks @dhcodes ! Awesomeness.

**Pull request merged**
