### PR TITLE
fix: improve test regex to validate disallowed methods that can be bypassed by prototype reassignments and/or otherwise

### LINKED ISSUE #38204: Some challenges' restrictions can be bypassed by re-assigning methods to different names
Hey all, so after spending a few minutes trying to solve the [Steamroller challenge](https://www.freecodecamp.org/learn/javascript-algorithms-and-data-structures/intermediate-algorithm-scripting/steamroller) from the Intermediate Algorithm Scripting section, I decided to try and reassign the `Array.prototype.flat` to a new method I named `Array.prototype.flatten` for the fun of it but surprisingly enough the challenge passed. So I think that this means all challenges which restrict the use of a certain method to pass can be bypassed with this same trick.

P.S: I'm gonna retry the challenge again legitimately.

### PR DESCRIPTION
**Pull request by hassaanp**
I went through the entire library of challenges and tested each to confirm if the disallowed methods could be bypassed by adding newlines/whitespaces or prototype reassignments.

I was able to fix the regex patterns to prevent those bypass scenarios. I have tested this on my local setup but it would be great if someone else can give it a spin as well.

- [x] I have read [freeCodeCamp's contribution guidelines](https://github.com/freeCodeCamp/freeCodeCamp/blob/master/CONTRIBUTING.md).
- [x] My pull request has a descriptive title (not a vague title like `Update index.md`)
- [x] My pull request targets the `master` branch of freeCodeCamp.
- [x] None of my changes are plagiarized from another source without proper attribution.
- [x] All the files I changed are in the same world language (for example: only English changes, or only Chinese changes, etc.)
- [x] My changes do not use shortened URLs or affiliate links.

Closes #38204

### CODE REVIEW

**Review by moT01 — APPROVED** [review]
I really don't think any of this is necessary, as I pointed out on the issue. But I suppose it's not hurting anything and the work was already put in. So unless anyone objects, I'm fine with adding this. LGTM 🎉

**Review by RandellDawson — APPROVED** [review]

**Comment by RandellDawson** [comment]
Thank you for your contribution to the page! 👍
We're happy to accept these changes, and look forward to future contributions. 🎉

**Comment by lasjorg** [comment]
@RandellDawson I think this regex change made it so you can't have an array named `flat`.

Forum post: https://www.freecodecamp.org/forum/t/steamroller-array-prototype-flat-error/368613

**Comment by RandellDawson** [comment]
@lasjorg Yes you are correct.  PR https://github.com/freeCodeCamp/freeCodeCamp/pull/38497 should fix it.

**Pull request merged**
