### PR TITLE
feat(client): place tool panel at the bottom

### PR DESCRIPTION
**Pull request by ValeraS**
- [x] I have read [freeCodeCamp's contribution guidelines](https://github.com/freeCodeCamp/freeCodeCamp/blob/master/CONTRIBUTING.md).
- [x] My pull request has a descriptive title (not a vague title like `Update index.md`)
- [x] My pull request targets the `master` branch of freeCodeCamp.
- [x] None of my changes are plagiarized from another source without proper attribution.

image

### CODE REVIEW

**Comment by raisedadead** [comment]
Hi @ValeraS 

We would want the order of the buttons preserved

image


That is the first one in the image above should be left to right. Literally the opposite of what you have

**Comment by raisedadead** [comment]
I think this might be pre-existing before your PR. But can you take a look?

**Comment by ValeraS** [comment]
@raisedadead It is done like in a mobile view.

**Comment by raisedadead** [comment]
Yep, and we would want the first button on the left to be the "Run tests", "Reset",  "Hint"... in that order in both mobile and desktop layouts.

**Comment by ValeraS** [comment]
> Moving the more important buttons to the right hand side is a really insightful UX improvement :)

https://github.com/freeCodeCamp/freeCodeCamp/pull/34602#issuecomment-445445592

**Comment by raisedadead** [comment]
Oh thanks. I guess I missed it from before.

**Review by raisedadead — APPROVED** [review]

**Pull request merged**
