### PR TITLE
fix(curriculum): wait for the last challenge to be populated

### LINKED ISSUE #35594: Missing Project Euler Challenges
**Describe the bug**
There are 30 missing challenges in the Project Euler section both locally and on freecodecamp.rocks:

`[8, 9, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84, 85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98, 99]`

I've tried running `npm run clean`, `npm install`, and reseeding the database, but the pages for the above challenges aren't built during `npm run develop`. The challenges aren't shown on the challenge map, and going directly to the URL (http://localhost:8000/learn/coding-interview-prep/project-euler/problem-8-largest-product-in-a-series) shows a 404 page.

One thing I noticed is that hot reloading a challenge causes the page to be built. Even without making any changes in the editor, if I save Problem 8, the challenge will be shown on the on the challenge map and you can navigate to the page. However, if I restart the server, the challenges will be missing until they're hot reloaded again.

The challenge IDs all seems to be unique, and match the ones listed in the Project Euler `meta.json` file.

Do you know what might be going on here @Bouncey, @raisedadead, and @ValeraS?

### PR DESCRIPTION
**Pull request by ValeraS**
- [x] I have read [freeCodeCamp's contribution guidelines](https://github.com/freeCodeCamp/freeCodeCamp/blob/master/CONTRIBUTING.md).
- [x] My pull request has a descriptive title (not a vague title like `Update index.md`)
- [x] My pull request targets the `master` branch of freeCodeCamp.
- [x] None of my changes are plagiarized from another source without proper attribution.

Closes #35594

### CODE REVIEW

**Comment by scissorsneedfoodtoo** [comment]
@ValeraS, awesome! Everything LGTM. Thank you for such a quick fix. Just waiting for another review before merging.

**Comment by ojeytonwilliams** [comment]
For what it's worth, you can simplify the logic by starting with `running = 1` and then call

```
function done() {
   if (--running === 0) resolve(curriculum);
};
```

after both `data` and `end` events.  Regardless, it's already a lot more elegant than the mess of callbacks I came up with!

**Review by raisedadead — APPROVED** [review]
LGTM. Thanks @ValeraS. @ojeytonwilliams please merge if you are happy with the updates.

**Comment by ojeytonwilliams** [comment]
Thanks! @ValeraS @raisedadead Everything looks good to me.

**Pull request merged**
