### PR TITLE
Added link for Part Two of article

### PR DESCRIPTION
**Pull request by dohmain**
- [x ] I have read [freeCodeCamp's contribution guidelines](https://github.com/freeCodeCamp/freeCodeCamp/blob/master/CONTRIBUTING.md).
- [x ] My pull request has a descriptive title (not a vague title like `Update index.md`)
- [x ] My pull request targets the `master` branch of freeCodeCamp.
- [x ] None of my changes are plagiarized from another source without proper attribution.
- [x ] My article does not contain shortened URLs or affiliate links.

If your pull request closes a GitHub issue, replace the XXXXX below with the issue number.

Closes #XXXXX

### CODE REVIEW

**Comment by honmanyau** [comment]
@dohmain Thank you very much for submitting a pull request (PR). I have resolved a merge conflict and done some basic editing to make the article's style consistent with the rest of the guide articles.

I think the changes are minored but I have unassigned myself so that another reviewer can check my changes.

**Comment by moT01** [comment]
Why did we remove the github link?

**Comment by honmanyau** [comment]
@moT01 I should have noted that again in my comment instead of just the commit message—that link goes to GitHub's pricing page and isn't something that specifically explains what code review is, that's why I decided to edit it out.

**Comment by moT01** [comment]
Thanks for contributing to freeCodeCamp @dohmain!

**Pull request merged**
