### PR TITLE
Added the missing semi-colon for valid JS in the basic-javascript.json

### LINKED ISSUE #9768: Missing semi-colon for valid JS
Challenge [Accessing Nested Objects](https://www.freecodecamp.com/challenges/accessing-nested-objects) has an issue.
User Agent is: <code>Mozilla/5.0 (Macintosh; Intel Mac OS X 10_10_5) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/51.0.2704.103 Safari/537.36</code>.
Please describe how to reproduce this issue, and include links to screenshots if possible.

## Description

The sample code is missing a semi-colon.

## How to Fix

[This line of code](https://github.com/FreeCodeCamp/FreeCodeCamp/blob/75bba05718dc0bb288beafb154ecc4b0181e8d64/seed/challenges/01-front-end-development-certification/basic-javascript.json#L4397) needs to be edited so that there is a semi-colon in the correct place. The edits you make in your code should be from the red to the green:

```diff
- "<blockquote>var ourStorage = {<br>  \"desk\": {<br>    \"drawer\": \"stapler\"<br>  },<br>  \"cabinet\": {<br>    \"top drawer\": { <br>      \"folder1\": \"a file\",<br>      \"folder2\": \"secrets\"<br>    },<br>    \"bottom drawer\": \"soda\"<br>  }<br>}<br>ourStorage.cabinet[\"top drawer\"].folder2;  // \"secrets\"<br>ourStorage.desk.drawer; // \"stapler\"</blockquote>",
+ "<blockquote>var ourStorage = {<br>  \"desk\": {<br>    \"drawer\": \"stapler\"<br>  },<br>  \"cabinet\": {<br>    \"top drawer\": { <br>      \"folder1\": \"a file\",<br>      \"folder2\": \"secrets\"<br>    },<br>    \"bottom drawer\": \"soda\"<br>  }<br>};<br>ourStorage.cabinet[\"top drawer\"].folder2;  // \"secrets\"<br>ourStorage.desk.drawer; // \"stapler\"</blockquote>",
```

## To Contributors

Please first read the [contributing guidelines](https://github.com/FreeCodeCamp/FreeCodeCamp/blob/staging/CONTRIBUTING.md) before taking care of this issue. And feel free to visit the [Contributors Help](https://gitter.im/FreeCodeCamp/HelpContributors) chat room if you have any questions about helping. We're there to help.

This issue is labeled as `first-timers-only` so only individuals who have not contributed to the main repository for Free Code Camp can resolve this issue. Thank you for understanding.

## Screenshot

image

### PR DESCRIPTION
**Pull request by aashil**
#### Pre-Submission Checklist

- [x] Your pull request targets the `staging` branch of FreeCodeCamp.
- [x] Branch starts with either `fix/`, `feature/`, or `translate/` (e.g. `fix/signin-issue`)
- [x] You have only one commit (if not, [squash](https://github.com/FreeCodeCamp/FreeCodeCamp/wiki/Git-Squash) them into one commit).
- [x] All new and existing tests pass the command `npm run test-challenges`. Use `git commit --amend` to amend any fixes.
#### Type of Change

- [x] Small bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds new functionality)
- [ ] Breaking change (fix or feature that would change existing functionality)
- [ ] Add new translation (feature adding new translations)
#### Checklist:

- [x] Tested changes locally.
- [x] Closes currently open issue (replace XXXX with an issue no): Closes #9768 
#### Description

…n file

### CODE REVIEW

**Comment by alayek** [comment]
# LGTM :+1:  :full_moon_with_face: 

Let's :shipit: :package:

---

On a separate note, why is the semicolon important? Is it for style-guide related something?

**Comment by erictleung** [comment]
@alayek it's for consistency and for the sake of best practice 😃 

@aashil LGTM! 👍  Thanks for your contribution to FreeCodeCamp! ✨ 🎉 ✨

**Comment by aashil** [comment]
@alayek Thanks, just wanted to know the reason for editing out the "closes #9768" part in the title. 
@erictleung You are welcome. My first open source contribution.

**Comment by alayek** [comment]
@aashil as @camperbot has [mentioned](#issuecomment-233213383) already, you should leave out issue name from PR's titles, and instead provide them as part of PR's comments. Hope that clears it up.

And congrats!! Do keep it up :100:

**Pull request merged**
