### PR TITLE
feat(curriculum): add animations to block 6.2 of the English Curriculum

### PR DESCRIPTION
**Pull request by miyaliu666**
Checklist:

- [x] I have read and followed the [contribution guidelines](https://contribute.freecodecamp.org).
- [x] I have read and followed the [how to open a pull request guide](https://contribute.freecodecamp.org/#/how-to-open-a-pull-request).
- [x] My pull request targets the `main` branch of freeCodeCamp.
- [x] I have tested these changes either locally on my machine, or GitPod.

### CODE REVIEW

**Review by nieldakarla — CHANGES_REQUESTED** [review]
This looks great @miyaliu666! Here are some minor comments that Daniel said will fix on his next commit:

Need fix audio: 9, 10, 11, 12, 14, 15, 24, 25, 26, 27, 28, 47, 48 and 49

Task 51: Need to remove the audio box. 

Also, for tasks where we don't teach anything on the description I'd like to suggest we just say "Listen to the audio and answer the question" or "listen to the audio and complete the sentence", instead of long paragraphs that aren't actually explaining any concept. ChatGPT generate those and I think they impact negatively the user experience. 

For example, this is the current description on task 38: Sophie's line encapsulates a polite request for assistance, her ongoing challenge, and her belief that another perspective could be beneficial. Understanding such professional communication is essential in collaborative environments.

This text is complex and it isn't actually teaching anything. I vote for replacing it by one of the options I mentioned earlier.

**Comment by DanielRosa74** [comment]
> This looks great @miyaliu666! Here are some minor comments that Daniel said will fix on his next commit:
> 
> Need fix audio: 9, 10, 11, 12, 14, 15, 24, 25, 26, 27, 28, 47, 48 and 49
> 
> Task 51: Need to remove the audio box.
> 
> Also, for tasks where we don't teach anything on the description I'd like to suggest we just say "Listen to the audio and answer the question" or "listen to the audio and complete the sentence", instead of long paragraphs that aren't actually explaining any concept. ChatGPT generate those and I think they impact negatively the user experience.
> 
> For example, this is the current description on task 38: Sophie's line encapsulates a polite request for assistance, her ongoing challenge, and her belief that another perspective could be beneficial. Understanding such professional communication is essential in collaborative environments.
> 
> This text is complex and it isn't actually teaching anything. I vote for replacing it by one of the options I mentioned earlier.

I'm working on these changes, too, @miyaliu666. No need to address them until I send it. ;)

**Comment by miyaliu666** [comment]
Thank @nieldakarla for listing the tasks for which we should fix the audio. I took notes when I tested them locally, and planned to send them together when I finish block 6.3. @DanielRosa74 could refer to our comments for details:)

- Task-11, task-12 and task-14: incomplete "Absolutely"
- Task-23, task-24, task-25 and task-32: "Could we provide more details about the problem" should be "Could you provide more details about the problem"?
- Task-26: incomplete "Great"
- Task-27, task-28 : incomplete "Excellent"

6-2-2

- Task-40 and task-41: incomplete "Just"

6-2-3

- Task-47: incomplete "agenda"
- Task-48: incomplete "practices"
- Task-51: incomplete "I"
- Task-58: incomplete "Great"

> Also, for tasks where we don't teach anything on the description I'd like to suggest we just say "Listen to the audio and answer the question" or "listen to the audio and complete the sentence", instead of long paragraphs that aren't actually explaining any concept. ChatGPT generate those and I think they impact negatively the user experience.

I was hesitant to change them that way when I submitted the PR for the tasks. I thought that the curriculum was midway through, and we could provide learners opportunity to practice understanding these longer paragraphs, so I kept some of them. However, now I agree it's a good idea to change them.

**Comment by DanielRosa74** [comment]
> Thank @nieldakarla for listing the tasks for which we should fix the audio. I took notes when I tested them locally, and planned to send them together when I finish block 6.3. @DanielRosa74 could refer to our comments for details:)
> 
> * Task-11, task-12 and task-14: incomplete "Absolutely"
> * Task-23, task-24, task-25 and task-32: "Could we provide more details about the problem" should be "Could you provide more details about the problem"?
> * Task-26: incomplete "Great"
> * Task-27, task-28 : incomplete "Excellent"
> 
> 6-2-2
> 
> * Task-40 and task-41: incomplete "Just"
> 
> 6-2-3
> 
> * Task-47: incomplete "agenda"
> * Task-48: incomplete "practices"
> * Task-51: incomplete "I"
> * Task-58: incomplete "Great"
> 
> > Also, for tasks where we don't teach anything on the description I'd like to suggest we just say "Listen to the audio and answer the question" or "listen to the audio and complete the sentence", instead of long paragraphs that aren't actually explaining any concept. ChatGPT generate those and I think they impact negatively the user experience.
> 
> I was hesitant to change them that way when I submitted the PR for the tasks. I thought that the curriculum was midway through, and we could provide learners opportunity to practice understanding these longer paragraphs, so I kept some of them. However, now I agree it's a good idea to change them.

Changes sent to fix both @nieldakarla's and @miyaliu666's issues.

**Review by DanielRosa74 — APPROVED** [review]
LGTM

**Review by nieldakarla — APPROVED** [review]
LGTM

**Review by naomi-lgbt — APPROVED** [review]
Dev team approval to unblock.

**Pull request merged**
