### PR TITLE
optimization on error handling for failed updates

### PR DESCRIPTION
**Pull request by mathantkumar**
Checklist:

- [x ] I have read and followed the [contribution guidelines](https://contribute.freecodecamp.org).
- [ x] I have read and followed the [how to open a pull request guide](https://contribute.freecodecamp.org/#/how-to-open-a-pull-request).
- [x ] My pull request targets the `main` branch of freeCodeCamp.
- [x ] I have tested these changes either locally on my machine, or GitPod.

Reduced Network Load: Batching updates using concatMap can significantly reduce the number of HTTP requests made to the server, potentially decreasing network latency and server load.

Improved Efficiency: By eliminating unnecessary delays and optimizing asynchronous operations, the code can execute more efficiently, leading to faster processing of updates and reduced CPU usage.

Enhanced Maintainability: The refactoring and modularization of code improve readability and maintainability, potentially reducing the time required for future development and debugging tasks.

### CODE REVIEW

**Comment by gikf** [comment]
Hey,

could you add a bit of context for this PR? Namely:
- Is this PR related to any existing issue?
- Specifically which code changes refer to which improvement described in the PR description?

Thank you and happy coding.

**Comment by mathantkumar** [comment]
No it doesn't solve existing issue, I have implemented batching of updates using **concatMap** in the **failedUpdateEpic** function, so this change consolidates multiple updates into single requests, reducing network traffic and server load. Refactored update processing logic into the **processUpdate** function. Improved error handling and asynchronous processing contribute to enhanced server efficiency and  I have extracted reusable functions (saveUpdateToStore, isSubmitable, processUpdate) to enhance code modularity and readability.

**Comment by ojeytonwilliams** [comment]
Hi @mathantkumar, the idea by behind this epic is that it should gradually submit the failed challenges. If I'm reading this right, your changes will, instead, send the same number of requests, but as quickly as possible. Is that correct?

**Comment by mathantkumar** [comment]
Yes, you are correct changes made to the **failedUpdateEpic** function focus on optimizing the processing of failed updates by batching them for submission. However the implementation as it stands does not introduce a gradual submission mechanism. Instead it processes all submitable failures as quickly as possible, potentially sending multiple requests simultaneously, but still with lil amendments to batching yes we have add delay,  for gradual submission. confirm me I'll amend the change.

**Comment by ojeytonwilliams** [comment]
Yes, please. A refactor is very welcome, but we do want to keep the original behaviour.

**Comment by mathantkumar** [comment]
Can I get review on this please?

**Review by naomi-lgbt — COMMENTED** [review]
There's a LOT of comments added in this PR that don't need to be added.

If a comment is explaining what the code does, it's probably extraneous.

```js
 payload.id = uuid(); // Assign a unique ID to the payload
```

**Review by ojeytonwilliams — CHANGES_REQUESTED** [review]
I agree with Naomi about the comments. Also, as far as we know, this epic is working as intended, so the functionality should not be changed.

A lighter refactor would be great, but we can't accept the PR as is.

**Comment by mathantkumar** [comment]
Alright thanks for the suggestions, closing this PR, to be more worked on open issues.

**Comment by ojeytonwilliams** [comment]
Okay, no worries. Thanks for taking the time to help out.

If you're looking for places to contribute our [contribution docs](https://contribute.freecodecamp.org/intro/) are a great place to start.

**Pull request closed without merging**
