### PR TITLE
fix(client): remove external prop on 'donate' link

### LINKED ISSUE #41016: Clicking the 'donate' link in the navbar menu does not redirect to the spanish version of the page
**Describe the bug**
If you are in the spanish version of freeCodeCamp, clicking the 'donar' (donate) link in the navbar menu redirects you to the english version of the donate page and not the spanish translated one.

**To Reproduce**
1. Go to https://www.freecodecamp.dev/espanol/
2. Click on 'Menú'
3. Click on 'Donar'
4. See how it opens https://www.freecodecamp.dev/donate/ (english version of the donate page)

**Expected behavior**
It should open: https://www.freecodecamp.dev/espanol/donate/ (spanish version of the donate page)

**Desktop (please complete the following information):**
- OS: [Windows 10]
- Browser: [chrome]
- Version: [88]

### PR DESCRIPTION
**Pull request by kelvinsanchez15**
Checklist:

- [x] I have read [freeCodeCamp's contribution guidelines](https://contribute.freecodecamp.org).
- [x] My pull request has a descriptive title (not a vague title like `Update index.md`)
- [x] My pull request targets the `main` branch of freeCodeCamp.
- [x] All the files I changed are in the same world language, for example: only English changes, or only Chinese changes, etc.

Closes #41016

### CODE REVIEW

**Comment by nhcarrigan** [comment]
Testing locally, I can confirm this resolves the issue of `/espanol` being removed from the donation redirect.

@kelvinsanchez15 I'll generate a suggestion to resolve the linting error momentarily.

**Review by naomi-lgbt — CHANGES_REQUESTED** [review]
Suggestion tool is not cooperating.

Replace:
```js
          <Link
            className='nav-link'
            key='donate'
            sameTab={false}
            to='/donate'
          >
            {t('buttons.donate')}
          </Link>
```

With:
```js
          <Link className='nav-link' key='donate' sameTab={false} to='/donate'>
            {t('buttons.donate')}
          </Link>
```

**Comment by kelvinsanchez15** [comment]
Thanks @nhcarrigan as soon as I have some time I will configure a proper fCC local instance.

**Review by naomi-lgbt — APPROVED** [review]
Looks good to me.

**Pull request merged**
