### PR TITLE
Add note on adding commas between JSON objects

### LINKED ISSUE #5837: missing comma?
Challenge [Waypoint: Introducing JavaScript Object Notation JSON](http://www.freecodecamp.com/challenges/waypoint-introducing-javascript-object-notation-json#?solution=var%20myMusic%20%3D%20%5B%0A%20%20%7B%0A%20%20%20%20%22artist%22%3A%20%22Billy%20Joel%22%2C%0A%20%20%20%20%22title%22%3A%20%22Piano%20Man%22%2C%0A%20%20%20%20%22release_year%22%3A%201993%2C%0A%20%20%20%20%22formats%22%3A%20%5B%20%0A%20%20%20%20%20%20%22CS%22%2C%20%0A%20%20%20%20%20%20%228T%22%2C%20%0A%20%20%20%20%20%20%22LP%22%20%5D%2C%0A%20%20%20%20%22gold%22%3A%20true%0A%20%20%7D%2C%0A%20%20%2F%2F%20Add%20record%20here%0A%20%20%7B%0A%20%20%20%20%22artist%22%3A%20%22Tsuyoshi%20Hiroshi%22%2C%0A%20%20%20%20%22title%22%3A%20%22Tonboyou%22%2C%0A%20%20%20%20%22release_year%22%3A%201987%2C%0A%20%20%20%20%22formats%22%3A%20%5B%0A%20%20%20%20%20%20%22CD%22%2C%0A%20%20%20%20%20%20%22DVD%22%2C%0A%20%20%20%20%20%20%22LP%22%5D%0A%20%20%7D%0A%5D%3B%0A%0A) has an issue.
User Agent is: <code>Mozilla/5.0 (Macintosh; Intel Mac OS X 10_11_2) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/47.0.2526.106 Safari/537.36</code>.
Please describe how to reproduce this issue, and include links to screenshots if possible.

My code:
```javascript
var myMusic = [
  {
    "artist": "Billy Joel",
    "title": "Piano Man",
    "release_year": 1993,
    "formats": [ 
      "CS", 
      "8T", 
      "LP" ], 
    "gold": true
  }, <---------------------perhaps is a missing a comma, here?
  // Add record here
  {
    "artist": "Tsuyoshi Hiroshi",
    "title": "Tonboyou",
    "release_year": 1987,
    "formats": [
      "CD",
      "DVD",
      "LP"]
  }
];


```

### PR DESCRIPTION
**Pull request by erictleung**
Closes #5837.

### CODE REVIEW

**Comment by SaintPeter** [comment]
Please remove the colon after `Note`.  None of the other notes have them.  Otherwise this looks good.

**Comment by bugron** [comment]
@erictleung thanks, merged.

**Comment by sgalizia** [comment]
This issue has not been resolved on the site yet, have they added the comma between the declarations yet? Or fixed it? Cause I just noticed the issue still active on the site.

**Comment by sludge256** [comment]
It's still on staging. It will be on the site once the new master goes live.

**Pull request merged**
