### PR TITLE
fix(seed): flex box challenges not displaying

### LINKED ISSUE #16878: Beta/Responsive Web Design/CSS Flexboxes Not displaying
#### Challenge Name

https://beta.freecodecamp.org/en/challenges/css-flexbox/use-display-flex-to-position-two-boxes
https://beta.freecodecamp.org/en/challenges/css-flexbox/use-the-flexdirection-property-to-make-a-row
https://beta.freecodecamp.org/en/challenges/css-flexbox/use-the-flexdirection-property-to-make-a-column

#### Issue Description

The blue and orange flexboxes don't display because they contain no content, and thus have no height enforced on them.

**Kludgy solution:** Even adding a single character between the div tags fixes the problem. I used "a" and "b" for #box-1 and #box-2 respectively. Whitespace does not fix the problem.

Example kludgy hack code in the above links:
```
<div id="box-container">
  <div id="box-1">a</div>
  <div id="box-2">b</div>
</div>
```

**Elegant solution:**  Actually, I stole it from another "theory challenge" in the in CSS-flexbox unit - (https://beta.freecodecamp.org/en/challenges/css-flexbox/align-elements-using-the-justifycontent-property)

In all the problematic challenges, I was able to modify the CSS for the div "#box-container" to add a height, and it fixed the problem. 
` #box-container {
    height: 25%;
  }`

#### Browser Information

* Browser Name, Version: Firefox 58.0.2
* Operating System: Windows 8.1 64-bit
* Mobile, Desktop, or Tablet: Desktop

#### Your Code

```js
#box-container {
    height: 25%;
  }
```

### PR DESCRIPTION
**Pull request by PolarisTLX**
#### Pre-Submission Checklist

- [X] Your pull request targets the `staging` branch of freeCodeCamp.
- [X] Branch starts with either `fix/`, `feature/`, or `translate/` (e.g. `fix/signin-issue`)
- [X] You have only one commit (if not, [squash](http://forum.freecodecamp.org/t/how-to-squash-multiple-commits-into-one-with-git/13231) them into one commit).
- [X] All new and existing tests pass the command `npm test`. Use `git commit --amend` to amend any fixes.

#### Type of Change

- [X] Small bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds new functionality)
- [ ] Breaking change (fix or feature that would change existing functionality)
- [ ] Add new translation (feature adding new translations)

#### Checklist:

- [X] Tested changes locally.
- [X] Addressed currently open issue (replace XXXXX with an issue no in next line)

Closes #16878

#### Description
Beta/Responsive Web Design/CSS Flexboxes Not displaying in Firefox browser

Fixed by adding a "height: 500px;" to all instances of "#box-container { "

By Paul  (@PolarisTLX) and Kyle (@jklemon17)

### CODE REVIEW

**Comment by raisedadead** [comment]
Nice work @PolarisTLX .

A few nitpicks before we can QA (sorry, we understand this is your first time here, and hence all the more important)

1. Could you rebase your branch against latest staging to resolve the snyk check.
2. update the commit message to be a little meaningful.

Here are some steps:

```
git checkout fix/flexbox-display-firefox 
git pull --rebase upstream staging
git commit --amend -m "fix(seed): flex box challenges not displaying"
git push --force
```
3. You have used the issue no.s in the description one too many times. A single entry with the `Closes` keyword is should suffice.

Hit us in [Contributors Chat room](https://gitter.im/FreeCodeCamp/Contributors) fir any assistance.

**Comment by raisedadead** [comment]
Awesome! Thanks @PolarisTLX we will get back to you after QA.

**Comment by mstellaluna** [comment]
I am working on this now

**Comment by mstellaluna** [comment]
@PolarisTLX I tested your changes in firefox and in chrome. Looks great to me :) I will go ahead an approve the changes. Great Job. Thank you for contributing. Happy Coding !

**Review by mstellaluna — APPROVED** [review]
Issue corrected in FF, and re-tested in chrome. Looks great to me.

**Comment by raisedadead** [comment]
Thanks for the QA @mstellaluna !

**Pull request merged**
