### PR TITLE
Add secure attribute to cookie

### PR DESCRIPTION
**Pull request by hodovani**
Checklist:

- [X] I have read [freeCodeCamp's contribution guidelines](https://contribute.freecodecamp.org).
- [X] My pull request has a descriptive title (not a vague title like `Update index.md`)
- [X] My pull request targets the `master` branch of freeCodeCamp.
- [X] All the files I changed are in the same world language, for example: only English changes, or only Chinese changes, etc.

Cookie [:11] misses the Secure attribute (it is false by default). Set it to true to protect the cookie from man-in-the-middle attacks.

### CODE REVIEW

**Comment by ojeytonwilliams** [comment]
Hi @hodovani, thanks for the PR.  This seems like a good change, but I'll defer to @raisedadead in case there are any problems that might arise due how we proxy things.

**Comment by hodovani** [comment]
@raisedadead could we merge this PR?

**Review by raisedadead — COMMENTED** [review]
Hi @hodovani Thanks a lot for the PR. We have decided conclusively that instead of merging this PR as is and having to invalidate all the existing sessions, we would be rewriting our API a bit to move away from this middleware. 

This is just cut the work involved in the ops. 

Your PR is still valid, and we thank you for taking the time to prepare this.

**Comment by hodovani** [comment]
@raisedadead thank you for the comment. I hope you would solve this problem :)

**Pull request closed without merging**
