### PR TITLE
fix(client): remove auto redirect in email sign up page

### LINKED ISSUE #42708: New user gets automatically redirected to /learn after briefly shown the intro page
**Affected page**
Add a Link to the page with the problem.

**To Reproduce**

1. Go to freecodecamp.org as an unauthenticated user and click Sign in
2. Enter a new email address that will sign you up as a new user
3. After the user enters the sign in code, they get redirected to a page where the intro ([IntroDescription](https://github.com/freeCodeCamp/freeCodeCamp/blob/main/client/src/components/Intro/components/IntroDescription.js)) is displayed, then almost immediately get redirected to /learn where they would see the curriculum. 

**Expected behavior**
I think the user should not be redirected to /learn automatically, as we would want them to read through the introduction page first.

**Screenshots**
If applicable, add screenshots to help explain your problem. you can drag and drop, png, jpg, gif, etc. in this box.

N/A

**System (please complete the following information):**
 - Device: Laptop
 - OS: MacOS
 - Browser: Firefox

**Additional context**
N/A

### PR DESCRIPTION
**Pull request by victor-duarte**
Checklist:

- [x] I have read [freeCodeCamp's contribution guidelines](https://contribute.freecodecamp.org).
- [x] My pull request has a descriptive title (not a vague title like `Update index.md`)
- [x] My pull request targets the `main` branch of freeCodeCamp.
- [x] I have tested these changes either locally on my machine, or GitPod.

Closes #42708

UPDATE: strike-though outdated items that this PR is not doing anymore. This PR will is focused on UI updates.

~Avoids users to be auto redirected from _email sign up page_ to _learn page_.~

**Assumptions**

   - ~User accepts terms and condition in the _login_ page after either submitting the code, using an email or Github~
   - ~On app load `acceptedPrivacyTerms` in state is always `true` when user is logged in~

**Important**

- ~Based on the assumptions, it seems the logic related to managing the `acceptedPrivacyTerms` in the store was deprecated, hence removed~
- ~Removed redirection to _email sign up page_ from _learn page_ if user was not sign in since _email sign up page_ is for newsletter opt-in and opt-out. Did not see any reason why to redirect the user there~

**UX Changes**

- ~Remove auto redirect to _learn page_ logic in _email sign up page_ and instead added a CTA for the action~
- ~opt-in / opt-out of newsletter is removed once user makes a selection, considering that users can later update selection from _settings page_~
- ~opt-in / opt-out newsletter section is not displayed If _email sign up page_ is reached without user being logged in~

**Visual Changes**

- Minor styles updates to match `learn` page, e.g: title, content width
- Reorder content
   - Set email opt-in/opt-out as the first item for users to interact with
   - ~Add CTA that redirects to learn page (styles are based on curriculum links from learn page)~

**Others**

- ~Renamed component function name since it does not accept terms~
- Add package to provide an initial state on tests
- Reorder some props alphabetically

**TODO**

~Add a couple of TODO's for later discussion to improve UX~

layout

_Apologies, for the large PR_

### CODE REVIEW

**Comment by victor-duarte** [comment]
Evidence:

https://user-images.githubusercontent.com/1746030/125313440-d8af4a80-e2fa-11eb-8c62-1ec6993cd7f2.mov

**Comment by victor-duarte** [comment]
@ojeytonwilliams, should this PR be closed due to the fix in [https://github.com/freeCodeCamp/freeCodeCamp/pull/42944](https://github.com/freeCodeCamp/freeCodeCamp/pull/42944)?

**Comment by ojeytonwilliams** [comment]
Hi @victor-duarte, that's a good question.  There's a lot I really like about this PR (the extensive tests for the sign up page, for example), but there are two issues.  

Firstly, as you say, the fix has been deployed (thanks again for letting us know about this).

Secondly, substantial changes to the UI would need @QuincyLarson's approval.

What I suggest is that we wait to see what Quincy has to say and then go from there.  I hope that makes sense.

**Review by raisedadead — COMMENTED** [review]
I really like the code simplification and refactoring from this as well.

Pending Quincy's go ahead on the UI changes, this should be good. Regardless of his thoughts, we should get the code refactoring bits in adjusting it all post his comments.

**Review by raisedadead — CHANGES_REQUESTED** [review]
Hi @victor-duarte 

Hope you are doing good? 

Do you mind undoing this:

> Set email opt-in/opt-out as the first item for users to interact with

and resolve the merge conflicts. Pending those, we are looking forward to getting this in. 

Thanks.

**Comment by victor-duarte** [comment]
Hey @raisedadead, I am doing good.

Since the original issue was tackled on another PR #42944, the work here can be considered "obsolete".
Having said that, all the changes related to the original fix have been reverted and only kept UI changes and some basic testing.

Hope this is what was requested.

**Screenshot**

image

**Comment by raisedadead** [comment]
Thanks @victor-duarte - I think a rebase should fix those conflicts.

**Comment by victor-duarte** [comment]
> Thanks @victor-duarte - I think a rebase should fix those conflicts.

Updated.

**Review by raisedadead — DISMISSED** [review]

**Comment by ojeytonwilliams** [comment]
@QuincyLarson could you take a look at the UI changes?

Before:
MainEmail

After:
PREmail

**Comment by QuincyLarson** [comment]
Thanks for @-mentioning me on chat. The "after" looks better. We should remove the words "email signup" from the top as well, since the goal is to get people to actually read the message rather than just scrolling down and clicking "no" which is what most of them are probably doing right now.

**Comment by victor-duarte** [comment]
Hi @QuincyLarson,
The `Email Sign Up` copy is actually the main headline of the page so from an SEO perspective it would be better to keep it. Before removing it I have the following recommendations.

**Option A**

1. Change the copy to something else that describes the page and keep the main headline `<h1>`
2. Move `Email Sign Up` down the page below the opt-in options making it a section header `<h2>`

proposal

**Option B**

The second alternative is to visually hide the title but keep it in the outline to follow SEO recommendations.

proposal-2

Please confirm the desired path to follow 👍🏻 

cc @ojeytonwilliams 

Regards,

**Comment by raisedadead** [comment]
We do not index these pages intentionally on search engines, these pages are behind auth. I am fairly sure we do not need to worry about SEO at all. 

I would request you to just remove the "Email Sign Up" up top, everything else looks good to go.

Thanks again for your work on this.

**Comment by victor-duarte** [comment]
@raisedadead, It has been removed.

image

Thank you for clarifying.

**Review by ojeytonwilliams — APPROVED** [review]
Nice work, as always. LGTM :+1: 

Thanks for bearing with us, @victor-duarte!

**Review by raisedadead — APPROVED** [review]

**Pull request merged**
