### PR TITLE
Guide: Visual Studio Code (tips and article additions)

### PR DESCRIPTION
**Pull request by DanielSegarra36**
- [x] I have read [freeCodeCamp's contribution guidelines](https://github.com/freeCodeCamp/freeCodeCamp/blob/master/CONTRIBUTING.md).
- [x] My pull request has a descriptive title (not a vague title like `Update index.md`)
- [x] My pull request targets the `master` branch of freeCodeCamp.
- [x] None of my changes are plagiarized from another source without proper attribution.
- [x] All the files I changed are in the same world language (for example: only English changes, or only Chinese changes, etc.)
- [x] My changes do not use shortened URLs or affiliate links.

Closes #XXXXX

### CODE REVIEW

**Comment by DanieSegarra36** [comment]
Hello @thecodingaviator @RandellDawson!

Is there anything I should clean up or fix in this PR?

Thank you for your time and have a great day!

**Comment by RandellDawson** [comment]
You show 3 files in your PR.  If you only changed the one file, that means you did not start with a clean master.  You should `git pull --rebase upstream master` and then `git push --force` to only have the single file on this commit.  Once you do that, then we can take a look at the actual changes you intended.

FYI - Before working on changes, you should always sync your master branch first with `git pull --rebase upstream master`.  Then when use `git checkout -b` to create a new branch, it will only have the changes you add.

**Comment by DanieSegarra36** [comment]
Thank you very much! Just cleaned it up!

**Review by thecodingaviator — APPROVED** [review]
LGTM

**Comment by thecodingaviator** [comment]
Thank you for your contribution to the page! 👍
We're happy to accept these changes, and look forward to future contributions. 📝

**Pull request merged**
