### PR TITLE
fix(curriculum): reword instructions in `XMLHttpRequest` section

### LINKED ISSUE #49875: Typo in Post Data with the JavaScript XMLHttpRequest Method module
### Describe the Issue

In [Post Data with the JavaScript XMLHttpRequest Method](https://www.freecodecamp.org/learn/data-visualization/json-apis-and-ajax/post-data-with-the-javascript-xmlhttprequest-method) module, currently, the instruction says:

You've seen several of these methods before. Here the `open` method initializes the request as a `POST` to the given URL of the external resource, and uses the `true` Boolean to make it asynchronous. The `setRequestHeader` method sets the value of an HTTP request header, which contains information about the sender and the request. It must be called after the `open` method, but before the `send` method. The two parameters are the name of the header and the value to set as the body of that header. Next, the `onreadystatechange` event listener handles a change in the state of the request. A `readyState` of `4` means the operation is complete, and a `status` of `201` means it was a successful request. The document's HTML can be updated. Finally, the `send` method sends the request with the `body` value, which the `userName` key was given by the user in the `input` field.

Instead of this, the instruction should be as follows:

You've seen several of these methods before. Here the `open` method initializes the request as a `POST` to the given URL of the external resource, and uses the `true` Boolean to make it asynchronous. The `setRequestHeader` method sets the value of an HTTP request header, which contains information about the sender and the request. It must be called after the `open` method, but before the `send` method. The two parameters are the name of the header and the value to set as the body of that header. Next, the `onreadystatechange` event listener handles a change in the state of the request. A `readyState` of `4` means the operation is complete, and a `status` of `201` means it was a successful request. The document's HTML can be updated now. Finally, the `send` method sends the request with the `body` value, in which the value of the `userName` key was given by the user via the `input` field.

**NOTE:** The last two sentence of the paragraph should be - _**The document's HTML can be updated now. Finally, the `send` method sends the request with the `body` value, in which the value of the `userName` key was given by the user via the `input` field.**_

### Affected Page

https://github.com/freeCodeCamp/freeCodeCamp/blob/main/curriculum/challenges/english/04-data-visualization/json-apis-and-ajax/post-data-with-the-javascript-xmlhttprequest-method.md

### Expected behavior

In [Post Data with the JavaScript XMLHttpRequest Method](https://www.freecodecamp.org/learn/data-visualization/json-apis-and-ajax/post-data-with-the-javascript-xmlhttprequest-method) module, the instruction should be as follows:

You've seen several of these methods before. Here the `open` method initializes the request as a `POST` to the given URL of the external resource, and uses the `true` Boolean to make it asynchronous. The `setRequestHeader` method sets the value of an HTTP request header, which contains information about the sender and the request. It must be called after the `open` method, but before the `send` method. The two parameters are the name of the header and the value to set as the body of that header. Next, the `onreadystatechange` event listener handles a change in the state of the request. A `readyState` of `4` means the operation is complete, and a `status` of `201` means it was a successful request. The document's HTML can be updated now. Finally, the `send` method sends the request with the `body` value, in which the value of the `userName` key was given by the user via the `input` field.

**NOTE:** The last two sentence of the paragraph should be - _**The document's HTML can be updated now. Finally, the `send` method sends the request with the `body` value, in which the value of the `userName` key was given by the user via the `input` field.**_

### Screenshots

image

### System

- Device: MacBook Pro
- OS: MacOS 13.3
- Browser: Chrome

### PR DESCRIPTION
**Pull request by anmxls**
Checklist:

- [x] I have read and followed the [contribution guidelines](https://contribute.freecodecamp.org).
- [x] I have read and followed the [how to open a pull request guide](https://contribute.freecodecamp.org/#/how-to-open-a-pull-request).
- [x] My pull request targets the `main` branch of freeCodeCamp.
- [x] I have tested these changes either locally on my machine, or GitPod.

Closes #49875

### CODE REVIEW

**Review by Sboonny — APPROVED** [review]
LGTM 🎉, thank you for your contribution to the page! 👍.

**Review by ShaunSHamilton — CHANGES_REQUESTED** [review]
Usually, we prefer brevity.

**Review by gikf — APPROVED** [review]
LGTM :+1:

**Review by ShaunSHamilton — APPROVED** [review]
This looks good to me 👍 

Thank you for your contribution to the page!
We are happy to accept these changes and look forward to future contributions. 📝

**Pull request merged**
