### PR TITLE
fix: add new test to create a set of new checkboxes

### LINKED ISSUE #18210: Checkboxes can be put outside designated form in "Basic HTML and HTML5: Create a Set of Checkboxes"
#### Describe your problem and - if possible - how to reproduce it
If you put a group of checkboxes outside `<form>` tests will pass though the assignment says 
> Add to your form a set of three checkboxes

Plus the previous challenge [Basic HTML and HTML5: Create a Set of Radio Buttons](https://learn.freecodecamp.org/responsive-web-design/basic-html-and-html5/create-a-set-of-radio-buttons/) actually has this check.

Solution: add check for the group of checkboxes to be inside `<form>` to tests.

#### Add a Link to the page with the problem
[Basic HTML and HTML5: Create a Set of Checkboxes](https://learn.freecodecamp.org/responsive-web-design/basic-html-and-html5/create-a-set-of-checkboxes/)

#### If possible, add a screenshot here
error

### PR DESCRIPTION
**Pull request by c-stu**
#### Pre-Submission Checklist

- [ ] Your pull request targets the `staging` branch of freeCodeCamp.
- [x] Branch starts with either `fix/`, `feature/`, or `translate/` (e.g. `fix/signin-issue`)
- [x] You have only one commit (if not, [squash](http://forum.freecodecamp.org/t/how-to-squash-multiple-commits-into-one-with-git/13231) them into one commit).
- [ ] All new and existing tests pass the command `npm test`. Use `git commit --amend` to amend any fixes.

#### Type of Change

- [x ] Small bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds new functionality)
- [ ] Breaking change (fix or feature that would change existing functionality)
- [ ] Add new translation (feature adding new translations)

#### Checklist:

- [x] Tested changes locally.
- [x] Addressed currently open issue (replace XXXXX with an issue no in next line)

Closes #18210

### CODE REVIEW

**Comment by raisedadead** [comment]
Hi @c-stu ,

Thanks for taking the time to prepare this PR.

This pull request needs to be tested locally. We will update the contributing documentation to reflect this requirement.

We will get back to you on further steps.

**Comment by lizardscruff** [comment]
If there is still an issue here, can I be of help to resolve it?

**Comment by c-stu** [comment]
@lizardscruff if you could test the change locally that would be great. Running bootstrap stage is just hanging for me

**Comment by scissorsneedfoodtoo** [comment]
Got local development running long enough to test this. Turns out I had to play with the single and double quotation marks a bit to get the test suite and tests in the browser to pass.

**Comment by scissorsneedfoodtoo** [comment]
@c-stu, everything LGTM! Thank you for helping us improve this section of the curriculum, and congratulations on your first contribution to freeCodeCamp! Looking forward to your next contribution :+1: :+1:

**Pull request merged**
