### PR TITLE
Fix: Remove slot machine challenges

### PR DESCRIPTION
**Pull request by BerkeleyTrue**

### CODE REVIEW

**Comment by abhisekp** [comment]
I made a fix https://github.com/FreeCodeCamp/FreeCodeCamp/pull/10546
Why is the slot machine challenge removed?

**Comment by BerkeleyTrue** [comment]
It was shelved a long time ago. It's not supposed to show up.

**Comment by QuincyLarson** [comment]
@abhisekp sorry for the confusion. These challenges generated a ton of complaints, and we don't plan to bring them back.

**Comment by QuincyLarson** [comment]
@BerkeleyTrue This seeds and runs fine. 

I can merge this as soon as the failing tests are fixed:
 ✖ test exited without ending
    -----------------------------
      operator: fail


    ✖ plan != count
    ----------------
      operator: fail
      expected: 2
      actual:   3


  Failed Tests: There were 2 failures

    These challenges have no solutions

      ✖ test exited without ending
      ✖ plan != count

**Comment by BerkeleyTrue** [comment]
That's what I'm trying to figure out. Remove challenges shouldn't break tests.

**Comment by erictleung** [comment]
@BerkeleyTrue @QuincyLarson I tried removing these challenges a while ago and ran into similar issues https://github.com/FreeCodeCamp/FreeCodeCamp/pull/8267. I couldn't find the source of the issue.

I tried removing each slot machine challenge one by one to see if it was a particular challenge. I was able to remove all but the last one without any issues. I hope some of my findings prove to be useful somehow.

**Comment by BerkeleyTrue** [comment]
Can't figure out why the test challenges fails with removal. I'm going to take a different approach.

**Comment by augmt** [comment]
Is the [process.exit(0) at the end of seed/test-challenges.js](https://github.com/FreeCodeCamp/FreeCodeCamp/blob/546572fbe82f2025872e9c22d20bb2bffbf40645/seed/test-challenges.js#L136) necessary? Removing it gets rid of the failures as it allows the final test to end properly.

**Comment by BerkeleyTrue** [comment]
@augmt Excellent find! I'll look into why that is.

**Pull request closed without merging**
