### PR TITLE
fix(curriculum): correct pronoun gender

### LINKED ISSUE #53920: typo - English for developers - 4th course, Task 5 - her not his
### Describe the Issue

Sophie is misgendered in the first sentence of task5 of the 4th course

'In this part of the dialogue, Sophie talks about his morning activities.'

### Affected Page

https://www.freecodecamp.org/learn/a2-english-for-developers/learn-how-to-talk-about-a-typical-workday-and-tasks/task-5

### Steps to Reproduce

-Proceed to the 4th course 'Learn How to Talk About a Typical Workday and Tasks'
-Proceed to Task 5
-Observe the first sentence 'In this part of the dialogue, Sophie talks about his morning activities.'

### Recommended fix or suggestions

Please change the first sentence to:

In this part of the dialogue, Sophie talks about her morning activities.

### Screenshots

his

### PR DESCRIPTION
**Pull request by kunalg12**
Describe the Issue

Sophie is misgendered in the first sentence of task5 of the 4th course

'In this part of the dialogue, Sophie talks about his morning activities.' changed to "In this part of the dialogue, Sophie talks about her morning activities"

Checklist:

- [x] I have read and followed the [contribution guidelines](https://contribute.freecodecamp.org).
- [x] I have read and followed the [how to open a pull request guide](https://contribute.freecodecamp.org/#/how-to-open-a-pull-request).
- [x] My pull request targets the `main` branch of freeCodeCamp.
- [x] I have tested these changes either locally on my machine, or GitPod.

Closes #53920

### CODE REVIEW

**Comment by Sembauke** [comment]
Could you update the title? It is not clear.

**Comment by RGHANILOO** [comment]
By updating the title they are referring to [Prepare a Good PR Title](https://contribute.freecodecamp.org/#/how-to-open-a-pull-request?id=prepare-a-good-pr-title)

**Comment by Sembauke** [comment]
> By updating the title they are referring to [Prepare a Good PR Title](https://contribute.freecodecamp.org/#/how-to-open-a-pull-request?id=prepare-a-good-pr-title)

Please follow ^

**Review by majestic-owl448 — APPROVED** [review]
LGTM 👍

**Review by huyenltnguyen — APPROVED** [review]
LGTM 👍

@kunalg12 Thank you for the PR and congratulations on your first contribution to this repo 🎉
We look forward to your next.

Happy contributing!

**Pull request merged**
