### PR TITLE
Replaces Project Euler stub with an article

### PR DESCRIPTION
**Pull request by ArielLeslie**
- [x] I have read [freeCodeCamp's contribution guidelines](https://github.com/freeCodeCamp/freeCodeCamp/blob/master/CONTRIBUTING.md).
- [x] My pull request has a descriptive title (not a vague title like `Update index.md`)
- [x] My pull request targets the `master` branch of freeCodeCamp.
- [x] None of my changes are plagiarized from another source without proper attribution.
- [x] My article does not contain shortened URLs or affiliate links.

### CODE REVIEW

**Comment by procode200** [comment]
How can we get it back to a stub again?

I want to write one replacing this current one.

**Comment by Manish-Giri** [comment]
@procode200 What's wrong with the current article? If you have new additions, feel free to create a PR, but there's no reason to replace the suggested changes.

**Comment by nathanhannig** [comment]
LGTM, I just added markdown to change the More Information section into an unordered list.

I will merge once the CI finishes again

**Comment by nathanhannig** [comment]
looks like all CIs are failing at the moment due to this issue
https://github.com/freeCodeCamp/freeCodeCamp/issues/24688#issuecomment-432397896

**Comment by nathanhannig** [comment]
Hi @ArielLeslie. Congrats on your first pull request (PR)! 🎉

Thank you for your contribution to the page! 👍
We're happy to accept these changes, and look forward to future contributions. 📝

**Pull request merged**
