### PR TITLE
fix(learn): correcting Hash Table Lookup Efficiency

### PR DESCRIPTION
**Pull request by srdubya**
A hash table provides a lookup of O(1), not O(n).

- [x] I have read [freeCodeCamp's contribution guidelines](https://github.com/freeCodeCamp/freeCodeCamp/blob/master/CONTRIBUTING.md).
- [x] My pull request has a descriptive title (not a vague title like `Update index.md`)
- [x] My pull request targets the `master` branch of freeCodeCamp.
- [x] None of my changes are plagiarized from another source without proper attribution.
- [x] All the files I changed are in the same world language (for example: only English changes, or only Chinese changes, etc.)
- [x] My changes do not use shortened URLs or affiliate links.

Closes #XXXXX

### CODE REVIEW

**Comment by RandellDawson** [comment]
@srdubya There is a reason why we have checkbox number 5 above.

> All the files I changed are in the same world language (for example: only English changes, or only Chinese changes, etc.)

Unless you have received special permission, please do not make changes to files of different languages as it takes longer to get them reviewed.

**Comment by srdubya** [comment]
My apologies...  That particular check box went in one eye and out the other.  I won't make that mistake again.  If you'd like me to do something to fix my blunder, please let me know.

**Comment by raisedadead** [comment]
No worries, considering this is your first PR to this codebase you are doing great. We typically want to have separate PRs for each language. This is to make the QA easy because not all contributors speak all the languages and hence are unable to give full approval for a merge.

If you are comfortable with git then you should be able to reset the changes to files other than english and update this PR and also make changes only to one language in separate PRs.

If not, you should be fine as well, and we would recommend you consider the same in future PRs.

Thanks for your contributions.

**Comment by raisedadead** [comment]
@RandellDawson going by the diff can we let this be merged? I think its a minor change of the notation?

**Review by RandellDawson — APPROVED** [review]

**Comment by RandellDawson** [comment]
@ojeytonwilliams Any idea why this is failing?

**Comment by ojeytonwilliams** [comment]
@RandellDawson not a clue.  I've restarted it in case it was a problem with Travis.

**Comment by ojeytonwilliams** [comment]
> Checking formatting...
[19:48:44] Using gulpfile ~/build/freeCodeCamp/freeCodeCamp/curriculum/gulpfile.js
[19:48:45] Starting 'lint'...
Segmentation fault (core dumped)

I'll investigate tomorrow, but there's no reason I can think of that changing markdown would do that, so I'm still leaning towards it being a Travis problem.

**Pull request merged**
