### PR TITLE
Wrapped up regexp

### PR DESCRIPTION
**Pull request by Andrey-Raspopov**
Check if something matching these regexps exist, so we can take its length

### CODE REVIEW

**Comment by bugron** [comment]
@Harmitage your branch has conflicts with FCC's staging branch. Please resolve those conflicts and push it back, thanks!

**Comment by ahstro** [comment]
Looks promising, but it's late and I'm slow, so would someone mind explaining what this prevents? Preferrably with a code example so I can test the code. Thanks! :)

**Comment by bugron** [comment]
@ahstro Seems this is fixed. https://github.com/FreeCodeCamp/FreeCodeCamp/blob/staging/seed/challenges/basic-javascript.json#L518

**Comment by BerkeleyTrue** [comment]
@bugron Has this indeed been fixed?

**Comment by bugron** [comment]
@BerkeleyTrue we have already https://github.com/FreeCodeCamp/FreeCodeCamp/pull/2825 merged which fixes 'editor.getValue(...).match(...) is null' error.

**Comment by BerkeleyTrue** [comment]
Closing as already fixed.

@Harmitage Thanks for the PR.

Happy Coding.

**Pull request closed without merging**
