### PR TITLE
Added more clarification on how to use z-index

### LINKED ISSUE #34928: Suggestion for "Applied Visual Design: Change the Position of Overlapping Elements with the z-index Property"
Only a suggestion for the [Applied Visual Design: Change the Position of Overlapping Elements](https://learn.freecodecamp.org/responsive-web-design/applied-visual-design/change-the-position-of-overlapping-elements-with-the-z-index-property/) with the z-index Property challenge:

It might be beneficial if the instructions mentioned that z-index requires the presence of the position property. It is kind of implied, since only position changes the flow, but learning about this requirement helped me to gain a better understanding of the subject.

### PR DESCRIPTION
**Pull request by thecodingaviator**
- [x] I have read [freeCodeCamp's contribution guidelines](https://github.com/freeCodeCamp/freeCodeCamp/blob/master/CONTRIBUTING.md).
- [x] My pull request has a descriptive title (not a vague title like `Update index.md`)
- [x] My pull request targets the `master` branch of freeCodeCamp.
- [x] None of my changes are plagiarized from another source without proper attribution.
- [x] All the files I changed are in the same world language (for example: only English changes, or only Chinese changes, etc.)
- [x] My changes do not use shortened URLs or affiliate links.

Closes #34928

### CODE REVIEW

**Comment by ahmadabdolsaheb** [comment]
Thanks @thecodingaviator, LGTM!

**Comment by RandellDawson** [comment]
@thecodingaviator `z-index` works other positioned elements (position: absolute|relative|fixed) and not just `position: absolute`.  Maybe instead of your proposed changes, the first sentence could be written something like:

>When elements are positioned (i.e. `position: absolute | relative| fixed`) to overlap, the element coming later in the HTML markup will, by default, appear on the top of the other elements.

Or maybe put an asterisk on the word positioned and have a note say something like:
>`*` Positioned means elements which have the value of `absolute`, `relative`, or `fixed` for the `posiition` property.

**Review by RandellDawson — CHANGES_REQUESTED** [review]
See my comments.

**Comment by thecodingaviator** [comment]
@RandellDawson How does this look?

**Comment by RandellDawson** [comment]
@thecodingaviator I believe that looks fine, however I forgot about one (`position: sticky`).

**Comment by thecodingaviator** [comment]
@RandellDawson Changes made

**Review by RandellDawson — APPROVED** [review]

**Review by RandellDawson — APPROVED** [review]
I have tested this wording change and believe it fixes the issue described in the issue it closes.

**Review by ezioda004 — APPROVED** [review]

**Comment by ezioda004** [comment]
Thank you @thecodingaviator for your contribution. Looking forward to more contributions from you! 🎉

**Pull request merged**
