### PR TITLE
fix(curriculum): fix typo for "your" in one of the curriculum challenge

### LINKED ISSUE #57524: [Library Manager Workshop] Typo in step 2
## Description

Change "yoour" to "your" in:

https://github.com/freeCodeCamp/freeCodeCamp/blob/723c15281f6abf53fdf690bec1e690ba91dd2828/curriculum/challenges/english/25-front-end-development/workshop-library-manager/67116d7584d0b469b14579bf.md#L69

### PR DESCRIPTION
**Pull request by chaitanyarahalkar**
Checklist:

- [x] I have read and followed the [contribution guidelines](https://contribute.freecodecamp.org).
- [x] I have read and followed the [how to open a pull request guide](https://contribute.freecodecamp.org/how-to-open-a-pull-request/).
- [x] My pull request targets the `main` branch of freeCodeCamp.
- [x] I have tested these changes either locally on my machine, or GitPod.

Closes #57524

This PR - 
- Fixes a typo for the word "your" in the curriculum challenge.

### CODE REVIEW

**Comment by chaitanyarahalkar** [comment]
@huyenltnguyen fyi this PR fixes #57524

**Review by gikf — COMMENTED** [review]
Please remove changes unrelated to this PR - typo in _avaialbe_.

**Comment by chaitanyarahalkar** [comment]
@gikf done! sorry for that

**Review by gikf — APPROVED** [review]

**Review by Sembauke — APPROVED** [review]

**Comment by gikf** [comment]
Hi @chaitanyarahalkar. Congrats on your first pull request (PR)! 🎉

Thank you for your contribution to the page! 👍
We are happy to accept these changes and look forward to future contributions. 📝

**Pull request merged**
