### PR TITLE
Allow strings to be passed in function test

### LINKED ISSUE #5701: Waypoint: Passing Values to Functions with Arguments (probable result checker issue)
Challenge [Waypoint: Passing Values to Functions with Arguments](http://www.freecodecamp.com/challenges/waypoint-passing-values-to-functions-with-arguments#?solution=%2F%2F%20Example%0Afunction%20ourFunction(a%2C%20b)%20%7B%0A%20%20console.log(a%20-%20b)%3B%0A%7D%0AourFunction(10%2C%205)%3B%20%2F%2F%20Outputs%205%0A%0A%2F%2F%20Only%20change%20code%20below%20this%20line.%0Afunction%20myFunction(param1%2C%20param2)%20%7B%0A%20%20console.log(param1%2Bparam2)%3B%0A%7D%0AmyFunction(%22booyakasha%22%2C%22%20ali%20pali%22)%3B%0A) has an issue.
User Agent is: <code>Mozilla/5.0 (X11; CrOS x86_64 5841.83.0) AppleWebKit/537.36 (KHTML like Gecko) Chrome/36.0.1985.138 Safari/537.36</code>.
Please describe how to reproduce this issue, and include links to screenshots if possible.

My code:
```javascript
// Example
function ourFunction(a, b) {
  console.log(a - b);
}
ourFunction(10, 5); // Outputs 5

// Only change code below this line.
function myFunction(param1, param2) {
  console.log(param1+param2);
}
myFunction("booyakasha"," ali pali");
```
note: **myFunction("booyakasha"," ali pali");**

Response is:
```javascript
ok > myFunction should be a function
ok > myFunction(1,2) should output 3
ok > myFunction(7,9) should output 16
not ok > Call myFunction after you define it
```
note: **not ok > Call myFunction after you define it**

If my code is:
```javascript
// Example
function ourFunction(a, b) {
  console.log(a - b);
}
ourFunction(10, 5); // Outputs 5

// Only change code below this line.
function myFunction(param1, param2) {
  console.log(param1+param2);
}
myFunction(548,958);
```
note: **myFunction(548,958);**

Response is:
```javascript
ok > myFunction should be a function
ok > myFunction(1,2) should output 3
ok > myFunction(7,9) should output 16
ok > Call myFunction after you define it 
```
note: **ok > Call myFunction after you define it**

Conclusion: result checker considers function not called, even though it is, if strings are passed as parameters.

PS: just checked combination param1 = int, param2 = str; checker returns failure => if at least one param is a string, checker most probably doesn't work in a correct way.

### PR DESCRIPTION
**Pull request by ShaggyTech**
Fixes #5701. For Waypoint: Passing Values to Functions with Arguments.
Changes the last test to allow strings to be passed as arguments in myFunction.

### CODE REVIEW

**Comment by ltegman** [comment]
Please remove `Fixes #5701` from the title of your PR and move it into the body.

**Comment by abhisekp** [comment]
@ShaggyTech I think the instruction also needs modification to pass in a parameter.

**Comment by ShaggyTech** [comment]
Yep my mistake on the title.  It should be fixed now.

@abhisekp Not exactly sure what you mean by that, I changed it to say "making sure to pass it two arguments".  Not passing any arguments is still less than two and the test will still fail.  If you pass it more than two it will just ignore anything after the second one.

**Comment by ShaggyTech** [comment]
@ltegman I need to change the regex to allow any characters like ```.``` and ```,```.   Should I make another commit and pull request?  If not, what is the correct way to go about changing something in my commit here.

**Comment by ltegman** [comment]
Good catch! You can make the change on your local branch and then `git add . && git commit --amend && git push -f` to ammend you commit and force push the change to the PR :smile:

**Comment by abhisekp** [comment]
@ShaggyTech it will also be nice to appending the line in the instruction `Call the function passing two arguments` in 
https://github.com/FreeCodeCamp/FreeCodeCamp/pull/5713/files#diff-5fbffcdf48f7976dd3b0216c387eebc2R1856

**Comment by ShaggyTech** [comment]
@ltegman  Well that was less painful than I thought it was going to be :+1: Thank you for the help!  Fixed the PR so the function accepts any characters inside a string.

**Comment by DDaems** [comment]
@ShaggyTech 

this passes:
```
// Example
function ourFunction(a, b) {
  console.log(a - b);
}
ourFunction(10, 5); // Outputs 5
myFunction("booyakasha", "ali pali");
// Only change code below this line.
function myFunction(param1, param2) {
  console.log(param1+param2);
}
```

Please alter the test, so it does exactly what its supposed to do. Also you do not have to explicitly test if 2 arguments or provided ;-)

**Comment by ShaggyTech** [comment]
@DDaems 
Ok I've altered the test so the function must be defined before calling it.

Regarding testing for 2 arguments provided, I assumed passing in two arguments was a requirement for passing the last test.  After going back and looking at the instructions again I think you're correct in that it was originally intended to just test if the function was called.

But this also brings up the question of why test for any arguments at all?  If the only requirement to pass the last test (according to the original instructions and test description) is to call the function, then shouldn't the test just check to make sure the function was called, regardless of # of arguments?

**Comment by DDaems** [comment]
Because a function is only called when there are `()` brackets behind it, this meens that you would actually need to parse trough it anyway. Hence you might aswell check if its somewhat valid. ;-)

**Comment by ltegman** [comment]
@DDaems Functions declarations are hoisted, so the location in the code where they use it is unimportant.

@ShaggyTech The following requirement will be sufficient, we don't need to overcomplicate this.
>Call the function, making sure to pass it two arguments.

**Comment by ShaggyTech** [comment]
@ltegman Sounds good, I'll make the change to the instructions to reflect that. 
However, because the test explicitly states:
> Call myFunction **after** defining it.

I feel the test should check that you've defined the function first, as @DDaems pointed out.

**Comment by ltegman** [comment]
After in this case could also mean later in time. I think when possible avoiding imposing arbitrary limitations to the code that a user can pass with is a bad idea. It generally leads to confusion and bugs/support requests.

**Comment by DDaems** [comment]
We might aswell than remove the test, sinds its pretty much pointless and confusing. It sure the hell fooled me :-) even tho i know functions or hoisted. I though it was supposed to be defined first before doing the call.

Sinds it brings no other addition to the tests. I think we can remove it.
Test 1 is pretty much the same anyway
@ltegman @ShaggyTech

**Comment by ShaggyTech** [comment]
I've amended the PR.  The only change now from the original code is to allow strings to be passed to the function and still pass the last test.

The original issue #5701 that was reported has now been remedied with the latest amendment to the PR. I do agree with @DDaems that there are some other problems with this waypoint.  However, I think any other problems/issues should be discussed elsewhere.

**Comment by ltegman** [comment]
:+1:

**Pull request merged**
