### PR TITLE
feat: change header structure in the landing page

### PR DESCRIPTION
**Pull request by Sboonny**
Checklist:

- [x] I have read and followed the [contribution guidelines](https://contribute.freecodecamp.org).
- [x] I have read and followed the [how to open a pull request guide](https://contribute.freecodecamp.org/#/how-to-open-a-pull-request).
- [x] My pull request targets the `main` branch of freeCodeCamp.
- [x] I have tested these changes either locally on my machine, or GitPod.

Changed the structure of the landing page headers of having multiple `h1` headers, there should be other pages that affected by changing in the `Map` component,

### CODE REVIEW

**Review by naomi-lgbt — CHANGES_REQUESTED** [review]
Semantically this is correct - but are we okay with the smaller heading font from a UI perspective?

**Comment by Sboonny** [comment]
I have no opinion on either, up to you 👍.

**Review by naomi-lgbt — APPROVED** [review]
I'm good with this.

**Comment by moT01** [comment]
Are we sure we don't want to keep these as `h1`'s? I see some [conflicting opinions on using more than one per page](https://stackoverflow.com/questions/503925/is-it-alright-to-use-multiple-h1-tags-on-the-same-page-but-style-them-different) - many say it's fine.

**Comment by Sboonny** [comment]
I would argue, that the main point of freeCodeCamp isn't the certification or FAQ, but the ability to learn for free, certifications and FAQ are a section of freeCodeCamp, and it falls under the ability to learn for free.

**Comment by Sboonny** [comment]
I will link this to Ahmad 👍 in chat, to clear what we are missing.

Btw, the reason I don't care about the SEO section, because this paragraph is mentioned in the [article](https://granwehr.com/blog/multiple-h1-tags#can-you-have-multiple-h1-tags-on-a-page).

> John Mueller explained how SEO marketers should approach this topic:
>
> _“In short, when thinking about this topic, SEO shouldn’t be your primary objective. Instead, think about your users. If you have ways of making your content accessible to them, be it by using multiple H1 headings or other standard HTML constructs, then that’s not going to get in the way of your SEO efforts.”_

**Comment by bbsmooth** [comment]
Current best practice is to only have one `h1` near the top of the page. I would tend to agree with this PR that the other `h1`s should be `h2`s. But just to be clear, multiple `h1`s are not a WCAG failure. But unless there is a very good reason why all of these headings need to be `h1` then I think we should follow best practices.

**Review by ahmaxed — APPROVED** [review]

**Pull request merged**
