### PR TITLE
Added test to determine num of elements with class

### LINKED ISSUE #1762: "Waypoint: Change the Font Size of an Element" Still has a problem (in live and beta)
As described in issue #492, [this Waypoint](http://www.freecodecamp.com/challenges/waypoint-change-the-font-size-of-an-element) is still accepting incorrect code as correct, as does the [beta site](http://beta.freecodecamp.com/challenges/waypoint-change-the-font-size-of-an-element).

The last requirement is "give your p elements the font size of 16px" but you only have to give the first one the correct size for it to be accepted. You don't need any sort of style at all on your second p:

image

### PR DESCRIPTION
**Pull request by butterthebuddha**
Closes #1762 

Apologies for the oversight.

### CODE REVIEW

**Comment by bugron** [comment]
@awesomeaniruddh not sure why there are two single quotes at the end of ` "assert($(\"p.red-text\").length === 2, 'Give each of your <code>p</code> elements the <code>red-text</code> class.'')",`? This causes an error.
Also I want to discuss **the**s.
>"Give **the** elements with **the** red-text class **the** font-size of 16px." seems there is an extra **the** (or two), but I'm not sure at this point.

**Comment by awesomeaniruddh** [comment]
^ Fixed the **the**s. Seems like me text editor did that. Let me fix it. Phew.

**Comment by awesomeaniruddh** [comment]
Yep, done.

**Comment by bugron** [comment]
@awesomeaniruddh Excellent, verified and merged, thanks for the PR!

**Pull request merged**
