### PR TITLE
CSS Flexbox QA and intro edits for other sections.

### PR DESCRIPTION
**Pull request by HKuz**
#### Pre-Submission Checklist

- [x] Your pull request targets the `feature/curriculum-expansion` branch of FreeCodeCamp (not `staging`).
- [x] Branch starts with either `fix/`, `feature/`, or `translate/` (e.g. `fix/signin-issue`)
- [x] You have only one commit (if not, [squash](http://forum.freecodecamp.com/t/how-to-squash-multiple-commits-into-one-with-git/13231) them into one commit).
- [ ] All new and existing tests pass the command `npm run test-challenges`. Use `git commit --amend` to amend any fixes. [Tests not passing in general for branch]
#### Type of Change

- [x] Small bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds new functionality)
- [ ] Breaking change (fix or feature that would change existing functionality)
- [ ] Add new translation (feature adding new translations)
#### Checklist:

- [x] Tested changes locally.
- [ ] Closes currently open issue (replace XXXX with an issue no): Closes #XXXX
#### Description

QA for the CSS Flexbox section - challenges imported, text reviewed. Running the assert tests in browser are still outstanding. Other changes were text edits for introductions and titles in several sections.

### CODE REVIEW

**Comment by HKuz** [comment]
I'm not sure if it's a local issue of recent changes on the branch, but when I had this running in browser, all the assert tests (in several sections) were passing without correct code. Even when no answer was entered, or I deleted all the code out of the editor. It happened on both Firefox and Chrome.

**Comment by HKuz** [comment]
@QuincyLarson - there are some key collisions on the latest branch. If you're not working in the backend files  with the duplicates (info security with helmet.js, advanced express tools, and quality assurance testing with Chai), I can jump in and edit the IDs and update this PR. Let me know!

**Comment by QuincyLarson** [comment]
@HKuz We can resolve these collisions on Skype later today if that's convenient for you. I'm in the process of inputing the back end challenges.

**Comment by HKuz** [comment]
@QuincyLarson I actually haven't touched those sections (an won't as you're working in them). I'll leave this PR as is.

**Pull request merged**
