### PR TITLE
Update Chinese footer

### PR DESCRIPTION
**Pull request by miyaliu666**
Checklist:

- [x] I have read [freeCodeCamp's contribution guidelines](https://contribute.freecodecamp.org).
- [x] My pull request has a descriptive title (not a vague title like `Update index.md`)
- [x] My pull request targets the `main` branch of freeCodeCamp.
- [x] All the files I changed are in the same world language, for example: only English changes, or only Chinese changes, etc.

### CODE REVIEW

**Review by naomi-lgbt — DISMISSED** [review]
Looks good to me.

**Comment by ahmadabdolsaheb** [comment]
i am not sure if they are ordered based on their popularity, but it would be great if we could move all of the longer titles to the leftmost column otherwise the items would wrap and the grid would break.

image

**Comment by miyaliu666** [comment]
> i am not sure if they are ordered based on their popularity, but it would be great if we could move all of the longer titles to the leftmost column otherwise the items would wrap and the grid would break.
> 
> image

Yes, they're ordered based on popularity. Just updated those three titles. Now they should be fine. Thanks for mentioning that.

**Comment by ahmadabdolsaheb** [comment]
Looks very good. thanks for the update.

**Review by ahmaxed — APPROVED** [review]

**Review by naomi-lgbt — APPROVED** [review]

**Pull request merged**
