### PR TITLE
fix(challenge): Fix tests for "Basic JS: Global scope and functions"

### LINKED ISSUE #13372: oopsGlobal variable
Without the oopsGlobalVariable the test will pass all but the last test. 
myGlobal should be defined
myGlobal should have a value of 10
myGlobal should be declared using the var keyword
oopsGlobal should have a value of 5
**Do not declare oopsGlobal using the var keyword**

#### Issue Description

It happened on the first try that the test seemed to treat the code as having the var keyword before oopsglobal
#### Browser Information

* Browser Name, Version:  Chrome
* Operating System: Chromebook,
* Mobile, Desktop, or Tablet: 

#### Your Code

```js
// Declare your variable here
var myGlobal=10;

function fun1() {
  // Assign 5 to oopsGlobal Here
  oopsGlobal=5;
}


// Only change code above this line
function fun2() {
  var output = "";
  if (typeof myGlobal != "undefined") {
    output += "myGlobal: " + myGlobal;
  }
  if (typeof oopsGlobal != "undefined") {
    output += " oopsGlobal: " + oopsGlobal;
  }
  console.log(output);
}
```

### PR DESCRIPTION
**Pull request by Greenheart**
#### Pre-Submission Checklist

- [x] Your pull request targets the `staging` branch of freeCodeCamp.
- [x] Branch starts with either `fix/`, `feature/`, or `translate/` (e.g. `fix/signin-issue`)
- [x] You have only one commit (if not, [squash](http://forum.freecodecamp.com/t/how-to-squash-multiple-commits-into-one-with-git/13231) them into one commit).
- [x] All new and existing tests pass the command `npm test`. Use `git commit --amend` to amend any fixes.

#### Type of Change

- [x] Small bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds new functionality)
- [ ] Breaking change (fix or feature that would change existing functionality)
- [ ] Add new translation (feature adding new translations)

#### Checklist:

- [x] Tested changes locally.
- [x] Closes currently open issue (replace XXXX with an issue no): Closes #13372 

#### Description

Since the last test case was triggering on a line from the challenge
head, it was necessary to slightly modify the test cases.

They now let the expected code pass by only testing the result of the code rather than the syntax used.

### CODE REVIEW

**Comment by dhcodes** [comment]
Tested locally and **LGTM**. Thanks @Greenheart 👍 💯 🎉

**Comment by RoniqueRicketts** [comment]
I tried this and it failed.
```
var myGlobal = 10;
function fun1() {
  // Assign 5 to oopsGlobal Here
  oopsGlobal = 5;
}

// Only change code above this line
function fun2() {
  var output = "";
  if (typeof myGlobal != "undefined") {
    output += "myGlobal: " + myGlobal;
  }
  if (typeof oopsGlobal != "undefined") {
    output += " oopsGlobal: " + oopsGlobal;
  }
  console.log(output);
}
```

**Comment by dhcodes** [comment]
@RoniqueRicketts the beta site is not immediately updated with each merge so give it a few days and it should work once the beta site is built again from the github codebase.

**Comment by pyan83** [comment]
Hi, I also have the same code as @RoniqueRicketts and this says that "oopsGlobal should have a value of 5" when it does. This doesn't seem to have been updated yet.

**Comment by Greenheart** [comment]
@pyan83 Are you using beta.freecodecamp.com? This fix is probably not pushed to the main site yet as it's part of our curriculum expansion effort.

**Comment by pyan83** [comment]
Ah, using the main site. Should I be using the beta one instead? How long does it take to push things through? Thx for the help

**Comment by Greenheart** [comment]
@pyan83 That explains it :blush:

We don't have a specific release date but we're doing our best. These updates will bring huge improvements so they will be worth the wait!

Feel free to help beta test it on https://beta.freecodecamp.com :smile:

Happy coding!

**Pull request merged**
