### PR TITLE
fix(challenges): Change invalid ObjectId

### PR DESCRIPTION
**Pull request by ATLowther**
#### Pre-Submission Checklist

- [x] Your pull request targets the `staging` branch of freeCodeCamp.
- [x] Branch starts with either `fix/`, `feature/`, or `translate/` (e.g. `fix/signin-issue`)
- [x] You have only one commit (if not, [squash](http://forum.freecodecamp.org/t/how-to-squash-multiple-commits-into-one-with-git/13231) them into one commit).
- [x] All new and existing tests pass the command `npm test`. Use `git commit --amend` to amend any fixes.

#### Type of Change

- [x] Small bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds new functionality)
- [ ] Breaking change (fix or feature that would change existing functionality)
- [ ] Add new translation (feature adding new translations)

#### Checklist:

- [x] Tested changes locally.
- [x] Addressed currently open issue (replace XXXXX with an issue no in next line)

#### Description
Change an Invalid MongoDB ObjectId from the challenges.

### CODE REVIEW

**Review by no-stack-dub-sack — CHANGES_REQUESTED** [review]
@ATLowther assuming you followed the proper steps to produce the new ObjectId, this looks good to me, but would you mind updating the commit messages so that the issue number is not in it? Part of the guidelines for this repo is that commit messages should never have issue numbers. Once you update the PR, I'd be happy to accept it! 

Let me know if you need guidance on how to do this.

**Comment by ATLowther** [comment]
@no-stack-dub-sack, I'm new to contributing to anything other than my own small projects. This will be my first PR request, so I'm still working through all of the small details that are new to me. Did I even put the issue number in the commit message? I don't see it anywhere.

**Comment by systimotic** [comment]
@no-stack-dub-sack Having the issue number in the commit is recommended now that we integrated `commitizen` 😅. @camperbot is no longer complaining about `closes` being in the commit message, this was removed [here](https://github.com/freeCodeCamp/camper-gh-bot/commit/d9024ed910628d88f95fe946120b2cca56da3410).

@ATLowther It's in the description, you need to click the "..." to see it.

**Comment by ATLowther** [comment]
@systimotic, okay thanks. I used commitizen, so I did not manually type the commit message. Is this something I still need to update, or it is approved as is?

**Review by systimotic — APPROVED** [review]
As @no-stack-dub-sack already mentioned, this looks good to me as well. I can confirm that the new ID is a valid MongoDB ObjectId.

Thanks a lot for contributing @ATLowther, congratulations on your first pull request!
## 🎉 🎉 🎉

**Comment by systimotic** [comment]
@ATLowther This is good to go as is 😃 Previously, we did ask people not to put issue numbers in commit messages, but these guidelines changed recently (which is why Peter understandably wasn't aware). You used commitizen correctly 👍

**Comment by no-stack-dub-sack** [comment]
@systimotic Oh! How about that!? Look at me trying to enforce rules that don't exist 😄 

I was wondering why everyone seemed to be doing that lately. 

We should prob remove [this](https://github.com/freeCodeCamp/freeCodeCamp/blob/staging/CONTRIBUTING.md#common-steps) from the docs... thoughts?

**Comment by systimotic** [comment]
@no-stack-dub-sack Good catch, we should absolutely remove that. That whole section could use a rewrite to take the PR template into account. It suggest you should put `closes #xxxx` at the bottom and indicate whether you tested locally, but those are both in the template.

**Pull request merged**
