### PR TITLE
Added solution for Bonfire:Check for Palindromes

### PR DESCRIPTION
**Pull request by ribeirojpn**
added solution for Bonfire:Check for Palindromes, passed in all tests.

### CODE REVIEW

**Comment by BerkeleyTrue** [comment]
Can you squash your commits into one?

**Comment by SaintPeter** [comment]
@ribeirojpn It looks like you may have the same issue I had - you're doing a bare pull against your upstream/staging.  This may not be easily fixable without deleting your local fork.

You can use this command:
`git pull --rebase upstream staging` 
to update your local fork without generating an extra commit.

More details here:
https://github.com/FreeCodeCamp/FreeCodeCamp/wiki/git-rebase#git-rebase-at-fcc

**Comment by ribeirojpn** [comment]
@BerkeleyTrue of course, I see how to do it. after do, i send a new Pull Request right?

@SaintPeter thanks man!

**Comment by SaintPeter** [comment]
@ribeirojpn If you can rebase your existing branch to squash the commits, when you push it to your GitHub fork it should automatically update this PR.  Just ping us once that has happened.

**Comment by BerkeleyTrue** [comment]
I don't think he can use a rebase because of all the merges

**Comment by ribeirojpn** [comment]
I made a new Pull Request:  #4421

I had to make a re-fork.

**Pull request closed without merging**
