### PR TITLE
fix(curriculum):explained the border-box property

### LINKED ISSUE #49156: learn-the-css-box-model-by-building-a-rothko-painting challenge - missing information about different css box models
### Describe the Issue

https://www.freecodecamp.org/learn/2022/responsive-web-design/learn-the-css-box-model-by-building-a-rothko-painting/

Challenge called "Learn the **css box model** by..."
There are bunch of steps which describes some parts of the box model, a lot of steps about changing colors etc
But it looks like there is no step describing that there are different models available like content-box, border-box etc
And in the next project https://www.freecodecamp.org/learn/2022/responsive-web-design/learn-css-flexbox-by-building-a-photo-gallery/step-7 there is a phrase:

> Normalize your box model by creating a * selector and setting the box-sizing property to border-box as the value.

But there was no information before that about border-box and what is it and why we are setting it to border-box here

### Affected Page

https://www.freecodecamp.org/learn/2022/responsive-web-design/learn-the-css-box-model-by-building-a-rothko-painting/

### Steps to Reproduce

Just go through challenge

### Recommended fix or suggestions

It will great if "Learn the css box model" project will include information about different box-sizing values 

### Screenshots

_No response_

### PR DESCRIPTION
**Pull request by Dikshantw**
Checklist:

- [x] I have read and followed the [contribution guidelines](https://contribute.freecodecamp.org).
- [x] I have read and followed the [how to open a pull request guide](https://contribute.freecodecamp.org/#/how-to-open-a-pull-request).
- [x] My pull request targets the `main` branch of freeCodeCamp.
- [x] I have tested these changes either locally on my machine, or GitPod.

Closes #49156 

The issue was that in description not information about the border-box property. so, I added the necessary and compact information about the property.

### CODE REVIEW

**Comment by Sboonny** [comment]
As a new contributor, we encourage you to read our [contributing guidelines](https://contribute.freecodecamp.org).

We expect our contributors to be aware of the process specific to this project. Following the guidelines religiously earns you the respect of fellow maintainers and saves everyone time.

Some examples of this are:
<details>
<summary>Our expectation</summary>

1. Do not edit files directly through GitHub – while you can, it's not a good idea.
2. Make sure you follow the PR checklist and not just tick things off; otherwise, we won't take you seriously.
3. Use the correct way to link issues in the description of the PR by updating the `XXXXXX`. Do not just add issue numbers everywhere and anywhere you feel like.
4. Keep mentions and review requests to a minimum. We understand you are excited about contributing, and our maintainers will get back to you as soon as they get a chance.
5. Do not work directly off your `main` branch - create a new branch for the changes you are working on.

</details>

We appreciate you taking the time to help us, and we hope to see more contributions from you.

Happy Contributing.

**Comment by raisedadead** [comment]
Hi, 

We are closing this because we haven't heard from you. Thanks for your understanding. 

Happy contributing.

**Comment by Dikshantw** [comment]
Hello @raisedadead , 
Thank you for taking the time to review my pull request. I apologize for any confusion caused by my lack of communication. I was not aware that I needed to reach out to you to get the PR merged. I have reviewed the contributing guidelines ,and I want to assure you that I did not intend to neglect any necessary steps. Please let me know if there is anything further I can do to help with this PR.

**Comment by Sboonny** [comment]
@Dikshantw, I have added the block because of not linking the issue, which you have already did. Remove the mention of the issue in the PR title and it's all good 👍. I have pushed your PR to draft, because the current change doesn't fix the issue

About the issue itself, to solve it you need to add step describe `box-sizing` and its properties as mentioned here https://github.com/freeCodeCamp/freeCodeCamp/issues/49156#issuecomment-1450353254, you can do this by using the challenge-editor.

run `pnpm run challenge-editor` in the root directory, or use the script commands mentioned in this section https://contribute.freecodecamp.org/#/how-to-work-on-practice-projects?id=step-tools

if you need help join us in [our discord](https://discord.gg/PRyKn3Vbay) or [the forum](https://forum.freecodecamp.org/c/contributors/3) if you need help contributing, our prolific contributors will guide you through this.

Good luck and happy coding

**Comment by raisedadead** [comment]
Hi, 

We are closing old issues/pull requests that we think are stale. If you still need help or are fixing this, please open a new issue/pull request.

Thanks for your understanding. 

Happy contributing.

**Pull request closed without merging**
