### PR TITLE
fix: simplify savedChallenges update

### LINKED ISSUE #46024: [DB Optimize] Simplify saveChallenges update
### Describe the Issue

The entire savedChallenges array is being rewritten any time a savedChallenge is written/updated/etc.

### Expected behavior

We should only update the savedChallenge that needs updating, not the whole array

### Additional context

Oliver already did this to [the completedChallenges array here](https://github.com/freeCodeCamp/freeCodeCamp/pull/45862), so we can use that as a template.

The [code that needs updating is here.](https://github.com/freeCodeCamp/freeCodeCamp/blob/main/api-server/src/server/boot/challenge.js#L104) That function is used in two spots, so we need to make sure changes work in both areas.

### PR DESCRIPTION
**Pull request by moT01**
Give this a good review - I finished up kind of late.

I focused on the database writes, I didn't want to mess with the request responses or anything on the client - so there may be some questionable looking code.

It appears that this and Oliver's PR make it so the database doesn't write all that extra "stuff". That seems to be the case anyway - so that's good. Don't know why.

- [x] I have read [freeCodeCamp's contribution guidelines](https://contribute.freecodecamp.org).
- [x] My pull request has a descriptive title (not a vague title like `Update index.md`)
- [x] My pull request targets the `main` branch of freeCodeCamp.
- [x] I have tested these changes either locally on my machine, or GitPod.

Closes #46024

### CODE REVIEW

**Review by ojeytonwilliams — APPROVED** [review]
LGTM :+1: 

Nice work, @moT01

**Comment by ojeytonwilliams** [comment]
> It appears that this and Oliver's PR make it so the database doesn't write all that extra "stuff". That seems to be the case anyway - so that's good. Don't know why.

:magic_wand:

**Comment by Sboonny** [comment]
> I finished up kind of late.

and here I am with coffee in hand, still couldn't do it. Good job, I learned a lot from this PR and Oliver's PR.

**Review by scissorsneedfoodtoo — APPROVED** [review]
Awesome, this looks great @moT01.

Tested this locally with the new RWD projects and this does seem to fix the problem of saving all that extra stuff to the db.

Will leave this open in case anyone else wants to take a look before merging. Otherwise I think it should be good to go.

**Pull request merged**
