### PR TITLE
fix(api): return early from `/get-session-user`

### PR DESCRIPTION
**Pull request by ShaunSHamilton**
If `req.user.username` does NOT exist, return

Checklist:

- [x] I have read and followed the [contribution guidelines](https://contribute.freecodecamp.org).
- [x] I have read and followed the [how to open a pull request guide](https://contribute.freecodecamp.org/#/how-to-open-a-pull-request).
- [x] My pull request targets the `main` branch of freeCodeCamp.
- [x] I have tested these changes either locally on my machine, or GitPod.

I am not sure the `.toJSON` call is necessary, but that is Loopback for you 🤷‍♂️

### CODE REVIEW

**Review by raisedadead — COMMENTED** [review]
Thanks for the quick analysis and fix –- do we know the source of this call in the client?

That is which logic could mean sending a request to the endpoint without a username?

**Comment by ShaunSHamilton** [comment]
> That is which logic could mean sending a request to the endpoint without a username?

I have not dug into this much, but this does not look like a client problem. The client makes a `fetch('/user/get-session-user', {credentials: 'include'});`. As far as I understand, the `username` is derived by: `client -> access_token -> api -> _id -> mongodb -> username`

This is more of a patch for our Sentry limits. I suspect our "fix" is located in `server/middlewares/request-authorization.js`

**Comment by ShaunSHamilton** [comment]
> @ShaunSHamilton did you have any luck recreating the bug locally?

No. Closest I got was setting the `username` to `""`.

**Review by naomi-lgbt — APPROVED** [review]
Do we still want to get this in?

**Comment by ShaunSHamilton** [comment]
Closing in favour of: https://github.com/freeCodeCamp/freeCodeCamp/pull/49386

**Pull request closed without merging**
