### PR TITLE
Added Bio from GitHub to freecodecamp portfolios

### LINKED ISSUE #8943: Add bio to Free Code Camp portfolios
GitHub recently introduced a bio field. We should also pull this from GitHub and store it on each user's object the same way we pull their name and location from GitHub. 

- [x] Update user schema to store bio
- [x] Update GitHub auth logic to request and store bio
- [x] Update code portfolio view to display bio if present

For reference, here's my public info: (https://api.github.com/users/quincylarson). You can see the new attribute is simply "bio":

```
{
  "login": "QuincyLarson",
  "id": 985197,
  "avatar_url": "https://avatars.githubusercontent.com/u/985197?v=3",
  "gravatar_id": "",
  "url": "https://api.github.com/users/QuincyLarson",
  "html_url": "https://github.com/QuincyLarson",
  "followers_url": "https://api.github.com/users/QuincyLarson/followers",
  "following_url": "https://api.github.com/users/QuincyLarson/following{/other_user}",
  "gists_url": "https://api.github.com/users/QuincyLarson/gists{/gist_id}",
  "starred_url": "https://api.github.com/users/QuincyLarson/starred{/owner}{/repo}",
  "subscriptions_url": "https://api.github.com/users/QuincyLarson/subscriptions",
  "organizations_url": "https://api.github.com/users/QuincyLarson/orgs",
  "repos_url": "https://api.github.com/users/QuincyLarson/repos",
  "events_url": "https://api.github.com/users/QuincyLarson/events{/privacy}",
  "received_events_url": "https://api.github.com/users/QuincyLarson/received_events",
  "type": "User",
  "site_admin": false,
  "name": "Quincy Larson",
  "company": "Free Code Camp",
  "blog": "http://www.FreeCodeCamp.com",
  "location": "San Francisco, California, US",
  "email": null,
  "hireable": null,
  "bio": "I'm a teacher at Free Code Camp. I write articles about technology at medium.com/@quincylarson and quora.com/profile/Quincy-Larson",
  "public_repos": 22,
  "public_gists": 38,
  "followers": 932,
  "following": 13,
  "created_at": "2011-08-17T04:08:08Z",
  "updated_at": "2016-06-03T21:48:07Z"
}
```

### PR DESCRIPTION
**Pull request by ghost**
#### Pre-Submission Checklist
- [x] Your pull request targets the `staging` branch of FreeCodeCamp.
- [x] Branch starts with either `fix/`, `feature/`, or `translate/`.
- [x] You have only one commit (if not, [squash](https://github.com/FreeCodeCamp/FreeCodeCamp/wiki/git-rebase#squashing-multiple-commits-into-one) them into one commit).
- [x] All new and existing tests pass the command `npm run test-challenges`.
#### Type of Change
- [x] New feature (non-breaking change which adds new functionality)
#### Checklist:
- [x] Tested changes locally.
- [x] Closes currently open issue: Closes #8943
#### Description

screenshot of what the bio looks like in portfolio

The design of the bio will probably change once #5667 is implemented, so there's no point trying anything fancy at this point.

### CODE REVIEW

**Comment by Bouncey** [comment]
Would love to test. Any clues on how to sign up on a local instance? I'm just getting a 500 or 404 depending on which method I try to use

**Comment by atjonathan** [comment]
@Bouncey you will need to create a github application and stick the credentials in `.env` :wink:

**Comment by Bouncey** [comment]
What happens if there is no bio to pull from GitHub?

**Comment by atjonathan** [comment]
@Bouncey, nothing will be displayed. Try it yourself. Temporarily remove your bio from Github, update your portfolio, and see what happens :wink:

**Comment by Bouncey** [comment]
LGTM :tada:

**Pull request merged**
