### PR TITLE
Updated sort challenge to be more clear

### PR DESCRIPTION
**Pull request by wildefires**
Sort challenge didn't actually tell you how the callback function should work - it just told you that it should be there. This adds a line to tell you how it works.

The line might be a bit long - maybe we should split it into a bulleted list? Something like:

"
The function should return:
- A negative number...
- A positive number...
- 0
  "

### CODE REVIEW

**Comment by SaintPeter** [comment]
This looks like a pretty good change, but I would do the following:
> The compare function ~~that you pass~~ should return a negative number if <code>a</code> should be before <code>b</code>, a positive number if <code>a</code> should be **after** <code>b</code>, or <code>0</code> if they ~~should be sorted as~~ are equal

Be sure to use `git commit --amend` when you make this change so you only have one commit.

**Comment by curioussavage** [comment]
:+1:  Nice and clear.

**Comment by bugron** [comment]
@Cull-Methi, please, next time follow the instructions from [**Guidelines for Contributing**](https://github.com/FreeCodeCamp/FreeCodeCamp/blob/staging/CONTRIBUTING.md), always create a new branch for a particular PR and name it like `fix/something` (if you're fixing some issue) or `feature/some-new-feature` (if you're adding a new feature). Thanks in advance.

**Comment by BerkeleyTrue** [comment]
@SaintPeter is this still blocked?

**Comment by SaintPeter** [comment]
Yes, the requested changes have not been made yet.

**Comment by BerkeleyTrue** [comment]
@Cull-Methi Please make the required changes

**Comment by SaintPeter** [comment]
@Cull-Methi - At this point you may be getting into exciting territory.  It is almost impossible to recover from this point, I can tell you from personal experience.

Save off your changes/edits to somewhere.  Delete your fork and re-fork.

When making edits, always create a branch off the latest version of staging.
To keep staging current, read here:
https://github.com/FreeCodeCamp/FreeCodeCamp/wiki/git-rebase#git-rebase-at-fcc

I'll see if I can't write up a guide or something, because this is a common problem.

**Pull request closed without merging**
