### PR TITLE
Use the correct element name in <code> blocks, gloss it seperately

### PR DESCRIPTION
**Pull request by jean**
If you write "`anchor` element" instead of "`a` element", you should also write "`hyperreference` attribute", instead of "`href` attribute".
Suggestion: write "`a` (_anchor_) element", or "anchor (`a`) element", to communicate the element name explicitly and gloss it at the same time.
The `<code>` sections should be valid code as far as possible.

- [x] I have read [freeCodeCamp's contribution guidelines](https://github.com/freeCodeCamp/freeCodeCamp/blob/master/CONTRIBUTING.md).
- [x] My pull request has a descriptive title (not a vague title like `Update index.md`)
- [x] My pull request targets the `master` branch of freeCodeCamp.
- [x] None of my changes are plagiarized from another source without proper attribution.
- [x] All the files I changed are in the same world language (for example: only English changes, or only Chinese changes, etc.)
- [x] My changes do not use shortened URLs or affiliate links.

Closes #XXXXX

### CODE REVIEW

**Review by thecodingaviator — DISMISSED** [review]
LGTM! 👍

**Comment by RandellDawson** [comment]
@jean The typical reason `anchor` element is used is to avoid having to write something like "Create an a element...", which at first looks like incorrect grammar (a and an are both articles).  That could be confusing to a reader.  Nobody uses "hyperreference attribute", because "http attribute" can not be confused with another word.  That being said, if others think this is a useful change, then don't let my opinion prevent the change.  Just keep in mind there are many challenges where the `anchor` is referenced.  Should they all be changed to `a`?  

**Note:** This really should have been brought up in an issue first, so we could discuss the broad ranging implications of the change, instead of discussing it on pull request for a single challenge.

**Comment by jean** [comment]
> "Create an a element...", which at first looks like incorrect grammar (a and an are both articles)

- The incorrect grammar is the cue that this is not the correct reading; i.e. it's self-correcting. Even if the reader goes with the wrong reading at first, the sentence is meaningless (what element? any element?), again prompting re-reading. 
- It would be "Create an `a` element...", i.e. the `a` would be clearly marked up as code. 

> Nobody uses "hyperreference attribute", because "~~http~~`href` attribute" can not be confused with another word. 

I don't think `anchor` is being used to distinguish it from the article a. I think it's being used to clarify that the `a` tag signifies an _anchor_. I.e. it's a gloss that abuses code markup. 

> Just keep in mind there are many challenges where the `anchor` is referenced. Should they all be changed to `a`?

I would certainly argue so. If others are in agreement, I'm prepared to add those changes to this PR. 

> This really should have been brought up in an issue first, so we could discuss the broad ranging implications of the change, 

Ah, sorry, I opened the PR as a starting point for discussion tied to a concrete example of the proposed change. I tend to think of PRs as issues with code attached, but you're right, github's UI segregates them. 

Thanks for considering my proposal :-)

**Comment by jean** [comment]
@thecodingaviator just curious, do you know why the `.md` challenge files would use `<i>html</i>` instead of `_markdown_`?

**Comment by thecodingaviator** [comment]
@jean I’m not sure why that happens but afaik, the markdown syntax does not work in the /curriculum files the same way it does in the /guide files

**Comment by Manish-Giri** [comment]
I think this change isn't required. `anchor` is used interchangeably with `a` element in many places, including [MDN](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/a). 

Additionally - 

> Create an `a` element

Non native english speakers might find this hard to understand at first glance. Unless the existing instructions are incorrect, we should try to keep things as simple as possible.

Thanks for creating the PR, btw!

**Comment by jean** [comment]
> `anchor` is used interchangeably with `a` element in many places, including [MDN](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/a).

On the contrary --- the MDN example illustrates exactly what I am advocating: the `<a>` element is marked up using `<code></code>`, and the gloss gets `<em></em>`:

    The <strong>HTML <code>&lt;a&gt;</code> element</strong> (or <em>anchor</em> element) creates a hyperlink [...]

Anchor is nowhere marked up as code. Regarding the readability argument, I see MDN does have an example of that usage:

> A skip link, also known as skipnav, is an `a` element

I disagree that in the context of HTML documentation it is confusing, due to the explicit code markup. It's certainly less confusing than "_A skip link, also known as skipnav, is an `anchor` element (but remember to write `a`, not `anchor`)_". Marking up `anchor` as code is simply never correct.

**Comment by thecodingaviator** [comment]
We'll need more discussion on this issue

**Comment by ojeytonwilliams** [comment]
This looks like a reasonable change to me.  I agree with @jean that we shouldn't be implying that anchor is a valid html tag.

As far as legibility goes, if we reckon 
> Create an `a` element

could be confusing, we could go with
> Create an `<a>` element

**Review by moT01 — DISMISSED** [review]
Thanks for the PR @jean! try a more descriptive branch name in the future. This LGTM, I don't think the `a` needs to be wrapped in `<>` - I don't see elements wrapped with those in any of the other challenges (that I checked), so I think it should stay like this for consistency. This should make it clear enough for campers. If you're satisfied @thecodingaviator, I think this can be merged.

For reference - a picture of what this looks like deployed:
Screen Shot 2019-03-20 at 8 00 14 AM

**Comment by jean** [comment]
Cool :-) I'll look for other occurrences of `anchor` and push to this PR.

**Review by lynxlynxlynx — APPROVED** [review]

**Comment by thecodingaviator** [comment]
@moT01 This looks good to me, I'm waiting for a go ahead from @jean when they're done with the other occurrences

**Comment by jean** [comment]
@thecodingaviator I think I got them all. 

I noticed there are some discrepancies in markup, e.g. sometimes "anchor text" is marked up as code, and sometimes it isn't, and often "anchor tag" is used without any markup. I think these are minor style issues, so I'm leaving them alone.

**Comment by thecodingaviator** [comment]
The change you have made at https://github.com/freeCodeCamp/freeCodeCamp/pull/35616/files#diff-b17a1aeb668293733b6e42c313bd9fe4R20 has not been made in any of the other languages as far as I see. Please check

**Comment by moT01** [comment]
PR's are supposed to stick to one language, so I think this should stick to english - the word "anchor" would not translate to "anchor" in other languages. Not sure if we want it translated or not, but I have no idea how it reads in the other languages. If you want to leave it and see if someone else approves it like this, that's fine - but I can't approve it anymore.

**Comment by thecodingaviator** [comment]
@jean Split this PR into different for each language, without that you're violating this point you checked:
image

**Comment by jean** [comment]
@thecodingaviator oh, sorry, yes I'll split languages!

Re: [this change](https://github.com/freeCodeCamp/freeCodeCamp/pull/35616/files#diff-b17a1aeb668293733b6e42c313bd9fe4R20), yes, I was starting to change `<code>anchor text</code>` to `<i>anchor text</i>`, because it signifies descriptive text, not markup. But then I wavered, thinking that (in some cases, not everywhere) it also signifies something that the user is editing as part of the page they're writing, i.e. it will be part of their code. I didn't change it back, because I noticed that "anchor text" is not consistently marked up as code .. e.g. [here](https://github.com/freeCodeCamp/freeCodeCamp/blob/79d90124320cdb83086e558dc6fe00f9ae51a45c/curriculum/challenges/english/01-responsive-web-design/basic-html-and-html5/link-to-external-pages-with-anchor-elements.english.md#L11), [here](https://github.com/freeCodeCamp/freeCodeCamp/blob/02a20f4a62159eb458bfc4a5bdf8b2c7513972a2/curriculum/challenges/english/01-responsive-web-design/basic-html-and-html5/nest-an-anchor-element-within-a-paragraph.english.md#L33), [here](https://github.com/freeCodeCamp/freeCodeCamp/blob/2ca3a2093fb9359483442e0fadeda1ea0fefff86/curriculum/challenges/chinese/01-responsive-web-design/basic-html-and-html5/nest-an-anchor-element-within-a-paragraph.chinese.md#L23), and other places it isn't marked up at all. It would make sense to think this through and make it consistent, but not in this PR. I wouldn't mind changing this occurrence back to `<code>anchor text</code>`. 

@moT01 

> the word "anchor" would not translate to "anchor" in other languages

Well, it's an English word included in the other languages, to show that the `a` tag comes from the English word "_anchor_". It may well be translated elsewhere in the text, but I do think that changing e.g. `<code>anchor</code>` to `<code>a</code> (<i>anchor</i>)` in all languages is fine. What do others think here?

**Comment by moT01** [comment]
"anchor" only didn't get translated to other languages where it was wrapped in the `code` tags. The `code` tag is supposed to represent code which can only be done exactly one way so it doesn't get translated. But anchor should be translated since it is not code, take a look at [this challenge](https://learn.freecodecamp.org/responsive-web-design/basic-html-and-html5/nest-an-anchor-element-within-a-paragraph) - the word "anchor" is in the description several times with and without the code tags.
[Here's the spanish translation of that file](https://github.com/freeCodeCamp/freeCodeCamp/blob/master/curriculum/challenges/spanish/01-responsive-web-design/basic-html-and-html5/nest-an-anchor-element-within-a-paragraph.spanish.md)
Anywhere the code tags weren't used, it got translated.
This is what I think anyway

**Comment by thecodingaviator** [comment]
@jean , I'm getting 5 occurrences:
image

Check which one this PR is missing, I see only 4 files

**Comment by jean** [comment]
@moT01 

> "anchor" only didn't get translated to other languages where it was wrapped in the `code` tags. The `code` tag is supposed to represent code which can only be done exactly one way so it doesn't get translated.

Correct, but this is an interesting case. The original `<code>anchor</code>` tried to do two things at the same time: 1. represent the code, 2. explain that the arbitrary `a` symbol actually comes from and is pronounced as the English word `anchor`. Including the English word at that point is the most obvious way to communicate this. This is quite separate from any other translations of _anchor_ in the text. If you want to discard the gloss, then `<i>anchor</i>` can go. But I don't really see how that improves things. 

@thecodingaviator in [`add-document-elements-with-d3.english.md#L12`](https://github.com/freeCodeCamp/freeCodeCamp/blame/master/curriculum/challenges/english/04-data-visualization/data-visualization-with-d3/add-document-elements-with-d3.english.md#L12) `<code>anchor</code>` refers to a javascript variable named `anchor`, not to an anchor tag.

**Comment by jean** [comment]
@moT01 

> The stuff in quotes did get translated and that would make it tough to pass the test

Yeah, 
_l nuevo párrafo debe tener un texto que diga &quot;Ver más **fotos de gatos**&quot;,_ vs 
_"Your <code>a</code> element should have the anchor text of "**cat photos**""_
right?

That should be a new issue though.

**Review by moT01 — APPROVED** [review]
LGTM @jean, congratulations on your first contribution to freeCodeCamp! 🎊 - There's tons to help with around here if you're interested, all help is welcome. Thanks and happy coding!

**Comment by jean** [comment]
@moT01 awesome, thank you very much :grinning:

**Pull request merged**
