### PR TITLE
chore(i18n,curriculum): processed translations

### PR DESCRIPTION
**Pull request by camperbot**
This PR was opened auto-magically by Crowdin.

### CODE REVIEW

**Review by naomi-lgbt — APPROVED** [review]

**Comment by nhcarrigan** [comment]
@ojeytonwilliams if you'd like to approve this, then we will be all set for deployment I think.

**Review by ojeytonwilliams — APPROVED** [review]
LGTM 👍

**Comment by ojeytonwilliams** [comment]
@nhcarrigan I think that brings the Spanish to 100%, but we're still waiting for the final Chinese translations and Miya's go-ahead.

**Comment by nhcarrigan** [comment]
No worries - I think Mrugesh is out for the night so likely won't be deploying until tomorrow.

**Comment by raisedadead** [comment]
She did mention that they will get around to completing the translations tomorrow and in any case it's non-blocking for deployment.

Will push a build to staging when I am up (for preliminary testing and checks). Should give them the day in case they get the changes done. We deploy in evening my time.

**Comment by ojeytonwilliams** [comment]
Wasn't the plan to only deploy once all the challenges are translated?

**Pull request merged**
