### PR TITLE
Fix text inconsistency

### PR DESCRIPTION
**Pull request by zbianca**
Fix text to match what was said on the previous paragraph.

Checklist:

- [x] I have read [freeCodeCamp's contribution guidelines](https://contribute.freecodecamp.org).
- [x] My pull request has a descriptive title (not a vague title like `Update index.md`)
- [x] My pull request targets the `master` branch of freeCodeCamp.
- [x] All the files I changed are in the same world language, for example: only English changes, or only Chinese changes, etc.

Closes #XXXXX

I've only fixed the inconsistency to the previous paragraph. I'd suggest that for such an introductory lesson, listing the primitive data types instead of all the Language Types (https://tc39.es/ecma262/#sec-ecmascript-data-types-and-values) is less overwhelming.

### CODE REVIEW

**Comment by RandellDawson** [comment]
@zbianca Thanks for catching `seven` vs. the correct `eight`.  Regarding your suggestion, you can create an issue on GitHub and present your ideas on changing the challenge description.

**Review by PeterF521 — DISMISSED** [review]
Nice!

**Review by raisedadead — DISMISSED** [review]

**Comment by RandellDawson** [comment]
@raisedadead Seems to be stuck at the Travis build stage.

**Review by moT01 — DISMISSED** [review]
Not sure what the deal with travis is, just gets stuck sometimes. I think we're fine on this one since it's a one word change.

**Comment by ojeytonwilliams** [comment]
It looks like Travis completes the run and then doesn't report back to GitHub, but I have no idea why.  [This](https://travis-ci.com/github/freeCodeCamp/freeCodeCamp/jobs/358618428) is the original job, which GitHub thinks has stalled, but Travis is reporting as a success.

Also, it should be enough to press the 'restart job' button on Travis - force pushing feels like overkill.

**Review by ojeytonwilliams — APPROVED** [review]
LGTM :+1:

**Comment by ojeytonwilliams** [comment]
Thanks for sorting this out @zbianca and congrats on your first merged PR!

**Pull request merged**
