### PR TITLE
fix(curriculum): remove setup code not needed anymore from Testing Objects for Properties challenge

### PR DESCRIPTION
**Pull request by RandellDawson**
Checklist:

- [x] I have read [freeCodeCamp's contribution guidelines](https://github.com/freeCodeCamp/freeCodeCamp/blob/master/CONTRIBUTING.md).
- [x] My pull request has a descriptive title (not a vague title like `Update index.md`)
- [x] My pull request targets the `master` branch of freeCodeCamp.
- [x] All the files I changed are in the same world language, for example: only English changes, or only Chinese changes, etc.

Due to the confusion discussed in [this forum thread](https://www.freecodecamp.org/forum/t/testing-object-for-properties-exercise-2020/364001) this PR removes the setup code from the seed code and solution that is no longer relevant due to changes in a [recently merged PR](https://github.com/freeCodeCamp/freeCodeCamp/pull/38414).

### CODE REVIEW

**Review by hassaanp — APPROVED** [review]

**Review by Manish-Giri — APPROVED** [review]

**Review by ojeytonwilliams — CHANGES_REQUESTED** [review]
Without `myObj`, `checkObj` on line 61 needs to either be removed or have an object literal passed in directly.

**Comment by RandellDawson** [comment]
@ojeytonwilliams Look at the `testString`s.  The function is called with an object and a property name.

**Comment by RandellDawson** [comment]
@ojeytonwilliams OK @ojeytonwilliams I removed the call which had `myObj` in it.  Thanks for catching that.

**Review by ojeytonwilliams — APPROVED** [review]
LGTM :+1:

**Pull request merged**
