### PR TITLE
chore: rename "part" to "step"

### PR DESCRIPTION
**Pull request by naomi-lgbt**
Checklist:

- [X] I have read [freeCodeCamp's contribution guidelines](https://contribute.freecodecamp.org).
- [X] My pull request has a descriptive title (not a vague title like `Update index.md`)
- [X] My pull request targets the `main` branch of freeCodeCamp.
- [ ] I have tested these changes either locally on my machine, or GitPod.

Closes #XXXXX

GitHub is likely to struggle with this one...

- Rename all the step files to use `step` instead of `part`
- Update the `meta.json` files
- Update the project tooling to use `step`.

A note for existing PRs that are using `part` files:

If you are on a UNIX system, `cd` into the project directory, run `rename 's/part/step/' *` to rename the files, and `git add --all .` to stage them as renames instead of addition/deletions.

### CODE REVIEW

**Review by ojeytonwilliams — DISMISSED** [review]
LGTM 👍

**Review by ojeytonwilliams — DISMISSED** [review]

**Review by ojeytonwilliams — APPROVED** [review]
Oops, didn't see the CI failing.

Btw, I'm pretty confident that if the CI passes, we're good.  Any other problems are almost certainly just dev-facing.

**Review by ejcheng — APPROVED** [review]
LGTM!
Just for curiosity's sake, how did you do this? Regex wizardry?

**Review by ShaunSHamilton — APPROVED** [review]

**Review by moT01 — APPROVED** [review]
LGTM 🎉 

> Some languages (POR and ITA) have the d3-dashboard project which still uses part-XXX. However, other languages do not even have this project.

Looks like Portuguese has the JavaScript projects as well. I'm guessing they were uploaded and download from crowdin before we started ignoring these. Is the plan to stop ignoring them at some point after we release or what?

**Comment by nhcarrigan** [comment]
The v8 projects aren't on Crowdin, so most likely another error when moving the initial English files over to allow a build to complete. Will PR to remove those separately.

**Pull request merged**
