### PR TITLE
Don't translate tooltip or callback, fix voice in add-a-tooltip-to-a-d3-element.spanish.md

### PR DESCRIPTION
**Pull request by azuzunaga**
Tooltip and callback are common enough in spanish web development
vocabulary that translating them causes more confucion. Additionally,
most web resources are still in English, and ambiguous translations
(i.e. retrollamada o devolucion de llamada for callback) could make
finding the right information more difficult.

- [x] I have read [freeCodeCamp's contribution guidelines](https://github.com/freeCodeCamp/freeCodeCamp/blob/master/CONTRIBUTING.md).
- [x] My pull request has a descriptive title (not a vague title like `Update index.md`)
- [x] My pull request targets the `master` branch of freeCodeCamp.
- [x] None of my changes are plagiarized from another source without proper attribution.
- [x] All the files I changed are in the same world language (for example: only English changes, or only Chinese changes, etc.)
- [x] My changes do not use shortened URLs or affiliate links.

Closes #XXXXX

### CODE REVIEW

**Comment by lynxlynxlynx** [comment]
Does this tooltip&callback problem come up in any other challenge?

**Comment by azuzunaga** [comment]
It does, tooltip comes up in 6 files in total and callback comes up on 39 files.

I can amend this PR to change all occurrences or create a new PR to specifically address those. I would like to still fix the passive voice in this particular article though (I am sure there are many many articles where that can be fixed too).

**Comment by thecodingaviator** [comment]
@azuzunaga please make changes to all occurrences in this PR. Thanks

**Comment by azuzunaga** [comment]
Will do.

**Comment by azuzunaga** [comment]
All set @thecodingaviator.

**Comment by RandellDawson** [comment]
@azuzunaga Thank you for  creating this PR.  However, since it was created, the underlying documents have changed.  Can you please review and resolve the current merge conflicts?  It could be the changes to the underlying documents are so significant that your changes are no longer relevant.  If the latter is the case, it might be easier to just close this PR and create a new PR with any changes you still feel are important to make.

If you need any assistance or have questions about resolving the merge conflicts, please reply back or contact someone in the [Contributors Room on Gitter](https://gitter.im/FreeCodeCamp/Contributors).

Thank you

**Comment by azuzunaga** [comment]
Thanks @RandellDawson. I think it will be easier to close this PR and open a new one.

**Comment by RandellDawson** [comment]
Make sure to resync your forked master branch to freecodecamp's master branch, because you soiled your master branch when you committed directly to it instead of creating a new branch from the unsoiled master.

**Pull request closed without merging**
