### PR TITLE
Fix: Code example and translation

### PR DESCRIPTION
**Pull request by ricardotenorio**
- [x] I have read [freeCodeCamp's contribution guidelines](https://github.com/freeCodeCamp/freeCodeCamp/blob/master/CONTRIBUTING.md).
- [x] My pull request has a descriptive title (not a vague title like `Update index.md`)
- [x] My pull request targets the `master` branch of freeCodeCamp.
- [x] None of my changes are plagiarized from another source without proper attribution.
- [x] My article does not contain shortened URLs or affiliate links.

If your pull request closes a GitHub issue, replace the XXXXX below with the issue number.

Closes #XXXXX

### CODE REVIEW

**Comment by RandellDawson** [comment]
Closed and Reopened this PR to attempt to resolve a specific Travis build failure.

**Review by thecodingaviator — CHANGES_REQUESTED** [review]
I would ask you to remove the 
```java
// Variável para definir o tipo de motor usado 
  private Motor motor;
```
part because you are not importing the Motor class anywhere and it's not a library class, neither have you made the class in your example

**Review by thecodingaviator — CHANGES_REQUESTED** [review]
I'd also want you to fix the formatting over here:
image

Bring the line out of the code block

**Review by thecodingaviator — CHANGES_REQUESTED** [review]
Also, you need to change the constructor syntax to reflect properly, the correct syntax is:
```java
ClassName object1 = new ClassName();
```
WITHOUT a space. Please fix that everywhere too.

**Review by Manish-Giri — APPROVED** [review]
Hi @ricardotenorio 

Congrats on your first pull request (PR)! 🎉

Thank you for your contribution to the page! 👍 We're happy to accept these changes and look forward to future contributions. 📝

**Pull request merged**
