### PR TITLE
Fix(curriculum): pyramid step43 update tests & clarify instruction

### LINKED ISSUE #55646: Pyramid Proj (JS Beta) - Step 43 Semi-colon check too sensitive
### Describe the Issue

A camper reported that in Step 43, if they add a semicolon one space to the right of the last word row on the result assignment statement, the test fails. But if the semi-colon is to the immediate right of the row variable, the test passes.
This seems like a too sensitive coding check given that most steps ignore missing semi-colons and also given that the space to the immediate left of the semi-colon is not causing a syntax error that we know of.

### Affected Page

https://www.freecodecamp.org/learn/javascript-algorithms-and-data-structures-v8/learn-introductory-javascript-by-building-a-pyramid-generator/step-43

### Your code

```
for (const row of rows) {
  result = result + "\n" + row ;
}
```

### Expected behavior

If other steps' tests allow campers to submit code without semi-colons, then a valid (if ugly) submission with a semi-colon displaced some space(s) to the right of the statement seems equally valid and should be accepted.

### Screenshots

_No response_

### System

N/A

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by hbar1st**
Checklist:

- [x] I have read and followed the [contribution guidelines](https://contribute.freecodecamp.org).
- [x] I have read and followed the [how to open a pull request guide](https://contribute.freecodecamp.org/how-to-open-a-pull-request/).
- [x] My pull request targets the `main` branch of freeCodeCamp.
- [x] I have tested these changes either locally on my machine, or GitPod.

Closes #55646

To fix the issue, I replaced the regex check with a check for the value in the result variable.

### CODE REVIEW

**Comment by codewitharun** [comment]
This is not related to semicolon ; there is need to re-ask question in different way as example and question asked is looking like it is asking to
` result = result + “\n” + row;
` 
but it should ask to add in last to go to the next line 

`result = result + row + "\n";
`

**Comment by lasjorg** [comment]
The test works.

I might however suggest we change the requirement slightly. Maybe something like?

> Use a second addition operator to append a new line after the `result` and `row` values.

**Comment by hbar1st** [comment]
Is it something that should be done in a separate issue or PR? (The original issue was about fixing the checks to allow people to not have to type in a semicolon)

**Comment by ilenia-magoni** [comment]
you can add it to this PR, it's all bettering the same step. You can change the title if needed

**Review by majestic-owl448 — APPROVED** [review]

**Review by lasjorg — APPROVED** [review]

**Pull request merged**
