### PR TITLE
Fixed bug: The text is hidden for non selected tab #51958

### PR DESCRIPTION
**Pull request by mughalmuneeb786**
Fixed bug: The text is hidden for non selected tab 
#51958

### CODE REVIEW

**Comment by jeremylt** [comment]
You deleted template content that comes when you create a PR. Please put it back! Its in the template because it is important to us.

**Comment by jeremylt** [comment]
Also, this issue has not been triaged and marked as ready for contributions. Please read our contributing guidelines.
https://contribute.freecodecamp.org/

**Comment by mughalmuneeb786** [comment]
> Also, this issue has not been triaged and marked as ready for contributions. Please read our contributing guidelines. https://contribute.freecodecamp.org/

Are you referring to Tests ? please explain ? 
https://contribute.freecodecamp.org/#/how-to-contribute-to-the-codebase?id=proposing-a-pull-request-pr

**Comment by jeremylt** [comment]
https://contribute.freecodecamp.org/#/FAQ?id=where-do-i-start-if-i-want-to-work-on-an-issue

**Comment by mughalmuneeb786** [comment]
> Also, this issue has not been triaged and marked as ready for contributions. Please read our contributing guidelines. https://contribute.freecodecamp.org/

Are you refering to Comment and Description Template used for PR ,.let me know will do it again or if this open PR i can't make any changes to this .

**Comment by jeremylt** [comment]
I meant all the template content that you deleted when you created the PR. There should be a checklist for you to complete.

**Comment by mughalmuneeb786** [comment]
> I meant all the template content that you deleted when you created the PR. There should be a checklist for you to complete.
> 
> But, again, this issue wasn't marked as ready for a contribution.

I have to make a new PR ? with new commit ?

**Comment by bbsmooth** [comment]
@mughalmuneeb786 Just don't do anything right now. It hasn't been officially decided on how we are going to fix this. I'm guessing we aren't going to use tabs any more and thus your proposed fix in this PR isn't even valid.

I know you are eager to contribute, but there is nothing to contribute at this point because a decision hasn't been made yet as to how to fix this.

**Comment by gikf** [comment]
Hey

Thank you for opening this pull request.

As there was different PR - #52018 - making all necessary changes, merged recently, we are going to close this one.

Thank you and happy coding! 😊

---

If you have any questions, feel free to ask questions on the ['Contributors' category on our forum](https://forum.freecodecamp.org/c/contributors) or [the contributors chat room](https://discord.gg/PRyKn3Vbay).

**Pull request closed without merging**
