### PR TITLE
chore: cache pnpm store

### PR DESCRIPTION
**Pull request by ojeytonwilliams**
Checklist:

- [x] I have read and followed the [contribution guidelines](https://contribute.freecodecamp.org).
- [x] I have read and followed the [how to open a pull request guide](https://contribute.freecodecamp.org/#/how-to-open-a-pull-request).
- [x] My pull request targets the `main` branch of freeCodeCamp.
- [x] I have tested these changes either locally on my machine, or GitPod.

This should shave a few minutes off CI, but we shall see.

### CODE REVIEW

**Review by raisedadead — APPROVED** [review]
This should not do anything significant. The "caching" takes effect within jobs (pnpm install across jobs in the same workflow).

To share across jobs you would need to use the dedicated `actions/cache` workflow.

**Comment by ojeytonwilliams** [comment]
actions/setup-node uses actions/cache under the hood: https://github.com/actions/setup-node#caching-global-packages-data

You can see that the cache is used here: https://github.com/freeCodeCamp/freeCodeCamp/actions/runs/4373459886/jobs/7651900278

It's a bit variable, but it looks like we're saving about a minute on each install step.

**Comment by ojeytonwilliams** [comment]
Right, but the process of building all the symlinks (i.e. populating node_modules) is pretty fast.  Setting up the store takes a little longer and that's where we get the savings.

It's not much, granted, but it is faster with caching.

**Review by ShaunSHamilton — APPROVED** [review]
💸

**Comment by raisedadead** [comment]
> It's not much, granted, but it is faster with caching.

What I am getting at is It would be faster if we used the underlying actions/cache for caching both the pnpm store and the `node_modules`.

**Comment by ojeytonwilliams** [comment]
Oh, right. That should be possible.

**Pull request merged**
