### PR TITLE
Replace example projects that don't fulfill all user stories

### LINKED ISSUE #6386: Replace challenge example apps that don't fulfill user stories
We need help going through the following challenges and testing their example apps to verify that they fulfill all of the challenge's user stories.

Note that we've done away with bonus user stories. Don't worry about the user stories show in the videos (I'm getting ready to re-record these videos anyway). 

If a challenge fails to deliver on a user story, find an example app that does. The easiest way to do this is to go to twitter and search "@freecodecamp" and you'll see thousands of tweets from campers, many of which include links to projects they've built. Or, if you've built your own implementation of this challenge already and it fulfills the user stories, you can just link to that.

Submit a pull request that updates these links. Then I will go through, fork them on CodePen, and link to our stable CodePen forks of these apps. 

Here are the challenges I haven't verified yet:

- [ ] http://www.freecodecamp.com/challenges/build-a-personal-portfolio-webpage
- [ ] http://www.freecodecamp.com/challenges/build-a-random-quote-machine
- [ ] http://www.freecodecamp.com/challenges/build-a-javascript-calculator
- [ ] http://www.freecodecamp.com/challenges/build-a-pomodoro-clock
- [ ] http://www.freecodecamp.com/challenges/show-the-local-weather
- [ ] http://www.freecodecamp.com/challenges/stylize-stories-on-camper-news
- [ ] http://www.freecodecamp.com/challenges/build-a-wikipedia-viewer
- [ ] http://www.freecodecamp.com/challenges/use-the-twitchtv-json-api
- [ ] http://www.freecodecamp.com/challenges/build-a-tic-tac-toe-game
- [ ] http://www.freecodecamp.com/challenges/build-a-simon-game
- [ ] http://www.freecodecamp.com/challenges/build-a-voting-app
- [ ] http://www.freecodecamp.com/challenges/build-a-nightlife-coordination-app
- [ ] http://www.freecodecamp.com/challenges/chart-the-stock-market
- [ ] http://www.freecodecamp.com/challenges/manage-a-book-trading-club
- [ ] http://www.freecodecamp.com/challenges/build-a-pinterest-clone

### PR DESCRIPTION
**Pull request by alistermada**
Example projects should now fulfill all the user stories.

| Project | Link to new example project |
| --- | --- |
| [Random Quote Machine](http://www.freecodecamp.com/challenges/build-a-random-quote-machine) | http://codepen.io/FreeCodeCamp/full/bELoPJ |
| [JavaScript Calculator](http://www.freecodecamp.com/challenges/build-a-javascript-calculator) | http://codepen.io/FreeCodeCamp/full/zrRzMR |
| [Local Weather App](http://www.freecodecamp.com/challenges/show-the-local-weather) | http://codepen.io/FreeCodeCamp/full/bELRjV |
| [Voting App](http://www.freecodecamp.com/challenges/build-a-voting-app) | https://fcc-voting-arthow4n.herokuapp.com/ |
| [Stock Market App](http://www.freecodecamp.com/challenges/chart-the-stock-market) | http://watchstocks.herokuapp.com/ |
| [Pinterest Clone](http://www.freecodecamp.com/challenges/build-a-pinterest-clone) | http://pintech.herokuapp.com/ |

Waiting on @QuincyLarson's approval
closes #6386

### CODE REVIEW

**Comment by QuincyLarson** [comment]
@alistermada Here's the forked pen: http://codepen.io/FreeCodeCamp/full/bELoPJ

Please update and I'll QA when I wake up in 8 hours.

**Comment by SaintPeter** [comment]
Oh no.  I'm an example.

**Comment by alistermada** [comment]
@QuincyLarson Updated.
@SaintPeter Too poll-tastic not to have as an example. Also, I've found bug where if you click on an option multiple times before the results are shown, you can add more votes to the count. That's how I have 7 votes on the poll I created.

Couldn't find another poll that allowed unauthorized users to vote (one of the user stories) that didn't have that bug.

**Comment by alistermada** [comment]
@QuincyLarson Found a voting app that doesn't require a login to vote and doesn't allow users (signed in or not) to vote twice: https://fcc-voting-arthow4n.herokuapp.com/. I've checked to make sure all user stories are fulfilled. I haven't found any major bugs.

**Comment by QuincyLarson** [comment]
@alistermada Thanks again for your fast help with this PR!

**Pull request merged**
