### PR TITLE
this pull request closes the issue #47738

### LINKED ISSUE #47738: Typos in challenges description
1. This sentence is missing a word
https://github.com/freeCodeCamp/freeCodeCamp/blob/762945baf260afde16f4fd5191ce50a1dc20e3cc/curriculum/challenges/english/15-javascript-algorithms-and-data-structures-22/learn-basic-javascript-by-building-a-role-playing-game/62aa2999ec27ec516655eba6.md?plain=1#L20

---

2. Here the word `gallery` should not have quotes inside the code block
https://github.com/freeCodeCamp/freeCodeCamp/blob/762945baf260afde16f4fd5191ce50a1dc20e3cc/curriculum/challenges/english/14-responsive-web-design-22/learn-css-flexbox-by-building-a-photo-gallery/61537c9eecea6a335db6da79.md?plain=1#L10

---

3. In this sentence
> The `"from"` array should contain the original names and the `"to"` array

`from` and `to` should not have quotations in the code block
https://github.com/freeCodeCamp/freeCodeCamp/blob/762945baf260afde16f4fd5191ce50a1dc20e3cc/curriculum/challenges/english/10-coding-interview-prep/rosetta-code/state-name-puzzle.md?plain=1#L18

### PR DESCRIPTION
**Pull request by getcoder-top**
Checklist:

- [x ] I have read [freeCodeCamp's contribution guidelines](https://contribute.freecodecamp.org).
- [x ] My pull request has a descriptive title (not a vague title like `Update index.md`)
- [x ] My pull request targets the `main` branch of freeCodeCamp.
- [x ] I have tested these changes either locally on my machine, or GitPod.

Closes #47738

### CODE REVIEW

**Comment by ieahleen** [comment]
As a new contributor, we encourage you to read our [contributing guidelines](https://contribute.freecodecamp.org).

We expect our contributors to be aware of the process specific to this project. Following the guidelines religiously earns you the respect of fellow maintainers and saves everyone time.

Some examples of this are:

1. Do not edit files directly through GitHub – while you can, it's not a good idea.
2. Make sure you follow the PR checklist and not just tick things off; otherwise, we won't take you seriously.
3. Use the correct way to link issues in the description of the PR by updating the `XXXXXX`. Do not just add issue numbers everywhere and anywhere you feel like.
4. Keep mentions and review requests to a minimum. We understand you are excited about contributing, and our maintainers will get back to you as soon as they get a chance.
5. Do not work directly off your `main` branch - create a new branch for the changes you are working on.

We appreciate you taking the time to help us, and we hope to see more contributions from you.

Happy Contributing.

**Comment by ieahleen** [comment]
If you need help, please reach out in the contributors chat room, keeping opening PRs without changing anything is not going to help.

**Comment by getcoder-top** [comment]
please review @raisedadead

**Comment by ieahleen** [comment]
For this PR to really close the issue it needs to include only changes related to that issue, you just added a commit for a different issue.

**Comment by jeremylt** [comment]
You are working on a 'dirty' main branch of your fork. This is the same problem you had with the last two nearly identical PRs you opened. I recommend you close this PR and look into how branches work.

**Comment by getcoder-top** [comment]
please review @raisedadead

**Comment by getcoder-top** [comment]
> For this PR to really close the issue it needs to include only changes related to that issue, you just added a commit for a different issue.

now it is related to the issue

**Comment by getcoder-top** [comment]
> You are working on a 'dirty' main branch of your fork. This is the same problem you had with the last two nearly identical PRs you opened. I recommend you close this PR and look into how branches work.

**Comment by naomi-lgbt** [comment]
As Ilenia mentioned:

> Keep mentions and review requests to a minimum. We understand you are excited about contributing, and our maintainers will get back to you as soon as they get a chance.

Please do not repeatedly ping our staff. Multiple members of our team have given you guidance on how to proceed with your contribution - ignoring that guidance and pinging other maintainers is rather impolite.

**Comment by getcoder-top** [comment]
> As Ilenia mentioned:
> 
> > Keep mentions and review requests to a minimum. We understand you are excited about contributing, and our maintainers will get back to you as soon as they get a chance.
> 
> Please do not repeatedly ping our staff. Multiple members of our team have given you guidance on how to proceed with your contribution - ignoring that guidance and pinging other maintainers is rather impolite.

now it will not happen

**Comment by ieahleen** [comment]
you have changes that are not related to the issue included in this PR.

Pinging `@raisedadead` multiple times is not going to change that, and it's pretty rude.

**Comment by jeremylt** [comment]
Yes, you have posted a screenshot of your 'dirty' main branch of your fork. This is making a messy PR because you have unrelated commits in your main branch. You need to re-sync your fork, create a branch off of the main branch of your fork, and then create commits that only apply to the issue you are trying to fix.

**Comment by getcoder-top** [comment]
now it is updated

**Comment by jeremylt** [comment]
No, it is not. Your main branch is still dirty. You have unrelated changes in this PR, and a merge conflict to boot.

Please do not create a PR from the main branch of your fork.

You need to

> You need to re-sync your fork, create a branch off of the main branch of your fork, and then create commits that only apply to the issue you are trying to fix.

**Pull request closed without merging**
