### PR TITLE
Python: Completed article Creating GUI's in Python 3

### PR DESCRIPTION
**Pull request by Moon4Light**
In this file I've completed the stub article which is about Creating GUI's in Python 3.

- [x] I have read [freeCodeCamp's contribution guidelines](https://github.com/freeCodeCamp/freeCodeCamp/blob/master/CONTRIBUTING.md).
- [x] My pull request has a descriptive title (not a vague title like `Update index.md`)
- [x] My pull request targets the `master` branch of freeCodeCamp.
- [x] None of my changes are plagiarized from another source without proper attribution.
- [x] My article does not contain shortened URLs or affiliate links.

If your pull request closes a GitHub issue, replace the XXXXX below with the issue number.

Closes #XXXXX

### CODE REVIEW

**Comment by lynxlynxlynx** [comment]
Mostly LGTM, needs a spellcheck run.

**Comment by RandellDawson** [comment]
Congrats @Moon4Light on your first pull request (PR)! 🎉

Thank you for your contribution to the page! 👍
We're happy to accept these changes, and look forward to future contributions. 📝

**Comment by jose-reyes-9** [comment]
Hello @RandellDawson, 

Is it possible to make pull requests on this still if I have valuable content to add? I would like to add a few tutorials, code snippets, and some more information on python GUIs. 

Cheers!

**Comment by RandellDawson** [comment]
@jose-reyes-9 You can create a new PR with changes for the file if you want.

**Pull request merged**
