### PR TITLE
fix(curriculum): make space optional

### LINKED ISSUE #46527: CatPhotoApp - Step 43: Spacing requirements not stated in instructions
### Describe the Issue

The test will only pass if there is a space between the `input` and the text "Indoor" but this is not stated in the instructions. It is explained in the hint but I feel that we should make it clear in the instructions to avoid confusion and frustration for the user.

### Affected Page

https://www.freecodecamp.org/learn/2022/responsive-web-design/learn-html-by-building-a-cat-photo-app/step-43

### Your code

This will not pass:

```
<input type="radio">Indoor
```

This will pass:

```
<input type="radio"> Indoor
```

### Expected behavior

Either get rid of the spacing requirement or clearly state that there must be a space between the `input` and text in the instructions.

### Screenshots

_No response_

### System

N/A

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by billybrown-iii**
Checklist:

- [x] I have read [freeCodeCamp's contribution guidelines](https://contribute.freecodecamp.org).
- [x] My pull request has a descriptive title (not a vague title like `Update index.md`)
- [x] My pull request targets the `main` branch of freeCodeCamp.
- [x] I have tested these changes either locally on my machine, or GitPod.

Closes #46527 

Made space between <input /> tag and text optional in challenge 43 of "Learn HTML by Building a Cat Photo App" section of the Responsive Web Design curriculum.  Also updated hint message to reflect the fact that the space is no longer required.

### CODE REVIEW

**Review by Sboonny — APPROVED** [review]
Hi @billybrown-iii . Congrats on your first pull request (PR)! 🎉

Thank you for your contribution to the page! 👍
We are happy to accept these changes and look forward to future contributions. 📝

**Review by naomi-lgbt — APPROVED** [review]
This looks good! Thanks for taking care of this!

__
[sema-logo](https://semasoftware.com/gh) &nbsp;**Summary:** :ok_hand: This code looks good

**Comment by bbsmooth** [comment]
Thanks for fixing my issue @billybrown-iii.

**Comment by raisedadead** [comment]
#### :sparkles: :sparkles: **AWESOME!** :sparkles: :sparkles: 

LGTM.

Thanks for this pull request, @billybrown-iii, and for contributing to the code-base for the first time.

We will be looking forward to more contributions in the future.

Cheers and happy contributing!

**Pull request merged**
