### PR TITLE
[Russian] Translate docs/how-to-catch-outgoing-emails-locally

### PR DESCRIPTION
**Pull request by greggubarev**
- [x] I have read [freeCodeCamp's contribution guidelines](https://github.com/freeCodeCamp/freeCodeCamp/blob/master/CONTRIBUTING.md).
- [x] My pull request has a descriptive title (not a vague title like `Update index.md`)
- [x] My pull request targets the `master` branch of freeCodeCamp.
- [x] None of my changes are plagiarized from another source without proper attribution.
- [x] My article does not contain shortened URLs or affiliate links.

 ##18312

### CODE REVIEW

**Comment by greggubarev** [comment]
@Manish-Giri can you review this one please?

**Comment by Manish-Giri** [comment]
@greggubarev Aside from the changes of `""` to `''`, the rest is in Russian, so I'm not sure if I can be much help to you reviewing this, sorry!

There also seems to be a merge conflict and it's complex enough that it cannot be resolved in the web editor itself. I can try and pull the PR in my local env. to see what the conflicts are, but I assume most of it will be in Russian too.

Maybe if you try and resolve the conflicts, I can attempt a review then?

**Comment by raisedadead** [comment]
@greggubarev 

1. You should tag @freeCodeCamp/moderators in future, and state that you need a merge because no one else is available to review your PR. Someone from the team will quickly sanity check the PR, even if they can't review the content.

2. Above all no self-merge rule is applicable at all costs. Regardless of the delay in getting anything merged.

3. Re: deleting the source repository... 

    Unfortunately nothing can be be done when a source repo has been deleted. We tend to close such PRs, because neither us nor the OP can make further changes. This is a limitation with GitHub itself.

   You should avoid having to delete a repo at all costs. I understand this usually comes from being less familiar with git. And I agree it can be intimidating. But it's best to ask for help. Especially in the [Contributors Chat room](https://gitter.im/FreeCodeCamp/Contributors).

Apologies, but we have to close this PR, and I recommend you to make a fresh one.

**Comment by greggubarev** [comment]
- @Manish-Giri The fact is that another Russian-speaking moderator is not active, and the @raisedadead  told me that I should not merge my PR and invite another moderator for this. 
- About the merge conflict - I deleted the repository from which this PR did, as I spent this way to solve other problems. If you could tell me how to fix a problem locally, I would do it. 

**Anyway - thanks for the review!**

**Comment by greggubarev** [comment]
@raisedadead ok, thank you

**Pull request closed without merging**
