### PR TITLE
Adding link to React documentation

### LINKED ISSUE #32286: Link for documentation: use-proptypes-to-define-the-props-you-expect
There should be a link to the documentation mentioned.

**Add a Link to the page with the problem:**

https://learn.freecodecamp.org/front-end-libraries/react/use-proptypes-to-define-the-props-you-expect

image

### PR DESCRIPTION
**Pull request by TomerPacific**
- [x] I have read [freeCodeCamp's contribution guidelines](https://github.com/freeCodeCamp/freeCodeCamp/blob/master/CONTRIBUTING.md).
- [x] My pull request has a descriptive title (not a vague title like `Update index.md`)
- [x] My pull request targets the `master` branch of freeCodeCamp.
- [x] None of my changes are plagiarized from another source without proper attribution.
- [x] My article does not contain shortened URLs or affiliate links.

If your pull request closes a GitHub issue, replace the XXXXX below with the issue number.

Closes #32286

### CODE REVIEW

**Comment by RandellDawson** [comment]
Hi @TomerPacific 

Can you modify your code so that is reflects the Github link markdown?

Example:
> [link title](url)

**Comment by TomerPacific** [comment]
@RandellDawson ,
does this fit the demand?

**Comment by RandellDawson** [comment]
@TomerPacific  LGTM

**Comment by RandellDawson** [comment]
It will be a while before we can merge this PR, due to the Hacktoberfest backlog.

**Pull request merged**
