### PR TITLE
chore(curriculum): add blockLayout when missing from meta

### PR DESCRIPTION
**Pull request by ojeytonwilliams**
Checklist:

- [x] I have read and followed the [contribution guidelines](https://contribute.freecodecamp.org).
- [x] I have read and followed the [how to open a pull request guide](https://contribute.freecodecamp.org/how-to-open-a-pull-request/).
- [x] My pull request targets the `main` branch of freeCodeCamp.
- [x] I have tested these changes either locally on my machine, or GitPod.

Companion to https://github.com/freeCodeCamp/freeCodeCamp/pull/56808. It adds all the layouts according to which combination of `isProjectBased` and `isGridBased` that they have. The rationale being that it's confusing (to me!) to have some block's layout determined by the `blockLayout` properties while some rely on `isProjectBased` and `isGridBased`.

 The logic for how they currently determine `blockLayout` is here

https://github.com/freeCodeCamp/freeCodeCamp/blob/c6c40097c199f934bf8ca1f986a793d8146c2fe6/client/src/templates/Introduction/components/block.tsx#L405-L407

@huyenltnguyen if this seems like a good idea to you, we can cherrypick these commits onto your PR. Or we can wait until yours is in and then look at this.

### CODE REVIEW

**Comment by ojeytonwilliams** [comment]
Absolutely, @huyenltnguyen. I'll take care of that once yours is in.

**Review by naomi-lgbt — APPROVED** [review]

**Comment by moT01** [comment]
Presumably, we will remove that logic on another PR?

```
 if (isProjectBlock) 
   return isGridBlock ? LegacyLinkBlock : ProjectListBlock; 
 return isGridBlock ? ChallengeGridBlock : LegacyChallengeListBlock; 
 ```

**Comment by ojeytonwilliams** [comment]
That can go in this PR. I'll remove it when I fix up the conflicts.

**Comment by ojeytonwilliams** [comment]
@freeCodeCamp/mobile the `blockLayout` is in the meta now, so gets added to the external data. I assume this is okay, because we're not removing anything, but could you confirm?

**Comment by ojeytonwilliams** [comment]
Thanks, @huyenltnguyen just to make sure we're on the same page: these are improvements? i.e. the current block layouts in main aren't the ones we want and your changes fix that.

**Review by Nirajn2311 — COMMENTED** [review]
All good from mobile app perspective

**Review by huyenltnguyen — APPROVED** [review]
> just to make sure we're on the same page: these are improvements?

Yup. Those blocks seemed to not be using the correct layout, so I thought we could fix that here (sorry for the scope creep).

**Pull request merged**
