### PR TITLE
added test case to waypoint

### LINKED ISSUE #4866: Waypoint: House our page within a Bootstrap Container Fluid Div
**Missing Check**

Challenge [Waypoint: House our page within a Bootstrap Container Fluid Div](http://www.freecodecamp.com/challenges/waypoint-house-our-page-within-a-bootstrap-container-fluid-div#?solution=%3Ch3%20class%3D%22text-primary%20text-center%22%3EjQuery%20Playground%3C%2Fh3%3E%0A%3Cdiv%20class%3D%22container-fluid%22%3E%3C%2Fdiv%3E%0A%0A) has an issue.

User Agent is: <code>Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/46.0.2490.86 Safari/537.36</code>.

My code:
```html
<h3 class="text-primary text-center">jQuery Playground</h3>
<div class="container-fluid"></div>


```

Steps to reproduce:

The Instructions state :
Let's nest your h3 element within a div element with the class container-fluid.

The Checks are:
1. Your div element should have the class container-fluid. 
2. Make sure each of your div elements has a closing tag. 

**Missing** Check:
Your h3 element should be nested within your div element.

Fix :
Add the missing check.

Thanks,
raisedadead.

### PR DESCRIPTION
**Pull request by gasperno**
Closes #4866

### CODE REVIEW

**Comment by SaintPeter** [comment]
I love your PRs, but you need to do two things:
1) Have a more descriptive title that includes the waypoint name
  * "added test case to waypoint" could be about anything
2) Describe the change in your PR body, especially if you tested locally or not.

**Comment by SaintPeter** [comment]
I did test this and it worked well.  
However, looks like you'll need to rebase to deal with some merge conflicts.

**Comment by gasperno** [comment]
Can I submit a new PR and delete this one? I think I messed up my local repo with rebase command.

**Comment by BerkeleyTrue** [comment]
Sure just close this one and submit the new one

**Comment by SaintPeter** [comment]
Closing as per user request.

**Pull request closed without merging**
