### PR TITLE
Edit description for more clarification

### PR DESCRIPTION
**Pull request by Ahmed-Elbessfy**
I am a new learner for REACT. From what I understood about the challenge, I think the description needs to be improved. So I made some changes to make more clear to be understood for newcomers like me.

- [ ] I have read [freeCodeCamp's contribution guidelines](https://github.com/freeCodeCamp/freeCodeCamp/blob/master/CONTRIBUTING.md).
- [ ] My pull request has a descriptive title (not a vague title like `Update index.md`)
- [ ] My pull request targets the `master` branch of freeCodeCamp.
- [ ] None of my changes are plagiarized from another source without proper attribution.
- [ ] My article does not contain shortened URLs or affiliate links.

If your pull request closes a GitHub issue, replace the XXXXX below with the issue number.

Closes #XXXXX

### CODE REVIEW

**Comment by RandellDawson** [comment]
Your additions have several typos and grammar issues.  Also, I do not see how these changes improve the challenge description.  It would have been better to first create an issue to explain which of the challenge description you found difficult to understand.  Then, multiple users could have made suggestions on how best to proceed, so that a PR could be created.

Can you provide some more information for us about what you found difficult to understand about the existing instructions?

**Comment by Ahmed-Elbessfy** [comment]
First thanks for your reviewing. Second, So sorry for the typos. Third, about what is difficult to understand : 
It took me a while to understand what the description means although I know it before because it doesn't clarify exactly what are the 2 methods to write a tag and close it which lead to not understanding how React closes tags and that may confuse a beginner as I was. So I think if we use points this will make it more clear than being explained in paragraphs.

**Comment by Manish-Giri** [comment]
IMO, the original wording is fine. The proposed changes do not add anything new while making things harder to read, such as - 

> Ordinary tags which needs always closing tag for good valid HMTL code 

> In JSX, there is no defference between Ordianry tags from HTML syntax.

**Comment by RandellDawson** [comment]
Thank you for opening this pull request.

This is a standard message notifying you that we’ve reviewed your pull request and have decided not to merge it. We would welcome future pull requests from you.

Thank you and happy coding.

**Pull request closed without merging**
