### PR TITLE
fix(client): use picture and source to display correct logo

### LINKED ISSUE #35934: [rocks/beta] logo in nav doesn't show up
**Describe the bug**
The FCC logo on the top left of the nav doesn't show up.

**To Reproduce**
1. Go to freecodecamp.rocks or refresh the page if you're already there.
1. go to either the 'learn' or 'settings' page with a wide enough window that the logo should show up
2. It doesn't show up

- It does show up if you shrink the window and then expand it again. Strange.

**Screenshots**
Screen Shot 2019-04-29 at 8 49 16 AM

**Desktop (please complete the following information):**
 - OS: high sierra 10.13.6
 - Firefox 66.0.3
 - Chrome 74.0.3729.108

**Additional context**
Tested on chrome and firefox, the issue occurs on both.

### PR DESCRIPTION
**Pull request by ojeytonwilliams**
- [x] I have read [freeCodeCamp's contribution guidelines](https://github.com/freeCodeCamp/freeCodeCamp/blob/master/CONTRIBUTING.md).
- [x] My pull request has a descriptive title (not a vague title like `Update index.md`)
- [x] My pull request targets the `master` branch of freeCodeCamp.
- [x] None of my changes are plagiarized from another source without proper attribution.
- [x] All the files I changed are in the same world language (for example: only English changes, or only Chinese changes, etc.)
- [x] My changes do not use shortened URLs or affiliate links.

Closes #35934

Possibly due to a bug with `react-responsive`, the second `img` in the conditional was being returned for wide viewports.  This meant nothing was displayed in that case, since `.logo-glyph` is hidden below 735px.

### CODE REVIEW

**Review by ValeraS — CHANGES_REQUESTED** [review]
Let's remove `Media` at all. We have got needed styles to show the right logo.

**Comment by ojeytonwilliams** [comment]
@ValeraS It does display perfectly either way.  However, it might be worth keeping `Media` because it makes sure that only the visible logo gets downloaded (until the window gets resized).  If we take it out both logos get downloaded immediately, at least on my versions of Chrome and Firefox.

**Comment by ahmadabdolsaheb** [comment]
FYI, if it helps, you could completely remove the small logo and go with the large logo for all screen sizes. That seems to be the direction for the next iteration.

**Comment by ojeytonwilliams** [comment]
@ahmadabdolsaheb Is this what you had in mind?  @ValeraS With this approach we definitely don't need `Media`.

**Comment by ahmadabdolsaheb** [comment]
Yes. LGTM.
What do you think @ValeraS ?
here is how it looks on smaller screens( iphone 5 ) with the full nav.
image

**Comment by ValeraS** [comment]
@ahmadabdolsaheb But on other screens, for example `/learn`, where will be search bar shown?

**Comment by ojeytonwilliams** [comment]
The more I look at this, the more I think we should abandon `react-responsive` entirely - not just for the logo.  It doesn't seem to interact well with Gatsby, as discussed [here](https://github.com/gatsbyjs/gatsby/issues/2142) and [here](https://github.com/gatsbyjs/gatsby/issues/11023).  I've changed my mind and think we'd be better off just using media queries.  Otherwise I think we're going to have the page jump around and/or parts render quite late.  

I'm pretty sure all the problems in #35931 come from `react-responsive` too, though I can't check the Apple specific issue.

As for the search bar, I think it looks better with the glyph
iPhone5Glyph
than the text

iPhone5
on small screens.  Which does everyone else prefer?

**Comment by ahmadabdolsaheb** [comment]
@ValeraS @ojeytonwilliams I agree, we should move forward with the glyph for now until we find a better solution.

**Comment by ahmadabdolsaheb** [comment]
Tested it locally, LGTM.
If it is alright with you @ValeraS, we can go ahead with this solution.

**Comment by ValeraS** [comment]
@ojeytonwilliams Let's try another approach:
```jsx
function NavLogo() {
  return (
    <picture>
      <source media='(max-width: 734px)' srcSet={fCCglyph} />
      <source media='(min-width: 735px)' srcSet={fCClogo} />
      <img
        alt='learn to code at freeCodeCamp logo'
        className='nav-logo'
        src={fCCglyph}
      />
    </picture>
  );
}
```

**Comment by ojeytonwilliams** [comment]
@ValeraS I like this approach a lot, it's a nice way to avoid the unnecessary downloads!  I've implemented the changes you requested and removed some css that was no longer needed.

**Review by ValeraS — APPROVED** [review]

**Pull request merged**
