### PR TITLE
Add Code Of Conduct

### PR DESCRIPTION
**Pull request by ivannieto**
#### Pre-Submission Checklist

- [ ] Your pull request targets the `staging` branch of FreeCodeCamp.
- [ ] Branch starts with either `fix/`, `feature/`, or `translate/` (e.g. `fix/signin-issue`)
- [x] You have only one commit (if not, [squash](http://forum.freecodecamp.com/t/how-to-squash-multiple-commits-into-one-with-git/13231) them into one commit).
- [x] All new and existing tests pass the command `npm test`. Use `git commit --amend` to amend any fixes.

#### Type of Change

- [ ] Small bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds new functionality)
- [ ] Breaking change (fix or feature that would change existing functionality)
- [ ] Add new translation (feature adding new translations)

#### Checklist:

- [x] Tested changes locally.
- [x] Closes currently open issue (replace XXXX with an issue no): Closes #XXXX

### CODE REVIEW

**Comment by texas2010** [comment]
I am sorry, we already have Code of Conduct.

**Comment by ivannieto** [comment]
Can't see nothing related in the root of the main project.

**Comment by texas2010** [comment]
@ivannieto, oh okay. I will ask someone look at this.

**Comment by abhisekp** [comment]
FreeCodeCamp code of conduct is documented here :point_right: **https://www.freecodecamp.com/code-of-conduct**

**Comment by ivannieto** [comment]
Then, I propose to add it to the main project.

**Comment by texas2010** [comment]
@ivannieto, oh ok. You can open an issue for propose code of conduct.

**Pull request closed without merging**
