### PR TITLE
docs(readme): updated as per new curriculum and certification programs

### PR DESCRIPTION
**Pull request by sanchit0496**
#### Pre-Submission Checklist

- [x] Your pull request targets the `staging` branch of freeCodeCamp.
- [ ] Branch starts with either `fix/`, `feature/`, or `translate/` (e.g. `fix/signin-issue`)
- [ ] You have only one commit (if not, [squash](http://forum.freecodecamp.org/t/how-to-squash-multiple-commits-into-one-with-git/13231) them into one commit).
- [ ] All new and existing tests pass the command `npm test`. Use `git commit --amend` to amend any fixes.

#### Type of Change

- [ ] Small bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds new functionality)
- [ ] Breaking change (fix or feature that would change existing functionality)
- [x] Add new translation (feature adding new translations)

#### Checklist:

- [x] Tested changes locally.
- [ ] Addressed currently open issue (replace XXXXX with an issue no in next line)

Closes #XXXXX

### CODE REVIEW

**Comment by sanchit0496** [comment]
First open source contribution. Making some more changes.

**Comment by sanchit0496** [comment]
The READ.md file has been updated as per the current curriculum and certification programs in the second commit.

**Comment by sanchit0496** [comment]
fccgh

**Comment by texas2010** [comment]
@sanchit0496 Where is issue number?

**Comment by sanchit0496** [comment]
@texas2010 https://github.com/freeCodeCamp/freeCodeCamp/issues/17361

**Comment by raisedadead** [comment]
@sanchit0496 Thanks a lot for updating the README. @QuincyLarson Can you please take a look.

**Comment by raisedadead** [comment]
Landed via https://github.com/freeCodeCamp/freeCodeCamp/pull/17367

**Pull request closed without merging**
