### PR TITLE
fix(client): render MathJax in jaws header

### LINKED ISSUE #52794: MathJax is not rendered in upper jaw
### Describe the Issue

MathJax is not rendered in upper jaw, this means new JS and Python curriculum.
Example:
image

### Affected Page

https://www.freecodecamp.org/learn/javascript-algorithms-and-data-structures-v8/learn-advanced-array-methods-by-building-a-statistics-calculator/step-46

### Steps to Reproduce

1. Go to challenge from new JS or Python curriculum, which includes MathJax tags.
2. See MathJax is not rendered.

### Expected behavior

MathJax properly rendered in the description in the upper jaw, for example:
image

### Screenshots

_No response_

### System

n/a

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by gikf**
Checklist:

- [x] I have read and followed the [contribution guidelines](https://contribute.freecodecamp.org).
- [x] I have read and followed the [how to open a pull request guide](https://contribute.freecodecamp.org/#/how-to-open-a-pull-request).
- [x] My pull request targets the `main` branch of freeCodeCamp.
- [x] I have tested these changes either locally on my machine, or GitPod.

Closes #52794

- - -
- MathJax is rendered in jaws header.
- A bit re-organizing and unifying to MathJax util.

### CODE REVIEW

**Comment by Sembauke** [comment]
I am not really a fan of using pathName as a condition. I think it would be better if we used the SuperBlocks enum to tell if MathJax needs to be imported or not.

We are aiming to no longer use stringified versions of SuperBlock names.

**Comment by gikf** [comment]
Do you mean _just_ using `SuperBlocks` in `isMathJaxAllowed` to compare/match (whichever is correct) with the passed `pathname`? Or having `SuperBlock` as the parameter?

The latter latter might not be possible, `onRenderBody` from the `gatsby-ssr` doesn't seem to be able to access page props.

**Comment by Sembauke** [comment]
If the latter is not possible, then we should keep it as it is.

**Review by Sembauke — APPROVED** [review]

**Review by moT01 — COMMENTED** [review]
I would be fine adding this if we want. Looks like mathjax adds about 300kb, which isn't a lot - but it loads for any of the JS challenges. I didn't see any other JS challenges that use it, though - so I'm wondering if it would be better to just use HTML tags for this one challenge to avoid loading it.

Here's the description of this challenge using HTML tags:

```
To calculate a root exponent, such as <sup>n</sup>&Sqrt;x, you can use an inverted exponent x<sup>1/n</sup>.

Declare a `standardDeviation` variable, and use the `Math.pow()` function to assign it the value of variance<sup>1/2</sup>.
```

and the output looks like this:

Screenshot 2024-02-16 at 3 42 05 PM


Just offering an alternative solution. I like some of the optimization here either way - and mathjax does look better, so I'm fine with this as-is if we don't want to do that. What do you think @gikf @Sembauke ?

**Comment by gikf** [comment]
@moT01 I wouldn't really mind, whichever is wanted. I can throw away enabling it in new JS and new Python, while keeping the rest. It will make changing it in future easier anyway, if needed.

**Comment by ilenia-magoni** [comment]
We are going to need it in the new Python curriculum when we start working on the new projects. Also we were hoping to try to draw a graph for the Shortest Path Algorithm, instead of using images. (There is no graphic rapresentation at all at the moment)

**Review by moT01 — APPROVED** [review]
Alright, lets go with this for now then. Thanks for all the work @gikf 🎉

**Pull request merged**
