### PR TITLE
add a simpler solution to Priority Queue

### PR DESCRIPTION
**Pull request by JoolsMcFly**
#### Pre-Submission Checklist

- [x] Your pull request targets the `staging` branch of freeCodeCamp.
- [x] Branch starts with either `fix/`, `feature/`, or `translate/` (e.g. `fix/signin-issue`)
- [x] You have only one commit (if not, [squash](http://forum.freecodecamp.com/t/how-to-squash-multiple-commits-into-one-with-git/13231) them into one commit).
- [x] All new and existing tests pass the command `npm test`. Use `git commit --amend` to amend any fixes.

#### Type of Change

- [x] Small bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds new functionality)
- [ ] Breaking change (fix or feature that would change existing functionality)
- [ ] Add new translation (feature adding new translations)

#### Checklist:

- [x] Tested changes locally.
- [ ] Closes currently open issue (replace XXXX with an issue no): Closes #XXXX

#### Description

Existing solution is a bit overkill (reduce + temp array). 
This PR introduces, I believe, a shorter and simpler to understand solution.
Thanks!

### CODE REVIEW

**Comment by QuincyLarson** [comment]
@bonham000 since it was likely you who created this original challenge, would you be interested in taking a look at @JoolsMcFly's solution and merging if you think it's an improvement?

**Comment by bonham000** [comment]
I actually did not write this one but I agree with OP and this passes tests — merging.

**Comment by JoolsMcFly** [comment]
Awesome, thanks!

**Comment by mooseworx** [comment]
unsubscribe

**Comment by texas2010** [comment]
@mooseworx 
looks like you may have accidentally subscribed to all notifications for the [FreeCodeCamp](https://github.com/FreeCodeCamp/FreeCodeCamp) repository. To stop receiving notifications please visit the [subscriptions page](https://github.com/FreeCodeCamp/FreeCodeCamp/subscription) and select "Not watching". Additionally, you can visit the [GitHub Help page on managing notification delivery methods](https://help.github.com/articles/managing-notification-delivery-methods/) for more help.

We are sorry for your inconvenience!

**Pull request merged**
