### PR TITLE
fix(learn): Improve tests for the Nest an Anchor Element within a Paragraph challenge

### PR DESCRIPTION
**Pull request by RandellDawson**
Checklist:

- [x] I have read [freeCodeCamp's contribution guidelines](https://contribute.freecodecamp.org).
- [x] My pull request has a descriptive title (not a vague title like `Update index.md`)
- [x] My pull request targets the `main` branch of freeCodeCamp.
- [x] All the files I changed are in the same world language, for example: only English changes, or only Chinese changes, etc.

I created this PR to address a recurring confusion I see in the [Nest an Anchor Element within a Paragraph](https://www.freecodecamp.org/learn/responsive-web-design/basic-html-and-html5/nest-an-anchor-element-within-a-paragraph) challenge.  This is the first challenge where the user is introduced to the concept of nesting an existing element into a newly created element.  So many times, a user ends up creating another anchor element instead of just using the existing anchor element.  Creating a new anchor element without the exact attributes/text of the original can lead to problems such as the one [in this forum topic](https://forum.freecodecamp.org/t/hi-thanks-in-advance-im-pulling-my-hair-out/450826). 

This PR aims to better guide the user into writing the correct code.  This is similar to the approach we are taking in the v7 curriculum.

### CODE REVIEW

**Review by naomi-lgbt — APPROVED** [review]
Looks good to me.

**Review by raisedadead — DISMISSED** [review]
I disagree. (kidding just testing out the auto merge, randy is awesome)

**Comment by raisedadead** [comment]
@moT01 can you approve this change.

**Review by moT01 — APPROVED** [review]
LGTM 🎉

**Comment by raisedadead** [comment]
Bazinga! That works

**Comment by raisedadead** [comment]
@RandellDawson go ahead and dismiss my review. It should merge the PR.

**Comment by RandellDawson** [comment]
@raisedadead Cool, so not until you either dismiss your requested change or approve it, will anything else happen?

**Comment by raisedadead** [comment]
> Cool, so not until you either dismiss your requested change or approve it, will anything else happen?

That is correct. Why don't you go ahead and try dismissing my review?

**Comment by nhcarrigan** [comment]
Woah that's neat.

**Comment by RandellDawson** [comment]
I just hope this does not get abused.  For instance, if there was a hold out mod that was requesting changes and two other mods approve and just decide to dismiss the other mod's requested changes.

**Comment by ShaunSHamilton** [comment]
I do not see myself making all that much use of this _auto-merge_ feature, because I often edit the commit message.

**Comment by nhcarrigan** [comment]
@ShaunSHamilton for what it is worth, the default commit message would be the title of the pull request.

**Comment by raisedadead** [comment]
>  because I often edit the commit message.

You will be able to edit the message prior commit. Everything works as usual (the only advantage is you skip the wait for a CI to pass, which could be helpful if we mandated the Cypress tests to be required)

Screenshot of editing commit message prior enabling auto merge:

image

**Pull request merged**
