### PR TITLE
fix(curriculum): use checkVisibility for visibility tests

### PR DESCRIPTION
**Pull request by lasjorg**
Checklist:

- [x] I have read and followed the [contribution guidelines](https://contribute.freecodecamp.org).
- [x] I have read and followed the [how to open a pull request guide](https://contribute.freecodecamp.org/how-to-open-a-pull-request/).
- [x] My pull request targets the `main` branch of freeCodeCamp.
- [x] I have tested these changes either locally on my machine, or GitPod.

This should allow the camper to show/hide the elements however they want, e.g. `classList.toggle("show")`.

I realize their code will be wiped out when they load the next challenge step. But this way they at least can have some sense of passing the requirements the way they want to, even if it doesn't persist. Which I think is important for this type of challenge (review/do it yourself). It could even work with `visibility` and `opacity` with the options set to true.

---

The `checkVisibility` API has good support.

https://caniuse.com/?search=checkVisibility

https://developer.mozilla.org/en-US/docs/Web/API/Element/checkVisibility

---

As an aside, `display: hidden` isn't a thing.

### CODE REVIEW

**Comment by gikf** [comment]
Do you know what's up with the failing test? I thought cause might be somehow being run not in order, so the modal is visible, but making sure other tests are clicking the button twice, doesn't change anything regarding failing.

Surprisingly moving failing test in order to the last test will cause another test fail instead.

**Comment by lasjorg** [comment]
No I don't. It works fine in develop, I tested it with both classes and inline styles.

I wasn't able to run tests locally, but I just had to increase the NODE_OPTIONS memory setting to twice as much, so now I can. They fail locally as well with the same error.

Not sure what the difference is between how the code runs in develop vs when tested. I tried messing with Babel/corejs but that didn't do anything.

Maybe someone that knows more about the built/testing side knows.

@ojeytonwilliams @naomi-lgbt do you have any insights?

---

Side question, do we have access to jest-dom in the challenge assert tests? I know I could just try it, but I can't right now. It has `toBeVisible` so that might work instead (if we can use it, that is).

**Comment by ojeytonwilliams** [comment]
@lasjorg Turns out it was an issue with puppeteer. Specifically that each version of puppeteer comes with a specific version of Chrome. The one we had simply didn't include `checkVisibility`, hence the error.

https://github.com/freeCodeCamp/freeCodeCamp/pull/55427 updates it, so once that's in this should be good to go.

**Comment by ojeytonwilliams** [comment]
> Side question, do we have access to jest-dom in the challenge assert tests?

Nope, not even jest, just chai. We can always add more assertion packages (chai-dom, say), but we want to keep the bundle size down, so typically that's the last resort.

**Comment by lasjorg** [comment]
@ojeytonwilliams Thank you for the info and update.

**Comment by ojeytonwilliams** [comment]
The puppeteer changes are in, so this should be fine now.

**Review by naomi-lgbt — APPROVED** [review]

**Review by Sembauke — APPROVED** [review]

**Pull request merged**
