### PR TITLE
chore: refactor and simplify testing

### PR DESCRIPTION
**Pull request by ojeytonwilliams**
The goal here is to make dom and js testing use the same flow, as well as slightly disentangle the client and the curriculum.

### CODE REVIEW

**Review by raisedadead — CHANGES_REQUESTED** [review]
While you are at it:

`client/utils/blockNameify.js → utils/blockNameify.js` 

should be

`client/utils/blockNameify.js → utils/block-nameify.js`

It was a terrible choice to use casing in file names, against the convention.

**Comment by ojeytonwilliams** [comment]
Just let me know before you merge, and I'll squash the new one into the original, so we don't have squash the whole lot.

**Comment by ojeytonwilliams** [comment]
Sorry about the noise, I should have stopped a bit earlier.  On the plus side, the CI is working really well...

**Comment by raisedadead** [comment]
Let me know when you are ready for QA.

**Comment by ojeytonwilliams** [comment]
@raisedadead it's ready now.

**Review by raisedadead — APPROVED** [review]

**Pull request merged**
