### PR TITLE
Fix Bonfire Truncate a String Description

### LINKED ISSUE #4706: Wrong description in truncate a string bonfire question.
In the question description the following section -
" If the length of the string is less than or equal to 3 characters, then the length of the three dots is not added to the string length.".
This should be stated as follwoing to get the code accepted -
" If the num is less than 3, then the length of the three dots is not added to the string length."
I had solved all the problems in algorithm scripting but this one because according to previous description my code was not getting accepted.
As soon as I wrote the code for the new description I got my code accepted.

### PR DESCRIPTION
**Pull request by iammangod96**
closes #4706 

In the question description the following section -
" If the length of the string is less than or equal to 3 characters, then the length of the three dots is not added to the string length.".
This should be stated as follwoing to get the code accepted -
" If the num is less than 3, then the length of the three dots is not added to the string length."
I had solved all the problems in algorithm scripting but this one because according to previous description my code was not getting accepted.
As soon as I wrote the code for the new description I got my code accepted.

### CODE REVIEW

**Comment by iammangod96** [comment]
Proof being the following function which got accepted as correct solution-
function truncate(str, num) {
  
  if(str.length<=num){
    return str;
  }else{
    if(num<=3){
      return str.slice(0,num)+"...";
    }else{
      return str.slice(0,num-3)+"...";
    }
  }
}

**Comment by ltegman** [comment]
Thanks for the PR! However, you'll need to fix it up a bit before it can be accepted. Please change the PR title to something shorter like "Fix Bonfire Truncate a String Description" and add `Closes #4706` to the body of the PR so that it is linked to the issue it closes and will auto-close that issue once this PR is merged.

Also, next time please read our [Contribution Guide](https://github.com/FreeCodeCamp/FreeCodeCamp/wiki/Pull-Request-Contribute) and make sure you are working in an appropriately named branch.

**Comment by iammangod96** [comment]
I have fixed everything and I'll make sure to go with the contribution guide. Sorry.

**Comment by ltegman** [comment]
Thanks for the fixes! One more thing I didn't notice last time: could you please wrap the word num in code tags like `<code>num</code>`? Once you've done this you can `git add . && git commit --amend` to alter your last commit and then `git push -f` to force push this change onto the remote branch.

**Comment by iammangod96** [comment]
Actually I am using only the web interface and not git. I could not find a way to delete or edit my previous commit in my local branch so I made a new commit and merged it to this pull request. And since the new commit is just modifying the previous one so I think this should work.

**Comment by ltegman** [comment]
I'm sorry, but having the git command line interface and it's capabilities available is a bit of a prerequisite for contributing to the repo. If PR's are corrected through multiple commits you essentially end up polluting the repo commit history with unfinished or incorrect commits. Our practice is to amend or squash corrected commits so this does not happen. If you are interested in getting your branch setup locally you can still accomplish this by [using rebase to squash your commits](https://github.com/FreeCodeCamp/FreeCodeCamp/wiki/git-rebase#squashing-multiple-commits-into-one). I'd also be happy to help you through any questions you have getting the repo setup with git locally on Gitter.

**Comment by bugron** [comment]
@iammangod96 I'm closing this because we have another PR https://github.com/FreeCodeCamp/FreeCodeCamp/pull/4738 which fixes the same issue, thanks for the PR though. Sorry for the inconvenience.
You've opened your PR **before** #4738 and normally I'd close that PR but you're using GitHub's web interface so your can't `amend` ("rewrite") your commits.

**Pull request closed without merging**
