### PR TITLE
fix(challenges): Fix test on react challenge that was always passing

### LINKED ISSUE #16555: [Beta] React set state challenge doesn't need any code to pass tests
https://beta.freecodecamp.org/en/challenges/react/set-state-with-thissetstate
#### Challenge Name
React Set State with this.setState()

https://beta.freecodecamp.org/en/challenges/react/set-state-with-thissetstate

#### Issue Description

The default code passes all tests no matter what you put. This has been verified by two other users on gitter.

#### Browser Information

* Browser Name, Version: Google Chrome, Version 63.0.3239.132 (Official Build) (64-bit)
* Operating System: Mac OS High Sierra 10.13.2
* Mobile, Desktop, or Tablet: Desktop

#### Your Code
This is the default code:

```js
class ControlledInput extends React.Component {
  constructor(props) {
    super(props);
    this.state = {
      input: ''
    };
  }
  // change code below this line

  // change code above this line
  render() {
    return (
      <div>
        { /* change code below this line */}

        { /* change code above this line */}
        <h4>Controlled Input:</h4>
        <p>{this.state.input}</p>
      </div>
    );
  }
};


```
#### Screenshot

Here are the challenge instructions and tests that are displayed:

screen shot 2018-01-22 at 10 36 35 am

screen shot 2018-01-22 at 10 36 45 am

### PR DESCRIPTION
**Pull request by diogorighi**
#### Pre-Submission Checklist

- [x] Your pull request targets the `staging` branch of freeCodeCamp.
- [x] Branch starts with either `fix/`, `feature/`, or `translate/` (e.g. `fix/signin-issue`)
- [x] You have only one commit (if not, [squash](http://forum.freecodecamp.org/t/how-to-squash-multiple-commits-into-one-with-git/13231) them into one commit).
- [x] All new and existing tests pass the command `npm test`. Use `git commit --amend` to amend any fixes.

#### Type of Change

- [x] Small bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds new functionality)
- [ ] Breaking change (fix or feature that would change existing functionality)
- [ ] Add new translation (feature adding new translations)

#### Checklist:

- [x] Tested changes locally.
- [x] Addressed currently open issue (replace XXXXX with an issue no in next line)

Closes #16555

#### Description

I changed the way the challenge is tested to simulate a click instead of set the state.
This is my first PR, so if I did something wrong, please tell me! ;)

### CODE REVIEW

**Comment by no-stack-dub-sack** [comment]
@diogorighi Welcome, and thanks for your first PR! 

I can take a look at the code, but please check out the PR template that is included when you open a new PR and re-copy it in and fill that out. With so many people contributing to this codebase, this is a necessary and very helpful step in making sure we're following some needed protocols before reviewing / merging a PR.  Include your comments at the bottom of the template. 

Also, there is a great resource for contributing [here](https://github.com/freeCodeCamp/freeCodeCamp/blob/staging/CONTRIBUTING.md#common-steps), which is especially useful for first-time contributors. I've linked specifically to the part about commit messages, because unfortunately we can't accept PRs with issue numbers in the commit message. Would you mind amending it?

Thanks! I know it's a lot of work, and some of it probably seems unnecessary, but again, with so many contributors, keeping consistency is key. Really appreciate your effort here, and please let me know if there are any other questions!

**Review by no-stack-dub-sack — CHANGES_REQUESTED** [review]
Code LGTM! Nice catch too, we had this test working on the Alpha site, so I probably missed something when copying it over, and didn't realize it since the challenge passed. 

Please see the comments regarding the PR itself. Once the commit message is amended, and the PR template is filled out (looks like everything is good to be checked), I'll be happy to accept this PR! Thanks again!

**Comment by diogorighi** [comment]
Thanks @no-stack-dub-sack! I'll try to fix the PR ASAP ;)

**Review by no-stack-dub-sack — APPROVED** [review]

**Comment by no-stack-dub-sack** [comment]
@diogorighi thanks for the quick turnaround on this, and nice job on your first PR to freeCodeCamp! We appreciate the help!

**Pull request merged**
