### PR TITLE
Add link to WCAG to Applied Accessibility Index Page

### PR DESCRIPTION
**Pull request by levlaz**
Checklist:

- [x] I have read [freeCodeCamp's contribution guidelines](https://contribute.freecodecamp.org).
- [x] My pull request has a descriptive title (not a vague title like `Update index.md`)
- [x] My pull request targets the `master` branch of freeCodeCamp.
- [x] All the files I changed are in the same world language, for example: only English changes, or only Chinese changes, etc.

This commit adds a link to the W3 WCAG guidelines page. I believe this is a small, but useful enhancement to this page.

### CODE REVIEW

**Comment by raisedadead** [comment]
Blocked by #38308

**Review by moT01 — COMMENTED** [review]
I think we want to avoid using external links in the challenges as much as possible. So I don't think this should be added. Anyone else can feel free to weigh in.

**Comment by levlaz** [comment]
That makes sense. In a previous module we linked to Wikipedia so i figured it was fair game. 

This is absolutely not a necessary link.

**Comment by moT01** [comment]
Yes, I know there's some hyperlinks lingering around out there, but I think that the general hope is to remove them. You can leave this open for now if you want and maybe someone else will share an opinion.

**Comment by RandellDawson** [comment]
@levlaz We actually are not wanting to add any more external links outside freeCodeCamp.org at this point.  I am going to close this PR now.  Users can search on their own to find out more about WCAG.

We do appreciate your efforts here and look forward to future contributions.

Thank you for understanding.

**Pull request closed without merging**
