### PR TITLE
chore: remove monaco-editor - already a peer

### PR DESCRIPTION
**Pull request by raisedadead**
This removes `monaco-editor` because it's a peer dependency of `react-monaco-editor` and since we are on npm 8, the correct expected version of `monaco-editor` by `react-monaco-editor` will be installed automatically.

The will remove pitfalls like https://github.com/freeCodeCamp/freeCodeCamp/pull/44708#issuecomment-1007324841

### CODE REVIEW

**Review by Sembauke — DISMISSED** [review]

**Comment by ojeytonwilliams** [comment]
Unfortunately there are a few problems with this.  The `react-monaco-editor` > 0.40 needs React 17 and we're stuck on 16 for now. Also, it's version 0.46 where they start using peer-deps, so there isn't a version we can use.

Finally, we need to make sure `monaco-editor-webpack-plugin` is compatible with the version of `monaco-editor` we install, that gets harder if we let `react-monaco-editor` choose.

**Comment by ojeytonwilliams** [comment]
This gets less messy once we can upgrade React, so I'll try to get to that sooner rather than later.

**Comment by nhcarrigan** [comment]
> Finally, we need to make sure monaco-editor-webpack-plugin is compatible with the version of monaco-editor we install, that gets harder if we let react-monaco-editor choose.

For what it's worth, I'm pretty sure `npm 8` "handles" this. If `react-monaco-editor` calls for 0.1.0 and `monaco-editor-webpack-plugin` calls for 0.2.0, `npm` should throw a "module resolution error" and fail.

**Comment by ojeytonwilliams** [comment]
@nhcarrigan yeah, that's true.  We'll still get errors, but that just means we'll have to handle this a bit more manually than other dependencies.

**Pull request closed without merging**
