### PR TITLE
Updated Lang="en"

### LINKED ISSUE #49562: Learn HTML by Building a Cat Photo App - Step 67 Lang attribute issue
### Describe the Issue

Simple issue. When typing in the attribute for "lang" if you type a space between the attribute and the value it will mark it as incorrect. Even though it may not be proper formatting, it may be confusing for beginners that have used spaces up until this point. 

### Affected Page

https://www.freecodecamp.org/learn/2022/responsive-web-design/learn-html-by-building-a-cat-photo-app/step-67

### Your code

```
<html lang = "en">
```

### Expected behavior

It should accept the code as fine and continue to the next lesson. 

### Screenshots

Capture

### System

- Device: Desktop 
- OS: Windows 10
- Browser: Mozilla Firefox
- Version: 110.0 (64-bit)

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by Sagargupta16**
Checklist:

- [x] I have read and followed the [contribution guidelines](https://contribute.freecodecamp.org).
- [x] I have read and followed the [how to open a pull request guide](https://contribute.freecodecamp.org/#/how-to-open-a-pull-request).
- [x] My pull request targets the `main` branch of freeCodeCamp.
- [x] I have tested these changes either locally on my machine, or GitPod.

Closes #49562

### CODE REVIEW

**Review by J-Drakon — COMMENTED** [review]
Cool

**Review by Sheriff-Forever — COMMENTED** [review]
Perfect

**Comment by bbsmooth** [comment]
@Sagargupta16 You shouldn't change the HTML. That is the seed code for the step and it shouldn't have a `lang` attribute. 

What you need to fix is the test that is not allowing spaces when you add the `lang` attribute to the `html` element.

Concerning that test, I think we also need to fix it so it only allows `en` as the value since that's what the instructions ask for.

**Comment by Sagargupta16** [comment]
> @Sagargupta16 You shouldn't change the HTML. That is the seed code for the step and it shouldn't have a `lang` attribute.
> 
> What you need to fix is the test that is not allowing spaces when you add the `lang` attribute to the `html` element.
> 
> Concerning that test, I think we also need to fix it so it only allows `en` as the value since that's what the instructions ask for.

ok got it

**Comment by bbsmooth** [comment]
@Sagargupta16 Also, you need to update the title of this PR so it follows FCC recommended practices:

[Prepare a good PR title](https://contribute.freecodecamp.org/#/how-to-open-a-pull-request?id=prepare-a-good-pr-title)

**Comment by Sagargupta16** [comment]
> @Sagargupta16 Also, you need to update the title of this PR so it follows FCC recommended practices:
> 
> [Prepare a good PR title](https://contribute.freecodecamp.org/#/how-to-open-a-pull-request?id=prepare-a-good-pr-title)

Ok Thanks I will take look at FCC recommended practices and Change PR Title

**Pull request closed without merging**
