### PR TITLE
Updated index.md - Added TOC

### PR DESCRIPTION
**Pull request by GunnerJnr**
Updated index.md to include a table of contents for easier file navigation, now the user can jump to the relevant section

- [x] I have read [freeCodeCamp's contribution guidelines](https://github.com/freeCodeCamp/freeCodeCamp/blob/master/CONTRIBUTING.md).
- [x] My pull request has a descriptive title (not a vague title like `Update index.md`)
- [x] My pull request targets the `master` branch of freeCodeCamp.
- [x] None of my changes are plagiarized from another source without proper attribution.
- [x] My article does not contain shortened URLs or affiliate links.

If your pull request closes a GitHub issue, replace the XXXXX below with the issue number.

Closes #XXXXX

### CODE REVIEW

**Comment by GunnerJnr** [comment]
Added TOC to index.md for ease of navigation.

**Comment by RandellDawson** [comment]
@GunnerJnr Make sure you do not change the title metadata.  The correct syntax is:
```
---
title: Article Title
---
```
You changed it to Title, but I corrected it for you.

**Comment by GunnerJnr** [comment]
> @GunnerJnr Make sure you do not change the title metadata. The correct syntax is:
> 
> ```
> ---
> title: Article Title
> ---
> ```
> You changed it to Title, but I corrected it for you.

Opps sorry about that @RandellDawson

**Comment by RandellDawson** [comment]
Thank you for your contribution to the page! 👍
We're happy to accept these changes, and look forward to future contributions. 🎉

**Pull request merged**
