### PR TITLE
Add another test case to WhereArtThou

### LINKED ISSUE #8673: Where art thou test cases
Challenge [Where art thou](https://www.freecodecamp.com/challenges/where-art-thou#?solution=function%20whereAreYou(collection%2C%20source)%20%7B%0A%20%20%2F%2F%20What's%20in%20a%20name%3F%0A%20%20var%20arr%20%3D%20%5B%5D%3B%0A%20%20%2F%2F%20Only%20change%20code%20below%20this%20line%0A%20%20for%20(var%20sKey%20in%20source)%20%7B%0A%20%20%7D%0A%20%20for%20(var%20objInColl%20in%20collection)%20%7B%0A%20%20%20%20if%20(collection%5BobjInColl%5D.hasOwnProperty(sKey)%20%26%26%20collection%5BobjInColl%5D%5BsKey%5D%20%3D%3D%3D%20source%5BsKey%5D)%20%7B%0A%20%20%20%20%20%20%20%20arr.push(collection%5BobjInColl%5D)%3B%0A%20%20%20%20%7D%0A%20%20%7D%0A%20%20%2F%2F%20Only%20change%20code%20above%20this%20line%0A%20%20return%20arr%3B%0A%7D%0A%0AwhereAreYou(%5B%7B%20%22a%22%3A%201%2C%20%22b%22%3A%202%20%7D%2C%20%7B%20%22a%22%3A%201%20%7D%2C%20%7B%20%22a%22%3A%201%2C%20%22b%22%3A%202%2C%20%22c%22%3A%202%20%7D%5D%2C%20%7B%20%22a%22%3A%201%2C%20%22b%22%3A%202%20%7D)%3B%0A) has an issue.
User Agent is: <code>Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/50.0.2661.102 Safari/537.36</code>.
Please describe how to reproduce this issue, and include links to screenshots if possible.

My code:
```javascript
function whereAreYou(collection, source) {
  // What's in a name?
  var arr = [];
  // Only change code below this line
  for (var sKey in source) {
  }
  for (var objInColl in collection) {
    if (collection[objInColl].hasOwnProperty(sKey) && collection[objInColl][sKey] === source[sKey]) {
        arr.push(collection[objInColl]);
    }
  }
  // Only change code above this line
  return arr;
}

whereAreYou([{ "a": 1, "b": 2 }, { "a": 1 }, { "a": 1, "b": 2, "c": 2 }], { "a": 1, "b": 2 });
// returns [{"a":1,"b":2},{"a":1,"b":2,"c":2}]

```

My stub code passes all the tests although it shouldn't.
Last two test should be modified, so they can't be passed by only checking with the last value of the `source` object.

### PR DESCRIPTION
**Pull request by MiloATH**
#### Pre-Submission Checklist

- [x] Your pull request targets the `staging` branch of FreeCodeCamp.
- [x] Branch starts with either `fix/`, `feature/`, or `translate/` (e.g. `fix/signin-issue`)
- [x] You have two commits since there was an update during QA.
- [ ] All new and existing tests pass the command `npm run test-challenges`. Use `git commit --amend` to amend any fixes.
#### Type of Change

- [x] Small bug fix (non-breaking change which fixes an issue)
#### Checklist:

- [ ] Tested changes locally.
- [x] Closes currently open issue: Closes #8673

### CODE REVIEW

**Comment by adamisntdead** [comment]
Looks good, but does it cover anything that wasn't covered before?
Or is there an issue that this is fixing?

**Comment by MiloATH** [comment]
The new test was a response to issue #8673. The problem was with the following code:
``` javascript
function whereAreYou(collection, source) {
  // What's in a name?
  var arr = [];
  // Only change code below this line
  for (var sKey in source) {
  }
  for (var objInColl in collection) {
    if (collection[objInColl].hasOwnProperty(sKey) && collection[objInColl][sKey] === source[sKey]) {
        arr.push(collection[objInColl]);
    }
  }
  // Only change code above this line
  return arr;
}

whereAreYou([{ "a": 1, "b": 2 }, { "a": 1 }, { "a": 1, "b": 2, "c": 2 }], { "a": 1, "b": 2 });
// returns [{"a":1,"b":2},{"a":1,"b":2,"c":2}]
```
This code passes all the current tests, but is incorrect code for the problem. This test cases would fail this submition.

**Comment by abhisekp** [comment]
@MiloATH Thanks for this :smiley: 

It would be really nice of you, if you could modify the property names `a`, `b`, `c` to something more appropriate and reasonable e.g. `bat`, `ball`, or something similar.
It was really a bad naming on my part. :pensive:

**Comment by abhisekp** [comment]
@MiloATH LOL. You literally made them `apple`, `bat` :smile: 

Please remove the emphasized part
> This changes a to apple, b to bat, and c to cookie. That way it is easier to understand. 
*This is in response to @abhisekp's comment.*

It's not good to keep that in history. The merge commit already specifies the PR number and someone who is looking for the reason behind the change may back trace and arrive at my comment :wink:

**Comment by abhisekp** [comment]
@MiloATH Thanks :relaxed:

**Comment by abhisekp** [comment]
Let there be two commits to make history. 

@MiloATH Please update the **Pre-Submission Checklist** (*optionally*) mentioning the reason.

**Comment by MiloATH** [comment]
Thanks. You are right.

**Comment by Bouncey** [comment]
## LGTM :+1:

Thanks for contributing :tada:

**Pull request merged**
