### PR TITLE
new Pair Code feature PR to ux-improvements instead of master

### PR DESCRIPTION
**Pull request by aldraco**
took out gitter and adding slack integration.

We are not able to embed a slack chat due to cross scripting restrictions from slack.

We could add the bot integration, but for now the user is able to add details and other users can see their slack handle to find them.

### CODE REVIEW

**Comment by aldraco** [comment]
Please let me know if the formatting is still off. I changed my settings and it looks okay on my end, but uploaded here looks like it's spacing funny again.

**Comment by MrRenter** [comment]
The pairWith.jade you removed the iframe for gitter. If you keep that iframe there you can replace the gitter url with https://freecode.slack.com/messages/@!{otherPersonsSlackHandleHere} and it will put them in a direct chat with that person.

**Comment by aldraco** [comment]
Sadly not. slack has prohibited cross-site scripting.

**Comment by MrRenter** [comment]
Just confirmed. We can however use that generated url as a link with a target="_blank" to open a new window. This will provide a simple QoL feature.

**Comment by terakilobyte** [comment]
Feedback:

This looks mostly *GREAT*! A few pointed areas of constructive criticism and some requests.

##### Request
I know I had you guys put this against ux-improvements but please re-submit against master. The reason for the past switch and the new switch is to get you guys on the latest code we are working on. Myself and Quincy have gone ahead and resolved the merge conflicts that were present against the most recent version of ux-improvements.

##### Feedback
*  When a user enters their slack handle, it should save. Currently it doesn't. Additionally, it needs to be elegantly called out that if they mistype their slack handle they can change their slack handle in their profile.

*  Speaking of the profile, the hash in front of the slack is a bit confusing. Please change it to an `@`.

*  When a user clicks the pair button, if they have not entered a slack username take them to their account page and use req.flash to show an error stating their slack username is required.

*  Instead of taking them to a view that shows the details of what the user wanted to pair on with any additional info, use a media object (see stories and comments for an example) that are clickable and take them directly into a slack conversation with the user.

*  Additionally, perhaps instead of asking them what they want to pair on, it would just find their current challenge (build this against master for sure, look in courseware.js for how to find a user's current challenge) and list that. Then it could be a toggle-able button.

*  Poll the slack api "users.list" once an hour and and if the user isn't online in slack they're removed automatically.

*  Poll users signed up for pair programming once an hour and show a popup to the user asking if they're still available to pair. Immediately remove any users that no longer have an active session, allow 5 minutes to respond to popup otherwise.

**Pull request closed without merging**
