### PR TITLE
nothing

### LINKED ISSUE #37988: Deprecated property grid-gap

### PR DESCRIPTION
**Pull request by SimonSiefke**

### CODE REVIEW

**Comment by RandellDawson** [comment]
The checkbox you did not check is there for a reason.  Please only make changes to challenge files of the same language on a single PR.  It makes the review much easier and faster.

You can revert the changes to the non-English files for this file and then make a separate PR for each of the other languages.  

Thank you. 

Thank you.

**Comment by SimonSiefke** [comment]
> Please only make changes to challenge files of the same language on a single PR. It makes the review much easier and faster.

I'm not sure but I guess that all the file rename changes (e.g. "Add Gaps faster with grid-gap.arabic.md" -> "Add Gaps faster with gap.arabic.md") would need to be in a single change to not break the build process with `css-grid/meta.json`?

In total that would be 7 PRs (arabic, chinese, english, portuguese, russian, spanish and the file rename changes) to change `grid-gap` to `gap`. I think it would be easier to do it all in one go (but also I'm kinda lazy and don't want to do 6 more PR's 😄).

Thoughts?

**Comment by raisedadead** [comment]
We recommend individual microscopic PRs.

> I think it would be easier to do it all in one go (but also I'm kinda lazy and don't want to do 6 more PR's 

We understand, and thank you for your efforts. But please note that most mods on the QA team are volunteers same as you, and it's of utmost important that we can respect everyones time.

Finally its not trivial to go thru 116 files at a go.

Also, I see your formatter is touching a lot of files that it should not be. I am blocking the merge for now to let you sort it out first.

**Comment by SimonSiefke** [comment]
Thanks. I still disagree, but I will update this PR to only change english files.

**Comment by raisedadead** [comment]
Thanks could you also update the PR to only make the intended changes and not touch the formatting.

**Comment by RandellDawson** [comment]
According to MDN:
>CSS Grid Layout initially defined the grid-gap property. This prefixed property is being replaced by gap. However, in order to support browsers that implemented grid-gap and not gap for grid, you will need to use the prefixed property as in the interactive example above.

It is not that it is deprecated because users must use the prefixed version to deal support Internet Explorer, some Edge browsers and all Safari browsers.  I think it is a bit premature to suggest this change.

**Comment by RandellDawson** [comment]
@SimonSiefke When you create an issue, you should typically let others respond to discuss whether or not a change is actually needed.  This will prevent you from spending the time to create a PR in case it is decided a change is not warranted or at least discuss what changes would be acceptable to the community. 

I have given my opinion here that we should not be making this change at this time.

**Comment by SimonSiefke** [comment]
> users must use the prefixed version to deal support Internet Explorer, some Edge browsers and all Safari browsers.

Source?

**Comment by RandellDawson** [comment]
> Source?

MDN.  Check it out for yourself.

**Comment by raisedadead** [comment]
> Source?

I would like to point you to your issue thread. The MDN quote, that you quoted yourself literally says this feature is "being replaced" and workarounds like 

> However, in order to support browsers that implemented grid-gap and not gap for grid, you will need to use the prefixed property as in the interactive example above.

need to be done for some browsers. Meaning you need to implement a API two ways. Its not generic, definitely not universal and hence not deprecated.

All this is from your quote from the official MDN.

We could go on about facts and semantics, but I think let's close this PR for now, wait if there is any interest on the reported issue and comeback with an improvement later.

**Comment by Mstava** [comment]
Hello, @raisedadead, @RandellDawson, @SimonSiefke is this still open to solve it or what?

**Comment by RandellDawson** [comment]
@Mstava This has been closed.

**Pull request closed without merging**
