### PR TITLE
feat: css photo gallery

### PR DESCRIPTION
**Pull request by naomi-lgbt**
Checklist:

- [X] I have read [freeCodeCamp's contribution guidelines](https://contribute.freecodecamp.org).
- [X] My pull request has a descriptive title (not a vague title like `Update index.md`)
- [X] My pull request targets the `main` branch of freeCodeCamp.
- [X] I have tested these changes either locally on my machine, or GitPod.

Closes #XXXXX

Starting to break this one down. It's rather short.

Some thoughts:
- The images won't work until I upload to the CDN. But prior to doing that:
- The images used all seem to advertise a non-existent web product. Not sure if there was a reason for selecting these, or if we want to go with some other image set.

### CODE REVIEW

**Review by ShaunSHamilton — CHANGES_REQUESTED** [review]
Nice job with this, Nich.

One major, highly-recommended suggestion. Otherwise, I am really glad this is not 100 steps 😅

**Comment by scissorsneedfoodtoo** [comment]
Just finished going through this project and everything looks good overall. Just noticed a minor typo in the `title` element of some seed code.

Otherwise, great info on Flexbox here. All of the descriptions are succinct, but very detailed.

I remember having a tough time coming up with ways to extend this project. If I remember my though process correctly, here are a few things we could consider doing:

* Start off with one image and cover how to center it horizontally and vertically
* Have learners add a row of images
* Cover other values for `justify-content` and `align-items` like `flex-start`, `flex-end`, `space-around`, and so on
* Introduce other values for `flex-direction` like `row-reverse`, `column`, etc.
* Use the `order` property to move a featured photo to a certain position
* Use the `flex-grow` and `flex-shrink` properties to change the size of certain photos
* Use `gap`, `row-gap`, `column-gap` to adjust the spacing between images. Explain that these properties only affect spacing between flex items, and not like padding which also works on the outer edges of the container

**Review by scissorsneedfoodtoo — COMMENTED** [review]
Adding more review suggestions to make things a bit easier.

**Review by ShaunSHamilton — DISMISSED** [review]
This seems to look good to me 👍 

Nice one, Nuch.

**Review by moT01 — DISMISSED** [review]
This project is pretty slick :+1: I left a couple fairly minor suggestions - but they aren't necessary to add. I would be fine going with this as-is.

Other thoughts:
Steps 14 and 15 didn't have any visible changes for me - they're the justify-content and align-items steps.

I like a short project mixed in - makes it quick and productive feeling. It would have been nice to have a little more on the parent-child relationship in there though.

Nice work @nhcarrigan :tada:

**Review by moT01 — DISMISSED** [review]
LGTM 🎉 

Wanna give this one more quick look @ShaunSHamilton 😄

**Review by ShaunSHamilton — APPROVED** [review]
I just spotted one tiny typo, and committed a change.

This LGTM 👍 

@moT01 Merge, if happy.

**Review by moT01 — APPROVED** [review]
LGTM 🎉

**Pull request merged**
