### PR TITLE
Fix css #two test color set to 'blue' to match instructions so user can pass challenge

### PR DESCRIPTION
**Pull request by bowen-anth**
…pass the challenge

Checklist:

- [x] I have read and followed the [contribution guidelines](https://contribute.freecodecamp.org).
- [x] I have read and followed the [how to open a pull request guide](https://contribute.freecodecamp.org/#/how-to-open-a-pull-request).
- [x] My pull request targets the `main` branch of freeCodeCamp.
- [x] I have tested these changes either locally on my machine, or GitPod.

Closes #XXXXX

### CODE REVIEW

**Comment by bowen-anth** [comment]
Fix css #two test color set to 'blue' to match instructions so user can pass challenge. I was only able to pass the challenge using the color '#0000ff' for the #two css selector before. The instructions say to use color names, in this case 'blue'.

**Review by bowen-anth — COMMENTED** [review]
Fix css #two selector color set to 'blue' to match instructions so user can pass challenge. It would only pass if I put in '#0000ff' before.

**Review by huyenltnguyen — COMMENTED** [review]
Hi @bowen-anth, is there an issue thread for this change? Please if there isn't.

Curriculum changes impact a lot of learners, so we want to err on the side of caution and have the issue go through the triage process.

**Comment by bowen-anth** [comment]
I can only pass the challenge with: #two {
  color: #0000FF;
  font-size: 36px;
}

Putting 'blue' in for the color doesn't work. I was stuck here until I
looked at the repot file.

You can check it with the link below. You just have to do the id selector
on the appropriate element and ignore the other challenge parts. It doesn't
pass the check for the second element with 'blue' but will with '#0000ff'.

https://www.freecodecamp.org/learn/the-odin-project/top-learn-css-foundations-projects/css-foundations-exercise-b

**Pull request closed without merging**
