### PR TITLE
Added Git Quiz

### PR DESCRIPTION
**Pull request by farihaNaqvi**
Git quiz #56235

Checklist:

- [x] I have read and followed the [contribution guidelines](https://contribute.freecodecamp.org).
- [x] I have read and followed the [how to open a pull request guide](https://contribute.freecodecamp.org/how-to-open-a-pull-request/).
- [x] My pull request targets the `main` branch of freeCodeCamp.
- [x] I have tested these changes either locally on my machine, or GitPod.

This is not spam.
I developed the questions for the Git quiz based on the documentation covering the relevant topics.
If you have any questions feel free to ask.

### CODE REVIEW

**Comment by farihaNaqvi** [comment]
I would be grateful if you could let me know where i am missing?

**Comment by Sembauke** [comment]
Hey @farihaNaqvi,

We are not yet accepting Hacktoberfest pull-requests before the kick-off event in our Discord.

**Comment by ilenia-magoni** [comment]
I'm closing this anyway, if you want to contribute to the quizzes please follow proper procedure.

**Comment by farihaNaqvi** [comment]
Could you please remove the spam tag as this is my first time in hacktoberfest. Please

**Comment by ilenia-magoni** [comment]
@farihaNaqvi we can think about it, we need to see you contributing following the guidelines for that.

**Comment by farihaNaqvi** [comment]
@ilenia-magoni if you don't mind can you please only guide me on how i request for assign on issue for that git quiz.
Thank you

**Comment by ilenia-magoni** [comment]
can you please read everything that is written in the issue, they are not open yet

**Pull request closed without merging**
