### PR TITLE
Fix typo in 'integer' word

### PR DESCRIPTION
**Pull request by karuppiah7890**
Checklist:

- [x] I have read [freeCodeCamp's contribution guidelines](https://contribute.freecodecamp.org).
- [x] My pull request has a descriptive title (not a vague title like `Update index.md`)
- [x] My pull request targets the `master` branch of freeCodeCamp.
- [x] All the files I changed are in the same world language, for example: only English changes, or only Chinese changes, etc.

### CODE REVIEW

**Review by MrHeer — DISMISSED** [review]

**Review by RandellDawson — DISMISSED** [review]
Thank you for find this typo.

**Review by IhostVlad — DISMISSED** [review]

**Review by naomi-lgbt — DISMISSED** [review]
Thanks for catching this! 🙂 LGTM!

**Comment by RandellDawson** [comment]
@raisedadead The `Travis CI - Pull Request Expected — Waiting for status to be reported` had been going for over several hours , so I opened/closed the PR and it still seems to be stuck.  Is this another case of a user being blocked by Travis?

**Comment by karuppiah7890** [comment]
Oops. I tried doing a force push with different commit sha to retrigger the pipeline, but no, didn't work. I have dismissed the reviews too. Sorry! 🙈

**Comment by raisedadead** [comment]
> Is this another case of a user being blocked by Travis?

I recommend reaching out to Travis Support.

**Review by thecodingaviator — APPROVED** [review]

**Comment by Twaha-Rahman** [comment]
> > Is this another case of a user being blocked by Travis?
> 
> I recommend reaching out to Travis Support.

@raisedadead Looks like the Travis has finished it's job finally. Are we waiting for anything here?

**Review by RandellDawson — APPROVED** [review]

**Comment by RandellDawson** [comment]
Thank you for your contribution to the page! 👍
We're happy to accept these changes, and look forward to future contributions. 🎉

**Pull request merged**
