### PR TITLE
Added explanation of technical term

### PR DESCRIPTION
**Pull request by Sebarbossus**
- [x] I have read [freeCodeCamp's contribution guidelines](https://github.com/freeCodeCamp/freeCodeCamp/blob/master/CONTRIBUTING.md).
- [x] My pull request has a descriptive title (not a vague title like `Update index.md`)
- [x] My pull request targets the `master` branch of freeCodeCamp.
- [x] None of my changes are plagiarized from another source without proper attribution.
- [x] My article does not contain shortened URLs or affiliate links.

If your pull request closes a GitHub issue, replace the XXXXX below with the issue number.

Closes #XXXXX

### CODE REVIEW

**Comment by RandellDawson** [comment]
**Hi,**

**Thanks for this pull request (PR).**

**Unfortunately, we are marking this PR invalid for hacktoberfest. We believe it does not follow the recommended guidelines:**

> ### Quality Standards 
> In line with Hacktoberfest value `#2` (Quantity is fun, Quality is key), we have provided examples of the quality standards we encourage. This applies mainly to beginners.
>
> * PRs that are automated e.g. scripted opening PRs to remove whitespace / optimize images.
> * PRs that are disruptive e.g. taking someone else's branch/commits and making a PR.
> * PRs that are regarded by a project maintainer as a hindrance vs. helping.
> * Something that's clearly an attempt to simply +1 your PR count for October.

Learn more at https://hacktoberfest.digitalocean.com/details

**Comment by Sebarbossus** [comment]
But why?! I just added information. That should help people learning at freeCodeCamp. By the way, the white spaces were removed automatically by GitHub, not me.

**Comment by RandellDawson** [comment]
Your PR was marked invalid almost automatically, because even though you checked box #2 (shown below), you did not actual do what it stated.
```
 My pull request has a descriptive title (not a vague title like Update index.md)
```
Commits should have short but useful descriptions of what you are doing. It helps us in the review process. With the sheer volume of PRs we are getting right now, we focus on the ones where the contributor has made the effort to follow the process. You have no idea how many of the "update index.md" are just a bot making a one character change.

Just update your PR title and tag me and I will review it personally.

**Comment by Sebarbossus** [comment]
Alright, yeah, I understand.
I just had the question because I thought it was about the content that I added and not about the title.
I just left the default title suggested by GitHub, my bad :) .
I am gonna go over the PR again, greetings.

**Pull request closed without merging**
