### PR TITLE
feat(challenges): Added pong game as a take home project

### PR DESCRIPTION
**Pull request by satyamchaudharydev**
#### Pre-Submission Checklist

- [x] Your pull request targets the `staging` branch of freeCodeCamp.
- [x] Branch starts with either `fix/`, `feature/`, or `translate/` (e.g. `fix/signin-issue`)
- [x] You have only one commit (if not, [squash](http://forum.freecodecamp.org/t/how-to-squash-multiple-commits-into-one-with-git/13231) them into one commit).
- [x] All new and existing tests pass the command `npm test`. Use `git commit --amend` to amend any fixes.

#### Type of Change

- [ ] Small bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds new functionality)
- [x] Breaking change (fix or feature that would change existing functionality)
- [ ] Add new translation (feature adding new translations)

#### Checklist:

- [x] Tested changes locally.
- [ ] Addressed currently open issue (replace XXXXX with an issue no in next line)

#### Description

I have followed your feedback. I have also created a new ObjectId. (Do you also need to create a new challengeSeed?).
Thank you guys for your feedback. 😄

### CODE REVIEW

**Comment by raisedadead** [comment]
Hi @satyamchaudharydev thanks a for the pull request, just noticed that the commit came from a different user account (`@sanatankc`) than yours, do you mind confirming that its the case?

This can happen if the commit authors user.email is not on their GitHub account.

**Comment by satyamchaudharydev** [comment]
Oh, he is my brother. I was committing from his computer.

**Comment by raisedadead** [comment]
> Oh, he is my brother. I was committing from his computer.

Ah! That makes sense. :sweat_smile: !

**Comment by QuincyLarson** [comment]
@satyamchaudharydev Awesome! This looks great! Thank you so much for creating this challenge. And congratulations on your first open source contribution to the freeCodeCamp community!

**Comment by satyamchaudharydev** [comment]
Hey @QuincyLarson, I have a question that on each project on the Freecodecamp website. Have a   video section related the project.

**Comment by raisedadead** [comment]
> I have a question that on each project on the Freecodecamp website. Have a video section related that project.

Its a little unclear what your query is?

Do you mean that we should have a video of the project as an intro? If yes, we did that before, and they quickly went outdated, whenever for example the user stories changed.

**Pull request merged**
