### PR TITLE
docs: add IntelliJ editor set up hint

### LINKED ISSUE #42319: Add section for configuring IntelliJ for running project locally in docs
**Description:**
I use IntelliJ Idea on Windows 10 with WSL2 to run the project locally.

The specific problem I ran in to was running tests via the IDE instead of the command line. I had to configure IntelliJ to use the version of Node I have installed in WSL2.

This is the error I encountered when trying to run the tests via the IDE:

`CMD.EXE was started with the above path as the current directory.
UNC paths are not supported.  Defaulting to Windows directory.
'jest' is not recognized as an internal or external command,
operable program or batch file.`

**Recommended fix, suggestions:**

I think it would be worth while to add a small section to the WSL set up doc (https://contribute.freecodecamp.org/#/how-to-setup-wsl) for anyone using IntelliJ products.

### PR DESCRIPTION
**Pull request by Dripcoding**
_Checklist:_

- [x] I have read [freeCodeCamp's contribution guidelines](https://contribute.freecodecamp.org).
- [x] My pull request has a descriptive title (not a vague title like `Update index.md`)
- [x] My pull request targets the `main` branch of freeCodeCamp.
- [x] I have tested these changes either locally on my machine, or GitPod.

I have previewed changes to the markdown file and tested these changes locally.

Closes #42319

### CODE REVIEW

**Review by Sembauke — APPROVED** [review]
Hey @Dripcoding,

Thank you for your contribution to the page! 👍
We are happy to accept these changes and look forward to future contributions. 🎉

**Review by ShaunSHamilton — APPROVED** [review]
This LGTM 👍

**Comment by ShaunSHamilton** [comment]
Congrats on your first pull request (PR)! 🎉

Thank you, for your contribution to the page! 👍
We are happy to accept these changes and look forward to future contributions. 📝

**Comment by Dripcoding** [comment]
Thanks all! I look forward to making more contributions 😄

**Pull request merged**
