### PR TITLE
fix: remove stray files

### PR DESCRIPTION
**Pull request by naomi-lgbt**
Checklist:

- [X] I have read [freeCodeCamp's contribution guidelines](https://contribute.freecodecamp.org).
- [X] My pull request has a descriptive title (not a vague title like `Update index.md`)
- [X] My pull request targets the `main` branch of freeCodeCamp.
- [X] I have tested these changes either locally on my machine, or GitPod.

Closes #XXXXX

I am not sure how these got left behind, or why the workflows did not remove them.

But these are unused and the presence is causing build errors for me locally. @moT01 these seem to be duplicates (comparing by ID) of the `build a kitty ipsum translator` file?

### CODE REVIEW

**Review by moT01 — APPROVED** [review]
In [a PR](https://github.com/freeCodeCamp/freeCodeCamp/pull/42885/files), I renamed only the English version of this file - I thought the others would be adjusted in the Crowdin process or something for some reason - Then, I made [another PR](https://github.com/freeCodeCamp/freeCodeCamp/pull/43349) to fix the rest of the languages and found that two of the languages (the ones on this PR) did get the new file from Crowdin, so I only adjust the others. Didn't see that these old files didn't get deleted.

LGTM 🎉

**Comment by nhcarrigan** [comment]
>  I thought the others would be adjusted in the Crowdin process or something for some reason

They are *supposed* to be fixed. Will investigate.

**Comment by moT01** [comment]
Ilenia pointed that [the instructions](https://contribute.freecodecamp.org/#/curriculum-file-structure?id=renaming-a-challenge) say to rename all languages - I only renamed English on that initial PR.

**Comment by nhcarrigan** [comment]
Ah I think I know the issue.

The workflow deletes the file from *Crowdin*, but not from the existing translations on the repository

**Review by majestic-owl448 — APPROVED** [review]

**Review by raisedadead — APPROVED** [review]

**Pull request merged**
