### PR TITLE
Make classic/SidePanel scroll to top on update

### LINKED ISSUE #13225: [beta][UX] New challenges should include a page/anchor jump
There is not enough indication that a change has occurred, after completing a challenge.

current challenge:
screen shot 2017-02-07 at 10 31 57 am

next challenge:
screen shot 2017-02-07 at 10 32 07 am

I suggest adding a **page jump** in the instructions panel, so that students can see a new Title and introduction for the challenge.

### LINKED ISSUE #13726: [Beta] Basic HTML and HTML5: Bad Scroll behavior on insctrucions
#### Challenge Name

Basic HTML and HTML5: Create a Bulleted Unordered List (But occurs in any challenge on HTML course)

#### Issue Description

Every time that you submit a challenge, the next challenge appear with the instructions scrolled. The link below points to the exact situation. So, you need to scroll up every time.

#### Browser Information

* Browser Name, Version: Chrome Version 56.0.2924.87
* Operating System: Windows 8
* Mobile, Desktop, or Tablet: Desktop

#### Your Code

```js



```
#### Screenshot

https://snag.gy/4tzmCe.jpg

### PR DESCRIPTION
**Pull request by Bouncey**
#### Pre-Submission Checklist

- [x] Your pull request targets the `staging` branch of freeCodeCamp.
- [x] Branch starts with either `fix/`, `feature/`, or `translate/` (e.g. `fix/signin-issue`)
- [x] You have only one commit (if not, [squash](http://forum.freecodecamp.com/t/how-to-squash-multiple-commits-into-one-with-git/13231) them into one commit).
- [x] All new and existing tests pass the command `npm test`. Use `git commit --amend` to amend any fixes.

#### Type of Change

- [x] Small bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds new functionality)
- [ ] Breaking change (fix or feature that would change existing functionality)
- [ ] Add new translation (feature adding new translations)

#### Checklist:

- [x] Tested changes locally.
- [x] Closes currently open issue (replace XXXX with an issue no): Closes #13726 Closes #13225

### CODE REVIEW

**Comment by dhcodes** [comment]
@Bouncey does this PR fix these issues? https://github.com/freeCodeCamp/freeCodeCamp/pull/15607

I didn't mean to steal it; i hadn't seen this PR when solving the other issue mentioning this.

**Comment by systimotic** [comment]
@dhcodes I just tested this on beta.freecodecamp.com and it appears I can still reproduce the issue #15607 attempted to fix. I haven't tested this PR yet.

**Comment by dhcodes** [comment]
@systimotic I'm not sure it's been applied to beta. I don't know the last time beta has been updated from staging.

**Comment by systimotic** [comment]
@dhcodes It has the new layout, which was merged after your changes, so your changes should be on there.

**Comment by dhcodes** [comment]
@systimotic hmm... working on beta in Chrome here and locally on Firefox. I didn't test it across the board. If you choose a challenge on the map, scroll down the instructions, then click a different challenge, the new challenge is reset to top.

**Comment by systimotic** [comment]
@dhcodes Hmmm, now it does seem to work... 😕 Not sure what happened previously that made it so that it didn't work.

That makes me curious, why does it work? How does `window` only refer to the description? The map doesn't scroll.

Given that your solution appears to work, should we use that, or should we use this instead? I'm thinking using `componentWillUpdate` and specifically scrolling the description might be more reliable.

**Comment by QuincyLarson** [comment]
@systimotic @dhcodes What's the status on this? Is there anything left to fix? If not, would one of you be interested in doing the honors and QA/merging this?

**Comment by QuincyLarson** [comment]
@systimotic @dhcodes I know you're working on Guide - just wanted to bump this so it doesn't get too stale. 🍞  Any updates?

**Comment by dhcodes** [comment]
@systimotic I don't really have a preference which we use, but mine was merged in #15607 so we'd need to unmerge it to go with this one. It's @Bouncey's PR that I accidentally tread on. I'm fine either way so I'll let you make the call and the updates.

**Comment by QuincyLarson** [comment]
@Bouncey Since this does the exact same thing that @dhcodes's already-merged PR does, I'm closing it. Thanks anyway, though. We can try to avoid this situation in the future by calling dibs on a given issue before starting a PR.

**Pull request closed without merging**
