### PR TITLE
fix: Add Dynamic Programming Quiz Questions (#56221)

### PR DESCRIPTION
**Pull request by MiyuruAmarasiri**
Checklist:

- [ ] I have read and followed the [contribution guidelines](https://contribute.freecodecamp.org).
- [ ] I have read and followed the [how to open a pull request guide](https://contribute.freecodecamp.org/how-to-open-a-pull-request/).
- [x] My pull request targets the `main` branch of freeCodeCamp.
- [x] I have tested these changes either locally on my machine, or GitPod.

Closes #XXXXX

### CODE REVIEW

**Comment by jeremylt** [comment]
Your pull request does not follow the contribution guidelines or how to open a pull request guide. Please read and follow those instructions.

**Review by MiyuruAmarasiri — COMMENTED** [review]
I follow the guidelines. please cheack what is issue in my pull request

**Comment by jeremylt** [comment]
You did not follow the guide
https://contribute.freecodecamp.org/how-to-open-a-pull-request/

**Review by MiyuruAmarasiri — COMMENTED** [review]
change the branch main to test

**Comment by jeremylt** [comment]
Please read 
https://contribute.freecodecamp.org/how-to-open-a-pull-request/

**Comment by naomi-lgbt** [comment]
Closing this PR in favour of #56430 which uses a dedicated branch.

**Pull request closed without merging**
