### PR TITLE
fix(curriculum): var keyword to global-scope-and-functions

### PR DESCRIPTION
**Pull request by ivpavici**
Added the `var` keyword in global-scope-and-functions challenge instructions to avoid confusion

Checklist:

- [x] I have read [freeCodeCamp's contribution guidelines](https://contribute.freecodecamp.org).
- [x] My pull request has a descriptive title (not a vague title like `Update index.md`)
- [x] My pull request targets the `main` branch of freeCodeCamp.
- [x] I have tested these changes either locally on my machine, or GitPod.

Closes #XXXXX

### CODE REVIEW

**Comment by ieahleen** [comment]
have you found cases of users reporting this as a source of confusion?

**Comment by ivpavici** [comment]
Hello! Well, I've made the mistake at first of using the `var` keyword inside of the function :) 
I know that in the text it says: _You should always declare your variables with let or const._ ...but I did most of my JS programing before those keywords existed, and `var` got stuck in my muscle memory :)

**Review by majestic-owl448 — APPROVED** [review]
LGTM :+1:

**Review by jdwilkin4 — APPROVED** [review]
LGTM! 👍

**Comment by jdwilkin4** [comment]
Congrats @ivpavici on your first merged PR to the freeCodeCamp repo. 
We look forward to future contributions.

**Pull request merged**
