### PR TITLE
fix(curriculum): add test for multiple ol elements

### LINKED ISSUE #48940: Cat Photos Step 27 allows wrong code to pass
### Describe the Issue

This step is allowing code that does not meet the requirements to pass.

### Affected Page

https://www.freecodecamp.org/learn/2022/responsive-web-design/learn-html-by-building-a-cat-photo-app/step-27

### Your code

This passes:

```
<h3>Top 3 things cats hate:</h3>
<ol><li>flea treatment</li></ol>
<ol><li>thunder</li></ol>
<ol><li>other cats</li></ol>
```

### Expected behavior

Step should not allow multiple ordered lists to pass. Should enforce that only one ordered list is used with three list items.

### Screenshots

_No response_

### System

- Device: Desktop
- OS: Linux Fedora 36
- Browser: Firefox
- Version: 108

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by a2937**
Checklist:

- [X] I have read and followed the [contribution guidelines](https://contribute.freecodecamp.org).
- [X] I have read and followed the [how to open a pull request guide](https://contribute.freecodecamp.org/#/how-to-open-a-pull-request).
- [X] My pull request targets the `main` branch of freeCodeCamp.
- [X] I have tested these changes either locally on my machine, or GitPod.

Closes #48940

[Screenshot](https://imgur.com/a/RpWPqIi)

### CODE REVIEW

**Comment by a2937** [comment]
How do I convert it a draft?

**Comment by a2937** [comment]
I just noticed a small flaw in the way I wrote the check. It does not even allow proper code to pass.

**Comment by a2937** [comment]
Why are these tests failing? I thought I had everything working now.

**Comment by gikf** [comment]
> Why are these tests failing? I thought I had everything working now.

Looks like some unrelated glitch, I've started failed checks again.

**Review by gikf — APPROVED** [review]
LGTM :+1:

**Review by Sembauke — APPROVED** [review]

**Pull request merged**
