### PR TITLE
chore(cypress): `email-change.js` to ts 

### PR DESCRIPTION
**Pull request by a2937**
Checklist:

- [X] I have read and followed the [contribution guidelines](https://contribute.freecodecamp.org).
- [X] I have read and followed the [how to open a pull request guide](https://contribute.freecodecamp.org/#/how-to-open-a-pull-request).
- [X] My pull request targets the `main` branch of freeCodeCamp.
- [X] I have tested these changes either locally on my machine, or GitPod.

Related to #48753

I am running into errors like

 `Failed prop type: Invalid prop `bsStyle` of value `errors` supplied to `Alert`, expected one of ["success","warning","danger","info"].`

and 

`Warning: Invalid DOM property `tabindex`. Did you mean `tabIndex`?`

### CODE REVIEW

**Comment by Nirajn2311** [comment]
Hi, could you post a screenshot of the errors? The TS spec file ran on my system without any errors.

**Comment by a2937** [comment]
Tab Index problem 



BsStyle issue 


There might be a fairly large possibility that a couple of dependencies may not exist on my system locally.

**Comment by Nirajn2311** [comment]
Do you have the mailhog server running?

**Comment by a2937** [comment]
I unfortunately did not. After running the test with the mail server , all tests complete successfully. However I still get that warning about the tabIndex property name in the background.  I've noticed both "tabIndex" and "tabindex" be used in the codebase. I'm assuming for a BlockSaveButton element somewhere, it is using the incorrect one. Should I try to figure it out and apply the fix to this PR?

**Comment by Nirajn2311** [comment]
> Should I try to figure it out and apply the fix to this PR?

It would be better if you made a new PR as its out of scope of this PR. Remember to reference your comment in that PRs description.

**Review by Nirajn2311 — APPROVED** [review]

**Review by ShaunSHamilton — APPROVED** [review]
Thank you for your contribution to the page! 👍
We are happy to accept these changes and look forward to future contributions. 🎉

**Pull request merged**
