### PR TITLE
Updates create issue button in bug modal to direct user to forum

### LINKED ISSUE #14934: Point bug modal to forum instead of github issue tracker
When a user creates a bug report, that should be done in the forum. We will use that forum as a staging place for issues. Forums are more conducive to discussion. There on the forum moderators can then escalate issues.

This needs to happen on both staging and on backup/master

### PR DESCRIPTION
**Pull request by padulam**
#### Pre-Submission Checklist

- [x] Your pull request targets the `staging` branch of freeCodeCamp.
- [x] Branch starts with either `fix/`, `feature/`, or `translate/` (e.g. `fix/signin-issue`)
- [x] You have only one commit (if not, [squash](http://forum.freecodecamp.com/t/how-to-squash-multiple-commits-into-one-with-git/13231) them into one commit).
- [x] All new and existing tests pass the command `npm test`. Use `git commit --amend` to amend any fixes.

#### Type of Change

- [ ] Small bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds new functionality)
- [x] Breaking change (fix or feature that would change existing functionality)
- [ ] Add new translation (feature adding new translations)

#### Checklist:

- [x] Tested changes locally.
- [x] Closes currently open issue (replace XXXX with an issue no): Closes #14934 

#### Description

Updates the bug modal to point to the freeCodeCamp forum when logging issues. Removes instances of the 'createIssue' code that previously allowed the user to create an issue in the GitHub issue tracker.

### CODE REVIEW

**Comment by raisedadead** [comment]
Could we also check and add a template just like we have for the issue tracker? I am pretty certain this could possibly be done via markdown syntax?

**Comment by padulam** [comment]
@raisedadead I wasn't sure this was possible when I originally worked on this request, but after some additional research it appears you can do this with the discourse forum api. I'll get to work on updating this request. Thanks!

**Review by raisedadead — CHANGES_REQUESTED** [review]
Thanks for the changes @padulam, here are a few things that we would want to see in this PR before its ready for deployment.

1. Please add a `title` field to the query, that takes the challenge name and creates a valid title:
`https://forum.freecodecamp.com/new-topic?category=General&title=XXXX&body=`
  Where XXXX is a string like "Need assistance in `<challenge name>`"

2. The conditional statement for opening up a search issue should be redirected to forum, again this can be done via the API just like the create issue.

3. The code from this block 
https://github.com/freeCodeCamp/freeCodeCamp/pull/14979/files#diff-191c615c9144c0afc21b9b0bcc66ce2eR49
 needs to be wrapped correctly in the conditional, because this is causing to open two tabs on the browser.

4. Finally we need to update the template of the issue itself for better alignment to the Github issue template here:
https://raw.githubusercontent.com/freeCodeCamp/freeCodeCamp/staging/.github/ISSUE_TEMPLATE.md

**Comment by padulam** [comment]
Thanks @raisedadead! I'll get to work on these changes.

**Comment by padulam** [comment]
@raisedadead One note about the updates I made: I replaced the reference to the challenge property of the challengeApp object with a reference to the legacyKey property. I felt that using the challenge name without hyphens made more sense for what it's being used for in this code.

**Review by raisedadead — APPROVED** [review]

**Comment by raisedadead** [comment]
@padulam I have made some minor changes to your pull request:

1. I have updated the search string.
2. I have also done a bit of formatting to the issue template.

This looks really good! Thanks a lot for having made this contribution.

We will merge this soon!

**Comment by raisedadead** [comment]
@BerkeleyTrue this is good to go. Please merge if you are okay with the changes. 
@padulam Once this is merged we would want this to be ported to `backup/master` branch as well.

/cc @m-henderson Just to give you a head start that we are moving the issue creation from the platform to be redirected to the forum.

May be we could explore adding a plugin or workflow to import legitimate bugs to tracker from forum via forum mods. That can be a separate activity of its own.

**Comment by m-henderson** [comment]
Sounds good, I think that would be a great idea!

**Review by BerkeleyTrue — APPROVED** [review]

**Comment by BerkeleyTrue** [comment]
Code LGTM

**Comment by raisedadead** [comment]
@BerkeleyTrue Thanks for merging this. 

@padulam Thanks for working on this.
Could you please check and create a PR against the `backup/master` as well?

**Comment by padulam** [comment]
@raisedadead Sure. I should have something ready later tonight.

**Pull request merged**
