### PR TITLE
fix: add legacy project map

### LINKED ISSUE #17300: Certification section of portfolio should show legacy certifications, too
profile___freecodecamp

### LINKED ISSUE #18253: Issue after claiming full stack certificate - legacy full stack shows error
I recently claimed my full stack certificate after having all the other certificates (including the 3 non full stack legacy ones) - When I claimed the cert, it showed up on my profile in two spots, the legacy area and the new area - so my profile looks like this...

screen shot 2018-10-04 at 7 46 09 am

I'm not sure if that's intentional or not but the issue is that when I try to open the legacy full stack cert it does not open and I get a flash message that looks like this...

screen shot 2018-09-29 at 11 54 37 am

The one at the top opens as expected 
https://www.freecodecamp.org/mot01 <= my profile if you want to see the problem

### LINKED ISSUE #35410: Legacy Certification Settings Section to be implemented
Need to port over the legacy certificate section on Settings page from the production

### PR DESCRIPTION
**Pull request by ahmaxed**
Closes #35410
Closes #17300
Closes #18253

### CODE REVIEW

**Comment by raisedadead** [comment]
@ahmadabdolsaheb when you get a minute, it would be awesome if you add any open issues and pull-requests on this to the OP (with closes tag, or suitable). We should track all of these and close when this lands.

**Review by raisedadead — CHANGES_REQUESTED** [review]
Let's add some tests to make this solid.

**Comment by ahmadabdolsaheb** [comment]
@raisedadead, what kind of tests. do you mean ui tests like snapshots? could you give me an example of what you have in mind from our codebase?

**Review by raisedadead — APPROVED** [review]

**Review by moT01 — COMMENTED** [review]
I had a discussion with @ahmadabdolsaheb about what the expected output was supposed to be...
[x] - full stack certs are not claimable - fixed
[x] - legacy certs are not claimable - fixed
[x] - new full stack gets applied automatically - fixed
[x] - legacy full stack cert is removed - fixed
Screen Shot 2019-05-07 at 8 59 12 AM

**The issues listed in the PR...**
https://github.com/freeCodeCamp/freeCodeCamp/issues/35410 - Not sure exactly what is meant in this issue - probably best for @raisedadead to take a look at this one.

https://github.com/freeCodeCamp/freeCodeCamp/issues/17300 - The first part of the issue looks fixed - the legacy certs do show up. But there does appear to be an issue with the second part - I reset my local account and the cert area still shows up in my profile...
Screen Shot 2019-05-07 at 9 15 47 AM


https://github.com/freeCodeCamp/freeCodeCamp/issues/18253 - It looks like the PR fixes this for someone who gets the full stack cert (legacy full stack doesn't show up) - not positive if it will remove the cert for someone who already has it - I have to assume it will, but I could not test it.

Overall it looks real good @ahmadabdolsaheb!

**Pull request merged**
