### PR TITLE
add text explaining order of operations. add a video tutorial and cha…

### PR DESCRIPTION
**Pull request by karlwil1**
…nged title

Changed the title from order of operations Pemdas to order of operations as that is not the only acronym for order of operations.

- [x] I have read [freeCodeCamp's contribution guidelines](https://github.com/freeCodeCamp/freeCodeCamp/blob/master/CONTRIBUTING.md).
- [x] My pull request has a descriptive title (not a vague title like `Update index.md`)
- [x] My pull request targets the `master` branch of freeCodeCamp.
- [x] None of my changes are plagiarized from another source without proper attribution.
- [x] My article does not contain shortened URLs or affiliate links.

If your pull request closes a GitHub issue, replace the XXXXX below with the issue number.

Closes #XXXXX

### CODE REVIEW

**Comment by karlwil1** [comment]
;D

**Comment by karlwil1** [comment]
;D

**Comment by thecodingaviator** [comment]
You'll also need to rename the file to reflect your change

**Comment by RandellDawson** [comment]
This PR has gone stale.

**Comment by thecodingaviator** [comment]
Hi,

As there has been no response from your end for a while, we are closing this PR.

Feel free to request this PR to be reopened, if you still wish to make the changes you originally added.  Also, remember to update your fork, so you have the latest version of master in case it has changed significantly.

Happy Coding! ✈️

**Pull request closed without merging**
