### PR TITLE
fix(learn): Disable auto focus on editor

### LINKED ISSUE #37146: [Beta] Each time the n or p Hotkey is used, the editor refocuses on Windows
**Problem:** When tested on Chrome and Firefox (on Windows) and using the `p` or `n` hotkeys, we are supposed to be able to navigate to the next and previous lessons without the editor going back into focus while in the escaped mode. However, on the beta site, I have to keep escaping the editor every single time I click the `p` or `n` once I first escape the editor. The original navigation buttons that were removed in favor of the hot keys did not do this.

### PR DESCRIPTION
**Pull request by ghost**
- [x] I have read [freeCodeCamp's contribution guidelines](https://github.com/freeCodeCamp/freeCodeCamp/blob/master/CONTRIBUTING.md).
- [x] My pull request has a descriptive title (not a vague title like `Update index.md`)
- [x] My pull request targets the `master` branch of freeCodeCamp.
- [x] None of my changes are plagiarized from another source without proper attribution.
- [x] All the files I changed are in the same world language (for example: only English changes, or only Chinese changes, etc.)
- [x] My changes do not use shortened URLs or affiliate links.

Closes #37146 by disabling auto focus on editor.

### CODE REVIEW

**Review by thecodingaviator — APPROVED** [review]
Although this fixes the issue at hand, now the autofocus is obviously directly not on the editor.

**Review by raisedadead — CHANGES_REQUESTED** [review]
Do not ship as is

**Comment by vkWeb** [comment]
@rickysyamsi @thecodingaviator This isn't the right approach in my personal opinion.

**Comment by raisedadead** [comment]
Hi @vkWeb thanks for your comments.

> This isn't the right approach in my personal opinion.

Unless you have a working pull-request or a solution to suggest, lets avoid the noise on the threads. We are in the midst of rapid iterations.

**Comment by rickysyamsi** [comment]
@vkWeb I agree that this is not the best possible approach. I also have commented a solution suggestion on #37146. Can you please give me some feedback on it? Also calling @raisedadead @thecodingaviator

**Comment by vkWeb** [comment]
>Unless you have a working pull-request or a solution to suggest, lets avoid the noise on the threads. We are in the midst of rapid iterations.

I will keep this in mind. I'm sorry.

**Comment by raisedadead** [comment]
No worries @vkWeb we understand you want to help. Thanks for your contributions.

Closing as discussed.

**Pull request closed without merging**
