### PR TITLE
fix(learn): Added test for edge case

### LINKED ISSUE #39320: False Positive: Confirm The Ending Challenge
**Describe your problem and how to reproduce it:**

During a challenge, testing various methods of completing them, I’ve noticed one of the coding questions seems to be a little too easy to pass and I believe it could be fixed with a simple additional test.

consider this code

```
function confirmEnding(str, target) {

  for (let i = target.length, j = 0; i > 0; i--, j++) {
    if (str[str.length-i] == target[j]) {
      return true;
    } else {
      return false;
    }
  }
}

// an actual test

confirmEnding("Open sesame", "same");
```
This code will pass all the tests provided, even though, when the target is changed to for example “sage” it returns

```
true
true
false
true
```
I think a test should be added with some incorrect middle letters such as

`confirmEnding("Open sesame", "sage");`

testing if each individual letter is correct.

Let me know what you think or if I’m being silly!

**Add a Link to the page with the problem:**
https://www.freecodecamp.org/learn/javascript-algorithms-and-data-structures/basic-algorithm-scripting/confirm-the-ending

**Tell us about your browser and operating system:**
* Browser Name:  Google Chrome
* Browser Version: Version 84.0.4147.89 (Official Build) (64-bit)
* Operating System: Windows 10 Pro

### PR DESCRIPTION
**Pull request by dyneskye**
Checklist:

- [*] I have read [freeCodeCamp's contribution guidelines](https://contribute.freecodecamp.org).
- [*] My pull request has a descriptive title (not a vague title like `Update index.md`)
- [*] My pull request targets the `master` branch of freeCodeCamp.
- [*] All the files I changed are in the same world language, for example: only English changes, or only Chinese changes, etc.

Closes #39320 

Test fixes the edge case scenario that this code is run:

```
function confirmEnding(str, target) {

  for (let i = target.length, j = 0; i > 0; i--, j++) {
    if (str[str.length-i] == target[j]) {
      return true;
    } else {
      return false;
    }
  }
}

confirmEnding("Open sesame", "sage");
```

In this case, the test would pass but would not follow the criteria of the challenge which is to confirm that the ending is correct, letter for letter.

### CODE REVIEW

**Review by ShaunSHamilton — CHANGES_REQUESTED** [review]
Ideally, one of the other existing tests would be replaced with this one, instead of adding another test. There are far too many tests in this challenge, in my opinion.

I suggest  the test below looking for the case of `"pen"` be replaced, unless someone can think of a reason why not.

**Comment by dyneskye** [comment]
> Ideally, one of the other existing tests would be replaced with this one, instead of adding another test. There are far too many tests in this challenge, in my opinion.
> 
> I suggest the test below looking for the case of `"pen"` be replaced, unless someone can think of a reason why not.

You are right. I've done so. I believe the test below it looking for the case of "mountain" explains the idea just the same, if not better.

**Review by ShaunSHamilton — APPROVED** [review]
Thank you, for getting this out so quickly. LGTM 👍

**Review by RandellDawson — APPROVED** [review]

**Comment by RandellDawson** [comment]
Congrats @dyneskye on your first pull request (PR)! 🎉

Thank you for your contribution to the page! 👍
We're happy to accept these changes, and look forward to future contributions. 📝

**Pull request merged**
