### PR TITLE
Follow-up article on pandas-operations.

### PR DESCRIPTION
**Pull request by harikrishnand**
- [x] I have read [freeCodeCamp's contribution guidelines](https://github.com/freeCodeCamp/freeCodeCamp/blob/master/CONTRIBUTING.md).
- [x] My pull request has a descriptive title (not a vague title like `Update index.md`)
- [x] My pull request targets the `master` branch of freeCodeCamp.
- [x] None of my changes are plagiarized from another source without proper attribution.
- [x] My article does not contain shortened URLs or affiliate links.

If your pull request closes a GitHub issue, replace the XXXXX below with the issue number.

Closes #XXXXX

### CODE REVIEW

**Comment by harikrishnand** [comment]
This is a follow-up article to my previous articles on pandas.

**Comment by paulywill** [comment]
@harikrishnand Wow! Very comprehensive article... thank you!

**Comment by harikrishnand** [comment]
@paulywill : Hi paulywill,  My pleasure to contribute. Thank you for accepting it. :) I do have more articles pending for merge on the same topic. Would you mind to have to look and do the necessary or please let me know if any comments. Below are the Pull request no.
#34184
#32621
#31801
#31661 

 I really appreciate your help. 

Thanks,
Hari.

**Comment by paulywill** [comment]
@harikrishnand I'll take a look.

**Pull request merged**
