### PR TITLE
Working demo for night mode

### PR DESCRIPTION
**Pull request by benmcmahon100**
Style needs to be touched up and redraw is a bit annoying still.
The styling needs to be reviewed by @QuincyLarson  and @hallaathrad before this is good to go.
I'm also working on getting the initial logic to be done server side but it would require current night mode preferences on the user obj.

### CODE REVIEW

**Comment by BerkeleyTrue** [comment]
We'll be using stylesheet switching instead of changing classes.

**Comment by BerkeleyTrue** [comment]
What's going on with you commit history?

**Comment by benmcmahon100** [comment]
@BerkeleyTrue I'm not sure why it's adding in the extra commits. I should just have all the stuff plus a few merges from staging

**Comment by benmcmahon100** [comment]
Is there any way to remove those commits without losing everyone's commits?

**Comment by BerkeleyTrue** [comment]
At this point, I would just manually copy the work you've done onto a new branch. In the future, do not merge staging into your branches.

**Comment by benmcmahon100** [comment]
Doing that would ditch everyone's commit history though! I wouldn't want to ruin the actual history of the changes. Is there definitely no way of removing the bad commits?

**Comment by BerkeleyTrue** [comment]
What?

**Comment by BerkeleyTrue** [comment]
```bash
git checkout staging
git pull staging
git checkout -b feature/add-night-mode
```

Then copy your code over to the new branch

**Comment by benmcmahon100** [comment]
There's work from @hallaathrad and @raisedadead in there. I'll just try to as everyone as a co-author on one bumper commit tomorrow. Don't delete this branch yet though, I'll ditch it once the new one is ready

**Comment by benmcmahon100** [comment]
:+1:

**Pull request closed without merging**
