### PR TITLE
Challenges HTML5 and CSS translated to German

### LINKED ISSUE #6964: German translation of HTML5 and CSS
- [ ] Say Hello to HTML Elements
- [ ] Headline with the h2 Element
- [ ] Inform with the Paragraph Element
- [ ]  Uncomment HTML
- [ ]  Comment out HTML
- [ ] Fill in the Blank with Placeholder Text
- [ ]  Delete HTML Elements
- [ ]  Change the color of Text
- [ ]  Use CSS Selectors to Style Elements
- [ ] Use a CSS Class to Style an Element
- [ ]  Change the Font Size of an Element
- [ ]  Change the Font Family of an Element
- [ ]  Import a Google Font
- [ ]  Specify How Fonts should degrade
- [ ]  Add Images to your Website
- [ ]  Size your Images
- [ ] Add Borders Around your Elements
- [ ]  Add Rounded Corners with a Border Radius
- [ ]  Make Circular Images with a Border Radius
- [ ]  Link to External Pages with Anchor Elements
- [ ]  Nest an Anchor Element within a Paragraph
- [ ]  Makde Dead Links using the Hash Symbol
- [ ]  Turn an Image into a Link
- [ ]  Add Alt Text to an Image for Accessibility
- [ ]  Create a Bulleted Unordered List
- [ ]  Create an Ordered List
- [ ]  Create a Text Field
- [ ]  Add a Placeholder Text to a Text Field
- [ ]  Create a Form Element
- [ ]  Add a Submit Button to a Form
- [ ]  Use HTML5 to Require a Field
- [ ]  Create a Set of Radio Buttons
- [ ]  Create a Set of Checkboxes
- [ ]  Check Radio Buttons and Checkboxes by Default
- [ ]  Nest Many Elements within a Single Div
- [ ] Give a Background Color to a Div Element
- [ ]  Set the ID of an Element
- [ ]  Use an ID Attribute to Style an Element
- [ ]  Adjusting the Padding of an Element
- [ ]  Adjust the Margin of an Element
- [ ]  Add a Negative Margin to an Element
- [ ]  Add a Different Padding to Each Side of an Element
- [ ]  Add Different Margins to Each Side of an Element
- [ ]  Use Clockwise Notation to Specify the Padding of an Element
- [ ] Use Clockwise Notation to Specify the Margin of an Element
- [ ]  Style the HTML Body Element
- [ ]  Inherit Styles from the Body Element
- [ ] Prioritize One Style Over Another
- [ ]  Override Styles in Subsequent CSS
- [ ]  Override Class Declarations by Styling ID Attributes
- [ ]  Override Class Declarations with Inline Styles
- [ ]  Override All Other Styles by using Important
- [ ]  Use Hex Code for Specific Colors
- [ ]  Use Hex Code to Color Elements White
- [ ]  Use Hex Code to Color Elements Red
- [ ]  Use Hex Code to Color Elements Green
- [ ]  Use Hex Code to Color Elements Blue
- [ ]  Use Hex Code to Mix Colors
- [ ]  Use Hex Code to Color Elements Gray
- [ ]  Use Hex Code for Specific Shades of Gray
- [ ]  Use Abbreviated Hex Code
- [ ]  Use RGB values to Color Elements
- [ ]  Use RGB values to Color Elements White
- [ ]  Use RGB values to Color Elements Green
- [ ]  Use RGB values to Color Elements Blue
- [ ]  Use RGB values to Mix Colours

### PR DESCRIPTION
**Pull request by abisz**
Completed translation of HTML5 and CSS Challenges. Would be great if someone could proofread it.

closes #6964

### CODE REVIEW

**Comment by 5k9m** [comment]
@abisz Would love to give some comments - but haven't got permissions (or might be too dumb to do so^^). Should I fork your repo and send you a pull request with the changes?

**Comment by abisz** [comment]
@5k9m hmmm this seems unnecessary complicated... how about moving the discussion to gitter and save ourselfs the trouble of creating a pull request inside a pull request?

**Comment by BerkeleyTrue** [comment]
What's the status of this PR?

**Comment by abisz** [comment]
@BerkeleyTrue I'm waiting for somebody to review the translation

**Comment by theflametrooper** [comment]
This PR has been around for over 1 week. I'm merging and if someone spots your mistakes they can fix them in a later pr. Thanks @abisz

**Pull request merged**
