### PR TITLE
Update description of pig-latin algorithm

### PR DESCRIPTION
**Pull request by Kenford20**
Added a sentence to clarify one of the test requirements of the pig-latin challenge in the intermediate algorithm scripting folder of the Javascript Algorithms And Data Structures Certification.

- [x] I have read [freeCodeCamp's contribution guidelines](https://github.com/freeCodeCamp/freeCodeCamp/blob/master/CONTRIBUTING.md).
- [x] My pull request has a descriptive title (not a vague title like `Update index.md`)
- [x] My pull request targets the `master` branch of freeCodeCamp.
- [x] None of my changes are plagiarized from another source without proper attribution.
- [x] My article does not contain shortened URLs or affiliate links.

If your pull request closes a GitHub issue, replace the XXXXX below with the issue number.

Closes #XXXXX

### CODE REVIEW

**Comment by nikrb** [comment]
@Kenford20 thanx for opening this pr and welcome to FCC.
I'm not sure the rule you have added is actually a rule. Can you provide a source?

**Comment by scissorsneedfoodtoo** [comment]
@Kenford20, everything LGTM! Thank you for helping us improve this section of the curriculum. It's been some time since I completed this challenge, so I had to do some digging around the forums. Seems like a test for this was added in beta but the description was never updated. Hopefully with your addition users won't have as much trouble with this challenge. Looking forward to your next contribution! :+1: :+1:

**Comment by scissorsneedfoodtoo** [comment]
@nikrb, sorry! I saw that you assigned yourself and I didn't mean to merge without your feedback. Was on autopilot there after leaving a comment. Hope you don't mind. Will be more careful the the future!

**Comment by Kenford20** [comment]
@nikrb Yes, it is not actually a rule. It was just meant to clarify the last test in the challenge that states "should handle words with no vowels." As @scissorsneedfoodtoo has mentioned, there was confusion with other campers as well in the forums. After revisiting this challenge, it seems the test has been modified, and the update to the description is no longer necessary (I think? since I was able to take out the portion of my solution that handled that last test case). But I guess it can't hurt :) Thanks guys!

**Comment by nikrb** [comment]
@scissorsneedfoodtoo no worries dude, it's all good 😄

**Pull request merged**
