### PR TITLE
Fix typo mentioned in issue #44761

### LINKED ISSUE #44761: Typo in Beta Responsive Web Design Certification,  Learn CSS Colors By Building a Set of colored markers project
## Affected page

Here is the lesson with the typo: 

https://github.com/freeCodeCamp/freeCodeCamp/blob/main/curriculum/challenges/english/14-responsive-web-design-22/learn-css-colors-by-building-a-set-of-colored-markers/step-047.md

It currently says "You may already be familiar with decimal, or base 10 values, which go from 0 - 10", whereas it should say  "You may already be familiar with decimal, or base 10 values, which go from 0 - 9".

## Screenshots
Screenshot 2022-01-12 at 11 38 48 AM

### PR DESCRIPTION
**Pull request by mdSrq**
Checklist:

- [ x ] I have read [freeCodeCamp's contribution guidelines](https://contribute.freecodecamp.org).
- [ x ] My pull request has a descriptive title (not a vague title like `Update index.md`)
- [ x ] My pull request targets the `main` branch of freeCodeCamp.
- [ x ] I have tested these changes either locally on my machine, or GitPod.

Closes #44761

### CODE REVIEW

**Comment by moT01** [comment]
Thanks for the PR @mdSrq 🎉 A couple tips - it's best not to work on your `main` branch. It's better to create a branch off of main and make changes to that. See [#3 in this section of our documentation](https://contribute.freecodecamp.org/#/how-to-setup-freecodecamp-locally?id=making-changes-locally) for how to go about that. Also, if you replace the `XXXXX` in the description of this PR, it will close the related issue automatically when this gets merged 👍

**Review by moT01 — APPROVED** [review]
LGTM 🎉

**Review by jdwilkin4 — APPROVED** [review]
LGTM! 👍

**Comment by mdSrq** [comment]
@moT01 Thank You! This was my first ever contribution to a project. I understand that I should create new branch to make my changes. But I don't understand what you meant my "replace the `XXXXX` in the description" and what should I replace it with.

**Comment by jdwilkin4** [comment]
Hi @mdSrq ! 
Congrats on your first PR! 👍 

>  But I don't understand what you meant my "replace the `XXXXX` in the description" and what should I replace it with.

If you take a look at the bottom of your PR, you will notice that I edited it to include the issue number so it would automatically close when the PR was merged into the main branch. 

Here is the edit that I made

> Closes #44761

Hope that clears it up!

**Pull request merged**
