### PR TITLE
Upgrade Node.js and likes

### PR DESCRIPTION
**Pull request by raisedadead**
Rebase merge

### CODE REVIEW

**Comment by ShaunSHamilton** [comment]
This looks to work 👍 

I do get this error in the client:

<details>
  <summary>Error</summary>

```bash
 ERROR 

(node:2531) [DEP0148] DeprecationWarning: Use of deprecated folder mapping "./"
in the "exports" field module resolution of the package at
/workspace/freeCodeCamp/client/node_modules/chai/package.json.
Update this package.json to use a subpath pattern like "./*".
(Use `node --trace-deprecation ...` to show where the warning was created)
```
</details>

But, this should be resolved with: https://github.com/chaijs/chai/pull/1400

---

Probably unrelated, but Gitpod at least uses this for some reason:
```bash
MongoDB shell version v5.0.2
```

Locally, it is `4.2`. So, something to keep in mind.

---

Otherwise, I have been using `node@16` for over one week, and have not come across any issues.

**Comment by nhcarrigan** [comment]
I get the deprecated folder mapping on Node 14 too.

**Comment by nhcarrigan** [comment]
image


I run `npm install` and it looks like our root package-lock is a bit out of sync. @raisedadead do you want me to push up a commit? It's only 43 lines of change.

**Comment by raisedadead** [comment]
Yeah - some dependencies were updated in some of these packages while this PR is awaiting a merge and I have just rebased and updated all the lockfiles including the root, client, tools, etc.

Thanks for your review Nick and Shaun. I am going to wait for the tests and merge this in.

**Pull request merged**
