### PR TITLE
added solution to challenge hints

### PR DESCRIPTION
**Pull request by magic-hat**
- [x] I have read [freeCodeCamp's contribution guidelines](https://github.com/freeCodeCamp/freeCodeCamp/blob/master/CONTRIBUTING.md).
- [x] My pull request has a descriptive title (not a vague title like `Update index.md`)
- [x] My pull request targets the `master` branch of freeCodeCamp.
- [x] None of my changes are plagiarized from another source without proper attribution.
- [x] My article does not contain shortened URLs or affiliate links.

If your pull request closes a GitHub issue, replace the XXXXX below with the issue number.

Closes #XXXXX

### CODE REVIEW

**Comment by RandellDawson** [comment]
Closed and Reopened this PR to attempt to resolve a specific Travis build failure.

**Comment by RandellDawson** [comment]
@magic-hat Please make sure any solution you add includes all original seed code, plus any changes necessary for the solution to pass the tests.

Thank you.

**Comment by magic-hat** [comment]
@RandellDawson Certainly. In this case, all I did was update some copy in a markdown file for clarity - I didn't touch any other files.

**Comment by magic-hat** [comment]
Ah, and now I understand your comment. Ignore my last one 😄

**Comment by RandellDawson** [comment]
@magic-hat Can you please update the solution with all the code?

**Comment by thecodingaviator** [comment]
This has gone stale

**Comment by RandellDawson** [comment]
As there has been no response from your end for a while, we are closing this PR.

Feel free to request this PR to be reopened or create a new PR, if you still wish to make the changes you originally added plus any additional change requests asked of you.  Also, remember to update your fork, so you have the latest version of master in case it has changed significantly.

Happy Coding!

**Pull request closed without merging**
