### PR TITLE
fix(learn): Fix largestPrimeFactor function results and add additional test. Project Euler: Problem 3

### LINKED ISSUE #38755: Test times out in Project Euler: Problem 3: Largest prime factor
**Describe your problem and how to reproduce it:**
The last test times out on the given problem and needs to either be removed or replaced with a smaller number.

**Add a Link to the page with the problem:**
https://www.freecodecamp.org/learn/coding-interview-prep/project-euler/problem-3-largest-prime-factor

**If possible, add a screenshot here (you can drag and drop, png, jpg, gif, etc. in this box):**
image

### PR DESCRIPTION
**Pull request by UgRoss**
* Fix `largestPrimeFactor(8)` result
* Improve `largestPrimeFactor` performance
* Add `largestPrimeFactor(8)` test

Checklist:

- [X] I have read [freeCodeCamp's contribution guidelines](https://contribute.freecodecamp.org).
- [X] My pull request has a descriptive title (not a vague title like `Update index.md`)
- [X] My pull request targets the `master` branch of freeCodeCamp.
- [X] All the files I changed are in the same world language, for example: only English changes, or only Chinese changes, etc.

Closes: #38755

### CODE REVIEW

**Review by ojeytonwilliams — APPROVED** [review]
LGTM 👍

**Comment by Sky020** [comment]
Question: As the tests are run, the _time-out_ is it started at the beginning of the tests? Or, at the beginning of each test? Reason I ask, is my solution, which previously passed (a long time ago), now times out. I thought, potentially, due to the extra test.

**Review by ShaunSHamilton — APPROVED** [review]
LGTM 👍

**Review by moT01 — APPROVED** [review]
LGTM @UgRoss 🎉 Congratulations on your first contribution to freeCodeCamp 🎉

I added this solution to the guide.

**Comment by UgRoss** [comment]
> LGTM @UgRoss 🎉 Congratulations on your first contribution to freeCodeCamp 🎉
> 
> I added this solution to the guide.

Thank you! 🙂

**Pull request merged**
