### PR TITLE
**my-notes

### PR DESCRIPTION
**Pull request by nmadar**
- [X] I have read [freeCodeCamp's contribution guidelines](https://github.com/freeCodeCamp/freeCodeCamp/blob/master/CONTRIBUTING.md).
- [X] My pull request has a descriptive title (not a vague title like `Update index.md`)
- [X] My pull request targets the `master` branch of freeCodeCamp.
- [X] None of my changes are plagiarized from another source without proper attribution.
- [X] My article does not contain shortened URLs or affiliate links.

If your pull request closes a GitHub issue, replace the XXXXX below with the issue number.

Closes #XXXXX

### CODE REVIEW

**Comment by ArielLeslie** [comment]
Please edit this to be in the tone of a guide article rather than an informal "my notes" section, which is likely to only confuse people.

**Comment by nmadar** [comment]
Hi thank you for this note, can you send me some guide? I did it just like I found online.. thank you

**Comment by ArielLeslie** [comment]
You should always refer to the [CONTRIBUTING](https://github.com/freeCodeCamp/freeCodeCamp/blob/master/CONTRIBUTING.md) document before pushing changes to an open source project. In the case of Guide articles, please read the article first and make sure that your changes fit in with (and improve upon) the FCC Guide. Remember that this is a resource used by tens of thousands of people and we want to provide the best information that we can in a clear and readable way.

**Review by Manish-Giri — COMMENTED** [review]
Hi,

As there has been no response from your end for a while, I am closing this PR.

Feel free to re-open it if you wish to apply the suggested changes.

Happy Coding!

**Pull request closed without merging**
