### PR TITLE
Adding a test in problem-14-Longest-collatz-sequence.english.md

### PR DESCRIPTION
**Pull request by yitzhak-bloy**
Checklist:

- [x] I have read [freeCodeCamp's contribution guidelines](https://github.com/freeCodeCamp/freeCodeCamp/blob/master/CONTRIBUTING.md).
- [x] My pull request has a descriptive title (not a vague title like `Update index.md`)
- [x] My pull request targets the `master` branch of freeCodeCamp.
- [x] All the files I changed are in the same world language, for example: only English changes, or only Chinese changes, etc.

Originally, this challenge was designed to check the case of all starting number under **one million** produces the longest chain, as you can see on the [official Project Euler website](https://projecteuler.net/problem=14).
but in the challenge here, the highest test is on starting number under **one hundred thousand**.
so I added another test to check the case of all starting number under one million.

### CODE REVIEW

**Comment by thecodingaviator** [comment]
Hello, thanks for opening the PR, I'm having a little trouble understanding the intent of the PR. Please help me out here. I realize that we want to check under `10^6` rather than `10^5`. Shouldn't we be checking for `9.99999E5`?

**Comment by moT01** [comment]
Looks like this test was [deliberately removed](https://github.com/freeCodeCamp/freeCodeCamp/commit/e4a229187ef035bffeff1175c23c9be246fb0761#diff-b61e3ec758c122cda19c56f06f08948f) at one point. Likely to stop code from timing out.

**Comment by RandellDawson** [comment]
@ojeytonwilliams I believe the commit referenced by @moT01 is yours.  Do you have anything to add here?

**Comment by yitzhak-bloy** [comment]
Thanks @moT01.

 joins @RandellDawson's question, 
@ojeytonwilliams why did you drop the test on 1000000, even though it is the original challenge?

**Comment by thecodingaviator** [comment]
@yitzhak-bloy it had most probably been done to stop the tests from timing out

**Comment by ojeytonwilliams** [comment]
Sorry for the late reply, and yes, that's exactly why it was removed.  The problem is that long running code can trigger the loop-protection, exit early and give unpredictable results.

If memory serves, I didn't find a fast enough algorithm, which would have allowed the original test to be used.  I'll take another look. If anyone else knows of a smarter algorithm, that would be great!

**Comment by ojeytonwilliams** [comment]
I researched a bit and improved the algorithm a reasonable amount.  It should be good enough for the 1,000,000 case.

@yitzhak-bloy thanks for finding my mistake!  Clearly I wasn't being careful enough when I cut out slow tests.

**Review by moT01 — APPROVED** [review]
LGTM 🎉 

For future reference, it's good to give your branch a more descriptive name and start it with a scope. See `#3` just below [here in the docs](https://github.com/freeCodeCamp/freeCodeCamp/blob/master/docs/how-to-setup-freecodecamp-locally.md#making-changes-locally)

I added this solution to the guide.

**Review by ShaunSHamilton — APPROVED** [review]
LGTM 🎉

**Comment by moT01** [comment]
Thanks for fixing this @yitzhak-bloy, and congratulations on your first contribution to freeCodeCamp 🎉

**Pull request merged**
