### PR TITLE
Clean-up of text in 4th paragraph.

### PR DESCRIPTION
**Pull request by deesto**
Clean up 4th para.

- [x] I have read [freeCodeCamp's contribution guidelines](https://github.com/freeCodeCamp/freeCodeCamp/blob/master/CONTRIBUTING.md).
- [x] My pull request has a descriptive title (not a vague title like `Update index.md`)
- [x] My pull request targets the `master` branch of freeCodeCamp.
- [x] None of my changes are plagiarized from another source without proper attribution.
- [x] My article does not contain shortened URLs or affiliate links.

If your pull request closes a GitHub issue, replace the XXXXX below with the issue number.

Closes #XXXXX

### CODE REVIEW

**Comment by RandellDawson** [comment]
Your PR was marked invalid almost automatically, becuase even though you checked box #2 (shown below), you did not actual do what it state.
```
 My pull request has a descriptive title (not a vague title like Update index.md)
```
Update your title and checkoff that box. These help us understand that you have read the requirements. Commits should have short but useful descriptions of what you are doing. It helps us in the review process. With the sheer volume of PRs we are getting right now, we focus on the ones where the conttributor has made the effort to follow the process. You have no idea how many of the "update index.md" are just a bot making a one character change.

Just update your PR title and tag me and I will review it personally.

**Comment by deesto** [comment]
Will do, and thank you and apologies: I'm used to working with GIt, with which a commit includes a descriptive message that doesn't have a title. I'll move my messages into the merge req titles.
Thanks,~John
    On Friday, October 19, 2018, 1:12:55 PM EDT, Randell Dawson <notifications@github.com> wrote:  
 
 
Your PR was marked invalid almost automatically, becuase even though you checked box #2 (shown below), you did not actual do what it state.
 My pull request has a descriptive title (not a vague title like Update index.md)

Update your title and checkoff that box. These help us understand that you have read the requirements. Commits should have short but useful descriptions of what you are doing. It helps us in the review process. With the sheer volume of PRs we are getting right now, we focus on the ones where the conttributor has made the effort to follow the process. You have no idea how many of the "update index.md" are just a bot making a one character change.

Just update your PR title and tag me and I will review it personally.

**Comment by deesto** [comment]
Title modified, and no additional PRs created for this. Thanks for looking again at my edits and merging the others.

**Comment by RandellDawson** [comment]
OK.  Everything looks good now.  Thank you for contributing.  I will merge when all the internal checks have taken place (about 10 hours from now).

**Review by RandellDawson — APPROVED** [review]

**Pull request merged**
