### PR TITLE
fix(challenge): map.add() test case in create map DS challenge

### LINKED ISSUE #16981: Assert Error: Create A Map Data Structure
#### Challenge Name : Create a Map Data Structure

https://beta.freecodecamp.org/en/challenges/coding-interview-data-structure-questions/create-a-map-data-structure

#### Issue Description

[The code below works fine on my IDE, but the 3rd test of “add” fails in fcc sandbox.]
In the seed code of this challenge, the 3rd assert instruction reads :

_“assert((function() { var test = false; if (typeof Map !== ‘undefined’) { test = new Map() }; test.add(5,6); test.add(2,3); test.add(2,5); return (test.size() == 3)})(), ‘message: The add method adds items to the map.’);”_

It adds (5,6),(2,3),(2,5) … then why is it asserting test.size() = 3 ? Shouldn’t it be = 2, since (2,3) and (2,5) will still map to the same key : 2 …?

Shouldn't the assert  be corrected ? 

#### Browser Information

* Browser Name, Version: Mozilla/5.0  Gecko/20100101 Firefox/59.0.
* Operating System: (X11; Ubuntu; Linux x86_64; rv:59.0)
* Mobile, Desktop, or Tablet: Desktop

#### Your Code

```js
var Map = function() {
  this.collection = {};
  // change code below this line
  this.add = (key,value)=>{
    this.collection[key] = value;
    return this.collection[key];
  };
  this.remove = (key)=>{
    if(this.collection.hasOwnProperty(key)){
      this.collection.delete(key);
    }
  };
  this.get = (key)=>{
    return this.collection[key];
  };
  this.has = (item)=>{
    return (this.collection.hasOwnProperty(item));
 };
 this.values = ()=>{
   let ar = [];
   for(let v in this.collection){
	   ar.push(this.collection[v]);
   }
   return ar;
 }; 
  this.size = ()=>(Object.keys(this.collection).length);
  this.clear = ()=>{
    this.collection = {};
  };
  // change code above this line
};

var m1 = new Map();
m1.add("p1","Tom");
m1.add("p2","Jerry");
m1.add("p3","Julie");
console.log(m1.values());
console.log(m1.size());
m1.clear();
m1.add(2,3);
m1.add(2,5);
m1.add(3,6);
console.log(m1.values());
console.log(m1.size());

```
#### Screenshot

create-map-data-structure

### PR DESCRIPTION
**Pull request by kirushna-kumar**
#### Pre-Submission Checklist

- [x] Your pull request targets the `staging` branch of freeCodeCamp.
- [x] Branch starts with either `fix/`, `feature/`, or `translate/` (e.g. `fix/signin-issue`)
- [x] You have only one commit (if not, [squash](http://forum.freecodecamp.org/t/how-to-squash-multiple-commits-into-one-with-git/13231) them into one commit).
- [x] All new and existing tests pass the command `npm test`. Use `git commit --amend` to amend any fixes.

#### Type of Change

- [x] Small bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds new functionality)
- [ ] Breaking change (fix or feature that would change existing functionality)
- [ ] Add new translation (feature adding new translations)

#### Checklist:

- [x] Tested changes locally.
- [x] Addressed currently open issue (replace XXXXX with an issue no in next line)

Closes #16981

#### Description

Minor fix in assert statement for validating behavior of map data structure

### CODE REVIEW

**Comment by mstellaluna** [comment]
I am working on this PR

**Review by mstellaluna — COMMENTED** [review]
Requesting secondary review @raisedadead

**Comment by mstellaluna** [comment]
@raisedadead  When using the code provided by the original issue opener, the challenge passes, which is fine. The issue is if I omit the second half the code which is the code snippet below, the challenge still passes. The code snippet is not part of the original code challenge. I am uncertain if this is meant to be there or not or if something indirectly broke.

Omitting this still passes the test:
`var m1 = new Map();
m1.add("p1","Tom");
m1.add("p2","Jerry");
m1.add("p3","Julie");
console.log(m1.values());
console.log(m1.size());
m1.clear();
m1.add(2,3);
m1.add(2,5);
m1.add(3,6);
console.log(m1.values());
console.log(m1.size());`

**Comment by flipsyde606** [comment]
@mstellaluna From what I can see in the challenge description, it just requires the map data structure to be defined. The test cases are defined to evaluate the properties and behaviour of the map and nothing else. The final part must have been written by OP just to validate his map structure outside of the challenge requirements.

**Comment by mstellaluna** [comment]
@flipsyde606 I will be approving this PR. Thank you for your contribution. Happy Coding.

**Pull request merged**
