### PR TITLE
Fixed Ambigious Explanation of Title Case

### LINKED ISSUE #2424: Bonfire: Title Case a Sentence
Challenge http://www.freecodecamp.com/challenges/bonfire-title-case-a-sentence has an issue. The Bonfire asks to "Return the provided string with the first letter of each word capitalized".The sentence should be worded differently because it should specify that all the letters remaining should be lower case. I realized this just at the moment of my submission looking at the tests.

### PR DESCRIPTION
**Pull request by avastu**
In "Title Case Case a Sentence" bonfire
Closes #2424

### CODE REVIEW

**Comment by BerkeleyTrue** [comment]
Hello @avastu,

Please move issues that this PR closes to their own lines in the form `closes #1337`. See https://github.com/FreeCodeCamp/FreeCodeCamp/wiki/Pull-Request-Contribute

Thanks for the prior fix as well, I know its a process but once you get it down the next ones are much easier to get merged. These are also standard forms across many open source projects so you will experience less friction when you contribute there as well.

**Comment by avastu** [comment]
Got it. Thanks for all your help! Looking forward to more contributions.

**Comment by BerkeleyTrue** [comment]
Thanks. Happy Coding.

**Comment by garyc60674** [comment]
Why are you messing with my phone? My life is so messed up as it is. Please
leave me alone. Please

**Pull request merged**
