### PR TITLE
feat(client): migrate fourOhFour 

### PR DESCRIPTION
**Pull request by naomi-lgbt**
Checklist:

- [X] I have read [freeCodeCamp's contribution guidelines](https://contribute.freecodecamp.org).
- [X] My pull request has a descriptive title (not a vague title like `Update index.md`)
- [X] My pull request targets the `main` branch of freeCodeCamp.
- [X] I have tested these changes either locally on my machine, or GitPod.

Closes #XXXXX

Thought I'd start poking at migrating some things as well - this might have to wait until a couple of our open PRs land tomorrow. I know we had a discussion about the `Spacer` element, which this'll rely on, but I can't for the life of me remember *where* that discussion is.

### CODE REVIEW

**Comment by ojeytonwilliams** [comment]
I know we had a discussion about the `Spacer` element, which this'll rely on, but I can't for the life of me remember _where_ that discussion is.

@huyenltnguyen worked around it by wrapping the Spacer in a fragment: https://chat.freecodecamp.org/channel/contributors?msg=7umgzLxEFuTT2bpmG

At the time I thought we should make it a little more concise, but maybe it's better to make as small a change as possible.  For visibility, here's Huyen's solution:

```jsx
<>
      {'#'
        .repeat(size)
        .split('')
        .map((_, i) => (
          <Comp key={`spacer_${i}`} />
        ))}
    </>
```

**Comment by ShaunSHamilton** [comment]
@ojeytonwilliams and @nhcarrigan First task on: https://github.com/freeCodeCamp/freeCodeCamp/issues/42256#issuecomment-867924539

As so many PRs rely on the Spacer, I have prioritised the PR actually migrating it. My PRs do not touch it, and I will rebase them, before merging - that way Linter does not complain.

Otherwise, I think we can just merge all PRs into `next` with the ESLint warnings, and they will resolve, provide no other PRs conflict with `Spacer`.

**Comment by nhcarrigan** [comment]
> Otherwise, I think we can just merge all PRs into next with the ESLint warnings, and they will resolve, provide no other PRs conflict with Spacer.

Alright then, I can work with this plan. 😁

**Review by ShaunSHamilton — APPROVED** [review]
This LGTM 👍

**Pull request merged**
