### PR TITLE
Fix meaning issue

### PR DESCRIPTION
**Pull request by thomas-kuntz**
The wording made think that we had to return the sum of the two numbers
and *then* all the numbers between them (in the form of an array for
instance). In fact we have to return the sum of the two numbers *plus* the
sum of all numbers the between them.

### CODE REVIEW

**Review by raisedadead — APPROVED** [review]
#### :sparkles: :sparkles: **LGTM.** :sparkles: :sparkles: 

Thanks @thomaskuntzz 

And congrats on your first pull request to freeCodeCamp.

**Comment by raisedadead** [comment]
@thomaskuntzz just confirming there wasn't any open issue for this change? Correct?

**Comment by thomaskuntzz** [comment]
After a quick search there doesn't seem to be any issue about that but it's not completely sure.

**Comment by maggiepagan** [comment]
I am not inundated so h 300 emails and can't keep up.  I have found the original email to allow me to see the first video to learn what it is I'm supposed to do. What can I do so I can begin again and only receive two or three emails a day.  How can anyone have this much time in there life to handle this much input?

Sent from
Maggie Pagan

**Comment by thomaskuntzz** [comment]
@maggiepagan, what is the problem you're having exactly? :sweat_smile:

**Comment by raisedadead** [comment]
Hello @maggiepagan !

Looks like you have accidentally subscribed to all notifications for the [freeCodeCamp](https://github.com/freeCodeCamp/freeCodeCamp) repository. To stop receiving notifications please visit the [subscriptions page](https://github.com/freeCodeCamp/freeCodeCamp/subscription) and select **"Not watching"**.

[image](https://github.com/FreeCodeCamp/FreeCodeCamp/subscription)


We are sorry for your inconvenience!

**Pull request merged**
