### PR TITLE
Fix: Certification Claims

### LINKED ISSUE #17336: Trying to claim my certification
#### Describe your problem and - if possible - how to reproduce it
I have completed every of the 5 projects in the “Apis And Microservices” category. But when I try to claim my certificate, I can see : “it looks like you have not completed the necessary steps. Please complete the required challenges to claim the APIs and Microservices”.

#### Add a Link to the page with the problem
Account settings (APIs and Microservices Projects)

#### Tell us about your browser and operating system

* Browser Name: Google Chrome
* Browser Version:  Version 67
* Operating System: W10

### LINKED ISSUE #17363: Responsive Design Certification can not be claimed
I completed the projects for Responsive Design Cert and even edit the older ones, from Legacy, to complete the new goals. But when I claim my cert a message appears that says "it looks like you have not completed the necessary steps. Please complete the required challenges to claim the Responsive Web Design"

Is it because I can not find how to complete introductions???

https://www.freecodecamp.org/settings

* Browser Name: Chrome 
* Browser Version: Version 67.0.3396.62 (Official Build) (64-bit)
* Operating System: Windows 10

image

### PR DESCRIPTION
**Pull request by Bouncey**
Closes #17363
Closes #17336 

Seed edit only effects server side and does not require the curriculum package to be updated.

### CODE REVIEW

**Comment by PABlond** [comment]
I saw that the problem was resolved for (everybody ?) but not for me ... Are you aware of that ? I still cannot see the certification part in the setting page.

**Comment by johnkennedy9147** [comment]
@PABlond your issue is a different one to what this fixes. This is for where users were getting an incorrect message saying they hadnt completed all necessary projects. You should look to issue #17278 for the problem you are experiencing. thanks

**Comment by kevintd** [comment]
Hi, 
screen shot 2018-06-09 at 2 09 07 am
screen shot 2018-06-09 at 2 07 12 am

This issue also happened to me again. Are there any things what i have to do?

**Comment by sdabhi23** [comment]
image
I am still not able  to claim my certificate 🙁

**Comment by FinQode** [comment]
Same situation here unfortunately. Any updates on a fix on this?

screenshot 2018-06-24 10 49 14

**Pull request merged**
