### PR TITLE
Add Node and Express quiz with 20 questions

### LINKED ISSUE #56237: [HACKTOBERFEST 2024] - Node and Express Quiz
> [!IMPORTANT]
> This issue is part of our 2024 Hacktoberfest initiative. If you are interested in working on this issue, refer to our [top-level tasks](https://github.com/freeCodeCamp/freeCodeCamp/issues/56170) to see if this issue is claimed, or to claim it if it is not.

This issue is to create the Node and Express quiz.

The file you should be working on is found in `/curriculum/challenges/english/25-front-end-development/quiz-node-and-express`.

**All quiz questions need to relate to one of these topics:**

- JavaScript runtimes and engines (V8, node, deno, bun, browsers)
- npm
- Express
- connect node to SQL db

> [!CAUTION]
> Questions which do not fall under these topics will be rejected.

You are welcome to include code blocks in your questions, but please keep them short (four lines or less).

Please do NOT open a pull request until you have completed all questions. Your quiz should have **exactly 20 questions**.

### PR DESCRIPTION
**Pull request by prasanna1225**
Checklist:

- [X] I have read and followed the [contribution guidelines](https://contribute.freecodecamp.org).
- [X] I have read and followed the [how to open a pull request guide](https://contribute.freecodecamp.org/how-to-open-a-pull-request/).
- [X] My pull request targets the `main` branch of freeCodeCamp.
- [X] I have tested these changes either locally on my machine, or GitPod.

Ref #56237

This pull request adds a Node and Express quiz with 20 questions for Hacktoberfest 2024.

**Key points:**
- The quiz covers topics such as Node.js, npm, Express, and connecting Node to SQL databases.
- The questions follow the FreeCodeCamp quiz structure, with distractors and answers.

**Note:** 
I used a placeholder file name for the quiz since I was unsure about the correct ID generation process for quiz files. Please assign the proper ID if needed, and let me know if I need to adjust anything. Thanks!

Looking forward to your feedback!

### CODE REVIEW

**Comment by prasanna1225** [comment]
I hope this message finds you well. I am writing to address an issue related to my recent contributions to the FreeCodeCamp repository during Hacktoberfest 2024. Two of my pull requests were marked as spam:
1.	[PR #56411](https://github.com/freeCodeCamp/freeCodeCamp/pull/56411)
2.	[PR #56410](https://github.com/freeCodeCamp/freeCodeCamp/pull/56410)
As a result of these labels, I have been disqualified from Hacktoberfest. I was informed that to lift the disqualification, I need to work with the maintainers to have these labels removed.
I would like to clarify that I put genuine effort into contributing to the project and followed the guidelines to the best of my understanding. Hacktoberfest is something I’ve looked forward to participating in, and it is disheartening to be disqualified after waiting a year for this event.
Could you kindly review these pull requests and provide feedback or guidance on how they can be improved to meet the project’s standards? I’m more than willing to make any necessary adjustments to ensure they are aligned with the contribution requirements.
I truly appreciate your time and support in resolving this matter and hope to continue contributing to FreeCodeCamp in a meaningful way.

**Comment by ilenia-magoni** [comment]
@prasanna1225 the first line in the issue specifically say "If you are interested in working on this issue, refer to our [top-level issue](https://github.com/freeCodeCamp/freeCodeCamp/issues/56170) to see if this issue is claimed, or to claim it if it is not.", and in the parent issue there is written "If you are interested in contributing, please respond OH THE ISSUE YOU'D LIKE TO WORK ON. We will then add you to the issue so other contributors know you have claimed that quiz.". 

As you have showed you do not read the issues you want to work on, at this time the spam label stands.

Feel free to join our [Discord](https://discord.gg/KVUmVXA) server and ask for help in the #contributors channel if you are willing to continue contributing.

**Comment by prasanna1225** [comment]
sorry to bother but what should i do to remove that label.

**Comment by ilenia-magoni** [comment]
@prasanna1225 if you show that you contribute following the guidelines we can review and consider removing the label

**Comment by prasanna1225** [comment]
Thank you again for your guidance. I now fully understand the importance of claiming issues before contributing and will ensure I follow this process in the future.

Could you kindly let me know if I can still contribute to the issues I worked on (PR #56411 and PR #56410), or would it be better for me to choose new ones?

I’m eager to contribute meaningfully and will make sure all future contributions strictly adhere to the guidelines.

Thank you for your support and time.

**Comment by ilenia-magoni** [comment]
The quizzes can be worked on only by whom is assigned, feel free to contribute to issues with the 'help wanted' label instead

**Pull request closed without merging**
