### PR TITLE
fix(e2e): wait for next challenge render

### PR DESCRIPTION
**Pull request by ojeytonwilliams**
The issue was caused by `cy.contains('Go to next challenge').click();` and then not waiting for the result before visiting the next page.

### CODE REVIEW

**Review by raisedadead — COMMENTED** [review]
I see the test run was cancelled. Not sure if this is ready or WIP?

**Comment by ojeytonwilliams** [comment]
I'm still in the dark about what's going on here.  I'll update when I have more of a clue.

**Comment by raisedadead** [comment]
Yeah, I figured that you were stuck.

**Comment by ojeytonwilliams** [comment]
I still don't have much of a clue what the root cause of this is.  Possibly something strange with Gatsby (since it's got its own webpack config that's creating these chunks) or vercel/serve.

**Comment by ojeytonwilliams** [comment]
@raisedadead I'm not 100% confident it's *fixed*, but it has passed the tests.

**Review by raisedadead — APPROVED** [review]

**Pull request merged**
