### PR TITLE
improvement(guide): ES6, code examples and resources

### PR DESCRIPTION
**Pull request by AdrianSkar**
- [x] I have read [freeCodeCamp's contribution guidelines](https://github.com/freeCodeCamp/freeCodeCamp/blob/master/CONTRIBUTING.md).
- [x] My pull request has a descriptive title (not a vague title like `Update index.md`)
- [x] My pull request targets the `master` branch of freeCodeCamp.
- [x] None of my changes are plagiarized from another source without proper attribution.
- [x] All the files I changed are in the same world language (for example: only English changes, or only Chinese changes, etc.)
- [x] My changes do not use shortened URLs or affiliate links.

### CODE REVIEW

**Comment by RandellDawson** [comment]
Thank you for opening this pull request.

This is a standard message notifying you that we’ve reviewed your pull request and have decided not to merge it. We would welcome future pull requests from you.

Thank you and happy coding.

**Comment by AdrianSkar** [comment]
Hi @RandellDawson, what is the reasoning behind this decision?

**Comment by RandellDawson** [comment]
Because there is no algorithm difference here.  You just added newer syntax.

**Comment by AdrianSkar** [comment]
Yep, you're totally right. Even with the resources section it doesn't seem to add much besides a solution with less code.

**Pull request closed without merging**
