### PR TITLE
fix(a11y): use appropriate aria-label for fCC logo depending on its use

### LINKED ISSUE #45095: FCC logo not linked to curriculum has aria-label "freeCodeCamp Curriculum"
The translation key and string for `fcc-logo: freeCodeCamp Logo` were changed to `fcc-curriculum: freeCodeCamp Curriculum` in #45039
As far as I understand, this change was intended for the logo in the navigation bar, but the `FreeCodeCampLogo` component is also used on certificates.

The logo on the certificate is not linked to the curriculum. So aria-label "freeCodeCamp Curriculum" seems incorrect here.

## Affected page

Users' certifications such as: https://www.freecodecamp.org/certification/{username}/responsive-web-design
**This change is not deployed to the production yet. I checked it on Gitpod.**

## To reproduce

1. Go to a certification page
2. Check the aria-label of the freeCodeCamp logo on the certificate

## Expected behavior

aria-label should be "freeCodeCamp Logo" when it is not used as a link
(I'm not sure if this is the best solution)

## Screenshots

**This change is not deployed to the production yet. I checked it on Gitpod.**
fcc-logo

## System

- Device: Laptop
- OS: Windows 10
- Browser: Brave
- Version: v 1.35.101
 
## Additional context

Originally pointed out in a Crowdin comment:
https://freecodecamp.crowdin.com/translate/249b43ffcacdb664884a87464db3db6d/25826/en-ja#1142854

### PR DESCRIPTION
**Pull request by sidemt**
Checklist:

- [x] I have read [freeCodeCamp's contribution guidelines](https://contribute.freecodecamp.org).
- [x] My pull request has a descriptive title (not a vague title like `Update index.md`)
- [x] My pull request targets the `main` branch of freeCodeCamp.
- [x] I have tested these changes either locally on my machine, or GitPod.

Closes #45095

`FreeCodeCampLogo` component is used on 2 different places, in the main navigation bar (as a link to the curriculum) and in certificates (as a pure logo).
Use "freeCodeCamp Curriculum" for `aria-label` in navigation bar, but "freeCodeCamp Logo" in certificates.
curriculum

logo

### CODE REVIEW

**Review by raisedadead — DISMISSED** [review]

**Comment by ojeytonwilliams** [comment]
I think the correct approach for purely decorative elements (like the logo on the certification) is to ignore them in screen readers. After all, I don't think the intention is for anyone to read the first sentence as "freeCodeCamp Logo Issued...".

**Comment by sidemt** [comment]
Thanks @ojeytonwilliams I agree with that. So should I change it not to have the aria-label attribute itself when it's on certification?

**Comment by ojeytonwilliams** [comment]
@sidemt I believe the correct approach is to add `aria-hidden="true"` to decorative svgs. That should do the trick.

**Comment by sidemt** [comment]
@ojeytonwilliams @raisedadead Fixed. Could you please review it again?
I hope I understood the use of `JSX.IntrinsicAttributes` correctly.

**Review by ojeytonwilliams — APPROVED** [review]
Thanks @sidemt, this is working nicely. LGTM :+1:

**Review by raisedadead — APPROVED** [review]

**Pull request merged**
