### PR TITLE
feat(tools): sentry apm and other telemetry

### PR DESCRIPTION
**Pull request by raisedadead**
This adds some tracing and other improvements to the sentry dashboard. For example, it was requested by one of the staff to understand things like TPS on a given endpoint, etc. Over all this will be nice to have since we often need better insights about the API.

### CODE REVIEW

**Review by ShaunSHamilton — COMMENTED** [review]
LGTM 👍 But I am not sure how to test this without using the production keys?

**Comment by raisedadead** [comment]
That's a good question.

You should be able to just sign up for sentry and create a project (it's free), and use those keys to check this locally. 

If you do not want to bother, I could do the same and add some screenshots if you prefer.

**Review by ShaunSHamilton — APPROVED** [review]
This LGTM 👍 Thank you for taking the time to go through this with me, Mrugesh 🚀

**Review by ojeytonwilliams — APPROVED** [review]
LGTM, too. Sorry about the error notification :cold_sweat: (I've deleted it in Sentry)

**Pull request merged**
