### PR TITLE
test(e2e,playwright): donate.tsx

### PR DESCRIPTION
**Pull request by anand-harsh**
Checklist:

- [x] I have read and followed the [contribution guidelines](https://contribute.freecodecamp.org).
- [x] I have read and followed the [how to open a pull request guide](https://contribute.freecodecamp.org/#/how-to-open-a-pull-request).
- [x] My pull request targets the `main` branch of freeCodeCamp.
- [x] I have tested these changes either locally on my machine, or GitPod.

Related to #51705

Updated PR of PR #51723

### CODE REVIEW

**Comment by anand-harsh** [comment]
Hi @huyenltnguyen I have resolved the issues. Kindly check and suggest if any more needed. Thank you for helping me with it.

**Review by huyenltnguyen — APPROVED** [review]
LGTM 👍 

@anand-harsh Thank you for the PR and congratulations on your first contribution to this repo 🎉

---
Just a small note though, I noticed that your branch has a `patch-1` part. This indicates that you were editing the files directly on GitHub, and while this is convenient, it is not a practice we recommend. Instead, you should follow our [setup guide](https://contribute.freecodecamp.org/#/how-to-setup-freecodecamp-locally) to make and test the changes locally 🙂

**Comment by anand-harsh** [comment]
> LGTM 👍
> 
> @anand-harsh Thank you for the PR and congratulations on your first contribution to this repo 🎉
> 
> Just a small note though, I noticed that your branch has a `patch-1` part. This indicates that you were editing the files directly on GitHub, and while this is convenient, it is not a practice we recommend. Instead, you should follow our [setup guide](https://contribute.freecodecamp.org/#/how-to-setup-freecodecamp-locally) to make and test the changes locally 🙂

Earlier I pushed through github but later pushed locally without changing branch name.
As you can see logs , Lint case is passed

**Review by naomi-lgbt — APPROVED** [review]

**Comment by naomi-lgbt** [comment]
Congrats on your first pull request (PR)! 🎉

Thank you for your contribution to the page! 👍
We are happy to accept these changes and look forward to future contributions. 📝

**Pull request merged**
