### PR TITLE
Typo Fix in guide/english/computer-hardware/ram/index.md

### PR DESCRIPTION
**Pull request by iamrajiv**
- [x] I have read [freeCodeCamp's contribution guidelines](https://github.com/freeCodeCamp/freeCodeCamp/blob/master/CONTRIBUTING.md).
- [x] My pull request has a descriptive title (not a vague title like `Update index.md`)
- [x] My pull request targets the `master` branch of freeCodeCamp.
- [x] None of my changes are plagiarized from another source without proper attribution.
- [x] All the files I changed are in the same world language (for example: only English changes, or only Chinese changes, etc.)
- [x] My changes do not use shortened URLs or affiliate links.

### CODE REVIEW

**Comment by iamrajiv** [comment]
@RandellDawson please review

**Comment by thecodingaviator** [comment]
@iamrajiv Please do not @ moderators for review of your PRs. They'll be surely reviewed and processed accordingly when we get to them

**Comment by iamrajiv** [comment]
sorry for the inconvenience, I will take care of next time

**Comment by thecodingaviator** [comment]
It’s fine. Take care of it next time :)

**Review by Manish-Giri — APPROVED** [review]
@iamrajiv LGTM. Thank You for your contribution.

**Pull request merged**
