### PR TITLE
feat(learn): add project tests

### PR DESCRIPTION
**Pull request by gikf**
* Adds four tests to the project page, adapted from functional tests in the [boilerplate code](https://github.com/freeCodeCamp/boilerplate-project-secure-real-time-multiplayer-game/blob/master/tests/2_functional-tests.js)

Related to #40877

Checklist:

- [x] I have read [freeCodeCamp's contribution guidelines](https://contribute.freecodecamp.org).
- [x] My pull request has a descriptive title (not a vague title like `Update index.md`)
- [x] My pull request targets the `main` branch of freeCodeCamp.
- [x] All the files I changed are in the same world language, for example: only English changes, or only Chinese changes, etc.

### CODE REVIEW

**Comment by raisedadead** [comment]
Hi @gikf 

Thanks for your recent pull requests to the Coding Interview sections, I just went through a bunch of them and merged them in. We should be able to deploy these changes to the production over the weekend.

I am particularly impressed and thankful for your high-quality improvements to these sections. We would love to have you on the moderators' team to be able to review and merge pull-requests especially to the coding interview section of our curriculum should that interest you.

If yes, please let us in our contributor's chat (or message me), and we will be more than happy to onboard you. 

Chat room: https://chat.freecodecamp.org/channel/contributors

**Review by ShaunSHamilton — DISMISSED** [review]
This LGTM 👍 

---

To mention: All of these tests rely heavily on the fact that the boilerplate comes with a specific version of Helmet. Therefore, the current docs from Helmet are useless, if a Camper uses them to try to pass this project.

I am wondering if we should be explicit about this in the body of the project?

**Comment by nhcarrigan** [comment]
> I am wondering if we should be explicit about this in the body of the project?

That's a good idea, I think.

**Comment by ShaunSHamilton** [comment]
@nhcarrigan Same PR? Or, get this moved, and work another quick PR on top?

**Comment by nhcarrigan** [comment]
I'd like to land it in the same PR to avoid potential issue where this is deployed without the hint.

**Comment by ShaunSHamilton** [comment]
@gikf Would you mind adding this to the instructions portion of the file:

> **Note**: `helmet@^3.21.1` is needed for the user stories. This means you will need to use the previous version of Helmet's docs, for information on how to achieve the user stories.

@nhcarrigan Feel free to edit this message, to tweek the instructions as you see fit.

**Comment by gikf** [comment]
@ShaunSHamilton I've pushed note with wording from your comment, only changing version to `^3.21.3` to match exactly boilerplate.

@raisedadead Thank you for kind words, I'll get back to you regarding this.

**Review by ShaunSHamilton — APPROVED** [review]
This LGTM 👍 . Nice catch on the version number

**Pull request merged**
