### PR TITLE
Fixes bug on Waypoint: Iterate Through an Array with a For Loop

### LINKED ISSUE #6137: Conditions are not displayed.
Challenge [Waypoint: Iterate Through an Array with a For Loop](http://www.freecodecamp.com/challenges/waypoint-iterate-through-an-array-with-a-for-loop#?solution=%2F%2F%20Example%0Avar%20ourArr%20%3D%20%5B%209%2C%2010%2C%2011%2C%2012%5D%3B%0Avar%20ourTotal%20%3D%200%3B%0A%0Afor%20(var%20i%20%3D%200%3B%20i%20%3C%20ourArr.length%3B%20i%2B%2B)%20%7B%0A%20%20ourTotal%20%2B%3D%20ourArr%5Bi%5D%3B%0A%7D%0A%0A%2F%2F%20Setup%0Avar%20myArr%20%3D%20%5B%202%2C%203%2C%204%2C%205%2C%206%5D%3B%0A%0A%0A%2F%2F%20Only%20change%20code%20below%20this%20line%0A%0Avar%20myTotal%20%3D%200%3B%0A%0Afor%20(var%20i%20%3D%200%3B%20i%20%3C%20myArr.length%3B%20i%2B%2B)%20%7B%0A%20%20myTotal%20%2B%3D%20myArr%5Bi%5D%3B%0A%7D%0A) has an issue.
User Agent is: <code>Mozilla/5.0 (Windows NT 6.1; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/47.0.2526.106 Safari/537.36</code>.
Please describe how to reproduce this issue, and include links to screenshots if possible.

conditions are not displayed ... not abele to continue.

screenshot 7

### PR DESCRIPTION
**Pull request by alistermada**
Conditions needed to pass the tests weren't showing. Problem was that the variable `total` was passed before it could be defined. Rewrote tail to check if `total` is defined.
closes #6137

### CODE REVIEW

**Comment by SaintPeter** [comment]
You should replicate the case that if total is undefined it states that as well.

**Comment by alistermada** [comment]
@SaintPeter The tests already check whether or not total is undefined.

```
"tests": [
        "assert(total !== 'undefined', 'message: <code>total</code> should be defined');",
        "assert(total === 20, 'message: <code>total</code> should equal 20');",
        "assert(!/20/.test(code), 'message: Do not set <code>total</code> to 20 directly');"
      ],
```

**Comment by SaintPeter** [comment]
If you look at the code you replaced in the `tail`, it checks to see if `total` is defined or not. If it is defined it displays the contents of `total`.  If it is not defined it displays `total is not defined`.

**Comment by alistermada** [comment]
@SaintPeter If you check out the waypoint http://www.freecodecamp.com/challenges/waypoint-iterate-through-an-array-with-a-for-loop, you'll see that the conditions for passing the Waypoint in the bottom-left are missing. The only way that a user is alerted that `total` is undefined is by checking the developer console.

pic

Notice that the conditions aren't shown to the user in the pic.

That's because the original tail is trying to run a function that passes `total` as a parameter before it even checks if it's defined.

My code simply checks if `total` is undefined, then returns it so the test can handle it if it isn't. If it is undefined, the test will run anyway and will alert the user that the variable is undefined without having to look at their console.

**Comment by SaintPeter** [comment]
Right.  What I'm suggesting is that you add an else statement on your condition and have it return "total is undefined".

I know it currently doesn't work, but it should/could.

**Comment by alistermada** [comment]
@SaintPeter Oh okay, sorry for misunderstanding. I thought it would be redundant since the tests already return 'total is undefined' and display it to the user. I'll change my code to add an else statement.

**Comment by SaintPeter** [comment]
FYI, you don't need to close the PR.  You can do a `git commit --amend` and then `git push -f` to update your branch.

**Comment by alistermada** [comment]
@SaintPeter Okay. Thank's for the clarification, I didn't know that. I'll leave this closed anyway until I'm ready to amend.

**Comment by alistermada** [comment]
Well.. I force pushed before I reopened. Didn't know it wouldn't allow me to reopen if I did that. Sorry about that. I suppose I'll have to create another pull request

**Pull request closed without merging**
