### PR TITLE
issue: #49081 - UI changes for the flash message

### LINKED ISSUE #49081: Close button (x) is not centered vertically in flash message
### Describe the Issue

Close button (x char) is not aligned vertically in flash message that states `Saved! Your code was saved to your browser's local storage.`

### Affected Page

/learn routes (i.e. https://www.freecodecamp.org/learn/2022/responsive-web-design/learn-html-by-building-a-cat-photo-app/step-3)

### Steps to Reproduce

1. Go to 'https://www.freecodecamp.org/learn/2022/responsive-web-design/learn-html-by-building-a-cat-photo-app/step-3'
2. Click inside of  `Code editor`
3. Save code to local storage (CTRL + S)
4. Flash message appears behind top navigation
5. See close button's vertical alignment is not centered (it is closer to top than to bottom).

### Expected behavior

Close button's vertical alignment should be centered (it should have the same spacing to top and bottom sides of flash message container.

### Screenshots

Screen Shot 2023-01-21 at 11 33 42 AM

Screen Shot 2023-01-21 at 11 33 53 AM

### System

- Device: Laptop
- OS: MacOS
- Browser: Chrome
- Version: v.109

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by SanjeevSingh08**
Aligned the text in the flash message centrally and applied dynamic font size for the text in the flash message

Checklist:

- [x] I have read [freeCodeCamp's contribution guidelines](https://contribute.freecodecamp.org).
- [x] My pull request has a descriptive title (not a vague title like `Update index.md`)
- [x] My pull request targets the `main` branch of freeCodeCamp.
- [x] I have tested these changes either locally on my machine, or GitPod.

Closes #49081

### CODE REVIEW

**Comment by Sboonny** [comment]
I have closed this PR, because it's trying to solve the same issue that #48911 solves

**Comment by SanjeevSingh08** [comment]
@Sboonny then can u please create a new issue so that u can review my commits for that issue.

**Comment by Sboonny** [comment]
I will add you as co-author in the original PR 👍

**Comment by SanjeevSingh08** [comment]
Sorry for disturbing you, but what is the meaning of this. I want to contribute to that issue. Is that possible that i can publish that issue? @Sboonny . Thank you for being a great mentor.

**Comment by Sboonny** [comment]
Adding co-author is a way to give credit for contributing https://github.com/freeCodeCamp/freeCodeCamp/pull/48911/commits/093a50141854935ee7396cc0957716c536c8a6af

https://docs.github.com/en/pull-requests/committing-changes-to-your-project/creating-and-editing-commits/creating-a-commit-with-multiple-authors

You can check the guideline for how to contribute, if this is your first open source contribution. https://contribute.freecodecamp.org/

---

I realized I haven't commented about font-size change, so we are against changing font-size, to make the site as accessible as people for all people. 

You can open issue for it, if you want.

**Comment by SanjeevSingh08** [comment]
ok @Sboonny , One more question - If the #49081 issue was closed. Then why there is  no change on the actual website. I mean if the code is not updated like in my case when i cloned the repo, the button was still not in the centre.And if i make changes to the code and previous changes were not merged.

**Comment by SanjeevSingh08** [comment]
> ok @Sboonny , One more question - If the #49081 issue was closed. Then why there is no change on the actual website. I mean if the code is not updated like in my case when i cloned the repo, the button was still not in the centre.And if i make changes to the code and previous changes were not merged, it will  create issue

**Comment by Sboonny** [comment]
this https://github.com/freeCodeCamp/freeCodeCamp/pull/48911 needs to be merged and deployed

**Comment by SanjeevSingh08** [comment]
ok i am working on it

**Pull request closed without merging**
