### PR TITLE
fix personal library boilerplate links destination

### PR DESCRIPTION
**Pull request by yasaminyaldaei**
Checklist:

- [x] I have read [freeCodeCamp's contribution guidelines](https://contribute.freecodecamp.org).
- [x] My pull request has a descriptive title (not a vague title like `Update index.md`)
- [x] My pull request targets the `master` branch of freeCodeCamp.
- [x] All the files I changed are in the same world language, for example: only English changes, or only Chinese changes, etc.

The boilerplate links for the personal library project led nowhere. I found the correct ones in a previous commit to `personal-library.md` file.

### CODE REVIEW

**Comment by nhcarrigan** [comment]
Hello @yasaminyaldaei !

Thank you for your interest in contributing! This error is also being addressed in #40266 - hey @RandellDawson should this be reviewed/merged since we are working on the linting error in the other PR?

As an aside, I recommend reviewing our [contributing documentation](https://contribute.freecodecamp.org), specifically the section regarding working off a branch and keeping your `master` branch clean. 🙂

**Comment by RandellDawson** [comment]
It can be merged.  If there are any merge conflicts, I will resolve them.

**Review by RandellDawson — APPROVED** [review]
LGTM

**Review by naomi-lgbt — APPROVED** [review]
LGTM~! 🥳 

Congratulations on your first pull request to this project! We look forward to future contributions!

**Pull request merged**
