### PR TITLE
fix: update confusing welcome page copy

### LINKED ISSUE #17302: Quotes need quotes around them
Be sure to use smart quotes as they'll look better:

&ldquo; and &rdquo;

welcome__quincy_larson____freecodecamp

### LINKED ISSUE #17305: Fix font weights on welcome page and settings
welcome__quincy_larson____freecodecamp

settings___freecodecamp

settings___freecodecamp_

profile___freecodecamp_

### PR DESCRIPTION
**Pull request by QuincyLarson**
#### Pre-Submission Checklist

- [x] Your pull request targets the `staging` branch of freeCodeCamp.
- [x] Branch starts with either `fix/`, `feature/`, or `translate/` (e.g. `fix/signin-issue`)

#### Type of Change

- [x] Small bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds new functionality)
- [ ] Breaking change (fix or feature that would change existing functionality)
- [ ] Add new translation (feature adding new translations)

#### Checklist:

- [ ] Tested changes locally.
- [ ] Addressed currently open issue (replace XXXXX with an issue no in next line)

Closes #17302, 
Closes #17305

### CODE REVIEW

**Comment by scissorsneedfoodtoo** [comment]
Hi @QuincyLarson! I hope you don't mind, but I was playing around with the quote marks earlier today and just have one suggestion.

I also tried the method you use here, `span &ldquo;#{quote}&rdquo;`, but noticed that the right double quote kind of hovers over the period:

inline

The easiest way I could find to solve that problem was by wrapping the quote in quote tags: 
```
span 
        q #{quote}
```

q-tag

Then there's a little spacing between the period and right double quote. It's a pretty minor detail, though.

**Comment by raisedadead** [comment]
@QuincyLarson I have fixed up those ugly merge commits that crept in. @scissorsneedfoodtoo Thanks for your QA. I have taken in your suggestion. It looks much better.

**Review by raisedadead — APPROVED** [review]

**Comment by raisedadead** [comment]
This is live on the main site.

**Comment by QuincyLarson** [comment]
@scissorsneedfoodtoo Thanks for cleaning up the quotes! 👍

**Comment by scissorsneedfoodtoo** [comment]
No problem! I'm really liking all the new quotes and the way you reworked the words/quote logic, too.

**Pull request merged**
