### PR TITLE
Fixed example code in Use-Spans-for-Inline-Elements Challenge

### LINKED ISSUE #7118: Minor error in example code for 'use-spans-for-inline-elements'
In the example code given for highlighting 'hate' text, the supplied colon in the code is omitted.

```<p>Top 3 things cats <span class = "text-danger">hate</span></p>```

should really be:

```<p>Top 3 things cats <span class = "text-danger">hate</span>:</p>```

### PR DESCRIPTION
**Pull request by NolanChan**
In the _Use-Spans-for-Inline-Elements_ challenge, changed 

`<p>Top 3 things cats <span class = "text-danger">hate</span></p>` to 
`<p>Top 3 things cats <span class = "text-danger">hate:</span></p>` 

to reflect the codemirror

npm tests pass:
total:     710
passing:   710

screen shot 2016-02-19 at 12 16 09 pm

closes #7118

### CODE REVIEW

**Comment by garbark** [comment]
Please stop sending me the page I don't know what to do with the right now
I have not been on the page all day

Gary M Barker

**Comment by sludge256** [comment]
@garbark Please read this if you do not wish to receive notifications from this Github repo https://help.github.com/articles/unwatching-repositories/

**Comment by garbark** [comment]
I'm not going to do anything for you and other's I don't know what you
talking about I have not post any of the problem thank you all for help
please stop playing with the page all day I have not been on the page at
all thank you

Gary M Barker

**Comment by sludge256** [comment]
@NolanChan Could you modify the PR to adhere to these [guidelines](https://github.com/FreeCodeCamp/FreeCodeCamp/blob/staging/CONTRIBUTING.md#common-steps)? Thanks.

**Comment by bugron** [comment]
@NolanChan please, don't include issue numbers in your PR's title or commit message (on branch name).

**Comment by NolanChan** [comment]
@bugron & @sludge256 : I believe the two infringing elements are gone; I removed the issue number from the title and commit message. I believe everything else should be good, but please tell me what you find!

**Comment by Greenheart** [comment]
@NolanChan Great work! :)

**Comment by NolanChan** [comment]
I assume a moderator pulls in my PR?

**Comment by Greenheart** [comment]
@NolanChan yes, as soon as they think you PR is ready :)

**Comment by ltegman** [comment]
:+1:

**Pull request merged**
