### PR TITLE
docs: Removed how-to-work-on-guide-articles from 4 languages

### PR DESCRIPTION
**Pull request by ilse-macias**
Removed guide articles in Spanish, Russian, Chinese and Portuguese.

- [x] I have read [freeCodeCamp's contribution guidelines](https://github.com/freeCodeCamp/freeCodeCamp/blob/master/CONTRIBUTING.md).
- [x] My pull request has a descriptive title (not a vague title like `Update index.md`)
- [x] My pull request targets the `master` branch of freeCodeCamp.
- [x] None of my changes are plagiarized from another source without proper attribution.
- [x] All the files I changed are in the same world language (for example: only English changes, or only Chinese changes, etc.)
- [x] My changes do not use shortened URLs or affiliate links.

Closes #XXXXX

### CODE REVIEW

**Comment by lynxlynxlynx** [comment]
LGTM, thanks!

**Review by lynxlynxlynx — APPROVED** [review]

**Comment by RandellDawson** [comment]
@lynxlynxlynx Thanks for reviewing this PR.  Could you review PR# 37222 which is an earlier PR which makes changes to the same file?  Also, if you are OK with those changes, go ahead and merge it and then review PR #37027 (also an earlier PR) which also makes changes to this same file.

Thanks.

**Comment by RandellDawson** [comment]
Actually, there is no more guide, so the changes to this file are not needed.  The file should actually be deleted instead of changed.  @ilse-macias Can you please use this PR do delete the file instead and commit that change?

Thank you.

**Comment by lynxlynxlynx** [comment]
Same holds for russian, chinese and portuguese.

**Comment by RandellDawson** [comment]
@lynxlynxlynx That is correct.

**Comment by ilse-macias** [comment]
@lynxlynxlynx @RandellDawson 
Thank you, I removed guide articles in spanish, russian, chinese and portuguese, as you requested.
Please check my latest commit.

**Comment by RandellDawson** [comment]
That should work.  I have updated your PR title to better reflect what your PR does now.

**Review by RandellDawson — APPROVED** [review]

**Comment by RandellDawson** [comment]
@raisedadead Merge if you are OK with these changes.

**Pull request merged**
