### PR TITLE
correct translation, typos, wording

### PR DESCRIPTION
**Pull request by bairamau**
- [x] I have read [freeCodeCamp's contribution guidelines](https://github.com/freeCodeCamp/freeCodeCamp/blob/master/CONTRIBUTING.md).
- [x] My pull request has a descriptive title (not a vague title like `Update index.md`)
- [x] My pull request targets the `master` branch of freeCodeCamp.
- [x] None of my changes are plagiarized from another source without proper attribution.
- [x] My article does not contain shortened URLs or affiliate links.

If your pull request closes a GitHub issue, replace the XXXXX below with the issue number.

Closes #XXXXX

### CODE REVIEW

**Review by greggubarev — CHANGES_REQUESTED** [review]
Please imrpove translate at line 

- [ ] 6

**Comment by bairamau** [comment]
The translation at line 6 seems correct to me and its corresponding to the English version

**Comment by greggubarev** [comment]
> The translation at line 6 seems correct to me and its corresponding to the English version

Выравните != выравнивание
Before translation was better

**Comment by bairamau** [comment]
the translation for **alignment** is **выравнивание**
the translation for *align* is **выравнить**

The English title states :
> **Align** Elements Using the align-items Property
so i adapted it as **выравните**.
The previous translation is machine-made and is totally incorrect

**Comment by greggubarev** [comment]
Выравнивание элементов используя свойство align-items - i mean this option

**Review by greggubarev — APPROVED** [review]

**Pull request merged**
