### PR TITLE
fix(curriculum): Fixed typo in step 82 hint text for music player project 

### LINKED ISSUE #52906: Fix typo in step 82 hint text for music player project
### Describe the Issue

The word statement is misspelled in this first hint for step 82 of the music player project

```md
You should create an if statment with the condition nextSongExists.
```

# Note to contributors 

This issue is marked available for contribution. The first comprehensive PR created will be reviewed and merged. We typically do not assign issues to anyone other than long-time contributors.

If you would like to contribute and have not read the contributors docs, please do so here: https://contribute.freecodecamp.org/#/

Here is the file you will need to change
https://github.com/freeCodeCamp/freeCodeCamp/blob/main/curriculum/challenges/english/15-javascript-algorithms-and-data-structures-22/learn-basic-string-and-array-methods-by-building-a-music-player/655b4bbff1dbf66cb2ed4dac.md

If you have any issues with contributing, be sure to join us on the [contributors channel](https://discord.com/channels/692816967895220344/715074489422970962), or on the [contributors sub-forum](https://forum.freecodecamp.org/c/contributors/3)

Happy coding! 

### Affected Page

https://www.freecodecamp.org/learn/javascript-algorithms-and-data-structures-v8/learn-basic-string-and-array-methods-by-building-a-music-player/step-82

### Your code

N/A

### Expected behavior

Fix typo in first hint text

### Screenshots

Screenshot 2024-01-02 at 8 39 06 PM

### System

- Device: [e.g. iPhone 6, Laptop]
- OS: [e.g. iOS 14, Windows 10, Ubuntu 20.04]
- Browser: [e.g. Chrome, Safari]
- Version: [e.g. 22]

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by ajcruise007**
Checklist:

- [x] I have read and followed the [contribution guidelines](https://contribute.freecodecamp.org).
- [x] I have read and followed the [how to open a pull request guide](https://contribute.freecodecamp.org/#/how-to-open-a-pull-request).
- [x] My pull request targets the `main` branch of freeCodeCamp.
- [x] I have tested these changes either locally on my machine, or GitPod.

Fix #52906

### CODE REVIEW

**Comment by jdwilkin4** [comment]
Hi @ajcruise007 ! 

Thank you for your interest in contributing to freeCodeCamp. 

Before we can review your PR you will need to remove the changes you made to the non english files.
You will also need to properly link the issue you are working on to your PR 
https://docs.github.com/en/issues/tracking-your-work-with-issues/linking-a-pull-request-to-an-issue

**Comment by ajcruise007** [comment]
Hi @jdwilkin4 , updated the pr and change is only made to the English file.

**Comment by jdwilkin4** [comment]
> You will also need to properly link the issue you are working on to your PR
https://docs.github.com/en/issues/tracking-your-work-with-issues/linking-a-pull-request-to-an-issue

You will still need to do this part to so the issue is properly linked to the PR

If you need help with that, then let us know 👍

**Comment by ajcruise007** [comment]
Hi @jdwilkin4 , linked it to the issue.

**Review by gikf — APPROVED** [review]
LGTM :+1:

**Review by jdwilkin4 — APPROVED** [review]
Congrats on your first contribution to our repository. 🎉
We look forward to future contributions. 👍

**Pull request merged**
