### PR TITLE
Updated Instructions and added a test case.

### LINKED ISSUE #8515: Access MultiDimensional Arrays With Indexes
Challenge [Access MultiDimensional Arrays With Indexes](https://www.freecodecamp.com/challenges/access-multidimensional-arrays-with-indexes#?solution=%0A%2F%2F%20Setup%0Avar%20myArray%20%3D%20%5B%5B1%2C2%2C3%5D%2C%20%5B4%2C5%2C6%5D%2C%20%5B7%2C8%2C9%5D%2C%20%5B%5B10%2C11%2C12%5D%2C%2013%2C%2014%5D%5D%3B%0A%0A%2F%2F%20Only%20change%20code%20below%20this%20line.%0Avar%20myData%20%3D%20myArray%5B0%5D%5B0%5D%20%2B%20myArray%5B2%5D%5B0%5D%3B) has an issue.
User Agent is: <code>Mozilla/5.0 (Windows NT 6.1; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/50.0.2661.94 Safari/537.36</code>.
Please describe how to reproduce this issue, and include links to screenshots if possible.

My code:
```javascript

// Setup
var myArray = [[1,2,3], [4,5,6], [7,8,9], [[10,11,12], 13, 14]];

// Only change code below this line.
var myData = myArray[0][0] + myArray[2][0];
```

I think the code used to validate the answer in this challenge has a bug. 
Could you please investigate.

### PR DESCRIPTION
**Pull request by pranayberry**
#### Pre-Submission Checklist

- [x] Your pull request targets the `staging` branch of FreeCodeCamp.
- [x] Branch starts with either `fix/`, `feature/`, or `translate/` (e.g. `fix/signin-issue`)
- [x] You have only one commit (if not, [squash](https://github.com/FreeCodeCamp/FreeCodeCamp/wiki/git-rebase#squashing-multiple-commits-into-one) them into one commit).
- [x] All new and existing tests pass the command `npm run test-challenges`. Use `git commit --amend` to amend any fixes.
#### Type of Change

- [x] Small bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds new functionality)
- [ ] Breaking change (fix or feature that would change existing functionality)
- [ ] Add new translation (feature adding new translations)
#### Checklist:

- [x] Tested changes locally.
- [x] Closes currently open issue (e.g. `Closes #XXXX`): Closes #8515 
#### Description

Updated description in challenge 'Access MultiDimensional Arrays With Indexes' so as to avoid confusion. Added the required test case and updated the previous test case for better flexibility.

Thanks 
@erictleung for the help.

### CODE REVIEW

**Comment by raisedadead** [comment]
@pranayberry This just changes the instructions. 
This does not however close the issue.
As pointed by @erictleung in his [comment](https://github.com/FreeCodeCamp/FreeCodeCamp/issues/8515#issuecomment-217750864) you would still need to add a test case.

**Comment by ltegman** [comment]
@pranayberry Do you have any plans to implement the suggestions from @raisedadead or should this PR be closed?

**Comment by pranayberry** [comment]
@ltegman I am working on it.

**Comment by erictleung** [comment]
@pranayberry LGTM! Thanks! 👍

**Pull request merged**
