### PR TITLE
Fix/ Missing CSS Selectors in code example

### PR DESCRIPTION
**Pull request by Hpauric**
#### Pre-Submission Checklist

- [x] Your pull request targets the `staging` branch of freeCodeCamp.
- [x] Branch starts with either `fix/`, `feature/`, or `translate/` (e.g. `fix/signin-issue`)
- [x] You have only one commit (if not, [squash](http://forum.freecodecamp.com/t/how-to-squash-multiple-commits-into-one-with-git/13231) them into one commit).
- [x] All new and existing tests pass the command `npm test`. Use `git commit --amend` to amend any fixes.

#### Type of Change

- [x] Small bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds new functionality)
- [ ] Breaking change (fix or feature that would change existing functionality)
- [ ] Add new translation (feature adding new translations)

#### Checklist:

- [x] Tested changes locally.
- [ ] Closes currently open issue (replace XXXX with an issue no): Closes #XXXX

#### Description

The code example in Sass: Nesting CSS with Sass was missing CSS element selectors. These have been added.

### CODE REVIEW

**Review by Greenheart — APPROVED** [review]
@Hpauric Thanks for the fix!

Was there an issue about this? We usually tag the issue like `Closing #XXXXX` to link the issue + PR and automate the closing of the issue.

If there is none, it doesn't matter though :blush:

**Comment by raisedadead** [comment]
@Greenheart Pull requests as patch should not be merged, they should follow the guidelines regarding branch naming.

**Comment by raisedadead** [comment]
There is a certainty that the OP did not test this locally because the PR came from the GitHub interface.

**Comment by Greenheart** [comment]
@raisedadead Sorry for that. I tested this in my local environment and concluded that it fixed an issue.

I need to look at details such as branch naming more closely.

**Comment by raisedadead** [comment]
Sure not a problem, just a heads up.

**Comment by Hpauric** [comment]
Sorry for the confusion 😅 There was no open issue 😃

**Comment by Greenheart** [comment]
@Hpauric Don't worry, I guess this was a learning experience for both of us! ^^

Feel free to tackle other issues if you want to!

**Pull request merged**
