### PR TITLE
feat(Cypress): reduce test time by disabling video upload on pass

### PR DESCRIPTION
**Pull request by Sembauke**
Checklist:

- [x] I have read [freeCodeCamp's contribution guidelines](https://contribute.freecodecamp.org).
- [x] My pull request has a descriptive title (not a vague title like `Update index.md`)
- [x] My pull request targets the `main` branch of freeCodeCamp.
- [x] I have tested these changes either locally on my machine, or GitPod.

As I discussed with Oliver, disabling video upload on pass should reduce testing time.
Should still upload when test fails.

### CODE REVIEW

**Comment by raisedadead** [comment]
Did you mean to close this?

**Comment by ojeytonwilliams** [comment]
@Sembauke is it just that it didn't save time in practice?

**Comment by Sembauke** [comment]
> @Sembauke is it just that it didn't save time in practice?
It just seemed really unclear if it had any effect.
I looked at different PR workflows and they seem to end around the same time as this one.
So I wasn't sure if this was worth doing.

**Comment by ojeytonwilliams** [comment]
Understood.  It was definitely worth conducting the experiment, but I agree that this doesn't seem to have obviously helped.

**Pull request closed without merging**
