### PR TITLE
Update broken URL

### LINKED ISSUE #34504: Information Security and Quality Assurance Projects - Metric-Imperial Converter : example app not functioning
**Describe your problem and how to reproduce it:**
The example app (hard-twilight) is not working properly, neither with Firefox nor with Chrome. Instead I get an explorer with the public source files.

**Add a Link to the page with the problem:**
https://learn.freecodecamp.org/information-security-and-quality-assurance/information-security-and-quality-assurance-projects/metric-imperial-converter
Direct link to the app: 
https://hard-twilight.glitch.me/

**Tell us about your browser and operating system:**
* Browser Name: Firefox and Brave
* Browser Version: latest
* Operating System: Ubuntu 18.04
challenge

**If possible, add a screenshot here (you can drag and drop, png, jpg, gif, etc. in this box):**

### PR DESCRIPTION
**Pull request by doubleUTF**
@scissorsneedfoodtoo- Please see New Glitch URL

The former project URL links to a malfunctioning web page. I decided to replace the link that leads to an identical, working project implemented by myself. 
Old, broken project page: https://hard-twilight.glitch.me/
New Glitch URL:  https://incongruous-beard.glitch.me/ ~~https://languid-pen.glitch.me~~
Glitch edit URL:  https://glitch.com/edit/#!/join/75f5cf20-00c9-4a79-bc3c-18ad7f57f1f1

- [x] I have read [freeCodeCamp's contribution guidelines](https://github.com/freeCodeCamp/freeCodeCamp/blob/master/CONTRIBUTING.md).
- [x] My pull request has a descriptive title (not a vague title like `Update index.md`)
- [x] My pull request targets the `master` branch of freeCodeCamp.
- [x] None of my changes are plagiarized from another source without proper attribution.
- [x] My article does not contain shortened URLs or affiliate links.

If your pull request closes a GitHub issue, replace the XXXXX below with the issue number.

Closes #34504

### CODE REVIEW

**Comment by nikrb** [comment]
@doubleUTF thanx for taking the time to open this pr.
When I run your app, at the link you provide, it doesn't appear to work and in the console I see `Reference error: event is not defined ... 62:11`.
I tried `4gal` in the text field and hit the convert button. Am I doing something wrong?

**Review by ezioda004 — APPROVED** [review]
Dont mind my review, I was checking another PR and had the tab mixed up.

**Comment by doubleUTF** [comment]
@nikrb The link at [https://languid-pen.glitch.me](https://languid-pen.glitch.me) seems to work for me. I type in '4gal', hit convert and it looks fine. Could you double check with another browser? All tests seem to have passed. 

A separate problem I noticed is that the original index.html template does not contain an error handling property in the ajax call; meaning errors are silent and show up in the console. I will start implementing this so that errors are properly handled and show gracefully in the template.

**Comment by doubleUTF** [comment]
Glad to hear  @nikrb  :smiley:

**Comment by nikrb** [comment]
@doubleUTF  sorry for the delay here. I think we use FCC examples. I'm trying to get some guidance

**Comment by doubleUTF** [comment]
@nikrb What do you mean by FCC examples and what kind of guidance are you looking for? I submitted this PR because the sample link to the [FCC Metric-Imperial Converter](https://learn.freecodecamp.org/information-security-and-quality-assurance/information-security-and-quality-assurance-projects/metric-imperial-converter) is broken and I'm just replacing it with a working one made by myself.

**Comment by ezioda004** [comment]
@doubleUTF @nikrb means that we'd want to use something "official" from fcc itself. Since, the last example broke and we cant fix it because it was submitted by a user, we'd like to avoid this foot-gun again.

Give us sometime and we'll update you with a decision regarding this.

**Comment by doubleUTF** [comment]
@ezioda004 Sure thing.

**Comment by thecodingaviator** [comment]
Hi @doubleUTF thank you for your PR but now we are no longer accepting links or other resources (images, etc.) which are not under our control, i.e. which a user or service might remove and is not under our control.

I'm closing this PR for the same reason as above, hope to see more contributions from you! ✈️

**Comment by doubleUTF** [comment]
@thecodingaviator I got no problem with that policy, but that link has been down for over 6 months and I thought a working solution would be better than a broken one. Please tell me how you intend on rectifying the current project and how I can contribute in a way that would be accepted because I don't have access to the original project link.

**Comment by thecodingaviator** [comment]
@RandellDawson would be able to provide more insight on that. I understand what you’re getting at

**Comment by RandellDawson** [comment]
@doubleUTF Can you create an issue about this, so we can discuss it there, before any PRs are created.

Thanks

**Comment by doubleUTF** [comment]
@RandellDawson I believe several issues have already been created pertaining to this problem:
[#34504](https://github.com/freeCodeCamp/freeCodeCamp/issues/34504)
[#34551](https://github.com/freeCodeCamp/freeCodeCamp/issues/34551)

Should I go ahead and create another one or just hop onto one of them to discuss?

**Comment by RandellDawson** [comment]
@doubleUTF Add your comment to #34504.

**Comment by scissorsneedfoodtoo** [comment]
@RandellDawson and @thecodingaviator, could do do a quick review? The new URL is now from the fCC camperbot account on Glitch.

**Review by thecodingaviator — DISMISSED** [review]
I've tested the API and it works for me. LGTM!

**Comment by RandellDawson** [comment]
Using the api, I was not able to validate the following two tests work as intended.
>If my number is invalid, returned with will 'invalid number'.
>If both are invalid, return will be 'invalid number and unit'.

What do I have to enter to get these return values?

**Comment by doubleUTF** [comment]
@RandellDawson Good catch, I made a small adjustment in the convertHandler.js to properly handle no units. Now if you input '13/13/13', it should return 'invalid number'. Inputting '13/13/13p' will return 'invalid number and unit.' 
@scissorsneedfoodtoo I made changes in my original [languid-pen Glitch](https://api.glitch.com/git/languid-pen). If or when Randell decides to approve the changes, could you pull the latest version again?

**Comment by thecodingaviator** [comment]
> Using the api, I was not able to validate the following two tests work as intended.
> 
> > If my number is invalid, returned with will 'invalid number'.
> > If both are invalid, return will be 'invalid number and unit'.
> 
> What do I have to enter to get these return values?

Nice catch! I somehow missed that.

**Comment by scissorsneedfoodtoo** [comment]
@doubleUTF, no problem, making the changes now. Thanks for catching that @RandellDawson!

**Comment by RandellDawson** [comment]
@doubleUTF Wouldn't `13/13/13` be `0.07692307692`?  How is `0.07692307692` an invalid number?

I actually expect the following to return `invalid number`.

https://languid-pen.glitch.me/api/convert?input=1a3lbs

**Comment by doubleUTF** [comment]
@RandellDawson That's another good catch for the '1a3lbs'' case and should indeed return an invalid message. I will look into this.

Regarding the '13/13/13' case, the original test cases shown in the [boilerplate project](https://github.com/freeCodeCamp/boilerplate-project-metricimpconverter/blob/gomix/tests/2_functional-tests.js) specifically state that these input values should return an invalid statement.

**Comment by Manish-Giri** [comment]
@doubleUTF Thanks for your patience with this PR. As I'm sure you understand, we get a lot of Pull Requests, and even though we actively review them to ensure each PR moves forward quickly, it may not always be possible to merge all of them right away.

Having said that, as a general practice, when we come across a bug or discrepancy in a challenge that an open PR addresses, we always try to ensure the bug can be fixed through the open PR itself unless it's a significant or breaking change.  Accordingly, I think if you are able to, you should update this PR to submit the required changes to address the '13/13/13' and '1a3lbs' cases. 

We will separately submit a PR to update the corresponding user stories and test cases.

**Comment by doubleUTF** [comment]
@Manish-Giri. Sure thing, but first I'll have to see that PR to see the updated test cases and user stories. I can't make any assumptions about the test cases. If there are any additional edge cases, they need to be explicitly included. If I update this project to satisfy the aforementioned cases and then a reviewer brings up another case that was not mentioned beforehand, then it would be unfair to expect that of a contributor like me. 

Since I'm being asked to deliver more than what was originally required, I'll have to wait and see the updated boilerplate project first.

For the '13/13/13' case, it's supposed to fail:

>       test('Convert 3/7.2/4kg (invalid number)', function(done) {
>         // This project passes
>         //done();
>       });  
>       
>       test('Convert 3/7.2/4kilomegagram (invalid number and unit)', function(done) {
>         // This project passes
>         //done();
>       });
>

**Comment by thecodingaviator** [comment]
@RandellDawson Since the OP has deleted their fork of the repo, no changes can be made to this PR anymore. Either we merge it as is or close it. Your call

**Comment by doubleUTF** [comment]
@thecodingaviator I'll close it for you, I don't plan on working on this PR anymore.

**Comment by scissorsneedfoodtoo** [comment]
Sorry, I'm just seeing this now. Thank you for getting this project working again, @doubleUTF. The most recent version of the Metric Imperial Converter project is at https://incongruous-beard.glitch.me/, so the URL will need to be updated. `master` is still showing the broken project at https://hard-twilight.glitch.me/.

**Comment by nikrb** [comment]
@scissorsneedfoodtoo I'll keep an eye on this and update it if we don't hear back from doubleUTF.

**Comment by scissorsneedfoodtoo** [comment]
Thanks @nikrb. I took a crack at fixing the issues listed here. Could you all check it out?: https://excited-nyala.glitch.me/

13/13/13 now returns 'no unit', and 13/13/13[unit] works as expected. Obviously broken inputs like 1a3lbs and 1a3lbz should also return `invalid number` and `invalid number and unit`, respectively.

**Pull request closed without merging**
