### PR TITLE
fix(seed): Add Test for Unique Challenge Titles

### LINKED ISSUE #16906: [Beta] Coding Interview Algorithm Questions section - Something went wrong
#### Challenge Name

https://beta.freecodecamp.org/en/challenges/coding-interview-algorithm-questions/inventory-update

#### Issue Description

Loading any challenge from the Coding Interview Algorithm Questions section gives Something went wrong message and checking the browser console shows:
`Failed to load resource: the server responded with a status of 500 ()`

```
Error: {"output":{"message":"Cannot read property 'isComingSoon' of undefined"},"meta":{}}
    at Object.callback (http.client.js:199)
    at n (index.js:62)
    at XMLHttpRequest.i (index.js:129)
    at XMLHttpRequest.o [as __zone_symbol___onload] (zone.js:1064)
    at e.invokeTask (zone.js:424)
    at t.runTask (zone.js:191)
    at XMLHttpRequest.invoke (zone.js:486)
```

#### Browser Information

* Browser Name, Version: Google Chrome 64.0.3282.186 (Official Build) (32-bit)
* Operating System: windows 7 32-bit
* Mobile, Desktop, or Tablet: Desktop

#### Your Code

```js

### PR DESCRIPTION
**Pull request by scissorsneedfoodtoo**
#### Pre-Submission Checklist

- [x] Your pull request targets the `staging` branch of freeCodeCamp.
- [x] Branch starts with either `fix/`, `feature/`, or `translate/` (e.g. `fix/signin-issue`)
- [x] You have only one commit (if not, [squash](http://forum.freecodecamp.org/t/how-to-squash-multiple-commits-into-one-with-git/13231) them into one commit).
- [x] All new and existing tests pass the command `npm test`. Use `git commit --amend` to amend any fixes.

#### Type of Change

- [x] Small bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds new functionality)
- [ ] Breaking change (fix or feature that would change existing functionality)
- [ ] Add new translation (feature adding new translations)

#### Checklist:

- [x] Tested changes locally.
- [ ] Addressed currently open issue (replace XXXXX with an issue no in next line)

Closes #16906

#### Description

Due to the recent problem with two challenges having the same title, I
added a check for unique titles to the test suite so that hopefully
won't happen again.

Addresses issue #16906, which was recently closed.

BREAKING CHANGE: None

### CODE REVIEW

**Comment by mstellaluna** [comment]
@scissorsneedfoodtoo Do you happen to know which issue number this is related to?

**Comment by scissorsneedfoodtoo** [comment]
@mstellaluna, yes, this is for issue #16906. Sorry I forgot to include it earlier!

**Comment by scissorsneedfoodtoo** [comment]
@raisedadead, there are some conflicts due to the new pack and unpack features. I'd be happy to refactor the tests here to more closely match the changes with that recent merge. But before I start, which do you think is better? Close this PR and start again from the updated staging branch? Or pull all the changes to staging into this branch and squash those commits?

**Comment by raisedadead** [comment]
Yes, you can do a rebase on this branch and then add you changes and force push to update the PR.
But starting off fresh from staging could be simpler IMHO.

**Comment by scissorsneedfoodtoo** [comment]
Okay! Thank you. I'll take a good look at the new code and try to submit another PR from staging soon.

**Comment by raisedadead** [comment]
Ok great... thanks a lot. I am going ahead closing this PR on that note.

**Pull request closed without merging**
