### PR TITLE
chore(api): remove unused code and endpoints

### PR DESCRIPTION
**Pull request by raisedadead**

### CODE REVIEW

**Review by RandellDawson — DISMISSED** [review]
@raisedadead All the deleted files seem to be fine removed (I was most interested in the cat.json file being removed, but it is handled in `client/static/json/cats.json`), but I have a question.  When I try to go to `http://localhost:8000/the-fastest-web-page-on-the-internet`, I get a 404 error.  I assume we are doing some kind of 301 redirect for this to show in production?

**Comment by raisedadead** [comment]
We serve it off of `client/static/the-fastest-web-page-on-the-internet/index.html`, you can serve it in gatsby development, but you should be able to see it when you use gatsby serve on a built client application.

A change request was made on the PR, does this answers your query?

**Comment by RandellDawson** [comment]
> We serve it off of `client/static/the-fastest-web-page-on-the-internet/index.html`, you can not see being served in gatsby development, but you should be able to see it when you use gatsby serve on a built client application.
> 
> A change request was made on the PR, does this answer your query?

I just thought it was strange, that I can go to `http://localhost:8000/json/cats.json` just find locally, but I can not go to `http://localhost:8000/the-fastest-page-on-the-internet/index.html`.

**Review by RandellDawson — APPROVED** [review]
After chatting with @raisedadead, I am fine with the changes, since he said regardless of me not being able to locally access `the-fastest page-on-the-internet` page, that it will not be a problem on production.  That was the only concern I had.

**Pull request merged**
