### PR TITLE
Add semicolon to inline CSS

### PR DESCRIPTION
**Pull request by nlakritz**
Using semicolons is recommended throughout the Basic CSS section.

- [x] I have read [freeCodeCamp's contribution guidelines](https://github.com/freeCodeCamp/freeCodeCamp/blob/master/CONTRIBUTING.md).
- [x] My pull request has a descriptive title (not a vague title like `Update index.md`)
- [x] My pull request targets the `master` branch of freeCodeCamp.
- [x] None of my changes are plagiarized from another source without proper attribution.
- [x] All the files I changed are in the same world language (for example: only English changes, or only Chinese changes, etc.)
- [x] My changes do not use shortened URLs or affiliate links.

Closes #XXXXX

### CODE REVIEW

**Comment by RandellDawson** [comment]
LGTM

**Comment by RandellDawson** [comment]
Will need to wait to merge until PR #27821 and PR #29979 have been merged first.

**Comment by RandellDawson** [comment]
@nlakritz Can you confirm you have the checkbox checked which allows maintainers to edit your PR?  I am getting a `permission denied` error when I try to push the changes which resolved the merge conflicts for this PR.  It will look like the following and be on the lower right-hand side of the PR body text.

image

Please let me know if it is or is not checked already.

Thanks.

**Comment by nlakritz** [comment]
@RandellDawson Yes, I can confirm that the checkbox has been, and still remains checked.

**Comment by RandellDawson** [comment]
I was finally able to resolve the merge conflict.

**Review by RandellDawson — APPROVED** [review]
Attention Mods: I have validated on all 6 languages, that the only thing changed is the addition of the `;` after `color: red`.  I approve this PR to be merged.  There are no earlier PRs with changes to these same files, so it can be merged right away by another mod who approves.

**Review by thecodingaviator — APPROVED** [review]
LGTM! 👍

**Comment by thecodingaviator** [comment]
@nlakritz Thank you for your contribution to the page! 👍
We're happy to accept these changes, and look forward to future contributions. 📝

**Pull request merged**
