### PR TITLE
Clarify instructions in "Insert an Element into a Max Heap"

### PR DESCRIPTION
**Pull request by TyMick**
Checklist:

- [x] I have read [freeCodeCamp's contribution guidelines](https://contribute.freecodecamp.org).
- [x] My pull request has a descriptive title (not a vague title like `Update index.md`)
- [x] My pull request targets the `master` branch of freeCodeCamp.
- [x] All the files I changed are in the same world language, for example: only English changes, or only Chinese changes, etc.

Changed "If the element is larger than its parents, switch them" to "If the element is larger than its **parent**, switch them". Reading the original I thought for a minute that an element could have more than one parent.

### CODE REVIEW

**Comment by moT01** [comment]
I have blocked this for now. See the [pinned code freeze issue](https://github.com/freeCodeCamp/freeCodeCamp/issues/38308)

**Comment by raisedadead** [comment]
Limitations removed on Coding Interview Prep Challenges.

**Review by moT01 — APPROVED** [review]
LGTM @tywmick 🎉

**Review by RandellDawson — APPROVED** [review]

**Comment by RandellDawson** [comment]
Thank you for your contribution to the page! 👍
We're happy to accept these changes, and look forward to future contributions. 🎉

**Pull request merged**
