### PR TITLE
fix(learn): split and simplified learn map

### LINKED ISSUE #38820: Split and simplify learn map
To make load time faster on learn, It would be great if we could have a list of all certificates (super blocks) on the learn page and once a user clicks on a certificate from the list, they would be redirected to the intro of that super block where a super block specific map is presented.

He is the list of super blocks that should be programmatically generated.
image

And if a user clicks on the first super block they should be directed to the intro page of a that super block that has an expandable map for that specific super block .
image

### PR DESCRIPTION
**Pull request by kabindrashrsth**
Checklist:

- [x] I have read [freeCodeCamp's contribution guidelines](https://contribute.freecodecamp.org).
- [x] My pull request has a descriptive title (not a vague title like `Update index.md`)
- [x] My pull request targets the `master` branch of freeCodeCamp.
- [x] All the files I changed are in the same world language, for example: only English changes, or only Chinese changes, etc.

Closes #38820

I have tested on a local copy of the site.

This is my draft PR. All the superblocks are displayed on the learn page and when the user clicks on the superblocks, they will be redirected to the intro page of that superblock and the list of blocks will be displayed. Since there is no markdown file for Coding Interview Prep, clicking on the superblock of Coding Interview Perp will give a 404 error. Other than that, everything works as expected.

I would appreciate any feedback on this PR. Thank you!

### CODE REVIEW

**Comment by kabindrashrsth** [comment]
I think the Travis CI test is failing because the tests expect SuperBlocks to expand, but the changes I made prevents the superblock from expanding and redirects to an intro page.

**Comment by raisedadead** [comment]
Thanks for working on this. @ahmadabdolsaheb can you guide here further.

**Comment by ahmadabdolsaheb** [comment]
Thanks for submitting this initial pr. 

Here are some considerations:
- since the /map links are not expandable, we should style them similar to the landing page's certification links until we roll out the link buttons with the upcoming landing page redesign. #39179 
- the carrots on the maps of each superblock should look similar to the live /learn page, and should resize on smaller screens similar to the live /learn page.
- we should also reduce the size of data we are prefetching on /learn. currently we are fetching all of the challenges and find the unique superblocks to display. Moving forward we should either make the graphql query only return a list of challenge nodes that has unique superblocks, or create superblock nodes in gatsby-nodes.js and query those using graphql.
- we should also reduce the size of data we are prefetching on each superblock intro. currently we are prefetching all of the challenges. We could make a custom query for the superblock intro pages preferably.
- the prefetched page-data.json file could be seen in the network tab after a hard refresh.
- we should add a markdown file to the  Coding Interview Perp, it could be a generic file similar to other certifications. 
- the map tests should be altered to reflect the current shape of the map, and superblock map tests should be added.

let me know if you are unclear about any of the above points so we could discuss them further.

**Comment by kabindrashrsth** [comment]
@ahmadabdolsaheb Thank you for your feedback. I'll work on those points.

**Comment by kabindrashrsth** [comment]
@ahmadabdolsaheb For the fifth point, could you give me some pointers on how to prevent page-data.json from appearing in the network tab?

**Comment by ahmadabdolsaheb** [comment]
> @ahmadabdolsaheb For the fifth point, could you give me some pointers on how to prevent page-data.json from appearing in the network tab?

It always should appear, but it should have less items in it.
image


Currently it is using a query that loads all of the challenge data.
To reduce its size you could refer to the third and forth point.

**Comment by kabindrashrsth** [comment]
I worked on all the mentioned points and pushed my changes, but the Cypress tests failed. I'm working on getting that test to pass.

**Comment by kabindrashrsth** [comment]
Ready for review! I would appreciate any feedback on this PR. Thank you!

**Comment by ahmadabdolsaheb** [comment]
@kabindrashrsth, Great job.
Thank you for your progress on this PR. it looks great.

Optimizing the learn page query has minimized the size of page-date.json to 1/6 of master which is great improvement. Could you investigate if SuperBlockIntroPageBySlug query could be any leaner?

Ultimately we would like to have the learn query only pull the relevant superblocks data instead of loading thousands of nodes. That should be doable by modifying the gatsby-node.js. I would appreciate it if you investigate that as well.

Also the is a Warning: Each child in a list should have a unique "key" prop. error on /learn and a
Failed prop type: The prop `pathname` is marked as required in `DefaultLayout`, but its value is `undefined`. error on superblocks intros. please check your browser console for those.

lastly, some cypress tests are appreciated.

@RandellDawson, we would need some intros for the superblocks before we ship this, would you be interested in sourcing those?

**Comment by kabindrashrsth** [comment]
@ahmadabdolsaheb Thanks for the feedback! I'll work on the mentioned points.

**Comment by raisedadead** [comment]
Hi @kabindrashrsth how is this coming along? If you need any help or clarifications, please do let us know.

**Comment by kabindrashrsth** [comment]
@raisedadead Hello! So far, I've fixed issues related to both warnings. I'm currently working on minimizing SuperBlockIntroPageBySlug query. 

As for the learn query, in my last PR, I added a filter on the graphql query such that it only relevant superblock data. So even now, the learn query does not load thousands of nodes. I understand that doing it from gatsby-node.js might be a better solution, and I did try to do it, but I couldn't get it right. I'll look into it again. Do want the gatsby-node.js solution before you close this issue?

Lastly, could you please let me know what I should be including in the cypress tests?

Would you like me to submit a PR for review? I might be able to minimize the SuperBlockIntroPageBySlug query to some extent by tomorrow.

**Comment by raisedadead** [comment]
Hi @kabindrashrsth 

Thanks a lot for your hard work on this one. This coming along real well actually, I am going to tag @ojeytonwilliams to advice on your queries.

Thanks for your patience.

**Comment by raisedadead** [comment]
hi @kabindrashrsth 

Can you sync this up with the latest master? To make it easier for you:

1. First squash all the commits on this PR to one.
2. Rebase against master and apply your changes as needed.

Thanks.

**Comment by kabindrashrsth** [comment]
@raisedadead I'm sorry for taking a while. I have been getting errors with Cypress tests. I will fix and send a PR as soon as possible.

**Comment by raisedadead** [comment]
Thanks for the update, there is no rush - take you time. Thanks for working on this. Let us know if we can be of help.

**Comment by ahmadabdolsaheb** [comment]
@kabindrashrsth, thank you for your progress on this feature, please let us know if you need any help with implementing this solution.

**Comment by kabindrashrsth** [comment]
@ahmadabdolsaheb thank you for your patience! I've resolved all the issues and have squashed all the commits into one. I think the PR is ready for review.

**Review by raisedadead — DISMISSED** [review]
I am really happy with the PR, some of things that we should add to this PR would be: 

1. Let's keep all the accordions in the individual super-block pages in the open state by default.

2. I would also consider removing those stub texts completely in favor of just the title of the superblock as a centered H2 on the superblock pages.

3. I think we should figure out the back navigation (going back to the superblock we are in at given time with some form of a bread-crumb style menu) - @ahmadabdolsaheb could you guide here.

**Comment by ahmadabdolsaheb** [comment]
> I am really happy with the PR, some of things that we should add to this PR would be:
> 
> 1. Let's keep all the accordions in the individual super-block pages in the open state by default.
> 2. I would also consider removing those stub texts completely in favor of just the title of the superblock as a centered H2 on the superblock pages.
> 3. I think we should figure out the back navigation (going back to the superblock we are in at given time with some form of a bread-crumb style menu) - @ahmadabdolsaheb could you guide here.

**Comment by kabindrashrsth** [comment]
@raisedadead Thank you for your feedback. I will work on those points.

**Comment by moT01** [comment]
Hey @kabindrashrsth, I was just taking a look at some of them - any interest in pairing up? Not sure if you are on gitter, but you can DM me there @moT01 - Or perhaps, is there somewhere I can DM you?

**Comment by kabindrashrsth** [comment]
@moT01 Sure! I'll DM you in gitter.

**Comment by moT01** [comment]
I rebased this against `next-i18n-client`. If @kabindrashrsth can change the PR to target that branch, it should be good to go.

I did notice a tiny bit of slowness relative to production when expanding some of the sections. Project Euler was particularly slow, maybe up to a second - not so slow that I would hold this up. I thought it was from this PR, there's certainly some room for speeding up some things, but I get the same slowness on master - so I don't think the issue is here.

**Comment by kabindrashrsth** [comment]
@moT01 I have changed the PR to target next-i18n-client!

**Comment by nhcarrigan** [comment]
I'm getting build errors when calling `npm run develop`. I've tried rebasing against `next-i18n-client` locally and repulling the changes from this PR, but I'm still having no luck. Is anyone else getting errors or am I missing something?

image

**Comment by moT01** [comment]
I am not getting those errors on this PR @nhcarrigan. I am getting similar errors on a different branch I have - but they say it's a graphql error.

**Comment by nhcarrigan** [comment]
Yep - they're GraphQL errors on my end too - but they cause the client to error out and not build. I'm also getting them on the `next-i18n-client` branch, but not on `master`.

**Comment by moT01** [comment]
Still no problems on my end:
node: 14.4.0
npm: 6.14.5
High Sierra: 10.13.6

What are you using? I assume you tried reinstalling packages and things. I am looking at [some gatsby config](https://www.gatsbyjs.com/docs/reference/graphql-data-layer/schema-customization/#fixing-field-types) that I think may help with my issues - not sure why you can't run this PR though - may be related.

**Comment by nhcarrigan** [comment]
I've got:
node: 14.15.1
npm: 6.14.9
Windows 10: 1909

Yeah, I've tried a full `npm ci` on both `master` and these branches, with still no luck.

**Comment by raisedadead** [comment]
Just a reminder, we haven't switched to Node 14 yet - I would recommend being on Node 12, until we have switched officialy.

**Comment by kabindrashrsth** [comment]
@nhcarrigan I was getting a different error but it was solved by doing `cp sample.env .env` (on Windows: `copy sample.env .env`) and then `npm ci`.

**Comment by nhcarrigan** [comment]
That was the trick - I had the `CLIENT_LOCALE` value but was missing the `CURRICULUM_LOCALE`.

Have this working locally now - will review this today.

**Comment by nhcarrigan** [comment]
Gave this a look locally, and everything seems to work as intended. Before approving, just a couple of thoughts I had:

- Should each superblock have a landing/intro page? Or text above the map?
- There is no progress indicator on the superblocks now - while the previous layout did not have one, everything was on one page so progress could be viewed quickly.

**Comment by moT01** [comment]
> Should each superblock have a landing/intro page? Or text above the map?
The plan is to add some intro text to each super block page with a future PR.

> There is no progress indicator on the superblocks now - while the previous layout did not have one, everything was on one page so progress could be viewed quickly.
I don't think we need to change anything there with this PR. The behavior is nearly identical to production. You can see the progress of each block within the superblock you are looking at. Not sure how we would add something to show the progress of the entire map with this implementation - could maybe add something to show the overall progress of the super block.

**Review by naomi-lgbt — APPROVED** [review]
LGTM~! 🥳 The other features can be explored in future PRs as desired. 

Thank you for your pull request! We look forward to additional contributions!

**Review by scissorsneedfoodtoo — APPROVED** [review]
:sparkles: :sparkles: :sparkles: Awesome! Congratulations on your first contribution to freeCodeCamp! :sparkles: :sparkles: :sparkles:

Thank you for all of your hard work on this @kabindrashrsth. This looks great, and we're excited to include this in our upcoming release.

Looking forward to your next contribution :+1: :+1:

**Comment by moT01** [comment]
Thanks for the work on this and helping me out @kabindrashrsth 🎉

**Comment by kabindrashrsth** [comment]
yay!! Thank you all so much for your help and patience! I really enjoyed working on this PR and I learned a lot from this experience.  
:relaxed:

**Pull request merged**
