### PR TITLE
fix: various multifile editor bugs

### LINKED ISSUE #42806: test-suite/jaws for project based curriculum disappeared after typescript migration
More info: https://github.com/freeCodeCamp/freeCodeCamp/issues/39348#issuecomment-876832306

### PR DESCRIPTION
**Pull request by ojeytonwilliams**
The issue was caused by the shift to functional components, since the Editor relied a lot on internal state (not React state) that needed to be present when the monaco editor mounted.  Using React state meant those values existed, but before `editorWillMount` and `editorDidMount` were called.

This PR handles everything with `useRef` instead, since that can be updated on the fly without triggering a new render.

Should fix #42806

### CODE REVIEW

**Comment by ShaunSHamilton** [comment]
Small bug, I stumbled on in: `/learn/responsive-web-design/basic-html-cat-photo-app/part-66`

```
Uncaught Error: Illegal value for lineNumber
    at TextModel.getLineContent (textModel.js:521)
    at positionsToRange (editor.tsx:1021)
    at eval (editor.tsx:796)
    at Array.map (<anonymous>)
    at decorateForbiddenRanges (editor.tsx:795)
    at editorWillMount (editor.tsx:275)
    at MonacoEditor.editorWillMount (editor.js:118)
    at MonacoEditor.initMonaco (editor.js:109)
    at MonacoEditor.componentDidMount (editor.js:53)
```

**Review by ShaunSHamilton — APPROVED** [review]
The above mentioned issue appears to be prior-existing, and largely unrelated. So, this LGTM 👍 

Many, many thanks, for fixing this, and tidying the editor all up, Oliver.

**Comment by ojeytonwilliams** [comment]
No worries. Thanks for all you've done to improve the editor. We're gradually getting it into shape.

**Review by Sembauke — APPROVED** [review]
it might be useful to start code splitting the editor file it's over 1k lines and for the average contributor, it might be really hard to understand.

Maybe split the multi-editor logic from the normal editor and place it in the MultifileEditor.js file.

It is only a suggestion everything else Looks good to me

**Comment by ojeytonwilliams** [comment]
@Sembauke yeah, it's definitely hard to understand.  

There's not really *that* much about this which has to do with the multiple files - it's just the `useRefs` that hold various parts of the editor's state.  We could lift that up into the multifile editor and pass it in as props, though.

We could also pull the config out to separate .json files.

**Pull request merged**
