### PR TITLE
feat: add python syntax highlighting

### PR DESCRIPTION
**Pull request by ojeytonwilliams**
To err on the side of caution, this explicitly includes all languages that were implicitly included before using the Babel plugin.

This is just the Python part of https://github.com/freeCodeCamp/freeCodeCamp/pull/38730/.  The rest could take some time to complete, but the Python highlighting can be enabled independently.

Answer with highlighting:

PythonAnswerHigh
without:
PythonAnswersBefore
Description with highlighting:
PythonDescBefore
without
PythonDescriptionHigh

and nightmode:

PyAnsNight
PyDescNight

### CODE REVIEW

**Review by raisedadead — APPROVED** [review]

**Comment by raisedadead** [comment]
> but the Python highlighting can be enabled independently.

Can you elaborate on this action item before I merge this.

**Comment by ojeytonwilliams** [comment]
> > but the Python highlighting can be enabled independently.
> 
> Can you elaborate on this action item before I merge this.

Sure, the [plugin](https://www.npmjs.com/package/babel-plugin-prismjs) requires you to specify the languages you would like Prism to highlight.  I've listed all the ones I think we were highlighting before and added Python to that list.

**Comment by raisedadead** [comment]
Cool, so there is there any change to the source markdown? I am sorry, I do not have all the understanding of how the syntax gets rendered.

**Comment by ojeytonwilliams** [comment]
Nope, it's done dynamically.  All the person writing the Markdown has to do is use the appropriate language tag on their code block and Prism takes care of the rest.

So, for example if this was in a question

````
```py 
width = 15
height = 12.0
print(height/3)
```
````

that gets transformed a bit (by the parser, if memory serves), but the high level perspective is that Prism will see the tag and transform it so it will look like this in the challenge:

```py
width = 15
height = 12.0
print(height/3)
```

**Comment by Sky020** [comment]
Sorry to butt in, but does explicitly defining languages to highlight, implicitly tell the plugin to ignore unmentioned languages?

That is, should we include _SASS_ and _SCSS_? Perhaps _SQL_?

**Comment by ojeytonwilliams** [comment]
> does explicitly defining languages to highlight, implicitly tell the plugin to ignore unmentioned languages?

Yes, that's exactly right.  However, everything was implicit before, by which I mean I had to go through the source to find which languages are included by default.

> should we include SASS and SCSS? Perhaps SQL?

The problem is Prism's default highlighting is quite different from the editor's.  https://github.com/freeCodeCamp/freeCodeCamp/pull/38730 adds SCSS and attempts to make code outside and inside the editor look the same.  It's a bit of a compromise and it's not finished. (the explanation's in the PR).

Adding SQL is probably fine, though.  cc: @moT01

**Comment by Sky020** [comment]
Hey @ojeytonwilliams , is this a consequence of this PR:
image
There is a background added to the code blocks.

As you can see in the picture, if the class `language-python` is removed from the `pre` tag, the background disappears. (I removed the class). Is there a way to have just the child `code` block inherit the class?

**Comment by ojeytonwilliams** [comment]
Thanks Shaun, I'm glad you caught that.

> Is there a way to have just the child code block inherit the class?

Possibly, but I don't know of a nice way to do so, and it's easy enough to fix with css.  I've made the changes in here: https://github.com/freeCodeCamp/freeCodeCamp/pull/39090

**Pull request merged**
