### PR TITLE
French Translation JavaScript Basics n°1 and n°2

### PR DESCRIPTION
**Pull request by mizujin**
#### Pre-Submission Checklist

- [X] Your pull request targets the `staging` branch of FreeCodeCamp.
- [X] Branch starts with either `fix/`, `feature/`, or `translate/` (e.g. `fix/signin-issue`)
- [X] You have only one commit (if not, [squash](https://github.com/FreeCodeCamp/FreeCodeCamp/wiki/Git-Squash) them into one commit).
- [ ] All new and existing tests pass the command `npm run test-challenges`. Use `git commit --amend` to amend any fixes.
#### Type of Change

- [ ] Small bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds new functionality)
- [ ] Breaking change (fix or feature that would change existing functionality)
- [X] Add new translation (feature adding new translations)
#### Checklist:

- [ ] Tested changes locally.
- [ ] Closes currently open issue (replace XXXX with an issue no): Closes #XXXX
#### Description

This is a fix to PR #9585 that was probably dropped. The translation are for the first two challenges of the basic javascript :
- Comment your JavaScript Code
- Declare JavaScript Variables
  
  and is part of issue #7635

### CODE REVIEW

**Comment by raisedadead** [comment]
@mizujin awesome work with the recent translation pull requests, is there anyone who could QA these and let us know if the translations are good to go? 

We can merge post a peer review. I am sure you can find some peers in the Chat rooms to help in this effort.

**Comment by mizujin** [comment]
@raisedadead Thanks! I know it sounds weird but I was the one to QA the original PR, So this current PR are my proposed fixes included. I can ask around on the chat rooms, but french translation room have been quite silent this past month.

**Comment by raisedadead** [comment]
Cool no issues we will merge after a week or so if no one turns up, thanks a lot for contributing.

**Comment by raisedadead** [comment]
Merging, this will help us in testing the beta site. @mizujin thanks a lot for contributing.

**Pull request merged**
