### PR TITLE
Save bonfire's solution as a GitHub gist

### LINKED ISSUE #1343: Feature Request: Push Bonfire solutions to Gist
I'd like to be able to save a Bonfire solution as a Gist on github.

### PR DESCRIPTION
**Pull request by bugron**
Adds the feature requested in https://github.com/FreeCodeCamp/FreeCodeCamp/issues/1343. Looks like this: http://prntscr.com/8vvgd7, two examples of gists: https://gist.github.com/anonymous/29ee0f9a9e21d34e78eb, https://gist.github.com/anonymous/8a9f708ac77a7c002011.
A couple of words about the implementation. By clicking that "create gists" button a new blank window is opened. After that we perform an AJAX `post` request to `api.github.com/gists` with the appropriate data (`data` object). From `api.github`'s response we get the `html_url` of the newly created **anonymous** gist. Then we change the window's `location.href`.
You should notice two things:
1. These gists are anonymous because we need to get user's authentication info to make them authorized (and I've no idea how to do that). As @BerkeleyTrue said "I don’t think there is going to be a way that we can share that information with the client side" (if user's GitHub account is linked to user's FCC account).
2. The new window is going to be blank until we get the answer from `api.github.com/gists`.
This is done because the browser will normally block the window like any other pop-up. To avoid this we need to open the window immediately after the button click and do any manipulations (in this case changing `location.href`) after AJAX request.
Another way is performing a synchronous AJAX request but this will freeze the browser until GitHub's response.
Closes #1343.

### CODE REVIEW

**Comment by ltegman** [comment]
Really wish the nature of how this works didn't mean it had to be anonymous but it looks great. Looks like  my PR #3984 may have created a merge conflict on this. Sorry about that!

**Comment by BerkeleyTrue** [comment]
@bugron We will give the issue a week of discussion. If no objects then we will QA and merge this.

**Comment by bugron** [comment]
@ltegman no worries, @BerkeleyTrue as you like it.

**Comment by SaintPeter** [comment]
If we can control the content going into the GIST it might be good to add a header with FCC Information:
```js
// Bonfire:Where Art Thou
// Author: @SaintPeter
// Challenge: http://www.freecodecamp.com/challenges/bonfire-where-art-thou
// Learn to Code at Free Code Camp (www.freecodecamp.com)
```

Ordering and content are flexible, of course, but we might as well identify ourselves.

**Comment by bugron** [comment]
@SaintPeter done. If user is [logged in](https://gist.github.com/anonymous/e54a16ff2380709aa57c) and if not the same without `// Author: @username`: [link](https://gist.github.com/anonymous/01febd16ea956fc98fc7).

**Comment by SaintPeter** [comment]
Brilliant.  Looks great!
:+1:

**Comment by bugron** [comment]
Maybe change gist's title to something like this: "`@username`'s solution for `some challenge`", where `@username` is a link to FCC account and `some challenge` is the title of the challenge (for example, Bonfire: Meet Bonfire)?

**Comment by SaintPeter** [comment]
Yeah, I like that too.

**Comment by bugron** [comment]
Seems that won't work. [This](https://gist.github.com/anonymous/ed550869a2e2d2ed7052) is the best I can do. (better then these: [one](https://gist.github.com/anonymous/7bd012915abd4ab6fd78), [two](https://gist.github.com/anonymous/98b7c9151ba5df02f11d), [three](https://gist.github.com/anonymous/227c93816164a1eb9dd8), [four](https://gist.github.com/anonymous/48815eadd81791fa8a0c), [five](https://gist.github.com/anonymous/e02f9a28cd45576b3274), [six]()). And when [logged out](https://gist.github.com/anonymous/b8d7156cb1bc2018855e). Is this acceptable?

**Comment by SaintPeter** [comment]
Those seem like reasonable titles to me.

**Comment by SaintPeter** [comment]
I think this one looks good to go.

**Comment by BerkeleyTrue** [comment]
Agreed. Anyone have time to QA this?

**Comment by ltegman** [comment]
Looks really good. Only issue I'm seeing is that if a user hasn't linked up their GitHub the username will show up like the following example:
```javascript
// Bonfire: Reverse a String
// Author: @fcca56baa66
// Challenge: http://localhost:3000/challenges/bonfire-reverse-a-string
// Learn to Code at Free Code Camp (www.freecodecamp.com)

//This is a test
function reverseString(str) {
  return str.split('').reverse().join('');
}

reverseString("hello");
```

Assuming it's not a huge amount of work it's probably worth removing that and posting as if they weren't logged in since it isn't meaningful, but I don't know that it's worth spending a lot of time on.

**Comment by BerkeleyTrue** [comment]
It should be left as is. More incentive to the user to create a Github account and link it with freecodecamp.

**Comment by ltegman** [comment]
Looks good then! :smile:. Merging.

**Comment by GregFoley** [comment]
This doesn't seem to work for me. After my gist appears on the site I can't find it in either "your gists" or the stream of recent gists.

**Comment by bugron** [comment]
@GregFoley that's because these gists are anonymous.

**Pull request merged**
