### PR TITLE
Make nouns plural in keeping with 'world objects'

### PR DESCRIPTION
**Pull request by joaquinfox**
Sentence subject 'real world objects' is plural, so noun derivatives should be plural as well.

- [x] I have read [freeCodeCamp's contribution guidelines](https://github.com/freeCodeCamp/freeCodeCamp/blob/master/CONTRIBUTING.md).
- [x] My pull request has a descriptive title (not a vague title like `Update index.md`)
- [x] My pull request targets the `master` branch of freeCodeCamp.
- [x] None of my changes are plagiarized from another source without proper attribution.
- [x] My article does not contain shortened URLs or affiliate links.

If your pull request closes a GitHub issue, replace the XXXXX below with the issue number.

Closes #XXXXX

### CODE REVIEW

**Comment by moT01** [comment]
This sentence doesn't make sense either way - Shouldn't it be like this...
"Objects are useful for storing data in a structured way and can be used to represent real world objects like cars, hotels, or a computer."

**Comment by joaquinfox** [comment]
That does read better, I agree.

**Comment by moT01** [comment]
@joaquinfox you should be able to make an edit to this to change that sentence to what I mentioned, then we can add it - and again, make sure you go over that checklist...
[x] My article does not contain shortened URLs or affiliate links.
 ^add x's to indicate you've gone over the list

**Review by joaquinfox — COMMENTED** [review]
Grammar and readability edits

**Comment by moT01** [comment]
Thanks @joaquinfox, LGTM

**Pull request merged**
