### PR TITLE
chore(snyk): Update snyk config

### PR DESCRIPTION
**Pull request by raisedadead**
This updates the snyk config to `prepare` hook from the deprecated
`prepublish` hook

### CODE REVIEW

**Comment by BerkeleyTrue** [comment]
I think we should actually remove snyk auto installing. It is quite slow and not really useful outside production environment.

**Comment by raisedadead** [comment]
Ah.. I see and agree, so just to confirm should be simply removing the scripts related to snyk from package.json?

Do we need any additional script to run `protect` when building for production? What's the workflow in that case.

**Comment by BerkeleyTrue** [comment]
We should just create a script to use in production. `npm run snyk`?

**Comment by raisedadead** [comment]
Yes, sure how about something like:

```js
{
   ...
   "scripts": {
     ...
     "build": "NODE_ENV=production gulp build -p",
     ...
     "production": "snyk protect && build"
     ...
   }
}
```
Should this suffice? Removing anything else in scripts.

**Comment by BerkeleyTrue** [comment]
I'd leave it as a separate command instead of bundling it for now

**Pull request merged**
