### PR TITLE
fix: arithmetic formatter tests

### PR DESCRIPTION
**Pull request by ojeytonwilliams**
Checklist:

- [x] I have read and followed the [contribution guidelines](https://contribute.freecodecamp.org).
- [x] I have read and followed the [how to open a pull request guide](https://contribute.freecodecamp.org/#/how-to-open-a-pull-request).
- [x] My pull request targets the `main` branch of freeCodeCamp.
- [x] I have tested these changes either locally on my machine, or GitPod.

We didn't really need pytest for these tests, so, rather than figuring out how to get it working, I removed it. This makes the code a lot cleaner and, because the assertion is no longer handled, we get readable errors to help with debugging.

### CODE REVIEW

**Review by ShaunSHamilton — APPROVED** [review]
Works a treat 👍

**Review by majestic-owl448 — COMMENTED** [review]
> we get readable errors to help with debugging.

how would I get this? I am not getting any readable errors trying the tests, no error at all actually

**Comment by ShaunSHamilton** [comment]
> how would I get this?

In the test-runner with `pnpm run test:curriculum`. By "we", he means "devs"/testers.

**Comment by ojeytonwilliams** [comment]
> By "we", he means "devs"/testers.

That's correct, but these errors do appear in the browser console too. I haven't updated the test runner to filter them out, yet.

**Review by Dario-DC — APPROVED** [review]
It works fine for me 🎉

**Pull request merged**
