### PR TITLE
fix(curriculum): correct wiki link for Standard deviation

### PR DESCRIPTION
**Pull request by ponomarevkonst**
Checklist:

- [x] I have read [freeCodeCamp's contribution guidelines](https://contribute.freecodecamp.org).
- [x] My pull request has a descriptive title (not a vague title like `Update index.md`)
- [x] My pull request targets the `main` branch of freeCodeCamp.
- [x] I have tested these changes either locally on my machine, or GitPod.

Just typo fix for wiki link to https://en.wikipedia.org/wiki/Standard_deviation

### CODE REVIEW

**Comment by ieahleen** [comment]
We can't accept a PR that changes the translated files, those are managed through automated pipelines

**Comment by nhcarrigan** [comment]
Heya @ponomarevkonst,

Have you had a chance to revisit ieahleen's review?

**Comment by moT01** [comment]
I went ahead and removed the changes to the other languages. This should be good to go.

**Review by gikf — APPROVED** [review]

**Review by majestic-owl448 — APPROVED** [review]

**Comment by ieahleen** [comment]
Hi @ponomarevkonst . Congrats on your first pull request (PR)! 🎉

Thank you for your contribution to the page! 👍
We are happy to accept these changes and look forward to future contributions. 📝

**Pull request merged**
