### PR TITLE
Add MDN links to guides arrow-functions and map

### PR DESCRIPTION
**Pull request by chrisdel101**
- [ x] I have read [freeCodeCamp's contribution guidelines](https://github.com/freeCodeCamp/freeCodeCamp/blob/master/CONTRIBUTING.md).
- [ x] My pull request has a descriptive title (not a vague title like `Update index.md`)
- [x ] My pull request targets the `master` branch of freeCodeCamp.
- [ x] None of my changes are plagiarized from another source without proper attribution.
- [x ] All the files I changed are in the same world language (for example: only English changes, or only Chinese changes, etc.)
- [ x] My changes do not use shortened URLs or affiliate links.

Attaching links to the guides as requested in [#34114](https://github.com/freeCodeCamp/freeCodeCamp/pull/34414)

### CODE REVIEW

**Comment by RandellDawson** [comment]
@chrisdel101 Why did you not just add the links in PR #34114?

**Comment by chrisdel101** [comment]
@RandellDawson This is my first PR so I don't have a good reason.

**Comment by RandellDawson** [comment]
I am closing this as a duplicate PR, because you already have the same changes to both 
 `guide/english/javascript/es6/map-function/index.md` and `guide/english/javascript/es6/arrow-functions/index.md` are in PR 34114.

**Comment by chrisdel101** [comment]
I can remove the ones from the other PR. I think that what was supposed to happen. Would you like me to do that?

**Comment by RandellDawson** [comment]
What do you mean it was an error for them being over in the earlier PR?  Were they changes you wanted to make to those files?  Either way, the addition of the MDN link to the one file is no longer needed, because another PR was already merged with a similar change.  The other change is fine in the other PR, because it definitely would be a good change to the verbiage of the article.

**Comment by chrisdel101** [comment]
The told me to remove and put it here. I did and forgot to remove it. I am just about to remove it and push to that PR. Should I not do that and leave 'it' in? (It being the way it is the that PR currently. Within the challenge) Otherwise I'll make this change inside that PR.

**Comment by RandellDawson** [comment]
Let me look at the other PR and get back to you.

**Comment by chrisdel101** [comment]
So I made the changes. If you won't like them I'll remove them.

**Comment by RandellDawson** [comment]
I must be missing something, because I could not find anything in PR 34114 about needing to create a separate PR for the guide articles.

**Comment by RandellDawson** [comment]
I will leave it up to you.  If you want to include the one change to `guide/english/javascript/es6/arrow-functions/index.md` on the other PR that is fine or on this PR, that is fine.  I will Reopen and you make the choice.

**Comment by chrisdel101** [comment]
I included this on the other PR so this can be closed again.

**Comment by chrisdel101** [comment]
@RandellDawson Here it is. Not ready yet. Just tagging

**Pull request closed without merging**
