### PR TITLE
paircode feature

### PR DESCRIPTION
**Pull request by aldraco**
No new dependencies.

Edits per comments found here: #322 

Slack handle is automatically populated; users specify if they want to pair on a bonfire, courseware, or both. Information is displayed conditionally on the next page, listing all the requests.

A modal pops up when the request is close to expiring; otherwise, if the user's request gets automatically deleted, a flash message informs them on the next page they visit.

:)

### CODE REVIEW

**Comment by terakilobyte** [comment]
This is a mountain of commits! I'll QA it today.

**Comment by BerkeleyTrue** [comment]
I seriously think I sleep-code. I have no recollections of adding `TODO` to this either.

This will probably need to be rebased on all the new changes made from the `challenge-restructure` merge from yesterday.

**Comment by terakilobyte** [comment]
@aldraco and @MrRenter 

This is a great looking pull request, but in discussion with @QuincyLarson I don't think FCC is ready for this.

We're going to implement a small-scale version of this that integrated with the slack api webhooks for now, until we're ready to revisit this idea in more detail.

Essentially, we've decided the the Free Code Camp of today can't deliver the user experience we want. Without proper sockets and a truly responsive frontend like React can give us we feel the UX would be mediocre at best.

As we move to LoopBack and React we're going to retool the server with RTC in mind. @QuincyLarson and I are in agreement about infrastructure scaling to support this overhead. At that point we'll look into adding a deep feature like this that also support notifications and communications within the FreeCodeCamp app itself.

Again, thanks for the effort on this you two. Not accepting this PR isn't because it isn't good, it's more a reflection on the current status of the FCC app itself.

**Comment by QuincyLarson** [comment]
I just want to compliment you two again on building such a cool feature and we can't wait to include it.

**Pull request closed without merging**
