### PR TITLE
fix(client): better contrast for code sections when selected

### LINKED ISSUE #40442: Low contrast on Code Selection: Can't See Anything
**Describe your problem and how to reproduce it:**

I had started noticing this a few days ago onward. The issue is that I can't see the code example when I highlight it. It has low contrast. The issue is similar to #39967. The surprising thing is that the highlight color is different in Chrome and FireFox Developer Edition.

**Add a Link to the page with the problem:**

https://www.freecodecamp.org/learn/javascript-algorithms-and-data-structures/functional-programming/use-the-reduce-method-to-analyze-data

The problem is in every challenges.

**Tell us about your browser and operating system:**
* Browser Name: Google Chrome & FireFox Developer Edition
* Browser Version: Version 87.0.4280.88 (Official Build) (64-bit) (Chrome) & Version 84.0b8 (64-bit) (FireFox)
* Operating System: Windows 10 64-bit

**If possible, add a screenshot here (you can drag and drop, png, jpg, gif, etc. in this box):**

image

The left is in Chrome & right is in FireFox.

### PR DESCRIPTION
**Pull request by ghost**
Checklist:

- [x] I have read [freeCodeCamp's contribution guidelines](https://contribute.freecodecamp.org).
- [x] My pull request has a descriptive title (not a vague title like `Update index.md`)
- [x] My pull request targets the `master` branch of freeCodeCamp.
- [x] All the files I changed are in the same world language, for example: only English changes, or only Chinese changes, etc.

Closes #40442

When the user selects the code in the challenges, there were a huge contrast issue. The text could not be seen as the selection background color was very bright. The bug is discussed in #40442. This PR fixes the issue by adjusting the selection background color to a lighter one, which works for both light and night mode.

File changed: `client/src/components/layouts/global.css`

Screenshots:

Before:

image

After:

image

image

This is my first PR in this repo, so if you find that I wrote the title and description in wrong format, kindly forgive me.

### CODE REVIEW

**Comment by raisedadead** [comment]
@ahmadabdolsaheb can you take a look at this, and merge if happy?

**Comment by ahmadabdolsaheb** [comment]
@paulsonjpaul, Thanks for the solution. 

There is a list of color variables in variables.css that we try to use as much as possible for consistency, so I tried to utilize them in this pr.

Since the additional changes affect the learn UI entirely, I encourage you to review them as well. 
We should wait for a second review before we go ahead with merging this just to be safe.

**Review by naomi-lgbt — APPROVED** [review]
LGTM~! 🥳 I've pulled this down locally, played around with it in light/dark modes, and I think the change is an improvement.

Congratulations on your first pull request to this project! We look forward to future contributions!

**Comment by paulsonjpaul** [comment]
Hi @nhcarrigan and @ahmadabdolsaheb for your review. Unfortunately, the issue still persists. Is it because @ahmadabdolsaheb changed the selector and color?

**Comment by raisedadead** [comment]
This code has not been deployed to production yet, and will be deployed in the upcoming weeks.

**Comment by paulsonjpaul** [comment]
> This code has not been deployed to production yet, and will be deployed in the upcoming weeks

Ok. 

> Are you able to reproduce the issue on you local setup?

I don't have a local setup. I have Gitpod setup.

**Comment by raisedadead** [comment]
Thanks, unless you can reproduce the issue on the master branch, (this PR's target), I recommend you to check back in a few weeks on production.

Happy contributing.

**Pull request merged**
