### PR TITLE
chore(client): remove bootstrap.min.css

### PR DESCRIPTION
**Pull request by huyenltnguyen**
Checklist:

- [x] I have read and followed the [contribution guidelines](https://contribute.freecodecamp.org).
- [x] I have read and followed the [how to open a pull request guide](https://contribute.freecodecamp.org/#/how-to-open-a-pull-request).
- [x] My pull request targets the `main` branch of freeCodeCamp.
- [x] I have tested these changes either locally on my machine, or GitPod.

This PR: 
- Removes the `bootstrap.min.css` stylesheet from the codebase
- Is related to #52030 

I'll comment on the code to explain each change, but the high-level approach is:
- We don't just rip `bootstrap.min.css` out, but we are replacing it with the `base.css` stylesheet exported from `@freecodecamp/ui`.
- We revised `base.css` and decided to include the [Tailwind preflight](https://tailwindcss.com/docs/preflight) in the file, which helps remove the inconsistencies in browser default styles. This change to `base.css` requires a `@freecodecamp/ui` major version bump.
- I wrote a script that grabs all class names from the Bootstrap stylesheet and finds the files in `/client` that have class names match those classes. I then checked the files and decided either to remove the classes or bring the classes/styles from `bootstrap.css` to `global.css`. I moved the CSS styles to an existing/custom class if the Bootstrap style is simple or used by a single component; otherwise I copy-pasted the styles from Bootstrap and would have another cleanup round (some require a considerable amount of code refactoring, I so would rather split that work to a separate PR).
  - Here is the PR (over my fork) with the script and the Bootstrap usages it found: https://github.com/huyenltnguyen/freeCodeCamp/pull/373.
- I also manually performed regression testing by going through each page and comparing the UI with production.

---

**Note for reviewers:** Be sure to run `pnpm i` when testing the PR locally.

## Testing

<details>
  <summary>Places I've checked (this is where I'm not methodical, I just wrote down a list of areas popped up in my head and checked them one by one)</summary>

  - Help modal
  - Donation modal
  - Completion modal
  - Shortcuts modal
  - Donation alert boxes
  - CTA buttons
  - Profile image and its responsiveness
  - Step-based grid
  - Lower jaw and upper jaw
  - Breadcrumb
  - C# challenges
  - C# exam
  - C# survey modal
  - RWD challenges
  - JS challenges
  - Python challenge
  - Certification project
  - A2 English challenges
  - Video-based lessons
  - The Odin project
  - Home page (/)
  - /learn
  - /settings
  - Profile page
  - /donate
  - /supporters
  - 404 page
  - /blocked
  - Certification page
  - Solution modal (on /settings)
  - Search box (on the nav)
  - Nav menu
  - Nav language selector
  - Footer
</details>

### CODE REVIEW

**Comment by Sembauke** [comment]
image

The placeholders inside the card input seem no longer centred.

**Review by Sembauke — COMMENTED** [review]
Some of the margins are a little off in the footer could you take a look at that?

**Comment by ahmaxed** [comment]
The border of the alert buttons seems affected:

Screenshot 2024-06-07 at 3 37 24 PM
Screenshot 2024-06-07 at 4 14 13 PM

**Review by ahmaxed — APPROVED** [review]

**Review by Sembauke — APPROVED** [review]
🎉 **CONGRATULATIONS** 🎉

**Pull request merged**
