### PR TITLE
fix(curriculum): Period added to the end of the sentence.

### LINKED ISSUE #42479: Missing period at the end of the third sentence.
**Affected page**
https://www.freecodecamp.org/learn/responsive-web-design/basic-html-and-html5/create-a-bulleted-unordered-list

**Your code**
Copy and paste the code from the editor that you used in between the back-ticks below:

```




```

**Expected behavior**
There should be a period at the end of the third sentence (Finally ...).

**Screenshots**
Screen

**System (please complete the following information):**
 - Device: [e.g. iPhone6, Laptop]
 - OS: [e.g. iOS 14, Windows 10, Ubuntu 20.4]
 - Browser: [e.g. chrome, safari]
 - Version: [e.g. 22]

**Additional context**

### PR DESCRIPTION
**Pull request by stephanduesterhoeft**
Period added to the end of the sentence.

Checklist:

- [x] I have read [freeCodeCamp's contribution guidelines](https://contribute.freecodecamp.org).
- [x] My pull request has a descriptive title (not a vague title like `Update index.md`)
- [x] My pull request targets the `main` branch of freeCodeCamp.
- [x] I have tested these changes either locally on my machine, or GitPod.

Closes #42479

### CODE REVIEW

**Comment by raisedadead** [comment]
Hi, @stephanduesterhoeft we recently merged one of your other PRs and going to let someone else work on the linked issue as a part of their first-timer PR.

At the same time, we would like to encourage you to work on something that interests you. Anything that is labelled "help wanted" is up for grabs.

Thanks again and happy contributing!

**Comment by stephanduesterhoeft** [comment]
Thank you!

**Comment by stephanduesterhoeft** [comment]
I found missing punctuation in several other places. Then, instead of a PR, should I rather open an issue so that other first-timers can do a PR?

**Comment by raisedadead** [comment]
> Then, instead of a PR, should I rather open an issue so that other first-timers can do a PR?

Actually, if that's the case you should instead bunch all of those together and make one single PR. 

While we would like to have more first-time PRs.  We would also want to encourage more meaningful PRs.

**Comment by raisedadead** [comment]
Yeah - that will be a very meaningful use of everyone's time. Thanks again for improving the codebase.

**Pull request closed without merging**
