### PR TITLE
revert : Added displayUsername and username update functionality

### PR DESCRIPTION
**Pull request by raisedadead**
removes implemenation from #35699
This reverts commit e154f38118be44b49e9a6a99dd88c447d008f9ac.

### CODE REVIEW

**Comment by raisedadead** [comment]
This is an emergency revert of the previous functionality which is broken as tested on .dev 

/cc @ojeytonwilliams @ahmadabdolsaheb

**Comment by raisedadead** [comment]
Just to add this maynot be a QA miss. The original PR was very old and I am not 100% if our bump of loopback or something is breaking something that is not compatible. We would probably want to do a implementation from scratch

**Comment by ojeytonwilliams** [comment]
It's possible I broke something when I was cleaning up the PR. What was going wrong?

**Comment by raisedadead** [comment]
We were unable to create new accounts on the staging. We were getting the 'Oops...' message.

I think it bombed in the authentication logic server side.

I haven't investigated, but reverting quickly at least isolated it to the PR. Also I had push the donation stuff life so I took the feature down for now. 

We can investigate and get it back. Sorry about that, and thanks for your hard work.

**Comment by ojeytonwilliams** [comment]
> We can investigate and get it back. Sorry about that, and thanks for your hard work.

Yeah, I just wondered if it was an avoidable mistake on my part.  Sounds like it's two things 1) no tests that involve client/server communication and 2) I should have done a sanity check (create a new account) before merging.

**Comment by raisedadead** [comment]
I think avoiding use cases like this one will fall under the #37053 work.

**Pull request merged**
