### PR TITLE
chore(npm-script): added dev to package.json/script

### PR DESCRIPTION
**Pull request by sarbbottam**
#### Pre-Submission Checklist
- [x] Your pull request targets the `staging` branch of FreeCodeCamp.
- [x] Branch starts with either `chore/`, `fix/`, `feature/`, or `translate/` (e.g. `fix/signin-issue`)
- [x] You have only one commit (if not, [squash](https://github.com/FreeCodeCamp/FreeCodeCamp/wiki/git-rebase#squashing-multiple-commits-into-one) them into one commit).
- [x] All new and existing tests pass the command `npm run test-challenges`. Use `git commit --amend` to amend any fixes.
#### Type of Change

- [ ] Small bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds new functionality)
- [ ] Breaking change (fix or feature that would change existing functionality)
- [ ] Add new translation (feature adding new translations)
- [x] Added dev to package.json/script (npm-script)
#### Checklist:
- [x] Tested changes locally.
- [ ] Closes currently open issue (e.g. `Closes #XXXX`): Closes 
#### Description

chore(npm-script): added `dev` to `package.json/script` to install `bower` dependencies and start the default `gulp` task

> In addition to the shell's pre-existing `PATH`, `npm run` adds `node_modules/.bin` to the `PATH` provided to scripts. Any binaries provided by locally-installed dependencies can be used without the `node_modules/.bin prefix`

For further details please refer [docs.npmjs.com/cli/run-script](https://docs.npmjs.com/cli/run-script)

### CODE REVIEW

**Comment by sarbbottam** [comment]
This change is neither `fix/`, `feature/`, `translate/` but to `chore/`. 😕

**Comment by theflametrooper** [comment]
@sarbbottam This PR seems unneeded to me. As far as I know, this was not related to any open Github issue.

Plus, this means every time someone want's to run freecodecamp, they have to reinstall `bower` components. You also got rid of the global install of `gulp` and `bower` which is required.

**Comment by sarbbottam** [comment]
> you also got rid of the global install of `gulp` and `bower` which is required.

They are installed locally

If all the dependencies can be sand-boxed locally why would you prefer global installation?

> they have to reinstall bower components

If there is no update `bower`, won't reinstall the dependencies, it will simply skip.

**Comment by theflametrooper** [comment]
@sarbbottam We need to have it installed globally and locally. To run the command `bower` you need a global installation.

**Comment by sarbbottam** [comment]
> To run the command `bower` you need a global installation.

Nope. Please read the PR description.

**Comment by sarbbottam** [comment]
BTW, this is by product of fixing https://github.com/FreeCodeCamp/FreeCodeCamp/issues/8575

**Comment by theflametrooper** [comment]
@sarbbottam Sorry for the confusion, you are correct about the global installation! Tagging @BerkeleyTrue 

However, I don't think this PR will be merged. The global installation is in place so the `gulp` command can be used across repos.

**Comment by sarbbottam** [comment]
>The global installation is in place so the `gulp` command can be used across repos.

Thats sad 😞  Every repo should be self sufficient, if there are no technology barrier / challenge. 
**Why rely on someone, installing a dependency globally, when you can enforce it locally. For global installation you can only suggest, can't enforce**, but for local installation it will get installed by default via `npm i`.

Not only that, as a contributor, you get rid of 3 extra steps.

I would suggest, let others take a look and go by majorities decision.

**Comment by BerkeleyTrue** [comment]
Gulp and Babel should be global, not deps of the project. 

Happy Coding!

**Comment by sarbbottam** [comment]
gulp - https://github.com/FreeCodeCamp/FreeCodeCamp/blob/staging/package.json#L62
babel - https://github.com/FreeCodeCamp/FreeCodeCamp/blob/staging/package.json#L32

both are being installed locally 😕

**Comment by theflametrooper** [comment]
@sarbbottam If i'm correct in saying, you always need a local copy of `gulp` for a project, even with a `global` instance already installed.

**Comment by sarbbottam** [comment]
I am not loosing hope, someday everything will be installed locally, sandbox everything 😄

**Pull request closed without merging**
