### PR TITLE
fix: claim legacy and full stack certifications

### PR DESCRIPTION
**Pull request by scissorsneedfoodtoo**
Checklist:

- [x] I have read and followed the [contribution guidelines](https://contribute.freecodecamp.org).
- [x] I have read and followed the [how to open a pull request guide](https://contribute.freecodecamp.org/#/how-to-open-a-pull-request).
- [x] My pull request targets the `main` branch of freeCodeCamp.
- [x] I have tested these changes either locally on my machine, or GitPod.

This PR is to fix the reported issues with claiming the legacy certifications from the settings page, including the Legacy Full Stack certification.

This solution is a bit different than the one we discussed, but treating the Legacy Full Stack certification like any other legacy certification by adding it to the `legacyCertifications` array in `shared/config/certification-settings.ts` breaks several other tests in `build-external-curricula-data.test.ts` and `certification.test.tsx`.

### CODE REVIEW

**Review by ShaunSHamilton — CHANGES_REQUESTED** [review]
Discussion needed. Specifically, do we need to add `Legacy2018FullStack` as an enum member?

**Comment by ojeytonwilliams** [comment]
>  breaks several other tests

Speaking of tests, something as important as being able to claim a cert really should have one. Do you mind adding one, Kris?

**Comment by scissorsneedfoodtoo** [comment]
Thanks for mentioning that @ShaunSHamilton. I agree we should discuss that before moving forward. We may be able to talk with Quincy and @raisedadead about it after the meeting tonight.

Also, sorry about that @ojeytonwilliams. I could have sworn that I updated my comment above asking whether e2e tests would be appropriate to test this or not, but I may have closed the tab too quickly. I can start working on adding tests for this now. I'm guessing that some Cypress tests would be the way to go here since we have some unit tests for the button disabled / enabled state already.

**Comment by raisedadead** [comment]
> ... may be able to talk with Quincy and @raisedadead about it after the meeting tonight.

Pretty sure we can call the 2018 cert "Legacy Full-Stack" so you can have two full-stack certs.

**Comment by scissorsneedfoodtoo** [comment]
@ojeytonwilliams, I was able to add some tests for the `ifNoCertification404` middleware, which is one of the things modified in this PR.

I also tried for a bit to add tests for `verifyCert`, but wasn't able to figure out how to test the different flash messages and response status. If you could point me in the right direction writing tests for `createVerifyCert` / `verifyCert`, that'd be great. Or if there are any other things that can be tested here, I'd be happy to work on those.

**Review by ShaunSHamilton — APPROVED** [review]
I am happy with this, and suggest we move it forward. We can iron-out the tests later if still required.

**Review by ojeytonwilliams — APPROVED** [review]
I'm fine with this for now. We can revisit testing when porting this to the new api.

LGTM :+1:

**Pull request merged**
