### PR TITLE
fix: Navbar breaks at 768px to 786px

### LINKED ISSUE #15839: Navbar breaks at 768px to 786px
#### Screenshot

breaks

### PR DESCRIPTION
**Pull request by JustusFT**
#### Pre-Submission Checklist

- [X] Your pull request targets the `staging` branch of freeCodeCamp.
- [X] Branch starts with either `fix/`, `feature/`, or `translate/` (e.g. `fix/signin-issue`)
- [X] You have only one commit (if not, [squash](http://forum.freecodecamp.org/t/how-to-squash-multiple-commits-into-one-with-git/13231) them into one commit).
- [x] All new and existing tests pass the command `npm test`. Use `git commit --amend` to amend any fixes.

#### Type of Change

- [X] Small bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds new functionality)
- [ ] Breaking change (fix or feature that would change existing functionality)
- [ ] Add new translation (feature adding new translations)

#### Checklist:

- [X] Tested changes locally.
- [X] Addressed currently open issue (replace XXXXX with an issue no in next line)

Closes #15839

#### Description
Reduced link padding when space gets too cramped. (from 15px to 10px)
Hide the username text when nav gets too small.

**Screenshots**
Signed in, 768px
screen shot 2017-10-26 at 07 10 59

Signed out, 768px
screen shot 2017-10-26 at 07 29 43

### CODE REVIEW

**Comment by QuincyLarson** [comment]
@JustusFT Thanks for this PR! Please note that we recently merged a PR that changed our navigation significantly: https://github.com/freeCodeCamp/freeCodeCamp/pull/15993

Can you take a look at this, address the merge conflicts, then let us know when you'd like us to take another look?

**Comment by JustusFT** [comment]
@QuincyLarson That was added in the master branch, so I don't have any conflicts related to the navbar. Do you want me to add the same thing in the beta version?

**Review by raisedadead — APPROVED** [review]
@JustusFT 

I have resolved the conflicts. 

Next time, I would recommend you to selectively add files that you change to the commit.
The `package-lock.json` should not be added unless you are changing any dependencies.

#### :sparkles: :sparkles: **LGTM.** :sparkles: :sparkles: 

Thanks and Happy coding!

**Comment by QuincyLarson** [comment]
@JustusFT Awesome - thanks for fixing this!

**Pull request merged**
