### PR TITLE
Fix when the nav tag has space, the last check is wrong.

### PR DESCRIPTION
**Pull request by ZTFtrue**
Checklist:

- [x] I have read [freeCodeCamp's contribution guidelines](https://contribute.freecodecamp.org).
- [x] My pull request has a descriptive title (not a vague title like `Update index.md`)
- [x] My pull request targets the `main` branch of freeCodeCamp.
- [x] I have tested these changes either locally on my machine, or GitPod.

Closes #XXXXX

### CODE REVIEW

**Review by yesidays — APPROVED** [review]

**Review by majestic-owl448 — COMMENTED** [review]
I fear that this change would make users expect the same from all other challenges - it's not wrong to have some more freedom for users, but we need to make sure it doesn't make too much work for making all tests have the same kind of freedom

for example, with this change it is possible to write `<nav >`, so why not `< nav >`, or `</nav >`?

I would be against this change

**Comment by ZTFtrue** [comment]
> 
> I fear that this change would make users expect the same from all other challenges - it's not wrong to have some more freedom for users, but we need to make sure it doesn't make too much work for making all tests have the same kind of freedom
> 
> for example, with this change it is possible to write `<nav >`, so why not `< nav >`, or `</nav >`?
> 
> I would be against this change

@ieahleen  You are right.  I have other ideas, maybe `freeCodeCamp` should provide courses about `space` or `code format`

**Comment by ieahleen** [comment]
@ZTFtrue why don't you write an article about it? there is always space for new articles on freecodecamp.org/news

**Comment by ieahleen** [comment]
Hey @username

Thank you for opening this pull request.

This is a standard message notifying you that we've reviewed your pull request and have decided not to merge it. We would welcome future pull requests from you.

Thank you and happy coding.

**Pull request closed without merging**
