### PR TITLE
fix: center certificates vertically when viewed on large screens

### LINKED ISSUE #37378: Certifications look buggy with new fonts
Please see below. The text has been shifted around a bit in some aspect ratios. We need to ensure that the text on certifications looks right on all screen sizes:

_5__freeCodeCamp_org_on_Twitter___We_are_taking_freeCodeCamp_down_so_we_can_deploy_some_major_changes__We_will_be_back_soon__In_the_meantime__our_YouTube_is_up_and_it_has_1_000__coding_tutorials_on_Python__SQL__Data_Science__and_Machine_Lea

### PR DESCRIPTION
**Pull request by DerrykBoyd**
- [x] I have read [freeCodeCamp's contribution guidelines](https://github.com/freeCodeCamp/freeCodeCamp/blob/master/CONTRIBUTING.md).
- [x] My pull request has a descriptive title (not a vague title like `Update index.md`)
- [x] My pull request targets the `master` branch of freeCodeCamp.
- [x] None of my changes are plagiarized from another source without proper attribution.
- [x] All the files I changed are in the same world language (for example: only English changes, or only Chinese changes, etc.)
- [x] My changes do not use shortened URLs or affiliate links.

Closes #37378

### CODE REVIEW

**Comment by dboydgit** [comment]
Screenshot with top margin added.
Screenshot from 2019-10-20 15-15-41

**Review by moT01 — CHANGES_REQUESTED** [review]
This only centers the cert when those conditions are met. If the screen is less than 1500px wide, it doesn't work...
Screen Shot 2019-10-21 at 10 25 40 AM

This also assumes that the cert will stay a constant 886px tall - if the height of the cert ever changes, it will no longer be centered. I would suggest using flexbox to center it - what I would do anyway.

Also, can anyone confirm that this is something we want to add @raisedadead? I'm fine with it.

**Comment by raisedadead** [comment]
Okay, let's land this PR and you can continue with the additional sizes if that's cool @moT01 ? If you are happy so far with the changes lets merge this?

**Comment by moT01** [comment]
I think you misunderstood me, I meant that I'm fine with centering the certifications. I didn't like approach on this PR.

> if the height of the cert ever changes, it will no longer be centered

**Comment by dboydgit** [comment]
The issue here is the height of the certificate will not be consistent due to wrapping text, certificates with more text will be taller on smaller screens. Do you have a suggestion for a fix when the height of the container is unknown?

The approach I took was to center the certificate only when it's at it's maximum dimensions.

**Comment by dboydgit** [comment]
Should be good now. Thanks for the suggestion @moT01

**Review by moT01 — CHANGES_REQUESTED** [review]
Screen Shot 2019-10-21 at 8 57 43 PM

My scroll bar is at the top in the picture, the cert is above the top of the page (when the window is short enough). Changing the `height` to `min-height` fixes this.

**Review by moT01 — APPROVED** [review]
LGTM 🎉 Thanks for fixing this @dboydgit 🎉

**Review by raisedadead — APPROVED** [review]

**Comment by raisedadead** [comment]
Thanks @dboydgit and @moT01

**Pull request merged**
