### PR TITLE
Fix sliding out/in for all waypoint slides

### LINKED ISSUE #4721: Step Waypoints: Old step should slide out while new step slides in

### PR DESCRIPTION
**Pull request by matthiaskern**
closes #4721.

### CODE REVIEW

**Comment by ltegman** [comment]
Thanks for the PR! Unfortunately your branch is 163 commits behind staging. You'll need to rebase onto the current version of staging to resolve the conflicts so this can be accepted.

**Comment by matthiaskern** [comment]
Done! Thought i'd done that when doing git fetch from upstream. Still learning git

**Comment by SaintPeter** [comment]
I tested this and it mostly works for the first slide only, and then only once.  Subsequent slides do not slide out, they just disappear.  Going back also does not work properly.

I'm going to leave this open if you want another stab at it, but please test more carefully.

**Comment by matthiaskern** [comment]
Tested new version for all "Get Started with Free Code Camp" Waypoints @SaintPeter

**Comment by bugron** [comment]
Looks good, waiting for others to QA.

**Comment by SaintPeter** [comment]
Here is what I see:
When I click next, the first slide moves to the left, then the next slide slides in.
For subsequent slides there is no sliding out motion.

Going backwards, the current slide disappears instantly and the prior slide slides in.

Here is a video:
https://www.youtube.com/watch?v=iZ6rcdyHa5M

**Comment by ltegman** [comment]
Huh. That's weird @SaintPeter. For me it looks just how you'd expect and works perfectly forwards and backwards.

**Comment by SaintPeter** [comment]
Ok, I blew away my local copy and made sure that I was looking at the right thing and, indeed, it seems to be working properly.  Sorry for the confusion.

**Comment by SaintPeter** [comment]
Also, thanks @matthiaskern!  Looks great!  :+1:

**Pull request merged**
