### PR TITLE
chore: migrate Landing component

### PR DESCRIPTION
**Pull request by kamatheuska**
Checklist:

- [x] I have read [freeCodeCamp's contribution guidelines](https://contribute.freecodecamp.org).
- [x] My pull request has a descriptive title (not a vague title like `Update index.md`)
- [x] My pull request targets the `main` branch of freeCodeCamp.
- [x] I have tested these changes either locally on my machine, or GitPod.

Closes #XXXXX

### CODE REVIEW

**Review by raisedadead — CHANGES_REQUESTED** [review]
Can you rename this file to kebab-case:

`client/src/components/landing/Landing.test.tsx`

**Comment by kamatheuska** [comment]
@raisedadead do you mean to rename **Landing.test.tsx** to **Landing-test.tsx**? Seems to me that the current naming is fine, since it is only on word. Do you refer to something else maybe?

**Comment by raisedadead** [comment]
Apologies, I misspoke earlier. 

I meant to say rename the file to lower case as we recommend in the migrations guidelines.

```diff 
- client/src/components/landing/Landing.test.tsx
+ client/src/components/landing/landing.test.tsx
```

**Comment by kamatheuska** [comment]
Sure thing! Just did it and pushed. Still, I see many other *.test.tsx files with PascalCase: e.g. 
- client/src/components/Intro/Intro.test.tsx
- client/src/components/Header/Header.test.tsx

Maybe we should change them also in the future?

**Comment by raisedadead** [comment]
Yes - please. I would recommend doing that in a separate PR if you are interested. 

Unless I am missing something, those files were missed in the migrations and are a simple oversight? @freeCodeCamp/dev-team do you know if this was not intentional for the test files?

**Comment by ojeytonwilliams** [comment]
> Unless I am missing something, those files were missed in the migrations and are a simple oversight?

I think so, too.  I can't think of reason to keep them upper case.

**Comment by kamatheuska** [comment]
ok, let me create a PR. Should I create an issue for that first?

**Comment by raisedadead** [comment]
> Should I create an issue for that first?

Nope. Not required in this case, please proceed with a PR ideally replacing all of those **already migrated files**. Make sure to check references in code too.

Thanks.

**Comment by kamatheuska** [comment]
@raisedadead Ok, I will do that now. Can this PR be merged then? There is an open change request blocking the merging from you, which is done now. Can we proceed?

**Comment by kamatheuska** [comment]
> Nope. Not required in this case, please proceed with a PR ideally replacing all of those **already migrated files**. Make sure to check references in code too.

https://github.com/freeCodeCamp/freeCodeCamp/pull/44261

**Comment by raisedadead** [comment]
> Can this PR be merged then? There is an open change request blocking the merging from you, which is done now. Can we proceed?

We merge PRs in due course being a small team and strive to be fair to all contributions alike. 

For instance, this particular component migration has been attempted by several others and have outstanding PRs. We will be able to update you once we have looked at prior PRs before this.

We will get back to you if we need additional changes or information.

Thanks for your contributions & your patience, meanwhile we encourage you to take a look at other help wanted issues that may interest you.

Cheers.

**Comment by kamatheuska** [comment]
oh sure not pb, completely understand. This is my first contribution to the project so I was just doing a follow back. Happy to contribute!

**Comment by moT01** [comment]
Hey @kamatheuska - Thanks for contributing 🎉 Unfortunately, these files were all migrated in other PR's that were created before this and are now merged. We won't be needing this PR anymore, so I am going to close it. If you have any objection to this, feel free to leave a message and we can discuss revisiting it.

 If you're looking for more to do, it looks like there's [quite a few other files that need migrating](https://github.com/freeCodeCamp/freeCodeCamp/issues/43778) 😉 Thanks again

**Pull request closed without merging**
