### PR TITLE
refactor: test output -> arrays

### PR DESCRIPTION
**Pull request by ojeytonwilliams**
This should not change anything's behaviour, but will make it possible to output a single test's results.

### CODE REVIEW

**Comment by ahmadabdolsaheb** [comment]
Initially consoleOut is [""] instead of [] which leads to the output not showing the default:
<code>
/**
* Your test output will go here.
**/
</code>



image



also, do we need to introduce a max or a limit for the logs or consoleOut?

**Comment by ojeytonwilliams** [comment]
Thanks Ahmad, I'll see about creating a Cypress test to make sure the default output is shown initially.

> also, do we need to introduce a max or a limit for the logs or consoleOut?

I don't think so, since they're just plain JavaScript arrays.  Possibly there's something I'm missing, but it should be fine.

**Comment by ojeytonwilliams** [comment]
The cypress tests are not 100% reliable (the first run failed), so I need to investigate.

**Comment by ojeytonwilliams** [comment]
@ahmadabdolsaheb everything should be behaving properly now.

**Review by ahmaxed — APPROVED** [review]

**Pull request merged**
