### PR TITLE
Fixed issue #1806

### PR DESCRIPTION
**Pull request by AryanJ-NYC**

### CODE REVIEW

**Comment by benmcmahon100** [comment]
Hey @AryanJ-NYC Has this been tested locally?

**Comment by AryanJ-NYC** [comment]
@benmcmahon100 It has not. I tried following the instructions to get freecodecamp running locally, but failed. Apologies.

**Comment by benmcmahon100** [comment]
What parts were causing issues?

**Comment by AryanJ-NYC** [comment]
I think it is my .env file. I assume I need my own MANDRILL API keys?

**Comment by benmcmahon100** [comment]
No you can leave out mandrill entirely!

**Comment by AryanJ-NYC** [comment]
So what's included in a .env?

**Comment by AryanJ-NYC** [comment]
node seed/
*no original function chain to wrap
TypeError: OAuth2Strategy requires a clientID option*

**Comment by benmcmahon100** [comment]
ehhhhhhhhhh

**Comment by jbmartinez** [comment]
I set up a cloud9 workspace yesterday. I copied the .env file and only changed the mongo connection

**Comment by benmcmahon100** [comment]
what's in you env? You need all the headings but you can just have stuff as the value

**Comment by benmcmahon100** [comment]
what jb said :p

**Comment by AryanJ-NYC** [comment]
Awesome. Got it running. Giving out brownie points in gitter. :smile:

**Comment by benmcmahon100** [comment]
Ha Ha nice!

**Comment by jbmartinez** [comment]
:smile:

**Comment by AryanJ-NYC** [comment]
Tested and works as desired.

**Comment by benmcmahon100** [comment]
Awesome! Will merge!

**Pull request merged**
