### PR TITLE
feat: Add solution to Portuguese challenges

### PR DESCRIPTION
**Pull request by MGenteluci**
- [x] I have read [freeCodeCamp's contribution guidelines](https://github.com/freeCodeCamp/freeCodeCamp/blob/master/CONTRIBUTING.md).
- [x] My pull request has a descriptive title (not a vague title like `Update index.md`)
- [x] My pull request targets the `master` branch of freeCodeCamp.
- [x] None of my changes are plagiarized from another source without proper attribution.
- [x] All the files I changed are in the same world language (for example: only English changes, or only Chinese changes, etc.)
- [x] My changes do not use shortened URLs or affiliate links.

Add solution to 5 challenges:

1. curriculum/challenges/portuguese/02-javascript-algorithms-and-data-structures/functional-programming/use-the-some-method-to-check-that-any-elements-in-an-array-meet-a-criteria.portuguese.md
2. curriculum/challenges/portuguese/02-javascript-algorithms-and-data-structures/functional-programming/add-elements-to-the-end-of-an-array-using-concat-instead-of-push.portuguese.md
3. curriculum/challenges/portuguese/02-javascript-algorithms-and-data-structures/functional-programming/combine-an-array-into-a-string-using-the-join-method.portuguese.md
4. curriculum/challenges/portuguese/02-javascript-algorithms-and-data-structures/functional-programming/use-the-every-method-to-check-that-every-element-in-an-array-meets-a-criteria.portuguese.md
5. curriculum/challenges/portuguese/02-javascript-algorithms-and-data-structures/functional-programming/use-the-filter-method-to-extract-data-from-an-array.portuguese.md

### CODE REVIEW

**Comment by MGenteluci** [comment]
> @MGenteluci Can you please put all of the changes for the challenges (solutions) into a single PR instead of separate PRs. Just close the extra PRs and have a single PR for all of the challenges you want to add solutions.
> 
> Thank you.

Sure, I can do that. Should I group it by language or should I submit both portuguese and english all together?

**Comment by RandellDawson** [comment]
As the 5th bullet point indicates, PRs should not mix languages.

**Comment by MGenteluci** [comment]
> As the 5th bullet point indicates, PRs should not mix languages.

Oh right. That's done, all 5 portuguese solutions are grouped in this PR.

**Comment by RandellDawson** [comment]
**Note to moderators:** To test solutions for non-English files such as these Portuguese challenges, you must run `npm run test:curriculum` after first changing `TEST_CHALLENGES_FOR_LANGS=english` to `TEST_CHALLENGES_FOR_LANGS=portuguese` in the `.env` file.  The problem is, many of the challenges are missing important sections such as the After or Before Test sections which the challenge tests use.  For example, the challenge named "24 Game" in the `Coding Interview Prep` section is currently failing the tests because it is missing the After Test section.

@raisedadead Until the existing challenge files on the `master` branch are fixed, I think we can not "test" any changes and be 100% confident the solutions will pass the existing test for the current state of the non-English files.  We can also not just test the solutions using the English version as we already know many of the non-English challenges were not updated when either solutions were added and/or tests were changed.   I propose blocking any further merging of the non-English curriculum PRs until each language on `master` can successfully pass all the existing tests for the applicable languages.

**Comment by RandellDawson** [comment]
@MGenteluci Thank you for putting them all into the same PR.  Now you can just close the other ones and add a comment to them like "Added to PR #37161 instead".  This will create a reference to this PR in case anyone wonders why the others were closed.

**Comment by raisedadead** [comment]
> for the current state of the non-English files

Do you mean the non-english curriculum needs update for the updated schema?

**Comment by RandellDawson** [comment]
**UPDATE:**  After discussing this issue with @ojeytonwilliams, he made a suggestion which I have put into a new PR (#37188) to update the `How to work on Coding Challenges` documentation.  Basically, we can test individual challenges without worry about the rest of the challenges' correctness when validating solutions are correct for the tests in a file.

@MGenteluci You need to take the following steps to test the changes you have made:

1. Set the environment variable `TEST_CHALLENGES_FOR_LANGS` to `portuguese` in the `.env` file.
2.  Change to the `curriculum` directory:
```bash
cd curriculum
```
3. Run the following for each challenge file for which you have added solution:
```bash
npm run test -- -g 'the full English title of the challenge'
```
I have already done this locally on my machine and found at least one challenge fails.  The reason is not your added solution, but problems in the `testString` which will need to be fixed as well.  They can be fixed by removing the assert message argument (which is no longer needed) for each test.  Some of the `testString` arguments were not properly created (i.e double quotes were not properly escaped), but since we only use the `text` for each test, they can be removed.  Once you tested each challenge file using the syntax above and the test results show all tests pass, then you should commit/push those changes back to this PR.

**Comment by MGenteluci** [comment]
> **UPDATE:** After discussing this issue with @ojeytonwilliams, he made a suggestion which I have put into a new PR (#37188) to update the `How to work on Coding Challenges` documentation. Basically, we can test individual challenges without worry about the rest of the challenges' correctness when validating solutions are correct for the tests in a file.
> 
> @MGenteluci You need to take the following steps to test the changes you have made:
> 
> 1. Set the environment variable `TEST_CHALLENGES_FOR_LANGS` to `portuguese` in the `.env` file.
> 2. Change to the `curriculum` directory:
> 
> ```shell
> cd curriculum
> ```
> 
> 1. Run the following for each challenge file for which you have added solution:
> 
> ```shell
> npm run test -- -g 'the full English title of the challenge'
> ```
> 
> I have already done this locally on my machine and found at least one challenge fails. The reason is not your added solution, but problems in the `testString` which will need to be fixed as well. They can be fixed by removing the assert message argument (which is no longer needed) for each test. Some of the `testString` arguments were not properly created (i.e double quotes were not properly escaped), but since we only use the `text` for each test, they can be removed. Once you tested each challenge file using the syntax above and the test results show all tests pass, then you should commit/push those changes back to this PR.

Fixed! I had to fix the asserts in both use-the-filter-method-to-extract-data-from-an-array and combine-an-array-into-a-string-using-the-join-method

**Comment by MGenteluci** [comment]
@RandellDawson for future PRs, should I group tests, docs and feats all in the same PR if they are in the same language?

**Comment by RandellDawson** [comment]
> should I group tests, docs and feats all in the same PR if they are in the same language?

If you are adding solutions to curriculum files, keep those together in a PR.  If making changes to docs, put those changes in a separate PR.  For documentation PRs, there is nothing to test and would not hold up a PR as long as one that has both types of changes on it.  It makes it easier for the reviewers approving the PRs for merging.

**Comment by MGenteluci** [comment]
> > should I group tests, docs and feats all in the same PR if they are in the same language?
> 
> If you are adding solutions to curriculum files, keep those together in a PR. If making changes to docs, put those changes in a separate PR. For documentation PRs, there is nothing to test and would not hold up a PR as long as one that has both types of changes on it. It makes it easier for the reviewers approving the PRs for merging.

I see. Thanks for the info!

**Review by RandellDawson — APPROVED** [review]
I have tested these locally and they all pass.  One thing I noticed which is beyond the scope of this PR is there are several places in these files (and many other non-English challenges), where the text inside the `code` tags (In Description, Instruction, and Test sections) has been converted to html entities, which will not show correctly when viewed on the site.  For example, the following test `text` in the `Use the filter Method to Extract Data from an Array` challenge
```
  - text: '<code>filteredList</code> deve ser igual a <code>[{&quot;title&quot;: &quot;Inception&quot;,&quot;rating&quot;: &quot;8.8&quot;},{&quot;title&quot;: &quot;Interstellar&quot;,&quot;rating&quot;: &quot;8.6&quot;},{&quot;title&quot;: &quot;The Dark Knight&quot;,&quot;rating&quot;: &quot;9.0&quot;},{&quot;title&quot;: &quot;Batman Begins&quot;,&quot;rating&quot;: &quot;8.3&quot;}]</code> .'
```
should actually be:
```
  - text: '<code>filteredList</code> deve ser igual a <code>[{"title": "Inception","rating": "8.8"},{"title": "Interstellar","rating": "8.6"},{"title": "The Dark Knight","rating": "9.0"},{"title": "Batman Begins","rating": "8.3"}]</code> .'
```

Should probably create an issue to document this for others to work on.

**Comment by MGenteluci** [comment]
> I have tested these locally and they all pass. One thing I noticed which is beyond the scope of this PR is there are several places in these files (and many other non-English challenges), where the text inside the `code` tags (In Description, Instruction, and Test sections) has been converted to html entities, which will not show correctly when viewed on the site. For example, the following test `text` in the `Use the filter Method to Extract Data from an Array` challenge
> 
> ```
>   - text: '<code>filteredList</code> deve ser igual a <code>[{&quot;title&quot;: &quot;Inception&quot;,&quot;rating&quot;: &quot;8.8&quot;},{&quot;title&quot;: &quot;Interstellar&quot;,&quot;rating&quot;: &quot;8.6&quot;},{&quot;title&quot;: &quot;The Dark Knight&quot;,&quot;rating&quot;: &quot;9.0&quot;},{&quot;title&quot;: &quot;Batman Begins&quot;,&quot;rating&quot;: &quot;8.3&quot;}]</code> .'
> ```
> 
> should actually be:
> 
> ```
>   - text: '<code>filteredList</code> deve ser igual a <code>[{"title": "Inception","rating": "8.8"},{"title": "Interstellar","rating": "8.6"},{"title": "The Dark Knight","rating": "9.0"},{"title": "Batman Begins","rating": "8.3"}]</code> .'
> ```
> 
> Should probably create an issue to document this for others to work on.

I'm willing to start working on the Portuguese files, should I create the issue first or can I start working and then submit the PR?

**Comment by scissorsneedfoodtoo** [comment]
@MGenteluci, please create an issue when you can for added visibility. There might be other contributors who can help fix the challenges in Portuguese and other affected languages.

**Comment by scissorsneedfoodtoo** [comment]
Thank you for all of your hard work on these @MGenteluci. Looking forward to your future contributions :1st_place_medal:

**Pull request merged**
