### PR TITLE
Update the codepen examples

### LINKED ISSUE #8139: Codepen - Issue with Show Local Weather App
Challenge [Show the Local Weather](https://www.freecodecamp.com/challenges/show-the-local-weather) has an issue.
User Agent is: <code>Mozilla/5.0 (Windows NT 6.1) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/49.0.2623.112 Safari/537.36</code>.

The local weather app at https://codepen.io/FreeCodeCamp/full/bELRjV. is not working properly
image

It does not show any weather information. Please update the link with an app that works.

### PR DESCRIPTION
**Pull request by raisedadead**
#### Pre-Submission Checklist

- [x] Your pull request targets the `staging` branch of FreeCodeCamp.
- [x] Branch starts with either `fix/`, `feature/`, or `translate/` (e.g. `fix/signin-issue`)
- [x] You have only one commit (if not, [squash](https://github.com/FreeCodeCamp/FreeCodeCamp/wiki/git-rebase#squashing-multiple-commits-into-one) them into one commit).
- [x] All new and existing tests pass the command `npm run test-challenges`. Use `git commit --amend` to amend any fixes.
#### Type of Change

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] Add new translation (feature adding new translations)
#### Checklist:

- [x] Tested changes locally.
- [x] Closes currently open issue (`Closes #XXXX`): 

Closes #8139 
Refers #7700
#### Description

This commit:
- Updates the Local Weather challenge example back to the
  `http` URL because a hosted resource is served over http.
- Updates the Portfolio challenge pen from @hallaathrad 's copy.
- Updates the Force Directed Graph challenge with a `https`
  link to the Camper News API.

Tested locally.

> Additionally added a comment in the Pen to prevent future edits:
> 
> ```
> /*
> Note this example will work only over
> http and NOT https because of a http resource used below.
> */
> ```

### CODE REVIEW

**Comment by erictleung** [comment]
Not sure how big of a deal it is but shouldn't [the `href` link for the API website](https://github.com/FreeCodeCamp/FreeCodeCamp/pull/8141/commits/d18be06f410bbf3f796b1693e535112c5b142102#diff-ed60b7522fed7dde276c9891b9142c82L95) have https to be consistent with the English translation? Otherwise, looks good to me 👍

**Comment by raisedadead** [comment]
@erictleung Nice Catch. Will Update.

**Comment by erictleung** [comment]
@raisedadead LGTM 👍  Also, thanks for the nice detailed list of changes. Makes QA'ing much easier! 👏 👏 👏

**Comment by raisedadead** [comment]
@erictleung I have been on the side of QA'ing, I know the feeling when you don't know what's going to break.So it always cleaner to provide as much details as possible.

Cheers and thanks a lot for QA and merge.

**Pull request merged**
