### PR TITLE
[fix] implemented information about box-sizing

### LINKED ISSUE #49156: learn-the-css-box-model-by-building-a-rothko-painting challenge - missing information about different css box models
### Describe the Issue

https://www.freecodecamp.org/learn/2022/responsive-web-design/learn-the-css-box-model-by-building-a-rothko-painting/

Challenge called "Learn the **css box model** by..."
There are bunch of steps which describes some parts of the box model, a lot of steps about changing colors etc
But it looks like there is no step describing that there are different models available like content-box, border-box etc
And in the next project https://www.freecodecamp.org/learn/2022/responsive-web-design/learn-css-flexbox-by-building-a-photo-gallery/step-7 there is a phrase:

> Normalize your box model by creating a * selector and setting the box-sizing property to border-box as the value.

But there was no information before that about border-box and what is it and why we are setting it to border-box here

### Affected Page

https://www.freecodecamp.org/learn/2022/responsive-web-design/learn-the-css-box-model-by-building-a-rothko-painting/

### Steps to Reproduce

Just go through challenge

### Recommended fix or suggestions

It will great if "Learn the css box model" project will include information about different box-sizing values 

### Screenshots

_No response_

### PR DESCRIPTION
**Pull request by CBID2**
Checklist:

- [X] I have read and followed the [contribution guidelines](https://contribute.freecodecamp.org).
- [X] I have read and followed the [how to open a pull request guide](https://contribute.freecodecamp.org/#/how-to-open-a-pull-request).
- [X] My pull request targets the `main` branch of freeCodeCamp.
- [X] I have tested these changes either locally on my machine, or GitPod.

Closes #49156 

Note: I created a better version of this pull request.  Check #50786

### CODE REVIEW

**Review by Sembauke — CHANGES_REQUESTED** [review]
Hey @CBID2,

Thank you for opening this pull-request, we like to introduce a new step before this step that introduces box-sizing.

If you need any help, let me know! We also have a good explanation on our contribution guidelines page.

**Comment by CBID2** [comment]
> Hey @CBID2,
> 
> 
> 
> Thank you for opening this pull-request, we like to introduce a new step before this step that introduces box-sizing.
> 
> 
> 
> If you need any help, let me know! We also have a good explanation on our contribution guidelines page.
> 
> 

Hi @Sembauke! Thank you for the suggestion, what step would that be?

**Comment by Sembauke** [comment]
Hey @CBID2,

Adding a new step (challenge / file in your editor) before step 7.

You'll have to do some reading on how to add a new step here
https://contribute.freecodecamp.org/#/how-to-work-on-coding-challenges

**Comment by CBID2** [comment]
> Hey @CBID2,
> 
> 
> 
> Adding a new step (challenge / file in your editor) before step 7.
> 
> 
> 
> You'll have to do some reading on how to add a new step here
> 
> https://contribute.freecodecamp.org/#/how-to-work-on-coding-challenges
> 
> 

Thanks @Sembauke, but I'm still wondering what step I should add as far as what the camper should do before the box-sizing property.

**Comment by Sembauke** [comment]
> We need to add a lesson before this which introduces the box-sizing property to give clarification to the user. 

I quoted this from the issue.

**Comment by CBID2** [comment]
> > We need to add a lesson before this which introduces the box-sizing property to give clarification to the user.
> 
> I quoted this from the issue.

Oh ok

**Comment by CBID2** [comment]
> > We need to add a lesson before this which introduces the box-sizing property to give clarification to the user.
> 
> I quoted this from the issue.

Hi @Sembauke! :) I added the lesson.

**Comment by naomi-lgbt** [comment]
I don't see a new lesson?

**Comment by CBID2** [comment]
> I don't see a new lesson?

Huh, I swore I had it in there @naomi-lgbt 🤔

**Comment by CBID2** [comment]
> I don't see a new lesson?

I did add it @naomi-lgbt. See line 10

**Comment by naomi-lgbt** [comment]
That's extra text to the current lesson - I believe the planned implementation was to add an entirely new lesson (step) **before** this lesson.

**Comment by CBID2** [comment]
> That's extra text to the current lesson - I believe the planned implementation was to add an entirely new lesson (step) **before** this lesson.

Ohhh ok @naomi-lgbt. Any suggestions?

**Comment by naomi-lgbt** [comment]
I would suggest a lesson that first has them set the box-sizing to content-box, explaining that this is the default and what it means.

Then update the current lesson to change content-box to border-box, and explain the difference.

**Comment by CBID2** [comment]
> I would suggest a lesson that first has them set the box-sizing to content-box, explaining that this is the default and what it means.
> 
> 
> 
> Then update the current lesson to change content-box to border-box, and explain the difference.

Ok thanks

**Comment by CBID2** [comment]
> #49156

I think I got it @naomi-lgbt! :)

**Comment by naomi-lgbt** [comment]
I think there is still some misunderstanding here.

With your changes:
- Step 7 teaches the content-box and border-box value.

The changes we want:
- A new Step 7 should be created to teach the content-box
- The old Step 7 (which becomes Step 8 with the new insertion) should teach border-box

**Comment by naomi-lgbt** [comment]
You can refer to https://contribute.freecodecamp.org/#/how-to-work-on-practice-projects?id=insert-step-1 for how to insert a new step.

**Comment by CBID2** [comment]
> I think there is still some misunderstanding here.
> 
> With your changes:
> 
> * Step 7 teaches the content-box and border-box value.
> 
> The changes we want:
> 
> * A new Step 7 should be created to teach the content-box
> * The old Step 7 (which becomes Step 8 with the new insertion) should teach border-box

Ahh ok

**Comment by CBID2** [comment]
> You can refer to https://contribute.freecodecamp.org/#/how-to-work-on-practice-projects?id=insert-step-1 for how to insert a new step.

Hi @naomi-lgbt. I got this error when I followed the steps to open the challenge editor:
error

**Comment by CBID2** [comment]
Hey @naomi-lgbt. I made the changes. Hopefully, I got it right this time! 😄 🤞🏾

**Comment by raisedadead** [comment]
Nice work so far. 


Please ensure you follow the PR checklist and not just tick things off; otherwise, we won't take you seriously. Respect the requirements to earn the respect of your fellow maintainers. You will also save everyone time :)

Since you are new here, please pace yourself and read our [contributing guidelines](https://contribute.freecodecamp.org), as we see that you may still need to catch up on a few things.

<details>
<summary>Here are some examples (expand)</summary>
 
1. Do not edit files directly on GitHub – while you can, it's not a good idea. 

   Typos and formatting errors can break the tests.

2. Use the correct way to link issues. 

   Add the issue number only in the description of the PR by updating the `XXXXXX`. Do not just add issue numbers everywhere and anywhere you feel like.

4. Keep mentions and review requests to a minimum. 

   We understand you are excited about contributing, and our maintainers will get back to you when they can.

5. Do not work directly off your `main` branch. 

   You can always create a new branch for the changes you are working on. That way, you can sync change to your PR branch as the main repository moves ahead while your PR is waiting in the merge queue.

</details>

Looking forward to more contributions!

Happy Contributing.

**Comment by naomi-lgbt** [comment]
Closing in favour of #50795

**Pull request closed without merging**
