### PR TITLE
Added new test cases and corrected the solution for positive and negative lookahead for ensuring that strings beginning with numbers are not accepted

### LINKED ISSUE #37481: Missing test case for the Positive and Negative Lookahead challenge
Per the discussion in the following forum topic, a new test case should be added which should fail if 
a password like “8pass99” which has more than 6 characters long and has 6 consecutive characters.

https://www.freecodecamp.org/forum/t/regex-look-aheads/323407/3

@ArielLeslie has already corrected the [forum hint/solution topic for the challenge](https://www.freecodecamp.org/forum/t/freecodecamp-challenge-guide-positive-and-negative-lookahead/301360), so the actual solution for the challenge file needs to also reflect the following corrected regex:

```js
let pwRegex = /^(?=\w{6,})(?=\D*\d{2})/;
```

### PR DESCRIPTION
**Pull request by FullBinaryAlchemist**
- [x] I have read [freeCodeCamp's contribution guidelines](https://github.com/freeCodeCamp/freeCodeCamp/blob/master/CONTRIBUTING.md).
- [x] My pull request has a descriptive title (not a vague title like `Update index.md`)
- [x] My pull request targets the `master` branch of freeCodeCamp.
- [x] None of my changes are plagiarized from another source without proper attribution.
- [x] All the files I changed are in the same world language (for example: only English changes, or only Chinese changes, etc.)
- [x] My changes do not use shortened URLs or affiliate links.

Closes #37481

Ran `npm run test:curriculum` and results:
image

### CODE REVIEW

**Comment by RandellDawson** [comment]
@FullBinaryAlchemist Make sure to update the solution too.

**Comment by FullBinaryAlchemist** [comment]
> @FullBinaryAlchemist Make sure to update the solution too. Also, you were supposed to run the tests as I mentioned in the issue before creating a PR.

@RandellDawson I have updated the `pwRegex` variable in the solution field. 
I'm unable to setup the environment locally so I using Gitpod. While the functionality is working by using the in-paeg browser of Gitpod , on running `npm run test:curriculum` I'm getting errors:

```
> @freecodecamp/curriculum@0.0.0-next.4 test /workspace/freeCodeCamp/curriculum
> mocha --delay --reporter progress --bail

Browserslist: caniuse-lite is outdated. Please run next command `npm update caniuse-lite browserslist`
⠏ Populate tests.
⠋ Populate tests.

  0 passing (161ms)
  1 failing

  1) Check challenges
       "before all" hook:
     Error: Failed to launch chrome!
/workspace/freeCodeCamp/curriculum/node_modules/puppeteer/.local-chromium/linux-674921/chrome-linux/chrome: error while loading shared libraries: libX11-xcb.so.1: cannot open shared object file: No such file or directory


TROUBLESHOOTING: https://github.com/GoogleChrome/puppeteer/blob/master/docs/troubleshooting.md

      at onClose (node_modules/puppeteer/lib/Launcher.js:349:14)
      at Interface.helper.addEventListener (node_modules/puppeteer/lib/Launcher.js:338:50)
      at Interface.close (readline.js:379:8)
      at Socket.onend (readline.js:157:10)
      at endReadableNT (_stream_readable.js:1125:12)
      at process._tickCallback (internal/process/next_tick.js:63:19)



npm ERR! Test failed.  See above for more details.
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! @freecodecamp/freecodecamp@0.0.1 test:curriculum: `cd ./curriculum && npm test && cd ../`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the @freecodecamp/freecodecamp@0.0.1 test:curriculum script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/gitpod/.npm/_logs/2019-10-23T19_58_48_068Z-debug.log
```
I'm having trouble resolving them, any idea on how I go around solving them ?

**Comment by RandellDawson** [comment]
@FullBinaryAlchemist See [this reply in the forum topic related to this PR](https://www.freecodecamp.org/forum/t/regex-look-aheads/323407/9).  You will need to adjust the solution.

**Comment by FullBinaryAlchemist** [comment]
@RandellDawson Okay , I'll make the changes. Also thinking about adding another test case "12abcde" to catch the `/^(?=\w{6,})(?=\D*\d{2})/` solution.Should I go ahead with it?

**Comment by RandellDawson** [comment]
@FullBinaryAlchemist What about @ArielLeslie's suggestion of changing `*` to `+`? in the regex solution.

**Comment by FullBinaryAlchemist** [comment]
@RandellDawson  Yes, I did that. See commit [1dfc704](https://github.com/freeCodeCamp/freeCodeCamp/pull/37485/commits/1dfc704af68886807c47d46bc1c92ac655dd5318)

**Review by RandellDawson — APPROVED** [review]
OK, I think this PR looks good now.

**Comment by RandellDawson** [comment]
Once this PR is merged, this new solution needs to be added to [this forum topic](https://www.freecodecamp.org/forum/t/freecodecamp-challenge-guide-positive-and-negative-lookahead/301360)

**Review by Manish-Giri — APPROVED** [review]
LGTM. Thank You for your contribution.

**Pull request merged**
