### PR TITLE
french translation of say hello to html elements part

### PR DESCRIPTION
**Pull request by cploose**
I translate in french the say hello to html elements part

### CODE REVIEW

**Comment by fnonga** [comment]
Someone know why the build failed?

**Comment by thejonathangraham** [comment]
Thanks fnonga maybe submit a pr per section instead of just one challenge ;)

**Comment by ltegman** [comment]
@fnonga We ask that you [squash your commits](https://github.com/FreeCodeCamp/FreeCodeCamp/wiki/git-rebase#squashing-multiple-commits-into-one) after you have finished modifying a PR. However, since you have a merge commit you will not be able to do this and are probably better off saving your changes and starting this PR from scratch. In the future you can avoid introducing merge commits by rebasing against staging instead of merging.

**Comment by thejonathangraham** [comment]
@fnonga Submit a pr to my fork and then I'll pr one with everything from
html and css

**Comment by bugron** [comment]
@fnonga please, `rebase` your branch on top of the latest staging branch and fix conflicts.

**Comment by fnonga** [comment]
@bugron can you explain me how rebase my branch on the top of the latest staging branch?

**Comment by bugron** [comment]
@fnonga see this wiki article https://github.com/FreeCodeCamp/FreeCodeCamp/wiki/git-rebase

**Comment by theflametrooper** [comment]
@fnonga Can you rebase this? Otherwise submit a pr to my fork instead and i'll fix the changes

**Comment by fnonga** [comment]
i have rebase

**Comment by theflametrooper** [comment]
@fnonga It hasn't been rebased...

**Comment by theflametrooper** [comment]
Make sure you squash your commits

**Comment by theflametrooper** [comment]
@fnonga Submit a pr to here instead https://github.com/theflametrooper/FreeCodeCamp/tree/feature/french-translation and close this one. I'll fix the errors.

**Comment by theflametrooper** [comment]
I will submit a new pr with squashed commits and bugs fixed.

**Comment by Vanco521** [comment]
Greetings,

Please stop the number of notifications.  What is the link or code to stop
notifications.

Thanks

**Comment by sludge256** [comment]
@Vanco521 You can visit this link to change your notifications settings https://github.com/settings/notifications

**Pull request closed without merging**
