### PR TITLE
Simplify truncate a string challenge

### LINKED ISSUE #12712: Confusing instructions in truncate a string
#### Challenge Name

[Truncate a string](https://www.freecodecamp.com/challenges/truncate-a-string)

#### Issue Description

_Inspired by https://github.com/FreeCodeCamp/freeCodeCamp/issues/12418_
Let's talk about why I think this is confusing. Here are the instructions:
>Truncate a string (first argument) if it is longer than the given maximum string length (second argument). Return the truncated string with a ... ending.
>
>Note that inserting the three dots to the end will add to the string length.
>
>However, if the given maximum string length num is less than or equal to 3, then the addition of the three dots does not add to the string length in determining the truncated string.

1. If the string is longer than three characters, the string should be truncated at `num - 3`
2. If it's three characters or shorted, it should be truncated at `num`

This doesn't really make sense to me.
Now, I don't want to talk about real world cases too much, but I'll do it a for a little bit.
I think the point of a truncate function is to get an output of a predictable length. With this function, regardless of the input, the output should be `num` or `num + 3`.

I suggest we simplify this challenge to _always_ shorten the string to the amount of characters passed in as the second argument (`num`), making the output string always `num + 3`.

I thought a bit about it being more complicated intentionally to make the camper dissect the requirements and use if statements, but I think it's a bad idea to intentionally make things more complicated than they would be for the sake of having them practice something.

### PR DESCRIPTION
**Pull request by systimotic**
#### Pre-Submission Checklist
- [x] Your pull request targets the `staging` branch of freeCodeCamp.
- [x] Branch starts with either `fix/`, `feature/`, or `translate/` (e.g. `fix/signin-issue`)
- [x] You have only one commit (if not, [squash](http://forum.freecodecamp.com/t/how-to-squash-multiple-commits-into-one-with-git/13231) them into one commit).
- [x] All new and existing tests pass the command `npm test`. Use `git commit --amend` to amend any fixes.

#### Type of Change
- [x] Small bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds new functionality)
- [ ] Breaking change (fix or feature that would change existing functionality)
- [ ] Add new translation (feature adding new translations)

#### Checklist:
- [x] Tested changes locally.
- [x] Closes currently open issue (replace XXXX with an issue no): Closes #12712

#### Description
This PR takes away the confusion as per the issue.

### CODE REVIEW

**Review by Greenheart — CHANGES_REQUESTED** [review]
@systimotic I think you need to do a `git rebase` so that your changes are applied on top of the staging branch.

I think https://github.com/freeCodeCamp/freeCodeCamp/blob/staging/CONTRIBUTING.md says something about this :blush:

**Comment by systimotic** [comment]
@Greenheart I think I did it! 🎉

**Review by Greenheart — APPROVED** [review]
@systimotic Good job! :smile:

**Comment by W88MYR** [comment]
Hangwa
Hộp thư chưa bỏ xung

**Pull request merged**
