### PR TITLE
Add twitch api pass-through links

### PR DESCRIPTION
**Pull request by Em-Ant**
#### Pre-Submission Checklist

- [ ] Your pull request targets the `staging` branch of FreeCodeCamp.
- [x] Branch starts with either `fix/`, `feature/`, or `translate/` (e.g. `fix/signin-issue`)
- [x] You have only one commit (if not, [squash](http://forum.freecodecamp.com/t/how-to-squash-multiple-commits-into-one-with-git/13231) them into one commit).
- [ ] All new and existing tests pass the command `npm run test-challenges`. Use `git commit --amend` to amend any fixes.
#### Type of Change

- [ ] Small bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds new functionality)
- [ ] Breaking change (fix or feature that would change existing functionality)
- [ ] Add new translation (feature adding new translations)
#### Checklist:

- [x] Tested changes locally.
- [ ] Closes currently open issue (replace XXXX with an issue no): Closes #XXXX
#### Description

Add Twitch API Client-Id workaround according to https://github.com/FreeCodeCamp/FreeCodeCamp/pull/11148 to the backup/master branch, in order to be released asap. See this comment https://github.com/FreeCodeCamp/FreeCodeCamp/pull/11148#issuecomment-253121289

### CODE REVIEW

**Comment by Em-Ant** [comment]
**Warning** 
I hope everything is ok with this, I've submitted PRs only to staging before. 
If not please HELP.

**Comment by atjonathan** [comment]
@Em-Ant, can you make another PR with this branch but only to `staging`?

**Comment by Em-Ant** [comment]
@atjonathan already did that...

please read the PR description, especially the provided link to the comment :smile:

**Comment by atjonathan** [comment]
@Em-Ant, oh lol 😂 Thanks!

**Comment by QuincyLarson** [comment]
@Em-Ant thanks for adding this, and for building the pass-through server :)

**Comment by lamlylom90** [comment]
Good and pull

**Pull request merged**
