### PR TITLE
fix(responsive-web-design): change follow-btn class name to action-button-container

### LINKED ISSUE #39608: Improve warnings about extensions?
I know we added a warning about extensions to the intro page for the CSS challenges, but it is not really working. We still get many forum posts about the challenges affected by ad-block (flexbox [tweet embed](https://www.freecodecamp.org/learn/responsive-web-design/css-flexbox/add-flex-superpowers-to-the-tweet-embed) challenge) and the various color challenges affected by dark mode/dark reader extensions.

I think we have to be more explicit in the warning about which extensions can cause issues, and maybe don't use a blue background color because that is not a warning that is just information and people tend to ignore that (maybe orange/yellow instead?). Or we have to add warnings to the individual challenges. For the flexbox challenge, I think an explicit warning about ad-block might be needed because we still get forum threads about this challenge all the time.

### PR DESCRIPTION
**Pull request by luqven**
Checklist:

- [x] I have read [freeCodeCamp's contribution guidelines](https://contribute.freecodecamp.org).
- [x] My pull request has a descriptive title (not a vague title like `Update index.md`)
- [x] My pull request targets the `master` branch of freeCodeCamp.
- [x] All the files I changed are in the same world language, for example: only English changes, or only Chinese changes, etc.

Closes #39608 | Improve warnings about extensions?

Changes:
- All changes were tested locally
- Switches all instances of `follow-btn` to `action-button-container` as suggested in #39608

### CODE REVIEW

**Review by naomi-lgbt — APPROVED** [review]
LGTM~! 🥳 

Thank you for your pull request! We look forward to additional contributions!

I pulled this down locally and tested against my ad blocker, and had no issues (the follow button still shows up). I don't know that this closes the linked issue, as there was some other discussion there as well, though. @lasjorg thoughts?

**Review by moT01 — COMMENTED** [review]
I'm not sure what the exact issue with the ad blocker is and that specific class. Perhaps if we change the class names to `follow-btn-container` or `follow-bttn` we can keep the video hints in these with only a minor inconsistency that, I think, most people would figure out or maybe not even notice.

If we really don't want any inconsistencies in the video hints, then they should probably just be removed here. But I wouldn't mind using `follow-bttn` and leaving them up.

**Comment by lasjorg** [comment]
@moT01 Is adding a note about the class name change a viable solution?

It is a bit unfortunate that we have to remove so many videos (five) just because we changed one class name. They do still explain and show usage, there is just inconsistency with the class name.

I think using `follow-bttn` might cause more confusion than an obvious difference.

---

Just an FYI, this is the filter list blocking follow-btn
https://easylist-downloads.adblockplus.org/fanboy-annoyance.txt

**Comment by moT01** [comment]
Thanks for the link @lasjorg. I'm not really a fan of adding notes all over the place - although, they are needed many times. Not sure if I should continue the discussion here or back on the issue but - what about adding info about the extension issue in the forum hint article? or perhaps the `ask for help` modal instead of trying to adjust the lessons?

What happens if/when some extension does this for another class we use? Just keep changing the lessons around and removing the videos? I'm wondering if this isn't the right approach. Perhaps we should just let those forum posts go in and let people get help there. Or try to find a blanket solution like maybe one of my suggestions. I kind of like the idea of putting a warning in the hint articles.

**Comment by nhcarrigan** [comment]
> Perhaps we should just let those forum posts go in and let people get help there. Or try to find a blanket solution like maybe one of my suggestions. I kind of like the idea of putting a warning in the hint articles.

What about a test at the top of the list that looks for the follow button to exist?
```yml
- text: The <code>.follow-btn</code> should be rendered on the page. Be sure to turn off any extensions such as ad blockers.
  testString: assert(follow button exists)
```

**Comment by lasjorg** [comment]
@nhcarrigan I kind of like that idea.

Unlike color issues with extensions, the missing button we can actually test for by just querying the DOM for the element.

**Comment by nhcarrigan** [comment]
I think it's the approach that would be most clear to our users (and remain compatible with the videos)

**Comment by RandellDawson** [comment]
@lasjorg @nhcarrigan Can you specify exactly what the contributor needs to do?  I assume the current changes are not what is wanted.

**Comment by lasjorg** [comment]
1. Revert everything back.

2. Add a new test, in the assert test for the button. I tested this assert using the Fanboy's Social Blocking List and it turns out the element is not removed from the DOM but is just set to `display: none`. We should probably test for both though.

```
- text: The <code>.follow-btn</code> should be rendered on the page. Be sure to turn off any extensions such as ad blockers.
  testString: assert($('.follow-btn').length > 0 && $('.follow-btn').css('display') !== 'none');
```


3. Add the test to all the flexbox challenges.

**Comment by RandellDawson** [comment]
@luqven Can you please do as @lasjorg has suggested?  

Thank you @lasjorg for the detailed response.  That really helped.

**Comment by RandellDawson** [comment]
@luqven On second thought, since all the changes need to be reverted and we are getting ready to merge a [PR that will completely change the layout of all challenge files](https://github.com/freeCodeCamp/freeCodeCamp/pull/39800), I am going to close this PR.  If you don't mind, wait a couple of days until we have validated the above referenced PR has not caused any undesirable effects.

Thank you for understanding.

**Pull request closed without merging**
