### PR TITLE
Fix Waypoint: While Loops

### PR DESCRIPTION
**Pull request by wilstenholme**
Update description with code highlighting and terms

### CODE REVIEW

**Comment by SaintPeter** [comment]
:+1:

**Comment by ltegman** [comment]
@SaintPeter A little premature on this merge. The quotes around `for loop` and `while loop` should be removed and the code tags should only be around `for` and `while` not loop.

**Comment by wilstenholme** [comment]
@ltegman Spent a little time thinking between the two, haha. But yes, that seems better.

**Comment by wilstenholme** [comment]
Follow-up: https://github.com/FreeCodeCamp/FreeCodeCamp/pull/5724

**Pull request merged**
