### PR TITLE
created checkpoint: profile-lookup

### LINKED ISSUE #5795: Caesar Replacement Checkpoint - Profile Lookup
Me and @SaintPeter have discussed the replacement for the Caesar checkpoint. 

It's going to be a Camper Lookup Checkpoint:

Make a function that takes a "camper" and a property as parameters and if that property exists, return that property is in. If the camper does not exist, return "No such Camper". If the property doesn't exist, return "Camper has no such property".

```javascript
var campers = [
    {
        "username": "SaintPeter",
        "title": "The Chosen One",
        "HP": 3000,
        "likes": ["Pizza", "Coding", "Brownie Points"]
    },
     {
        "username": "AkiraLaine",
        "title": "Time Traveler",
        "HP": 2000,
        "likes": ["Magic", "Javascript", "Cookies"]

    }
]

function lookUp(camper, prop){
    var answer;

    return answer;
}

lookUp("AkiraLaine", "likes");
```

@SaintPeter gave me the green light to make it. I'm currently setting up FCC locally and will start working on it.

### PR DESCRIPTION
**Pull request by AkiraLaine**
closes #5795 

Fixed all issues!

### CODE REVIEW

**Comment by SaintPeter** [comment]
This looks really good.  

Some Concerns:
> A lookUp function that takes firstName and property as arguments has been pre-written for you.
> The function should check if the given firstName is an actual contact and the given property is a property of that contact.

You talk about `property` when the actual variable is called `prop`.  You should be consistent in calling it `prop` and maybe call it a property (with no highlighting).  It might also make sense to use `firstName` rather than `name` so we don't confuse them that they're supposed to match the first name in the contact.

The very first line should be:  
`// Setup` - just above the `contact` definition

You use non-standard code demarcations:
`//Write your function in between these comments`

You should use:
```js
function lookUp(name, prop) {
  // Only change code below this line


  // Only change code above this line
}
```
Those lines should be indented and inside the function.

For the execution of the function, use the following tag in the line immediately above the code:
```js
// Change these values to test your function
lookUp("Akira", "likes");
```

My Solution:
```js
function lookUp(name, prop){
  for(var i = 0, len = contacts.length; i < len; i++) {
    if(contacts[i].firstName === name) {
      if(contacts[i].hasOwnProperty(prop)) {
        return contacts[i][prop];
      } else {
        return "No such property";
      }
    }
  }
  return "No such contact"; 
}
```

image

**Comment by CaroleAnneHannon** [comment]
It looks fairly clear and it's not too hard.

The only concern I'd have is some people get flustered when reading (especially if they are not fluent in English), and they may misread `If both are true, then return the "value" of that property` to actually return the property parameter instead. But I'm not sure how it could be worded to prevent that.

**Comment by AkiraLaine** [comment]
@CaroleAnneHannon I'm not sure how that can solved. But this is one of the test case:
```message: <code>"Kristian", "lastName"</code> should return <code>"Vos"</code>``` It clearly indicates that *vos* should be returned, not *lastName*.

**Comment by SaintPeter** [comment]
:+1: 
Awesome!

**Pull request merged**
