### PR TITLE
feat(curriculum): add python multiple choice questions

### PR DESCRIPTION
**Pull request by scissorsneedfoodtoo**
Checklist:

- [x] I have read [freeCodeCamp's contribution guidelines](https://contribute.freecodecamp.org).
- [x] My pull request has a descriptive title (not a vague title like `Update index.md`)
- [ ] My pull request targets the `master` branch of freeCodeCamp.
- [x] All the files I changed are in the same world language, for example: only English changes, or only Chinese changes, etc.

Closes #XXXXX

### CODE REVIEW

**Comment by scissorsneedfoodtoo** [comment]
@raisedadead, sorry, forgot to take this off of draft mode.

**Comment by raisedadead** [comment]
Can you confirm that you have all the files in the changeset. I just rebase this and resolved some conflicts.

**Comment by scissorsneedfoodtoo** [comment]
@raisedadead, thank you for solving all the merge conflicts. Checked again locally and found a challenge with a missing `isHidden` flag and another that I didn't write questions for. Everything should be good to go now.

**Comment by raisedadead** [comment]
Thanks @scissorsneedfoodtoo there is a missing entry in meta as per travis: https://travis-ci.com/github/freeCodeCamp/freeCodeCamp/jobs/340819999#L885

**Comment by scissorsneedfoodtoo** [comment]
@raisedadead, sorry, I missed that earlier when I fixed a typo with one of the challenges. Should be okay now.

**Review by raisedadead — APPROVED** [review]

**Pull request merged**
