### PR TITLE
chore(client): Replace Spacer with the one from @freecodecamp/ui

### LINKED ISSUE #56744: Replace Spacer with the one from @freecodecamp/ui
## Description

We have implemented a `Spacer` component in our component library (`@freecodecamp/ui`), so the existing `Spacer` in the /learn client should be replaced with that:

```diff
--- import { Loader, Spacer } from '../components/helpers';
+++ import { Spacer } from '@freecodecamp/ui';
```

Note that this is not a direct swap. The `size` prop needs to be updated as follows:

| /learn Spacer | @freecodecamp/ui Spacer |
| --- | --- |
| `xxSmall` | `xxs` |
| `small` | `xs` |
| `xSmall` | `s` |
| `medium` | `m` |
| `large` | `l` |
| `exLarge` | `xl` |
| `doubleXL` | `xxl` |

## Changes needed
 
- Migrate all Spacer usages to `@freecodecamp/ui` following the mapping above
- Remove the Spacer component from the codebase: https://github.com/freeCodeCamp/freeCodeCamp/blob/main/client/src/components/helpers/spacer.tsx

### PR DESCRIPTION
**Pull request by sulaiman-dev**
Checklist:

- [X] I have read and followed the [contribution guidelines](https://contribute.freecodecamp.org).
- [X] I have read and followed the [how to open a pull request guide](https://contribute.freecodecamp.org/how-to-open-a-pull-request/).
- [X] My pull request targets the `main` branch of freeCodeCamp.
- [X] I have tested these changes either locally on my machine, or GitPod.

Closes [#56744](https://github.com/freeCodeCamp/freeCodeCamp/issues/56744)

### CODE REVIEW

**Review by huyenltnguyen — APPROVED** [review]
@sulaiman-dev Thank you for the PR. The changes LGTM 👍

**Comment by ojeytonwilliams** [comment]
Hi @sulaiman-dev, something seems to have gone wrong with the merge. Could you address the lint errors?

Please let us know if you need any help.

**Comment by sulaiman-dev** [comment]
> Hi @sulaiman-dev, something seems to have gone wrong with the merge. Could you address the lint errors?
> 
> Please let us know if you need any help.

**Comment by sulaiman-dev** [comment]
> > Hi @sulaiman-dev, something seems to have gone wrong with the merge. Could you address the lint errors?
> > Please let us know if you need any help.



> Hi @sulaiman-dev, something seems to have gone wrong with the merge. Could you address the lint errors?
> 
> Please let us know if you need any help.

@ojeytonwilliams Thanks for flagging this! I'll address the lint errors and push the fixes ASAP. If I hit any snags, I’ll definitely reach out for help. Appreciate the heads-up. 👍

**Comment by sulaiman-dev** [comment]
> Hi @sulaiman-dev, something seems to have gone wrong with the merge. Could you address the lint errors?
> 
> Please let us know if you need any help.

@ojeytonwilliams Thanks for flagging this! I'll address the lint errors and push the fixes ASAP. If I hit any snags, I’ll definitely reach out for help. Appreciate the heads-up. 👍

**Comment by ilenia-magoni** [comment]
There is something going wrong with the tests, can you take a look again?
Also please don't merge main into your branch unless necessary (like to solve a merge conflict), or asked by maintainers

**Comment by sulaiman-dev** [comment]
> There is something going wrong with the tests, can you take a look again? Also please don't merge main into your branch unless necessary (like to solve a merge conflict), or asked by maintainers

Thanks for pointing that out! I'm not quite sure why the tests are failing. Could you provide some guidance or insights to help me resolve this? I will also make sure not to merge main into my branch unless absolutely necessary. Appreciate your help!

**Comment by ilenia-magoni** [comment]
Some are the same failures that are on `main` https://github.com/freeCodeCamp/freeCodeCamp/actions/runs/11500439422/job/32011185808 so not related to your PR

**Comment by sulaiman-dev** [comment]
> Some are the same failures that are on `main` https://github.com/freeCodeCamp/freeCodeCamp/actions/runs/11500439422/job/32011185808 so not related to your PR

Thanks for clarifying! Let me know if there's anything else you need me to address in my PR.

**Comment by ojeytonwilliams** [comment]
The chromium tests are pretty reliable, so any chromium failures will need to be addressed.

It might help to track them down if you split the PR into multiple, smaller PRs. That should narrow down the problem. Alternatively you could run the playwright tests locally to try and discover what is broken.

**Review by raisedadead — APPROVED** [review]

**Pull request merged**
