### PR TITLE
fix: Settings page picture url fix

### LINKED ISSUE #55653: Settings page - not possible to save after clearing picture URL
### Describe the Issue

Save button does not get enabled even if the picture URL is valid

### Affected Page

https://www.freecodecamp.org/settings

### Steps to Reproduce

Here are the steps to reproduce.

1. Go to https://www.freecodecamp.org/settings page
2. Go to picture field and edit the value.
3. The message `URL must link directly to an image file` will be visible below the field
4. Save button does not enable even if the URL entered is valid

### Expected behavior

Save button should get enabled and the message below the field should go away in both conditions
1. Picture url is valid
2. Picture url does not have value

### Screenshots

_No response_

### System

- Device: [Laptop]
- OS: [MacOS]
- Browser: [Chrome]
- Version: [126.0.6478.183]

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by gagan-bhullar-tech**
Checklist:

- [x] I have read and followed the [contribution guidelines](https://contribute.freecodecamp.org).
- [x] I have read and followed the [how to open a pull request guide](https://contribute.freecodecamp.org/how-to-open-a-pull-request/).
- [x] My pull request targets the `main` branch of freeCodeCamp.
- [x] I have tested these changes either locally on my machine, or GitPod.

Closes #55653

### CODE REVIEW

**Review by naomi-lgbt — APPROVED** [review]

**Review by gikf — COMMENTED** [review]
Api will need to do the same: https://github.com/freeCodeCamp/freeCodeCamp/blob/2b8169dc4f1776ebced64fbd00cfe988b8a6033a/api-server/src/server/boot/settings.js#L173-L187

**Comment by gagan-bhullar-tech** [comment]
@gikf updated API

**Review by ojeytonwilliams — CHANGES_REQUESTED** [review]
This looks good, thanks, @gagan-bhullar-tech.

Could you implement this in the new api? The code in question is here:

https://github.com/freeCodeCamp/freeCodeCamp/blob/2a36629aa3306d80d1ddb803ae9ad305b7288385/api/src/routes/settings.ts#L482-L499

**Comment by gagan-bhullar-tech** [comment]
> onst hasProtocol = isPictureWithProtocol

@ojeytonwilliams updated PR.

**Review by ojeytonwilliams — APPROVED** [review]
Perfect, thanks for taking care of that @gagan-bhullar-tech 

LGTM :+1:

**Comment by raisedadead** [comment]
Late to this, but we should really make it a point to expand tests when we see bugs.

**Pull request merged**
