### PR TITLE
Added additional section and update previous section

### PR DESCRIPTION
**Pull request by marcusparsons**
Added an additional section for complex ternary operations and updated previous section to have csharp flavored code rendering.

- [x] I have read [freeCodeCamp's contribution guidelines](https://github.com/freeCodeCamp/freeCodeCamp/blob/master/CONTRIBUTING.md).
- [x] My pull request has a descriptive title (not a vague title like `Update index.md`)
- [x] My pull request targets the `master` branch of freeCodeCamp.
- [x] None of my changes are plagiarized from another source without proper attribution.
- [x] My article does not contain shortened URLs or affiliate links.

If your pull request closes a GitHub issue, replace the XXXXX below with the issue number.

Closes #XXXXX

### CODE REVIEW

**Review by paulywill — CHANGES_REQUESTED** [review]
This looks very comprehensive.

However, can you drop the first-person pronoun "I", with indefinite articles?

e.g. 

```myResult based on what I expect above.``` changed to
```myResult based on what is expected above.```

In addition, I would not recommend including a link to your own personal repl.it example. Rather present the code as is.

**Comment by marcusparsons** [comment]
Absolutely! I'll make the changes and re-commit. Thanks, Paul!

**Review by paulywill — APPROVED** [review]
LGTM!

**Comment by paulywill** [comment]
@marcusparsons Thank you for this contribution!

IT CROWD

**Pull request merged**
