### PR TITLE
Corrected typo - missing period - in Waypoint: Continue working with Nodejs Servers

### PR DESCRIPTION
**Pull request by emersonp**
Hope I'm doing this correctly. This is my first pull request.

### CODE REVIEW

**Comment by ltegman** [comment]
Thanks for the contribution! In the future please name your branch in accordance with the conventions described in the [Pull Request Contribute](https://github.com/FreeCodeCamp/FreeCodeCamp/wiki/Pull-Request-Contribute) wiki article. Happy coding!

**Comment by emersonp** [comment]
Will do. @ltegman - The example given was "fix typo in basic-javascript challenge" - should my future PRs be all lower case and present tense?

**Comment by ltegman** [comment]
@emersonp The way to named your PR was fine, the problem was that you didn't create a branch in your local repository. For example, in the case of a fix like this you'd do something like the following before making your code change: `git checkout -b fix/waypoint-continue-working-with-nodejs-typo`. This will create a new branch on your local repository called `fix/waypoint-continue-working-with-nodejs-typo` and switch to it. Then, after you had completed your change and committed them to that branch you'd do `git push -u origin fix/waypoint-continue-working-with-nodejs-typo`. This will push the new branch you created and worked in to your remote on Github.

[This blog post](https://natacseanc.wordpress.com/2015/09/07/beginners-guide-to-easy-contributions-to-free-code-camp/) has a pretty good run down of the full process for FCC specifically that might help simplify it.

**Comment by emersonp** [comment]
Oh, okay - awesome, thanks!

**Pull request merged**
