### PR TITLE
Added never Mutate State

### PR DESCRIPTION
**Pull request by AkshayBabbar**
Added Never Mutate State

- [X] I have read [freeCodeCamp's contribution guidelines](https://github.com/freeCodeCamp/freeCodeCamp/blob/master/CONTRIBUTING.md).
- [x] My pull request has a descriptive title (not a vague title like `Update index.md`)
- [x] My pull request targets the `master` branch of freeCodeCamp.
- [x] None of my changes are plagiarized from another source without proper attribution.
- [x] My article does not contain shortened URLs or affiliate links.

If your pull request closes a GitHub issue, replace the XXXXX below with the issue number.

Closes #XXXXX

### CODE REVIEW

**Comment by AkshayBabbar** [comment]
please add reason

**Comment by ezioda004** [comment]
Hi @AkshayBabbar,

Do add proper code formatting to your article and please dont just add solution. Explain it too.

**Comment by AkshayBabbar** [comment]
> Hi @AkshayBabbar,
> 
> I think the invalid tag was added by mistake.
> 
> However, do add proper code formatting to your article and please don't just add solution. Explain it too.

Hi Can you please check others pull request also since all of them is marked invalid without a reason.

**Comment by RandellDawson** [comment]
Closed and Reopened this PR to attempt to resolve a specific Travis build failure.

**Comment by RandellDawson** [comment]
@AkshayBabbar Please make sure any solution you add includes all original seed code, plus any changes necessary for the solution to pass the tests.

Thank you.

**Comment by RandellDawson** [comment]
Hi @AkshayBabbar,

As there has been no response from your end for a while, we are closing this PR.

Feel free to request this PR to be reopened or create a new PR, if you still wish to make the changes you originally added plus any additional change requests asked of you.  Also, remember to update your fork, so you have the latest version of master in case it has changed significantly.

Happy Coding!

**Pull request closed without merging**
