### PR TITLE
fix: Change Mr. Page's firstname to Elliot (#41540)

### LINKED ISSUE #41540: Obsolete / potentially offensive cultural reference
JavaScript Algorithms and Data Structures > Functional Programming > Use the filter Method to Extract Data from an Array

The variable watchList[0]["Actors"] contains the name of a former actress who is now an actor, having transitioned gender and changed his name to _Elliot_ Page. Many people describe it as mortally offensive or even endangering to use the former names of trans people in this way, so this should probably be changed. (It appears to be standard entertainment industry practice now to retroactively change credits in this circumstance, so that is what I would suggest.)

### PR DESCRIPTION
**Pull request by akibmaredia**
Checklist:

- [x] I have read [freeCodeCamp's contribution guidelines](https://contribute.freecodecamp.org).
- [x] My pull request has a descriptive title (not a vague title like `Update index.md`)
- [x] My pull request targets the `main` branch of freeCodeCamp.
- [x] All the files I changed are in the same world language, for example: only English changes, or only Chinese changes, etc.

Closes #41540

### CODE REVIEW

**Comment by gikf** [comment]
Hey @akibmaredia 

translated versions of the challenges should not be changed directly, they will be updated using the translating workflow, after English version is changed. Could you revert these changes in the non-English files?

**Comment by gikf** [comment]
One more thing, it's better to make changes on a separate branch of your fork, rather than on your `main` branch. More about it can be read in the https://contribute.freecodecamp.org/#/how-to-setup-freecodecamp-locally?id=making-changes-locally

**Comment by akibmaredia** [comment]
I'll make the necessary changes. Thank you for the insight

**Comment by akibmaredia** [comment]
I think I will create a new pull request

**Pull request closed without merging**
