### PR TITLE
Added type to challenge and document title

### LINKED ISSUE #11061: Add challenge names and potentially breadcrumbs
We can improve the searchability of our challenges by including additional text and links in the descriptions of these challenges.

We could add the following to the top of a challenge lesson description.

(these breadcrumbs would be clickable and lead to cert/topic landing pages)
Responsive Web Design > HTML5 and CSS > Say Hello to HTML Elements

Then: "Learn to Code with HTML and Say Hello to HTML Elements"

### PR DESCRIPTION
**Pull request by keevcodes**
#### Pre-Submission Checklist

- [x] Your pull request targets the `staging` branch of FreeCodeCamp.
- [x] Branch starts with either `fix/`, `feature/`, or `translate/` (e.g. `fix/signin-issue`)
- [x] You have only one commit (if not, [squash](http://forum.freecodecamp.com/t/how-to-squash-multiple-commits-into-one-with-git/13231) them into one commit).
- [x] All new and existing tests pass the command `npm run test-challenges`. Use `git commit --amend` to amend any fixes.
#### Type of Change

- [ ] Small bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds new functionality)
- [ ] Breaking change (fix or feature that would change existing functionality)
- [ ] Add new translation (feature adding new translations)
#### Checklist:

- [x] Tested changes locally.
- [x] Closes currently open issue (replace XXXX with an issue no): Closes #11061 
#### Description

Type category was added to the seed/challenges files. Type is then rendered in the Show.jsx file and added to the updateTitle function.

### CODE REVIEW

**Comment by Bouncey** [comment]
@andmckvr13 I this isn't working for me. 

However the idea is a simpler implementation than my crack at it #11236 

We can collaborate on this if you like? I can do the redux side of it for you

**Comment by andmckvr13** [comment]
@Bouncey, yes let's work on this together! I was unsure how to test if this solution would work. I would love some help on this

**Comment by QuincyLarson** [comment]
@Bouncey I'm having trouble pulling this down to test it. I think it's because you used # in the branch name, which Git doesn't seem to like. 

```
FreeCodeCamp➜~/web/freecodecamp(andmckvr13-feature/addCategoryToChallengeViewTitle)» git pull https://github.com/andmckvr13/FreeCodeCamp.git feature/addCategoryToChallengeViewTitle#issue11061
zsh: no matches found: feature/addCategoryToChallengeViewTitle#issue11061
```

Can you rename this branch and open a new PR?

**Comment by Bouncey** [comment]
Closing and re-opening as #11251

**Pull request closed without merging**
