### PR TITLE
fix(curriculum): Completed the step 6 in instructions for building a role playing game

### LINKED ISSUE #52774: Missing instructions for Step 6 of the JS Beta Certification - Learn Basic JavaScript by Building a Role Playing Game
### Describe the Issue

Hi,
I noticed that partial instructions are given to complete step 6 (that is part of the Beta version of the new JS certification)

The current instructions at step 6 say:
"Similar to your `#stats` element, your `#monsterStats` element needs two `span` elements. Give them the class `stat` and give the first element the text `Monster Name: ` and the second the text `Health: `. After the text in each, add a `strong` element **with an empty nested `span` element**."

At step 7 the HTML code has the two `span`, those created in the previous step after `Monster Name: ` and `Health: ` ,with respectively:

- `<span id="monsterName"></span>`
- `<span id="monsterHealth"></span>`

Also _at step 34 and 35_ the `id` of these two `span` are both used in the code

**Instructions at step 34:**

"Just like you did with the buttons, create variables for the following `id`s and use `querySelector()` to give them the element as a value:

`text`, `xpText`, `healthText`, `goldText`, `monsterStats`, and `monsterName`.

Remember to declare these with the `const` keyword, and name the variables to match the `id`s."

**Instructions at step 35:**

Finally, use `querySelector()` to get the `#monsterHealth` element. Because you have already declared a `monsterHealth` variable earlier, you need to use a different variable name for this element.

Declare a new variable with the `const` keyword and name it `monsterHealthText`.

### Affected Page

 https://www.freecodecamp.org/learn/javascript-algorithms-and-data-structures-v8/learn-basic-javascript-by-building-a-role-playing-game/step-6

### Your code

```
     <div id="monsterStats">

     </div>
```

### Expected behavior

I think the instructions of step 6 should include the request to:

- add to the the two `span` (created after the texts `Monster Name: ` and `Health: ` )
the `id` of `monsterName` for the first `span` and the `id` of `monsterHealth` for the second `span`

### Screenshots

step6fCC

step7fCC

### System

Device: [e.g. iPhone 6, Laptop]
OS: [e.g. iOS 14, Windows 10, Ubuntu 20.04]
Browser: [e.g. Chrome, Safari]
Version: [e.g. 22]

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by usamabasharat**
Checklist:

- [x] I have read and followed the [contribution guidelines](https://contribute.freecodecamp.org).
- [x] I have read and followed the [how to open a pull request guide](https://contribute.freecodecamp.org/#/how-to-open-a-pull-request).
- [x] My pull request targets the `main` branch of freeCodeCamp.
- [x] I have tested these changes either locally on my machine, or GitPod.

Closes #52774

### CODE REVIEW

**Review by huyenltnguyen — COMMENTED** [review]
Hey @usamabasharat, thank you for the PR.

Since we are adding more items to the requirements, the additional tests also need to be added to the challenge, so please add them in as well.

**Comment by usamabasharat** [comment]
> Hey @usamabasharat, thank you for the PR.
> 
> Since we are adding more items to the requirements, the additional tests also need to be added to the challenge, so please add them in as well.

Hey @huyenltnguyen, I have added the tests as well.

**Review by huyenltnguyen — APPROVED** [review]
LGTM. Thanks @usamabasharat.

**Review by jdwilkin4 — APPROVED** [review]

**Comment by jdwilkin4** [comment]
Hi @usamabasharat ! 

Congrats on your first contribution to our repository. 🎉
We look forward to future contributions. 👍

**Pull request merged**
