### PR TITLE
Formatting and added a new source

### PR DESCRIPTION
**Pull request by JIBIN-P**
The bold I guess wasn't showing up so did some formatting there and numbered the sources too.
Added one new source.

- [x] I have read [freeCodeCamp's contribution guidelines](https://github.com/freeCodeCamp/freeCodeCamp/blob/master/CONTRIBUTING.md).
- [x] My pull request has a descriptive title (not a vague title like `Update index.md`)
- [x] My pull request targets the `master` branch of freeCodeCamp.
- [x] None of my changes are plagiarized from another source without proper attribution.
- [x] My article does not contain shortened URLs or affiliate links.

If your pull request closes a GitHub issue, replace the XXXXX below with the issue number.

Closes #XXXXX

### CODE REVIEW

**Comment by JIBIN-P** [comment]
@RandellDawson Can you please take a look into this issue and resolve the failing status and if something more needs to be edited in the file then please point me in the right direction.

**Comment by RandellDawson** [comment]
Sorry for not getting back to you sooner.  I see you closed it.  Did you open a new PR?  This had a merge conflict on it, but since you closed it, I can not see it anymore.  If you want to reopen it, please do and send me another message.  Back 17 days ago when you first sent me a message we were very busy with Hacktoberfest.  I now have more time to help you.

**Comment by JIBIN-P** [comment]
Yeah I thought so and since there was merge conflict I thought it wouldn't be merged into the main branch, if there's still a possibility of merging plz do so.

**Comment by RandellDawson** [comment]
Thank you for your contribution to the page! 👍
We're happy to accept these changes, and look forward to future contributions. 🎉

**Pull request merged**
