### PR TITLE
Solution to specify-exact-number-of-matches.english JavaScript Challenge 

### PR DESCRIPTION
**Pull request by aesher9o1**
Added an explanation to the working code too

- [x] I have read [freeCodeCamp's contribution guidelines](https://github.com/freeCodeCamp/freeCodeCamp/blob/master/CONTRIBUTING.md).
- [x] My pull request has a descriptive title (not a vague title like `Update index.md`)
- [x] My pull request targets the `master` branch of freeCodeCamp.
- [x] None of my changes are plagiarized from another source without proper attribution.
- [x] All the files I changed are in the same world language (for example: only English changes, or only Chinese changes, etc.)
- [x] My changes do not use shortened URLs or affiliate links.

### CODE REVIEW

**Review by paulywill — CHANGES_REQUESTED** [review]
Tested locally... tests passing.

I recommend not including "/i" at the ending, as the instructions did not indicate to be case insenstive and even expecting to match a specific mixed case instance.

**Comment by RandellDawson** [comment]
@aesher9o1 I agree with @paulywill on this requested change.

**Comment by aesher9o1** [comment]
Sure!! I'll do the needful.

**Comment by RandellDawson** [comment]
@paulywill I made the requested changes on behalf of the user.  I also removed the comments in the code, which did were not necessary.  I have tested the solution.  If you are OK with the changes, please approve and merge at will.

**Review by paulywill — APPROVED** [review]

**Comment by paulywill** [comment]
@aesher9o1 @RandellDawson Thank you!

**Pull request merged**
