### PR TITLE
delete code of conduct

### PR DESCRIPTION
**Pull request by texas2010**
#### Pre-Submission Checklist

- [ ] Your pull request targets the `staging` branch of freeCodeCamp.
- [x] Branch starts with either `fix/`, `feature/`, or `translate/` (e.g. `fix/signin-issue`)
- [ ] You have only one commit (if not, [squash](http://forum.freecodecamp.com/t/how-to-squash-multiple-commits-into-one-with-git/13231) them into one commit).
- [ ] All new and existing tests pass the command `npm test`. Use `git commit --amend` to amend any fixes.

#### Type of Change

- [x] Small bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds new functionality)
- [ ] Breaking change (fix or feature that would change existing functionality)
- [ ] Add new translation (feature adding new translations)

#### Checklist:

- [ ] Tested changes locally.
- [ ] Closes currently open issue (replace XXXX with an issue no): Closes #XXXX

#### Description

#15474

### CODE REVIEW

**Comment by BerkeleyTrue** [comment]
You'll also need to remove the router handler for that route.

**Comment by texas2010** [comment]
@BerkeleyTrue oh dang it. how could I find it? I don't know where/what files. thanks

**Comment by mdxedia** [comment]
Dear SIr,

Here my typodeart for you. Please review and you can launched.

Regards


[image: --]

Md Xedia
[image: https://]about.me/mxedia
<https://about.me/mxedia?promo=email_sig&utm_source=product&utm_medium=email_sig&utm_campaign=chrome_ext>

**Comment by dhcodes** [comment]
@texas2010 I believe the coc routes are here: https://github.com/freeCodeCamp/freeCodeCamp/blob/d9c166111b5d0b3d8e16c908e0f9dd73e5d6610a/server/boot/randomAPIs.js

**Comment by texas2010** [comment]
@dhcodes oh thank you so much.

**Comment by texas2010** [comment]
Whew, I hope I do it right. There. I did remove router handler.

**Comment by dhcodes** [comment]
@texas2010 closing as duplicate?

**Comment by texas2010** [comment]
@dhcodes but this is for backup/master. we already have COC in static. so we can remove it.

**Comment by BerkeleyTrue** [comment]
@texas2010 You have some conflicts (probably the .org transition stuff)

**Comment by texas2010** [comment]
Oh odd. i will check it out tomorrow morning.  probably try rebase it.

**Comment by dhcodes** [comment]
Sorry @texas2010 my bad.

**Comment by texas2010** [comment]
@dhcodes it is fine.

@BerkeleyTrue, there, I fixed it.

**Pull request merged**
