### PR TITLE
Added more options with examples and numerical format for providing permissions

### PR DESCRIPTION
**Pull request by saravannann**
- [x] I have read [freeCodeCamp's contribution guidelines](https://github.com/freeCodeCamp/freeCodeCamp/blob/master/CONTRIBUTING.md).
- [x] My pull request has a descriptive title (not a vague title like `Update index.md`)
- [x] My pull request targets the `master` branch of freeCodeCamp.
- [x] None of my changes are plagiarized from another source without proper attribution.
- [x] My article does not contain shortened URLs or affiliate links.

If your pull request closes a GitHub issue, replace the XXXXX below with the issue number.

Closes #XXXXX

### CODE REVIEW

**Comment by saravannann** [comment]
@nikrb : You are right nik. Can i work on this ?

**Comment by ezioda004** [comment]
@saravannann Ofcourse you can, its your PR :')

**Comment by RandellDawson** [comment]
@nikrb This one is stale.  I suggest closing it and asking the user to request it to be reopened if they still want to work on this PR.

**Comment by RandellDawson** [comment]
Hi @saravannann,

As there has been no response from your end for a while, I am closing this PR.

Feel free to request this PR to be reopened, if you still wish to make the changes you originally added.  Also, remember to update your fork, so you have the latest version of master in case it has changed significantly.

Happy Coding!

**Pull request closed without merging**
