### PR TITLE
Make code-uri more robust

### LINKED ISSUE #5033: Previous accepted solution to bonfire isn't displayed when accessing solution from profile
http://www.freecodecamp.com/challenges/bonfire-arguments-optional?solution=function%20add()%20%7B%0A%20%20var%20args%20%3D%20Array.prototype.slice.call(arguments)%3B%0A%20%20var%20isNumber%20%3D%20function(num)%20%7B%0A%20%20%20%20return%20(Number(num)%20%3D%3D%3D%20num)%20%3F%20num%20%3A%20undefined%3B%0A%20%20%7D%3B%0A%20%20for%20(var%20i%3D0%3B%20i%3C%20args.length%3B%20i%2B%2B)%20%7B%0A%20%20%20%20if%20(!isNumber(args%5Bi%5D))%20%7B%0A%20%20%20%20%20%20return%20undefined%3B%0A%20%20%20%20%7D%0A%20%20%7D%0A%20%20if%20(args.length%20%3D%3D%3D%202)%20%7B%0A%20%20%20%20return%20args.reduce(function(x%2Cy)%20%7B%20return%20x%2By%3B%7D)%3B%0A%20%20%7D%20else%20%7B%0A%20%20%20%20%20%20%0A%20%20%20%20%20%20return%20function(num)%20%7B%0A%20%20%20%20%20%20%20%20if%20(isNumber(num)%20%3D%3D%3D%20undefined)%20%7B%0A%20%20%20%20%20%20%20%20%20%20return%20undefined%3B%0A%20%20%20%20%20%20%20%20%7D%20else%20%7B%0A%20%20%20%20%20%20%20%20%20%20console.log(args%5B0%5D%20%2B%20%22%20%22%2Bnum)%3B%0A%20%20%20%20%20%20%20%20%20%20return%20args%5B0%5D%20%2B%20num%3B%0A%20%20%20%20%20%20%20%20%20%20%0A%20%20%20%20%20%20%20%20%7D%0A%20%20%20%20%20%20%7D%3B%20%20%20%20%20%20%20%20%20%20%20%20%20%0A%20%20%7D%0A%7D%0A%0Aadd(2)(3)%3B%0A

That is the link to my solution for the Arguments Optional Bonfire.

What is displayed to me when I click that link is the default "starter code" as if I'd reset the bonfire
```
function add() {
  return false;
}

add(2,3);
```
The "displayer of previous solution" functionality seems to be intermittently broken, I can retrieve my prior solutions on some bonfires, but not others.

### PR DESCRIPTION
**Pull request by BerkeleyTrue**
closes #5033

### CODE REVIEW

**Comment by bugron** [comment]
Works great, thanks!

**Comment by P1xt** [comment]
Any idea when this will be pushed live?

**Comment by bugron** [comment]
This is already live.

**Comment by P1xt** [comment]
Then it didn't actually fix the issue I opened and was closed as a result of the "fix" #5033 because I tested it right before I posed asking when it'd go live, and it still wasn't fixed.

**Comment by P1xt** [comment]
Update: I've logged in with multiple browsers and though I can browse other users profiles (and could browse my own this morning), now I get the message "Oops! Something went wrong. Please try again later" if I attempt to browse to my own profile using the direct url, by clicking my avatar in the top menu, or by clicking my [points] in the top menu.

**Comment by P1xt** [comment]
Update: I don't know what changed in the past 18 minutes, but I can (once again) get to my profile, and now (from my profile) my prior solutions appear to display correctly. My solutions also appear to be showing up appropriately on my map as well. Thank you :+1:

**Comment by BerkeleyTrue** [comment]
@P1xt I've created a hot fix on the server. For now things work as usual. Unfortunately (or fortunately?) this exposed another issue. It seems bonfires are not being saved, or saved without solutions. Not sure which is causing the issue just yet. Working on a pr for both problems.

**Comment by P1xt** [comment]
@BerkeleyTrue Yeah, I just started going down my map and clicking bonfires I'd solved. A number of them remain "reset" while others show my solution even though it now appears that my solutions are universally available on my profile. It's odd that the system can find my solution if I'm on my profile, but not find it if I'm on my Map. Please feel free to holler if you need or want a hand with anything.

**Comment by P1xt** [comment]
@BerkeleyTrue  Update: This is still not fixed. There are bonfires I've completed that I can access via my profile that are "reset" on my map. The map still isn't universally parsing solutions and displaying them when you click on completed bonfires. The solution is obviously saved and available or it wouldn't be accessible from my profile so I would surmise the issue is in the map parsing the solution and displaying it.

**Comment by BerkeleyTrue** [comment]
@P1xt We don't put your solutions on the map.

**Comment by SaintPeter** [comment]
@BerkeleyTrue I believe he means on his "Profile" page.

**Comment by BerkeleyTrue** [comment]
> I can access via my profile that are "reset" on my map.

**Comment by P1xt** [comment]
Two weeks ago, if I clicked on any item on my map that I had already completed, the page that loaded showed me the state at which that page was when last I clicked submit.

Now, some of my "map entries" show a reset state. And, others show the state of the page when I last clicked submit.

@BerkeleyTrue I mean on my map. The profile page was broken too but that seems fixed now.

@SaintPeter We most certainly do show solutions when one clicks on a previously completed entry on the map. The problem is that it was broken a couple weeks ago and now some show it and some don't.

**Comment by BerkeleyTrue** [comment]
@P1xt We do not have solutions on the map. We do store them in your localStorage. This is written whenever on a debounced keystroke. If you have the solution in your profile, load the through the link, add and remove a key and wait 1 second and they will be saved to localStorage.

The intent of code storage is to allow you to keep going on a challenge that you have not completed. It is not meant to be permanent storage.

**Comment by P1xt** [comment]
@BerkeleyTrue Ah, that's unfortunate but I understand how they started falling out of local storage (I probably cleared cache at some point.

From a UX perspective - if I click on an item on my map, complete that item, submit that item ... and later return to that item, it should be the way I left it. I have to wonder why the decision was made to intentionally introduce a disconnect.

**Pull request merged**
