### PR TITLE
[WIP]Re-seed database when seed files change

### LINKED ISSUE #10022: Live-updating broken for local FCC instance
Live-updating on file save is not working correctly. Saving a file does cause an open page to refresh, but changes do not take effect until the database is re-seeded and `gulp` is run again. A simple `gulp` restart has no effect.

Observed on latest staging with updated npm and all the correct post-reactification packages.

`(Macintosh; Intel Mac OS X 10_11_6)`

### PR DESCRIPTION
**Pull request by Bouncey**
#### Pre-Submission Checklist

- [x] Your pull request targets the `staging` branch of freeCodeCamp.
- [x] Branch starts with either `fix/`, `feature/`, or `translate/` (e.g. `fix/signin-issue`)
- [x] You have only one commit (if not, [squash](http://forum.freecodecamp.com/t/how-to-squash-multiple-commits-into-one-with-git/13231) them into one commit).
- [x] All new and existing tests pass the command `npm test`. Use `git commit --amend` to amend any fixes.

#### Type of Change

- [x] Small bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds new functionality)
- [ ] Breaking change (fix or feature that would change existing functionality)
- [ ] Add new translation (feature adding new translations)

#### Checklist:

- [x] Tested changes locally.
- [x] Closes currently open issue (replace XXXX with an issue no): Closes #10022 

#### Description

Added WebSocket to `gulp` can initiate a `fetchChallenges` action.

### CODE REVIEW

**Comment by Bouncey** [comment]
@BerkeleyTrue Gulp is causing `fetchChallenges` to dispatch, but the challenge instructions remain unchanged.

What am I missing?

**Comment by BerkeleyTrue** [comment]
Noice. This is exactly the direction I would have taken. I tried to tackle this a couple of months ago and found that there is a bug in loopback itself that caches challenges when using the include method. This would have to change to get everything else to work.

**Comment by Bouncey** [comment]
Could you point me to where it is? Is there an open issue with Loopback?

**Comment by Bouncey** [comment]
I read somewhere in the Loopback docs that this is not possible due to the way Loopback references data from mongodb. 

As seen I have tried the websocket approach, I have tried forcing a reload after `node seed` and finally I have tried automating the restart of the entire `gulp` process. 

It's just not happening, as it stands, we have lost the 'live updating' of the challenge seed :crying_cat_face:

**Pull request closed without merging**
