### PR TITLE
feat(client): adjustable scrollbar width in code editor

### PR DESCRIPTION
**Pull request by bbsmooth**
Checklist:

- [x] I have read and followed the [contribution guidelines](https://contribute.freecodecamp.org).
- [x] I have read and followed the [how to open a pull request guide](https://contribute.freecodecamp.org/#/how-to-open-a-pull-request).
- [x] My pull request targets the `main` branch of freeCodeCamp.
- [x] I have tested these changes either locally on my machine, or GitPod.

Closes #XXXXX

Based on the excellent suggestion from @raisedadead in this forum post:

https://forum.freecodecamp.org/t/scroll-wheel-size-is-too-small/602363

This implements the ability for the user to customize the width of the vertical scroll bar in the monaco editor.

### CODE REVIEW

**Comment by bbsmooth** [comment]
I basically designed a new input to use for this feature. Would love to get some feedback on it. If it doesn't fit in I'm more than happy to make changes or scrap it and start over with something else.

**Review by raisedadead — COMMENTED** [review]
The component looks fantastic to me. One nitpick:

image

I will defer to @ahmadabdolsaheb on this.

**Comment by ahmadabdolsaheb** [comment]
Great job with the scrollbar settings component. Here are some suggestions:

- Change the name to Editor Scrollbar Width 
- Increase the height of the keyboard shortcut component’s spacer to medium (15px) so there are enough space to separate those two settings.
- getScrollbarWidth function is duplicated. Set it as a helper and use it in both places?
- A cypress test would be appreciated for the new feature.
- The lower jaw overlaps the scrollbar when it is wide:
Screenshot 2023-04-12 at 10 49 45 AM

**Comment by ahmadabdolsaheb** [comment]
let us know when this is ready for the next round.

**Comment by bbsmooth** [comment]
Yes, please, it's ready for another look.

**Review by raisedadead — APPROVED** [review]
LGTM. 

The range of 5-25 is a bit too much. I think it should be OK to give them a range of 5-15 and make the stops more granular (like a stop every 3's)

But at this point, I am not holding this feature. Nice work!

**Review by ahmaxed — APPROVED** [review]
Thank you for your contribution to the settings page. I bet the mobile users would appreciate the wide scroll bar.

**Pull request merged**
