### PR TITLE
feat(curriculum, i18n): enable a super block in Chinese

### PR DESCRIPTION
**Pull request by miyaliu666**
Checklist:

- [x] I have read and followed the [contribution guidelines](https://contribute.freecodecamp.org).
- [x] I have read and followed the [how to open a pull request guide](https://contribute.freecodecamp.org/how-to-open-a-pull-request/).
- [x] My pull request targets the `main` branch of freeCodeCamp.
- [x] I have tested these changes either locally on my machine, or GitPod.

JS new curriculum is fully localised and ready to go.

### CODE REVIEW

**Review by sidemt — COMMENTED** [review]
Thanks, Miya!

I'm wondering if we should do the same for `Languages.ChineseTraditional` at the same time. Probably @naomi-lgbt can confirm?

**Comment by naomi-lgbt** [comment]
Yes. But this is blocked anyway, until I've resolved the i18n build issues.

**Comment by ilenia-magoni** [comment]
i18n issues are solved now

**Comment by miyaliu666** [comment]
I just find the Foundational C# course is not there in Traditional Chinese, so I remove that superblock, too. Thank you.

**Review by sidemt — APPROVED** [review]
LGTM 👍

**Review by majestic-owl448 — APPROVED** [review]

**Pull request merged**
