### PR TITLE
fix(common): Fix for loopProtect undefined error

### LINKED ISSUE #16260: loopProtect is not defined problem on beta
With some of the challenges, such as the algorithm challenges, we're experiencing this problem:

learn_to_code___freecodecamp

This may be related to https://github.com/freeCodeCamp/freeCodeCamp/issues/13532, but I'm experiencing this in edge Chrome (Version 63.0.3239.84 (Official Build) (64-bit) on MacOS)

### PR DESCRIPTION
**Pull request by scissorsneedfoodtoo**
#### Pre-Submission Checklist

- [x] Your pull request targets the `staging` branch of freeCodeCamp.
- [x] Branch starts with either `fix/`, `feature/`, or `translate/` (e.g. `fix/signin-issue`)
- [x] You have only one commit (if not, [squash](http://forum.freecodecamp.org/t/how-to-squash-multiple-commits-into-one-with-git/13231) them into one commit).
- [x] All new and existing tests pass the command `npm test`. Use `git commit --amend` to amend any fixes.

#### Type of Change

- [x] Small bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds new functionality)
- [ ] Breaking change (fix or feature that would change existing functionality)
- [ ] Add new translation (feature adding new translations)

#### Checklist:

- [x] Tested changes locally.
- [x] Addressed currently open issue (replace XXXXX with an issue no in next line)

Closes #16260

#### Description

Edited the file so that the loopProtect code, which is in the head of
the iframe on www.freecodecamp.org, is in the same script tag as the
base challenge content that get's rendered to the page. While the
loopProtect code is not rendered to the page like the rest of the
challenge code, it's within the same scope and seems to function
normally.

BREAKING CHANGE: None that I know of, but will keep checking.

### CODE REVIEW

**Comment by QuincyLarson** [comment]
@scissorsneedfoodtoo Awesome! Thank you for doing this so quickly.

@BerkeleyTrue could you take a look at this code and this approach, and QA it if you think it's a sound approach?

**Review by Ethan-Arrowood — COMMENTED** [review]
LGTM - going to run locally and test with one of my ES6 challenges next and approve if it solves the loopProtect issue

**Review by BerkeleyTrue — APPROVED** [review]

**Review by Ethan-Arrowood — APPROVED** [review]

**Comment by Ethan-Arrowood** [comment]
Great work on this! Was able to run my new changes to ES6 curriculum and get the LoopProtect error to go away 👍

**Comment by QuincyLarson** [comment]
@BerkeleyTrue @Ethan-Arrowood Thanks for taking a look at this and evaluating its approach. 

I can confirm that it works great on my end.

@scissorsneedfoodtoo thank you so much for this pull request!

**Comment by scissorsneedfoodtoo** [comment]
No problem! I'm glad it worked. Was kind of just throwing things at the wall, but was happy to find a solution.

**Pull request merged**
