### PR TITLE
fix(curriculum): spelling of cinnamon in RWD Camper Cafe Menu

### LINKED ISSUE #44596: RWD Beta, Create Cafe Menu, Cinnamon is spelled wrong.
## Affected page

Problem begins at Step 53 and continues throughout the rest of the tutorial (Step 92)
https://www.freecodecamp.org/learn/2022/responsive-web-design/learn-basic-css-by-building-a-cafe-menu/step-53

## To reproduce

Am able to see in private browsing mode too. 

## Recommended fix, suggestions

Wherever the code is located that has the word "Cinammon", fixing the spelling error so it's "Cinnamon". 

## Screenshots
First page it's incorrect.
Screen Shot 2021-12-27 at 10 34 39 AM

Last page, showing it's still incorrect.
Screen Shot 2021-12-27 at 10 35 17 AM

### PR DESCRIPTION
**Pull request by xoxoKaralee**
Checklist:

- [x] I have read [freeCodeCamp's contribution guidelines](https://contribute.freecodecamp.org).
- [x] My pull request has a descriptive title (not a vague title like `Update index.md`)
- [x] My pull request targets the `main` branch of freeCodeCamp.
- [x] I have tested these changes either locally on my machine, or GitPod. ***see notes**

Closes #44596

Every instance of the word "Cinammon" has been replaced with "Cinnamon".

*I have tried to go through "set up FCC locally" but i'm currently working on the MongoDB part since i've never used it before. I'm in the contributors chat if anyone wants to assist in getting me set up so i can run locally i'd appreciate any help! 

Update: I've attempted to view changes through Gitpod > Remote Explorer > port 8000 but the RWD beta just isnt there. I tried copying and pasting the end url into the remote explorer, and the page didnt exist. 

Update 2: it ran and passed the checks in github. I'm marking the check off.

### CODE REVIEW

**Review by ejcheng — DISMISSED** [review]
LGTM

**Review by gikf — CHANGES_REQUESTED** [review]
There's one more place with _Cinammon_, solutions in step `92`: https://github.com/freeCodeCamp/freeCodeCamp/blob/5a4fe42760f416a0adcb6857ee2cc447f1a878a7/curriculum/challenges/english/14-responsive-web-design-22/learn-basic-css-by-building-a-cafe-menu/step-092.md?plain=1#L250

**Review by gikf — APPROVED** [review]

**Review by ejcheng — APPROVED** [review]

**Review by jdwilkin4 — APPROVED** [review]
LGTM! 👍

**Comment by gikf** [comment]
Hi @xoxoKaralee. Congrats on your first pull request (PR)! 🎉

Thank you for your contribution to the page! 👍
We are happy to accept these changes and look forward to future contributions. 📝

**Pull request merged**
