### PR TITLE
feat: adding explanation for id selector for cafe menu project

### LINKED ISSUE #51319: Need proper introduction for CSS id selector
### Describe the Issue

I believe that [step 8 of the accessibility quiz](https://www.freecodecamp.org/learn/2022/responsive-web-design/learn-accessibility-by-building-a-quiz/step-8) is the first time the CSS id selector is introduced. (I searched the previous courses and did not find it. Even though the registration form uses the `id` attribute on some HTML elements it does not style them with the id selector.) The instructions for step 8 ask the user to style the image using its `id` as the selector but they don't explain how to do that. The user only gets this information from a hint if they don't do it correctly.

### Affected Page

https://www.freecodecamp.org/learn/2022/responsive-web-design/learn-accessibility-by-building-a-quiz/step-8

### Your code

N/A

### Expected behavior

I think it is preferable if we explain how to use the `id` selector in the instructions instead of having the user fail and then telling them how to do it through a hint. Since step 8 already has a considerable amount of content explaining the `max` function, one option would be to create a new step just for explaining the `id` selector. Step 9 has the user add `padding` to the image, so we could create a new step before the current step 8 with an explanation on how to target by `id` and have them add the `padding` in that step instead (since they are already familiar with that property). This new step would be similar to [step 26 in the Cafe Menu.](https://www.freecodecamp.org/learn/2022/responsive-web-design/learn-basic-css-by-building-a-cafe-menu/step-26).

But if adding a step is a pain then we could swap step 8 and step 9 since step 9 has a relatively small amount of content, and add the explanation of the `id` selector there.

Or we could look for a place in a previous course to use the id selector. It does seem a little odd to wait so long to use it since it is a pretty popular selector.

Or I suppose we could do nothing and keep relying on the hint to give them the information after the fact. To be honest, I don't recall seeing too many issues about this in the forums. I did a search and maybe found one or two that were about this issue out of the thirty or so I looked at. So perhaps the hint method is doing its job? It just seems to me that an important and common selector like this should be clearly explained up front. This isn't something they would be able to deduce from information they have already learned. They would need to go to an outside source to figure it out since it is a completely new selector.

### Screenshots

_No response_

### System

N/A

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by jdwilkin4**
## Summary of changes made

This PR is responsible for adding an explanation for the id selector.
For step 20, we are adding the id of menu to the div

Step 21 has the explanation for the id selector. 

In step 26, we change it to use the class selector just like in the current version

closes #51319 

Checklist:

- [x] I have read and followed the [contribution guidelines](https://contribute.freecodecamp.org).
- [x] I have read and followed the [how to open a pull request guide](https://contribute.freecodecamp.org/#/how-to-open-a-pull-request).
- [x] My pull request targets the `main` branch of freeCodeCamp.
- [x] I have tested these changes either locally on my machine, or GitPod.

### CODE REVIEW

**Review by Sboonny — CHANGES_REQUESTED** [review]
The seed code in the following files hasn't been updated to reflect changes

https://github.com/jdwilkin4/freeCodeCamp/blob/feat-adding-id-selector-explanation/curriculum/challenges/english/14-responsive-web-design-22/learn-basic-css-by-building-a-cafe-menu/5f76967fad478126d6552b0d.md#--seed-contents--

**Comment by jdwilkin4** [comment]
Hey @Sboonny 

Can you point out what needs to be changed in step 34, because the seed code looks correct to me
In steps 26 and 27, we remove the menu id and just use the menu class for the rest of the project
thanks 👍

**Review by Sboonny — APPROVED** [review]

**Comment by Sboonny** [comment]
Make sense, thank you for the clarification 👍.

**Review by naomi-lgbt — APPROVED** [review]
Reminding myself to remove jQuery from the tests

**Pull request merged**
