### PR TITLE
fix(curriculum): enhance width calculation expressions

### LINKED ISSUE #55821: platformer game (js beta) step 84 and step 88 (and step 89) check is too strict
### Describe the Issue

In the platformer game's (js beta) step 84 (and step 88), the step expects us to write this new line of code
```js
      player.position.x >= platform.position.x - player.width / 2
```

but doesn't accept this equally valid variation (at least in my view, it is valid):
```js
      player.position.x >= platform.position.x - (0.5 * player.width)
```

When we provide the variation above, the hint also does not provide any help to direct us to what it needs us to write.
(Note that the instructions also do not make mention of a specific method for getting "half of the player's width" so it is open to interpretation there too)
please note other steps have similar issues but with different numbers (like step 89)

### Affected Page

https://www.freecodecamp.org/learn/javascript-algorithms-and-data-structures-v8/learn-intermediate-oop-by-building-a-platformer-game/step-84
https://www.freecodecamp.org/learn/javascript-algorithms-and-data-structures-v8/learn-intermediate-oop-by-building-a-platformer-game/step-88
https://www.freecodecamp.org/learn/javascript-algorithms-and-data-structures-v8/learn-intermediate-oop-by-building-a-platformer-game/step-89
### Your code

as above.

### Expected behavior

Either fix the check to allow users to multiply by 0.5 (in addition to divide by 2) or update the text of the step and the hints to be more explicit about a division operator being a requirement to finding half the width.

### Screenshots

_No response_

### System

N/A

### Additional context

There's a similar problem in step 85, but it is mitigated there by the hint which actually says that we should divide by 3. (on my first attempt, I multiplied by 1/3 which was not accepted)

Also whatever fix is done for step 84 should apply to step 88 too as they have the same issue.
Please also look at updating step 89 checks/hints as well to match whatever decision is reached here. (either update the hint to be like step 85 and say that division is required or update the step's checks to allow multiplication by 1/3)

### PR DESCRIPTION
**Pull request by TofikE124**
- [x] I have read and followed the [contribution guidelines](https://contribute.freecodecamp.org).
- [x] I have read and followed the [how to open a pull request guide](https://contribute.freecodecamp.org/how-to-open-a-pull-request/).
- [x] My pull request targets the `main` branch of freeCodeCamp.
- [x] I have tested these changes either locally on my machine, or GitPod.

Closes #55821 

# Summary of Updates

## Enhancements to Collision Detection and Width Calculations

These updates enhance the flexibility of collision detection rules and width calculations, allowing for a wider range of expression formats.

### Step 84: Half Width Calculation
- **Previous Limitation:**
  - Only recognized straightforward expressions like:
    ```javascript
    player.position.x >= platform.position.x - player.width / 2
    ```
- **New Capabilities:**
  - Supports various formats, including:
    ```javascript
    player.position.x >= platform.position.x - (player.width / 2)
    player.position.x >= platform.position.x - player.width * 0.5
    player.position.x >= platform.position.x - (0.5 * player.width)
    ```

### Step 85: One-Third Width Calculation
- **Previous Limitation:**
  - Recognized only:
    ```javascript
    player.position.x <= platform.position.x + platform.width - player.width / 3
    ```
- **New Capabilities:**
  - Handles multiple expressions, such as:
    ```javascript
    player.position.x <= platform.position.x + platform.width - (player.width / 3)
    player.position.x <= platform.position.x + platform.width - player.width * 1/3
    player.position.x <= platform.position.x + platform.width - (1/3 * player.width)
    ```

### Step 88: Additional Variants for One-Third Width
- **Previous Limitation:**
  - Limited to specific formats for one-third width calculations.
- **New Capabilities:**
  - Accommodates various representations including:
    ```javascript
    player.position.x <= platform.position.x + platform.width - player.width / 3
    player.position.x <= platform.position.x + platform.width - (player.width / 3)
    player.position.x <= platform.position.x + platform.width - player.width * 1/3
    player.position.x <= platform.position.x + platform.width - (1/3 * player.width)
    ```

### Step 89: Final Calculation Adjustment
- **Previous Limitation:**
  - Expression for comparing player’s `x` position and platform's dimensions did not account for all valid formats.
- **New Capabilities:**
  - Now accommodates various valid expressions, including:
    ```javascript
    player.position.x <= platform.position.x + platform.width - player.width / 3
    player.position.x <= platform.position.x + platform.width - (player.width / 3)
    player.position.x <= platform.position.x + platform.width - player.width * 1/3
    player.position.x <= platform.position.x + platform.width - (1/3 * player.width)
    ```

## Examples of Code That Works Now

- **Half Width Calculation:**
  - **Before:**
    ```javascript
    player.position.x >= platform.position.x - player.width / 2
    ```
  - **Now:**
    ```javascript
    player.position.x >= platform.position.x - (player.width / 2)
    player.position.x >= platform.position.x - player.width * 0.5
    player.position.x >= platform.position.x - (0.5 * player.width)
    ```

- **One-Third Width Calculation:**
  - **Before:**
    ```javascript
    player.position.x <= platform.position.x + platform.width - player.width / 3
    ```
  - **Now:**
    ```javascript
    player.position.x <= platform.position.x + platform.width - (player.width / 3)
    player.position.x <= platform.position.x + platform.width - player.width * 1/3
    player.position.x <= platform.position.x + platform.width - (1/3 * player.width)
    ```

These updates ensure that the code now accommodates a broader range of calculations and formats, making it more flexible and versatile.

### CODE REVIEW

**Review by Sembauke — CHANGES_REQUESTED** [review]
Hey @TofikE124,

This is looking good! Thank you for the detailed message. Could you put all these different type of assertions in separate variables? It makes them easier to read.

**Comment by TofikE124** [comment]
Hey @Sembauke, I just want to make sure we are on the same page, do you mean something like this ?

# Original Code

```javascript
assert.match(code, /const\s+collisionDetectionRules\s*=\s*\[\s*player\.position\.y\s*\+\s*player\.height\s*<=\s*platform\.position\.y\s*,\s*player\.position\.y\s*\+\s*player\.height\s*\+\s*player\.velocity\.y\s*>=\s*platform\.position\.y\s*,\s*player\.position\.x\s*>=\s*platform\.position\.x\s*-\s*(?:\(\s*player\.width\s*\/\s*2\s*\)|player\.width\s*\/\s*2|player\.width\s*\*\s*0\.5|\(\s*player\.width\s*\*\s*0\.5\s*\)|0\.5\s*\*\s*player\.width|\(\s*0\.5\s*\*\s*player\.width\s*\))\s*,?\s*]\s*;?/);
```

# Refactored Code

```javascript
const yHeightCheck = /player\.position\.y\s*\+\s*player\.height\s*<=\s*platform\.position\.y/;
const yVelocityCheck = /player\.position\.y\s*\+\s*player\.height\s*\+\s*player\.velocity\.y\s*>=\s*platform\.position\.y/;
const xHalfWidthCheck = /player\.position\.x\s*>=\s*platform\.position\.x\s*-\s*(?:\(\s*player\.width\s*\/\s*2\s*\)|player\.width\s*\/\s*2|player\.width\s*\*\s*0\.5|\(\s*player\.width\s*\*\s*0\.5\s*\)|0\.5\s*\*\s*player\.width|\(\s*0\.5\s*\*\s*player\.width\s*\))/;

const regexPattern = new RegExp(
  `const\\s+collisionDetectionRules\\s*=\\s*\\[\\s*${yHeightCheck.source}\\s*,\\s*${yVelocityCheck.source}\\s*,\\s*${xHalfWidthCheck.source}\\s*,?\\s*\\]\\s*;?`
);

assert.match(code, regexPattern);
```

**Comment by Sembauke** [comment]
Yes, that is exactly what I mean!

**Comment by TofikE124** [comment]
@Sembauke 

Done!

**Comment by ojeytonwilliams** [comment]
Hi @TofikE124 could you take a look at these conflicts?

**Pull request closed without merging**
