### PR TITLE
fix issue #56235 [HACKTOBERFEST 2024] - Git Quiz

### LINKED ISSUE #56235: [HACKTOBERFEST 2024] - Git Quiz
> [!IMPORTANT]
> This issue is part of our 2024 Hacktoberfest initiative. If you are interested in working on this issue, refer to our [top-level tasks](https://github.com/freeCodeCamp/freeCodeCamp/issues/56170) to see if this issue is claimed, or to claim it if it is not.

This issue is to create the Git quiz.

The file you should be working on is found in `/curriculum/challenges/english/25-front-end-development/quiz-git`.

**All quiz questions need to relate to one of these topics:**

- What is version control
- Purpose of/benefits to sites like Github and Gitlab
- Installing and setting up git
- security requirements like SSH/GPG keys
- What is a repository
- How to push to repository
- How to contribute to other people's repositories
- How to create new branch
- What is a pull request
- What does code review process look like
- How do you use github pages to deploy a project
- How to remain in sync with remote
- `.gitignore` and what to include
- Branching strategies
- Merge conflicts and resolution (rebase too)
- One of the interactive courses before this quiz is [located here.](https://github.com/freeCodeCamp/learn-git-by-building-an-sql-reference-object/blob/main/TUTORIAL.md) Any commands or topics covered in that course can be used in the quiz as well. Here's a partial list: status, staged/unstaged changes, adding and committing changes, log/commit history, stashing and popping changes, merging branches, squashing/rewording/dropping commits, reverting commits, resetting, .gitignore

> [!CAUTION]
> Questions which do not fall under these topics will be rejected.

You are welcome to include code blocks in your questions, but please keep them short (four lines or less).

Please do NOT open a pull request until you have completed all questions. Your quiz should have **exactly 20 questions**.

### PR DESCRIPTION
**Pull request by farihaNaqvi**
Checklist:

- [x] I have read and followed the [contribution guidelines](https://contribute.freecodecamp.org).
- [ ] I have read and followed the [how to open a pull request guide](https://contribute.freecodecamp.org/how-to-open-a-pull-request/).
- [x] My pull request targets the `main` branch of freeCodeCamp.
- [x] I have tested these changes either locally on my machine, or GitPod.

Closes #56235

The questions and options were purely created by own with the help of the topics provided and reference of the documentations on those topics.
and most imp no gpt was used in this.
Feel free to ask if there are any other questions.

### CODE REVIEW

**Comment by ilenia-magoni** [comment]
You are joking, this is the 4th PR I need to close from you because _you are not reading and followign the rules_

**Comment by farihaNaqvi** [comment]
now where i am missing? could you please elaborate since i really wanted to add a successful contribution and i really worked hard on this

**Comment by ilenia-magoni** [comment]
The issues for Hacktoberfest, _as explained in the issue itself_, need to be assigned.

**Comment by farihaNaqvi** [comment]
but in the meet he mentioned that it doesn't matter if you are assigned the best PR will be merged that's why i did otherwise i wouldn't have i was waiting for this moment for so long

**Comment by ilenia-magoni** [comment]
That is the usual, yes, then there was all the part about how to contribute to the Hacktoberfest PRs, about that you need to ask to be assigned

**Comment by farihaNaqvi** [comment]
i do not wish to contribute any more i think it was my first and last time. Thank you for your support the last favor i would like to ask if you could remove the spam tag. if you dont its fine for me now. i am totally demotivated now. Thank you once again.

**Comment by naomi-lgbt** [comment]
>  it doesn't matter if you are assigned
I was very specific that this was for the non-hacktoberfest issues, and that the Hacktoberfest Quiz issues need to be assigned to avoid a massive influx of PRs.

**Comment by farihaNaqvi** [comment]
@ilenia-magoni sorry to ask as i am now assign to git quiz should i make new PR request or this can be reopened? i am asking so that i dont make the same mistake again. Please guide me

**Comment by ilenia-magoni** [comment]
@farihaNaqvi open a new PR, you should never make changes on main, you always need a branch. You could also take the chance to read and follow the [how to open a pull request guide](https://contribute.freecodecamp.org/how-to-open-a-pull-request/) linked in the PR checklist as you have not done that yet.

**Pull request closed without merging**
