### PR TITLE
Added solution to Add Document Elements with D3

### PR DESCRIPTION
**Pull request by thecodingaviator**
- [x] I have read [freeCodeCamp's contribution guidelines](https://github.com/freeCodeCamp/freeCodeCamp/blob/master/CONTRIBUTING.md).
- [x] My pull request has a descriptive title (not a vague title like `Update index.md`)
- [x] My pull request targets the `master` branch of freeCodeCamp.
- [x] None of my changes are plagiarized from another source without proper attribution.
- [x] My article does not contain shortened URLs or affiliate links.

If your pull request closes a GitHub issue, replace the XXXXX below with the issue number.

Closes #XXXXX

### CODE REVIEW

**Comment by RandellDawson** [comment]
@raisedadead Can you check out why the build is not triggered?

**Comment by thecodingaviator** [comment]
My account has been flagged by Travis CI for potential abuse, I'm in contact with them, getting it sorted

**Comment by RandellDawson** [comment]
@thecodingaviator Can you think of anything specific why you might be getting flagged for this?

**Comment by thecodingaviator** [comment]
> @thecodingaviator Can you think of anything specific why you might be getting flagged for this?

@RandellDawson Yes, I had changed my username some time ago

**Comment by thecodingaviator** [comment]
Closing since a better solution is added by #27095

**Pull request closed without merging**
