### PR TITLE
changed assertion to check for both classes, in no particular order.

### LINKED ISSUE #6367: order of classes on html element should not matter (in this instance)
Challenge [Add Font Awesome Icons to our Buttons](http://www.freecodecamp.com/challenges/add-font-awesome-icons-to-our-buttons) has an issue.
User Agent is: <code>Mozilla/5.0 (Macintosh; Intel Mac OS X 10_11_3) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/47.0.2526.111 Safari/537.36</code>.
Please describe how to reproduce this issue, and include links to screenshots if possible.

My code:
```html
<link href="http://fonts.googleapis.com/css?family=Lobster" rel="stylesheet" type="text/css">
<style>
  h2 {
    font-family: Lobster, Monospace;
  }

  .thick-green-border {
    border-color: green;
    border-width: 10px;
    border-style: solid;
    border-radius: 50%;
  }
</style>

<div class="container-fluid">
  <div class="row">
    <div class="col-xs-8">
      <h2 class="text-primary text-center">CatPhotoApp</h2>
    </div>
    <div class="col-xs-4">
      <a href="#"><img class="img-responsive thick-green-border" src="https://bit.ly/fcc-relaxing-cat"></a>
    </div>
  </div>
  <img src="http://bit.ly/fcc-running-cats" class="img-responsive">
  <div class="row">
    <div class="col-xs-4">
      <button class="btn btn-block btn-primary"><i class="fa-thumbs-up fa"></i>Like</button>
    </div>
    <div class="col-xs-4">
      <button class="btn btn-block btn-info">Info</button>
    </div>
    <div class="col-xs-4">
      <button class="btn btn-block btn-danger">Delete</button>
    </div>
  </div>
  <p>Things cats <span class="text-danger">love:</span></p>
  <ul>
    <li>cat nip</li>
    <li>laser pointers</li>
    <li>lasagna</li>
  </ul>
  <p>Top 3 things cats hate:</p>
  <ol>
    <li>flea treatment</li>
    <li>thunder</li>
    <li>other cats</li>
  </ol>
  <form action="/submit-cat-photo">
    <label><input type="radio" name="indoor-outdoor"> Indoor</label>
    <label><input type="radio" name="indoor-outdoor"> Outdoor</label>
    <label><input type="checkbox" name="personality"> Loving</label>
    <label><input type="checkbox" name="personality"> Lazy</label>
    <label><input type="checkbox" name="personality"> Crazy</label>
    <input type="text" placeholder="cat photo URL" required>
    <button type="submit">Submit</button>
  </form>
</div>

```

In working thru the above example I noticed that I was not able to validate my input and move to the next challenge if I changed the order of classes for the <i> element. In trying to apply font awesome classes of  "fa" and "fa-thumbs-up", I could not be allowed to enter <i class="fa-thumbs-up fa"> it would only allow <i class="fa fa-thumbs-up">. This could have been very frustrating to someone with less experience, although the sample does show the "fa" class first, this really shouldn't be required for the validation of this challenge, it may confuse those who think it must this way, when they work on future projects.
fa_fa-thumbs-up
fa-thumbs-up_fa

### LINKED ISSUE #6376: Rebuilding cell phone to newer version
So I have seen a feel phone be rebuilt while the person was still using the phone and had no knowledge of it. How us that possible?

### PR DESCRIPTION
**Pull request by ghost**
used element.is('.fa, .fa-thumbs-up') instead of element.hasClass('fa
fa-thumbs-up')
closes #6367

### CODE REVIEW

**Comment by bugron** [comment]
@robjloranger can you explain what is the issue of https://github.com/FreeCodeCamp/FreeCodeCamp/issues/6376 and how to reproduce it so I can understand what's your PR fixing?

**Comment by raisedadead** [comment]
Ahh he just mentioned the wrong issue!

@robjloranger Change the PR description and make it to `closes #6367` instead.

**Comment by robjloranger** [comment]
lol sorry, fixed

**Comment by SaintPeter** [comment]
Closing as this issue has already been resolved by #6439

**Pull request closed without merging**
