### PR TITLE
fix: remove unused className spacer from spacer helper

### PR DESCRIPTION
**Pull request by jsg994**
Checklist:

- [x] I have read [freeCodeCamp's contribution guidelines](https://contribute.freecodecamp.org).
- [x] My pull request has a descriptive title (not a vague title like `Update index.md`)
- [x] My pull request targets the `main` branch of freeCodeCamp.
- [x] I have tested these changes either locally on my machine, or GitPod.

Closes #XXXXX

Was going through repo to get familiar and noticed that the className="spacer" in the Spacer component, isn't actually doing anything.  It is inside an isolated Spacer component and no style is being attributed to it so while it doesn't break anything, the code is more verbose than necessary.

### CODE REVIEW

**Review by Sboonny — APPROVED** [review]
#### :sparkles: :tada: **AWESOME!** :tada: :sparkles:

 Hi @jsg994, thanks for this pull request and for contributing to the code-base for the first time. We are looking forward to more contributions from you in the future.

 Cheers & happy contributing!

**Comment by Sboonny** [comment]
you need to run `npx jest -u` to update the snapshot and remove `spacer` class from it

**Comment by gikf** [comment]
Hey @jsg994 

did you have a chance to take a look at what is still needed here, in the comment above?

**Comment by jsg994** [comment]
ran npx jest -u to remove spacer class from snapshot

**Comment by Nirajn2311** [comment]
Hi @jsg994 , could you run the `npx jest-u` command again as new snapshots from the merge have the class in them.

**Comment by jsg994** [comment]
@Nirajn2311 ran npx jest -u again

**Review by Nirajn2311 — APPROVED** [review]

**Pull request merged**
