### PR TITLE
add releasedOn dates to all new challenges

### PR DESCRIPTION
**Pull request by QuincyLarson**
#### Pre-Submission Checklist

- [x] Your pull request targets the `staging` branch of freeCodeCamp.
- [x] Branch starts with either `fix/`, `feature/`, or `translate/` (e.g. `fix/signin-issue`)
- [x] You have only one commit (if not, [squash](http://forum.freecodecamp.com/t/how-to-squash-multiple-commits-into-one-with-git/13231) them into one commit).
- [x] All new and existing tests pass the command `npm test`. Use `git commit --amend` to amend any fixes.

#### Type of Change

- [x] Small bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds new functionality)
- [ ] Breaking change (fix or feature that would change existing functionality)
- [ ] Add new translation (feature adding new translations)

#### Checklist:

- [x] Tested changes locally.
- [ ] Closes currently open issue (replace XXXX with an issue no): Closes #XXXX

#### Description

This adds a "releasedOn" date so they will get a "New" tag in the challenge map (though this feature has yet to be implemented in our reactified platform).

I also moved some of our retired backend projects into our "take-home practice projects" section so campers can still build them if they're looking for extra practice.

Finally, I fixed the "isRequired" flag for a couple of the intermediate algorithm challenges that were moved over from advanced algorithm challenges (and were previously un-required)

### CODE REVIEW

**Comment by QuincyLarson** [comment]
@systimotic OK - this I was able to re-do this in about 20 minutes with out all the merge conflict baggage. Please take a look at this.

**Comment by raisedadead** [comment]
#### :sparkles: :sparkles: **LGTM.** :sparkles: :sparkles: 

Thanks @QuincyLarson !

**Comment by systimotic** [comment]
Thanks for reviewing @raisedadead!

**Comment by QuincyLarson** [comment]
@raisedadead @systimotic thanks for helping get this merged! :)

**Pull request merged**
