### PR TITLE
Code blocks formatted, qualified POST security statement, added array form data examples

### PR DESCRIPTION
**Pull request by neenjaw**
- [x] I have read [freeCodeCamp's contribution guidelines](https://github.com/freeCodeCamp/freeCodeCamp/blob/master/CONTRIBUTING.md).
- [x] My pull request has a descriptive title (not a vague title like `Update index.md`)
- [x] My pull request targets the `master` branch of freeCodeCamp.
- [x] None of my changes are plagiarized from another source without proper attribution.
- [x] My article does not contain shortened URLs or affiliate links.

If your pull request closes a GitHub issue, replace the XXXXX below with the issue number.

Closes #XXXXX

### CODE REVIEW

**Comment by RandellDawson** [comment]
@neenjaw Would you please use two space indentation as recommended in the styling guide.

Thank you.

**Comment by neenjaw** [comment]
@RandellDawson I think I did two space indentation, as the file in the commit has two space indentation for the codeblocks unless I am misunderstanding what that means..  The original file had no indentation for code blocks.

Can you clarify?

**Comment by RandellDawson** [comment]
@neenjaw You are correct.  I must have been looking at the current version on `master`.

Looks good.

**Comment by RandellDawson** [comment]
Thank you for your contribution to the page! 👍
We're happy to accept these changes, and look forward to future contributions. 🎉

**Comment by neenjaw** [comment]
Thanks @RandellDawson, glad to help!

**Pull request merged**
