### PR TITLE
fix: typo in the new RWD

### PR DESCRIPTION
**Pull request by Sboonny**
Checklist:

- [x] I have read [freeCodeCamp's contribution guidelines](https://contribute.freecodecamp.org).
- [x] My pull request has a descriptive title (not a vague title like `Update index.md`)
- [x] My pull request targets the `main` branch of freeCodeCamp.
- [x] I have tested these changes either locally on my machine, or GitPod.

because the step require the code below, and people may put `main` like this `<h1><main></h1>`

```html
<h1>CatPhotoApp</h1>
    <main>
    <h2>Cat Photos</h2>
    <!-- TODO: Add link to cat photos -->
    <p>Click here to view more cat photos.</p>
    </main>
```

related [forum post](https://forum.freecodecamp.org/t/where-do-i-put-the-main-tag/510299/3)

my change

```diff
- Identify the main section of this page by adding a `<main>` opening tag after the `h1` element, and a `</main>` closing tag after the `p` element.
+ Identify the main section of this page by adding a `<main>` opening tag after the `h1` element closing tag, then add a `</main>` closing tag a the after `p` element closing tag.
```

### CODE REVIEW

**Comment by bbsmooth** [comment]
To be honest, I'm not sure I see a problem with the original instructions and I think I prefer "after" to "below". I think "below" makes the assumption that the tags will always be on a separate line. While this may indeed be a best practice, it is not a requirement. If we want to be crystal clear then we could use "immediately after" instead of just "after". 

I think the issue with the forum post is that perhaps the user did not understand that an element comprises both the opening and closing tag. This was addressed in Step 1. If the user did not understand this then I think it was a good thing that they posted to the forum so it could be explained again. Basically, the system worked.

**Comment by Sboonny** [comment]
>  I'm not sure I see a problem with the original instructions and I think I prefer "after" to "below".

I see your point

> I think the issue with the forum post is that perhaps the user did not understand that an element comprises both the opening and closing tag. This was addressed in Step 1.

This is a user who asked for help. Some don't, I think it's better to mention closing tags in the description. as reminder and to hammer concepts.

**Comment by Sembauke** [comment]
Hey @Sboonny,

Thank you for opening this pull-request, but I must agree with Bruce that this change is not really necessary.
It also breaks the consistency. 

If the user does not understand a challenge, they should open a forum post.

**Comment by Sboonny** [comment]
I am convinced 👌

**Pull request closed without merging**
