### PR TITLE
Fix #34443

### LINKED ISSUE #34443: Vague instructions in Rest Operator challenge
**Describe your problem and how to reproduce it:**
On this challenge, the instructions are vague, I mean what does `work in the same way` even mean? We should make the 'way' clear to the student

**Add a Link to the page with the problem:**
https://learn.freecodecamp.org/javascript-algorithms-and-data-structures/es6/use-the-rest-operator-with-function-parameters

### PR DESCRIPTION
**Pull request by prahaladbelavadi**
This PR fixes and closes #34443. The instructions have been rephrased accordingly.
Thanks @erictleung

- [x] I have read [freeCodeCamp's contribution guidelines](https://github.com/freeCodeCamp/freeCodeCamp/blob/master/CONTRIBUTING.md).
- [x] My pull request has a descriptive title (not a vague title like `Update index.md`)
- [x] My pull request targets the `master` branch of freeCodeCamp.
- [x] None of my changes are plagiarized from another source without proper attribution.
- [x] My article does not contain shortened URLs or affiliate links.

If your pull request closes a GitHub issue, replace the XXXXX below with the issue number.

Closes #34443

### CODE REVIEW

**Review by ezioda004 — COMMENTED** [review]
Hi @prahaladbelavadi,

Thank you for opening this PR.

The issue was already claimed and we try to keep it fair and since the person who claimed the issue already made a PR, I'll have to close this one. 
Next time please review the issue before opening a PR.

Thank you for understanding.
Happy coding.

**Comment by prahaladbelavadi** [comment]
That was my mistake. I got excited and hadn't checked if there was an already existing PR.
I'll do so the next time.
Cheers @ezioda004

**Comment by prahaladbelavadi** [comment]
I've got commits on my fork but I'm also behind the main branch by ~6000 commits.

Do you know how I could discard my two commits and sync up with master ? @ezioda004

**Comment by ojeytonwilliams** [comment]
@prahaladbelavadi I'd start a fresh branch off master and cherry pick the commits from the original branch.

**Comment by prahaladbelavadi** [comment]
Awesome! Thanks @ojeytonwilliams 
I'll try doing that

**Pull request closed without merging**
