### PR TITLE
correct usage of Math.random() to give equal 50/50 results

### PR DESCRIPTION
**Pull request by bherrchen**
- [X ] I have read [freeCodeCamp's contribution guidelines](https://github.com/freeCodeCamp/freeCodeCamp/blob/master/CONTRIBUTING.md).
- [X ] My pull request has a descriptive title (not a vague title like `Update index.md`)
- [X ] My pull request targets the `master` branch of freeCodeCamp.
- [X ] None of my changes are plagiarized from another source without proper attribution.
- [X ] All the files I changed are in the same world language (for example: only English changes, or only Chinese changes, etc.)
- [X ] My changes do not use shortened URLs or affiliate links.

### CODE REVIEW

**Comment by RandellDawson** [comment]
@bherrchen You are correct here, but you will also need to change the Solution in the challenge file so that it reflects the same thing.

**Review by RandellDawson — APPROVED** [review]
LGTM

**Comment by bherrchen** [comment]
And thanks for the tip!

Randell Dawson <notifications@github.com> schrieb am Sa., 13. Apr. 2019,
19:41:

**Review by Manish-Giri — APPROVED** [review]
Hi @bherrchen 

Congrats on your first pull request (PR)! 🎉

Thank you for your contribution to the page! 👍 We're happy to accept these changes and look forward to future contributions. 📝

**Pull request merged**
