### PR TITLE
fix: code element border

### LINKED ISSUE #50034: Wrap border around code elements in the instruction
Mentioned once in issue triage meeting, we can add border to indicate when is the code starts and ends, something like this.

image

image

Some styling can make the border look better.

### PR DESCRIPTION
**Pull request by zavedhussain**
Checklist:

- [x] I have read and followed the [contribution guidelines](https://contribute.freecodecamp.org).
- [x] I have read and followed the [how to open a pull request guide](https://contribute.freecodecamp.org/#/how-to-open-a-pull-request).
- [x] My pull request targets the `main` branch of freeCodeCamp.
- [x] I have tested these changes either locally on my machine, or GitPod.

Closes #50034 

freeCodeCamp-light
freeCodeCamp-dark

### CODE REVIEW

**Comment by zavedhussain** [comment]
Added screenshots for the fix.

**Comment by Sembauke** [comment]
Hey @zavedhussain,

Thank you for making this pull-request, I do have some points I like to address.

We should keep the `background-color` for the night theme, the border should be less thick like 1px or 2px. I would change the border color should be one of the lighter colors.

image

**Review by Sembauke — DISMISSED** [review]
See comment above

**Comment by zavedhussain** [comment]
Thanks @bbsmooth and @Sembauke for the feedback. 


> We should keep the `background-color` for the night theme,

Do you mean to say we should reverse the background to be the night mode colour when on light mode and vice-versa.

**Comment by zavedhussain** [comment]
Attaching screenshots. @Sembauke and @bbsmooth could you please take a look and see if that's ok.
light
dark

**Comment by ahmadabdolsaheb** [comment]
@bbsmooth, do we need borders for the code blocks?
Screenshot 2023-06-15 at 10 27 56 AM

**Comment by Sembauke** [comment]
Hey @zavedhussain,
These changes look better already, how about less top/bottom-padding for code tags?

**Comment by bbsmooth** [comment]
> do we need borders for the code blocks?

Just to clarify, technically we don't need borders for any of this, so the quick answer is no.

But I also think that those code blocks are already clear enough because they separate the code from the rest of the content and thus it is probably overkill to have borders around that code. So feel free to leave the borders off for code blocks.

**Comment by zavedhussain** [comment]
Hi all, I have made the changes according to the feedback received.

- border added to code element 

> how about less top/bottom-padding for code tags?
- reduced top-bottom padding

>So feel free to leave the borders off for code blocks.
- removed border for code blocks



light2
dark2

**Review by ahmaxed — APPROVED** [review]

**Review by naomi-lgbt — APPROVED** [review]

**Comment by zavedhussain** [comment]
Thanks a lot! I am hoping this will be the first of many PR's as I start my open-source journey.

**Pull request merged**
