### PR TITLE
fix: use position: fixed to avoid forcing Cypress

### LINKED ISSUE #39604: Fixed vs absolute Universal nav
As discussed in https://github.com/freeCodeCamp/freeCodeCamp/pull/39580#discussion_r489477744 Cypress has a hard time with absolutely positioned elements.  Also, `fixed` seems more natural for a nav, since it always stays at the top of the viewport (and that seems to be the point of `fixed`).

Is there anything I'm missing or can we move to `position: fixed` and `click({ force: true }) -> click()`?

cc: @ahmadabdolsaheb @Twaha-Rahman

### PR DESCRIPTION
**Pull request by ojeytonwilliams**
Assuming the position change is fine, this closes: #39604

### CODE REVIEW

**Comment by Twaha-Rahman** [comment]
@ojeytonwilliams Almost all the Cypress tests have `force`. Have you checked if changes in all the tests (after removing force) pass? (I think it will but just to be sure)

**Comment by ojeytonwilliams** [comment]
Thanks @Twaha-Rahman I've included the rest.

**Comment by Twaha-Rahman** [comment]
for the Cypress part of things, it LGTM.

**Comment by ahmadabdolsaheb** [comment]
The nav is LGMT.

**Comment by ojeytonwilliams** [comment]
Cool, thanks for the reviews!

**Review by ahmaxed — APPROVED** [review]

**Review by raisedadead — APPROVED** [review]

**Pull request merged**
