### PR TITLE
Removed all empty translations present in the challenges in the seed files

### LINKED ISSUE #12899: Remove all empty translations
Some of the challenges in the seed files have translations with no text. These will cause errors when campers have selected these languages. These look like:

```
      "translations": {
        "de": {
          "description": [],
          "title": ""
        }
      }
```

In this case, we would need to delete
```
        "de": {
          "description": [],
          "title": ""
        }
```
We need to go through and delete all of these empty translations from seed files, and leave the empty `"translation": {}`

### PR DESCRIPTION
**Pull request by envy7**
#### Pre-Submission Checklist

- [x] Your pull request targets the `staging` branch of freeCodeCamp.
- [x] Branch starts with either `fix/`, `feature/`, or `translate/` (e.g. `fix/signin-issue`)
- [x] You have only one commit (if not, [squash](http://forum.freecodecamp.com/t/how-to-squash-multiple-commits-into-one-with-git/13231) them into one commit).
- [x] All new and existing tests pass the command `npm test`. Use `git commit --amend` to amend any fixes.

#### Type of Change

- [x] Small bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds new functionality)
- [ ] Breaking change (fix or feature that would change existing functionality)
- [ ] Add new translation (feature adding new translations)

#### Checklist:

- [x] Tested changes locally.
- [x] Closes currently open issue (replace XXXX with an issue no): Closes #12899 

#### Description

Removed all empty translations i.e the translations with no text present in seed/challenges folder. Changed all code in the form
        
        translations: {
            "de": {
              "description": [],
              "title": ""
            }
        }
        
to
        
        translations: {}

### CODE REVIEW

**Review by raisedadead — APPROVED** [review]
#### :sparkles: :sparkles: **LGTM.** :sparkles: :sparkles: 

Thanks @envy7 

P.S : I have just eye-balled the diff.

**Comment by BerkeleyTrue** [comment]
Please rebase to remove conflicts

**Comment by QuincyLarson** [comment]
@envy7 thanks for doing this. Looking forward to merging this as soon as you've resolved the conflicts. Please let me know if I can be of any help with this.

**Comment by envy7** [comment]
@QuincyLarson I have resolved all the conflicts.

**Review by Greenheart — APPROVED** [review]
@envy7 Thanks for the PR! :smile:

I searched for `translations` in my text editor and stepped through all translation objects to make sure everything that should be empty in fact is so.

I might have missed empty translations if there were more in other files than those changed by this PR. But whatever the case, I think this is ready to merge. 
If there's something missed, it could always be fixed in a future patch. Let's merge this before it gets outdated again :relaxed:

**Comment by envy7** [comment]
Wow, this is my first PR that has been merged in a big organisation, certainly learnt a lot, I hope to keep contributing in the future.

**Comment by Greenheart** [comment]
@envy7 Glad to hear that! :smile: If you want to help out more, there are plenty of open issues [labeled as "Help Wanted"](is:open label:"help wanted" ).

**Pull request merged**
