### PR TITLE
fix(utils): unify common utility scripts

### LINKED ISSUE #18040: "Resume curriculum" link on homepage results in 404 error
#### Describe your problem and - if possible - how to reproduce it

The "Go to the coding curriculum" button on the homepage currently points to this non-existant page:

https://learn.freecodecamp.org/front-end-libraries/react/set-state-with-this.setstate

when it should be pointing here:

https://learn.freecodecamp.org/front-end-libraries/react/set-state-with-this-setstate/

Looks like the `.` in `this.setstate` is not properly being converted to a `-`.

#### Tell us about your browser and operating system

* Browser Name: Chrome
* Browser Version: 68.0.3440.106
* Operating System: MacOS 10.13.6

### PR DESCRIPTION
**Pull request by ojeytonwilliams**
Unify common scripts like dasherize.

### CODE REVIEW

**Review by Seilamuk610 — APPROVED** [review]

**Comment by paulywill** [comment]
@raisedadead @Bouncey Why is the PR still open if labeled blocked?

**Comment by paulywill** [comment]
Opps... wrong button

**Comment by raisedadead** [comment]
Hi @ojeytonwilliams this is change that we are evaluating for inclusion. 

We have merged the learn platform in this main repo. So, it needs to be decided where we need to put up some common utils like such as this file.

We haven't gotten around to this, hence the blocked status.

Thanks.

**Comment by RandellDawson** [comment]
@ValeraS Is this PR still needed, since you made the recent changes to dasherize?  The only other thing I see is changes to `nameify` function.

**Comment by ojeytonwilliams** [comment]
@RandellDawson I think an updated version of this PR is needed, since there are still several instances of `dasherize` and `nameify`.  `dasherize` is a bit tricky because some of which are slightly different!  

Nonetheless, if they can be unified, presumably they should be.  Perhaps in a new common utils directory.

**Comment by raisedadead** [comment]
Are we able to revisit or close this @ojeytonwilliams ?

**Comment by ojeytonwilliams** [comment]
Well, this is stale to the point of useless, but I still think we should DRY out this stuff.

I've taken another look at the three dasherize functions and they all have exactly the same functionality. They're just written slightly differently.

Is there any reason not to just put a single util in the root dir and have the client, server and curriculum all use that?

**Comment by raisedadead** [comment]
> Is there any reason not to just put a single util in the root dir and have the client, server and curriculum all use that?

There is none. Please go ahead with the refactor if you are interested.

**Review by raisedadead — APPROVED** [review]

**Comment by raisedadead** [comment]
Hi @ojeytonwilliams I like this, and going forth we should probably using this structure for our utils. Do you mind throwing some tests in?

**Comment by ojeytonwilliams** [comment]
@raisedadead are these tests what you had in mind?  They made me realise that " a title  " becomes "-a-title--", which doesn't look great.  Perhaps we should trim the strings first.

**Comment by raisedadead** [comment]
These tests are perfect and as you seem to have found a use case where we do need to trim the spaces.

**Review by RandellDawson — APPROVED** [review]
LGTM

**Review by raisedadead — APPROVED** [review]
You sir rock!

**Pull request merged**
