### PR TITLE
A  basic solution to challenge

### PR DESCRIPTION
**Pull request by Samueltommzy**
- [x] I have read [freeCodeCamp's contribution guidelines](https://github.com/freeCodeCamp/freeCodeCamp/blob/master/CONTRIBUTING.md).
- [x] My pull request has a descriptive title (not a vague title like `Update index.md`)
- [x] My pull request targets the `master` branch of freeCodeCamp.
- [x] None of my changes are plagiarized from another source without proper attribution.
- [x] My article does not contain shortened URLs or affiliate links.

If your pull request closes a GitHub issue, replace the XXXXX below with the issue number.

Closes #XXXXX

### CODE REVIEW

**Review by thecodingaviator — DISMISSED** [review]
You can remove the word simplified from basic code solution

**Comment by thecodingaviator** [comment]
I've made a minor change to number the solutions

**Review by thecodingaviator — APPROVED** [review]
The solution has been tested to work

**Comment by thecodingaviator** [comment]
Thanks @Samueltommzy  for contributing to this repo! 👍

We're glad to accept your changes and look forward to more contributions from you!

**Comment by Samueltommzy** [comment]
Thank you

**Pull request merged**
