### PR TITLE
fix(i18n): update Chinese translation of es6

### PR DESCRIPTION
**Pull request by ZhichengChen**
- [x] I have read [freeCodeCamp's contribution guidelines](https://github.com/freeCodeCamp/freeCodeCamp/blob/master/CONTRIBUTING.md).
- [x] My pull request has a descriptive title (not a vague title like `Update index.md`)
- [x] My pull request targets the `master` branch of freeCodeCamp.
- [x] None of my changes are plagiarized from another source without proper attribution.
- [x] All the files I changed are in the same world language (for example: only English changes, or only Chinese changes, etc.)
- [x] My changes do not use shortened URLs or affiliate links.

### CODE REVIEW

**Review by miyaliu666 — APPROVED** [review]

**Review by miyaliu666 — APPROVED** [review]

**Comment by RandellDawson** [comment]
@ZhichengChen I have a question regarding your overall process of working on each section and challenges within a certification.  How often do your sync your `master` branch before creating a new branch off of it to work on translating a section, so that you have the latest changes to the English versions of the challenges you are translating?  Do you sync everything before working on each new challenge or just when you start a new sub section (like the Functional Programming section of the JavaScript Algorithms and Data Structures certification?

The reason I ask, is because I am trying to pin down a date for each sub section to check for any English challenges that have changed since you created the challenge translation.  I want to be able to provide the Chinese team a list of the challenges challenges in the JavaScript Algorithms and Data Structures certification that may need an extra audit to validate the translations are up to date as possible like we did for the Responsive Web Design in issue #38299.  

Once you explain your workflow, I may ask some followup questions pertaining to what the earliest date we should check for each sub section of the JavaScript Algorithms and Data Structures certification.

Thanks in advance.

**Comment by ZhichengChen** [comment]
@RandellDawson Let me describe the workflow of transferring. 

The Chinese team has a translate version of the curriculum in 2018-10, and the main repository has a machine translate version, both of them are too old compared to the online English version.

I have written a bash script to transfer the Chinese version to the markdown, and after I started creating a new translate branch,  I will sync the master code, and compare the script version to the online English version file by file. during that, I found there is some changed of the curriculum, some file was added, some text was changed, some test string was added, and so on. I will handle all of the different, after that, I will copy the new transfer Chinese version to the online English version folder, change the xxx.chinese.md to xxx.english.md, then run locally, finish those challenges make sure there is no problem. then I recovery the test changed, commit the code, the other contributor will do the code review, then approve it.

I'm not sure whether my describe has answered your question. If my description is not clear, feel free to comment me. 

Thank you.

**Comment by RandellDawson** [comment]
@ZhichengChen Please address the numerous merge conflicts present on this PR.

Thank you.

**Comment by ZhichengChen** [comment]
@RandellDawson Could you please give me the permission to resolve this PR's conflicts.

**Comment by ZhichengChen** [comment]
@RandellDawson I have addressed the merge conflicts.

**Pull request merged**
