### PR TITLE
feat(client): add recursion protection

### PR DESCRIPTION
**Pull request by ShaunSHamilton**
Checklist:

- [x] I have read [freeCodeCamp's contribution guidelines](https://contribute.freecodecamp.org).
- [x] My pull request has a descriptive title (not a vague title like `Update index.md`)
- [x] My pull request targets the `main` branch of freeCodeCamp.
- [x] All the files I changed are in the same world language, for example: only English changes, or only Chinese changes, etc.

Related Issue: #36118
Actual PR that closes above: https://github.com/ojeytonwilliams/loop-protect/pull/5

18/02/2021: This PR includes the updated `loop-protect` library, for ease. This will be removed, once PR5 is merged. Then, to test:

1. `cd client/node_modules/@freecodecamp/loop-protect`
2. `npm i`
3. `npm run build`
4.  Now, you may develop the client.

Edit: @ShaunSHamilton I trimmed a few steps, this *should* still work though.

### CODE REVIEW

**Comment by ShaunSHamilton** [comment]
<details>
  <summary> `npm run test:curriculum --superblock='javascript-algorithms-and-data-structures'`</summary>

```
> @freecodecamp/curriculum@0.0.0-next.4 test
> mocha --delay --reporter progress --bail

⠴ Populate tests.
superBlock being tested: javascript-algorithms-and-data-structures



  2839 passing (3m)
```

</details>
<details>
  <summary> `npm run test:curriculum --superblock='front-end-libraries'`</summary>

```
> @freecodecamp/curriculum@0.0.0-next.4 test
> mocha --delay --reporter progress --bail

⠼ Populate tests.
superBlock being tested: front-end-libraries



  1187 passing (39s)
```

_Fun fact: If you type `frontend-libraries` instead, the tests still run correctly_

</details>
<details>
  <summary> `npm run test:curriculum --superblock='data-visualization'`</summary>

```
> @freecodecamp/curriculum@0.0.0-next.4 test
> mocha --delay --reporter progress --bail

⠼ Populate tests.
superBlock being tested: data-visualization



  416 passing (8s)
```

</details>

Currently, an issue has been uncovered likely unrelated to the scope of this PR. This is causing the tests to not all be run, if the `timeout` is set sufficiently high. Oliver pointed out it is likely to do with: 
>https://boneskull.com/mocha-v4-nears-release/#mochawontforceexit
I think this is what's happening. That is to say, some tests never complete.

**Comment by ShaunSHamilton** [comment]
@ojeytonwilliams I would appreciate help looking into why `loop-protect` cannot be built:
```bash
failed Building production JavaScript and CSS bundles - 368.507s
error Generating JavaScript bundles failed

Can't resolve '@freecodecamp/loop-protect' in '/home/runner/work/freeCodeCamp/freeCodeCamp/client/src/templates/Challenges/rechallenge'
```

I assume this relates to my PR not being on your branch, but cannot think why the build is not done automagically.

**Comment by ojeytonwilliams** [comment]
I think it's just that it's designed to be published as a package, during which `npm run build` should get invoked automatically.  Getting it from the tarball doesn't do any of that - you just get the raw files.

It shouldn't be a problem for QA, though, we just need to remember to `npm ci && npm run build` inside the `@freecodecamp/loop-protect` dir.

**Comment by ojeytonwilliams** [comment]
After following those steps I got:

image

where the decoded error is:

> DisplayMessages(...): Nothing was returned from render. This usually means a return statement is missing. Or, to render nothing, return null.

i.e. loop-protect kicked in and the render never happened.

That particular challenge is inefficient - it uses async tests needlessly.  Unless we can make `loop-protect` less computationally intensive (and I can't see how), we'll need to improve these tests.

As far as I can see, it's only this one, "Manage State Locally First", that's a problem, so hopefully that's all that needs fixing.

**Comment by ShaunSHamilton** [comment]
@ojeytonwilliams I am at a bit of a loss with what more to do with this. I still have been unable to run all the tests at the same time without Mocha just derping and forgetting to finish the tests - leaving some pending.

I can pass all of the superblocks individually.

**Comment by ojeytonwilliams** [comment]
Weird.  Which commit does the pending thing for you?  Could you drop a copy of the output in here, so I know for sure what to expect?

**Comment by ShaunSHamilton** [comment]
> Which commit does the pending thing for you?

@ojeytonwilliams The latest commit:
```console
> @freecodecamp/curriculum@0.0.0-next.4 test /workspace/freeCodeCamp/curriculum
> mocha --delay --reporter progress --bail

⠼ Populate tests.


  12148 passing (12m)
  534 pending
```

**Comment by ojeytonwilliams** [comment]
That's what I see on `main` when it's working, though.  Is it continuing to spin after showing those messages?

**Comment by ShaunSHamilton** [comment]
> Is it continuing to spin after showing those messages?

No. That is the tests done.

Just a reminder: This has been the issue, for a long time. So, other than some A/B testing, I cannot see how we can evaluate this package.

**Comment by raisedadead** [comment]
Cleaning things up. Added this to your Trello, so that you can come back and resurrect this when you are ready.

**Pull request closed without merging**
