### PR TITLE
refactor: justify readme text

### PR DESCRIPTION
**Pull request by caioreius**
Checklist:

- [ ] I have read and followed the [contribution guidelines](https://contribute.freecodecamp.org).
- [x] I have read and followed the [how to open a pull request guide](https://contribute.freecodecamp.org/#/how-to-open-a-pull-request).
- [x] My pull request targets the `main` branch of freeCodeCamp.
- [ ] I have tested these changes either locally on my machine, or GitPod.

Closes #XXXXX

### CODE REVIEW

**Comment by Sboonny** [comment]
Hey @caioreius

Thank you for opening this pull request.

This is a standard message notifying you that we've reviewed your pull request and have decided not to merge it. We would welcome future pull requests from you.

Thank you and happy coding.

**Comment by Sboonny** [comment]
You haven't tested it locally

image

in the guideline, there is a mention of opening PRs like this, and what is the process that you should take.

There is no issue discussing the changes, and description in the PR itself discussing the need for the change.

**Comment by caioreius** [comment]
@Sboonny, i fixed. can I give a new Pull?

**Comment by Sboonny** [comment]
Discuss it in issue first before opening new PR, other maintainers won't see it in a good light, because of your previous PRs.

image

**Comment by bbsmooth** [comment]
@caioreius 

> Could you please explain to me why the pull request cannot be accepted?

The `align` attribute should not be used on the `p` element (technically, the specs don't allow it). If you want to style text in a `p` element it should be done with CSS. Also, it is considered bad for accessibility to align text in a justified manner, so unless there is a very good reason to do so then it should not be done.

**Comment by caioreius** [comment]
@bbsmooth All right, I understood, I thought the text would be better to understand.
Thanks

**Comment by caioreius** [comment]
@bbsmooth If you look, the changes look very good in the document, I think it looks better to visualize, but that's ok, you know what you do ..

**Comment by bbsmooth** [comment]
@caioreius This is not my personal opinion. It is documented in a WCAG success criterion. I will post more info in the issue you just opened.

**Pull request closed without merging**
