### PR TITLE
fix(about): Open links in new tab

### LINKED ISSUE #13780: [beta] Clicking on "About" in the menu opens the map
#### Issue Description

In any page, clicking Community > About in the navigation bar opens the map page instead. After a few seconds a message "Oops! Something went wrong" appears, but no message is shown in the console.

#### Browser Information

* Browser Name, Version: 56.0.2924.87 (64-bit)
* Operating System: Windows 7, 64bit
* Mobile, Desktop, or Tablet: Desktop

### PR DESCRIPTION
**Pull request by raisedadead**
This updates the links to open in new tab (synonymous to the current behavior in production)

Closes #13780

### CODE REVIEW

**Comment by raisedadead** [comment]
I feel that instead of throwing off error messages for the about page, it's better UX to keep the behavior same as that of the current production site.

If this okay, then we should also create a separate issue for handling static pages errors (that are being linked relatively), which should be handled by a more generic error catching logic.

**Comment by dhcodes** [comment]
I think this may be taken care of by this PR: https://github.com/freeCodeCamp/freeCodeCamp/pull/15508

Yours was first, though... Thoughts?

**Comment by raisedadead** [comment]
@dhcodes Sure, not a problem, please close this PR and add the issue (#13780) that this PR addresses to the one that you have opened so that it is tracked and closed, with yours?

Thanks a lot for letting me know.

**Comment by dhcodes** [comment]
Done @raisedadead . Closing this one.

**Pull request closed without merging**
