### PR TITLE
Translate discerption to Arabic

### PR DESCRIPTION
**Pull request by aseelsky**
- [x] I have read [freeCodeCamp's contribution guidelines](https://github.com/freeCodeCamp/freeCodeCamp/blob/master/CONTRIBUTING.md).
- [x] My pull request has a descriptive title (not a vague title like `Update index.md`)
- [x] My pull request targets the `master` branch of freeCodeCamp.
- [x] None of my changes are plagiarized from another source without proper attribution.
- [x] All the files I changed are in the same world language (for example: only English changes, or only Chinese changes, etc.)
- [x] My changes do not use shortened URLs or affiliate links.

### CODE REVIEW

**Comment by RandellDawson** [comment]
Thank you for opening this pull request.

This is a standard message notifying you that we’ve reviewed your pull request and have decided not to merge it. We would welcome future pull requests from you.

Thank you and happy coding.

**Comment by RandellDawson** [comment]
@aseelsky To be considered for merging, please update all applicable sections of the challenge from the current English version to Arabic.

Thank you.

**Comment by aseelsky** [comment]
OK, I will update the commit.

**Review by aseelsky — COMMENTED** [review]
Update translation

**Comment by ahmadabdolsaheb** [comment]
Congratulations @aseelsky on your first contribution.

**Pull request merged**
