### PR TITLE
Update gif showing how to start FreeCodeCamp

### PR DESCRIPTION
**Pull request by vibegui**
To reflect recent UI changes in GitHub (and star count!)
Fixes https://github.com/FreeCodeCamp/FreeCodeCamp/issues/5527

### CODE REVIEW

**Comment by bouraimad** [comment]
hello world

**Comment by bouraimad** [comment]
i am imad bouramana from morroco . i join freecode for studying  web developer

**Comment by ltegman** [comment]
@bouraimad Welcome to the community! However, Github Pull Requests and issues are not a place for casual conversation. Please join our [Gitter Channel](gitter.im/FreeCodeCamp/FreeCodeCamp) if you would like to introduce yourself to our community.

**Comment by QuincyLarson** [comment]
@firstdoit Thanks for recording this gif. I actually fixed this a couple days ago but there was a  miscommunication (I didn't see your outstanding issue).

I've closed the issue.

Good work on the gif. We could definitely use your help creating some wiki entries if you're interested in helping with that. Gifs are a great way to walk people through workflows, and I'm glad you've figured out a good way to record them.

**Comment by firstdoit** [comment]
@QuincyLarson cool :) but... the current gif still shows the old interface? http://i.imgur.com/pYk0wOk.gif

**Pull request closed without merging**
