### PR TITLE
fix(curriculum): bracket notation regex

### LINKED ISSUE #43058: Allow bracket notation in Implementation of Social Authentication II
```js
assert.match(
  data,
  /process.env.GITHUB_CLIENT_SECRET/g,
  'You should use process.env.GITHUB_CLIENT_SECRET'
);
assert.match(
  data,
  /process.env.GITHUB_CLIENT_ID/g,
  'You should use process.env.GITHUB_CLIENT_ID'
);
```

Challenge: https://github.com/freeCodeCamp/freeCodeCamp/blob/main/curriculum/challenges/english/06-quality-assurance/advanced-node-and-express/implementation-of-social-authentication-ii.md

Forum post: https://forum.freecodecamp.org/t/couldnt-pass-the-test-github-strategy-should-be-setup-correctly-thus-far/471350

### PR DESCRIPTION
**Pull request by awu43**
Checklist:

- [x] I have read [freeCodeCamp's contribution guidelines](https://contribute.freecodecamp.org).
- [x] My pull request has a descriptive title (not a vague title like `Update index.md`)
- [x] My pull request targets the `main` branch of freeCodeCamp.
- [x] I have tested these changes either locally on my machine, or GitPod.

Closes #43058

Implementation borrowed from #42881. ~~Not tested since attempting to run the tests on GitPod throws CORS errors. How should this be tested?~~

### CODE REVIEW

**Comment by gikf** [comment]
Hey @awu43 cors errors suggest, to test from Gitpod, it would be needed to adjust code of the running challenge to allow testing from Gitpod, as in - change it on the replit or other place where challenge is deployed and running. In this case I believe it would this line https://github.com/freeCodeCamp/boilerplate-advancednode/blob/a7c60ac9258452c45821120e57a62827bb5b9d03/freeCodeCamp/fcctesting.js#L40

**Comment by awu43** [comment]
@gikf That seems like the solution, but forking the problematic submission doesn't include secrets/env and I haven't done this part of the curriculum so I don't have access to a complete solution to run.

**Comment by gikf** [comment]
@awu43 I've forked it, added needed secrets and added Gitpod to allowed hosts (although it wasn't giving me any issues without that) - https://boilerplate-advancednode-4.sanityto.repl.co

**Comment by awu43** [comment]
Thanks for that. All three tests are now passing as they should.

**Review by gikf — APPROVED** [review]
LGTM :+1:

**Review by Sembauke — APPROVED** [review]

**Pull request merged**
