### PR TITLE
chore(ui): removed unused default-avatar classes

### LINKED ISSUE #55067: Remove unused avatar class
## Description

The `default-avatar` class is not used and can be removed.

## Changes needed

Remove `default-avatar` class from:
- https://github.com/freeCodeCamp/freeCodeCamp/blob/ebf8d8fda9c48e3d77ae3779f05d08c70395d175/client/src/components/helpers/avatar-renderer.tsx#L47
- https://github.com/freeCodeCamp/freeCodeCamp/blob/ebf8d8fda9c48e3d77ae3779f05d08c70395d175/client/src/assets/icons/default-avatar.tsx#L11

### PR DESCRIPTION
**Pull request by LuG-r**
Checklist:

- [x] I have read and followed the [contribution guidelines](https://contribute.freecodecamp.org).
- [x] I have read and followed the [how to open a pull request guide](https://contribute.freecodecamp.org/#/how-to-open-a-pull-request).
- [x] My pull request targets the `main` branch of freeCodeCamp.
- [x] I have tested these changes either locally on my machine, or GitPod.

Closes #55067

### CODE REVIEW

**Review by naomi-lgbt — CHANGES_REQUESTED** [review]
The snapshot will need to be updated too - you should be able to do this by running `pnpm test-client -u` and committing the updated file.

**Comment by LuG-r** [comment]
@naomi-lgbt Thanks for your help, I've committed the updated snapshot file.

**Review by naomi-lgbt — APPROVED** [review]
Awesome!

**Review by a2937 — APPROVED** [review]
Looks Good To Me! 👍

**Pull request merged**
