### PR TITLE
refactor : curriculum server

### PR DESCRIPTION
**Pull request by mayankkamboj47**
Checklist:

- [x] I have read and followed the [contribution guidelines](https://contribute.freecodecamp.org).
- [x] I have read and followed the [how to open a pull request guide](https://contribute.freecodecamp.org/#/how-to-open-a-pull-request).
- [x] My pull request targets the `main` branch of freeCodeCamp.
- [x] I have tested these changes either locally on my machine, or GitPod.

Refactor cirriculum server code to enhance readability

### CODE REVIEW

**Review by ojeytonwilliams — CHANGES_REQUESTED** [review]
Hi @mayankkamboj47, thanks for taking the time to clean up the code - it's always appreciated.

If you want to contribute further, please take a look at other parts of the code base. Reason being this is an old prototype and won't be actively developed any time soon. Not this year, at least.

**Comment by mayankkamboj47** [comment]
Hey william :) Thanks for replying so kindly, it made my otherwise tough day a lot better. And thanks for the feedback.
Does the functional code only rule apply to the entire codebase ? I'm thinking of contributing more code changes. 
Also, having looked at your suggestions for changes, what do you think about
```
Object.fromEntries(
     Object.keys(curriculum).map(r=>[r.replace(/\//g, '-'), curriculum[r])
```
This keeps it functional, but also such that it can be read at a quick glance

**Comment by naomi-lgbt** [comment]
I would say that the existing code is readable. I think that latest example is treading into the code golf territory, and is actually less readable AND less maintainable.

**Comment by mayankkamboj47** [comment]
@naomi-lgbt  Code golf is only bad when it convolutes the code just to shrink it right ? I do not know why you think what you do because you give no reason. Perhaps you'd break the code into smaller chunks, or maybe you object (pun not intended) to the use of Object.fromEntries. 

For a new contributor, it can be intimidating to have a long term contributor call one's code less readable, less maintainable, and code golf without really saying why. You do realise that you should use these adjectives responsibly ? Newcomers are most likely to contribute
minor typos and refactorings, and they're also the ones most likely to be discouraged by someone they see as more experienced and frankly better, giving untransparent feedback. 

This is my second time opening this PR. Most contributors would give up after the first, which
was closed with a camperbot message you edited, saying that my PR didn't follow the contribution instructions. The edit you made is sad.
Besides, if a reviewer had the time to manually edit the camperbot message, they also had time for a quick reply, any contributor would think. What am I to make of such petty behaviour that you're still persisting on ? This isn't even a significant contribution.

**Comment by ojeytonwilliams** [comment]
> Hey Oliver :) Thanks for replying so kindly, it made my otherwise tough day a lot better.

Not at all, I'm always happy when someone takes the time to improve my code. So, thanks again for that.

> Does the functional code only rule apply to the entire codebase ? I'm thinking of contributing more code changes.

No, it's not a rule, it's just my preference. But it's always a balancing act between various concerns, so, no, it's not a rule we enforce.

Anyways, I think Naomi was just pointing out that there comes a point where brevity comes at the expense of readability, not that you were trying to make it less readable. It's obvious that you intended to improve the code. However, this isn't production code (and may never become production code), and improving it is a very low priority from a maintainer perspective.

With that in mind, if you're happy to make the suggested change, I think we can merge this and move on.

**Comment by mayankkamboj47** [comment]
Changed ! But I see that the linting failed now. Should I fix it from my end ?

**Comment by ojeytonwilliams** [comment]
> Changed ! But I see that the linting failed now. Should I fix it from my end ?

Thanks :) Don't worry about the linting. It failed because the first commit had an unused variable, but the second commit made use of it. If you look at the current checks, you can see that the linting was successful.

**Review by ojeytonwilliams — APPROVED** [review]
LGTM :+1:

**Review by ahmaxed — APPROVED** [review]

**Pull request merged**
