### PR TITLE
feat(interview-prep): Adding Rosetta Code problems

### PR DESCRIPTION
**Pull request by NitronR**
- [ ] I have read [freeCodeCamp's contribution guidelines](https://github.com/freeCodeCamp/freeCodeCamp/blob/master/CONTRIBUTING.md).
- [ ] My pull request has a descriptive title (not a vague title like `Update index.md`)
- [ ] My pull request targets the `master` branch of freeCodeCamp.
- [ ] None of my changes are plagiarized from another source without proper attribution.
- [ ] My article does not contain shortened URLs or affiliate links.

Closes #XXXXX

### CODE REVIEW

**Comment by NitronR** [comment]
@scissorsneedfoodtoo Added some Rosetta Code problems. Can you please review them? I have added white-space for readability this time, please tell me if it is correct.

**Comment by scissorsneedfoodtoo** [comment]
Awesome! Everything looks great at first glance. Thank you for adding the white-space here. I'll check these problems out ASAP.

**Comment by scissorsneedfoodtoo** [comment]
Everything LGTM! Thanks again for all of your hard work here, @NitronR :+1: :+1:

**Comment by NitronR** [comment]
@scissorsneedfoodtoo Thank you for your time on reviewing and cleaning up these problems. I will clean up the <p> tags for the next set of problems.

**Comment by ezioda004** [comment]
@scissorsneedfoodtoo Do we need bubble sort, insertion sort, merge sort, quick sort here? We already have those challenges for those in the "coding interview/algorithms" section.

**Comment by scissorsneedfoodtoo** [comment]
@NitronR, no problem! It was easy to just find and replace those. Doing the pre sections is much easier than before, too, so I'll have to go back through some of the older ports and untangle those bits.

@ezioda004, you do bring up a good point. It would be less confusing to have one challenge for each type of sort. It's my understanding that one of the things we're trying to do with these ports is to preserve the different challenges and descriptions. I figure it doesn't hurt to have some repetition if it means having a copy of the Rosetta code descriptions and examples here. If others decide to go with the ones in the coding interview/algorithms section, though, I could see removing them from this section.

**Comment by ezioda004** [comment]
@scissorsneedfoodtoo My take on this is that the challenges in the "coding interview/algorithms" are the classical sorting algorithms, which are taught in colleges and generally asked in interviews cause they expect the candidate to atleast know these 5 sorting algorithms. 

That being said, I like the idea of having all the sorting algorithms in one place, but on the other hand repetition feels excessive.

Maybe we could add a note saying to check these challenges out at the beginning/end of one of these sorting algorithms and remove the duplicate ones?

Another option would be to remove sorting algorithms from "coding interview/algorithms" so we can have all of them in Rosetta section. The downside of that would be, Rosetta section is already huge so these classic algorithms will be hidden.

**Comment by scissorsneedfoodtoo** [comment]
@ezioda004, sorry for the delay!

Those are all good suggestions. I could see having a note in the "coding interview/algorithms" challenges that reference the ones here, and vice versa. Or even just a small note reminding the users that these challenges are all optional and they could skip any duplicates they come across.

If it comes down to it, I think it would be better to remove the duplicate sorting challenges from the Rosetta Code section here. They're newer and aren't on the live site yet, so it's unlikely that anyone will notice that they've been removed.

I can open an issue so we can get some feedback from other contributors about what to do here.

**Comment by ezioda004** [comment]
@scissorsneedfoodtoo Yep opening an issue and tracking there sounds good to me!

**Pull request merged**
