### PR TITLE
Adds test for class selector in Prioritize One Style Over Another

### LINKED ISSUE #6432: HTML & CSS Waypoint: "prioritize-one-style-over-another" can be fooled
When I couldn't figure out what to do, I went in and changed the body color to pink and hit submit to see if that was the right answer.  It gave me the "congrats" and moved me forward because it met both criteria, but then upon seeing the code in the next waypoint I realized that wasn't right and I had just "fooled" the test. Here's the code I entered:  
```
<style>
  body {
    background-color: black;
    font-family: Monospace;
    color: pink;
  }
  pink-text {
     color: pink;
  }
</style>
```

### PR DESCRIPTION
**Pull request by alistermada**
Adds test to make sure `.pink-text` class selector is declared with its color set to pink.
closes #6432

### CODE REVIEW

**Comment by SaintPeter** [comment]
One more space detection needed:
```css
  .pink-text      {
    color    : pink  ;  
  }
```

The above code should be valid CSS and pass - we recently had a similar change required on another css regex.  More `\s*`, I guess.

**Comment by alistermada** [comment]
Hmm... I could've sworn I had that `\s*` in there. Thanks for catching that. Fixed.

**Comment by SaintPeter** [comment]
This still fails:
```css
  .pink-text {
    color:  pink      ;
  }
```

Looks like it's the spaces after the pink but before the semi-colon.

Are you testing these locally, because you ought to be able to drop my code in place and test it.

**Comment by alistermada** [comment]
@SaintPeter  Oh right, forgot to test using your code. I only tested for a space before the colon.

Fixed (hopefully). Tested locally.

**Comment by SaintPeter** [comment]
Like Buddah!  :100:

**Pull request merged**
