### PR TITLE
Change test method from string.test(regex) to regex.test(string)

### PR DESCRIPTION
**Pull request by maxjunerd**
- [x] I have read [freeCodeCamp's contribution guidelines](https://github.com/freeCodeCamp/freeCodeCamp/blob/master/CONTRIBUTING.md).
- [x] My pull request has a descriptive title (not a vague title like `Update index.md`)
- [x] My pull request targets the `master` branch of freeCodeCamp.
- [x] None of my changes are plagiarized from another source without proper attribution.
- [x] All the files I changed are in the same world language (for example: only English changes, or only Chinese changes, etc.)
- [x] My changes do not use shortened URLs or affiliate links.

Change how test method is being used from string.test(regex) to regex.test(string)

Original
original

Editted
editted

### CODE REVIEW

**Comment by RandellDawson** [comment]
@maxjunerd Why make this change?

**Comment by maxjunerd** [comment]
Test modthod must be called by regex. It will throw errors if you call test method by string.

Test method being called by string
Screen Shot 2019-10-23 at 12 09 31

Test method being called by regex
Screen Shot 2019-10-23 at 12 07 13

**Review by RandellDawson — APPROVED** [review]
@maxjunerd You are absolutely correct.  Not sure why I questioned your change.

**Review by moT01 — APPROVED** [review]
LGTM @maxjunerd 🎉 Thanks for fixing this and congratulations on your first contribution to freeCodeCamp 🎉

**Pull request merged**
