### PR TITLE
[WIP] fix: request should hit update email API

### LINKED ISSUE #16145: [beta] request from react view is not hitting the update email API

### PR DESCRIPTION
**Pull request by raisedadead**
Closes #16145

### CODE REVIEW

**Comment by raisedadead** [comment]
Ah, my initial thought was that this is something with the backend. But looks like this is to do with the redux actions at the client side, of which I have no idea.

@BerkeleyTrue I guess, you will have to take a look at this. Apologies.

**Comment by raisedadead** [comment]
I had started some work on [on my fork here](https://github.com/freeCodeCamp/freeCodeCamp/compare/staging...raisedadead:fix/update-email-request)
But, I lack the understanding of redux, and Observables, to get this working.

**Comment by Zou1738** [comment]
Stop

**Comment by texas2010** [comment]
@Zou1738 
looks like you may have accidentally subscribed to all notifications for the [FreeCodeCamp](https://github.com/FreeCodeCamp/FreeCodeCamp) repository. To stop receiving notifications please visit the [subscriptions page](https://github.com/FreeCodeCamp/FreeCodeCamp/subscription) and select "Not watching". Additionally, you can visit the [GitHub Help page on managing notification delivery methods](https://help.github.com/articles/managing-notification-delivery-methods/) for more help.

We are sorry for your inconvenience!

**Pull request closed without merging**
