### PR TITLE
fix(curriculum): intro for travel agency page

### LINKED ISSUE #56862: [ Full Stack Cert ] - update description for travel agency page
Let’s update the intro text to the following:

```md
        "intro": [
          "For this lab, you will review working with HTML fundamentals by creating a web page for a travel agency. This lab will give you an opportunity to review working with images, the <code>figure</code> element, the <code>figcaption</code> element, the <code>anchor</code> element and more."
        ]

```

Here is the file you need to edit:

https://github.com/freeCodeCamp/freeCodeCamp/blob/main/client/i18n/locales/english/intro.json#L1721-L1726

### PR DESCRIPTION
**Pull request by charu1110**
Checklist:

- [x] I have read and followed the [contribution guidelines](https://contribute.freecodecamp.org).
- [x] I have read and followed the [how to open a pull request guide](https://contribute.freecodecamp.org/how-to-open-a-pull-request/).
- [x] My pull request targets the `main` branch of freeCodeCamp.
- [x] I have tested these changes either locally on my machine, or GitPod.

Closes #56862

### CODE REVIEW

**Comment by charu1110** [comment]
updated the intro for travel agency page . please merge my pull request .

**Comment by ilenia-magoni** [comment]
> * I have read and followed the [how to open a pull request guide](https://contribute.freecodecamp.org/how-to-open-a-pull-request/).

you have not followed this guide, we can't accept the PR as is. Please update the title of the PR.

**Comment by charu1110** [comment]
Updated the title . Please  review it once .

**Review by majestic-owl448 — APPROVED** [review]

**Review by charu1110 — COMMENTED** [review]
approved

**Comment by ilenia-magoni** [comment]
@charu1110 you can't approve your own PR, you will need to wait for a maintainer to make the second approval

**Review by gikf — APPROVED** [review]

**Comment by gikf** [comment]
Hi @charu1110. Congrats on your first pull request (PR)! 🎉

Thank you for your contribution to the page! 👍
We are happy to accept these changes and look forward to future contributions. 📝

**Pull request merged**
