### PR TITLE
Change instructions from import to fork

### PR DESCRIPTION
**Pull request by pkdvalis**
Instructions to import these projects on replit no longer seem to work. I've had to look up the freecodecamp account on replit, search for the corect project and fork it to work from the boilerplates.

Checklist:

- [x] I have read and followed the [contribution guidelines](https://contribute.freecodecamp.org).
- [x] I have read and followed the [how to open a pull request guide](https://contribute.freecodecamp.org/#/how-to-open-a-pull-request).
- [x] My pull request targets the `main` branch of freeCodeCamp.
- [x] I have tested these changes either locally on my machine, or GitPod.

Closes #XXXXX

Fix to an error I've received for all of the Scientific Computing with Python challenges. If this is good, I will update each of them. 
Error: "This repository could not be accessed, try again later"

### CODE REVIEW

**Comment by moT01** [comment]
I'm not having any issues importing a project.

<details>
    <summary>I click the link on one of the python projects, and it takes me to this screen:</summary>
    
</details>

<details>
    <summary>Then it loads up:</summary>
    
</details>

And I follow the existing instructions to "Select `Use run command` and click the `Done` button."

So I don't think this change is needed at first glance. I don't see any options to "fork" the repo either - you can only import it (which is maybe technically a fork - but it doesn't say fork, it says import). Are you still seeing this problem @pkdvalis? It's possible that replit or GitHub had an intermittent issue at the time you tried to import the repo.

**Comment by gikf** [comment]
I saw it mentioned a couple of times on the forums, but I also have not encountered it myself.

**Comment by gikf** [comment]
To be honest I wouldn't replace it completely, personally. No need for additional things be in sync with repository is a big advantage.

I was going to suggest adding it as an alternative, but that wouldn't make sense without making sure things are always in sync. Instead I had idea about linking to forums with post describing how to clone boilerplate repository to a freshly started replit via shell commands.

**Comment by pkdvalis** [comment]
> I saw it mentioned a couple of times on the forums, but I also have not encountered it myself.

I still get this error but now I see it's related to this: I need to click "Connect Github to import your private repos." first and authorize github on replit. Forking it was just my workaround at the time.

Thanks for looking at this issue, I'll try to close it and add this solution to the forum if it's not already there.

**Pull request closed without merging**
