### PR TITLE
fix(styles): apply conventional styles

### PR DESCRIPTION
**Pull request by raisedadead**
Updates styling for the:

- Footer in day and night mode: Makes it a little more subtle than current
- Map in night mode.

### CODE REVIEW

**Comment by raisedadead** [comment]
Hey @ahmadabdolsaheb can you check this? I thought it would be a bit nicer this way.

**Comment by ahmadabdolsaheb** [comment]
The changes looking great. I really liked the light green on night mode.
I was wondering, are we bound to using the colors in the FCC style guide? because we could really use more shades of gray in the UI :)
Not sure if it is intentional but the grays are not neutral they have some blue in them, and was wondering if the progress numbers should be light green as well.
 
screen shot 2019-02-23 at 5 25 05 pm
screen shot 2019-02-23 at 5 42 36 pm
screen shot 2019-02-23 at 5 43 03 pm

**Comment by raisedadead** [comment]
> ...the progress numbers should be light green as well.

I missed it. Thanks. Will fix.

**Comment by raisedadead** [comment]
> I was wondering, are we bound to using the colors in the FCC style guide?

The style guide is accurate in terms of having a11y compliance for a day mode. 

I don't think we thought about night colors then. We can experiment a little bit on that, and possibly have a scheme that we can use platform wide.

At the minute, we should focus on polishing the site.

Eventually we will have a dedicates css component repo, that unifies all the interfaces.

**Comment by raisedadead** [comment]
Forgot to mention, I generated the colors to be a11y compliant using chrome's dev tools. You can learn more about it here: https://developers.google.com/web/updates/2018/01/devtools#contrast

**Pull request merged**
