### PR TITLE
Map fixes

### LINKED ISSUE #6177: Side map should automatically scroll down to current challenge

### PR DESCRIPTION
**Pull request by QuincyLarson**
- Adds Expand/Collapse All
- Adds Carat animation
- Defaults map to open
- Move scripts to their own place in `main.js`
- Remove the "view this map in fullscreeen" button on fullscreen

Closes #6177

### CODE REVIEW

**Comment by QuincyLarson** [comment]
This almost works, but still needs a bit of help with the Caret functionality (which I've commented out - the expand-all / collapse-all functionality works.

**Comment by SaintPeter** [comment]
This one is ready for QA, merged in @bugron's fixes.

Tested Locally.

**Comment by SaintPeter** [comment]
Blocked pending PR from @bugron to add auto-scroll to current challenge.

**Comment by SaintPeter** [comment]
Ready for QA

**Comment by SaintPeter** [comment]
Thank @AkiraLaine for QAing

**Pull request merged**
