### PR TITLE
Corrected the grammatical mistakes.

### LINKED ISSUE #40470: there is a spelling error in this lesson "Count Backwards With a For Loop"
**Describe your problem and how to reproduce it:**
here in this lesson we this explanation: In order to count backwards by twos, we'll need to change our initialization, condition, and final-expression.
 backwards should change into backward and twos should change into two. 

**Add a Link to the page with the problem:**

https://www.freecodecamp.org/learn/javascript-algorithms-and-data-structures/basic-javascript/count-backwards-with-a-for-loop

**Tell us about your browser and operating system:**
* Browser Name: chrome 
* Browser Version: 
* Operating System: Windows 10

**If possible, add a screenshot here (you can drag and drop, png, jpg, gif, etc. in this box):**

### PR DESCRIPTION
**Pull request by rishabhlingam**
Checklist:

- [x] I have read [freeCodeCamp's contribution guidelines](https://contribute.freecodecamp.org).
- [x] My pull request has a descriptive title (not a vague title like `Update index.md`)
- [x] My pull request targets the `master` branch of freeCodeCamp.
- [x] All the files I changed are in the same world language, for example: only English changes, or only Chinese changes, etc.

Closes #40470

### CODE REVIEW

**Review by raisedadead — COMMENTED** [review]
The grammar is correct (we err on the side of using American english), I do not think we need this change.

I will let some else weigh in though.

**Comment by rishabhlingam** [comment]
> The grammar is correct (we err on the side of using American english), I do not think we need this change.
> 
> I will let some else weigh in though.

**Comment by rishabhlingam** [comment]
> The grammar is correct (we err on the side of using American english), I do not think we need this change.
> 
> I will let some else weigh in though.

Yea I know.. it was just to get familiar with Github.
Thanks for pointing out though :)

**Comment by raisedadead** [comment]
> Yea I know.. it was just to get familiar with Github.

I would recommend you follow the documentation for GitHub at https://docs.github.com/en instead. You should use your own repos for this :), and respect the time and efforts for moderators on this repo.

Thanks for your understanding, and welcome to open source.

**Pull request closed without merging**
