### PR TITLE
fix(learn) - add a comment dictionary 

### PR DESCRIPTION
**Pull request by RandellDawson**
Checklist:

- [x] I have read [freeCodeCamp's contribution guidelines](https://contribute.freecodecamp.org).
- [x] My pull request has a descriptive title (not a vague title like `Update index.md`)
- [x] My pull request targets the `master` branch of freeCodeCamp.
- [x] All the files I changed are in the same world language, for example: only English changes, or only Chinese changes, etc.

This PR creates a new version of the `comments-dictionary.js`.  Now it contains two separate arrays of comment objects with an `id` and a `text` property.  One for comments that need to be translated and one for comments that do not need to be translated.

### CODE REVIEW

**Comment by RandellDawson** [comment]
@ojeytonwilliams This PR is now ready for you to add your parser changes to account for the new structure of the comments dictionary.

**Comment by raisedadead** [comment]
@ojeytonwilliams this PR is prep-ed for the oncoming changes that you would want to do pick and use the translated version of the comment dictionary.

Feel free to mock it while writing code for it, we will add/overwrite the file with the Crowdin integration later.

@RandellDawson 

I am also going to need you to update the docs/schema to reflect these:

1. We have a comment dictionary and it should not be expanded without prior discussion with the dev-team. Some pointer for contributors with examples of parts the strings should not be translated.

2. We are working on an integration to make it possible to work on i18n for this dictionary. (later replace this sentence with doc for Crowdin when its available).

The idea is to have something in the interim while we figure out a way to decorate strings and get advice from Crowdin for the setup of this file.

**Comment by RandellDawson** [comment]
>@RandellDawson
>
>I am also going to need you to update the docs/schema to reflect these:
>
>We have a comment dictionary and it should not be expanded without prior discussion with the dev-team. Some pointer for contributors with examples of parts the strings should not be translated.
>
>We are working on an integration to make it possible to work on i18n for this dictionary. (later replace this sentence with doc for Crowdin when its available).
>
>The idea is to have something in the interim while we figure out a way to decorate strings and get advice from Crowdin for the setup of this file.

@raisedadead I added a couple sections in the `How to work on coding challenges` file to incorporate best practices with using comments in the challenge seed code and mentioned the comment dictionaries.

I am sure the wording could be improved, but I feel the changes reflect the main goal.  @moT01 What do you think?

**Comment by raisedadead** [comment]
I think the docs look good. Thanks for adding the clarifications.

**Comment by ojeytonwilliams** [comment]
@RandellDawson if you're happy with this, I'll delete the Spanish and move the translations we do have into the Chinese.

**Comment by ojeytonwilliams** [comment]
I've left the debug commit in so that it's possible to verify that all the comments get replaced - both via testing and by looking in the client.  I'll clean up the history a little after QA.

**Review by raisedadead — COMMENTED** [review]
Logic LGTM. Fixing that linting error would allow passing the tests I believe.

**Comment by ojeytonwilliams** [comment]
Yep, the tests pass locally, it's just the linting. I just want Randy to have a chance to review and then I'll clean everything up.

**Comment by ojeytonwilliams** [comment]
I've dealt with the linting issues, so it should be easier to QA now.

**Comment by ojeytonwilliams** [comment]
The way I've implemented things means we need a complete dictionary before the tests for that language will pass.  If the tests detect any English comments in the Chinese, they will fail.  

@raisedadead if this will be too much of a headache for test deployments, let me know and I'll comment out that bit for now.

**Comment by raisedadead** [comment]
>  If the tests detect any English comments in the Chinese, they will fail.

Could we put in a placeholder comment in Chinese?

**Comment by ojeytonwilliams** [comment]
> Could we put in a placeholder comment in Chinese?

Sure, how about 'comment placeholder (needs translation)'?

**Comment by raisedadead** [comment]
Yup - totally works for me.

**Comment by ojeytonwilliams** [comment]
It should pass with our without the debug commit now.

**Comment by raisedadead** [comment]
Let's summon the comments ninja @RandellDawson to take a look and merge this in

**Comment by RandellDawson** [comment]
@raisedadead I personally would like to see the current English comments back in `curriculum/dictionaries/chinese/comments.js`.  I would think we want the build to fail if a comment has not been translated.  I thought the original idea was to get the `curriculum/dictionaries/chinese/comments.js` into the repo, so that @miyaliu666 could test out using Crowdin to create these translations that really should never change once they have been translated.  If the English text is in the file, then when it gets translated, the English text still shows which makes the build fail (which I thought is what we want).

Also, while testing locally, I am seeing the following (plus many more like them)  in my console when running `npm run develop`:
```bash
Should display 'carrot' does not appear in the comment dictionary
Using s = [2, 5, 7] would be invalid does not appear in the comment dictionary
responseFromServer is set to false to represent an unsuccessful response from a server does not appear in the comment dictionary
responseFromServer is set to true to represent a successful response from a server does not appear in the comment dictionary
responseFromServer represents a response from a server does not appear in the comment dictionary
Change this line does not appear in the comment dictionary
Change this line does not appear in the comment dictionary
Creates a 2-D array with m rows and n columns of zeroes does not appear in the comment dictionary
Adds the m-th row into newArray does not appear in the comment dictionary
Pushes n zeroes into the current row to create the columns does not appear in the comment dictionary
Pushes the current row, which now has n zeroes in it, to the array does not appear in the comment dictionary
Open your browser console. does not appear in the comment dictionary
Use console.log() to print the output variable. does not appear in the comment dictionary
Run the tests to see the difference between the two consoles. does not appear in the comment dictionary
Now, add console.clear() before your console.log() to clear the browser console, and pass the tests. does not appear in the comment dictionary
Setup does not appear in the comment dictionary
Setup does not appear in the comment dictionary
Change this line does not appear in the comment dictionary
Setup does not appear in the comment dictionary
Change this line does not appear in the comment dictionary
Setup does not appear in the comment dictionary
Change this line does not appear in the comment dictionary
Setup does not appear in the comment dictionary
Change this line does not appear in the comment dictionary
Setup does not appear in the comment dictionary
Setup does not appear in the comment dictionary
Variable declarations does not appear in the comment dictionary
Variable assignments does not appear in the comment dictionary
Change this line does not appear in the comment dictionary
Setup does not appear in the comment dictionary
Setup does not appear in the comment dictionary
Display code does not appear in the comment dictionary
Setup does not appear in the comment dictionary
Setup does not appear in the comment dictionary
Setup does not appear in the comment dictionary
Setup does not appear in the comment dictionary
Change this line does not appear in the comment dictionary
Setup does not appear in the comment dictionary
Add a record here does not appear in the comment dictionary
Setup does not appear in the comment dictionary
Setup does not appear in the comment dictionary
Setup does not appear in the comment dictionary
Setup does not appear in the comment dictionary
Run and check the console does not appear in the comment dictionary
myVar is not defined outside of myLocalScope does not appear in the comment dictionary
Setup does not appear in the comment dictionary
Setup does not appear in the comment dictionary
Setup does not appear in the comment dictionary
Setup does not appear in the comment dictionary
Setup does not appear in the comment dictionary
Setup does not appear in the comment dictionary
Declare the myGlobal variable below this line does not appear in the comment dictionary
Assign 5 to oopsGlobal Here does not appear in the comment dictionary
Setup does not appear in the comment dictionary
Change this line does not appear in the comment dictionary
Change this line does not appear in the comment dictionary
Setup does not appear in the comment dictionary
Setup does not appear in the comment dictionary
Change this line does not appear in the comment dictionary
Setup does not appear in the comment dictionary
Change this line does not appear in the comment dictionary
Setup does not appear in the comment dictionary
Change this line does not appear in the comment dictionary
Change this line does not appear in the comment dictionary
Change this line does not appear in the comment dictionary
Change this line does not appear in the comment dictionary
Change this line does not appear in the comment dictionary
Setup does not appear in the comment dictionary
Change this line does not appear in the comment dictionary
Change this line does not appear in the comment dictionary
Change this line does not appear in the comment dictionary
Change this line does not appear in the comment dictionary
Change this line does not appear in the comment dictionary
Setup does not appear in the comment dictionary
Change this line does not appear in the comment dictionary
Setup does not appear in the comment dictionary
Setup does not appear in the comment dictionary
Setup does not appear in the comment dictionary
Change this line does not appear in the comment dictionary
Change this line does not appear in the comment dictionary
Setup does not appear in the comment dictionary
Change this line does not appear in the comment dictionary
Change this line does not appear in the comment dictionary
Setup does not appear in the comment dictionary
Change this line does not appear in the comment dictionary
Setup does not appear in the comment dictionary
Setup does not appear in the comment dictionary
Setup does not appear in the comment dictionary
Change this line does not appear in the comment dictionary
Change this line does not appear in the comment dictionary
Change this line does not appear in the comment dictionary
Change this line does not appear in the comment dictionary
```

Lastly, when running `npm run develop`, I get:

```bash
 ERROR 

Missing English challenge for
08-data-analysis-with-python/data-analysis-with-python-course/pandas-condtitional-selection-and-modifying-dataframes.md
It should be in
/home/rdawson/Coding/fcc/curriculum/challenges/english/08-data-analysis-with-python/data-analysis-with-python-course/pandas-condtitional-selection-and-modifying-dataframes.md

  Error: Missing English challenge for
  08-data-analysis-with-python/data-analysis-with-python-course/pandas-condtitional-selection-and-modifying-dataframes.md
  It should be in
  /home/rdawson/Coding/fcc/curriculum/challenges/english/08-data-analysis-with-python/data-analysis-with-python-course/pandas-condtitional-selection-and-modifying-dataframes.md
```

The reason it appears, is that the English version of the challenge was renamed due to the typo "condtitional" to the following:
> curriculum/challenges/english/08-data-analysis-with-python/data-analysis-with-python-course/pandas-conditional-selection-and-modifying-dataframes.md

but it was never changed in the Chinese version.

**Comment by raisedadead** [comment]
Yes - That's correct while went back and forth on a lot of ideas and settled on a few things. 

I agree on those points that you mentioned.

However, as we are fine tuning the we think the build process the builds should not fail for reasons other than logic errors (unit tests, etc.) - "**for now as of this PR**".

I would not be able to explain all the details of "how" the Crowdin integration will evolve (you are going to have to trust me on this one 😅). 

In interest of time here is the spec that we need to hit with this PR and nothing more:

1. Add a comment dictionary in English at its said location that we have defined in the Corwdin.yml
2. Make sure the parse can pick things up from their locations including the other-language bits.
3. Make sure that the build and linting for comments in English passes - we do not need to worry about the other-language translations, consistency or anything additional - "**for now in this PR**"
4. Make sure we are able to build and see the site in other-languages (if the miss comments, strings, or show up placeholders, etc.) - "**for now in this PR**"

The idea right now is to get the main bits in and make `master` stable "**one bit at a time**", that includes addressing some of those warnings and errors.

We would be able to manage this by not using that last `DEBUG` commit

Hope this clarifies things.

**Comment by RandellDawson** [comment]
@raisedadead I suppose I am ok with the changes then.  Merge when ready.  I think I was just trying to make sure we have a way to validate a Chinese translation exists for each comment at some point before go to build the Chinese version for production.

Also, my first reply above was really just wanting to make sure we harnessed the following code in `test-challenges.js`:
```js
            // - None of the translatable comments should appear in the
            //   translations. While this is a crude check, no challenges
            //   currently have the text of a comment elsewhere. If that happens
            //   we can handle that challenge separately.
            TRANSLATABLE_COMMENTS.forEach(comment => {
              Object.values(challenge.files).forEach(file => {
                if (file.contents.includes(comment))
                  throw Error(
                    `English comment '${comment}' should be replaced with its translation`
                  );
              });
            });
```

where if we were to go back and put the same English comments into the Chinese `comments.js` file, we would "know" a translation was made (the English version would not appear in the Chinese seed code). As long we revert the Chinese `comments.js` at some point where Miya or someone else can go through Crowdin to make all the translations, then I am content. The code above helps protect us from accidentally leaving a comment untranslated before trying to build.

**Comment by raisedadead** [comment]
> ... we have a way to validate a Chinese translation exists for each comment at some point before go to build the Chinese version for production.

That is correct, we would not roll this out on .org without those validations in place. For the current spike like @ojeytonwilliams  mentioned we have a "fallback" placeholder that can be used in tandem with the Crowdin integration that I am working on to make this quite smooth experience.

The end goal being, we would not do any i18n changes on GitHub other than build validation, sanity checks etc.

**Comment by ojeytonwilliams** [comment]
Just a temporary block while I check something. Will update once I have.

**Comment by ojeytonwilliams** [comment]
It had been testing for comment replacement in all certs, while only replacing them in audited ones.  Should be fixed now.

**Pull request merged**
