### PR TITLE
fix: content misalignment on the profile page

### LINKED ISSUE #51955: Content misalignment on the profile page
### Describe the Issue

This issue was reported on Discord: https://discord.com/channels/692816967895220344/693145545878929499/1162395054237831301.

The certification links are shifted to the left instead of being centered:

Screenshot 2023-10-13 at 21 56 47

### System

N/A

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by ghost**
Checklist:

- [x] I have read and followed the [contribution guidelines](https://contribute.freecodecamp.org).
- [x] I have read and followed the [how to open a pull request guide](https://contribute.freecodecamp.org/#/how-to-open-a-pull-request).
- [x] My pull request targets the `main` branch of freeCodeCamp.
- [x] I have tested these changes either locally on my machine, or GitPod.

Closes #51955

I have increased the size of the certification links instead of shifting it to the center, by removing the wrapper around the link.

Screenshot 2023-10-14 033557
Screenshot 2023-10-14 033607

### CODE REVIEW

**Comment by Amit-Morade** [comment]
Can I work on this

**Comment by devuser200** [comment]
@Amit-Morade I am not a member of the team. You should go to #51955 where the issue was raised

**Review by huyenltnguyen — COMMENTED** [review]
Hey @devuser200, thank you for your contribution!

As mentioned in the issue thread, we are going to proceed with #52008 as the fix aligns with what we want to achieve (using a layout component to maintain the layout consistency). Therefore, we are going to close this PR in favor of #52008.

However, we do appreciate your time and efforts, and we are going to label this PR with `hacktoberfest-accepted` as a thank-you. We hope you won't be discouraged by this, and we look forward to your future contributions.

Happy contributing!

**Comment by devuser200** [comment]
@huyenltnguyen Thank you for adding the label.

**Pull request closed without merging**
