### PR TITLE
fix(curriculum): fix typo in challenge

### LINKED ISSUE #45269: typo in test of a challenge
In challenge Euler problem 184 both the hint and the text have the function call with a typo.

To fix this issue you would need to edit the linked file and remove the extra `t` in the function call in the test description and in the assertion of the test itself.

https://github.com/freeCodeCamp/freeCodeCamp/blob/main/curriculum/challenges/english/10-coding-interview-prep/project-euler/problem-184-triangles-containing-the-origin.md

Please make sure you read [our guidelines for contributing](https://contribute.freecodecamp.org/#/), we prioritize contributors following the instructions in our guides. Join us in [our chat room](https://chat.freecodecamp.org/channel/contributors) or [the forum](https://forum.freecodecamp.org/c/contributors/3) if you need help contributing, our moderators will guide you through this.

Sometimes we may get more than one pull requests. We typically accept the most quality contribution followed by the one that is made first.

Happy contributing.

### PR DESCRIPTION
**Pull request by LedaThemis**
Checklist:

- [x] I have read [freeCodeCamp's contribution guidelines](https://contribute.freecodecamp.org).
- [x] My pull request has a descriptive title (not a vague title like `Update index.md`)
- [x] My pull request targets the `main` branch of freeCodeCamp.
- [x] I have tested these changes either locally on my machine, or GitPod.

Closes #45269

Fixed typo in english, japanese, portuguese, ukrainian

### CODE REVIEW

**Comment by ieahleen** [comment]
Thank you for your pull request, but we are unable to accept it as it is. As explained in our contributing guidelines, changes to challenges have to be done only to the English files, as the other languages are updated through automated pipelines.
Please update this PR removing the changes to non-english languages

**Comment by LedaThemis** [comment]
I apologize for the inconvenience!
I reverted the commit, and made the correct changes.
Is this how it should be done? or should I fork the repo again and make changes?

**Review by gikf — APPROVED** [review]
@LedaThemis it's okay right now.

LGTM :+1: 

---

Note for future - it is recommended to make changes on a separate branch, than the `main` branch. See more about it in point 3 at https://contribute.freecodecamp.org/#/how-to-setup-freecodecamp-locally?id=making-changes-locally.

**Review by majestic-owl448 — APPROVED** [review]
Hi @LedaThemis. Congrats on your first pull request (PR)! 🎉

Thank you for your contribution to the page! 👍
We are happy to accept these changes and look forward to future contributions. 📝

**Pull request merged**
