### PR TITLE
Changed the description of the algorithm

### PR DESCRIPTION
**Pull request by Prudkovskiy**
- [x] I have read [freeCodeCamp's contribution guidelines](https://github.com/freeCodeCamp/freeCodeCamp/blob/master/CONTRIBUTING.md).
- [x] My pull request has a descriptive title (not a vague title like `Update index.md`)
- [x] My pull request targets the `master` branch of freeCodeCamp.
- [x] None of my changes are plagiarized from another source without proper attribution.
- [x] My article does not contain shortened URLs or affiliate links.

If your pull request closes a GitHub issue, replace the XXXXX below with the issue number.

Closes #XXXXX

### CODE REVIEW

**Review by greggubarev — APPROVED** [review]
### LGTM 👍  Congrats on your first contribution! 
Image of Office
Thank you for the PR ✨ 🎉 We're happy to accept these changes and look forward to your future contributions.

Happy coding!

**Comment by RandellDawson** [comment]
@greggubarev This PR should not have been accepted.  Only the FCC created videos (i.e. scrimba) are to referenced for the videoUrl key in the front matter.  Would you mind creating another PR to revert back to the original empty string for the videoUrl?

Thank you.

**Comment by greggubarev** [comment]
> @greggubarev This PR should not have been accepted. Only the FCC created videos (i.e. scrimba) are to referenced for the videoUrl key in the front matter. Would you mind creating another PR to revert back to the original empty string for the videoUrl?
> 
> Thank you.

@RandellDawson ok

**Comment by RandellDawson** [comment]
I created an issue #34535, because I was not sure when you would be working on this.  Can you reference this issue in your PR (Closes #XXXXX)?

Thanks.

**Pull request merged**
