### PR TITLE
fix: removed trailing spaces, fixed a typo

### PR DESCRIPTION
**Pull request by tr1s**
Just some cleanups

- [x] I have read [freeCodeCamp's contribution guidelines](https://github.com/freeCodeCamp/freeCodeCamp/blob/master/CONTRIBUTING.md).
- [x] My pull request has a descriptive title (not a vague title like `Update index.md`)
- [x] My pull request targets the `master` branch of freeCodeCamp.
- [x] None of my changes are plagiarized from another source without proper attribution.
- [x] All the files I changed are in the same world language (for example: only English changes, or only Chinese changes, etc.)
- [x] My changes do not use shortened URLs or affiliate links.

### CODE REVIEW

**Comment by RandellDawson** [comment]
Mods: There are a few other PRs with changes to the same section of these files, so there will be merge conflicts to resolve before being able to review/merge this PR.

**Review by ojeytonwilliams — APPROVED** [review]
LGTM :+1:

**Comment by RandellDawson** [comment]
Still waiting on PR #37103, #37238, and #37266 to be merged first.

**Comment by RandellDawson** [comment]
@ojeytonwilliams Doesn't the linter or Huskey remove lines with only whitespace upon commit?

**Comment by ojeytonwilliams** [comment]
The markdown linter we currently just makes suggestions, unfortunately. My plan is to migrate to one that can also fix trivial things like this.

**Pull request merged**
