### PR TITLE
Added more direction to the challenge.

### PR DESCRIPTION
**Pull request by TarunApp**
The challenge might be a little confusing because when the use attempts to use the attribute selector within style, the changes might not show. This is due to the attribute selector having to be placed before all other style selectors. If there is another way for me to submit this change, please contact me!
Thank you.

- [x] I have read [freeCodeCamp's contribution guidelines](https://github.com/freeCodeCamp/freeCodeCamp/blob/master/CONTRIBUTING.md).
- [x] My pull request has a descriptive title (not a vague title like `Update index.md`)
- [x] My pull request targets the `master` branch of freeCodeCamp.
- [x] None of my changes are plagiarized from another source without proper attribution.
- [x] All the files I changed are in the same world language (for example: only English changes, or only Chinese changes, etc.)
- [x] My changes do not use shortened URLs or affiliate links.

Closes #XXXXX

### CODE REVIEW

**Comment by RandellDawson** [comment]
@TarunApp Can you give a little more detail about what you mean by "when the user attempts to use the attribute selector within style, the changes might not show" ?

Do you have some example code which you think should pass the tests but does not?

**Comment by TarunApp** [comment]
> @TarunApp Can you give a little more detail about what you mean by "when the user attempts to use the attribute selector within style, the changes might not show" ?
> 
> Do you have some example code which you think should pass the tests but does not?

Hello, @RandellDawson, when I was attempting this challenge, I used the attribute selector for altering the checkboxes. However, I put the code after id and class selectors, this caused my code to not work and the you cannot complete the challenge. There is no explicit description that said the attribute selector had to be placed above id and class selectors, which allowed me to complete the challenge. I apologize if I didnt follow procedure or am hindering anything, its just that for people who think linearly or specifically, it was a little frustrating to see the code not working haha.

**Comment by TarunApp** [comment]
@RandellDawson can you verify this error by yourself? I  just want to make sure my computer is not the only one having issues.

**Comment by RandellDawson** [comment]
@TarunApp Can you provide the exact code you used in the style tags (including the style tags), so I can test?

Thank you.

**Comment by TarunApp** [comment]
> @TarunApp Can you provide the exact code you used in the style tags (including the style tags) which failed, so I can test?
> 
> Thank you.

`<link href="https://fonts.googleapis.com/css?family=Lobster" rel="stylesheet" type="text/css">
<style>
  .red-text {
    color: red;
  }

  h2 {
    font-family: Lobster, monospace;
  }

  p {
    font-size: 16px;
    font-family: monospace;
  }

  .thick-green-border {
    border-color: green;
    border-width: 10px;
    border-style: solid;
    border-radius: 50%;
  }

  .smaller-image {
    width: 100px;
  }

  .silver-background {
    background-color: silver;

  [type='checkbox']{
    margin:10px 0px 15px 15px;
  }

  }
</style>

<h2 class="red-text">CatPhotoApp</h2>
<main>
  <p class="red-text">Click here to view more <a href="#">cat photos</a>.</p>
  
  <a href="#">A cute orange cat lying on its back.</a>
  
  <div class="silver-background">
    <p>Things cats love:</p>
    <ul>
      <li>cat nip</li>
      <li>laser pointers</li>
      <li>lasagna</li>
    </ul>
    <p>Top 3 things cats hate:</p>
    <ol>
      <li>flea treatment</li>
      <li>thunder</li>
      <li>other cats</li>
    </ol>
  </div>
  
  <form action="/submit-cat-photo" id="cat-photo-form">
    <label><input type="radio" name="indoor-outdoor" checked> Indoor</label>
    <label><input type="radio" name="indoor-outdoor"> Outdoor</label><br>
    <label><input type="checkbox" name="personality" checked> Loving</label>
    <label><input type="checkbox" name="personality"> Lazy</label>
    <label><input type="checkbox" name="personality"> Energetic</label><br>
    <input type="text" placeholder="cat photo URL" required>
    <button type="submit">Submit</button>
  </form>
</main>`

This is the exact code. Notice how the attribute selector is placed after the id and class selectors. When you attempt this, the terminal returns an error of the following.
`The top margins of the checkboxes should be 10px.
The bottom margins of the checkboxes should be 15px.`

**Comment by TarunApp** [comment]
Apologies, the previous comment was disorganized, I dont know why it complies the code.
Try this code in challenge: Basic CSS: Use Attribute Selectors to Style Elements

<link href="https://fonts.googleapis.com/css?family=Lobster" rel="stylesheet" type="text/css">
<style>
  .red-text {
    color: red;
  }

  h2 {
    font-family: Lobster, monospace;
  }

  p {
    font-size: 16px;
    font-family: monospace;
  }

  .thick-green-border {
    border-color: green;
    border-width: 10px;
    border-style: solid;
    border-radius: 50%;
  }

  .smaller-image {
    width: 100px;
  }

  .silver-background {
    background-color: silver;

  [type='checkbox']{
    margin:10px 0px 15px 15px;
  }

  }
</style>

<h2 class="red-text">CatPhotoApp</h2>
<main>
  <p class="red-text">Click here to view more <a href="#">cat photos</a>.</p>
  
  <a href="#">A cute orange cat lying on its back.</a>
  
  <div class="silver-background">
    <p>Things cats love:</p>
    <ul>
      <li>cat nip</li>
      <li>laser pointers</li>
      <li>lasagna</li>
    </ul>
    <p>Top 3 things cats hate:</p>
    <ol>
      <li>flea treatment</li>
      <li>thunder</li>
      <li>other cats</li>
    </ol>
  </div>
  
  <form action="/submit-cat-photo" id="cat-photo-form">
    <label><input type="radio" name="indoor-outdoor" checked> Indoor</label>
    <label><input type="radio" name="indoor-outdoor"> Outdoor</label><br>
    <label><input type="checkbox" name="personality" checked> Loving</label>
    <label><input type="checkbox" name="personality"> Lazy</label>
    <label><input type="checkbox" name="personality"> Energetic</label><br>
    <input type="text" placeholder="cat photo URL" required>
    <button type="submit">Submit</button>
  </form>
</main>

**Comment by RandellDawson** [comment]
@TarunApp I see what you are talking about now.  However, instead of changing the instructions, I think we need to change the test to allow the selector to be placed anywhere in the `style` element.  I have created a separate PR to address the test.

**Comment by TarunApp** [comment]
> @TarunApp I see what you are talking about now. However, instead of changing the instructions, I think we need to change the test to allow the selector to be placed anywhere in the `style` element. I have created a separate PR to address the test.

**Comment by TarunApp** [comment]
@RandellDawson Is it the testing or does this occur in real HTML?

**Comment by RandellDawson** [comment]
It is the first test which needs to be fixed.

**Comment by RandellDawson** [comment]
I am going to reopen this PR to serve as a reference for my PR which should resolve the issue if you don't mind.

**Comment by TarunApp** [comment]
That is alright, I just want to help others! Thanks for your responsive cooperation. Do you want me to make any improvements on my issue reporting?

**Comment by RandellDawson** [comment]
@TarunApp In the future, when you are thinking of changing the verbiage for a challenge, it would probably be better to create an issue first, so others can review and discuss and create PRs if necessary to resolve the issue.

**Comment by TarunApp** [comment]
> @TarunApp In the future, when you are thinking of changing the verbiage for a challenge, it would probably be better to create an issue first, so others can review and discuss and create PRs if necessary to resolve the issue.

I will make sure to do this in the future. Thank you.

**Comment by RandellDawson** [comment]
@TarunApp On second review of your code, I noticed a problem with your actual solution.  You have tried to embed the selector inside the `silver-background` class.  There is nothing wrong with the test actually.  It is your code.  In general, always go to [the forum](https://forum.freecodecamp.org) first and ask why your solution does not pass.  They will debug and let you know if it is your code or an actually bug with the tests.

**Comment by TarunApp** [comment]
Sorry for the issue. I'll make sure to use the forum next time.

**Pull request closed without merging**
