### PR TITLE
fix(curriculum): clarify react use-array.map-to-dynamically-render-elements.md

### LINKED ISSUE #46470: Typo in challenge instructions React - Array.map
### Describe the Issue

Instructions say:

"Next, delete the comment in the `render()` method..."
instead of:
"Next, delete the `null` value in the `render()` method..."

### Affected Page

https://github.com/freeCodeCamp/freeCodeCamp/blob/main/curriculum/challenges/english/03-front-end-development-libraries/react/use-array.map-to-dynamically-render-elements.md

### PR DESCRIPTION
**Pull request by L4rryFisherman**
Checklist:

- [x] I have read [freeCodeCamp's contribution guidelines](https://contribute.freecodecamp.org).
- [x] My pull request has a descriptive title (not a vague title like `Update index.md`)
- [x] My pull request targets the `main` branch of freeCodeCamp.
- [x] I have tested these changes either locally on my machine, or GitPod.

Closes #46470

### CODE REVIEW

**Comment by raisedadead** [comment]
Hi @L4rryFisherman 

Thanks for taking the time to contribute to freeCodeCamp. We sincerely appreciate the help. 

The first look at the PR doesn't tell a maintainer "what" it is about. While it can be tempting to make a quick typo fix, it's best you still follow the contribution workflows for this repo 🙂 - they are there to make everyone's lives easier.

Your fellow peers and maintainers are more likely to take your PR seriously when you follow these. Everything you need to know about it is available in the contributing guidelines.

Happy contributing.

**Review by moT01 — APPROVED** [review]
I'm fine with this change. LGTM @L4rryFisherman 🎉

**Review by Sboonny — APPROVED** [review]
LGTM 🎉, thank you for your contribution to the page! 👍.

**Comment by L4rryFisherman** [comment]
> Hi @L4rryFisherman 
> 
> Thanks for taking the time to contribute to freeCodeCamp. We sincerely appreciate the help. 
> 
> The first look at the PR doesn't tell a maintainer "what" it is about. While it can be tempting to make a quick typo fix, it's best you still follow the contribution workflows for this repo 🙂 - they are there to make everyone's lives easier.
> 
> Your fellow peers and maintainers are more likely to take your PR seriously when you follow these. Everything you need to know about it is available in the contributing guidelines.
> 
> Happy contributing.

Thanks for the feedback. I had previously created an issue for this item and thought I had 'linked' the PR to it. But as I understand now, this is a one way link of attaching the PR to an issue, but not attaching the issue to the PR, so the PR-title should still be descriptive as well, correct?

**Comment by moT01** [comment]
Yes @L4rryFisherman - although it doesn't always happen, PR titles are supposed to be in a specific format - something like `type(scope): title/details`. [See all the commits on main](https://github.com/freeCodeCamp/freeCodeCamp/commits/main) for examples. This is partially my fault, reviewers are supposed to make sure there's a good title before merging.

This is a pretty minor fix/change so it's not a very big deal here - but the typical workflow would be to create an issue (which you did), then we come up with a solution amongst staff and contributors in the issue discussion, then we add an appropriate label to the issue (maybe `help wanted`), then we will accept a PR to make the fix. It's tough to follow it to a "T" all the time, but that's what we try to do anyway.

**Comment by moT01** [comment]
I change the title anyway as an example 👍 Congratulations on your first contribution to the freeCodeCamp repo 🎉

**Pull request merged**
