### PR TITLE
Make Exact Change function name unique & lint

### PR DESCRIPTION
**Pull request by erictleung**
Tested locally. References #7085.
- Change `drawer` function to `checkCashRegister`
- Add code tags around subjectively needed text

### CODE REVIEW

**Comment by ltegman** [comment]
I know this was on the list in that thread, but I guess I'm confused as to why this needs to change. This function name already is unique and only used by this challenge. I'd rather we change as few of these function names as possible since changing them means invalidating everyone's saved solution and needing to change the wiki solution.

@SaintPeter Is there a reason why this particular challenge name needs to change even though it's not shared with another challenge?

**Comment by SaintPeter** [comment]
Yes, we want the names to not only be unique within FCC, but to not be plain english words, so we can discern them from the chat.

@erictleung There appears to be an issue that Exact Change is not showing a solution?  check the output of `npm run test-challenges`.

**Comment by erictleung** [comment]
@SaintPeter It's been a while since I made this PR so I rebased the branch. I then ran `npm run test-challenges` and didn't run into any problems. It says it ran total of 716 tests and all 716 of them pass.

**Comment by SaintPeter** [comment]
When I look at the test output I see:
Exact Change
No solutions for Exact Change

So I don't think it's being tested at all.

**Comment by erictleung** [comment]
So there is a section of the tests titled `These challenges have no solutions` and Exact Change is there but it doesn't throw up any red flags or anything. Is this what you are seeing or something else?

**Comment by SaintPeter** [comment]
Sorry for the delay in accepting this.  I will add a solution to it.

This looks good and if you want to do this for other challenges that would be awesome!

**Pull request merged**
