### PR TITLE
fix(i18n): chinese test suite

### PR DESCRIPTION
**Pull request by scissorsneedfoodtoo**
Add localeTiltes, descriptions, and adjust test text and testStrings to get the automated test suite working. The changes to the testStrings here are from the current English curriculum.

- [x] I have read [freeCodeCamp's contribution guidelines](https://github.com/freeCodeCamp/freeCodeCamp/blob/master/CONTRIBUTING.md).
- [x] My pull request has a descriptive title (not a vague title like `Update index.md`)
- [x] My pull request targets the `master` branch of freeCodeCamp.
- [x] None of my changes are plagiarized from another source without proper attribution.
- [x] All the files I changed are in the same world language (for example: only English changes, or only Chinese changes, etc.)
- [x] My changes do not use shortened URLs or affiliate links.

Closes #XXXXX

### CODE REVIEW

**Comment by RandellDawson** [comment]
@scissorsneedfoodtoo @raisedadead I would prefer not merging this PR, because @ojeytonwilliams has a draft PR (#38040) that will use the English challenge seed, `testString`s, and solutions for the non-English versions.  It will also warn if the number of tests does not match (to catch situations where tests in English have been removed or added).  My plan was to be able to use the feature of this PR to capture all Chinese challenges that have different testStrings (minus the assert arguments), so we would know those challenge's `text` need to be scrutinized.  More than likely, if a challenge's number of tests is different, then the `text` probably changed on one or more of the tests for the challenge.  Also, even if the number of tests is the same, but the `testString` is different, it means that we probably need to make sure the `text` reflects any changes to the `textString`.  

If you merge this PR, then we will lose all the insight on which challenges' text` actually need to be reviewed in the Chinese version.

**Comment by raisedadead** [comment]
We do intend in releasing the Chinese Curriculum ASAP.

Can you confirm if we would have the draft PR ready sooner in the next week.

Is there anything that we can do to speed up the same.

Is branching off or melding the PR into the target or this PR going to help?

**Comment by ojeytonwilliams** [comment]
I don't think my PR should be rushed in. If I've messed something up, it could affect a huge number of challenges.  As for finishing it, the main barriers (aside from QA) are the concerns @ahmadabdolsaheb raised and I wrote up here: https://github.com/freeCodeCamp/freeCodeCamp/pull/38040#issuecomment-577699712 Until we've figured out how to resolve them, I don't think the PR can be used.

@RandellDawson if this PR is merged, could you not diff the merge commit with the previous one? You should still be able to see all the changes to the testStrings.

**Comment by scissorsneedfoodtoo** [comment]
@RandellDawson, you bring up a very good point. Unfortunately, this PR would make it more difficult to figure out which Chinese challenges's `text` will need to be updated.

I think your method of determining whether the `text` or `testString` for a test or tests needs to be updated is sound. When I was going through this by hand, comparing the number of tests between the English and Chinese challenges was the most obvious indication that the English challenge had updated tests.

The most common problem with the current Chinese `testString`s are the third arguments for the `assert` statements. A lot of them have been removed or fixed in the English curriculum, but on the Chinese side, a bunch of challenges have nested double quotes. There were also things like missing `localeTitle`s, descriptions, and solutions that used `// solution  required` (with two spaces instead of one), which caused the solution to be tested and fail.

Like @raisedadead mentioned on a call yesterday, the next step could be to take the solutions from the English challenges and port them to the Chinese files. The errors there will give us a good idea of which tests will need to be updated.

After that, while it's not ideal, one thing we could do is ask Chinese contributors to keep a list of challenges where the test `text` or `testString`s are different than the English versions. Then we should have a good idea of which challenges in other languages will need to be fixed before @ojeytonwilliams's PR lands.

**Comment by raisedadead** [comment]
Oliver, you have done some incredible work on the PR and you are correct, we would not want to rush you at all.

That said, the Chinese community has been waiting for the curriculum to go live and we have a good momentum over here in terms of the translation efforts.

The freeCodeCamp.one instance is running on the legacy code and is also becoming slower to manage. We could spend the time getting it upto speed or dedicate ourselves in bring the Curriculum at par with the current english version (which it self is getting a overhaul)

I would vote for bringing this PR in and moving forward. And like Randell has pointed it would make our lives difficult, but I would ask your opinion before moving forth.

Would you all be OK with merging this and handling the additional work to bring the consistency in the `text` and `testStrings`.

The reason being we can get this live real quick on the staging instance and have a lot of eyes from the Chinese community who are currently working on the legacy codebase here. That way, we can quickly iterate and bring in the quality that we are aiming for.

Thoughts?

**Comment by raisedadead** [comment]
Quick Update:

Randell has reached out to me, he is on vacation for a few days and will have completed all that he needs to do to capture the data.

He has already completed hours worth of work on this, and has requested us to wait a few days.

I would honor his request and put a hold on this until next week. Meanwhile, I should still be able to take the changes from this PR and manually land a build for our internal testing.

Thanks a lot to everyone for your flexibility, patience and work on this. I am sure the Chinese community will be looking forward to this, excited as we are.

**Comment by scissorsneedfoodtoo** [comment]
Thank you @RandellDawson and @ojeytonwilliams for all of your hard work unifying these tests. It will go a long way towards maintenance between these two languages, and later, all of the other translations.

Please let me know if there's anything else I can do in this PR. Once we have a good idea of which English challenges have changed since the release last year, I'd be happy to go in and apply them to the `text` and `testStrings` here in the Chinese challenges.

**Comment by raisedadead** [comment]
BTW, I was wondering since this PR targets the next-chinese branch. We can merge this. It could wait there while the #38040 (aiming master) gets ready and Randell is back?

@ojeytonwilliams thoughts?

**Comment by ojeytonwilliams** [comment]
As I understand it, this only affects my PR indirectly through what Randell was doing (putting together the comment dictionary).  As long as he's happy, I can't see any reason not to go ahead with this.

**Comment by raisedadead** [comment]
Awesome, so I am landing this on the `next-chinese` branch and I will setup the pipelines, provision servers, etc.

Thanks for all your work Gentlemen.

/cc @freeCodeCamp/chinese

**Pull request merged**
