### PR TITLE
fix(seed): Bootstrap default button fix

### LINKED ISSUE #17075: Wrong bootstrap button usage in challenge.
#### Challenge Name

https://www.freecodecamp.org/challenges/create-a-bootstrap-button

#### Issue Description

The button doesn't render in chrome. In Firefox and Safari a grey area appears, but it doesn't seem to be an actual bootstrap button (see screenshots). A default button is created by adding the classes btn and btn-default to the button element. Usage according to the documentation http://bootstrapdocs.com/v3.3.1/docs/css/#buttons:
```js
<!-- Standard button -->
<button type="button" class="btn btn-default">Default</button>


```

#### Browser Information

* Browser Name, Version: Chrome 66.0.3359.117
* Operating System: MacOS 10.13.2
* Mobile, Desktop, or Tablet: Desktop

#### Your Code

imho wrong:
```js

<button class="btn">Like</button>

```
#### Screenshot

the button isn't visible in chrome:
chrome<br>
there is a buttonlike gray area rendered in Firefox, but it doesn't have a style which is documented in the bootstrap documentation:
firefox<br>
Valid bootstrap (v3.3.1) buttons:
bootstrap_buttons

### PR DESCRIPTION
**Pull request by mpro7**
added btn-default class to lessons with basic Bootstrap buttons, which
add proper styles for default button

Closes #17075

#### Pre-Submission Checklist

- [x] Your pull request targets the `staging` branch of freeCodeCamp.
- [x] Branch starts with either `fix/`, `feature/`, or `translate/` (e.g. `fix/signin-issue`)
- [x] You have only one commit (if not, [squash](http://forum.freecodecamp.org/t/how-to-squash-multiple-commits-into-one-with-git/13231) them into one commit).
- [x] All new and existing tests pass the command `npm test`. Use `git commit --amend` to amend any fixes.

#### Type of Change

- [x] Small bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds new functionality)
- [ ] Breaking change (fix or feature that would change existing functionality)
- [ ] Add new translation (feature adding new translations)

#### Checklist:

- [x] Tested changes locally.
- [ ] Addressed currently open issue (replace 17075 with an issue no in next line)

Closes #XXXXX

#### Description

As mentioned in the [#17075 issue](https://github.com/freeCodeCamp/freeCodeCamp/issues/17075), there was little bug or inaccuracy in the lesson with Bootstrap button, however the next two lessons needed to be change consistent. The class <code>btn-default</code> was missing and was added.

I'd also removed green styling for two buttons in the description in the lesson with using the <code>btn-block</code> class. This approach could be more clear for weaker users which sometimes get lost, when description it's not 1 to 1 with the example, either exercise. I've left the hover untouched.

This PR possibly closes #17075 but, there was a question of the rendering of the buttons too, which is still unanswered (in my environment the rendering bug doesn't exist).

Well, if the changes gonna be accepted the translation need to be done - this is the thing I've forgotten to ask, how you deal with it?

### CODE REVIEW

**Comment by raisedadead** [comment]
> I'd also removed green styling for two buttons in the description in the lesson with using the btn-block class. This approach could be more clear for weaker users which sometimes get lost, when description it's not 1 to 1 with the example, either exercise. I've left the hover untouched.

I think this is intended to have them simply not copy the example over. Which most beginners tend to do.

**Comment by raisedadead** [comment]
The rendering issue with chrome is seemingly macOS only.

**Comment by raisedadead** [comment]
Anyways, I like all of the changes. This is ready for a QA and merge. I'll do so soon, if no one beats me. You can ignore the translations for now.

**Comment by mstellaluna** [comment]
@raisedadead If this is a Mac only issue, I can't verify it.

**Comment by raisedadead** [comment]
@mstellaluna the rendering is part of the issue. The other parts of the issue exist on all systems.

**Comment by mstellaluna** [comment]
I am working on this PR

**Comment by mstellaluna** [comment]
@mpro7 Hello, I will be approving this PR. Thank you for your contribution. Happy Coding !

**Review by mstellaluna — APPROVED** [review]
LGTM

**Pull request merged**
