### PR TITLE
feat(api-server): show unique messages when API is called

### PR DESCRIPTION
**Pull request by Sboonny**
Checklist:

- [x] I have read and followed the [contribution guidelines](https://contribute.freecodecamp.org).
- [x] I have read and followed the [how to open a pull request guide](https://contribute.freecodecamp.org/#/how-to-open-a-pull-request).
- [x] My pull request targets the `main` branch of freeCodeCamp.
- [x] I have tested these changes either locally on my machine, or GitPod.

Ref #49396

This PR is open based on my understanding of this request https://github.com/freeCodeCamp/freeCodeCamp/pull/49396?notification_referrer_id=NT_kwDOBUKR3bM1NjIwNDM3NzY0Ojg4MjQ4Nzk3#pullrequestreview-1349922113

### CODE REVIEW

**Comment by Sboonny** [comment]
To remove Block label, this PR need to be merged #49782

**Comment by raisedadead** [comment]
This should be ready for review.

**Comment by Sembauke** [comment]
please merge main into this pr. @Sboonny

**Review by Sembauke — APPROVED** [review]

**Review by ShaunSHamilton — APPROVED** [review]
This LGTM 👍

**Pull request merged**
