### PR TITLE
Added 'Quirks' to article and changed capital I to lowercase i

### PR DESCRIPTION
**Pull request by LP773**
- [x] I have read [freeCodeCamp's contribution guidelines](https://github.com/freeCodeCamp/freeCodeCamp/blob/master/CONTRIBUTING.md).
- [x] My pull request has a descriptive title (not a vague title like `Update index.md`)
- [x] My pull request targets the `master` branch of freeCodeCamp.
- [x] None of my changes are plagiarized from another source without proper attribution.
- [x] My article does not contain shortened URLs or affiliate links.

If your pull request closes a GitHub issue, replace the XXXXX below with the issue number.

Closes #XXXXX

### CODE REVIEW

**Comment by scissorsneedfoodtoo** [comment]
We are marking this PR invalid for Hactoberfest as it does not follow the recommended guidelines below:

> ### Quality Standards
> In line with Hacktoberfest value #2 (Quantity is fun, Quality is key), we have provided examples of the quality standards we encourage. This applies mainly to beginners.
> 
> - PRs that are automated e.g. scripted opening PRs to remove white space / optimize images.
> - PRs that are disruptive e.g. taking someone else's branch/commits and making a PR.
> - PRs that are regarded by a project maintainer as a hindrance vs. helping.
> - Something that's clearly an attempt to simply +1 your PR count for October.

Learn more at https://hacktoberfest.digitalocean.com/details

The quirks section is from https://www.coursehero.com/file/p32gb8k/The-returned-type-must-be-compatible-with-the-actual-value-IDS-401-Fall-2017/

**Comment by lvphan** [comment]
I'd like more explanation. My contribution to the article was from my class notes, if another student uploads the professor's slides, it makes my contribution, invalid... because... it isn't my own information?

**Comment by scissorsneedfoodtoo** [comment]
@lvphan, I see, that would be a bit different. Sorry, we've been moving really fast to get through all of these open PRs.

I think it would still be best if you were to change up the wording and code example a bit. The main issue is that both are directly from a source that isn't your own. It seems like you closed your branch, so would you be able to open another PR?

**Comment by lvphan** [comment]
@scissorsneedfoodtoo , I apologize if I came off aggressive or rude. That wasn't my intention!

I can restore the branch. But let me see if I can do as you've asked and change up the wording and the code example a bit.

**Pull request closed without merging**
