### PR TITLE
fix(docs): add fill in the blank to challenge template

### PR DESCRIPTION
**Pull request by moT01**
Checklist:

- [x] I have read and followed the [contribution guidelines](https://contribute.freecodecamp.org).
- [x] I have read and followed the [how to open a pull request guide](https://contribute.freecodecamp.org/#/how-to-open-a-pull-request).
- [x] My pull request targets the `main` branch of freeCodeCamp.
- [x] I have tested these changes either locally on my machine, or GitPod.

Ref: https://github.com/freeCodeCamp/freeCodeCamp/issues/52304

### CODE REVIEW

**Comment by bbsmooth** [comment]
As I'm sure you can imagine, my spidey sense started tingling when I read the title of this PR. Are these fill in the blank questions implemented anywhere so I can take a look at them?

**Comment by moT01** [comment]
They're part of the English curriculum we are creating @bbsmooth. Set the `SHOW_UPCOMING_CHANGES` to `true` to see the "A2 English for Developers" superblock. Several of the challenges in there are this "fill in the blank" style. It was just added. Your input on accessibility would be greatly appreciated. Note that we are trying to teach the English language with these challenges - there's going to be audio, images, and new challenge types. I have mentioned to the creators that many of these things may have issues with accessibility - but, when trying to teach a language, we may have to make some compromises in this regard. Let me know what you find.

**Comment by bbsmooth** [comment]
> I have mentioned to the creators that many of these things may have issues with accessibility - but, when trying to teach a language, we may have to make some compromises in this regard.

I don't think that needs to be the case. I don't see any reason why these can't be made fairly accessible. But I am of course open to hearing about specific concerns.

Is this the best place to start discussing accessibility issues about these fill in the blank questions? If not, please let me know what you think would be best and I'll do it. I will warn you, this is not going to be a simple fix, so there will be plenty of discussion involved.

**Comment by moT01** [comment]
I think we are probably safe to merge this with the one failing test. Let me know if not and I will update the branch.

**Review by Sembauke — APPROVED** [review]

**Review by huyenltnguyen — APPROVED** [review]

**Pull request merged**
