### PR TITLE
Add correction to Waypoint - Sift through Text with Regular Expressions

### PR DESCRIPTION
**Pull request by abhisekp**
- Change information text
- Change regular expression
- Change code in editor
- Change assertion
### Details of Change
- The `+` in the regular expression `/and+/gi` matches `and`, `andd`, `anddd`, etc.
  **See:** https://regex101.com/r/vU6eF7/1 vs https://regex101.com/r/vU6eF7/2
- Explained correctly the instructions about using RegEx.
- Changed the assertion statements accordingly to match the expression written in the editor.

cc: @BerkeleyTrue

### CODE REVIEW

**Comment by BerkeleyTrue** [comment]
@abhisekp You don't need to tag me. I see every issue/PR.

**Comment by abhisekp** [comment]
@benmcmahon100 told me to tag you! :(

**Comment by abhisekp** [comment]
@benmcmahon100 I've updated the challenge with correct description and hints. 
I think it's ready for merge.

**Comment by benmcmahon100** [comment]
Can you change the ... to just . and then I'll merge it in

**Comment by abhisekp** [comment]
@benmcmahon100 i thought `...` looks nice. Ok. I'll change it as you say.

**Comment by abhisekp** [comment]
@benmcmahon100 ready for merge. :+1:

**Comment by abhisekp** [comment]
close PR #2365

**Pull request merged**
