### PR TITLE
Clarify output format for counting card Checkpoint

### LINKED ISSUE #5916: Challenge Checkpoint: Counting Cards Description
Challenge [Checkpoint: Counting Cards](http://www.freecodecamp.com/challenges/checkpoint-counting-cards#?solution=var%20count%20%3D%200%3B%0A%0Afunction%20cc(card)%20%7B%0A%20%20%2F%2F%20Only%20change%20code%20below%20this%20line%0A%20%20switch(card)%7B%0A%20%20%20%20case%202%3A%0A%20%20%20%20case%203%3A%0A%20%20%20%20case%204%3A%0A%20%20%20%20case%205%3A%0A%20%20%20%20case%206%3A%0A%20%20%20%20%20%20count%2B%2B%3B%0A%20%20%20%20%20%20break%3B%0A%20%20%20%20case%207%3A%0A%20%20%20%20case%208%3A%0A%20%20%20%20case%209%3A%0A%20%20%20%20%20%20break%3B%0A%20%20%20%20case%2010%3A%0A%20%20%20%20case%20'J'%3A%0A%20%20%20%20case%20'Q'%3A%0A%20%20%20%20case%20'K'%3A%0A%20%20%20%20case%20'A'%3A%0A%20%20%20%20%20%20count--%3B%0A%20%20%20%20%20%20break%3B%0A%20%20%7D%20%20%0A%20%20%0A%20%20if(count%3E0)%7B%0A%20%20%20%20return%20count%2B%22%20Bet%22%3B%0A%20%20%7D%0A%20%20if(count%3C%3D0)%7B%0A%20%20%20%20return%20count%2B%22%20Hold%22%3B%0A%20%20%7D%0A%20%20%2F%2F%20Only%20change%20code%20above%20this%20line%0A%7D%0A%0A%2F%2F%20Add%2Fremove%20calls%20to%20test%20your%20function.%0A%2F%2F%20Note%3A%20Only%20the%20last%20will%20display%0Acc(2)%3B%20cc(3)%3B%20cc(7)%3B%20cc('K')%3B%20cc('A')%3B%0A) has an issue.
User Agent is: <code>Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/47.0.2526.80 Safari/537.36</code>.
Please describe how to reproduce this issue, and include links to screenshots if possible.

My code:
```javascript
var count = 0;

function cc(card) {
  // Only change code below this line
  switch(card){
    case 2:
    case 3:
    case 4:
    case 5:
    case 6:
      count++;
      break;
    case 10:
    case 'J':
    case 'Q':
    case 'K':
    case 'A':
      count--;
      break;
    default:
      break;
  }  
  
  if(count>0){
    return count+" Bet";
  }
  return count+" Hold";
  // Only change code above this line
}

// Add/remove calls to test your function.
// Note: Only the last will display
cc(2); cc(3); cc(7); cc('K'); cc('A');

```

The problem is with description of the checkpoint they have asked us to return the count and the string 

There is no clear explanation saying that we need to return a variable by concatenating the count with `"Hold"` or `"Bet"`. 

You took the general assumption as the return var as string 

one could also say to return a array of variable like 

```javascript
  return [count,"Hold"];
  
  return [count,"Bet"];
```

So here the issue to fix is the description of the challenge

### PR DESCRIPTION
**Pull request by erictleung**
Closes #5916.

### CODE REVIEW

**Comment by bugron** [comment]
@erictleung thanks for posting this PR. What's the difference between https://github.com/FreeCodeCamp/FreeCodeCamp/pull/6015 and yours?

>***
>Please review the [**Guidelines for Contributing**](https://github.com/FreeCodeCamp/FreeCodeCamp/blob/staging/CONTRIBUTING.md), thank you!.
>***

**Comment by erictleung** [comment]
@bugron My PR tries to clarify description about the output needed to complete the challenge, as per #5916, which #6015 doesn't. 

On another note, I actually issued #6011, which is what #6015 fixes, but I was also in the middle writing up this PR (#6016) and noticed that there would be a merge conflict if I changed the code according to Issue #5916.

Most efficiently, I could close both issues (#6011 and #5916) with this PR. Let me know what works best.

**Comment by bugron** [comment]
OK, I'm going to QA and merge https://github.com/FreeCodeCamp/FreeCodeCamp/pull/6015, because it is created earlier then yours. That will cause merge conflicts and after you resolve them this PR will be ready to be QA'd.

**Comment by erictleung** [comment]
I've resolved the merge conflict and tested my changes locally as well.

**Comment by SaintPeter** [comment]
Looking good!  :+1:

**Pull request merged**
