### PR TITLE
refactor: simplify curriculum ordering

### PR DESCRIPTION
**Pull request by ojeytonwilliams**
- **refactor: collapse core curriculum**
- **refactor: build learn map with stageOrder**
- **fix: drop New curriculum if not showNewCurriculum**

Checklist:

- [x] I have read and followed the [contribution guidelines](https://contribute.freecodecamp.org).
- [x] I have read and followed the [how to open a pull request guide](https://contribute.freecodecamp.org/how-to-open-a-pull-request/).
- [x] My pull request targets the `main` branch of freeCodeCamp.
- [x] I have tested these changes either locally on my machine, or GitPod.

The superblock stages are basically the same, except that the first stage shows progress numbers and lines. That meant that I could simplify the rendering by just mapping over the stages.  Also, making the stage order explicit (an array) rather than implied allowed for a few more simplifications.

For production this is just a refactor, but if `SHOW_NEW_CURRICULUM` is true, then the client will try to render it (even if it's empty). The upshot of this being that you get an extra spacer and an empty heading. However, when we need the new curriculum it should be fine.

### CODE REVIEW

**Review by naomi-lgbt — APPROVED** [review]
This is kind of a nasty diff, but some *very* clean code!

**Comment by naomi-lgbt** [comment]
Confirmed that `SHOW_NEW_CURRICULUM` is false in our pipelines.

**Comment by ojeytonwilliams** [comment]
Thanks, Naomi!

**Review by moT01 — APPROVED** [review]
Much better 🥇

**Pull request merged**
