### PR TITLE
feat: refactor and test tools steps utilities

### LINKED ISSUE #41994: Tests for curriculum helpers
The curriculum helper scripts could use some tests.  A recent breaking change to https://github.com/williamkapke/bson-objectid stops the helpers working, but https://github.com/freeCodeCamp/freeCodeCamp/pull/41677 is green.

### PR DESCRIPTION
**Pull request by victor-duarte**
Checklist:

- [x] I have read [freeCodeCamp's contribution guidelines](https://contribute.freecodecamp.org).
- [x] My pull request has a descriptive title (not a vague title like `Update index.md`)
- [x] My pull request targets the `main` branch of freeCodeCamp.
- [x] I have tested these changes either locally on my machine, or GitPod.

Closes #41994

This PR is a refactor for the utilities and helpers used by the curriculums steps scripts.
**IMPORTANT:** The steps scripts output should have not been affected.

- Some methods were moved to individual files
  - Add checks in some methods but mostly these were not modified
  - Add tests to validate the expected output, did not consider edge cases since it seems the usage of the scripts are under a controlled environment
  - Add typescript type information files
  - `fs` was mocked for some tests with `mock-fs`. There is a consideration on the usage, Use `console.log()` before mocking the filesystem or use `process.stdout.write()` instead. There are issues when using `mock-fs` and `require`.`

*My apologies for the size of the PR.*

### CODE REVIEW

**Review by ojeytonwilliams — APPROVED** [review]
This is a great PR, @victor-duarte. Thanks for putting it together.  On a personal note, I didn't know about `mock-fs` - I'll definitely be using that in future.

LGTM :+1:

**Review by ShaunSHamilton — APPROVED** [review]
This LGTM :thumbsup: . 

**Not related to this PR**: Currently, the create-next-step does not work as it should; it does not remove `--fcc-editable-region--` from the seed, and I would expect it to use the solutions as the next seed.

**Comment by Nirajn2311** [comment]
> **Not related to this PR**: Currently, the create-next-step does not work as it should; it does not remove `--fcc-editable-region--` from the seed 
While I was creating the tests, I came upon this and investigated it further. I think I've found out the reason behind this bug, will edit in the cause of it here later tonight.

> I would expect it to use the solutions as the next seed.
Do you mean that it should copy the previous steps solution into the new step file? I had assumed that was how the command should've worked and went on with making the tests.

**Comment by ShaunSHamilton** [comment]
> Do you mean that it should copy the previous steps solution into the new step file?

Yes, if there is one.

**Pull request merged**
