### PR TITLE
Added the semicolon in the example provided

### PR DESCRIPTION
**Pull request by dev7060**
- [x] I have read [freeCodeCamp's contribution guidelines](https://github.com/freeCodeCamp/freeCodeCamp/blob/master/CONTRIBUTING.md).
- [x] My pull request has a descriptive title (not a vague title like `Update index.md`)
- [x] My pull request targets the `master` branch of freeCodeCamp.
- [x] None of my changes are plagiarized from another source without proper attribution.
- [x] All the files I changed are in the same world language (for example: only English changes, or only Chinese changes, etc.)
- [x] My changes do not use shortened URLs or affiliate links.

Closes #XXXXX

### CODE REVIEW

**Comment by Dharmin2108** [comment]
sdhkhd

**Comment by Dharmin2108** [comment]
dhkck

**Comment by Dharmin2108** [comment]
{"body":"jhfbk"}

**Comment by Dharmin2108** [comment]
hi

**Comment by Dharmin2108** [comment]
hd

**Review by RandellDawson — APPROVED** [review]
Trivial, but still valid.  LGTM

**Review by Manish-Giri — APPROVED** [review]
LGTM. Thank You for your contribution.

**Pull request merged**
