### PR TITLE
added some text to the challenge 08-coding-interview-questions

### LINKED ISSUE #12598: Symmetric Difference Algorithm not Testing for Symmetric Difference
While I understand that the challenge can come up with all sorts of rules, it is quite confusing since it really isn't testing for the _symmetric difference_ between all the given arrays.

Example: 
sym([1, 2, 5], [2, 3, 5], [3, 4, 5]) should return [1, 4, 5]

That isn't _"correct"_ since the actual symmetric difference among the 3 arrays should be [1,4].

On the challenge help, a link to a [youtube video](https://www.youtube.com/watch?v=PxffSUQRkG4) was provided. 

In the video, the following example was given:
A = [1,2,3,4]
B = [3,4,5,6]
C = [2,4,6,7]
And the symmetric difference between the 3 sets is [1,2,5,7]. Comparing with the answers expected from the challenge, which in this instance would be [1,4,5,7].

Once again, I know that the challenges can have its own rules to it. I just thought that I should point out this fact.

### PR DESCRIPTION
**Pull request by Syntactual**
#### Pre-Submission Checklist

- [x] Your pull request targets the `staging` branch of freeCodeCamp.
- [x] Branch starts with either `fix/`, `feature/`, or `translate/` (e.g. `fix/signin-issue`)
- [x] You have only one commit (if not, [squash](http://forum.freecodecamp.com/t/how-to-squash-multiple-commits-into-one-with-git/13231) them into one commit).
- [x] All new and existing tests pass the command `npm test`. Use `git commit --amend` to amend any fixes.

#### Type of Change

- [x] Small bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds new functionality)
- [ ] Breaking change (fix or feature that would change existing functionality)
- [ ] Add new translation (feature adding new translations)

#### Checklist:

- [x] Tested changes locally.
- [x] Closes currently open issue (replace XXXX with an issue no): Closes #12598

#### Description

Just changed the text on the challenge to match the new text from erictleung

Create a function that takes two or more arrays and returns an array of the iterative symmetric difference (△ or ⊕) of the provided arrays. In other words, start with the first array and keep on taking symmetric differences of each the following arrays after it.

### CODE REVIEW

**Comment by dhcodes** [comment]
@Syntactual why different accounts for this PR and the commit? I'm not even sure how you did that lol.

**Comment by Syntactual** [comment]
different accounts?

**Comment by Syntactual** [comment]
oh i see; same account just updated my profile

**Comment by Syntactual** [comment]
oh wow i just looked at that; i have no idea where that came from or how my commit came from that account; i am that person but i cloned using syntactual; i even committed to syntacual account; im sorry about that il have to take a look on my personal machine when i get home

**Comment by Syntactual** [comment]
only thing i can tell is im signed into git as joshopp at home so when i pushed the commit it was with that username not syntactual; but i did fork it to syntactual so my mistake

**Comment by Syntactual** [comment]
yeah i figured it out ; joshopp was my git account associated with my home machine; i deleted that account and will push my future commits with syntactual ; sorry for the confusion

**Comment by dhcodes** [comment]
@Syntactual no worries. **LGTM** :eagle: 🌱  🌮 . In the future if you would be so kind as to name your branch a little more descriptively like `fix/update-desc-symmetric-diff`, it'd be much appreciated. 

Thanks and congrats on your first contribution!

**Pull request merged**
