### PR TITLE
[Update-guide] Improved article

### PR DESCRIPTION
**Pull request by shreyas1599**
Added link of a hands-on tutorial which is a great way to learn more about Haskell.

- [x] I have read [freeCodeCamp's contribution guidelines](https://github.com/freeCodeCamp/freeCodeCamp/blob/master/CONTRIBUTING.md).
- [x] My pull request has a descriptive title (not a vague title like `Update index.md`)
- [x] My pull request targets the `master` branch of freeCodeCamp.
- [x] None of my changes are plagiarized from another source without proper attribution.
- [x] All the files I changed are in the same world language (for example: only English changes, or only Chinese changes, etc.)
- [x] My changes do not use shortened URLs or affiliate links.

### CODE REVIEW

**Comment by RandellDawson** [comment]
Thank you for opening this pull request.

This is a standard message notifying you that we’ve reviewed your pull request and have decided not to merge it. We would welcome future pull requests from you.

**Reason:** We do not accept PRs which **only** add links when there are already valid reference links for the article.  Instead of just adding a link, it would be great if you can add original content. Paraphrased content from another source should be referenced.

Thank you and happy coding.

**Comment by shreyas1599** [comment]
@RandellDawson The link was not a reference but more of a tutorial to get acquainted with the language. It was not easy for me to find a practical tutorial for haskell and after a bit of digging this is what was I found and it was indeed helpful. I thought it would help others.

**Comment by RandellDawson** [comment]
> If you want me to add a description of why one should use this as a reference I can do that.

How about adding some more general content to the Haskell article in general?

**Comment by shreyas1599** [comment]
@RandellDawson Sure! Will do. Thanks. I'll have to post a comment here once I'm done, right? (Apologies, I'm new to this.)

**Comment by shreyas1599** [comment]
@RandellDawson I have improved the article as suggested.

**Review by RandellDawson — APPROVED** [review]

**Comment by RandellDawson** [comment]
Congrats @shreyas1599 on your first pull request (PR)! 🎉

Thank you for your contribution to the page! 👍
We're happy to accept these changes, and look forward to future contributions. 📝

**Pull request merged**
