### PR TITLE
fix(donate): quick patch for auth

### LINKED ISSUE #37617: freecodecamp.org/donate should explain it is a donate page, even for unauthenticated users
Currently, when an unauthenticated user visits https://freecodecamp.org/donate, it shows a sign-in page with no indication it is a donate page.

It would be a better user experience if there was a message at the top of the page saying it was a donate page and explaining why authentication is necessary. With no message about this, users could assume that they are at the wrong page to donate or there is an error happening.

### LINKED ISSUE #37626: Stripe Scripts for the donation modal should not load before donation modal opens.
Stripe scripts only load for the lesson donation modal and the donation page.
However, the scripts for the donation modal loads before the donation modal opens.

Screen Shot 2019-10-31 at 10 33 05 AM

here would be a good place to start the investigation.
https://github.com/freeCodeCamp/freeCodeCamp/blob/3a2db6f090821fd0bff8c7258283050552046417/client/src/components/Donation/components/DonateModal.js

### PR DESCRIPTION
**Pull request by raisedadead**
Closes #37617
Closes #37626

### CODE REVIEW

**Review by raisedadead — COMMENTED** [review]
Please rebase and merge, I need to drop the last commit on this PR when #37689 is ready

**Comment by ahmadabdolsaheb** [comment]
should the showdonationselector also go away?
https://github.com/freeCodeCamp/freeCodeCamp/blob/9fb9ce3085585287516def3c519e82f3575619be/client/src/redux/index.js#L148

**Comment by raisedadead** [comment]
> should the showdonationselector also go away?

No, I thought of removing it but then figured out we could use the same logic and implement https://github.com/freeCodeCamp/freeCodeCamp/issues/37143. 

We may ofcourse rename it then

**Review by raisedadead — COMMENTED** [review]
Reviwed with @QuincyLarson

**Pull request merged**
