### PR TITLE
Fix 'npm run only-once' command on Windows

### PR DESCRIPTION
**Pull request by systimotic**
#### Pre-Submission Checklist

- [x] Your pull request targets the `staging` branch of FreeCodeCamp.
- [x] Branch starts with either `fix/`, `feature/`, or `translate/` (e.g. `fix/signin-issue`)
- [x] You have only one commit (if not, [squash](http://forum.freecodecamp.com/t/how-to-squash-multiple-commits-into-one-with-git/13231) them into one commit).
- [x] All new and existing tests pass the command `npm run test-challenges`. Use `git commit --amend` to amend any fixes.
#### Type of Change

- [x] Small bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds new functionality)
- [ ] Breaking change (fix or feature that would change existing functionality)
- [ ] Add new translation (feature adding new translations)
#### Checklist:

- [x] Tested changes locally.
- [ ] Closes currently open issue (replace XXXX with an issue no): Closes #XXXX
#### Description

I've started contributing to FreeCodeCamp about a week ago. When I started contributing, I also joined the Contributors chat room. From my own experience and the experience of many other new contributors, I've found there's an issue in the `npm run only-once` command. `\n` on Windows doesn't add a new line. In fact, it's even worse. In the script, it seems to break. This pull request removes the new lines. I realize that this does make these little messages harder to catch. I think the trade-off is worth it, though. Because there is no new output for a while after the first message, and the last message is the very last thing logged, they're still hard to miss. I did some research on getting newlines in the command line on Windows, but there doesn't seem to be an easy cross-platform solution.  
I hope this will help out new contributors, taking one more bump out of the road of contributing to a large open source project. 🔥

### CODE REVIEW

**Comment by BerkeleyTrue** [comment]
Does `echo 'foo' && echo 'foo'` on windows print

```
foofoo
```
or
```
foo
foo
```
?

**Comment by systimotic** [comment]
Hey @BerkeleyTrue! 
cmd_2016-10-13_14-37-31
That's what that looks like on Windows. Here's the output of `npm run only-once` on Windows before the change:
firefox_2016-10-13_14-40-18
This is the output after the change:
```
C:\Users\Timo\dev\FreeCodeCamp>npm run only-once

> freecodecamp@0.1.0 only-once C:\Users\Timo\dev\FreeCodeCamp
> npm run create-rev && echo 'seeding database' && node seed && echo 'Seeding Completed'


> freecodecamp@0.1.0 create-rev C:\Users\Timo\dev\FreeCodeCamp
> node -e "var fs = require('fs'); fs.access('./server/rev-manifest.json', function(err) { if (err) { console.log('\n\ncreating manifest\n\n'); return fs.writeFileSync('server/rev-manifest.json', '{}'); } console.log('\n\nrev-manifest present\n\n'); });"



rev-manifest present


'seeding database'
parsed Join the Free Code Camp Community successfully
(...)
parsed Mock Interviews successfully
successfully created Join the Free Code Camp Community block
(...)
successfully created Mock Interviews block
join-the-free-code-camp-community successfully saved
(...)
coding-interview-training successfully saved
challenge seed completed
'Seeding Completed'

C:\Users\Timo\dev\FreeCodeCamp>
```

**Comment by BerkeleyTrue** [comment]
Cool. Can we add some visual dividers? 

```
"scripts": {
    "only-once": "npm run create-rev && echo '/****/' && echo 'seeding database' && echo '/****/' && node seed && echo '/****/' && echo 'Seeding Completed'" && echo '/****/'
}
```

**Comment by systimotic** [comment]
Sure thing! New output looks like this:
```
[default script stuff here]


rev-manifest present


'/****/'
'Seeding Database'
'/****/'
parsed Join the Free Code Camp Community successfully
(...)
parsed Mock Interviews successfully
successfully created Join the Free Code Camp Community block
(...)
successfully created Mock Interviews block
join-the-free-code-camp-community successfully saved
(...)
coding-interview-training successfully saved
challenge seed completed
'/****/'
'Seeding Completed'
'/****/'
```
I made the casing consistent while I was at it as well.

**Comment by Bouncey** [comment]
Windows users to test and QA?

@raisedadead @dhcodes ??

**Comment by dhcodes** [comment]
I won't be able to test this on Windows until Monday.

**Comment by atjonathan** [comment]
Testing now.

**Review by ghost — APPROVED** [review]
#### LGTM 👍

Thanks @systimotic for this improvement!

**Pull request merged**
