### PR TITLE
Fixed issue with accessibility challenge about accesskeys

### LINKED ISSUE #17495: Fix content on Applied accessibility
I recommend checking the following content to analyse if this should be fixed (I’m using Chrome on Windows):

On the page[ Applied Accessibility - Avoid Colorblindness Issues by Using Sufficient Contrast](https://forum.freecodecamp.org/clicks/track?url=https%3A%2F%2Flearn.freecodecamp.org%2Fresponsive-web-design%2Fapplied-accessibility%2Favoid-colorblindness-issues-by-using-sufficient-contrast&post_id=436010&topic_id=197853) the text separates two types of colors: darker and lighter colors, being blue, violet, magenta and red the former, and green, yellow, orange, blue-green the latter. I don’t think this information is accurate. All hues have darker and lighter tones, tints and shades. The author of the text was probably trying to talk about warm and cold colors, being green, yellow and red the former, and violet and blue the latter. See the following image: http://www.aridglamor.com/wp-content/uploads/2014/03/tintsshades.jpg

On the page [Make Links Navigatable with HTML Access Keys](https://forum.freecodecamp.org/clicks/track?url=https%3A%2F%2Flearn.freecodecamp.org%2Fresponsive-web-design%2Fapplied-accessibility%2Fmake-links-navigatable-with-html-access-keys&post_id=436010&topic_id=197853) the text says that we should use the accesskey to use the keys to go direct to the element with the accesskey attribute, but it doesn’t say that we should type ALT + key (windows) to make it work. For exemple, a tag with the attribute accesskey=“a” will only work if you type ALT + a. I think this information should be added to the page. For more accurate information about the correct shortcut key to access this property, see this link: https://www.w3schools.com/tags/att_global_accesskey.asp

On the page [Applied Accessibility - Use tabindex to Specify the Order of Keyboard Focus for Several Elements](https://forum.freecodecamp.org/clicks/track?url=https%3A%2F%2Flearn.freecodecamp.org%2Fresponsive-web-design%2Fapplied-accessibility%2Fuse-tabindex-to-specify-the-order-of-keyboard-focus-for-several-elements&post_id=436010&topic_id=197853) the text says that if we use the attribute tabindex with the value of any positive numbers like 1, 2, 3, etc, the tab will first follow the order of these elements, and after this, they go the the other elements. This is not true, it doesn’t happen. Any value in the tabindex attribute that is different from 0, be it positive or negative, will make the tab jump over the element and ignore it. This is what happened to me using chrome on windows.

Bug on the last page of [Responsive Web Design - Make typography responsive](https://learn.freecodecamp.org/responsive-web-design/responsive-web-design-principles/make-typography-responsive)
After finishing the challenge, the page fails in trying to open the next challenge, which is the first page of the CSS Flexbox. Weirdly, the url of the adressbar of the browser changes to the url of the flexbox introduction page, but we remain in the Make Typography Responsive page.

### LINKED ISSUE #17945: right answer not accepted
https://learn.freecodecamp.org/javascript-algorithms-and-data-structures/intermediate-algorithm-scripting/arguments-optional

my answer:
works fine in chrome v8.   

    var args=[]
    function addTogether() {
      args = args.concat(Array.from(arguments))
        
      return args.length == 1 ? 
        addTogether: 
        args.some(n => typeof n !== 'number') ?
            undefined:
            args[0]+args[1]
    
    }

### PR DESCRIPTION
**Pull request by thecodingaviator**
- [x] I have read [freeCodeCamp's contribution guidelines](https://github.com/freeCodeCamp/freeCodeCamp/blob/master/CONTRIBUTING.md).
- [x] My pull request has a descriptive title (not a vague title like `Update index.md`)
- [x] My pull request targets the `master` branch of freeCodeCamp.
- [x] None of my changes are plagiarized from another source without proper attribution.
- [x] My article does not contain shortened URLs or affiliate links.

Partly fixes #17495

### CODE REVIEW

**Comment by ezioda004** [comment]
@thecodingaviator How does it fix that issue? The issue is about algorithm and you're adding a note.
Also, don't add links to w3schools.

**Comment by thecodingaviator** [comment]
@ezioda004 

I think I’ve put the wrong issue no on this one, I’ll check it in some time. As far as the link is concerned, I can make a table in the challenge about this but wouldn’t that hag up a lot of space on the contents?

**Comment by thecodingaviator** [comment]
@ezioda004 The issue no has been corrected

**Comment by ezioda004** [comment]
@thecodingaviator You can certainly add a reference to some other website (preferably wikipedia, MDN). We avoid w3schools because its unreliable and often has incomplete or incorrect information.

**Comment by thecodingaviator** [comment]
@ezioda004 done

**Comment by thecodingaviator** [comment]
@ezioda004

**Comment by moT01** [comment]
Thank you for your PR, but we don’t use outbound links in challenge instructions see the [challenge style guide](https://github.com/freeCodeCamp/freeCodeCamp/blob/master/docs/style-guide-for-curriculum-challenges.md) for more details.

Thanks and happy coding!

**Pull request closed without merging**
