### PR TITLE
fix(seed): Fixed issue with approximately always failing

### LINKED ISSUE #16665: Test if a Value Falls within a Specific Range - always fails
#### Test if a Value Falls within a Specific Range 

https://beta.freecodecamp.org/en/challenges/quality-assurance-and-testing-with-chai/test-if-a-value-falls-within-a-specific-range

#### Issue Description
The test always fails. It appears that there are two problems in /freeCodeCamp/seed/challenges/06-information-security-and-quality-assurance/quality-assurance-and-testing-with-chai.json:

1. Test is checking unit test No. 10 but it should be No. 9 : 
```
 "title": "Test if a Value Falls within a Specific Range",
...
...
"testString": "getUserInput => $.get(getUserInput('url') + '/_api/get-tests?type=unit&n=10')
... 
```

Here are the results to the get-tests glitch api, both with `unit&n=9` and `unit&n=10` query strings.

`https://honeysuckle-crime.glitch.me/_api/get-tests?type=unit&n=10`

```
{"title":"#isArray, #isNotArray","context":"Unit Tests -> Arrays","state":"failed","assertions":[{"method":"fail","args":["'isThisAnArray?'.split('')","'String.prototype.split() returns an Array'"]},{"method":"fail","args":["[1,2,3].indexOf(2)","'indexOf returns a number.'"]}]}
```

`https://honeysuckle-crime.glitch.me/_api/get-tests?type=unit&n=9`

```
{"title":"#isApproximately","context":"Unit Tests -> Comparisons","state":"passed","assertions":[{"method":"approximately","args":["weirdNumbers(0.5)","1","0.5"]},{"method":"approximately","args":["weirdNumbers(0.2)","1","0.8"]}]}
```

No. 10 is for the next challenge ( Test if Value is An Array )

2) Test is checking for the assertion method "isApproximately" but it should be "approximately"

          `{  assert.equal(data.assertions[1].method, 'isApproximately'); ` 

#### Screenshot

image

I would be happy to tackle this one if FreeCodeCamp team agrees this is an issue.

Thank you.

### PR DESCRIPTION
**Pull request by Brybro**
#### Pre-Submission Checklist

- [x] Your pull request targets the `staging` branch of freeCodeCamp.
- [x] Branch starts with either `fix/`, `feature/`, or `translate/` (e.g. `fix/signin-issue`)
- [x] You have only one commit (if not, [squash](http://forum.freecodecamp.org/t/how-to-squash-multiple-commits-into-one-with-git/13231) them into one commit).
- [x] All new and existing tests pass the command `npm test`. Use `git commit --amend` to amend any fixes.

#### Type of Change

- [x] Small bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds new functionality)
- [ ] Breaking change (fix or feature that would change existing functionality)
- [ ] Add new translation (feature adding new translations)

#### Checklist:

- [x] Tested changes locally.
- [x] Addressed currently open issue (replace XXXXX with an issue no in next line)

Closes #16665

#### Description
Fixed seed to ensure tests pass when a value falls within a specific range using the assert.approximately method.

### CODE REVIEW

**Comment by Brybro** [comment]
Just to note, there is a typo in the Glitch starter project.  For this "approximately" test, the first assert statement is misspelled.  It is "assert.approximatey" and should be "assert.approximately".  I am not sure where this gets changed.

**Comment by mstellaluna** [comment]
I am currently working on this PR

**Comment by mstellaluna** [comment]
There is only one issue with this PR and it is on line 105 of the test/1_unit-tests.js file.  assert.approximatey is misspelled as mentioned above. it will cause only 1 of 3 tests to pass. if you manually correct the spelling mistakes, all 3 tests pass with the code below. not sure where this is corrected.

`test('#isApproximately', function() {
      assert.approximately(weirdNumbers(0.5) , 1, /*edit this*/ 0.5 );
      assert.approximately(weirdNumbers(0.2) , 1, /*edit this*/ 0.8 );
    });`

**Comment by Em-Ant** [comment]
Hi, guys. Quincy asked me to have a look at this.

I checked the updated code in the PR and it works. I use the l glitch project that me and Samuel used to develop these challenges as a quick tester. If you need it it's this https://narrow-plane.glitch.me/, you can 'test' the test.

I think the code in the PR can be merged, but according to the contributing guide the the commits should be squeezed into one. @Brybro why there are 3 commits here ?

**Comment by mstellaluna** [comment]
@Em-Ant I agree the PR fixes the issue. I am just concerned about the typo that shows up that I mentioned above

**Comment by Em-Ant** [comment]
@mstellaluna I have access to the boilerplates, and I just fixed the typo in glitch. Unfortunately that's not enough, because currently the new projects are cloned from https://github.com/freeCodeCamp/boilerplate-mochachai . I'll open a PR to that repo with the fix for the typo, and I will let you know when it's ready.

**Comment by mstellaluna** [comment]
@em-ant thank you :)

**Review by mstellaluna — APPROVED** [review]
LGTM

**Comment by mstellaluna** [comment]
as per @QuincyLarson will push through this PR while we wait for the boilerplate typo is corrected.

**Comment by Myrmidonut** [comment]
The typo for "approximately" hasn't been merged yet. The merge still has to get approved or is there some other requirement we are waiting for?

**Pull request merged**
