### PR TITLE
feat(client): reimplement the DangerZone on Settings Page

### LINKED ISSUE #35242: Reimplement the Danger Zone on the setting page
The Danger Zone is missing on the settings page. It should be a clone of what we have in production.

### PR DESCRIPTION
**Pull request by hemakshis**
- [x] I have read [freeCodeCamp's contribution guidelines](https://github.com/freeCodeCamp/freeCodeCamp/blob/master/CONTRIBUTING.md).
- [x] My pull request has a descriptive title (not a vague title like `Update index.md`)
- [x] My pull request targets the `master` branch of freeCodeCamp.
- [x] None of my changes are plagiarized from another source without proper attribution.
- [x] All the files I changed are in the same world language (for example: only English changes, or only Chinese changes, etc.)
- [x] My changes do not use shortened URLs or affiliate links.

Closes #35242

### CODE REVIEW

**Comment by hemakshis** [comment]
I have some doubts regarding the implementation of actions in the redux folder.
Would be glad if someone could help me out in this. :)

**Comment by raisedadead** [comment]
Thanks for the PR. 

The components are here:
https://github.com/freeCodeCamp/freeCodeCamp/tree/production/common/app/routes/Settings

Actions are here:
https://github.com/freeCodeCamp/freeCodeCamp/tree/production/common/app/routes/Settings/redux

@Bouncey and @ValeraS should be able to guide you further.

**Comment by hemakshis** [comment]
Hi @raisedadead, thank you for the pointers!
My question is should I create new saga for the DangerZone or add them in the existing saga?

**Comment by Bouncey** [comment]
Hi @hemakshis the new saga would be lovely, thank you.

You can reference the existing [epic on master](https://github.com/freeCodeCamp/freeCodeCamp/blob/production/common/app/routes/Settings/redux/danger-zone-epic.js).

**Comment by hemakshis** [comment]
Hi @Bouncey, the danger zone in production uses something like [`getState().app`](https://github.com/freeCodeCamp/freeCodeCamp/blob/production/common/app/routes/Settings/redux/danger-zone-epic.js#L17). I can't find anything like that while working on it. I do get a `payload.getModifierState()` and it returns a boolean of `false`.
Could you please tell what should the payload look like what function to call?

**Comment by hemakshis** [comment]
Hi @Bouncey, can you please guide me on how the url for delete request would look like and what should be passed as a parameter to the back-end?

Thank you!

**Comment by raisedadead** [comment]
Hi @hemakshis I have gone ahead and resolved the merge conflicts and pushed a bit of styling changes while I was at it.

@Bouncey if you could guide them with the endpoints that they need, we are good to go, further? This is a critpath for beta.

**Comment by hemakshis** [comment]
Hi @raisedadead thanks! also, sorry about those silly mistakes I was gonna resolve a few of them in the next commit :)

**Comment by Bouncey** [comment]
These are the endpoints you need to hit:
https://github.com/freeCodeCamp/freeCodeCamp/blob/06311a56f629a9b83070286adeb929b68fd7e1a3/api-server/server/boot/user.js#L29-L30

Follow this pattern to create the requests:
https://github.com/freeCodeCamp/freeCodeCamp/blob/06311a56f629a9b83070286adeb929b68fd7e1a3/client/src/utils/ajax.js#L47-L51

The request handlers do not expect anything in the request body.

**Comment by raisedadead** [comment]
> [...] sorry about those silly mistakes I was gonna resolve a few of them in the next commit

You don't need to apologise. We should be sorry for being pushy. Normally we do not rush any contributions.  But, this feature is an showstopper requirement for the our next major release.

Thanks a lot for all your help.

**Comment by raisedadead** [comment]
Hi I guess, my commit was overwritten. Do not worry we will take care of fixing up this PR when we land this.

**Comment by hemakshis** [comment]
Hi @raisedadead, I am really sorry but I am not good at handling merge conflicts. I really don't have much experience with such cases. :disappointed:

**Review by Bouncey — APPROVED** [review]
Nice work @hemakshis 👍 

Thank you

**Comment by raisedadead** [comment]
> I am not good at handling merge conflicts.

Do not worry, this repo is massive with a really fast updates to the git history. 
I would not blame you.

I do not mean to scare you, buy here is what happened (probably).

1. You already had the branch on your local which had divulged from master (because master moved ahead on the same files) => `feat: added danger zone`.
  This is fine and normal. Happens all the time and a `rebase` should have fixed it.
2. So, I updated your remote branch (on GitHub) resolving conflicts and changed the branch's history with an additional commit. => `fix: apply conventional styling changes`
3. You had more changes on you local. => `feat: added danger-zone-saga.js`
4. Here is where `2` and `3` divulged. Normally a simple git pull would have fixed it. **Normally.**
5. **But**, I am assuming you had attempted either a `rebase` or a `merge`, before the pull. So it go a bit messy.

Here is the daunting way to fix this complex merge: 

Make a backup/temporary branch off of your local branch. Delete the original local branch. Pull down the remote (which is in a clean state). Cherry-pick the commits that you need on the fresh branch from your local backup/temporary copy.

I know it's daunting, when you are starting. But trust me we have been there. Do not worry about it. At the end of the day its git and as daunting as it maybe, it's going to work out.

--

We have updated this PR with a few additional things that we wanted and thought would be simper to add on this PR. You can follow the commits, to see what went in. 

Thanks a lot for working on this and contributing to the codebase for the first time. 
Nice work.

**Review by raisedadead — APPROVED** [review]
#### :sparkles: :sparkles: **AWESOME! LGTM.** :sparkles: :sparkles: 

Thanks @hemakshis, for this pull request and contributing to the code-base for the first time.
We will be looking forward for more contributions in future.

Cheers and happy contributing!

**Review by raisedadead — APPROVED** [review]
#### :sparkles: :sparkles: **AWESOME! LGTM.** :sparkles: :sparkles: 

Thanks @hemakshis, for this pull request and contributing to the code-base for the first time.
We will be looking forward for more contributions in future.

Cheers and happy contributing!

**Pull request merged**
