### PR TITLE
refactor(client): turn image validation component into subComponent

### PR DESCRIPTION
**Pull request by Sboonny**
Checklist:

- [x] I have read and followed the [contribution guidelines](https://contribute.freecodecamp.org).
- [x] I have read and followed the [how to open a pull request guide](https://contribute.freecodecamp.org/#/how-to-open-a-pull-request).
- [x] My pull request targets the `main` branch of freeCodeCamp.
- [x] I have tested these changes either locally on my machine, or GitPod.

FormGroup components were acting as `div` with `margin-bottom`, and using them were weird without `validationState`

If this is an acceptable way to clear them, I will copy what Bruce did in #49142, and add a code similar to the one below to 

```ts
<Grid
              role='group'
              aria-label={t('settings.headings.personal-info')}
            >
<ControlLabel htmlFor></ControlLabel>
<FormInput id></FormInput>
</Grid>
```

### CODE REVIEW

**Comment by Sboonny** [comment]
> Removing the div wrapper around each label/input won't affect the underlying accessibility at all.

True, I was referring to adding `role=group` and `aria-labels` to the places missing them. 

I am removing the div, because extra diva can make it harder for newer developers to create layout, whether flex or grid.

This purely based on my experience with chapter, and how much I broke the layout because I followed the docs, because I didn't know better, and added element without the need to, which broke the layout for a while.

**Comment by Sboonny** [comment]
> > But visually I think some works needs to be done so that the label is closer to its input.

> True, this should be better 👍

While trying to do this, I needed to add `div` back, and the result turn into a formGroup but without validationState logic added. Although it's fine, this isn't the originial attend by making the are cleaner and less bloated. I will wait for tailwind or sass to be added to the codebase then comeback to remove this bloating divs.

**Review by moT01 — APPROVED** [review]
This LGTM 🎉 

Unless I'm missing something - I'm not sure what the `closeLabel` is for since there isn't a close button on that alert. We could probably remove it. It was pre-existing so I don't mind leaving it.

**Comment by Sboonny** [comment]
Yeab, you are right. there is no dismissable, so the text is flowing and won't render

https://github.com/react-bootstrap/react-bootstrap/blob/v0.33.1/src/Alert.js#L41

---

Funny, I tried to look at our component to see how the Alert works, but it wasn't there. Your catch will make me update the Alert component, maybe update its type to warn about the need for `onDismiss` as well 👍. Nice catch

**Review by Sembauke — APPROVED** [review]

**Pull request merged**
