### PR TITLE
feat(curriculum): implement bubble sort algorithm with performance tr…

### PR DESCRIPTION
**Pull request by dineshkottaKota**
…acking

This commit implements the bubble sort algorithm to sort an array of integers in ascending order. The algorithm iterates through the array multiple times, comparing adjacent elements and swapping them if they are out of order. The implementation includes performance tracking by counting the number of iterations, which helps analyze the algorithm's efficiency. The code avoids using the built-in `.sort()` method to ensure the bubble sort logic is correctly demonstrated. 

Additionally, the solution uses array destructuring for cleaner swap operations and incorporates an early exit mechanism to improve performance when the array is already sorted.

Checklist:

- [x] I have read and followed the [contribution guidelines](https://contribute.freecodecamp.org).
- [x] I have read and followed the [how to open a pull request guide](https://contribute.freecodecamp.org/how-to-open-a-pull-request/).
- [x] My pull request targets the `main` branch of freeCodeCamp.
- [x] I have tested these changes either locally on my machine, or GitPod.

Closes #XXXXX

### CODE REVIEW

**Comment by dineshkottaKota** [comment]
> this solution is not user-facing, what benefits there are in implementing it?

It encourages learners to analyse time complexity and see why bubble sort is less efficient than other sorting methods.

**Comment by dineshkottaKota** [comment]
Mam please consider my pull request. I had  replied to you in github.

**Comment by gikf** [comment]
Hey

Thank you for opening this pull request.

This is a standard message notifying you that we've reviewed your pull request and have decided not to merge it. We would welcome future pull requests from you.

Thank you and happy coding.

- - -

Note for future - it is recommended to make changes on a separate branch, rather than the `main` branch. See more about it in point 3 at https://contribute.freecodecamp.org/how-to-contribute-to-the-codebase/#contributing-to-the-codebase.

**Comment by ilenia-magoni** [comment]
> It encourages learners

it doesn't, the solution is not shown to campers. I recommend checking your changes in your local instance.

**Pull request closed without merging**
