### PR TITLE
Added solution to Use grid-area Without Creating an Areas Template

### PR DESCRIPTION
**Pull request by thecodingaviator**
- [x] I have read [freeCodeCamp's contribution guidelines](https://github.com/freeCodeCamp/freeCodeCamp/blob/master/CONTRIBUTING.md).
- [x] My pull request has a descriptive title (not a vague title like `Update index.md`)
- [x] My pull request targets the `master` branch of freeCodeCamp.
- [x] None of my changes are plagiarized from another source without proper attribution.
- [x] All the files I changed are in the same world language (for example: only English changes, or only Chinese changes, etc.)
- [x] My changes do not use shortened URLs or affiliate links.

Closes #XXXXX

### CODE REVIEW

**Comment by RandellDawson** [comment]
Make sure your solutions always include the entire code used in the challenge and not just the code to add.

**Comment by thecodingaviator** [comment]
Even the HTML parts? @RandellDawson

**Comment by RandellDawson** [comment]
@thecodingaviator Yeah.  The idea is that someone should be able to copy/paste the entire solution into the editor and it pass the tests.  There are many challenges, which have multiple parts where users need to insert their own code (i.e. React challenges).  It just makes it simpler to put the entire solution into the guide.  My only wish is we could make it a standard practice to use detail/summary tags for the solutions, so the user has to take a 2nd step to see.  If they click on the Get a Hint link from the forum and all they want to see is some hints and not the full solution, they should be able to do that.

**Comment by thecodingaviator** [comment]
Alright @RandellDawson , I'm making some changes, tell me if they're fine or something needs to be changed

**Review by RandellDawson — APPROVED** [review]
LGTM

**Comment by RandellDawson** [comment]
Thank you for your contribution to the page! 👍
We're happy to accept these changes, and look forward to future contributions. 🎉

**Pull request merged**
