### PR TITLE
Improve code block formatting in "Add Axes to a Visualization"

### PR DESCRIPTION
**Pull request by TyMick**
Checklist:

- [x] I have read [freeCodeCamp's contribution guidelines](https://contribute.freecodecamp.org).
- [x] My pull request has a descriptive title (not a vague title like `Update index.md`)
- [x] My pull request targets the `master` branch of freeCodeCamp.
- [x] All the files I changed are in the same world language, for example: only English changes, or only Chinese changes, etc.

I figured, since `const xAxis = d3.axisBottom(xScale);` is already on a line by itself, I may as well add block formatting to it.

### CODE REVIEW

**Review by huyenltnguyen — DISMISSED** [review]
LGTM 👍

**Review by huyenltnguyen — COMMENTED** [review]
Hi @tywmick, your PR looks good to me, but I just realized you have another open PR targeting the same file. I think it's better to merge the changes into one PR to reduce the noise and speed up the reviewing process. I guess we could close this one and cherry-pick this commit into https://github.com/freeCodeCamp/freeCodeCamp/pull/39261. What do you think?

**Comment by tywmick** [comment]
@huyenltnguyen Sounds good, I'll get on it!

**Comment by tywmick** [comment]
Alright, moved it on over. 👍🏼

**Pull request closed without merging**
