### PR TITLE
fix: Restore missing emojis and fix broken links

### PR DESCRIPTION
**Pull request by ojeytonwilliams**
- [x] I have read [freeCodeCamp's contribution guidelines](https://github.com/freeCodeCamp/freeCodeCamp/blob/master/CONTRIBUTING.md).
- [x] My pull request has a descriptive title (not a vague title like `Update index.md`)
- [x] My pull request targets the `master` branch of freeCodeCamp.
- [x] None of my changes are plagiarized from another source without proper attribution.
- [x] All the files I changed are in the same world language (for example: only English changes, or only Chinese changes, etc.)
- [x] My changes do not use shortened URLs or affiliate links.

While reviewing #34946 I noticed that some emojis were not displaying correctly.  This PR fixes that and updates some broken links.  

One of the emoji's, :bowtie:, is not part of the freeCodeCamp forum emoji set.  I replaced this with :computer:, since that seemed like a reasonable emoji to pair with "Happy Coding".

### CODE REVIEW

**Review by thecodingaviator — DISMISSED** [review]
I'd suggest you to do the other way, remove all emoticons.

https://github.com/freeCodeCamp/freeCodeCamp/blob/master/docs/style-guide-for-guide-articles.md#images states:
`Don't use emojis or emoticons in the Guide. freeCodeCamp has a global community, and the cultural meaning of an emoji or emoticon may be different around the world. Also, emojis can render differently on different systems.`

**Comment by RandellDawson** [comment]
@thecodingaviator I told @ojeytonwilliams it was fine to make this fix on this PR.  However, I do agree that we should probably add this discussion about removing the emojis and icons from all of the curriculum-related Guide articles on issue #35453.

**Comment by ojeytonwilliams** [comment]
@thecodingaviator @RandellDawson I went ahead and removed the emojis anyway - that is what the style guide says, after all.

There are another 151 files with them, however.  Is it better to be consistent with those files or get started removing them?

**Comment by RandellDawson** [comment]
> Reason being, there are another 151 files with emojis. Many of them have the same form (hints and so on) as the certification pages I changed. Is it better to be consistent with those files or get started by removing the emojis here?

@ojeytonwilliams Are you thinking about removing all the emojis with this PR?  I am OK with it, but I was kind of hoping any mass change we make to the curriculum-related Guide articles would be decided upon in the issue #35453 so we can do everything in one shot, but that is just my opinion.

Regarding the 151 files you mention, is that only in the certifications folder in each language or across the entire repo?

**Comment by ojeytonwilliams** [comment]
@RandellDawson I would favour reinstating the emojis with this PR (i.e. I roll it back to my first commit) and then remove them all en masse after #35453 has settled.  That way we're more likely to end up with consistency across the guide articles.

In hindsight, I should have just opened an issue to avoid repairing the emojis and then removing them, but at least we have options.

**Review by thecodingaviator — COMMENTED** [review]
LGTM now if you want to go for just these 6 files

**Comment by RandellDawson** [comment]
Thank you for your contribution to the page! 👍
We're happy to accept these changes, and look forward to future contributions. 🎉

**Pull request merged**
