### PR TITLE
Fixing error in data structure description

### LINKED ISSUE #14843: Error in description of max heap challenge
Challenge [insert-an-element-into-a-max-heap](http://beta.freecodecamp.com/en/challenges/coding-interview-data-structure-questions/insert-an-element-into-a-max-heap) has an issue.
User Agent is: <code>Mozilla/5.0 (X11; CrOS x86_64 9000.82.0) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/56.0.2924.87 Safari/537.36</code>.
Please describe how to reproduce this issue, and include links to screenshots if possible.

Here is some text from the description text of this challenge: 
> For instance, consider this array representation of a binary max heap:
> [ 6, 22, 30, 37, 63, 48, 42, 76 ]
> The root node is the first element, 6.

I'm almost postitve that that is a representation of a binary **min** heap, not a binary _max_ heap. Since this challenge is about binary max heaps, I think the array should be changed to:
[ 76, 63, 48, 42, 37, 6, 42, 22 ]

Am I OK to make the update myself? (Assuming I can figure out where to update at. I'm new to this. )

### PR DESCRIPTION
**Pull request by beaucarnes**
Referenced in https://github.com/freeCodeCamp/freeCodeCamp/issues/14843

#### Pre-Submission Checklist

- [x] Your pull request targets the `staging` branch of freeCodeCamp.
- [ ] Branch starts with either `fix/`, `feature/`, or `translate/` (e.g. `fix/signin-issue`)
- [x] You have only one commit (if not, [squash](http://forum.freecodecamp.com/t/how-to-squash-multiple-commits-into-one-with-git/13231) them into one commit).
- [ ] All new and existing tests pass the command `npm test`. Use `git commit --amend` to amend any fixes.

#### Type of Change

- [x] Small bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds new functionality)
- [ ] Breaking change (fix or feature that would change existing functionality)
- [ ] Add new translation (feature adding new translations)

#### Checklist:

- [ ] Tested changes locally.
- [x] Closes currently open issue (replace XXXX with an issue no): Closes #14843

### CODE REVIEW

**Comment by beaucarnes** [comment]
See https://github.com/freeCodeCamp/freeCodeCamp/issues/14843

**Comment by beaucarnes** [comment]
I knew I was naming my branch wrong but I couldn't figure out how to fix it. I know how to create a branch name through CLI but I was just editing right on GitHub. How do I set my branch name when I'm editing on GitHub?

**Comment by raisedadead** [comment]
Hey, @beaucarnes Thanks for the pull request. You can usually set a branch name from the home page of your fork, with branch names drop down:

</img>

However, it's highly recommended to use local git client, because GitHub doesn't let you edit stuff easily.

But it's okay for this PR. Thanks once again.

**Comment by beaucarnes** [comment]
Ok, thanks for the info.

**Review by raisedadead — APPROVED** [review]
#### :sparkles: :sparkles: **LGTM.** :sparkles: :sparkles: 

Thanks @beaucarnes and congrats on your first contribution to the codebase!!

Keep them coming.!

**Pull request merged**
