### PR TITLE
fix(i18n): correct wording

### LINKED ISSUE #45373: Grammar issue in Learn CSS introduction
https://github.com/freeCodeCamp/freeCodeCamp/blob/984a2f2bc2e234466c3800c87038f28fdc9bc1d0/client/i18n/locales/english/intro.json#L153

I am not sure this is correct English here

### PR DESCRIPTION
**Pull request by Rubanik-Alexei**
Checklist:

- [x] I have read [freeCodeCamp's contribution guidelines](https://contribute.freecodecamp.org).
- [x] My pull request has a descriptive title (not a vague title like `Update index.md`)
- [x] My pull request targets the `main` branch of freeCodeCamp.
- [x] I have tested these changes either locally on my machine, or GitPod.

Closes #45373

### CODE REVIEW

**Comment by ieahleen** [comment]
> Closes #XXXXX

Please remember to mention the issue number, your PR could go unnoticed if you don't

**Comment by Rubanik-Alexei** [comment]
Added the issue number

**Review by gikf — APPROVED** [review]
LGTM :+1: 

---

Note for future - it is recommended to make changes on a separate branch, than the `main` branch. See more about it in point 3 at https://contribute.freecodecamp.org/#/how-to-setup-freecodecamp-locally?id=making-changes-locally.

**Review by Sembauke — APPROVED** [review]

**Comment by Sembauke** [comment]
Hi @Rubanik-Alexei, Congrats on your first pull request (PR)! 🎉

Thank you for your contribution to the page! 👍
We are happy to accept these changes and look forward to future contributions. 📝

**Pull request merged**
