### PR TITLE
fix(curriculum): Update grammar for translation

### LINKED ISSUE #49408: Grammar: Basic JS Step: Assignment with a return value
### Describe the Issue

The step contains an incomplete sentence (grammatically speaking) when it says:

will call the sum function, which returns a value of 17 and assigns it to the ourSum variable.

It is not clear who "will call the sum function" without actually looking at the code because the sentence is broken.
(The sentence is untranslatable at the moment.)

Perhaps it should say:
This line of code calls the sum function, which returns ...

### Affected Page

https://www.freecodecamp.org/learn/javascript-algorithms-and-data-structures/basic-javascript/assignment-with-a-returned-value

### Your code

```

```

### Expected behavior

correct the grammar of the sentence so it is clear who is doing the calling.

### Screenshots

_No response_

### System

N/A

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by azr-arch**
fix(UI): removed grammatical mistakes stated in #49408 

Checklist:

- [x] I have read and followed the [contribution guidelines](https://contribute.freecodecamp.org).
- [x] I have read and followed the [how to open a pull request guide](https://contribute.freecodecamp.org/#/how-to-open-a-pull-request).
- [x] My pull request targets the `main` branch of freeCodeCamp.
- [x] I have tested these changes either locally on my machine, or GitPod.

Closes #49408

### CODE REVIEW

**Comment by gikf** [comment]
As a new contributor, we encourage you to read our [contributing guidelines](https://contribute.freecodecamp.org).

We expect our contributors to be aware of the process specific to this project. Following the guidelines religiously earns you the respect of fellow maintainers and saves everyone time.

Some examples of this are:

1. Do not edit files directly through GitHub – while you can, it's not a good idea.
2. Make sure you follow the PR checklist and not just tick things off; otherwise, we won't take you seriously.
3. Use the correct way to link issues in the description of the PR by updating the `XXXXXX`. Do not just add issue numbers everywhere and anywhere you feel like.
4. Keep mentions and review requests to a minimum. We understand you are excited about contributing, and our maintainers will get back to you as soon as they get a chance.
5. Do not work directly off your `main` branch - create a new branch for the changes you are working on.

We appreciate you taking the time to help us, and we hope to see more contributions from you.

Happy Contributing.

**Comment by Sembauke** [comment]
Hi please update your pull-request title, with an informative title following our guidelines.

**Comment by azr-arch** [comment]
> Hi please update your pull-request title, with an informative title following our guidelines.

is it okay now ?

**Review by Sembauke — APPROVED** [review]

**Comment by azr-arch** [comment]
> ch PR title is still the same as when it was created.

is it changed now if not can u help me here also why title is showing #49426 after #49408?  and it is not editable .
a help here would be greatly appreciated

**Review by gikf — APPROVED** [review]

**Comment by gikf** [comment]
Hi @azr-arch. Congrats on your first pull request (PR)! 🎉

Thank you for your contribution to the page! 👍
We are happy to accept these changes and look forward to future contributions. 📝

**Pull request merged**
