### PR TITLE
Re-revert the API decoupling

### PR DESCRIPTION
**Pull request by raisedadead**
This pr should add back the decoupling we attempted previously via PRs #40703 and #41234, and removed in #41250.

### CODE REVIEW

**Comment by nhcarrigan** [comment]
The decoupling led to a breakdown in our deployment pipeline, correct? 

Is that resolved? Or do we need to ship this back to staging again to triage?

**Comment by raisedadead** [comment]
The decoupling led to a breakdown in our deployment pipeline, correct?

Yes - but that was a silly missing command that I botched up and not the code itself. I could not wrap my head around the error at the time and wanted to unblock staging and production from fixes.

Is that resolved? Or do we need to ship this back to staging again to triage?

Yes - Oliver clarified the details, and setup a test instance for us to validate. The updated commands and paths are being added as docs on our flight manuals. You should see them as this commit here: https://github.com/freeCodeCamp/freeCodeCamp/pull/41263/commits/f38a8426c86df4b9fa084a501bc2bf82b3c570e6

These docs will replace the existing commands in when this PR lands.

I will obviously add the commands to the pipeline too on this lands on `main`.

**Comment by raisedadead** [comment]
For now, I just want an approval on this PR at your convenience. I will take care of merging and updating the pipelines in tandem.

**Review by naomi-lgbt — APPROVED** [review]
Looks good to me. No issues with local development.

**Pull request merged**
