### PR TITLE
fix(curriculum): clarify that 'g flag' signifies 'global flag'

### PR DESCRIPTION
**Pull request by L4rryFisherman**
Checklist:

- [x ] I have read [freeCodeCamp's contribution guidelines](https://contribute.freecodecamp.org).
- [x ] My pull request has a descriptive title (not a vague title like `Update index.md`)
- [x ] My pull request targets the `main` branch of freeCodeCamp.
- [x ] I have tested these changes either locally on my machine, or GitPod.

Closes #XXXXX

### CODE REVIEW

**Review by Sboonny — CHANGES_REQUESTED** [review]
We can make it clearer by adding what the flag do as well

```diff
- To search or extract a pattern more than once, you can use the global flag: `g`.
+ To search or extract a pattern more than once, you can use the global search flag: `g`.
```

Edit:

We are happy, you are taking your time to make freeCodeCamp better.

Make sure to follow [freeCodeCamp's contribution guidelines](https://contribute.freecodecamp.org/), it will save you headache from some issues that you may face. 

In case you face these issues, you can seek us out in the [freeCodeCamp forum](https://forum.freecodecamp.org/) or our [freeCodaCamp chat](https://chat.freecodecamp.org/channel/contributors)

**Comment by L4rryFisherman** [comment]
This is my first time making a pull-request. I reviewed the github documentation, but I'm a little lost. Should I do anything further to incorporate your feedback, or is it automatically incorporated?

**Review by Sboonny — APPROVED** [review]

**Comment by Sboonny** [comment]
LGTM🎉

**Review by jeremylt — APPROVED** [review]
Seems like a good change to me

**Pull request merged**
