### PR TITLE
Provide working demo for File Metadata Microservice bonfire challenge

### LINKED ISSUE #9181: File metadata microservice sample app does not satisfy specs
Challenge [File Metadata Microservice](https://www.freecodecamp.com/challenges/file-metadata-microservice) has an issue.

The [sample app](https://cryptic-ridge-9197.herokuapp.com/) does not render a JSON response as requested in instruction 5:

> User Story: When I submit something, I will receive the file size in bytes within the JSON response

### PR DESCRIPTION
**Pull request by AryanJ-NYC**
#### Pre-Submission Checklist

- [x] Your pull request targets the `staging` branch of FreeCodeCamp.
- [x] Branch starts with either `fix/`, `feature/`, or `translate/` (e.g. `fix/signin-issue`)
- [x] You have only one commit (if not, [squash](https://github.com/FreeCodeCamp/FreeCodeCamp/wiki/git-rebase#squashing-multiple-commits-into-one) them into one commit).
- [x] All new and existing tests pass the command `npm run test-challenges`. Use `git commit --amend` to amend any fixes.
#### Type of Change

- [x] Small bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds new functionality)
- [ ] Breaking change (fix or feature that would change existing functionality)
- [ ] Add new translation (feature adding new translations)
#### Checklist:

- [x] Tested changes locally.
- [x] Closes currently open issue (replace XXXX with an issue no): Closes #9181
#### Description

The current [file metadata microservice demo](https://cryptic-ridge-9197.herokuapp.com/) does not satisfy all user stories for [Challenge File Metadata Microservice](https://www.freecodecamp.com/challenges/file-metadata-microservice). Specifically, it does not render a JSON response.  This PR replaces the current linked app with another that satisfies all user stories.

### CODE REVIEW

**Comment by raisedadead** [comment]
@AryanJ-NYC  thanks for the pull request, would you mind amending your commit message and remove the issue no.

**Comment by AryanJ-NYC** [comment]
@raisedadead Am I to remove the issue number completely or take it out of the commit message and into the body of the message?

**Comment by AryanJ-NYC** [comment]
Phew. It's been a long time. I took out "close #xxx" from the commit message and edited the PR description.

**Comment by raisedadead** [comment]
#### :sparkles: :sparkles: **LGTM.** :sparkles: :sparkles: 

Thanks for the changes. and welcome back :wink:

**Comment by raisedadead** [comment]
@AryanJ-NYC on a side node would you point us to the code as well if you could on Github

**Comment by AryanJ-NYC** [comment]
https://github.com/AryanJ-NYC/file-metadata

**Pull request merged**
