### PR TITLE
Add Instructions Clarification to Using Objects for Lookups

### LINKED ISSUE #6657: Using Objects for Lookups - Need Instructions Clarification
Challenge [Using Objects for Lookups](http://www.freecodecamp.com/challenges/using-objects-for-lookups#?solution=%2F%2F%20Setup%0Afunction%20phoneticLookup(val)%20%7B%0A%20%20var%20result%20%3D%20%22%22%3B%0A%0A%20%20%2F%2F%20Only%20change%20code%20below%20this%20line%0A%20var%20lookup%20%3D%20%7B%0A%20%20%20%20alpha%3A%20%22Adams%22%2C%0A%20%20%20%20bravo%3A%20%22Boston%22%2C%0A%20%20%20%20charlie%3A%20%22Chicago%22%2C%0A%20%20%20%20delta%3A%20%22Denver%22%2C%0A%20%20%20%20echo%3A%20%22Easy%22%2C%0A%20%20%20%20foxtrot%3A%20%22Frank%22%0A%20%20%7D%3B%0A%0A%20%20%2F%2F%20Only%20change%20code%20above%20this%20line%0A%20%20return%20lookup%5Bval%5D%3B%0A%7D%0A%0A%2F%2F%20Change%20this%20value%20to%20test%0AphoneticLookup(%22charlie%22)%3B%0A) has an issue.
User Agent is: <code>Mozilla/5.0 (Windows NT 6.1; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/48.0.2564.97 Safari/537.36</code>.
Please describe how to reproduce this issue, and include links to screenshots if possible.

The instructions say:
>Convert the switch statement into a lookup table called lookup. Use it to lookup val and **return the associated string**.

(Emphasis added)

Which leads to this solution:
```javascript
// Setup
function phoneticLookup(val) {
  var result = "";

  // Only change code below this line
 var lookup = {
    alpha: "Adams",
    bravo: "Boston",
    charlie: "Chicago",
    delta: "Denver",
    echo: "Easy",
    foxtrot: "Frank"
  };

  // Only change code above this line
  return lookup[val];  // <-----   They modified this line
}
```

I think the confusion is that the instructions say to `return the associated string`.

They should probably say:
> Convert the switch statement into a lookup table called lookup. Use it to lookup val and assign the associated string to the `result` variable.

### PR DESCRIPTION
**Pull request by raisedadead**
This commit adds clarification to the Instructions.

Tested locally.

closes #6657

### CODE REVIEW

**Comment by raisedadead** [comment]
I don't know what's the issue with the Travis CI build.

`npm test` passes without errors locally : [test_result.txt](https://github.com/FreeCodeCamp/FreeCodeCamp/files/113004/test_result.txt)

Although there are some warnings, but I have seen the same in other CI logs for other PR's too, hence can be assumed are pre-existing.

I highly doubt that the my change should cause this error.

Am I missing something?

**Comment by SaintPeter** [comment]
No, there is definitely a problem with es-lint.  It appears to be a known issue, we're working it.

**Comment by SaintPeter** [comment]
Try rebasing in staging and see if that fixes the issue.

**Comment by hallaathrad** [comment]
nope ;) it's good
it seems as long as staging (receiving branch) passes with the PR additions, it goes well

**Comment by SaintPeter** [comment]
:+1:

**Comment by raisedadead** [comment]
Thanks @SaintPeter and @hallaathrad !

**Pull request merged**
