### PR TITLE
fix: Display JS "Claim Certificate" button

### PR DESCRIPTION
**Pull request by jmagers**
#### Pre-Submission Checklist
- [x] Your pull request targets the `staging` branch of freeCodeCamp.
- [x] Branch starts with either `fix/`, `feature/`, or `translate/` (e.g. `fix/signin-issue`)
- [x] You have only one commit (if not, [squash](http://forum.freecodecamp.org/t/how-to-squash-multiple-commits-into-one-with-git/13231) them into one commit).
- [x] All new and existing tests pass the command `npm test`. Use `git commit --amend` to amend any fixes.

#### Type of Change
- [x] Small bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds new functionality)
- [ ] Breaking change (fix or feature that would change existing functionality)
- [ ] Add new translation (feature adding new translations)

#### Checklist:
- [x] Tested changes locally.
- [x] Addressed currently open issue

Addresses part of #16923

#### Description
The "Claim Certificate" button for the "JavaScript Algorithms and Data
Structures" projects will now be visible when all projects have been
completed.

### CODE REVIEW

**Review by Bouncey — APPROVED** [review]
Nice catch @JMagers :+1:

**Comment by johnpaulada** [comment]
Is this bug fix now on the live site? the buttons isn't showing for me 😢

**Comment by JMagers** [comment]
In order to claim certificates you need to go to the settings page. "Settings" should be in the upper right hand corner of the navigation bar.

**Comment by johnpaulada** [comment]
FreeCodeCamp is apparently on maintenance. Will try that when it's back up. Thanks! 😄

**Comment by JMagers** [comment]
It seems that other users aren't able to claim some certificates from their settings page either. You can see that its under the "Known bugs we're working on fixing this week" section [here](https://forum.freecodecamp.org/t/10-major-freecodecamp-improvements-that-are-live-now/192130).

**Pull request merged**
