### PR TITLE
fix(preview): Vertical scroll fix & UI adjustments of JS warning

### PR DESCRIPTION
**Pull request by vkWeb**
### Pre-Submission Checklist
- [x] Your pull request targets the `staging` branch of freeCodeCamp.
- [x] Branch starts with either `fix/`, `feature/`, or `translate/` (e.g. `fix/signin-issue`)
- [x] You have only one commit (if not, [squash](http://forum.freecodecamp.org/t/how-to-squash-multiple-commits-into-one-with-git/13231) them into one commit).
- [x] All new and existing tests pass the command `npm test`. Use `git commit --amend` to amend any fixes.

### Type of Change

- [x] Small bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds new functionality)
- [ ] Breaking change (fix or feature that would change existing functionality)
- [ ] Add new translation (feature adding new translations)

### Checklist:

- [x] Tested changes locally.
- [ ] Addressed currently open issue (replace XXXXX with an issue no in next line)

### Description
The preview pane wasn't scrolling after #16848 was merged. This PR aims at fixing that.

### CODE REVIEW

**Comment by vkWeb** [comment]
@Bouncey Why synk test failed? Is there something wrong with my code?

**Review by raisedadead — APPROVED** [review]
A rebase against staging will fix the snyk error. Code LGTM.

**Comment by vkWeb** [comment]
@raisedadead Rebase done.

**Comment by vkWeb** [comment]
@raisedadead Rebase Done. Thanks 😃! Snyk test passed.

**Comment by Bouncey** [comment]
@vkWeb Thanks for the work you have put in to this. However, we are removing this part of the UI in #16933. So I am closing this in favour of that.

Happy Coding!

**Pull request closed without merging**
