### PR TITLE
Fixed odd menu behaviors on mobile

### LINKED ISSUE #9822: Odd menu behaviors while on Map in mobile
#### Issue Description

While on mobile (real or simulated), Map behavior is odd.

_While on desktop emulated mobile_, menu hides the Free Code Camp logo and ability to close the menu while on Map.

_While on Map on an Android mobile device_, just clicking the Menu button will create this odd "menu" shown in the screenshot below. The menu is first drawn out normally, but just as the menu finished loading, the below screenshot is shown. This oddity will disappear if you click on the menu button again.
#### Browser Information

**Desktop Error**
- Browser Name, Version: Chrome
- Operating System: Windows
- Mobile, Desktop, or Tablet: Desktop (emulating Mobile)

**Mobile Error**
- Browser Name, Version: Chrome
- Operating System: Android
- Mobile, Desktop, or Tablet: Mobile
#### Screenshot

**Simulated mobile:**

map

**Real Android mobile:**

screenshot_20160720-171936

### PR DESCRIPTION
**Pull request by ooade**
#### Pre-Submission Checklist

- [x] Your pull request targets the `staging` branch of FreeCodeCamp.
- [ ] Branch starts with either `fix/`, `feature/`, or `translate/` (e.g. `fix/signin-issue`)
- [ ] You have only one commit (if not, [squash](http://forum.freecodecamp.com/t/how-to-squash-multiple-commits-into-one-with-git/13231) them into one commit).
- [ ] All new and existing tests pass the command `npm test`. Use `git commit --amend` to amend any fixes.

#### Type of Change

- [x] Small bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds new functionality)
- [ ] Breaking change (fix or feature that would change existing functionality)
- [ ] Add new translation (feature adding new translations)

#### Checklist:

- [x] Tested changes locally.
- [x] Closes currently open issue (replace XXXX with an issue no): Closes  #9822

#### Description
Fixed drawer behaviors on mobile devices.

### CODE REVIEW

**Comment by atjonathan** [comment]
@marhyorh, please update your title so it doesn't include the issue number. Also update your commit so it looks something like "Fixed odd menu behaviors on mobile" using `git commit --amend` and `git push -f`.

**Comment by marhyorh** [comment]
@atjonathan done.

**Review by ghost — CHANGES_REQUESTED** [review]
## The navbar works fine now! However, there is still an issue with the map when clicking "map" from the navbar on a challenge:

**Comment by marhyorh** [comment]
fcc Works fine for me ever since i made the update.

**Comment by marhyorh** [comment]
Who else is having this issue, i'd like to know what browser and perhaps mobile device you used?

**Comment by atjonathan** [comment]
cc @FreeCodeCamp/moderators ⬆️ https://github.com/FreeCodeCamp/FreeCodeCamp/pull/11562#issuecomment-259249048

**Review by markjoseph1995 — APPROVED** [review]

**Comment by atjonathan** [comment]
@marhyorh, I used a Sony Xperia Z3 Compact.

**Comment by ChaituVR** [comment]
@atjonathan  https://github.com/FreeCodeCamp/FreeCodeCamp/pull/11562#pullrequestreview-7520636 
i got the same issue with the staging branch .. 
image
but this map issue is actually resolved with this PR 
image
This could be actually due to your cache on the mobile browser At first i got the same thing but when i reloaded .. it actually got resolved when i removed my cache ... so can u try again with this pr?

**Comment by marhyorh** [comment]
@ChaituVR grab my (branch)[https://github.com/marhyorh/FreeCodeCamp/tree/odd-menu-behaviors]. It will be on staging once its merged.

**Comment by Bouncey** [comment]
LGTM

@atjonathan Has your issue been resolved?

**Review by ghost — APPROVED** [review]
#### LGTM :+1:

Thanks @marhyorh

**Pull request merged**
