### PR TITLE
Common framework refactor

### LINKED ISSUE #1683: Refactor CodeMirror to only use 1 webworker
"class" will completely freeze a bonfire

### LINKED ISSUE #4034: minify js in production

### LINKED ISSUE #4622: Memory Leak on the FCC website
Hi,

This is the memory profile of the webiste over time while writing a single line 
`$('button').prop('disabled', true);` No. of Event Listeners increased by 140 or so for that period which indicates the memory leak.  

 
I have looked at CodeMirror memory profile while writing a similar line (`$('editor').prop('disabled', true);`). Here things are looking pretty normal.

One of the sources seems to be `jailed.js` as shown in this picture.

 
cc @BerkeleyTrue

### PR DESCRIPTION
**Pull request by BerkeleyTrue**
Will push to beta for testing

closes #4622
closes #4034
closes #1683

### CODE REVIEW

**Comment by BerkeleyTrue** [comment]
@FreeCodeCamp/issue-moderators I have this up on Beta. If you have some time to check it out that would be great.

**Comment by SaintPeter** [comment]
My local QA has passed.  I checked a number of different challenge types, ran some tests, etc.  Didn't see any errors or obviously bad behavior.

I did test on IE11 and Edge, just for kicks, and it still doesn't work.

**Comment by ltegman** [comment]
Haven't completely finished testing, but so far I've tested javascript, html and step challenges, clicking through to new challenges, news, map, user profiles and these are all I've spotted so far:

+ ESLint (or strict mode?) errors cause code execution problems but don't flag the user (for example, variables defined without `var`).
+ Sometimes an infinitely looping web worker continues after tab is closed.
+ Initial load of any challenges with HTML results in console error (`Error: run preview not enabled at Object.o.runPreviewTests$`) and iPhone with `[object Object]` in display area.

Tomorrow I plan to load it up locally to get a side-by-side performance comparison with the prod codebase and test out the new gulp setup. I'll let you know how that goes by EOD (hopefully much earlier than that!)

**Comment by BerkeleyTrue** [comment]
> ESLint (or strict mode?) errors cause code execution problems but don't flag the user (for example, variables defined without var).

This PR does not try to solve this

> Sometimes an infinitely looping web worker continues after tab is closed.

This is interesting. Seems like closing a tab should kill webworkers as they are bound to the tab. I'm interesting in knowing why this does not happen with the current framework.

> Initial load of any challenges with HTML results in console error 

We'll need to figure out why that is. From the error it seems like the delay from updating of the iframe and then running the tests, which require the iframe DOM to be fully loaded, is not long enough.

**Comment by BerkeleyTrue** [comment]
> I did test on IE11 and Edge, just for kicks, and it still doesn't work.

So the original theory behind this is that those browsers do not support shared web workers. I no longer think this is the case. For one, shared web workers (SharedWorker) has a completely different api and Jailed (the framework that we currently run loop detect in) uses straight web workers (Worker).


So there is something else stoping Free Code Camp from working on those browsers. 

We need more eyes on this.

**Comment by ltegman** [comment]
Sorry for only reporting problems and not fixing any of them, but I haven't had time to go beyond testing yet today. Some more issues:

+ showJS.jade still references files from the old codemirror location and not the new bower install location. I didn't notice this on the beta site, so it appears to still have the old codemirror available.

On the plus side though performance is (unsurprisingly) very favorable in the refactor. Cached bonfire load takes an average of 1.6 seconds on my machine compared to an average of around 2.5 seconds for the production code! :+1: Map and other page loads seem unchanged.

@BerkeleyTrue My concern with FCC editor linting not exposing errors that will break code execution in the web worker is that this is newly introduced in the refactor. In the production website this code that doesn't cause linting errors will run without issue but in the refactor that code will fail to run.

I'll see if I can come up with consistent repro steps for the webworker not closing with the tab since it doesn't happen every time.

**Comment by ltegman** [comment]
Final though: after lots more testing today I'd say if we're comfortable having a discrepancy between what our linter catches and what the webworker will execute this is good to merge as soon as we change the initial delay from 50 to 80 to fix the problem with HTML challenge previews. I can't repro the infinitely looping webworker not closing with the tab despite my many attempts, so I don't think that's worth worrying about.

**Comment by bugron** [comment]
I think it's better to decrease CodeMirror's line height. The same code in [production](http://prntscr.com/97kpyw) looks better than in [beta](http://prntscr.com/97kprx), isn't it?

**Comment by BerkeleyTrue** [comment]
I've increased the delay on update preview

**Comment by BerkeleyTrue** [comment]
Great, conflicts!

**Comment by BerkeleyTrue** [comment]
Alright, rebased. @FreeCodeCamp/issue-moderators if there are no more changes that need to be done then this needs to be pulled as soon as possible.

**Comment by ltegman** [comment]
Thanks for resolving the conflicts -- merging this as soon as the travis build finishes!

**Pull request merged**
