### PR TITLE
 Update alt text challenge translation to pt-br

### PR DESCRIPTION
**Pull request by frontendwizard**
Few minor corrections to the alt text challenge translation to pt-br.

### CODE REVIEW

**Comment by RandellDawson** [comment]
**Hi,**

**Thanks for this pull request (PR).**

**Unfortunately, we are marking this PR invalid for hacktoberfest. We believe it does not follow the recommended guidelines:**

> ### Quality Standards 
> In line with Hacktoberfest value `#2` (Quantity is fun, Quality is key), we have provided examples of the quality standards we encourage. This applies mainly to beginners.
>
> * PRs that are automated e.g. scripted opening PRs to remove whitespace / optimize images.
> * PRs that are disruptive e.g. taking someone else's branch/commits and making a PR.
> * PRs that are regarded by a project maintainer as a hindrance vs. helping.
> * Something that's clearly an attempt to simply +1 your PR count for October.

Learn more at https://hacktoberfest.digitalocean.com/details

**Comment by RandellDawson** [comment]
Can you point out the changes you made?  I could not see any differences from what was already written.

Thanks.

**Comment by thefrontendwizard** [comment]
From `<code>Alt</code> texto alternativo descreve o conteúdo` to `O atributo <code>Alt</code> descreve o conteúdo`.
From `Eles não receberão as informações se estas forem apresentadas apenas visualmente.` to  `Eles não receberão informações se forem apresentados apenas visualmente.`
From `O <code>src</code> imagem não tem link para um arquivo real,` to `O atributo <code>src</code> da imagem não tem um link para um arquivo real,`
Those are subtle changes, but they do improve the readability.

**Comment by thefrontendwizard** [comment]
🎉
You're welcome.
Happy to help. 😃

**Pull request merged**
