### PR TITLE
fix(seed): Sass Challenge:Use @each to Map Over Items in a List tests were incorrect

### LINKED ISSUE #16894: SASS Challenges not working
#### Challenge Name
Sass: Use @each to Map Over Items in a List

#### Issue Description
The challenge always fails on the point 2-3-4, despite the code seems to be correct, the preview works fine and inspecting the html show me the three styles (blue-bg, black-bg, red-bg) properly expanded

#### Browser Information
* Browser Name, Version: Mozilla/5.0 (Windows NT 6.1; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/64.0.3282.186 Safari/537.36.
* Operating System: Microsoft Windows 7 Enterprise SP1
* Mobile, Desktop, or Tablet: Desktop

#### Your Code
```
<style type='text/sass'>
  
  @each $color in blue, black, red {
    .#{$color}-bg {background-color: $color;}
  }

  div {
    height: 200px;
    width: 200px;
  }
</style>

<div class="blue-bg"></div>
<div class="black-bg"></div>
<div class="red-bg"></div>
```

#### Screenshot
image

### LINKED ISSUE #16896: Sass Challenge:Use @each to Map Over Items in a List
#### Challenge Name
Use @each to Map Over Items in a List

https://beta.freecodecamp.org/en/challenges/sass/use-each-to-map-over-items-in-a-list
#### Issue Description

My code clearly works and provide the right result in the preview section but for some reason I don't
understand I don't pass the challenge.
#### Browser Information

* Browser Name, Version:  Chrome 64.0.3282.186
* Operating System: Windows 7
* Mobile, Desktop, or Tablet: 

#### Your Code

```js
<style type='text/sass'>
@each $color in blue, black, red {
  .#{$color}-bg {background-color: $color}
}

  div {
    height: 200px;
    width: 200px;
  }
</style>

<div class="blue-bg"></div>
<div class="black-bg"></div>
<div class="red-bg"></div>
```
#### Screenshot

screenshot-2

### PR DESCRIPTION
**Pull request by akoskoc**
Closes #16896
Closes #16894

#### Pre-Submission Checklist

- [x] Your pull request targets the `staging` branch of freeCodeCamp.
- [x] Branch starts with either `fix/`, `feature/`, or `translate/` (e.g. `fix/signin-issue`)
- [x] You have only one commit (if not, [squash](http://forum.freecodecamp.org/t/how-to-squash-multiple-commits-into-one-with-git/13231) them into one commit).
- [x] All new and existing tests pass the command `npm test`. Use `git commit --amend` to amend any fixes.

#### Type of Change

- [x] Small bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds new functionality)
- [ ] Breaking change (fix or feature that would change existing functionality)
- [ ] Add new translation (feature adding new translations)

#### Checklist:

- [x] Tested changes locally.
- [x] Addressed currently open issue (replace XXXXX with an issue no in next line)

Closes #16896
Closes #16894

#### Description

Those issues are duplicates.

### CODE REVIEW

**Comment by mstellaluna** [comment]
I am currently working on this PR

**Comment by mstellaluna** [comment]
@absolitudo I will be approving this PR. Thank you for your contribution. Happy Coding!

**Comment by elbui3** [comment]
Thank you msgtellaluna for your contribution, but this challenges is still not working...Maybe your changes are not yet effective?

**Comment by Asjas** [comment]
@elbui3 The freeCodeCamp codebase is deployed by @BerkeleyTrue every so often. So the changes does not show immediately but will only work after a deployement has been done.

**Comment by chriswingler** [comment]
Has a deployment not been done yet?  This test won't pass for me, but renders correctly.

**Comment by absolitudo** [comment]
It has been deployed, I investigated a little bit and found that in chrome the tests work correctly, in firefox however, every test that is using .css breaks, didn't find the reason yet.

**Pull request merged**
