### PR TITLE
fix: replace hard-code learn URL with .env value

### PR DESCRIPTION
**Pull request by tchaffee**
#### Pre-Submission Checklist

- [x] Your pull request targets the `staging` branch of freeCodeCamp.
- [x] Branch starts with either `fix/`, `feature/`, or `translate/` (e.g. `fix/signin-issue`)
- [x] You have only one commit (if not, [squash](http://forum.freecodecamp.org/t/how-to-squash-multiple-commits-into-one-with-git/13231) them into one commit).
- [x] All new and existing tests pass the command `npm test`. Use `git commit --amend` to amend any fixes.

#### Type of Change

- [x] Small bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds new functionality)
- [ ] Breaking change (fix or feature that would change existing functionality)
- [ ] Add new translation (feature adding new translations)

#### Checklist:

- [x] Tested changes locally.
- [ ] Addressed currently open issue (replace XXXXX with an issue no in next line)

Closes #XXXXX

#### Description
The learn URL is currently hard-coded. This PR first checks if the LEARN_URL value has been provided by the `.env` file, and if not it reverts to the hard-coded value. This allows easy configuration of the learn URL for testing or for use with a custom learn platform.

### CODE REVIEW

**Review by SubhrajyotiSen — APPROVED** [review]

**Comment by Charles909090** [comment]
Someone have stolen me from mine URL IN PARIS TEXAS 75460 CHARLES LEWIS NICHOLS

**Comment by Charles909090** [comment]
Been NOT TO GREAT ABOUT THERE LYING HERE.

**Comment by raisedadead** [comment]
Hi @tchaffee thanks a lot for the pull-request. 

We are in the process of making learn available at `https://www.freecodecamp.org/learn`. Its still going to be a separate application, served by netlify. There are certain challenges involved.

We are working on them.

/cc @Bouncey

**Comment by QuincyLarson** [comment]
@tchaffee As @raisedadead mentioned, we are putting all of our subdomains into a single domain, and @raisedadead and I are under the impression that once we've done so your PR will no longer be necessary, so I am closing this. If we are mistaken, please re-open this and explain why. As always, thanks for your help!

**Pull request closed without merging**
