### PR TITLE
fix(curriculum): added forumTopicId to Use Recursion to Create a Countdown challenge

### PR DESCRIPTION
**Pull request by RandellDawson**
- [x] I have read [freeCodeCamp's contribution guidelines](https://github.com/freeCodeCamp/freeCodeCamp/blob/master/CONTRIBUTING.md).
- [x] My pull request has a descriptive title (not a vague title like `Update index.md`)
- [x] My pull request targets the `master` branch of freeCodeCamp.
- [x] None of my changes are plagiarized from another source without proper attribution.
- [x] All the files I changed are in the same world language (for example: only English changes, or only Chinese changes, etc.)
- [x] My changes do not use shortened URLs or affiliate links.

After adding a solution to a new forum topic for this challenge, this PR adds the corresponding forumTopicId to the frontmatter.

### CODE REVIEW

**Review by ojeytonwilliams — APPROVED** [review]
LGTM :+1:

**Comment by thecodingaviator** [comment]
@RandellDawson how are you assigning the forumIDs?

**Comment by RandellDawson** [comment]
They are added after a corresponding forum topic is created for a new challenge.  There will not be many more under the new curriculum, because there is only one more PR which adds 4 new Rosetta Stone challenges which has not yet been merged.

**Review by moT01 — APPROVED** [review]
LGTM @RandellDawson 🎉

**Pull request merged**
