### PR TITLE
fix(curriculum): adding explanation for indexOf in music player project

### LINKED ISSUE #52926: Teach indexOf method in step 36 of music player project
### Describe the Issue

We have this [issue](https://github.com/freeCodeCamp/freeCodeCamp/issues/52898) here to refactor the RPG game to use the `includes` method instead of the `indexOf` method.
As a result, we will need to teach the `indexOf` method in step 36 of the music player project. 

I think it would be best to break up this step into two steps

[Step 36](https://www.freecodecamp.org/learn/javascript-algorithms-and-data-structures-v8/learn-basic-string-and-array-methods-by-building-a-music-player/step-36) could be to create the arrow function.

And then we can add a new step 37, to teach `indexOf` and then have campers use it on the `userData?.songs`

### Updated step 36 text

```md
# --description--

Before you start working on playing the next and previous song, you need to get the index of each song in the `songs` property of `userData`. 

Start by creating an arrow function called `getCurrentSongIndex`.
```

### New step 37 text

# --description--

To get the index for the current song, you can use the <dfn>indexOf</dfn> method. The `indexOf()` array method returns the first index at which a given element can be found in the array, or `-1` if the element is not present.

```js
const animals = ["dog", "cat", "horse"];
animals.indexOf("cat") // 1
```

Inside your `getCurrentSongIndex` function, return the result of using the `indexOf()` method on `userData?.songs` with the parameter set as `userData.currentSong`.

### Affected Page

https://www.freecodecamp.org/learn/javascript-algorithms-and-data-structures-v8/learn-basic-string-and-array-methods-by-building-a-music-player/step-36

### Your code

N/A

### Expected behavior

This step should be broken up into two steps so we can teach the `indexOf` method

### Screenshots

_No response_

### System

- Device: [e.g. iPhone 6, Laptop]
- OS: [e.g. iOS 14, Windows 10, Ubuntu 20.04]
- Browser: [e.g. Chrome, Safari]
- Version: [e.g. 22]

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by jdwilkin4**
## Summary of changes 
Added a new step for introducing the `indexOf` method since we removed the use of the `indexOf` method in the RPG. This will be first time campers will learn about this method so it needs an introduction to it. 

Checklist:

- [x] I have read and followed the [contribution guidelines](https://contribute.freecodecamp.org).
- [x] I have read and followed the [how to open a pull request guide](https://contribute.freecodecamp.org/#/how-to-open-a-pull-request).
- [x] My pull request targets the `main` branch of freeCodeCamp.
- [x] I have tested these changes either locally on my machine, or GitPod.

Closes #52926

### CODE REVIEW

**Comment by jdwilkin4** [comment]
I just marked the other PR as blocked since I think this one should go in first.
Since we removed the explanation for `indexOf` in the RPG project, technically there is no lesson to teach it right now. This PR fixes that.

**Comment by Ksound22** [comment]
Hey Jessica 👋🏽

The songs in the last step (Now 85) should be by Quincy, not Rafa:
Screenshot 2024-01-08 at 1 23 14 PM

The songs in step 84 (the last step before this PR) are Quincy's: 
Screenshot 2024-01-08 at 1 23 53 PM

**Comment by jdwilkin4** [comment]
HI @Ksound22 ! 

I am having trouble reproducing what you are seeing on your end.

On my end the song order is displaying correctly

Here is what I am seeing for step 84
Screenshot 2024-01-08 at 6 24 08 AM


Here is my step 85
Screenshot 2024-01-08 at 6 24 40 AM

Here are the meta.json files

[step 85](https://github.com/jdwilkin4/freeCodeCamp/blob/ab2b0c50a64235ff2ba140d7a4f889903e04973c/curriculum/challenges/english/15-javascript-algorithms-and-data-structures-22/learn-basic-string-and-array-methods-by-building-a-music-player/655b4dad1d38ff7cdd65cbfe.md)

[step 84](https://github.com/jdwilkin4/freeCodeCamp/blob/ab2b0c50a64235ff2ba140d7a4f889903e04973c/curriculum/challenges/english/15-javascript-algorithms-and-data-structures-22/learn-basic-string-and-array-methods-by-building-a-music-player/655b4c8f636d9675953a0388.md)

**Comment by Ksound22** [comment]
> HI @Ksound22 !
> 
> I am having trouble reproducing what you are seeing on your end.
> 
> On my end the song order is displaying correctly
> 
> Here is what I am seeing for step 84 Screenshot 2024-01-08 at 6 24 08 AM
> 
> Here is my step 85 Screenshot 2024-01-08 at 6 24 40 AM
> 
> Here are the meta.json files
> 
> [step 85](https://github.com/jdwilkin4/freeCodeCamp/blob/ab2b0c50a64235ff2ba140d7a4f889903e04973c/curriculum/challenges/english/15-javascript-algorithms-and-data-structures-22/learn-basic-string-and-array-methods-by-building-a-music-player/655b4dad1d38ff7cdd65cbfe.md)
> 
> [step 84](https://github.com/jdwilkin4/freeCodeCamp/blob/ab2b0c50a64235ff2ba140d7a4f889903e04973c/curriculum/challenges/english/15-javascript-algorithms-and-data-structures-22/learn-basic-string-and-array-methods-by-building-a-music-player/655b4c8f636d9675953a0388.md)

I thought of it as an issue on my end and decided to clear my browser ccokies and cache. Everything is now as it is on your end.

**Review by moT01 — APPROVED** [review]
LGTM 🎉

**Review by Ksound22 — APPROVED** [review]

**Pull request merged**
