### PR TITLE
fix: remove donation prevention

### PR DESCRIPTION
**Pull request by ahmaxed**
- [x] I have read [freeCodeCamp's contribution guidelines](https://github.com/freeCodeCamp/freeCodeCamp/blob/master/CONTRIBUTING.md).
- [x] My pull request has a descriptive title (not a vague title like `Update index.md`)
- [x] My pull request targets the `master` branch of freeCodeCamp.
- [x] None of my changes are plagiarized from another source without proper attribution.
- [x] All the files I changed are in the same world language (for example: only English changes, or only Chinese changes, etc.)
- [x] My changes do not use shortened URLs or affiliate links.

Closes #XXXXX

### CODE REVIEW

**Comment by ahmadabdolsaheb** [comment]
@ojeytonwilliams turns out we don't need to prevent donation since donation prompts happen less often on the previous donation modal logic.

could you take a look please?

**Review by ojeytonwilliams — CHANGES_REQUESTED** [review]
Removing `preventDonationRequests` means that once you trigger the `DonationModal` you see it every time you mount a page inside `/learn`.  To fix this, how about using `preventDonationRequests`, but only in `showDonateModalSaga` and have it flip `canRequestDonation` back to false?

That way the donation message should always be visible on certs and the donation modal should only pop up after you complete a block (but if you complete multiple blocks in a session, you will see multiple modals).

**Comment by ahmadabdolsaheb** [comment]
@ojeytonwilliams you are right. although I am not sure I follow logic for using preventDonationRequests for setting canRequestDonation back go false. in that case what would flip canRequestDonation to true?

How about flipping tryToShowDonationModal back to false after the donation pop up?

**Comment by ojeytonwilliams** [comment]
>  in that case what would flip canRequestDonation to true?

That will happen each time you finish a block, same as before.  The idea (in my last commit) is to have block completion flip `canRequestDonation` to true and then the modal's appearance (i.e. the saga) flips it back to false.  That way the modal appears, once, each time you finish a block.

**Review by ojeytonwilliams — APPROVED** [review]
LGTM :+1:

**Pull request merged**
