### PR TITLE
solution to challenge bad87fee1348bd9aedf08829

### PR DESCRIPTION
**Pull request by anassalam**
solution to challenge bad87fee1348bd9aedf08829 Create a Text Field

- [x] I have read [freeCodeCamp's contribution guidelines](https://github.com/freeCodeCamp/freeCodeCamp/blob/master/CONTRIBUTING.md).
- [x] My pull request has a descriptive title (not a vague title like `Update index.md`)
- [x] My pull request targets the `master` branch of freeCodeCamp.
- [x] None of my changes are plagiarized from another source without proper attribution.
- [x] My article does not contain shortened URLs or affiliate links.

If your pull request closes a GitHub issue, replace the XXXXX below with the issue number.

Closes #XXXXX

### CODE REVIEW

**Comment by RandellDawson** [comment]
Closed and reopened this PR in an attempt to resolve the following Travis build error:

> AssertionError: Test suit does not fail on the initial contents

**Comment by ValeraS** [comment]
@RandellDawson This is not a problem of tests, a problem with the changes provided.

And why you close/open PR instead of restart build in Travis CI?
image

**Comment by RandellDawson** [comment]
@ValeraS The original failure error is was different than what the current Travis build is failing for.  95% of the PRs I have been closing/reopening with these types of errors have not responded to just clicking the Restart Build.  

>This is not a problem of tests, a problem with the changes provided.

What is wrong with the changes exactly which causes it to failing with the following?
```
  1) Check challenges tests
       Create a Text Field
         Test suite must fail on the initial contents:
     Test suit does not fail on the initial contents
```

**Comment by RandellDawson** [comment]
@ValeraS I see the changes you just made, but I would not have guessed that fix based on the cryptic error message showing in the build log.

**Comment by ValeraS** [comment]
@RandellDawson Could you give me a PR problem that cannot be solved by restarting in Travis?

Tests check challenges provided by `getChallengesForLang`, these tests don't check the structure of md files. In this case `<section id='challengeSeed'>` is duplicated. Parser gets the second section with the provided solution, because of this tests pass on `seed` content.

**Comment by RandellDawson** [comment]
> Could you give me a PR problem that cannot be solved by restarting in Travis?

@ValeraS Almost every single PRs showing "missing script: test-ci" in the Travis build error message can not currently be resolved by simply clicking the Restart Build button.  If it was, then I would not have been closing/opening about 1000 PRs over the past couple days which had this error.  For example, PR #33455 showed the following before I clicked Restart Build:
image

About 4 minutes after I clicked the Restart Build button, I get the following which is the same failure as before.  This is why we are closing and restarted the majority of the Travis failures.  The only time that neither the Restart Build or the Close/Open works is if the PR has an existing merge conflict, so we have not been closing/opening those.  Plus, if it has a merge conflict, it will should resolve once a true rebase is performed during the merge conflict resolution which will trigger a new build anyway.
image

NOTE: If after a closing and opening, the PR it still fails, the next step is to pull down the PR locally and do a rebase and push back to the user's branch.

**Comment by ValeraS** [comment]
@RandellDawson So you open/close PR only with incorrect Travis config. https://github.com/travis-ci/travis-ci/issues/1485

**Comment by ValeraS** [comment]
> ```
>   1) Check challenges tests
>        Create a Text Field
>          Test suite must fail on the initial contents:
>      Test suit does not fail on the initial contents
> ```
> Before I closed and reopened it, it failed with a slightly different message:
> 
> ```
> AssertionError: Test suit does not fail on the initial contents
> ```

But this is the same error, and restarting build is enough for this PR.

**Comment by RandellDawson** [comment]
Hi @anassalam

It seems that similar changes have already been accepted earlier for this article you're editing, sorry about that. 😓

If you feel you have more to add, please feel free to open up a new PR.

Thanks again! 😊

---

> If you have any questions, feel free to reach out through [Gitter](https://gitter.im/FreeCodeCamp/Contributors) or by commenting below. 💬

**Pull request closed without merging**
