### PR TITLE
fix: Formatting for Zig Zag Matrix challenge

### PR DESCRIPTION
**Pull request by thecodingaviator**
- [x] I have read [freeCodeCamp's contribution guidelines](https://github.com/freeCodeCamp/freeCodeCamp/blob/master/CONTRIBUTING.md).
- [x] My pull request has a descriptive title (not a vague title like `Update index.md`)
- [x] My pull request targets the `master` branch of freeCodeCamp.
- [x] None of my changes are plagiarized from another source without proper attribution.
- [x] All the files I changed are in the same world language (for example: only English changes, or only Chinese changes, etc.)
- [x] My changes do not use shortened URLs or affiliate links.

Refer to #35387

### CODE REVIEW

**Comment by scissorsneedfoodtoo** [comment]
@thecodingaviator, just noticed a couple of minor things I left as a review.

**Comment by thecodingaviator** [comment]
Changed.

@RandellDawson Could you have a look at the asserts and tell me if the text has been removed correctly?

**Comment by RandellDawson** [comment]
@thecodingaviator Yes, the asserts you changes will work fine.

**Comment by scissorsneedfoodtoo** [comment]
@thecodingaviator, everything LGTM! Will ask for another review.

**Review by theNaut1lus — APPROVED** [review]
LGTM 🎉 @RandellDawson @scissorsneedfoodtoo @thecodingaviator

**Review by ezioda004 — APPROVED** [review]

**Comment by ezioda004** [comment]
Thank you @thecodingaviator for your contribution. Looking forward to more contributions from you! 🎉

**Pull request merged**
