### PR TITLE
fix: portfolio card style

### PR DESCRIPTION
**Pull request by Sembauke**
image

The new design for the project cards. I and Ahmad decided on a new design, this design offers consistency with our news platform. Meaning, the cards look like the landing page on news. While keeping the flexibility of the old design.

We need to make sure this is what we want. 

related to #48234

### CODE REVIEW

**Comment by ahmaxed** [comment]
Thank you for the pr. Here are a few things that could be improved in this pr.

1. the title/text should have a space between them and the right side of the card. The space should be similar to the space between the button and the side of the card. The styles to achieve the spacing should use grid for consistency.
2. the size of the displayed image should remain the same regardless of the size of the source image. use object-fit: cover;
3. the size of the image comparing to the size of the card should remain similar to news for consistancy

**Comment by Sembauke** [comment]
@ahmaxed, you are using an older version of the branch please update :)

**Comment by ahmaxed** [comment]
Here is the last layout. it accommodates for larger titles and larger descriptions. I removed the button in favor of turning the whole card to a link. We do have a similar pattern in news but I am not sure if it is obvious enough. 

Screenshot 2024-05-07 at 3 34 35 PM

**Comment by ahmaxed** [comment]
Thanks for the feedback. The border is going to look strange if the description and the title exceed the height of the image.

**Review by ahmaxed — APPROVED** [review]

**Review by huyenltnguyen — APPROVED** [review]

**Pull request merged**
