### PR TITLE
fix(code-editor): Fixed matching braces style  

### LINKED ISSUE #16363: [Beta] Matching Braces color in the editor needs to be changed
#### Issue Description
The matching braces color `#00ff00` in the beta looks weird and after some time it becomes difficult to trace the matching pair. So, with my idea of adding a border around the matching braces like in VSCode, will resolve this issue.
Please, have a look at the below GIF's in fullscreen by clicking on them to notice the difference effectively. **This issue will be addressed in my up-coming PR.**  

Default Setup:
before

After applying the proposed changes: 
after

#### Browser Information
* Browser Name, Version: Chrome(latest release) & Firefox(latest release).
* Operating System: Windows 10 Pro 32 Bit. 
* Mobile, Desktop, or Tablet: Desktop

@QuincyLarson, @raisedadead Thoughts on this?

### PR DESCRIPTION
**Pull request by vkWeb**
#### Pre-Submission Checklist
- [x] Your pull request targets the `staging` branch of freeCodeCamp.
- [x] Branch starts with either `fix/`, `feature/`, or `translate/` (e.g. `fix/signin-issue`)
- [x] You have only one commit (if not, [squash](http://forum.freecodecamp.org/t/how-to-squash-multiple-commits-into-one-with-git/13231) them into one commit).
- [x] All new and existing tests pass the command `npm test`. Use `git commit --amend` to amend any fixes.

#### Type of Change

- [x] Small bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds new functionality)
- [ ] Breaking change (fix or feature that would change existing functionality)
- [ ] Add new translation (feature adding new translations)

#### Checklist:

- [ ] Tested changes locally.
**Reason:** Code-mirror isn't working locally for me. 
- [x] Addressed currently open issue (replace XXXXX with an issue no in next line)

Closes #16363 

#### Description
Added a border around the matching braces like we have in VSCode. Also, it fixes the accessibility issue for matching-braces in night mode.

### CODE REVIEW

**Comment by vkWeb** [comment]
@raisedadead Thoughts?

**Comment by vkWeb** [comment]
@raisedadead PR Updated as per your request.

**Comment by raisedadead** [comment]
Unfortunately this is not working, you might have to check the underlying functionality locally. Please reopen a fresh request when ready.

**Comment by vkWeb** [comment]
@raisedadead Actually, CodeMirror was not working locally on my system. I just tested this on beta live site and it worked perfectly. Please check this change once more on live site. 

Btw, How can I make CodeMirror work in my local environment?

**Comment by raisedadead** [comment]
> Actually, CodeMirror was not working locally on my system. I just tested this on beta live site and it worked perfectly. Please check this change once more on live site.

I understand, that. But, as I said, after pulling down your changes, the fixes are not working. Without confirmation, we can't assume and merge, hoping it will work on a live site.

> Btw, How can I make CodeMirror work in my local environment?

Unfortunately, I am on a different build system than yours. And on mine it works seemingly fine.

We have just merged a ton of PRs. You should start with a clean rebase of your local copy, install the deps, and test again.

If still stuck, you should reach out to the [Contributors Chat room](https://gitter.im/FreeCodeCamp/Contributors) and try and seek assistance.

**Comment by vkWeb** [comment]
@raisedadead Okay. I'll open a new PR after doing the clean rebase and installation of dependencies.

**Pull request closed without merging**
