### PR TITLE
fix(guide): Add full solution to jQuery challenge: Use jQuery to Modify the Entire Page

### PR DESCRIPTION
**Pull request by thecodingaviator**
- [x] I have read [freeCodeCamp's contribution guidelines](https://github.com/freeCodeCamp/freeCodeCamp/blob/master/CONTRIBUTING.md).
- [x] My pull request has a descriptive title (not a vague title like `Update index.md`)
- [x] My pull request targets the `master` branch of freeCodeCamp.
- [x] None of my changes are plagiarized from another source without proper attribution.
- [x] All the files I changed are in the same world language (for example: only English changes, or only Chinese changes, etc.)
- [x] My changes do not use shortened URLs or affiliate links.

Closes #XXXXX

### CODE REVIEW

**Comment by RandellDawson** [comment]
@thecodingaviator When posting a full solution for the Guide, it should include all relative code (HTML, CSS, JS), so that a user could copy/paste and replace all the code in the editor and the code would pass.

**Comment by thecodingaviator** [comment]
@RandellDawson That goes for all guide articles, right? I was going by what the existing articles say and they had only the `<script>`

**Comment by RandellDawson** [comment]
@thecodingaviator The guide articles you find that do not have the full code should be updated at some point.  We will just fix them as we find them.

**Comment by thecodingaviator** [comment]
Ahh, alright

**Comment by RandellDawson** [comment]
Thank you for your contribution to the page! 👍
We're happy to accept these changes, and look forward to future contributions. 🎉

**Pull request merged**
