### PR TITLE
Consolidate contributors instructions into CONTRIBUTING.md

### PR DESCRIPTION
**Pull request by pbnj**
1. I've taken out contribution instructions from `README.md` and consolidated them into `CONTRIBUTING.md`. 
2. Expanded the "Creating Pull Requests" section with pertinent instructions from the Wiki and linked to the Wiki article for reference to the full instructions.

### CODE REVIEW

**Comment by SaintPeter** [comment]
Is there a reason you remove the "Code Not Working" section?  We have that up top since you can see the "Contribution Guidelines" when you are submitting an issue.

**Comment by pmbenjamin** [comment]
`Code not working?` section has been relabeled as `Found a bug?` for purposes of documentation flow:
- An overview of the process (e.g. check the board, pick an issue, if you found a bug that is not on the board follow the `found a bug` steps ...etc).
- Once you start working on an issue, you follow `contributors guideline` of creating a fork, branching, linting, committing, pushing ...etc
- Getting started guide (prerequisites, `npm install`, `touch .env` ...etc)
- `Found a bug` information & instructions
- `Creating Pull Requests` information & instructions

### Potential Enhancements:
- Table of Contents for quick/easy navigation
- Add `Creating and Maintaining Local Fork` section and copy the instructions from the Wiki.


Let me know if you still prefer to re-order `CONTRIBUTING.md`.

**Comment by SaintPeter** [comment]
There are basically two different audiences here:
1) Interested developers, for whom your organization is perfect.
2) Hapless campers, fumbling around because their code broke and they forgot about the Help room.  That's why we have that section up top.  No idea if it does any good, but there is no chance the'll read through in the middle.

**Comment by pmbenjamin** [comment]
@SaintPeter an average camper would not even think to check `CONTRIBUTING.md`, or would even be intimidated by it.

An alternative solution would be to add it to README.md, which makes sense since consumers/users of the app (aka campers) are the ones most likely finding and reporting bugs/issues.

**Comment by SaintPeter** [comment]
Maybe so.  Ok, I'll accept this as is and we'll work on adding info elsewhere.

Thank you for the excellent job!

**Comment by pmbenjamin** [comment]
I'll start working on adding some info to `README.md` about `Code not working`

**Pull request merged**
