### PR TITLE
fix(curriculum): removed __pyodide constant from pythontest evaluator

### LINKED ISSUE #54810: remove __pyodide now that all the tests use runPython.
https://github.com/freeCodeCamp/freeCodeCamp/blob/fc392d85477924064181137f98fee2a9fd9fc081/tools/client-plugins/browser-scripts/python-test-evaluator.ts#L122

### PR DESCRIPTION
**Pull request by AndrewYturaldi**
Checklist:

- [x] I have read and followed the [contribution guidelines](https://contribute.freecodecamp.org).
- [x] I have read and followed the [how to open a pull request guide](https://contribute.freecodecamp.org/#/how-to-open-a-pull-request).
- [x] My pull request targets the `main` branch of freeCodeCamp.
- [x] I have tested these changes either locally on my machine, or GitPod.

Closes #54810 

Removed pyodide as specified in the issue.

### CODE REVIEW

**Review by majestic-owl448 — CHANGES_REQUESTED** [review]
EDIT: ignore this, working on it

**Comment by ilenia-magoni** [comment]
How to unblock: #54832 needs to be merged, then a translation cycle needs to complete, then this branch needs to be updated to match `main`

**Comment by AndrewYturaldi** [comment]
@ilenia-magoni is there a way I can update the files in the portuguese and italian sections of the curriculum? it appears that is the reason the test are failing. If so, will this require a new issue and pull request?

**Comment by ilenia-magoni** [comment]
It requires the automatic translation process to happen, please do nothing and wait

**Review by majestic-owl448 — APPROVED** [review]
If the tests pass this should be good to go.

**Review by ojeytonwilliams — APPROVED** [review]
Thanks @AndrewYturaldi! LGTM 👍

**Pull request merged**
