### PR TITLE
guide/russian/cpp/index.md translation improves

### PR DESCRIPTION
**Pull request by everthinq**
freeCodeCamp/freeCodeCamp/guide/russian/cplusplus/index.md translation improves

I've done it in more readable way and translated missing parts.

- [x] I have read [freeCodeCamp's contribution guidelines](https://github.com/freeCodeCamp/freeCodeCamp/blob/master/CONTRIBUTING.md).
- [x] My pull request has a descriptive title (not a vague title like `Update index.md`)
- [x] My pull request targets the `master` branch of freeCodeCamp.
- [x] None of my changes are plagiarized from another source without proper attribution.
- [x] My article does not contain shortened URLs or affiliate links.

If your pull request closes a GitHub issue, replace the XXXXX below with the issue number.

Closes #XXXXX

### CODE REVIEW

**Comment by RandellDawson** [comment]
Closed and Reopened this PR to attempt to resolve a specific Travis build failure.

**Comment by RandellDawson** [comment]
@greggubarev Can you review this PR?  It has a big merge conflict.  The most important thing is, regardless what parts you end up keeping, make sure to replace the following:
```
![Img](https://i.imgur.com/d1liGwI.png)
```
with:
```
![Img](https://cdn-media-1.freecodecamp.org/imgr/d1liGwI.png)
```

**Review by greggubarev — COMMENTED** [review]
LGTM 👍 :dart:

**Review by greggubarev — APPROVED** [review]
Thank you for the PR ✨ 🎉
 We're happy to accept these changes and look forward to your future contributions :clap:

Happy coding! :octocat:

**Comment by RandellDawson** [comment]
@greggubarev There can not be a blank line above the front matter.  This must be removed or the Travis build will fail (as it is doing now).

**Pull request merged**
