### PR TITLE
Added padding in navigation bar for mobile view.

### LINKED ISSUE #45510: Addding a margin to the header
## Is your feature request related to a problem? Please describe.
On mobile devices, there is a navigation bar where you can switch back and forth the pages right below the header. It can be quite frustrating to tap on the logo accidentally when you tap on the 'Info' or 'Code' in the navigation bar.
Screenshot_20220323-152933_Chrome

## Describe the solution you'd like

I am proposing to add a padding to the header component, which can help to prevent accidental taps on the logo when using the navigation bar right below the header on mobile devices.

### PR DESCRIPTION
**Pull request by dmdbilal**
Checklist:

- [ ] I have read [freeCodeCamp's contribution guidelines](https://contribute.freecodecamp.org).
- [ ] My pull request has a descriptive title (not a vague title like `Update index.md`)
- [x] My pull request targets the `main` branch of freeCodeCamp.
- [x] I have tested these changes either locally on my machine, or GitPod.

Closes #45510

I've added extra padding in the navigation bar. This is my first contribution in freecodecamp.

Tested in iPhone 13
160995907-a775f39e-9467-4c66-8804-1d6c902ff738

### CODE REVIEW

**Comment by ahmadabdolsaheb** [comment]
Screen Shot 2022-10-03 at 3 21 03 PM

That would push down the action row in the bottom of the page.

**Comment by dmdbilal** [comment]
Can you assign this issue to someone.

**Comment by ShaunSHamilton** [comment]
Hello there,

Please edit this PR title to match our recommended title format: https://contribute.freecodecamp.org/#/how-to-open-a-pull-request

**Comment by ieahleen** [comment]
As a new contributor, we encourage you to read our [contributing guidelines](https://contribute.freecodecamp.org).

We expect our contributors to be aware of the process specific to this project. Following the guidelines religiously earns you the respect of fellow maintainers and saves everyone time.

Some examples of this are:

1. Do not edit files directly through GitHub – while you can, it's not a good idea.
2. Make sure you follow the PR checklist and not just tick things off; otherwise, we won't take you seriously.
3. Use the correct way to link issues in the description of the PR by updating the `XXXXXX`. Do not just add issue numbers everywhere and anywhere you feel like.
4. Keep mentions and review requests to a minimum. We understand you are excited about contributing, and our maintainers will get back to you as soon as they get a chance.
5. Do not work directly off your `main` branch - create a new branch for the changes you are working on.

We appreciate you taking the time to help us, and we hope to see more contributions from you.

Happy Contributing.

**Comment by ahmadabdolsaheb** [comment]
The main issue has been resolved by moving the breadcrumbs to the top of the tabs.

**Pull request closed without merging**
