### PR TITLE
fix: typos from your to you in challenges (#57713)

### LINKED ISSUE #57713: Typo 'Your' instead of 'You'
## Description

`Your` should be changed to `You` in the following occurrences:
https://github.com/freeCodeCamp/freeCodeCamp/blob/310eb2455bd2883e648a40b46eeba2eaf2be55e8/curriculum/challenges/english/14-responsive-web-design-22/learn-intermediate-css-by-building-a-cat-painting/646c48df8674cf2b91020ecc.md?plain=1#L14
https://github.com/freeCodeCamp/freeCodeCamp/blob/310eb2455bd2883e648a40b46eeba2eaf2be55e8/curriculum/challenges/english/15-javascript-algorithms-and-data-structures-22/learn-asynchronous-programming-by-building-an-fcc-forum-leaderboard/644b6d20eabd7e0149383254.md?plain=1#L20
https://github.com/freeCodeCamp/freeCodeCamp/blob/310eb2455bd2883e648a40b46eeba2eaf2be55e8/curriculum/challenges/english/25-front-end-development/workshop-cat-painting/646c48df8674cf2b91020ecc.md?plain=1#L15
https://github.com/freeCodeCamp/freeCodeCamp/blob/310eb2455bd2883e648a40b46eeba2eaf2be55e8/curriculum/challenges/english/25-front-end-development/workshop-music-player/6758a61fc7e949923716ec41.md?plain=1#L22
https://github.com/freeCodeCamp/freeCodeCamp/blob/310eb2455bd2883e648a40b46eeba2eaf2be55e8/curriculum/challenges/english/25-front-end-development/workshop-reusable-mega-navbar/6745d9df333efe2543a1f457.md?plain=1#L20
https://github.com/freeCodeCamp/freeCodeCamp/blob/310eb2455bd2883e648a40b46eeba2eaf2be55e8/curriculum/challenges/english/25-front-end-development/workshop-reusable-mega-navbar/6745d9df333efe2543a1f457.md?plain=1#L26

- - -

This issue is open to first-time code contributors to this repository.

We typically do not assign issues. Instead, we accept the most quality contribution followed by the one that is made first.

Please make sure you read our [guidelines for contributing](https://contribute.freecodecamp.org/#/) as well as our [expectations from a pull request](https://contribute.freecodecamp.org/#/how-to-open-a-pull-request), we prioritize contributors following the instructions in our guides. Join us in our [chat room](https://discord.gg/PRyKn3Vbay) or our [forum](https://forum.freecodecamp.org/c/contributors/3) if you need help contributing; our moderators will guide you through this.

Happy contributing.

### PR DESCRIPTION
**Pull request by Ishaankhan7**
Checklist:
 I have read and followed the [contribution guidelines](https://contribute.freecodecamp.org/).
 I have read and followed the [how to open a pull request guide](https://contribute.freecodecamp.org/how-to-open-a-pull-request/).
 My pull request targets the main branch of freeCodeCamp.
 I have tested these changes either locally on my machine, or GitPod.

Closes #57713

This pull request fixes a typo by replacing 'Your' with 'You' in several curriculum challenge files as per issue #57713.

### CODE REVIEW

**Review by Dario-DC — APPROVED** [review]
LGTM :tada: 

Edit: but now that I have my fictional glasses on, I can spot that everything is NOT in its proper place.

**Review by a2937 — CHANGES_REQUESTED** [review]
Hello,

Firstly, thank you for submitting this pull request!

As you navigate through the process, we have a PR checklist to ensure consistency and quality in our contributions. We kindly ask that you genuinely follow through with each point. This not only facilitates the review process but also demonstrates a mutual respect for the community's efforts.

If you're unfamiliar with certain aspects, our [contributing guidelines](https://contribute.freecodecamp.org) are a helpful resource to get you up to speed.

<details>
<summary>**Friendly Pointers (click to expand)**</summary>

<Steps>

1. **Editing on GitHub:** While it's possible to edit files directly on GitHub, it's typically better not to. This helps avoid inadvertent mistakes like typos that can disrupt tests.
2. **Pull Request Title:** Please ensure the PR title follows [our convention](/how-to-open-a-pull-request/#prepare-a-good-pr-title).
3. **Linking Issues:** Please ensure you link issues using the designated method. Simply update the `XXXXXX` in the PR description to include the issue number. This keeps our records organized and clear.
4. **Engaging with the Team:** We know you're eager, but kindly keep mentions and review requests limited. Our maintainers are always on the lookout and will attend to PRs in the order they come in.
5. **Branch Management:** It's a good practice not to work directly off your `main` branch. Creating separate branches for different changes allows you to smoothly update your PR even as the main repository progresses.

</Steps>

</details>

Please note, there's no need to close this PR. If you have questions or need guidance refining your contribution, don't hesitate to ask. Our community is here to assist. 

Edit: Now that I have my glasses on, I can spot that the answers are in it's proper place.

**Review by a2937 — APPROVED** [review]

**Review by majestic-owl448 — CHANGES_REQUESTED** [review]
Please make sure that your title follows the guidelines on how to open a PR

**Review by majestic-owl448 — APPROVED** [review]

**Comment by Ishaankhan7** [comment]
Thank you for reviewing my pull request. I have ensured that the checklist is addressed and reviewed the guidelines to bring it to the expected standards—**happy to refine further as needed!** 😊

**Comment by ilenia-magoni** [comment]
@Ishaankhan7 this time Naomi changed the title for you, next time you contribute it would be great if you could follow the contributing guidelines

**Comment by Ishaankhan7** [comment]
Sure ma'am 👍🏻

**Pull request merged**
