### PR TITLE
fix phrase issue for #52778

### PR DESCRIPTION
**Pull request by JackBerezhnov**
Checklist:

- [yes] I have read and followed the [contribution guidelines](https://contribute.freecodecamp.org).
- [yes] I have read and followed the [how to open a pull request guide](https://contribute.freecodecamp.org/#/how-to-open-a-pull-request).
- [yes] My pull request targets the `main` branch of freeCodeCamp.
- [yes] I have tested these changes either locally on my machine, or GitPod.

I was working on this issue [RPG Project] - Unclear instructions for step 77 #52778

I changed text from "For now, follow that pattern to use a string condition inside your if statement." to
"For now, the `if` statement condition should be set to the string `condition` as a placeholder." in this file "curriculum/challenges/english/15-javascript-algorithms-and-data-structures-22/learn-basic-javascript-by-building-a-role-playing-game/62a8c4db0710f3260f867a92.md"

### CODE REVIEW

**Comment by gikf** [comment]
Looks like something might have go wrong with the PR, for a change in a single file, that's a lot of files removed...

**Comment by JackBerezhnov** [comment]
@gikf Thank you for the review! For some reason when I try to clone the repo from my fork the git gives me that

error: unable to create file curriculum/challenges/chinese-traditional/19-foundational-c-sharp-with-microsoft/create-and-run-simple-c-sharp-console-applications/challenge-project-develop-foreach-and-if-elseif-else-structures-to-process-array-data-in-c-sharp.md: Filename too long
error: unable to create file curriculum/challenges/chinese-traditional/19-foundational-c-sharp-with-microsoft/create-and-run-simple-c-sharp-console-applications/guided-project-develop-foreach-and-if-elseif-else-structures-to-process-array-data-in-c-sharp.md: Filename too long
error: unable to create file curriculum/challenges/chinese-traditional/19-foundational-c-sharp-with-microsoft/create-and-run-simple-c-sharp-console-applications/store-and-iterate-through-sequences-of-data-using-arrays-and-the-foreach-statement-in-c-sharp.md: Filename too long
Updating files: 100% (72233/72233), done.
fatal: unable to checkout working tree
warning: Clone succeeded, but checkout failed.
You can inspect what was checked out with 'git status'
and retry with 'git restore --source=HEAD :/'

I don't know why I have that exactly. Do I do something wrong? I use Windows 10 and the latest git version.

**Comment by JackBerezhnov** [comment]
The rest of the files just didn't downloaded from the repo

**Comment by naomi-lgbt** [comment]
We do not officially support Windows for development. Recommend you look in to WSL.

**Comment by JackBerezhnov** [comment]
@naomi-lgbt Thank you so much! I didn't know that. I installed linux on my VM and now everything works perfectly!

**Comment by naomi-lgbt** [comment]
Glad to help! If you run into any further issues, feel free to pop into our Discord. :3

**Pull request closed without merging**
