### PR TITLE
fix(Nav): Avatar should light up brownie

### PR DESCRIPTION
**Pull request by ooade**
#### Pre-Submission Checklist

- [ ] Your pull request targets the `staging` branch of FreeCodeCamp.
- [ ] Branch starts with either `fix/`, `feature/`, or `translate/` (e.g. `fix/signin-issue`)
- [ ] You have only one commit (if not, [squash](http://forum.freecodecamp.com/t/how-to-squash-multiple-commits-into-one-with-git/13231) them into one commit).
- [ ] All new and existing tests pass the command `npm run test-challenges`. Use `git commit --amend` to amend any fixes.
#### Type of Change

- [x] Small bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds new functionality)
- [ ] Breaking change (fix or feature that would change existing functionality)
- [ ] Add new translation (feature adding new translations)
#### Checklist:

- [x] Tested changes locally.
- [ ] Closes currently open issue (replace XXXX with an issue no): Closes #XXXX

### CODE REVIEW

**Comment by marhyorh** [comment]
Its all good now @hallaathrad

**Comment by hallaathrad** [comment]
@marhyorh Dude! such an improvement! Thank you.

Wanna work on adding the user name on the next PR?

**Comment by marhyorh** [comment]
Yeah. It might have some ux issues on tablet devices. But i'll see what i can do about that :smile:

**Comment by hallaathrad** [comment]
We'll cross that bridge when we get there. I'll create the issue now and assign it to you.

**Pull request merged**
