### PR TITLE
feat(learn): create a progress indicator map

### LINKED ISSUE #50412: Add progress indicators to maps
Here's some mocks:

### PR DESCRIPTION
**Pull request by a2937**
Checklist:

- [X] I have read and followed the [contribution guidelines](https://contribute.freecodecamp.org).
- [X] I have read and followed the [how to open a pull request guide](https://contribute.freecodecamp.org/#/how-to-open-a-pull-request).
- [X] My pull request targets the `main` branch of freeCodeCamp.
- [X] I have tested these changes either locally on my machine, or GitPod.

Closes https://github.com/freeCodeCamp/freeCodeCamp/issues/50412

It's a revival of this PR. https://github.com/freeCodeCamp/freeCodeCamp/pull/52686

### CODE REVIEW

**Review by Sembauke — CHANGES_REQUESTED** [review]
Thanks for working on this @a2937,

We should centre the numbers inside the certifications. 

I am not sure if I like the arrows, it might me useful to try a couple of them.

Also, arrows should be white in the dark-theme and black in the light-theme.

image

**Comment by a2937** [comment]
The arrows aren't exactly a character. They're an SVG as it was the only way I could make something grow and shrink on the page.

**Comment by a2937** [comment]
Screenshot

Here's the current status.

**Comment by a2937** [comment]
I actually might need a little help making a new arrow shape, if that's alright. Though I'm fairly sure the colors are adjusted for night mode. Additionally, while centering isn't my strong suit; I hope it's closer this time.

**Comment by Sembauke** [comment]
Hey @a2937,

Sorry for keeping you waiting so long, I will check it today.

**Comment by Sembauke** [comment]
Current progress:
image

**Comment by a2937** [comment]
Thank you Sembauke. Those arrows look very lovely.

**Review by Sembauke — APPROVED** [review]

**Comment by naomi-lgbt** [comment]
image

Firefox (Ubuntu) does not have the numbers centred.

**Comment by a2937** [comment]
Yeah unfortunately I can confirm twice here. It's a possibility that it could be possible that absolute units messing things up. Or perhaps relative units aren't lining things up. 

WSL 2: 

image


Windows: 

image

**Comment by naomi-lgbt** [comment]
image

Better now on the ribbons, but not on the greyed out ones.

**Comment by a2937** [comment]
image

Okay we finally seem good now.

**Review by naomi-lgbt — CHANGES_REQUESTED** [review]
image

Out of these three, I've claimed the Machine Learning cert.

There's no visual indication here that I've done so.

**Comment by a2937** [comment]
Hmmm...what kind of indication should I give that says the camper has claimed the certification?

**Comment by naomi-lgbt** [comment]
I would hide the ribbon part on unclaimed certs, but leave the circle dark.

**Comment by a2937** [comment]
I can't hit the "I agree to freeCodeCamp's Academic Honesty Policy." button so I can claim my certifications.  But I will send in my update.

**Review by naomi-lgbt — APPROVED** [review]
image

Awesome work on all of this!

**Comment by ahmaxed** [comment]
@a2937, thank you for the hard work here. 
I think isCompleted is not being calculated probably. 
Could you please take a look into it?

**Comment by a2937** [comment]
No problem. I'll look into it and start that follow up PR soon.

**Pull request merged**
