### PR TITLE
revert: night mode as default

### PR DESCRIPTION
**Pull request by raisedadead**
I am reverting the earlier PR #36675 it has a splash effect for most users who don't have night mode in the settings.

We will have to revisit a different strategy for this.

/cc @ojeytonwilliams

### CODE REVIEW

**Comment by ValeraS** [comment]
you still will get splash for users who have night mode in the settings.

**Comment by raisedadead** [comment]
I thought so, but testing it locally with hard refresh I am not getting the same effect? Unless I am missing something?

**Comment by ojeytonwilliams** [comment]
Yep, as @ValeraS said.  I don't think my PR caused the problem.  My PR just shifted it from "users who have night mode set see a splash of light mode" to  "users who have light mode set see a splash of night mode".

**Comment by ojeytonwilliams** [comment]
@raisedadead Are you using `npm run develop`?  You'll only see it once the site's built.

**Comment by raisedadead** [comment]
Ah, the hyderation.

**Comment by raisedadead** [comment]
Okay, I'll close this then an log a issue.

**Comment by raisedadead** [comment]
Hi @ValeraS @ojeytonwilliams, 

I am re-opening this PR, to revert the changes and fallback to light mode as default. I audited the db and most users actually have light mode as default. Meaning the splash effect is going to be a issue for most (even if the flip the switch to night).

We should look into the splash effect issue (https://github.com/freeCodeCamp/freeCodeCamp/issues/36732) and the other code block issue that @ojeytonwilliams's PR #36675 attempted to fix separately.

**Comment by ojeytonwilliams** [comment]
That makes sense to me. I'll redo the fix (without changing what's default) later.

Revert away!

**Pull request merged**
