### PR TITLE
Fix typos and markdown

### PR DESCRIPTION
**Pull request by mbdaso**
- [x] I have read [freeCodeCamp's contribution guidelines](https://github.com/freeCodeCamp/freeCodeCamp/blob/master/CONTRIBUTING.md).
- [x] My pull request has a descriptive title (not a vague title like `Update index.md`)
- [x] My pull request targets the `master` branch of freeCodeCamp.
- [x] None of my changes are plagiarized from another source without proper attribution.
- [x] My article does not contain shortened URLs or affiliate links.

If your pull request closes a GitHub issue, replace the XXXXX below with the issue number.

Closes #XXXXX

### CODE REVIEW

**Comment by tchaffee** [comment]
@alu0100832211 someone merged another PR before yours and now there are merge conflicts. Could you please fix the merge conflicts?

**Comment by alu0100832211** [comment]
Yes, give me a minute

**Comment by tchaffee** [comment]
@alu0100832211 I see the same thing. Not sure why it's grayed out. Can you try contacting github support?

**Comment by alu0100832211** [comment]
Ok

**Comment by moT01** [comment]
Thank you for your contribution, but the guide has been moved here https://github.com/freeCodeCamp/freeCodeCamp/tree/master/guide and this cannot be merged. If you create a new PR targeting the new location we will do our best to get it merged.

**Pull request closed without merging**
