### PR TITLE
Fixes basic bonfire's permissive test

### LINKED ISSUE #2080: Free Code Camp Bonfire Challenge (Confirm the ending) issue
Challenge http://www.freecodecamp.com/challenges/bonfire-confirm-the-ending has an issue. It has a glitch. It accepts as a good solution this code:

function end(str, target) {
  
  var endLetter = str.substr(- 1);
  var endTarget = target.substr(-1);
  
if (endLetter === endTarget) {
  return true;
  } else {
  return false; 
};
}

But this code only analyze if the last letter of the string is equal the last letter of the target string.
So it would accept something like this also:
end('He has to give me a new name', 'fdsfsdfsefsfe');

Image:

freecodecampbug

### PR DESCRIPTION
**Pull request by butterthebuddha**
closes #2080

### CODE REVIEW

**Comment by bugron** [comment]
@awesomeaniruddh you've removed that dot from the test but you need to remove it from the test's description too.

**Comment by awesomeaniruddh** [comment]
Done.

**Comment by ahstro** [comment]
I'll merge this as soon as the conflicts are resolved. :)

**Comment by QuincyLarson** [comment]
@awesomeaniruddh @ahstro @bugron  I've gone ahead and resolved the conflicts myself to move this along. Thanks for your hard work all.

**Pull request merged**
