### PR TITLE
fix: update guide hint to properly declare regex

### PR DESCRIPTION
**Pull request by fbattle**
- [x] I have read [freeCodeCamp's contribution guidelines](https://github.com/freeCodeCamp/freeCodeCamp/blob/master/CONTRIBUTING.md).
- [x] My pull request has a descriptive title (not a vague title like `Update index.md`)
- [x] My pull request targets the `master` branch of freeCodeCamp.
- [x] None of my changes are plagiarized from another source without proper attribution.
- [x] My article does not contain shortened URLs or affiliate links.

Closes #XXXXX

Per the guide, minor typo updates do not need a GitHub issue, so I did not create one.

Regex values are always declared to be bound by '/' and '/'.  While reviewing the hints page, I noticed some regex strings do not have the final closing slash.  I found the same issue for each language version.  Also made one typo spelling update for the English version.

I did not test on a local copy of the site.

### CODE REVIEW

**Comment by fbattle** [comment]
I meant to include this info in my submission.  This is the issue I am fixing:
https://guide.freecodecamp.org/certifications/javascript-algorithms-and-data-structures/regular-expressions/reuse-patterns-using-capture-groups/

let re = /(test)\s\1;
let literalRe = /test\stest;

Notice how these two lines of code have the begin regex slash /, but not the end regex slash /.   Other regex values on the same page have both slashes.

**Comment by dingjy94** [comment]
@fbattle 
Congrats on your first pull request (PR)! 🎉

Thank you for your contribution to the page! 👍 We're happy to accept these changes and look forward to future contributions.

**Comment by RandellDawson** [comment]
@dingjy94 I sent you a message on Gitter regarding this PR.

**Comment by fbattle** [comment]
To close this out, the commit was reverted due to a merge conflict with other pending changes.  This commit should be applied to those future changes.

**Pull request merged**
