### PR TITLE
refactor(tests): enzyme => react-testing-library

### LINKED ISSUE #37690: rewrite enzyme tests in react-testing-library
We want to re-write the enzyme based tests in react-testing-library. For example: Profile.test.js is in enzyme. Eventually we want to remove it as a dependency on the client

### PR DESCRIPTION
**Pull request by theashraf**
- [x] I have read [freeCodeCamp's contribution guidelines](https://github.com/freeCodeCamp/freeCodeCamp/blob/master/CONTRIBUTING.md).
- [x] My pull request has a descriptive title (not a vague title like `Update index.md`)
- [x] My pull request targets the `master` branch of freeCodeCamp.
- [x] None of my changes are plagiarized from another source without proper attribution.
- [x] All the files I changed are in the same world language (for example: only English changes, or only Chinese changes, etc.)
- [x] My changes do not use shortened URLs or affiliate links.

Closes #37690

### CODE REVIEW

**Comment by raisedadead** [comment]
Ah.. my bad. I forgot to mention and clarify that we use Enzyme for our in browser test runner (for the curriculum), where should probably leave it as is (for now). 

Hey @ValeraS do you think there is a better way to test the react challenges?

**Comment by ValeraS** [comment]
@raisedadead It may be difficult to replace the `enzyme` in challenges tests. The enzyme allows you to check the internal state of the component. `testing-library` does not.

IMHO, we can use the `testing-library` for client tests as best practice and `enzyme` for challenges tests, because we want to check the internals of the components.

**Comment by theashraf** [comment]
Well, I added back `enzyme` for the reasons mentioned by @ValeraS  which makes sense

**Comment by raisedadead** [comment]
Thanks @theashraf will have this pulled down and merged soon :)

**Review by raisedadead — APPROVED** [review]

**Comment by RandellDawson** [comment]
@raisedadead I believe this PR may have broken something.  We are receiving many reports on the forum about the React challenges no longer working.  I have validated they do not seem to work on Chrome or Firefox.  The following error appears in the console with the correct solution for the first challenge.

image


[Link to challenge](https://www.freecodecamp.org/learn/front-end-libraries/react/create-a-simple-jsx-element)

**Comment by RandellDawson** [comment]
**Update**:  I confirmed this PR is the cause of the problem by removing the commit and testing locally.  I do not experience the issue then.

**Comment by ojeytonwilliams** [comment]
I can't reproduce it either.  .org .dev and local all seem fine.  Also, the changes in `frame-runner.js` should not have any effect on the functionality.

One complete guess is that, somehow, they've got a broken version of the enzyme adapter cached.  Maybe.

**Comment by RandellDawson** [comment]
When you say "they", how do you mean?

**Comment by ojeytonwilliams** [comment]
I just meant "the people that are experiencing the problem.".

Since you don't see the problem when you `npm run clean-and-develop` you could try building the site and checking again. It looks webpack related, after all.

**Comment by raisedadead** [comment]
Hi @RandellDawson @ojeytonwilliams can you point me to the threads on forum? Thanks.

**Comment by RandellDawson** [comment]
https://www.freecodecamp.org/forum/t/react-redux-tutorials-tests-are-not-executing/326155/6

**Pull request merged**
