### PR TITLE
Merge pull request #1 from freeCodeCamp/master

### PR DESCRIPTION
**Pull request by attaradev**

### CODE REVIEW

**Review by ezioda004 — COMMENTED** [review]
Hi @mikeattara,

Did you open this PR by mistake?

**Comment by mikeattara** [comment]
Hi @ezioda004 the first PR was a mistake.
Kindly check and merge this PR. I fixed the inconsistency in the function formatting. Fix issue #34367

**Review by Nirajn2311 — APPROVED** [review]
Everything LGTM
@ezioda004 do you think it would be better with 4 spaces or just 2 is enough.

**Review by ezioda004 — COMMENTED** [review]
LGTM 👍

**Comment by ezioda004** [comment]
@Nirajn2311 The codebase uses 2 spaces so we should be using that for consistency.

**Comment by ezioda004** [comment]
Thank you @mikeattara for your contribution and congratulations on your first PR merge to this repo! 🎉
Hope to see more contributions from you in the future.

**Comment by mikeattara** [comment]
This is a great milestone for me. I look forward to working more with you. Thanks, @ezioda004, and @Nirajn2311 so much for making this happen.

**Pull request merged**
