### PR TITLE
Guide Article: D3 JS data join (guide/english/d3)

### PR DESCRIPTION
**Pull request by sabeersulaiman**
- [x] I have read [freeCodeCamp's contribution guidelines](https://github.com/freeCodeCamp/freeCodeCamp/blob/master/CONTRIBUTING.md).
- [x] My pull request has a descriptive title (not a vague title like `Update index.md`)
- [x] My pull request targets the `master` branch of freeCodeCamp.
- [x] None of my changes are plagiarized from another source without proper attribution.
- [x] My article does not contain shortened URLs or affiliate links.

If your pull request closes a GitHub issue, replace the XXXXX below with the issue number.

Closes #XXXXX

### CODE REVIEW

**Review by thecodingaviator — DISMISSED** [review]
Please fix merge conflict

**Comment by RandellDawson** [comment]
@thecodingaviator This one has gone stale.

**Comment by sabeersulaiman** [comment]
@RandellDawson I can fix the conflicts and send PR soon

**Comment by thecodingaviator** [comment]
@sabeersulaiman Please send a PR soon

**Comment by sabeersulaiman** [comment]
@thecodingaviator See if it is good now. Sorry for the delay.

**Review by cmccormack — APPROVED** [review]
This looks good to me 👍.  Thank you for your contribution!

**Pull request merged**
