### PR TITLE
Improve Navigation Menu and Responsiveness

### PR DESCRIPTION
**Pull request by tharun977**
- [x] I have read and followed the [contribution guidelines](https://contribute.freecodecamp.org).
- [x] I have read and followed the [how to open a pull request guide](https://contribute.freecodecamp.org/how-to-open-a-pull-request/).
- [x] My pull request targets the `main` branch of freeCodeCamp.
- [x] I have tested these changes either locally on my machine, or GitPod.

Closes #1234

I added a new feature to the project that enhances user experience by improving the navigation menu. This change also includes updates to the corresponding CSS styles to make the layout more responsive.

### CODE REVIEW

**Comment by ilenia-magoni** [comment]
Your PR covers 213 files, that seems a bit much.

Was there discussion of this on an issue somewhere? UI changes always need an issue and some discussione

**Comment by tharun977** [comment]
Thank you for the feedback! I understand that covering 213 files in a single pull request is quite extensive. I will review the changes and break them down into smaller, more focused pull requests to improve the review process.

Additionally, I’ll check for any existing issues related to the UI changes I've made. If there are none, I will create an issue to document our discussions on this topic and ensure community input.

Thanks again for your guidance!

**Comment by tharun977** [comment]
Thank you for the insights and constructive feedback regarding the pull request. I will take the necessary steps to break down the changes into smaller, more manageable pull requests and create an issue for further discussion on the UI changes. I appreciate your guidance in helping me align with the project's contribution standards.

Looking forward to collaborating further!

**Comment by ilenia-magoni** [comment]
also make sure your PR includes only your commits, not others like it happened here

**Pull request closed without merging**
