### PR TITLE
fix: resubscribe endpoint when not logged in

### LINKED ISSUE #37662: The unsubscribe path works, but the resubscribe doesn't
The unsubscribe path works, but the resubscribe doesn't -- at least it didn't for me. All I wanted to do was change the email address where I receive, but when I try to resubscribe following the link shown in the screenshot above, I get this:

Screenshot 2019-11-01 19 40 52

_Originally posted by @laghee in https://github.com/freeCodeCamp/freeCodeCamp/issues/37331#issuecomment-548916882_

### PR DESCRIPTION
**Pull request by davidkwan95**
- [x] I have read [freeCodeCamp's contribution guidelines](https://github.com/freeCodeCamp/freeCodeCamp/blob/master/CONTRIBUTING.md).
- [x] My pull request has a descriptive title (not a vague title like `Update index.md`)
- [x] My pull request targets the `master` branch of freeCodeCamp.
- [x] None of my changes are plagiarized from another source without proper attribution.
- [x] All the files I changed are in the same world language (for example: only English changes, or only Chinese changes, etc.)
- [x] My changes do not use shortened URLs or affiliate links.

Closes #37662

### CODE REVIEW

**Comment by davidkwan95** [comment]
cc @raisedadead 

this PR uses the whitelisting approach. Feel free to comment if you want the other approach or for me to add some tests.

**Comment by raisedadead** [comment]
I think think should be fine. Yup, we would love some tests while you are at this

**Comment by davidkwan95** [comment]
Hi, mind telling me where where and how should I implement the test? I can't find existing test for testing the randomAPIs or testing whether a url is whitelisted.

**Comment by raisedadead** [comment]
> Hi, mind telling me where where and how should I implement the test? I can't find existing test for testing the randomAPIs or testing whether a url is whitelisted.

Its right alongside the file you changed:

https://github.com/freeCodeCamp/freeCodeCamp/blob/master/api-server/server/middlewares/request-authorization.test.js

**Comment by raisedadead** [comment]
I don't think we would need this anymore. We have moved away to hosting the static content on the same server.

**Comment by raisedadead** [comment]
Thanks lot for your work on this by the way. :)

**Pull request closed without merging**
