### PR TITLE
refactor: control project preview with challenge property

### PR DESCRIPTION
**Pull request by ojeytonwilliams**
- **feat: add demoType to relevant challenges**
- **feat: control preview via demoType**
- **tools: update project helper to create property**

Checklist:

- [x] I have read and followed the [contribution guidelines](https://contribute.freecodecamp.org).
- [x] I have read and followed the [how to open a pull request guide](https://contribute.freecodecamp.org/how-to-open-a-pull-request/).
- [x] My pull request targets the `main` branch of freeCodeCamp.
- [x] I have tested these changes either locally on my machine, or GitPod.

This removes the awkward logic from the client and, instead, means the project creator can choose if they want to show the final project or not.

Also, labs will soon let learners see the demo inside the client and this PR lays some of the groundwork for that.

### CODE REVIEW

**Comment by ojeytonwilliams** [comment]
@freeCodeCamp/mobile I assume adding a property is fine, but could you confirm?

**Review by moT01 — APPROVED** [review]
I'm good with getting this in. I do wonder if this is the best way. What if we want to show the workshop preview on demand as well - like a button on all the steps. We can make adjustments later if we have different use cases.

**Comment by ojeytonwilliams** [comment]
> What if we want to show the workshop preview on demand as well - like a button on all the steps.

If we decided that all the labs and workshops should behave the same way, we can probably remove this code. There's not much logic that relies on the `demoType`, so it shouldn't be hard to remove.

**Comment by ojeytonwilliams** [comment]
https://github.com/freeCodeCamp/freeCodeCamp/pull/55569 has diverged a little, so it doesn't seem helpful to keep this around any more.

**Pull request closed without merging**
