### PR TITLE
Fix remove leaf node Closes #40411

### LINKED ISSUE #40411: Unclear instructions and typeError Remove Leaf Node
**Describe your problem and how to reproduce it:**
using the code in this file:
[remove nodes](https://github.com/KravMaguy/Technical-interview/blob/master/Data%20Structures/removeNodes.js)

the challenge is passable by uncommenting lines 56-59
`            if (curr === null) {
                console.log(curr, "curr")
                return null
            }`

The wording of the test is "Trying to remove an element that does not exist should return null." yet the assertions only test for removing a node that does not exist in an empty tree. What about removing nodes that do not exist in a tree that has nodes?

````
js
assert(
  (function () {
    var test = false;
    if (typeof BinarySearchTree !== 'undefined') {
      test = new BinarySearchTree();
    } else {
      return false;
    }
    if (typeof test.remove !== 'function') {
      return false;
    }
    return test.remove(100) == null;
  })()
);
````

**Add a Link to the page with the problem:**
https://www.freecodecamp.org/learn/coding-interview-prep/data-structures/delete-a-leaf-node-in-a-binary-search-tree

My pull request:
https://github.com/freeCodeCamp/freeCodeCamp/pull/40371

**Tell us about your browser and operating system:**
* Browser Name: 
* Browser Version: 
* Operating System: 

**If possible, add a screenshot here (you can drag and drop, png, jpg, gif, etc. in this box):**

### PR DESCRIPTION
**Pull request by KravMaguy**
Checklist:

- [x] I have read [freeCodeCamp's contribution guidelines](https://contribute.freecodecamp.org).
- [x] My pull request has a descriptive title (not a vague title like `Update index.md`)
- [x] My pull request targets the `master` branch of freeCodeCamp.
- [x] All the files I changed are in the same world language, for example: only English changes, or only Chinese changes, etc.

Closes #XXXXX

### CODE REVIEW

**Comment by Sky020** [comment]
Hello there,

Does this PR resolve an open issue?

Also, please complete the checklist given in the body of your PR.

**Comment by KravMaguy** [comment]
What do you mean open issue? 
the issue is that the tests are not comprehensive, this part of the curriculum is not developed. 

its calling remove on an empty tree. and does not call remove on a tree that has nodes with a node that does not exist. I believe the wording of the test is misleading/incorrect and it should test for a case when a tree exists (that has nodes) and you pass in data for a node that does not exist or test for both cases in a single test… or if you want to add an additional test case for when your removing a node that does not exist in an empty tree then have a separate case for that.

**Comment by Sky020** [comment]
> What do you mean open issue?

Typically, PRs (pull-requests) are opened to close existing [issues](https://github.com/freeCodeCamp/freeCodeCamp/issues). So, I am confirming whether or not this PR is aimed at closing an issue. In which case, the body of this PR needs to be edited to change:
```text
Closes #XXXXX
```
To reference the issue number related.

In general, I recommend the body of a PR contain necessary information for maintainers to understand the reasoning behind opening it:
a) Is the PR related to a discussed issue
b) If not, what is the reasoning behind opening the PR - forum discussion, self-discovered bug, etc.
c) Any additional information to clarify intent

Hope this clarifies

**Comment by KravMaguy** [comment]
I see what you mean, although I did not see a reason to open an issue retroactively
a) Is the PR related to a discussed issue
Ive been tasked by robert groves (leader on the forum) with trying to improve this part of the curriculum
b) If not, what is the reasoning behind opening the PR - forum discussion, self-discovered bug, etc.
Yes, forum discussion with robert groves.

**Comment by KravMaguy** [comment]
it could be a bug?. in a real app, for example if your trying to delete something that does not exist how would you know that it does not exist unless the program gives some feedback. so you will receive a typeError. In this case that would equate to trying to read the value of null (i.e. the value of the node that does not exist in the tree)

**Comment by KravMaguy** [comment]
ive updated the title of the pull request per your instructions referencing the issue number

**Pull request closed without merging**
