### PR TITLE
feat(curriculum): add animations to block 4.1 of the English Curriculum

### PR DESCRIPTION
**Pull request by DanielRosa74**
Checklist:

- [X] I have read and followed the [contribution guidelines](https://contribute.freecodecamp.org).
- [X] I have read and followed the [how to open a pull request guide](https://contribute.freecodecamp.org/#/how-to-open-a-pull-request).
- [X] My pull request targets the `main` branch of freeCodeCamp.
- [X] I have tested these changes either locally on my machine, or GitPod.

### CODE REVIEW

**Review by moT01 — COMMENTED** [review]
This is looking real good @DanielRosa74 🎉 

 Quite a few of the animations seem to cut off a little early. Here’s a mostly complete list of the ones I noticed: Tasks 9, 20, 21, 25, 34, 38, 46, 47, 51-67, 70-72, 74, 77, 80, 87, 88, 99, 109, 110, 115, 116, 119, 120, 121, 127, 128, 137-139. Some of them are minor enough that they could probably just be left alone, but others are quite significant. Are you seeing that? Perhaps there's an issue with how something is loaded and you aren't seeing it. Or maybe it's an issue with the script that creates the scenes, or how it's played - not sure.
 
 Tasks 66 and 67 have the same JSON for the scene, but they seem to cut off at slightly different times.
   
    Tasks 9 and 10 end with Maria saying the same word, but the finishTimestamp is different. Not sure if you manually changed that or if the script is being goofy.
    
       Before we go in and change all the times, I think we should look into a little and see where the issue is. Seems like it's probably something with the finishTime, since the majority of the scenes work fine, but it would be nice to be sure. 
       
       Task 134-136 open-source doesn't have the hyphen.

**Comment by nieldakarla** [comment]
> This is looking real good @DanielRosa74 🎉
> 
>  Quite a few of the animations seem to cut off a little early. Here’s a mostly complete list of the ones I noticed: Tasks 9, 20, 21, 25, 34, 38, 46, 47, 51-67, 70-72, 74, 77, 80, 87, 88, 99, 109, 110, 115, 116, 119, 120, 121, 127, 128, 137-139. Some of them are minor enough that they could probably just be left alone, but others are quite significant. Are you seeing that? Perhaps there's an issue with how something is loaded and you aren't seeing it. Or maybe it's an issue with the script that creates the scenes, or how it's played - not sure.    Tasks 66 and 67 have the same JSON for the scene, but they seem to cut off at slightly different times.         Tasks 9 and 10 end with Maria saying the same word, but the finishTimestamp is different. Not sure if you manually changed that or if the script is being goofy.             Before we go in and change all the times, I think we should look into a little and see where the issue is. Seems like it's probably something with the finishTime, since the majority of the scenes work fine, but it would be nice to be sure.                 Task 134-136 open-source doesn't have the hyphen.


@DanielRosa74 I'll add my notes here. I've paid special attention to the tasks. @moT01 I've paid special attention to all the tasks you had mentioned. I list below the tasks I've noticed the audio gets cut off earlier and the ones that have extra words. 

Tasks that have extra words from other lines of dialogue: 
12, 42, 83, 84, 101, 102, 124, 131 and 133 

Tasks that get cut off before the end:
52, 99, 119 (there might be some more that could use some breathing space, but I didn't mention them here)

About tasks 9 and 10:

I think they are correct. From what I saw, the difference is that task 9 uses just the second part of what Maria is saying - The first part is in task 08 - while task 10 uses her entire line of dialogue to check understanding.

Extra requests: 
Task 44: Can you please update the question to be: "What is making Tom feel demotivated?"
Currently it ends with "and why?" but the options don't include reasons.

Task 126: Remove extra dot at the end of the description.

**Review by nieldakarla — COMMENTED** [review]
@DanielRosa74 I'll add my notes here. @moT01, I've paid special attention to the tasks you mentioned on your review. I've listed below the tasks I've noticed the audio gets cut off earlier and the ones that have extra words. 

Tasks with extra words from other lines of dialogue: 
12, 42, 83, 84, 101, 102, 124, 131 and 133 

Tasks that get cut off before the end:
52, 99, 119 (there might be some more that could use some breathing space, but I didn't mention them here)

About tasks 9 and 10:

I think they are correct. From what I saw, the difference is that task 9 uses just the second part of what Maria is saying - The first part is in task 08 - while task 10 uses her entire line of dialogue to check understanding.

Extra requests: 
Task 44: Can you please update the question to be: "What is making Tom feel demotivated?"
Currently it ends with "and why?" but the options don't include reasons.

Task 126: Remove extra dot at the end of the description.

**Comment by DanielRosa74** [comment]
> This is looking real good @DanielRosa74 🎉
> 
>  Quite a few of the animations seem to cut off a little early. Here’s a mostly complete list of the ones I noticed: Tasks 9, 20, 21, 25, 34, 38, 46, 47, 51-67, 70-72, 74, 77, 80, 87, 88, 99, 109, 110, 115, 116, 119, 120, 121, 127, 128, 137-139. Some of them are minor enough that they could probably just be left alone, but others are quite significant. Are you seeing that? Perhaps there's an issue with how something is loaded and you aren't seeing it. Or maybe it's an issue with the script that creates the scenes, or how it's played - not sure.    Tasks 66 and 67 have the same JSON for the scene, but they seem to cut off at slightly different times.         Tasks 9 and 10 end with Maria saying the same word, but the finishTimestamp is different. Not sure if you manually changed that or if the script is being goofy.             Before we go in and change all the times, I think we should look into a little and see where the issue is. Seems like it's probably something with the finishTime, since the majority of the scenes work fine, but it would be nice to be sure.                 Task 134-136 open-source doesn't have the hyphen.

Fixes sent to the repo, except for the absence of the hyphen in tasks 134-136, which is on purpose, as per https://learn.microsoft.com/en-us/style-guide/a-z-word-list-term-collections/o/open-source.

**Comment by DanielRosa74** [comment]
> @DanielRosa74 I'll add my notes here. @moT01, I've paid special attention to the tasks you mentioned on your review. I've listed below the tasks I've noticed the audio gets cut off earlier and the ones that have extra words.
> 
> Tasks with extra words from other lines of dialogue: 12, 42, 83, 84, 101, 102, 124, 131 and 133
> 
> Tasks that get cut off before the end: 52, 99, 119 (there might be some more that could use some breathing space, but I didn't mention them here)
> 
> About tasks 9 and 10:
> 
> I think they are correct. From what I saw, the difference is that task 9 uses just the second part of what Maria is saying - The first part is in task 08 - while task 10 uses her entire line of dialogue to check understanding.
> 
> Extra requests: Task 44: Can you please update the question to be: "What is making Tom feel demotivated?" Currently it ends with "and why?" but the options don't include reasons.
> 
> Task 126: Remove extra dot at the end of the description.

Extra requests sent to the repo. The other items stem from the audio difference between FF and Chrome, I suppose, which may be fixed with Tom's and Oliver's audio fix.

**Review by nieldakarla — APPROVED** [review]
LGTM

**Review by moT01 — APPROVED** [review]

**Pull request merged**
