### PR TITLE
Combining all Calculus related topics into one

### PR DESCRIPTION
**Pull request by thecodingaviator**
- [x] I have read [freeCodeCamp's contribution guidelines](https://github.com/freeCodeCamp/freeCodeCamp/blob/master/CONTRIBUTING.md).
- [x] My pull request has a descriptive title (not a vague title like `Update index.md`)
- [x] My pull request targets the `master` branch of freeCodeCamp.
- [x] None of my changes are plagiarized from another source without proper attribution.
- [x] My article does not contain shortened URLs or affiliate links.

All calculus related topics have been moved to one folder and a repeated topic has been deleted

### CODE REVIEW

**Comment by RandellDawson** [comment]
What is the purpose of deleting all those files?  Why not keep them separate?

**Comment by thecodingaviator** [comment]
I haven't deleted any file except one which was a copy of another file but with a different name. All other files have just been renamed i.e. I have changed their paths to the newly created folder

**Comment by thecodingaviator** [comment]
@RandellDawson One file for partial-derivatives was duplicate so I've added it to the other one

**Comment by RandellDawson** [comment]
You still have some merge conflicts on this PR which need resolution.

**Comment by thecodingaviator** [comment]
@RandellDawson Updated

**Comment by RandellDawson** [comment]
There are several PRs against the old file names which need to be reviewed/merged/closed first.  I will do that now and then you may have to fix some other merge conflicts.

**Comment by RandellDawson** [comment]
I reviewed 3 PRs which had files with changes, but I closed them due to changes not needed (duplicate) and/or changes which did not add any value to the content.

Thank you for your contribution to the page! 👍
We're happy to accept these changes, and look forward to future contributions. 🎉

**Pull request merged**
