### PR TITLE
Fix/Spinal Tap Case Missing Parenthesis

### LINKED ISSUE #8852: Spinal Tap Case Missing Parenthesis
#### Spinal Tap Case intermediate algorithm
https://www.freecodecamp.com/challenges/spinal-tap-case

#### Issue Description
3rd test case is missing a closing parenthesis.  This does not really affect my experience with the challenge too much I just felt like it is something that should be fixed and would be an easy fix.  I would be interested in doing it just for fun if possible

#### Browser Information
Google Chrome, Mac OSX Yosemite

#### Screenshot
screen shot 2016-05-29 at 6 13 53 pm

### PR DESCRIPTION
**Pull request by Bouncey**
#### Pre-Submission Checklist

- [x] Your pull request targets the `staging` branch of FreeCodeCamp.
- [x] Branch starts with either `fix/`, `feature/`, or `translate/` (e.g. `fix/signin-issue`)
- [x] You have only one commit (if not, [squash](https://github.com/FreeCodeCamp/FreeCodeCamp/wiki/git-rebase#squashing-multiple-commits-into-one) them into one commit).
- [x] All new and existing tests pass the command `npm run test-challenges`. Use `git commit --amend` to amend any fixes.
#### Type of Change

- [x] Small bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds new functionality)
- [ ] Breaking change (fix or feature that would change existing functionality)
- [ ] Add new translation (feature adding new translations)
#### Checklist:

- [x] Tested changes locally.
- [x] Closes currently open issue (replace XXXX with an issue no): Closes #8852 
#### Description

Added `<wbr>` to long test cases in this challenge to enable wrapping when required.

### CODE REVIEW

**Comment by erictleung** [comment]
@Bouncey LGTM! But I wanna wait to get @hallaathrad's opinion on this fix.

**Comment by hallaathrad** [comment]
yup. LGTM too. worst case scenario it shouldn't break a thing... I think. How does it render in IE >12?

**Comment by erictleung** [comment]
@hallaathrad https://developer.mozilla.org/en-US/docs/Web/HTML/Element/wbr

> This element was first implemented in Internet Explorer 5.5 and was officially defined in HTML5.

But then 

image

"[1] Support for the <wbr> tag was introduced in Internet Explorer 5.5, though removed again in version 7."

**Comment by hallaathrad** [comment]
Oh, I'm well aware of this... I'm just wondering what the failure behaviour will be. Will it simply be ignored and not added to the DOM? and even throw an error message? or perhaps it will simply be displayed as part of the text (i.e. the text `thisIsSpinal<wbr>Tap` actually being shown to the user).

IE is sort of horrible and unpredictable that way. any chance we can run tests? I mean, if it simply gets ignored, I'm ok with this and those users will simply have to put up with the missing parenthesis —and hopefully get a decent browser too. haha

**Comment by erictleung** [comment]
@hallaathrad ah I see. You said "how does it render". I didn't read carefully enough. Anyways, I don't have quick access to IE to test this.

**Comment by hallaathrad** [comment]
@FreeCodeCamp/issue-moderators anyone to try this one out, just to be on the safe side?

**Comment by atjonathan** [comment]
@hallaathrad, pulling down now...

**Comment by Bouncey** [comment]
There some ie work-arounds [here](http://stackoverflow.com/questions/23756932/wbr-tag-doesnt-work-in-ie)

I'm away for a wedding and unable to try them out until Wednesday. If someone wants to try them out then be my guest.

**Comment by scshepard** [comment]
For what it's worth, the "fiddle" works great in Edge; I'm on Windows 10 so no more IE for me...http://fiddle.jshell.net/88q54/1/I see a "WORD" in the bottom right hand corner (appears to be the Render view).Thanks,Steve

Date: Sun, 5 Jun 2016 00:56:04 -0700

**Comment by Bouncey** [comment]
Thanks Steve, 

W3Schools states it is supported from IE 12(edge?) 
Caniuse.com states support from IE 13?

**Comment by hallaathrad** [comment]
@scshepard you should still have ie 11 installed yet hidden. I know my windows 10 desktop does.

For all interested, I've run tests and ie sees and recognises it as an element in the DOM, but offers not any behaviour. I'd dare say it's safe and I'll clean the mess if we get any reports :)

**Pull request merged**
