### PR TITLE
fix: correct inconsistency in formatting

### PR DESCRIPTION
**Pull request by lasjorg**
- [x] I have read [freeCodeCamp's contribution guidelines](https://github.com/freeCodeCamp/freeCodeCamp/blob/master/CONTRIBUTING.md).
- [x] My pull request has a descriptive title (not a vague title like `Update index.md`)
- [x] My pull request targets the `master` branch of freeCodeCamp.
- [x] None of my changes are plagiarized from another source without proper attribution.
- [x] All the files I changed are in the same world language (for example: only English changes, or only Chinese changes, etc.)
- [x] My changes do not use shortened URLs or affiliate links.

Fix for minor inconsistency in formatting. Remove space before parentheses for method glideMixin.

### CODE REVIEW

**Comment by RandellDawson** [comment]
I honestly can not tell a difference in the formatting.  If you really want to format it, use triple backticks on the line before and the line after each code section and then use 2 space indention for the code itself.

**Comment by lasjorg** [comment]
The space after the function keyword and before the parentheses is inconsistent with the formatting in the curriculum. The only other place i see that style is the anonymous functions of the IIFE's (in the assignment before and in this, I'm not even sure if that should be there).


How it is now:

```
let motionModule = (function () {
  return {
    glideMixin: function (obj) { // Space before the parentheses
      obj.glide = function() {
        console.log("Gliding on the water");
      };
    },
    flyMixin: function(obj) {
      obj.fly = function() {
        console.log("Flying, wooosh!");
      };
    }
  }
}) (); // The two parentheses cause the function to be immediately invoked
```
After fix:

```
let motionModule = (function () {
  return {
    glideMixin: function(obj) {  // No space before the parentheses
      obj.glide = function() {
        console.log("Gliding on the water");
      };
    },
    flyMixin: function(obj) {
      obj.fly = function() {
        console.log("Flying, wooosh!");
      };
    }
  }
}) (); // The two parentheses cause the function to be immediately invoked
```
A teaching platform should be enforcing good habits, that includes consistent code formatting.

**Comment by RandellDawson** [comment]
@lasjorg I see the difference now that you commented it.  If you are removing unecessary spaces, then you should get rid of the spaces on the last line:

Instead of:
```
}) (); // The two parentheses cause the function to be immediately invoked
```
it should be:
```
})(); // The two parentheses cause the function to be immediately invoked
```

Honestly, I was not aware of a "best practice" regarding not having a space after the `function` keyword, which is probably why I did not notice an issue to begin with.

**Comment by lasjorg** [comment]
@RandellDawson 

Well the best practice would be to be consistent in the formatting. It's up to the team/person what formatting rules to follow. The curriculum seems to follow the no space style.

Airbnb: Spacing in a function signature
https://github.com/airbnb/javascript#functions--signature-spacing

Eslint space-before-function-paren
https://eslint.org/docs/rules/space-before-function-paren


You are right that space is also inconsistent with the previous assignment style, but I'm not sure if that space is more of a "instructional" nature, i.e. to call attention to the parentheses. But i removed it.

**Comment by RandellDawson** [comment]
Thank you for your contribution to the page! 👍
We're happy to accept these changes, and look forward to future contributions. 🎉

**Pull request merged**
