### PR TITLE
added double quotes condition to Target HTML Elements with jQuery cha…

### LINKED ISSUE #10315: "Target HTML Elements with Selectors Using jQuery" code does past test with single quotes
#### Challenge Name
[Target HTML Elements with Selectors Using jQuery](https://www.freecodecamp.com/challenges/target-html-elements-with-selectors-using-jquery)

#### Issue Description
The instructions say, "Additionally make sure to use $("button").addClass("animated bounce"); instead of $('button').addClass("animated bounce"); since single-quote selectors will not pass our tests."

However, this may be able to be removed since my tests passed using single quotes in the jQuery code.

#### Browser Information
* Browser Name, Version: Chrome, 52.0.2743.116
* Operating System: Mac OSX El Capitan

### PR DESCRIPTION
**Pull request by oalhait**
#### Pre-Submission Checklist

- [x] Your pull request targets the `staging` branch of FreeCodeCamp.
- [x] Branch starts with either `fix/`, `feature/`, or `translate/` (e.g. `fix/signin-issue`)
- [x] You have only one commit (if not, [squash](http://forum.freecodecamp.com/t/how-to-squash-multiple-commits-into-one-with-git/13231) them into one commit).
- [x] All new and existing tests pass the command `npm run test-challenges`. Use `git commit --amend` to amend any fixes.
#### Type of Change

- [x] Small bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds new functionality)
- [ ] Breaking change (fix or feature that would change existing functionality)
- [ ] Add new translation (feature adding new translations)
#### Checklist:

- [x] Tested changes locally.
- [x] Closes currently open issue (replace XXXX with an issue no): Closes #10315 
#### Description

The "Target HTML Elements with jQuery" challenge accepts code that uses single quotes for selectors, so I added an assertion that requires the code to use double quotes rather than single quotes.

### CODE REVIEW

**Comment by dhcodes** [comment]
@oalhait is the edit to the translation in line 152--from `mit` to `imit` intentional?

**Comment by oalhait** [comment]
@dhcodes nope, not intentional. My bad! Should I make a new PR?

**Comment by dhcodes** [comment]
@oalhait You should be able to pull this branch and then amend it. Might have to do a `--force` on the push though.

**Comment by oalhait** [comment]
@dhcodes could you give me a little bit of a tutorial on what to do? sorry, haven't had to do that before with git yet

**Comment by dhcodes** [comment]
@oalhait jump on gitter in the HelpContributor room

**Comment by dhcodes** [comment]
@oalhait if you still have your branch, you can edit it and then do a `git commit --amend` and then push it again with `git push -u origin staging --force`. If you don't have it, you can either pull it from your remote repo or recreate a branch with the same name and remake the change.

**Comment by oalhait** [comment]
got it. thanks @dhcodes !!

**Comment by atjonathan** [comment]
### **LGTM :+1:**
Thanks @oalhait

**Pull request merged**
