### PR TITLE
Fix/Basic CSS: Understand Absolute versus Relative Units - to pass tests with multiple fields before the required padding-ENGLISH

### LINKED ISSUE #35830: CSS challenges - pass/fail related to attribute order
**Describe your problem and how to reproduce it:**
Deliberately tried to break the test by adding superfluous CSS attributes. Requested addition was "padding:1.5em", and the tests are:

Your red-box class should have a padding property.
Your red-box class should give elements 1.5em of padding.

I added CSS attributes in the following order:

    font-family:"Bauhaus 93";
    font-size:3em;
    padding:1.5em;
    color:papayawhip;   

This passed the first test but failed the second.

Next I removed the "font-size" attribute.

    font-family:"Bauhaus 93";
    padding:1.5em;
    color:papayawhip;  

 and retested with the same result.

Finally I restored the font-size attribute but reordered with the "padding" attribute first:

    padding:1.5em;
    font-family:"Bauhaus 93";
    font-size:3em;
    color:papayawhip;  

This passed both tests.

CSS is supposed to be rendered independent of attribute order, so all three attempts should have passed.

**Link to the page with the problem:**
CSS challenge:https://learn.freecodecamp.org/responsive-web-design/basic-css/understand-absolute-versus-relative-units

**Browser and operating system:**
* Browser Name: Avant Ultimate using Firefox/Gecko engine
* Browser Version: Firefox 60.0.0.6708
* Operating System: Windows 10 Professional
screenshot1
screenshot2

### PR DESCRIPTION
**Pull request by icatat**
- [x] I have read [freeCodeCamp's contribution guidelines](https://github.com/freeCodeCamp/freeCodeCamp/blob/master/CONTRIBUTING.md).
- [x] My pull request has a descriptive title (not a vague title like `Update index.md`)
- [x] My pull request targets the `master` branch of freeCodeCamp.
- [x] None of my changes are plagiarized from another source without proper attribution.
- [x] All the files I changed are in the same world language (for example: only English changes, or only Chinese changes, etc.)
- [x] My changes do not use shortened URLs or affiliate links.

Closes #35830

### CODE REVIEW

**Comment by RandellDawson** [comment]
@icatat Would you mind squashing you commits to clean up the history?

**Comment by icatat** [comment]
Thank you @RandellDawson! I just did. Should I do a separate PR for the rest of the translations?

**Comment by RandellDawson** [comment]
@icatat Wait on creating PRs for the other languages (one for each) until this one gets merged.

**Comment by k-mayur** [comment]
test comment api post

**Comment by pratipb** [comment]
document.getElementById('add').value

**Comment by pratipb** [comment]
second comment

**Comment by pratipb** [comment]
1234

**Comment by pratipb** [comment]
wow

**Comment by Dharmin2108** [comment]
...

**Comment by Dharmin2108** [comment]
...

**Comment by Dharmin2108** [comment]
0

**Review by ojeytonwilliams — APPROVED** [review]
Tested locally, LGTM :+1:

**Review by RandellDawson — APPROVED** [review]
LGTM

**Comment by RandellDawson** [comment]
Congrats @icatat on your first pull request (PR)! 🎉

Thank you for your contribution to the page! 👍
We're happy to accept these changes, and look forward to future contributions. 📝

**Comment by icatat** [comment]
Thank you @RandellDawson! Very excited to have my first PR merged! How is the procedure for the rest of the translations? Should just add a few additional PRs?

**Comment by RandellDawson** [comment]
@icatat Don't worry about translating the non-English version of the files.  There are other plans in the works for those files.

**Pull request merged**
