### PR TITLE
Update the sign up view with beta notice

### PR DESCRIPTION
**Pull request by QuincyLarson**
#### Pre-Submission Checklist

- [x] Your pull request targets the `staging` branch of freeCodeCamp.
- [x] Branch starts with either `fix/`, `feature/`, or `translate/` (e.g. `fix/signin-issue`)
- [x] You have only one commit (if not, [squash](http://forum.freecodecamp.com/t/how-to-squash-multiple-commits-into-one-with-git/13231) them into one commit).
- [x] All new and existing tests pass the command `npm test`. Use `git commit --amend` to amend any fixes.

#### Type of Change

- [ ] Small bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds new functionality)
- [ ] Breaking change (fix or feature that would change existing functionality)
- [ ] Add new translation (feature adding new translations)

### CODE REVIEW

**Comment by BerkeleyTrue** [comment]
This won't allow anyone working on freecodecamp to create accounts using emails

**Comment by QuincyLarson** [comment]
@BerkeleyTrue That's correct. We can create accounts for them manually in the database as needed.

**Comment by BerkeleyTrue** [comment]
> We can create accounts for them manually in the database as needed.

This will disable creating accounts for everybody developing with freecodecamp.

**Comment by QuincyLarson** [comment]
Closed in favor of https://github.com/freeCodeCamp/freeCodeCamp/pull/15604

**Pull request closed without merging**
