### PR TITLE
feat(seed): Added more assertions for Project Euler Problem th

### PR DESCRIPTION
**Pull request by alvinkl**
#### Pre-Submission Checklist

- [x] Your pull request targets the `staging` branch of freeCodeCamp.
- [x] Branch starts with either `fix/`, `feature/`, or `translate/` (e.g. `fix/signin-issue`)
- [x] You have only one commit (if not, [squash](http://forum.freecodecamp.org/t/how-to-squash-multiple-commits-into-one-with-git/13231) them into one commit).
- [x] All new and existing tests pass the command `npm test`. Use `git commit --amend` to amend any fixes.

#### Type of Change

- [ ] Small bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds new functionality)
- [ ] Breaking change (fix or feature that would change existing functionality)
- [ ] Add new translation (feature adding new translations)

#### Checklist:

- [x] Tested changes locally.
- [ ] Addressed currently open issue (replace XXXXX with an issue no in next line)

Closes #XXXXX

#### Description

Added more assertions for Project Euler problem 31
Here's the solution

```javascript
function coinSums(n) {
	var target = n;
	var coinSizes = [1, 2, 5, 10, 20, 50, 100, 200];
	var ways = Array.apply(null, { length: n + 1 }).map(w => 0);
	ways[0] = 1;

	for (let i = 0; i < coinSizes.length; i++) {
		for (let j = coinSizes[i]; j <= target; j++) {
			ways[j] += ways[j - coinSizes[i]];
		}
	}

	return ways[n];
}
```

### CODE REVIEW

**Comment by raisedadead** [comment]
@QuincyLarson I am not sure (for my lack of expertise on the topic) what this needs for a QA? Are we able to either merge or close this?

**Comment by scissorsneedfoodtoo** [comment]
Hi @alvinkl, everything with this pull request LGTM! Thank you for your submission and for providing a solution for me to QA with.

**Comment by raisedadead** [comment]
Thanks @scissorsneedfoodtoo for the QA and @alvinkl for this pull request!

**Comment by QuincyLarson** [comment]
@scissorsneedfoodtoo Awesome! Thanks for QA'ing this!

**Pull request merged**
