### PR TITLE
Add translation for new challenge

### LINKED ISSUE #6495: Translation to Spanish: Verify and update translation of basic-bonfires.json

### PR DESCRIPTION
**Pull request by justinian336**
Closes #6495

### CODE REVIEW

**Comment by SaintPeter** [comment]
@vtamara or @jbmartinez Please review.

**Comment by jbmartinez** [comment]
@justinian336 @SaintPeter  It looks fine to me but the expression "simplemente ignóralos", although correct, might be misleading. Perhaps "pásalos intactos" is a better choice.

**Comment by justinian336** [comment]
@SaintPeter thanks, you're right. I'll make the change.

**Comment by justinian336** [comment]
@SaintPeter @jbmartinez thanks, you're right. I'll make the change.

**Comment by justinian336** [comment]
Ups, so I forgot to `--amend` my commit and then tried to squash both of them by rebasing but just ended up messing up with the branch. Should I delete the branch and create a new one from zero?

**Comment by SaintPeter** [comment]
@justinian336 You can always use `git reflog` to find a reference that occurs prior to the failed rebase.  Then you can do `git reset <refnum>` to roll back to that change and try again.

**Pull request closed without merging**
