### PR TITLE
fix/Remove broken twitter links in python curriculum

### PR DESCRIPTION
**Pull request by JoshQuaintance**
Checklist:

- [x] I have read [freeCodeCamp's contribution guidelines](https://contribute.freecodecamp.org).
- [x] My pull request has a descriptive title (not a vague title like `Update index.md`)
- [x] My pull request targets the `main` branch of freeCodeCamp.
- [x] All the files I changed are in the same world language, for example: only English changes, or only Chinese changes, etc.

Related to #41127

The twitter link provided to the cheatsheet does not work anymore because the twitter account has deleted all their tweets including the cheatsheet that we used. In this event, we have to delete this link and on a later PR, a new link to another article will be added.

### CODE REVIEW

**Review by naomi-lgbt — APPROVED** [review]
Looks good to me.

**Review by RandellDawson — APPROVED** [review]
LGTM

**Comment by RandellDawson** [comment]
@nhcarrigan I am thinking we change `Closes #41127` to `Related to #41127`, so the issue is still visible.  What do you think?

**Comment by nhcarrigan** [comment]
Agreed - I don't want to lose track of the note that we need a `news` article.

**Comment by RandellDawson** [comment]
Thank you for your contribution to the page! 👍
We're happy to accept these changes, and look forward to future contributions. 🎉

**Pull request merged**
