### PR TITLE
fix(challenges): Fix typo issue on CSS Grid:Minmax

### LINKED ISSUE #16996: Typo - CSS Grid: Limit Item Size Using the minmax Function
#### Challenge Name
[CSS Grid: Limit Item Size using the minmax Function](https://beta.freecodecamp.org/en/challenges/css-grid/limit-item-size-using-the-minmax-function)

#### Issue Description
For the  challenge, the text states:

> `grid-template-columns: 100px minmax(50px, 200px);`
> 
> In the code above, grid-template-columns is set to create three columns; the first is 100px wide, and the second has the minimum width of 50px and the maximum width of 200px.

This may confuse people who are unfamiliar with the code. Instead, this should read:

> In the code above, grid-template-columns is set to create **two** columns; the first is 100px wide, and the second has the minimum width of 50px and the maximum width of 200px.

#### Screenshot
css-grid-screenshot

### PR DESCRIPTION
**Pull request by Bennet11**
the example explains that grid-template-columns: 100px minmax(50px,
200px) is set to create three columns when in fact it is only set to
create two columns.

#### Pre-Submission Checklist

- [x] Your pull request targets the `staging` branch of freeCodeCamp.
- [x] Branch starts with either `fix/`, `feature/`, or `translate/` (e.g. `fix/signin-issue`)
- [x] You have only one commit (if not, [squash](http://forum.freecodecamp.org/t/how-to-squash-multiple-commits-into-one-with-git/13231) them into one commit).
- [x] All new and existing tests pass the command `npm test`. Use `git commit --amend` to amend any fixes.

#### Type of Change

- [x] Small bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds new functionality)
- [ ] Breaking change (fix or feature that would change existing functionality)
- [ ] Add new translation (feature adding new translations)

#### Checklist:

- [x] Tested changes locally.
- [x] Addressed currently open issue (replace XXXXX with an issue no in next line)

Closes #16996

#### Description

fixed typo error on the description from " is set to create three columns" to  "is set to create `two` columns"

### CODE REVIEW

**Comment by raisedadead** [comment]
Nice work @Bennet11 but there are merge conflicts to resolve, do you know how to do this? There are steps in the contributing guide on how to rebase. If you need you can ask for help in the contributors chat as well.

**Comment by Bennet11** [comment]
@raisedadead I only know how to fix conflicts through text editor but not with a forked project though. Ill try to rebase it. Do i have to merge my newly created branch with my forked staging?

**Comment by raisedadead** [comment]
@Bennet11 

Here is what you git to do:

```
git checkout fix/short-description-fix 
git pull --rebase upstream staging
```

Resolve the conflicts if not solved automatically done for you.

```
git add <file path of the conflict>
git rebase --continue
```

if the conflicts were auto solved then skip the above two commands and jump to the next:

```
git push origin fix/short-description-fix  --force
```

**Comment by Bennet11** [comment]
@raisedadead Thanks! `git rebase --continue is new to me`. Thanks for letting me know!

**Comment by raisedadead** [comment]
Almost there. Can you fill the checklist above in the OP. You can just click on the checkboxes. Also is there any open issue?

**Comment by Bennet11** [comment]
@raisedadead updated the checkbox, ran the program locally and can confirm the changes were made.

**Comment by raisedadead** [comment]
Perfect thanks a lot @Bennet11 we will review and merge this soon.

**Review by ahmaxed — APPROVED** [review]
Thanks for the PR, LGTM 👍

**Pull request merged**
