### PR TITLE
fix: update copyright year in README.md and LICENSE.md

### PR DESCRIPTION
**Pull request by Mike-ops273**
Checklist:

- [x] I have read [freeCodeCamp's contribution guidelines](https://contribute.freecodecamp.org).
- [x] My pull request has a descriptive title (not a vague title like `Update index.md`)
- [x] My pull request targets the `main` branch of freeCodeCamp.
- [x] I have tested these changes either locally on my machine, or GitPod.

Closes #XXXXX

### CODE REVIEW

**Comment by Sboonny** [comment]
we can let GitHub update it annually instead of opening PRs for this. 🤔 

We have done the same thing for chapter https://github.com/freeCodeCamp/chapter/blob/main/.github/workflows/update-license.yaml

**Comment by ShaunSHamilton** [comment]
I thought we came to the realisation we are not supposed to update the copyright year - it is supposed to be the year of first publication/release.

**Comment by Sboonny** [comment]
I remember reading about someone losing a legel case about intellectual property, because the copyright site wasn't up to date.

**Comment by ojeytonwilliams** [comment]
From what I've read either StartYear-CurrentYear or CurrentYear is fine. StartYear alone might be fine, but most of the advice I've seen says you need CurrentYear.

**Review by Sboonny — APPROVED** [review]
#### :sparkles: :tada: **AWESOME!** :tada: :sparkles:

 Hi @Mike-ops273, thanks for this pull request and for contributing to the code-base for the first time. We are looking forward to more contributions from you in the future.

 Cheers & happy contributing!

**Review by raisedadead — APPROVED** [review]

**Comment by Mike-ops273** [comment]
> #### ✨ 🎉 **AWESOME!** 🎉 ✨
> Hi @Mike-ops273, thanks for this pull request and for contributing to the code-base for the first time. We are looking forward to more contributions from you in the future.
> 
> Cheers & happy contributing!

Thanks, it was a pleasure.

**Pull request merged**
