### PR TITLE
Improve instructions in font degrade challenge

### LINKED ISSUE #13457: How Fonts Should Degrade Instructions Unclear
#### Challenge Name

[Specify How Fonts Should Degrade](https://www.freecodecamp.com/challenges/specify-how-fonts-should-degrade#?solution=%0A%3Clink%20href%3D%22https%3A%2F%2Ffonts.googleapis.com%2Fcss%3Ffamily%3DLobster%22%20rel%3D%22stylesheet%22%20type%3D%22text%2Fcss%22%3E%0A%3Cstyle%3E%0A%20%20.red-text%20%7B%0A%20%20%20%20color%3A%20red%3B%0A%20%20%7D%0A%0A%20%20h2%20%7B%0A%20%20%20%20%3C!--font-family%3A%20Lobster%2C%20Monospace%3B--%3E%0A%20%20%7D%0A%0A%20%20p%20%7B%0A%20%20%20%20font-size%3A%2016px%3B%0A%20%20%20%20font-family%3A%20Monospace%3B%0A%20%20%7D%0A%3C%2Fstyle%3E%0A%0A%3Ch2%20class%3D%22red-text%22%3ECatPhotoApp%3C%2Fh2%3E%0A%0A%3Cp%20class%3D%22red-text%22%3EKitty%20ipsum%20dolor%20sit%20amet%2C%20shed%20everywhere%20shed%20everywhere%20stretching%20attack%20your%20ankles%20chase%20the%20red%20dot%2C%20hairball%20run%20catnip%20eat%20the%20grass%20sniff.%3C%2Fp%3E%0A%3Cp%20class%3D%22red-text%22%3EPurr%20jump%20eat%20the%20grass%20rip%20the%20couch%20scratched%20sunbathe%2C%20shed%20everywhere%20rip%20the%20couch%20sleep%20in%20the%20sink%20fluffy%20fur%20catnip%20scratched.%3C%2Fp%3E%0A)

#### Browser Information

* Browser Name, Version: 
* Operating System: 
* Mobile, Desktop, or Tablet: 

#### Your Code

```js



```

### PR DESCRIPTION
**Pull request by Manish-Giri**
#### Pre-Submission Checklist

- [x] Your pull request targets the `staging` branch of freeCodeCamp.
- [x] Branch starts with either `fix/`, `feature/`, or `translate/` (e.g. `fix/signin-issue`)
- [x] You have only one commit (if not, [squash](http://forum.freecodecamp.com/t/how-to-squash-multiple-commits-into-one-with-git/13231) them into one commit).
- [x] All new and existing tests pass the command `npm test`. Use `git commit --amend` to amend any fixes.

#### Type of Change

- [x] Small bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds new functionality)
- [ ] Breaking change (fix or feature that would change existing functionality)
- [ ] Add new translation (feature adding new translations)

#### Checklist:

- [x] Tested changes locally.
- [x] Closes currently open issue (replace XXXX with an issue no): Closes #13457 

#### Description

Reworded instructions as per suggestion in issue. I removed these lines - 
> You'll also have to make sure the heading font gets degraded to <code>Monospace</code>. Some CSS changes will be necessary for this.

I think the first line is redundant and the second one is somewhat vague. The new instruction should be clearer by itself - 

screenshot 2017-02-22 19 45 09

Closes #13457

### CODE REVIEW

**Comment by dhcodes** [comment]
@Manish-Giri if we make this change, we should probably add `Monospace` as the `h2` fallback font in the editor when the page loads or else these new instructions don't make sense.

**Comment by Manish-Giri** [comment]
@dhcodes Oh yes, I didn't notice the updated `challengeSeed`. I remembered the current production site does have `Monospace` on as the fallback- 
```
  h2 {
    font-family: Lobster, Monospace;
  }
```

**Comment by raisedadead** [comment]
@Manish-Giri thanks for the PR. Here is the change https://github.com/freeCodeCamp/freeCodeCamp/pull/13448, well I am honestly not sure that it actually achieved the re-wording part.

**Comment by raisedadead** [comment]
Can you suggest a better instruction? Maybe something on the lines of adding the Monospace font, manually?

**Comment by Manish-Giri** [comment]
@raisedadead How about something like this?

> 
>`<hr>`
> To begin with, apply the `Monospace` font to the `h2` element, so that it now has two fonts - `Lobster` and `Monospace`.
> In the last challenge, you imported the <code>Lobster</code> font using the <code>link</code> tag. Now comment out that import of the <code>Lobster</code> font from Google Fonts so that it isn't available anymore. Notice how your <code>h2</code> element degrades to the <code>Monospace</code> font when `Lobster` isn't available.
> Note ...

I think with this way, you would also ensure that the challenge isn't too "easy", with the `Monospace` font being applied to the `h2` by default - which, I think, was the original intent of #13448.

Also, applying `Monospace` to `h2` along with `Lobster` shouldn't be much of a problem, as there's an example right in the description - 
```
"<blockquote>p {<br>&nbsp;&nbsp;font-family: Helvetica, Sans-Serif;<br>}</blockquote>",
```

Your thoughts?

**Comment by raisedadead** [comment]
@Manish-Giri sounds good to me.

**Comment by sharan-reddy** [comment]
Hi

**Comment by Manish-Giri** [comment]
@raisedadead Done!

**Comment by dhcodes** [comment]
**LGTM**. Keep up the good work! Thanks for contributing 🐔 💯 🐿

**Pull request merged**
