### PR TITLE
fix(curriculum): build a survey form - update instructions

### LINKED ISSUE #54796: [Certification Projects] Show a dialog when user leaving the page
## Description

On practice challenge pages, the code is automatically saved to the browser storage when the user clicks the test button. This isn't the case with the certification project pages, the code is not saved unless the user clicks the "Save your Code" button.

We have received multiple reports of users losing their code changes after they closed the tab or navigated away from the page, without pressing the save button.

I think one way to prevent this is to update the instruction text and mention that the user needs to manually save their progress. 

Though I'm not sure where the text should be added. Perhaps at the end of the instruction and as a note?

```md
Fulfill the user stories and pass all the tests below to complete this project. Give it your own personal style. Happy Coding!

Notes:
- [Other notes related to the project requirements]
- Your code is not automatically saved. Be sure to click the "Save your Code" button to save your progress.
```

## Affected pages

Certification projects.

Example: https://www.freecodecamp.org/learn/2022/responsive-web-design/build-a-survey-form-project/build-a-survey-form

## Additional context

Other UI/UX improvements are discussed in #53000.

### PR DESCRIPTION
**Pull request by nayelimdejesus**
Checklist:

- [x] I have read and followed the [contribution guidelines](https://contribute.freecodecamp.org).
- [x] I have read and followed the [how to open a pull request guide](https://contribute.freecodecamp.org/how-to-open-a-pull-request/).
- [x] My pull request targets the `main` branch of freeCodeCamp.
- [x] I have tested these changes either locally on my machine, or GitPod.

Closes #54796

### CODE REVIEW

**Comment by moT01** [comment]
Thanks for the PR - I guess this doesn't really hurt anything, but this is not the solution discussed in the issue. I am going to close this for now, because I think the issue needs some more discussion. If you think I'm wrong, feel free to leave a message and we can revisit it.

**Comment by moT01** [comment]
Actually, I am going to open this back up. We can use this as a temporary solution while we figure out something better. We would need to add this note to all of the projects though. You should be able to do a search for `challengeType: 14` to find them all @nayelimdejesus. If you do that, I think we would be able to merge this.

**Comment by ojeytonwilliams** [comment]
Hi @nayelimdejesus do you think you'll have time to address Tom's concerns?

**Comment by moT01** [comment]
Closing this as inactive. If you want to add the suggestions @nayelimdejesus - feel free to make a new PR with those additions. Thanks and happy coding 🎉

**Pull request closed without merging**
