### PR TITLE
Added 3 D3 challenge solutions

### PR DESCRIPTION
**Pull request by thecodingaviator**
- [x] I have read [freeCodeCamp's contribution guidelines](https://github.com/freeCodeCamp/freeCodeCamp/blob/master/CONTRIBUTING.md).
- [x] My pull request has a descriptive title (not a vague title like `Update index.md`)
- [x] My pull request targets the `master` branch of freeCodeCamp.
- [x] None of my changes are plagiarized from another source without proper attribution.
- [x] My article does not contain shortened URLs or affiliate links.

If your pull request closes a GitHub issue, replace the XXXXX below with the issue number.

Closes #XXXXX

### CODE REVIEW

**Review by RandellDawson — DISMISSED** [review]
Can you please modify your code so that it has two space indentation throughout?

**Comment by thecodingaviator** [comment]
@RandellDawson The indentation is the same as the one on the website as the code has been directly copied from there. I don't think this should be a problem

**Comment by thecodingaviator** [comment]
Thanks @QuincyLarson

**Comment by RandellDawson** [comment]
@thecodingaviator I was just going by what the Styling Guide suggested which is 2 space indentation.

**Comment by thecodingaviator** [comment]
Oh okay, sorry. I’ll keep an eye out next time

**Pull request merged**
