### PR TITLE
feat: use ast-based helpers

### PR DESCRIPTION
**Pull request by ojeytonwilliams**
Checklist:

- [x] I have read and followed the [contribution guidelines](https://contribute.freecodecamp.org).
- [x] I have read and followed the [how to open a pull request guide](https://contribute.freecodecamp.org/#/how-to-open-a-pull-request).
- [x] My pull request targets the `main` branch of freeCodeCamp.
- [x] I have tested these changes either locally on my machine, or GitPod.

This makes use of the new tools for evaluating python code, recently added to https://github.com/freeCodeCamp/curriculum-helpers/ and documented
[here](https://opensource.freecodecamp.org/curriculum-helpers/python.html#ast-based-helpers)

I added a sample curriculum test and there are a bunch of tests of the code itself in the [curriculum-helpers](https://github.com/freeCodeCamp/curriculum-helpers/blob/main/python/py_helpers.test.py). They demonstrate multiple ways to use the library.

### CODE REVIEW

**Comment by ojeytonwilliams** [comment]
I'm not sure why the Italian and Portuguese are failing here, but not in main. The next challenge (step 37) is missing, but that's true for main, too.

I'll dig into that, but otherwise this should be good to go.

**Review by ShaunSHamilton — APPROVED** [review]
Makes sense, but I thought we wanted to move away from using the _fake filesystem_ because it was messing up tests?

**Review by ShaunSHamilton — APPROVED** [review]

**Comment by ojeytonwilliams** [comment]
Ooof, more regex issues. @ShaunSHamilton if you've got any ideas, let me know, otherwise I'll have another go.

**Comment by ShaunSHamilton** [comment]
@ojeytonwilliams Why is just the `i18n` stuff failing?

**Comment by ojeytonwilliams** [comment]
> @ojeytonwilliams Why is just the `i18n` stuff failing?

I've not dug into it, but they must have different solutions since they're not syncing properly at the moment. 

Assuming that's correct, those solutions are confusing the regex, but are probably valid python.

**Comment by ShaunSHamilton** [comment]
This should fix the failing test: https://github.com/freeCodeCamp/curriculum-helpers/pull/148

Here is `/english/`:

```python
        else:
            
            key_char = key[key_index % len(key)]
```

Here is `/portugues/`:

```python
        else:

            key_char = key[key_index % len(key)]
```

**Review by Sembauke — APPROVED** [review]

**Pull request merged**
