### PR TITLE
fix(curriculum): added extra line before </section> tag - English challenges

### PR DESCRIPTION
**Pull request by RandellDawson**
- [x] I have read [freeCodeCamp's contribution guidelines](https://github.com/freeCodeCamp/freeCodeCamp/blob/master/CONTRIBUTING.md).
- [x] My pull request has a descriptive title (not a vague title like `Update index.md`)
- [x] My pull request targets the `master` branch of freeCodeCamp.
- [x] None of my changes are plagiarized from another source without proper attribution.
- [x] All the files I changed are in the same world language (for example: only English changes, or only Chinese changes, etc.)
- [x] My changes do not use shortened URLs or affiliate links.

Related to PR #35829

Using the following search regex search pattern in VS Code, I was able to find/replace all instances (944 of them) in 943 files where the closing fence backticks did not have an extra line before a closing`</section> tag.

Capture

I also went through all of the outstanding open PRs which make changes to the solution section and added extra lines where necessary.  This should avoid merge conflicts as much as possible.

@raisedadead Once @ojeytonwilliams gets his PR ready to go, he wants to have this one reviewed/merged first.

### CODE REVIEW

**Review by ojeytonwilliams — APPROVED** [review]
So... The regex looks good and I ran the changed files through `npm run lint:challenges` in #35829.  A lot of the lint errors vanished and no new ones appeared.  I didn't check every file by hand, but the sample I looked at were all fine.  In other words, LGTM!

**Comment by ojeytonwilliams** [comment]
Since #35829 is going to entail more changes to the markdown before it passes, I think it makes sense to merge this first to reduce the noise on other any other PRs we write.

**Comment by raisedadead** [comment]
I think here is what we will do, once both the PRs are ready you should just let me know, and we can land this on a separate branch quickly test and look how the CI behaves and then land all the changes on master.

**Comment by ojeytonwilliams** [comment]
In that case, how about I create another PR with the manual changes?  Just the changes `markdownlint` asks for, but that `prettier` doesn't fix.

**Comment by RandellDawson** [comment]
@thecodingaviator , @moT01 Can someone else review and get this one merged?

**Review by raisedadead — APPROVED** [review]

**Pull request merged**
