### PR TITLE
fix(client): Fix print media queries for certificate

### LINKED ISSUE #46965: Certification printing / saving as PDF not formatted correctly
**Describe the bug**
Certifications are not correctly formatting when downloading / printing.

**To Reproduce**
View a certification. For example: https://www.freecodecamp.org/certification/mainlycoding/javascript-algorithms-and-data-structures

Then right click save as PDF or print. You will see the formatting jumbled, despite efforts to manually resize. The signature, for example, is way too big.

**Screenshots**
Here's the twitter thread with some screenshots: https://twitter.com/Lebron29ayy/status/1549522926751318017/photo/1

**Desktop (please complete the following information):**
 - Browser: latest Chrome and Firefox tested – it doesn't work in either

### PR DESCRIPTION
**Pull request by amorimr**
Checklist:

- [x] I have read [freeCodeCamp's contribution guidelines](https://contribute.freecodecamp.org).
- [x] My pull request has a descriptive title (not a vague title like `Update index.md`)
- [x] My pull request targets the `main` branch of freeCodeCamp.
- [x] I have tested these changes either locally on my machine, or GitPod.

Closes #46965

The issues with the certificate printing layout were originated from two points:

- Some styles coming from bootstrap css that were interfering with the layout:
image

- The media queries had the `screen` media type, making the layout lose responsiveness when printing

This PR fixes these issues by overriding the bootstrap css rules and applying the certificate media queries to both print and screen layouts. 

image

### CODE REVIEW

**Comment by ahmadabdolsaheb** [comment]
Thanks for working on this pr, @amorimr. This is a huge improvement over what we had. Here is what I see on my macOS Monterey 12.2:

Chrome Version 103.0.5060.114 (Official Build) (arm64):
Screen Shot 2022-07-27 at 2 42 10 PM

Firefox 102.0.1 (64-bit):
Screen Shot 2022-07-27 at 2 43 32 PM

You are in the right direction. It seems like it would need a little more touch ups and it should be good to go.

**Comment by amorimr** [comment]
Thank you for the feedback, @ahmadabdolsaheb. I've made some adjustments to keep the certificate borders and backgrounds visible at all times when printing: 

Firefox:
Screen Shot 2022-07-27 at 4 58 21 PM

Chrome:
Screen Shot 2022-07-27 at 4 58 50 PM


Let me know if there are any additional adjustments to be made!

**Review by moT01 — COMMENTED** [review]
This is looking good @amorimr 👍 I think I would be fine merging this since it's such an improvement, but I see a few things that could still be improved...

1. Typically, I'm used to seeing certifications like this in landscape mode - where the certification fits the page nicely. I think if I were to want to print mine, I would rather it be like that. When I click landscape, it doesn't fit a single page or fill the page very well:
Screen Shot 2022-07-28 at 9 32 20 AM

A quick search of certification images shows a mix of portrait and landscape, so I don't think we necessarily need it to work with landscape - but that's my preference anyway. I would be fine if it only worked with portrait mode. Edit: I do think our certs were designed more for, and look better in, landscape mode.

2. Related to the above thought, portrait mode is a little off center vertically:
Screen Shot 2022-07-28 at 9 45 50 AM

^ print preview - extra space at the top. Not a huge deal either, but it would be nice if was centered and filled the page a little more.

3. It looks like you are hiding the donate section and the share buttons, I would vote to hide that section at the bottom that shows the projects a camper created, as well.

**Comment by amorimr** [comment]
Thank you for the review and suggestions, @moT01. I've made some adjustments on the margins and on the certificate for printing on landscape mode. Let me know if there are any other issues!

image

**Comment by naomi-lgbt** [comment]
On portrait it looks good:

image

On landscape we are almost there:

image


__
[sema-logo](https://semasoftware.com/gh) &nbsp;**Summary:** :hammer_and_wrench: This code needs a fix

**Comment by amorimr** [comment]
> On portrait it looks good:
> 
> image
> 
> On landscape we are almost there:
> 
> image
> 
> __ [sema-logo](https://semasoftware.com/gh) [ sema-logo ](https://semasoftware.com/gh) [ ](https://semasoftware.com/gh)  **Summary:** 🛠️ This code needs a fix

Thank you for the comment, @naomi-lgbt. I've made some adjustments, let me know if there is still any issue.

**Review by moT01 — APPROVED** [review]
This LGTM @amorimr 🎉

Portrait:
Screen Shot 2022-08-08 at 11 53 20 AM

Landscape:
Screen Shot 2022-08-08 at 11 53 27 AM

I think these look real good and I would be fine merging this. Some more thoughts though... pretty minor - they could both fill the page a little more, there's still some space around the outside of the blue - not saying it needs to go to the edge, but maybe a little further. Portrait has a lot of space at the bottom, we could try and make it more like the original image. Could maybe add a print button to the certificate page?

These are just some thoughts and pretty minor. I would leave it like this for now @amorimr and see if we're ready to get this in.

**Comment by naomi-lgbt** [comment]
This looks great on Firefox. I'm still getting a slight overflow on Chrome, but it might be something local to my setup?

**Comment by ahmadabdolsaheb** [comment]
I checked the certificate on both browsers and they look great. Solid work @amorimr and congrats on landing your first freeCodeCamp pull-request.

**Review by ahmaxed — APPROVED** [review]

**Pull request merged**
