### PR TITLE
Replace Github with GitHub

### PR DESCRIPTION
**Pull request by lipis**
I used VS Code editor to search and replace all occurrences of `Github` to `GitHub`.

- [x] I have read [freeCodeCamp's contribution guidelines](https://github.com/freeCodeCamp/freeCodeCamp/blob/master/CONTRIBUTING.md).
- [x] My pull request has a descriptive title (not a vague title like `Update index.md`)
- [x] My pull request targets the `master` branch of freeCodeCamp.
- [x] None of my changes are plagiarized from another source without proper attribution.
- [x] All the files I changed are in the same world language (for example: only English changes, or only Chinese changes, etc.)
- [x] My changes do not use shortened URLs or affiliate links.

### CODE REVIEW

**Comment by RandellDawson** [comment]
@lipis There is a reason for the 5th checkbox. We expect changes to files of different languages to be on different PRs.  The reason is because in case you made any changes to the translation, those PRs would be handled by a translation reviewer for that specific language.  

While your PRs states you only changed `Github` to `GitHub`, other sections "appear" to be changed entirely (see below).  Without carefully reviewing every section, it will take some time to review this PR.

Would you mind creating separate PRs for these changes by language, so the other languages can be checked in case something else got changed?  Also, make sure you are only changing `Github` to `GitHub`.

image

**Comment by lipis** [comment]
@RandellDawson I updated the PR and now there are only changes in the English versions.

I only changed Github to GitHub, but if the block is too big GitHub UI is not that smart to show it correctly.

**Comment by RandellDawson** [comment]
@lipis Thanks for breaking this up to the English files.  I have reviewed all the changes and they look fine to me.  I am going to let a couple other mods review/approve this before we consider merging it.  Keep in mind there are about 40 other earlier PRs which makes changes to one or more of the files in this PR and try to merge from oldest PR to newest PR for a given file.  This means, it could be a while before we actually merge this one.  Overall, we have 4500+ PRs we are working our way through currently.

**Review by RandellDawson — APPROVED** [review]

**Review by raisedadead — APPROVED** [review]

**Comment by lipis** [comment]
Thanks @RandellDawson! There is definitely no rush from my side.. and I'm pretty aware how this open source works :) I can update the other languages once this one is in.. but for now good luck with the rest of the PRs.

**Comment by RandellDawson** [comment]
Thank you for your contribution to the page! 👍
We're happy to accept these changes, and look forward to future contributions. 🎉

When you have the time, please continue with creating separate PRs with the same changes for each of the other languages.

**Pull request merged**
