### PR TITLE
fix: make superblock data paths match normal paths

### PR DESCRIPTION
**Pull request by ojeytonwilliams**
@Sembauke I know you had reservations about this, but it's less hacky if the /curriculum-data paths match the /learn paths.  I figured I'd create the PR quickly, so we have something concrete to discuss!

### CODE REVIEW

**Comment by Sembauke** [comment]
Yes we can!

**Comment by ojeytonwilliams** [comment]
Perfect, thanks for confirming. That makes things a lot simpler!

**Comment by Sembauke** [comment]
Hey Oliver,
Is there no "hours" key available on the Coding Interview Prep? 

Could we make it a string instead of an integer?

**Comment by ojeytonwilliams** [comment]
> Is there no "hours" key available on the Coding Interview Prep?

Nope, it's just "Thousands of hours of challenges".

> Could we make it a string instead of an integer?

Yes, but why?  It's always an integer.

**Review by raisedadead — DISMISSED** [review]

**Comment by Sembauke** [comment]
> @Sembauke since we're looking to remove the hours from the /learn map, do you still want them for mobile? It's totally fine if you do and /learn still wants them for the certifications, but I thought I'd check :)

I am fine with leaving them out, I would love a way of displaying the icons though. But we can talk about that on chat.

**Comment by Nirajn2311** [comment]
Those icons are from Font Awesome IIRC so if we get the name of the icon then we would be able to display the right one

**Review by Sembauke — APPROVED** [review]

**Review by moT01 — APPROVED** [review]
LGTM 🎉

**Pull request merged**
