### PR TITLE
fix: typo in javascript-algorithms-and-data-structures > object-orien…

### LINKED ISSUE #44828: Minor typo in javascript-algorithms-and-data-structures > object-oriented-programming > understand-own-properties
## Affected page

https://www.freecodecamp.org/learn/javascript-algorithms-and-data-structures/object-oriented-programming/understand-own-properties
## To reproduce

There is a typo in one of the code blocks.  There is an extra space in the following line between "name" and "=":

this.name  = name;
## Recommended fix, suggestions

Remove the extra space.

## Screenshots
Screenshot 2022-01-18 180915

### PR DESCRIPTION
**Pull request by Palakash27**
javascript-algorithms-and-data-structures > object-oriented-programming > understand-own-properties

Checklist:
- [x] I have read [freeCodeCamp's contribution guidelines](https://contribute.freecodecamp.org).
- [x] My pull request has a descriptive title (not a vague title like `Update index.md`)
- [x] My pull request targets the `main` branch of freeCodeCamp.
- [x] I have tested these changes either locally on my machine, or GitPod.

Closes #44828

Removed extra space in between the code

### CODE REVIEW

**Comment by nhcarrigan** [comment]
Heya @Palakash27!

Thanks for your interest in contributing! I saw the discussion in the contributors room - it looks like you might have "reverted" the changes on the wrong line, resulting in a second change instead.

There are a couple of ways to fix this:
- You could manually undo all of the changes (not really recommended)
- You can rebase this branch and start fresh (we can help with this process in the contributors room if needed 😄 )
- You could also close this PR and make a new one from a fresh branch, but this isn't really the best practise.

**Review by naomi-lgbt — APPROVED** [review]
Nice work getting those changes reverted. This looks good to me now!

**Review by gikf — APPROVED** [review]
Looks good :+1:

**Comment by gikf** [comment]
Hi @Palakash27. Congrats on your first pull request (PR)! 🎉

Thank you for your contribution to the page! 👍
We are happy to accept these changes and look forward to future contributions. 📝

**Pull request merged**
