### PR TITLE
Remove the random compliment that has no gender neutral alternative

### PR DESCRIPTION
**Pull request by padi**
#### Pre-Submission Checklist
- [x] Your pull request targets the `staging` branch of freeCodeCamp.
- [x] Branch starts with either `fix/`, `feature/`, or `translate/` (e.g. `fix/signin-issue`)
- [x] You have only one commit (if not, [squash](http://forum.freecodecamp.org/t/how-to-squash-multiple-commits-into-one-with-git/13231) them into one commit).
- [x] All new and existing tests pass the command `npm test`. Use `git commit --amend` to amend any fixes.

#### Type of Change
- [x] Small bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds new functionality)
- [ ] Breaking change (fix or feature that would change existing functionality)
- [ ] Add new translation (feature adding new translations)

#### Checklist:
- [x] Tested changes locally.
- [x] Addressed currently open issue

Closes https://github.com/freeCodeCamp/freeCodeCamp/issues/15999

#### Description
Changes one the random compliments to work for any gender. My girlfriend was working through one of the lessons when she encountered it.

### CODE REVIEW

**Comment by texas2010** [comment]
Please open an issue about that. thanks

**Comment by BtheGit** [comment]
Perhaps use a gender neutral word like 'ruler' instead?

**Comment by raisedadead** [comment]
Hi @padi we would rather have this compliment removed all together. You are of course more than welcome to add more compliments/memes too.

I would recommend you should update this pull request and remove the compliment, this does not cover the entire spectrum in any case.

**Comment by padi** [comment]
Fixed it. Thanks for the feedback! Looking forward to finishing more freeCodeCamp content. :) 👍

**Comment by raisedadead** [comment]
#### :sparkles: :sparkles: **LGTM.** :sparkles: :sparkles: 

Thanks @padi and congrats on your first contribution to freeCodeCamp!

Happy fixing!

**Pull request merged**
