### PR TITLE
Cleaning up the iPhone frame

### PR DESCRIPTION
**Pull request by ahstro**
Okay, so I noticed that when trying to click and drag the scrollbar next to the code editor, this happened (the red dot is representing my cursor): 

Upon investigation, I noticed that the image being used consisted of about 66% transparent background. Cool, easy fix! Or not.
When trimming the transparency from the image, it ended up misaligned, of course, so I went digging through the related code and decided to trim a bit off of that as well.

Since I don't have access to your Amazon server I just went ahead and stored the new image locally; you guys have an [Offline Mode](https://github.com/FreeCodeCamp/freecodecamp/milestones/Offline%20Mode!) milestone anyway, right?

Edit: Oh, and remember to test this. I did my best, checked it on a few different challenges and with a few different screen sizes/resolutions, and everything seemed fine, but you can never be too sure.

### CODE REVIEW

**Comment by BerkeleyTrue** [comment]
Not a big fan of storing the image in Github. Ideally offline mode would pull down images it needed from their source on activation. Lets remove it for this PR.

**Comment by ahstro** [comment]
Yeah, I see your points, gets really big really quickly. Could you upload the image to your Amazon server then, so I can replace the link?

**Comment by benmcmahon100** [comment]
I fixed this today by fudging the z-index so it should be perma fixed!

**Comment by ahstro** [comment]
@benmcmahon100 Could you link to the relevant commits?

**Comment by benmcmahon100** [comment]
@ahstro #uberHax https://github.com/FreeCodeCamp/FreeCodeCamp/commit/fe102bdf51ae0b8ffcceab682d78d63cf75d2898

**Comment by ahstro** [comment]
I don't mean to be rude, but that doesn't really address the fact that we have an image that is almost thrice as large as necessary nor the 10 lines of JavaScript and 6 lines of CSS that can be eliminated if this is handled my way.

**Comment by benmcmahon100** [comment]
This is totally true but it fixes the issue immediately and I can't resize the image so it was the best way to sort it at the time

**Comment by benmcmahon100** [comment]
Like i said it's reeeeeaaaalllllly hacky but it solves the immediate issue

**Comment by ahstro** [comment]
Okay, but could you reopen the pull request so it can be merged if @BerkeleyTrue or someone uploads a trimmed version to the AWS?

**Comment by benmcmahon100** [comment]
@QuincyLarson

**Comment by ahstro** [comment]
Thank you @benmcmahon100 :)

**Comment by BerkeleyTrue** [comment]
@ahstro I would rather see us move to a css option http://purecssapple.com/  :+1:

**Comment by ahstro** [comment]
@BerkeleyTrue I'll take a look after I get some food. Which iPhone version would you prefer?

**Comment by BerkeleyTrue** [comment]
Whats to most populous iPhone? I believe it is the 5.

**Comment by ahstro** [comment]
The 6 has a bigger screen and smaller frame, so there's more space for actual content. But I can use the 5 if that's better?

**Comment by BerkeleyTrue** [comment]
Which ever is the most common. This should be done in a new PR.

**Comment by ahstro** [comment]
I'll submit one once I get it working properly. Closing this in the meantime.

**Comment by QuincyLarson** [comment]
Hi everyone, this is an issue of aesthetics, not an issue of efficiency. The pure CSS solutions don't look as true as this (11kb) image does. It is literally how an iPhone 6 looks. Changing to an iPhone 5 is a non-starter imho because it would date the look of the page.

**Comment by ahstro** [comment]
@QuincyLarson I really preferred the CSS version, but if you've decided against it, you should really consider merging this PR. As you can see, it removes some code that executes on every `scroll` event, which should make the pages a bit more efficient.

**Comment by QuincyLarson** [comment]
Hi @ahstro Your image doubled the size of the file (from 8kb to 16kb). It may have allowed for elimination of some JavaScript, but you should be able to accomplish this without increasing the file size of the PNG. 

Also, we don't want these served locally. If you're able to make a suitable PNG, I can upload it to S3 for you.

Finally, note that we are moving to React ASAP. This doesn't seem like a big enough issue to bother with considering we are about to completely rearchitect the view.

I am closing this PR and you can create a new PR if you are able to make the PNG smaller losslessly and also remove those lines of JavaScript.

Thanks for your patience and help with this long PR cycle.

**Pull request closed without merging**
