### PR TITLE
fix(curriculum): fixed typo in challenge description

### LINKED ISSUE #48806: New JS course (build an rpg): should "Hello World" be enclosed in backticks
### Describe the Issue

Should the string "Hello World" be enclosed in backticks in order for the translators to know that it should not be translated?
Specific strings that I noticed this issue in below:

15-javascript-algorithms-and-data-structures-22/learn-basic-javascript-by-building-a-role-playing-game/62a3c8bf3980c14c438d2aed.md:
For now, make your `goStore` function output the message `Going to store.` to the console. For example, here is a function that outputs the message "Hello World".

15-javascript-algorithms-and-data-structures-22/learn-basic-javascript-by-building-a-role-playing-game/62a3c0ab883fd9435cd5c518.md:
Comments allow you to add notes to your code. In JavaScript, single-line comments can be written with `//` and multi-line comments can be written with `/*` and `*/`. For example, here are single and multi-line comments that say "Hello World":

### Affected Page

as described in main description

### Your code

```

```

### Expected behavior

If the string "Hello World" should not be translated, then perhaps it should be enclosed in backticks.

### Screenshots

_No response_

### System

N/A

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by andriy-koz**
Checklist:

- [x] I have read [freeCodeCamp's contribution guidelines](https://contribute.freecodecamp.org).
- [x] My pull request has a descriptive title (not a vague title like `Update index.md`)
- [x] My pull request targets the `main` branch of freeCodeCamp.
- [x] I have tested these changes either locally on my machine, or GitPod.

Closes #48806

### CODE REVIEW

**Review by gikf — APPROVED** [review]
LGTM :+1: 

---

Note for future - it is recommended to make changes on a separate branch, than the `main` branch. See more about it in point 3 at https://contribute.freecodecamp.org/#/how-to-contribute-to-the-codebase?id=contributing-to-the-codebase.

**Comment by gikf** [comment]
Hey @andriy-koz,

no need to keep updating PR branch, with newest changes from `freeCodeCamp:main`, at this point.

**Comment by andriy-koz** [comment]
> Hi @gikf, oh i see that every update gets reflected on this PR, that's why its recommended to have a separate branch for every issue i think. Thank you for following this. Should i just close this and make a new clean one?

**Comment by gikf** [comment]
> Hi @gikf, oh i see that every update gets reflected on this PR, that's why its recommended to have a separate branch for every issue i think. Thank you for following this. Should i just close this and make a new clean one?

No need to right now

**Review by Sembauke — APPROVED** [review]

**Comment by gikf** [comment]
Hi @andriy-koz. Congrats on your first pull request (PR)! 🎉

Thank you for your contribution to the page! 👍
We are happy to accept these changes and look forward to future contributions. 📝

**Comment by andriy-koz** [comment]
> Hi @andriy-koz. Congrats on your first pull request (PR)! tada
> 
> Thank you for your contribution to the page! +1 We are happy to accept these changes and look forward to future contributions. memo

@gikf thank you for your support and advice. Hope to keep contributing on this amazing project and learning by the way.

**Pull request merged**
