### PR TITLE
feat: Added new weighted and directed graphs challenge

### PR DESCRIPTION
**Pull request by ptkpyitheim**
Checklist:

- [x] I have read [freeCodeCamp's contribution guidelines](https://contribute.freecodecamp.org).
- [x] My pull request has a descriptive title (not a vague title like `Update index.md`)
- [x] My pull request targets the `master` branch of freeCodeCamp.
- [x] All the files I changed are in the same world language, for example: only English changes, or only Chinese changes, etc.

Closes #XXXXX

There was a feature request on Graph/Shortest Path Coding Challenge Suggestion ( Issue No: #39238 ) and I thought this would be a necessary introduction to directed and weighted graphs before throwing in Graph/Shortest Path Coding Challenge.

I am contributing to FreeCodeCamp with two other teammates for a course that we are taking. We would love to contribute new challenges under Coding Interview Prep -> Data Structures. After really good introductions to Graphs including DFS and BFS, we thought Dijkstra's algorithm, A* and other famous problems would complement the knowledge even better.

One small issue: We couldn't figure out what to put under forumTopicId in the markdown file. We searched through the documentations and contribution guidelines and couldn't find a solution. As a result, our challenge supposedly should be under Depth-First Search challenge but it's currently on top.

Happy to clarify about these better. Thank you for your consideration!

### CODE REVIEW

**Review by naomi-lgbt — CHANGES_REQUESTED** [review]
https://github.com/freeCodeCamp/freeCodeCamp/blob/master/curriculum/challenges/_meta/data-structures/meta.json

Heya~! It looks like (from what I can tell in the Travis logs) the build is failing because the meta.json for the data structures section doesn't include your new challenge. I would recommend trying to add this, 
and testing locally to ensure the build will run properly (the two commands Travis runs are `npm run lint` and `npm test`).

**Comment by RandellDawson** [comment]
@raisedadead This PR includes an image for the challenge.  For accessibility and the fact that the image is hosted on GitHub, what do recommend?

**Comment by moT01** [comment]
I created a [forum topic for this](https://forum.freecodecamp.org/t/freecodecamp-challenge-guide-weighted-and-directed-graphs/418501) @ptkpyitheim - use `418501` for the `forumTopicId`

**Comment by ptkpyitheim** [comment]
I'm taking a look...

**Comment by raisedadead** [comment]
Hi @RandellDawson,

I am not sure if there is a better way for images given the context of this challenge, I am going to defer to your best judgement.

**Comment by RandellDawson** [comment]
@ptkpyitheim What is the source of these images?  Who owns them?  

@raisedadead If we have the right to use the images, don't we need to host them on our CDN?

@ptkpyitheim On a side note, the challenge instructions do not explain how to create an adjacency matrix (the algorithm so to speak) for a weighted directed graph.  It just shows an example of a graph and what it looks like.  I think this challenge could benefit from such details. I also notice the instructions state to create an adjacency matrix with 5 nodes, yet there are only 4 nodes in the graph.

Since both this challenge and [this existing challenge on creating an adjacency matrix for unweighted undirected graph](https://www.freecodecamp.org/learn/coding-interview-prep/data-structures/adjacency-matrix) are both challenges about creating adjacency matrices, I kind of feel we should rename both of them.

The existing one could be:

`Create an Adjacency Matrix for an Unweighted Undirected Graph`

and the challenge for this PR could be:

`Create an Adjacency Matrix for an Weighted Directed Graph`

**Comment by Sky020** [comment]
@RandellDawson I agree with your suggestion to rename both related lessons. Majority of the other lessons have the structure: `verb` - `subject` - `noun`

To risk bikeshedding: I do not think _"an weighted"_ is correct 🤷‍♂️

**Comment by RandellDawson** [comment]
For now we are going to block this PR until after the schema migration takes place and revisit exactly what needs to happen on for the changes this PR introduces as well as the other challenge.

**Comment by raisedadead** [comment]
Hey @RandellDawson I just rebased this PR. I think that this can be unblocked and merged.

**Comment by RandellDawson** [comment]
@raisedadead I had blocked it originally because some more discussion needs to take place about this challenge.  It is really not ready to be merge.

**Comment by raisedadead** [comment]
Thanks for confirming.

**Pull request closed without merging**
