### PR TITLE
fix(docs): typo in how to work on coding challenges

### PR DESCRIPTION
**Pull request by Chelsgray**
Changed "changes" to "challenges in the last line of The 2-minute rule section

Checklist:

- [x] I have read [freeCodeCamp's contribution guidelines](https://contribute.freecodecamp.org).
- [x] My pull request has a descriptive title (not a vague title like `Update index.md`)
- [x] My pull request targets the `main` branch of freeCodeCamp.
- [ ] I have tested these changes either locally on my machine, or GitPod.

Closes #XXXXX

### CODE REVIEW

**Comment by hanswang123456** [comment]
Might be good to open an issue on this too, just so there is a trace for the actual problem.

**Comment by Chelsgray** [comment]
I definitely can if needed. I was just going by the documentation that says for spelling and other wording changes, creating an issue is not necessary.

**Review by raisedadead — APPROVED** [review]

**Comment by raisedadead** [comment]
#### :sparkles: :sparkles: **AWESOME!** :sparkles: :sparkles: 

LGTM.

Thanks for this pull request, @Chelsgray, and for contributing to the codebase for the first time.

We will be looking forward to more contributions in the future.

Cheers and happy contributing!

**Review by scissorsneedfoodtoo — APPROVED** [review]
Everything LGTM!

Thank you for catching and fixing this, @Chelsgray 👍

**Pull request merged**
