### PR TITLE
Add vertical scrollbar for challenges instructions panel.

### PR DESCRIPTION
**Pull request by eduardbme**
#### Pre-Submission Checklist

- [x] Your pull request targets the `staging` branch of FreeCodeCamp.
- [x] Branch starts with either `fix/`, `feature/`, or `translate/` (e.g. `fix/signin-issue`)
- [x] You have only one commit (if not, [squash](http://forum.freecodecamp.com/t/how-to-squash-multiple-commits-into-one-with-git/13231) them into one commit).
- [x] All new and existing tests pass the command `npm run test-challenges`. Use `git commit --amend` to amend any fixes.
#### Type of Change

- [ ] Small bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds new functionality)
- [ ] Breaking change (fix or feature that would change existing functionality)
- [ ] Add new translation (feature adding new translations)
- [x] Little front-end enchantment.
#### Checklist:

- [x] Tested changes locally.
- [ ] Closes currently open issue (replace XXXX with an issue no): Closes #XXXX
#### Description

Add scrollbar for challenge instruction part of the page (the leftmost column).

Before fix:
screen shot 2016-09-04 at 12 11 31 pm

After fix:
screen shot 2016-09-04 at 12 24 34 pm

### CODE REVIEW

**Comment by erictleung** [comment]
Tagging @QuincyLarson @hallaathrad @BerkeleyTrue for review of UX/UI changes.

**Comment by eduardbcom** [comment]
Just fixed indentations I haven't noticed before.

**Comment by QuincyLarson** [comment]
@eduardbcom Thanks for submitting this PR.

Can you include screen shots of how this looks in other browsers and on Windows/Linux? I think we tried adding scroll bars in the past and it resulted in duplicate scroll bars so we ditched them. 

Also, I don't see an issue that this is referencing. Unless there are a lot of campers asking for this sort of UI element, it's probably not worth cluttering up our UI over.

**Comment by Bouncey** [comment]
@eduardbcom is there any progress on this?

**Comment by Bouncey** [comment]
Closing as stale 

@eduardbcom feel free to reopen this PR if you have any more progress

**Comment by eduardbcom** [comment]
@Bouncey @QuincyLarson Looks like this issue reproduces just on my screen. Have tested on wider screen and it works just fine. In the next time will check on several devices first..by the way, my solution does not duplicate scrollbar, so it will work just fine.

Many thanks for your time will continue study and contribute to FCC.

**Comment by QuincyLarson** [comment]
@eduardbcom OK - what is your device's resolution? Thanks for raising this issue. We are not closed to the option of adding a scroll bar necessarily, but there are so many browsers, all of which interpret these differently, and significant cross browser and device testing would be necessary.

**Pull request closed without merging**
