### PR TITLE
feat: Added 1st batch of Rosetta code problems.

### PR DESCRIPTION
**Pull request by tpoikela**
#### Pre-Submission Checklist

- [X ] Your pull request targets the `staging` branch of freeCodeCamp.
- [X ] Branch starts with either `fix/`, `feature/`, or `translate/` (e.g. `fix/signin-issue`)
- [X] You have only one commit (if not, [squash](http://forum.freecodecamp.org/t/how-to-squash-multiple-commits-into-one-with-git/13231) them into one commit).
- [X] All new and existing tests pass the command `npm test`. Use `git commit --amend` to amend any fixes.

#### Type of Change

- [ ] Small bug fix (non-breaking change which fixes an issue)
- [X] New feature (non-breaking change which adds new functionality)
- [ ] Breaking change (fix or feature that would change existing functionality)
- [ ] Add new translation (feature adding new translations)

#### Checklist:

- [X] Tested changes locally.
- [ ] Closes currently open issue (replace XXXX with an issue no): Closes #XXXX

#### Description

I added a json file containing 62 coding challenges ported from Rosetta code.

### CODE REVIEW

**Comment by systimotic** [comment]
Hi @tpoikela! I'm missing some information here. Can you link to the discussion about this?

**Review by bonebizz21 — APPROVED** [review]
.

**Comment by tpoikela** [comment]
@systimotic Sorry, I should've added more info. These originate from http://github.com/freecodecamp/arcade-mode/. There's some discussion [here](https://github.com/freeCodeCamp/arcade-mode/issues/6).

**Comment by systimotic** [comment]
Thanks for the info! Sorry for the delay, I've been busy working on the Guide.

Looks like you have some cool challenges in here! I'm still not fully following what's going on. Is this content meant to be a normal challenge, or should it be in a different format? I didn't see any discussion about merging this into the main repo yet. What I understood from the issue you linked was that these Rosetta code challenges should be added to the arcade mode MVP, not the main repo.

**Comment by tpoikela** [comment]
@systimotic We discussed with Quincy (via private email/Skype) that we should merge these challenges to the main fCC repo. They are available in arcade-mode (in a timed/scored format), but should also be available as free-form practice in the main repo.

**Comment by QuincyLarson** [comment]
@tpoikela Awesome - thanks for getting the built to pass.

@systimotic these are part of our interview prep initiative. We're going to be adding hundreds of additional coding challenges like these.

**Comment by systimotic** [comment]
I see, cool!

**Pull request merged**
