### PR TITLE
Challenge - ES6: Write Concise Declarative Functions with ES6 - Added solution

### PR DESCRIPTION
**Pull request by alanpaulprice**
- [x] I have read [freeCodeCamp's contribution guidelines](https://github.com/freeCodeCamp/freeCodeCamp/blob/master/CONTRIBUTING.md).
- [x] My pull request has a descriptive title (not a vague title like `Update index.md`)
- [x] My pull request targets the `master` branch of freeCodeCamp.
- [x] None of my changes are plagiarized from another source without proper attribution.
- [x] My article does not contain shortened URLs or affiliate links.

If your pull request closes a GitHub issue, replace the XXXXX below with the issue number.

Closes #XXXXX

### CODE REVIEW

**Comment by RandellDawson** [comment]
Closed and Reopened this PR to attempt to resolve a specific Travis build failure.

**Comment by RandellDawson** [comment]
@ValeraS Can you help me understand why this is failing?  I also pulled down this PR  down locally and when I run npm test it fails with the same error. If I copy/paste the solution into the current production site, it passes all the tests. What needs to be added to this code?  Is there another PR with a fix for this issue?

**Comment by nikrb** [comment]
not sure anything changed, perhaps just not spotted before?
Wondering why we use `getUserInput` when we could just use the `code` variable, seems simpler?
e.g. instead of
`getUserInput => assert(!getUserInput('index').match(/function/), ...)`
just
`assert(!code.match(/function/), ...)`

**Comment by RandellDawson** [comment]
I went ahead and made the `text` for each test usable for assert message in the console.  I believe this PR is ready to merge.

**Review by Manish-Giri — APPROVED** [review]
LGTM. Thank You for your contribution.

**Pull request merged**
