### PR TITLE
Back end and Front end files back to English

### LINKED ISSUE #43218: Source strings on Crowdin not in English
While going back to re-confirm the strings for the Italian translation of the curriculum, I found some source strings not in English

image

these are in 00-certificates in the Front End Development Libraries certificate folder

image

And these others in the Back End cert folder in 00-certificates

### PR DESCRIPTION
**Pull request by majestic-owl448**
Checklist:

- [x] I have read [freeCodeCamp's contribution guidelines](https://contribute.freecodecamp.org).
- [x] My pull request has a descriptive title (not a vague title like `Update index.md`)
- [x] My pull request targets the `main` branch of freeCodeCamp.
- [ ] I have tested these changes either locally on my machine, or GitPod.

Closes #43218

### CODE REVIEW

**Comment by moT01** [comment]
Looks like the [front end one](https://github.com/freeCodeCamp/freeCodeCamp/blob/main/curriculum/challenges/english/00-certificates/front-end-development-libraries-certificate/front-end-development-libraries-certificate.yml) got the same problem.

**Review by moT01 — DISMISSED** [review]
LGTM 🎉 

These files have a new line after the `-` in front of each `id`. The rest of the English files don't have that. All the other languages do. So, I'm guessing, that gets added somewhere between the crowdin upload and download to the rest of the languages. I would be fine merging this 👍

Looks like these files across all, or probably most, languages on crowdin are showing this Portuguese translation since they were uploaded for English.

I looked at a file from each superblock in English, didn't see any others that were like this.

**Comment by ieahleen** [comment]
> These files have a new line after the `-` in front of each `id`. The rest of the English files don't have that. All the other languages do.

Should I change that so it is like the other English files?

**Comment by ieahleen** [comment]
Found an other file, I committed it to this PR as it has not yet been merged

**Review by naomi-lgbt — APPROVED** [review]

**Review by moT01 — APPROVED** [review]
LGTM 🎉

**Pull request merged**
