### PR TITLE
ga completion event change

### PR DESCRIPTION
**Pull request by evaristoc**
Getting rid of time and attempt variables for following completion through event tracking (the setting is not correctly working at GoAn).

### CODE REVIEW

**Comment by BerkeleyTrue** [comment]
You will need to remove all these as well
https://github.com/FreeCodeCamp/FreeCodeCamp/search?l=jade&q=started&utf8=%E2%9C%93

**Comment by evaristoc** [comment]
Additional corrections were included

**Comment by BerkeleyTrue** [comment]
@evaristoc Thanks! Once this is QA'd it can be merged. CI seems to be broken. Will need to investigate to determine which package is the cause.

**Comment by benmcmahon100** [comment]
Looks like it's the mongo-loopback connector as per line 2171 of the build log

**Comment by evaristoc** [comment]
benmcmahon100 - I also saw errors in several mongo stages and in socket.io, but I don't know how to interpret the build log at this moment.

**Comment by BerkeleyTrue** [comment]
:+1:

**Pull request merged**
