### PR TITLE
solving some links problems and typos in spanish README.md

### PR DESCRIPTION
**Pull request by jotagarciaz**
I have made some changes in freeCodeCamp\docs\i18n-languages\spanish in order to solve some problem with the links. And making some changes in the spanish text more understandable.

- [x] I have read [freeCodeCamp's contribution guidelines](https://github.com/freeCodeCamp/freeCodeCamp/blob/master/CONTRIBUTING.md).
- [x] My pull request has a descriptive title (not a vague title like `Update index.md`)
- [x] My pull request targets the `master` branch of freeCodeCamp.
- [x] None of my changes are plagiarized from another source without proper attribution.
- [x] All the files I changed are in the same world language (for example: only English changes, or only Chinese changes, etc.)
- [x] My changes do not use shortened URLs or affiliate links.

Closes #XXXXX

### CODE REVIEW

**Comment by raisedadead** [comment]
Thanks can you get someone (who speaks spanish) to get this peer reviewed for us, before we can merge?

**Comment by jotagarciaz** [comment]
> Thanks can you get someone (who speaks spanish) to get this peer reviewed for us, before we can merge?

okay, I don't know anybody who collaborate with freecodecamp in Spain, but I know someone who is a kind of writer and copywriter. is it enough?

**Comment by raisedadead** [comment]
> but I know someone who is a kind of writer and copywriter. is it enough?

Should be great, all they need is to leave a comment after taking a look at the files you changed.

**Comment by Narshe1412** [comment]
I believe this is a duplicate of #37593
I've left a review in that PR

**Comment by RandellDawson** [comment]
It seems that similar changes have already been created in another PR you created, so we are closing this PR.

**Comment by jotagarciaz** [comment]
Yes, these PRs: #37525 , #37589, #37591 are merged in #37593 , I published this one as a bundle of all the others in order to do all the changes in the last one, but I needed to mantain the old ones in order to pass the Hacktoberfest, now I'm out of the goal. hahaha

**Comment by jotagarciaz** [comment]
Good evening, @RandellDawson. As I told you, I made the changes in a bundle to make things easier for your team, but marking my other PRs as invalid has left me out of Hacktoberfest, which was never my intention. I have other two Gatsby PRs that count, and the bundle PR, so if you could do me the favor of opening one of my PRs so I could be on the contest again, I would really appreciate it. I understand it is unusual, but I was just trying to help, and I never intended for the rest of my PRs to get closed because of this. Thank you in advance.

**Comment by jotagarciaz** [comment]
Thank you so much @RandellDawson I will try to do better my next pull request ^^

**Comment by jotagarciaz** [comment]
The hacktoberfest is finish we can label this repo as invalid, thank you again.

**Pull request closed without merging**
