### PR TITLE
Migrate Cypress Tests to Typescript

### PR DESCRIPTION
**Pull request by a2937**
Checklist:

- [ ] I have read [freeCodeCamp's contribution guidelines](https://contribute.freecodecamp.org).
- [ ] My pull request has a descriptive title (not a vague title like `Update index.md`)
- [X] My pull request targets the `main` branch of freeCodeCamp.
- [X] I have tested these changes either locally on my machine, or GitPod.

Related to #48753

I had to change some of the constant names because they were already defined elsewhere. I wanna keep converting additional tests. I have only done 17 so far out of the 43 files. 

Update: 34 out of 43 done. I had to adjust one of the commands so it returned something.

### CODE REVIEW

**Comment by a2937** [comment]
Quick Question. Why is ```cypress/e2e/default/learn/challenges/multifileCertProject.ts``` failing on both the Chrome and Firefox tests yet perfectly fine on the Electron one?

**Comment by a2937** [comment]
I've also noticed something unusual. The documentation tells me that the URL method of the global Cypress object is supposed to be taking options not a forward slash. Is it possible that this line should be ```expect(cy.url()).to.eq('/')``` or a close equivalent? 

https://github.com/freeCodeCamp/freeCodeCamp/blob/288ee08c546e4067f41d2893fce3bdc5a8411f1d/cypress/e2e/default/learn/common-components/searchBar.js#L109

**Comment by scissorsneedfoodtoo** [comment]
Thank you for all of your hard work converting these Cypress test files to TypeScript.

I believe you're right about this line:

https://github.com/freeCodeCamp/freeCodeCamp/blob/288ee08c546e4067f41d2893fce3bdc5a8411f1d/cypress/e2e/default/learn/common-components/searchBar.js#L109

It's been a while since I looked at any of the search bar tests. But if I remember correctly, that test is there to make sure that, when a query with no hits is submitted from the `/learn` search bar, that the URL remains the same. So I think this would work: `expect(cy.url()).to.eq('/learn')`

Also, it's strange that the Electron tests pass while Firefox and Chrome both fail.

Looking at the changed files, it seems like `outputSelectors` was changed to `databaseSelectors` in `multifileCertProject.ts`.

Updating that variable name should fix things.

**Comment by raisedadead** [comment]
We are officially on Node.js 18 now. We have changed the merge requirements accordingly.

You will need to rebase this PR against the main branch OR Click the "Update branch" button to get the new checks going.

Thanks for your contribution.

**Comment by a2937** [comment]
I keep getting this message when trying to convert sass.js to Typescript. Maybe one of you know what to do here. 
"Avoid referencing unbound methods which may cause unintentional scoping of `this`.
If your function does not access `this`, you can annotate it with `this: void`, or consider using an arrow function instead."

It's in regards to 
https://github.com/freeCodeCamp/freeCodeCamp/blob/ecc7101854ecbfd1f6854eb0e27348582b7f83b6/cypress/e2e/default/learn/challenges/sass.js#L12

I don't quite understand. The variable ```cy``` is a global variable. I am not quite familiar with any ways around this.

**Comment by a2937** [comment]
I think I did enough to warrant a pull request. While it may not have been a lot, it was a lot of files.

**Comment by a2937** [comment]
Typescript and Cypress was heavily confusing me because my editor was screaming "This is completely wrong" while in reality there was nothing really wrong.

**Pull request closed without merging**
