### PR TITLE
Update correct link reference on mozilla web docs, also update the hyperlinks texts accordingly 

### PR DESCRIPTION
**Pull request by six9**
- [ x] I have read [freeCodeCamp's contribution guidelines](https://github.com/freeCodeCamp/freeCodeCamp/blob/master/CONTRIBUTING.md).
- [ x] My pull request has a descriptive title (not a vague title like `Update index.md`)
- [ x] My pull request targets the `master` branch of freeCodeCamp.
- [ x] None of my changes are plagiarized from another source without proper attribution.
- [ x] All the files I changed are in the same world language (for example: only English changes, or only Chinese changes, etc.)
- [ x] My changes do not use shortened URLs or affiliate links.

Closes #XXXXX

### CODE REVIEW

**Comment by six9** [comment]
Plus I would like to know how to keep updated with the master branch without using git bash. 
like in this,
https://github.com/KirstieJane/STEMMRoleModels/wiki/Syncing-your-fork-to-the-original-repository-via-the-browser
when I did the above I had a commit merge to my forked repo and I was worried that commit will conflict with the master .
so I deleted my repo and forked again. 
Can you suggest a new way?

**Comment by RandellDawson** [comment]
In general, you do not want to make changes on your forked master.  You want to first make sure you master branch is in sync with the main repo's and then create a new branch with any of your changes.  This way, you always keep your master "clean".

**Review by thecodingaviator — APPROVED** [review]
LGTM

**Comment by thecodingaviator** [comment]
Thanks for contributing to the freeCodeCamp repository. Congratulations on your first PR! 🎊 

Look forward to more contributions from you! ✈️

**Pull request merged**
