### PR TITLE
Fix/remove message quote

### LINKED ISSUE #8183: Typo in Instructions Section missing quotes
Challenge [Escaping Literal Quotes in Strings](https://www.freecodecamp.com/challenges/escaping-literal-quotes-in-strings#?solution=var%20myStr%3B%20%2F%2F%20Change%20this%20line%0A%0AmyStr%3D%22I%20am%20a%20%5C%22double%20quoted%5C%22%20string%20inside%20%5C%22double%20quotes%5C%22%20%22%3B%0A) has an issue.
User Agent is: <code>Mozilla/5.0 (Macintosh; Intel Mac OS X 10_11_4) AppleWebKit/601.5.17 (KHTML, like Gecko) Version/9.1 Safari/601.5.17</code>.
Please describe how to reproduce this issue, and include links to screenshots if possible.

My code:
```javascript
var myStr; // Change this line

myStr="I am a \"double quoted\" string inside \"double quotes\" ";

```
The instructions say the following: 

if you were to print it to the console, you would see:

I am a "double quoted" string inside "double quotes" 

The instructions ask for a phrase that only has quotes around the words "double quoted" and "double quotes," but if you write code that accomplishes this, the answer is marked wrong and the second requirement  appearing in the bottom left corner with a red circled x icon says the entire phrase should be in quotes as follows:

Variable myStr should equal to ("I am a "double quoted" string inside "double quotes"").

screen shot 2016-04-18 at 5 27 18 pm

Note how in screenshot the console output for myStr is identical to what instructions ask for, yet the answer is still marked incorrect.

### PR DESCRIPTION
**Pull request by evannudd**
#### Pre-Submission Checklist

- [x] Your pull request targets the `staging` branch of FreeCodeCamp.
- [x] Branch starts with either `fix/`, `feature/`, or `translate/` (e.g. `fix/signin-issue`)
- [x] You have only one commit (if not, [squash](https://github.com/FreeCodeCamp/FreeCodeCamp/wiki/git-rebase#squashing-multiple-commits-into-one) them into one commit).
- [ ] All new and existing tests pass the command `npm run test-challenges`. Use `git commit --amend` to amend any fixes.
#### Type of Change

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] Add new translation (feature adding new translations)
#### Checklist:

- [x] Tested changes locally.
- [x] Closes currently open issue (`Closes #XXXX`): Closes #8183
#### Description

I edited the JSON to remove the quotation marks in the message at the bottom of the instructions. I ran this locally and it did work. I keep failing the npm test though because of .DS_Store I'm hoping that when i submit a pr github will automatically run those tests to prove it works without my silly .DS_Store(i've tried a lot to remove this problem)  If it doesn't pass please don't hate me, I'm trying.

### CODE REVIEW

**Comment by evannudd** [comment]
So all checks passed, yay this makes me happy. I'll figure out how to squash those commits now (sorry!).

**Comment by raisedadead** [comment]
@evannudd Well this time this passes the tests but I am afraid that you have, while trying to squash merged your commit history with another contributor.

I request you to reach out to the [Contributors Chat room](https://gitter.im/FreeCodeCamp/HelpContributors). We will try to sort your issue there. Also there is a dedicated [Git Chat Room](https://gitter.im/FreeCodeCamp/Git) as well.

Thanks.

**Comment by raisedadead** [comment]
@evannudd Do not open a fresh PR until you are advised to do so. Its always possible most of the times to amend the PR, commits etc. Please reach out to the chat rooms if you need any assistance. 😉

**Comment by raisedadead** [comment]
@evannudd Any updates on this?

**Comment by evannudd** [comment]
@raisedadead I want to fix this commit problem but I have no idea how to come at this. I posted https://gitter.im/FreeCodeCamp/HelpContributors here looking for some direction, but that hasn't been successful yet. Im sure it's just a few commands I have to enter in my terminal but I'm not sure entirely how to do it right.

**Comment by evannudd** [comment]
to clarify something else, I understand to use git commit --amend, then git commit --force to overwrite my existing pr. I don't understand how to resolve my commit history being merged with another contributor.

**Comment by raisedadead** [comment]
Well what I can see that you have over written the commit history of another author, its best you follow the below steps:

Step 1 : Copy your fix physically to some place safe.
Step 2 :
```
git checkout staging
git branch -D fix/remove_message_quote
git pull --rebase upstream staging
git push origin staging -f <-------------- This is optional, but recommended
git checkout -b fix/remove_message_quote
```
Step 3 :
Do the fix from your saved copy.
Step 4 :
```
git add --all
git commit -m "Removed the quotation marks from the message"
git push origin fix/remove_message_quote --force
```

That should do it.

**Comment by evannudd** [comment]
I honestly have no idea how it failed the tests I've literally changed nothing from the files that were successfully committed before.

**Comment by raisedadead** [comment]
@evannudd That's okay, the tests are broken on all the PR's, we are looking into it. 
Thanks for updating this request. Great work!

**Comment by evannudd** [comment]
Should I do anything once Travis-ci is working to resubmit?

**Comment by theflametrooper** [comment]
@evannudd I'm restarting the build now. If it works, then we just need to `QA` and  :shipit:.

**Comment by theflametrooper** [comment]
## LGTM :+1:

**Comment by raisedadead** [comment]
Thanks @evannudd and @theflametrooper !

**Comment by ArtriciaDM** [comment]
Ok

**Pull request merged**
