### PR TITLE
fix(server,secrets): Specify profile field for LinkedIn provider.

### LINKED ISSUE #16559: LinkedIn Scope issue "InternalOAuthError: failed to fetch user profile"
We have been getting InternalOAuthErrors for linkedIn recently on PRODUCTION. 

Also reported by @IsaacAbrahamson in https://github.com/freeCodeCamp/freeCodeCamp/issues/14652#issuecomment-359528285

We need to update our config as per the suggested fix for the correct scope:
https://github.com/auth0/passport-linkedin-oauth2/issues/24#issuecomment-358279513

Just to note, this still links the profile, correctly, only thing is this exception needs to be handled, by correcting the scopes.

### PR DESCRIPTION
**Pull request by ojongerius**
Addresses #16559, new PR against the correct target (backup/master).

- [x] Your pull request targets the `staging` branch of freeCodeCamp.
- [x] Branch starts with either `fix/`, `feature/`, or `translate/` (e.g. `fix/signin-issue`)
- [x] You have only one commit (if not, [squash](http://forum.freecodecamp.org/t/how-to-squash-multiple-commits-into-one-with-git/13231) them into one commit).
- [x] All new and existing tests pass the command `npm test`. Use `git commit --amend` to amend any fixes.

#### Type of Change
- [x] Small bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds new functionality)
- [ ] Breaking change (fix or feature that would change existing functionality)
- [ ] Add new translation (feature adding new translations)

#### Checklist:
- [ ] Tested changes locally.
- [x] Addressed currently open issue .

Closes #16559

#### Description
See #16559 and https://github.com/auth0/passport-linkedin-oauth2/issues/24

### CODE REVIEW

**Review by raisedadead — APPROVED** [review]

**Comment by raisedadead** [comment]
@Bouncey @BerkeleyTrue I haven't been able to get my setup working lately for the production branch.

The config above seems fine to me from cross-referencing the code and the docs over at the passport repo, linked in OP and original issue.

I'll merge as soon as I can test locally. But feel free to beat me, if you have a minute to pull this.

**Comment by raisedadead** [comment]
Tested with my updated PR #16740 and LGTM.

**Comment by ojongerius** [comment]
@raisedadead looks like we are good to merge?

**Comment by raisedadead** [comment]
@ojongerius Yes, we are.. just waiting for my linked PR to get through first. Thanks for working on this.

**Comment by ojongerius** [comment]
@raisedadead you're welcome, good to know it's not blocked on me.

**Comment by BerkeleyTrue** [comment]
@raisedadead can this be merge now or does it need further QA?

**Comment by raisedadead** [comment]
Thanks @ojongerius

**Comment by ojongerius** [comment]
🎈

**Pull request merged**
