### PR TITLE
docs: correct typo in 'Work on Codebase' page

### PR DESCRIPTION
**Pull request by pramod74**
Checklist:

- [ x] I have read and followed the [contribution guidelines](https://contribute.freecodecamp.org).
- [ x] I have read and followed the [how to open a pull request guide](https://contribute.freecodecamp.org/#/how-to-open-a-pull-request).
- [ x] My pull request targets the `main` branch of freeCodeCamp.
- [ x] I have tested these changes either locally on my machine, or GitPod.

I have replaced the word 'rebase' with the word 'rebasing' in the last statement of step 2 on the 'Work on Codebase' page (https://contribute.freecodecamp.org/#/how-to-contribute-to-the-codebase). The sentence should now read: 

The resulting output should be empty. This process is important, because you will be rebasing your branch on top of the latest upstream/main as often as possible to avoid conflicts later.

### CODE REVIEW

**Review by jdwilkin4 — APPROVED** [review]

**Review by hejoefs — COMMENTED** [review]
Nice

**Review by huyenltnguyen — APPROVED** [review]
LGTM 👍

@pramod74 Thank you for the PR and congratulations on your first contribution to this repo 🎉
We look forward to your next.

Happy contributing!

**Comment by pramod74** [comment]
> Nice

Thanks!

**Comment by pramod74** [comment]
> LGTM 👍
> 
> @pramod74 Thank you for the PR and congratulations on your first contribution to this repo 🎉 We look forward to your next.
> 
> Happy contributing!

Thanks, @huyenltnguyen ! I am glad I could help. Yes, this was my first contribution to this repo. Thanks for the encouraging words!

**Pull request merged**
