### PR TITLE
French Translation for HTML and CSS

### PR DESCRIPTION
**Pull request by mizujin**
#### Pre-Submission Checklist

- [x] Your pull request targets the `staging` branch of FreeCodeCamp.
- [x] Branch starts with either `fix/`, `feature/`, or `translate/` (e.g. `fix/signin-issue`)
- [x] You have only one commit (if not, [squash](https://github.com/FreeCodeCamp/FreeCodeCamp/wiki/Git-Squash) them into one commit).
- [ ] All new and existing tests pass the command `npm run test-challenges`. Use `git commit --amend` to amend any fixes.
#### Type of Change

- [ ] Small bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds new functionality)
- [ ] Breaking change (fix or feature that would change existing functionality)
- [x] Add new translation (feature adding new translations)
#### Checklist:

- [ ] Tested changes locally.
- [ ] Closes currently open issue (replace XXXX with an issue no): Closes #XXXX
#### Description

Related to issue no #7288, but doesn't closes it yet.

Further translation of the following challenges :
- Use a CSS Class to Style an Element
- Style Multiple Elements with a CSS Class
- Change the Font Size of an Element
- Set the Font Family of an Element
- Import a Google Font
- Specify How Fonts Should Degrade
- Add Images to your Website
- Size your Images
- Add Borders Around your Elements

### CODE REVIEW

**Comment by raisedadead** [comment]
@mizujin 

- Can you update the PR title to French Translation for HTML and CSS
- The challenges are not numbered, can you please list them (just names will do) in the PR description.

Thanks.

**Comment by mizujin** [comment]
@raisedadead Done, thanks for your help!

**Comment by atjonathan** [comment]
Please get someone in the [TranslationFrench](https://gitter.im/FreeCodeCamp/TranslationFrench) chat room to peer review this, thanks :+1:

**Comment by mizujin** [comment]
@atjonathan I did... 3 days ago and my message is still the most recent. Looks like i'm alone atm.

**Comment by atjonathan** [comment]
@mizujin, np. Give it another 4 days, then we will merge anyway :+1:

**Comment by raisedadead** [comment]
Merging, this will help us in testing the beta site. @mizujin thanks a lot for contributing.

**Review by TOPCODER10192 — COMMENTED** [review]
I checked the translation in french, and everything is properly translated.

**Comment by raisedadead** [comment]
Thanks @ScrumUser1

**Pull request merged**
