### PR TITLE
Create empty method body to prevent TypeError

### LINKED ISSUE #14095: Make a Person challenge missing tests in production
Challenge [Make a Person](https://www.freecodecamp.com/challenges/make-a-person) has an issue.
User Agent is: <code>Mozilla/5.0 (Macintosh; Intel Mac OS X 10_12_3) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/56.0.2924.87 Safari/537.36</code>.

Make a Person's tests aren't appearing in production. This is a high-priority issue.

If you think you can fix this, branch off of backup/master, fix it, and put in a PR. Mention @BerkeleyTrue and this issue in the PR and Berkeley can help QA this real quick and deploy it. Thanks!

make_a_person___free_code_camp

### PR DESCRIPTION
**Pull request by Manish-Giri**
#### Pre-Submission Checklist

- [x] Your pull request targets the `staging` branch of freeCodeCamp.
- [x] Branch starts with either `fix/`, `feature/`, or `translate/` (e.g. `fix/signin-issue`)
- [x] You have only one commit (if not, [squash](http://forum.freecodecamp.com/t/how-to-squash-multiple-commits-into-one-with-git/13231) them into one commit).
- [x] All new and existing tests pass the command `npm test`. Use `git commit --amend` to amend any fixes.

#### Type of Change

- [x] Small bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds new functionality)
- [ ] Breaking change (fix or feature that would change existing functionality)
- [ ] Add new translation (feature adding new translations)

#### Checklist:

- [x] Tested changes locally.
- [x] Closes currently open issue (replace XXXX with an issue no): Closes #14095 

#### Description

Added empty method body to prevent TypeError which was being thrown due to a non existent function, as noted in the issue.

Verified the change locally, tests appear - 

screenshot 2017-03-26 03 57 05

@BerkeleyTrue - please review.

Closes #14095

### CODE REVIEW

**Comment by raisedadead** [comment]
Hi @Manish-Giri are is this issue on `staging` as well, not sure why its opened against `backup\master`?

We are not releasing `backup\master` except for critical issues ?

**Comment by Manish-Giri** [comment]
@raisedadead oops, I must have misunderstood then. I thought that's what was mentioned in the issue - create the PR to address the issue in production, on the `backup/master` branch. And then I could create another PR to fix it in `staging`.

**Comment by raisedadead** [comment]
Oh right. I missed the OP. Thanks for confirming. We would need a PR for staging as well.
I'll QA this meanwhile.

**Comment by BerkeleyTrue** [comment]
@Manish-Giri thanks!

Happy Coding

**Pull request merged**
