### PR TITLE
fix(curriculum): Removed URL for wrong video solution

### LINKED ISSUE #43185: Incorrect solution provided for Divide the Grid Into an Area Template challenge
A user on the forum had trouble passing a challenge using a solution provided in the video. 
I led them to the correct solution but the video seems to be referencing a different challenge. 
Even the hint page is incorrect and provides these instructions. 

"Since the challenge requires you to make the cell labeled advert into an empty cell, change advert to a . (period) so that the code reflects the following:"
https://forum.freecodecamp.org/t/freecodecamp-challenge-guide-divide-the-grid-into-an-area-template/301130

But those are the incorrect instructions.
Here are the correct instructions
Change the template so the footer area spans the entire bottom row. 

The solution in the hint needs to be updated and the video should be removed. 

Thanks! 

## Affected page

https://www.freecodecamp.org/learn/responsive-web-design/css-grid/divide-the-grid-into-an-area-template

## Your code

Correct solution
```
    grid-template-areas:
    /* Only change code below this line */
      "header header header"
      "advert content content"
      "footer footer footer";
    /* Only change code above this line */
  }

```

### PR DESCRIPTION
**Pull request by w286432531**
Removed video in the challenge "Divide the Grid Into an Area Template" because it's the solution for another challenge.

Checklist:

- [x] I have read [freeCodeCamp's contribution guidelines](https://contribute.freecodecamp.org).
- [x] My pull request has a descriptive title (not a vague title like `Update index.md`)
- [x] My pull request targets the `main` branch of freeCodeCamp.
- [ ] I have tested these changes either locally on my machine, or GitPod.

Closes #43185

### CODE REVIEW

**Review by gikf — CHANGES_REQUESTED** [review]
Hey @w286432531

the line with `videoUrl:` needs to be removed completely, leaving it blank will result in errors, as it can be seen in CI checks.

Could you revert changes made to the non-English languages? Files in other languages shouldn't be changed directly. When needed they will be updated using the translation workflow.

Also for future, it is recommended to use separate branch for changes, instead of using the `main` branch of fork. See step 3 from https://contribute.freecodecamp.org/#/how-to-setup-freecodecamp-locally?id=making-changes-locally for more information about this.

**Comment by w286432531** [comment]
> Hey @w286432531
> 
> the line with `videoUrl:` needs to be removed completely, leaving it blank will result in errors, as it can be seen in CI checks.
> 
> Could you revert changes made to the non-English languages? Files in other languages shouldn't be changed directly. When needed they will be updated using the translation workflow.
> 
> Also for future, it is recommended to use separate branch for changes, instead of using the `main` branch of fork. See step 3 from https://contribute.freecodecamp.org/#/how-to-setup-freecodecamp-locally?id=making-changes-locally for more information about this.

Thank you for the reply. It's my first time trying to contribute. I will make sure I use a new branch next time. I reverted the changes I made to the other languages and deleted the line with `videoUrl:` completely.

**Review by gikf — APPROVED** [review]
Looks good to me :+1:

**Review by raisedadead — APPROVED** [review]
#### :sparkles: :sparkles: **AWESOME! LGTM.** :sparkles: :sparkles: 

Thanks, @w286432531, for this pull request and for contributing to the code-base for the first time.

We will be looking forward to more contributions in future.

Cheers and happy contributing!

**Pull request merged**
