### PR TITLE
fix(client): added editorRef to enable hotkey focus

### LINKED ISSUE #41751: `e` keymap not working in challenges with JS
**Describe the bug**
In challenges which make use of JS in the editor, the `e` keymap doesn't work as in it doesn't focus on the editor.

**To Reproduce**
1. Go to any challenge with a JS editor like [Comment-your-javascript-code](https://www.freecodecamp.org/learn/javascript-algorithms-and-data-structures/basic-javascript/comment-your-javascript-code) or [Add-comments-in-jsx](https://www.freecodecamp.org/learn/front-end-libraries/react/add-comments-in-jsx)
2. Don't focus on the editor
3. Click `e` in your keyboard
4. The editor doesn't get focused

### PR DESCRIPTION
**Pull request by hassaanp**
Checklist:

- [x] I have read [freeCodeCamp's contribution guidelines](https://contribute.freecodecamp.org).
- [x] My pull request has a descriptive title (not a vague title like `Update index.md`)
- [x] My pull request targets the `main` branch of freeCodeCamp.
- [x] All the files I changed are in the same world language, for example: only English changes, or only Chinese changes, etc.

Closes #41751

### CODE REVIEW

**Review by gikf — DISMISSED** [review]
Confirmed locally it fixes issue with editor focusing hotkey in some challenges.

LGTM :+1:

**Comment by raisedadead** [comment]
Oliver is this a regression? I see that the fix needed to be done in the multifile editor but I have not been keeping up with the client side of things lately.

**Comment by ojeytonwilliams** [comment]
> @ojeytonwilliams is this a regression? I see that the fix needed to be done in the multifile editor but I have not been keeping up with the client side of things lately.

Yep, it is.  I must have forgotten to pass that ref to the `Editor` when it became a component of the `MultifileEditor`.

@hassaanp do you think you could add some tests, so we catch this regression?  A Cypress test that just presses 'e' on a few challenges and checks if the editor gets focused should cover it.  No worries if you're not up for that, I can just add it to my backlog!

**Comment by hassaanp** [comment]
> > @ojeytonwilliams is this a regression? I see that the fix needed to be done in the multifile editor but I have not been keeping up with the client side of things lately.
> 
> Yep, it is. I must have forgotten to pass that ref to the `Editor` when it became a component of the `MultifileEditor`.
> 
> @hassaanp do you think you could add some tests, so we catch this regression? A Cypress test that just presses 'e' on a few challenges and checks if the editor gets focused should cover it. No worries if you're not up for that, I can just add it to my backlog!

I can take a look. I will probably push the tests tomorrow.

**Comment by ojeytonwilliams** [comment]
Awesome, thanks.  I'm looking forward to seeing what you come up with.

**Comment by hassaanp** [comment]
@ojeytonwilliams I have pushed a commit that adds a test to verify hotkey behavior. However, I have not run this locally yet. I just wanted to get your feedback on it before I add more tests.

We can perhaps add more tests for all hotkeys. Let me know what you think.

**Comment by ojeytonwilliams** [comment]
@hassaanp I'm broadly in favour of more tests, so testing each hotkey sounds good to me.  What I will say is that @Sembauke has done a load of great work on adding tests for all the challenges here: https://github.com/freeCodeCamp/freeCodeCamp/pull/41602.  With that in mind, it might be a good plan to defer the testing until after that lands, rather than reinventing the approach here.

If we go that route, I'm completely fine with merging this without the commit that adds tests.  

What do you think?

**Comment by hassaanp** [comment]
> If we go that route, I'm completely fine with merging this without the commit that adds tests.
> 
> What do you think?

Yes, that makes sense. I will revert the commit then.

**Comment by ojeytonwilliams** [comment]
Perfect, thanks.  Sorry for going back and forth on this. I hope it's not too much trouble to port over your work.

**Comment by hassaanp** [comment]
> Perfect, thanks. Sorry for going back and forth on this. I hope it's not too much trouble to port over your work.

No issues at all. I have reverted the commit for the cypress test. Take a look and approve if everything looks good.
Also let me know if you want me to add the hotkey tests to cypress once #41602 is merged.

**Review by ojeytonwilliams — APPROVED** [review]
LGTM :+1:

**Comment by ojeytonwilliams** [comment]
> Also let me know if you want me to add the hotkey tests to cypress once #41602 is merged.

Definitely. We're planning to advertise the hotkeys (a bit) in the multifile editor, so it would be great if we had test coverage.

**Review by gikf — APPROVED** [review]
:+1: PR reverted to commit previously reviewed https://github.com/freeCodeCamp/freeCodeCamp/pull/41757#pullrequestreview-629629230

**Pull request merged**
