### PR TITLE
update functions to use arrow syntax

### PR DESCRIPTION
**Pull request by anthonykyi**
- [x] I have read [freeCodeCamp's contribution guidelines](https://github.com/freeCodeCamp/freeCodeCamp/blob/master/CONTRIBUTING.md).
- [x] My pull request has a descriptive title (not a vague title like `Update index.md`)
- [x] My pull request targets the `master` branch of freeCodeCamp.
- [x] None of my changes are plagiarized from another source without proper attribution.
- [x] All the files I changed are in the same world language (for example: only English changes, or only Chinese changes, etc.)
- [x] My changes do not use shortened URLs or affiliate links.

### CODE REVIEW

**Comment by RandellDawson** [comment]
Will there not be a performance hit here, since using function properties vs. class methods due to the properties being initialized on each new instance of the component rather than just once on the class?

**Comment by anthonykyi** [comment]
@RandellDawson You are correct!

**Review by ojeytonwilliams — CHANGES_REQUESTED** [review]
As far as performance goes, it's possible this creates a performance hit, but probably not a big one.  I've profiled this a bit and, while the two approaches do take different amounts of time to run, it seems the change has no significant impact on performance as a whole.

Overall, I think this is a nice change - improving code legibility is always good!

**Comment by ValeraS** [comment]
Thank you for opening this pull request.

This is a standard message notifying you that we’ve reviewed your pull request and have decided not to merge it. We would welcome future pull requests from you.

Thank you and happy coding.

**Pull request closed without merging**
