### PR TITLE
Improve description of Find Numbers with Regular Expressions Waypoint

### LINKED ISSUE #5892: Incorrect explanation of the `+`
Challenge [Waypoint: Find Numbers with Regular Expressions](http://www.freecodecamp.com/challenges/waypoint-find-numbers-with-regular-expressions#?solution=%2F%2F%20Setup%0Avar%20testString%20%3D%20%22There%20are%203%20cats%20but%204%20dogs.%22%3B%0A%0A%2F%2F%20Only%20change%20code%20below%20this%20line.%0A%0Avar%20expression%20%3D%20%2Fd%2B%2Fg%3B%20%20%2F%2F%20Change%20this%20line%0A%0A%2F%2F%20Only%20change%20code%20above%20this%20line%0A%0A%2F%2F%20This%20code%20counts%20the%20matches%20of%20expression%20in%20testString%0Avar%20digitCount%20%3D%20testString.match(expression).length%3B%0A) has an issue.
User Agent is: <code>Mozilla/5.0 (Macintosh; Intel Mac OS X 10_11_2) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/47.0.2526.106 Safari/537.36</code>.
Please describe how to reproduce this issue, and include links to screenshots if possible.

The content is this:

>For numbers this is often written as /\d+/g, where the + following the digit selector allows this regular expression **to match one or more numbers**.

the `+` in this case is to match one or more digits, not one or more numbers. The `g` is a global match flag which will find all the numbers.

### PR DESCRIPTION
**Pull request by pbnj**
closes #5892
### Waypoint: Find Numbers With Regular Expressions

Current Waypoint description:

> We can use special selectors in Regular Expressions to select a particular type of value.
> 
> One such selector is the digit selector \d which is used to retrieve the numbers in a string.
> 
> It is used like this: /\d/g.
> 
> For numbers this is often written as /\d+/g, where the + following the digit selector allows this regular expression to match one or more numbers.
> 
> Instructions
> Use the \d selector to select the number of numbers in the string, allowing for the possibility of one or more digit.
### Improved Waypoint description:

> We can use special selectors in <code>Regular Expressions</code> to select a particular type of value.
> 
> One such selector is the digit selector <code>\d</code> which is used to retrieve one digit in a string.
> 
> In JavaScript code, it is used like this: <code>/\d/g</code>.
> 
> Appending a plus sign (<code>+</code>) after the selector, e.g. <code>/\d+/g</code>, allows this regular expression to match one or more digits.
> 
> The trailing <code>g</code> is short for 'global', which allows this regular expression find all matches rather than stop at the first match

### CODE REVIEW

**Comment by SaintPeter** [comment]
I really like this change.  Two minor things:
1. Use the `<dfn>` tags around "Regular Expression" - they're not supported yet, but will be.
2. Might want to explain what a digit is - IE:  the numbers 0 to 9.

**Comment by pmbenjamin** [comment]
- Replaced `<code></code>` with `<dfn></dfn>`
- Defined digits as (`numbers 0 to 9`)

**Comment by pmbenjamin** [comment]
Accidentally clicked "close and comment" rather than "comment" button.

**Comment by SaintPeter** [comment]
Oh dear.  It looks like you did a `git pull` on your branch?  I'm seeing other people's commits?  

Here is a guide about maintaining your local copy of the site: 
https://github.com/FreeCodeCamp/FreeCodeCamp/wiki/How-To-Fork-And-Maintain-a-Local-Instance-of-Free-Code-Camp

I'm not sure if you're going to be able to recover this branch, unless you know how to revert that pull.

**Comment by pmbenjamin** [comment]
Hmm, not sure what happened. I'll redo the work on a clean branch.

**Pull request closed without merging**
