### PR TITLE
translate(docs): how-to-catch-outgoing-emails-locally.md to russian

### PR DESCRIPTION
**Pull request by artolshansky**
- [x] I have read [freeCodeCamp's contribution guidelines](https://github.com/freeCodeCamp/freeCodeCamp/blob/master/CONTRIBUTING.md).
- [x] My pull request has a descriptive title (not a vague title like `Update index.md`)
- [x] My pull request targets the `master` branch of freeCodeCamp.
- [x] None of my changes are plagiarized from another source without proper attirbution.
- [x] My article does not contain shortened URLs or affiliate links.

Related #18308

### CODE REVIEW

**Comment by olshansky** [comment]
@raisedadead @Bouncey review this, please

**Comment by raisedadead** [comment]
Hi @olshansky 

Thanks a lot for taking the time to make this PR. 

We would review this in due course. Just a recommendation that a we should reserve `@mentions` on the side of issues needing immediate attention when possible.

That said, we sincerely appreciate your contributions.

Happy translating.

**Review by greggubarev — CHANGES_REQUESTED** [review]
Need improve translate in line 19

**Review by greggubarev — APPROVED** [review]

**Comment by sergeyradov** [comment]
@raisedadead if you need PR reviews with Russian languages articles, please ping me. I will be happy to help

**Comment by raisedadead** [comment]
@sergeyradov can you DM me on gitter: https://gitter.im/raisedadead

**Comment by sergeyradov** [comment]
@raisedadead sent a few strings, but it looks like message history is not stored after a switch from  DM to a chat.

**Pull request merged**
