### PR TITLE
add a mobile portfolio view

### LINKED ISSUE #4056: Code Portfolio views on should show links to a camper's solutions
Here's what @abhisekp's profile looks like on mobile: 

It doesn't show any of his challenge solutions.

Ideally, we would have a single column with just the name of the completed solution that would be a hyperlink to the solution.

For example:

[Bonfire: Repeat a String](http://freecodecamp.com/challenges/bonfire-repeat-a-string-repeat-a-string?solution=function%20repeat(str%2C%20num)%20%7B%0A%20%20%2F%2F%20repeat%20after%20me%0A%20%20%2F%2F%20am%20i%20in%20class%202%20or%20something%3F%0A%20%20%0A%20%20return%20str.repeat(num%20%3C%200%20%3F%200%20%3A%20num)%3B%0A%7D%0A%0Arepeat(%27abc%27%2C%203)%3B%0A)

The view that would need to be updated here is showAccount.jade

There shouldn't be any need to update the controller - this is purely a Bootstrap / Jade task.

### PR DESCRIPTION
**Pull request by matthiaskern**
closes #4056

### CODE REVIEW

**Comment by bugron** [comment]
@kema00 thanks for the PR. Please, remove the issue number from the title and add `closes #4056` to the description.

**Comment by kema00** [comment]
@bugron sorry, i misread the wiki entry (don't know how that's possible)

**Comment by bugron** [comment]
@kema00 no worries.

**Comment by SaintPeter** [comment]
This may not be fixable, but the centering on the table is not correct.  See the red arrows I added.  There is 2-3 times more space on the right hand side.
image

My testing is using Chrome on Windows Desktop, using their Cell Phone Simulator feature, so this may not be representative of actual mobile view.

**Comment by kema00** [comment]
For me this also happens in a bigger view in the current online version of FCC (Google Chrome on Linux).

**Comment by SaintPeter** [comment]
I guess we need to figure out why that exists and if it's still relevant.

**Comment by BerkeleyTrue** [comment]
@SaintPeter Is this in the bootstrap files or in the main.less file?

**Comment by SaintPeter** [comment]
@kema00 Where did you find the `.table` css?

**Comment by kema00** [comment]
It is in the main.less file. For git blame, this commit comes up: bedddde945410b9f6a6ac3ca580fc39332d1ee66

**Comment by SaintPeter** [comment]
Waiting on an opinion from @BerkeleyTrue as to if the `.table` css is still needed.

**Comment by BerkeleyTrue** [comment]
@SaintPeter That will have to be @QuincyLarson's call.

**Comment by QuincyLarson** [comment]
I removed the CSS like @SaintPeter suggested. Thanks everyone, especially @kema00 for taking the initiative and fixing it. :)

**Pull request merged**
