### PR TITLE
Fix to Issue 1540

### PR DESCRIPTION
**Pull request by Rafase282**
Change the challenge seed to reflect the first test case properly.

### CODE REVIEW

**Comment by ahstro** [comment]
Protip: When referring to an issue, use # before, so GitHub knows what you mean, like this: #1540

**Comment by Rafase282** [comment]
Thanks @ahstro

**Comment by benmcmahon100** [comment]
Hey @Rafase282 sorry to be a pain but would you be able open a new pull request? The files have changed a lot since this was done and there are merge conflicts. It'd make the fix myself but i'd rather that you got the credit for it. All it requires is making the same changes to the current version of the file. I'll merge it straight away in order to avoid running into another conflict

**Comment by Rafase282** [comment]
Issue was solved here https://github.com/FreeCodeCamp/freecodecamp/pull/1581#event-374693567

**Pull request closed without merging**
