### PR TITLE
fix(api): only use homeLocation as a fallback

### PR DESCRIPTION
**Pull request by ojeytonwilliams**
@raisedadead this could use a few more tests, but I think it's good enough to be QA'd.

### CODE REVIEW

**Comment by raisedadead** [comment]
This was broken as is with this error:

```
[ERR_INVALID_URL]: Invalid URL: undefined
    at onParseError (internal/url.js:257:9)
    at new URL (internal/url.js:333:5)
    at getRedirectParams (/home/raisedadead/DEV/freeCodeCamp/api-server/server/utils/redirection.js:69:21)
    at /home/raisedadead/DEV/freeCodeCamp/api-server/server/middlewares/error-handlers.js:29:24
```

I had to add this to the `next` branch for validation: https://github.com/freeCodeCamp/freeCodeCamp/commit/5a5811af97aafedef85ea452c02c31907a58aeb7

Also, I can't seemingly get myself successfully redirected back to settings page like before (or any page for that matter locallt). I haven't tested it out on production. Will let you know.

**Comment by ojeytonwilliams** [comment]
Weird.  I'll give it a quick look, but I'm surprised `Referer` isn't getting set - I thought that would be reliable.

**Comment by ojeytonwilliams** [comment]
I'm not sure what's going on with `Invalid URL: undefined`, but the lack of redirection in development is because of 

https://github.com/freeCodeCamp/freeCodeCamp/blob/5a5811af97aafedef85ea452c02c31907a58aeb7/api-server/server/utils/redirection.js#L74

Everything gets normalised and localhost is rejected because it's not an allowed origin.  I'll create a quick fix.

**Comment by raisedadead** [comment]
Ah - right. Thanks for clarifying.

**Pull request merged**
