### PR TITLE
feat: restrict update flag endpoint

### PR DESCRIPTION
**Pull request by naomi-lgbt**
Checklist:

- [X] I have read [freeCodeCamp's contribution guidelines](https://contribute.freecodecamp.org).
- [X] My pull request has a descriptive title (not a vague title like `Update index.md`)
- [X] My pull request targets the `main` branch of freeCodeCamp.
- [X] I have tested these changes either locally on my machine, or GitPod.

Closes #XXXXX

The changes to the client should be deployed already, so we can restrict this endpoint more - it should only be the socials that are calling this endpoint now? @ojeytonwilliams would you mind confirming?

### CODE REVIEW

**Comment by raisedadead** [comment]
Do you know what's up with the Cypress tests?

**Comment by raisedadead** [comment]
Do you know what's up with the Cypress tests?

**Comment by ojeytonwilliams** [comment]
> Do you know what's up with the Cypress tests?

I'm not sure about the universal nav one, but the challenge-hot-keys are failing because they rely on `updateUserFlag`.

**Comment by ojeytonwilliams** [comment]
Also, it looks like all the routes exist, so after one more client update we should be able remove the `updateUserFlag` endpoint entirely.

**Comment by ojeytonwilliams** [comment]
Once https://github.com/freeCodeCamp/freeCodeCamp/pull/46378 and https://github.com/freeCodeCamp/freeCodeCamp/pull/46380 have been deployed we should be able to get this done.

**Comment by raisedadead** [comment]
We are officially on Node.js 18 now. We have changed the merge requirements accordingly.

You will need to rebase this PR against the main branch OR Click the "Update branch" button to get the new checks going.

Thanks for your contribution.

**Review by raisedadead — APPROVED** [review]

**Review by ahmaxed — APPROVED** [review]

**Pull request merged**
