### PR TITLE
trim query before making request

### LINKED ISSUE #37386: Validating Search bar content before making request
How to reproduce?
      Go to the search bar , press space and hit enter, you will see the loading starts and it makes request for searching which should not be there until and unless some content is there in the search bar.

I would like to work on it if its needed

### PR DESCRIPTION
**Pull request by shakti97**
- [x] I have read [freeCodeCamp's contribution guidelines](https://github.com/freeCodeCamp/freeCodeCamp/blob/master/CONTRIBUTING.md).
- [x] My pull request has a descriptive title (not a vague title like `Update index.md`)
- [x] My pull request targets the `master` branch of freeCodeCamp.
- [x] None of my changes are plagiarized from another source without proper attribution.
- [x] All the files I changed are in the same world language (for example: only English changes, or only Chinese changes, etc.)
- [x] My changes do not use shortened URLs or affiliate links.

Closes #37386

### CODE REVIEW

**Comment by thecodingaviator** [comment]
The PR hasn't fixed the problem. We'll need to do it some other way
image

**Review by thecodingaviator — CHANGES_REQUESTED** [review]
Please do not ship as is. The issue hasn't been fixed

**Comment by shakti97** [comment]
Actually it is, check for entering space and then press enter it will not navigate to any other page as no real content is there, and then check for the entering character and then press enter

**Comment by thecodingaviator** [comment]
@shakti97 IMO there should be no hits until a non-whitespace character is typed for the first time into the search bar.

**Comment by shakti97** [comment]
Actually i just worked on no requesting until non-whitespace character is typed, i didn't worked on hits part because i thought it will help user recommending several options

**Comment by raisedadead** [comment]
Closing as discussed.

**Pull request closed without merging**
