### PR TITLE
feat(client): add common links to formValidators regex

### PR DESCRIPTION
**Pull request by ShaunSHamilton**
Checklist:

- [x] I have read [freeCodeCamp's contribution guidelines](https://contribute.freecodecamp.org).
- [x] My pull request has a descriptive title (not a vague title like `Update index.md`)
- [x] My pull request targets the `main` branch of freeCodeCamp.
- [x] All the files I changed are in the same world language, for example: only English changes, or only Chinese changes, etc.

This PR adds links like `https://repl.it/join/Sky020` to the editor validation. As well as freeCodeCamp related links:
- CodePen links
- GitHub boilerplate links
- `freeCodeCamp.rocks` links

Never ceases to amaze how many different links Campers will submit before the correct one.

### CODE REVIEW

**Comment by ahmadabdolsaheb** [comment]
is submitting https://repl.it/join/ .... common?

**Comment by ShaunSHamilton** [comment]
> is submitting https://repl.it/join/ .... common?

It has happened twice that I have seen. This PR can hold off, though, as there might be scope to add validation that the links submitted does not include the boilerplate URLs.

Specifically, we discussed this on the fCC chat in Contributors - ensure Campers do not submit the CodePen boilerplate, thinking they have their code submitted and saved.

**Comment by raisedadead** [comment]
> This PR can hold off, though, as there might be scope to add validation that the links submitted does not include the boilerplate URLs.

Do you mean, you intend to expand the scope of the PR to add more invalid URL patterns?

**Comment by ShaunSHamilton** [comment]
> you intend to expand the scope of the PR to add more invalid URL patterns?

@raisedadead Yes. There was some discussion about it, but I will actually open an issue specifically about it, first - for clarity.

I will set this to a _work in progress_

**Review by raisedadead — APPROVED** [review]

**Review by ojeytonwilliams — APPROVED** [review]
LGTM :+1: 

Nice work, Shaun.  It occurs to me that we should translate these messages, but that's a job for another PR.

**Pull request merged**
