### PR TITLE
Fix CONTRIBUTING.md link and capitalization

### PR DESCRIPTION
**Pull request by Atomk**
#### Pre-Submission Checklist

- [x] Your pull request targets the `staging` branch of freeCodeCamp.
- [x] Branch starts with either `fix/`, `feature/`, or `translate/` (e.g. `fix/signin-issue`)
- [x] You have only one commit (if not, [squash](http://forum.freecodecamp.com/t/how-to-squash-multiple-commits-into-one-with-git/13231) them into one commit).
- [ ] All new and existing tests pass the command `npm test`. Use `git commit --amend` to amend any fixes.

#### Type of Change

- [x] Small bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds new functionality)
- [ ] Breaking change (fix or feature that would change existing functionality)
- [ ] Add new translation (feature adding new translations)

#### Checklist:

- [x] Tested changes locally.
- [ ] Closes currently open issue (replace XXXX with an issue no): Closes #XXXX

#### Description

The internal link "found a bug" does not work since the section was probably moved to README.md, so I used a link to that file. The best thing would be to use a link to the same repository but I don't know if using README.md#found-a-bug would work.

I have also found a small inconsistency in the capitalization of a title so I fixed that too.

### CODE REVIEW

**Review by Greenheart — CHANGES_REQUESTED** [review]
@Atomk Nice catch!

I tested the link by editing the link in the live version of the document on GitHub and it worked.

If you squash your commits, this is ready to be merged :blush: :+1:

**Comment by Atomk** [comment]
@Greenheart I had some unexpected complications with Git but I think I made it!

**Review by systimotic — APPROVED** [review]
# LGTM 🎉 
Thanks for contributing @Atomk!

**Comment by Greenheart** [comment]
@Atomk Great job! Thanks for contributing! :smile:

**Pull request merged**
