### PR TITLE
Create how-to-open-a-pull-request.md in Portuguese

### PR DESCRIPTION
**Pull request by lucasrafaldini**
I've translated the reply-templates.md for Portuguese.

- [X] I have read [freeCodeCamp's contribution guidelines](https://github.com/freeCodeCamp/freeCodeCamp/blob/master/CONTRIBUTING.md).
- [X] My pull request has a descriptive title (not a vague title like `Update index.md`)
- [X] My pull request targets the `master` branch of freeCodeCamp.
- [X] None of my changes are plagiarized from another source without proper attribution.
- [X] All the files I changed are in the same world language (for example: only English changes, or only Chinese changes, etc.)
- [X] My changes do not use shortened URLs or affiliate links.

Closes #XXXXX

### CODE REVIEW

**Comment by junagao** [comment]
Could I help reviewing this or other PRs related to Portuguese language? I'm a native Portuguese speaker and would like to contribute back to the community in some way. Cheers.

**Comment by RandellDawson** [comment]
> Could I help reviewing this or other PRs related to Portuguese language? I'm a native Portuguese speaker and would like to contribute back to the community in some way. Cheers.

@lucasrafaldini Do you know Brazilian or European?

**Comment by junagao** [comment]
Hi @RandellDawson, it's Juliane here. I know Brazilian portuguese.

**Comment by raisedadead** [comment]
Hi @junagao are you able to review this PR? If so please let us know.

**Pull request closed without merging**
