### PR TITLE
fix(UI): remove flash from update email flow

### PR DESCRIPTION
**Pull request by a2937**
Checklist:

- [X] I have read and followed the [contribution guidelines](https://contribute.freecodecamp.org).
- [X] I have read and followed the [how to open a pull request guide](https://contribute.freecodecamp.org/#/how-to-open-a-pull-request).
- [X] My pull request targets the `main` branch of freeCodeCamp.
- [X] I have tested these changes either locally on my machine, or GitPod.

Closes #53899

### CODE REVIEW

**Review by naomi-lgbt — CHANGES_REQUESTED** [review]
image

The client is going to need an update to display the changed return value correctly.

**Comment by a2937** [comment]
I think I might be pretty close to figuring it out if I haven't already. The banner asked me to wait four minutes to try again.

**Comment by a2937** [comment]
I realize now that it only changed the issue with the object variable going elsewhere. But I'm a little confused on how it actually renders the info messages.

**Comment by a2937** [comment]
I wanted to clean up my workspace. I know I still don't have the answer quite yet.

**Review by naomi-lgbt — APPROVED** [review]

**Review by raisedadead — APPROVED** [review]

**Pull request merged**
