### PR TITLE
fix(curriculum): Convert blockquote elements to triple backtick syntax for Front End Libraries

### PR DESCRIPTION
**Pull request by RandellDawson**
- [x] I have read [freeCodeCamp's contribution guidelines](https://github.com/freeCodeCamp/freeCodeCamp/blob/master/CONTRIBUTING.md).
- [x] My pull request has a descriptive title (not a vague title like `Update index.md`)
- [x] My pull request targets the `master` branch of freeCodeCamp.
- [x] None of my changes are plagiarized from another source without proper attribution.
- [x] All the files I changed are in the same world language (for example: only English changes, or only Chinese changes, etc.)
- [x] My changes do not use shortened URLs or affiliate links.

**PR Purpose:** Converts `blockquote` elements to triple backtick syntax in the `Description` and `Instructions` sections of the `Front End Libraries` challenges.

Related to issue #35991

### CODE REVIEW

**Review by moT01 — APPROVED** [review]
Looks good to me! 🎉

**Review by ojeytonwilliams — CHANGES_REQUESTED** [review]
Aside from some nitpicks about `js` vs `jsx`, everything looks good.

**Comment by RandellDawson** [comment]
@ojeytonwilliams I made your suggested changes.

**Review by ojeytonwilliams — APPROVED** [review]

**Comment by ojeytonwilliams** [comment]
@RandellDawson Thanks for doing that, LGTM.

**Comment by RandellDawson** [comment]
@moT01 @ojeytonwilliams See my comment on #35993. I believe this can be merged now.

**Comment by moT01** [comment]
🎉

**Pull request merged**
