### PR TITLE
feat: reimplement Growthbook

### PR DESCRIPTION
**Pull request by ahmaxed**
This pr archives the followings:

1. Removed unused feature flagged alerts.
2. Set up Growthbook for all users (previously signed in only).
3. Create a UUID cookie
4. Pass UUID cookie to Growthbook as ID
5. Add aa-test-in-component

Note for reviewers: the related env key has been updated. 

Checklist:

- [x] I have read [freeCodeCamp's contribution guidelines](https://contribute.freecodecamp.org).
- [x] My pull request has a descriptive title (not a vague title like `Update index.md`)
- [x] My pull request targets the `main` branch of freeCodeCamp.
- [x] I have tested these changes either locally on my machine, or GitPod.

Closes #XXXXX

### CODE REVIEW

**Review by Sembauke — APPROVED** [review]

**Review by ShaunSHamilton — COMMENTED** [review]
I cannot get the Relational Database feature to show. I might be doing something wrong, but I did try a lot of things.

**Comment by ahmaxed** [comment]
Use the production key and you will sea it after a refresh. 

The DB feature flag is ON for production only.

**Comment by ShaunSHamilton** [comment]
> Use the production key and you will sea it after a refresh.
> 
> The DB feature flag is ON for production only.

Thank you. I keep editing the `web.gb` site. I hope we get rid of that soon, otherwise, I will probably waste many more hours on this.

**Review by ShaunSHamilton — APPROVED** [review]
This LGTM 👍 Thank you for bearing with me as I stumbled through the review

**Pull request merged**
