### PR TITLE
Revise intro for Basic CSS section

### LINKED ISSUE #13145: There are more (common) ways of using CSS
Challenge [introduction-to-basic-css](http://beta.freecodecamp.com/en/challenges/basic-css/introduction-to-basic-css) has an issue.

> CSS can be applied both as inline styles—typed directly within HTML style tags—or external style sheets—typed in a separate file that is referenced from your HTML file. 

The text implies there are two ways of using CSS, and ignores using CSS via `style` attribute.

As [W3 describes](https://www.w3.org/TR/CSS2/intro.html#design-principles):

> Flexibility. CSS can be applied to content in several ways. The key feature is the ability to cascade style information specified in the default (user agent) style sheet, user style sheets, linked style sheets, the document head, and in attributes for the elements forming the document body.

_This bug is targeted for the beta version._

### PR DESCRIPTION
**Pull request by HKuz**
#### Pre-Submission Checklist

- [x] Your pull request targets the `staging` branch of freeCodeCamp.
- [x] Branch starts with either `fix/`, `feature/`, or `translate/` (e.g. `fix/signin-issue`)
- [x] You have only one commit (if not, [squash](http://forum.freecodecamp.com/t/how-to-squash-multiple-commits-into-one-with-git/13231) them into one commit).
- [x] All new and existing tests pass the command `npm test`. Use `git commit --amend` to amend any fixes.

#### Type of Change

- [x] Small bug fix (non-breaking change which fixes an issue)

#### Checklist:

- [x] Tested changes locally.
- [x] Closes currently open issue (replace XXXX with an issue no): Closes #13145 

#### Description

Small revisions to the introduction for the CSS challenges to clarify the three ways to apply CSS.

### CODE REVIEW

**Comment by HKuz** [comment]
@Greenheart - changes to the CSS intro, as discussed over in the issue 😄

**Review by Greenheart — APPROVED** [review]
@HKuz Excellent! :ok_hand: 

Also, thanks to @Hapoofesgeli for reporting! :smile:

**Comment by bigkatspence** [comment]
@BerkeleyTrue @Greenheart @ceejayoz @shlomif  to me it looks pretty good , i think it it worth moving from staging to a full commit

**Comment by Greenheart** [comment]
@bigkatspence It'll be published to https://beta.freecodecamp.com in a few days and pushed to the main site only when the rest of the curriculum expansion is complete. We're currently QA:ing and finalizing the new challenges :blush:

**Comment by bigkatspence** [comment]
@Greenheart  let me know if we have any code that need going over am decent at picking out bugs in code

**Pull request merged**
