### PR TITLE
Feat/test challenges for all lang

### PR DESCRIPTION
**Pull request by ValeraS**
This PR shows challenge errors for other langs.

### CODE REVIEW

**Comment by ValeraS** [comment]
@raisedadead, @Bouncey In Travis CI, you can see the current state of non-English challenges.

Here are two types of errors in most:
1. `ValidationError` - some sections became `undefined`. [Example](https://github.com/freeCodeCamp/freeCodeCamp/blob/2ca3a2093fb9359483442e0fadeda1ea0fefff86/curriculum/challenges/arabic/01-responsive-web-design/applied-accessibility/use-headings-to-show-hierarchical-relationships-of-content.arabic.md#instructions)
2. `SyntaxError: missing ) after argument list` - it's because translation has been made from broken English challenge files. I've mentioned it in #18828.

**Review by raisedadead — COMMENTED** [review]
Thanks for the update @ValeraS !

I like where this is heading, can we get more control on how when when we run the tests for? 

That is  I agree that by default these tests should be run for everything. 

Then instead of this array:
```js
const supportedLangs = [
  'arabic',
  'chinese',
  'english',
  'portuguese',
  'russian',
  'spanish'
];
```
I would like to be able to select the languages that I want the tests to run on. Meaning something on the lines of:

```
process.ENV.BUILD_FOR_LANGUAGE='english, arabic, chinese'
```

where it **should build and test all languages** if I have this env var `undefined`.

My reasoning being, once we merge this PR, we can enforce work on a language one by one, making the workflow stricter gradually.

This way, we leave @freeCodeCamp/translation-team to work thru their respective languages and fixup the issues like you have demonstrated.

**Review by Bouncey — APPROVED** [review]
This LGTM 👍 

Does as requested be @raisedadead

**Comment by Bouncey** [comment]
@raisedadead, do we want to handle all the syntax errors in each language before merging?

**Comment by raisedadead** [comment]
> do we want to handle all the syntax errors in each language before merging?

Yes, eventually as we go live with them into the beta?

**Comment by raisedadead** [comment]
Let's get this in. If you are happy with it.

**Pull request merged**
