### PR TITLE
feat(client): add badges to Camper profile

### LINKED ISSUE #42837: Discourse-Learn Integration
Following the addition of more badges to profiles, this issue discusses the possible integration of the Discourse API with `/learn`.

As Discourse comes with the API and GUI to create/grant badges, it would be most ideal to _seamlessly_ provide this functionality on a Camper's profile on `/learn`.

Possible Feature Additions (will do):
- [x] Display all current badges from `forum` to `/learn`
- [x] Use Discourse to upload/create i18n badges
- [x] Port _Top Contributor_ badges (years) over to Discourse
- [ ] Add `forum` account metrics to `/learn` (e.g. Number of hearts, number of question answers)

Implementation Details:
- Use associated email addresses for authentication
  - Some Campers use a separate email for forum and `/learn`
    - Allow Campers to manually associate forum account with `/learn`? ❌ 
  - Use OAuth to authenticate (match) Camper accounts ✔️ 
  - Will require API Key for at least email verification
- Which privacy settings to use for feature?
  - Use an existing setting (e.g. `profile`) ✔️ 
  - Automatically associate known email addresses? _Potentially require intervention on `/settings`
- Styling
  - How to display the badges on the profile?
    - At the very bottom ✔️ _low priority_
    - Probably provide collapsible functionality
    - Use Discourse-provided priority meta for order
    - Use Discourse-provided _favourites_ functionality for displaying Camper-chosen badges

**TODO**
- [x] Open initial PR
- [ ] Investigate SVG vs JPEG for creating badges
- [ ] Finalise authentication method

[Discourse Badges API Documentation](https://docs.discourse.org/#tag/Badges)

### PR DESCRIPTION
**Pull request by ShaunSHamilton**
Checklist:

- [x] I have read [freeCodeCamp's contribution guidelines](https://contribute.freecodecamp.org).
- [x] My pull request has a descriptive title (not a vague title like `Update index.md`)
- [x] My pull request targets the `main` branch of freeCodeCamp.
- [x] I have tested these changes either locally on my machine, or GitPod.

Closes #42837 

**TODO**
- [ ] Look at potentially creating an epic for data handling
- [x] Integrate method to link Discourse and `/learn` accounts
- [ ] Clean up styling to be responsive
- [x] Change badge background to be same as container
- [x] Get new badge description and long description
- [ ] Link display of badges to existing privacy setting (My Portfolio?)
- [ ] Finalise how to display/order badges
- - [ ] Collapsable?
- - [ ] Show favourites above other Profile content?
- - [ ] Add more `badge_groups` to meta on Discourse?

As of _08/09/2021_
- My forum account is the only one with a new Badge awarded - for testing
- Discourse Connect does not have correct Headers to allow `localhost:8000` to be redirected

CC:/ @RafaelDavisH

### CODE REVIEW

**Comment by ShaunSHamilton** [comment]
Since the latest commit, this works. Testing is only possible over HTTPS through GitPod, after adding the domain to Discourse's CORS and `discourse connect secrets` settings input.

This does not make use of the generated `nonce`, because I am unsure how to persist the nonce from one request to another. Oliver has mentioned use of cookies which I am looking into.

**Comment by ahmadabdolsaheb** [comment]
Do we still need this feature?

**Comment by ShaunSHamilton** [comment]
@ahmadabdolsaheb Thank you, for pinging on this. I had completely forgot about this feature 😰 

I will find out from Quincy and Rafa, if this is something I should try to _get out the door_ soon.

**Comment by ShaunSHamilton** [comment]
Closing for now.

This might become relevant again closer to WTM (September)

**Pull request closed without merging**
