### PR TITLE
Updated instructions and gifs from c9 + Heroku to Glitch.com

### LINKED ISSUE #15044: Replacing Heroku / C9.io instructions with Glitch.com instructions on production
We no longer recommend using Heroku.com + C9.io for our back end projects. Both of them now require credit cards, and have limited resources.

Instead, we recommend Glitch.com. 

We need to update the instructions on our back end challenges to tell campers to use Glitch.com instead. Here's what these instructions look like on our beta branch:

managing_packages_with_npm__how_to_use_package_json__the_core_of_any_node_js_project_or_npm_package___freecodecamp_

Is anyone interested in branching off of backup/master and modifying the back end certificate's seed files to remove the references to Heroku and C9, and recommend Glitch.com instead?

### PR DESCRIPTION
**Pull request by codemzy**
#### Pre-Submission Checklist

- [ ] Your pull request targets the `staging` branch of freeCodeCamp.
- [x] Branch starts with either `fix/`, `feature/`, or `translate/` (e.g. `fix/signin-issue`)
- [x] You have only one commit (if not, [squash](http://forum.freecodecamp.com/t/how-to-squash-multiple-commits-into-one-with-git/13231) them into one commit).
- [x] All new and existing tests pass the command `npm test`. Use `git commit --amend` to amend any fixes.

#### Type of Change

- [x] Small bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds new functionality)
- [ ] Breaking change (fix or feature that would change existing functionality)
- [ ] Add new translation (feature adding new translations)

#### Checklist:

- [x] Tested changes locally.
- [x] Closes currently open issue (replace XXXX with an issue no): Closes #15044

#### Description

I think it is right that this PR should be against the backup/master branch since is a change to that branch as per issue #15044 ??

I have updated the gifs and instructions on the backend challenges to change the recommendation from c9 + Heroku to Glitch. 

This should help campers be able to sign up and set up projects in Glitch. Also added some info about mLab for the projects that require MongoDB.

### CODE REVIEW

**Comment by codemzy** [comment]
_Note: The learn you mongo and how to npm waypoints still point to c9.io, I didn't change these (within this pull request) to Glitch as I wan't able to install mongo on Glitch so mongo shell wouldn't work for learn-you-mongo, and while I was able to access the console on Glitch, new files created in the terminal were not showing up in the file directory on the project even when committed to git. Console access seems to be a new feature in Glitch, so may just be a glitch._ 🤣

**Review by raisedadead — APPROVED** [review]
#### :sparkles: :sparkles: **LGTM.** :sparkles: :sparkles: 

Thanks @codemzy

**Comment by raisedadead** [comment]
@QuincyLarson this is good to go! :shipit:

**Review by Jefreesujit — COMMENTED** [review]
Seems good!

**Pull request merged**
