### PR TITLE
Update Chinese translation of CONTRIBUTING.md 

### PR DESCRIPTION
**Pull request by aaronsum1102**
Refer to issue #18310
- [ x] I have read [freeCodeCamp's contribution guidelines](https://github.com/freeCodeCamp/freeCodeCamp/blob/master/CONTRIBUTING.md).
- [x ] My pull request has a descriptive title (not a vague title like `Update index.md`)
- [x ] My pull request targets the `master` branch of freeCodeCamp.
- [x ] None of my changes are plagiarized from another source without proper attribution.
- [x ] My article does not contain shortened URLs or affiliate links.

### CODE REVIEW

**Review by dingjy94 — APPROVED** [review]

**Comment by dingjy94** [comment]
@aaronsum1102 
Congrats on your first pull request (PR)! 🎉

Thank you for your contribution to the page! 👍 We're happy to accept these changes and look forward to future contributions.

**Comment by QuincyLarson** [comment]
@aaronsum1102 Awesome! Thanks for this translation.

@dingjy94 thanks for the assist! 

We are launching a new Chinese-language forum, and also a Chinese-language podcast. Would either of you be interested in getting involved?

**Comment by dingjy94** [comment]
@QuincyLarson 
Yes, of course, I'm really interested in this chance.  What can I do for this new forum and podcast?

**Comment by QuincyLarson** [comment]
@dingjy94 We will launch the forum soon. 

Regarding the podcast, I recommend putting together a list of people from the Chinese developer community whom you think would be good guests for the Chinese-language podcast. I can walk you through how to interview these people using our podcasting tools.

Please send me an email at quincy@freecodecamp.org and we can continue our discussion there.

**Pull request merged**
