### PR TITLE
Fix: Learn Greetings in your First Day at the Office - Task 32 - Sentence doesn't match audio

### LINKED ISSUE #53010: Learn Greetings in your First Day at the Office - Task 32 - Sentence doesn't match audio
### Describe the Issue

The fill-in-the-blank sentence doesn't match what the character says.

### Affected Page

https://www.freecodecamp.org/learn/a2-english-for-developers/learn-greetings-in-your-first-day-at-the-office/task-32

### Your code

The written sentence is:
`Thanks, Maria, for ___ me around the ___.`

### Expected behavior

The character says:
`Thanks for ___ me around the ___, Maria.`

### Screenshots

_No response_

### System

- Device: all
- OS: all
- Browser: all
- Version: all

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by aakash-a-dev**
Checklist:

- [x] I have read and followed the [contribution guidelines](https://contribute.freecodecamp.org).
- [ ] I have read and followed the [how to open a pull request guide](https://contribute.freecodecamp.org/#/how-to-open-a-pull-request).
- [x] My pull request targets the `main` branch of freeCodeCamp.
- [x] I have tested these changes either locally on my machine, or GitPod.

Closes #53010

### CODE REVIEW

**Comment by ieahleen** [comment]
can you expand on how this PR fixes the linked issue?

**Review by gikf — CHANGES_REQUESTED** [review]
Hey @aakash-a-dev there seem to be few commits unrelated to the issue - they will need to be removed from PR.

One of them appear to contain your credentials to the mongodb cluster, so make sure you change your password.

**Comment by aakash-a-dev** [comment]
@ieahleen I followed the steps described in the issue itself and it worked:

In https://github.com/freeCodeCamp/freeCodeCamp/blob/main/curriculum/challenges/chinese/21-a2-english-for-developers/learn-greetings-in-your-first-day-at-the-office/656a14b0e1c43d0ffabd15a9.md:
Change the text in the AUDIO REFERENCE tag from Thanks, Maria, for showing me the place! to Thanks for showing me around the place, Maria. in https://github.com/freeCodeCamp/freeCodeCamp/blob/main/curriculum/challenges/chinese/21-a2-english-for-developers/learn-greetings-in-your-first-day-at-the-office/656a14b0e1c43d0ffabd15a9.md
In https://github.com/freeCodeCamp/freeCodeCamp/blob/main/curriculum/challenges/english/21-a2-english-for-developers/learn-greetings-in-your-first-day-at-the-office/656a18189b21f51037e518b4.md:
Change the text in the AUDIO REFERENCE tag from Thanks, Maria, for showing me around the place! to Thanks for showing me around the place, Maria.
Change the fill-in-the-blank sentence from Thanks, Maria, for _ me around the _. to Thanks for _ me around the _, Maria..

I followed this steps

**Comment by aakash-a-dev** [comment]
@gikf Yes I did it sorry, it happens for testing purpose as I am using Atlas, so for that. I changed the password

**Review by majestic-owl448 — CHANGES_REQUESTED** [review]
You have 68 files changed in this PR, please remove the 67 files that are not needed for this PR. This is one of the reasons for which making changes on the main branch is a bad idea.

**Comment by aakash-a-dev** [comment]
Okat @ieahleen I am working on this.

**Comment by aakash-a-dev** [comment]
Closing this PR as it found a lot of fault during setting up offline. Raised a new PR on the same issue with more precaution and correct file changes only. Sorry and So much Thank you for valuable feedback.

**Pull request closed without merging**
