### PR TITLE
fix: update "Note" formatting in "Remove Elements from a Linked List" challenge

### LINKED ISSUE #36171: Changing "Note" formatting in "Remove Elements from a Linked List" challenge
Following the conventions decided upon in #35464, we should change the instruction in the "Remove Elements from a Linked List" challenge - 
```
Note The length of the list should decrease by one every time an element is removed from the linked list.
```
to 
```
<strong>Note:</strong> The length of the list should decrease by one every time an element is removed from the linked list.
```
**Add a Link to the page with the problem:**
https://learn.freecodecamp.org/coding-interview-prep/data-structures/remove-elements-from-a-linked-list/

The file to be changed is [here](https://github.com/freeCodeCamp/freeCodeCamp/blob/master/curriculum/challenges/english/08-coding-interview-prep/data-structures/remove-elements-from-a-linked-list.english.md). 

Since this is a simple change, we would welcome Pull Requests from first time contributors.

### PR DESCRIPTION
**Pull request by minggas**
- [X ] I have read [freeCodeCamp's contribution guidelines](https://github.com/freeCodeCamp/freeCodeCamp/blob/master/CONTRIBUTING.md).
- [X ] My pull request has a descriptive title (not a vague title like `Update index.md`)
- [X ] My pull request targets the `master` branch of freeCodeCamp.
- [ X] None of my changes are plagiarized from another source without proper attribution.
- [X ] All the files I changed are in the same world language (for example: only English changes, or only Chinese changes, etc.)
- [X ] My changes do not use shortened URLs or affiliate links.

Closes #36171

### CODE REVIEW

**Review by ojeytonwilliams — APPROVED** [review]
LGTM :+1:

**Review by RandellDawson — APPROVED** [review]
LGTM

**Comment by RandellDawson** [comment]
I moved the note to the same line as `<strong>Note:</strong>` per the current style guidelines.

**Review by moT01 — APPROVED** [review]
LGTM - congratulations on your first contribution to freeCodeCamp @minggas!

**Pull request merged**
