### PR TITLE
chore(curriculum): Remove an incorrect sentence

### LINKED ISSUE #48856: Unecessary opinion and innaccuracy surrounding notes about classes
### Describe the Issue

On the topic of ES6 classes in JavaScript, the section in question reads this sentence at the very top of the article:

> It should be noted that the class syntax is just syntax, and not a full-fledged class-based implementation of an object-oriented paradigm, unlike in languages such as Java, Python, Ruby, etc.

This is entirely uneccesary, confusing to beginners, and incorrect by any existing definition of a class. While ES6 classes are certainly a syntax sugar for prototypal inheritence, it doesn't make them "not a full-fledged class-based implementation of an object-oriented paradigm." ES6 provides a syntax which makes ugly prototypal inheritence _look like_ a traditional OOP implementation of classes but it already _behaved like_ classes. This makes it a true class based implementation because it allows for the development & behavior of applications using object-oriented-paradigms with classes and all the features you would expect. And for any possible definition I could find of what a class is, it is the programatic behavior of using it that defines it, not any kind of underlying implementation.

This is especially problematic when Python is listed among the languages that _do_ support a "full fledged class-based implementation." Python is also a runtime scripting language that is dynamically typed, with classes that are also entirely mutable, similar to JavaScript. So if someone happens to know Python then it is _extra_ confusing.

### Affected Page

https://github.com/freeCodeCamp/freeCodeCamp/blob/main/curriculum/challenges/english/02-javascript-algorithms-and-data-structures/es6/use-class-syntax-to-define-a-constructor-function.md

### Steps to Reproduce

I don't know why the "Steps to Reproduce" section is here. This should be the template for a "content" error, not a challenge error.

### Recommended fix or suggestions

Just remove this sentence as it does nothing to help anyone's understanding of programming or features of JavaScript as a language. It may be helpful to have a section about prototypal inheritence here and that syntax instead before showing the class based syntax so the student understands the underlying implementation. However, I don't feel that an extra section is nearly as valuable as it would be to just  remove this sentence.

### Screenshots

_No response_

### PR DESCRIPTION
**Pull request by a2937**
Checklist:

- [X] I have read and followed the [contribution guidelines](https://contribute.freecodecamp.org).
- [X] I have read and followed the [how to open a pull request guide](https://contribute.freecodecamp.org/#/how-to-open-a-pull-request).
- [X] My pull request targets the `main` branch of freeCodeCamp.
- [X] I have tested these changes either locally on my machine, or GitPod.

Closes #48856

### CODE REVIEW

**Review by Sboonny — APPROVED** [review]
LGTM 🎉, thank you for your contribution to the page! 👍.

**Comment by a2937** [comment]
Should I update the alternate language versions of the curriculum as well? I have enough context clues to apply the fix to the rest I believe.

**Comment by Sboonny** [comment]
Crowdin downloads will take care of alternative language version, don't worry.

**Review by gikf — APPROVED** [review]
LGTM :+1:

**Pull request merged**
