### PR TITLE
fix(guide): Redux Selectors

### PR DESCRIPTION
**Pull request by jonniebigodes**
Created a simple guide document for redux selectors, with a simple example to ilustrate the pattern

- [X] I have read [freeCodeCamp's contribution guidelines](https://github.com/freeCodeCamp/freeCodeCamp/blob/master/CONTRIBUTING.md).
- [X] My pull request has a descriptive title (not a vague title like `Update index.md`)
- [X] My pull request targets the `master` branch of freeCodeCamp.
- [X] None of my changes are plagiarized from another source without proper attribution.
- [X] My article does not contain shortened URLs or affiliate links.

### CODE REVIEW

**Comment by lynxlynxlynx** [comment]
You screwed up the title tag.

**Comment by jonniebigodes** [comment]
@lynxlynxlynx sorry about the fumble fingering. The title is corrected on the redux middleware guide.
Should be ok now. Thank you for the heads up

**Comment by lynxlynxlynx** [comment]
Check the first line of the diff.

**Comment by jonniebigodes** [comment]
Correcting it now. On my branch fix/redux-middleware it was corrected but not on the branch fix/redux-selector

**Pull request merged**
