### PR TITLE
fix(tools): bug in directory creation

### PR DESCRIPTION
**Pull request by naomi-lgbt**
Checklist:

- [X] I have read and followed the [contribution guidelines](https://contribute.freecodecamp.org).
- [X] I have read and followed the [how to open a pull request guide](https://contribute.freecodecamp.org/#/how-to-open-a-pull-request).
- [X] My pull request targets the `main` branch of freeCodeCamp.
- [X] I have tested these changes either locally on my machine, or GitPod.

Closes #XXXXX

### CODE REVIEW

**Review by ShaunSHamilton — COMMENTED** [review]
Looks the same:
image

**Review by scissorsneedfoodtoo — COMMENTED** [review]
Everything LGTM 👍

As far as I can tell, this should strip the filename off of `targetDir` before creating the directory, which was the issue before.

**Comment by naomi-lgbt** [comment]
Shaun are you looking at an old commit by chance?

**Comment by naomi-lgbt** [comment]
I did do a force push to clean up that PR.

**Comment by ShaunSHamilton** [comment]
> Shaun are you looking at an old commit by chance?

There is only one commit in this PR?

**Review by ShaunSHamilton — APPROVED** [review]

**Review by ShaunSHamilton — APPROVED** [review]
Fine. This does not fix the bugs that I make up, but it does fix the other one

**Review by scissorsneedfoodtoo — APPROVED** [review]

**Pull request merged**
