### PR TITLE
fix(curriculum): sentence construction in build an RPG project

### LINKED ISSUE #48775: overly wordy statement in new JS course step 16 of build-a-role-playing-game
### Describe the Issue

step16 of the build an rpg for the new JS course has this overly wordy sentence:

`Add a <code>console.log("Hello World");</code> line between your <code>script</code> tags, then click the "Console" button to open our console, and you should see the text <code>Hello World</code> in your console.`

The use of "our console" and then "your console" makes the sentence unwieldy and harder to translate as well.

I discussed this with @jeremylt in the discord forum for contributors and he agreed and came up with the following recommendation:
`Add a <code>console.log("Hello World");</code> line between your <code>script</code> tags. Then click the "Console" button to open the console. You should see the text <code>Hello World</code>.`

### Affected Page

https://github.com/freeCodeCamp/freeCodeCamp/blob/main/curriculum/challenges/english/15-javascript-algorithms-and-data-structures-22/learn-basic-javascript-by-building-a-role-playing-game/62a255dae245b52317da824a.md

### Your code

```

```

### Expected behavior

It is expected that the new JS curriculum use concise sentences where possible.

### Screenshots

_No response_

### System

n/a

### Additional context

link to the discord discussion
<https://discordapp.com/channels/692816967895220344/715074489422970962/1053112008461000776>

### PR DESCRIPTION
**Pull request by Sriparno08**
Checklist:

- [x] I have read [freeCodeCamp's contribution guidelines](https://contribute.freecodecamp.org).
- [x] My pull request has a descriptive title (not a vague title like `Update index.md`)
- [x] My pull request targets the `main` branch of freeCodeCamp.
- [x] I have tested these changes either locally on my machine, or GitPod.

Closes #48775

The below sentence:

`Add a <code>console.log("Hello World");</code> line between your <code>script</code> tags, then click the "Console" button to open our console, and you should see the text <code>Hello World</code> in your console.`

is changed to:

`Add a <code>console.log("Hello World");</code> line between your <code>script</code> tags. Then click the "Console" button to open the console. You should see the text <code>Hello World</code>.`

### CODE REVIEW

**Comment by raisedadead** [comment]
We are officially on Node.js 18 now. We have changed the merge requirements accordingly.

You will need to rebase this PR against the main branch OR Click the "Update branch" button to get the new checks going.

Thanks for your contribution.

**Review by naomi-lgbt — DISMISSED** [review]

**Comment by Sriparno08** [comment]
Updated it, @naomi-lgbt!

**Review by Sembauke — APPROVED** [review]

**Review by naomi-lgbt — APPROVED** [review]
banger pr, thanks for contributing!

**Comment by Sriparno08** [comment]
Thanks, @naomi-lgbt!

**Pull request merged**
