### PR TITLE
combine backslash tests for quoting strings challenge

### LINKED ISSUE #10338: Goals are contradictory
Remove all the backslashes (\)
You should have two single quotes ' and four double quotes "
Only remove the backslashes \ used to escape quotes.

Challenge [Quoting Strings with Single Quotes](https://www.freecodecamp.com/challenges/quoting-strings-with-single-quotes#?solution=%0Avar%20myStr%20%3D%20%22%3Ca%20href%3D'http%3A%2F%2Fwww.example.com'%20target%3D%22_blank%22%3ELink%3C%2Fa%3E%22%3B%0A%0A%0A) has an issue.
User Agent is: <code>Mozilla/5.0 (iPad; CPU OS 9_3_3 like Mac OS X) AppleWebKit/601.1.46 (KHTML, like Gecko) Version/9.0 Mobile/13G34 Safari/601.1</code>.
Please describe how to reproduce this issue, and include links to screenshots if possible.

My code:
```javascript

var myStr = "<a href='http://www.example.com' target="_blank">Link</a>";



```

### PR DESCRIPTION
**Pull request by dhcodes**
#### Pre-Submission Checklist

- [X] Your pull request targets the `staging` branch of FreeCodeCamp.
- [X] Branch starts with either `fix/`, `feature/`, or `translate/` (e.g. `fix/signin-issue`)
- [X] You have only one commit (if not, [squash](http://forum.freecodecamp.com/t/how-to-squash-multiple-commits-into-one-with-git/13231) them into one commit).
- [X] All new and existing tests pass the command `npm run test-challenges`. Use `git commit --amend` to amend any fixes.
#### Type of Change

- [X] Small bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds new functionality)
- [ ] Breaking change (fix or feature that would change existing functionality)
- [ ] Add new translation (feature adding new translations)
#### Checklist:

- [X] Tested changes locally.
- [X] Closes currently open issue (replace XXXX with an issue no): Closes #10338
#### Description

Combined the third test into the first via the following:
`"assert(!/\\\\/g.test(code) && myStr === '<a href=\"http://www.example.com\" target=\"_blank\">Link</a>', 'message: Remove all the <code>backslashes</code> (<code>\\</code>)');",`

### CODE REVIEW

**Comment by erictleung** [comment]
@dhcodes thanks for the PR! Unfortunately, I'm oddly enough unable to get the second test to work. Here's the code I submitted.

```js
var myStr = '<a href="http://www.example.com" target="_blank">Link</a>';
```

It passes the first test but fails the second test.

**Comment by dhcodes** [comment]
Thanks @erictleung. I'll take a look today.

**Comment by dhcodes** [comment]
Disregard camperbot for now. I'm working to update this but it's not ready yet.

**Comment by dhcodes** [comment]
@erictleung having looked into this more, I think the issue is actually #10258 as I did not change the test that is not working and it also doesn't work on the current beta site

**Comment by ltegman** [comment]
👍

**Comment by TheNewbCoder** [comment]
I made a comment below the string and put backlashes in it hit ctrl+enter, then removed those \'s again and hit ctrl+enter and somehow it worked out! :) Old thread but maybe it helps someone stuck on it.

**Pull request merged**
