### PR TITLE
fix NaN issue for the number of active Donations

### LINKED ISSUE #35964: [rocks/beta] Number of donators is NaN
**Describe the bug**
When you go to the donate page, the number of donators in not a number (displays as NaN).

**To Reproduce**
1. Go to https://www.freecodecamp.rocks/donate/ 
2. Scroll down to second paragraph.
3. Oops! There is a bug 🐛

**Expected behavior**
I expected to see number of donators.

**Screenshots**
73q9s_1

**Desktop (please complete the following information):**
 - OS: Windows 7 Ultimate
 - Browser: Firefox Quantum (64-bit)
 - Version: 66.0.3

### PR DESCRIPTION
**Pull request by waseemahmad31**
- [x] I have read [freeCodeCamp's contribution guidelines](https://github.com/freeCodeCamp/freeCodeCamp/blob/master/CONTRIBUTING.md).
- [x] My pull request has a descriptive title (not a vague title like `Update index.md`)
- [x] My pull request targets the `master` branch of freeCodeCamp.
- [x] None of my changes are plagiarized from another source without proper attribution.
- [x] All the files I changed are in the same world language (for example: only English changes, or only Chinese changes, etc.)
- [x] My changes do not use shortened URLs or affiliate links.

Closes #35964

### CODE REVIEW

**Review by ojeytonwilliams — APPROVED** [review]
I've checked this locally and it LGTM :+1:

**Comment by moT01** [comment]
I didn't test this out, but looking at the code - does it actually solve the problem? It looks like it just displays a `0` instead of `NaN` - is that the route we want to go? I guess it's probably better than nothing, but it doesn't seem like the best route to me.

**Comment by raisedadead** [comment]
> I didn't test this out, but looking at the code - does it actually solve the problem? It looks like it just displays a `0` instead of `NaN` - is that the route we want to go? I guess it's probably better than nothing, but it doesn't seem like the best route to me.

This is an case, that you will never see on production systems. That is you will always have a valid number of donors present on production. However, defaulting this to 0 is probably a good idea, which I think this PR achieves.

**Review by raisedadead — COMMENTED** [review]
I would probably do this instead:

```js
export const activeDonationsSelector = state => {
  const currentDonations = Number(sessionMetaSelector(state).activeDonations) + Number(PAYPAL_SUPPORTERS);
  return isNaN(currentDonations) ? 0 : currentDonations; 
};
```

**Review by raisedadead — COMMENTED** [review]
However, the real issue/bug here is the the env variable is left un-defaulted to an initial value.

```js
export const activeDonationsSelector = state =>
  Number(sessionMetaSelector(state).activeDonations) +
  Number(PAYPAL_SUPPORTERS || 0);
```

That should be the enough for a fix. Ideally whenever depending on any environment values, we should  be defaulting to something.

**Comment by ojeytonwilliams** [comment]
What about starting it as 0 in `intialState`?
```js
sessionMeta: { activeDonations: 0}
```

**Comment by raisedadead** [comment]
> What about starting it as 0 in `initialState`?
> 
> ```js
> sessionMeta: { activeDonations: 0}
> ```

Yes, that and defaulting the env var as well is the ideal fix.

**Comment by waseemahmad31** [comment]
> What about starting it as 0 in `initialState`?
> 
> ```js
> sessionMeta: { activeDonations: 0}
> ```

Yep, this will be a cleaner approach.

**Review by ojeytonwilliams — APPROVED** [review]
Thanks for making the changes, LGTM.

**Comment by raisedadead** [comment]
@ojeytonwilliams Please merge if tested locally. Thanks for the QA.

**Comment by ojeytonwilliams** [comment]
@waseemahmad31 Congrats on your first pull request (PR)! 🎉

Thank you for your contribution! 👍
We're happy to accept these changes, and look forward to future contributions. 📝

**Pull request merged**
