### PR TITLE
added optional space to the editor match in OOP challenges.

### LINKED ISSUE #3331: Error: "You should have made use of the reduce/filter method"
Challenge [Waypoint: Condense arrays with reduce](http://freecodecamp.com/challenges/waypoint-condense-arrays-with-reduce) has an issue.
Challenge [Waypoint: Filter Arrays with filter](http://freecodecamp.com/challenges/waypoint-filter-arrays-with-filter) has an issue.
User Agent is: <code>Mozilla/5.0 (Windows NT 6.2; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/45.0.2454.85 Safari/537.36</code>.
A space between 'array.reduce' and '(' will make the reduce method undetectable. When I remove the space, everything goes well.
The same error also exist in "Filter array with filter" waypoint, with slightly different error message.

My code:
```javascript
var array = [4,5,6,7,8];
var singleVal = 0;
// Only change code below this line.
var singleVal = array.reduce (function (previousVal,currentVal){
  return previousVal+currentVal;
});


// Only change code above this line.
(function() {return singleVal;})();

```

### LINKED ISSUE #3577: Problem with spacing in return value
Challenge [Waypoint: Iterate over Arrays with map](http://freecodecamp.com/challenges/waypoint-iterate-over-arrays-with-map) has an issue.
User Agent is: <code>Mozilla/5.0 (Macintosh; Intel Mac OS X 10_10_5) AppleWebKit/601.1.56 (KHTML, like Gecko) Version/9.0 Safari/601.1.56</code>.
Please describe how to reproduce this issue, and include links to screenshots if possible.

My code:
```javascript
//Use map to add three to each value in the array
var array = [1,2,3,4,5];
// Only change code below this line.
array = array.map (function(val) {
  return val+3;
});
// Only change code above this line.
(function() {return array;})();

```
If you include spaces in the return statement (for example ```return val + 3;``` as opposed to ```return val+3``` as in the code above, the waypoint fails with an error indicating the map function hasn't been used.

### PR DESCRIPTION
**Pull request by natac13**
closes #3331

Edit by @ahstro:
closes #3577

### CODE REVIEW

**Comment by bugron** [comment]
Hey @natac13, thanks for this PR. Please, read [Contributing Guidelines](https://github.com/FreeCodeCamp/FreeCodeCamp#contributing) and in future name your branches like `fix/xxx` or `feature/xxx`, thanks.

**Comment by natac13** [comment]
For sure sorry about that one!

**Comment by bugron** [comment]
Hey @natac13, please, pull the latest code, rebase with this branch and resolve conflicts so we can merge this PR, thanks.

**Comment by ahstro** [comment]
The question marks after `\s*` are not necessary, since `*` means "0 or more" and `?` means "whether the previous character exists or not".
Also, I added `closes #3577` to the description since that issue is fixed as well.

**Comment by natac13** [comment]
@Bugron for sure! As soon as I get home to a computer.

**Comment by natac13** [comment]
@bugron I hope I was able to handle that correctly! lol Great learning experience!!

**Comment by ahstro** [comment]
@natac13 I'm confused, why did you close this?

**Comment by natac13** [comment]
@ahstro I didn't... once I did the rebase and resolved the conflicts I pushed and it did this itself...

**Comment by natac13** [comment]
I am starting to think I really messed something up. really sorry

**Comment by natac13** [comment]
I think I know what my issue was and fixing now

**Comment by ahstro** [comment]
I love when you see a "I'm fixing it"-comment from a couple of hours ago and then nothing :wink:
Seriously though, let me know if you need git help.

**Comment by natac13** [comment]
@ahstro WOW what a comment guess you don't realize I am new to this and messed this PR up so I submitted a new one. And i guess I didn't realize I answer to you and have to update you every step of the way. Maybe I an out of line but I feel a comment like that makes a new contributor anxious which should not be the case with the joy of coding!

**Comment by natac13** [comment]
Thanks for letting me know about the regex. I made the change you suggest.

**Comment by ahstro** [comment]
@natac13 I'm really sorry if you were offended, that was definitely not my intention! I've done the same thing myself. I understand that things take time. Sorry! Also, my bad that I didn't see your other PR. I looked, but it must've been merged too quickly for me to find it open.

**Comment by natac13** [comment]
@ahstro  thank you for clearing that up... I was really just taking back as all.

**Pull request closed without merging**
