### PR TITLE
Add 'copy to clipboard' buttons for easy challenge link and code copying

### LINKED ISSUE #4092: Gitter Tool Pallet
> Gitter Tool Pallet
1) Copy Solution as Gitter Link
Precisely as @abhisekp suggested above:  :point_up: November 1, 2015 4:05 AM (Sans URL Shortening) - It is definitely Gitter specific, but Gitter is our help platform of choice.
2) Copy Solution as Gitter Formatted code.
Would prepend the ```js and backtick suffix to simplify cuting and pasting a solution for review. I've also been thinking about adding a waypoint on this, because we burn a lot of time trying to get people to understand this. It's a waste of helper time and it's a waste of camper time.

-@saintpeter

### PR DESCRIPTION
**Pull request by bugron**
Adds the following buttons to the Gitter tool pallet.

Clicking the first button copies the challenge link in [this format](https://github.com/FreeCodeCamp/FreeCodeCamp/issues/4092#issuecomment-152839868) if user isn't logged in, and in [this format](https://github.com/FreeCodeCamp/FreeCodeCamp/issues/4092#issuecomment-152839930) if user is logged in.
Clicking the second button copies the challenge code in Markdown syntax.

Uses [clipboard.js](http://zenorocha.github.io/clipboard.js/). Don't forget to `bower install clipboard`.
Closes #4092.

### CODE REVIEW

**Comment by SaintPeter** [comment]
@BerkeleyTrue Travis does not do `bower install`

**Comment by bugron** [comment]
Fails because of https://travis-ci.org/FreeCodeCamp/FreeCodeCamp/builds/101499217#L1508 but works in local.

**Comment by abhisekp** [comment]
@bugron it fails in local too using `npm test`

**Comment by SaintPeter** [comment]
Seems to work well enough, in my local testing.  Sounds like there are some test issues to be resolved.

**Comment by ltegman** [comment]
This has some linting errors that need to be resolved.

**Comment by bugron** [comment]
I can't resolve https://travis-ci.org/FreeCodeCamp/FreeCodeCamp/builds/101507263#L1508. I don't know how.

**Comment by ltegman** [comment]
@bugron At the top of `create-editor.js` where it says:
```js
const {
    Rx: { Subject, Observable },
    CodeMirror,
    emmetCodeMirror,
    common = { init: [] }
  } = global;
```
change it to:
```js
const {
    Rx: { Subject, Observable },
    CodeMirror,
    emmetCodeMirror,
    Clipboard,
    common = { init: [] }
  } = global;
```

**Comment by bugron** [comment]
@ltegman thank you.

**Comment by SaintPeter** [comment]
Is there something we're waiting on to merge this?

**Comment by ltegman** [comment]
@SaintPeter Quincy's approval is needed for UI addtions AFAIK.

**Comment by SaintPeter** [comment]
@QuincyLarson Want to take a look?

**Comment by abhisekp** [comment]
Wouldn't it be nice if we could select some codes and the tool-tip for selecting the code appears above our selection? On click, it will copy in markdown format? Not everyone uses the sidecar.

**Comment by bugron** [comment]
@abhisekp is this what you are suggesting?

**Comment by abhisekp** [comment]
@bugron what side effects? It's a good solution. Campers will love it.

**Comment by bugron** [comment]
@abhisekp http://jsfiddle.net/v5L7m/296/ . Try selecting with doubleclick or clicking the link-button "Copy the code".

**Comment by BerkeleyTrue** [comment]
@bugron I think a tool tip is a much better approach that static buttons.

**Comment by abhisekp** [comment]
@bugron I see double click *sometimes* doesn't work well. Anyway, the selection works and that's what primarily required.

**Comment by bugron** [comment]
@BerkeleyTrue @abhisekp I'm not satisfied with the current implementation of the tool-tip. I'll work on it but can't promise I'll have a positive result. Also, @abhisekp this implementation has another bug issue. Clicking the link "Copy the code" isn't firing the `click` event (maybe because it is overwritten by `mousedown` and `mouseup`) so currently I am not able to interact with it.

**Comment by bugron** [comment]
Seems I've fixed all issues listed above, http://jsfiddle.net/v5L7m/297. If this is what you want I'll do the same for our editor.

**Comment by abhisekp** [comment]
@bugron why do you use `stopPropagation`? Why not let the event propagate and some other handler listen to it?
And the markdown format for JavaScript code is

    ```js
    <code here>
    ```

and HTML is

    ```html
    <code here>
    ```

and similar for CSS and SCSS.

**Comment by bugron** [comment]
@abhisekp not sure in this case that is important. Syntax highlighting will be done for our editor, for jsfiddle it's all the same. All these are secondary questions, check how is this implementation working.

**Comment by bugron** [comment]
OK, implemented the tool-tip for our editor

Editor's contents can be selected by mouse or by the `CTRL+A` shortcut. Tool-tip appears near the cursor.
But this is not ready to be merged. Needs to be QA'd.

**Comment by abhisekp** [comment]
@bugron the partial word breaks doesn't look good. I think it will be better to break at the whitespaces.

```js
copyButton = `<a id="demo" href="/" data-toggle="popover" data-trigger="ma\
nual" title="<a class='demo1' id='markdown' href='/' data-toggle='popover'\
data-trigger='manual' title='Copy the contents of code editor with Markdo\
wn syntax highlighting' data-content='And here's some amazing content. It\
's very engaging. Right?'>Copy markdown</a>" data-content="<a class='demo\
1' id='plain' href='/' data-toggle='popover' data-trigger='manual' title=\
'Copy the contents of code editor' data-content='And here's some amazing \
content. It's very engaging. Right?'>Copy plain code</a>"></a>`;
````

**Comment by bugron** [comment]
@abhisekp agreed and fixed, thanks.

**Comment by abhisekp** [comment]
@bugron 
- Add an item to popover that allows to copy the link of the soln. 
- When selecting and dragging the mouse and the mouse moves beyond the pg, the popup shows partially. It goes beyond the pg. it should stay within the editor area. This issue occurs both while drag selection and `CTRL+A` selection.
> [](http://i.imgur.com/hntrLZF.png)
> [](http://i.imgur.com/e8L5m2F.png)

**Comment by abhisekp** [comment]
@bugron 3 Items
- Copy as Link
- Copy as Pretty Code
- Copy as Plain Code

Beginners don't know what "markdown" is. :dart:

**Comment by bugron** [comment]
@abhisekp I've implemented all your suggestions. Now the tool-tip looks like this:

Also now I'm checking if the cursor is inside the code editor. If not the tool-tip will appear inside the code editor. If cursor is inside then it will appear near the cursor.

**Pull request merged**
