### PR TITLE
Update 2 of the new js curriculum!

### PR DESCRIPTION
**Pull request by benmcmahon100**
7 more challenges added!

### CODE REVIEW

**Comment by LumenTeun** [comment]
Nice! :) But why don't you just add this to your previous pull request? It hasn't been merged yet from what I can see.

**Comment by benmcmahon100** [comment]
Because I'm an idiot an meant to do that! :p

**Comment by benmcmahon100** [comment]
I'll Close this and move all the stuff over tomorrow

**Comment by LumenTeun** [comment]
Haha :P Well, you learn form your mistakes I guess.

**Comment by benmcmahon100** [comment]
Don't commit while tired!

**Pull request merged**
