### PR TITLE
Update README.md

### PR DESCRIPTION
**Pull request by ennzin**
I translated from English to Portuguese

Checklist:

- [x] I have read and followed the [contribution guidelines](https://contribute.freecodecamp.org).
- [x] I have read and followed the [how to open a pull request guide](https://contribute.freecodecamp.org/how-to-open-a-pull-request/).
- [x] My pull request targets the `main` branch of freeCodeCamp.
- [x] I have tested these changes either locally on my machine, or GitPod.

Closes #XXXXX

### CODE REVIEW

**Comment by ennzin** [comment]
isto quer dizer que deu certo? nao entendo, eu traduzi certinho para o portugues

**Comment by ennzin** [comment]
sim, mas para nos brasileiros falcilitaria mto se tivesse um README em portugues tbm, nao tem como deixar um link ou outro assim, alem do ingles

**Comment by DanielRosa74** [comment]
That could be something to check in the future, I believe. In the meantime, please remember that other people read these messages in an attempt to try to help and answer your questions and clarify things to contributors, not only people who understand Portuguese, but people from all over the world. That being the case, please keep messages in English to give the opportunity to others to understand you as well. 😉 Cheers!

**Comment by ennzin** [comment]
oh okay, Here is a version of the README in Portuguese, I wanted to help people who speak Portuguese, and anyone interested in taking a look or arranging something, feel free!!

**Pull request closed without merging**
