### PR TITLE
feat(client): refactor desktop-layout to ts

### PR DESCRIPTION
**Pull request by ShaunSHamilton**
Checklist:

- [x] I have read [freeCodeCamp's contribution guidelines](https://contribute.freecodecamp.org).
- [x] My pull request has a descriptive title (not a vague title like `Update index.md`)
- [x] My pull request targets the `main` branch of freeCodeCamp.
- [x] I have tested these changes either locally on my machine, or GitPod.

Related to #42256

This targets `next`, but should not hold `next` back from being merged to `main`. I started this refactor because I wanted to find the cause of this error on `next`.
```
Warning: Failed prop type: checker is not a function
    in DesktopLayout (created by ShowClassic)
    in ShowClassic (created by withI18nextTranslation(ShowClassic))
    in withI18nextTranslation(ShowClassic) (created by Connect(withI18nextTranslation(ShowClassic)))
    in Connect(withI18nextTranslation(ShowClassic)) (created by PageRenderer)
    in div (created by DefaultLayout)
    in div (created by DefaultLayout)
    in DefaultLayout (created by withI18nextTranslation(DefaultLayout))
```

### CODE REVIEW

**Comment by nhcarrigan** [comment]
Need to update the import in the `Show` file.

**Review by raisedadead — COMMENTED** [review]
We have landed the `next` branch into `main`, and I have rebased and retargeted your pull request. Please make sure to sync with your local before you continue to make any further changes.

If you need assistance with that, let us know in the contributors chat, or here.

**Comment by nhcarrigan** [comment]
image

This change seems to break the breadcrumbs for me.

**Review by naomi-lgbt — DISMISSED** [review]
This looks good to me.

**Review by raisedadead — APPROVED** [review]

**Review by moT01 — APPROVED** [review]
LGTM 🎉

**Pull request merged**
