### PR TITLE
Fix(challenges): code storage/uri

### LINKED ISSUE #9115: After submitting a challenge, remove its code from browser's local storage
Our storage of incomplete code has caused a ton of confusion. Many campers switch browsers or devices, then visit a previously completed challenge only to think that "Free Code Camp has lost my code!"

The reason we store campers' code in a browser is to prevent them from losing this code if their browser crashes. 

- [ ] As a camper, once I submit a solution to a challenge, my stored solution should be removed from my browser's local storage so I next time I view this challenge.

- [ ] As a camper, if I return to a challenge and a partial solution for that challenge is available in my local storage, it should load my partial solution (as it currently does). I should see a flash message that says "We have loaded your partial solution below. Good luck finishing and submitting it."

### LINKED ISSUE #9598: [beta] add message when code uri is present
A message should be shown confirming that code in URI should be run

### LINKED ISSUE #9984: [beta] Submitted solution not present on revisit
When code is submitted, and user goes to solve other problems; and decides to revisit the earlier challenge (from map page or hitting back button), the code in the editor should contain the solution.

However, I didn't find that to be the case.

This is what I am seeing before refresh 
screenshot from 2016-07-29 20 34 47

---

After refreshing the page, it comes back and preview pane also reflects that

screenshot from 2016-07-29 20 34 56

Browser: Google Chrome latest on Linux Mint

### LINKED ISSUE #10052: [beta] Show solutions instead of challenge links on user portfolio
Refers https://github.com/FreeCodeCamp/FreeCodeCamp/pull/10041#issuecomment-236961267

### PR DESCRIPTION
**Pull request by BerkeleyTrue**
Pulls code in this order

If present in uri (i.e. ?solution=function foo() {}). This will locks the challenge as running untrusted code until the user unlocks it manually.

If present in localStorage
- this checks first for the modern version, which uses the challenge id instead of title with 'Val' appended
- then checks for the legacy version,
  - i.e. 'Concat StringsVal', and converts it to the modern version
  - removes the legacy key

If both of the above find nothing, it then looks at the user challengeMap if available and pulls the previous solution.

When a user completes a challenge, the local copy is removed.

closes #9115
closes #9984
closes #9598
closes #10052

### CODE REVIEW

**Comment by alayek** [comment]
@BerkeleyTrue please tag me once you have completed this one and deployed. I will confirm from my end that it is resolved in beta.

**Comment by BerkeleyTrue** [comment]
@alayek Why not confirm from this PR instead?

**Comment by alayek** [comment]
@BerkeleyTrue ok.

**Comment by BerkeleyTrue** [comment]
@alayek This is ready to QA

**Comment by raisedadead** [comment]
@BerkeleyTrue just to confirm to test the use case for:
[`Fix(challenges): load legacy code from localStorage`](https://github.com/FreeCodeCamp/FreeCodeCamp/pull/10200/commits/29ed57e36c0f7d409c36a80819723545fe59e7ee),

I should first solve a couple of challenges on `backup/staging`, then switch to this PR and move forth from there? Right? 

I know a QA should not ask questions to DEV, but you probably are best suited to guide.

**Comment by BerkeleyTrue** [comment]
@raisedadead You can manually change edit your localStorage. Just go to the main site and copy from their.

**Comment by BerkeleyTrue** [comment]
@alayek Are you still QA'ing this?

**Comment by QuincyLarson** [comment]
@BerkeleyTrue QA'd LTGTM!

**Pull request merged**
