### PR TITLE
chore(i18n): update German forum links

### PR DESCRIPTION
**Pull request by Sboonny**
Checklist:

- [x] I have read [freeCodeCamp's contribution guidelines](https://contribute.freecodecamp.org).
- [x] My pull request has a descriptive title (not a vague title like `Update index.md`)
- [x] My pull request targets the `main` branch of freeCodeCamp.
- [x] I have tested these changes either locally on my machine, or GitPod.

### CODE REVIEW

**Review by raisedadead — APPROVED** [review]

**Review by ShaunSHamilton — DISMISSED** [review]
We do not have German on the forum yet.

**Comment by raisedadead** [comment]
> We do not have German on the forum yet.

Tag the PR as blocked instead of a change request, which is misleading?

**Comment by ShaunSHamilton** [comment]
> Tag the PR as blocked instead of a change request, which is misleading?

Will do. I just did not because a label does not prevent the PR from being merged.

**Comment by raisedadead** [comment]
> because a label does not prevent the PR from being merged.

If and when that happens, the maintainer is not paying attention and should not even be merging PRs, in the first place.

**Comment by raisedadead** [comment]
I have created https://forum.freecodecamp.org/c/german - but someone will need to create the actual sub-categories in there.

**Pull request merged**
