### PR TITLE
fix(editor): remove MDN reference tool-tips

### LINKED ISSUE #44735: RWD Beta: Tooltip in the editor should not be displayed
When you mouse over on a HTML tag in the editor, a tooltip will be displayed.
~~But when the tag is near the top of the editor area, the tooltip gets hidden by the header area.~~

## Affected page

Any of the new Responsive Web Design Beta page such as:
https://www.freecodecamp.org/learn/2022/responsive-web-design/learn-html-by-building-a-cat-photo-app/step-2

## To reproduce

1. Go to the link above
2. Mouse over on `<html>` or `<body>` tag in the editor
3. See the tooltip

## Expected behavior

~~The tooltip is not hidden~~ -> Don't show tooltips

## Screenshots

new challenge

## System

- Device: Laptop
- OS: Windows 10
- Browser: Chrome
- Version: 97.0.4692.71

## Additional context

This does not happen in the editor for the existing challenges
existing challenge

### PR DESCRIPTION
**Pull request by Sembauke**
Checklist:

- [x] I have read [freeCodeCamp's contribution guidelines](https://contribute.freecodecamp.org).
- [x] My pull request has a descriptive title (not a vague title like `Update index.md`)
- [x] My pull request targets the `main` branch of freeCodeCamp.
- [x] I have tested these changes either locally on my machine, or GitPod.

Reference on how to disable:
https://github.com/microsoft/vscode-docs/blob/vnext/release-notes/v1_54.md#hovers-in-csslessscss-and-html

Closes #44735

### CODE REVIEW

**Comment by ojeytonwilliams** [comment]
Hi Sem, wasn't the plan to remove them entirely, rather than on update?

**Comment by Sembauke** [comment]
> Hi Sem, wasn't the plan to remove them entirely, rather than on update?

If there is a option to do so, this is also immediate, once the editor is loaded in.

**Comment by ojeytonwilliams** [comment]
Can't we just update these options: https://github.com/freeCodeCamp/freeCodeCamp/blob/c0af99748e28204fa10fcc3a8a6730aaf84d2d79/client/src/templates/Challenges/classic/editor.tsx#L229 ?

**Comment by Sembauke** [comment]
> Can't we just update these options:

My bad! I completely looked over that!

**Review by ojeytonwilliams — APPROVED** [review]
Cheers Sem, I really prefer this quieter editor.  You wouldn't happen to know how to turn this off in VSCode?

**Review by ShaunSHamilton — APPROVED** [review]
😞 I liked the feature...

Oh well. LOTM 👍

**Comment by ojeytonwilliams** [comment]
>  I liked the feature...

I somehow failed to notice your comment to that effect.  Sorry!

@ahmadabdolsaheb conceivably this is something we could A/B test, though it might make the editor look flaky if it shows tooltips one day and then randomly stops.

**Comment by Sembauke** [comment]
> Cheers Sem, I really prefer this quieter editor. You wouldn't happen to know how to turn this off in VSCode?

File > Preferences > Settings, Search for MDN

**Comment by ojeytonwilliams** [comment]
Bliss. Thanks @Sembauke

**Pull request merged**
