### PR TITLE
Code tags don't appear in output anymore

### LINKED ISSUE #14479: Code tags shouldn't be included in console output
Challenge [use-responsive-design-with-bootstrap-fluid-containers](http://beta.freecodecamp.com/en/challenges/bootstrap/use-responsive-design-with-bootstrap-fluid-containers) has an issue.
User Agent is: <code>Mozilla/5.0 (Macintosh; Intel Mac OS X 10_12_3) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/57.0.2987.133 Safari/537.36</code>.
Please describe how to reproduce this issue, and include links to screenshots if possible.

Here's a screenshot:

### PR DESCRIPTION
**Pull request by techstonia**
#### Pre-Submission Checklist

- [x] Your pull request targets the `staging` branch of freeCodeCamp.
- [x] Branch starts with either `fix/`, `feature/`, or `translate/` (e.g. `fix/signin-issue`)
- [x] You have only one commit (if not, [squash](http://forum.freecodecamp.com/t/how-to-squash-multiple-commits-into-one-with-git/13231) them into one commit).
- [x] All new and existing tests pass the command `npm test`. Use `git commit --amend` to amend any fixes.

#### Type of Change

- [x] Small bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds new functionality)
- [ ] Breaking change (fix or feature that would change existing functionality)
- [ ] Add new translation (feature adding new translations)

#### Checklist:

- [x] Tested changes locally.
- [x] Closes currently open issue (replace XXXX with an issue no): Closes #14479

#### Description

The solution was to make the regex lazy i.e. matching as little as possible. I also changed matching to global so that it would match more than one time.

### CODE REVIEW

**Comment by lynxlynxlynx** [comment]
LGTM. Both changes are needed for the corner case in question. A simpler regex could be used, but this way the change is minimal.

**Review by BerkeleyTrue — APPROVED** [review]
Code LGTM

**Comment by techstonia** [comment]
Thanks!

**Comment by dhcodes** [comment]
Tested locally and **LGTM**. Thanks @techstonia . Keep up the good work! 👍 💯 🌮

**Pull request merged**
