### PR TITLE
optional whitespaces around '-' symbol

### LINKED ISSUE #2597: Spaces are considered to validate the chalenge
Challenge http://freecodecamp.com/challenges/waypoint-give-your-javascript-slot-machine-some-stylish-images has an issue. Please describe how to reproduce it, and include links to screenshots if possible.

It is considering spaces to validate code in:

```javascript
 $($('.slot')[0]).html('<img src = "' + images[slotOne-1] + '">');
    $($('.slot')[1]).html('<img src = "' + images[slotTwo-1] + '">');
    $($('.slot')[2]).html('<img src = "' + images[slotThree-1] + '">');
```
is validated, but the code below with spaces in `slotOne - 1` for example do not validate

```javascript
 $($('.slot')[0]).html('<img src = "' + images[slotOne - 1] + '">');
    $($('.slot')[1]).html('<img src = "' + images[slotTwo - 1] + '">');
    $($('.slot')[2]).html('<img src = "' + images[slotThree - 1] + '">');
```

### PR DESCRIPTION
**Pull request by bugron**
Closes #2597.

### CODE REVIEW

**Comment by bugron** [comment]
Branch is rebased and conflicts are resolved.

**Comment by BerkeleyTrue** [comment]
@bugron I cannot verify that this works. Seems to not fix the issue.

**Comment by BerkeleyTrue** [comment]
@ahstro Can you verify if this works for you?

**Comment by bugron** [comment]
@BerkeleyTrue I've just added `\\s*?` in `images\\[\\w+\\-1\\]` so now it looks like this: `images\\[\\w+\\s*?\\-\\s*?1\\]`. I don't know what's the problem but before this change I was unable to pass the first test with this code for example:
```javascript
$($('.slot')[0]).html('<img src = "' + images[slotOne - 1] + '">');
$($('.slot')[1]).html('<img src = "' + images[slotTwo - 1] + '">');
$($('.slot')[2]).html('<img src = "' + images[slotThree - 1] + '">');
```
Notice the spaces in `images[slotOne - 1]`, `images[slotTwo - 1]` and `images[slotThree - 1]`.

**Comment by BerkeleyTrue** [comment]
I was unable to pass your tests with that code.

**Comment by ahstro** [comment]
@bugron @BerkeleyTrue Isn't that code unable to pass because this challenge is still strict about using double quotes re: #3069?

**Comment by bugron** [comment]
@ahstro That is already fixed by @natac13: `(?:'|\")`. This PR is about spaces around `-` sign.

**Comment by ahstro** [comment]
@bugron Okay, didn't know that that was merged, thought maybe that was why @BerkeleyTrue was having trouble with the above code.

**Comment by QuincyLarson** [comment]
It sounds like this PR doesn't address the issue at hand. I'm going to close it as part of cleaning up the outstanding pull requests. @ahstro Please open a new pull request when you've fixed the issue. Thanks for your help.

**Pull request closed without merging**
