### PR TITLE
fix(curriculum): improve instruction for binary search algorithm

### LINKED ISSUE #48872: Fix typo and improve instruction.
### Describe the Issue

The current explanation for the description of a binary Search is:
```
    Find the middle value of a sorted array. If value == target return (found it!).
    If middle value < target, search right half of array in next compare.
    If middle value > target, search left half of array in next compare.
```
Maybe for the top line we could rephrase the (found it!) part so people don't confuse this part with the coding challenge, also we could make it clearer with something more generic "return `true`. (The value has been found)."
I think we could also include the base case for when a value is not present in the given array, for example "return `false` (The value is not present in the array").

Also in the instruction there's a line:

```If value not is found, ``` 
Which should be:
```If the value is not found```

I'm happy to work on it: I'll submit a PR  linked to this issue. 🙂

### Affected Page

https://www.freecodecamp.org/learn/coding-interview-prep/algorithms/implement-binary-search

### Your code

Issue noted above

### Expected behavior

Remove typo and improve clarity of instructions

### Screenshots

_No response_

### System

Not a system error

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by marktlinn**
fixed typo and improved the general working of the description section to make it clearer precisely how the search works
added: 4th case for the description to clarify the process if value is not in array. Also, fixed a typo on lines 23-24 which was missing a word.

Checklist:

- [x] I have read [freeCodeCamp's contribution guidelines](https://contribute.freecodecamp.org).
- [x] My pull request has a descriptive title (not a vague title like `Update index.md`)
- [x] My pull request targets the `main` branch of freeCodeCamp.
- [x] I have tested these changes either locally on my machine, or GitPod.

Closes #48872

### CODE REVIEW

**Comment by raisedadead** [comment]
As a new contributor, we encourage you to read our [contributing guidelines](https://contribute.freecodecamp.org).

We expect our contributors to be aware of the process specific to this project. Following the guidelines religiously earns you the respect of fellow maintainers and saves everyone time.

Some examples of this are:

1. Do not edit files directly through GitHub – while you can, it's not a good idea.
2. Make sure you follow the PR checklist and not just tick things off; otherwise, we won't take you seriously.
3. Use the correct way to link issues in the description of the PR by updating the `XXXXXX`. Do not just add issue numbers everywhere and anywhere you feel like.
4. Keep mentions and review requests to a minimum. We understand you are excited about contributing, and our maintainers will get back to you as soon as they get a chance.
5. Do not work directly off your `main` branch - create a new branch for the changes you are working on.

We appreciate you taking the time to help us, and we hope to see more contributions from you.

Happy Contributing.

**Comment by Sboonny** [comment]
@marksist300, your current PRs are blocked, because they don't follow our naming standard, if you are still willing to fix the issue, follow them and ping me to start the reviewing process.

**Comment by marksist300** [comment]
> @marksist300, your current PRs are blocked, because they don't follow our naming standard, if you are still willing to fix the issue, follow them and ping me to start the reviewing process.

Yep, happy to fix them, I've read through your guidelines and tried to follow the standards of the conventional titles preferred. What would you like me to include or how would you like me to change the title?

**Comment by marksist300** [comment]
update title

**Comment by Sboonny** [comment]
https://contribute.freecodecamp.org/#/how-to-open-a-pull-request?id=prepare-a-good-pr-title

in this section, you will find good examples, and the scope is in the PR tags. Here are examples of pr titles.

- fix(a11y): improved search bar contrast
- feat: add more tests to HTML and CSS challenges
- fix(api,client): prevent CORS errors on form submission
- docs(i18n): fix links to be relative instead of absolute

---

- You don't need capitalization of the first latter in the title. 
- You don't include the issue number in the PR (already sorted).
- You need to have the right syntax `<type>([optional scope(s)]): <description>`.

**Comment by marksist300** [comment]
Ok, many thanks, I think the title accords with the given description now.

**Review by Sboonny — APPROVED** [review]
#### :sparkles: :tada: **AWESOME!** :tada: :sparkles:

 Hi @marksist300, thanks for this pull request and for contributing to the code-base for the first time. We are looking forward to more contributions from you in the future.

 Cheers & happy contributing!

**Comment by marksist300** [comment]
Thank you 🙂

**Review by raisedadead — APPROVED** [review]

**Pull request merged**
