### PR TITLE
refactor(client): replace Bootstrap button component on settings page

### PR DESCRIPTION
**Pull request by huyenltnguyen**
Checklist:

- [x] I have read and followed the [contribution guidelines](https://contribute.freecodecamp.org).
- [x] I have read and followed the [how to open a pull request guide](https://contribute.freecodecamp.org/#/how-to-open-a-pull-request).
- [x] My pull request targets the `main` branch of freeCodeCamp.
- [x] I have tested these changes either locally on my machine, or GitPod.

This PR
- Replaces Bootstrap button component with `ui-components`'s Button
- Partially addresses #52092

## Affected areas and steps to test

<details>
  <summary>Details with screenshots</summary>

| Affected area | Steps to test | Screenshot |
| --- | --- | --- |
| Inline login CTA | - Sign out and go to the landing page <br /> - Check the sign in button in the navigation | Screenshot 2023-12-13 at 09 38 11 |
| Block login CTA | - Sign out and go to the landing page <br /> - Check the "Get started (it's free)" button | Screenshot 2023-12-13 at 09 42 14 |
| Update button on /update-email | - Go to /update-email <br /> - Check the update button | Screenshot 2023-12-13 at 14 56 36 |
| "Personal Information" section on Settings page | - Go to /settings <br>  - Scroll down to the "Personal Information" section - Check the save button | Screenshot 2023-12-13 at 15 31 44 |
| "Privacy Settings" section on Settings page | - Go to /settings <br> - Scroll down to the "Privacy Settings" section <br> - Check the save and the download data buttons | Screenshot 2023-12-13 at 16 53 02 |
| "Email Settings" section on Settings page - save button | - Go to /settings <br> - Scroll down to the "Email Settings" section <br> - Check the save button | Screenshot 2023-12-13 at 16 07 15 |
| "Email settings" section on Settings page - edit button | - Flip the rendering logic of the edit button ([link to the code](https://github.com/freeCodeCamp/freeCodeCamp/blob/575aa172ad2c4db55a02a42ebf5206a1e6759ac8/client/src/components/settings/email.tsx#L146)) - Go to /settings <br> - Scroll down to the "Email Settings" section <br> - Check the edit button | Screenshot 2023-12-13 at 16 10 50 |
| "Your Internet Presence" section on Settings page | - Go to /settings <br> - Scroll down to the "Your Internet Presence" section <br> - Check the save button | Screenshot 2023-12-13 at 16 27 20 |
| "Portfolio Settings" section on Settings page - add item button | - Go to /settings <br> - Scroll down to the "Portfolio Settings" section <br> - Check the add item button | Screenshot 2023-12-13 at 16 29 42 |
| "Portfolio Settings" section on Settings page - save and remove item buttons | - Go to /settings <br> - Scroll down to the "Portfolio Settings" section <br> - Click the "Add a new portfolio item" button - Check the save and remove item buttons | Screenshot 2023-12-13 at 16 39 00 |
| "Academic Honesty Policy" section on Settings page | - Go to /settings <br> - Scroll down to the "Academic Honesty Policy" section <br> - Check the accept button | Screenshot 2023-12-13 at 16 24 35 |
| "Certification" section on Settings page - show cert | - Go to /settings <br> - Scroll down to the "Certifications" section <br> - Check the "Show Certification" buttons | Screenshot 2023-12-13 at 15 54 09 |
| "Certification" section on Settings page - claim cert | - Seed the DB with `isFullStackCert` being false <br> - Go to /settings <br> - Scroll down to the "Legacy Full Stack Certification" section <br> - Check the "Claim Certification" button | Screenshot 2023-12-13 at 15 54 29 |
| "Danger zone" section on Settings page - delete and reset buttons  |  - Go to /settings <br> - Scroll all the way down to the "Danger zone" section <br> - Check the buttons in the section | Screenshot 2023-12-13 at 15 59 40 |
| "Danger zone" section on Settings page - delete modal  |  - Go to /settings <br> - Scroll all the way down to the "Danger zone" section <br> - Click "Delete my account" <br> - Check the buttons in the modal | Screenshot 2023-12-13 at 16 02 29 |
| "Danger zone" section on Settings page - reset modal  |  - Go to /settings <br> - Scroll all the way down to the "Danger zone" section <br> - Click "Reset all of my progress" <br> - Check the buttons in the modal | Screenshot 2023-12-13 at 16 03 43 |

</details>

### CODE REVIEW

**Review by huyenltnguyen — COMMENTED** [review]
This PR is blocked by Cypress test failure, and I can't fix them for the life of me.

I'll create an issue for the Cypress removal and start cleaning up / migrating those that are blocking this PR.

**Comment by Sembauke** [comment]
Seems that aria-label would still be there after the button was disabled. This was not the case for the Button component:

image

**Review by ahmaxed — APPROVED** [review]

**Review by Sembauke — APPROVED** [review]

**Comment by Sembauke** [comment]
May Cypress die peacefully

**Comment by Sembauke** [comment]
Thank you for all your hard work Huyen!

**Pull request merged**
