### PR TITLE
Fixed a couple errors (i.e. print() --> printf())

### LINKED ISSUE #35141: Typo with print(): Should be printf() instead of print()
**Describe your problem and how to reproduce it:**
In the Hello World example in guide, there is a typo when explaining the stdio library. Instead of print(), it should be printf().

**Add a Link to the page with the problem:**
https://github.com/freeCodeCamp/freeCodeCamp/blob/master/guide/english/c/hello-world/index.md

**Tell us about your browser and operating system:**
* Browser Name: Google Chrome
* Browser Version: 71.0.3578.98
* Operating System: MacOS Mojave 10.14.3

**If possible, add a screenshot here (you can drag and drop, png, jpg, gif, etc. in this box):**

screen shot 2019-02-11 at 1 24 20 am

### PR DESCRIPTION
**Pull request by cindydhy**
- [x] I have read [freeCodeCamp's contribution guidelines](https://github.com/freeCodeCamp/freeCodeCamp/blob/master/CONTRIBUTING.md).
- [x] My pull request has a descriptive title (not a vague title like `Update index.md`)
- [x] My pull request targets the `master` branch of freeCodeCamp.
- [x] None of my changes are plagiarized from another source without proper attribution.
- [x] All the files I changed are in the same world language (for example: only English changes, or only Chinese changes, etc.)
- [x] My changes do not use shortened URLs or affiliate links.

Closes #35141

### CODE REVIEW

**Review by theNaut1lus — CHANGES_REQUESTED** [review]
Please add issue number which this commit will fix in the pull request you have created.

**Comment by RandellDawson** [comment]
@co16353sidak Does this PR actually close an issue?  If so, which one?

**Comment by co16353sidak** [comment]
This will fix #35141 @cindydhy has added it.

**Comment by RandellDawson** [comment]
@cindydhy When you see typos like this, you can just create a PR instead of creating an issue first.  The only time we prefer you to create an issue first is to report a problem with the way something works (i.e a challenge test or the way the site displays oddly), so we can discuss and confirm the issue appears across multiple users.

**Comment by moT01** [comment]
Thanks for the PR @cindydhy, but this has been fixed from a PR that was created before this and not merged until after this was created (we merge from oldest first). In the future, you should create a branch to make changes on, and not make changes directly to the master branch. This is described [here](https://github.com/freeCodeCamp/freeCodeCamp/blob/master/docs/how-to-setup-freecodecamp-locally.md) in the `Making changes to your clone of freeCodeCamp locally` section. We welcome future PR's from you - thanks and happy coding!

**Pull request closed without merging**
