### PR TITLE
feat: group cypress deps in renovate config

### PR DESCRIPTION
**Pull request by moT01**
Checklist:

- [x] I have read [freeCodeCamp's contribution guidelines](https://contribute.freecodecamp.org).
- [x] My pull request has a descriptive title (not a vague title like `Update index.md`)
- [x] My pull request targets the `main` branch of freeCodeCamp.
- [ ] I have tested these changes either locally on my machine, or GitPod.

Closes #XXXXX

### CODE REVIEW

**Comment by moT01** [comment]
Want to take a look at this @ojeytonwilliams - I think it looks right.

**Review by raisedadead — COMMENTED** [review]
Do we use anything else from the testing library? If we do, are we likely to break something?

**Review by naomi-lgbt — APPROVED** [review]
This should be good yeah

**Comment by nhcarrigan** [comment]
> Do we use anything else from the testing library? If we do, are we likely to break something?

We do, but I'm pretty sure they're fairly decoupled.

**Review by raisedadead — APPROVED** [review]

**Pull request merged**
