### PR TITLE
chore(LoopBack): Upgrade to LoopBack 3

### LINKED ISSUE #12780: [build] Update loopback components and migrations for gulp warnings in build.
As of today, there is a verbose error in the gulp log as below:
```
The user model "User" is attached to an application that does not specify
whether other sessions should be invalidated when a password or
an email has changed. Session invalidation is important for security
reasons as it allows users to recover from various account breach
situations.

We recommend turning this feature on by setting
"logoutSessionsOnSensitiveChanges" to true in
server/config.json (unless you have implemented your own solution
for token invalidation).

We also recommend enabling "injectOptionsFromRemoteContext" in
User's settings (typically via common/models/*.json file).
This setting is required for the invalidation algorithm to keep 
the current session valid.


The user model "user" is attached to an application that does not specify
whether other sessions should be invalidated when a password or
an email has changed. Session invalidation is important for security
reasons as it allows users to recover from various account breach
situations.

We recommend turning this feature on by setting
"logoutSessionsOnSensitiveChanges" to true in
server/config.json (unless you have implemented your own solution
for token invalidation).

We also recommend enabling "injectOptionsFromRemoteContext" in
user's settings (typically via common/models/*.json file).
This setting is required for the invalidation algorithm to keep 
the current session valid.
```

### PR DESCRIPTION
**Pull request by raisedadead**
This upgrades LoopBack to v3.x.x

- [x] Update LoopBack version
- [x] Update use of REST error handler
- [x] Replace LoopBack middleware “getter” properties 
- [ ] Update models
- [x] Update models derived from PersistedModel
- [x] Explicitly add User model properties that were removed
- [ ] Remove use of `current-context` methods, middleware, and configuration settings
  - This throws an error, please see the linked gist below for details. 
- [ ] Check request parameter encoding
- [ ] Update use of promises
- [x] Check CORS configuration

More details of the checklist with some error stack are available here:
https://gist.github.com/raisedadead/22f7a38bb47204fded9b0877fde954ef

Closes #12780

### CODE REVIEW

**Comment by systimotic** [comment]
@raisedadead Is this still blocked?

**Comment by raisedadead** [comment]
Hi @systimotic I was away for a bit, I could still continue, but looks like this is closed. I'll let @BerkeleyTrue confirm if there are other plans before I continue.

Cheers.

**Comment by systimotic** [comment]
@raisedadead 👍 No worries. I'm pretty sure this was closed as stale, as a part of [the massive cleanup](https://forum.freecodecamp.org/t/cleaning-up-github-issues-and-pull-requests/145317). If you want to update this / get it reviewed, I think you're free to reopen it.

**Comment by raisedadead** [comment]
Sure, I just got whats going on... lol. Thanks for the link. I'll make a fresh pull request (I have to update the code anyways) because we need this upgrade

**Comment by systimotic** [comment]
@raisedadead Awesome!

**Pull request closed without merging**
