### PR TITLE
added BigInt as data type

### PR DESCRIPTION
**Pull request by theprakashkumar**
Checklist:

- [x] I have read [freeCodeCamp's contribution guidelines](https://contribute.freecodecamp.org).
- [x] My pull request has a descriptive title (not a vague title like `Update index.md`)
- [x] My pull request targets the `master` branch of freeCodeCamp.
- [x] All the files I changed are in the same world language, for example: only English changes, or only Chinese changes, etc.

Closes #XXXXX

### CODE REVIEW

**Comment by ThePrakashKumar** [comment]
What is happening to this PR?

**Comment by ThePrakashKumar** [comment]
I accidentally deleted this PR, what to do now? The reopen button is disabled in my case.

**Comment by Sky020** [comment]
> I accidentally deleted this PR, what to do now? The reopen button is disabled in my case.

It appears you have deleted your fork of the repo, not just the PR. So, you will have to re-fork the repo, then _maybe_ you can merge the last commit of this branch with a new branch. You will need to be able to find this branch hash, though, which I do not think exists.

Simplest thing to do is open a new PR.

**Comment by Sky020** [comment]
> I accidentally deleted this PR, what to do now? The reopen button is disabled in my case.

It appears you have deleted your fork of the repo, not just the PR. So, you will have to re-fork the repo, then _maybe_ you can merge the last commit of this branch with a new branch. You will need to be able to find this branch hash, though, which I do not think exists.

Simplest thing to do is open a new PR.

**Pull request closed without merging**
