### PR TITLE
fix: Added Change this line comment in Redux Challenge

### LINKED ISSUE #40489: Remove the change code below/above line instructions for Redux challenge:Use const for Action Types
**Describe your problem and how to reproduce it:**
Hi there! 
This challenge asks users to declare two variables with const and then edit the `authReducer()` function and action creators. 
The `//change code below/above line` instructions imply that your code should only be between those two lines. 
However, in order to pass the challenge, you have to edit the code below the `// Change code above this line`.
I think it would be best to remove those comments. 

Thanks! 

**Add a Link to the page with the problem:**
https://www.freecodecamp.org/learn/front-end-libraries/redux/use-const-for-action-types

**Tell us about your browser and operating system:**
* Browser Name: 
* Browser Version: 
* Operating System: 

**If possible, add a screenshot here (you can drag and drop, png, jpg, gif, etc. in this box):**
Screen Shot 2020-12-18 at 4 34 39 PM

### PR DESCRIPTION
**Pull request by NirajNair**
Checklist:

- [X] I have read [freeCodeCamp's contribution guidelines](https://contribute.freecodecamp.org).
- [X] My pull request has a descriptive title (not a vague title like `Update index.md`)
- [X] My pull request targets the `master` branch of freeCodeCamp.
- [X] All the files I changed are in the same world language, for example: only English changes, or only Chinese changes, etc.

Closes #40489

### CODE REVIEW

**Review by ShaunSHamilton — APPROVED** [review]
This LGTM 👍 

Congratulations on your first PR to this repo! We look forward to your future contribution

**Review by naomi-lgbt — APPROVED** [review]
LGTM~! 🥳 

Congratulations on your first pull request to this project! We look forward to future contributions!

Please note that we are in a code freeze at the moment, so merging this will wait until that is lifted. 🙂

**Comment by NirajNair** [comment]
> This LGTM 👍
> 
> Congratulations on your first PR to this repo! We look forward to your future contribution

Thank you so much!

**Comment by NirajNair** [comment]
> LGTM~! 🥳
> 
> Congratulations on your first pull request to this project! We look forward to future contributions!
> 
> Please note that we are in a code freeze at the moment, so merging this will wait until that is lifted. 🙂

Thank you so much!

**Comment by RohiniMallem** [comment]
Hi freecodecamp/Freecodecamp

Thank you for showing path 😅

**Comment by RandellDawson** [comment]
Congrats @NirajNair on your first pull request (PR)! 🎉

Thank you for your contribution to the page! 👍
We're happy to accept these changes, and look forward to future contributions. 📝

**Pull request merged**
