### PR TITLE
fix typo in mock-guide/english/accessibility/index.md

### PR DESCRIPTION
**Pull request by iamrajiv**
- [x] I have read [freeCodeCamp's contribution guidelines](https://github.com/freeCodeCamp/freeCodeCamp/blob/master/CONTRIBUTING.md).
- [x] My pull request has a descriptive title (not a vague title like `Update index.md`)
- [x] My pull request targets the `master` branch of freeCodeCamp.
- [x] None of my changes are plagiarized from another source without proper attribution.
- [x] All the files I changed are in the same world language (for example: only English changes, or only Chinese changes, etc.)
- [x] My changes do not use shortened URLs or affiliate links.

### CODE REVIEW

**Comment by RandellDawson** [comment]
@iamrajiv The mock-quide contents are never shown to the public.  It is strictly used to create a smaller version of the Guide when developing locally for testing purposes.  We can merge this one PR, but don't worry about creating further changes to anything in the mock-guide.  Thanks for understanding.

**Review by RandellDawson — APPROVED** [review]
LGTM

**Comment by RandellDawson** [comment]
Thank you for your contribution to the page! 👍
We're happy to accept these changes, and look forward to future contributions. 🎉

**Comment by iamrajiv** [comment]
> @iamrajiv The mock-quide contents are never shown to the public. It is strictly used to create a smaller version of the Guide when developing locally for testing purposes. We can merge this one PR, but don't worry about creating further changes to anything in the mock-guide. Thanks for understanding.

yup, I got it I did not know earlier thanks for guidance @RandellDawson

**Pull request merged**
