### PR TITLE
feat(client): remove the Media component for our Card component

### LINKED ISSUE #49277: Change the Media component to our news card component
After discussing the media component and how it looks in the profile section, Ahmad request to change it to our Card component similar to how new display it

Small mobile view

image

wide view (apply to tablet and wide screens)

image

It should have similar style, but without tags and date 🤔

### PR DESCRIPTION
**Pull request by Sboonny**
Checklist:

- [x] I have read and followed the [contribution guidelines](https://contribute.freecodecamp.org).
- [x] I have read and followed the [how to open a pull request guide](https://contribute.freecodecamp.org/#/how-to-open-a-pull-request).
- [x] My pull request targets the `main` branch of freeCodeCamp.
- [x] I have tested these changes either locally on my machine, or GitPod.

Closes #49277
Clear the confusing alt described in this issue #49144

### CODE REVIEW

**Comment by bbsmooth** [comment]
Hey @Sbooney, nice job on making the link spread over the entire card. That is exactly how you create a clickable card accessibly. I do think we should make a few changes to the underlying HTML though.

- I think the `h3` should be the first element in the card. I know we are doing an empty `alt` attribute (at least for now), so screen reader users won't even be aware of the image, but semantically, the image is content for the card and thus it should probably come after the heading. Feel free to use CSS to reorder the heading and image for mobile view (this is one of those instances where it is OK to do that).

- We should wrap the `a` element around the heading text (it would be nested inside of the `h3`) instead of creating a separate link with sr-only text. I think we have some potential confusion of having a link with only sr-only text for people who use a screen reader and can see the page (not everyone who uses a screen reader is blind). Besides, the heading text already provides the perfect text for the link so we can do away with some duplication.

I also think we might want to put some sort of border around each card just to make it a little clearer that it is a card that can be clicked on anywhere to go to the project.

**Review by naomi-lgbt — APPROVED** [review]
image

This is super cool.

**Comment by bbsmooth** [comment]
Agreed, definitely like the looks of this. But I found a few things that we might want to touch up.

fcc-profile-card

- Can the `h3` take up all available inline space?
- If the `h3` is long enough to line wrap then the keyboard focus indicator does not look very good.
- The description text is being cut-off arbitrarily in the middle of a word.

**Comment by Sboonny** [comment]
chrome has a different way of setting the outline than FireFox 🤣

**Comment by Sboonny** [comment]
The new look in mobile

image

in desktop 

image

**Comment by Sboonny** [comment]
nope, go ahead 👍

**Comment by bbsmooth** [comment]
If we are not going to use the `h3` as a link and instead have a separate link to open the item, then the link text will need to be more specific. Perhaps something like "Open item [title of item]" where the text in the brackets is sr-only text. I'm just not sure "Follow link [title of item]" makes as much sense? Regardless, however you want to word it, but the title of the portfolio item should be at the end of the link text as sr-only text.

**Comment by Sembauke** [comment]
@Sboonny Feel free to fix it.

**Review by Sembauke — APPROVED** [review]

**Comment by Sembauke** [comment]
Thanks for making this, I like collaborating with you :)

**Pull request merged**
