### PR TITLE
fix(curriculum): remove semicolon from iteration example

### LINKED ISSUE #56838: Remove semicolon from iteration example to avoid confusion.
This page: https://www.freecodecamp.org/learn/javascript-algorithms-and-data-structures-v8/learn-introductory-javascript-by-building-a-pyramid-generator/step-36
Has the example `bees = bees + 3;` This creates confusion and sometimes people add the semicolon at the end of the iteration statement in a for loop.

Solution: remove the semicolon.

### PR DESCRIPTION
**Pull request by shashanknayak12**
Checklist:

- [x] I have read and followed the [contribution guidelines](https://contribute.freecodecamp.org).
- [x] I have read and followed the [how to open a pull request guide](https://contribute.freecodecamp.org/how-to-open-a-pull-request/).
- [x] My pull request targets the `main` branch of freeCodeCamp.
- [x] I have tested these changes either locally on my machine, or GitPod.

Closes #56838

### CODE REVIEW

**Comment by ilenia-magoni** [comment]
You don't need to open a new PR to solve feedback, you can always update the existing PR, please keep it in mind for future contributions

**Review by majestic-owl448 — CHANGES_REQUESTED** [review]
You are still missing a scope in the title, can you add that please?

**Review by majestic-owl448 — APPROVED** [review]
LGTM 👍

**Review by gikf — APPROVED** [review]

**Comment by gikf** [comment]
Hi @shashanknayak12. Congrats on your first pull request (PR)! 🎉

Thank you for your contribution to the page! 👍
We are happy to accept these changes and look forward to future contributions. 📝

**Pull request merged**
