### PR TITLE
i18n: adding motivational quotes and compliments in Portuguese

### PR DESCRIPTION
**Pull request by DanielRosa74**
Checklist:

- [X] I have read [freeCodeCamp's contribution guidelines](https://contribute.freecodecamp.org).
- [X] My pull request has a descriptive title (not a vague title like `Update index.md`)
- [X] My pull request targets the `main` branch of freeCodeCamp.
- [X] I have tested these changes either locally on my machine, or GitPod.

Adding motivational quotes and compliments to Brazilian Portuguese

### CODE REVIEW

**Comment by nhcarrigan** [comment]
Heya Daniel!

Thanks for all the efforts you've been making in our internationalisation goals. Before merging this, are you able to confirm that the quotes make sense in Portuguese? I believe specifically for the quotes and compliments, we are allowing each language to curate their own list which fits that language culturally/idiomatically.

**Comment by DanielRosa74** [comment]
> Heya Daniel!
> 
> Thanks for all the efforts you've been making in our internationalisation goals. Before merging this, are you able to confirm that the quotes make sense in Portuguese? I believe specifically for the quotes and compliments, we are allowing each language to curate their own list which fits that language culturally/idiomatically.
Hey @nhcarrigan . They do, don't worry. The quotes are taken from known authors and I tried to make the compliments understandable to the language. There are some related to Pokemon, Star Trek, Harry Potter, HIMYM and others which are gonna ring a bell to the Brazilian audience as well. Don't worry. I believe I just removed some baseball-related stuff (not a very popular sport around here) and adapted the rest the best I could.

**Review by naomi-lgbt — APPROVED** [review]
Looks good to me then!

**Review by majestic-owl448 — APPROVED** [review]
LGTM 👍

**Pull request merged**
