### PR TITLE
Fixed bootstrap link

### PR DESCRIPTION
**Pull request by lalov1**
- [ x] I have read [freeCodeCamp's contribution guidelines](https://github.com/freeCodeCamp/freeCodeCamp/blob/master/CONTRIBUTING.md).
- [ x] My pull request has a descriptive title (not a vague title like `Update index.md`)
- [ x] My pull request targets the `master` branch of freeCodeCamp.
- [ x] None of my changes are plagiarized from another source without proper attribution.
- [ x] My article does not contain shortened URLs or affiliate links.

If your pull request closes a GitHub issue, replace the XXXXX below with the issue number.

Closes #XXXXX

### CODE REVIEW

**Review by CodingSolo — COMMENTED** [review]
Thanks, but the changes you have made does not improve the article and the bootstrap link is not broken

**Comment by lalov1** [comment]
@CodingSolo The link is actually broken. Did you check the link?
https://guide.freecodecamp.org/react-native/styling/

It is linking to the markdown file which works on development because it is a markdown file, but on production it doesn't. I thought fixing something such as a broken link improves the article.

**Comment by CodingSolo** [comment]
@lalov1 yes, the link is broken in production. your change must be ok. Probably you could use just /bootstrap, but I can test it

**Comment by scissorsneedfoodtoo** [comment]
@lalov1, everything LGTM! And I believe that you're right about the link, though it's hard to test without local development working at the moment. Anyway, thank you for your contribution, and we're looking forward to the next :+1: :+1:

**Pull request merged**
