### PR TITLE
Fixed typos on two video challenge pages

### PR DESCRIPTION
**Pull request by erichartline**
I noticed some typos and capitalization errors on two of the Computer Basics video challenge pages, specifically Binary Bytes and Measuring Data Speed. I believe there were 13 changes in total.

I plan on going through the other pages and fixing typos, too, if I see any more, but I wanted to submit this first to make sure my first pull request works.

### CODE REVIEW

**Comment by ltegman** [comment]
Perfectly formatted PR! :+1: Thanks for the fixes!

**Comment by wildlifehexagon** [comment]
Awesome, glad it worked! How long does it usually take for the changes to show up on the FCC website?

**Comment by bugron** [comment]
@wildlifehexagon usually a day or two.

**Comment by wildlifehexagon** [comment]
@bugron Cool, thanks for the info

**Pull request merged**
