### PR TITLE
fix: resolve paypal subscription error

### PR DESCRIPTION
**Pull request by ahmaxed**
Update paypal subscription script to the latest api requirements. 
https://developer.paypal.com/docs/business/javascript-sdk/javascript-sdk-reference/#createsubscription

### CODE REVIEW

**Comment by ojeytonwilliams** [comment]
Hey Ahmad, are there tests we could add to check if this problem is solved?  It would be nice to get automatic notifications whenever PayPal makes breaking changes to their api.

**Comment by ahmadabdolsaheb** [comment]
The Paypal script is only erroring out, only was logs to the console about an update.

To my understanding the requirement has recently been added to their docs, and it is not required by he api yet.

**Comment by raisedadead** [comment]
> it is not required by he api yet.

So the current change is to supress the logs only? If yes, that looks a bit unpleasant.

**Comment by ahmadabdolsaheb** [comment]
No it is a new requirement that has not been reinforced by PayPal yet.

**Comment by ojeytonwilliams** [comment]
Thanks Ahmad, that makes sense now.  Are there queries that will cause this to error out?  i.e. if we used `&vault=gibberish&intent=subversion` would that do something that's caught by our tests?  It would be nice we could engineer them to warn us about bad query strings.

**Comment by ahmadabdolsaheb** [comment]
@ojeytonwilliams that is the path moving forward. Since we cannot consistently test the outcome of our scripts on a third party service (paypal modal), the best way to test such cases would be to test the information that we are giving to these services. 

For this instance, a test to check if we are supplying the proper url parameters should work; however, if they change their api without our knowledge, I am not sure how we could properly test against that unless a user creates an issue.

**Comment by ojeytonwilliams** [comment]
Okay, that makes sense, thanks Ahmad.  So, for this PR, we just need to verify that the PayPal button still works in the sandbox?

**Pull request merged**
