### PR TITLE
Added note about language degradation

### LINKED ISSUE #9696: Add note about translations degrading to english
cc/ @QuincyLarson

### PR DESCRIPTION
**Pull request by Bouncey**
#### Pre-Submission Checklist

- [x] Your pull request targets the `staging` branch of FreeCodeCamp.
- [x] Branch starts with either `fix/`, `feature/`, or `translate/` (e.g. `fix/signin-issue`)
- [x] You have only one commit (if not, [squash](http://forum.freecodecamp.com/t/how-to-squash-multiple-commits-into-one-with-git/13231) them into one commit).
- [x] All new and existing tests pass the command `npm test`. Use `git commit --amend` to amend any fixes.
#### Type of Change

- [x] Small bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds new functionality)
- [ ] Breaking change (fix or feature that would change existing functionality)
- [ ] Add new translation (feature adding new translations)
#### Checklist:

- [x] Tested changes locally.
- [x] Closes currently open issue (replace XXXX with an issue no): Closes #9696

### CODE REVIEW

**Review by ghost — APPROVED** [review]
#### LGTM :tada:

Thanks again @Bouncey

**Comment by BerkeleyTrue** [comment]
This does not fulfill the requirements of that issue.

**Comment by atjonathan** [comment]
@BerkeleyTrue, the issue wasn't clear, and the only message was https://github.com/FreeCodeCamp/FreeCodeCamp/issues/9696#issuecomment-232135473. It seemed that that was the issue.

**Comment by BerkeleyTrue** [comment]
> the issue wasn't clear

If an issue isn't clear, ask for clarification. Better to wait to know then create a PR unwarranted.

Please do not accept PR's unless there is a clear issue the PR solves.

**Comment by BerkeleyTrue** [comment]
Please undo this commit

**Comment by Bouncey** [comment]
I didn't find the issue unclear, the title asked to:

> Add note about translations degrading to english

Quincy was cc'd and he posted a comment about language degradation. I took that as the note to be added.

**Comment by BerkeleyTrue** [comment]
That note does not state where and under what conditions to post a note about translations.

**Comment by Bouncey** [comment]
Not a problem. #11484 is for the revert of this PR.

**Pull request merged**
