### PR TITLE
feat: advertise mobile app in footer

### LINKED ISSUE #51630: Advertise the freeCodeCamp mobile app for mobile devices.
### Is your feature request related to a problem? Please describe.

It would be nice to Advertise the freeCodeCamp mobile app for mobile users. This will improve their experience. Currently what I am thinking :

1. A pop up:
"It seems you are using a mobile device. Try the freeCodeCamp Moible App." This would be shown once on every block for the available superblocks.

2. Advertising the app in the footer like this:
image

3. A link in the Navbar to a seperate page that links the IOS and Android version. With a paragraph of what is features. 

### Describe the solution you'd like

-

### Describe alternatives you've considered

-

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by hariomgehlot**
Checklist:

- [x ] I have read and followed the [contribution guidelines](https://contribute.freecodecamp.org).
- [ x] I have read and followed the [how to open a pull request guide](https://contribute.freecodecamp.org/#/how-to-open-a-pull-request).
- [ x] My pull request targets the `main` branch of freeCodeCamp.
- [ x] I have tested these changes either locally on my machine, or GitPod.

Closes #51630

### CODE REVIEW

**Comment by Sembauke** [comment]
Hey @hariomgehlot,
This is looking great already but the aspect ratio is a bit of on the images. 

this means that the images look a bit "mushed". 

This might help:
https://stackoverflow.com/questions/12991351/css-force-image-resize-and-keep-aspect-ratio

**Comment by Amit-Morade** [comment]
Can I work on this?

**Comment by hariomgehlot** [comment]
I am working on it @Amit-Morade . But some test cases are failing. If you can help me out. I am new to React.
Fixed all the UI but some test which are unrelated to the problem are failing.

**Comment by hariomgehlot** [comment]
```

A worker process has failed to exit gracefully and has been force exited. This is likely caused by tests leaking due to improper teardown. Try running with --detectOpenHandles to find leaks. Active timers can also cause this, ensure that .unref() was called on them.
Summary of all failing tests
 FAIL  tools/challenge-helper-scripts/utils.test.ts (11.794 s)
  ● Challenge utils helper scripts › createStepFile util › should create next step and return its identifier

    ENOENT: no such file or directory, open 'project/60d35cf3fe32df2ce8e31b03.md'

      27 |   });
      28 |
    > 29 |   fs.writeFileSync(`${projectPath}${challengeId.toString()}.md`, template);
         |      ^
      30 |
      31 |   return challengeId;
      32 | };

      at writeFileSync (tools/challenge-helper-scripts/utils.ts:29:6)
      at Object.<anonymous> (tools/challenge-helper-scripts/utils.test.ts:42:34)

  ● Challenge utils helper scripts › createChallengeFile util › should create the challenge

    ENOENT: no such file or directory, open 'project/hi.md'

      37 |   path = getProjectPath()
      38 | ): void => {
    > 39 |   fs.writeFileSync(`${path}${title}.md`, template);
         |      ^
      40 | };
      41 |
      42 | interface InsertOptions {

      at writeFileSync (tools/challenge-helper-scripts/utils.ts:39:6)
      at Object.<anonymous> (tools/challenge-helper-scripts/utils.test.ts:74:26)

  ● Challenge utils helper scripts › insertStepIntoMeta util › should update the meta with a new file id and name

    ENOENT: no such file or directory, open '_meta/project/meta.json'

      20 |
      21 | function getMetaData(): Meta {
    > 22 |   const metaData = fs.readFileSync(getProjectMetaPath(), 'utf8');
         |                       ^
      23 |   return JSON.parse(metaData) as Meta;
      24 | }
      25 |

      at readFileSync (tools/challenge-helper-scripts/helpers/project-metadata.ts:22:23)
      at insertStepIntoMeta (tools/challenge-helper-scripts/utils.ts:48:35)
      at Object.<anonymous> (tools/challenge-helper-scripts/utils.test.ts:109:25)

  ● Challenge utils helper scripts › updateStepTitles util › should apply meta.challengeOrder to step files

    ENOENT: no such file or directory, open '_meta/project/meta.json'

      20 |
      21 | function getMetaData(): Meta {
    > 22 |   const metaData = fs.readFileSync(getProjectMetaPath(), 'utf8');
         |                       ^
      23 |   return JSON.parse(metaData) as Meta;
      24 | }
      25 |

      at readFileSync (tools/challenge-helper-scripts/helpers/project-metadata.ts:22:23)
      at updateStepTitles (tools/challenge-helper-scripts/utils.ts:74:27)
      at Object.<anonymous> (tools/challenge-helper-scripts/utils.test.ts:172:23)

 FAIL  tools/challenge-helper-scripts/helpers/project-metadata.test.ts
  ● getMetaData helper › should process requested file

    ENOENT: no such file or directory, open 'curriculum/challenges/_meta/mock-project/meta.json'

      20 |
      21 | function getMetaData(): Meta {
    > 22 |   const metaData = fs.readFileSync(getProjectMetaPath(), 'utf8');
         |                       ^
      23 |   return JSON.parse(metaData) as Meta;
      24 | }
      25 |

      at readFileSync (tools/challenge-helper-scripts/helpers/project-metadata.ts:22:23)
      at Object.<anonymous> (tools/challenge-helper-scripts/helpers/project-metadata.test.ts:66:23)

  ● validateMetaData helper › should throw if a stepfile is missing

    expect(received).toThrow(expected)

    Expected substring: "ENOENT: no such file or directory, access 'english/superblock/project/id-2.md'"
    Received message:   "ENOENT: no such file or directory, open '_meta/project/meta.json'"

          20 |
          21 | function getMetaData(): Meta {
        > 22 |   const metaData = fs.readFileSync(getProjectMetaPath(), 'utf8');
             |                       ^
          23 |   return JSON.parse(metaData) as Meta;
          24 | }
          25 |

          at readFileSync (tools/challenge-helper-scripts/helpers/project-metadata.ts:22:23)
          at getMetaData (tools/challenge-helper-scripts/helpers/project-metadata.ts:43:30)
          at tools/challenge-helper-scripts/helpers/project-metadata.test.ts:120:34
          at Object.<anonymous> (node_modules/.pnpm/expect@29.7.0/node_modules/expect/build/toThrowMatchers.js:74:11)
          at Object.throwingMatcher [as toThrow] (node_modules/.pnpm/expect@29.7.0/node_modules/expect/build/index.js:320:21)
          at Object.toThrow (tools/challenge-helper-scripts/helpers/project-metadata.test.ts:120:38)

      118 |     process.env.CALLING_DIR = 'english/superblock/project';
      119 |
    > 120 |     expect(() => validateMetaData()).toThrow(
          |                                      ^
      121 |       "ENOENT: no such file or directory, access 'english/superblock/project/id-2.md'"
      122 |     );
      123 |   });

      at Object.toThrow (tools/challenge-helper-scripts/helpers/project-metadata.test.ts:120:38)

  ● validateMetaData helper › should throw if a step is present in the project, but not the meta

    expect(received).toThrow(expected)

    Expected substring: "File english/superblock/project/id-3.md should be in the meta.json's challengeOrder"
    Received message:   "ENOENT: no such file or directory, open '_meta/project/meta.json'"

          20 |
          21 | function getMetaData(): Meta {
        > 22 |   const metaData = fs.readFileSync(getProjectMetaPath(), 'utf8');
             |                       ^
          23 |   return JSON.parse(metaData) as Meta;
          24 | }
          25 |

          at readFileSync (tools/challenge-helper-scripts/helpers/project-metadata.ts:22:23)
          at getMetaData (tools/challenge-helper-scripts/helpers/project-metadata.ts:43:30)
          at tools/challenge-helper-scripts/helpers/project-metadata.test.ts:158:34
          at Object.<anonymous> (node_modules/.pnpm/expect@29.7.0/node_modules/expect/build/toThrowMatchers.js:74:11)
          at Object.throwingMatcher [as toThrow] (node_modules/.pnpm/expect@29.7.0/node_modules/expect/build/index.js:320:21)
          at Object.toThrow (tools/challenge-helper-scripts/helpers/project-metadata.test.ts:158:38)

      156 |     process.env.CALLING_DIR = 'english/superblock/project';
      157 |
    > 158 |     expect(() => validateMetaData()).toThrow(
          |                                      ^
      159 |       "File english/superblock/project/id-3.md should be in the meta.json's challengeOrder"
      160 |     );
      161 |   });

      at Object.toThrow (tools/challenge-helper-scripts/helpers/project-metadata.test.ts:158:38)

 FAIL  tools/challenge-helper-scripts/helpers/get-challenge-order.test.ts
  ● getChallengeOrderFromMeta helper › should load the file order

    ENOENT: no such file or directory, open '/workspace/freeCodeCamp/curriculum/challenges/_meta/mock-project/meta.json'

      20 |
      21 | function getMetaData(): Meta {
    > 22 |   const metaData = fs.readFileSync(getProjectMetaPath(), 'utf8');
         |                       ^
      23 |   return JSON.parse(metaData) as Meta;
      24 | }
      25 |

      at readFileSync (tools/challenge-helper-scripts/helpers/project-metadata.ts:22:23)
      at getChallengeOrderFromMeta (tools/challenge-helper-scripts/helpers/get-challenge-order.ts:27:27)
      at Object.<anonymous> (tools/challenge-helper-scripts/helpers/get-challenge-order.test.ts:47:53)

  ● getChallengeOrderFromFileTree helper › should load the file order

    ENOENT: no such file or directory, open '/workspace/freeCodeCamp/curriculum/challenges/english/superblock/mock-project/step-001.md'

      13 |   const fileList = await readdir(path);
      14 |   const challengeOrder = fileList
    > 15 |     .map(file => matter.read(join(path, file)))
         |                         ^
      16 |     .map(({ data }) => ({
      17 |       id: data.id as string,
      18 |       title: data.title as string

      at Function.Object.<anonymous>.matter.read (node_modules/.pnpm/gray-matter@4.0.3/node_modules/gray-matter/index.js:179:18)
      at read (tools/challenge-helper-scripts/helpers/get-challenge-order.ts:15:25)
          at Array.map (<anonymous>)
      at map (tools/challenge-helper-scripts/helpers/get-challenge-order.ts:15:6)
      at Object.<anonymous> (tools/challenge-helper-scripts/helpers/get-challenge-order.test.ts:101:28)

  ● getChallengeOrderFromFileTree helper › should load the file order

    expect.assertions(1)

    Expected one assertion to be called but received zero assertion calls.

      90 |
      91 |   it('should load the file order', async () => {
    > 92 |     expect.assertions(1);
         |            ^
      93 |     process.env.CALLING_DIR = join(
      94 |       process.cwd(),
      95 |       'curriculum',

      at Object.assertions (tools/challenge-helper-scripts/helpers/get-challenge-order.test.ts:92:12)

 FAIL  tools/challenge-helper-scripts/helpers/get-file-name.test.ts
  ● getFileName helper › should return the file name if found

    ENOENT: no such file or directory, open '/workspace/freeCodeCamp/curriculum/challenges/english/superblock/mock-project/i-dunno.md'

      10 |       continue;
      11 |     }
    > 12 |     const frontMatter = matter.read(`${path}${file}`);
         |                                ^
      13 |     if (String(frontMatter.data.id) === id) {
      14 |       return file;
      15 |     }

      at Function.Object.<anonymous>.matter.read (node_modules/.pnpm/gray-matter@4.0.3/node_modules/gray-matter/index.js:179:18)
      at read (tools/challenge-helper-scripts/helpers/get-file-name.ts:12:32)
      at Object.<anonymous> (tools/challenge-helper-scripts/helpers/get-file-name.test.ts:45:22)

  ● getFileName helper › should return the file name if found

    expect.assertions(1)

    Expected one assertion to be called but received zero assertion calls.

      34 |
      35 |   it('should return the file name if found', async () => {
    > 36 |     expect.assertions(1);
         |            ^
      37 |     process.env.CALLING_DIR = join(
      38 |       process.cwd(),
      39 |       'curriculum',

      at Object.assertions (tools/challenge-helper-scripts/helpers/get-file-name.test.ts:36:12)

  ● getFileName helper › should return null if not found

    ENOENT: no such file or directory, open '/workspace/freeCodeCamp/curriculum/challenges/english/superblock/mock-project/i-dunno.md'

      10 |       continue;
      11 |     }
    > 12 |     const frontMatter = matter.read(`${path}${file}`);
         |                                ^
      13 |     if (String(frontMatter.data.id) === id) {
      14 |       return file;
      15 |     }

      at Function.Object.<anonymous>.matter.read (node_modules/.pnpm/gray-matter@4.0.3/node_modules/gray-matter/index.js:179:18)
      at read (tools/challenge-helper-scripts/helpers/get-file-name.ts:12:32)
      at Object.<anonymous> (tools/challenge-helper-scripts/helpers/get-file-name.test.ts:59:22)

  ● getFileName helper › should return null if not found

    expect.assertions(1)

    Expected one assertion to be called but received zero assertion calls.

      48 |
      49 |   it('should return null if not found', async () => {
    > 50 |     expect.assertions(1);
         |            ^
      51 |     process.env.CALLING_DIR = join(
      52 |       process.cwd(),
      53 |       'curriculum',

      at Object.assertions (tools/challenge-helper-scripts/helpers/get-file-name.test.ts:50:12)


Test Suites: 4 failed, 113 passed, 117 total
Tests:       11 failed, 750 passed, 761 total
Snapshots:   29 passed, 29 total
Time:        79.595 s
Ran all test suites.
 ELIFECYCLE  Command failed with exit code 1.
ERROR: "test:source" exited with 1.
 ELIFECYCLE  Test failed. See above for more details.
```



can you help here @Sembauke ?

**Comment by Sembauke** [comment]
@hariomgehlot, you should update your main branch to the latest main branch of freeCodeCamp.

We do not recommend working on features from your main branch.

**Comment by Sembauke** [comment]
Hey @hariomgehlot,
Thank you for making this change, although this pull-request already looks pretty good. We would like to see some changes. Let us know if we can be of any help. 

In the mean time I will be closing this pull-request to open this issue up for other contributors. Feel free to re-open and work on it again.

Have a great day and happy coding.

**Pull request closed without merging**
