### PR TITLE
fix(curriculum): binary search tree min/max height 

### LINKED ISSUE #34725: Small fix needed in Binary Search Tree Min/Max Height challenge
**Describe your problem and how to reproduce it:**
This last test for method isBalanced is incorrect.  It should return the negation because the tree is unbalanced with min height of 1 and max height of 5.  Should be like:

`- text: The <code>isBalanced</code> method returns true if the tree is a balanced binary search tree.
    testString: assert((function() { var test = false; if (typeof BinarySearchTree !== 'undefined') { test = new BinarySearchTree() } else { return false; }; if (typeof test.isBalanced !== 'function') { return false; }; test.add(4); test.add(1); test.add(7); test.add(87); test.add(34); test.add(45); test.add(73); test.add(8); return !test.isBalanced(); })(), 'The <code>isBalanced</code> method returns true if the tree is a balanced binary search tree.');`

Also the add method in the After Test section should be included in the Challenge Seed because it is necessary for the test.

**Add a Link to the page with the problem:**
https://github.com/freeCodeCamp/freeCodeCamp/blob/master/curriculum/challenges/english/08-coding-interview-prep/data-structures/find-the-minimum-and-maximum-height-of-a-binary-search-tree.english.md

**Tell us about your browser and operating system:**
* Browser Name: Google Chrome
* Browser Version: 72
* Operating System: Chrome OS

**If possible, add a screenshot here (you can drag and drop, png, jpg, gif, etc. in this box):**

### PR DESCRIPTION
**Pull request by Fordco**
- [x] I have read [freeCodeCamp's contribution guidelines](https://github.com/freeCodeCamp/freeCodeCamp/blob/master/CONTRIBUTING.md).
- [x] My pull request has a descriptive title (not a vague title like `Update index.md`)
- [x] My pull request targets the `master` branch of freeCodeCamp.
- [x] None of my changes are plagiarized from another source without proper attribution.
- [x] All the files I changed are in the same world language (for example: only English changes, or only Chinese changes, etc.)
- [x] My changes do not use shortened URLs or affiliate links.

Closes #34725

### CODE REVIEW

**Comment by raisedadead** [comment]
Hi @Fordco 

Thanks a lot for the PR. Can you please remove the changes to the lockfiles. You can reach out to the [Contributors Chat room](https://gitter.im/FreeCodeCamp/Contributors) for help. The folks there are amazing and will help with this.

Thanks a lot and happy contributing!

**Comment by ValeraS** [comment]
@Fordco Could you provide a solution to this challenge to show the correctness of tests?

**Comment by Fordco** [comment]
> @Fordco Could you provide a solution to this challenge to show the correctness of tests?

We used a solution posted by hk-skit in the forum.  
https://www.freecodecamp.org/forum/t/data-structures-find-the-minimum-and-maximum-height-of-a-binary-search-tree/215822
Here is the solution:

var displayTree = (tree) => console.log(JSON.stringify(tree, null, 2));
function Node(value) {
    this.value = value;
    this.left = null;
    this.right = null;
}
function BinarySearchTree() {
    this.root = null;
    // change code below this line
    // change code above this line
    this.findMinHeight = function(root = this.root) {
        // empty tree.
        if(root === null) {
            return -1;
        }
        // leaf node.
        if(root.left === null && root.right === null) {
            return 0;
        }
        if(root.left === null){
            return this.findMinHeight(root.right) + 1;
        }
        if(root.right === null){
            return this.findMinHeight(root.left) + 1;
        }
        const lHeight = this.findMinHeight(root.left);
        const rHeight = this.findMinHeight(root.right);
        return Math.min(lHeight, rHeight) + 1;
    };
    this.findMaxHeight = function(root = this.root) {
        // empty tree.
        if(root === null) {
            return -1;
        }
        // leaf node.
        if(root.left === null && root.right === null) {
            return 0;
        }
        if(root.left === null){
            return this.findMaxHeight(root.right) + 1;
        }
        if(root.right === null){
            return this.findMaxHeight(root.left) + 1;
        }
        const lHeight = this.findMaxHeight(root.left);
        const rHeight = this.findMaxHeight(root.right);
        return Math.max(lHeight, rHeight) + 1;
    };
    this.isBalanced = function(root = this.root) {
        
        if(root === null) {
            return true;
        }

        if(root.left === null && root.right === null){
            return true;
        }

        if(root.left === null) {
            return this.findMaxHeight(root.right) <= 0; 
        }

        if(root.right === null) {
             return this.findMaxHeight(root.left) <= 0; 
        }

        const lHeight = this.findMaxHeight(root.left);
        const rHeight = this.findMaxHeight(root.right);
        if(Math.abs(lHeight - rHeight) > 1){
            return false;
        }
        return this.isBalanced(root.left) && this.isBalanced(root.right);
    };
}

**Comment by ValeraS** [comment]
place it in a solution section in the challenge file.

**Comment by Fordco** [comment]
Is that what you meant by challenge file @ValeraS ?

**Comment by ValeraS** [comment]
Find in the committed file lines:
````
<section id='solution>

```js
// solution required
```

</section>
````

and replace `// solution required` to the solution.

**Comment by chaomt** [comment]
> Find in the committed file lines:
> 
> ```
> <section id='solution'>
> 
> ```js
> // solution required
> ```
> 
> </section>
> ```
> and replace `// solution required` to the solution.

We update the pull request to include the solution. Thanks for your help!

**Comment by Fordco** [comment]
Hi @ValeraS  and @raisedadead 
I was wondering if anything else needs to be done for this PR to be merged?

**Comment by RandellDawson** [comment]
@Fordco It just needs to be reviewed thoroughly and we still have many ahead of yours.  Don't worry, we will eventually get to yours.

**Comment by Fordco** [comment]
Thanks, just checking if there was anything else needed on my end.

**Review by thecodingaviator — DISMISSED** [review]
The solution for this challenge has been provided in an earlier PR (#35006 ), in addition, the currently provided solution fails the last test:
image

**Comment by MengtingChao** [comment]
@thecodingaviator 
The last test case is wrong. That is why the currently provided solution fails the last test.

**Comment by chaomt** [comment]
@thecodingaviator
The last test case is wrong. That is why the currently provided solution fails the last test.

**Comment by Fordco** [comment]
This pr will fix the incorrect final test case. A previous valid solution was used to verify that the change made will correct the test case so all test cases pass when a correct solution is submitted.

**Comment by thecodingaviator** [comment]
Ah, alright

**Comment by Fordco** [comment]
Is there anything I need to do to resolve the conflicts on the branch?

**Comment by thecodingaviator** [comment]
Yeah, please go ahead and fix the merge conflict

**Comment by thecodingaviator** [comment]
@Fordco There still seem to be some merge conflicts on my end, can you see them?

**Comment by Fordco** [comment]
@thecodingaviator Yes I saw them, sorry about that. I just fixed them now. I think I accidentally requested a review from Quincy Larson in the process, that wasn't intentional.

**Comment by Fordco** [comment]
Actually @thecodingaviator  @RandellDawson  I think I messed something up when I tried to fix the merge conflict. I only wanted to merge one commit from my branch, not 1,454.

**Comment by thecodingaviator** [comment]
@Fordco did you rebase the branch before pushing? That's the most likely error

**Comment by thecodingaviator** [comment]
@Fordco What I'd suggest you do is pull a fresh copy of the latest master branch, make your changes on that fresh copy and push it here

**Comment by Fordco** [comment]
Great, I'll try that now.

**Comment by thecodingaviator** [comment]
@Fordco We're trying something here too

**Comment by Fordco** [comment]
@thecodingaviator  So should I still try what you suggested or should I wait?

**Comment by RandellDawson** [comment]
@Fordco Wait just a bit.  @thecodingaviator and I are discussing the best fix.  We will let you know soon.

**Comment by Fordco** [comment]
@RandellDawson  Will do. Sorry for causing trouble.

**Comment by thecodingaviator** [comment]
@Fordco Now, please check if the changes you wanted to have been made

**Comment by RandellDawson** [comment]
@Fordco I believe I resolved everything.  Definitely review it one last time, before we merge it, to make sure this is how you want the PR.

FYI - It added Quincy because of all those other files you accidentally added. 

I was also able to clean up the git history to be a single commit.

**Comment by Fordco** [comment]
@thecodingaviator @RandellDawson  Thanks for the help! Sorry again.

Yes, the PR now looks correct and includes the changes I wanted made.

**Comment by thecodingaviator** [comment]
@Fordco Go over this once would help: https://gist.github.com/thecodingaviator/db4c142a6f21d1c1a19d53fc7c11d5c5

**Comment by Fordco** [comment]
Thanks @thecodingaviator

**Review by ojeytonwilliams — APPROVED** [review]
LGTM :+1:

**Review by thecodingaviator — APPROVED** [review]
LGTM

**Comment by thecodingaviator** [comment]
Thank you for your contribution to the page! 👍
We're happy to accept these changes, and look forward to future contributions. 📝

**Comment by thecodingaviator** [comment]
@Fordco Please open a PR to fix the guide article for this challenge

**Comment by Fordco** [comment]
@thecodingaviator I can do that. Is this the guide article you mean? guide/english/certifications/coding-interview-prep/data-structures/find-the-minimum-and-maximum-height-of-a-binary-search-tree/index.md
What would you like me to contribute to it?

**Comment by thecodingaviator** [comment]
Change the solution given in that file so that it contains the correct solution to this challenge

**Comment by Fordco** [comment]
We made a PR adding the solution to the guide article, #35938.

**Pull request merged**
