### PR TITLE
Render CodeMirror skeleton for SSR

### LINKED ISSUE #9735: Progress Visualization for clean UX experience
For a user, who visits the website (initial loads on a fresh device), certain UI elements take a while to populate.

Example:
1. Login, the profile image takes a couple of seconds to appear on the navbar
2. The map aside takes a couple of seconds to populate and displays "No Superblocks" 
3. Challenges views at times take a second to render.

Although these happen seamlessly from the next interaction with the elements. Hence we might as well think of having some form of progress to present the blocking nature of the UI.

### PR DESCRIPTION
**Pull request by Bouncey**
#### Pre-Submission Checklist

- [x] Your pull request targets the `staging` branch of FreeCodeCamp.
- [x] Branch starts with either `fix/`, `feature/`, or `translate/` (e.g. `fix/signin-issue`)
- [x] You have only one commit (if not, [squash](http://forum.freecodecamp.com/t/how-to-squash-multiple-commits-into-one-with-git/13231) them into one commit).
- [x] All new and existing tests pass the command `npm test`. Use `git commit --amend` to amend any fixes.

#### Type of Change

- [ ] Small bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds new functionality)
- [ ] Breaking change (fix or feature that would change existing functionality)
- [ ] Add new translation (feature adding new translations)

#### Checklist:

- [x] Tested changes locally.
- [x] Closes currently open issue (replace XXXX with an issue no): Closes #9735 

#### Description

See [issue comment](https://github.com/FreeCodeCamp/FreeCodeCamp/issues/9735#issuecomment-259809758)

### CODE REVIEW

**Comment by Bouncey** [comment]
See #12305 for details of broken build

**Comment by BerkeleyTrue** [comment]
This is dope. Did you source the animation from anywhere?

**Comment by Bouncey** [comment]
I started looking for an animation to liberate to our code base, but they were all for text shimmers mimicking iOS examples. The only thing I think I didn't write myself is the `.shimmer` class name.

**Comment by Bouncey** [comment]
Fixed some whitespace issues

**Comment by BerkeleyTrue** [comment]
Awesome!

**Pull request merged**
