### PR TITLE
feat(UI): Add new congratulations messages and remove some

### PR DESCRIPTION
**Pull request by QuincyLarson**
#### Pre-Submission Checklist

- [x] Your pull request targets the `staging` branch of freeCodeCamp.
- [x] Branch starts with either `fix/`, `feature/`, or `translate/` (e.g. `fix/signin-issue`)
- [x] You have only one commit (if not, [squash](http://forum.freecodecamp.org/t/how-to-squash-multiple-commits-into-one-with-git/13231) them into one commit).
- [ ] All new and existing tests pass the command `npm test`. Use `git commit --amend` to amend any fixes.

#### Type of Change

- [x] Small bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds new functionality)
- [ ] Breaking change (fix or feature that would change existing functionality)
- [ ] Add new translation (feature adding new translations)

#### Description
Some campers found the "We underestimated you" congratulatory line to be inappropriate. I removed it and added a few new ones.

### CODE REVIEW

**Review by raisedadead — APPROVED** [review]
LGTM.

Quick query: Where do we plan to use the `calls-to-action` ?

Thanks @QuincyLarson

**Comment by QuincyLarson** [comment]
@raisedadead We may start letting campers turn on browser notifications to remind them to come back and code. Like once a day a noon, it could pop up a browser notification that takes them back to their current challenge. This feature is just an idea at this point, but I didn't think it would hurt to add my proposed call to action phrases to the document.

**Comment by raisedadead** [comment]
Oh yes, totally. I was just curious about the addition. 😃 !

**Comment by QuincyLarson** [comment]
@raisedadead thanks for QA'ing this.

**Pull request merged**
