### PR TITLE
fix: add donation ga and tests

### PR DESCRIPTION
**Pull request by ahmaxed**
this pr does the followings:
- moves GA from the views to a redux saga
- adds donation related GA events 
- adds an integration test to the GA saga

note: I tested building and serving this pr locally.

### CODE REVIEW

**Comment by raisedadead** [comment]
Did we change anything in the logic, or this PR is the same implementation with added tests to resolve the build errors?

**Comment by ahmadabdolsaheb** [comment]
> Did we change anything in the logic, or this PR is the same implementation with added tests to resolve the build errors?

It is the same logic. the build was a result of a misspelled function name, I believe.

The test checks that when a specific action is fired, GA is called with the right arguments.

**Comment by raisedadead** [comment]
Perfect, thanks for confirming. I will do a sanity check and land this.

**Comment by ahmadabdolsaheb** [comment]
let's land this. I am gonna need the wiring here to tackle #38052. I will resolve the conflict today.

**Comment by ahmadabdolsaheb** [comment]
should be good to go.

**Pull request merged**
