### PR TITLE
Fix for a grammar issue in add a submit button to a form ( #1218 )

### PR DESCRIPTION
**Pull request by benmcmahon100**
Fix for issue #1218

### CODE REVIEW

**Comment by BerkeleyTrue** [comment]
@benmcmahon100 in the future please add `fix for #<issue number>` to body of message and make title descriptive of changes.

see: http://tbaggery.com/2008/04/19/a-note-about-git-commit-messages.html

**Comment by benmcmahon100** [comment]
@BerkeleyTrue Sorry just threw it up when i saw it initially! Just fixed all that now

**Comment by BerkeleyTrue** [comment]
Looking it over it looks like it would make more sense as `Your submit button should be of input type "submit"`

**Comment by BerkeleyTrue** [comment]
@benmcmahon100 No worries.

**Comment by BerkeleyTrue** [comment]
@benmcmahon100 You move fast.

**Comment by benmcmahon100** [comment]
<Insert sonic gif here>

**Comment by benmcmahon100** [comment]
Do you want me to change it back? :blush:

**Comment by BerkeleyTrue** [comment]
Lets make it specific `Your submit button should have the attribute 'type' set to \"submit\"`

**Pull request merged**
