### PR TITLE
Update knip & config

### PR DESCRIPTION
**Pull request by webpro**
Checklist:

- [x] I have read [freeCodeCamp's contribution guidelines](https://contribute.freecodecamp.org).
- [x] My pull request has a descriptive title (not a vague title like `Update index.md`)
- [x] My pull request targets the `main` branch of freeCodeCamp.
- [x] I have tested these changes either locally on my machine, or GitPod.

Figured it would be good to assist with the migration to Knip v1, which is almost there. Then saw that `npx -y knip` is now used instead of being a regular dependency, which would result in issues caused by breaking changes.

So, first of all I would suggest to use versioning, either by using Knip as a regular dependency, or by adding the version to the `npx` command (e.g. `npx -y knip@0.13.3`). I would also suggest to rename the npm scripts, perhaps like so:

```json
{
  "scripts": {
    "knip": "knip",
    "knip:files": "knip --include files",
  }
}
```

Or remove them from the `scripts` altogether and use `npx knip` everywhere. I didn't change the npm script names as not to mess with the `node.js-find-unused.yml` workflow.

Then, since the API (CLI arguments and configuration schema) should not change anymore I just went ahead and offer this PR just before the v1 release. What's in there for FCC:

- Please see https://github.com/webpro/knip/blob/next/docs/migration-to-v1.md for the breaking changes
- Amongst other things, no more `dev` config means you don't need to fiddle with glob patterns for test files, and one `knip.jsonc` should be enough.
- Less configuration with the introduction of plugins for Babel, Cypress, ESLint, Jest, Gatsby, etc. etc. that take care of related (glob patterns for) configuration and entry files, and reduce the number of false positives.
- Workspaces are now central to Knip, and I configured a few more workspaces while I was at it.
- While the previous config had `"exclude": ["dependencies"]`, this is no longer the case and while there are still a few false positives, I think a good analysis is worth a try (e.g. `npx knip --include dependencies,unlisted`).
- Many improvements and bug fixes I'm missing now, but I think this list is most relevant for now.

TODO

- Taking the `entry` files from the `webpack` config automatically is high on the list to implement after v1 is out.
- ✂️ Knip, knip, knip!

### CODE REVIEW

**Review by raisedadead — CHANGES_REQUESTED** [review]
We moved to use `npx -y knip` because of the incompatible changes with strict engines in one of the recent knip versions. We were on Node.js 16 then, and adding knip (which needs Node.js 18?) as a regular dep was not feasible.

While we have moved up to Node.js 18 now, we would like to avoid surprises in specific workflows.

We use knip only occasionally (no CI/CD flows), and we prefer to keep it that way. We will bump the version (including beta) if you like that.

Please adjust the PR accordingly. Thanks.

**Comment by webpro** [comment]
> We moved to use `npx -y knip` because of the incompatible changes with strict engines in one of the recent knip versions. We were on Node.js 16 then, and adding knip (which needs Node.js 18?) as a regular dep was not feasible.

Sorry to hear you had issues. Knip requires at least Node.js v16.17 or v18.6 and uses GitHub Actions to `npm test` since v0.7.2.

> While we have moved up to Node.js 18 now, we would like to avoid surprises in specific workflows.

> We use knip only occasionally (no CI/CD flows), and we prefer to keep it that way. We will bump the version (including beta) if you like that.

> Please adjust the PR accordingly. Thanks.

I certainly don't want to be a burden here.

**Review by raisedadead — APPROVED** [review]
LGTM. Thanks a lot @webpro! @ojeytonwilliams, please give this a quick look and land if you are happy.

**Comment by ojeytonwilliams** [comment]
Hey @webpro thanks for helping out with the migration.  It looks like the new version/config has found even more junk, so that's good!

One weird thing I noticed while testing was this:

```
npx -y knip@^1.0.0-beta.9

node:internal/errors:484
    ErrorCaptureStackTrace(err);
    ^

Error [ERR_MODULE_NOT_FOUND]: Cannot find package 'typescript' imported from .../.npm/_npx/ebee0bdb22a1405e/node_modules/knip/dist/util/tsconfig-loader.js
    at new NodeError (node:internal/errors:393:5)
    at packageResolve (node:internal/modules/esm/resolve:860:9)
    at moduleResolve (node:internal/modules/esm/resolve:909:20)
    at defaultResolve (node:internal/modules/esm/resolve:1124:11)
    at nextResolve (node:internal/modules/esm/loader:163:28)
    at ESMLoader.resolve (node:internal/modules/esm/loader:841:30)
    at ESMLoader.getModuleJob (node:internal/modules/esm/loader:424:18)
    at ModuleWrap.<anonymous> (node:internal/modules/esm/module_job:76:40)
    at link (node:internal/modules/esm/module_job:75:36) {
  code: 'ERR_MODULE_NOT_FOUND'
}
```

I've never run into `ERR_MODULE_NOT_FOUND` before when `npx`ing something. Any idea why that might be?

**Comment by webpro** [comment]
> I've never run into `ERR_MODULE_NOT_FOUND` before when `npx`ing something. Any idea why this might be happening?

It means a dependency was not installed (usually because it was not part of its `dependencies`)

> One weird thing I noticed while testing was this:
> 
> ```
> npx -y knip@^1.0.0-beta.9
> 
> node:internal/errors:484
>     ErrorCaptureStackTrace(err);
>     ^
> 
> Error [ERR_MODULE_NOT_FOUND]: Cannot find package 'typescript' imported from 

This is now fixed, I moved the `typescript` dependency. Internally, Knip now has a `--production --strict` mode to eat its own dog food and prevent this from happening again.

**Comment by ojeytonwilliams** [comment]
> It means a dependency was not installed (usually because it was not part of its dependencies)

Ah, I see you've made it a production dep. Makes sense!

**Review by ojeytonwilliams — APPROVED** [review]
LGTM :+1:

**Comment by webpro** [comment]
Just to clarify a bit further: this wasn't really an issue elsewhere, as usually `knip` itself is a `devDependency` and so is `typescript`. Good to be aware of this though and have it fixed, so thanks a bunch!

**Comment by ojeytonwilliams** [comment]
Yep, that makes sense.  We should be more disciplined about that, to be honest.

Anyways, thanks again for helping with the maintenance :)

**Pull request merged**
