### PR TITLE
fix(flash-message) Centered text of flash-message

### LINKED ISSUE #44835: Minor UI issue in homepage, while toggling night mode.
**Affected Page**
https://www.freecodecamp.org/learn and all the pages in which we are flashing `We have updated your preferences` this message on changing of `Night Mode`

**To Reproduce**
1. Go to 'https://www.freecodecamp.org/learn' and sign in/ sign up
2. Click on 'Menu' button on navigation bar and select night mode `ON/OFF`
3. After selecting the night mode, you will see a message flashes with text `We have updated your preferences`

**Expected behavior**
The text in the message and button should be in the center. But it is not centered.

**Screenshots**
image

**Desktop (please complete the following information):**
 - OS: MacOs
 - Browser: Chrome
 - Version: 97.0.4692.71 (Official Build) (arm64)

### PR DESCRIPTION
**Pull request by GoonerBrian**
Checklist:

- [x] I have read [freeCodeCamp's contribution guidelines](https://contribute.freecodecamp.org).
- [x] My pull request has a descriptive title (not a vague title like `Update index.md`)
- [x] My pull request targets the `main` branch of freeCodeCamp.
- [x] I have tested these changes either locally on my machine, or GitPod.

Closes #44835

Centered text of flash-message in the alert bar and moved close button to right in the alert bar. Verified for both updating preference (dark mode on/off) and trying to claim a certificate without completing the necessary steps.

### CODE REVIEW

**Comment by ahmadabdolsaheb** [comment]
Thanks for your patience with this. I have been reviewing different notification solutions. I will get back to you as soon as I have an answer to see if we need a more fundamental change to our flash messages.

**Comment by ahmadabdolsaheb** [comment]
Thank you for submitting this pr. After considering your pr and alternative solutions, I think it would be better close this pr and iterate on the alert component of the UI component library once the library is in use.

I highly encourage you to check out the related issue for the [Component Library](https://github.com/freeCodeCamp/freeCodeCamp/issues/44668) and let us know if you have any questions.

I am closing this pull request accordingly and look forward to your future contributions to our repository

**Comment by ahmadabdolsaheb** [comment]
Thank you for submitting this pr. After considering your pr and alternative solutions, I think it would be better to close this pr and iterate on the alert component of the UI component library once the library is in use.

I highly encourage you to check out the related issue for the [Component Library](https://github.com/freeCodeCamp/freeCodeCamp/issues/44668).

I look forward to seeing your future contributions to the freeCodeCamp repository and let us know if you need any help.

**Comment by GoonerBrian** [comment]
Thanks! I'll check out that component library.

**Pull request closed without merging**
