### PR TITLE
Update challenge.js

### PR DESCRIPTION
**Pull request by MurrayBakerWebDeveloper**
removed backslash from HalfWayClub link on line 234

### CODE REVIEW

**Comment by abhisekp** [comment]
Was it doing anything bad? You left the other backslashes though.

**Comment by ltegman** [comment]
Please follow the branch naming conventions described in [Pull Request Contribute](https://github.com/FreeCodeCamp/FreeCodeCamp/wiki/Pull-Request-Contribute) and also put `Closes #XXXX` with a reference to whatever issue you are closing.

Also, as @abhisekp asked, what it this PR solving?

**Comment by nuku89** [comment]
On what lines did you see the other backslashes? It was my first pull request I didn't know what I was doing I will follow that link. 

Removing the unnecessary backslash makes the link accessible.

**Comment by ltegman** [comment]
The backslash you removed is used to escape the quotation mark. The problem lies in the two forward slashes at the front of the URL. Closing this PR but feel free to open a new PR that follows the contribution guides.

Thanks and happy coding!

**Pull request closed without merging**
