### PR TITLE
fix(curriculum): move sentence maker lab to strings and variables module

### LINKED ISSUE #57710: The Sentence Maker lab from the JS functions module does not ask to use functions
This was discussed and apparently never implemented. User stories and tests should be modified to use functions, since this lab has been placed in that module.

https://github.com/freeCodeCamp/freeCodeCamp/blob/main/curriculum/challenges/english/25-front-end-development/lab-sentence-maker/66c057041df6394ca796bf33.md?plain=1

### PR DESCRIPTION
**Pull request by Dario-DC**
Checklist:

- [x] I have read and followed the [contribution guidelines](https://contribute.freecodecamp.org).
- [x] I have read and followed the [how to open a pull request guide](https://contribute.freecodecamp.org/how-to-open-a-pull-request/).
- [x] My pull request targets the `main` branch of freeCodeCamp.
- [x] I have tested these changes either locally on my machine, or GitPod.

Closes #57710

### CODE REVIEW

**Comment by zairahira** [comment]
Looking good 👍️
<details>
<summary>
image</summary>

image

</details>

**Review by majestic-owl448 — APPROVED** [review]

**Comment by Dario-DC** [comment]
So is it okay to place it after the trivia bot lab?

**Comment by zairahira** [comment]
> So is it okay to place it after the trivia bot lab?

Yes!

**Comment by Dario-DC** [comment]
Could you approve then? @zairahira

**Review by zairahira — APPROVED** [review]

**Pull request merged**
