### PR TITLE
fix first test message in Where art thou bonfire

### PR DESCRIPTION
**Pull request by ribeirojpn**
Closes https://github.com/FreeCodeCamp/FreeCodeCamp/issues/3862

### CODE REVIEW

**Comment by ltegman** [comment]
Thanks for the PR!

Since this test isn't looking for just an array of objects but actually a specific array of objects it would be preferable if the test said something like "`where([{ first: \"Romeo\", last: \"Montague\" }, { first: \"Mercutio\", last: null }, { first: \"Tybalt\", last: \"Capulet\" }], { last: \"Capulet\" })` should return `[{ first: \"Tybalt\", last: \"Capulet\" }]`"

Also, please format your notation of what issue it closes like "Closes #3862" so that the issue will be automatically closed if the PR is merged.

**Comment by ribeirojpn** [comment]
Updated as requests

**Comment by ltegman** [comment]
Thanks for the quick update! :smile:

**Comment by ribeirojpn** [comment]
Thank you for merge. This was my first contribution, I hope to contribute more and more.

**Comment by ltegman** [comment]
Always good to see new faces contributing! I look forward to more PRs from you!

**Pull request merged**
