### PR TITLE
fix(curriculum) : allow a and b to be cast as numbers in step 41 of num sort

### LINKED ISSUE #54420: Updates to step 40 and 41 of Number Sorter Challenge
### Describe the Issue

The instruction asks the challenger to "return a single subtraction calculation using a and b" without providing a piece of contextual information that if `a` and `b` are both number-like string, `a` - `b` will return a numeric result. 

First coming into the challenge, my thought process was to convert `a` and `b` into numbers, using `Number()` or `parseInt()`. But neither method passed the test. Later, I suspected that the calculation (`a` - `b`) without converting `a` and `b` into numbers first will still return a number, I passed the test. 

I am not sure whether this counts as a bug in the test. Nevertheless, I thought it would be clearer for the challengers had they been provided with the relevant information. 

### Affected Page

https://www.freecodecamp.org/learn/javascript-algorithms-and-data-structures-v8/learn-basic-algorithmic-thinking-by-building-a-number-sorter/step-41

### Your code

```

  const sortedValues = inputValues.sort((a, b) => {
    return Number(a) - Number(b);
  });

```

### Expected behavior

I expected this code to pass the test. 
I was informed that the callback function should return `a - b`, but not informed about the reason why `Number(a) - Number(b)` doesn't pass.

### Screenshots

_No response_

### System

- Device: Laptop
- OS: Windows 11
- Browser: FireFox
- Version: 125.0.1

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by a2937**
Checklist:

- [X] I have read and followed the [contribution guidelines](https://contribute.freecodecamp.org).
- [X] I have read and followed the [how to open a pull request guide](https://contribute.freecodecamp.org/#/how-to-open-a-pull-request).
- [X] My pull request targets the `main` branch of freeCodeCamp.
- [X] I have tested these changes either locally on my machine, or GitPod.

Closes #54420

In my opinion the following answers should be allowed. 

`a` and `b` both wrapped in parentheses. 

```
 const sortedValues = inputValues.sort((a, b) => {
    return (a - b);
  });
```

Our default solution. 

```
 const sortedValues = inputValues.sort((a, b) => {
    return a - b;
  });
```

`a` and `b` parsed as integers. 

```
 const sortedValues = inputValues.sort((a, b) => {
    return parseInt(a) - parseInt(b);
  });
```

`a` and `b` used as arguments in the Number function. 

```
 const sortedValues = inputValues.sort((a, b) => {
    return Number(a) - Number(b);
  });
```

This pull request covers all four test cases that should be expected to pass.

### CODE REVIEW

**Comment by jdwilkin4** [comment]
This needs further discussion so I am labelling this as blocked until a definitive solution has been reached.

**Comment by a2937** [comment]
Understood.

**Comment by jdwilkin4** [comment]
Now that the issue is ironed out, the updates to the tests look good to me.
Let's just update the step 40 description and this PR should be good to go 👍 

https://github.com/freeCodeCamp/freeCodeCamp/issues/54420#issuecomment-2062837261

**Comment by a2937** [comment]
Step 40 description is now updated.

**Review by jdwilkin4 — COMMENTED** [review]
The changes look good but for some reason one of the automated test is failing
Could you look into that?
Thanks

**Comment by a2937** [comment]
Nothing related to the stuff modified in the PR is failing. As far as I can tell it is the `reset-modal.spec.ts` not being able to add in the `h2` element properly.

**Comment by a2937** [comment]
Playwright screenshot
 
It's out of scope of this PR. I also need to install other browsers locally. But I also noticed the test passed in E2E Firefox.

**Review by jdwilkin4 — APPROVED** [review]
Tested it and works well on my end.
This unfortunately can't be merged until that last test is passing.
Sometimes where the tests are flaky, I merge the latest changes from main and that seems to fix it 🤷‍♀️

**Comment by a2937** [comment]
Hey all the checks seem to have passed.

**Review by moT01 — APPROVED** [review]
LGTM 🎉

**Pull request merged**
