### PR TITLE
Change Challenge use-the-conditional-ternary-operator.english.md

### LINKED ISSUE #18925: Basic JavaScript: Use the Conditional (Ternary) Operator teaches questionable practices?
**Describe your problem and how to reproduce it:**
The exercise is teaches questionable practices!?
There were a discussion previously https://github.com/freeCodeCamp/freeCodeCamp/issues/14821 .
But i think it should be reviewed again as change could be fairly simple.
Instead of asking if numbers are equal, ask to return "Bigger" or "Smaller" or something. 
As currently the better solution would be to return a === b;

**Add a Link to the page with the problem:**
https://learn.freecodecamp.org/javascript-algorithms-and-data-structures/basic-javascript/use-the-conditional-ternary-operator

### PR DESCRIPTION
**Pull request by brownben**
Change true to "equal" to demonstrate a better use case for ternary operator. 
Implementing @ezioda004 's idea from #18925

- [x] I have read [freeCodeCamp's contribution guidelines](https://github.com/freeCodeCamp/freeCodeCamp/blob/master/CONTRIBUTING.md).
- [x] My pull request has a descriptive title (not a vague title like `Update index.md`)
- [x] My pull request targets the `master` branch of freeCodeCamp.
- [x] None of my changes are plagiarized from another source without proper attribution.
- [x] My article does not contain shortened URLs or affiliate links.

Closes #18925

### CODE REVIEW

**Review by RandellDawson — CHANGES_REQUESTED** [review]
Was this supposed to close a specific open issue?  If so, please update your PR to state:

> Closes #XXXXX

**Review by ezioda004 — COMMENTED** [review]
Could you change `"equal"` to `"Equal"` and `"not equal"` to `"Not Equal"`?

**Comment by bonalybob** [comment]
Now changed to `"Equal"` and `"Not Equal"`

**Review by RandellDawson — APPROVED** [review]

**Comment by RandellDawson** [comment]
Keep in mind.  Whenever you make a change to a challenge in the curriculum, it needs to be changed in all 5 languages and the Guide article needs to be updated with the new solution.

**Comment by ezioda004** [comment]
Not merging this yet, need consensus. Can any of you guys check the PR and the issue? @Bouncey @raisedadead @QuincyLarson

**Review by cmccormack — APPROVED** [review]
Resolved merge conflicts, fixed missed `equal`.  Tested locally, tests appeared to pass fine.

This looks good to me.  Thank you for your contribution!

**Review by ezioda004 — APPROVED** [review]
Successfully tested locally.

**Comment by Bouncey** [comment]
@brownben Sorry for the delay in getting round to this PR. Im sure you can understand that the past two months have been overwhelming.

Could you please rebase your pull request so we can get these changes in? Many thanks

**Comment by brownben** [comment]
I think I have rebased the pull request now

**Review by cmccormack — APPROVED** [review]
@Bouncey I believe it is now properly rebased and pushed, could you please review when you get a chance?  I tested locally after fixing the conflicts and it passed.

**Review by raisedadead — APPROVED** [review]
#### :sparkles: :sparkles: **LGTM.** :sparkles: :sparkles: 

Thanks @brownben @RandellDawson @cmccormack @brownben !

Happy Contributing!

**Pull request merged**
