### PR TITLE
Fixed tests in Waypoint: Use Comments to Clarify Code

### PR DESCRIPTION
**Pull request by fridaybyte**
Added check for null and changed length check to larger than 0 (becuase we need only one comment to pass the tests)
Issue #1579

### CODE REVIEW

**Comment by benmcmahon100** [comment]
Is this tested on a local copy of FCC?

**Comment by flota113** [comment]
Yes ;)

**Comment by benmcmahon100** [comment]
Awesome work!

**Comment by flota113** [comment]
Thanks, the same goes for You guys :+1:

**Pull request merged**
