### PR TITLE
fix(seed): Add legacy project back in and update id

### LINKED ISSUE #16336: Image Search Abstraction API listed as Exercise Tracker on profile page
#### Issue Description

The 'Exercise Tracker' shows up as completed on 7th July 2016 on my profile. The actual project it is referring to is the Image Search Abstraction Layer project.

The 'view solution' link links to: `https://beta.freecodecamp.org/challenges/api-and-microservice-projects/exercise-tracker?solution=http%3A%2F%2Fpowerful-lowlands-49298.herokuapp.com%2F`

As you can see, the url definitely thinks it's the tracker, but my app linked to is the image one. I haven't completed the exercise tracker. 

The link doesn't actually open up the tracker / image app, it just links to the incomplete exercise tracker challenge page.

You can find this on my profile page, in the challenges section: https://beta.freecodecamp.org/en/jacksonbates

#### Browser Information

* Browser Name, Version: Chrome 60
* Operating System: Ubuntu 16.04
* Mobile, Desktop, or Tablet: Desktop

#### Screenshot

ex tracker bug

### PR DESCRIPTION
**Pull request by QuincyLarson**
Closes #16336

#### Pre-Submission Checklist

- [ ] Your pull request targets the `staging` branch of freeCodeCamp.
- [ ] Branch starts with either `fix/`, `feature/`, or `translate/` (e.g. `fix/signin-issue`)
- [ ] You have only one commit (if not, [squash](http://forum.freecodecamp.org/t/how-to-squash-multiple-commits-into-one-with-git/13231) them into one commit).
- [ ] All new and existing tests pass the command `npm test`. Use `git commit --amend` to amend any fixes.

#### Type of Change

- [ ] Small bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds new functionality)
- [ ] Breaking change (fix or feature that would change existing functionality)
- [ ] Add new translation (feature adding new translations)

#### Checklist:

- [ ] Tested changes locally.
- [ ] Addressed currently open issue (replace XXXXX with an issue no in next line)

Closes #XXXXX

### CODE REVIEW

**Review by raisedadead — CHANGES_REQUESTED** [review]
`package-lock.json` should not be added to this commit.

**Comment by QuincyLarson** [comment]
@raisedadead Thanks for clarifying. I've amended my commit to exclude the package-lock.json - ready for you to QA :)

**Comment by QuincyLarson** [comment]
@Bouncey I haven't heard back from @raisedadead yet. If this is blocking you from doing https://github.com/freeCodeCamp/freeCodeCamp/issues/16238 then please take a quick look at it and merge it - I think I've addressed @raisedadead's feedback.

**Comment by raisedadead** [comment]
Hi Guys, sorry about the delay in reviewing.

**Comment by QuincyLarson** [comment]
@raisedadead Thanks for reviewing and merging! 👍

**Pull request merged**
