### PR TITLE
feat(client): ts-migrate editor component

### PR DESCRIPTION
**Pull request by ShaunSHamilton**
Checklist:

- [x] I have read [freeCodeCamp's contribution guidelines](https://contribute.freecodecamp.org).
- [x] My pull request has a descriptive title (not a vague title like `Update index.md`)
- [x] My pull request targets the `main` branch of freeCodeCamp.
- [x] I have tested these changes either locally on my machine, or GitPod.

Related to #42256

### CODE REVIEW

**Comment by ShaunSHamilton** [comment]
I am not sure why this is failing:
```bash
success Building production JavaScript and CSS bundles - 721.239s
success Rewriting compilation hashes - 0.011s
success Building HTML renderer - 55.391s
failed Building static HTML for pages - 4.126s
error "navigator" is not available during server side rendering.

  53 |     return WindowManager.INSTANCE.getPixelRatio();
  54 | }
> 55 | const userAgent = navigator.userAgent;
     | ^
  56 | export const isFirefox = (userAgent.indexOf('Firefox') >= 0);
  57 | export const isWebKit = (userAgent.indexOf('AppleWebKit') >= 0);
  58 | export const isChrome = (userAgent.indexOf('Chrome') >= 0);


  WebpackError:ReferenceError: navigator is not defined
  
  - browser.js:55 
    [client]/[monaco-editor]/esm/vs/base/browser/browser.js:55:1
```

**Comment by ShaunSHamilton** [comment]
Cypress does not like the Spacer icon change:
```
  3) Email input field
       Should be possible to get Quincys weekly email:
     TypeError: The following error originated from your application code, not from Cypress.

  > Cannot assign to read only property 'style' of object '#<Object>'

When Cypress detects uncaught errors originating from your application it will automatically fail the current test.

This behavior is configurable, and you can choose to turn this off by listening to the `uncaught:exception` event.

```
CC @nhcarrigan

**Comment by nhcarrigan** [comment]
Weird that TypeScript and React don't think it's a read only property. I'll have to dig in to that more.

**Review by moT01 — APPROVED** [review]
LGTM 🎉

**Pull request merged**
