### PR TITLE
translate some few words

### PR DESCRIPTION
**Pull request by rnrnshn**
- [ x ] I have read [freeCodeCamp's contribution guidelines](https://github.com/freeCodeCamp/freeCodeCamp/blob/master/CONTRIBUTING.md).
- [ x ] My pull request has a descriptive title (not a vague title like `Update index.md`)
- [ x ] My pull request targets the `master` branch of freeCodeCamp.
- [ x ] None of my changes are plagiarized from another source without proper attribution.
- [ x ] My article does not contain shortened URLs or affiliate links.

### CODE REVIEW

**Comment by RandellDawson** [comment]
Closed and Reopened this PR to attempt to resolve a specific Travis build failure.

**Comment by 0limpi0** [comment]
Should I make any changes? Is something wrong with the file?

**Comment by RandellDawson** [comment]
@0limpi0 We had a technical issue on our end, which is unrelated to your content. Before we could review your content, our system performs certain tests which were failing for something not in your control.  It has been resolved now.  There is a large backlog of PRs, so it will likely be another month before we actually review this PR.  Anyway, thank you for your contribution.

**Comment by lynxlynxlynx** [comment]
LGTM, but there's an older PR first in the queue. #21289

**Comment by RandellDawson** [comment]
@freeCodeCamp/portuguese-language-editors Can we get this PR reviewed to validate that the translation matches the current English version of the challenge?  If everything looks good but you need help with 
 resolving the merge conflict, just let me know. Thank you.

**Review by RandellDawson — APPROVED** [review]
LGTM

**Comment by RandellDawson** [comment]
Congrats @0limpi0  on your first pull request (PR)! 🎉

Thank you for your contribution to the page! 👍
We're happy to accept these changes, and look forward to future contributions. 📝

**Pull request merged**
