### PR TITLE
Added Punctuation and Clarified Information

### PR DESCRIPTION
**Pull request by RunsWithSquirrels**
I added a period to help make the article appear cleaner, as well as some further information with an already-established link to help clarify what the link tells the reader.

- [x] I have read [freeCodeCamp's contribution guidelines](https://github.com/freeCodeCamp/freeCodeCamp/blob/master/CONTRIBUTING.md).
- [x] My pull request has a descriptive title (not a vague title like `Update index.md`)
- [x] My pull request targets the `master` branch of freeCodeCamp.
- [x] None of my changes are plagiarized from another source without proper attribution.
- [x] My article does not contain shortened URLs or affiliate links.

If your pull request closes a GitHub issue, replace the XXXXX below with the issue number.

Closes #XXXXX

### CODE REVIEW

**Comment by RandellDawson** [comment]
Closed and Reopened this PR to attempt to resolve a specific Travis build failure.

**Review by cmccormack — APPROVED** [review]
Looks good to me, and congratulations on your first Pull Request!  🎉🎉🎉
We look forward to future contributions!

**Comment by METALMAN01** [comment]
I'm looking for some help

**Comment by RandellDawson** [comment]
@METALMAN01 If you need help with how to contribute visit https://gitter.im/FreeCodeCamp/Contributors.  If you need help with understanding/writing some code visit [the FCC forum](https://freecodecamp.org/forum).

**Pull request merged**
