### PR TITLE
fix(client): map progress ui

### PR DESCRIPTION
**Pull request by ahmaxed**
Checklist:

- [x] I have read [freeCodeCamp's contribution guidelines](https://contribute.freecodecamp.org).
- [x] My pull request has a descriptive title (not a vague title like `Update index.md`)
- [x] My pull request targets the `main` branch of freeCodeCamp.
- [x] I have tested these changes either locally on my machine, or GitPod.

Screenshot 2024-04-29 at 11 29 01 PM

### CODE REVIEW

**Review by naomi-lgbt — APPROVED** [review]

**Review by moT01 — COMMENTED** [review]
Thanks for jumping on this @ahmaxed. I gave it a quick look - here's what I see:

Firefox:
Screenshot 2024-04-29 at 9 45 31 PM

Safari:
Screenshot 2024-04-29 at 9 45 12 PM

Looks good in Chrome. I played with it a bit - couldn't quite get it right, but have some ideas. Let me know if you want to pair up on it for a bit. Since deployments are sort of blocked until we get this looking a little better, maybe it's okay to just have it look good in Chrome temporarily if we need to.

I also kind of feel like only the core curriculum needs the numbers. Not sure if we should just omit the icons for the rest - I think I would be fine with that - or we could maybe use some neutral icons, like just a circle without the number, and the ribbons if isCert

**Comment by ahmaxed** [comment]
We can definitely pair on it. I agree, the items outside of the curriculum set should not have numbers or arrows.

**Comment by ahmaxed** [comment]
Screenshot 2024-04-30 at 1 49 35 PM

**Comment by Sembauke** [comment]
The arrows seem no longer centred.

**Comment by moT01** [comment]
I added some logic to see if the user has completed all the challenges in a superblock - if so, the icon with the double circle shows up:

Screenshot 2024-04-30 at 11 51 46 AM

^
1: none
2: isCert
3: isCert & allChallengesCompleted
4: same as 2
5: allChallengesCompleted

**Comment by ahmaxed** [comment]
Tom's changes are LGMT.

**Review by ShaunSHamilton — APPROVED** [review]
LGTM 👍 

Though, the arrows do not look like arrows:
image

**Pull request merged**
