### PR TITLE
fix(curriculum): Allow both explicity and truthiness check for step 30 football team cards project

### LINKED ISSUE #52937: [Football Team Cards] Step 30 should clarify if truthiness check is expected
### Describe the Issue

The challenge asks the user to:

> use a ternary operator to check if `isCaptain` is true.

So the following code should pass:

```js
<h2>${name} ${isCaptain === true ? '(Captain)' : ''}</h2>
```

But the challenge only accepts truthiness check:

```js
<h2>${name} ${isCaptain ? '(Captain)' : ''}</h2>
```

### Affected Page

https://www.freecodecamp.org/learn/javascript-algorithms-and-data-structures-v8/learn-modern-javascript-methods-by-building-football-team-cards/step-30

### Expected behavior

I think either the instruction should be changed to:

> use a ternary operator to check if `isCaptain` is truthy.

Or the test should accept the explicit `=== true` check.

### PR DESCRIPTION
**Pull request by JamesCartar**
…for check

Checklist:

- [x] I have read and followed the [contribution guidelines](https://contribute.freecodecamp.org).
- [x] I have read and followed the [how to open a pull request guide](https://contribute.freecodecamp.org/#/how-to-open-a-pull-request).
- [x] My pull request targets the `main` branch of freeCodeCamp.
- [x] I have tested these changes either locally on my machine, or GitPod.

Closes #52937

Allowed both the explicit check and truthiness check in every languages folder for the JavaScript Algorithms and Data Structures (Beta), Learn Modern JavaScript Methods By Building Football Team Cards Step 30.

In JavaScript, both truthiness checks and explicit boolean checks are valid and commonly used. Allowing both types of checks in this challenge reflects real-world coding practices and provides learners with a more comprehensive understanding of JavaScript’s flexibility and nuances.

### Affected Page
(https://www.freecodecamp.org/learn/javascript-algorithms-and-data-structures-v8/learn-modern-javascript-methods-by-building-football-team-cards/step-30)

#### **_Before_**

first-explicity_truthiness_check_before

#### **_After_**

first-explicity_truthiness_check_after

### CODE REVIEW

**Comment by jdwilkin4** [comment]
You should not make changes to the non english files. 

Please revert your changes for all non english files and only update the tests for the english file
Thanks 👍

**Review by jdwilkin4 — APPROVED** [review]
tested both versions and it is working for me

**Comment by JamesCartar** [comment]
> tested both versions and it is working for me

Thank you

**Review by moT01 — APPROVED** [review]
LGTM @JamesCartar 🎉 Congratulations on your first contribution to the freeCodeCamp repo 🎉

**Pull request merged**
