### PR TITLE
fix(curriculum): wording change from "SVG canvas" to "SVG" in d3 course 

### LINKED ISSUE #49266: d3 step uses the phrase 'SVG canvas' half way through the course without any explanation
### Describe the Issue

About halfway through the D3 (data visualization with D3) course, we see the phrase "SVG canvas" for the first time on this page: https://www.freecodecamp.org/learn/data-visualization/data-visualization-with-d3/add-labels-to-d3-elements

However prior to this point the course only used the phrase 'SVG area' in reference to the space that the SVG takes up on the screen. No explanation was given in the step for what 'SVG canvas' is which was confusing to me as a translator (why a different word than before?) and as a Java developer who sees 'canvas' as a class for drawing. I did a quick google search for 'svg canvas' and all I got were results suggesting that these are different things.

I propose therefore that all occurrences of 'SVG canvas' be replaced with 'SVG area' in this step and following steps (it is mentioned again later several times). 

### Affected Page

https://www.freecodecamp.org/learn/data-visualization/data-visualization-with-d3/add-labels-to-d3-elements

### Your code

```

```

### Expected behavior

replace all occurrences of 'SVG canvas' with 'SVG area' in the D3 curriculum

### Screenshots

_No response_

### System

N/A

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by MikeJakuszewski**
Checklist:

- [X] I have read and followed the [contribution guidelines](https://contribute.freecodecamp.org).
- [X] I have read and followed the [how to open a pull request guide](https://contribute.freecodecamp.org/#/how-to-open-a-pull-request).
- [X] My pull request targets the `main` branch of freeCodeCamp.
- [X] I have tested these changes either locally on my machine, or GitPod.

Closes #49266

I changed from main branch, and made text changes from SVG canvas to SVG. Updated dictionaries to remove SVG canvas. These are the up-to-date changes that I made to improve my current PR from my previous PR.

### CODE REVIEW

**Comment by MikeJakuszewski** [comment]
If there is anything I could have done better, please let me know! Thank you.

**Comment by MikeJakuszewski** [comment]
These were the errors responses for the two failed test 
```
The comment
'Padding between the SVG canvas boundary and the plot'
does not appear in the comment dictionary.
When updating or adding a comment it must have the same text in the English challenges and the comment dictionary.

 ELIFECYCLE  Test failed. See above for more details.
```

Would you like me to update the other versions? Let me know how to proceed. Thank you.

**Comment by Sboonny** [comment]
No need to update other languages' version, but can you clean the changes in pnpm-lock and package.json?

**Comment by MikeJakuszewski** [comment]
Changes made. They are ready for review.

**Comment by lynxlynxlynx** [comment]
It's unfortunate, but there are already 4 unmergeable PRs in total for the same issue, seemingly identical in the end: https://github.com/freeCodeCamp/freeCodeCamp/pull/49684, https://github.com/freeCodeCamp/freeCodeCamp/pull/49686, https://github.com/freeCodeCamp/freeCodeCamp/pull/49688.

**Pull request closed without merging**
