### PR TITLE
fix(curriculum): update layout and styles, remove inline styles

### LINKED ISSUE #55542: Decimal to binary converter - Stack animation looks bad when default font is large
### Describe the Issue

Please see the video I made of the stack animation created by the end of the decimal to binary converter project.
The layout is quite messy in my view once the blocks start being displayed with an explanation.
If in agreement, it would be great to get a fix for it. Video: 

https://github.com/user-attachments/assets/abafcc3a-7a0d-42ef-95bc-f2c4fc6b6de0

 

Other thoughts which may or may not be welcome. The stack animation itself is not good. I think the blocks need to actually 'stack up' instead of being displayed as evenly spaced blocks in space. Something like this image: https://cdn.programiz.com/sites/tutorial2program/files/stack.png
What I like about the image shown is that the stack has edges (it looks like an open box that allows things to go into it)
I also like that the blocks are close together.

thanks for your attention

### Affected Page

https://www.freecodecamp.org/learn/javascript-algorithms-and-data-structures-v8/learn-recursion-by-building-a-decimal-to-binary-converter/step-109

### Your code

complete the expected step code and test the animation

### Expected behavior

neater display where blocks are not overlapping. Also preferably a type of 'container' line to represent the stack 'box'. Also the blocks should be closer together vertically.

### Screenshots

_No response_

### System

- Device: laptop
- OS: Windows 11 Pro Version 23H2 OS Build 22631.3880
- Browser: Chrome
- Version: 126.0.6478.127 (Official Build) (64-bit)

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by lasjorg**
Checklist:

- [x] I have read and followed the [contribution guidelines](https://contribute.freecodecamp.org).
- [x] I have read and followed the [how to open a pull request guide](https://contribute.freecodecamp.org/how-to-open-a-pull-request/).
- [x] My pull request targets the `main` branch of freeCodeCamp.
- [x] I have tested these changes either locally on my machine, or GitPod.

Closes #55542

Don't consider this a massive improvement, I do think it looks better. Tested with different browser zoom and font size.

It's a lot of changes for such a simple bug, but I think it is worth the update. Even if we could fix it with fewer changes, e.g. switch to rem for the margin and lower the values.

Separate commits to keep track of what I was doing.

Ran the `sync-i18n` script, but it messed with a bunch of unrelated files. For example, it deleted Odin project files from the Chinese and Arabic files, and made other changes to unrelated files including creating files (1507 changes in total). So I reverted it back. Not sure what the correct process is or if the docs for updating step based challenges is out of date.

Other PRs for this challenge are in progress, so it will end up with merge conflicts that need to be fixed.

---

Changes made:

1. Use flexbox for the call stack layout.

2. Created a box for the call stack and gave it a heading.

3. Added monospace font style, personal preference, but I think it fits the subject.

4. Removed the inline margin on call stack `p` elements and the related challenge step.

---

Edit: here is what it looks like

decimal-to-binary

### CODE REVIEW

**Comment by lasjorg** [comment]
Well, I might have jumped the shark on this. With very large fonts, there is an overflow on input-container at one point. I did move the MQ breakpoint, but I guess I didn't test it with very large fonts. Also, it is a little wonky when the text starts to wrap before the inputs stack. I should probably move the break point up to 590px so it stacks sooner.

**Comment by hbar1st** [comment]
wish list: should the stack have an open top? (no top border) and any chance the animation can move the blocks from the top to the bottom where they can rest? (like a more interesting animation). Just a wish list...

**Comment by lasjorg** [comment]
The stack can be open at the top, but most illustrations usually do not have that.

Adding animations would require more work. I'm guessing it would need to be done in the JS as part of the challenge. Adding it behind the scenes in pure CSS would be more difficult or have some potential timing jank.

**Review by moT01 — APPROVED** [review]
LGTM @lasjorg 👍

Correct me if any of this is wrong - here's some more context to the next reviewer:

The project starts users off with HTML and CSS boilerplate. This PR changes that boilerplate, which means the seed of each step needs the same boilerplate. That accounts for the majority of the changes in the diff. 

Since the boilerplate was adjusted to use different CSS, part of the JS that added inline styles wasn't needed...

Steps 84-86 added three news objects, each with a `marginTop` property and value, e.g: 

```
{
  marginTop: 300
}
```
 
That was removed from those three steps. So the seed from then on doesn’t have that property in the objects.

The use of those `marginTop` values was removed in the deleted step 95. e.g:
```
`<p style="margin-top: ${obj.marginTop}px;"></p>`
```

So the seed from then on doesn’t have that.

 The three files that have more than just seed code changes: 
64648534ff5498bee5dceb28.md - step 84
646486adf52652c0ee103aab.md - step 85
64648963e014f8c42a65b83a.md - step 86
(and step 95 was deleted)

**Comment by Sembauke** [comment]
@lasjorg Could you answer Tom's questions?

**Comment by lasjorg** [comment]
There are no questions. They asked for corrections, as such because I haven't corrected anything you can assume it is correct.

**Review by ojeytonwilliams — APPROVED** [review]
LGTM :+1:

**Pull request merged**
