### PR TITLE
fixed uncessary line breaks

### LINKED ISSUE #9554: Remove unnecessary spaces
#### Challenge Name

https://www.freecodecamp.com/challenges/iterate-over-arrays-with-map

#### Issue Description

There are unnecessary line breaks in "Iterate over Arrays with .map".

[This line](https://github.com/FreeCodeCamp/FreeCodeCamp/blob/78a1240f4f9a4c4ecf02ec30a871f4fdc64b83ee/seed/challenges/01-front-end-development-certification/object-oriented-and-functional-programming.json#L309) and [this line](https://github.com/FreeCodeCamp/FreeCodeCamp/blob/78a1240f4f9a4c4ecf02ec30a871f4fdc64b83ee/seed/challenges/01-front-end-development-certification/object-oriented-and-functional-programming.json#L341) need to be removed.

#### To Contributors

Please first read the [contributing guidelines](https://github.com/FreeCodeCamp/FreeCodeCamp/blob/staging/CONTRIBUTING.md) before taking care of this issue. And feel free to visit the [Contributors Help](https://gitter.im/FreeCodeCamp/HelpContributors) chat room if you have any questions about helping. We're there to help.

This issue is labeled as `first-timers-only` so only those who have never contributed to FreeCodeCamp's main repo can take up this issue.

#### Screenshot

**Now:**
image

**After:**
image

### PR DESCRIPTION
**Pull request by dkat90**
#### Pre-Submission Checklist

- [x] Your pull request targets the `staging` branch of FreeCodeCamp.
- [x] Branch starts with either `fix/`, `feature/`, or `translate/` (e.g. `fix/signin-issue`)
- [x] You have only one commit (if not, [squash](https://github.com/FreeCodeCamp/FreeCodeCamp/wiki/Git-Squash) them into one commit).
- [x] All new and existing tests pass the command `npm run test-challenges`. Use `git commit --amend` to amend any fixes.
#### Type of Change

- [x] Small bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds new functionality)
- [ ] Breaking change (fix or feature that would change existing functionality)
- [ ] Add new translation (feature adding new translations)
#### Checklist:

- [x] Tested changes locally.
- [x] Closes currently open issue: Closes #9554

### CODE REVIEW

**Comment by dkat90** [comment]
fixed uneccessary line breaks in issue #9554

**Comment by erictleung** [comment]
@dkat90 looks good to me but can you put or edit your PR message's last checkbox to have `Closes #9554`? This will autoclose the issue when your PR is merged. Thanks!

**Comment by dkat90** [comment]
Hey Eric,
Thanks so much for accepting my pull request!I'll fix it as soon as I get the chance.

Warmest regards,
David Ken

On Tue, Jul 05, 2016 at 10:39 AM, Eric Leung < notifications@github.com [notifications@github.com] > wrote:
@dkat90 [https://github.com/dkat90] looks good to me but can you put or edit your PR message's last checkbox to have Closes #9554 ? This will autoclose the issue when your PR is merged. Thanks!

**Comment by dkat90** [comment]
Done!

**Comment by erictleung** [comment]
@dkat90 thanks for your efforts but I don't see any changes. To make the change of adding `Closes #9554`, you'll need to visit the GitHub site where your PR is. So you'll need to go to https://github.com/FreeCodeCamp/FreeCodeCamp/pull/9556 and edit your PR commit message where it says 

> Closes currently open issue (replace XXXX with an issue no): Closes #XXXX

Let me know if you have any questions. Thanks again!

**Comment by dkat90** [comment]
Hey Eric! I think it shows up correctly now! I don't know what happened to my edits, I'm really sorry about that!

**Comment by atjonathan** [comment]
#### :sparkles: :sparkles: **LGTM :+1:** :sparkles: :sparkles: 

:tada: Thanks for contributing @dkat90 and congratulations on your first PR submission to FreeCodeCamp! :tada:

**Pull request merged**
