### PR TITLE
Replace Github -> GitHub (Portuguese)

### PR DESCRIPTION
**Pull request by lipis**
- [x] I have read [freeCodeCamp's contribution guidelines](https://github.com/freeCodeCamp/freeCodeCamp/blob/master/CONTRIBUTING.md).
- [x] My pull request has a descriptive title (not a vague title like `Update index.md`)
- [x] My pull request targets the `master` branch of freeCodeCamp.
- [x] None of my changes are plagiarized from another source without proper attribution.
- [x] All the files I changed are in the same world language (for example: only English changes, or only Chinese changes, etc.)
- [x] My changes do not use shortened URLs or affiliate links.

Closes #XXXXX

### CODE REVIEW

**Comment by RandellDawson** [comment]
@thefrontendwizard, @fabiotp91, @marceloazambuja, or @jefferson2z The following earlier PRs need to be reviewed (closed/merged/changes requested) before I even attempt to merge this current PR which is only changing `Github` to `GitHub`, so I can fix all merge conflicts in one shot.  This PR touches many files and I want to try and get it merged.

Could any of you please review these as soon as you can?

**NOTE:**  Some of these PRs have merge conflicts.  If you need any help resolving them, please let me know and I can try to help.

https://github.com/freeCodeCamp/freeCodeCamp/pull/22936
https://github.com/freeCodeCamp/freeCodeCamp/pull/24842
https://github.com/freeCodeCamp/freeCodeCamp/pull/28920
https://github.com/freeCodeCamp/freeCodeCamp/pull/29877
https://github.com/freeCodeCamp/freeCodeCamp/pull/30638
https://github.com/freeCodeCamp/freeCodeCamp/pull/31737
https://github.com/freeCodeCamp/freeCodeCamp/pull/32256

Thank you

**Comment by fabiotp91** [comment]
I have checked every PR and reviewed it, the conflicts are unfortunately out of my scope, but all the translations have been reviewed, some have been asked for changes.

**Comment by RandellDawson** [comment]
@fabiotp91 One last thing.  I need your assistance in resolve 1 of the 4 merge conflicts. 

Which of the following is the better translation?
```
Depois disso, toda uma gama de validadores de tipo podem ser usados para garantir que os dados que o desenvolvedor receberá realmente sejam válidos. Quando um valor inválido é fornecido, haverá um aviso aparecendo no console do JavaScript.

Observe que, por motivos de desempenho, os propTypes definidos são verificados apenas no modo de desenvolvimento.

Também, ao contrário do estado do componente, que pode ser manipulado conforme necessário, essas propriedades (props) são somente leitura.
```
OR
```
Depois disso, toda uma gama de validadores que podem ser usados ​​para garantir que os dados que o desenvolvedor receberá realmente sejam válidos. Quando um valor inválido é fornecido, haverá um aviso aparecendo no console do JavaScript.

Observe que, por motivos de desempenho, os propTypes definidos são verificados apenas no modo de desenvolvimento.

Também, ao contrário do estado do componente, que pode ser manipulado conforme necessário, esses suportes são somente leitura.
```

**Comment by fabiotp91** [comment]
I really think both have the same mistake, translating "validadores de tipo" and "validadores" sounds like something related to JavaScript, but the first one looks better because we can't translate directly everything because it wont make sense.

Simple example: 
Table can be translated to tábela ou mesa
Tábela = Mathematycal Table 
Mesa = Furniture Table

**Comment by RandellDawson** [comment]
@fabiotp91 OK, I went with the first one.  Thank you very much for reviewing all of these so quickly.  It is really appreciated.

**Comment by RandellDawson** [comment]
Thank you for your contribution to the page! 👍
We're happy to accept these changes, and look forward to future contributions. 🎉

**Pull request merged**
