### PR TITLE
Fixed Typographical Error in guide/english/react/index.md

### PR DESCRIPTION
**Pull request by iamrajiv**
- [x] I have read [freeCodeCamp's contribution guidelines](https://github.com/freeCodeCamp/freeCodeCamp/blob/master/CONTRIBUTING.md).
- [x] My pull request has a descriptive title (not a vague title like `Update index.md`)
- [x] My pull request targets the `master` branch of freeCodeCamp.
- [x] None of my changes are plagiarized from another source without proper attribution.
- [x] All the files I changed are in the same world language (for example: only English changes, or only Chinese changes, etc.)
- [x] My changes do not use shortened URLs or affiliate links.

### CODE REVIEW

**Review by thecodingaviator — CHANGES_REQUESTED** [review]
Please do the required changes

**Comment by iamrajiv** [comment]
thank you for guidance @thecodingaviator

**Comment by thecodingaviator** [comment]
Although this Pr is good, I think the whole article would need a re-write from a third person perspective. Right now it is using `our`, `your`, we need to change it to `the`, etc.

**Comment by iamrajiv** [comment]
can I take these issues to re-write this whole article in third person perspective if possible @thecodingaviator

**Comment by thecodingaviator** [comment]
@iamrajiv Feel free to

**Comment by RandellDawson** [comment]
@iamrajiv , @thecodingaviator Per the [Styling guidelines](https://github.com/freeCodeCamp/freeCodeCamp/blob/master/docs/style-guide-for-guide-articles.md#point-of-view), articles should be written from the `second person` point of view, to give a conversational tone.

**Comment by thecodingaviator** [comment]
I'm sorry. I meant second person. There are some third person views in the article. I always mess them up :p

**Comment by iamrajiv** [comment]
is this PR good to merged @RandellDawson

**Review by RandellDawson — CHANGES_REQUESTED** [review]
I have suggested several changes that should improve the readability of this article.  I did not mark all the changes and it would be great if you could actually rewrite the article in second-person (you vs I or we). 
 See the following for examples of what would need to be changed throughout the rest of this article. 

* `we` => `you`
* `we're` => `you're`
* `our(s)` => `your(s)`

**Comment by iamrajiv** [comment]
thank you for guidance @RandellDawson I have made a new PR #35187 because by mistake I have deleted the branch file of PR #34893. In PR #35187 I have implemented your suggestions can you review it

**Comment by iamrajiv** [comment]
thank you for guidance @RandellDawson I have made a new PR #35187 because by mistake I have deleted the branch file of PR #34893. In PR #35187 I have implemented your suggestions can you review it. Now I am going to close this PR

**Pull request closed without merging**
