### PR TITLE
fix(seed): update test for create a bootstrap button

### LINKED ISSUE #16763: Incorrect answer accepted and passed for challenge: Create a Bootstrap Button
#### Challenge Name

https://www.freecodecamp.org/challenges/create-a-bootstrap-button

#### Issue Description

I rushed and misread the question and instead of creating a new button as requested I merely edited the existing button and it passed the checks. Realised in next challenge my mistake.

#### Browser Information

* Browser Name, Version: chrome v.64
* Operating System: Linux Mint
* Mobile, Desktop, or Tablet: 

#### Your Code

```html

<link href="https://fonts.googleapis.com/css?family=Lobster" rel="stylesheet" type="text/css">
<style>
  .red-text {
    color: red;
  }

  h2 {
    font-family: Lobster, Monospace;
  }

  p {
    font-size: 16px;
    font-family: Monospace;
  }

  .thick-green-border {
    border-color: green;
    border-width: 10px;
    border-style: solid;
    border-radius: 50%;
  }

  .smaller-image {
    width: 100px;
  }
</style>

<div class="container-fluid">
  <h2 class="red-text text-center">CatPhotoApp</h2>

  <p>Click here for <a href="#">cat photos</a>.</p>

  <a href="#"><img class="smaller-image thick-green-border" src="https://bit.ly/fcc-relaxing-cat" alt="A cute orange cat lying on its back. "></a>

  <img src="https://bit.ly/fcc-running-cats" class="img-responsive" alt="Three kittens running towards the camera. ">

  <p>Things cats love:</p>
  <ul>
    <li>cat nip</li>
    <li>laser pointers</li>
    <li>lasagna</li>
  </ul>
  <p>Top 3 things cats hate:</p>
  <ol>
    <li>flea treatment</li>
    <li>thunder</li>
    <li>other cats</li>
  </ol>
  <form action="/submit-cat-photo">
    <label><input type="radio" name="indoor-outdoor"> Indoor</label>
    <label><input type="radio" name="indoor-outdoor"> Outdoor</label>
    <label><input type="checkbox" name="personality"> Loving</label>
    <label><input type="checkbox" name="personality"> Lazy</label>
    <label><input type="checkbox" name="personality"> Crazy</label>
    <input type="text" placeholder="cat photo URL" required>
    <button type="submit" class="btn">Like</button>
  </form>
</div>


```

### PR DESCRIPTION
**Pull request by gondar00**
#### Pre-Submission Checklist

- [x] Your pull request targets the `staging` branch of freeCodeCamp.
- [x] Branch starts with either `fix/`, `feature/`, or `translate/` (e.g. `fix/signin-issue`)
- [x] You have only one commit (if not, [squash](http://forum.freecodecamp.org/t/how-to-squash-multiple-commits-into-one-with-git/13231) them into one commit).
- [x] All new and existing tests pass the command `npm test`. Use `git commit --amend` to amend any fixes.

#### Type of Change

- [x] Small bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds new functionality)
- [ ] Breaking change (fix or feature that would change existing functionality)
- [ ] Add new translation (feature adding new translations)

#### Checklist:

- [x] Tested changes locally.
- [x] Addressed currently open issue (replace XXXXX with an issue no in next line)
 
Closes #16763 

#### Description

Added a test case to check that the length of the buttons present is equal to `two` as the challenge was being accepted even without adding a new button.

### CODE REVIEW

**Comment by mstellaluna** [comment]
I am currently working on this PR

**Comment by mstellaluna** [comment]
I am currently reviewing this PR

**Review by mstellaluna — CHANGES_REQUESTED** [review]
Test fail on "Create a new button element with the text "Like"

**Comment by mstellaluna** [comment]
@gondar00 Hello. I have reviewed your PR and it does correct the issue of the btn class and Like text being accidentally applied to the submit button BUT if you were to create a new button, it does not recognize the new button being created and the test fails. 
image

**Comment by gondar00** [comment]
@mstellaluna hello, i have updated the pull request, please take a look

**Comment by mstellaluna** [comment]
I am currently working on this PR

**Review by mstellaluna — APPROVED** [review]

**Comment by mstellaluna** [comment]
@gondar00 The changes looks great to me ! I will go ahead and approve this request. Thank you for contributing. Happy Coding !

**Pull request merged**
