### PR TITLE
Improved grammar and message

### PR DESCRIPTION
**Pull request by JustinBen-Tzioni**
- [x] I have read [freeCodeCamp's contribution guidelines](https://github.com/freeCodeCamp/freeCodeCamp/blob/master/CONTRIBUTING.md).
- [x] My pull request has a descriptive title (not a vague title like `Update index.md`)
- [x] My pull request targets the `master` branch of freeCodeCamp.
- [x] None of my changes are plagiarized from another source without proper attribution.
- [x] My article does not contain shortened URLs or affiliate links.

If your pull request closes a GitHub issue, replace the XXXXX below with the issue number.

Closes #XXXXX

### CODE REVIEW

**Comment by RandellDawson** [comment]
LGTM

**Comment by RandellDawson** [comment]
Closed and Reopened this PR in an attempt to attempt to break out of the Travis build pending status.

**Review by paulywill — CHANGES_REQUESTED** [review]
not part of PR...but should capitalize "Internet" if using a definite article "the Internet".  

"There are many sources for web fonts on the Internet. For this example we will focus on the Google Fonts library."

**Review by paulywill — APPROVED** [review]

**Comment by RandellDawson** [comment]
Thank you for your contribution to the page! 👍
We're happy to accept these changes, and look forward to future contributions. 🎉

**Pull request merged**
