### PR TITLE
Fix Grammar Issue in Make Instances of Objects

### LINKED ISSUE #4172: Tiny typo in Waypoint: Make Instances of Objects with a Constructor Function instructions
In the first paragraph, "many copies of an objects" should be "many copies of an object" (object should be singular).

link: http://www.freecodecamp.com/challenges/waypoint-make-instances-of-objects-with-a-constructor-function

screen cap:
fcctypo

### PR DESCRIPTION
**Pull request by SaintPeter**
Fixes #4172

Grammar is hard.

### CODE REVIEW

**Comment by awesomeaniruddh** [comment]
Please remove the issue number from the title. Thanks!

**Comment by ltegman** [comment]
Grammar **is** hard, so excuse me if I'm wrong about this, but I don't think the verb "shares" makes sense here instead of "share". My understanding is that the verb "shares" should only be used in the third-person singular present, which this wouldn't be since the subject we're talking about with the action "share" is plural and not singular ("many copies").

**Comment by awesomeaniruddh** [comment]
@ltegman Yep, `share` seems to make more sense here.

**Comment by SaintPeter** [comment]
My current text is:
`Sometimes you'll want to be able to easily create many copies of an object that shares the same methods.`

You are creating many copies of an object (singular), which shares (plural) the same methods (plural).

I'm not sure that this:
`Sometimes you'll want to be able to easily create many copies of an object that share the same methods.` sounds right to me.

Maybe we need to kill it with fire and rewrite the whole sentence less awkwardly?

**Comment by ltegman** [comment]
I think a less awkward rewrite of the sentence may be in order!

**Comment by BerkeleyTrue** [comment]
How about.

"Sometimes you'll want to create many copies of an object and each copy should share the same methods."

**Comment by SaintPeter** [comment]
Will this be superseeded by @ltegman's other proposed patch?  If so, let's just close this one out.  I think his overall wording is superior.

**Comment by BerkeleyTrue** [comment]
@SaintPeter Let's go with Logan's patch.

Happy Coding!

**Pull request closed without merging**
