### PR TITLE
fix: do not show progress and checkbox on learn if not logged in

### LINKED ISSUE #37930: No need for number of challenges and check if not logged in
> https://github.com/freeCodeCamp/freeCodeCamp/issues/37878#issuecomment-565677329

### PR DESCRIPTION
**Pull request by thecodingaviator**
- [x] I have read [freeCodeCamp's contribution guidelines](https://github.com/freeCodeCamp/freeCodeCamp/blob/master/CONTRIBUTING.md).
- [x] My pull request has a descriptive title (not a vague title like `Update index.md`)
- [x] My pull request targets the `master` branch of freeCodeCamp.
- [x] None of my changes are plagiarized from another source without proper attribution.
- [x] All the files I changed are in the same world language (for example: only English changes, or only Chinese changes, etc.)
- [x] My changes do not use shortened URLs or affiliate links.

Closes #37930

### CODE REVIEW

**Comment by RandellDawson** [comment]
@thecodingaviator Make sure you are running `npm run test` before creating a PR, to make sure everything works locally first.

**Comment by thecodingaviator** [comment]
@RandellDawson I try to do that. My machine just doesn't finish the scripts. Trying Docker.

**Comment by thecodingaviator** [comment]
@raisedadead @ojeytonwilliams How does this PR look now?

**Review by ojeytonwilliams — APPROVED** [review]
The code looks good!  For future reference, before this PR:
image

and after:
image

One thing I did notice is that after this PR there will be no visual difference between an intro and a challenge.  However, if we're planning to remove the intros, this should not matter.

**Comment by raisedadead** [comment]
See https://github.com/freeCodeCamp/freeCodeCamp/issues/37878#issuecomment-565996667

**Pull request closed without merging**
