### PR TITLE
fix(curriculum): slighly faster soln for euler47

### PR DESCRIPTION
**Pull request by jeremylt**
Checklist:

- [x] I have read [freeCodeCamp's contribution guidelines](https://contribute.freecodecamp.org).
- [x] My pull request has a descriptive title (not a vague title like `Update index.md`)
- [x] My pull request targets the `main` branch of freeCodeCamp.
- [x] I have tested these changes either locally on my machine, or GitPod.

Closes N/A

I don't think this can really get much faster. 

For my own knowledge, is the code defining the solution only run once? That would make a speed difference here.

### CODE REVIEW

**Review by Sboonny — APPROVED** [review]
Although it doesn't close an issue, it does help with contributing to #40896 

LGTM 🎉

**Review by moT01 — APPROVED** [review]
LGTM 🎉 

Not quite sure exactly what you're doing @jeremylt, but you're pushing your branches right to freeCodeCamp or something and they are showing up there:
Screen Shot 2022-06-16 at 7 38 34 AM
It's not a big deal, but I think you should typically push branches to your fork and create a PR from that.

Are you satisfied with this @gikf?

**Review by gikf — APPROVED** [review]
LGTM :+1:

**Comment by jeremylt** [comment]
Ah, I see what's happening.. I'm mixing workflows from tow different projects. I'll shift to the forking workflow.

**Pull request merged**
