### PR TITLE
fix(curriculum): Edit the title of Project Euler Problem 283

### LINKED ISSUE #44297: Mistake in the title of Project Euler Problem 283, "area * perimeter" should be "area / perimeter"
The current title is:
"Problem 283: Integer sided triangles for which the area * perimeter ratio is integral"

But it should be:
"Problem 283: Integer sided triangles for which the area / perimeter ratio is integral"

It is "/" on Project Euler's official site: https://projecteuler.net/problem=283

## Affected page

Coding Interview Prep > Project Euler > Problem 283: Integer sided triangles for which the area * perimeter ratio is integral
https://www.freecodecamp.org/learn/coding-interview-prep/project-euler/problem-283-integer-sided-triangles-for-which-the-area--perimeter-ratio-is-integral

## Expected behavior

The title should be:
"Problem 283: Integer sided triangles for which the area / perimeter ratio is integral"

## System

- Device: Laptop
- OS: Windows 10
- Browser: chrome
- Version: 96.0.4664.45

## Additional context

Originally reported in a comment on Crowdin
https://freecodecamp.crowdin.com/translate/690087755819f2f67b26dbee3be0eb53/21380/en-ja/132?filter=basic&value=17#q=630728

### PR DESCRIPTION
**Pull request by ghost**
Checklist:

- [x] I have read [freeCodeCamp's contribution guidelines](https://contribute.freecodecamp.org).
- [x] My pull request has a descriptive title (not a vague title like `Update index.md`)
- [x] My pull request targets the `main` branch of freeCodeCamp.
- [x] I have tested these changes either locally on my machine, or GitPod.

Closes #44297

### CODE REVIEW

**Comment by gikf** [comment]
Hey @najmieh

title of challenge needs to be changed in the `meta.json` file as well - https://github.com/freeCodeCamp/freeCodeCamp/blob/main/curriculum/challenges/_meta/project-euler/meta.json - as it can be seen in the details how challenge can be renamed - https://contribute.freecodecamp.org/#/curriculum-file-structure?id=renaming-a-challenge. Note that with this change `dashedName` stays the same.

**Comment by najmieh** [comment]
> Hey @najmieh
> 
> title of challenge needs to be changed in the `meta.json` file as well - https://github.com/freeCodeCamp/freeCodeCamp/blob/main/curriculum/challenges/_meta/project-euler/meta.json - as it can be seen in the details how challenge can be renamed - https://contribute.freecodecamp.org/#/curriculum-file-structure?id=renaming-a-challenge. Note that with this change `dashedName` stays the same.

Ok, I edit that as well. Thank you for the review.

**Comment by najmieh** [comment]
@gikf can you review the changes and tell me if everything is alright. Thank you in advance.

**Comment by gikf** [comment]
@najmieh I don't see any new change in this PR, did you add it to the correct branch?

**Comment by najmieh** [comment]
> @najmieh I don't see any new change in this PR, did you add it to the correct branch?

I added a new PR :/

**Review by gikf — APPROVED** [review]
Looks good :+1:

**Review by naomi-lgbt — APPROVED** [review]
This looks good to me.

**Comment by najmieh** [comment]
> Congrats on your first pull request (PR)! 🎉
> 
> Thank you for your contribution to the page! 👍 We are happy to accept these changes and look forward to future contributions. 📝

Thank YOU ^^ :) 
I appreciate it.

**Pull request merged**
