### PR TITLE
Added test case to Bonfire Drop it

### PR DESCRIPTION
**Pull request by alan1001110**

### CODE REVIEW

**Comment by alan1001110** [comment]
To close #4741

**Comment by alan1001110** [comment]
semi-colon...

**Comment by alan1001110** [comment]
I made a typo, but don't know why that would affect the Travis CI build. :(

**Comment by ltegman** [comment]
The travis CI build runs a test that checks if the solution provided for a problem will pass all the tests, which will also catch syntax errors without your tests. It looks like you're missing a comma between what the expected result is and the message. The message also doesn't quite match the test you're running.

Once you've fixed this please [squash all your commits into one](https://github.com/FreeCodeCamp/FreeCodeCamp/wiki/git-rebase#squashing-multiple-commits-into-one). Thanks! :smile:

**Comment by alan1001110** [comment]
Thanks for the direction @ltegman, and for putting up with my messy first PR attempt.

**Comment by ltegman** [comment]
Not a problem -- everyone's first PR has some growing pains!

**Comment by alan1001110** [comment]
Wish I'd checked my work better the first time. Now can't figure out git/Github enough to make it work. 
:(

**Comment by ltegman** [comment]
@alan1001110 What issues are you experiencing? I'm happy to help you out on Gitter if you want to message me. Another option is to delete this PR and open a new one on a new branch that only has one correct commit. If you go that route please name your branch according to the [Contribution Guide](https://github.com/FreeCodeCamp/FreeCodeCamp/wiki/Pull-Request-Contribute).

**Comment by alan1001110** [comment]
@ltegman I had a few issues and I probably need to start by learning more about git.   I'll have a little free time this Sunday morning, so I'll do some reading then and ask you any remaining questions afterwards.  My goal is to only take 2 minutes of your time rather than 20.   :-)

**Comment by SaintPeter** [comment]
@alan1001110 If you need help: https://gitter.im/FreeCodeCamp/HelpContributors

**Pull request closed without merging**
