### PR TITLE
fix(curriculum): Add missing quote in Python list example

### LINKED ISSUE #56273: String is missing a quote
In this paragraph in the code block the string `Twice` is missing a quote:

https://github.com/freeCodeCamp/freeCodeCamp/blob/945504d9e0ab681bfca675d5f16545f285853e40/curriculum/challenges/english/07-scientific-computing-with-python/learn-lambda-functions-by-building-an-expense-tracker/66694bfa435cef241f6f9a68.md#L21

---

This looks like something that can be fixed by "first-time" code contributors to this repository. THe file you should be looking at to work on a fix is the one linked above.

Please make sure you read our [guidelines for contributing](https://contribute.freecodecamp.org/#/), we prioritize contributors following the instructions in our guides. Join us in our [chat room](https://discord.gg/PRyKn3Vbay) or our [forum](https://forum.freecodecamp.org/c/contributors/3) if you need help contributing; our moderators will guide you through this.

Sometimes we may get more than one pull request. We typically accept the most quality contribution followed by the one that is made first.

Happy contributing.

### PR DESCRIPTION
**Pull request by patchmyday**
Checklist:

- [x] I have read and followed the [contribution guidelines](https://contribute.freecodecamp.org).
- [x] I have read and followed the [how to open a pull request guide](https://contribute.freecodecamp.org/how-to-open-a-pull-request/).
- [x] My pull request targets the `main` branch of freeCodeCamp.
- [x] I have tested these changes either locally on my machine, or GitPod.

Closes #56273 

This PR fixes a typo in the Python list example in the lambda functions lesson. 
A missing quotation mark was added to correctly format the nested list example.

### CODE REVIEW

**Comment by gikf** [comment]
Hey @DFwJZ,

Is this PR related to some existing issue, which should be closed by this PR? If so, please link it correctly.

Here's the pull request template for reference
```
Checklist:

<!-- Please follow this checklist and put an x in each of the boxes, like this: [x]. It will ensure that our team takes your pull request seriously. -->

- [ ] I have read and followed the [contribution guidelines](https://contribute.freecodecamp.org).
- [ ] I have read and followed the [how to open a pull request guide](https://contribute.freecodecamp.org/how-to-open-a-pull-request/).
- [ ] My pull request targets the `main` branch of freeCodeCamp.
- [ ] I have tested these changes either locally on my machine, or GitPod.

<!--If your pull request closes a GitHub issue, replace the XXXXX below with the issue number.-->

Closes #XXXXX

<!-- Feel free to add any additional description of changes below this line -->
```

**Comment by DFwJZ** [comment]
Thank you, just updated.

**Review by majestic-owl448 — APPROVED** [review]
Thank you for opening this PR!

LGTM 👍 (Looks Good To Me)

**Review by gikf — APPROVED** [review]

**Comment by ilenia-magoni** [comment]
Hi @DFwJZ. Congrats on your first pull request (PR)! 🎉

Thank you for your contribution to the page! 👍
We are happy to accept these changes and look forward to future contributions. 📝

**Pull request merged**
