### PR TITLE
Add keyboard shortcut for commenting back in

### PR DESCRIPTION
**Pull request by systimotic**
#### Pre-Submission Checklist

- [x] Your pull request targets the `staging` branch of FreeCodeCamp.
- [x] Branch starts with either `fix/`, `feature/`, or `translate/` (e.g. `fix/signin-issue`)
- [x] You have only one commit (if not, [squash](http://forum.freecodecamp.com/t/how-to-squash-multiple-commits-into-one-with-git/13231) them into one commit).
- [x] All new and existing tests pass the command `npm run test-challenges`. Use `git commit --amend` to amend any fixes.
#### Type of Change

- [x] Small bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds new functionality)
- [ ] Breaking change (fix or feature that would change existing functionality)
- [ ] Add new translation (feature adding new translations)
#### Checklist:

- [x] Tested changes locally.
- [ ] Closes currently open issue (replace XXXX with an issue no): Closes #XXXX
#### Description

On the live site, pressing Ctrl or Cmd + / comments and uncomments the code. I really love this feature. This functionality is no longer present in the beta. I did a little bit of git-digging, but I wasn't able to find where it disappeared. I decided to try to add it back in, and see if it would work. Surprisingly, it worked fine! Credits to @gangachris for originally adding this in #9854 👍 
_Edit: I wasn't sure whether this was a feature or a fix._

### CODE REVIEW

**Comment by shojaala** [comment]
cb67150

**Comment by shojaala** [comment]
cb67150

**Comment by Bouncey** [comment]
The changes look good, I will pull this done shortly to test.

**Comment by Bouncey** [comment]
## LGTM :+1: 

Thanks for contributing :tada:

**Pull request merged**
