### PR TITLE
fix(curriculum): replace flaky solution

### LINKED ISSUE #53140: Flaky test in Project Euler Problem 84
## Describe the bug

A test of Project Euler Problem 84 failed randomly in CI:

Screenshot 2024-01-12 at 14 26 58

The failure can be seen here: https://github.com/freeCodeCamp/freeCodeCamp/actions/runs/7498904426/job/20414989793?pr=52980.

## Affected page

- Challenge page: https://www.freecodecamp.org/learn/project-euler/project-euler-problems-1-to-100/problem-84-monopoly-odds
- Challenge file: https://github.com/freeCodeCamp/freeCodeCamp/blob/main/curriculum/challenges/english/18-project-euler/project-euler-problems-1-to-100/problem-84-monopoly-odds.md

## Steps to reproduce

Running `test:curriculum` multiple times on the challenge.

## Expected behavior

The test should always pass.

### PR DESCRIPTION
**Pull request by gikf**
Checklist:

- [x] I have read and followed the [contribution guidelines](https://contribute.freecodecamp.org).
- [x] I have read and followed the [how to open a pull request guide](https://contribute.freecodecamp.org/#/how-to-open-a-pull-request).
- [x] My pull request targets the `main` branch of freeCodeCamp.
- [x] I have tested these changes either locally on my machine, or GitPod.

Closes #53140

- - -
- Changes solution to one using Markov chain.
- Improves solution result consistency and efficiency (I'm seeing 4x-25x speedup depending on test case).
- Don't hesitate to ask if something isn't clear. I can't promise I will be able to explain all the math  behind it, but what's happening - yes.

### CODE REVIEW

**Review by moT01 — APPROVED** [review]
LGTM ❓🙃 🎉 

Did you write this @gikf?

**Comment by gikf** [comment]
@moT01,
 
Yeah, any concerns?

**Comment by moT01** [comment]
nope. It just looks impressive.

**Comment by gikf** [comment]
🚀 As noted in comment this is based on https://github.com/ByteThisCoding/project-euler/blob/master/problems/0084/0084.ts. It does all the heavy lifting as far as the math behind it.

**Review by jdwilkin4 — APPROVED** [review]

**Pull request merged**
