### PR TITLE
feat: add script to remove unused curriculum files

### PR DESCRIPTION
**Pull request by moT01**
When english challenges are removed, the crowdin sync doesn't remove the i18n files. This removes them.

Checklist:

- [x] I have read and followed the [contribution guidelines](https://contribute.freecodecamp.org).
- [x] I have read and followed the [how to open a pull request guide](https://contribute.freecodecamp.org/#/how-to-open-a-pull-request).
- [x] My pull request targets the `main` branch of freeCodeCamp.
- [x] I have tested these changes either locally on my machine, or GitPod.

Closes #XXXXX

### CODE REVIEW

**Review by raisedadead — CHANGES_REQUESTED** [review]
We usually use npm run-script entry for these things. It would also be nicer to have a GitHub workflow that can take care of running this once a day after the Crowdin PRs come in.

**Comment by moT01** [comment]
I know, but this was easier for me. It could probably just be part of the download action.

**Comment by raisedadead** [comment]
> I know, but this was easier for me. It could probably just be part of the download action.

Sorry - I meant there should be npm run-script shortcut to run the nodejs script and it should then be included in one of the actions or have a dedicated workflow.

**Comment by naomi-lgbt** [comment]
https://github.com/freeCodeCamp/crowdin-action/blob/main/src/plugins/remove-deleted-files.ts

Our crowdin action does have a plugin for this

**Comment by raisedadead** [comment]
So - we do not need this @naomi-lgbt?

**Pull request closed without merging**
