### PR TITLE
fix(curriculum): update instructions

### PR DESCRIPTION
**Pull request by DaVicki**
Checklist:

- [x] I have read [freeCodeCamp's contribution guidelines](https://contribute.freecodecamp.org).
- [x] My pull request has a descriptive title (not a vague title like `Update index.md`)
- [x] My pull request targets the `master` branch of freeCodeCamp.
- [x] All the files I changed are in the same world language, for example: only English changes, or only Chinese changes, etc.

Closes #XXXXX

edited text - change "returns a random number" to "returns a random whole number" to be more clear on the problem statement.

### CODE REVIEW

**Comment by Sky020** [comment]
This is a useful change, but before we _review_ this PR, let use hear from another contributor.

**Comment by erictleung** [comment]
I do like the change. And it becomes consistent with the challenge title.

Things I might change would be making the rest of the challenge somehow mention whole numbers as well, or at least somewhere in the first part of the challenge.

**Review by jordanliu — APPROVED** [review]
-see below-

**Review by jordanliu — COMMENTED** [review]
as @erictleung mentioned, you could probably modify the rest of the challenge to include the keyword, such as the description

**Review by ShaunSHamilton — APPROVED** [review]
LGTM 👍

**Comment by DaVicki** [comment]
Let me know if there's anything else needed to merge my commit.

**Comment by ojeytonwilliams** [comment]
@DaVicki  Congrats on your first pull request (PR)! 🎉

Thank you for your contribution to the page! 👍
We're happy to accept these changes, and look forward to future contributions. 📝

**Pull request merged**
