### PR TITLE
fix(curriculum): update test of TODO step 6 to allow for multiple function answers

### LINKED ISSUE #54347: step-6 of todo app in new Js Curriculum has issues
### Describe the Issue

It only passes when someone uses es6 arrow function while doesn't pass when anyone uses regular function, plus, its not mentioned clearly which function to use 
image

### Affected Page

https://www.freecodecamp.org/learn/javascript-algorithms-and-data-structures-v8/learn-localstorage-by-building-a-todo-app/step-6

### Your code

```
openTaskFormBtn.addEventListener("click", function(){
taskForm.classList.toggle("hidden")
}
);
```

### Expected behavior

openTaskFormBtn.addEventListener("click", () =>
  taskForm.classList.toggle("hidden")
);

### Screenshots

_No response_

### System

- Device: [e.g. iPhone 6, Laptop]
- OS: [e.g. iOS 14, Windows 10, Ubuntu 20.04]
- Browser: [e.g. Chrome, Safari]
- Version: [e.g. 22]

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by Supravisor**
Checklist:

- [x] I have read and followed the [contribution guidelines](https://contribute.freecodecamp.org).
- [x] I have read and followed the [how to open a pull request guide](https://contribute.freecodecamp.org/#/how-to-open-a-pull-request).
- [x] My pull request targets the `main` branch of freeCodeCamp.
- [x] I have tested these changes either locally on my machine, or GitPod.

Closes #54347

Passes regular function
image

Also arrow function
image

### CODE REVIEW

**Comment by jdwilkin4** [comment]
It looks like a few a automated tests are failing.
Please look into those tests and resolve the issues but a review can be done.
Thanks

**Comment by Ksound22** [comment]
Both the function keyword and arrow function syntax are not working: 
arrow-syntax-not-working

function-keyword-not-working

Your regex also didn't match any of the possible solutions:
regex-didnt-match-any-possible-solution

That's the reason why some of the tests are failing. If you can get the regex to work, they will pass.

**Comment by Supravisor** [comment]
Arrow and regular function both match in regex101, not sure why they are still failing tests.
image
image

**Comment by Supravisor** [comment]
Here is the assertion error from CI Node js
It seems to be working for function keyword.
image
Also for arrow function syntax.
image

**Review by jdwilkin4 — APPROVED** [review]

**Review by Ksound22 — APPROVED** [review]
Well done!

**Pull request merged**
