### PR TITLE
fix(curriculum): rework Project Euler 84

### PR DESCRIPTION
**Pull request by gikf**
- Reworks challenge to use argument in function call.
- Adds more tests.
- Adds solution.
- Adds `<br>` to position board evenly between paragraphs.
- Changed expected return type to string, as per description.
- Related to #40896.
- Tested on local fork.

Checklist:

- [x] I have read [freeCodeCamp's contribution guidelines](https://contribute.freecodecamp.org).
- [x] My pull request has a descriptive title (not a vague title like `Update index.md`)
- [x] My pull request targets the `main` branch of freeCodeCamp.
- [x] All the files I changed are in the same world language, for example: only English changes, or only Chinese changes, etc.

### CODE REVIEW

**Comment by gikf** [comment]
Important note about solution and example from description.

Because solution is basically simulating x rounds, with randomly generated dice rolls, and counting which field is visited how many times, exact results may differ slightly depending on number of rounds played. In solution that's 2 millions, this number was giving consistent results for added test cases. In description as example is used dice with `6` sides. I decided to not add it as one of the test case. Reason for it is inconsistent result even with `10` times more rounds simulated, every dozen or so test there was result different than expected. Because of that I didn't think it's worth to increase number of rounds simulated and/or risking getting result wrong result, which would fail tests.

**Review by moT01 — APPROVED** [review]
Running the solution displays `Potential infinite loop detected on line 56. Tests may fail if this is not changed.` in the console. The solution does pass shortly after though. I ran the solution quite a few times, couldn't get it to fail. Dropping the number of rounds did fail. I guess I don't see any problems with this - Is there no other way to get a solution without simulating rounds @gikf? I see the Euler site does something similar - so I'm guessing not.

I am just going to approve it pending another opinion. If it causes any problems, we can revert it. We could consider just leaving this one without a solution if it's a potential issue as well.

Note to self: Remind me to add this to the forum guide article if/when this gets merged.

**Comment by gikf** [comment]
@moT01 there's another approach using Markov chains. It's kind of above my understanding how to do that. Although it's expected to give the exact values, I haven't really encountered any solution using it, which I could follow, and try to figure out what exactly is happening.

**Review by raisedadead — APPROVED** [review]

**Comment by moT01** [comment]
I added this solution to the forum guide article

**Pull request merged**
