### PR TITLE
Added all 'React and Redux' challenge solutions 

### PR DESCRIPTION
**Pull request by jasonranney**
- [x ] I have read [freeCodeCamp's contribution guidelines](https://github.com/freeCodeCamp/freeCodeCamp/blob/master/CONTRIBUTING.md).
- [x ] My pull request has a descriptive title (not a vague title like `Update index.md`)
- [x ] My pull request targets the `master` branch of freeCodeCamp.
- [x ] None of my changes are plagiarized from another source without proper attribution.
- [x ] All the files I changed are in the same world language (for example: only English changes, or only Chinese changes, etc.)
- [x ] My changes do not use shortened URLs or affiliate links.

Closes #XXXXX

### CODE REVIEW

**Review by theNaut1lus — CHANGES_REQUESTED** [review]
Please follow the style used in creating other hints in challenges.
Add an explanation to the problem and and add some hints.

**Review by theNaut1lus — CHANGES_REQUESTED** [review]
Also it is requested not to remove any existing solution present in the guide itself(if working) but to add your own solution below it.
It is requested to retrieve the old solution and to add your solution below it.
P.S :- use the tags `basic solution`, `intermediate solution`, or `advanced solution` to categorise if two solutions present

**Comment by RandellDawson** [comment]
@co16353sidak There is no style preference anymore for the Guide articles. Yes, we would like to have hint and explanations for each solution added, but there is no required format.

@jasonranney As @co16353sidak mentioned, please do not overwrite existing working solutions.  Instead, add a new one below the existing one.  

Thank you.

**Comment by co16353sidak** [comment]
@RandellDawson  Add `status: needs update` tag for reference.

**Comment by co16353sidak** [comment]
Might conflict with #35067.

**Comment by RandellDawson** [comment]
> Might conflict with #35067.

@co16353sidak You don't have to worry about that.  If there are conflicts, they will show up and we will deal with them at the time they do.

**Comment by thecodingaviator** [comment]
Hi @jasonranney ,

As there has been no response from your end for a while, we are closing this PR.

Feel free to request this PR to be reopened, if you still wish to make the changes you originally added.  Also, remember to update your fork, so you have the latest version of master in case it has changed significantly.

Happy Coding! ✈️

**Pull request closed without merging**
