### PR TITLE
update code of conduct

### LINKED ISSUE #15371: Remove the views for CoC, Privacy and the ToS
#### Issue Description

~~The Beta Code of Conduct was updated but not the production one.~~
~~Updated: https://beta.freecodecamp.com/en/code-of-conduct ~~
~~Not updated: https://freecodecamp.com/en/code-of-conduct~~

Update(@raisedadead) :

The pages for code-of-conduct, privacy-policy and terms-of-service have moved to the independent static repos.
We just need to remove the routes and the views from the main repo.
This should happen once the redirects are done.

Thanks !!

### PR DESCRIPTION
**Pull request by texas2010**
#### Pre-Submission Checklist

- [ ] Your pull request targets the `staging` branch of freeCodeCamp.
- [x] Branch starts with either `fix/`, `feature/`, or `translate/` (e.g. `fix/signin-issue`)
- [x] You have only one commit (if not, [squash](http://forum.freecodecamp.com/t/how-to-squash-multiple-commits-into-one-with-git/13231) them into one commit).
- [ ] All new and existing tests pass the command `npm test`. Use `git commit --amend` to amend any fixes.

#### Type of Change

- [ ] Small bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds new functionality)
- [ ] Breaking change (fix or feature that would change existing functionality)
- [ ] Add new translation (feature adding new translations)

#### Checklist:

- [ ] Tested changes locally.
- [ ] Closes currently open issue (replace XXXX with an issue no): Closes #15371

### CODE REVIEW

**Comment by texas2010** [comment]
@raisedadead

**Comment by raisedadead** [comment]
Thanks @texas2010 I am blocking this for now. Once we have the static redirects, maybe you can remove this page altogether.

I'll update further on the details.

Happy fixing!

**Comment by texas2010** [comment]
@raisedadead sure!   thanks

**Comment by BerkeleyTrue** [comment]
@raisedadead Do we have a static version of this?

**Comment by raisedadead** [comment]
@BerkeleyTrue Yes, the repositories for the CoC, Privacy-Policy and the ToS are transferred from me to the org account.

I had setup the static sites at the master branch of the repositories on each.

Then can be redirected just like we have for our shop and about pages.

**Comment by raisedadead** [comment]
https://github.com/freeCodeCamp/code-of-conduct

**Comment by texas2010** [comment]
@raisedadead, 
Do I need to change branch name? 
other question, just delete files then commit it right? just wondering. thanks!
I think I forget how to change commit message.

thanks again.

**Comment by BerkeleyTrue** [comment]
@raisedadead We are now proxying the new CoC static page. Do we still need this PR?

**Pull request closed without merging**
