### PR TITLE
fix: Change instructions for Set up a Template Engine challenge to make user implement res.render() 

### PR DESCRIPTION
**Pull request by RandellDawson**
Checklist:

- [x] I have read [freeCodeCamp's contribution guidelines](https://contribute.freecodecamp.org).
- [x] My pull request has a descriptive title (not a vague title like `Update index.md`)
- [x] My pull request targets the `main` branch of freeCodeCamp.
- [x] I have tested these changes either locally on my machine, or GitPod.

This PR is an attempt to address [the issue I pointed out in the merging of PR #47050](https://github.com/freeCodeCamp/freeCodeCamp/pull/47050#issuecomment-1200248050).  I will make a suggested change on https://github.com/freeCodeCamp/boilerplate-advancednode/pull/24 that will correspond to this new instruction, so users do not see error messages in the console when first starting up the project to work on it.

### CODE REVIEW

**Review by Sboonny — APPROVED** [review]
LGTM 🎉, thank you for your contribution to the page! 👍.

**Review by scissorsneedfoodtoo — APPROVED** [review]
Everything LGTM 👍 👍 

Thank you for catching and fixing this future issue @RandellDawson. This should cut down on the confusion from a missing error message once https://github.com/freeCodeCamp/boilerplate-advancednode/pull/24 is merged.

**Comment by scissorsneedfoodtoo** [comment]
Note: This should not be merged until the changes from https://github.com/freeCodeCamp/boilerplate-advancednode/pull/24 are reviewed and merged.

**Comment by Sboonny** [comment]
I have reviewed and merged https://github.com/freeCodeCamp/boilerplate-advancednode/pull/24

**Comment by RandellDawson** [comment]
It is fine to have merged this PR, but the boilerplate should not really have been merged until commit(s) on this PR hit production.

**Comment by RandellDawson** [comment]
@ojeytonwilliams, @raisedadead  Can someone kick off a deployment to production in the next day or so?

**Comment by ojeytonwilliams** [comment]
@RandellDawson yep, it's on the way.

**Comment by RandellDawson** [comment]
@ojeytonwilliams I guess it failed on staging branch?

**Comment by ojeytonwilliams** [comment]
@RandellDawson unfortunately, yes. There were two Italian challenges claiming to be step 30 of the same block (the build is designed to fail if that happens).  Now https://github.com/freeCodeCamp/freeCodeCamp/pull/47127 we should catch that on merges to main.

**Pull request merged**
