### PR TITLE
fix(curriculum): Update 613e275749ebd008e74bb62e.md

### LINKED ISSUE #50888: Grammatical error in building a quiz - step 8
### Describe the Issue

The word "to" is repeated one after the other on the instructions:

Scale the image using its id as a selector, and setting the width **to to** be the maximum of 100px or 18vw.

### Affected Page

https://www.freecodecamp.org/learn/2022/responsive-web-design/learn-accessibility-by-building-a-quiz/step-8

### Your code

```



```

### Expected behavior

it should be: 
Scale the image using its id as a selector, and setting the width to be the maximum of 100px or 18vw.

### Screenshots

image

### System

- Device: [Laptop lenovo]
- OS: [Windows 10]
- Browser: [Chrome]

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by nikhilgarg26**
typo: "to to" -> "to"

Checklist:

- [x] I have read and followed the [contribution guidelines](https://contribute.freecodecamp.org).
- [ ] I have read and followed the [how to open a pull request guide](https://contribute.freecodecamp.org/#/how-to-open-a-pull-request).
- [x] My pull request targets the `main` branch of freeCodeCamp.
- [x] I have tested these changes either locally on my machine, or GitPod.

Closes #50888

### CODE REVIEW

**Comment by Sembauke** [comment]
As a new contributor, we encourage you to read our [contributing guidelines](https://contribute.freecodecamp.org).

We expect our contributors to be aware of the process specific to this project. Following the guidelines religiously earns you the respect of fellow maintainers and saves everyone time.

Some examples of this are:

1. Do not edit files directly through GitHub – while you can, it's not a good idea.
2. Make sure you follow the PR checklist and not just tick things off; otherwise, we won't take you seriously.
3. Use the correct way to link issues in the description of the PR by updating the `XXXXXX`. Do not just add issue numbers everywhere and anywhere you feel like.
4. Keep mentions and review requests to a minimum. We understand you are excited about contributing, and our maintainers will get back to you as soon as they get a chance.
5. Do not work directly off your `main` branch - create a new branch for the changes you are working on.

We appreciate you taking the time to help us, and we hope to see more contributions from you.

Happy Contributing.

**Comment by nikhilgarg26** [comment]
Hey, i was just wandering what went wrong with my PR if you may guide.

**Comment by jeremylt** [comment]
> Hey, i was just wandering what went wrong with my PR if you may guide.


Make sure you read up on how to open a PR:
https://contribute.freecodecamp.org/#/how-to-open-a-pull-request?id=prepare-a-good-pr-title

**Comment by gikf** [comment]
Hey @nikhilgarg26

Thank you for opening this pull request.

As there was different PR - #50891 - making all necessary changes, merged recently, we are going to close this one.

Thank you and happy coding! 😊

---

If you have any questions, feel free to ask questions on the ['Contributors' category on our forum](https://forum.freecodecamp.org/c/contributors) or [the contributors chat room](https://discord.gg/PRyKn3Vbay).

**Pull request closed without merging**
