### PR TITLE
Translate in Japanese Getting started / Create a GitHub Account and …

### PR DESCRIPTION
**Pull request by regonn**
I translated a part of Getting started in Japanese.

I finished "Create a GitHub Account and Join our Chat Rooms".
#6789

### CODE REVIEW

**Comment by hallaathrad** [comment]
私の日本語はかなり悪いですが、これは大丈夫に見えます。
Anyone, any concerns about the PR itself (guidelines, etc)?

**Comment by AaronJRubin** [comment]
I see that メール受信箱 and メール受信box are both used (lines 428 and 429, respectively) - for the sake of consistency, I would only use メール受信箱. Actually, my intuition would be that メールアドレス would be more idiomatic than both, but as I am a non-native speaker, please take that with a grain of salt.

**Comment by hallaathrad** [comment]
@AaronJRubin Yeah, I think even mixi simply uses メールアドレス... thanks for catching that one.

**Comment by regonn** [comment]
@hallaathrad @AaronJRubin Thank you for reviewing and pointing. :+1: 

I updated it. I'm a native Japanese. In this case, I think "メールアドレス宛" is better than "メールアドレス".

**Comment by AaronJRubin** [comment]
勉強になりました！

**Comment by hallaathrad** [comment]
@regonn OH of course. I didn't imply my Japanese was even decent at all. But there's something to be said about preexisting UX patterns and that's what we were aiming for to avoiding forcing people to learn our interface from scratch.  :)
Great job, though!

**Comment by regonn** [comment]
I deleted a unnecessary line.

**Comment by hallaathrad** [comment]
:+1: solid!

**Pull request merged**
