### PR TITLE
fix(guide):  Update guide solution for Positive and Negative Lookahead

### PR DESCRIPTION
**Pull request by emh1010**
The exercise requires a match at greater than 5 characters however the solution has a match occurring at a minimum of 5.
Request to update 5 to a 6.

- [X] I have read [freeCodeCamp's contribution guidelines](https://github.com/freeCodeCamp/freeCodeCamp/blob/master/CONTRIBUTING.md).
- [X] My pull request has a descriptive title (not a vague title like `Update index.md`)
- [X] My pull request targets the `master` branch of freeCodeCamp.
- [X] None of my changes are plagiarized from another source without proper attribution.
- [X] My article does not contain shortened URLs or affiliate links.

Closes #XXXXX

### CODE REVIEW

**Comment by lynxlynxlynx** [comment]
Why did you open a separate PR? This is the same issue as #34582 .

**Comment by emh1010** [comment]
Sorry I am still learning how this all works.  I was not sure if updating the Guide page would be included in a pull request to update the Learn page.  I opted to open a request for both.  If that is not correct, my apologies.

**Review by Manish-Giri — COMMENTED** [review]
I think this change is good. The guide article should also be updated to reflect the solution update that is proposed in the corresponding curriculum challenge.

**Comment by RandellDawson** [comment]
I updated the PR to reflect this is for the Guide.

**Review by thecodingaviator — APPROVED** [review]
LGTM! 👍 

@Manish-Giri I've tested this. Merge it if you feel it to be fine

**Review by Manish-Giri — APPROVED** [review]
@emh1010 LGTM. Thank You for your contribution.

**Pull request merged**
