### PR TITLE
feat: update readme links to link to specific blocks

### LINKED ISSUE #43010: Update README to link to specific blocks
The links to curriculum blocks in the [main README file](https://github.com/freeCodeCamp/freeCodeCamp/blob/main/README.md#1-responsive-web-design-certification) all just link to the top of the superblock page. We could link to the specific blocks with something like https://www.freecodecamp.org/learn/responsive-web-design/#basic-html-and-html5. Unless there's a reason we wouldn't want to do that, seems like a good first timer issue.

### PR DESCRIPTION
**Pull request by Aryan-Mohanty**
Updates README to link to specific blocks 
Resolves: #43010

### CODE REVIEW

**Review by ojeytonwilliams — CHANGES_REQUESTED** [review]
Hi @Aryan-Mohanty, thanks for this PR.  Could you also link the headings to the original urls?  Reason being, without those there would no longer be any direct links to the top of those pages.

**Comment by Sembauke** [comment]
Also please read our [contributor guide](https://contribute.freecodecamp.org/#/),

and make use of the following template: 

- [ ] I have read [freeCodeCamp's contribution guidelines](https://contribute.freecodecamp.org).
- [ ] My pull request has a descriptive title (not a vague title like `Update index.md`)
- [ ] My pull request targets the `main` branch of freeCodeCamp.
- [ ] I have tested these changes either locally on my machine, or GitPod.



Closes #XXXXX

**Comment by Aryan-Mohanty** [comment]
@ojeytonwilliams, added the original links to the headings as you have suggested!

**Review by ojeytonwilliams — APPROVED** [review]
@Aryan-Mohanty, thanks for making those changes. LGTM 👍

**Review by ShaunSHamilton — APPROVED** [review]
This LGTM 👍

**Comment by ShaunSHamilton** [comment]
Congrats on your first pull request (PR)! 🎉

Thank you, for your contribution to the page! 👍
We are happy to accept these changes and look forward to future contributions. 📝

**Pull request merged**
