### PR TITLE
French translation v1

### PR DESCRIPTION
**Pull request by cploose**
This is a PR concerning french translation of seed/challenges/00-getting-started/getting-started.json

### CODE REVIEW

**Comment by BerkeleyFalse** [comment]
@fnonga thanks for the PR.
Your branch name should start with one of `fix/, feature/` prefixes. Name, your branches correctly next time, please.
You have pushed more than one commit. When you finish editing, [squash](https://github.com/FreeCodeCamp/FreeCodeCamp/wiki/git-rebase#squashing-multiple-commits-into-one) your commits into one.
Please, review our [**Guidelines for Contributing**](https://github.com/FreeCodeCamp/FreeCodeCamp/blob/staging/CONTRIBUTING.md), thank you!.

**Comment by thejonathangraham** [comment]
@fnonga Thanks so much for mixing up my bad french! I'll pull these commits into my PR so they're all together. I'll give you admin access.

**Comment by thejonathangraham** [comment]
@fnonga Do you have gitter?

**Comment by thejonathangraham** [comment]
@fnonga @bugron This can be closed as I've merged it into mine and the user has been notified.

**Comment by bugron** [comment]
Closing. Don't mix PRs, please, work in separate branches/PRs until you know what are you doing.

**Pull request closed without merging**
