### PR TITLE
[fix]: Problem 47 - Added optimized solution

### PR DESCRIPTION
**Pull request by ezioda004**
- [x] I have read [freeCodeCamp's contribution guidelines](https://github.com/freeCodeCamp/freeCodeCamp/blob/master/CONTRIBUTING.md).
- [x] My pull request has a descriptive title (not a vague title like `Update index.md`)
- [x] My pull request targets the `master` branch of freeCodeCamp.
- [x] None of my changes are plagiarized from another source without proper attribution.
- [x] My article does not contain shortened URLs or affiliate links.

If your pull request closes a GitHub issue, replace the XXXXX below with the issue number.

In reference to the issue https://github.com/freeCodeCamp/freeCodeCamp/issues/30462

Here's the [performance comparison](https://jsperf.com/euler-problem-47-test/1) between previous and new solution. The new solution is 4x times faster. 

However, it still doesnt pass the last test in the curriculum.
I've tested locally and all the tests pass within < 80ms. I guess the timeout for this challenge also needs to be increased.

### CODE REVIEW

**Comment by ezioda004** [comment]
@ValeraS The new solution is a bit slower than previous one.
https://jsperf.com/problem-47-2

**Comment by ValeraS** [comment]
@ezioda004 look at this https://repl.it/@ValeraS1/StormyBrokenConnections

**Comment by ValeraS** [comment]
It's strange a bit. I 've got this result in repl.it
image

**Comment by ezioda004** [comment]
@ValeraS It seems like a repl issue.
I've tested locally on node as well.

Getting similar results:
screenshot 160
screenshot 159

**Comment by ValeraS** [comment]
Which version of Node?

**Comment by ezioda004** [comment]
v10.5.0

**Comment by ValeraS** [comment]
I've tested it on Node v8 and it's worked quicker significantly. On Node v10 both solutions almost identical. Perhaps it depends on the hardware too.

I've wanted to remove `Set` as it is overhead.

**Comment by ezioda004** [comment]
@ValeraS Yeah, the new solution you mentioned is the fastest.
Updated the perf test with that https://jsperf.com/problem-47-2

Its weird that removing `const` increased the performance and the fact that calculating `Math.sqrt(n)` each iteration is faster than storing it in a variable.

**Comment by ValeraS** [comment]
> calculating Math.sqrt(n) each iteration is faster than storing it in a variable.

No, it's not faster, but in loop `n` may change and because of this, the loop iterates fewer times.

**Pull request merged**
