### PR TITLE
Added external link to substantiate js waypoint

### LINKED ISSUE #2595: Wondering about this formula
Challenge http://www.freecodecamp.com/challenges/waypoint-create-a-javascript-slot-machine has an issue. Please describe how to reproduce it, and include links to screenshots if possible.

Hello,

 I was working on this problem, and I was just wondering about the formula that was used in order to solve this problem:

Math.floor(Math.random() * (3 - 1 + 1)) + 1;

Doesn't this just mean the same thing as:

Math.floor(Math.random() * (3)) + 1;

I tried to use this formula, but it would not let me pass the level without using the example provided.

Also, it might be useful to other campers to give a detailed explanation as to how this works and why it does work.

Thanks!!
Alisa

### PR DESCRIPTION
**Pull request by butterthebuddha**
Added a link to a StackoverFlow answer to provide explanation of the formula used in the 'Create a JavaScript Slot Machine' basic javascript waypoint (seeds and renders successfully)
closes #2595

### CODE REVIEW

**Comment by bugron** [comment]
@awesomeaniruddh IMHO this link also needs to be in waypoint "Generate Random Whole Numbers within a Range".

**Comment by awesomeaniruddh** [comment]
Done!

**Comment by awesomeaniruddh** [comment]
Wait, don't merge yet, need to amend the commit!

**Comment by awesomeaniruddh** [comment]
k, can be merged now :D

**Comment by bugron** [comment]
@awesomeaniruddh remove the dot at the end of: "(an explanation of the formula can be found <a href=\"https://github.com/FreeCodeCamp/FreeCodeCamp/wiki/Waypoint-Generate-Random-Whole-Numbers-within-a-Range#explanation\">here</a>**.**):"

**Comment by awesomeaniruddh** [comment]
yeh, done. Need to start wearing my glasses.

**Comment by bugron** [comment]
@awesomeaniruddh I'm sorry but you also need to remove backslashes at the end of your links.

**Comment by awesomeaniruddh** [comment]
The backslashes are there to escape the `"` character

**Comment by bugron** [comment]
Oh, of course, sorry, verified and merged, thanks.

**Pull request merged**
