### PR TITLE
fix(curriculum,i18n): issues in the source string

### PR DESCRIPTION
**Pull request by fhsinchy**
Checklist:

- [x] I have read [freeCodeCamp's contribution guidelines](https://contribute.freecodecamp.org).
- [x] My pull request has a descriptive title (not a vague title like `Update index.md`)
- [x] My pull request targets the `main` branch of freeCodeCamp.
- [x] I have tested these changes either locally on my machine, or GitPod.

I've removed an extra `a` and a misplaced full stop from the source string from the `5efb23e70dc218d6c85f89b1.md` file. Removed an extra quotaion mark from the `5f0d4d04b435f13ab6550053.md` file.

### CODE REVIEW

**Review by naomi-lgbt — DISMISSED** [review]
Looks good to me.

**Review by gikf — COMMENTED** [review]
Could you remove from this PR commits related to the already merged PR - #45448?

Generally it's recommended to make new branch, based off `main` branch, for each PR.

**Comment by fhsinchy** [comment]
@gikf my apologies, that was not intended. Should I close this PR and make the changes in a new branch and create a new PR? Also, I'll make sure to create a new branch for each PR in the future.

**Comment by gikf** [comment]
No need to open new PR. There's couple ways to deal with the situation, simplest might be reverting changes made to `5ef9b03c81a63668521804e7.md`, so the file is not touched in PR. Alternatives are utilizing more advanced git features and ie. using interactive rebase to remove whole commits from the branch.

**Comment by fhsinchy** [comment]
@gikf thank you for your guidelines. I've reverted the unwanted commits.

**Review by raisedadead — APPROVED** [review]

**Review by gikf — APPROVED** [review]
Looks good to me :+1:

**Pull request merged**
