### PR TITLE
[Feature] - Add eslint-plugin-security

### PR DESCRIPTION
**Pull request by MrSlimCoder**
- [x] I have read [freeCodeCamp's contribution guidelines](https://github.com/freeCodeCamp/freeCodeCamp/blob/master/CONTRIBUTING.md).
- [x] My pull request has a descriptive title (not a vague title like `Update index.md`)
- [x] My pull request targets the `master` branch of freeCodeCamp.
- [x] None of my changes are plagiarized from another source without proper attribution.
- [x] All the files I changed are in the same world language (for example: only English changes, or only Chinese changes, etc.)
- [x] My changes do not use shortened URLs or affiliate links.

Closes #XXXXX

### CODE REVIEW

**Comment by viveksharmaui** [comment]
I have added [eslint plugin security rules](https://www.npmjs.com/package/eslint-plugin-security) .

**Comment by raisedadead** [comment]
Thanks for the PR, but I am personally not sold on this:

> This project will help identify potential security hotspots, but *finds a lot of false positives which need triage by a human.*

**Comment by ojeytonwilliams** [comment]
It does at that.  I tried it locally and it produces a ton of warnings.  

Having said that, they are only warnings, so they wouldn't cause the linter to fail.  We *could* go through them gradually.  In my opinion it would need to be separate from the regular linting, so that we don't have to ignore the warnings when dealing with something else.

**Comment by viveksharmaui** [comment]
I used eslint-security-plugin and i love it in my opinion it is very useful to find bad practices in code .

**Comment by viveksharmaui** [comment]
It only output warnings i mean it wouldn't fail linter .

**Comment by viveksharmaui** [comment]
I think you guy's should use it and we will working to solve those warnings

**Comment by viveksharmaui** [comment]
> Thanks for the PR, but I am personally not sold on this:
> 
> > This project will help identify potential security hotspots, but _finds a lot of false positives which need triage by a human._

I'm using eslint-security-plugin and never experienced a false positive result it helped me alot to solve those security bad practices .

**Comment by viveksharmaui** [comment]
> It does at that. I tried it locally and it produces a ton of warnings.
> 
> Having said that, they are only warnings, so they wouldn't cause the linter to fail. We _could_ go through them gradually. In my opinion it would need to be separate from the regular linting, so that we don't have to ignore the warnings when dealing with something else.

Yes you are right these are just warnings and it will not fail linter 🎉 we can integrate it on the go it can improve codebase security .

**Comment by ojeytonwilliams** [comment]
> I'm using eslint-plugin-security and never experienced a false positive result it helped me alot to solve those security bad practices .

I'm afraid that's not the case here, unless I'm totally missing something.  When I looked I found situations where it complains when you use `obj[variable]` just because *in principle* the variable could be anything.  However, if you look closer at the code it's something we control.

So, we'd have to go through manually and check them all (and probably put in disabling comments for a fair number).  Something that will take time.  And, until that's done, we'd be bombarding contributors with warnings that have nothing to do with their code.  That's something we should avoid, so we don't create an unnecessary barrier to contribution.

**Comment by raisedadead** [comment]
> we can integrate it on the go it can improve codebase security.

I agree, but that defeats the purpose of the plugin. People get complacent with these things easily. 

We seriously would like to employ best practices especially security.

I do recommend using this plugin, but not at the cost of only ignoring it. If this is integrated it should be strict and we should also include the fixes in this PR?

**Comment by viveksharmaui** [comment]
> > we can integrate it on the go it can improve codebase security.
> 
> I agree, but that defeats the purpose of the plugin. People get complacent with these things easily.
> 
> We seriously would like to employ best practices especially security.
> 
> I do recommend using this plugin, but not at the cost of only ignoring it. If this is integrated it should be strict and we should also include the fixes in this PR?

If you can merge this PR then i will work on Fixing these warnings and send another PR of that.

**Comment by raisedadead** [comment]
> If you can merge this PR then i will work on Fixing these warnings and send another PR of that.

Unfortunately we can't merge the PR as is. As Oliver already pointed in his comments, it shows up the warnings locally. This will lead to a lot of confusion because this is a tooling feature that we are implementing.

We would prefer the fix to the warning with this PR.

**Comment by viveksharmaui** [comment]
No problem i will update PR with all fix warnings .

**Comment by raisedadead** [comment]
Thanks for taking the time to work on this PR.

**Comment by ojeytonwilliams** [comment]
Based off Mrugesh's comment

>  If this is integrated it should be strict 

I converted the warnings to errors.

@viveksharmaui I was going to add this as a review suggestion, but Github's interface wouldn't let me, so I just added a commit.  I hope that's okay!

**Comment by viveksharmaui** [comment]
> Based off Mrugesh's comment
> 
> > If this is integrated it should be strict
> 
> I converted the warnings to errors.
> 
> @viveksharmaui I was going to add this as a review suggestion, but Github's interface wouldn't let me, so I just added a commit. I hope that's okay!

That's great .

**Comment by viveksharmaui** [comment]
@raisedadead @ojeytonwilliams please review PR guys.

**Comment by viveksharmaui** [comment]
Still, we have 50 remaining security problems in this codebase which I was unable to solve so I edit eslintrc.json and update them to warn 
`We still have 50 problems (0 errors, 50 warnings)`
I tried and solve 200+ problems and i don't know why test is failed.

**Comment by ojeytonwilliams** [comment]
@viveksharmaui thanks for all the work you're putting into this!

I'm going to defer to @raisedadead's judgement, but I think that any problems that do not need fixing should have their warnings disabled via comments (i.e. `// eslint-disable-next-line`).  While we can disable specific rules (or lower them to warnings) I think that should only be done when we're not worried about that class of issues.

**Comment by viveksharmaui** [comment]
@ojeytonwilliams yeah ! this will be good if we disable those warnings because our codebase need sometime for that , and test is fail actually there was security error in test which i edited and i stuck on it give me few days more to update test or replace them to previous version .

**Comment by viveksharmaui** [comment]
> @viveksharmaui thanks for all the work you're putting into this!
> 
> I'm going to defer to @raisedadead's judgement, but I think that any problems that do not need fixing should have their warnings disabled via comments (i.e. `// eslint-disable-next-line`). While we can disable specific rules (or lower them to warnings) I think that should only be done when we're not worried about that class of issues.

. `// eslint-disable-next-line` is not supported in eslint security plugin we should do something else for this .

**Comment by ojeytonwilliams** [comment]
@viveksharmaui take as long as you need!  If there's a particular warning that's hard to deal with, please ask - another pair of eyes could help.

> // eslint-disable-next-line is not supported in eslint security plugin we should do something else for this .

That could be a bit of problem.  I'll see if I can figure out what our options are.

**Comment by viveksharmaui** [comment]
@ojeytonwilliams there was few security warnings related to regex and few was about security flaws which i found tough but i will try my best .

**Comment by viveksharmaui** [comment]
@raisedadead @ojeytonwilliams  guy's i wanna join freecodecamp as a member on github this will give more motivation to me . Thanks !

**Comment by RandellDawson** [comment]
>guy's i wanna join freecodecamp as a member on github this will give more motivation to me . Thanks !

@viveksharmaui This is the first contribution you have attempted to make for Free Code Camp and you have not yet even completed it.   I would hope your motivation to complete this PR would be that you want to help make things better for Free Code Camp.  

Membership is earned through lots of contributions.

**Pull request closed without merging**
