### PR TITLE
feat (curriculum): add instructions to data analysis in python project

### PR DESCRIPTION
**Pull request by a2937**
Checklist:

- [x] I have read and followed the [contribution guidelines](https://contribute.freecodecamp.org).
- [x] I have read and followed the [how to open a pull request guide](https://contribute.freecodecamp.org/#/how-to-open-a-pull-request).
- [x] My pull request targets the `main` branch of freeCodeCamp.
- [x] I have tested these changes either locally on my machine, or GitPod.

Related to https://github.com/freeCodeCamp/freeCodeCamp/issues/47038 

The markdown for instructions was added but the problem is tasks also covers a lot of similar data. Additionally I think my wording can perhaps be improved.

### CODE REVIEW

**Review by moT01 — COMMENTED** [review]
I think we should put many of these values in backticks so they look like code and don't get translated. e.g. `overweight`, `cholesterol`, `matplotlib`, etc. What do you think @a2937?

**Comment by a2937** [comment]
You're right. I should have done that ages ago. But now is good.

**Review by moT01 — COMMENTED** [review]
Something still doesn't feel right here - it's slightly confusing. I think we could maybe use a sentence that describes what the instructions are for - maybe "By each number in the `medical_data_visualizer.py` file, add the code from the associated instruction number below."

I think something like that would work.

**Comment by a2937** [comment]
On it chief. It's been pushed.

**Review by majestic-owl448 — APPROVED** [review]
LGTM 👍

**Review by Dario-DC — CHANGES_REQUESTED** [review]

**Review by Dario-DC — APPROVED** [review]
LGTM 🎉

**Pull request merged**
