### PR TITLE
feat: add new responsive webdesign to certified user

### PR DESCRIPTION
**Pull request by Sembauke**
Checklist:

- [ ] I have read and followed the [contribution guidelines](https://contribute.freecodecamp.org).
- [ ] I have read and followed the [how to open a pull request guide](https://contribute.freecodecamp.org/#/how-to-open-a-pull-request).
- [ ] My pull request targets the `main` branch of freeCodeCamp.
- [ ] I have tested these changes either locally on my machine, or GitPod.

Closes #XXXXX

### CODE REVIEW

**Comment by ahmaxed** [comment]
This just updates the seed file with responsive web design challenges. 
@Sembauke is there a reason for the pnpm-lock.yaml update?

**Comment by Sembauke** [comment]
@ahmaxed I am not sure. @naomi-lgbt is there any issue merging the lock file with it?

**Comment by ahmaxed** [comment]
Not sure. We could drop the lock here and move forward with the pr.

**Comment by naomi-lgbt** [comment]
> is there any issue merging the lock file with it?

It creates extra noise. What `pnpm` version are you using?

**Comment by naomi-lgbt** [comment]
For more context, the lockfile version was bumped to 6.1 in pnpm 8.6.0, but was bumped back down to 6.0 in 8.6.2 due to older pnpm versions being unable to parse 6.1

As such, we should not merge this with the lock file for two reasons:
- Our engines field specifies `pnpm: 8`, which means contributors could be using versions earlier than 8.6.X, and we would not want the lockfile version to be 6.1
- Anyone using pnpm later than 8.6.2 would revert the lockfile to 6.0.

**Comment by Sembauke** [comment]
Hey @ahmaxed, 

The lock file is no longer here.

**Comment by ojeytonwilliams** [comment]
Does it matter that all the challenges were completed within a millisecond of each other?  @ahmaxed, does this meet your requirements?

**Comment by ahmaxed** [comment]
I see your point Oliver. We have a few features that depend on timestamps, streak, heat-map, etc. 
There is not test coverage for some of these features yet, so merging this pr will not cause any issues.

I will double check with our most active user ever to see if we can reuse his user object. If that is confirmed, I will revert this in favor of an object with a natural progression.

Down the line, I will remove 1-2 challenges from a block so I could test the donation modal popping, etc.

**Review by ojeytonwilliams — APPROVED** [review]
LGTM :+1:

**Comment by ahmaxed** [comment]
@Sembauke 🫡 LGMT

**Review by ahmaxed — APPROVED** [review]

**Pull request merged**
