### PR TITLE
fix: prevent focus when using find/replace

### LINKED ISSUE #19695: Cursor moves out of find and replace box after typing the character 'e'
I tried using the find and replace in the editor with Command + Option + F while doing a challenge and noticed that after typing the 'e' or 'E' character in the find or replace box my cursor would automatically move to the selected word on the page (out of the find or replace box and onto challenge editor section
cursor moving out of find and replace
).

Add a Link to the page with the problem:
https://learn.freecodecamp.org/javascript-algorithms-and-data-structures/es6/declare-a-read-only-variable-with-the-const-keyword
(I think it's on all pages and is the editor but I noticed it here)

Browser Name: 
Google Chrome
Browser Version: 
Version 69.0.3497.100 (Official Build) (64-bit)
Operating System: 
macOS High Sierra
10.13.6

### PR DESCRIPTION
**Pull request by TheHollidayInn**
I apologize that this is hacky. I'm not sure of any way to check if MonacoEditor is currently in the find/replace state. I checked their github and docs. If anyone has a better idea, let me know, but the issue lies in the hot key event.

- [x] I have read [freeCodeCamp's contribution guidelines](https://github.com/freeCodeCamp/freeCodeCamp/blob/master/CONTRIBUTING.md).
- [x] My pull request has a descriptive title (not a vague title like `Update index.md`)
- [x] My pull request targets the `master` branch of freeCodeCamp.
- [x] None of my changes are plagiarized from another source without proper attribution.
- [x] My article does not contain shortened URLs or affiliate links.

If your pull request closes a GitHub issue, replace the XXXXX below with the issue number.

Closes #19695

### CODE REVIEW

**Comment by RandellDawson** [comment]
@Bouncey How does this look?

**Comment by RandellDawson** [comment]
Closed and Reopened this PR to attempt to resolve a specific Travis build failure.

**Comment by Bouncey** [comment]
Hi @TheHollidayInn, sorry for the delay in getting round to this.

I would be in favour of simply removing the `focusEditor` key binding.

**Comment by TheHollidayInn** [comment]
Works for me. Should I go ahead and remove the key binding then? @Bouncey

**Comment by raisedadead** [comment]
Hey @ValeraS can you please review this? Thanks

**Review by ValeraS — APPROVED** [review]

**Comment by ValeraS** [comment]
#### :sparkles: :sparkles: **LGTM.** :sparkles: :sparkles: 

Thanks @TheHollidayInn 

Happy Contributing!

**Comment by TheHollidayInn** [comment]
Thanks!

**Pull request merged**
