### PR TITLE
Fix case sensitivity in Prioritize Styles challenge

### LINKED ISSUE #9751: Letter case not considered when a color is mentioned in a class
#### Challenge Name

https://www.freecodecamp.com/challenges/prioritize-one-style-over-another#?solution=%0A%3Cstyle%3E%0A%20%20body%20%7B%0A%20%20%20%20background-color%3A%20black%3B%0A%20%20%20%20font-family%3A%20Monospace%3B%0A%20%20%20%20color%3A%20green%3B%0A%20%20%7D%0A%20%20.pink-text%20%7B%0A%20%20%20%20color%3A%20PINK%3B%0A%20%20%7D%0A%20%20h1%20%7B%0A%20%20%20%20color%3A%20yellow%3B%0A%20%20%7D%0A%3C%2Fstyle%3E%0A%3Ch1%20class%3D'pink-text'%3EHello%20World!%3C%2Fh1%3E%0A

#### Issue Description

when the color in a class is mentioned in upper case, the output shown on the screen is already pink, but i cannot proceed by pressing ctrl+enter unless i mention the color in lower case text.

#### Browser Information

* Browser Name, Version: Chrome
* Operating System: Windows 8
* Mobile, Desktop, or Tablet: Laptop

#### Your Code

.pink-text {
    color: PINK;
  }

#### Screenshot

image

### PR DESCRIPTION
**Pull request by Manish-Giri**
#### Pre-Submission Checklist

- [x] Your pull request targets the `staging` branch of FreeCodeCamp.
- [x] Branch starts with either `fix/`, `feature/`, or `translate/` (e.g. `fix/signin-issue`)
- [x] You have only one commit (if not, [squash](https://github.com/FreeCodeCamp/FreeCodeCamp/wiki/Git-Squash) them into one commit).
- [x] All new and existing tests pass the command `npm run test-challenges`. Use `git commit --amend` to amend any fixes.
#### Type of Change

- [x] Small bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds new functionality)
- [ ] Breaking change (fix or feature that would change existing functionality)
- [ ] Add new translation (feature adding new translations)
#### Checklist:

- [x] Tested changes locally.
- [x] Closes currently open issue (replace XXXX with an issue no): Closes #9751 
#### Description

Amending Regex to consider color name in CAPS. 

Verified locally - 

```
  total:     777
  passing:   777
  duration:  10.1s 
```

Closes #9751

### CODE REVIEW

**Comment by raisedadead** [comment]
@erictleung do we want to split this in this pull request or a fresh one? as per your last comment on the issue thread.

**Comment by erictleung** [comment]
@raisedadead we can do a fresh one unless @Manish-Giri wants to work on it with this PR. 

@Manish-Giri thanks for your efforts on this change but I think doing this *ad hoc* regex to do case insensitivity is too hacky. Please refer to my comment on #9751 for more information. Feel free to close this PR or just make changes to it.

**Comment by Manish-Giri** [comment]
@erictleung I'll try to make changes to this PR itself, to meet the new requirements. I'm not too good with regex yet, so please bear with me while I sort it out!!

**Comment by Manish-Giri** [comment]
I am creating a new branch for this issue, when I re-create the PR from the new branch, that should re-open this PR.

**Pull request closed without merging**
