### PR TITLE
fix(i18n): apply unused translations

### PR DESCRIPTION
**Pull request by naomi-lgbt**
Checklist:

- [X] I have read [freeCodeCamp's contribution guidelines](https://contribute.freecodecamp.org).
- [X] My pull request has a descriptive title (not a vague title like `Update index.md`)
- [X] My pull request targets the `master` branch of freeCodeCamp.
- [X] All the files I changed are in the same world language, for example: only English changes, or only Chinese changes, etc.

Closes #XXXXX

Applies the following unused translation keys
(discovered with script from #40585):
- ~~HeatMap uses plural form of points unless points=1~~ - handled automatically
- ~~Camper uses plural form of points unless points=1~~ - handled automatically
- DeleteModal uses delete title instead of button text - fixed with this PR
- UpdateEmail page uses verify email translation correctly - fixed with this PR
- buttons.reset-lesson (replaced by reset-code?) - fixed with this PR

Still unused:
- settings.username validation error messages (loaded dynamically)
- flash messages (sent from server?)
- donate.additional (removed from page, discussed to keep this key)

Signed-off-by: nhcarrigan <nhcarrigan@gmail.com>

### CODE REVIEW

**Comment by moT01** [comment]
Pretty sure those `_plural` keys automatically work behind the scenes.

**Comment by nhcarrigan** [comment]
Oh neat! Okay I'll revert that change (and update my script to ignore `_plural`)

**Review by raisedadead — APPROVED** [review]

**Comment by raisedadead** [comment]
We should probably track the unused keys in an issue thread.

**Review by moT01 — APPROVED** [review]
LGTM 🎉 Thanks for getting that script running and fixing these @nhcarrigan 🎉

**Pull request merged**
