### PR TITLE
Added link to additional resource

### PR DESCRIPTION
**Pull request by Sourabh06**
- [x] I have read [freeCodeCamp's contribution guidelines](https://github.com/freeCodeCamp/freeCodeCamp/blob/master/CONTRIBUTING.md).
- [x] My pull request has a descriptive title (not a vague title like `Update index.md`)
- [x] My pull request targets the `master` branch of freeCodeCamp.
- [x] None of my changes are plagiarized from another source without proper attribution.
- [x] My article does not contain shortened URLs or affiliate links.

If your pull request closes a GitHub issue, replace the XXXXX below with the issue number.

Closes #XXXXX

### CODE REVIEW

**Comment by honmanyau** [comment]
@Sourabh06 Thank you very much for submitting a pull request (PR). Could you please comment on the legality of the PDF that you added a link to? It appears to be the scan of an entire copyrighted book and I can't see immediately on the website whether or not they are allowed to do that (seems unlikely).

**Comment by Sourabh06** [comment]
Thank you @honmanyau.
I have updated the new link. The previous one was  legit copy but it was reuploaded by the other site

**Comment by honmanyau** [comment]
I think it would be more appropriate to use the link from the publisher (McGraw-Hill):

https://www.mheducation.com/highered/product/data-communications-networking-forouzan/M0073376221.html

Looking through the table of contents it does appear that that the book is a good reference book and I think the link is worthwhile adding. Please modify your PR with the link above and make sure that the link sections is formatted properly.

**Comment by honmanyau** [comment]
@cmccormack Thank you very much for sorting it out! 👍

**Pull request merged**
