### PR TITLE
fix(curriculum): check position of if statement - calorie counter New JS Project

### LINKED ISSUE #55303: Step 76 - Learn form validation by building a calorie counter
### Describe the Issue

The challenge asks you add code to check if there is an error after calling the getCaloriesFromInputs() function. However, the challenge passes even if this code is added before.

### Affected Page

https://www.freecodecamp.org/learn/javascript-algorithms-and-data-structures-v8/learn-form-validation-by-building-a-calorie-counter/step-76

### Your code

```
function calculateCalories(e) {
  e.preventDefault();
  isError = false;


// this should go at the end of this function but it works here too
  if(isError) {
    return;
  }

  const breakfastNumberInputs = document.querySelectorAll('#breakfast input[type=number]');
  const lunchNumberInputs = document.querySelectorAll('#lunch input[type=number]');
  const dinnerNumberInputs = document.querySelectorAll('#dinner input[type=number]');
  const snacksNumberInputs = document.querySelectorAll('#snacks input[type=number]');
  const exerciseNumberInputs = document.querySelectorAll('#exercise input[type=number]');

  const breakfastCalories = getCaloriesFromInputs(breakfastNumberInputs);
  const lunchCalories = getCaloriesFromInputs(lunchNumberInputs);
  const dinnerCalories = getCaloriesFromInputs(dinnerNumberInputs);
  const snacksCalories = getCaloriesFromInputs(snacksNumberInputs);
  const exerciseCalories = getCaloriesFromInputs(exerciseNumberInputs);
  const budgetCalories = getCaloriesFromInputs([budgetNumberInput]);

}

```

### Expected behavior

The test / challenge should fail if the code is added before the function is called. This is because we just set isError to false and having an if(isError) block right after it is pointless as it would never enter it.

### Screenshots

_No response_

### System

- Device: [e.g. iPhone 6, Laptop] - Macbook Air M2
- OS: [e.g. iOS 14, Windows 10, Ubuntu 20.04] Sonoma 14.5
- Browser: [e.g. Chrome, Safari] Chrome and Safari
- Version: [e.g. 22] IDK

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by lasjorg**
Checklist:

- [x] I have read and followed the [contribution guidelines](https://contribute.freecodecamp.org).
- [x] I have read and followed the [how to open a pull request guide](https://contribute.freecodecamp.org/how-to-open-a-pull-request/).
- [x] My pull request targets the `main` branch of freeCodeCamp.
- [x] I have tested these changes either locally on my machine, or GitPod.

Closes #55303

Regex checks `code` for `if` statement position.

---

Notes:

If we just check what comes before the if statement and the camper for whatever reason alters the function call order that would fail.

If we just check for the closing function bracket they can close the function in the wrong place, BTW they can pass the previous tests doing that now as well.

```
function calculateCalories(e) {
  e.preventDefault();
  isError = false;

  if(isError) {
    return;
  }
}
// Other function body code
```

### CODE REVIEW

**Review by JoyShaheb — CHANGES_REQUESTED** [review]
image
The hint should be modified as 
```
Your calculateCalories function should have an if statement with isError variable as the condition.
```
This is because if you write **if** without any condition, it will throw error and the hint won't be displayed.

**Comment by lasjorg** [comment]
@JoyShaheb I combined the first two tests. It doesn't seem to make sense to check for the if statement without the condition if that just causes a false positive.

**Comment by JoyShaheb** [comment]
> @JoyShaheb I combined the first two tests. It doesn't seem to make sense to check for the if statement without the condition if that just causes a false positive.

only editing the hint should be fine. When the user will type ```if``` statement without any condiitons, which won't pass any test cases. we just wanted to let them know via hint that ```you should write if statement with xyz conditions```. Now, you don;t have to do this porgrammatically, just write on the hint, that should do it. I might be wrong, please correct me.
```
if(){}
```

**Review by JoyShaheb — APPROVED** [review]
good work 👍

**Review by raisedadead — APPROVED** [review]

**Pull request merged**
