### PR TITLE
chore: change type of challenges to type 1 js

### PR DESCRIPTION
**Pull request by majestic-owl448**
Checklist:

- [x] I have read [freeCodeCamp's contribution guidelines](https://contribute.freecodecamp.org).
- [x] My pull request has a descriptive title (not a vague title like `Update index.md`)
- [x] My pull request targets the `main` branch of freeCodeCamp.
- [x] I have tested these changes either locally on my machine, or GitPod.

Second step for #46729

All challenges have been converted to type 1 js, js projects (in new and current js cert) are type 5 jsProject (current bonfire).

### CODE REVIEW

**Review by ojeytonwilliams — APPROVED** [review]
LGTM :+1:

**Review by Sboonny — APPROVED** [review]
LGTM 🎉, thank you for your contribution to the page! 👍.

**Comment by ieahleen** [comment]
> Do you think you'll have a chance to simplify the logic, too?

Once these two PRs are merged, I can try! @ojeytonwilliams

**Comment by ojeytonwilliams** [comment]
Awesome, thanks @ieahleen!

**Pull request merged**
