### PR TITLE
A-href-attribute__English-to-Spanish-translation.md

### PR DESCRIPTION
**Pull request by KrsBB**
Translation to Spanish

- [x] I have read [freeCodeCamp's contribution guidelines](https://github.com/freeCodeCamp/freeCodeCamp/blob/master/CONTRIBUTING.md).
- [x] My pull request has a descriptive title (not a vague title like `Update index.md`)
- [x] My pull request targets the `master` branch of freeCodeCamp.
- [x] None of my changes are plagiarized from another source without proper attribution.
- [x] My article does not contain shortened URLs or affiliate links.

If your pull request closes a GitHub issue, replace the XXXXX below with the issue number.

Closes #XXXXX

### CODE REVIEW

**Comment by KrsBB** [comment]
Sorry, I'm new here :)

**Comment by ArielLeslie** [comment]
You checked a box that said "My pull request has a descriptive title (not a vague title like Update index.md)", but your PR is called "Update index.md". Descriptive titles and comment blocks make a big difference in the maintainablility of a codebase.

**Comment by KrsBB** [comment]
Oh, sorry, I thought that I had written "Spanish translation". Something might be wrong, could you help me to change it?

**Comment by RandellDawson** [comment]
Update the title of the PR.

image

**Comment by KrsBB** [comment]
> You checked a box that said "My pull request has a descriptive title (not a vague title like Update index.md)", but your PR is called "Update index.md". Descriptive titles and comment blocks make a big difference in the maintainablility of a codebase.

Titke changed :)

**Review by cmccormack — APPROVED** [review]
This looks good to me 👍.  Thank you for your contribution!

**Pull request merged**
