### PR TITLE
fix(learn): update Write Arrow Functions with Parameters tests

### LINKED ISSUE #39049: Lesson: ES6: Write Arrow Functions with Parameters - allows pass with incorrect code
**Describe your problem and how to reproduce it:**
The lesson on page will allow the user to pass the test using the following answer;
const myConcat = (arr1, arr2) => arr1.push(arr2);
console.log(myConcat([1, 2], [3, 4, 5]));

And the console below displays "3"
Further testing reveals it will also pass with the following code;
const myConcat = () => {};
console.log(3);
*The HINT answer also advises to use the .concat method, which likely hasn't been presented to the user before.

**Add a Link to the page with the problem:**
https://www.freecodecamp.org/learn/javascript-algorithms-and-data-structures/es6/write-arrow-functions-with-parameters

**Tell us about your browser and operating system:**
* Browser Name: Firefox
* Browser Version: 77.0.1 (64-bit)
* Operating System: Linux Mint 19.3 Tricia
Screenshot_2020-06-11 freeCodeCamp org

**If possible, add a screenshot here (you can drag and drop, png, jpg, gif, etc. in this box):**

### PR DESCRIPTION
**Pull request by Issue-03**
Checklist:

- [x] I have read [freeCodeCamp's contribution guidelines](https://contribute.freecodecamp.org).
- [x] My pull request has a descriptive title (not a vague title like `Update index.md`)
- [x] My pull request targets the `master` branch of freeCodeCamp.
- [x] All the files I changed are in the same world language, for example: only English changes, or only Chinese changes, etc.

Closes #39049

**Before:**

The lesson on page will allow the user to pass the test using the following answer;
```
const myConcat = (arr1, arr2) => arr1.push(arr2);
console.log(myConcat([1, 2], [3, 4, 5]));
```

And the console below displays "3"
Further testing reveals it will also pass with the following code;
```
const myConcat = () => {};
console.log(3);
```

**After:**

It won't pass something like this now:

```
const myConcat = () => {};
console.log(3);
```

or this:

` #const myConcat = eval("(func"+"tion(){})");`

### CODE REVIEW

**Comment by Manish-Giri** [comment]
While this fix takes care of the current issue, I wonder if we could add an additional test or two to ensure that the user makes use of `.concat()` and `arr1`, `arr2` are unchanged? Because currently something like this will pass all the tests -
```js
const myConcat = () => [1,2,3,4,5];
```

This should make the tests more robust. @ojeytonwilliams Thoughts?

**Review by Manish-Giri — COMMENTED** [review]
While this fix takes care of the current issue, I wonder if we could add an additional test or two to ensure that the user makes use of `.concat()` and `arr1`, `arr2` are unchanged? Because currently something like this will pass all the tests -
```js
const myConcat = () => [1,2,3,4,5];
```

This should make the tests more robust. @ojeytonwilliams Thoughts?

**Comment by ojeytonwilliams** [comment]
@Manish-Giri I think it's reasonable as is and we generally want to avoid adding too many tests.  They can clutter up a challenge.  That said, just adding a single extra test which passes different arguments to `myConcat` would be fine.

**Review by ptkpyitheim — COMMENTED** [review]
Looks good to me! I'm new to the community. Hi everyone.

**Comment by Sky020** [comment]
@Manish-Giri Are we going to move ahead with this PR as is? Or, ask @Issue-03 to add one more test to ensure there are parameters used within the function?

**Comment by RandellDawson** [comment]
Since the whole point of the challenge is to learn how to write functions (with parameters) using arrow function syntax, the final solution should validate the function has the overall skeleton like:
```js
const myConcat = (arr1, arr2) => {
  return
}
```
OR
```js
const myConcat = (arr1, arr2) => 
```
and return the correct value `[1, 2, 3, 4, 5]`.

Based on the point of the lesson, I personally believe we should validate that the variables `arr1` and `arr2` appear outside of comments.  Plus I believe there should be one additional test case (with different array arguments), so a user can not just return the literal array `[1, 2, 3, 4, 5]`.  We show the user the `concat` method, so they should be using that, but unless we explicitly state to use the `concat` method, which is not the purpose of the lesson, I say we should not restrict the solution to only use concat.

**Comment by Sky020** [comment]
@RandellDawson It seems fair to check for the use of parameters as well as not just returning the answer.
> We show the user the concat method, so they should be using that, but unless we explicitly state to use the concat method, which is not the purpose of the lesson, I say we should not restrict the solution to only use concat.

Seeing as this is the seed code:
```
var myConcat = function(arr1, arr2) {
  "use strict";
  return arr1.concat(arr2);
};

console.log(myConcat([1, 2], [3, 4, 5]));

```
What about using comments:
```
var myConcat = function(arr1, arr2) {
  /* Do not change code below this line */
  "use strict";
  return arr1.concat(arr2);
  /* Do not change code above this line */
};

console.log(myConcat([1, 2], [3, 4, 5]));
```
It sidesteps any issue of the use/knowledge of `concat`

**Comment by RandellDawson** [comment]
> It sidesteps any issue of the use/knowledge of concat

True, but would not allow the user to write:
```js
const myConcat = (arr1, arr2) => arr1.concat(arr2);
```

**Comment by Manish-Giri** [comment]
@Sky020 Sorry, missed your ping! Personally, I prefer an additional test to check the usage of parameters, since that's what this challenge is about, but I can also understand the rationale behind cluttering the existing tests. I am fine either way.

**Comment by Sky020** [comment]
What about adding a test like (I am struggling to think a better text description):
```
  - text: <code>myConcat()</code> should not brute-force <code>[1, 2, 3, 4, 5]</code>
    testString: assert(!/\[1,2,3,4,5\]/.test(code.replace(/\s/g, '')));
```

I realise this can be cheated with
```
const myConcat = (arr1, arr2) => {
  const a = [1,2,3]
  a.push(4, 5)
  return a
}

console.log(myConcat([1, 2], [3, 4, 5]));
```

**OR**
Add another test checking for `assert.deepEqual([1, 4, 7, 9], myConcat([1, 4], [7, 9]));`

**Comment by nhcarrigan** [comment]
@Sky020 - For the description, would this work?
```
- text: <code>myConcat()</code> should not have the <code>[1, 2, 3, 4, 5]</code> result hard coded.
```

**Comment by Sky020** [comment]
@nhcarrigan Thank you! I have been trying to think of the words _"hard-coded"_ for too long.

I would make it more concise with:
```
- text: You should not hard-code <code>[1, 2, 3, 4, 5]</code>.
```

But I am leaning more towards a test that checks the concatenation of different arrays.

**Comment by moT01** [comment]
The content of the function seems pretty irrelevant to me. I think we just need a test that checks if they turn the function into an arrow function with the two parameters. 

How about replacing the third test with something like this:
"myConcat should be an arrow function with `arr1` and `arr2` as parameters"
/myConcat\s*=\s*\(\s*arr1\s*,\s*arr2\s*\)\s*=>/.test(code) && typeof myConcat === 'function';

I'm not opposed to adding another test for checking the return, but I don't think it's necessary. The existing test for that is fine with me.

**Comment by Sky020** [comment]
@moT01 I agree. Let us do this, but I would recommend this change:

```
- text: <code>myConcat</code> should be an arrow function with two parameters
testString: assert(/myConcat=\(\w+,\w+\)=>/.test(code.replace(/\s/g, '')) && typeof myConcat === 'function');
```

**Comment by RandellDawson** [comment]
@moT01 I like @Sky020's suggestion for the simplified regex (white-space removed).

**Comment by moT01** [comment]
If you two agree, then I'm fine with it - but I think we should make sure that the parameters are `arr1` and `arr2`?

**Comment by Sky020** [comment]
@moT01 I am fine with either. The test text will just need to be sure to clearly state, if a user has decided to change them.

**Review by RandellDawson — APPROVED** [review]
LGTM

**Comment by RandellDawson** [comment]
@Sky020 If you are fine with all the changes, feel free to merge.

**Review by ShaunSHamilton — APPROVED** [review]
Hi @Issue-03 . Congrats on your first pull request (PR)! 🎉

Thank you, for your contribution to the page! 👍
We are happy to accept these changes and look forward to future contributions. 📝

**Pull request merged**
