### PR TITLE
fix(learn): Added code tags to translated texts

### LINKED ISSUE #38312: Need to update a few challenges' test texts to wrap certain values in code tags to prevent translation in other languages
Following up on the [comment on PR 38309](https://github.com/freeCodeCamp/freeCodeCamp/pull/38309#discussion_r386444356), the following English challenge tests need to be updated as described, as the non-English version were translating these when they should not have been translated.

* Standardize Times with the HTML5 datetime Attribute
**Issues:** All tests need to be re-translated

* Use the strong Tag to Make Text Bold 
**Issues:**  "Stanford University" needs code tags so it is not translated.

* Add a Submit Button to a Form
**Issues:** "Submit" needs code tags so it is not translated

* Add Placeholder Text to a Text Field
**Issues:** "cat photo URL" needs code tags so it is not translated

* Create an Ordered List
**Issues:** The first test text "Top 3 things cats hate:" needs code tags so it is not translated.  The same goes for the second test text "Things cats love:"

* Headline with the h2 Element
**Issues:** The third test text "CatPhotoApp" needs code tags so it is not translated. 

* Inform with the Paragraph Element
**Issues:**  The second test text "Hello Paragraph" needs code tags so it is not translated.

* Use the u Tag to Underline Text
**Issues:** The second test text "Ph.D. students" needs code tags so it is not translated.

### PR DESCRIPTION
**Pull request by ShaunSHamilton**
Checklist:

- [X ] I have read [freeCodeCamp's contribution guidelines](https://github.com/freeCodeCamp/freeCodeCamp/blob/master/CONTRIBUTING.md).
- [X ] My pull request has a descriptive title (not a vague title like `Update index.md`)
- [X] My pull request targets the `master` branch of freeCodeCamp.
- [X] All the files I changed are in the same world language, for example: only English changes, or only Chinese changes, etc.

Closes #38312

Followed @RandellDawson detailed description of what test texts needed `code` tags, in order to fix a previous pull request.

`npm run test:curriculum` has been run, and all tests passed.

### CODE REVIEW

**Comment by RandellDawson** [comment]
@Sky020 Your forked branch has not been updated since Oct, 5, 2019, so you really should sync it up.  In general, before creating a new PR, you always want to sync your master branch first and then create a branch off of it.  The merge conflicts above are caused by that issue.  I have fixed them for you.

**Comment by raisedadead** [comment]
Blocked by #38308

**Comment by RandellDawson** [comment]
@raisedadead This PR will be a good first test of the bot I am working on when we unblock the repo.  These are all Responsive Web Design challenges.

**Comment by raisedadead** [comment]
There are additional PRs that I blocked. Please take a look at those as well.

**Comment by Sky020** [comment]
> @Sky020 Your forked branch has not been updated since Oct, 5, 2019, so you really should sync it up. In general, before creating a new PR, you always want to sync your master branch first and then create a branch off of it. The merge conflicts above are caused by that issue. I have fixed them for you.

Apologies for that. I have been using GitHub Desktop, and assumed using the _fetch upstream_ button would sync up my repo with fCC's. Are these the commands that will do what you are referring to:
```
git reset --hard upstream/master
git push origin master --force
```

**Comment by RandellDawson** [comment]
@Sky020 When resolving merge conflicts, I use:
```
git pull --rebase upstream master
git push origin master --force
```

**Review by tinktink1 — COMMENTED** [review]
I really liked the changes that you made! I am glad you were able to figure out how to update to the latest version.

**Review by moT01 — CHANGES_REQUESTED** [review]
I believe this needs a rebase and has a conflict or two. Also, I'm thinking we should remove the quotes inside most of those code tags. My opinion anyway - the code tags should be the exact text or code, the quotes aren't part of the text.

**Comment by Sky020** [comment]
@moT01 
>  I'm thinking we should remove the quotes inside most of those code tags.

I agree. _This was my first PR_ 🙈

**Review by RandellDawson — APPROVED** [review]
@moT01 LGTM

**Review by moT01 — APPROVED** [review]
LGTM @Sky020 🎉 Congratulations on your first PR 🎉 😉

**Pull request merged**
