### PR TITLE
Mention returning undefined in "Finders Keepers"

### PR DESCRIPTION
**Pull request by Kwpolska**
#### Pre-Submission Checklist

- [x] Your pull request targets the `staging` branch of FreeCodeCamp.
- [x] Branch starts with either `fix/`, `feature/`, or `translate/` (e.g. `fix/signin-issue`)
- [x] You have only one commit (if not, [squash](http://forum.freecodecamp.com/t/how-to-squash-multiple-commits-into-one-with-git/13231) them into one commit).
- [ ] All new and existing tests pass the command `npm test`. Use `git commit --amend` to amend any fixes. [is that really necessary for a simple text change? considering how hard the setup is?]

#### Type of Change

- [x] Small bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds new functionality)
- [ ] Breaking change (fix or feature that would change existing functionality)
- [ ] Add new translation (feature adding new translations)

#### Checklist:

- [ ] Tested changes locally.
- [ ] Closes currently open issue (replace XXXX with an issue no): Closes #XXXX

#### Description

The "Finders Kepeers" challenge text does not mention the need to return `undefined` if no element passes the truth test. Therefore, students can’t do it without checking the challenge tests.

### CODE REVIEW

**Comment by Bouncey** [comment]
@Kwpolska Thanks for the PR :+1: 

Can you point me in the direction of the original issue please?

**Comment by Kwpolska** [comment]
What original issue? (I didn’t create any GitHub issues if that’s what you ask.)

**Comment by Bouncey** [comment]
## LGTM :+1: 

Thanks for contributing :tada:

**Comment by aureliojuarezcortez** [comment]
(*AurelioJuarezCortez.wow)

**Comment by teeleek** [comment]
puttasak insee

**Pull request merged**
