### PR TITLE
fix: use lodash-es in the client

### PR DESCRIPTION
**Pull request by ojeytonwilliams**
This isn't a *huge* saving in bundle size, but it is a saving.  According to the [bundle analyzer](https://www.gatsbyjs.com/plugins/gatsby-plugin-webpack-bundle-analyser-v2/):

lodash:

stat: 208kb
parsed: 42.8kb
gzip: 13kb

lodash-es: 
stat: 143.15kb
parsed: 30kb
gzip: 9kb

### CODE REVIEW

**Comment by ojeytonwilliams** [comment]
The fact we still need lodash itself for both Jest and various node scripts is a pain, but we'll be able to move everything to ES modules eventually.

**Comment by ojeytonwilliams** [comment]
@raisedadead Speaking of pain... The problem with Mocha is that it's relying on @babel/register and that converts `import`s to `require`s on the fly.  The reason that's a problem is that 
 when you do this for https://github.com/freeCodeCamp/freeCodeCamp/blob/main/client/src/templates/Challenges/rechallenge/transformers.js it means it will try to `require` lodash-es and fail because you can't do that with an ES module.
 
 There might be a clever way to do this, but I'm not seeing it.  Using `esm` in Mocha just creates an even more cryptic error.
 
 Options:

1. Revert to lodash and only use lodash/core which is considerably smaller
2. Figure out an analog to https://jestjs.io/docs/configuration#modulenamemapper-objectstring-string--arraystring
3. Abandon these in favour of browser tests, that @Sembauke is working on 

I'm leaning towards 1 and 3.

**Comment by raisedadead** [comment]
You said:

> This isn't a huge saving in bundle size, but it is a saving.

Looking at the milliseconds that will we shave off. Is this worth fixing? 

I do not see us practically (and more importantly reliably) depending only on browser tests for the QA PASS in favor of what we have now, for a few weeks. You know just a standard let the process "mature and age" type thing.

To give you inspiration I would definitely say what's please do whatever is the best use of your efforts and time.

**Comment by ojeytonwilliams** [comment]
> To give you inspiration I would definitely say: please do whatever is the best use of your efforts and time.

Yeah, it seemed reasonable when I started out, but less so now.  I'm going to see if https://www.npmjs.com/package/lodash-webpack-plugin helps at all and potentially use that.  Otherwise, I'll create an issue in case someone who's made of sterner stuff than I am wants to take a look.

**Comment by ojeytonwilliams** [comment]
@raisedadead I went away, had lunch and realised there was a simple solution :man_facepalming:

**Review by raisedadead — APPROVED** [review]

**Review by moT01 — APPROVED** [review]
LGTM 🎉

**Pull request merged**
