### PR TITLE
fix(curriculum): pass tests with x and y overflows

### LINKED ISSUE #47513: Broken test: Step 5 of Learn CSS transforms by building a penguin
### Describe the Issue

Instruction: Remove both the horizontal and vertical scrollbars, and prevent programmatic scrolling, using only one property.
Hint: You should give body and overflow of clip.
I typed in overflow: clip; to the list of properties: values; within the body selector. Even the hint is giving me the same answer, but the code will not pass. I tried different browsers, checked for extensions and updates, but so far nothing has fixed this.

### Affected Page

https://www.freecodecamp.org/learn/2022/responsive-web-design/learn-css-transforms-by-building-a-penguin/step-5

### Your code

```
body { background-color: linear-gradient(45deg, rgb(118, 201, 255), rgb(247, 255, 222)); margin: 0; padding: 0; width: 100%; height: 100vh; overflow: clip; }

```

### Expected behavior

Since I typed overflow: clip; I expected the overflow to be clipped with the rest of the content hidden, and scrolling should be forbidden. According to the hint that comes up and the forum post about this exact issue, I’ve entered the correct code. However, the test keeps failing.

### Screenshots

_No response_

### System

- Device: iPad Pro
- OS: iOS 15.6.1
- Browser: Safari, Chrome, Firefox
- Version: iPadOS 15.6.1

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by ojeytonwilliams**
It's not necessary, but may help the test pass on iPads

Checklist:

- [x] I have read [freeCodeCamp's contribution guidelines](https://contribute.freecodecamp.org).
- [x] My pull request has a descriptive title (not a vague title like `Update index.md`)
- [x] My pull request targets the `main` branch of freeCodeCamp.
- [x] I have tested these changes either locally on my machine, or GitPod.

This is a bit of a wild hunch but it may close

Close https://github.com/freeCodeCamp/freeCodeCamp/issues/47513

### CODE REVIEW

**Comment by naomi-lgbt** [comment]
@moT01 can you take a look at this one on Safari?

__
[sema-logo](https://semasoftware.com/gh) &nbsp;**Summary:** :question: I have a question

**Review by moT01 — CHANGES_REQUESTED** [review]
No, this doesn't pass for me on my Safari.

I looked around a little bit to see if I could find anything that would help. Nothing seems to be changed in the dom that we can query here:
Screen Shot 2022-09-15 at 1 18 39 PM

The property just isn't added anywhere. I also didn't see any way to easily enable this in my safari settings. So we may want to regex it. 

We could potentially change this to `overflow: hidden` - I only glanced at it, but the `clip` seems to have a very specific purpose, and I don't think it applies here. `hidden` gives us the same result. Not sure why we went this route.

Safari <= July 19, 2022 (< 16.0) will have have this issue. So perhaps we shouldn't be teaching it - or maybe just mention it once. The way this step is worded, I think we must have taught it previously. I think `hidden` is much more common and `clip` is likely used only rarely, but I'm not sure.

**Comment by naomi-lgbt** [comment]
I'd be fine swapping this for `overflow: hidden` - `clip` has the feature of preventing programmatic scrolling, but this is a penguin do we need that

**Comment by naomi-lgbt** [comment]
@ojeytonwilliams are you fine with closing this in favour of https://github.com/freeCodeCamp/freeCodeCamp/pull/48163?

**Comment by ojeytonwilliams** [comment]
Absolutely. I don't think this PR does anything.  Thanks, @naomi-lgbt!

**Pull request closed without merging**
