### PR TITLE
fix(client): keep editor tabs buttons visible

### LINKED ISSUE #52641: [Multi-file template] Issues with panel toggle buttons
### Describe the Issue

I found 2 issues with this template:
- The "Instructions" toggle button is not highlighted when it is on (`aria-expanded="true"`)
- When the instructions panel is closed, the editor toggle buttons disappear

| Instructions on | Instructions off |
| --- | --- |
| Screenshot 2023-12-20 at 16 12 36 | Screenshot 2023-12-20 at 16 18 37 |

### Affected Page

Projects that use the multi-file template. Example: https://www.freecodecamp.org/learn/2022/responsive-web-design/build-a-survey-form-project/build-a-survey-form

### Steps to Reproduce

1. Go to https://www.freecodecamp.org/learn/2022/responsive-web-design/build-a-survey-form-project/build-a-survey-form
2. Check the display of the "Instructions" button. It's not highlighted even though the instructions panel is open
3. Click the "Instructions" button
4. See the disappearance of the editor toggle buttons

### Expected behavior

I expect that:
- The "Instructions" toggle button should be highlighted when it is on
- The editor toggle buttons should be on the screen when the instructions panel is closed

But will wait for the core team to confirm.

### PR DESCRIPTION
**Pull request by gikf**
Checklist:

- [x] I have read and followed the [contribution guidelines](https://contribute.freecodecamp.org).
- [x] I have read and followed the [how to open a pull request guide](https://contribute.freecodecamp.org/#/how-to-open-a-pull-request).
- [x] My pull request targets the `main` branch of freeCodeCamp.
- [x] I have tested these changes either locally on my machine, or GitPod.

Closes #52641

- - -
- Consistent styling for _Instructions_ button.
- Editor tabs buttons stops being hidden when _Instructions_ are not expanded.
- For somebody who knows very little of css, let's call this quite eventful. `.monaco-editor-tabs` div was being hidden by the style from the universal nav https://github.com/freeCodeCamp/freeCodeCamp/blob/987fe44b27f561dda6f3fec4778d7fa70e650a79/client/src/components/Header/components/universal-nav.css#L426-L428
- Now this makes me think, it might be better to make that one to apply only to `#universal-nav`.

### CODE REVIEW

**Comment by ojeytonwilliams** [comment]
@gikf the playwright failures for random quote seem unrelated. I'm hoping that https://github.com/freeCodeCamp/freeCodeCamp/pull/53375 will fix them.

**Comment by gikf** [comment]
@ojeytonwilliams that's kind of expected now and then. What surprised me is test checking the wrong behavior of _Instructions_ button :grin:

**Comment by ojeytonwilliams** [comment]
>  confirming the wrong behavior of Instructions button 

Oh wow, that's just weird.

**Review by ojeytonwilliams — COMMENTED** [review]
> For somebody who knows very little of css, let's call this quite eventful. .monaco-editor-tabs div was being hidden by the style from the universal nav
> Now this makes me think, it might be better to make that one to apply only to #universal-nav.

I'm not a CSS expert, but I agree that generally it's better to keep the CSS changes as specific as possible.  My only concern is that we might have been relying on their generality

However, I think it makes sense to restrict the `display: none` rules to the universal nav and then see if any `div`s appear that shouldn't.

**Comment by gikf** [comment]
I haven't noticed any obvious issues after limiting the scope to `#universal-nav`. These two rules appear to have been added just few months ago, it's possible they didn't yet have enough time ( :stuck_out_tongue: ) to be unknowingly used elsewhere.

**Review by moT01 — APPROVED** [review]
LGTM 🎉 I didn't see any negative side-effects from changing the selectors.

**Review by ojeytonwilliams — APPROVED** [review]
Chees, @gikf. This LGTM, :+1:

**Pull request merged**
