### PR TITLE
fix(curriculum): step 11 implict return fix

### LINKED ISSUE #55851: Building a Todo App - Step 11 - implicit return
### Describe the Issue

The step doesn't call for an implicit return to be used, but it won't pass without using one.  The following is what the step asked to do: 

"Use const to declare a variable called ```dataArrIndex``` and assign it the value of ```taskData.findIndex()```. For the ```findIndex()``` method, pass in an arrow function with item as the parameter.

Within the arrow function, check if the id property of item is strictly equal to the id property of currentTask."  

### Affected Page

https://www.freecodecamp.org/learn/javascript-algorithms-and-data-structures-v8/learn-localstorage-by-building-a-todo-app/step-11

### Your code

The following code was my initial answer to this step. 

```
  const dataArrIndex = taskData.findIndex((item) => {
    item.id === currentTask.id;
  })
```

This is the only code that I have been able to get to pass this step. 

```
  const dataArrIndex = taskData.findIndex((item) => item.id === currentTask.id)
```

### Expected behavior

This step should pass with my first code since the step doesn't call for Implicit return.  The other option would be update the step to call for an implicit return. 

### Screenshots

_No response_

### System

- Device: Macbook
- OS: macOS
- Browser: safari
- Version: 17.6

### Additional context

Here is a link to my post out on the forum for this issue as well.

* https://forum.freecodecamp.org/t/learn-localstorage-step-11/706026/4

### PR DESCRIPTION
**Pull request by gagan-bhullar-tech**
Checklist:

- [x] I have read and followed the [contribution guidelines](https://contribute.freecodecamp.org).
- [x] I have read and followed the [how to open a pull request guide](https://contribute.freecodecamp.org/how-to-open-a-pull-request/).
- [x] My pull request targets the `main` branch of freeCodeCamp.
- [x] I have tested these changes either locally on my machine, or GitPod.

Closes #55851

### CODE REVIEW

**Comment by lasjorg** [comment]
I'm not sure we have reached a consensus on this.

But no matter what, we should update the description to include information about the callback. Please refer back to the issue for the text.

**Comment by gagan-bhullar-tech** [comment]
@lasjorg thanks. Updated PR.

**Review by a2937 — COMMENTED** [review]
On one hand, you've updated the description to the right text. On the other hand, I can't exactly call the issue solved as the main problem isn't taken of. 

I'm personally for the inclusion of all valid syntax but it doesn't look like a consensus was ever fully reached.

**Review by moT01 — CHANGES_REQUESTED** [review]
We need to update the test to allow for implicit or explicit return in the arrow function.

**Comment by gagan-bhullar-tech** [comment]
@moT01 updated PR.

**Comment by moT01** [comment]
The code from the issue isn't passing:

```js
const dataArrIndex = taskData.findIndex((item) => {
  item.id === currentTask.id;
})
```

Something might be missing from that regex, but I didn't look at it too hard to find it. Do you want to take a look at that @gagan-bhullar-tech? Thanks. Or let me know what I am missing.

**Comment by moT01** [comment]
My bad. I'll take another look.

**Review by moT01 — APPROVED** [review]
yup, forgot the return keyword. LGTM 🎉

**Review by a2937 — APPROVED** [review]
I've tested with the solutions that work (and remembered my return statement). 

Thusly it looks good to me.

**Pull request merged**
