### PR TITLE
fix(curriculum): quotes in tests

### PR DESCRIPTION
**Pull request by ValeraS**
- [x] I have read [freeCodeCamp's contribution guidelines](https://github.com/freeCodeCamp/freeCodeCamp/blob/master/CONTRIBUTING.md).
- [ ] My pull request has a descriptive title (not a vague title like `Update index.md`)
- [x] My pull request targets the `master` branch of freeCodeCamp.
- [x] None of my changes are plagiarized from another source without proper attribution.
- [x] My article does not contain shortened URLs or affiliate links.

If your pull request closes a GitHub issue, replace the XXXXX below with the issue number.

Closes #XXXXX

@Bouncey  after replacing `''` to `"`, some tests became broken. I have reverted a commit https://github.com/freeCodeCamp/freeCodeCamp/pull/18277/commits/233922c8081147fe9004df0397c392bcac0c4501 and have simplified quotes. 

@beaucarnes Need to redo challenges for other languages.

### CODE REVIEW

**Comment by lynxlynxlynx** [comment]
What disaster warranted this (and why didn't it get reverted)?

**Comment by ValeraS** [comment]
For example:
changed test behavior
https://github.com/freeCodeCamp/freeCodeCamp/commit/233922c8081147fe9004df0397c392bcac0c4501#diff-8d377b9fd2a899b7d2d08753b09a314cR27

test broken
https://github.com/freeCodeCamp/freeCodeCamp/commit/233922c8081147fe9004df0397c392bcac0c4501#diff-709cacc7833f0b49e3d12770dc10f889R33

**Comment by lynxlynxlynx** [comment]
No, before that, this "transform".

**Comment by raisedadead** [comment]
Wait we need to get the tests working on CI once again. This will have to be caught on the CI. @ValeraS will you be interested? Also, tagging along @tchaffee who may be able to jump in as well.

We can get on a call if you all are okay?

**Comment by ValeraS** [comment]
@raisedadead @Bouncey old tests checked compliance with the scheme. And these changes will pass this type of tests.
IMO we need to freeze changes of challenges or at least revert the commit https://github.com/freeCodeCamp/freeCodeCamp/commit/233922c8081147fe9004df0397c392bcac0c4501 before we decide what to do.

**Comment by tchaffee** [comment]
I just got back from traveling with limited internet access. I can try to help with this but I'm not sure where we are with this? In what way can I help?

**Comment by raisedadead** [comment]
Hi @ValeraS 

I think we can't revert because that's a needed change. We screwed up in the initial migration from json to markdown.

Your changes look valid. I am going to merge them. Can you please resolve a commit. @RandellDawson recently fixed a bunch of unwanted escaping.

That said, @tchaffee @ValeraS right now, me and stuart are working on ways to test the solutions in the curriculum against their tests. This would most likely be done in something like mocha with a test runner (we want to ensure that browser tests work)

We would love your help with this.

Thanks

**Comment by ValeraS** [comment]
@raisedadead it passes all old tests with #24180

**Pull request merged**
