### PR TITLE
Add head/tail to challenges spec

### LINKED ISSUE #4107: Add head/tail (wrapping) to challenge spec/commonFramework

### PR DESCRIPTION
**Pull request by BerkeleyTrue**
Also lint, serious lint.

closes #4107

### CODE REVIEW

**Comment by BerkeleyTrue** [comment]
@FreeCodeCamp/issue-moderators Please QA and merge

**Comment by ltegman** [comment]
QAing now.

**Comment by SaintPeter** [comment]
QAing as well.

**Comment by ltegman** [comment]
Getting an error on the Map that is not in prod:
```
uncaught error: common framework should be loaded
function: reBindModals
```

**Comment by SaintPeter** [comment]
All of the Basic Javascript waypoints are displaying:
`Here are some helpful links:` 
despite not having any MDNLinks in the JSON.

**Comment by SaintPeter** [comment]
Other than the issue noted above, the basic functionality of head/tail seems to work well.  I've reworked several of the bonfires to move the "test function" to the tail and, in one case, moved an entire function definition out to head and tail.  Overall it looks good.

**Comment by BerkeleyTrue** [comment]
Alrighty, I'll fix these issues tonight.

**Comment by ltegman** [comment]
Pushed a fix for the issue pointed out by @SaintPeter and an issue with `bonfireExecute` being run on step challenges. tt looks like the error in `reBindModal` was being thrown because that function runs any time `main.js` is loaded but only the challenges load the common framework. @BerkeleyTrue Hopefully it's a satisfactory solution to just return from the function when common isn't loaded instead of throwing.

**Comment by BerkeleyTrue** [comment]
Yeah that works great. Moving that stuff into commonFramework is the next step.

**Comment by ltegman** [comment]
Okay, I think we're good then :smile:

**Pull request merged**
