### PR TITLE
Fixed issue with accessibility challenge about contrast

### LINKED ISSUE #17495: Fix content on Applied accessibility
I recommend checking the following content to analyse if this should be fixed (I’m using Chrome on Windows):

On the page[ Applied Accessibility - Avoid Colorblindness Issues by Using Sufficient Contrast](https://forum.freecodecamp.org/clicks/track?url=https%3A%2F%2Flearn.freecodecamp.org%2Fresponsive-web-design%2Fapplied-accessibility%2Favoid-colorblindness-issues-by-using-sufficient-contrast&post_id=436010&topic_id=197853) the text separates two types of colors: darker and lighter colors, being blue, violet, magenta and red the former, and green, yellow, orange, blue-green the latter. I don’t think this information is accurate. All hues have darker and lighter tones, tints and shades. The author of the text was probably trying to talk about warm and cold colors, being green, yellow and red the former, and violet and blue the latter. See the following image: http://www.aridglamor.com/wp-content/uploads/2014/03/tintsshades.jpg

On the page [Make Links Navigatable with HTML Access Keys](https://forum.freecodecamp.org/clicks/track?url=https%3A%2F%2Flearn.freecodecamp.org%2Fresponsive-web-design%2Fapplied-accessibility%2Fmake-links-navigatable-with-html-access-keys&post_id=436010&topic_id=197853) the text says that we should use the accesskey to use the keys to go direct to the element with the accesskey attribute, but it doesn’t say that we should type ALT + key (windows) to make it work. For exemple, a tag with the attribute accesskey=“a” will only work if you type ALT + a. I think this information should be added to the page. For more accurate information about the correct shortcut key to access this property, see this link: https://www.w3schools.com/tags/att_global_accesskey.asp

On the page [Applied Accessibility - Use tabindex to Specify the Order of Keyboard Focus for Several Elements](https://forum.freecodecamp.org/clicks/track?url=https%3A%2F%2Flearn.freecodecamp.org%2Fresponsive-web-design%2Fapplied-accessibility%2Fuse-tabindex-to-specify-the-order-of-keyboard-focus-for-several-elements&post_id=436010&topic_id=197853) the text says that if we use the attribute tabindex with the value of any positive numbers like 1, 2, 3, etc, the tab will first follow the order of these elements, and after this, they go the the other elements. This is not true, it doesn’t happen. Any value in the tabindex attribute that is different from 0, be it positive or negative, will make the tab jump over the element and ignore it. This is what happened to me using chrome on windows.

Bug on the last page of [Responsive Web Design - Make typography responsive](https://learn.freecodecamp.org/responsive-web-design/responsive-web-design-principles/make-typography-responsive)
After finishing the challenge, the page fails in trying to open the next challenge, which is the first page of the CSS Flexbox. Weirdly, the url of the adressbar of the browser changes to the url of the flexbox introduction page, but we remain in the Make Typography Responsive page.

### PR DESCRIPTION
**Pull request by thecodingaviator**
- [x] I have read [freeCodeCamp's contribution guidelines](https://github.com/freeCodeCamp/freeCodeCamp/blob/master/CONTRIBUTING.md).
- [x] My pull request has a descriptive title (not a vague title like `Update index.md`)
- [x] My pull request targets the `master` branch of freeCodeCamp.
- [x] None of my changes are plagiarized from another source without proper attribution.
- [x] My article does not contain shortened URLs or affiliate links.

Partly fixes #17495

### CODE REVIEW

**Comment by thecodingaviator** [comment]
@Asjas

**Comment by moT01** [comment]
Thank you for your PR, but this does not improve the challenge description, and sounds a little repetitive.

Hey @thecodingaviator, sorry for closing all these PR's of yours - but the challenge descriptions need to stay as short as possible - and like I said, I don't think the PR's are improving them. If you think I'm wrong, feel free to make your case - I hope this doesn't discourage you.

Thanks, and happy coding!

**Comment by moT01** [comment]
On second thought after reading the issue, I think something could be done here - but I'm not sure this sentence best describes how to reach the contrast ratio...

**Comment by moT01** [comment]
@thecodingaviator change the sentence to something like this... 
In practice, the 4.5:1 contrast ratio can be reached by shading (adding black) to the colder color and tinting (adding white) to the warmer color. Colder colors are considered to be hues of blues, violets, and greens; whereas warmer colors are hues of oranges, yellows, and reds.

**Comment by thecodingaviator** [comment]
@moT01 Does it look better now?

**Comment by moT01** [comment]
Hmm, perhaps I don't know enough about colors and their properties - your original edit might have been fine - I think they both work after taking another look - so you can leave it like this or put it back to what you had originally - sorry about that, Thanks!

**Comment by thecodingaviator** [comment]
@moT01 I think its fine even now.....

**Comment by RandellDawson** [comment]
I closed/re-opened in an attempt to clear Travis error.

**Comment by nikrb** [comment]
@RandellDawson I think camper bot was a bit over zealous here, but I've tested it locally anway, LGTM.

**Comment by RandellDawson** [comment]
@nikrb camberBot adds the `status: need to test locally` label to any curriculum folder change.  Sometimes only description or instructions verbiage changes, but we felt the extra label brings attention to it just in case someone changes the description and/or instructions enough that the  tests might need to be rewritten also (which would require testing).

**Comment by RandellDawson** [comment]
@moT01 If you are ok with the latest changes, then feel free to merge them.  I am fine with the PR as it stands now.

**Review by RandellDawson — APPROVED** [review]

**Pull request merged**
