### PR TITLE
fix(client): i18n project and certification titles in settings, profile and certification page

### LINKED ISSUE #40998: Staging/i18n: Project and certificates titles are untranslatable on settings page
**Describe the bug**

freeCodeCamp aims for all of its content to be translated, but the project titles that appear in the sections "certifications" and "legacy certifications" of the user settings page are not translated.

**To Reproduce**
1. Go to https://www.freecodecamp.dev/espanol/settings
2. Sign in
3. Scroll down to 'Certifications'
4. See untranslated strings

To reproduce this Locally, change the below values in `.env` to your desired language.

```
# Languages to build
CLIENT_LOCALE=english
CURRICULUM_LOCALE=english
```

**Expected behavior**

The title should be properly translated, linking the used values to a respectable JSON file should make it so.

Here is the file for the projects [intro.json](https://github.com/freeCodeCamp/freeCodeCamp/blob/main/client/i18n/locales/english/intro.json), you can use it.
here are the used components:

- [certification.js](https://github.com/freeCodeCamp/freeCodeCamp/blob/main/client/src/components/settings/certification.js)
- [time-line.tsx](https://github.com/freeCodeCamp/freeCodeCamp/blob/main/client/src/components/profile/components/time-line.tsx)

**Screenshots**
- Spanish:
image
- Chinese:
image

**Desktop (please complete the following information):**
- OS: [Windows 10]
- Browser: [chrome]
- Version: [88]

**Additional Context**

If you would like to fix this issue, please make sure you read [our guidelines for contributing](https://contribute.freecodecamp.org/#/), we prioritize contributors following the instructions in our guides. Join us in [our chat room](https://discord.gg/PRyKn3Vbay) or [the forum](https://forum.freecodecamp.org/c/contributors/3) if you need help contributing, our moderators will guide you through this.

### PR DESCRIPTION
**Pull request by Nirajn2311**
Checklist:

- [x] I have read [freeCodeCamp's contribution guidelines](https://contribute.freecodecamp.org).
- [x] My pull request has a descriptive title (not a vague title like `Update index.md`)
- [x] My pull request targets the `main` branch of freeCodeCamp.
- [x] I have tested these changes either locally on my machine, or GitPod.

Closes #40998 

~~I created a new json file for storing the certification and project titles so that it'll be easier to update them in the future.~~

### CODE REVIEW

**Review by Sboonny — COMMENTED** [review]
I discussed the possible solution with Naomi, and she mentioned we should avoid the creation of a new file as much as possilbe

**Comment by Nirajn2311** [comment]
I see. I'll put everything back into the `translations.json` file then

**Comment by Sboonny** [comment]
Is it ready for review?

**Comment by Nirajn2311** [comment]
Yes it's ready for review now

**Comment by Nirajn2311** [comment]
Yup, now it's ready for review. The titles have been fixed across all 3 pages: settings, profile and certification page

**Review by Sboonny — APPROVED** [review]
LGTM 🎉, thank you for your contribution to the page! 👍. Awesome work

**Comment by raisedadead** [comment]
We are officially on Node.js 18 now. We have changed the merge requirements accordingly.

You will need to rebase this PR against the main branch OR Click the "Update branch" button to get the new checks going.

Thanks for your contribution.

**Comment by naomi-lgbt** [comment]
I feel like creating new JSON data for this is the wrong approach.

Certification titles are already translated:

image


We should instead pull from where these translations are, so we don't have to duplicate everything.

**Comment by Nirajn2311** [comment]
Ok I dint see this key `learn.cert-map-estimates.certs` before and so with the different varieties I just created new data.

Also in some places the props hold the dasherized values and in other places it's the whole title.

**Review by raisedadead — APPROVED** [review]
@Nirajn2311 please create a fresh issue to de-duplicate these and preferably assign it to yourself.

**Pull request merged**
