### PR TITLE
feat: add security.txt file

### PR DESCRIPTION
**Pull request by raisedadead**
This adds a security.txt file to the static files for serving on the main domain.

### CODE REVIEW

**Comment by Sembauke** [comment]
They also recommend adding a Digital signature to a security.txt file:
https://datatracker.ietf.org/doc/html/draft-foudil-securitytxt#section-3.3

**Comment by raisedadead** [comment]
> They also recommend adding a Digital signature to a security.txt file:

Yes - it was intentional not because we need to update this file and I wanted to avoid the overhead of signatures because the security policy is the real deal.

**Comment by Sembauke** [comment]
Thank you for the Demo/Explaining.

**Review by naomi-lgbt — APPROVED** [review]
Looks good!

**Review by Sembauke — APPROVED** [review]

**Pull request merged**
