### PR TITLE
chore: replace forum links

### LINKED ISSUE #39138: /forum → forum.freecodecamp.org
We are migrating to the managed Discourse by the Discourse team. Until now we had been doing a semi-on-premise setup.

This migration unfortunately involves us going back to the subdomain for various technical limitations with the new setup.

We need to audit and update the links in the codebase.

Fallback redirects will be setup, but changing as many links as we can will take the load off of the webservers.

### PR DESCRIPTION
**Pull request by naomi-lgbt**
Checklist:

- [X] I have read [freeCodeCamp's contribution guidelines](https://contribute.freecodecamp.org).
- [X] My pull request has a descriptive title (not a vague title like `Update index.md`)
- [X] My pull request targets the `master` branch of freeCodeCamp.
- [ ] All the files I changed are in the same world language, for example: only English changes, or only Chinese changes, etc.

Related to #39138

This pull request should have replaced all instances of "www.freecodecamp.org/forum" and "freecodecamp.org/forum" with "forum.freecodecamp.org", per the linked issue.

### CODE REVIEW

**Review by RandellDawson — CHANGES_REQUESTED** [review]
@nhcarrigan Can you please split this PR up into separate ones by language?  This will make the review process much faster on GitHub.   Plus, we would prefer to merge the English and the Chinese and platform files (if needed) first.  We have the checkbox on the Checklist, to let users know they must not mix the languages on the same PR.

Thank you

@raisedadead Please correct me if I have misspoken here.

**Comment by nhcarrigan** [comment]
Ah! My apologies - I had thought it best to do it all at once, since it seemed to be rather time-sensitive. I will work on splitting them up now.

**Comment by ojeytonwilliams** [comment]
@nhcarrigan is this just a straight replacement of the two strings you mentioned?  I'm looking at other links (in the nav and so on) now, and don't want to clash.

**Comment by raisedadead** [comment]
> We would prefer to merge the English and the Chinese and platform files (if needed) first.

That is correct. We would like to fix everything that is deployed to be merged in first.

**Comment by raisedadead** [comment]
I think if you dropped the changes to `client/src/templates/Challenges/components/HelpModal.js` in this PR and moved it to a different PR, we could merge this one as is after the fact. The redirect handling would take care of it in the interim.

The modal is more critical, because it sends direct traffic to the forum.

**Comment by nhcarrigan** [comment]
@raisedadead I revered the change to the `HelpModal.js` file, as requested. 

@ojeytonwilliams Correct - this is a straight replacement of the link strings.

**Review by raisedadead — APPROVED** [review]

**Pull request merged**
