### PR TITLE
fix: ensure only one lockfile is used

### PR DESCRIPTION
**Pull request by raisedadead**
This should take care of throwing when more than one lockfiles is found in the repo

### CODE REVIEW

**Review by naomi-lgbt — DISMISSED** [review]

**Comment by nhcarrigan** [comment]
We know it works because the CI failed 😁

**Comment by raisedadead** [comment]
There you go! Now the demo works, the first commit ads the test and the next fixes it.

**Review by naomi-lgbt — APPROVED** [review]

**Comment by raisedadead** [comment]
Reminder to unblock https://github.com/freeCodeCamp/freeCodeCamp/pull/45227 when this lands.

**Review by ojeytonwilliams — APPROVED** [review]
That's a neat script, LGTM!

**Pull request merged**
