### PR TITLE
steps-to-upload-an-app-on-Playstore.

### PR DESCRIPTION
**Pull request by Anurag26**
- [x] I have read [freeCodeCamp's contribution guidelines](https://github.com/freeCodeCamp/freeCodeCamp/blob/master/CONTRIBUTING.md).
- [x] My pull request has a descriptive title (not a vague title like `Update index.md`)
- [x] My pull request targets the `master` branch of freeCodeCamp.
- [x] None of my changes are plagiarized from another source without proper attribution.
- [x] My article does not contain shortened URLs or affiliate links.

If your pull request closes a GitHub issue, replace the XXXXX below with the issue number.

Closes #XXXXX

### CODE REVIEW

**Comment by Anurag26** [comment]
@RandellDawson  any idea why the CI build failed for my commit?

**Comment by RandellDawson** [comment]
Yes, I believe it was because you had uppercase letters in your folder name.

**Comment by Anurag26** [comment]
@RandellDawson  are you a part of the freecodecamp org?

**Comment by RandellDawson** [comment]
I am a volunteer helping out with reviews for FCC.

**Comment by Anurag26** [comment]
Oh, that sounds good. I was wondering if there is a way I could volunteer too or is it like invite only.@RandellDawson

**Review by moT01 — APPROVED** [review]
Looks good @Anurag26, thanks for contributing to freeCodeCamp!

**Comment by Anurag26** [comment]
Thank you!

**Pull request merged**
