### PR TITLE
Fix bad UX for splitter of code's panels

### LINKED ISSUE #34358: Bad UX for splitter of description's and code's panels
**Describe the bug**
It is hard to catch the splitter between panels to drag it. Scrolling controls on the splitter makes a bad user experience if one tries to drag it.

**To Reproduce**
1. Go to challenge page like this - https://learn.freecodecamp.org/javascript-algorithms-and-data-structures/basic-javascript/record-collection/
2. Try to drag separator (which is between a code panel and a description)
3. Very hard to catch it by mouse because FF draws a scroll-related ui controls.

**Expected behavior**
The separator should be clicked very easy.

**Screenshots**
Here are screenshots which demonstrate cursor style on top of the scroll controls and on top of the separator. 
Note: width of the separator is set to 25px for convenience.
no resize on top of scroll controls
resize cursor

**Desktop:**
 - OS: Win7
 - Browser: Firefox 63

**Additional context**
The separator can be dragged even if scroll-controls on top of it (FF only). But this is not obviously since user will be looking for resize-cursor style and that style won't appear if the mouse is over scroll-controls. In Opera(v56) this even worse - the separator cannot be dragged with scroll controls.

### PR DESCRIPTION
**Pull request by T1mL3arn**
Closes #34358 .

### CODE REVIEW

**Comment by thecodingaviator** [comment]
I think this is an issue we need to discuss extensively before passing, as we may have unintended side effects on all places of the website where we use separators, and also if we really want to do this and increase the width of the separator

**Comment by T1mL3arn** [comment]
The width 5px of a separator will be OK, if there will be no problem with the scroll controls. I don't think it is needed to increase width since `overflow-y: hidden` fixes the problem and 5px are enough to easy catch the splitter. Proposed change affects only vertical separator thus there shouldn't be any problem with styling of other separators.

**Comment by Bouncey** [comment]
@T1mL3arn Sorry for the delay in getting round to this. I cannot reproduce your original issue on the current `master` branch. Could you check https://www.freecodecamp.rocks/learn (this is our staging environment) to see if the issue is still present?

**Comment by T1mL3arn** [comment]
@Bouncey Looks like there is no problem in the staging env (at least for me). So original issue and this pr can be closed.

**Pull request closed without merging**
