### PR TITLE
Better explaining tinting and shading

### PR DESCRIPTION
**Pull request by siddtheone**
With current explanation it appears confusing. Hoping updated text more helpful in understanding.

Checklist:

- [x] I have read [freeCodeCamp's contribution guidelines](https://contribute.freecodecamp.org).
- [x] My pull request has a descriptive title (not a vague title like `Update index.md`)
- [x] My pull request targets the `master` branch of freeCodeCamp.
- [x] All the files I changed are in the same world language, for example: only English changes, or only Chinese changes, etc.

Closes #XXXXX

### CODE REVIEW

**Review by tinktink1 — APPROVED** [review]
I have read through the changes and have checked your grammar and it looks good to me! I think that this better explains tinting and shading. Good job

**Review by moT01 — DISMISSED** [review]
LGTM 🎉

**Review by Manish-Giri — COMMENTED** [review]
Might be me, but the new change doesn't quite fit well in the context of the first sentence - 

> Increasing percentage only for lightness creates a tint, and decreasing will make a shade.

The earlier version was better (at least the first part of it) -

> Mixing white with a pure hue creates a tint of that color

**Comment by Madalena-15** [comment]
I agree with @Manish-Giri on this one.

The first version briefly explained what is exactly tint and shade. This is not only clear but useful to explain to non-designers as there is a misconception on the term  _shade_.

The second version is correct but this explains how the `hsl()` works on the technical side. I would suggest putting this in place after explaining what is tint and shade.

Hope this is helpful

**Comment by moT01** [comment]
My new vote goes to leave it as-is and close this PR. That sounds decent @Madalena-15, but it's kind of lengthy and after another read - I think the original version is the easiest to understand for me. What do you think?

**Comment by nhcarrigan** [comment]
I agree with @moT01 - my understanding is we generally want to avoid the "wall of text" in challenges where possible. While the proposed information @Madalena-15 has shared is *good information*, my argument is that it is extraneous for the needs of the challenge.

**Review by Madalena-15 — APPROVED** [review]

**Review by naomi-lgbt — APPROVED** [review]
LGTM!

Congratulations on your first pull request! 🥳

**Comment by RandellDawson** [comment]
@Madalena-15 You approved the PR, so you are still OK with changing:
```
The <code>hsl()</code> option in CSS also makes it easy to adjust the tone of a color. Mixing white with a pure hue creates a tint of that color, and adding black will make a shade. Alternatively, a tone is produced by adding gray or by both tinting and shading. Recall that the 's' and 'l' of <code>hsl()</code> stand for saturation and lightness, respectively. The saturation percent changes the amount of gray and the lightness percent determines how much white or black is in the color. This is useful when you have a base hue you like, but need different variations of it.
```
to:
```
The <code>hsl()</code> option in CSS also makes it easy to adjust the tone of a color. Increasing percentage only for lightness creates a tint, and decreasing will make a shade. Alternatively, a tone is produced by either changing saturation or lightness. Recall that the 's' and 'l' of <code>hsl()</code> stand for saturation and lightness, respectively. The saturation percent changes the amount of gray and the lightness percent determines how much white or black is in the color. This is useful when you have a base hue you like, but need different variations of it.
```

Earlier, you agreed with @Manish-Giri that something was not quite right with the wording.

**Comment by moT01** [comment]
Thanks for the PR and the suggestions everyone. We have decided to close this and leave this challenge as-is for now. Thanks and happy coding 🎉

**Pull request closed without merging**
