### PR TITLE
Corrected spellings and optimised images

### PR DESCRIPTION
**Pull request by aravindvnair99**
- [x] I have read [freeCodeCamp's contribution guidelines](https://github.com/freeCodeCamp/freeCodeCamp/blob/master/CONTRIBUTING.md).
- [x] My pull request has a descriptive title (not a vague title like `Update index.md`)
- [x] My pull request targets the `master` branch of freeCodeCamp.
- [x] None of my changes are plagiarized from another source without proper attribution.
- [x] All the files I changed are in the same world language (for example: only English changes, or only Chinese changes, etc.)
- [x] My changes do not use shortened URLs or affiliate links.

Issue #35158

I've corrected a few spelling mistakes and optimised the images in the repository with lossless compression.

### CODE REVIEW

**Review by theNaut1lus — CHANGES_REQUESTED** [review]
Every separate entry has Page with it, so it would be more suitable I guess to Remove the word web altogether. 
Also Capitalise Page at the end to maintain consistency, so basically from `'Web page'` -> `'Web Page'`

**Comment by QuincyLarson** [comment]
@aravindvnair99 Thanks for opening this GitHub issue. Webpage is an accepted alternate spelling. 

Regarding the image changes, I'm not sure what you did there. The issue you created wasn't sufficiently clear, so I've closed it.

**Comment by aravindvnair99** [comment]
> Every separate entry has Page with it, so it would be more suitable I guess to Remove the word web altogether.
> Also Capitalise Page at the end to maintain consistency, so basically from `'Web page'` -> `'Web Page'`

@co16353sidak Okay, should I make the necessary changes in all files as you have suggested, i.e. "Web Page" and make a new pull request? Or leave the spellings as it is, i.e. "Webpage"?

**Comment by aravindvnair99** [comment]
> @aravindvnair99 Thanks for opening this GitHub issue. Webpage is an accepted alternate spelling.
> 
> Regarding the image changes, I'm not sure what you did there. The issue you created wasn't sufficiently clear, so I've closed it.

@QuincyLarson Yes, I thought I'll change it to "web page" from "webpage" as all dictionaries I visited of US, UK, Australia, India and couple of other countries have it as "web page".

Reference links:

- [Oxford US Dictionary](https://en.oxforddictionaries.com/definition/us/web_page)
- [Oxford British and World English Dictionary](https://en.oxforddictionaries.com/definition/web_page)
- [Dictionary.com](https://www.dictionary.com/browse/web--page)
- [Cambridge Dictionary](https://dictionary.cambridge.org/dictionary/english/web-page)
- [Merriam Webster](https://www.merriam-webster.com/dictionary/web%20page)
- [Collins](https://www.collinsdictionary.com/dictionary/english/web-page)

If it's decided to change from "webpage" to "Web Page" as @co16353sidak and I have suggested, I'll make the changes in all the files and submit a new pull request or you could reopen this pull request. If not, I'll revert the changes in my fork so that I can make further contributions to freeCodeCamp without the "web page" thing.

As for the images, I have performed lossless compression. It's just for optimising storage space, thus leading to faster load times. I'll revert this too if it's unnecessary.

Thanks for replying! :)

**Comment by co16353sidak** [comment]
Leave as Webpage, @QuincyLarson suggests  thst there is no need for a change hence this Pull was closed.

Instead You could look into other open issues and try for a solution there

**Comment by aravindvnair99** [comment]
> Leave as Webpage, @QuincyLarson suggests thst there is no need for a change hence this Pull was closed.
> 
> Instead You could look into other open issues and try for a solution there

@co16353sidak Sure. Will revert my changes. Went with the spellings as most dictionaries had it as "web page" as I've mentioned in my previous [comment](https://github.com/freeCodeCamp/freeCodeCamp/pull/35159#issuecomment-463507411).

What about the images? Should I revert that as well?

Thanks for replying! :)

**Pull request closed without merging**
