### PR TITLE
fix(client): prevent submitting forms in iframe

### LINKED ISSUE #46057: Preview editor re-renders incorrectly
### Describe the Issue

On Firefox, clicking a link inside the preview pane and pressing 'back' on your web browser causes the preview pane to reload with the entire content of the page (html, css, preview pane etc.)
image

On Chrome, this issue is not present, BUT it still re-renders the preview pane incorrectly. Instead of being able to create multiple pages in one preview pane, Chrome renders blank content until the preview pane is closed and re-opened.

### Affected Page

https://www.freecodecamp.org/learn/2022/responsive-web-design/learn-html-forms-by-building-a-registration-form/step-57

### Steps to Reproduce

1. Go to the preview pane.
2. Click on a link (or create one in html first)
3. Press back in your browser.
4. Preview pane now contains the content of the page.
5. Repeat and create more panes.

### Expected behavior

I expected the page to maybe go blank or just go back to the last web page. I did not expect to be able to multiply the content of the page.

### Screenshots

image

### System

- Device: [e.g. iPhone 6, Laptop]
- OS: [e.g. iOS 14, Windows 10, Ubuntu 20.04]
- Browser: [e.g. Chrome, Safari]
- Version: [e.g. 22]

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by Prathamesh010**
Checklist:

- [x] I have read [freeCodeCamp's contribution guidelines](https://contribute.freecodecamp.org).
- [x] My pull request has a descriptive title (not a vague title like `Update index.md`)
- [x] My pull request targets the `main` branch of freeCodeCamp.
- [x] I have tested these changes either locally on my machine, or GitPod.

Closes #46057

### CODE REVIEW

**Comment by raisedadead** [comment]
I could not repro as per https://github.com/freeCodeCamp/freeCodeCamp/issues/46057#issuecomment-1133543202.

because the issue was fixed somewhere in the last 5 months per the blame.

However, I am not sure if we want to add the message. 
Do we @Nirajn2311 and @moT01?

**Comment by raisedadead** [comment]
> This pr aims on fixing it.

Elaborate how? The changes I see are only adding an alert message. That is not what the comment in the original comment from @Nirajn2311 means. Correct?

**Comment by Nirajn2311** [comment]
I haven't tested the PR locally yet but the solution we reached was to show the same alert which is used for links which change the iframe page. 

> I could not repro as per https://github.com/freeCodeCamp/freeCodeCamp/issues/46057#issuecomment-1133543202 because the issue was fixed somewhere in the last five months per git blame.

Hmm that's strange as I still see the issue mentioned in that comment.

**Comment by raisedadead** [comment]
> Hmm that's strange as I still see the issue mentioned in that comment.

Are we looking at the same thing?

If it's all the same, @Nirajn2311 could record a screen-cap or something real quick. I might be doing something stupidly wrong.

I am looking at the code and the git-blame here: 

https://github.com/freeCodeCamp/freeCodeCamp/blame/7b24e7e597ecd72caf4752b362b7c184e75456b3/client/src/templates/Challenges/utils/frame.ts#L97

And there is a check (`preventDefault`) that should stop the event propagation. If that is correct, then all this PR is adding, is a message on the alert, which is nice to have, but the issue is indeed resolved even before this PR. Correct?

**Review by moT01 — APPROVED** [review]
This LGTM @Prathamesh010 🎉

Here's a screen cap @raisedadead
Oct-11-2022 17-06-36

It wasn't preventing default because it didn't get passed that `if !action` condition.

The only thing I might like to see is to move the alert for these two into the preview itself instead of the main window. Something for another discussion/PR.

Edit: Actually, I wonder if we need to be checking if the action is a URL here. If you use something that doesn't start with `http...`, you don't get the alert.

**Review by raisedadead — APPROVED** [review]

**Pull request merged**
