### PR TITLE
Create oddorevennumber.py

### PR DESCRIPTION
**Pull request by ManmathX**
this file give odd or even

Checklist:

- [ ] I have read and followed the [contribution guidelines](https://contribute.freecodecamp.org).
- [ ] I have read and followed the [how to open a pull request guide](https://contribute.freecodecamp.org/how-to-open-a-pull-request/).
- [ ] My pull request targets the `main` branch of freeCodeCamp.
- [ ] I have tested these changes either locally on my machine, or GitPod.

Closes #XXXXX

### CODE REVIEW

**Comment by ilenia-magoni** [comment]
do not add random files

**Comment by ManmathX** [comment]
I apologize if it didn’t meet your expectations. My intention was to contribute positively to the project. Could you please remove the spam label? bcz it will affect on my future pull requests......

**Comment by ManmathX** [comment]
please remove it i have done a huge mistake

**Comment by ilenia-magoni** [comment]
contributing a random file to an established project is the definition of spam, I will not remove the label

**Comment by ManmathX** [comment]
I understand your perspective on my contribution. I appreciate any guidance on how I can better align with the project’s goals in future submissions.

**Comment by ilenia-magoni** [comment]
You should bother to learn what the project is about, and check if there are issues you can solve

**Comment by ManmathX** [comment]
I appreciate your advice and will take the time to better understand the project and identify relevant issues I can help with. I value your guidance and hope to contribute meaningfully in the future.

**Comment by ManmathX** [comment]
please kindly remove my spam label it can effect my gsoc and hackeroberfeat jounery

**Comment by ManmathX** [comment]
i will make make sure that i don't do this mistake from next time

**Comment by ilenia-magoni** [comment]
stop asking, it will result in moderation actions. You made a PR against Hacktoberfest values, the spam label is part of the rules of Hacktoberfest.

**Comment by naomi-lgbt** [comment]
We will not be removing the label, as this pull request is blatant spam. It does not follow our contributing guidelines in the slightest, and makes no meaningful contribution to the codebase or community.

If you continue to create noise on this PR, we will remove you from the organisation entirely.

**Pull request closed without merging**
