### PR TITLE
Fixed 2 typo in language lead handbook

### LINKED ISSUE #46977: Typo in language lead handbook
there are two typos in the file 

- [ ] a typo in this line, `there two places` should be `there are two places`, here is the line

https://github.com/freeCodeCamp/freeCodeCamp/blob/d0e42982f070e9ec8ba95be308af1ea090384421/docs/language-lead-handbook.md#L34

- [ ] a typo in this line, `settngs` should be `settings`, here is the line 

https://github.com/freeCodeCamp/freeCodeCamp/blob/d0e42982f070e9ec8ba95be308af1ea090384421/docs/language-lead-handbook.md#L269

---

Here is the markdown file https://github.com/freeCodeCamp/freeCodeCamp/blob/d0e42982f070e9ec8ba95be308af1ea090384421/docs/language-lead-handbook.md

### Additional context

Please make sure you read [our guidelines for contributing](https://contribute.freecodecamp.org/#/), we prioritize contributors following the instructions in our guides. Join us in [our chat room](https://discord.gg/PRyKn3Vbay) or [the forum](https://forum.freecodecamp.org/c/contributors/3) if you need help contributing, our moderators will guide you through this.

Sometimes we may get more than one pull requests. We typically accept the most quality contribution, followed by the one that is made first.

Happy contributing.

### PR DESCRIPTION
**Pull request by hrittik2002**
Checklist:

- [x] I have read [freeCodeCamp's contribution guidelines](https://contribute.freecodecamp.org).
- [x] My pull request has a descriptive title (not a vague title like `Update index.md`)
- [x] My pull request targets the `main` branch of freeCodeCamp.
- [x] I have tested these changes either locally on my machine, or GitPod.

Closes #46977

### CODE REVIEW

**Comment by Sboonny** [comment]
hi @hrittik2002, thank you for opening the PR, can you edit `Closes #XXXXX`, to link to the issue.

**Comment by hrittik2002** [comment]
yes sure........but can you just explain what I have to edit? I can't get it what closes #XXXXX means

**Review by Sboonny — APPROVED** [review]
#### :sparkles: :tada: **AWESOME!** :tada: :sparkles:

 Hi @hrittik2002, thanks for this pull request and for contributing to the code-base for the first time. We are looking forward to more contributions from you in the future.

 Cheers & happy contributing!

**Comment by Nishant-96** [comment]
Hey @hrittik2002  I think the closes code should be `#47977` to link to the issue. You have linked it to PR i made.

**Comment by hrittik2002** [comment]
oh  okk, what to do now?

**Comment by hrittik2002** [comment]
actually, I had fixed the issue before you but I haven't mentioned Closes #XXXXX

**Comment by hrittik2002** [comment]
now is it ok Nishant-96 ?

**Comment by Sboonny** [comment]
Hi @hrittik2002 because of my poor management, multiple pull request targeting the same issue occurred. 

I decided to close yours and add you into the second pr as co-author in appreciation for your good will. 

Have a good day, and happy coding.

**Pull request closed without merging**
