### PR TITLE
feat(client): re-enable failed update re-submission

### PR DESCRIPTION
**Pull request by ojeytonwilliams**
There is a little bit of code that's not used for much (most of the response is ignored), but it was necessary for handling failed updates.  I didn't want to create a special case just for them, so now all ajax functions return it. 

TODO:
- [x] Add Cypress tests for the flushing
- [ ] Once https://github.com/freeCodeCamp/freeCodeCamp/pull/46378/ goes in, settings-saga.js will need updating

### CODE REVIEW

**Comment by ahmadabdolsaheb** [comment]
@ojeytonwilliams, what is missing here?

**Comment by ojeytonwilliams** [comment]
@ahmadabdolsaheb nothing's was missing.  I've fixed the conflict, though.

**Comment by ojeytonwilliams** [comment]
> nothing was missing

Except what I missed while fixing the conflicts.  Cypress caught those, though.

**Review by raisedadead — APPROVED** [review]
I am not the expert here, but with a cursory look code seems good to me.

**Comment by ojeytonwilliams** [comment]
That's a good question. The data is just the body of the response and most of the time that is all we need. However, for the failed updates we want to know if the request was processed successfully or not. Status codes are the natural way to communicate something like that and so we need access to more than just the body.

**Review by ahmaxed — APPROVED** [review]

**Pull request merged**
