### PR TITLE
[fix] Data Structures: Create a Circular Queue challenge example

### PR DESCRIPTION
**Pull request by ezioda004**
The current example shown in the [challenge](https://learn.freecodecamp.org/coding-interview-prep/data-structures/create-a-circular-queue) suggests that the `^Write` pointer can overwrite the existing queue values bypassing `^Read` pointer. Example:
```
[1, 2, 3, 4, 5]
^Read @ 0
^Write @ 0
```
To:
```
[a, b, c, 4, 5]
^Read @ 0
^Write @ 3
```
The elements in the first example are suppose to show the nth term of the array but it comes off as the value instead.
From the text challenge:
> **The write pointer should not be allowed to move past the read pointer** (our class won't let you overwrite data you haven't read yet) and the read pointer should not be able to advance past data you have written.

This PR improves this example so theres no ambiguity in the text and improves the current solution.

- [x] I have read [freeCodeCamp's contribution guidelines](https://github.com/freeCodeCamp/freeCodeCamp/blob/master/CONTRIBUTING.md).
- [x] My pull request has a descriptive title (not a vague title like `Update index.md`)
- [x] My pull request targets the `master` branch of freeCodeCamp.
- [x] None of my changes are plagiarized from another source without proper attribution.
- [x] My article does not contain shortened URLs or affiliate links.

If your pull request closes a GitHub issue, replace the XXXXX below with the issue number.

Closes #XXXXX

### CODE REVIEW

**Review by cmccormack — APPROVED** [review]
Changes look good, matches the explanation of the read and write positions much better than the previous example.  Only thing I would suggest is lining the carets up so they are pointing to the index after the `@`, as the caret doesn't make sense if it's not positioned.

**Comment by ezioda004** [comment]
Thats a good suggestion. I reckon we can use `<span>` and use inline style with `padding-left`?
Not sure if thats the best way to go about it, do you have any suggestions?

**Comment by cmccormack** [comment]
I went ahead and replaced all of the html markup with markdown where I could find it, and fixed some grammar issues, hope you don't mind.  Not sure if we still use section ids?

**Comment by ezioda004** [comment]
@cmccormack I see you've added the markdown blocks, but I dont think that'll work in the curriculum challenges.

This needs to be tested locally.

**Comment by nikrb** [comment]
@ezioda004 @cmccormack successfully tested locally.
Pointers look good to me.

**Comment by cmccormack** [comment]
This looks good to me.  Thank you for your contribution!

**Pull request merged**
