### PR TITLE
Fix typos in MongoDB lessons and clarify some language

### PR DESCRIPTION
**Pull request by PorgJuice**
- [x] I have read [freeCodeCamp's contribution guidelines](https://github.com/freeCodeCamp/freeCodeCamp/blob/master/CONTRIBUTING.md).
- [x] My pull request has a descriptive title (not a vague title like `Update index.md`)
- [x] My pull request targets the `master` branch of freeCodeCamp.
- [x] None of my changes are plagiarized from another source without proper attribution.
- [x] All the files I changed are in the same world language (for example: only English changes, or only Chinese changes, etc.)
- [x] My changes do not use shortened URLs or affiliate links.

There were a few little typos and grammatical errors in the text of the MongoDB lessons. This PR clears up the low hanging fruit.

### CODE REVIEW

**Comment by RandellDawson** [comment]
@PortableStick Thanks for this PR.  There were 2 earlier PRs with some changes to the same sections.  I have now merged them, so now your PR has a couple merge conflicts.  Can you resolve them?  One of your changes has been fixed from another PR (take a look at the current master for [this file](https://github.com/freeCodeCamp/freeCodeCamp/blob/master/curriculum/challenges/english/05-apis-and-microservices/mongodb-and-mongoose/create-and-save-a-record-of-a-model.en.md)) to see what I mean.

Thanks again for your contribution.

**Comment by PortableStick** [comment]
@RandellDawson Got it. Conflicts should all be resolved now. Please let me know if there's anything else you need!

**Comment by RandellDawson** [comment]
@PortableStick Looks good.  To validate the tests all work, can you also add a valid solution for each of the 3 challenges you updated?  You replaced `''`` with `"` wrapping.  Actually, I believe you can not wrap the asserts with `"` and still be fine.  If you add valid solutions and the tests pass without wrapping the asserts with `"`, then that would be preferred.

**Comment by PortableStick** [comment]
I will look into it. I didn't make that change manually, it came about when I ran Prettier. I assumed it would be fine since the project has a `prettierrc`. I'll check it out this weekend.

**Review by moT01 — COMMENTED** [review]
The empty lines after all the headers aren't necessary. I suppose it's not a big deal, but I couldn't find any other challenges that have those empty lines. Perhaps that can be ignored since @RandellDawson intends on going through these challenges in the near future, and he can maybe just revert that (or leave it). I don't see any other challenges that follow the changed quote format in the tests either, but I was able to test them and my old glitch project (https://fcc-mongo-mongoose.glitch.me/) still passes all the tests. This does make the test area of the files look better, I think. But, is it better to make a few files look slightly better, or keep consistency across the challenges? The changes to the descriptions look good. As for adding the solutions that @RandellDawson mentioned, that could maybe be saved for another PR. I'm curious what we would put for a solution? I think a simple URL to a working project would have to go there, as submitting a URL is how you check if it passes the tests.

**Comment by RandellDawson** [comment]
@moT01, @PortableStick  Turns out after talking with @ValeraS, we do not need to put solutions for these challenges right now, because there is nothing setup to use them.

**Comment by PortableStick** [comment]
Alright, so what needs to happen now?

**Comment by RandellDawson** [comment]
@PortableStick Nothing.  I am approving the changes.

**Review by RandellDawson — APPROVED** [review]

**Review by moT01 — APPROVED** [review]
Looks good @PortableStick, thanks for your patience on this.

**Pull request merged**
