### PR TITLE
Feat: Convert landing page test to Typescript

### PR DESCRIPTION
**Pull request by a2937**
Checklist:

- [X] I have read [freeCodeCamp's contribution guidelines](https://contribute.freecodecamp.org).
- [X] My pull request has a descriptive title (not a vague title like `Update index.md`)
- [X] My pull request targets the `main` branch of freeCodeCamp.
- [X] I have tested these changes either locally on my machine, or GitPod.

Related to #48753

Unfortunately some of the more advanced tests don't work locally and I'm still trying to figure out why.

### CODE REVIEW

**Comment by a2937** [comment]
I'm a little confused about why the lint failed. It said ``` Error:   44:12  error  Invalid type "any" of template literal expression  @typescript-eslint/restrict-template-expressions```

**Comment by a2937** [comment]
It's tied back to the problem I tried to solve the last time. As selectors has been declared already; in line 44 it's assuming the old type is being used here.

**Review by Sembauke — APPROVED** [review]

**Comment by a2937** [comment]
I tried to make it able to be merged by re-basing it.

**Comment by Sboonny** [comment]
@a2937, using `export {}` felt like cheating for me, so here are the changes that were implemented

When TypeScript complained about the naming of the `selectors`, it doesn't like it when the same name is used between files. I changed the names of the selectors to not have duplicates between files.

When TypeScript was giving `cert` and `name` weird values which cased an error, setting types to in the function sorted it out.

--- 

If you have any questions, feel free to ask? And if you think this isn't necessary, feel free to revert it.

**Review by Sboonny — APPROVED** [review]
LGTM 🎉, thank you for your contribution to the page! 👍.

**Review by Sembauke — APPROVED** [review]

**Pull request merged**
