### PR TITLE
Add mutable types example

### PR DESCRIPTION
**Pull request by mrassili**
Mentioned the mutable data types and gave an example with object

### CODE REVIEW

**Comment by ezioda004** [comment]
Hi @mrassili, 
Since the article is about immutable data types I think we should limit this one for that only. I suppose you could make a new article for mutable types.
Would like to hear suggestion from others on this.

**Comment by mrassili** [comment]
I think it's best to keep them in the same article since this is only one subject

**Comment by Asjas** [comment]
I would suggest we move this into a sub-folder called `mutable-types` inside the [javascript](https://github.com/freeCodeCamp/freeCodeCamp/tree/872078c912c58b00919528e6aaa6a67e08ddeea4/client/src/pages/guide/english/javascript) folder.

Separation of concerns basically.

**Comment by Asjas** [comment]
Hey @mrassili :wave: :smile:

**Comment by mrassili** [comment]
Hi @Asjas 👋🏼
Fair enough. is a PR necessary to make these changes into a new article?

**Comment by QuincyLarson** [comment]
@mrassili I agree that this could be a separate article and they could link to one another. I'm going to close this PR - please open another when when you get a chance. Thanks again!

**Pull request closed without merging**
