### PR TITLE
feat: update mobile app superblock order

### PR DESCRIPTION
**Pull request by Sembauke**
Checklist:

- [ ] I have read [freeCodeCamp's contribution guidelines](https://contribute.freecodecamp.org).
- [ ] My pull request has a descriptive title (not a vague title like `Update index.md`)
- [ ] My pull request targets the `main` branch of freeCodeCamp.
- [ ] I have tested these changes either locally on my machine, or GitPod.

Closes #XXXXX

### CODE REVIEW

**Comment by scissorsneedfoodtoo** [comment]
@Sembauke, I'm probably not the best person to review this because I don't have any experience with this codebase, but on first glance everything LGTM. It seems like most certifications are hidden now, and just the new and legacy RWD certs should be visible.

Is the goal here to mimic the certification order currently on Learn? Or will that come later. I vaguely recall a meeting where we said that we'll eventually move the legacy RWD cert to the bottom of the map, but I think it was decided that the RDB cert should remain between Data Vis and Back End Development.

Just something I noticed, but again, I'm sure it's not a big deal.

**Comment by Sembauke** [comment]
Hey Kris,

> I vaguely recall a meeting where we said that we'll eventually move the legacy RWD cert to the bottom of the map

I am not sure if that is what we agreed on, seeing the following issue: https://github.com/freeCodeCamp/freeCodeCamp/issues/46523 . But to my knowledge we might not even see this legacy certification in the mobile app at all. As it might be gone from the web client before we do a first release of learn on mobile.

>  It seems like most certifications are hidden now, and just the new and legacy RWD certs should be visible.

You are correct that only the legacy and the new Responsive Web Design certification are now available. We have not yet implemented a console for the JavaScript certifications (Everything gets complicated when a application is not web-based). But when we do implement it I will make sure to re-enable the certification.  

> Is the goal here to mimic the certification order currently on Learn?

We could keep everything in the same order as the web-client, but it would not make sense in my opinion to do so. Because most of the certifications won't be available on launch. Thus I think it would be more pleasing to the eye to keep to available certifications at the top. 

Some of the certifications might never become available, we might even remove them from the map entirely in the future. But  I have not thought about that yet.

**Comment by Nirajn2311** [comment]
> Thus I think it would be more pleasing to the eye to keep to available certifications at the top.

I agree on this

**Comment by scissorsneedfoodtoo** [comment]
Awesome, thanks for those details @Sembauke, and for your input @Nirajn2311.

I agree with that, too. Good to hear a bit more about the plans you both have for the rollout of the curriculum on the mobile app.

Also, even though I was assigned to review this automatically, please feel free to merge things as necessary. I don't know much about the mobile app and your process, and I wouldn't want to be a roadblock for either of you.

**Review by scissorsneedfoodtoo — APPROVED** [review]

**Review by majestic-owl448 — APPROVED** [review]

**Pull request merged**
