### PR TITLE
fix(curriculum): reorder steps in JS RPG

### LINKED ISSUE #52667: Role Playing Game: Move initial JS steps to the front
### Describe the Issue

Having 16 steps of boilerplate HTML before you even get to any JS seems a bit much.

Why not move steps 2 to 17 to before step 30 when the DOM content is needed?

1 > 17-29 > 2-16 > 29-end

### Affected Page

https://www.freecodecamp.org/learn/javascript-algorithms-and-data-structures-v8/learn-basic-javascript-by-building-a-role-playing-game/step-1

### Your code

```



```

### Expected behavior

Not spending so much time writing HTML before the initial JS intro. 

### Screenshots

_No response_

### System

- Device: [e.g. iPhone 6, Laptop]
- OS: [e.g. iOS 14, Windows 10, Ubuntu 20.04]
- Browser: [e.g. Chrome, Safari]
- Version: [e.g. 22]

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by majestic-owl448**
waiting for #53037 [skip ci]

Checklist:

- [x] I have read and followed the [contribution guidelines](https://contribute.freecodecamp.org).
- [x] I have read and followed the [how to open a pull request guide](https://contribute.freecodecamp.org/#/how-to-open-a-pull-request).
- [x] My pull request targets the `main` branch of freeCodeCamp.
- [x] I have tested these changes either locally on my machine, or GitPod.

Closes #52667

### CODE REVIEW

**Review by jdwilkin4 — CHANGES_REQUESTED** [review]
Was able to test things locally and the new flow is working for me.
Left one suggestion 👍

**Comment by ieahleen** [comment]
I have fixed the merge conflicts, now it should be ready to review

**Review by jdwilkin4 — APPROVED** [review]
tested it again and works for me 👍

**Review by naomi-lgbt — APPROVED** [review]
Should be good to go now. :3

**Pull request merged**
