### PR TITLE
fix(curriculum): typos in making RPG game project at new JS

### PR DESCRIPTION
**Pull request by rffontenelle**
Checklist:

- [x] I have read [freeCodeCamp's contribution guidelines](https://contribute.freecodecamp.org).
- [x] My pull request has a descriptive title (not a vague title like `Update index.md`)
- [x] My pull request targets the `main` branch of freeCodeCamp.
- [ ] I have tested these changes either locally on my machine, or GitPod.

This fixes minor typographic errors.

I tried setting up and building, but expended too much time when I believe it should be necessary. Please let me know if building locally is a *si ne qua non* condition to accepting this PR.

### CODE REVIEW

**Review by Sboonny — APPROVED** [review]
#### :sparkles: :tada: **AWESOME!** :tada: :sparkles:

 Hi @rffontenelle, thanks for this pull request and for contributing to the code-base for the first time. We are looking forward to more contributions from you in the future.

 Cheers & happy contributing!

**Comment by raisedadead** [comment]
> I tried setting up and building, but expended too much time when I believe it should be necessary.

Did you try the GitPod setup? It's quite quick - but a wait time of 8-12 mins is normal.

**Review by naomi-lgbt — APPROVED** [review]
banger pr, thanks for contributing!

Testing locally is generally a good idea - just to be sure your changes didn't break anything. If you're having trouble getting things set up, feel free to pop in our [Discord](https://discord.gg/PRyKn3Vbay).

**Comment by rffontenelle** [comment]
> Did you try the GitPod setup? It's quite quick - but a wait time of 8-12 mins is normal.

I haven't, but I'll try. Thanks for the suggestion.

I went with npm commands inside a podman environment. I installed dependencies via `npm ci` and then ran `npm run test:curriculum --superblock=learn-basic-javascript-by-building-a-role-playing-game`, based on [How to open a Pull Request (PR)](https://contribute.freecodecamp.org/#/how-to-open-a-pull-request) guide, but the test failed to find config/client/frame-runner.json (don't have the exact output here.

**Comment by rffontenelle** [comment]
> If you're having trouble getting things set up, feel free to pop in our [Discord](https://discord.gg/PRyKn3Vbay).

I will, thanks!

**Pull request merged**
