### PR TITLE
Added semicolon to end of first statement in the challenge "Regular Expressions: Find Characters with Lazy Matching"

### LINKED ISSUE #13047: [beta] Missing semicolon in challengeSeed for "Regular Expressions: Find Characters with Lazy Matching"
Challenge [find-characters-with-lazy-matching](http://beta.freecodecamp.com/en/challenges/regular-expressions/find-characters-with-lazy-matching) has an issue.

```js

let text = "<h1>Winter is coming</h1>"
let myRegex = /<.*>/; // Change this line
let result = text.match(myRegex);

```

The first line of the `challengeSeed` for this challenge needs a semicolon to prevent the editor from showing a warning when the challenge loads.

If you want to fix this, please read [CONTRIBUTING.md](https://github.com/FreeCodeCamp/FreeCodeCamp/blob/staging/CONTRIBUTING.md) to get started.

When you're all set, add a semicolon to [this line](https://github.com/freeCodeCamp/freeCodeCamp/blob/staging/seed/challenges/02-javascript-algorithms-and-data-structures/regular-expressions.json#L423) and make your commit.

If you have any questions, please come chat with us in the [Contributors Chat Room](https://gitter.im/FreeCodeCamp/Contributors).

Happy Coding :smile:

### PR DESCRIPTION
**Pull request by ankitdwivedi23**
#### Pre-Submission Checklist

- [x] Your pull request targets the `staging` branch of freeCodeCamp.
- [x] Branch starts with either `fix/`, `feature/`, or `translate/` (e.g. `fix/signin-issue`)
- [x] You have only one commit (if not, [squash](http://forum.freecodecamp.com/t/how-to-squash-multiple-commits-into-one-with-git/13231) them into one commit).
- [x] All new and existing tests pass the command `npm test`. Use `git commit --amend` to amend any fixes.

#### Type of Change

- [x] Small bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds new functionality)
- [ ] Breaking change (fix or feature that would change existing functionality)
- [ ] Add new translation (feature adding new translations)

#### Checklist:

- [x] Tested changes locally.
- [x] Closes currently open issue (replace XXXX with an issue no): Closes #13047

#### Description
Added semicolon to the end of the first statement in the challenge. This fix prevents the editor from showing a warning when the challenge loads.

Before fix:
image

After fix:
image

### CODE REVIEW

**Review by mother46 — APPROVED** [review]

**Review by Greenheart — APPROVED** [review]
@ankitdwivedi23 Thanks for helping out! :smile:

**Comment by ankitdwivedi23** [comment]
@Greenheart Thanks for merging the PR, and for helping me get started! :)

**Comment by Greenheart** [comment]
@ankitdwivedi23 Sure, no problem! I'm truly impressed by your perseverance in fighting the development environment! Most would have quit :smile: :star2:

**Review by ghost — COMMENTED** [review]
let text = "<h1>Winter is coming</h1>";
let myRegex = /<[a-z0-9]*?>/gi; // Change this line
let result = text.match(myRegex);
works for me

**Pull request merged**
