### PR TITLE
fix: correct unbalanced <code> element spacing

### LINKED ISSUE #35343: Code elements have unbalanced spacing on the sides
**Describe your problem and how to reproduce it:**

`<code></code>` elements appear visually unbalanced on the left and right side due to improper space in pseudo-selectors.

The `::before` pseudo selector used on the `code` element does not appear to add the spacing intended - while it works on the `::after` selector, the space, when applied to the `::before` selector, doesn't appear to display anything.

**Add a Link to the page with the problem:**

Every page using the `<code></code>` element.
[this](https://learn.freecodecamp.org/javascript-algorithms-and-data-structures/basic-javascript/iterate-with-javascript-do---while-loops/) challenge was used in the screenshot.

**If possible, add a screenshot here (you can drag and drop, png, jpg, gif, etc. in this box):**

image

### PR DESCRIPTION
**Pull request by cmccormack**
- [X] I have read [freeCodeCamp's contribution guidelines](https://github.com/freeCodeCamp/freeCodeCamp/blob/master/CONTRIBUTING.md).
- [X] My pull request has a descriptive title (not a vague title like `Update index.md`)
- [X] My pull request targets the `master` branch of freeCodeCamp.
- [X] None of my changes are plagiarized from another source without proper attribution.
- [X] All the files I changed are in the same world language (for example: only English changes, or only Chinese changes, etc.)
- [X] My changes do not use shortened URLs or affiliate links.

Closes #35343

### CODE REVIEW

**Comment by cmccormack** [comment]
Looking for feedback as I'm not certain if padding will resolve any previous issues the pseudo-elements were added to correct.

**Comment by ahmadabdolsaheb** [comment]
@cmccormack I see that the before and after content: " "  was applied, but I'm not sure why it is not being displayed.

**Comment by cmccormack** [comment]
@ahmadabdolsaheb I'm not very familiar with the quirks of the pseudo-elements, but when playing with it in the browser it appears to be an issue with using white-space in the `::before` element when the previous character outside the `code` block is also white-space.  You can test this by changing the value in the `content` property to a non-white-space character, or by adding a character immediately prior to the code block.

**Examples:**
Original:
image

Adding a non-white-space character immediately preceding the `code` element:
image

Adding a non-white-space character `#` as the `content` value on the `code::before` selector:
image

**Comment by cmccormack** [comment]
After digging around a little more this may be due to [Anonymous inline boxes](https://www.w3.org/TR/CSS21/visuren.html#anonymous)

I tested a fix using `white-space: pre;` as so:
```css
code:before,
code:after,
tt:before,
tt:after {
  letter-spacing: -0.2em;
  content: ' ';
  white-space: pre;
}
```
This may be a cleaner solution and probably should have been included by default.
I have updated the PR with these changes, please let me know what you think.

**Review by thecodingaviator — APPROVED** [review]
@cmccormack Just tried your new solution using `white-space: pre`, it's definitely working better, i also tried fiddling with some settings but pseudo-elements, argh. Anyways, Kudos!

**Comment by ahmadabdolsaheb** [comment]
@cmccormack thanks for digging and trying different approaches. Tested your finally solution locally, and it seems like the better approach. Thank you.

**Pull request merged**
