### PR TITLE
fix: step 30 registration form add test against wrong code

### LINKED ISSUE #46957: Reg Form Step 30: Options are not required to be in the select
### Describe the Issue

Had a user in the forum who was able to pass this step with the following HTML:

```
<label>How did you hear about us? 
          <select></select>
</label>
          <option></option>
          <option></option>
          <option></option>
          <option></option>
          <option></option>
```

### Affected Page

https://www.freecodecamp.org/learn/2022/responsive-web-design/learn-html-forms-by-building-a-registration-form/step-30

### Your code

See above.

### Expected behavior

I'm guessing the tests are just checking if the `select` element is nested in the `label` and the `option`s are not being verified because why would someone move them out of the `select` in the first place :-)

### Screenshots

_No response_

### System

- Device: Desktop
- OS: Linux Fedora 35, Windows 11
- Browser: Firefox v102, Chrome v103 

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by majestic-owl448**
Checklist:

- [x] I have read [freeCodeCamp's contribution guidelines](https://contribute.freecodecamp.org).
- [x] My pull request has a descriptive title (not a vague title like `Update index.md`)
- [x] My pull request targets the `main` branch of freeCodeCamp.
- [x] I have tested these changes either locally on my machine, or GitPod.

Closes #46957

image

### CODE REVIEW

**Comment by Sboonny** [comment]
I wonder should we change the description as it isn't mentioning `option` elements

> Nest the `select` element within a `label` element with the text `How did you hear about us?`. The text should come before the `select` element.

**Comment by ieahleen** [comment]
@Sboonny Something like 
> Nest the `select` element (with its `option` elements) in...

**Comment by Sboonny** [comment]
@ieahleen I do like it

**Review by Sboonny — APPROVED** [review]
LGTM 🎉, thank you for your contribution to the page! 👍.

**Review by naomi-lgbt — APPROVED** [review]
__
[sema-logo](https://semasoftware.com/gh) &nbsp;**Summary:** :ok_hand: This code looks good

**Pull request merged**
