### PR TITLE
Add test to Profile Lookup challenge.

### LINKED ISSUE #15563: Profile Lookup challenge needs test with non-existent firstName AND prop
#### Profile Lookup
https://www.freecodecamp.com/challenges/profile-lookup

#### Issue Description
There is no test with both a name and property that doesn't exist, e.g. "Bob" "address". If the user is capable of not knowing contacts or properties, the code should handle the case of them not knowing both.

### PR DESCRIPTION
**Pull request by MiloATH**
#### Pre-Submission Checklist

- [x] Your pull request targets the `staging` branch of freeCodeCamp.
- [x] Branch starts with either `fix/`, `feature/`, or `translate/` (e.g. `fix/signin-issue`)
- [x] You have only one commit (if not, [squash](http://forum.freecodecamp.com/t/how-to-squash-multiple-commits-into-one-with-git/13231) them into one commit).
- [x] All new and existing tests pass the command `npm test`. Use `git commit --amend` to amend any fixes.

#### Type of Change

- [x] Small bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds new functionality)
- [ ] Breaking change (fix or feature that would change existing functionality)
- [ ] Add new translation (feature adding new translations)

#### Checklist:

- [x] Tested changes locally.
- [x] Closes currently open issue: Closes #15563

#### Description

This will add another test to the Profile Lookup challenge. This test is necessary to determine if the code is returning the correct error message. The user may return the incorrect error "No such property", but really should return correct "No such contact".

### CODE REVIEW

**Comment by dhcodes** [comment]
How is this test different than `lookupProfile('Bob', 'potato')`?

**Comment by MiloATH** [comment]
The issue talked about how `lookupProfile('Bob', 'address')` was to make sure the correct error is returned. As mentioned by @willnwhite: 
> My original motivation for this test was that I solved this challenge with code that returned 'No such property' for lookUp("Bob", "address"), which leads the user into thinking there is a contact called Bob, which is untrue.

The profiles have the `address` property, but not the `potato` property. 

I do understand that this could be over testing. Let me know if you want me to close the PR.

**Comment by dhcodes** [comment]
@MiloATH I read the issue thread; I'm just confused because on beta the profiles don't have the `address` property so I'm fairly certain that the `potato` test is achieving the same thing.

**Comment by MiloATH** [comment]
@dhcodes Oh. My bad, you are correct. Would the test make sense if it was `lookupProfile('Bob', 'number')`?

**Comment by dhcodes** [comment]
@MiloATH I don't think so because that test appears to already exist.

**Comment by MiloATH** [comment]
After looking at the seed code, I am closing this PR since the test would be redundant. #15563 should be closed as well.

**Pull request closed without merging**
