### PR TITLE
Fixed broken link

### LINKED ISSUE #8618: Link from challenge "Use the Twitchtv JSON API" to example use of API is broken
#### Use the Twitchtv JSON API
https://www.freecodecamp.com/challenges/use-the-twitchtv-json-api

#### Issue Description

> 8. Hint: See an example call to Twitch.tv's JSONP API at https://github.com/FreeCodeCamp/FreeCodeCamp/wiki/Front-End-Project-Use-the-Twitchtv-JSON-API.

The link is broken. It results in being dropped at the main wiki page. If you look into the index, the page for this project doesn't exist.

Re-instate the example

#### Browser Information

* Browser Name, Version: All
* Operating System: All
* Mobile, Desktop, or Tablet: All 

#### Screenshot
use_the_twitch_tv_json_api___free_code_camp

### PR DESCRIPTION
**Pull request by sahilkhurana19**
#### Pre-Submission Checklist

- [x] Your pull request targets the `staging` branch of FreeCodeCamp.
- [x] Branch starts with either `fix/`, `feature/`, or `translate/` (e.g. `fix/signin-issue`)
- [x] You have only one commit (if not, [squash](https://github.com/FreeCodeCamp/FreeCodeCamp/wiki/git-rebase#squashing-multiple-commits-into-one) them into one commit).
- [x] All new and existing tests pass the command `npm run test-challenges`. Use `git commit --amend` to amend any fixes.
#### Type of Change

- [x] Small bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds new functionality)
- [ ] Breaking change (fix or feature that would change existing functionality)
- [ ] Add new translation (feature adding new translations)
#### Checklist:

- [x] Tested changes locally.
- [x] Closes currently open issue (replace XXXX with an issue no): Closes #8618 
#### Description

Fixed broken link for point 8 at https://www.freecodecamp.com/challenges/use-the-twitchtv-json-api

### CODE REVIEW

**Comment by raisedadead** [comment]
@sahilkhurana19 

1. Edit the PR title and remove the Issue no.
2. Edit the commit message and remove the Issue no.

    ```
    git commit --amend
    ```
    Change your commit message.
    ```
    gitt push origin fix/broken-link --force
    ```

Thanks for contributing.

**Comment by raisedadead** [comment]
Thanks @sahilkhurana19 for the changes.
/cc @Rafase282 @theflametrooper and @abhisekp to confirm if this has been renamed as per ongoing wiki migration.

Else we may have to edit this yet again.

**Comment by raisedadead** [comment]
Confirmed as okay [May 14, 2016 10:50 PM](https://gitter.im/FreeCodeCamp/Wiki?at=57375e481794136a7d08a9f6)



#### :sparkles: :sparkles: **LGTM.** :sparkles: :sparkles: 

:tada: Thanks @sahilkhurana19, for contributing and congratulations on your first submission to Free Code Camp :tada:

**Comment by sahilkhurana19** [comment]
@raisedadead Thanks for the guidance :smile:

**Pull request merged**
