### PR TITLE
Update link to a new Metric Imperial Conversion API demo

### PR DESCRIPTION
**Pull request by wmemorgan**
- [X ] I have read [freeCodeCamp's contribution guidelines](https://github.com/freeCodeCamp/freeCodeCamp/blob/master/CONTRIBUTING.md).
- [ X] My pull request has a descriptive title (not a vague title like `Update index.md`)
- [ X] My pull request targets the `master` branch of freeCodeCamp.
- [ X] None of my changes are plagiarized from another source without proper attribution.
- [ X] My article does not contain shortened URLs or affiliate links.

If your pull request closes a GitHub issue, replace the XXXXX below with the issue number.

Closes #XXXXX

### CODE REVIEW

**Comment by RandellDawson** [comment]
Closed and Reopened this PR to attempt to resolve a specific Travis build failure.

**Comment by wmemorgan** [comment]
Hi Randell,

Was my PR submitted correctly? It was my first PR with fCC.

**Comment by RandellDawson** [comment]
Yes, but there was some technical issues on our end, so we had to close and reopen to fix some things.

**Comment by RandellDawson** [comment]
Thank you for opening this pull request.

This is a standard message notifying you that we’ve reviewed your pull request and have decided not to merge it. We would welcome future pull requests from you.

**Reason:**  The url you provided does not work.  Also, we are looking to use a project which is owned by FCC and not an individual account which could be deleted.

Thank you and happy coding.

**Pull request closed without merging**
