### PR TITLE
refactor: use the English json as the schema

### PR DESCRIPTION
**Pull request by ojeytonwilliams**
@nhcarrigan I was thinking about https://github.com/freeCodeCamp/freeCodeCamp/pull/41140 and I reckon this problem arose because it's not obvious to a human what `donate.confirm-3` is and when it should be used instead of `donate.confirm-2`. That inspired me to rewrite them (`confirm-monthly`, `confirm-one-time` etc.) and then I realised I'd need to rewrite the schema too.

That leads me to this PR.  Since we're trying to validate that all three languages have the same json structure, is it sufficient to validate that everything has the same structure as `english`?

### CODE REVIEW

**Comment by nhcarrigan** [comment]
When I added this validation script, the schemas were already being used to test (through a different approach) and had to be re-written to work with this approach. I vaguely remember thinking about using the English files as the single source of truth, but thought it was a bad approach. Can't for the life of me remember *why* I thought that, though.

Regardless, the schemas are proving to be a bit of technical overhead that I agree we don't need (I forget to update them myself all the time). 100% in favour of removing them and using the English file as the root for testing.

**Review by naomi-lgbt — DISMISSED** [review]
IDK if an approval sticks around on a draft PR, but this looks good to me.

**Comment by ojeytonwilliams** [comment]
Yeah, I remember us discussing it briefly, but I can't remember what we concluded either.  If this proves troublesome somehow we can always revert.

> When this lands, I'll update the validate-keys script to not rely on the non-existent schema files.

You can pop that onto this PR if you reckon it fits.

**Comment by raisedadead** [comment]
I agree, Nick you should update this PR to update the validation script so it stays together.

**Comment by nhcarrigan** [comment]
Just took a look at this - the `validate-keys` script was already running against the English `translations.json` file. 

However, I'm going to push an update to validate the other `json` files as well.

**Review by naomi-lgbt — APPROVED** [review]
Not sure if I qualify, but still looks good to me

**Pull request merged**
