### PR TITLE
Added the relevance of the `alt` attribute to the description of the challenge in steps 2 and 3.

### LINKED ISSUE #44923: Adding an alt attribute to steps 2-4 of the CSS Box Model project
This might be a small issue, but I think for consistency sake we should always require users to add an alt attribute for their image tags.
In steps [2](https://www.freecodecamp.org/learn/2022/responsive-web-design/learn-the-css-box-model-by-building-a-rothko-painting/step-2), [3](https://www.freecodecamp.org/learn/2022/responsive-web-design/learn-the-css-box-model-by-building-a-rothko-painting/step-3), and [4](https://www.freecodecamp.org/learn/2022/responsive-web-design/learn-the-css-box-model-by-building-a-rothko-painting/step-4) the challenge has the users working with an image tag but they are not required to add an alt attribute.
I understand that we remove that image tag in step 5, but I think for best practices we should always require users to add the alt attribute. 

Thoughts?

### PR DESCRIPTION
**Pull request by Mfonn**
Checklist:

- [ ] I have read [freeCodeCamp's contribution guidelines](https://contribute.freecodecamp.org).
- [x] My pull request has a descriptive title (not a vague title like `Update index.md`)
- [x] My pull request targets the `main` branch of freeCodeCamp.
- [x] I have tested these changes either locally on my machine, or GitPod.

Closes #44923

### CODE REVIEW

**Comment by bbsmooth** [comment]
I don't think this is the proposed solution for this issue. In fact, I'm not sure we have a settled solution for this issue yet. But adding these disclaimers is probably not going to be part of it since I think we are ultimately going to do away with the images.

**Comment by jeremylt** [comment]
I agree, I don't think this is the fix we want.

**Comment by naomi-lgbt** [comment]
Thank you for opening this pull request.

This is a standard message notifying you that we've reviewed your pull request and have decided not to merge it. We would welcome future pull requests from you.

Thank you and happy coding.

**Comment by Mfonn** [comment]
Thank you for the feedback!

**Pull request closed without merging**
