### PR TITLE
Removes RSA links from English challenges

### LINKED ISSUE #37827: External links in coding challenges
**Describe your problem and how to reproduce it:**
In a recent pull request (#37802) it was brought to attention that there are external links in coding challenges such as [this one](https://github.com/freeCodeCamp/freeCodeCamp/blob/master/curriculum/challenges/english/02-javascript-algorithms-and-data-structures/basic-javascript/increment-a-number-with-javascript.english.md). Both @RandellDawson and @moT01 thought that it would be a good idea to remove any MDN links found in coding challenges.
I am creating this issue to discuss removing these links and where to possibly move them (such as to the corresponding forum topics, as Randell suggested).

### PR DESCRIPTION
**Pull request by Kbarias**
- [x] I have read [freeCodeCamp's contribution guidelines](https://github.com/freeCodeCamp/freeCodeCamp/blob/master/CONTRIBUTING.md).
- [x] My pull request has a descriptive title (not a vague title like `Update index.md`)
- [x] My pull request targets the `master` branch of freeCodeCamp.
- [x] None of my changes are plagiarized from another source without proper attribution.
- [x] All the files I changed are in the same world language (for example: only English changes, or only Chinese changes, etc.)
- [x] My changes do not use shortened URLs or affiliate links.

Related to #37827

### CODE REVIEW

**Comment by Kbarias** [comment]
Hello @raisedadead and @RandellDawson , just curious if it is removing the RSA links from challenges is still being considered?

**Comment by RandellDawson** [comment]
@Kbarias Yes, but we just have no got around to reviewing this PR.  There are still many earlier PRs needing review at this time.  We will eventually get to it though.

**Comment by ojeytonwilliams** [comment]
One quick observation: there are 74 English challenges with the text 'read-search-ask', but there aren't that many files in this PR.  Is there a reason they don't match?

I've not had chance to review in depth, yet, so sorry if this is a dumb question!

**Comment by moT01** [comment]
Looks like it's the projects. The `responsive web design`, `front end libraries` and `data visualization` projects got missed as far as I can tell.

**Comment by ojeytonwilliams** [comment]
Fair enough.  Projects are harder, so leaving the reminder for up for them doesn't seem terrible.

**Comment by moT01** [comment]
Well, maybe we should figure out what we want. The issue was to try and make these links consistent. The sections I listed all have the RSA links in the projects but the other sections don't have them in the projects. So I feel like we should either add the link to all the projects or get rid of it on those I mentioned, I don't mind either way. The projects might be a good place to keep them - any thoughts @RandellDawson?

**Comment by RandellDawson** [comment]
I was under the impression we were to remove them from all challenges (projects included).  As long as the Ask for Help button is located somewhere on a challenge or project (which it is), then the user will see the Read, Search, Ask link on the modal.  I say remove them everywhere except the modal.

**Comment by ojeytonwilliams** [comment]
Okay, that seems reasonable. @Kbarias could you add a commit removing the links from the projects?

**Comment by moT01** [comment]
Also, I don't think just removing the RSA links addresses the entire issue. The original issue was brought up because of other links (see issue). So those should probably be taken out as well - at least for the most part. There might be a few that need to stay, I'm not sure. I'm not sure how many more there is, but they can be added to this PR or we can make a separate one for the rest.

**Comment by ojeytonwilliams** [comment]
The other links require a bit more thought, though.  Presumably the information they link to is needed, so either should be mirrored on the forum (if it's something we can just copy) or the challenge will need changing or the link should stay.  I don't think there's a blanket solution.

I think it's fine to have this PR just remove the RSA links.  If that's okay with everyone, we can just edit the OP so it doesn't auto-close the issue.

**Comment by moT01** [comment]
agreed, I edited the post.

**Comment by scissorsneedfoodtoo** [comment]
Hi all, sorry I'm getting to this so late. I agree that we should be consistent, whether that's keeping or removing the RSA links. I'm in favor of removing them to keep the descriptions as concise as possible.

As @ojeytonwilliams mentioned, it seems fine for this PR to just remove the RSA links. We can then go back to whatever's left and handle that on a case-by-case basis, mirroring things on the forum if necessary.

**Comment by moT01** [comment]
I removed the remaining links in the mentioned areas. This should be good to go.

**Comment by moT01** [comment]
bump

**Review by RandellDawson — APPROVED** [review]
LGTM

**Comment by RandellDawson** [comment]
@scissorsneedfoodtoo If you are still OK with this PR, I think it is ready to be merged.

**Comment by scissorsneedfoodtoo** [comment]
Thank you @Kbarias and @moT01 for removing all of these RSA links. Also, thank you everyone for your thorough review.

**Pull request merged**
