### PR TITLE
chore(deps): update Cypress to version 12

### PR DESCRIPTION
**Pull request by ojeytonwilliams**
Checklist:

- [x] I have read and followed the [contribution guidelines](https://contribute.freecodecamp.org).
- [x] I have read and followed the [how to open a pull request guide](https://contribute.freecodecamp.org/#/how-to-open-a-pull-request).
- [x] My pull request targets the `main` branch of freeCodeCamp.
- [x] I have tested these changes either locally on my machine, or GitPod.

### CODE REVIEW

**Comment by naomi-lgbt** [comment]
I pushed a couple of commits, but this is strange.

The `cy.get()` calls seem to need a page refresh to see the elements in each test? In theory this should be a stateless method, but for some reason it seems to get stuck?

**Comment by naomi-lgbt** [comment]
I found the actual issue. Cypress 12, by default, [isolates tests](https://docs.cypress.io/guides/references/migration-guide#Test-Isolation). Turning that off should address a good portion of our issues.

**Comment by ojeytonwilliams** [comment]
@naomi-lgbt yeah, it does, but it also indicates our tests were poorly written. They should work in isolation, so I went ahead and made the updates that should allow that.

I also added some comments about why some tests fail locally. In this case because you don't live in Greenwich in the winter.

**Comment by ojeytonwilliams** [comment]
That was a struggle, but everything should be behaving itself now.

**Review by naomi-lgbt — APPROVED** [review]

**Review by moT01 — APPROVED** [review]
Nice one @ojeytonwilliams 👍

I don't particularly like removing all the `it` statements - they tell us what the test is for without relying on comments and, when something fails, we get a better idea of where it went wrong. Couldn't we have kept all the `it` statements and used the `{ testIsolation: false }` where needed? I think that's what I would have preferred.

Perhaps that would have lead to more flaky tests and unreliable errors. I'm gonna merge this since we've always has issues with flaky tests - hopefully this will make them more reliable.

**Comment by ojeytonwilliams** [comment]
> I don't particularly like removing all the it statements - they tell us what the test is for without relying on comments and, when something fails, we get a better idea of where it went wrong.

I think most of the it statements were just unnecessary from a documentation perspective, since the code is very readable with or without them.

That wasn't always the case, though, and there were definitely a few where the code could use more work. I just wanted to get it working for the weekend, so I rushed a bit!

**Pull request merged**
