### PR TITLE
Fixes issue with map line numbering breaking into differnet lines

### LINKED ISSUE #5309: Each character of the numbered list's index appears on it's own line on mobile
Link to the page: http://www.freecodecamp.com/map
How to replicate: Open the Map page on a mobile phone(or simulate a small screen).
Screenshot: 
screenshot_2015-12-15-23-57-35

### PR DESCRIPTION
**Pull request by josh3336**
[Fixes #5309]

### CODE REVIEW

**Comment by ltegman** [comment]
Looks much better! Thanks :+1:

**Comment by BerkeleyTrue** [comment]
@ltegman Doesn't this effect all `ul`'s?

**Comment by josh3336** [comment]
yea it would, there doesn't seem to be many specific identifying classes on elements and didn't know if it was acceptable to add one, for this specific ul.

**Comment by ltegman** [comment]
@BerkeleyTrue I didn't see any negative side effects on other `ul`'s from changing this, but I apologize if I jumped the gun on this and missed something.

**Comment by BerkeleyTrue** [comment]
It's looks good. In the future, changes to css should be scoped to the element they are trying to correct, otherwise unintended side-effects can happen.

Happy Coding!

**Pull request merged**
