### PR TITLE
Added eslint,jest-based tests.

### PR DESCRIPTION
**Pull request by olwanissam**
Checklist:

- [x] I have read [freeCodeCamp's contribution guidelines](https://contribute.freecodecamp.org).
- [x] My pull request has a descriptive title (not a vague title like `Update index.md`)
- [x] My pull request targets the `main` branch of freeCodeCamp.
- [x] I have tested these changes either locally on my machine, or GitPod.

Closes #XXXXX

I added a linter, however it's giving way too many errors in the existing project. Is this normal ?
Added jest-based tests as well, and a better error detection js file. Could use some feedback. Cheers.

### CODE REVIEW

**Comment by ojeytonwilliams** [comment]
Hi. We already have Jest and Eslint running in CI. What does this PR do differently?

**Comment by SuitlessStan** [comment]
Hey. I had seen them alright but I was assigned this task by Shaun. My bad,
should’ve dig deeper into it.
I added a js file for better error detection though.

**Comment by raisedadead** [comment]
Point us to the original discussion, this looks like a random PR change to us, and as is we are unable to review and land this.

Thanks for your understanding and looking forward to your future PRs.

**Comment by SuitlessStan** [comment]
I see now. That makes much more sense,lol. I've asked him to contribute to
the new API, and thus this whole shenanigan.

‫في الاثنين، 5 ديسمبر 2022 في 6:39 م تمت كتابة ما يلي بواسطة ‪Oliver
Eyton-Williams‬‏ ***@***.***‬‏>:‬

**Pull request closed without merging**
