### PR TITLE
fix: Update test for ES6 challenge

### LINKED ISSUE #34009: ES6: Use getters and setters to Control Access to an Object can be passed with an empty class
On the challenge "ES6: Use getters and setters to Control Access to an Object" you can pass the challenge by simply making a class with the name "Thermostat" that contains nothing.

**Add a Link to the page with the problem:**
https://learn.freecodecamp.org/javascript-algorithms-and-data-structures/es6/use-getters-and-setters-to-control-access-to-an-object

**Tell us about your browser and operating system:**
* Browser Name: Google Chrome
* Browser Version: Version 70.0.3538.77 (Official Build) (64-bit)
* Operating System: macOs Mojave Version 10.14

**If possible, add a screenshot here (you can drag and drop, png, jpg, gif, etc. in this box):**
screen shot 2018-10-31 at 9 12 21 pm

### PR DESCRIPTION
**Pull request by HugoLiconV**
- [x] I have read [freeCodeCamp's contribution guidelines](https://github.com/freeCodeCamp/freeCodeCamp/blob/master/CONTRIBUTING.md).
- [x] My pull request has a descriptive title (not a vague title like `Update index.md`)
- [x] My pull request targets the `master` branch of freeCodeCamp.
- [x] None of my changes are plagiarized from another source without proper attribution.
- [x] My article does not contain shortened URLs or affiliate links.

If your pull request closes a GitHub issue, replace the XXXXX below with the issue number.

Closes #34009

### CODE REVIEW

**Comment by RandellDawson** [comment]
@HugoLiconV Can you explain how your changes fixes the challenge?

**Comment by HugoLiconV** [comment]
@RandellDawson Sure, the problem was one function that was passed as a parameter to the assert needed to be inside an IIFE in order to execute it:
```javascript
// this won't work. It will never execute that function
testString: assert(() => {
  const t = new Thermostat(32); 
  // you can even put return false and the test won't fail
  return typeof t === 'object' && t.temperature === 0;
}, '<code>Thermostat</code> can be instantiated.');
```
So I put it inside an IIFE and I also added a solution to the challenge.

**Comment by ChrisBrownie55** [comment]
Is the added `console.log` necessary in any way???

**Comment by HugoLiconV** [comment]
@RandellDawson Any update?

**Comment by RandellDawson** [comment]
@ezioda004 What are your thoughts on this PR?

**Review by ezioda004 — APPROVED** [review]

**Comment by ezioda004** [comment]
@RandellDawson LGTM.

**Comment by RandellDawson** [comment]
@ezioda004 Another question, if I use the new solution code provided by the OP and just remove the `setter`, shouldn't the first test and third test still pass based on the test description?  

With respect to the 3rd test, I think the verbiage should be changed to something different, because you can still initiate `Thermostat` even if it does not have a `setter` or `getter` class for that matter.   Maybe a 4th test for validating `setter` and `getter` are actual functions also?

**Comment by lynxlynxlynx** [comment]
Randell, how about opening a new issue to address these extra questions? This PR already solves a problem and is just stagnating now.

**Comment by nikrb** [comment]
maybe lynx has a point, but ...
@RandellDawson I agree with you it should pass without a setter. 
Also seems odd that it fails if the temperature property isn't prefixed with an underscore.
I thought we were removing IIFE's, so the last test could be rewritten:
```
testString: () => { const t = new Thermostat(32); assert(typeof t === 'object' && t.temperature === 0, '<code>Thermostat</code> can be instantiated.')};
```

**Comment by RandellDawson** [comment]
Merge it if it makes an improvement.

**Comment by thecodingaviator** [comment]
This actually looks better to me. @lynxlynxlynx Merge if you find it fine

**Pull request merged**
