### PR TITLE
fix: update SEO on landing page

### PR DESCRIPTION
**Pull request by ahmaxed**
Here are the proposed changes to improve SEO.
Additionally, I changed the rest of the h1 titles in the landing page to h2.

Learn_to_Code_for_Free_–_Coding_Courses_for_Busy_People
Learn_to_Code_for_Free_–_Coding_Courses_for_Busy_People-1

### CODE REVIEW

**Comment by RandellDawson** [comment]
The `h1` to `h2` changes seem appropriate.  I am not a big fan of the long dash between "Learn to code" and "for free."  How does the dash help SEO?

**Comment by ahmadabdolsaheb** [comment]
> The `h1` to `h2` changes seem appropriate. I am not a big fan of the long dash between "Learn to code" and "for free." How does the dash help SEO?

@RandellDawson, thanks for the review. let's pick this up in the core chat.

**Comment by raisedadead** [comment]
Hi @ahmadabdolsaheb did you get a chance to confirm this change?

**Comment by ahmadabdolsaheb** [comment]
> Hi @ahmadabdolsaheb did you get a chance to confirm this change?

Yes, I just double checked with Quincy and changed the h2s to p. 
Also the screenshots above are provided by Quincy.

**Review by raisedadead — APPROVED** [review]

**Pull request merged**
