### PR TITLE
Update description of beta challenge

### LINKED ISSUE #13466: [beta] ES6: Use Destructuring Assignment with Objects - description errors
Challenge [use-destructuring-assignment-with-objects](http://beta.freecodecamp.com/en/challenges/es6/use-destructuring-assignment-with-objects) has an issue.
User Agent is: <code>Mozilla/5.0 (X11; Ubuntu; Linux i686; rv:51.0) Gecko/20100101 Firefox/51.0</code>.
Please describe how to reproduce this issue, and include links to screenshots if possible.

In description it says:

"Consider the following ES5 code:"
```js

const voxel = {x: 3.6, y: 7.4, z: 6.54 };
const x = voxel.x; // x = 3.6
const y = voxel.y; // y = 7.4
const z = voxel.z; // z = 6.54

```
"const" is ES6, should be "var"?

Also: is below code correct? Are there "a", "y", "z" on purpose, maybe to show that you can use xyz and abc?
```js
    const { x : a, y : b, z : c } = voxel // a = 3.6, y = 7.4, z = 6.54
```

**edit: This challenge is weird. I don't know how to solve it so I clicked "Run tests" to see some errors descriptions, but instead of errors I got confirmation of solved challenge (and all tests passed even though I didn't change anything in code yet).**

### PR DESCRIPTION
**Pull request by mapadev**
#### Pre-Submission Checklist

- [x] Your pull request targets the `staging` branch of freeCodeCamp.
- [x] Branch starts with either `fix/`, `feature/`, or `translate/` (e.g. `fix/signin-issue`)
- [x] You have only one commit (if not, [squash](http://forum.freecodecamp.com/t/how-to-squash-multiple-commits-into-one-with-git/13231) them into one commit).
- [x] All new and existing tests pass the command `npm test`. Use `git commit --amend` to amend any fixes.

#### Type of Change

- [x] Small bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds new functionality)
- [ ] Breaking change (fix or feature that would change existing functionality)
- [ ] Add new translation (feature adding new translations)

#### Checklist:

- [x] Tested changes locally.
- [x] Closes currently open issue (replace XXXX with an issue no): Closes #13466

### CODE REVIEW

**Comment by wisamsalem** [comment]
Can someone tell me why I'm getting this email?

**Comment by texas2010** [comment]
@wisamsalem 
looks like you may have accidentally subscribed to all notifications for the [FreeCodeCamp](https://github.com/FreeCodeCamp/FreeCodeCamp) repository. To stop receiving notifications please visit the [subscriptions page](https://github.com/FreeCodeCamp/FreeCodeCamp/subscription) and select "Not watching". Additionally, you can visit the [GitHub Help page on managing notification delivery methods](https://help.github.com/articles/managing-notification-delivery-methods/) for more help.

We are sorry for your inconvenience!

**Review by Greenheart — APPROVED** [review]
@gogolab You did it! Congratulations! :smile: :+1:

Thanks for helping out!

**Comment by wisamsalem** [comment]
Thanks, glad to help. Hope I can do better.

**Comment by Greenheart** [comment]
@gogolab You're off to a great start, keep it up! :smile:

**Pull request merged**
