### PR TITLE
translated some Chinese curriculum files

### PR DESCRIPTION
**Pull request by miyaliu666**
Checklist:

- [x] I have read [freeCodeCamp's contribution guidelines](https://contribute.freecodecamp.org).
- [x] My pull request has a descriptive title (not a vague title like `Update index.md`)
- [x] My pull request targets the `master` branch of freeCodeCamp.
- [x] All the files I changed are in the same world language, for example: only English changes, or only Chinese changes, etc.

### CODE REVIEW

**Comment by moT01** [comment]
Do we have a process for keeping track of what files have been fixed or looked over? Should we just check the box next to each lesson on the issue after this gets merged? I think some files don't need any changes - we can probably just remove those from the issues when they are found - just trying to get on the same page for these.

**Comment by miyaliu666** [comment]
> Do we have a process for keeping track of what files have been fixed or looked over? Should we just check the box next to each lesson on the issue after this gets merged? I think some files don't need any changes - we can probably just remove those from the issues when they are found - just trying to get on the same page for these.

Just saw this comment. If I understand right, I've checked the first four boxes of issues #40463. For the last one (task #5), we'll fix them on Crowdin later as Randy and I agreed before. Not sure if we can merge this PR now. All the content is fine. Do you want to take a look? @RandellDawson

**Comment by RandellDawson** [comment]
> Just saw this comment. If I understand right, I've checked the first four boxes of issues #40463. For the last one (task #5), we'll fix them on Crowdin later as Randy and I agreed before. Not sure if we can merge this PR now. All the content is fine. Do you want to take a look? @RandellDawson

@miyaliu666 Since we do not have a finalized date for Crowdin integration, it would probably be better to go ahead and translate as many of these as possible.  We will upload all these changes the Chinese translation team as been working on (via GitHub PRs) into Crowdin's translation memory before opening up the translation of challenges on Crowdin.

**Review by RandellDawson — APPROVED** [review]

**Comment by RandellDawson** [comment]
I am merging this PR, so we can push the changes up to Crowdin.

**Comment by RandellDawson** [comment]
@miyaliu666 Thank you for your contribution to the page! 👍
We're happy to accept these changes, and look forward to future contributions. 🎉

**Pull request merged**
