### PR TITLE
Fix: return a value from a function with return

### LINKED ISSUE #9583: Issue with Return a Value from a Function with Return
Challenge [Return a Value from a Function with Return](https://www.freecodecamp.com/challenges/return-a-value-from-a-function-with-return#?solution=%0A%2F%2F%20Example%0Afunction%20minusSeven%28num%29%20%7B%0A%20%20return%20num%20-%207%3B%0A%7D%0Avar%20answer%20%3D%20minusSeven%287%29%3B%0A%2F%2F%20Only%20change%20code%20below%20this%20line%0A%0A%0A) has an issue.
User Agent is: <code>Mozilla/5.0 (Windows NT 6.1; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/51.0.2704.103 Safari/537.36</code>.
Please describe how to reproduce this issue, and include links to screenshots if possible.

My code:
function timesFive(num){
  return num \* 5;
}
var answer = timesFive(5);

// Example
function minusSeven(num) {
  return num - 7;
}
var answer = minusSeven(7);
// Only change code below this line

```
**The console deck won't change no matter what you type in. Always showing "timesFive(5)===25".**

People who have this kind of problem could go to this link and test:
https://jsbin.com/daxoyifabe/edit?html,css,output
```

### PR DESCRIPTION
**Pull request by ananaymital**
#### Pre-Submission Checklist

- [x] Your pull request targets the `staging` branch of FreeCodeCamp.
- [x] Branch starts with either `fix/`, `feature/`, or `translate/` (e.g. `fix/signin-issue`)
- [x] You have only one commit (if not, [squash](http://forum.freecodecamp.com/t/how-to-squash-multiple-commits-into-one-with-git/13231) them into one commit).
- [x] All new and existing tests pass the command `npm run test-challenges`. Use `git commit --amend` to amend any fixes.
#### Type of Change

- [x] Small bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds new functionality)
- [ ] Breaking change (fix or feature that would change existing functionality)
- [ ] Add new translation (feature adding new translations)
#### Checklist:

- [x] Tested changes locally.
- [x] Closes #9583
#### Description

Deleted the **tail** in the challenge. Couldn't find a better way.

### CODE REVIEW

**Comment by ananaymital** [comment]
I can't figure out how to remove that html commit from this PR

**Comment by atjonathan** [comment]
@ananaymital, try using `git rebase -I HEAD~2` and change `pick` to `drop` to remove the commits. If you want to keep the changes of the commit use `squash` to squash the two together.

**Comment by fooosmar** [comment]
via Newton Mail 
[https://cloudmagic.com/k/d/mailapp?ct=pi&cv=9.1.19&pv=10.1&source=email_footer_2]

**Comment by fooosmar** [comment]
---------- 转发的邮件 ----------
发件人： *Thomas* <notifications@github.com>
日期： 2016年10月11日星期二
主题： [web-pal/DBGlass] Empty password (#17)
收件人： web-pal/DBGlass <DBGlass@noreply.github.com>


Allow for an empty password (ie: localhost connection)

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub
<https://github.com/web-pal/DBGlass/issues/17>, or mute the thread

**Pull request closed without merging**
