### PR TITLE
fix: stop modal appearing in steps

### PR DESCRIPTION
**Pull request by ojeytonwilliams**
- fix: stop showing completion modal on steps
- feat: submit steps with ctrl+enter

### CODE REVIEW

**Review by scissorsneedfoodtoo — DISMISSED** [review]
Tested locally with a handful of steps from one of the new projects. It's great that the modal no longer pops up and breaks the flow of moving from step to step.

Also tested with some of the older challenges to ensure the modal still appears in these instances.

Everything LGTM :+1: :+1:

**Review by gikf — COMMENTED** [review]
A bit edge case - when both html and css are visible, and focus is on the frame without editable region, ctrl+enter will bring up the modal. Is that intended or wanted?

**Review by gikf — COMMENTED** [review]
I still get modal appear when both html and css *tabs* are visible, code will pass, and focus is not on the frame with editable region.

When both are hidden, modal doesn't appear, however with passing code. ctrl + enter twice will go to next challenge.

**Review by ShaunSHamilton — CHANGES_REQUESTED** [review]
This LGTM 👍 Pending removal of logs

Although, it is concerning to see how many times that log is printed to the console with edits and each test

**Review by ShaunSHamilton — DISMISSED** [review]
👍 This LTMG 👍

**Review by ahmaxed — APPROVED** [review]

**Pull request merged**
