### PR TITLE
Fix : Spelling errors

### PR DESCRIPTION
**Pull request by DipakKumarSingh**
"buisnesses" should be "businesses"
"enviorment" should be "environment"
"disiplines" should be "disciplines"
"impove" should be "improve"

- [x] I have read [freeCodeCamp's contribution guidelines](https://github.com/freeCodeCamp/freeCodeCamp/blob/master/CONTRIBUTING.md).
- [x] My pull request has a descriptive title (not a vague title like `Update index.md`)
- [x] My pull request targets the `master` branch of freeCodeCamp.
- [x] None of my changes are plagiarized from another source without proper attribution.
- [x] My article does not contain shortened URLs or affiliate links.

If your pull request closes a GitHub issue, replace the XXXXX below with the issue number.

Closes #XXXXX

### CODE REVIEW

**Comment by DipakKumarSingh** [comment]
"Until" is an acceptable and meaningful word. Undemand - again depends on
usage, I got fair idea what the sentence meant to say hence kept it as it
is.

**Review by ezioda004 — APPROVED** [review]

**Comment by ezioda004** [comment]
@honmanyau These changes are fine since they improve this article in particular. So I merged this.

@DipakKumarSingh As @honmanyau suggested, in future please make a single PR for such small corrections. Thank you for your contribution.

**Comment by DipakKumarSingh** [comment]
I also have a couple of similar ones open, can you please club and approve?

**Comment by honmanyau** [comment]
@ezioda004 Thank you for having another look and for sorting it out! ☀️ 

@DipakKumarSingh 

> "Until" is an acceptable and meaningful word. Undemand - again depends on

Yes, it is and I have no issues with its usage; I was referring to the fact that that it's currently misspelled as "untill" with two L's in the article.

I still think the use of "undemand" is very questionable if not plain wrong; my best guess is the original author seems to want to mean "produce without question" or "yield without question", and the sentence doesn't mean that at all as it is; it now reads like it has the meaning of "retract", which is just wrong.

In any case, the PR has been merged now so it's pointless to debate about these unless another PR is opened to fix those; that's just to wrap up the discussion and for future reference. Feel free to submit another PR and reference this Issue if it's not just for the sake of Hacktoberfest.

**Pull request merged**
