### PR TITLE
fix(curriculum): fix typo remaing to remaining

### LINKED ISSUE #57651: [Plant Nursery Catalog] Typo in step 8
## Description

Change `remaing` to `remaining` in:

https://github.com/freeCodeCamp/freeCodeCamp/blob/3cf0b74964b7647c3225cb740ed18c4e51c85e27/curriculum/challenges/english/25-front-end-development/workshop-plant-nursery-catalog/6734a606e5968a5a19b77171.md#L10

### PR DESCRIPTION
**Pull request by JungLee-Dev**
Checklist:

- [x] I have read and followed the [contribution guidelines](https://contribute.freecodecamp.org).
- [x] I have read and followed the [how to open a pull request guide](https://contribute.freecodecamp.org/how-to-open-a-pull-request/).
- [x] My pull request targets the `main` branch of freeCodeCamp.
- [ ] I have tested these changes either locally on my machine, or GitPod.

Closes #57651

### CODE REVIEW

**Review by jdwilkin4 — APPROVED** [review]

**Comment by jdwilkin4** [comment]
@JungLee-Dev 

I have updated your PR description to properly link the issue with the PR.
Please re read through our PR guidelines so you will know how to do this in the future 
https://contribute.freecodecamp.org/how-to-open-a-pull-request/

**Comment by JungLee-Dev** [comment]
> @JungLee-Dev
> 
> I have updated your PR description to properly link the issue with the PR. Please re read through our PR guidelines so you will know how to do this in the future https://contribute.freecodecamp.org/how-to-open-a-pull-request/

@jdwilkin4
Thank you for letting me know and updating my PR description with issue number. Now I understand PR requests better.

_"If the PR is meant to address an existing GitHub Issue then, at the end of your PR’s description body, use the keyword Closes with the issue number to [automatically close that issue if the PR is accepted and merged](https://help.github.com/en/articles/closing-issues-using-keywords).

Example: Closes #123 will close issue 123"_

**Review by zairahira — APPROVED** [review]

**Comment by gikf** [comment]
Hi @JungLee-Dev. Congrats on your first pull request (PR)! 🎉

Thank you for your contribution to the page! 👍
We are happy to accept these changes and look forward to future contributions. 📝

**Comment by JungLee-Dev** [comment]
> Hi @JungLee-Dev. Congrats on your first pull request (PR)! 🎉
> 
> Thank you for your contribution to the page! 👍 We are happy to accept these changes and look forward to future contributions. 📝

Hi @gikf. Thank you for your warm words.
I'm very happy to have contributed and look forward to what's to come.

**Pull request merged**
