### PR TITLE
Fixup Map the Debris

### PR DESCRIPTION
**Pull request by bluestealth**
Units were missing, calculated values do not match results using constants for Earth's Radius, Earth's Mass, and the Gravitational Constant G from Wikipedia.

### CODE REVIEW

**Comment by terakilobyte** [comment]
Units are implied to be in KM and seconds, grabbing the formula from Wikipedia (which was part of the point of this challenge) makes that obvious. Additionally, your updated units do not match what I'm pulling from Wikipedia, nor Wolfram Alpha.

I'll need to see a functioning algorithm that succeeds using the tests you've provided before this can be accepted.

**Comment by bluestealth** [comment]
Here is the JavaScript code I used.
Alternatively you could just list the constants used to reach your solution in the problem description.
I do not think units should ever be implied, it also may be wise to allow for a certain amount of error in solutions.
```javascript
  function AltToPeriod(alt) {
    var G = 6.6738480e-11; /*http://en.wikipedia.org/wiki/Gravitational_constant*/
    var Me = 5.97219e24; /*http://en.wikipedia.org/wiki/Earth*/
    var Re = 6371000; /*http://en.wikipedia.org/wiki/Earth*/
    /*Small body orbiting a central body from http://en.wikipedia.org/wiki/Orbital_period 
     T = 2\pi\sqrt{a^3/mu} where, mu=G*M */
    /*T=2*pi*sqrt((Alt(in Meters)+Radius_Earth)^3/(G*M_Earth)) */
    return Math.round( 2*Math.PI*Math.sqrt(Math.pow(alt*1000+Re,3)/(G*Me)) );
  }
```

**Comment by terakilobyte** [comment]
While I still somewhat disagree about the units (the formula is given in KM and seconds, afterall), I agree it should be cleaned up to be precise.

I also like the idea of a range as people can get slightly different values depending on where they get their info (preferable Wolfram Alpha!).

If you could add that in to this bonfire I'll gladly pull this in.

**Comment by terakilobyte** [comment]
Also thanks to @johnmellis

**Pull request closed without merging**
