### PR TITLE
chore(i18n,learn): processed translations

### PR DESCRIPTION
**Pull request by camperbot**
This PR was opened auto-magically by Crowdin.

### CODE REVIEW

**Comment by naomi-lgbt** [comment]
Build validation errors passing locally.

**Comment by naomi-lgbt** [comment]
Lint issues resolved locally.

**Comment by naomi-lgbt** [comment]
Tests to validate:

- [ ] Espanol
- [ ] Chinese
- [ ] Chinese Traditional
- [ ] Italian
- [ ] Portuguese
- [ ] Ukrainian
- [ ] Japanese
- [ ] German
- [ ] Arabic

**Review by naomi-lgbt — APPROVED** [review]
Okay, everything seems to pass locally. This *should* be good to go.

**Review by majestic-owl448 — APPROVED** [review]

**Pull request merged**
