### PR TITLE
index.md

### PR DESCRIPTION
**Pull request by Joe-Lalama**
added an explanation of the bash command

- [x] I have read [freeCodeCamp's contribution guidelines](https://github.com/freeCodeCamp/freeCodeCamp/blob/master/CONTRIBUTING.md).
- [x] My pull request has a descriptive title (not a vague title like `Update index.md`)
- [x] My pull request targets the `master` branch of freeCodeCamp.
- [x] None of my changes are plagiarized from another source without proper attribution.
- [x] My article does not contain shortened URLs or affiliate links.

If your pull request closes a GitHub issue, replace the XXXXX below with the issue number.

Closes #XXXXX

### CODE REVIEW

**Comment by Joe-Lalama** [comment]
new to this.  hope it's helpful.

**Comment by Asjas** [comment]
Please read the Contributing Guidelines that is linked in the PR template that you checked. You need to follow the style that is set out in the Article Style Guide.

Your PR does not conform to any of the requirements that are needed to be merged.

Once you have made the necessary changes I will review it.

**Comment by jonathan-grah** [comment]
@Joe-Lalama, update on this?

**Comment by Joe-Lalama** [comment]
So apparently I did not understand what this command does when I created this.  The original definition that i read for bash was very general and maybe even wrong.  I've done a little research and tried to give a more accurate description.  But, admittedly I'm still not 100% on what the full use of this command is.  I removed ifconfig, not sure why that was even there or how I missed it.  I also finally fixed the file name to index.md.  I think that's everything.  Thanks for the feedback.

**Comment by RandellDawson** [comment]
@Joe-Lalama Your changes still show a file path of `guide/english/bash/bash`.  You should have been making changes to the file located at `guide/english/bash/index.md`

Since the time you created this PR, the file on the master branch has changed significantly.  I suggest rebasing your local master (if you were working locally) and then review the file above to see if your changes are even warranted.  If all your changes were made from your fork, you need to [update your fork](https://github.com/KirstieJane/STEMMRoleModels/wiki/Syncing-your-fork-to-the-original-repository-via-the-browser).  Either way, I am closing this PR, because your changes are no longer relevant.

Feel free to create a new pull request with any new changes/additions you feel the article needs.

Thank you.

**Pull request closed without merging**
