### PR TITLE
fix(curriculum): Add more valid triples to the test

### LINKED ISSUE #35070: project euler problem 9
**Describe your problem and how to reproduce it:**
The answer to the project euler problem 9 special pythagorean triplet for n=120 should be 60000 but instead it says 49920 to be the answer

**Add a Link to the page with the problem:**

https://learn.freecodecamp.org/coding-interview-prep/project-euler/problem-9-special-pythagorean-triplet
**Tell us about your browser and operating system:**
* Browser Name: chrome
* Browser Version: Version 72.0.3626.81 (Official Build) (64-bit)
* Operating System: centos 7

**If possible, add a screenshot here (you can drag and drop, png, jpg, gif, etc. in this box):**

### PR DESCRIPTION
**Pull request by ojeytonwilliams**
- [x] I have read [freeCodeCamp's contribution guidelines](https://github.com/freeCodeCamp/freeCodeCamp/blob/master/CONTRIBUTING.md).
- [x] My pull request has a descriptive title (not a vague title like `Update index.md`)
- [x] My pull request targets the `master` branch of freeCodeCamp.
- [x] None of my changes are plagiarized from another source without proper attribution.
- [x] All the files I changed are in the same world language (for example: only English changes, or only Chinese changes, etc.)
- [x] My changes do not use shortened URLs or affiliate links.

There are three Pythagorean triples that sum to 120.  This changes the test to allow all three and cleans up all the tests.

Closes #35070

### CODE REVIEW

**Review by paulywill — APPROVED** [review]
LGTM!

Tested locally.

**Comment by RandellDawson** [comment]
@ojeytonwilliams, @paulywill  What are the values of a, b, and c which result in the product 55080 and 60000?

**Comment by paulywill** [comment]
> @ojeytonwilliams, @paulywill What are the values of a, b, and c which result in the product 55080 and 60000?

Good question... only ran the `npm run test`.

**Comment by ojeytonwilliams** [comment]
@RandellDawson  `[24,45,51]` gives you 55080  and  `[30,40,50]` gives you 60000.  I don't think anyone's likely to land on the first one, but in principle they could use a weird search algorithm.

**Comment by RandellDawson** [comment]
> I don't think anyone's likely to land on the first one, but in principle they could use a weird search algorithm.

@ojeytonwilliams Yes, 24 * 45 * 51 = 55080, but (24, 45, 51) is not a Pythagorean triple, because a<sup>2</sup> (24<sup>2</sup>) + b<sup>2</sup> (45<sup>2</sup>) **is not equal** to c<sup>2</sup> (51<sup>2</sup>).  That is the definition of a Pythagorean triple. 

The first one (49920) is the only value where a * b * c = 49920 AND where a<sup>2</sup> (20<sup>2</sup>) + b<sup>2</sup> (48<sup>2</sup>) **is equal** to c<sup>2</sup> (52<sup>2</sup>). 

Remember the number for `c` (120) is passed to the function and 20 + 48 + 52 = 120.

The person who added those other two values to the test did not understand the definition and/or wrote the wrong algorithm when solving this problem.
```
    testString: assert.strictEqual(specialPythagoreanTriplet(120), 49920);
```

**Comment by ojeytonwilliams** [comment]
They're definitely Pythagorean triples.  Just to ensure I'm not doing something daft, here's the working:

24<sup>2</sup> + 45<sup>2</sup> = 576 + 2025 = 2601
51<sup>2</sup> = 2601

30<sup>2</sup> + 40<sup>2</sup> = 900 + 1600 = 2500
50<sup>2</sup> = 2500

**Comment by RandellDawson** [comment]
@ojeytonwilliams I sincerely apologize.  I am not sure what I was thinking when I wrote the above comment.  I confirm these are all valid Pythagorean triplets.

**Review by RandellDawson — APPROVED** [review]
After a second review, everything looks fine.

**Comment by RandellDawson** [comment]
Thank you for your contribution to the page! 👍
We're happy to accept these changes, and look forward to future contributions. 🎉

**Comment by ojeytonwilliams** [comment]
@RandellDawson No harm done!

**Pull request merged**
