### PR TITLE
Fixed Typographical Error in guide/english/angular/index.md

### PR DESCRIPTION
**Pull request by iamrajiv**
- [x] I have read [freeCodeCamp's contribution guidelines](https://github.com/freeCodeCamp/freeCodeCamp/blob/master/CONTRIBUTING.md).
- [x] My pull request has a descriptive title (not a vague title like `Update index.md`)
- [x] My pull request targets the `master` branch of freeCodeCamp.
- [x] None of my changes are plagiarized from another source without proper attribution.
- [x] All the files I changed are in the same world language (for example: only English changes, or only Chinese changes, etc.)
- [x] My changes do not use shortened URLs or affiliate links.

### CODE REVIEW

**Review by theNaut1lus — APPROVED** [review]
@iamrajiv some good error correction there.

**Comment by iamrajiv** [comment]
thank you @co16353sidak

**Review by thecodingaviator — APPROVED** [review]
LGTM! 👍

**Comment by iamrajiv** [comment]
@RandellDawson is this PR good to merged

**Review by RandellDawson — APPROVED** [review]

**Comment by RandellDawson** [comment]
Thank you for your contribution to the page! 👍
We're happy to accept these changes, and look forward to future contributions. 🎉

**Comment by iamrajiv** [comment]
thank you @RandellDawson :+1:

**Comment by RandellDawson** [comment]
@iamrajiv You can safely delete the branch locally and on your fork, because the PR has been merged.

**Comment by iamrajiv** [comment]
@RandellDawson but after my PR got merged I have sync my local repo and fork repo to make even with freeCodeCamp:master. Since new changes merged to my local and fork repo my branch should automatically be removed but it is still there... Why it is not automatically removed like other organizations have this feature... can you help me out of this

**Comment by RandellDawson** [comment]
@iamrajiv You can delete the branch from you fork easily by clicking the Trash Can by the branch name on GitHub.  Then locally, you can delete the branch by using `git branch -D Fixed-Typographical-Error-in-guide/english/angular/index.md`.  Lastely, remove the remote reference locally by using `git remote prune origin`.

> Why it is not automatically removed like other organizations have this feature

We just don't have this feature yet.  You can create an issue and ask for it.  In the issue, make sure to give an example of another repo which has this feature and post details and/or links to how it can be implemented.  I am sure we would at least look into it.

**Comment by iamrajiv** [comment]
thank you @RandellDawson for guidance I will try to make issues on this and also try to implement it :+1:

**Pull request merged**
