### PR TITLE
Fix typo in redux.json

### LINKED ISSUE #16920: [Beta] Typo in Redux: Dispatch an Action Event
#### Challenge Name

https://beta.freecodecamp.org/en/challenges/redux/dispatch-an-action-event

#### Issue Description

Redux: Dispatch an Action Event

The first sentence reads, "od is what you use to dispatch actions to the Redux store." That makes no sense and is probably a typo.

#### Browser Information

* Browser Name, Version: Firefox Quantum 59.0.1 (64-bit)
* Operating System: Windows 7 x64
* Mobile, Desktop, or Tablet: NIL

#### Screenshot

image

### PR DESCRIPTION
**Pull request by durgeshra**
#### Pre-Submission Checklist

- [x ] Your pull request targets the `staging` branch of freeCodeCamp.
- [ x] Branch starts with either `fix/`, `feature/`, or `translate/` (e.g. `fix/signin-issue`)
- [ x] You have only one commit (if not, [squash](http://forum.freecodecamp.org/t/how-to-squash-multiple-commits-into-one-with-git/13231) them into one commit).
- [ x] All new and existing tests pass the command `npm test`. Use `git commit --amend` to amend any fixes.

#### Type of Change

- [ x] Small bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds new functionality)
- [ ] Breaking change (fix or feature that would change existing functionality)
- [ ] Add new translation (feature adding new translations)

#### Checklist:

- [x ] Tested changes locally.
- [x] Addressed currently open issue (replace XXXXX with an issue no in next line)

Closes #XXXXX

#### Description

closes #16920

### CODE REVIEW

**Comment by raisedadead** [comment]
Hi @durgeshra since this PR was made over GitHub, this was most likely not tested locally?

**Comment by raisedadead** [comment]
The changes look fine to me, but we would want you to follow the Contributing Guidelines, and adhere to some of the conventions in future.

**Comment by durgeshra** [comment]
Oh! I am extremely sorry for that x being mentioned incorrectly. May I know what guidelines I failed to follow except for commiting changes on GitHub itself? Thank you so much!

**Comment by durgeshra** [comment]
Any other steps that I should take in this PR and others in future to satisfy your expectations are most welcome. :-)

**Comment by raisedadead** [comment]
@durgeshra here are our [Guidelines for Contributing](https://github.com/freeCodeCamp/freeCodeCamp/blob/staging/CONTRIBUTING.md)

**Comment by durgeshra** [comment]
Can I expect this PR to get merged, or I should rectify it? Will definitely agree to the guidelines. :-)

**Comment by durgeshra** [comment]
@raisedadead  please look at #16935

**Comment by QuincyLarson** [comment]
I'm closing this in favor of https://github.com/freeCodeCamp/freeCodeCamp/pull/16935

**Pull request closed without merging**
