### PR TITLE
Add solutions to Bootstrap challenges

### PR DESCRIPTION
**Pull request by Dana94**
- [x] I have read [freeCodeCamp's contribution guidelines](https://github.com/freeCodeCamp/freeCodeCamp/blob/master/CONTRIBUTING.md).
- [x] My pull request has a descriptive title (not a vague title like `Update index.md`)
- [x] My pull request targets the `master` branch of freeCodeCamp.
- [x] None of my changes are plagiarized from another source without proper attribution.
- [x] All the files I changed are in the same world language (for example: only English changes, or only Chinese changes, etc.)
- [x] My changes do not use shortened URLs or affiliate links.

### CODE REVIEW

**Review by thecodingaviator — COMMENTED** [review]
@Dana94 as far as I know, @Manish-Giri had already taken this up.

**Comment by Dana94** [comment]
@thecodingaviator Ok, if you think it's not necessary then feel free to close it. I'm not familiar with that label, so does @Manish-Giri already have a PR like this?

**Comment by thecodingaviator** [comment]
@Dana94 ,

@Manish-Giri would close the PR or free it for review if and as he feels necessary. He might not already have a PR, but might have a local branch which he may be working on. Since he commented on the issue to take it up, he has the right to make a PR :)

**Comment by RandellDawson** [comment]
@Dana94 I have reviewed @Manish-Giri and we are waiting on a second review, but it appears the other PR which actually includes 19 other Bootstrap challenge solutions will be merged instead of yours.  Thanks for understanding.  We are going to close this PR for now, but welcome future PRs from you.  Take a look at the [list of current issues](https://github.com/freeCodeCamp/freeCodeCamp/issues) and see if you can help with one that is labeled `help wanted`

**Pull request closed without merging**
