### PR TITLE
Standardize indent size in Data Structures challenge seeds

### PR DESCRIPTION
**Pull request by TyMick**
Checklist:

- [x] I have read [freeCodeCamp's contribution guidelines](https://contribute.freecodecamp.org).
- [x] My pull request has a descriptive title (not a vague title like `Update index.md`)
- [x] My pull request targets the `master` branch of freeCodeCamp.
- [x] All the files I changed are in the same world language, for example: only English changes, or only Chinese changes, etc.

Current challenge seed switches between 4-space indenting and 2-space indenting. This change standardizes the indenting to 2 spaces.

### CODE REVIEW

**Comment by tywmick** [comment]
You know what, I'm finding myself making several "standardize indent size" PRs, and given they all have the exact same purpose, they can all be handled together. I'm gonna close #38812 and #38815 and merge them with this one.

**Comment by moT01** [comment]
I have blocked this for now. See the [pinned code freeze issue](https://github.com/freeCodeCamp/freeCodeCamp/issues/38308)

**Comment by raisedadead** [comment]
Limitations removed on Coding Interview Prep Challenges.

**Review by moT01 — APPROVED** [review]
LGTM @tywmick 🎉 Thanks for contributing to freeCodeCamp 🎉

**Pull request merged**
