### PR TITLE
[Search] Fix styling - autocomplete out of screen

### LINKED ISSUE #29806: Search autocomplete display out of screen
**Describe the bug**
Auto-complete dropdown in Quick search in top navigation bar is out of screen.

**To Reproduce**
1. Go to 'https://learn.freecodecamp.org/'
2. Type text in Search Input at the top navigation bar
3. See the auto-complete dropdown, the block width is out of screen

**Expected behavior**
The search auto-complete dropdown should be displayed properly

**Screenshots**
search

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser: Firefox, Chrome

### PR DESCRIPTION
**Pull request by sureemo**
- [x] I have read [freeCodeCamp's contribution guidelines](https://github.com/freeCodeCamp/freeCodeCamp/blob/master/CONTRIBUTING.md).
- [x] My pull request has a descriptive title (not a vague title like `Update index.md`)
- [x] My pull request targets the `master` branch of freeCodeCamp.
- [x] None of my changes are plagiarized from another source without proper attribution.
- [x] My article does not contain shortened URLs or affiliate links.

Closes #29806. #18150

Note
- Fix search autocomplete width & position
- Fix search result item padding

Result:
search_improve

### CODE REVIEW

**Comment by raisedadead** [comment]
This maynot be the only place that this needs to be changed. The codebase has divulged from what you see on the production site. @Bouncey can you check and guide.

**Comment by zybex86** [comment]
Well the search bar is still BBB :)

**Comment by Cyb3rN4u7** [comment]
is this issue still open?

**Comment by Cyb3rN4u7** [comment]
### Hello guys , i have noticed that in screens that are smaller than 600px the problem persists

screen shot 2018-12-07 at 09 58 19

### I have a solution if you are interested
screen shot 2018-12-07 at 10 13 44

**Comment by fifn2** [comment]
This is happening to me too.
image
Using my magic power of Chrome Dev Tools, I found out that this was happening regardless of the viewport width.

**Comment by RandellDawson** [comment]
@raisedadead The original issue #18150 for which this PR was created seems to no longer be and issue.  I tested the latest version of the `master` branch locally and tested the search feature out on the beta site and no longer see this issue.  I can confirm too that this used to be a problem and still is on the current production site.

I think we can close this PR, but I will let you make the call on it.

**Comment by raisedadead** [comment]
I will defer to @Bouncey on this for this expertise on this component.

**Comment by Bouncey** [comment]
Currently the css is the only thing we adjust with regards to search in this repository. If the issue no longer exists on the master branch, then this PR is no longer required.

Sorry @sureemo, it seems like another PR has been merged fixing the issue. At the time you submitted this PR we had over 5000 open pull requests, so things like this are almost guaranteed to happen. Please don't let it discourage you from contributing to freeCodeCamp in the furture.

Happy Coding!

**Pull request closed without merging**
