### PR TITLE
replace Hyperdev references with Gomix

### LINKED ISSUE #13092: [beta] change all instances of "HyperDev" to "gomix" (or GoMix?)
In addition to #13091 regarding HyperDev, apparently HyperDev is no longer HyperDev. Our codebase should be updated to reflect the new name GoMix (or gomix). Otherwise, campers will be running around like developers with their heads cut off trying to find something that does not exist. 

The current references to HyperDev are in the APIs and Microservices section primarily

### PR DESCRIPTION
**Pull request by dhcodes**
#### Pre-Submission Checklist

- [X] Your pull request targets the `staging` branch of freeCodeCamp.
- [X] Branch starts with either `fix/`, `feature/`, or `translate/` (e.g. `fix/signin-issue`)
- [X] You have only one commit (if not, [squash](http://forum.freecodecamp.com/t/how-to-squash-multiple-commits-into-one-with-git/13231) them into one commit).
- [X] All new and existing tests pass the command `npm test`. Use `git commit --amend` to amend any fixes.

#### Type of Change

- [X] Small bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds new functionality)
- [ ] Breaking change (fix or feature that would change existing functionality)
- [ ] Add new translation (feature adding new translations)

#### Checklist:

- [X] Tested changes locally.
- [X] Closes currently open issue (replace XXXX with an issue no): Closes #13092 

#### Description

Changed all instances of Hyperdev to Gomix.

### CODE REVIEW

**Review by Greenheart — COMMENTED** [review]
@dhcodes This looks good!

I'm just unsure if we should change [these instances of "hyperdev"](https://github.com/freeCodeCamp/freeCodeCamp/blob/staging/client/rechallenge/throwers.js#L52-L60) too.
@BerkeleyTrue would probably be the right person to answer that.

**Comment by raisedadead** [comment]
#### :sparkles: :sparkles: **LGTM.** :sparkles: :sparkles: 

Thanks @dhcodes and yes, we need to update the file pointed above by @Greenheart ! Good catch.

**Comment by Greenheart** [comment]
@raisedadead That function seems to be some kind of protection against malicious code. Maybe we should change it to take both `hyperdev` and `gomix` into account?

**Comment by BerkeleyTrue** [comment]
> That function seems to be some kind of protection against malicious code. Maybe we should change it to take both hyperdev and gomix into account?

@Greenheart Actually we have removed hyperdev from our [connect src csp](https://github.com/freeCodeCamp/freeCodeCamp/blob/staging/server/middlewares/csp.js#L22) so code with ajax requests to hyperdev will no longer run. So we will need to change that transformer to check for gomix domains instead of hyperev. Also, those error descriptions should be a little more informative.

**Pull request merged**
