### PR TITLE
fix: Typo in "Convert seconds to compound duration"

### LINKED ISSUE #42246: Typo in "Convert seconds to compound duration"
In this table, the left column represents the same duration as in the right column, but in seconds.
The left middle-left cell should be 86400 instead of 72**86400**59.

[Challenge: Convert seconds to compound duration](https://www.freecodecamp.org/learn/coding-interview-prep/rosetta-code/convert-seconds-to-compound-duration)

2021-05-25 12_01_05-Learn Rosetta Code_ Convert seconds to compound duration _ freeCodeCamp org

### PR DESCRIPTION
**Pull request by PrashantSakre**
Checklist:

- [x] I have read [freeCodeCamp's contribution guidelines](https://contribute.freecodecamp.org).
- [x] My pull request has a descriptive title (not a vague title like `Update index.md`)
- [x] My pull request targets the `main` branch of freeCodeCamp.
- [x] I have tested these changes either locally on my machine, or GitPod.

Closes #42246

Hi as mentioned above typo I have fixed it and created the pull request.
and this my first time contribution to the freeCodeCamp and Thank you

### CODE REVIEW

**Comment by PrashantSakre** [comment]
Sorry about the first commit, I am too much excited

**Review by gikf — APPROVED** [review]
Looks good! :+1:

**Review by Nirajn2311 — APPROVED** [review]
LGTM 👍

**Comment by Nirajn2311** [comment]
Hi @PrashantSakre. Congrats on your first pull request (PR)! 🎉

Thank you for your contribution to the page! 👍
We are happy to accept these changes and look forward to future contributions. 📝

**Pull request merged**
