### PR TITLE
fix(client): corrected guide url logic for backend challenges and projects

### LINKED ISSUE #36596: [.dev] Get a hint links not working
Go to any [backend challenge](https://www.freecodecamp.dev/learn/information-security-and-quality-assurance/information-security-with-helmetjs/hide-potentially-dangerous-information-using-helmet.hidepoweredby)
Click the "get a hint" button

It redirects to https://www.freecodecamp.org/forum/search?q=/learn/information-security-and-quality-assurance/information-security-with-helmetjs/hide-potentially-dangerous-information-using-helmet.hidepoweredby%20in%3Atitle%20order%3Aviews

It should redirect to https://www.freecodecamp.org/forum/t/freecodecamp-challenge-guide-hide-potentially-dangerous-information-using-helmet-hidepoweredby/301580

So I'm not sure if it's something with the forum search query, or the link on the challenge.

It seems to be like this on all the backend challenges, looks like it works in all the other areas.

### PR DESCRIPTION
**Pull request by RandellDawson**
- [x] I have read [freeCodeCamp's contribution guidelines](https://github.com/freeCodeCamp/freeCodeCamp/blob/master/CONTRIBUTING.md).
- [x] My pull request has a descriptive title (not a vague title like `Update index.md`)
- [x] My pull request targets the `master` branch of freeCodeCamp.
- [x] None of my changes are plagiarized from another source without proper attribution.
- [x] All the files I changed are in the same world language (for example: only English changes, or only Chinese changes, etc.)
- [x] My changes do not use shortened URLs or affiliate links.

Closes #36596

The problem was the `Show.js` for the backend and `Show.js` for the projects were not using the challenge title and forumTopicId like the recent changes to `Show.js` for the classic challenges. 
 
These changes pass all existing tests with `npm run test`, but not sure if there needs to be any additional tests added or anything else in general.

### CODE REVIEW

**Review by moT01 — APPROVED** [review]
Tested this locally - looks good to me 🎉

**Comment by RandellDawson** [comment]
I should have made this a Draft.  I am making some more changes and will add the `ready for QA` when I am happy with it.

**Review by ojeytonwilliams — COMMENTED** [review]
I've checked this out locally and everything seems good.  EDIT: nevermind, I misunderstood how `propTypes` work: ignore what I said before.  All that I think needs to change is that `forumTopicId: PropTypes.number` should appear in `propTypes.js`

**Comment by RandellDawson** [comment]
@ojeytonwilliams Are you thinking I should add the following:
```js
  forumTopicIr: PropTypes.number
```

after this line https://github.com/freeCodeCamp/freeCodeCamp/blob/72d0525d5f23ae985a6492a8228299cdfac9398f/client/src/redux/propTypes.js#L57?

**Comment by ojeytonwilliams** [comment]
I believe the propTypes need to be in alphabetical order, but, yeah, that's where it goes.

**Comment by RandellDawson** [comment]
Most of them are not already in alphabetical order.  Should I correct that while I am in there?

**Review by ojeytonwilliams — APPROVED** [review]
Thanks, @RandellDawson LGTM.

**Comment by ojeytonwilliams** [comment]
@raisedadead I think this is good to go.

**Comment by raisedadead** [comment]
Thanks, I had thrown the original code in a hurry and it was a mess to be honest. I will clean this up a little bit before landing on master.

**Comment by RandellDawson** [comment]
@raisedadead What can I do to clean it up for you?

**Comment by raisedadead** [comment]
> @raisedadead What can I do to clean it up for you?

I would love some tests, for this. Also the utils file seems to be doing a bit of repeated logic. I would also like to put those URLs behind env variables instead of the current way.

**Comment by raisedadead** [comment]
Hi Randell, I have merged this PR into another https://github.com/freeCodeCamp/freeCodeCamp/pull/36625 which is in the works and touches the same areas for creating a forum URL.

**Pull request merged**
