### PR TITLE
feat: re-enable rwd tests

### PR DESCRIPTION
**Pull request by naomi-lgbt**
Checklist:

- [X] I have read [freeCodeCamp's contribution guidelines](https://contribute.freecodecamp.org).
- [X] My pull request has a descriptive title (not a vague title like `Update index.md`)
- [X] My pull request targets the `main` branch of freeCodeCamp.
- [X] I have tested these changes either locally on my machine, or GitPod.

Closes #XXXXX

This enables the superblock order + meta testing for the Responsive Web Design.

Blocked until #44459 is in.

### CODE REVIEW

**Review by ojeytonwilliams — DISMISSED** [review]
LGTM pending marker practice project going in.

**Comment by nhcarrigan** [comment]
This... should be failing, at the moment. 🤔

**Review by ojeytonwilliams — DISMISSED** [review]
LGTM :+1: 

For the benefit of anyone that doesn't get (like I didn't) why the upcoming changes are passing despite the marker project not being in: that superBlock is not built unless `SHOW_NEW_CURRICULUM` is true, and that's not set for those tests.

**Comment by moT01** [comment]
Hope nobody minds - I fixed conflicts on this using the github UI

**Comment by ojeytonwilliams** [comment]
Closed - changes already in main

**Pull request closed without merging**
