### PR TITLE
feat(euler-problem): Add Test and solution for euler problem 9

### PR DESCRIPTION
**Pull request by AungMyoKyaw**
#### Pre-Submission Checklist

- [x] Your pull request targets the `staging` branch of freeCodeCamp.
- [x] Branch starts with either `fix/`, `feature/`, or `translate/` (e.g. `fix/signin-issue`)
- [x] You have only one commit (if not, [squash](http://forum.freecodecamp.org/t/how-to-squash-multiple-commits-into-one-with-git/13231) them into one commit).
- [ ] All new and existing tests pass the command `npm test`. Use `git commit --amend` to amend any fixes.

#### Type of Change

- [ ] Small bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds new functionality)
- [ ] Breaking change (fix or feature that would change existing functionality)
- [ ] Add new translation (feature adding new translations)

#### Checklist:

- [x] Tested changes locally.
- [ ] Addressed currently open issue (replace XXXXX with an issue no in next line)

Closes #XXXXX

### CODE REVIEW

**Comment by alvinkl** [comment]
Hi @AungMyoKyaw, 
The solution you included was fast and working well 👍 ,
but can you add more assertions, maybe like`specialPythagoreanTriplet(n)`;
and test multiple `n` value, so the user won't just cheat and return the value.
Thank you.

**Comment by raisedadead** [comment]
@QuincyLarson I am not sure (for my lack of expertise on the topic) what this needs for a QA? Are we able to either merge or close this?

**Comment by scissorsneedfoodtoo** [comment]
Hi @AungMyoKyaw, thank you very much for including a solution. Everything works well!

However, like @alvinkl said, perhaps it would be best to modify this submission a bit. Since your submission almost there, I hope you don't mind if I suggest some additions to help get it merged.

For the tests, how about adding a couple more?:

`"assert.strictEqual(specialPythagoreanTriplet(1000), 31875000, 'message: <code>specialPythagoreanTriplet(1000)</code> should return 31875000.');", "assert.strictEqual(specialPythagoreanTriplet(24), 480, 'message: <code>specialPythagoreanTriplet(24)</code> should return 480.');", 
"assert.strictEqual(specialPythagoreanTriplet(120), 49920, 'message: <code>specialPythagoreanTriplet(120)</code> should return 49920.');"`

Then you can update your solution a bit:

`"const specialPythagoreanTriplet = (n)=>{\n let sumOfabc = n;\n let a,b,c;\n for(a = 1; a<=sumOfabc/3; a++){\n for(b = a+1; b<=sumOfabc/2; b++){\n c = Math.sqrt(a*a+b*b);\n if((a+b+c) == sumOfabc){\n return a*b*c;\n }\n }\n }\n}"`

The challenge seed:

`"function specialPythagoreanTriplet(n) {",
        "  let sumOfabc = n;",
        "  // Good luck!",
        "  return true;",
        "}",
        "",
        "specialPythagoreanTriplet(1000);"`

And just add a space in the description here between, "...a + b + c = 1000" and the next sentence, "Find the product abc."

**Review by raisedadead — CHANGES_REQUESTED** [review]
Need changes as @scissorsneedfoodtoo suggests.

**Comment by AungMyoKyaw** [comment]
Hi @alvinkl , @raisedadead , @scissorsneedfoodtoo 
Sorry for my late reply
I am updating my pull request.

**Comment by scissorsneedfoodtoo** [comment]
@AungMyoKyaw, happy New Year! Thank you for taking the time to update your pull request.

I'm very sorry, in my last message I really should have used code blocks to show you the new tests for this challenge. Because I gave you one long string to copy and paste, your updated challenges work but are hard to read for future maintainers. 

Would you mind just making a couple of quick changes and submitting your pull request one more time? 

We need to format the tests array like this:

```
        "assert.strictEqual(specialPythagoreanTriplet(1000), 31875000, 'message: <code>specialPythagoreanTriplet(1000)</code> should return 31875000.');",
        "assert.strictEqual(specialPythagoreanTriplet(24), 480, 'message: <code>specialPythagoreanTriplet(24)</code> should return 480.');",
        "assert.strictEqual(specialPythagoreanTriplet(120), 49920, 'message: <code>specialPythagoreanTriplet(120)</code> should return 49920.');"
```

Also, the description is missing a space between the last two sentences. Here's the fixed description:

```
        "A Pythagorean triplet is a set of three natural numbers, a < b < c, for which,",
        " a2 + b2 = c2",
        "For example, 32 + 42 = 9 + 16 = 25 = 52.",
        "There exists exactly one Pythagorean triplet for which a + b + c = 1000. Find the product abc."
```

Sorry again! After these small changes everything should be good to go.

**Review by raisedadead — APPROVED** [review]

**Comment by QuincyLarson** [comment]
@AungMyoKyaw Thanks for updating this challenge! And thanks to @scissorsneedfoodtoo, @raisedadead and @Ethan-Arrowood for helping move this along through the long QA process :)

**Pull request merged**
