### PR TITLE
chore(curriculum): remove non-existing data structures challenges from meta

### PR DESCRIPTION
**Pull request by moT01**
I'm not convinced these challenges ever existed. I couldn't find any record of them - there's no markdown file for them, I didn't see anything in the commit history.

Checklist:

- [x] I have read and followed the [contribution guidelines](https://contribute.freecodecamp.org).
- [x] I have read and followed the [how to open a pull request guide](https://contribute.freecodecamp.org/#/how-to-open-a-pull-request).
- [x] My pull request targets the `main` branch of freeCodeCamp.
- [x] I have tested these changes either locally on my machine, or GitPod.

Closes #XXXXX

### CODE REVIEW

**Comment by ojeytonwilliams** [comment]
It's surprising that nothing breaks because of this. Presumably the point is the order is something like 1, 2, 5, 6... so even though the numbers are wrong, the order is correct.

Anyways, could you remove these challenges entirely? They appear in a couple of other places (the seed script and completed-challenges.json).

**Comment by moT01** [comment]
> could you remove these challenges entirely?

I can, but it is necessary? Presumably, they once existed and people could have completed them - so they would still exist in their completedChallenges. Which is what those are mocking.

**Review by ojeytonwilliams — APPROVED** [review]
It's a fair point about the mocks.

I don't think we should be seeding a user with non-existent challenges, though. We should probably remove them from the db at some point. That and make sure we never delete challenges again.

**Review by naomi-lgbt — APPROVED** [review]
Schrodinger's challenges

**Pull request merged**
