### PR TITLE
Remove use of for from radio button lesson

### LINKED ISSUE #16458: Basic HTML and HTML5, input elements - incomplete description of the "for" attribute
#### Challenge Name

[Basic HTML and HTML5: Create a Text Field](https://beta.freecodecamp.org/en/challenges/basic-html-and-html5/create-a-text-field)
[Basic HTML and HTML5: Create a Set of Radio Buttons](https://beta.freecodecamp.org/en/challenges/basic-html-and-html5/create-a-set-of-radio-buttons)
[Basic HTML and HTML5: Create a Set of Checkboxes](https://beta.freecodecamp.org/en/challenges/basic-html-and-html5/create-a-set-of-checkboxes)

#### Issue Description

This is a follow up to issue #15946 where it was suggested that the lesson [Basic HTML and HTML5: Create a Set of Radio Buttons](https://beta.freecodecamp.org/en/challenges/basic-html-and-html5/create-a-set-of-radio-buttons) should reflect the best practice guidelines from [the Mozilla documentation](https://developer.mozilla.org/en-US/docs/Learn/HTML/Forms/How_to_structure_an_HTML_form#The_%3Clabel%3E_element).

The issue was closed and now the lesson includes the following:
>It is considered best practice to set the for attribute for assistive technologies to be able to link the relationship between the label and the child elements such as an input in this case.

Yet:
1. If the goal is teaching best practice, the lesson should explain that the `label` element's `for` value has to match the `input` element's `id` value as explained in [the linked Mozilla documentation page](https://developer.mozilla.org/en-US/docs/Learn/HTML/Forms/How_to_structure_an_HTML_form#The_%3Clabel%3E_element).
2. The same issue applies to the next lesson: [Basic HTML and HTML5: Create a Set of Checkboxes](https://beta.freecodecamp.org/en/challenges/basic-html-and-html5/create-a-set-of-checkboxes).
3. This advice applies not only to clickable `input` elements, the Mozilla page actually discusses `input type="text"` which is covered in a previous lesson: [Basic HTML and HTML5: Create a Text Field](https://beta.freecodecamp.org/en/challenges/basic-html-and-html5/create-a-text-field).
4. However, keep in mind that this topic is actually covered in its own lesson under: [Applied Accessibility: Improve Form Field Accessibility with the label Element](https://beta.freecodecamp.org/en/challenges/applied-accessibility/improve-form-field-accessibility-with-the-label-element)

### PR DESCRIPTION
**Pull request by elbaumpj**
#### Pre-Submission Checklist

- [x] Your pull request targets the `staging` branch of freeCodeCamp.
- [x] Branch starts with either `fix/`, `feature/`, or `translate/` (e.g. `fix/signin-issue`)
- [x] You have only one commit (if not, [squash](http://forum.freecodecamp.org/t/how-to-squash-multiple-commits-into-one-with-git/13231) them into one commit).
- [x] All new and existing tests pass the command `npm test`. Use `git commit --amend` to amend any fixes.

#### Type of Change

- [x] Small bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds new functionality)
- [ ] Breaking change (fix or feature that would change existing functionality)
- [ ] Add new translation (feature adding new translations)

#### Checklist:

- [x] Tested changes locally.
- [x] Addressed currently open issue (replace XXXXX with an issue no in next line)

Closes #16458 

#### Description

This change was made in order to address the above issue. After consensus, the decision was made to move any mention of `for` out of the radio button lesson in the Basic HTML section. I also added a reference to the radio button lesson and fuller explanation of `for`'s use in accessibility in the Form Field Accessibility lesson.

### CODE REVIEW

**Comment by mstellaluna** [comment]
I am currently working on this PR

**Comment by mstellaluna** [comment]
@elbaumpj Hello. There are two minor issues.
1) In the sentence "Another way to achieve this is by using the for attribute as explained in this lesson." for the "Improve Form Field Accessibility with the label Element" lesson, the for keyword isn't highlighted like the others.

2) In the sentence "Each of your radio buttons should be nested within its own label element. Wrapping an input element inside of a label element makes the lable text clickable." in the challenge Create a Set of Radio Buttons, there label is misspelled.

**Review by mstellaluna — DISMISSED** [review]
Formatting and Spelling issue(s), needs to be fixed.

**Comment by elbaumpj** [comment]
hey @mstellaluna thanks for the feedback. I made the changes you requested but am not quite sure what happened with squashing my previous commits. I apologize for the mess up there.

**Comment by elbaumpj** [comment]
@mstellaluna thanks for your feedback, I made the changes you requested but had some trouble with squashing all of the commits to one. Let me know if there's anything else I should change or if there's other feedback.

**Comment by elbaumpj** [comment]
Sorry for all of the updates. I made a mess of trying to make the requested changes and it took me a while to figure out how to properly revert and submit the changes, hence all of the updates.

**Comment by raisedadead** [comment]
@elbaumpj 

Thanks for working on this.

I have resolved some merge conflicts. I would recommend that you do the below on you local machine in the below order:

```
git checkout staging
git branch -D fix/radio-button
git fetch --all --prune
git reset --hard upstream/staging
git push origin staging --force
```

This will bring your local copy to proper sync with the main repo. It will also update the staging branch of your fork on GitHub to main repo.

If further change is needed you can do a checkout of this PR's branch and you should be good to go.

**Comment by elbaumpj** [comment]
thanks @raisedadead - really appreciate your help and patience!

**Comment by raisedadead** [comment]
@mstellaluna @elbaumpj Can you guys do a sanity check on the files here https://github.com/freeCodeCamp/freeCodeCamp/pull/16821/files

You should be able to see the diff, and make a note if I accidentally changed anything?

**Comment by elbaumpj** [comment]
@raisedadead that looks like what I have locally, so all's well. 

I did notice that line 1709 is missing a period at the end of the sentence. I checked the current live site just to make sure I hadn't done that by accident, and it's missing there too (see attached). We might look at changing that. Otherwise, LGTM. 
fcc-radio

**Comment by raisedadead** [comment]
> I checked the current live site just to make sure I hadn't done that by accident, and it's missing there too (see attached).

This means it was pre-existing.

Sure please go ahead and follow the steps from my earlier comment, i.e:

```
git checkout staging
git branch -D fix/radio-button
git fetch --all --prune
git reset --hard upstream/staging
git push origin staging --force
```

and then for this PR

```
git checkout fix/radio-button
MAKE YOUR CHANGES TO THE FILE
git commit --amend --no-edit
git push origin fix/radio-button
```

by using amend commit you will avoid making a new commit.
If you are still stuck you know where to find us.

Happy fixing

**Comment by elbaumpj** [comment]
@raisedadead quick question...I'm about ready to push, but the push failed because it says my local is behind the remote. should I pull first or use `git push --force`?

**Comment by raisedadead** [comment]
You should `git push --force`. The message that you see, is because you made changes to the git commit history and the remote (GitHub) is crying about it. This is fine.

**Comment by elbaumpj** [comment]
I made the changes @mstellaluna requested but didn't remove text, aside from what I had initially done to refactor the use of `for`. I'm not quite sure why the changes are gone. In any case, unless someone has further comments I believe this PR is ready.

**Review by raisedadead — APPROVED** [review]

**Comment by raisedadead** [comment]
The removed lines are a result of a rebase that I did to resolve the merge conflict, which is fine and intended.

Thanks for working on this @elbaumpj !

**Comment by mstellaluna** [comment]
@raisedadead thanks for checking !!!! @elbaumpj Thanks for your contribution ! Happy Coding !

**Pull request merged**
