### PR TITLE
chore: remove `Types` suffixes from `client/src/redux/prop-types.ts`

### PR DESCRIPTION
**Pull request by vishwasnavadak**
Checklist:

- [x] I have read [freeCodeCamp's contribution guidelines](https://contribute.freecodecamp.org).
- [x] My pull request has a descriptive title (not a vague title like `Update index.md`)
- [x] My pull request targets the `main` branch of freeCodeCamp.
- [x] I have tested these changes either locally on my machine, or GitPod.

This PR is based on the discussion from the thread: https://github.com/freeCodeCamp/freeCodeCamp/pull/43262#issuecomment-950830058

### CODE REVIEW

**Review by ojeytonwilliams — CHANGES_REQUESTED** [review]
Thanks @vishwasnavadak, this is much nicer!  Could you rename the remaining PropTypes (`User`, `ChallengeNode` and so on) to `OriginalNamePropType`?  There's a naming clash between the `User` type and the `User` PropType.

Also, I'm just updating the lint rules to forbid `type ThingType`, so if use PropType as a suffix we guarantee there will be no other clashes.

**Comment by vishwasnavadak** [comment]
Done @ojeytonwilliams ! One thing I noticed while I was adding `PropType`  suffix is that those PropTypes are not imported anywhere. Should we get rid of them for good? 

Here is the list of them:
1. FilePropType
2. MarkdownRemarkPropType
3. AllMarkdownRemarkPropType
4. UserPropType
5. CurrentCertsPropType
6. StepsPropType

**Review by ojeytonwilliams — APPROVED** [review]
LGTM :+1: 

I removed as many redundant proptypes as I could in https://github.com/freeCodeCamp/freeCodeCamp/pull/44110, so I think this PR's good as is.  Once this is merged, I'll double check my PR to make sure all the ones you highlighted have been dealt with.

Thanks again!

**Review by ShaunSHamilton — APPROVED** [review]
This LGTM 👍

**Comment by ShaunSHamilton** [comment]
Thank you, for your contribution to the page! 👍
We are happy to accept these changes, and look forward to future contributions. 🎉

**Pull request merged**
