### PR TITLE
fix(curriculum): Add missing solutions for interview prep algorithm challenges

### PR DESCRIPTION
**Pull request by TyMick**
Checklist:

- [x] I have read [freeCodeCamp's contribution guidelines](https://contribute.freecodecamp.org).
- [x] My pull request has a descriptive title (not a vague title like `Update index.md`)
- [x] My pull request targets the `master` branch of freeCodeCamp.
- [x] All the files I changed are in the same world language, for example: only English changes, or only Chinese changes, etc.

[Implement Quick Sort](https://www.freecodecamp.org/learn/coding-interview-prep/algorithms/implement-quick-sort) and [Implement Merge Sort](https://www.freecodecamp.org/learn/coding-interview-prep/algorithms/implement-merge-sort) were missing solutions in their English source files, so I added the ones I wrote.

### CODE REVIEW

**Comment by moT01** [comment]
I have blocked this for now. See the [pinned code freeze issue](https://github.com/freeCodeCamp/freeCodeCamp/issues/38308)

**Comment by raisedadead** [comment]
Limitations removed on Coding Interview Prep Challenges.

**Review by tinktink1 — APPROVED** [review]
I really liked your solution for the problem. The formatting is good and the code is clean. I have done some tests and this looks like it should work.

**Review by moT01 — APPROVED** [review]
LGTM @tywmick 🎉 Thanks for contributing to freeCodeCamp 🎉 

I have added these solutions to the guide 😄

**Pull request merged**
