### PR TITLE
chore: misc updates and housekeeping

### PR DESCRIPTION
**Pull request by raisedadead**
Commits on this PR are meant to do some cleanup, "nice to have" like changes. 

@ojeytonwilliams Feel free to merge at any point though. Do not want to overdo it.

### CODE REVIEW

**Comment by ojeytonwilliams** [comment]
@raisedadead longer term is the plan to deploy Docker containers, even if we don't recommend using it in development?

**Comment by raisedadead** [comment]
> longer term is the plan to deploy Docker containers, even if we don't recommend using it in development?

Yes, you are correct. And since that is deployment/packaging and most likely will not make into this repo itself

**Review by ojeytonwilliams — CHANGES_REQUESTED** [review]

**Review by ojeytonwilliams — DISMISSED** [review]
LGTM :+1:

**Comment by ojeytonwilliams** [comment]
I just rebased in the change, so this can be rebased and merged once it's green.

**Review by ojeytonwilliams — APPROVED** [review]
LGTM :+1:

**Pull request merged**
