### PR TITLE
feat: filter challenges by tags

### LINKED ISSUE #48800: Tag System
Creating a new issue specifically to track discussion for the tag system - spinning off of #48502.

This also follows up on #47478

### PR DESCRIPTION
**Pull request by Canopius**
Checklist:

- [x] I have read and followed the [contribution guidelines](https://contribute.freecodecamp.org).
- [x] I have read and followed the [how to open a pull request guide](https://contribute.freecodecamp.org/#/how-to-open-a-pull-request).
- [x] My pull request targets the `main` branch of freeCodeCamp.
- [x] I have tested these changes either locally on my machine, or GitPod.

Closes #48800 

This still has some work to do, however the majority of the features are in.

image

* Adds the Topics drop down
* When a topic is selected the option is removed from the list and a tag created
* When a tag is clicked, it is removed and the option returned to the dropdown
* The tags are added to each challenge in the challenge md file under a new line `tags: tag1,tag2,tag3`
* When multiple tags are selected the challenges are shown if they match all tags

To do:
* I18n
* Add meaningfull tags to each challenge

### CODE REVIEW

**Comment by ahmadabdolsaheb** [comment]
Solid work here. Here are a few UX pointers:(
1) The spacing(margin/paddin) in the dropdown button, dropdown items, and the tags should be similar to other buttons( e.x. resume project button)
2) the topic-filter-select  should collapse once a choice has been made.
3) X in the tag should be replaced with an svg. Look for font awesome alternatives if one is not found in our codebase.

**Review by ojeytonwilliams — CHANGES_REQUESTED** [review]
Hi @Canopius, the functionality is great, but I think it could use some refactoring.  Avoiding mutations where possible and simplifying the flow of data should make this much easier to maintain.

I'll explain a little more below, but the data flow should just be

`props.challengesWithCompleted -> topics -> useState(topics)`

then rendering just depends on `topics` and user input just affects if a single topic is 'active' or not.

Just to reiterate, the code works well as is, but I think it could be clearer.

**Comment by Canopius** [comment]
Thanks a bunch for the advice, I'll try and get this implemented over the next week.

**Comment by ojeytonwilliams** [comment]
No problem at all, @Canopius. Please reach out if anything is unclear or confusing and I'll be happy to help.

**Comment by bbsmooth** [comment]
Hey @Canopius, not sure if we've crossed paths before but if not then I'll let you know that I can be a bit of a squeaky wheel about accessibility :slightly_smiling_face:  I'll make note of some basic things that can be enhanced now. And then as this comes together I'll chime in when needed.

First thing, the Topics button is acting as a disclosure button (it controls the visibility of the Topics list). In order to help screen reader users understand this, we need to add the `aria-expanded` attribute to the button. When the list hidden, the button should have `aria-expanded="false"` and when the list is showing the button should have `aria-expanded="true"`.

**Comment by bbsmooth** [comment]
A second enhancement. When a filter is active, I'm assuming that the steps that are not part of the filter should also not be active (you can't click on them or Tab to them). In order to do this we need to do a few things:

- The `li` that wraps the link needs to have `aria-hidden="true"` added to it. This will prevent screen readers and other AT from recognizing the list item and thus they will only report the number of list items actually available in the filter.
- The link itself needs to be disabled. Usually you would disable an interactive item with the `disabled` attribute but that attribute doesn't work for links. The easiest way to disable a link is to remove the `href` attribute. (Not just make it empty, but completely remove the attribute from the tag.) That's what I would suggest we do here.

Along with the above we should also remove the hover styling for these disabled links.

**Comment by Sboonny** [comment]
Hi @Canopius, I am wondering how is the progress for this PR, and do you need help?

**Comment by Sembauke** [comment]
Hey @Canopius,

We have see that you have not been active in a long while. Therefore I will be closing this pull-request. Feel free to re-open when you are ready to revisit.

**Pull request closed without merging**
