### PR TITLE
Removed Rule 4 from Build a Personal Portfolio Webpage

### LINKED ISSUE #8125: Probably wrong rule in "Build a Personal Portfolio Webpage"
#### Challenge Name

Build a Personal Portfolio Webpage

#### Issue Description

One of the rules is "Choose your own tribute subject". This is probably accidentally copied from the tribute project's requirements.

### PR DESCRIPTION
**Pull request by ghost**
Removed Rule 4 from Build a Personal Portfolio Webpage as it was incorrect.
closes #8125

### CODE REVIEW

**Comment by raisedadead** [comment]
@theflametrooper Change the description to the correct issue closure. 
Secondly PR assignment is done to the reviewer only if necessary not the PR owner. :wink:

**Comment by theflametrooper** [comment]
@raisedadead Changed the description!

**Comment by raisedadead** [comment]
@theflametrooper 

Check `closes #8133` --> ????

**Comment by theflametrooper** [comment]
Oh lol sorry I just typed the wrong issue number.

**Comment by raisedadead** [comment]
#### :sparkles: :sparkles: **LGTM.** :sparkles: :sparkles: 

Thanks.

**Pull request merged**
