### PR TITLE
feat(curriculum): adding student database workshops to cert

### LINKED ISSUE #574: chore: add student database part 1 workshop to main repo
We are adding the entire relational database projects to the frontend cert. We are adding everything as is.

For this issue, add the Build a Student Database: Part 1 project to the main repo.

https://www.freecodecamp.org/learn/relational-database/learn-sql-by-building-a-student-database-part-1/build-a-student-database-part-1

make sure to keep the same ids

### LINKED ISSUE #575: chore: add student database part 2 workshop to main repo
We are adding the entire relational database projects to the frontend cert. We are adding everything as is.

For this issue, add the Build a Student Database: Part 2 project to the main repo.

https://www.freecodecamp.org/learn/relational-database/learn-sql-by-building-a-student-database-part-2/build-a-student-database-part-2

make sure to keep the same ids

### PR DESCRIPTION
**Pull request by jdwilkin4**
Checklist:

- [x] I have read and followed the [contribution guidelines](https://contribute.freecodecamp.org).
- [x] I have read and followed the [how to open a pull request guide](https://contribute.freecodecamp.org/how-to-open-a-pull-request/).
- [x] My pull request targets the `main` branch of freeCodeCamp.
- [x] I have tested these changes either locally on my machine, or GitPod.

Closes https://github.com/freeCodeCamp/CurriculumExpansion/issues/575
closes https://github.com/freeCodeCamp/CurriculumExpansion/issues/574

### CODE REVIEW

**Comment by ilenia-magoni** [comment]
maybe these two could be combined in a single block?

**Comment by jdwilkin4** [comment]
> maybe these two could be combined in a single block?

The original relational database curriculum is split into two blocks, so I vote we leave it as is since there is probably a reason why Tom structured it that way

**Comment by moT01** [comment]
Yea, keep them separate. I split it because it was really long. It's kinda neat, at the end of the first one, they save a dump of their DB - and then restore it on at the start of the second.

**Review by moT01 — APPROVED** [review]

**Comment by ilenia-magoni** [comment]
I meant having part 1 and part 2 being like step 1 and step 2 of the same block, not merging the two together completely, but if you say separate is better, let's keep it separate

**Review by Dario-DC — APPROVED** [review]
LGTM :+1:

**Pull request merged**
