### PR TITLE
fix(curriculum): error in asserting initial state of redux store

### LINKED ISSUE #45267: Error in asserting initial state of Redux Store
## Affected page

https://www.freecodecamp.org/learn/front-end-development-libraries/redux/write-a-counter-with-redux
## Your code

```js
const INCREMENT = 'INCREMENT';
const DECREMENT = 'DECREMENT';

const counterReducer = (state = 0, action) => {
  switch(action.type) {
    case INCREMENT:
      return state + 1;
    case DECREMENT:
      return state - 1;
    default:
      return state;
  }
};

const incAction = () => {
  return {
    type: INCREMENT
  }
};

const decAction = () => {
  return {
    type: DECREMENT
  }
};

const store = Redux.createStore(counterReducer);

// TESTS:
store.dispatch(incAction());
console.log(store.getState()); // 1
store.dispatch(incAction()); 
console.log(store.getState()); // 2
store.dispatch(decAction());
console.log(store.getState()); // 1
```

## Expected behavior

This should be accepted as a correct answer, as it solves the challenge.
## System

- Device: PC
- OS: Windows 10
- Browser: Firefox
- Version: 97.0.1

## Additional context

The problem arises if the user tries to test their Redux store functionality

After checking the source code of the challenge,
the problem seems to be the method used to check if user initiated state correctly or not
```js
assert(store.getState() === 0);
```
found in `/curriculum/challenges/english/03-front-end-development-libraries/redux/write-a-counter-with-redux.md`

This is resulting in a false assert because the user has modified their state (with Tests)

I don't know of a way to assert that the user initialized state other than the way mentioned above

Maybe add a note that the user should remove their tests before checking their answer?

Sorry if this was mentioned before, but I didn't find it so decided to open the issue.

### PR DESCRIPTION
**Pull request by raditotev**
Checklist:

- [x] I have read [freeCodeCamp's contribution guidelines](https://contribute.freecodecamp.org).
- [x] My pull request has a descriptive title (not a vague title like `Update index.md`)
- [x] My pull request targets the `main` branch of freeCodeCamp.
- [x] I have tested these changes either locally on my machine, or GitPod.

Closes #45267

### CODE REVIEW

**Review by naomi-lgbt — APPROVED** [review]
Looks good to me!

**Review by gikf — APPROVED** [review]
LGTM :+1:

**Comment by gikf** [comment]
Hi @raditotev. Congrats on your first pull request (PR)! 🎉

Thank you for your contribution to the page! 👍
We are happy to accept these changes and look forward to future contributions. 📝

**Comment by raditotev** [comment]
Thanks @gikf. My pleasure. More contributions coming up 😃

**Pull request merged**
