### PR TITLE
fix(challenges): Edit Description and Add Solution for Project Euler 45

### PR DESCRIPTION
**Pull request by scissorsneedfoodtoo**
#### Pre-Submission Checklist

- [x] Your pull request targets the `staging` branch of freeCodeCamp.
- [x] Branch starts with either `fix/`, `feature/`, or `translate/` (e.g. `fix/signin-issue`)
- [x] You have only one commit (if not, [squash](http://forum.freecodecamp.org/t/how-to-squash-multiple-commits-into-one-with-git/13231) them into one commit).
- [x] All new and existing tests pass the command `npm test`. Use `git commit --amend` to amend any fixes.

#### Type of Change

- [x] Small bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds new functionality)
- [ ] Breaking change (fix or feature that would change existing functionality)
- [ ] Add new translation (feature adding new translations)

#### Checklist:

- [x] Tested changes locally.
- [ ] Addressed currently open issue (replace XXXXX with an issue no in next line)

Closes #XXXXX

#### Description

Updated the problem description with an inline CSS grid, `<sup>`, and
`<var>` tags. Also added a solution that user @elliotjz contributed
to the fCC Arcade Mode.

BREAKING CHANGE: None

Here's a solution for QA:

```
function triPentaHexa(n) {
  function triangular(num) {
    return (num * (num + 1)) / 2;
  }

  function isPentagonal(num) {
    // Formula found by completing the square and
    // solving for n.
    const n = (Math.sqrt((24 * num) + 1) + 1) / 6;
    return n % 1 === 0;
  }

  function isHexagonal(num) {
    // Formula found by completing the square and
    // solving for n.
    const n = Math.sqrt(0.5 * (num + (1 / 8))) + 0.25;
    return n % 1 === 0;
  }

  let iTri = n;
  let tri;
  let found = false;
  while (!found) {
    iTri++;
    tri = triangular(iTri);
    if (isPentagonal(tri) && isHexagonal(tri)) {
      found = true;
    }
  }
  return tri;
}
```

### CODE REVIEW

**Comment by mstellaluna** [comment]
@raisedadead of course, I will take a look at this tomorrow 😄

**Comment by mstellaluna** [comment]
Currently working on this PR

**Review by mstellaluna — APPROVED** [review]
LGTM

**Comment by mstellaluna** [comment]
@scissorsneedfoodtoo Hello, I will be approving this PR. Thank you for your contribution. Happy Coding !

**Comment by scissorsneedfoodtoo** [comment]
@mstellaluna, thank you for taking the time to QA and merge this!

**Pull request merged**
