### PR TITLE
fixed DO#, renamed to C#, replaced "C #" with "C#"

### PR DESCRIPTION
**Pull request by saeg2k3**
C# is a product name and must not be translated.
replaced "C #" with the correct name "C#"

- [x] I have read [freeCodeCamp's contribution guidelines](https://github.com/freeCodeCamp/freeCodeCamp/blob/master/CONTRIBUTING.md).
- [x] My pull request has a descriptive title (not a vague title like `Update index.md`)
- [x] My pull request targets the `master` branch of freeCodeCamp.
- [x] None of my changes are plagiarized from another source without proper attribution.
- [x] My article does not contain shortened URLs or affiliate links.

If your pull request closes a GitHub issue, replace the XXXXX below with the issue number.

Closes #XXXXX

### CODE REVIEW

**Comment by saeg2k3** [comment]
fixed title and c# product name

**Comment by RandellDawson** [comment]
Did you mean to close this PR?

**Comment by saeg2k3** [comment]
Hi I'm new on this and closed ir accidentally.

Best regards
Sergio E

**Comment by RandellDawson** [comment]
Just making sure.

**Comment by RandellDawson** [comment]
Closed and Reopened this PR to attempt to resolve a specific Travis build failure.

**Comment by Drithyl** [comment]
Shouldn't this be closed or merged?

**Comment by RandellDawson** [comment]
@Drithyl Didn't you ask the same question on another PR.  The answer is the same "Yes".

**Comment by Drithyl** [comment]
@RandellDawson I apologize, I'm a beginner and have been looking through issues and PRs to try and contribute. If the answer is yes, who should do it? Or why isn't it done? The last comment before mine is 5 months old.

**Comment by RandellDawson** [comment]
We have 2200+ other PRs we still have not reviewed.  It just takes time as we are all volunteers.

**Review by RandellDawson — APPROVED** [review]

**Comment by RandellDawson** [comment]
Thank you for your contribution to the page! 👍
We're happy to accept these changes, and look forward to future contributions. 🎉

**Pull request merged**
