### PR TITLE
refactor(client): make ShowCertification functional

### PR DESCRIPTION
**Pull request by ShaunSHamilton**
Checklist:

- [x] I have read [freeCodeCamp's contribution guidelines](https://contribute.freecodecamp.org).
- [x] My pull request has a descriptive title (not a vague title like `Update index.md`)
- [x] My pull request targets the `master` branch of freeCodeCamp.
- [x] All the files I changed are in the same world language, for example: only English changes, or only Chinese changes, etc.

In part with #39695

### CODE REVIEW

**Comment by ahmadabdolsaheb** [comment]
Thanks for the refactor, @Sky020.  The close button does not seem to be closing the donation section and that issue seems to be originated from the second useEffect.

The easiest way to test it would be to  replace `  {isDonationSubmitted && donationCloseBtn}` with  ` {donationCloseBtn}` and see the close button's behavior.

**Comment by Sky020** [comment]
@ahmadabdolsaheb Excellent catch! Sorry about that, I completely forgot to test that side, and it was a very small typo on my part.

**Comment by ahmadabdolsaheb** [comment]
Thanks for your patience, @Sky020. I would re-review and merge as soon as you get the conflict sorted out.

**Comment by Sky020** [comment]
@ahmadabdolsaheb Thank you. I had not even realized there were conflicts on this.

Should be sorted, now.

**Review by ahmaxed — APPROVED** [review]

**Review by ojeytonwilliams — APPROVED** [review]
LGTM :+1:

**Pull request merged**
