### PR TITLE
Added solution to challenge

### PR DESCRIPTION
**Pull request by GoldenCorgi**
- [x] I have read [freeCodeCamp's contribution guidelines](https://github.com/freeCodeCamp/freeCodeCamp/blob/master/CONTRIBUTING.md).
- [x] My pull request has a descriptive title (not a vague title like `Update index.md`)
- [x] My pull request targets the `master` branch of freeCodeCamp.
- [x] None of my changes are plagiarized from another source without proper attribution.
- [x] My article does not contain shortened URLs or affiliate links.

If your pull request closes a GitHub issue, replace the XXXXX below with the issue number.

Closes #XXXXX

### CODE REVIEW

**Comment by nikrb** [comment]
Deleted PR because user deleted the fork used to create PR

**Comment by RandellDawson** [comment]
You can still merge PRs without a repo if the content looks good.

**Comment by nikrb** [comment]
apologies, I saw you closed others so thought it was standard procedure. I'll test it locally. @RandellDawson I don't seem to be able to re-open it, greyed out.

**Comment by RandellDawson** [comment]
Nope.  Once you close a PR which has an unknown repo, you can not reopen it.

**Pull request closed without merging**
