### PR TITLE
feat: add bio component to profile page

### LINKED ISSUE #48234: Help with the Portfolio redesign
### Is your feature request related to a problem? Please describe.

The redesign of the Profile is way overdue. Here is the proposal for organizing the personal info section of the Profile and improving its aesthetics.

Design file:

https://www.figma.com/file/4M7uEe9kH8hgZdB07lBvj9/Untitled-(Copy)?type=design&node-id=0-1&mode=design&t=xDY6TLQqE5Ez0LF3-0

### Describe the solution you'd like

We could use icons for location and joined date as Tom suggested.
Let us know if you have other considerations before we move to the implementation.

### Describe alternatives you've considered

.

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by shootermv**
`bio` section of the profile page
desktop:
image
mobile:
image

- [x] I have read and followed the [contribution guidelines](https://contribute.freecodecamp.org).
- [x] I have read and followed the [how to open a pull request guide](https://contribute.freecodecamp.org/#/how-to-open-a-pull-request).
- [x] My pull request targets the `main` branch of freeCodeCamp.
- [x] I have tested these changes either locally on my machine, or GitPod.

related to #48234

### CODE REVIEW

**Comment by ahmaxed** [comment]
Thanks for the pr and sorry for the confusion. those three dots (<figure>) are the current socials, and the image should be on the left.

**Comment by shootermv** [comment]
> Thanks for the pr and sorry for the confusion. those three dots (
> 
> ) are the current socials, and the image should be on the left. Also I would be great if you could look into the failing tests.

as far as i can see - those icons appear when user adds one pf the fields - 
how is it possible to access `settings` in dev mode to add for example - github account?

**Comment by shootermv** [comment]
> [ahmaxed](/ahmaxed)

here is some problem with those icons: they only shown when user has some data at those fields,
currently development user has no data - so the no icons will display...
does this means - i should create some PR with modified `seed` scripts in a way the development user will have for example -github account?

**Comment by Sembauke** [comment]
> here is some problem with those icons: they only shown when user has some data at those fields, currently development user has no data - so the no icons will display... does this means - i should create some PR with modified `seed` scripts in a way the development user will have for example -github account?

Hey @shootermv,
It is possible to add your own info to the developer account by going to the settings. There you should see a couple of fields were you can put your GitHub link etc..

**Comment by Sembauke** [comment]
Hey @shootermv,

A couple of things:

1. We should only add new classes when absolutely necessary, meaning the colour classes are redundant as we use predefined colours. You can view these colours in the developer console:
image
or in the `global.css` file. We do this to prevent duplication and to make sure that colours are both fit for light and dark theme.
2. The new component should have a width that correlates to the others. Meaning the bio components seems to have a larger width than say, the points component.

Again, thank you for working on this. If you have any questions let me know here.

**Review by Sembauke — CHANGES_REQUESTED** [review]
view comment above.

**Review by Sembauke — APPROVED** [review]

**Review by ahmaxed — APPROVED** [review]

**Pull request merged**
