### PR TITLE
feat(tools): introduce knip to find unused files, dependencies & exports

### PR DESCRIPTION
**Pull request by webpro**
_(edit: exportman was renamed to knip during the lifetime of this PR)_

Checklist:

- [ ] I have read [freeCodeCamp's contribution guidelines](https://contribute.freecodecamp.org).
- [x] My pull request has a descriptive title (not a vague title like `Update index.md`)
- [x] My pull request targets the `main` branch of freeCodeCamp.
- [x] I have tested these changes either locally on my machine, or GitPod.

Apologies for not opening an issue first, hope you don't mind this rather random pull request. I'm working on a new project and when looking for a proper workload to test it, I came across this rather large project. This is great, because [exportman](https://github.com/webpro/exportman) targets projects like this. Please allow me to just go ahead and put the output of this command right here to see what I'm talking about.

With a bit of configuration (`config/exportman/client.json`) it's possible to find unused files and exports:

```
❯ npx exportman --config config/exportman/client.json
--- UNUSED FILES (10)
client/src/assets/icons/donate-with-PayPal.tsx
client/src/assets/icons/intro-information.tsx
client/src/components/Donation/duration-amount-options.tsx
client/src/components/Header/components/user-state.tsx
client/src/components/helpers/form/block-save-wrapper.tsx
client/src/components/search/searchPage/empty-search.tsx
client/src/components/search/searchPage/no-results.tsx
client/src/components/search/searchPage/search-page-hits.tsx
client/src/declarations.d.ts
client/src/html.tsx
--- UNUSED EXPORTS (46)
DonationOptionsText              client/src/components/Donation/donation-text-components.tsx
DonationSupportText              client/src/components/Donation/donation-text-components.tsx
PaypalButton                     client/src/components/Donation/paypal-button.tsx
sagas                            client/src/components/Flash/redux/index.ts
NavLinks                         client/src/components/Header/components/nav-links.tsx
searchIndexNameSelector          client/src/components/search/redux/index.js
updateSearchIndexName            client/src/components/search/redux/index.js
SearchBarOptimized               client/src/components/search/searchBar/search-bar-optimized.tsx
SearchBar                        client/src/components/search/searchBar/search-bar.tsx
CertificationSettings            client/src/components/settings/certification.js
ns                               client/src/redux/action-types.js
sessionMetaSelector              client/src/redux/index.js
updateCurrentChallengeId         client/src/redux/index.js
defaultFetchState                client/src/redux/index.js
CurrentCertsPropType             client/src/redux/prop-types.ts
UserPropType                     client/src/redux/prop-types.ts
saveChallengeSaga                client/src/redux/save-challenge-saga.js
defaultDonationFormState         client/src/redux/types.ts
defaultFetchState                client/src/redux/types.ts
CompletionModalInner             client/src/templates/Challenges/components/completion-modal.tsx
getCompletedPercent              client/src/templates/Challenges/components/completion-modal.tsx
HelpModal                        client/src/templates/Challenges/components/help-modal.tsx
ShortcutsModal                   client/src/templates/Challenges/components/shortcuts-modal.tsx
VideoModal                       client/src/templates/Challenges/components/video-modal.tsx
ToolPanel                        client/src/templates/Challenges/projects/tool-panel.tsx
replaceNBSP                      client/src/templates/Challenges/rechallenge/transformers.js
testJS$JSX                       client/src/templates/Challenges/rechallenge/transformers.js
updateSuccessMessageSaga         client/src/templates/Challenges/redux/current-challenge-saga.js
currentChallengeSaga             client/src/templates/Challenges/redux/current-challenge-saga.js
executeChallengeSaga             client/src/templates/Challenges/redux/execute-challenge-saga.js
executeCancellablePreviewSaga    client/src/templates/Challenges/redux/execute-challenge-saga.js
executeCancellableChallengeSaga  client/src/templates/Challenges/redux/execute-challenge-saga.js
currentTabSelector               client/src/templates/Challenges/redux/index.js
checkChallenge                   client/src/templates/Challenges/redux/index.js
lockCode                         client/src/templates/Challenges/redux/index.js
updateJSEnabled                  client/src/templates/Challenges/redux/index.js
buildBackendChallenge            client/src/templates/Challenges/utils/build.ts
buildJSChallenge                 client/src/templates/Challenges/utils/build.ts
buildDOMChallenge                client/src/templates/Challenges/utils/build.ts
Block                            client/src/templates/Introduction/components/block.tsx
CertChallenge                    client/src/templates/Introduction/components/cert-challenge.tsx
handledErrorSymbol               client/src/utils/handled-error.ts
wrapHandledError                 client/src/utils/handled-error.ts
pathParsers                      client/src/utils/path-parsers.ts
pathsMap                         client/utils/challenge-types.js
injectConditionalTags            client/utils/tags.tsx
--- UNUSED TYPES (17)
LoginProps                client/src/components/Header/components/Login.tsx
AuthOrProfileProps        client/src/components/Header/components/auth-or-profile.tsx
MenuButtonProps           client/src/components/Header/components/menu-button.tsx
NavLinksProps             client/src/components/Header/components/nav-links.tsx
UniversalNavProps         client/src/components/Header/components/universal-nav.tsx
HeaderProps               client/src/components/Header/index.tsx
Validator                 client/src/components/formHelpers/form-validators.tsx
FormProps                 client/src/components/formHelpers/form.tsx
FileKeyChallenge          client/src/redux/prop-types.ts
SavedChallenges           client/src/redux/prop-types.ts
ClaimedCertifications     client/src/redux/prop-types.ts
CertTest                  client/src/redux/prop-types.ts
AllMarkdownRemark         client/src/redux/prop-types.ts
Required                  client/src/redux/prop-types.ts
DefaultDonationFormState  client/src/redux/types.ts
DefaultFetchState         client/src/redux/types.ts
HandledError              client/src/utils/handled-error.ts
--- DUPLICATE EXPORTS (4)
PayPalButtonScriptLoader, default  client/src/components/Donation/paypal-button-script-loader.tsx
UniversalNav, default              client/src/components/Header/components/universal-nav.tsx
Header, default                    client/src/components/Header/index.tsx
Map, default                       client/src/components/Map/index.tsx
```

You may not be interested in certain types of issues, then e.g. the `--onlyFiles` flag is available to speed up the process and have it report only the unused files. It could be useful to add more configurations for other parts of the repo, and maybe add scripts to `package.json` and/or add runs to CI.

Note that exportman requires Node.js v16.17.0 or higher.

After using this repo to improve exportman, why not give something back by opening this PR?  Happy to hear your thoughts and whether it could be interesting for you to add exportman to this repo and make maintenance easier and keep the codebase tidier. Any feedback is welcome! Happy to explain or help further.

### CODE REVIEW

**Comment by moT01** [comment]
This may look a little spammy, but I think it's a genuine attempt to be helpful. I am going to open this back up for some others to weigh in on. We have come across other tools in a similar fashion that have turned out to be helpful. If this can help us find code that we aren't using, I think it's worth a little more of a discussion.

**Comment by jeremylt** [comment]
Fair enough. I've been more quick to flag spammy behavior as spam since we're in Hacktoberfest.

**Comment by webpro** [comment]
I can understand my timing and some large sloppy console output may appear spammy, but just trying to help here. It's just that I pressed "Explore" here on GitHub when I searched for a large TypeScript project and this one appeared high in this list. I've fixed a few bugs in Exportman using this repo as a workload, after which I thought I should report back to you guys.

And back on topic, when looking at the most interesting part, the upper list of unused files (10). You'll find they are actually not referenced anywhere in the project. Only one exception (`block-save-wrapper.tsx`), which is coming from the strict configuration, is imported by a test file (`block-save-wrapper.test.tsx`).

The rest can be seen as "coding style" (some people prefer to simply export all TS interfaces), but also they can potentially lead to large cleanups when repeating the process of removing unused files and exports, in turn revealing new unused ones, etc.

I have tried other tools and explain why I think they're not sufficient for larger repos like this: https://github.com/webpro/exportman#why-yet-another-unused-fileexport-finder. It's an immature project, but I'm keen to develop it further. The results (also in other projects at work) are very promising. As long as the results do not cause CI jobs to fail (from false negatives) it certainly doesn't hurt, imho.

**Comment by ieahleen** [comment]
To take a look at the output, many files are not being used _yet_, see #44668

**Comment by ojeytonwilliams** [comment]
Hi @webpro, the tool is pretty interesting, thanks for putting it together! 

So, one quick observation: it seems to have been fooled by some of our imports.  For example, https://github.com/freeCodeCamp/freeCodeCamp/blob/main/client/src/components/formHelpers/form.tsx#L15 does import `block-save-wrapper`, but it does it it via the `import { default as alias } from ...` syntax.  Clearly we didn't need to do this (TS copes with `import thing from ...` just fine), but I feel like this is a false positive.  It's something that would be nice to know about, but probably not something that should be flagged as an error.

> Just chiming again to state that this tool is currently not meant to be used in an automated CI fashion.

Understood.  @raisedadead might have a different opinion on this, but my take is that if we can use it in CI, I'm all for it. If not, it's quite likely that we will simply forget to use it.

Having said all that, it's already proving useful in that it's uncovered a bunch of things that were exported for no reason. And it's always nice to find out you can delete entire files!

**Comment by webpro** [comment]
> So, one quick observation: it seems to have been fooled by some of our imports. For example, https://github.com/freeCodeCamp/freeCodeCamp/blob/main/client/src/components/formHelpers/form.tsx#L15 does import `block-save-wrapper`, but it does it it via the `import { default as alias } from ...` syntax. Clearly we didn't need to do this (TS copes with `import thing from ...` just fine), but I feel like this is a false positive. It's something that would be nice to know about, but probably not something that should be flagged as an error.

This is because `BlockSaveWrapper` is imported by a file that's excluded in the `filePatterns` (by `!**/*.test.{js,ts,tsx}`), since it's not production code. This is a very "strict" configuration. To include test files in the mix, this pattern can be moved to the `entryFiles`. Interestingly, something else is revealed using this configuration:

```json
{
  "entryFiles": [
    "client/gatsby-*.js",
    "client/src/pages/*.tsx",
    "client/src/templates/Challenges/**/{s,S}how.tsx",
    "client/src/templates/Introduction/**/{intro,super-block-intro}.tsx",
    "client/**/*.test.{js,ts,tsx}"
  ],
  "filePatterns": [
    "client/**/*.{js,ts,tsx}",
    "!client/static/misc/*.js",
    "!client/i18n/schema-validation.ts",
    "!client/plugins/**",
    "!client/postcss.config.js",
    "!client/src/client/frame-runner.ts",
    "!client/src/client/workers/**",
    "!client/webpack-workers.js",
    "!**/__mocks__/**",
    "!**/node_modules/**"
  ]
}
```

```
❯ npx exportman --config config/exportman/client.json --onlyFiles
client/src/assets/icons/donate-with-PayPal.tsx
client/src/assets/icons/intro-information.tsx
client/src/components/Donation/duration-amount-options.tsx
client/src/components/Header/components/user-state.tsx
client/src/components/helpers/form/block-save-wrapper.tsx
client/src/components/search/searchPage/empty-search.tsx
client/src/components/search/searchPage/no-results.tsx
client/src/components/search/searchPage/search-page-hits.tsx
client/src/declarations.d.ts
client/src/html.tsx
```

This reports `block-save-wrapper.tsx` as unused, but note that this file is in another directory and indeed, unused!
 
> > Just chiming again to state that this tool is currently not meant to be used in an automated CI fashion.
> 
> Understood. @raisedadead might have a different opinion on this, but my take is that if we can use it in CI, I'm all for it. If not, it's quite likely that we will simply forget to use it.

Totally agree. I had planned to add this feature soon. My idea was to simply have non-zero exit code with more than one reported unused file by default, but maybe a `--maxIssues` option or something could be useful here.

> Having said all that, it's already proving useful in that it's uncovered a bunch of things that were exported for no reason. And it's always nice to find out you can delete entire files!

That's great to here! Same here.

**Comment by ojeytonwilliams** [comment]
> This reports block-save-wrapper.tsx as unused, but note that this file is in another directory and indeed, unused!

Ah, my mistake, we have two files of with that name and, yes, one is unused.  Nice! I never would have caught that without the tool.

The only other things I spotted as potential false positives were

client/src/declarations.d.ts
client/src/html.tsx

We use `declarations.d.ts` to suppress TS errors for things we couldn't provide types for otherwise. Fonts and modules without type definitions and so on.  `html.tsx` isn't imported directly by our code, but Gatsby [uses it](https://www.gatsbyjs.com/docs/custom-html/) and we use Gatsby.  These aren't huge problems, but they do make it tricky to use in CI. Unless it's possible to ignore certain files, that is.

> My idea was to simply have non-zero exit code with more than one reported unused file by default, but maybe a --maxIssues option or something could be useful here.

Sounds great. That's pretty much all we'd want.

What I propose is this: we leave this PR open for further discussion and open up the list of issues you discovered for contribution. Once all the true positives have been dealt with, we can see where we are with respect to CI.  How does that sound?

**Comment by webpro** [comment]
> The only other things I spotted as potential false positives were
> 
> client/src/declarations.d.ts
> client/src/html.tsx

See the `projectFiles` in `exportman.json` to add ignore files, I've added a few already.

> > My idea was to simply have non-zero exit code with more than one reported unused file by default, but maybe a --maxIssues option or something could be useful here.
> 
> Sounds great. That's pretty much all we'd want.

The exit code is in the latest version (I've just updated it to the latest version). This could be relaxed it a bit with `--max-issues n` until more issues are resolved if that helps.

> What I propose is this: we leave this PR open for further discussion and open up the list of issues you discovered for contribution. Once all the true positives have been dealt with, we can see where we are with respect to CI. How does that sound?

That's sounds just fine. I'm leaving it up to you, as maintainers of this repo, on how to proceed with this.

Please note that the configuration in this PR is solely for the `/client` folder. The current configuration could be extended to include more entry and project files as a whole. Or, the configuration could be split up and handle various folders as separate packages. Or, just add more folders with separate configs. Oh my, too many options.

Feel free to read https://github.com/webpro/exportman for more details. This repo and this PR has helped me a lot to improve the tool further, so thanks for that!

**Comment by webpro** [comment]
Apologies to bother you again. Over the weekend I had an idea and it worked out pretty well. It even made me change the name of the project to "knip" (Dutch for "cut"), because the old name just didn't... cut it.

The tool now also finds (1) unused dependencies and (2) dependencies not listed in `package.json`. The first I excluded in this project, since there are too many false positives (coming from Babel plugins etc. not referenced from code; honestly I think they should be in `devDependencies` but that's another discussion).

I updated this PR. Not that much has changed actually. What's in it for you? Mostly the addition of the "unlisted dependencies" category:

```
❯ npx knip --config config/knip/knip.json --cwd client
--- UNUSED FILES (10)
src/assets/icons/donate-with-PayPal.tsx
src/assets/icons/intro-information.tsx
src/components/Donation/duration-amount-options.tsx
src/components/Header/components/user-state.tsx
src/components/helpers/form/block-save-wrapper.tsx
src/components/search/searchPage/empty-search.tsx
src/components/search/searchPage/no-results.tsx
src/components/search/searchPage/search-page-hits.tsx
src/declarations.d.ts
src/html.tsx
--- UNLISTED DEPENDENCIES (4)
react-instantsearch-core  src/components/search/searchBar/search-bar.tsx
react-instantsearch-core  src/components/search/searchBar/search-hits.tsx
react-instantsearch-core  src/components/search/searchBar/search-suggestion.tsx
gatsby-link               src/templates/Introduction/components/cert-challenge.tsx
```

🎣  I think they're good catches, since I believe both `react-instantsearch-core` and `gatsby-link` should be added explicitly as dependencies to `package.json`.

When I run Knip over both production and non-production files, it also finds that `faker` is not in `package.json`:

```
❯ npx knip --config config/knip/knip.dev.json --cwd client --include unlisted
react-instantsearch-core  src/components/search/searchBar/search-bar.tsx
react-instantsearch-core  src/components/search/searchBar/search-hits.tsx
react-instantsearch-core  src/components/search/searchBar/search-suggestion.tsx
gatsby-link               src/templates/Introduction/components/cert-challenge.tsx
faker                     src/utils/A-B-tester.test.ts
```

Hopefully this also makes it a bit more clear what this `dev` mode does/means. By default Knip is strict and only for production files, but it can be extended to include test files and `devDependencies` as well to also cover test code.

/ktxbaai!

**Comment by ojeytonwilliams** [comment]
No, no it's all good.  I understand that you're iterating rapidly at the moment.

Once the linked issue is resolved, let's revisit this!

**Review by raisedadead — COMMENTED** [review]
Hi @webpro 

Once you add a handy npm run-script for us to use, this is golden for a merge.

We can worry about adding this into a CI/CD workflow in later PRs (could be you, or us when we are more familiar with the tool)

**Review by raisedadead — DISMISSED** [review]

**Comment by webpro** [comment]
> Hi @webpro
> 
> Once you add a handy npm run-script for us to use, this is golden for a merge.
> 
> We can worry about adding this into a CI/CD workflow in later PRs (could be you, or us when we are more familiar with the tool)

I've added two npm scripts, the first one you could use in CI already, the second one can help with maintenance etc. in the `/client` dir.

**Comment by webpro** [comment]
> Hi @webpro
> 
> Once you add a handy npm run-script for us to use, this is golden for a merge.
> 
> We can worry about adding this into a CI/CD workflow in later PRs (could be you, or us when we are more familiar with the tool)

I've added two npm scripts, the first one you could use in CI already, the second one can help with maintenance etc. in the `/client` dir. Guess this could be merged as-is, but let me know any feedback you may have now or later along the road. Thanks for bearing with me! This PR has been of great help to knip's early days.

**Review by raisedadead — APPROVED** [review]
LGTM

**Review by ojeytonwilliams — APPROVED** [review]
Awesome, thanks again for creating the tool and setting it up for us!

LGTM :+1:

**Pull request merged**
