### PR TITLE
fix(client): display legacy certs like current ones

### LINKED ISSUE #39132: Tests for some projects can be bypassed
On the settings page, I can submit "legacy" projects and, if they are still part of the curriculum, they will automatically be filled in for that project as well.

For example, I can submit the timestamp microservice project like this...
Screen Shot 2020-06-24 at 9 17 19 PM

and it automatically gets filled in here...
Screen Shot 2020-06-24 at 9 19 02 PM

If I were to try and submit this URL on the [page for that project](https://www.freecodecamp.dev/learn/apis-and-microservices/apis-and-microservices-projects/timestamp-microservice), the tests fail and I can't submit.

Wondering if we should remove the input fields for legacy projects on the settings page and make them like the rest. I believe all the legacy projects pages are all still available either in the current curriculum, or the take home projects.

### LINKED ISSUE #39561: Legacy submission bug
**Describe the bug**

**To Reproduce**
1. Go to `https://www.freecodecamp.dev/settings`
2. Scroll down to just above 'Legacy Backend'
3. Enter in a valid url for any 'Legacy Front End' project 
4. Click 'Save Progress'
5. Alter that url (it should still be valid)
6. Click 'Save Progress' again
7. See 'It looks like you have not completed the necessary steps. Please complete the required projects to claim the Legacy Front End Certification'

**Expected behavior**
Step 7 should report: 'Your projects have been updated.'

@raisedadead am I right in thinking that once someone has claimed their cert, submissions should be closed?

Here's what it looks like:
SubmissionBug

### PR DESCRIPTION
**Pull request by gikf**
Additional checklist:
- [x] Remove obsolete code handling rendering of the legacy certifications form from `Certification.js`
- [x] Update cypress tests.
- [x] `Stylize Stories on Camper News` project from `Legacy Front End` doesn't have truly corresponding project in the current curriculum, although it shares `id` with the `Build a Tribute Page` from `Responsive Web Design` and one fills the other. I haven't changed link for it yet.
- [ ] Unify titles of projects in the legacy certifications, to match exactly how they are titled currently?
- [ ] Add more and/or change cypress/jest tests?
- [x] Fix merge conflict.

Checklist:

- [x] I have read [freeCodeCamp's contribution guidelines](https://contribute.freecodecamp.org).
- [x] My pull request has a descriptive title (not a vague title like `Update index.md`)
- [x] My pull request targets the `main` branch of freeCodeCamp.
- [x] All the files I changed are in the same world language, for example: only English changes, or only Chinese changes, etc.

Closes #39132
Closes #39561 (indirectly)

### CODE REVIEW

**Comment by gikf** [comment]
I've removed more not needed anymore (I hope) internals related to updating legacy certs. `updateLegacyCert` props and actions, legacy `update-my-projects` route and handler. Although I haven't noticed anything broken and are not complaining, I'm getting a bit nervous with the removals.

**Review by ShaunSHamilton — DISMISSED** [review]
This LGTM 👍 , and massively simplifies the component. So, thanks for that.

I am not too sure about the changes to `certAndProjectMap`, but still expect that file to be deleted sometime. So, seeing as it works, I am happy.

**Comment by ojeytonwilliams** [comment]
First off, @gikf, this works much better with fewer lines of code, nice work!  The only problem I saw was "Stylize Stories on Camper News", which doesn't exist any more.  Ideally we should recreate this and put it in the interview prep section, or it will be impossible to claim the legacy front end cert.  

@scissorsneedfoodtoo @raisedadead this is a bit before my time, do you happen to remember when this was removed?

**Comment by scissorsneedfoodtoo** [comment]
@gikf, wow, this looks great! Thank you for all the hard work you put into these improvements.

@ojeytonwilliams, the Stylize Stories on Camper News project was a bit before my time as well.

I did a bit of digging and it seems like we used to have a feature where people could submit posts and links, and the data was accessible through an API.

The API was [later deprecated](https://github.com/freeCodeCamp/freeCodeCamp/commit/6bb1b090200cfb6b0c094278a81288691260aefb) in favor of the freeCodeCamp subreddit in 2016.

Looking at the id for the Stylize Stories on Camper News project, it seems like it's the same one we use for the Tribute Page project, `bd7158d8c442eddfaeb5bd18`. So I'm thinking that some time ago, the Camper News project was replaced by the Tribute Page project, and the Tribute Page just used the same id. Is that correct, @raisedadead.

Looking at my settings page, this seems to be the case. I definitely didn't complete the Stylize Stories on Camper News project, but a link is there, which points to my old Tribute Page project.

If we did replace the Stylize Stories on Camper News project with the Tribute Page, and since they're using the same id, should we just go ahead and update the name for that project? Maybe something like "Stylize Stories on Camper News / Tribute Page"?

**Comment by ojeytonwilliams** [comment]
Thanks for digging into that @scissorsneedfoodtoo, we're really going deep into fcc's history, here!

So, update the links to point to the tribute project and update the legacy title to "Stylize Stories on Camper News / Tribute Page"?  Sounds reasonable to me.  It does create another special case, but I think that's unavoidable if we want to have the legacy links make sense for everyone. @raisedadead what do you think?

**Comment by raisedadead** [comment]
Yes - that project is before I started working full time here. So it's pretty early days, and I bet not even Quincy remembers how it was structured in the code.

I am in favour of whatever keeps this PR moving, I really do not think we would have high support requests from a project that old (4+ yrs). 

This PR does a good job of improving the UX and I think we should be fine moving forward with your recommendation Oliver & Kris.

**Comment by moT01** [comment]
What about just completely renaming it to Build a Tribute Page?

**Comment by scissorsneedfoodtoo** [comment]
@moT01, that works, too. The Stylize Stories on Camper News project is so old that I doubt many people would mind if we just renamed it to Build a Tribute Page.

As far as I can tell, Camper Leaderboard was renamed to Forum Homepage some time ago. It wasn't a separate project with a different id that replaced another project. We should go ahead and rename that, too.

**Comment by raisedadead** [comment]
Great, thanks for confirming guys. @gikf when you get a chance would you be able to add these additional changes to the PR?

**Review by ojeytonwilliams — APPROVED** [review]
LGTM :+1: 

The legacy settings look so much better now. Great work, as always, @gikf

**Review by ShaunSHamilton — APPROVED** [review]
LGTM 👍

**Comment by gikf** [comment]
Uh, sorry for the flaky test. I'm looking at how to make it more reliable.

**Comment by scissorsneedfoodtoo** [comment]
No worries @gikf. Thanks for taking a look at that.

**Comment by raisedadead** [comment]
Let us know if we can be of help in any way.

**Comment by Sembauke** [comment]
Hey @gikf, 

I've been working a lot with Cypress, and know probably where the issue lies.  Cypress does not always fully wait for the Monaco editor to load incorrectly. What you can do is `cy.get()`  in one of the elements nested in the Monaco editor.

I don't know for sure and there might be a better solution for your problem.

**Comment by Sembauke** [comment]
Adding `cy.get('.react-monaco-editor-container', {timeout: 30000})` after the foreach loop seems to do the trick

**Comment by gikf** [comment]
@Sembauke thanks, I'm a bit confused why exactly this is happening, and I'm unable to reproduce it locally (it might be because I'm running just failing file spec). Do you want to make PR for that?

**Comment by Sembauke** [comment]
> @Sembauke thanks, I'm a bit confused why exactly this is happening, and I'm unable to reproduce it locally (it might be because I'm running just file spec that's causing error). Do you want to make PR for that?

I made a PR :)

**Comment by ojeytonwilliams** [comment]
These issues are a massive pain, as Sem is all too aware.  They're random by nature and only seem to appear once you've built the site.

My (limited) understanding is that they're generally caused by navigating too quickly between pages, but Sem has more experience fighting them than I do.

**Comment by gikf** [comment]
@ojeytonwilliams Oh, randomness doesn't help here.

@Sembauke thanks again.

**Comment by ojeytonwilliams** [comment]
@gikf No, it really doesn't, flaky tests are incredibly frustrating.  Fortunately, Sem's fix seems to have banished them.

**Pull request merged**
