### PR TITLE
Fix example if-else statements with clearer example

### LINKED ISSUE #4722: Usability on Waypoint: Use Conditional Logic with If and Else Statements
I would suggest changing the example on the left side since it can be confusing for people not familiar with conditional logic.
The example listed on the site shows (I added my suggestion as a comment on the code)

if (1 === 2) {  

  return true;
// 1 is NOT equal to 2 so the condition evaluates to FALSE. So to return TRUE can be confusing in my opinion
} else {

  return false;

}

### PR DESCRIPTION
**Pull request by erictleung**
Closes #4722. I hope that makes it less confusing on what is going on in an if-else statement.

### CODE REVIEW

**Comment by ltegman** [comment]
Thanks for the PR! However, you're using unescaped double-quotes inside of a double-quoted string literal, which break the outside string literal. Free Code Camp actually prefers using single-quotes for string literals in javascript code examples, so if you change the double-quotes in `"x is 2"` and `"x is not 2"` to single-quotes that will solve the problem.

After you've changed that don't add a new commit, just amend your old one by doing `git add . && git commit --amend` and then force push it to your remote with `git push -f`.

**Comment by erictleung** [comment]
Ah I forgot about those. Thanks! I'll go ahead and fix that real fast.

**Comment by ltegman** [comment]
Haha, I think you may have skimmed the part of my post where I said FCC prefers single-quotes to be used in example code. If you could switch to them it would be much appreciated :smile: (and you won't even need to escape them then!)

**Comment by erictleung** [comment]
Thanks again @ltegman! I think it's getting late for me haha.

**Comment by ltegman** [comment]
Thanks for the quick fix!

**Pull request merged**
