### PR TITLE
fix(client): Don't truncate challenge titles

### LINKED ISSUE #41090: Challenge titles should not be truncated.
I am not sure if this is by design, but I don't think it is necessary.

Screen Shot 2021-02-13 at 12 20 17 AM

### LINKED ISSUE #41123: Challenge Title CSS
Some challenge titles are not fit a single line:

freecodecamp_before

So I think it would be helpful to add a wrap to a new line for a better perception of content:

freecodecamp_after

### PR DESCRIPTION
**Pull request by ClockworkOrange605**
Checklist:

- [x] I have read [freeCodeCamp's contribution guidelines](https://contribute.freecodecamp.org).
- [x] My pull request has a descriptive title (not a vague title like `Update index.md`)
- [x] My pull request targets the `main` branch of freeCodeCamp.
- [x] All the files I changed are in the same world language, for example: only English changes, or only Chinese changes, etc.

Closes #41090

### CODE REVIEW

**Review by moT01 — CHANGES_REQUESTED** [review]
This is an extreme example, but they do still get truncated at very small widths:
Screen Shot 2021-02-17 at 11 29 33 AM

^^ I don't see this as a problem though, as it's too small to even work on it.

Here's the challenge when the title is fully displayed:
Screen Shot 2021-02-17 at 11 29 47 AM

At a little smaller width:
Screen Shot 2021-02-17 at 11 29 41 AM

^^ The words start to disappear. `string` is missing from the bottom image, and the words continue to disappear as it gets smaller. I think the `max-height` might be causing that. I think this should be fixed.

**Comment by ClockworkOrange605** [comment]
After removing fixed max-height:

**Review by ojeytonwilliams — APPROVED** [review]
LGTM :+1: 

Nice work @ClockworkOrange605

**Review by moT01 — APPROVED** [review]
LGTM @ClockworkOrange605 🎉 Thanks for fixing this and congratulations on your first contribution to this freeCodeCamp repository 🎉 

For future reference, it's best to create a branch to work on for issues. There's some more info on this [under #3 here](https://contribute.freecodecamp.org/#/how-to-setup-freecodecamp-locally?id=making-changes-locally).

**Pull request merged**
