### PR TITLE
fix(client, curriculum): center images in challenge description

### PR DESCRIPTION
**Pull request by huyenltnguyen**
Checklist:

- [x] I have read and followed the [contribution guidelines](https://contribute.freecodecamp.org).
- [x] I have read and followed the [how to open a pull request guide](https://contribute.freecodecamp.org/how-to-open-a-pull-request/).
- [x] My pull request targets the `main` branch of freeCodeCamp.
- [x] I have tested these changes either locally on my machine, or GitPod.

This PR fixes an image alignment issue caused by #55068.

## Screenshots

| Before | After |
| --- | --- |
| Screenshot 2024-06-14 at 02 48 02 | Screenshot 2024-06-14 at 02 52 04 |

### CODE REVIEW

**Review by Dario-DC — COMMENTED** [review]
In case you haven't done it yet, could you include this two? :slightly_smiling_face: 
https://github.com/freeCodeCamp/freeCodeCamp/blob/dda4bb9d6a6c49ed626ed3bfa8dd69dfff9bc541/curriculum/challenges/english/07-scientific-computing-with-python/learn-special-methods-by-building-a-vector-space/65f03d9f92eac9183a4d3281.md?plain=1#L12
https://github.com/freeCodeCamp/freeCodeCamp/blob/dda4bb9d6a6c49ed626ed3bfa8dd69dfff9bc541/curriculum/challenges/english/07-scientific-computing-with-python/learn-special-methods-by-building-a-vector-space/65f3fe07cc763212efe91285.md?plain=1#L12

**Review by ojeytonwilliams — APPROVED** [review]
Nice work, @huyenltnguyen. 

LGTM :+1:

**Comment by moT01** [comment]
Wondering if this is the best approach. I'm fine with it, but couldn't we do something like `.description > img { margin: auto }` - so it's a little more universal?

Also wondering about other clients. Maybe it will make things more difficult for mobile or other future clients, in that they may have to overwrite the inline styles. Perhaps that's fine.

**Review by Sembauke — APPROVED** [review]

**Comment by Sembauke** [comment]
Thanks Huyen!

**Pull request merged**
