### PR TITLE
refactor(client): data sourcing for super-block-intro

### PR DESCRIPTION
**Pull request by ojeytonwilliams**
Checklist:

- [x] I have read and followed the [contribution guidelines](https://contribute.freecodecamp.org).
- [x] I have read and followed the [how to open a pull request guide](https://contribute.freecodecamp.org/how-to-open-a-pull-request/).
- [x] My pull request targets the `main` branch of freeCodeCamp.
- [x] I have tested these changes either locally on my machine, or GitPod.

The main change of this PR is to get the data we want more directly (`nodes` rather than `edges` with nodes inside them) and only passing data that the components need (`challenges` rather than `nodes` with challenges inside them).

### CODE REVIEW

**Comment by ojeytonwilliams** [comment]
I'll revisit this after https://github.com/freeCodeCamp/freeCodeCamp/pull/55792 is in, since that touches a lot of the same code.

**Comment by Sembauke** [comment]
Hey @ojeytonwilliams,

Can you take a look at the tests? Some of them seem to be failing.

**Review by moT01 — APPROVED** [review]
LGTM 🎉

**Review by ahmaxed — APPROVED** [review]
@ojeytonwilliams, LGMT upon conflict resolution.

**Pull request merged**
