### PR TITLE
fix(learn): Fixed test issue in HashTable exercise

### LINKED ISSUE #38049: Hash Table challenge test case
**Describe your problem**

The test case pass when the remove method is empty
> The remove method should accept a key as input and should remove the associated key value pair 

**How to reproduce it:**
Here is link of my code: https://gist.github.com/hisergiorojas/8c3dbd57afd02663de9e5c0a70cc21e7

1. Copy and paste the code to the FreeCodeCamp editor.
2. Click on "Run the Tests"
3. There will be a check mark on: 
alt text

**Add a Link to the page with the problem:**
https://www.freecodecamp.org/learn/coding-interview-prep/data-structures/create-a-hash-table

### PR DESCRIPTION
**Pull request by anthonyzeng99**
Checklist:

- [x] I have read [freeCodeCamp's contribution guidelines](https://github.com/freeCodeCamp/freeCodeCamp/blob/master/CONTRIBUTING.md).
- [x] My pull request has a descriptive title (not a vague title like `Update index.md`)
- [x] My pull request targets the `master` branch of freeCodeCamp.
- [x] All the files I changed are in the same world language, for example: only English changes, or only Chinese changes, etc.

Closes #38049

Fixed issue where test for removal from hash table was passing even if method implementation is incorrect or empty. New test also checks to make sure the add method actually added the key/value or else the test would pass by virtue of the key/value never having been in the collection in the first place.

### CODE REVIEW

**Review by moT01 — COMMENTED** [review]
I know this was preexisting, but the test assumes correct implementation of the `add` method. This test would fail if that method is wrong. I think we should write an external add method to use so we aren't counting on the users. Perhaps inline in the test, or probably better in the "[before test](https://github.com/freeCodeCamp/freeCodeCamp/blob/6251e01c3359529511beafd394b1d59f970e8e9e/curriculum/challenges/english/08-coding-interview-prep/data-structures/create-a-hash-table.english.md#before-test)" area. What do you think @anthonyzeng99?

**Comment by RandellDawson** [comment]
> Perhaps inline in the test, or probably better in the "before test" area. 

@moT01 Definitely put it in the Before Test section.

**Comment by anthonyzeng99** [comment]
@moT01 @RandellDawson Makes sense. I'll get on that.

**Review by moT01 — APPROVED** [review]
LGTM 🎉 

For future reference @anthonyzeng99, it's good to give your branch a scope. See [this area of the docs](https://github.com/freeCodeCamp/freeCodeCamp/blob/master/docs/how-to-setup-freecodecamp-locally.md#making-changes-locally) - scroll down a little to `#3`.

**Review by ojeytonwilliams — APPROVED** [review]
LGTM :+1:

**Comment by ojeytonwilliams** [comment]
@anthonyzeng99 Thank you for your contribution to the page! :+1:
We're happy to accept these changes, and look forward to future contributions. :memo:

**Pull request merged**
