### PR TITLE
fix(curriculum): add desc cat-app-step-15

### LINKED ISSUE #49021: Cat Photo App Step 15
### Describe the Issue

I think we can clarify this step with one small tweak.

### Affected Page

https://www.freecodecamp.org/learn/2022/responsive-web-design/learn-html-by-building-a-cat-photo-app/step-15

### Current Instructions

Currently the instructions say

> Turn the image into a link by surrounding it with necessary element tags. Use https://freecatphotoapp.com as the anchor's href attribute value.

### Expected behavior

Students seem to often miss what is going on here and try to make a combo img-anchor element.

We could modify it to add a brief bit of context

> In previous steps you used an anchor element to turn text into a link. Other types of content can also be turned into a link by wrapping it in anchor tags.

> Turn the image into a link by surrounding it with necessary element tags. Use `https://freecatphotoapp.com` as the anchor's `href `attribute value.

### Screenshots

_No response_

### System

All

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by marktlinn**
Add additional information in the description linking to previous exercises to avoid possible confusion as per the issue raised (#49021)

Checklist:

- [  X ] I have read [freeCodeCamp's contribution guidelines](https://contribute.freecodecamp.org).
- [ X  ] My pull request has a descriptive title (not a vague title like `Update index.md`)
- [ X ] My pull request targets the `main` branch of freeCodeCamp.
- [ X  ] I have tested these changes either locally on my machine, or GitPod.

fix #49021

### CODE REVIEW

**Review by SanjeevSingh08 — COMMENTED** [review]
yes Its done

**Review by SanjeevSingh08 — COMMENTED** [review]
This text will be more comprehensive and is easy to understand.

**Review by Sboonny — APPROVED** [review]
LGTM 🎉, thank you for your contribution to the page! 👍.

**Comment by ShaunSHamilton** [comment]
@marksist300 Thank you for your contributions to freeCodeCamp. However, the issue linked is labelled with the `first timers only` label.

As you are already a contributor, I am going to close this PR, and let a first timer contribute to close the issue.

**Comment by marksist300** [comment]
> @marksist300 Thank you for your contributions to freeCodeCamp. However, the issue linked is labelled with the `first timers only` label.
> 
> As you are already a contributor, I am going to close this PR, and let a first timer contribute to close the issue.

Ah, ok, no worries 👍🏻

**Pull request closed without merging**
