### PR TITLE
test(e2e,playwright): staging-warning-modal

### PR DESCRIPTION
**Pull request by Riya267**
Checklist:

- [x] I have read and followed the [contribution guidelines](https://contribute.freecodecamp.org).
- [x] I have read and followed the [how to open a pull request guide](https://contribute.freecodecamp.org/#/how-to-open-a-pull-request).
- [x] My pull request targets the `main` branch of freeCodeCamp.
- [x] I have tested these changes either locally on my machine, or GitPod.

 #51705

Snapshot:-
image

### CODE REVIEW

**Comment by Riya267** [comment]
camperbot cant code

**Comment by Bitnagar** [comment]
I think its better for everyone that contributors must not make more than 1 PR for this issue. It will give everyone a fair chance to contribute.

**Comment by raisedadead** [comment]
> I think its better for everyone that contributors must not make more than 1 PR for this issue. It will give everyone a fair chance to contribute.

Hi there,

Do not be disappointed. Hactoberfest is a celebration of getting started with open-source. Just know that we are only one among the millions of open-source repositories on GitHub. There are millions more on GitLab.

We all love and share the passion for contributing to freeCodeCamp, but I would encourage you to check these links to explore even more opportunities during hacktoberfest and beyond hactoberfest (in no particular order):

- https://gitlab.com/explore/projects/topics/hacktoberfest
- https://hacktoberfest-projects.vercel.app
- https://up-for-grabs.net/#/
- https://www.firstissue.dev/
- https://github.com/topics/hacktoberfest
- https://github.com/search?q=is%3Aissue%20label%3Ahacktoberfest&type=issues (This has 180,000 results)

There is no dearth of opportunities. Hope this helps :)

**Comment by Riya267** [comment]
@naomi-lgbt Please review this pull request. thanks

**Comment by jdwilkin4** [comment]
Hey @Riya267 

I have remove the closes keyword in your PR body

The reason why is because we don't want to close this hacktoberfest issue because multiple PR's will be associated with it.
We just want to mention it.

The closes keyword will automatically closes a PR when a PR is approved and merged in which is not what we want in this case.

Hope that helps

**Review by huyenltnguyen — APPROVED** [review]

**Review by Ahmadkashif — APPROVED** [review]
LGTM

**Review by moT01 — APPROVED** [review]
LGTM @Riya267 :tada: Thanks for contributing to freeCodeCamp :tada:

**Pull request merged**
