### PR TITLE
Update instructions for first challenge under 'Quality Assurance and Testing with Chai'

### PR DESCRIPTION
**Pull request by cadams8238**
Add instructions to let user know which file to navigate to in order to begin lesson for learn-how-javascript-assertions-work.english.md

- [x] I have read [freeCodeCamp's contribution guidelines](https://github.com/freeCodeCamp/freeCodeCamp/blob/master/CONTRIBUTING.md).
- [x] My pull request has a descriptive title (not a vague title like `Update index.md`)
- [x] My pull request targets the `master` branch of freeCodeCamp.
- [x] None of my changes are plagiarized from another source without proper attribution.
- [x] My article does not contain shortened URLs or affiliate links.

If your pull request closes a GitHub issue, replace the XXXXX below with the issue number.

Closes #XXXXX

### CODE REVIEW

**Comment by RandellDawson** [comment]
Closed and Reopened this PR to attempt to resolve a specific Travis build failure.

**Comment by RandellDawson** [comment]
Closed/Reopened this PR in an attempt to resolve 503 Travis error

**Review by moT01 — COMMENTED** [review]
The last few words in the sentence added sound repetitive, as they are nearly identical to the last few words in the next sentence. Also, markdown doesn't translate to the website (see photo below). With those two issues in one sentence, I think it might be easiest to just close this and have someone go through this whole section thoroughly to make better instructions since this whole section has very minimal descriptions/instructions and it needs a makeover. 

However, if someone wants to request changes - this does have the potential to slightly improve this one challenge.
<hr>
screen shot 2019-02-27 at 9 16 49 am

**Comment by RandellDawson** [comment]
Thank you for opening this pull request.

This is a standard message notifying you that we’ve reviewed your pull request and have decided not to merge it. We would welcome future pull requests from you.

**Reason:**  I agree with @moT01's comments.  This whole section needs to be discussed in an issue and then all these challenges should be reworded.

Thank you and happy coding.

**Pull request closed without merging**
