### PR TITLE
test explicit types

### PR DESCRIPTION
**Pull request by Sboonny**
Don't merge

### CODE REVIEW

**Comment by raisedadead** [comment]
Please consider making PRs as drafts before clicking the open PR button. It helps reduce the notification noise.

**Comment by ojeytonwilliams** [comment]
Thanks for the examples, @Sboonny. I'm still not convinced there's a problem here, though.

In the cases you've shown the types are aliases for the same thing `{ 'camper': string }`. Because of that, there's no logic you can write that will behave differently if you use `HonestCamper`, `TopContributor` or `Camper`. I get that they're misleading names, but we are not being forced to write them by the linter.

If I reviewed this code, I'd just say "Hey, these aliases are all the same, please just use `Camper` or `{ 'camper': string }` as the return type".

Now, you mentioned `as const`. That's definitely a good idea, since `{ readonly camper: 'HonestCamper' }` is a reasonable type for an honest camper. However, that's compatible with the lint rule. You just have to use `{ readonly camper: 'HonestCamper' }` (or an alias) in the return type.

**Comment by Sboonny** [comment]
Finally, we are in the same ground and discussing the same thing, you mentioned this.

> Now, you mentioned `as const`. That's definitely a good idea, since `{ readonly camper: 'HonestCamper' }` is a reasonable type for an honest camper. However, that's compatible with the lint rule. You just have to use `{ readonly camper: 'HonestCamper' }` (or an alias) in the return type.

Even with your insight and if you have set the type beforehand to `read-only`, TypeScript doesn't care, as shown in the last commit, it won't provide an error, even with read-only type provided, that is why I am saying it isn't secure and can lie.

---

> In the cases you've shown the types are aliases for the same thing `{ 'camper': string }`. Because of that, there's no logic you can write that will behave differently if you use `HonestCamper`, `TopContributor` or `Camper`. I get that they're misleading names, but we are not being forced to write them by the linter.
>
> If I reviewed this code, I'd just say "Hey, these aliases are all the same, please just use `Camper` or `{ 'camper': string }` as the return type".

And I would have asked myself to use `useReducer`, so we have different way of thinking and that's fine, but we shouldn't be forced to follow the same rules, especially if that rule doesn't provide security or productivity. 

The code I write, the code you write, or the code contributors write in the end will provide the same functionality, without extra rules that shackle how we produce that function.

If you want to type 100 functions with explicit type, go for it< I will happily mess with it and review it, but I shouldn't or random contributor should follow that rule.

**Comment by Sboonny** [comment]
> Same with JavaScript? Explicit return types might not be perfect, sure. But they do improve the developer experience and reduce the risk of unexpected bugs from returning the incorrect type.

This isn't always the case, so because it isn't always the case, let's not put it as default, and feel free to add 100 explicit types, but let's not **force** it

**Comment by Sboonny** [comment]
Btw, if we are going to keep spinning around the point, whether it's helpful or not, just add it as I said before 🤷, if you don't want to exclude the client, don't.

**Comment by raisedadead** [comment]
I think there is a simple way & scientific (pun intended) to resolve this discussion:

- Find a precedent for NOT defaulting to explicit return types in other projects to guide us.
- If we do not find a precedent, then it just comes down to our own opinion. This can be put to a concrete action item by putting it to vote.

What do you all think?

**Pull request closed without merging**
