### PR TITLE
Fix naming in "Where art thou" challenge

### LINKED ISSUE #9239: Where art thou - Intermediate Algorithm
I'm being very pedantic: 

1) The quote is not 'where art thou?', it's 'wherefore art thou?' 
2) The meaning is not 'where are you?', but 'why are you?' i.e. 'why were you born a Montague?'

Challenge [Where art thou](https://www.freecodecamp.com/challenges/where-art-thou) has an issue.
User Agent is: <code>Mozilla/5.0 (Macintosh; Intel Mac OS X 10_9_5) AppleWebKit/601.5.17 (KHTML, like Gecko) Version/9.1 Safari/537.86.5</code>.
Please describe how to reproduce this issue, and include links to screenshots if possible.

My code:
```javascript

function whereAreYou(collection, source) {
  // What's in a name?
  var arr = [];
  // Only change code below this line
  
  
  // Only change code above this line
  return arr;
}

whereAreYou([{ first: "Romeo", last: "Montague" }, { first: "Mercutio", last: null }, { first: "Tybalt", last: "Capulet" }], { last: "Capulet" });

```

### PR DESCRIPTION
**Pull request by Manish-Giri**
#### Pre-Submission Checklist

- [x] Your pull request targets the `staging` branch of FreeCodeCamp.
- [x] Branch starts with either `fix/`, `feature/`, or `translate/` (e.g. `fix/signin-issue`)
- [x] You have only one commit (if not, [squash](https://github.com/FreeCodeCamp/FreeCodeCamp/wiki/git-rebase#squashing-multiple-commits-into-one) them into one commit).
- [x] All new and existing tests pass the command `npm run test-challenges`. Use `git commit --amend` to amend any fixes.
#### Type of Change

- [x] Small bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds new functionality)
- [ ] Breaking change (fix or feature that would change existing functionality)
- [ ] Add new translation (feature adding new translations)
#### Checklist:

- [x] Tested changes locally.
- [x] Closes currently open issue (replace XXXX with an issue no): Closes #9239 
#### Description

Changed the challenge title to 

> Wherefore art thou?

Changed the challenge function to 

> whatIsInAName

Verified change with command `npm run test-challenges`.  Result - 

> total : 775 / passing: 775

closes #9239

### CODE REVIEW

**Comment by atjonathan** [comment]
### **LGTM :+1:**

**Comment by Bouncey** [comment]
The only thing I can see is an issue number in the commit message.

Can you please `git commit --amend -m "Fix/Where Art Thou"`

then `git push -f` don't worry about any advisory messages.

Great first FreeCodeCamp PR!

Thanks for contributing :tada:

**Comment by Manish-Giri** [comment]
Sure thing, thanks for pointing it out! Will get back to it as soon as I return home.

**Comment by Manish-Giri** [comment]
It looks like the branch against which I made the change is now 6 commits behind the FCC staging branch.

> This branch is 1 commit ahead, 6 commits behind FreeCodeCamp:staging.

How do I make my branch up to date before submitting the new PR, without having to discard this branch and redo the process again against another branch?

 Thanks for the help!

**Comment by Bouncey** [comment]
@Manish-Giri try `git pull --rebase upstream staging`

**Pull request merged**
