### PR TITLE
Cristianvnica 1677

### PR DESCRIPTION
**Pull request by cristianvnica**
I can see that all my previous changes sum up in this commit. Sry for
that, still newbie.

### CODE REVIEW

**Comment by BerkeleyTrue** [comment]
if all your commits are summed up here, please close the previous PR's

**Comment by cristianvnica** [comment]
Done

**Comment by QuincyLarson** [comment]
Thanks for spotting these issues and fixing them!

**Comment by QuincyLarson** [comment]
Note that due to significant changes, I'm making these changes manually on my side but I'll credit you in the commit.

**Comment by cristianvnica** [comment]
@BerkeleyTrue @QuincyLarson we thank you!

**Pull request closed without merging**
