### PR TITLE
update doc to include instruction to update page title to conform with tests

### LINKED ISSUE #16967: How to Use Passport Strategies & Create New Middleware
https://learn.freecodecamp.org/information-security-and-quality-assurance/advanced-node-and-express/create-new-middleware/

1) code does not work for mongodb package 3.X needs 2.X or will get db.collection is not a function.  hence this dependency needs to be more strictly enforced
error...

2) test no.2 does not pass even though i am pretty certain code redirects to '/' 

#### Challenge Name

https://beta.freecodecamp.org/en/challenges/advanced-node-and-express/create-new-middleware
https://beta.freecodecamp.org/en/challenges/advanced-node-and-express/how-to-use-passport-strategies
#### Browser Information

* Browser Name, Version: 
* Operating System: 
* Mobile, Desktop, or Tablet: 

#### Your Code

https://tan-bow.glitch.me/
```js



```

### PR DESCRIPTION
**Pull request by ryantimjohn**
update doc to include changing '/' page title to "Home page" to conform with tests.

- [ x] I have read [freeCodeCamp's contribution guidelines](https://github.com/freeCodeCamp/freeCodeCamp/blob/master/CONTRIBUTING.md).
- [ x] My pull request has a descriptive title (not a vague title like `Update index.md`)
- [ x] My pull request targets the `master` branch of freeCodeCamp.
- [ x] None of my changes are plagiarized from another source without proper attribution.
- [ x] All the files I changed are in the same world language (for example: only English changes, or only Chinese changes, etc.)
- [ x] My changes do not use shortened URLs or affiliate links.

Closes #16967

### CODE REVIEW

**Comment by RandellDawson** [comment]
Issue #16967 was already closed.  Also, if I am not mistaken, added more than what you state in your PR body.  I appears you added the actual solution code?

**Comment by ryantimjohn** [comment]
If you look here:
https://www.freecodecamp.org/forum/t/advanced-node-and-express-create-new-middleware/212990
Issue #16967 was closed prematurely. Campers need to update the name of the page to "Home page" for the tests to pass (the tests search for the words "Home page" somewhere in the page) but, at no point in the tutorial does it say to do so.

**Comment by ojeytonwilliams** [comment]
This is still being discussed in the original issue and #18103 and I agree that the challenge is confusing as it stands.  However, I think it would be preferable to change the tests rather than the description.  That way the student can focus on what's relevant to the challenge.  The solution in freeCodeCamp/curriculum#103 provides an example of one way it could be done.  

Also I agree with @RandellDawson about the solution text.

**Comment by thecodingaviator** [comment]
@RandellDawson I guess what this PR is doing is, like you said, adding the solution into the instructions. Maybe we should close this PR and it can be reopened if the OP changes the content

**Comment by thecodingaviator** [comment]
@ryantimjohn 

@RandellDawson and I had a short conversation about this and we think that w.r.t. my comment on the PR, we should close it, so that's what I'll do. **If however**, you make changes and want us to review it again, please reopen the PR.

**Pull request closed without merging**
