### PR TITLE
feat(Cypress): Update Cypress workflow for parallelization

### PR DESCRIPTION
**Pull request by Twaha-Rahman**
Checklist:

- [x] I have read [freeCodeCamp's contribution guidelines](https://contribute.freecodecamp.org).
- [x] My pull request has a descriptive title (not a vague title like `Update index.md`)
- [x] My pull request targets the `master` branch of freeCodeCamp.
- [x] All the files I changed are in the same world language, for example: only English changes, or only Chinese changes, etc.

This PR allows Cypress to run tests in parallel. This will also improve the scalability of the Cypress CI.

### CODE REVIEW

**Comment by ojeytonwilliams** [comment]
Hey @Twaha-Rahman, it looks like this will run all the specs 3 times on pull requests.  Do you know if it's possible to do a single run on a PR while keeping the ability to load balance the specs when we're recording?

**Comment by Twaha-Rahman** [comment]
> Hey @Twaha-Rahman, it looks like this will run all the specs 3 times on pull requests. Do you know if it's possible to do a single run on a PR while keeping the ability to load balance the specs when we're recording?

Yup, it is possible. I'm currently having trouble figuring out and testing this parallelization in this PR. If a had access to the Cypress Dashboard, it would have been quite helpful.

I'll need to create 2 more PRs to address two more problems before we merge this parallelization PR -

1. Persist host's DB state with MongoMemoryServer as [discussed here](https://github.com/freeCodeCamp/freeCodeCamp/issues/39574#issuecomment-693319480).
2. Remove any chances of race condition by giving each test runner container their own DB and reset DB before running each test

**Comment by ojeytonwilliams** [comment]
Hey @Twaha-Rahman is there anything we can help with?

**Comment by Twaha-Rahman** [comment]
> Hey @Twaha-Rahman is there anything we can help with?

This was the old PR. I'm closing this in favor of the new PR I'll be doing tomorrow.

**Comment by ojeytonwilliams** [comment]
Oh, fair enough.  It's fine if you want to keep using existing PRs, though.  If it's a complete re-write you can just force push the new commits.  Whatever works, though.

**Pull request closed without merging**
