### PR TITLE
fix(curriculum): typo in Project Euler Problem

### LINKED ISSUE #42536: Typo in Project Euler Problem 349 - Langton's ant
Hi! 

A user on the forum brought up a typo in one of the Project Euler challenges.
https://forum.freecodecamp.org/t/error-in-problem-description/464703

In the last sentence it should be 10 to the power of 18. 
Not 1018. 

Last sentence from the FCC challenge.
Screen Shot 2021-06-16 at 9 17 22 AM

**Affected page**
https://www.freecodecamp.org/learn/coding-interview-prep/project-euler/problem-349-langtons-ant

**Expected behavior**
Here is the correct sentence from [project euler.net- Langton's ant](https://projecteuler.net/problem=349)

Screen Shot 2021-06-16 at 9 18 52 AM

### PR DESCRIPTION
**Pull request by lazy-geek**
Checklist:

- [x] I have read [freeCodeCamp's contribution guidelines](https://contribute.freecodecamp.org).
- [x] My pull request has a descriptive title (not a vague title like `Update index.md`)
- [x] My pull request targets the `main` branch of freeCodeCamp.
- [x] I have tested these changes either locally on my machine, or GitPod.

Closes #42536

### CODE REVIEW

**Comment by lazy-geek** [comment]
@raisedadead can you review this?

**Comment by raisedadead** [comment]
Hi,

Someone will eventually review this. We request and thank you for your patience meanwhile. You are welcome to work on other open issues, or hang out on our community forum and chat rooms.

Happy contributing.

**Review by gikf — APPROVED** [review]
LGTM :+1:

**Review by Sembauke — APPROVED** [review]
Hey @lazy-geek,

Thank you for working on this issue 😄 

We hope to see more of you in the future

Stay safe and happy contributing 🥇

**Pull request merged**
