### PR TITLE
Consistency Update for label and input elements for last lessons

### PR DESCRIPTION
**Pull request by limonkufu**
- [x] I have read [freeCodeCamp's contribution guidelines](https://github.com/freeCodeCamp/freeCodeCamp/blob/master/CONTRIBUTING.md).
- [x] My pull request has a descriptive title (not a vague title like `Update index.md`)
- [x] My pull request targets the `master` branch of freeCodeCamp.
- [x] None of my changes are plagiarized from another source without proper attribution.
- [x] All the files I changed are in the same world language (for example: only English changes, or only Chinese changes, etc.)
- [x] My changes do not use shortened URLs or affiliate links.

### CODE REVIEW

**Comment by RandellDawson** [comment]
I do not believe this is necessary since the input is nested within the label element.

**Comment by Limonkufu** [comment]
> 
> 
> I do not believe this is necessary since the input is nested within the label element.

In the previous lessons it is said as best practice and the solutions include this so I thought it should be consistent with the former lessons. On the other hand, are you saying this is unnecessary since input is nested within label? If this is the case then previous lessons should be updated.

**Comment by RandellDawson** [comment]
Which previous lessons specifically are you referring?

**Comment by Limonkufu** [comment]
@RandellDawson https://learn.freecodecamp.org/responsive-web-design/basic-html-and-html5/create-a-set-of-checkboxes and https://learn.freecodecamp.org/responsive-web-design/basic-html-and-html5/create-a-set-of-radio-buttons mention

**Review by jonathan-grah — APPROVED** [review]
## LGTM 👍 
Congratulations on your first pull request @Limonkufu 🎉 ❤️ 
I think we can merge this as it does no harm, and is seen as best practice.

**Pull request merged**
