### PR TITLE
fix(learn): added regex for comma separated const declarations in redux challenge

### LINKED ISSUE #42460: Comma-separated const declarations not accepted (Redux)
**Affected page**
https://www.freecodecamp.org/learn/front-end-libraries/redux/use-const-for-action-types

**Expected behavior**
The following two code snippets are both correct and semantically equivalent js, but one passes all tests and the other does not. Either both should pass or both should fail.

Passes:
```
const LOGIN = `LOGIN`;
const LOGOUT = `LOGOUT`;
```
Fails:
```
const LOGIN = `LOGIN`
    , LOGOUT = `LOGOUT`;
```

Declaring multiple comma separated const's fails this test:
```LOGIN and LOGOUT should be declared as const values and should be assigned strings of LOGIN and LOGOUT.```

**Your code**
Copy and paste the code from the editor that you used in between the back-ticks below:

```
const LOGIN = 'LOGIN'
    , LOGOUT = 'LOGOUT';

const defaultState = {
  authenticated: false
};

const authReducer = (state = defaultState, action) => {

  switch (action.type) {
    case LOGIN: 
      return {
        authenticated: true
      }
    case LOGOUT: 
      return {
        authenticated: false
      }

    default:
      return state;

  }

};

const store = Redux.createStore(authReducer);

const loginUser = () => {
  return {
    type: LOGIN
  }
};

const logoutUser = () => {
  return {
    type: LOGOUT
  }
};
```

**System (please complete the following information):**
 - Browser: Firefox 90.0b6

### PR DESCRIPTION
**Pull request by patlehmann1**
Checklist:

- [X] I have read [freeCodeCamp's contribution guidelines](https://contribute.freecodecamp.org).
- [X] My pull request has a descriptive title (not a vague title like `Update index.md`)
- [X] My pull request targets the `main` branch of freeCodeCamp.
- [X] I have tested these changes either locally on my machine, or GitPod.

Closes #42460

### CODE REVIEW

**Review by ojeytonwilliams — APPROVED** [review]
While the regex lets you enter `const LOGIN = 'LOGIN', LOGIN = 'LOGIN';` the editor realises this is a syntax error and stops the tests from running.

LGTM :+1:

**Review by ShaunSHamilton — APPROVED** [review]
This LGTM 👍

**Comment by ShaunSHamilton** [comment]
Thank you, for your contribution to the page! 👍
We are happy to accept these changes, and look forward to future contributions. 🎉

**Comment by SamIrvin17** [comment]
@ojeytonwilliams the regex actually does not allow the 
'const LOGIN = 'LOGIN', LOGIN = 'LOGIN';'

if you look in the regex it uses a negative lookahead with the selection of capture group 1 to ensure the user does not enter the same 'LOGIN' or 'LOGOUT' twice.

**Pull request merged**
