### PR TITLE
Updated Model to the latest bootstrap v 4.1

### PR DESCRIPTION
**Pull request by vardanabhanot**
Changed the example code to that of the latest version of bootstrap that is v 4.1 and added the .fade  class and changed or removed the old links.

- [x] I have read [freeCodeCamp's contribution guidelines](https://github.com/freeCodeCamp/freeCodeCamp/blob/master/CONTRIBUTING.md).
- [x] My pull request has a descriptive title (not a vague title like `Update index.md`)
- [x] My pull request targets the `master` branch of freeCodeCamp.
- [x] None of my changes are plagiarized from another source without proper attribution.
- [x] My article does not contain shortened URLs or affiliate links.

If your pull request closes a GitHub issue, replace the XXXXX below with the issue number.

Closes #XXXXX

### CODE REVIEW

**Comment by thecodingaviator** [comment]
Since there has been no activity on this PR, I'm marking this as stale and closing it.
I'm also closing it since the latest version of Bootstrap is now 4.3.

Look forward to more contributions from you in the future!

**Review by thecodingaviator — CHANGES_REQUESTED** [review]
Please change the Bootstrap version to the latest i.e. 4.3 and the corresponding code too

**Comment by RandellDawson** [comment]
@thecodingaviator This one has gone stale.

**Comment by thecodingaviator** [comment]
Hi @VardanBhanot 

As there has been no response from your end for a while, we are closing this PR.

Feel free to request this PR to be reopened, if you still wish to make the changes you originally added.  Also, remember to update your fork, so you have the latest version of master in case it has changed significantly.

Happy Coding! ✈️

**Pull request closed without merging**
