### PR TITLE
Fix/remove property references and update tests

### PR DESCRIPTION
**Pull request by lasjorg**
- [x] I have read [freeCodeCamp's contribution guidelines](https://github.com/freeCodeCamp/freeCodeCamp/blob/master/CONTRIBUTING.md).
- [x] My pull request has a descriptive title (not a vague title like `Update index.md`)
- [x] My pull request targets the `master` branch of freeCodeCamp.
- [x] None of my changes are plagiarized from another source without proper attribution.
- [x] All the files I changed are in the same world language (for example: only English changes, or only Chinese changes, etc.)
- [x] My changes do not use shortened URLs or affiliate links.

New PR, the original is here https://github.com/freeCodeCamp/freeCodeCamp/pull/34797

### CODE REVIEW

**Comment by RandellDawson** [comment]
@lasjorg I resolved the merge conflict for you.

**Comment by lasjorg** [comment]
Awesome, thanks.

**Comment by RandellDawson** [comment]
@lasjorg Hope you don't mind, but I saw an error in the regex I proposed for the 3rd test which would have still allowed something like:
```
function Bird() {
  var weight = 15;
  this.getWeight = function () { return 15; };
}
```

It was missing an extra pair of parentheses.  I have now tested my addition and it works fine now and correctly fails when 15 hard-coded as the return value.

**Review by RandellDawson — APPROVED** [review]

**Comment by RandellDawson** [comment]
@ezioda004, @Manish-Giri Would one of you take a look at the original issue referenced and validate this PR now fixes the issue?

**Review by Manish-Giri — APPROVED** [review]
@lasjorg @RandellDawson I tested this locally and it looks all good to me. Thank You for your contributions 👍

**Pull request merged**
