### PR TITLE
Docs - Romanian translation corrections were made. Previous translation was inaccurate

### PR DESCRIPTION
**Pull request by rebelliovs**
- [X] I have read [freeCodeCamp's contribution guidelines](https://github.com/freeCodeCamp/freeCodeCamp/blob/master/CONTRIBUTING.md).
- [X] My pull request has a descriptive title (not a vague title like `Update index.md`)
- [X] My pull request targets the `master` branch of freeCodeCamp.
- [X] None of my changes are plagiarized from another source without proper attribution.
- [X] My article does not contain shortened URLs or affiliate links.

If your pull request closes a GitHub issue, replace the XXXXX below with the issue number.

Closes #XXXXX

### CODE REVIEW

**Review by RandellDawson — CHANGES_REQUESTED** [review]
@rebelliovs The [English version of the README.md](https://github.com/freeCodeCamp/freeCodeCamp/blob/master/README.md)has changed since you first created this.  Can you please review it and update this PR to reflect the latest version?  It could be that some of your original changes are no longer needed.

Thank you

**Comment by rebelliovs** [comment]
@RandellDawson from what I've seen most of the English version of the README.md has changed, and it no longer corresponds with any of the previous versions there are for the Romanian README.md; The corrections I made back in October concern the grammatical aspect of the Romanian version that was published, since it was a poor translation, most likely done using Google.

I'd advise the deletion of the current file, or if you want to keep it, accepting the grammatical corrections; However, as said, it is not a translation of the CURRENT English README.md. (I'd translate this myself, but I do not have the time at the moment)

**Comment by RandellDawson** [comment]
@rebelliovs Since you do not have the time currently, are you OK with us closing this PR?  You can always create a new PR at a later date with a complete translation.

**Comment by rebelliovs** [comment]
@RandellDawson feel free to close it.

**Pull request closed without merging**
