### PR TITLE
fix(curriculum): clarify exercise tracker

### LINKED ISSUE #40405: Flesh-Out Exercise Tracker User Stories and Typo
In order to avoid common confusion with this project, I suggest we add something along the lines of:

```typescript
interface Exercise {
  description: string,
  duration: number,
  date: Date, // Specifically: toDateString (date portion of Date object
}

interface NewUser {
  _id: string,
  username: string,
}

interface Log {
  count: number,
  log: Exercise[],
}

```

I expect this to be added to the description of the challenge. Something to that extent.

---

Also, there is a small typo, which can be easily fixed: [from this forum post](https://forum.freecodecamp.org/t/tiny-typo-in-exercise-tracker-challenge/443740)
You can POST to /api/exercise/new-user with form data username to create a new user. The returned response will be an object with username and _id properties.

You can make a GET request to :point_right: api/exercise/users to get an array of all users. Each element in the array is an object containing a user’s username and _id .

You can make a GET request to /api/exercise/log with […]

### PR DESCRIPTION
**Pull request by naomi-lgbt**
Checklist:

- [X] I have read [freeCodeCamp's contribution guidelines](https://contribute.freecodecamp.org).
- [X] My pull request has a descriptive title (not a vague title like `Update index.md`)
- [X] My pull request targets the `main` branch of freeCodeCamp.
- [X] I have tested these changes either locally on my machine, or GitPod.

Closes #40405

### CODE REVIEW

**Review by ShaunSHamilton — DISMISSED** [review]
This LGTM 👍 

---

I just had the thought, it would probably be better to just split up the user stories (still backwards-compatible). Something like:

**Original**
> You can make a `GET` request to `/api/users/:_id/logs` to retrieve a full exercise log of any user. The returned response will be the user object with a log array of all the exercises added. Each log item has the `description`, `duration`, and `date` properties.

**Replacements**
> You can make a `GET` request to `/api/users/:_id/logs` to retrieve a full exercise log of any user.

- Tests for route existence...mostly.

> A `GET` request to `/api/users/:_id/logs` will return the user object with a log array of all the exercises added.

> A `GET` request to `/api/users/:_id/logs` returns a log item with the description, duration, and date properties.

- Test for existence...

> The `GET /api/users/:_id/logs` route `log` has a an object with `description` as a string.

> The `GET /api/users/:_id/logs` route `log` has a an object with `duration` as a number.

> The `GET /api/users/:_id/logs` route `log` has a an object with `date` as a string using the _dateString_ format of the `Date` API.

Thoughts?

**Comment by nhcarrigan** [comment]
That would definitely make things easier to debug when submitting the project - will push a commit to do this

**Comment by nhcarrigan** [comment]
Okay @ShaunSHamilton I went ahead and split up the tests. I tweaked the verbiage a bit so it would read more naturally, let me know what you think.

Unfortunately this *does* result in a lot of extra calls to the camper's project - if we don't want that, I can drop the commit and keep the tests as is.

**Comment by ShaunSHamilton** [comment]
@nhcarrigan Sorry, but I think we should drop the previous commit. This PR was fine as is, and resolves the issue.

For a future PR, and/or for future projects/tests, I think we should split up the tests as you did. The reason not to use your latest commit is because it does not actually close the issue - one or more other tests would need to be split up likewise.

**Review by gikf — APPROVED** [review]
Looks good :+1:

**Review by Sembauke — APPROVED** [review]

**Pull request merged**
