### PR TITLE
feat(client, i18n): Updating a translation in motivation.json - typo in line 170

### PR DESCRIPTION
**Pull request by DanielRosa74**
Checklist:

- [X] I have read [freeCodeCamp's contribution guidelines](https://contribute.freecodecamp.org).
- [X] My pull request has a descriptive title (not a vague title like `Update index.md`)
- [X] My pull request targets the `main` branch of freeCodeCamp.
- [X] I have tested these changes either locally on my machine, or GitPod.

Quick fix on a motivational quote.

### CODE REVIEW

**Comment by Sembauke** [comment]
Hey @DanielRosa74,

I do not know why our GitHub bot did not catch this but we do not accept translations through GitHub anymore.
You can log in and resolve the issue through Crowdin:

https://freecodecamp.crowdin.com/u/projects/2

**Comment by DanielRosa74** [comment]
Hi, @Sembauke . I think it's because this file (in fact, all the json files) , specifically, is not in Crowdin. So translations for it still go through here. Could this be reopened?
Regards.

**Comment by Sembauke** [comment]
Hey @DanielRosa74,

Apparently, I missed something about translating motivational quotes, sorry about that!

Have a great day!

**Review by Sembauke — APPROVED** [review]

**Review by majestic-owl448 — APPROVED** [review]
LGTM!

**Review by ShaunSHamilton — APPROVED** [review]

**Pull request merged**
