### PR TITLE
refactor(client): clean landing page CSS file

### PR DESCRIPTION
**Pull request by Sboonny**
Checklist:

- [x] I have read and followed the [contribution guidelines](https://contribute.freecodecamp.org).
- [x] I have read and followed the [how to open a pull request guide](https://contribute.freecodecamp.org/#/how-to-open-a-pull-request).
- [x] My pull request targets the `main` branch of freeCodeCamp.
- [x] I have tested these changes either locally on my machine, or GitPod.

In the devtools of

<s>there is error message warning about the using lazy load, in the devtools of https://www.freecodecamp.org

this aims to clean it, and clean extra styles.

image</s>

The eager loading image was mistake from my part, the new changes about cleaning the CSS file

### CODE REVIEW

**Comment by Sboonny** [comment]
I will clean landing.css in another PR, and because I want to add `section` elements with aria-labelledby accessibility, and I don't want this to be too big of change

**Comment by naomi-lgbt** [comment]
image

Are we sure this is correct? I'd think we would want to keep lazy-load on the images (which is a common best practise, from my understanding), and fix the preloading on the fonts?

Are you seeing different errors than I am?

**Comment by Sboonny** [comment]
The reason that lazy loading an image is best practice, is to increase the performance and delay it's rendering until user get the whole data.

But the

**Comment by naomi-lgbt** [comment]
> But as pointed out by the browser in the error, delaying loading an image that is already in viewport isn't optimal way to use the attribute, and don't provide performance enhancement.

That's not what I'm seeing in the browser errors though? Every one of these warnings is for a font file.

**Comment by Sboonny** [comment]
Are you seeing different errors than I am?

Yes I am aware of the font issue and I am researching the ways to sort it

**Comment by naomi-lgbt** [comment]
Right, so I'm back to not understanding the need for this change.

The browser isn't warning us about lazy-loading images, but about pre-loading fonts. So we should continue to lazy-load our images, IMHO.

**Comment by Sboonny** [comment]
> That's not what I'm seeing in the browser errors though? Every one of these warnings is for a font file.

I have copied the wrong error 🤦‍♂️

**Comment by Sboonny** [comment]
Here is the correct image and error message in chromium browser

image

[Intervention] Images loaded lazily and replaced with placeholders. Load events are deferred. See https://go.microsoft.com/fwlink/?linkid=2048113

**Comment by naomi-lgbt** [comment]
Is your browser up-to-date?

That message appears to come from a Chromium flag that enabled experimental native lazy-loading, which is now no longer experimental. My understanding is that this message would appear when an image was *not* set to load lazily, and Chrome applied lazy loading anyway.

**Comment by Sboonny** [comment]
Let me check this early morning 👍🤔

**Comment by Sboonny** [comment]
Yeab, it was lower than 111.0.1661.41, feels bad man, I was so proud of the faster loading, and most likely it's because I reduce the imports 😥

**Comment by ahmadabdolsaheb** [comment]
LGMT for the css clean up

**Review by ahmaxed — APPROVED** [review]

**Review by raisedadead — APPROVED** [review]

**Pull request merged**
