### PR TITLE
Update Description of Stern-Brocot Challenge

### LINKED ISSUE #40684: Rosetta Code - Stern-Brocot sequence - tests don't match task in challenge description
**Describe your problem and how to reproduce it:**
Challenge description gives slightly different task, to what needs to be done to pass tests.

Challenge is about [Stern-Brocot sequence](https://oeis.org/A002487), which looks at the beginning like (skipping zero at start):
```
1, 1, 2, 1, 3, 2, 3, 1, 4, 3, 5, 2, 5, 3, 4, 1, 5, 4, 7, 3
```
Challenge description asks to create function returning **n-th member** of the sequence. 

However expected values in tests, and sample solution don't match that.
>sternBrocot(2) should return 3.
sternBrocot(3) should return 5.
sternBrocot(5) should return 11.
sternBrocot(7) should return 19.
sternBrocot(10) should return 39.

Function matching tests would be one returning at **which position** in sequence number is encountered for first time.

Original challenge on Rosetta Code - [Stern-Brocot sequence](https://rosettacode.org/wiki/Stern-Brocot_sequence) have both these variations as a part of task, so that's most likely how it sneaked in.

**Add a Link to the page with the problem:**
https://www.freecodecamp.org/learn/coding-interview-prep/rosetta-code/stern-brocot-sequence
https://github.com/freeCodeCamp/freeCodeCamp/blob/master/curriculum/challenges/english/10-coding-interview-prep/rosetta-code/stern-brocot-sequence.md

### PR DESCRIPTION
**Pull request by jeremylt**
Checklist:

- [x] I have read [freeCodeCamp's contribution guidelines](https://contribute.freecodecamp.org).
- [x] My pull request has a descriptive title (not a vague title like `Update index.md`)
- [x] My pull request targets the `master` branch of freeCodeCamp.
- [x] All the files I changed are in the same world language, for example: only English changes, or only Chinese changes, etc.

Closes #40684

Perhaps we should also say the sequence is 1-indexed?

### CODE REVIEW

**Comment by nhcarrigan** [comment]
> Perhaps we should also say the sequence is 1-indexed?

I would be in favour of adding this note, if the tests expect 1-indexed based results.

**Review by naomi-lgbt — APPROVED** [review]
LGTM~! 🥳 

Thank you for your pull request! We look forward to additional contributions!

Please note that we are currently in a code freeze and are not merging PRs to curriculum files.

**Review by RandellDawson — APPROVED** [review]
LGTM

**Comment by RandellDawson** [comment]
Thank you for your contribution to the page! 👍
We're happy to accept these changes, and look forward to future contributions. 🎉

**Pull request merged**
