### PR TITLE
French translation for Gear up for Success

### LINKED ISSUE #7632: French translation of Gear up for Success
- [x] Join our LinkedIn Alumni Network 
- [x] Join our Subreddit 
- [x] Read Coding News on our Medium Publication 
- [x] Watch us Code Live on Twitch.tv
- [x] Commit to a Goal and a Nonprofit

### PR DESCRIPTION
**Pull request by elazzabi**
Closes #7632

### CODE REVIEW

**Comment by theflametrooper** [comment]
Any update on this @elazzabi ? We need someone to verify your translation before we merge.

**Comment by elazzabi** [comment]
@theflametrooper I asked on the FrenchRoom, still no response

**Comment by BerkeleyTrue** [comment]
If no one objects after a week we should merge translation. Otherwise we'll have to wait a long time. I'd rather see them merged in and corrected later.

**Comment by theflametrooper** [comment]
I'm merging this pr as it's been a week since @elazzabi originally asked in the chat rooms. Thanks @elazzabi

**Pull request merged**
