### PR TITLE
fix(learn): Remove isHidden from frontmatter for steps 87-94 of Cafe Menu project

### PR DESCRIPTION
**Pull request by RandellDawson**
Checklist:

- [x] I have read [freeCodeCamp's contribution guidelines](https://contribute.freecodecamp.org).
- [x] My pull request has a descriptive title (not a vague title like `Update index.md`)
- [x] My pull request targets the `master` branch of freeCodeCamp.
- [x] All the files I changed are in the same world language, for example: only English changes, or only Chinese changes, etc.

This PR removes the `isHidden` key from the challenge file frontmatter for steps 87-94 of the Cafe Menu project.  The reason they were even present (after a recent purge) was because the branch that the last changes were made on still had a previous version of the step helper tools which added this key by default.  The current `master` branch has the corrected version of the tool, so this should not happen again.

### CODE REVIEW

**Comment by RandellDawson** [comment]
@moT01 Once the tests successfully complete on this PR, you can merge it.

**Review by moT01 — DISMISSED** [review]
LGTM 🎉  Looks like there's still some issues around the tests.

**Comment by moT01** [comment]
Here's the node error `Uncaught Error: Editable region not closed in file /home/runner/work/freeCodeCamp/freeCodeCamp/curriculum/challenges/english/01-responsive-web-design/basic-css-cafe-menu/part-069.md`

**Comment by RandellDawson** [comment]
@moT01 All tests pass now.

**Review by ojeytonwilliams — APPROVED** [review]
LGTM :+1:

**Review by moT01 — APPROVED** [review]
👍 🎉 🚀

**Pull request merged**
