### PR TITLE
fix: Specify indent_size = 2 globally in .editorconfig.

### PR DESCRIPTION
**Pull request by KartikSoneji**
Checklist:

- [x] I have read [freeCodeCamp's contribution guidelines](https://contribute.freecodecamp.org).
- [x] My pull request has a descriptive title (not a vague title like `Update index.md`)
- [x] My pull request targets the `master` branch of freeCodeCamp.
- [x] All the files I changed are in the same world language, for example: only English changes, or only Chinese changes, etc.

Closes #XXXXX

Most editors (VSCode, Atom, etc.) default to 4 spaces per indent.
fcc uses 2 spaces per indent.
eslint does enforce this, but the editorconfig should also reflect the preference.

### CODE REVIEW

**Comment by ojeytonwilliams** [comment]
Hey @KartikSoneji thanks for pointing this out.  It doesn't look like `.editorconfig` is used any more, though - not by VSCode, anyway.

Could you confirm/deny?

**Comment by KartikSoneji** [comment]
Hi @ojeytonwilliams 
I don't know if VSCode respects .editorconfig by default, but there is [an extension](https://marketplace.visualstudio.com/items?itemName=EditorConfig.EditorConfig) for that.
GitPod **does** respect .editorconfig, so it might be useful for those using it.

.editorconfig seems to be the best place for style decisions such as this.
From https://editorconfig.org/ :
> EditorConfig helps maintain consistent coding styles for multiple developers working on the same project across various editors and IDEs.

**Comment by ojeytonwilliams** [comment]
Well, as it stands, eslint + prettier are responsible for making sure that the code style is consistent across editors.  I'm not sure it's a good idea to split that responsibility up, as that just makes it harder to understand what's going on.

Are there popular editors that do not support eslint?  If most do, I think it would be easier just to use one tool.

**Comment by KartikSoneji** [comment]
OK, try this:
- Click the "Open in GitPod" button.
- Open any file in the editor.
- Notice the "Spaces: 4" in the bottom right corner.
- Press the <kbd>Tab</kbd> key.

What happens?
4 Spaces are inserted.

- Add `indent_size = 2` to `.editorconfig`:
- Open a new file in the editor (important).
- Notice that "Spaces: 4" has changed to "Spaces: 2".
- Press <kbd>Tab</kbd> again.

What happens now?
2 Spaces are inserted, as should be.

**Comment by KartikSoneji** [comment]
eslint and prettier format the code AFTER it has been edited.
It will be a much smoother experience if the editor itself can adjust some settings (like indent_size) to the correct amount.

**Review by ojeytonwilliams — APPROVED** [review]
Ah, thanks for bearing with me.  I thought the style was being set in two places (which we don't want), but all this would do is align the editor's default settings with what eslint is going to apply.

I've checked it out locally and it all looks good to me!

**Comment by KartikSoneji** [comment]
No issues :)

**Pull request merged**
