### PR TITLE
fix: order imports and remove circular dependencies

### PR DESCRIPTION
**Pull request by ojeytonwilliams**
The goal here was just to simplify the linting/formatting and order the the imports so that webpack would know how to order the css imports.   This has worked, but we should audit the css, since the declaration order has probably changed.

However, reordering the imports showed that several modules had circular dependencies since they broke when the order changed.  To fix this I separated out the offending code (types for actions) to flatten out the dependencies.

This did not fix `redux/settings` however, since there was a missing type, `updateUserFlagComplete`.  I don't know how everything functioned without it, but I created it anyway.

### CODE REVIEW

**Comment by ahmadabdolsaheb** [comment]
I didn't notice any inconsistencies in the UI. I am still investigating the action.

**Comment by ahmadabdolsaheb** [comment]
So we you create an asyc type, the complete and error versions get created automatically.

https://github.com/freeCodeCamp/freeCodeCamp/blob/e59ad6ebda1d92de58cb55e230f9e1aa130c059b/client%2Fsrc%2Futils%2FcreateTypes.js#L11-L15

**Comment by ojeytonwilliams** [comment]
That's interesting, thanks Ahmad.  It explains why it wasn't completely broken!  I will need to look into why the tests started failing, though.

**Comment by ojeytonwilliams** [comment]
@ahmadabdolsaheb mystery solved. You were spot on - there was no need to add `updateUserFlagComplete`.  The reason the test was failing was another circular dependency issue: `settingsTypes` was undefined.

**Comment by raisedadead** [comment]
Do we want to give this one more go?

**Comment by ojeytonwilliams** [comment]
Sure.  I'll take a stab at it tomorrow.

We might need a small freeze, though.

**Comment by raisedadead** [comment]
Sure.

**Comment by ojeytonwilliams** [comment]
@raisedadead I removed the prettier changes and brought everything up-to-date.  Ironically, ordering the inputs was not enough to get rid of these warnings:

```
chunk commons [mini-css-extract-plugin]
Conflicting order. Following module has been added:
 * css ./node_modules/css-loader/dist/cjs.js??ruleSet[1].rules[9].oneOf[1].use[1]!./node_modules/gatsby-plugin-postcss/node_modules/postcss-loader/dist/cjs.js??ruleSet[1].rules[9].oneOf[1].use[2]!./src/t
emplates/Challenges/components/test-suite.css
despite it was not able to fulfill desired ordering with these modules:
 * css ./node_modules/css-loader/dist/cjs.js??ruleSet[1].rules[9].oneOf[1].use[1]!./node_modules/gatsby-plugin-postcss/node_modules/postcss-loader/dist/cjs.js??ruleSet[1].rules[9].oneOf[1].use[2]!./src/t
emplates/Challenges/components/challenge-description.css
   - couldn't fulfill desired order of chunk group(s) component---src-templates-challenges-projects-backend-show-tsx
   - while fulfilling desired order of chunk group(s) component---src-templates-challenges-classic-show-tsx
 * css ./node_modules/css-loader/dist/cjs.js??ruleSet[1].rules[9].oneOf[1].use[1]!./node_modules/gatsby-plugin-postcss/node_modules/postcss-loader/dist/cjs.js??ruleSet[1].rules[9].oneOf[1].use[2]!./node_
modules/prismjs/themes/prism.css
   - couldn't fulfill desired order of chunk group(s) component---src-templates-challenges-projects-backend-show-tsx
   - while fulfilling desired order of chunk group(s) component---src-templates-challenges-classic-show-tsx
 * css ./node_modules/css-loader/dist/cjs.js??ruleSet[1].rules[9].oneOf[1].use[1]!./node_modules/gatsby-plugin-postcss/node_modules/postcss-loader/dist/cjs.js??ruleSet[1].rules[9].oneOf[1].use[2]!./node_
modules/prismjs/plugins/line-numbers/prism-line-numbers.css
   - couldn't fulfill desired order of chunk group(s) component---src-templates-challenges-projects-backend-show-tsx
   - while fulfilling desired order of chunk group(s) component---src-templates-challenges-classic-show-tsx
```

because of nested imports.  That's why I changed `classic/Show.tsx` slightly, so that it's closer to the other `Show.tsx`s as far as imports are concerned.

**Comment by nhcarrigan** [comment]
There's a *lot* less noise when I run the development build now, but I do get this:

image

**Review by naomi-lgbt — DISMISSED** [review]
Despite that warning, everything seems to look good locally. 🙂

**Comment by ojeytonwilliams** [comment]
Huh.  It's weird that we *don't* have that rule.  Let me see about adding that and fixing the issue.

**Review by naomi-lgbt — APPROVED** [review]
All better!

I still get this one, but I think this is actual babel and not us.
image

**Comment by ojeytonwilliams** [comment]
It's been around for a while, I think, https://github.com/freeCodeCamp/freeCodeCamp/runs/3204052148?check_suite_focus=true#step:9:221 and doesn't seem to be breaking anything

**Review by ahmaxed — APPROVED** [review]
Other than what Nick said, LGMT.

**Review by moT01 — APPROVED** [review]
Well, I looked this over and tested it pretty thoroughly - didn't find any issue. LGTM 👍

**Pull request merged**
