### PR TITLE
chore(i18n,learn): processed translations

### PR DESCRIPTION
**Pull request by camperbot**
This PR was opened auto-magically by Crowdin.

### CODE REVIEW

**Comment by ieahleen** [comment]
@naomi-lgbt could you maybe restart the crowdin upload process? the missing files are not yet on crowdin

**Comment by naomi-lgbt** [comment]
Done.

__
[sema-logo](https://semasoftware.com/gh) &nbsp;**Summary:** :ok_hand: This code looks good&nbsp; | &nbsp;**Tags:** Efficient

**Review by DanielRosa74 — DISMISSED** [review]
LGTM (Portuguese)

**Review by naomi-lgbt — APPROVED** [review]
@ieahleen it looks like the missing challenge file has been translated

**Review by moT01 — APPROVED** [review]

**Pull request merged**
