### PR TITLE
doc: add information about editing branches

### PR DESCRIPTION
**Pull request by kartikgajjar7**
i added briefly explanation on topics :

1.Provide context for PR.
2.make it as smaller as possible.

let me know for any suggestions :)

Checklist:

- [x ] I have read [freeCodeCamp's contribution guidelines](https://contribute.freecodecamp.org).
- [x ] My pull request has a descriptive title (not a vague title like `Update index.md`)
- [x ] My pull request targets the `main` branch of freeCodeCamp.
- [x] I have tested these changes either locally on my machine, or GitPod.

Closes #XXXXX

### CODE REVIEW

**Comment by gikf** [comment]
This is copied from https://www.inrhythm.com/write-a-good-pull-request/

**Comment by Kartik2220** [comment]
> This is copied from https://www.inrhythm.com/write-a-good-pull-request/

it s not allowed

**Comment by Sboonny** [comment]
@Kartik2220 Yes, in general, using someone else content requires you to attribute them. 

But in freeCodeCamp, we require our content to be from our resources. Try to change it to news article from here https://www.freecodecamp.org/news/

**Comment by Kartik2220** [comment]
> @Kartik2220 Yes, in general, using someone else content requires you to attribute them.
> 
> But in freeCodeCamp, we require our content to be from our resources. Try to change it to news article from here https://www.freecodecamp.org/news/

REWIEW IT :)

**Comment by gikf** [comment]
Would you mind providing information why do you think this change is necessary?

**Comment by Kartik2220** [comment]
> Would you mind providing information why do you think this change is necessary?

i think it s good to put ways to do pr coz it all  about creating a pr :)

**Comment by gikf** [comment]
The change points just two of many ways how files can be changed. But that's a bit a side-note to the topic of page - opening pull request on GitHub.

**Comment by Kartik2220** [comment]
> The change points just two of many ways how files can be changed. But that's a bit a side-note to the topic of page - opening pull request on GitHub.

should i add more ways ?

**Comment by jeremylt** [comment]
I vote against this change - I don't think it adds anything useful to the reader; it only adds extra noise.

**Comment by naomi-lgbt** [comment]
Thank you for opening this pull request.

This is a standard message notifying you that we've reviewed your pull request and have decided not to merge it. We would welcome future pull requests from you.

Thank you and happy coding.


__
[sema-logo](https://semasoftware.com/gh) &nbsp;**Summary:** :hammer_and_wrench: This code needs a fix

**Pull request closed without merging**
