### PR TITLE
Add and Update test cases for "Bonfire: Check for Palindromes"

### PR DESCRIPTION
**Pull request by abhisekp**
Update tests for Bonfire Check for Palindromes
- Replace expect with assert
- Use strictEqual for checking equality of primitive.
  - consider `assert.deepEqual(1, true); // pass (undesirable)` vs `assert.strictEqual(1, true); // fail (expected)`
- Add message to assert test cases
- Minor modification to some existing test cases
- Add test for Bonfire Check for Palindromes
  - Checks unicode characters between "`Z`" (capital Z) and "`a`" (small a)"
    such as "`\`" (back slash) as punctuation for incorrect regex `/[^A-z]/` in palindrome solution.

### CODE REVIEW

**Comment by abhisekp** [comment]
@bugron @QuincyLarson please have a look as the messages of `assert` statements. Is it ok or should I modify it? Please suggest an example of the modification.

**Comment by abhisekp** [comment]
@ahstro Please look into this PR.

**Comment by ahstro** [comment]
@abhisekp The switch from except to assert and from deepEqual to `strictEqual` make a lot of sense to me, but since there is descriptive language involved - something which has to be judged subjectively by the owners - I'm not comfortable merging this.

**Comment by abhisekp** [comment]
@ahstro many campers write the replace statement as `str.replace(/[^A-z0-9]/g, "")`
But this wrong. This would also exclude the backslash character `\` from removal.
In the current production scenario, the challenge would pass with that wrong regex.

But due to my addition of another test in this PR, their regex will rightly fail and the challenge won't pass till they use the correct regex i.e. `/[^A-Za-z0-9]/g` or `/[\W_]/g`.

Campers must know that `/[^A-z0-9]/g` and `/[^A-Za-z0-9]/g` are not the same thing.

**Comment by ahstro** [comment]
@abhisekp Ah, okay, that makes sense. :) But like I said, I'll leave the merging to someone else though.

**Comment by QuincyLarson** [comment]
I agree with @abhisekp - we should ensure they use the right regex.

**Comment by QuincyLarson** [comment]
Please note that soon all tests will be "assert" style. I am completely refactoring the bonfire tests. But I will do so to make sure it reflects this. In the meantime, I will merge this improvement in.

**Pull request merged**
