### PR TITLE
added word-wrap less rule to .test-output

### LINKED ISSUE #11687: CSS issue with 13" (1280 x 659) viewports.
Device:

`Mozilla/5.0 (Macintosh; Intel Mac OS X 10_12_1) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/54.0.2840.98 Safari/537.36`

Viewport : 1280 x 659

Issue :
image

This almost made be believe that the url is actually `.co` instead of a `.com`

### PR DESCRIPTION
**Pull request by chiptus**
#### Pre-Submission Checklist

- [X] Your pull request targets the `staging` branch of FreeCodeCamp.
- [X] Branch starts with either `fix/`, `feature/`, or `translate/` (e.g. `fix/signin-issue`)
- [X] You have only one commit (if not, [squash](http://forum.freecodecamp.com/t/how-to-squash-multiple-commits-into-one-with-git/13231) them into one commit).
- [X] All new and existing tests pass the command `npm test`. Use `git commit --amend` to amend any fixes.

#### Type of Change

- [X] Small bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds new functionality)
- [ ] Breaking change (fix or feature that would change existing functionality)
- [ ] Add new translation (feature adding new translations)

#### Checklist:

- [X] Tested changes locally.
- [X] Closes currently open issue (replace XXXX with an issue no): Closes #11687 

#### Description

Added a rule to the .test-output class: word-wrap: break-word.
closes #11687

### CODE REVIEW

**Comment by QuincyLarson** [comment]
@chiptus can you double check that issue number? I couldn't find issue #11867

**Comment by texas2010** [comment]
that is odd. we don't have an issue #11867. it does not exist. because all issue is still in 117**. 

probably typo number

**Comment by texas2010** [comment]
oh okay. I found an issue. here issue is https://github.com/FreeCodeCamp/FreeCodeCamp/issues/11687

**Comment by chiptus** [comment]
Sorry, yes it was #11687

**Comment by raisedadead** [comment]
@chiptus great job.

#### :sparkles: :sparkles: **LGTM.** :sparkles: :sparkles: 

Thanks.

**Pull request merged**
