### PR TITLE
fix/Update CONTRIBUTING.md

### PR DESCRIPTION
**Pull request by learnitmyway**
I had a problem starting `mongod` on Mac OS and I would like to share how I solved it.

### CODE REVIEW

**Comment by raisedadead** [comment]
Hi @DeveloperDavo thanks a lot for the pull request.

The issue that you are mentioning is not specific to the freeCodeCamp codebase, but MongoDB setup.
I would highly recommend you mention this change/additional info on the platform-specific guide available on the forum (link is mentioned in the Contributing Guide under [prerequisites](https://github.com/freeCodeCamp/freeCodeCamp/blob/staging/CONTRIBUTING.md#prerequisites) )

**Comment by DeveloperDavo** [comment]
Thanks for getting back to me. Do you mean this [link](https://forum.freecodecamp.org/t/how-to-clone-and-setup-the-freecodecamp-website-on-a-mac/78450)? Unfortunately it has been closed and I can't add anything to it.

**Comment by raisedadead** [comment]
Hi @DeveloperDavo i have opened it up for you! Goodluck. Let me know when its done.

**Comment by DeveloperDavo** [comment]
Done :)

**Pull request closed without merging**
