### PR TITLE
Remove MDN link to slice() as it is not required in the challenge

### PR DESCRIPTION
**Pull request by prateekgoel**
#### Pre-Submission Checklist

- [ ] Your pull request targets the `staging` branch of freeCodeCamp.
- [x] Branch starts with either `fix/`, `feature/`, or `translate/` (e.g. `fix/signin-issue`)
- [x] You have only one commit (if not, [squash](http://forum.freecodecamp.org/t/how-to-squash-multiple-commits-into-one-with-git/13231) them into one commit).
- [ ] All new and existing tests pass the command `npm test`. Use `git commit --amend` to amend any fixes.

#### Type of Change

- [x] Small bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds new functionality)
- [ ] Breaking change (fix or feature that would change existing functionality)
- [ ] Add new translation (feature adding new translations)

#### Checklist:

- [ ] Tested changes locally.
- [ ] Closes currently open issue (replace XXXX with an issue no): Closes #XXXX

#### Description

Array.prototype.slice() is not used in the challenge "Diff Two Arrays". Removed MDN link to that.

### CODE REVIEW

**Comment by texas2010** [comment]
@prateekgoel Please add issue number in the Checklist. 
> Closes currently open issue (replace XXXX with an issue no): Closes #XXXX

**Comment by prateekgoel** [comment]
Hi @texas2010 , This doesn't belong to any issue. Should I create an issue for the same?

**Comment by BerkeleyTrue** [comment]
@prateekgoel The reason we ask to put issue numbers on PR's is so that a discussion about potential changes could be had. This prevents unnecessary work. Currently MDN links are not shown in the UI and have been phased out.

**Comment by prateekgoel** [comment]
Ok Thanks @BerkeleyTrue

**Pull request closed without merging**
