### PR TITLE
Added Solution

### PR DESCRIPTION
**Pull request by rabowlen**
Added a solution for the challenge's "Get a Hint" documentation.

- [X ] I have read [freeCodeCamp's contribution guidelines](https://github.com/freeCodeCamp/freeCodeCamp/blob/master/CONTRIBUTING.md).
- [X] My pull request has a descriptive title (not a vague title like `Update index.md`)
- [X ] My pull request targets the `master` branch of freeCodeCamp.
- [X] None of my changes are plagiarized from another source without proper attribution.
- [X] My article does not contain shortened URLs or affiliate links.

If your pull request closes a GitHub issue, replace the XXXXX below with the issue number.

Closes #XXXXX

### CODE REVIEW

**Comment by jonathan-grah** [comment]
### LGTM @rabowlen and congratulations on your first PR 😄🎉 

Thanks for contributing!

**Comment by rabowlen** [comment]
It passed the test. So is there a bug in the test?

**Comment by rabowlen** [comment]
> @jonathan-grah That solution doesn't seem correct, `Object.hasOwnProperty()` doesnt take more than 1 parameter.

It passed the test. So is there a bug in the test?

**Comment by ezioda004** [comment]
@rabowlen Yep, there are only 3 tests and it's passing as long as you have any of the properties in that method so `obj.hasOwnProperty("Alan");` passes as well, no need to check for other properties.
Will open an issue for this bug.

**Comment by jonathan-grah** [comment]
@ezioda004, yeah I should have looked at this in more depth, the tests would need improved.

**Comment by lms15** [comment]
In the class I set up hello world. not sure if I did it correctly
Mamie

**Pull request merged**
