### PR TITLE
Update post-data-with-the-javascript-xmlhttprequest-method.md instructions

### PR DESCRIPTION
**Pull request by jameshbush**
Uses common language to describe API data request. Improves clarity of instruction.

Checklist:

- [X] I have read [freeCodeCamp's contribution guidelines](https://contribute.freecodecamp.org).
- [X] My pull request has a descriptive title (not a vague title like `Update index.md`)
- [X] My pull request targets the `master` branch of freeCodeCamp.
- [X] All the files I changed are in the same world language, for example: only English changes, or only Chinese changes, etc.

Closes #XXXXX

### CODE REVIEW

**Review by RandellDawson — APPROVED** [review]
LGTM

**Review by Manish-Giri — APPROVED** [review]
LGTM

**Comment by jameshbush** [comment]
LGTM @raisedadead  can you take a final look?

**Comment by RandellDawson** [comment]
Congrats @jameshbush on your first pull request (PR)! 🎉

Thank you for your contribution to the page! 👍
We're happy to accept these changes, and look forward to future contributions. 📝

**Comment by jameshbush** [comment]
Welcome @RandellDawson 🎊🎉🕺

**Pull request merged**
