### PR TITLE
updated to suggest alternates to openweatherapi

### LINKED ISSUE #9145: Show the Local Weather - getCurrentPosition not working over http
#### Challenge Name
Show the Local Weather

https://www.freecodecamp.com/challenges/show-the-local-weather

#### Issue Description

getCurrentPosition does not work over http. I think that changing the url to codepen.io in that particular challenge would help others campers not thinking their code isn't correct.

#### Browser Information

* Browser Name, Version: Chrome 51.0.2704.84 m
* Operating System: Windows 10
* Mobile, Desktop, or Tablet: Desktop

#### Your Code

```js
// If relevant, paste all of your challenge code in here

```

#### Screenshot

image

### PR DESCRIPTION
**Pull request by edm00se**
#### Pre-Submission Checklist

- [x] Your pull request targets the `staging` branch of FreeCodeCamp.
- [ ] Branch starts with either `fix/`, `feature/`, or `translate/` (e.g. `fix/signin-issue`)
- [x] You have only one commit (if not, [squash](http://forum.freecodecamp.com/t/how-to-squash-multiple-commits-into-one-with-git/13231) them into one commit).
- [x] All new and existing tests pass the command `npm run test-challenges`. Use `git commit --amend` to amend any fixes.
#### Type of Change

- [x] Small bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds new functionality)
- [ ] Breaking change (fix or feature that would change existing functionality)
- [ ] Add new translation (feature adding new translations)
#### Checklist:

- [x] Tested changes locally.
- [ ] Closes currently open issue: Closes #9145
#### Description

The Open Weather Map API was not serving over HTTPS, leading to mixed content issues, since geolocation requires HTTPS. Forecast.io's API is also free, requires sign up, but up to 1k hits per day w/ no charge or card on file.

I'm (unsurprisingly) not the first person to notice this. Seems to intersect w/ #7853 and #9145.

### CODE REVIEW

**Comment by edm00se** [comment]
Curses, was trying to change my branch, managed to screw up the PR.

**Comment by edm00se** [comment]
In any case, I do have a [fix/weather-api-suggestion](https://github.com/edm00se/FreeCodeCamp/tree/fix/weather-api-suggestion) branch on my forked copy now. If there's a way of switching my base branch, I'm not seeing it. :-| I'll go review the contribution guidelines.

**Comment by atjonathan** [comment]
@edm00se you can't change your base branch. Please make a new PR using the new branch :smiley:

**Comment by edm00se** [comment]
I might have guessed. Thanks, I've opened PR #10341.

**Pull request closed without merging**
