### PR TITLE
fix typo in description

### LINKED ISSUE #4993: Typo in Waypoint: Use Hex Code for Specific Colors
Challenge [Waypoint: Use Hex Code for Specific Colors](http://www.freecodecamp.com/challenges/waypoint-use-hex-code-for-specific-colors) has an issue.
User Agent is: <code>Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/47.0.2526.73 Safari/537.36</code>.

The text "The word ```Hexademical``` can be broken down into the words hexa and decimal. " is wrong, must be ```Hexadecimal```

### PR DESCRIPTION
**Pull request by xjlim**
closes #4993

### CODE REVIEW

**Comment by ltegman** [comment]
Thanks for the PR! Please put `closes #4993` in the body or your PR so that Github will autoclose the issue when this PR is merged :smile:

**Comment by xjlim** [comment]
closes #4993

**Comment by ltegman** [comment]
@xjlim You need to edit the body of your main PR message using the pencil icon in the top right corner of the message.

**Comment by benschac** [comment]
Poo, is this issue closed?

**Comment by bugron** [comment]
@xjlim thanks, merged!

**Pull request merged**
