### PR TITLE
fix(curriculum): Remove videoUrl using old image srcs

### LINKED ISSUE #43624: Need to remove videos from HTML challenges using old image src url
For the HTML and CSS challenges, the src url for the image tag was recently changed. 

This is the old url
`src="https://bit.ly/fcc-relaxing-cat."`

This is the new one
`https://cdn.freecodecamp.org/curriculum/cat-photo-app/relaxing-cat.jpg`

We have campers using the old URL because they watched the video in the Get Help section.
For example,
[Forum post of user copying incorrect code from video](https://forum.freecodecamp.org/t/everything-is-correct-i-literally-copied-and-pasted-the-completed-code-from-the-how-to-video-and-it-still-wont-accept-it/479728)

The videos should be removed from these challenges:
[Add Images to Your Website](https://www.freecodecamp.org/learn/responsive-web-design/basic-html-and-html5/add-images-to-your-website)
[Size Your Images](https://www.freecodecamp.org/learn/responsive-web-design/basic-css/size-your-images)

Thanks!

### PR DESCRIPTION
**Pull request by dharmin**
Checklist:
  * [x]  I have read [freeCodeCamp's contribution guidelines](https://contribute.freecodecamp.org).
  * [x]  My pull request has a descriptive title (not a vague title like `Update index.md`) 
  * [x]  My pull request targets the `main` branch of freeCodeCamp.
  * [x]  All the files I changed are in the same world language, for example: only English changes, or only Chinese changes, etc.
 
Closes: #43624

This PR replace old url from the video to the new one from freecodecamp cdn.
Here's a list of the URLs that are being updated: 
  * https://bit.ly/fcc-relaxing-cat --> https://cdn.freecodecamp.org/curriculum/cat-photo-app/relaxing-cat.jpg
  * https://bit.ly/fcc-running-cats --> https://cdn.freecodecamp.org/curriculum/cat-photo-app/running-cats.jpg

### CODE REVIEW

**Comment by gikf** [comment]
Hey @dharmin 

Thank you for opening this pull request.

I'm afraid those are not the changes indented by linked issue. 
Only:
- https://github.com/freeCodeCamp/freeCodeCamp/blob/main/curriculum/challenges/english/01-responsive-web-design/basic-html-and-html5/add-images-to-your-website.md
- https://github.com/freeCodeCamp/freeCodeCamp/blob/main/curriculum/challenges/english/01-responsive-web-design/basic-css/size-your-images.md

Were supposed to be changed, by removing the scrimba `videoUrl`. No other files need to be edited. Files from other languages will be updated using the translation workflow.

Could you make changes that will reflect the intended changes from the issue?

Thank you and happy coding.

**Comment by dharmin** [comment]
@gikf 

Thanks for guiding me.

I've reverted my previous commit and removed the `videoUrl` from the two challenges.

Is it correct right? or I have to just remove the scrimba link with empty `videoUrl`?

**Comment by gikf** [comment]
@dharmin yes, `videoUrl` should be removed completely as you did. :+1:

**Review by gikf — APPROVED** [review]
LGTM :+1:

**Review by Nirajn2311 — APPROVED** [review]
LGTM 👍

**Comment by gikf** [comment]
Hi @dharmin. Congrats on your first pull request (PR)! 🎉

Thank you for your contribution to the page! 👍
We are happy to accept these changes and look forward to future contributions. 📝

**Pull request merged**
