### PR TITLE
feat(client/curriclum): fsd block layout

### PR DESCRIPTION
**Pull request by moT01**
This is an attempt to make the blocks look a little better on the superblock page. There's a long way to go, but it also should make it easier to make changes in the future.

It changes the existing `challenge-list` and `link` block layouts to `legacy-challenge-list` and `legacy-link` - and adds two new layouts of the original names. This is so I could make changes to the block layouts without affecting the existing layouts.

Extracts a few things from block.tsx into their own components.

Updates all the full stack meta.json files to include a blockLayout.

Some other misc changes might have snuck in there.

Checklist:

- [x] I have read and followed the [contribution guidelines](https://contribute.freecodecamp.org).
- [x] I have read and followed the [how to open a pull request guide](https://contribute.freecodecamp.org/how-to-open-a-pull-request/).
- [x] My pull request targets the `main` branch of freeCodeCamp.
- [x] I have tested these changes either locally on my machine, or GitPod.

Closes #XXXXX

### CODE REVIEW

**Comment by ahmaxed** [comment]
Here are some nitpicks:
- Could the block layout be derived from block type? we might have discussed this.
- The hover state on the tag makes it look clickable.
- We have not used boarder radios on anything purposefully so far. We can drop it until we implement it across learn.

**Review by ojeytonwilliams — APPROVED** [review]
Looks solid. As I said last time, it would be nice if `LegacyChallengeListBlock` etc. were promoted to components. Maybe next time we revisit this.

Also, it's quite surprising that clicking on the link blocks causes you to navigate to the lesson. They look very similar to the grid block, so you might expect them to expand. It might be more intuitive if the half with the description is a link. Not a big deal, mind.

**Comment by moT01** [comment]
Thanks for taking a look 🙂

> Could the block layout be derived from block type?

No. The block type determines the label. Sometimes the challenge layout is different for the same block type. For instance the RWD workshops show the grid cause of the steps, the RDB workshops show the link cause it's just one challenge that opens gitpod, but still a workshop.

> the hover state on the tag makes it look clickable.

I'm not convinced. Any suggestions?

<details><summary>demo</summary>

Oct-23-2024 09-43-49

</details>

**Review by ahmaxed — APPROVED** [review]
I must have altered the DOM from myside for the hover state.

**Pull request merged**
