### PR TITLE
chore(i18n,learn): processed translations

### PR DESCRIPTION
**Pull request by camperbot**
This PR was opened auto-magically by Crowdin.

### CODE REVIEW

**Review by DanielRosa74 — DISMISSED** [review]
LGTM (Portuguese)

**Review by DanielRosa74 — APPROVED** [review]
LGTM (Portuguese)

**Comment by ieahleen** [comment]
@DanielRosa74 you should make changes on crowdin, not here

**Review by DanielRosa74 — COMMENTED** [review]
LGTM (Portuguese)

**Comment by ieahleen** [comment]
@DanielRosa74 what's going on with this one? you deleted the branch but commented that it looks good?

**Comment by DanielRosa74** [comment]
Hey, @ieahleen . I deleted the branch and left it as it was, so just sent the LGTM to say I'll do the fixing on Crowdin. I hope this is ok.

**Pull request closed without merging**
