### PR TITLE
fix(curriculum): clear up confusion of array index example

### LINKED ISSUE #45572: Basic Javascrip - Access Array Data with Indexes Example is confusing.
## Affected page

https://www.freecodecamp.org/learn/javascript-algorithms-and-data-structures/basic-javascript/access-array-data-with-indexes

## Your code

The example, and example explanation are confusing here. Right now, array[0] is initialized to 50, and the second line is doing nothing, and the explanation says "array[0] is now 50, and data has the value 60.", where array[0] has always been 50. I think this is confusing, and maybe the second line in the example should change the value of array[0], and the explanation should say "array[0] is now [new value], and data has the value 60.". 

## Expected behavior

Example is not confusing.

## Screenshots
image

## System

- Device: Laptop
- OS: Windows 10
- Browser: Firefox
- Version: 98.0.2

### PR DESCRIPTION
**Pull request by sprajams**
Checklist:

- [x] I have read [freeCodeCamp's contribution guidelines](https://contribute.freecodecamp.org).
- [x] My pull request has a descriptive title (not a vague title like `Update index.md`)
- [x] My pull request targets the `main` branch of freeCodeCamp.
- [x] I have tested these changes either locally on my machine, or GitPod.

Closes #45572

### CODE REVIEW

**Review by naomi-lgbt — APPROVED** [review]
This looks good to me.

**Review by gikf — APPROVED** [review]
Looks good :+1:

**Comment by gikf** [comment]
Hi @sprajams. Congrats on your first pull request (PR)! 🎉

Thank you for your contribution to the page! 👍
We are happy to accept these changes and look forward to future contributions. 📝

**Comment by sprajams** [comment]
Hi @gikf, thank you for the feedback and I am very excited to continue contributing! 😄

**Pull request merged**
