### PR TITLE
fix: Replace Array.prototype.sort and update old isSorted method.

### LINKED ISSUE #39220: Test Error on "Implement Selection Sort"
**Describe your problem and how to reproduce it:**
The tests for this challenge require the user to NOT use the `.sort()` function. The particular testString that checks this uses a regex, but that regex will match an occurrence of the word `sort` (case-sensitive), so using a variable name such as `sortedArray` will cause this test case to fail erroneously.

**Add a Link to the page with the problem:**
[Implement Selection Sort challenge](https://www.freecodecamp.org/learn/coding-interview-prep/algorithms/implement-selection-sort)

**Tell us about your browser and operating system:**
* Browser Name: Chrome
* Browser Version:  83.0.4103.116
* Operating System: Windows 10 Home 1909

**If possible, add a screenshot here (you can drag and drop, png, jpg, gif, etc. in this box):**
Failing Code:
image
Passing Code: 
image
As a note, the code is not mine but was provided by a user when they requested debugging assistance.

### PR DESCRIPTION
**Pull request by KartikSoneji**
Checklist:

- [x] I have read [freeCodeCamp's contribution guidelines](https://contribute.freecodecamp.org).
- [x] My pull request has a descriptive title (not a vague title like `Update index.md`)
- [x] My pull request targets the `master` branch of freeCodeCamp.
- [ ] All the files I changed are in the same world language, for example: only English changes, or only Chinese changes, etc.

Closes #39220

### CODE REVIEW

**Comment by KartikSoneji** [comment]
I also took this chance to clean up the old (and quite frankly, horrible) `isSorted` method.

Old function:
```javascript
function isSorted(arr) {
  var check = (i) => (i == arr.length - 1) ? true : (arr[i] > arr[i + 1]) ? false : check(i + 1);
  return check(0);
};
```

New function:
```javascript
function isSorted(a){
  for(let i = 0; i < a.length - 1; i++)
    if(a[i] > a[i + 1])
      return false;
  return true;
}
```

**Comment by RandellDawson** [comment]
@KartikSoneji It looks good, though I would name the function `isBuilitInSort` instead of `isInBuiltSort`.  It is a small thing, but it does read better since we are checking for the built-in `sort` method.

**Comment by KartikSoneji** [comment]
@RandellDawson I have changed the name, please take a look.

> Was there a particular reason why you changed the `isSorted` function?

Well, I don't see a good reason to use a recursive closure function to check the array, especially where a simple `for` loop can do the job.

**Comment by Sky020** [comment]
Hello @KartikSoneji ,

I think Randell meant for the function name to be `isBuiltInSort`, **not** `isBuilitInSort`.

**Comment by KartikSoneji** [comment]
@Sky020 
> I think Randell meant for the function name to be isBuiltInSort, not isBuilitInSort.

🤦‍♂️ That is what I get for programming while half-asleep.

> And it is convention, throughout most of the fCC codebase, to prefix all functions/variable names with is, if they return/are a boolean.

Initially, I though that `isBuiltInSortUsed` might be too long but it is more clear.
I have changed the name of the function.

**Comment by Sky020** [comment]
Now worries, at @KartikSoneji . 

@RandellDawson , should be we adding this to all of the languages, though?

**Comment by RandellDawson** [comment]
@Sky020 Yes, that was a typo on my part.  Normally, we would not update the other language files, but since it is only code changing and not anything text related (description, instructions or test `text`), then it is fine for this PR.

**Review by naomi-lgbt — APPROVED** [review]
LGTM.

**Review by RandellDawson — APPROVED** [review]

**Comment by RandellDawson** [comment]
Thank you for your contribution to the page! 👍
We're happy to accept these changes, and look forward to future contributions. 🎉

**Pull request merged**
