### PR TITLE
Added a "What can go Here" section

### PR DESCRIPTION
**Pull request by AndrewStill**
Added a "What can go Here" section, explaining what can go in the `<head>` tag. Also added that `<head>` tag is not necessary in HTML5.

- [X] I have read [freeCodeCamp's contribution guidelines](https://github.com/freeCodeCamp/freeCodeCamp/blob/master/CONTRIBUTING.md).
- [X] My pull request has a descriptive title (not a vague title like `Update index.md`)
- [X] My pull request targets the `master` branch of freeCodeCamp.
- [X] None of my changes are plagiarized from another source without proper attribution.
- [X] My article does not contain shortened URLs or affiliate links.

If your pull request closes a GitHub issue, replace the XXXXX below with the issue number.

Closes #XXXXX

### CODE REVIEW

**Comment by nikrb** [comment]
Hi @AndrewStill, thanx for taking the time to submit this pr.
Whilst the head tag is optional, I don't think it's correct to say it should be omitted. Can you point to a reference in the W3C standards for this or rewrite the sentence please?

**Comment by RandellDawson** [comment]
Closed and Reopened this PR to attempt to resolve a specific Travis build failure.

**Comment by cmccormack** [comment]
> Hi @AndrewStill, thanx for taking the time to submit this pr.
> Whilst the head tag is optional, I don't think it's correct to say it should be omitted. Can you point to a reference in the W3C standards for this or rewrite the sentence please?

Looks like [Google's style guide](https://google.github.io/styleguide/htmlcssguide.html#Optional_Tags) recommends omitting some tags for lower file size, but this should be explicitly mentioned if adding to this guide or else risk confusing readers.  I would recommend removing or asking the submitter to remove that line completely and fix formatting of the tag explanations

**Comment by RandellDawson** [comment]
I agree with both @nikrb  and @cmccormack.  However, since there has been no response from the contributor for a while, I am closing this PR as `stale`

@AndrewStill Feel free to request this PR to be reopened, if you still wish to make the changes you originally added.  Also, remember to update your fork, so you have the latest version of master in case it has changed significantly.

Happy Coding!

**Pull request closed without merging**
