### PR TITLE
fix(curriculum): added BigInt as data type

### PR DESCRIPTION
**Pull request by theprakashkumar**
Checklist:

- [x] I have read [freeCodeCamp's contribution guidelines](https://contribute.freecodecamp.org).
- [x] My pull request has a descriptive title (not a vague title like `Update index.md`)
- [x] My pull request targets the `master` branch of freeCodeCamp.
- [x] All the files I changed are in the same world language, for example: only English changes, or only Chinese changes, etc.

Closes #XXXXX

### CODE REVIEW

**Review by moT01 — CHANGES_REQUESTED** [review]
[MDN says there's nine](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Data_structures) types in JS. You might as well add the ninth?

**Comment by ThePrakashKumar** [comment]
Hi, 
@moT01 you should check this [thread](https://github.com/freeCodeCamp/freeCodeCamp/pull/38732).

**Review by moT01 — APPROVED** [review]
LGTM 🎉

**Review by ShaunSHamilton — APPROVED** [review]
LGTM 👍

**Comment by ojeytonwilliams** [comment]
@ThePrakashKumar Thank you for your contribution to the page! :+1:
We're happy to accept these changes, and look forward to future contributions. :memo:

**Pull request merged**
