### PR TITLE
fix(curriculum): Added new hints/tests to step 6 and split step 12 into two steps of the Learn HTML by Building a Cat Photo App project

### PR DESCRIPTION
**Pull request by RandellDawson**
Checklist:

- [x] I have read [freeCodeCamp's contribution guidelines](https://contribute.freecodecamp.org).
- [x] My pull request has a descriptive title (not a vague title like `Update index.md`)
- [x] My pull request targets the `main` branch of freeCodeCamp.
- [x] I have tested these changes either locally on my machine, or GitPod.

I noticed on the forum many of the help topics being created were from the first project ([Learn HTML by Building a Cat Photo App](https://www.freecodecamp.org/learn/2022/responsive-web-design/learn-html-by-building-a-cat-photo-app)) in the new RWD. Using the [Tricky Challenge Tool](https://github.com/freeCodeCamp/scripts/tree/main/packages/tricky-challenges), I ran the following command to better understand which steps in this project needed changes to decrease the number of questions raised on the forum.
```
npm start -- posts=5500 block="Learn HTML by Building a Cat Photo App" display=table project
```
The command pulls the last 5500 topics created (regardless of category), filters by topics starting with `Learn HTML by Building a Cat Photo App - Step xxx` and displays a Pareto-like analysis (see below).

| Challenge/Step                                 | Frequency |   %   | Cumulative % |
| :--------------------------------------------- | :-------: | :---: | :----------: |
| Learn HTML by Building a Cat Photo App-Step 6  |    45     | 22.61 |    22.61     |
| Learn HTML by Building a Cat Photo App-Step 12 |    36     | 18.09 |    40.70     |
| Learn HTML by Building a Cat Photo App-Step 14 |    16     | 8.04  |    48.74     |
| Learn HTML by Building a Cat Photo App-Step 13 |    11     | 5.53  |    54.27     |
| Learn HTML by Building a Cat Photo App-Step 46 |    10     | 5.03  |    59.30     |
| Learn HTML by Building a Cat Photo App-Step 55 |     8     | 4.02  |    63.32     |
| Learn HTML by Building a Cat Photo App-Step 1  |     6     | 3.02  |    66.33     |
| Learn HTML by Building a Cat Photo App-Step 4  |     5     | 2.51  |    68.84     |
| Learn HTML by Building a Cat Photo App-Step 28 |     4     | 2.01  |    70.85     |
| Learn HTML by Building a Cat Photo App-Step 63 |     4     | 2.01  |    72.86     |
| Learn HTML by Building a Cat Photo App-Step 16 |     4     | 2.01  |    74.87     |
| Learn HTML by Building a Cat Photo App-Step 2  |     4     | 2.01  |    76.88     |
| Learn HTML by Building a Cat Photo App-Step 43 |     4     | 2.01  |    78.89     |
| Learn HTML by Building a Cat Photo App-Step 8  |     3     | 1.51  |    80.40     |
| Learn HTML by Building a Cat Photo App-Step 3  |     3     | 1.51  |    81.91     |
| Learn HTML by Building a Cat Photo App-Step 15 |     3     | 1.51  |    83.42     |
| Learn HTML by Building a Cat Photo App-Step 22 |     3     | 1.51  |    84.92     |
| Learn HTML by Building a Cat Photo App-Step 45 |     3     | 1.51  |    86.43     |
| Learn HTML by Building a Cat Photo App-Step 68 |     3     | 1.51  |    87.94     |
| Learn HTML by Building a Cat Photo App-Step 42 |     3     | 1.51  |    89.45     |
| Learn HTML by Building a Cat Photo App-Step 10 |     3     | 1.51  |    90.95     |
| Learn HTML by Building a Cat Photo App-Step 5  |     2     | 1.01  |    91.96     |
| Learn HTML by Building a Cat Photo App-Step 23 |     2     | 1.01  |    92.96     |
| Learn HTML by Building a Cat Photo App-Step 39 |     1     | 0.50  |    93.47     |
| Learn HTML by Building a Cat Photo App-Step 29 |     1     | 0.50  |    93.97     |
| Learn HTML by Building a Cat Photo App-Step 31 |     1     | 0.50  |    94.47     |
| Learn HTML by Building a Cat Photo App-Step 9  |     1     | 0.50  |    94.97     |
| Learn HTML by Building a Cat Photo App-Step 24 |     1     | 0.50  |    95.48     |
| Learn HTML by Building a Cat Photo App-Step 7  |     1     | 0.50  |    95.98     |
| Learn HTML by Building a Cat Photo App-Step 35 |     1     | 0.50  |    96.48     |
| Learn HTML by Building a Cat Photo App-Step 56 |     1     | 0.50  |    96.98     |
| Learn HTML by Building a Cat Photo App-Step 25 |     1     | 0.50  |    97.49     |
| Learn HTML by Building a Cat Photo App-Step 17 |     1     | 0.50  |    97.99     |
| Learn HTML by Building a Cat Photo App-Step 47 |     1     | 0.50  |    98.49     |
| Learn HTML by Building a Cat Photo App-Step 11 |     1     | 0.50  |    98.99     |
| Learn HTML by Building a Cat Photo App-Step 19 |     1     | 0.50  |    99.50     |
| Learn HTML by Building a Cat Photo App-Step 52 |     1     | 0.50  |    100.00    |

I decided to work on the top two problem steps as they account for over 40% of the topics for this project. I ended up changing the instructions/example and adding many more hints/tests for step 6 and splitting step 12 into two steps.

**Step 6**
Some recent changes to step 6 resulted in creating a disconnect in the starting code of step 6 based on the step 5 instructions.  You can [read my comments on that matter here](https://github.com/freeCodeCamp/freeCodeCamp/pull/47088#discussion_r936639774).  After reading many of the topics created on step 6, I concluded the biggest issue was the user not understanding how many spaces were expected to be at the beginning of each element compared to what the user actually was using.  Using dynamic hints, the user is now told how many spaces are expected vs. how many spaces the user put.

I am definitely open to making changes to my changes to the instructions as long as the intent is still the same.

**Step 12**
Reading the forum topics for this step indicated to me that we were asking too many tasks in the same step.  To solve this, I broke this one into two steps.  First, I deleted instruction about removing the old anchor tag and text below the paragraph because this seemed to be confusing the users.  I moved this part to a new step 13, so users can just focus on getting the correct text link in step 12 and removing the old link below the `p` element in the next step.

**Step 10**
I noticed an opportunity for a small wording change in the instructions of this step.  This step was way down on the list, so if others feel this change is not necessary, then I am fine reverting the change.

### CODE REVIEW

**Comment by bbsmooth** [comment]
I'm just going to say that I am strongly opposed to adding an example back to Step 6. We just changed the description/instructions about a week ago to remove the previous example since it was causing so much confusion, and changed the wording to make the instructions clearer, and overall the number of posts for Step 6 has decreased dramatically. @RandellDawson, I don't know what time period your stats cover, but my gut tells me if you just run them for the past week that step 6 will be a very small percentage, or at least much smaller than what it has been historically. I think this decrease is enough to prove that removing the example and rewording are working. I think adding an example back in, no matter how good, is going to create more confusion again.

**Comment by RandellDawson** [comment]
@bbsmooth I am fine leaving the example out. I had changed the example based on what `main` looked like before the other PRs were merged.  I figured if there would be an example, then the example should show elements the user would have already seen up to this point in the project.

However, I am strongly opposed to the starting seed code for step 6 showing the `h2` and comment already indented.  Each step's start code is supposed to represent what the instructions of the previous step would end up as.  Nothing in step 5 indicated to indent those two items.  

My changes with the extra hints/tests (especially the dynamic hints) will guide a user to create the necessary indentation for all 3 items.  It is fairly bulletproof with my new changes in that regards.

Would you object to changing the instructions to something that reflects the user needing to add spaces for all 3 items and make the starting seed code where all 3 items are at the same indention level as the `main` element?

One of the methods we use with these projects to "teach" users, is to have them perform repetitive tasks.  By having the user move all 3 items, that accomplishes this without hand feeding them pre-indented code that magically appeared without the user doing it in the previous step.  We are only 6 steps into most users first time learning HTML, so we should make the steps not have code jumping around unexpectedly when we can prevent it.  That is my only point about the indention step.

What do you think about the changes to step 12 (breaking it into two parts)?

**Comment by jeremylt** [comment]
I also am strongly opposed to the changes to Step 6 in this PR. They are out of step with the rest of our efforts to improve this Step.

These changes to Step 6 move away from changes intentionally added that successfully reduced the number of people getting stuck on Step 6. This is early enough that we saw many learners blindly copy-pasted the example, so we removed the example.

I wasn't entirely sold on moving two elements for the users, but it does in fact seem to help them understand what to do.

Ultimately, we have autoformatting nowadays. I don't think we need to belabor the point or make this step harder. The seed code in every Step in all of the projects downstream of this point naturally reinforce this indentation idea. We can bend one minor piece of standardization to help users not get stuck on a Step that isn't ultimately that big of a deal.

Partial previous discussion here (also in many, many other issues):
https://github.com/freeCodeCamp/freeCodeCamp/issues/46863

---

On the other hand, I think splitting Step 12 into two parts is a very good idea. This is one of those other common stumbling blocks and I suspect that you are correct that creating a new anchor element and deleting the old one is too much in one Step this early on in the curriculum.

**Comment by bbsmooth** [comment]
I would wholeheartedly endorse splitting step 12 into two steps.

I however think the seed code for step 6 should stay as it is. I think we do need an example of indentation, and starting the `h2` and comment indented is that example. It allows us to have an example without having to create a totally unrelated example. I understand the need for consistency from step to step, but I think the rule should be broken in this case. We aren't adding new HTML to the step behind their backs, just changing the indentation a little. I doubt that will cause any confusion. 

Also, I think we have learned that if you mention any other numbers than the original "two spaces" in the hints that it will confuse users. I think your intentions with the dynamic feedback are good, but I think history has shown that telling users how much then need to indent a line from the beginning doesn't work. Once you introduce other numbers into the equation then they start using that number everywhere.

Sorry if I'm a little curt here. I think I might be done with step 6. I've answered so many questions about it in the forums that I've come to loathe it. I do think the hints for this step need to be fixed. I already opened and issue for it and a PR was created and merged. Didn't get exactly what I wanted but good enough. I think what we have now is working pretty well as the number of step 6 posts have decrease dramatically. Maybe we need to wait a little longer to make further changes until we see what the remaining issues are with the changes we just made last week?

On a side note, I personally think this step should be removed. It stands out like a sore thumb and as far as I know it's the only step in the RWD courses that tests for indentation (correct me if I'm wrong). I understand that indentation is important, but maybe not at step 6 of the very first course. Besides, how many of us really spend time counting spaces to make sure our code is indented properly? We all have tools to do that for us. Or, I think a better approach would be to teach them how to use the document formatter included in the monaco editor. Then they would be able to format their entire code at once, anytime they needed to. And it wouldn't involve the tedious counting of spaces from the beginning of a line, which again, I think experience shows doesn't work.

**Comment by jeremylt** [comment]
I like the idea of teaching the automatic formatter, so long as it works on mobile.

**Comment by bbsmooth** [comment]
> so long as it works on mobile

As soon as I read that I was like "Ahh, I forgot about mobile, and the monaco editor is not officially supported on touch devices, so we probably can't do that."

But I just tried it on my Android device with FF and it worked. If you press your finger on the editor for a "long hold" when you let up it gives you the monaco pop-up menu, and "Format Document" is the fourth item in the menu. We'd need to verify this with iOS devices as well, but it's looking promising.

**Comment by RandellDawson** [comment]
I believe the new hints/tests I created for step 6 increases the odds of a user finishing it without having to resort to the forum and based on my 5 years on the forum as a mod and my 4 years of contributing to the curriculum.
> We all have tools to do that for us. Or, I think a better approach would be to teach them how to use the document formatter included in the monaco editor.

You have to step back for a moment as a seasoned developer and think like a complete beginner that is literally only 6 steps into learning HTML (or any programming like language) for the first time.  We teach the basics first without the fancy tools and them show them the tools later.  It is about getting the users used to indenting the code or thinking about it that was the purpose of this step.

I believe if you take the time to work through the challenge with the changes I have made, you will not think these changes are a waste of time to include for step 6. If the consensus is I have wasted my time trying to help, then I have no issues stepping away from contributing to this project.

**Comment by jeremylt** [comment]
At the very least, I think this PR should be split into two parts - one part for splitting Step 12 that we all agree with and another PR for the controversial reverting previous changes to Step 6.

**Comment by RandellDawson** [comment]
If you think you know better how to approach the project then go for it.  I won't waste anymore of my time trying to improve the curriculum.

**Comment by bbsmooth** [comment]
We discussed improving step 6 for weeks ([#46863](https://github.com/freeCodeCamp/freeCodeCamp/issues/46863)). And once we merged the PR and it went live on production about a week ago, the number of step 6 posts almost disappeared within a few days. So hopefully you can understand my strong reaction to having someone with your stature suddenly open a PR to undo the changes we just made and that seem to be working. If step 6 starts to become an issue again I am more than open to new approaches. But it would be nice to at least wait a little longer to see if the recent changes are doing their job.

**Pull request closed without merging**
