### PR TITLE
fix(curriculum): clean-up Project Euler 221-240

### PR DESCRIPTION
**Pull request by gikf**
- Cleans description.
- Changes generic `eulerXXX` function name.
- Adds images.
- Uses MathJax, a lot.
- Related to #40896.

Needed before merging:
- [x] Merged PR adding needed images to CDN https://github.com/freeCodeCamp/cdn/pull/84.

Checklist:

- [x] I have read [freeCodeCamp's contribution guidelines](https://contribute.freecodecamp.org).
- [x] My pull request has a descriptive title (not a vague title like `Update index.md`)
- [x] My pull request targets the `main` branch of freeCodeCamp.
- [x] I have tested these changes either locally on my machine, or GitPod.

### CODE REVIEW

**Review by moT01 — COMMENTED** [review]
👍

**Review by moT01 — APPROVED** [review]
LGTM 🎉 assuming tests pass

**Comment by ieahleen** [comment]
I'm trying to review the challenges on GitPod, problem number 221 can't be opened, the others don't have the issue
image

**Comment by gikf** [comment]
@ieahleen I'm getting it locally from time to time on various pages (usually on challenges listings). Try refreshing it few times.

**Review by majestic-owl448 — APPROVED** [review]
Ok, it was just my environment.

:+1: LGTM

thank you for your contribution

**Pull request merged**
