### PR TITLE
fix(learn): update the required package name

### PR DESCRIPTION
**Pull request by akiko-pusu**
Checklist:

- [x] I have read [freeCodeCamp's contribution guidelines](https://contribute.freecodecamp.org).
- [x] My pull request has a descriptive title (not a vague title like `Update index.md`)
- [x] My pull request targets the `master` branch of freeCodeCamp.
- [x] All the files I changed are in the same world language, for example: only English changes, or only Chinese changes, etc.

Ref. https://www.freecodecamp.org/learn/quality-assurance/advanced-node-and-express/set-up-the-environment

IMO: The required package name is ``http``.  Just fix only in the documentation (not code sample, test script).

### CODE REVIEW

**Review by majestic-owl448 — CHANGES_REQUESTED** [review]
change the files in only one language, specifically only in english
> All the files I changed are in the same world language, for example: only English changes, or only Chinese changes, etc.

why have you proposed this change?

**Comment by akiko-pusu** [comment]
@ieahleen 
Thanks for your time and comment!

> why have you proposed this change?

The only place that was changed was the word,  "html". So I included the Chinese translation file because I didn't change the Chinese characters.

According to the rule,  ``All the files I changed are in the same world language``, my changeset is not appropriate. Should I close and re-issue the pull request only for the English file?

**Comment by raisedadead** [comment]
I think we can make exception on this one because it probably does not affect the translation.

**Review by ShaunSHamilton — APPROVED** [review]
Thanks, for catching this. I am surprised it got through.

If we are fine with both languages being updated here, then this LGTM 👍

**Review by raisedadead — APPROVED** [review]

**Comment by raisedadead** [comment]
#### :sparkles: :sparkles: **AWESOME! LGTM.** :sparkles: :sparkles: 

Thanks @akiko-pusu, for this pull request and contributing to the code-base for the first time.

We will be looking forward for more contributions in future.

Cheers and happy contributing!

**Pull request merged**
