### PR TITLE
fix(curriculum): tests for background-color in skyline project

### PR DESCRIPTION
**Pull request by majestic-owl448**
Checklist:

- [x] I have read [freeCodeCamp's contribution guidelines](https://contribute.freecodecamp.org).
- [x] My pull request has a descriptive title (not a vague title like `Update index.md`)
- [x] My pull request targets the `main` branch of freeCodeCamp.
- [x] I have tested these changes either locally on my machine, or GitPod.

Discussed in https://github.com/freeCodeCamp/freeCodeCamp/pull/46482#issuecomment-1154087080

### CODE REVIEW

**Comment by ieahleen** [comment]
Oh, jeez

I will be back, let me fix _that_

**Review by Sboonny — APPROVED** [review]
The tests accept the code below as a valid answer LGTM

```css
 background-color: var( --building-color);
```

**Comment by ieahleen** [comment]
Now doubt - would `var(-- building- color2)` we want to make sure that that doesn't passes?

**Review by moT01 — APPROVED** [review]
LGTM @ieahleen 🎉

> would var(-- building- color2) we want to make sure that that doesn't passes?

Looks like that isn't passing, so we should be good to go 👍

**Pull request merged**
