### PR TITLE
Fixed formatting inconsistency in issue-template

### LINKED ISSUE #39017: Formatting iconsistency in issue template
**Describe the bug**

There's some formatting inconsistency in the issue templates.

**To Reproduce**
1. Try to create an issue
2. Check the issue template and you'll find the formatting inconsistency

**Screenshots**

Capture

### PR DESCRIPTION
**Pull request by UnevenCoder**
Checklist:

- [x] I have read [freeCodeCamp's contribution guidelines](https://contribute.freecodecamp.org).
- [x] My pull request has a descriptive title (not a vague title like `Update index.md`)
- [x] My pull request targets the `master` branch of freeCodeCamp.
- [x] All the files I changed are in the same world language, for example: only English changes, or only Chinese changes, etc.

Closes #39017

### CODE REVIEW

**Comment by nhcarrigan** [comment]
Nice work @UnevenCoder! Congratulations on submitting your first Pull Request!

**Comment by UnevenCoder** [comment]
> Nice work @UnevenCoder! Congratulations on submitting your first Pull Request!

thanks a lot , looking for to do more and learn along the way !!

**Review by ojeytonwilliams — APPROVED** [review]
LGTM

**Comment by ojeytonwilliams** [comment]
Thanks for the quick fix!

**Pull request merged**
