### PR TITLE
fix: center donation modal text

### LINKED ISSUE #39300: Text under the icon in block completion donation modal should be centered.
image

To replicate locally, submit any url to the data visualization projects. The modal should pop up after the last submission.

### PR DESCRIPTION
**Pull request by shraddhavp**
updated the js file

Checklist:

- [x] I have read [freeCodeCamp's contribution guidelines](https://contribute.freecodecamp.org).
- [x] My pull request has a descriptive title (not a vague title like `Update index.md`)
- [x] My pull request targets the `master` branch of freeCodeCamp.
- [x] All the files I changed are in the same world language, for example: only English changes, or only Chinese changes, etc.

Closes #39300

### CODE REVIEW

**Comment by RandellDawson** [comment]
@shraddhavp Does this close an outstanding reported GitHub issue?  If so, can you please specify that in the issue body?  Also, how did you test your changes?

**Comment by RandellDawson** [comment]
@shraddhavp Can you please update your PR body text with `Closes #issueNumberGoeHere`?

**Comment by shraddhavp** [comment]
done @RandellDawson

**Comment by ahmadabdolsaheb** [comment]
Checked locally and it looks as expected 
image

**Review by ahmaxed — APPROVED** [review]

**Comment by ojeytonwilliams** [comment]
@shraddhavp Congrats on your first pull request (PR)! 🎉

Thank you for your contribution! 👍
We're happy to accept these changes, and look forward to future contributions. 📝

**Comment by shraddhavp** [comment]
thank you @ojeytonwilliams

**Pull request merged**
