### PR TITLE
fix(dev): Remove jade middleware

### PR DESCRIPTION
**Pull request by Bouncey**
Remove unrequired middleware

### CODE REVIEW

**Comment by Bouncey** [comment]
@joshalling, the file that is removed in this PR is the only reference to the rev-manifest and it is not required any more. Please try the same locally or pull down this PR, if it resolves your issue please merge this PR 👍

**Comment by joshalling** [comment]
@Bouncey That fixed it. I can now preview the curriculum and guide locally.

I am still seeing the following error pop up as I move around the app though:

```
{ Error: Access token is required for this request
    at authorizeByJWT (/home/josh/development/freeCodeCamp/api-server/server/middlewares/jwt-authorization.js:16:9)
    at Layer.handle [as handle_request] (/home/josh/development/freeCodeCamp/api-server/node_modules/express/lib/router/layer.js:95:5)
    at trim_prefix (/home/josh/development/freeCodeCamp/api-server/node_modules/express/lib/router/index.js:317:13)
    at /home/josh/development/freeCodeCamp/api-server/node_modules/express/lib/router/index.js:284:7
    at Function.process_params (/home/josh/development/freeCodeCamp/api-server/node_modules/express/lib/router/index.js:335:12)
    at next (/home/josh/development/freeCodeCamp/api-server/node_modules/express/lib/router/index.js:275:10)
    at cookieParser (/home/josh/development/freeCodeCamp/api-server/node_modules/cookie-parser/index.js:70:5)
    at Layer.handle [as handle_request] (/home/josh/development/freeCodeCamp/api-server/node_modules/express/lib/router/layer.js:95:5)
    at trim_prefix (/home/josh/development/freeCodeCamp/api-server/node_modules/express/lib/router/index.js:317:13)
    at /home/josh/development/freeCodeCamp/api-server/node_modules/express/lib/router/index.js:284:7
    at Function.process_params (/home/josh/development/freeCodeCamp/api-server/node_modules/express/lib/router/index.js:335:12)
    at next (/home/josh/development/freeCodeCamp/api-server/node_modules/express/lib/router/index.js:275:10)
    at next (/home/josh/development/freeCodeCamp/api-server/server/middlewares/add-return-to.js:36:14)
    at Layer.handle [as handle_request] (/home/josh/development/freeCodeCamp/api-server/node_modules/express/lib/router/layer.js:95:5)
    at trim_prefix (/home/josh/development/freeCodeCamp/api-server/node_modules/express/lib/router/index.js:317:13)
    at /home/josh/development/freeCodeCamp/api-server/node_modules/express/lib/router/index.js:284:7
  [Symbol(handledError)]: 
   { type: 'info',
     message: 'Access token is required for this request',
     redirectTo: undefined,
     status: 403 } }
2018-10-12T12:37:20.922Z 403 GET 11.338 ms - /internal/user/get-session-user
```

Also I see the following when I click on signin:

image

**Review by joshalling — APPROVED** [review]
This fixed `Error: connect ECONNREFUSED 127.0.0.1:3000` and got me up and running so I will go ahead and merge.

**Comment by Bouncey** [comment]
@joshalling we are aware of the auth issue and trying to implement a fix for it, thanks for mentioning it 👍

**Pull request merged**
