### PR TITLE
Added social buttons in the README file

### PR DESCRIPTION
**Pull request by Prashoon123**
Checklist:

- [x] I have read [freeCodeCamp's contribution guidelines](https://contribute.freecodecamp.org).
- [x] My pull request has a descriptive title (not a vague title like `Update index.md`)
- [x] My pull request targets the `main` branch of freeCodeCamp.
- [x] I have tested these changes either locally on my machine, or GitPod.

### CODE REVIEW

**Comment by Nirajn2311** [comment]
@nhcarrigan I'm not sure whether to consider this as spam or not. Could you take a look at it also?

**Review by raisedadead — COMMENTED** [review]
@Prashoon123 

Thanks for the pull request and for taking the time to contribute to freeCodeCamp.

While this looks good and well-intended, I think we would not want to link to our social handles as badges.  

We have a dozen Twitter accounts for several world languages. We also have a few world language YouTube channels. Our Reddit is a super casual place, just like our Discord. Linking to our primary social handles is helpful but we should remain neutral to all world languages because we possibly can't just link to all of them.

IMHO, we should leave the social badges from the README altogether and keep it uncluttered instead. 

@freeCodeCamp/staff 

It is fair to assume that the GitHub readme is not going to be the primary place how our community discovers these social resources?

**Comment by scissorsneedfoodtoo** [comment]
@Prashoon123, thank you for taking the time to open this PR.

Unfortunately, like @raisedadead mentioned, I don't think the README is the best place for these badges. We'll continue to add more Twitter accounts and YouTube channels, and social media badges will quickly get unwieldy.

My thinking is that the people who arrive at this repo are likely already aware of our presence on YouTube, Twitter, and our chatroom. Instead, it's probably better for the README to serve as a high-level overview of the project, and to be more focused on development.

We do mention some of our other platforms [here](https://github.com/freeCodeCamp/freeCodeCamp#the-learning-platform) in the README, but I think that's enough for the moment.

News is probably a better place to list all of our different Twitter accounts, YouTube channels, and so on.

**Comment by Prashoon123** [comment]
Thanks guys for taking your time and reviewing my PR! 🙂

**Comment by scissorsneedfoodtoo** [comment]
No problem! Thanks for your understanding.

Please feel free to check out our issues with the [help wanted](https://github.com/freeCodeCamp/freeCodeCamp/issues?q=is%3Aopen+is%3Aissue+label%3A%22help+wanted%22) label that are open for contribution.

**Pull request closed without merging**
