### PR TITLE
fix(seed): improve instructions of css-flex challenge

### LINKED ISSUE #16879: Beta/Responsive Web Design erratum
#### Challenge Name

https://beta.freecodecamp.org/en/challenges/css-flexbox/use-the-flex-shorthand-property

#### Issue Description

Just an error in the lesson. I don't want to sound arrogant - I had to read up on flexboxes when I used the non-beta version. The following block of text comprises the challenge instructions:
>Add the CSS property flex to both #box-1 and #box-2. Give #box-1 the values so its flex-grow is 2, its flex-shrink is 2, and its flex-basis is 150px. Give #box-2 the values so its flex-grow is 1, its flex-shrink is 1, and its flex-basis is 150px.

Followed by this explanation of behavior:
>These values will cause #box-1 to be twice the size of #box-2 when the container is greater than 300px and half the size of #box-2 when the container is less than 300px. 300px is the combined size of the flex-basis values of the two boxes.

I believe that what will actually happen is that the **extra pixels** will be distributed in a 2:1 ratio when the container is greater than 300px, and that when the container is smaller than 300px,  the **pixel deficit** (number of pixels by which the container had to be reduced from the basis) will be distributed in a 2:1 ratio when the container is less than 300px.

Tricky to explain succinctly. I offer the following replacement text:
>These values will cause #box-1 to grow to fill the extra space at twice the rate of #box-2 when the container is greater than 300px and shrink at twice the rate of #box-2 when the container is less than 300px. 300px is the combined size of the flex-basis values of the two boxes.
#### Browser Information

* Browser Name, Version: Firefox 58.0.2
* Operating System: Windows 8.1 64-bit
* Mobile, Desktop, or Tablet: Desktop

#### Your Code

```js
  #box-1 {
    background-color: dodgerblue;
    flex: 2 2 150px;
    height: 200px;
  }

  #box-2 {
    background-color: orangered;
    flex: 1 1 150px;
    height: 200px;
  }


```

### PR DESCRIPTION
**Pull request by YogeshSharma0201**
#### Pre-Submission Checklist

- [x] Your pull request targets the `staging` branch of freeCodeCamp.
- [ ] Branch starts with either `fix/`, `feature/`, or `translate/` (e.g. `fix/signin-issue`)
- [x] You have only one commit (if not, [squash](http://forum.freecodecamp.org/t/how-to-squash-multiple-commits-into-one-with-git/13231) them into one commit).
- [x] All new and existing tests pass the command `npm test`. Use `git commit --amend` to amend any fixes.

#### Type of Change

- [ ] Small bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds new functionality)
- [ ] Breaking change (fix or feature that would change existing functionality)
- [ ] Add new translation (feature adding new translations)

#### Checklist:

- [x] Tested changes locally.
- [x] Addressed currently open issue (replace XXXXX with an issue no in next line)

Closes #16879

### CODE REVIEW

**Comment by raisedadead** [comment]
Please run `npm run test-challenges-develop` on your local copy to get the linting error in the seed file. Once resolved, please update the PR by amending your commit.

Instructions for the same are available in the [Guidelines for Contributing](https://github.com/freeCodeCamp/freeCodeCamp/blob/staging/CONTRIBUTING.md) and you can also reach out to the [Contributors Chat room](https://gitter.im/FreeCodeCamp/Contributors) for any assistance.

**Comment by raisedadead** [comment]
Ignore previous comment. 

You just need a simple rebase against staging to resolve the snyk issue.
```
git checkout <this pr branch name>
git pull --rebase upstream staging
git commit --amend -m "fix(seed): improve instructions of css-flex challenge"
git push force
```

**Comment by mstellaluna** [comment]
I am currently working on this PR.

**Comment by mstellaluna** [comment]
@YogeshSharma0201 Hello. I finished testing your PR. It looks good to me, I will be approving your changes. Thank you for your contribution. Happy Coding!

**Review by mstellaluna — APPROVED** [review]
It looks great to me. Approving changes.

**Pull request merged**
