### PR TITLE
fix(UI): refactor the searchbar from flex to grid

### LINKED ISSUE #48912: Refactor the searchbar from flex layout to grid layout
**Describe the request**
The searchbar has `flex` layout and it was fine with one icon in it, but with the addition of `reset` icon, the spacing between the `buttons` and `input` needs to be precises. 

Flexbox doesn't provide a good way for precision, which cased the need to add magic number to position it so we can change the searchbar to `grid` with 3 columns template, and with `grid-area` we don't need to have `position: absolute` and `right: 291` properties anymore.

---

To solve this issue, you need to:
- swap to  `grid` in this selector `.fcc_searchBar .ais-SearchBox-form`.
- Remove `position: absolute` from these selectors `.ais-SearchBox-reset, .ais-SearchBox-submit`.
- Remove the magic number from `.ais-SearchBox-reset`. (`right: 0;`, `right: 15px;`, `right: 291px;`).

---

You may run into these issues:

- with the `ais-SearchBox-input`, as I think it won't wrap around the elements anymore 🤔. This can be fixed adding `border` to it's pseudo-elements instead (you can choose between `::before`, or `::after`).
- with the `background-color` or having `border` between each of the elements, you can use its parent or pseudo-elements to fix it, if you run into it.

----

If you would like to fix this issue, please make sure you read [our guidelines for contributing](https://contribute.freecodecamp.org/#/), we prioritize contributors following the instructions in our guides. Join us in [our chat room](https://discord.gg/PRyKn3Vbay) or [the forum](https://forum.freecodecamp.org/c/contributors/3) if you need help contributing, our moderators will guide you through this.

### PR DESCRIPTION
**Pull request by mmatsumoto1026**
Checklist:

- [x] I have read [freeCodeCamp's contribution guidelines](https://contribute.freecodecamp.org).
- [x] My pull request has a descriptive title (not a vague title like `Update index.md`)
- [x] My pull request targets the `main` branch of freeCodeCamp.
- [x] I have tested these changes either locally on my machine, or GitPod.

Closes #48912

To refactor the searchbar from flex layout to grid layout, this PR was opened.

The code was tested locally and by using gitpod, with the environments showed below.

Actually, I could not test the search button's functionality in learn, donate and settings page which use `search-bar.tsx` (in landig page which use `search-bar-optimized.tsx`, the button functions correctlly).
Because in dev environment (both locally and using gitpod), the search button did not open the news page not only in the fixed code but also in the original code when I tested.
So I only focused to refactor the layout of searchbar in this PR.

- Test environments

    - In PC dev environment

        - OS: Windows 11 Home
        - Browsers: Chrome, Firefox, Edge and Brave

    - In mobile dev environment (android studio emulator - Pixel 3a XL, and iPhone SE)

         - OS: android 12.0 and iOS 15.7.1
         - Browsers: android => Chrome, iOS => Chrome, Firefox, Safari, Opera and Brave

### CODE REVIEW

**Review by Sboonny — COMMENTED** [review]
Nicely done 👏, I actually thought it isn't possible to have the border without user pseudo-elements.

Small clean up, and this is ready to merge 👍

**Review by Sboonny — APPROVED** [review]
LGTM 🎉, thank you for your contribution to the page! 👍.

**Comment by bbsmooth** [comment]
I agree with @Sboonny, this is very nice. I've been trying to break it for the past hour and nothing.

**Review by scissorsneedfoodtoo — APPROVED** [review]
Tested locally and everything LGTM 👍 👍 

Like @bbsmooth, I also tried to break this with different widths and screen heights, but wasn't able to. The look and behavior seemed to match the production search bar exactly.

Thank you for all of your hard work refactoring the search bar to use CSS Grid, @mmatsumoto1026. This should make things much more maintainable in the future, and we can carry a lot of this over to the News search bar.

**Pull request merged**
