### PR TITLE
chore(i18n,curriculum): processed translations

### PR DESCRIPTION
**Pull request by camperbot**
This PR was opened auto-magically by Crowdin.

### CODE REVIEW

**Review by naomi-lgbt — DISMISSED** [review]

**Comment by raisedadead** [comment]
I want to sit on these Crowdin PRs for the night and see how the action behaves when we do not check-in during the weekends. Should be a good test of the CI runs.

**Comment by raisedadead** [comment]
The action is pushing an update to the PR. We need camperbot to push the update, I would recommend changing this line:

https://github.com/freeCodeCamp/freeCodeCamp/blob/aea37058bf5b12c3b0a923e8b977a82b3ec55838/.github/workflows/crowdin-i18n-curriculum-download.yml#L47

to use the PAT from camperbot.

**Comment by ojeytonwilliams** [comment]
I'm surprised the checks don't trigger - what's the problem with the action bot pushing the new branch?

**Review by raisedadead — APPROVED** [review]

**Comment by nhcarrigan** [comment]
@ojeytonwilliams GitHub considers it a security feature to disallow actions triggering other actions in this way.

Because the action bot is doing the push instead of Camperbot, the CI won't run on the PR - which is why we had to make Camperbot open the PRs instead. 

@raisedadead I'll push a PR with the suggested workflow changes today.

**Review by naomi-lgbt — APPROVED** [review]

**Pull request merged**
