### PR TITLE
fix(learn): Strengthen a test in "Data Structures: Remove Elements from a Linked List"

### PR DESCRIPTION
**Pull request by TyMick**
Checklist:

- [x] I have read [freeCodeCamp's contribution guidelines](https://contribute.freecodecamp.org).
- [x] My pull request has a descriptive title (not a vague title like `Update index.md`)
- [x] My pull request targets the `master` branch of freeCodeCamp.
- [x] All the files I changed are in the same world language, for example: only English changes, or only Chinese changes, etc.

Looking back at the code I wrote for this challenge a few months ago, I realized that my `remove` method was decreasing the `length` of the linked list whether or not it actually found an element to remove, and the challenge tests didn't catch that. Here's an additional test that'll catch this mistake.

### Test text:

> Your <code>remove</code> method should <em>not</em> decrease the <code>length</code> of the linked list if it does not remove a node.

The word "not" is emphasized the first time because I placed this test right after one that reads, "Your <code>remove</code> method should decrease the <code>length</code> of the linked list by one for every node removed."

### Test code:

```js
assert(
  (function () {
    var test = new LinkedList();
    test.add('cat');
    test.add('dog');
    test.remove('fish');
    return test.size() === 2;
  })()
);
```

-----

Also, all 21 tests for this challenge are passing on my end.

```shell
freeCodeCamp % cd curriculum
curriculum % npm run test -- -g "Remove Elements from a Linked List"
...
  21 passing (3s)
```

### CODE REVIEW

**Comment by tywmick** [comment]
`linked-list-remove-test` was not the best branch name choice—I'm _adding_ a test, not removing one; the lesson itself is just about removing... Oh well. 🤦🏼‍♂️

**Comment by RandellDawson** [comment]
@tywmick That is a good catch about the existing tests.  I would like to suggest a different fix here.  The text for the existing text already state that the length should only decrease by one for each node removed, so instead of adding a completely new test, maybe you can simply add one more item to the linked list (i.e. `hamster`), still remove `cat`, and then remove the non-existent item (`fish`), and check that the length is still `2`.

**Comment by tywmick** [comment]
Good thinking! Here's the new consolidated `length`-related test:

```js
assert(
  (function () {
    var test = new LinkedList();
    test.add("cat");
    test.add("dog");
    test.add("hamster");
    test.remove("cat");
    test.remove("fish");
    return test.size() === 2;
  })()
);
```

**Review by RandellDawson — APPROVED** [review]
LGTM

**Review by ShaunSHamilton — APPROVED** [review]
This LGTM 👍 

Thank you, for your contribution to the page! 👍
We are happy to accept these changes, and look forward to future contributions. 🎉

**Pull request merged**
