### PR TITLE
fix: make donation styles consistent

### LINKED ISSUE #36763: Audit and update styles for error, info and warning, etc.
image

### PR DESCRIPTION
**Pull request by ahmaxed**
- [x] I have read [freeCodeCamp's contribution guidelines](https://github.com/freeCodeCamp/freeCodeCamp/blob/master/CONTRIBUTING.md).
- [x] My pull request has a descriptive title (not a vague title like `Update index.md`)
- [x] My pull request targets the `master` branch of freeCodeCamp.
- [x] None of my changes are plagiarized from another source without proper attribution.
- [x] All the files I changed are in the same world language (for example: only English changes, or only Chinese changes, etc.)
- [x] My changes do not use shortened URLs or affiliate links.

Closes #36763

### CODE REVIEW

**Comment by ahmadabdolsaheb** [comment]
**this is how they look now. is more modification needed?**

Screen Shot 2019-10-09 at 12 59 08 PM
Screen Shot 2019-10-09 at 1 00 18 PM
Screen Shot 2019-10-09 at 1 05 47 PM

**Comment by raisedadead** [comment]
Thanks Ahmad, looks good. 

Just to make sure we would be moving the modal and pages (actually have). We would still need these changes, I would land them soon.

Is this all of the CSS that needed updating for consistency?

**Comment by ahmadabdolsaheb** [comment]
These changes address the donation modal.

The rest of the notifications such as flash messages and lesson modals have been adjusted previously.

If you are aware of any other form of alert of notification that is not mentioned above, please let me know and I will work on them immediately.

**Comment by vkWeb** [comment]
@raisedadead @ahmadabdolsaheb Can we make the modal a bit small in vertical size so that we don't need to scroll. If we look at the stats: https://gs.statcounter.com/screen-resolution-stats/desktop/worldwide then making modal vertically small for 1280*720 will make it work for all bigger resolutions as well.

I hope you got my point.

**Comment by raisedadead** [comment]
> If you are aware of any other form of alert of notification that is not mentioned above, please let me know and I will work on them immediately.

Not that I am aware of, but you should audit all the .css files just in case.

**Comment by raisedadead** [comment]
> Can we make the modal a bit small [...]

The modal is going away, thanks for your feedback.

**Comment by ahmadabdolsaheb** [comment]
The css files have been audited and look good to the best of my knowledge.

However, bootstrap styles sometimes conflict with our styles that causes aesthetic and readability issues.

Those issues cannot be spotted by reviewing our css files.

I suggest treating such issues on the case by case basis until we migrate away from bootstrap completely.

**Comment by raisedadead** [comment]
Okay thanks for confirming.

**Review by raisedadead — APPROVED** [review]

**Pull request merged**
