### PR TITLE
fix(curriculum): Replace special characters with HTML entities

### LINKED ISSUE #36036: [beta] Challenge Basic CSS: Cascading CSS variables is missing a keyword
**Describe your problem and how to reproduce it:**

Challenge `Basic CSS: Cascading CSS variables` has a missing keyword in its description.

Untitled

**Add a Link to the page with the problem:**

https://www.freecodecamp.rocks/learn/responsive-web-design/basic-css/cascading-css-variables

### PR DESCRIPTION
**Pull request by huyenltnguyen**
- [x] I have read [freeCodeCamp's contribution guidelines](https://github.com/freeCodeCamp/freeCodeCamp/blob/master/CONTRIBUTING.md).
- [x] My pull request has a descriptive title (not a vague title like `Update index.md`)
- [x] My pull request targets the `master` branch of freeCodeCamp.
- [x] None of my changes are plagiarized from another source without proper attribution.
- [x] All the files I changed are in the same world language (for example: only English changes, or only Chinese changes, etc.)
- [x] My changes do not use shortened URLs or affiliate links.

Closes #36036

### CODE REVIEW

**Review by moT01 — APPROVED** [review]
Nice catch @huyenltnguyen - LGTM

**Comment by RandellDawson** [comment]
Wouldn't it just be the following?

```
<code>:root</code> is a <dfn>pseudo-class</dfn> selector that matches the root element of the document, usually the <code>html</code> element. By creating your variables in <code>:root</code>, they will be available globally and can be accessed from any other selector later in the style sheet.
```

When we refer to **elements** in almost all the other challenges we do not include the `<` pr `>`.  If we a referring to a **tag**, I have seen the the `<` and `>` and `/` if it is a closing tag.

**Comment by huyenltnguyen** [comment]
@RandellDawson Agreed! I'll make the change shortly.

**Review by thecodingaviator — APPROVED** [review]
LGTM now. Thanks @huyenltnguyen

**Comment by thecodingaviator** [comment]
Thank you for your contribution to the page! 👍
We're happy to accept these changes, and look forward to future contributions. 📝

**Pull request merged**
