### PR TITLE
fix: use lts node in gitpod

### PR DESCRIPTION
**Pull request by ojeytonwilliams**
Checklist:

- [x] I have read and followed the [contribution guidelines](https://contribute.freecodecamp.org).
- [x] I have read and followed the [how to open a pull request guide](https://contribute.freecodecamp.org/#/how-to-open-a-pull-request).
- [x] My pull request targets the `main` branch of freeCodeCamp.
- [x] I have tested these changes either locally on my machine, or GitPod.

### CODE REVIEW

**Review by ShaunSHamilton — COMMENTED** [review]
Interesting this does not work:

```bash
gitpod /workspace/freeCodeCamp (fix/lts-node-in-gitpod) $ node --version
v16.19.0
gitpod /workspace/freeCodeCamp (fix/lts-node-in-gitpod) $ nvm install --lts
Installing latest LTS version.
v18.14.0 is already installed.
Now using node v18.14.0 (npm v9.3.1)
gitpod /workspace/freeCodeCamp (fix/lts-node-in-gitpod) $ node --version
v18.14.0
```

**Comment by ShaunSHamilton** [comment]
I would prefer not to use a custom Dockerfile, if we can avoid it. From my experience, it adds a lot of overhead to the startup time.

**Review by ShaunSHamilton — APPROVED** [review]
👍

**Comment by ojeytonwilliams** [comment]
Sorry, Shaun, I meant to say that you'd tested it and it was only a few seconds slower.

**Comment by raisedadead** [comment]
Yeah - I have had the same experience with a custom Dockerfile. It makes the startup a bit slower. But I think it is fair to have the version pinned, which is more critical.

**Review by raisedadead — APPROVED** [review]

**Pull request merged**
