### PR TITLE
Updated jest in packages

### LINKED ISSUE #36216: Update jest to latest
We want to update jest to the latest version and the related code to address the breaking changes.

### PR DESCRIPTION
**Pull request by kozlovvski**
- [x] I have read [freeCodeCamp's contribution guidelines](https://github.com/freeCodeCamp/freeCodeCamp/blob/master/CONTRIBUTING.md).
- [x] My pull request has a descriptive title (not a vague title like `Update index.md`)
- [x] My pull request targets the `master` branch of freeCodeCamp.
- [x] None of my changes are plagiarized from another source without proper attribution.
- [x] All the files I changed are in the same world language (for example: only English changes, or only Chinese changes, etc.)
- [x] My changes do not use shortened URLs or affiliate links.

Closes #36216 (probably)

----
Okay, so I've updated `jest` in every `package.json` file (and installed them to update `package-lock.json`).  `npm audit` returned no vulnerabilities concerning `jest`. Does that solve the issue? If not, can someone please tell me what to do next, beginner here.

Cheers!

### CODE REVIEW

**Comment by raisedadead** [comment]
Hi @kozlovvski thanks for the PR. This is great. 

While the CI reports the builds to pass, can you also do a quick audit of the breaking changes that they introduced and maybe check if they have a migration doc or something for the major version? If yes, then it would be as easy as doing a quick search in the codebase if we are following any of the breaking changes. I hope we aren't, but just to be 100% sure before we do the major bump.

**Comment by kozlovvski** [comment]
@raisedadead I didn't find any migration doc, but found breaking changes in [their changelog ](https://github.com/facebook/jest/blob/master/CHANGELOG.md). How do I now check if everything works fine?

**Comment by raisedadead** [comment]
It most likely already works as it is. But just to be safe you want to be: 

- Start looking at https://github.com/facebook/jest/blob/master/CHANGELOG.md#2400, thats where the major version came in.
- Then go thru the fixes part first, and see when breaking changes they have. Do we need to update any code in our side? You can maybe locally search in your codebase for the api/methods/routines etc mentioned there.
- Also then double check the features section.

It doesn't have to be very meticulous, but you need to do an audit of what's changed and if we are using something that's deprecated.

Another way to debug would be to see what's logged when you run tests locally. If you see any warning flags that are related to the changes and so on.

**Comment by kozlovvski** [comment]
Okay, so I checked those breaking changes and:
- we don't use any of the deprecated methods
- other packages still use dependencies dropped by `jest`, for example `jest` replaced `diff` with `diff-sequences` but our other dependies still use `diff`

I also ran tests locally and only one test failed (but I don't think that's related to the `jest` update):

```js
RUNS  src/components/Map/components/Block.test.js
 30% building 8/10 modules 2 active  30% building 8/11 modules 3 active ...eCamp\client\node_modules\chai\index.js FAIL  server/boot_tests/challenge.test.js
  ● Test suite failed to run

    Cannot find module '../resources/pathMigration.json' from 'challenge.js'

    However, Jest was able to find:
        '../boot/challenge.js'

    You might want to include a file extension in your import, or update your 'moduleFileExtensions', which is currently ['js', 'json', 'jsx', 'ts', 'tsx', 'node'].

    See https://jestjs.io/docs/en/configuration#modulefileextensions-array-string

      17 | import { ifNoUserSend } from '../utils/middleware';
      18 | import { dasherize } from '../utils';
    > 19 | import _pathMigrations from '../resources/pathMigration.json';
         | ^
      20 | import { fixCompletedChallengeItem } from '../../common/utils';
      21 |
      22 | const log = debug('fcc:boot:challenges');

      at Resolver.resolveModule (node_modules/jest-resolve/build/index.js:230:17)
      at Object.<anonymous> (server/boot/challenge.js:19:1)
```

**Comment by raisedadead** [comment]
Perfect, thanks for auditing these. I guess we can ignore that other deps have not updated yet, but will do in future, hopefully.

As for the error that you get. I think that file should have been generated in a build step, so its unrelated to what we are doing here.

Thanks for the all the work on this PR. I'll have this pulled down and merged soon.

**Comment by kozlovvski** [comment]
Thank you too for the instructions and opportunity to fix this issue - it feels nice to somehow contribute to the place where I started learning webdev 😄 

Cheers!

**Review by raisedadead — APPROVED** [review]
#### :sparkles: :sparkles: **AWESOME! LGTM.** :sparkles: :sparkles: 

Thanks @kozlovvski, for this pull request and contributing to the code-base for the first time.
We will be looking forward for more contributions in future.

Cheers and happy contributing!

**Pull request merged**
