### PR TITLE
nest anchor within paragraph instructions modification

### LINKED ISSUE #17406: Basic HTML and HTML5 - Nest an Anchor Element within a Paragraph: First test tracks the href of the wrong <a> element
#### Describe your problem and - if possible - how to reproduce it
The first test ("You need an `a` element that links to `http://freecatphotoapp.com`.") is testing the first `a` element, not the one that the user is supposed to type. It is marked as correct even though the user typed the wrong `href` value.

Somehow this interferes with the 4th and 5th tests.

```html
<h2>CatPhotoApp</h2>
<main>
  
  <a href="http://freecatphotoapp.com" target="_blank">cat photos</a>
  
  <img src="https://bit.ly/fcc-relaxing-cat" alt="A cute orange cat lying on its back.">
  
  <p>Kitty ipsum dolor sit amet, shed everywhere shed everywhere stretching attack your ankles chase the red dot, hairball run catnip eat the grass sniff.</p>
  <p>Purr jump eat the grass rip the couch scratched sunbathe, shed everywhere rip the couch sleep in the sink fluffy fur catnip scratched.</p>
</main>

<p>View more <a href="http://www.catphotoapp.com">cat photos</a></p>
```

#### Add a Link to the page with the problem
https://learn.freecodecamp.org/responsive-web-design/basic-html-and-html5/nest-an-anchor-element-within-a-paragraph/

##### Relevant forum post
https://forum.freecodecamp.org/t/solved-nest-an-anchor-element-within-a-paragraph-dont-understand-step-4-and-5/195819

#### Tell us about your browser and operating system

* Browser Name: Firefox
* Browser Version: 60.0.1
* Operating System: Manjaro

### PR DESCRIPTION
**Pull request by tannerabread**
wording on challenge instructions may have been unclear to some campers
changes "your" to "the" existing <code>a</code> element to make it more clear

- [x] I have read [freeCodeCamp's contribution guidelines](https://github.com/freeCodeCamp/freeCodeCamp/blob/master/CONTRIBUTING.md).
- [x] My pull request has a descriptive title (not a vague title like `Update index.md`)
- [x] My pull request targets the `master` branch of freeCodeCamp.
- [x] None of my changes are plagiarized from another source without proper attribution.
- [x] My article does not contain shortened URLs or affiliate links.

If your pull request closes a GitHub issue, replace the XXXXX below with the issue number.

Closes #17406

### CODE REVIEW

**Comment by nikrb** [comment]
successfully tested locally

**Comment by RandellDawson** [comment]
This change does not seem necessary to me.  I don't see how it improves the challenge instructions.  The `in the editor` part is definitely not needed.  Where else would you add code?

**Comment by nikrb** [comment]
two penneth ... I went through the challenge whilst testing locally and speaking as a relative nuub, I had to read through the instructions a few times. I think the change of 'your' to 'the' does actually help.
I agree the `in the editor` bit probably isn't necessary.

**Comment by Nirajn2311** [comment]
@nikrb @RandellDawson So are we agreeing on changing 'your' to 'the' and removing the other change?

**Comment by RandellDawson** [comment]
@bannon-tanner You are correct.  Only change 'your' to `'the`. Go ahead and revert the other change, so we can approve this PR and get it merged.

**Comment by RandellDawson** [comment]
I made the change on the user's behalf to avoid waiting any longer.

**Comment by RandellDawson** [comment]
@Nirajn2311 or @nikrb  Feel free to merge this PR.

**Review by RandellDawson — APPROVED** [review]

**Review by ezioda004 — APPROVED** [review]

**Comment by ezioda004** [comment]
Thank you @bannon-tanner for your contribution. Looking forward to more contributions from you! 🎉

**Pull request merged**
