### PR TITLE
Show status on individual completed courseware

### PR DESCRIPTION
**Pull request by wakqasahmed**
Shows if the current waypoint, bonfire you are standing it was completed already.

### CODE REVIEW

**Comment by SaintPeter** [comment]
This looks pretty good:
image

In the future, when making UI changes, it would be helpful if you included a screenshot of the relevant part.

I do believe that for accessibility this icon should have a `title` tag of "Completed".

Here is the sample code:
`i.ion-checkmark-circled.text-primary(title="Completed")`

If you make this change, amend your commit with:
`git commit --amend` and `git push -f` to force push it up.

I would like others opinions before I push this live.
@FreeCodeCamp/issue-moderators - Thoughts?

**Comment by ltegman** [comment]
I'm good with this. It adds information without adding UI clutter and in most cases users won't see it anyways since going back to a completed challenge is not the usual use-case of challenges.

**Comment by SaintPeter** [comment]
Thanks!

**Comment by wakqasahmed** [comment]
Thanks for merging.. @ltegman: Since FCC constantly evolving with new challenges even the existing campers will benefit from it.

**Pull request merged**
