### PR TITLE
Added a new test for the challenge

### LINKED ISSUE #12419: Wrong solution is accepted when submitted
Challenge [Return Largest Numbers in Arrays](https://www.freecodecamp.com/challenges/return-largest-numbers-in-arrays#?solution=%0Afunction%20largestOfFour(arr)%20%7B%0A%20%20return%20arr.map(function(subArray)%20%7B%0A%20%20%20%20return%20subArray.reduce(function(prev%2C%20curr)%20%7B%0A%20%20%20%20%20%20return%20(curr%20%3E%20prev%20%3F%20curr%20%3A%20prev)%3B%0A%20%20%20%20%7D%2C%200)%3B%0A%20%20%7D)%3B%0A%7D%0A%0AlargestOfFour(%5B%5B4%2C%205%2C%201%2C%203%5D%2C%20%5B13%2C%2027%2C%2018%2C%2026%5D%2C%20%5B32%2C%2035%2C%2037%2C%2039%5D%2C%20%5B1000%2C%201001%2C%20857%2C%201%5D%5D)%3B%0A) has an issue.
User Agent is: <code>Mozilla/5.0 (Windows NT 6.1; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/55.0.2883.87 Safari/537.36</code>.
The code below uses map/reduce as suggested in the medium forum (I've reviewed the solutions over there) and is accepted when submitted.

The problem is that there is an assumption that in every subarray not all of the values are negatives and it is not shown in the description of the problem. That is, if one of the subarray contains only negatives values, the accepted solution below isn't correct.

My code:
```javascript

function largestOfFour(arr) {
  return arr.map(function(subArray) {
    return subArray.reduce(function(prev, curr) {
      return (curr > prev ? curr : prev);
    }, 0);
  });
}

largestOfFour([[4, 5, 1, 3], [13, 27, 18, 26], [32, 35, 37, 39], [1000, 1001, 857, 1]]);

```

### PR DESCRIPTION
**Pull request by 91aman**
#### Pre-Submission Checklist

- [x] Your pull request targets the `staging` branch of FreeCodeCamp.
- [x] Branch starts with either `fix/`, `feature/`, or `translate/` (e.g. `fix/signin-issue`)
- [x] You have only one commit (if not, [squash](http://forum.freecodecamp.com/t/how-to-squash-multiple-commits-into-one-with-git/13231) them into one commit).
- [x] All new and existing tests pass the command `npm test`. Use `git commit --amend` to amend any fixes.

#### Type of Change

- [x] Small bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds new functionality)
- [ ] Breaking change (fix or feature that would change existing functionality)
- [ ] Add new translation (feature adding new translations)

#### Checklist:

- [x] Tested changes locally.
- [x] Closes currently open issue (replace XXXX with an issue no): Closes #12419

#### Description
Add a new test for the checking negative values as mentioned in #12419

### CODE REVIEW

**Review by ooade — APPROVED** [review]
## LGTM
You might just need to change the title and commit message to match what the PR actually does

**Comment by 91aman** [comment]
@ooade , In my opinion, this is what the PR is doing, adding a new test. Any suggestions on what should I change it to, if it is needed?

**Comment by dhcodes** [comment]
On hold while I wait for feedback in issue thread.

**Comment by dhcodes** [comment]
Tested locally on staging 👍 . Tested new wiki solutions locally on staging and on freecodecamp.com 👍  

#LGTM 

Thanks @91aman @systimotic for contributing to freeCodeCamp 👍 🌮 :eagle:

**Pull request merged**
