### PR TITLE
fix: Stop pairs of tags from getting put into paragraphs

### LINKED ISSUE #35727: [beta] Challenge instruction drops to a new line mid-sentence
**Describe your problem and how to reproduce it:**

Go to challenge `Basic JavaScript: Global Scope and Functions`.

The instruction's last sentence breaks to a new line mid-sentence.

(This issue does not exist in production: https://learn.freecodecamp.org/javascript-algorithms-and-data-structures/basic-javascript/global-scope-and-functions/ )

**Add a Link to the page with the problem:**

https://www.freecodecamp.rocks/learn/javascript-algorithms-and-data-structures/basic-javascript/global-scope-and-functions

**Tell us about your browser and operating system:**
* Browser Name:
* Browser Version:
* Operating System:

**If possible, add a screenshot here (you can drag and drop, png, jpg, gif, etc. in this box):**

Screen Shot 2019-04-01 at 11 13 05 AM

### PR DESCRIPTION
**Pull request by ojeytonwilliams**
- [x] I have read [freeCodeCamp's contribution guidelines](https://github.com/freeCodeCamp/freeCodeCamp/blob/master/CONTRIBUTING.md).
- [x] My pull request has a descriptive title (not a vague title like `Update index.md`)
- [x] My pull request targets the `master` branch of freeCodeCamp.
- [x] None of my changes are plagiarized from another source without proper attribution.
- [x] All the files I changed are in the same world language (for example: only English changes, or only Chinese changes, etc.)
- [x] My changes do not use shortened URLs or affiliate links.

Closes #35727, which is a specific case of a problem that appears throughout the challenges.  As @RandellDawson pointed out in https://github.com/freeCodeCamp/freeCodeCamp/issues/35727#issuecomment-478433879, if you have a space between any two tags, the second tag will appear in a new paragraph.

With this PR if the parser encounters a line which is just whitespace, it will leave it alone and not try to wrap it into a paragraph.  As far as I can see, this should only appear when some text is nestled between two tags.  In that case we don't want it to get its own paragraph.

### CODE REVIEW

**Review by moT01 — COMMENTED** [review]
I took a look at this locally @ojeytonwilliams, it looks like it fixes the issue. I took a small look around at other challenges and couldn't find any negative consequences. But I was wondering if an easier fix here might be to just change the "without" to regular text instead of the bold/italic it is now as it might be the only challenge with this issue.

We might want one of the core members to take a look at this before merging as it adds all this code.

**Comment by ojeytonwilliams** [comment]
@moT01 Thanks for the review!  So, we could definitely fix that challenge by removing the tags or by wrapping the space.  Unfortunately this problem crops up all over the place.  For example, [here after "not"](https://www.freecodecamp.rocks/learn/javascript-algorithms-and-data-structures/basic-javascript/use-conditional-logic-with-if-statements), [here after "Bird's"](https://www.freecodecamp.rocks/learn/javascript-algorithms-and-data-structures/object-oriented-programming/add-methods-after-inheritance) and [here after "&&"](https://www.freecodecamp.rocks/learn/front-end-libraries/react/render-conditionally-from-props).

I'll compile a list of them, just in case we do want to fix the challenges rather than the parser.  However, I think it would be better if we could write whatever tags are needed and not have to worry about spaces.  Having said all that, I entirely agree that it needs reviewing by a core member!

**Comment by moT01** [comment]
Well, I suppose since you already did the work here, and there is more than just the one challenge with the issue... maybe we should just get this looked at, and if it gets merged we don't need to worry about the issue popping back up. I'm not sure a list is necessary at the moment, I would wait on it until it's decided we want to go that route - but go ahead if you want.

**Comment by ojeytonwilliams** [comment]
@moT01 Yeah, you're right, I'll put that on hold for now.  There are rather a lot of them!

**Comment by moT01** [comment]
This looks like it's probably the way to go then.

**Review by ValeraS — APPROVED** [review]

**Pull request merged**
