### PR TITLE
fix(README.md): Added learn remotely in it

### PR DESCRIPTION
**Pull request by vickyIee**
Let people know that this is a remote course (that can be done from anywhere).

Checklist:

- [ ] I have read [freeCodeCamp's contribution guidelines](https://contribute.freecodecamp.org).
- [ ] My pull request has a descriptive title (not a vague title like `Update index.md`)
- [ x] My pull request targets the `main` branch of freeCodeCamp.
- [ x] I have tested these changes either locally on my machine, or GitPod.

### CODE REVIEW

**Comment by RTOChamp** [comment]
Hey guys, I know I am seeing a lot of back-and-forth on this topic, but I really need to push back and raise some red flags here.

Having an on-site office presence is foundational to our ability to drive efficiencies in a corporate landscape. It is in our DNA. Sure, there is no 'one size fits all' or silver bullet and some are just boilerplate solutions, leveraged to the hilt and really only keeping us at a 30,000-foot-view of things. Being on-site, however, really allow us to get better granularity, find better directional-indicators, or loop back and dive deep into some critical issues on a go-forward basis.

I think if you all start spending more time in the office again, you'll find yourself trending toward the positive, but you'll have to keep an eye on the puck. Gut through it, reduce thrash, and let's stay in lock-step on this. Yes, we will synergize!

What's the root cause of the hatred of Corporate office spaces? I'll put my layman's hat on and guess that it comes from movies such as Office Space and Dilbert cartoons. But we all know that these are fictional spaces, and real office spaces allow us to touch base in a much more efficient manner.

I have to time-box this comment, as I have a hard-stop in a moment when I will have to jump onto a call. So, just one more point that I want to cover-off on: let's socialize the idea of having more office presence and loop back to see whether we're being more impactful. From a management standpoint, I think that we can get the traction to do it.

So, net/net, ignore the naysayers, sidebar the folks that are stuck in the weeds, and don't waste cycles or bandwidth on folks that don't align strongly with this mission. Try it out, and we'll have another touch point in a little while to see if we've moved the needle. Remember, our north star hasn't changed. We're still championing our core values remotely and we will only do it better in person.

If you need me, I will be online again in a bit.

**Comment by RTOChamp** [comment]
Also would the following issues have happened if people had been back in the office?

#40791 #43906 #39952 #36842 #38787 #40097 #19050 #18592 #15524 #33220 #18399 #19185 #18302 #41741 #43528 #30082 #23474 #18851 #40936 #38125 #28960 #38978 #15914 #15167 #29535 #24192 #29189 #21550 #37268 #45663 #33297 #45886 #42806 #21196 #27372 #36791 #21079 #27245 #34261 #17788 #18363 #31338 #26207 #35135 #19435 #41300 #35317 #24856 #21341 #41823 #35827 #16356 #27753 #29082 #22899 #41489 #21361 #43423 #29854 #45694 #26829 #23292 #26953 #19164 #28786 #27577 #46352 #40089

**Comment by Sboonny** [comment]
Thanks for pull request, please give https://contribute.freecodecamp.org/ 2 minutes of your time.

Have a good day and happy coding.

**Review by Sboonny — APPROVED** [review]

**Comment by JordanMooree** [comment]
Hi @vickyIee, thanks for this pull request. I think:
> "...where you can learn to code for free"

is sufficient given that anyone who views this markdown file will remotely view it anyway. I'm up for discussion on this one.

**Comment by Sembauke** [comment]
Thank you for opening this pull request.

This is a standard message notifying you that we've reviewed your pull request and have decided not to merge it. We would welcome future pull requests from you.

Thank you and happy coding.

**Pull request closed without merging**
