### PR TITLE
test: fix flaky redirect tests

### PR DESCRIPTION
**Pull request by ojeytonwilliams**

### CODE REVIEW

**Comment by nhcarrigan** [comment]
Unrelated to this PR, but is it worth noting that these tests will fail locally unless a contributor grabs and adds the `serve.json` manually?

**Comment by ojeytonwilliams** [comment]
@nhcarrigan good call.  Since the workflow is the source of truth here, I just referenced it.

**Comment by nhcarrigan** [comment]
image
Beautiful :)

**Review by naomi-lgbt — DISMISSED** [review]

**Comment by ojeytonwilliams** [comment]
9 seconds?  That's a bit more like it!

**Review by Sembauke — APPROVED** [review]

**Review by naomi-lgbt — APPROVED** [review]
I'm going to miss my creative test name 🙁

**Pull request merged**
