### PR TITLE
feat(tools): add warnings for filename-convention

### PR DESCRIPTION
**Pull request by raisedadead**
This PR will enforce the filename conventions that we keep recomending and often forget to follow ourselves. I intend to change the warning to an error once I audit and address the existing names

### CODE REVIEW

**Comment by ShaunSHamilton** [comment]
The warnings cause an exit of 1. Are the fixes going to be made in this PR? Or, one shortly after?

**Comment by raisedadead** [comment]
Yes – I will add a commit here.

**Comment by raisedadead** [comment]
I realized that adding one commit to the PR will make everyone's life difficult with merge conflicts in existing PRs. Instead, I will post the list here, and we should handle them in separate PRs before merging this.

That way, we can cut the noise a bit.

**Comment by raisedadead** [comment]
List of files to be handled

- [x] client/src/__mocks__/fileMock.ts
- [x] client/src/__mocks__/styleMock.ts
- [ ] client/src/assets/icons/API-icon.tsx
- [ ] client/src/assets/icons/D3-icon.tsx
- [ ] client/src/assets/icons/Database-icon.tsx
- [ ] client/src/assets/icons/FreeCodeCamp-logo.tsx
- [ ] client/src/assets/icons/JavaScript-icon.tsx
- [ ] client/src/assets/icons/Magnifier.tsx
- [ ] client/src/assets/icons/React-icon.tsx
- [ ] client/src/assets/icons/Tensorflow-icon.tsx
- [ ] client/src/assets/icons/inputReset.tsx
- [ ] client/src/components/Donation/walletsButton.tsx
- [ ] client/src/components/Header/components/Login.tsx
- [ ] client/src/components/Intro/components/IntroDescription.tsx
- [ ] client/src/components/SolutionViewer/ProjectModal.tsx
- [ ] client/src/components/SolutionViewer/SolutionViewer.tsx
- [ ] client/src/components/settings/Honesty.test.tsx
- [ ] client/src/pages/404.tsx
- [ ] client/src/redux/cookieValues.js
- [ ] client/src/redux/createStore.js
- [ ] client/src/redux/rootEpic.js
- [ ] client/src/redux/rootReducer.js
- [ ] client/src/redux/rootSaga.js
- [ ] client/src/templates/Challenges/components/Challenge-Description.tsx
- [ ] client/src/templates/Challenges/components/Hotkeys.tsx
- [ ] client/src/templates/Challenges/components/ResetModal.tsx
- [ ] client/src/templates/Challenges/components/VideoPlayer.tsx
- [ ] client/src/templates/Challenges/odin/Show.tsx
- [ ] client/src/templates/Challenges/projects/backend/Show.tsx
- [ ] client/src/templates/Challenges/projects/frontend/Show.tsx
- [ ] client/src/templates/Challenges/video/Show.tsx
- [ ] client/src/utils/analyticsStrings.test.ts
- [ ] client/src/utils/analyticsStrings.ts
- [ ] curriculum/getChallenges.acceptance.test.js
- [ ] curriculum/getChallenges.js
- [ ] curriculum/getChallenges.test.js
- [ ] curriculum/schema/challengeSchema.js
- [ ] curriculum/test/utils/challengeTitles.js
- [ ] curriculum/test/utils/mongoIds.js
- [ ] cypress/e2e/default/ShowCertification.js
- [ ] tools/challenge-editor/api/configs/superBlockList.ts
- [ ] tools/challenge-editor/api/interfaces/ChallengeData.ts
- [ ] tools/challenge-editor/api/interfaces/PartialMeta.ts
- [ ] tools/challenge-editor/api/interfaces/Tools.ts
- [ ] tools/challenge-editor/api/routes/blockRoute.ts
- [ ] tools/challenge-editor/api/routes/indexRoute.ts
- [ ] tools/challenge-editor/api/routes/saveRoute.ts
- [ ] tools/challenge-editor/api/routes/stepRoute.ts
- [ ] tools/challenge-editor/api/routes/superblockRoute.ts
- [ ] tools/challenge-editor/api/routes/toolsRoute.ts
- [ ] tools/challenge-editor/api/utils/getBlocks.ts
- [ ] tools/challenge-editor/api/utils/getStepContent.ts
- [ ] tools/challenge-editor/api/utils/getSteps.ts
- [ ] tools/challenge-editor/api/utils/saveStep.ts
- [ ] tools/challenge-editor/client/interfaces/Block.ts
- [ ] tools/challenge-editor/client/interfaces/ChallengeContent.ts
- [ ] tools/challenge-editor/client/interfaces/ChallengeData.ts
- [ ] tools/challenge-editor/client/interfaces/PropTypes.ts
- [ ] tools/challenge-editor/client/interfaces/SuperBlock.ts
- [ ] tools/challenge-editor/client/src/App.tsx
- [ ] tools/challenge-editor/client/src/components/block/Block.tsx
- [ ] tools/challenge-editor/client/src/components/buttons/CreateEmptySteps.tsx
- [ ] tools/challenge-editor/client/src/components/buttons/CreateNextStep.tsx
- [ ] tools/challenge-editor/client/src/components/buttons/DeleteStep.tsx
- [ ] tools/challenge-editor/client/src/components/buttons/InsertStep.tsx
- [ ] tools/challenge-editor/client/src/components/buttons/SaveChallenge.tsx
- [ ] tools/challenge-editor/client/src/components/buttons/UpdateStepTitles.tsx
- [ ] tools/challenge-editor/client/src/components/editor/Editor.tsx
- [ ] tools/challenge-editor/client/src/components/header/Header.tsx
- [ ] tools/challenge-editor/client/src/components/landing/Landing.tsx
- [ ] tools/challenge-editor/client/src/components/superblock/SuperBlock.tsx
- [ ] tools/challenge-editor/client/src/components/tools/Tools.tsx
- [ ] tools/challenge-editor/client/src/setupTests.ts
- [ ] tools/challenge-editor/client/src/utils/handleRequest.ts
- [ ] tools/scripts/seed/certifiedUserData.js
- [ ] tools/scripts/seed/seedAuthUser.js

**Comment by raisedadead** [comment]
<details>
<summary>Updated list</summary>

```
client/src/assets/icons/API-icon.tsx
client/src/assets/icons/D3-icon.tsx
client/src/assets/icons/Database-icon.tsx
client/src/assets/icons/FreeCodeCamp-logo.tsx
client/src/assets/icons/JavaScript-icon.tsx
client/src/assets/icons/Magnifier.tsx
client/src/assets/icons/React-icon.tsx
client/src/assets/icons/Tensorflow-icon.tsx
client/src/assets/icons/inputReset.tsx
client/src/components/Donation/walletsButton.tsx
client/src/components/Header/components/Login.tsx
client/src/components/Intro/components/IntroDescription.tsx
client/src/components/SolutionViewer/ProjectModal.tsx
client/src/components/SolutionViewer/SolutionViewer.tsx
client/src/components/settings/Honesty.test.tsx
client/src/pages/404.tsx
client/src/redux/cookieValues.js
client/src/redux/createStore.js
client/src/redux/rootEpic.js
client/src/redux/rootReducer.js
client/src/redux/rootSaga.js
client/src/templates/Challenges/components/Challenge-Description.tsx
client/src/templates/Challenges/components/Hotkeys.tsx
client/src/templates/Challenges/components/ResetModal.tsx
client/src/templates/Challenges/components/VideoPlayer.tsx
client/src/templates/Challenges/odin/Show.tsx
client/src/templates/Challenges/projects/backend/Show.tsx
client/src/templates/Challenges/projects/frontend/Show.tsx
client/src/templates/Challenges/video/Show.tsx
client/src/utils/analyticsStrings.test.ts
client/src/utils/analyticsStrings.ts
curriculum/getChallenges.acceptance.test.js
curriculum/getChallenges.js
curriculum/getChallenges.test.js
curriculum/schema/challengeSchema.js
curriculum/test/utils/challengeTitles.js
curriculum/test/utils/mongoIds.js
cypress/e2e/default/ShowCertification.js
tools/scripts/seed/certifiedUserData.js
tools/scripts/seed/seedAuthUser.j
```

</details>

**Comment by raisedadead** [comment]
<details>
<summary>Updated List</summary>

```
client/src/components/Donation/walletsButton.tsx
client/src/components/Header/components/Login.tsx
client/src/components/Intro/components/IntroDescription.tsx
client/src/components/SolutionViewer/ProjectModal.tsx
client/src/components/SolutionViewer/SolutionViewer.tsx
client/src/components/settings/Honesty.test.tsx
client/src/templates/Challenges/components/Challenge-Description.tsx
client/src/templates/Challenges/components/Hotkeys.tsx
client/src/templates/Challenges/components/ResetModal.tsx
client/src/templates/Challenges/components/VideoPlayer.tsx
client/src/templates/Challenges/odin/Show.tsx
client/src/templates/Challenges/projects/backend/Show.tsx
client/src/templates/Challenges/projects/frontend/Show.tsx
client/src/templates/Challenges/video/Show.tsx
client/src/utils/analyticsStrings.test.ts
client/src/utils/analyticsStrings.ts
curriculum/getChallenges.acceptance.test.js
curriculum/getChallenges.js
curriculum/getChallenges.test.js
curriculum/schema/challengeSchema.js
curriculum/test/utils/challengeTitles.js
curriculum/test/utils/mongoIds.js
cypress/e2e/default/ShowCertification.js
tools/scripts/seed/certifiedUserData.js
tools/scripts/seed/seedAuthUser.js
```

</details>

**Comment by raisedadead** [comment]
<details>
<summary>Updated List</summary>

```
client/src/components/Donation/walletsButton.tsx
client/src/components/Header/components/Login.tsx
client/src/components/Intro/components/IntroDescription.tsx
client/src/components/SolutionViewer/ProjectModal.tsx
client/src/components/SolutionViewer/SolutionViewer.tsx
client/src/components/settings/Honesty.test.tsx
client/src/templates/Challenges/components/Challenge-Description.tsx
client/src/templates/Challenges/components/Hotkeys.tsx
client/src/templates/Challenges/components/ResetModal.tsx
client/src/templates/Challenges/components/VideoPlayer.tsx
client/src/templates/Challenges/odin/Show.tsx
client/src/templates/Challenges/projects/backend/Show.tsx
client/src/templates/Challenges/projects/frontend/Show.tsx
client/src/templates/Challenges/video/Show.tsx
client/src/utils/analyticsStrings.test.ts
client/src/utils/analyticsStrings.ts
curriculum/getChallenges.acceptance.test.js
curriculum/getChallenges.js
curriculum/getChallenges.test.js
curriculum/schema/challengeSchema.js
tools/scripts/seed/certifiedUserData.js
tools/scripts/seed/seedAuthUser.js
```

</details>

**Comment by raisedadead** [comment]
<details>
<summary>Updated List</summary>

client/src/components/Donation/walletsButton.tsx
client/src/components/Header/components/Login.tsx
client/src/components/Intro/components/IntroDescription.tsx
client/src/components/SolutionViewer/ProjectModal.tsx
client/src/components/SolutionViewer/SolutionViewer.tsx
client/src/components/settings/Honesty.test.tsx
client/src/templates/Challenges/components/Challenge-Description.tsx
client/src/templates/Challenges/components/Hotkeys.tsx
client/src/templates/Challenges/components/ResetModal.tsx
client/src/templates/Challenges/components/VideoPlayer.tsx
client/src/templates/Challenges/odin/Show.tsx
client/src/templates/Challenges/projects/backend/Show.tsx
client/src/templates/Challenges/projects/frontend/Show.tsx
client/src/templates/Challenges/video/Show.tsx

</details>

**Comment by raisedadead** [comment]
This should be good to go - hopefully, as soon as we can. 

I intend to create a generic linter that can handle folder path names in the future. For now this should handle all filenames that we care about.

**Review by naomi-lgbt — APPROVED** [review]

**Review by Sboonny — APPROVED** [review]

**Pull request merged**
