### PR TITLE
Modified a typo in test case

### LINKED ISSUE #4967: Bonfire: Make A Person
I think there may be an issue with the following test in the Make A Person Bonfire:

```
bob.getFullName() should return "Bob Curry" after bob.setLastName("Curry")
```

After working my solution for a bit, I gave up and checked the solution posted on the [gitter help section](https://gitter.im/camperbot/bonfire-make-a-person) and tried the code. The test also failed on the posted solution. I included the solution below for convenience.

```js
var Person = function(firstAndLast) {
  var fullName = firstAndLast;

  this.getFirstName = function() {
    return fullName.split(" ")[0];
  };

  this.getLastName = function() {
    return fullName.split(" ")[1];
  };

  this.getFullName = function() {
    return fullName;
  };

  this.setFirstName = function(name) {
    fullName = name + " " + fullName.split(" ")[1];
  };

  this.setLastName = function(name) {
    fullName = fullName.split(" ")[0] + " " + name;
  };

  this.setFullName = function(name) {
    fullName = name;
  };
};

var bob = new Person('Bob Ross');
bob.getFullName();
```

### PR DESCRIPTION
**Pull request by gasperno**
Just changed the word Bob to Haskell.

Tested in local copy with chrome. All tests pass for the [solution](http://localhost:3001/challenges/bonfire-make-a-person?solution=var%20Person%20%3D%20function%28firstAndLast%29%20%7B%0A%20%20var%20fullName%20%3D%20firstAndLast%3B%0A%0A%20%20this.getFirstName%20%3D%20function%28%29%20%7B%0A%20%20%20%20return%20fullName.split%28%22%20%22%29%5B0%5D%3B%0A%20%20%7D%3B%0A%0A%20%20this.getLastName%20%3D%20function%28%29%20%7B%0A%20%20%20%20return%20fullName.split%28%22%20%22%29%5B1%5D%3B%0A%20%20%7D%3B%0A%0A%20%20this.getFullName%20%3D%20function%28%29%20%7B%0A%20%20%20%20return%20fullName%3B%0A%20%20%7D%3B%0A%0A%20%20this.setFirstName%20%3D%20function%28name%29%20%7B%0A%20%20%20%20fullName%20%3D%20name%20%2B%20%22%20%22%20%2B%20fullName.split%28%22%20%22%29%5B1%5D%3B%0A%20%20%7D%3B%0A%0A%20%20this.setLastName%20%3D%20function%28name%29%20%7B%0A%20%20%20%20fullName%20%3D%20fullName.split%28%22%20%22%29%5B0%5D%20%2B%20%22%20%22%20%2B%20name%3B%0A%20%20%7D%3B%0A%0A%20%20this.setFullName%20%3D%20function%28name%29%20%7B%0A%20%20%20%20fullName%20%3D%20name%3B%0A%20%20%7D%3B%0A%7D%3B%0A%0Avar%20bob%20%3D%20new%20Person%28%27Bob%20Ross%27%29%3B%0Abob.getFullName%28%29%3B) mentioned in the issue. 
Closes #4967

### CODE REVIEW

**Comment by gasperno** [comment]
I investigated the issue. I understood that the build failed because the test case below fails. 
> Make a Person: message: \<code>bob.getFullName()\</code> should return "Haskell Curry" after \<code>bob.setLastName("Curry")\</code>.

I ran the test cases separately by `npm run test-challenges`.  The test case that is run is..

> assert.strictEqual((function () { bob.setLastName(\"Curry\"); return bob.getFullName(); })(), 
> __'Haskell Curry'__, 'message: \<code>bob.getFullName()\</code> should return \"Haskell Curry\" after \<code>bob.setLastName(\"Curry\")\</code>.');

The test case passes when I use __'HaskellCurry'__ instead of 'Haskell Curry'.
But the test case passes when I use the same code in the UI editor via browser and hit Run Tests.

**Comment by SaintPeter** [comment]
I'm wondering if there is a problem with the solution?

Here is the model solution from within the file:
```js
var Person = function(firstAndLast) {

  var firstName, lastName;

  function updateName(str) {    
    firstName = str.split(" ")[0];
    lastName = str.split(" ")[1];    
  }

  updateName(firstAndLast);

  this.getFirstName = function(){
    return firstName;
  };
  
  this.getLastName = function(){
    return lastName;
  };
  
  this.getFullName = function(){
    return firstName + " " + lastName;
  };
  
  this.setFirstName = function(str){
    firstName = str;
  };
  

  this.setLastName = function(str){
    lastName = str;
  };
  
  this.setFullName = function(str){
    updateName(str);
  };
};

var bob = new Person('Bob Ross');
bob.getFullName();
```

The `getFullName` function looks correct.  I can't see why it would omit the space.

**Comment by BerkeleyTrue** [comment]
@SaintPeter Yeah it is super weird. It may be in the way the tests are run. Making the test less stateful fixed the issue. i.e.
```js
assert.strictEqual((function () { var _bob = new Person('Haskell Ross'); _bob.setLastName(\"Curry\"); return _bob.getFullName(); })(), 
'Haskell Curry', 'message: <code>bob.getFullName()</code> should return \"Haskell Curry\" after <code>bob.setLastName(\"Curry\")</code>.');

**Comment by gasperno** [comment]
@SaintPeter 
I ran the code using the solution in json file. Printing the full name after changing the bob's last name to __Curry__ results in 'Haskell Curry' as expected.

I could pass the test cases after modifying the code as @BerkeleyTrue suggested. I will edit this PR

**Comment by gasperno** [comment]
Hey, can you tell me if this PR is alright? I see six commits in the PR. I squashed two of my commits but this shows six of them.

**Comment by bugron** [comment]
@gasperno [Squashing multiple commits into one](https://github.com/FreeCodeCamp/FreeCodeCamp/wiki/git-rebase).

**Comment by SaintPeter** [comment]
@gasperno I think you may have erred.  You did a bare `git pull upstream` which caused you to create a commit.  Unfortunately, those can be hard to fix.
[How do maintin your local fork](https://github.com/FreeCodeCamp/FreeCodeCamp/wiki/How-To-Fork-And-Maintain-a-Local-Instance-of-Free-Code-Camp#maintaining-your-fork)

I suggest you do this:  
1. Close this PR
2. Make a copy of your modified file elsewhere on your filesystem
3. Go to your staging branch
4. `git reset --hard upstream staging` (assuming you have `upstream` configured as in the link above)
5. `git checkout -b fix/new-branch-to-work-on`
6. Copy your file back
7. Commit, etc.
8. Create a new PR

**Comment by gasperno** [comment]
Yes. Thanks for being patient. I did reset on my commits and pushed with a single commit. Still it is leading to another persons commit within my PR. I will close the commit as you suggested and start with a new one. Thanks.

**Pull request closed without merging**
