### PR TITLE
Auto-collapse superblock when it's challenges are hidden

### LINKED ISSUE #6414: Map's "show incomplete challenges" should hide empty chapters.
The button works great, but as it hides the unfinished stuff, it shouldn't leave a bunch of empty chapter titles behind. Ideally, for someone with just one challenge to complete, should see an almost empty map.
screen shot 2016-01-24 at 14 01 02

----
On a side note, shouldn't the completed challenges be hidden by default, and have the option to show them all instead?

### LINKED ISSUE #6575: Proper highlighting for completed challenges and their containers
As a follow up on #6414, and as per previous approval by @QuincyLarson in PR #6403:
The fully completed containers (otherwise known as superblocks), should add a `.faded` class to their containers, as shown at the bottom in the following screen capture.
This feature is slightly beyond my skills because of the involved detection for empty chapters...
Thus, "help wanted" applies.

screen shot 2016-01-29 at 09 01 47

------

Furthermore, The default behaviour for the map (or at least the sidebar's) should be that the completed ones are hidden, and then the button would let you see the hidden ones. I cannot think of any reason why any camper would by default want to see the completed from the beginning, when their common idea is to move forward.

This is a secondary idea and would indeed require Quincy's approval.

### LINKED ISSUE #6584: Remove show/hide incomplete challenges button from map
@bugron @hallaathrad

### LINKED ISSUE #6585: Never hide challenges in map (unless filtering using forthcoming realtime search)
@hallaathrad @bugron @SaintPeter

### PR DESCRIPTION
**Pull request by bugron**
And refactors a little bit the code.
Fixes #6585, fixes #6584 and closes #6575.
Closes #6414.

### CODE REVIEW

**Comment by hallaathrad** [comment]
at #6414 I was thinking more along the lines of actually making those empty blocks invisible... but I guess this could sort of do the trick.
However —and I don't know if this matters at the moment— when running your fork locally, challenges do not approve/submit/advance. Would that have anything to do with the changes you made?

**Comment by bugron** [comment]
@hallaathrad not sure why do you have such an issue (and what do you mean by saying `challenges do not approve/submit/advance`). I'm able to submit solutions and as you can see I've not changed anything on server side code or something else which may cause that. The only thing comes in my mind is that's related to your DB, maybe.

**Comment by hallaathrad** [comment]
If you have some time, we can do ScreenHero and I can show you what I mean.

**Comment by bugron** [comment]
Waiting for https://github.com/FreeCodeCamp/FreeCodeCamp/pull/6403 to be QA'd and merged.

**Comment by SaintPeter** [comment]
As per #6575, can a class of `.faded` be added to the superblock headers?

**Comment by SaintPeter** [comment]
Note also that #6403 has been merged.

**Comment by bugron** [comment]
@SaintPeter I've pushed today the amended code and it does add the class 'faded' to superblock headers. This PR works well on top of #6403. I'll try to include here the fix for #6575 too.

**Comment by bugron** [comment]
@SaintPeter @hallaathrad pushed. Now completed superblocks are faded but are **not** collapsed by default (this a one line fix if needed).

**Comment by hallaathrad** [comment]
That's the onload behaviour we talked about, right? would you PR on that separately, in order to close #6575, pending Quincy's approval/rejection?

**Comment by bugron** [comment]
@hallaathrad yes, this is it. If Quincy approves we'll merge that in this PR and will close both issues. Since the new PR will depend on this one I think it's better to keep one PR. Is this OK?

**Comment by hallaathrad** [comment]
I'd say since this one we have here has already been approved, we should get it out of the way and into staging ASAP. (I feel it's complementary with my previous, already merged one).

The other one is pending approval. And thus it may or not get rejected, pushing this one back.

@SaintPeter what's your take?

----
BTW, testing the latest amend...

**Comment by SaintPeter** [comment]
#6403 was merged . . unless you're talking about another one.  I think the right thing to do is ping @QuincyLarson and get approval on this change.  

Do we have a current complete screenshot?

**Comment by QuincyLarson** [comment]
I'm here. We could all do a quick screen hero call together if that works.

**Comment by bugron** [comment]
OK, summarizing:
 1. Completed challenges are now `.faded` and not `slightly-faded`.
 2. `Show all/incomplete challenges` button is removed entirely with it's functionality.
 3. Completed sections and superblocks are **collapsed** by default (we're ***not hiding*** anything anymore)

@QuincyLarson @hallaathrad @SaintPeter ready to be QA'd. Check if auto-scroll feature is working properly too.

**Comment by hallaathrad** [comment]
Killing spree!!!
--------

Closes #6575 #6584 #6585 #6414.

**Comment by SaintPeter** [comment]
Closing in lieu of #6592

**Pull request closed without merging**
