### PR TITLE
Fix the Markdown Syntax Error

### PR DESCRIPTION
**Pull request by tsunghanjacktsai**
Fix the Markdown Syntax which initially would make the code cause confusion.

- [x] I have read [freeCodeCamp's contribution guidelines](https://github.com/freeCodeCamp/freeCodeCamp/blob/master/CONTRIBUTING.md).
- [x] My pull request has a descriptive title (not a vague title like `Update index.md`)
- [x] My pull request targets the `master` branch of freeCodeCamp.
- [x] None of my changes are plagiarized from another source without proper attribution.
- [x] My article does not contain shortened URLs or affiliate links.

If your pull request closes a GitHub issue, replace the XXXXX below with the issue number.

Closes #XXXXX

### CODE REVIEW

**Review by amandeepmittal — APPROVED** [review]
LGTM!

**Comment by amandeepmittal** [comment]
**cc** @RandellDawson @raisedadead I do not have write access to the repository anymore. Please merge it or let me know whom to assign in case of PR I review?

**Comment by raisedadead** [comment]
Hi @amandeepmittal please reachout to us over a DM https://gitter.im/raisedadead

**Comment by RandellDawson** [comment]
Thank you for your contribution to the page! 👍
We're happy to accept these changes, and look forward to future contributions. 🎉

**Pull request merged**
