### PR TITLE
Add CSS Logo to file

### PR DESCRIPTION
**Pull request by yusuf-delvi**
- [x] I have read [freeCodeCamp's contribution guidelines](https://github.com/freeCodeCamp/freeCodeCamp/blob/master/CONTRIBUTING.md).
- [x] My pull request has a descriptive title (not a vague title like `Update index.md`)
- [x] My pull request targets the `master` branch of freeCodeCamp.
- [x] None of my changes are plagiarized from another source without proper attribution.
- [x] My article does not contain shortened URLs or affiliate links.

If your pull request closes a GitHub issue, replace the XXXXX below with the issue number.

Closes #XXXXX

### CODE REVIEW

**Comment by yusuf-delvi** [comment]
Add a CSS Logo to the file

**Comment by yusuf-delvi** [comment]
Added CSS Logo to the Markdown file

**Comment by honmanyau** [comment]
@yusuf-delvi I don't think the logo you have added is an official logo—and I seem to have difficulties confirming what the official logo is. Could you please comment on this?

**Comment by yusuf-delvi** [comment]
@honmanyau 
You are right I am really sorry can you help me where can I find an official logo.

**Comment by honmanyau** [comment]
@yusuf-delvi It's okay! I had a quick look and couldn't figure out what the official logo should be, or if there is one. I will close this PR since it doesn't appear to be something obvious and will take time to confirm; please feel free to open another PR if you have figured out what the logo is!

**Pull request closed without merging**
