### PR TITLE
fix(curriculum): Fixed typography in "Use body-parser to Parse POST Requests"

### LINKED ISSUE #39269: Errors in challenge description
**Describe your problem and how to reproduce it:**

The challenge says:

> In these kind of requests, the data doesn’t appear in the URL, it is hidden in the request body. This is a part of the HTML request, also called payload. Since HTML is text-based, even if you don’t see the data, it doesn’t mean that it is secret.

It should be “HTTP request”, not “HTML request”.

Also I don’t get the point in the third sentence “Since HTML is text-based, even if you don’t see the data, it doesn’t mean that it is secret”. What does HTML being text-based have to do with not seeing the data from a POST request? The response to an HTTP request doesn’t even necessarily have to be HTML, or even text-based. None of the examples up to this point has the response been HTML, but JSON. And how does HTML being text-based and not being able to see the data being sent in the request relate to the data being “secret” and why is that important?

**Add a Link to the page with the problem:**
[Use body-parser to Parse POST Requests](https://www.freecodecamp.org/learn/apis-and-microservices/basic-node-and-express/use-body-parser-to-parse-post-requests)

### PR DESCRIPTION
**Pull request by nakul251197**
Checklist:

- [x] I have read [freeCodeCamp's contribution guidelines](https://contribute.freecodecamp.org).
- [x] My pull request has a descriptive title (not a vague title like `Update index.md`)
- [x] My pull request targets the `master` branch of freeCodeCamp.
- [x] All the files I changed are in the same world language, for example: only English changes, or only Chinese changes, etc.

Closes #39269

The changes have been made in the challenge description of "Use body-parser to Parse POST Requests" to make it more informative.

### CODE REVIEW

**Review by ojeytonwilliams — APPROVED** [review]
LGTM :+1:

**Review by naomi-lgbt — APPROVED** [review]
LGTM!

**Review by RandellDawson — APPROVED** [review]

**Comment by RandellDawson** [comment]
Congrats @nakul251197 on your first pull request (PR)! 🎉

Thank you for your contribution to the page! 👍
We're happy to accept these changes, and look forward to future contributions. 📝

**Comment by RandellDawson** [comment]
@nakul251197 Note that you should not be creating PRs from your master branch.  Instead, you should create a separate branch off of master, then make your changes.  This keeps your master always in sync with Free Code Camp's master.

**Comment by nakul251197** [comment]
> @nakul251197 Note that you should not be creating PRs from your master branch. Instead, you should create a separate branch off of master, then make your changes. This keeps your master always in sync with Free Code Camp's master.

Thanks a lot! 
I'll keep this in mind from the next time.

**Pull request merged**
