### PR TITLE
fix(ui): update a link for new campers

### LINKED ISSUE #47206: "start at the beginning" link navigates to the legacy RWD
### Describe the Issue

When a new camper signs in and visits the top page of `/learn` , a message "If you are new to coding, we recommend you start at the beginning." is displayed.

But when they click the link, it will take them to the legacy RWD. I think we should switch it to the new RWD.

### Affected Page

https://www.freecodecamp.org/learn/

### Steps to Reproduce

1. Sign in with a new user (with less than 15 challenges completed, as far as I understand the code. I checked this behavior by creating a new GitPod workspace)
2. Go to /learn
3. Click the link "start at the beginning"
4. It will navigate to the first lesson of the **legacy** RWD

### Expected behavior

The link should take the camper to:
- The new RWD curriculum if the new RWD is translated for the current language
- The legacy RWD curriculum if the translation is not ready

### Screenshots

start-at-the-beginning

### System

- Device: Laptop
- OS: Windows 10
- Browser: Chrome
- Version: 104.0.5112.81

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by mmatsumoto1026**
Checklist:

- [x] I have read [freeCodeCamp's contribution guidelines](https://contribute.freecodecamp.org).
- [x] My pull request has a descriptive title (not a vague title like `Update index.md`)
- [x] My pull request targets the `main` branch of freeCodeCamp.
- [x] I have tested these changes either locally on my machine, or GitPod.

Closes #47206

Update "start at the beginning" link so it can navigate new campers to the first challenge of new Responsive Web Design Certification in the audited language environments.

The code have been tested in all language environment via setting `CLIENT_LOCALE` and `CURRICULUM_LOCAL` in `.env` and previewed locally.

Affected page:  
[https://www.freecodecamp.org/learn/](https://www.freecodecamp.org/learn/)

### CODE REVIEW

**Review by moT01 — COMMENTED** [review]
I may have spoke too soon on the issue. This looks good and works, but I think we could filter for `superOrder = 0` along with the `challengeOrder` and `order`. Then we wouldn't need to check if the cert is audited and it would be more dynamic. What do you think @mmatsumoto1026?

**Comment by mmatsumoto1026** [comment]
@moT01 I agree. So I comitted the modified query and code which have again been tested and previewed in all language environment locally.  Thank you.

**Review by naomi-lgbt — APPROVED** [review]
This is looking good. Nice work!

__
[sema-logo](https://semasoftware.com/gh) &nbsp;**Summary:** :ok_hand: This code looks good

**Review by moT01 — APPROVED** [review]
LGTM @mmatsumoto1026 🎉 Thanks for contributing to freeCodeCamp 🎉

**Comment by mmatsumoto1026** [comment]
Thanks @moT01. It's owe to your appropriate advice.

**Pull request merged**
