### PR TITLE
test(e2e,playwright): blocked.tsx

### PR DESCRIPTION
**Pull request by grbknr1996**
Checklist:

- [x] I have read and followed the [contribution guidelines](https://contribute.freecodecamp.org).
- [x] I have read and followed the [how to open a pull request guide](https://contribute.freecodecamp.org/#/how-to-open-a-pull-request).
- [x] My pull request targets the `main` branch of freeCodeCamp.
- [x] I have tested these changes either locally on my machine, or GitPod.

image
Solves Pages-blocked.tsx #51705 
for hacktoberfest 2023
@hacktober24 
@raisedadead

### CODE REVIEW

**Comment by grbknr1996** [comment]
bazingaa

**Comment by grbknr1996** [comment]
Please review my code .Thanks :) in advance

**Comment by raisedadead** [comment]
Hi, @grbknr1996 - Thanks for taking the time to contribute. 

After carefully considering it, we have decided to proceed with another PR now. I encourage you to focus on other hacktoberfest-related tasks and PRs. 

If you're interested, we have more issues across other projects available for you to work on.

I appreciate your understanding. Happy contributing! You've got this.

**Comment by grbknr1996** [comment]
Thanks @raisedadead will try to be more specific on ids when I write e2e test cases. Happy learning :)

**Pull request closed without merging**
