### PR TITLE
fix(curriculum): Rewrite of Create Reusable CSS with Mixins module

### PR DESCRIPTION
**Pull request by irfanzainudin**
Checklist:

- [x] I have read and followed the [contribution guidelines](https://contribute.freecodecamp.org).
- [x] I have read and followed the [how to open a pull request guide](https://contribute.freecodecamp.org/#/how-to-open-a-pull-request).
- [x] My pull request targets the `main` branch of freeCodeCamp.
- [x] I have tested these changes either locally on my machine, or GitPod.

Closes #50155 

As per @lasjorg's suggestions, I removed any references to vendor prefixing as they are unnecessary and outdated.

In this rewrite, I kept the general structure of the challenge text but modified to suit the new example code. However, I didn't use the `@mixin` prose example given by @lasjorg as I think it'll be better to build on the previous challenges. So I did my own simple example about individual styles on headings, which is covered in previous challenges.

As for the task itself, I used @lasjorg's suggestion with some add-ons.

Tagging @naomi-lgbt for visibility.

Also, I messed up my git commits so there's multiple commits in my branch. I'm not sure if that's acceptable, apologies. Please let me know if I have to fix it.

I've opened a PR before this one, but because I messed up my commit history, the previous PR got closed so I'm opening this new one, very sorry for the inconveniences.

Thank you!

### CODE REVIEW

**Comment by lasjorg** [comment]
@irfanzainudin I forgot about this PR, sorry.

I think we should shorten the example a bit, it's a bit much right now.

Just the single `h1` heading is enough. I don't think we need to give a realistic example of something that would require extra work/code duplication to maintain.

**Comment by ojeytonwilliams** [comment]
Hi @irfanzainudin if you've got a moment, could you address @lasjorg's concerns?

**Comment by Sembauke** [comment]
Hey @lasjorg,
Can you take this one over?

**Comment by lasjorg** [comment]
@Sembauke I will create a new PR, I have a few other changes I want to make. I will keep the requirements and tests from this PR.

**Pull request closed without merging**
