### PR TITLE
Fix typo on OOP challenge

### LINKED ISSUE #18091: Typo in OOP challenge
**Challenge**: Remember to Set the Constructor Property when Changing the Prototype

**Problem**
For the Dog constructor is says
`numLegs: 2,`
Can we change it to say `numLegs: 4` ?
**Link**
https://learn.freecodecamp.org/javascript-algorithms-and-data-structures/object-oriented-programming/remember-to-set-the-constructor-property-when-changing-the-prototype/

### PR DESCRIPTION
**Pull request by jeffersonataide**
#fix: 
numLegs: 2 to numLegs: 4 

on challenge:
 Remember to Set the Constructor Property when Changing the Prototype

- [X] I have read [freeCodeCamp's contribution guidelines](https://github.com/freeCodeCamp/freeCodeCamp/blob/master/CONTRIBUTING.md).
- [X] My pull request has a descriptive title (not a vague title like `Update index.md`)
- [X] My pull request targets the `master` branch of freeCodeCamp.
- [X] None of my changes are plagiarized from another source without proper attribution.
- [X] My article does not contain shortened URLs or affiliate links.

If your pull request closes a GitHub issue, replace the XXXXX below with the issue number.

Closes #18091

### CODE REVIEW

**Comment by ezioda004** [comment]
Hi @jefferson2z,
Thank you for opening this PR. However, this is not a bug. 
This is the [challenge](https://learn.freecodecamp.org/javascript-algorithms-and-data-structures/object-oriented-programming/remember-to-set-the-constructor-property-when-changing-the-prototype/) and the existing solution is correct.
Though I agree the challenge text can be improved.
Anyway, feel free to open new PR's in future.

**Comment by ezioda004** [comment]
Hi @jefferson2z,
I've reopened the PR. 
As I can see you're updating as per the issue https://github.com/freeCodeCamp/freeCodeCamp/issues/18091. I don't think you need to update the description ie the Bird Prototype (it should still have 2 legs), only the Dog Prototype needs to update which you've already done.

**Comment by jefferson2z** [comment]
I have updated so that the bird prototype has 2 legs again, leaving the dog with 4 legs.

**Review by ezioda004 — APPROVED** [review]
LGTM 👍

**Comment by ezioda004** [comment]
Thank you @jefferson2z for your contribution and congrats on your first PR merge to this repo.

**Pull request merged**
