### PR TITLE
Basic Javascript waypoints translated into ES [WIP]

### PR DESCRIPTION
**Pull request by eabedrapo**
Basic JavaScript waypoints translated into Spanish [WIP].

### CODE REVIEW

**Comment by BerkeleyTrue** [comment]
@eabedrapo Thanks! Let us know when it is ready to be merged.

**Comment by eabedrapo** [comment]
Freezing my translation as I'm waiting a small fix for the 3rd WP ;)

Thanks!

**Comment by eabedrapo** [comment]
I'll start over to avoid conflicts with the latest changes in the file.

Closing this pull.

**Comment by BerkeleyTrue** [comment]
Hello @eabedrapo Please make changes to master branch. We are currently moving to Loopback on staging and a lot of files have moved around. We will be merge changes to master into staging while transitioning.

**Comment by eabedrapo** [comment]
Whops... I just sent a PR to Stage... now I'll close it and send a PR to master.

Thanks @BerkeleyTrue!

**Pull request closed without merging**
