### PR TITLE
feat(challenges): Updated project euler problem

### PR DESCRIPTION
**Pull request by alvinkl**
added more assertion and tweaked the task

#### Pre-Submission Checklist

- [x] Your pull request targets the `staging` branch of freeCodeCamp.
- [x] Branch starts with either `fix/`, `feature/`, or `translate/` (e.g. `fix/signin-issue`)
- [x] You have only one commit (if not, [squash](http://forum.freecodecamp.com/t/how-to-squash-multiple-commits-into-one-with-git/13231) them into one commit).
- [x] All new and existing tests pass the command `npm test`. Use `git commit --amend` to amend any fixes.

#### Type of Change

- [ ] Small bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds new functionality)
- [ ] Breaking change (fix or feature that would change existing functionality)
- [ ] Add new translation (feature adding new translations)

#### Checklist:

- [x] Tested changes locally.
- [ ] Closes currently open issue (replace XXXX with an issue no): Closes #XXXX

#### Description

Updated, added more assertion for problem 21

### CODE REVIEW

**Comment by alvinkl** [comment]
I don't know how to put the solution,
I put the solution in the array but it always return errors on npm run test
```javascript
function sumAmicableNumbers(n) {
  let div = {};

  const getDivisorSum = (num) => {
    let res = [];

    for (let i = 0; i < num; i++) {
      if (num % i === 0) {
        res.push(i);
      }
    }
    return res.reduce((prev, curr) => prev + curr, 0);
  };

  for (let i = 0; i < n; i++) {
    div[i] = getDivisorSum(i);
  }

  let amic = [];
  for (let i = 0; i < n; i++) {
    var sum = div[i];
    if (i === div[sum] && div[sum] !== sum) {
      amic.push(i);
    }
  }

  return amic.reduce((prev, curr) => prev + curr, 0);
}```

**Comment by MarcDearden** [comment]
Please stop sending emails, I am getting 35 emails a day it's ridiculous.
Do you think that anyone is going to read all these emails. You are sending
that many that they go straight in the bin.

**Comment by MarcDearden** [comment]
I don't want anymore emails because you are sending 35-40 emails a day. Who in their right mind wants all these emails? I don't even read them anymore I just delete them. You are driving me crazy as every time you send me an email my watch notifies me, you are sending that many that I'm having to charge my watch every day. What are you trying to achieve by sending all these emails? I have clicked the undo thread and every time you say that I have done this already but within a couple of minutes another email comes, please advise me what I am supposed to do to stop them. I can hear them coming all night, so as you can appreciate it is driving me crazy. I hope that you are able to stop sending me emails.
Yours Sincerely 
Marc Dearden

**Comment by texas2010** [comment]
@MarcDearden 
looks like you may have accidentally subscribed to all notifications for the [FreeCodeCamp](https://github.com/FreeCodeCamp/FreeCodeCamp) repository. To stop receiving notifications please visit the [subscriptions page](https://github.com/FreeCodeCamp/FreeCodeCamp/subscription) and select "Not watching". Additionally, you can visit the [GitHub Help page on managing notification delivery methods](https://help.github.com/articles/managing-notification-delivery-methods/) for more help.

We are sorry for your inconvenience!

**Comment by QuincyLarson** [comment]
@alvinkl I was able to get this to pass using `// noprotect` at the top. The reason it wasn't working for you is because of our infinite loop protection.

We will have to address the infinite loop protection later. Some of these Project Euler problems are computationally intense. Anyway, this one is good to go. Thanks for your contribution!

**Pull request merged**
