### PR TITLE
docs(component-library): Fix typo in table

### PR DESCRIPTION
**Pull request by Kinzume**
Checklist:

- [x] I have read [freeCodeCamp's contribution guidelines](https://contribute.freecodecamp.org).
- [x] My pull request has a descriptive title (not a vague title like `Update index.md`)
- [x] My pull request targets the `main` branch of freeCodeCamp.
- [x] I have tested these changes either locally on my machine, or GitPod.

Hi all, I've fixed a typo in the contribution docs for the [component library](https://contribute.freecodecamp.org/#/how-to-work-on-the-component-library?id=implementing-the-component). Thank you!

### CODE REVIEW

**Review by gikf — APPROVED** [review]
Looks good :+1:

**Comment by gikf** [comment]
Hey @Kinzume you don't need to keep merging latest changes from `main`. Unless there are merge conflicts, PR will be merged cleanly. Otherwise all it does is makes require running CI checks once more.

**Comment by Kinzume** [comment]
Thanks @gikf for letting me know! Will keep that in mind for future PRs 😊

**Review by Nirajn2311 — APPROVED** [review]

**Comment by Nirajn2311** [comment]
Hi @Kinzume . Congrats on your first pull request (PR)! 🎉

Thank you for your contribution to the page! 👍
We are happy to accept these changes and look forward to future contributions. 📝

**Comment by Kinzume** [comment]
Hi @Nirajn2311 @gikf thanks for approving my PR! Looking forward to contributing more in the future 👍

**Pull request merged**
