### PR TITLE
chore: use constants for superblocks

### PR DESCRIPTION
**Pull request by ShaunSHamilton**
- [x] I have read [freeCodeCamp's contribution guidelines](https://contribute.freecodecamp.org).
- [x] My pull request has a descriptive title (not a vague title like `Update index.md`)
- [x] My pull request targets the `main` branch of freeCodeCamp.
- [x] I have tested these changes either locally on my machine, or GitPod.

I have been meaning to do this for a while. This should be one of the easiest ways we can keep track of superblocks and make comparisons like `if superBlock === 'yada'...`

### CODE REVIEW

**Review by ojeytonwilliams — COMMENTED** [review]
Some initial thoughts

- Let's not add any more tsconfigs if we can avoid it.  We `extend` configs if need be (probably we don't).
- If we need to emit .js files then they'll need to be .gitignore'd

**Comment by ShaunSHamilton** [comment]
> Let's not add any more tsconfigs if we can avoid it.

I was not sure why we have more than 1 anyway.

How should I go about TypeScript-ing these directories? Should we just have a `config/tsconfig.json` which is used for all directories (that we need/want)? Or, a root `tsconfig.json`?

**Comment by nhcarrigan** [comment]
Pretty sure https://github.com/freeCodeCamp/freeCodeCamp/pull/43886/commits/9d20ccdcd16a385e6cc0cadfb929610c0d35e3c6 is going to fix some issues that I was having on another PR. 💜

**Review by ojeytonwilliams — DISMISSED** [review]
LGTM :+1:

**Review by ojeytonwilliams — DISMISSED** [review]

**Pull request merged**
