### PR TITLE
fix(client): Prevent saving invalid portfolio item

### PR DESCRIPTION
**Pull request by igorctorres**
Checklist:

- [x] I have read and followed the [contribution guidelines](https://contribute.freecodecamp.org).
- [x] I have read and followed the [how to open a pull request guide](https://contribute.freecodecamp.org/#/how-to-open-a-pull-request).
- [x] My pull request targets the `main` branch of freeCodeCamp.
- [x] I have tested these changes either locally on my machine, or GitPod.

Unsaved portfolio item is being saved when updating an existing one, bypassing any validation.
This commit removes the unsaved item from portfolio before saving it, while the unsaved item is kept in state so user can keep editing it.

This bug was referenced on this comment: https://github.com/freeCodeCamp/freeCodeCamp/issues/49132#issuecomment-1476031123

### CODE REVIEW

**Comment by Sboonny** [comment]
Thank you for taking care of this, although in the future we can take care of this by creating two endpoints in the new API, your fix is welcomed 👍.

----

One nitpick, campers can update the existing items, when they create a new card in the profile page.


[rec-tab (1).webm](https://user-images.githubusercontent.com/88248797/233397969-413aff3a-d34a-49f6-b1fa-5cdec9a46bf7.webm)

**Comment by igorctorres** [comment]
> One nitpick, campers can update the existing items, when they create a new card in the profile page.

That's the current behavior and I don't see it as a problem.
When you update existing items, the new item is not saved along. The new item is temporarily removed from portfolio while the existing items are being saved. Then it is added back to the portfolio as a new item.

**Comment by Sembauke** [comment]
@igorctorres Sorry for the lack of response. So as you can see from Sboonny's video, there seems to be a bug which adds the values of the previous card to the next one.

Though, the behaviour that is desired is to disable the ability to make new cards before saving the currently edited one. This should erase the above behaviour.

If you are still interested in developing this feature, then, go right ahead. If you are not, you can expect us to help. Please let us know.

Thank you, happy coding.

**Comment by Sembauke** [comment]
Hey @igorctorres

Thank you for taking the time to open this pull-request. Due to inactivity we will open this to other contributors. Feel free to revisit.

**Pull request closed without merging**
