### PR TITLE
Hyperdev has been renamed: update twitch pass-through link

### LINKED ISSUE #11934: FCC Twitch API Pass-through not returning JSON
#### Challenge Name

[Twitch JSON API Challenge](https://www.freecodecamp.com/challenges/use-the-twitchtv-json-api)

#### Issue Description

The link for the FCC Twitch Pass Through API no longer returns valid JSON (regardless if callback request is passed). Returns a web page containing a note about the usage (screenshot below). Multiple users have reported similar issue.

https://wind-bow.hyperdev.space/twitch-api/streams/freecodecamp?callback=?
https://wind-bow.hyperdev.space/twitch-api/streams/freecodecamp

#### Browser Information

* Browser Name, Version: Safari 9.1.3; Chrome 54.0.2840
* Operating System: OS X El Capitan

#### Screenshot

screen shot 2016-12-05 at 4 41 39 pm

### PR DESCRIPTION
**Pull request by Em-Ant**
#### Pre-Submission Checklist

- [x] Your pull request targets the `staging` branch of FreeCodeCamp.
- [x] Branch starts with either `fix/`, `feature/`, or `translate/` (e.g. `fix/signin-issue`)
- [x] You have only one commit (if not, [squash](http://forum.freecodecamp.com/t/how-to-squash-multiple-commits-into-one-with-git/13231) them into one commit).
- [ ] All new and existing tests pass the command `npm test`. Use `git commit --amend` to amend any fixes.

#### Type of Change

- [x] Small bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds new functionality)
- [ ] Breaking change (fix or feature that would change existing functionality)
- [ ] Add new translation (feature adding new translations)

#### Checklist:

- [x] Tested changes locally.
- [x] Closes currently open issue (replace XXXX with an issue no): Closes #11934

#### Description

Hyperdev has been renamed to **gomix** . This PR updates the twitch api pass through server link from https://wind-bow.hyperdev.space/twitch-api to https://wind-bow.gomix.me/twitch-api

### CODE REVIEW

**Comment by BerkeleyTrue** [comment]
@Em-Ant Thanks! Does hyperdev redirect to gomix?

**Comment by atjonathan** [comment]
@BerkeleyTrue, yeah it does.

**Comment by tommygebru** [comment]
Ok this affirms the change, but is there a fix in place to update the link here?
https://www.freecodecamp.com/challenges/use-the-twitchtv-json-api
because it has been the old url for 2 days now

**Comment by Manish-Giri** [comment]
@tommygebru I think the [change in the description](https://github.com/FreeCodeCamp/FreeCodeCamp/blob/9a6eb99ed0f8197c5c675f04584c8431b24227a9/seed/challenges/01-front-end-development-certification/intermediate-ziplines.json#L171) has already been made on the `staging` branch. The current live site is on the `backup/staging` branch, so when the `staging` changes go in, this should be resolved.

**Comment by tommygebru** [comment]
awesome, thanks Manish

**Comment by Em-Ant** [comment]
https://github.com/FreeCodeCamp/FreeCodeCamp/pull/11968 this should fix the link rapidly.

**Pull request merged**
