### PR TITLE
</li> closing tag

### PR DESCRIPTION
**Pull request by DavidNachman**
- [x] I have read [freeCodeCamp's contribution guidelines](https://github.com/freeCodeCamp/freeCodeCamp/blob/master/CONTRIBUTING.md).
- [x] My pull request has a descriptive title (not a vague title like `Update index.md`)
- [x] My pull request targets the `master` branch of freeCodeCamp.
- [x] None of my changes are plagiarized from another source without proper attribution.
- [x] My article does not contain shortened URLs or affiliate links.

If your pull request closes a GitHub issue, replace the XXXXX below with the issue number.

Closes #XXXXX

### CODE REVIEW

**Comment by RandellDawson** [comment]
Closed and Reopened this PR to attempt to resolve a specific Travis build failure.

**Comment by RandellDawson** [comment]
Hi @DavidNachman 

Thank you for opening this pull request.

What you have stated is not as accurate as it could be.  You need to mention the exceptions to the rule:

* The `</li>` can be omitted if immediately followed by another `li` element
* If there is no more content in the parent element.

Please make these changes, so we can consider merging your pull request. 

Thank you and happy coding.

**Comment by DavidNachman** [comment]
> Hi @DavidNachman
> 
> Thank you for opening this pull request.
> 
> What you have stated is not as accurate as it could be. You need to mention the exceptions to the rule:
> 
> * The `</li>` can be omitted if immediately followed by another `li` element
> * If there is no more content in the parent element.
> 
> Please make these changes, so we can consider merging your pull request.
> 
> Thank you for your input. I have made your requested changes.

**Comment by RandellDawson** [comment]
Thank you for your contribution to the page! 👍
We're happy to accept these changes, and look forward to future contributions. 🎉

**Pull request merged**
