### PR TITLE
fix: change toggle style and improve responsiveness

### LINKED ISSUE #36641: Slight tweak to settings style
With the new command line chic changes, the text in the toggle buttons is aligned a bit strangely. For example, for Quincy's email:

QuincysEmail

might look nicer as follows:

QuincysEmailUpdated

For the privacy settings:
SettingsButtons
My changes are to the top button.

Specifically, I would make both sides of the toggle button the same width and centre the text inside them.

I'd be happy to take this on, if people think it's a good change.

### PR DESCRIPTION
**Pull request by ojeytonwilliams**
- [x] I have read [freeCodeCamp's contribution guidelines](https://github.com/freeCodeCamp/freeCodeCamp/blob/master/CONTRIBUTING.md).
- [x] My pull request has a descriptive title (not a vague title like `Update index.md`)
- [x] My pull request targets the `master` branch of freeCodeCamp.
- [x] None of my changes are plagiarized from another source without proper attribution.
- [x] All the files I changed are in the same world language (for example: only English changes, or only Chinese changes, etc.)
- [x] My changes do not use shortened URLs or affiliate links.

This is to give us a concrete change to the toggle style to compare with what we currently have.  In addition to the changes discussed in #36641 there are three fixes.

* `white-space: pre-line` to ensure buttons with lots of text don't overflow.
* `margin-left: -2px;` for the margins between two `.btn` elements since the border is `2px` wide.
* `border-color: var(--tertiary-color);` instead of `--secondary-color` for the border since the background is already `--secondary-color`.

Obviously if any of those are not actually bugs, let me know and I'll revert them.

One thing I wasn't too sure on was the alignment of the buttons with the label text.  Center them both vertically, maybe?  I.e. `justify-content: center` rather than `flex-start`.

If anyone wants to see any of the other suggestions we discussed, let me know and I'll add extra commits with them.

Closes #36641

### CODE REVIEW

**Review by moT01 — COMMENTED** [review]
Overall, I think this is definitely better, my only real concern is small screens...
Screen Shot 2019-08-21 at 11 40 50 AM
It feels like it's unnecessarily taking up a lot of vertical space. Perhaps if we kept the buttons inline and moved them below the text.
Of course, I would rather see it like this, than having the text get cut off. 

Also, I did prefer the border color to be the same as the backgrounds - even though you can hardly notice the difference - my opinion.

But, I think this is enough of an improvement to add if we want.

**Comment by ojeytonwilliams** [comment]
We can definitely try putting the buttons below the text, as @ahmadabdolsaheb originally suggested.  It'll still take up a lot of vertical space, mind.  We could also bring the buttons a tad closer, though not *too* close, since they need to be clicked on mobile.

I don't have a strong opinion about the border colour, I just assumed that both toggled and untoggled buttons should have visible borders.

Anyway, thanks for the review.  I'll make the changes soon.

**Comment by moT01** [comment]
Yea, it wouldn't save any vertical space, would it. Well, it seem like there's wasted space there anyway.

**Comment by moT01** [comment]
This should close https://github.com/freeCodeCamp/freeCodeCamp/issues/36594 as well.

**Comment by ojeytonwilliams** [comment]
> Yea, it wouldn't save any vertical space, would it. Well, it seem like there's wasted space there anyway.

It might when there's a lot of text, but mostly no.  Still worth trying, even if only to see if it looks better.

**Comment by ojeytonwilliams** [comment]
The commit could have been worded better - 'reduce repetition' isn't right.  What I actually did was make things more homogeneous by putting the Night Mode toggle in a form like every other toggle.

Next commit will put the toggles below the text.

**Comment by ojeytonwilliams** [comment]
The last two commits are the most polished.

The penultimate one looks like this on mobile:
StackedMobileS5
Though it's not shown, all the ticks are on the same side, as @RandellDawson suggested,

The final commit like this:
SingleLineButtonsS5

**Review by raisedadead — APPROVED** [review]

**Pull request merged**
