### PR TITLE
Correct typo for computer basics question.

### LINKED ISSUE #9646: videos/computer-basics-measuring-data-speed Q1: bits -> bits/sec
#### Challenge Name

https://www.freecodecamp.com/videos/computer-basics-measuring-data-speed

#### Issue Description

The first question: Data speed is measured in bits. True or False?

The correct answer should be false (but is currently true). Data speed is measured in bits per second.

### PR DESCRIPTION
**Pull request by refinedblessing**
#### Pre-Submission Checklist

- [x] Your pull request targets the `staging` branch of FreeCodeCamp.
- [x] Branch starts with either `fix/`, `feature/`, or `translate/` (e.g. `fix/signin-issue`)
- [x] You have only one commit (if not, [squash](https://github.com/FreeCodeCamp/FreeCodeCamp/wiki/Git-Squash) them into one commit).
- [x] All new and existing tests pass the command `npm run test-challenges`. Use `git commit --amend` to amend any fixes.
#### Type of Change

- [x] Small bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds new functionality)
- [ ] Breaking change (fix or feature that would change existing functionality)
- [ ] Add new translation (feature adding new translations)
#### Checklist:

- [x] Tested changes locally.
- [x] Closes currently open issue (replace XXXX with an issue no): Closes #9646
#### Description

I corrected [this question](https://github.com/FreeCodeCamp/FreeCodeCamp/blob/b4f108c1afa8bbb30fdeb4e3c81e409eef91f0df/seed/challenges/04-video-challenges/computer-basics.json#L373), [this text](https://github.com/FreeCodeCamp/FreeCodeCamp/blob/b4f108c1afa8bbb30fdeb4e3c81e409eef91f0df/seed/challenges/04-video-challenges/computer-basics.json#L365) and [this other question](https://github.com/FreeCodeCamp/FreeCodeCamp/blob/b4f108c1afa8bbb30fdeb4e3c81e409eef91f0df/seed/challenges/04-video-challenges/computer-basics.json#L379) from using `bits` to `bits per second` as a measure for data speed.

### CODE REVIEW

**Comment by Bouncey** [comment]
**LGTM** :+1: 

Thanks for contributing :tada:

**Comment by Bouncey** [comment]
@andela-bebowe Can you please do the Spanish translation also? A google translate should be fine, as it is such a small adjustment.

Remember to `git commit --amend` so you don't end up with multiple commits.

**Comment by andela-bebowe** [comment]
@Bouncey Spanish translation of what part exactly the commit message or the code ?

**Comment by Bouncey** [comment]
Thank you @andela-bebowe :+1:

**Comment by andela-bebowe** [comment]
I am very excited to have done this task its my first open source contribution, and I hope to do more. @Bouncey

**Pull request merged**
