### PR TITLE
docs: add README.japanese.md

### PR DESCRIPTION
**Pull request by danbileee**
- [x] I have read [freeCodeCamp's contribution guidelines](https://github.com/freeCodeCamp/freeCodeCamp/blob/master/CONTRIBUTING.md).
- [x] My pull request has a descriptive title (not a vague title like `Update index.md`)
- [x] My pull request targets the `master` branch of freeCodeCamp.
- [x] None of my changes are plagiarized from another source without proper attribution.
- [x] All the files I changed are in the same world language (for example: only English changes, or only Chinese changes, etc.)
- [x] My changes do not use shortened URLs or affiliate links.

Closes #XXXXX

### CODE REVIEW

**Comment by RandellDawson** [comment]
@raisedadead I missed this one, because it did not have a documentation label on it.  Once you merge PR #36716, then I will add another commit to this PR to move the file to the applicable `docs` sub-folder and rename it to `README.md`. I will notify you once the PR is ready to merge (as I will not be able to merge it).

**Review by raisedadead — APPROVED** [review]

**Comment by raisedadead** [comment]
@RandellDawson I have pre-approved this for you.

**Comment by blocktobody** [comment]
I think I've accidentally closed this PR. I was just trying to update my forked repository. Sorry to bother, but what should I do now?

**Comment by raisedadead** [comment]
No, worries @blocktobody. I have re-opened it. You do not need to do anything. We will get this merged as it is. Thanks for the PR.

**Comment by blocktobody** [comment]
> No, worries @blocktobody. I have re-opened it. You do not need to do anything. We will get this merged as it is. Thanks for the PR.

Okay, got it. Thank you.

**Comment by RandellDawson** [comment]
@raisedadead No file was added to the repo.

**Comment by raisedadead** [comment]
Side effect of this: https://github.com/freeCodeCamp/freeCodeCamp/issues/36718, my apologies.

**Comment by raisedadead** [comment]
Oh no wait not because of that, the OP deleted their fork. 🤦‍♂

**Comment by RandellDawson** [comment]
I assume there is nothing that can be done, since the user deleted the fork?

**Comment by RandellDawson** [comment]
When you merged it, I guess it did not have the file on it anymore.

**Comment by raisedadead** [comment]
I guess so. :(

**Comment by RandellDawson** [comment]
I am not really sure how it got removed, since there was no rebase of the PR itself (from what I can tell).

**Pull request merged**
