### PR TITLE
App "listens" before 'MongoStore' is ready fix

### PR DESCRIPTION
**Pull request by ghost**
fix for #224

### CODE REVIEW

**Comment by BerkeleyTrue** [comment]
Not liking moving server launch into a middleware. I would prefer the timeout on the gulpfile to be increased.

**Comment by jameskopacz** [comment]
Is this the setting to change the time out? https://github.com/FreeCodeCamp/freecodecamp/blob/master/gulpfile.js#L8

**Comment by BerkeleyTrue** [comment]
yeah that's the one. Create a new PR with changes to gulpfile and close this one.

**Comment by jameskopacz** [comment]
It's not working. Tried 10000 and even 30000.

**Comment by BerkeleyTrue** [comment]
Not running into this on my system. Could be something else is the issue.

**Comment by jameskopacz** [comment]
Here's the error from command line:

> Error: Error getting collection: sessions
    at E:\freecodecamp\node_modules\connect-mongo\lib\connect-mongo.js:160:19
    at nrCallbackWrap (E:\freecodecamp\node_modules\newrelic\lib\instrumentation\mongodb.js:305:27)
    at wrapped (E:\freecodecamp\node_modules\newrelic\lib\transaction\tracer\index.js:156:28)
    at wrappedCallback (E:\freecodecamp\node_modules\newrelic\lib\transaction\tracer\index.js:401:66)
    at wrapped (E:\freecodecamp\node_modules\newrelic\lib\transaction\tracer\index.js:156:28)
    at Db.collection (E:\freecodecamp\node_modules\mongodb\lib\mongodb\db.js:524:27)
    at Db.wrapped (E:\freecodecamp\node_modules\newrelic\lib\transaction\tracer\index.js:156:28)
    at segmentWrapper (E:\freecodecamp\node_modules\newrelic\lib\instrumentation\mongodb.js:300:55)
    at wrapped (E:\freecodecamp\node_modules\newrelic\lib\transaction\tracer\index.js:156:28)
    at Tracer.addSegment (E:\freecodecamp\node_modules\newrelic\lib\transaction\tracer\index.js:66:48)

**Comment by BerkeleyTrue** [comment]
If you set it to 30 seconds then it definitely isn't a timing issue. If you run `node app.js` instead of gulp do you run into the same issue?

**Comment by jameskopacz** [comment]
Yeah, it can happen with ```node app.js```:
```
E:\freecodecamp>node app.js
FreeCodeCamp server listening on port 3000 in development mode
GET / - - ms - -
GET / - - ms - -
Error: Error getting collection: sessions
    at E:\freecodecamp\node_modules\connect-mongo\lib\connect-mongo.js:160:19
    at nrCallbackWrap (E:\freecodecamp\node_modules\newrelic\lib\instrumentation\mongodb.js:305:27)
    at wrapped (E:\freecodecamp\node_modules\newrelic\lib\transaction\tracer\index.js:156:28)
    at wrappedCallback (E:\freecodecamp\node_modules\newrelic\lib\transaction\tracer\index.js:401:66)
    at wrapped (E:\freecodecamp\node_modules\newrelic\lib\transaction\tracer\index.js:156:28)
    at Db.collection (E:\freecodecamp\node_modules\mongodb\lib\mongodb\db.js:524:27)
    at Db.wrapped (E:\freecodecamp\node_modules\newrelic\lib\transaction\tracer\index.js:156:28)
    at segmentWrapper (E:\freecodecamp\node_modules\newrelic\lib\instrumentation\mongodb.js:300:55)
    at wrapped (E:\freecodecamp\node_modules\newrelic\lib\transaction\tracer\index.js:156:28)
    at Tracer.addSegment (E:\freecodecamp\node_modules\newrelic\lib\transaction\tracer\index.js:66:48)
```

**Comment by BerkeleyTrue** [comment]
I just pushed a new commit to master. This deactivates newrelic during development. Can you run gulp again and see if the stack trace changes?

**Comment by jameskopacz** [comment]
```
E:\freecodecamp>gulp
[00:37:08] Using gulpfile E:\freecodecamp\gulpfile.js
[00:37:08] Starting 'serve'...
[gulp] [nodemon] v1.3.7
[gulp] [nodemon] to restart at any time, enter `rs`
[gulp] [nodemon] watching: *.*
[gulp] [nodemon] starting `node ./app.js`
[00:37:10] Finished 'serve' after 2.02 s
[00:37:10] Starting 'sync'...
[00:37:10] Finished 'sync' after 37 ms
[00:37:10] Starting 'default'...
[00:37:10] Finished 'default' after 4.22 µs
FreeCodeCamp server listening on port 3000 in development mode
[BS] Proxying: http://localhost:3000
[BS] Now you can access your site through the following addresses:
[BS] Local URL: http://localhost:3001
[BS] External URL: http://192.168.0.121:3001
[BS] Watching files...
GET / 200 160.862 ms - 16480
Error: Error getting collection: sessions
    at E:\freecodecamp\node_modules\connect-mongo\lib\connect-mongo.js:160:19
    at Db.collection (E:\freecodecamp\node_modules\mongodb\lib\mongodb\db.js:524:27)
    at MongoStore._get_collection (E:\freecodecamp\node_modules\connect-mongo\lib\connect-mongo.js:158:17)
    at MongoStore.set (E:\freecodecamp\node_modules\connect-mongo\lib\connect-mongo.js:274:12)
    at Session.save (E:\freecodecamp\node_modules\express-session\session\session.js:71:25)
    at Session.save (E:\freecodecamp\node_modules\express-session\index.js:315:15)
    at ServerResponse.end (E:\freecodecamp\node_modules\express-session\index.js:273:21)
    at ServerResponse.send (E:\freecodecamp\node_modules\express\lib\response.js:195:10)
    at fn (E:\freecodecamp\node_modules\express\lib\response.js:934:10)
    at View.exports.renderFile [as engine] (E:\freecodecamp\node_modules\jade\lib\index.js:374:12)
GET / 200 636.391 ms - 16480
```

**Comment by BerkeleyTrue** [comment]
try `rm -rf node_modules` and `npm install`. Then `gulp`.

**Comment by jameskopacz** [comment]
I'm on windows but I think that's just to delete the node_modules folder? Running npm install now

**Comment by jameskopacz** [comment]
```
E:\freecodecamp>gulp
[00:50:06] Using gulpfile E:\freecodecamp\gulpfile.js
[00:50:06] Starting 'serve'...
[gulp] [nodemon] v1.3.7
[gulp] [nodemon] to restart at any time, enter `rs`
[gulp] [nodemon] watching: *.*
[gulp] [nodemon] starting `node ./app.js`
[00:50:08] Finished 'serve' after 2.02 s
[00:50:08] Starting 'sync'...
[00:50:08] Finished 'sync' after 34 ms
[00:50:08] Starting 'default'...
[00:50:08] Finished 'default' after 5.72 µs
FreeCodeCamp server listening on port 3000 in development mode
GET / - - ms - -
Error: Error getting collection: sessions
    at E:\freecodecamp\node_modules\connect-mongo\lib\connect-mongo.js:160:19
    at Db.collection (E:\freecodecamp\node_modules\mongodb\lib\mongodb\db.js:524:27)
    at MongoStore._get_collection (E:\freecodecamp\node_modules\connect-mongo\lib\connect-mongo.js:158:17)
    at MongoStore.get (E:\freecodecamp\node_modules\connect-mongo\lib\connect-mongo.js:222:10)
    at session (E:\freecodecamp\node_modules\express-session\index.js:392:11)
    at Layer.handle [as handle_request] (E:\freecodecamp\node_modules\express\lib\router\layer.js:82:5)
    at trim_prefix (E:\freecodecamp\node_modules\express\lib\router\index.js:302:13)
    at E:\freecodecamp\node_modules\express\lib\router\index.js:270:7
    at Function.proto.process_params (E:\freecodecamp\node_modules\express\lib\router\index.js:321:12)
    at next (E:\freecodecamp\node_modules\express\lib\router\index.js:261:10)
GET / - - ms - -
[BS] Proxying: http://localhost:3000
[BS] Now you can access your site through the following addresses:
[BS] Local URL: http://localhost:3001
[BS] External URL: http://192.168.0.121:3001
[BS] Watching files...
```

**Comment by BerkeleyTrue** [comment]
It's hard to figure out the exact cause of this. Since @QuincyLarson, @terakilobyte and myself run into this, I am guessing this might be a windows issue. You could try using node-inspector a try and trace the problem (seems like an async issue, that is why the stack trace isn't as helpful).

**Comment by BerkeleyTrue** [comment]
I am going to close this PR since this isn't going to fix the issue. Lets continue this discusion in https://github.com/FreeCodeCamp/freecodecamp/issues/224

**Comment by QuincyLarson** [comment]
@BerkeleyTrue I would agree - this is probably a windows or environment configuration issue. You're running MongoDB, right?

**Comment by jameskopacz** [comment]
Yeah, MongoDB is running. The site runs just sometimes this happens.

**Pull request closed without merging**
