### PR TITLE
Added reference to Raspberry pi and desktop ATX

### PR DESCRIPTION
**Pull request by purifyyourhome**
Modified "Types of Motherboards" section to point to how ATX is common mostly for desktop and server computers.  Mentioned how many Single Board Computers such as the Raspberry Pi use their own form factor not based off the ATX standard.

- [ ] I have read [freeCodeCamp's contribution guidelines](https://github.com/freeCodeCamp/freeCodeCamp/blob/master/CONTRIBUTING.md).
- [ ] My pull request has a descriptive title (not a vague title like `Update index.md`)
- [ ] My pull request targets the `master` branch of freeCodeCamp.
- [ ] None of my changes are plagiarized from another source without proper attribution.
- [ ] My article does not contain shortened URLs or affiliate links.

If your pull request closes a GitHub issue, replace the XXXXX below with the issue number.

Closes #XXXXX

### CODE REVIEW

**Review by cmccormack — APPROVED** [review]
This looks good to me 👍.  Thank you for your contribution!

**Review by METALMAN01 — COMMENTED** [review]
I read on different types of ATX I use a very nice HP I1LULA4. No problem there and it's only about a month old very clean.

**Comment by METALMAN01** [comment]
I see what mean about the changes in ATX I just got a little caught up.

**Comment by METALMAN01** [comment]
PURIFIED

**Comment by METALMAN01** [comment]
I would only join a team on GitHub if it was needed.

**Comment by RandellDawson** [comment]
@METALMAN01 Please stop making random comments. 

Thank you.

**Pull request merged**
