### PR TITLE
fix(curriculum) Added numbered options for easy reference 

### PR DESCRIPTION
**Pull request by dineshkottaKota**
Checklist:

- [x] I have read and followed the [contribution guidelines](https://contribute.freecodecamp.org).
- [x] I have read and followed the [how to open a pull request guide](https://contribute.freecodecamp.org/how-to-open-a-pull-request/).
- [x] My pull request targets the `main` branch of freeCodeCamp.
- [x] I have tested these changes either locally on my machine, or GitPod.

Closes #XXXXX

### CODE REVIEW

**Comment by dineshkottaKota** [comment]
Added numbered options for easy reference

**Comment by gikf** [comment]
Hey

Thank you for opening this pull request.

This is a standard message notifying you that we've reviewed your pull request and have decided not to merge it. We would welcome future pull requests from you.

Thank you and happy coding.

**Comment by dineshkottaKota** [comment]
@ilenia-magoni please don't label my PR as spam. This is my first hactoberfest and by labelling as spam, I may disqualify from hactoberfest

**Comment by ilenia-magoni** [comment]
see https://github.com/freeCodeCamp/freeCodeCamp/pull/56654#issuecomment-2408500023 for the answer

**Pull request closed without merging**
