### PR TITLE
fix: a typo in ga-saga.test.js

### PR DESCRIPTION
**Pull request by felixonmars**
Checklist:

- [x] I have read [freeCodeCamp's contribution guidelines](https://contribute.freecodecamp.org).
- [x] My pull request has a descriptive title (not a vague title like `Update index.md`)
- [x] My pull request targets the `main` branch of freeCodeCamp.
- [x] I have tested these changes either locally on my machine, or GitPod.

### CODE REVIEW

**Comment by Sembauke** [comment]
Hey @lavindersingh931

Thank you for opening this pull request.

This is a standard message notifying you that we've reviewed your pull request and have decided not to merge it. We would welcome future pull requests from you. I suggest you first read our documentation at contribute.freecodecamp.org.

Thank you and happy coding.

**Comment by felixonmars** [comment]
Hi, I did have read the contributing guidelines and followed it. I don't think this pull request is `invalid` though, or perhaps you should add something like "small doc fixes are not welcomed"?

**Comment by ieahleen** [comment]
LGTM 👍

**Review by majestic-owl448 — APPROVED** [review]

**Review by Sembauke — APPROVED** [review]

**Comment by Sembauke** [comment]
We have discussed your PR for a second time, and decided to merge it!

Sorry for the inconvenience @felixonmars.

Have a nice day and happy coding.

**Pull request merged**
