### PR TITLE
Feature: Render spinner whilst app loads

### LINKED ISSUE #9735: Progress Visualization for clean UX experience
For a user, who visits the website (initial loads on a fresh device), certain UI elements take a while to populate.

Example:
1. Login, the profile image takes a couple of seconds to appear on the navbar
2. The map aside takes a couple of seconds to populate and displays "No Superblocks" 
3. Challenges views at times take a second to render.

Although these happen seamlessly from the next interaction with the elements. Hence we might as well think of having some form of progress to present the blocking nature of the UI.

### PR DESCRIPTION
**Pull request by Bouncey**
#### Pre-Submission Checklist

- [x] Your pull request targets the `staging` branch of FreeCodeCamp.
- [x] Branch starts with either `fix/`, `feature/`, or `translate/` (e.g. `fix/signin-issue`)
- [x] You have only one commit (if not, [squash](http://forum.freecodecamp.com/t/how-to-squash-multiple-commits-into-one-with-git/13231) them into one commit).
- [x] All new and existing tests pass the command `npm test`. Use `git commit --amend` to amend any fixes.

#### Type of Change

- [ ] Small bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds new functionality)
- [ ] Breaking change (fix or feature that would change existing functionality)
- [ ] Add new translation (feature adding new translations)

#### Checklist:

- [x] Tested changes locally.
- [x] Closes currently open issue (replace XXXX with an issue no): Closes #9735

#### Description

Render spinner whilst challenges are being pulled from the db

### CODE REVIEW

**Comment by BerkeleyTrue** [comment]
Why are you showing a loading screen on the main challenge view? These are server side rendered.

**Comment by Bouncey** [comment]
Point No.3 in #9735 

Even though they are rendered server side, the app hangs whilst entities resolves. The loading screen just eases the transition

**Comment by BerkeleyTrue** [comment]
> Even though they are rendered server side, the app hangs whilst entities resolves. The loading screen just eases the transition

So are able to replicate this issue and this PR solves it? Because `areChallengeLoaded` has no bearing on wether the current challenge is in the data or not.

**Comment by Bouncey** [comment]
Yes I can replicate the issue and the PR solves it.

`areChallengesLoaded` is derived from `superBlocks.length`, which is updated in the reducer by `fetchChallengesCompleted`.

The `fetchChallengesCompleted` action is dispatched by `fecth-challenges-saga`

Is this not related to challenges being in the store?

**Comment by Bouncey** [comment]
If I navigate directly to a challenge, I find the UI is blocked in the same way as described in #9735

**Comment by BerkeleyTrue** [comment]
> Is this not related to challenges being in the store?

The challenge on the page is loaded sever side. `areChallengesLoaded` only effects the map and all challenges minus what is on the current page. 

> If I navigate directly to a challenge, I find the UI is blocked 

fill_in_the_blank_with_placeholder_text___free_code_camp_

If I turn off javascript, I can clearly see that there is data loaded on the page.

Maybe the issue is that codemirror does not render server side. This has nothing to do with whether the other challenges are loaded or not.

**Comment by Bouncey** [comment]
Im not disagreeing that the data for the current challenge is there on initial load, but the UI is blocked whilst `entities` resolves.

Before `entities` resloves:
User profile picture and brownie points are absent from the header. 
codemirror is not rendered.
I do not have consistent scrolling of the instructions.

These three issues resolve themselves at the same time `entities` resolves.

So I thought that, instead of showing in incomplete/blocking UI, we should render a spinner instead, to indicate that the UI isn't quite ready yet.

If you would prefer I could refactor it to check that each part of entities is resolved before the challenge is rendered. But seeing as the `challenges` section is the largest, would it not be reasonable to presume it takes the longest of them all?

**Comment by Bouncey** [comment]
I also understand that entities has no direct effect on codemirror rendering, but it does have an effect on `challenge.viewType`

**Comment by BerkeleyTrue** [comment]
> but the UI is blocked whilst entities resolves.

This is not the cause for rendering to block, it may seem like it but it just a correlation. 

> I also understand that entities has no direct effect on codemirror rendering, but it does have an effect on challenge.viewType

viewType is derived from the current challenge, which does not change until the challenge changes. fetchChallengesComplete does not have an effect on this. If you where to remove the fetchChallenges call you would see this. 

> If you would prefer I could refactor it to check that each part of entities is resolved

This does not get to the cause of the issue.

**Comment by Bouncey** [comment]
So we need to find what is blocking the render then. I'll close this and move the discussion back to the original issue.

**Comment by BerkeleyTrue** [comment]
Any easy way to see that this is not the reason for the block is to add

```js
 .delay(5000)
```

right before this https://github.com/FreeCodeCamp/FreeCodeCamp/blob/staging/common/app/routes/challenges/redux/fetch-challenges-saga.js#L55 line

**Pull request closed without merging**
