### PR TITLE
chore(curriculum): update survey form challenge ids

### LINKED ISSUE #607: Challenge http://www.freecodecamp.com/challenges/waypoint-check-radio-buttons-and-checkboxes-by-default has an issue
Gives an error while trying to add checked to first radio and checkbox
Syntax error, unrecognized expression
Syntax error, unrecognized expression

code for form
```
<form action="/submit-cat-photo">
  <label><input type='radio' name='indoor-outdoor' checked> Indoor</label>
  <label><input type='radio' name='indoor-outdoor'> Outdoor</label>
  <br>
  <label><input type='checkbox' name='personality' checked> Loving</label>
  <label><input type='checkbox' name='personality'> Lazy</label>
  <label><input type='checkbox' name='personality'> Crazy</label>
  <br>
  <input type='text' placeholder='cat photo URL' required>
  <button type='submit'>Submit</button>
</form>
```

### LINKED ISSUE #607: chore: update ids for survey form lab in main repo
The survey form lab ids need to be updated to use the same ids from the RWD project here

https://www.freecodecamp.org/learn/2022/responsive-web-design/build-a-survey-form-project/build-a-survey-form

### PR DESCRIPTION
**Pull request by zairahira**
Checklist:

- [x] I have read and followed the [contribution guidelines](https://contribute.freecodecamp.org).
- [x] I have read and followed the [how to open a pull request guide](https://contribute.freecodecamp.org/how-to-open-a-pull-request/).
- [x] My pull request targets the `main` branch of freeCodeCamp.
- [x] I have tested these changes either locally on my machine, or GitPod.

Closes https://github.com/freeCodeCamp/CurriculumExpansion/issues/607

### CODE REVIEW

**Review by ojeytonwilliams — COMMENTED** [review]
Silly question, probably, but what was wrong with the old one?

**Comment by zairahira** [comment]
This lab was based on an existing project in the curriculum. If a camper has already done the existing one, it would be marked completed here as well.

**Review by moT01 — APPROVED** [review]
LGTM 🎉

**Review by ojeytonwilliams — APPROVED** [review]
Thanks for explaining, Zaira. LGTM :+1:

**Pull request merged**
