### PR TITLE
fix: responsive videos

### PR DESCRIPTION
**Pull request by ojeytonwilliams**
Credit to @jeffehobbs for the css, which works beautifully.

@ahmadabdolsaheb it's slightly smaller on desktop (because it now stays within its box). I'm not sure if it was intended to be a little larger.

### CODE REVIEW

**Comment by ahmadabdolsaheb** [comment]
This works beautifully.

**Comment by ahmadabdolsaheb** [comment]
You can have the player in a different column 10 with 1 offset to make it larger?

**Comment by raisedadead** [comment]
Can this move out of draft or closed if not needed anymore?

**Comment by ojeytonwilliams** [comment]
@ahmadabdolsaheb I played with a few column settings and this looked nicest to me.  The video stays slightly larger than the text beneath it until the screen is small enough, when it expands to full width.  Let me know if you like this version.

**Review by ahmaxed — APPROVED** [review]

**Pull request merged**
