### PR TITLE
fix: add a ; to the end of the example code in a markdown file

### PR DESCRIPTION
**Pull request by christophszcz**
- [x] I have read [freeCodeCamp's contribution guidelines](https://github.com/freeCodeCamp/freeCodeCamp/blob/master/CONTRIBUTING.md).
- [x] My pull request has a descriptive title (not a vague title like `Update index.md`)
- [x] My pull request targets the `master` branch of freeCodeCamp.
- [x] None of my changes are plagiarized from another source without proper attribution.
- [x] My article does not contain shortened URLs or affiliate links.

This PR adds a semi-colon to one of the code examples in the use-destructuring-assignment-to-assign-variables-from-objects.english.md file. I did not test this live on my local machine.

### CODE REVIEW

**Comment by farisoft** [comment]
Seems okay from my end!

And convinced with the passed build and approving to be merged.

**Comment by lynxlynxlynx** [comment]
The example works without this trivial change, so I'm baffled why you even changed it.

**Comment by christophszcz** [comment]
Hi @lynxlynxlynx and @farisoft, thank you for reviewing my PR. I understand that the example works without this requested change. However, for aesthetic purposes, to show that it is best to use semicolons even in ES6 and to keep the markup consistent with the other examples (which contain semi-colons), my reasoning for this change is to keep it congruent with the other text.

**Review by paulywill — APPROVED** [review]
Good eye!

This change keeps things consistent.

**Review by ezioda004 — APPROVED** [review]
LGTM
@lynxlynxlynx as mentioned by @RandellDawson we use semicolon after expressions (where applicable) across all JS code (curriculum/guide) for consistency.

**Comment by ezioda004** [comment]
Thank you @christophszcz for your contribution and congratulations on your first PR merge to this repo! 🎉
Hope to see more contributions from you in the future.

**Pull request merged**
