### PR TITLE
fix: align sponsors and give background

### LINKED ISSUE #35450: Sponsor page logo images don't load with ad blocker active
For some reason my ad blocker is blocking our S3 images of these sponsor's from loading.

sponsors_who_help_freecodecamp_through_financial_and_in-kind_sponsorship___freecodecamp_org

Also note that some of the images are not transparent but rather have white backgrounds - which means they look bad in night mode. Even if they were transparent, their colors would look bad in night mode, so we might want to redesign how this page looks in night mode.

sponsors_who_help_freecodecamp_through_financial_and_in-kind_sponsorship___freecodecamp_org

### PR DESCRIPTION
**Pull request by ahmaxed**
- [x] I have read [freeCodeCamp's contribution guidelines](https://github.com/freeCodeCamp/freeCodeCamp/blob/master/CONTRIBUTING.md).
- [x] My pull request has a descriptive title (not a vague title like `Update index.md`)
- [x] My pull request targets the `master` branch of freeCodeCamp.
- [x] None of my changes are plagiarized from another source without proper attribution.
- [x] All the files I changed are in the same world language (for example: only English changes, or only Chinese changes, etc.)
- [x] My changes do not use shortened URLs or affiliate links.

Closes #35450

### CODE REVIEW

**Comment by ahmadabdolsaheb** [comment]
before:
53505776-884f3d80-3aef-11e9-943f-9725c219987c


After:
screen shot 2019-03-04 at 12 59 30 pm
screen shot 2019-03-04 at 12 59 45 pm

**Comment by Bouncey** [comment]
That's nice! Is the new layout the same in the default theme?

**Comment by thecodingaviator** [comment]
Looks great! Are we pushing this for production or this would be frozen for now and would release with the next release after the one we're prepping for?

**Comment by ahmadabdolsaheb** [comment]
@Bouncey thanks, Yes.
@thecodingaviator thanks, not sure.

**Comment by Bouncey** [comment]
@thecodingaviator This is a fix, so it is not affected by the feature freeze. 

The feature freeze puts a hold on new features entering the code base. Fixes and chores are still important to merge before the release.

**Pull request merged**
