### PR TITLE
fix(curriculum): move RDBMS cert to proper order

### PR DESCRIPTION
**Pull request by moT01**
This moves the Relational Database cert to right after the Data Viz. In order to do this I...
- Added 1 to the `order` in all the `meta/{superBlock}-certificate/meta.json` files from API's and Microservices on. This is the certificate order.
- Added 1 to the `superOrder` in all the `meta/{block}/meta.json` files for all blocks from API's and Microservices and on. This is the order of the superBlock each block belongs to.

Side addition: In **all** the `meta/{superBlock}-certificate/meta.json` files, I change the `superOrder` to `0`. This is the `certificate` superblock and is not shown anywhere. Changing it to zero should keep it from getting in the way in the future. I didn't see any issues with it.

You will need to set `showUpcomingChange` to `true` in the `.env` to see it. Everything seems to be working whether or not they are shown.

Checklist:

- [x] I have read [freeCodeCamp's contribution guidelines](https://contribute.freecodecamp.org).
- [x] My pull request has a descriptive title (not a vague title like `Update index.md`)
- [x] My pull request targets the `main` branch of freeCodeCamp.
- [x] I have tested these changes either locally on my machine, or GitPod.

Related to #42509

### CODE REVIEW

**Review by naomi-lgbt — APPROVED** [review]
This is looking good on my end.

**Review by ShaunSHamilton — CHANGES_REQUESTED** [review]
I am quite confused why this test did not fail: https://github.com/freeCodeCamp/freeCodeCamp/blob/main/cypress/integration/landing.js#L61

Either way, this cert should be added to: https://github.com/freeCodeCamp/freeCodeCamp/blob/main/cypress/integration/landing.js#L10

And we should change this hard-coding to:
```diff
  it('Has links to all the certifications', function () {
-    cy.get(selectors.certifications).children().its('length').should('eq', 10);
+    cy.get(selectors.certifications).children().its('length').should('eq', certifications.length);
```

**Comment by moT01** [comment]
> I am quite confused why this test did not fail

Pretty sure it's cause the cert is an upcoming change - so it does not get loaded for the tests.

**Review by 3zrv — APPROVED** [review]

**Review by ShaunSHamilton — APPROVED** [review]
LGTM 👍

**Pull request merged**
