### PR TITLE
Corrected description of Truncate a String bonfire.

### LINKED ISSUE #4706: Wrong description in truncate a string bonfire question.
In the question description the following section -
" If the length of the string is less than or equal to 3 characters, then the length of the three dots is not added to the string length.".
This should be stated as follwoing to get the code accepted -
" If the num is less than 3, then the length of the three dots is not added to the string length."
I had solved all the problems in algorithm scripting but this one because according to previous description my code was not getting accepted.
As soon as I wrote the code for the new description I got my code accepted.

### PR DESCRIPTION
**Pull request by AryanJ-NYC**
Close #4706

### CODE REVIEW

**Comment by SaintPeter** [comment]
Discussing this in CurriculumDevelopment

**Comment by bugron** [comment]
@AryanJ-NYC thanks for the PR but, please, check before opening a PR if there is already another one (https://github.com/FreeCodeCamp/FreeCodeCamp/pull/4708) opened which fixes the same issue. 
I think **`num`** can't be less than or equal to `3 characters`, it can be less than or equal to `3`.

**Comment by AryanJ-NYC** [comment]
@bugron I understand another PR was open.  I waited a few days for it to be amended; when I saw it wasn't, I went ahead and made my own PR.

**Comment by ltegman** [comment]
After the change @bugron suggested is made I'm happy to merge this. It solves the issue at hand. Further rewrites of this challenge can be handled in a further PR desired.

**Comment by ltegman** [comment]
Thanks for the quick update @AryanJ-NYC! :+1:

**Pull request merged**
