### PR TITLE
Fixes Spelling of Cinammon to Cinnamon on steps 54-92 RWD beta, issue #44596

### LINKED ISSUE #44596: RWD Beta, Create Cafe Menu, Cinnamon is spelled wrong.
## Affected page

Problem begins at Step 53 and continues throughout the rest of the tutorial (Step 92)
https://www.freecodecamp.org/learn/2022/responsive-web-design/learn-basic-css-by-building-a-cafe-menu/step-53

## To reproduce

Am able to see in private browsing mode too. 

## Recommended fix, suggestions

Wherever the code is located that has the word "Cinammon", fixing the spelling error so it's "Cinnamon". 

## Screenshots
First page it's incorrect.
Screen Shot 2021-12-27 at 10 34 39 AM

Last page, showing it's still incorrect.
Screen Shot 2021-12-27 at 10 35 17 AM

### PR DESCRIPTION
**Pull request by xoxoKaralee**
Checklist:

- [x ] I have read [freeCodeCamp's contribution guidelines](https://contribute.freecodecamp.org).
- [x ] My pull request has a descriptive title (not a vague title like `Update index.md`)
- [ x] My pull request targets the `main` branch of freeCodeCamp.
- [ x] I have tested these changes either locally on my machine, or GitPod.

Closes #44596

fixed spelling for steps 54-92

### CODE REVIEW

**Comment by xoxoKaralee** [comment]
hi, i dont know how to undo the most recent commit. I'm completely new to this and I wanted to try to fix another thing. I dont know how to remove the other commit

**Comment by gikf** [comment]
Hey @xoxoKaralee,

it is recommended to make changes on a separate branch, than the `main` branch. See more about it in point 3 at https://contribute.freecodecamp.org/#/how-to-setup-freecodecamp-locally?id=making-changes-locally.

To remove commit from this PR, it will be needed to remove it first locally and then push branch again, with the `--force` option as it requires changing history of branch. There's couple ways for removing commit, one might be using `reset` command, another one using interactive rebasing. Let me know if you'd need a more detailed guidance.

**Comment by xoxoKaralee** [comment]
I used gitpod, which was the other way suggested. I've never done any of this before, and thought i was committing to my own github fork first, then was going to make a new pull request with that commit? Again, I apologize. It's my first time with all of this. Any help or guidance is much appreciated

**Comment by gikf** [comment]
@xoxoKaralee because each PR can consist of multiple commits, PRs are made on branch basis, one branch is merged into another.

---

Here are more detailed guidelines. We are going to clean up your `main` branch, and create two new branches for each of these changes. There's some going back and forth here, but it's a nice practice for getting some familiarity with git.

Starting off with making new branch:
```bash
git checkout main
git checkout -b fix/add-missing-word
```
On this branch we will keep only the second change, because it's based off current `main` we need to remove other, not needed, commits from it. To do so, we are going to use interactive rebasing, for it we need to find commit that's made just before first wanted change in this PR. Looking at branch history - https://github.com/xoxoKaralee/freeCodeCamp/commits/main - we can use commit _chore(deps): update dependency eslint-plugin-jest-dom to v3.9.4_ with c52f5d6 hash.
```bash
git rebase -i c52f5d6
```
This command will open editor, with list of commits made since the commit we are rebasing on. Change `pick` to `drop` for all commits other than the one adding _Channel_ word. After saving file and closing editor, git will perform rebasing, this shouldn't require any additional actions, and when it completes one branch is ready.

This branch could be now pushed to remote repository (your fork) and be used for creating PR.

Next, the branch correcting _cinnamon_, using the same approach and the same commit for rebasing:
```bash
git checkout main
git checkout -b fix/cinnamon-spelling
git rebase -i c52f5d6
```
Similarly like with previous branch rebasing, change `pick` to `drop` for all listed commits, that should not be a part of this branch. After completing rebasing this branch also is now ready.

Finally, to clean up the `main` branch. This could be made in similar manner as the changes above, but  for the sake of showing another way of doing this, we are going to use `reset` command here.
```bash
git checkout main
git reset --hard c52f5d6
```
This basically discards from the branch any commit made after c52f5d6. Making the `main` branch in sync with the `freeCodeCamp:main` branch. And to push `main` branch back to your fork, it's needed to use the `--force` option, as we rewrote history of it:
```bash
git push --force origin main
```

**Pull request closed without merging**
