### PR TITLE
Incorrect error thrown when function is in comments

### LINKED ISSUE #10925: Doesn't see my comments
Challenge [Comment your JavaScript Code](https://www.freecodecamp.com/challenges/comment-your-javascript-code#?solution=%2F%2F%20d%20regularly%20add%20comments%20to%20clarify%20the%20function%20of%20parts%20of%20your%20code.%20Good%20commenting%20can%20help%20communicate%20the%20intent%20of%20your%20code%E2%80%94both%20for%20oth%0A%0A%2F*%20d%20regularly%20add%20comments%20to%20clarify%20the%20function%20of%20parts%20of%20your%20code.%20Good%20commenting%20can%20help%20communicate%20the%20intent%20of%20your%20code%E2%80%94both%20for%20oth%20*%2F%0A%0A) has an issue.
User Agent is: <code>Mozilla/5.0 (Macintosh; Intel Mac OS X 10_12_0) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/53.0.2785.116 Safari/537.36</code>.
Please describe how to reproduce this issue, and include links to screenshots if possible.

My code:
```javascript
// d regularly add comments to clarify the function of parts of your code. Good commenting can help communicate the intent of your code—both for oth

/* d regularly add comments to clarify the function of parts of your code. Good commenting can help communicate the intent of your code—both for oth */


```

### PR DESCRIPTION
**Pull request by Bouncey**
#### Pre-Submission Checklist

- [x] Your pull request targets the `staging` branch of FreeCodeCamp.
- [x] Branch starts with either `fix/`, `feature/`, or `translate/` (e.g. `fix/signin-issue`)
- [x] You have only one commit (if not, [squash](http://forum.freecodecamp.com/t/how-to-squash-multiple-commits-into-one-with-git/13231) them into one commit).
- [x] All new and existing tests pass the command `npm run test-challenges`. Use `git commit --amend` to amend any fixes.
#### Type of Change

- [x] Small bug fix (non-breaking change which fixes an issue)
#### Checklist:

- [x] Tested changes locally.
- [x] Closes currently open issue (replace XXXX with an issue no): Closes #10925 
#### Description

Added new regExp in `detect-unsafe-code-stream.js` to detect if the word `function` is in comments and if so, ignore and do not throw the error `SyntaxError: Unsafe or unfinished function declaration`

### CODE REVIEW

**Comment by ktajpuri** [comment]
@bouncey could you please explain the regex you used? A bit tough to figure out for me.

**Comment by Bouncey** [comment]
cc @FreeCodeCamp/issue-moderators - -this is ready

**Review by arialaurel — APPROVED** [review]
This looks good to me, but I can't get the branch up and running locally for some reason. Would love a confirmation from someone who can get it running that this works as it should.

**Comment by atjonathan** [comment]
@ltegman, I will test this in a few hours 👍

**Comment by atjonathan** [comment]
Having issue with the tests on my local setup. Don't believe it's an issue with this PR however.

cc/ @FreeCodeCamp/issue-moderators, please try and review this PR!

**Comment by Bouncey** [comment]
Unable to QA due to #11198

**Comment by ltegman** [comment]
Something about the state of staging when you made your changes is what was causing problems for me. I rebased this branch against the latest staging and was able to QA just fine. LGTM 👍

**Comment by BerkeleyTrue** [comment]
@FreeCodeCamp/issue-moderators 

When merging a PR please ensure the PR actually works or does what it says. This file is no longer used anywhere and does not run actually run anywhere.

**Comment by ltegman** [comment]
Huh. I compared this code side by side with code that didn't have the change and saw an improvement, but it must have been something else doing it. Sorry about that!

**Pull request merged**
