### PR TITLE
fix(challenge): update text to give an explanation of wrapping

### PR DESCRIPTION
**Pull request by lasjorg**
- [x] I have read [freeCodeCamp's contribution guidelines](https://github.com/freeCodeCamp/freeCodeCamp/blob/master/CONTRIBUTING.md).
- [x] My pull request has a descriptive title (not a vague title like `Update index.md`)
- [x] My pull request targets the `master` branch of freeCodeCamp.
- [x] None of my changes are plagiarized from another source without proper attribution.
- [x] All the files I changed are in the same world language (for example: only English changes, or only Chinese changes, etc.)
- [x] My changes do not use shortened URLs or affiliate links.

PR for this challenge: https://learn.freecodecamp.org/responsive-web-design/basic-html-and-html5/introduction-to-html5-elements/

Info: The challenge asks the camper to understand the concept of wrapping, without explaining it. In fact, the challenge is just as much, if not more, about understanding this concept then it is about HTML5 Elements.

I'm sure the idea is to not overwhelm the camper with too much information at this point, however, the number of forum posts this challenge has generated in my opinion shows the challenge needs some help. The text is a little more "heavy" now, but I think it isn't too bad.

1. This PR adds a brief explanation of parent/child, wrapping and nesting. And provides an example.

2. It includes the main tag in the list of tags because given the challenge it seems odd not to.

3. The last paragraph in the instructions is, I think, more clear.

### CODE REVIEW

**Comment by lasjorg** [comment]
I forgot to mention the accompanying video should really also be updated as it does not show the proper nesting of the p elements inside the main element. It also has one error as one of the p elements are not closed properly.

https://scrimba.com/c/c4Ep9Am

**Comment by RandellDawson** [comment]
Is this related to an issue that was created?  If not, it probably should have been created first to discuss the best approach here.  You have added a lot of good information, but it seems like it might be too much for a single challenge.  Maybe this could be separated into two challenges?  I will let some others chime in when they get to this PR.

**Comment by lasjorg** [comment]
@RandellDawson No, there is no related issue. Should I make one, or can we just use this PR?

It's based on my forum experience and how the challenge is causing more people trouble then it should. Specifically related to the nesting of the p elements inside the main element. It's the first time elements are nested and the concept is not explained. It confuses some people. The video is also part of the problem I think.

I can see how the information is unrelated to the HTML5 Elements and makes the challenge a bit long, but I was not sure where else to put it. If not in this challenge, it would need to come before this challenge to be of use.

I can break up the PR into two if needed. One for a new challenge on nesting that should come before this challenge and one for the updated text in this challenge.

**Comment by RandellDawson** [comment]
@Manish-Giri , @ezioda004, @moT01 Any thoughts about breaking this challenge into two challenges to better explain the concept of nesting first?  Do you think we should create an issue to discuss this and then have @lasjorg come back to this PR to make any changes which would need to be made based on the discussion?

**Comment by moT01** [comment]
My quick two cents, after taking a brief look at the challenges...
I think this challenge could be renamed to something like `Nesting HTML Elements` - and the lesson should focus on that - remove all the stuff about the new HTML5 elements and just teach how to nest an element...
We could then rewrite the second challenge (Headline with the h2 Element) - to inform about different elements - something like...
```
HTML tags (or elements) tell your browser how to format and display the content 
within them. Some common tags are <p> (paragraph), <b> (bold), <br> (line break), 
and <ol> (ordered list). HTML5 introduces more descriptive tags like <header>, 
<footer>, <nav>, <video>, <article>, and <section>. These are just a few of the 
more than 200 tags available.

The <h1> element you used in the first lesson is a header and is often used for 
main headings. The <h2> element is also a header, but generally used for 
subheadings. There are also <h3>, <h4>, <h5> and <h6> elements to indicate 
different levels of subheadings.

Over the next few lessons, we'll build an HTML5 cat photo web app piece-by-piece.
------------------------------------------
Add an h2 tag that says "CatPhotoApp" to create a second HTML element below 
your "Hello World" h1 element.
```
Or perhaps, just redo this lesson to focus on nesting and don't change the second one.

Keep in mind, that when changing a lesson like this - there's video's, and hints, and translations and all that stuff that might not align after a change. Especially with these earlier lessons. 

This is just a quick thought after taking a look, and one possible way to go.

**Comment by Manish-Giri** [comment]
I agree that an issue should have been created first, which would have allowed for more discussion on the subject, following which a PR could have been created. Ideally, we should be following this approach for all curriculum PRs which involve anything more than small changes, like typo fixes.

Since there's already some discussion going on in this PR, perhaps we could continue it here itself, _in this instance_. This would avoid repeating a lot of the same thing in the issue.

Regarding the problem at hand, I also think the proposed change is a bit overwhelming for one single challenge. I propose creating another challenge just before this, which just explains HTML elements (including semantic tags), and requires the camper to create multiple HTML elements, like an `h2` followed by two `p` elements. 

And then in this challenge, we could explain nesting (in depth, if required), and even refer to the earlier challenge, like so - 

> In the earlier challenge, we created two `p` elements. - 
>```
> <p>Kitty ipsum dolor sit amet, shed everywhere shed everywhere stretching attack your ankles chase the red dot, hairball run catnip eat the grass sniff.</p>
>
> <p>Purr jump eat the grass rip the couch scratched sunbathe, shed everywhere rip the couch >sleep in the sink fluffy fur catnip scratched</p>
>```
>Often, you would need to nest multiple html elements together, for various reasons - (ex: similar styling, or to convey semantic meaning). In that case, you could create an html element like `<div>` or `<main>` or `<aside>` and then nest elements in it, like so - 
>```
><div>
 >  <p>Kitty ipsum dolor sit amet, shed everywhere shed everywhere stretching attack your ankles     chase the red dot, hairball run catnip eat the grass sniff.</p>
>
 >  <p>: Purr jump eat the grass rip the couch scratched sunbathe, shed everywhere rip the couch >sleep in the sink fluffy fur catnip scratched</p>
></div>
>```

The challenge  could then ask the camper to nest maybe an `h2` and `p` elements in a `<main>` tag.

**Comment by RandellDawson** [comment]
@lasjorg What are your thoughts on the suggestions in the reviews by @moT01 and @Manish-Giri?

**Comment by lasjorg** [comment]
Thinking about this some more here are my thoughts:

1. Making a challenge on different elements seem to go against the way the curriculum is structured now where new elements are being introduced more "organically" challenge by challenge.

2. This is the first challenge to introduce container elements. Even the div element is not shown until the very end. Making a challenge just on nesting this early seems like a bad idea.


Having said that, I would prefer to try and simplify this PR.

1. Remove the last sentence from the part about the tags.

2. Remove everything about nesting.

3. Move the information about the main element up.

4. Show an example usage of the main element with nesting and very little information.

> Example usage, main element with two child elements nested inside:
> 
> ```
> <main>
>   <h1>Hello World</h1>
>   <p>Hello Paragraph</p>
> </main>
> ```

@RandellDawson Should I update the PR with my suggested changes so it is more clear?

Side note: I also think once the accompanying video for this challenge gets updated it will solve a lot of the issues.

**Comment by RandellDawson** [comment]
@moT01, @Manish-Giri What do you think?

**Comment by moT01** [comment]
It would help me if you did update the PR or maybe just post a comment here of what you were thinking.
Challenges are supposed to teach a single concept and be short - so what is this challenge teaching? Nesting right? So I am going to stick with what I wrote earlier and say that this challenge should focus on nesting and get rid of all the stuff about the new html5 elements.

**Comment by lasjorg** [comment]
@RandellDawson I forgot I had another commit, do I need to squash them?

@moT01 I don't fully disagree with you as much as I think it is a bit wasted work for a curriculum being rewritten now anyway. I'm really just trying to update the challenge to make it clearer what the camper needs to do to pass the tests with as few changes as possible.

I have updated the PR, tell me what you think. At this point, I'm really not sure what the best approach is.

**Review by RandellDawson — CHANGES_REQUESTED** [review]
You have added extra lines which are not needed for the challenge to render the way you want.  The challenge renderer was designed to treat anything on a single line of the markdown as a separate paragraph.

You can remove line 10, 12, 14, 17, 18, 24, and 26 and it will display the exact same way.  I have tested this locally and it displays fine.

**Comment by moT01** [comment]
Wasted work because of the planned curriculum overhaul @lasjorg? ...I don't think that's true, the overhaul could potentially take a very long time before it's deployed. Perhaps it might influence some decisions like not turning this into two challenges like we sort of talked about, but small fixes like this are still useful and will probably be around for quite a while for many people to see.

I like the changes you made here and it should make it good enough for now, I think it makes this challenge a little more clear. If we want to make another challenge or something we can create an issue to discuss it. You should remove the lines that @RandellDawson mentioned and we can probably get this merged.

**Comment by lasjorg** [comment]
@moT01 OK maybe wasted work was a bit harsh. I just got the impression from the draft PR that the html part of the rewrite was pretty far along. I didn't mean to imply that making the current curriculum better ever is wasted work. I just meant we might be better off making as few changes as possible.

@RandellDawson I had issues with formatting before. If I remove the line breaks then locally it just shows up as one long line of text. I think it may have to do with when the branch was made. I guess if I sync the branch with the updated master it might work. What is the best way to update a branch with changes from the upstream master? Should I use merge or rebase?

I think I will just take your word for it and remove the line breaks if the new changes I made are acceptable.

**Comment by RandellDawson** [comment]
git --rebase upstream master

**Comment by lasjorg** [comment]
I get rejected when I try to push, I assume it is because of the https://github.com/freeCodeCamp/freeCodeCamp/pull/35528 PR. Before I totally mess things up I'd like to ask what the correct way of dealing with this is.

I guess I can just use the GitHub file edit and it should work, I'd just like to learn what to do in this situation.

Note: I did not do the rebase with master

**Comment by RandellDawson** [comment]
Did you use --force ?

**Comment by RandellDawson** [comment]
I would do the rebase.

**Comment by moT01** [comment]
Is there any sort of error @lasjorg?

**Comment by lasjorg** [comment]
@RandellDawson @moT01 
Well that didn't work as I expected it to.

1. I assumed if I made the formatting changes myself to this PR it would let me push. But I still had to do a force push.
```
-<strong>Note</strong><br>
+<strong>Note:</strong>
```

2. I did a backup of the branch and tried a rebase on it and it gives me a merge conflict.

3. To make it more confusing. When I tried to remove the line breaks using the online file editor the preview looks odd (I didn't commit). I can't tell if it is messed up or if I just don't understand why the preview looks the way it does. Would removing the line breaks in the online file editor cause any issues I'm not aware of?
editor-preview

**Comment by moT01** [comment]
I think that would be fine to use the online editor here, it's a few line breaks - then Randell and I can check it out locally. 

https://github.blog/2015-06-08-how-to-undo-almost-anything-with-git/

**Review by RandellDawson — APPROVED** [review]

**Comment by RandellDawson** [comment]
I was able to clean up the commit history.  I tested it locally and see the following.  Just want to make sure everyone is ok with it in the current state.  If everyone (@lasjorg, @moT01, @Manish-Giri) is, then reply back and then I will merge it.

image

**Comment by lasjorg** [comment]
@RandellDawson LGTM

**Comment by moT01** [comment]
LGTM

**Comment by Manish-Giri** [comment]
Perhaps it's just me, but when I read the instructions - 
> Create a second <code>p</code> element after the existing <code>p</code> element with the following kitty ipsum text:

> Create a <code>main</code> element and nest the two <code>p</code> elements inside the <code>main</code> element

These two instructions seem a bit unrelated to each other. This wasn't an issue with the earlier instruction (`Wrap the paragraphs with an opening and closing <code>main</code> tag.`). 
 
Maybe, the second instruction can be changed to: 

> Then, create a <code>main</code> element and nest the two <code>p</code> elements inside the <code>main</code> element.

**Comment by lasjorg** [comment]
@Manish-Giri Agree.
@RandellDawson I updated the second instruction.

**Review by Manish-Giri — APPROVED** [review]
@lasjorg Thanks for your contribution! Changes LGTM.

**Pull request merged**
