### PR TITLE
fix: Remove unnecessary comments

### PR DESCRIPTION
**Pull request by emerconn**
https://github.com/freeCodeCamp/freeCodeCamp/pull/41612

Checklist:

- [x] I have read [freeCodeCamp's contribution guidelines](https://contribute.freecodecamp.org).
- [x] My pull request has a descriptive title (not a vague title like `Update index.md`)
- [x] My pull request targets the `main` branch of freeCodeCamp.
- [x] All the files I changed are in the same world language, for example: only English changes, or only Chinese changes, etc.

### CODE REVIEW

**Comment by ojeytonwilliams** [comment]
Hi, thanks for creating this PR, but this not a change we will be making at this time.

While we cannot accept this contribution, if you would like to help out, please take a look at our [contributing guide](https://contribute.freecodecamp.org/) for other things you can do.

**Review by moT01 — COMMENTED** [review]
I don't think that last comment is necessary. The instructions seem clear enough that it shouldn't be needed. What do you think @emerconghaile?

**Comment by emerconghaile** [comment]
Agreed @moT01, I say bye-bye comment 🙂

**Review by moT01 — APPROVED** [review]
LGTM 🎉

**Review by naomi-lgbt — APPROVED** [review]
Thank you for all of your work on these PRs.

**Pull request merged**
