### PR TITLE
Rename and split LICENSEs to show up on Github

### PR DESCRIPTION
**Pull request by mgattozzi**
#### Pre-Submission Checklist

- [x] Your pull request targets the `staging` branch of FreeCodeCamp.
- [x] Branch starts with either `fix/`, `feature/`, or `translate/` (e.g. `fix/signin-issue`)
- [x] You have only one commit (if not, [squash](http://forum.freecodecamp.com/t/how-to-squash-multiple-commits-into-one-with-git/13231) them into one commit).
- [x] All new and existing tests pass the command `npm run test-challenges`. Use `git commit --amend` to amend any fixes.
#### Type of Change

- [x] Small bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds new functionality)
- [ ] Breaking change (fix or feature that would change existing functionality)
- [ ] Add new translation (feature adding new translations)
#### Checklist:

- [x] Tested changes locally.
- [x] Closes currently open issue (replace XXXX with an issue no): Closes #XXXX
  https://twitter.com/ossia/status/778778253108531200
#### Description

Github's new feature displays the LICENSE from the repo in the info bar.
However, this only works if the file is named LICENSE not LICENSE.md.
The LICENSE file must also contain the exact wording unmodified from the
template that Github uses (except for copyright information). This commit
changes the files and splits it up so that it will be rendered properly on
the page as expected.

You can see it rendered properly after merge [here](https://github.com/mgattozzi/FreeCodeCamp). While this doesn't close an issue number @QuincyLarson was asking Github how to do this and so I implemented the fix myself since it was relatively easy to do and I had a suspicion on how to fix it.

Please let me know if you want something named a different way or if I need to do anything else in order for the PR to be approved.

### CODE REVIEW

**Comment by BerkeleyTrue** [comment]
@QuincyLarson I don't really know how to QA this. Maybe we should pull in Kyle?

**Comment by QuincyLarson** [comment]
@mgattozzi have you installed Ruby in the directory so you can run the license gem and verify that this new version of the license file will work? Can you find a way to get this to work without splitting the LICENSE.md into two files?

**Comment by mgattozzi** [comment]
Github's license gem? I'll see what if I can get it working without splitting the files but at the very least I suspect it won't support md. I'll have to play around with it to see what's possible. Most repos just have the LICENSE file which is probably what Github's engineers had based it around. Surprising, considering one of the most starred and forked repos on here wasn't considered as a possible edge case.

**Comment by QuincyLarson** [comment]
@mgattozzi thanks for your help with this. Once we can verify that the Ruby licensee gem  correctly detects our license as BSD-3, we can merge a PR for this.

**Comment by QuincyLarson** [comment]
@mgattozzi I'm going to close this PR for now, since your solution may change. I'm going to open an issue and at-mention you in it.

**Comment by mgattozzi** [comment]
Perfect! I'll work on it when I can this weekend. I have some particularly tough CS assignments due for class so I'd say expect an update or PR at latest by next week.

**Comment by QuincyLarson** [comment]
@mgattozzi OK - great. No rush. Thank you for your help!

**Pull request closed without merging**
