### PR TITLE
fix: dropdown svg margin that move the text from the center

### PR DESCRIPTION
**Pull request by Sboonny**
Checklist:

- [x] I have read and followed the [contribution guidelines](https://contribute.freecodecamp.org).
- [x] I have read and followed the [how to open a pull request guide](https://contribute.freecodecamp.org/#/how-to-open-a-pull-request).
- [x] My pull request targets the `main` branch of freeCodeCamp.
- [x] I have tested these changes either locally on my machine, or GitPod.

You can visit [JavaScript challenge](https://www.freecodecamp.org/learn/javascript-algorithms-and-data-structures/basic-javascript/initializing-variables-with-the-assignment-operator) to see the that the text are misaligned
image

image

### CODE REVIEW

**Comment by naomi-lgbt** [comment]
image

This is what I currently see on production - yikes! Taking a look at this PR now.

**Comment by bbsmooth** [comment]
> This is what I currently see on production - yikes!

@naomi-lgbt I am trying to replicate your pic and am not able. What browser/version/OS are you using?

**Comment by naomi-lgbt** [comment]
It's a strange bug, that I think is related to caching? I see it on page load in a normal tab, but in incognito the page loads correctly and a refresh is required to trigger the bug.


I'm on Win 11 - Chrome 115.0.5790.111 (Official Build) (64-bit)

**Comment by Sboonny** [comment]
I can re produce it, when I zoom to 50% in the dev-tools, and that state will be saved until I close the dev tools, refresh and open it again.

image

**Comment by naomi-lgbt** [comment]
> I can re produce it, when I zoom to 50% in the dev-tools, and that state will be lingering until I remove the zoom, close the dev tools, refresh the page and open the dev tools again.

I followed this, it worked. Refreshed the page with the dev tools still open, bug came back haha

**Comment by bbsmooth** [comment]
Interesting. I've been trying my hardest to trigger this with FF but still not able. And I can only trigger it with Chrome with dev tools open and the toggle device emulator active. But I'm on linux, so my experience may be different for other OS's.

**Comment by naomi-lgbt** [comment]
> toggle device emulator active

Yeah I only get this with the device emulator too. I just use that all the time because I'm too lazy to resize my window haha

**Review by naomi-lgbt — APPROVED** [review]
Anyway, the strange bug isn't caused by this PR, and the changes make the buttons look better. Happy to land this.

**Review by Sembauke — APPROVED** [review]

**Pull request merged**
