### PR TITLE
fix(curriculum): arrow function checking consistency

### PR DESCRIPTION
**Pull request by gikf**
Checklist:

- [x] I have read and followed the [contribution guidelines](https://contribute.freecodecamp.org).
- [x] I have read and followed the [how to open a pull request guide](https://contribute.freecodecamp.org/#/how-to-open-a-pull-request).
- [x] My pull request targets the `main` branch of freeCodeCamp.
- [x] I have tested these changes either locally on my machine, or GitPod.

- - -
- Mainly focusing on arrow functions with single parameter - option to write parameter with and without parenthesis.
- Some other issues related to optional spaces also were handled, when file included arrow function.
- Triple checked by hand, which means there must be some mistakes still lurking around.
- Whomever will be reviewing this: I'm sorry.
- Any questions, nitpicks, etc. are welcomed.

### CODE REVIEW

**Comment by JoyShaheb** [comment]
i really like the solution/idea. but @jdwilkin4 @scissorsneedfoodtoo  guys do you think its a good idea to add solutions that involve multiple projects ?

**Comment by jdwilkin4** [comment]
> guys do you think its a good idea to add solutions that involve multiple projects ?

While this PR is on the larger side, @gikf is a long time contributor so I think it is fine in the case. 
There will be multiple people reviewing this to make sure everything works as it should 👍

**Review by scissorsneedfoodtoo — COMMENTED** [review]
Thank you so much for taking the time to improve all of these tests, @gikf. This is really awesome, and will make the projects much more flexible.

I went through all the steps and played with spacing, writing functions with and without parentheses when there was only one parameter, and so on.

Out of all the updated tests I only have one suggestion. Otherwise, everything LGTM 👍

**Comment by gikf** [comment]
@scissorsneedfoodtoo Thanks for looking, that was the goal. :rocket:

**Review by naomi-lgbt — APPROVED** [review]
Thanks for taking care of this. It turned into a bit of a behemoth, and your efforts are appreciated!

**Review by JoyShaheb — APPROVED** [review]

**Pull request merged**
