### PR TITLE
Added emoji support for Bio

### LINKED ISSUE #10817: Add emoji support for GitHub-imported data
I've just noticed emojis are displayed as text and not as images — [example](https://www.freecodecamp.com/zdroid). Emojis are becoming very popular, especially on GitHub and I think they should be supported on a site which is partly supported by GitHub.

Is it possible to edit profile description at least, if emoji support can't or won't be implemented?

### PR DESCRIPTION
**Pull request by ghost**
#### Pre-Submission Checklist
- [x] Your pull request targets the `staging` branch of FreeCodeCamp.
- [x] Branch starts with either `fix/`, `feature/`, or `translate/`.
- [x] You have only one commit.
- [x] All new and existing tests pass the command `npm run test-challenges`.
#### Type of Change
- [x] Breaking change (fix or feature that would change existing functionality)
#### Checklist:
- [x] Tested changes locally.
- [x] Closes currently open issue: Closes #10817

### CODE REVIEW

**Comment by Bouncey** [comment]
When I add emoji to my bio and click the 'Updated from GitHub' button, the emoji appear, but they are bleached out (no colour, hard to make out). 

emoji

**Comment by atjonathan** [comment]
@Bouncey, this is because these are emoji's you imputed on a mobile device.

**Comment by Bouncey** [comment]
No no, these are GitHub emoji 

🍪 🌵 🐫 🍆 🌍

**Comment by atjonathan** [comment]
@Bouncey, weird, I can't reproduce.

**Comment by dhcodes** [comment]
@atjonathan Did you update this to account for null bios?

**Comment by atjonathan** [comment]
@dhcodes, lol, i forgot. I'll get this sorted soon 😄

**Comment by atjonathan** [comment]
@dhcodes, can you reproduce the issue that @Bouncey was having?

**Comment by dhcodes** [comment]
@atjonathan I've tried it on two different system (same user, though) and it worked fine except for the null bio issue we discussed in the Contributors room. @Bouncey how did you test it? Your github bio doesn't currently have emojis. Did you delete them?

**Comment by Bouncey** [comment]
So, I added cookie, cactus, camel, eggplant and earth_africa to the end of my bio and clicked the Update from GitHub button 

I'm using the latest stable chrome release on Ubuntu 16.04. 

I will try a different browser later today

**Comment by scshepard** [comment]
Hi Stuart,

These silly emoji are popping everywhere! I had one knowledgeable insist that they are ASCII, but they can't be.

But WHAT are these nutty things:  ? ? ? ? ?


od -c shows: 360 237 215 252

od -x shows: 9ff0 aa8d 000a


This is just driving me batty!

Steve

________________________________

**Comment by atjonathan** [comment]
@dhcodes, this should finally be good to go!

**Comment by Bouncey** [comment]
Still the same for me...

anim

**Comment by atjonathan** [comment]
cc/ @FreeCodeCamp/issue-moderators, anyone else having the same issue as @Bouncey? I personally still can't reproduce.

**Comment by QuincyLarson** [comment]
@atjonathan you're not encountering this yourself? Is it possible that this could be caused by our custom CSS rules or by Bootstrap?

**Comment by ltegman** [comment]
I can't repro this on Mac, but I can (kind of) on Windows. I don't get black and white emojis on Windows, but I do get a flat style of emoji, rather than the 3D looking ones I'm used to. I would guess this is due to our font stack. If you check out the Github CSS you'll see they add a special class around emojis which gives them the following font stack:
```
"Apple Color Emoji", "Segoe UI", "Segoe UI Emoji", "Segoe UI Symbol"
```

**Comment by atjonathan** [comment]
@ltegman, could you attach a screenshot?
@QuincyLarson, no, I can't reproduce.

**Comment by Em-Ant** [comment]
@ltegman I think you are right. I guess it depends on the fonts you have installed on your machine. 
I didn't test this particular case, but I already had troubles with emojis on my Ubuntu system because of missing fonts.

**Comment by Bouncey** [comment]
From the forum post linked by @Em-Ant 

>In addition to the Apple Color Emojis being proprietary, I'm pretty sure Ubuntu doesn't support colour bitmap fonts.
>
>So, for use in single documents, you can fall back to images 

Not supported in Ubuntu, needs an image fallback

**Review by arialaurel — APPROVED** [review]
This does as advertised and adds emoji support in Bios. I don't think we should hold this back just because it doesn't implement image fallbacks for computers without the appropriate fonts.

**Comment by atjonathan** [comment]
@ltegman :+1:

**Comment by atjonathan** [comment]
@ltegman can this be merged?

**Comment by ltegman** [comment]
I was just waiting to see if there were any remaining concerns now that we know the rendering issue is down to installed fonts, but it looks like there isn't 👍

**Pull request merged**
