### PR TITLE
chore(client): reorder and rename rwd changes

### LINKED ISSUE #45968: Clarify New VS Old Responsive Web Design cert right in /learn UI
### Describe the Issue

The biggest issue we've had with promoting the updated Responsive Web Design certification to production (and retiring the old one to legacy) is confusion from past visitors. They seem to think their progress was erased.

I have a simple way we can update this:

Put the word `(New)` in front of Responsive Web Design on /learn, then move the Legacy Responsive Web Design cert to be immediately below it, like this:
Learn_to_Code_—_For_Free_—_Coding_Courses_for_Busy_People_and_Idea_

I believe this will immediately reduce confusion.

We can just show this for returning campers – not new ones. (Though I think we can add this functionality later. The most immediate concern is reducing confusion.)

Then, a few weeks from now, we can revert to just putting the legacy cert at the bottom again.

### Affected Page

https://www.freecodecamp.org/learn

### Your code

N/A

### Expected behavior

Clarity

### Screenshots

_No response_

### System

- Device: [e.g. iPhone 6, Laptop]
- OS: [e.g. iOS 14, Windows 10, Ubuntu 20.04]
- Browser: [e.g. Chrome, Safari]
- Version: [e.g. 22]

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by ShaunSHamilton**
Checklist:

- [x] I have read [freeCodeCamp's contribution guidelines](https://contribute.freecodecamp.org).
- [x] My pull request has a descriptive title (not a vague title like `Update index.md`)
- [x] My pull request targets the `main` branch of freeCodeCamp.
- [x] I have tested these changes either locally on my machine, or GitPod.

Closes #45968 

image

### CODE REVIEW

**Review by ojeytonwilliams — COMMENTED** [review]
Just one wrinkle: this will modify the curriculum order, not just the map. I think the ideal order would be to go RWD -> JS and Legacy RWD -> JS, not RWD -> Legacy RWD -> JS since users aren't going to want to finish RWD and then start again.

Not a big deal, mind, just something to consider.

**Review by ojeytonwilliams — DISMISSED** [review]
LGTM 👍

**Comment by ShaunSHamilton** [comment]
@ojeytonwilliams That completely slipped my mind.

I will see about just changing the display position with some good-old, hard-coded values

**Comment by ojeytonwilliams** [comment]
I think what you've done should help reduce the confusion a fair bit. If we can get this deployed ASAP, that's the way to go.

Also, I just tested it out on GitPod. When I submitted the portfolio project it took me to https://8000-shaunshamil-freecodecam-vyi5t7qevoi.ws-eu45.gitpod.io/learn/2022/responsive-web-design/ so maybe it's fine!

**Comment by ShaunSHamilton** [comment]
> Also, I just tested it out on GitPod. When I submitted the portfolio project it took me to https://8000-shaunshamil-freecodecam-vyi5t7qevoi.ws-eu45.gitpod.io/learn/2022/responsive-web-design/ so maybe it's fine!

Where there errors in the console?

**Comment by ojeytonwilliams** [comment]
Sorry, I was checking it out on my phone, so I don't know.

**Comment by ShaunSHamilton** [comment]
I cannot figure out why the test is failing. At first, it looks like the snapshot just needs updating, but, even after doing that, it still fails for the same reason.

**Review by Sembauke — APPROVED** [review]

**Review by raisedadead — APPROVED** [review]

**Pull request merged**
