### PR TITLE
fix(curriculum): Fix english curriculum courses challenge titles

### LINKED ISSUE #53643: New English curriculum titles are not displayed appropriately in timeline
### Describe the Issue

In the timeline table on the profile page, the title of each task of the New English curriculum is now displayed as `Task 3`, but each of the three courses contains a task with the same name, so campers can not recognize at a glance which course's task have been completed.

### Affected Page

/username

### Steps to Reproduce

1. Go to profile page after solving a task of new English curriculum
2. Scroll down to the table under the `Timeline` heading
3. See the curriculum title 

### Expected behavior

Like the Steps in new RWD or new JS Algorithms and Data Structures Certification, the title will be displayed with block name title and a dash.

### Screenshots

<details>
<summary>The title of each task of New English Curriculum on the timeline table</summary>

New_English_curriculum_title_on_the_timeline_table
</details>

### System

- Device: Laptop
- OS: Windows 11 Home
- Browser: Chrome
- Version: 121.0.6167.161 (Official Build) (64-bit)

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by abhinavkgrd**
Checklist:

- [x] I have read and followed the [contribution guidelines](https://contribute.freecodecamp.org).
- [x] I have read and followed the [how to open a pull request guide](https://contribute.freecodecamp.org/#/how-to-open-a-pull-request).
- [x] My pull request targets the `main` branch of freeCodeCamp.
- [x] I have tested these changes either locally on my machine, or GitPod.

Closes #53643

`hasEditableBoundaries`  is used to determine if the challenge is step or not, and thereby whether to append the block name to the challenge name or not
https://github.com/freeCodeCamp/freeCodeCamp/blob/c1137b0900ad098fee2fca430d11f69dfc909d3b/client/src/components/profile/components/time-line.tsx#L299-L301

I don't have context, if `hasEditableBoundaries` can cause any other unwanted effects. I did a basic smoke test by solving some of the english curriculum and everything seems to be working fine.

### CODE REVIEW

**Comment by naomi-lgbt** [comment]
I don't think that adding that flag (which isn't accurate here) to the metadata is the best approach here.

**Comment by abhinavkgrd** [comment]
> I don't think that adding that flag (which isn't accurate here) to the metadata is the best approach here.

Hey @naomi-lgbt, my bad, I saw the pattern and reverse-engineered the solution. 
Can you guide me, with what a proper solution might be, should we have a new flag for it?

**Comment by moT01** [comment]
I'm not sure using `hasEditableBoundaries` is the best approach for the step challenges either. What if a challenge is created that has editable boundaries, but has a regular title? Not a big deal for now.

I see two approaches you could use here.

1. Regex to see if the challenge `isTaskChallenge`. e.g. `/^Task \d+$/.test(challengeTitle)`

or

2. Just do it for all the challenges in the english superblock. `if (superblock === superblocks.a2-english)`

I would be fine with either approach. What do you two think @abhinavkgrd @naomi-lgbt ?

**Comment by naomi-lgbt** [comment]
I like scoping it to that superblock, tbh.

**Comment by abhinavkgrd** [comment]
Heyy @moT01 , as suggested, I have updated the code to do it for all english curriculum challenges, instead of adding the `hasEditableBoundaries` to the block metadata

But, as you have also said, using `hasEditableBoundaries` as a check if a challenge is a step challenges might cause issues. And I think, a better solution might be to have a new flag something like`isStepChallenge` and use that to do this would be better solution in long term.

**Review by moT01 — APPROVED** [review]
LGTM @abhinavkgrd 🎉 Thanks for working on this 👍 

If you want, you could create an issue where we can discuss a new flag specific for displaying these title.

**Review by naomi-lgbt — APPROVED** [review]
Nice work! Let's go ahead and land this.

**Pull request merged**
