### PR TITLE
fix(curriculum): Improve test to allow any valid function call for Write Reusable JavaScript with Functions challenge

### PR DESCRIPTION
**Pull request by RandellDawson**
Checklist:

- [x] I have read [freeCodeCamp's contribution guidelines](https://contribute.freecodecamp.org).
- [x] My pull request has a descriptive title (not a vague title like `Update index.md`)
- [x] My pull request targets the `main` branch of freeCodeCamp.
- [x] All the files I changed are in the same world language, for example: only English changes, or only Chinese changes, etc.

I noticed [this forum discussion](https://forum.freecodecamp.org/t/reusablefunction/451964) and realized one of the tests was to rigid.  This PR allows the function to be called anywhere in the code (outside the function of course).

### CODE REVIEW

**Comment by RandellDawson** [comment]
I have discovered another bug with this challenge.  The following will pass all the tests:

**Review by naomi-lgbt — APPROVED** [review]
Looks good to me. Resolves both issues mentioned in the linked forum post.

**Review by ShaunSHamilton — APPROVED** [review]
This LGTM 👍 

I am surprised we do not see more Campers do this (But, rightly, this does not pass):
```
function reusableFunction() {
  console.log("Hi World");
  reusableFunction();
}
```

**Comment by nhcarrigan** [comment]
That's how you break the internet, Shaun - too much recursion 😉

**Pull request merged**
