### PR TITLE
fix(active-users): remove api calls until after beta release

### PR DESCRIPTION
**Pull request by raisedadead**
@Bouncey lets keep this on hold, we have a long pending issue with chrome caching requests. And our use of Rx and LB is complicating this. This is getting mixed up with authenticated requests and I have to admit I think its worth taking in after we have open-api for this instead.

### CODE REVIEW

**Comment by Bouncey** [comment]
What is the issue with caching?

**Comment by raisedadead** [comment]
If you make authenticated requests and unauthenticated requests in parallel especially with something like jQuery ajax, it just gets combined together. 

And more often than not, the Rx part where we combine actions starts to crash.
This is because a lot of the LB internals is synchronous.

There is no clean way to reproduce this currently.

**Comment by Bouncey** [comment]
Oh man that sucks. Which RX parts?

**Comment by raisedadead** [comment]
Well it crashes at times at the get services, I think. Especially while at GET Passwordless methods. It sporadic on development though.

Express will cache those requests and continue to serve them on an page that's left open. While an email is sent and is opened on a separate tab.

https://github.com/freeCodeCamp/freeCodeCamp/pull/8931/files is where we had to reverse this, untill finding a workaround.

**Comment by Bouncey** [comment]
Do we have an issue tracking this cache issue?

**Comment by raisedadead** [comment]
I just created one.

**Pull request merged**
