### PR TITLE
fix/regex-lower-number-of-matches

### LINKED ISSUE #35988: [challenge] bad tests: Regular Expressions: Specify Only the Lower Number of Matches
[challenge](https://www.freecodecamp.rocks/learn/javascript-algorithms-and-data-structures/regular-expressions/specify-only-the-lower-number-of-matches) has insufficient tests.
Challenge instructions:

> Change the regex haRegex to match the word "Hazzah" only when it has four or more letter z's.

`/z{4}/` is enough to pass, whereas I _think_ it should be more like `/Haz{3,}ah/`

Found this while testing #35747 locally, tested on .rocks with same results.

**Tell us about your browser and operating system:**
* Browser Name: Chromium
* Browser Version: Version 72.0.3626.121 (Official Build) Built on Ubuntu , running on Ubuntu 16.04 (64-bit)
* Operating System: crouton running on chromebook - Ubuntu 16.04.6 LTS

### PR DESCRIPTION
**Pull request by moT01**
- updated the tests to ensure the users regex will match all the letters in the various `Hazzzzah`'s
- removed old/unnecessary assert messages
- updated solution

- [x] I have read [freeCodeCamp's contribution guidelines](https://github.com/freeCodeCamp/freeCodeCamp/blob/master/CONTRIBUTING.md).
- [x] My pull request has a descriptive title (not a vague title like `Update index.md`)
- [x] My pull request targets the `master` branch of freeCodeCamp.
- [x] None of my changes are plagiarized from another source without proper attribution.
- [x] All the files I changed are in the same world language (for example: only English changes, or only Chinese changes, etc.)
- [x] My changes do not use shortened URLs or affiliate links.

Closes https://github.com/freeCodeCamp/freeCodeCamp/issues/35988

### CODE REVIEW

**Comment by nikrb** [comment]
@moT01 tested locally. looks good except specifying the upper bound will pass the test e.g. `/Haz{4,30}ah/`. Am I being too picky?

**Comment by moT01** [comment]
Thanks for the review @nikrb - I'm not sure what you're saying there - you're saying that regex will pass the tests? and it shouldn't or something? just trying to understand.

**Comment by nikrb** [comment]
@moT01 the challenge is to use only the regex lower bound, e.g. `{4,}`. However the tests also pass if you supply the upper bound, `{4,30}`. Hope that makes sense.

**Comment by moT01** [comment]
I see what you're saying now @nikrb - so perhaps another test that checks something like: `use only the lower bound` or `do not use an upper bound` - the directions don't really say not to use the upper bound though - and it is a valid way to match the strings. It might cause confusion unless there's something added to the instructions. 

I think we could probably add that since this challenge is focused on that - what do you think @nikrb ?

**Comment by RandellDawson** [comment]
@nikrb, @moT01 My 2 cents here.  Since the main purpose of the challenge is to make sure the regex used contains the lower bound syntax, is it really an issue if they happen to also use  the upper bound syntax?  As long as using the other tests pass, does it really matter?

**Comment by moT01** [comment]
I don't really have an opinion - it works either way.

**Comment by RandellDawson** [comment]
@nikrb I guess the decision is yours regarding whether there should be extra verbiage and test changes made.  I always error on keeping the challenge as simple as possible, yet also making sure there are not false positives and the tests allow correct yet flexible solutions.

**Comment by moT01** [comment]
I'm thinking we just leave it - this fixes the main issue, and I'm not sure I like forcing a valid regex to fail.

**Comment by nikrb** [comment]
@moT01 @RandellDawson I wasn't sure if I was being too picky, so if you guys are happy so am I :)
There was talk about having more mods review pr's, so do we need another review or two before merging?

**Comment by moT01** [comment]
That was definitely worth bringing up @nikrb - as far as I know curriculum PR's just need to be approved by two people. tip: you can give a more official review by clicking the `files changed` tab at the top and then the `review changes` button on the top right of that.

**Comment by RandellDawson** [comment]
@nikrb What we have typically been doing is if two mods don't agree on a review, we will bring in a 3rd mod to give another opinion.

**Comment by moT01** [comment]
Looks like this file is on your backtick conversion PR @RandellDawson - this PR doesn't touch that part of the file - is it fine to leave it? Or should I make that conversion in this PR?

**Comment by RandellDawson** [comment]
@moT01 My first thought is to just leave it, because in the issue #35991 I said we could either add an extra commit to the existing PRs or wait until all of the backtick conversion PRs were merge and fix the extra ones with a single PR.  Since #35415 was merged without making the conversion, I assume that meant we were just going to wait until all of those are merged.  

Actually, converting this now could help prevent a merge conflict on my PR though, so maybe it is best to go ahead and make the conversion.

**Review by RandellDawson — APPROVED** [review]
LGTM

**Comment by RandellDawson** [comment]
Based on the lessons learned here, the next challenge (Match Single Character with Multiple Possibilities)[https://learn.freecodecamp.org/javascript-algorithms-and-data-structures/regular-expressions/match-single-character-with-multiple-possibilities/) has the same issues.  I technically should not be able to pass the 2nd through the 6th tests using `let ohRegex = /h{3,6}/;`

**Comment by moT01** [comment]
What challenge exactly @RandellDawson? The one you linked is not correct I don't think.

**Comment by moT01** [comment]
Nevermind - it must be this one - https://learn.freecodecamp.org/javascript-algorithms-and-data-structures/regular-expressions/specify-upper-and-lower-number-of-matches - yea, that has a similar issue

**Comment by RandellDawson** [comment]
Yes, you are correct.  I meant that one, but for some reason copied/pasted something else.

**Review by ojeytonwilliams — APPROVED** [review]
LGTM :+1:

**Comment by RandellDawson** [comment]
@nikrb If you are ok with the current version, please go ahead and merge this PR.  I prefer you merge it, since you had some initial concerns and want to make sure you are fine with the changes as is.

Thanks

**Pull request merged**
