### PR TITLE
fix(curriculum): add line to seed code

### LINKED ISSUE #41528: Typo in challenge for ES6 JS, "Use * to Import Everything"
**Describe your problem and how to reproduce it:**
There is a typo in the sample text provided. The comment says "Only change code above this line" for line 1. It should be "Only change code below this line", or move line 1 to line 2

**Add a Link to the page with the problem:**
https://www.freecodecamp.org/learn/javascript-algorithms-and-data-structures/es6/use--to-import-everything-from-a-file

**Tell us about your browser and operating system:**
* Browser Name:  Firefox
* Browser Version: Latest
* Operating System: W10

**If possible, add a screenshot here (you can drag and drop, png, jpg, gif, etc. in this box):**
image

### PR DESCRIPTION
**Pull request by CoolBlueDesigns**
Checklist:

- [x] I have read [freeCodeCamp's contribution guidelines](https://contribute.freecodecamp.org).
- [x] My pull request has a descriptive title (not a vague title like `Update index.md`)
- [x] My pull request targets the `main` branch of freeCodeCamp.
- [x] All the files I changed are in the same world language, for example: only English changes, or only Chinese changes, etc.

Closes #41528

### CODE REVIEW

**Comment by RandellDawson** [comment]
@CoolBlueDesigns Why did you create another PR?  I left instructions on your other PR on how to resolve.  Anyway, you can close the other PR since you have this one now.

**Comment by CoolBlueDesigns** [comment]
@RandellDawson I have closed my first one. Thank you for the advice.

**Review by gikf — APPROVED** [review]
LGTM

**Review by ShaunSHamilton — APPROVED** [review]
This LGTM 👍 
Congrats on your first pull request (PR)! 🎉

Thank you, for your contribution to the page! 👍
We are happy to accept these changes, and look forward to future contributions. 📝

**Pull request merged**
