### PR TITLE
(feat/curriculum) add wordFrequency (RosettaCode) lesson

### PR DESCRIPTION
**Pull request by anthonyzeng99**
Checklist:

- [x] I have read [freeCodeCamp's contribution guidelines](https://github.com/freeCodeCamp/freeCodeCamp/blob/master/CONTRIBUTING.md).
- [x] My pull request has a descriptive title (not a vague title like `Update index.md`)
- [x] My pull request targets the `master` branch of freeCodeCamp.
- [x] All the files I changed are in the same world language, for example: only English changes, or only Chinese changes, etc.

Closes #XXXXX

### CODE REVIEW

**Review by moT01 — CHANGES_REQUESTED** [review]
I added a guide article for this: https://www.freecodecamp.org/forum/t/freecodecamp-challenge-guide-word-frequency/393913
Please add `393913` as the `forumTopicId`

I also noticed that we added another property in the front matter at the top.
Add `isHidden: false` up there as well.

It should look like this:
```
id: 5e94a54cc7b022105bf0fd2c
title: Word frequency
challengeType: 5
isHidden: false
forumTopicId: 393913
```

You used mongo to generate that ID right?

**Comment by raisedadead** [comment]
@anthonyzeng99 

Looks like you have explicitly disabled edits from maintainers, which means you would need to look into the currently updated file structure and rebase this PR before we are able to QA and merge this.

Thanks.

**Comment by moT01** [comment]
Any interest in rebasing this @anthonyzeng99?

**Comment by moT01** [comment]
Thanks for the PR @anthonyzeng99, I have made a PR in place of this so we can make changes and get it merged. Thanks for contributing to freeCodeCamp 🎉

**Pull request closed without merging**
