### PR TITLE
refactor: use process.env in node environments

### PR DESCRIPTION
**Pull request by ojeytonwilliams**
env.json is only necessary for code that runs in the browser and does not have access to process.

Using env.json in other workspaces creates more coupling between them and the client.

Checklist:

- [x] I have read and followed the [contribution guidelines](https://contribute.freecodecamp.org).
- [x] I have read and followed the [how to open a pull request guide](https://contribute.freecodecamp.org/#/how-to-open-a-pull-request).
- [x] My pull request targets the `main` branch of freeCodeCamp.
- [x] I have tested these changes either locally on my machine, or GitPod.

### CODE REVIEW

**Review by huyenltnguyen — APPROVED** [review]
If you fancy it, we could consider enforcing the [no-restricted-paths](https://github.com/import-js/eslint-plugin-import/blob/main/docs/rules/no-restricted-paths.md) rule to prevent these imports in the future.

I could raise a PR for this :)

**Comment by ojeytonwilliams** [comment]
@huyenltnguyen that's an interesting option, for sure! 

What I'm currently trying to figure out is how to make our various workspaces more modular, while still sharing code, types and config where necessary. It's tricky :(

Something like `no-restricted-paths` could help with that, so I'd definitely be interested in trying it out for a while!

**Comment by ojeytonwilliams** [comment]
> How modular do we want the workspaces to be? I'd imagine having workspaces for shared models/types, utils, configs, etc. which could be turned into standalone packages for the client and the server to consume. But I assume realistically things are way more complicated than that.

Pretty much that complicated, actually! What you describe should be a lot better than what we currently have.

The difficulty is that we've picked up a lot of explicit and implicit dependencies (like this one) over the years, so disentangling them is quite a task.

**Review by ShaunSHamilton — APPROVED** [review]
This looks correct 👍, and nothing broke during build.

**Pull request merged**
