### PR TITLE
fix: Unclear test output use-array.map-to-dynamically-render-elements

### PR DESCRIPTION
**Pull request by kundan59**
- [x] I have read [freeCodeCamp's contribution guidelines](https://github.com/freeCodeCamp/freeCodeCamp/blob/master/CONTRIBUTING.md).
- [x] My pull request has a descriptive title (not a vague title like `Update index.md`)
- [x] My pull request targets the `master` branch of freeCodeCamp.
- [x] None of my changes are plagiarized from another source without proper attribution.
- [x] All the files I changed are in the same world language (for example: only English changes, or only Chinese changes, etc.)
- [x] My changes do not use shortened URLs or affiliate links.

Closes #XXXXX

### CODE REVIEW

**Comment by ojeytonwilliams** [comment]
@raisedadead I have no idea why Travis is ignoring this.  I've checked it out locally and it passes all the tests, so I think it's safe to merge.

**Review by ojeytonwilliams — APPROVED** [review]

**Comment by raisedadead** [comment]
Hi @kundan59 can you please reach out to travis support? What I can see is that your pull-requests do not fire the CI for some reason. There is a chance that the user account is flagged for some reason?

**Comment by kundan59** [comment]
Hi, @raisedadead should I raised this issue to Travis CI as I didn't get your point.

**Comment by raisedadead** [comment]
Yes, @kundan59 you should first sign in to https://travis-ci.org/ and check that you do not have any warnings or notifications. Then on you could reach out to their support email (you will find contact details in the footer on their website) giving reference to this PR stating that the CI checks are not firing for some reason.

**Comment by RandellDawson** [comment]
This is a duplicate of PR #38172, so we are closing it.  

@kundan59 Follow the instructions given by @raisedadead

**Pull request closed without merging**
