### PR TITLE
fix(client): add instructions to challenge view components

### PR DESCRIPTION
**Pull request by moT01**
This adds the instructions to the odin (challenge-type 15 & 19) and dialogue (challenge-type 21) view components. None of those challenges have instructions at the moment. Adding this so the English team can put something like "Watch the video and complete the task below" between the video and tasks.

Checklist:

- [x] I have read and followed the [contribution guidelines](https://contribute.freecodecamp.org).
- [x] I have read and followed the [how to open a pull request guide](https://contribute.freecodecamp.org/how-to-open-a-pull-request/).
- [x] My pull request targets the `main` branch of freeCodeCamp.
- [x] I have tested these changes either locally on my machine, or GitPod.

Closes #XXXXX

### CODE REVIEW

**Review by ojeytonwilliams — APPROVED** [review]
Is this still necessary if we're adding `explanation`?

The code looks good, regardless.

**Comment by moT01** [comment]
I think it's still fine to add these. It gives a consistent place to put the instructions. For instance, I think the english team has been using the description for the instructions on these challenges, but the instructions on challenges where it's available.

**Comment by nieldakarla** [comment]
I agree it makes sense to create this heading to keep consistency. Thank you for creating this PR, Tom!

**Review by nieldakarla — APPROVED** [review]
Thank you for adding this feature, Tom! it looks good to me.

**Pull request merged**
