### PR TITLE
fix:Added extra test cases for 'arguments-optional' problem

### LINKED ISSUE #38774: [Arguments Optional] Current test cases allow for unintended solutions to pass
**Describe your problem and how to reproduce it:**
On the Intermediate Algorithm Scripting: Arguments Optional challenge, the only two happy path test cases -- `addTogether(2, 3)` and `addTogether(2)(3)`, both expect a return value of 5. All other test cases expect a return value of undefined. Because there are no other happy path test cases, it's possible to construct a passing solution that doesn't add inputs together, but simply returns 5 when the inputs are valid numbers (pasted below). Another set of happy path test cases could help prevent this sort of unintended solution from passing.

```javascript
// passes tests without performing addition
function addTogether(x, y) {
  if (y) {
    return returnFive(x, y);
  }
  return curriedReturnFive(x);
}

function returnFive(x, y) {
  if (!areNumbers(x, y)) {
    return;
  }
  return 5; // just 5 satisfies current tests
}

function curriedReturnFive(x) {
  if (!isNumber(x)) {
    return;
  }
  return function(y) {
    return returnFive(x, y);
  }
}

function areNumbers(...args) {
  return args.every(isNumber);
}

function isNumber(x) {
  return typeof x === 'number';
}
```

**Add a Link to the page with the problem:**
https://www.freecodecamp.org/learn/javascript-algorithms-and-data-structures/intermediate-algorithm-scripting/arguments-optional

**If possible, add a screenshot here (you can drag and drop, png, jpg, gif, etc. in this box):**
image

### PR DESCRIPTION
**Pull request by rajat641**
Checklist:

- [x] I have read [freeCodeCamp's contribution guidelines](https://contribute.freecodecamp.org).
- [ x] My pull request has a descriptive title (not a vague title like `Update index.md`)
- [ x] My pull request targets the `master` branch of freeCodeCamp.
- [ x] All the files I changed are in the same world language, for example: only English changes, or only Chinese changes, etc.

Closes #38774 

I have added extra test cases that don't allow any possibility of solution creation without actual input addition. The previous test case could easily be hacked as it always gives answers either 5 or undefined.

### CODE REVIEW

**Comment by rajat641** [comment]
@moT01 , @Sky020 : Can you please review the PR and let me know if it's fine.

**Comment by raisedadead** [comment]
Hi @rajat641 

Thanks for your interest and excitement. 

We request you to bear with the mods and respect their time, they are volunteers like you 🙂, and will surely get back to you with the feedback.

Thanks for your patience, and meanwhile please I encourage you to go ahead and work on other help wanted issues.

**Comment by rajat641** [comment]
Hi @raisedadead , I didn't know that you were a part of a really small team and you had other things to do. I will take care of it in the future. I appreciate your response.

**Review by ShaunSHamilton — APPROVED** [review]
LGTM 👍

**Review by ShaunSHamilton — APPROVED** [review]
LGTM 👍

**Review by raisedadead — APPROVED** [review]

**Comment by raisedadead** [comment]
#### :sparkles: :sparkles: **AWESOME! LGTM.** :sparkles: :sparkles: 

Thanks @rajat641, for this pull request and contributing to the code-base for the first time.
We will be looking forward for more contributions in future.

Cheers and happy contributing!

**Pull request merged**
