### PR TITLE
Brazilian Portuguese translation of Getting Started section.

### PR DESCRIPTION
**Pull request by samanthakem**
#### Pre-Submission Checklist

- [x] Your pull request targets the `staging` branch of FreeCodeCamp.
- [x] Branch starts with either `fix/`, `feature/`, or `translate/` (e.g. `fix/signin-issue`)
- [x] You have only one commit (if not, [squash](http://forum.freecodecamp.com/t/how-to-squash-multiple-commits-into-one-with-git/13231) them into one commit).
- [x] All new and existing tests pass the command `npm run test-challenges`. Use `git commit --amend` to amend any fixes.
#### Type of Change

- [ ] Small bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds new functionality)
- [ ] Breaking change (fix or feature that would change existing functionality)
- [x] Add new translation (feature adding new translations)
#### Checklist:

- [ ] Tested changes locally.
- [ ] Closes currently open issue (replace XXXX with an issue no): Closes #XXXX
#### Description

I did the translation of the session - Getting Started **[Learn How Free Code Camp Works]** - into Brazilian Portuguese.

### CODE REVIEW

**Comment by samanthakem** [comment]
I am having hard time when squashing the commit because of all the commits related to merging. Could someone guide me in how to fix that?

**Comment by atjonathan** [comment]
@samanthakem, try `git rebase -i HEAD~n`, remove all unnecessary commits and then pushing using `git push -f`!

**Comment by samanthakem** [comment]
@atjonathan if I remove the unnecessary commits (merge PRs), dont you think I am removing the changes from these commits as well? I tried the `git rebase -i HEAD~n` but I am still having problems because the merge commits are on the top so there's no way I squash it without a my own previous commit. Sorry about that. Let me know if you got more ideas :)

**Comment by samanthakem** [comment]
hey @atjonathan it looks like does not make sense for me to squash it because I just dont have a single commit made by myself. In fact, if I run
`git rebase -i --autosquash staging`
It just shows up the ONLY commit I made with the changes which is:
_pick 5f275c6 adding Brazilian Portuguese translation for getting started_

The others one shown on this PR are Merge commits, I can't squash someone's else commits on mine :/ 

Let me know if you have additional thoughts about that.

**Comment by atjonathan** [comment]
@samanthakem, try `git push -f`, it might get rid of the merge commits 😉

**Comment by samanthakem** [comment]
@atjonathan done! thanks a lot ^^

**Comment by hallaathrad** [comment]
Are we ready to go on this one then?

**Comment by atjonathan** [comment]
@samanthakem, I'm still seeing 6 commits 😢

**Comment by hallaathrad** [comment]
There :) case closed

**Comment by samanthakem** [comment]
thanks @hallaathrad !

hey @atjonathan i got the notification about the 6 commits still... i was able to squash only two of my own commits (reduced from 7 to 6 commits), every time i tried to squash @BerkeleyTrue's commits (the merge ones) I was getting error message saying that was not allowed to do that :( that was my first problem with git squash command, trying to figure out how to squash someone's else previous commit on mine. I did not get the complain from the bot saying that I had more than one commit after I squashed both my own commits into one so I figured I made it right. Could you go over all the current commits and confirm there was nothing I could do about the merge commits? I am just asking because I want to learn as well :) I really appreciate that. Thanks!

**Comment by hallaathrad** [comment]
@samanthakem The issue you were having is because your branch must've been out of sync from the staging one at the moment of submission. Else it would've only shown your own commits.

Regardless, for this reason I usually pull from staging before I commit the changes I want to submit. And then push and PR. 

Anyway, obrigado for your submission and we hope seeing some more coming from you.

**Comment by samanthakem** [comment]
@hallaathrad so in this case, there is no way i squash the commits right? just wondering...

Por nada! hahaha I certainly will contribute more. Thanks a lot.

**Pull request merged**
