### PR TITLE
Define the Head and Body of an HTML Document for challenge solution

### LINKED ISSUE #35757: Define the Head and Body of an HTML Document | Can pass tests without a body tag
**Describe your problem and how to reproduce it:**
The request for this problem is: `Edit the markup so there's a head and a body. The head element should only include the title, and the body element should only include the h1 and p.`  
However, all the tests pass even without a `body` tag, including these two tests specifically checking for it:
- There should be only one body element on the page.
- The body element should wrap around both the h1 and p elements.

Code that will pass:
```
<!DOCTYPE html>
<html>
<head>
    <title>The best page ever</title>
</head>

<h1>The best page ever</h1>
<p>Lorem Ipsum</p>
</html>
```

**Add a Link to the page with the problem:**
https://learn.freecodecamp.org/responsive-web-design/basic-html-and-html5/define-the-head-and-body-of-an-html-document

**Tell us about your browser and operating system:**
* Browser Name: Chrome
* Browser Version: 73
* Operating System: Windows 10

**If possible, add a screenshot here (you can drag and drop, png, jpg, gif, etc. in this box):**
page

### PR DESCRIPTION
**Pull request by sil3nthill**
- [x] I have read [freeCodeCamp's contribution guidelines](https://github.com/freeCodeCamp/freeCodeCamp/blob/master/CONTRIBUTING.md).
- [x] My pull request has a descriptive title (not a vague title like `Update index.md`)
- [x] My pull request targets the `master` branch of freeCodeCamp.
- [x] None of my changes are plagiarized from another source without proper attribution.
- [x] All the files I changed are in the same world language (for example: only English changes, or only Chinese changes, etc.)
- [x] My changes do not use shortened URLs or affiliate links.

Closes #35757

### CODE REVIEW

**Comment by RandellDawson** [comment]
@sil3nthill  It appears you did not test your code locally as your code fails for invalid syntax.  

Also, you do not have to close the PR.  You just need to fix it.  Also, I don't believe we concluded exactly what the fix needed to be in the original issue.  The regex you are attempting on the 2nd to last test would fail if the body tags were missing but the test would fail for `The <code>head</code> element should wrap around the <code>title</code> element` if the body tags were missing, which would be confusing for the user.  I suggest the extra validation go in either the `There should be only one body element on the page.` test or the `The body element should wrap around both the h1 and p elements.` test to make more since to the campers.

**Comment by sil3nthill** [comment]
hello  @RandellDawson , i see yeah , so just let me close my other pr for this , because i fixed that bug . maybe , i think we need to talk about it in the chat room

**Comment by RandellDawson** [comment]
Reopen this PR then.

**Comment by RandellDawson** [comment]
@sil3nthill Have you resolved this problem locally yet?  If not, how can we help?

**Comment by sil3nthill** [comment]
hello @RandellDawson  i was working on it but i didnt get it do you want to add another test ? 
```
text: The <code>body</code> element should wrap around both the <code>h1</code>and <code>p</code>elements
  testString: assert(code.match(/<head>\s*?<title>\s*?.*?\s*?<\/title>\s*?<\/head>\s*?<body>\s*?.*?\s*?<\/body>/gi), 'The <code>head</code> element should wrap around the <code>title</code> element.');
```
what do you think about this ?

**Comment by PunisherCR** [comment]
hello @RandellDawson  just fixed the bug and tested it locally and all is good 
tests
will update the PR now

**Comment by sil3nthill** [comment]
hello @RandellDawson  just tested the code again locally and everything seems ok ,  and the new PR passed.
tell me if you further details , cheers

**Comment by keerthi-suresh** [comment]
???

**Review by moT01 — CHANGES_REQUESTED** [review]
Thanks for the PR @sil3nthill! Your new test passes without the `h1` and `p` nested within the `body`...

Screen Shot 2019-05-03 at 8 00 36 AM

You should check to make sure the `h1` and `p` tags are nested. Also, since you are adding this new test - you can remove the duplicate one that was there originally. Fixing these should be enough to merge this PR and close the issue. But if you're interested, all the tests need to be redone...

Screen Shot 2019-05-03 at 7 56 20 AM

This second image is what happens when running the default setup code. None of the passing tests should pass at this point. So they should all be redone. If you don't want to redo all of these, that's fine - we can create a new issue after this gets merged to fix the rest.

**Comment by sil3nthill** [comment]
@moT01  i will start working on it now ! thanks

**Comment by sil3nthill** [comment]
if i understood clearly you want to take off the old tests for using `<p> and <h1>` tags , and add them to the regex , correct me if i am wrong @moT01

**Comment by moT01** [comment]
Both of the bottom two tests say "The body element should wrap around both the h1 and p elements" - we only need one of these.

**Comment by sil3nthill** [comment]
@moT01  hello again , i fixed it again and tested it locally tell me if you are okey with this , and make my day with another merge haha ! cheers 

1st case all good :
image
second case if he puts p and h1 outside of body  : 
image
3rd case no h1 or p 
image

**Comment by sil3nthill** [comment]
Also i made it possible to the user to enter h1 before p or p before h1 since the challenge doesnt mention anything about the order of tags

**Comment by moT01** [comment]
The test text is "The body element should wrap around both the h1 and p elements" but if you put the body tags in properly do what that sentence asks, it can still fail if the head or title aren't there. I may be nitpicking too much here, cause I tested it and it works. But could you also remove the checks for the `head` and `title` in your regex - then we should be golden. Sorry to keep asking for changes, it's really probably good enough like this. But that's one edge case that we can solve quick I think.

**Comment by sil3nthill** [comment]
@moT01  yes i got you , i will change it as u want to no problem ! thanks !

**Comment by sil3nthill** [comment]
@moT01  okey no problem i understand , i will just remove those checks for the title and the head

**Review by moT01 — APPROVED** [review]

**Comment by moT01** [comment]
I gave it another quick test. I think it looks good now. Thanks for the PR and the prompt fixes @sil3nthill 😄

**Comment by sil3nthill** [comment]
@moT01  my pleasure ! and thank you for your time !!

**Comment by ojeytonwilliams** [comment]
@sil3nthill Thank you for your contribution to the page! :+1:
We're happy to accept these changes, and look forward to future contributions. :memo:

**Comment by hoffme** [comment]
hi, i made the form in Firefox 68 on Debian 10 32 bits and i get the error in the image. Then I did it in chromium 83 and it works perfectly.

Screenshot_2020-09-18 freeCodeCamp org

**Pull request merged**
