### PR TITLE
fix: handle uppercase and missing user verification

### PR DESCRIPTION
**Pull request by naomi-lgbt**
Checklist:

- [X] I have read [freeCodeCamp's contribution guidelines](https://contribute.freecodecamp.org).
- [X] My pull request has a descriptive title (not a vague title like `Update index.md`)
- [X] My pull request targets the `main` branch of freeCodeCamp.
- [X] I have tested these changes either locally on my machine, or GitPod.

Closes #XXXXX

This should be a hot-fix for instances where `isHonest` isn't set in the database. We'll need to investigate why it isn't being set, but this will ideally resolve the Sentry error.

### CODE REVIEW

**Review by ojeytonwilliams — DISMISSED** [review]
I think the issue was that `user` was `null`, so we need to avoid destructuring it rather than providing a default.

**Comment by nhcarrigan** [comment]
Misread the error message oops.

**Review by raisedadead — APPROVED** [review]
API Code LGTM.

**Review by ShaunSHamilton — APPROVED** [review]
This LGTM 👍 

---

I am busy fixing the `getVerifyCanClaimCert` logic/(error handling) in another PR.

**Pull request merged**
