### PR TITLE
fix(Cypress): show certification wait on editor to load

### PR DESCRIPTION
**Pull request by Sembauke**
Checklist:

- [x] I have read [freeCodeCamp's contribution guidelines](https://contribute.freecodecamp.org).
- [x] My pull request has a descriptive title (not a vague title like `Update index.md`)
- [x] My pull request targets the `main` branch of freeCodeCamp.
- [x] I have tested these changes either locally on my machine, or GitPod.

### CODE REVIEW

**Comment by Sembauke** [comment]
We were doing the same thing 😄

**Review by raisedadead — APPROVED** [review]

**Comment by ojeytonwilliams** [comment]
So, this is probably fine, but timed delays like this are generally hiding the real problem.

I noticed when trying to fix https://github.com/freeCodeCamp/freeCodeCamp/pull/42394 that we just click the login button and immediate do stuff.  It seems that waiting for the login to complete *might* have fixed that PR.  If so, I'd rather try out that solution here.

**Comment by Sembauke** [comment]
> So, this is probably fine, but timed delays like this are generally hiding the real problem.
> 
> I noticed when trying to fix #42394 that we just click the login button and immediate do stuff. It seems that waiting for the login to complete _might_ have fixed that PR. If so, I'd rather try out that solution here.

Yeah Cypress Firefox has a lot of timing problems, I am just trying to prevent Cypress from moving on in this example.

**Comment by ojeytonwilliams** [comment]
> I'll try to add what you did. Maybe it works.

Unfortunately not.  I'll keep digging, but let's merge this so we stop getting so many false positives.

**Review by ojeytonwilliams — APPROVED** [review]
LGTM :+1: 

There may be a way to fix this without requiring a timeout, but it is a solid fix, thanks @Sembauke

**Pull request merged**
