### PR TITLE
Update data type

### PR DESCRIPTION
**Pull request by theprakashkumar**
Checklist:

- [x] I have read [freeCodeCamp's contribution guidelines](https://contribute.freecodecamp.org).
- [x] My pull request has a descriptive title (not a vague title like `Update index.md`)
- [x] My pull request targets the `master` branch of freeCodeCamp.
- [x] All the files I changed are in the same world language, for example: only English changes, or only Chinese changes, etc.

Closes #XXXXX

### CODE REVIEW

**Comment by lasjorg** [comment]
A function isn't considered a Data Type.

> [6.1 ECMAScript Language Types](https://tc39.es/ecma262/#sec-ecmascript-language-types)
> 
> The ECMAScript language types are Undefined, Null, Boolean, String, Symbol, Number, BigInt, and Object.

MDN:

> [Data structures](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Data_structures)
> 
> [Function](https://developer.mozilla.org/en-US/docs/Glossary/Function) non data structure, though it also answers for typeof operator: `typeof instance === "function"`. This answer is done as a special shorthand for Functions, though every Function constructor is derived from Object constructor.
> 
> ["Normal" objects, and functions](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Data_structures#Normal_objects_and_functions)
> 
> Functions are regular objects with the additional capability of being callable.



I guess we should update the list to include BigInt, even if it is still pretty new.

**Comment by lasjorg** [comment]
@ThePrakashKumar Did you not want to update the list with BigInt? You are more than welcome to make a new PR with that change.

**Comment by ThePrakashKumar** [comment]
Hi @lasjorg,
If the function is not a data type then why ([Monzilla](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Data_structures)) says there are NINE. I have also looked at [javascript.info](https://javascript.info/types) they say there is eight basic data type.

**Comment by lasjorg** [comment]
MDN lists it as a type but notes that it is a **non data structure**. A function is basically a callable object.

**Comment by ThePrakashKumar** [comment]
Thanks for your response, I really appreciate it. I am creating a new PR and will delete this one.
Regards!

**Pull request closed without merging**
