### PR TITLE
test: add logs to help debug flaky Cypress test

### PR DESCRIPTION
**Pull request by ojeytonwilliams**
This might help debug https://github.com/freeCodeCamp/freeCodeCamp/runs/3143634260?check_suite_focus=true#step:9:1290

### CODE REVIEW

**Comment by Sembauke** [comment]
Hey @oliver,
It would maybe help to increase the global time out for commands
https://docs.cypress.io/guides/references/configuration#Timeouts

This would probably help with cypress not being able to find objects in time.

**Comment by ojeytonwilliams** [comment]
@Sembauke I'm a little reluctant to increase the timeouts without a solid justification.  If we don't know why a particular timeout needs to be extended, we're hiding either poor performance (4 seconds is already a long time) or a bug.

In this particular case, you can see that this test either fails 5 times in a row or passes.  If it was a timing issue, I'd expect it to fail, say, 1, 2, 3 or 4 times then pass, but it always passes first time or fails 5 times.

**Comment by ojeytonwilliams** [comment]
Thanks for the link, too.  Unfortunately I've been unable to recreate the bug locally - hence this PR.

**Comment by Sembauke** [comment]
I do have an error when running `claim-cert-from-learn.`
image

**Comment by ojeytonwilliams** [comment]
Ah, unfortunately that's just telling me that Cypress will break if we set `SHOW_UPCOMING_CHANGES` to `true`.  I'll cross that bridge when it's a bit closer!

**Comment by gikf** [comment]
Was it tried/considered to use `cy.intercept` - https://docs.cypress.io/api/commands/intercept#Syntax - to intercept requests during the project submission? And to ensure test goes forward only when such requests are completed?

**Comment by ojeytonwilliams** [comment]
No, I'd not considered that. It's a very good thought, though.  Is this something you'd be interested in creating a PR for @gikf ?  If not, I'll take a stab at it, since I'm pretty sure you're right.

**Comment by ojeytonwilliams** [comment]
blocked for now.  If the `intercept` approach fails, we can try this.

**Comment by gikf** [comment]
@ojeytonwilliams Honestly not at this time, so I'd say go ahead :rocket:

**Comment by ojeytonwilliams** [comment]
No worries.  Thanks a ton for the suggestion!

**Comment by ojeytonwilliams** [comment]
The issue seems to be fixed, so I'm closing this.

**Pull request closed without merging**
