### PR TITLE
Add toasts to react app

### LINKED ISSUE #5969: Hike transcript should be larger font, left adjusted

### LINKED ISSUE #5973: Extra semicolons at the top and bottom of the HTML Preview
Two semicolons at the top and bottom of the phone screen.
screen shot 2016-01-08 at 12 05 11 pm

### PR DESCRIPTION
**Pull request by BerkeleyTrue**
Fix for broken Vimeo API
Adds Vimeo to script CSP
question answers happens on mouse up instead of mouse move

closes #5969 
closes #5973

### CODE REVIEW

**Comment by BerkeleyTrue** [comment]
Live on Beta. Seems like react-vimeo is no longer working correctly. That is unrelated to this post. It seems like they have changed their API.

**Comment by SaintPeter** [comment]
I completed 2 hikes but I only got a Toast on the first one.  Looks like it maybe isn't resetting properly?

**Comment by BerkeleyTrue** [comment]
@SaintPeter Thanks. I'll look into it.

**Comment by BerkeleyTrue** [comment]
Latest up on beta

**Comment by BerkeleyTrue** [comment]
Another bug.

**Comment by SaintPeter** [comment]
BTW, this: `http://beta.freecodecamp.com/jobs/568c2c345b8c198319646fa5` is uncool for a job URL.  You should have pretty slugs based on the company name.

The toasts are working fine now, though.

**Comment by BerkeleyTrue** [comment]
@SaintPeter The id is the only unique identifier for Jobs. Also, this PR does not change the functionality of jobs.

**Comment by BerkeleyTrue** [comment]
Latest on Beta.

**Comment by SaintPeter** [comment]
Usability:  
If I scroll down to the bottom of the list of hikes and click on a hike, I'm still at the "bottom of the page" in the hike.  This is pretty confusing, especially once we get a bunch more hikes and to hikes with more text.
image

**Comment by SaintPeter** [comment]
Spelling Error in Routers and Packets:
image

## Usability
Two Toasts at once that basically say the same thing?
image
That's a little weird.Maybe the bottom one is supposed to come first?  Is it supposed to replace the other one?

Toasts should stay opaque for some period of time after they come up.  Right now they come up and are VERY briefly opaque, then they immediately go transparent, which makes them a bit hard to read.  I'd have them stay opaque for maybe half their life, 5 seconds?

Do not all questions have a hint when you give a wrong answer?  At least one appeared to, but I never got another one to open the hint.  Also, should hints be a different color than other toasts?

**Comment by BerkeleyTrue** [comment]
> Two Toasts at once that basically say the same thing?

The first one states that the hike is completed. The app does two things in parallel at this point: load the next challenge, and save to the server.

The second one states that the challenge has successfully saved. It will also state weather this is the first time you have completed the challenge.

> That's a little weird.Maybe the bottom one is supposed to come first? 

Toasts stack on top of each other.

**Comment by SaintPeter** [comment]
RE: Two Toasts.
It's weird to me that they basically both appear at exactly the same time and the one on the bottom is supposed to come first.  Maybe only the second one should display?  It seems like it should be one or the other, not both.

**Comment by BerkeleyTrue** [comment]
> It's weird to me that they basically both appear at exactly the same time 

Try reducing you bandwidth.

**Comment by BerkeleyTrue** [comment]
If there are no obvious bugs this PR should be merged in

**Comment by ltegman** [comment]
Looks good then! Excited to get the vimeo fixes in prod :shipit:

**Comment by BerkeleyTrue** [comment]
@ltegman Thanks!

**Pull request merged**
