### PR TITLE
Scalar addition issue on Element-wise operations

### LINKED ISSUE #40001: Scalar addition issue on Element-wise operations
**Describe your problem and how to reproduce it:**
For the challenge "Rosetta Code: Element-wise operations", it says that operation`("s_add",[[1,2],[3,4]],[[1,2],[3,4]])` should return `[[3,4],[5,6]]`.  However, to find this value, you simply add 2 to each element, which is scalar addition.  The second input should just be the number 2.

**Add a Link to the page with the problem:**
https://www.freecodecamp.org/learn/coding-interview-prep/rosetta-code/element-wise-operations

**Tell us about your browser and operating system:**
* Browser Name: Firefox
* Browser Version: 82
* Operating System: Linux Mint

### PR DESCRIPTION
**Pull request by msreekm**
Checklist:

- [x ] I have read [freeCodeCamp's contribution guidelines](https://contribute.freecodecamp.org).
- [ x] My pull request has a descriptive title (not a vague title like `Update index.md`)
- [x ] My pull request targets the `master` branch of freeCodeCamp.
- [ x] All the files I changed are in the same world language, for example: only English changes, or only Chinese changes, etc.

Closes #40001

### CODE REVIEW

**Review by majestic-owl448 — DISMISSED** [review]
please change files in only one language, as written in the docs and in the checklist that you have checked in the pull request

**Comment by msreekm** [comment]
so create 2 PR's for english and chinese?

**Comment by msreekm** [comment]
removed chinese from PR ,let me know if I should create another PR for chinese?

**Comment by RandellDawson** [comment]
> removed chinese from PR ,let me know if I should create another PR for Chinese?

The Chinese version will be translated using a different platform in the near future, so there is no need to make this change right now.

**Review by ShaunSHamilton — APPROVED** [review]
This LGTM 👍 

@msreekm For future PRs, please consult the [contributors docs](https://contribute.freecodecamp.org/#/index), specifically to see concerning working off of a separate branch.

**Review by RandellDawson — APPROVED** [review]

**Comment by RandellDawson** [comment]
Congrats @msreekm on your first pull request (PR)! 🎉

Thank you for your contribution to the page! 👍
We're happy to accept these changes, and look forward to future contributions. 📝

**Comment by msreekm** [comment]
Nice, looking forward to contributing more to this awesome platform.  I have learned a lot from here. it is time to give back to community!

**Pull request merged**
