### PR TITLE
Added example with one parameter to master branch

### PR DESCRIPTION
**Pull request by BagheeraBear**
- [ ] I have read [freeCodeCamp's contribution guidelines](https://github.com/freeCodeCamp/freeCodeCamp/blob/master/CONTRIBUTING.md).
- [ ] My pull request has a descriptive title (not a vague title like `Update index.md`)
- [ ] My pull request targets the `master` branch of freeCodeCamp.
- [ ] None of my changes are plagiarized from another source without proper attribution.
- [ ] My article does not contain shortened URLs or affiliate links.

If your pull request closes a GitHub issue, replace the XXXXX below with the issue number.

Closes #XXXXX

### CODE REVIEW

**Comment by moT01** [comment]
PR's need to target the master branch - please reopen this targeting that branch if you want to add this information - Thanks!

**Comment by BagheeraBear** [comment]
> PR's need to target the master branch - please reopen this targeting that branch if you want to add this information - Thanks!

Ok, really new to this, I don't see where I target the wrong branch

**Comment by moT01** [comment]
@BagheeraBear at the top it says `BagheeraBear wants to merge 1 commit into freeCodeCamp:moT01-patch-1 from BagheeraBear:patch-5` - I accidentally made that branch so I'm trying to get it deleted so more people don't do this - don't worry about being new, this is how you learn - so when you make a PR, you should be able to select which branch to "commit into", it might also be called the `head` branch - and that should be `master`

**Comment by BagheeraBear** [comment]
> @BagheeraBear at the top it says `BagheeraBear wants to merge 1 commit into freeCodeCamp:moT01-patch-1 from BagheeraBear:patch-5` - I accidentally made that branch so I'm trying to get it deleted so more people don't do this - don't worry about being new, this is how you learn - so when you make a PR, you should be able to select which branch to "commit into", it might also be called the `head` branch - and that should be `master`

Ok, I think I found where to change to master. But how do I reopen the issue? :)

**Comment by moT01** [comment]
I did that for you, but you could have probably done it at the bottom below the comment box - there should be a `close` button now since it's open again

**Comment by BagheeraBear** [comment]
> I did that for you, but you could have probably done it at the bottom below the comment box - there should be a `close` button now since it's open again

Thank you! Should I close it now, or just leave it?

**Comment by moT01** [comment]
One other thing... In that PR template, you should put an `x` next to all those things listed - in between the `[]`, like this `[x]` assuming they are true - you can leave it open if you want it added

**Comment by Nirajn2311** [comment]
@BagheeraBear just leave it, someone will review and merge it soon. Congrats on your first PR.

**Review by RandellDawson — APPROVED** [review]

**Comment by RandellDawson** [comment]
Thank you for your contribution to the page! 👍
We're happy to accept these changes, and look forward to future contributions. 🎉

**Pull request merged**
