### PR TITLE
this pull request solves the issue #48085which states that line 191 and 200 in docs how to open a pull request, please consider

### LINKED ISSUE #48085: Typo on how to open pull request document
in the document, the instruction header says this:

> Resolve any conflicts, and cleanup, install run tests

because how the following instruction looks

 ```console
   npm run clean

   npm ci
   npm run test:curriculum --superblock=<superblock-name>

   # example:

   # npm run test:curriculum --superblock=python-for-everybody

 ```
 
I agree with the camper suggestion, in the original issue
 
 > Resolve any conflicts, cleanup, install dependencies and run tests
 
Can we clear the empty line in the code block, it's annoying me 🤣 
 
 here is the file

https://github.com/freeCodeCamp/freeCodeCamp/blob/6df93646db629a535c3ae193aee1c8e16d33feed/docs/how-to-open-a-pull-request.md#L191

here is the original issue

https://freecodecamp.crowdin.com/translate/457d487b1586f10d2fba3c4ccb9c5453/5358/en-ptbr?filter=basic&value=0#q=1222499

### PR DESCRIPTION
**Pull request by getcoder-top**
Checklist:

- [x] I have read [freeCodeCamp's contribution guidelines](https://contribute.freecodecamp.org).
- [x] My pull request has a descriptive title (not a vague title like `Update index.md`)
- [x] My pull request targets the `main` branch of freeCodeCamp.
- [ ] I have tested these changes either locally on my machine, or GitPod.

Closes #48085

### CODE REVIEW

**Comment by getcoder-top** [comment]
the codefactor is again and again telling new issues

**Comment by raisedadead** [comment]
Thank you for opening this pull request.

We’ve reviewed your pull request and decided not to merge it; However, We would welcome future pull requests from you. 

You are welcome to [read these guidelines](https://contribute.freecodecamp.org) to learn more about contributing to this project. 

Happy contributing.

**Comment by getcoder-top** [comment]
please review and thank you for giving me this chance

**Comment by raisedadead** [comment]
We have reviewed this already.

The maintainers of this repo will not take you seriously unless you read the guidelines and follow them seriously.

We understand you are new to contributing; please visit our chat rooms, also mentioned in the guidelines, for further help.

Good luck.

**Pull request closed without merging**
