### PR TITLE
Update the return value of values method in create a set class challenge

### LINKED ISSUE #40443: The return value of values method is incorrect in project seed.
**Describe your problem and how to reproduce it:**

In the [Data Structures: Create a Set Class](https://www.freecodecamp.org/learn/coding-interview-prep/data-structures/create-a-set-class) challenge of data structures, interview prep section, there is a method called `values` defined in the `Set` class which emulates sets. Apparently the challenge requires one to add new elements to `this.dictionary = {}` so that it takes up the shape:
```js
this.dictionary = {"a": "a", "1": 1, "2": 2, "c": "c" };
```
and the `values` method is
```js
 values() {
    return Object.keys(this.dictionary);
  }
``` 
This doesn't return the correct values stored in the set. This would be correct if we were only storing strings in the set. I think the `values` method should return `Object.values(this.dictionary)` not `Object.keys(this.dictionary)`. The project seed is [here](https://github.com/freeCodeCamp/freeCodeCamp/blob/master/curriculum/challenges/english/10-coding-interview-prep/data-structures/create-a-set-class.md#--seed--). It appears the tests also rely on the `values` method.

**Add a Link to the page with the problem:**

https://www.freecodecamp.org/learn/coding-interview-prep/data-structures/create-a-set-class

**Tell us about your browser and operating system:**
* Browser Name: N/A
* Browser Version: N/A
* Operating System: N/A

**If possible, add a screenshot here (you can drag and drop, png, jpg, gif, etc. in this box):**

### PR DESCRIPTION
**Pull request by qaz6209031**
Checklist:

- [x] I have read [freeCodeCamp's contribution guidelines](https://contribute.freecodecamp.org).
- [x] My pull request has a descriptive title (not a vague title like `Update index.md`)
- [x] My pull request targets the `master` branch of freeCodeCamp.
- [x] All the files I changed are in the same world language, for example: only English changes, or only Chinese changes, etc.

Closes #40443

Change values method in both contest and solution in create a set class, and revise the solution add method

### CODE REVIEW

**Comment by qaz6209031** [comment]
This is my first open source contribution, please correct me if I did anything wrong

**Review by naomi-lgbt — APPROVED** [review]
LGTM~! 🥳 This seems to resolve the linked issue.

Congratulations on your first pull request to this project! We look forward to future contributions!

A couple of quick notes - first, our workflow will require at least one additional approval before this can be merged. Second, in general the issues labelled with `needs help for triage` have not been discussed yet. Opening a PR for those issues can lead to your PR being closed if the issue discussion results in an alternative fix or a decision that the issue is not something that needs corrected. In general, it is best to look for issues labelled `help wanted` as those have been identified as ready for contributions. 🙂

**Review by RandellDawson — APPROVED** [review]
LGTM

**Comment by RandellDawson** [comment]
Congrats @qaz6209031 on your first pull request (PR)! 🎉

Thank you for your contribution to the page! 👍
We're happy to accept these changes, and look forward to future contributions. 📝

**Pull request merged**
