### PR TITLE
Change several wordings of the text.

### PR DESCRIPTION
**Pull request by BurIgor**
- [x] I have read [freeCodeCamp's contribution guidelines](https://github.com/freeCodeCamp/freeCodeCamp/blob/master/CONTRIBUTING.md).
- [x] My pull request has a descriptive title (not a vague title like `Update index.md`)
- [x] My pull request targets the `master` branch of freeCodeCamp.
- [x] None of my changes are plagiarized from another source without proper attribution.
- [x] My article does not contain shortened URLs or affiliate links.

If your pull request closes a GitHub issue, replace the XXXXX below with the issue number.

Closes #XXXXX

### CODE REVIEW

**Comment by RandellDawson** [comment]
Why did you close this PR?

**Comment by BurIgor** [comment]
Sorry, I am not very familiar with github. I've made a few corrections
(translated into Russian), but I can't see them. I probably did something
wrong.

вс, 28 окт. 2018 г. в 0:56, Randell Dawson <notifications@github.com>:

**Comment by RandellDawson** [comment]
If you need assistance try https://gitter.im/FreeCodeCamp/Contributors where you can ask for help.

**Comment by BurIgor** [comment]
Thanks! )

**Pull request closed without merging**
