### PR TITLE
chore(curriculum): Front End catagories links standardized.

### LINKED ISSUE #47691: Update data viz demo project URL's
### Describe the Issue

All the data viz projects were created on our .rocks domain. We just need to replace the codepen URL's with the new addresses in the curriculum files of those five projects.

Here's the URL's:
https://bar-chart.freecodecamp.rocks/
https://scatterplot-graph.freecodecamp.rocks/
https://heat-map.freecodecamp.rocks/
https://choropleth-map.freecodecamp.rocks/
https://treemap-diagram.freecodecamp.rocks/

And the [project files are here](https://github.com/freeCodeCamp/freeCodeCamp/tree/main/curriculum/challenges/english/04-data-visualization/data-visualization-projects)

### PR DESCRIPTION
**Pull request by IvanoskiHarmonia**
Checklist:

- [x] I have read [freeCodeCamp's contribution guidelines](https://contribute.freecodecamp.org).
- [x] My pull request has a descriptive title (not a vague title like `Update index.md`)
- [x] My pull request targets the `main` branch of freeCodeCamp.
- [x] I have tested these changes either locally on my machine, or GitPod.

Closes #47691

This is my second pull request on this because the last one I forgot to change the "a" tag,

Sorry about that.

### CODE REVIEW

**Comment by moT01** [comment]
no worries @IvanoskiHarmonia - thanks for the PR 🎉 

Mind changing that `Closes #47695` in the PR description to `Closes #47691` - the issue that it closes. Thanks.

**Comment by IvanoskiHarmonia** [comment]
Hey @moT01,

I just made the change, let me know what you think.

**Comment by ieahleen** [comment]
Hey @IvanoskiHarmonia 

This PR seems to make similar changes as the existing PR #47694. As such, we are going to close this as duplicate.

If you feel you have additional changes to expand upon this PR, please feel free to push your commits and request this PR be reopened.

Thanks again! 😊

---

If you have any questions, feel free to ask questions on the ["Contributors" category on our forum](https://forum.freecodecamp.org/c/contributors) or [the contributors chat room](https://discord.gg/PRyKn3Vbay).

**Comment by IvanoskiHarmonia** [comment]
Hey @ieahleen

Yea I understand,

I got a question though: my changes were exactly the same and were done before his pull request, how do you guys decide who's pull request gets to be merged? 

Thank you in advance, and sorry for the probably weird question, but just curious.

**Comment by ieahleen** [comment]
Hey @IvanoskiHarmonia, Your PR is 47698, the merged one is 47694, it was created earlier, I was opening PRs in order from the issue.
Also, not linking the issue could mean that reviewers don't see your PR, so make sure that you link the issue (`closes #xxxxx`), as even if yours is the first, it doesn't matter if it's reviewed last.

**Comment by IvanoskiHarmonia** [comment]
@ieahleen yeah I made a slight mistake when I was referencing the issue the first time but I fixed it later.

My bad about that I didn't see the exact time of when the merged repo had made the pull request.

Thanks for the explanation I will make sure I don't make the same mistake again in the future.

**Pull request closed without merging**
