### PR TITLE
Updated text formatting and inconsistencies for files in basic-html-and-html5 challenges

### PR DESCRIPTION
**Pull request by lauren-van-sloun**
- [x] I have read [freeCodeCamp's contribution guidelines](https://github.com/freeCodeCamp/freeCodeCamp/blob/master/CONTRIBUTING.md).
- [x] My pull request has a descriptive title (not a vague title like `Update index.md`)
- [x] My pull request targets the `master` branch of freeCodeCamp.
- [x] None of my changes are plagiarized from another source without proper attribution.
- [x] My article does not contain shortened URLs or affiliate links.

There were a lot of minor inconsistencies I noticed when going through the [basic-html-and-html5](https://learn.freecodecamp.org/responsive-web-design/basic-html-and-html5) challenges. Most of the things I noticed were places where words would be formatted as code on one page, but not another. (ex "`anchor` element" vs "anchor element"). Other small fixes include a missing period and changing things like "`radio buttons`" to "`radio button`s".

Let me know if you want any of the changes reverted or want a different style applied. Thanks!

### CODE REVIEW

**Review by raisedadead — APPROVED** [review]
LGTM

**Comment by Ashera138** [comment]
I'm not sure why CI is failing.

**Comment by paulywill** [comment]
@Ashera138 	The reason the CI is failing is because of the article/file name '3D':

```
Error: 
Upper case characters found in 3D, all folder names must be lower case
  Found in :
    /home/travis/build/freeCodeCamp/freeCodeCamp/guide/english/3D
```

This should be changed to '3d'.

**Comment by paulywill** [comment]
@raisedadead This test is tripping on the folder name '3D'.

**Pull request merged**
