### PR TITLE
C stack implementation using array

### PR DESCRIPTION
**Pull request by mimikaan**
I am implementing a stack using an array.

- [x] I have read [freeCodeCamp's contribution guidelines](https://github.com/freeCodeCamp/freeCodeCamp/blob/master/CONTRIBUTING.md).
- [x] My pull request has a descriptive title (not a vague title like `Update index.md`)
- [x] My pull request targets the `master` branch of freeCodeCamp.
- [x] None of my changes are plagiarized from another source without proper attribution.
- [x] My article does not contain shortened URLs or affiliate links.

If your pull request closes a GitHub issue, replace the XXXXX below with the issue number.

Closes #XXXXX

### CODE REVIEW

**Comment by mimikaan** [comment]
Stack implementation using array

**Comment by RandellDawson** [comment]
Please use PR titles which explain what you are changing. If it is a translation, please also indicate **translation: language name**.  This let's the reviewer quickly know what kind of contribution you have made.  

Thank you

**Comment by scissorsneedfoodtoo** [comment]
@mimikaan, thanks for taking the time to submit this PR. Your code looks good, though a bit of the text seems to be directly from https://www.quora.com/What-is-the-difference-between-a-stack-and-a-linked-list. Also, there are some spelling errors in your code, things like traverse, enter, and elements. Could you make those changes and let us know when you're finished?

**Comment by RandellDawson** [comment]
Hi,

As there has been no response from your end for a while, I am closing this PR.

Feel free to create a new PR if you still wish to make the changes you originally added in this PR.  Also, remember to re-sync your fork, so you have the latest version of master in case it has changed significantly.

Happy Coding!

**Pull request closed without merging**
