### PR TITLE
fix: resolve lint error in paypal-button

### PR DESCRIPTION
**Pull request by naomi-lgbt**
Checklist:

- [X] I have read [freeCodeCamp's contribution guidelines](https://contribute.freecodecamp.org).
- [X] My pull request has a descriptive title (not a vague title like `Update index.md`)
- [X] My pull request targets the `main` branch of freeCodeCamp.
- [X] I have tested these changes either locally on my machine, or GitPod.

Closes #XXXXX

This should fix the lint error that's coming up in "unchanged files with check annotations" on all of our PRs.

### CODE REVIEW

**Comment by ojeytonwilliams** [comment]
Have you any idea why was *only* CodeFactor that was complaining?

**Review by ojeytonwilliams — APPROVED** [review]

**Comment by nhcarrigan** [comment]
It wasn't only codefactor, it was the linter too.
image

image

What I don't understand is why it's not a non-zero exit code.

**Comment by ojeytonwilliams** [comment]
I completely missed that, I just assumed that there was some bizarre difference between my machine and CI.  But no, the error code is 0... Cheers, @nhcarrigan that's been bothering me for a while!

**Review by ShaunSHamilton — APPROVED** [review]
Yay!

I actually spent a little time looking into this, but was not sure what could fix it.

**Pull request merged**
