### PR TITLE
fix(client): disable unnecessary features in Monaco editor

### LINKED ISSUE #38541: Monaco Editor: Add delay to hover or disable
In some cases, the hover is blocking the code and it seems a bit intrusive with the default delay. See gif.

editor-hover

Do we even want the hover?

I think we should at least add a delay of like 2000 or more. Not sure how the positioning of the tooltip is done?

[Editor.js](https://github.com/freeCodeCamp/freeCodeCamp/blob/master/client/src/templates/Challenges/classic/Editor.js) options (one or the other):
```
hover: {
  enabled: false,
  delay: 2000
}
```

https://microsoft.github.io/monaco-editor/api/interfaces/monaco.editor.ieditorhoveroptions.html

### PR DESCRIPTION
**Pull request by AshNaz87**
Checklist:

- [x] I have read [freeCodeCamp's contribution guidelines](https://github.com/freeCodeCamp/freeCodeCamp/blob/master/CONTRIBUTING.md).
- [x] My pull request has a descriptive title (not a vague title like `Update index.md`)
- [x] My pull request targets the `master` branch of freeCodeCamp.
- [x] All the files I changed are in the same world language, for example: only English changes, or only Chinese changes, etc.

Closes #38541

### CODE REVIEW

**Review by raisedadead — COMMENTED** [review]
This looks good. IMHO, we should remove these too:

image

**Comment by AshNaz87** [comment]
@raisedadead Disabled more features. Please check

**Comment by raisedadead** [comment]
Can you share some screenshots of the before and after of the updates you made? I am having trouble to confirm this locally.

**Comment by AshNaz87** [comment]
@raisedadead Thanks for the heads up.

Two things I found handy:

1. Enabling the `formatOnPaste` option. It 

> Controls if the editor should allow to move selections via drag and drop.

2. Disabling the `dragAndDrop` option. It

> Enable the suggestion box to pop-up on trigger characters.

Which I found a little annoying as well

**Comment by lasjorg** [comment]
@AshNaz87 We may also want to disable the lightbulb.
```
lightbulb: {
  enabled: false
}
```
https://microsoft.github.io/monaco-editor/api/interfaces/monaco.editor.ieditorlightbulboptions.html

@raisedadead Not sure removing items from the context menu is exposed by the API (I know you can add actions).
https://github.com/Microsoft/monaco-editor/issues/1280

Here is some not so pretty CSS that removes the context menu items and separators, except the cut/copy and except items added by some context, like selecting text will add a new format selection item to the menu.

```
.monaco-menu .monaco-action-bar.vertical .action-item:nth-child(-n + 8),
.monaco-menu .monaco-action-bar.vertical .action-item:last-child,
.monaco-menu .monaco-action-bar.vertical .action-label.separator {
  display: none !important;
}
```
context-menu-no-selection
context-menu-selection

I'm also not sure you can disable the `Ctrl + Space` suggest menu.
https://github.com/microsoft/monaco-editor/issues/1681

You can set it to just 1 item `suggest: { maxVisibleSuggestions: 0 }` (yes 0 leaves 1 item, go figure) but it still shows up.
https://microsoft.github.io/monaco-editor/api/interfaces/monaco.editor.isuggestoptions.html#maxvisiblesuggestions

We can again hide it with CSS.
```
.monaco-editor .editor-widget {
  display: none !important;
}
```

Hiding stuff with CSS is less that optimal, but it might be the only choice.


Some relavant files:

monaco-editor CSS files:
node_modules\monaco-editor\esm\vs\base\browser\ui\actionbar\actionbar.css
node_modules\monaco-editor\dev\vs\editor\editor.main.css

Guessing the CSS changes would go in this file:
freeCodeCamp\client\src\templates\Challenges\classic\classic.css

**Comment by raisedadead** [comment]
I think all of the above suggestions (using CSS) are okay for us. @AshNaz87 can you please update the PR taking the advice above.

**Comment by AshNaz87** [comment]
Made the changes

@raisedadead, @lasjorg Please check

**Comment by lasjorg** [comment]
@AshNaz87 Sorry, I just realized that depending on the challenge the context menu will contain different amounts of items. Which breaks the CSS that hides everything but the cut/copy.

Old context menu with fewer items:
fewer-items-original-context
New context menu with fewer items:
fewer-items-new-context


I'm also starting to doubt just how useful that menu really is. Maybe we should just disable it completely instead like @raisedadead suggested from the start? So keep the CSS that hides the .editor-widget and just disable the context menu in the options `contextmenu: false`.

The only issue disabling the context menu causes is it makes the native browser context menu show up instead but you can't use it for anything (like copy/paste for example), which might be a bit confusing UX.

**Comment by lasjorg** [comment]
@AshNaz87 Or we can count backwards in the CSS and that might be consistent across all context menus. If you can help check that I'm correct about this that would be great.

```
.monaco-menu .monaco-action-bar.vertical .action-item:nth-last-child(n + 5),
.monaco-menu .monaco-action-bar.vertical .action-item:last-child,
.monaco-menu .monaco-action-bar.vertical .action-label.separator {
  display: none !important;
}
```

**Comment by ojeytonwilliams** [comment]
The separators can be made to look a little nicer like this:
```css
.monaco-menu a.action-label.codicon.separator.disabled {
  border: 0 !important;
  border-bottom: 1px solid var(--secondary-color) !important;
}
```
so in night mode it looks like this:
NightMenu
and day mode:
DayMenu

I think it's worth keeping the menu, since there's a bunch of useful things in there and, as @lasjorg pointed out, removing it would make right-clicks behave oddly.

**Comment by AshNaz87** [comment]
@ojeytonwilliams Good shout

**Comment by lasjorg** [comment]
@ojeytonwilliams I don't mind having the context menu. The thing is, we are already removing "useful" features, like intellisense/code completion.

The issue I made that got this PR rolling was just about making sure that the hover didn't cover the code.

Personally, I would keep code completion as I think it can be helpful and increases discoverability. Dotting into an object/array/string and seeing all the methods on the object is a useful feature to have even for beginners, in my opinion.

It just sounded like it had been decided at some point that the editor should be totally stripped of all such functionality. Not sure what the consensus is here?

**Comment by raisedadead** [comment]
We should remove the code completion. I think we are fine being opinionated about it, its more distraction unless we perfect the config to be without the additional bugs and complaints it brings.

As for the right-click menu, if its too hacky with css, we can let it be.

**Comment by raisedadead** [comment]
@AshNaz87 

Here is what this PR should do:

1. Remove the code completion and anything additional other than the right-click menu.
2. The right-click menu if it can be removed using any config options, should be removed, if not let's leave it as is.

**Comment by ojeytonwilliams** [comment]
I'm dumb, sorry everyone. I thought we just wanted the spacers cleaning up, not removing actions from it.

Anyway, the right-click menu can be disabled by adding `contextmenu: false` to the options. @raisedadead if there's an ideal menu you want, I can take a look at customising it, but you just want it gone, right?

**Comment by raisedadead** [comment]
> if there's an ideal menu you want, I can take a look at customising it, but you just want it gone, right?

Ideally we want:

1. All context based auto-suggestions, hover based definitions, etc. to be gone.
2. The right-click menu can stay or go depending on complexity. If it can stay with only copy / paste menu items, even better.

**Comment by ojeytonwilliams** [comment]
> If it can stay with only copy / paste menu items, even better.

In principle it could be pared down to just copy + cut (paste isn't an option - not sure why).  I'll see if I can figure out how.

**Comment by ojeytonwilliams** [comment]
Sorry, @lasjorg I didn't read your comments carefully enough - apologies for just repeating what you were saying!  

I'm leaning towards just removing the context menu, since the css solution seems brittle.  It could easily break if we update the editor.  Hopefully they will add an api for that at some point, then we can easily configure it.

Also, all the commands will be accessible via keyboard shortcuts, so people who're used to vscode should still be fine.

**Comment by lasjorg** [comment]
@ojeytonwilliams No worries.

I think the counting backward CSS [I posted](https://github.com/freeCodeCamp/freeCodeCamp/pull/38551#issuecomment-614916849) for the context menu is less likely to break as I don't think new items are added to the end of the menu. But I agree it's far from foolproof, any CSS solution is bound to be more susceptible to breakage. For the widget, I don't think there is another option.

BTW. The missing Paste functionality is a browser limitation.
https://github.com/microsoft/monaco-editor/issues/391#issuecomment-312237052

**Comment by ojeytonwilliams** [comment]
Thanks, I was wondering which browsers could paste, since that could also break the css solution. If no modern ones can, at least that isn't a big problem.

My main concern is that we can't test this at all. I'll take another look at #37053 since that could potentially help.

**Comment by ojeytonwilliams** [comment]
No need to wait for that PR. If I get it working, I'll add tests for the context menu then.

**Comment by raisedadead** [comment]
@AshNaz87 

With the current state of the PR, when nothing is selected right-click leads to:

image

**Comment by AshNaz87** [comment]
@raisedadead Should work now

Would be great if a final consensus can be gathered

**Comment by raisedadead** [comment]
Do you mind sharing a screenshot of a before and after before I pull this down. 

> Would be great if a final consensus can be gathered

If you mean about the approach for this PR, I think [my comment still stands](https://github.com/freeCodeCamp/freeCodeCamp/pull/38551#issuecomment-615386157)

> Ideally we want:
> 
> 1. All context based auto-suggestions, hover based definitions, etc. to be gone.
> 2. The right-click menu can stay or go depending on complexity. If it can stay with only copy / paste menu items, even better.

The best you are able to achieve should be good enough iteration. A screenshot of the various things that this PR fixes would help in the QA.

Most importantly we should not be introducing additional annoyance in a change. :)

**Comment by lasjorg** [comment]
Current PR code has:

1. Code completion.

2. `Ctrl + Space` will open the editor widget.

The CSS that hides the editor-widget takes care of both 1 and 2 as you can't see the widget even if it is triggered (without having to disable anything related in the options).

```
.monaco-editor .editor-widget {
  display: none !important;
}
```

Just to be clear. I was not saying to put code completion back, I was expressing my personal preference and asking for what the consensus was. @raisedadead has the final say, not me.


3. The right-click context menu is back.

A. Use the latest CSS I posted:

```
.monaco-menu .monaco-action-bar.vertical .action-item:nth-last-child(n + 5),
.monaco-menu .monaco-action-bar.vertical .action-item:last-child,
.monaco-menu .monaco-action-bar.vertical .action-label.separator {
  display: none !important;
}
```

Using the `nth-last-child` selector should be much more reliable. The last two context menu groups (command palette and cut/copy/paste) looks reserved to me. I would imagine that new items are not very likely to be added to these groups. I have tested the CSS in challenges with HTML/CSS/JS/React/D3 and the menu stays the same (has cut/copy, with or without making a selection). The only exception here would be in IE where the paste menu item will show up. But as far as I know, the curriculum already has incompatibilities with IE.

B. Remove the context menu completely using the option, which is easy and unlikely to break.

```
contextmenu: {
  enabled: false
}
```

**Comment by AshNaz87** [comment]
@lasjorg Thanks for your suggestions

A few pointers: 

- I've implemented your CSS suggestions. Am also in favour of keeping the cut/copy options on right click
- Edited options:
  - `hover` set to false
  - `dragAndDrop` set to true. This enables users to literally drag and drop text. Think it's useful
  - `lightbulb` object enabled to `false`, which to my understanding is another suggestion box

**Comment by lasjorg** [comment]
@AshNaz87 Looks pretty good to me. Let's wait and see what others have to say.

There is one UI thing I want to ask about. Unused variables get colored differently, they are sort of faded. We can turn it off using the `showUnused: false` option.

@raisedadead Is turning that off something we should consider? Personally I think it's nice to have an indication but I'm wondering if it can be confusing to beginners that don't know why it looks like that.

For now, I'm just posing it as a question.

**Unused variables on:**
unused-on

**Unused variables off:**
unused-off


showUnused: false
https://microsoft.github.io/monaco-editor/api/interfaces/monaco.editor.ieditoroptions.html#showunused

**Comment by raisedadead** [comment]
> ... Unused variables get colored differently ...

We should consider updating the theme(s) instead. Maybe in a separate PR.

**Review by raisedadead — APPROVED** [review]

**Pull request merged**
