### PR TITLE
add solution

### PR DESCRIPTION
**Pull request by dingjy94**
- [x] I have read [freeCodeCamp's contribution guidelines](https://github.com/freeCodeCamp/freeCodeCamp/blob/master/CONTRIBUTING.md).
- [x] My pull request has a descriptive title (not a vague title like `Update index.md`)
- [x] My pull request targets the `master` branch of freeCodeCamp.
- [x] None of my changes are plagiarized from another source without proper attribution.
- [x] All the files I changed are in the same world language (for example: only English changes, or only Chinese changes, etc.)
- [x] My changes do not use shortened URLs or affiliate links.

Closes #XXXXX

### CODE REVIEW

**Comment by RandellDawson** [comment]
@dingjy94 You need to test your solution locally before creating a PR.  It is currently failing Travis (see the Details link above) for why it is failing.

**Comment by RandellDawson** [comment]
@dingjy94 In the future, just the Moderator Tools app which has been discussed on [Gitter](https://gitter.im/FreeCodeCamp/Contributors) and search for the filename, to check for other PRs affecting the same file.

**Comment by dingjy94** [comment]
@RandellDawson Thank you for your instruction. I will test my solution locally. Should I also close the #34496 and create new PR after I test the solution locally?

**Comment by RandellDawson** [comment]
@dingjy94 You do not have to close #34496.  Just push to the same branch and it will update the PR with the new changes.

**Pull request closed without merging**
