### PR TITLE
fix: capitalizing 'or' to 'OR' 

### PR DESCRIPTION
**Pull request by SaifullahBijapur**
Checklist:

- [x] I have read and followed the [contribution guidelines](https://contribute.freecodecamp.org).
- [x] I have read and followed the [how to open a pull request guide](https://contribute.freecodecamp.org/#/how-to-open-a-pull-request).
- [x] My pull request targets the `main` branch of freeCodeCamp.
- [ ] I have tested these changes either locally on my machine, or GitPod.

Closes #53311

### CODE REVIEW

**Comment by SaifullahBijapur** [comment]
hi I'm actually confused, chatbot is  directing me to remove the changes to non-english of files
but I updated the english version README file

**Comment by jdwilkin4** [comment]
@SaifullahBijapur 

> hi I'm actually confused, chatbot is directing me to remove the changes to non-english of files

It looks like everything was resolved so you shouldn't receive any more messages from the bot.

But in general, it is best practice to not work on the main branch when creating PR's.
It always cleaner to work from a new branch.
https://contribute.freecodecamp.org/#/how-to-open-a-pull-request

**Review by jdwilkin4 — CHANGES_REQUESTED** [review]
You have edited the arabic file.
That is why camperbot keeps sending you messages

you need to make changes to the english file
https://github.com/freeCodeCamp/freeCodeCamp/blob/main/curriculum/challenges/english/15-javascript-algorithms-and-data-structures-22/learn-basic-javascript-by-building-a-role-playing-game/62aa21971e3b743844849985.md

**Comment by gikf** [comment]
Hey @SaifullahBijapur 

Thank you for opening this pull request.

As there was different PR - #53321 - making all necessary changes, merged recently, we are going to close this one.

Thank you and happy coding! 😊

---

If you have any questions, feel free to ask questions on the ['Contributors' category on our forum](https://forum.freecodecamp.org/c/contributors) or [the contributors chat room](https://discord.gg/PRyKn3Vbay).

**Pull request closed without merging**
