### PR TITLE
Feat: add new Markdown parser

### PR DESCRIPTION
**Pull request by ojeytonwilliams**
This lets us 

1. Parse mdx files
2. Import boilerplate into them
3. Syntax highlight (in editors) and format
4. Warn users about broken syntax

Gotchas

Prettier does not know what `--fcc-editable-region--` means and tries to transform it in several ways, depending on the code language.  The parser will complain about the transformations I've come across, but it is a little frustrating if you're in the habit of formatting your code.

The commits are mostly organised to make it a bit easier to review, once QA is done we might as well squash the relevant ones. 

TODO:

- [x] id to directive syntax
- [x] prettify the hints

### CODE REVIEW

**Comment by ojeytonwilliams** [comment]
We're not attaching ids to hints, so I need to remove that.

**Review by raisedadead — CHANGES_REQUESTED** [review]
Just blocking a merge.

**Comment by RandellDawson** [comment]
@ojeytonwilliams I believe this PR depends on PR https://github.com/freeCodeCamp/freeCodeCamp/pull/37912 being ran first?  If so, I assume I will first need to pull down #37912 and rebase against master to the merge conflicts and then cherry pick the commits from this PR (once you resolve the conflicts) to be able to test it correctly?

**Comment by ojeytonwilliams** [comment]
@RandellDawson nope, it should work as is.

I'll clarify.  This PR contains, essentially, a snapshot of the transformed curriculum.  It's the MDX that the format scripts generated at the time I pushed this.  Keeping this up-to-date is a bit involved, so I'd rather not keep doing it over and over.

That said, rebasing against master isn't too painful and needs doing, so I'll push up a new version shortly.

**Comment by scissorsneedfoodtoo** [comment]
Just wanted to chime in and say that I tested this locally and everything LGTM. Tried updating the description and seed for a handful of challenges in the current and project based curriculum. Also was able to submit all the projects and claim each certificate. 

Everything seemed to work the way it currently does with md files.

**Review by moT01 — COMMENTED** [review]
I played with this quite a bit. I didn't see any big issues - everything seems to be working.

**Comment by ojeytonwilliams** [comment]
Thanks @scissorsneedfoodtoo and @moT01, much appreciated!  Also, thanks @ahmadabdolsaheb for pointing out a few places where I was less than clear.  The last commit should make it a little easier to understand and more consistent with the naming convention.

**Comment by RandellDawson** [comment]
@ojeytonwilliams I could not find any existing challenges that did not display as I expected, so that is great. At the very bottom of this comment you will see a Python challenge that showed a warning in the browser console, but I did not see any other warnings like this on the various challenges I tested.

I did test a lot of cases that could pop up when creating/modifying challenges/projects steps and made the following observations.  I found some of the error messages might not give enough information to a contributor who happened to make common mistakes.  

1. The first example of such a case is if I removed the ` ```html` from the start of the `## --seed-contents--` section in the `curriculum/challenges/english/01-responsive-web-design/applied-accessibility/improve-accessibility-of-audio-content-with-the-audio-element.mdx` challenge file.  I see the following error in the Node console.

>  Unexpected id syntax must be id
 in file /home/rdawson/Coding/fcc/curriculum/challenges/english/01-responsive-web-design/applied-accessibility/improve-accessibility-of-audio-content-with-the-audio-element.mdx

2. I also notice if I remove the either `# --seed--` or `## --seed-contents--`, but not both,  there is no error in the Node console, but the challenge seed code just does not appear in the challenge.  When I remove both of them, I get the following error message in the Node console, but it makes it sound like a test (hint) is not correct vs. missing the necessary headings for the challenge seed code.
>   Tests must be in (text, ```testString```) order in file /home/rdawson/Coding/fcc/curriculum/challenges/english/01-responsive-web-design/applied-accessibility/improve-accessibility-of-audio-content-with-the-audio-element.mdx

3. Though it is quite obvious what happens without the Node console showing an error, if I remove the ` ``` ` below challenge seed code section, it just ends up displaying the rest of the file as if it should be part of the seed code.  On a side note, not sure why, but I am unable to see the rest of the seed code (line 27) unless I actually shrink the size of the FCC console frame.
image

4. If I do not specify a language after the triple backticks for a code section in the seed code section, I get the correct message about not specifying a language, but it would be nice if it specified the line number in the challenge file with the issue.

5. I notice if I leave off the `js` after the triple backticks for a testString code, there is no Node error message and the challenge tests appear to work as if I put `js` for the language.  I assume it defaults to JavaScript if the it is missing for a test?

6. If I leave off the ` ``` ` after a testString, then it seems as if the rest of the code becomes a part of that code section.  There is no Node error, but when the `Run Tests` button is clicked, there are errors in the browser console to indicate something is wrong.

---
I am seeing the following warning in the browser console when going to `/learn/information-security/python-for-penetration-testing/creating-a-tcp-client` challenge.  

image

**Comment by ojeytonwilliams** [comment]
Hey Randy, thanks for the detailed feedback.  

Points 1, 2 and 4 should be fixed now.  

Point 3 is a bit tricky, though, since that's valid markdown and the solution section is not mandatory.  I'm inclined to leave it for now and try and address it if people have a problems with it.

Point 5: the language tag is largely cosmetic, since all our code is js.  All it currently does is tell your editor how to highlight and format the code inside the backticks.

Point 6: similarly to 3, that's tricky to fix.  It is caught by the tests, though, so I'd prefer to leave this for now.

> On a side note, not sure why, but I am unable to see the rest of the seed code (line 27) unless I actually shrink the size of the FCC console frame.

That's an outstanding bug with the new editor - it does not appear in production.

**Comment by ojeytonwilliams** [comment]
There's also a bigger change.  Instead of using `import x from 'y';` statements (which broke when I updated Remark), we can use Markdown directives like `::import{component="x" from="y"}` to achieve the same thing.  Since this was the only thing we were using mdx for, it should not have much impact.

**Comment by ojeytonwilliams** [comment]
If we like the directives, it would be a fairly painless change to use them for ids, too, rather than abusing image links.

```
![an-id]()
```
becomes
```
::id{#an-id}
```

It's a touch more verbose, but more semantic.

**Comment by RandellDawson** [comment]
> ::id{#an-id}
> It's a touch more verbose, but more semantic.

I like this better.

**Comment by ojeytonwilliams** [comment]
The new id syntax should work now.  The prettifying needs to happen in the other PR, so I'll update this once we can produce prettified hints.

**Comment by RandellDawson** [comment]
LGTM

**Pull request merged**
