### PR TITLE
Update how-to-set-up-freeCodeCamp-locally

### PR DESCRIPTION
**Pull request by moi238**
Made some minor grammatical changes to clarify the message intended by the sentence

- [x] I have read [freeCodeCamp's contribution guidelines](https://github.com/freeCodeCamp/freeCodeCamp/blob/master/CONTRIBUTING.md).
- [x] My pull request has a descriptive title (not a vague title like `Update index.md`)
- [x] My pull request targets the `master` branch of freeCodeCamp.
- [x] None of my changes are plagiarized from another source without proper attribution.
- [x] All the files I changed are in the same world language (for example: only English changes, or only Chinese changes, etc.)
- [x] My changes do not use shortened URLs or affiliate links.

Closes #XXXXX

### CODE REVIEW

**Comment by raisedadead** [comment]
This checklist is there for a reason:

- [ ] My pull request has a descriptive title (not a vague title like `Update index.md`)

**Review by moT01 — CHANGES_REQUESTED** [review]
There are conflicts, and this cannot be merged as is. Please take a look at those @moi238.

**Comment by moT01** [comment]
Fixed conflicts on behalf of user.

**Review by ojeytonwilliams — APPROVED** [review]
LGTM :+1:

**Review by RandellDawson — APPROVED** [review]

**Comment by RandellDawson** [comment]
@moT01 Just waiting on your approval for this one.

**Review by moT01 — APPROVED** [review]

**Comment by moT01** [comment]
Thank you for contributing to freeCodeCamp @moi238 🎉

**Pull request merged**
