### PR TITLE
fix(client): remove unused files

### LINKED ISSUE #47971: Clean up unused files and exports
As discussed in https://github.com/freeCodeCamp/freeCodeCamp/pull/47836 there are several unused files and exports.  We should remove all of these from the codebase.

The full set of tasks is:

- [ ] Remove unused files
- [ ] Add missing dependencies
- [ ] Remove unused exports
- [ ] Remove unused types
- [ ] Remove duplicate exports

The files with issues are:

--- UNUSED FILES (8)
src/assets/icons/donate-with-PayPal.tsx
src/assets/icons/intro-information.tsx
src/components/Donation/duration-amount-options.tsx
src/components/Header/components/user-state.tsx
src/components/helpers/form/block-save-wrapper.tsx
src/components/search/searchPage/empty-search.tsx
src/components/search/searchPage/no-results.tsx
src/components/search/searchPage/search-page-hits.tsx

--- UNLISTED DEPENDENCIES (4)
react-instantsearch-core  src/components/search/searchBar/search-bar.tsx
react-instantsearch-core  src/components/search/searchBar/search-hits.tsx
react-instantsearch-core  src/components/search/searchBar/search-suggestion.tsx
gatsby-link               src/templates/Introduction/components/cert-challenge.tsx

--- UNUSED EXPORTS (46)
DonationOptionsText              src/components/Donation/donation-text-components.tsx
DonationSupportText              src/components/Donation/donation-text-components.tsx
PaypalButton                     src/components/Donation/paypal-button.tsx
sagas                            src/components/Flash/redux/index.ts
NavLinks                         src/components/Header/components/nav-links.tsx
searchIndexNameSelector          src/components/search/redux/index.js
updateSearchIndexName            src/components/search/redux/index.js
SearchBarOptimized               src/components/search/searchBar/search-bar-optimized.tsx
SearchBar                        src/components/search/searchBar/search-bar.tsx
CertificationSettings            src/components/settings/certification.js
updateCurrentChallengeId         src/redux/actions.js
initialState                     src/redux/index.js
defaultFetchState                src/redux/index.js
CurrentCertsPropType             src/redux/prop-types.ts
UserPropType                     src/redux/prop-types.ts
saveChallengeSaga                src/redux/save-challenge-saga.js
sessionMetaSelector              src/redux/selectors.js
defaultDonationFormState         src/redux/types.ts
defaultFetchState                src/redux/types.ts
CompletionModalInner             src/templates/Challenges/components/completion-modal.tsx
getCompletedPercent              src/templates/Challenges/components/completion-modal.tsx
HelpModal                        src/templates/Challenges/components/help-modal.tsx
ShortcutsModal                   src/templates/Challenges/components/shortcuts-modal.tsx
VideoModal                       src/templates/Challenges/components/video-modal.tsx
ToolPanel                        src/templates/Challenges/projects/tool-panel.tsx
replaceNBSP                      src/templates/Challenges/rechallenge/transformers.js
testJS$JSX                       src/templates/Challenges/rechallenge/transformers.js
checkChallenge                   src/templates/Challenges/redux/actions.js
lockCode                         src/templates/Challenges/redux/actions.js
updateJSEnabled                  src/templates/Challenges/redux/actions.js
updateSuccessMessageSaga         src/templates/Challenges/redux/current-challenge-saga.js
currentChallengeSaga             src/templates/Challenges/redux/current-challenge-saga.js
executeChallengeSaga             src/templates/Challenges/redux/execute-challenge-saga.js
executeCancellablePreviewSaga    src/templates/Challenges/redux/execute-challenge-saga.js
executeCancellableChallengeSaga  src/templates/Challenges/redux/execute-challenge-saga.js
currentTabSelector               src/templates/Challenges/redux/selectors.js
buildBackendChallenge            src/templates/Challenges/utils/build.ts
buildJSChallenge                 src/templates/Challenges/utils/build.ts
buildDOMChallenge                src/templates/Challenges/utils/build.ts
Block                            src/templates/Introduction/components/block.tsx
CertChallenge                    src/templates/Introduction/components/cert-challenge.tsx
handledErrorSymbol               src/utils/handled-error.ts
wrapHandledError                 src/utils/handled-error.ts
pathParsers                      src/utils/path-parsers.ts
pathsMap                         utils/challenge-types.js
injectConditionalTags            utils/tags.tsx

--- UNUSED TYPES (17)
LoginProps                interface  src/components/Header/components/Login.tsx
AuthOrProfileProps        interface  src/components/Header/components/auth-or-profile.tsx
MenuButtonProps           interface  src/components/Header/components/menu-button.tsx
NavLinksProps             interface  src/components/Header/components/nav-links.tsx
UniversalNavProps         interface  src/components/Header/components/universal-nav.tsx
HeaderProps               interface  src/components/Header/index.tsx
Validator                 type       src/components/formHelpers/form-validators.tsx
FormProps                 type       src/components/formHelpers/form.tsx
FileKeyChallenge          type       src/redux/prop-types.ts
SavedChallenges           type       src/redux/prop-types.ts
ClaimedCertifications     type       src/redux/prop-types.ts
CertTest                  type       src/redux/prop-types.ts
AllMarkdownRemark         type       src/redux/prop-types.ts
Required                  type       src/redux/prop-types.ts
DefaultDonationFormState  interface  src/redux/types.ts
DefaultFetchState         interface  src/redux/types.ts
HandledError              type       src/utils/handled-error.ts

--- DUPLICATE EXPORTS (4)
PayPalButtonScriptLoader, default src/components/Donation/paypal-button-script-loader.tsx
UniversalNav, default             src/components/Header/components/universal-nav.tsx
Header, default                   src/components/Header/index.tsx
Map, default                      src/components/Map/index.tsx

### PR DESCRIPTION
**Pull request by anubhav823**
Removed unused files as per comments for issue #47971

Checklist:

- [x] I have read [freeCodeCamp's contribution guidelines](https://contribute.freecodecamp.org).
- [x] My pull request has a descriptive title (not a vague title like `Update index.md`)
- [x] My pull request targets the `main` branch of freeCodeCamp.
- [x] I have tested these changes either locally on my machine, or GitPod.

Ref #47971

### CODE REVIEW

**Comment by Sboonny** [comment]
Hey @anubhav823 

Thank you for opening this pull request.

This is a standard message notifying you that we've reviewed your pull request and have decided not to merge it. We would welcome future pull requests from you.

Thank you and happy coding.

**Comment by anubhav823** [comment]
Hey  @Sboonny
Can you please let me know what I am missing in my pull request so that I can correct it?

**Comment by Sboonny** [comment]
no worries, we are using these files. so we closed this pr

**Comment by anubhav823** [comment]
@Sboonny Thank you for reopening the PR!

**Comment by Sboonny** [comment]
No worries, sorry for closing it

**Review by ojeytonwilliams — CHANGES_REQUESTED** [review]
Hi @anubhav823, thanks for taking this on.  It looks like you've removed the unused files, but there's more that needs to be done before we can merge.  I've updated the original issue to better explain the requirements.

**Comment by anubhav823** [comment]
Hi @ojeytonwilliams 
Yes, I am working on the other tasks of the issue. As the ask requires changes to several files, I thought it would be easier to fix some issues at a go.

**Comment by ojeytonwilliams** [comment]
@anubhav823 perfect, thanks!  I've updated your original comment on this PR so that it no longer closes the issue, but multiple PRs are very welcome.

**Comment by Jyotishmoy365** [comment]
Hcyfh

**Comment by anubhav823** [comment]
@ojeytonwilliams I see some files mentioned under Unused Exports section such as-
Block src/templates/Introduction/components/block.tsx

Should I remove the entire Block class from the file?

**Comment by anubhav823** [comment]
Okay. I will do that.
Also, is it possible for you to merge the PR in its current state?

**Comment by ojeytonwilliams** [comment]
We'll need to QA it first, but definitely. Please feel free to create a second PR if you'd like to keep working on this.

**Comment by anubhav823** [comment]
Okay.
Thank you!

**Review by ojeytonwilliams — CHANGES_REQUESTED** [review]
The tests caught a few issues, I'm afraid.  It's worth running `npm lint` before committing to make 100% sure you've not removed something that we need.

For example, `universal-nav` exports the class twice, but it is the default export that's used, so that cannot be removed.

**Comment by anubhav823** [comment]
> The tests caught a few issues, I'm afraid. It's worth running `npm lint` before committing to make 100% sure you've not removed something that we need.
> 
> For example, `universal-nav` exports the class twice, but it is the default export that's used, so that cannot be removed.

I will keep that in mind.

**Comment by ieahleen** [comment]
> I will keep that in mind.

You will also need to update the PR to change that

**Comment by anubhav823** [comment]
@ojeytonwilliams @ieahleen can someone help me out? I am unable to understand why the Lint (16.x) build is not getting triggered.

**Comment by anubhav823** [comment]
> The tests caught a few issues, I'm afraid. It's worth running `npm lint` before committing to make 100% sure you've not removed something that we need.
> 
> For example, `universal-nav` exports the class twice, but it is the default export that's used, so that cannot be removed.

I have fixed the build.

**Comment by ojeytonwilliams** [comment]
Thanks @anubhav823, it's looking good.  All being well I should be able to get this reviewed later this week.

**Comment by anubhav823** [comment]
@ojeytonwilliams Thank you! Meanwhile, I will continue to work on the other files of the issue.

**Review by ojeytonwilliams — APPROVED** [review]
LGTM :+1: 

Nice work, @anubhav823!

**Comment by ojeytonwilliams** [comment]
Thanks again for helping out with this.

FYI, https://github.com/freeCodeCamp/freeCodeCamp/pull/48019 already seems to cover the remaining issues (though there are some failing tests), so more work may not be needed.

**Comment by anubhav823** [comment]
@ojeytonwilliams Thank you! Hope to contribute more to freeCodeCamp!

**Comment by ojeytonwilliams** [comment]
You're very welcome! Thanks again for the help.

**Pull request merged**
