### PR TITLE
feat(client): add local timezone

### LINKED ISSUE #39186: Certificate displays incorrect date
**Describe the bug**
New certificate displays incorrect date.

**To Reproduce**
I can't say I'm really sure of the steps - I claimed the certificate just a few moments ago, and it is still 3 July 2020 local time. The certificate shows "Issued July 4, 2020" however.

**Expected behavior**
Certificate earned date should be based on local time?

**Screenshots**
image

**Desktop (please complete the following information):**
 - OS: Windows 10 v. 1909
 - Browser: Chrome
 - Version: 83.0.4103.116

**Additional context**
The Quality Assurance certification had no such issue.

### PR DESCRIPTION
**Pull request by ShaunSHamilton**
Checklist:

- [x] I have read [freeCodeCamp's contribution guidelines](https://contribute.freecodecamp.org).
- [x] My pull request has a descriptive title (not a vague title like `Update index.md`)
- [x] My pull request targets the `master` branch of freeCodeCamp.
- [x] All the files I changed are in the same world language, for example: only English changes, or only Chinese changes, etc.

Closes #39186 

I have opened this for review, but realise a lot will probably be best changed.

### CODE REVIEW

**Review by raisedadead — COMMENTED** [review]
`timezone` is a new property that you would need to set in the user's boot script and the user's schema (`user.json`). Let us know if you need help in identifying where and how.

**Comment by Sky020** [comment]
Thank you, @raisedadead . I will need guidance with where to look in the user's boot script. However, I have come across a problem:
- The `timezone` property already exists within `user.json`, and is used in other places throughout the codebase. Specifically, I can see it is used for calculating correct offsets for the curriculum streaks, as well as the heatmap.
- Also, the default for `timezone` is sometimes `'UCT'` and '`EST'` (seen in: `api-server/server/boot/challenge.js`, `api-server/server/utils/date-utils.js`, and `api-server/server/utils/publicUserProps.js`)
- I would think having `timezone` be of type `object` is best, but if that is not possible to change due to current user records, then alternatives I can think of are:
 1) Change the `timezones.json` to use the `abbreviation` property as the primary key (currently, it is `id`). This might make dealing with DST more difficult, as there could be no duplicates of _eg._ 'BST' (British) with daylight, and 'BST' (Bangladesh) without.
2) Use the `id` as a string, and if `isNaN(timezone)`, then use default until the user records are changed...

@moT01 , I was told you spent time on the client-side stuff of the heatmap etc., is there any unnecessary use of the `timezone` property that can be excluded/changed?

**Comment by moT01** [comment]
Did you have something specific in mind @Sky020? I believe the way the heatmap currently works is that the user has an array of timestamps in the db for each thing completed. We take that array and calculate the streaks and stuff (on the client) based on the persons timezone who is viewing it. So if **I** look at your map, it shows it as if you completed all your stuff in my timezone - but if **you** look at your map, it shows them completed in your timezone. It's not great, but it has cut down on issues and questions about it. I want to say the timestamps are in the db as UTC time - not positive.

Not sure if that helps at all @Sky020. Now that I am looking at this again, I do believe there are some things that could go. I calculated the streaks client side, they were previously calculated on the back end and stored in the db [here](https://github.com/freeCodeCamp/freeCodeCamp/blob/master/api-server/server/utils/user-stats.js#L51) I think. That function and the one above and below it aren't necessary I don't think. I probably should have looked into that harder when I made the PR, but I suppose I wasn't sure if it would break something - so I left them there.

Side note: The way I understand this after a quick read of the issue... If a user completed say half the curriculum in one timezone, then moved halfway across the world (and updated their timezone)- all those completed challenges might be on a different day now. So if I put somewhere that I completed X certificate on June 10th - moved timeszone, now it might say the 9th or 11th. Just an observation.

**Comment by Sky020** [comment]
>Did you have something specific in mind @Sky020?

Not really. I just want to iron out what is necessary and what is not, because I do not want to mess anything up.

Currently, the issue with the certificates (that this PR almost solves), is the user claims a certificate on server time (for this, it is UTC), but, when they view their certificate, the date could be the day before or after they claimed it, because they could be ahead or behind UTC. This PR takes server time, and converts it to either browser, or user-set, timezone.

Mrugesh did ask for the capability for the user to choose their own timezone. So, if you wanted, you could have your certificate say you completed the certificate a day early...

The crux: My implementation converts the `timezone` property into an object (currently it is a string). Can anyone foresee any issue with this conversion? What can I do to ensure the current database records are not messed up?

**Comment by raisedadead** [comment]
> What can I do to ensure the current database records are not messed up?

You do not need to do much I think, we can get this tested on the staging site. 

But, every place the timezone is being used, should have a default fallback. This will account for all records that may not have the value set for instance. Once a user does set the value, we could use that to compute whatever we need to compute.

**Comment by Sky020** [comment]
@raisedadead Sorry for the mess, but this is now ready for review. I have tested everything except the curriculum tests did not run, because docker does not seem to like puppeteer. I tested using a `mockUser` with a `timezone` as in this PR, as well as a timezone of type string (to see what would happen for current users with such a state).

Once [ES6 imports are added](https://github.com/freeCodeCamp/freeCodeCamp/issues/39277), I would want to change to using it. Otherwise,

**Review by raisedadead — COMMENTED** [review]
Hey @Sky020 

Oliver and I paired to review this PR and we think that there are some complexities that this PR will introduce.

While we are interested in getting the feature in, which is "letting users set a timezone of choice", it would need us to work on a migration something unrelated to the PR.

At this time that migration is a bit involved. We sincerely thank you for the hard work you've put in. For now, we are keeping this on the roadmap.

Oliver will add a quick fix to address the original issue. We will work on adding changes to this PR to address the incompatibility issues with the database.

Apologies for having to keep you waiting, and thanks a lot for working on this.

**Comment by Sky020** [comment]
@raisedadead , Thank you, for the update.

No worries about this PR. You do what makes sense, and is best.

**Comment by raisedadead** [comment]
Closing this for now. 

@ShaunSHamilton thanks a lot for your work on this, which we do intend to add to the codebase. Thanks for your patience, we will update you once we have figured out the approach.

**Pull request closed without merging**
