### PR TITLE
Updated the CSS to be more consistent with the style guide

### PR DESCRIPTION
**Pull request by deveshp**
I've made a small change by adding a space after the colon to make it more consistent with the style guide followed by the curriculum.

- [x] I have read [freeCodeCamp's contribution guidelines](https://github.com/freeCodeCamp/freeCodeCamp/blob/master/CONTRIBUTING.md).
- [x] My pull request has a descriptive title (not a vague title like `Update index.md`)
- [x] My pull request targets the `master` branch of freeCodeCamp.
- [x] None of my changes are plagiarized from another source without proper attribution.
- [x] My article does not contain shortened URLs or affiliate links.

If your pull request closes a GitHub issue, replace the XXXXX below with the issue number.

Closes #XXXXX

### CODE REVIEW

**Comment by RandellDawson** [comment]
Closed and Reopened this PR to attempt to resolve a specific Travis build failure.

**Review by paulywill — APPROVED** [review]
LGTM!

**Comment by RandellDawson** [comment]
Actually, after testing this locally, it does not make any difference in the display because there is only once space.  If you needed two spaces, then it would have needed either `  &nbsp;` or ` &nbsp; &nbsp;`

**Review by ezioda004 — COMMENTED** [review]
Hi @deveshp,

Thank you for opening this PR. 
You said the PR is suppose to be consistent with the style guide but I cant find where in the [guide](https://github.com/freeCodeCamp/freeCodeCamp/blob/master/docs/style-guide-for-curriculum-challenges.md) it says about having a line break around `<blockquote>` or similar elements.

Hence I'm closing this PR but feel free to open a new one in future.

Happy coding!

**Pull request closed without merging**
