### PR TITLE
recursion

### PR DESCRIPTION
**Pull request by 0x1h0b**
i believe that once we know function we should introduce a little bit of recursion techniques which nothing but an advancement of function.

- [ ] I have read [freeCodeCamp's contribution guidelines](https://github.com/freeCodeCamp/freeCodeCamp/blob/master/CONTRIBUTING.md).
- [ ] My pull request has a descriptive title (not a vague title like `Update index.md`)
- [ ] My pull request targets the `master` branch of freeCodeCamp.
- [ ] None of my changes are plagiarized from another source without proper attribution.
- [ ] My article does not contain shortened URLs or affiliate links.

If your pull request closes a GitHub issue, replace the XXXXX below with the issue number.

Closes #XXXXX

### CODE REVIEW

**Review by CodingSolo — COMMENTED** [review]
Hi,

Please, move your change before notes and  format your article correctly with [Markdown](https://guides.github.com/features/mastering-markdown/) and [the style guide for articles]( freeCodeCamp/docs/style-guide-for-guide-articles.md)

**Preview your change** before you submit a pull request

Thank you

**Review by CodingSolo — CHANGES_REQUESTED** [review]
.

**Comment by paulywill** [comment]
@hb10001 I concur with @CodingSolo... please fix up your PR.

**Comment by paulywill** [comment]
@hb10001 Well done!

IT CROWD

**Pull request merged**
