### PR TITLE
docs(i18n): enable portuguese

### PR DESCRIPTION
**Pull request by naomi-lgbt**
Checklist:

- [X] I have read [freeCodeCamp's contribution guidelines](https://contribute.freecodecamp.org).
- [X] My pull request has a descriptive title (not a vague title like `Update index.md`)
- [X] My pull request targets the `main` branch of freeCodeCamp.
- [X] All the files I changed are in the same world language, for example: only English changes, or only Chinese changes, etc.

Closes #XXXXX

- Adds Portuguese to the translation links
- Enables the Portuguese download in the Crowdin docs workflow (@RandellDawson when you have a chance do you want to take a peek at that?)
- Copies the English files into a Portuguese i18n directory to avoid 404s between the time this lands and the time we run our next docs download.

I've added the appropriate setting on the Crowdin project to map the downloaded files to the correct directory as well.

### CODE REVIEW

**Review by RandellDawson — APPROVED** [review]
The `.github/workflows/crowdin-i18n-docs-download..yml` file looks correct to me.

**Comment by RandellDawson** [comment]
Don't forget to add Portuguese to the Language mapping under `Project settings` before running the first download.

image

**Comment by nhcarrigan** [comment]
I did that... but it didn't stick. Saved it again and now it should be good.

**Comment by RandellDawson** [comment]
> I did that... but it didn't stick. Saved it again and now it should be good.

It is set up now.

**Pull request merged**
