### PR TITLE
fix(Client): Use `font-display: swap` to avoid FOIT

### PR DESCRIPTION
**Pull request by Twaha-Rahman**
Checklist:

- [x] I have read [freeCodeCamp's contribution guidelines](https://contribute.freecodecamp.org).
- [x] My pull request has a descriptive title (not a vague title like `Update index.md`)
- [x] My pull request targets the `master` branch of freeCodeCamp.
- [x] All the files I changed are in the same world language, for example: only English changes, or only Chinese changes, etc.

Currently while the fonts load, the website has shows no text. This know as _FOIT_ and is bad practice as users with slower internet speed has to wait a lot of seconds before they can event see any text. This PR fixes this issue.

For more info: https://web.dev/font-display/?utm_source=lighthouse&utm_medium=ci

### CODE REVIEW

**Comment by ahmadabdolsaheb** [comment]
So `swap` would lead to FOUT where the fonts are loaded as they become available and it leads to a flash for browsers with medium speed. (fast 3g)

@ojeytonwilliams, any preference?

**Comment by Twaha-Rahman** [comment]
Here's the explanation from the article -

> `swap` tells the browser that text using the font should be displayed immediately using a system font. Once the custom font is ready, it replaces the system font.

**Comment by ojeytonwilliams** [comment]
This seems reasonable, but how about going with `fallback` instead?  That seems like it would be a nicer user experience - what do you think?

**Comment by Twaha-Rahman** [comment]
> This seems reasonable, but how about going with `fallback` instead? That seems like it would be a nicer user experience - what do you think?

@ojeytonwilliams Sure. Updated PR.

**Comment by ojeytonwilliams** [comment]
I should clarify: it seemed slightly better to me, but I only learned of the feature today!  There may be some reason to prefer `swap` that I'm unaware of.  @ahmadabdolsaheb any ideas?

**Comment by Twaha-Rahman** [comment]
AFAIK `swap` is generally used with `font-display`. Google (and a LOT of other articles) recommends to use `swap`. The article I posted in the first message is the blogpost by Google Lighthouse devs and they recommend `swap`.

So I think `swap` should be the way to go. Any thoughts?

**Review by ojeytonwilliams — APPROVED** [review]
I came across [this](https://developers.google.com/web/updates/2016/02/font-display#swap) which discusses use cases for both.  The gist being: if it's important that it eventually renders correctly, use `swap` (i.e. if it's a logo), otherwise `fallback` is probably better.

Presumably the optimal approach is to use both, depending on the context, but I'll defer to Ahmad on this one.

**Comment by ahmadabdolsaheb** [comment]
I don't think you can go wrong with either of these.

**Pull request merged**
