### PR TITLE
fix: rwd beta - ferris wheel step 1 html test

### LINKED ISSUE #44623: RWD Ferris Wheel Step 1
## Affected page

https://www.freecodecamp.org/learn/2022/responsive-web-design/learn-css-animation-by-building-a-ferris-wheel/step-1

## Your code

```
<!DOCTYPE html>

<html>
  <head>
    <meta charset="UTF-8" />
    <link rel="stylesheet" href="./styles.css" />
    <title>CSS Ferris Wheel</title>
  </head>
  <body></body>
</html>

```

## Expected behavior

Tests return error: 
Your html element should be below the DOCTYPE declaration

## System

- Device: [Desktop]
- OS: [EndeavorOS (Arch Linux)]
- Browser: [chrome]
- Version: [96.0.4664.110 (Official Build) (64-bit)]

### PR DESCRIPTION
**Pull request by bbsmooth**
Checklist:

- [x] I have read [freeCodeCamp's contribution guidelines](https://contribute.freecodecamp.org).
- [x] My pull request has a descriptive title (not a vague title like `Update index.md`)
- [x] My pull request targets the `main` branch of freeCodeCamp.
- [x] I have tested these changes locally on my machine.

Closes #44623

Just needed the 'm' flag to handle mulitline.

### CODE REVIEW

**Comment by bbsmooth** [comment]
Hmm, you know what, after thinking about this a little more, the 'm' flag may not be the best option. I might have jumped the gun a little here.

**Comment by bbsmooth** [comment]
OK, I think I figured out what is causing this issue. The code string that is being passed into the match has comments at the beginning:
```
/*fcc*/

/*fcc*/
<!DOCTYPE html>

<html>
  <head>
    <meta charset="UTF-8" />
    <link rel="stylesheet" href="./styles.css" />
    <title>CSS Ferris Wheel</title>
  </head>
  <body></body>
</html>
```

So using the caret to anchor this particular match to the beginning of the string is going fail:

```
assert(code.match(/^\s*<!DOCTYPE\s+html\s*>[\s\S]*<\s*html\s*>/gi));
```

Removing the caret seems to solve this particular problem, but the match itself still doesn't enforce the condition that the `html` tag should be below the `DOCTYPE` since the regex is using `[\s\S]*` to separate the tags, which not only doesn't require a newline but also allows any type of gibberish between the two tags.

My first instinct is to replace `[\s\S]*` with `(\r?\n)+` which will force at least one newline between the tags.

**Comment by bbsmooth** [comment]
Question for anyone in the know, why are those comments above the HTML there? Is this expected? Seems like this could cause an issue for other tests as well. I believe it is required to be at the very top of the document so it actually does make sense to use a caret to anchor this match to the beginning of the string.

**Review by gikf — APPROVED** [review]
Changed regex makes test work correctly. :+1:

**Review by ejcheng — APPROVED** [review]
Regex looks good on my end too, good job!

**Review by jdwilkin4 — APPROVED** [review]
LGTM! 👍

**Comment by ShaunSHamilton** [comment]
> Question for anyone in the know, why are those comments above the HTML there? Is this expected? Seems like this could cause an issue for other tests as well. I believe the DOCTYPE is required to be at the very top of the document so it actually does make sense to use a caret to anchor this match to the beginning of the string.

@bbsmooth We have been trying to fix a few issues with the way we insert the user code into the `iframe`. However, we have encountered a, so far, unexplained bug: https://github.com/freeCodeCamp/freeCodeCamp/pull/42195

**Pull request merged**
