### PR TITLE
Closed input field in example

### LINKED ISSUE #1067: Misleading note in waypoint create a text field
I wasn't sure if this one was going too far but figured I would throw it open for discussion.

In lesson http://www.freecodecamp.com/challenges/waypoint-create-a-text-field it says:

    You can create one like this: <input type='text'>. Note that input elements are self-closing.

Thats not a self closing tag which would look like `<input type='text' />` but this isn't valid html5.

To be technically accurate the note should say input elements are void elements which don't have an end tag (or probably just keep it simple and say they don't have an end tag).

I did [some research](http://stackoverflow.com/a/5047150/156388) and it seems that the spec says web browsers should tolerate it content authors shouldn't use them.

### PR DESCRIPTION
**Pull request by AryanJ-NYC**

### CODE REVIEW

**Comment by bugron** [comment]
@AryanJ-NYC actually in HTML5 it is not strictly necessary to close this HTML tag.

**Comment by AryanJ-NYC** [comment]
I understand that. However, @benschenker recommended we put a closing tag anyway to avoid any confusion.  The thread is at #1067.  I just created this pull request to close that issue with the edit that was suggested.

**Comment by bugron** [comment]
@AryanJ-NYC a few days ago a camper opened an issue and he was confused that there was a closing `/` in `img` tag. Unfortunately I can't remember what challenge he was talking about.

**Comment by AryanJ-NYC** [comment]
Then the PR will be declined if it's unwanted. It will be accepted if it's wanted. No harm done in creating one.

**Comment by bugron** [comment]
@AryanJ-NYC I agree with you.
P.S. I've found that issue https://github.com/FreeCodeCamp/FreeCodeCamp/issues/3024.

**Comment by BerkeleyTrue** [comment]
closing are `img` tags do not need to be closed.

@AryanJ-NYC Thanks for the PR!

**Pull request closed without merging**
