### PR TITLE
fix(curriculum): remove unnecessary class instruction

### LINKED ISSUE #51541: Remove class example for step 6 of css box model project
### Describe the Issue

For [step 6](https://www.freecodecamp.org/learn/2022/responsive-web-design/learn-the-css-box-model-by-building-a-rothko-painting/step-6) of the box model project, the third sentence shows an example of how to add a class to a div.

```
For example, <div class="my-div">.
```
But at this point, the camper will have already built 4 practice projects and 1 certification project before getting to this step.
They will have had plenty of practice to add classes between the colored markers project and cafe menu.
Plus I haven't seen anyone on the forum struggling with this step. 
So I don't think we need to add this third sentence at all

## Proposed new text

Add a `div` element in the `body` and set the `class` attribute equal to `canvas`. 

This will act as the canvas for your painting.

### Affected Page

https://www.freecodecamp.org/learn/2022/responsive-web-design/learn-the-css-box-model-by-building-a-rothko-painting/step-6

### PR DESCRIPTION
**Pull request by Gauravkumar1502**
Checklist:

- [x] I have read and followed the [contribution guidelines](https://contribute.freecodecamp.org).
- [x] I have read and followed the [how to open a pull request guide](https://contribute.freecodecamp.org/#/how-to-open-a-pull-request).
- [x] My pull request targets the `main` branch of freeCodeCamp.
- [x] I have tested these changes either locally on my machine, or GitPod.

Closes #51541 

remove unnecessary adding class instruction for step 6 of CSS box model.

### CODE REVIEW

**Review by gikf — CHANGES_REQUESTED** [review]
Hey @Gauravkumar1502,

please remove changes to non-English files. Changes in translations will be handled using translation workflow, they shouldn't be edited directly.

**Review by gikf — APPROVED** [review]
LGTM :+1:

**Comment by Gauravkumar1502** [comment]
@gikf 
Thank-you🙏 for approving my first pull request! FreeCodeCamp taught me how to code and contribute to open source, and this moment means a lot. Excited to continue my open-source journey and collaborate with amazing developers like you.🧑‍💻

**Review by moT01 — APPROVED** [review]
LGTM @Gauravkumar1502 🎉 Congratulations on your first contribution to the freeCodeCamp repo 🎉

**Pull request merged**
