### PR TITLE
fix(curriculum): augment test for adding tracks property

### LINKED ISSUE #45409: Record Collection - Buggy Test
## Affected page

https://www.freecodecamp.org/learn/javascript-algorithms-and-data-structures/basic-javascript/record-collection

## Your code

This code passes when it should not:

```javascript
function updateRecords(records, id, prop, value) {
  if (value === "") {
    delete records[id][prop];
  } else if (prop === "tracks") {
    if (!records[id][prop]) {
      // Good:
      // records[id][prop] = [];
      // Bad:
      records[id][prop] = ["this array is not empty"];
    }
    records[id][prop].push(value);
  } else {
    records[id][prop] = value;
  }
  return records;
}
```

## Expected behavior

The instructions say

>If prop is tracks but the album doesn't have a tracks property, create an empty array and add value to it.

But we don't check that the user adds an empty array.

This test

>After updateRecords(recordCollection, 5439, "tracks", "Take a Chance on Me"), tracks should have the string Take a Chance on Me as the last element.

should be updated to verify

> After updateRecords(recordCollection, 5439, "tracks", "Take a Chance on Me"), tracks should have the string Take a Chance on Me as the **only** element.

That would involve adding a check to verify that the tracks array is only length 1.

### PR DESCRIPTION
**Pull request by kai-wei-mo**
Checklist:

- [x] I have read [freeCodeCamp's contribution guidelines](https://contribute.freecodecamp.org).
- [x] My pull request has a descriptive title (not a vague title like `Update index.md`)
- [x] My pull request targets the `main` branch of freeCodeCamp.
- [x] I have tested these changes either locally on my machine, or GitPod.

Closes #45409

We now test that the user creates an empty array then adds `value` to said empty array, as opposed to allowing the user to stuff the initial array with random data.
image

### CODE REVIEW

**Review by ShaunSHamilton — CHANGES_REQUESTED** [review]
Hello there,

Thank you, for taking the time to contribute.

However, the linked issue has not been triaged yet. So, we have not come to a conclusion as how to resolve the issue.

Issues with the _help wanted_ label are open for contribution.

---

Also, regarding what Camperbot said above:
- You do not need to change any i18n files - solely the `english` file
- The others will automatically be updated

Hope this clarifies

**Review by gikf — APPROVED** [review]
Looks good :+1:

**Comment by kai-wei-mo** [comment]
^ Rerequested review to have requested changes be approved and unblock merge

**Review by ShaunSHamilton — APPROVED** [review]
Thank you.
This LGTM 👍

**Comment by ShaunSHamilton** [comment]
Thank you for your contribution to the page! 👍
We are happy to accept these changes, and look forward to future contributions. 🎉

**Pull request merged**
