### PR TITLE
Update "Waypoint: Build Web Apps with Express.js" Exercise List

### PR DESCRIPTION
**Pull request by SaintPeter**
Updated the Build Web Apps exercise list to match the ExpressWorks list.  There are at least 3 new menu items.

Added:
- Static
- Param Pam Pam
- What's in Query

Removed:
- Session and Cookie

### CODE REVIEW

**Comment by SaintPeter** [comment]
image

**Comment by ahstro** [comment]
Sorry, but does the merged commit have anything to do with the title of the PR? Am I just really tired?

**Comment by SaintPeter** [comment]
You're right, the merged commit is for something else entirely.  I may have totally destroyed my fork's Git chain.  I do believe that there was at one point a commit that addressed the title.

**Comment by ahstro** [comment]
They ended up in #1368, which was closed for some reason.

**Pull request merged**
