### PR TITLE
Fix error toast not display when JavaScript syntax error

### LINKED ISSUE #11198: err-saga.js causes problems when syntax errors are caught
When a syntax error is caught, `err-saga.js` gets as far as [line 5](https://github.com/FreeCodeCamp/FreeCodeCamp/blob/staging/client/sagas/err-saga.js#L5) and stops all processes. 

There is a syntax error message in the dev console

There is no error toast

I can't see anything in `~ /client/commonFramwork/` working eg. `code-storage`, `detect-unsafe-code-stream`, display-test-results` etc...

anim

### PR DESCRIPTION
**Pull request by WiNloSt**
#### Pre-Submission Checklist

- [x] Your pull request targets the `staging` branch of FreeCodeCamp.
- [x] Branch starts with either `fix/`, `feature/`, or `translate/` (e.g. `fix/signin-issue`)
- [x] You have only one commit (if not, [squash](http://forum.freecodecamp.com/t/how-to-squash-multiple-commits-into-one-with-git/13231) them into one commit).
- [x] All new and existing tests pass the command `npm run test-challenges`. Use `git commit --amend` to amend any fixes.
#### Type of Change

- [x] Small bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds new functionality)
- [ ] Breaking change (fix or feature that would change existing functionality)
- [ ] Add new translation (feature adding new translations)
#### Checklist:

- [x] Tested changes locally.
- [x] Closes currently open issue (replace XXXX with an issue no): Closes #XXXX
#### Description

In [/client/saga/err-saga.js#7](https://github.com/FreeCodeCamp/FreeCodeCamp/blob/staging/client/sagas/err-saga.js#L7), the dispatched action has type `app.makeToast` but there is no this type name in the project. I looked into [/common/app/redux/types.js](https://github.com/FreeCodeCamp/FreeCodeCamp/blob/staging/common/app/redux/types.js) which contains all the action types with prefix `app`, and `makeToast` is no where to be found. So I use the action creator from [/common/app/toasts/redux/actions.js](https://github.com/FreeCodeCamp/FreeCodeCamp/blob/staging/common/app/toasts/redux/actions.js) instead.

closes #11198

### CODE REVIEW

**Review by ghost — COMMENTED** [review]
The toast is displaying, however, after submitting and entering the next challenge, two of these error toasts pop up:

[https://gyazo.com/1ee0ee8c610086a13edf60a5eefc2726](https://gyazo.com/1ee0ee8c610086a13edf60a5eefc2726)

**Comment by WiNloSt** [comment]
Oh snap! I didn't test that. I'll try tracking those errors down. But one thing I know for sure is that `err-saga.js` now dispatch a correct action, so any action that has a key `error` that was dispatched will now cause the error toast to popup i.e. These 2 errors were there originally, but they just didn't show the error toasts.

To be honest, I'm not entirely sure if an error is handle by the middleware or is handle in a handler and then fire an action containing an `error` key. I'll need more time to investigate, hopefully I'll come up with something in a couple of days.

**Comment by BerkeleyTrue** [comment]
This code looks good and works. @atjonathan I think your issue has to do with a redux storage system I implement. It tends to keep the csrf token around between sessions during development. 

@WiNloSt Thanks so much. Happy Coding!

**Comment by aaryanrathi** [comment]
Hello world

**Comment by BerkeleyTrue** [comment]
@aaryanrathi Please use the [chat](https://gitter.im/FreeCodeCamp/FreeCodeCamp) rooms to introduce yourself. The issue tracker is for reporting issues only.

**Pull request merged**
