### PR TITLE
fix(curriculum): "Get JSON with the JavaScript fetch method" Test Too Specific

### LINKED ISSUE #41750: "Get JSON with the JavaScript fetch method" Test Too Specific
Challenge Page: https://www.freecodecamp.org/learn/data-visualization/json-apis-and-ajax/get-json-with-the-javascript-fetch-method
File: https://github.com/freeCodeCamp/freeCodeCamp/blob/main/curriculum/challenges/english/04-data-visualization/json-apis-and-ajax/get-json-with-the-javascript-fetch-method.md

Code which passes:
```
      // Add your code below this line
      fetch('/json/cats.json')
        .then(response => response.json())
        .then(data => {
          document.getElementById('message').innerHTML = JSON.stringify(data);
        })
      // Add your code above this line
```
Code which fails:
```
      // Add your code below this line
      fetch('/json/cats.json')
        .then(response => response.json())
        .then(x => {
          document.getElementById('message').innerHTML = JSON.stringify(x);
        })
      // Add your code above this line
```

The test should not rely on the variable name.

Suggestion for 3rd test:
```
assert(__helpers.removeWhiteSpace(code).match(/\.then\(\(?\w+\)?=>{[^}]*}\)/g));
```

---

An issue with the _help wanted_ or _first timers only_ label is open for contribution. The first comprehensive PR created will be reviewed and merged. We typically do not assign issues to anyone other than long-time contributors.

If you would like to contribute, and have not read the contributors docs, please do so here: https://contribute.freecodecamp.org/#/

If you have any issues with contributing, be sure to join us on the [contributors channel](https://chat.freecodecamp.org/channel/contributors), or on the [contributors sub-forum](https://forum.freecodecamp.org/c/contributors/3)

### PR DESCRIPTION
**Pull request by jonathankerr**
- Tested locally
- Tests were too specific and relied on the variable name `data`
- Changed the final two tests to allow `data` to be renamed in the solution
- Closes issue:  #41750

Checklist:

- [x] I have read [freeCodeCamp's contribution guidelines](https://contribute.freecodecamp.org).
- [x] My pull request has a descriptive title (not a vague title like `Update index.md`)
- [x] My pull request targets the `main` branch of freeCodeCamp.
- [x] All the files I changed are in the same world language, for example: only English changes, or only Chinese changes, etc.

Closes #41750

### CODE REVIEW

**Review by ShaunSHamilton — APPROVED** [review]
This LGTM 👍 

Thank you, for opening this PR.
This challenge is easy to pass with incorrect code, but without testing for the specific data, I am happy with this.

**Comment by jonathankerr** [comment]
> 
> 
> This LGTM 👍
> 
> Thank you, for opening this PR.
> This challenge is easy to pass with incorrect code, but without testing for the specific data, I am happy with this.

Thanks for the feedback appreciate it!

**Review by gikf — APPROVED** [review]
Changes looks good :+1:

**Comment by gikf** [comment]
Hi @jonathankerr. Congrats on your first pull request (PR)! 🎉

Thank you for your contribution to the page! 👍
We are happy to accept these changes and look forward to future contributions. 📝

**Pull request merged**
