### PR TITLE
chore: enabled `MD040` lint rule

### PR DESCRIPTION
**Pull request by k-rajat19**
Checklist:

- [x] I have read [freeCodeCamp's contribution guidelines](https://contribute.freecodecamp.org).
- [x] My pull request has a descriptive title (not a vague title like `Update index.md`)
- [x] My pull request targets the `main` branch of freeCodeCamp.
- [x] I have tested these changes either locally on my machine, or GitPod.

same as in the title

### CODE REVIEW

**Comment by ieahleen** [comment]
hey there, can you expand on why you are doing this change?

**Comment by k-rajat19** [comment]
> hey there, can you expand on why you are doing this change?

If I'm getting it right, we should [enable](https://github.com/freeCodeCamp/freeCodeCamp/blob/main/curriculum/challenges/.markdownlint.yaml#L8) this option now
however, some fenced code blocks still don't have a language specified so I've fixed it in this [commit](https://github.com/freeCodeCamp/freeCodeCamp/pull/47853/commits/c493b2256373f1eb5e91bcdab027b0db3c7a52e1)

**Comment by ieahleen** [comment]
GitHub is having issues, but if you run the command locally you will see the linter results

**Comment by k-rajat19** [comment]
@ieahleen  this PR is ready for review now

**Review by majestic-owl448 — APPROVED** [review]
Thank you for your PR!

That's one less TODO in the codebase :)

**Review by raisedadead — APPROVED** [review]

**Pull request merged**
