### PR TITLE
fix: use rimraf instead of shx

### PR DESCRIPTION
**Pull request by raisedadead**
This PR swaps `shx` for `rimraf` because the latter is doing what we are using shx for, primarily for the `rm -rf` commands during cleanup. Also, before this change, the npm run-script for `clean:packages` actually never worked, i.e., it did not do anything with the wild card search.

### CODE REVIEW

**Review by naomi-lgbt — APPROVED** [review]
Looks good to me.

Worth noting that `rimraf` is about 50% slower than `rm -rf` is.

**Comment by raisedadead** [comment]
> Worth noting that `rimraf` is about 50% slower than `rm -rf` is.

Agreed. This workaround only keeps supporting (unofficially) people building on Windows natively.

**Comment by nhcarrigan** [comment]
At the risk of bikeshedding...

Would it be preferable to use `rm -rf` directly and add a note to the contributing docs that folks who are absolutely stuck on a native windows environment can use something like GitBash?

**Comment by raisedadead** [comment]
I am in favor as long as we have a few others from the @freeCodeCamp/moderators onboard

**Comment by thecodingaviator** [comment]
> At the risk of bikeshedding...
> 
> Would it be preferable to use `rm -rf` directly and add a note to the contributing docs that folks who are absolutely stuck on a native windows environment can use something like GitBash?

This sounds good to me. I can create an issue once more people chime in

**Comment by ieahleen** [comment]
> Would it be preferable to use `rm -rf` directly and add a note to the contributing docs that folks who are absolutely stuck on a native windows environment can use something like GitBash?

I support this

**Review by Sembauke — APPROVED** [review]

**Comment by ojeytonwilliams** [comment]
Did someone say bikeshedding?  

I'd prefer to use rimraf since, even if it's slower, cleaning isn't something you need to do often. Also, it takes all of 9 seconds on my machine.  

Also I'm not keen on adding to the docs unless we have to.  They're already big enough that new contributors are unlikely to read them.

**Review by ojeytonwilliams — APPROVED** [review]

**Comment by raisedadead** [comment]
If we talk stats, users building natively on Windows are even fewer. 

Cleaning is a crucial step during the deployments we do currently (hence I needed to create the PR in the first place). See https://dev.azure.com/freeCodeCamp-org/freeCodeCamp/_releaseDefinition?definitionId=13&_a=definition-tasks&environmentId=43

**Comment by ojeytonwilliams** [comment]
Right, but rimraf is required by ~20 other dependencies, so it's not going anywhere.

I'd forgotten cleaning was part of the deployment, thanks for reminding me!  Still, I think it's fine to use rimraf.  After all, it's basically the same. Also, the containers are on the horizon and they will render the deployment concerns moot.

**Comment by raisedadead** [comment]
> ...they will render the deployment concerns moot.

Actually, the deps are the problem. The image sizes are terribly large for the API, but someone said this thread is not about bike shedding.

**Comment by ojeytonwilliams** [comment]
Pretty sure this thread is for bikeshedding now :)

I'll take a look at the api images, though.

**Pull request merged**
