### PR TITLE
feat(curriculum): adding 1st review project for JS cert

### PR DESCRIPTION
**Pull request by jdwilkin4**
## Summary of changes
As discussed in the meetings, we are going to add small review projects between each of the learn projects.
This will give campers the ability to practice more of what they learned and build functions on their own.

This JS only project reviews the following:
- basic functions
- string concatenation
- loops
- comparison operators
- booleans
- conditionals

Checklist:

- [x] I have read and followed the [contribution guidelines](https://contribute.freecodecamp.org).
- [x] I have read and followed the [how to open a pull request guide](https://contribute.freecodecamp.org/#/how-to-open-a-pull-request).
- [x] My pull request targets the `main` branch of freeCodeCamp.
- [x] I have tested these changes either locally on my machine, or GitPod.

### CODE REVIEW

**Comment by jdwilkin4** [comment]
hmmm....the tests don't seem to like the updated order.
Will look into it tomorrow

**Review by naomi-lgbt — COMMENTED** [review]
I wonder if, given the amount of text, it would be better to have this use the old layout.

**Comment by jdwilkin4** [comment]
It looks like all js challenges will be challenge type 1 based on this PR here. So I updated the challenge type in my PR.
https://github.com/freeCodeCamp/freeCodeCamp/pull/54438

once that PR is merged then I pull in those latest changes

**Review by naomi-lgbt — APPROVED** [review]
Solved all of these with one-liners. Tests are great!

**Review by a2937 — APPROVED** [review]
Looks Good To Me! 👍

**Pull request merged**
