### PR TITLE
fix: stop multiple prettier runs on large commits

### PR DESCRIPTION
**Pull request by ojeytonwilliams**
This works around https://github.com/okonet/lint-staged/issues/925

### CODE REVIEW

**Review by naomi-lgbt — APPROVED** [review]
Is this why the pre-commit hook takes forever sometimes? 😓 

LGTM.

**Review by dakgk — APPROVED** [review]

**Comment by ojeytonwilliams** [comment]
> Is this why the pre-commit hook takes forever sometimes? :sweat:

Yes. I'm really sorry, I only realised it was an issue when @Sembauke  mentioned it today.

**Review by ShaunSHamilton — APPROVED** [review]
This seems GLTM 👍 

Although, I probably would have just set `completedStages.add('eg')` for any linting - not just when all files are linterised.

**Comment by ojeytonwilliams** [comment]
> Although, I probably would have just set completedStages.add('eg') for any linting - not just when all files are linterised.

I think it's safer this way, because the chunking algorithm isn't part of the public api.  So, we don't know how big a chunk is.

If we always added a completed stage, and the chunks were less than 10 files, then we'd bail before all files had been linted.  Not that this is a *huge* deal (or likely), but we can easily avoid it.

**Pull request merged**
