### PR TITLE
Added new "touch" command

### PR DESCRIPTION
**Pull request by amitech**
Added new useful touch command used for modifying timestamps

- [x] I have read [freeCodeCamp's contribution guidelines](https://github.com/freeCodeCamp/freeCodeCamp/blob/master/CONTRIBUTING.md).
- [x] My pull request has a descriptive title (not a vague title like `Update index.md`)
- [x] My pull request targets the `master` branch of freeCodeCamp.
- [x] None of my changes are plagiarized from another source without proper attribution.
- [x] My article does not contain shortened URLs or affiliate links.

If your pull request closes a GitHub issue, replace the XXXXX below with the issue number.

Closes #XXXXX

### CODE REVIEW

**Comment by lynxlynxlynx** [comment]
Please fix the grammar. Note that touch is not a builtin bash command or in other words, it works also in other shells, so the title isn't fitting.

**Comment by QuincyLarson** [comment]
@amitech Awesome! Thanks for writing this.

@lynxlynxlynx I went ahead and merged this. Once we've moved the Guide folder over to its new location, could you open a follow-up PR with your grammar improvements?

**Comment by lynxlynxlynx** [comment]
No. I think this duplication of effort is a waste of everyone's time, but this PR also isn't the place to talk about that.

**Comment by amitech** [comment]
@QuincyLarson @lynxlynxlynx I will fix grammatically error.

**Pull request merged**
