### PR TITLE
test(challenges): Correct test case regular expression

### LINKED ISSUE #17387: Debugging - Understanding the Differences between the freeCodeCamp and Browser Console / Firefox bug
#### Describe your problem and - if possible - how to reproduce it
In the JS course, the **Debugging - Understanding the Differences between the freeCodeCamp and Browser Console** lesson doesn't properly evaluate on Firefox, showing `invalid regexp group` in the bottom console. On Chrome, however, it works just fine. The issue has to do with the regexp used to check `console.clear()`.

#### Add a Link to the page with the problem

https://learn.freecodecamp.org/javascript-algorithms-and-data-structures/debugging/understanding-the-differences-between-the-freecodecamp-and-browser-console

#### Tell us about your browser and operating system

* Browser Name: Firefox
* Browser Version: Developer Edition / 61.0b10 (64-bit)
* Operating System: Windows 10

#### If possible, add a screenshot here

fcc

### PR DESCRIPTION
**Pull request by matthew-t-smith**
Changed regular expression in testString that was giving error on
challenge

BREAKING CHANGE: n/a

Closes #17387

#### Pre-Submission Checklist

- [x] Your pull request targets the `staging` branch of freeCodeCamp.
- [x] Branch starts with either `fix/`, `feature/`, or `translate/` (e.g. `fix/signin-issue`)
- [x] You have only one commit (if not, [squash](http://forum.freecodecamp.org/t/how-to-squash-multiple-commits-into-one-with-git/13231) them into one commit).
- [x] All new and existing tests pass the command `npm test`. Use `git commit --amend` to amend any fixes.

#### Type of Change

- [x] Small bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds new functionality)
- [ ] Breaking change (fix or feature that would change existing functionality)
- [ ] Add new translation (feature adding new translations)

#### Checklist:

- [x] Tested changes locally.
- [x] Addressed currently open issue (replace XXXXX with an issue no in next line)

Closes #17387 

#### Description

The third testString for [this challenge](https://learn.freecodecamp.org/javascript-algorithms-and-data-structures/debugging/understanding-the-differences-between-the-freecodecamp-and-browser-console) gave a regular expression error in the challenge, likely because of the negative look behind's compatibility in browsers. Thanks to @scissorsneedfoodtoo for assistance in editing the regular expression to catch user's input of `console.clear()` without the commented version of the text.

### CODE REVIEW

**Comment by scissorsneedfoodtoo** [comment]
@matthew-t-smith, thank you for submitting a PR to fix this issue. Sorry for the delay. We're currently in the process of moving all updates to the curriculum over to a separate repository, so your PR is blocked for now.

I checked it out and everything LGTM! However, since I was the one who suggested some of the regex for this new test, I'd feel more comfortable if another contributor could take a look at it. [Here's](regexr.com/3rcqe) a link to the regular expression used in this test, along with the editor code and solution, over on regexr. Please try to break it and see if it can be improved!

If everything's looks good, then @raisedadead, myself, or any other members will merge things are ready with the new repo.

**Comment by matthew-t-smith** [comment]
@scissorsneedfoodtoo  I had played with that regex a bit before submitting previously, and I think it holds up. If we want to go back to the look behind once it has been fully integrated into Firefox, I don't see any issue there either. Again, I appreciate the help, but let me know if you need anything more from me on this one.

**Comment by scissorsneedfoodtoo** [comment]
@matthew-t-smith, thanks for confirming that it works! In that case, I think all we need to do is wait for the go ahead to merge this and cherry-pick your commit over to the new curriculum repo where the challenge seed files will be hosted from now on.

**Comment by matthew-t-smith** [comment]
Party - this is the last thing between me and my first certificate.

**Comment by raisedadead** [comment]
Hi @matthew-t-smith 

Thanks a lot for this pull request. We sincerely appreciate the time and efforts put into this. 

However can you please make the same changes once again on the https://github.com/freeCodeCamp/curriculum repository?

I would like to apologise for the inconvenience, but at this point it has become very difficult to carry over commits into the other repo, to which we have moved over the entire curriculum package.

Thanks once again. 

Please reach out to us in the [Contributors Chat room](https://gitter.im/FreeCodeCamp/Contributors) for any assistance.

Happy contributing!

**Pull request closed without merging**
