### PR TITLE
Typo fix on 'set-up-a-template-engine.english.md'

### PR DESCRIPTION
**Pull request by darren-stoll**
Checklist:

- [x] I have read [freeCodeCamp's contribution guidelines](https://contribute.freecodecamp.org).
- [x] My pull request has a descriptive title (not a vague title like `Update index.md`)
- [x] My pull request targets the `master` branch of freeCodeCamp.
- [x] All the files I changed are in the same world language, for example: only English changes, or only Chinese changes, etc.

Closes #XXXXX

### CODE REVIEW

**Review by naomi-lgbt — APPROVED** [review]
LGTM! Congratulations on your first pull request! 🥳 

A quick note: Our workflow will require one additional approving review before it can be merged. 

As an aside, should `"view engine"` be bold there? 🤔

**Review by ShaunSHamilton — APPROVED** [review]
LGTM :thumbsup: 

@nhcarrigan As for it being in bold: we will hopefully get some concensus on this in the opened issue.

**Comment by Sky020** [comment]
Thank you, @darren-stoll for your contribution, and congrats on your first PR!

We are happy to accept these changes, and look forward to your future contributions.

On a side note: I recommend you look to the contributors docs concerning more standard PR titles, as well as commit messages.

**Comment by RandellDawson** [comment]
Just seeing this one now.  All of the words in bold should really have really been in `code` tags.

**Pull request merged**
