### PR TITLE
Fix/update challenges for sass

### LINKED ISSUE #34743: Possible Typo in "SASS Challenge: Use @if and @else to Add Logic to your Styles"
**Issue Description**
Following the given instructions. The test will fail for the @else 
`  @mixin border-stroke($val) { 
  @if $val === light { border: 1px solid black; 
                      }
@else if $val === medium { border: 3px solid black; 
                          }
@else if $val === heavy { border: 6px solid black; 
                          }
@else { border: none; 
      }
}`

The checkmark at the bottom left says: "Your mixin should have an @else statement to set the border to none." and it will pass if using "none" but not "no border" as suggested. 

My suggestion is to replace "no border" from the instructions with "none"

**Link to the page with the problem:**
https://learn.freecodecamp.org/front-end-libraries/sass/use-if-and-else-to-add-logic-to-your-styles

**browser and operating system:**
* Browser Name: Chrome
* Browser Version:  Version 71.0.3578.98 (Official Build) (64-bit)
* Operating System: MacOs Sierra Version 10.12.6

### PR DESCRIPTION
**Pull request by joshiad**
I changed the description of the challenge for sass. It was swapping the words so I made these changes to all world languages. 

- [X] I have read [freeCodeCamp's contribution guidelines](https://github.com/freeCodeCamp/freeCodeCamp/blob/master/CONTRIBUTING.md).
- [X] My pull request has a descriptive title (not a vague title like `Update index.md`)
- [X] My pull request targets the `master` branch of freeCodeCamp.
- [x] None of my changes are plagiarized from another source without proper attribution.
- [x] All the files I changed are in the same world language (for example: only English changes, or only Chinese changes, etc.)
- [X] My changes do not use shortened URLs or affiliate links.

Closes #34743 (Language: English)

### CODE REVIEW

**Comment by RandellDawson** [comment]
@joshiad There are a couple of problems with your PR.  First, there is a reason we have the 5th check mark above.  We have special reviewers for the non-English articles/challenges, so we need to keep them separate so as not to hold up the PR from getting merged due to waiting on 5 other people to review and approve.  Please break this up into 6 PRs to make the review/merge process faster.  In fact, I would suggest just focusing on the English version and once we can agree on the final verbiage, you can create PRs for the other 5 languages.

The other issue has to due with a mistake the original auto-translation which was made on the non-English challenges.  Technically, the word `none` is part of the code, so it should not be translated.  The meaning should be translated.  This means that in each language version, the word `none` should still appear in the applicable position in the text.  You will notice, that some of the languages (Chinese, Portuguese, Spanish were translated by mistake.  Also, I noticed the Arabic version was not included in your PR, so that would possibly need to be changed also.

Another approach which might also make it clearer would be to change the instructions to something like:
```
Create a mixin called border-stroke that takes a parameter $val. The mixin should check for the following conditions using @if, @else if, and @else:
light - 1px solid black
medium - 3px solid black
heavy - 6px solid black

If `$val` is not `light`, `medium`, or `heavy`, the the border should be set to `none`.
```

In the future, it would be best to discuss the verbiage of such a change on the issue and once everyone agrees, then create a PR and reference the issue thread.

**Comment by aditijoshi14** [comment]
Thank you so much for your feedback @RandellDawson. I apologize for the mistakes. In this case, should I create a new PR for different languages or should we change the instruction to the example you gave?

`Create a mixin called border-stroke that takes a parameter $val. The mixin should check for the following conditions using @if, @else if, and @else:
light - 1px solid black
medium - 3px solid black
heavy - 6px solid black

If `$val` is not `light`, `medium`, or `heavy`, the the border should be set to `none`.`

I personally liked the instruction you suggested, which is given above.

**Comment by RandellDawson** [comment]
@aditijoshi14 I would change this PR to only focus on the English version and then once we approve that, you can create separate PRs for the other languages.  Start with what I suggested for the English version and we will see what other reviewers think.  Where you see me use backticks above, use `<code>...</code` instead.  For example, the last sentence would be:
```
If <code>$val</code> is not <code>light</code>, <code>medium</code>, or <code>heavy</code>, the the border should be set to <code>none</code>.
```

**Comment by aditijoshi14** [comment]
@RandellDawson I will start working on creating a separate PR. Regarding my two usernames, I used to have two usernames but I recently transferred all my repository to my personal account. In that case, I will be just using this one from now. Sorry for the confusion.

**Comment by aditijoshi14** [comment]
I made the changes and it looks like this @RandellDawson 

screen shot 2019-02-02 at 10 20 50 am

**Comment by RandellDawson** [comment]
@joshiad I think these changes look good.  Now, just adjust this PR's scope to only change the English PR.  Once we merge the English version, you can create a separate PR for the other languages using Google translate or some other translation software for the changed sections.  That way, one of our translator reviewers can look at those separately.

Thanks again for you contribution!

**Comment by aditijoshi14** [comment]
@RandellDawson Thank you for checking. Do you think I should start working on creating separate PRs for 5 different languages or should I wait until this English version gets merged?

**Review by cmccormack — APPROVED** [review]
Looks good to me, and congratulations on your first Pull Request!  🎉🎉🎉
We look forward to future contributions!

**Comment by RandellDawson** [comment]
@aditijoshi14 Now that the English version has been merged, you should now only translate the parts which were changed/added in this PR for the other ones.  You can use Google translate or another translation site to help you attempt the translations.

Thanks again for all your work!

**Pull request merged**
