### PR TITLE
Add basic blockchain datastructure implementation

### PR DESCRIPTION
**Pull request by trungqudinh**
- [x] I have read [freeCodeCamp's contribution guidelines](https://github.com/freeCodeCamp/freeCodeCamp/blob/master/CONTRIBUTING.md).
- [x] My pull request has a descriptive title (not a vague title like `Update index.md`)
- [x] My pull request targets the `master` branch of freeCodeCamp.
- [x] None of my changes are plagiarized from another source without proper attribution.
- [x] My article does not contain shortened URLs or affiliate links.

If your pull request closes a GitHub issue, replace the XXXXX below with the issue number.

Closes #XXXXX

### CODE REVIEW

**Comment by RandellDawson** [comment]
The code blocks should use 2 space indention.  Also, if you take a look at the [Styling Guide](https://github.com/freeCodeCamp/freeCodeCamp/blob/master/docs/style-guide-for-guide-articles.md#title), you will see you are missing the required title metadata information.  I have reopened your PR, so you can make the changes.

**Comment by trungqudinh** [comment]
Hi, I updated my change. Plz let me know if there's any problem with my commit.
Thanks.

p/s: It seem like i could not edit my commit message and use sth like "--amend" option here, doesn't it?

**Comment by RandellDawson** [comment]
Make sure to click the View button so you can preview your markedown file.  I am still seeing more than 2 space indention.

image

**Comment by trungqudinh** [comment]
i fixed it.
btw, could i have your convention, since in other places people use 4 space to indent.

**Comment by RandellDawson** [comment]
LGTM

**Comment by RandellDawson** [comment]
Hi @trungqudinh. Congrats on your first pull request (PR)! 🎉

Thank you for your contribution to the page! 👍
We're happy to accept these changes, and look forward to future contributions. 📝

**Pull request merged**
