### PR TITLE
Add Twitch.tv pass-trough API link

### PR DESCRIPTION
**Pull request by Em-Ant**
#### Pre-Submission Checklist

- [x] Your pull request targets the `staging` branch of FreeCodeCamp.
- [x] Branch starts with either `fix/`, `feature/`, or `translate/` (e.g. `fix/signin-issue`)
- [x] You have only one commit (if not, [squash](http://forum.freecodecamp.com/t/how-to-squash-multiple-commits-into-one-with-git/13231) them into one commit).
- [x] All new and existing tests pass the command `npm run test-challenges`. Use `git commit --amend` to amend any fixes.
#### Type of Change

- [ ] Small bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds new functionality)
- [ ] Breaking change (fix or feature that would change existing functionality)
- [ ] Add new translation (feature adding new translations)
#### Checklist:

- [x] Tested changes locally.
- [ ] Closes currently open issue (replace XXXX with an issue no): Closes #XXXX
#### Description

Add a link to a HyperDev based API endpoint which tunnels GET requests to the Twitch.tv API. 
In this way we bypass the need of exposing a Client-ID in codepen. See #10740

### CODE REVIEW

**Comment by Em-Ant** [comment]
I think it would be nice if We also update/integrate the forum post that shows how to use the Twitch API http://forum.freecodecamp.com/t/use-the-twitchtv-json-api/19541

**Comment by ltegman** [comment]
I don't know that's I'd put the `UPDATE` part at the beginning of the note since all parts of our curriculum are constantly updating and evolving. Also, I think it might be worth including an example call to the passthrough, just make it clear if it's a straight passthrough and for example you still need the `/kraken/` part of the URL or is that abstracted away in the passthrough?

Overall I like it though as long as this isn't breaking TOS or going to hit up against rate limits.

**Comment by Em-Ant** [comment]
@ltegman, 
* the UPDATE part was already there, I simply changed the workaround method from having an array of hardcoded responses, to a 'clone' of the original API.
* The edited text asks to replace the Twitch API  **base URL** with the proposed new one. According to the twitch documentation the API base URL is `https://api.twitch.tv/kraken` (so no, You dont'need `/kraken`). I can change this part adding more infos.
* I totally agree with You about breaking the TOS or hitting the rate limits. I had a discussion with @QuincyLarson about this ( and I was proposing a different solution...). He said that We should think this as a band-aid fix until we ship the new curriculum, since this challenge is going to be retired. That's also why I left the `UPDATE` paragraph. Besided that the proposed pass-through endpoint has a db cache that stores the requests for 1 hour, to mitigate the risk of hitting the rate limits, and can be switched to serve static data only, in case of complaints.

@ltegman thoughts or other suggestion ?
Thanks.

**Comment by Em-Ant** [comment]
@ltegman I updated the description as you suggested in point 2 for now. Let me know if you want other changes to be applied.

**Review by fooosmar — APPROVED** [review]

**Comment by QuincyLarson** [comment]
@Em-Ant this looks good to me. Note that you'll also need to branch off of backup/master, make this same change, then submit a pull request against backup/master - that way we can deploy this fix to production while we finish preparing the staging branch.

**Comment by Em-Ant** [comment]
@QuincyLarson  I have merge conflicts on backup/master when I try to fetch that branch. How can I solve them ?

**Pull request merged**
