### PR TITLE
chore(deps): react 16 -> 17

### PR DESCRIPTION
**Pull request by ojeytonwilliams**
- chore: update to 17 + smallest changes to plugins
- fix: migrate code for monaco-editor
- fix: install react 17 compatible packages
- fix: set react(DOM) as webpack externals

Checklist:

- [x] I have read and followed the [contribution guidelines](https://contribute.freecodecamp.org).
- [x] I have read and followed the [how to open a pull request guide](https://contribute.freecodecamp.org/#/how-to-open-a-pull-request).
- [x] My pull request targets the `main` branch of freeCodeCamp.
- [x] I have tested these changes either locally on my machine, or GitPod.

Still to do:
- [x] fix the broken client tests
- [x] find out where the upper jaw is hiding

### CODE REVIEW

**Comment by ahmadabdolsaheb** [comment]
Component library works properly.

**Comment by ojeytonwilliams** [comment]
Hey @freeCodeCamp/dev-team a lot of the problems I ran into with this one were caused by npm pulling workspace packages to the root.

With that in mind, I'm going to focus on https://github.com/freeCodeCamp/freeCodeCamp/pull/49293 initially to make sure pnpm meets our needs and, if all goes well, use pnpm here.

@Sembauke if you're working on the elusive upper jaw, don't worry about the pnpm stuff, it should not impact what you're doing.

**Comment by Sboonny** [comment]
Do we need to include [react-test-library](https://github.com/testing-library/react-testing-library) in the updates?

Here its npm package https://www.npmjs.com/package/@testing-library/react

**Comment by ojeytonwilliams** [comment]
@Sboonny not for React 17, no.  We will need to when we move to 18.

**Comment by ojeytonwilliams** [comment]
Hey @bbsmooth, we ran into some issues with the upper jaw during this migration and could use your input.  The problem we have is that we've been unable to get it to render without turning it back from a content widget to an overlay widget.

I know you were originally trying to work with an overlay widget in https://github.com/freeCodeCamp/freeCodeCamp/pull/45803 so I was wondering: do you remember if there was a way to get the desired ordering of DOM elements while still using overlay widgets?

**Comment by bbsmooth** [comment]
> do you remember if there was a way to get the desired ordering of DOM elements while still using overlay widgets?

Looking back at that original PR, I believe that monaco will always place overlay widgets after the textarea (which is what we were initially using for the instructions) and I discovered that the content widget will always be placed before the textarea, which solved the issue of DOM ordering. So I'm tempted to say that monaco does not provide a way for putting an overlay widget before the textarea (at least not one I could find).  

Furthermore, if you look at the resulting DOM you'll see that there is a `.contentWidgets` div above the textarea and an `.overlayWidgets` div below the textarea. You can use the [Listening To Mouse Events playground example](https://microsoft.github.io/monaco-editor/playground.html?source=v0.35.0#example-interacting-with-the-editor-listening-to-mouse-events) to add further content and overlay widgets and you'll see that they are always placed in their respective divs. So now I'm almost certain that the only way to put content before the textarea (using what monaco provides us) is to use a content widget.

I believe my initial fix in that PR was to manually move the textarea (this was before I knew that the content widget was a thing). But you rightly pointed out that that might not be the best solution because we could get bit by an update at a later time and thus I went seeking for a different solution and discovered the content widget. Not necessarily suggesting this would be an appropriate solution for this problem, but it is there if we are willing to take the risk and can't find anything else.

Also, we are also using a content widget to add a "scroll gutter" over the line numbers so that touch users will always have an area they can use to scroll since both the content and overlay widgets steal touch events and thus you can't scroll over them. But I think we should be able to convert that to an overlay widget since DOM order isn't important

**Comment by ojeytonwilliams** [comment]
Alright, I think I understand things a little better now. Cheers, Bruce.

I'm still hopeful that the content widget can be made to work, so I'll keep at it.

**Comment by ojeytonwilliams** [comment]
https://github.com/freeCodeCamp/freeCodeCamp/pull/53410 can be reverted if this goes in and we change the build of React used in testing.

**Pull request closed without merging**
