### PR TITLE
feat: move Repl.it links to first challenge in backend projects

### LINKED ISSUE #41044: boilerplate links for backend challenges has gone missing
the introduction page that was removed had the link to the boilerplate, now those links are not in the curriculum

already a few people that reached that point today have shown confusion

### PR DESCRIPTION
**Pull request by scissorsneedfoodtoo**
Checklist:

- [x] I have read [freeCodeCamp's contribution guidelines](https://contribute.freecodecamp.org).
- [x] My pull request has a descriptive title (not a vague title like `Update index.md`)
- [ ] My pull request targets the `master` branch of freeCodeCamp.
- [x] All the files I changed are in the same world language, for example: only English changes, or only Chinese changes, etc.

Closes #41044 

Because we won't show the introduction pages anymore, this PR reworks the way Repl.it starter links are introduced for the backend challenges.

It also adds another challenge to the MongoDB and Mongoose section to walk learners through setting up a MongoDB Atlas account. While this information could be moved to a forum post instead, including it as another challenge should make it easier to localize.

Just let me know what you all think.

Note: Create a Guide forum post and update the `forumTopicId` field if we decide to go with a new challenge.

### CODE REVIEW

**Comment by RandellDawson** [comment]
@scissorsneedfoodtoo For the new challenge, can we remove the headings?  Maybe make them `<strong>` instead?  Also, could we structure some tests for this challenge step?

**Comment by scissorsneedfoodtoo** [comment]
@RandellDawson, sure, I can start working on that now.

About the tests, I think we can ask that they add their Mongo URI here and check if that exists without exposing any secrets. I'll play around with it and see if I can add a test or two. It may also involve some changes in text for the next challenge.

**Comment by RandellDawson** [comment]
Why not just create a news article for the necessary information and add a link to it and maybe slightly modify the first challenge to avoid a wall of text in a challenge?

**Comment by scissorsneedfoodtoo** [comment]
@RandellDawson, that would work, too. I was just thinking of what would be easier to track and for contributors to translate.

If it's better to go with a News article, I could create one and communicate that with the rest of the team to get it translated.

**Comment by scissorsneedfoodtoo** [comment]
@RandellDawson, this should be ready for review when you have some time.

I moved the instructions to set up MongoDB Atlas over to a News article and removed that new challenge. I also made it so the different options for developing the project (locally by cloning the repo or by using Repl.it) is similar to what we do for the backend projects.

**Comment by scissorsneedfoodtoo** [comment]
@nhcarrigan, could you take a look at this if you get a chance? Please let me know if there's anything else I can do :)

**Review by raisedadead — APPROVED** [review]

**Pull request merged**
