### PR TITLE
Update map.less to fix flash messages

### LINKED ISSUE #8505: On certain views, flash notices are awkwardly placed
Steps to reproduce: Go to a nonexistent challenge like this one: https://www.freecodecamp.com/challenges/dfdsfds

### PR DESCRIPTION
**Pull request by cashhh**
#### Pre-Submission Checklist

- [x] Your pull request targets the `staging` branch of FreeCodeCamp.
- [x] Branch starts with either `fix/`, `feature/`, or `translate/` (e.g. `fix/signin-issue`)
- [x] You have only one commit (if not, [squash](https://github.com/FreeCodeCamp/FreeCodeCamp/wiki/git-rebase#squashing-multiple-commits-into-one) them into one commit).
- [x] All new and existing tests pass the command `npm run test-challenges`. Use `git commit --amend` to amend any fixes.
#### Type of Change

- [x] Small bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds new functionality)
- [ ] Breaking change (fix or feature that would change existing functionality)
- [ ] Add new translation (feature adding new translations)
#### Checklist:

- [x] Tested changes locally.
- [x] Closes currently open issue (e.g. `Closes #XXXX`): Closes #8505 
#### Description

Only one line has been added in the class "flashMessage".
Flash messages should be centered now instead of being offset.

Before:
flashmessagebefore
After:
flashmessageafter

### CODE REVIEW

**Comment by raisedadead** [comment]
Is this the correct place as seen in the screenshot? I think to keep it consistent the message should go to the top of the page below the nav bar as in other pages.

/cc @hallaathrad Can you QA if this is the expected behavior?

**Comment by BerkeleyTrue** [comment]
@raisedadead That is where it is supposed to be on the map page

**Comment by BerkeleyTrue** [comment]
@cashhh Nice work!

**Comment by cashhh** [comment]
@BerkeleyTrue Thanks alot!

**Pull request merged**
