### PR TITLE
Add test cases for Bonfire: Where do I belong

### PR DESCRIPTION
**Pull request by abhisekp**
Checks for proper positioning of element based on proper sorting order.

### CODE REVIEW

**Comment by abhisekp** [comment]
Campers do mistake while sorting Arrays. The additional test cases ensure that the docs are read thoroughly before using `Array.prototype.sort` method.

**Comment by abhisekp** [comment]
@benmcmahon100 will you please look into this PR?

**Comment by benmcmahon100** [comment]
We are changing everything into asserts so if you have the time to change this to use asserts i can merge it.

**Comment by abhisekp** [comment]
@benmcmahon100 I guessed so. Alright. I'll try to and ping back you.

**Comment by abhisekp** [comment]
@benmcmahon100 i've replaced expect with assert. Could you take a look and merge it if it's good enough?

**Comment by benmcmahon100** [comment]
The fifth test doesn't look right

**Comment by abhisekp** [comment]
@benmcmahon100 oh! :worried: 
How can I make such a silly mistake.

**Comment by abhisekp** [comment]
@benmcmahon100 ready for commit, i guess. :+1:

**Pull request merged**
