### PR TITLE
Replaced reference to Angular.js and Agile with React.js and D3.js

### PR DESCRIPTION
**Pull request by alistermada**
Replaced the image on slide 5 of the Waypoint: Learn how Free Code Camp Works. The new picture replaces Angular.js and Agile with React.js and D3.js to match what's shown on FCC's homepage.

New picture: New picture

Old picture: Old picture

### CODE REVIEW

**Comment by navinkumarkg** [comment]
Hi Friends,
I have been receiving mails from this forum from past 2 months. I could
find out that this forum belongs to coding champs.
I am Naveen Kumar from India. I would like to learn professional coding . I
am a UI developer by profession . I am good at my basics but haven't
writtena single piece of code yet. I have wasted my time in reading many
books . I would like to be a student from any one of the code champ who
belongs to this forum . As I am eager to learn , If any one of you
interested in guiding me , I will be thankfull to them from the bottom of
my heart. This is a request . thank you




-- 


*Naveen Kumar K G*  / UI Developer
*Ph : 9844198990 / navinkumar618@gmail.com <navinkumar618@gmail.com>*
*Bangalore.*

**Comment by bugron** [comment]
@alistermada thanks for the PR. Waiting for @FreeCodeCamp/owners to merge.
@navinkumarkg awesome, you can start by registering here: http://freecodecamp.com/ (this if optional, though). After that you can start learnincg by clicking the link "Learn" on the top of the page.

**Comment by navinkumarkg** [comment]
Thank you so much @aresnMelikyan . I feel so happy . I am so unlighted
after you replied bk to my chat . Thank you very much . I hope to see your
guidance every time thank you




-- 


*Naveen Kumar K G*  / UI Developer
*Ph : 9844198990 / navinkumar618@gmail.com <navinkumar618@gmail.com>*
*Bangalore.*

**Comment by bugron** [comment]
Closing this PR as this was a part of the redesign, see [this line](https://github.com/FreeCodeCamp/FreeCodeCamp/blob/7b3e78119da00a1ebd34d94df6686a634256a6b8/seed/challenges/00-getting-started/getting-started.json#L37).
@alistermada thanks for your contribution, though.

**Pull request closed without merging**
