### PR TITLE
Update to Construct JavaScript Objects with Functions

### LINKED ISSUE #4525: Issue with test suite description
Challenge [Waypoint: Construct JavaScript Objects with Functions](http://www.freecodecamp.com/challenges/waypoint-construct-javascript-objects-with-functions#?solution=var%20Car%20%3D%20function()%20%7B%0A%20%20this.wheels%20%3D%204%3B%0A%20%20this.engines%20%3D%201%3B%0A%20%20this.seats%20%3D%201%3B%0A%7D%3B%0A%0Avar%20myCar%20%3D%20new%20Car()%3B%0A%0A%2F%2F%20Only%20change%20code%20below%20this%20line.%0A%0Avar%20MotorBike%20%3D%20function()%20%7B%0A%20%20this.engines%20%3D%201%3B%0A%20%20this.wheels%20%3D%202%3B%0A%20%20this.seats%20%3D%201%3B%0A%7D%3B%0A) has an issue.
User Agent is: <code>Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/46.0.2490.86 Safari/537.36</code>.
Please describe how to reproduce this issue, and include links to screenshots if possible.

My code:
```javascript
var Car = function() {
  this.wheels = 4;
  this.engines = 1;
  this.seats = 1;
};

var myCar = new Car();

// Only change code below this line.

var MotorBike = function() {
  this.engines = 1;
  this.wheels = 2;
  this.seats = 1;
};

```

The user isn't required to instantiate an object of `MotorBike` as `myMotorBike` (like the `Car` example above) to proceed. I would have expected the code below in order to pass:
```javascript
var Car = function() {
  this.wheels = 4;
  this.engines = 1;
  this.seats = 1;
};

var myCar = new Car();

// Only change code below this line.

var MotorBike = function() {
  this.engines = 1;
  this.wheels = 2;
  this.seats = 1;
};

var myMotorBike = new MotorBike();

```

### PR DESCRIPTION
**Pull request by shadowfool**
Fixes #4525 (conforming to FCC commit guidelines.)

Fixes ghosting variable in tail of challenge that allowed user to complete challenge without actually ever initializing the variable myMotorBike. Not sure if this should be left up to the user, but the challenge instructions leaves this a bit ambiguous as it never tells the user to define the variable myMotorBike, this is why I propose we do it for them.  Also the issue in the code made it seem like this was the intention of the original coder.

### CODE REVIEW

**Comment by SaintPeter** [comment]
This looks decent.  I'd like @ltegman's opinion, since he wrote the original.

I do have a couple comments inline.

**Comment by SaintPeter** [comment]
Please either use `git commit --amend` to update this commit, or squash your commits to one with rebase.

**Comment by ltegman** [comment]
My preference would be to actually remove the use of the constructor from the example code and leave the one for myMotorBike in the tail, since we don't talk about actually using the constructor until the next lesson.

**Comment by shadowfool** [comment]
@itegman I actually agree with this, but the point of confusion is in the checks that are shown to the user. The user is shown the hidden myMotorBike but isn't shown it in the coding area. So either the checks should be against MotorBike, or I think the user needs to be able to see the myMotorBike variable in the code. Let me know your thoughts. 

mymotorbike

**Comment by ltegman** [comment]
I'd say if we're both in agreement that constructing the object is confusing in this lesson then remove the object construction altogether and change the tests to test against the constructor instead of an instance.

**Comment by SaintPeter** [comment]
The tests already do that.  I think just moving the constructor to the `tail` section should be sufficient.

Then remove the `// code only above this line`.

**Comment by ltegman** [comment]
True enough that they're testing against the constructor, but the text says they're testing an instance that isn't visible to the student, so that might be a bit confusing.

**Comment by SaintPeter** [comment]
ok, so:
1) Move the instance to the `tail` (for display purposes only)
2) Change all of the test text to read relative to the constructor, not the instance.

**Comment by ltegman** [comment]
3) remove construction of the instance for the Car constructor (since using constructors isn't broached in this lesson)

**Comment by bugron** [comment]
@shadowfool what's your progress on this PR?

**Comment by shadowfool** [comment]
Been traveling for a few weeks now and haven't had a chance to update from my primary computer. Feel free to create a pull to fix this, not sure when I'll be back.

Aaron

**Comment by SaintPeter** [comment]
@ltegman Want to take this one?

**Comment by ltegman** [comment]
Superseded by #4880

**Pull request closed without merging**
