### PR TITLE
Feat: hide blocks not challenges

### PR DESCRIPTION
**Pull request by ojeytonwilliams**
`SHOW_HIDDEN` is replaced with `SHOW_UPCOMING_CHANGES` for clarity.

`isHidden` is removed entirely, because we no longer wish to hide individual challenges.

`"isUpcomingChange": true/false` is now a required part of every `meta.json` so that someone adding a block has to decide if it is included in production or not.

### CODE REVIEW

**Comment by raisedadead** [comment]
Can you update the battle-plan?

**Comment by ojeytonwilliams** [comment]
I've removed the Chinese changes for now, to avoid creating unnecessary conflicts.

**Review by RandellDawson — DISMISSED** [review]
Works as designed.  I can add `isHidden: true` to a block's `meta.json` and as long as `SHOW_HIDDEN` is not true in the .env, it will not show the entire block.

**Comment by RandellDawson** [comment]
@raisedadead I was wondering why we have an extra SHOW_HIDDEN environment variable where Oliver checks the following:
```js
if (!isHidden || process.env.SHOW_HIDDEN === 'true') {
```
I asked him why we could not just use:
```js
if (!isHidden || process.env.FREECODECAMP_NODE_ENV === 'development') {
```
since it is only production we don't want to show the ones with isHidden: true

He said that was a good question for you.  There maybe a good reason to have an extra environment variable, but it was not obvious to me at first glance. Oliver also said, it seems reasonable, since we have DEPLOYMENT_ENV, for showing them in staging.

**Comment by raisedadead** [comment]
I have gone over this with Oliver a few times which led to the #39443 

Here is the long explanation for everyones benefit:

`FREECODECAMP_NODE_ENV` synonymous to the standard `NODE_ENV`. It is used to identify an environment and enable/disable certain things at **build time**.

`DEPLOYMENT_ENV` is used to differentiate between **run time** configs, keys, API endpoints. These enable/disable dynamic behaviour.

Examples:

`production-staging` and `production-current` are both production build targets. They need to very close and similar to each other to avoid surprises between them during builds and eventual deployments. `FREECODECAMP_NODE_ENV` is the `production-*` part of this in simple terms.

`production-staging` and `production-current` are dynamically different from each other even the builds are similar. They both have similar setups but things dynamic things like auth, donation payment gateways run on alternate instances. `DEPLOYMENT_ENV` is the "-staging" and the "-current" part in this case.

Keeping the value of `FREECODECAMP_NODE_ENV` same and `DEPLOYMENT_ENV` different we are able to generate the same build artifacts (JS binaries) in both cases while keeping the execution context seprate.

Now, lets circle to the `SHOW_HIDDEN` flag.

`SHOW_HIDDEN` is a variable that you are able to use when working locally, especially on `next-*` branches. This is where we are building upcoming features and curicular content. Because only a few people are working on features, its pointless to build all challenges locally for everyone. Having the flag lets keep the code on the `master` without deploying it anywhere.

Can we reuse one of the available flags we discussed earlier? Probably yes. 

But if you look closely its not a good idea. You may be needing to build and test the codebase locally to debug and understand issues on the live platforms. This requires us to isolate away any features that are present in the code but not deployed at all.

Another use of this third variable by extension is, we can temporarily test out the challenges in a staging deployement. We did this in the past when we were testing the python curriculum before going live.

We want to be able to revert back to the production and staging parity after doing temporary deployements.

**Going forward:**

However I can see that this causing a bit of confusion. I admit the naming convention for these three have not been the best. For instance in our last meeting I proposed that we could use the `SHOW_HIDDEN` var to disable UI features (editor) being developed in the `next-*` branches. This is a new need that we had not thought of before.

So here is the new naming convention for these variables that I propose now:

`FREECODECAMP_NODE_ENV` should now be renamed to `BUILD_ENV`
`DEPLOYMENT_ENV` should be left as is and
`SHOW_HIDDEN` should be renamed to `SHOW_UPCOMING_CHANGES` ("Show" signifing explicit opt-in by the dev to build / test / work on new things)

**Comment by ojeytonwilliams** [comment]
> SHOW_HIDDEN should be renamed to SHOW_UPCOMING_CHANGES ("Show" signifing explicit opt-in by the dev to build / test / work on new things)

So, what do you think about the following: 

- It should be impossible to accidentally release a block or a cert

It's a bit of a pain, but we should require the meta json to have the `isHidden` key rather than defaulting to `false`.

- Unless you're working on upcoming content it should be invisible

So, `SHOW_UPCOMING_CHANGES` would be false by default

**Comment by ojeytonwilliams** [comment]
I'm less convinced about the following, but I figure it's worth talking about:

- There should be e2e tests that confirm specific things that should be in production are there (like the current suite of certs) and that upcoming features are not

That would help make sure people don't accidentally release content while it's still in the testing phase.

- There should be another set of e2e tests that confirm the upcoming changes behave as expected

If we tied the tests to `SHOW_UPCOMING_CHANGES` we could keep working on 'hidden' features and be reasonably confident that production was unaffected.  At the same time we can create e2e tests for the new features and have those pass.

For example if `SHOW_UPCOMING_CHANGES` was true, the e2e tests would expect to *not* see 'Hypothetical New Cert' on /learn, but if it was false, the would expect it to be there.  When we're ready to go live, we'd remove the old e2e tests in favour of the new ones.

It would require a bit more juggling of tests, but it could make it easier to incorporate new features into the codebase before they're ready to go live.

**Comment by raisedadead** [comment]
@ojeytonwilliams 

I agree with you your [first comment](https://github.com/freeCodeCamp/freeCodeCamp/pull/39504#issuecomment-685059112) and as for your [second comment](https://github.com/freeCodeCamp/freeCodeCamp/pull/39504#issuecomment-685060206), I think that's a good approach. 

However lets start with small steps. Please note, the whole point of the staging environment is to check all things with parity to production. Will e2e tests for these help? Defnitely Yes. 

But I see them to have a diminishing effect here. You would be doing a basic QA of the curriculum and other things. e2e test would become "need" when we have three or more languages to support and the turn around time becomes a limitation.

For now and purposes of this PR, if we can re-align the variables we are good.

**Comment by ojeytonwilliams** [comment]
> For now and purposes of this PR, if we can re-align the variables we are good.

That should be working now.  I agree that the other discussion doesn't need to be resolved immediately.

**Comment by scissorsneedfoodtoo** [comment]
Thanks for implementing this @ojeytonwilliams and thanks @raisedadead for giving us that context about the different flags.

Tested locally by flipping `isUpcomingChange` to true in a couple of `meta.json` files and by playing with the `SHOW_UPCOMING_CHANGES` flag in `.env`. Everything LGTM.

**Comment by ojeytonwilliams** [comment]
Cool, thanks Kris.  When everyone's happy, I'll rebase this to two commits (removal from frontmatter and the new stuff)

**Review by RandellDawson — DISMISSED** [review]
LGTM

**Comment by RandellDawson** [comment]
After your last force-push, I tested things locally again and I believe found a problem.

I set the Debugging section's meta.json to show  "isUpcomingChange": true.  Then, when I ran npm run develop, I got:
```sh
Error: debugging is missing from superblock javascript-algorithms-and-data-structures
    at buildCurriculum (/home/rdawson/Coding/fcc/curriculum/getChallenges.js:96:13)
    at EventEmitter.<anonymous> (/home/rdawson/Coding/fcc/curriculum/getChallenges.js:47:9)
    at EventEmitter.emit (/home/rdawson/Coding/fcc/curriculum/node_modules/eventemitter3/index.js:181:35)
    at Object.filter (/home/rdawson/Coding/fcc/curriculum/node_modules/readdirp-walk/readdirp.js:72:15)
    at processFilter (/home/rdawson/Coding/fcc/curriculum/node_modules/walk-filtered/index.js:23:91)
    at /home/rdawson/Coding/fcc/curriculum/node_modules/walk-filtered/index.js:34:5
    at FSReqCallback.oncomplete (fs.js:169:5)
failed to create block debugging in superBlock javascript-algorithms-and-data-structures
not finished source and transform nodes - 1.511s
```
When I reviewed PR this morning before the force-push, it would not error out and instead just not show the Debugging section in learn (which is the expected behavior).

**Comment by ojeytonwilliams** [comment]
Just an FYI: *all* the meta.json files have `"isUpcomingChanges": true` now, but it only matters for the blocks, not the superblocks.  The superblock's meta.jsons have it, but it's silently ignored.  However the superblocks should disappear from the map when all their blocks do.

@ahmadabdolsaheb if you're making the settings dynamic, it might be useful.

**Review by RandellDawson — APPROVED** [review]
Finally finished my final review including testing out the changes mentioned in @ojeytonwilliams' last comment.  LGTM

**Pull request merged**
