### PR TITLE
Contributor tools searches from all PRs

### PR DESCRIPTION
**Pull request by Nirajn2311**
Search for common files through all PRs instead of PRs from `main` branch only

Checklist:

- [x] I have read [freeCodeCamp's contribution guidelines](https://contribute.freecodecamp.org).
- [x] My pull request has a descriptive title (not a vague title like `Update index.md`)
- [x] My pull request targets the `main` branch of freeCodeCamp.
- [x] I have tested these changes either locally on my machine, or GitPod.

Closes #XXXXX

### CODE REVIEW

**Review by thecodingaviator — CHANGES_REQUESTED** [review]
`defaultBase` can also go from line 4

**Comment by Nirajn2311** [comment]
Nice catch. Also I just remembered there is one other thing to look at.

**Review by raisedadead — DISMISSED** [review]
I'll need a while to get this deployed.

**Review by naomi-lgbt — DISMISSED** [review]
Thanks for this Niraj!

**Comment by Nirajn2311** [comment]
Ok, this PR is ready to be merged now.

**Review by naomi-lgbt — APPROVED** [review]

**Review by thecodingaviator — APPROVED** [review]

**Pull request merged**
