### PR TITLE
New "for loop" waypoints and verbiage improvements

### PR DESCRIPTION
**Pull request by SaintPeter**
I see a lot of folks come though the Bonfires and they don't have a clear understanding of everything that for loops can do for them.  I wanted to expand the explanations given about for loops and then run through some examples.

I don't know if the new verbiage on the existing For loop is too dense, but it covers all the fundamentals.

I have tested all of this locally.

### CODE REVIEW

**Comment by abhisekp** [comment]
@SaintPeter Could you upload a screenshot of how the challenge looks like in production?

**Comment by BerkeleyTrue** [comment]
@SaintPeter Just double checking, you used Mongodb to create a fresh id for the new challenge?

**Comment by SaintPeter** [comment]
Correct.  The original For loop challenge has the same ID, the two new ones
have new IDs.

Regards,
Rex Schrader

**Comment by BerkeleyTrue** [comment]
Awesome. I'm paranoid about these things. Duplicate id's cause havoc and are easily overlooked. Thanks for being so thorough.

Sorry about the delay. This is waiting on Quincy to QA and approve.

**Comment by QuincyLarson** [comment]
@SaintPeter excellent work here. These challenges make for loops much clearer than they were before. These are definitely the kinds of improvements we want to make to our curriculum, so please keep it up! :)

**Pull request merged**
