### PR TITLE
fix: change typo in 3 mentioned certifications

### LINKED ISSUE #39284: Typo in scientific computing with python certificate
**Describe your problem and how to reproduce it:**
There is a typo in the scientific computing with python certificate which displays "400" hours instead of "300" as the conservative estimated time of completion.

**Add a Link to the page with the problem:**
https://www.freecodecamp.org/certification/obsessedyouth/scientific-computing-with-python-v7

**Tell us about your browser and operating system:**
* Browser Name: 
Google Chrome
* Browser Version: 
Version 84.0.4147.89 (Official Build) (64-bit
* Operating System: 
Windows 10 Enterprise

**If possible, add a screenshot here (you can drag and drop, png, jpg, gif, etc. in this box):**
Screenshot (364)

### PR DESCRIPTION
**Pull request by Aviel212**
resolves #39284

Checklist:

- [x] I have read [freeCodeCamp's contribution guidelines](https://contribute.freecodecamp.org).
- [x] My pull request has a descriptive title (not a vague title like `Update index.md`)
- [x] My pull request targets the `master` branch of freeCodeCamp.
- [x] All the files I changed are in the same world language, for example: only English changes, or only Chinese changes, etc.

Closes #39284

### CODE REVIEW

**Comment by nhcarrigan** [comment]
Hello~!

Thank you for submitting a potential fix, however I believe this is not correct. It looks like you are changing the estimated course length to 300 hours, but per [this comment](https://github.com/freeCodeCamp/freeCodeCamp/issues/39284#issuecomment-660453375) the estimates in the API are correct and it is the curriculum map that needs to be updated. 🙂

**Comment by Aviel212** [comment]
The hard coded value shown in the curriculim map is 300 though in the certifications mentioned the value is 400. I was hoping to get it right, I'll follow the Issue.

**Comment by Aviel212** [comment]
After re-investigation I believe that this pull request will fix the bug.

**Comment by nhcarrigan** [comment]
To clarify, the 400 hour estimate for these certifications is *correct* and not a typo. 

The bug is due to the *300 hour* estimate being hard-coded here:
https://github.com/freeCodeCamp/freeCodeCamp/blob/76879f9e7e77dc3bd263c55246c07c965bfded4e/client/src/components/Map/components/SuperBlock.js#L51-L55

It appears that your proposal still changes the 400 hour value on the certificates to 300 hours, which is not correct - we, instead, want to update the curriculum map to accurately reflect the estimated time for each certificate (either 300 or 400 hours, at the moment).

**Comment by Aviel212** [comment]
Thank you for clarify.

**Pull request closed without merging**
