### PR TITLE
fix: updated description of the lesson.

### LINKED ISSUE #45097: implicit use of a function without any guide.
## Affected page

https://www.freecodecamp.org/learn/2022/responsive-web-design/learn-css-transforms-by-building-a-penguin/step-104

## To reproduce

It's implicit required the use of the function calc in order to complete this minichallenge. this function was never explained or used in the entire course, students should have issues trying to find this function in google.

## Recommended fix, suggestions

Giving a brief explanation of the function will be enough

## Screenshots

image

### PR DESCRIPTION
**Pull request by tikenov**
Checklist:

- [x] I have read [freeCodeCamp's contribution guidelines](https://contribute.freecodecamp.org).
- [x] My pull request has a descriptive title (not a vague title like `Update index.md`)
- [x] My pull request targets the `main` branch of freeCodeCamp.
- [x] I have tested these changes either locally on my machine, or GitPod.

Closes #45097

Added short description about calc() function.

### CODE REVIEW

**Comment by Sembauke** [comment]
Hey @tikenov,

please update the title to your pr and read our [contributor guidelines](https://contribute.freecodecamp.org/#/)

**Comment by tikenov** [comment]
> Hey @tikenov,
> 
> please update the title to your pr and read our [contributor guidelines](https://contribute.freecodecamp.org/#/)

Hi #Sembauke,

Updated title according to guidelines.

**Comment by ShaunSHamilton** [comment]
Hello there,

Thank you, for being eager to contribute. However, the issue this relates to has not been discussed, and has not been made open for contribution.

As such, I am blocking this PR, until we have discussed the best course of action for the linked issue. Thank you.

---


An issue with the _help wanted_ or _first timers only_ label is open for contribution. The first comprehensive PR created will be reviewed and merged. We typically do not assign issues to anyone other than long-time contributors.

If you would like to contribute, and have not read the contributors docs, please do so here: https://contribute.freecodecamp.org/#/

If you have any issues with contributing, be sure to join us on the [contributors channel](https://chat.freecodecamp.org/channel/contributors), or on the [contributors sub-forum](https://forum.freecodecamp.org/c/contributors/3)

**Comment by nhcarrigan** [comment]
Hey there!

Thank you for your interest in contributing. However, with the refactor of the balance sheet project, we're now introducing `calc` earlier in the curriculum and further explanation in this step isn't needed.

We'd gladly welcome future pull requests from you!

**Pull request closed without merging**
