### PR TITLE
feat(documentation): add some words to specify for users and developers

### PR DESCRIPTION
**Pull request by LilyYin17**
Checklist:

- [x] I have read [freeCodeCamp's contribution guidelines](https://contribute.freecodecamp.org).
- [x] My pull request has a descriptive title (not a vague title like `Update index.md`)
- [x] My pull request targets the `main` branch of freeCodeCamp.
- [x] I have tested these changes either locally on my machine, or GitPod.

Closes #XXXXX

### CODE REVIEW

**Comment by samarmohan** [comment]
Hey! It is definitely possible that developers would want to learn and normal users would want to contribute. Normal users could contribute to documentations and devs are always leveling up their skills.
Thanks for contributing though!

**Review by samarmohan — CHANGES_REQUESTED** [review]
It is definitely possible that developers would want to learn and normal users would want to contribute. Normal users could contribute to documentation and devs are always leveling up their skills.

**Comment by LilyYin17** [comment]
> It is definitely possible that developers would want to learn and normal users would want to contribute. Normal users could contribute to documentation and devs are always leveling up their skills.

Thanks!

**Comment by samarmohan** [comment]
Thanks for your time and effort though!

**Comment by samarmohan** [comment]
@LilyYin17 you have 3 prs doing the same thing, would you mind closing two of them and continuing your development in one?

**Comment by LilyYin17** [comment]
> @LilyYin17 you have 3 prs doing the same thing, would you mind closing two of them and continuing your development in one?

I can do that!

**Review by ShaunSHamilton — COMMENTED** [review]
Hello there,

Thank you, for taking the time to contribute. However, I do not believe this change would be beneficial, at this time.

Mostly, because the contributing link is not solely for developers, but translators, as well as moderators. As such, we would not want to reduce the likelyhood of someone coming across these changes.

Will leave open for now, to hear from others.

**Pull request closed without merging**
