### PR TITLE
feat: show reset button after submitting the code once

### LINKED ISSUE #47037: Reduce require submit times needed to show reset the code button
### Is your feature request related to a problem? Please describe.

In forum, people come frustrated, I think when they have the ability to reset their steps early, it will reduce that frustration.

### Describe the solution you'd like

Show reset button after one click. 

Seeing `reset` button showing after one click, will make it look like we are offering tools if they need them, instead of blocking them.

Pressing `reset` button will reset the counter, which should need to be changed, as well. 

### Describe alternatives you've considered

Show `reset` button right away, although easier, it will make people feel, we are blocking need for help button, because you can't access it unless you have submitted three times.

### Additional context

If you would like to fix this issue, please make sure you read [our guidelines for contributing](https://contribute.freecodecamp.org/#/), we prioritize contributors following the instructions in our guides. Join us in [Discord server](https://discord.gg/Z7Fm39aNtZ)) or [the forum](https://forum.freecodecamp.org/c/contributors/3) if you need help contributing, our moderators will guide you through this.

Sometimes we may get more than one pull requests. We typically accept the most quality contribution, followed by the one that is made first.

You can try to take inspiration from this pull request 😉 if you want to tackle it https://github.com/freeCodeCamp/freeCodeCamp/pull/46641

Happy contributing.

### PR DESCRIPTION
**Pull request by Jagrutiti**
Checklist:

- [x] I have read [freeCodeCamp's contribution guidelines](https://contribute.freecodecamp.org).
- [x] My pull request has a descriptive title (not a vague title like `Update index.md`)
- [x] My pull request targets the `main` branch of freeCodeCamp.
- [x] I have tested these changes either locally on my machine, or GitPod.

Closes #47037

### CODE REVIEW

**Review by Sboonny — CHANGES_REQUESTED** [review]
hey @Jagrutiti, we are seeking to show reset the step first before showing ask for help

something like this:
image

You can go for Naomi suggestion, and show it all the time. but ask for help button shouldn't show after one attempt

**Comment by Sboonny** [comment]
If you decided an approach, we can discuss how you can do it here or in discord https://discord.com/invite/Z7Fm39aNtZ

**Comment by Jagrutiti** [comment]
Hey @Sboonny 

I couldn't find to hide and show button in React (I only the one with document.getElementById() in vanilla JavaScript). So I used the if and else condition. It does the job. But I change the code if you want me to.

**Review by Sboonny — APPROVED** [review]
While testing it I had taken the same approach.

So LGTM 🎉, thank you for your contribution to the page! 👍.

Edit should have waited for tests before approving, I will check on it later

**Review by Sembauke — CHANGES_REQUESTED** [review]
Hey the reset button seems to always be visible, even before the first attempt.

We should only show the reset button after the first attempt.

**Comment by Sboonny** [comment]
@Sembauke I prefer the first attempt too, but @naomi-lgbt won the democratic votes with bbsmooth 
and Jeremy votes  https://github.com/freeCodeCamp/freeCodeCamp/issues/47037#issuecomment-1195764572

That being said I am down for a coup 😉

**Comment by Jagrutiti** [comment]
@Sembauke 

This sounds logical. I wanted to do the same initially but in the discord discussion, it was decided it should be visible from the beginning.

So let me know what is to be done.

**Review by ahmaxed — APPROVED** [review]

**Comment by ahmadabdolsaheb** [comment]
@Sembauke, I agree with you; however, since other team members have come to a conclusion we could move forward with this implementation. We could revisit it in the upcoming icon button revision.

**Comment by ahmadabdolsaheb** [comment]
@Jagrutiti Thanks for working on this. 🙌

**Pull request merged**
