### PR TITLE
fix(Certificates): Delete word 'projects' from certificates' titles

### LINKED ISSUE #17667: Certification views have an unnecessary "projects" word in them
Please see image below. This seems to affect all six of the new certifications.

dgkd_vfvaaassmd

### PR DESCRIPTION
**Pull request by Dar0n**
It seems like the problem was in .jade files describing certificate wrapper container.
Corresponding .jade files were changed.
Have not tested results due to the issue #17382.

Closes #17667

#### Pre-Submission Checklist

- [ ] Your pull request targets the `staging` branch of freeCodeCamp.
- [ ] Branch starts with either `fix/`, `feature/`, or `translate/` (e.g. `fix/signin-issue`)
- [ ] You have only one commit (if not, [squash](http://forum.freecodecamp.org/t/how-to-squash-multiple-commits-into-one-with-git/13231) them into one commit).
- [ ] All new and existing tests pass the command `npm test`. Use `git commit --amend` to amend any fixes.

#### Type of Change

- [ ] Small bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds new functionality)
- [ ] Breaking change (fix or feature that would change existing functionality)
- [ ] Add new translation (feature adding new translations)

#### Checklist:

- [ ] Tested changes locally.
- [ ] Addressed currently open issue (replace XXXXX with an issue no in next line)

Closes #XXXXX

### CODE REVIEW

**Comment by Bouncey** [comment]
Thanks for the PR @Dar0n, could you please undo the changes to the `package.json` and the `package-lock.json` file. These changes are out of scope for this PR. Many thanks :+1:

**Comment by Dar0n** [comment]
I have messed around trying to revert or reset changes. In the end I just made a hard reset to the state before initial commit and modified only .jade files once again. Please check it :)

**Review by Bouncey — APPROVED** [review]

**Comment by Bouncey** [comment]
Thanks @Dar0n

**Comment by QuincyLarson** [comment]
@Dar0n Thanks again for your help with this!

**Comment by Dar0n** [comment]
@QuentinGibson @Bouncey Thank you so much for this opportunity! :)

**Pull request merged**
