### PR TITLE
Anadi informacion de apps

### PR DESCRIPTION
**Pull request by allmessedup**
con hipervínculo: https://apps.wordpress.com/mobile/

- [x] I have read [freeCodeCamp's contribution guidelines](https://github.com/freeCodeCamp/freeCodeCamp/blob/master/CONTRIBUTING.md).
- [x] My pull request has a descriptive title (not a vague title like `Update index.md`)
- [x] My pull request targets the `master` branch of freeCodeCamp.
- [x] None of my changes are plagiarized from another source without proper attribution.
- [x] My article does not contain shortened URLs or affiliate links.

If your pull request closes a GitHub issue, replace the XXXXX below with the issue number.

Closes #XXXXX

### CODE REVIEW

**Comment by RandellDawson** [comment]
Closed and Reopened this PR to attempt to resolve a specific Travis build failure.

**Comment by RandellDawson** [comment]
@allmessedup Thank you for  creating this PR.  However, since it was created, the underlying document has changed.  Can you please review and resolve the current merge conflicts?  It could be the changes to the underlying document are so significant that your changes are no longer relevant.  If the latter is the case, it might be easier to just close this PR and create a new PR with any changes you still feel are important to make.

If you need any assistance or have questions about resolving the merge conflicts, please reply back or contact someone in the [Contributors Room on Gitter](https://gitter.im/FreeCodeCamp/Contributors).

Thank you.

**Comment by allmessedup** [comment]
Hello and thank you.

I haven’t done much of this, and I am not quite sure what is needed here. I am guessing this is small stuff and you have many other things going on. 

But I located the page below.

I would learn something here if I knew (for example)...  why there appears to be an add/delete of the same item?

Also, is there a big picture bullet point/blurb on what is happening relative to the page or project.  I read that the entire thing is moving to a new spot...

Thank you for encouraging the Hacktoberfest participation

Best regards!  If you need to resolve this without diving into individual attention and move along - No problem at all. Understand.


https://github.com/freeCodeCamp/freeCodeCamp/pull/27342/files#diff-60d70c3c7481e059429d2ab4a861fe99

**Comment by RandellDawson** [comment]
@allmessedup After reviewing your changes compared to the what has already been changed on the master branch after your PR was created, we have decided not to incorporate your changes.  

Thank you

**Pull request closed without merging**
