### PR TITLE
docs: update Russian translation for the whole React guide

### PR DESCRIPTION
**Pull request by egor-sorokin**
- [x] I have read [freeCodeCamp's contribution guidelines](https://github.com/freeCodeCamp/freeCodeCamp/blob/master/CONTRIBUTING.md).
- [x] My pull request has a descriptive title (not a vague title like `Update index.md`)
- [x] My pull request targets the `master` branch of freeCodeCamp.
- [x] None of my changes are plagiarized from another source without proper attribution.
- [x] My article does not contain shortened URLs or affiliate links.

If your pull request closes a GitHub issue, replace the XXXXX below with the issue number.

Closes #XXXXX

### CODE REVIEW

**Comment by greggubarev** [comment]
This PR was closed and then re-opened in an attempt to clear a specific Travis build failure

**Comment by RandellDawson** [comment]
@greggubarev I resolved the frontmatter issues which CamperBot mentioned above and was the reason the build failed.  That is why just closing and reopening the PR did not resolve the Travis failure.  If you have reviewed the content, feel free to merge it now.

**Comment by greggubarev** [comment]
### LGTM 👍  Congrats on your first contribution! 
Image of Office
Thank you for the PR ✨ 🎉 We're happy to accept these changes and look forward to your future contributions.

Happy coding!

**Review by greggubarev — APPROVED** [review]
### LGTM 👍  Congrats on your first contribution! 
Image of Office
Thank you for the PR ✨ 🎉 We're happy to accept these changes and look forward to your future contributions.

Happy coding!

**Pull request merged**
