### PR TITLE
Fix/forgot password error message

### LINKED ISSUE #5120: Password reset error trying to display an object
Here's a screenshot: http://www.evernote.com/shard/s29/sh/9a04e852-0397-4c52-9aba-9766c6bf3dc4/1935afe4e3290aa56f367dd810db26d9

I'm going to poke around in the code and see if I can figure out what's trying to be returned and what's actually being returned. If I'm able to do so, I'll submit a PR.

### PR DESCRIPTION
**Pull request by Zenith-One**
This fixes the incorrect display of the error message for the 'Forgot Password' form, as well as a the existing linting errors in server/boot/user.js (both were implicit coercion errors).

**EDIT:** Removed the unnecessary lint fixes

Fixes #5120

### CODE REVIEW

**Comment by ltegman** [comment]
Thanks for the PR. Looks good and is perfectly formatted! Only issue is that we do not have the `no-implicit-coercion` eslint rule turned on, so your second commit should be removed from this branch.

**Comment by Zenith-One** [comment]
Apparently my local eslint config overrode the one in the repo. I'll fix that.

**Comment by Zenith-One** [comment]
Fixed.

**Comment by ltegman** [comment]
Looks good, thanks for the PR! Look forward to more from you in the future! :smile:

**Pull request merged**
