### PR TITLE
fix(a11y): remove unnecessary link on course heading

### PR DESCRIPTION
**Pull request by bbsmooth**
Checklist:

- [x] I have read [freeCodeCamp's contribution guidelines](https://contribute.freecodecamp.org).
- [x] My pull request has a descriptive title (not a vague title like `Update index.md`)
- [x] My pull request targets the `main` branch of freeCodeCamp.
- [x] I have tested these changes either locally on my machine, or GitPod.

Closes #XXXXX

The course headings (`<h3>`) on the curriculum block pages have an unnecessary link around them. This link does not actually function as a link since clicking on it does not take the user to another location. From what I can tell, clicking on the link triggers a page scroll which moves the heading to the top of the view port, but for keyboard users this does not change the location of the keyboard focus, so it's as if the link does nothing. Clicking on this link when using a screen reader gives no feedback and thus will appear as a broken link. The accessible name of the link is merely the course title and thus the screen reader user will assume the link takes them to a new page for the course instead of just scrolling the page.

If there is a need to have a feature that scrolls the course heading to the top of the page then this is best done with a separate button that explicitly states its functionality.

Removing these links does not affect the functionality of the react-scrollable-anchor library. You will still be able to target a specific course heading via the URL using the `#` such as learn/responsive-web-design/#basic-html-and-html5.

### CODE REVIEW

**Review by huyenltnguyen — COMMENTED** [review]
LGTM. 

I also agree that the scroll-into-view behavior should be implemented with a button instead of a link. Though personally I think the behavior here is a bit redundant because we can scroll past the headings, thus most of the time they would just be invisible to the users (unless this is a bug and we actually want the headings to always stick to the top of the page).

However, we still have one spot that needs to be fixed as well 🙂:

https://github.com/freeCodeCamp/freeCodeCamp/blob/304773d62be4b77882d38e5f1ab7a99b034a92ec/client/src/templates/Introduction/components/certification-card.tsx#L49-L54

And I think we would need to update this unit test also:

https://github.com/freeCodeCamp/freeCodeCamp/blob/d75e43a1e7ab608fa89221f36bce8b961c36151d/cypress/integration/learn/responsive-web-design/claim-cert-from-learn.js#L37-L40

**Comment by bbsmooth** [comment]
Good catch on the 'Claim Your Certification' heading (I wasn't logged in as a user so I didn't see it on my local version).

I'll set someone else do the cypress tests. Two of them deal with the anchor, which won't be there any more. The react-scrollable-anchor library doesn't appear to put the actual ids in the HTML so there is no element with `id="claim-cert-block"` that can be used to scroll to.

**Comment by huyenltnguyen** [comment]
Sorry, I meant to say we need to delete the unit test, but used the word "update" for some reason. The test is no longer relevant or correct (which is why it failed), so we can just delete it.

There is also some small cleanup we can do, if you don't mind. The class `block-link` is used in these components only, and we can safely delete the CSS now (https://github.com/freeCodeCamp/freeCodeCamp/search?q=block-link)

**Review by ojeytonwilliams — COMMENTED** [review]
There are a couple of merge conflicts, but aside from them, I think this is good to go.

**Comment by ahmadabdolsaheb** [comment]
@bbsmooth, I think when the conflicts are resolved this should be good to go.

**Review by ahmaxed — APPROVED** [review]

**Comment by ahmadabdolsaheb** [comment]
@ShaunSHamilton seems like you have taken care of the styles. LGMT

**Review by raisedadead — APPROVED** [review]

**Pull request merged**
