### PR TITLE
fix(learn): correct tests description

### PR DESCRIPTION
**Pull request by gikf**
* Adds missing closing quote in last test, and backticks to the results.
* Changes instruction to refer to general case, as it is currently in challenge.
* There is no outstanding issue regarding this problem.

Checklist:

- [x] I have read [freeCodeCamp's contribution guidelines](https://contribute.freecodecamp.org).
- [x] My pull request has a descriptive title (not a vague title like `Update index.md`)
- [x] My pull request targets the `main` branch of freeCodeCamp.
- [x] All the files I changed are in the same world language, for example: only English changes, or only Chinese changes, etc.

### CODE REVIEW

**Review by RandellDawson — DISMISSED** [review]
@gikf Thanks for these changes.  We are actually in the process of going through the various certification sections and removing quotation marks from inline code blocks for translation purposes.  Some languages use different kinds of quotation marks, so we are removing them all together.  @nhcarrigan is leading the effort on this, but any you find in the challenges you are modifying, it would be great if you went ahead and made those changes also.

Thanks

**Comment by gikf** [comment]
Sure, I'll keep an eye for them from now on.

**Review by moT01 — APPROVED** [review]
LGTM @gikf 🎉 I'm fine with these changes since it's an improvement. But I feel like this one could use some work. The instructions don't seem very clear. There's some external links that could go. Maybe some other time.

**Comment by gikf** [comment]
You are right, description could use clarity, I didn't want to touch it just yet.

**Review by naomi-lgbt — APPROVED** [review]
Looks good to me.

I agree with @moT01 that this challenge could use some help, but this resolved the inaccuracy in the instructions.

**Pull request merged**
