### PR TITLE
[WIP] Use Plain XHR instead of jQuery to avoid multiple request to endpoints 

### PR DESCRIPTION
**Pull request by raisedadead**
Refers #8923 and #9196

### CODE REVIEW

**Comment by bugron** [comment]
What's the status of this PR?

**Comment by alayek** [comment]
What if we use the [fetch API](https://developer.mozilla.org/en/docs/Web/API/Fetch_API) and its polyfills for older browsers?

**Comment by raisedadead** [comment]
@bugron I seem to have problem reproducing this and the issue is highly weird. Could any of the @FreeCodeCamp/issue-moderators pitch in and test this PR as it is with the email verification scenario.

If it looks okay, then I'll clean up the fix, add it to night mode and update.

@alayek yeah we could, but I think @BerkeleyTrue and myself felt making a vanilla implement to be most clean way to address this, because even a solid library like jQuery seems to act weird over here.

**Comment by BerkeleyTrue** [comment]
@raisedadead I've already updated the ajax requests to use XHR on the react branch. I have not run into the issue again since.

**Comment by raisedadead** [comment]
@BerkeleyTrue in that case closing this in favor of react infrastructure. And awesome job resolving it!

**Comment by BerkeleyTrue** [comment]
Beta is using the the new ajax to update email. I still haven't run into the same issue

**Comment by raisedadead** [comment]
Cool. Could you try adding the verification prompt like we did and maybe I'll give it test to double check?

**Pull request closed without merging**
