### PR TITLE
feat(curriculum): add log with function call to challenge

### PR DESCRIPTION
**Pull request by yasledesma**
Checklist:

- [x] I have read [freeCodeCamp's contribution guidelines](https://contribute.freecodecamp.org).
- [x] My pull request has a descriptive title (not a vague title like `Update index.md`)
- [x] My pull request targets the `main` branch of freeCodeCamp.
- [x] I have tested these changes either locally on my machine, or GitPod.

Added a log statement to the seed's content, referencing the function countOnline with a sample object as argument.
The user should be able to see the result of the function printed out on the console as soon as it is ran, and it should be easier to understand what is being outputed by the function in this challenge.

### CODE REVIEW

**Review by gikf — COMMENTED** [review]
I think it'd be better to keep it consistent with [previous](https://www.freecodecamp.org/learn/javascript-algorithms-and-data-structures/basic-data-structures/check-if-an-object-has-a-property) and [next](https://www.freecodecamp.org/learn/javascript-algorithms-and-data-structures/basic-data-structures/generate-an-array-of-all-object-keys-with-object-keys) challenges. That means adding sample `users` object to the seed code and then using it for the printed out function call.

Here that would allow removing the sample users object from instructions.

**Review by BIOSTYMA — APPROVED** [review]

**Comment by nhcarrigan** [comment]
Hey @HiddenOgre28,

Are you interested in implementing gikf's suggestions?

**Comment by HiddenOgre28** [comment]
@nhcarrigan @gikf Sorry, I added the example object now and corrected the printing statement.

**Comment by gikf** [comment]
@HiddenOgre28 All is good, no need to make new PR. As it can be seen above, new commit on the branch got added to PR.

**Review by gikf — APPROVED** [review]
LGTM :+1:

**Review by ShaunSHamilton — CHANGES_REQUESTED** [review]
Before we move forward with this, I would like to point out that we specifically removed the `users` object in a previous PR: https://github.com/freeCodeCamp/freeCodeCamp/pull/35899

**Comment by gikf** [comment]
As far as the modifying this object - it won't matter. In tests are used objects defined in the `## --after-user-code--`, which will take precedence, even if there's defined variable with the same name in seed code.

**Pull request merged**
