### PR TITLE
fix(challenges): Fix octal escape sequence error

### LINKED ISSUE #16396: Octal Escape Sequence Error with Travis CI Build
#### Issue Description

User @AungMyoKyaw issued a pull request (#15856) to update Euler Project problem 4 in the interview prep section. Though the updated code in the pull request is correct and passes `npm test`, Travis CI throws the error `Octal escape sequences are not allowed in strict mode.` However, the error occurs due to a leading zero in the solution of the Create a Priority Queue problem in the data structures portion of the interview prep section.

### PR DESCRIPTION
**Pull request by scissorsneedfoodtoo**
#### Pre-Submission Checklist

- [x] Your pull request targets the `staging` branch of freeCodeCamp.
- [x] Branch starts with either `fix/`, `feature/`, or `translate/` (e.g. `fix/signin-issue`)
- [x] You have only one commit (if not, [squash](http://forum.freecodecamp.org/t/how-to-squash-multiple-commits-into-one-with-git/13231) them into one commit).
- [x] All new and existing tests pass the command `npm test`. Use `git commit --amend` to amend any fixes.

#### Type of Change

- [x] Small bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds new functionality)
- [ ] Breaking change (fix or feature that would change existing functionality)
- [ ] Add new translation (feature adding new translations)

#### Checklist:

- [x] Tested changes locally.
- [x] Addressed currently open issue (replace XXXXX with an issue no in next line)

Closes #16396

#### Description

Another user is having a problem with their pull request because the
Travis Cl build keeps failing. Each time the Travis Cl build throws an
error about an octal literal escape sequence not being allowed in strict
mode, and it seems to happen with the Create a Priority Queue Class
challenge.

BREAKING CHANGE: None

### CODE REVIEW

**Comment by raisedadead** [comment]
@AungMyoKyaw will you be interested in QA for this?

**Comment by scissorsneedfoodtoo** [comment]
@raisedadead, Sorry! I should have thought of this sooner.

If @AungMyoKyaw can add the code here to the pull request that keeps failing the build, then we don't need to coordinate between two separate pull requests to solve one issue.

**Comment by raisedadead** [comment]
Hi @scissorsneedfoodtoo https://github.com/scissorsneedfoodtoo/freeCodeCamp/pull/1
Please squash and merge there.

That will update this PR of yours.

**Comment by scissorsneedfoodtoo** [comment]
Sure thing! I'll do that now.

**Comment by scissorsneedfoodtoo** [comment]
Turns out I was way off base. There was no problem with the "Create a Priority Queue Class" challenge, and it was either the tests, solution, or both from Euler "Problem 4: Largest palindrome product" causing the issues.

**Comment by raisedadead** [comment]
Yikes, we have some unwanted commits in there. 

I am sorry I should have been clearer for you in the instruction earlier, that you should have had to only hit the 'Squash and merge' button on the PR that I created.

Never mind, I'll take a look asap and fix this.

Sorry once again.

**Comment by scissorsneedfoodtoo** [comment]
@raisedadead, I'm sorry about that! I ended up playing the the files on my end trying the fix the issue and messed up the commit commands.

**Comment by raisedadead** [comment]
No worries, it git and hence fixable..! BTW just to confirm we want the commit you have for this PR originally and the commit from @AungMyoKyaw 's original PR.

i.e:
1. https://github.com/freeCodeCamp/freeCodeCamp/pull/16385/commits/5ec8341caffb126578391c841f156019dbbe75f6
2. https://github.com/freeCodeCamp/freeCodeCamp/pull/16385/commits/4521e2052f7f28c02939e913c912ce617d804764

Correct ?

**Comment by scissorsneedfoodtoo** [comment]
Actually, maybe the best thing to do is close this. Turns out the problem has to do with the solution in @AungMyoKyaw's original PR. If we remove the solution there, `npm test` should pass just fine.

**Comment by raisedadead** [comment]
Okay, then lets proceed with that discussion there and close this

**Comment by scissorsneedfoodtoo** [comment]
Okay! Thanks again for all your help. Sorry about the trouble.

**Comment by raisedadead** [comment]
No worries thanks for all the effort in this!

**Pull request closed without merging**
