### PR TITLE
feat: split JS challenge into two

### PR DESCRIPTION
**Pull request by beaucarnes**
Checklist:

- [x] I have read [freeCodeCamp's contribution guidelines](https://contribute.freecodecamp.org).
- [x] My pull request has a descriptive title (not a vague title like `Update index.md`)
- [x] My pull request targets the `master` branch of freeCodeCamp.
- [x] All the files I changed are in the same world language, for example: only English changes, or only Chinese changes, etc.

Closes #XXXXX

@QuincyLarson requested that the "Storing Values with the Assignment Operator" challenge should be broken into two challenges. That is what this PR does.

### CODE REVIEW

**Comment by RandellDawson** [comment]
>From my understanding it was discussed we would not be updating (including, re-arranging, re-ordering, etc.) the current optional challenges in favor of the planned project based curriculum.

That has been our understanding for quite some time.  There are so many challenges we wanted to rearrange and fix the order/section in which they were in (based on Forum feedback), but we were told no new challenges and no more rearranging existing challenges were allowed.  We were only allowed to "tweak" existing challenges to improve them without creating any new ones.

**Comment by beaucarnes** [comment]
The context was @QuincyLarson  requested this in an email (see screenshot below). Maybe we should confirm with Quincy before merging, though.

image

**Comment by RandellDawson** [comment]
@beaucarnes After reviewing the changes, I notice your example in the `Assigning the Value of One Variable to Another`, that you show initializing a variable (i.e. `var a = 5;`), but that concept is not introduced until the lesson after this (`Initializing Variables with the Assignment Operator`).   

I think you should change the description to something like:

> After a value is assigned to a variable using the assignment operator, you can assign the value of that variable to another variable using the assignment operator.
```js
var myVar;
myVar = 5;
var myNum;
myNum = myVar;
```
 >The above declares a `myVar` variable, then assigns it the value `5`.  Next, a variable named `myNum` is declared with no value.  Then, the contents of `myVar` (which is `5`) is assigned to the variable `myNum`.  Now, `myNum` also has the value of `5`.

**Comment by moT01** [comment]
I changed this to use @RandellDawson's suggestion. Also created a guide article for the new challenge and added the topicId.

**Review by moT01 — APPROVED** [review]
Not sure I should review this since I made the last commit - but it LGTM 🎉

Edit: Pending the tests

**Review by RandellDawson — APPROVED** [review]
LGTM.  Tested locally.

**Comment by RandellDawson** [comment]
@Sky020 If you are fine with the changes, feel free to merge this one.

**Comment by Sky020** [comment]
I am happy with these changes, as they work. Thank you, Beau

To mention a spanner in the works: Had I caught onto this PR sooner, I would not have created a new challenge, but just split the content between _Initializing Variables with the Assignment Operator_, as there is very little content there.

Keeping in line with what Quincy mentioned earlier:
> Yes – we shouldn't spend a whole lot of time updating these challenges, but in a situation where a challenge is unnecessarily complicated like this one, we do want to go ahead and fix it. Even if that means breaking the challenge down into several, simpler challenges.

I am happy to merge this.

**Pull request merged**
