### PR TITLE
Fix/portuguese translation

### PR DESCRIPTION
**Pull request by kodagabriel**
- [x] I have read [freeCodeCamp's contribution guidelines](https://github.com/freeCodeCamp/freeCodeCamp/blob/master/CONTRIBUTING.md).
- [x] My pull request has a descriptive title (not a vague title like `Update index.md`)
- [x] My pull request targets the `master` branch of freeCodeCamp.
- [x] None of my changes are plagiarized from another source without proper attribution.
- [x] All the files I changed are in the same world language (for example: only English changes, or only Chinese changes, etc.)
- [x] My changes do not use shortened URLs or affiliate links.

Closes #XXXXX

### CODE REVIEW

**Comment by RandellDawson** [comment]
@kodagabriel Thank you for helping us update our documentation.  Would it be possible for you to look through the current English version of the same 3 files you changed (see below) and add any additional content that is not currently present in Portuguese version of the files and remove any content from the Portuguese version of the files which is no longer in the English version?  We are trying to make sure the non-English versions of these files are kept in sync and there have been many changes to the English versions of these same files in the past 11 months, so I am fairly sure they are out of sync.

**Note:** Make sure the translations use Brazilian Portuguese if the translations are not already.

Thanks in advance for any help you can provide here!  Your work would be greatly appreciated.

The following English document corresponds to the `docs/portuguese/document-quick-reference.md`:
>https://github.com/freeCodeCamp/freeCodeCamp/blob/master/docs/README.md

The following English document corresponds to the `docs/portuguese/how-to-catch-outgoing-emails-locally.md`:
>https://github.com/freeCodeCamp/freeCodeCamp/blob/master/docs/how-to-catch-outgoing-emails-locally.md

The following English document corresponds to the `docs/portuguese/how-to-setup-freecodecamp-locally.md`:
>https://github.com/freeCodeCamp/freeCodeCamp/blob/master/docs/how-to-setup-freecodecamp-locally.md

**Comment by kodagabriel** [comment]
I noticed few changes in the english documentation and wasn't sure if I should translate them. I'll keep up to it and make the changes so that the files are in sync. As far as I noticed it's all already in Brazilian Portuguese. I plan to check all translated files in the future, so I'll keep that in mind. 
Also, quick questions:
1) the links to the translated versions here (https://github.com/freeCodeCamp/freeCodeCamp/blob/master/docs/README.md) don't work at all. They all lead to files that don't exist. I believe they should be poiting to the CONTRIBUTING.md file insted. Is this corret? If so, I'll already change that too. 

2) In all the portuguese files there is a navigation "bar" that leads to other translations (in this one the links work). In the english version this navbar is only in the CONTRIBUTING.md file. Should I keep it that way or change it to match the english version? 

Thanks in advance!

**Comment by RandellDawson** [comment]
@kodagabriel In the one file where you replaced:
```
        <td><a href="/docs/chinese/README.md"> 中文 </a></td>
        <td><a href="/docs/russian/README.md"> русский </a></td>
        <td><a href="/docs/arabic/README.md"> عربي </a></td>
        <td><a href="/docs/spanish/README.md"> Español </a></td>
        <td><a href="/docs/portuguese/README.md"> Português </a></td>
        <td><a href="/docs/german/README.md"> Deutsch </a></td>
```
with something else, don't do that.  Instead, just make it just like the English version.

As far as where you removed the tables from the other two files, only do that if the English version does not have them.

We are actually going to remove all of these table in the future and create a section on our https://contribute.freecodecamp.org which would host the documentation and we would use a template site which would have a single applicable  table navigation header dynamically inserted into all of the various languages's documentation pages.

**Comment by kodagabriel** [comment]
I fixed the part that wasn't matching the English version. Had to change one file's name to continue matching. I guess it's all good now. Is there anything else I could fix?

**Comment by RandellDawson** [comment]
@kodagabriel You should not have changed `docs/portuguese/CONTRIBUTING.md` to `docs/portuguese/README.md`.  Please revert that change.

**Comment by kodagabriel** [comment]
Done! Still learning how to do stuff. Thanks for being patient.

**Comment by RandellDawson** [comment]
@kodagabriel You were not supposed to delete the `CONTRIBUTING.md` file, so please revert that change.  Also, since you last committed, there have been some decisions made around reorganizing the docs folder in general.  We will no longer have the `document-quick-reference.md` files, so please delete `docs/portuguese/document-quick-reference.md`.

**Comment by RandellDawson** [comment]
Thank you for opening this pull request.

This is a standard message notifying you that we’ve reviewed your pull request and have decided not to merge it. We would welcome future pull requests from you.

**Reason:** Since your PR was created, the master branch content has updated making some of your changes unnecessary or need to be reorganized to fit the current version.  Please re-sync your fork so you are looking at the latest version of master and then create a new PR if you find any changes warranted.  

Thank you and happy coding.

**Pull request closed without merging**
