### PR TITLE
Added Installation for Linux

### PR DESCRIPTION
**Pull request by kindavishal**
- [x] I have read [freeCodeCamp's contribution guidelines](https://github.com/freeCodeCamp/freeCodeCamp/blob/master/CONTRIBUTING.md).
- [x] My pull request has a descriptive title (not a vague title like `Update index.md`)
- [x] My pull request targets the `master` branch of freeCodeCamp.
- [x] None of my changes are plagiarized from another source without proper attribution.
- [x] My article does not contain shortened URLs or affiliate links.

If your pull request closes a GitHub issue, replace the XXXXX below with the issue number.

Closes #XXXXX

### CODE REVIEW

**Comment by Nirajn2311** [comment]
@VishalDas95 Could you follow the [style guide](https://github.com/freeCodeCamp/freeCodeCamp/blob/master/docs/style-guide-for-guide-articles.md) as the formatting in your file is wrong.

**Comment by VishalDas95** [comment]
Oh! I am so sorry I couldn't follow up! I will do the needful asap!

**Comment by RandellDawson** [comment]
@Asjas What does "other: decayed" label mean?

**Comment by Asjas** [comment]
It means the ticket is `stale` (no activity in more than 7 days).

**Pull request closed without merging**
