### PR TITLE
docs: use of language in tests

### PR DESCRIPTION
**Pull request by ojeytonwilliams**
I've been thinking about changing how we use language in tests (which are implicitly criticising the user) to make them less off-putting.  The idea being that being told that you've made a coding mistake is more frustrating than that there is a mistake in the code.  

If we can slightly change how we phrase things it might ease new learners into something that can be quite daunting.

That's the justification, anyway.  What do people think?

### CODE REVIEW

**Comment by jasmcaus** [comment]
Sounds good. The language we use directly mirrors how welcoming of a community we are in general - a sentence or two slightly out of place, and you've already got the user on the defense; doubt it'll suggest happy thoughts :) 

I second this. I think we could use this moving forward for the newer curriculum, and update the older one to reflect the same.

**Review by ShaunSHamilton — COMMENTED** [review]
Do you not think this paragraph would be better suit within `## Challenge description/instructions` (maybe change this title): https://github.com/freeCodeCamp/freeCodeCamp/pull/41864/files#diff-89131c49b98026768a7e023be9586401b75b650c17aaada42d2d733a4ad296c7R219 (where language/tone is already mentioned)

**Comment by moT01** [comment]
In general, I agree. I looked through many of the hints I have added to my tutorials and I don't use "you" that much. But, I'm not sure if setting a rule like this in stone is necessary. I do use it often enough, and I think it's fine if you're not blaming the user. These tests are a little different than what I've been doing so maybe it's harder to not imply a mistake from them. Here's a set of hints from one of my lessons:
```
    Use touch file_name to create a file
    Type touch README.md into the terminal and press enter
    Don't try to create the file with another method
    Make sure you are in your sql_reference repo folder
    Enter cd ~/project/sql_reference to go to the folder if you aren't there
```
It uses "you" twice. Here's another set:
```
Use the ALTER TABLE and DROP COLUMN keywords
Here's an example: ALTER TABLE table_name DROP COLUMN column_name;
You dropped a column before with: ALTER TABLE second_table DROP COLUMN age;
Try ALTER TABLE second_table DROP COLUMN username;
Enter psql -U freecodecamp second_database into the terminal to log in if you aren't already
```

**Comment by jasmcaus** [comment]
Sounds good. The language we use directly mirrors how welcoming of a community we are in general - a sentence or two slightly out of place, and you've already got the user on the defense; doubt it'll suggest happy thoughts :)

But as Tom said, it's wise not to set this rule in stone. You can't *not* have 'you's - it makes sense not to include it (or simply rephrasing it) if the general sentiment is at the point of blaming the user.  

Tom's done a great job at adding examples, so I guess the general direction should be finding that "sweet spot", where you're giving the user a 'personality' ("Extend your class "Foo" by adding...." over "Extend the class "Foo") and not explicitly blaming them. Suggestions?

**Comment by ojeytonwilliams** [comment]
Yeah, that makes sense.  I didn't mean to imply that "you" should be banned, so clearly my wording needs work. I think we broadly agree, though. 

I think it's fine (good, in fact) to emphasise that it's their code.  However, I think it's better if we keep the language impersonal when talking about the mistake. 

Just for concreteness, contrast "You should have put a \<div> in your \<main> section." with "There should be a \<div> in your \<main> section.".

**Comment by jasmcaus** [comment]
Agreed. Let's go with that then.

**Review by jasmcaus — APPROVED** [review]

**Comment by moT01** [comment]
Some other thoughts. I looked through a few of the new front end projects ([cat photo app](https://github.com/freeCodeCamp/freeCodeCamp/tree/main/curriculum/challenges/english/01-responsive-web-design/basic-html-cat-photo-app), [cafe menu](https://github.com/freeCodeCamp/freeCodeCamp/pull/41797/files)), seems like almost every hint uses "you". Here's one of them:
```
You should have a closing </p> tag.
assert(code.match(/<\/p>/i));
```
Pretty sure it's valid to have spaces in a closing `p` tag like this: `</ p >`. Which would not pass this test. And the text is sort of blaming it on the user, when it's our test. So I see the dilemma. I'm trying to think of how we might best word something like that more generically. Maybe: ```Make sure you have a closing `p` tag that looks like this: `</p>` ``` - Seems like that test could be better. And it seems very difficult to not put some (implied) blame on the users code. Inevitably, there will be bugs in the tests - but with a perfect test, I wouldn't mind the text that is there. If we can be certain it is the users code and not the test, then I don't really see a problem - although it could be a little softer. ```Make sure there's a closing `p` tag```

**Comment by jasmcaus** [comment]
Tbh I prefer ```Make sure you have a closing `p` tag that looks like this: `</p>` ``` because the sentiment gives the user sort of a 'personality' and added motivation, something you won't quite get from ```Make sure there's a closing `p` tag```. 

If I were the user, I don't think I would have been greatly miffed at the review received (the former statement you mentioned). A *slight* blame is inevitable no matter how perfect the tests are. 

PS: I'm in favour of the inclusion of statements like: ```... should look like ...``` - the user will realise that there is a space in between the brackets, and be able to fix it.

**Comment by ojeytonwilliams** [comment]
So, one quick thing about style guides.  Part of the point of them is to avoid endless debate - so that a reviewer can just say "yeah, it's not that this test is badly worded, it's just not following the style guide".  So, whatever we settle on, it's important that it be unambiguous.

I appreciate that that's not going to be trivial, but if we settle on a few concrete examples, I think it should be doable.  Tricky, but doable.

**Review by moT01 — APPROVED** [review]
Well, I think I would be fine adding this then. The only thing that comes to mind is that it could maybe use a few more examples in there. Not necessary though. I'll leave it for a bit in case anyone else wants to weigh.

**Comment by nhcarrigan** [comment]
I do think the addition of a few more examples would be beneficial.

**Comment by Sembauke** [comment]
So you suggest using passive voice instead of active voice.

Sometimes passive voice is preferred over active voice because it puts emphasis on what was done instead of who did it.

**For example:**

The p-tag should have a closing tag.

(This puts the actor out of the center)

**Comment by nhcarrigan** [comment]
Before I push forward, is [this the style we are looking for](https://github.com/freeCodeCamp/freeCodeCamp/pull/41797/commits/25c1d1cfab4a191963bf4cd161deeef0ac513d36)?

**Comment by ojeytonwilliams** [comment]
> Before I push forward, is [this the style we are looking for](https://github.com/freeCodeCamp/freeCodeCamp/pull/41797/commits/25c1d1cfab4a191963bf4cd161deeef0ac513d36)?

Seems reasonable to me.

@QuincyLarson any thoughts on this?

**Review by raisedadead — APPROVED** [review]

**Comment by raisedadead** [comment]
@nhcarrigan this should be okay to merge?

**Comment by nhcarrigan** [comment]
Ah, forgot about this. 

My understanding was Quincy recommended sticking with the "you" voice.

**Comment by ojeytonwilliams** [comment]
Yeah, that sounds right.  We discussed this briefly in a standup and the argument was that there can be a lot of code on the screen, so saying "your code" makes it obvious that they need to change something.

**Comment by raisedadead** [comment]
So you want to update the PR then?

**Comment by QuincyLarson** [comment]
@raisedadead that's correct. @ojeytonwilliams and I discussed this and we decided to continue to refer to code the user writes as "your code" to remove ambiguity. As such, I am closing this PR.

**Pull request closed without merging**
