### PR TITLE
Added semicolons to calculator.js

### LINKED ISSUE #15237: Missing semi-colon in calculator.js
#### Issue Description

Missing semi-colons on the below lines of file `public/js/calculator.js`:

https://github.com/freeCodeCamp/freeCodeCamp/blob/staging/public/js/calculator.js#L186
https://github.com/freeCodeCamp/freeCodeCamp/blob/staging/public/js/calculator.js#L203
https://github.com/freeCodeCamp/freeCodeCamp/blob/staging/public/js/calculator.js#L246

Note: Beginner friendly only.

### PR DESCRIPTION
**Pull request by AnishHota**
#### Pre-Submission Checklist

- [x] Your pull request targets the `staging` branch of freeCodeCamp.
- [x] Branch starts with either `fix/`, `feature/`, or `translate/` (e.g. `fix/signin-issue`)
- [x] You have only one commit (if not, [squash](http://forum.freecodecamp.com/t/how-to-squash-multiple-commits-into-one-with-git/13231) them into one commit).
- [x] All new and existing tests pass the command `npm test`. Use `git commit --amend` to amend any fixes.

#### Type of Change

- [x] Small bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds new functionality)
- [ ] Breaking change (fix or feature that would change existing functionality)
- [ ] Add new translation (feature adding new translations)

#### Checklist:

- [x] Tested changes locally.
- [x] Closes currently open issue (replace XXXX with an issue no): Closes #15237 

#### Description

This commit adds semicolons to line 186,203,and 246 to calculator.js.This commit doesn't fix a bug as the file will work fine without even adding the semicolons but it maintains the consistency.

### CODE REVIEW

**Comment by raisedadead** [comment]
Thanks for the pull request, but can you please follow the guidelines and remove the issue nos from wherever they are not necessary?

Also, we would want you to update the commit message to be more meaningful.

Here are the places where you should be looking into for help:

1. https://github.com/freeCodeCamp/freeCodeCamp/blob/staging/CONTRIBUTING.md#if-your-pr-is-rejected
2. https://forum.freecodecamp.com/t/writing-good-git-commit-messages/13210

**Comment by raisedadead** [comment]
Do not worry, this is all about getting used to contributing to freeCodeCamp and getting to know our guidelines for that.

Goodluck!

**Comment by AnishHota** [comment]
I made some changes. Should i make any more changes? Your feedback is appreciated.Thank you.

**Comment by raisedadead** [comment]
> Also, we would want you to update the commit message to be more meaningful.

Yes, please follow the comment earlier, on how to amend a commit.

**Comment by raisedadead** [comment]
Your current commit message reads:
> Create calculator.js

That is not relevant, it could be more meaningful like the title of the PR you have for example to make sense of the intent.

**Pull request closed without merging**
