### PR TITLE
fix: a typo - TSL certificate ===> TLS certificate

### PR DESCRIPTION
**Pull request by musiyenko**
Checklist:

- [x] I have read [freeCodeCamp's contribution guidelines](https://contribute.freecodecamp.org).
- [x] My pull request has a descriptive title (not a vague title like `Update index.md`)
- [x] My pull request targets the `master` branch of freeCodeCamp.
- [x] All the files I changed are in the same world language, for example: only English changes, or only Chinese changes, etc.

Closes #XXXXX

### CODE REVIEW

**Comment by ahmadabdolsaheb** [comment]
Thanks for the PR. There seem to be another instance in the Chinese curriculum that needs updating.

**Review by ahmaxed — DISMISSED** [review]

**Comment by musiyenko** [comment]
> Thanks for the PR. There seem to be another instance in the Chinese curriculum that needs updating.

Fixed that one too.

**Comment by RandellDawson** [comment]
@musiyenko Since @ahmadabdolsaheb made his suggestion about the Chinese file, we have implemented a new policy of no longer accepting curriculum-related PRs with changes to non-English files. The other languages will get the translated content from another source in the near future. So can you please revert the change to the Chinese file? Thank you.

**Review by RandellDawson — CHANGES_REQUESTED** [review]
@musiyenko Since @ahmadabdolsaheb made his suggestion about the Chinese file, we have implemented a new policy of no longer accepting curriculum-related PRs with changes to non-English files. The other languages will get the translated content from another source in the near future. So can you please revert the change to the Chinese file? Thank you.

**Comment by RandellDawson** [comment]
@musiyenko Thank you for the quick change.

**Review by RandellDawson — APPROVED** [review]

**Review by naomi-lgbt — APPROVED** [review]
LGTM~! 🥳 

Thank you for your pull request! We look forward to additional contributions!

Please note that we are currently in a code freeze and not merging PRs to curriculum challenges at this time. 🙂

**Comment by RandellDawson** [comment]
Congrats @musiyenko on your first pull request (PR)! 🎉

Thank you for your contribution to the page! 👍
We're happy to accept these changes, and look forward to future contributions. 📝

**Pull request merged**
