### PR TITLE
#39233 insertion sort added sameMember test 

### LINKED ISSUE #39233: Algorithms: Implement Insertion Sort - You can get it to pass even though the algorithm is not correct
https://www.freecodecamp.org/learn/coding-interview-prep/algorithms/implement-insertion-sort

`
function insertionSort(array) {
  for(let i=1; i<array.length; i++){
    let toInsert = array[i];
    let j = i-1;
    while(j >= 0){
      if(toInsert < array[j]){
        array[j+1] = array[j];
      }
      else{
        array[j+1] = toInsert;
        break;
      } 
      j--
    }
    console.log(array)
  }
  return array;
}
insertionSort([5, 4, 33, 2, 8]);
`

Will make the challenge pass even though the code is not correct which my example shows. 

The test in the challenge passes, because by chance the first element in the test array is also the smallest and doesnt have to be changed. So adding a second test array with a first element not being the smallest element would solve that issue.

Browser: Chrome

### PR DESCRIPTION
**Pull request by Azalen**
Checklist:

- [x] I have read [freeCodeCamp's contribution guidelines](https://contribute.freecodecamp.org).
- [x] My pull request has a descriptive title (not a vague title like `Update index.md`)
- [x] My pull request targets the `master` branch of freeCodeCamp.
- [x] All the files I changed are in the same world language, for example: only English changes, or only Chinese changes, etc.

Closes #39233

### CODE REVIEW

**Comment by RandellDawson** [comment]
@Azalen After thinking about it, instead of having another test with the same `text`, why not just modify the existing test's array to achieve the ideal test.

**Comment by nhcarrigan** [comment]
@RandellDawson I had thought about the same `text` concern as well. Would it be better to modify the `text` for both of the tests to specify the function call and intended result, instead?

Otherwise the challenge seed includes the function call for one test but the user won't see the other test call without some extra digging.

**Comment by RandellDawson** [comment]
That is why I suggested just changing the 2nd test array, so that the `1` is not the first element of the array.  For these algorithm challenges, it is not necessary to show the function call and expected result.  At this point in the curriculum, a user should be able to create one's own test cases.  That 2nd test's array is very long, so it would take up a lot of space in the `text`.

Let's get another mod's opinion on the matter.  @scissorsneedfoodtoo @ojeytonwilliams @moT01

**Comment by nhcarrigan** [comment]
I see your point - hadn't considered that, actually, and it makes sense. 
It looks like the same bug is present on the other sort algorithms as well - whichever route we go, we may wish to consider changing the tests on all of them to match. 🙂

**Comment by moT01** [comment]
I would not have a second test with the same text. One should work, and I think the text can stay as is.

**Comment by scissorsneedfoodtoo** [comment]
I agree, modifying the array of the original second test is better than adding a new test with the same text.

**Comment by RandellDawson** [comment]
@Azalen As there has been no response from your end for a while, we are closing this PR.

Feel free to request this PR to be reopened or create a new PR, if you still wish to make the changes you originally added plus any additional change requests asked of you.  Also, remember to update your fork, so you have the latest version of master in case it has changed significantly.

Happy Coding!

**Pull request closed without merging**
