### PR TITLE
Add information about pattern matching

### PR DESCRIPTION
**Pull request by Evaldas22**
Added information about how we can use a switch statement for pattern matching and gave an example from Microsoft docs.

- [x I have read [freeCodeCamp's contribution guidelines](https://github.com/freeCodeCamp/freeCodeCamp/blob/master/CONTRIBUTING.md).
- [x] My pull request has a descriptive title (not a vague title like `Update index.md`)
- [x] My pull request targets the `master` branch of freeCodeCamp.
- [x] None of my changes are plagiarized from another source without proper attribution.
- [x] My article does not contain shortened URLs or affiliate links.

If your pull request closes a GitHub issue, replace the XXXXX below with the issue number.

Closes #XXXXX

### CODE REVIEW

**Review by thecodingaviator — DISMISSED** [review]
Please fix merge conflict

**Comment by RandellDawson** [comment]
@thecodingaviator Is this PR ready to be merged?

**Comment by thecodingaviator** [comment]
@RandellDawson someone with more ecperience in C# would need to look at the code

**Comment by RandellDawson** [comment]
@thecodingaviator This code is taken directly from https://docs.microsoft.com/en-us/dotnet/csharp/pattern-matching

**Review by thecodingaviator — APPROVED** [review]
Looks good to be merged

**Comment by thecodingaviator** [comment]
Thank you for your contribution to the page! 👍
We're happy to accept these changes, and look forward to future contributions. 📝

**Pull request merged**
