### PR TITLE
fix: mobile curriculum test

### PR DESCRIPTION
**Pull request by Nirajn2311**
Checklist:

- [x] I have read and followed the [contribution guidelines](https://contribute.freecodecamp.org).
- [x] I have read and followed the [how to open a pull request guide](https://contribute.freecodecamp.org/#/how-to-open-a-pull-request).
- [x] My pull request targets the `main` branch of freeCodeCamp.
- [x] I have tested these changes either locally on my machine, or GitPod.

### CODE REVIEW

**Review by Sembauke — APPROVED** [review]

**Review by ShaunSHamilton — COMMENTED** [review]
I tried for way too long to get the tests to run, but they just keep timing out - showing `Attempt 1 of 5... 2 of 5...`

The premise of the change makes sense to me.

**Comment by Nirajn2311** [comment]
> I tried for way too long to get the tests to run, but they just keep timing out

That's strange. They shouldn't be doing that. I'll give it a run from my end.

**Review by ojeytonwilliams — APPROVED** [review]
LGTM :+1: 

I think this is only triggered by workflow_dispatch, could you merge and press the button when you're ready @Nirajn2311?

**Comment by ojeytonwilliams** [comment]
Oh, automerge, nevermind. I'll push the button :)

**Comment by ojeytonwilliams** [comment]
@Nirajn2311 this was the result: https://github.com/freeCodeCamp/freeCodeCamp/actions/runs/7571734603/job/20619932550

**Comment by Nirajn2311** [comment]
Yup, it looks good to me. That one error is expected. Thanks

**Pull request merged**
