### PR TITLE
fix(challenges): Change Lesson pane name in navigation

### LINKED ISSUE #16453: Lesson pane should always be called "Lesson" in navigation
On Step challenges, it should be changed from "Step" to "Lesson":

basic_html_and_html5__learn_how_freecodecamp_works___freecodecamp

On System Design Question challenges, it should be changed from "Main" to "Lesson":

system_design_and_concept_questions__array_prototype_map___freecodecamp

### PR DESCRIPTION
**Pull request by warborn**
Lesson pane on Step challenges was changed from "Step" to "Lesson", on
System Design Question challenges was changed from "Main" to "Lesson"

Closes #16453

#### Pre-Submission Checklist

- [x] Your pull request targets the `staging` branch of freeCodeCamp.
- [x] Branch starts with either `fix/`, `feature/`, or `translate/` (e.g. `fix/signin-issue`)
- [x] You have only one commit (if not, [squash](http://forum.freecodecamp.org/t/how-to-squash-multiple-commits-into-one-with-git/13231) them into one commit).
- [x] All new and existing tests pass the command `npm test`. Use `git commit --amend` to amend any fixes.

#### Type of Change

- [x] Small bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds new functionality)
- [ ] Breaking change (fix or feature that would change existing functionality)
- [ ] Add new translation (feature adding new translations)

#### Checklist:

- [x] Tested changes locally.
- [x] Addressed currently open issue (replace XXXXX with an issue no in next line)

Closes #16453

#### Description

Lesson pane name on Step challenges was changed from "Step" to "Lesson" and on System Design Question challenges was changed from "Main" to "Lesson"

### CODE REVIEW

**Comment by raisedadead** [comment]
Hi @warborn thanks for the pull request, however there is a previous currently in QA PR by @no-stack-dub-sack tackling this.

We unfortunately may have to close this, if its merged there. 
We sincerely thank you for taking the time to prepare this, and look forward to help on other open issues.

Thanks a lot, happy contributing.

Tagging as blocked and updating the same in the related PR.

**Comment by BerkeleyTrue** [comment]
fixed in 62e079c7215fc13296e934ff304b6894e4a45dca

**Comment by BerkeleyTrue** [comment]
Reopening this. We should update the step challenge panesMap to say Lesson instead of Step

**Comment by BerkeleyTrue** [comment]
@warborn Thanks for the PR. This makes the nav buttons more consistent.

Happy Coding

**Pull request merged**
