### PR TITLE
Removed extra word from the description of bootstrap Waypoint: Use Spans for Inline Elements

### PR DESCRIPTION
**Pull request by srodman7689**
This Pull Request Closes Issue #2636.

### CODE REVIEW

**Comment by BerkeleyTrue** [comment]
Please change the title to be descriptive of the changes you have made.

Also state which issues, if any, that this PR closes in the description each on its own line. For example: `closes #1337`

**Comment by srodman7689** [comment]
Is this more like what I should have? I read a commit style guide from someone else but I don't think I fully grasped what is needed. If there is anything else I need to change or anything I need to read to do this correctly please let me know.

**Comment by BerkeleyTrue** [comment]
Yes that is acceptable for now.

See: https://github.com/FreeCodeCamp/FreeCodeCamp/wiki/Pull-Request-Contribute

Thanks for the PR. Happy Coding!

**Comment by srodman7689** [comment]
Thank you!

**Pull request merged**
