### PR TITLE
Update index.md

### PR DESCRIPTION
**Pull request by swetaprajapati**
- [x] I have read [freeCodeCamp's contribution guidelines](https://github.com/freeCodeCamp/freeCodeCamp/blob/master/CONTRIBUTING.md).
- [x] My pull request has a descriptive title (not a vague title like `Update index.md`)
- [x] My pull request targets the `master` branch of freeCodeCamp.
- [x] None of my changes are plagiarized from another source without proper attribution.
- [x] My article does not contain shortened URLs or affiliate links.

If your pull request closes a GitHub issue, replace the XXXXX below with the issue number.

Closes #XXXXX

### CODE REVIEW

**Comment by ArielLeslie** [comment]
You ignored a list of requirements including "My pull request has a descriptive title (not a vague title like `Update index.md`)". Descriptive titles and good explanations of changes are necessary for a well maintained codebase. Free Code Camp is choosing to relax some of its requirements to help people reach their Hacktoberfest goals, but this PR would normally be rejected. In the future, please help repository maintainers by providing useful titles and do not ignore contributing guidelines or requirements.

**Comment by RandellDawson** [comment]
Closed and Reopened this PR to attempt to resolve a specific Travis build failure.

**Review by theNaut1lus — COMMENTED** [review]
@swetaprajapati 
Seems like the changes you are adding is not original content and seems to have been picked up from external sources. At FCC, it is encouraged to write original content.
 
So for this reason, this PR is to be closed. 🥇
 
external src: https://www.geeksforgeeks.org/boundary-fill-algorithm/
 
@RandellDawson: Please close this PR. adds content from external source

**Comment by RandellDawson** [comment]
@swetaprajapati Expanding on what @co16353sidak has stated above.  You must properly cite a source when using verbiage directly from it.  See the [Attributions](https://github.com/freeCodeCamp/freeCodeCamp/blob/master/docs/style-guide-for-guide-articles.md#attributions) sections of our Styling Guide.

**Comment by RandellDawson** [comment]
As there has been no response from your end for a while, we are closing this PR.

Feel free to request this PR to be reopened or create a new PR, if you still wish to make the changes you originally added plus any additional change requests asked of you.  Also, remember to update your fork, so you have the latest version of master in case it has changed significantly.

Happy Coding!

**Pull request closed without merging**
