### PR TITLE
feat: add copyright to footer

### PR DESCRIPTION
**Pull request by anthonykyi**
- [x] I have read [freeCodeCamp's contribution guidelines](https://github.com/freeCodeCamp/freeCodeCamp/blob/master/CONTRIBUTING.md).
- [x] My pull request has a descriptive title (not a vague title like `Update index.md`)
- [x] My pull request targets the `master` branch of freeCodeCamp.
- [x] None of my changes are plagiarized from another source without proper attribution.
- [x] All the files I changed are in the same world language (for example: only English changes, or only Chinese changes, etc.)
- [x] My changes do not use shortened URLs or affiliate links.

### CODE REVIEW

**Comment by raisedadead** [comment]
Can you please add a screenshot for confirmation on how this looks, before we QA?

**Comment by scissorsneedfoodtoo** [comment]
Here's a screenshot for review:

image

**Comment by anthonykyi** [comment]
@raisedadead  I just added the copyright sign on the bottom of the footer (shown at the bottom of the screenshot shown by @scissorsneedfoodtoo  )

**Review by raisedadead — APPROVED** [review]
Code LGTM. But @QuincyLarson will have to sign off on this.

**Comment by QuincyLarson** [comment]
@anthonykyi Thank you for opening this pull request. Since many of the pages this content would appear on, we do not have a copyright, we would prefer to leave this off. Note that copyright is not necessary - it is implicit thanks to [the Berne Convention](https://en.wikipedia.org/wiki/Berne_Convention). 

Thank you again for opening this pull request and we look forward to future contributions from you.

**Pull request closed without merging**
