### PR TITLE
Typos y errores de traducción - typos and translation errors

### PR DESCRIPTION
**Pull request by GonzaloGM**
Socket.io is not known as Zócalo.io, so I changed it back. Also fixed some small translation errors.

Socket.io no se conoce como Zócalo.io en español, así que lo volví a cambiar. También corregí otros errores de traducción pequeños.

- [x] I have read [freeCodeCamp's contribution guidelines](https://github.com/freeCodeCamp/freeCodeCamp/blob/master/CONTRIBUTING.md).
- [x] My pull request has a descriptive title (not a vague title like `Update index.md`)
- [x] My pull request targets the `master` branch of freeCodeCamp.
- [x] None of my changes are plagiarized from another source without proper attribution.
- [x] My article does not contain shortened URLs or affiliate links.

If your pull request closes a GitHub issue, replace the XXXXX below with the issue number.

Closes #XXXXX

### CODE REVIEW

**Comment by RandellDawson** [comment]
Added localTitle on user's behalf.  Still needs to be reviewed for translation.

**Comment by GonzaloGM** [comment]
@RandellDawson No translation needed for the localTitle, not sure what the next step is. Thanks for the commit, I was on vacation until recently and forgot about this. I'll check my other PRs.

**Comment by RandellDawson** [comment]
Congrats @GonzaloGM on your first pull request (PR)! 🎉

Thank you for your contribution to the page! 👍
We're happy to accept these changes, and look forward to future contributions. 📝

**Comment by GonzaloGM** [comment]
@RandellDawson thank you so much! :) Just glad to be able to give just a little bit back to freeNodeCamp :)

**Pull request merged**
