### PR TITLE
fix(curriculum):add code example for str.match()  in step 35 of calorie counter project

### LINKED ISSUE #53458: Add code example of intro to `str.match()` step 35 of calorie counter
### Describe the Issue

We should always have a code example when introducing a new concept.

Here is the new updated description for step 35

````md
Strings have a <dfn>.match()</dfn> method, which takes a regex argument. `.match()` will return an array of match results – containing either the first match, or all matches if the global flag is used.

```js
const str = 'example string';
const regex = /example/;
const result = str.match(regex); // Returns ['example']
```

Return the result of calling the `.match()` method on `str` and passing your `regex` variable as the argument. You'll use this match result later on.
````

### Affected Page

https://www.freecodecamp.org/learn/javascript-algorithms-and-data-structures-v8/learn-form-validation-by-building-a-calorie-counter/step-35

### Your code

see explanation above

### Expected behavior

see explanation above

### Screenshots

_No response_

### System

- Device: [e.g. iPhone 6, Laptop]
- OS: [e.g. iOS 14, Windows 10, Ubuntu 20.04]
- Browser: [e.g. Chrome, Safari]
- Version: [e.g. 22]

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by GNUSheep**
Checklist:

- [ x ] I have read and followed the [contribution guidelines](https://contribute.freecodecamp.org).
- [ x ] I have read and followed the [how to open a pull request guide](https://contribute.freecodecamp.org/#/how-to-open-a-pull-request).
- [ x ] My pull request targets the `main` branch of freeCodeCamp.
- [ x ] I have tested these changes either locally on my machine, or GitPod.

Closes #53458 

I dunno is that what u meant but I'll give it try ;)

### CODE REVIEW

**Review by jdwilkin4 — APPROVED** [review]

**Comment by jdwilkin4** [comment]
@GNUSheep 

Whenever you have question about an issue and what is expected in the PR, it is always best to reply back to the original issue and ask clarifying questions. 
That way you make sure your changes are correct with what the maintainers had in mind.

This will come in handy when you start contributing to more complex issues that involve more changes. 👍

**Comment by GNUSheep** [comment]
Okay so everything is all right?

**Comment by GNUSheep** [comment]
> @GNUSheep
> 
> > I dunno is that what u meant but I'll give it try ;)
> 
> Whenever you have questions about an issue and what is expected in the PR, it is always best to reply back to the original issue and ask clarifying questions. That way you make sure your changes are correct with what the maintainers had in mind.
> 
> This will come in handy when you start contributing to more complex issues that involve more changes. 👍

Like I understand what u mean, but it was just copy & paste and check if its look all right. So it seems too easy for me to be a contribution

**Review by JoyShaheb — APPROVED** [review]
@GNUSheep yeah all good ! congrats to your first contribution to our repo, and thank you for your time, keep up the great work 🙏
NOTE : merge it ONLY when all the tests pass please

**Comment by jdwilkin4** [comment]
@GNUSheep 

> So it seems too easy for me to be a contribution

Yeah, some help wanted issues will be that straight forward and easy.
Some involve make small updates to description or tests, while others will require adding more steps and make more complex changes.

For the small updates, I like to open those up for contribution as often as possible because so many people are looking for their start in open source and usually small issues are an easy way to get started 👍

**Pull request merged**
