### PR TITLE
Fix BF Exact Change Tests

### LINKED ISSUE #1409: "Bonfire: Exact Change" needs additional tests
The instinct on this bonfire is to total up all the change in the drawer to determine whether this is greater than the amount required. This will, however, miss the case where you don't have sufficient lower denominations to make change.
```
drawer(17.50, 20.00, [['FIVE', 25.00], ['TEN', 20.00], ['TWENTY', 60.00], ['ONE HUNDRED', 100.00]]);
```
In this case, we have a total of $205.00 available, but we can't make correct change for $2.50. A test should be written to check for a return value of 'Insufficient Funds' in this case.

### PR DESCRIPTION
**Pull request by arialaurel**
Added a test case for when the smallest denomination of change available is larger than the total change required.

Closes #1409

### CODE REVIEW

**Comment by ahstro** [comment]
Thank you for this, but you need to add a large value as well, e.g. `ONE HUNDRED`, to make sure that the code written says `Insufficient Funds` even if there is enough money, just not enough change.

**Comment by ltegman** [comment]
The test case I included should only return `.5` of change and the available dollar in the drawer is valued at `1.00` so I think this should correctly test the case where the value of the total change is high enough but the denomination is too high and should return `Insufficient Funds`. I'm happy to change the case though if you think that's not correct.

**Comment by ahstro** [comment]
Oh, duh, my brain is apparenlty mush. My code worked, but I didn't think it was supposed to.. Let me do some more testing.

**Comment by ahstro** [comment]
Didn't expect my old code to work, I guess I just wrote better code than I though back when I solved this. Thank you :)

**Pull request merged**
