### PR TITLE
fix(client): update breadcrumb navigation

### PR DESCRIPTION
**Pull request by ahmaxed**

### CODE REVIEW

**Comment by ahmadabdolsaheb** [comment]
How it looks now.
image

Things are still blending in and crowded mobile view.
image

Since it is a non-essential feature, I was wondering if we should hide breadcrumbs on mobile. thoughts?

**Comment by raisedadead** [comment]
> Since it is a non-essential feature, I was wondering if we should hide breadcrumbs on mobile. thoughts?

I think we could add a link back to the block, because users are most likely to go back to that.

**Comment by ahmadabdolsaheb** [comment]
Is this better, @raisedadead?

Screen Shot 2021-02-03 at 7 35 05 PM

**Comment by raisedadead** [comment]
Yes.

**Pull request merged**
