### PR TITLE
fix(learn): reword incorrect line reference in React render conditionally from props

### LINKED ISSUE #39741: React: Render Conditionally from Props Incorrect Line Reference
The challenge seed has since been updated, and this paragraph is _out of line_ 😉 
> First, you'll need a simple expression that randomly returns a different value every time it is run. You can use `Math.random()`. This method returns a value between 0 (inclusive) and 1 (exclusive) each time it is called. So for 50/50 odds, use `Math.random() >= .5` in your expression. Statistically speaking, this expression will return true 50% of the time, and false the other 50%. On line 30, replace the comment with this expression to complete the variable declaration.

This should be reworded to not make a line reference.

I suggest:
> ...Statistically speaking, this expression will return true 50% of the time, and false the other 50%. In the `render` method, replace `null` with the above expression to complete the variable declaration.

---
Challenge: https://www.freecodecamp.org/learn/front-end-libraries/react/render-conditionally-from-props

### PR DESCRIPTION
**Pull request by HaramanJohal**
Checklist:

- [x] I have read [freeCodeCamp's contribution guidelines](https://contribute.freecodecamp.org).
- [x] My pull request has a descriptive title (not a vague title like `Update index.md`)
- [x] My pull request targets the `master` branch of freeCodeCamp.
- [x] All the files I changed are in the same world language, for example: only English changes, or only Chinese changes, etc.

Closes #39741

I also changed the russian.md file as it had the same line reference. Happy to adjust if anything is incorrect

### CODE REVIEW

**Review by ShaunSHamilton — CHANGES_REQUESTED** [review]
Thank you, for getting this PR out.

However, there is this line in the checklist:
> All the files I changed are in the same world language, for example: only English changes, or only Chinese changes, etc.

The idea is, we can only review one language at a time, except for previously agreed on circumstances.

Please remove the Russian changes from this PR. I am not sure why the Russian md file is English, but I assume it will be changed completely, so any curriculum changes should be reserved for the english side, for now. Cheers

**Comment by HaramanJohal** [comment]
> Thank you, for getting this PR out.
> 
> However, there is this line in the checklist:
> 
> > All the files I changed are in the same world language, for example: only English changes, or only Chinese changes, etc.
> 
> The idea is, we can only review one language at a time, except for previously agreed on circumstances.
> 
> Please remove the Russian changes from this PR. I am not sure why the Russian md file is English, but I assume it will be changed completely, so any curriculum changes should be reserved for the english side, for now. Cheers

Yeah that's fair enough, will do. I only changed it because it's in English right now so wasn't sure if I should keep it up to date.

**Review by ShaunSHamilton — APPROVED** [review]
This LGTM 👍 

Thank you, for making that change HaramanJohal.

**Review by RandellDawson — APPROVED** [review]

**Comment by RandellDawson** [comment]
Congrats @HaramanJohal on your first pull request (PR)! 🎉

Thank you for your contribution to the page! 👍
We're happy to accept these changes, and look forward to future contributions. 📝

**Pull request merged**
