### PR TITLE
Revert "fix: replace navigate with hardgoto in showUser"

### PR DESCRIPTION
**Pull request by ahmaxed**
Reverts freeCodeCamp/freeCodeCamp#37363

### CODE REVIEW

**Comment by raisedadead** [comment]
The navigations should be handled outside of the component lifecycles gracefully.

**Comment by ojeytonwilliams** [comment]
Did my PR break something?

**Comment by raisedadead** [comment]
> Did my PR break something?

The component lifecycle and the navigation are tightly coupled in some cases, going to /donate for example.

Where we try to navigate away to `api.freecodecamp.org/signin` before react has done its thing.

Needs to be decoupled and handled gracefully.

**Comment by raisedadead** [comment]
To be clear, your original PR's logic is still needed.

**Pull request closed without merging**
