### PR TITLE
fix(curriculum): iterate with javascript do...while loops

### LINKED ISSUE #35110: Iterate with JavaScript Do…While Loops
**Describe your problem and how to reproduce it:**
The description of the problem and the solution that passes are not the same.  The code that passes this section would give you the wrong answer to the instructions.  write the proper code for the instructions and it will not pass.  try it.

**Add a Link to the page with the problem:**
https://learn.freecodecamp.org/javascript-algorithms-and-data-structures/basic-javascript/iterate-with-javascript-do---while-loops

**Tell us about your browser and operating system:**
* Browser Name: CHROME
* Browser Version: Version 71.0.3578.98
* Operating System: OSX

**If possible, add a screenshot here (you can drag and drop, png, jpg, gif, etc. in this box):**

### PR DESCRIPTION
**Pull request by Fordco**
- [x] I have read [freeCodeCamp's contribution guidelines](https://github.com/freeCodeCamp/freeCodeCamp/blob/master/CONTRIBUTING.md).
- [x] My pull request has a descriptive title (not a vague title like `Update index.md`)
- [x] My pull request targets the `master` branch of freeCodeCamp.
- [x] None of my changes are plagiarized from another source without proper attribution.
- [x] All the files I changed are in the same world language (for example: only English changes, or only Chinese changes, etc.)
- [x] My changes do not use shortened URLs or affiliate links.

Closes #35110

### CODE REVIEW

**Comment by RandellDawson** [comment]
@Fordco 
Two comments:
1. I would flip the words so that `only` comes before `push` to make it more readable.

2. I noticed you also are trying to change another challenge with changes that are identical to what the `master` branch currently has.  Can you revert the changes to that file on your branch (`git checkout filename` and then commit/push your changes back to this PR?

**Review by RandellDawson — CHANGES_REQUESTED** [review]
See my comment.

**Review by theNaut1lus — COMMENTED** [review]
What is the status of this PR? @Fordco.

**Comment by Fordco** [comment]
I made some mistakes on this pull request and didn't know how to undo them. I tried to recommit to this pull request with the correct fix but accidentally made a new pull request. Is there a way to connect that commit/PR to this one?

**Comment by RandellDawson** [comment]
@Fordco Can you confirm the new PR #35214 should replace this current one here and I can close this one?  If so, you should update PR #35214's body and change the `Closes` to the issue and not this PR number.

**Comment by Fordco** [comment]
@RandellDawson  I confirm PR #35214  replaces this one. I changed the `Closes` to the issue number as well.

**Comment by RandellDawson** [comment]
OK, then I am closing this one.

**Pull request closed without merging**
