### PR TITLE
fix(challenge): Cleaner assertion for "Copy an Array with slice()".

### PR DESCRIPTION
**Pull request by Greenheart**
#### Pre-Submission Checklist

- [x] Your pull request targets the `staging` branch of freeCodeCamp.
- [x] Branch starts with either `fix/`, `feature/`, or `translate/` (e.g. `fix/signin-issue`)
- [x] You have only one commit (if not, [squash](http://forum.freecodecamp.com/t/how-to-squash-multiple-commits-into-one-with-git/13231) them into one commit).
- [x] All new and existing tests pass the command `npm test`. Use `git commit --amend` to amend any fixes.

#### Type of Change

- [x] Small bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds new functionality)
- [ ] Breaking change (fix or feature that would change existing functionality)
- [ ] Add new translation (feature adding new translations)

#### Checklist:

- [x] Tested changes locally.
- [ ] Closes currently open issue (replace XXXX with an issue no): Progress towards #13110 

#### Description

Improve a test case. As this challenge doesn't function properly because of the remaining tasks in #13110, this was tested by evaluating the assertion in a browser console, against a string containing the valid solution.
proof

### CODE REVIEW

**Comment by no-stack-dub-sack** [comment]
@Greenheart so this challenge still passes with this solution, you just still get the React error, right?

**Comment by Greenheart** [comment]
@no-stack-dub-sack It doesn't work properly at the moment. I suspect it's because of the React error.

**Comment by no-stack-dub-sack** [comment]
@Greenheart That's odd - same challenge on the beta side does not produce the same error

**Comment by Greenheart** [comment]
@no-stack-dub-sack Either, this branch has gotten additional patches that beta doesn't have - or my code simply is incorrect :smile:

I'd say we can wait with this one for a few days and see if it works to rebase this on top of more recent changes.

**Comment by erictleung** [comment]
@Greenheart are you still getting React errors? I pulled this down and ran the solution with no issues. Anything I should be looking for? The only odd thing I see is this large space where the `<hr>` should be.

image

The errors I get are font loading errors, which is a different issue.

**Comment by Greenheart** [comment]
@erictleung Now it works for me!

The `<hr>` is there as well. I'd say this is ready now :blush:

**Comment by erictleung** [comment]
@Greenheart mmm and the `<hr>` came out of hiding for me too!

image

So LGTM! 👍  Thanks for all the PRs!

**Comment by Greenheart** [comment]
@erictleung Haha that's good to hear! Maybe it was just afraid of mondays... 

And thanks yourself, no problem! :smiley:

**Pull request merged**
