### PR TITLE
feat(learn): Add Basic CSS Cafe Menu practice project instructions and hints/tests (v7)

### PR DESCRIPTION
**Pull request by RandellDawson**
Checklist:

- [x] I have read [freeCodeCamp's contribution guidelines](https://contribute.freecodecamp.org).
- [x] My pull request has a descriptive title (not a vague title like `Update index.md`)
- [x]  My pull request targets the `master` branch of freeCodeCamp.
- [x] All the files I changed are in the same world language, for example: only English changes, or only Chinese changes, etc.

This PR updates the first CSS project (Cafe Menu) in the project-based curriculum.

### CODE REVIEW

**Comment by RandellDawson** [comment]
Closing to make the PR a draft.

**Comment by raisedadead** [comment]
You can toggle a PR to draft too :)

**Comment by RandellDawson** [comment]
@raisedadead For some reason, I could not figure out how to do it.

**Comment by ojeytonwilliams** [comment]
It should say 'Still in progress?' in the top right, followed by a clickable 'Convert to draft'

**Pull request closed without merging**
