### PR TITLE
feat: delete lockCode saga

### PR DESCRIPTION
**Pull request by ahmaxed**
This is a GPT-4 experiment where I fed it similar saga files for context and ask it to replace the epic file with saga.

Checklist:

- [x] I have read [freeCodeCamp's contribution guidelines](https://contribute.freecodecamp.org).
- [x] My pull request has a descriptive title (not a vague title like `Update index.md`)
- [x] My pull request targets the `main` branch of freeCodeCamp.
- [x] I have tested these changes either locally on my machine, or GitPod.

Closes #XXXXX

### CODE REVIEW

**Comment by ShaunSHamilton** [comment]
Ahmad, I thought we discussed (years ago) replacing sagas **for** epics? Not the other way around?

**Comment by ahmadabdolsaheb** [comment]
When updateFile action runs in the editor: [updateFile](https://github.com/freeCodeCamp/freeCodeCamp/blame/main/client/src/templates/Challenges/classic/editor.tsx#L835)

**Comment by Sboonny** [comment]
Can you ask it to turn it to TypeScript as well?

**Review by ojeytonwilliams — CHANGES_REQUESTED** [review]
Hey @ahmadabdolsaheb, it looks to me like `isCodeLocked` is always `false`. So, can we just get rid of it entirely?

**Comment by ahmadabdolsaheb** [comment]
@ojeytonwilliams, that makes sense.

**Review by ojeytonwilliams — APPROVED** [review]
LGTM :+1:

**Review by raisedadead — APPROVED** [review]

**Pull request merged**
