### PR TITLE
fix(curriculum): typos in Beta Colored Markers section

### PR DESCRIPTION
**Pull request by Kernix13**
Checklist:

- [x] I have read [freeCodeCamp's contribution guidelines](https://contribute.freecodecamp.org).
- [x] My pull request has a descriptive title (not a vague title like `Update index.md`)
- [x] My pull request targets the `main` branch of freeCodeCamp.
- [x] I have tested these changes either locally on my machine, or GitPod.

Step 22 Remove word: removed "a" from before the word "values"
Step 80 Add word & change words: added "you" before "can also go with" in the second sentence and replaced "go with" to "use"
Step 88 Remove character: removed the comma after 5px for the blur radius
Step 89 Remove character: removed the comma after 0 for the blur radius

### CODE REVIEW

**Review by gikf — CHANGES_REQUESTED** [review]
Looks like commit from other PR (Camper Cafe) made into here, it will need to be removed from this PR before merging.

**Comment by Kernix13** [comment]
What do you mean by 

> Looks like commit from other PR (Camper Cafe) made into here, it will need to be removed from this PR before merging.

I pushed that from a different branch? You can only work on one branch at a time? How did the two become merged and how do I remove one of them? I did the Camper CAfe PR first, so shouldn't the Marger PR be removed? I am new to contributing so I don't know what I'm supposed to do here.

**Comment by gikf** [comment]
You might have inadvertently created this branch based off the `fix/campercafe-typos` branch, instead off the `main`. 

One way to resolve this could be using interactive rebasing in git. Let me know if you'd need more detailed guidelines how to do that.

**Comment by Kernix13** [comment]
I definitely do not know what rebasing is. 

So you think it is my fault? That I was in my campercafe branch when I created the marker branch? I could have been because I did not know that you always have to be in/on the main branch when you create a branch. Is that what you need to do - be in main/master when you create a branch? I'll make sure of that from here on.

What would be quicker and easier for me to fix this? Learn "rebasing" or delete my branch and the push associated with it and start over? I know how to delete a branch but I do not know how to delete my commit and/or the PR. What do you think?

**Comment by gikf** [comment]
Unless in the command creating branch is added another parameter - branch, on which new one should be based - used is branch as a base is the one currently checked out.

---

I won't say it will be easier, but I'd recommend trying out interactive rebase. While it may sound overwhelming at first, the actions needed in this case are rather straightforward, and may be a nice way to get a bit more familiar with git.

To give a brief rundown:
- Use git's interactive rebase to remove unwanted commit from the branch.
- Push branch to your fork, to update PR, with `--force` option, as we are changing branch history here.

If you'd got stuck or would need some assistance, you can join us in [our chat room](https://chat.freecodecamp.org/channel/contributors) or [the forum](https://forum.freecodecamp.org/c/contributors/3). My username there is "sanity". Or let me know here, and I'll give you detailed guidelines what exactly should be done and how.

**Comment by Kernix13** [comment]
Would this do it:

```
git rebase main fix/coloredmarkers-typos
git push origin main --force
```

**Comment by gikf** [comment]
That won't do it. Interactive rebase is done with `rebase -i [commit/branch]` the commit/branch should be what you want to rebase on - here it can be commit just before first your commit on this branch.

**Comment by Kernix13** [comment]
Well I know the branch but what do I use for the commit in what you have: `[commit/branch]`? And is that all? I just signed into the chat room...

**Review by gikf — APPROVED** [review]
LGTM :+1:

**Comment by Kernix13** [comment]
Oh yeah? So no problems and I have to wait for approvals or changes? Sounds good - thanks again!

**Review by ejcheng — APPROVED** [review]

**Review by jdwilkin4 — APPROVED** [review]
LGTM! 👍

**Pull request merged**
