### PR TITLE
fix(curriculum): userDataSongs is not highlighted

### LINKED ISSUE #52805: Music Player step #67: userData.songs is not highlighted
### Describe the Issue

for the #67 step 2023-12-28 190405

As can be seen on the picture, in the instructions for the step, the last mentioning of `userData.songs` is not highlighted like other variables, method names etc. usually are. Examples on the picture would be `filter()` or `song.id`. 

### Affected Page

https://www.freecodecamp.org/learn/javascript-algorithms-and-data-structures-v8/learn-basic-string-and-array-methods-by-building-a-music-player/step-67

### Your code

```



```

### Expected behavior

`useData.songs` at the very end of the instructions should be highlighted.

### Screenshots

_No response_

### System

- Device: Laptop
- OS: Windows 10
- Browser: Chrome
- Version: [e.g. 22]

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by iprime2**
Checklist:

- [x] I have read and followed the [contribution guidelines](https://contribute.freecodecamp.org).
- [x] I have read and followed the [how to open a pull request guide](https://contribute.freecodecamp.org/#/how-to-open-a-pull-request).
- [x] My pull request targets the `main` branch of freeCodeCamp.
- [x] I have tested these changes either locally on my machine, or GitPod.

Closes #52805

### CODE REVIEW

**Review by huyenltnguyen — COMMENTED** [review]
Hey @iprime2, thank you for the PR.

There are a couple things you need to do in order for the PR to be ready for review:
- The PR title needs to be updated to follow our convention: https://contribute.freecodecamp.org/#/how-to-open-a-pull-request?id=prepare-a-good-pr-title
- Review the checkboxes in the PR description and tick off items that you have done (I think you accidentally removed those so I just added them back)

**Review by huyenltnguyen — APPROVED** [review]

**Review by gikf — APPROVED** [review]

**Comment by gikf** [comment]
Hi @iprime2. Congrats on your first pull request (PR)! 🎉

Thank you for your contribution to the page! 👍
We are happy to accept these changes and look forward to future contributions. 📝

**Comment by iprime2** [comment]
Hi @gikf @huyenltnguyen  Thanks for merging my pull request.
I hope I can fix the issues as much as I can.
So many pull requests will be coming in the future.

**Comment by iprime2** [comment]
Hi! @gikf @huyenltnguyen 
I think this fix is still not solved.
I have to also make changes in other language files I forgot to do that. Sorry about that.

**Pull request merged**
