### PR TITLE
Fix test checking for a valid <input> tag in placeholder input challenge

### LINKED ISSUE #8443: Add Placeholder Text to a Text Field challenge syntax error
screenshot 4
placeholder challenge

Challenge [Add Placeholder Text to a Text Field](https://www.freecodecamp.com/challenges/add-placeholder-text-to-a-text-field#?solution=%0A%3Clink%20href%3D%22https%3A%2F%2Ffonts.googleapis.com%2Fcss%3Ffamily%3DLobster%22%20rel%3D%22stylesheet%22%20type%3D%22text%2Fcss%22%3E%0A%3Cstyle%3E%0A%20%20.red-text%20%7B%0A%20%20%20%20color%3A%20red%3B%0A%20%20%7D%0A%0A%20%20h2%20%7B%0A%20%20%20%20font-family%3A%20Lobster%2C%20Monospace%3B%0A%20%20%7D%0A%0A%20%20p%20%7B%0A%20%20%20%20font-size%3A%2016px%3B%0A%20%20%20%20font-family%3A%20Monospace%3B%0A%20%20%7D%0A%0A%20%20.thick-green-border%20%7B%0A%20%20%20%20border-color%3A%20green%3B%0A%20%20%20%20border-width%3A%2010px%3B%0A%20%20%20%20border-style%3A%20solid%3B%0A%20%20%20%20border-radius%3A%2050%25%3B%0A%20%20%7D%0A%0A%20%20.smaller-image%20%7B%0A%20%20%20%20width%3A%20100px%3B%0A%20%20%7D%0A%3C%2Fstyle%3E%0A%0A%3Ch2%20class%3D%22red-text%22%3ECatPhotoApp%3C%2Fh2%3E%0A%0A%3Cp%3EClick%20here%20for%20%3Ca%20href%3D%22%23%22%3Ecat%20photos%3C%2Fa%3E.%3C%2Fp%3E%0A%0A%3Ca%20href%3D%22%23%22%3E%3Cimg%20class%3D%22smaller-image%20thick-green-border%22%20alt%3D%22A%20cute%20orange%20cat%20lying%20on%20its%20back%22%20src%3D%22https%3A%2F%2Fbit.ly%2Ffcc-relaxing-cat%22%3E%3C%2Fa%3E%0A%3Cp%3EThings%20cats%20love%3A%3C%2Fp%3E%0A%3Cul%3E%0A%20%20%3Cli%3Ecat%20nip%3C%2Fli%3E%0A%20%20%3Cli%3Elaser%20pointers%3C%2Fli%3E%0A%20%20%3Cli%3Elasagna%3C%2Fli%3E%0A%3C%2Ful%3E%0A%3Cp%3ETop%203%20things%20cats%20hate%3A%3C%2Fp%3E%0A%3Col%3E%0A%20%20%3Cli%3Eflea%20treatment%3C%2Fli%3E%0A%20%20%3Cli%3Ethunder%3C%2Fli%3E%0A%20%20%3Cli%3Eother%20cats%3C%2Fli%3E%0A%3C%2Fol%3E%0A%3Cinput%20type%3D%22text%22%0Aplaceholder%3D%22cat%20photo%20URL%22%3E) has an issue.
User Agent is: <code>Mozilla/5.0 (Windows NT 10.0; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/49.0.2623.112 Safari/537.36</code>.
Please describe how to reproduce this issue, and include links to screenshots if possible.

My code:
```html

<link href="https://fonts.googleapis.com/css?family=Lobster" rel="stylesheet" type="text/css">
<style>
  .red-text {
    color: red;
  }

  h2 {
    font-family: Lobster, Monospace;
  }

  p {
    font-size: 16px;
    font-family: Monospace;
  }

  .thick-green-border {
    border-color: green;
    border-width: 10px;
    border-style: solid;
    border-radius: 50%;
  }

  .smaller-image {
    width: 100px;
  }
</style>

<h2 class="red-text">CatPhotoApp</h2>

<p>Click here for <a href="#">cat photos</a>.</p>

<a href="#"><img class="smaller-image thick-green-border" alt="A cute orange cat lying on its back" src="https://bit.ly/fcc-relaxing-cat"></a>
<p>Things cats love:</p>
<ul>
  <li>cat nip</li>
  <li>laser pointers</li>
  <li>lasagna</li>
</ul>
<p>Top 3 things cats hate:</p>
<ol>
  <li>flea treatment</li>
  <li>thunder</li>
  <li>other cats</li>
</ol>
<input type="text"
placeholder="cat photo URL">
```

### PR DESCRIPTION
**Pull request by bcherny**
#### Pre-Submission Checklist

- [x] Your pull request targets the `staging` branch of FreeCodeCamp.
- [x] Branch starts with either `fix/`, `feature/`, or `translate/` (e.g. `fix/signin-issue`)
- [x] You have only one commit (if not, [squash](https://github.com/FreeCodeCamp/FreeCodeCamp/wiki/git-rebase#squashing-multiple-commits-into-one) them into one commit).
- [x] All new and existing tests pass the command `npm run test-challenges`. Use `git commit --amend` to amend any fixes.
#### Type of Change

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] Add new translation (feature adding new translations)
#### Checklist:

- [x] Tested changes locally.
- [x] Closes currently open issue (`Closes #XXXX`): Closes #8443
#### Description

Regex is from http://haacked.com/archive/2004/10/25/usingregularexpressionstomatchhtml.aspx/

### CODE REVIEW

**Comment by bcherny** [comment]
> Do not include issue numbers and following keywords in commit messages.

This seems to contradict 5 here, no? https://github.com/FreeCodeCamp/FreeCodeCamp/blob/staging/CONTRIBUTING.md#common-steps

**Comment by raisedadead** [comment]
@bcherny I have just made a PR to address that. Meanwhile you could simply omit the issue no from commits.

It should rather be in the PR description above (1st message of this thread)

`git commit --amend`
`git push origin --force`

**Comment by raisedadead** [comment]
This looks good to me. Just amend that commit and we can merger this!

**Comment by bcherny** [comment]
@raisedadead Done. FYI, if you merge the PR through Github's GUI, you can squash + merge to set your own commit message.

**Comment by raisedadead** [comment]
Thanks for pointing that out @bcherny!

I don't mean to be rude, but IMHO the [**Contributing Guidelines**](https://github.com/FreeCodeCamp/FreeCodeCamp/blob/staging/CONTRIBUTING.md) are there for a reason.

FYI,
We get to triage a ton of issues and considerably fair amount of PRs everyday. We would rather want contributors to this repo follow what's necessary for us to maintain it. I could have gone ahead and merged the PR anyway, and yes I can go ahead and change the commit message, add the closing tags to the PR description.

But we do need to enforce certain rules. Hence these requests.

I sincerely appreciate the hard work of yours and the time and effort you have put in, but IMHO I am not willing to do any thing extra that should be addressed by the contributors themselves (just because they don't RTFM :laughing: !).

We do enforce this for every contributor including ourselves.
Hope that's taken in a good faith! Have a nice one!

Thanks once again for contributing and apologies if if I have offended you.
Cheers.

PS : You have yet missed the closing tags in the description, never mind I am gonna add that for ya.
PPS : The commit message is still weird, but still never mind I'll accept it.
> Fix test checking for a valid <input> tag in placeholder input challenge **closes**

**Comment by raisedadead** [comment]
#### :sparkles: :sparkles: **LGTM.** :sparkles: :sparkles:

**Pull request merged**
