### PR TITLE
Add content to stub

### PR DESCRIPTION
**Pull request by BTmathic**
Just addition, gave formula and example.

- [x] I have read [freeCodeCamp's contribution guidelines](https://github.com/freeCodeCamp/freeCodeCamp/blob/master/CONTRIBUTING.md).
- [x] My pull request has a descriptive title (not a vague title like `Update index.md`)
- [x] My pull request targets the `master` branch of freeCodeCamp.
- [x] None of my changes are plagiarized from another source without proper attribution.
- [x] My article does not contain shortened URLs or affiliate links.

If your pull request closes a GitHub issue, replace the XXXXX below with the issue number.

Closes #XXXXX

### CODE REVIEW

**Comment by paulywill** [comment]
@BTmathic 

Dwight thanks

**Comment by BTmathic** [comment]
@paulywill Quick question, you guys have labels added to most of my PRs, but I can't see any way to help out and do this while submitting the request in the first place. Can I add the scope: guide label when pulling (a guide article), or is that something only members can do?

**Comment by RandellDawson** [comment]
@BTmathic Great question!  Currently, only mods can add the labels. However, in the near future, a bot will add certain labels like `scope: guide`, `scope: curriculum`, or `scope: guide` along with an applicable `language` label for us.

**Comment by BTmathic** [comment]
Fair enough, thanks for the quick replies!

**Pull request merged**
