### PR TITLE
solved step 59 new js course

### LINKED ISSUE #48865: Step 59 new js course (build an rpg) is missing needed backslashes
### Describe the Issue

Step 59 asks users to copy code from one place to another. However the hint text below is missing the escape backslashes around the word “Store” which were found in the original code being copied. 

Your `update` function should set `text.innerText` to `You are in the town square. You see a sign that says "Store".`.

### Affected Page

curriculum/challenges/english/15-javascript-algorithms-and-data-structures-22/learn-basic-javascript-by-building-a-role-playing-game/62a8b0b5053f16111b0b6b5f.md

### Your code

```

```

### Expected behavior

The hint should say:
Your `update` function should set `text.innerText` to `You are in the town square. You see a sign that says \"Store\".`.

### Screenshots

_No response_

### System

N/A

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by AnshPhirani**
Checklist:

- [x] I have read [freeCodeCamp's contribution guidelines](https://contribute.freecodecamp.org).
- [x] My pull request has a descriptive title (not a vague title like `Update index.md`)
- [x] My pull request targets the `main` branch of freeCodeCamp.
- [x] I have tested these changes either locally on my machine, or GitPod.

Closes #48865

### CODE REVIEW

**Comment by lynxlynxlynx** [comment]
Welcome to FCC and thanks for trying to contribute. This doesn't appear to be correct though — it does not address the issue you linked.

**Comment by AnshPhirani** [comment]
What's wrong here can you explain to me more clearly

**Comment by lynxlynxlynx** [comment]
Well look at the expected behaviour, the issue is well documented. It's not clear at all what you're trying to achieve with your code change and how you came to the conclusion that it fixes the bug and not actually causes further problems.

**Comment by jdwilkin4** [comment]
HI @AnshPhirani ! 

This issue wants you to update the hint text. 

Here is a quote from the original issue:

> Expected behavior
> The hint should say:
> Your update function should set text.innerText to You are in the town square. You see a sign that says \"Store\".



Hope that clears up your confusion.

**Comment by AnshPhirani** [comment]
So in this string 
`You are in the town square. You see a sign that says \"Store\".`
`\"`  is not an escape sequence ?

**Comment by jdwilkin4** [comment]
@AnshPhirani 

> \" is not an escape sequence ?

The issue with your PR is that you have made changes to the wrong section.

This issue is about updating the hint text which is found in this section here 
Screen Shot 2023-01-02 at 12 39 55 AM

It also looks like another contributor starting working on this issue so you can take a look at what they did to better understand the issue
https://github.com/atnakayrus/freeCodeCamp/commit/78ca43575e9f4addb316dc5ce61c4f6c4de3e359

Hope that helps!

**Comment by AnshPhirani** [comment]
@jdwilkin4 I have created a new pull request
please review

**Pull request closed without merging**
