### PR TITLE
Improved challenges and normalized formating

### PR DESCRIPTION
**Pull request by QuincyLarson**

### CODE REVIEW

**Comment by BerkeleyTrue** [comment]
Woot!

**Comment by kennethmath** [comment]
I don't know how I got Here r how anything works all I k.ow is I want a pho.e that don't all jacked up and everybody can't het in it I'm lost whencomes to this stuff sorry a

**Comment by kennethmath** [comment]
C they Chang my text while writing I'm sick of it u can watch it change

**Comment by kennethmath** [comment]
What ever I did it said unable to shorten

**Pull request merged**
