### PR TITLE
misc: correct typo in README.md

### PR DESCRIPTION
**Pull request by knownasnaffy**
Checklist:

- [x] I have read [freeCodeCamp's contribution guidelines](https://contribute.freecodecamp.org).
- [x] My pull request has a descriptive title (not a vague title like `Update index.md`)
- [x] My pull request targets the `main` branch of freeCodeCamp.
- [x] I have tested these changes either locally on my machine, or GitPod.

Changes:
```
... 4 legacy certifications ... , which is still available.
```
->
```
... 4 legacy certifications ... , which are still available. 
```

### CODE REVIEW

**Comment by Sboonny** [comment]
Hey @naffydharni006 

Thank you for opening this pull request.

This is a standard message notifying you that we've reviewed your pull request and have decided not to merge it. We would welcome future pull requests from you.

Thank you and happy coding.

**Comment by Sboonny** [comment]
I have reopened it, because "is" can stand for curriculum or certifications. If it's standing for curriculum, then this isn't a typo.
If it's standing for certifications, then it's a typo

**Comment by naffydharni006** [comment]
Hello @Sboonny
I think it makes more sense when it refers to `certifications` instead of `curriculum`

**Review by ShaunSHamilton — APPROVED** [review]
Thank you for taking the time to contribute. I am happy with this change 👍

**Review by Sboonny — APPROVED** [review]
#### :sparkles: :tada: **AWESOME!** :tada: :sparkles:

 Hi @naffydharni006, thanks for this pull request and for contributing to the code-base for the first time. We are looking forward to more contributions from you in the future.

 Cheers & happy contributing!

**Pull request merged**
