### PR TITLE
Center Testimonial Text

### LINKED ISSUE #12014: Home Page Text Alignment Issue - Chrome
#### Challenge Name

[FreeCodeCamp Home](https://www.freecodecamp.com/)

#### Issue Description

I noticed today that the FreeCodeCamp's home page seems to have a bug in Chrome. In the testimonials section, the text seems to be displaying with `text-align: justify`. However, I opened the page in Safari, and it looked fine. Because I'm unfamiliar with FreeCodeCamp's page hierarchy, I couldn't find the stylesheet that might be affecting this.
#### Browser Information

* Browser Name, Version: Chrome 54.0.2840.98
* Operating System: OS X El Capitan
* Mobile, Desktop, or Tablet: Desktop

#### Your Code

```js
 
 
 
```

### PR DESCRIPTION
**Pull request by hudsontaylor**
#### Pre-Submission Checklist

- [x] Your pull request targets the `staging` branch of FreeCodeCamp.
- [ ] Branch starts with either `fix/`, `feature/`, or `translate/` (e.g. `fix/signin-issue`)
- [x] You have only one commit (if not, [squash](http://forum.freecodecamp.com/t/how-to-squash-multiple-commits-into-one-with-git/13231) them into one commit).
- [x] All new and existing tests pass the command `npm test`. Use `git commit --amend` to amend any fixes.

#### Type of Change

- [x] Small bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds new functionality)
- [ ] Breaking change (fix or feature that would change existing functionality)
- [ ] Add new translation (feature adding new translations)

#### Checklist:

- [x] Tested changes locally.
- [x] Closes currently open issue (replace XXXX with an issue no): Closes #12014

#### Description

This gets rid of the odd white spaces in the testimonials section by just centering the text instead of justifying it.

### CODE REVIEW

**Comment by raisedadead** [comment]
@hudsontaylor thanks a lot for the pull request. ✨ 

We are good to go. Kindly fill in the checklist and amend your commit to removing the issue no. from the commit text.

> This gets rid of the odd white spaces in the testimonials section by just centering the text instead > of justifying it.

For any assistance hit us up on the [Contributors Chat room](https://gitter.im/FreeCodeCamp/Contributors).

Happy fixing!

**Review by raisedadead — CHANGES_REQUESTED** [review]
Code LGTM. Just update the commit message and fill in the checklist.

**Review by raisedadead — APPROVED** [review]

**Comment by raisedadead** [comment]
Can someone merge, since I fixed a commit message via my own commit for the OP. Thanks.

**Comment by erictleung** [comment]
@hudsontaylor LGTM! 👍  Thanks for your contribution to FreeCodeCamp! ✨ 🎉 ✨

**Pull request merged**
