### PR TITLE
Added Pre-Built Theme Sites

### PR DESCRIPTION
**Pull request by anthonyecampbell**
Added pre-built theme websites and added 3 links below the section.

- [x] I have read [freeCodeCamp's contribution guidelines](https://github.com/freeCodeCamp/freeCodeCamp/blob/master/CONTRIBUTING.md).
- [x] My pull request has a descriptive title (not a vague title like `Update index.md`)
- [x] My pull request targets the `master` branch of freeCodeCamp.
- [x] None of my changes are plagiarized from another source without proper attribution.
- [x] My article does not contain shortened URLs or affiliate links.

If your pull request closes a GitHub issue, replace the XXXXX below with the issue number.

Closes #XXXXX

### CODE REVIEW

**Review by CodingSolo — COMMENTED** [review]
two commercial link and an affiliate link

**Comment by moT01** [comment]
Are those not allowed @CodingSolo?

**Comment by CodingSolo** [comment]
@anthonyecampbell for affiliate link (Artisan Themes):
> [  ] My article does not contain shortened URLs or affiliate links.

For commercial Website, you must check with others on gitter. it's just my opinion, but If all sites add their link ...

**Comment by cmccormack** [comment]
Closing this request as it violates the freeCodeCamp [Code of Conduct](https://code-of-conduct.freecodecamp.org/).  Please submit a new PR with the affiliate link(s) removed and we will review for approval.

**Pull request closed without merging**
