### PR TITLE
chore: renovate bot setting to pin actions to a full length commit SHA

### PR DESCRIPTION
**Pull request by naveensrinivasan**
- https://docs.renovatebot.com/modules/manager/github-actions/#additional-information

- Pinned actions by SHA https://github.com/ossf/scorecard/blob/main/docs/checks.md#pinned-dependencies

>Pin actions to a full length commit SHA

>Pinning an action to a full length commit SHA is currently the only way to use an action as an immutable release.
> Pinning to a particular SHA helps mitigate the risk of a bad actor adding a backdoor to the action's repository,
> as they would need to generate a SHA-1 collision for a valid Git object payload.

- https://docs.github.com/en/actions/security-guides/security-hardening-for-github-actions#using-third-party-actions
- https://github.com/renovatebot/.github/blob/b0c3aa85ef2bb242580f20b02b380ca532b4ce17/default.json#L13

### CODE REVIEW

**Review by ojeytonwilliams — COMMENTED** [review]
Thanks a lot @naveensrinivasan this looks useful.

@raisedadead if you like this too, should we update the global config instead of just this repo?

**Comment by ojeytonwilliams** [comment]
> If renovate starts sending update PRs for every commit hash - it would be too noisy for us to handle.

Good point.  @naveensrinivasan do you know if this will change the rate of PRs or just attach the hashes to the PRs it was already going to send?

**Comment by naveensrinivasan** [comment]
> > If renovate starts sending update PRs for every commit hash - it would be too noisy for us to handle.
> 
> Good point. @naveensrinivasan do you know if this will change the rate of PRs or just attach the hashes to the PRs it was already going to send?

It sends one PR for all the hash changes as the first PR to pin all hashes.

**Comment by ojeytonwilliams** [comment]
> It sends one PR for all the hash changes as the first PR to pin all hashes.

Awesome. Then, after that, it will just be the normal number of PRs, but with hashes attached?

**Comment by nhcarrigan** [comment]
> Then, after that, it will just be the normal number of PRs, but with hashes attached?

Just to clarify this:

The current behaviour I have seen with Renovate is:
`actions/setup-node@v2` got updated to `actions/setup-node@v3` when the release was generated.

If we switch to hashes, will we still only get an update when `v4` releases? Or will we get an update on every new commit hash generated on the action's default branch?

**Comment by raisedadead** [comment]
> Or will we get an update on every new commit hash generated on the action's default branch?

If it's this, then we would not be able to keep up with the PRs.

**Review by raisedadead — APPROVED** [review]

**Pull request merged**
