### PR TITLE
Added hints and solutions to Redux exercises

### PR DESCRIPTION
**Pull request by niccololampa**
Added hints and solutions to the following exercises:  

Redux: Use a Switch Statement to Handle Multiple Actions.
Redux: Combine Multiple Reducers

- [x] I have read [freeCodeCamp's contribution guidelines](https://github.com/freeCodeCamp/freeCodeCamp/blob/master/CONTRIBUTING.md).
- [x] My pull request has a descriptive title (not a vague title like `Update index.md`)
- [x] My pull request targets the `master` branch of freeCodeCamp.
- [x] None of my changes are plagiarized from another source without proper attribution.
- [x] My article does not contain shortened URLs or affiliate links.

If your pull request closes a GitHub issue, replace the XXXXX below with the issue number.

Closes #XXXXX

### CODE REVIEW

**Comment by RandellDawson** [comment]
Can you also translate the test section?
```
tests:
  - text: El elemento de tu <code>body</code> debe tener un fondo negro.
    testString: 'assert($("body").css("background-color") === "rgb(0, 0, 0)", "Your <code>body</code> element should have a black background.");'
  - text: Usa <code>rgb</code> para darle a tu <code>body</code> un color negro.
    testString: 'assert(code.match(/rgb\s*\(\s*0\s*,\s*0\s*,\s*0\s*\)/ig), "Use <code>rgb</code> to give your <code>body</code> element a color of black.");'
```

Specifically the parts below:
```
Your <code>body</code> element should have a black background.
```
and 
```
Use <code>rgb</code> to give your <code>body</code> element a color of black.
```

Thank you.

**Comment by niccololampa** [comment]
I don't get what you mean. Can you please expound? 

The code  format is consistent with the other solutions provided in the website.

The edits are plainly for index.md are are plain text/markdown files. 

The styling will be handled elsewhere not in the index.md. 

Thanks. 


> Can you also translate the test section?
> 
> ```
> tests:
>   - text: El elemento de tu <code>body</code> debe tener un fondo negro.
>     testString: 'assert($("body").css("background-color") === "rgb(0, 0, 0)", "Your <code>body</code> element should have a black background.");'
>   - text: Usa <code>rgb</code> para darle a tu <code>body</code> un color negro.
>     testString: 'assert(code.match(/rgb\s*\(\s*0\s*,\s*0\s*,\s*0\s*\)/ig), "Use <code>rgb</code> to give your <code>body</code> element a color of black.");'
> ```
> 
> Specifically the parts below:
> 
> ```
> Your <code>body</code> element should have a black background.
> ```
> 
> and
> 
> ```
> Use <code>rgb</code> to give your <code>body</code> element a color of black.
> ```
> 
> Thank you.

**Comment by RandellDawson** [comment]
Sorry for the confusion.  I have to many windows open.  Your addition looks great!

**Review by RandellDawson — APPROVED** [review]

**Comment by niccololampa** [comment]
> Sorry for the confusion. I have to many windows open. Your addition looks great!

No problem. :). Don't work too hard. Will update other solutions as well. Within the day. Thanks.

**Pull request merged**
