### PR TITLE
fix: Use new Twitter icon

### LINKED ISSUE #51278: Old Twitter Logo
### Describe the Issue

This is a minor issue, the twitter logo on the profile page is that white bird but actually its an "X" symbol so i believe we should change that logo to the latest one.

### Affected Page

https://www.freecodecamp.org/Adarshtx

### Steps to Reproduce

1. Just go on anyone's code camp public profile
2. There you can see the old twitter logo

### Expected behavior

Just expecting a new twitter logo there

### Screenshots

_No response_

### System

- Device: Laptop
- OS: Windows 11
- Browser: Chrome

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by a2937**
Checklist:

- [X] I have read and followed the [contribution guidelines](https://contribute.freecodecamp.org).
- [X] I have read and followed the [how to open a pull request guide](https://contribute.freecodecamp.org/#/how-to-open-a-pull-request).
- [X] My pull request targets the `main` branch of freeCodeCamp.
- [X] I have tested these changes either locally on my machine, or GitPod.

Closes #51278

There isn't a profile page for `developmentuser` but I assume it worked. Everything runs properly.

### CODE REVIEW

**Review by naomi-lgbt — CHANGES_REQUESTED** [review]
The snapshots need to be updated. You should be able to do this by running `pnpm run test-client -u` and committing the resulting changes.

**Comment by a2937** [comment]
Thank you Naomi. I was wondering how to update it.

**Comment by naomi-lgbt** [comment]
> There isn't a profile page for developmentuser but I assume it worked.

There actually is. User profiles are actually a hacky approach using a custom 404 page. When testing locally, you'll see a standard 404 page, with a button that says "Preview custom 404 page". Clicking that will take you to the profile.

**Review by naomi-lgbt — APPROVED** [review]
It pains me to approve this - rip twitter 😭

**Review by raisedadead — APPROVED** [review]

**Pull request merged**
