### PR TITLE
Fixed regex to check if style color is white

### LINKED ISSUE #11226: I had inline style color as green and the test, Give your h1 element the inline style of color: white, passed.
Challenge [Override Class Declarations with Inline Styles](https://www.freecodecamp.com/challenges/override-class-declarations-with-inline-styles#?solution=%0A%3Cstyle%3E%0A%20%20body%20%7B%0A%20%20%20%20background-color%3A%20black%3B%0A%20%20%20%20font-family%3A%20Monospace%3B%0A%20%20%20%20color%3A%20green%3B%0A%20%20%7D%0A%20%20%23orange-text%20%7B%0A%20%20%20%20color%3A%20orange%3B%0A%20%20%7D%0A%20%20.pink-text%20%7B%0A%20%20%20%20color%3A%20pink%3B%0A%20%20%7D%0A%20%20.blue-text%20%7B%0A%20%20%20%20color%3A%20blue%3B%0A%20%20%7D%0A%3C%2Fstyle%3E%0A%3Ch1%20id%3D%22orange-text%22%20class%3D%22pink-text%20blue-text%22%20style%3D%22color%3Agreen%22%3EHello%20World!%3C%2Fh1%3E%0A) has an issue.
User Agent is: <code>Mozilla/5.0 (Windows NT 10.0; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/53.0.2785.143 Safari/537.36</code>.
Please describe how to reproduce this issue, and include links to screenshots if possible.

My code:

``` html

<style>
  body {
    background-color: black;
    font-family: Monospace;
    color: green;
  }
  #orange-text {
    color: orange;
  }
  .pink-text {
    color: pink;
  }
  .blue-text {
    color: blue;
  }
</style>
<h1 id="orange-text" class="pink-text blue-text" style="color:green">Hello World!</h1>

```

### PR DESCRIPTION
**Pull request by tealamore**
#### Pre-Submission Checklist

- [x] Your pull request targets the `staging` branch of FreeCodeCamp.
- [x] Branch starts with either `fix/`, `feature/`, or `translate/` (e.g. `fix/signin-issue`)
- [x] You have only one commit (if not, [squash](http://forum.freecodecamp.com/t/how-to-squash-multiple-commits-into-one-with-git/13231) them into one commit).
- [x] All new and existing tests pass the command `npm run test-challenges`. Use `git commit --amend` to amend any fixes.
#### Type of Change

- [x] Small bug fix (non-breaking change which fixes an issue)
#### Checklist:

- [x] Tested changes locally.
- [x] Closes currently open issue (replace XXXX with an issue no): Closes #11226 
#### Description

Changed previous test from 
`
code.match(/<h1[\\s\\S]*?style[\\s\\S]*?color\\s*?:/gi)
`

to

`
code.match(/<h1[\\s\\S]*?style[\\s\\S]*?color\\s*?:white/gi)
`

### CODE REVIEW

**Comment by WiNloSt** [comment]
I think this would not match the case where there is any space between colon and the world `white`
```html
<h1 style="color: white" ></h1>
```

**Comment by atjonathan** [comment]
@bradarv90, please update your PR with the allowance for space as @WiNloSt mentioned 😄

**Comment by Bouncey** [comment]
@bradarv90 do you have an update on this? 

If you need help with updating the PR, call out to us in [Contributors chat](https://gitter.im/freeCodeCamp/contributors) 👍

**Comment by atjonathan** [comment]
Closing in favor of https://github.com/FreeCodeCamp/FreeCodeCamp/pull/11318, due to inactivity.

**Pull request closed without merging**
