### PR TITLE
Imrpove russian translation in article (React)

### PR DESCRIPTION
**Pull request by plxel**
- [x] I have read [freeCodeCamp's contribution guidelines](https://github.com/freeCodeCamp/freeCodeCamp/blob/master/CONTRIBUTING.md).
- [x] My pull request has a descriptive title (not a vague title like `Update index.md`)
- [x] My pull request targets the `master` branch of freeCodeCamp.
- [x] None of my changes are plagiarized from another source without proper attribution.
- [x] My article does not contain shortened URLs or affiliate links.

This PR only contains language translation enhancements.

### CODE REVIEW

**Comment by greggubarev** [comment]
Hi,

Thanks for this pull request (PR).

Unfortunately, we are marking this PR invalid for hacktoberfest. We believe it does not follow the recommended guidelines:

- Quality Standards
- In line with Hacktoberfest value #2 (Quantity is fun, Quality is key), we have provided examples of the quality standards we encourage. This applies mainly to beginners.
- 
- PRs that are automated e.g. scripted opening PRs to remove white space / optimize images.
- PRs that are disruptive e.g. taking someone else's branch/commits and making a PR.
- PRs that are regarded by a project maintainer as a hindrance vs. helping.
- Something that's clearly an attempt to simply +1 your PR count for October.

Learn more at https://hacktoberfest.digitalocean.com/details

**Comment by plxel** [comment]
@greggubarev 
could you provide more descrptive info why ?

I changed incorrect translation, because nobody called it like this in Russia

**Comment by greggubarev** [comment]
@plxel add more information in this section, and not just change one word. At the moment it's more like 

> Something that's clearly an attempt to simply +1 your PR count for October.

Learn more at https://hacktoberfest.digitalocean.com/details

**Comment by plxel** [comment]
ok, thanks

**Pull request closed without merging**
