### PR TITLE
fix(api): @bable/node is not the part of cli

### PR DESCRIPTION
**Pull request by raisedadead**
IDK why, but I used to get an error while building. Re-installing this seems to fix the error. I also ran `npm audit fix` while I was at it.

### CODE REVIEW

**Comment by ojeytonwilliams** [comment]
Hey @raisedadead.  What wasn't working?  I can't see anything wrong with this, but I don't really know what I'm looking for.

**Comment by raisedadead** [comment]
The error was really cryptic:

```
sh: babel-node: not found
```

All I did was update it to the latest version and ran the `npm audit fix` while I was at it.

**Comment by ojeytonwilliams** [comment]
That is weird.  `babel-node` gets installed when I `npm ci` this branch and seems to work fine (i.e. `npm run babel-dev-server` runs without complaint) on my machine.  

By the way, do you want me to take a look at the audit or is that under control?

**Comment by raisedadead** [comment]
> ...when I `npm ci` this branch and seems to work fine...

That is the point of the fix, unless you meant it works fine on master?

> By the way, do you want me to take a look at the audit or is that under control?

Nope the audit is fine as well. You should merge this if you see the build / dev is fine.

**Comment by ojeytonwilliams** [comment]
> That is the point of the fix, unless you meant it works fine on master?

Yep, it's fine for me on this branch and on master.

> Nope the audit is fine as well. You should merge this if you see the build / dev is fine.

I'm still seeing 4 vulnerabilities (though 3 are dev only) on this branch which couldn't be resolved by `npm audit fix`.

**Comment by raisedadead** [comment]
Hmm, maybe it's down to the binaries for the dependencies that I have for my OS (macOS). I don't think bumping the version is going to hurt (you have already confirmed, it works for you on this branch).

As for the remaining sec issues:

```
~/DEV/freeCodeCamp/api-server fix/add-bable-node
❯ npm audit fix
up to date in 9.477s
fixed 0 of 4 vulnerabilities in 890669 scanned packages
  3 vulnerabilities required manual review and could not be updated
  1 package update for 1 vuln involved breaking changes
  (use `npm audit fix --force` to install breaking changes; or refer to `npm audit` for steps to fix these manually)
```

I get the same checked that these are in the explorer (swagger-ui) and will not be available in production. So we can worry about them later?

**Comment by ojeytonwilliams** [comment]
I'm not worried about the swagger ones either - as you say, they're not used in production.  The one that concerns me is the googleapis package, since that's used in production in the 'About' model.

**Comment by raisedadead** [comment]
Regardless, this PR is not adding to the risk that we already have. The major changes will have to come in a separate PR? Unless you want to address it here? Right now, the build are pretty much broken for me.

**Comment by ojeytonwilliams** [comment]
> Regardless, this PR is not adding to the risk that we already have. The major changes will have to come in a separate PR? 

That's a very good point, I'll stop holding this PR up - I wasn't thinking straight. I'll create an issue about the security updates in a sec.

**Review by ojeytonwilliams — APPROVED** [review]
LGTM :+1:

**Comment by ojeytonwilliams** [comment]
@raisedadead I can't merge this, but it's ready.

**Review by ValeraS — APPROVED** [review]

**Comment by raisedadead** [comment]
Thanks @ojeytonwilliams and @ValeraS !

**Pull request merged**
