### PR TITLE
feat(seed): add css variable challenges

### LINKED ISSUE #16809: [beta] Adding CSS Variables Challenges
@moT01 and I are interested in developing the CSS variables challenges and look forward for your challenge ideas and feedback. 
@QuincyLarson

### PR DESCRIPTION
**Pull request by moT01**
#### Pre-Submission Checklist
- [x] Your pull request targets the `staging` branch of freeCodeCamp.
- [x] Branch starts with either `fix/`, `feature/`, or `translate/` (e.g. `fix/signin-issue`)
- [x] You have only one commit (if not, [squash](http://forum.freecodecamp.org/t/how-to-squash-multiple-commits-into-one-with-git/13231) them into one commit).
- [x] All new and existing tests pass the command `npm test`. Use `git commit --amend` to amend any fixes.

#### Type of Change
- [ ] Small bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds new functionality)
- [ ] Breaking change (fix or feature that would change existing functionality)
- [ ] Add new translation (feature adding new translations)

#### Checklist:
- [x] Tested changes locally.
- [x] Addressed currently open issue (replace XXXXX with an issue no in next line)

Closes #16809 

#### Description
@ahmadabdolsaheb and I created lessons to teach about CSS Variables

@mstellaluna Do you want to QA this one as well? It's the last 7 challenges in the `Basic CSS` section.

### CODE REVIEW

**Comment by mstellaluna** [comment]
@raisedadead I'm on this now.

**Comment by mstellaluna** [comment]
@ahmadabdolsaheb @moT01  I found two issues with the challenges. 
First Issue: 
Challenge:  
http://localhost:3000/en/challenges/basic-css/attach-a-fallback-value-to-a-css-variable

Issue: 
Challenge passes when adding fallback code to any other CSS Variable(s) that are not asked by the challenge

Screenshot: 
image

Second Issue: 

Challenge: 
http://localhost:3000/en/challenges/basic-css/change-a-variable-for-a-specific-area

Issue:
Changing the :root value for --penguin-belly changes the background also. I am not sure if this meant to be this way or not. Please verify.

Screenshot: 
image

**Review by mstellaluna — DISMISSED** [review]
There are two issues with the challenges. Details are provided in the PR.

**Comment by moT01** [comment]
@mstellaluna In the second issue you found - Your picture is from the challenge before the one you link - the cascading one - Changing both to pink is intentional to show how the value cascades down to change the background and the belly and cheeks - I agree that it's not very obvious - Any thoughts on a better way to demonstrate this? We could have it change just the background or just part of the penguin and leave the others alone.  The challenge your talking about (change a specific area) is the one after that - and I had the user change the belly to white there - maybe we could come up with a better demonstration for these two challenges. 

And the first issue looks like a regex problem - good find on that one - probly not a tough fix with a little tweaking.

@ahmadabdolsaheb Any ideas on these?

**Comment by mstellaluna** [comment]
@moT01 if I go to challenge past issue 2 where you change it from pink to white, the background also changes to white... so its all back to normal :)

**Comment by mstellaluna** [comment]
@moT01 okay I re-checked everything for the 2nd issue its fine. you can disregard. As per our convo its intended behavior when you pre-applied the variable to the body of the document to setup for the next lesson.

**Comment by ahmadabdolsaheb** [comment]
@mstellaluna I am not clear on the first issue. If I understood correctly the tests passes when a  fallback is added to a variable in addition to the required variables?

**Comment by moT01** [comment]
hey @mstellaluna what exactly is the 1st issue? I see that it works like this...

You can change the code where you are showing in the picture, but it won't pass the tests unless you also complete what it asks.

I did a little testing and a lot of the other challenges behave this way. I feel like we could ignore this for now, perhaps the ability to change other areas of the code is allowed - I'm not sure. Let me know if you disagree and we can try and come up with something. Otherwise, I think it could just get merged.

**Comment by mstellaluna** [comment]
This PR is pending a secondary review.

**Comment by QuincyLarson** [comment]
@moT01 @ahmadabdolsaheb Thank you for your excellent contribution here, and thanks to @mstellaluna for QA'ing.

I've made some minor copy improvements and merged!

**Comment by randelldawson** [comment]
I noticed something which needs to be corrected on this challenge.  

The default code starts with:
```
  .penguin {
    --penguin-skin: gray;


  .penguin-top {
    top: 10%;
    left: 25%;
  
    /* change code below */
    background: var(--pengiun-skin);
    /* change code above */


  .penguin-bottom {
    top: 40%;
    left: 23.5%;
  
    /* change code below */
    background: var(--pengiun-skin);
    /* change code above */
```
You will notice --penguin-skin is spelled differently in the top and bottom classes, which could be confusing for campers, because they think they only need to add **,black** to the other classes.  

The easiest way to resolve this, would be to simply use the spelling in the .penguin class as follows:
```
  .penguin-top {
    top: 10%;
    left: 25%;
  
    /* change code below */
    background: var(--penguin-skin);
    /* change code above */


  .penguin-bottom {
    top: 40%;
    left: 23.5%;
  
    /* change code below */
    background: var(--penguin-skin);
    /* change code above */
```

**Comment by huyenltnguyen** [comment]
Hi @randelldawson, this PR has already been merged. If there's any bug, I would suggest opening a fresh issue for it.

**Pull request merged**
