### PR TITLE
fix: delete existing users before seeding db

### LINKED ISSUE #40421: Seeded users share an email
In [the scripts to seed the database](https://github.com/freeCodeCamp/freeCodeCamp/tree/master/tools/scripts/seed), the auth user and certified user share an email address. I had them both seeded and could not change any of the settings for the development user - you get an "email uniqueness" error.

One of the email addresses could probably be changed in there.

Edit: On second thought, I bet this is by design so you can log in with either user in development. I'll leave this open for a bit though. Perhaps those scripts could delete the maybe existing user with the same email before seeding.

### PR DESCRIPTION
**Pull request by moT01**
Checklist:

- [x] I have read [freeCodeCamp's contribution guidelines](https://contribute.freecodecamp.org).
- [x] My pull request has a descriptive title (not a vague title like `Update index.md`)
- [x] My pull request targets the `master` branch of freeCodeCamp.
- [x] All the files I changed are in the same world language, for example: only English changes, or only Chinese changes, etc.

Closes https://github.com/freeCodeCamp/freeCodeCamp/issues/40421

### CODE REVIEW

**Review by raisedadead — COMMENTED** [review]
Could we possibly drop the collection instead of deleting individual items? Apologies if I am missing context here.

**Comment by moT01** [comment]
I think I would prefer to just drop the users. I have some other users locally that I use, so those would get deleted if we drop the collection.

**Comment by raisedadead** [comment]
You are right - I did not think about that usecase. Let's leave this PR as is.

**Comment by ojeytonwilliams** [comment]
Also, I'm probably being excessively paranoid, but purging specific records seems safer than wiping the whole collection.

**Review by raisedadead — APPROVED** [review]

**Pull request merged**
