### PR TITLE
feat: save submitted code

### PR DESCRIPTION
**Pull request by SanjoSolutions**
Checklist:

- [X] I have read [freeCodeCamp's contribution guidelines](https://github.com/freeCodeCamp/freeCodeCamp/blob/master/CONTRIBUTING.md).
- [X] My pull request has a descriptive title (not a vague title like `Update index.md`)
- [X] My pull request targets the `master` branch of freeCodeCamp.
- [X] All the files I changed are in the same world language, for example: only English changes, or only Chinese changes, etc.

Keeps submitted code saved instead of deleting it on submit. Use cases:
* User wants to access code later for review or usage elsewhere.

### CODE REVIEW

**Comment by RandellDawson** [comment]
@SanjoSolutions Thank you for opening this pull request.

This is a standard message notifying you that we’ve reviewed your pull request and have decided not to merge it. We would welcome future pull requests from you.

**Reason:**  There is already a PR #38324 working on an option to save the solutions to localStorage.

Thank you and happy coding.

**Comment by SanjoSolutions** [comment]
@RandellDawson This PR does something else than #38324 and is not in conflict with it. All, this PR is doing is removing the deletion of the code when it has been submitted. This behavior was not touched by #38324. So I would appreciate a re-review.

**Comment by RandellDawson** [comment]
@SanjoSolutions I have reopened so some others can provide their opinions.

@moT01 @ojeytonwilliams

**Comment by raisedadead** [comment]
Hi @SanjoSolutions thanks for the PR. 

We have several closed issues regarding storing solutions. We have had discussed this in the past, and I would like to re-iterate that removing the solution once submitted is expected at this point and will not be changing.

The use case you mention is handled using the download solution option durin submit.

I would recommend you to dig thru the threads if you need more context.

Happy Contributing!

**Pull request closed without merging**
