### PR TITLE
remove slice and splice

### PR DESCRIPTION
**Pull request by QuincyLarson**
Complaints are pouring in about this challenge not working (and being a new required challenge). It is my fault that I didn't notice this was being added to the curriculum. We can QA this and add it back in later when we release the curriculum expansion.

Note that the "isBeta" flag is not working, so I removed the challenge completely from the JSON file.

### CODE REVIEW

**Comment by QuincyLarson** [comment]
closes #10615

**Comment by jeffrath504** [comment]
Thank you!

**Comment by BerkeleyTrue** [comment]
@QuincyLarson I've got a PR to fix the beta flag issue. Do we still want to remove this challenge?

**Comment by QuincyLarson** [comment]
@BerkeleyTrue if it will be hidden in production, no need to remove the challenge. We can QA it on beta and launch it with the other new challenges.

**Comment by abhisekp** [comment]
Solving the challenge using only `Array#slice` and `Array#splice` requires the use of loops.
But it can be solved in two other ways which needs to introduce `Array#concat` and `Function#apply`

```js
function frankenSplice(arr1, arr2, n) {
  // It's alive. It's alive!
  return [].splice.apply((arr2 = arr2.slice()), [n, 0].concat(arr1)), arr2;
}
```

or **ES6**
```js
function frankenSplice(arr1, arr2, n) {
  // It's alive. It's alive!
  return (arr2 = [...arr2]).splice(n, 0, ...arr1), arr2;
}
```

// cc @BKinahan

**Pull request closed without merging**
