### PR TITLE
Fix typo and move functions to tail

### LINKED ISSUE #4399: Typo in Waypoint: Reverse Arrays with reverse
There is a typo I found in one of the waypoint challenges.
In the link below, the description says reverse an array and set it to myArray.
But the waypoint is achieved by setting the reversed array to newArray.

http://www.freecodecamp.com/challenges/waypoint-reverse-arrays-with-reverse

### PR DESCRIPTION
**Pull request by aulisius**
Fixes #4399 

I initially started to fix Waypoint: Reverse Arrays and moved the display function to the tail portion. Being a little bit enthusiastic, I moved all the display functions in the other Waypoints to the tail portion.

Note : Didn't test locally.

### CODE REVIEW

**Comment by ltegman** [comment]
Unfortunately the tail calls are actually intentionally being left in the seed for these lessons because of #4228, which causes the page to lockup when a user creates the callback function if the tail call is not in the seed. For now would you mind reverting those changes and just fixing the typo? Sorry about that! Normally the enthusiasm would be well received but this darn bug keeps getting in the way.

**Comment by faizaanceg** [comment]
But [here](https://github.com/FreeCodeCamp/FreeCodeCamp/issues/4399#issuecomment-156315474), @SaintPeter  told me I could move the display function to tail part. Or was it only for that challenge?

**Comment by ltegman** [comment]
For now only that challenge, since `reverse` doesn't require typing `function` because there is no callback involved. All the other functional challenges do require typing `function` though and will lock up :worried:

**Comment by faizaanceg** [comment]
Hmm.. ok. Didn't think about that. Need to setup the dev env. soon instead of being ignorant :/ .

Will remove those changes and leave the `reverse` alone.

**Comment by ltegman** [comment]
Awesome, thank you :smile: Getting FCC setup locally will definitely make things a lot easier on you. Feel free to hit me up on Gitter if you need any help setting it up.

**Pull request merged**
