### PR TITLE
replaced literal translation with no real meaning in PT

### PR DESCRIPTION
**Pull request by lacazeto**
This PR aims to remove the implemented literal translation of `Happy Coding!`, which brought no real meaning and made no sense.

The term `Happy coding!` has no equivalent in Portuguese and cannot be translated as such. In an attempt of fixing that, the term has been replaced by `Bom divertimento!` which means `Have fun!` in Portuguese.   

- [X] I have read [freeCodeCamp's contribution guidelines](https://github.com/freeCodeCamp/freeCodeCamp/blob/master/CONTRIBUTING.md).
- [X] My pull request has a descriptive title (not a vague title like `Update index.md`)
- [X] My pull request targets the `master` branch of freeCodeCamp.
- [X] None of my changes are plagiarized from another source without proper attribution.
- [X] My article does not contain shortened URLs or affiliate links.

If your pull request closes a GitHub issue, replace the XXXXX below with the issue number.

Closes #XXXXX

### CODE REVIEW

**Comment by RandellDawson** [comment]
@lacazeto What if you translated "Have fun coding!" instead?

**Comment by RandellDawson** [comment]
@freeCodeCamp/portuguese-language-editors Can we get this PR reviewed to validate that the translation matches the current English version of the challenge?  If you need help resolving the merge conflict, please let me know.  Thank you.

**Comment by yuricoppe** [comment]
> @lacazeto What if you translated "Have fun coding!" instead?

Maybe `Divirta-se com o código` works

**Review by RandellDawson — APPROVED** [review]
LGTM

**Comment by RandellDawson** [comment]
Congrats @lacazeto on your first pull request (PR)! 🎉

Thank you for your contribution to the page! 👍
We're happy to accept these changes, and look forward to future contributions. 📝

**Pull request merged**
