### PR TITLE
fix(curriculum): add sentence to instructions for clarity

### LINKED ISSUE #43141: Modify instructions for Nest an Anchor Element within a Paragraph challenge
The [Nest an Anchor Element within a Paragraph](https://www.freecodecamp.org/learn/responsive-web-design/basic-html-and-html5/nest-an-anchor-element-within-a-paragraph) comes up a lot in the forum. 

It has come up over 50 times in the past couple of months. 
https://forum.freecodecamp.org/search?q=Challenge%3A%20Nest%20an%20Anchor%20Element%20within%20a%20Paragraph%20after%3A2021-05-01

Most people misunderstand the instructions and create a new anchor tag even though the instructions say to use the existing one. 

Since this is a frequent problem, I think the instructions should be modified to include "Do not create a new anchor tag"
Love to hear your thoughts. 

## Affected page

https://www.freecodecamp.org/learn/responsive-web-design/basic-html-and-html5/nest-an-anchor-element-within-a-paragraph

## Screenshots

Proposed solution

Screen Shot 2021-08-07 at 1 02 40 PM

### PR DESCRIPTION
**Pull request by MChiancone**
Checklist:

- [x] I have read [freeCodeCamp's contribution guidelines](https://contribute.freecodecamp.org).
- [x] My pull request has a descriptive title (not a vague title like `Update index.md`)
- [x] My pull request targets the `main` branch of freeCodeCamp.
- [x] I have tested these changes either locally on my machine, or GitPod.

Closes #43141

### CODE REVIEW

**Comment by ieahleen** [comment]
Would you be willing to do the same for the other challenge mentioned in https://github.com/freeCodeCamp/freeCodeCamp/issues/43141#issuecomment-895159527 ?
Otherwise the PR is ready to review

**Review by raisedadead — DISMISSED** [review]

**Comment by raisedadead** [comment]
@MChiancone We request you do not close or open fresh PRs for no reason. The maintainers spend their valuable time reviewing these. You can leave this PR as is, someone will review and merge this or get back to you with more feedback where needed.

Thanks for your contributions.

**Review by raisedadead — APPROVED** [review]

**Review by majestic-owl448 — APPROVED** [review]
Hi @MChiancone . Congrats on your first pull request (PR)! 🎉

Thank you for your contribution to the page! 👍
We are happy to accept these changes and look forward to future contributions. 📝

Once the tests pass, this will merge automatically. ⌛

**Comment by MChiancone** [comment]
@ieahleen Thanks! It was fun trying to figure all of this out and I look forward to contributing on more difficult issues in the future. @raisedadead Sorry about closing the pull request, that was an accident.  I am still a newbie with git and github.

**Pull request merged**
