### PR TITLE
fix: Can't read buttons on dev 404 page + nightmode

### LINKED ISSUE #36652: [localhost] Can't read buttons on dev 404 page + nightmode
with an instance running locally
go to any user profile url (localhost:8000/anyuser)
it will bring up this page...

Screen Shot 2019-08-20 at 4 12 47 PM

can't read the buttons/search

### PR DESCRIPTION
**Pull request by carlosfrontend**
- [X] I have read [freeCodeCamp's contribution guidelines](https://github.com/freeCodeCamp/freeCodeCamp/blob/master/CONTRIBUTING.md).
- [X] My pull request has a descriptive title (not a vague title like `Update index.md`)
- [X] My pull request targets the `master` branch of freeCodeCamp.
- [X] None of my changes are plagiarized from another source without proper attribution.
- [X] All the files I changed are in the same world language (for example: only English changes, or only Chinese changes, etc.)
- [X] My changes do not use shortened URLs or affiliate links.

Deleted property ~~**color:"inherit";**~~ in  bootstrap.min.css at selector:

**Before**
```
button,input,optgroup,select,textarea{color:inherit;font:inherit;margin:0}
```

**After**

```
button,input,optgroup,select,textarea{font:inherit;margin:0}
```
Closes #36652

### CODE REVIEW

**Comment by raisedadead** [comment]
Thanks for the pull-request @carlosfrontend I think we should override this in the `globals.css`? The file that you have is a build artefact and will be replaced between builds

**Comment by raisedadead** [comment]
Thanks for updating the PR. Can you remove the other changes that is not needed:

```
git checkout upstream/master -- path/to/file
```

**Comment by carlosfrontend** [comment]
> Thanks for updating the PR. Can you remove the other changes that is not needed:
> 
> ```
> git checkout upstream/master -- path/to/file
> ```

I removed unnecesary changes in last commit. Thanks

**Comment by ahmadabdolsaheb** [comment]
LGTM

**Review by raisedadead — APPROVED** [review]

**Comment by carlosfrontend** [comment]
Thanks for arrange the styles @ahmadabdolsaheb and by merge it @raisedadead ! :+1:

**Pull request merged**
