### PR TITLE
fix(curriculum): resolve the duplicate function

### LINKED ISSUE #53624: Learn Basic JavaScript by Building a Role Playing Game - Step 86 - function passed twice
### Describe the Issue

In the JavaScript Algorithms and Data Structures (Beta) series/course Step 86 there is a bug in the locations object.

```
  {
    name: "store",
    "button text": ["Buy 10 health (10 gold)", "Buy weapon (30 gold)", "Go to town square"],
    "button functions": [buyWeapon, buyWeapon, goTown],
    text: "You enter the store."
  }
```

in the "button functions" `buyWeapon` is repeated twice the first one should be `buyHealth`.

### Affected Page

https://www.freecodecamp.org/learn/javascript-algorithms-and-data-structures-v8/learn-basic-javascript-by-building-a-role-playing-game/step-86

### Steps to Reproduce

1. Go to '...' https://www.freecodecamp.org/learn/javascript-algorithms-and-data-structures-v8/learn-basic-javascript-by-building-a-role-playing-game/step-86
2. Click on '...' Go to store button
3. Scroll down to '...'

### Expected behavior

Clicking on the Go to Store button and Buy Health should update the health value but it's not happening because of the correct function is not in place.

### Screenshots

_No response_

### System

- Browser: [e.g. Chrome, Safari]

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by DeanTheReider**
Checklist:

- [x] I have read and followed the [how to open a pull request guide](https://contribute.freecodecamp.org/#/how-to-open-a-pull-request).
- [x] I have read and followed the [contribution guidelines](https://contribute.freecodecamp.org).
- [x] My pull request targets the `main` branch of freeCodeCamp.
- [x] I have tested these changes either locally on my machine, or GitPod.

Closes #53624

This is my first ever pull request and fixed the issue that was detailed in the GitHub case. I utilized a GitPod workspace for this change but I plan on contributing more in the future! Any feedback on how to improve is greatly appreciated.

### CODE REVIEW

**Comment by a2937** [comment]
Hi there. 

You seemed to have attached some changes in your PR that are not related to solving the linked issue. While we appreciate the attempt, this can complicate the review process. We ask you to please discard the unrelated changes. 

Thank you.

**Comment by DeanTheReider** [comment]
Hi,
I accidentally attached another commit to this Pull Request, but I believe that I reverted that commit. Let me know if those changes have been successfully discarded or not.

Thank you!

**Review by gikf — APPROVED** [review]

**Comment by gikf** [comment]
Note for future - it is recommended to make changes on a separate branch, rather than the `main` branch. See more about it in point 3 at https://contribute.freecodecamp.org/#/how-to-contribute-to-the-codebase?id=contributing-to-the-codebase.

**Review by jdwilkin4 — APPROVED** [review]
Congrats on your first contribution to our repository. 🎉
We look forward to future contributions. 👍

**Pull request merged**
