### PR TITLE
fix: transpile api before npm start (in production)

### PR DESCRIPTION
**Pull request by ojeytonwilliams**
This fixes `npm run build` and `npm start` in `api-server`, so that the first transpiles the entire api to `/lib` and the second serves from that directory.

### CODE REVIEW

**Comment by ojeytonwilliams** [comment]
Related to the api tidying efforts started in #40703

**Comment by ojeytonwilliams** [comment]
As far as building goes, the process after this PR should be

```
npm ci
npm run ensure-env
cd curriculum
npm run build
npm ci --production
cd ..
npm ci --production
```

At this point the api should only rely on

```
/api-server/lib
/api-server/node_modules
/utils
/tools
/node_modules
```

and these can be copied over to the Docker image.

I think we will need to adjust the CI to use the images, because people might not realise that they can't couple the api directly to the curriculum or client.

**Comment by scissorsneedfoodtoo** [comment]
Hi @ojeytonwilliams, thanks for your patience. This all looks great and I'm looking forward to the upcoming Dockerization :)

For testing, I tried running through the commands listed in your last comment but ran into a couple of errors. Not sure it's my setup or I'm doing something wrong, or if it's really an issue at all.

After running `npm run clean`, I tried running these command from the root `/freeCodeCamp` directory:

```
npm ci
npm run ensure-env
cd curriculum --> maybe `cd client`?
npm run build
npm ci --production
cd ..
npm ci --production --> at this point I get the error `sh: 1: lerna: not found`
```

Other than that, I ran this in development mode, went through the usual checks, and everything LGTM.

**Comment by ojeytonwilliams** [comment]
Thanks Kris and sorry for the confusion - I rushed this a bit.  I'll make those last fixes (and double-check them!) and give you a shout once I'm confident they work locally.

**Comment by ojeytonwilliams** [comment]
Hey @scissorsneedfoodtoo I've checked this a bit more and the edited process above should work.  After that's run, `npm start` should start the server running in production mode (minus the environment variables, of course).

**Comment by ojeytonwilliams** [comment]
Closed in favour of #40703

**Comment by scissorsneedfoodtoo** [comment]
Hey @ojeytonwilliams, sorry for the delay. I'll check out your new PR :)

**Comment by ojeytonwilliams** [comment]
No worries, take your time.

**Pull request closed without merging**
