### PR TITLE
Update README.md (Fixed TYPO)

### PR DESCRIPTION
**Pull request by BeardedWinter**
Fixed typo in Found a Bug section

- [x] I have read [freeCodeCamp's contribution guidelines](https://github.com/freeCodeCamp/freeCodeCamp/blob/master/CONTRIBUTING.md).
- [x] My pull request has a descriptive title (not a vague title like `Update index.md`)
- [x] My pull request targets the `master` branch of freeCodeCamp.
- [x] None of my changes are plagiarized from another source without proper attribution.
- [x] My article does not contain shortened URLs or affiliate links.

If your pull request closes a GitHub issue, replace the XXXXX below with the issue number.

Closes #XXXXX

### CODE REVIEW

**Comment by honmanyau** [comment]
@QuincyLarson I think this one is okay to be merged!

**Comment by honmanyau** [comment]
Argh! Apologies! I clicked on the wrong button!

**Comment by QuincyLarson** [comment]
@BeardedWinter Thanks for catching this typo and fixing it!

@raisedadead could you address the merge conflict and merge this?

**Comment by raisedadead** [comment]
#### :sparkles: :sparkles: **AWESOME! LGTM.** :sparkles: :sparkles: 

Thanks @BeardedWinter , for this pull request and contributing to the code-base for the first time.
We will be looking forward for more contributions in future.

Cheers and happy contributing!

**Pull request merged**
