### PR TITLE
French Translation for Pig Latin challenge

### LINKED ISSUE #9649: Pig Latin instructions translation - Fr
French language translation for PR #9602

Added text: "Input strings are guaranteed to be English words in all lowercase."

### PR DESCRIPTION
**Pull request by mizujin**
#### Pre-Submission Checklist

- [X] Your pull request targets the `staging` branch of FreeCodeCamp.
- [X] Branch starts with either `fix/`, `feature/`, or `translate/` (e.g. `fix/signin-issue`)
- [X] You have only one commit (if not, [squash](https://github.com/FreeCodeCamp/FreeCodeCamp/wiki/Git-Squash) them into one commit).
- [ ] All new and existing tests pass the command `npm run test-challenges`. Use `git commit --amend` to amend any fixes.
#### Type of Change

- [ ] Small bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds new functionality)
- [ ] Breaking change (fix or feature that would change existing functionality)
- [X] Add new translation (feature adding new translations)
#### Checklist:

- [ ] Tested changes locally.
- [X] Closes currently open issue (replace XXXX with an issue no): Closes #9649
#### Description

Translated new instruction (Input strings are guaranteed to be English words in all lowercase.) to french in Pig Latin challenge.

### CODE REVIEW

**Comment by raisedadead** [comment]
@mizujin can you try and rebase this off staging?

```
git checkout <pr-branch>
git pull --rebase upstream staging
git push origin -f
```

**Comment by mizujin** [comment]
@raisedadead Could you tell me what's up with the snyk tests, and what should I do about it ?

**Comment by raisedadead** [comment]
Just commented above.

**Comment by mizujin** [comment]
@raisedadead Will do in a second, thanks

**Comment by atjonathan** [comment]
@mizujin, please get someone in the French rooms to review your translation before merge, thanks :tada:

**Comment by raisedadead** [comment]
Merging, this will help us in testing the beta site. @mizujin thanks a lot for contributing.

**Pull request merged**
