### PR TITLE
Feat: shortcut dialog

### LINKED ISSUE #37398: Escape key unfocuses the editor when not meant to.
**Describe the bug**
When trying to exit the multi cursor function (Ctrl + D) with the escape key, the editor loses focus. before the update, it worked fine.
(happens also when trying to deselect a selected text, but can be deselected using the arrow keys instead)

**To Reproduce**
1. Select a word or a character.
2. Press Ctrl + D until you've selected the desired words that you wish to change
3. When trying to deselect with ESC, the editor loses focus.

**Expected behavior**
When a text is selected or the editor has multiple cursors, pressing ESC should only deselect or exit the multi cursor mode and not exit to navigation mode.

**GIF**

**Desktop :**
 - OS: Windows 10 
 - Browser Chrome
 - Version 77.0.3865.120

**Additional context**
Based on bug #37146 and PR #37167

### LINKED ISSUE #38842: Keyboard Shortcut to go back and forth between reading area and editor.
**Is your feature request related to a problem? Please describe.**
I'm always frustrated when I have to reach my mouse to go back and forth between reading area and editor, just because I'm using a small screen, I can't read the whole thing and need to scroll down and then go back to editor using mouse. This causes frustration which often prevents me from coding, for long hours.

**Describe the solution you'd like**
A keyboard shortcut to go back and forth would definitely help. 

**Describe alternatives you've considered**
I have tried to scale down my browser window, but it creates readability issues, which not only makes it hard to read but it's difficult for the eyes too.  

**Screenshot**

### PR DESCRIPTION
**Pull request by ojeytonwilliams**
This adds a dialog showing commands and their shortcuts, accessible by `shift + ?`.  It also closes #37398 by changing the 'navigation mode' shortcut from `Escape` to `Alt + n`.

Considerations:
- Do we want to add an alternative way to trigger the dialog, perhaps an extra button inside 'Get Help'

TODO:

- [ ] trigger search exclusively via react hotkeys
- [ ] mount the hotkeys with the searchbar
- [ ] include 'hotkeys' in the modal redux state

closes: #38842

### CODE REVIEW

**Comment by ojeytonwilliams** [comment]
Hey, @ahmadabdolsaheb, any thoughts about the style and implementation?  I just started from [here](https://github.com/greena13/react-hotkeys#displaying-a-list-of-available-hot-keys) and iterated until I had something I liked.  Only then did I think about the other modals we use!

**Comment by ahmadabdolsaheb** [comment]
The functionality is great. a couple of considerations.
how would the users learn about shift + ? before opening the shortcuts modal? ( just a thought, although we could leave it for superusers to discover)
The div moves around when searching. probably it should resize from the bottom.

**Comment by ojeytonwilliams** [comment]
> how would the users learn about shift + ? before opening the shortcuts modal? ( just a thought, although we could leave it for superusers to discover)

I wasn't sure about that, because Quincy didn't want it to be *too* obvious, since the navigation hotkeys could encourage skipping challenges.  That said, making the information public somewhere seems like a good idea.

> The div moves around when searching. probably it should resize from the bottom.

Good point, I'll sort that out.

**Comment by ojeytonwilliams** [comment]
@ahmadabdolsaheb it should look a bit better now.

**Comment by ojeytonwilliams** [comment]
@scissorsneedfoodtoo hey Kris, I just realised I've made this clash with search.  The dialog is triggered by `?` but (because you're pressing `shift+/`) this moves focus to the search bar.

What do you think, should we limit search to `s` or is there a better hotkey for the hotkey legend?

**Comment by scissorsneedfoodtoo** [comment]
@ojeytonwilliams, sorry for the late response.

I think limiting search to `s` sounds great. It's probably more intuitive for most people than `/` like it is now.

**Comment by ojeytonwilliams** [comment]
Thanks, @scissorsneedfoodtoo, that seems reasonable, so I went with that and added `s` to the legend.

**Comment by moT01** [comment]
Overall, I really like this feature and it's looking good. Some suggestions...

Screen Shot 2020-03-30 at 8 21 10 AM

- A skinny window isn't utilizing all the space it could be ^^
- I feel like I would like it more in direct center of the screen, or maybe the bottom right corner or something. It just doesn't feel right top-center (on desktop anyway).
- I don't see a need for the filtering search since there's only nine items at the moment. I would get rid of that and center the title.
- I think it could use an overlay to fade out the rest of the page when the modal is open, like the other modals.
- clicking outside of the modal should close the box.
- could maybe use a close button in there to close it as well.
- for some reason I feel like the shortcuts should be all lowercase and abbreviated where they can be.
- maybe a tiny bit more padding at the bottom to match the sides.

**Comment by ahmadabdolsaheb** [comment]
Thanks for the pr,
we are planning to move code radio to learn which would add at least 4 more shortcuts, so having a search might not be a bad idea.
the UI could be similar to other modals (similar width and backdrop), with similar closing mechanism.

**Comment by ojeytonwilliams** [comment]
@ahmadabdolsaheb I should have used a bootstrap modal in the first place. I'll redo it using that.

@moT01 I'll ping you once I've done that. Hopefully it should fix most of the problems you found.

**Comment by moT01** [comment]
I still vote to remove the search, that's still only 13 items and can all fit on one screen. I'm just not seeing the usefulness of it.

**Comment by ojeytonwilliams** [comment]
@moT01 I've made a few changes, I think it's a bit better now.

Still under discussion:

- Remove other references to hotkeys?
- Advertise this somewhere?
- Keep the filter?

**Comment by raisedadead** [comment]
I think its conventional to use `/` for search and `s` (with a modifier) for save.

**Comment by ojeytonwilliams** [comment]
Okay, I'll see if I can do everything with react-hotkeys to avoid the clash.

**Comment by Kazamario** [comment]
Hello! Jumped down a rabbit hole looking for shortcuts and ended up here! I RTFD'ed the comments above, and have tried:

- Shift + ? | Jumps to search, as called out above
- s | Jumps to search as well.

What esoteric key combination fires that gorgeous shortcut menu in @moT01's post?

This guide [here](https://forum.freecodecamp.org/t/free-code-camp-hotkeys/59467), the "g.x.x" key combinations events don't seem to be firing for me, perhaps I'm missing something?

If someone could set me sorted on how to access the shortcut menu, I'd be one happy coder!

Love the site btw, hence my inquiry for all of the shortcuts! Thank you for your time, and I hope everyone is safe and healthy.

**Comment by ahmadabdolsaheb** [comment]
On the side note: these shortcuts could show up in the background when all editor tabs are unselected in the new next-curriculum editor.

**Comment by raisedadead** [comment]
Closing this stale for now, for a head branch rename. Thanks for your PR.

**Pull request closed without merging**
