### PR TITLE
Add animate.css to relevant jQuery challenges

### LINKED ISSUE #10087: [beta] Add Animate.css to relevant challenges

### PR DESCRIPTION
**Pull request by BKinahan**
#### Pre-Submission Checklist
- [X] Your pull request targets the `staging` branch of FreeCodeCamp.
- [X] Branch starts with either `fix/`, `feature/`, or `translate/` (e.g. `fix/signin-issue`)
- [X] You have only one commit (if not, [squash](http://forum.freecodecamp.com/t/how-to-squash-multiple-commits-into-one-with-git/13231) them into one commit).
- [X] All new and existing tests pass the command `npm run test-challenges`. Use `git commit --amend` to amend any fixes.
#### Type of Change
- [X] Small bug fix (non-breaking change which fixes an issue)
#### Checklist:
- [X] Tested changes locally.
- [X] Closes #10087
#### Description

Adds animate.css to all challenges where it is a required dependency, determined by challenges whose seed code includes the `animated` class (required for any use of animate.css), or whose tests require that class to be added by the user. Adds version of animate.css currently used in production (`3.2.0`, latest is `3.5.2`), tested locally.

### CODE REVIEW

**Comment by atjonathan** [comment]
@BKinahan I don't see animate.css being applied to the challenges in anyway.

**Comment by BKinahan** [comment]
@atjonathan The effect can be seen in the animation of elements in the iPhone preview in the relevant challenges, eg the `#target3` and `#target6` buttons in Target a Specific Child of an Element Using jQuery, both on initial load and any time the tests are run.

These elements do not animate in the current `staging` due to lacking a reference to animate.css

Here's a list of affected challenges for your convenience:

- Target HTML Elements with Selectors Using jQuery
- Target Elements by Class Using jQuery
- Target Elements by ID Using jQuery
- Delete your jQuery Functions
- Target the same element with multiple jQuery Selectors
- Remove Classes from an element with jQuery
- Change the CSS of an Element Using jQuery
- Target a Specific Child of an Element Using jQuery
- Target Even Numbered Elements Using jQuery
- Use jQuery to Modify the Entire Page

**Comment by BerkeleyTrue** [comment]
Thanks @BKinahan Works great!

**Comment by atjonathan** [comment]
@BerkeleyTrue, could you update the beta with the latest from `staging`? I couldn't get this to work, just wanna check it was an issue on my local machine.

**Comment by BerkeleyTrue** [comment]
@atjonathan Did you beforehand seed?

**Comment by atjonathan** [comment]
@BerkeleyTrue, yeah

**Comment by BerkeleyTrue** [comment]
hmmm..

**Comment by atjonathan** [comment]
@BerkeleyTrue, just cleared my mongo collections, which seems to have fixed the issue. Not sure the cause lol.

**Pull request merged**
