### PR TITLE
chore(curriculum): add pokemon search lab

### PR DESCRIPTION
**Pull request by zairahira**
Checklist:

- [x] I have read and followed the [contribution guidelines](https://contribute.freecodecamp.org).
- [x] I have read and followed the [how to open a pull request guide](https://contribute.freecodecamp.org/how-to-open-a-pull-request/).
- [x] My pull request targets the `main` branch of freeCodeCamp.
- [x] I have tested these changes either locally on my machine, or GitPod.

Converting the existing pokemon search app to lab.

### CODE REVIEW

**Comment by moT01** [comment]
Blocking this while we figure out if we want to use the same or new challenge ID's

**Review by moT01 — CHANGES_REQUESTED** [review]
We should use the ID of the existing pokemon project here - `6555c1d3e11a1574434cf8b5`

**Review by jdwilkin4 — APPROVED** [review]

**Comment by zairahira** [comment]
@Sembauke, I have improved the readability of the instructions as suggested. However, I am getting linting/ indentation errors.
Can you take a look?

**Comment by ilenia-magoni** [comment]
I tried to run `pnpm run format` to see if it would fix the files but it seems you need to do it manually. Run `pnpm run lint` to see the errors locally

**Comment by ilenia-magoni** [comment]
I kept playing with it locally, and fixed the lint issues, but I don't think it's good, the numbered list restart:
image

**Comment by ilenia-magoni** [comment]
I managed to fix the thing and I added a commit to the PR with properly formatted page:
to nest lists the bullet point of a nested list needs to be in column with the first character of the parent list item

```md
1. Hey
   - Here the dask is under the H
```

**Comment by zairahira** [comment]
Thank you @ilenia-magoni for sorting these linting errors 👍️

**Review by moT01 — CHANGES_REQUESTED** [review]
The filename should change to match the challenge id.

**Review by moT01 — APPROVED** [review]

**Pull request merged**
