### PR TITLE
fix(seed): Fix Jquery Passing to next step without error

### LINKED ISSUE #16470: Passing to next step without error
#### Challenge Name

https://www.freecodecamp.org/challenges/target-html-elements-with-selectors-using-jquery

#### Issue Description

I placed the `$("button").addClass("animated bounce");` outside `$(document).ready(function() {});` and then I __Ctrl+Enter__ it, and its not considered wrong.  

#### Browser Information

* Browser Name, Version:  Google Chrome, 63.0.3239.132 (Official Build) (64-bit)
* Operating System: Windows 10 Pro 64-bit
* Mobile, Desktop, or Tablet: Desktop 

#### Your Code

```js

<script>
  $(document).ready(function() {

  });
  
  $("button").addClass("animated bounce");
</script>

<!-- Only change code above this line. -->

<div class="container-fluid">
  <h3 class="text-primary text-center">jQuery Playground</h3>
  <div class="row">
    <div class="col-xs-6">
      <h4>#left-well</h4>
      <div class="well" id="left-well">
        <button class="btn btn-default target bounce" id="target1">#target1</button>
        <button class="btn btn-default target bounce" id="target2">#target2</button>
        <button class="btn btn-default target bounce" id="target3">#target3</button>
      </div>
    </div>
    <div class="col-xs-6">
      <h4>#right-well</h4>
      <div class="well" id="right-well">
        <button class="btn btn-default target bounce" id="target4">#target4</button>
        <button class="btn btn-default target bounce" id="target5">#target5</button>
        <button class="btn btn-default target bounce" id="target6">#target6</button>
      </div>
    </div>
  </div>
</div>
```
#### Screenshot

fcc

### PR DESCRIPTION
**Pull request by ninadingole**
#### Pre-Submission Checklist

- [x] Your pull request targets the `staging` branch of freeCodeCamp.
- [x] Branch starts with either `fix/`, `feature/`, or `translate/` (e.g. `fix/signin-issue`)
- [x] You have only one commit (if not, [squash](http://forum.freecodecamp.org/t/how-to-squash-multiple-commits-into-one-with-git/13231) them into one commit).
- [x] All new and existing tests pass the command `npm test`. Use `git commit --amend` to amend any fixes.

#### Type of Change

- [x] Small bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds new functionality)
- [ ] Breaking change (fix or feature that would change existing functionality)
- [ ] Add new translation (feature adding new translations)

#### Checklist:

- [x] Tested changes locally.
- [x] Addressed currently open issue (replace XXXXX with an issue no in next line)

Closes #16470

#### Description

Added a new test for verifying the code is not written outside `$(document).ready();` function

### CODE REVIEW

**Review by Bouncey — CHANGES_REQUESTED** [review]
Thanks for the contribution @ninadingole 

If I do 
```js
$(document).ready(function(){$("button").addClass("animated bounce");});
```
or
```js
$(document).ready(function() {

$("button").addClass("animated bounce");
});
```

The test issues a false negative.

**Comment by ninadingole** [comment]
@Bouncey Thank you, I will do the changes

**Comment by Bouncey** [comment]
@ninadingole Has there been any progress on this?

**Comment by ninadingole** [comment]
@Bouncey I will do the changes today, a bit busy with my work.

**Comment by Bouncey** [comment]
Oh wow, you have been busy re-writing the entire code base 😃 

I think there has been an issue with your branch locally, some how you have picked up a whole bunch of commits that are already merged.

There are ways in which to resolve this through `git`, but for the changes you are making it might just be easier to start a-fresh with a clean, up to date branch off of `staging`. Do you need help with this? I don't know what your git-game is like

**Comment by ninadingole** [comment]
@Bouncey I will start with a fresh branch from `staging`, reject this pull request. 😄

**Pull request closed without merging**
