### PR TITLE
fix(challenges): Remove broken images when undefined

### LINKED ISSUE #16410: [beta] Project submission challenges - Images are undefined
Most images on the submission pages are broken due to an incorrect link, the majority are `http://i.imgur.com/undefined.png`

If `image` is falsey [here](https://github.com/freeCodeCamp/freeCodeCamp/blob/a7a436651d338059a0f7506cfd9b9495eb737f6e/common/app/routes/Challenges/views/project/Project.jsx#L44) then we shouldn't try to render an image.

### PR DESCRIPTION
**Pull request by jameskaupert**
BREAKING CHANGE: none

Closes #16410

Have reviewed guidelines for contribution (first PR!)

#### Pre-Submission Checklist
- [x ] Your pull request targets the `staging` branch of freeCodeCamp.
- [ x] Branch starts with either `fix/`, `feature/`, or `translate/` (e.g. `fix/signin-issue`)
- [ x] You have only one commit (if not, [squash](http://forum.freecodecamp.org/t/how-to-squash-multiple-commits-into-one-with-git/13231) them into one commit).
- [ x] All new and existing tests pass the command `npm test`. Use `git commit --amend` to amend any fixes.

#### Type of Change
- [ x] Small bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds new functionality)
- [ ] Breaking change (fix or feature that would change existing functionality)
- [ ] Add new translation (feature adding new translations)

#### Checklist:
- [x ] Tested changes locally.
- [ x] Addressed currently open issue (replace XXXXX with an issue no in next line)

Closes #16410

#### Description
Added ternary check based on `image`.  If an image exists, will still show (ie: the Front End projects that have images).  If falsey, no broken image icon will be displayed anymore (ie: Applied Responsive Design and Data Viz projects)

### CODE REVIEW

**Comment by BerkeleyTrue** [comment]
"During deep meditation it is possible to dispel time, to see simultaneously all the past present, present, and future, and then everything is fine, everything is perfect, everything is Code" - Berks

Happy Coding

**Comment by jameskaupert** [comment]
Unfortunately it's looking like this is still broken.  It worked locally for me last night, but now on both Beta and locally it's rendering the broken image, but this time with `src="false`.  

Is there a way to reopen the issue or is it better to open a new one?

**Comment by jameskaupert** [comment]
Two better ways to handle this:

1. wrap the entire  tag in a jsx boolean expression evaluated against `image` so the element won't even be rendered

2. set `src="undefined"` (the `` element will be rendered, but without a `src` attribute, so nothing displayed)

I will likely implemented (1) once I understand the correct process to resubmit this.

**Comment by raisedadead** [comment]
Could you please open a fresh issue as per the current state if any thing was missed?

**Comment by BerkeleyTrue** [comment]
see: https://github.com/freeCodeCamp/freeCodeCamp/issues/16426

**Pull request merged**
