### PR TITLE
fix(challenges): Fix broken link

### LINKED ISSUE #17596: Broken Link in Introducing Inline Styles of the React Front End Library curriculum
The link in this paragraph needs to be like this:

"There are other complex concepts that add powerful capabilities to your React code. But you may be wondering about the more simple problem of how to style those JSX elements you create in React. You likely know that it won't be exactly the same as working with HTML because of <a target=\"_blank\" **href=\"front-end-libraries/react/define-an-html-class-in-jsx/\"**> the way you apply classes to JSX elements</a>.",

The href in the above JSON element is currently (define-an-html-class-in-jsx) and this creates a 404 error.

#### Add a Link to the page with the problem
https://learn.freecodecamp.org/front-end-libraries/react/introducing-inline-styles

#### Tell us about your browser and operating system

* Browser Name: Chrome
* Browser Version: 66.09
* Operating System: macOS Sierra

#### Solution

I have a forked repository with the broken link properly formatted (https://github.com/iarobinson/freeCodeCamp) - I just don't know how to do a pull request properly...

### PR DESCRIPTION
**Pull request by eolculnamo2**
A simple link fix.
Fixes link on https://learn.freecodecamp.org/front-end-libraries/react/introducing-inline-styles.
Not tested locally as I do not have the Learn Repo locally.

Closes #17596

#### Pre-Submission Checklist

- [x] Your pull request targets the `staging` branch of freeCodeCamp.
- [ ] Branch starts with either `fix/`, `feature/`, or `translate/` (e.g. `fix/signin-issue`)
- [ ] You have only one commit (if not, [squash](http://forum.freecodecamp.org/t/how-to-squash-multiple-commits-into-one-with-git/13231) them into one commit).
- [ ] All new and existing tests pass the command `npm test`. Use `git commit --amend` to amend any fixes.

#### Type of Change

- [x] Small bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds new functionality)
- [ ] Breaking change (fix or feature that would change existing functionality)
- [ ] Add new translation (feature adding new translations)

#### Checklist:

- [ ] Tested changes locally.
- [ ] Addressed currently open issue (replace XXXXX with an issue no in next line)

Closes #XXXXX

### CODE REVIEW

**Comment by Nirajn2311** [comment]
The changes should be done in FreeCodeCamp’s curriculum package as the learn repo takes its challenges from there.

**Comment by eolculnamo2** [comment]
Yeah, probably so.. I'm probably off, but the react.json file where the data is located is not included in the learn repo. Is this data possibly kept elsewhere that I'm missing.. i.e. database etc?

**Comment by scissorsneedfoodtoo** [comment]
@eolculnamo2, thank you for for submitting this fix! Everything looks great. Just going to hold off on merging until we can get the Travis CI build to pass.

For your next contribution, please review the Contributor's Guide section [Create a Branch](https://github.com/freeCodeCamp/freeCodeCamp/blob/staging/CONTRIBUTING.md#create-a-branch). In the future please start your branch name for fixes like this with `fix/`, and a meaningful name like `fix-broken-link`.

@Nirajn2311, you're right, in the near future we'll ask that updates and fixes to the curriculum be directed to the [curriculum](https://github.com/freeCodeCamp/curriculum) repo. However, that's a very new repo with no contributor's guide at the moment, so we can still merge PRs to the challenge seed files here and move them over to the curriculum repo later.

**Comment by eolculnamo2** [comment]
@scissorsneedfoodtoo Thank you. I'll be sure to make my future pull requests in this format. 

I owe fCC a lot and am excited to contribute.

**Comment by scissorsneedfoodtoo** [comment]
@eolculnamo2, no problem. It also took me some time to get used to the format, and I still forget from time to time. Just something we can both keep in mind in the future. And we're all happy to have this or any of your future contributions :+1:

Just wanted to let you know that we're currently in the process of moving all updates to the curriculum over to a separate repository, so your PR is blocked for now. But everything still LGTM! @raisedadead, myself, or any other members will merge things are ready with the new repo.

**Comment by raisedadead** [comment]
Hi @eolculnamo2  

Thanks a lot for this pull request. We sincerely appreciate the time and efforts put into this. 

However can you please make the same changes once again on the https://github.com/freeCodeCamp/curriculum repository?

I would like to apologise for the inconvenience, but at this point it has become very difficult to carry over commits into the other repo, to which we have moved over the entire curriculum package.

Thanks once again. 

Please reach out to us in the [Contributors Chat room](https://gitter.im/FreeCodeCamp/Contributors) for any assistance.

Happy contributing!

**Pull request closed without merging**
