### PR TITLE
Quick Selection Algorithm

### PR DESCRIPTION
**Pull request by F9Uf**
- [x] :star2: Explain **Quick Selection Algorithm**
- [x] :new_moon: Psudocode about **Quick Selection Algorithm**
- [x] :sun_with_face: Psudocode about **Lomuto partition**
- [x] :earth_asia: Psudocode about **Hoare partition**
- [x] :partly_sunny: Explain **Lomuto partition**
- [x] :milky_way: Explain **Hoare partition**

### CODE REVIEW

**Review by tchaffee — CHANGES_REQUESTED** [review]
@F9Uf Thanks for your contribution. There are many English spelling and grammar mistakes in this PR. Could you please have someone help you with the English and make corrections so we can merge this? Thanks!

**Comment by RandellDawson** [comment]
Also, I do not think extra directories and index.md files should be created.

**Comment by tchaffee** [comment]
@F9Uf Per the suggestion from @RandellDawson I think you could condense this all into one article.

**Comment by F9Uf** [comment]
thank you i'll fix it later

**Comment by F9Uf** [comment]
I fixed it, is there anything else?

**Comment by QuincyLarson** [comment]
@F9Uf Excellent work! This is a great article. 

@RandellDawson and @tchaffee thanks for the assist!

**Pull request merged**
