### PR TITLE
test: enable testing for upcoming challenges

### PR DESCRIPTION
**Pull request by ojeytonwilliams**
I ran them locally and they completed fairly quickly and all passed, so I think we can start including them in CI.

### CODE REVIEW

**Review by ShaunSHamilton — COMMENTED** [review]
Do we not want to do this before the curriculum build step, as the `.env` file is overwritten? https://github.com/freeCodeCamp/freeCodeCamp/pull/42360/files#diff-72b60d54640c9e2f298edde10495ba362a230dc5e4288af7ff638215f27133d7R83

Also, is echo-ing the variable into `.env` the recommended way to handle env logic?

**Comment by ojeytonwilliams** [comment]
> Do we not want to do this before the curriculum build step, as the .env file is overwritten?

Yep, thanks!

> Also, is echo-ing the variable into .env the recommended way to handle env logic?

Generally no, but using .env works quite well since we have so many environment variables.  Echoing is just a cute trick to replace the variable, since the last entry takes precedence.  Bit of a hack, but I think it's fine here.

**Comment by ShaunSHamilton** [comment]
**Unrelated**:
This is nice to see:
```console
16930 passing (7m)
666 pending
```
But, the number of pending has gone up from its typical `~512`. So, it appears to be some percentage of the total tests run which go to pending.

Although, most of the literature I have read suggests the pending is just due to incorrectly formatted tests:
```javascript
test("some test without a callback"); // results in a pending test
```

**Comment by ojeytonwilliams** [comment]
Interesting. I'd always assumed it was challenges without tests, but perhaps not. I'll keep this in mind.

**Comment by gikf** [comment]
While poking in code interview prep section I've noticed adding solution to the challenge reduces that number by one. So it seems to at least include such challenges.

**Review by ShaunSHamilton — COMMENTED** [review]
I just realised! What happens when the final part of a project is reached, where there is no next part with solution seed?

**Comment by ojeytonwilliams** [comment]
> I just realised! What happens when the final part of a project is reached, where there is no next part with solution seed?

In that case you need to provide a solution. I'm guessing we didn't document this 🤦

**Review by raisedadead — CHANGES_REQUESTED** [review]
IMHO, we should still have the separations of concerns. 

Either as a separate workflow that runs on all PRs and pushes OR as a separate job on all PRs and pushes.

CI should always prioritise on mirroring dev/prod flows as closely as it can.

**Comment by ojeytonwilliams** [comment]
@raisedadead how about this?  I've put it on the same level as the localize job.

**Review by raisedadead — APPROVED** [review]

**Comment by ShaunSHamilton** [comment]
As we already have the tests running for the _"production"_ replica, would it not be nice/useful to skip re-running these same tests with SHOW_UPCOMMING?
Sorry, for the trickled picking 🙈

**Comment by raisedadead** [comment]
> Sorry, for the trickled picking 🙈

Never be shy of asking questions. It's better to ask than not.

> would it not be nice/useful to skip re-running these same tests with SHOW_UPCOMMING?

Yes - it would save us a few minutes. However, we want to test them alongside the other tests. 

That way, you are testing them alongside any additional tooling you make have (ex. challenge helpers, parsers, etc.), which may have custom code for one or the other types of the challenges (current or upcoming).

The idea with coding tests is they should be dumb. The idea with coding logic is they should be DRY and smart.

Duplication is good with tests and suites because you are not thinking about how you want to spread the net. You get the widest net possible and catch them all.

**Review by ShaunSHamilton — APPROVED** [review]
LGTM 👍

**Pull request merged**
