### PR TITLE
changes in the output

### PR DESCRIPTION
**Pull request by himanshu07070**
['I', 'love', 'Python', 'very much']
instead of double quotes , it should be single quote.

- [ ] I have read [freeCodeCamp's contribution guidelines](https://github.com/freeCodeCamp/freeCodeCamp/blob/master/CONTRIBUTING.md).
- [ ] My pull request has a descriptive title (not a vague title like `Update index.md`)
- [ ] My pull request targets the `master` branch of freeCodeCamp.
- [ ] None of my changes are plagiarized from another source without proper attribution.
- [ ] My article does not contain shortened URLs or affiliate links.

If your pull request closes a GitHub issue, replace the XXXXX below with the issue number.

Closes #XXXXX

### CODE REVIEW

**Comment by nathanhannig** [comment]
why didn't you change everything in double quotes then to match?

**Comment by nathanhannig** [comment]
Python would output to single quotes, LGTM when passing CI

**Comment by RandellDawson** [comment]
Closed and Reopened this PR to attempt to resolve a specific Travis build failure.

**Comment by himanshu07070** [comment]
because i think everything was right . The only problem is that output
always comes in single quotes , instead of double quotes.

**Comment by moT01** [comment]
Looks good @himanshu07070, thanks for contributing to freeCodeCamp! In the future, be sure to complete the checklist in the PR template. Thanks and happy coding!

**Pull request merged**
