### PR TITLE
feat(tools): remove deleted challenges from i18n

### PR DESCRIPTION
**Pull request by naomi-lgbt**
Checklist:

- [X] I have read and followed the [contribution guidelines](https://contribute.freecodecamp.org).
- [X] I have read and followed the [how to open a pull request guide](https://contribute.freecodecamp.org/#/how-to-open-a-pull-request).
- [X] My pull request targets the `main` branch of freeCodeCamp.
- [X] I have tested these changes either locally on my machine, or GitPod.

Related #52148

### CODE REVIEW

**Comment by Sembauke** [comment]
I encountered an error with the following message:

<details><summary>Details</summary>
<p>
Syncing 00-certifications/a2-english-for-developers-certification/a2-english-for-developers-certification.yml
Error: Command failed: mkdir -p /Users/sembauke/Documents/freecodecamp/curriculum/challenges/.DS_Store/00-certifications/a2-english-for-developers-certification && cp /Users/sembauke/Documents/freecodecamp/curriculum/challenges/english/00-certifications/a2-english-for-developers-certification/a2-english-for-developers-certification.yml /Users/sembauke/Documents/freecodecamp/curriculum/challenges/.DS_Store/00-certifications/a2-english-for-developers-certification/a2-english-for-developers-certification.yml
mkdir: /Users/sembauke/Documents/freecodecamp/curriculum/challenges/.DS_Store: Not a directory

    at ChildProcess.exithandler (node:child_process:421:12)
    at ChildProcess.emit (node:events:514:28)
    at ChildProcess.emit (node:domain:489:12)
    at maybeClose (node:internal/child_process:1105:16)
    at Socket.<anonymous> (node:internal/child_process:457:11)
    at Socket.emit (node:events:514:28)
    at Socket.emit (node:domain:489:12)
    at Pipe.<anonymous> (node:net:337:12) {
  code: 1,
  killed: false,
  signal: null,
  cmd: 'mkdir -p /Users/sembauke/Documents/freecodecamp/curriculum/challenges/.DS_Store/00-certifications/a2-english-for-developers-certification && cp /Users/sembauke/Documents/freecodecamp/curriculum/challenges/english/00-certifications/a2-english-for-developers-certification/a2-english-for-developers-certification.yml /Users/sembauke/Documents/freecodecamp/curriculum/challenges/.DS_Store/00-certifications/a2-english-for-developers-certification/a2-english-for-developers-certification.yml',
  stdout: '',
  stderr: 'mkdir: /Users/sembauke/Documents/freecodecamp/curriculum/challenges/.DS_Store: Not a directory\n'
}
sembauke@sems-air freecodecamp % 
</p>
</details> 

chatGPT:
It's important to note that .DS_Store is a system file generated by macOS to store folder-specific metadata, and it shouldn't be part of your directory structure for syncing files.

To resolve this issue, you should check the configuration or script that you're using for syncing and ensure that it's not trying to include .DS_Store files in the process. Additionally, make sure that the directory paths specified in your sync command are correct and that the target directory exists.

**Comment by naomi-lgbt** [comment]
Gosh darn mac users. 😭

**Review by moT01 — APPROVED** [review]
LGTM @naomi-lgbt 🎉

Only thing I could mention is that I might rather see the filter go the other direction - e.g. filter out everything that doesn't match what we specify, maybe ! .md file.

**Review by Sembauke — APPROVED** [review]
It is still not working for me, but I am fine merging this.

**Pull request merged**
