### PR TITLE
chore(i18n,docs): processed translations

### PR DESCRIPTION
**Pull request by camperbot**
This PR was opened auto-magically by Crowdin.

### CODE REVIEW

**Review by sidemt — COMMENTED** [review]
The most recent change is only to add the `### I am interested in being a moderator at freeCodeCamp. Where should I start?` section, but other parts are being changed back to English. (Especially the Portuguese file which has been fully translated)
Is this OK?

**Review by DanielRosa74 — APPROVED** [review]
LGTM

**Comment by ieahleen** [comment]
> The most recent change is only to add the `### I am interested in being a moderator at freeCodeCamp. Where should I start?` section, but other parts are being changed back to English. (Especially the Portuguese file which has been fully translated)
> Is this OK?

It means that the original file has been changed

**Review by majestic-owl448 — APPROVED** [review]

**Comment by sidemt** [comment]
@ieahleen I thought the changes were larger than the change in the original file. Excuse me if I misunderstood something. Thanks anyway 🙂

**Comment by ieahleen** [comment]
@sidemt that's crowdin for you, it changes more than you think it should

**Pull request merged**
