### PR TITLE
updated gulp to watch new file structure

### PR DESCRIPTION
**Pull request by gasperno**
DEV environment updates automatically when .json is modified. 
gulp watches for modifications in .json in seed/challenges. This feature helps developer's productivity
But the file structure is modified in this release. So gulp file is modified to reflect the same.

### CODE REVIEW

**Comment by SaintPeter** [comment]
:shipit:

**Comment by abhisekp** [comment]
Probably, this could've been like the following (but i'm not sure or if this might work or not)
```js
challenges: [
    'seed/challenges/**.json'
]
```

**Comment by gasperno** [comment]
Is that for recursive search in directories?

**Comment by abhisekp** [comment]
@gasperno yep! That's what the wildcard means. But i'm not sure if it works for that use case. You may run and check it.

**Pull request merged**
