### PR TITLE
change

### PR DESCRIPTION
**Pull request by baskaodo**
<style>
  :root {

    /* add code below */
    --penguin-belly:pink;
    /* add code above */
  }

- [ ] I have read [freeCodeCamp's contribution guidelines](https://github.com/freeCodeCamp/freeCodeCamp/blob/master/CONTRIBUTING.md).
- [ ] My pull request has a descriptive title (not a vague title like `Update index.md`)
- [ ] My pull request targets the `master` branch of freeCodeCamp.
- [ ] None of my changes are plagiarized from another source without proper attribution.
- [ ] All the files I changed are in the same world language (for example: only English changes, or only Chinese changes, etc.)
- [ ] My changes do not use shortened URLs or affiliate links.

Closes #XXXXX

### CODE REVIEW

**Comment by RandellDawson** [comment]
@baskaodo What is the purpose of this change?  Does it fix a bug?

**Comment by baskaodo** [comment]
Hi
Your code didnt work for me. The one i proposed changed everything to pink
as it was meant to

Dňa st 6. 11. 2019, 6:14 Randell Dawson <notifications@github.com>
napísal(a):

**Comment by ojeytonwilliams** [comment]
It seems like this challenge has an incomplete solution that's just designed to pass the test. This PR doesn't fix that, though.

**Comment by RandellDawson** [comment]
@baskaodo If you want to add code to this challenge's solution section, please add all the seed code plus any changes to make it a working solution.

Thank you.

**Comment by baskaodo** [comment]
OK

st 6. 11. 2019 o 15:41 Randell Dawson <notifications@github.com> napísal(a):

**Comment by RandellDawson** [comment]
@baskaodo Please change your PR's title to something more descriptive.  See the guidelines I referenced 2 days ago for guidance.  Also, we are still waiting for you to add a full working solution.

Thank you.

**Comment by baskaodo** [comment]
Hello, I appologize, too much happening at work and home Ill do it asap

Dňa pi 8. 11. 2019, 18:41 Randell Dawson <notifications@github.com>
napísal(a):

**Comment by baskaodo** [comment]
Hello again
actually, I executed my proposed change on fcc now again. The tests allowed
me to pass to another challenge, but the pink color appeared on the screen
only for a while like a pink flash light.
So maybe my propose doesn't work anymore. Sorry. Just don't mind my pull
request anymore.

Have a nice weekend

pi 8. 11. 2019 o 19:06 Barbara Odokienkova <baskaodo@gmail.com> napísal(a):

**Pull request closed without merging**
