### PR TITLE
Issue 49976 switch condition

### PR DESCRIPTION
**Pull request by ChenXie-sci**
Checklist:

- [x] I have read and followed the [contribution guidelines](https://contribute.freecodecamp.org).
- [x] I have read and followed the [how to open a pull request guide](https://contribute.freecodecamp.org/#/how-to-open-a-pull-request).
- [x] My pull request targets the `main` branch of freeCodeCamp.
- [x] I have tested these changes either locally on my machine, or GitPod.

Closes #XXXXX

### CODE REVIEW

**Comment by ChenXie-sci** [comment]
fixed(Issue 49976) switch condition problem

**Comment by ChenXie-sci** [comment]
fixed(Issue 49976 switch condition)

**Review by jeremylt — CHANGES_REQUESTED** [review]
I am strongly against this change. This makes the example nearly a copy-paste solution.

The linked issue has not been discussed, triaged, or opened for contributions.

In my opinion, this PR should be closed and there should be discussion in the linked issue instead.

**Comment by raisedadead** [comment]
Thank you for opening this pull request.

We’ve reviewed your pull request and decided not to merge it; However, We would welcome future pull requests from you. 

You are welcome to [read these guidelines](https://contribute.freecodecamp.org) to learn more about contributing to this project. 

Happy contributing.

**Pull request closed without merging**
