### PR TITLE
Several fixes for php-syntax-overview/index.md

### PR DESCRIPTION
**Pull request by ericol**
I made several fixes for the index file.

I changed the structure of several lines or paragraph to make them sound more natural in Spanish, opposed to a direct translation from English.

I fixed those pages where what seems to be auto translation had translated PHP stataments.

I translated several strings in code, and I fixed at least one bug in the PHP examples (The ending tag of here documents cannot have spaces between the tag and the margin).

- [x] I have read [freeCodeCamp's contribution guidelines](https://github.com/freeCodeCamp/freeCodeCamp/blob/master/CONTRIBUTING.md).
- [x] My pull request has a descriptive title (not a vague title like `Update index.md`)
- [x] My pull request targets the `master` branch of freeCodeCamp.
- [x] None of my changes are plagiarized from another source without proper attribution.
- [x] My article does not contain shortened URLs or affiliate links.

If your pull request closes a GitHub issue, replace the XXXXX below with the issue number.

Closes #XXXXX

### CODE REVIEW

**Comment by ericol** [comment]
Regarding "My pull request has a descriptive title" my PR here has kind of a non-descriptive title because I made several fixes that were not related.

Should I group instead similar fixes and make a PR for each group?

**Comment by tbushman** [comment]
@ericol No, because this is all one file. This is great! Thanks. I'll tag this for proofreading.

**Comment by ericol** [comment]
@tbushman event thought your post about the tshirt contest brought me here, I'm all in for keeping these coming.
Let me know if you're open for more contributions.

**Review by RandellDawson — APPROVED** [review]

**Comment by RandellDawson** [comment]
Congrats @ericol on your first pull request (PR)! 🎉

Thank you for your contribution to the page! 👍
We're happy to accept these changes, and look forward to future contributions. 📝

**Pull request merged**
