### PR TITLE
refactor(client): simplify certification config

### PR DESCRIPTION
**Pull request by ojeytonwilliams**
- refactor: rename cert data structures
- refactor: more renaming
- feat: add map for upcoming certifications
- refactor: use certification titles directly
- refactor: move to config

Checklist:

- [x] I have read and followed the [contribution guidelines](https://contribute.freecodecamp.org).
- [x] I have read and followed the [how to open a pull request guide](https://contribute.freecodecamp.org/#/how-to-open-a-pull-request).
- [x] My pull request targets the `main` branch of freeCodeCamp.
- [x] I have tested these changes either locally on my machine, or GitPod.

This should be a little less confusing now. Also, I dropped the dependence on `showUpcomingChanges` since this is (should be) a simple config file. In a followup PR I plan to use `showUpcomingChanges` to control which certifications appear on the settings page, but this module's job is just to describe and group the certifications.

### CODE REVIEW

**Review by moT01 — APPROVED** [review]
LGTM 🎉

**Comment by naomi-lgbt** [comment]
> I dropped the dependence on showUpcomingChanges since this is (should be) a simple config file. In a followup PR I plan to use showUpcomingChanges to control which certifications appear on the settings page,

Do we need to hold deployments after this is merged?

**Comment by ojeytonwilliams** [comment]
> Do we need to hold deployments after this is merged?

We shouldn't need to. I just dropped the branch of the conditional where upcoming changes were included. It wasn't doing much.

**Review by naomi-lgbt — APPROVED** [review]
I think this is good to go then.

**Pull request merged**
