### PR TITLE
run python code in the challenges with pyodide

### PR DESCRIPTION
**Pull request by etnnth**
Checklist:

- [x] I have read [freeCodeCamp's contribution guidelines](https://contribute.freecodecamp.org).
- [x] My pull request has a descriptive title (not a vague title like `Update index.md`)
- [x] My pull request targets the `master` branch of freeCodeCamp.
- [x] All the files I changed are in the same world language, for example: only English changes, or only Chinese changes, etc.

Closes #XXXXX

This a demo of using  [pyodide](https://github.com/iodide-project/pyodide) to run python in a similar way as javascript run in challenges.
This is a similar proposition to issue #39271.
I added a challenge: learn/scientific-computing-with-python/python-for-everybody/example-pyodide as demo.

### CODE REVIEW

**Comment by raisedadead** [comment]
Thanks for this PR, let me discuss this with the @freeCodeCamp/dev-team and get back to you. We are very much interested in this implementation. In fact, I had explored this in the past when speaking to @ojeytonwilliams.

Thanks for your patience, while we get back to you.

**Comment by Twaha-Rahman** [comment]
I think a decision was reached here -> https://github.com/freeCodeCamp/freeCodeCamp/issues/39271#issuecomment-695138370

**Comment by raisedadead** [comment]
Right, at the minute we definitely do not want to use Brython. But Pyiode could potentially replace the equivalent for data-science type projects.

It is supposed to be a drop-in replacement for Google Collab style notebooks and is in browser.

We would like to explore this still. We would use the integrated IDE, that would be depending on backends however if Pyodide becomes mature enough by the time it would be nicer to have it in browser.

/cc @beaucarnes

**Comment by raisedadead** [comment]
Closing this stale for now, for a head branch rename. Thanks for your PR.

**Pull request closed without merging**
