### PR TITLE
feat(docs): Implement dark mode functionality

### LINKED ISSUE #50976: Dark Mode Functionality Request for FreeCodeCamp Documentation Reading Site
### Describe the Issue

I would like to request the addition of dark mode functionality to the FreeCodeCamp documentation reading site. As the site primarily serves as a platform for reading and learning, it would greatly benefit users who experience discomfort or eye strain when viewing bright pages for an extended period of time. By implementing a dark mode option, users would have the flexibility to choose their preferred reading experience, enhancing overall usability and accessibility.

### Affected Page

https://contribute.freecodecamp.org/#/

### Steps to Reproduce

1. Open the FreeCodeCamp documentation reading site.
2. Click on "Read our contributing guidelines" button.
3. Navigate to any section or page of the documentation.
Note the absence of dark mode functionality and the resulting bright page appearance.

### Expected behavior

Upon enabling dark mode, the colors, backgrounds, and text elements of the site should be adjusted to create a visually comfortable reading experience for users. Dark mode should provide a high contrast environment that reduces eye strain and improves readability, especially in low-light conditions.

### Screenshots

_No response_

### System

- OS: Windows 10
- Browser: Google Chrome
- Version: 114.0.5735.199 (Official Build) (64-bit)

### Additional context

I believe that implementing dark mode functionality on the FreeCodeCamp documentation reading site would significantly enhance user experience and accessibility. I am interested in contributing to this feature request and would appreciate it if the assigned developers could consider assigning this issue to me. I am excited to collaborate and help improve the FreeCodeCamp platform for the benefit of all users.

### PR DESCRIPTION
**Pull request by ketansahugit**
Checklist:

- [x ] I have read and followed the [contribution guidelines](https://contribute.freecodecamp.org).
- [x ] I have read and followed the [how to open a pull request guide](https://contribute.freecodecamp.org/#/how-to-open-a-pull-request).
- [x ] My pull request targets the `main` branch of freeCodeCamp.
- [x ] I have tested these changes either locally on my machine, or GitPod.

This pull request adds dark mode functionality to the FreeCodeCamp Documentation Reading Site (#50976). The dark mode feature allows the website to adapt its appearance based on the user's preferred color scheme.

Changes Made
- Implemented a media query ( `@media (prefers-color-scheme: dark)`) to target devices with a preferred color scheme set to dark mode.
- Added styles within the media query to update the appearance of various elements when in dark mode.
- Modified color schemes, backgrounds, and text colors to ensure readability and usability in dark mode.

Closes #50976

### CODE REVIEW

**Comment by naomi-lgbt** [comment]
IMHO, if we are going to implement a dark mode, it should be togglable independently of the system theme.

**Comment by ketansahugit** [comment]
> IMHO, if we are going to implement a dark mode, it should be togglable independently of the system theme.

Of course! If the issue is triaged and this is the direction the maintainers want, I'll gladly proceed with implementing the independent togglable dark mode. Your input is valuable, and I'm here to contribute accordingly. Thank you!

**Comment by jeremylt** [comment]
I agree that a toggle is needed.

> If the issue is triaged and this is the direction the maintainers want

The issue looks like it was marked as ready for contributions?

**Comment by ketansahugit** [comment]
Just to clarify, where would you prefer the toggle button to be placed?

**Comment by jeremylt** [comment]
I don't have strong opinions - I think that would usually go in the hamburger menu?

**Comment by raisedadead** [comment]
Hey @ketansahugit - how is this coming along? Do let us know in the chat if you need help or are stuck.

**Comment by ketansahugit** [comment]
> Hey @ketansahugit - how is this coming along? Do let us know in the chat if you need help or are stuck.

Hello, I have already raised a PR for Dark Mode functionality based on System's default settings. Currently I'm waiting for the issue to be triaged and if the maintainers need me to make changes to my PR, I will certainly do that.

**Comment by ketansahugit** [comment]
> Hey @ketansahugit - how is this coming along? Do let us know in the chat if you need help or are stuck.

Hello, I've already submitted a draft pull request for implementing Dark Mode that follows the system's default settings. Right now, I'm in the process of incorporating a toggle-based functionality. Please inform me about the specific requirements FCC has for their documentation page's functionality.

**Comment by raisedadead** [comment]
> Please inform me about the specific requirements FCC has for their documentation page's functionality.

You can use Jeremy's suggestion from above. BTW, to us when a PR is in draft it means you are still working on it. Please feel free to open it up when it is ready for review.

**Comment by ketansahugit** [comment]
@raisedadead  Hi, I've submitted my draft PR for your review. I wanted to inform the maintainers that, due to my busy schedule, I'm unable to implement the toggle-based functionality. If someone else is planning to work on it, please feel free to take it over.

**Comment by ShaunSHamilton** [comment]
Thank you @ketansahugit for all your work on this.

I pushed a commit using the `variables.css` definitions, and removing some of the duplicate css declarations.

---

Also, I did a bit more of an overhaul to match our current theme on `freecodecamp.org`:

**After | Before**

image

image

---

**New Light theme After | Before**

image

**Comment by ShaunSHamilton** [comment]
With toggle:
image

image

**Review by naomi-lgbt — APPROVED** [review]

**Review by raisedadead — APPROVED** [review]

**Pull request merged**
