### PR TITLE
fix(curriculum) require creating store

### LINKED ISSUE #50460: Redux - test doesnt take createStore into consideration
### Describe the Issue

This challenge should push the programmer to create the Redux.store() at the end of the challenge. But it passes with declaring this:
```
const store = null;
```
Now it was explained to me, that the site creates its store on its own, but i think the programmer should be expected to do that even if he forgot - like me :)

### Affected Page

https://www.freecodecamp.org/learn/front-end-development-libraries/redux/write-a-counter-with-redux

### Your code

```
const INCREMENT = 'INCREMENT'; // Define a constant for increment action types
const DECREMENT = 'DECREMENT'; // Define a constant for decrement action types

const counterReducer = (state = 0, action) => {
  switch(action.type) {
    case INCREMENT:
      return state + 1;
    case DECREMENT:
      return state - 1;
    default:
      return state;
  }
}; // Define the counter reducer which will increment or decrement the state based on the action it receives

const incAction = () => {
  return {type: INCREMENT}
}; // Define an action creator for incrementing

const decAction = () => {
  return {type: DECREMENT}
}; // Define an action creator for decrementing

const store = null;


```

### Expected behavior

The test should fail if Redux.createStore() wasnt used

### Screenshots

_No response_

### System

- Device: [Laptop]
- OS: [X11; Linux x86_64]
- Browser: [Chrome]
- Version: [113.0.0.0]

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by jmetev1**
Checklist:

- [x ] I have read and followed the [contribution guidelines](https://contribute.freecodecamp.org).
- [x ] I have read and followed the [how to open a pull request guide](https://contribute.freecodecamp.org/#/how-to-open-a-pull-request).
- [x ] My pull request targets the `main` branch of freeCodeCamp.
- [x ] I have tested these changes either locally on my machine, or GitPod.

Closes #50460

First there was #45267 where a user felt that doing `store.dispatch(incAction());` in their code to see that things worked should not lead to failing tests. Which makes sense. So #45457 was done to test against a separately created store. But now user points out that they can just leave `const store = null` and still pass test. Which is also not perfect. So here I add a test making sure the user is creating a store that returns some number. But I don't check for specific number so it will not be affected by their inline attempts like before. But also leaving other tests independent.  I hope this helps! If anyone wants to update language or whatever else, feel free.

### CODE REVIEW

**Review by moT01 — APPROVED** [review]
Thanks for working on this @jmetev1 👍 

I'm fine with adding this. I would prefer the text say `Running store.getState() should return a number` or something like that. But this works too.

**Comment by jmetev1** [comment]
wording updated

**Comment by jmetev1** [comment]
The CI - E2E - Web browser / Test (firefox, 18.x) failed. I think I've seen that it fails regularly and is probably not due to my pr, right? Is there a way I can trigger tests to rerun? This time I pulled from main and pushed. But if there were no changes there, I guess I'd have to just add some junk white space or such to trigger the tests?

**Comment by gikf** [comment]
> The CI - E2E - Web browser / Test (firefox, 18.x) failed. I think I've seen that it fails regularly and is probably not due to my pr, right? Is there a way I can trigger tests to rerun? This time I pulled from main and pushed. But if there were no changes there, I guess I'd have to just add some junk white space or such to trigger the tests?

I've started the failed check again for you.

As a side note, there's no need to keep merging new changes from the `main` to the PR branch. Unless there are merge conflicts (which will be indicated below the CIs checks) PR will be merged cleanly. What it does is basically just starting all CI checks again.

**Comment by jmetev1** [comment]
> > The CI - E2E - Web browser / Test (firefox, 18.x) failed. I think I've seen that it fails regularly and is probably not due to my pr, right? Is there a way I can trigger tests to rerun? This time I pulled from main and pushed. But if there were no changes there, I guess I'd have to just add some junk white space or such to trigger the tests?
> 
> I've started the failed check again for you.
> 
> As a side note, there's no need to keep merging new changes from the `main` to the PR branch. Unless there are merge conflicts (which will be indicated below the CIs checks) PR will be merged cleanly. What it does is basically just starting all CI checks again.

I understand that I don't have to merge in main. I just did it to restart the failed test. But what you're saying is that I should not do anything and just wait for someone to come restart the test for me? Or should I tag someone?

**Comment by jmetev1** [comment]
wording updated

**Review by Sboonny — APPROVED** [review]

**Comment by gikf** [comment]
> I understand that I don't have to merge in main. I just did it to restart the failed test. But what you're saying is that I should not do anything and just wait for someone to come restart the test for me? Or should I tag someone?

Yes, if failing test is unrelated to changes, there's no need to take any immediate actions on your part. At the worst it will be started again when somebody is reviewing PR.

**Pull request merged**
