### PR TITLE
fix(coding): uncomment destructuring test and add solution

### LINKED ISSUE #18177: Array destructuring "easy" solution to the challenge
#### Describe your problem and - if possible - how to reproduce it
I don't know if it's a "fixable" problem but i was surprised my solution without using array destructuring worked. Just had to write : 
"a = 6
b = 8"
Then submit and my solution was accepted !
So i don't know if it's a real issue but i wanted to share it, because in the challenge it's specified that you need to "Use array destructuring to swap a and b."

#### Add a Link to the page with the problem
https://learn.freecodecamp.org/javascript-algorithms-and-data-structures/es6/use-destructuring-assignment-to-assign-variables-from-arrays

#### Tell us about your browser and operating system

* Browser Name: Mozilla Firefox
* Browser Version: 52.9.0 (64 bits)
* Operating System: Linux - Debian

### PR DESCRIPTION
**Pull request by geeseyj**
- [x] I have read [freeCodeCamp's contribution guidelines](https://github.com/freeCodeCamp/freeCodeCamp/blob/master/CONTRIBUTING.md).
- [x] My pull request has a descriptive title (not a vague title like `Update index.md`)
- [x] My pull request targets the `master` branch of freeCodeCamp.
- [x] None of my changes are plagiarized from another source without proper attribution.
- [x] My article does not contain shortened URLs or affiliate links.

If your pull request closes a GitHub issue, replace the XXXXX below with the issue number.

Closes #18177

### CODE REVIEW

**Comment by RandellDawson** [comment]
Thank you for your contribution.  However, uncommenting that assert with that particular regular expression will not create a valid test.  This fact coupled with the fact this PR has a merge conflict, we are closing it.

**Comment by RandellDawson** [comment]
I fixed a merge conflict and replaced the single line with a full working solution for the challenge on the OP's behalf.

**Review by RandellDawson — COMMENTED** [review]
I have tested this PR locally and validated the assert works correctly and makes sure the only way for the values for variables `a` and `b` are swapped, is via destructuring.

**Review by ezioda004 — APPROVED** [review]

**Comment by ezioda004** [comment]
Thank you @geeseyj and @RandellDawson for your contribution. Looking forward to more contributions from both of you! 🎉

**Pull request merged**
