### PR TITLE
Cambios a la redacción

### PR DESCRIPTION
**Pull request by Josev47**
Cambios a la redacción para dar un mejor sentido a la lectura del artículo.

- [ x ] I have read [freeCodeCamp's contribution guidelines](https://github.com/freeCodeCamp/freeCodeCamp/blob/master/CONTRIBUTING.md).
- [ x ] My pull request has a descriptive title (not a vague title like `Update index.md`)
- [ x ] My pull request targets the `master` branch of freeCodeCamp.
- [ x ] None of my changes are plagiarized from another source without proper attribution.
- [ x ] My article does not contain shortened URLs or affiliate links.

If your pull request closes a GitHub issue, replace the XXXXX below with the issue number.

Closes #XXXXX

### CODE REVIEW

**Review by RandellDawson — DISMISSED** [review]
Can you please translate the tests also?
```
tests:
  - text: El elemento de su imagen debe tener la clase "borde verde grueso".
    testString: 'assert($("img").hasClass("thick-green-border"), "Your image element should have the class "thick-green-border".");'
  - text: Tu imagen debe tener un radio de <code>10px</code> de <code>10px</code>
    testString: 'assert(parseInt($("img").css("border-top-left-radius")) > 8, "Your image should have a border radius of <code>10px</code>");'
```

**Comment by Josev47** [comment]
Sure.

**Comment by RandellDawson** [comment]
@Josev47 Just reply and tag me when you have made the translations to the Tests section.

**Comment by Josev47** [comment]
@RandellDawson already made the translations, check back later.

**Comment by RandellDawson** [comment]
I was referring to the text in double quotes of the tests section (see below)
```
"Your image element should have the class "thick-green-border"."
```
and 
```
"Your image should have a border radius of <code>10px</code>"
```

**Comment by lynxlynxlynx** [comment]
Thanks and congrats!

**Pull request merged**
