### PR TITLE
fix: store completed js projects in redux

### PR DESCRIPTION
**Pull request by ojeytonwilliams**
These were missed when we migrated from files to challengeFiles

### CODE REVIEW

**Comment by ojeytonwilliams** [comment]
QA note: to see the change, complete JS projects, go to settings, click Show Code, see code. Then claim the certification, click Show Certification and click on the solutions.

Before this PR the code did not appear.

**Comment by nhcarrigan** [comment]
If I open the cert in an incognito window, I get no solution links:

image

**Review by naomi-lgbt — DISMISSED** [review]
Yeah okay it was a privacy setting issue. That probably merits further discussion, but not here.

This lgtm.

**Review by ShaunSHamilton — CHANGES_REQUESTED** [review]
My nitpick, because in our TS config, we expect `challengeFiles` to either be `null | Array<something>`

**Review by ShaunSHamilton — APPROVED** [review]
Pending tests, this LGMT 👍

**Review by moT01 — APPROVED** [review]
LGTM :tada:

**Pull request merged**
