### PR TITLE
test(e2e):  fix  flaky firefox tests

### PR DESCRIPTION
**Pull request by shootermv**
Checklist:

- [x] I have read and followed the [contribution guidelines](https://contribute.freecodecamp.org).
- [x] I have read and followed the [how to open a pull request guide](https://contribute.freecodecamp.org/#/how-to-open-a-pull-request).
- [x] My pull request targets the `main` branch of freeCodeCamp.
- [x] I have tested these changes either locally on my machine, or GitPod.

Ref #49966

### CODE REVIEW

**Comment by ojeytonwilliams** [comment]
Hi, @shootermv, in order to close the issue, all the specs need to be fixed. Either that or we need to determine that they cannot be fixed and come up with some kind of workaround (i.e. skip them on Firefox).

**Comment by shootermv** [comment]
may be I could get a clue if I look at cypress cloud recording...

**Comment by shootermv** [comment]
I wasn't able to find recording of not-main branches

**Comment by shootermv** [comment]
currently I don't have a clue what exactly makes test to fall...
one I idea I want to try - is to attach my cypress dashboard to fork and try to look there on the recordings, because I wasn't able to see them at public dashboard...

**Comment by shootermv** [comment]
so far, the situation is: I managed to "solve" problem with 1 of two filing tests
the test wants able to figure out - is "focuses the submit button after testing a valid solution"
for some reason the "submit" button which appears the validation is not focused when running at FF

**Comment by shootermv** [comment]
image
tests started to pass after commenting out this code...
must figure out yet - what was this check for

**Comment by ojeytonwilliams** [comment]
Hi @shootermv thanks for updating the PR. Are the changes to the lower-jaw related to the test fixes?

**Comment by shootermv** [comment]
No. I restore the old lower-jaw to its original situation

**Review by ojeytonwilliams — APPROVED** [review]
It's difficult to be sure that flakiness has gone, but I'm happy to give these changes a go.

Nice work, @shootermv :+1:

**Review by Sembauke — APPROVED** [review]

**Pull request merged**
