### PR TITLE
Fix curriculum: add hint not to remove text in editor

### LINKED ISSUE #49020: Cat Photo App Step 64
### Describe the Issue

Users often delete the text `No Copyright -` or include it inside of the anchor text. Could we add a line to the instructions preventing this error?

### Affected Page

https://www.freecodecamp.org/learn/2022/responsive-web-design/learn-html-by-building-a-cat-photo-app/step-64

### Your code

Common errors:

```html
       <a href="https://www.freecodecamp.org">freeCodeCamp.org</a>
```

```html
        <a href="https://www.freecodecamp.org">No Copyright - freeCodeCamp.org</a<
```

Target solution:
```html
        No Copyright - <a href="https://www.freecodecamp.org">freeCodeCamp.org</a<
```

### Expected behavior

There should be a way to prevent these common errors.

### Screenshots

_No response_

### System

All

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by marktlinn**
Checklist:

- [ X ] I have read [freeCodeCamp's contribution guidelines](https://contribute.freecodecamp.org).
- [ X ] My pull request has a descriptive title (not a vague title like `Update index.md`)
- [ X ] My pull request targets the `main` branch of freeCodeCamp.
- [ X ] I have tested these changes either locally on my machine, or GitPod.

fix #49020

Add hint not to remove the copyright text, as doing so causes the tests not to pass. Adding this as a hint should provide a reason and avoid confusion for those struggling to pass the tests for this reason. But also doesn't unnecessarily bloat the description section for those that don't have this issue.

### CODE REVIEW

**Comment by bbsmooth** [comment]
To be honest, I'm not sure this proposed change is enough to solve the issue. Part of the issue is that users include the `No Copyright -` text within the link and I don't think this change does enough to prevent that. I think this needs to be hashed out in the issue further before we decide on how to reword this step.

**Comment by marksist300** [comment]
> To be honest, I'm not sure this proposed change is enough to solve the issue. Part of the issue is that users include the `No Copyright -` text within the link and I don't think this change does enough to prevent that. I think this needs to be hashed out in the issue further before we decide on how to reword this step.

With all due respect I disagree about it's relevance in respect to solving the raised issue: the issue raised is specifically about the given `No Copyright -` text being deleted by user's. This PR helps solve that specific issue, for those that have trouble with it.

**Comment by bbsmooth** [comment]
From the first sentence in the issue:

"Users often delete the text No Copyright - or include it inside of the anchor text."

**Comment by marksist300** [comment]
> From the first sentence in the issue:
> 
> 
> 
> "Users often delete the text No Copyright - or include it inside of the anchor text."
> 
> 
> 
> But I really think that these issues need to be dealt with in the instructions, not by adding information to the hints. I see this step come up a lot in the forum, so there is definitely something lacking in the instructions that is not making it clear to the reader what is expected. Hints are indeed valuable, but they should not be used as an alternative to having clear instructions.


The entire quoted sentence is dealt with by the hint introduced in the PR. Of course, I understand where you're coming from, but as you previously stated in your comments in the issue's discussion, people try to place the `anchor` tags inside `p` tags as well, I think if we write a list of imperative instructions about what you should and shouldn't do taking into account every possibility, eventuality or anomaly, we'll actually create more confusion for the majority of user's interacting with this site and attempting to solve this challenge. Providing that information as a hint enables us to allow people to first try and then debug as necessary without creating a lot of additional bloat in the description section of the challenge.

**Comment by Sboonny** [comment]
Because there isn't a suggested string in the original PR, can you move the editor region?

---

I have skimmed through the PR discussion, but here are points that even without the previous discussion, you as a contributor who read our guideline should know.

- This isn't our PR naming convection
- Issues without label help wanted aren't open for contribution for contributors
- You should never add `<br />`, if the text isn't address or poem
- Hints shouldn't be longer than one sentences
- Discussion are on the issue are not in the PR

**Comment by marksist300** [comment]
> Because there isn't a suggested string in the original PR, can you move the editor region?
> 
> 
> 
> ---
> 
> 
> 
> I have skimmed through the PR discussion, but here are points that even without the previous discussion, you as a contributor who read our guideline should know.
> 
> 
> 
> - This isn't our PR naming convection
> 
> - Issues without label help wanted aren't open for contribution for contributors
> 
> - You should never add `<br />`, if the text isn't address or poem
> 
> - Hints shouldn't be longer than one sentences
> 
> - Discussion are on the issue are not in the PR

No worries, that all makes sense and thank you for the points. I've closed the PR. Maybe there should be another issues raised as the current hint that exists is actually over one sentence long and thus violates the contribution guidelines you've referenced, changing it will make them seem less arbitrary 🙂.

**Pull request closed without merging**
