### PR TITLE
fix(curriculum): add test cases to ensure single whitespace

### LINKED ISSUE #49171: Missing test cases: Reuse Patterns Using Capture Groups
On the [Reuse Patterns Using Capture Groups](https://www.freecodecamp.org/learn/javascript-algorithms-and-data-structures/regular-expressions/reuse-patterns-using-capture-groups), there's a missing test case that allows solutions that do not match the requirements.

The requirements read (emphasis added):

> Use capture groups in `reRegex` to match a string that consists of only the same number repeated exactly three times separated by ***single spaces***.

However, there's no test to confirm that a regex only matches single whitespace characters. Consider the following solution:
```js
let reRegex = /^(\d+)\s+\1\s+\1$/;
```
This will match `"42   42 42"` and `"42\t42\t42"`, neither of which meet the requirements of having a single space character delimiting the numbers.

I propose adding two additional test cases to prevent overly-permissive solutions:

````markdown
Your regex should not match the string `42\t42\t42`.

```js
reRegex.lastIndex = 0;
assert(!reRegex.test('42\t42\t42'));
```
````

````markdown
Your regex should not match the string `42  42  42`.

```js
reRegex.lastIndex = 0;
assert(!reRegex.test('42  42  42'));
```
````

See: 
https://github.com/freeCodeCamp/freeCodeCamp/blob/b35e8166c07604ad32618b3439916a754520bbcc/curriculum/challenges/english/02-javascript-algorithms-and-data-structures/regular-expressions/reuse-patterns-using-capture-groups.md?plain=1#L38-L98

### PR DESCRIPTION
**Pull request by javrrr**
Checklist:

- [x] I have read and followed the [contribution guidelines](https://contribute.freecodecamp.org).
- [x] I have read and followed the [how to open a pull request guide](https://contribute.freecodecamp.org/#/how-to-open-a-pull-request).
- [x] My pull request targets the `main` branch of freeCodeCamp.
- [x] I have tested these changes either locally on my machine, or GitPod.

Closes [#49171](https://github.com/freeCodeCamp/freeCodeCamp/issues/49171)

### CODE REVIEW

**Comment by gikf** [comment]
Could you update solution to not match `42\t42\t42`?

**Comment by javrrr** [comment]
> Could you update solution to not match `42\t42\t42`?

Done!

**Review by gikf — APPROVED** [review]
Thanks!

LGTM :+1:

**Review by Sboonny — APPROVED** [review]
LGTM 🎉, thank you for your contribution to the page! 👍.

**Comment by gikf** [comment]
Hi @javrrr. Congrats on your first pull request (PR)! 🎉

Thank you for your contribution to the page! 👍
We are happy to accept these changes and look forward to future contributions. 📝

**Pull request merged**
