### PR TITLE
Create index.md for markdown in R.

### PR DESCRIPTION
**Pull request by SudhakarKuma**
Create index.md for markdown in R.

- [x] I have read [freeCodeCamp's contribution guidelines](https://github.com/freeCodeCamp/freeCodeCamp/blob/master/CONTRIBUTING.md).
- [x] My pull request has a descriptive title (not a vague title like `Update index.md`)
- [x] My pull request targets the `master` branch of freeCodeCamp.
- [x] None of my changes are plagiarized from another source without proper attribution.
- [x] All the files I changed are in the same world language (for example: only English changes, or only Chinese changes, etc.)
- [x] My changes do not use shortened URLs or affiliate links.

Closes #XXXXX

### CODE REVIEW

**Comment by RandellDawson** [comment]
Hi @SudhakarKuma 

You checked off the box ` My pull request has a descriptive title (not a vague title like Update index.md)`, but your PR title does not briefly explain the purpose of the PR.

**Comment by SudhakarKuma** [comment]
@RandellDawson 

Thank you for pointing out. I have now added the descriptive title for my PR.

**Review by thecodingaviator — COMMENTED** [review]
@SudhakarKuma What you've done is change the name of the commit and not the PR, please change the name of the PR from the button next to it

**Comment by SudhakarKuma** [comment]
@thecodingaviator Thanks for your suggestion. I have now changed the title.

**Review by RandellDawson — APPROVED** [review]

**Comment by RandellDawson** [comment]
Thank you for your contribution to the page! 👍
We're happy to accept these changes, and look forward to future contributions. 🎉

**Pull request merged**
