### PR TITLE
fix(curriculum): Update Cat Photo App Step 11/12

### LINKED ISSUE #47631: Cat Photo App - Revenge of Step 12
### Describe the Issue

Step 12 continues to plague users. I would be really good if we can get them to understand "copy-paste the previous anchor element into this new spot" without saying that explicitly.

(Follow-up from discussion on Discord with @bbsmooth @ieahleen @hbar1st)

### Affected Page

https://www.freecodecamp.org/learn/2022/responsive-web-design/learn-html-by-building-a-cat-photo-app/step-12

### Expected behavior

Possible extended wording

> You have now created a link with the text `cat photos`. The words `cat photos` are underlined next to the image in the preview now. You can click on the link now.

> Now, turn the words `cat photos` inside of your `p` element into a new link to `https://freecatphotoapp.com` by placing these words inside of a new anchor element.

### Screenshots

_No response_

### System

All

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by jeremylt**
Checklist:

- [x] I have read [freeCodeCamp's contribution guidelines](https://contribute.freecodecamp.org).
- [x] My pull request has a descriptive title (not a vague title like `Update index.md`)
- [x] My pull request targets the `main` branch of freeCodeCamp.
- [ ] I have tested these changes either locally on my machine, or GitPod.

Closes #47631

### CODE REVIEW

**Comment by Sembauke** [comment]
Hi @jeremylt,

I see you have changed the text between the anchor tags too. But after step 14 you have not changed anything.
Is there any reason behind this.

Thanks for taking this on btw 😄

**Comment by jeremylt** [comment]
My intent is that only the Step 11 anchor text will be different, and the Step 13 will delete this modified text from Step 11. Hopefully I lined up those pieces correctly.

**Review by majestic-owl448 — APPROVED** [review]
I like this, let's see if it helps

**Review by naomi-lgbt — APPROVED** [review]
banger pr, thanks for contributing!

**Pull request merged**
