### PR TITLE
fix(seed/challenges): Change Exact Change algorithm to return single data type

### LINKED ISSUE #16083: "Exact Change" algorithm challenge should return single data type.
#### Challenge Name

https://www.freecodecamp.org/challenges/exact-change

#### Issue Description

My own two cents as an experienced developer is that this problem teaches newcomers that it's totally normal and acceptable for your functions to return completely different types depending on arbitrary input conditions. I know javascript is not statically typed, but this is the stuff that bugs are made of. 

I'd suggest having it at least tag the return value with the type in some way, such as `{registerState: 'CLOSED', change: [...]}` or `{registerState: "INSUFFICIENT_FUNDS", change: []}` etc. As-is, the correct solution wouldn't pass code review at any of the places I've worked. Seems in bad taste to teach it to people that are trying to pass interviews someday.

To clarify, I propose that the function *always* return an object containing a `status` key and a `change` key. The `status` is one of `INSUFFICIENT_FUNDS`, `CLOSED`, `OPEN`, and `change` is a 2D array that is described in the original problem. Examples:

```
{status: "INSUFFICIENT_FUNDS", change: []}  // change should probably always be empty list in this case
{status: "CLOSED", change: [["PENNY", 1.01], ["NICKEL", 2.05]]}
{status: "OPEN", change:  [["TEN", 20.00], ["TWENTY", 60.00]]}
```

Discuss.

### PR DESCRIPTION
**Pull request by scissorsneedfoodtoo**
#### Pre-Submission Checklist

- [x] Your pull request targets the `staging` branch of freeCodeCamp.
- [x] Branch starts with either `fix/`, `feature/`, or `translate/` (e.g. `fix/signin-issue`)
- [x] You have only one commit (if not, [squash](http://forum.freecodecamp.org/t/how-to-squash-multiple-commits-into-one-with-git/13231) them into one commit).
- [x] All new and existing tests pass the command `npm test`. Use `git commit --amend` to amend any fixes.

#### Type of Change

- [x] Small bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds new functionality)
- [ ] Breaking change (fix or feature that would change existing functionality)
- [ ] Add new translation (feature adding new translations)

#### Checklist:

- [x] Tested changes locally.
- [ ] Addressed currently open issue (replace 16083 with an issue no in next line)

Closes #16083

#### Description

Edited the description and tests so that freeCodeCamp users learn to write functions that return a similar data structure type each time.

### CODE REVIEW

**Comment by scissorsneedfoodtoo** [comment]
I just found an error where the first check passes whether the function returns a string, array, or object. Sorry about that. 

Any advice about how to rewrite that test? I can play with it a bit more tomorrow evening.

**Comment by scissorsneedfoodtoo** [comment]
I believe I fixed the problem. Now the first test uses Object.prototype.toString.call to check whether the checkCashRegister function returns a regular object or an array object.

**Comment by scissorsneedfoodtoo** [comment]
Now it seems like I wasn't able to squash the commits properly and there are two. I'll try to fix that later tonight.

**Comment by QuincyLarson** [comment]
@scissorsneedfoodtoo Thanks for improving these tests. We recently moved this challenge to this file: https://github.com/freeCodeCamp/freeCodeCamp/blob/staging/seed/challenges/02-javascript-algorithms-and-data-structures/javascript-algorithms-and-data-structures-projects.json

Could you make the edits on that file and open a new pull request?

**Comment by scissorsneedfoodtoo** [comment]
Of course, no problem. I'll work on it a bit later tonight.

**Comment by QuincyLarson** [comment]
@scissorsneedfoodtoo Awesome! Thanks for your help with this, and your flexibility!

**Comment by scissorsneedfoodtoo** [comment]
My pleasure! I'll open another pull request soon.

**Pull request closed without merging**
