### PR TITLE
Correct paddings in inline code blocks

### LINKED ISSUE #35401: [Challenge descriptions] - Move punctuation inside code blocks/tags?
#### At certain widths, punctuation next to a code block gets pushed to its own line because it treats it like there's a space there, or like it's it's own element or something....

screen shot 2019-02-25 at 8 24 57 am

### A few more examples... 
screen shot 2019-02-25 at 8 16 52 am

<hr>

screen shot 2019-02-25 at 8 18 02 am

### PR DESCRIPTION
**Pull request by 777genius**
- [x] I have read [freeCodeCamp's contribution guidelines](https://github.com/freeCodeCamp/freeCodeCamp/blob/master/CONTRIBUTING.md).
- [x] My pull request has a descriptive title (not a vague title like `Update index.md`)
- [x] My pull request targets the `master` branch of freeCodeCamp.
- [x] None of my changes are plagiarized from another source without proper attribution.
- [x] All the files I changed are in the same world language (for example: only English changes, or only Chinese changes, etc.)
- [x] My changes do not use shortened URLs or affiliate links.

# Before

# After

Closes #35401

### CODE REVIEW

**Comment by thecodingaviator** [comment]
Hi, Thanks for your contributions and these look great, however as part of a feature freeze we have in place due to us being in the final stages of releasing the current `master` branch to production, UI changes are on hold.

We'll have a look at this PR once we are through with the freeze. Thank you for your patience! 😄

**Comment by thecodingaviator** [comment]
The freeze does not cover the scope of the PR a.t.m. so it is good to be QA'd

**Review by ojeytonwilliams — CHANGES_REQUESTED** [review]
Thanks for the PR, it looks good.

Since the pseudo elements are no long being created, please could you remove
https://github.com/freeCodeCamp/freeCodeCamp/blob/b8c2b1a3efe100c0a5b330334d2459530bc42121/client/src/components/layouts/layout.css#L591-L596

Also, removing the pseudo elements means surrounding punctuation behaves correctly, so this fixes #35401

**Comment by iliyaZelenko** [comment]
@ojeytonwilliams did as you requested.

**Comment by thecodingaviator** [comment]
I believe this fixes #35497 , so am adding that to the PR description

**Review by thecodingaviator — APPROVED** [review]
LGTM! 👍

**Review by ojeytonwilliams — APPROVED** [review]

**Comment by ojeytonwilliams** [comment]
@iliyaZelenko Thank you for your contribution to the page! :+1:
We're happy to accept these changes, and look forward to future contributions. :memo:

**Pull request merged**
