### PR TITLE
fix(app): Normalize flash type

### LINKED ISSUE #16395: Normalize flash type
Normalize flash type.
The different level of message types provided by bootstrap are 'info', 'warning', 'danger', 'success'. The express flash system is currently using 'info', 'success', 'errors' (inconsistent with BS style and inconsistent pluralization)

 These should all be normalized to the BS style from front to back.

Relavent code:

https://github.com/freecodecamp/freecodecamp/blob/staging/server/views/partials/flash.jade
https://github.com/freecodecamp/freecodecamp/blob/staging/server/middlewares/error-handlers.js#L33
https://github.com/freecodecamp/freecodecamp/blob/staging/server/views/account/email-signin.jade#L65

(note: this is some not all of the locations where we use flash/alert messages)

### PR DESCRIPTION
**Pull request by cassidypignatello**
#### Pre-Submission Checklist

- [x] Your pull request targets the `staging` branch of freeCodeCamp.
- [x] Branch starts with either `fix/`, `feature/`, or `translate/` (e.g. `fix/signin-issue`)
- [x] You have only one commit (if not, [squash](http://forum.freecodecamp.org/t/how-to-squash-multiple-commits-into-one-with-git/13231) them into one commit).
- [x] All new and existing tests pass the command `npm test`. Use `git commit --amend` to amend any fixes.

#### Type of Change

- [x] Small bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds new functionality)
- [ ] Breaking change (fix or feature that would change existing functionality)
- [ ] Add new translation (feature adding new translations)

#### Checklist:

- [x] Tested changes locally.
- [x] Addressed currently open issue (replace XXXXX with an issue no in next line)

Closes #16395

#### Description
Removed flash message types provided by Express Flash and changed to types provided by Bootstrap.

I also wanted to note that I had an issue seeding the database for the first time. After running `npm run only-once`, the script failed at `node seed` and logged the following error:

```
/freeCodeCamp/seed/index.js:91
                  ...file,
                  ^^^

SyntaxError: Unexpected token ...
    at createScript (vm.js:56:10)
    at Object.runInThisContext (vm.js:97:10)
    at Module._compile (module.js:542:28)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)
    at Module.runMain (module.js:604:10)
    at run (bootstrap_node.js:383:7)
    at startup (bootstrap_node.js:149:9)
```

I went ahead and removed that spread operator from `file` in `index.js` and was able to seed the database successfully and get the application running after that, but thought it was pretty strange that happened. I didn't commit my changes to `index.js` in this PR, but just wanted to call that out in case it's related to a separate issue.

### CODE REVIEW

**Comment by BerkeleyTrue** [comment]
@cassidypignatello I'd suggest reading through the contributing guidelines here https://github.com/freeCodeCamp/freeCodeCamp/blob/staging/CONTRIBUTING.md

You are running an out of date nodejs. You must also rebase you changes on current staging as you are running an out of date version of the repo.

**Review by BerkeleyTrue — CHANGES_REQUESTED** [review]
see comment

**Comment by cassidypignatello** [comment]
Sorry about that, I contribute to another repo that uses an older version of Node and forgot to switch it in NVM before developing here. I've also rebased my staging branch and everything looks up-to-date now. I went ahead and updated the marge conflicts to match what's on staging as well. Please let me know if you need anything else!

**Review by BerkeleyTrue — APPROVED** [review]

**Comment by BerkeleyTrue** [comment]
Thanks for contributing!

Happy Coding

**Pull request merged**
