### PR TITLE
Add tests for mutate const array

### PR DESCRIPTION
**Pull request by techstonia**
#### Pre-Submission Checklist

- [x] Your pull request targets the `staging` branch of freeCodeCamp.
- [x] Branch starts with either `fix/`, `feature/`, or `translate/` (e.g. `fix/signin-issue`)
- [x] You have only one commit (if not, [squash](http://forum.freecodecamp.com/t/how-to-squash-multiple-commits-into-one-with-git/13231) them into one commit).
- [x] All new and existing tests pass the command `npm test`. Use `git commit --amend` to amend any fixes.

#### Type of Change

- [x] Small bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds new functionality)
- [ ] Breaking change (fix or feature that would change existing functionality)
- [ ] Add new translation (feature adding new translations)

#### Checklist:

- [x] Tested changes locally.
- [ ] Closes currently open issue (replace XXXX with an issue no): Closes #XXXX

#### Description

I added couple of tests for http://beta.freecodecamp.com/en/challenges/es6/mutate-an-array-declared-with-const. I actually wanted to add all the test and solve the #14118, but it turns out that checking whether variable is a constant or not is not very straightforward. That's probably because  console.log(code) reveals that s is a var and not a const.

Hope those two extra tests are still useful to merge. :)

### CODE REVIEW

**Comment by dhcodes** [comment]
@techstonia did these tests work locally? I am getting a "Something went wrong" error that seems to be caused by line 4.

**Comment by techstonia** [comment]
I ran `npm test`, which didn't give errors, but now I'm not sure if that was enough? Is there another command for beta features or something like that? :)

**Comment by dhcodes** [comment]
@techstonia I meant if you run `gulp` and go to `localhost:3000` and test the challenge itself. Do the two tests you add work on your end?

**Comment by techstonia** [comment]
@dhcodes No problem. I tried to run it locally again. This code makes the tests pass:
`
const s = [ 5, 7, 2 ];
// change code below this line
//s = [2, 5, 7];
s[0] = 2;
s[1] = 5;
s[2] = 7;
// change code above this line
// Test your code
console.log(s);
`

But maybe you meant that the default code gives the error and it's not very descriptive to the user?

screen shot 2017-04-06 at 18 30 14

**Comment by dhcodes** [comment]
@techstonia I've taken another look at this and you're right, the previous error is unrelated to your changes. That said, I'm a bit confused by the wording here. Can you change the message on the second test to be "`s` is equal to `[2, 5, 7]`" as there are more than one way to complete this and "is sorted" does not reflect how the items are being reassigned in the example.

**Comment by techstonia** [comment]
@dhcodes sure! It takes a bit time as I'm on vacation without my laptop. I'll bing you in this thread after I have made changes.

**Review by JsaGrabass — APPROVED** [review]

**Comment by techstonia** [comment]
@dhcodes Thanks for the suggestion on wording! I now finally managed to get behind my laptop and made the changes. ;)

**Comment by dhcodes** [comment]
Thanks @techstonia. **LGTM** 👍 💯 🌮

**Pull request merged**
