### PR TITLE
Challenges of Intermediate Algorithm Scripting translated into French

### LINKED ISSUE #7640: French translation of Intermediate Algorithm Scripting
- [x] Sum All Numbers in a Range 
- [x] Diff Two Arrays 
- [x] Roman Numeral Converter 
- [x] Where art thou 
- [x] Search and Replace 
- [x] Pig Latin 
- [x] DNA Pairing 
- [x] Missing letters 
- [x] Boo who 
- [x] Sorted Union 
- [x] Convert HTML Entities 
- [x] Spinal Tap Case 
- [x] Sum All Odd Fibonacci Numbers 
- [x] Sum All Primes 
- [x] Smallest Common Multiple 
- [x] Finders Keepers 
- [x] Drop it 
- [x] Steamroller 
- [x] Binary Agents 
- [x] Everything Be True 
- [x] Arguments Optional

### PR DESCRIPTION
**Pull request by NaitoKenzo**
Closes #7640

### CODE REVIEW

**Comment by theflametrooper** [comment]
@NaitoKenzo Someone needs to verify the translation before this pr is merged.

**Comment by theflametrooper** [comment]
@fnonga Could you verify this?

**Comment by elazzabi** [comment]
@theflametrooper I reviewed the translation. It's good :+1:

**Comment by theflametrooper** [comment]
@elazzabi Thanks so much!

**Pull request merged**
