### PR TITLE
Fixed grammar - replaced 'but' with 'by'

### LINKED ISSUE #2479: Incorrect Grammar
Challenge http://www.freecodecamp.com/challenges/waypoint-generate-random-whole-numbers-with-javascript has an issue. Please describe how to reproduce it, and include links to screenshots if possible.

When test 3 does not pass it should read "You should have multiplied the result of Math.random **by** 10 to make it a number that's greater then zero" instead of, "You should have multiplied the result of Math.random **but** 10 to make it a number that's greater then zero".

### PR DESCRIPTION
**Pull request by uwaseem**
This is for issue 2479 on waffle board.

closes #2479

### CODE REVIEW

**Comment by abhisekp** [comment]
@uwaseem waffle board issues and issues here are the same. 
And you could refer issues by prepending a `#` symbol like #2479

**Comment by uwaseem** [comment]
didn't know that, sorry. will keep that in mind though for future uses, thanks !!

**Comment by abhisekp** [comment]
@uwaseem When referring to someone's reply in pull request, you can write `@uwaseem`.
Also in you commit message and/or in the pull request you can write `close #2479` to close the issue automatically after the merge of PR.

**Read:** [Writing great commit messages](https://github.com/FreeCodeCamp/FreeCodeCamp/wiki/Writing-great-git-commit-message) and [Closing issues via commit messages](https://help.github.com/articles/closing-issues-via-commit-messages/)

**Comment by uwaseem** [comment]
@abhisekp thank you for the links. I have read them and will adhere to them in the future.

**Pull request merged**
