### PR TITLE
Combining the profile picture and the brownie points into a single a

### PR DESCRIPTION
**Pull request by meetmangukiya**
#### Pre-Submission Checklist

- [x] Your pull request targets the `staging` branch of FreeCodeCamp.
- [x] Branch starts with either `fix/`, `feature/`, or `translate/` (e.g. `fix/signin-issue`)
- [x] You have only one commit (if not, [squash](http://forum.freecodecamp.com/t/how-to-squash-multiple-commits-into-one-with-git/13231) them into one commit).
- [ ] All new and existing tests pass the command `npm run test-challenges`. Use `git commit --amend` to amend any fixes.
#### Type of Change

- [x] Small bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds new functionality)
- [ ] Breaking change (fix or feature that would change existing functionality)
- [ ] Add new translation (feature adding new translations)
#### Checklist:

- [ ] Tested changes locally.
- [x] Closes currently open issue (replace XXXX with an issue no): Closes #XXXX
#### Description

If applied this commit will combine the profile picture and the number
of brownie
points the user has earned into a single anchor

Closes https://github.com/FreeCodeCamp/FreeCodeCamp/issues/10581

### CODE REVIEW

**Comment by meetmangukiya** [comment]
@hallaathrad #10581 I am not really sure if this will **really** make the profile picture light up on hover. I think there's more code to change then this.

**Comment by hallaathrad** [comment]
@meetmangukiya my friend! I've checked the PR and it should've worked perfectly... except for the fact that was for the old version of the site (which has been replaced for a React version of the same items). 
Afraid I've misrepresented this issue for a simpler one... thanks for your effort!!! 

Wanna give the react one a shot, and update the PR? 
screen shot 2016-09-10 at 22 42 30

**Comment by meetmangukiya** [comment]
I afraid I don't understand .jsx well, I'll try though :D

**Comment by meetmangukiya** [comment]
I'm definitely going to need some help :disappointed: The profile pic is in `Avatar-Nav-Item.jsx` and the brownie points is in `Points-Nav-Item.jsx` I think we'll have to merge both the files and have a single return statement with a single `li` enclosing the both. Correct me if I am wrong :confused:

**Comment by hallaathrad** [comment]
Yep, my assumptions pointed towards the same files. However my knowledge of react/jsx are limited :S Will close this PR and we can try a different one afterwards, if you want to give it a try

**Pull request closed without merging**
