### PR TITLE
fix: re-order and update sign in CTA styles on completion modal

### LINKED ISSUE #37878: No need for completion animation when not logged in
If a user is not logged in, the newly implemented completion animation along with the section name above it (see below) are not needed.  Also, it will always show `0% complete` which does not really serve any purpose for the end user.  I suggest hiding this feature unless logged in.

image

### PR DESCRIPTION
**Pull request by thecodingaviator**
- [x] I have read [freeCodeCamp's contribution guidelines](https://github.com/freeCodeCamp/freeCodeCamp/blob/master/CONTRIBUTING.md).
- [x] My pull request has a descriptive title (not a vague title like `Update index.md`)
- [x] My pull request targets the `master` branch of freeCodeCamp.
- [x] None of my changes are plagiarized from another source without proper attribution.
- [x] All the files I changed are in the same world language (for example: only English changes, or only Chinese changes, etc.)
- [x] My changes do not use shortened URLs or affiliate links.

Closes #37878

### CODE REVIEW

**Comment by raisedadead** [comment]
Can you throw in a few screenshots of how this looks? And while you are at this, can you please add a couple tests.

**Comment by thecodingaviator** [comment]
I’ll drop some over the weekend. Thinking if there’s a way I can get it to look better than how it looks now.

**Comment by thecodingaviator** [comment]
@raisedadead This is how it looks a.t.m.:
image

**Comment by raisedadead** [comment]
Yup. I was guessing that looking at the code. Let me get back to you on what we would want it to be like.

/cc @ahmadabdolsaheb

**Comment by ahmadabdolsaheb** [comment]
> @raisedadead This is how it looks a.t.m.:
> image

so the logic should be flipped since now it does not show the modal body for signed in users.

Also it completely removes the completion checkmark that we had before rolling out the percentages.

we could alter that from inside the modal body component if we would like to completely remove it.

I will cc @moT01 since he has more context.

Also since you are working on this, I would appreciate it if you could the sign in button the modal footer a CTA similar to the one we have on the main page and putting it on the top of the button stack.

Thank you

**Comment by thecodingaviator** [comment]
@ahmadabdolsaheb How about having a prop passed to the component which decided whether the progress bar is displayed or not rather than putting a conditional where I have put it. The tick can just render anyway

**Comment by moT01** [comment]
I think it looks a little bare without the checkmark there. Yes, @thecodingaviator, that's how I would do anyway. Pass `isSignedin` to the modal body and conditionally render the stuff you need in there.

**Comment by thecodingaviator** [comment]
@moT01 @ahmadabdolsaheb @raisedadead Does it look okay to you now?

**Comment by moT01** [comment]
Looks like the tests aren't passing anymore. The .test file may need to be updated along with the snapshot.

**Comment by thecodingaviator** [comment]
I'll work on fixing and/or writing tests for this today @moT01

**Comment by thecodingaviator** [comment]
@ahmadabdolsaheb @raisedadead, @ojeytonwilliams worked on the tests, guiding me through them. How does the PR look to you now?

**Review by raisedadead — CHANGES_REQUESTED** [review]
See https://github.com/freeCodeCamp/freeCodeCamp/issues/37878#issuecomment-565996667

- Update the PR to have the CTA in the orange cta color
- Re-order the CTA to be the top button.
- Revert the progress related changes.

**Review by raisedadead — APPROVED** [review]

**Pull request merged**
