### PR TITLE
feat(LoopBack): Upgrade to LoopBack 3

### LINKED ISSUE #12780: [build] Update loopback components and migrations for gulp warnings in build.
As of today, there is a verbose error in the gulp log as below:
```
The user model "User" is attached to an application that does not specify
whether other sessions should be invalidated when a password or
an email has changed. Session invalidation is important for security
reasons as it allows users to recover from various account breach
situations.

We recommend turning this feature on by setting
"logoutSessionsOnSensitiveChanges" to true in
server/config.json (unless you have implemented your own solution
for token invalidation).

We also recommend enabling "injectOptionsFromRemoteContext" in
User's settings (typically via common/models/*.json file).
This setting is required for the invalidation algorithm to keep 
the current session valid.


The user model "user" is attached to an application that does not specify
whether other sessions should be invalidated when a password or
an email has changed. Session invalidation is important for security
reasons as it allows users to recover from various account breach
situations.

We recommend turning this feature on by setting
"logoutSessionsOnSensitiveChanges" to true in
server/config.json (unless you have implemented your own solution
for token invalidation).

We also recommend enabling "injectOptionsFromRemoteContext" in
user's settings (typically via common/models/*.json file).
This setting is required for the invalidation algorithm to keep 
the current session valid.
```

### PR DESCRIPTION
**Pull request by raisedadead**
This upgrades LoopBack to v3.x.x

- [x]  Update LoopBack version
- [x]  Update use of REST error handler
- [x]  Replace LoopBack middleware “getter” properties 
- [ ]  Update models
- [x]  Update models derived from PersistedModel
- [x]  Explicitly add User model properties that were removed
- [ ]  Remove use of `current-context` methods, middleware, and configuration settings
- [ ]  Check request parameter encoding
- [x]  Update use of promises
- [x]  Check CORS configuration

More details of the checklist:
https://gist.github.com/raisedadead/22f7a38bb47204fded9b0877fde954ef

Closes #12780

### CODE REVIEW

**Comment by fizzvr** [comment]
Why blocked? seems nice to upgrade the project, idk

**Comment by raisedadead** [comment]
>Why blocked? seems nice to upgrade the project, idk

It's a WIP actually but is blocked because some of other PR's especially those touching the models will have to land before this goes in.

Please feel free to pull down and test though.

**Comment by raisedadead** [comment]
I think this is ready for a QA. I have three items on the checklist that I am confident that I have done a review of, but unsure and would love a second set of eyes.

**Comment by BerkeleyTrue** [comment]
Thanks for the PR. How much QA will this need. It seems to simple to be the only required changes.

**Comment by raisedadead** [comment]
Honestly, this adds only the most minimum of changes needed to move to LB3, thanks to the fact that we do not use much of the features of Loopback.

You have already fixed a ton of issues with the error handling and the promise handling by customising it.

To, my best knowledge we should be safe, by merging this.
This is better than having the 2.x which is having tons of unhandled issues and isn't receiving any upgrades in a long time.

My advise though is to schedule this one of the incremental candidates in the RC plan, and roll back just one this if you do see issues, which I am hoping that you might not have to.

**Comment by BerkeleyTrue** [comment]
The code looks good as far as I can see. Since loopback touches so many things I don't want to leave this till RC. I'm completely frustrated with loopbacks 2.0 LTS not fixing anything. I'll merge this in and update beta.

**Comment by raisedadead** [comment]
Sure, thanks!

**Comment by BerkeleyTrue** [comment]
May have spoke to soon. I'm getting `cannot find adler32` when trying to run node seed. Doesn't seem like the package lock file is complete. I'lll remedy this shortly

**Pull request merged**
