### PR TITLE
fix(curriculum): Add tests for setter, getter and setting a temperature (es6 tests)

### LINKED ISSUE #17403: ES6 - Use getters and setters to Control Access to an Object: Confusing?
#### Describe your problem and - if possible - how to reproduce it
The exercise can pass with just one line of code.
```js
  /* Alter code below this line */
  class Thermostat {}
  /* Alter code above this line */
```
It doesn't test what it should be testing.

I think the instructions can be made clearer. This is what I have in mind:

> Use the `class` keyword to create a `Thermostat` class. It should have a constructor that accepts a temperature in degrees Fahrenheit.
> 
> Now create a getter and a setter called `temperature` [or `celsius`, or `tempCelsius`, or `temperatureC`; they're clearer, but changing to any of these needs changes in the last few lines of the code as well] in the class. The getter should return the temperature in degrees Celsius. The setter should accept a temperature in degrees Celsius.
> 
> Remember that &deg;C = 5/9 * (&deg;F - 32) and &deg;F = &deg;C * 9/5 + 32.
> 
> Note that while the constructor requires a temperature in Fahrenheit, you can store the temperature internally in either Fahrenheit or Celsius. What's important is that the getter returns the temperature in Celsius and the setter accepts a temperature in Celsius.
> 
> This is the power of getters and setters - you are creating an API for another user, who would get the correct result, no matter how you implement them.
> 
> In other words, you are abstracting implementation details from the consumer.
> 

#### Add a Link to the page with the problem
https://learn.freecodecamp.org/javascript-algorithms-and-data-structures/es6/use-getters-and-setters-to-control-access-to-an-object/

### PR DESCRIPTION
**Pull request by entwicklerfr**
- [x] I have read [freeCodeCamp's contribution guidelines](https://github.com/freeCodeCamp/freeCodeCamp/blob/master/CONTRIBUTING.md).
- [x] My pull request has a descriptive title (not a vague title like `Update index.md`)
- [x] My pull request targets the `master` branch of freeCodeCamp.
- [x] None of my changes are plagiarized from another source without proper attribution.
- [x] All the files I changed are in the same world language (for example: only English changes, or only Chinese changes, etc.)
- [x] My changes do not use shortened URLs or affiliate links.

Closes #17403

This PR is about the following curriculum:
javascript-algorithms-and-data-structures >  es6 >  use-getters-and-setters-to-control-access-to-an-object

As described in the issue #17403, and even if the test suite was modified since the last issue update, this current PR provides 3 new tests:
- test if a getter is declared
- test if a setter is declared
- test if setting the temperature updates the previous temperature as described [here](https://github.com/freeCodeCamp/freeCodeCamp/issues/17403#issuecomment-405969306)

Adding the 2 first tests is usefull to detect this type code snippet which passes the current test suite:
`
// my class
function Thermostat(fahrenheit) {
    this._tempInCelsius = 5/9 * (fahrenheit - 32);
    this.temperature = this._tempInCelsius    
}
`

### CODE REVIEW

**Comment by RandellDawson** [comment]
@entwicklerfr At least one of your new tests is failing with a valid solution.

**Comment by entwicklerfr** [comment]
@RandellDawson, Travis CI has shown me the way :-). It was the third test. It's fixed. Thx.

**Comment by scissorsneedfoodtoo** [comment]
Thank you for improving this challenge, @entwicklerfr. Checked with all of the workarounds / incorrect solutions listed in https://github.com/freeCodeCamp/freeCodeCamp/issues/17403 and your new tests prevent any of them from passing.

Will wait for another reviewer to check this out before merging.

**Review by scissorsneedfoodtoo — APPROVED** [review]

**Comment by ojeytonwilliams** [comment]
@entwicklerfr Congrats on your first pull request (PR)! 🎉

Thank you for your contribution to the page! 👍
We're happy to accept these changes, and look forward to future contributions. 📝

**Pull request merged**
