### PR TITLE
Change challengeSeed in accessing nested objects

### LINKED ISSUE #13472: Accessing Nested Objects Suggestion
```// Setup
var myStorage = {
  "car": {
    "inside": {
      "glove box": "maps",
      "passenger seat": "crumbs"
     },
    "outside": {
      "trunk": "jack"
    }
  }
};

// Only change code below this line

var gloveBoxContents = "" ; // Change this line
```

Hello, I'm quite new to programming but I thought it's a good idea to grow a pair and learn go to give feedback(and receive as well).

I completed this challenge but my issue with it is that it can be confusing.
The element that is a bit confusing and misleading is the "" notation after var gloveBoxContents =.
Although if a camper remembers the previous lessons when searching through objects i'm sure there won't be much of an issue.
My overall impression was that I had to write a completely new line above the var gloveBoxContents.

My issue is more in regards to clarity.

I hope I was helpful.

One peace.

### PR DESCRIPTION
**Pull request by Manish-Giri**
#### Pre-Submission Checklist

- [x] Your pull request targets the `staging` branch of freeCodeCamp.
- [x] Branch starts with either `fix/`, `feature/`, or `translate/` (e.g. `fix/signin-issue`)
- [x] You have only one commit (if not, [squash](http://forum.freecodecamp.com/t/how-to-squash-multiple-commits-into-one-with-git/13231) them into one commit).
- [x] All new and existing tests pass the command `npm test`. Use `git commit --amend` to amend any fixes.

#### Type of Change

- [x] Small bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds new functionality)
- [ ] Breaking change (fix or feature that would change existing functionality)
- [ ] Add new translation (feature adding new translations)

#### Checklist:

- [x] Tested changes locally.
- [x] Closes currently open issue (replace XXXX with an issue no): Closes #13472 

#### Description

Updated `challengeSeed` to replace `""` with `undefined`. Removed a comment and extra new line.

screenshot 2017-02-25 01 33 53

Note - this does throw a warning though (redundant assignment to `undefined`). 

screenshot 2017-02-25 01 34 04

Closes #13472

### CODE REVIEW

**Review by Greenheart — COMMENTED** [review]
@Manish-Giri I think the warning about undefined would be helpful in this case - it shows campers that it's a bad practice to initiate variables to undefined, while also making it clearer where they should make the change.

If we don't want this warning, another solution to the referenced issue could be to simply write `var gloveBoxContents;`

**Comment by Manish-Giri** [comment]
@Greenheart I also think that the warning is fine. I just wanted to point out that there *is* a warning.

**Comment by Greenheart** [comment]
@Manish-Giri Thanks for doing that!

Do you think the second option (`var gloveBoxContents;`) would be cleaner?

**Comment by Manish-Giri** [comment]
@Greenheart I think using `undefined` is still clearer, as the camper would know that they are required to change the expression to replace `undefined` with the correct value. Maybe we could replace the comment `// Only change code below this line` to `// Change this line`, to be even more explicit?

While the second option `var gloveBoxContents;` is also a good one, I can imagine campers doing something like this - 
```
var gloveBoxContents;
gloveBoxContents = ...
```

**Comment by Greenheart** [comment]
@Manish-Giri The comment change is a great idea!

So, lets go for the following then?
`var gloveBoxContents = undefined;  // Change this line`

**Comment by Manish-Giri** [comment]
@Greenheart Yep! let's do this 👍

**Comment by Manish-Giri** [comment]
@Greenheart Done!

**Review by erictleung — APPROVED** [review]

**Review by Greenheart — APPROVED** [review]

**Pull request merged**
