### PR TITLE
fixed typos on basic-javascript challenge

### PR DESCRIPTION
**Pull request by EmaJP**

### CODE REVIEW

**Comment by abhisekp** [comment]
@EmaJP why did you delete it? it looks good

**Comment by ltegman** [comment]
@abhisekp I think it's because there's a missing space after the word return, but @EmaJP you can just amend you commit and force push to update this PR, no need to close it and start over! :smile:

**Comment by EmaJP** [comment]
Didn't know that deleting the branch would close it :p sorry!

**Comment by abhisekp** [comment]
@EmaJP use the COM1000 to make updates

**Comment by abhisekp** [comment]
@ltegman the space is not required after the return keyword if there is a string after it.

**Comment by EmaJP** [comment]
Thanks for the info, will check it out @abhisekp

**Comment by ltegman** [comment]
@abhisekp This is not code, this is an english sentence and even if it were code we don't leave badly formatted code in the FCC codebase just because it would work.

@EmaJP Please add a space after the word `return` that you added in the test messages and then `git add . && git commit --amend && git push -f` to amend your commit and force push the update to this PR.

**Comment by ltegman** [comment]
Closing in favor of the new PR #5681

**Pull request closed without merging**
