### PR TITLE
refactor: separate public and private plugins

### PR DESCRIPTION
**Pull request by ojeytonwilliams**
Checklist:

- [x] I have read and followed the [contribution guidelines](https://contribute.freecodecamp.org).
- [x] I have read and followed the [how to open a pull request guide](https://contribute.freecodecamp.org/how-to-open-a-pull-request/).
- [x] My pull request targets the `main` branch of freeCodeCamp.
- [x] I have tested these changes either locally on my machine, or GitPod.

Slightly rejigs the api's organisation - hopefully making it clearer which endpoints require auth and which do not.

Ref: #54143

### CODE REVIEW

**Review by naomi-lgbt — APPROVED** [review]

**Comment by ojeytonwilliams** [comment]
Hey @naomi-lgbt, I included one change (protecting /signout) since your review. If it's too annoying to review, I'll split the PR.

**Comment by ShaunSHamilton** [comment]
What do you think about refactoring more so we can have the below?

```ts
import * as publicRoutes from "./routes/public";
import * as protectedRoutes from "./routes/public";
```

**Comment by ojeytonwilliams** [comment]
> What do you think about refactoring more so we can have the below?
> 
> ```ts
> import * as publicRoutes from "./routes/public";
> import * as protectedRoutes from "./routes/public";
> ```

Works for me :+1:

**Review by ShaunSHamilton — APPROVED** [review]
LOTM :thumbsup:

Potentially, in the future, we can rename some of those variables like: `protectedCertificateRoutes`, `userPublicGetRoutes`, `unprotectedCertificateRoutes`

**Pull request merged**
