### PR TITLE
Fixes a Typo in Project Euler Problem 70

### LINKED ISSUE #38776: Fix Project Euler: Problem 70 Typo
**Describe your problem and how to reproduce it:**
Following this post on the forum: https://www.freecodecamp.org/forum/t/project-euler-problem-70-totient-permutation-error-in-description/377577

The instructions should have `1 < n < 107`, be `1 < n < 10**7`.

**Add a Link to the page with the problem:**
https://www.freecodecamp.org/learn/coding-interview-prep/project-euler/problem-70-totient-permutation

First-timers welcome.

### PR DESCRIPTION
**Pull request by daksh-goyal**
Checklist:

- [x] I have read [freeCodeCamp's contribution guidelines](https://contribute.freecodecamp.org).
- [x] My pull request has a descriptive title (not a vague title like `Update index.md`)
- [x] My pull request targets the `master` branch of freeCodeCamp.
- [x] All the files I changed are in the same world language, for example: only English changes, or only Chinese changes, etc.

Closes #38776 

Line 15 changed for a minor typo.

### CODE REVIEW

**Review by moT01 — CHANGES_REQUESTED** [review]
maybe have a look at the [sup tag](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/sup)?

**Comment by daksh-goyal** [comment]
Please have a look at the updated markdown. I hope this fixes everything.

**Review by moT01 — APPROVED** [review]
LGTM @daksh-goyal 🎉  

For future reference, you should not make changes directly to your master branch. You should create a new branch to make changes on and it should follow a format. See `#3` just below [here in the docs](https://github.com/freeCodeCamp/freeCodeCamp/blob/master/docs/how-to-setup-freecodecamp-locally.md#making-changes-locally)

**Review by ShaunSHamilton — APPROVED** [review]
LGTM 👍

**Comment by moT01** [comment]
🎉 Congratulations on your first contribution to freeCodeCamp @daksh-goyal 🎉

**Pull request merged**
