### PR TITLE
Refactor ES6 Challenges

### PR DESCRIPTION
**Pull request by Ethan-Arrowood**
#### Pre-Submission Checklist

- [x] Your pull request targets the `staging` branch of freeCodeCamp.
- [x] Branch starts with either `fix/`, `feature/`, or `translate/` (e.g. `fix/signin-issue`)
- [x] You have only one commit (if not, [squash](http://forum.freecodecamp.org/t/how-to-squash-multiple-commits-into-one-with-git/13231) them into one commit).
- [x] All new and existing tests pass the command `npm test`. Use `git commit --amend` to amend any fixes.

#### Type of Change

- [x] Small bug fix (non-breaking change which fixes an issue)

#### Checklist:

- [x] Tested changes locally. ✅ QA'd locally on livestream!
- [x] Addressed currently open issue 

Reference #16254

#### Description

Refactored first 13 challenges with function scope `"use strict";` syntax

### CODE REVIEW

**Comment by QuincyLarson** [comment]
@Ethan-Arrowood OK - I started QA'ing these and I'm still having a few problems with them:

learn_to_code___freecodecamp

learn_to_code___freecodecamp

**Comment by Ethan-Arrowood** [comment]
@QuincyLarson working on these live right now! The error you ran into has something to do with the self calling function declaration. I'm updating them to look nicer now and still use `"use strict";`

**Comment by Ethan-Arrowood** [comment]
TODO: Test `Declare a Read-Only Variable with the const Keyword` with: https://github.com/freeCodeCamp/freeCodeCamp/pull/16263#pullrequestreview-85367841

**Comment by QuincyLarson** [comment]
I'm still encountering a few issues like this one:
learn_to_code___freecodecamp

Also, these test messages should be improved. "`i` is `let`" basically tells people what to do directly, when we should be reinforcing concepts like "`i` should be variable that is only defined within the scope of the function (by using `let`)" or something like that.

**Comment by Ethan-Arrowood** [comment]
@QuincyLarson `sentence` needs to capitalized in this test. The tests even have the `SENTENCE` in it, and the instructions mention right at the end to `rename variables declared with const to conform to common practices.`

Thank you for the feedback on the test messages. That is the kind of feedback I really need because I wasn't sure of the balance between being vague and challenging versus providing enough of a hint to get them through it without looking at the instructions. 
I'll see what I come up with for these descriptions.

**Comment by QuincyLarson** [comment]
@Ethan-Arrowood Per our discussion, I'm going to go ahead and merge this to get all the improved tests and test messages into the beta codebase. Please open an additional PRs as you're able to make further improvements.

**Pull request merged**
