### PR TITLE
updated signature URL to freecodecamp CDN

### LINKED ISSUE #34834: Quincy's signature is not showing up
This may not be the best place to discuss it but the signature on the certifications does not show up if your country has blocked imgur.com. I live in Turkey and apparently, our government decided to put imgur.com down too, alongside with all the other useful web services. 

This is also a problem for future employers since we're listing the certificates on our LinkedIn profile. They basically don't see them fully if they don't use VPN.

So, it would be better to use a CDN service for serving static files.

### PR DESCRIPTION
**Pull request by saranshkataria**
- [x] I have read [freeCodeCamp's contribution guidelines](https://github.com/freeCodeCamp/freeCodeCamp/blob/master/CONTRIBUTING.md).
- [x] My pull request has a descriptive title (not a vague title like `Update index.md`)
- [x] My pull request targets the `master` branch of freeCodeCamp.
- x ] None of my changes are plagiarized from another source without proper attribution.
- x ] All the files I changed are in the same world language (for example: only English changes, or only Chinese changes, etc.)
- [x] My changes do not use shortened URLs or affiliate links.

Closes #34834

### CODE REVIEW

**Comment by caglarturali** [comment]
I assume this project needs to be rebuilt after making changes to the codebase but I'm not sure how it goes. So, I'd appreciate if someone explains to me how it's deployed. :confused: I think we have CI/CD pipelines involved here.

**Review by raisedadead — APPROVED** [review]
Code changes LGTM. @QuincyLarson can you sign off on this? 

Here is the URL:
https://cdn.freecodecamp.org/platform/english/images/quincy-larson-signature.svg

While I am OK with SVG, I think it still needs your Sign-off for accuracy.

**Comment by raisedadead** [comment]
@caglarturali 

This will take us a while, before we can get this deployed on production. We are currently under a freeze while we prep the next release for freeCodeCamp.

Thanks for your patience.

**Comment by caglarturali** [comment]
@raisedadead OK, thanks for the reply.

**Comment by QuincyLarson** [comment]
@raisedadead It seems strange to say this but yes - I sign off on my signature 😄

**Comment by raisedadead** [comment]
Thanks @QuincyLarson 😄 !

@caglarturali and @saranshkataria thanks for working on this issue and raising the pull request.

Happy contributing!

**Pull request merged**
