### PR TITLE
add solution to meet-the-node-console challenge

### PR DESCRIPTION
**Pull request by ambarvm**
add solution to meet-the-node-console challenge in the APIs and Microservices section

- [x] I have read [freeCodeCamp's contribution guidelines](https://github.com/freeCodeCamp/freeCodeCamp/blob/master/CONTRIBUTING.md).
- [x] My pull request has a descriptive title (not a vague title like `Update index.md`)
- [x] My pull request targets the `master` branch of freeCodeCamp.
- [x] None of my changes are plagiarized from another source without proper attribution.
- [x] All the files I changed are in the same world language (for example: only English changes, or only Chinese changes, etc.)
- [x] My changes do not use shortened URLs or affiliate links.

Closes #XXXXX

### CODE REVIEW

**Comment by RandellDawson** [comment]
@supercoww Please hold off on adding any further solutions to the backend challenges until we get a response from @raisedadead.

Thank you,

**Comment by raisedadead** [comment]
See https://github.com/freeCodeCamp/freeCodeCamp/pull/37111#issuecomment-539403870

**Comment by RandellDawson** [comment]
@raisedadead I think we can safely close this PR as the agreed upon comment has been added to the backend challenges in PR #37111  and #37227.

**Comment by moT01** [comment]
Closing in favor of the PR's linked in @RandellDawson's comment.

**Pull request closed without merging**
