### PR TITLE
fix: update notification bar z-index

### LINKED ISSUE #41126: z-index clash on notification bar vs menu
**Describe the bug**
The notification bar has a higher z-index than the menu, making portions of it inaccessible without dismissing a notification.

**To Reproduce**
1. Set your profile to private
2. Attempt to view your certificates
3. After the notification appears, open the menu

**Expected behavior**
I reported this on the forums where [it was suggested](https://forum.freecodecamp.org/t/site-bug-z-index-for-menu-vs-notification/446388) this was not a bug, but it's not how I would expect the z-index to work. 

It's a notification bar not a modal, so it shouldn't block you from doing other activities on the site.

**Screenshots**
image

**Desktop (please complete the following information):**
 - OS: [e.g. iOS] Mac
 - Browser: [e.g. chrome, safari] Chrome
 - Version: [e.g. 22] Version 88.0.4324.150 (Official Build) (x86_64)

**Additional context**

### PR DESCRIPTION
**Pull request by manziEric**
Checklist:

- [x] I have read [freeCodeCamp's contribution guidelines](https://contribute.freecodecamp.org).
- [x] My pull request has a descriptive title (not a vague title like `Update index.md`)
- [x] My pull request targets the `main` branch of freeCodeCamp.
- [x] All the files I changed are in the same world language, for example: only English changes, or only Chinese changes, etc.

Closes #41126

update the z-index of the notification bar to be under the dropdown menu but above the content on the page

### CODE REVIEW

**Review by JoshQuaintance — COMMENTED** [review]
Instead of making the z-index into 1, make it 100, because z-index 1 will actually make the notification bar behind some elements. 100 is the optimal z-index.

**Review by JoshQuaintance — CHANGES_REQUESTED** [review]
Change the 1 into 100`

**Review by raisedadead — DISMISSED** [review]
@ahmadabdolsaheb please confirm and merge if this OK.

**Comment by manziEric** [comment]
> Change the 1 into 100`

@JoshuaPelealu the change of z-index from 1 to 100 is been updated

**Comment by JoshuaPelealu** [comment]
Looks good to me!

**Comment by moT01** [comment]
Attempting to restart the tests...

**Comment by ahmadabdolsaheb** [comment]
The solution works; however, It would be better if we update the z-index of the `flash-message` instead of setting a z-index for `alert`

Here is the link to the line that needs changing https://github.com/freeCodeCamp/freeCodeCamp/blob/main/client/src/components/Flash/flash.css#L10

**Comment by manziEric** [comment]
> The solution works; however, It would be better if we update the z-index of the `flash-message` instead of setting a z-index for `alert`
> 
> Here is the link to the line that needs changing https://github.com/freeCodeCamp/freeCodeCamp/blob/main/client/src/components/Flash/flash.css#L10

@ahmadabdolsaheb i have made the update in flash-message and removed z-index in alert

**Comment by JoshuaPelealu** [comment]
Looks good

**Comment by nhcarrigan** [comment]
image

Issue appears to be resolved.

**Review by naomi-lgbt — APPROVED** [review]
Looks good to me.

@ahmadabdolsaheb would you mind another look when you have the time?

**Pull request merged**
