### PR TITLE
Changes question in 4 Basic Parts of Computer Basics Hike

### LINKED ISSUE #8792: Ambiguous question statement in 4 Basic Parts of Computer Basics Hike
#### Challenge Name
[Computer Basics: The 4 Basic Parts of a Computer](https://www.freecodecamp.com/videos/computer-basics-the-4-basic-parts-of-a-computer) (Quiz Question 1)

#### Issue Description
Question 1 of the "Computer Basics: The 4 Basic Parts of a Computer" quiz (following the reading) asks for a true or false on the following statement: "The computer has 3 basic parts." Now simply referencing the quiz title, one can see the unit review 4 basic parts of a computer, but it can be very confusing based on the wording of the question. The answer could be true, as a computer does have 3 basic parts (and one more). The answer could also be false, as many quiz takers expect 4 basic parts by the name of the unit. To make the question clearer, I propose we rephrase the question to be "The computer has 5 basic parts."

My aim in raising this issue is to make this question more specific, and follow clear logic.

### PR DESCRIPTION
**Pull request by estherfang09**
#### Pre-Submission Checklist

- [ x] Your pull request targets the `staging` branch of FreeCodeCamp.
- [ x] Branch starts with either `fix/`, `feature/`, or `translate/` (e.g. `fix/signin-issue`)
- [x ] You have only one commit (if not, [squash](https://github.com/FreeCodeCamp/FreeCodeCamp/wiki/git-rebase#squashing-multiple-commits-into-one) them into one commit).
- [ ] All new and existing tests pass the command `npm run test-challenges`. Use `git commit --amend` to amend any fixes.
#### Type of Change

- [x ] Small bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds new functionality)
- [ ] Breaking change (fix or feature that would change existing functionality)
- [ ] Add new translation (feature adding new translations)
#### Checklist:

- [ x] Tested changes locally.
- [ ] Closes currently open issue (replace XXXX with an issue no): Closes #8792
#### Description

fix bug 8792 by changing           "The computer has 3 basic parts.",
to   "The computer only has 3 basic parts.",

### CODE REVIEW

**Comment by atjonathan** [comment]
@estherfang09 Please rename your commit to something more relevant like `Fixed test on the 4 Basic Parts of a Computer challenge`. Use `commit --amend` to solve this.

**Comment by atjonathan** [comment]
@estherfang09 You seem to have some unneeded commits. Please drop the following commits using `git rebase -i HEAD~3` and changing `squash` to `drop`:
- `Fixd test on the 4 Basic Parts of a Computer Challenge`
- `Merge branch 'fix/8792' of https://github.com/estherfang09/FreeCodeCamp into fix/8792`

To change the commit name, just edit the original commit using `git commit --amend`.

**Comment by estherfang09** [comment]
Sorry, I am new to git. After doing the git commit --amend. Do I need to re-push to my local branch?

**Comment by atjonathan** [comment]
@estherfang09 Yeh use `git push -f`

**Comment by atjonathan** [comment]
@estherfang09 Unfortunately, you seem to have pushed another unwanted commit. Please `git rebase -i HEAD~2` and remove the unwanted commit. The force push using `git push -f` Thanks!

**Comment by estherfang09** [comment]
git
So Do I need to drop the second commit?

**Comment by atjonathan** [comment]
@estherfang09 Yeh drop `Removed /labs from about page`

**Comment by estherfang09** [comment]
Thx! Hope this time it works

**Comment by atjonathan** [comment]
#### :sparkles: :sparkles: **LGTM :+1:** :sparkles: :sparkles: 

:tada: Thanks for contributing @estherfang09 and congratulations on your first PR submission to FreeCodeCamp! :tada:

**Pull request merged**
