### PR TITLE
fix: minor grammar mistake in 'applied visual design' challenge

### LINKED ISSUE #35798: [beta] Minor grammar mistake in Applied Visual Design: Adjust the Tone of a Color challenge description
**Describe your problem and how to reproduce it:**
There is a grammar mistake in challenge `Applied Visual Design: Adjust the Tone of a Color`'s description.

```
Our nav element currently appears have a cyan background
```

Should be

```
Our nav element currently appears to have a cyan background
```

**Add a Link to the page with the problem:**
https://www.freecodecamp.rocks/learn/responsive-web-design/applied-visual-design/adjust-the-tone-of-a-color

**If possible, add a screenshot here (you can drag and drop, png, jpg, gif, etc. in this box):**

Screen Shot 2019-04-09 at 5 08 48 PM

---

Here is the file that needs to be edited: https://github.com/freeCodeCamp/freeCodeCamp/blob/master/curriculum/challenges/english/01-responsive-web-design/applied-visual-design/adjust-the-tone-of-a-color.english.md

### PR DESCRIPTION
**Pull request by AstiV**
- [x] I have read [freeCodeCamp's contribution guidelines](https://github.com/freeCodeCamp/freeCodeCamp/blob/master/CONTRIBUTING.md).
- [x] My pull request has a descriptive title (not a vague title like `Update index.md`)
- [x] My pull request targets the `master` branch of freeCodeCamp.
- [x] None of my changes are plagiarized from another source without proper attribution.
- [x] All the files I changed are in the same world language (for example: only English changes, or only Chinese changes, etc.)
- [x] My changes do not use shortened URLs or affiliate links.

Closes #35798

### CODE REVIEW

**Comment by RandellDawson** [comment]
@AstiV You need to revert the changes to `package-lock.json` as you did not actually add any packages on this PR.  To do this, you can take the following steps while in the branch `fix/minor-grammar-mistake` locally.
```bash
git checkout HEAD^ -- package-lock.json
git commit --amend
git push --force
```

**Comment by AstiV** [comment]
@RandellDawson Thanks for pointing out my mistake and for providing the steps to revert it. I wasn't entirely shure if `package-lock.json` needs to be commited or not. So rule of thumb is to only commit it, if packages were added?

**Comment by RandellDawson** [comment]
> So rule of thumb is to only commit it, if packages were added?

@AstiV Yes.  Unless you explicitly add new packages to the repo then you definitely should not be pushing changes to `package.json` or `package-lock.json`.

**Comment by AstiV** [comment]
@RandellDawson thanks for explaining!

**Review by RandellDawson — APPROVED** [review]
LGTM

**Review by thecodingaviator — APPROVED** [review]
LGTM! 👍

**Comment by thecodingaviator** [comment]
Thanks for contributing to the freeCodeCamp repository. Congratulations on your first PR! 🎊 

Look forward to more contributions from you! ✈️

**Comment by AstiV** [comment]
Thanks @thecodingaviator! Had a really nice onboarding experience, here. So, I'm quite sure that there will be more contributions from my side 🔥

**Pull request merged**
