### PR TITLE
feat: certification qr

### LINKED ISSUE #47225: Feature Request for certificate - Add QR Code linked to Certificate on FCC Website on Certificate
### Is your feature request related to a problem? Please describe.

Typing the URL given at the bottom of the certificate takes more time and is harder to verify.

So kindly add the requested feature below:

### Describe the solution you'd like

Can you please add a QR Code to the certificate which links to the actual certificate on the freeCodeCamp website for the uniqueness of the certificate (Instead of the usual link that is given below the certificate)? It also takes up lesser space and is easier to scan and verify than to type the usual URL.

It can be like this -

image

### Describe alternatives you've considered

A smaller URL or a Barcode instead of the QR Code is also suitable.

### Additional context

Related Links -

https://www.w3schools.com/js/js_exam.asp

### PR DESCRIPTION
**Pull request by naomi-lgbt**
Checklist:

- [X] I have read [freeCodeCamp's contribution guidelines](https://contribute.freecodecamp.org).
- [X] My pull request has a descriptive title (not a vague title like `Update index.md`)
- [X] My pull request targets the `main` branch of freeCodeCamp.
- [X] I have tested these changes either locally on my machine, or GitPod.

Closes #47225 

I thought I'd play around with this a bit - this seems to work. Not sure if we want to play with the positioning at all.

### CODE REVIEW

**Review by hanswang123456 — COMMENTED** [review]
Looks Good,

**Review by majestic-owl448 — DISMISSED** [review]
It works, I am not sure I like where the QR code is positione

image

cc/ @ahmadabdolsaheb

**Comment by moT01** [comment]
I feel like we should maybe run this by Quincy before adding - or see if some of the rest of the staff is on board. I like it, btw.

**Comment by ahmadabdolsaheb** [comment]
For the positioning, I would bring the QR code in the same row as the signature and give it some right and left margin.

**Comment by vishalscodes** [comment]
Also, can you please shorten the URL given at the bottom of the Certificate? I feel that it is tough to enter the URL on the address bar without the help of a phone.

**Comment by ahmadabdolsaheb** [comment]
We should ship this feature as is and discuss the url shortening further on the issue.

The QR code is good to go. It just need to be smaller and placed on the same row as the signature.

Btw, it is currently covered in certain vewports.
Screen Shot 2022-09-06 at 3 33 46 PM

**Comment by moT01** [comment]
> ...placed on the same row as the signature.

I feel like I would put it down by the verify URL

**Comment by ahmadabdolsaheb** [comment]
@moT01, that sounds like a good idea. My only concern is the long the url. Would you like to share a mock of what you thinking about?

**Comment by moT01** [comment]
I tried to come up with a couple quick mocks...

Screen Shot 2022-09-19 at 11 57 03 AM
Screen Shot 2022-09-19 at 11 58 19 AM

They're not bad - they're not fined tuned CSS wise. The first image is close to what I had in mind. Not sure how small we can make a QR code - but if we can go smaller, it would look a little better. I put the "verify this certification at" text on its own line to give the URL a better chance at fitting on one line. Not sure if we want to do that.

**Review by axljoker03 — COMMENTED** [review]
thanks

**Comment by moT01** [comment]
I gave this a rebase to fix the conflicts and moved the qr code to the bottom rightish:
Dec-09-2022 13-37-28

**Comment by vishalscodes** [comment]
> @moT01, that sounds like a good idea. My only concern is the long the url. Would you like to share a mock of what you thinking about?

Something like this: freecodecamp.org/bbbbbb

**Review by ahmaxed — APPROVED** [review]

**Review by Nirajn2311 — APPROVED** [review]

**Comment by DylanDevelops** [comment]
This looks really awesome @naomi-lgbt! Great feature :)

**Pull request merged**
