### PR TITLE
fix: update user state from server

### PR DESCRIPTION
**Pull request by ahmaxed**
- [x] I have read [freeCodeCamp's contribution guidelines](https://github.com/freeCodeCamp/freeCodeCamp/blob/master/CONTRIBUTING.md).
- [x] My pull request has a descriptive title (not a vague title like `Update index.md`)
- [x] My pull request targets the `master` branch of freeCodeCamp.
- [x] None of my changes are plagiarized from another source without proper attribution.
- [x] All the files I changed are in the same world language (for example: only English changes, or only Chinese changes, etc.)
- [x] My changes do not use shortened URLs or affiliate links.

This pr updates the user state from the changes that happens in the settings page such as adding social urls

Thanks to @scissorsneedfoodtoo for helping with the investigation
ref #37279

### CODE REVIEW

**Comment by raisedadead** [comment]
Add tests please for these, a sample problem use case it the original issue.

**Comment by ojeytonwilliams** [comment]
I've checked this out in Gitpod and the socials still aren't updating.  They do on reload, so the server's fine.

**Comment by ahmadabdolsaheb** [comment]
as you mentioned, the spreadThePayloadOnUser also needs updating.

**Comment by ahmadabdolsaheb** [comment]
@scissorsneedfoodtoo, there are multiple issues with the social buttons.

The links get updated with each change; however, isGithub, isLinkedIn, isTwitter, isWebsite, linkedin (not sure what their purpose are) cause the icons not to render correctly  in  SocialIcons.js.

An example would be when one twitter link is deleted and changes saved.
redux shows that link as empty string but isTwitter is still true.

Another issue is that you cannot delete all of your socials and save changes.

**Comment by ahmadabdolsaheb** [comment]
@raisedadead, I am waiting #37053 to land so I could write more comprehensive tests if that is ok with you.

**Comment by raisedadead** [comment]
> > Add tests please for these, a sample problem use case it the original issue.
> 
> @raisedadead, I am waiting for #37053 to land so I could write more comprehensive tests if that is ok with you.

Respectfully, I disagree.

This line should have had a unit test in place (like it does for other things).

https://github.com/freeCodeCamp/freeCodeCamp/pull/37374/files#diff-c20fd624bd1c17e7fb54d7b971e712d0R249

Things like these could have been caught in unit tests.

I am approving for further QA, though.

**Review by raisedadead — APPROVED** [review]

**Comment by ahmadabdolsaheb** [comment]
image

**Pull request merged**
