### PR TITLE
updated the 'getting started' instruction about adding Bootstrap v3.3.7 instead of v.4 on Codepen

### LINKED ISSUE #13787: Amend the "Get set for our front end development projects" description to make clear to use Bootstrap 3.3.7
#### Challenge Name
https://www.freecodecamp.com/challenges/get-set-for-our-front-end-development-projects

#### Issue Description

As of today Codpen default quick-add is Bootstrap.4 which has some differences from the 3.3.7 version that gets taught during the lessons.

I have noticed and increased number of Camper asking for help in chat asking why their code was not behaving as expected all due to them using version 4.

I propose to amend the description and provide the link to the version 3.3.7 and let the camper insert that.

It's also worth mentioning that in case we proceed with this change we have to change the `.gif` accordingly.

-----
[edit]
The text I'm referring to is at step 6/7:
> Click the gear in the upper left hand corner of the CSS box, then scroll down to "Quick add" and choose Bootstrap.

By doing so the camper will inevitably add the version 4.
We could change it with:
>Click the gear in the upper left hand corner of the CSS box, then in the text field add this link
`https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css`.

And perhaps leaving a note that using the dropdown will load the Alpha version, advising that may encounter some differences in syntax with the lessons's examples.

### PR DESCRIPTION
**Pull request by Marmiz**
#### Pre-Submission Checklist

- [x] Your pull request targets the `staging` branch of freeCodeCamp.
- [x] Branch starts with either `fix/`, `feature/`, or `translate/` (e.g. `fix/signin-issue`)
- [x] You have only one commit (if not, [squash](http://forum.freecodecamp.com/t/how-to-squash-multiple-commits-into-one-with-git/13231) them into one commit).
- [x] All new and existing tests pass the command `npm test`. Use `git commit --amend` to amend any fixes.

#### Type of Change

- [x] Small bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds new functionality)
- [ ] Breaking change (fix or feature that would change existing functionality)
- [ ] Add new translation (feature adding new translations)

#### Checklist:

- [x] Tested changes locally.
- [x] Closes currently open issue (replace XXXX with an issue no): Closes #13787

#### Description

Since the default dropdown on codepen adds the v.4 of Bootstrap, I have amended the text in the "get set for our front-end development project" as follow:

>Click the gear in the upper left hand corner of the CSS box, then copy this link <code>https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css</code> inside the text box. Now give your <code>h1</code> element the class of <code>text-primary</code> to change its color and prove that Bootstrap is now available. Note that by using the dropdown menu and selecting \"Bootstrap\", the Alpha v.4 will be added instead.

And updated the `gif` with a new one that reflect the new functionality, also uploaded on `imgur` [here](http://i.imgur.com/oLYs8EA.gif)

NOTE: This fix will also require to update the available translation for this challenge seed: *spanish - russian - portughese-

### CODE REVIEW

**Comment by raisedadead** [comment]
Code LGTM.

**Review by raisedadead — APPROVED** [review]

**Comment by dhcodes** [comment]
@Marmiz I think this needs a better gif imho. The one here is a low resolution. Any way to improve it? I'll merge it in if you can get a higher res gif.

**Comment by raisedadead** [comment]
@dhcodes I am merging this in and opening a new issue for tracking the higher resolution gif.
@Marmiz Thanks for the pull request!

Happy fixing!

**Comment by Unabashedley** [comment]
I'm too much of a noob to know if I'm missing something... but this seems to be still not fixed? I checked and the instructions are still not amended to the above and the issue keeps popping up in the forum...
https://forum.freecodecamp.com/t/bootstrap-issues-with-codepen/118274
https://forum.freecodecamp.com/t/text-not-centering-ughh/118006

Just, um,  wondering :)

**Comment by raisedadead** [comment]
Hi @Unabashedley This PR has been merged into the beta website (staging) branch. I believe you are pointing out the discussion on the main website?

Can you open a fresh issue just in case?

**Comment by raisedadead** [comment]
Also just to note that the changes will NOT reflect in the main website until the new curriculum is out of beta.

**Pull request merged**
