### PR TITLE
fix: Clear search input of home page on search #52322

### LINKED ISSUE #52322: Clear search input of home page on search
### Describe the Issue

When we search on [news page](https://www.freecodecamp.org/news), the search field gets cleared on search. But, when we search on [home page](https://www.freecodecamp.org) results will open on a separate tab "/news" with the search query and the origin tab still has the searched query.

### Affected Page

https://www.freecodecamp.org/

### Steps to Reproduce

1. Go to [freecodecamp](https://www.freecodecamp.org/)
2. Click on the search field and type your query then press enter
3. A separate tab "/news" is open with the searched query
4. The origin tab search field is not clear and still has the searched query

### Expected behavior

As performing a search on [home page](https://www.freecodecamp.org/) the result shows on a separate tab, the origin tab search field should get cleared.

### Screenshots

_No response_

### System

- Device: Laptop
- OS: macOS
- Browser: Chrome

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by Asifdecoder**
Checklist:

- [ x] I have read and followed the [contribution guidelines](https://contribute.freecodecamp.org).
- [x ] I have read and followed the [how to open a pull request guide](https://contribute.freecodecamp.org/#/how-to-open-a-pull-request).
- [ x] My pull request targets the `main` branch of freeCodeCamp.
- [ x] I have tested these changes either locally on my machine, or GitPod.

Closes #52322

### CODE REVIEW

**Review by asdotdev — COMMENTED** [review]
This PR has 0 files changed and isn't resolving the linked issue.

If willing to resolve the issue then convert it to a draft till the issue resolved and if PR is created by mistake then close it.

**Comment by Asifdecoder** [comment]
There is a linting error and I runned the project on gitpod it succesfully solves the stated problem but can anyone suggest how to solve this error CI - Node.js / Lint (20.x) (pull_request), I'm currently learning so wanted some help.

**Comment by amitabh-sahu** [comment]
Try running the “lint” and “format” scripts from the package file to check what causing the error and fix it.

**Comment by Asifdecoder** [comment]
> Try running the “lint” and “format” scripts from the package file to check what causing the error and fix it.

Thanks for the suggestion worked on them and now test have passed.

**Review by naomi-lgbt — APPROVED** [review]

**Review by ahmaxed — APPROVED** [review]

**Pull request merged**
