### PR TITLE
Added or in between greater than and less than equal to

### LINKED ISSUE #6380: Change "Greater Than Equal To" to "Greater Than or Equal To"
I hope this isn't too nit picky, but the [Comparison with the Greater Than Equal To Operator](http://www.freecodecamp.com/challenges/comparison-with-the-greater-than-equal-to-operator) and [Comparison with the Less Than Equal To Operator](http://www.freecodecamp.com/challenges/comparison-with-the-less-than-equal-to-operator) challenges should change their text from 

> "____ than equal to"

 to

> "____ that **or** equal to"

where "___" is "greater" or "less."

The [Comparison with the Less Than Equal To Operator](http://www.freecodecamp.com/challenges/comparison-with-the-less-than-equal-to-operator) challenge already uses this expression in the editor but not in the description itself.

image

Also, the [MDN JavaScript reference page](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Operators/Comparison_Operators) adds the "or" to describe these symbols.

### PR DESCRIPTION
**Pull request by tahmidulkarim**
Added or in between greater than equal to and less than equal to .

closes #6380

### CODE REVIEW

**Comment by erictleung** [comment]
Please add something along the lines of `Closes #6380` in your commit message to close the issue with your pull request. Here are some [other keywords to use](https://help.github.com/articles/closing-issues-via-commit-messages/). For some [more help on contributing](https://github.com/FreeCodeCamp/FreeCodeCamp/blob/staging/CONTRIBUTING.md#common-steps).

**Comment by tahmid-ul** [comment]
Is it ok now @erictleung

**Comment by erictleung** [comment]
@tahmid-ul looks almost good to me. This is the only part that is kind of bothering me:

image

I think it has to do with your commit message when you made the commit locally on your computer but I'm not sure how to fix it or if it is an issue. Maybe @SaintPeter will know.

**Comment by SaintPeter** [comment]
I think you can fix the commit message by doing a `git commit --amend` on that branch and editing the commit message.  Generally speaking the commit messages should be descriptive of the change that is being made.  I'll fix it when I merge this, but it would be better if it were correct initially.

**Comment by SaintPeter** [comment]
:+1: 

Way to go @tahmid-ul on your first FCC PR!

**Comment by tahmid-ul** [comment]
thanks @SaintPeter

**Pull request merged**
