### PR TITLE
Added challenge for Attribute Selector

### PR DESCRIPTION
**Pull request by adrianwithah**
#### Pre-Submission Checklist

- [X] Your pull request targets the `staging` branch of freeCodeCamp.
- [X] Branch starts with either `fix/`, `feature/`, or `translate/` (e.g. `fix/signin-issue`)
- [X] You have only one commit (if not, [squash](http://forum.freecodecamp.com/t/how-to-squash-multiple-commits-into-one-with-git/13231) them into one commit).
- [X] All new and existing tests pass the command `npm test`. Use `git commit --amend` to amend any fixes.

#### Type of Change

- [X] Small bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds new functionality)
- [ ] Breaking change (fix or feature that would change existing functionality)
- [ ] Add new translation (feature adding new translations)

#### Checklist:

- [X] Tested changes locally.
- [ ] Closes currently open issue (replace XXXX with an issue no): Closes #XXXX

#### Description

Introduced the attribute selector challenge as part of the curriculum teaching about pseudo classes/elements and selectors. Deals with issue #13594 . 

@Ethan-Arrowood Hi ethan, could you help to review the challenge? 😄 I plan to add in the solutions after finalising the content of all the challenges, so as to reduce the portions i have to change if there are any amendments, hope that's fine with you.

### CODE REVIEW

**Comment by QuincyLarson** [comment]
@Ethan-Arrowood @HKuz would either of you be interested in reviewing this challenge?

**Comment by Ethan-Arrowood** [comment]
@QuincyLarson I'll add it to my todo list

**Comment by Ethan-Arrowood** [comment]
Okay I copied your code into my own branch and ran through the challenge. Explanation sounds good to me. I'd recommend filling out the solution though so the challenge is included in `npm test`.  Another note is I know these challenges tend to build on each other, so would it be useful to keep the `[type='radio'] { }` selector on the remaining Cat Photo App challenges so the user can get familiar seeing it over and over again.
Great work none the less!

**Comment by raisedadead** [comment]
@Ethan-Arrowood you would need to pull down the pull request and then run this locally.

Two ways to do this (well there are others, these are just the way I do it):
**1. If you are not reviewing pull request regularly:**
```
git checkout -b hay-dee-fix/include-selectors-challenge staging
git pull https://github.com/hay-dee/freeCodeCamp.git fix/include-selectors-challenge
node seed
gulp
```

**2. If you intend to this more often (recommended)**
- Install [git-extras](https://github.com/tj/git-extras/blob/master/Installation.md) (one time only installation)
- Follow these:
```
git checkout staging
git pr https://github.com/freeCodeCamp/freeCodeCamp/pull/13996
node seed
gulp
```
- Clean up is done by:
```
git checkout staging
git pr clean
```

**Comment by hay-dee** [comment]
@Ethan-Arrowood Apologies for the delay! Was busy during the weekdays. I was not planning to carry the changes over to the subsequent CatPhotoApp challenges and hence did not focus on the aesthetics of my changes. As you can see, the end result is not that aesthetically pleasing 😅 .

I found a more better method, which is to move the challenge right after the [Use Clockwise Notation to Specify the Margin of an Element](http://beta.freecodecamp.com/en/challenges/basic-css/use-clockwise-notation-to-specify-the-margin-of-an-element). I will then utilise margin properties to space out the checkboxes. Will that be fine with you?

**Comment by hay-dee** [comment]
@Ethan-Arrowood Should I proceed with the changes stated? 😄

**Comment by Ethan-Arrowood** [comment]
Your changes sound good to me. I can't merge your commit but you should go alert some of the mods on Gitter and have them do it for you. Good work!

**Comment by hay-dee** [comment]
I have re-positioned and reworked the attribute selectors challenge.
cc/ @freeCodeCamp/moderators

**Review by raisedadead — APPROVED** [review]
LGTM

**Comment by raisedadead** [comment]
@hay-dee the only thing I can see as a problem being the use of word `checkboxes` vs `checkbox` in the type.

I believe the tests and instructions areas should explicitly mention something like `[type='checkbox']` because we might get a lot of support issues with newcomers trying to use 'checkboxes' in the selector as in `[type='checkboxes']` and fail the tests.

Else this is ready for a merge. 

If you agree, either update this PR or feel free to make a new one after we merge this, I'll let you decide how you would want that.

And thanks again for creating this challenge, good work!

**Comment by hay-dee** [comment]
@raisedadead I could change the example given in the description to a <code>[type="checkbox"]</code> selector, instead of the <code>[type="radio"]</code> selector. Will update the PR soon.

**Comment by raisedadead** [comment]
@hay-dee  I'll go ahead and merge this so that it does not go stale. Please open a fresh PR when you are ready.

Thanks once again!

**Pull request merged**
