### PR TITLE
Fixed flyer dismiss issue on firefox

### LINKED ISSUE #9480: Flyer returns after being dismissed in FireFox
#### Issue Description

1. open up FreeCodeCamp.com in firefox, sign in, and make sure you have at least 5 brownie points.
2. you should see the "flyer" at the top of the page with a promotional message like "check out our forum"
3. dismiss it
4. refresh the page. It comes back.

This is a problem with our use of local storage.

### PR DESCRIPTION
**Pull request by kirushna-kumar**
#### Pre-Submission Checklist

- [x] Your pull request targets the `staging` branch of FreeCodeCamp.
- [x] Branch starts with either `fix/`, `feature/`, or `translate/` (e.g. `fix/signin-issue`)
- [x] You have only one commit (if not, [squash](https://github.com/FreeCodeCamp/FreeCodeCamp/wiki/Git-Squash) them into one commit).
- [x] All new and existing tests pass the command `npm run test-challenges`. Use `git commit --amend` to amend any fixes.
#### Type of Change

- [x] Small bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds new functionality)
- [ ] Breaking change (fix or feature that would change existing functionality)
- [ ] Add new translation (feature adding new translations)
#### Checklist:

- [x] Tested changes locally.
- [x] Closes currently open issue (replace XXXX with an issue no): Closes #9480 
#### Description

Minor change in jade template, moved id from span to close button so that click event gets triggered alongside data-dismiss in firefox.

### CODE REVIEW

**Comment by flipsyde606** [comment]
@atjonathan, is this on hold?

**Comment by atjonathan** [comment]
@flipsyde606, I couldn't successfully `QA` your code, due to not being able to get the flash messages at all. This could be an issue with my local setup or your code. @FreeCodeCamp/issue-moderators could someone else pull this down? Sorry about the wait.

**Comment by flipsyde606** [comment]
@atjonathan, you would probably need to populate flyer collection in mongo (check API explorer for schema). Database seed script doesn't create this one. Also you need atleast 5 user points.

**Comment by QuincyLarson** [comment]
@flipsyde606 awesome work! I verified it works in both Chrome and Firefox now.

**Pull request merged**
