### PR TITLE
Do not auto toggle to Question view when video ends

### LINKED ISSUE #8583: Video Challenges - immediately goes to questions
#### Challenge Name

Video Challenges

#### Issue Description

They now record completion, however, I liked it better when I chose when I wanted to go to the questions.  Now it automatically brings up the questions when the video finishes.  That means I can't read over the notes below the video after the video.  I have to read and understand them before I watch the video or have to exit out and start the challenge again.  I liked the old way better.

### PR DESCRIPTION
**Pull request by bugron**
#### Pre-Submission Checklist

- [x] Your pull request targets the `staging` branch of FreeCodeCamp.
- [x] Branch starts with either `fix/`, `feature/`, or `translate/` (e.g. `fix/signin-issue`)
- [x] You have only one commit (if not, [squash](https://github.com/FreeCodeCamp/FreeCodeCamp/wiki/git-rebase#squashing-multiple-commits-into-one) them into one commit).
- [x] All new and existing tests pass the command `npm run test-challenges`. Use `git commit --amend` to amend any fixes.
#### Type of Change

- [x] Small bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds new functionality)
- [ ] Breaking change (fix or feature that would change existing functionality)
- [ ] Add new translation (feature adding new translations)
#### Checklist:

- [x] Tested changes locally.
- [x] Closes currently open issue (replace XXXX with an issue no): Closes #8583

I don't like this feature either. It's very surprising that view is being toggled immediately after video ends. And there is no a UI way to go back to read the transcript. The only way is refreshing the page.

### CODE REVIEW

**Comment by bugron** [comment]
Another thing I want to propose is to move `Take me to the Questions` button up like this:
untitled
In this way there is no need to scroll all the way down to click that button.
/cc @QuincyLarson @hallaathrad

**Comment by atjonathan** [comment]
@bugron Add some padding top and bottom, and maybe give the button a smaller width?

**Comment by bugron** [comment]
@atjonathan sure, that will be done in a separate PR, this was just a thought.

**Comment by ltegman** [comment]
👍

**Pull request merged**
