### PR TITLE
Remove unused authentication methods

### PR DESCRIPTION
**Pull request by erictleung**
#### Pre-Submission Checklist

- [x] Your pull request targets the `staging` branch of FreeCodeCamp.
- [x] Branch starts with either `fix/`, `feature/`, or `translate/` (e.g. `fix/signin-issue`)
- [x] You have only one commit (if not, [squash](https://github.com/FreeCodeCamp/FreeCodeCamp/wiki/git-rebase#squashing-multiple-commits-into-one) them into one commit).
- [x] All new and existing tests pass the command `npm run test-challenges`. Use `git commit --amend` to amend any fixes.
#### Type of Change

- [x] Small bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds new functionality)
- [ ] Breaking change (fix or feature that would change existing functionality)
- [ ] Add new translation (feature adding new translations)
#### Checklist:

- [x] Tested changes locally.
- [ ] Closes currently open issue (replace XXXX with an issue no): Closes #XXXX
#### Description

Remove unused authentication methods. Let me know if there are any other places I missed.

### CODE REVIEW

**Comment by atjonathan** [comment]
### **LGTM :+1:**

**Comment by erictleung** [comment]
@BerkeleyTrue do you know if the mention of Mandrill [here](https://github.com/FreeCodeCamp/FreeCodeCamp/blob/87ef97f59e2a2f4dc425982f76f14a57d0900bcf/pm2Start.js) will be affected with this PR?

**Comment by BerkeleyTrue** [comment]
@erictleung That part of the script isn't used anymore. Do you mind removing the email stuff there as well?

**Comment by erictleung** [comment]
@BerkeleyTrue let me know if I got too delete happy on that file or not.

**Comment by ramir141974** [comment]
Hello s

**Comment by ramir141974** [comment]
Hello sir can you explain to me if the question is from me?thank you and have a nice day and night.

**Comment by Bouncey** [comment]
@BerkeleyTrue Are we OK to merge this PR?

**Comment by BerkeleyTrue** [comment]
LGTM

**Comment by Bouncey** [comment]
Thanks for contributing :tada:

**Pull request merged**
