### PR TITLE
fix(seed): Make algorithm projects appear after intermediate algorithms

### LINKED ISSUE #16654: Algorithm challenges are in wrong sequence
Intermediate algorithms should come before the algorithm projects. I'll fix this real quick.

applied_visual_design__introduction_to_the_applied_visual_design_challenges___freecodecamp

### PR DESCRIPTION
**Pull request by QuincyLarson**
Closes #16654

### CODE REVIEW

**Comment by Bouncey** [comment]
`Basic Data Structures` and `Debugging` both have an order of `4` and they are rendered differently on my machine compared to your screenshot  in the original issue.

It would require a bump in order for all blocks from 5 upwards.

**Review by Bouncey — DISMISSED** [review]
`Basic Data Structures` and `Debugging` both have an order of `4` and they are rendered differently on my machine compared to your screenshot  in the original issue.

It would require a bump in order for all blocks from 5 upwards.

**Comment by QuincyLarson** [comment]
@Bouncey Nice catch! OK - I've updated the order values for all those seed files and verified that everything looks correct on the map.

**Review by Bouncey — APPROVED** [review]

**Comment by Bouncey** [comment]
## LGTM

**Pull request merged**
