### PR TITLE
fix: correct function call in test description

### PR DESCRIPTION
**Pull request by gikf**
* Corrects last test description to use right argument in function.
* Adds expected return value to the same description.

Checklist:

- [x] I have read [freeCodeCamp's contribution guidelines](https://contribute.freecodecamp.org).
- [x] My pull request has a descriptive title (not a vague title like `Update index.md`)
- [x] My pull request targets the `main` branch of freeCodeCamp.
- [x] All the files I changed are in the same world language, for example: only English changes, or only Chinese changes, etc.

### CODE REVIEW

**Comment by RandellDawson** [comment]
@gikf Is this related to an outstanding GitHub issue?  If it is, can you add `Closes #issue-number-goes-here` to the body of this PR?  Thanks.

**Comment by gikf** [comment]
@RandellDawson As far as I'm aware there's no such issue. I haven't created one either, as changes here are rather straightforward and they didn't seem to be significant enough or needing to have more investigation, to warrant one. If my assessment wasn't correct here I'll be happy to create the issue.

**Comment by RandellDawson** [comment]
@gikf You are fine.  I was just making sure in case there was one that was not linked here.

**Comment by gikf** [comment]
I kind of even on purpose removed the `Closes (...)` line from the template to not make it seem that filling it might have been overlooked. :slightly_smiling_face:

**Review by raisedadead — APPROVED** [review]

**Pull request merged**
