### PR TITLE
test: enable tests for steps

### PR DESCRIPTION
**Pull request by ojeytonwilliams**
https://github.com/freeCodeCamp/freeCodeCamp/pull/43971 had got a bit stale. This just contains the test code changes, we'll still need the curriculum updates.

### CODE REVIEW

**Comment by ojeytonwilliams** [comment]
This needs some of the changes in https://github.com/freeCodeCamp/freeCodeCamp/pull/44539 as well as the curriculum changes in https://github.com/freeCodeCamp/freeCodeCamp/pull/43971

**Comment by moT01** [comment]
So does this need some more things added (other than what's needed to make the tests pass) from those other PR's, or do we just need to get those in first?

**Comment by ojeytonwilliams** [comment]
@moT01 there are some fixes to the curriculum tests in https://github.com/freeCodeCamp/freeCodeCamp/pull/44539 and the steps themselves should pass.

If we merge the others first, I can rebase this and see if it uncovers any more problems.

**Review by ShaunSHamilton — APPROVED** [review]

**Comment by ojeytonwilliams** [comment]
> fix: idIndex is index of id not id

Yes. Yes, it is. 🤦‍♂️

**Review by naomi-lgbt — APPROVED** [review]
HERE WE GO!!!!!

**Pull request merged**
