### PR TITLE
fix(a11y): completed-step focus accessibility

### LINKED ISSUE #50023: Accessibility issue with keyboard focus indicator on steps grid
### Describe the Issue

Since we recently added a global focus outline color, the keyboard focus state on the New RWD steps grid now does not have a large enough color contrast to be accessible when focused on a completed step. This is an issue in both light and dark mode. In the following images, assume step 3 is completed.

fcc-steps1

Neither the blue outline or the light gray background has enough contrast with the original lighter blue background they are replacing to be accessible under WCAG.

fcc-steps1-dark

Again, neither the blue outline or the dark background has enough contrast with the original dark blue background they are replacing to meet WCAG contrast requirements.

I didn't want to make a unilateral decision on how to fix this, so here are a few options to consider:

1. Move the outline so it is just outside of the step square:

fcc-step2

This is accessible because the blue outline now has enough contrast with the white background it is replacing and as an added bonus, the focus ring makes the square appear bigger. Technically, we do not need to have that thin strip of white space between the square and the outline. The outline could be right up against the edge of the square. I like the white space because I think it makes the outline stand out a little more and makes the square look even bigger. This technique will also work in dark mode for the same reasons.

fcc-step2-dark

2. Change the color of the focus outline so it has more contrast. Perhaps the same color as the text?

fcc-steps3

fcc-steps3-dark

3. I'm not that creative, so please feel free to suggest something else if.

Also, while we are fixing this, I would recommend we increase the font weight from `700` to `900` and the font size from `1.3rem` to `1.5rem` on the completed steps to make the difference in those numbers stand out a little more since we can't rely on the background color for the completed steps to convey their state since they don't have enough color contrast with the background.

### Affected Page

Any steps page

### Steps to Reproduce

N/A

### Expected behavior

Completed steps should have a keyboard focus indicator that meets WCAG standards.

### Screenshots

_No response_

### System

N/A

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by harmeet01singh**
Changed completed-step outline color to secondary color on focus

Checklist:

- [x] I have read and followed the [contribution guidelines](https://contribute.freecodecamp.org).
- [x] I have read and followed the [how to open a pull request guide](https://contribute.freecodecamp.org/#/how-to-open-a-pull-request).
- [x] My pull request targets the `main` branch of freeCodeCamp.
- [x] I have tested these changes either locally on my machine, or GitPod.

Closes #50023

### CODE REVIEW

**Comment by bbsmooth** [comment]
The focus outline looks good in both light/dark mode.

From the issue: 

> Also, while we are fixing this, I would recommend we increase the font weight from 700 to 900 and the font size from 1.3rem to 1.5rem on the completed steps to make the difference in those numbers stand out a little more since we can't rely on the background color for the completed steps to convey their state since they don't have enough color contrast with the background.

Any objection to doing this? I feel like the current difference in the display of the completed step numbers is barely enough to be detectable and thus we are just barely fulfilling the requirement for [WCAG 1.4.1](https://www.w3.org/WAI/WCAG21/Understanding/use-of-color.html).

**Comment by harmeetsingh01** [comment]
Had some doubts in that, you only want this behaviour to occur when the elements are keyboard focused only or on mouse hover as well. I think it makes sense to do it for both.

**Comment by cw-harmeetsingh** [comment]
Hi @bbsmooth , any update on this? Are we taking the font size changes on as other features. Also, can you help me in understanding what changing of the title means?

**Comment by harmeetsingh01** [comment]
Hi @bbsmooth , any update on this? Are we taking the font size changes on as other features. Also, can you help me in understanding what changing of the title means?

**Review by AliMora83 — COMMENTED** [review]
Very good 🥳

**Comment by Sboonny** [comment]
@harmeetsingh01, adding hover is outside the scope of the issue and what Bruce worried about.

We can discuss it after the original issue is closed, because we can improve the design as well if needed.

**Comment by harmeetsingh01** [comment]
Understood @Sboonny , will add the discussed font changes on focus for now.

**Comment by bbsmooth** [comment]
@harmeetsingh01 Sorry, I've been gone for the past couple of weeks and forgot to get back to you on the font size and weight. It's not my decision, but it sounds like @Sboonny is OK with increasing both to my suggestions for completed steps.

Please note, this has nothing to do with either focus or hover. The font changes should be present at all times for the completed step. Right now the font size on a completed step is `1.3rem` and the `font-weight` is `700`. But that change is hardly noticeable. So I am suggesting we up it to `1.5rem` and `900` to make it stand out more.

**Comment by harmeetsingh01** [comment]
Oh, Thanks for clearing it up, I was a bit confused and thought we want the increase in font size on focus or hover. Understood, will push the necessary change. Apologise for the misunderstanding.

**Review by bbsmooth — APPROVED** [review]
LGTM

**Review by Sboonny — APPROVED** [review]
#### :sparkles: :tada: **AWESOME!** :tada: :sparkles:

 Hi @harmeetsingh01, thanks for this pull request and for contributing to the code-base for the first time. We are looking forward to more contributions from you in the future.

 Cheers & happy contributing!

**Comment by harmeetsingh01** [comment]
Thanks to you @Sboonny and @bbsmooth as well for helping me. Looking forward to more such collaborations in the future.

**Pull request merged**
