### PR TITLE
Points to working example to use Twitch JSONP API

### PR DESCRIPTION
**Pull request by vtamara**

### CODE REVIEW

**Comment by awesomeaniruddh** [comment]
Thanks for the PR @vtamara.

Can you please rebase the two commits? Instructions on that here: https://github.com/FreeCodeCamp/FreeCodeCamp/wiki/git-rebase

**Comment by vtamara** [comment]
Rebased

**Comment by bugron** [comment]
@vtamara, please, `squash` commits into one `Points to working example of using Twitch JSONP` commit.

**Comment by vtamara** [comment]
squashed

**Comment by awesomeaniruddh** [comment]
Merged, thanks for the PR!

**Pull request merged**
