### PR TITLE
fix: Changed the description for finders keepers

### PR DESCRIPTION
**Pull request by Ghahjih**
Checklist:

- [x] I have read [freeCodeCamp's contribution guidelines](https://contribute.freecodecamp.org).
- [x] My pull request has a descriptive title (not a vague title like `Update index.md`)
- [x] My pull request targets the `master` branch of freeCodeCamp.
- [x] All the files I changed are in the same world language, for example: only English changes, or only Chinese changes, etc.

Closes #XXXXX

### CODE REVIEW

**Comment by Ghahjih** [comment]
first commit on the project

**Comment by raisedadead** [comment]
@Sky020 I do not see a merge conflict, did you happen to add this acidentally or did you mean that this is conflicting with the other duplicate PR.

**Comment by Sky020** [comment]
@raisedadead , Sorry about that. I intentionally added it, but realise now it should have been the _duplicate_ label.

**Comment by moT01** [comment]
Closing in favor of the other PR which makes the changes suggested in the issue. This one does not. Thanks, and happy coding @Ghahjih 🎉

**Pull request closed without merging**
