### PR TITLE
solution to issue #1173

### PR DESCRIPTION
**Pull request by benmcmahon100**
this solution may also be needed for some of the other css-based challenges

### CODE REVIEW

**Comment by LumenTeun** [comment]
Looks good, but you should probably replace the non-strict comparison `==` with the scrict one `===`. I'm not sure it would make any difference here, but it's preferred.

**Comment by benmcmahon100** [comment]
Just added that extra = like you were saying its doesn't really achieve much other then consistency but I'm all for consistency!

**Comment by LumenTeun** [comment]
Nice :) You might also want to [rebase](https://github.com/edx/edx-platform/wiki/How-to-Rebase-a-Pull-Request) your commits into one since the second is such a minor change. I don't think you have to, but it's a good skill to have and the history will look cleaner.

**Comment by QuincyLarson** [comment]
Wow, I didn't realize you could do this with Chai.js. Great work, @benmcmahon100. @LumenTeun is right, you can rebase these. That said, I'm not doing this yet myself, so I will go ahead and accept this PR as is.

**Pull request merged**
