### PR TITLE
Update basic-javascript.json

### PR DESCRIPTION
**Pull request by MurrayBakerWebDeveloper**
Added solution to Basic Javascript: Comment out your HTML

### CODE REVIEW

**Comment by ltegman** [comment]
You have merge conflicts and your json is invalid. Please [rebase](https://github.com/FreeCodeCamp/FreeCodeCamp/wiki/git-rebase#preventing-merge-conflicts) your local branch and fix the JSON problems and then force push your branch.

**Comment by nuku89** [comment]
I was able to rebase, can i try another pr? force pushing wasn’t working

**Comment by ltegman** [comment]
Up to you, but `git push -f` should definitely work and update this PR with the changes.

**Comment by bugron** [comment]
Closing this PR. This is the first PR which I wanted to label as `bike shedding`. @nuku89 if you're going to create a new PR, note, that currently our test suites support only one solution and `solutions` is an array of strings. Thanks for your contribution, though.

**Comment by nuku89** [comment]
Thank you allowing me to give it my best shot. I’m working on setting up COM1000, I heard it is the best tool for making contributions. I hadn’t heard of it until a couple of days ago. I wish it was advertised right by the link to the waffle board.

**Pull request closed without merging**
