### PR TITLE
Updated wording in Spanish translation

### PR DESCRIPTION
**Pull request by DavSanchez**
Hello! I'm updating some wording and orthography on the Spanish documentation.

Source: native speaker!

- [x] I have read [freeCodeCamp's contribution guidelines](https://github.com/freeCodeCamp/freeCodeCamp/blob/master/CONTRIBUTING.md).
- [x] My pull request has a descriptive title (not a vague title like `Update index.md`)
- [x] My pull request targets the `master` branch of freeCodeCamp.
- [x] None of my changes are plagiarized from another source without proper attribution.
- [x] All the files I changed are in the same world language (for example: only English changes, or only Chinese changes, etc.)
- [x] My changes do not use shortened URLs or affiliate links.

### CODE REVIEW

**Comment by RandellDawson** [comment]
@DavSanchez Thank you for  creating this PR.  However, since it was created, the underlying document has changed.  Can you please review and resolve the current merge conflicts?  It could be the changes to the underlying document are so significant that your changes are no longer relevant.  If the latter is the case, it might be easier to just close this PR and create a new PR with any changes you still feel are important to make.

If you need any assistance or have questions about resolving the merge conflicts, please reply back or contact someone in the [Contributors Room on Gitter](https://gitter.im/FreeCodeCamp/Contributors).

Thank you

**Comment by DavSanchez** [comment]
Alright! I'll have a look on this and get back here with an update

**Comment by DavSanchez** [comment]
Hi! I have fixed the merge conflicts and squashed my last 3 commits, onto the updated document. Please let me know if anything else is needed on my part!

**Comment by RandellDawson** [comment]
You should only have one file `docs/i18n-languages/spanish/CONTRIBUTING.md` on this PR.  You have changes for 3 other files on this PR which need to be removed.

Thank you.

**Comment by DavSanchez** [comment]
Ah, my bad! I think I got one additional commit in my previous rebase by accident... It is corrected now.

**Review by Narshe1412 — APPROVED** [review]

**Review by raisedadead — APPROVED** [review]
Approved on behalf of dev team. Mods please merge if change is OK.

**Comment by RandellDawson** [comment]
@DavSanchez The current [English version of CONTRIBUTING.md](https://github.com/freeCodeCamp/freeCodeCamp/blob/master/CONTRIBUTING.md) looks like the folloiwng:
```
1. [Contribute to this open-source codebase](#contribute-to-this-open-source-codebase). Help us edit coding challenges, or fix bugs on the learning platform.

2. Help campers on our [public forum](https://www.freecodecamp.org/forum/). [Answer their coding questions](https://www.freecodecamp.org/forum/?max_posts=1) or [give them feedback on their coding projects](https://www.freecodecamp.org/forum/c/project-feedback?max_posts=1).
```
It seems the translated version is out of sync with the English version (which is what I alluded to above).  Can you please re-translate these two bullets and also confirm the rest of this document is in sync with the English version.

Thank you.

**Comment by DavSanchez** [comment]
Sorry @RandellDawson I initially thought you were talking about just the Spanish document and not the English one. I have already begun a translation review to get everything faithful to the original, I'll let you know when it's finished (and squashed into just one commit if required)!

**Comment by DavSanchez** [comment]
Hi! I have now reviewed the Spanish file to make it more faithful to the English original. Feel free to check it out!

**Comment by RandellDawson** [comment]
@DavSanchez Can you fix the merge conflict so we can make a final review?

Thanks

**Comment by DavSanchez** [comment]
Sorry for the late response, it should be resolved now.

**Pull request merged**
