### PR TITLE
fix(curriculum): update tests for HTML formatting

### LINKED ISSUE #52811: RPG step 6 spaces - HTML formatting issue
### Describe the Issue

Prettier formatted HTML will fail the "Health" text test. If you add text to the nested span you can see the spacing is correct.

```
<div id="monsterStats">
  <span class="stat">
    Monster Name: 
    <strong>
      <span></span>
    </strong>
  </span>
  <span class="stat">
    Health: 
    <strong>
      <span></span>
    </strong>
  </span>
</div>
```

The test is also relying on `textContent` for the space which won't allow for proper formatting.

I'm not sure what the best option is here but having the camper add placeholders would allow us to test for the space more easily.

```
<div id="monsterStats">
  <span class="stat">
    Monster Name: 
    <strong>
      <span>Slime</span>
    </strong>
  </span>
  <span class="stat">
    Health: 
    <strong>
      <span>10</span>
    </strong>
  </span>
</div>
```

```
const spans = document.querySelectorAll(`#monsterStats > span`);
spans[0].innerText.includes('Monster Name: Slime')
spans[1].innerText.includes('Health: 10')
```

Tests: https://github.com/freeCodeCamp/freeCodeCamp/tree/main/curriculum/challenges/english/15-javascript-algorithms-and-data-structures-22/learn-basic-javascript-by-building-a-role-playing-game/62a23d1c5f1c93161f3582ae.md

### Affected Page

https://www.freecodecamp.org/learn/javascript-algorithms-and-data-structures-v8/learn-basic-javascript-by-building-a-role-playing-game/step-6

### Your code

```



```

### Expected behavior

Proper formatted HTML should not fail the test.

### Screenshots

_No response_

### System

- Device: [e.g. iPhone 6, Laptop]
- OS: [e.g. iOS 14, Windows 10, Ubuntu 20.04]
- Browser: [e.g. Chrome, Safari]
- Version: [e.g. 22]

### Additional context

Forum: https://forum.freecodecamp.org/t/learn-basic-javascript-by-building-a-role-playing-game-step-6/659144

I know they also added an extra space but the issue remains the same.

### PR DESCRIPTION
**Pull request by edwinhung**
Checklist:

- [x] I have read and followed the [contribution guidelines](https://contribute.freecodecamp.org).
- [x] I have read and followed the [how to open a pull request guide](https://contribute.freecodecamp.org/#/how-to-open-a-pull-request).
- [x] My pull request targets the `main` branch of freeCodeCamp.
- [x] I have tested these changes either locally on my machine, or GitPod.

Closes #52811

I made changes to tests so that a prettier HTML formatting would also pass tests, though a few issues may need to be addressed. 1. Additional whitespaces after `Heath: ` in code editor would also pass the test. 
2. The test for `Health: ` is exactly the same as the very last test (Your strong and span elements should come after the text.).

### CODE REVIEW

**Comment by lasjorg** [comment]
As long as it checks for at least one space and properly formatted HTML passes the tests I'm good with it. I don't think checking for an exact amount of spaces is important. Besides, the code will be replaced by the seed code in the next step anyway.

However, we may have to move the tests that check for the elements to before the tests that check the text to avoid any confusing hints. If they are missing the strong element they should get the proper hint message.

**Comment by edwinhung** [comment]
Thanks, I agree with you that we need to check for elements first to avoid confusing hint. I moved the test for `Health: ` below the tests for elements.

**Comment by lasjorg** [comment]
I just noticed that when writing this one step at a time and not having written the text in the second span element yet, the text test for the first span element will fail. It is because `innerText` will not have a space in it without any text in the second span element.

This code:
```
<div id="monsterStats">
    <span class="stat">Monster Name: <strong><span></span></strong></span>
    <span class="stat"></span>
</div>
```

Fails with this message:

> Your first span element should have the text Monster Name: . Make sure the spacing is correct.

Which is a little confusing.

```
document.querySelectorAll('#monsterStats > span')[0].innerText
// 'Monster Name:'
```

Compared to:

```
<div id="monsterStats">
    <span class="stat">Monster Name: <strong><span></span></strong></span>
    <span class="stat">test</span>
</div>
```
```
document.querySelectorAll('#monsterStats > span')[0].innerText
'Monster Name: '
```

**Comment by edwinhung** [comment]
I didn't notice that part, thanks.
I changed the regex of tests for text so they check only for text. Then, the tests checking for order would work properly.
For example, the following would fails with the hint 
> Your strong and span elements should come after the text.
`<span class="stat"><strong><span></span></strong>Monster Name: </span>`

**Comment by edwinhung** [comment]
I noticed this markdown file was changed by a different PR for adding element ids. I tried pull rebase on my machine, and there's no conflict. Should I push again to repo?

**Comment by lasjorg** [comment]
You can do a rebase and push but it shouldn't be needed. The final merge should not have any conflicts as long as we are not touching the same parts of the file.

**Review by lasjorg — APPROVED** [review]
I think this looks good.

I didn't see anything else that tripped me up when completing this going step by step following the hints.

And it now passes using the formatted HTML from the issue as well.

**Review by Sembauke — APPROVED** [review]

**Pull request merged**
