### PR TITLE
refactor: use fastify/rate-limit, drop express

### PR DESCRIPTION
**Pull request by ojeytonwilliams**
Checklist:

- [x] I have read and followed the [contribution guidelines](https://contribute.freecodecamp.org).
- [x] I have read and followed the [how to open a pull request guide](https://contribute.freecodecamp.org/how-to-open-a-pull-request/).
- [x] My pull request targets the `main` branch of freeCodeCamp.
- [x] I have tested these changes either locally on my machine, or GitPod.

I was looking into migrating Fastify to V5 and noticed we're still using an express plugin. This removes express entirely.

It did mean I had to "patch" the rate limit store, since their `incr` signatures were different, so there's more code than I'd like. However, when we use redis (see: https://github.com/freeCodeCamp/freeCodeCamp/issues/50631) all the custom code can be dropped, since fastify/rate-limit supports redis out of the box.

### CODE REVIEW

**Review by naomi-lgbt — APPROVED** [review]
Bye ~~Felicia~~ Express!

**Review by ShaunSHamilton — APPROVED** [review]
Works.

---

For discussion: Are we purposefully prioritising `redirectToLearnIfSignedIn` over the rate limit?

For testing, I had to disable that redirect to ever hit the rate limit.

**Comment by ojeytonwilliams** [comment]
> For discussion: Are we purposefully prioritising redirectToLearnIfSignedIn over the rate limit?

Yep! The idea is to provide an extra layer of protection to the mobile-login endpoint. If, for whatever reason, it's possible to spam this endpoint to get logged in, this mitigates that. However, if they're already signed in, that's irrelevant (nothing changes about their login status). They should just be redirected.

**Review by ghost — COMMENTED** [review]
TZAHAL 126477

**Pull request merged**
