### PR TITLE
Fix formatting, tests for new HTML and CSS challenges

### LINKED ISSUE #12646: [beta] Section order - Should Basic HTML come before Basic CSS?
#### Challenge Name

N/A - this can be seen [in the map](https://beta.freecodecamp.com/en/map)

#### Issue Description

Right now, Basic CSS is the first section of the curriculum. I think Basic HTML should be first instead. The first HTML challenge even states "Welcome to Free Code Camp's first coding challenge".

#### Screenshot

challenge-order

### LINKED ISSUE #12653: QA issues for new challenges in HTML and CSS sections
#### Challenge Name

There are general formatting issues (lack of `code` tags, tag name angle brackets need escape characters, Instructions need `h4` tags, etc.) for all the following challenges. Some also have issues with their tests, as noted.

New challenges in Basic HTML and HTML5 section:
- [ ] Say Hello to HTML elements
  need to update the copy per [this comment](https://github.com/FreeCodeCamp/CurriculumExpansion/issues/74#issuecomment-254080698)
- [ ] Introduction to HTML5 Elements
  3rd assert test doesn't work (need to escape the closing main tag forward slash in the regex)
- [ ] Link to Internal Sections of a Page with Anchor Elements
  The  `a` referenced in the instructions is missing in the seed code
- [ ] Declare the Doctype of an HTML Document
  first two tests displaying oddly and third test not working (on both Firefox and Chrome)
- [ ] Define the Head and Body of an HTML Document
  5th test not working (on both Firefox and Chrome)

New challenge in Basic CSS section:
- [ ] Understand Absolute versus Relative Units

#### Issue Description

The challenge text and tests need some clean up to look right and work properly.

#### Browser Information

* Browser Name, Version: Firefox 50.1.0 and Chrome 55.0.2883.95 (64-bit)
* Operating System: Mac OS X El Capitan
* Mobile, Desktop, or Tablet: Desktop

### PR DESCRIPTION
**Pull request by HKuz**
#### Pre-Submission Checklist

- [x] Your pull request targets the `staging` branch of freeCodeCamp.
- [x] Branch starts with either `fix/`, `feature/`, or `translate/` (e.g. `fix/signin-issue`)
- [x] You have only one commit (if not, [squash](http://forum.freecodecamp.com/t/how-to-squash-multiple-commits-into-one-with-git/13231) them into one commit).
- [x] All new and existing tests pass the command `npm test`. Use `git commit --amend` to amend any fixes.

#### Type of Change

- [x] Small bug fix (non-breaking change which fixes an issue)

#### Checklist:

- [x] Tested changes locally.
- [x] Closes currently open issues (replace XXXX with an issue no): Closes #12646 and Closes #12653 

#### Description

Formatting changes: adds `code` tags, fixes multi-line code examples, and swaps the angle brackets in examples for escape characters
Tests: fixes a few challenge tests that had regex errors or weren't running as expected. They all work locally now
Section ordering: fixes `order` field in `.json` files so Basic HTML and HTML5 comes first, then Basic CSS, then Applied Visual Design. The CSS section was appearing first before.

### CODE REVIEW

**Comment by raisedadead** [comment]
LGTM, and this does not relate to your challenge, but your you mind removing this line:
https://github.com/freeCodeCamp/freeCodeCamp/pull/12663/files#diff-fa15da2c3b9ebc5c5f9028135cafe5f8R2053

```js
         "<div class=\"box yellow-box\">",
         "  <h5 class=\"box red-box\">padding</h5>",
         "  <h5 class=\"box green-box\">padding</h5>",
         "</div>",
         "</style>", //<-----
         "",
```
which has crept in somehow?

**Review by raisedadead — APPROVED** [review]
Except a small change not related to this PR we are looking good, thanks @HKuz

**Comment by HKuz** [comment]
@raisedadead just saw that issue, and that's a good catch! I'll make that fix here 👍

**Comment by HKuz** [comment]
Those `h1` lines at the bottom weren't supposed to be in there either, so I took those out.

**Review by raisedadead — APPROVED** [review]
#### :sparkles: :sparkles: **LGTM.** :sparkles: :sparkles: 

Thanks @HKuz

**Pull request merged**
