### PR TITLE
feat(docs): Add Mod Onboarding Guide to _sidebar.md

### PR DESCRIPTION
**Pull request by hbar1st**
Checklist:

- [X] I have read [freeCodeCamp's contribution guidelines](https://contribute.freecodecamp.org).
- [X] My pull request has a descriptive title (not a vague title like `Update index.md`)
- [X] My pull request targets the `main` branch of freeCodeCamp.
- [X] I have tested these changes either locally on my machine, or GitPod.

Closes #XXXXX

When the Mod. Onboarding guide was created, it didn't get added to the list of flight manuals in the fCC doc.  This PR updates the _sidebar.md to make it show up below the Moderator Handbook.

### CODE REVIEW

**Review by Sboonny — APPROVED** [review]
LGTM 🎉, thank you for your contribution to the page! 👍.

**Review by raisedadead — CHANGES_REQUESTED** [review]
Hi @hbar1st 

I just noticed this guide exists. IMHO the content of the guide should be a part of the moderator handbook itself. 

Let me know if you are interested in merging the text copy into the handbook, or I could do that in a later PR?

**Comment by hbar1st** [comment]
The onboarding guide is meant to be updated to include onboarding steps for other platforms (not just the discourse forum) and as such merging it with the main guide may be problematic because it would increase the size but would mostly be ignored by people who have already been onboarded? I'm not sure. The decision to make an onboarding guide came from discussions with other mods so it may be prudent to let others give their opinions on this in a different issue perhaps.

**Comment by raisedadead** [comment]
There is a reason we call it the moderator's handbook. We do not have multiple pages for multiple platforms. That is by design. Fragmentation inherently means something parts are less important than others. Instead, we have always put guidelines in one singular handbook because it tells everyone this is important – you should read and re-read it. The idea of a "handbook" is to be lengthy and comprehensive.

We have often established this in our publications with all our handbooks for JS, Python, Linux, etc.

You are welcome to check in with other mods, but there is a president here :)

**Comment by hbar1st** [comment]
I have revived the discussion on the forum about this. I will close the PR until a resolution is agreed upon there.
Thanks.

**Pull request closed without merging**
