### PR TITLE
refactor(api): import ts-reset in entrypoint

### PR DESCRIPTION
**Pull request by ojeytonwilliams**
It simplifies the config and slightly improves startup times in
development.

Checklist:

- [x] I have read and followed the [contribution guidelines](https://contribute.freecodecamp.org).
- [x] I have read and followed the [how to open a pull request guide](https://contribute.freecodecamp.org/#/how-to-open-a-pull-request).
- [x] My pull request targets the `main` branch of freeCodeCamp.
- [x] I have tested these changes either locally on my machine, or GitPod.

### CODE REVIEW

**Review by ShaunSHamilton — APPROVED** [review]
Seems fine. I could not find a definition for `ts-node` in a `tsconfig` file. Accidental? Or, unused?

**Comment by ojeytonwilliams** [comment]
It's no-longer used. The only thing it was doing was sourcing all files and this PR removes the need.

**Review by naomi-lgbt — APPROVED** [review]
If only typescript did this natively 😔

**Comment by ojeytonwilliams** [comment]
@naomi-lgbt it's ts-node that's the problem here. If you use `tsc` it works just fine (it compiles everything), but ts-node tries to save startup time by compiling lazily. Which is great... until you need something that's not directly required.

**Pull request merged**
