### PR TITLE
fix: sent to local repo in error

### PR DESCRIPTION
**Pull request by leebut**
- [x] I have read [freeCodeCamp's contribution guidelines](https://github.com/freeCodeCamp/freeCodeCamp/blob/master/CONTRIBUTING.md).
- [x] My pull request has a descriptive title (not a vague title like `Update index.md`)
- [x] My pull request targets the `master` branch of freeCodeCamp.
- [x] None of my changes are plagiarized from another source without proper attribution.
- [x] My article does not contain shortened URLs or affiliate links.

If your pull request closes a GitHub issue, replace the XXXXX below with the issue number.

Closes #XXXXX

### CODE REVIEW

**Comment by leebut** [comment]
It looks like more than one file was submitted. They are self-produced about flexbox. I pulled them to my local freecodecamp repo in error. Some of the files have several commits because I didn't realise that files had to be index.md and that code needed particular formatting.

**Review by moT01 — CHANGES_REQUESTED** [review]
Thanks for the PR @leebut - but there is already an area with some flexbox articles [here](https://github.com/freeCodeCamp/freeCodeCamp/tree/master/guide/english/css/layout/flexbox) - You should try and merge these with those if you want this added. Also, we don't want to use images anymore, so those should be removed. Thanks.

**Comment by leebut** [comment]
Okay. Thanks, Tom.

**Comment by moT01** [comment]
Hey @leebut - not sure if you started modifying these yet. But I thought I could add some more details on what to do here. I'm not sure exactly what to do yet, but It looks like you spent some time on these and I would love to just be able to merge them. We do want to avoid duplicate articles, so we definitely want to either merge these with what we have already. Or possibly just replace what we have with these if they're significantly better. I didn't look through them thoroughly before, so I'm not sure on that. And as far as the images go, we may be able to make an exception here since visuals are really helpful when talking about flexbox. I can take a closer look at some point in the near future and possibly give a better plan - and maybe get some input from someone else. Or if you had something in mind you can let us know or just make the changes.

**Comment by moT01** [comment]
Yea, I don't know what to tell ya here @leebut - the articles we have are okay. There's definitely some issues with them, but they aren't bad. These seem about the same - perhaps the `flex-grow` article could be replaced with yours, but the others seem about the same. Like I said before, we don't want duplicate articles - so if you want to get something merged here you're going to have to make the changes to the articles we already have.

**Comment by leebut** [comment]
Not to worry, Tom. I enjoyed writing them, which also helped me to consolidate my knowledge. At the time I didn't realise there were already articles present.

Thank you for your input.
All the best.

**Review by QuincyLarson — APPROVED** [review]
Solid improvements.

**Comment by QuincyLarson** [comment]
@moT01 I'm going to go ahead and merge these and we can sort out the duplication when we move these over to the guide. 

@leebut Thanks again for your contribution.

**Comment by leebut** [comment]
@QuincyLarson Thank you. I'm just happy to have learned something and be able to pass it on.

**Pull request merged**
