### PR TITLE
fix(a11y): accessibility for code examples/add copy button

### PR DESCRIPTION
**Pull request by bbsmooth**
Checklist:

- [x] I have read [freeCodeCamp's contribution guidelines](https://contribute.freecodecamp.org).
- [x] My pull request has a descriptive title (not a vague title like `Update index.md`)
- [x] My pull request targets the `main` branch of freeCodeCamp.
- [x] I have tested these changes either locally on my machine, or GitPod.

Closes #XXXXX

I've been using `/learn/responsive-web-design/basic-css/import-a-google-font` for testing but you can use any curriculum page that has a code example.

The PrismJS syntax highlighter adds a `tabindex=0` to the `<pre>` tag used for code examples, which is needed since these elements have the potential to overflow, and some browsers (cough, chrome, cough) do not allow keyboard users to scroll overflowing elements by default. But to be truly accessible, adding `tabindex` is not enough. The `<pre>` element must also be given an accessible role and name, which will also turn it into a landmark. This is not a terrible option, but if there are several code blocks on the page then that adds several landmarks, which isn't necessarily a great option for screen reader users (landmarks should be kept to a minimum).

But we can avoid all of the above if the overflow element has a focusable element in it, such as a button. Then the keyboard user would always be able to scroll the overflowing element, regardless of browser, once they put the keyboard focus on the button. If we added a "copy" button to the code example then we could solve the above accessibility issue and also provide added accessibility by making it much easier to copy the code for non-mouse users.

### CODE REVIEW

**Review by ShaunSHamilton — COMMENTED** [review]
Heya,

Would you mind changing the new file name to kebab-case? We have been slowly migrating that way.

There is not enough of an industry convention to name the file exactly the same as the class.

**Comment by nhcarrigan** [comment]
While I'm all for the accessibility fix, I'm concerned that adding a copy code button to our examples is going to result in campers copying the examples and asking on the forums why their code isn't working (more than they do already).

**Comment by bbsmooth** [comment]
@nhcarrigan That is a good point I didn't really consider. If this solution isn't the best for FCC then I'll happily withdraw it and implement the other solution I mentioned.

**Comment by ahmadabdolsaheb** [comment]
I could see how this would be useful specially for people using cellphones. 
At the same time I share @nhcarrigan's concerns, and that excessive copy pasting might affect learning and retention.

**Comment by bbsmooth** [comment]
It sounds like the copy button feature is a no-go for the challenges, so I will submit a new PR that uses the region method instead. And then maybe someday Chrome can get its act together and make scrollable elements keyboard accessible and we won't have to worry about this any more.

**Comment by ahmadabdolsaheb** [comment]
Sounds like a plan. So I will close this pr based on our discussion and look forward to your upcoming pr.

**Pull request closed without merging**
