### PR TITLE
fix: add missing period in file

### PR DESCRIPTION
**Pull request by aknouche**
Checklist:

- [x] I have read [freeCodeCamp's contribution guidelines](https://contribute.freecodecamp.org).
- [x] My pull request has a descriptive title (not a vague title like `Update index.md`)
- [x] My pull request targets the `main` branch of freeCodeCamp.
- [x] I have tested these changes either locally on my machine, or GitPod.

Closes #42338

### CODE REVIEW

**Comment by aknouche** [comment]
I am a first time contributor. I forked the repo then went to the file "curriculum/challenges/english/01-responsive-web-design/basic-css/specify-how-fonts-should-degrade.md" and added a missing period. Then add comitted and made this pull request. Hoping everything looks ok

**Comment by raisedadead** [comment]
Looks great, you should edit the OP and add the issue no in the `Closes` section to get the original issue auto closed.

image

**Comment by aknouche** [comment]
Thank you! Done : )

**Review by raisedadead — APPROVED** [review]

**Comment by gikf** [comment]
Hey @aknouche 

Looks like other PR making similar changes was already merged - PR #42335. As such, we are going to close this as duplicate.

If you feel you have additional changes to expand upon this PR, please feel free to push your commits and request this PR be reopened.

Thanks again! 😊

---

If you have any questions, feel free to ask questions on the ['Contributors' category on our forum](https://forum.freecodecamp.org/c/contributors) or [the contributors chat room](https://chat.freecodecamp.org/channel/contributors).

**Pull request closed without merging**
