### PR TITLE
update codepen signup link

### LINKED ISSUE #13638: Codepen sign up link for other languages needs updating
#### Challenge Name

"Get Set for our Responsive Web Design Projects" (but for other languages)

#### Issue Description

Similar to an [earlier issue](https://github.com/freeCodeCamp/freeCodeCamp/issues/13630), Codepen's sign up page has changed and the sign-up link needs to be updated for the other languages.

#### Changes Proposed

[This line](https://github.com/freeCodeCamp/freeCodeCamp/blob/staging/seed/challenges/01-responsive-web-design/responsive-web-design-projects.json#L85), [this line](https://github.com/freeCodeCamp/freeCodeCamp/blob/staging/seed/challenges/01-responsive-web-design/responsive-web-design-projects.json#L126), and [this line](https://github.com/freeCodeCamp/freeCodeCamp/blob/staging/seed/challenges/01-responsive-web-design/responsive-web-design-projects.json#L173) need to be changed to

```
https://codepen.io/accounts/signup/user/free
```

### PR DESCRIPTION
**Pull request by sidoshi**
#### Pre-Submission Checklist

- [x] Your pull request targets the `staging` branch of freeCodeCamp.
- [x] Branch starts with either `fix/`, `feature/`, or `translate/` (e.g. `fix/signin-issue`)
- [x] You have only one commit (if not, [squash](http://forum.freecodecamp.com/t/how-to-squash-multiple-commits-into-one-with-git/13231) them into one commit).
- [x] All new and existing tests pass the command `npm test`. Use `git commit --amend` to amend any fixes.

#### Type of Change

- [x] Small bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds new functionality)
- [ ] Breaking change (fix or feature that would change existing functionality)
- [ ] Add new translation (feature adding new translations)

#### Checklist:

- [x] Tested changes locally.
- [x] Closes currently open issue Closes #13638

#### Description

Update the codepen signup link

### CODE REVIEW

**Comment by tommygebru** [comment]
Glad you caught this I was going to PR a new link
https://codepen.io/accounts/signup/user/free

**Comment by sid-doshi** [comment]
Sorry, screwed up with the issue number.
@tommygebru I don't get what you are saying.

**Review by Greenheart — CHANGES_REQUESTED** [review]
@sid-doshi Thanks for fixing this! The code changes looks great! :+1: :tada:

I've just got a few things I want to point out:
* You haven't named your branch to start with `fix/` or `feature/`.
* It seems like you haven't tested this locally.

#### To get your pull request merged:
1. Please review the [Contribution Guidelines](https://github.com/freeCodeCamp/freeCodeCamp/blob/staging/CONTRIBUTING.md).
2. Set up a local instance of freeCodeCamp (See the guide for details).
3. Create a new branch in your local project. Start it's name with `fix/` and then a title for your fix. Example: `fix/login-page-typos`.
4. Apply the same changes as you've done in this PR.
5. Test your changes to make sure they solve the original issue. In this case, open the relevant pages and see if the link works as expected.
5. `git add` and `git commit`. (See the guide for details).
6. Push your new local branch to your forked repository on GitHub (See the the guide for details).
7. Open a new PR with your new `fix/x-y-z` branch as the **target** and `freeCodeCamp/staging` as the **base** and fill out the description.

## I really understand that what's written above is much to take in!
**If you need any help**, feel free to reach out to me or other contributors in [this chat room](https://gitter.im/FreeCodeCamp/Contributors). We want to help you through this process! :blush:

**Comment by sid-doshi** [comment]
see #13675

**Pull request closed without merging**
