### PR TITLE
want to create a german folder to start working on german translations for the website. 

### PR DESCRIPTION
**Pull request by joshuaRuff**
- [check ] I have read [freeCodeCamp's contribution guidelines](https://github.com/freeCodeCamp/freeCodeCamp/blob/master/CONTRIBUTING.md).
- [check ] My pull request has a descriptive title (not a vague title like `Update index.md`)
- [check ] My pull request targets the `master` branch of freeCodeCamp.
- [ check] None of my changes are plagiarized from another source without proper attribution.
- [check ] My article does not contain shortened URLs or affiliate links.

If your pull request closes a GitHub issue, replace the XXXXX below with the issue number.

Closes #XXXXX

### CODE REVIEW

**Comment by Jacobmpp** [comment]
that is crazy in a good way(a lot of work)

**Comment by joshuaRuff** [comment]
Yes, will be a side project for awhile

**Comment by joshuaRuff** [comment]
A little at a time :D

**Comment by joshuaRuff** [comment]
Did this wrong so closed it.

**Pull request closed without merging**
