### PR TITLE
Javascript -> JavaScript (English)

### PR DESCRIPTION
**Pull request by lipis**
- [x] I have read [freeCodeCamp's contribution guidelines](https://github.com/freeCodeCamp/freeCodeCamp/blob/master/CONTRIBUTING.md).
- [x] My pull request has a descriptive title (not a vague title like `Update index.md`)
- [x] My pull request targets the `master` branch of freeCodeCamp.
- [x] None of my changes are plagiarized from another source without proper attribution.
- [x] All the files I changed are in the same world language (for example: only English changes, or only Chinese changes, etc.)
- [x] My changes do not use shortened URLs or affiliate links.

Closes #XXXXX

### CODE REVIEW

**Comment by RandellDawson** [comment]
@raisedadead I had planned on reviewing this one.  Can you add your commentary on issue #35185 ?

**Comment by RandellDawson** [comment]
@lipis There are 104 earlier PRs which have changes on one or more of the files on this PR, so this will take a long time to review these.  It might help if you broke this PR up into separate PRs (one for JavaScript and one for TypeScript).

**Comment by lipis** [comment]
Removed Typescript from this PR.. but Javascript for English still affects many files..

**Comment by RandellDawson** [comment]
@lipis I made a mistake in my last reply.  I meant to say **do not split this PR**, but instead I said **do split**.   We had already started working on the earlier PRs which would have needed reviewing to get this PR merged.  It was my mistake, so at this point, we will leave them split and I will make a new list of earlier PRs to work through.  This will not take me long at all so don't worry.

**Comment by thecodingaviator** [comment]
We have so many merge conflicts on this PR that I don't think that it is worth the pain to work them out. IMO pulling a fresh copy of the fCC master branch and then doing all replacements again is better. What do you think @RandellDawson ?

**Comment by RandellDawson** [comment]
@thecodingaviator No don't worry, I will take care of them.

**Review by thecodingaviator — APPROVED** [review]
LGTM! 👍

**Comment by thecodingaviator** [comment]
@lipis Thank you for your contribution to the page! 👍
We're happy to accept these changes, and look forward to future contributions. 📝

**Pull request merged**
