### PR TITLE
Added links at the place of FreeCodeCamp.org

### PR DESCRIPTION
**Pull request by iamvevaar**
I have added the below link at the appropriate position
(https://www.freecodecamp.org)

Checklist:

- [x] I have read [freeCodeCamp's contribution guidelines](https://contribute.freecodecamp.org).
- [x] My pull request has a descriptive title (not a vague title like `Update index.md`)
- [x] My pull request targets the `main` branch of freeCodeCamp.
- [x] I have tested these changes either locally on my machine, or GitPod.

Closes #XXXXX

### CODE REVIEW

**Comment by gikf** [comment]
Hey @gautammsuthar

Thank you for opening this pull request.

Could you include some reasoning for the change? Is there a specific reason why links were added in those particular places? There's a couple more locations with the same text, that don't have the link added.

**Comment by gautammsuthar** [comment]
Reason is that
There will be more chance that READER will visit the site.

**Comment by gautammsuthar** [comment]
Thanks
So I think,
I should close the PR

**Comment by Sembauke** [comment]
Hey @gautammsuthar,

I do not think this change is necessary, sorry!

We hope to see more of you in the future 😄 

You can always look at the first timer only label for an entry level issue. If you are up for the challenge you can always look at the help wanted label.

But as you are a First timer, I would suggest keeping an eye out on the first timer only label because it's Hacktoberfest 😉

I hope you are having a great day, and happy coding.

**Comment by gautammsuthar** [comment]
@Sembauke 
Thanks For the Value

**Pull request closed without merging**
