### PR TITLE
Added support for British version of Gray 

### LINKED ISSUE #38123: Add support for British version of gray
**Describe your problem and how to reproduce it:**
As per [this forum post](https://www.freecodecamp.org/forum/t/deaclaring-a-variable-in-css/344859) we need to add support for British `grey` in [Basic CSS: Create a custom CSS Variable](https://www.freecodecamp.org/learn/responsive-web-design/basic-css/create-a-custom-css-variable) challenge as it's totally valid.

Also test regex might be slightly improved to ensure proper syntax:
```
/\.penguin\s*\{[^{}]*?--penguin-skin\s*:\s*gr[ae]y\s*;[^{}]*?\}/
```

### PR DESCRIPTION
**Pull request by Pallof**
Checklist:

- [x] I have read [freeCodeCamp's contribution guidelines](https://github.com/freeCodeCamp/freeCodeCamp/blob/master/CONTRIBUTING.md).
- [x] My pull request has a descriptive title (not a vague title like `Update index.md`)
- [x] My pull request targets the `master` branch of freeCodeCamp.
- [x] All the files I changed are in the same world language, for example: only English changes, or only Chinese changes, etc.

Closes #38123

### CODE REVIEW

**Review by ojeytonwilliams — APPROVED** [review]
LGTM :+1:

**Comment by ahmadabdolsaheb** [comment]
LGMT. might be affected by code freeze #38308

**Comment by moT01** [comment]
I believe we are still able to merge PR's to the responsive web section if they only change things that won't need translating - basically the tests and code. So I think this one is fine.

Can anyone confirm this?

**Comment by mstillman9** [comment]
@moT01 Hi, are there any updates on this? Me and Daniel (@Pallof ) were wondering if this can be merged.

**Comment by moT01** [comment]
@raisedadead - I believe there a couple PR's out there that only change tests and/or non translated things for the code freeze section. If those aren't being translated, I feel like we would be fine to merge them. I believe I've been told at one point that it's fine and another that we shouldn't. Can I get some final clarification on this?

**Comment by raisedadead** [comment]
> Can I get some final clarification on this?

Let me get some for you, I have a meeting with Oliver later today :)

**Comment by ahmadabdolsaheb** [comment]
We are planning to use english tests for other languages so this should not be affected by the freeze.

**Pull request merged**
