### PR TITLE
Updated index.md

### PR DESCRIPTION
**Pull request by ritulsriva**
Added more resources to the article

- [ ] I have read [freeCodeCamp's contribution guidelines](https://github.com/freeCodeCamp/freeCodeCamp/blob/master/CONTRIBUTING.md).
- [ ] My pull request has a descriptive title (not a vague title like `Update index.md`)
- [ ] My pull request targets the `master` branch of freeCodeCamp.
- [ ] None of my changes are plagiarized from another source without proper attribution.
- [ ] My article does not contain shortened URLs or affiliate links.

If your pull request closes a GitHub issue, replace the XXXXX below with the issue number.

Closes #XXXXX

### CODE REVIEW

**Review by RandellDawson — DISMISSED** [review]
Move the following to be outside the code block:
```
You can refer to this article for deeper insight into regression  
https://www.analyticsvidhya.com/blog/2017/06/a-comprehensive-guide-for-linear-ridge-and-lasso-regression/
```

**Review by ritulsriva — COMMENTED** [review]
I have added the resource article outside the codeblock which I mistakenly inserted inside the codeblock in my previous commit.

**Review by cmccormack — APPROVED** [review]
This looks good to me.  Thank you for your contribution!

**Comment by moT01** [comment]
Looks good @ritulsriva, thanks for contributing to freeCodeCamp! In the future, be sure to fill out the checklist in the PR template provided. Thanks!

**Pull request merged**
