### PR TITLE
fix(client): handle empty editor contents

### LINKED ISSUE #46814: Bugs in Colored Markers Step 2
### Describe the Issue

I am able to pass this step by completely removing all HTML from the editor. I am also able to pass this step if I add the correct `head` and `body` elements but delete everything else. Finally, I am able to pass this test if I add the `body` element before the `head` element.

### Affected Page

https://www.freecodecamp.org/learn/2022/responsive-web-design/learn-css-colors-by-building-a-set-of-colored-markers/step-2

### Your code

Described above.

### Expected behavior

I'm not sure how many of these bugs absolutely need fixing but I would think the empty editor bug should be fixed for sure. And since the instructions ask that the `body` element be added after the `head` element we should probably fix that one as well.

### Screenshots

_No response_

### System

Confirmed with newest versions of both Chrome and Firefox.

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by ojeytonwilliams**
Checklist:

- [x] I have read [freeCodeCamp's contribution guidelines](https://contribute.freecodecamp.org).
- [x] My pull request has a descriptive title (not a vague title like `Update index.md`)
- [x] My pull request targets the `main` branch of freeCodeCamp.
- [x] I have tested these changes either locally on my machine, or GitPod.

Closes https://github.com/freeCodeCamp/freeCodeCamp/issues/46814

### CODE REVIEW

**Review by Sboonny — APPROVED** [review]
LGTM 🎉, thank you for your contribution to the page! 👍.

**Review by Sembauke — APPROVED** [review]

**Comment by Sembauke** [comment]
Yes we would love to see more contributions from you @ojeytonwilliams 😜

**Comment by RandellDawson** [comment]
@ojeytonwilliams Are there any new tests that can be written to assure changes in the code base do not result in this situation again?

**Comment by ojeytonwilliams** [comment]
@RandellDawson I was wondering about that, too.

The problem is we have the ability to test multiple good solutions, but not multiple bad ones. Right now we check if the seed code fails (since it should), but that's it.  What we'd need is something like this:

````
# --solutions--

```html
<h1>Hello World</h1>
```

# --bad-solutions--

```html
<h1>Hello Hello Hello</h1>
```
````

and then test the bad solutions, if they exist, in the test that's currently called `Test suite must fail on the initial contents`.

Now that I've sketched it out, this feels like a reasonable feature request. What do you think?

**Pull request merged**
