### PR TITLE
feat(e2e): enable cypress retries

### PR DESCRIPTION
**Pull request by ojeytonwilliams**
As discussed in https://github.com/freeCodeCamp/freeCodeCamp/issues/41009

### CODE REVIEW

**Comment by raisedadead** [comment]
Do we need to undo the changes that I made in #41010 to see this in action? Or the we need to increase the delay regardless.

**Comment by ojeytonwilliams** [comment]
I was expecting to see some other flaky tests, not just the one we've been seeing recently.  I've pushed https://github.com/freeCodeCamp/freeCodeCamp/tree/feat/enable-cypress-retries so we can look in the dashboard and check I didn't mess up the config.

>  we need to increase the delay regardless.

In the short term, sure, but we really should not need to - the tests should not be taking anywhere near that amount of time.

**Comment by nhcarrigan** [comment]
According to their status page, GitHub Actions is experiencing degraded performance. Could this be the cause of tests timing out?

**Review by naomi-lgbt — APPROVED** [review]
Looks good to me.

Pulled this down locally, and it does retry failing tests:

image


(As an aside, these ones refuse to pass locally for me.)

**Pull request merged**
