### PR TITLE
Better visibility for `<code>` in night mode

### LINKED ISSUE #9838: Night mode and visually impaired
The light grey labels in the instructions portion of the screen have neon green text color. That is not the best color scheme for people with visual issues. There is a chrome plugin and some script to change these things locally but that shouldn't really be something the user needs to do is it? I don't know. Maybe it isn't really an issue. If it isn't go on and close this I apologize.

### PR DESCRIPTION
**Pull request by justincorrigible**
#### Pre-Submission Checklist
- [x] Your pull request targets the `staging` branch of FreeCodeCamp.
- [x] Branch starts with either `fix/`, `feature/`, or `translate/` (e.g. `fix/signin-issue`)
- [x] You have only one commit (if not, [squash](http://forum.freecodecamp.com/t/how-to-squash-multiple-commits-into-one-with-git/13231) them into one commit).
- [x] All new and existing tests pass the command `npm run test-challenges`. Use `git commit --amend` to amend any fixes.
#### Type of Change
- [x] Small bug fix (non-breaking change which fixes an issue)
#### Checklist:
- [x] Tested changes locally.
- [x] Closes currently open issue: Closes #9838 
#### Description

Darkened the element's background while making the text slightly brighter. Easy fix.

### CODE REVIEW

**Comment by dhcodes** [comment]
@hallaathrad much improved, but dare I say the new color scheme throws off the theme a bit imho. I wonder if it wouldn't be as good to use the same dark background as the editor and output boxes (#242424). Maybe this is worth a look from @QuincyLarson.

**Comment by hallaathrad** [comment]
That's a perfectly reasonable request. :D
Merge away.

**Comment by dhcodes** [comment]
tested and works great! Thanks for contributing to freecodecamp! 👍   🎉

**Comment by hallaathrad** [comment]
Thank you for QAing me :)

**Pull request merged**
