### PR TITLE
fix(curriculum): give useful hint for step 50 of statistics calculator if you are missing the starting value of the reduce.

### LINKED ISSUE #56938: Step 50 of Statistics Calculator doesn't give useful hint if you are missing starting value of reduce
### Describe the Issue

The step doesn't give a useful hint if you are missing the initial value of the reduce.

### Affected Page

https://www.freecodecamp.org/learn/javascript-algorithms-and-data-structures-v8/learn-advanced-array-methods-by-building-a-statistics-calculator/step-50

### Your code

```js
const getVariance = (array) => {
  const mean = getMean(array);
  const differences = array.map(
    el => el - mean
  );
  const squaredDifferences = differences.map(
    el => el ** 2
  );
  const sumSquaredDifferences = squaredDifferences.reduce((acc, el) => acc + el);

}


```

### Expected behavior

I would expect an hint that said that you are missing the starting value of the reduce.

### Screenshots

Image

### System

- Device: [e.g. iPhone 6, Laptop]
- OS: [e.g. iOS 14, Windows 10, Ubuntu 20.04]
- Browser: [e.g. Chrome, Safari]
- Version: [e.g. 22]

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by Agung1606**
Checklist:

- [x] I have read and followed the [contribution guidelines](https://contribute.freecodecamp.org).
- [x] I have read and followed the [how to open a pull request guide](https://contribute.freecodecamp.org/how-to-open-a-pull-request/).
- [x] My pull request targets the `main` branch of freeCodeCamp.
- [x] I have tested these changes either locally on my machine, or GitPod.

Closes #56938

### CODE REVIEW

**Comment by ilenia-magoni** [comment]
Please stop closing and opening PRs, you can make changes to the existing PR to address any issues, withotu closing it. Thank you

**Comment by Agung1606** [comment]
> Please stop closing and opening PRs, you can make changes to the existing PR to address any issues, withotu closing it. Thank you

sorry i didn’t know how to do it 🙏

**Comment by ilenia-magoni** [comment]
You can ask for help, opening a topic on the forum or writing on discord

**Comment by Agung1606** [comment]
> You can ask for help, opening a topic on the forum or writing on discord

should i continue this pr or what?

**Comment by ilenia-magoni** [comment]
Yes please keep this PR! You said you didn't know how to do something, when you don't know how to do something you can ask for help

**Comment by Agung1606** [comment]
> Yes please keep this PR! You said you didn't know how to do something, when you don't know how to do something you can ask for help

okay thank you

**Review by a2937 — APPROVED** [review]
Thank you for your patience. This does solve the issue and as a result I'm approving it.

**Review by majestic-owl448 — APPROVED** [review]

**Pull request merged**
