### PR TITLE
fix(challenge): check for li and specify elements accepting text

### PR DESCRIPTION
**Pull request by lasjorg**
- [x] I have read [freeCodeCamp's contribution guidelines](https://github.com/freeCodeCamp/freeCodeCamp/blob/master/CONTRIBUTING.md).
- [x] My pull request has a descriptive title (not a vague title like `Update index.md`)
- [x] My pull request targets the `master` branch of freeCodeCamp.
- [x] None of my changes are plagiarized from another source without proper attribution.
- [x] All the files I changed are in the same world language (for example: only English changes, or only Chinese changes, etc.)
- [x] My changes do not use shortened URLs or affiliate links.

Fixes for the challenge: https://learn.freecodecamp.org/front-end-libraries/react/create-a-complex-jsx-element/

1. The assertion test does not check for the type of ul children. You can pass using the wrong elements.

2. Right now the challenge text says "You can include any text you want within each element". However, text is not permitted content for the ul element. I changed the text to specify what elements accept text.

3. I switched the order of the tests to be first element, second element, third element. Instead of before where it was second element, third element, first element. Not sure why it was like that, but I didn't see a reason for it.

@RandellDawson If you have the time at some point can you test this locally?

Note: The test still uses hard-coded positions for the elements. The last test will fail with an incorrect assertion text if you mess up the order of the element because it depends on the location of the UL.

```
// This will fail with the assertion for the last test "The ul should contain three li elements."
const JSX = <div>
  <h1>Start</h1>
  <ul>
    <li>2</li>
    <li>2</li>
    <li>2</li>
  </ul>
  <p>Paragraph Two</p>
</div>
```

### CODE REVIEW

**Comment by lynxlynxlynx** [comment]
LGTM, except 2) looks like a needless complication of the instructions. If we cared that nobody put anything semantically inappropriate in the ul, we'd add a test for it. But that's not the point of this exercise.

**Comment by RandellDawson** [comment]
@lasjorg I agree with @lynxlynxlynx's assessment of num 2 above.  Please revert those changes.  Everything else looks good to me.

**Comment by RandellDawson** [comment]
@lasjorg I think your changes are fine now.  However, if you are concerned about the last test failing if the `ul` element is placed out of order, then would the following work?
```
  - text: The <code>ul</code> should contain three <code>li</code> elements.
    testString: assert(JSX.props.children.filter(ele => ele.type === 'ul')[0].props.children.filter(ele => ele.type === 'li').length === 3);
```

**Comment by RandellDawson** [comment]
@lasjorg What do you think about my last comment?

**Comment by RandellDawson** [comment]
@lasjorg Any comment?

**Comment by lasjorg** [comment]
@RandellDawson Sorry for the delay.

That is a good idea. I have updated the test and also removed the secondary assertion texts.

**Review by ojeytonwilliams — APPROVED** [review]
LGTM :+1:

**Review by thecodingaviator — APPROVED** [review]
LGTM! 👍

**Comment by thecodingaviator** [comment]
Thank you for your contribution to the page! 👍
We're happy to accept these changes, and look forward to future contributions. 📝

**Pull request merged**
