### PR TITLE
fix(curriculum): Added definition of vh and rem

### LINKED ISSUE #46502: New RWD : Concepts like `vh` and `rem` are never explained
### Describe the Issue

In [step 7](https://www.freecodecamp.org/learn/2022/responsive-web-design/learn-html-forms-by-building-a-registration-form/step-7) of `Learn HTML Forms by Building a Registration Form`  , we are asked to set the height of the body element to 100vh. However, the unit vh was never introduced in earlier lessons and there is no explanation given at this step too as to what it is.

As I continued through the course, I stumbled upon another unexplained unit `rem` in [step 14](https://www.freecodecamp.org/learn/2022/responsive-web-design/learn-html-forms-by-building-a-registration-form/step-14)

`em` isn't explained either in [step 38](https://www.freecodecamp.org/learn/2022/responsive-web-design/learn-html-forms-by-building-a-registration-form/step-38) 

Relative units were never explained in the course. The problem seems to be that this practice projects assumes familiarity with these concepts.
 

### Affected Pages

https://www.freecodecamp.org/learn/2022/responsive-web-design/learn-html-forms-by-building-a-registration-form/step-7
https://www.freecodecamp.org/learn/2022/responsive-web-design/learn-html-forms-by-building-a-registration-form/step-14
https://www.freecodecamp.org/learn/2022/responsive-web-design/learn-html-forms-by-building-a-registration-form/step-38

### Your code

n/a

### Expected behavior

 A brief explanation on relative units in CSS would help new learners.

### PR DESCRIPTION
**Pull request by Ayush-singla27**
added definition of `vh` at [step 8](https://www.freecodecamp.org/learn/2022/responsive-web-design/learn-html-forms-by-building-a-registration-form/step-8) of "Learn HTML Forms by Building a Registration Form" and definition of `rem` at [step 15](https://www.freecodecamp.org/learn/2022/responsive-web-design/learn-html-forms-by-building-a-registration-form/step-15) of "Learn HTML Forms by Building a Registration Form"

Checklist:

- [x] I have read [freeCodeCamp's contribution guidelines](https://contribute.freecodecamp.org).
- [x] My pull request has a descriptive title (not a vague title like `Update index.md`)
- [x] My pull request targets the `main` branch of freeCodeCamp.
- [x] I have tested these changes either locally on my machine, or GitPod.

Closes #46502

### CODE REVIEW

**Review by gikf — COMMENTED** [review]
Why ids of these challenges and file names were changed?

**Comment by Ayush-singla27** [comment]
oh sorry, i think i misunderstood the contributor guide. Are rest of the changes fine? i will create a new PR.

**Comment by raisedadead** [comment]
You don't have to close a PR to make fixes, you can push new commits to the same branch. 

You must read the contribution guidelines. They have a lot of details to avoid issues like this. Your previous PR: https://github.com/freeCodeCamp/freeCodeCamp/pull/47874 was making the correct changes.

**Comment by Ayush-singla27** [comment]
Ok, thank you. I have edited the PR and now it should be fine.

**Comment by raisedadead** [comment]
Looks better now; the only thing is you have created the PR from the main branch of your fork. 

That's OK for now, but when you want to make PRs later for future contributions, you must reset it correctly. That is, your fork is now in a soiled state.

**Comment by Ayush-singla27** [comment]
Ok sir, next time i will make sure to make a branch. Looking forward to making more contributions to this repo! Also thanks for the help.

**Review by raisedadead — APPROVED** [review]

**Review by Sembauke — APPROVED** [review]

**Pull request merged**
