### PR TITLE
Fix/Remove Filter and Adjust Map Spacing and Coloring

### LINKED ISSUE #6414: Map's "show incomplete challenges" should hide empty chapters.
The button works great, but as it hides the unfinished stuff, it shouldn't leave a bunch of empty chapter titles behind. Ideally, for someone with just one challenge to complete, should see an almost empty map.
screen shot 2016-01-24 at 14 01 02

----
On a side note, shouldn't the completed challenges be hidden by default, and have the option to show them all instead?

### LINKED ISSUE #6564: Staging: Can't scroll all the way up map

### LINKED ISSUE #6575: Proper highlighting for completed challenges and their containers
As a follow up on #6414, and as per previous approval by @QuincyLarson in PR #6403:
The fully completed containers (otherwise known as superblocks), should add a `.faded` class to their containers, as shown at the bottom in the following screen capture.
This feature is slightly beyond my skills because of the involved detection for empty chapters...
Thus, "help wanted" applies.

screen shot 2016-01-29 at 09 01 47

------

Furthermore, The default behaviour for the map (or at least the sidebar's) should be that the completed ones are hidden, and then the button would let you see the hidden ones. I cannot think of any reason why any camper would by default want to see the completed from the beginning, when their common idea is to move forward.

This is a secondary idea and would indeed require Quincy's approval.

### LINKED ISSUE #6584: Remove show/hide incomplete challenges button from map
@bugron @hallaathrad

### LINKED ISSUE #6585: Never hide challenges in map (unless filtering using forthcoming realtime search)
@hallaathrad @bugron @SaintPeter

### PR DESCRIPTION
**Pull request by SaintPeter**
This PR combines #6590 and #6464, since they really were not very separable.

image

Tested locally at as many sizes as I could make my browser.

Note that this contains two commits because it combines the work of two separate people.

Fixes #6585
Fixes #6584 
Fixes #6564
Closes #6575
Closes #6414

### CODE REVIEW

**Comment by SaintPeter** [comment]
@QuincyLarson This is the one to test and merge at your leisure.

**Comment by hallaathrad** [comment]
@QuincyLarson's approval required, maybe?

**Comment by bugron** [comment]
This PR doesn't address any of the last three issues. I've removed them from the first comment.

**Comment by SaintPeter** [comment]
Thanks.

**Comment by SaintPeter** [comment]
Merging as per @QuincyLarson

**Pull request merged**
