### PR TITLE
feat: use English code in i18n challenges

### PR DESCRIPTION
**Pull request by ojeytonwilliams**
Checklist:

- [x] I have read and followed the [contribution guidelines](https://contribute.freecodecamp.org).
- [x] I have read and followed the [how to open a pull request guide](https://contribute.freecodecamp.org/#/how-to-open-a-pull-request).
- [x] My pull request targets the `main` branch of freeCodeCamp.
- [x] I have tested these changes either locally on my machine, or GitPod.

This should make our challenges a little more robust. If the translated challenge file has changes in the seed, testStrings or solution that will not matter, because the English's value will be used.   To confirm, if you make some changes to an i18n challenge's that cause the tests to fail, they should pass on this PR.

I also added some warnings, so the issues don't get buried. Another option is to add some checks to the challenge-auditor.

### CODE REVIEW

**Review by moT01 — COMMENTED** [review]
I played around with this a bit. I'm not in love with it, but I would be fine adding it if we want to try it out. It seems to work as intended.

It sure adds a lot of errors to the console on i18n builds. I looked into a few of them, they were all issues with extra spaces in the English files that must get removed after it goes through crowdin. So we could fix up those English files to get rid of a lot of those errors. Not sure if they're all from spacing issues.

I gave this a rebase to look at some challenges with recent changes. The i18n builds broke from a new test being added - e.g. espanol had 2 tests on a challenge and english had 3. Also, it changed the second test. So a potential issue with this approach would be that we change an english test (text and test) - and then the espanol build will display the old text, but use the new test? That seems sketchy. I suppose the same would apply to seed code or anything else we are taking from the english files? That could certainly cause some confusion.

Note that I mentioned a rebase broke the build - so we probably don't want to merge this until after a sync? I suppose it adds that as an issue as well. We may be forced to do a sync before we can deploy. I'm not sure how long a download takes - but it would certainly slow us down - mostly not much of a problem, but particularly crappy if we're trying to deploy something quickly.

I think we need some more discussion on this before we go with it. Could we add something to the download flow to transform that one broken file or something? Maybe something like that would be better.

**Comment by ojeytonwilliams** [comment]
> The i18n builds broke from a new test being added - e.g. espanol had 2 tests on a challenge and english had 3.

We could downgrade that to a warning and just use the English,. I just figured we'd want to know there was an issue and that we should sync.

**Comment by moT01** [comment]
> we should use the original code and not "translate" it.

I definitely like the idea, but the problem is that the English challenges don't align with the i18n challenges. So we will get issues like I mentioned above. A solution could be along the lines of something I've brought up a few times - separate the source files from the build files. e.g. English gets uploaded to crowdin, then we download all languages, including English, and use those to build. So all i18n curriculum files would align with English (align with English build files, not source files).

**Comment by ojeytonwilliams** [comment]
I think this is a good place to discuss how to solve this, but Tom's right: this isn't a good solution.

We should, instead, come up with an acceptable band-aid. Possibilities include

- Periodically replace the broken challenge/challenges with the original English by hand
- Write a script to do that
- Modify `getChallenges` to always use the English for this challenge

In addition, we need to think through Tom's idea (keep English source in a 'src' folder, but download all languages, including English into a 'dist' folder). I like this idea a lot, but I think it may need modifying if we want it to solve this problem. Reason being, if we want to solve the problem this PR solves, we'd need to use the files in the 'dist' folder to provide the translations and the files in the 'src' folder to provide the code. That leaves us with the synchronization problem that Tom discussed above.

For example, if we delete a challenge from 'src', we cannot get its code and we need to download into 'dist' before deploying.

---

One thing we can try is moving away from Markdown and, instead, upload JSON to crowdin.

Pros:
- We may need to do this if we start storing challenges in a db
- Hopefully JSON is easier to parse

Cons:
- The translation UI is a little less friendly. It's not too bad, but you can see the difference between the learn UI project and curriculum projects.

**Comment by naomi-lgbt** [comment]
I could just add a step to the workflow to copy that one broken challenge over

**Comment by ojeytonwilliams** [comment]
Naomi's workflow changes have fixed the immediate problem, so I don't think we need this any more.

**Pull request closed without merging**
