### PR TITLE
fix(curriculum): granular chart tests in budget app

### PR DESCRIPTION
**Pull request by gikf**
Checklist:

- [x] I have read and followed the [contribution guidelines](https://contribute.freecodecamp.org).
- [x] I have read and followed the [how to open a pull request guide](https://contribute.freecodecamp.org/how-to-open-a-pull-request/).
- [x] My pull request targets the `main` branch of freeCodeCamp.
- [x] I have tested these changes either locally on my machine, or GitPod.

- - -
- Adds few granular tests for chart:
  - Title at the top
  - Percentages at the left
  - Rounding of the bars
  - Length of the horizontal line
  - Category names written vertically
  - No new line at the end

### CODE REVIEW

**Comment by gikf** [comment]
That's because current `21` checks against string without the new line character at the end. I'm seeing two options:
1. Strip tailing new lines, from string returned by function, in the current `21` test.
2. Swap tests order, so new line is checked first, then the category names.

I think I like second one more.

**Comment by ilenia-magoni** [comment]
they would still both fail, and it can be confusing, I would guess you can implement both?

**Comment by Dario-DC** [comment]
The order is not really important since it is a lab and all the hints are visible. I'm okay with removing the trailing newline character.

**Review by majestic-owl448 — APPROVED** [review]

**Review by Dario-DC — COMMENTED** [review]
I found the last test failing like this:
```
AssertionError: 'Perc[34 chars]     \n 90|         \n 80|         \n 70|    o[329 chars] t  '
             != 'Perc[34 chars]      \n 90|          \n 80|          \n 70|  [340 chars] t  '
```

but none of the other is failing.

**Comment by gikf** [comment]
Yeah, that's not tested currently. I can add another test checking length of all lines.

**Review by majestic-owl448 — APPROVED** [review]

**Review by Dario-DC — APPROVED** [review]
Happy to approve this :tada: Thanks!

**Pull request merged**
