### PR TITLE
fix: Challenge solution added and broken test updated.

### PR DESCRIPTION
**Pull request by ojeytonwilliams**
- [x] I have read [freeCodeCamp's contribution guidelines](https://github.com/freeCodeCamp/freeCodeCamp/blob/master/CONTRIBUTING.md).
- [x] My pull request has a descriptive title (not a vague title like `Update index.md`)
- [x] My pull request targets the `master` branch of freeCodeCamp.
- [x] None of my changes are plagiarized from another source without proper attribution.
- [x] All the files I changed are in the same world language (for example: only English changes, or only Chinese changes, etc.)
- [x] My changes do not use shortened URLs or affiliate links.

The beta/rocks page, https://www.freecodecamp.rocks/learn/responsive-web-design/basic-css/use-css-selectors-to-style-elements, does not accept the solution of adding a single style element.  i.e.

```
<style>
  h2 {
    color: blue;
  }
</style>

<h2>CatPhotoApp</h2>...
```

  This PR corrects that and adds a bare-bones solution as well.

### CODE REVIEW

**Comment by RandellDawson** [comment]
All added solutions need to include all original Challenge Seed code and necessary changes to pass solution.  Thank you.

**Comment by RandellDawson** [comment]
Also, the challenge instructions are quite specific for this challenge:

>  and instead create a CSS style block

It does not say add more than one block.  This extra test change is not needed.

**Comment by ojeytonwilliams** [comment]
That's a bit strange, given that the rest of the solution isn't used in the tests.  Isn't including it just going to make the tests slower unnecessarily?

> It does not say add one or more style blocks. This extra test change is not needed, so please remove.

Fair enough, I just figured it wouldn't hurt to make the test forgiving.  Having said that, I don't know why someone would _want_ to add a second block. I'll make it an equality.

**Comment by RandellDawson** [comment]
> That's a bit strange, given that the rest of the solution isn't used in the tests. Isn't including it just going to make the tests slower unnecessarily?

It is our standard practice to include all code, so that in case any test added/changed breaks with a full working solution of the challenge, we know it has nothing to do with the solution.  It may not always been relevant with the current set of tests, but on many challenges it would be.  It is quite possible that someone might think they are add all "needed" code, but later tests added/changed could pass when they should not if the full solution was present.  This way, we don't have to worry about that scenario.

**Comment by ojeytonwilliams** [comment]
Righto.  I was operating under the assumption that the tests were basically a specification for what a solution has to be i.e. something that passes the tests!  Would it be possible to add a clarification to https://github.com/freeCodeCamp/freeCodeCamp/blob/master/docs/how-to-work-on-coding-challenges.md and/or https://github.com/freeCodeCamp/freeCodeCamp/blob/master/docs/style-guide-for-curriculum-challenges.md ?

**Comment by RandellDawson** [comment]
@ojeytonwilliams Great idea.  Would you mind creating a separate issue for your request, so we don't lose track and also, we can discuss/work out the verbiage which needs to be added before creating a PR for it.

**Comment by ojeytonwilliams** [comment]
@RandellDawson Sure, I'll do that in a sec.  I've made the changes as well.

**Comment by RandellDawson** [comment]
@ojeytonwilliams After thinking about it a bit more, I am reversing my original stance on allowing the multiple style elements.  I think your original idea of `>=` is fine.  Actually, I am not sure how campers were even getting past this test before when it was just `>`.

**Comment by ojeytonwilliams** [comment]
@RandellDawson Ah, that's because this bug isn't on live, just on beta/rocks.  I only stumbled across it when I was looking at something completely unrelated.  I'll change it back to >=.

**Comment by lasjorg** [comment]
I was looking at this bug, almost didn't see there was a PR already.

I didn't see an explanation for this bug so I just wanted to point out what I found.

Looks like there used to be a style element in head of the #fcc-main-frame iframe which is no longer there on master and the version on freecodecamp.rocks

The test which checks for the style element assumes the style element in head is there and is testing for `$("style").length > 1` (the style in head + the style added by the camper in the challenge). I search for other challenge tests and can't find any other that is using $("style") so it looks like it only broke the one challenge.


@ojeytonwilliams @RandellDawson Anyway, would scoping the selector to the body help future proof this test a bit better?

`$("body style").length > 0`

**Comment by ojeytonwilliams** [comment]
@lasjorg Good catch!  I wondered why this ever used to work.

As far as future proofing goes, it should be fine as is.  Reason being, this PR adds a solution, which means this challenge will be added to the test suite.  If someone adds a style element to the test frame, the challenge seed would no longer fail the tests (which it should!) and we'd know there's a problem.

**Comment by lynxlynxlynx** [comment]
LGTM!

**Review by RandellDawson — APPROVED** [review]
Tested locally.  LGTM

**Comment by RandellDawson** [comment]
Thank you for your contribution to the page! 👍
We're happy to accept these changes, and look forward to future contributions. 🎉

**Pull request merged**
