### PR TITLE
Add the 'Make navbar fixed'

### PR DESCRIPTION
**Pull request by manishkaa**
- [x] I have read [freeCodeCamp's contribution guidelines](https://github.com/freeCodeCamp/freeCodeCamp/blob/master/CONTRIBUTING.md).
- [x] My pull request has a descriptive title (not a vague title like `Update index.md`)
- [x] My pull request targets the `master` branch of freeCodeCamp.
- [x] None of my changes are plagiarized from another source without proper attribution.
- [x] My article does not contain shortened URLs or affiliate links.

If your pull request closes a GitHub issue, replace the XXXXX below with the issue number.

Closes #XXXXX

### CODE REVIEW

**Review by CodingSolo — COMMENTED** [review]
For me, all the examples at the end of the file should be deleted. They are poorly formatted and  does not improve the article

**Comment by manishkaa** [comment]
What I felt I wrote. But did not ask your opinions

**Comment by manishkaa** [comment]
Sir I think such examples actually help people who read..there are many but I found it more important as it is used more

**Comment by nikrb** [comment]
@manishkaa I think fixing the navbar is covered earlier in the article?
#### Displaying the navbar independent of scrolling

**Review by cmccormack — COMMENTED** [review]
Was this tested locally?  I'm worried this will take over the freeCodeCamp navigation bar.
Bootstrap does appear to be used on these pages when rendered @nikrb but we'll need to test locally prior to merging this example PR.

**Comment by nikrb** [comment]
@cmccormack fixing the navbar is covered earlier in the article, so I'm wondering if this pr is valid. If it turns out to be valid I'm quite happy to test it.

**Comment by cmccormack** [comment]
> @cmccormack fixing the navbar is covered earlier in the article, so I'm wondering if this pr is valid. If it turns out to be valid I'm quite happy to test it.

<https://guide.freecodecamp.org/bootstrap/navigation-bar> has actual examples of the navbar at the bottom, I believe that is what this PR is trying to add, an example of a fixed nav bar.

**Comment by nikrb** [comment]
@cmccormack you got it!
tested locally and it does sit at the top over the fcc menu.

**Comment by nikrb** [comment]
Hi @manishkaa, thanx for taking the time to open this pr. Unfortunately, as @cmccormack pointed out, the example code causes the navbar to appear at the top of the screen, overlaying and obscuring the fcc menu.
So sorry but we will have to close this pr. Please feel free to re-open the pr with a fix if you find one.
Thanx again for the pr and we look forward to future contributions :balloon:

**Pull request closed without merging**
