### PR TITLE
extended minimal example and Google CDN

### PR DESCRIPTION
**Pull request by danielpoehle**
- [ x ] I have read [freeCodeCamp's contribution guidelines](https://github.com/freeCodeCamp/freeCodeCamp/blob/master/CONTRIBUTING.md).
- [ x ] My pull request has a descriptive title (not a vague title like `Update index.md`)
- [ x ] My pull request targets the `master` branch of freeCodeCamp.
- [ x ] None of my changes are plagiarized from another source without proper attribution.
- [ x ] My article does not contain shortened URLs or affiliate links.

If your pull request closes a GitHub issue, replace the XXXXX below with the issue number.

Closes #XXXXX

### CODE REVIEW

**Comment by sergeyradov** [comment]
What are the next steps to get this PR merged? I am new in here, but looking for a chance to contribute.

**Comment by amandeepmittal** [comment]
@sergeyradov you submit a PR and one of the member will look take of the rest (which includes if there are any changes needed, you will be notified) otherwise the PR will undergo a process of CI passing and then ready to merge.

**Review by amandeepmittal — APPROVED** [review]
LGTM!

**Comment by amandeepmittal** [comment]
@danielpoehle Congratulations on your first PR 🎉

**Comment by moT01** [comment]
hey @amandeepmittal - I think we're supposed to start with the oldest PR's and work our way to the new ones.

**Pull request merged**
