### PR TITLE
Feature/add project euler problems

### PR DESCRIPTION
**Pull request by P1xt**
@QuincyLarson
@AdventureBear

Here's the bulk load json for the Project Euler stuff. It may or may not need to be resubmitted. I won't be resubmitting it but either of you are free to.

I ran a quick scrape of Project Euler to fill out the bulk of what will be needed for the add-project-euler-problems feature

The json contains all 600 existing questions, including a test against a confirmed correct answer for each question for which a confirmed answer is available. There is still more work to be done, but this should handle the initial bulk load.

- Questions for which I did not have confirmed answers for have "TODO" marked in the tests.
- Some descriptions contain latex - I scraped them off the official project euler site (where they use MathJax)
- Some descriptions contain images - easily found in the json by looking for contiguous blank lines - these will have to be handled manually.

### CODE REVIEW

**Comment by P1xt** [comment]
There is zero chance I'm squashing commits on this, I only had one commit but it was based off a branch @QuincyLarson created.

**Comment by raisedadead** [comment]
@P1xt thanks for the pull request, 

There are a lot of un-encoded values in the json, which would be an issue, please reformat things like :

`\u003c`

Also I am afraid you have to squash this because the PR does have 2 commits and you would possibly be editing the json for fixes. 

Also I believe that you can choose to do so this via multiple smaller PRs to make it easier for you?
Thanks.

**Review by raisedadead — DISMISSED** [review]
The diff is too long for review comments if possible please break into smaller pull requests.

**Comment by QuincyLarson** [comment]
@raisedadead This is fine for now. I've gone through and spot-checked it. It doesn't seem to be breaking the build - the JSON seems valid. 

This is a work in progress. I'm going to go ahead and merge it in.

**Pull request merged**
