### PR TITLE
Added solution to reuse-patterns-using-capture-groups.english.md

### PR DESCRIPTION
**Pull request by Hiyorimi**
- [x] I have read [freeCodeCamp's contribution guidelines](https://github.com/freeCodeCamp/freeCodeCamp/blob/master/CONTRIBUTING.md).
- [x] My pull request has a descriptive title (not a vague title like `Update index.md`)
- [x] My pull request targets the `master` branch of freeCodeCamp.
- [x] None of my changes are plagiarized from another source without proper attribution.
- [x] All the files I changed are in the same world language (for example: only English changes, or only Chinese changes, etc.)
- [x] My changes do not use shortened URLs or affiliate links.

### CODE REVIEW

**Comment by RandellDawson** [comment]
@Hiyorimi Even though your added solution passes, could you please paste a full solution which includes all of the original challenge seed code plus the additions/changes which allow the solution to pass?  We prefer solutions have all original seed code plush changes/additions to solve the challenge.

Thank you.

**Comment by Hiyorimi** [comment]
Updated the code, thank you!

**Comment by RandellDawson** [comment]
I have successfully tested this solution.  Still waiting on another PR to close/merge before merging this one.

**Review by RandellDawson — APPROVED** [review]

**Comment by Hiyorimi** [comment]
Other was closed, thank you!

**Comment by RandellDawson** [comment]
Thank you for your contribution to the page! 👍
We're happy to accept these changes, and look forward to future contributions. 🎉

**Pull request merged**
