### PR TITLE
test(e2e,playwright): progress-bar.tsx

### PR DESCRIPTION
**Pull request by Aman1919**
Checklist:

- [x] I have read and followed the [contribution guidelines](https://contribute.freecodecamp.org).
- [x] I have read and followed the [how to open a pull request guide](https://contribute.freecodecamp.org/#/how-to-open-a-pull-request).
- [x] My pull request targets the `main` branch of freeCodeCamp.
- [x] I have tested these changes either locally on my machine, or GitPod.

Related to https://github.com/freeCodeCamp/freeCodeCamp/issues/51705

### CODE REVIEW

**Comment by Aman1919** [comment]
i made  a fresh  pr https://github.com/freeCodeCamp/freeCodeCamp/pull/51789 .  prev on  was giving some error in node lint . i did all the changes it requested

**Review by huyenltnguyen — APPROVED** [review]

**Review by Ahmadkashif — APPROVED** [review]
LGTM!!

**Comment by Aman1919** [comment]
camperbot cant code

**Comment by Aman1919** [comment]
Can u merge this .

**Review by Ahmadkashif — APPROVED** [review]
It looks good to merge @Aman1919 

I would request you to maybe give the team a little more time as we have other PRs which are pending reviews.

Thank you for understanding.

**Review by huyenltnguyen — APPROVED** [review]

**Review by Sembauke — APPROVED** [review]

**Pull request merged**
