### PR TITLE
fix(curriculum): Update question in optimize media assets lecture

### LINKED ISSUE #57773: Update question in optimize media assets lecture
Here is the second question for that lecture video

```md
Which file type should you prefer?
```

That is really vague. I get that is trying to point to the WEBP option but here is a better question to use in its place.

```md
## --text--

Which of the following is NOT a valid image file type?

## --answers--

TS

---

PNG

### --feedback--

Review the video starting at the 53 second mark to see which of these options was not mentioned.

---

JPG

### --feedback--

Review the video starting at the 53 second mark to see which of these options was not mentioned.

---

WEBP

### --feedback--

Review the video starting at the 53 second mark to see which of these options was not mentioned.

## --video-solution--

1
```

Here is the file you need to update

https://github.com/freeCodeCamp/freeCodeCamp/blob/main/curriculum/challenges/english/25-front-end-development/lecture-working-with-media/67167835def3588873f339c6.md

### PR DESCRIPTION
**Pull request by Pratheek2474**
Checklist:

- [x] I have read and followed the [contribution guidelines](https://contribute.freecodecamp.org).
- [x] I have read and followed the [how to open a pull request guide](https://contribute.freecodecamp.org/how-to-open-a-pull-request/).
- [x] My pull request targets the `main` branch of freeCodeCamp.
- [x] I have tested these changes either locally on my machine, or GitPod.

Closes #57773

For my first Pull request, i changed a vague open ended question to a better one as suggested. I have replaced the answers as well as instructed.

### CODE REVIEW

**Comment by Pratheek2474** [comment]
i redid the commit based on the guidelines and naming conventions. can you please look into it?

**Comment by jdwilkin4** [comment]
In the future, it is best to avoid PR titles like `"Update 67167835def3588873f339c6.md"` or `"Updated 2nd question"`. 


I changed your title to something more descriptive so now we know what you are working on 👍

**Review by jdwilkin4 — APPROVED** [review]

**Comment by Pratheek2474** [comment]
Got it. I'll try to improve on commit messages.

**Review by a2937 — APPROVED** [review]

**Comment by ilenia-magoni** [comment]
@Pratheek2474 the issue was the PR title, not only commit messages

**Pull request merged**
