### PR TITLE
Update challenge description

### LINKED ISSUE #11104: No explanation what anti-pattern is
Challenge [Returning Boolean Values from Functions](https://www.freecodecamp.com/challenges/returning-boolean-values-from-functions) has an issue.
User Agent is: <code>Mozilla/5.0 (iPad; CPU OS 10_0_2 like Mac OS X) AppleWebKit/602.1.50 (KHTML, like Gecko) Version/10.0 Mobile/14A456 Safari/602.1</code>.
Please describe how to reproduce this issue, and include links to screenshots if possible.

My code:
```javascript

function isLess(a, b) {
  // Fix this code
  if (a < b) {
    return true;
  } else {
    return false;
  }
}

// Change these values to test
isLess(10, 15);

```

### PR DESCRIPTION
**Pull request by anu0012**
Remove 'anti-pattern' statement from the description.
Closes #11104

### CODE REVIEW

**Review by ghost — CHANGES_REQUESTED** [review]
#### LGTM :tada:

Just before we can merge this in, can you change `Fix #11104` to `Closes #11104`. This will let GitHub know to automatically close that issue once this PR is merged in!

**Comment by anu0012** [comment]
@atjonathan Updated.

**Comment by atjonathan** [comment]
Thanks and congratulations on your first open source contribution @anu0012!

**Review by ghost — APPROVED** [review]

**Comment by anu0012** [comment]
@atjonathan Thanks ^_^

**Pull request merged**
