### PR TITLE
fix: update Advanced Node and Express text

### PR DESCRIPTION
**Pull request by scissorsneedfoodtoo**
Checklist:

- [x] I have read [freeCodeCamp's contribution guidelines](https://contribute.freecodecamp.org).
- [x] My pull request has a descriptive title (not a vague title like `Update index.md`)
- [x] My pull request targets the `main` branch of freeCodeCamp.
- [x] I have tested these changes either locally on my machine, or GitPod.

Related to https://github.com/freeCodeCamp/freeCodeCamp/issues/46910

This PR updates the text in the Advanced Node and Express challenges to reflect that the required dependencies should already be installed.

### CODE REVIEW

**Review by Sboonny — APPROVED** [review]

**Review by majestic-owl448 — APPROVED** [review]

**Comment by RandellDawson** [comment]
Why was this PR merged before https://github.com/freeCodeCamp/boilerplate-advancednode/pull/24 was merged?  We have always merged the boilerplates on the same day or slightly before any changes merged on freeCodeCamp.org to prevent confusion in the instructions.  I noticed the instructions said pug was already installed yet the `package.json` file did not reflect that.

**Comment by RandellDawson** [comment]
To test these kinds of PRs, you must pull down the changes of the corresponding boilerplate PRs and make sure everything works as expected with the changed instructions.  I do not think that happened here because if you pull down the boilerplate PR associated with the changes for the Advanced Node challenges, the first thing you will notice when running `npm start` is an error message appearing in the Node console and the website (see below).

image

There was a good reason we did not preinstall pug originally, so users did not encounter this message and assume there was something wrong from the beginning of the challenge.  I am fine leaving it this way, but the instructions should be changed to explain it is normal to see the message until the correct changes have been made as stated in the first challenge's instructions.

**Comment by ieahleen** [comment]
the PR to the boilerplate is to be merged when the site is deployed, otherwise there is a mismatch between boilerplate and instructions

**Comment by RandellDawson** [comment]
@ieahleen You currently still have a mismatch because these changes do not reflect the current `master` branch for at least the Advanced Node challenges. This PR should not have been merged at all until the corresponding boilerplate PRs were approved.  Then, when the commits on this PR hit production, then those approved boilerplates would need to be merged.  That did not happen here, which is why there is a disconnect on `/learn`.  As it stands, I would not approve the Advanced Node boilerplate PR because of the error message showing until a change is made to the `/learn` instructions.

**Comment by ieahleen** [comment]
Oh, yes, that makes sense

**Pull request merged**
