### PR TITLE
fix(curriculum): remove extraneous word from instructions

### PR DESCRIPTION
**Pull request by bbsmooth**
Checklist:

- [x] I have read [freeCodeCamp's contribution guidelines](https://contribute.freecodecamp.org).
- [x] My pull request has a descriptive title (not a vague title like `Update index.md`)
- [x] My pull request targets the `main` branch of freeCodeCamp.
- [x] I have tested these changes locally on my machine.

Closes #XXXXX

### CODE REVIEW

**Review by gikf — APPROVED** [review]
LGTM :+1:

**Review by jdwilkin4 — APPROVED** [review]
LGTM! 👍

**Comment by gikf** [comment]
Hi @bbsmooth. Congrats on your first pull request (PR)! 🎉

Thank you for your contribution to the page! 👍
We are happy to accept these changes and look forward to future contributions. 📝

**Comment by bbsmooth** [comment]
Thanks @gikf, pleasure doing business with you.

**Pull request merged**
