### PR TITLE
fix(tools): update failing tests on main

### PR DESCRIPTION
**Pull request by naomi-lgbt**
Checklist:

- [X] I have read and followed the [contribution guidelines](https://contribute.freecodecamp.org).
- [X] I have read and followed the [how to open a pull request guide](https://contribute.freecodecamp.org/#/how-to-open-a-pull-request).
- [X] My pull request targets the `main` branch of freeCodeCamp.
- [X] I have tested these changes either locally on my machine, or GitPod.

Tracing this issue back, discovered that some [optimisation changes to the fs.readFileSync](https://github.com/tschaub/mock-fs/issues/377) broke the ability for `mock-fs` to mock the file system correctly.

The workaround for this, until the upstream issue is fixed, is to not pass the `utf-8` argument, but to instead call `toString('utf-8')` on the returned Buffer.

This also meant that `matter.read()` was unusable, as it appears to default to passing the parameter. Instead, we have to read the file separately, and pass the contents to `matter()` directly.

image

Tools tests are now all passing locally for me on my node 20 instance.

### CODE REVIEW

**Review by raisedadead — APPROVED** [review]

**Comment by gikf** [comment]
These work on `20.7`. `20.8` appears to make more changes that `mock-fs` doesn't like.

**Review by huyenltnguyen — APPROVED** [review]
LGTM 👍 

I think we should create an issue to track the removal of the workaround though.

**Comment by naomi-lgbt** [comment]
image

Okay I threw out the mock-fs and just wrote to the file system (and cleaned it up after) directly. That gets these passing locally on Node 20.8.1 finally.

**Review by huyenltnguyen — COMMENTED** [review]
Could we revert the `.toString('utf-8')` workaround then, or do we still need it?

**Pull request merged**
