### PR TITLE
Added example, explanation and solution to "Use RGB to Mix Colors"

### PR DESCRIPTION
**Pull request by KevTrang00**
- [x] I have read [freeCodeCamp's contribution guidelines](https://github.com/freeCodeCamp/freeCodeCamp/blob/master/CONTRIBUTING.md).
- [x] My pull request has a descriptive title (not a vague title like `Update index.md`)
- [x] My pull request targets the `master` branch of freeCodeCamp.
- [x] None of my changes are plagiarized from another source without proper attribution.
- [x] My article does not contain shortened URLs or affiliate links.

Closes #XXXXX

### CODE REVIEW

**Comment by RandellDawson** [comment]
Hi @KevinatorTrainer5 

Not sure if you know, but you only need to surround the key words with a single back ticks instead of 3 backticks as you are doing in your code.  The guide articles use Github markdown, so just surround the key words single backticks.

Thanks.

**Comment by KevinatorTrainer5** [comment]
I didnt know that you could use single backticks for keywords, because its my first time using backticks for coding purposes.  So I just changed the backticks immediately as suggested.

**Comment by RandellDawson** [comment]
@KevinatorTrainer5 The single backticks look much cleaner.  The only other thing I see is you are not consistent with your code indentation for the `style` elements. 

Under the Problem section you have:
```
<style>
  .red-text {
    color: #000000;
  }
  .orchid-text {
    color: #000000;
  }
  .sienna-text {
    color: #000000;
  }
  .blue-text {
    color: #000000;
  }
</style>
```
and then under the Before an After examples of the Example section, you have:
```
<style>
.ClassName {
  color: #000000;
}
</style>
```

**Comment by KevinatorTrainer5** [comment]
I'll fix that right away in that case.

**Comment by RandellDawson** [comment]
OK, that looks better.  One last thing and it is the most important.  Make sure you post the full code for the solution.  The user should be able to copy/paste what you show in the solution and pass the tests.

You left out:
```
<h1 class="red-text">I am red!</h1>

<h1 class="orchid-text">I am orchid!</h1>

<h1 class="sienna-text">I am sienna!</h1>

<h1 class="blue-text">I am blue!</h1>
```

FYI - There is an earlier PR which adds some examples, but does not break the solution down like you do.  I am going to go ahead and merge it before yours and then deal with any merge conflict which shows up on your PR.

**Comment by KevinatorTrainer5** [comment]
Ahhh I see now. I'll remember the feedback after I just made my first pull request for the FreeCodeCamp solutions. Thanks a lot!!

**Comment by RandellDawson** [comment]
Thank you for your contribution to the page! 👍
We're happy to accept these changes, and look forward to future contributions. 🎉

**Pull request merged**
