### PR TITLE
feat(client): style code block scrollbar

### PR DESCRIPTION
**Pull request by naomi-lgbt**
Checklist:

- [X] I have read [freeCodeCamp's contribution guidelines](https://contribute.freecodecamp.org).
- [X] My pull request has a descriptive title (not a vague title like `Update index.md`)
- [X] My pull request targets the `main` branch of freeCodeCamp.
- [X] All the files I changed are in the same world language, for example: only English changes, or only Chinese changes, etc.

Closes #XXXXX

Tweaking the CSS on the horizontal scrollbar for video challenge answer blocks, to make the scrollbar a little less obtrusive.

@ahmadabdolsaheb feel free to close if you have a better approach 🙂 

Example on:
Chrome  - Firefox - Edge (I can't test on safari 🙁 )

image

### CODE REVIEW

**Review by ojeytonwilliams — DISMISSED** [review]
These scrollbars look good. One thing I thought might be nice is if they had a 1px gap above them, but I couldn't figure out how to achieve that with CSS.

Very much a minor thing, but if you a) know how and b) agree, we could try it.

Regardless, I think this can go in pending Ahmad's input.

**Comment by moT01** [comment]
Just an observation from the image - is there any way to combine the scroll bars into one so the whole block just has one at the bottom instead of three individual scroll bars?

**Comment by nhcarrigan** [comment]
I can make the entire thing scrollable, but then the borders between the options don't cooperate at all. I can remove them, tho:

image

**Comment by moT01** [comment]
I definitely think I would prefer it like that. Five potential scroll bars seems obnoxious. Although, I don't know what it would look like with larger code blocks as options or something. Perhaps the borders were necessary. I think I would vote for the single scroll bar regardless.

**Comment by ahmadabdolsaheb** [comment]
Thanks for working on this fix. Although one scroll for all looks cleaner, it would prefer individual scrollbars, and we could apply this convention for all code blocks. How about changing the styles a bit to make the scroll bar more obvious? 

image

**Comment by nhcarrigan** [comment]
image

A slightly more aggressive scrollbar.

Firefox, unfortunately, offers less styling. I can't change the thickness directly, only choose between `thin` and `auto`, and `auto` makes the arrow buttons visible.

image

**Review by ahmaxed — APPROVED** [review]

**Comment by ahmadabdolsaheb** [comment]
It could be a little shorter, but either way works for me. That being said, we should probably make all scrollers in additional to the editor scroller look the same throughout the platform.

**Review by ojeytonwilliams — APPROVED** [review]
LGTM :+1: 

This looks way nicer than what's currently live and we can revisit the styling when we unify them across the platform.

**Pull request merged**
