### PR TITLE
fix(curriculum): removed marginBottom, 'auto' assertion

### LINKED ISSUE #46598: Not explicit test in step 12 of Penguin project of new RWD
### Describe the Issue

The description says: Use the `margin `property to horizontally center the `.penguin` element, and set the `margin-top` to `75px`.

Maybe we should explicitly say in the description that the test requires that `margin-bottom: auto` or change the test.

### Affected Page

https://github.com/freeCodeCamp/freeCodeCamp/blob/main/curriculum/challenges/english/14-responsive-web-design-22/learn-css-transforms-by-building-a-penguin/619699c10a0f6e11591d73c4.md

### Your code

 The code
`margin: 75px auto 0;`
or
```
margin-top: 75px;
margin-left: auto;
margin-right: auto;
```
does not pass because the test requires that also `margin-bottom` is set to `auto`. So the accepted code is `margin: 75px auto auto;`.

### Expected behavior

From reading the description I understand that the requirements involve `margin-left` and `margin-right` (value of `auto`) and `margin-top` (value of `75px`). I didn't expect to need also` margin-bottom: auto`.

### Screenshots

_No response_

### System

- Device: [e.g. iPhone 6, Laptop]
- OS: [e.g. iOS 14, Windows 10, Ubuntu 20.04]
- Browser: [e.g. Chrome, Safari]
- Version: [e.g. 22]

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by Sherelle-S**
Checklist:

- [x] I have read [freeCodeCamp's contribution guidelines](https://contribute.freecodecamp.org).
- [x] My pull request has a descriptive title (not a vague title like `Update index.md`)
- [x] My pull request targets the `main` branch of freeCodeCamp.
- [x] I have tested these changes either locally on my machine, or GitPod.

Closes #46598

### CODE REVIEW

**Comment by Sboonny** [comment]
Hey @Sherelle-S 

Thank you for opening this pull request.

This is a standard message notifying you that we've reviewed your pull request and have decided not to merge it. We would welcome future pull requests from you.

Thank you and happy coding.

**Comment by Sboonny** [comment]
While talking to another moderator, I noticed in the description, it mentions horizontally center requirement. So your changes may be welcomed. 

For this, my earlier comment is invalid. I am sorry for wasting your time @Sherelle-S, and I am reopening the pull request.

**Comment by ieahleen** [comment]
Thank you for your PR, before we can accept it, please go through the checklist, and link the correct issue https://github.com/freeCodeCamp/freeCodeCamp/issues/46598

**Comment by Sherelle-S** [comment]
I think I pressed the button without linking the issue. Sorry, very new to this

**Comment by Sboonny** [comment]
@Sherelle-S no worries, take your time. 

> I think I pressed the button without linking the issue. Sorry, very new to this

**Comment by ieahleen** [comment]
@Sherelle-S please edit the description of this PR to link the correct issue :)

**Comment by Sboonny** [comment]
Hey @Sherelle-S, for you to edit the description, you can click on the three dots icon. Then click edit

image

After you had clicked edit, changing the description is possible, and you can change the issue number

image

**Comment by Sherelle-S** [comment]
Thank you for you patience and guidance guys. Definitely a learning experience issues number updated!

**Review by Sboonny — APPROVED** [review]
#### :sparkles: :tada: **AWESOME!** :tada: :sparkles:

 Hi @Sherelle-S, thanks for this pull request and for contributing to the code-base for the first time. We are looking forward to more contributions from you in the future.

 Cheers & happy contributing!

**Review by gikf — APPROVED** [review]
Looks good :+1: 

Note for future - it is recommended to make changes on a separate branch, than the `main` branch. See more about it in point 3 at https://contribute.freecodecamp.org/#/how-to-setup-freecodecamp-locally?id=making-changes-locally.

**Pull request merged**
