### PR TITLE
fix(curriculum): ensure function is passed as argument

### LINKED ISSUE #53091: (Javascript Course) Learn Form Validation by Building a Calorie Counter, Step 50 - test accepts wrong answer
### Describe the Issue

The test asks to create an event listener, and pass addEntry function without directly calling addEntry. However, when I tried to call the addEntry directly, this test accepted the wrong answer

### Affected Page

https://www.freecodecamp.org/learn/javascript-algorithms-and-data-structures-v8/learn-form-validation-by-building-a-calorie-counter/step-50

### Your code

```
Right Answer
addEntryButton.addEventListener("click",**addEntry**);

Wrong Answer
addEntryButton.addEventListener("click",**addEntry()**);

```

### Expected behavior

The is not suppose to let me pass.

### Screenshots

_No response_

### System

- Device: [e.g. iPad Pro]
- OS: [e.g. iOS 15]
- Browser: [e.g. Safari]
- Version: [e.g. 22]

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by jayanth920**
Checklist:

- [x] I have read and followed the [contribution guidelines](https://contribute.freecodecamp.org).
- [x] I have read and followed the [how to open a pull request guide](https://contribute.freecodecamp.org/#/how-to-open-a-pull-request).
- [x] My pull request targets the `main` branch of freeCodeCamp.
- [x] I have tested these changes either locally on my machine, or GitPod.

Closes #53091

Changed the regex to only accept : addEntryButton.addEventListener("click",**addEntry**);
and not: addEntryButton.addEventListener("click",**addEntry()**);

### CODE REVIEW

**Review by huyenltnguyen — COMMENTED** [review]
@jayanth920 Thanks for the PR. 

We don't accept changes to non-English files, so please help remove them.

And just a small note: Next time, please wait for us to triage the issue before creating a PR. Only issues that are triaged and labeled with `first timers only` or `help wanted` are open to contribution.

**Comment by jayanth920** [comment]
@huyenltnguyen  thx for the reply. I actually dont know how to remove them now, i'll just make a new one then?.

**Comment by jayanth920** [comment]
]

> You could either revert each commit that includes non-English file, or reset the branch to `main` and cherry-pick the commit that changes the English file.
> 
> If you go with the latter:
> 
> * To reset the branch to fCC's `main`, run:
>   ```shell
>   git reset --hard upstream/main
>   ```
> * To cherry-pick the English file change, run:
>   ```shell
>   git cherry-pick f08ab8e
>   ```
> 
> Then you'll need to `git push -f` to force-push the changes.

yep doing it right away

**Comment by jayanth920** [comment]
@huyenltnguyen I reverted the code in all the other languages except English.

**Review by huyenltnguyen — APPROVED** [review]

**Review by gikf — APPROVED** [review]
LGTM :+1:

**Pull request merged**
