### PR TITLE
feat(rechallenge): Retool challenge framework

### LINKED ISSUE #13325: Berkeley's refactor of how files are built.
This will enable us to asynchronously load libraries as necessary. @berkeleytrue thinks he'll have something to demo by Friday Feb 17.

### PR DESCRIPTION
**Pull request by BerkeleyTrue**
closes #13325

### CODE REVIEW

**Comment by mmmhmhmn** [comment]
Meh fluckt

**Comment by QuincyLarson** [comment]
@BerkeleyTrue do you know why Travis is failing on this? I'm unfamiliar with the error it's throwing.

```
  6:10  error  updateContents not found in '../../common/utils/polyvinyl'  import/named
```

**Comment by QuincyLarson** [comment]
@BerkeleyTrue Is this ready for QA? (It has the QA label.) If so, give me some QA instructions or a testplan and I'll get to it. Eager to test this out :)

**Comment by BerkeleyTrue** [comment]
@QuincyLarson Do you remember which challenges where not working for you?

**Comment by BerkeleyTrue** [comment]
note: `</code>` shows up in output channel

**Comment by BerkeleyTrue** [comment]
Seems like the user code in string that is used by some tests is not updated with the code written to the iframe test window. Investigating...

**Comment by QuincyLarson** [comment]
Note that back end challenges are not yet working but everything else seems to be.

**Pull request merged**
