### PR TITLE
Fix: replace hardGoTo with links where possible

### PR DESCRIPTION
**Pull request by ojeytonwilliams**
It mostly is redundant, though there's still one case were we use it programmatically. `ShowSettings` still uses it because it calls it to go to /signin.

Also, I've added a couple of commits that fix some test warning's that have been bugging me for a while!

edit: I updated this comment to consolidate the discussion

### CODE REVIEW

**Comment by ojeytonwilliams** [comment]
Actually, we don't need it in most places.  There's still one case were we use it programmatically.

**Comment by raisedadead** [comment]
> There's still one case were we use it programmatically.

Elaborate? And do you want me to keep the commits or squash this.

**Comment by ojeytonwilliams** [comment]
Sorry, that was a bit cryptic.  `ShowSettings` still uses it because it calls it to go to `/signin`.

I'll reorganise the commits, then it shouldn't need squashing.

**Comment by ahmadabdolsaheb** [comment]
Let's wait on this until /donatioin paypal redirection is out of the door.

**Comment by ojeytonwilliams** [comment]
Sure, could you unblock it when that's done?

**Comment by ahmadabdolsaheb** [comment]
Sure.

**Comment by raisedadead** [comment]
The reason for the block is not very clear? Is it just merge conflicts?

**Comment by raisedadead** [comment]
It was my understanding that:

> I'll reorganise the commits, then it shouldn't need squashing.

@ahmadabdolsaheb 

Can you rebase this instead of merging master on this PR branch, if you are working on it.

**Review by ahmaxed — APPROVED** [review]

**Pull request merged**
