### PR TITLE
Clarified instructions for Pairwise algorithm

### LINKED ISSUE #16800: Pairwise Language Clarification
#### Challenge Name

Pairwise: https://www.freecodecamp.org/challenges/pairwise

#### Issue Description

The phrasing of the rule: **"If multiple pairs are possible that have the same numeric elements but different indices, return the smallest sum of indices. Once an element has been used, it cannot be reused to pair with another."** could be interpreted multiple ways, for example:

1) If you have multiple indices a, b, c whose values are equal and any could pair with another indice y to reach arg, create only one pair utilizing y, and choose indice a, b, or c based on which indice pair's sum is the smallest.
2) Only keep one pair if you find multiple pairs with matching numerical values that all came from unique indices. Determine which pair to keep based on which pair's indice sum is smallest.

In both interpretations, it's applying the test of sum(indices) to multiple possible pairs with equal numeric elements but different indices.

The first interpretation is the intended interpretation given that it expects [0, 0, 0, 0, 1, 1] to return 10. Interpreted the second way that same array and arg would return 4. You would create two pairs of [0,1] (given elements can't be reused) and prune the pair whose indices equal 6.

I would suggest either including an example or new language to clarify that "It means that if there are two different ways to make a pair, then use the combination with the smallest index.", as ArielLeslie so put it so well on the forums.

Maybe: "If a single indice could be paired with multiple other indices containing the same numeric elements, return the pair with the smallest sum of indices. For example, pairwise([1, 1, 2], 3) creates a pair with 2 using the 1 at indice 0 rather than the 1 at indice 1, because 0+2 < 1+2. Once an element has been used, it cannot be reused to pair with another."

#### Browser Information

* Browser Name, Version: Chrome, Version 64.0.3282.186 (Official Build) (64-bit)
* Operating System: Windows 10
* Mobile, Desktop, or Tablet: Desktop

#### Your Code

```js



```

### PR DESCRIPTION
**Pull request by willimsbw**
Added an example to further clarify the directions in the "Pairwise" algorithm, per issue #16800 https://github.com/freeCodeCamp/freeCodeCamp/issues/16800

#### Pre-Submission Checklist

- [X] Your pull request targets the `staging` branch of freeCodeCamp.
- [X] Branch starts with either `fix/`, `feature/`, or `translate/` (e.g. `fix/signin-issue`)
- [X] You have only one commit (if not, [squash](http://forum.freecodecamp.org/t/how-to-squash-multiple-commits-into-one-with-git/13231) them into one commit).
- [x] All new and existing tests pass the command `npm test`. Use `git commit --amend` to amend any fixes.

#### Type of Change

- [X] Small bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds new functionality)
- [ ] Breaking change (fix or feature that would change existing functionality)
- [ ] Add new translation (feature adding new translations)

#### Checklist:

- [ ] Tested changes locally.
- [ ] Addressed currently open issue (replace XXXXX with an issue no in next line)

Closes #16800

#### Description

Added an example to further clarify the desired behavior for the Pairwise algorithm challenge

### CODE REVIEW

**Comment by mstellaluna** [comment]
I am currently working on this PR

**Review by mstellaluna — CHANGES_REQUESTED** [review]
The wording for the second example should be changed from "For example" to "Another example" as two consecutive "For example" isn't used in English text.

**Comment by mstellaluna** [comment]
@willimsbw Hello. I have a small suggestion for the changed text. There are two consecutive phrases that start with "For example", this isn't normally done in English text. Is it possible to change the following: 

`For example, pairwise([1, 1, 2], 3) creates a pair [2, 1] using the 1 at indice 0 rather than the 1 at indice 1, because 0+2 < 1+2.`

to 

`For instance, pairwise([1, 1, 2], 3) creates a pair [2, 1] using the 1 at indice 0 rather than the 1 at indice 1, because 0+2 < 1+2..`

Otherwise the PR is fine.

**Comment by willimsbw** [comment]
Not I problem! I've made the change. Let me know if there's anything else needed.

**Review by mstellaluna — APPROVED** [review]

**Comment by mstellaluna** [comment]
@willimsbw I will be approving this PR. Thank you for your contribution. Happy Coding !

**Pull request merged**
