### PR TITLE
fix(curriculum): add test case to check country code

### LINKED ISSUE #45080: JS Curriculum: missing test case in Telephone Number Validator challenge
## Affected page

https://www.freecodecamp.org/learn/javascript-algorithms-and-data-structures/javascript-algorithms-and-data-structures-projects/telephone-number-validator
## Your code

```
// example of buggy function that passes the challenge
function telephoneCheck(str) {
  return /^(1)*(\s)*(?:\d\d\d|\(\d\d\d\))([-|\s])*\d\d\d([-|\s])*\d\d\d\d$/.test(str);
}

```

## Expected behavior

The code above shouldn't pass the challenge.

## Additional context

In the challenge, it is required to confirm that the country code is 1, where it is provided.

Please add a test case where the country code is made of multiple 1s, for example:

```
//test 
console.log(telephoneCheck("11 555-555-5555")); // should return false


```

### PR DESCRIPTION
**Pull request by poonkuzhali**
Checklist:

- [x] I have read [freeCodeCamp's contribution guidelines](https://contribute.freecodecamp.org).
- [x] My pull request has a descriptive title (not a vague title like `Update index.md`)
- [x] My pull request targets the `main` branch of freeCodeCamp.
- [x] I have tested these changes either locally on my machine, or GitPod.

Closes #45080

### CODE REVIEW

**Review by gikf — APPROVED** [review]
LGTM :+1: 

Code from issue doesn't pass anymore.

---

Note for future - it is recommended to make changes on a separate branch, than the `main` branch. See more about it in point 3 at https://contribute.freecodecamp.org/#/how-to-setup-freecodecamp-locally?id=making-changes-locally.

**Comment by wbenarto** [comment]
PR54100

Checked through Gitlab and issue code still returns true on the 11 country test case. Please see image attached. 

//Issue:
function telephoneCheck(str) {
  return /^(1)*(\s)*(?:\d\d\d|\(\d\d\d\))([-|\s])*\d\d\d([-|\s])*\d\d\d\d$/.test(str);
}

//test 
console.log(telephoneCheck("11 555-555-5555")); // should return false

Fix still returns true

**Comment by gikf** [comment]
@wbenarto we cannot change that this function implementation returns `true` for the `11 555-555-5555`. However the additional test is expecting the function to return `false` for it. That makes code from issue not have all tests passed.

**Comment by wbenarto** [comment]
@gikf Thanks for the clarification. 

This LGTM👍

**Review by wbenarto — APPROVED** [review]

**Review by wbenarto — APPROVED** [review]

**Review by naomi-lgbt — APPROVED** [review]
Looks good to me!

**Comment by nhcarrigan** [comment]
Thank you for your contribution to the page! 👍
We are happy to accept these changes and look forward to future contributions. 🎉

**Pull request merged**
