### PR TITLE
update pull request template with convenient way to test

### PR DESCRIPTION
**Pull request by crashuniverse**
#### Pre-Submission Checklist

- [x] Your pull request targets the `staging` branch of FreeCodeCamp.
- [x] Branch starts with either `fix/`, `feature/`, or `translate/` (e.g. `fix/signin-issue`)
- [x] You have only one commit (if not, [squash](https://github.com/FreeCodeCamp/FreeCodeCamp/wiki/git-rebase#squashing-multiple-commits-into-one) them into one commit).
- [x] All new and existing tests pass the command `npm run test-challenges`. Use `git commit --amend` to amend any fixes.
#### Type of Change

- [x] Small bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds new functionality)
- [ ] Breaking change (fix or feature that would change existing functionality)
- [ ] Add new translation (feature adding new translations)
#### Checklist:

- [x] Tested changes locally.
- [ ] Closes currently open issue (replace XXXX with an issue no): Closes #XXXX (None)
#### Description

We have 370+ contributors and every time they make a contribution they can actually just run `npm test` instead of `npm run test-challenges`. This is interchangeable because of `"test": "npm run test-challenges"` in npm scripts section. So with this change from now on, PR template would recommend to just run `npm test`. Also the deletion of last line in file as a change is in agreement with `.editorconfig` file.

### CODE REVIEW

**Comment by crashuniverse** [comment]
I just read in [Contributing.md](https://github.com/FreeCodeCamp/FreeCodeCamp/blob/staging/CONTRIBUTING.md):
5. When you are ready to share your code, run the test suite `npm test` and ensure all tests pass.  For Windows contributors, skip the jsonlint pretest run by using `npm run test-challenges`, as jsonlint will always fail on Windows, given the wildcard parameters.

So that makes the PR bad because it would lead to failing on Windows platform.

**Comment by crashuniverse** [comment]
I closed it in error thinking `npm test` would not work on windows, and so this PR still looks valid to me. I don't want to do the same thing again in a different PR number. Thanks.

**Comment by Bouncey** [comment]
`npm test` works for me on Ubuntu, It's slower, but it works.

**Comment by atjonathan** [comment]
@crashuniverse, does `npm test` work on Windows? I didn't think it did...

**Comment by crashuniverse** [comment]
@atjonathan Good point, I never tested it on Windows. I need more time to get to a windows machine to confirm on this.

**Comment by Bouncey** [comment]
I will test this on a Windows machine later today

**Comment by atjonathan** [comment]
I can confirm `npm test` doesn't work on Windows.

**Pull request closed without merging**
