### PR TITLE
Add "personal Items" to category list

### PR DESCRIPTION
**Pull request by Cowmman1**
- [ ] I have read [freeCodeCamp's contribution guidelines](https://github.com/freeCodeCamp/freeCodeCamp/blob/master/CONTRIBUTING.md).
- [ ] My pull request has a descriptive title (not a vague title like `Update index.md`)
- [ ] My pull request targets the `master` branch of freeCodeCamp.
- [ ] None of my changes are plagiarized from another source without proper attribution.
- [ ] My article does not contain shortened URLs or affiliate links.

If your pull request closes a GitHub issue, replace the XXXXX below with the issue number.

Closes #XXXXX

### CODE REVIEW

**Comment by artoodeeto** [comment]
@RandellDawson hello. @huyenltnguyen  and I are still fixing it. we're trying to figure out the Jquery logic. what you mean tested? if you're saying that we're we run the changes locally we did and its running.

**Comment by RandellDawson** [comment]
If you need any help, I can assist.  I had actually started working on that project about 3 weeks ago, before I knew you all were working on it.

**Comment by artoodeeto** [comment]
oh. yea we made a gitter group just for this. i could i add you there and we could talk. @huyenltnguyen is the one initiating it. im just following her. but we are done with the UI. the logic to calculate and d3 were still doing it.

**Comment by huyenltnguyen** [comment]
Hi @RandellDawson, first of all, thank you for your help on every fCC-related thing! 😄 

@artoodeeto and I are still slowly working on converting the Coding Bootcamp Cost Calculator app to React. I'm curious on your progress and wondering if we could collaborate to help complete the task sooner. I will DM you in Gitter later today to give you a summary of what we have done so far.

Regarding the change in this PR, I think it is unnecessary and irrelevant to the CBCC app, and you were right on closing it.

Thank you again.

**Comment by RandellDawson** [comment]
@huyenltnguyen Looking forward to your summary.  So I am good to close this PR?

**Comment by huyenltnguyen** [comment]
@RandellDawson Yes, please close the PR.
Thank you for your help! I will definitely get back to you on Gitter asap.

**Pull request closed without merging**
