### PR TITLE
Update index.md

### PR DESCRIPTION
**Pull request by codegrinders**
added period to end of row 14

- [ ] I have read [freeCodeCamp's contribution guidelines](https://github.com/freeCodeCamp/freeCodeCamp/blob/master/CONTRIBUTING.md).
- [ ] My pull request has a descriptive title (not a vague title like `Update index.md`)
- [ ] My pull request targets the `master` branch of freeCodeCamp.
- [ ] None of my changes are plagiarized from another source without proper attribution.
- [ ] My article does not contain shortened URLs or affiliate links.

If your pull request closes a GitHub issue, replace the XXXXX below with the issue number.

Closes #XXXXX

### CODE REVIEW

**Comment by codegrinders** [comment]
Hello,

I would like some clarification on this based on the email and article
received from Mr. Larson. It states if you are new to code or don't know a
language. I am in that boat and right now having just starting to learn
HTML so grammar changes are what I can provide based on the limited
knowledge I have. There was no mention of any time, what you pull and the
article states "In this quick article, I’ll show you how you can get a
Hacktoberfest shirt — even if you have never coded before. The bottom line
is this: if you can open 5 pull requests by October 31.. "

Should I do one per day? Or should I not even participate with my knowledge
level being at zero?

Thanks

**Comment by RandellDawson** [comment]
The reason your PR was marked invalid was because you failed to check the 5 checkboxes and the title of your PR was vague "update index.md".  We are receiving a massive number of PRs at the moment and many contributors are not making significant contributions (i.e. adding a space where not necessary or adding garbage).  These PRs share the same characteristics.  They do not have any of the checkboxes checked and the title of the PR is "update index.md".  Your PR adds a period to a sentence which is appreciated, so make your title more descriptive of the change and check off your checkboxes.  I have reopened the PR to allow you to do that.  Reply back once you have done this.

In general, you are correct that you can contribute by helping with grammar without knowing how to code yet.

**Comment by codegrinders** [comment]
You can do these pull requests at whatever speed you feel comfortable, as
long as you open all 5 by the end of the month.

- Quincy Larson

Teacher at https://www.freecodecamp.org
I share useful things on Twitter at https://www.twitter.com/ossia

**Comment by RandellDawson** [comment]
You still have not modified the title of this PR to reflect what changes you have made.

**Comment by codegrinders** [comment]
Please disregard my updates to Github.

Thanks

**Pull request closed without merging**
