### PR TITLE
fix(curriculum): update "SVG canvas" to "SVG" in D3 course

### LINKED ISSUE #49266: d3 step uses the phrase 'SVG canvas' half way through the course without any explanation
### Describe the Issue

About halfway through the D3 (data visualization with D3) course, we see the phrase "SVG canvas" for the first time on this page: https://www.freecodecamp.org/learn/data-visualization/data-visualization-with-d3/add-labels-to-d3-elements

However prior to this point the course only used the phrase 'SVG area' in reference to the space that the SVG takes up on the screen. No explanation was given in the step for what 'SVG canvas' is which was confusing to me as a translator (why a different word than before?) and as a Java developer who sees 'canvas' as a class for drawing. I did a quick google search for 'svg canvas' and all I got were results suggesting that these are different things.

I propose therefore that all occurrences of 'SVG canvas' be replaced with 'SVG area' in this step and following steps (it is mentioned again later several times). 

### Affected Page

https://www.freecodecamp.org/learn/data-visualization/data-visualization-with-d3/add-labels-to-d3-elements

### Your code

```

```

### Expected behavior

replace all occurrences of 'SVG canvas' with 'SVG area' in the D3 curriculum

### Screenshots

_No response_

### System

N/A

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by al6862**
Checklist:

- [x] I have read and followed the [contribution guidelines](https://contribute.freecodecamp.org).
- [x] I have read and followed the [how to open a pull request guide](https://contribute.freecodecamp.org/#/how-to-open-a-pull-request).
- [x] My pull request targets the `main` branch of freeCodeCamp.
- [x] I have tested these changes either locally on my machine, or GitPod.

Closes #49266

### CODE REVIEW

**Comment by al6862** [comment]
While changing "SVG canvas" to "SVG" in use-dynamic-scales.md, I changed a comment. It seems like I then had to change the corresponding comment in dictionaries/english/comments.json and the corresponding comment in all language translations of use-dynamic-scales.md

Should I just remove the changes in the language translations of use-dynamic-scales.md? This seems to then cause some check failures for localization.

**Comment by Sboonny** [comment]
Open it for review after removing the changes in the other languages, I have moved it to draft to reduce the maintainance workload

**Comment by moT01** [comment]
I updated the branch to re-run the tests.

**Comment by lynxlynxlynx** [comment]
Please update your branch with the latest changes to master, so it becomes mergeable.  You now have 2 other competitors:  https://github.com/freeCodeCamp/freeCodeCamp/pull/49686, https://github.com/freeCodeCamp/freeCodeCamp/pull/49688.

**Comment by raisedadead** [comment]
Hi @al6862 

Thanks for taking the time to contribute. We are sorry that we should have been more explicit about the instructions in the original thread – we are working on updating some of our testing to help handle scenarios like this.

Thanks for taking the time to contribute; we look forward to more PRs in the future.

**Comment by raisedadead** [comment]
Hi @lynxlynxlynx 

Thanks for the review. I have updated the PR, please give it one more look and merge it when you are happy. 

Thanks for your contribution :)

**Review by lynxlynxlynx — APPROVED** [review]
LGTM, let's go!

**Review by Sboonny — APPROVED** [review]
#### :sparkles: :tada: **AWESOME!** :tada: :sparkles:

 Hi @al6862, thanks for this pull request and for contributing to the code-base for the first time. We are looking forward to more contributions from you in the future.

 Cheers & happy contributing!

**Pull request merged**
