### PR TITLE
fix(curriculum): redundant initial newline in Pyramid Generator output

### LINKED ISSUE #56143: Avoid Initial Blank Line in Pyramid Generator Output
### Describe the Issue

In the current implementation of the pyramid generator coding challenge, the output starts with an unnecessary blank line due to the way newline characters are added in the code. This can result in a confusing or unintended output format when generating the pyramid. The current code adds a newline character before each row, including the first row.

### Affected Page

https://www.freecodecamp.org/learn/javascript-algorithms-and-data-structures-v8/learn-introductory-javascript-by-building-a-pyramid-generator/step-43

### Your code

```
const character = "#";
const count = 8;
const rows = [];

for (let i = 0; i < count; i = i + 1) {
  rows.push(i);
}

let result = "";

for (const row of rows) {
  result = result + "\n" + row; // Adds a newline before each row, causing an initial blank line
  // Suggested improvement
 result = result + row + "\n";  // Short syntax: result += row + "\n"; 
}

console.log(result);


```

### Expected behavior

The expected behavior is for each row to be printed without a leading newline at the beginning of the output. Instead, the newline should be added after each row to separate the lines correctly. By adjusting the code to add newlines after each row, we can avoid the initial blank line, resulting in a cleaner and more readable output.

### Screenshots

image 

image   // Suggested improvement

### System

System
- Device: Laptop
- OS: Windows 10
- Browser: Chrome
- Version: 117.0.5938.132
- The issue was encountered in both the freeCodeCamp editor and the standalone Chrome browser.
- The output started with an unnecessary blank line in both environments.

### Additional context

This issue is more of a logical improvement rather than a critical bug. Adjusting the code to avoid adding a newline before the first row can help produce cleaner and more accurate output, aligning with typical pattern generation practices. The suggested improvement is to append the newline character after each row rather than before it.

### PR DESCRIPTION
**Pull request by AnarchistHoneybun**
Checklist:

- [x] I have read and followed the [contribution guidelines](https://contribute.freecodecamp.org).
- [x] I have read and followed the [how to open a pull request guide](https://contribute.freecodecamp.org/how-to-open-a-pull-request/).
- [x] My pull request targets the `main` branch of freeCodeCamp.
- [x] I have tested these changes either locally on my machine, or GitPod.

Closes #56143 

addition should be after the first value being appended, putting it earlier/in the middle adds an initial newline

### CODE REVIEW

**Comment by AnarchistHoneybun** [comment]
full disclosure, used a script to update the seed code for steps 44-118 but did go through all the diffs once before commit+push

**Comment by ilenia-magoni** [comment]
did you run the tests locally to check that none fail? did you also update the final solution in the file for step 118?

**Comment by AnarchistHoneybun** [comment]
Yes, the file for step-118 has both the seed code and solution code updated for the new concat order. 

yes, this is the pnpm thing I'm assuming. took a while to get it working but I didn't see any failures yes

**Comment by ilenia-magoni** [comment]
it looks like you did not run the curriculum tests after all, please try to do that before committing

**Comment by AnarchistHoneybun** [comment]
> it looks like you did not run the curriculum tests after all, please try to do that before committing

Sorry it probably didn't run properly on local, I did follow all commands as it said on the 'setting up for wsl' guide though.

All tests are passing now, I'm assuming this is also the required outcome when setting up locally? I'll try and go through the setup again

**Comment by ilenia-magoni** [comment]
This change will add an extra row at the bottom of the pyramid instead of the top. Are we fine with that? If yes, I believe the PR is good to go, after a last check for the wording

**Review by majestic-owl448 — APPROVED** [review]

**Review by Sembauke — APPROVED** [review]

**Pull request merged**
