### PR TITLE
translate\Translated Reclaim your back end development certificate in french

### LINKED ISSUE #7653: French translation of Claim Your Back End Development Certificate
- [x] Claim Your Back End Development Certificate

### PR DESCRIPTION
**Pull request by N0bl3**
closes #7653

### CODE REVIEW

**Comment by theflametrooper** [comment]
Please change FR to Fr

**Comment by N0bl3** [comment]
I changed it and squashed it in one commit. It seems that there is a conflict but i don"t understand why.

**Comment by theflametrooper** [comment]
Someone may have edited the code in between your fork and your pr and therefore you've got conflicts. On your fork on your 'N0bl3:translate/FR-Claim-Your-Back-End-Development-Certificate' branch, run `git remote add upstream https://github.com/FreeCodeCamp/FreeCodeCamp.git` `git pull upstream`. This should get the newest copy from freecodecamp's github.

**Comment by BerkeleyTrue** [comment]
@N0bl3 Can you try rebasing your PR against staging?

**Comment by N0bl3** [comment]
Do i have to resquash everything after?

**Comment by BerkeleyTrue** [comment]
@N0bl3 If you do a rebase you shouldn't have to.

```bash
git checkout staging
git pull
git checkout translate/FR-Claim-Your-Back-End-Development-Certificate
git rebase staging
```
If there are conflicts make sure you fix them, use `git add <path to changed file>` to add those changes to the staging area and then use `git rebase --continue` to continue 

This puts your commit on top of the latest version of staging, then you just need to 
```bash
git push -f
```
To force an overwrite of the history on your remote branch. That should update this PR and resolve the conflicts that are preventing this PR from being merged in.

**Comment by N0bl3** [comment]
I understand better. Thanks. This will be done.

**Comment by N0bl3** [comment]
I deleted the branch... I'm learning git and probably erase the content.... I'll have to submit a new one. Sorry for this

**Comment by N0bl3** [comment]
Is this ok now?

**Comment by theflametrooper** [comment]
Yeh seems to be! You need to get someone else who can read french to verify the translation before this is merged.

**Comment by BerkeleyTrue** [comment]
@N0bl3 You still ended up with an unnecessary merge in your commit history.

**Comment by N0bl3** [comment]
It ends exactly like before with a conflict but on my side there is none. I followed your hints and learnt a lot about git. However as i don't have any conflicts warnings on my side i can't do anything .

**Comment by N0bl3** [comment]
Looks like i found a way to do the trick! Sorry for the issue. ENjoy thetranslation :)
BTW when i translated bootstrap challenges we used nameLg and now we use titleLg when we should use the same everywhere.

**Comment by theflametrooper** [comment]
Awesome! Someone just needs to verify this translation.

**Comment by BerkeleyTrue** [comment]
@N0bl3 Thanks!

**Pull request merged**
