### PR TITLE
feat(i18n): enable more localised certs

### PR DESCRIPTION
**Pull request by ojeytonwilliams**
Now that https://github.com/freeCodeCamp/freeCodeCamp/pull/41512 is in, let's see if we can start deploying more certifications.

### CODE REVIEW

**Review by raisedadead — APPROVED** [review]
Deployments oncoming for more certifications in Chinese and Espanol! 🎉  :shipit:

**Comment by ojeytonwilliams** [comment]
@RafaelDavisH @miyaliu666 could you confirm that you're happy with all of these certs?  I thought they were okay, but checking on Crowdin, they're not 100% green right now.  Close, but not 100%.

**Comment by miyaliu666** [comment]
Several challenges should be updated since there're updates in English. We'll complete them tomorrow. Thank you!

**Comment by ojeytonwilliams** [comment]
No problem, I got there in the end :)

**Comment by raisedadead** [comment]
> Several challenges should be updated since there're updates in English. 

That should not stop us from going forward with the deployments correct?

**Comment by miyaliu666** [comment]
> > Several challenges should be updated since there're updates in English.
> 
> That should not stop us from going forward with the deployments correct?

I think so. Just a few challenges need to be updated.

**Comment by RafaelDavisH** [comment]
Great work 🥳. It only dropped 1%, but I got that back to 💯. 🎉 LATM!

**Comment by ojeytonwilliams** [comment]
Awesome, thanks @RafaelDavisH.  @nhcarrigan is now a good time to download the translations, since Rafa's got us to 100%?

**Comment by nhcarrigan** [comment]
Yep. I can go ahead and run the download job manually.

**Review by naomi-lgbt — APPROVED** [review]
Approving this to merge

**Pull request merged**
