### PR TITLE
Added Solution in Guide to while sass problem

### LINKED ISSUE #35088: Sass: Apply a Style Until a Condition is Met with @while: Add proper guide
**Describe your problem and how to reproduce it:**
The guide seems to be empty for this particular problem, as I am finding some problems are being faced by the amount of issues opened on this particular challenge.

**Add a Link to the page with the problem:**
[Inside Repo Link](https://github.com/freeCodeCamp/freeCodeCamp/blob/master/guide/english/certifications/front-end-libraries/sass/apply-a-style-until-a-condition-is-met-with-while/index.md)
[guide link](https://guide.freecodecamp.org/certifications/front-end-libraries/sass/apply-a-style-until-a-condition-is-met-with-while/)
**Tell us about your browser and operating system:**
* Browser Name: Not Browser Specific
* Browser Version: Not Browser Specific
* Operating System: Not OS Specific

**If possible, add a screenshot here (you can drag and drop, png, jpg, gif, etc. in this box):**
screenshot 2019-02-08 at 1 17 48 am

### PR DESCRIPTION
**Pull request by theNaut1lus**
Added proper Solution to the Guide for the problem Apply a Style Until a Condition is Met with `@while` , this is hopefully no longer a stub

- [x] I have read [freeCodeCamp's contribution guidelines](https://github.com/freeCodeCamp/freeCodeCamp/blob/master/CONTRIBUTING.md).
- [x] My pull request has a descriptive title (not a vague title like `Update index.md`)
- [x] My pull request targets the `master` branch of freeCodeCamp.
- [x] None of my changes are plagiarized from another source without proper attribution.
- [x] All the files I changed are in the same world language (for example: only English changes, or only Chinese changes, etc.)
- [x] My changes do not use shortened URLs or affiliate links.

Closes #35088

### CODE REVIEW

**Comment by RandellDawson** [comment]
@co16353sidak I made a couple of changes to your additions.  Also, can you fix that broken image (the warning)?

**Comment by co16353sidak** [comment]
Removed the links @RandellDawson

**Comment by RandellDawson** [comment]
@co16353sidak Actually, when I test it locally, the images show up, so it must be a glitch on the way the GitHub preview works.  Would you mind reverting back the last commit on your branch?  Sorry about any confusing I may have caused.

**Comment by co16353sidak** [comment]
No issues, although I was a little suspicious because many guides do still use the traditional notation along with all the linked images.
I will revert back.

**Comment by co16353sidak** [comment]
Hopefully everything now will be on track @RandellDawson

**Comment by RandellDawson** [comment]
Thank you for your contribution to the page! 👍
We're happy to accept these changes, and look forward to future contributions. 🎉

**Pull request merged**
