### PR TITLE
fix: update tests for data structures challenges

### PR DESCRIPTION
**Pull request by cazyw**
Fix the test strings to run the functions as the challenge currently passes without any code changes (all languages)
- Data Structures: Use .has and .size on an ES6 Set
- Data Structures: Use Spread and Notes for ES5 Set() Integration

- [X] I have read [freeCodeCamp's contribution guidelines](https://github.com/freeCodeCamp/freeCodeCamp/blob/master/CONTRIBUTING.md).
- [X] My pull request has a descriptive title (not a vague title like `Update index.md`)
- [X] My pull request targets the `master` branch of freeCodeCamp.
- [X] None of my changes are plagiarized from another source without proper attribution.
- [X] My article does not contain shortened URLs or affiliate links.

Is related to #17856

### CODE REVIEW

**Comment by QuincyLarson** [comment]
@cazyw Awesome!

@raisedadead can you verify all these tests look good?

**Comment by tbushman** [comment]
@cazyw All tests pass locally. Thank you for your patience and contributions.

**Comment by raisedadead** [comment]
Thanks  @tbushman @scissorsneedfoodtoo for the QA.

#### :sparkles: :sparkles: **AWESOME! LGTM.** :sparkles: :sparkles: 

Thanks @cazyw , for this pull request and contributing to the code-base for the first time.
We will be looking forward for more contributions in future.

Cheers and happy contributing!

**Comment by raisedadead** [comment]
@cazyw @tbushman I have removed some of your changes with 

https://github.com/freeCodeCamp/freeCodeCamp/pull/28296/commits/32e15e45e18d8a0c38a413ee33b3a01054390441

These were breaking the tests. Also we have updated our test output to render better failure results.

**Comment by cazyw** [comment]
> @cazyw @tbushman I have removed some of your changes with [32e15e4](https://github.com/freeCodeCamp/freeCodeCamp/commit/32e15e45e18d8a0c38a413ee33b3a01054390441)
> 
> These were breaking the tests. Also we have updated our test output to render better failure results.

@raisedadead oh :(    what was failing? Actually I've realised what was wrong

**Pull request merged**
