### PR TITLE
fix: remove unnecessary linting

### PR DESCRIPTION
**Pull request by ojeytonwilliams**
These checks don't really make sense, since they only look at the code (which isn't changing). Also, the full set of checks will be run when the PR is created (at the end of the action). That way we will get a more visible warning if something, somehow, goes wrong.

Checklist:

- [x] I have read and followed the [contribution guidelines](https://contribute.freecodecamp.org).
- [x] I have read and followed the [how to open a pull request guide](https://contribute.freecodecamp.org/#/how-to-open-a-pull-request).
- [x] My pull request targets the `main` branch of freeCodeCamp.
- [x] I have tested these changes either locally on my machine, or GitPod.

### CODE REVIEW

**Review by raisedadead — APPROVED** [review]
Merging this because of the blocker, but @naomi-lgbt can we be sure the downloads are not out of format for some reason? I hope that wasn't the need for this step in the first place.

**Comment by ojeytonwilliams** [comment]
> can we be sure the downloads are not out of format for some reason?

I don't think we should worry about it, honestly. We deliberately don't run prettier on the challenges so that we can format the code as we want and the linting doesn't care about the language. 

If we're concerned, we should run the node-js tests on more languages. That's the only meaningful automated testing we're doing, imo.

**Comment by ojeytonwilliams** [comment]
As far as I can see the goal is to try to catch problems with the translated .md files in CI. That's really all we're trying to do. Given that the full suite of tests run once the PR is created it follows that all these checks could possibly do is give us an early warning.

I don't think that's particularly useful, even if people saw the warning and the download was likely to generate warnings.

**Comment by naomi-lgbt** [comment]
Yes, I believe this was an artefact left from when we *did* lint the curriculum. The format step was merely intended to catch small issues (such as a trailing space at the end of the translation) that would have tripped the linter, allowing the action to fix them prior to creating a PR.

**Pull request merged**
