### PR TITLE
fix:reformat-npm-section

### PR DESCRIPTION
**Pull request by moT01**
I have gone through the "Managing Packages with Npm" section and done the following:
Reformat code to use `blockquote` tags where needed
Move any instructions to the instructions area of the file
Add `<code>` and other tags where needed.
Slightly reword some things/fix up grammar and punctuation to make it more concise and understandable.

I have gone through these pretty thoroughly - I hope it's not too many changes. 

- [x] I have read [freeCodeCamp's contribution guidelines](https://github.com/freeCodeCamp/freeCodeCamp/blob/master/CONTRIBUTING.md).
- [x] My pull request has a descriptive title (not a vague title like `Update index.md`)
- [x] My pull request targets the `master` branch of freeCodeCamp.
- [x] None of my changes are plagiarized from another source without proper attribution.
- [x] All the files I changed are in the same world language (for example: only English changes, or only Chinese changes, etc.)
- [x] My changes do not use shortened URLs or affiliate links.

Refer to https://github.com/freeCodeCamp/freeCodeCamp/issues/35413

### CODE REVIEW

**Comment by moT01** [comment]
No earlier PR's affect any of these files.

**Review by RandellDawson — APPROVED** [review]
LGTM.  There are a few places where a `<code>` element could be useful, but since the main purpose of this PR is to change `code` to `blockquote` where applicable, I am fine with these changes and a future PR can deal with adding the other changes if/when those individual challenges are reworded.

**Review by ezioda004 — APPROVED** [review]

**Comment by ezioda004** [comment]
Thanks @moT01 for fixing these up!

**Comment by moT01** [comment]
Thanks for reviewing it @RandellDawson @ezioda004

**Pull request merged**
