### PR TITLE
added details for crossfilter.js

### PR DESCRIPTION
**Pull request by bspai**
Added brief details and setup instructions for crossfilter.js

- [x] I have read [freeCodeCamp's contribution guidelines](https://github.com/freeCodeCamp/freeCodeCamp/blob/master/CONTRIBUTING.md).
- [x] My pull request has a descriptive title (not a vague title like `Update index.md`)
- [x] My pull request targets the `master` branch of freeCodeCamp.
- [x] None of my changes are plagiarized from another source without proper attribution.
- [x] My article does not contain shortened URLs or affiliate links.

### CODE REVIEW

**Comment by RandellDawson** [comment]
Closed and Reopened this PR to attempt to resolve a specific Travis build failure.

**Review by moT01 — DISMISSED** [review]
Links should follow markdown formatting described [here](https://github.com/freeCodeCamp/freeCodeCamp/blob/master/docs/style-guide-for-guide-articles.md#links)

**Review by RandellDawson — CHANGES_REQUESTED** [review]
How about showing an actual example of using crossfilter.js instead of just how to add the cdn to the script tag?

**Review by RandellDawson — DISMISSED** [review]

**Review by QuincyLarson — APPROVED** [review]
Even though this is a superficial article, it is still a net-positive, so I am merging it. Thanks, @bspai

**Pull request merged**
