### PR TITLE
fix(curriculum): replace tabs with spaces and remove spaces on empty lines

### LINKED ISSUE #47533: Standardize spacing in challenge files
### Describe the Issue

In the challenge files, some of the whitespace characters are tabs, others are spaces. It looks fine when you open a challenge:
Screen Shot 2022-09-16 at 9 43 18 AM

But when you create a forum post:
Screen Shot 2022-09-16 at 9 42 39 AM

The code isn't aligned. We should replace all the tabs with two spaces. This is likely present in many challenge files, not sure how many. One example is below.

### Affected Page

https://www.freecodecamp.org/learn/2022/responsive-web-design/learn-accessibility-by-building-a-quiz/step-25

### Expected behavior

Forum post code to be aligned.

### PR DESCRIPTION
**Pull request by moT01**
This replaces all the tabs in the english challenge files with two spaces. ~~While I was at it, I removed any spaces on empty lines - that's in a separate commit that I can revert if we just want to leave it.~~ reverted

Will this propagate to the i18n's through the crowdin process?

Checklist:

- [x] I have read [freeCodeCamp's contribution guidelines](https://contribute.freecodecamp.org).
- [x] My pull request has a descriptive title (not a vague title like `Update index.md`)
- [x] My pull request targets the `main` branch of freeCodeCamp.
- [x] I have tested these changes either locally on my machine, or GitPod.

Ref #47533

### CODE REVIEW

**Review by ojeytonwilliams — COMMENTED** [review]
You've just trimmed html, js and css, right?  A couple of empty spaces in md creates a line break, is all.

**Comment by moT01** [comment]
Empty spaces or empty lines?

The first commit replaces all the tabs in the English folder with two spaces. The second commit removes any spaces that are on their own line in the English folder - so the empty lines are still there. I am fine reverting that one if we want to simply this.

**Comment by ojeytonwilliams** [comment]
Empty spaces at the end of a line get interpreted as a line break.  If you've only changed code blocks inside challenge files, it's fine.

**Comment by moT01** [comment]
I just reverted it - keep it simpler.

**Review by Sboonny — APPROVED** [review]
LGTM 🎉, thank you for your contribution to the page! 👍.

**Comment by Sboonny** [comment]
I thought this is similar to an old PR, in which tabs were changed to spaces. Didn't notice the discussion on this issue was still going, sorry for early approval

**Review by ojeytonwilliams — APPROVED** [review]
LGTM :+1:

**Pull request merged**
