### PR TITLE
translation: Spanish

### PR DESCRIPTION
**Pull request by rodoviario**
Improved meaning in one sentence by removing words and using a shorter version.
Consolidates some of the use of third and first person

- [ ] I have read [freeCodeCamp's contribution guidelines](https://github.com/freeCodeCamp/freeCodeCamp/blob/master/CONTRIBUTING.md).
- [ ] My pull request has a descriptive title (not a vague title like `Update index.md`)
- [ ] My pull request targets the `master` branch of freeCodeCamp.
- [ ] None of my changes are plagiarized from another source without proper attribution.
- [ ] My article does not contain shortened URLs or affiliate links.

If your pull request closes a GitHub issue, replace the XXXXX below with the issue number.

Closes #XXXXX

### CODE REVIEW

**Comment by RandellDawson** [comment]
In the future, please use PR titles which explain what you are changing.  If it is a translation, please also indicate **translation: language name**. This let's the reviewer quickly know what kind of contribution you have made.

Also, please read/check all 5 items above indicating you have fulfilled each requirement.

**Comment by rodoviario** [comment]
I apologize x 2, I will check the 5 points next time, and use your suggestion of title (or a meaningful in any other case)

**Comment by RandellDawson** [comment]
Nothing is stopping you from updating your title or checking them off now.

**Review by RandellDawson — APPROVED** [review]

**Comment by RandellDawson** [comment]
Thank you for your contribution to the page! 👍
We're happy to accept these changes, and look forward to future contributions. 🎉

**Pull request merged**
