### PR TITLE
fix(curriculum): remove unnecessary quote signs

### PR DESCRIPTION
**Pull request by ghost**
The original issue is mentioned here. https://freecodecamp.crowdin.com/translate/690087755819f2f67b26dbee3be0eb53/all/en-fa/132?filter=basic&value=0

There were unnecessary quotation marks in the text. I just removed Those.

Checklist:

- [x] I have read [freeCodeCamp's contribution guidelines](https://contribute.freecodecamp.org).
- [x] My pull request has a descriptive title (not a vague title like `Update index.md`)
- [x] My pull request targets the `main` branch of freeCodeCamp.
- [x] I have tested these changes either locally on my machine, or GitPod.

Closes #XXXXX

### CODE REVIEW

**Comment by gikf** [comment]
Hey @najmieh could you remove changes to `curriculum/challenges/_meta/project-euler/meta.json` and `.../problem-283-integer-sided-triangles-for-which-the-area--perimeter-ratio-is-integral.md` from this PR?

**Comment by najmieh** [comment]
> Hey @najmieh could you remove changes to `curriculum/challenges/_meta/project-euler/meta.json` and `.../problem-283-integer-sided-triangles-for-which-the-area--perimeter-ratio-is-integral.md` from this PR?

Sure I do that. I need a little bit of Guidance on that. How should I remove those?

**Comment by gikf** [comment]
@najmieh one way would be using interactive rebase in git. To rebase on commit, that's one before first commit in this PR, and drop those two not needed commits from branch. Let me know if you'd need more detailed help with that.

**Comment by najmieh** [comment]
> @najmieh one way would be using interactive rebase in git. To rebase on commit, that's one before the first commit in this PR, and drop those two not needed commits from the branch. Let me know if you'd need more detailed help with that.

@gikf I rebased the commit but and used commit --amend but still, I have the previous ones here. Not sure how to edit this one. please give me further instructions. Thank You.

**Comment by gikf** [comment]
@najmieh first we need to find commit just before first commit in this PR. Looking at branch history - https://github.com/najmieh/freeCodeCamp/commits/quote-sign - we can use _chore(deps): update dependency lint-staged to v11.2.2_ commit, with hash `986345e`

`git rebase -i 986345e`

This will open editor window with list of commits made after the commit, we are rebasing on. Change `pick` to `drop` for commits that are not needed in this PR, that is:

- Edited the title following the issue
- Edited the title in the JSON file as well

After saving and closing editor window git will start the rebasing. In this case there shouldn't be any additional actions needed during it.

Once git finishes only step left is push branch with `--force` option. Because commit history on the branch was changed that option is needed update remote branch too.

**Comment by najmieh** [comment]
> @najmieh first we need to find commit just before first commit in this PR. Looking at branch history - https://github.com/najmieh/freeCodeCamp/commits/quote-sign - we can use _chore(deps): update dependency lint-staged to v11.2.2_ commit, with hash `986345e`
> 
> `git rebase -i 986345e`
> 
> This will open editor window with list of commits made after the commit, we are rebasing on. Change `pick` to `drop` for commits that are not needed in this PR, that is:
> 
> * Edited the title following the issue
> * Edited the title in the JSON file as well
> 
> After saving and closing editor window git will start the rebasing. In this case there shouldn't be any additional actions needed during it.
> 
> Once git finishes only step left is push branch with `--force` option. Because commit history on the branch was changed that option is needed update remote branch too.

woo-hoo I did it ^^
Thank you @gikf  for the help.

**Review by gikf — APPROVED** [review]
Looks good to me :+1:

**Review by naomi-lgbt — APPROVED** [review]
Looks good!

**Comment by nhcarrigan** [comment]
Thank you for your contribution to the page! 👍
We are happy to accept these changes and look forward to future contributions. 🎉

**Pull request merged**
