### PR TITLE
chore: extend linting to cover react hooks

### PR DESCRIPTION
**Pull request by ojeytonwilliams**
- [x] I have read [freeCodeCamp's contribution guidelines](https://github.com/freeCodeCamp/freeCodeCamp/blob/master/CONTRIBUTING.md).
- [x] My pull request has a descriptive title (not a vague title like `Update index.md`)
- [x] My pull request targets the `master` branch of freeCodeCamp.
- [x] None of my changes are plagiarized from another source without proper attribution.
- [x] All the files I changed are in the same world language (for example: only English changes, or only Chinese changes, etc.)
- [x] My changes do not use shortened URLs or affiliate links.

Since we're looking to start using React hooks in #36722, I figured we should lint them.

### CODE REVIEW

**Comment by ojeytonwilliams** [comment]
I gave the review in Gitpod button a push.  It's pretty fantastic!

**Comment by raisedadead** [comment]
It sure is thanks to @svenefftinge and @jankeromnes for the integration! 🚀

**Review by raisedadead — APPROVED** [review]

**Comment by raisedadead** [comment]
I just used GitPods Interface to approve and merge the PR and this is pretty sarn slick!!

**Comment by ojeytonwilliams** [comment]
I hadn't realised you could do that through GitPod.  So, yeah, thanks @svenefftinge and @jankeromnes!

**Pull request merged**
