### PR TITLE
feat(client): remove legacy search page logic

### PR DESCRIPTION
**Pull request by Sboonny**
Checklist:

- [x] I have read and followed the [contribution guidelines](https://contribute.freecodecamp.org).
- [x] I have read and followed the [how to open a pull request guide](https://contribute.freecodecamp.org/#/how-to-open-a-pull-request).
- [x] My pull request targets the `main` branch of freeCodeCamp.
- [x] I have tested these changes either locally on my machine, or GitPod.

### CODE REVIEW

**Comment by mmatsumoto1026** [comment]
Hello, @Sboonny.

I actually don't know how to test that the number of search results changes from 5 to 8 when the window height changes, so I couldn't verify it myself, but the `useMediaQuery` argument It seems that we can set a height threshold (I'm not sure if this is best practice as this is not demonstrated on the [react-responsive page](https://www.npmjs.com/package/react-responsive)).

**Comment by Sboonny** [comment]
> but the `useMediaQuery` argument It seems that we can set a height threshold (I'm not sure if this is best practice as this is not demonstrated on the [react-responsive page](https://www.npmjs.com/package/react-responsive)).

Nice catch, to be honest, I don't care about best practice, because we can't have a decent logic without account for `height` threshold, so in my eyes it can get in the way.

> I actually don't know how to test that the number of search results changes from 5 to 8 when the window height changes, so I couldn't verify it myself

You need to have key and app ID with polluted data, that will show search results.

**Comment by ahmaxed** [comment]
Thanks for the pr. The change from 5 to 8 does not seem to be happening. Also it would be great if you pull the Mobile screen size from the config/mics.ts or move it there if it does not exist. Other than that things look good.

**Comment by Sboonny** [comment]
@ahmaxed, the change happens when you change the breakpoint for the height.

image
image


The logic that targets height confused me at first, too.

----

I am in conflict about adding the value to `config/misc.ts`, because there is no other place that is using it, and if we are going to use it in multiple places in the future, I prefer removing the logic entirely, having a breakpoint for height is confusing and having more will be a nightmare.

**Comment by ahmaxed** [comment]
It makes sense. LGTM

**Review by ahmaxed — APPROVED** [review]

**Review by moT01 — APPROVED** [review]
LGTM @Sboonny 🎉 
Screen Shot 2023-07-11 at 12 38 17 PM

**Pull request merged**
