### PR TITLE
fix(ui): confirmation safeguard danger zone

### LINKED ISSUE #55684: Make the Danger Zone safer by adding a confirmation safeguard that requires typing a specific phrase
### Is your feature request related to a problem? Please describe.

The Danger Zone contains stuff about resetting all progress and deleting accounts. Currently, you only have to click on the “Yes” button or anything similar to perform these dangerous actions. I think leaving this just like the way it is could cause lots of progress loss:

[Screenshot_2024-07-28-21-32-37-799_com kiwibrowser browser-edit](https://github.com/user-attachments/assets/3db35b6d-2b58-41bc-9184-3ce9522374c1)

[Screenshot_2024-07-28-21-33-15-253_com kiwibrowser browser-edit](https://github.com/user-attachments/assets/d28437d1-adb6-4ef4-908a-1603c2661fc5)

### Describe the solution you'd like

My suggestion is to add a failsafe, where you type something like “I agree that all progress will be lost” (without quotes), just like in GitHub:

[IMG_20240728_214736](https://github.com/user-attachments/assets/4b8ab203-f40e-4fdb-9b22-18941fe041e4)

### Describe alternatives you've considered

No alternatives would fit for the solution because the failsafe must take a lot of time for users in order to protect users from progress loss accidents. So, it is crucial to make the failsafe be a typing specific phrase, which takes a lot of time so that users will not experience progress loss accidents.

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by gagan-bhullar-tech**
Checklist:

- [x] I have read and followed the [contribution guidelines](https://contribute.freecodecamp.org).
- [x] I have read and followed the [how to open a pull request guide](https://contribute.freecodecamp.org/how-to-open-a-pull-request/).
- [x] My pull request targets the `main` branch of freeCodeCamp.
- [x] I have tested these changes either locally on my machine, or GitPod.

Closes #55684

### CODE REVIEW

**Review by Sembauke — APPROVED** [review]
A good safeguard. I like it.

**Review by moT01 — CHANGES_REQUESTED** [review]
This looks good @gagan-bhullar-tech 👍 

It adds the verification when resetting your progress, but the delete account option still doesn't have it. I think we should add that here so we have it on both when it gets deployed.

**Comment by gagan-bhullar-tech** [comment]
@moT01 updated PR.

**Review by moT01 — COMMENTED** [review]
One more thing

**Review by moT01 — APPROVED** [review]
LGTM @gagan-bhullar-tech 🎉 Thanks for working on this 👍

**Pull request merged**
