### PR TITLE
fix(classic-challenge): should not show scroll bar if not needed

### PR DESCRIPTION
**Pull request by BerkeleyTrue**

### CODE REVIEW

**Comment by QuincyLarson** [comment]
@BerkeleyTrue Is this ready to QA? Do you by any chance have a before/after screen shot so I can know which scrollbar I should look out for when QA'ing? Happy to hop on Skype and knock out this one and others if that's faster.

**Comment by BerkeleyTrue** [comment]
Yes, this is marked as QA. 

Here is a photo of what it looks like without this:

basic_html_and_html5__say_hello_to_html_elements___freecodecamp

**Comment by QuincyLarson** [comment]
@BerkeleyTrue lgtm!

**Comment by barkinet** [comment]
<html>
    <head>
    </head>
    
    <body>
    <h1>Hello World<h1>
    <body>  
    
</html>

**Pull request merged**
