### PR TITLE
fix(learn): Remove repeated definition tag in challenge

### PR DESCRIPTION
**Pull request by kelvinsanchez15**
Checklist:

- [x] I have read [freeCodeCamp's contribution guidelines](https://contribute.freecodecamp.org).
- [x] My pull request has a descriptive title (not a vague title like `Update index.md`)
- [x] My pull request targets the `main` branch of freeCodeCamp.
- [x] All the files I changed are in the same world language, for example: only English changes, or only Chinese changes, etc.

### CODE REVIEW

**Review by raisedadead — APPROVED** [review]

**Review by RandellDawson — APPROVED** [review]
LGTM

**Comment by kelvinsanchez15** [comment]
@raisedadead @RandellDawson 
I'm sorry, I just realized that I targeted the Spanish version of the file instead of English. Should I fix it with another PR?

**Comment by raisedadead** [comment]
Ah - that's right. Please create a separate PR. @nhcarrigan did we not create some workflow action that catches accidental changes like this?

**Comment by kelvinsanchez15** [comment]
Created at: https://github.com/freeCodeCamp/freeCodeCamp/pull/41151

**Comment by nhcarrigan** [comment]
@raisedadead we have that workflow but switched it off when we ran in to issues with the Crowdin download PRs.

**Comment by raisedadead** [comment]
Thanks for letting us know.

**Comment by RandellDawson** [comment]
We need to reimplement the action that only allows prs to change English unless it comes from a specific branch located on the FCC repo.

**Comment by nhcarrigan** [comment]
@RandellDawson I'll be working on that shortly.

**Pull request merged**
