### PR TITLE
Remove bower_components from source and use bower.json

### PR DESCRIPTION
**Pull request by fnky**
Use `bower install` to install bower components.

### CODE REVIEW

**Comment by BerkeleyTrue** [comment]
I don't see the benefit of this. This adds an extra step and extra software requirement to new users who want to contribute. 

Unlike npm modules, bower files do not have to be built/compiled, so there is no real issue with tracking them.  The only other reason not to track is to clean up folder structure.

**Comment by QuincyLarson** [comment]
@fnky If this does indeed introduce an additional setup step for new contributors without any real performance gains, I would be inclined to agree with @BerkeleyTrue . Are there other reasons to do this that we haven't discussed here?

**Comment by BerkeleyTrue** [comment]
Going to close this as an extra barrier to new campers wanting to contribute . If there are other reasons please feel free to reopen this.

**Comment by fnky** [comment]
I can see the problem in relying on GitHub for packages. However, what about just separating bower components and first-party libraries and still check-in the bower components (removing directory from `.gitignore`)

**Comment by BerkeleyTrue** [comment]
Ideally all third party stuff should have their own directory so they can easily be ignored during linting. This isn't such a big deal in master, but in reactify branch, which will eventually be master, we are hope to have everything linted. 

At the moment we are only handling burning fires in master and focusing on getting reactify ready. When that is pushed I would welcome a PR to clean up public scripts.

**Pull request closed without merging**
