### PR TITLE
Fixing spelling errors

### PR DESCRIPTION
**Pull request by MEWestvig**
- [x] I have read [freeCodeCamp's contribution guidelines](https://github.com/freeCodeCamp/freeCodeCamp/blob/master/CONTRIBUTING.md).
- [x] My pull request has a descriptive title (not a vague title like `Update index.md`)
- [x] My pull request targets the `master` branch of freeCodeCamp.
- [x] None of my changes are plagiarized from another source without proper attribution.
- [x] My article does not contain shortened URLs or affiliate links.

If your pull request closes a GitHub issue, replace the XXXXX below with the issue number.

Closes #XXXXX

### CODE REVIEW

**Comment by adrianch** [comment]
I came across this PR and have resolved the conflict - I forked from MEWestvig's repo. 
Wondering how you would like me to resolve the conflict? Should I raise a PR against MEWestvig's repo to propagate the change from my repo and keep this PR open?
or should I raise a PR from my repo against freeCodeCamp repo directly? I believe the later will create a separate PR.

**Comment by RandellDawson** [comment]
@adrianch If you resolved the conflict locally by pulling down the user's branch, then you will need to force-push the changed back to the user's branch.  This PR can actually be resolved via the Github site, by clicking on the `Resolve conflicts` button above.

**Comment by adrianch** [comment]
@RandellDawson For some reason that button is not visible for me. 
In case it's easier, I have raised a similar PR to this
https://github.com/freeCodeCamp/freeCodeCamp/pull/34698

**Comment by RandellDawson** [comment]
@adrianch I resolved the merge conflict and closed your duplicate.  It is best to resolve the conflict either using Github site (if possible) or locally instead of creating a new PR.

**Comment by RandellDawson** [comment]
Congrats @MEWestvig on your first pull request (PR)! 🎉

Thank you for your contribution to the page! 👍
We're happy to accept these changes, and look forward to future contributions. 📝

**Comment by codepritesh** [comment]
how can i contribute

**Pull request merged**
