### PR TITLE
solution to Challenge ID:bad87fee1348bd9aedd08835

### PR DESCRIPTION
**Pull request by anassalam**
solution to Challenge ID:bad87fee1348bd9aedd08835 - Check Radio Buttons and Checkboxes by Default

- [x] I have read [freeCodeCamp's contribution guidelines](https://github.com/freeCodeCamp/freeCodeCamp/blob/master/CONTRIBUTING.md).
- [x] My pull request has a descriptive title (not a vague title like `Update index.md`)
- [x] My pull request targets the `master` branch of freeCodeCamp.
- [x] None of my changes are plagiarized from another source without proper attribution.
- [x] My article does not contain shortened URLs or affiliate links.

If your pull request closes a GitHub issue, replace the XXXXX below with the issue number.

Closes #XXXXX

### CODE REVIEW

**Comment by RandellDawson** [comment]
Closed and reopened this PR in an attempt to resolve the following Travis build error:

> AssertionError: Test suit does not fail on the initial contents

**Review by paulywill — APPROVED** [review]
Tested locally and LGTM!

**Comment by RandellDawson** [comment]
I also have tested this added solution and it works.

**Review by RandellDawson — APPROVED** [review]

**Comment by RandellDawson** [comment]
Thank you for your contribution to the page! 👍
We're happy to accept these changes, and look forward to future contributions. 🎉

**Pull request merged**
