### PR TITLE
fix(client): move new stuffs to new pages location

### PR DESCRIPTION
**Pull request by ShaunSHamilton**
Checklist:

- [x] I have read [freeCodeCamp's contribution guidelines](https://contribute.freecodecamp.org).
- [x] My pull request has a descriptive title (not a vague title like `Update index.md`)
- [x] My pull request targets the `main` branch of freeCodeCamp.
- [x] I have tested these changes either locally on my machine, or GitPod.

**TBD**

I have no idea what to do about the certification projects, because we currently have one `index.md` file (page) for all 5 projects, but should this have one for each?

### CODE REVIEW

**Comment by moT01** [comment]
Could we mimic what's in the curriculum? Keep the existing page for the old RWD (one page, all five projects). And add a 2022 folder in that learn folder with the five new projects in there. Seems like that should work.

**Comment by ShaunSHamilton** [comment]
> Keep the existing page for the old RWD (one page, all five projects). And add a 2022 folder in that learn folder with the five new projects in there.

To clarify: One new folder within `src/pages/learn/2022` called `/responsive-web-design-projects`, which contains one `index.md` the same as what is in `src/pages/learn/responsive-web-design-projects`?

**Comment by moT01** [comment]
no, sorry. Each project is it's own block in the new RWD. So I was thinking something like this...
```
pages
  - learn
    - 2022
      - responsive-web-design
        index.md
        - build-a-personal-portfolio-webpage-project
          index.md
        - build-a-product-landing-page-project 
          index.md
        - build-a-survey-form-project
          index.md
        - build-a-technical-documentation-page-project
          index.md
        - build-a-tribute-page-project
          index.md
```

**Review by naomi-lgbt — APPROVED** [review]

**Review by ojeytonwilliams — APPROVED** [review]
LGTM :+1:

**Review by moT01 — APPROVED** [review]

**Pull request merged**
