### PR TITLE
Updated GIFs and Screenshots with up-to-date branding of FreeCodeCamp

### LINKED ISSUE #8839: Update GIFs and screenshots on Getting Started Challenges
Some GIFs and screenshots on the following challenges need updated, as they show older versions of the site and branding:
- [x] [Create a GitHub account and join our chat rooms](https://www.freecodecamp.com/challenges/create-a-github-account-and-join-our-chat-rooms)
- [x] [Configure your code portfolio](https://www.freecodecamp.com/challenges/configure-your-code-portfolio)
- [x] [Join a campsite in your city](https://www.freecodecamp.com/challenges/join-a-campsite-in-your-city)
- [x] [Learn what to do if you get stuck](https://www.freecodecamp.com/challenges/learn-what-to-do-if-you-get-stuck)

## Examples:

**_Older version of the site_**

image

_**Needs changed to the new green background: `#006400`**_

image

### PR DESCRIPTION
**Pull request by ghost**
#### Pre-Submission Checklist
- [x] Your pull request targets the `staging` branch of FreeCodeCamp.
- [x] Branch starts with either `fix/`, `feature/`, or `translate/`.
- [x] You have only one commit.
- [x] All new and existing tests pass the command `npm run test-challenges`.
#### Type of Change
- [x] Small bug fix (non-breaking change which fixes an issue)
#### Checklist:
- [x] Tested changes locally.
- [x] Closes currently open issue: Closes #8839

### CODE REVIEW

**Comment by v0109** [comment]
001-302-255-8888

**Comment by dhcodes** [comment]
@atjonathan this lgtm, but there are still a few gifs with older branding. ex. http://beta.freecodecamp.com/en/challenges/join-the-free-code-camp-community/learn-what-to-do-if-you-get-stuck step 7/8 where the site in the gif still has the brown color scheme. I'm not sure all of them need to be updated but wanted to point it out just in case.

**Comment by atjonathan** [comment]
@dhcodes, sure 😉

**Comment by atjonathan** [comment]
@dhcodes, we should be good to go!

**Comment by dhcodes** [comment]
LGTM, can someone else test too?

**Comment by dhcodes** [comment]
LGTM @atjonathan. As food for thought in the future, I might recommend stripping out the loading screens between sites (ex. the 2 second white screen when loading the facebook page) on the gifs. Do you use Camtasia to make these gifs?

**Comment by atjonathan** [comment]
@dhcodes, I use licecap. The old gifs had loading screens so I didn't think to remove them in the new ones. When these need changed again, we can bear that in mind 😄

**Pull request merged**
