### PR TITLE
fix(learn): Rework Euler Problem 182

### PR DESCRIPTION
**Pull request by Ne0nWinds**
Checklist:
- [x] I have read [freeCodeCamp's contribution guidelines](https://contribute.freecodecamp.org).
- [x] My pull request has a descriptive title (not a vague title like `Update index.md`)
- [x] My pull request targets the `main` branch of freeCodeCamp.
- [x] All the files I changed are in the same world language, for example: only English changes, or only Chinese changes, etc.

- Addresses #40896
- Fixed description (it was completely unreadable before)
- Added 5 tests
- Added Solution

### CODE REVIEW

**Review by moT01 — COMMENTED** [review]
Yikes, what happened to this file.

I think we should try and make this a little prettier. Here's some issues I see:
- I think we should put backticks around all the equations to separate them from the text. This particular line: `Then n=1937=703 and φ=1836=648.` isn't rendering the `*` for some reason. It should be `Then n=19*37=703 and φ=18*36=648.`
- The exponents in the equations look like any other letter. `m=cd` for instance, should look like m=c<sup>d</sup> - hmm, looks like you can't combine the backticks and the `<sup>` tags. Perhaps we shouldn't go with the backticks then. @gikf left some suggestions on your other PR @Ne0nWinds - I haven't looked at them, but there may be some good advice on how to render some things in there.
- I haven't dove into this to figure out how it all works but, if we are changing the function to accept arguments `p` and `q`, the instruction probably need to change to reflect that - which, I don't think they do. `Choose p=1009 and q=3643. Find the sum of all values of e, 1 < e < φ(1009,3643)`, for instance, might need to change to `Find the sum of all values of e, 1 < e < φ(p,q)` or something - not sure.


I would prefer to try and fix these things up - however, anything is better than what's there now - so I would be fine merging this without fixing them if it comes to it.

I'm sure you've been there, but here's a link to [the original Euler challenge](https://projecteuler.net/problem=182) for reference

**Comment by Ne0nWinds** [comment]
@moT01 @gikf  So I've added a commit with better formatting, but I'm still not sure when to use the mathjax library or when to put equations in backticks. Is there style guide or rule of thumb for this? I guess, just let me know what else I can do for this PR's description

**Comment by moT01** [comment]
I added a comment on the issue about that @Ne0nWinds. I think we should come to a consensus again, so we can be consistent moving forward.

**Review by gikf — COMMENTED** [review]
I've confirmed expected results in tests against another solution.

I think once formatting doubts are clarified this will be good to go.

**Review by moT01 — APPROVED** [review]
I think I'm good with this one.

There are some inconsistencies:
Screen Shot 2021-03-09 at 9 24 31 AM

Looks like most of the equations and variables are in backticks, giving the darker background color - but there's a few that don't have it. I would prefer they all have it. I don't know if there's a way to highlight those last few.

I think since this is such a dramatic improvement, I would be fine merging this.

LGTM @Ne0nWinds 🎉 

I added this solution to the forum guide article.

**Comment by Ne0nWinds** [comment]
@moT01 The reason those equations that don't have backticks is because the exponents just don't look correct with the backtick styling
image
Mathjax makes it look inconsistent with the rest of the problem, so I'm not sure what the best approach is

**Review by gikf — APPROVED** [review]
Considering current unreadable state of the challenge, leaving little inconsistencies for later, seems to be okay.

**Comment by gikf** [comment]
Thank you for your contribution to the page! 👍
We are happy to accept these changes and look forward to future contributions. 🎉

**Pull request merged**
