### PR TITLE
docs: translate testString and description of slice and splice (portuguese)

### PR DESCRIPTION
**Pull request by PeterF521**
Checklist:

- [x] I have read [freeCodeCamp's contribution guidelines](https://contribute.freecodecamp.org).
- [x] My pull request has a descriptive title (not a vague title like `Update index.md`)
- [x] My pull request targets the `master` branch of freeCodeCamp.
- [x] All the files I changed are in the same world language, for example: only English changes, or only Chinese changes, etc.

I translated a change that I did on description to portuguese and I improved the translation of `text` and `testString` params.

### CODE REVIEW

**Comment by RandellDawson** [comment]
@PeterF521 I should have mentioned this on the other PR, but you really should not create your PRs from the master branch.  You always want your fork's master branch to be reflective of the current master branch in freecodecamp's repo.  Instead, you should always sync up your local with freecodecamp's master (see documentation) and then create a new local branch to push up to your fork.  You will use this branch on your fork to create a PR against the freecodecamp's master branch.

**Comment by PeterF521** [comment]
Ok, sorry

**Comment by PeterF521** [comment]
So I need to create a branch for create a PR.

**Comment by RandellDawson** [comment]
First, you need to make sure you sync your local master with the current master.

**Pull request closed without merging**
