### PR TITLE
Revert "Challenge - ES6: Use Destructuring Assignment to Assign Variables from Arrays - Added solution"

### PR DESCRIPTION
**Pull request by paulywill**
Reverts freeCodeCamp/freeCodeCamp#26531

Sorry the last test is still passing without deconstruction, as indicated by @RandellDawson .

### CODE REVIEW

**Comment by raisedadead** [comment]
Hi @RandellDawson can we get this resolved and delete the branch? I understand this is just a revert.

**Comment by RandellDawson** [comment]
@raisedadead I will test it locally now and if it passes all the tests, I will merge it and delete the branch.

**Comment by RandellDawson** [comment]
@raisedadead This should never have been merged before the other PR #34538 was reviewed and merged, so I guess merging this one which takes it back to what it was before is fine.

**Comment by RandellDawson** [comment]
@raisedadead I have tested the changes locally and everything seems to be working fine as it was before the other PR was merged.

**Comment by raisedadead** [comment]
Awsome! Thanks a lot @RandellDawson !

**Pull request merged**
