### PR TITLE
fix: account for tab height when sizing editor

### PR DESCRIPTION
**Pull request by ojeytonwilliams**
@ahmadabdolsaheb this fixes the problems caused by putting the tabs next to the editor, but it's not pretty.  Any idea how to do it better?

### CODE REVIEW

**Comment by ahmadabdolsaheb** [comment]
Did not see any issue with the tab hight when resizing the editor. could you elaborate?

**Comment by ojeytonwilliams** [comment]
Sure.  The problem arises when there is so much in the Editor that you have to scroll.  Without the changes if you scroll to the bottom it looks like this:
image

and with them: 
image

That said, I'm re-organising things for the multi-editor case and this problem might go away, so this isn't a high priority.

**Comment by RandellDawson** [comment]
@ojeytonwilliams Is this PR still needed after merged the recent changes to the multi-file editor?

**Comment by ojeytonwilliams** [comment]
The editor has moved on and this PR is no longer relevant.

**Pull request closed without merging**
