### PR TITLE
Add another test to the Chunky Money challenge

### LINKED ISSUE #7031: Chunky Monkey needs randomly generated tests
Challenge [Chunky Monkey](http://www.freecodecamp.com/challenges/chunky-monkey#?solution=function%20chunk(arr%2C%20size)%20%7B%0A%20%20%2F%2F%20Break%20it%20up.%0A%20%20var%20chunks%20%3D%20%5B%5D%3B%0A%20%20chunks.push(arr.slice(0*size%2C%20size))%3B%0A%20%20chunks.push(arr.slice(size%2C%202*size))%3B%0A%20%20if%20(arr.length%20%3E%202*size)%20%7B%0A%20%20%20%20%20%20chunks.push(arr.slice(2*size%2C%203*size))%3B%0A%20%20%7D%0A%20%20return%20chunks%3B%0A%7D%0A%0Achunk(%5B%22a%22%2C%20%22b%22%2C%20%22c%22%2C%20%22d%22%5D%2C%202)%3B%0A) has an issue.
User Agent is: <code>Mozilla/5.0 (Macintosh; Intel Mac OS X 10.10; rv:44.0) Gecko/20100101 Firefox/44.0</code>.

My code:
```javascript
function chunk(arr, size) {
  var chunks = [];
  chunks.push(arr.slice(0*size, size));
  chunks.push(arr.slice(size, 2*size));
  if (arr.length > 2*size) {
      chunks.push(arr.slice(2*size, 3*size));
  }
  return chunks;
}

```
This very naive code passes the tests, and I don't think it should. This would fail randomly generated tests (arrays of random lengths, random integers).

### PR DESCRIPTION
**Pull request by daniel-chung**
#### Pre-Submission Checklist

- [x] Your pull request targets the `staging` branch of FreeCodeCamp.
- [x] Branch starts with either `fix/`, `feature/`, or `translate/` (e.g. `fix/signin-issue`)
- [x] You have only one commit (if not, [squash](https://github.com/FreeCodeCamp/FreeCodeCamp/wiki/git-rebase#squashing-multiple-commits-into-one) them into one commit).
- [x] All new and existing tests pass the command `npm run test-challenges`. Use `git commit --amend` to amend any fixes.
#### Type of Change

- [x] Small bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds new functionality)
- [ ] Breaking change (fix or feature that would change existing functionality)
- [ ] Add new translation (feature adding new translations)
#### Checklist:

- [x] Tested changes locally.
- [x] Closes currently open issue (replace XXXX with an issue no): Closes #7031 
#### Description

Inserts another test to the Chunky Money challenge that checks a situation where the solution returns  array of 5 "chunks" (i.e., an array containing 5 arrays).

Resolves: #7031

### CODE REVIEW

**Comment by erictleung** [comment]
@daniel-chung hi there! For this one, it appears to may have reverted your commits too much on this one. You also seem to have the commits from the other PR on this one. Also, for commit message, you don't need to add in the issue numbers. You only need to add it here on GitHub.

For this PR, you'll need to remove your last commit for this branch (because that commit is for the other PR) and then make your intended changes.

These commands may help

```bash
cd where-your-freecodecamp-folder-is
git checkout fix/add-test
 git reset --hard HEAD^
... # Make your actual changes for the Chunky Monkey challenge here
git add seed/challenges/01-front-end-development-certification/basic-javascript.json # Or wherever the file is
git commit # And you can put your commit message
```

As with the other PR, feel free to visit the [Contributors Help](https://gitter.im/FreeCodeCamp/HelpContributors) chat room if you have any questions about helping.

**Comment by daniel-chung** [comment]
@erictleung thanks so much for the detailed responses! I went through the reset and updated my commit.

**Comment by erictleung** [comment]
@daniel-chung no problem, glad those helped! It'll get easier the more you contribute. Anyways, your commit looks good to me! Congrats on your first PR to FreeCodeCamp! ✨ 🎉 ✨

**Comment by daniel-chung** [comment]
Thanks @erictleung !

**Pull request merged**
