### PR TITLE
fix(style): rework color scheme for icons

### LINKED ISSUE #36666: [.dev] checkmarks on learn+night mode are hard to see
Screen Shot 2019-08-22 at 9 52 02 AM

It's worse than it looks in the picture, it's like an optical illusion or something.

### PR DESCRIPTION
**Pull request by moT01**
I reworked the colors of our icons to go with the new theme. I'm not sure if that was wanted - I think they look pretty good - see photos.

- [x] I have read [freeCodeCamp's contribution guidelines](https://github.com/freeCodeCamp/freeCodeCamp/blob/master/CONTRIBUTING.md).
- [x] My pull request has a descriptive title (not a vague title like `Update index.md`)
- [x] My pull request targets the `master` branch of freeCodeCamp.
- [x] None of my changes are plagiarized from another source without proper attribution.
- [x] All the files I changed are in the same world language (for example: only English changes, or only Chinese changes, etc.)
- [x] My changes do not use shortened URLs or affiliate links.

Closes #36666

Screen Shot 2019-09-05 at 7 57 37 AM
Screen Shot 2019-09-05 at 7 57 55 AM
Screen Shot 2019-09-05 at 7 58 13 AM
Screen Shot 2019-09-05 at 7 56 16 AM
Screen Shot 2019-09-05 at 7 56 34 AM
Screen Shot 2019-09-05 at 7 56 57 AM

### CODE REVIEW

**Comment by raisedadead** [comment]
Not related but could you add a 1-2px padding or margin between those test lists. I have always hated them getting squished like that.

**Comment by ahmadabdolsaheb** [comment]
We could even add more space.
Alternate background colors for list items could be re-evaluated.
See #36681 mocks for reference.

**Comment by ahmadabdolsaheb** [comment]
we could also experiment with smaller icons for the tests

**Comment by moT01** [comment]
Screen Shot 2019-09-05 at 1 45 09 PM

**Comment by moT01** [comment]
I added my changes to the PR in case anyone wants to see the code or test it locally.

**Comment by ahmadabdolsaheb** [comment]
it looks much better already

**Review by ahmaxed — APPROVED** [review]

**Review by raisedadead — APPROVED** [review]

**Pull request merged**
