### PR TITLE
fix(curriculum): rework Project Euler 95

### PR DESCRIPTION
**Pull request by gikf**
- Reworks challenge to use argument in function call.
- Adds more tests.
- Adds solution.
- Uses MathJax to improve positioning and look of example.
- Related to #40896.

Checklist:

- [x] I have read [freeCodeCamp's contribution guidelines](https://contribute.freecodecamp.org).
- [x] My pull request has a descriptive title (not a vague title like `Update index.md`)
- [x] My pull request targets the `main` branch of freeCodeCamp.
- [x] I have tested these changes either locally on my machine, or GitPod.

### CODE REVIEW

**Review by Sembauke — COMMENTED** [review]
Can we change "For this reason, 220 and 284 are called an amicable pair."  to "For this reason, 220 and 284 are called amicable pairs."

**Comment by gikf** [comment]
> Can we change "For this reason, 220 and 284 are called an amicable pair." to "For this reason, 220 and 284 are called amicable pairs."

Won't that make it sound a bit stranger? Could you take another look?

**Comment by Sembauke** [comment]
I am fine with leaving it as it is.

**Review by Sembauke — APPROVED** [review]

**Review by raisedadead — APPROVED** [review]

**Comment by moT01** [comment]
I added this solution to the forum guide article

**Pull request merged**
