### PR TITLE
Update test case for Waypoint to 'container-fluid'.

### PR DESCRIPTION
**Pull request by aviato**
Issue [1567](https://github.com/FreeCodeCamp/freecodecamp/issues/1567)

The test case should now properly look for 'container-fluid' instead of 'row'.

### CODE REVIEW

**Comment by Greenheart** [comment]
@ rsprice Nice job! ^^

**Comment by ahstro** [comment]
Let's play "who gets merged first" ;) #1613

**Comment by BerkeleyTrue** [comment]
Hello @rsprice 

This is a duplicate of @ahstro PR. In the future please to a search to ensure no duplicate efforts are being made.


Happy Coding!

**Comment by Greenheart** [comment]
@ahstro Or maybe people who start solving issues could leave a comment so others know... ;)

**Comment by ahstro** [comment]
@Greenheart Or maybe GitHub could fix their permissions so I can self-assign ;)

**Comment by rsprice** [comment]
@BerkeleyTrue, my bad! @ahstro nice job, sir. :+1:

**Pull request closed without merging**
