### PR TITLE
change "#button" to "button" in the example to target all buttons.

### LINKED ISSUE #2014: Wrong jQuery example
Challenge http://freecodecamp.com/challenges/waypoint-disable-an-element-using-jquery has an issue. Please describe how to reproduce it, and include links to screenshots if possible.

Here's how you would disable all buttons: $('#button').prop('disabled', true);

should be

$('button').prop('disabled', true);

btw, do we have a codestyle for javascript? This is the first waypoint I've seen using single quotes.

### PR DESCRIPTION
**Pull request by mtrifilo**
I changed "#button" to "button" in the example to target all buttons, and I changed the single quotes to double quotes in the description for consistency.

Closes #2014

### CODE REVIEW

**Comment by benmcmahon100** [comment]
Can you please check this out in a JSON linter. The JSON is completely broken

**Comment by benmcmahon100** [comment]
Once the JSON is good i can merge this in for you right away! It should just need to have the " escaped within the string

**Comment by itxchy** [comment]
My mistake, I escaped the double quotes. It should be fine now.

**Comment by BerkeleyTrue** [comment]
Please change the title to be descriptive of the changes you have made.

Also state which issues, if any, that this PR closes in the description each on its own line. For example: `closes #1337`

**Comment by itxchy** [comment]
@BerkeleyTrue 

I changed the initial title and description of this pull request. I'll look up some style guides for GitHub, still getting my feet wet.

**Comment by BerkeleyTrue** [comment]
No worries.

**Pull request merged**
