### PR TITLE
Add "scope based variables" to this article

### PR DESCRIPTION
**Pull request by Ccancode**
- [x] I have read [freeCodeCamp's contribution guidelines](https://github.com/freeCodeCamp/freeCodeCamp/blob/master/CONTRIBUTING.md).
- [x] My pull request has a descriptive title (not a vague title like `Update index.md`)
- [x] My pull request targets the `master` branch of freeCodeCamp.
- [x] None of my changes are plagiarized from another source without proper attribution.
- [x] My article does not contain shortened URLs or affiliate links.

If your pull request closes a GitHub issue, replace the XXXXX below with the issue number.

Closes #XXXXX

### CODE REVIEW

**Comment by lynxlynxlynx** [comment]
Please fix the spacing around your punctuation and use plurals names as needed.

**Comment by Ccancode** [comment]
hi jaka Kranjc ,didn't understood what you said? please can you elaborate
which spaces which punctuation?

**Comment by lynxlynxlynx** [comment]
all punctuation, just look at your own changes.

**Comment by RandellDawson** [comment]
@Ccancode Can you rebase your PR and resolve any outstanding merge conflicts. There were earlier PRs for this same article which have now been merged.  A lot of your changes may not be relevant based on the most updated version of this article on `master`.  You may need to shift some of your content around.

**Comment by RandellDawson** [comment]
@Ccancode As there has been no response from your end for a while, I am closing this PR.

Feel free to request this PR to be reopened, if you still wish to make the changes you originally added.  Also, remember to update your fork, so you have the latest version of master in case it has changed significantly.

Happy Coding!

**Pull request closed without merging**
