### PR TITLE
fixed an unclosed <code> tag that was triggering invariant element id error

### LINKED ISSUE #16581: [Beta] On site code editor and page not working when reloading/refreshing react challenge
#### Challenge Name
React: Use Array.filter() to Dynamically Filter an Array

https://beta.freecodecamp.org/en/challenges/react/use-arrayfilter-to-dynamically-filter-an-array

#### Issue Description

On the above challenge, when you reload or refresh the page, the on site code editor doesn't load and stays on the black shimmering type animation and the formatting of the instructions change. Also, none of the buttons work except for the ones with an href attribute with an outside link.

I have been able to reproduce this this on my three browsers of Chrome, Firefox, and Safari.
#### Browser Information

* Browser Name, Version: 

- Google Chrome Version 63.0.3239.132 (Official Build) (64-bit)
- Mozilla Firefox Quantum 57.0.4 (64-bit)
- Apple Safari Version 11.0.2 (13604.4.7.1.3)

* Operating System: Mac OS High Sierra 10.13.2
* Mobile, Desktop, or Tablet: Desktop

#### Your Code

```js



```
#### Screenshot

screen shot 2018-01-26 at 11 32 15 am
screen shot 2018-01-26 at 11 32 48 am
screen shot 2018-01-26 at 11 32 56 am

### PR DESCRIPTION
**Pull request by squirrelsquirrel78**
#### Pre-Submission Checklist

- [x] Your pull request targets the `staging` branch of freeCodeCamp.
- [x] Branch starts with either `fix/`, `feature/`, or `translate/` (e.g. `fix/signin-issue`)
- [x] You have only one commit (if not, [squash](http://forum.freecodecamp.org/t/how-to-squash-multiple-commits-into-one-with-git/13231) them into one commit).
- [x] All new and existing tests pass the command `npm test`. Use `git commit --amend` to amend any fixes.

#### Type of Change

- [x] Small bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds new functionality)
- [ ] Breaking change (fix or feature that would change existing functionality)
- [ ] Add new translation (feature adding new translations)

#### Checklist:

- [x] Tested changes locally.
- [x] Addressed currently open issue (replace XXXXX with an issue no in next line)

Closes #16581

#### Description
An unclosed `<code>` tag in the React challenge "React: Use Array.filter() to Dynamically Filter an Array" was disrupting the DOM (`invariant` throws the error `Unable to find element with ID 646.`). As a result, the entire page broke. I closed this tag in the [seed file](https://github.com/freeCodeCamp/freeCodeCamp/blob/staging/seed/challenges/03-front-end-libraries/react.json) and have successfully tested the page locally.

### CODE REVIEW

**Comment by vkWeb** [comment]
@BerkeleyTrue Much required update! Please review this.

**Review by Bouncey — APPROVED** [review]
Code LGTM 👍

**Comment by DawoodMorris** [comment]
‎L
Ltl
L‎to
Sent from my BlackBerry 10 smartphtnepl

From: Stuart Taylor
Sent: Tuesday, January 30, 2018 9:00 PM
To: freeCodeCamp/freeCodeCamp
Reply To: freeCodeCamp/freeCodeCamp
Cc: Subscribed
Subject: Re: [freeCodeCamp/freeCodeCamp] fixed an unclosed <code> tag that was triggering invariant element id error (#16594)



@Bouncey approved this pull request.

Code LGTM 👍

**Comment by Bouncey** [comment]
Thanks @jkao1 👍

**Pull request merged**
