### PR TITLE
fix(curriculum): fix incorrectly highlighted texts

### LINKED ISSUE #55803: Example texts being incorrectly highlighted in Build a Gradebook App
## Description

The example texts are plain text so they shouldn't have syntax highlighting applied.

Screenshot 2024-08-10 at 00 06 57

## Affected page

- https://www.freecodecamp.org/learn/javascript-algorithms-and-data-structures-v8/review-js-fundamentals-by-building-a-gradebook-app/step-1
- https://www.freecodecamp.org/learn/javascript-algorithms-and-data-structures-v8/review-js-fundamentals-by-building-a-gradebook-app/step-4

## Changes needed

Remove `js` from the following code blocks:
- https://github.com/freeCodeCamp/freeCodeCamp/blob/18fe86897e07e9e027a7d9f4beb78f369c63d361/curriculum/challenges/english/15-javascript-algorithms-and-data-structures-22/review-js-fundamentals-by-building-a-gradebook-app/662693f82c91a66be46c881b.md#L16
- https://github.com/freeCodeCamp/freeCodeCamp/blob/18fe86897e07e9e027a7d9f4beb78f369c63d361/curriculum/challenges/english/15-javascript-algorithms-and-data-structures-22/review-js-fundamentals-by-building-a-gradebook-app/6626b8dcf5057f896f948440.md#L16
- https://github.com/freeCodeCamp/freeCodeCamp/blob/18fe86897e07e9e027a7d9f4beb78f369c63d361/curriculum/challenges/english/15-javascript-algorithms-and-data-structures-22/review-js-fundamentals-by-building-a-gradebook-app/6626b8dcf5057f896f948440.md#L22

### PR DESCRIPTION
**Pull request by Neema-Joju**
Checklist:

- [x] I have read and followed the [contribution guidelines](https://contribute.freecodecamp.org).
- [x] I have read and followed the [how to open a pull request guide](https://contribute.freecodecamp.org/how-to-open-a-pull-request/).
- [x] My pull request targets the `main` branch of freeCodeCamp.
- [x] I have tested these changes either locally on my machine, or GitPod.

Closes #55803

Removed ```js from the mentioned code blocks

### CODE REVIEW

**Review by gikf — COMMENTED** [review]
Please re-add the code blocks, but replace `js` with `md` as the _language_.

**Comment by Neema-Joju** [comment]
Hi,
I have added the changes suggested. Kindly let me know if it is correct or not.

**Review by gikf — APPROVED** [review]

**Review by Sembauke — APPROVED** [review]

**Comment by gikf** [comment]
Hi @Neema-Joju. Congrats on your first pull request (PR)! 🎉

Thank you for your contribution to the page! 👍
We are happy to accept these changes and look forward to future contributions. 📝

**Comment by Neema-Joju** [comment]
Hi @gikf .

Thank you as well. I am looking forward to all contributions I can make. :smile:

**Pull request merged**
