### PR TITLE
Improve Regex

### PR DESCRIPTION
**Pull request by jagzmz**
Challenge requires a matching pattern for Major 2 Minor 10 and Path 2 which should be "2.10.2"
previous regex `/^[\^\~]?2\.10\.2/` allows patterns like `~2.10.2, ^2.10.2, ~2.10.2abc` we have 2 different challenges for Tilde and Caret.
Check the regex **[here](https://regexr.com/4e6lg)**.

- [x] I have read [freeCodeCamp's contribution guidelines](https://github.com/freeCodeCamp/freeCodeCamp/blob/master/CONTRIBUTING.md).
- [x] My pull request has a descriptive title (not a vague title like `Update index.md`)
- [x] My pull request targets the `master` branch of freeCodeCamp.
- [x] None of my changes are plagiarized from another source without proper attribution.
- [x] All the files I changed are in the same world language (for example: only English changes, or only Chinese changes, etc.)
- [x] My changes do not use shortened URLs or affiliate links.

Closes #XXXXX

### CODE REVIEW

**Comment by thecodingaviator** [comment]
Is this related to #36068 ?

**Comment by jagzmz** [comment]
> Is this related to #36068 ?

No it is not!
That issue is already resolved by this PR #36074

**Review by AntoineDrouhin — APPROVED** [review]
:+1:  Looks good to me

**Review by ojeytonwilliams — APPROVED** [review]
LGTM :+1:

**Comment by moT01** [comment]
I took a look at this - to me it seems like we shouldn't need to use regex here. Seems more appropriate to just use a `.equal`...
`assert.equal(packJson.dependencies.moment, "2.10.2"`?

Could probably go that route for many of these challenges, as the others use regex as well. I suppose it works either way.

Any thoughts anyone?

**Comment by ojeytonwilliams** [comment]
@moT01 You're right, that would be better - I'm not sure why that didn't occur to me.  @jagzmz Could you change it to use `assert.equal` instead?

**Comment by jagzmz** [comment]
@ojeytonwilliams made required changes!

**Review by RandellDawson — APPROVED** [review]
LGTM now.

**Review by ojeytonwilliams — APPROVED** [review]
Thanks! LGTM.

**Comment by ojeytonwilliams** [comment]
@jagzmz Thank you for your contribution to the page! :+1:
We're happy to accept these changes, and look forward to future contributions. :memo:

**Pull request merged**
