### PR TITLE
Fix/drop it wording change

### LINKED ISSUE #14880: Incorrect phrasing on challenge "Drop It"
Challenge [Drop it](https://www.freecodecamp.com/challenges/drop-it#?solution=function%20dropElements(arr%2C%20func)%20%7B%0A%20%20return%20!arr.length%20%7C%7C%20func(arr%5B0%5D)%20%3F%20arr%20%3A%20dropElements(arr.slice(1)%2Cfunc)%3B%0A%20%20%2F%2F%20return%20(arr.filter(func).length)%20%3F%20arr.splice(arr.indexOf(arr.filter(func)%5B0%5D))%20%3A%20%5B%5D%20%3B%0A%7D) has an issue.
User Agent is: <code>Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/57.0.2987.133 Safari/537.36</code>.
Please describe how to reproduce this issue, and include links to screenshots if possible.

I believe the using the term "argument" In the first sentence of this challenge is used incorrectly, and could be confusing, especially considering the second sentence.

**The current challenge text reads:**
Drop the elements of an array (first argument), starting from the front, until the predicate (second argument) returns true.

The second argument, func, is a function you'll use to test the first elements of the array to decide if you should drop it or not.

**I propose it reads:** 
Drop the elements of an array, starting from the first (0 index), until the predicate (second **element**) returns true.

The second argument, func, is a function you'll use to test the first elements of the array to decide if you should drop it or not.

### PR DESCRIPTION
**Pull request by jonathanihm**
#### Pre-Submission Checklist

- [x] Your pull request targets the `staging` branch of freeCodeCamp.
- [x] Branch starts with either `fix/`, `feature/`, or `translate/` (e.g. `fix/signin-issue`)
- [x] You have only one commit (if not, [squash](http://forum.freecodecamp.com/t/how-to-squash-multiple-commits-into-one-with-git/13231) them into one commit).
- [x] All new and existing tests pass the command `npm test`. Use `git commit --amend` to amend any fixes.

#### Type of Change

- [x] Small bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds new functionality)
- [ ] Breaking change (fix or feature that would change existing functionality)
- [ ] Add new translation (feature adding new translations)

#### Checklist:

- [x] Tested changes locally.
- [x] Closes currently open issue: Closes #14880

#### Description
Wording change for Drop It challenge

### CODE REVIEW

**Comment by jonathanihm** [comment]
It seems my fork was a little weird when I submitted this, please let me know if you want me to close this and submit a new PR

**Comment by raisedadead** [comment]
@jonathanihm You just need a rebase (remember to do it when you work on a new fix or feature).
Here is how to do so:
https://github.com/freeCodeCamp/freeCodeCamp/blob/staging/CONTRIBUTING.md#maintaining-your-fork

You should follow the same steps for this PR i.e `fix/drop-it-wording-change` branch

Hit us up in the [Contributors Chat room](https://gitter.im/FreeCodeCamp/Contributors), in case you need any assistance.

**Comment by jonathanihm** [comment]
Sorry, I thought I had done this all but apparently I just suck at Git.  Thanks!

**Review by raisedadead — APPROVED** [review]

**Comment by raisedadead** [comment]
@jonathanihm thanks for the pull request and making the changes, and do not worry we have all been there, it's only a matter of time and practice and you will be an expert at git too.

**Pull request merged**
