### PR TITLE
fix: MailHog installation guide

### PR DESCRIPTION
**Pull request by varunzxzx**
#### Pre-Submission Checklist

- [x] Your pull request targets the `staging` branch of freeCodeCamp.
- [x] Branch starts with either `fix/`, `feature/`, or `translate/` (e.g. `fix/signin-issue`)
- [x] You have only one commit (if not, [squash](http://forum.freecodecamp.org/t/how-to-squash-multiple-commits-into-one-with-git/13231) them into one commit).
- [x] All new and existing tests pass the command `npm test`. Use `git commit --amend` to amend any fixes.

#### Type of Change

- [ ] Small bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds new functionality)
- [ ] Breaking change (fix or feature that would change existing functionality)
- [ ] Add new translation (feature adding new translations)

#### Checklist:

- [x] Tested changes locally.
- [ ] Addressed currently open issue (replace XXXXX with an issue no in next line)

Closes #XXXXX

#### Description

I just setup MailHog locally by following the current guide. But, it doesn't work as the `mailhog` is not getting installed in the root. So, I am suggesting a minor change in this PR so that the `mailhog` is installed in the root.

### CODE REVIEW

**Comment by scissorsneedfoodtoo** [comment]
@varunzxzx, thank you for catching this and for your PR. You're right--when I uninstalled MailHog and tried reinstalling with the instructions in the guide I got an error about having to set the path for Go. I'll do some testing later and let's see how we can fix that section of the guide.

**Comment by scissorsneedfoodtoo** [comment]
@varunzxzx, just finished testing things out on my system. I really like the way you use echo to set the path for Go, and copy the binary to /usr/local/bin/mailhog to make it available everywhere on the system.

I just have a couple of suggestions for simplifying the instructions a bit. How about breaking up the instructions and commands like this:

Set the paths for Go:

```
echo 'export GOPATH=$HOME/go' >> ~/.profile
echo 'export PATH=$PATH:/usr/local/go/bin:$GOPATH/bin' >> ~/.profile
source ~/.profile
```

Then install and run MailHog:

```
go get github.com/mailhog/MailHog
sudo cp /home/$(whoami)/go/bin/MailHog /usr/local/bin/mailhog
mailhog
```

Note the additional echo command and the change to single quotes ('). The additional command is to make sure the path is set for Go in any alternate installation locations, just in case the user hasn't done so already. The single quote is to protect the string from interpretation by the shell. This isn't an issue with your original code, but more to prevent mine from converting to a really long $PATH value.

Other than that, everything LGTM!

**Comment by varunzxzx** [comment]
@scissorsneedfoodtoo Thanks for the suggestion. Looks good. I'll push the changes

**Comment by scissorsneedfoodtoo** [comment]
@varunzxzx, thank you making those changes. Everything LGTM!

**Review by raisedadead — APPROVED** [review]

**Pull request merged**
