### PR TITLE
chore(.devcontainer): update Dockerfiles

### PR DESCRIPTION
**Pull request by ShaunSHamilton**
Checklist:

- [x] I have read and followed the [contribution guidelines](https://contribute.freecodecamp.org).
- [x] I have read and followed the [how to open a pull request guide](https://contribute.freecodecamp.org/#/how-to-open-a-pull-request).
- [x] My pull request targets the `main` branch of freeCodeCamp.
- [x] I have tested these changes either locally on my machine, or Gitpod.

Changes to `.devcontainers`:

- Update Nodejs to 20
- Update Ubuntu to 22
- Avoid 60 second timeout during image build by using Nodejs-recommended method to install Nodejs

### CODE REVIEW

**Review by ojeytonwilliams — COMMENTED** [review]
These changes seem good, but if I try to start the container it fails. It tries to use `npm` to install and even `npm` itself isn't working.

If we're going to support devcontainers, I think we need the experience to require less troubleshooting. If not, we should just get rid of them.

Edit(after reading the issue): is this just a codespace thing? I tried using VSCode locally and ran into the problems I mentioned, is all. If it _is_ just intended to be for codespaces, can we update the docs?

**Comment by ShaunSHamilton** [comment]
> is this just a codespace thing?

That is why I added it to the repo. I did not think about running it locally.

> If it is just intended to be for codespaces, can we update the docs?

The docs don't mention Codespaces or using `.devcontainers` locally. So, do you mean to add a sentence about using the repo in Codespaces?

**Comment by ojeytonwilliams** [comment]
That should be enough, yeah. We go to some lengths to explain about Gitpod, so it feels like an odd omission that we don't even mention Codespaces.

**Comment by raisedadead** [comment]
FWIW, I see a notification about starting up the workspace in devcontainers when launching this repo in VSCode. 

Is it too much work to get support for it. If anything it would mean we could move away from local (native) support and just use containers

**Comment by ShaunSHamilton** [comment]
> Is it too much work to get it working and provide support for it

I will look into this.

**Comment by raisedadead** [comment]
Thanks a lot. Note that it doesn't have to be this PR.

**Review by raisedadead — APPROVED** [review]

**Pull request merged**
