### PR TITLE
chore(api-server): use unified topology

### PR DESCRIPTION
**Pull request by ShaunSHamilton**
With Nodejs driver <4, unified topology is not default, and can affect connection pool resolution

Checklist:

- [x] I have read and followed the [contribution guidelines](https://contribute.freecodecamp.org).
- [x] I have read and followed the [how to open a pull request guide](https://contribute.freecodecamp.org/how-to-open-a-pull-request/).
- [x] My pull request targets the `main` branch of freeCodeCamp.
- [x] I have tested these changes either locally on my machine, or GitPod.

### CODE REVIEW

**Comment by ojeytonwilliams** [comment]
Is the gist of this change that we don't need to `connect` any more and the client will automatically try to find a server if it loses connection?

**Comment by ShaunSHamilton** [comment]
> Is the gist of this change that we don't need to `connect` any more and the client will automatically try to find a server if it loses connection?

I am not sure I understand. We still need to connect, but, now, the topology is unified 😁 

Best I understand it is any one connection/request will no longer be tied to a specific replica 🤷‍♂️

**Comment by ojeytonwilliams** [comment]
Okay, fair enough. It looks like this should be a transparent change, but we should keep an eye on Sentry when we deploy this.

**Review by ojeytonwilliams — COMMENTED** [review]
> [MONGODB DRIVER] Warning: Current Server Discovery and Monitoring engine is deprecated, and will be removed in a future version. To use the new Server Discover and Monitoring engine, pass option { useUnifiedTopology: true } to the MongoClient constructor.

I still see this when I start the server in development. Any idea why?

**Comment by ShaunSHamilton** [comment]
> > [MONGODB DRIVER] Warning: Current Server Discovery and Monitoring engine is deprecated, and will be removed in a future version. To use the new Server Discover and Monitoring engine, pass option { useUnifiedTopology: true } to the MongoClient constructor.
> 
> I still see this when I start the server in development. Any idea why?

Not really. I also saw it, but in the database logs, the connection shows up as "unified".

**Comment by ShaunSHamilton** [comment]
> I am quite sure this is coming from the `connect-mongo` setup. See:
> 
> https://github.com/jdesboeufs/connect-mongo#connection-to-mongodb
> 
> and
> 
> https://github.com/freeCodeCamp/freeCodeCamp/blob/10da750534274f3050d55a7830832b8824892118/api-server/src/server/middlewares/sessions.js#L18

Should not be: https://github.com/jdesboeufs/connect-mongo/tree/v3.x?tab=readme-ov-file#more-options

It is the default.

**Comment by ojeytonwilliams** [comment]
Okay, this is quite silly, but what's happening is that loopback-connector-mongodb silently discards any options it doesn't understand. Version 4.2.0 (our version) doesn't know what `useUnifiedTopology` is, so it drops it. Version 5.5.0 keeps it.

**Comment by ShaunSHamilton** [comment]
> Anyways, this should work if we can upgrade to v5.

Should be possible:
> Please use the latest 5.x version in your LoopBack 3 applications.
> https://github.com/loopbackio/loopback-connector-mongodb?tab=readme-ov-file#supported-versions

**Comment by ShaunSHamilton** [comment]
Thanks, @ojeytonwilliams .

Looks better to me:

```bash
> @freecodecamp/api-server@0.0.1 develop /workspace/freeCodeCamp/api-server
> node src/development-start.js

Debugger listening on ws://0.0.0.0:9229/7a6ad6d6-39ef-4d33-9373-352f2001cf36
For help, see: https://nodejs.org/en/docs/inspector
  fcc:server:datasources using MailHog server on port 1025 +0ms
  fcc:models:user setting up user hooks +646ms
  fcc:server Sentry reporting disabled unless DSN is provided. +978ms
  fcc:server freeCodeCamp server listening on port 3000 in development +24ms
  fcc:server connecting to db at mongodb://127.0.0.1:27017/freecodecamp?directConnection=true +0ms
  fcc:boot:donate Donation disabled in development unless ALL test keys are provided +1ms
  fcc:server db connected +85ms
  fcc:boot:donate activeDonor count: 0 +18ms

```

**Review by raisedadead — APPROVED** [review]

**Review by ojeytonwilliams — APPROVED** [review]
This got rid of 

> [MONGODB DRIVER] Warning: Top-level use of w, wtimeout, j, and fsync is deprecated. Use writeConcern instead.

too :rocket:

**Pull request merged**
