### PR TITLE
chore(client): bump prisma to v5

### PR DESCRIPTION
**Pull request by Sboonny**
Checklist:

- [x] I have read and followed the [contribution guidelines](https://contribute.freecodecamp.org).
- [x] I have read and followed the [how to open a pull request guide](https://contribute.freecodecamp.org/#/how-to-open-a-pull-request).
- [x] My pull request targets the `main` branch of freeCodeCamp.
- [ ] I have tested these changes either locally on my machine, or GitPod.

in version 5, the used protocol is json by default, so we can remove the deprecated `previewfeature`

### CODE REVIEW

**Review by ojeytonwilliams — APPROVED** [review]
LGTM :+1:

**Comment by raisedadead** [comment]
> I have tested these changes either locally on my machine, or GitPod.

The OP says it hasn't been tested, @ojeytonwilliams can you confirm this is tested by you in the review, or do you want someone to?

**Comment by ojeytonwilliams** [comment]
I _think_ I checked it locally, but I'll double check.

**Comment by raisedadead** [comment]
Thanks - I will leave an approval, please merge if it is all good.

**Review by raisedadead — APPROVED** [review]

**Comment by ojeytonwilliams** [comment]
It's all looking good.

**Pull request merged**
