### PR TITLE
fix: only show loader message on layout

### PR DESCRIPTION
**Pull request by ojeytonwilliams**
Checklist:

- [x] I have read and followed the [contribution guidelines](https://contribute.freecodecamp.org).
- [x] I have read and followed the [how to open a pull request guide](https://contribute.freecodecamp.org/#/how-to-open-a-pull-request).
- [x] My pull request targets the `main` branch of freeCodeCamp.
- [x] I have tested these changes either locally on my machine, or GitPod.

No other `Loader` is passed `messageDelay` so they were all displaying the message immediately.

### CODE REVIEW

**Review by Sboonny — COMMENTED** [review]
it still shows the message, my advice is to move the message to intro and its logic there.

image

----

The component is trying to be smart about showing the message and delaying the spinner, but there is no reason for this.

There is only one place that need to show the message in, so we can have that place carry the logic and not worry about why it's happening.

delaying the spinner is similar case, but no issue is raised about it 🤷.

**Comment by ojeytonwilliams** [comment]
@Sboonny I thought that was what we were after, though. The message is supposed to appear if there's a delay getting the session user, but not if there's a delay getting the 'other'.

**Comment by Sboonny** [comment]
The url is navigating to the profile, which doesn't have a delay for the message or any delay set in it.

What am I misunderstanding? 🤔

**Review by raisedadead — APPROVED** [review]

**Comment by ojeytonwilliams** [comment]
> The url is navigating to the profile, which doesn't have a delay for the message or any delay set in it.

So, the layout loader (which shows the message) can always appear (on all non-certification pages).

This should only be shown while fetching the session user.

The other loader (without the message) shows if the first loader isn't being rendered while the other user is being fetched.

**Pull request merged**
