### PR TITLE
fix: broken tests in add-axes-to-a-visualization-challenge-in-d3 (Iss…

### LINKED ISSUE #35554: Broken Tests in Add Axes to a Visualization challenge in D3
**Describe your problem and how to reproduce it:**
Even though the following code:

```js
    svg.append("g")
      .attr("transform",  "translate(" + 60 + ", 0)")
      .call(yAxis);
```
places the Y-Axis at the right place, it doesn't pass the challenge:

image

**Add a Link to the page with the problem:**

https://www.freecodecamp.rocks/learn/data-visualization/data-visualization-with-d3/add-axes-to-a-visualization

### PR DESCRIPTION
**Pull request by Sumer16**
- [x] I have read [freeCodeCamp's contribution guidelines](https://github.com/freeCodeCamp/freeCodeCamp/blob/master/CONTRIBUTING.md).
- [x] My pull request has a descriptive title (not a vague title like `Update index.md`)
- [x] My pull request targets the `master` branch of freeCodeCamp.
- [x] None of my changes are plagiarized from another source without proper attribution.
- [x] All the files I changed are in the same world language (for example: only English changes, or only Chinese changes, etc.)
- [x] My changes do not use shortened URLs or affiliate links.

Closes #35554 

Fixed the Broken Tests in Add Axes to a Visualization Challenge in D3 opened by @thecodingaviator to resolve the issue #35554.

### CODE REVIEW

**Comment by thecodingaviator** [comment]
The files of this PR look fine, it'll still need to be tested locally though

**Review by cmccormack — APPROVED** [review]
This looks good to me 👍.   Tests passed locally.  Thank you for your contribution!

**Comment by Sumer16** [comment]
Thank You! @cmccormack for approving it.

**Review by thecodingaviator — APPROVED** [review]
LGTM! 👍

**Comment by thecodingaviator** [comment]
Thanks for contributing to the freeCodeCamp repository. Congratulations on your first PR! 🎊 

Look forward to more contributions from you! ✈️

**Comment by Sumer16** [comment]
Thank You so much! @thecodingaviator

**Pull request merged**
