### PR TITLE
fix: add info for problem 54 - project Euler

### PR DESCRIPTION
**Pull request by AdrianMuntean**
Checklist:

- [x] I have read [freeCodeCamp's contribution guidelines](https://contribute.freecodecamp.org).
- [x] My pull request has a descriptive title (not a vague title like `Update index.md`)
- [x] My pull request targets the `master` branch of freeCodeCamp.
- [x] All the files I changed are in the same world language, for example: only English changes, or only Chinese changes, etc.

[Problem 54](https://www.freecodecamp.org/learn/coding-interview-prep/project-euler/problem-54-poker-hands) has a vague input description. It doesn't mention the test case. 

Mentioning the test case is useful when someone wants to try out on their local machine, or in another programming language.

### CODE REVIEW

**Comment by RandellDawson** [comment]
Thank you for opening this pull request.

This is a standard message notifying you that we’ve reviewed your pull request and have decided not to merge it. We would welcome future pull requests from you.

Thank you and happy coding.

**Comment by AdrianMuntean** [comment]
Well, the problem is incomplete, you can't argue with that

**Comment by RandellDawson** [comment]
@AdrianMuntean You are correct.  It was my mistake in closing it.  However, instead of linking to the external file, maybe we can just state:
> The global array (`arr`) that will be passed to the function contains one-thousand string elements representing random hands dealt to two players. Each element of the array contains ten cards (separated by a single space): the first five are Player 1's cards and the last five are Player 2's cards. You can assume that all hands are valid (no invalid characters or repeated cards), each player's hand is in no specific order, and in each hand there is a clear winner.

**Comment by RandellDawson** [comment]
@AdrianMuntean Feel free to reopen and consider using the text I have suggested above.  Sorry for closing so quickly.

**Comment by AdrianMuntean** [comment]
@RandellDawson I couldn't re-open it caused I have removed the branch. I have created a new one https://github.com/freeCodeCamp/freeCodeCamp/pull/40057. I have updated with your suggestion. Thanks

**Pull request closed without merging**
