### PR TITLE
Fix text in image accessiblity in Bootstrap grid challenge

### LINKED ISSUE #10968: Picture of text not accessible for screen readers.
#### Browser Information

* Browser Name, Version: 
* Operating System: 
* Mobile, Desktop, or Tablet: 

#### Your Code

```js
 
 
 
```

### PR DESCRIPTION
**Pull request by systimotic**
#### Pre-Submission Checklist

- [x] Your pull request targets the `staging` branch of FreeCodeCamp.
- [x] Branch starts with either `fix/`, `feature/`, or `translate/` (e.g. `fix/signin-issue`)
- [x] You have only one commit (if not, [squash](http://forum.freecodecamp.com/t/how-to-squash-multiple-commits-into-one-with-git/13231) them into one commit).
- [x] All new and existing tests pass the command `npm run test-challenges`. Use `git commit --amend` to amend any fixes.
#### Type of Change

- [x] Small bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds new functionality)
- [ ] Breaking change (fix or feature that would change existing functionality)
- [ ] Add new translation (feature adding new translations)
#### Checklist:

- [x] Tested changes locally.
- [x] Closes currently open issue (replace XXXX with an issue no): Closes #10968
#### Description

As discussed in #10968, there is an accessibility issue in the challenge "Use the Bootstrap Grid to Put Elements Side By Side". This pull request fixes that issue by linking to the page that is the source of the image, instead of the original image. Screen readers will be able to read out the content.  
Happy coding!

### CODE REVIEW

**Comment by ltegman** [comment]
Thanks for the PR! Would you mind making this change in the translated versions as well?

**Comment by systimotic** [comment]
Oops, sorry about that @ltegman! I just updated it. I left the title of the image the same in French. I don't know enough French to change it. Technically it still enlarges what you see in the image when you click on it, so I don't think it's that big of a deal. The Spanish translation already had the title in English, so I updated that to the new English title.

**Comment by ltegman** [comment]
Perfect -- thank you! :tada:

**Comment by dhcodes** [comment]
@systimotic @ltegman not to be picky, but I think we should try to fix the translations while this was open. I also think the English text might be better as below:

English: "Click to view the Bootstrap grid documentation"

Spanish: "Haga clic para ver la documentación rejilla Bootstrap"

French: "Cliquez pour voir la documentation de la grille Bootstrap"

Now that it's merged, I'm not sure how hard it is to re-open so w/e.

**Comment by systimotic** [comment]
Sorry for taking so long to get back. @dhcodes Are these translations verified? As a non-native English speaker, I often prefer no translation over a poor translation 😅 In reality, by now I always prefer English over Dutch (my native language), but in that case I'm an exception. I'd be happy to submit a new PR with the fixed translations if we're sure they're correct.

**Comment by dhcodes** [comment]
Yeah, I verified with native speakers in the Gitter chat @systimotic

**Comment by systimotic** [comment]
Great! New PR incoming...

**Pull request merged**
