### PR TITLE
Fixing very minor grammatical error in ES6 challenge

### LINKED ISSUE #39820: Typo - ES6 Const Array Mutatation
**Describe your problem and how to reproduce it:**
In this challenge, there is a minor grammar issue.
> Change the array to [2, 5, 7] using various element assignment.

should say

> Change the array to [2, 5, 7] using various element assignments.

as "various" means the noun is plural.

**Add a Link to the page with the problem:**
https://www.freecodecamp.org/learn/javascript-algorithms-and-data-structures/es6/mutate-an-array-declared-with-const

**Tell us about your browser and operating system:**
N/A

**If possible, add a screenshot here (you can drag and drop, png, jpg, gif, etc. in this box):**
 
image

### PR DESCRIPTION
**Pull request by nick-w-nick**
Checklist:

- [x] I have read [freeCodeCamp's contribution guidelines](https://contribute.freecodecamp.org).
- [x] My pull request has a descriptive title (not a vague title like `Update index.md`)
- [x] My pull request targets the `master` branch of freeCodeCamp.
- [x] All the files I changed are in the same world language, for example: only English changes, or only Chinese changes, etc.

Closes #39820

Fixed a very small grammatical error to close out an issue.

**NOTES:**

- The issue was labeled with "first timers only" of which I am, as I have not previously made any contributions to the freeCodeCamp repo.
- I am making this contribution as part of the **Hacktoberfest 2020 event**, and would appreciate if the PR could be labeled as such with the `hacktoberfest-accepted` label.

Thanks!

### CODE REVIEW

**Review by naomi-lgbt — APPROVED** [review]
LGTM~! Congratulations on your first contribution! 🥳 

Please note that our workflow requires at least one additional approval before this may be merged.

**Review by andi73-bit — APPROVED** [review]

**Review by andi73-bit — APPROVED** [review]

**Comment by nick-w-nick** [comment]
@nhcarrigan / @andi73-bit  could you please add the `hacktoberfest-accepted` label to this PR so that I am able to get credit for it within the Hacktoberfest 2020 event?

I would very much appreciate it.

Thank you!

**Review by ShaunSHamilton — APPROVED** [review]
LGTM 👍 

Congrats on your first pull request (PR)! 🎉

Thank you for your contribution to the page! 👍
We are happy to accept these changes, and look forward to future contributions. 📝

**Comment by Sky020** [comment]
As far as I am aware, we did not opt in as a Hacktoberfest repo, and do not have such a label.

@raisedadead Any clarification about this?

**Pull request merged**
