### PR TITLE
feat: Escape hotkey enters 'navigation mode'

### LINKED ISSUE #37146: [Beta] Each time the n or p Hotkey is used, the editor refocuses on Windows
**Problem:** When tested on Chrome and Firefox (on Windows) and using the `p` or `n` hotkeys, we are supposed to be able to navigate to the next and previous lessons without the editor going back into focus while in the escaped mode. However, on the beta site, I have to keep escaping the editor every single time I click the `p` or `n` once I first escape the editor. The original navigation buttons that were removed in favor of the hot keys did not do this.

### PR DESCRIPTION
**Pull request by ojeytonwilliams**
- [x] I have read [freeCodeCamp's contribution guidelines](https://github.com/freeCodeCamp/freeCodeCamp/blob/master/CONTRIBUTING.md).
- [x] My pull request has a descriptive title (not a vague title like `Update index.md`)
- [x] My pull request targets the `master` branch of freeCodeCamp.
- [x] None of my changes are plagiarized from another source without proper attribution.
- [x] All the files I changed are in the same world language (for example: only English changes, or only Chinese changes, etc.)
- [x] My changes do not use shortened URLs or affiliate links.

Previously only 'escape'ing from the editor prevented auto focus on the editor, now you can 'escape' from anywhere that listens to Hotkeys.  Now, `n` and `p` can only be used to navigate after pressing `escape`, to prevent accidental navigation.

Also the outline for HotKeys is hidden as it is not used by tab navigation.

Closes #37146

### CODE REVIEW

**Comment by ojeytonwilliams** [comment]
@RandellDawson @thecodingaviator would you mind taking a look at this and let me know if it behaves how you expect?

**Comment by thecodingaviator** [comment]
I don't really think this is actually fixing the issue at hand at all. To reproduce the problem, just wait till the editor has loaded fully, after that, you'll encounter the same issue as we've discussed.

**Review by thecodingaviator — CHANGES_REQUESTED** [review]
See comment above

**Comment by ojeytonwilliams** [comment]
@thecodingaviator I had a chat with @RandellDawson and thought that it would be more intuitive if the navigation is disabled until you press escape, regardless of what's currently in focus.  So, the new behaviour would be:

Normal behaviour:
1) Press n or p
2) It doesn't navigate

To trigger navigation mode:
1) Press escape
2) Press n or p
3) It navigates to the next or previous challenge
4) Click on the editor
5) You're back in normal mode.

The idea being accidentally navigating is frustrating, particularly if you can't immediately navigate back.  Does that seem reasonable?

**Comment by thecodingaviator** [comment]
@ojeytonwilliams That sounds good to me

**Comment by thecodingaviator** [comment]
I like the new way we're doing things but I think it'll be good if clicking on the instructions panel also enters nav mode. What do you think @RandellDawson ?

**Comment by ojeytonwilliams** [comment]
I think it's better if we make navigation mode something you have purposefully activate.  If clicking on the instructions triggered it, that could easily happen by accident.

**Comment by RandellDawson** [comment]
> I like the new way we're doing things but I think it'll be good if clicking on the instructions panel also enters nav mode. What do you think @RandellDawson ?

The problem I saw with clicking on the instructions activating navigation mode, is if you were working on a challenge in the editor and wanted to copy/paste something from the instructions or just accidentally clicked on the instructions (for whatever reason), then all the sudden you are in navigation mode and would not expect it.  You could inadvertently end up navigating away from the challenge you were working on.   @ojeytonwilliams and I discussed it for a while yesterday and concluded that navigation mode should be a very deliberate action taken by the user.

**Review by RandellDawson — APPROVED** [review]

**Comment by thecodingaviator** [comment]
That sounds reasonable

**Review by thecodingaviator — APPROVED** [review]

**Comment by RandellDawson** [comment]
@freeCodeCamp/dev-team Just need someone from the dev team to review now.

**Review by raisedadead — APPROVED** [review]

**Pull request merged**
