### PR TITLE
fix(show): add solutions view

### PR DESCRIPTION
**Pull request by raisedadead**
I have added a modal, on lines of @Bouncey 's work from the beta, and this should let us tackle the complaints by re-enabling viewing solutions on the production.

Please note, lets take #16740 first before merging this.

image

### CODE REVIEW

**Comment by raisedadead** [comment]
I did not bother, taking care of any syntax-highlighting, considering all this change are going away when we ship beta.

This should at least be of some relief to the users.

**Comment by QuincyLarson** [comment]
@raisedadead Great - thanks for making this. From a UX perspective this looks good and is clearly an improvement. I'll defer to @BerkeleyTrue for feedback on how you implemented this.

**Comment by Bouncey** [comment]
My understanding was that master is on a feature freeze?

**Comment by raisedadead** [comment]
Yes, @Bouncey that is correct, but going by the forum and the chat rooms, the regression that we introduced with https://github.com/freeCodeCamp/freeCodeCamp/pull/16552 is quite inconvenient to the the users on the production, before we are able to launch beta.

**Comment by QuincyLarson** [comment]
@raisedadead Awesome - thanks for fixing this!

**Pull request merged**
