### PR TITLE
Update for Map.less

### PR DESCRIPTION
**Pull request by TylerDelRosario**

### CODE REVIEW

**Comment by bugron** [comment]
Unfortunately, your PR has conflicts. Please, `rebase` staging branch on top of it, resolve conflicts and `force` push your PR back to your fork. https://github.com/FreeCodeCamp/FreeCodeCamp/wiki/git-rebase

**Comment by HTMLNoob** [comment]
Do I need to install github desktop? If i do I wont be able to since I have windows xp.

**Comment by bugron** [comment]
I don't think it's necessary to install GitHub desktop. Git Bash (I means command line version) will do the work.

**Comment by HTMLNoob** [comment]
ok, thank you bugron.

**Comment by HTMLNoob** [comment]
Ok, I just cloned my fork. Now, do I just type in the code solution you pointed to?

**Comment by HTMLNoob** [comment]
I'm sorry for any inconvenience bugron.

**Comment by bugron** [comment]
Oh, we were making changes using GitHub's web interface. Do you know how Git works?

**Comment by bugron** [comment]
But you have to close this PR, make the changes in your local fork then push your branch to your remote fork and then open a new PR.

**Comment by SaintPeter** [comment]
If you're having trouble or need a hand, we have a help room: [HelpContributors](https://gitter.im/FreeCodeCamp/HelpContributors)

**Comment by HTMLNoob** [comment]
oh cool I'll go there

**Pull request closed without merging**
