### PR TITLE
fix(map): Render superBlock titles on initial render

### LINKED ISSUE #16317: Fix map loading UI
Currently while the map loads it looks like this: 

learn_to_code___freecodecamp

Instead, we should show the spinner in the upper middle of that pane until it's fully loaded. This will communicate that the map is still loading, and will prevent people from clicking anything (which can potentially break the app at this point).

@BerkeleyTrue @Bouncey @raisedadead I consider this a must-fix before shipping beta. If you don't have time to significantly improve the performance of the map, I think using a spinner is our best option.

### PR DESCRIPTION
**Pull request by Bouncey**
#### Pre-Submission Checklist

- [x] Your pull request targets the `staging` branch of freeCodeCamp.
- [x] Branch starts with either `fix/`, `feature/`, or `translate/` (e.g. `fix/signin-issue`)
- [x] You have only one commit (if not, [squash](http://forum.freecodecamp.org/t/how-to-squash-multiple-commits-into-one-with-git/13231) them into one commit).
- [x] All new and existing tests pass the command `npm test`. Use `git commit --amend` to amend any fixes.

#### Type of Change

- [x] Small bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds new functionality)
- [ ] Breaking change (fix or feature that would change existing functionality)
- [ ] Add new translation (feature adding new translations)

#### Checklist:

- [x] Tested changes locally.
- [x] Addressed currently open issue (replace XXXXX with an issue no in next line)

Closes #16317 

#### Description

Send superBlock data with firstChallenge

### CODE REVIEW

**Comment by raisedadead** [comment]
Related: https://github.com/freeCodeCamp/freeCodeCamp/issues/15972

**Comment by systimotic** [comment]
Looks like this works really well. Should @BerkeleyTrue review?

**Comment by BerkeleyTrue** [comment]
Code LGTM

**Comment by BerkeleyTrue** [comment]
Works! Nice job @Bouncey on finding a simple solution

**Pull request merged**
