### PR TITLE
fix(client): SASS - show error messages instead of timeout

### LINKED ISSUE #39432: Sass challenge timeout
**Describe the bug**
Sass pages with invalid syntax occasionally timeout

**To Reproduce**
1. Go to https://www.freecodecamp.org/learn/front-end-libraries/sass/store-data-with-sass-variables
2. Paste in 
```
<style type='text/scss'>
$text-color: red;

  .header{
    text-align: center;
  }
  .blog-post, h2 {
    color: $text-color;

</style>
```
3. See `timeout` in the console (sometimes)

**Expected behavior**

The following should appear in the console:
```
Error: Invalid CSS after "...r: $text-color;": expected "}", was ""
        on line 8:24 of /stdin
>>     color: $text-color;
```

Since this is intermittent, here's a gif to demonstrate:

SassTimeout

**Additional Context**

When the error appears it does so very quickly, so it is unlikely that this is due to a genuine timeout.

### PR DESCRIPTION
**Pull request by jacob-oreilly**
Checklist:

- [x] I have read [freeCodeCamp's contribution guidelines](https://contribute.freecodecamp.org).
- [x] My pull request has a descriptive title (not a vague title like `Update index.md`)
- [x] My pull request targets the `main` branch of freeCodeCamp.
- [x] I have tested these changes either locally on my machine, or GitPod.

Closes #39432

I don't know if this totally closes #39432. I was just fixing the issue the last comment in the issue had pointed out which was
that it wasn't displaying a better error message than the timeout default error in the console. 

I also found out that the main cause for the timeout is happening in execute-challenge-saga.js inside of the previewChallengeSage function. I noticed that getting rid of the delay did help significantly but then was updating the console consistently and from my understanding is not the desired effect. 

I just wanted to point out that's where the timeout is originating from and not sure if the this issue was being held open because of the error message needed to be handled better or if there still needs to be a fix for this.

### CODE REVIEW

**Comment by ojeytonwilliams** [comment]
Hi @jacob-oreilly thanks for looking into this.

> not sure if the this issue was being held open because of the error message needed to be handled better or if there still needs to be a fix for this.

Ideally it should be fixed, so if you've got some ideas about how to do that, that's great!  If not, then we should just tell people what's wrong and how to fix it.

**Comment by raisedadead** [comment]
@ojeytonwilliams 

I have gone ahead and assigned this to you to help resolve the merge conflict in this PR due to recent Lerna changes and also give this a review while you are at it. 

Thanks.

**Comment by raisedadead** [comment]
I am auditing PRs in limbo. @ojeytonwilliams mind taking a look?

**Comment by ojeytonwilliams** [comment]
I was going to clean this up, but I realised that the error message would have to be "Something went wrong, here's a hack to fix it...". That didn't feel great.  So, I went down the rabbit hole and fixed the bug.

@jacob-oreilly made a nice improvement, giving us a better error than 'timeout', so I'd be happy to accept that change.

Since this is a bit stale :cold_sweat: I'll sort that out myself.

**Review by raisedadead — APPROVED** [review]

**Review by naomi-lgbt — APPROVED** [review]
The SASS bug is fixed, but I believe `timeout` can be thrown elsewhere.
Regardless, good to have this fix in.

**Comment by ojeytonwilliams** [comment]
Yep, it's there as a fallback in case something weird happens.

**Pull request merged**
