### PR TITLE
Added additional information about the <i>element, campers were asking...

### PR DESCRIPTION
**Pull request by iheartkode**
Waypoint Add Font Awesome Icons to all of our Buttons
I made it a bit clearer by informing users of the <i> tag

### CODE REVIEW

**Comment by SaintPeter** [comment]
I would add an actual example of using another FA icon.

**Comment by iheartkode** [comment]
@SaintPeter  There is already one before the text I added??

**Comment by SaintPeter** [comment]
@iheartkode I'm talking about `<i class="fa fa-thumb-up"></i>` as opposed to just a bare `<i></i>`.

**Comment by iheartkode** [comment]
@SaintPeter Ahh I see, I will change it
How can i change it but keep the same pr or do I need to close it?

**Comment by SaintPeter** [comment]
If you change your local files and then do a `git commit --amend`, then `git push --force` it will push out a new commit.

Which it looks like you did?

**Comment by SaintPeter** [comment]
You do not need to do a new PR.

**Comment by iheartkode** [comment]
@SaintPeter thanks

**Comment by SaintPeter** [comment]
ok, it looks like you didn't amend your commit, so now you need to rebase to squash the commits.

Do `git rebase -i HEAD^^` and change the second commit to "Squash".
Then push it up again.

More on Git Rebase:
https://github.com/FreeCodeCamp/FreeCodeCamp/wiki/git-rebase

**Comment by iheartkode** [comment]
@SaintPeter check pm on gitter please

**Pull request closed without merging**
