### PR TITLE
feat(i18n): enable italian new RWD

### PR DESCRIPTION
**Pull request by Dario-DC**
Checklist:

- [x] I have read [freeCodeCamp's contribution guidelines](https://contribute.freecodecamp.org).
- [x] My pull request has a descriptive title (not a vague title like `Update index.md`)
- [x] My pull request targets the `main` branch of freeCodeCamp.
- [ ] I have tested these changes either locally on my machine, or GitPod.

Closes #XXXXX

I have not been able to test as during the build process I got this error

```
  Error: Missing italian audited challenge for
  14-responsive-web-design-22/learn-css-grid-by-building-a-magazine/6148d4d57b965358c9fa38bf.md
  No audited challenges should fallback to English.
```

### CODE REVIEW

**Comment by raisedadead** [comment]
@oliver can you help validate this, and recommend changes if needed? Thanks :)

**Comment by ojeytonwilliams** [comment]
@raisedadead we discussed this in chat and Dario's confirmed that the latest crowdin download should fix this.

The error itself *is* useful, since we don't want to accidentally show people English challenges, but it's confusing. I'll try and come up with a better approach.

**Comment by raisedadead** [comment]
> the latest crowdin download should fix this.

OK - so this PR should wait for the main branch to get the latest downloads and we can then go ahead with merging and deploying this?

**Comment by ojeytonwilliams** [comment]
That's right.  It's worth doing a quick build locally to check, but it should be fine.

**Review by majestic-owl448 — APPROVED** [review]

**Comment by ieahleen** [comment]
LGTM :+1:

Il build locally fine now that the translation is merged 

Responsive Web Design 2022 is 100% approved
image

**Review by raisedadead — APPROVED** [review]

**Pull request merged**
