### PR TITLE
fix(nav): Apply correct classes and style to nav profile

### LINKED ISSUE #16168: [beta] Fix the UI of the static Public Profile
We are doing a overhaul for the public profile page by a upgrading them to react pages.
Refer: https://github.com/freeCodeCamp/freeCodeCamp/issues/15942
Refer: https://github.com/freeCodeCamp/freeCodeCamp/issues/15729

But, while that is deferred to until after the release of beta, we want fixes to the currently broken UX on the setting page which is a static server rendered page available here:

https://github.com/freeCodeCamp/freeCodeCamp/blob/staging/server/views/account/show.jade

As of this issue post it renders like so:
profile

### PR DESCRIPTION
**Pull request by onelharrison**
Closes #16168

#### Pre-Submission Checklist

- [x] Your pull request targets the `staging` branch of freeCodeCamp.
- [x] Branch starts with either `fix/`, `feature/`, or `translate/` (e.g. `fix/signin-issue`)
- [x] You have only one commit (if not, [squash](http://forum.freecodecamp.org/t/how-to-squash-multiple-commits-into-one-with-git/13231) them into one commit).
- [x] All new and existing tests pass the command `npm test`. Use `git commit --amend` to amend any fixes.

#### Type of Change

- [x] Small bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds new functionality)
- [ ] Breaking change (fix or feature that would change existing functionality)
- [ ] Add new translation (feature adding new translations)

#### Checklist:

- [x] Tested changes locally.
- [x] Addressed currently open issue (replace XXXXX with an issue no in next line)

Closes #16168 

#### Description

I applied the correct classes to the "nav profile" elements and added a `height:0` style to the fix a height inconsistency that became apparent when I hovered over the nav profile image.

### CODE REVIEW

**Comment by raisedadead** [comment]
Hi, @onelharrison this fixes the Nav bar. Thanks for the changes.

Can you also, check the accounts/show.jade and add the correct classes?

On production:

production

On staging:

staging

That should make this ready for a merge.

**Review by raisedadead — CHANGES_REQUESTED** [review]
Need styling changes on show.jade as well

**Comment by onelharrison** [comment]
@raisedadead, I'll get right on it.

**Comment by raisedadead** [comment]
Nicely done @onelharrison great work! Thanks.

**Comment by matjack1** [comment]
@raisedadead I think this PR has broken the content of the homepage. Currently the rows are overflowing the window area.

I've fixed that in my fork here: https://github.com/freeCodeCamp/freeCodeCamp/compare/staging...matjack1:fix/missing-container shall I open a PR for that? Do I need to open an issue first? Thanks!

**Comment by raisedadead** [comment]
@matjack1 oh yes, you are right. I completely missed the change was to a `layout.jade`.

Yes, please make a PR directly (PRs are also issue threads)

Finally, instead of the change what you have right now, lets add back the original change on the layout.jade

```diff
+    .container
-    .app-content.app-centered
```

and think of a different fix for the `show.jade`

**Comment by raisedadead** [comment]
On `show.jade`

we should have this

```diff
 block content
     include ../partials/flyer
+    .app-content.app-centered
     script.
         var challengeName = 'Profile View';
```

**Comment by raisedadead** [comment]
@matjack1 it would be awesome if you can make this change, and raise a pull request. Thanks a lot for catching this.

**Comment by matjack1** [comment]
thanks @raisedadead I'll do 👍

**Comment by matjack1** [comment]
sorry @raisedadead about your suggestion on `show.jade`, the `.app-content.app-centered` div should contain everything else in the page, or just add the margin at the top? It's fine to leave that empty?

**Comment by raisedadead** [comment]
Yes, you should just insert the line in green in the snippet between the existing code lines.

**Pull request merged**
