### PR TITLE
fix(ui): whitespacing and re-arrange footer

### LINKED ISSUE #35232: [beta] remove <hr>'s above footer?
In my opinion, I don't like the hr's above the footer - specifically on the curriculum page, but it might look better without it all around. It just looks a little out of place or something to me.

screen shot 2019-02-15 at 10 36 43 am
screen shot 2019-02-15 at 10 36 14 am

### PR DESCRIPTION
**Pull request by raisedadead**
Not the original intention for but Closes #35232

### CODE REVIEW

**Comment by raisedadead** [comment]
This PR re-arranges the layout slightly using whitespace to make it hopefully better.


image

**Comment by thecodingaviator** [comment]
@raisedadead The whitespace above and below the buttons is not equal, the bottom side has a bit more of it:
image

**Comment by raisedadead** [comment]
Hi @thecodingaviator 

Thanks for the feedback.

> The whitespace above and below the buttons is not equal, the bottom side has a bit more of it.

Yep, it's a side-effect (for now). The tool panel (buttons) is balanced in the viewport and the other panels with this PR. 

Balancing it between the footer and the panels involves adding one more selector specific to the `hr` on this component that will add `4px` below the footer. Its a bit hacky for the nitpick IMHO.

Let's leave this one for now while we are re-arranging the view itself to be more functional. Feel free to log an issue once this lands though.

**Comment by raisedadead** [comment]
Hey @freeCodeCamp/dev-team I have had some discussion with Quincy about the layout. So, I am going to block this PR for now. 

We have some thoughts on the approach for the UI. So I'll open a fresh PR that reverts some of the recent layout changes as well.

In short we are going to be aiming for the single column like layout after master's release.

**Comment by ahmadabdolsaheb** [comment]
looking forward to it

**Pull request closed without merging**
