### PR TITLE
Remove unnecessary whitespace from array

### PR DESCRIPTION
**Pull request by jasperpilgrim**
Checklist:

- [x] I have read [freeCodeCamp's contribution guidelines](https://contribute.freecodecamp.org).
- [x] My pull request has a descriptive title (not a vague title like `Update index.md`)
- [x] My pull request targets the `master` branch of freeCodeCamp.
- [x] All the files I changed are in the same world language, for example: only English changes, or only Chinese changes, etc.

### CODE REVIEW

**Comment by RandellDawson** [comment]
Thank you for opening this pull request.

This is a standard message notifying you that we’ve reviewed your pull request and have decided not to merge it. We would welcome future pull requests from you.

Thank you and happy coding.

**Comment by jasperpilgrim** [comment]
Does something break if the whitespace is removed?

**Comment by RandellDawson** [comment]
No, but the change is not really necessary as it is never seen.  The only thing the solution is for is to run the challenge tests against.

**Comment by jasperpilgrim** [comment]
Aha, thanks. I did a quick ctrl + f and didn't realize I edited the solution instead of the seed. Cheers.

**Pull request closed without merging**
