### PR TITLE
Add language routing

### PR DESCRIPTION
**Pull request by BerkeleyTrue**

### CODE REVIEW

**Comment by QuincyLarson** [comment]
@BerkeleyTrue I can change my preferred language to Spanish, but it doesn't affect the language of the challenges.

**Comment by bugron** [comment]
Here is what I see both in Firefox and Chrome respectively (even if I select something):


When I change the language the map is still in English

And I think we should change "Preferred language" to "Preferred language of challenges" because one can thought that changing the lang will change everything but it actually changes only challenge seed's language.
And for future approach I think it would be better to have test messages translated too.

**Comment by BerkeleyTrue** [comment]
I'll work on the map.

> And I think we should change "Preferred language" to "Preferred language of challenges"

We're asking when language they preferred. I don't think we need the extra qualifier.

**Comment by BerkeleyTrue** [comment]
Added language support on maps. Superblocks/blocks will need title translations as well, but we'll cross that bridge at some other point

**Comment by BerkeleyTrue** [comment]
I'll leave the select css stuff to someone with more skills than I, like @hallaathrad.

**Comment by BerkeleyTrue** [comment]
Still need to figure out why React stuff keeps cycling.

**Comment by BerkeleyTrue** [comment]
Live on Beta

**Comment by QuincyLarson** [comment]
LGTM.

**Comment by QuincyLarson** [comment]
OK - I've found a couple issues:

- If I'm unauthenticated and I complete a challenge, it will send me to the map and say "We couldn't find a challenge with the name next-challenge. Please double check the name."
- If I'm authenticated and I complete a challenge with Spanish as my language, it will never advance to the next challenge (it shows the spinner forever).

**Comment by BerkeleyTrue** [comment]
@QuincyLarson fixed

**Comment by ltegman** [comment]
@BerkeleyTrue It saves challenges to the user object with the translated name, so if someone completes a challenge in spanish anyone who visits that profile will see the name in spanish rather than english, and because the spanish version of the name is not a valid URL they will get an error like `We couldn't find a challenge with the name Borra elementos HTML. Please double check the name.` when trying to visit the solution from the link profile link.

**Comment by BerkeleyTrue** [comment]
@ltegman Thanks. We'll definitely need to incorporate language routing into find next challenge. I guess we'll need to parse the lang from the url and search the appropriate language name.

**Comment by ltegman** [comment]
@BerkeleyTrue I don't know how practical this is but is there any chance we can store the challenge with the english name in the user object and translate what is shown on the user profile? Seems like saving it in a consistent fashion and translating from there would have less potential side effects on things like challenge validation for certs and mean all our users can easily view each others challenges regardless of the language the user completed the challenge in.

**Comment by BerkeleyTrue** [comment]
@ltegman I've actually been thinking of creating a id => name map to use on profiles. This would solve other issue's were having with the profile and always keep the names up to date. We could make a map per language.

**Comment by ltegman** [comment]
@BerkeleyTrue That sounds like an excellent solution for this!

**Comment by vtamara** [comment]
I cannot test in http://beta.freecodecamp.com/es

**Comment by BerkeleyTrue** [comment]
@vtamara I've since taken it down from beta. I'll put it back up when I fix the issue reported by @ltegman

**Comment by vtamara** [comment]
Thank you

**Comment by bugron** [comment]
@BerkeleyTrue, please, rebase.

**Comment by BerkeleyTrue** [comment]
I'll be doing this on the react side

**Pull request closed without merging**
