### PR TITLE
Added solution to remove-whitespace-from-start-and-end.english.md

### PR DESCRIPTION
**Pull request by Hiyorimi**
- [x] I have read [freeCodeCamp's contribution guidelines](https://github.com/freeCodeCamp/freeCodeCamp/blob/master/CONTRIBUTING.md).
- [x] My pull request has a descriptive title (not a vague title like `Update index.md`)
- [x] My pull request targets the `master` branch of freeCodeCamp.
- [x] None of my changes are plagiarized from another source without proper attribution.
- [x] All the files I changed are in the same world language (for example: only English changes, or only Chinese changes, etc.)
- [x] My changes do not use shortened URLs or affiliate links.

### CODE REVIEW

**Comment by RandellDawson** [comment]
@Hiyorimi You must paste a full solution which includes all of the original challenge seed code plus the additions/changes which allow the solution to pass.  You only added a single line of code.  There should be a total of 3 lines of code.

**Comment by Hiyorimi** [comment]
Updated the code, thank you for the comments!

**Review by RandellDawson — APPROVED** [review]

**Comment by RandellDawson** [comment]
Congrats @Hiyorimi on your first pull request (PR)! 🎉

Thank you for your contribution to the page! 👍
We're happy to accept these changes, and look forward to future contributions. 📝

**Comment by Hiyorimi** [comment]
Thank you! Glad to make small contribution for such a great project!

**Pull request merged**
