### PR TITLE
Updated problem example to a working implementation matching the solution style 

### PR DESCRIPTION
**Pull request by dchenmei**
- [x] I have read [freeCodeCamp's contribution guidelines](https://github.com/freeCodeCamp/freeCodeCamp/blob/master/CONTRIBUTING.md).
- [x] My pull request has a descriptive title (not a vague title like `Update index.md`)
- [x] My pull request targets the `master` branch of freeCodeCamp.
- [x] None of my changes are plagiarized from another source without proper attribution.
- [x] All the files I changed are in the same world language (for example: only English changes, or only Chinese changes, etc.)
- [x] My changes do not use shortened URLs or affiliate links.

### CODE REVIEW

**Review by theNaut1lus — CHANGES_REQUESTED** [review]
It is Requested that you do not edit out previously added solutions/examples by other contributors, if there is another solution/example you would like to propose then add it below the original as a another perspective to the same problem

**Comment by RandellDawson** [comment]
@co16353sidak Actually, the user is correcting the existing solution.  The existing solution no longer works in latest version of Chrome. The solution now follows the standard in which you must specify what happens for the 3 possible cases (a < b, a > b, and a === b).

**Comment by dchenmei** [comment]
@co16353sidak  @RandellDawson 

Exactly, the current solution is outdated and needs to be updated.

**Comment by RandellDawson** [comment]
Congrats @dchenmei on your first pull request (PR)! 🎉

Thank you for your contribution to the page! 👍
We're happy to accept these changes, and look forward to future contributions. 📝

**Pull request merged**
