### PR TITLE
feat(challenges): Added more assertion for Project Euler problem twe

### PR DESCRIPTION
**Pull request by alvinkl**
#### Pre-Submission Checklist

- [x] Your pull request targets the `staging` branch of freeCodeCamp.
- [x] Branch starts with either `fix/`, `feature/`, or `translate/` (e.g. `fix/signin-issue`)
- [x] You have only one commit (if not, [squash](http://forum.freecodecamp.com/t/how-to-squash-multiple-commits-into-one-with-git/13231) them into one commit).
- [x] All new and existing tests pass the command `npm test`. Use `git commit --amend` to amend any fixes.

#### Type of Change

- [ ] Small bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds new functionality)
- [ ] Breaking change (fix or feature that would change existing functionality)
- [ ] Add new translation (feature adding new translations)

#### Checklist:

- [x] Tested changes locally.
- [ ] Closes currently open issue (replace XXXX with an issue no): Closes #XXXX

#### Description

Added more assertion for Project Euler Problem 23
Here's the JS solution
```javascript
function sumOfNonAbundantNumbers(n) {
	const getFactors = number => {
		let factors = [];

		let possibleFactor = 1;
		let sqrt = Math.sqrt(number);

		while (possibleFactor <= sqrt) {
			if (number % possibleFactor == 0) {
				factors[factors.length] = possibleFactor;

				let otherPossibleFactor = number / possibleFactor;
				if (otherPossibleFactor > possibleFactor)
					factors[factors.length] = otherPossibleFactor;
			}
			possibleFactor++;
		}

		return factors;
	};

	const getAbundantNumbers = upperLimit => {
		let abundantNumbers = [];
		for (let i = 12; i <= upperLimit; i++) {
			let factors = getFactors(i);
			let factorSum = 0;
			for (let factor, j = 0; (factor = factors[j]); j++)
				if (i != factor) factorSum += factor;

			if (factorSum > i) {
				abundantNumbers.push(i);
			}
		}
		return abundantNumbers;
	};

	var abundantNumbers = getAbundantNumbers(n);

	var sum = 0;

	for (var testNum = 1; testNum <= n; testNum++) {
		var sumOfAbundant = false;
		for (
			var i = 0, j = abundantNumbers.length - 1, abundantNumber1;
			(abundantNumber1 = abundantNumbers[i]);
			i++
		) {
			if (abundantNumber1 > testNum) {
				break;
			}

			var abundantNumber2 = abundantNumbers[j];
			while (j > 0 && abundantNumber1 + abundantNumber2 > testNum) {
				abundantNumber2 = abundantNumbers[--j];
			}

			if (abundantNumber1 + abundantNumber2 == testNum) {
				sumOfAbundant = true;
				break;
			}
		}
		if (!sumOfAbundant) {
			sum += testNum;
		}
	}

	return sum;
}
```

### CODE REVIEW

**Comment by beaucarnes** [comment]
@alvinkl The solution you included currently does not work. Can you update the solution so we can verify your assertions are correct. Thanks!

**Comment by alvinkl** [comment]
Hi @beaucarnes, thanks for reviewing my code, but can you tell me how it doesn't work?

**Comment by beaucarnes** [comment]
After rechecking this, I realized the error I was getting was about a potential infinite loop. I added `// noprotect` at the beginning of your code to disable infinite loop protection. Then, the challenge passed. So this looks good! Thanks for doing this one.

**Comment by alvinkl** [comment]
@beaucarnes I think it's due to that huge number that the problem asked. Thank you for taking time to check my code :D

**Pull request merged**
