### PR TITLE
fix: Remove and update challenges with legacy methods

### LINKED ISSUE #36381: Dealing with legacy lifecycle methods
As mentioned in https://github.com/freeCodeCamp/freeCodeCamp/pull/35894 and https://github.com/freeCodeCamp/freeCodeCamp/pull/35895#issuecomment-508145165 there are still challenges that use legacy React lifecycle methods.

Let's discuss what we should do with those challenges.

Personally, I think [the challenge](https://learn.freecodecamp.org/front-end-libraries/react/manage-updates-with-lifecycle-methods/) that uses them should simply be removed.  Quoting the [React blog](https://reactjs.org/blog/2018/03/27/update-on-async-rendering.html):
> some of our legacy component lifecycles tend to encourage unsafe coding practices

So, not something we need to teach.

The other [challenge](https://learn.freecodecamp.org/front-end-libraries/react/optimize-re-renders-with-shouldcomponentupdate/) has `componentWillReceiveProps`, but it is not integral to the challenge.  If the method is removed, I think that challenge will be fine.

### PR DESCRIPTION
**Pull request by ojeytonwilliams**
- [x] I have read [freeCodeCamp's contribution guidelines](https://github.com/freeCodeCamp/freeCodeCamp/blob/master/CONTRIBUTING.md).
- [x] My pull request has a descriptive title (not a vague title like `Update index.md`)
- [x] My pull request targets the `master` branch of freeCodeCamp.
- [x] None of my changes are plagiarized from another source without proper attribution.
- [x] All the files I changed are in the same world language (for example: only English changes, or only Chinese changes, etc.)
- [x] My changes do not use shortened URLs or affiliate links.

This removes the challenge that teaches the legacy methods and updates the challenge that was using one, but did not need to be.

Closes #36381

### CODE REVIEW

**Review by thecodingaviator — APPROVED** [review]
LGTM

**Review by jonathan-grah — APPROVED** [review]
#### LGTM, tested locally and reviewed changes to curriculum 👍

**Review by jonathan-grah — CHANGES_REQUESTED** [review]
@ojeytonwilliams, shouldn't the challenge in other languages be removed, as well as the corresponding guide article be removed?

**Comment by RandellDawson** [comment]
> @ojeytonwilliams, shouldn't the challenge in other languages be removed, as well as the corresponding guide article be removed?

@jonathan-grah It does not matter, because all of the non-English languages for the current curriculum are never going to be put into production and the guide which is going to be ported over to the forum is only going to include solutions from existing challenges in the curriculum.

**Comment by RandellDawson** [comment]
There is an earlier PR with changes to `curriculum/challenges/english/03-front-end-libraries/react/manage-updates-with-lifecycle-methods.english.md`.

**Comment by ojeytonwilliams** [comment]
Fixed the latest merge conflict.

**Review by raisedadead — APPROVED** [review]

**Review by RandellDawson — APPROVED** [review]

**Comment by RandellDawson** [comment]
@jonathan-grah Can you please approve/merge this PR?

**Comment by ojeytonwilliams** [comment]
Actually, please don't merge this just yet.  https://github.com/freeCodeCamp/freeCodeCamp/pull/35894 should be merged first.

**Comment by ojeytonwilliams** [comment]
With #36444 merged and the conflict fixed, this is ready to be QA'd.  @jonathan-grah if you're happy with this, could you merge it?

**Review by jonathan-grah — APPROVED** [review]

**Comment by jonathan-grah** [comment]
### LGTM 👍

Thanks @ojeytonwilliams 😃

**Pull request merged**
