### PR TITLE
fix(curriculum): put a verb in singular by removing a letter

### PR DESCRIPTION
**Pull request by JoseDeFreitas**
Checklist:

- [x] I have read [freeCodeCamp's contribution guidelines](https://contribute.freecodecamp.org).
- [x] My pull request has a descriptive title (not a vague title like `Update index.md`)
- [x] My pull request targets the `main` branch of freeCodeCamp.
- [x] I have tested these changes either locally on my machine, or GitPod.

I didn't test this change as the fourth point says because I don't think it's necessary (very small change in a Markdown file).

### CODE REVIEW

**Comment by ShaunSHamilton** [comment]
Hello there,

Please edit this PR title to match our recommended title format: https://contribute.freecodecamp.org/#/how-to-open-a-pull-request

**Comment by ieahleen** [comment]
As a new contributor, we encourage you to read our contributing guidelines. 

We expect our contributors to be aware of the process specific to this project. Following the guidelines religiously earns you the respect of fellow maintainers and saves everyone time.

Some examples of this are:

1. Make sure you are not editing off of GitHub (while you can, it's not a good idea).
2. Makes sure you actually follow the PR checklist and not just tick things off; we won't take you seriously otherwise.
3. Use the correct way to link PRs in the description of the PR by updating the `XXXXXX`.
4. ... and similar things.

We appreciate you taking the time to help us, and we hope to see more contributions from you.

Cheers & Happy Coding!

**Comment by JoseDeFreitas** [comment]
Hello, @ShaunSHamilton and @ieahleen. Foremost, I want to apologise for checking those two checks when I hadn't read the entire guidelines (I had only read the [main page](https://contribute.freecodecamp.org/#/index) and [this one](https://contribute.freecodecamp.org/#/how-to-work-on-coding-challenges)) and hadn't written the title of the pull request correctly.

As stated in the [FAQ](https://contribute.freecodecamp.org/#/FAQ), when it comes to fixing a typo, I can open a pull request right away; to explain more about my change, I basically removed a "s" from the verb as the substantive is in plural.

I read the main pages of the guidelines and the ones regarding a change like this, fixed the title of the pull request and tested the change using the link Gitpod generated, so I have checked all the checks in my original message.

**Review by ShaunSHamilton — APPROVED** [review]
This LGTM 👍 

---

Congrats on your first pull request (PR)! 🎉

Thank you for your contribution to the page! 👍
We are happy to accept these changes and look forward to future contributions. 📝

**Review by majestic-owl448 — APPROVED** [review]
Thank you for your contribution!

Happy coding!

**Pull request merged**
