### PR TITLE
Adding a solution for reversing a DoubleLinkedList.

### PR DESCRIPTION
**Pull request by kmwarter**
Checklist:

- [x ] I have read [freeCodeCamp's contribution guidelines](https://github.com/freeCodeCamp/freeCodeCamp/blob/master/CONTRIBUTING.md).
- [x ] My pull request has a descriptive title (not a vague title like `Update index.md`)
- [ x] My pull request targets the `master` branch of freeCodeCamp.
- [x ] All the files I changed are in the same world language, for example: only English changes, or only Chinese changes, etc.

Closes #XXXXX

### CODE REVIEW

**Review by RandellDawson — CHANGES_REQUESTED** [review]
@kmwarter Just pick a single solution.

**Comment by kmwarter** [comment]
Ok. I removed the other solution.

**Review by moT01 — APPROVED** [review]
LGTM 🎉 

Might as well add this to the guide when it gets merged?

**Review by RandellDawson — APPROVED** [review]

**Comment by RandellDawson** [comment]
Thank you for your contribution to the page! 👍
We're happy to accept these changes, and look forward to future contributions. 🎉

**Comment by RandellDawson** [comment]
@moT01 I updated the forum guide topic.

**Pull request merged**
