### PR TITLE
New Logo Rendering for Certifications Issuing

### PR DESCRIPTION
**Pull request by molecula451**
- [x] I have read [freeCodeCamp's contribution guidelines](https://github.com/freeCodeCamp/freeCodeCamp/blob/master/CONTRIBUTING.md).
- [x] My pull request has a descriptive title (not a vague title like `Update index.md`)
- [x] My pull request targets the `master` branch of freeCodeCamp.
- [x] None of my changes are plagiarized from another source without proper attribution.
- [x] All the files I changed are in the same world language (for example: only English changes, or only Chinese changes, etc.)
- [x] My changes do not use shortened URLs or affiliate links.

**These new changes should render the new logo as expected.**

Closes ##37892

### CODE REVIEW

**Comment by molecula451** [comment]
You may fix the lastest build error using --fix command

**Comment by raisedadead** [comment]
Hi @molecula451, Here's our [guidelines for contributing](https://github.com/freeCodeCamp/freeCodeCamp/blob/master/CONTRIBUTING.md), we recommend reading before making a PR.

**Comment by molecula451** [comment]
@raisedadead is there any issue with the files changes at all?

**Comment by raisedadead** [comment]
I am not sure if there is any, I never looked. We present a checklist when a PR is opened:

> Please follow this checklist ... 
> ... It will ensure that our team **takes your pull request seriously**.

We sincerely thank your efforts, but we are unable to merge it as is. The guidelines and the requirements are there for a reason.

1. This PR is made from a source branch that we are unable to push to (at least not without soiling your fork forever).
2. The commits need a cleanup.
3. This is probably untested locally looking at the history of commits.

Essentially in our best judgment we consider this a low effort PR and the QA is more involving and we would rather encourage a more refined contribution.

Thanks once again for taking the time.

**Comment by molecula451** [comment]
I am pretty sure the file changes are not breaking any other element. As the original file it's only rendering the old logo. While the other files that are in companion with this one are OK.

I will find a spare time if no any other person look at this so I can properly make the tests

**Comment by raisedadead** [comment]
Thanks for your understanding and interest in helping us. :)

**Pull request closed without merging**
