### PR TITLE
fix(client): remove --fcc-expected-- from hints

### LINKED ISSUE #56572: --fcc-actual-- and --fcc-expected-- not working in hints
`--fcc-actual--` and `--fcc-expected--` are not being replaced by their values in hints:

Image

While in the console the actual and expected values are visible:

Image

To reproduce, go to any challenge that uses `--fcc-actual--` and/or `--fcc-expected--`:
https://www.freecodecamp.org/learn/2022/responsive-web-design/learn-css-transforms-by-building-a-penguin/step-74

### PR DESCRIPTION
**Pull request by ojeytonwilliams**
Checklist:

- [x] I have read and followed the [contribution guidelines](https://contribute.freecodecamp.org).
- [x] I have read and followed the [how to open a pull request guide](https://contribute.freecodecamp.org/how-to-open-a-pull-request/).
- [x] My pull request targets the `main` branch of freeCodeCamp.
- [x] I have tested these changes either locally on my machine, or GitPod.

The error was caused by https://github.com/freeCodeCamp/freeCodeCamp/pull/56364 because I used the wrong test property (`text` includes `--fcc-expected--`, but `message` has that replaced with the value).

Closes: https://github.com/freeCodeCamp/freeCodeCamp/issues/56572

### CODE REVIEW

**Review by naomi-lgbt — APPROVED** [review]

**Comment by ojeytonwilliams** [comment]
Also, for future reference, I think we should distinguish between tests and test results. Using the same property for both is iffy.

**Review by a2937 — APPROVED** [review]
Getting this merged and approved as soon as it's working is a great idea. Yet I'd feel better if we added some kind of test to make sure something silly like this doesn't happen again.

**Comment by ojeytonwilliams** [comment]
Me too, @a2937. The problem I keep running into is that this is a nightmare to test.

The way forward is probably to create a self-contained testing module that we can feed in tests and get out results, but it's tricky to impose that structure on such a messy application.

**Comment by a2937** [comment]
The best solution I can think of would be to create a specialized set of curriculum files specifically made to test if all of our functionality works. That set of curriculum files never actually being seen by the campers and only are reachable in the developer environment.

**Comment by ojeytonwilliams** [comment]
Yep, that's pretty much what I had in mind, too.

**Pull request merged**
