### PR TITLE
fix(client): merge and update the learn map

### LINKED ISSUE #36820: Consolidate the welcome page and the projects/learn map page

### PR DESCRIPTION
**Pull request by raisedadead**
Closes #36820

Todo: 
- [x] Update tests for welcome component
- [x] ~~Add few tests for some of the learn page components component~~ We already have tests for the map component

### CODE REVIEW

**Comment by raisedadead** [comment]
Progress so far:

<details>
<summary>
Signed in view:
</summary>

image

</details>

<details>
<summary>
Non-Signed in view
</summary>

image

</details>

**Comment by ojeytonwilliams** [comment]
@raisedadead, I don't think we should be nesting `Grid` elements.  `learn.js` wraps everything in one, so we don't need them in `Map` or `Welcome`.  It ends up creating too much padding on small screens.

**Comment by raisedadead** [comment]
You are correct, I think I missed it. I never checked the mobile views. I'll update the PR.

**Comment by RandellDawson** [comment]
@raisedadead I will take a look at this later today and give my review.

**Comment by raisedadead** [comment]
Thanks @RandellDawson. 

Please note I am not doing the restructuring of sections that we talked about yet on this PR. This lays the groundwork for it though.

@ahmadabdolsaheb is going to be implementing some changes in his landing page updates that depends on this PR.

The section restructuring will come after his changes have been merged.

**Comment by RandellDawson** [comment]
@raisedadead In that case, I will wait for the next PR after @ahmadabdolsaheb's changes have been merged.

**Pull request merged**
