### PR TITLE
feat(dev): update GitPod testing

### PR DESCRIPTION
**Pull request by ShaunSHamilton**
Checklist:

- [x] I have read [freeCodeCamp's contribution guidelines](https://contribute.freecodecamp.org).
- [x] My pull request has a descriptive title (not a vague title like `Update index.md`)
- [x] My pull request targets the `master` branch of freeCodeCamp.
- [x] All the files I changed are in the same world language, for example: only English changes, or only Chinese changes, etc.

Previously, running `npm run test` within GitPod would error out due to the domain being `localhost`

Might update this to include the tooling (`Pupeteer`) needed for the Mocha side of the tests.

### CODE REVIEW

**Comment by raisedadead** [comment]
Hey @ojeytonwilliams, mind taking a look?

**Review by ojeytonwilliams — APPROVED** [review]
LGTM :+1: 

@Sky020 did you want to add Puppeteer? I'm fine with this going in without it, though.

**Comment by Sky020** [comment]
> did you want to add Puppeteer? I'm fine with this going in without it, though.

@ojeytonwilliams Not in this PR. I am still figuring that out. So, I will get back to it some other time. Right now, I am worried it will add a lot of overhead to the initialisation.

**Comment by ojeytonwilliams** [comment]
> add a lot of overhead to the initialisation.

Good point.  We should probably consider installing it on demand, like we do with Cypress.

**Pull request merged**
