### PR TITLE
chore: make local installations even faster

### PR DESCRIPTION
**Pull request by raisedadead**

### CODE REVIEW

**Comment by ojeytonwilliams** [comment]
I tried this out and ran into this:
build errors
after deleting the client cache and running `npm run develop`.

**Comment by raisedadead** [comment]
I do not if this is related to the PR? Can you confirm without the changes from this PR if you have the same issue?

**Comment by ojeytonwilliams** [comment]
@raisedadead The issue doesn't appear on master, but does when I switch to this PR.

Just to make 100% sure we're on the same page, these are the steps I took:

- `npm run clean`
- `rm -rf client/.cache`
- `npm i`
- `npm run develop`

**Comment by raisedadead** [comment]
Thanks for the information. I may have botched up the update.

Can you try these additional commands.

-  ..
- `rm -rf client/.cache`
- `rm -rf client/public`
- `npm ci`
- ..

**Comment by ojeytonwilliams** [comment]
Still happening, I'm afraid.  I'll try docker and see if that makes a difference.

**Comment by ojeytonwilliams** [comment]
Docker is not working properly.  Running `npm run docker:install` gives you:

```
> @freecodecamp/freecodecamp@0.0.1 bootstrap /app
> lerna bootstrap --ci
lerna notice cli v3.13.1
lerna info versioning independent
lerna info ci enabled
lerna info Bootstrapping 9 packages
lerna info Installing external dependencies
lerna ERR! npm ci exited 240 in '@freecodecamp/api-server'
lerna ERR! npm ci stderr:
npm WARN prepare removing existing node_modules/ before installation
npm ERR! path /app/api-server/node_modules
npm ERR! code EBUSY
npm ERR! errno -16
npm ERR! syscall rmdir
npm ERR! EBUSY: resource busy or locked, rmdir '/app/api-server/node_modules'
```
If you get rid of the `--ci` flag in package.json and just use `lerna bootstrap` it behaves exactly like I described above - the build succeeds, but with the prism warnings.

**Comment by raisedadead** [comment]
> If you get rid of the --ci flag in package.json and just use lerna bootstrap it behaves exactly like I described above - the build succeeds, but with the prism warnings.

You mean without the flags you are getting the warnings?

**Comment by ojeytonwilliams** [comment]
Exactly.  It will only install without flags, but you still get the warnings when you run `npm run docker:develop`

**Comment by ojeytonwilliams** [comment]
After a bit of trial and error, I've narrowed it down to the change from `"gatsby-remark-prismjs": "3.2.4"` to 3.2.6.

If you keep that at 3.2.4, you get rid of those warnings.  There's still

```
success extract queries from components — 0.134 s
⠁ (node:6461) MaxListenersExceededWarning: Possible EventEmitter memory leak detected. 11 drain listeners added. Use emitter.setMaxListeners() to increase limit
success run graphql queries — 3.246 s — 1692/1692 521.60 queries/second
success write out page data — 0.021 s
success write out redirect data — 0.000 s
success onPostBootstrap — 0.071 s

info bootstrap finished - 13.086 s

(node:6461) DeprecationWarning: Tapable.plugin is deprecated. Use new API on `.hooks` instead

WARNING: We noticed you're using the `useBuiltIns` option without declaring a core-js version. Currently, we assume version 2.x when no version is passed. Since this default version will likely change in future versions of Babel, we recommend explicitly setting the core-js version you are using via the `corejs` option.

You should also be sure that the version you pass to the `corejs` option matches the version specified in your `package.json`'s `dependencies` section. If it doesn't, you need to run one of the following commands:

  npm install --save core-js@2    npm install --save core-js@3
  yarn add core-js@2              yarn add core-js@3
```
but I don't think they're as serious.  

I'll see if I can find anything useful about the warnings - which files are affected, for instance.

**Comment by raisedadead** [comment]
I added some more updates.

I am not sure of what this one is:

```
(node:6461) MaxListenersExceededWarning: Possible EventEmitter memory leak detected. 11 drain listeners added. Use emitter.setMaxListeners() to increase limit
```

This one below is a webpack issue, which could be us (we are on a older version) or a underlying lib.

```
(node:6461) DeprecationWarning: Tapable.plugin is deprecated. Use new API on `.hooks` instead
```

**Comment by RandellDawson** [comment]
> (node:6461) DeprecationWarning: Tapable.plugin is deprecated. Use new API on `.hooks` instead

I have seen this message since I joined the GitHub mods in October.

**Comment by ojeytonwilliams** [comment]
I saw the `MaxListenersExceededWarning` one when I was working on watching the old curriculum.  As I understand it, it's only an issue for development - changing source files may not trigger recompiles or browser reloads.  It's annoying, but I don't think it's fatal.

As for the prism warnings, I've tracked that down to [here](https://github.com/gatsbyjs/gatsby/commit/25bd2fc168066abce3f21ca7e8bedab5739db881).  The problem was already there, but now Gatsby is telling us about it.  I'm not sure why those languages aren't being found, though.

**Comment by raisedadead** [comment]
Can you guys QA this? I am also tagging @cmccormack who may be interested in taking a look as well.

**Review by ojeytonwilliams — COMMENTED** [review]
The core-js issue is resolved.  

I checked the landing page and that looks good.  However, I don't know how to view my public profile in development, so I could not check that directly.  

`npm docker:install` still fails as described above.  

The prism warnings have been suppressed, ~~but I think I understand the underlying problem.  `gatsby-prism-remark` does not accept language synonyms, so `language-bash` is fine, but `language-shell` is not.~~  EDIT: it's not that. This still seems out of the scope of this PR, so I'll create an issue addressing it.

**Comment by raisedadead** [comment]
Thanks for catching the docker version of the installation. I have not checked the conflict with it. I'll update the PR soon.

**Comment by ojeytonwilliams** [comment]
@raisedadead It should be safe to update `gatsby-remark-prismjs` to 3.2.8 and `prismjs` to 1.16.0 now. I've tried installing that locally and the only remaining warning is about the fact that we aren't specifying languages for inline code.  We can ignore that one!

**Comment by RandellDawson** [comment]
Should `curriculum/challenges/english/08-coding-interview-prep/rosetta-code/define-a-primitive-data-type.english.md` be on this PR?

**Comment by ValeraS** [comment]
> Should `curriculum/challenges/english/08-coding-interview-prep/rosetta-code/define-a-primitive-data-type.english.md` be on this PR?

Without it, tests fail.

**Review by ojeytonwilliams — APPROVED** [review]
Everything seems to be working nicely now, LGTM :+1:

**Pull request merged**
