### PR TITLE
fix(curriculum): Add Missing Backticks

### LINKED ISSUE #48916: Step 83 of new JS build an rpg course inconsistent use of backticks
### Describe the Issue

In step 83 of the new js course to build an rpg, the step sometimes uses backticks around the number 30 and sometimes it does not. This seems inconsistent. Please see examples below (first one has no backticks around 30, while the next sentence uses backticks)

# --description--

Similar to your `buyHealth` function, set `gold` equal to 30 less than its current value. Make sure this is inside your `if` statement.

# --hints--

You should use compound assignment to subtract `30` from `gold`.

### Affected Page

curriculum/challenges/english/15-javascript-algorithms-and-data-structures-22/learn-basic-javascript-by-building-a-role-playing-game/62a8c89e4272512d44fc1c66.md

### Your code

```

```

### Expected behavior

The first occurrence of 30 should probably be enclosed in backticks.

### Screenshots

_No response_

### System

N/A

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by Sriparno08**
Checklist:

- [x] I have read [freeCodeCamp's contribution guidelines](https://contribute.freecodecamp.org).
- [x] My pull request has a descriptive title (not a vague title like `Update index.md`)
- [x] My pull request targets the `main` branch of freeCodeCamp.
- [x] I have tested these changes either locally on my machine, or GitPod.

Closes #48916

I have added the missing backticks in the new JavaScript course to build an RPG.

### CODE REVIEW

**Review by raisedadead — DISMISSED** [review]
Could you also update one of the other steps, as requested in the original issue?

**Comment by Sriparno08** [comment]
Yeah, sure 👍

**Review by naomi-lgbt — APPROVED** [review]
banger pr, thanks for contributing!

**Comment by Sriparno08** [comment]
Thanks, @naomi-lgbt 👍

**Review by Sembauke — APPROVED** [review]

**Pull request merged**
