### PR TITLE
Change instructions for how-to-npm and learnyounode challanges

### LINKED ISSUE #7080: Fix HowToNPM
We need to audit HowToNPM and figure out whether outstanding pull requests exist that can fix our current issues with it. 

I had previously recommended campers stop going after they finished challenge 11 (#3685) but it looks like challenge 10 might be broken now, too: https://github.com/FreeCodeCamp/FreeCodeCamp/issues/7073

Here's the largely inactive repo: https://github.com/npm/how-to-npm

Here's what I propose we do:
1. Try to run through HowToNPM and see how far we can get
2. Look at the outstanding pull requests and see whether there might be any that would fix that, and test those locally.
3. Reach out to the person who's maintaining it (currently seems to be @ashleygwilliams) and see if we can convince her to accept those PRs that would fix the functionality, and introduce PRs of our own if necessary.

If that doesn't work, we may need to maintain a fork ourselves, which would be undesirable but not out of the question.

### LINKED ISSUE #8680: The later challenges in learnyounode (challenge 10 onwards) do not work on C9 due to port restrictions.
Challenge [Finish working with Nodejs Servers](https://www.freecodecamp.com/challenges/finish-working-with-nodejs-servers) has an issue.
User Agent is: <code>Mozilla/5.0 (Windows NT 6.1) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/50.0.2661.94 Safari/537.36</code>.
Please describe how to reproduce this issue, and include links to screenshots if possible.

### PR DESCRIPTION
**Pull request by hutstep**
#### Pre-Submission Checklist

- [x] Your pull request targets the `staging` branch of FreeCodeCamp.
- [x] Branch starts with either `fix/`, `feature/`, or `translate/` (e.g. `fix/signin-issue`)
- [x] You have only one commit (if not, [squash](https://github.com/FreeCodeCamp/FreeCodeCamp/wiki/git-rebase#squashing-multiple-commits-into-one) them into one commit).
- [x] All new and existing tests pass the command `npm run test-challenges`. Use `git commit --amend` to amend any fixes.
#### Type of Change

- [x] Small bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds new functionality)
- [ ] Breaking change (fix or feature that would change existing functionality)
- [ ] Add new translation (feature adding new translations)
#### Checklist:

- [x] Tested changes locally.
- [x] Closes currently open issue (replace XXXX with an issue no): closes #8680 closes #7080  
#### Description

This PR changes the instructions for the how-to-npm and learnyounode challanges.
The main change is to use a "Blank" template instead of a "Node.js" template when creating a workspace on C9.
With the "Node.js" template both challenges regularly broke. Especially the dist tag challenge from how-to-npm.
I also fixed some typos and instructions which weren't so clear to the user.

### CODE REVIEW

**Comment by erictleung** [comment]
@hutstep everything looks good to me, but isn't npm stylized as lowercase? On the npm website (https://www.npmjs.com/), npm is always lowercase. What are you thoughts on this?

**Comment by hutstep** [comment]
@erictleung I don't understand what you mean? I changed all "npm" to lowercase because of that. They were all uppercase before.
On the npm website and on Wikipedia it's always lowercase.

**Comment by erictleung** [comment]
@hutstep oh sorry, I mixed up the red and greens in the commit diff in GitHub :smile: LGTM! :+1: Thanks for your contribution!

**Comment by hutstep** [comment]
No problem. :smile: 
Thanks!

**Pull request merged**
