### PR TITLE
Added a new lesson to check radio button in registration form class.

### PR DESCRIPTION
**Pull request by NiharPhansalkar**
Checklist:

- [x] I have read [freeCodeCamp's contribution guidelines](https://contribute.freecodecamp.org).
- [x] My pull request has a descriptive title (not a vague title like `Update index.md`)
- [x] My pull request targets the `main` branch of freeCodeCamp.
- [x] I have tested these changes either locally on my machine, or GitPod.

Closes #XXXXX

### CODE REVIEW

**Review by majestic-owl448 — CHANGES_REQUESTED** [review]
Please follow the contribution guidelines on how to add a step using the challenge editor.

This is not going to work.

**Comment by NiharPhansalkar** [comment]
I added it in as Step 41. Please re-review the pull request.

**Comment by ieahleen** [comment]
It's still not going to work, there is already a step 41.

Please read [contribution guidelines](https://contribute.freecodecamp.org/), there is also a part on how to work on practice projects.

**Comment by NiharPhansalkar** [comment]
I clicked on the insert step button. Should it not re-order the rest of the steps and insert mine as the 41st step?

**Comment by ieahleen** [comment]
yes, but whatever you did is not is the PR so it doesn't count

**Comment by raisedadead** [comment]
Hi @NiharPhansalkar, it seems you need more help with this; we encourage you to read the contribution guidelines, as you have been told a few times. We have a contributors discord chat room if you want to ask more questions.

Closing this for now, you are welcome to open fresh PR when you are ready.

**Pull request closed without merging**
