### PR TITLE
tools(client): Translation Key usage validation

### PR DESCRIPTION
**Pull request by naomi-lgbt**
Checklist:

- [X] I have read [freeCodeCamp's contribution guidelines](https://contribute.freecodecamp.org).
- [X] My pull request has a descriptive title (not a vague title like `Update index.md`)
- [X] My pull request targets the `master` branch of freeCodeCamp.
- [X] All the files I changed are in the same world language, for example: only English changes, or only Chinese changes, etc.

Closes #XXXXX

Adds a script that compares the list of keys in the English translations.json object against the client codebase to verify that all keys are used. Any unused translation key will be logged in the console for further investigation.

To run the script, from the root repository directory call:
```bash
cd ./client
npm run validate-keys
```

The console will output any unused keys in the translation object.

Signed-off-by: nhcarrigan <nhcarrigan@gmail.com>

### CODE REVIEW

**Comment by raisedadead** [comment]
We should also check things (if not already) like:

- The count of keys in the English should match that with the ones on the other languages.
- The keys should have the same identifier in all languages, for example a typo like below: 

  English
  ```js
  "labels": {
      "username": "...",
  ...
  }
  ```
  Spanish
  ```js
  "labels": {
      "usenrame": "...",
  ...
  }
  ```

  could lead to the UI showing `labels.usenrame` instead.

I can't think of more tests at the moment, but there can be more.

**Comment by nhcarrigan** [comment]
Both of those validations are handled in the `locales.test.js` file I believe:

```js
        // check that each of the json files match the schema
        test(`${file.name} has correct schema`, async () => {
          const jsonFile = fs.readFileSync(`${path}/${lang}/${file.name}`);
          let json = await JSON.parse(jsonFile);
          expectToMatchSchema(json, file.schema);
        });
```

**Comment by nhcarrigan** [comment]
> On another note, I think those should run as a part of the linting script.

To clarify, the schema validation should run as the lint? Or this key usage script I added?

**Comment by raisedadead** [comment]
Yes, the schema validation should run as a linting step. The script that you are introducing can remain independent.

**Comment by nhcarrigan** [comment]
Alright - I'll refactor the validation in a separate PR. 🙂

**Pull request merged**
