### PR TITLE
fix: code style in output now mirror test suite

### LINKED ISSUE #37307: Test output style should mirror the test suite
**Describe the bug**
The code blocks in the test output (below the editor) do not match the test suite (below the instructions)

**To Reproduce**
1. Go to [a challenge](www.freecodecamp.dev/learn/responsive-web-design/basic-css/use-css-selectors-to-style-elements)
2. Click on run the test
3. Scroll down to the output
4. See:

OutputDefault
in the default theme
and 
OutputNight
in night mode.

**Expected behavior**
The code blocks in the output should be the same as the suite.

### PR DESCRIPTION
**Pull request by ghost**
- [x] I have read [freeCodeCamp's contribution guidelines](https://github.com/freeCodeCamp/freeCodeCamp/blob/master/CONTRIBUTING.md).
- [x] My pull request has a descriptive title (not a vague title like `Update index.md`)
- [x] My pull request targets the `master` branch of freeCodeCamp.
- [x] None of my changes are plagiarized from another source without proper attribution.
- [x] All the files I changed are in the same world language (for example: only English changes, or only Chinese changes, etc.)
- [x] My changes do not use shortened URLs or affiliate links.

Closes #37307 by adding several attributes in specific CSS selector. Hence, there should be no unintended side effects. I had tested this on my local dev with both day and night mode.

### CODE REVIEW

**Review by ojeytonwilliams — APPROVED** [review]
LGTM :+1:

**Comment by ojeytonwilliams** [comment]
Thanks @rickysyamsi, that's exactly what I had in mind.

We're not merging to master while it's being deployed to production (and there's still discussion ongoing in the issue), so I won't merge immediately.

**Comment by rickysyamsi** [comment]
@ojeytonwilliams You're welcome :)

No problem with it, good luck with the deployment.

**Comment by raisedadead** [comment]
Screenshots please.

**Comment by rickysyamsi** [comment]
Sure thing @raisedadead.

Below is result in day mode:

day-mode

and below is in night mode:

night-mode

**Review by raisedadead — APPROVED** [review]

**Pull request merged**
