### PR TITLE
fix(seed): Fixed broken link in React Introducing Inline Styl

### LINKED ISSUE #17038: [BETA] Broken link in React Introducing Inline Styles Waypoint
#### Challenge Name
https://beta.freecodecamp.org/en/challenges/react/introducing-inline-styles

#### Issue Description
In the lesson, there is a broken link:
*Link text:*"the way you apply classes to JSX elements"
*URL*"https://beta.freecodecamp.org/en/challenges/react/link%20to%20classes%20challenge"

Having done the React lessons in a short time, I just looked at the Map for the React section (because I remembered doing it), and found the unbroken link.

**Suggested Replacement Text**
*Link text:*"the way you apply classes to JSX elements"
*URL*"https://beta.freecodecamp.org/en/challenges/react/define-an-html-class-in-jsx"

### PR DESCRIPTION
**Pull request by EditB**
#### Pre-Submission Checklist

- [x] Your pull request targets the `staging` branch of freeCodeCamp.
- [x] Branch starts with either `fix/`, `feature/`, or `translate/` (e.g. `fix/signin-issue`)
- [x] You have only one commit (if not, [squash](http://forum.freecodecamp.org/t/how-to-squash-multiple-commits-into-one-with-git/13231) them into one commit).
- [x] All new and existing tests pass the command `npm test`. Use `git commit --amend` to amend any fixes.

#### Type of Change

- [x] Small bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds new functionality)
- [ ] Breaking change (fix or feature that would change existing functionality)
- [ ] Add new translation (feature adding new translations)

#### Checklist:

- [x] Tested changes locally.
- [x] Addressed currently open issue (replace XXXXX with an issue no in next line)

Closes #17038

### CODE REVIEW

**Comment by varunzxzx** [comment]
@EditB Kindly mention the issue you are targeting in `Closes #XXXXX` in the template. Also, fix the typo in your commit message. You can do this using the command: `git commit --amend`. It will open the text editor, edit your commit message there, then save it. After that, `git push <remote> <branch> -f`

**Comment by EditB** [comment]
I made the changes. Not sure if the amend went through.

**Comment by varunzxzx** [comment]
Thanks for the changes. Now, it will be merged soon by any moderator.

**Comment by raisedadead** [comment]
@EditB looks like you have mentioned the PR no in the closed tag in the opening post 😅 !

Did you mean to have #17038 instead?

**Comment by EditB** [comment]
Yes, Thank you @raisedadead. I fixed it now. I had no idea there were different numbers. I thought the same number references the whole thread. Fixing the code was the easy part, the admin work is hard...

**Comment by mstellaluna** [comment]
I am currently working on this PR

**Review by mstellaluna — APPROVED** [review]
LGTM

**Comment by mstellaluna** [comment]
@EditB I will be approving this PR. Thank you for your contribution. Happy Coding !!

**Pull request merged**
