### PR TITLE
fix(guide): Corrected/Improved Hint and made similar solution to hint for Sort an Array Alphabetically using the sort Method challenge

### PR DESCRIPTION
**Pull request by RandellDawson**
- [x] I have read [freeCodeCamp's contribution guidelines](https://github.com/freeCodeCamp/freeCodeCamp/blob/master/CONTRIBUTING.md).
- [x] My pull request has a descriptive title (not a vague title like `Update index.md`)
- [x] My pull request targets the `master` branch of freeCodeCamp.
- [x] None of my changes are plagiarized from another source without proper attribution.
- [x] All the files I changed are in the same world language (for example: only English changes, or only Chinese changes, etc.)
- [x] My changes do not use shortened URLs or affiliate links.

Many forum users are confused on the **Sort an Array Alphabetically using the sort Method** challenge ever since Chrome made changes to the way the sort method works (now it correctly uses the compareFunction).  I noticed the hint in the Guide on `master` was incorrect, so I fixed it and added some extra verbiage to the hint.  Lastly, I made the example solution have the reverse logic of the hint example.

### CODE REVIEW

**Review by Manish-Giri — COMMENTED** [review]
I just went over the challenge and was surprised to find there was no details/mention of how a normal "compare function" is usually written. I feel like this part - 

> * If the compare function returns a value less than 0 for a given two elements (`a` and `b`), then `a` will > come before `b`.  
> * If the compare function returns a value equal to 0 for a given two elements (`a` and `b`), then `a` and > `b` will not change.  
> * If the compare function returns a value greater than 0 for a given two elements (`a` and `b`), then `b` > will come before `a`.  

should be included in the challenge itself. It's too important of a detail to be left in "hints".

MDN's [description of compare function](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Array/sort) is also quite well placed.

**Review by Manish-Giri — COMMENTED** [review]
@RandellDawson Will do. PR on its way.

**Comment by Manish-Giri** [comment]
@RandellDawson Created #35756.

**Comment by RandellDawson** [comment]
@Manish-Giri Now that #35756 has been merged should I remove the hint information from this PR?

**Comment by Manish-Giri** [comment]
@RandellDawson Sounds good.

**Comment by RandellDawson** [comment]
@Manish-Giri OK, I have removed the text that you added to the challenge.  Let me know if I need to change anything else.

**Review by Manish-Giri — APPROVED** [review]
@RandellDawson LGTM 💯

**Pull request merged**
