### PR TITLE
Correct the array description of Chunky Monkey

### PR DESCRIPTION
**Pull request by IanvsPoplicola**
The array required from the Chunky Monkey challenge is two-dimensional, not multidimensional.
The change has been made in both English and Spanish.

### CODE REVIEW

**Comment by SaintPeter** [comment]
Your PR has several issues:
1) You need to [squash your commits](https://github.com/FreeCodeCamp/FreeCodeCamp/wiki/git-rebase#squashing-multiple-commits-into-one).
2) You should NEVER be submitting from your staging, only a branch off staging.
3) Your branch name should be in the form `fix/some-short-description`

Please review: [Contributing.md](https://github.com/FreeCodeCamp/FreeCodeCamp/blob/staging/CONTRIBUTING.md) and its ancillary documents.

If you have messed up your staging branch, you can seek assistance in [HelpContributors](https://gitter.im/FreeCodeCamp/HelpContributors?utm_source=share-link&utm_medium=link&utm_campaign=share-link)

**Comment by IanvsPoplicola** [comment]
Thanks for the feedback!
This is my first attempt at doing pull requests, so I had no idea how to do them... (I have read Contributing.md though)
Should I redo all my changes and submit another pull request?

**Comment by IanvsPoplicola** [comment]
In case my staging branch is messed up, can't I just simply delete it and re-fork the repository from here?

**Comment by SaintPeter** [comment]
I think that you probably should.  You're going to need to clean your staging. Assuming you have a link to the main repo at `upstream`, you can do this from your local `staging` branch:
`git reset --hard upstream staging`

That will completely wipe your current staging and reset it to the current live branch head.  You shouldn't need to delete and re-fork.

Then you can create a branch and make your changes again.

NOTE:  You can just copy and paste the changed lines into a text editor so you can redo them.

**Comment by SaintPeter** [comment]
One more thing - once you reset the head, you can push your changes back to your github staging:
`git push origin staging -f`

You need the -f to overwrite the current staging branch on your GitHub repo.

**Comment by IanvsPoplicola** [comment]
Thank you so much for the tips!

**Pull request closed without merging**
