### PR TITLE
fix test for only change the first line

### LINKED ISSUE #14554: [BUG] Only change the first line
Challenge [subtract-one-number-from-another-with-javascript](http://beta.freecodecamp.com/en/challenges/basic-javascript/subtract-one-number-from-another-with-javascript) has an issue.
User Agent is: <code>Mozilla/5.0 (Macintosh; Intel Mac OS X 10_12_4) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/57.0.2987.133 Safari/537.36</code>.
Please describe how to reproduce this issue, and include links to screenshots if possible.

```js
var difference = 45 - 33;
```
I'm getting an error: `Only change the first line`

### PR DESCRIPTION
**Pull request by charlesBak**
closes #14554

### CODE REVIEW

**Comment by dhcodes** [comment]
@charlesBak thanks for the PR. I'm not sure this test is functioning correctly though as the following code still yields a passing test.
```
var difference = 45 - 31;
difference = 12;
```

**Comment by charlesBak** [comment]
@dhcodes, a other option would be to remove the tail element
https://github.com/freeCodeCamp/freeCodeCamp/blob/staging/seed/challenges/02-javascript-algorithms-and-data-structures/basic-javascript.json#L389

Because it is part of the code.

**Comment by raisedadead** [comment]
Actually, this change is now unnecessary, and the use case is accounted for already in the latest version of staging.

Closing as resolved already.

@charlesBak thanks a lot for your time and hard work, we value your contributions. Please feel free to check out more open issues and keep those PRs coming.

Happy fixing!

**Comment by raisedadead** [comment]
Refer chat thread: [May 28, 2017 2:25 PM](https://gitter.im/FreeCodeCamp/Contributors?at=592a906beec422e415f73cfd)

**Pull request closed without merging**
