### PR TITLE
fix(docs): Update docs for Docsify port 3400

### LINKED ISSUE #47669: Update docs following latest PR changes
And here! So the documentation is updated together
https://github.com/freeCodeCamp/freeCodeCamp/blob/2c4b0adf4163bd01ce7ae2aeb6bd5649dc557d37/docs/how-to-work-on-the-docs-theme.md?plain=1#L79

_Originally posted by @ieahleen in https://github.com/freeCodeCamp/freeCodeCamp/issues/47663#issuecomment-1262600581_
      

Following #47665 the docs need to be updated

### PR DESCRIPTION
**Pull request by LucasVance**
Checklist:

- [x] I have read [freeCodeCamp's contribution guidelines](https://contribute.freecodecamp.org).
- [x] My pull request has a descriptive title (not a vague title like `Update index.md`)
- [x] My pull request targets the `main` branch of freeCodeCamp.
- [x] I have tested these changes either locally on my machine, or GitPod.

Closes #47669

### CODE REVIEW

**Review by naomi-lgbt — APPROVED** [review]
banger pr, thanks for contributing!

A couple of quick notes:

- You should not make your changes directly on your `main` branch, as you want to keep it clean. Instead, you should create a branch for each feature/fix/change you are working on.
- I saw your previous PR which had changes to the language files. In the future, when you need to update a PR, you can push additional commits directly to the branch instead of having to make a new PR. 😁

**Review by gikf — APPROVED** [review]
LGTM :+1:

**Comment by gikf** [comment]
Hi @LucasVance. Congrats on your first pull request (PR)! 🎉

Thank you for your contribution to the page! 👍
We are happy to accept these changes and look forward to future contributions. 📝

**Comment by LucasVance** [comment]
Thanks, all! I look forward to contributing more.

**Pull request merged**
