### PR TITLE
Updated the Code of Conduct per the Wiki

### LINKED ISSUE #8506: [Fix] Update Code of Conduct
Update official code of conduct in the website [**FreeCodeCamp.com/code-of-conduct**](https://www.freecodecamp.com/code-of-conduct) with the one in the wiki [**Code of Conduct** (wiki)](https://github.com/FreeCodeCamp/FreeCodeCamp/wiki/Code-of-Conduct) which was updated recently.

#### Related Files:
- **File to Update:** [**code-of-conduct.jade** (FCC repository file)](https://github.com/FreeCodeCamp/FreeCodeCamp/blob/staging/server/views/resources/code-of-conduct.jade)
- **Reference File:** [**Code-of-Conduct.md** (FCC wiki file)](https://github.com/FreeCodeCamp/wiki/blob/master/Code-of-Conduct.md)
<br>
<br>

> ----
<p align="center">Need Help? Read <a href="https://github.com/FreeCodeCamp/FreeCodeCamp/blob/staging/CONTRIBUTING.md"><b>CONTRIBUTING</b></a> Guidelines<br>or Chat with us in <kbd><a href="https://gitter.im/FreeCodeCamp/HelpContributors"> <b>FreeCodeCamp/HelpContributors</b></a></kbd></p>

> ----

**Currently Assigned to:** @josevill 

> *If you want to work on this, please comment below and we can chat over* <kbd><a href="https://gitter.im/FreeCodeCamp/HelpContributors"> <b>gitter</b></a></kbd>
Note: you may be assigned **only if** the current assignee doesn't respond within a given time-frame.

### PR DESCRIPTION
**Pull request by nishant-tomer**
#### Pre-Submission Checklist

- [x] Your pull request targets the `staging` branch of FreeCodeCamp.
- [x] Branch starts with either `fix/`, `feature/`, or `translate/` (e.g. `fix/signin-issue`)
- [x] You have only one commit (if not, [squash](https://github.com/FreeCodeCamp/FreeCodeCamp/wiki/git-rebase#squashing-multiple-commits-into-one) them into one commit).
- [x] All new and existing tests pass the command `npm run test-challenges`. Use `git commit --amend` to amend any fixes.
#### Type of Change

- [x] Small bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds new functionality)
- [ ] Breaking change (fix or feature that would change existing functionality)
- [ ] Add new translation (feature adding new translations)
#### Checklist:

- [x] Tested changes locally.
- [x] Closes currently open issue: Closes #8506
#### Description

Updated official code of conduct in the website [FreeCodeCamp.com/code-of-conduct](https://www.freecodecamp.com/code-of-conduct) with the one in the wiki Code of Conduct (wiki) which was updated recently.

Related Files:

File to Update: [code-of-conduct.jade (FCC repository file)](https://github.com/FreeCodeCamp/FreeCodeCamp/blob/staging/server/views/resources/code-of-conduct.jade)
Reference File: [Code-of-Conduct.md (FCC wiki file)](https://github.com/FreeCodeCamp/wiki/blob/master/FreeCodeCamp-Code-Of-Conduct.md)

### CODE REVIEW

**Comment by c0906969479** [comment]
2016/5/15 23:36於 "Nishant Tomer" <notifications@github.com>寫道：

**Comment by abhisekp** [comment]
<h1 align="center"> :sparkles:  :smile_cat:  :+1: LGTM :smiley: :+1:   :sparkles:  </h1>

> [](http://i.imgur.com/qtLqhEh.png)

@raisedadead please merge :ship: :sparkles:

**Comment by raisedadead** [comment]
@abhisekp for the QA.
@nishant-tomer Thanks for the fix.

**Pull request merged**
