### PR TITLE
Fix missing link in updated instructions

### PR DESCRIPTION
**Pull request by noelnoche**
#### Pre-Submission Checklist

- [ ] Your pull request targets the `staging` branch of FreeCodeCamp.
- [x] Branch starts with either `fix/`, `feature/`, or `translate/` (e.g. `fix/signin-issue`)
- [x] You have only one commit (if not, [squash](http://forum.freecodecamp.com/t/how-to-squash-multiple-commits-into-one-with-git/13231) them into one commit).
- [ ] All new and existing tests pass the command `npm run test-challenges`. Use `git commit --amend` to amend any fixes.
#### Type of Change

- [x] Small bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds new functionality)
- [ ] Breaking change (fix or feature that would change existing functionality)
- [ ] Add new translation (feature adding new translations)
#### Checklist:

- [x] Tested changes locally.
- [ ] Closes currently open issue (replace XXXX with an issue no): Closes #XXXX
#### Description

This fixes the missing link in the updated instructions due to the lack of a closing `<a>` tag with content.

Before
"UPDATE: Due to a change in conditions on API usage explained here, use the sample API response we provide at"

Fixed
"UPDATE: Due to a change in conditions on API usage explained here, use the sample API response we provide at https://gist.github.com/QuincyLarson/2ff6892f948d0b7118a99264fd9c1ce8".

### CODE REVIEW

**Comment by atjonathan** [comment]
### **LGTM :+1:**
Can we merge to `backup/master` @BerkeleyTrue?

**Review by ghost — APPROVED** [review]
### **LGTM :+1:**

Can we merge to `backup/master` @BerkeleyTrue?

**Comment by BerkeleyTrue** [comment]
@atjonathan Yes, this looks like it needs to go out.

**Comment by atjonathan** [comment]
@BerkeleyTrue, cool!

**Pull request merged**
