### PR TITLE
feat(curriculum): add form validation lab to FSD cert

### LINKED ISSUE #646: Add form validation lab to main repo
Here is the merged prototype

https://github.com/freeCodeCamp/CurriculumExpansion/pull/627

We need to add that lab to main with tests

### PR DESCRIPTION
**Pull request by Dario-DC**
Checklist:

- [x] I have read and followed the [contribution guidelines](https://contribute.freecodecamp.org).
- [x] I have read and followed the [how to open a pull request guide](https://contribute.freecodecamp.org/how-to-open-a-pull-request/).
- [x] My pull request targets the `main` branch of freeCodeCamp.
- [x] I have tested these changes either locally on my machine, or GitPod.

Closes https://github.com/freeCodeCamp/CurriculumExpansion/issues/646

If you want to test this lab with the provided JS solution, be sure to use the HTML from the solution (**not from the seed**).
There's a clear button in my solution but I decided to not include it in the user stories because the lab is already way too long.

### CODE REVIEW

**Review by fhsinchy — APPROVED** [review]
Unfortunately couldn't find anything to complain about @Dario-DC 😅

**Comment by zairahira** [comment]
@Dario-DC

I have noticed, the last test is failing due to timeout. It takes some time to run as compared to other tests.
I feel this could be due to the alert box.

I have tried your solution as well. I am using Firefox.

image

**Comment by Dario-DC** [comment]
> @Dario-DC
> 
> I have noticed, the last test is failing due to timeout. It takes some time to run as compared to other tests. I have tried your solution as well. I am using Firefox.
> 
> image

I'm not able to reproduce it @zairahira Does it happen with your own solution? If so can you share it?

**Comment by zairahira** [comment]
> > @Dario-DC
> > I have noticed, the last test is failing due to timeout. It takes some time to run as compared to other tests. I have tried your solution as well. I am using Firefox.
> > image
> 
> I'm not able to reproduce it @zairahira Does it happen with your own solution? If so can you share it?

I happens with my own solution and with yours as well.
For me, this test is usually taking a bit longer to execute, and it doesn't timeout every time.

**Review by moT01 — CHANGES_REQUESTED** [review]
Well, this really is a beast @Dario-DC - challenging and fun though 👍 Here's what I found... 

I had a number of timeout errors on firefox as well. Sometimes they would go slow and timeout - other times they would all pass really fast. Also got a runtime error that says "timeout" at one point - so maybe not ideal. Didn't have any issues on chrome. I wonder if you changed those tests to actually fill out the form instead of overwriting the `isValid` function?

<details><summary>Here's the code I used</summary>

```js
const fullNameEl = document.getElementById('full-name');
const emailEl = document.getElementById('email');
const orderNoEl = document.getElementById('order-no');
const productCodeEl = document.getElementById('product-code');
const quantityEl = document.getElementById('quantity');
const complaintsGroupEl = document.getElementById('complaints-group');
const complaintCheckboxEls = document.querySelectorAll('input[name="complaint"]')
const complaintOtherEl = document.querySelector('#complaints-group input[value="other"]');
const complaintDescriptionEl = document.getElementById('complaint-description');
const solutionsGroupEl = document.getElementById('solutions-group');
const solutionRadioEls = document.querySelectorAll('input[name="solutions"]');
const solutionOtherEl = document.querySelector('#solutions-group input[value="other"]');
const solutionDescriptionEl = document.getElementById('solution-description');
const messageBoxEl = document.getElementById('message-box');

const validateForm = () => {
  return {
    "full-name": !!fullNameEl.value,
    "email": /^\S+@\S+\.\S+$/.test(emailEl.value),
    "order-no": /^2024\d{6}$/.test(orderNoEl.value),
    "product-code": /^[a-z]{2}\d{2}-[a-z]\d{3}-[a-z]{2}\d$/.test(productCodeEl.value.toLowerCase()),
    "quantity": Number.isInteger(parseInt(quantityEl.value)) && quantityEl.value > 0,
    "complaints-group": Array.from(complaintCheckboxEls).some(checkbox => checkbox.checked),
    "complaint-description": complaintOtherEl.checked ? complaintDescriptionEl.value.length >= 20 : true,
    "solutions-group": Array.from(solutionRadioEls).some(radio => radio.checked),
    "solution-description": solutionOtherEl.checked ? solutionDescriptionEl.value.length >= 20 : true
  }
}

const isValid = form => !Object.values(form).includes(false);

const highlightFields = validatedForm => {
  const {
    "full-name": validFullName,
    "email": validEmail,
    "order-no": validOrderNo,
    "product-code": validProductCode,
    "quantity": validQuantity,
    "complaints-group": validComplaintsGroup,
    "complaint-description": validComplaintDescription,
    "solutions-group": validSolutionsGroup,
    "solution-description": validSolutionDescription
  } = validatedForm;

  fullNameEl.style.borderColor = validFullName ? 'green' : 'red';
  emailEl.style.borderColor = validEmail ? 'green' : 'red';
  orderNoEl.style.borderColor = validOrderNo ? 'green' : 'red';
  productCodeEl.style.borderColor = validProductCode ? 'green' : 'red';
  quantityEl.style.borderColor = validQuantity ? 'green' : 'red';
  complaintsGroupEl.style.borderColor = validComplaintsGroup ? 'green' : 'red';
  complaintDescriptionEl.style.borderColor = validComplaintDescription ? 'green' : 'red';
  solutionsGroupEl.style.borderColor = validSolutionsGroup ? 'green' : 'red';
  solutionDescriptionEl.style.borderColor = validSolutionDescription ? 'green' : 'red';
}

form.addEventListener('submit', () => {
  const validatedForm = validateForm();
  highlightFields(validatedForm);

  if (!isValid(validatedForm)) {
    messageBoxEl.innerText = 'Please, fill out the required fields correctly before submitting.';
  } else {
    messageBoxEl.innerText = '';
    alert('Form successfully submitted.');
  }
});

form.addEventListener('change', () => highlightFields(validateForm()));
```

</details>

It behaves a little differently than the demo, but fulfills the user stories - it doesn't pass all the tests as they are. At the bottom, I add an event listener to the `#form`, and the dispatched events on the input elements in the tests won't cause that to fire. I changed all the tests to look like this: `field.dispatchEvent(new Event("change", { bubbles: true }));` to get them to trigger that event. We should add that to all those tests.

One thing you could maybe do to increase readability is group the first nine user stories into a list like some of the other labs have been doing. e.g:

```
1. When a form is submitted, you should:
 - ensure that `#full-name` is not empty.
 - ensure that #email is a valid email address format.
 - etc.
```

User stories 12 and 13 were a little confusing at first. Initially I thought that I should add a change listener, then I wondered if I was supposed to just change the colors on submit. Figured out that it was the change listener. Maybe we could reword those to something like:

```
If a change event is triggered on a form field and it has a valid value,
you should set its border color to green. In case of checkbox and radio
button groups, you should set the border color of the parent fieldset.
```

**Comment by Dario-DC** [comment]
> I wonder if you changed those tests to actually fill out the form instead of overwriting the isValid function?

That was my initial attempt but for some reasons I wasn't able to make it work :face_with_diagonal_mouth: @moT01

**Comment by Dario-DC** [comment]
> It behaves a little differently than the demo, but fulfills the user stories - it doesn't pass all the tests as they are. At the bottom, I add an event listener to the #form, and the dispatched events on the input elements in the tests won't cause that to fire

I don't like very much that once you fill a form field, the other fields become red, even if you haven't touched them yet.

But this is probably a bit too much for this lab, I agree. I updated the user stories as per your suggestions. Not sure what to do about the rest though.

**Comment by Dario-DC** [comment]
I modified the tests to use `{bubbles: true}`. Your solution passes now @moT01 

@zairahira told me that the issue was with the last test but @ilenia-magoni had issues with the last 3 tests. I decided to remove those 3 and the related user stories. I haven't found another solution.

**Comment by zairahira** [comment]
@Dario-DC,

I do not see any timeouts now 👍️

**Review by moT01 — APPROVED** [review]

**Pull request merged**
