### PR TITLE
fix(buttons): update toggle buttons feedback color

### PR DESCRIPTION
**Pull request by raisedadead**

### CODE REVIEW

**Comment by raisedadead** [comment]
Before:
image


After:

image

**Comment by ahmadabdolsaheb** [comment]
@mrughesh, I like how some of the explanations are shorter.
For adding red to the buttons' color palette, there is whole discussion around this, but I think it would add confusion. 


 I see Stuart added the gray background for the .toggle-not-active, but we could just change
  background-color: white; if you are going for the clean production look

**Comment by raisedadead** [comment]
> I like how some of the explanations are shorter.

IMHO, they should be succinct.

`"Your certifications will be disabled."` ==> When??
`"Your certifications will be disabled, if set to private."` ==> Oh.. I see.

About the color:

What I have had known from my experience with mods and issue thread, constantly see that user's complain their certs are not visible or they are unable to claim certs only to realise they had the button flipped the other way.

A visual feedback gives quick ques.

But I am open to feedback.

**Comment by ahmadabdolsaheb** [comment]
well explained, LGTM. one small suggestion. maybe we flip the night mode toggles to have all the reds on one side on another PR.

**Comment by raisedadead** [comment]
Maybe instead of the red we could go with something more subtle.

**Comment by ahmadabdolsaheb** [comment]
would adding the red or hue's of red only to the toggle buttons that hide certificates make sense?
for instance, the toggle is red and green on night mode which does not convey any information.
Additionally, I think if you try to open a certificate and privacy toggles are not set correctly, you get a flash message.

**Comment by raisedadead** [comment]
I have rolled back the changes, keeping things to match production with the exception of the explain text.

image

**Comment by ahmadabdolsaheb** [comment]
🙏

**Pull request merged**
