### PR TITLE
Responsive Web Design: Improve translate Give Links Meaning by Using …

### PR DESCRIPTION
**Pull request by greggubarev**
…Descriptive Link Text

- [x] I have read [freeCodeCamp's contribution guidelines](https://github.com/freeCodeCamp/freeCodeCamp/blob/master/CONTRIBUTING.md).
- [x] My pull request has a descriptive title (not a vague title like `Update index.md`)
- [x] My pull request targets the `master` branch of freeCodeCamp.
- [x] None of my changes are plagiarized from another source without proper attribution.
- [x] My article does not contain shortened URLs or affiliate links.

If your pull request closes a GitHub issue, replace the XXXXX below with the issue number.

Closes #XXXXX

### CODE REVIEW

**Comment by RandellDawson** [comment]
@greggubarev Since you are doing several of these translations, would you mind adding the label Russian and if it relates to the curriculum add the scope: curriculum or scope: guide for Guide related translations.  That would really help us out.

Thank you for all your hard work!

**Comment by greggubarev** [comment]
Ok, got it

**Comment by greggubarev** [comment]
> @greggubarev Since you are doing several of these translations, would you mind adding the label Russian and if it relates to the curriculum add the scope: curriculum or scope: guide for Guide related translations. That would really help us out.
> 
> Thank you for all your hard work!

[Creating a label](https://help.github.com/articles/labeling-issues-and-pull-requests/#creating-a-label)
How i can create a label, i dont have write access.. or am i wrong?

**Comment by greggubarev** [comment]
> @greggubarev You can't only collaborator and above can, however in your PR's title, you could add the language at the beginning like `[Russian] Rest of the title`

@ezioda004 Ok, thank you, in my next commits i`ll use this!

**Comment by ezioda004** [comment]
@greggubarev I'm not sure if you are allowed to merge your own PR's. Please confirm this with @QuincyLarson and @raisedadead.

**Pull request merged**
