### PR TITLE
fix: get jquery from cdn

### PR DESCRIPTION
**Pull request by ojeytonwilliams**
- fix: ensures jquery exists for those challenges
- Revert "Revert "fix: only include frame-runner when running tests (#44337)" (#44419)"

### CODE REVIEW

**Review by naomi-lgbt — APPROVED** [review]
jQuery still works 😁

**Comment by ojeytonwilliams** [comment]
@ShaunSHamilton mentioned that this might have caused campers some problems running the tests.  Since this isn't urgent, I'd like to give him a chance to see if putting framer-runner everywhere fixes things.

**Comment by ShaunSHamilton** [comment]
This is what I am investigating: https://forum.freecodecamp.org/t/unable-to-move-on-after-completing-an-assignment/488058

I have been unable to reproduce any issues in the mentioned challenges. So, my best guess is it is one of those _recent push to production_ issues - usually resolved with a good ol' hard-refresh.

**Comment by ojeytonwilliams** [comment]
Thanks @ShaunSHamilton could you unblock this when you're reasonably confident that forum post is unrelated?

**Comment by raisedadead** [comment]
@ShaunSHamilton please confirm ?

**Review by ShaunSHamilton — APPROVED** [review]
This works, but because of how old this branch is, I was unable to confirm whether or not this might affect the new curriculum - doubtful, but 🤷‍♂️

**Pull request merged**
