### PR TITLE
feat: add Reverse an Integer  exercise for Basic Algorithm Scripting

### PR DESCRIPTION
**Pull request by liamsloane**
- [x ] I have read [freeCodeCamp's contribution guidelines](https://github.com/freeCodeCamp/freeCodeCamp/blob/master/CONTRIBUTING.md).
- [x ] My pull request has a descriptive title (not a vague title like `Update index.md`)
- [x ] My pull request targets the `master` branch of freeCodeCamp.
- [x ] None of my changes are plagiarized from another source without proper attribution.
- [x ] All the files I changed are in the same world language (for example: only English changes, or only Chinese changes, etc.)
- [ x] My changes do not use shortened URLs or affiliate links.

I have written a new exercise, 'Reverse an Integer' in the JavaScript: Basic Algorithm Scripting section. 

Going through the exercises myself, I find that practicing this algorithm is a valuable and key exercise to learning and familiarization with JavaScript. I think it can make a great addition to the questions. 

Not only that, it is a common programming question asked in interviews so it provide real world value. And it still passes the mark for being straightforward and friendly for all levels. Finally, It differs from reversing a string and challenges the person's fundamental understanding of arrays vs strings vs  numbers. 

I've ran and passed tests on a local copy of the site. 

Would be great to get some feedback on this.

Thanks

### CODE REVIEW

**Comment by RandellDawson** [comment]
@01Clarian Thank you for trying to contribute, but we are currently not accepting any new challenges for the current curriculum.  We are only accepting bug fixes or rewording of existing challenges to make them better.  All new curriculum work is being worked on in the [CurriculumExpansion repo](https://github.com/freeCodeCamp/CurriculumExpansion).  You should take a look at the outstanding issues/projects which need help there for adding new content.

**Comment by 01Clarian** [comment]
@RandellDawson 

Thanks for your prompt response.  Being new to open source contributions, I got excited and went straight to writing and testing so appreciate the guidance to refer to the issues raised first and you taking the time to mention that. 

Will definitely check out the Expansion Repository and issues/projects!

**Comment by RandellDawson** [comment]
@01Clarian You are still more than welcome to take a look at [any existing issues we currently have with the current curriculum](https://github.com/freeCodeCamp/freeCodeCamp/issues?q=is%3Aopen+is%3Aissue+label%3A%22scope%3A+curriculum%22) and offer some suggestions on those issues and/or create PRs for those issues.

**Comment by RandellDawson** [comment]
> so appreciate the guidance to refer to the issues raised first

You can always create a PR that fixes a bug (even if the bug has not been reported on an existing issue) when you see them.  However, we have found in the past, sometimes users think they have found bugs which were not.  This is why an issue is typically recommended which involves making a substantial change to a challenge's tests or solution.

**Comment by 01Clarian** [comment]
@RandellDawson  Understood. I see how it makes sense to bring up an issue beforehand and have that discussion / bring things better to light and getting on the same page.  

Will have a look through. Thanks.

**Pull request closed without merging**
