### PR TITLE
feat(curriculum): DRY-out backend project descriptions

### PR DESCRIPTION
**Pull request by ShaunSHamilton**
Checklist:

- [x] I have read [freeCodeCamp's contribution guidelines](https://contribute.freecodecamp.org).
- [x] My pull request has a descriptive title (not a vague title like `Update index.md`)
- [x] My pull request targets the `master` branch of freeCodeCamp.
- [x] All the files I changed are in the same world language, for example: only English changes, or only Chinese changes, etc.

Groundwork and test to help maintainers with the descriptions. _I am still experimenting with adding functionality to allow the example links to be incorporated_

### CODE REVIEW

**Comment by nhcarrigan** [comment]
I think we could DRY this out even more. What if we...

Within each file, change the text to:
```md
Build a full stack JavaScript app that is functionally similar to this: <live link>. Use this boilerplate to start your project: <github repo link>
```

Then the import block could be:
```md
Working on this project will involve you writing your code using one of the following methods:
-   Clone the boilerplate project and complete your project locally.
-   Use repl.it to import the boilerplate and complete your project.
-   Use a site builder of your choice to complete the project. Be sure to incorporate all the files from our GitHub repo.

When you are done, make sure a working demo of your project is hosted somewhere public. Then submit the URL to it in the `Solution Link` field. Optionally, also submit a link to your projects source code in the `GitHub Link` field.
```

It might take an extra step for campers to import the repl.it from the github repository (rather than clicking the link and auto-forking it) but would make updating the text smoother and remove the need to maintain the boilerplate repl.it instances.

Thoughts?

**Comment by ShaunSHamilton** [comment]
@nhcarrigan That would definitely be the eaiser/quicker fix (feat). However, I would much prefer adding functionality like:

Export
```markdown
Project="""Working on this project will involve you writing your code using one of the following methods:

-   Clone [this GitHub repo](link1) and complete your project locally.
-   Use [our repl.it starter project](link2) to complete your project.
-   Use a site builder of your choice to complete the project. Be sure to incorporate all the files from our GitHub repo.
"""
```
Import:
```markdown
import{project="Project" from="./foo"}

use{project(link1, link2)}
```

---

I have only just started looking at this. So, i do not expect the above to be at all representative of an actual implementation.

**Comment by nhcarrigan** [comment]
If we can get functionality like that in place, then we could actually move the whole block into an import right? Since we could replace the live example link too.

**Comment by RandellDawson** [comment]
@ShaunSHamilton I assume you are still working out the bugs on this PR?  When I go to any of the projects I see something like:

image

**Comment by ShaunSHamilton** [comment]
@RandellDawson Yes. You can go to the first commit to see it working.

I will name my commits `broken: something` if they really do not work.

**Comment by ojeytonwilliams** [comment]
So, this is failing because reference style links only get interpreted if both halves exist.

If you have
```
[link][1]

[1]: http://example.com
```
it'll work, but

```
[link][1]
```

on its own is just treated as text.  Two options spring to mind.

a) parse markdown -> insert imports -> recreate markdown -> parse it again
b) modify the underlying markdown parser so that it interprets [this][construct] as a reference link, even if it refers to nothing.

a) seems a bit hacky, but should work.  The only worry is that it might escape [link][1].
b) is probably harder and more likely to create weird behaviour.

**Comment by ShaunSHamilton** [comment]
@ojeytonwilliams Thanks for that. Which option would you recommend for the repo going forward? Something hacky does not sound like an enjoyable option - maintainability-wise.

**Comment by ojeytonwilliams** [comment]
Well, one issue is that I probably won't have time to work on this for a few weeks.  If you are interested in trying to change the parser, you're more than welcome.  I'd recommend approach a), it seems like a reasonable, if slightly weird, approach.

There may be a way to achieve what you want using the parser as is, but nothing leaps to mind.

**Comment by ShaunSHamilton** [comment]
Thank you, very much for your hints, Oliver.

This is now working. All I had to do was force the tree to look the way it should, by adding placeholders for the link references. I am happy with this as is.

**Comment by ojeytonwilliams** [comment]
Oh, interesting.  That's a neat workaround. If/when we change the parser we can get rid of the placeholders, but this looks good for now.

Finally 'dictionaries' isn't the right place for the imported file.  Could you put it in `/curriculum/challenges/imported-files/` ?  It's not the ideal place, but we'd need to rework how the files are sourced before we can put it anywhere inside `/curriculum/challenges/english`

**Comment by RandellDawson** [comment]
@ShaunSHamilton To make it a bit more readable, why not use descriptive keys instead of numbers?

For example, the `markdown-exports.md` file could look like:
```md
Build a full stack JavaScript app that is functionally similar to this: [example project][demo-project-url]. Working on this project will involve you writing your code using one of the following methods:

- Clone [this GitHub repo][github-url] and complete your project locally.
- Use [our repl.it starter project][repl.it-url] to complete your project.
- Use a site builder of your choice to complete the project. Be sure to incorporate all the files from our GitHub repo.

When you are done, make sure a working demo of your project is hosted somewhere public. Then submit the URL to it in the `Solution Link` field. Optionally, also submit a link to your project's source code in the `GitHub Link` field.

[demo-project-url]: placeholder
[github-url]: placeholder
[repl.it-url]: placeholder
```
then in let's say the `timestamp-microservice` project, the description section could look like:
```md
# --description--

::use{description="Desc"}

[demo-project-url]: https://timestamp-microservice.freecodecamp.rocks
[github-url]: https://github.com/freeCodeCamp/boilerplate-project-timestamp/
[repl.it-url]: https://repl.it/github/freeCodeCamp/boilerplate-project-timestamp
```

@raisedadead @ojeytonwilliams If we use these, we will need to have a corresponding `markdown-exports.md` for each language, so I am thinking the proper location would need to be within each language folder like:

- `curriculum/challenges/english/imported-files/markdown-exports.md`
- `curriculum/challenges/chinese/imported-files/markdown-exports.md`
- `curriculum/challenges/espanol/imported-files/markdown-exports.md`

**Comment by ojeytonwilliams** [comment]
> language, so I am thinking the proper location would need to be within each language folder like:
> 
> curriculum/challenges/english/imported-files/markdown-exports.md
curriculum/challenges/chinese/imported-files/markdown-exports.md
curriculum/challenges/espanol/imported-files/markdown-exports.md

That makes sense, but currently everything inside `curriculum/challenges/any-language/` gets treated as a challenge, so we'd need to change that before we could put any other markdown there.

**Comment by nhcarrigan** [comment]
Rather than placing it in the challenges (since it is not a challenge), can we use a folder like `curriculum/imported-files`? 🤔

**Comment by RandellDawson** [comment]
Wherever it gets put, there will need to be a Chinese and Espanol version in separate folders to be able to integrate with Crowdin.

**Comment by raisedadead** [comment]
> @raisedadead We need to nail this down today and get this PR in before freezing the code again...

This is a feature (nice-to-have) - and beyond the scope of the sprint. We will be entertaining this at a later point, no ETAs. We will have to run that audit once more when we do end up merging this sometime in future.

**Comment by ojeytonwilliams** [comment]
Right now the syntax should be `::import{component="name" from="path"}` with `::use{component="name"}`.  The code in this PR works, but only because I messed up that bit of the parser - it should ignore import statements without `component`.  We could deliberately allow generic `::import{name-of-your-choice="name" from="path"}` and `::use{name-of-your-choice="name"}`, but is it a good idea? 

 I'm leaning towards the stricter syntax, while having the parser throw an helpful error when you don't use component + from.  I think this will be the least confusing, since it can tell you exactly what you did wrong and how to fix it. Any thoughts @ShaunSHamilton @nhcarrigan @RandellDawson ?

**Comment by ShaunSHamilton** [comment]
@ojeytonwilliams I did wonder about that, but thought _not to look a gift horse in the mouth_ 😄 

I was actually hoping we could have named imports/exports. Particularly, to reduce the number of files necessary. However, if this is not possible/too complex, then having one, straight-forward standard would probably be beneficial.

**Comment by ojeytonwilliams** [comment]
> @ojeytonwilliams I did wonder about that, but thought _not to look a gift horse in the mouth_ 

This horse was a bug :sweat: 

> I was actually hoping we could have named imports/exports. Particularly, to reduce the number of files necessary. However, if this is not possible/too complex, then having one, straight-forward standard would probably be beneficial.

Does this reduce the number of files?  You can always `::import{component="one" from="one.md"}` and `::import{component="two" from="two.md"}`.  Could you give me a code example so I can understand where it would help?

**Comment by ShaunSHamilton** [comment]
@ojeytonwilliams 
> Could you give me a code example so I can understand where it would help?

I briefly mentioned it in an [above comment](https://github.com/freeCodeCamp/freeCodeCamp/pull/40456#issuecomment-744854464), but I am not set on the syntax.

Something I assume to be easier to implement would be:
**Export File**:
```markdown
This is just _one_ markdown section, which is, potentially the default export...

---

This is a second section, separated by the above `hr`, which can be imported as follows...
```
**Importing file**
```markdown
::import{section="1" from="exporter.md"}

---

::import{section="2" from="exporter.md"}
```

I hope that makes sense.

**Comment by ojeytonwilliams** [comment]
Thanks for clarifying, I had misunderstood.

I like that idea in principle, but probably not in practice.  Reason being, this makes the role of the imported file much less straightforward.  Right now it's just markdown. Except for edge cases like the ones discussed in this PR, it's the same if you wrote that markdown in the original, importing file.  This lets you reuse code, like we want, but is really easy to understand.

If we find more situations where we want the ability to pass in props, the case for this functionality gets stronger.  However, what you described is just a way to pack more things into one file, so I don't think the utility justifies the complexity.

**Review by raisedadead — COMMENTED** [review]
We are going to be doing a head branch rename. I understand this is a high-priority PR. I can stow this on a separate branch on the main repo for now if you all prefer.

**Comment by raisedadead** [comment]
I have stowed this away and we can address the merge conflicts and create a fresh PR when ready.

**Comment by RandellDawson** [comment]
When we decide to pursue this further, I will need to figure out how to best transition this into Crowdin.

**Pull request merged**
