### PR TITLE
Guide Article guide/english/d3 typo and version fixes + D3 DOM Selectors article

### PR DESCRIPTION
**Pull request by sabeersulaiman**
- [x] I have read [freeCodeCamp's contribution guidelines](https://github.com/freeCodeCamp/freeCodeCamp/blob/master/CONTRIBUTING.md).
- [x] My pull request has a descriptive title (not a vague title like `Update index.md`)
- [x] My pull request targets the `master` branch of freeCodeCamp.
- [x] None of my changes are plagiarized from another source without proper attribution.
- [x] My article does not contain shortened URLs or affiliate links.

If your pull request closes a GitHub issue, replace the XXXXX below with the issue number.

Closes #XXXXX

### CODE REVIEW

**Review by thecodingaviator — DISMISSED** [review]
Remove file whose name you changed, use two space indentaion please

**Comment by sabeersulaiman** [comment]
@thecodingaviator are we talking about the code in the markdown ?

**Comment by thecodingaviator** [comment]
@sabeersulaiman Yes, change indent to 2 spaces per indent level

**Review by cmccormack — APPROVED** [review]
This looks good to me 👍.  Thank you for your contribution!

**Pull request merged**
