### PR TITLE
feat(i18n, client): update news links

### PR DESCRIPTION
**Pull request by naomi-lgbt**
Checklist:

- [X] I have read [freeCodeCamp's contribution guidelines](https://contribute.freecodecamp.org).
- [X] My pull request has a descriptive title (not a vague title like `Update index.md`)
- [X] My pull request targets the `master` branch of freeCodeCamp.
- [X] All the files I changed are in the same world language, for example: only English changes, or only Chinese changes, etc.

Closes #XXXXX

This PR updates the news links for the footer - this is on the `next-i18n-client` branch to demonstrate the new flow, so merging this won't land anything on production yet.

@scissorsneedfoodtoo @ahmadabdolsaheb I wanted to create this PR to solicit your feedback on this approach. 🙂

### CODE REVIEW

**Comment by ojeytonwilliams** [comment]
Hey Nick, I was wondering about a couple of things.  Don't these lend themselves to being arrays?  Either 

```
[["What is Docker?",
 "https://freecoodecamp.org/news/what-is-docker-used-for-a-docker-container-tutorial-for-beginners/"]...]
 ``` 

or perhaps with object elements for clarity

```
[{"title": "What is Docker?",
  "link": "https://freecoodecamp.org/news/what-is-docker-used-for-a-docker-container-tutorial-for-beginners/"}...]
 ``` 
 
We can always check the number of elements with a test, if we want more validation.

Also, shouldn't the links be to `www.freecodecamp...` not `freecodecamp...`?  We redirect there, after all.

**Comment by nhcarrigan** [comment]
Hey @ojeytonwilliams,

Would an array structure work with the `i18n` translation plugin? Currently we directly call each property and pass it in to the function:

```jsx
 <Link external={false} to={t('trending:article1link')}>
                  {t('trending:article1title')}
                </Link>
                <Link external={false} to={t('trending:article2link')}>
                  {t('trending:article2title')}
                </Link>
                <Link external={false} to={t('trending:article3link')}>
                  {t('trending:article3title')}
                </Link>
                <Link external={false} to={t('trending:article4link')}>
                  {t('trending:article4title')}
                </Link>
                <Link external={false} to={t('trending:article5link')}>
                  {t('trending:article5title')}
                </Link>
                <Link external={false} to={t('trending:article6link')}>
                  {t('trending:article6title')}
                </Link>
                <Link external={false} to={t('trending:article7link')}>
                  {t('trending:article7title')}
                </Link>
                <Link external={false} to={t('trending:article8link')}>
                  {t('trending:article8title')}
                </Link>
                <Link external={false} to={t('trending:article9link')}>
                  {t('trending:article9title')}
                </Link>
                <Link external={false} to={t('trending:article10link')}>
                  {t('trending:article10title')}
                </Link>
              </div>
```

**Comment by ojeytonwilliams** [comment]
Ah, I was just thinking that it looked a bit repetitive!  So, I dug into the docs and found [this](https://www.i18next.com/translation-function/objects-and-arrays).  Presumably we could write code like this:

```jsx
<Link external={false} to={t('trendingArray.0.link')}>
{t('trendingArray.0.title')}
</Link>
```

Or DRY it out a bit more and use a map:

```jsx
const numbers = [1, 2, 3, 4, 5];
const listItems = numbers.map((number) =>
 <Link external={false} to={t(`trendingArray.$(number).link`)}>
{t('trendingArray.$(number).title')}
</Link>
);

```

**Comment by nhcarrigan** [comment]
I'll play with this a little bit and see what I can get to work. 

I'm planning to ship a PR to our news theme to implement similar functionality, so I'll get something working here first and mirror the changes there later. 🙂

**Comment by ojeytonwilliams** [comment]
> I'll play with this a little bit and see what I can get to work.

Cool.  It would be nice if we could DRY these out, but if I'm missing something and `i18next` doesn't like it, don't spend too long trying to force it.

**Comment by ojeytonwilliams** [comment]
Hey Nick, GitHub was convinced this had a bunch of conflicts, so I cherry-picked this back onto the new `next-i18n-client` branch.

**Comment by ahmadabdolsaheb** [comment]
LGMT. Thanks for taking care of this.

**Comment by ahmadabdolsaheb** [comment]
Also @scissorsneedfoodtoo pointed out that some of the links have an extra o in the ur freecoodecamp.org instead of freecodecamp

**Comment by nhcarrigan** [comment]
Fixed 😅

**Pull request merged**
