### PR TITLE
revert: cypress temporary workaround

### PR DESCRIPTION
**Pull request by moT01**
Reverts https://github.com/freeCodeCamp/freeCodeCamp/pull/45593

Checklist:

- [x] I have read [freeCodeCamp's contribution guidelines](https://contribute.freecodecamp.org).
- [x] My pull request has a descriptive title (not a vague title like `Update index.md`)
- [x] My pull request targets the `main` branch of freeCodeCamp.
- [x] I have tested these changes either locally on my machine, or GitPod.

Closes #XXXXX

### CODE REVIEW

**Comment by raisedadead** [comment]
@moT01 whats with this PR?

**Comment by moT01** [comment]
We had some failing cypress tests that I fixed with the PR in the description. The issue: `https://github.com/cypress-io/cypress/issues/20562`. Once that issue is fixed, we can revert that fix I added with this PR. Looks like they merged a fix - once it's deployed and we update cypress, we should be able to get this in.

**Comment by raisedadead** [comment]
Thanks for sharing the context.

**Comment by raisedadead** [comment]
A quick reminder that they landed a fix for the issue.

**Comment by moT01** [comment]
cypress v9.5.4 has it - so when we update to that or newer, this can go in.

**Review by raisedadead — APPROVED** [review]

**Review by ojeytonwilliams — APPROVED** [review]

**Pull request merged**
