### PR TITLE
remove MDN links from English challenges

### LINKED ISSUE #37827: External links in coding challenges
**Describe your problem and how to reproduce it:**
In a recent pull request (#37802) it was brought to attention that there are external links in coding challenges such as [this one](https://github.com/freeCodeCamp/freeCodeCamp/blob/master/curriculum/challenges/english/02-javascript-algorithms-and-data-structures/basic-javascript/increment-a-number-with-javascript.english.md). Both @RandellDawson and @moT01 thought that it would be a good idea to remove any MDN links found in coding challenges.
I am creating this issue to discuss removing these links and where to possibly move them (such as to the corresponding forum topics, as Randell suggested).

### PR DESCRIPTION
**Pull request by brignano**
Checklist:

- [x] I have read [freeCodeCamp's contribution guidelines](https://contribute.freecodecamp.org).
- [x] My pull request has a descriptive title (not a vague title like `Update index.md`)
- [x] My pull request targets the `master` branch of freeCodeCamp.
- [x] All the files I changed are in the same world language, for example: only English changes, or only Chinese changes, etc.

Closes #37827

> @Sky020 You might try to search https://freecodecamp.org/news to see if you can find a good article there.  Many of the most popular Guide Topics were transported to a corresponding news article.
>
>Currently, there are only 4 challenges with MDN links:
>
>* [Increment a Number with JavaScript](https://www.freecodecamp.org/learn/javascript-algorithms-and-data-structures/basic-javascript/increment-a-number-with-javascript) - The MDN information does not give any further incite to using the `++` operator, so I think we just remove this link all together.  Also, it would not make sense to create an entire news article for this, though we could create a Guide topic on the forum I suppose and make it a wiki.
>
>* [Record Collection](https://www.freecodecamp.org/learn/javascript-algorithms-and-data-structures/basic-javascript/record-collection) - The MDN link relates to the `push` method which is already introduced way before this challenge, so I think we can just delete this link.
>
>* [Change Text Inside an Element Using jQuery]() - The MDN link here (https://developer.mozilla.org/en-US/docs/Web/HTML/Element/em) actually has some merit.  I think we could either create a news article or a forum Guide topic with similar information and examples and link to it instead.
>
>* [Use Assert.isOK and Assert.isNotOK](https://www.freecodecamp.org/learn/quality-assurance/quality-assurance-and-testing-with-chai/use-assert-isok-and-assert-isnotok) - The Truthy and Falsy MDN links could be replaced by a link to the [Falsy Bouncer](https://www.freecodecamp.org/learn/javascript-algorithms-and-data-structures/basic-algorithm-scripting/falsy-bouncer) challenge or a news or forum article covering the information in more detail.
>
>The above is just my thoughts on the links.  If at all possible, I think the links to MDN should be removed.
>
_Originally posted by @RandellDawson in https://github.com/freeCodeCamp/freeCodeCamp/issues/37827#issuecomment-665854174_

# Todo
- [x] Increment a Number with JavaScript
- [x] Change Text Inside an Element Using jQuery
- [x] Use Assert.isOK and Assert.isNotOK
#### What verbiage do we want here?

- [x] Record Collection

> @RandellDawson , That is excellent! In this case, I suggest because other members were in agreement in the linked PR, we open this to _help wanted_ (or _first-timers_), and do as you have suggested above.
> 
> One point on my side:
> 
> > Record Collection - The MDN link relates to the push method which is already introduced way before this challenge, so I think we can just delete this link.
> 
> Instead of removing the link, I suggest it be changed to direct to the challenge that introduces the `push` method.
> 
> So, if you agree, Randell, I leave it to you to open this to _first-timers_ or otherwise.
_Originally posted by @Sky020 in https://github.com/freeCodeCamp/freeCodeCamp/issues/37827#issuecomment-665927113_

### CODE REVIEW

**Comment by scissorsneedfoodtoo** [comment]
Hi @brignano, thanks for taking the time to create this PR.

For Record Collection, the first challenge to introduce `push` is here: https://www.freecodecamp.org/learn/javascript-algorithms-and-data-structures/basic-javascript/manipulate-arrays-with-push

We could link to that challenge instead of removing the link. For verbiage, maybe something like:

```
The `push` array method will be helpful here. Check out our <a href="https://www.freecodecamp.org/learn/javascript-algorithms-and-data-structures/basic-javascript/manipulate-arrays-with-push" target="_blank">Manipulate Arrays With push()</a> challenge to review how it works.
```

**Comment by brignano** [comment]
Thanks for the quick response @scissorsneedfoodtoo :partying_face: 

Record collection should be all set now as per your feedback.

Just want to confirm the verbiage I used for ```Use Assert.isOK and Assert.isNotOK```,

https://github.com/freeCodeCamp/freeCodeCamp/blob/0a1a2b133f554db7df3705d2bc22965983971e84/curriculum/challenges/english/06-quality-assurance/quality-assurance-and-testing-with-chai/use-assert.isok-and-assert.isnotok.english.md#L15

Also, as per https://github.com/freeCodeCamp/freeCodeCamp/issues/37827#issuecomment-666066362, please let me know if there's anything I can contribute regarding the news article referenced in the below comment.

> Change Text Inside an Element Using jQuery - The MDN link here (https://developer.mozilla.org/en-US/docs/Web/HTML/Element/em) actually has some merit. I think we could either create a news article or a forum Guide topic with similar information and examples and link to it instead.

Thanks again!

**Comment by scissorsneedfoodtoo** [comment]
@brignano, awesome, thanks for updating that so quickly. There wasn't a great resource on `<em>` elements on News, so I updated an existing article: https://www.freecodecamp.org/news/html-elements-explained-what-are-html-tags/#em-element

Would you mind adding that to your PR?

Also, I think the verbiage for the Use Assert.isOK and Assert.isNotOK sounds great. What do you think @RandellDawson?

**Comment by brignano** [comment]
Great @scissorsneedfoodtoo thanks for sharing the updated News article :+1: 

I have updated both files as per your latest comments.

**Review by RandellDawson — APPROVED** [review]
LGTM

**Comment by RandellDawson** [comment]
@scissorsneedfoodtoo If you are happy with the changes, I think it is ready to merge.

**Comment by scissorsneedfoodtoo** [comment]
:sparkles: :sparkles: :sparkles: Congratulations on your first contribution to freeCodeCamp! :sparkles: :sparkles: :sparkles:

Thank you for this quick fix, @brignano. Looking forward to your next contribution.

**Pull request merged**
