### PR TITLE
Fixed broken link in challenge manipulating complex objects

### LINKED ISSUE #9704: Broken link in challenge manipulating complex objects
#### Challenge Name

https://www.freecodecamp.com/challenges/manipulating-complex-objects

#### Issue Description

When you click on the link labeled "JavaScript Object Notation", you get a ERR_SSL_PROTOCOL_ERROR.
In the source code, we have: "href='//json.org/'"
By default, the browser replaces "//" by "https://", but the Json.org page doesn't support SSL.
I advise to use "http://www.json.org/" instead.

#### Browser Information

* Browser Name, Version: Chrome (latest), but also reproduced with my Safari
* Operating System: Mac OS X
* Mobile, Desktop, or Tablet: Desktop

#### Your Code

```js
 
```

### PR DESCRIPTION
**Pull request by Jaskaranbir**
#### Pre-Submission Checklist
- [x] Your pull request targets the `staging` branch of FreeCodeCamp.
- [x] Branch starts with either `fix/`, `feature/`, or `translate/` (e.g. `fix/signin-issue`)
- [x] You have only one commit (if not, [squash](https://github.com/FreeCodeCamp/FreeCodeCamp/wiki/Git-Squash) them into one commit).
- [x] All new and existing tests pass the command `npm run test-challenges`. Use `git commit --amend` to amend any fixes.
#### Type of Change
- [x] Small bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds new functionality)
- [ ] Breaking change (fix or feature that would change existing functionality)
- [ ] Add new translation (feature adding new translations)
#### Checklist:
- [x] Tested changes locally.
- [x] Closes currently open issue (replace XXXX with an issue no): Closes #9704 
#### Description

Fixes JSON link in documentation of challenge: https://www.freecodecamp.com/challenges/manipulating-complex-objects.

### CODE REVIEW

**Comment by raisedadead** [comment]
@Jaskaranbir thanks a lot for this PR. 

The nos on the top of the page are brownie points and not challenge nos. I understand that the issue creator and many campers aren't aware of this. Refer this [comment](https://github.com/FreeCodeCamp/FreeCodeCamp/issues/9704#issuecomment-232300656)

Can you please update the commit message to something like below:
`Fixed broken link in challenge manipulating complex objects`

To do the change:

1. `git checkout fix/json-link-challenge-208`
2. `git commit --amend`
3. Change the commit message
4. `git push origin fix/json-link-challenge-208 --force`

Next change the PR title on the top of this page as well with the edit option.

Thanks.

**Comment by Jaskaranbir** [comment]
@raisedadead ah I see. My bad; fixed it now. I did know about brownie system, I just got a bit (silly?) and followed the issue description point-on. Thanks for tip though.

**Comment by raisedadead** [comment]
@Jaskaranbir you closed the pull request.

**Comment by Jaskaranbir** [comment]
@raisedadead shoot! Accidental touch while browsing on mobile (although I almost instantly closed tab so I didnt notice). But anyway, to reopen, google searching gave me this result:

```
Delete the branch using the button in the GitHub PR.
Move the branch back to where the last PR sha is locally.
Push the branch again.
Reopen the PR.
```

Does that mean I will have to delete the branch in my forked repo and push it again; then create another pull request?

**Comment by raisedadead** [comment]
@Jaskaranbir Yeah happens all the time. No need for that above steps. Trust me Google is drunk at times.

You haven't deleted the branch.

You can click on reopen pull request and comment button below, on this thread. If that is disabled or doesn't work  just head over to GitHub (preferably on a desktop) and head to your branches.

https://github.com/Jaskaranbir/FreeCodeCamp/branches

There you should see a compare button besides this branch.
Just make a new pull request from there as you did last time.

That should work.
Hit us up on the contributors chat if you need any assistance.

**Comment by Jaskaranbir** [comment]
@raisedadead thanks. Create new PR here: https://github.com/FreeCodeCamp/FreeCodeCamp/pull/9710 (the reopen PR button was disabled for me).

**Pull request closed without merging**
