### PR TITLE
The cmd and ctrl button now both trigger events

### LINKED ISSUE #1256: Suggestion: Allow use of ⌘+Enter on OS X to advance
This would be much more intuitive / ergonomic for mac users imho as opposed to ctrl-enter, and mimics gmail keystroke behavior on mac browsers. :)

### PR DESCRIPTION
**Pull request by junhaoyap**
Closes #1256

### CODE REVIEW

**Comment by ltegman** [comment]
Glad to see this getting a PR :smile:. I haven't had time to look into why, but I can't get Cmd-Enter to work from the showVideo or showZiplineOrBaseJump views, only from the Bonfire view.

**Comment by junhaoyap** [comment]
I needed this for myself too, it just feels so weird to press ctrl-enter on my Mac when going through the lessons :\ I hope when it's done it'll benefit all the Mac users out there!

Alright thanks for alerting me on that, I tried it on the challenges page and assumed it work, my bad on that, I'll look into it one of these days and give it a fix :)

**Comment by ltegman** [comment]
Looks like this stems from the event being bound being `keypress`. Keypress signifies a key being pressed inside a text entry area, which isn't want we're doing on these pages. I don't know why it works with Ctrl-Enter and not Cmd-Enter, but changing the event binding to `keydown` seems to solve the problem. `keydown` also seems like the more appropriate event to be binding since we aren't using a text entry element.

**Comment by junhaoyap** [comment]
Indeed, I did see somewhere where it mentions that ```.metaKey``` only works on keydown and not on keypress, I'll update this PR and squash the commits and ping you tomorrow :)

Apart from technicalities, did I manage to get the binary operators styling right?

**Comment by ltegman** [comment]
Yup, that part looks good to me :+1:

**Comment by junhaoyap** [comment]
Great, I'll get to it after work, thanks for the review, again :)

**Comment by junhaoyap** [comment]
@ltegman it's done :)

**Comment by ltegman** [comment]
Great work! :+1:

**Pull request merged**
