### PR TITLE
Fix closing / </code> causing styling error.

### LINKED ISSUE #9756: Text formatting
#### Challenge Name
https://www.freecodecamp.com/challenges/accessing-nested-objects

#### Issue Description
In the paragraph with instructions, the highlight term styling extends beyond where it should be, starting with the word "gloveBoxContents." It continues into other line breaks and into the subsequent pop-up window (run tests, reset, bug). The screenshots included here are from "night mode" but the problem occurs in the default setting colors as well.

#### Screenshots
nested-obj-styling-screenshot
nested-obj-styling-screenshot2
nested-obj-styling-screenshot3
nested-obj-styling-screenshot4

### PR DESCRIPTION
**Pull request by benschac**
#### Pre-Submission Checklist

- [x] Your pull request targets the `staging` branch of FreeCodeCamp.
- [x] Branch starts with either `fix/`, `feature/`, or `translate/` (e.g. `fix/signin-issue`)
- [x] You have only one commit (if not, [squash](https://github.com/FreeCodeCamp/FreeCodeCamp/wiki/Git-Squash) them into one commit).
- [x] All new and existing tests pass the command `npm run test-challenges`. Use `git commit --amend` to amend any fixes.
#### Type of Change

- [x] Small bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds new functionality)
- [ ] Breaking change (fix or feature that would change existing functionality)
- [ ] Add new translation (feature adding new translations)
#### Checklist:

- [x] Tested changes locally.
- [ ] Closes currently open issue (replace XXXX with an issue no): Closes #9756
#### Description

This fix adds a / to the closing code block that was causing a styling issue in the challenge.

### CODE REVIEW

**Comment by benschac** [comment]
@erictleung @alayek first first FCC PR eeeeeeek!  Please let me know if I burned everything to the ground :)

**Comment by alayek** [comment]
# LGTM :+1:  

Let's :shipit: :package: @erictleung what say?

**Comment by erictleung** [comment]
@benschac LGTM to be too! 👍  Thanks for your contribution to FreeCodeCamp! ✨ 🎉 ✨

**Comment by benschac** [comment]
yay! when does the change hit production? :)

**Comment by alayek** [comment]
@benschac when the `staging` branch merges with the `master` and our coreteam does a deployment on our servers.

**Comment by benschac** [comment]
> when the staging branch merges with the master

How often is that? :eager:

**Comment by erictleung** [comment]
@benschac about once a week. You'll get a notification about it 😃

**Pull request merged**
