### PR TITLE
Added solution to D3 predefined scale challenge

### PR DESCRIPTION
**Pull request by thecodingaviator**
- [x] I have read [freeCodeCamp's contribution guidelines](https://github.com/freeCodeCamp/freeCodeCamp/blob/master/CONTRIBUTING.md).
- [x] My pull request has a descriptive title (not a vague title like `Update index.md`)
- [x] My pull request targets the `master` branch of freeCodeCamp.
- [x] None of my changes are plagiarized from another source without proper attribution.
- [x] My article does not contain shortened URLs or affiliate links.

If your pull request closes a GitHub issue, replace the XXXXX below with the issue number.

Closes #XXXXX

### CODE REVIEW

**Comment by RandellDawson** [comment]
@thecodingaviator The solution passes the tests. The solution would look much better with 2 space indentation as well as the challenge seed code (which is beyond the scope of this PR). Would you mind reformatting the solution for the article. I will create a separate PR to indent all of these D3 challengess' seed code.

**Comment by thecodingaviator** [comment]
@RandellDawson how does it look now?

**Comment by RandellDawson** [comment]
@thecodingaviator That does look better.  If you want the right bracket of each subarray (see below) to line up, I think the following:
````
```js
    const dataset = [
      [ 34,     78 ],
      [ 109,   280 ],
      [ 310,   120 ],
      [ 79,   411 ],
      [ 420,   220 ],
      [ 233,   145 ],
      [ 333,   96 ],
      [ 222,    333 ],
      [ 78,    320 ],
      [ 21,   123 ]
    ];
```
````
would display better as:
````
```js
    const dataset = [
      [ 34,   78 ],
      [ 109, 280 ],
      [ 310, 120 ],
      [ 79,  411 ],
      [ 420, 220 ],
      [ 233, 145 ],
      [ 333,  96 ],
      [ 222  333 ],
      [ 78,  320 ],
      [ 21,  123 ]
    ];
```
````

FYI - I did not test this locally, but when I view it on the GitHub site, it seems to line up correctly. What do you think?

The same thing could be done with the other PR (#34241).

**Review by moT01 — APPROVED** [review]
LGTM @thecodingaviator 🎉

**Comment by RandellDawson** [comment]
@thecodingaviator If the goal was to make the right brackets line up, the current changes do not do that (see below):
image
If you want them to line up (like below): 
image

then you will need to change lines 46 thru 55 to the following:
```
      [ 34,   78 ],
      [ 109, 280 ],
      [ 310, 120 ],
      [ 79,  411 ],
      [ 420, 220 ],
      [ 233, 145 ],
      [ 333,  96 ],
      [ 222, 333 ],
      [ 78,  320 ],
      [ 21,  123 ]
```

**Comment by moT01** [comment]
I noticed that - If you're going to line them up - you should line up the numbers by like the denomination I think would be best...
```
      [  34,  78 ],
      [ 109, 280 ],
      [ 310, 120 ],
      [  79, 411 ],
      [ 420, 220 ],
      [ 233, 145 ],
      [ 333,  96 ],
      [ 222, 333 ],
      [  78, 320 ],
      [  21, 123 ]
```

**Comment by RandellDawson** [comment]
I do like @moT01's version too.  I think either will work as long as the right side brackets align.

**Comment by RandellDawson** [comment]
@thecodingaviator I think this looks good now.  Thank you.

**Pull request merged**
