### PR TITLE
feat(learn): c# solution links now lead to user trophies

### LINKED ISSUE #53073: MSLearn C# Course - Timeline - View button - User is shown a JSON object instead of the appropriate achievement page
**Describe the bug**
The "View" button on the public profile Timeline leads to webpage serving a JSON object for the MS Learn C# course trophy achievements in the feed.

Example:
https://learn.microsoft.com/api/gamestatus/f1787997-8b19-4837-bdeb-ad536637b5dd

**To Reproduce**
1. Complete a module on the Microsoft Learn C# course and verify the trophy on freeCodeCamp
2. Go to the user's public profile
3. Scroll down to the Timeline
4. Click on the "View" button for your trophy achievement

**Expected behavior**
1 of these 2 options could work:

The link leads to the "Learning Paths" tab of the Achievements section of the user's Microsoft Learn public profile.
Example:
https://learn.microsoft.com/en-us/users/stevenboutcher-4303/achievements?tab=tab-learning-paths

OR

The link leads to the achievement's own shareable page.
Example:
https://learn.microsoft.com/en-us/users/stevenboutcher-4303/achievements/24uqr9cv

**Screenshots**
fcc_bug_1
fcc_bug_2

**Desktop:**
 - OS: macOS Sonoma (14.1)
 - Browser: Chrome
 - Chrome Version: 120.0.6099.199

### PR DESCRIPTION
**Pull request by Lil-Nugs**
Checklist:

- [x] I have read and followed the [contribution guidelines](https://contribute.freecodecamp.org).
- [x] I have read and followed the [how to open a pull request guide](https://contribute.freecodecamp.org/#/how-to-open-a-pull-request).
- [x] My pull request targets the `main` branch of freeCodeCamp.
- [x] I have tested these changes either locally on my machine, or GitPod.

Closes #53073

Added a helper function to get the trophy ID based on the challenge ID you feed it. Makes it easier to generate links in the test file + grab it in the route file.

### CODE REVIEW

**Comment by ojeytonwilliams** [comment]
Thanks for putting this together, @mccarreon, it looks good! The only issue I see is that it only targets the new api and not the existing one (in /api-server). While we do plan to ship the new version, it will likely be at least a month before we do.

@moT01 can you confirm that this is the desired behaviour? If so, @mccarreon could you implement the feature in the old api?

**Comment by mccarreon** [comment]
Ah yep- added!

**Comment by ojeytonwilliams** [comment]
> Ah yep- added!

Thanks!

> Would it be good to add a section mentioning the api-server/ folder is the current production api directory?

Yeah, I think it's misleading at the moment.

**Comment by moT01** [comment]
Thanks for working on this @mccarreon. I think I might prefer to leave the API as it is and just generate the URL on the client with the info we have... 

1. We are already saving the solutions in the database as `https://learn.microsoft.com/api/gamestatus/${msUserId}`. So if we change it to the new format, there will be inconsistencies with the solutions in the database.
2. We don't really know what those ID's are, and it's possible they could change or something. From the issue, the ID the OP had for the first trophy is `24uqr9cv`, for a URL of https://learn.microsoft.com/en-us/users/stevenboutcher-4303/achievements/24uqr9cv - the ID I found when looking at my profile is what we use here, `yzhut2fr` - when you plug that into the URL, it works as well: https://learn.microsoft.com/en-us/users/stevenboutcher-4303/achievements/yzhut2fr

And looking at this now, we may have to scrap this solution... Opening those two URLs shows the user completed the trophy on a different date. The latter is the date I completed it, and the former is when the issue creator completed it. I didn't notice that before - I probably should have caught that. So if we use these ID's, it will show that everyone completed the trophy when I did. Perhaps that's fine, but I'm not a big fan. Wondering if we should just link to the users profile for now: https://learn.microsoft.com/users/mot01/ - and perhaps something will come along on MS's end where we will be able to link to the trophy without using the ID's.

What do you think @mccarreon @ojeytonwilliams ?

**Comment by mccarreon** [comment]
Oh right I wasn't even thinking about the migration you'd have to do to sync things up. 

Yeah just having it generated on the client and have it link to their profile seems like it'd be good for now.

**Comment by ojeytonwilliams** [comment]
> We are already saving the solutions in the database as https://learn.microsoft.com/api/gamestatus/${msUserId}. So if we change it to the new format, there will be inconsistencies with the solutions in the database.

My understanding was that the gamestatus api was the one we're expected to use. So, if we went this route, we'd need to store both the shared trophy url and the gamestatus id.

>  Wondering if we should just link to the users profile for now: https://learn.microsoft.com/users/mot01/ - and perhaps something will come along on MS's end where we will be able to link to the trophy without using the ID's.

Sounds good. It's better UX than linking to the api endpoint and doesn't have any obvious issues.

**Comment by moT01** [comment]
hey @mccarreon - any interest in adjusting this PR to use the solution I mentioned?

**Comment by Sembauke** [comment]
Hey @mccarreon I am going to open this for other contributors, please feel free to re-open this if you are still interested.

**Pull request closed without merging**
