### PR TITLE
Update instructions to provide implicit information in Accessing Nested Objects Challenge

### LINKED ISSUE #36080: Accessing Nested Objects challenge could use a small change in instructions
Based on [this forum thread discussion](w.freecodecamp.org/forum/t/accessing-nested-objects/136398/) and others like it, I am wondering if we should slightly modify the instructions for the [Accessing Nested Objects](https://learn.freecodecamp.org/javascript-algorithms-and-data-structures/basic-javascript/accessing-nested-objects/) challenge.

The last test is written to only accept a solution were the properties "car" and "inside" must use dot notation and the "glove box" property (of course) has to use bracket notation.  The instructions only state the camper to use bracket notation on the "glove box", but does not make it clear bracket notation can not be used on "car" and "inside".  Many campers don't understand why their solution (which would technically get the "glove box" property's value) fails the last test.  With the current instructions, all three of the following should be accepted because the only real requirement in the current instructions is "Use bracket notation for properties with a space in their name."

```
var gloveBoxContents = myStorage.car.inside["glove box"];
var gloveBoxContents = myStorage.car["inside"]["glove box"];
var gloveBoxContents = myStorage["car"].inside["glove box"];
```

Since it is a "best practice" for more readable code to use dot notation where possible, I am wondering what others think about changing the instructions to something like the following:

> Access the `myStorage` object and assign the contents of the `glove box` property to the `gloveBoxContents` variable. Use dot notation for all properties where possible, otherwise use bracket notation.

This way the existing test can be used and the camper gets to use the knowledge they have already obtained from previous lessons (i.e. properties with spaces need bracket notation) without us explicitly telling them to use bracket notation (which felt a bit like hand-holding to me).

### PR DESCRIPTION
**Pull request by NoobyScoob**
- [x] I have read [freeCodeCamp's contribution guidelines](https://github.com/freeCodeCamp/freeCodeCamp/blob/master/CONTRIBUTING.md).
- [x] My pull request has a descriptive title (not a vague title like `Update index.md`)
- [x] My pull request targets the `master` branch of freeCodeCamp.
- [x] None of my changes are plagiarized from another source without proper attribution.
- [x] All the files I changed are in the same world language (for example: only English changes, or only Chinese changes, etc.)
- [x] My changes do not use shortened URLs or affiliate links.

Closes #36080

### CODE REVIEW

**Review by ojeytonwilliams — APPROVED** [review]
LGTM :+1:

**Review by RandellDawson — APPROVED** [review]
LGTM

**Comment by RandellDawson** [comment]
Congrats @NoobyScoob on your first pull request (PR)! 🎉

Thank you for your contribution to the page! 👍
We're happy to accept these changes, and look forward to future contributions. 📝

**Comment by NoobyScoob** [comment]
Thank you @RandellDawson I really like to contribute. Love Freecodecamp!
BTW how can I add emote here?

**Pull request merged**
