### PR TITLE
Updated this page to match its English version

### PR DESCRIPTION
**Pull request by dennislixin**
- [x] I have read [freeCodeCamp's contribution guidelines](https://github.com/freeCodeCamp/freeCodeCamp/blob/master/CONTRIBUTING.md).
- [x] My pull request has a descriptive title (not a vague title like `Update index.md`)
- [x] My pull request targets the `master` branch of freeCodeCamp.
- [x] None of my changes are plagiarized from another source without proper attribution.
- [x] My article does not contain shortened URLs or affiliate links.

If your pull request closes a GitHub issue, replace the XXXXX below with the issue number.

Closes #XXXXX

### CODE REVIEW

**Comment by RandellDawson** [comment]
Closed and Reopened this PR to attempt to resolve a specific Travis build failure.

**Review by dingjy94 — CHANGES_REQUESTED** [review]
Hey, thank you for your contribution!

However, I cannot approve the merge since there are some markdown syntax error. Please fix these error, and use the rich diff view to check the effect and make sure the page looks good. Thank you!

**Comment by dennislixin** [comment]
I have fixed the markdown syntax errors I can find. 
Please let me know if I miss anything. 
Thanks.

**Review by dingjy94 — APPROVED** [review]

**Comment by dingjy94** [comment]
@dennislixin Thank you for your quick response, I will merge this PR.

Thank you for your contribution to the page! 👍 We're happy to accept these changes and look forward to future contributions.

**Pull request merged**
