### PR TITLE
refrased unclear instructions for Create Bootstrap Wells

### PR DESCRIPTION
**Pull request by saadanerdetbare**
Targets https://github.com/FreeCodeCamp/FreeCodeCamp/issues/1968
https://github.com/FreeCodeCamp/FreeCodeCamp/issues/2016
https://github.com/FreeCodeCamp/FreeCodeCamp/issues/2042
https://github.com/FreeCodeCamp/FreeCodeCamp/issues/2130
Reworded instructions

### CODE REVIEW

**Comment by bugron** [comment]
@saadanerdetbare, unfortunately, this branch also has conflicts with FCC's staging branch. Please resolve these conflicts and push your changes back, thanks!

**Comment by saadanerdetbare** [comment]
pr is rebased ontop of staging

**Comment by BerkeleyTrue** [comment]
@saadanerdetbare unfortunately it looks like things have moved around again. Can you rebase once again?

@bugron Where you able to test out the new tests here so we can merge this as soon as the PR is rebased?

**Comment by bugron** [comment]
@BerkeleyTrue I think these new `assert`s are unnecessary and they are duplicating existing ones.

**Comment by BerkeleyTrue** [comment]
@bugron Agreed.

@saadanerdetbare Thanks for the PR. There is another PR that changes the description that should address this issue.

Happy Coding.

**Pull request closed without merging**
