### PR TITLE
fix(seed): Correct typos in es6.json

### PR DESCRIPTION
**Pull request by PolarisTLX**
#### Pre-Submission Checklist

- [x] Your pull request targets the `staging` branch of freeCodeCamp.
- [x] Branch starts with either `fix/`, `feature/`, or `translate/` (e.g. `fix/signin-issue`)
- [x] You have only one commit (if not, [squash](http://forum.freecodecamp.org/t/how-to-squash-multiple-commits-into-one-with-git/13231) them into one commit).
- [x] All new and existing tests pass the command `npm test`. Use `git commit --amend` to amend any fixes.

#### Type of Change

- [x] Small bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds new functionality)
- [ ] Breaking change (fix or feature that would change existing functionality)
- [ ] Add new translation (feature adding new translations)

#### Checklist:

- [x] Tested changes locally.
- [ ] Addressed currently open issue (replace XXXXX with an issue no in next line)

Closes # N/A

#### Description

File: es6.json

1. Challenge Title: "Use the Rest Operator with Function Parameters"
  Typo "so that is uses the..."  fixed to "so that it uses the..."

2. Challenge Title: "Write Concise Object Literal Declarations Using Simple Fields"
  Typo: "for easily definining object" fixed to "for easily defining object"

3. Challenge Title: "Use getters and setters to Control Access to an Object"
  Typo1: "accepts Farenheit temperature"  fixed to "accepts Fahrenheit temperature"

  Typo2: "const thermos = new Thermostat(76); // setting in Farenheit scale"  
             fixed to "const thermos = new Thermostat(76); // setting in Fahrenheit scale"

By Paul (@PolarisTLX) and Kyle (@jklemon17)

### CODE REVIEW

**Review by ojongerius — APPROVED** [review]
Thank you!

**Comment by ojongerius** [comment]
@PolarisTLX you  mention this was done by you and Kyle (@jklemon17). Would you like to amend your commit and add him as co author?
You will be able to amend your commit with `git commit --amend` and add him as a co author, per 
 https://help.github.com/articles/creating-a-commit-with-multiple-authors . You'll have to use force to push this but that's fine in your own fork: `git push --force`.

**Comment by PolarisTLX** [comment]
@ojongerius   Yes we were not sure that we could amend a commit but yes we will do that, likely sometime tomorrow, thanks for the heads up!

**Comment by PolarisTLX** [comment]
Alright we tried to amend the commit message and believe it should now be including the "Co-authored-by: Kyle <james.kyle.lemon@gmail.com>"  though the user interface is not very friendly and would not allow us to put it in a new line like the  co-authored instructions tell us to.
Let me know if any more changes are needed, thanks.

**Review by raisedadead — APPROVED** [review]
Nice work! Thanks for the PR

**Comment by PolarisTLX** [comment]
You are welcome, though I don't think the  "Co-authored-by: Kyle james.kyle.lemon@gmail.com"  worked as he is not listed as a contributor in the commit still.  I think because that text needs to be on a new line (which we tried to do but it did not work).
co-author

**Pull request merged**
