### PR TITLE
feat: convert c-sharp exam tests to Playwright

### PR DESCRIPTION
**Pull request by Sembauke**
Checklist:

- [x] I have read and followed the [contribution guidelines](https://contribute.freecodecamp.org).
- [x] I have read and followed the [how to open a pull request guide](https://contribute.freecodecamp.org/#/how-to-open-a-pull-request).
- [x] My pull request targets the `main` branch of freeCodeCamp.
- [x] I have tested these changes either locally on my machine, or GitPod.

## Note

`Should show prerequisites alert and have "start exam" button disabled'` is covered in`exam-show-qualified.spec.ts`

### CODE REVIEW

**Review by naomi-lgbt — APPROVED** [review]

**Review by moT01 — COMMENTED** [review]
I'm getting an issue locally when running the different browsers sequentially...

Screenshot 2024-05-31 at 9 52 17 AM

After the first run, the survey isn't getting reset. So when the next browser goes to the page, the survey is already completed. The script to delete the surveys doesn't delete the survey that gets added cause it has a different ID when it gets created by the test. We could run a query in this file to delete all surveys with the certified user ID?

**Comment by Sembauke** [comment]
Alright @moT01 this should be good now.

**Comment by Sembauke** [comment]
It does use an additional parameter, but sure, no worries. Thanks for the help. 

The Firefox tests seem to be failing though.

**Comment by Sembauke** [comment]
@moT01 Can you give this one another look?

**Review by moT01 — APPROVED** [review]

**Pull request merged**
