### PR TITLE
Fix Get JSON with the jQuery getJSON Method

### LINKED ISSUE #8543: Issue in Get JSON with Jquery getJSON method challenge
#### Challenge Name
Get JSON with the jQuery getJSON Method
[Challenge Link](https://www.freecodecamp.com/challenges/get-json-with-the-jquery-getjson-method)

#### Issue Description
Eventhough my solution is right, the tests don't pass.

#### Browser Information

* Browser Name, Version: Google Chrome 50.0.2661.94 (Official Build) (64-bit) 
* Operating System: Linux
* Mobile, Desktop, or Tablet: Laptop

#### My Code

```
$("#getMessage").on("click", function(){
      
      $.getJSON("/json/cats.json", function(data){
        $(".message").html(JSON.stringify(data));
      });
      
});
```

#### Screenshot
solution_not_working

### PR DESCRIPTION
**Pull request by arku**
#### Pre-Submission Checklist

- [x] Your pull request targets the `staging` branch of FreeCodeCamp.
- [x] Branch starts with either `fix/`, `feature/`, or `translate/` (e.g. `fix/signin-issue`)
- [x] You have only one commit (if not, [squash](https://github.com/FreeCodeCamp/FreeCodeCamp/wiki/git-rebase#squashing-multiple-commits-into-one) them into one commit).
- [x] All new and existing tests pass the command `npm run test-challenges`. Use `git commit --amend` to amend any fixes.
#### Type of Change

- [x] Small bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds new functionality)
- [ ] Breaking change (fix or feature that would change existing functionality)
- [ ] Add new translation (feature adding new translations)
#### Checklist:

- [x] Tested changes locally.
- [x] Closes currently open issue (replace 8543 with an issue no): Closes #8543
#### Description

Removed case-senstitive flags from the tests and added a test to capture the parameter name from the callback method and checked whether its same as that of the variable used inside the callback method.

### CODE REVIEW

**Comment by atjonathan** [comment]
### **LGTM :+1:**

**Comment by raisedadead** [comment]
Thanks for the PR, but the regex is not allowing for conventional variable naming
```
$.getJSON("/json/cats.json", function(var2) {
         $(".message").html(JSON.stringify(var2));
});
```

> `var2` is a valid variable name.

**Comment by arun1595** [comment]
Good catch. I will fix that now.

**Comment by raisedadead** [comment]
@atjonathan will you be testing and merging?

**Comment by atjonathan** [comment]
@raisedadead, I've already tested. If you're up for it, you could merge, so we we have a second reviewer!

**Comment by raisedadead** [comment]
#### :sparkles: :sparkles: **LGTM.** :sparkles: :sparkles: 

Thanks.

**Pull request merged**
