### PR TITLE
Announcement feature

### LINKED ISSUE #7946: Create a standard global alert that shows up on every page until dismissed
We want a good way to share important announcements right on freecodecamp.com with authenticated users.

For returning users (not first-time users) we want a flash message that appears and doesn't go away until dismissed, but once it's dismissed, it writes to local storage and doesn't show up again.

When we reset the message, it shows up in everyone's browsers again (including the ones who dismissed the previous one) until they dismiss it again.

This message should be changeable by people who have access to the production database (me and @BerkeleyTrue) without the need for creating a pull request by modifying an object in the database.

### PR DESCRIPTION
**Pull request by benmcmahon100**
This allows for announcements to be set so that they are displayed to the end user when visiting the site.
~ The announcements are set manually by @QuincyLarson or @BerkeleyTrue by directly editing the BillBoard object in the database.

closes #7946

### CODE REVIEW

**Comment by BerkeleyTrue** [comment]
The API should be moved to use loopback's built in methods. See https://github.com/FreeCodeCamp/FreeCodeCamp/blob/staging/common/models/user.js#L239

**Comment by benmcmahon100** [comment]
Foot notes:
    Flyers require:
        id (string)
        message (string)
        active (boolean)

image

**Comment by BerkeleyTrue** [comment]
Don't forget to push up your changes

**Comment by benmcmahon100** [comment]
@BerkeleyTrue ha ha almost did but not quite! ;)

**Comment by QuincyLarson** [comment]
Dibs. I'm going to fix @benmcmahon100's failing lint errors myself.

**Comment by QuincyLarson** [comment]
@benmcmahon100 did that last commit fix the issue? Should we QA again?

**Comment by benmcmahon100** [comment]
Everything should be perfect. If you could try a tonne of different messages to if any break my system. Other than that we were able to work it in incognito mode last night

**Comment by QuincyLarson** [comment]
I verified that this now works even in an incognito tab.

**Pull request merged**
