### PR TITLE
Update make-a-person challenge to support ES6 classes

### LINKED ISSUE #8096: Allowing ES6 Classes in Basic Algorithms and ES5 Challenges
#### Challenge Name

https://www.freecodecamp.com/challenges/make-a-person
#### Issue Description

the code provided below should work, but it's failing the checks for a count and an undefined check
#### Browser Information

- Browser Name, Version: Firefox Dev
- Operating System: Linux Ubuntu / windows 10
- Mobile, Desktop, or Tablet: Desktop
#### Your Code

``` js
"use strict";

class Person {
    constructor(firstAndLast) {
        this.setFullName(firstAndLast);
    }
    setFirstName(first) {
        this.firstName = first;
    }
    setLastName(last) {
        this.lastName = last;
    }
    setFullName(firstAndLast) {
        var arr = firstAndLast.split(' ');
        if(arr.length <= 2) {
            this.firstName = arr[0];
            this.lastName = arr[1];
        } else {
            console.log('That is not a valid name');
        }
    }
    getFirstName() {
        return this.firstName;
    }
    getLastName() {
        return this.lastName;
    }
    getFullName() {
        return `${this.firstName} ${this.lastName}`;
    }
}


var bob = new Person("Bob Ross");

```

### PR DESCRIPTION
**Pull request by mpontus**
This PR addresses issue #8096 and enables ES6 class solution to pass the test.

#### Pre-Submission Checklist
- [ ] Your pull request targets the `staging` branch of freeCodeCamp.
- [x] Branch starts with either `fix/`, `feature/`, or `translate/` (e.g. `fix/signin-issue`)
- [x] You have only one commit (if not, [squash](http://forum.freecodecamp.org/t/how-to-squash-multiple-commits-into-one-with-git/13231) them into one commit).
- [x] All new and existing tests pass the command `npm test`. Use `git commit --amend` to amend any fixes.

#### Type of Change
- [ ] Small bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds new functionality)
- [ ] Breaking change (fix or feature that would change existing functionality)
- [ ] Add new translation (feature adding new translations)

#### Checklist:
- [x] Tested changes locally.
- [x] Addressed currently open issue

Closes #8096

#### Description
Three of the tests had to be removed: class solution does not expose methods as public properties, and does permit access to internal attributes. Exercise description has been altered accordingly.

Another problem with classes is global scope. Evaluating the code multiple times results in an error unless the scope is refreshed. Proposed solution involves reloading an iframe. It also makes it possible to use `const` in global scope throughout all exercises.

### CODE REVIEW

**Comment by QuincyLarson** [comment]
@BerkeleyTrue since this is touching the testing framework itself, could you take a look at this one?

**Review by BerkeleyTrue — APPROVED** [review]
code LGTM

**Comment by QuincyLarson** [comment]
@BerkeleyTrue OK - if you're confident this is safe to merge, could you merge and we can deploy next time we do a deploy?

**Comment by BerkeleyTrue** [comment]
@QuincyLarson Alright I'll pull this down and test it

**Comment by raisedadead** [comment]
Hi @mpontus 

Thanks for making this pull request, and your contribution. Sorry about the delays in getting back.
If you are around, and interested can you please take a look at this https://github.com/freeCodeCamp/freeCodeCamp/issues/8096#issuecomment-350430279

Accordingly, you may want leave your thoughts on the action needed and update this PR.

**Comment by mpontus** [comment]
@raisedadead It's no problem. 

I've anticipated this discussion when I removed the checks. In fact I thought to suggest making it an explicit requirement to use prototypal inheritance in this exercise. I decided it would be easier to make a PR and then to move on from there.

I'm glad this discussion is taking place, however I won't be able to add much to it until I review the current program, which I have been delaying until the opening the signup.

I understand this PR will be closed after beta sees its release, and that's completely fine by me. I hope to be able to contribute more actively in the following year.

**Comment by raisedadead** [comment]
Thanks @mpontus closing! Happy contributing.

**Pull request closed without merging**
