### PR TITLE
fix(curriculum): Making post case insensitive

### LINKED ISSUE #52375: Registration Form Step 12 is not case insensitive
### Describe the Issue

The tests will not allow the value "POST" to pass. It will only pass if the value is "post".

### Affected Page

https://www.freecodecamp.org/learn/2022/responsive-web-design/learn-html-forms-by-building-a-registration-form/step-12

### Your code

This does not pass:

```
<form action='https://register-demo.freecodecamp.org' method="POST">
    </form>
```

### Expected behavior

The `method` attribute and its values are [case insensitive](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/form#method), so the tests should allow any form of capitalization (or lack thereof) to pass. I have tested and they do allow `METHOD` to pass, they just don't allow `POST` to pass.

### Screenshots

_No response_

### System

N/A

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by neuronCoder**
Checklist:

- [x] I have read and followed the [contribution guidelines](https://contribute.freecodecamp.org).
- [x] I have read and followed the [how to open a pull request guide](https://contribute.freecodecamp.org/#/how-to-open-a-pull-request).
- [x] My pull request targets the `main` branch of freeCodeCamp.
- [x] I have tested these changes either locally on my machine, or GitPod.

Closes #52375

### CODE REVIEW

**Comment by neuronCoder** [comment]
Since chai is already in npm list, first I tried to implement it using assert.match and the regex expression I used is **/post/i**. But while testing this in Gitpod, I found that this implementation has a vulnerability: it allows for values **1post** or **post1**. Then I implemented the assert statements(one for **post** and other for **POST**) in the try and catch blocks. Thus if the user enters anything other than **POST** or **post**, the test block fails. This has been tested on Gitpod. Thank you!!

**Comment by moT01** [comment]
Wouldn't something like this work @neuronCoder:

`assert.equal(document.querySelector('form')?.getAttribute('method').toLowerCase(), 'post');`

^ Added `.toLowerCase()`. Should work for `post`, `POST` and `PosT`, etc.

**Comment by neuronCoder** [comment]
Hi @moT01, thanks for taking the time to review and providing feedback. The approach you suggested works perfectly, but I was thinking along the lines of allowing only 'POST' or 'post'. Should we allow the user to enter values like pOsT or PoSt? If yes, I will change the code accordingly.
Also, thanks for mentioning the issue with raising PRs from main. Will keep this in mind from next time.

**Review by huyenltnguyen — COMMENTED** [review]
Hey @neuronCoder, thanks for the PR!

We have accepted #52418 and now need to close this one.

Just a quick note, this PR was created directly off of your `main` branch, which is not a strategy we recommend (changes should always be on feature branches) 🙂 

If you're interested in contributing to our codebase, please check out issues labeled with `first timers only` or `help-wanted`. We would welcome future pull requests from you.

Happy coding!

**Comment by moT01** [comment]
> Should we allow the user to enter values like pOsT or PoSt

Generally, we like to try and allow valid syntax to pass unless otherwise stated in the challenge. Any of those variants of `post` are valid as far as I know, so I think we should allow any case combination.

**Pull request closed without merging**
