### PR TITLE
fix(curriculum): copy edit for grammar

### PR DESCRIPTION
**Pull request by karenjoycelowe**
Checklist:

- [x] I have read [freeCodeCamp's contribution guidelines](https://contribute.freecodecamp.org).
- [x] My pull request has a descriptive title (not a vague title like `Update index.md`)
- [x] My pull request targets the `main` branch of freeCodeCamp.
- [x] I have tested these changes either locally on my machine, or GitPod.

I felt it was important to use proper grammar when exploring the strange coincidences surrounding Chuck Norris and Camper Cat.

### CODE REVIEW

**Review by naomi-lgbt — DISMISSED** [review]
Looks good to me. Nice catch!

**Review by gikf — DISMISSED** [review]
LGTM :+1:

**Review by gikf — CHANGES_REQUESTED** [review]
Could you change the text also in the solution section for each file?

**Comment by karenjoycelowe** [comment]
> 

Great idea @gikf! I fixed the remaining English instances.

**Review by gikf — APPROVED** [review]
Looks good! :+1:

**Review by Sembauke — APPROVED** [review]

**Pull request merged**
