### PR TITLE
feat(curriculum): refactor step 12 and check images using `.src`

### LINKED ISSUE #54767: Refactor step 12 of HTML cat photo app project
### Describe the Issue

We are still getting a ton of questions about how to do step 12 of the cat photo app project.
https://forum.freecodecamp.org/search?q=step%2012%20cat%20photo%20app%20%23html-css

So I am not entirely sure how to best update this.
Maybe there needs to be a different code example?
Maybe the hints need to be updated?

Maybe something else?

There are too many people lost on this step so I should be updated to make it clearer on what needs to be done.
So I am opening this up for discussion

### Affected Page

https://www.freecodecamp.org/learn/2022/responsive-web-design/learn-html-by-building-a-cat-photo-app/step-12

### Your code

see explanation above

### Expected behavior

see explanation above

### Screenshots

_No response_

### System

- Device: [e.g. iPhone 6, Laptop]
- OS: [e.g. iOS 14, Windows 10, Ubuntu 20.04]
- Browser: [e.g. Chrome, Safari]
- Version: [e.g. 22]

### Additional context

_No response_

### LINKED ISSUE #56255: Explicitly say extra spaces are present in Learn HTML by Building a Cat Photo App - Step 29
### Describe the Issue

Despite having typed out the `src` attribute link correctly, it is still possible to fail the challenges. If a camper adds an extra space before or after the link, the challenge won't pass and they'll be stuck trying to find a typo. Even more confusing to the potential campers is that the image does display in the browser. 

### Affected Page

https://www.freecodecamp.org/learn/2022/responsive-web-design/learn-html-by-building-a-cat-photo-app/step-29

### Your code

```HTML
<figure>
       <img src="https://cdn.freecodecamp.org/curriculum/cat-photo-app/cats.jpg "> 
</figure>
````

### Expected behavior

The camper should get explicitly told if the `src` attribute has extra spaces before or after the link. 

### Screenshots

_No response_

### System

- Device: Desktop
- OS: Windows 10
- Browser: Firefox
- Version: 130.0.1

### Additional context

This was the third image out of three. It's very possible the other lessons have that exact same issue.

### PR DESCRIPTION
**Pull request by majestic-owl448**
Checklist:

- [x] I have read and followed the [contribution guidelines](https://contribute.freecodecamp.org).
- [x] I have read and followed the [how to open a pull request guide](https://contribute.freecodecamp.org/how-to-open-a-pull-request/).
- [x] My pull request targets the `main` branch of freeCodeCamp.
- [x] I have tested these changes either locally on my machine, or GitPod.

Closes #56255
Closes #54767
Closes #56435
Closes #56347
Closes #55461

### CODE REVIEW

**Review by a2937 — CHANGES_REQUESTED** [review]
Step 17 isn't passing the "You are missing a closing `a` tag after the image." test. 

Additionally, if I recall correctly, the lower-jaw.spec.ts and progress-bar.spec.ts in the `e2e` folder need updating with the correct phrase. This seems like a solid attempt though.

**Comment by ilenia-magoni** [comment]
why, step 17 was passing fine locally...

**Comment by ilenia-magoni** [comment]
I guess this shows that having mock challenges that we can use for testing, instead of using the curriculum that is subjected to changes, would be better

**Review by a2937 — APPROVED** [review]
Okay so the curriculum tests are passing again. As are the end to end tests. In addition, at a quick glance everything seems acceptable. There might be like one or two asserts that could be full methods, but that is beyond the scope of this PR.

For these reasons, I am approving this PR.

**Review by Dario-DC — APPROVED** [review]

**Review by jdwilkin4 — APPROVED** [review]

**Comment by jeremylt** [comment]
You're my hero! Thanks for getting this in!!

**Pull request merged**
