### PR TITLE
Change "rest operator" to say "rest parameter" in challenges and guide

### LINKED ISSUE #34240: Referring to ... as an operator
so the rest or spread is referred to as an operator but I've been informed that it's not.
You can see it in the following places (both coding challenges and guides)
https://learn.freecodecamp.org/javascript-algorithms-and-data-structures/es6/use-the-rest-operator-with-function-parameters/
https://guide.freecodecamp.org/certifications/javascript-algorithms-and-data-structures/es6/use-the-rest-operator-with-function-parameters/
https://learn.freecodecamp.org/javascript-algorithms-and-data-structures/es6/use-the-spread-operator-to-evaluate-arrays-in-place/
https://learn.freecodecamp.org/javascript-algorithms-and-data-structures/basic-data-structures/combine-arrays-with-the-spread-operator/

There's probably some more, I stopped checking there.

### PR DESCRIPTION
**Pull request by dnntrn**
Hi! This pull request changes instances in the learning challenges and guides where the term "rest operator" is used. This term is changed to "rest parameter" to follow more closely with MDN ES6 language and for consistency reasons.

- [x] I have read [freeCodeCamp's contribution guidelines](https://github.com/freeCodeCamp/freeCodeCamp/blob/master/CONTRIBUTING.md).
- [x] My pull request has a descriptive title (not a vague title like `Update index.md`)
- [x] My pull request targets the `master` branch of freeCodeCamp.
- [x] None of my changes are plagiarized from another source without proper attribution.
- [x] All the files I changed are in the same world language (for example: only English changes, or only Chinese changes, etc.)
- [x] My changes do not use shortened URLs or affiliate links.

Refer to #34240

### CODE REVIEW

**Comment by RandellDawson** [comment]
@dnntrn See [comment](https://github.com/freeCodeCamp/freeCodeCamp/issues/34240#issuecomment-469019134) on the issue.

**Comment by dnntrn** [comment]
@RandellDawson I went through and changed the instances of "rest operator" to "rest parameter" in the english sections of guide and curriculum based on the link. The checklist says "All the files I changed are in the same world language (for example: only English changes, or only Chinese changes, etc.)", so I left those alone...unless you guys want me to change it?

**Comment by RandellDawson** [comment]
@dnntrn Valid point regarding the non-English languages.  However, since the other changes would only affect the `title` in the front matter block (you need to validate this) for the other languages, then I think it is fine to put all on the same PR.  You have our permission to do that.

**Comment by dnntrn** [comment]
@RandellDawson made the "rest parameter" changes in the English texts of the files for non-English languages. Someone definitely has to go through and make changes to the body though. I am vaguely familiar with Spanish and I recognized "rest operator" several times in the Spanish and Portuguese files. I think I can make those changes using MDN's languages functionality as a guide, but I'm not comfortable updating the script-based languages. Should I open issue reports for them? (separate ones for each language?)

**Comment by RandellDawson** [comment]
@dnntrn Where the instances in the non-English versions outside of the `testString`?

**Comment by dnntrn** [comment]
@RandellDawson yup! It appears they are in the non-English titles, descriptions, and instructions. Also, not sure if this is due to my unfamiliarity with the language, but there also appears to be multiple synonyms used to reference the "rest operator" in the Spanish and Portuguese files.


Some I noticed:
Portuguese: operador de descanso, operador rest
Spanish: operador de reposo, operador de descanso, operador de resto

Would be best checked with a native speaker tho; these could be fine.

Screenshot example:

screen shot 2019-03-03 at 4 26 16 pm

**Comment by RandellDawson** [comment]
Anything which needs to be reviewed by a translator reviewer should be taken off this PR.

**Comment by dnntrn** [comment]
@RandellDawson done. I didn't make any changes to non-English wording. I just changed "rest operator" to "rest parameter" if it appeared in English in the files.

**Comment by RandellDawson** [comment]
Since this PR is making changes to the word parameter vs operator, we do not want to lose track that the other parts of these non-English files will still need to be translated.

**On a separate note to mods:**  Make sure to use the Moderator Tools app's Filename search to validate that all 30 of the old filenames are not on any current open PR with the same files, or you will create merge conflicts on those open PRs.

**Comment by thecodingaviator** [comment]
To make sure that if this PR gets merged but the issue does not close without other languages being translated, I'm changing the Closes #XXXXX to Refer to #XXXXX

**Comment by RandellDawson** [comment]
@dnntrn I have been reviewing this PR for about 40 minutes.  If I just look at the renames, I see 23 instances where files were renamed.  The problem is, I expected to see a number evenly divisible by 6, because there are 6 languages.  See if you can figure out which extra one should be renamed.

**Comment by dnntrn** [comment]
@RandellDawson I'm taking another look now to be sure, but as I was changing rest operator to rest parameter, some of the files already had the changes or were written like that originally. Thus, the "for consistency reasons" part of my original pull request. That may explain why the number isn't divisible by 6. But I shall check again!

**Comment by dnntrn** [comment]
@RandellDawson I found 15 instances of "rest operator" in CHANGELOG.md and javascript files. I generally left these alone unless they were titles because I was afraid of somehow messing up the logic. Should I make the change? No .html or .md files except the CHANGELOG appear to have "rest operator"

image

**Comment by RandellDawson** [comment]
You should exclude anything in the node_modules folders.

**Comment by dnntrn** [comment]
@RandellDawson everything left is in node_modules, client/node_modules, or api-server/node_modules. No more "rest operators" remain besides these

**Comment by RandellDawson** [comment]
@dnntrn I figured out why you had 23 instead of the 24 renames I expected to see in this PR.

You missed renaming the file and changing the title for the following file:

`guide/chinese/certifications/javascript-algorithms-and-data-structures/es6/use-destructuring-assignment-with-the-rest-operator-to-reassign-array-elements/index.md`

**Comment by dnntrn** [comment]
@RandellDawson Did you make the change already? My file system shows it as "rest parameter" on the folder and in the index.md. Git status says "Your branch is up to date with 'origin/fix-rest-operator-to-rest-parameter'".

screen shot 2019-03-08 at 2 12 36 pm
screen shot 2019-03-08 at 2 11 38 pm

**Comment by RandellDawson** [comment]
@dnntrn OK, I agree with you now.  I had somehow missed the fact that one file had already been renamed.  

Now, we (the mods) just need to validate that each of the old filenames which are being renamed does not have any open PRs. Otherwise, those PRs will end up with merge conflicts.  This process could take a while and I will report back any PR which needs to be reviewed/closed/merged first before this PR can be merged.

**Comment by lynxlynxlynx** [comment]
First, the proposed changes include a bunch of noise in the form of whitespace only changes. Don't do that.

But more importantly, it still uses "rest parameter" everywhere, while a bunch of the uses are of the **spread** parameter, which just happens to have the same triple dot notation.

**Review by lynxlynxlynx — CHANGES_REQUESTED** [review]
First, the proposed changes include a bunch of noise in the form of whitespace only changes. Don't do that.

But more importantly, it still uses "rest parameter" everywhere, while a bunch of the uses are of the **spread** operator, which just happens to have the same triple dot notation.

**Comment by dnntrn** [comment]
@lynxlynxlynx I only changed rest operator to rest parameter. I understand that spread is different from rest, and I didn't search for spread at all. I will delete any extra spaces.

**Comment by lynxlynxlynx** [comment]
Sure, but you changed it also where it's actually the spread operator being used, while being called a "rest operator". So only reaffirming the bug there. 

If for some reason you don't want to fix that misuse, please exclude those files from this PR and we can open a separate bug for the needed changes of rest to spread.

**Comment by RandellDawson** [comment]
I am blocking this PR from getting merged until contributor has resolved the issues @lynxlynxlynx has found.  @dnntrn See the requested changes.

**Comment by dnntrn** [comment]
@lynxlynxlynx  @RandellDawson I fixed the whitespacing issue, but can you point to an example where rest parameter should be the spread operator? I might be misunderstanding, but I can't find it. Thanks!

**Comment by thecodingaviator** [comment]
@dnntrn go over this: https://scotch.io/bar-talk/javascripts-three-dots-spread-vs-rest-operators543

**Comment by dnntrn** [comment]
@thecodingaviator Thank you for the link, but I still can't find the problem. Sorry, but I don't see where rest parameter should be spread operator or vice versa.

Most of my changes were made in the "Use Destructuring Assignment with the Rest Parameter to Reassign Array Elements" and "Use the Rest Parameter with Function Parameters" files in various languages.

The second one is a classic use of rest. The first uses rest to gather an arbitrary number of values of an array into another array. Excerpt:
```
const [a, b, ...arr] = [1, 2, 3, 4, 5, 7];
console.log(a, b); // 1, 2
console.log(arr); // [3, 4, 5, 7]
```

This is also considered rest. It would be spread if the last console.log said console.log(...arr);, and thus, 3,4,5,7 would print as separate values, not in an array.

Please let me know if I'm confused or missing something! Thanks! @RandellDawson @lynxlynxlynx

**Comment by RandellDawson** [comment]
@dnntrn, @thecodingaviator I believe the confusion is in part because the title of one of the **Use Destructuring Assignment with the Rest Operator to Reassign Array Elements** challenge should really be **Use Destructuring Assignment with the Spread Operator to Reassign Array Elements** based on how it is used in that particular challenge.  Unless it is related to function parameters, it is the Spread Operator.  In that challenge file, all current references to "rest operator" should actually be "spread operator".  Also, the name of the file for that challenge (English version) should be changed from:
```
curriculum/challenges/english/02-javascript-algorithms-and-data-structures/es6/use-destructuring-assignment-with-the-rest-parameter-to-reassign-array-elements.english.md
```
to
```
curriculum/challenges/english/02-javascript-algorithms-and-data-structures/es6/use-destructuring-assignment-with-the-spread-operator-to-reassign-array-elements.english.md
```
These changes above would also apply to the non-English files for this challenge. 

Also, the guide articles would need similar verbiage changes and files renamed as well. 

Lastly, the `curriculum/challenges/_meta/es6/meta.json` file needs to make sure to change **"Use Destructuring Assignment with the Rest Parameter to Reassign Array Elements"** to **"Use Destructuring Assignment with the Spread Operator to Reassign Array Elements"**

**Comment by dnntrn** [comment]
@RandellDawson I don't think **Use Destructuring Assignment with the Rest Operator to Reassign Array Elements** should be **Use Destructuring Assignment with the Spread Operator to Reassign Array Elements**. 

The MDN docs specifically uses the following language:

> "When destructuring an array, you can unpack and assign the remaining part of it to a variable using the rest pattern"

 and 

> "The Rest/Spread Properties for ECMAScript proposal (stage 3) adds the rest syntax to destructuring. Rest properties collect the remaining own enumerable property keys that are not already picked off by the destructuring pattern."

Other online resources also refer to destructuring as using rest, and the examples provided do not use it as a function parameter. I can make the change if you want me to, but I don't think it would be correct and will probably need to be changed again later.

Let me know how to proceed for these files. I will remove my changes to the non-English files.

Resources:

MDN: [https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Operators/Destructuring_assignment](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Operators/Destructuring_assignment)

image

image

Other resource: [https://dmitripavlutin.com/how-three-dots-changed-javascript/](https://dmitripavlutin.com/how-three-dots-changed-javascript/)
image

**Comment by RandellDawson** [comment]
@dnntrn I am quite familiar with MDN.  Technically, `...` is the rest syntax, but its use with the array is as the spread operator.  Are purpose here is to use "spread operator" where applicable and "rest parameter".  As I said before, the only place "rest parameter" should be used is a function's parameters (hence the name rest parameter).  If we use what you have said, then we would never use "spread operator" as it really is "rest syntax".  We decided in the issue (#34240) to use both "spread operator" and "rest parameter" where applicable.  In this case "rest parameter" is not applicable, because the `...` is not used in a function's parameter section.  Hopefully this makes sense.

**Comment by RandellDawson** [comment]
@dnntrn It is almost as if we should really refer to it as Rest syntax and Spread syntax instead of Rest Parameter and Spread Operator.  MDN seems to use the terms interchangeably.

**Comment by RandellDawson** [comment]
@dnntrn After discussing with another mod (@ojeytonwilliams), I am in agreement with your conclusion that I should not have asked you to change **Use Destructuring Assignment with the Rest Operator to Reassign Array Elements** to **Use Destructuring Assignment with the Spread Operator to Reassign Array Elements**.  We will just go with **Use Destructuring Assignment with the Rest Parameter to Reassign Array Elements** for that challenge.  My other comments still stand though, unless I have made a mistake on those.

**Comment by RandellDawson** [comment]
@dnntrn Due to a recent change, we are not going to have the curriculum challenges be translated to the other languages, so you can revert all the changes to the non-English files and then this PR will only deal with the English files.  Let us know if you have any further questions.

**Comment by RandellDawson** [comment]
@dnntrn Due to a recent change, we are not going to have the curriculum challenges be translated to the other languages, so I have reverted the changes to those files on your behalf and pushed those changes.

@lynxlynxlynx and @thecodingaviator, @ojeytonwilliams I believe after removing the non-English files from this PR on behalf of the OP, I think everything is as it should be now regarding the correct terms.  Can you all take a look the current changes and comment on anything that still needs to be changed?

Thank you.

**Review by ojeytonwilliams — APPROVED** [review]
LGTM :+1:

**Review by Manish-Giri — APPROVED** [review]
LGTM.

**Review by lynxlynxlynx — APPROVED** [review]

**Comment by lynxlynxlynx** [comment]
Thanks and congratulations on surviving review. :)

**Review by thecodingaviator — COMMENTED** [review]
Nice work

**Comment by dnntrn** [comment]
@RandellDawson Sorry, I got busy in my personal life and have been MIA. Thank you for taking care of this for me!

**Pull request merged**
