### PR TITLE
fix(seed): Remove typo from chai-http-IV challenge title

### PR DESCRIPTION
**Pull request by Wojonatior**
#### Pre-Submission Checklist
- [x] Your pull request targets the `staging` branch of freeCodeCamp.
- [x] Branch starts with either `fix/`, `feature/`, or `translate/` (e.g. `fix/signin-issue`)
- [x] You have only one commit (if not, [squash](http://forum.freecodecamp.org/t/how-to-squash-multiple-commits-into-one-with-git/13231) them into one commit).
- [x] All new and existing tests pass the command `npm test`. Use `git commit --amend` to amend any fixes.

#### Type of Change
- [x] Small bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds new functionality)
- [ ] Breaking change (fix or feature that would change existing functionality)
- [ ] Add new translation (feature adding new translations)

#### Checklist:

- [x] Tested changes locally.
- [x] Addressed currently open issue (replace XXXXX with an issue no in next line)

Closes #17148

#### Description
Removed the typo in the challenge name that was present [here](https://beta.freecodecamp.org/en/challenges/quality-assurance-and-testing-with-chai/run-functional-tests-on-an-api-response-using-chaihttp-iv--put-method-redux)

### CODE REVIEW

**Comment by Wojonatior** [comment]
Travis looks like it's currently having some build issues. Let me know if there's something else I need to be doing to prepare my branch for a PR.

**Comment by raisedadead** [comment]
Hi @ojongerius I went though the issue thread once again, and the challenge series themselves. There is very little meaning that the word 'redux' adds here other than confusing non-native speakers. I think removing it keeps the challenge same while avoiding the confusion?

I open to thoughts though.

**Comment by Bouncey** [comment]
## LGTM :+1:

**Review by mstellaluna — APPROVED** [review]
LGTM

**Comment by mstellaluna** [comment]
@Wojonatior Hello, I will be approving this PR. Thank you for your contribution. Happy Coding !

**Pull request merged**
