### PR TITLE
fix(i18n): annotate code with notranslate

### LINKED ISSUE #40534: Need to add the <notranslate> annotation to single back tick code blocks for Crowdin integration
The `tools/formatter/translation-annotation/annotate.js` script used to annotate the files before uploading to Crowdin, needs to add the <notranslate> around the single back tick code blocks in the description, instructions, and test text.

For example, a test text in the English file may look like:

````
Add a media query, so that the `p` tag has a `font-size` of `10px` when the device's height is less than or equal to `800px`.
````
Currently, the script just surrounds the entire test text like:
````
<notranslate>
Add a media query, so that the `p` tag has a `font-size` of `10px` when the device's height is less than or equal to `800px`.
</notranslate>
````
In order for translators to not accidentally translate the code blocks, it should look like:
````
Add a media query, so that the <notranslate>`p`</notranslate> tag has a <notranslate>`font-size`</notranslate> of <notranslate>`10px`</notranslate> when the device's height is less than or equal to <notranslate>`800px`</notranslate>.
````

### PR DESCRIPTION
**Pull request by ojeytonwilliams**
@RandellDawson I was not sure exactly what needed tags. If it's not quite what you need, let me know.  It's easy to modify.

Closes https://github.com/freeCodeCamp/freeCodeCamp/issues/40534

### CODE REVIEW

**Comment by RandellDawson** [comment]
@ojeytonwilliams I pull this PR down and cherry-picked [the commit](https://github.com/freeCodeCamp/freeCodeCamp/pull/40602/commits/09072f65a729226db3cebffa41159ae1a1f08a38) from my PR #40602 and ran `tools/crowdin/actions/annotate-curriculum-files/index.js` locally and get the following errors:
```
Error transforming
/home/rdawson/Coding/fcc/curriculum/challenges/english/10-coding-interview-prep/rosetta-code/24-game.md
Error: Cannot handle unknown node `table`
    at Object.unknown (/home/rdawson/Coding/fcc/tools/formatter/node_modules/mdast-util-to-markdown/lib/index.js:65:9)
    at Object.one [as handle] (/home/rdawson/Coding/fcc/tools/formatter/node_modules/zwitch/index.js:20:25)
    at flow (/home/rdawson/Coding/fcc/tools/formatter/node_modules/mdast-util-to-markdown/lib/util/container-flow.js:15:15)
    at Object.root (/home/rdawson/Coding/fcc/tools/formatter/node_modules/mdast-util-to-markdown/lib/handle/root.js:6:10)
    at Object.one [as handle] (/home/rdawson/Coding/fcc/tools/formatter/node_modules/zwitch/index.js:20:25)
    at toMarkdown (/home/rdawson/Coding/fcc/tools/formatter/node_modules/mdast-util-to-markdown/lib/index.js:38:20)
    at compile (/home/rdawson/Coding/fcc/tools/formatter/node_modules/remark-stringify/index.js:13:12)
    at Function.stringify (/home/rdawson/Coding/fcc/tools/formatter/node_modules/unified/index.js:354:12)
    at stringifyMd (/home/rdawson/Coding/fcc/tools/formatter/translation-annotation/utils/index.js:27:6)
    at transformer (/home/rdawson/Coding/fcc/tools/formatter/translation-annotation/plugins/text-to-data.js:13:30)
Error transforming
/home/rdawson/Coding/fcc/curriculum/challenges/english/10-coding-interview-prep/rosetta-code/balanced-brackets.md
Error: Cannot handle unknown node `table`
    at Object.unknown (/home/rdawson/Coding/fcc/tools/formatter/node_modules/mdast-util-to-markdown/lib/index.js:65:9)
    at Object.one [as handle] (/home/rdawson/Coding/fcc/tools/formatter/node_modules/zwitch/index.js:20:25)
    at flow (/home/rdawson/Coding/fcc/tools/formatter/node_modules/mdast-util-to-markdown/lib/util/container-flow.js:15:15)
    at Object.root (/home/rdawson/Coding/fcc/tools/formatter/node_modules/mdast-util-to-markdown/lib/handle/root.js:6:10)
    at Object.one [as handle] (/home/rdawson/Coding/fcc/tools/formatter/node_modules/zwitch/index.js:20:25)
    at toMarkdown (/home/rdawson/Coding/fcc/tools/formatter/node_modules/mdast-util-to-markdown/lib/index.js:38:20)
    at compile (/home/rdawson/Coding/fcc/tools/formatter/node_modules/remark-stringify/index.js:13:12)
    at Function.stringify (/home/rdawson/Coding/fcc/tools/formatter/node_modules/unified/index.js:354:12)
    at stringifyMd (/home/rdawson/Coding/fcc/tools/formatter/translation-annotation/utils/index.js:27:6)
    at transformer (/home/rdawson/Coding/fcc/tools/formatter/translation-annotation/plugins/text-to-data.js:12:29)
Error transforming
/home/rdawson/Coding/fcc/curriculum/challenges/english/10-coding-interview-prep/rosetta-code/convert-seconds-to-compound-duration.md
Error: Cannot handle unknown node `table`
    at Object.unknown (/home/rdawson/Coding/fcc/tools/formatter/node_modules/mdast-util-to-markdown/lib/index.js:65:9)
    at Object.one [as handle] (/home/rdawson/Coding/fcc/tools/formatter/node_modules/zwitch/index.js:20:25)
    at flow (/home/rdawson/Coding/fcc/tools/formatter/node_modules/mdast-util-to-markdown/lib/util/container-flow.js:15:15)
    at Object.root (/home/rdawson/Coding/fcc/tools/formatter/node_modules/mdast-util-to-markdown/lib/handle/root.js:6:10)
    at Object.one [as handle] (/home/rdawson/Coding/fcc/tools/formatter/node_modules/zwitch/index.js:20:25)
    at toMarkdown (/home/rdawson/Coding/fcc/tools/formatter/node_modules/mdast-util-to-markdown/lib/index.js:38:20)
    at compile (/home/rdawson/Coding/fcc/tools/formatter/node_modules/remark-stringify/index.js:13:12)
    at Function.stringify (/home/rdawson/Coding/fcc/tools/formatter/node_modules/unified/index.js:354:12)
    at stringifyMd (/home/rdawson/Coding/fcc/tools/formatter/translation-annotation/utils/index.js:27:6)
    at transformer (/home/rdawson/Coding/fcc/tools/formatter/translation-annotation/plugins/text-to-data.js:12:29)
Error transforming
/home/rdawson/Coding/fcc/curriculum/challenges/english/10-coding-interview-prep/rosetta-code/execute-brain.md
Error: Cannot handle unknown node `table`
    at Object.unknown (/home/rdawson/Coding/fcc/tools/formatter/node_modules/mdast-util-to-markdown/lib/index.js:65:9)
    at Object.one [as handle] (/home/rdawson/Coding/fcc/tools/formatter/node_modules/zwitch/index.js:20:25)
    at flow (/home/rdawson/Coding/fcc/tools/formatter/node_modules/mdast-util-to-markdown/lib/util/container-flow.js:15:15)
    at Object.root (/home/rdawson/Coding/fcc/tools/formatter/node_modules/mdast-util-to-markdown/lib/handle/root.js:6:10)
    at Object.one [as handle] (/home/rdawson/Coding/fcc/tools/formatter/node_modules/zwitch/index.js:20:25)
    at toMarkdown (/home/rdawson/Coding/fcc/tools/formatter/node_modules/mdast-util-to-markdown/lib/index.js:38:20)
    at compile (/home/rdawson/Coding/fcc/tools/formatter/node_modules/remark-stringify/index.js:13:12)
    at Function.stringify (/home/rdawson/Coding/fcc/tools/formatter/node_modules/unified/index.js:354:12)
    at stringifyMd (/home/rdawson/Coding/fcc/tools/formatter/translation-annotation/utils/index.js:27:6)
    at transformer (/home/rdawson/Coding/fcc/tools/formatter/translation-annotation/plugins/text-to-data.js:12:29)
Error transforming
/home/rdawson/Coding/fcc/curriculum/challenges/english/10-coding-interview-prep/rosetta-code/fibonacci-n-step-number-sequences.md
Error: Cannot handle unknown node `table`
    at Object.unknown (/home/rdawson/Coding/fcc/tools/formatter/node_modules/mdast-util-to-markdown/lib/index.js:65:9)
    at Object.one [as handle] (/home/rdawson/Coding/fcc/tools/formatter/node_modules/zwitch/index.js:20:25)
    at flow (/home/rdawson/Coding/fcc/tools/formatter/node_modules/mdast-util-to-markdown/lib/util/container-flow.js:15:15)
    at Object.root (/home/rdawson/Coding/fcc/tools/formatter/node_modules/mdast-util-to-markdown/lib/handle/root.js:6:10)
    at Object.one [as handle] (/home/rdawson/Coding/fcc/tools/formatter/node_modules/zwitch/index.js:20:25)
    at toMarkdown (/home/rdawson/Coding/fcc/tools/formatter/node_modules/mdast-util-to-markdown/lib/index.js:38:20)
    at compile (/home/rdawson/Coding/fcc/tools/formatter/node_modules/remark-stringify/index.js:13:12)
    at Function.stringify (/home/rdawson/Coding/fcc/tools/formatter/node_modules/unified/index.js:354:12)
    at stringifyMd (/home/rdawson/Coding/fcc/tools/formatter/translation-annotation/utils/index.js:27:6)
    at transformer (/home/rdawson/Coding/fcc/tools/formatter/translation-annotation/plugins/text-to-data.js:12:29)
Error transforming
/home/rdawson/Coding/fcc/curriculum/challenges/english/10-coding-interview-prep/rosetta-code/hash-join.md
Error: Cannot handle unknown node `table`
    at Object.unknown (/home/rdawson/Coding/fcc/tools/formatter/node_modules/mdast-util-to-markdown/lib/index.js:65:9)
    at Object.one [as handle] (/home/rdawson/Coding/fcc/tools/formatter/node_modules/zwitch/index.js:20:25)
    at flow (/home/rdawson/Coding/fcc/tools/formatter/node_modules/mdast-util-to-markdown/lib/util/container-flow.js:15:15)
    at Object.root (/home/rdawson/Coding/fcc/tools/formatter/node_modules/mdast-util-to-markdown/lib/handle/root.js:6:10)
    at Object.one [as handle] (/home/rdawson/Coding/fcc/tools/formatter/node_modules/zwitch/index.js:20:25)
    at toMarkdown (/home/rdawson/Coding/fcc/tools/formatter/node_modules/mdast-util-to-markdown/lib/index.js:38:20)
    at compile (/home/rdawson/Coding/fcc/tools/formatter/node_modules/remark-stringify/index.js:13:12)
    at Function.stringify (/home/rdawson/Coding/fcc/tools/formatter/node_modules/unified/index.js:354:12)
    at stringifyMd (/home/rdawson/Coding/fcc/tools/formatter/translation-annotation/utils/index.js:27:6)
    at transformer (/home/rdawson/Coding/fcc/tools/formatter/translation-annotation/plugins/text-to-data.js:13:30)
Error transforming
/home/rdawson/Coding/fcc/curriculum/challenges/english/10-coding-interview-prep/project-euler/problem-54-poker-hands.md
Error: Cannot handle unknown node `table`
    at Object.unknown (/home/rdawson/Coding/fcc/tools/formatter/node_modules/mdast-util-to-markdown/lib/index.js:65:9)
    at Object.one [as handle] (/home/rdawson/Coding/fcc/tools/formatter/node_modules/zwitch/index.js:20:25)
    at flow (/home/rdawson/Coding/fcc/tools/formatter/node_modules/mdast-util-to-markdown/lib/util/container-flow.js:15:15)
    at Object.root (/home/rdawson/Coding/fcc/tools/formatter/node_modules/mdast-util-to-markdown/lib/handle/root.js:6:10)
    at Object.one [as handle] (/home/rdawson/Coding/fcc/tools/formatter/node_modules/zwitch/index.js:20:25)
    at toMarkdown (/home/rdawson/Coding/fcc/tools/formatter/node_modules/mdast-util-to-markdown/lib/index.js:38:20)
    at compile (/home/rdawson/Coding/fcc/tools/formatter/node_modules/remark-stringify/index.js:13:12)
    at Function.stringify (/home/rdawson/Coding/fcc/tools/formatter/node_modules/unified/index.js:354:12)
    at stringifyMd (/home/rdawson/Coding/fcc/tools/formatter/translation-annotation/utils/index.js:27:6)
    at transformer (/home/rdawson/Coding/fcc/tools/formatter/translation-annotation/plugins/text-to-data.js:12:29)
Error transforming
/home/rdawson/Coding/fcc/curriculum/challenges/english/10-coding-interview-prep/project-euler/problem-61-cyclical-figurate-numbers.md
Error: Cannot handle unknown node `table`
    at Object.unknown (/home/rdawson/Coding/fcc/tools/formatter/node_modules/mdast-util-to-markdown/lib/index.js:65:9)
    at Object.one [as handle] (/home/rdawson/Coding/fcc/tools/formatter/node_modules/zwitch/index.js:20:25)
    at flow (/home/rdawson/Coding/fcc/tools/formatter/node_modules/mdast-util-to-markdown/lib/util/container-flow.js:15:15)
    at Object.root (/home/rdawson/Coding/fcc/tools/formatter/node_modules/mdast-util-to-markdown/lib/handle/root.js:6:10)
    at Object.one [as handle] (/home/rdawson/Coding/fcc/tools/formatter/node_modules/zwitch/index.js:20:25)
    at toMarkdown (/home/rdawson/Coding/fcc/tools/formatter/node_modules/mdast-util-to-markdown/lib/index.js:38:20)
    at compile (/home/rdawson/Coding/fcc/tools/formatter/node_modules/remark-stringify/index.js:13:12)
    at Function.stringify (/home/rdawson/Coding/fcc/tools/formatter/node_modules/unified/index.js:354:12)
    at stringifyMd (/home/rdawson/Coding/fcc/tools/formatter/translation-annotation/utils/index.js:27:6)
    at transformer (/home/rdawson/Coding/fcc/tools/formatter/translation-annotation/plugins/text-to-data.js:12:29)
Error transforming
/home/rdawson/Coding/fcc/curriculum/challenges/english/10-coding-interview-prep/project-euler/problem-68-magic-5-gon-ring.md
Error: Cannot handle unknown node `table`
    at Object.unknown (/home/rdawson/Coding/fcc/tools/formatter/node_modules/mdast-util-to-markdown/lib/index.js:65:9)
    at Object.one [as handle] (/home/rdawson/Coding/fcc/tools/formatter/node_modules/zwitch/index.js:20:25)
    at flow (/home/rdawson/Coding/fcc/tools/formatter/node_modules/mdast-util-to-markdown/lib/util/container-flow.js:15:15)
    at Object.root (/home/rdawson/Coding/fcc/tools/formatter/node_modules/mdast-util-to-markdown/lib/handle/root.js:6:10)
    at Object.one [as handle] (/home/rdawson/Coding/fcc/tools/formatter/node_modules/zwitch/index.js:20:25)
    at toMarkdown (/home/rdawson/Coding/fcc/tools/formatter/node_modules/mdast-util-to-markdown/lib/index.js:38:20)
    at compile (/home/rdawson/Coding/fcc/tools/formatter/node_modules/remark-stringify/index.js:13:12)
    at Function.stringify (/home/rdawson/Coding/fcc/tools/formatter/node_modules/unified/index.js:354:12)
    at stringifyMd (/home/rdawson/Coding/fcc/tools/formatter/translation-annotation/utils/index.js:27:6)
    at transformer (/home/rdawson/Coding/fcc/tools/formatter/translation-annotation/plugins/text-to-data.js:12:29)
Error transforming
/home/rdawson/Coding/fcc/curriculum/challenges/english/10-coding-interview-prep/project-euler/problem-69-totient-maximum.md
Error: Cannot handle unknown node `table`
    at Object.unknown (/home/rdawson/Coding/fcc/tools/formatter/node_modules/mdast-util-to-markdown/lib/index.js:65:9)
    at Object.one [as handle] (/home/rdawson/Coding/fcc/tools/formatter/node_modules/zwitch/index.js:20:25)
    at flow (/home/rdawson/Coding/fcc/tools/formatter/node_modules/mdast-util-to-markdown/lib/util/container-flow.js:15:15)
    at Object.root (/home/rdawson/Coding/fcc/tools/formatter/node_modules/mdast-util-to-markdown/lib/handle/root.js:6:10)
    at Object.one [as handle] (/home/rdawson/Coding/fcc/tools/formatter/node_modules/zwitch/index.js:20:25)
    at toMarkdown (/home/rdawson/Coding/fcc/tools/formatter/node_modules/mdast-util-to-markdown/lib/index.js:38:20)
    at compile (/home/rdawson/Coding/fcc/tools/formatter/node_modules/remark-stringify/index.js:13:12)
    at Function.stringify (/home/rdawson/Coding/fcc/tools/formatter/node_modules/unified/index.js:354:12)
    at stringifyMd (/home/rdawson/Coding/fcc/tools/formatter/translation-annotation/utils/index.js:27:6)
    at transformer (/home/rdawson/Coding/fcc/tools/formatter/translation-annotation/plugins/text-to-data.js:12:29)
Error transforming
/home/rdawson/Coding/fcc/curriculum/challenges/english/10-coding-interview-prep/project-euler/problem-78-coin-partitions.md
Error: Cannot handle unknown node `table`
    at Object.unknown (/home/rdawson/Coding/fcc/tools/formatter/node_modules/mdast-util-to-markdown/lib/index.js:65:9)
    at Object.one [as handle] (/home/rdawson/Coding/fcc/tools/formatter/node_modules/zwitch/index.js:20:25)
    at flow (/home/rdawson/Coding/fcc/tools/formatter/node_modules/mdast-util-to-markdown/lib/util/container-flow.js:15:15)
    at Object.root (/home/rdawson/Coding/fcc/tools/formatter/node_modules/mdast-util-to-markdown/lib/handle/root.js:6:10)
    at Object.one [as handle] (/home/rdawson/Coding/fcc/tools/formatter/node_modules/zwitch/index.js:20:25)
    at toMarkdown (/home/rdawson/Coding/fcc/tools/formatter/node_modules/mdast-util-to-markdown/lib/index.js:38:20)
    at compile (/home/rdawson/Coding/fcc/tools/formatter/node_modules/remark-stringify/index.js:13:12)
    at Function.stringify (/home/rdawson/Coding/fcc/tools/formatter/node_modules/unified/index.js:354:12)
    at stringifyMd (/home/rdawson/Coding/fcc/tools/formatter/translation-annotation/utils/index.js:27:6)
    at transformer (/home/rdawson/Coding/fcc/tools/formatter/translation-annotation/plugins/text-to-data.js:12:29)
Error transforming
/home/rdawson/Coding/fcc/curriculum/challenges/english/10-coding-interview-prep/algorithms/pairwise.md
Error: Cannot handle unknown node `table`
    at Object.unknown (/home/rdawson/Coding/fcc/tools/formatter/node_modules/mdast-util-to-markdown/lib/index.js:65:9)
    at Object.one [as handle] (/home/rdawson/Coding/fcc/tools/formatter/node_modules/zwitch/index.js:20:25)
    at flow (/home/rdawson/Coding/fcc/tools/formatter/node_modules/mdast-util-to-markdown/lib/util/container-flow.js:15:15)
    at Object.root (/home/rdawson/Coding/fcc/tools/formatter/node_modules/mdast-util-to-markdown/lib/handle/root.js:6:10)
    at Object.one [as handle] (/home/rdawson/Coding/fcc/tools/formatter/node_modules/zwitch/index.js:20:25)
    at toMarkdown (/home/rdawson/Coding/fcc/tools/formatter/node_modules/mdast-util-to-markdown/lib/index.js:38:20)
    at compile (/home/rdawson/Coding/fcc/tools/formatter/node_modules/remark-stringify/index.js:13:12)
    at Function.stringify (/home/rdawson/Coding/fcc/tools/formatter/node_modules/unified/index.js:354:12)
    at stringifyMd (/home/rdawson/Coding/fcc/tools/formatter/translation-annotation/utils/index.js:27:6)
    at transformer (/home/rdawson/Coding/fcc/tools/formatter/translation-annotation/plugins/text-to-data.js:12:29)
```

**Comment by RandellDawson** [comment]
Another strange thing I notice is for the challenge , it changes:
```markdown
**Note about `section` and `div`**  
```
into:
```markdown
**Note about <notranslate>`section`</notranslate> and <notranslate>`div`</notranslate>**\\
```
Not sure why it added the two `\\` at the end of this line.

**Comment by ojeytonwilliams** [comment]
Hey @RandellDawson, the `table` issue should be resolved now.  

As for the `\`, a single slash is used to create a `<br>`, which is what I'm seeing here.  The original file used two spaces at the end of the line to create it.  I'm not 100% sure why it's started stringifying that to `\`, but I suspect that a default option changed at some point.  Either way, it means the same thing and is a little easier to read, so I think it's okay.

I'm guessing the double slash is just a rendering thing and it's really just one.

**Comment by RandellDawson** [comment]
@ojeytonwilliams I think we can safely close this PR now.

**Pull request closed without merging**
