### PR TITLE
fix(challenges): Hide second scrollbar in challenge preview pane

### LINKED ISSUE #16695: [Beta] There are two scrollbars in the Preview Panel
### Issue Description
In many challenges eg. [Use a CSS Class to style an element](https://beta.freecodecamp.org/en/challenges/basic-css/use-a-css-class-to-style-an-element) or [Create a block element bootstrap button](https://beta.freecodecamp.org/en/challenges/bootstrap/create-a-block-element-bootstrap-button), there are two scrollbars in the preview panel. There should be a single scrollbar like we have in all of our challenges.  

issue

### Browser Information
* Browser Name, Version: Chrome and Firefox (latest).
* Operating System: Windows 10 Pro 32 Bit.
* Mobile, Desktop, or Tablet: Desktop.

### PR DESCRIPTION
**Pull request by pitts114**
#### Pre-Submission Checklist

- [x] Your pull request targets the `staging` branch of freeCodeCamp.
- [x] Branch starts with either `fix/`, `feature/`, or `translate/` (e.g. `fix/signin-issue`)
- [x] You have only one commit (if not, [squash](http://forum.freecodecamp.org/t/how-to-squash-multiple-commits-into-one-with-git/13231) them into one commit).
- [x] All new and existing tests pass the command `npm test`. Use `git commit --amend` to amend any fixes.

#### Type of Change

- [x] Small bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds new functionality)
- [ ] Breaking change (fix or feature that would change existing functionality)
- [ ] Add new translation (feature adding new translations)

#### Checklist:

- [x] Tested changes locally.
- [x] Addressed currently open issue (replace XXXXX with an issue no in next line)

Closes #16695

#### Description

In order to fix a small bug with two scrollbars appearing in a challenge preview pane, I've hidden the scrollbar in the div surrounding the challenge preview iframe. 

sorta-fixed

However, there is still some whitespace surrounding the preview pane due to the styling of the parent Pane component. To remove the odd whitespace, I removed the padding from the left and right sides.
 
fixed

### CODE REVIEW

**Comment by vkWeb** [comment]
@pullman14 Next time before opening a PR against an issue please comment on the issue thread that you're on it. 
@raisedadead Please review this :).

**Comment by raisedadead** [comment]
@vkWeb 

> Next time before opening a PR against an issue please comment on the issue thread that you're on it.

That's not at all mandatory, although its ideal.

@pullman14 thanks a lot for taking the time to prepare this.

**Comment by vkWeb** [comment]
@raisedadead Then how will others know that someone is working on it? At least they should comment so that others don't waste their time on it.

**Comment by raisedadead** [comment]
> Then how will others know that someone is working on it? At least they should comment so that others don't waste their time on it.

An open PR linked to issue should be enough?

**Review by raisedadead — APPROVED** [review]

**Comment by vkWeb** [comment]
> An open PR linked to issue should be enough?


@quimbyosis was already working on this issue so, @pullman14 should have first confirmed whether he can tackle the issue or not. Please have a look at [this discussion](https://github.com/freeCodeCamp/freeCodeCamp/issues/16695#issuecomment-365001495).
@Bouncey Shouldn't we comment first on the issue thread and then start working on it?

**Comment by pullman14** [comment]
I understand that commenting in threads before working on an issue would result in less wasted time for everyone, but considering that this beginner issue is about a week old with no commits or discussion addressing it, I decided that a solution to this particular problem would be found more quickly if I did not wait for a response to see if others were still working on it. For more complex issues I can certainly comment in threads before committing time to them.

**Comment by Bouncey** [comment]
@pullman14 the code looks good, I want to check that stripping the padding away doesn't effect the other panes negatively. 

@vkWeb I agree with @raisedadead's comments on this not being mandatory, but an ideal. There is an ongoing discussion about improving this workflow [here](https://github.com/freeCodeCamp/freeCodeCamp/issues/16350#issuecomment-354604185).

**Comment by raisedadead** [comment]
@pullman14 yes you are absolutely right. 

The reason we can't guarantee that someone commenting a on an issue will open a PR is because more often than not, many contributors do not end up opening a pull request after showing their interest.

Traditionally we have always accepted the first open and suitable pull request for any open issue.

Thanks for preparing this pull request, and we welcome you to contribute more in future.

Happy contributing!

**Comment by vkWeb** [comment]
@raisedadead, @Bouncey Okay. :)

**Comment by amramadan** [comment]
the open issue was not closed

**Comment by Bouncey** [comment]
Thanks for the changes @pullman14 :+1:

**Pull request merged**
