### PR TITLE
Feature/Loading Spinner

### LINKED ISSUE #9735: Progress Visualization for clean UX experience
For a user, who visits the website (initial loads on a fresh device), certain UI elements take a while to populate.

Example:
1. Login, the profile image takes a couple of seconds to appear on the navbar
2. The map aside takes a couple of seconds to populate and displays "No Superblocks" 
3. Challenges views at times take a second to render.

Although these happen seamlessly from the next interaction with the elements. Hence we might as well think of having some form of progress to present the blocking nature of the UI.

### PR DESCRIPTION
**Pull request by Bouncey**
#### Pre-Submission Checklist

- [x] Your pull request targets the `staging` branch of FreeCodeCamp.
- [x] Branch starts with either `fix/`, `feature/`, or `translate/` (e.g. `fix/signin-issue`)
- [x] You have only one commit (if not, [squash](http://forum.freecodecamp.com/t/how-to-squash-multiple-commits-into-one-with-git/13231) them into one commit).
- [x] All new and existing tests pass the command `npm test`. Use `git commit --amend` to amend any fixes.
#### Type of Change

- [ ] Small bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds new functionality)
- [ ] Breaking change (fix or feature that would change existing functionality)
- [ ] Add new translation (feature adding new translations)
#### Checklist:

- [x] Tested changes locally.
- [x] Closes currently open issue (replace XXXX with an issue no): Closes #9735 
#### Description

Uses new FontAwesome Icon as a loading spinner.

Visible whilst react app hasn't resolved fully (entities). Disappears when challenge/map is ready, this is also the same time that the user appears in the navbar :+1: 

FontAwesome lib not required in `client/less/lib` it is introduced through `public/bower_components`

Will require a `bower install` to QA

### CODE REVIEW

**Comment by raisedadead** [comment]
> Will require a bower install to QA

Might I suggest using a CDN, when they have one? IMHO, we should have just one set of dependency management.

**Comment by Bouncey** [comment]
@raisedadead I agree we should CDN all the things, but that is not the purpose of this PR. I will raise an issue for this

I haven't added fontawesome to bower, I have just updated the version so we can access the new fcc icon.

**Comment by BerkeleyTrue** [comment]
Please separate the removal of font awesome and the addition of the spinner into separate PR's

**Comment by Bouncey** [comment]
:+1: will do

**Comment by BerkeleyTrue** [comment]
@Bouncey Thanks for putting the time into this PR.

We don't want to associate the logo with waiting. We should be using a conventional spinner for this.

Happy Coding

**Pull request closed without merging**
