### PR TITLE
fix(server): error on claim certification

### PR DESCRIPTION
**Pull request by ValeraS**
- [x] I have read [freeCodeCamp's contribution guidelines](https://github.com/freeCodeCamp/freeCodeCamp/blob/master/CONTRIBUTING.md).
- [x] My pull request has a descriptive title (not a vague title like `Update index.md`)
- [x] My pull request targets the `master` branch of freeCodeCamp.
- [x] None of my changes are plagiarized from another source without proper attribution.

### CODE REVIEW

**Comment by raisedadead** [comment]
Can you point me to how to reproduce the issue?

**Comment by ValeraS** [comment]
If set a name, accept Academic Honesty Policy, finish all project in a section and press a `Claim Certification` button, you'll get an error:
<details>
  <summary>error log</summary>
  
  ```
  fcc:certification responsive-web-design +10s
  fcc:certification isRespWebDesignCert +1ms

Time: 2019-02-18T08:29:20.974Z
Error: Cannot destructure property `count` of 'undefined' or 'null'.
Is authenticated user: true
Route: {
  "path": "/certificate/verify",
  "stack": [
    {
      "name": "ifNoUser401",
      "keys": [],
      "regexp": {
        "fast_star": false,
        "fast_slash": false
      },
      "method": "put"
    },
    {
      "name": "ifNoSuperBlock404",
      "keys": [],
      "regexp": {
        "fast_star": false,
        "fast_slash": false
      },
      "method": "put"
    },
    {
      "name": "verifyCert",
      "keys": [],
      "regexp": {
        "fast_star": false,
        "fast_slash": false
      },
      "method": "put"
    }
  ],
  "methods": {
    "put": true
  }
}
Stack: TypeError: Cannot destructure property `count` of 'undefined' or 'null'.
    at _rx.Observable.combineLatest (C:\home\projects\freeCodeCamp\freeCodeCamp\api-server\server\boot/certificate.js:292:11)
    at tryCatcher (C:\home\projects\freeCodeCamp\freeCodeCamp\api-server\node_modules\rx\dist\rx.js:63:31)
    at CombineLatestObserver.tryCatcher (C:\home\projects\freeCodeCamp\freeCodeCamp\api-server\node_modules\rx\dist\rx.js:63:31)
    at tryCatcher (C:\home\projects\freeCodeCamp\freeCodeCamp\api-server\node_modules\rx\dist\rx.js:63:31)
    at runCallback (timers.js:705:18)
    at tryOnImmediate (timers.js:676:5)
    at processImmediate (timers.js:658:5)
From previous event:
    at combineLatest (C:\home\projects\freeCodeCamp\freeCodeCamp\api-server\server\boot/certificate.js:283:27)
    at tryCatcher (C:\home\projects\freeCodeCamp\freeCodeCamp\api-server\node_modules\rx\dist\rx.js:63:31)
    at InnerObserver.tryCatcher (C:\home\projects\freeCodeCamp\freeCodeCamp\api-server\node_modules\rx\dist\rx.js:63:31)
    at InnerObserver.tryCatcher (C:\home\projects\freeCodeCamp\freeCodeCamp\api-server\node_modules\rx\dist\rx.js:63:31)

// raw
{}


TypeError: Cannot destructure property `count` of 'undefined' or 'null'.
    at _rx.Observable.combineLatest (C:\home\projects\freeCodeCamp\freeCodeCamp\api-server\server\boot/certificate.js:292:11)
    at tryCatcher (C:\home\projects\freeCodeCamp\freeCodeCamp\api-server\node_modules\rx\dist\rx.js:63:31)
    at CombineLatestObserver.tryCatcher (C:\home\projects\freeCodeCamp\freeCodeCamp\api-server\node_modules\rx\dist\rx.js:63:31)
    at tryCatcher (C:\home\projects\freeCodeCamp\freeCodeCamp\api-server\node_modules\rx\dist\rx.js:63:31)
    at runCallback (timers.js:705:18)
    at tryOnImmediate (timers.js:676:5)
    at processImmediate (timers.js:658:5)
From previous event:
    at combineLatest (C:\home\projects\freeCodeCamp\freeCodeCamp\api-server\server\boot/certificate.js:283:27)
    at tryCatcher (C:\home\projects\freeCodeCamp\freeCodeCamp\api-server\node_modules\rx\dist\rx.js:63:31)
    at InnerObserver.tryCatcher (C:\home\projects\freeCodeCamp\freeCodeCamp\api-server\node_modules\rx\dist\rx.js:63:31)
    at InnerObserver.tryCatcher (C:\home\projects\freeCodeCamp\freeCodeCamp\api-server\node_modules\rx\dist\rx.js:63:31)
TypeError: Cannot destructure property `count` of 'undefined' or 'null'.
    at _rx.Observable.combineLatest (C:\home\projects\freeCodeCamp\freeCodeCamp\api-server\server\boot/certificate.js:292:11)
    at tryCatcher (C:\home\projects\freeCodeCamp\freeCodeCamp\api-server\node_modules\rx\dist\rx.js:63:31)
    at CombineLatestObserver.tryCatcher (C:\home\projects\freeCodeCamp\freeCodeCamp\api-server\node_modules\rx\dist\rx.js:63:31)
    at tryCatcher (C:\home\projects\freeCodeCamp\freeCodeCamp\api-server\node_modules\rx\dist\rx.js:63:31)
    at runCallback (timers.js:705:18)
    at tryOnImmediate (timers.js:676:5)
    at processImmediate (timers.js:658:5)
From previous event:
    at combineLatest (C:\home\projects\freeCodeCamp\freeCodeCamp\api-server\server\boot/certificate.js:283:27)
    at tryCatcher (C:\home\projects\freeCodeCamp\freeCodeCamp\api-server\node_modules\rx\dist\rx.js:63:31)
    at InnerObserver.tryCatcher (C:\home\projects\freeCodeCamp\freeCodeCamp\api-server\node_modules\rx\dist\rx.js:63:31)
    at InnerObserver.tryCatcher (C:\home\projects\freeCodeCamp\freeCodeCamp\api-server\node_modules\rx\dist\rx.js:63:31)
2019-02-18T08:29:21.048Z 500 PUT 183.855 ms - /internal/certificate/verify
```
  
</details>

**Comment by raisedadead** [comment]
Hmm @Bouncey has something changed from production for this to apprear?

**Comment by ValeraS** [comment]
It's only in the master, because of `updatePromise` resolves to `undefined`:
https://github.com/freeCodeCamp/freeCodeCamp/blob/4fd6515e1e2ec22172882964c0bb4b586461589c/api-server/server/boot/certificate.js#L275-L285

**Review by Bouncey — APPROVED** [review]
The [`updateAttributes`](https://apidocs.strongloop.com/loopback/#persistedmodel-prototype-updateattributes) method does return the updated instance if we wanted to keep the debug log the same.

But I don't think it adds anything at this time.

I am happy with this change

**Review by Bouncey — APPROVED** [review]
The [`updateAttributes`](https://apidocs.strongloop.com/loopback/#persistedmodel-prototype-updateattributes) method does return the updated instance if we wanted to keep the debug log the same.

But I don't think it adds anything at this time.

I am happy with this change

**Pull request merged**
