### PR TITLE
fix(curriculum): D3/DataVisualization Project 3

### LINKED ISSUE #47290: Update the x-axis ticks for the Data Visualization Heat map example project
### Describe the Issue

Each tick is exactly **one year off**, as you can see in FCCs example project [here](https://codepen.io/freeCodeCamp/full/JEXgeY). This shouldn't actually pass the test (user story 10) but it does. 
I have detailed the issues in this [post](https://www.reddit.com/r/FreeCodeCamp/comments/wnpxch/updoot_for_visibility_mods_correction_to_d3_heat/)

This is because the first/last ticks have half the spacing as every other, this makes the tick in the middle of the of the d3"rect".

### Affected Page

https://codepen.io/freeCodeCamp/full/JEXgeY

### Your code

```
  let newScale = d3.scaleBand()
   .domain(d3.range(1759,2019,10))      //2019 for 2009
                 .range([0, width])
                 .padding(.3);          //adjusts start/end ticks Different for each project
  let newAxis = d3.axisBottom(newScale) // ALSO modify call to newAxis 
```

### Expected behavior

I have already forked the codepen example project [here](https://codepen.io/ninjaboy667/pen/zYWmaRb?editors=0010) and fixed the tick marks. The code is much cleaner and easier to understand. 

### Screenshots

image

Notice that the tick is 1779 but the year is 1980

### System

- Device: macbook pro early 2015
- OS: Monterey 12.5
- Browser: I have tested with Firefox and Chrome, both have the ticks off by one year
- Version: latest

### Additional context

You should be able to fork [my solution ](https://codepen.io/ninjaboy667/pen/zYWmaRb?editors=0010)

[DD Here](https://www.reddit.com/r/FreeCodeCamp/comments/wnpxch/updoot_for_visibility_mods_correction_to_d3_heat/)

### PR DESCRIPTION
**Pull request by ninjaboy667**
As current example project does not have the x-axis tick marks lined up correctly either.

Checklist:

- [x] I have read [freeCodeCamp's contribution guidelines](https://contribute.freecodecamp.org).
- [x] My pull request has a descriptive title (not a vague title like `Update index.md`)
- [X] My pull request targets the `main` branch of freeCodeCamp.
- [X] I have tested these changes either locally on my machine, or GitPod.

Closes #47290

Update visualize-data-with-a-heat-map user story 10 with hint.

### CODE REVIEW

**Comment by Sembauke** [comment]
Hi @ninjaboy667,

Please read our contributing guidelines and update your pr-title.

Thanks, 
Have a nice day and happy coding

**Comment by ieahleen** [comment]
Also please if this PR closes the issue, use the `Closes #XXXXX` part to link PR and issue

**Review by majestic-owl448 — DISMISSED** [review]
thank you for one change to the PR title/body.
please apply also the other requested change in https://github.com/freeCodeCamp/freeCodeCamp/pull/47291#issuecomment-1218125866.

**Review by ninjaboy667 — COMMENTED** [review]
I think this is a good change.

**Comment by ieahleen** [comment]
The example project does have the ticks lined up correctly, I am not sure we want the hint.

This may be something that needs to be discussed first.

**Comment by ninjaboy667** [comment]
> The example project does have the ticks lined up correctly, I am not sure we want the hint.
> 
> This may be something that needs to be discussed first.

now that the example project has been corrected it seems less important. People just need to be aware that the default scaling only works when there is an equal number of ticks/bars.

**Pull request closed without merging**
