### PR TITLE
docs(i18n): updated German translation of PR guidelines

### PR DESCRIPTION
**Pull request by flechnical**
This translation fixes some grammar and semantics and improves overall readability for German readers.

- [x] I have read [freeCodeCamp's contribution guidelines](https://github.com/freeCodeCamp/freeCodeCamp/blob/master/CONTRIBUTING.md).
- [x] My pull request has a descriptive title (not a vague title like `Update index.md`)
- [x] My pull request targets the `master` branch of freeCodeCamp.
- [x] None of my changes are plagiarized from another source without proper attribution.
- [x] All the files I changed are in the same world language (for example: only English changes, or only Chinese changes, etc.)
- [x] My changes do not use shortened URLs or affiliate links.

### CODE REVIEW

**Comment by RandellDawson** [comment]
@flechnical Can you please change all instances of "pull-request" or "Pull-Request" to have a space instead of the hyphen?

Thank you.

**Comment by flechnical** [comment]
@RandellDawson sure thing

**Comment by RandellDawson** [comment]
@flechnical Thanks.

**Comment by RandellDawson** [comment]
@raisedadead Do we have any reviewers for this one?

**Comment by raisedadead** [comment]
I do not believe we have anyone, but I am going ahead and merging this for the hard work that has been put in by @flechnical :)

**Pull request merged**
