### PR TITLE
Safari IOS Fix

### LINKED ISSUE #6227: Sidebars that scroll independently of main page (such as the Map sidebar and the 'Help' Gitter chat sidebar), do not scroll on iPad

### PR DESCRIPTION
**Pull request by TylerDelRosario**
closes #6227

### CODE REVIEW

**Comment by HTMLNoob** [comment]
Please test this solution

**Comment by ltegman** [comment]
Please edit the message of your PR to contain `closes #xxxx` where `xxxx` is the issue number this fixes.

**Comment by SaintPeter** [comment]
Tested on iOS 9.2.1 and I was still unable to scroll the sidebar.  No apparent change.

**Comment by HTMLNoob** [comment]
I'm sorry for wasting your time guys. This was a solution provided by Apple themselves. So I dont think there is much of a solution for the problem as of right now,

**Comment by HTMLNoob** [comment]
I'll try and see if there is another way around this.

**Comment by QuincyLarson** [comment]
@HTMLNoob No worries, thank you for taking a crack at this. If you can fix it, please open a new PR.

**Pull request closed without merging**
