### PR TITLE
fix(curriculum):updated instructions on inline-styles

### LINKED ISSUE #39969: React: Add Inline Styles in React
**Describe your problem and how to reproduce it:**
Correct answer doesn't get evaluated to true.

**Add a Link to the page with the problem:**
https://www.freecodecamp.org/learn/front-end-libraries/react/add-inline-styles-in-react

**Tell us about your browser and operating system:**
* Browser Name: Firefox
* Browser Version: 
* Operating System: Windows 10 Home

**If possible, add a screenshot here (you can drag and drop, png, jpg, gif, etc. in this box):**
image

### PR DESCRIPTION
**Pull request by Mallikarjunople**
Checklist:

- [x] I have read [freeCodeCamp's contribution guidelines](https://contribute.freecodecamp.org).
- [x] My pull request has a descriptive title (not a vague title like `Update index.md`)
- [x] My pull request targets the `main` branch of freeCodeCamp.
- [x] I have tested these changes either locally on my machine, or GitPod.

Closes #39969 

Updated instructions as suggested by @kevinsmithidt

### CODE REVIEW

**Review by Sembauke — APPROVED** [review]
LGTM 👍

**Review by ShaunSHamilton — APPROVED** [review]
This LGTM 👍

**Comment by ShaunSHamilton** [comment]
Congrats on your first pull request (PR)! 🎉

Thank you, for your contribution to the page! 👍
We are happy to accept these changes and look forward to future contributions. 📝

**Comment by Mallikarjunople** [comment]
Yes, actually I am new to Github that's why I got confused. But I understood my mistake "not to commit anything to main , always work in branch". I will make sure to never repeat it again. Thanks for the valuable advice. :)

**Pull request merged**
