### PR TITLE
fix(docs): Update readme file to reflect new JS Certification Course

### LINKED ISSUE #53267: Update README to show list of new JS projects
Our current README, still lists the old JS curriculum

Screenshot 2024-01-18 at 6 58 18 AM

We need to update that to list out the new projects as well as the new certification projects.
Each of these projects should have links pointing to their respective pages.

It should follow this same format as the RWD cert here
Screenshot 2024-01-18 at 6 59 42 AM

### PR DESCRIPTION
**Pull request by ArvindParekh**
Checklist:

- [x] I have read and followed the [contribution guidelines](https://contribute.freecodecamp.org).
- [x] I have read and followed the [how to open a pull request guide](https://contribute.freecodecamp.org/#/how-to-open-a-pull-request).
- [x] My pull request targets the `main` branch of freeCodeCamp.
- [x] I have tested these changes either locally on my machine, or GitPod.

### CODE REVIEW

**Review by moT01 — APPROVED** [review]
LGTM @ArvindParekh 🎉

**Comment by moT01** [comment]
Actually, I am going to temporarily block this @ArvindParekh. The issue is labelled `first timers only`, and you have contributed before - I hope you don't mind. There's another PR where a first timer is trying to make the fix. If that PR doesn't get in, we can come back to this.

**Comment by ArvindParekh** [comment]
> Actually, I am going to temporarily block this @ArvindParekh. The issue is labelled `first timers only`, and you have contributed before - I hope you don't mind. There's another PR where a first timer is trying to make the fix. If that PR doesn't get in, we can come back to this.

Oh yes, no worries at all. Please prefer the other person, thanks!

**Comment by jdwilkin4** [comment]
We have just merged in this PR which addresses this issue.

https://github.com/freeCodeCamp/freeCodeCamp/pull/53294

As a result, we are going to close this PR

**Pull request closed without merging**
