### PR TITLE
chore: remove Cypress

### PR DESCRIPTION
**Pull request by Sembauke**
Checklist:

- [x] I have read and followed the [contribution guidelines](https://contribute.freecodecamp.org).
- [x] I have read and followed the [how to open a pull request guide](https://contribute.freecodecamp.org/#/how-to-open-a-pull-request).
- [x] My pull request targets the `main` branch of freeCodeCamp.
- [x] I have tested these changes either locally on my machine, or GitPod.

Closes #52905

### CODE REVIEW

**Comment by Sembauke** [comment]
@SocketSecurity ignore

**Review by naomi-lgbt — APPROVED** [review]
YES

**Review by naomi-lgbt — APPROVED** [review]
DOUBLE YES EVEN

**Review by Nirajn2311 — APPROVED** [review]
As a wise emperor once said, "Dew it"

**Review by huyenltnguyen — APPROVED** [review]

**Pull request merged**
