### PR TITLE
feat: added progress indicators to Block component

### PR DESCRIPTION
**Pull request by matthew-beaty**
- [x] I have read [freeCodeCamp's contribution guidelines](https://github.com/freeCodeCamp/freeCodeCamp/blob/master/CONTRIBUTING.md).
- [x] My pull request has a descriptive title (not a vague title like `Update index.md`)
- [x] My pull request targets the `master` branch of freeCodeCamp.
- [x] None of my changes are plagiarized from another source without proper attribution.
- [x] My article does not contain shortened URLs or affiliate links.

Partially addresses #17869 by adding progress indicators to the Curriculum.

Manually tested page: 
https://www.dropbox.com/s/1bo424pwqwnlb5e/Screenshot%202018-10-21%2015.44.30.png?dl=0

### CODE REVIEW

**Review by Bouncey — CHANGES_REQUESTED** [review]
These changes will have broken some tests. Run `npm test` in the project root to find out what is broken, I think it is mainly snapshots.

Side note, you can paste/drag-and-drop a screenshot into GitHub's comment boxes, and it will add it inline with your comment. That way, we do not need to signup to another service just to see a screenshot.

**Comment by matthewchase** [comment]
will do!

sidenote - oh whoops. fwiw, my work account must lock down the screenshots because an account isn't normally required. will drag and drop in the future anyway, especially is there auto-rendering

**Comment by matthewchase** [comment]
oh man. looks like i don't understand git, yet. i'll try to figure this out

**Comment by matthewchase** [comment]
hmm, looks like I had two branches for this, and this PR has an incomplete set of changes. Closing this pr, and made a new here (that also doesn't have hundreds of other commits XD)

**Pull request closed without merging**
