### PR TITLE
refactor: updating styles for RPG game

### PR DESCRIPTION
**Pull request by jdwilkin4**
## Summary of changes

This PR is responsible for updating the RPG game styles as discussed in the staff chat. 
I still kept the styles pretty simple since campers will be adding HTML, CSS and JavaScript in this project, and I don't want it to get to long.

## Before 
Screenshot 2023-12-10 at 11 05 56 PM

<br>

Screenshot 2023-12-10 at 11 06 54 PM

## After
Screenshot 2023-12-10 at 11 06 12 PM

<br>

Screenshot 2023-12-10 at 11 07 20 PM

Checklist:

- [x] I have read and followed the [contribution guidelines](https://contribute.freecodecamp.org).
- [x] I have read and followed the [how to open a pull request guide](https://contribute.freecodecamp.org/#/how-to-open-a-pull-request).
- [x] My pull request targets the `main` branch of freeCodeCamp.
- [x] I have tested these changes either locally on my machine, or GitPod.

### CODE REVIEW

**Comment by moT01** [comment]
Presumably this is ready for review @jdwilkin4? I added the label for that.

**Review by scissorsneedfoodtoo — APPROVED** [review]
Ran through the steps where you add HTML and CSS, and the later steps where you move the script tag to just before the closing `body` tag. All of the seeds seem to build towards and match what we currently have in the CurriculumExpansion repo. Everything LGTM 👍 

One thing I did notice is that the HTML seeds seem to use 4 spaces rather than 2 for each indent. But that's what we have in the CurriculumExpansion repo, and is a minor details outside the scope of this PR. We can adjust the spacing later if we decide to fix it.

**Review by Ksound22 — APPROVED** [review]
Everything's okay with this for me

**Review by naomi-lgbt — APPROVED** [review]
Styles look good, tabbed through all the steps and didn't see any reversion to the old styles. Should be good to land.

**Pull request merged**
