### PR TITLE
fix(UI): Resolved conflicting bg color in Tests

### LINKED ISSUE #55963: Code blocks in tests are same color as background
### Describe the Issue

Some codeblocks in the tests have the same color as the background - making it more difficult to notice them.

### Affected Page

https://www.freecodecamp.org/learn/javascript-algorithms-and-data-structures-v8/build-a-cash-register-project/

### Steps to Reproduce

1. Go to https://www.freecodecamp.org/learn/javascript-algorithms-and-data-structures-v8/build-a-cash-register-project/build-a-cash-register
1. Scroll down to the tests with the alternating background colors
1. See the codeblocks in the tests with the darker background blend in

### Expected behavior

It to not blend in like that. 

### Screenshots

_No response_

### System

Screenshot 2024-08-30 at 3 27 02 PM

^ notice on the ones with the darker background. The code blocks blend in.

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by Lalith246**
Checklist:

- [x] I have read and followed the [contribution guidelines](https://contribute.freecodecamp.org).
- [x] I have read and followed the [how to open a pull request guide](https://contribute.freecodecamp.org/how-to-open-a-pull-request/).
- [x] My pull request targets the `main` branch of freeCodeCamp.
- [x] I have tested these changes either locally on my machine, or GitPod.

Closes #55963

### CODE REVIEW

**Review by anandfresh — COMMENTED** [review]
LGTM

**Comment by jeremylt** [comment]
> LGTM

Please stop posting this on PRs where you don't have approval permissions

**Comment by lasjorg** [comment]
Not sure if there was an actual consensus on this but here is how the PR looks.

light-mode
dark-mode

It feels a little off to me, but the contrast is definitely better.

---

I have unblocked the PR.

**Review by a2937 — APPROVED** [review]
This was a very hard pick. At the end of the day, the CSS selector is less redundant than the other PR. For that reason , I am approving this one.

**Review by ahmaxed — APPROVED** [review]
We might be able to simplify it further in the next iterations or use the Table component, but this LGTM.

Screenshot 2024-10-01 at 4 56 22 PM

**Pull request merged**
