### PR TITLE
Fix imperative wording for starring the repo

### PR DESCRIPTION
**Pull request by balthazar**
Hi :wave:! First of, thanks for this amazing job, keep it up!

I've changed the texts of the getting started challenge for the github :star: step.
This way, people now really understand that they're not forced to do so to go to the next step, but it's only a way to support the community.

I would have preferred that clicking the link would be also optional and that the next button was not disabled, but this may add a bit of logic, so I dunno what you think about that.

Thanks!

### CODE REVIEW

**Comment by SaintPeter** [comment]
@QuincyLarson Please take a look.

**Comment by QuincyLarson** [comment]
Hi Apercu,

Thanks for the PR. All the steps in all the challenges are imperative - not just this one - and we require lock the "next step" button because if we don't, people will just click through these slides really fast without reading them, which is really detrimental to their overall experience with Free Code Camp.

We have experimented with all of this. Introducing ambiguity "if you want to" etc. actually makes completing these challenges much more stressful, because on top of everything else, the user has to make judgement calls, which saps their mental reserves.

**Comment by Apercu** [comment]
Hi @QuincyLarson.

I can understand the button lock, but I really don't grasp how it would be stressful to tell people that if they don't want to star the repository now, it's entirely up to them to do so, without getting locked to progress on the website.

Steps about the Github account creation and the Gitter to join the chatrooms are fine, but the mandatory starring (since everyone understands that it is) seems only to me a roundabout way to advertise by using new users inexperience rather than teach people how the project works to get them started.

The challenge title is actually only "Create a GitHub Account and Join our Chat Rooms", and this step doesn't fit with the challenge goal at all.

**Comment by QuincyLarson** [comment]
Hi @Apercu I just saw your response here. I appreciate you taking the time to further explain your thoughts.

I have gone ahead and merged your pull request, updating the Spanish and English wording. 

Thank you for your contribution to our codebase. We welcome more contributions from you in the future :)

**Comment by Apercu** [comment]
@QuincyLarson Thank you for reviewing this again glad you understand how I felt about this.

Will do if I find something else to improve ;)

**Pull request merged**
