### PR TITLE
fix(curriculum): force directed graph example link

### PR DESCRIPTION
**Pull request by moT01**
Related to [comment.](https://github.com/freeCodeCamp/freeCodeCamp/pull/47321#issuecomment-1219818120) I added the project to the freeCodeCamp codepen account and made some minor improvements while I was at it.

- [x] I have read [freeCodeCamp's contribution guidelines](https://contribute.freecodecamp.org).
- [x] My pull request has a descriptive title (not a vague title like `Update index.md`)
- [x] My pull request targets the `main` branch of freeCodeCamp.
- [x] I have tested these changes either locally on my machine, or GitPod.

Closes #XXXXX

### CODE REVIEW

**Review by Sboonny — APPROVED** [review]
LGTM 🎉, thank you for your contribution to the page! 👍.

**Review by Sembauke — CHANGES_REQUESTED** [review]
The new project seems a bit different from the old one, and I see some issues when scrolling the page. 

image

The lines seems to disappear, I do not think this is intentional. I am using  a chromium browser.

**Comment by moT01** [comment]
that was present in my old project of this, too @Sembauke. I made a few little tweaks that make that not as bad, but it's still kind of there. Want to take another look?

**Comment by Sembauke** [comment]
I think it is good to go, thanks for taking another look at this Tom.

**Review by Sembauke — APPROVED** [review]

**Comment by moT01** [comment]
Going to merge this. The link will be updated and we can further improve the project on codepen without having to update the link again.

**Pull request merged**
