### PR TITLE
fix(docs): npm run commit has been removed

### PR DESCRIPTION
**Pull request by jonathan-grah**
The npm script `npm run commit` appears to have been removed.
Updating the docs accordingly.

### CODE REVIEW

**Review by ojeytonwilliams — APPROVED** [review]
LGTM :+1:

**Comment by ojeytonwilliams** [comment]
I took a quick look at the rest of that document and `npm run bootstrap` isn't typically what you want to do.  Better advice would be just to use `npm ci`.  Would you mind changing that as well?

**Comment by ojeytonwilliams** [comment]
Thanks!

**Comment by jonathan-grah** [comment]
@ojeytonwilliams, makes perfect sense as `npm ci` is caught by `postinstall` and runs `npm run bootstrap` anyways. If you run `npm run bootstrap` by itself, `lerna` may not be installed to run in the first place in my testing.

**Comment by ojeytonwilliams** [comment]
@jonathan-grah yep, you're right.  Most people won't ever need to worry about that, can just run `npm ci` and have it all work nicely.

**Review by thecodingaviator — APPROVED** [review]
LGTM

**Comment by thecodingaviator** [comment]
Thank you for your contribution to the page! 👍
We're happy to accept these changes, and look forward to future contributions. 📝

**Pull request merged**
