### PR TITLE
fix(ci): add node 18 build, test variants

### PR DESCRIPTION
**Pull request by raisedadead**
This PR can sit here and brew for a while. We can merge it in a few days when I will add a commit that removes Node 16. Till then we get to validate the bump.

### CODE REVIEW

**Review by Sboonny — DISMISSED** [review]
approving it, so it can be pushed forward faster, when needed

**Comment by naomi-lgbt** [comment]
Hey Mrugesh, is this still blocked?

**Comment by raisedadead** [comment]
Sort off - the CI flows should be updated only after we have moved all the servers over to v18. This is on my backlog.

**Comment by naomi-lgbt** [comment]
Sure - let me know if there is anything I can do to help.

**Pull request merged**
