### PR TITLE
consolidated .json files into one and updated the imports and references to it.

### LINKED ISSUE #38200: Update congratulatory quotes
Refers changes from #37952

The changes from the linked PR should go into the correct file, I believe there are multiple such files.

We need to audit and combine all of them to one, and at the same time move them into the common config location.

### PR DESCRIPTION
**Pull request by rdm100**
Checklist:

- [x] I have read [freeCodeCamp's contribution guidelines](https://github.com/freeCodeCamp/freeCodeCamp/blob/master/CONTRIBUTING.md).
- [x] My pull request has a descriptive title (not a vague title like `Update index.md`)
- [x] My pull request targets the `master` branch of freeCodeCamp.
- [x] All the files I changed are in the same world language, for example: only English changes, or only Chinese changes, etc.

Closes #38200 

I forked the correct repository this time.

consolidated .json files into one at utils/words.json on fix/update-congratulatory-quotes branch.
and also updated the files that referenced the original separate .json files to reference the new consolidated .json file.

Let me know if it is ok?

### CODE REVIEW

**Comment by raisedadead** [comment]
Hi,

Can you confirm this was done locally and you have tested everything works? 

Also we would need you to go through the contributing documentation throughly. We recommend you to send pull-requests from a non-default branch (which would be `master`). This is to avoid soiling your copy fork for review changes that we may request.

Please reach out to [contributors chat room](https://gitter.im/FreeCodeCamp/Contributors) if you need help thru this.

**Comment by rdm100** [comment]
@raisedadead yes I forked it and then worked on it locally created a new branch made the changes needed and merged it back into the master of my fork, pushed it to the fork and then made the pull request.

No I have not tested it because I didn't know how to go about that, I will ask in the contributors chat room as you suggest.

**Comment by raisedadead** [comment]
> I didn't know how to go about that, ...

I believe we have documented everything in our [guidelines for contributing](https://github.com/freeCodeCamp/freeCodeCamp/blob/master/CONTRIBUTING.md). I recommend you give it a through read.

**Comment by rdm100** [comment]
@raisedadead thanks I will take another look I must have missed that.

**Comment by raisedadead** [comment]
Please re-open a fresh request when ready

**Pull request closed without merging**
