### PR TITLE
update hr element guide to indicate use for separating themes; remove …

### PR DESCRIPTION
**Pull request by morganda**
…xhtml syntax as it is outdated and confusing to beginners

- [x] I have read [freeCodeCamp's contribution guidelines](https://github.com/freeCodeCamp/freeCodeCamp/blob/master/CONTRIBUTING.md).
- [x] My pull request has a descriptive title (not a vague title like `Update index.md`)
- [x] My pull request targets the `master` branch of freeCodeCamp.
- [x] None of my changes are plagiarized from another source without proper attribution.
- [x] My article does not contain shortened URLs or affiliate links.

Closes #XXXXX

### CODE REVIEW

**Comment by morganda** [comment]
The contribution guidelines do not say anything about updating the guide for other languages. I unfortunately can't help directly with translating. Any suggestions to help get that done or is there some other process for updating the guid in other languages?

**Review by bikingbadger — APPROVED** [review]
Makes much more sense. Good job on clarifying things.

**Comment by RandellDawson** [comment]
Your changes look fine, other than you need to add Resources back in:

```
## Resources:
* [MDN](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/hr)
* [W3C](http://w3c.github.io/html-reference/hr.html)
```

**Comment by morganda** [comment]
Yep you're right. Added back in.

**Comment by RandellDawson** [comment]
Congrats @morganda on your first pull request (PR)! 🎉

Thank you for your contribution to the page! 👍
We're happy to accept these changes, and look forward to future contributions. 📝

**Pull request merged**
