### PR TITLE
Update to "Search and Replace" intermediate solution

### PR DESCRIPTION
**Pull request by Jryke**
new solution addresses the possibility of first letter of arg "before" being lower case and needing to change the first letter of "after" from capital to lowercase

solution more streamlined

added resource to help with regular expressions

- [x] I have read [freeCodeCamp's contribution guidelines](https://github.com/freeCodeCamp/freeCodeCamp/blob/master/CONTRIBUTING.md).
- [x] My pull request has a descriptive title (not a vague title like `Update index.md`)
- [x] My pull request targets the `master` branch of freeCodeCamp.
- [x] None of my changes are plagiarized from another source without proper attribution.
- [x] All the files I changed are in the same world language (for example: only English changes, or only Chinese changes, etc.)
- [x] My changes do not use shortened URLs or affiliate links.

Closes #XXXXX

### CODE REVIEW

**Comment by Jryke** [comment]
Another note: Are the advanced solutions really more advanced?  They check for uppercase/lowercase for the entire words, but the challenge only asks to check for the first letter.  The advanced solutions appear to be bloated code that are arguably not more advanced than the intermediate solution.

**Comment by RandellDawson** [comment]
>new solution addresses the possibility of first letter of arg "before" being lower case and needing to change the first letter of "after" from capital to lowercase

Can you provide an example where the solution you replaced would not work correctly?

**Comment by Jryke** [comment]
The existing solution doesn't account for arg "before" starting with a lower case letter and arg "after" starting with a capital letter.  An example of a solution that will not replace the word correctly is:

myReplace("A quick brown fox jumped over the lazy dog", "jumped", "Leaped");

which will return "A quick brown fox **L**eaped over the lazy dog".  In this case, if the "before" (jumped) starts with a lower case letter, then "after" (Leaped) should return as a lower case letter as well.  

A correct solution should return "A quick brown fox **l**eaped over the lazy dog".  This solution has a lower case "l" in "leaped" in order to "preserve the case of the first character in the original word" as the instructions state.  

The current solution accounts for making the first letter capital to match, but not making the first letter lower case to match.

**Comment by RandellDawson** [comment]
@Jryke So not only is the solution in correct, we need an additional test in the challenge.  Would you be interested in also adding the new test case you bring up here, so that we don't allow incorrect solutions to pass for other campers?

**Comment by Jryke** [comment]
@RandellDawson I will be happy to add new test cases to the challenge file.  

In reference to the test cases that you discussed above, I will also make sure that the solution requires the "before" argument to match the word in the "str" argument exactly (with the same capital/lowercase letter)?  Currently, this solution is passing even if the "before" argument does not match the case of the word in the "str" argument even though in practice the code doesn't work.

test case: 
`myReplace("A quick brown fox jumped over the lazy dog", "Jumped", "leaped");`
This test case is passing with the current solution but is not functionally correct because the "jumped" in the "str" argument does not match "Jumped" in the "before" arg.  In other words, code that allows this is passing even though it is not functional in JavaScript.  

I think that the test cases should include words that start with **both** capital and lower case letters because those test cases will test the true functionality of the solution.

**Comment by RandellDawson** [comment]
@Jryke Before moving forward on the exact changes, let's get some feedback from a couple other mods (who I tagged in my last reply).  We want to make sure we have a consensus before we make breaking changes to the challenge.

Thanks for your patience.

**Comment by moT01** [comment]
What about this..
`myReplace("A quick brown fox jUmpEd over the lazy dog", "JuMPeD", "leaped");`
or this..
`myReplace("A quick brown fox jumped over the lazy dog", "asdfasdf, "leaped");`


#### My solution
Add two tests similar to this maybe -
```
myReplace("A quick brown fox jumped over the lazy dog", "jumped", "Leaped");
should return "A quick brown fox leaped over the lazy dog"
```
```
myReplace("A quick brown fox jumped over the lazy dog", "Jumped", "leaped");`
should return "Jumped not found"
```
Add something like this at the bottom of the instructions -
```
If the word you are searching for is not found, return the word with "not found" after it.
For example, if your search does not find "Book", return "Book not found".
```

Or perhaps, return the original sentence if the word isn't found.

Not sure if this is the best way to go.

@Jryke 
> Are the advanced solutions really more advanced?

No, they look convoluted to me - advanced solutions should be clean and concise with as few lines of code as possible using the latest syntax. Beginner solutions should be step by step logic. Why do we need 5 solutions for this challenge? I don't know - I guess it's not really hurting, but it does clutter up the article in my opinion.

**Comment by RandellDawson** [comment]
> Also, it's not clear to me what case we are preserving - the case of the word in the sentence? or the case of the word in the before argument

The current instructions indicate the replaced word should keep the case of the original word it replaced.      That is why I thought we should make all the cases of the before and after arguments lowercase, so people don't think they have to make it the case of one of them instead.

**Comment by moT01** [comment]
Yea, I think that would work pretty good @RandellDawson - I may have been overthinking.

**Comment by Jryke** [comment]
I think that one of the important parts of this challenge is that the solution must include fixing the case of the first letter.  Otherwise, the solution is just using the .replace method.  The real challenge here is to make the first letter match the case before using the .replace method.  The issue I brought up from the beginning is that if the "before" argument starts with a capital letter, then the solution should require the "after" argument to also start with a capital letter.  

If all of the test cases have both the "before" and "after" arguments start with lower case letters, then this challenge becomes simpler and loses the essence of what I think was originally intended.

**Comment by ojeytonwilliams** [comment]
So, I think I'm up to speed!  The problem, as I see it, is that the challenge is a little ambiguous.  It doesn't say if `before` should match in a case sensitive or insensitive way.  It also doesn't mention if all the instances of `before` need replacing, but hey.

If we go for case insensitive the camper has to come up with something like

```js
function myReplace(str, before, after) {
  if (before[0] === before[0].toUpperCase()) {
    after = after[0].toUpperCase() + after.slice(1);
  } else {
    after = after[0].toLowerCase() + after.slice(1);
  }
  return str.replace(new RegExp(before, "i"), after);
}
```

Now this isn't stupidly hard, but it is quite a lot for a challenge.

As such, I think we should focus on the interesting bit of the challenge, namely the fact that the original sentence's case is preserved.  So, if we want a strict match we'd need to add something like

>  For this challenge, `before` should be replaced only if there is an exact match i.e. myReplace("Hello", "hello", "there") would not replace anything, returning "Hello".

to the instructions.  I was thinking about @moT01's idea of 'word not found' and it's nice, but I think it might make the solution a bit too long and distract from the searching and replacing.

Also, I agree with @Jryke, the tests should check if the case is preserved.  They will need examples where `before` and `after` have opposite cases to demonstrate that the original sentence controls the case.

**Comment by Jryke** [comment]
Do we have a decision on how to fix this challenge?  I agree with @ojeytonwilliams that 

> I think we should focus on the interesting bit of the challenge, namely the fact that the original sentence's case is preserved. 

Again, I will be happy to make the changes once we decide exactly what we want to do

**Comment by moT01** [comment]
I think the upside to randell's suggestion here is that it's an easier fix - It would just be changing the tests if I understand it correctly. If we go rewording the challenge and making different types of returns for when a word isn't found - then it makes all the solutions in the guide need updating as well.

I'm fine with the length of the challenge/solution - it's in the algorithms area, so there's a number of others that are longer. 

I don't mind either way here, what do you think @Jryke?

**Comment by Jryke** [comment]
Given the difficulty of the other challenges in the algorithms section, any of the suggested changes aren't too difficult.  

I think that changing the test cases is good enough; it still maintains the objective of the challenge but accounts for what I originally brought up as the issue (no test of: "before" starting with a capital letter && "after" starting with a lower case letter).  To make a test case that exists in a real life scenario, we could make the word in the "str" and "before" a name of a person or place (which should be capital) and the "after" word starting with a lower case letter.

**Comment by moT01** [comment]
Sounds good to me - if @RandellDawson or @ojeytonwilliams want to second that, I think it would be fine to get a PR started and we can review it from there.

**Comment by Manish-Giri** [comment]
I think we should keep the focus of the algorithm on just two things - search and replace and maintain the case of the original word in the sentence. As @ojeytonwilliams mentioned earlier, checking for presence of `before` in `str`, or case-sensitive/insensitive match of `before` with the corresponding word in `str`, or adding different returns based on the presence of `before` - it's just putting a whole lot of things in one challenge. Most of these exercises have already been covered in earlier challenges.

**Comment by Jryke** [comment]
@Manish-Giri I agree.  The only change that I am proposing at this point is that the test cases include at least one that "before" starts with a lower case letter and "after" starts with a capital letter. 

current test cases: 

> myReplace("Let us go to the store", "store", "mall") should return "Let us go to the mall".

> myReplace("He is Sleeping on the couch", "Sleeping", "sitting") should return "He is Sitting on the couch".

> myReplace("This has a spellngi error", "spellngi", "spelling") should return "This has a spelling error".

> myReplace("His name is Tom", "Tom", "john") should return "His name is John".

> myReplace("Let us get back to more Coding", "Coding", "algorithms") should return "Let us get back to more Algorithms".

I propose that one or both of these existing test cases be changed to: 
myReplace("He is **s**leeping on the couch", "**s**leeping", "**S**itting") should return "He is **s**itting on the couch".
> myReplace("Let us get back to more **c**oding", "**c**oding", "**A**lgorithms") should return "Let us get back to more **a**lgorithms".

These test cases make more sense this way anyway as these words should be correctly written as lowercase anyway.  I think the important part is that the capital letter matching goes both ways between the "before" and "after" arguments.  

This conversation initially started because I was proposing a change to the solution page that resolves the capital/lowercase letter both ways.  The current solution resolves the current test cases but not the test cases that I am proposing to be added.

**Comment by Manish-Giri** [comment]
@Jryke Oh yes, I'm totally on board the changes you suggested! They are still in scope with the original challenge of matching the case of the word, and the tests should rightly be amended, as your examples state.

I was just referring to some of the other changes like different return types or checking if `before` exists. I felt like these were not necessarily in-scope with the central idea of the challenge.

**Comment by RandellDawson** [comment]
@Jryke Since in end, the after word which replaces will need to have the same case of the original before word's case it had in the sentence, I still think it is less confusing to a camper to keep the arguments all lowercase.  In fact, you could make them both uppercase which might even make it clearer.   Plus, we might be able to have less test cases this way.

**Comment by Jryke** [comment]
@RandellDawson I think that if we make all of the arguments the same case, this defeats the point of the challenge.  Without differences in cases, all the user needs to do is use the `.replace` method.  The point of this challenge is to make sure that the arguments match the case of the first letter before performing the replace.  

I agree that making the case of the "before" argument different from the word in the "str" argument might make this challenge too confusing or difficult.  However, having a different case for the "before" and "after" arguments is the whole point of this challenge and I think should absolutely be maintained as part of the challenge.

**Comment by RandellDawson** [comment]
>Without differences in cases, all the user needs to do is use the .replace() method.

That is not true.  The final case of the replacement is still based on the original case of the word which was replaced.  It is not just a simple replace.

**Comment by Jryke** [comment]
My point is that if the cases are the same then there is no need to change anything to match the original case.  I'm not sure how we are misunderstanding each other.

**Comment by RandellDawson** [comment]
>  I'm not sure how we are misunderstanding each other.

I am not misunderstanding.  I am saying there will always be cases where it wont' matter (i.e they are both lowercase) and there will be cases where the original is uppercase, so the replacement (2nd argument) which is lower-case (in my scenario) will need to be made uppercase.  If the fact that both arguments are lowercase, then let's make both arguments all-caps for all test-case function calls.  See test cases below:
```
myReplace("Let us go to the store", "STORE", "MALL") should return "Let us go to the mall".

myReplace("He is Sleeping on the couch", "SLEEPING", "SITTING") should return "He is Sitting on the couch".

myReplace("This has a spellngi error", "SPELLINGI", "SPELLING") should return "This has a spelling error".

myReplace("His name is Tom", "TOM", "JOHN") should return "His name is John".

myReplace("Let us get back to more Coding", "CODING", "ALGORITHMS") should return "Let us get back to more Algorithms".
```

**Comment by raisedadead** [comment]
IMHO, since this conversation has taken a direction where we are talking about the challenge itself, I recommend let's close this and talk on a separate issue thread about the challenge.

Keep in mind that these challenges are soon to become legacy, with our updated project based curriculum. So we also need to consider the worth of updating a old challenge vs incorporating the concept into the project based curriculum instead.

If you all agree, then please let me know. I'll create an issue and close this.

**Comment by RandellDawson** [comment]
@raisedadead After reviewing this PR again, let's go ahead and merge it (once I fix the merge conflict) and convert it to the new format of the curriculum-related guide articles and have a separate issue created to continue the discussion around changing the actual challenge and tests.

**Comment by RandellDawson** [comment]
@raisedadead OK, I fixed the merge conflicts for this PR and made sure the new format was preserved along with the OP's solution code and code explanation changes.  I am OK merging this one now.

**Comment by raisedadead** [comment]
Okay, can you then please take care of creating the issue since you are already on top of this and have all the relevant details. I am going to land this.

**Review by raisedadead — APPROVED** [review]

**Comment by raisedadead** [comment]
@Jryke thanks a lot for all your inputs and work on this PR. Happy contributing.

**Comment by Jryke** [comment]
@raisedadead @RandellDawson Thank you!

**Comment by RandellDawson** [comment]
@Jryke Would you be interested in creating the new issue and referencing this PR, so we can continue discussing the possible challenge instruction and test changes?  Maybe also hit the highlights of this thread?  Just let us know.

Thanks again for your patience.

**Comment by Jryke** [comment]
I created an issue to change this challenge and mentioned the different topics we discussed in this thread.  Here is the link:
[https://github.com/freeCodeCamp/freeCodeCamp/issues/36520](url)
Let me know if there is anything else I can do to help!

**Comment by raisedadead** [comment]
Thanks a lot @Jryke !

**Pull request merged**
