### PR TITLE
chore(client): refactor ImageLoader

### PR DESCRIPTION
**Pull request by ghost**
Checklist:

- [x] I have read [freeCodeCamp's contribution guidelines](https://contribute.freecodecamp.org).
- [x] My pull request has a descriptive title (not a vague title like `Update index.md`)
- [x] My pull request targets the `master` branch of freeCodeCamp.
- [x] All the files I changed are in the same world language, for example: only English changes, or only Chinese changes, etc.

Hello,

* Edited an eslint rule to allow `onLoad` attribute on img elements
* Converted the ImageLoader component into a functional one

Please review :)

### CODE REVIEW

**Comment by RandellDawson** [comment]
@max-voronov Can you please use arrow function syntax for `ImageLoader`.  Right now it is a mix of ES6 and non-ES6?

**Comment by max-voronov** [comment]
> @max-voronov Can you please use arrow function syntax for `ImageLoader`. Right now it is a mix of ES6 and non-ES6?

Do you mean changing `function ImageLoader({` to be an arrow function?
I yes then most of the components in the same folder defined this way and not as an arrow function.
If you mean something else could you explain please? :)

**Comment by RandellDawson** [comment]
@max-voronov Yes, that is exactly what I mean.  Might as well use arrow function syntax if you are making changes anyway.

**Comment by max-voronov** [comment]
> @max-voronov Yes, that is exactly what I mean. Might as well use arrow function syntax if you are making changes anyway.

OK thanks, I've pushed a CR commit with the requested changes

**Comment by max-voronov** [comment]
Squashed the change that uses arrow function syntax for functional component definition.

Please let me know if something else needed for this PR :)

**Comment by ahmadabdolsaheb** [comment]
Thanks for making imageLoader more concise.  LGMT
To avoid having a global jslint exception, we could only delete the lower jslint line exception and it should be good enough.
```js
      {/* eslint-disable jsx-a11y/no-noninteractive-element-interactions */}
      <img
        alt={alt}
        className={fullClassName}
        onLoad={() => setLoaded(true)}
        src={src}
      />
```

**Comment by max-voronov** [comment]
> Thanks for making imageLoader more concise. LGMT
> To avoid having a global jslint exception, we could only delete the lower jslint line exception and it should be good enough.
> 
> ```js
>       {/* eslint-disable jsx-a11y/no-noninteractive-element-interactions */}
>                alt={alt}
>         className={fullClassName}
>         onLoad={() => setLoaded(true)}
>         src={src}
>       />
> ```

Thanks for the review :)

I've removed the global lint exception and added back `{/* eslint-disable jsx-a11y/no-noninteractive-element-interactions */}`
Please let me know if any additional changes needed.

**Review by ahmaxed — APPROVED** [review]

**Comment by raisedadead** [comment]
Thanks @max-voronov for making this PR and contributing to the codebase for the first time. Looking forward to more contributions.🎉 🎉

**Pull request merged**
