### PR TITLE
Change number of car seats to 5

### LINKED ISSUE #9565: Change number of car seats to 5
#### Challenge Name

https://www.freecodecamp.com/challenges/make-instances-of-objects-with-a-constructor-function

#### Issue Description

Same issue as #9544 but in another challenge.

#### To Fix
[This line in an example block](https://github.com/FreeCodeCamp/FreeCodeCamp/blob/a9c172454fcc1b637830a5fd6ff3cdf20d0543b6/seed/challenges/01-front-end-development-certification/object-oriented-and-functional-programming.json#L120), [this line in the challenge seed](https://github.com/FreeCodeCamp/FreeCodeCamp/blob/a9c172454fcc1b637830a5fd6ff3cdf20d0543b6/seed/challenges/01-front-end-development-certification/object-oriented-and-functional-programming.json#L132), and [this line in the solution](https://github.com/FreeCodeCamp/FreeCodeCamp/blob/a9c172454fcc1b637830a5fd6ff3cdf20d0543b6/seed/challenges/01-front-end-development-certification/object-oriented-and-functional-programming.json#L143) needs to be changed to have 5 seats (e.g. `this.seats = 5;`).

#### To Contributors

Please first read the [contributing guidelines](https://github.com/FreeCodeCamp/FreeCodeCamp/blob/staging/CONTRIBUTING.md) before taking care of this issue. And feel free to visit the [Contributors Help](https://gitter.im/FreeCodeCamp/HelpContributors) chat room if you have any questions about helping. We're there to help. 

This issue is labeled `first-timers-only` so only those who have not contributed to Free Code Camp's main repository may resolve this issue. 

#### Screenshot

image

### PR DESCRIPTION
**Pull request by ladybugtju**
#### Pre-Submission Checklist

- [x] Your pull request targets the `staging` branch of FreeCodeCamp.
- [x] Branch starts with either `fix/`, `feature/`, or `translate/` (e.g. `fix/signin-issue`)
- [x] You have only one commit (if not, [squash](https://github.com/FreeCodeCamp/FreeCodeCamp/wiki/Git-Squash) them into one commit).
- [x] All new and existing tests pass the command `npm run test-challenges`. Use `git commit --amend` to amend any fixes.
#### Type of Change

- [x] Small bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds new functionality)
- [ ] Breaking change (fix or feature that would change existing functionality)
- [ ] Add new translation (feature adding new translations)
#### Checklist:

- [x] Tested changes locally.
- [x] Closes currently open issue (replace XXXX with an issue no): Closes #9565

### CODE REVIEW

**Comment by BKinahan** [comment]
You should include `Closes #9565` in the description text (that's what this line is for: `Closes currently open issue (replace XXXX with an issue no): Closes #XXXX`)

GitHub will then cross-reference the pull request and the issue automatically.

Also, while you're at it, consider changing the number of seats a car has for all other instances (eg translations since it's only a number change, and other challenges in the same file which also mention how cars have one seat).

**Comment by BKinahan** [comment]
You should have only one commit. It looks like you merged from the `master` branch into your fix branch instead of rebasing your `staging` from the FCC `staging` branch, adding a bunch of extra commits to your branch.

If you need help, visit the [HelpContributors](https://gitter.im/FreeCodeCamp/HelpContributors) chat room 😄

**Comment by raisedadead** [comment]
@ladybugtju Please visit the Contributors chat room for assistance as mentioned by @BKinahan above. We will help you in creating a pull request.

Closing, this pull request.

**Comment by ladybugtju** [comment]
Thanks for the notification @BKinahan @raisedadead . These commits didn t show when I made the request. I actually did the rebase after forking the repo and upstreaming form master. I think I got that fixed now and will check on the chat room.

**Pull request closed without merging**
