### PR TITLE
Advanced Ziplines translated into Brazilian Portuguese 

### PR DESCRIPTION
**Pull request by andreferreira-me**
#### Pre-Submission Checklist

- [X] Your pull request targets the `staging` branch of FreeCodeCamp.
- [X] Branch starts with either `fix/`, `feature/`, or `translate/` (e.g. `fix/signin-issue`)
- [X] You have only one commit (if not, [squash](http://forum.freecodecamp.com/t/how-to-squash-multiple-commits-into-one-with-git/13231) them into one commit).
- [ ] All new and existing tests pass the command `npm run test-challenges`. Use `git commit --amend` to amend any fixes.
#### Type of Change

- [ ] Small bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds new functionality)
- [ ] Breaking change (fix or feature that would change existing functionality)
- [X] Add new translation (feature adding new translations)
#### Checklist:

- [ ] Tested changes locally.
- [x] Closes currently open issue (replace XXXX with an issue no): Closes FreeCodeCamp/TranslationExpansion#86
#### Description

advanced-ziplines.json translated into Brazilian Portuguese

### CODE REVIEW

**Comment by raisedadead** [comment]
needs a peer review.

**Comment by tmpvnunes** [comment]
Can I give a suggestion? What about Portuguese (European) translation to the project?

**Comment by raisedadead** [comment]
@tmpvnunes please check the guidelines http://forum.freecodecamp.com/t/guidelines-for-translating-free-code-camp-to-any-language/19111

**Comment by samanthakem** [comment]
Just reviewed it @andreferreira-me :)
Sorry I took long, have been traveling a little.

**Comment by raisedadead** [comment]
@andreferreira-me @samanthakem  thanks a lot for the pull request and the peer review! looking forward to more.. 😉 !

#### :sparkles: :sparkles: **LGTM.** :sparkles: :sparkles: 

Thanks.

**Comment by andreferreira-me** [comment]
Thanks @raisedadead!! Thanks @samanthakem for review it! 👍

**Comment by tmpvnunes** [comment]
@andreferreira-me  gostaria tambem de participar e ajudar na traducao para o portugues de portugal

**Comment by andreferreira-me** [comment]
Legal @tmpvnunes! Confira os links a seguir:
http://forum.freecodecamp.com/t/guidelines-for-translating-free-code-camp-to-any-language/19111/
https://github.com/FreeCodeCamp/TranslationExpansion/issues

**Pull request merged**
