### PR TITLE
removed '/' from Link

### PR DESCRIPTION
**Pull request by AkshayBabbar**
'/' was linking to the wrong link. Updated please review

- [x] I have read [freeCodeCamp's contribution guidelines](https://github.com/freeCodeCamp/freeCodeCamp/blob/master/CONTRIBUTING.md).
- [x] My pull request has a descriptive title (not a vague title like `Update index.md`)
- [x] My pull request targets the `master` branch of freeCodeCamp.
- [x] None of my changes are plagiarized from another source without proper attribution.
- [x] My article does not contain shortened URLs or affiliate links.

If your pull request closes a GitHub issue, replace the XXXXX below with the issue number.

Closes #XXXXX

### CODE REVIEW

**Comment by AkshayBabbar** [comment]
Please provide REASON

**Comment by Manish-Giri** [comment]
LGTM 👍

**Comment by AkshayBabbar** [comment]
> LGTM 👍

can you please check other also since they have been marked invalid.

**Comment by QuincyLarson** [comment]
@RandellDawson I agree with @Manish-Giri - This PR does seem to fix a broken link (the https://en.wikipedia.org/wiki/Rabin%E2%80%93Karp_algorithm/ link with the trailing slash doesn't work on Wikipedia for some reason).

**Comment by RandellDawson** [comment]
@QuincyLarson I labeled it invalid, because it was a self-closure at the time I saw it.

**Review by Manish-Giri — APPROVED** [review]
Hi @AkshayBabbar 

Congrats on your first pull request (PR)! 🎉

Thank you for your contribution to the page! 👍 We're happy to accept these changes and look forward to future contributions. 📝

**Comment by AkshayBabbar** [comment]
Thanks @Manish-Giri  will surely look forward to involve more in FreeCodeCamp. 👍

**Pull request merged**
