### PR TITLE
fix: Update regex to have more color values

### PR DESCRIPTION
**Pull request by prateekgoel**
#### Pre-Submission Checklist

- [x] Your pull request targets the `staging` branch of freeCodeCamp.
- [ ] Branch starts with either `fix/`, `feature/`, or `translate/` (e.g. `fix/signin-issue`)
- [x] You have only one commit (if not, [squash](http://forum.freecodecamp.org/t/how-to-squash-multiple-commits-into-one-with-git/13231) them into one commit).
- [ ] All new and existing tests pass the command `npm test`. Use `git commit --amend` to amend any fixes.

#### Type of Change

- [x] Small bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds new functionality)
- [ ] Breaking change (fix or feature that would change existing functionality)
- [ ] Add new translation (feature adding new translations)

#### Checklist:

- [ ] Tested changes locally.
- [x] Closes currently open issue : Closes https://github.com/freeCodeCamp/freeCodeCamp/issues/13613

#### Description

Added more color values to regex to cover most of the common possibilities of the blue color.

### CODE REVIEW

**Comment by prateekgoel** [comment]
Yes, I missed to name the branch correctly. Will take care next time.

**Comment by raisedadead** [comment]
@prateekgoel can you confirm this was tested locally?

**Comment by prateekgoel** [comment]
@raisedadead I could not test this locally due to some issues. But I tested the regular expression against various inputs for color values using regex tester.
It would be great if you can test this locally.

**Comment by raisedadead** [comment]
Hi @prateekgoel thanks for the PR. 

We need all changes to be tested locally (especially when they are touching seed files). I understand that you had issues with the setup earlier?

If that is still the case please reach out to [Contributors Chat room](https://gitter.im/FreeCodeCamp/Contributors), and we will be glad to assist you there.

**Comment by raisedadead** [comment]
@prateekgoel please reach us in the chat room to get your setup issues sorted and re-open when ready.

Thanks a lot for your contribution. Happy fixing.

**Pull request closed without merging**
