### PR TITLE
chore(i18n,docs): processed translations

### PR DESCRIPTION
**Pull request by camperbot**
This PR was opened auto-magically by Crowdin.

### CODE REVIEW

**Review by sidemt — APPROVED** [review]
LGTM

**Review by ShaunSHamilton — CHANGES_REQUESTED** [review]
@nhcarrigan Should we be concerned with all these changes (re-uploads?) considering the recent move in Action?

**Comment by nhcarrigan** [comment]
@ShaunSHamilton These are all `chinese-traditional`, which is an automatic conversion from the Simplified Chinese that's pulled down from Crowdin. It wasn't running on the docs prior to the migration, so this is a one-time thing. We shouldn't see this many files (unless the Chinese team makes significant progress on the docs on Crowdin all at once).

**Review by majestic-owl448 — APPROVED** [review]

**Comment by raisedadead** [comment]
@ShaunSHamilton mind removing the restriction on the merge if you are happy with the confirmation?

**Review by ShaunSHamilton — APPROVED** [review]

**Pull request merged**
