### PR TITLE
fix(seed): Add missing bindings outside comment lines

### LINKED ISSUE #16554: [Beta] Comment on where to code is misplaced in React challenge
#### Challenge Name
React Write a Simple Counter

https://beta.freecodecamp.org/en/challenges/react/write-a-simple-counter

#### Issue Description

The default code tells you to define methods underneath the constructor. However, the default code doesn't include the explicit binding of these methods that need to go within the constructor. I'm not sure if the fix should be moving up the comment that says  "change code below this line" or if the challenge should already have the binding lines within the constructor. Once I know which solution would be better, I'd like to help make a PR to correct this.

#### Browser Information

* Browser Name, Version: Google Chrome, Version 63.0.3239.132 (Official Build) (64-bit)
* Operating System: Mac OS High Sierra 10.13.2
* Mobile, Desktop, or Tablet: Desktop

#### Your Code

Here is the successful challenge code.
```js
class Counter extends React.Component {
  constructor(props) {
    super(props);
    this.state = {
      count: 0
    };
    this.reset = this.reset.bind(this);
    this.increment = this.increment.bind(this);
    this.decrement = this.decrement.bind(this);
  }
  // change code below this line

  reset() {
    this.setState({ count: 0 });
  }
  
  increment() {
    this.setState({ count: (this.state.count + 1) })
  }
  
  decrement() {
    this.setState({ count: this.state.count - 1 })
  }
  // change code above this line
  render() {
    return (
      <div>
        <button className='inc' onClick={this.increment}>Increment!</button>
        <button className='dec' onClick={this.decrement}>Decrement!</button>
        <button className='reset' onClick={this.reset}>Reset</button>
        <h1>Current Count: {this.state.count}</h1>
      </div>
    );
  }
};

```
#### Screenshot

screen shot 2018-01-22 at 10 06 00 am

### PR DESCRIPTION
**Pull request by bqnguyen94**
#### Pre-Submission Checklist

- [x] Your pull request targets the `staging` branch of freeCodeCamp.
- [x] Branch starts with either `fix/`, `feature/`, or `translate/` (e.g. `fix/signin-issue`)
- [x] You have only one commit (if not, [squash](http://forum.freecodecamp.org/t/how-to-squash-multiple-commits-into-one-with-git/13231) them into one commit).
- [x] All new and existing tests pass the command `npm test`. Use `git commit --amend` to amend any fixes.

#### Type of Change

- [x] Small bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds new functionality)
- [ ] Breaking change (fix or feature that would change existing functionality)
- [ ] Add new translation (feature adding new translations)

#### Checklist:

- [x] Tested changes locally.
- [x] Addressed currently open issue (replace XXXXX with an issue no in next line)

Closes #16554

#### Description

Add explicit bindings to constructor method so that users only have to add code in between the comment lines.

### CODE REVIEW

**Review by no-stack-dub-sack — CHANGES_REQUESTED** [review]
Hi @bqnguyen94, this code looks good, but I think a better approach will be to have the camper do this themselves. We teach this concept [here](https://beta.freecodecamp.org/en/challenges/react/bind-this-to-a-class-method), and since this challenge comes after, I think it will be good to reinforce this by having campers repeat this afterwards (as discussed [here](https://github.com/freeCodeCamp/freeCodeCamp/issues/16554#issuecomment-359653159)). 

Would you mind updating the PR? Instead of the bindings, we can just add comments to denote that code needs to be changed in the constructor. 

Maybe, if you think it's necessary, we can also add a note in the instructions telling campers "be sure you don't forget to bind these methods in the constructor!"

Thoughts?

Also, if you're up for it, the same issue is also present in [this](https://beta.freecodecamp.org/en/challenges/react/create-a-controlled-input) challenge. Would you want to make the changes there as well (can be done in the same PR)?

P.S. sorry for the delay!

**Comment by bqnguyen94** [comment]
@no-stack-dub-sack totally agree! I have instead added comments to the instructor so that users can add bindings there, for both challenges. Also, I have updated the instructions accordingly. Can you help me see if the instructions are appropriate?

**Comment by no-stack-dub-sack** [comment]
@bqnguyen94 Great! Sure on the instructions, maybe they should be:

> Also, remember to add the necessary bindings for the newly-created methods in the constructor.

and

> Last but not least, don't forget to add the necessary bindings in the constructor.

If you can make this last change and squash your commits when your done that would be awesome! Thanks for your help!

**Comment by bqnguyen94** [comment]
@no-stack-dub-sack I ended up doing hard reset to before merging from staging and making the changes again. Do you know of any way to squash branch commits without squashing the merge commit?

**Comment by no-stack-dub-sack** [comment]
@bqnguyen94 when I need to squash the commits on my local branch, I always use `git rebase -i HEAD~<numCommits>`, if the commits have already been pushed to your local branch, you can use the `-f` flag when you push for force the update. If I need to merge upstream changes from staging into my local branch to make the branches even before pushing, I use `git pull --rebase upstream staging`, and as long as no conflicts have been merged upstream, the changes will be successfully merged to your local branch. Does this help / answer your question?

**Comment by bqnguyen94** [comment]
@no-stack-dub-sack Ah I see. I will remember this next time. Thanks! :)

**Comment by no-stack-dub-sack** [comment]
This LGTM! Thanks @bqnguyen94!

**Review by no-stack-dub-sack — APPROVED** [review]

**Pull request merged**
