### PR TITLE
fix(curriculum): colored markers  - clarify meta tag description

### LINKED ISSUE #47266: Learn-css-colors-by-building-a-set-of-colored-markers - Step 5
### Describe the Issue

For more clarity, can we specify to the user to add a **_NEW_** `meta` element in Step 5 as one already exists (added in step 4)?

Also, explain the reason why we are adding a new `meta` when some might think of adding attributes to the existing one.

- **Exactly one of the `name`, `http-equiv`, and `charset` attributes must be specified for a single meta element.**

### Affected Page

https://www.freecodecamp.org/learn/2022/responsive-web-design/learn-css-colors-by-building-a-set-of-colored-markers/step-5

### Your code

Nest a self-closing meta element within the head. Give it a name attribute set to viewport and a content attribute set to width=device-width, initial-scale=1.0.

```
<meta charset="utf-8" name="viewport" content="width=device-width, initial-scale=1.0"/>
```

### Expected behavior

Nest another self-closing meta element within the head. Give it a name attribute set to viewport and a content attribute set to width=device-width, initial-scale=1.0.

```
<meta charset="utf-8"/>
<meta name="viewport" content="width=device-width, initial-scale=1.0"/>
```

### Screenshots

_No response_

### System

- Device: [e.g. iPhone 6, Laptop]
- OS: [e.g. iOS 14, Windows 10, Ubuntu 20.04]
- Browser: [e.g. Chrome, Safari]
- Version: [e.g. 22]

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by SoumyadebMisra**
Checklist:

- [x] I have read [freeCodeCamp's contribution guidelines](https://contribute.freecodecamp.org).
- [x] My pull request has a descriptive title (not a vague title like `Update index.md`)
- [x] My pull request targets the `main` branch of freeCodeCamp.
- [x] I have tested these changes either locally on my machine, or GitPod.

Closes #47266 

Specified that a 'new' `meta` tag is to be added and added the reason for doing so.

### CODE REVIEW

**Comment by ShaunSHamilton** [comment]
Thank you for taking the time to contribute.

Please familiarise yourself with our [Contributor Docs](https://contribute.freecodecamp.org/#/how-to-open-a-pull-request) on how to open a PR. We accept PRs for issues with the `help wanted` or `first timers only` labels.

**Comment by SoumyadebMisra** [comment]
> Thank you for taking the time to contribute.
> 
> Please familiarise yourself with our [Contributor Docs](https://contribute.freecodecamp.org/#/how-to-open-a-pull-request) on how to open a PR. We accept PRs for issues with the `help wanted` or `first timers only` labels.

Thank you. Will familarise myself with the contributor docs.

**Review by hanswang123456 — COMMENTED** [review]
The actual content looks good. Remember to follow PR titling guidelines.

**Comment by hanswang123456** [comment]
image

**Review by Sembauke — DISMISSED** [review]

**Review by moT01 — CHANGES_REQUESTED** [review]
We want to keep the instructions as short as possible. This sounds repetitive to me...
>add a new `<meta>` tag with `name` attribute set to `viewport`
>Nest a new self-closing `meta` element within the `head`. Give it a `name` attribute set to `viewport`

I don't think we need to mention the reason for needing a second tag. I would just go with something like this:

> Finally, use a `viewport` `<meta>` tag to make sure your page looks the same on all devices.
> Nest a second, self-closing, `meta` element within the `head`. Give it a `name` attribute set to `viewport` and a `content` attribute set to `width=device-width, initial-scale=1.0`.

My preference and opinion anyway.

**Comment by moT01** [comment]
This has been sitting for a little while - I gave it an update to use my suggestion in the issue.

**Review by moT01 — APPROVED** [review]

**Review by Sembauke — APPROVED** [review]

**Pull request merged**
