### PR TITLE
Made a minor adjustment in instruction 

### PR DESCRIPTION
**Pull request by pkshreeman**
Preventing confusion regards to variable use of item and the instruction use of the word.  Revised the instruction to clarify the elements inside the array to be used, instead of variable named item.

### CODE REVIEW

**Comment by SaintPeter** [comment]
This looks good.  Can you please squash your commits?

**Comment by ltegman** [comment]
I think we need to pick which way we go with this wording. `item at the front of the queue` and `first element of the array` both describe the same thing. This PR has a mashup of both wordings rather than just one.

**Comment by pkshreeman** [comment]
@ltegman I am open to rewording, however the original instruction had me assuming that it wanted the item (variable) to be pushed to the array (correct assumption here), then it stated "then remove and return the item at the front of the queue."  I erroneously assume that the "item" in that instruction was in reference to the variable item hence same "value", not a general reference of the elements in the array.  Took me a long while to figure out that the item in instruction was not part of the variable item in that second part.

I respectfully disagree that it is a "same thing"..when you put front of queue, you are essentially (at least in this part of instruction) putting a value in front of function called queue, which also use another variable called arr (array).  This array is intergral part of the function, but is not the array itself.  When I finally passed, my understanding is that you put the item (variable in the function) in end of the array, remove the first element of the array, and return that value.

**Comment by ltegman** [comment]
I'd suggest either `Add the item onto the end of the array, then remove and return the element at the front of the queue.` or `Add the item onto the end of the array, then remove and return the first element of the array.`, whichever seems more clear to you.

**Comment by pkshreeman** [comment]
@SaintPeter   Squashed 'em...
@ltegman   Agreed! :)

**Comment by SaintPeter** [comment]
Thanks!

**Pull request merged**
