### PR TITLE
fix(client): set fcc-sound value in local storage

### LINKED ISSUE #46372: Campfire Mode doesn't trigger on multiple browsers unless you turn it on and off
### Describe the Issue

Campfire Mode was not playing on my account. I did find a fix, but still wanted to report! Please note it could be affecting more than one page, but I only tested on the new responsive web design! 

### Affected Page

https://www.freecodecamp.org/learn/2022/responsive-web-design/

### Steps to Reproduce

1. I'm logged in on my computer 
2. Under settings, Campfire Mode is enabled. 
3. My volume is turned up!
4. I go to the (New) Responsive Web Design course
5. The serenade of the Guitar does not play as I type or click on items :(

### Expected behavior

1. I'm logged in on my computer 
2. Under settings, Campfire Mode is enabled. 
3. My volume is turned up!
4. I go to the (New) Responsive Web Design course
5. The serenade of the Guitar plays!

### Screenshots

_No response_

### System

- Mac OS Big Sur 11.6.5 running Safari
- Windows 10 running Google Chrome 

### Additional context

I found a fix while poking around! 

1. I go to my settings and turn off and on Campfire mode.
2. The serenade of the Guitar DOES play as I type and click on items :)

### PR DESCRIPTION
**Pull request by nayabatir1**
Checklist:

- [x] I have read [freeCodeCamp's contribution guidelines](https://contribute.freecodecamp.org).
- [x] My pull request has a descriptive title (not a vague title like `Update index.md`)
- [x] My pull request targets the `main` branch of freeCodeCamp.
- [x] I have tested these changes either locally on my machine, or GitPod.

Closes #46372 

I've to close PR [#48106](https://github.com/freeCodeCamp/freeCodeCamp/pull/48106) due to merge conflict. Merging main branch results in more 10K file changes.

### CODE REVIEW

**Comment by moT01** [comment]
This is ready for review I presume @nayabatir1?

**Comment by nayabatir1** [comment]
> This is ready for review I presume @nayabatir1?

Not yet.
Certification timeline test is pending 
Facing some issue mocking api call. Hopefull will finish it soon and mark it for need review.

**Comment by nayabatir1** [comment]
@moT01 my bad this is PR is ready for review
I confused it with other PR, I replied from my mobile notification didn't realized which PR you were referring to.

**Comment by raisedadead** [comment]
We are officially on Node.js 18 now. We have changed the merge requirements accordingly.

You will need to rebase this PR against the main branch OR Click the "Update branch" button to get the new checks going.

Thanks for your contribution.

**Review by moT01 — APPROVED** [review]
This LGTM @nayabatir1 🎉

I think we should be good to merge this to fix the problem - but we may want to leave the issue open (or just create a new one) since it mentions that we want to move away from local storage completely if I'm reading it right.

**Comment by nayabatir1** [comment]
@moT01 this PR is focused on setting sound value in local storage.
If we want to move away from local storage creating a separate issue will be preferred approach. Tackling on issue at a time.

**Review by raisedadead — APPROVED** [review]

**Pull request merged**
