### PR TITLE
fix: typo issue in Iterate Over All Properties

### LINKED ISSUE #18243: "Object Oriented Programming: Iterate Over All Properties": description formatting typo
#### Describe your problem and - if possible - how to reproduce it
In the "Object Oriented Programming: Iterate Over All Properties" challenge, there is the following text in the description:

>Here is how you add <code>duck’s</code> <code>own</code> properties to the array <code>ownProps</code> and <code>prototype</code> properties to the array <code>prototypeProps</code>:

"<code>duck’s</code>" should probably be "<code>duck</code>’s".

#### Add a Link to the page with the problem
https://learn.freecodecamp.org/javascript-algorithms-and-data-structures/object-oriented-programming/iterate-over-all-properties

#### If possible, add a screenshot here
image

### PR DESCRIPTION
**Pull request by lauren-van-sloun**
#### Pre-Submission Checklist

- [ ] Your pull request targets the `staging` branch of freeCodeCamp. (next?)
- [x] Branch starts with either `fix/`, `feature/`, or `translate/` (e.g. `fix/signin-issue`)
- [x] You have only one commit (if not, [squash](http://forum.freecodecamp.org/t/how-to-squash-multiple-commits-into-one-with-git/13231) them into one commit).
- [x] All new and existing tests pass the command `npm test`. Use `git commit --amend` to amend any fixes.

#### Type of Change
- [x] Small bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds new functionality)
- [ ] Breaking change (fix or feature that would change existing functionality)
- [ ] Add new translation (feature adding new translations)

#### Checklist:
- [x] Tested changes locally.
- [x] Addressed currently open issue

Closes #18243 

#### Description
Corrected duck typo as described in [issue #18243](https://github.com/freeCodeCamp/freeCodeCamp/issues/18243)

### CODE REVIEW

**Review by Nirajn2311 — APPROVED** [review]
LGTM 👍 👍

**Comment by Bouncey** [comment]
@Ashera138 could you please rebase this PR with the `next` branch, it seems the file has changed since you made your PR.

Thanks for taking the time to fix this 👍

**Comment by raisedadead** [comment]
@Ashera138 the file has now moved to a `.md`. 

You can find it here: 

https://github.com/freeCodeCamp/freeCodeCamp/blob/next/curriculum/challenges/english/02-javascript-algorithms-and-data-structures/object-oriented-programming/iterate-over-all-properties.english.md

I am closing this PR. Can you instead make a fresh PR. 

Thanks a lot for taking the time to prepare this.

**Comment by Ashera138** [comment]
@raisedadead, Sure thing, thanks for providing the link. I'll get a fresh PR submitted soon. :)

**Comment by Ashera138** [comment]
[Here's the new PR.](https://github.com/freeCodeCamp/freeCodeCamp/pull/18287)

**Pull request closed without merging**
