### PR TITLE
Fix doctype regex in various RWD beta challenges

### LINKED ISSUE #44626: RWD Beta: Test that requires DOCTYPE to be on its own line is failing
## Affected page

Several. One example is [Learn HTML Forms by Building a Registration Form / Step 2](https://www.freecodecamp.org/learn/2022/responsive-web-design/learn-html-forms-by-building-a-registration-form/step-2)

## Your code

```
<!DOCTYPE html><html></html>
```

## Expected behavior

The hint for this step seems to indicate that the user must add the `html` element below the `DOCTYPE` (there must be at least one new line separating them).

Hint: "Your `html` element should be below the `DOCTYPE` declaration.:"

So the expected behavior would be that the user will not pass this step until they add the `html` element below the `DOCTYPE`.

## System

- Device: Desktop
- OS: Linux/Fedora 34
- Browser: Firefox
- Version: [e.g. 22]

## Additional context

This is happening for several courses. The regex used for this test is not enforcing the newline between the elements. If this requirement is important enough to be enforced then we should probably come up with one regex that enforces this requirement and use it for all courses.

### PR DESCRIPTION
**Pull request by xoxoKaralee**
Checklist:

- [x] I have read [freeCodeCamp's contribution guidelines](https://contribute.freecodecamp.org).
- [x] My pull request has a descriptive title (not a vague title like `Update index.md`)
- [x] My pull request targets the `main` branch of freeCodeCamp.
- [x] I have tested these changes either locally on my machine, or GitPod. **tested in GitPod on Safari

Closes #44626

Used @bbsmooth's regex/code `assert(code.match(/\s*<!DOCTYPE\s+html\s*>(\r?\n)+<\s*html\s*>/gi));` and updated the pages in RWD beta that contained the code for `Your `html` element should be below the `DOCTYPE` declaration.`

Pages changed: 
Build a Set of Colored Markers - Step 1
Build a Photo Gallery - Step 1
Build a Magazine - Step 1
Build a City Skyline - Step 2
Build a Registration Form - Step 2
Build a Picasso Painting - Step 1
Build a Piano - Step 1

Camper Cafe Menu and Cat Photo App dont have this specific check but have similar instruction wording to the other Challenges. Is this intentionally omitted? Should this check be included?

### CODE REVIEW

**Comment by bbsmooth** [comment]
> Camper Cafe Menu and Cat Photo App dont have this specific check but have similar instruction wording to the other Challenges. Is this intentionally omitted? Should this check be included?

For consistency's sake I would say yes, this check should be included for those two as well.

**Comment by xoxoKaralee** [comment]
@bbsmooth  Sorry, I think I meant the Hints (not checks). I'm not sure how to do the fancy linking code thing, but the the place that teaches about DOCTYPE is (last step) [Step 67 of Cat Photo App.](https://github.com/freeCodeCamp/freeCodeCamp/blob/main/curriculum/challenges/english/14-responsive-web-design-22/learn-html-by-building-a-cat-photo-app/step-067.md) I dont think it'd actually needs an update here, just worth mentioning in case anything needs to be clarified in how DOCTYPE is introduced. If we want to add in just that doctype above html regex we can, but all of  [Camper Cafe's Step 1 Hints](https://github.com/freeCodeCamp/freeCodeCamp/blob/main/curriculum/challenges/english/14-responsive-web-design-22/learn-basic-css-by-building-a-cafe-menu/step-001.md) could stand to be improved to look like [Colored Marker's Step 1 Hints](https://github.com/freeCodeCamp/freeCodeCamp/blob/main/curriculum/challenges/english/14-responsive-web-design-22/learn-css-colors-by-building-a-set-of-colored-markers/step-001.md)

**Comment by bbsmooth** [comment]
You know, after looking into this some more, I'm not sure we aren't trying to enforce a rule that isn't actually required. I'm not finding anything that says it is required that the doctype be on a line of its own. It does have to be the first thing on the page (aside from comments) but from what I can tell, the html element is allowed to follow it on the same line. The W3C html validator is letting me put all of my html on one continuous line, and the googles have not turned up anything yet that says this is required.

I understand that nicely formatted HTML is easier to work with and perhaps that's what this requirement is designed to enforce. But I'm noticing that this formatting requirement isn't being enforced in other places. For example, I can submit the following HTML in the [photo gallery course for step 1](https://www.freecodecamp.org/learn/2022/responsive-web-design/learn-css-flexbox-by-building-a-photo-gallery/step-1) and it will be accepted:

```
<!DOCTYPE html>
<html><head></head><body></body></html>
```

So I'm wondering if we shouldn't get rid of this separate line requirement for the doctype and rather just check that it is the first element on the page?

**Comment by xoxoKaralee** [comment]
I wasnt a fan of having it be on a new line anyways. So the question is, where do we go from here? I believe the last regex also enforced a new line (or at least i seem to remember being told to put it on a new line at some point).

**Comment by cronlabspl** [comment]
> I wasnt a fan of having it be on a new line anyways. 

@xoxoKaralee why not? Seems logical.

**Review by cronlabspl — CHANGES_REQUESTED** [review]
`DOCTYPE` **not needed** here at all.

**Comment by xoxoKaralee** [comment]
@cronlabspl i mean, as @bbsmooth mentioned, "nice formatting" is nice, but not required and not enforced in other places. I also got it wrong the first time because I was speeding through and didnt put it on a different line. I don't think my opinion matters *THAT* much about it one way or the other though.  

Also, you requested changes "DOCTYPE not needed here at all", would you mind clarifying what you are wanting changed?

**Comment by bbsmooth** [comment]
> where do we go from here?

Should probably take this discussion back to the original [issue](https://github.com/freeCodeCamp/freeCodeCamp/issues/44626).

**Comment by moT01** [comment]
Our general rule is to try and make it so all valid code will pass, unless something specific is mentioned about the formatting. In this case, it does say "below". I vote to just change all those to "after" and allow the tags to be on whatever line works.

**Comment by ahmadabdolsaheb** [comment]
I agree with Bruce about taking the discussion back to the original issue.

**Comment by xoxoKaralee** [comment]
Closing this Pull request since other PR's have taken over.

**Pull request closed without merging**
