### PR TITLE
fix(curriculum): switch Ferris Wheel and Penguin projects

### LINKED ISSUE #45985: Ferris wheel and Penguin project should be switched in the curriculum order
### Describe the Issue

There was a discussion on the [forum here ](https://forum.freecodecamp.org/t/responsive-web-design-updates/508345/71?u=jwilkins.oboe) regarding the penguin project. The user brought up that the animation elements were taught in the ferris wheel project which is currently after the penguin project in the curriculum. This user had some trouble completing the project because of this order. 

Also the [last step of the penguin project](https://www.freecodecamp.org/learn/2022/responsive-web-design/learn-css-transforms-by-building-a-penguin/step-104) congratulates the user on completing the course, even though there is a whole other practice project left in the curriculum. 
Screen Shot 2022-05-15 at 11 45 09 PM

Were these two projects originally swapped in the beta version? 
Should they be swapped back so the Ferris Wheel comes before the penguin project?

### Affected Page

https://www.freecodecamp.org/learn/2022/responsive-web-design/learn-css-transforms-by-building-a-penguin/step-104

### PR DESCRIPTION
**Pull request by majestic-owl448**
Checklist:

- [x] I have read [freeCodeCamp's contribution guidelines](https://contribute.freecodecamp.org).
- [x] My pull request has a descriptive title (not a vague title like `Update index.md`)
- [x] My pull request targets the `main` branch of freeCodeCamp.
- [x] I have tested these changes either locally on my machine, or GitPod.

Closes #45985

### CODE REVIEW

**Comment by ieahleen** [comment]
let's ignore the extra commits considering the squash&merge

**Comment by nhcarrigan** [comment]
Whoops - clicked the wrong button.

`git rebase` is your friend, but this should be good to go.

**Comment by nhcarrigan** [comment]
Whoops - clicked the wrong button.

`git rebase` is your friend, but this should be good to go.

**Review by naomi-lgbt — APPROVED** [review]

**Review by sidemt — APPROVED** [review]
LGTM

**Pull request merged**
