### PR TITLE
Fixing #3663 'array or numbers' should read 'array of numbers'

### PR DESCRIPTION
**Pull request by danielrob**

### CODE REVIEW

**Comment by bugron** [comment]
@danielrob thanks for the PR. Please remove issue number from the title and also from the commit message. Just a tip: you can overwrite your last commit by `git commit --amend` command.
Also read our [Guidelines for Contributing](https://github.com/FreeCodeCamp/FreeCodeCamp/blob/staging/CONTRIBUTING.md) and [Pull Request Contribute](https://github.com/FreeCodeCamp/FreeCodeCamp/wiki/Pull-Request-Contribute) and next time name your branches correctly, thanks.

**Comment by ahstro** [comment]
Why was this closed?

**Comment by danielrob** [comment]
It got closed automatically when I deleted the branch, which I mistakenly thought was necessary. https://github.com/FreeCodeCamp/FreeCodeCamp/pull/3677 supersedes this pull request.

**Comment by ahstro** [comment]
Oh, I see, thanks!

**Pull request closed without merging**
