### PR TITLE
feat: audit for data visualization projects

### PR DESCRIPTION
**Pull request by XuQuan-nikkkki**

### CODE REVIEW

**Comment by XuQuan-nikkkki** [comment]
@miyaliu666

**Comment by RandellDawson** [comment]
@XuQuan-nikkkki I noticed there are 10 files in this PR, but the [original issue]() mentioned 11 files.  Did  the change in the English file for `visualize-data-with-a-bar-chart.md` not need a translation?  I would assume that all of these projects' changed, due to some formatting changes we made on all of them.  If not, that is fine.

@miyaliu666 Can you review the changes in this PR?

**Comment by XuQuan-nikkkki** [comment]
@RandellDawson @pjwok and I volunteered to audit these 11 files together. He said he has audited `visualize-data-with-a-bar-chart.md` and his PR has already merged. I only need to finish the rest 10 files, so there are only 10 files in this PR instead of 11.

**Comment by RandellDawson** [comment]
> He said he has audited visualize-data-with-a-bar-chart.md and his PR has already merged.

@XuQuan-nikkkki I do not see any merged PR that contains changes to this file.  Can you provide the PR number?  Thank you.

**Review by miyaliu666 — APPROVED** [review]
This is good to go now. We'll fix descriptions on Crowdin.

**Review by RandellDawson — APPROVED** [review]

**Comment by RandellDawson** [comment]
@XuQuan-nikkkki Thank you for your contribution.

**Pull request merged**
