### PR TITLE
Added a link to Babel to see JSX to HTML conversion in JSX Guide

### PR DESCRIPTION
**Pull request by johncgenere**
- [x] I have read [freeCodeCamp's contribution guidelines](https://github.com/freeCodeCamp/freeCodeCamp/blob/master/CONTRIBUTING.md).
- [x] My pull request has a descriptive title (not a vague title like `Update index.md`)
- [x] My pull request targets the `master` branch of freeCodeCamp.
- [x] None of my changes are plagiarized from another source without proper attribution.
- [x] All the files I changed are in the same world language (for example: only English changes, or only Chinese changes, etc.)
- [x] My changes do not use shortened URLs or affiliate links.

### CODE REVIEW

**Comment by johncgenere** [comment]
I am not sure why there are multiple file changes, I only made the change to the JSX index.md file on my local machine. If need be I can close and create another pull request.

**Comment by scissorsneedfoodtoo** [comment]
@johncgenere, thanks for taking the time to submit this PR! Sorry you're having trouble.

Did you use `git add .` to add the file you changed? If so, that command adds all files that were changed, which can include package.json and package-lock.json. A safer bet is to enter the path of the file with your changes: `git add guide/english/react/jsx/index.md`.

Hope that helps! Please let us know if you have any problems with your next PR.

**Comment by johncgenere** [comment]
@scissorsneedfoodtoo, yes that is exactly what I did! I opened another pull request using the path of the file and it worked perfectly. Thank you!

**Comment by RandellDawson** [comment]
@johncgenere I assume when you ran the `npm install` it added those two extra package-related files.  You can also just check them out to revert the changes to them.  In general, unless you are adding a new package to the repo, you would not want to include changes to those package-related files.  Before using `git add .`, always run `git status`, to see what files are going to be included if you use the `add 
 ,` option.  If you see files like `package.json` and/or `package-lock.json`, you can simply do the following for those files, to revert any unstaged changes:
```
git checkout -- package.json
git checkout -- package-lock.json
```

**Pull request closed without merging**
