### PR TITLE
curriculum: Fix tests in Positive and Negative lookahead challenge for Regular Expressions

### PR DESCRIPTION
**Pull request by thecodingaviator**
- [x] I have read [freeCodeCamp's contribution guidelines](https://github.com/freeCodeCamp/freeCodeCamp/blob/master/CONTRIBUTING.md).
- [x] My pull request has a descriptive title (not a vague title like `Update index.md`)
- [x] My pull request targets the `master` branch of freeCodeCamp.
- [x] None of my changes are plagiarized from another source without proper attribution.
- [x] All the files I changed are in the same world language (for example: only English changes, or only Chinese changes, etc.)
- [x] My changes do not use shortened URLs or affiliate links.

Refer to the discussion on PR #34582 

The following incorrect case was passing, this PR fixes that
image

### CODE REVIEW

**Comment by thecodingaviator** [comment]
I've tested it locally:
image

image

**Comment by RandellDawson** [comment]
@thecodingaviator The current regex solution (seen below) is incorrect, because the following password should **not match** "36b3ez".
```
var pwRegex = /(?=\w{6})(?=\D*\d{2})/;
```

Why?  Because it starts a digit and that is one of the challenge requirements ("do not begin with numbers") in the instructions.

Since this PR is about fixing the tests and the last PR #34582 was supposed to "fix" the challenge and was merged without catching this issue, I am requesting we get this fixed once and for all on this PR.

**Comment by thecodingaviator** [comment]
I've added in a test to make sure the first character is not a number

**Comment by RandellDawson** [comment]
@thecodingaviator The solution is still wrong, because it still should **not match** any of the following:
```
36b3ez
395ezb
2783ez
36838z
783869
```

**Comment by thecodingaviator** [comment]
@RandellDawson I know. That's why I didn't remove the label. I'm not sure how that solution would be implemented

**Comment by RandellDawson** [comment]
This challenge has been broken since it was implemented.  I remember thinking the tests were wrong a long time ago, because the solutions campers were submitting and passing the tests were not actually following the instructions.  I will take a look at this in more detail when I get a chance.

**Comment by RandellDawson** [comment]
On second thought, let's close this PR and move the discussion to an issue.

**Comment by thecodingaviator** [comment]
That sounds fair enough

**Pull request closed without merging**
