### PR TITLE
added clarification in test text

### LINKED ISSUE #17490: Possible Clarification + Issue on Basic HTML and HTML5
#### Describe your problem and - if possible - how to reproduce it
Currently, the test text reads "The finished input element should have valid syntax."
I find this potentially confusing for a beginner to HTML because most of the block elements they would have seen are not self-closing. It may clarify to put another clause "Remember that input elements are self-closing" in the test text.

As an aside, the tests **do** pass if you add a closing input element tag. Not sure if this is intended...

#### Add a Link to the page with the problem
https://learn.freecodecamp.org/responsive-web-design/basic-html-and-html5/add-placeholder-text-to-a-text-field

#### Tell us about your browser and operating system

* Browser Name: Google Chrome
* Browser Version: Chrome 66
* Operating System: Windows NT 10.0

#### If possible, add a screenshot here
image

### PR DESCRIPTION
**Pull request by tannerabread**
fix to issue #17490

- [x] I have read [freeCodeCamp's contribution guidelines](https://github.com/freeCodeCamp/freeCodeCamp/blob/master/CONTRIBUTING.md).
- [x] My pull request has a descriptive title (not a vague title like `Update index.md`)
- [x] My pull request targets the `master` branch of freeCodeCamp.
- [x] None of my changes are plagiarized from another source without proper attribution.
- [x] My article does not contain shortened URLs or affiliate links.

If your pull request closes a GitHub issue, replace the XXXXX below with the issue number.

Closes #17490

### CODE REVIEW

**Comment by RandellDawson** [comment]
I am not convinced this extra text is needed.  I think we need this needs to be discussed further.  You should not have to add the closing / to the tag to be considered valid HTML5.  If the test is requiring the /, then we should look at changing the test instead of adding incorrect verbiage.

**Comment by bannon-tanner** [comment]
I agree with what you are saying. Correct me if I'm wrong though if I had <input attribute="value" > it would still be considered a self closing tag. So the test probably also needs to be changed but is the extra text wrong?

**Comment by RandellDawson** [comment]
@bannon-tanner 
> So the test probably also needs to be changed but is the extra text wrong?

It is not that it is wrong, it is just not needed in the test text.  Maybe in the challenge description?

**Comment by bannon-tanner** [comment]
@RandellDawson 
> It is not that it is wrong, it is just not needed in the test text. Maybe in the challenge description?

Alright you got it, I have changed it to be a note in the challenge description. I will also try to add the test to check that there is no </input> tag

**Comment by RandellDawson** [comment]
LGTM

**Review by RandellDawson — APPROVED** [review]

**Comment by nikrb** [comment]
@RandellDawson successfully tested locally

**Review by huyenltnguyen — DISMISSED** [review]
@bannon-tanner Thanks a lot for the PR!

I just pulled this down and tested locally. It looks good to me 👍 However, the issue reporter mentioned that the tests pass even for invalid code (adding the closing `</input>` tag). I'm wondering if you could update the test to make it a bit stricter?

**Comment by bannon-tanner** [comment]
Sorry for the delay guys, I'm willing to try to fix this issue adding the test to check for the closing tag. I do not know what syntax/test suite this is though to look up information to make sure I am writing it correctly. Any help would be appreciated

**Comment by RandellDawson** [comment]
@huyenltnguyen Since what you are proposing is a valid suggestion, but does not related to the issue this current PR aims to close, would you mind creating a new issue which describes the issue and maybe some suggestions for how best to approach the test changes?

**Comment by RandellDawson** [comment]
@bannon-tanner, @huyenltnguyen Since we did not hear back from you, I created a new issue (#35543) related to what you mentioned on this PR, since the PR actually resolved the original issue for which it was originally created.

**Review by thecodingaviator — APPROVED** [review]
LGTM! 👍

**Comment by thecodingaviator** [comment]
@bannon-tanner Thank you for your contribution to the page! 👍
We're happy to accept these changes, and look forward to future contributions. 📝

**Pull request merged**
