### PR TITLE
Fixed typo issue #11404

### LINKED ISSUE #11404: Fix jsx typo in map header
[autocompleted](https://github.com/FreeCodeCamp/FreeCodeCamp/blob/staging/common/app/routes/challenges/components/map/Header.jsx#L100) here is misspelled and should be campelCase to conform with jsx property naming conventions.

This fixes a React warning in development.

autocompleted => autoComplete

### PR DESCRIPTION
**Pull request by yarwest**
#### Pre-Submission Checklist

- [x] Your pull request targets the `staging` branch of FreeCodeCamp.
- [x] Branch starts with either `fix/`, `feature/`, or `translate/` (e.g. `fix/signin-issue`)
- [x] You have only one commit (if not, [squash](http://forum.freecodecamp.com/t/how-to-squash-multiple-commits-into-one-with-git/13231) them into one commit).
- [ ] All new and existing tests pass the command `npm run test-challenges`. Use `git commit --amend` to amend any fixes.
#### Type of Change

- [x] Small bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds new functionality)
- [ ] Breaking change (fix or feature that would change existing functionality)
- [ ] Add new translation (feature adding new translations)
#### Checklist:

- [ ] Tested changes locally.
- [x] Closes currently open issue (replace XXXX with an issue no): Closes #11404 
#### Description

Fixed the typo

### CODE REVIEW

**Comment by BerkeleyTrue** [comment]
> Please, review our Guidelines for Contributing, thank you!.

**Comment by raisedadead** [comment]
Ummn, they have since deleted the repo. Can we close this?

**Comment by atjonathan** [comment]
@raisedadead :+1:
@yarwest, if you are still interested in contributing, please do not delete your fork while a PR is open.

**Comment by yarwest** [comment]
@atjonathan woops, didnt delete it on purpose :p sorry

**Pull request closed without merging**
