### PR TITLE
fix(client): typo intro.json

### LINKED ISSUE #43283: Typo in Basic Node and Express introduction
This issue was brought up on the forum.
https://forum.freecodecamp.org/t/incomplete-typo-on-description-text-in-basic-node-and/473859

## Affected page

https://www.freecodecamp.org/learn/apis-and-microservices/#basic-node-and-express

## Paragraph with typo and incomplete sentence 
The third paragraph second sentence needs to be rewritten. 

Express makes it much easier to create a server and handle routing the routing for your application, which handles things like direct people to the correct page when they visit a certain endpoint like

## Proposed change
Express makes it much easier to create a server and handle routing for your application, which handles things like direct people to the correct page when they visit a certain endpoint.

## Screenshots

Screen Shot 2021-08-23 at 10 00 07 PM

### PR DESCRIPTION
**Pull request by munib-ahmad**
- fix: typo in intro.json
Closes: #43283

### CODE REVIEW

**Review by naomi-lgbt — APPROVED** [review]
Thanks for catching this

**Comment by ieahleen** [comment]
This does not close the linked issue, can you remove the linking to the issue, or add the fix for that issue to this PR?

**Review by majestic-owl448 — CHANGES_REQUESTED** [review]
This does not close the linked issue, can you remove the linking to the issue, or add the fix for that issue to this PR?

**Review by majestic-owl448 — APPROVED** [review]
Sorry, it's actually fine 👍

**Comment by ieahleen** [comment]
Hi @muneeb-121 . Congrats on your first pull request (PR)! 🎉

Thank you for your contribution to the page! 👍
We are happy to accept these changes and look forward to future contributions. 📝

**Pull request merged**
