### PR TITLE
Update how-to-work-on-coding-challenges.md

### PR DESCRIPTION
**Pull request by tjjohny**
- [ ] I have read [freeCodeCamp's contribution guidelines](https://github.com/freeCodeCamp/freeCodeCamp/blob/master/CONTRIBUTING.md).
- [ ] My pull request has a descriptive title (not a vague title like `Update index.md`)
- [ ] My pull request targets the `master` branch of freeCodeCamp.
- [ ] None of my changes are plagiarized from another source without proper attribution.
- [ ] My article does not contain shortened URLs or affiliate links.

If your pull request closes a GitHub issue, replace the XXXXX below with the issue number.

Closes #XXXXX

### CODE REVIEW

**Comment by lynxlynxlynx** [comment]
Seems pointless, but at least also fix item 1 in case others will disagree.

**Comment by RandellDawson** [comment]
Closed and Reopened this PR to attempt to resolve a specific Travis build failure.

**Comment by Nirajn2311** [comment]
@tjjohny Any updates?
@RandellDawson Also can we close this PR as there has been no updates for two months?

**Comment by lynxlynxlynx** [comment]
Yes, it is a low effort change of questionable value.

**Pull request closed without merging**
