### PR TITLE
fix: stop creating config before starting client

### PR DESCRIPTION
**Pull request by ojeytonwilliams**
Checklist:

- [x] I have read and followed the [contribution guidelines](https://contribute.freecodecamp.org).
- [x] I have read and followed the [how to open a pull request guide](https://contribute.freecodecamp.org/#/how-to-open-a-pull-request).
- [x] My pull request targets the `main` branch of freeCodeCamp.
- [x] I have tested these changes either locally on my machine, or GitPod.

### CODE REVIEW

**Review by moT01 — APPROVED** [review]
LGTM :tada:

**Review by ShaunSHamilton — COMMENTED** [review]
Doesn't this shoot us in the foot when it comes time to deploy, and we forget to run `create:config`?

**Comment by ojeytonwilliams** [comment]
> Doesn't this shoot us in the foot when it comes time to deploy, and we forget to run `create:config`?

Nope, that's taken care of by prebuild.

**Review by ShaunSHamilton — APPROVED** [review]
I missed the `prebuild` :thumbsup:

**Pull request merged**
