### PR TITLE
fix: fixed styling for modal headers (className fcc-modal)

### LINKED ISSUE #35213: Modal header styling is incorrect
The header of our modals have no background colour. They should have a background-color of `#006400`

image

### PR DESCRIPTION
**Pull request by ghost**
- [x] I have read [freeCodeCamp's contribution guidelines](https://github.com/freeCodeCamp/freeCodeCamp/blob/master/CONTRIBUTING.md).
- [x] My pull request has a descriptive title (not a vague title like `Update index.md`)
- [x] My pull request targets the `master` branch of freeCodeCamp.
- [x] None of my changes are plagiarized from another source without proper attribution.
- [x] All the files I changed are in the same world language (for example: only English changes, or only Chinese changes, etc.)
- [x] My changes do not use shortened URLs or affiliate links.

Closes #35213

### CODE REVIEW

**Comment by alan-nguy** [comment]
This PR is for https://github.com/freeCodeCamp/freeCodeCamp/issues/35213

**Comment by RandellDawson** [comment]
@alan-nguy I have updated your PR body.  When you create a PR which you think will close an existing issue, please put `Closes #IssueNumber` in the body.  That way, if the PR gets merged, the issue will auto-close.

Thank you.

**Comment by raisedadead** [comment]
Can we have some screenshots for the result? Both in normal and night modes?

**Comment by alan-nguy** [comment]
@RandellDawson thnx for the tip! Will keep in mind for next issue.

**Comment by alan-nguy** [comment]
@raisedadead  There you go!
night-mode
light-mode

**Comment by Nirajn2311** [comment]
@raisedadead @RandellDawson Shouldn't the styling be there also for the `Ask for Help` and `Watch a video` modal just like in freecodecamp.org

**Comment by raisedadead** [comment]
@Nirajn2311 possibly in a separate PR?

**Comment by raisedadead** [comment]
@alan-nguy Thanks.

**Comment by alan-nguy** [comment]
@Nirajn2311 @raisedadead  The styling do apply for the help and watch a video modals in light mode. But in night mode, the styling for those components do get overridden by a dark gray colour.

I've checked in production, in night mode the help and watch-a-video modal header background is dark green and the body is white but in the master branch, they are dark gray. Those changes seems to be applied recently. 

Do we want a green background in the modal header and white background in the body in night mode or all dark gray? I'll be happy to make the changes once i get a confirmation.

**Comment by raisedadead** [comment]
> Do we want a green background in the modal header and white background in the body in night mode or all dark gray?

I guess, it should be all dark gray

**Comment by DzmitryUr** [comment]
@alan-nguy @RandellDawson @raisedadead  `.fcc-modal` is a global class and used for several modals, but styles are placed for the class in `.css` file for specific component. Probably it would be better to place CSS rules for global class `.fcc-modal` in `.css` file somewhere above for global classes?

**Comment by alan-nguy** [comment]
I agree with @DzmitryUr that the styling for .fcc-modal should be placed in a file that touches several components. I have moved the code to a global.css file.

I also added a minor css fix for night mode in the success completion modal. Attached are the styling results as per previous discussion
night-mode
light-mode

**Comment by moT01** [comment]
Visually, this all LGTM! Green headers for all popups on regular mode, and dark grey for night mode - just like the pictures. I checked, and there are no other earlier PR's that affect these files. As far as where the code should belong, I'm not sure where is best.

**Comment by RandellDawson** [comment]
I like the look of what I see, but will defer to @raisedadead if using these particular CSS file is the ideal approach.

**Review by raisedadead — APPROVED** [review]

**Comment by raisedadead** [comment]
#### :sparkles: :sparkles: **AWESOME!.** :sparkles: :sparkles: 

Thanks @alan-nguy, for this pull request and contributing to the code-base for the first time.
We will be looking forward for more contributions in future.

Cheers and happy contributing!

**Pull request merged**
