### PR TITLE
fix: remove portfolio and render map intro conditionally

### LINKED ISSUE #37369: Show a skeleton loaders on the the `/learn` page
Show a skeleton loader on the sign in button instead of the full page loader on the learn application:

image

This should let users see the page faster than waiting for the sync.

The other things that can be a skeleton are the welcome message

### PR DESCRIPTION
**Pull request by ahmaxed**
Closes #37369

### CODE REVIEW

**Comment by raisedadead** [comment]
We should probably keep the quote on the signed in view.

**Review by raisedadead — COMMENTED** [review]
Lets also add the sign out button on their portfolio page too. Its going to be way too deeply nested otherwise.

**Comment by ahmadabdolsaheb** [comment]
@raisedadead great ideas.

**Comment by ahmadabdolsaheb** [comment]
@QuincyLarson, @raisedadead 

There are two versions of /learn intro for signed and unsigned users.

How about allocating let’s say %70 percent of the view to the conditional into and try to fit both versions in that real-estate. 

That would help us avoid adding animation or page jump when conditional intro renders after the loader.

How a about doing the following:

- using smaller font for the welcome page and fitting “Learn to code. Build projects. Earn certifications.”  in one line the same way we fit the company names in a row for the unsigned users.

- Showing the quote and settings and portfolio and/or sign-out buttons for signed in users (to reduce user journey.)

thoughts?

**Comment by ahmadabdolsaheb** [comment]
I discussed this with Quincy, we will be sticking to the previous plan and iterate after shipping this if necessary.

**Comment by ahmadabdolsaheb** [comment]
we could add the following copy to the signed in intro.

You have completed N out of N lessons.
You have built N out of N certification projects.
[to add later] You donations have provided N hours of free education for people around the world. (Update your donation)

**Pull request merged**
