### PR TITLE
feat: process video question md into html

### PR DESCRIPTION
**Pull request by ojeytonwilliams**
The generated html is wrapped in unwanted `<p>` tags, but `SanitizedSpan` removes those anyway, so I think that's fine.

Here's some yaml to help with QA:
````
```yml
question:
  text: | 
    Some code:
    ```js
    var x = 'y';
    ```
    some `inline code` and *italics*
    escaped \*

    new paragraph's don't work.
    <br>
    <br>
    breaks do
  answers:
    - '*one*'
    - '**two**'
    - '`three`'
  solution: 3
```
````

so you can see what actually appears on the page.  Also, if we want paragraphs it's a trivial change to `SanitizedSpan`

### CODE REVIEW

**Review by moT01 — COMMENTED** [review]
Nice job @ojeytonwilliams. I think this looks pretty good. The only thing I saw missing is some styling on code blocks. The inline blocks are highlighted, code blocks aren't as far as I could tell.

It took me a little bit to figure out the structure this has to be. It's quite strict. Wondering if it's good to have it that strict or if we should try and make it more flexible?

It pretty much has too look exactly like this:
````
```yml
  question:
    text: |
      What will the following JavaScript code log to the console?

      ```js
      console.log('hello world');
      ```
    answers:
      - 'hello'
      - 'world' 
      - 'hello world' 
    solution: 3
```
````

For example, each child has to be indented one level, `text: |` has to look exactly like that with a space and pipe. I think I'm fine with that, it's probably for the better - I can make something for the docs that explains it.

**Comment by ojeytonwilliams** [comment]
> The only thing I saw missing is some styling on code blocks. The inline blocks are highlighted, code blocks aren't as far as I could tell.

Good catch.  The issue is that `SanitizedSpan` strips the classes and then does not use Prism to format it.  I was being overly paranoid when I made `SanitizedSpan` - we control the content that reaches it, so the sanitizing is not necessary.  I'll fix it.


> It took me a little bit to figure out the structure this has to be. It's quite strict. Wondering if it's good to have it that strict or if we should try and make it more flexible?

It's tricky.  Ultimately we have to encode the test/questions in some format, but YAML is quite fiddly to use.  I think providing examples in the docs would help, though, and we can certainly discuss moving away from YAML if there's a better alternative.

**Comment by ojeytonwilliams** [comment]
@moT01 I could not figure out how to stop the parser treating 
```md
single line of text
```
as a paragraph and generating html wrapped in `<p>` tags. This messed up the formatting, so I fixed it with css.

**Review by moT01 — APPROVED** [review]
Alright, this LGTM 🎉 

I think we wanted to wait to merge this until after tomorrow. Once it gets merged I, or someone, can update the docs to describe the structure these need to be. Then we can go and change all the questions to this format if we want. And maybe make some more tests after that if we want to enforce some of this.

**Comment by moT01** [comment]
Alright, I think I am going to merge this before conflicts show up.

**Comment by ojeytonwilliams** [comment]
You're welcome.  Were you planning on updating the docs or should I have a go?

**Comment by moT01** [comment]
Give it a go if you want. Do you think we should only explain the new syntax? or give people options of this and html. I think I would rather only explain this and try to keep things consistent, plus I think it's better.

**Pull request merged**
