### PR TITLE
doc - Update French README (add links, update translation)

### PR DESCRIPTION
**Pull request by tdimnet**
- [x] I have read [freeCodeCamp's contribution guidelines](https://github.com/freeCodeCamp/freeCodeCamp/blob/master/CONTRIBUTING.md).
- [x] My pull request has a descriptive title (not a vague title like `Update index.md`)
- [x] My pull request targets the `master` branch of freeCodeCamp.
- [x] None of my changes are plagiarized from another source without proper attribution.
- [x] All the files I changed are in the same world language (for example: only English changes, or only Chinese changes, etc.)
- [x] My changes do not use shortened URLs or affiliate links.

Hello there,

this is the first time I contribute on your project and I want to do it right 😄 .
I started working on the French README file and I would like to have your opinion before going on. I updated the french translation (some sentences were a bit strange) and I also added links.

If my work is OK for you, I will finish reviewing the README before helping on this English technical guides (I think I can help for the Sass and the Bootstrap Guide).

Thanks you.

### CODE REVIEW

**Comment by RandellDawson** [comment]
@tdimnet Thank you for  creating this PR.  However, since it was created, the underlying document has changed.  Can you please review and resolve the current merge conflicts?  It could be the changes to the underlying document are so significant that your changes are no longer relevant.  If the latter is the case, it might be easier to just close this PR and create a new PR with any changes you still feel are important to make.

If you need any assistance or have questions about resolving the merge conflicts, please reply back or contact someone in the [Contributors Room on Gitter](https://gitter.im/FreeCodeCamp/Contributors).

Thank you.

**Comment by tdimnet** [comment]
@RandellDawson : thank you for your reply.
I am going to fix the conflicts either today or tomorrow and I will "up" you once it's done.

By the way: is it a good thing to contribute on the french docs or do you need more help on something help (like the course or your base code)?
Thank you again (I am starting contributing to open source and I have some many interrogations 😄 ).

**Comment by RandellDawson** [comment]
> By the way: is it a good thing to contribute on the french docs or do you need more help on something help (like the course or your base code)?

The [new curriculum](https://github.com/freeCodeCamp/CurriculumExpansion) could really use some help.

**Comment by tdimnet** [comment]
@RandellDawson : it's done!
Thank you for the link I am going to have a look on it.

**Comment by RandellDawson** [comment]
@tdimnet After reviewing your document compared to the [current English version](https://github.com/freeCodeCamp/freeCodeCamp/blob/master/README.md) you will notice your version is missing many of the links on the sub sections of the curriculum.  Also, The capitalization is not always the same for the titles.  Lastly, under the English version's `The Learning Platform`, there are more bullet points than your translation has.  Can you make sure your document matches the English version?

Thanks.

**Comment by tdimnet** [comment]
It should better now.
When I start working on this branch I was not sure you were interested in these modifications (since it was French translation).

The `Readme` file is now up to date.

**Comment by RandellDawson** [comment]
For the documentation like README.md and CONTRIBUTING.md, we don't mind having other language translations.

**Review by RandellDawson — APPROVED** [review]
I made a few indentation changes for the list of projects.

**Review by RandellDawson — APPROVED** [review]

**Pull request merged**
