### PR TITLE
add comment explaining back-end challenges don't need a solution

### PR DESCRIPTION
**Pull request by ambarvm**
add solution to the challenge: add-a-description-to-your-package-json

- [x] I have read [freeCodeCamp's contribution guidelines](https://github.com/freeCodeCamp/freeCodeCamp/blob/master/CONTRIBUTING.md).
- [x] My pull request has a descriptive title (not a vague title like `Update index.md`)
- [x] My pull request targets the `master` branch of freeCodeCamp.
- [x] None of my changes are plagiarized from another source without proper attribution.
- [x] All the files I changed are in the same world language (for example: only English changes, or only Chinese changes, etc.)
- [x] My changes do not use shortened URLs or affiliate links.

Closes #XXXXX

### CODE REVIEW

**Comment by RandellDawson** [comment]
@raisedadead These backend challenges don't need solutions, because they would need to be tested against a full working project (on Glitch or something local).  The tests work against a url and not the solution in the Solution section.

**Comment by raisedadead** [comment]
@RandellDawson You are correct. 

Will it be a good idea to add this a comment in the solution sections for these challenges:

```markdown

	## Solution
	<section id='solution'>
	
	```js
	/**
	
	Backend challenges don't need solutions, 
    because they would need to be tested against a full working project. 
    Please check our contributing guidelines to learn more.
	
	*/ 
	```
	
	</section>

```

**Comment by supercoww** [comment]
I confused the solution section for the solution that gets displayed when you press the `Get a Hint` button. Is that section removed from the repository?

**Comment by thecodingaviator** [comment]
> I confused the solution section for the solution that gets displayed when you press the `Get a Hint` button. Is that section removed from the repository?

Yes @supercoww please see #36729

**Comment by raisedadead** [comment]
Okay great.

@supercoww 

Will you be interested in updating the backend challenges with the comment then?

**Comment by supercoww** [comment]
> Okay great.
> 
> @supercoww
> 
> Will you be interested in updating the backend challenges with the comment then?

Yes, I will to do it 😊

**Review by moT01 — APPROVED** [review]
Looks like this adds the message to all the apis and microservices challenges/projects - Any interest in adding the same message to everything in the information security section @supercoww? I think it would be easiest to just make a new PR for those to keep them smaller; but they could be tacked on to this one if you want. If not, we can make an issue for someone else to add it to those.

Unless you want to tack the other stuff onto this PR - it LGTM - let us know.

**Comment by RandellDawson** [comment]
@supercoww I second the request to have all the backend challenges updated on the same PR.

**Comment by supercoww** [comment]
@moT01 I will add the comment for the information security section. I would prefer making another pull request for that if that's okay.

**Comment by RandellDawson** [comment]
>  I would prefer making another pull request for that if that's okay.

As long as the total number of files affected is not more than 75, please put all the same changes on this PR.

Thank you.

**Review by RandellDawson — CHANGES_REQUESTED** [review]
>  I would prefer making another pull request for that if that's okay.

As long as the total number of files affected is not more than 75, please put all the same changes on this PR.

Thank you.

**Comment by moT01** [comment]
Adding those files onto this will put it well over 75 files - a second PR is fine for this. Makes reviewing easier as well.

**Comment by supercoww** [comment]
Made a separate PR #37227 as asked by @moT01

**Comment by scissorsneedfoodtoo** [comment]
@supercoww, thank you for adding these messages to the challenges here and in https://github.com/freeCodeCamp/freeCodeCamp/pull/37227. Looking forward to your future contributions! :+1: :+1:

**Pull request merged**
