### PR TITLE
Typo fix line 13

### PR DESCRIPTION
**Pull request by LeoGuilherme**
Changed the word "ocupará" to "ocupar" because of context in the portuguese translation.

- [x] I have read [freeCodeCamp's contribution guidelines](https://github.com/freeCodeCamp/freeCodeCamp/blob/master/CONTRIBUTING.md).
- [x] My pull request has a descriptive title (not a vague title like `Update index.md`)
- [x] My pull request targets the `master` branch of freeCodeCamp.
- [x] None of my changes are plagiarized from another source without proper attribution.
- [x] All the files I changed are in the same world language (for example: only English changes, or only Chinese changes, etc.)
- [x] My changes do not use shortened URLs or affiliate links.

Closes #XXXXX

### CODE REVIEW

**Review by thecodingaviator — COMMENTED** [review]
Hi, Please read our [Guidelines for Contributing](https://github.com/freeCodeCamp/freeCodeCamp/blob/master/CONTRIBUTING.md) before opening a PR.

We are marking this as invalid and closing for low effort.

Thanks.

**Comment by LeoGuilherme** [comment]
Hi @thecodingaviator , in the "Guidelines for Contributing" there is a specific part about correcting a typo, which I quote below:
> I found a typo, should I report an issue before I can make a pull request?
For typos and other wording changes, you can directly open pull requests without first creating an issue. Issues are more for discussing larger problems associated with code or structural aspects of the curriculum.

So, I found the typo and opened a PR like the Guidelines says. I know it's just a word, but it's wrong nonetheless. Will it just stay wrong then?

**Comment by thecodingaviator** [comment]
I had closed this for low-effort however I'll cc @raisedadead as I think he is better qualified to answer that question.

**Comment by raisedadead** [comment]
Hi @LeoGuilherme thanks for taking the time to make the pull-request. 

And while you are correct about the guidelines, we are getting a lot of spam and low effort pull-requests during hacktoberfest. This would not have been an issue any other time of the year. I hope you understand our intention to discourage spam and not contributions.

We will gladly accept the change if you can incorporate this as a part of a larger set of changes? I am pretty sure there are lot of things that need updating in the translation areas for portuguese?

I am unmarking this as invalid in good faith. But we encourage you to make a fresh PR as well and get it peer reviewed from another speaker.

Happy contributing.

**Comment by LeoGuilherme** [comment]
@raisedadead Ah I understand now, thanks for explaining it. This typo was something that jumped to my eyes as soon as I read the page, but I'll review the entire page again to see if there's more things that need to be corrected and then open a new PR.
Thanks @thecodingaviator and @raisedadead .

**Pull request closed without merging**
