### PR TITLE
[Guide] Data Structures: Create a Set Class

### PR DESCRIPTION
**Pull request by ezioda004**
Added Data Structures: Create a Set Class method, solution and reference.

- [x] I have read [freeCodeCamp's contribution guidelines](https://github.com/freeCodeCamp/freeCodeCamp/blob/master/CONTRIBUTING.md).
- [x] My pull request has a descriptive title (not a vague title like `Update index.md`)
- [x] My pull request targets the `master` branch of freeCodeCamp.
- [x] None of my changes are plagiarized from another source without proper attribution.
- [x] My article does not contain shortened URLs or affiliate links.

If your pull request closes a GitHub issue, replace the XXXXX below with the issue number.

Closes #XXXXX

### CODE REVIEW

**Review by cmccormack — COMMENTED** [review]
Everything looks good, although the solution for `this.add` seems maybe a bit too code golf, nesting an `&&` within a ternary.  Maybe consider expanding it just to make it easier to grok quickly.

**Review by cmccormack — APPROVED** [review]
Everything looks good, although the solution for `this.add` seems maybe a bit too code golf, nesting an `&&` within a ternary.  Maybe consider expanding it just to make it easier to grok quickly.

Tested locally and all tests passed using given solution.

**Comment by ezioda004** [comment]
@cmccormack My linter didnt give any warning; should I change the expression to `if` statement?

**Comment by cmccormack** [comment]
> @cmccormack My linter didnt give any warning; should I change the expression to `if` statement?

Not a linting issue, just wondering if it could be more clearly described.
an if statement would be very clear, something like

```js
    this.add = function(el){
        if (this.has(el)) {
            return false;
        }
        collection.push(el);
        return true;
    }
```

Something like the following may be more terse and slightly easier to understand
```js
    this.add = function(el){
        return this.has(el) ? false : Boolean(collection.push(el))
    }
```

or maybe
```js
    this.add = function(el){
        return this.has(el) && Boolean(collection.push(el))
    }
```

I'm not sure if any of these are actually an improvement though.  I will gladly approve this PR and allow someone who has a better idea submit their own PR.

**Comment by ezioda004** [comment]
@cmccormack These suggestions are definitely more readable! Since this challenge is interview prep - I used the boolean ternary suggestion, we can presume that anyone attempting this section can understand explicit type coercion and ternary operator.

**Review by cmccormack — APPROVED** [review]
This looks great to me.  Thank you for your contribution!

**Pull request merged**
