### PR TITLE
fix(curriculum): fixing the potentially confusing use of brackets in challenges text.

### LINKED ISSUE #52809: Potentially confusing use of brackets in challenges text
### Describe the Issue

Example:

> Use the `+=` operator to add `Your [weapon] breaks.`

I think it is easy to misinterpret this in challenges where bracket notation is used in the code, as it is in this project.

Not sure what the solution is. I feel like this might also be another instance where the lack of string notation is an issue.

### Affected Page

https://www.freecodecamp.org/learn/javascript-algorithms-and-data-structures-v8/learn-basic-javascript-by-building-a-role-playing-game/step-155

### Your code

```



```

### Expected behavior

Do not use [initializer/literal syntax](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Operators#primary_expressions) in the challenge guide text to avoid confusion.

### Screenshots

_No response_

### System

- Device: [e.g. iPhone 6, Laptop]
- OS: [e.g. iOS 14, Windows 10, Ubuntu 20.04]
- Browser: [e.g. Chrome, Safari]
- Version: [e.g. 22]

### Additional context

forum: https://forum.freecodecamp.org/t/learn-basic-javascript-by-building-a-role-playing-game-step-155/658923

### PR DESCRIPTION
**Pull request by luqmanalzobe**
Checklist:

- [x] I have read and followed the [contribution guidelines](https://contribute.freecodecamp.org).
- [x] I have read and followed the [how to open a pull request guide](https://contribute.freecodecamp.org/#/how-to-open-a-pull-request).
- [x] My pull request targets the `main` branch of freeCodeCamp.
- [x] I have tested these changes either locally on my machine, or GitPod.

Closes #52809

Changes the way the bracket notation is used in the code, so that the instructions are not misinterpreted.

Changes both instances where the instructions say ```[weapon]``` to ```[weapon]```

### CODE REVIEW

**Review by gikf — COMMENTED** [review]
There's three more steps with similar pattern:
[119](https://github.com/freeCodeCamp/freeCodeCamp/blob/main/curriculum/challenges/english/15-javascript-algorithms-and-data-structures-22/learn-basic-javascript-by-building-a-role-playing-game/62a8e35675c18c56354c08cf.md)
[120](https://github.com/freeCodeCamp/freeCodeCamp/blob/main/curriculum/challenges/english/15-javascript-algorithms-and-data-structures-22/learn-basic-javascript-by-building-a-role-playing-game/62a8e41e2f190c58404dd46e.md)
[128](https://github.com/freeCodeCamp/freeCodeCamp/blob/main/curriculum/challenges/english/15-javascript-algorithms-and-data-structures-22/learn-basic-javascript-by-building-a-role-playing-game/62a8eec45f77bc69e8775294.md)

**Comment by luqmanalzobe** [comment]
Sounds good I can do those steps aswell.

**Comment by luqmanalzobe** [comment]
I've just added another commit and fixed steps 119, 120, and 128.

**Review by plamoni — APPROVED** [review]
LGTM.

**Review by gikf — APPROVED** [review]
LGTM :+1:

**Comment by gikf** [comment]
Hi @luqmanalzobe. Congrats on your first pull request (PR)! 🎉

Thank you for your contribution to the page! 👍
We are happy to accept these changes and look forward to future contributions. 📝

**Pull request merged**
