### PR TITLE
Update Chinese translation of responsive-web-design

### LINKED ISSUE #40479: Chinese challenges (Responsive Web Design) needing an audit for English changes from Feb 29, 2020
@freeCodeCamp/chinese 

In preparation of the upcoming launch of the Chinese curriculum, the following Chinese curriculum challenges need to be compared to their English equivalents.

This issue only covers challenges in the **`Responsive Web Design`** certification.

All the challenges below have Description or Instructions sections with changes to the English version since Feb 29, 2020. Also includes any challenges with Tests where at least one test's text has changed in the English version since Feb 29, 2020 or where the number of tests in the current English version is different than the number of tests in the current Chinese version.

Please create any necessary PRs to bring the Chinese challenge listed below in sync with the English version.  

**NOTES:**
- Some changes are not translation related (like addition of code examples or addition/removal of code tags (single back ticks).  These changes are still needed to bring make the challenge more like the English version.
- There are two links to the right of the challenge title (one allows you directly link to the editable Chinese version of the file on GitHub and the other links to the raw English version.  You can right-click and open the links in new tabs to keep this issue in the background.
---
- [ ] **Standardize Times with the HTML5 datetime Attribute** [Edit Chinese](https://github.com/freeCodeCamp/freeCodeCamp/edit/master/curriculum/challenges/chinese/01-responsive-web-design/applied-accessibility/standardize-times-with-the-html5-datetime-attribute.md) | [View English](https://raw.githubusercontent.com/freeCodeCamp/freeCodeCamp/master/curriculum/challenges/english/01-responsive-web-design/applied-accessibility/standardize-times-with-the-html5-datetime-attribute.md)

<details><summary>Show/Hide sections with changes/issues</summary>

- **The following test(s) `text` do not match:**
**Instructions:** Make sure to also check that the English tests have not been reorderd.
**Test 1**
    <table>
  <tr>
  <th>
  Version
  </th>
  <th align="left">
  Text
  </th>
  </tr>
  <tr>
  <td align>Old</td>
  <td align>

```
  Your code should have a <code>p</code> element which includes the text "Thank you to everyone for responding to Master Camper Cat's survey." and include a <code>time</code> element.
```
  </td>
  </tr>
  <td>New</td>
  <td>

```
  Your code should have a `p` element which includes the text `Thank you to everyone for responding to Master Camper Cat's survey.` and include a `time` element.

```
  </td>
  </tr>
  </table>

**Test 2**
    <table>
  <tr>
  <th>
  Version
  </th>
  <th align="left">
  Text
  </th>
  </tr>
  <tr>
  <td align>Old</td>
  <td align>

```
  Your added <code>time</code> tags should wrap around the text "Thursday, September 15&lt;sup&gt;th&lt;/sup&gt;".
```
  </td>
  </tr>
  <td>New</td>
  <td>

```
  Your added `time` tags should wrap around the text `Thursday, September 15<sup>th</sup>`.

```
  </td>
  </tr>
  </table>

**Test 4**
    <table>
  <tr>
  <th>
  Version
  </th>
  <th align="left">
  Text
  </th>
  </tr>
  <tr>
  <td align>Old</td>
  <td align>

```
  Your added <code>datetime</code> attribute should be set to a value of 2016-09-15.
```
  </td>
  </tr>
  <td>New</td>
  <td>

```
  Your added `datetime` attribute should be set to a value of `2016-09-15`.

```
  </td>
  </tr>
  </table>

</details>

---
- [ ] **Use tabindex to Specify the Order of Keyboard Focus for Several Elements** [Edit Chinese](https://github.com/freeCodeCamp/freeCodeCamp/edit/master/curriculum/challenges/chinese/01-responsive-web-design/applied-accessibility/use-tabindex-to-specify-the-order-of-keyboard-focus-for-several-elements.md) | [View English](https://raw.githubusercontent.com/freeCodeCamp/freeCodeCamp/master/curriculum/challenges/english/01-responsive-web-design/applied-accessibility/use-tabindex-to-specify-the-order-of-keyboard-focus-for-several-elements.md)

<details><summary>Show/Hide sections with changes/issues</summary>

- **`Description` section has changed**
- **`Instructions` section has changed**

</details>

---
- [ ] **Use tabindex to Add Keyboard Focus to an Element** [Edit Chinese](https://github.com/freeCodeCamp/freeCodeCamp/edit/master/curriculum/challenges/chinese/01-responsive-web-design/applied-accessibility/use-tabindex-to-add-keyboard-focus-to-an-element.md) | [View English](https://raw.githubusercontent.com/freeCodeCamp/freeCodeCamp/master/curriculum/challenges/english/01-responsive-web-design/applied-accessibility/use-tabindex-to-add-keyboard-focus-to-an-element.md)

<details><summary>Show/Hide sections with changes/issues</summary>

- **`Instructions` section has changed**

</details>

---
- [ ] **Add Images to Your Website** [Edit Chinese](https://github.com/freeCodeCamp/freeCodeCamp/edit/master/curriculum/challenges/chinese/01-responsive-web-design/basic-html-and-html5/add-images-to-your-website.md) | [View English](https://raw.githubusercontent.com/freeCodeCamp/freeCodeCamp/master/curriculum/challenges/english/01-responsive-web-design/basic-html-and-html5/add-images-to-your-website.md)

<details><summary>Show/Hide sections with changes/issues</summary>

- **`Description` section has changed**

</details>

---
- [ ] **Link to External Pages with Anchor Elements** [Edit Chinese](https://github.com/freeCodeCamp/freeCodeCamp/edit/master/curriculum/challenges/chinese/01-responsive-web-design/basic-html-and-html5/link-to-external-pages-with-anchor-elements.md) | [View English](https://raw.githubusercontent.com/freeCodeCamp/freeCodeCamp/master/curriculum/challenges/english/01-responsive-web-design/basic-html-and-html5/link-to-external-pages-with-anchor-elements.md)

<details><summary>Show/Hide sections with changes/issues</summary>

- **`Instructions` section has changed**
- **The following test(s) `text` do not match:**
**Instructions:** Make sure to also check that the English tests have not been reorderd.
**Test 2**
    <table>
  <tr>
  <th>
  Version
  </th>
  <th align="left">
  Text
  </th>
  </tr>
  <tr>
  <td align>Old</td>
  <td align>

```
  You need an <code>a</code> element that links to <code>http&#58;//freecatphotoapp<wbr>.com</code>
```
  </td>
  </tr>
  <td>New</td>
  <td>

```
  You need an `a` element that links to `https://freecatphotoapp.com`

```
  </td>
  </tr>
  </table>

</details>

---
- [ ] **Use the value attribute with Radio Buttons and Checkboxes** [Edit Chinese](https://github.com/freeCodeCamp/freeCodeCamp/edit/master/curriculum/challenges/chinese/01-responsive-web-design/basic-html-and-html5/use-the-value-attribute-with-radio-buttons-and-checkboxes.md) | [View English](https://raw.githubusercontent.com/freeCodeCamp/freeCodeCamp/master/curriculum/challenges/english/01-responsive-web-design/basic-html-and-html5/use-the-value-attribute-with-radio-buttons-and-checkboxes.md)

<details><summary>Show/Hide sections with changes/issues</summary>

- **`Description` section has changed**

</details>

---
- [ ] **Nest an Anchor Element within a Paragraph** [Edit Chinese](https://github.com/freeCodeCamp/freeCodeCamp/edit/master/curriculum/challenges/chinese/01-responsive-web-design/basic-html-and-html5/nest-an-anchor-element-within-a-paragraph.md) | [View English](https://raw.githubusercontent.com/freeCodeCamp/freeCodeCamp/master/curriculum/challenges/english/01-responsive-web-design/basic-html-and-html5/nest-an-anchor-element-within-a-paragraph.md)

<details><summary>Show/Hide sections with changes/issues</summary>

- **`Instructions` section has changed**
- **The following test(s) `text` do not match:**
**Instructions:** Make sure to also check that the English tests have not been reorderd.
**Test 1**
    <table>
  <tr>
  <th>
  Version
  </th>
  <th align="left">
  Text
  </th>
  </tr>
  <tr>
  <td align>Old</td>
  <td align>

```
  You should have an <code>a</code> element that links to "http://freecatphotoapp.com".
```
  </td>
  </tr>
  <td>New</td>
  <td>

```
  You should have an `a` element that links to "`https://freecatphotoapp.com`".

```
  </td>
  </tr>
  </table>

</details>

---
- [ ] **Headline with the h2 Element** [Edit Chinese](https://github.com/freeCodeCamp/freeCodeCamp/edit/master/curriculum/challenges/chinese/01-responsive-web-design/basic-html-and-html5/headline-with-the-h2-element.md) | [View English](https://raw.githubusercontent.com/freeCodeCamp/freeCodeCamp/master/curriculum/challenges/english/01-responsive-web-design/basic-html-and-html5/headline-with-the-h2-element.md)

<details><summary>Show/Hide sections with changes/issues</summary>

- **Number of tests do not match - English: 5 | Chinese: 4**
**Instructions:** Add or delete the applicable tests.  It is possible some tests have been rearranged, so make sure each English test has a corresponding Chinese test in the same order

</details>

---
- [ ] **Add Placeholder Text to a Text Field** [Edit Chinese](https://github.com/freeCodeCamp/freeCodeCamp/edit/master/curriculum/challenges/chinese/01-responsive-web-design/basic-html-and-html5/add-placeholder-text-to-a-text-field.md) | [View English](https://raw.githubusercontent.com/freeCodeCamp/freeCodeCamp/master/curriculum/challenges/english/01-responsive-web-design/basic-html-and-html5/add-placeholder-text-to-a-text-field.md)

<details><summary>Show/Hide sections with changes/issues</summary>

- **The following test(s) `text` do not match:**
**Instructions:** Make sure to also check that the English tests have not been reorderd.
**Test 2**
    <table>
  <tr>
  <th>
  Version
  </th>
  <th align="left">
  Text
  </th>
  </tr>
  <tr>
  <td align>Old</td>
  <td align>

```
  You should set the value of your placeholder attribute to "cat photo URL".
```
  </td>
  </tr>
  <td>New</td>
  <td>

```
  You should set the value of your placeholder attribute to `cat photo URL`.

```
  </td>
  </tr>
  </table>

</details>

---
- [ ] **Create a Form Element** [Edit Chinese](https://github.com/freeCodeCamp/freeCodeCamp/edit/master/curriculum/challenges/chinese/01-responsive-web-design/basic-html-and-html5/create-a-form-element.md) | [View English](https://raw.githubusercontent.com/freeCodeCamp/freeCodeCamp/master/curriculum/challenges/english/01-responsive-web-design/basic-html-and-html5/create-a-form-element.md)

<details><summary>Show/Hide sections with changes/issues</summary>

- **`Instructions` section has changed**
- **The following test(s) `text` do not match:**
**Instructions:** Make sure to also check that the English tests have not been reorderd.
**Test 1**
    <table>
  <tr>
  <th>
  Version
  </th>
  <th align="left">
  Text
  </th>
  </tr>
  <tr>
  <td align>Old</td>
  <td align>

```
  Your text input element should be nested within a <code>form</code> element.
```
  </td>
  </tr>
  <td>New</td>
  <td>

```
  The existing `input` element should be nested within a `form` element.

```
  </td>
  </tr>
  </table>

**Test 2**
    <table>
  <tr>
  <th>
  Version
  </th>
  <th align="left">
  Text
  </th>
  </tr>
  <tr>
  <td align>Old</td>
  <td align>

```
  Your <code>form</code> should have an <code>action</code> attribute which is set to <code>/submit-cat-photo</code>
```
  </td>
  </tr>
  <td>New</td>
  <td>

```
  Your `form` should have an `action` attribute which is set to `https://freecatphotoapp.com/submit-cat-photo`

```
  </td>
  </tr>
  </table>

</details>

---
- [ ] **Create an Ordered List** [Edit Chinese](https://github.com/freeCodeCamp/freeCodeCamp/edit/master/curriculum/challenges/chinese/01-responsive-web-design/basic-html-and-html5/create-an-ordered-list.md) | [View English](https://raw.githubusercontent.com/freeCodeCamp/freeCodeCamp/master/curriculum/challenges/english/01-responsive-web-design/basic-html-and-html5/create-an-ordered-list.md)

<details><summary>Show/Hide sections with changes/issues</summary>

- **The following test(s) `text` do not match:**
**Instructions:** Make sure to also check that the English tests have not been reorderd.
**Test 1**
    <table>
  <tr>
  <th>
  Version
  </th>
  <th align="left">
  Text
  </th>
  </tr>
  <tr>
  <td align>Old</td>
  <td align>

```
  You should have an ordered list for "Top 3 things cats hate:"
```
  </td>
  </tr>
  <td>New</td>
  <td>

```
  You should have an ordered list for `Top 3 things cats hate:`

```
  </td>
  </tr>
  </table>

**Test 2**
    <table>
  <tr>
  <th>
  Version
  </th>
  <th align="left">
  Text
  </th>
  </tr>
  <tr>
  <td align>Old</td>
  <td align>

```
  You should have an unordered list for "Things cats love:"
```
  </td>
  </tr>
  <td>New</td>
  <td>

```
  You should have an unordered list for `Things cats love:`

```
  </td>
  </tr>
  </table>

</details>

---
- [ ] **Make Dead Links Using the Hash Symbol** [Edit Chinese](https://github.com/freeCodeCamp/freeCodeCamp/edit/master/curriculum/challenges/chinese/01-responsive-web-design/basic-html-and-html5/make-dead-links-using-the-hash-symbol.md) | [View English](https://raw.githubusercontent.com/freeCodeCamp/freeCodeCamp/master/curriculum/challenges/english/01-responsive-web-design/basic-html-and-html5/make-dead-links-using-the-hash-symbol.md)

<details><summary>Show/Hide sections with changes/issues</summary>

- **`Instructions` section has changed**

</details>

---
- [ ] **Add a Submit Button to a Form** [Edit Chinese](https://github.com/freeCodeCamp/freeCodeCamp/edit/master/curriculum/challenges/chinese/01-responsive-web-design/basic-html-and-html5/add-a-submit-button-to-a-form.md) | [View English](https://raw.githubusercontent.com/freeCodeCamp/freeCodeCamp/master/curriculum/challenges/english/01-responsive-web-design/basic-html-and-html5/add-a-submit-button-to-a-form.md)

<details><summary>Show/Hide sections with changes/issues</summary>

- **The following test(s) `text` do not match:**
**Instructions:** Make sure to also check that the English tests have not been reorderd.
**Test 3**
    <table>
  <tr>
  <th>
  Version
  </th>
  <th align="left">
  Text
  </th>
  </tr>
  <tr>
  <td align>Old</td>
  <td align>

```
  Your submit button should only have the text "Submit".
```
  </td>
  </tr>
  <td>New</td>
  <td>

```
  Your submit button should only have the text `Submit`.

```
  </td>
  </tr>
  </table>

</details>

---
- [ ] **Inform with the Paragraph Element** [Edit Chinese](https://github.com/freeCodeCamp/freeCodeCamp/edit/master/curriculum/challenges/chinese/01-responsive-web-design/basic-html-and-html5/inform-with-the-paragraph-element.md) | [View English](https://raw.githubusercontent.com/freeCodeCamp/freeCodeCamp/master/curriculum/challenges/english/01-responsive-web-design/basic-html-and-html5/inform-with-the-paragraph-element.md)

<details><summary>Show/Hide sections with changes/issues</summary>

- **The following test(s) `text` do not match:**
**Instructions:** Make sure to also check that the English tests have not been reorderd.
**Test 2**
    <table>
  <tr>
  <th>
  Version
  </th>
  <th align="left">
  Text
  </th>
  </tr>
  <tr>
  <td align>Old</td>
  <td align>

```
  Your <code>p</code> element should have the text "Hello Paragraph".
```
  </td>
  </tr>
  <td>New</td>
  <td>

```
  Your `p` element should have the text `Hello Paragraph`.

```
  </td>
  </tr>
  </table>

</details>

---
- [ ] **Use grid-area Without Creating an Areas Template** [Edit Chinese](https://github.com/freeCodeCamp/freeCodeCamp/edit/master/curriculum/challenges/chinese/01-responsive-web-design/css-grid/use-grid-area-without-creating-an-areas-template.md) | [View English](https://raw.githubusercontent.com/freeCodeCamp/freeCodeCamp/master/curriculum/challenges/english/01-responsive-web-design/css-grid/use-grid-area-without-creating-an-areas-template.md)

<details><summary>Show/Hide sections with changes/issues</summary>

- **The following test(s) `text` do not match:**
**Instructions:** Make sure to also check that the English tests have not been reorderd.
**Test 1**
    <table>
  <tr>
  <th>
  Version
  </th>
  <th align="left">
  Text
  </th>
  </tr>
  <tr>
  <td align>Old</td>
  <td align>

```
  <code>item5</code> class should have a <code>grid-area</code> property such that it is between the third and fourth horizontal lines and between the first and fourth vertical lines.
```
  </td>
  </tr>
  <td>New</td>
  <td>

```
  The `item5` class should have a `grid-area` property to make it fill the whole area between the third and fourth horizontal lines, and first and fourth vertical lines.

```
  </td>
  </tr>
  </table>

</details>

---
- [ ] **Size Your Images** [Edit Chinese](https://github.com/freeCodeCamp/freeCodeCamp/edit/master/curriculum/challenges/chinese/01-responsive-web-design/basic-css/size-your-images.md) | [View English](https://raw.githubusercontent.com/freeCodeCamp/freeCodeCamp/master/curriculum/challenges/english/01-responsive-web-design/basic-css/size-your-images.md)

<details><summary>Show/Hide sections with changes/issues</summary>

- **`Instructions` section has changed**
- **The following test(s) `text` do not match:**
**Instructions:** Make sure to also check that the English tests have not been reorderd.
**Test 2**
    <table>
  <tr>
  <th>
  Version
  </th>
  <th align="left">
  Text
  </th>
  </tr>
  <tr>
  <td align>Old</td>
  <td align>

```
  Your image should be 100 pixels wide. Browser zoom should be at 100%.
```
  </td>
  </tr>
  <td>New</td>
  <td>

```
  Your image should be 100 pixels wide.

```
  </td>
  </tr>
  </table>

</details>

---
- [ ] **Import a Google Font** [Edit Chinese](https://github.com/freeCodeCamp/freeCodeCamp/edit/master/curriculum/challenges/chinese/01-responsive-web-design/basic-css/import-a-google-font.md) | [View English](https://raw.githubusercontent.com/freeCodeCamp/freeCodeCamp/master/curriculum/challenges/english/01-responsive-web-design/basic-css/import-a-google-font.md)

<details><summary>Show/Hide sections with changes/issues</summary>

- **`Description` section has changed**
- **`Instructions` section has changed**
- **The following test(s) `text` do not match:**
**Instructions:** Make sure to also check that the English tests have not been reorderd.
**Test 3**
    <table>
  <tr>
  <th>
  Version
  </th>
  <th align="left">
  Text
  </th>
  </tr>
  <tr>
  <td align>Old</td>
  <td align>

```
  You should use an <code>h2</code> CSS selector to change the font.
```
  </td>
  </tr>
  <td>New</td>
  <td>

```
  You should only use an `h2` element selector to change the font.

```
  </td>
  </tr>
  </table>

</details>

---
- [ ] **Adjust the Padding of an Element** [Edit Chinese](https://github.com/freeCodeCamp/freeCodeCamp/edit/master/curriculum/challenges/chinese/01-responsive-web-design/basic-css/adjust-the-padding-of-an-element.md) | [View English](https://raw.githubusercontent.com/freeCodeCamp/freeCodeCamp/master/curriculum/challenges/english/01-responsive-web-design/basic-css/adjust-the-padding-of-an-element.md)

<details><summary>Show/Hide sections with changes/issues</summary>

- **`Description` section has changed**

</details>

---
- [ ] **Use the align-items Property in the Tweet Embed** [Edit Chinese](https://github.com/freeCodeCamp/freeCodeCamp/edit/master/curriculum/challenges/chinese/01-responsive-web-design/css-flexbox/use-the-align-items-property-in-the-tweet-embed.md) | [View English](https://raw.githubusercontent.com/freeCodeCamp/freeCodeCamp/master/curriculum/challenges/english/01-responsive-web-design/css-flexbox/use-the-align-items-property-in-the-tweet-embed.md)

<details><summary>Show/Hide sections with changes/issues</summary>

- **`Instructions` section has changed**

</details>

---
- [ ] **Use the flex-direction Property to Make a Row** [Edit Chinese](https://github.com/freeCodeCamp/freeCodeCamp/edit/master/curriculum/challenges/chinese/01-responsive-web-design/css-flexbox/use-the-flex-direction-property-to-make-a-row.md) | [View English](https://raw.githubusercontent.com/freeCodeCamp/freeCodeCamp/master/curriculum/challenges/english/01-responsive-web-design/css-flexbox/use-the-flex-direction-property-to-make-a-row.md)

<details><summary>Show/Hide sections with changes/issues</summary>

- **`Description` section has changed**

</details>

---
- [ ] **Use the flex-direction Property to Make a Column** [Edit Chinese](https://github.com/freeCodeCamp/freeCodeCamp/edit/master/curriculum/challenges/chinese/01-responsive-web-design/css-flexbox/use-the-flex-direction-property-to-make-a-column.md) | [View English](https://raw.githubusercontent.com/freeCodeCamp/freeCodeCamp/master/curriculum/challenges/english/01-responsive-web-design/css-flexbox/use-the-flex-direction-property-to-make-a-column.md)

<details><summary>Show/Hide sections with changes/issues</summary>

- **`Description` section has changed**

</details>

---
- [ ] **Create a Media Query** [Edit Chinese](https://github.com/freeCodeCamp/freeCodeCamp/edit/master/curriculum/challenges/chinese/01-responsive-web-design/responsive-web-design-principles/create-a-media-query.md) | [View English](https://raw.githubusercontent.com/freeCodeCamp/freeCodeCamp/master/curriculum/challenges/english/01-responsive-web-design/responsive-web-design-principles/create-a-media-query.md)

<details><summary>Show/Hide sections with changes/issues</summary>

- **`Instructions` section has changed**

</details>

---
- [ ] **Use a Retina Image for Higher Resolution Displays** [Edit Chinese](https://github.com/freeCodeCamp/freeCodeCamp/edit/master/curriculum/challenges/chinese/01-responsive-web-design/responsive-web-design-principles/use-a-retina-image-for-higher-resolution-displays.md) | [View English](https://raw.githubusercontent.com/freeCodeCamp/freeCodeCamp/master/curriculum/challenges/english/01-responsive-web-design/responsive-web-design-principles/use-a-retina-image-for-higher-resolution-displays.md)

<details><summary>Show/Hide sections with changes/issues</summary>

- **`Instructions` section has changed**

</details>

---
- [ ] **Use the strong Tag to Make Text Bold** [Edit Chinese](https://github.com/freeCodeCamp/freeCodeCamp/edit/master/curriculum/challenges/chinese/01-responsive-web-design/applied-visual-design/use-the-strong-tag-to-make-text-bold.md) | [View English](https://raw.githubusercontent.com/freeCodeCamp/freeCodeCamp/master/curriculum/challenges/english/01-responsive-web-design/applied-visual-design/use-the-strong-tag-to-make-text-bold.md)

<details><summary>Show/Hide sections with changes/issues</summary>

- **The following test(s) `text` do not match:**
**Instructions:** Make sure to also check that the English tests have not been reorderd.
**Test 3**
    <table>
  <tr>
  <th>
  Version
  </th>
  <th align="left">
  Text
  </th>
  </tr>
  <tr>
  <td align>Old</td>
  <td align>

```
  The <code>strong</code> tag should wrap around the words "Stanford University".
```
  </td>
  </tr>
  <td>New</td>
  <td>

```
  The `strong` tag should wrap around the words `Stanford University`.

```
  </td>
  </tr>
  </table>

</details>

---
- [ ] **Use the s Tag to Strikethrough Text** [Edit Chinese](https://github.com/freeCodeCamp/freeCodeCamp/edit/master/curriculum/challenges/chinese/01-responsive-web-design/applied-visual-design/use-the-s-tag-to-strikethrough-text.md) | [View English](https://raw.githubusercontent.com/freeCodeCamp/freeCodeCamp/master/curriculum/challenges/english/01-responsive-web-design/applied-visual-design/use-the-s-tag-to-strikethrough-text.md)

<details><summary>Show/Hide sections with changes/issues</summary>

- **`Instructions` section has changed**

</details>

---
- [ ] **Use the u Tag to Underline Text** [Edit Chinese](https://github.com/freeCodeCamp/freeCodeCamp/edit/master/curriculum/challenges/chinese/01-responsive-web-design/applied-visual-design/use-the-u-tag-to-underline-text.md) | [View English](https://raw.githubusercontent.com/freeCodeCamp/freeCodeCamp/master/curriculum/challenges/english/01-responsive-web-design/applied-visual-design/use-the-u-tag-to-underline-text.md)

<details><summary>Show/Hide sections with changes/issues</summary>

- **The following test(s) `text` do not match:**
**Instructions:** Make sure to also check that the English tests have not been reorderd.
**Test 2**
    <table>
  <tr>
  <th>
  Version
  </th>
  <th align="left">
  Text
  </th>
  </tr>
  <tr>
  <td align>Old</td>
  <td align>

```
  The <code>u</code> tag should wrap around the text "Ph.D. students".
```
  </td>
  </tr>
  <td>New</td>
  <td>

```
  The `u` tag should wrap around the text `Ph.D. students`.

```
  </td>
  </tr>
  </table>

</details>

---
- [ ] **Set the font-size for Multiple Heading Elements** [Edit Chinese](https://github.com/freeCodeCamp/freeCodeCamp/edit/master/curriculum/challenges/chinese/01-responsive-web-design/applied-visual-design/set-the-font-size-for-multiple-heading-elements.md) | [View English](https://raw.githubusercontent.com/freeCodeCamp/freeCodeCamp/master/curriculum/challenges/english/01-responsive-web-design/applied-visual-design/set-the-font-size-for-multiple-heading-elements.md)

<details><summary>Show/Hide sections with changes/issues</summary>

- **`Instructions` section has changed**

</details>

---
- [ ] **Create a Gradual CSS Linear Gradient** [Edit Chinese](https://github.com/freeCodeCamp/freeCodeCamp/edit/master/curriculum/challenges/chinese/01-responsive-web-design/applied-visual-design/create-a-gradual-css-linear-gradient.md) | [View English](https://raw.githubusercontent.com/freeCodeCamp/freeCodeCamp/master/curriculum/challenges/english/01-responsive-web-design/applied-visual-design/create-a-gradual-css-linear-gradient.md)

<details><summary>Show/Hide sections with changes/issues</summary>

- **`Description` section has changed**

</details>

---
- [ ] **Build a Tribute Page** [Edit Chinese](https://github.com/freeCodeCamp/freeCodeCamp/edit/master/curriculum/challenges/chinese/01-responsive-web-design/responsive-web-design-projects/build-a-tribute-page.md) | [View English](https://raw.githubusercontent.com/freeCodeCamp/freeCodeCamp/master/curriculum/challenges/english/01-responsive-web-design/responsive-web-design-projects/build-a-tribute-page.md)

<details><summary>Show/Hide sections with changes/issues</summary>

- **`Description` section has changed**

</details>

---
- [ ] **Build a Technical Documentation Page** [Edit Chinese](https://github.com/freeCodeCamp/freeCodeCamp/edit/master/curriculum/challenges/chinese/01-responsive-web-design/responsive-web-design-projects/build-a-technical-documentation-page.md) | [View English](https://raw.githubusercontent.com/freeCodeCamp/freeCodeCamp/master/curriculum/challenges/english/01-responsive-web-design/responsive-web-design-projects/build-a-technical-documentation-page.md)

<details><summary>Show/Hide sections with changes/issues</summary>

- **`Description` section has changed**

</details>

---
- [ ] **Build a Product Landing Page** [Edit Chinese](https://github.com/freeCodeCamp/freeCodeCamp/edit/master/curriculum/challenges/chinese/01-responsive-web-design/responsive-web-design-projects/build-a-product-landing-page.md) | [View English](https://raw.githubusercontent.com/freeCodeCamp/freeCodeCamp/master/curriculum/challenges/english/01-responsive-web-design/responsive-web-design-projects/build-a-product-landing-page.md)

<details><summary>Show/Hide sections with changes/issues</summary>

- **`Description` section has changed**

</details>

---
- [ ] **Build a Personal Portfolio Webpage** [Edit Chinese](https://github.com/freeCodeCamp/freeCodeCamp/edit/master/curriculum/challenges/chinese/01-responsive-web-design/responsive-web-design-projects/build-a-personal-portfolio-webpage.md) | [View English](https://raw.githubusercontent.com/freeCodeCamp/freeCodeCamp/master/curriculum/challenges/english/01-responsive-web-design/responsive-web-design-projects/build-a-personal-portfolio-webpage.md)

<details><summary>Show/Hide sections with changes/issues</summary>

- **`Description` section has changed**

</details>

---
- [ ] **Build a Survey Form** [Edit Chinese](https://github.com/freeCodeCamp/freeCodeCamp/edit/master/curriculum/challenges/chinese/01-responsive-web-design/responsive-web-design-projects/build-a-survey-form.md) | [View English](https://raw.githubusercontent.com/freeCodeCamp/freeCodeCamp/master/curriculum/challenges/english/01-responsive-web-design/responsive-web-design-projects/build-a-survey-form.md)

<details><summary>Show/Hide sections with changes/issues</summary>

- **`Description` section has changed**

</details>

### PR DESCRIPTION
**Pull request by S1ngS1ng**
Checklist:

- [x] I have read [freeCodeCamp's contribution guidelines](https://contribute.freecodecamp.org).
- [x] My pull request has a descriptive title (not a vague title like `Update index.md`)
- [x] My pull request targets the `master` branch of freeCodeCamp.
- [x] All the files I changed are in the same world language, for example: only English changes, or only Chinese changes, etc.

Closes #40479

## Note
- Trailing space after `**Note:**` is removed
- `"Your code"` is disregarded in the translation. The updated translation constitutes a more objective description
- Several test cases are reverted. Now that test cases are aligned w/ that in the English version
    - @RandellDawson In the previous translation session, we altered some `instruction` as well as `tests`. For example:
        - Here is the [altered instruction](https://github.com/freeCodeCamp-China/learn/blob/master/curriculum/challenges/01-responsive-web-design/basic-html-and-html5.json#L133) as well as the [altered test case](https://github.com/freeCodeCamp-China/learn/blob/master/curriculum/challenges/01-responsive-web-design/basic-html-and-html5.json#L139)
        - Though, when the translation is ported here for the first time, looks like the altered test case is not picked up. See [here](https://github.com/freeCodeCamp/freeCodeCamp/blob/master/curriculum/challenges/chinese/01-responsive-web-design/basic-html-and-html5/fill-in-the-blank-with-placeholder-text.md)
        - While the altered `instruction` is retained, this ended up with discrepancies on both versions. Hence the revert.

Glossary:
- Element: [元素](https://developer.mozilla.org/zh-CN/docs/Glossary/%E5%85%83%E7%B4%A0)
- Enclosed content: [内容](https://developer.mozilla.org/zh-CN/docs/Learn/HTML/Introduction_to_HTML/Getting_started)
- Focus: [聚焦](https://developer.mozilla.org/zh-CN/docs/Web/HTML/Global_attributes/tabindex)
- Web Fonts: [Web 字体](https://developer.mozilla.org/zh-CN/docs/Learn/CSS/%E4%B8%BA%E6%96%87%E6%9C%AC%E6%B7%BB%E5%8A%A0%E6%A0%B7%E5%BC%8F/Web_%E5%AD%97%E4%BD%93)
- Block: 限制访问
- Viewport: [视口](https://developer.mozilla.org/zh-CN/docs/Glossary/Viewport)
- `should` syntax: 应存在
- Form Control/Widget: [表单部件](https://developer.mozilla.org/zh-CN/docs/Learn/HTML/Forms/The_native_form_widgets)
- Self-closing: 自闭和
- Closing tag: [结束标签](https://developer.mozilla.org/zh-CN/docs/Learn/HTML/Introduction_to_HTML/Getting_started)
- Font family: [字体族名](https://developer.mozilla.org/zh-CN/docs/Web/CSS/font-family)

### CODE REVIEW

**Comment by S1ngS1ng** [comment]
@miyaliu666 @ZhichengChen Please review this PR. Lemme know if we need an offline review session regarding this.

**Comment by RandellDawson** [comment]
I think we should all meet to discuss this PR.  I am not quite following what the issues are relating to the reverts.

**Comment by S1ngS1ng** [comment]
> I think we should all meet to discuss this PR. I am not quite following what the issues are relating to the reverts.

Sure. Let's sync up when we are all available. I should be available after 8 PM (PST) on weekdays.
@miyaliu666  @ZhichengChen Let me know what time would work for both of you.

**Comment by RandellDawson** [comment]
@S1ngS1ng @miyaliu666 So is this PR ready to be merged from a translation standpoint?

**Comment by S1ngS1ng** [comment]
> @S1ngS1ng @miyaliu666 So is this PR ready to be merged from a translation standpoint?

AFAIC, yes. But let's see if @miyaliu666 and @ZhichengChen would both approve this PR.
Any comments/concerns are welcome.

**Review by miyaliu666 — APPROVED** [review]

**Comment by miyaliu666** [comment]
All look good to me 👍

**Comment by RandellDawson** [comment]
@S1ngS1ng Thank you for your contribution to the page! 👍
We're happy to accept these changes, and look forward to future contributions. 🎉

**Pull request merged**
