### PR TITLE
Updated index.md to include TOC

### PR DESCRIPTION
**Pull request by GunnerJnr**
Added a table of contents for the user to easily navigate the index.md and jump to the relevant section.

- [x] I have read [freeCodeCamp's contribution guidelines](https://github.com/freeCodeCamp/freeCodeCamp/blob/master/CONTRIBUTING.md).
- [x] My pull request has a descriptive title (not a vague title like `Update index.md`)
- [x] My pull request targets the `master` branch of freeCodeCamp.
- [x] None of my changes are plagiarized from another source without proper attribution.
- [x] My article does not contain shortened URLs or affiliate links.

If your pull request closes a GitHub issue, replace the XXXXX below with the issue number.

Closes #XXXXX

### CODE REVIEW

**Comment by GunnerJnr** [comment]
added TOC for easier navigation of index.md

**Comment by RandellDawson** [comment]
Looks great!

**Comment by GunnerJnr** [comment]
> Looks great!

Thanks

**Comment by RandellDawson** [comment]
Hi @GunnerJnr. Congrats on your first pull request (PR)! 🎉

Thank you for your contribution to the page! 👍
We're happy to accept these changes, and look forward to future contributions. 📝

**Comment by RandellDawson** [comment]
Thank you for your contribution to the page! 👍
We're happy to accept these changes, and look forward to future contributions. 🎉

**Pull request merged**
