### PR TITLE
refactor(landing): migrate index to tsx

### PR DESCRIPTION
**Pull request by luqven**
This commit refactors `client/src/components/landing/index.js` component into a `React.FC` component. The file extension was changes from `js` to `.tsx`.

Related issue: #43778

Checklist:

- [x] I have read [freeCodeCamp's contribution guidelines](https://contribute.freecodecamp.org).
- [x] My pull request has a descriptive title (not a vague title like `Update index.md`)
- [x] My pull request targets the `main` branch of freeCodeCamp.
- [x] I have tested these changes either locally on my machine, or GitPod.

Tested this locally and the site builds without issues. As far as using `tsx` instead of `ts` for the file extension, I made a judgement call. I personally like using `jsx/tsx` whenever there's HTML alongside the JS in a React file.

One quick-question. Unsure as to what the `displayName` property is. Is that needed? I can check line 42 back in, I just wasn't sure what that was in reference to.

Thanks and looking forward to your comments and feedback 😄 🍂

### CODE REVIEW

**Review by ojeytonwilliams — CHANGES_REQUESTED** [review]
Hi @luqven, I wouldn't normally recommend changing code in a TS migration, but since this is relatively small change, I think this is fine.

By the way, the tests will need to be updated if we use `function Landing`, but if you run `npx jest` it should be reasonably clear.

Give me a shout if you need any more feedback.

**Comment by luqven** [comment]
> Hi @luqven, I wouldn't normally recommend changing code in a TS migration, but since this is relatively small change, I think this is fine.
> 
> By the way, the tests will need to be updated if we use `function Landing`, but if you run `npx jest` it should be reasonably clear.
> 
> Give me a shout if you need any more feedback.

Thanks for the feedback @ojeytonwilliams !

TIL about not using FC , good callout. Apols for the late turn around on this, addressing your comments now and will push up soon.

**Comment by ojeytonwilliams** [comment]
Hey @luqven do you think you'll have a moment to make those changes?

**Comment by luqven** [comment]
> Hey @luqven do you think you'll have a moment to make those changes?

Hey @ojeytonwilliams I meant to ping you a while back. I've been stuck on updating the tests

`expect(view.type.displayName === 'Landing').toBeTruthy();`

Took me an embarrasingly long time to realize I was missing this line

`Landing.displayName = 'Landing';` 🤦🏼 

Just pushed up some changes.

**Review by ojeytonwilliams — APPROVED** [review]
Hey @luqven I went ahead and renamed the file, I hope that's okay.

Anyways, this LGTM :+1:

**Comment by ojeytonwilliams** [comment]
> Took me an embarrasingly long time to realize I was missing this line

No worries!  It's totally cool to ping people if you're confused about something, though.  We're happy to help where we can.

**Review by moT01 — APPROVED** [review]
LGTM @luqven 🎉  Thanks for contributing to freeCodeCamp 🎉

**Pull request merged**
