### PR TITLE
fix(client): Header and buttons text made smaller

### PR DESCRIPTION
**Pull request by miksa1987**
- [x] I have read [freeCodeCamp's contribution guidelines](https://github.com/freeCodeCamp/freeCodeCamp/blob/master/CONTRIBUTING.md).
- [x] My pull request has a descriptive title (not a vague title like `Update index.md`)
- [x] My pull request targets the `master` branch of freeCodeCamp.
- [x] None of my changes are plagiarized from another source without proper attribution.
- [x] All the files I changed are in the same world language (for example: only English changes, or only Chinese changes, etc.)
- [x] My changes do not use shortened URLs or affiliate links.

This is a suggestion to make header and button fonts smaller and their margins smaller too, especially on front page and learn page. This is because on smaller screens it is easier to read everything without so much scrolling.

### CODE REVIEW

**Comment by ahmadabdolsaheb** [comment]
Hi @miksa1987, could you please add some before after screenshots to make it easier for reviewers?

**Comment by miksa1987** [comment]
Here's a screenshot, above is current and below is my suggestion.

beforeafter

**Comment by thecodingaviator** [comment]
Hi, @miksa1987 , while we absolutely welcome your PR, in the future, please consider opening an issue first. ✈️

**Comment by ahmadabdolsaheb** [comment]
thanks for the screens shots, the changes look good.

It seems like the changes would have site-wide affects which requires this pr to be reviewed in detail.

by looking at the changes, it seems like the medium titles and h2 might be undistinguishable from the rest of text.

h3 would also be smaller than regular text if I am not mistaken?

**Comment by miksa1987** [comment]
H2 seems to be distinguishable from the rest of the text by the quick look I took, I can investigate more tomorrow. 

H3 yes, seems to be mistake on my side, I can fix the size tomorrow and do a new PR.

Thanks for the comments!

**Comment by ahmadabdolsaheb** [comment]
Thank you,

if you could also look into instances where  h3 and .medium-heading is being used and check if they look alright on mobile it would be great.

alternatively, instead of changing the text size on all those elements we could change the elements used in the landing page/learn page to make sure we avoid unintentional side effects.

**Comment by miksa1987** [comment]
headers

Here is a screenshot of the donate page with h1 (Become a supporter), h3 (Duration and amount) and h4 (Need help ... ) headers. I think they turned out quite good. I tweaked the font sizes just slightly bigger so nothing would be under 1rem.

Does it look good to you?

**Comment by ahmadabdolsaheb** [comment]
Thanks for sharing the screenshot @miksa1987,

They look alright on large screens, but for smaller screens I see h3 going .8rm and medium-heading and h2 going 1rm. 

I was wondering if you were able to check the font sizes on smaller screens?

**Comment by miksa1987** [comment]
mobiletextandheaders

@ahmadabdolsaheb 
Here's couple screenshots of a mobile view of the same page, how it's supposed to look on Pixel 2. This is after I tweaked the headers a bit, h3 is now 1.1rem. If it looks ok I shall do a new pull request?

**Comment by ahmadabdolsaheb** [comment]
Thanks for the screen shots, @miksa1987. 
Please update this pr with your final tweaks for the final review.

**Comment by miksa1987** [comment]
@ahmadabdolsaheb I just pushed the commit. The pull request should be automatically updated? (I'm totally noob with pull requests)

**Comment by ojeytonwilliams** [comment]
>  The pull request should be automatically updated?

Yep, you're doing it right.  You can take a look at the 'Commits' tab at the top if you want to make 100% sure everything has worked (though it can take a minute or two to refresh).

**Comment by raisedadead** [comment]
Hi @miksa1987 nice work on the PR. Thanks a lot. Next time, I recommend giving the [guidelines for contributing](https://github.com/freeCodeCamp/freeCodeCamp/blob/master/CONTRIBUTING.md) a read. Right now, unless this PR is merged, you have a soiled copy of freeCodeCamp on your fork, because you used the master branch.

I would recommend, after this PR is accepted and merged you should force push to your fork's master following the guidelines.

Then on for future PRs, make a separate branch of off master.

**Review by ahmaxed — APPROVED** [review]

**Review by raisedadead — APPROVED** [review]

**Pull request merged**
