### PR TITLE
chore(i8n,learn): processed translations

### PR DESCRIPTION
**Pull request by naomi-lgbt**
Checklist:

- [ ] I have read [freeCodeCamp's contribution guidelines](https://contribute.freecodecamp.org).
- [ ] My pull request has a descriptive title (not a vague title like `Update index.md`)
- [ ] My pull request targets the `main` branch of freeCodeCamp.
- [ ] All the files I changed are in the same world language, for example: only English changes, or only Chinese changes, etc.

Closes #XXXXX

### CODE REVIEW

**Review by RandellDawson — DISMISSED** [review]
@raisedadead I reviewed through all 82 files (specifically the tests, seed code, and solutions changes) and they all match the current English (which we want), so I am fine with merging this PR.

**Comment by ojeytonwilliams** [comment]
If we do merge this, we should create another PR with all the Spanish files and merge that straight away.  Reason being, it's not great to have the Spanish in a broken and potentially confusing state.

**Comment by RandellDawson** [comment]
I am not sure what you mean by all the Spanish files.

**Comment by ojeytonwilliams** [comment]
Yeah, I could have been clearer.  I mean all the files that have been uploaded to Crowdin for translation.  We'd need another PR to pull all of those down.  As discussed in https://github.com/freeCodeCamp/freeCodeCamp/issues/40907 the `challenges/english` and `challenges/espanol` directories need to be mirrors of each other.

**Comment by nhcarrigan** [comment]
@RandellDawson as a heads up - we ran in to the issue where CI wouldn't fire on a PR created by the action.

It turns out, if the PR already exists and the action does a new commit (force pushed), the CI will also not fire. We'll want to ensure that we don't re-run the download with an outstanding PR.

**Comment by RandellDawson** [comment]
> It turns out, if the PR already exists and the action does a new commit (force pushed), the CI will also not fire. 

Well that is annoying.

**Comment by RandellDawson** [comment]
Can we add an additional step into the download workflow to prevent the rest of the steps from executing if the branch already exists?

**Comment by nhcarrigan** [comment]
We could look in to that, yeah

**Comment by raisedadead** [comment]
Closing as discussed in chat.

**Pull request closed without merging**
