### PR TITLE
fix: show fsd superblock in development

### PR DESCRIPTION
**Pull request by ojeytonwilliams**
Checklist:

- [x] I have read and followed the [contribution guidelines](https://contribute.freecodecamp.org).
- [x] I have read and followed the [how to open a pull request guide](https://contribute.freecodecamp.org/how-to-open-a-pull-request/).
- [x] My pull request targets the `main` branch of freeCodeCamp.
- [x] I have tested these changes either locally on my machine, or GitPod.

### CODE REVIEW

**Review by Sembauke — APPROVED** [review]

**Review by Ksound22 — APPROVED** [review]

**Comment by ilenia-magoni** [comment]
are the failed tests something to worry about?

**Comment by Ksound22** [comment]
> are the failed tests something to worry about?

I believe PRs with failing E2E CIs can go in.

Oliver is in a better place to confirm that.

**Review by naomi-lgbt — CHANGES_REQUESTED** [review]
> I believe PRs with failing E2E CIs can go in.

Sure, when the E2E failures are due to a flaky test unrelated to the changes. But that's not what is happening here.

It looks like the block is being displayed when the tests run, resulting in the mismatch between the expected number of blocks and the actual render.

**Comment by ojeytonwilliams** [comment]
Yep, that's right, thanks Naomi.

I'll take a look at those failures now.

**Comment by ojeytonwilliams** [comment]
@naomi-lgbt I've cleared out a little of the repetition and the tests should pass now.

It's a little awkward since they're testing `SHOW_UPCOMING_CHANGES===false` and `useFeature('fcc-10').on === true`, i.e.  what we would deploy, were we to turn on the growthbook flag, not what we actually deploy.

If I have time, I'll come up with a way to test both without duplicating the entire test suite and bogging down our CI. For now, though, I think this is the least bad option.

**Review by naomi-lgbt — APPROVED** [review]

**Pull request merged**
