### PR TITLE
fix(challenge): Improve tests for Circular Queue challenge.

### LINKED ISSUE #13303: [beta] Improve tests for "Coding Interview Data Structure Questions: How to Create a Circular Queue"
Challenge [how-to-create-a-circular-queue](http://beta.freecodecamp.com/en/challenges/coding-interview-data-structure-questions/how-to-create-a-circular-queue) has an issue.

[These lines](https://github.com/freeCodeCamp/freeCodeCamp/blob/staging/seed/challenges/08-coding-interview-questions-and-take-home-assignments/coding-interview-data-structure-questions.json#L217-L218) misspell `CircularQueue` as `CircularQueuee`, which breaks tests.

I'll submit a quick PR for this right away.

### PR DESCRIPTION
**Pull request by Greenheart**
#### Pre-Submission Checklist

- [x] Your pull request targets the `staging` branch of freeCodeCamp.
- [x] Branch starts with either `fix/`, `feature/`, or `translate/` (e.g. `fix/signin-issue`)
- [x] You have only one commit (if not, [squash](http://forum.freecodecamp.com/t/how-to-squash-multiple-commits-into-one-with-git/13231) them into one commit).
- [x] All new and existing tests pass the command `npm test`. Use `git commit --amend` to amend any fixes.

#### Type of Change

- [x] Small bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds new functionality)
- [ ] Breaking change (fix or feature that would change existing functionality)
- [ ] Add new translation (feature adding new translations)

#### Checklist:

- [x] Tested changes locally.
- [x] Closes currently open issue (replace XXXX with an issue no): Closes #13303 

#### Description

* Fix some typos that prevented valid solutions from passing.
* Add new test cases to better test for what the instructions ask for.
* Improve test-messages.
* Add passing solution, to increase coverage of `npm test`.

### CODE REVIEW

**Comment by dhcodes** [comment]
@Greenheart can you PM me your successful code for this on Gitter? I've written what I think is decent code but it doesn't pass the tests.

Thanks.

**Comment by Greenheart** [comment]
@dhcodes I'll post it here if anyone else is interested.

I use `JSON.stringify()` to prepare code to be posted in `solutions`
and then `console.log()` to print it with proper formatting again. It makes it pretty convenient to test things :blush:

```js
class CircularQueue {
  constructor () {
    this._cq = ['', '', '', '', ''];
    this._reader = 0;
    this._writer = 0;
  }
  
  printCollection () {
    return this._cq;
  }
  
  _updatePointer (id) {
    if (++this[id] === this._cq.length) {
      this[id] = 0;
    }
  }
  
  enqueue (item) {
    if (Array.isArray(item)) {
      for (const x of item) {
        this.enqueue(x);
      }

      return;
    }
    
    this._cq[this._writer] = item;
    
    this._updatePointer('_writer');
  }
  
  dequeue () {
    const item = this._cq[this._reader];
    this._cq[this._reader] = '';
    
    this._updatePointer('_reader');
    return item;
  }
  
  front () {
    return this._cq[this._reader];
  }
}
```

**Comment by dhcodes** [comment]
I'm sort of mixed up in the directions so I'll let someone else QA.

**Review by raisedadead — COMMENTED** [review]
@Greenheart 

While you are at this, can you change the `"Instructions:",` to a `<hr>`

Also, while going thru the challenge, I felt the instructions part should be more clear and in tune with what the tests want, for instance they should state creating the necessary methods in the class as tested in the test cases.

Well these can be taken in a separate PR if you prefer?

**Comment by Greenheart** [comment]
@raisedadead Good points! I don't know if we've got a separate issue for this (I'll see what I can find), but I think it's better to fix this in a separate PR.

**Comment by Greenheart** [comment]
@raisedadead I didn't find any issues for this. Could you open one with your suggested changes and tag me there so we could discuss and fix it? :blush:

**Comment by raisedadead** [comment]
Sounds, good to me. Will do the needful.

**Pull request merged**
