### PR TITLE
fix: rename guide folders [arabic]

### PR DESCRIPTION
**Pull request by moT01**
This renames guide folders to align with lesson titles by changing the dashes(`-`) back to periods(`.`) where they have been previously replaced for the arabic guide.

- [x] I have read [freeCodeCamp's contribution guidelines](https://github.com/freeCodeCamp/freeCodeCamp/blob/master/CONTRIBUTING.md).
- [x] My pull request has a descriptive title (not a vague title like `Update index.md`)
- [x] My pull request targets the `master` branch of freeCodeCamp.
- [x] None of my changes are plagiarized from another source without proper attribution.
- [x] All the files I changed are in the same world language (for example: only English changes, or only Chinese changes, etc.)
- [x] My changes do not use shortened URLs or affiliate links.

Related to issue https://github.com/freeCodeCamp/freeCodeCamp/issues/35155

### CODE REVIEW

**Comment by moT01** [comment]
Reviewers, make sure there are no other PR's to these files before merging. Check the [contributor tools](https://contribute.freecodecamp.org/dashboard/)

**Comment by RandellDawson** [comment]
The following PR has changes to the old filename, so wait until it has been merged before merging this PR.
#34955

**Comment by ValeraS** [comment]
@RandellDawson Changes to challenge files in #34955 are made as an example and should not block this PR.

**Comment by RandellDawson** [comment]
@ValeraS That is fine.  Since we can not test the non-English versions of the challenges, should we wait on this and the other non-English languages until we can validate the links will go to the correct challenges. We could manually validate the corresponding non-English guide article has the same filename as a way to "test" the link "should" work.  What do you think?

**Comment by ValeraS** [comment]
Manually or try to use a script from that PR to fix challenges locally and check on them.

**Comment by RandellDawson** [comment]
LGTM - I first checked there are currently no open PRs making changes to the old filename.  I also manually validated, that all the new filenames of the Guide articles match the same naming convention of the the current `master` branch curriculum filename.

**Comment by RandellDawson** [comment]
Thank you for your contribution to the page! 👍
We're happy to accept these changes, and look forward to future contributions. 🎉

**Pull request merged**
