### PR TITLE
fix(client): typo in APIs and Microservices Projects intro

### PR DESCRIPTION
**Pull request by heysujal**
Checklist:

- [x] I have read [freeCodeCamp's contribution guidelines](https://contribute.freecodecamp.org).
- [x] My pull request has a descriptive title (not a vague title like `Update index.md`)
- [x] My pull request targets the `main` branch of freeCodeCamp.
- [x] All the files I changed are in the same world language, for example: only English changes, or only Chinese changes, etc.

I fixed the typo in [APIs and Microservices Projects introduction](https://www.freecodecamp.org/learn/apis-and-microservices/#apis-and-microservices-projects)

fcc

Error can be found at line 315 of [client/i18n/locales/english/intro.json](https://github.com/freeCodeCamp/freeCodeCamp/blob/main/client/i18n/locales/english/intro.json#L315) and line 336 of [client/i18n/locales/espanol/intro.json](https://github.com/freeCodeCamp/freeCodeCamp/blob/main/client/i18n/locales/espanol/intro.json#L336)

### CODE REVIEW

**Comment by gikf** [comment]
Hey @heysujal

could you revert changes made to the Espanol locale? Non-English files should not be changed directly, if needed, they will be updated using the translating workflow.

**Comment by heysujal** [comment]
@gikf  Hey reverted my change by making another commit.

**Review by gikf — APPROVED** [review]
Looks good :+1:

**Review by raisedadead — APPROVED** [review]

**Comment by raisedadead** [comment]
#### :sparkles: :sparkles: **AWESOME! LGTM.** :sparkles: :sparkles: 

Thanks, @heysujal, for this pull request and for contributing to the code-base for the first time.

We will be looking forward to more contributions in future.

Cheers and happy contributing!

**Pull request merged**
