### PR TITLE
feat: optimize head tags

### PR DESCRIPTION
**Pull request by ahmaxed**
closes: #40596

### CODE REVIEW

**Comment by nhcarrigan** [comment]
Is the em-dash in `Learn to Code - for Free` not going to hurt our SEO?

I'm not 100% sure how Google parses that when I search for "learn to code for free".

**Comment by raisedadead** [comment]
Did you also want to handle the seemingly arbitrary CSS sources in this PR being introduced here:

https://github.com/freeCodeCamp/freeCodeCamp/blob/d23feadc1f000fdeb8d3ef994157bfeef8d233be/client/src/html.js#L15-L16

**Comment by ahmadabdolsaheb** [comment]
> Is the em-dash in `Learn to Code - for Free` not going to hurt our SEO?
> 
> I'm not 100% sure how Google parses that when I search for "learn to code for free".

let's pick up this discussion on core chat.

**Comment by ahmadabdolsaheb** [comment]
> freeCodeCamp/client/src/html.js

**Comment by raisedadead** [comment]
We should re target this non-critical PR to the next branch.

**Comment by ahmadabdolsaheb** [comment]
Sure, I will make a another pr to address the title description changes on master.

**Comment by ahmadabdolsaheb** [comment]
the title and description has been altered and might need re translation. ( it might not need to if we are not aiming for a 1:1 translation )
Also would we need the social description tags to be translated and added to translation files?

**Comment by raisedadead** [comment]
> the title and description has been altered and might need re translation. ( it might not need to if we are not aiming for a 1:1 translation )

You should add the English copy to the translated files, which should eventually get noticed and replaced.

> Also would we need the social description tags to be translated and added to translation files?

Yes, similar as above.

**Review by raisedadead — APPROVED** [review]

**Pull request merged**
