### PR TITLE
Added some info on recursion

### PR DESCRIPTION
**Pull request by MattyBear**
May be important info for some

- [x] I have read [freeCodeCamp's contribution guidelines](https://github.com/freeCodeCamp/freeCodeCamp/blob/master/CONTRIBUTING.md).
- [x] My pull request has a descriptive title (not a vague title like `Update index.md`)
- [x] My pull request targets the `master` branch of freeCodeCamp.
- [x] None of my changes are plagiarized from another source without proper attribution.
- [x] My article does not contain shortened URLs or affiliate links.

If your pull request closes a GitHub issue, replace the XXXXX below with the issue number.

Closes #XXXXX

### CODE REVIEW

**Review by CodingSolo — COMMENTED** [review]
Thank you for your PR but the changes you have made does not improve the article.

**Comment by moT01** [comment]
Why doesn't that improve it @CodingSolo ?

**Comment by CodingSolo** [comment]
@moT01 I found [very similar text](https://jatinmandav.wordpress.com/2017/01/18/recursion/) and don't like this sentence : 

> If the speed of the program is important then you may not want to use recursion as it uses more memory and can slow the program down.

it's an affirmation without explanation.
But why not ?  it's better than other PR.

**Comment by moT01** [comment]
I hear what you're saying @CodingSolo - it's definitely not a copy from your source, some similar elements but I think it's unique enough - this is from the moderator post on the forum...
```
Guide Edits: These are text changes to guide articles. You can review these right on GitHub and decide whether to merge them. If these pull requests seem to improve an article - by fixing grammatical or factual errors, adding additional details, or adding relevant links or images - you should err on the side of merging them.
```
Things could always be better but I think it's good enough to be added. Thanks for looking into it.

**Comment by moT01** [comment]
Congratulations on your first contribution to freeCodeCamp @MattyBear! We look forward to future contributions!

**Pull request merged**
