### PR TITLE
Clearer explanation of PR details & review process

### PR DESCRIPTION
**Pull request by anthonyjvoss**
Made an edit to the PR process to more clearly indicate adding details and the subsequent review for approval and merge.

- [x] I have read [freeCodeCamp's contribution guidelines](https://github.com/freeCodeCamp/freeCodeCamp/blob/master/CONTRIBUTING.md).
- [x] My pull request has a descriptive title (not a vague title like `Update index.md`)
- [x] My pull request targets the `master` branch of freeCodeCamp.
- [x] None of my changes are plagiarized from another source without proper attribution.
- [x] All the files I changed are in the same world language (for example: only English changes, or only Chinese changes, etc.)
- [x] My changes do not use shortened URLs or affiliate links.

Closes #XXXXX

### CODE REVIEW

**Comment by anthonyjvoss** [comment]
@raisedadead  - any chance you could provide more feedback on why this was marked as 'invalid'?  I thought these updates were worthwhile improvements to make these instructions easier to follow.

**Comment by raisedadead** [comment]
Yes, we were unable to merge (as a policy) the PR because the fork was deleted, which doesnt let us push changes to the PR.

You are wlecome to make a fresh PR.

**Comment by anthonyjvoss** [comment]
That's really strange, I do not recall deleting the fork.  I will work on getting this re-submitted.  Thank you!

**Comment by raisedadead** [comment]
Sure thing. Thanks for contributing.

**Pull request closed without merging**
