### PR TITLE
updated the tests to avoid confusion issue-15012

### LINKED ISSUE #15012: Passing this challenge is very tricky - this can cause confusion
Challenge [create-a-more-complex-shape-using-css-and-html](https://beta.freecodecamp.com/en/challenges/applied-visual-design/create-a-more-complex-shape-using-css-and-html) has an issue.
User Agent is: <code>Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/58.0.3029.110 Safari/537.36</code>.
Please describe how to reproduce this issue, and include links to screenshots if possible.

```html


<style>
.heart {
  position: absolute;
  margin: auto;
  top: 0;
  right: 0;
  bottom: 0;
  left: 0;
  background-color: pink;
  height: 50px;
  width: 50px;
  transform: rotate(-45deg);
}
.heart:after {
  background-color: pink;
  content: "";
  border-radius: 50%;
  position: absolute;
  width: 50px;
  height: 50px;
  top: 0px;
  left: 25px;
}
.heart:before {
  content: "";  // when you add any extra space outside the empty string will not pass this challenge
  background-color: pink;
  border-radius: 50%;
  position: absolute;
  width: 50px;
  height: 50px;
  top: -25px;
  left: 0px;
}
</style>
<div class = "heart"></div>

```

**content: "";  // when you addany extra space outside the empty string will not pass this challenge. Can't you add any whitespace?**

### PR DESCRIPTION
**Pull request by prateek3255**
#### Pre-Submission Checklist

- [x] Your pull request targets the `staging` branch of freeCodeCamp.
- [x] Branch starts with either `fix/`, `feature/`, or `translate/` (e.g. `fix/signin-issue`)
- [x] You have only one commit (if not, [squash](http://forum.freecodecamp.org/t/how-to-squash-multiple-commits-into-one-with-git/13231) them into one commit).
- [x] All new and existing tests pass the command `npm test`. Use `git commit --amend` to amend any fixes.

#### Type of Change

- [x] Small bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds new functionality)
- [ ] Breaking change (fix or feature that would change existing functionality)
- [ ] Add new translation (feature adding new translations)

#### Checklist:

- [x] Tested changes locally.
- [x] Addressed currently open issue (replace XXXXX with an issue no in next line)

Closes #15012 

#### Description
I have updated the tests so that the tests work even if there is space before or after : and space after "" or any other value.

### CODE REVIEW

**Comment by prateek3255** [comment]
I have updated the tests for the issue #15012 so that the test work even if there is space before or after `:` and space after `""` or any other value.

**Comment by prateek3255** [comment]
@ahmadabdolsaheb can you please review my PR because of it been 5 days since it has been marked ready for QA and there is no progress yet.

**Comment by scissorsneedfoodtoo** [comment]
@prateek3255, thank you for submitting a PR to fix this issue. Sorry for the delay.

We're currently in the process of moving all updates to the curriculum over to a separate repository, so your PR is blocked for now. I checked it out and everything LGTM! Just made one small change to allow for possible spaces between the parentheses and `-45deg`.

@raisedadead, myself, or any other members will merge things are ready with the new repo.

**Comment by raisedadead** [comment]
Hi @prateek3255 

Thanks a lot for this pull request. We sincerely appreciate the time and efforts put into this. 

However can you please make the same changes once again on the https://github.com/freeCodeCamp/curriculum repository?

I would like to apologise for the inconvenience, but at this point it has become very difficult to carry over commits into the other repo, to which we have moved over the entire curriculum package.

Thanks once again. 

Please reach out to us in the [Contributors Chat room](https://gitter.im/FreeCodeCamp/Contributors) for any assistance.

Happy contributing!

**Comment by prateek3255** [comment]
Yeah sure, I would make those changes in https://github.com/freeCodeCamp/curriculum repository as soon as I can.

**Comment by prateek3255** [comment]
@raisedadead I have submitted [#57](https://github.com/freeCodeCamp/curriculum/pull/57) pull request with the same changes in the https://github.com/freeCodeCamp/curriculum repository.

**Comment by raisedadead** [comment]
@prateek3255 Thanks a lot for the updates.

**Comment by prateek3255** [comment]
@raisedadead there is one more problem, the Travis CI tests are failing on that repo even when I made the exact same changes in my commit.

**Comment by raisedadead** [comment]
OK no worries, I'll comment there after I am able to take a look.

**Comment by prateek3255** [comment]
@raisedadead I have fixed the Travis CI test failing issue ( I just had to change my commit message to `fix(challenge): ...` ) thanks to the [Contributors Chat room](https://gitter.im/FreeCodeCamp/Contributors).
Now I think that it is ready to be merged.

**Pull request closed without merging**
