### PR TITLE
feat: only remove comments when specified in the test

### PR DESCRIPTION
**Pull request by ojeytonwilliams**
- feat: stop removing comments by default
- fix: manually removeJSComments in some challenges
- fix: use helper in more challenges

Checklist:

- [x] I have read and followed the [contribution guidelines](https://contribute.freecodecamp.org).
- [x] I have read and followed the [how to open a pull request guide](https://contribute.freecodecamp.org/#/how-to-open-a-pull-request).
- [x] My pull request targets the `main` branch of freeCodeCamp.
- [x] I have tested these changes either locally on my machine, or GitPod.

Closes #XXXXX

### CODE REVIEW

**Comment by ojeytonwilliams** [comment]
@freeCodeCamp/mobile could you confirm that the schema change is okay?

**Comment by Nirajn2311** [comment]
> @freeCodeCamp/mobile could you confirm that the schema change is okay?

Yup, they're good to go from the mobile perspective.

**Review by naomi-lgbt — APPROVED** [review]
Tests are failing because challenges will need to be synced. Will monitor this and manually run upload/download when merged.

**Comment by ojeytonwilliams** [comment]
Thanks, Naomi. If I'm around when it's merged, I'll try and remember to sync.

**Review by moT01 — APPROVED** [review]
LGTM 🎉

**Comment by moT01** [comment]
I might have rushed this one a little.

This stops removing comments by default @ojeytonwilliams? If so, that will change the tests for many of the other challenges - in the new JS specifically, but probably all over. Do we think that's an issue? Like maybe users will pass a test with commented out code or something.

Also, I did a quick search in the old JS and found these challenges didn't get the helper added to one or more of their tests:

accessing-nested-objects
declare-a-read-only-variable-with-the-const-keyword
create-strings-using-template-literals
use-arrow-functions-to-write-concise-anonymous-functions
use-getters-and-setters-to-control-access-to-an-object
use-destructuring-assignment-with-the-rest-parameter-to-reassign-array-elements
write-arrow-functions-with-parameters
make-a-person

Perhaps it didn't need to get added to those.

**Comment by ojeytonwilliams** [comment]
@moT01 I'm not _too_ fussed about the older JS stuff, but I do agree that the new JS lessons need updating. I'll do that now.

**Pull request merged**
