### PR TITLE
refactor: Basic Algorithm Scripting

### PR DESCRIPTION
**Pull request by ncaron**
#### Pre-Submission Checklist

- [x] Your pull request targets the `staging` branch of freeCodeCamp.
- [x] Branch starts with either `fix/`, `feature/`, or `translate/` (e.g. `fix/signin-issue`)
- [x] You have only one commit (if not, [squash](http://forum.freecodecamp.org/t/how-to-squash-multiple-commits-into-one-with-git/13231) them into one commit).
- [x] All new and existing tests pass the command `npm test`. Use `git commit --amend` to amend any fixes.

#### Type of Change

- [ ] Small bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds new functionality)
- [ ] Breaking change (fix or feature that would change existing functionality)
- [ ] Add new translation (feature adding new translations)
- [x] Refactor existing code

#### Checklist:

- [x] Tested changes locally.
- [x] Addressed currently open issue (replace XXXXX with an issue no in next line)

Part of #16325

#### Description

Important: If some of the following changes are not approved or if there's more to be done, please provide feedback so I can change them and apply the accepted changes when I work on converting the other sections to ES6.

ES6
* Change `var` to `let` or `const`
* Change callback functions to use arrow syntax

STYLE
* Change some single quotes to double quotes
  * Most challenges were using double quotes already while few had single quotes
  * Empty strings will keep their single quotes
* Add function call to solution
  * Some challenge solutions have the function call while some didn't. Now it is more consistent.
* Restyled solution code [See note 1]
  * Some challenges have comments but most solutions have them removed. They are now removed from all solutions to make them more consistent.
  * Some solutions didn't have new lines between blocks of code. This has been fixed.
  * Some solutions don't have spaces around operators `(i,i+1)` while most do `(i, i + 1)`. Now, they all do.
  * Some solutions didn't follow the style found [here](https://forum.freecodecamp.org/t/free-code-camp-javascript-style-guide/19121)
    * eg.  `if (num < 0) return '';` Had no curly brackets

NOTES
1. I'm not sure where the solution is displayed(if at all) but this makes them easier to read if they are.

### CODE REVIEW

**Comment by ncaron** [comment]
Maybe the guidelines should be updated. It only mentions this about branch names:

> Name the branch something like fix/xxx or feature/xxx

It doesn't mention the others and the `something` word made me think my branch name was appropriate especially since it is an accepted one for commit titles.

**Review by Jinxzone — COMMENTED** [review]
I file changed

**Comment by Jinxzone** [comment]
It was working

**Review by raisedadead — APPROVED** [review]

**Comment by raisedadead** [comment]
#### :sparkles: :sparkles: **LGTM.** :sparkles: :sparkles: 

Thanks @ncaron , sorry about being so late in reviewing this.

Happy Contributing!

**Pull request merged**
