### PR TITLE
Updated Cross Multiply with definition and example

### PR DESCRIPTION
**Pull request by JakeGerber**
- [x] I have read [freeCodeCamp's contribution guidelines](https://github.com/freeCodeCamp/freeCodeCamp/blob/master/CONTRIBUTING.md).
- [x] My pull request has a descriptive title (not a vague title like `Update index.md`)
- [x] My pull request targets the `master` branch of freeCodeCamp.
- [x] None of my changes are plagiarized from another source without proper attribution.
- [x] My article does not contain shortened URLs or affiliate links.

If your pull request closes a GitHub issue, replace the XXXXX below with the issue number.

Closes #XXXXX

### CODE REVIEW

**Review by bikingbadger — CHANGES_REQUESTED** [review]
I would maybe suggest using different numbers instead of both having 3, might just make for easier understanding

**Review by thecodingaviator — APPROVED** [review]
LGTM 👍

**Comment by RandellDawson** [comment]
Thank you for your contribution to the page! 👍
We're happy to accept these changes, and look forward to future contributions. 🎉

**Comment by RandellDawson** [comment]
@bikingbadger The PR was good enough, because there was no example before.  I do like your idea of changing one of the denominators to something other than `3`.  Feel free to create a new PR with your suggestion.

**Pull request merged**
