### PR TITLE
test: login more directly

### PR DESCRIPTION
**Pull request by ojeytonwilliams**
@raisedadead I was going to comment out the tests that were failing, but I realised it was always `cy.login()` that failed. That's used in an awful lot of the tests, so I tried re-writing it.

I'm not keen on turning off the tests right now, not while we're making so many big changes.

### CODE REVIEW

**Review by raisedadead — COMMENTED** [review]
No worries, while you are here can you update the workflow jobs to not "fail-fast"? See: https://docs.github.com/en/actions/learn-github-actions/workflow-syntax-for-github-actions#jobsjob_idstrategyfail-fast

**Comment by ojeytonwilliams** [comment]
> No worries, while you are here can you update the workflow jobs to not "fail-fast"? See: https://docs.github.com/en/actions/learn-github-actions/workflow-syntax-for-github-actions#jobsjob_idstrategyfail-fast

Sure, did you want that for all the strategies?  If it was just Cypress, let me know and I'll revert the others.

**Comment by raisedadead** [comment]
> Sure, did you want that for all the strategies?

Not really, but now that you have added it - I think it's fine.

**Comment by ojeytonwilliams** [comment]
@raisedadead I've finally squashed all the bugs. Hopefully this will make a difference.

**Review by raisedadead — APPROVED** [review]

**Comment by raisedadead** [comment]
>  I've finally squashed all the bugs. Hopefully this will make a difference.

If this works, you know I owe you a few 🍻 !

**Comment by ojeytonwilliams** [comment]
I'll take you up on that!

**Pull request merged**
