### PR TITLE
fixes typo in line 1769, changes "bracket" to "brackets"

### PR DESCRIPTION
**Pull request by LeeWarnock**
#### Pre-Submission Checklist

- [x] Your pull request targets the `staging` branch of FreeCodeCamp.
- [ ] Branch starts with either `fix/`, `feature/`, or `translate/` (e.g. `fix/signin-issue`)
- [x] You have only one commit (if not, [squash](https://github.com/FreeCodeCamp/FreeCodeCamp/wiki/Git-Squash) them into one commit).
- [ ] All new and existing tests pass the command `npm run test-challenges`. Use `git commit --amend` to amend any fixes.
#### Type of Change

- [x] Small bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds new functionality)
- [ ] Breaking change (fix or feature that would change existing functionality)
- [ ] Add new translation (feature adding new translations)
#### Checklist:

- [ ] Tested changes locally.
- [x] Closes currently open issue (replace XXXX with an issue no): Closes #XXXX

### CODE REVIEW

**Comment by atjonathan** [comment]
@LeeWarnock, unfortunately 2 pull requests were created at the same time. The other pull request author (@sergroja) already asked if he could fix that issue. I will have to accept his insead, sorry about that :disappointed:

**Comment by LeeWarnock** [comment]
thanks @atjonathan for the explanation. I'll just have to be quicker next time.

**Comment by atjonathan** [comment]
@LeeWarnock, no worries man, sorry about that :sob:

**Comment by LeeWarnock** [comment]
lol, making me laugh @atjonathan, I'm happy to be a part of this community! Are pull requests the only way to become a member?

**Comment by atjonathan** [comment]
@LeeWarnock, you mean a core team member of freecodecamp? You would need to talk to @BerkeleyTrue about that. Active contributing and helping out in chat rooms, repo, and other freecodecamp related projects are all factors.

**Pull request closed without merging**
