### PR TITLE
fix(curriculum): wrap logo in a code block

### LINKED ISSUE #47015: Missing code block around the hint in step 21 of building a piano project
### Describe the Issue

in step 21 of building a piano project, the hint in line 30 is missing code blocks

> Your `img` element should have a `class` set to logo. 

This should be changed to

> Your `img` element should have a `class` set to `logo`. 

https://github.com/freeCodeCamp/freeCodeCamp/blob/343b7f70eede56860097df1ea7a9f9d60146ee7e/curriculum/challenges/english/14-responsive-web-design-22/learn-responsive-web-design-by-building-a-piano/612eaf56b7ba3257fdbfb0db.md#L29-L31

### Additional context

If you would like to fix this issue, please make sure you read [our guidelines for contributing](https://contribute.freecodecamp.org/#/), we prioritize contributors following the instructions in our guides. Join us in [our chat room](https://chat.freecodecamp.org/channel/contributors) or [the forum](https://forum.freecodecamp.org/c/contributors/3) if you need help contributing, our moderators will guide you through this.

Sometimes we may get more than one pull requests. We typically accept the most quality contribution, followed by the one that is made first.

Happy contributing.

### PR DESCRIPTION
**Pull request by DylanDevelops**
…sed to be.

Checklist:

- [x] I have read [freeCodeCamp's contribution guidelines](https://contribute.freecodecamp.org).
- [x] My pull request has a descriptive title (not a vague title like `Update index.md`)
- [x] My pull request targets the `main` branch of freeCodeCamp.
- [x] I have tested these changes either locally on my machine, or GitPod.

Closes #47015

### CODE REVIEW

**Review by Sboonny — APPROVED** [review]
You have forgotten to create a branch, other than that.

#### :sparkles: :tada: **AWESOME!** :tada: :sparkles:

 Hi @DylanDevelops, thanks for this pull request and for contributing to the code-base for the first time. We are looking forward to more contributions from you in the future.

 Cheers & happy contributing!

**Review by gikf — APPROVED** [review]
LGTM :+1:

**Comment by DylanDevelops** [comment]
> You have forgotten to create a branch, other than that.
> 
> #### ✨ 🎉 **AWESOME!** 🎉 ✨
> Hi @DylanDevelops, thanks for this pull request and for contributing to the code-base for the first time. We are looking forward to more contributions from you in the future.
> 
> Cheers & happy contributing!

When I create a branch do I just name it anything? Like could I name my branch, DylanDevs-patches or something like that or how exactly do I work with that. Branches are still a bit confusing to me.

**Comment by gikf** [comment]
It is recommended to make changes on a separate branch, than the `main` branch. See more about it in point 3 at https://contribute.freecodecamp.org/#/how-to-setup-freecodecamp-locally?id=making-changes-locally.

**Pull request merged**
