### PR TITLE
Add solution d3challenges

### PR DESCRIPTION
**Pull request by prayagd**
- [x] I have read [freeCodeCamp's contribution guidelines](https://github.com/freeCodeCamp/freeCodeCamp/blob/master/CONTRIBUTING.md).
- [x] My pull request has a descriptive title (not a vague title like `Update index.md`)
- [x] My pull request targets the `master` branch of freeCodeCamp.
- [x] None of my changes are plagiarized from another source without proper attribution.
- [x] All the files I changed are in the same world language (for example: only English changes, or only Chinese changes, etc.)
- [x] My changes do not use shortened URLs or affiliate links.

Closes #XXXXX

### CODE REVIEW

**Review by moT01 — CHANGES_REQUESTED** [review]
I'm not sure if it's a big deal, but I think we should change all the ` ```js ` to ` ```html ` since it's technically all wrapped in html.

It would be nice to format everything a little better as well. But since the seed code isn't, we can probably save that for another PR or something.

All the solutions look good to me 🎉 

If/when we merge this, someone could probably go through and add all these to the guide.

**Review by moT01 — APPROVED** [review]
LGTM 🎉  I added these to the guide for the ones that didn't already have solutions.

**Review by ShaunSHamilton — APPROVED** [review]
LGTM 👍

**Comment by moT01** [comment]
Thanks for contributing to freeCodeCamp @prayagd 🎉

**Comment by prayagd** [comment]
✌

**Pull request merged**
