### PR TITLE
'Bug' button not working in Es6 challenges

### LINKED ISSUE #15740: 'Bug' button not working in Es6 challenges
#### Challenge Name

All ES6 Challenges

#### Issue Description

Bug button not working

#### Browser Information

* Browser Name, Version: Chrome Version 59.0.3071.115 (Official Build) (64-bit)
OSX
* Operating System: MacOS Sierra 10.12.3 (16D32)
* Mobile, Desktop, or Tablet: Desktop

#### Your Code

```js



```

### PR DESCRIPTION
**Pull request by Nevillealee**
bug btn now sends user to github submit new issue url  .
BREAKING CHANGE: none

Closes #15740

fix(challenges): Fixed bug button in tool panel to redirect user to

report bug button on ES6 challneges wouldnt do anything when clicked

BREAKING CHANGE: none

Closes #15740

#### Pre-Submission Checklist

- [x ] Your pull request targets the `staging` branch of freeCodeCamp.
- [ x] Branch starts with either `fix/`, `feature/`, or `translate/` (e.g. `fix/signin-issue`)
- [ x] You have only one commit (if not, [squash](http://forum.freecodecamp.com/t/how-to-squash-multiple-commits-into-one-with-git/13231) them into one commit).
- [x ] All new and existing tests pass the command `npm test`. Use `git commit --amend` to amend any fixes.

#### Type of Change

- [ x] Small bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds new functionality)
- [ ] Breaking change (fix or feature that would change existing functionality)
- [ ] Add new translation (feature adding new translations)

#### Checklist:

- [x ] Tested changes locally.
- [ x] Closes currently open issue (replace XXXX with an issue no): Closes #15740 

#### Description

the report bug button in the ES6 challenges wasnt performing any action when pressed. I went into app\route\challenges\views\classic\Tool-Panel.jsx and changed line 137 to an href tag that redirects the user to https://github.com/freeCodeCamp/freeCodeCamp/issues/new so they can report a bug. I also added the attribute:  target='blank' on line 138 so the github url would open in a new tab.

### CODE REVIEW

**Comment by Nevillealee** [comment]
Thank you for the information. I may have accidentally included that issue number (wrong number, fix is for 15740) by copying and pasting the issue subject.  I look forward to learning more and becoming a regular contributor. Thank you!!

Sent from Mail for Windows 10

**Comment by BerkeleyTrue** [comment]
Thanks but the bug button should open the modal. If the issue is that the bug modal is not opening then the solutions is not to add a hardlink to github issues.

Happy Coding

**Comment by Nevillealee** [comment]
Hello,

Thank you for the feedback. I tried to get clarification on glitter and
github and the only response was from github stating it should point
directly to github. I appreciate you clearing up my confusion

Best,

Neville lee

**Comment by w96k** [comment]
The bug still exists.

**Comment by Nevillealee** [comment]
Is it a bootstrap modal? How does it work?

**Pull request closed without merging**
