### PR TITLE
feat: Breadcrumbs in help text

### LINKED ISSUE #46411: Feature: Mark editable regions on help posts in forum
### Describe the Issue

The forum help posts submitted by users do not show the editable parts of the code. The snippets ('you code so far') have boilerplate code which makes it difficult to understand the actual edits made by the user.

### Steps to Reproduce

1. On any later step in the RWD project, click Ask For Help and look at the forum post contents.
2. The code snippet looks like so:

   ```html
   <html>
	  <body>
	    <main>
	      <h1>CatPhotoApp</h1>
	      <h2>Cat Photos</h2>
	      <!-- TODO: Add link to cat photos -->
	      <p>Click here to view more <a href="https://freecatphotoapp.com">this is what I changed</a>.</p>
	      <img src="https://cdn.freecodecamp.org/curriculum/cat-photo-app/relaxing-cat.jpg" alt="A cute orange cat lying on its back.">
	    </main>
	  </body>
	</html>
   ```

### Expected behavior

Instead of the above, maybe the code snippet should show what they changed:

```html
<html>
  <body>
    <main>
      <h1>CatPhotoApp</h1>
      <h2>Cat Photos</h2>
      <!-- TODO: Add link to cat photos -->

<!-- User Editable Region -->

      <p>Click here to view more <a href="https://freecatphotoapp.com">this is what I changed</a>.</p>

<!-- User Editable Region -->

      <img src="https://cdn.freecodecamp.org/curriculum/cat-photo-app/relaxing-cat.jpg" alt="A cute orange cat lying on its back.">
    </main>
  </body>
</html>
```

Maybe a nice to have will be to show some diff-style syntax highlighting, but the above should be a good starting point.

### PR DESCRIPTION
**Pull request by KravMaguy**
Checklist:

- [x] I have read [freeCodeCamp's contribution guidelines](https://contribute.freecodecamp.org).
- [x] My pull request has a descriptive title (not a vague title like `Update index.md`)
- [x] My pull request targets the `main` branch of freeCodeCamp.
- [x] I have tested these changes either locally on my machine, or GitPod.

Closes #46411 

tested locally by removing lines from both files, fixed bug when creating new post after student revises original changes (additional unnecessary files being created), solution is adapted from https://github.com/freeCodeCamp/freeCodeCamp/issues/46411#issuecomment-1150955886

### CODE REVIEW

**Comment by moT01** [comment]
This is ready for review I presume @KravMaguy?

**Comment by naomi-lgbt** [comment]
image

This is off to a great start! I wonder if we should add line numbers, or inline this with the camper's code, so it's more clear *where* the changes were made?

**Comment by KravMaguy** [comment]
> This is ready for review I presume @KravMaguy?
I think so...
from the original post by jeremylt:
"It's a bit difficult to dig through the code on some of the later steps in the RWD."
"Easier output for forum helpers to parse would be nice."

This allow forum helpers to be able to point out quicker what the issues might be with the campers code. It works for what its designed to do, yes?

**Comment by KravMaguy** [comment]
> image
> 
> This is off to a great start! I wonder if we should add line numbers, or inline this with the camper's code, so it's more clear _where_ the changes were made?

Thanks for your input it means alot to me. About line numbers, the line numbers are only in the challenge editor and dont currently show up when the files are posted in the forum. so my persoanl opinion is that its a seperate feature, but.. up to you.

inline with the campers code, do you mean I shouldnt add any additional files to the forum post but rather apply the changes to the original files (that would be posted anyways). if you'd like some combination with the line numbers please describe it, and i can try to do it.

**Comment by KravMaguy** [comment]
> inline this with the camper's code, so it's more clear

reason I didnt do it that way is because I thought he wanted to ONLY show the changed lines https://github.com/freeCodeCamp/freeCodeCamp/issues/46411#issuecomment-1150955886

let me know if you like this better:
https://github.com/KravMaguy/freeCodeCamp/tree/feat/diff-in-campers-code

( though I personally prefer the version that only shows the changed lines. )

**Comment by naomi-lgbt** [comment]
This feature is primarily beneficial to our forum moderators, who have asked for improvements in identifying where campers changed code. I'm going to loop @jeremylt in on this, who I know has asked for a similar feature.

**Comment by jeremylt** [comment]
Backing up a moment, here is the problem we're trying to solve:

As learners move towards later steps in these practice projects, there is a lot of code in the editor that is not related to the current step they are trying to accomplish.This makes it hard to quickly pinpoint the error.

I have seen two proposed ideas to help with this.

1) Insert the comments denoting the editable region into the auto generated post

2) Supply a diff from the seed code

I'm not sure if there are other options. I'm not sure what the best option is. 1) certainly would be the least disruptive.

**Comment by ojeytonwilliams** [comment]
It's a bit tangential, but if we want diffs, let's not use `diff` to generate them.  It's a rather large package that we can't justify bundling into the client.

Or rather: we can't bundle it.  If we want to dynamically import it, that should be okay.

**Comment by KravMaguy** [comment]
> 
> 1. Insert the comments denoting the editable region into the auto generated post

yes sir, as requested, ive tested it and working as expected:

https://github.com/KravMaguy/freeCodeCamp/tree/feat/insert-comments-editable-region

> 2. Supply a diff from the seed code

Ive done that already in this PR, yes? 

a. File showing only changed lines (This PR)
b. Show full campers code [integrated with changed lines](https://github.com/KravMaguy/freeCodeCamp/tree/feat/diff-in-campers-code)

**Comment by KravMaguy** [comment]
> It's a bit tangential, but if we want diffs, let's not use `diff` to generate them. It's a rather large package that we can't justify bundling into the client.
> 

Ok, I can go through line by line and just find the ones that are different. maybe we dont need the package, I only used it because it was mentioned in the issue. 

> Or rather: we can't bundle it. If we want to dynamically import it, that should be okay.

I'll do it. please advise how you would like me to proceed.

**Comment by jeremylt** [comment]
> Ive done that already in this PR, yes?

You have done both, yes, but like I said,

> I'm not sure if there are other options. I'm not sure what the best option is.

I don't know what direction we want to actually go here.

**Comment by KravMaguy** [comment]
> It's a bit tangential, but if we want diffs, let's not use `diff` to generate them. It's a rather large package that we can't justify bundling into the client.

I tried to reacreate it scratch, I can add tests and work on it more if you guys want to go this route:

[diff from scratch
](https://github.com/KravMaguy/freeCodeCamp/tree/feat/diff-without-dependency
)

> Or rather: we can't bundle it. If we want to dynamically import it, that should be okay.

I [tried](https://github.com/freeCodeCamp/freeCodeCamp/commit/c937983681ec1d092d38e51373d7198fa5ea3112)

**Comment by raisedadead** [comment]
Hi @KravMaguy 

After a brief discussion, we decided to close the PR. I think we did not do an excellent job of explaining the exact requirements on the main issue thread. We will add more details there and open it up for contributions later. You can then make a fresh PR should you still be interested.

**Pull request closed without merging**
