### PR TITLE
feat: simplify client logic

### PR DESCRIPTION
**Pull request by majestic-owl448**
Checklist:

- [x] I have read [freeCodeCamp's contribution guidelines](https://contribute.freecodecamp.org).
- [x] My pull request has a descriptive title (not a vague title like `Update index.md`)
- [x] My pull request targets the `main` branch of freeCodeCamp.
- [x] I have tested these changes either locally on my machine, or GitPod.

Continue work for #46729 

`isJsProject` now can rely only on the challenge type. Challenge order was for the new JavaScript curriculum, but was kinda hacky.

And in the return there is no need to check for take home projects, as there is none that is of challenge type 5. (Take Home Projects are of type 3 and 4)

### CODE REVIEW

**Review by ojeytonwilliams — CHANGES_REQUESTED** [review]
Hey @ieahleen, this is looking good.  That said, I think we can clean this up a little more.

Rather than checking if it's a js project or another type of project, we can extend 

https://github.com/freeCodeCamp/freeCodeCamp/blob/16438b13ed9c2893e263a2a5bb6ec06ce6da00fb/client/utils/challenge-types.js#L44-L54

to include all projects and call that.

This could have side effects, since `isProject` is used in a couple of places.  But, frankly, if they're relying on `isProject`'s current broken state, that needs fixing too!

**Comment by ieahleen** [comment]
the only thing there is that take home projects are type 3 and 4, frontEndProject and backEndProject, so if there is anything that should happen with certification projects but not take home projects, we need an other way to distinguish that

**Comment by ojeytonwilliams** [comment]
@ieahleen that's true. However, unless we're intending to do that soon, it's fine to defer the problem until we need to solve it. We may never need to.

**Comment by ieahleen** [comment]
@ojeytonwilliams the consequence is going to be that the Take Home projects section is going to be non-collapsable, like it happened with the rosetta section (and we are back at https://github.com/freeCodeCamp/freeCodeCamp/issues/46006)

**Comment by ieahleen** [comment]
Simplification without dealing with the take honme projects would be something like

```
    const isProjectBlock = challenges.some(({ challenge }) =>
      isProject(challenge.challengeType)
    );
```
image

with keeping collapsible take home projects maybe something like

```
    const isProjectBlock = challenges.some(({ challenge }) => {
      const isTakeHomeProject = blockDashedName === 'take-home-projects';

      return isProject(challenge.challengeType) && !isTakeHomeProject;
    });
```

**Comment by ojeytonwilliams** [comment]
Yep, that's a good solution. The take home projects are an exception, so that has to be handled, but this approach is much better than what we had.

**Comment by ieahleen** [comment]
this one will not change the result, as it checks for multifile and not project, so it's fine
https://github.com/freeCodeCamp/freeCodeCamp/blob/67cf5d63f2885c0cb93e591e1d988fa893dbf9a6/client/src/templates/Challenges/classic/editor.tsx#L427-L443

here there is also codeAllyPractice type that make line 361 true, I don't know the implication of that
https://github.com/freeCodeCamp/freeCodeCamp/blob/67cf5d63f2885c0cb93e591e1d988fa893dbf9a6/client/src/templates/Challenges/components/completion-modal.tsx#L356-L364

and it is used here, which should also be fine as it checks for multifile and not project
https://github.com/freeCodeCamp/freeCodeCamp/blob/67cf5d63f2885c0cb93e591e1d988fa893dbf9a6/client/src/templates/Challenges/components/Hotkeys.tsx#L102-L115

**Comment by ojeytonwilliams** [comment]
@ieahleen that makes sense. The completion modal will break because the CodeAlly practice projects are also exceptions.  So, we have 

- Certification projects: non-collapsible, use certification.yml to determine completion %
- CodeAlly practice projects: non-collapsible, use meta.json to determine completion %
- Take Home projects: collapsible, use meta.json to determine completion %

Part of the problem comes from the fact we're inferring a block property (collapsible or not) from a mixture of challenge properties (`challengeType`) and information about the block (is it `take-home-projects`?). The client should have direct access to the block data.

We're also trying to determine if a given challenge is part of a block or a certification from its `challengeType` and that's impossible.  There's a bug related to this: if you complete a Take Home Project the modal includes "NaN% complete".

Unfortunately fixing these issues is a pretty big job.

For now we can do some relatively simple things.

1. `isProject` should be called `isNonPracticeProject` or `isFinalProject` something like that.  It can't be called `isCertificationProject`, because Take Home Projects exist
2. `isFinalProject` should not include `codeAllyPractice`, a separate `isCodeAllyPractice` function can handle them
3. Re-complicate the collapsible logic by using `isFinalProject`, `isCodeAllyPractice` and `isTakeHomeProject`

Then the different project types can work like this:

- Certification projects: `isFinalProject` && `!isTakeHomeProject`
- CodeAlly practice projects: `isCodeAllyPractice`
- Take Home projects: `isFinalProject` && `isTakeHomeProject`

**Comment by ieahleen** [comment]
@ojeytonwilliams I tried to follow what you said with remaking the logic, did you mean like this?

**Review by ojeytonwilliams — DISMISSED** [review]
Nice work, Ilenia, this LGTM :+1: 

There's one nitpick, but I'd be happy to merge as is.

**Review by ojeytonwilliams — APPROVED** [review]
LGTM :+1:

**Review by raisedadead — APPROVED** [review]

**Pull request merged**
