### PR TITLE
Add Issue and Pull Request GitHub templates

### LINKED ISSUE #7093: Add Issue Template for easier issue creation
It looks like Github has [created a new feature](https://github.com/dear-github/dear-github/issues/125) whereby when you make a new issue, it can look for a `issue_template.md` file in the repo to use as an issue template. This will help clarify why the issue was made and what should be done to fix it.

It might not seem obvious what is going on (I was confused when I first saw this), but if you go [here](https://github.com/owncloud/core/issues/new) to a repo using this feature, a new issue is automatically templated.

This can help when a user creates an issue straight from Github instead of from the FCC website where it would template the issue.

### LINKED ISSUE #7096: Add Pull Request Template
Details:
https://help.github.com/articles/creating-a-pull-request-template-for-your-repository/

We need to add a template with the default information we need in a PR.

### PR DESCRIPTION
**Pull request by bugron**
[Here](https://github.com/blog/2111-issue-and-pull-request-templates) is an official blog article about this new GitHub feature.
Closes #7093 and closes #7096.

### CODE REVIEW

**Comment by erictleung** [comment]
I think you'll also want to edit the `README.md` file because it links to the `CONTRIBUTING.md` file in the root directory instead of the newly made `.github/` hidden folder :)

**Comment by bugron** [comment]
@erictleung fixed, thanks!

**Comment by SaintPeter** [comment]
I guess we'll see if this improves anything.  One can dream.

**Comment by QuincyLarson** [comment]
@SaintPeter @bugron @erictleung this is an excellent idea. I read it and followed it myself. Great job - this will save our issue mods (and contributors) a ton of time!

**Comment by tinkbl67** [comment]
How can I stop these emails on pulls

**Comment by bugron** [comment]
@tinkbl67 unwatch this repository.

**Pull request merged**
