### PR TITLE
guide-to-implement-google-sign-in-using-firebase-auth

### PR DESCRIPTION
**Pull request by Anurag26**
This is a thorough guide on how to implement Google sign-in using firebase authentication.

- [x] I have read [freeCodeCamp's contribution guidelines](https://github.com/freeCodeCamp/freeCodeCamp/blob/master/CONTRIBUTING.md).
- [x] My pull request has a descriptive title (not a vague title like `Update index.md`)
- [x] My pull request targets the `master` branch of freeCodeCamp.
- [x] None of my changes are plagiarized from another source without proper attribution.
- [x] My article does not contain shortened URLs or affiliate links.

If your pull request closes a GitHub issue, replace the XXXXX below with the issue number.

Closes #XXXXX

### CODE REVIEW

**Comment by RandellDawson** [comment]
@Anurag26  I had to change the folder name, because it needed to be all lowercase.  I believe you had one uppercase letter.  It was failing the tests, so I fixed and added the change to your commit.  You will get the credit for it.

**Comment by Anurag26** [comment]
@RandellDawson  Thanks

**Review by cmccormack — APPROVED** [review]
This looks good to me.  Thank you for your contribution!

**Comment by Anurag26** [comment]
Thank you!

**Pull request merged**
