### PR TITLE
fix(ui): "sign in" button hidden at small devices

### LINKED ISSUE #46534: Sign-in button missing visiting a profile page in portrait mode
On a mobile browser or on a desktop one (under a width resolution of 456px ) there is no sign-in button to login in freecodecamp even in the burger menu in portrait mode.

**To Reproduce**
1. Visit a profile page from the smartphone in portrait mode (Ex. [this page](https://www.freecodecamp.org/eidan))
2. Log out if logged in
3. The sign-in button is missing on the page and in the burger menu

**Expected behavior**
The sign-in button should be visible on the main page and in the burger menu or at least in the burger menu

**Screenshots**
image

**Desktop**
 - OS: any
 - Browser: any
 - Version: any

**Smartphone**
 - Device: any
 - OS: any
 - Browser: any
 - Version: any

### PR DESCRIPTION
**Pull request by shootermv**
image
Checklist:

- [x ] I have read [freeCodeCamp's contribution guidelines](https://contribute.freecodecamp.org).
- [x ] My pull request has a descriptive title (not a vague title like `Update index.md`)
- [x ] My pull request targets the `main` branch of freeCodeCamp.
- [x ] I have tested these changes either locally on my machine, or GitPod.

Closes #46534

### CODE REVIEW

**Comment by moT01** [comment]
There's a few failing tests here. Mind taking a look at those @shootermv?

**Review by moT01 — CHANGES_REQUESTED** [review]
I opened this up locally and took a quick look.
In chrome, it looks alright:
Screen Shot 2022-06-24 at 8 40 45 AM

Firefox looks rough:
Screen Shot 2022-06-24 at 8 41 11 AM

We shouldn't need to change the signin button text elsewhere. The button in the middle of the page should still be text I think - I dunno, maybe that's fine - it looks pretty good I guess. Some other things I see, the fCC logo disappears at certain point - maybe we can't avoid that. I would try and keep it - but if we can't, maybe spread the buttons out or something? not quite sure. Also, the sizing of the icons and logo feels off. The logo gets real small, and the icons feel abnormally large when that happens. What do you think @ahmadabdolsaheb? At a minimum I would try and see what the problem with firefox is. Note: I am using the browser dev tools to "view" this on mobile sizes. The browser itself doesn't actually get small enough to see this view when on desktop. 

I ended up opening this on my iphone:
Screen Shot 2022-06-24 at 9 00 43 AM

Icon doesn't show up. Couldn't we use a font-awesome icon, [similar to this](https://github.com/freeCodeCamp/freeCodeCamp/blob/b2da57881c67bd92de003c2ad6c5d082809d66c5/client/src/components/Header/components/nav-links.tsx#L13), instead of coding the svg - I think we want to try and go that route across the codebase - maybe that would fix all the UI issues I'm seeing.

**Comment by ahmadabdolsaheb** [comment]
@moT01, thanks for taking a look and finding out where the UI breaks. @shootermv thanks for pushing the fixes. 
I will take it from here. In the few days, I will try different UI alternatives, push the changes, and include screenshots.

**Comment by moT01** [comment]
Looks good @ahmadabdolsaheb 👍

**Comment by ahmadabdolsaheb** [comment]
@shootermv, design wise this should be good to go.
Feel free to clean up the pr if necessary and pass the tests.

**Review by ahmaxed — APPROVED** [review]

**Review by Sboonny — APPROVED** [review]
LGTM 🎉, thank you for your contribution to the page! 👍.

**Review by moT01 — APPROVED** [review]
LGTM 🎉 All the UI issues I found before are fixed 👍

Thanks for contributing to freeCodeCamp @shootermv 🎉

**Pull request merged**
