### PR TITLE
fix(scripts): Use production webpack and reduce code duplication

### LINKED ISSUE #18145: Having issue running FCC in production
#### Describe your problem and - if possible - how to reproduce it

I have to run FCC in production because I’m one of the maintainers of FCC china website, we launch the new site on 15th, and through some offline activity, users are increasing, but they also report some bugs and performance issue.  I check the code and notice on production server ``npm run start-production`` don’t actually pass the ``env=production`` environment variables to the node app. and when I debug locally and manually pass the ``env=production`` and run ``npm run start-production`` again. all the routes don’t work, meaning not even hitting the routes.

#### Tell us about your browser and operating system

* Browser Name: chrome
* Browser Version:  Version 69.0.3497.92 (Official Build) (64-bit)
* Operating System: Mac os 10.12.6 (16G1510)

### PR DESCRIPTION
**Pull request by ojeytonwilliams**
#### Pre-Submission Checklist

- [x] Your pull request targets the `staging` branch of freeCodeCamp.
- [x] Branch starts with either `fix/`, `feature/`, or `translate/` (e.g. `fix/signin-issue`)
- [x] You have only one commit (if not, [squash](http://forum.freecodecamp.org/t/how-to-squash-multiple-commits-into-one-with-git/13231) them into one commit).
- [x] All new and existing tests pass the command `npm test`. Use `git commit --amend` to amend any fixes.

#### Type of Change

- [x] Small bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds new functionality)
- [ ] Breaking change (fix or feature that would change existing functionality)
- [ ] Add new translation (feature adding new translations)

#### Checklist:

- [x] Tested changes locally.
- [x] Addressed currently open issue (replace XXXXX with an issue no in next line)

Closes #18145

#### Description

This slightly changes how webpack behaves, putting it into production mode and cutting down on code duplication.  Issue #18145 highlighted that the NODE_ENV variable was not being set and this PR addresses at least that part of the issue, though it does not deal with the missing routes.

### CODE REVIEW

**Comment by ojeytonwilliams** [comment]
I'm not quite with you.  pm2 should have been running in production mode already and this PR changes the build process to match.

**Comment by Bouncey** [comment]
@ojeytonwilliams Thank you for this PR. We are, however, moving away from managing our own webpack config. Check out our `next` branch to see how we are doing things. It is a work in progress though, so don't be surprised if something doesn't work

**Comment by ojeytonwilliams** [comment]
@Bouncey Fair enough - I will take a look.

**Comment by ojeytonwilliams** [comment]
@Bouncey Come to think of it - to see what you're currently working on, is it a good rule of thumb to just look for an active branch in a given repo?  Or is there a better way?

**Pull request closed without merging**
