### PR TITLE
fix(eslint): meld into main repo

### LINKED ISSUE #40159: Bring @freecodecamp/eslint-config inside the monorepo
We currently have some eslint configuration in the published package and some inside freeCodeCamp/freeCodeCamp - this is a bit confusing.  Is there a good reason to maintain the eslint-config repo separately?

If not, I think we should manage it with Lerna instead.

### PR DESCRIPTION
**Pull request by patlehmann1**
Checklist:

- [x] I have read [freeCodeCamp's contribution guidelines](https://contribute.freecodecamp.org).
- [x] My pull request has a descriptive title (not a vague title like `Update index.md`)
- [x] My pull request targets the `master` branch of freeCodeCamp.
- [x] All the files I changed are in the same world language, for example: only English changes, or only Chinese changes, etc.

Closes #40159 

Just consolidated the eslint rules and deleted the external package from package.json. I was getting some linting errors after I consolidated so I changed the errors to a warn. I tried to install eslint globally and fix some of the issues but it didn't edit any files. Please feel free to contact me with any questions or concerns. Thanks!

### CODE REVIEW

**Review by ojeytonwilliams — CHANGES_REQUESTED** [review]
Hey @patlehmann1, sorry for the delay getting to this.

So, the issue here is that some of our the rules in `eslint-config-freecodecamp` conflicted with prettier.  Those rules were being overwritten by `"extends": ["prettier"]`, but since the rules are now being added after that statement, there are conflicts.

What I propose is this: move the rules into a `.eslintrc-base.json` file and import that into the current `.eslintrc.json` file (via `extends`).  That should fix the problem.

Ideally, if you have time, the rules that conflict with Prettier should also be removed.

**Comment by patlehmann1** [comment]
Thanks for the feedback. Will push up changes shortly.

**Comment by patlehmann1** [comment]
Uh, tried to squash some commits and I think I just made things worse. Sorry! Should be good to go now.

**Review by ojeytonwilliams — APPROVED** [review]
Nice work @patlehmann1. LGTM :+1:

**Review by raisedadead — APPROVED** [review]

**Pull request merged**
