### PR TITLE
Fixes title - Corrige el título

### PR DESCRIPTION
**Pull request by GonzaloGM**
Corrige el título 

Fixes title

- [x] I have read [freeCodeCamp's contribution guidelines](https://github.com/freeCodeCamp/freeCodeCamp/blob/master/CONTRIBUTING.md).
- [x] My pull request has a descriptive title (not a vague title like `Update index.md`)
- [x] My pull request targets the `master` branch of freeCodeCamp.
- [x] None of my changes are plagiarized from another source without proper attribution.
- [x] My article does not contain shortened URLs or affiliate links.

If your pull request closes a GitHub issue, replace the XXXXX below with the issue number.

Closes #XXXXX

### CODE REVIEW

**Comment by GonzaloGM** [comment]
@huyenltnguyen Solved the conflict.

**Comment by RandellDawson** [comment]
@GonzaloGM You accidentally deleted the `---` on the first line of the file which is part of the required front  matter block.  Actually, I can not even tell what you changed in this file except removing the first line of the file.  What exactly were you trying to change with this PR?

**Comment by GonzaloGM** [comment]
@RandellDawson You're right, sorry about that. With the [latest commit](https://github.com/freeCodeCamp/freeCodeCamp/commit/6d511c558a26e6e7a33c71a2c4e6af0f31c41cf5#diff-65f488383e058364c1230c2d543f9d22) my proposed change is fixed so I think we can close this PR.

**Comment by RandellDawson** [comment]
Do you have another PR with changes to the same file?  If so, what is the number?

**Comment by GonzaloGM** [comment]
@RandellDawson No, that was the only thing that needed a fix, the rest of the translation is OK. [I have some other PRs but for other articles](https://github.com/freeCodeCamp/freeCodeCamp/pulls/GonzaloGM).

**Comment by RandellDawson** [comment]
OK.

**Pull request closed without merging**
