### PR TITLE
fix: simplify completedChallenges updates

### PR DESCRIPTION
**Pull request by ojeytonwilliams**
Checklist:

- [x] I have read [freeCodeCamp's contribution guidelines](https://contribute.freecodecamp.org).
- [x] My pull request has a descriptive title (not a vague title like `Update index.md`)
- [x] My pull request targets the `main` branch of freeCodeCamp.
- [x] I have tested these changes either locally on my machine, or GitPod.

Replacing the entire completedChallenges array on submission of a single update seems wasteful, so this PR makes the update more focused. :crossed_fingers: this will help with the slow op logs.

### CODE REVIEW

**Comment by ojeytonwilliams** [comment]
I wasn't sure how best to profile these changes.  Any ideas? Push them to staging and see what happens?

**Comment by ShaunSHamilton** [comment]
I am not sure how indicative a local profile would be - sans clusters and replicas. However, if there is a difference locally, then I suppose it would be obvious this is worth it.

We do have the test data. I assume you would just want to profile the DB, and not the server?

**Comment by ojeytonwilliams** [comment]
> I assume you would just want to profile the DB, and not the server?

Indeed. The only thing I'm trying to improve is the speed of writes to the db.

**Review by moT01 — DISMISSED** [review]
LGTM 🎉 Gave it some good testing - everything looks like it works

Only thing I noticed is that we could maybe do the same to the `buildNewSavedChallenges` function.

**Comment by ojeytonwilliams** [comment]
> Only thing I noticed is that we could maybe do the same to the buildNewSavedChallenges function.

Yeah, for sure. After we test this on staging?

**Comment by moT01** [comment]
Yea, we can wait on it for now @ojeytonwilliams. The savedChallenges array will have a max length of 10 when we release those new projects, so it shouldn't really make much of a difference.

**Review by ShaunSHamilton — APPROVED** [review]
This LGTM 👍 . I did not run the code, but I am happy with the logic

**Review by scissorsneedfoodtoo — APPROVED** [review]

**Pull request merged**
