### PR TITLE
Added Icon in svg format for free code camp logo

### PR DESCRIPTION
**Pull request by Sanskar95**
This will imported in NavLogo.js

- [x] I have read [freeCodeCamp's contribution guidelines](https://github.com/freeCodeCamp/freeCodeCamp/blob/master/CONTRIBUTING.md).
- [x] My pull request has a descriptive title (not a vague title like `Update index.md`)
- [x] My pull request targets the `master` branch of freeCodeCamp.
- [x] None of my changes are plagiarized from another source without proper attribution.
- [x] All the files I changed are in the same world language (for example: only English changes, or only Chinese changes, etc.)
- [x] My changes do not use shortened URLs or affiliate links.

Closes #XXXXX

### CODE REVIEW

**Review by raisedadead — CHANGES_REQUESTED** [review]
Hi @Sanskar95 

You need to 

- [ ] test this locally. 
- [ ] convert the svg into a react component (not just link to the s3 asset).
- [ ] make sure the linting is passing.

You can reach out to the [contributors chat room](https://gitter.im/FreeCodeCamp/Contributors) for help.

**Comment by Sanskar95** [comment]
Sure @raisedadead

**Comment by raisedadead** [comment]
Are you editing off of GitHub? I recommend you either setup locally or use the GitPod, and reopen this PR once again when ready.

Hacktoberfest is firing off a lot of notifications for us and we would like to cut down the noise.

Thanks once again for working on this.

**Comment by Sanskar95** [comment]
Yeah sure I understand , will set up the code locally and create a  PR

**Comment by raisedadead** [comment]
Thanks and as always, reach out to [contributors chat room](https://gitter.im/FreeCodeCamp/Contributors) for help

**Pull request closed without merging**
