### PR TITLE
fix(challenge): formatting of "Remove Items Using splice()".

### LINKED ISSUE #13067: [beta] Change order of array methods in "Basic Data Structures: Remove Items Using splice()"
Challenge [remove-items-using-splice](http://beta.freecodecamp.com/en/challenges/basic-data-structures/remove-items-using-splice) has an issue.

I think `pop()` and `shift()` should swap places in the following sentence, so they come in the same order as their functionality gets described.
order

**Edit:** The last line of the first paragraph also needs a small fix:
Change "from anywhere on an array" to `from anywhere in an array`.

**Edit 2:** [This line](https://github.com/freeCodeCamp/freeCodeCamp/blob/staging/seed/challenges/02-javascript-algorithms-and-data-structures/basic-data-structures.json#L190) could be replaced with `"  ",` (two spaces), to improve formatting of the initial `challengeSeed`.

### PR DESCRIPTION
**Pull request by Greenheart**
#### Pre-Submission Checklist

- [x] Your pull request targets the `staging` branch of freeCodeCamp.
- [x] Branch starts with either `fix/`, `feature/`, or `translate/` (e.g. `fix/signin-issue`)
- [x] You have only one commit (if not, [squash](http://forum.freecodecamp.com/t/how-to-squash-multiple-commits-into-one-with-git/13231) them into one commit).
- [x] All new and existing tests pass the command `npm test`. Use `git commit --amend` to amend any fixes.

#### Type of Change

- [x] Small bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds new functionality)
- [ ] Breaking change (fix or feature that would change existing functionality)
- [ ] Add new translation (feature adding new translations)

#### Checklist:

- [x] Tested changes locally.
- [x] Closes currently open issue (replace XXXX with an issue no): Closes #13067 

#### Description

* Improve order of Array-methods in a sentence.
* Fix preposition.
* Fix tab for challengeSeed.

### CODE REVIEW

**Comment by Greenheart** [comment]
@raisedadead How can I improve my label usage for PRs? :blush:

**Comment by raisedadead** [comment]
@Greenheart : We label PRs with only `QA`, `blocked`, `translation`, and for issues, as the case maybe.

**Comment by Greenheart** [comment]
@raisedadead Thanks! I learn every day :smile:

**Comment by no-stack-dub-sack** [comment]
## LGTM!

**Comment by Greenheart** [comment]
@no-stack-dub-sack Thanks!

I agree, multiple reviews are more important for PRs changing bigger things, or if one's unsure and need more opinions.

**Pull request merged**
