### PR TITLE
fix(curriculum): remind users about healthText rpg step 76

### LINKED ISSUE #55209: Role playing game - step 76: Selector in example code may cause confusion
### Describe the Issue

The challenge should either not show the `querySelector` in the example code, or it should be mentioned in the note that they already have access to the two DOM nodes.

### Affected Page

https://www.freecodecamp.org/learn/javascript-algorithms-and-data-structures-v8/learn-basic-javascript-by-building-a-role-playing-game/step-76

### Your code

```



```

### Expected behavior

Make sure the camper knows they already have access to the two DOM nodes, or remove the `querySelector` in the example code.

### Screenshots

_No response_

### System

- Device: [e.g. iPhone 6, Laptop]
- OS: [e.g. iOS 14, Windows 10, Ubuntu 20.04]
- Browser: [e.g. Chrome, Safari]
- Version: [e.g. 22]

### Additional context

Forum: https://forum.freecodecamp.org/t/learn-basic-javascript-by-building-a-role-playing-game-step-76/695998

### PR DESCRIPTION
**Pull request by a2937**
Checklist:

- [X] I have read and followed the [contribution guidelines](https://contribute.freecodecamp.org).
- [X] I have read and followed the [how to open a pull request guide](https://contribute.freecodecamp.org/how-to-open-a-pull-request/).
- [X] My pull request targets the `main` branch of freeCodeCamp.
- [X] I have tested these changes either locally on my machine, or GitPod.

Closes #55209

I went for the second approach as I don't normally like incomplete examples. However I would be happy to change it.

### CODE REVIEW

**Comment by lasjorg** [comment]
I think the consensus is we don't need the example code. So we should probably just remove it.

**Comment by a2937** [comment]
Okie dokie. It's been removed.

**Review by lasjorg — APPROVED** [review]
"Thankfully" sounds a little odd to me. Not really sure why, so it might just be me.

I might just go with.

> You already retrieved the `healthText` and `goldText` elements in a prior step.

But I guess its fine. LGTM

**Comment by a2937** [comment]
I removed "Thankfully"

**Review by huyenltnguyen — APPROVED** [review]

**Pull request merged**
