### PR TITLE
chore: drop setup-node and use caching

### PR DESCRIPTION
**Pull request by ojeytonwilliams**
Checklist:

- [x] I have read and followed the [contribution guidelines](https://contribute.freecodecamp.org).
- [x] I have read and followed the [how to open a pull request guide](https://contribute.freecodecamp.org/#/how-to-open-a-pull-request).
- [x] My pull request targets the `main` branch of freeCodeCamp.
- [x] I have tested these changes either locally on my machine, or GitPod.

Since we're using `.npmrc` + pnpm to set the node version it will get downloaded and installed when needed. As such, we do not need to rely on the `setup-node` action in CI. This PR removes it.

We can still test against multiple node versions by appending to `.npmrc` (much like .env the last config is used).

Also, while `pnpm install` is considerably faster than `npm ci`, it still should be possible to save a bit of time by caching the node module store. i.e. download the cache as whole rather than individual node modules. precisely how much (or how little) remains to be seen.

### CODE REVIEW

**Review by raisedadead — CHANGES_REQUESTED** [review]
How does this play with multiple node versions when I want to test with the next LTS side-by-side?

That's a hard and non-negotiable requirement.

**Comment by ojeytonwilliams** [comment]
Good question. I think the simplest approach would be to append `use-node-version=${{ matrix.node-version }}` to `.npmrc` conditionally. i.e. have a step with `if: ${{ matrix.node-version != 'default' }}` to do that.

I can test that out on this PR if you like.

**Comment by raisedadead** [comment]
Sure

**Comment by raisedadead** [comment]
Also, why are we doing this PR in the first place (the OP is saying little)?

**Comment by raisedadead** [comment]
And it is not ideal:

a) Having both .npmrc and setup-node (because I see the workaround in this PR as a brittle hack).
b) Not having a .npmrc at all

**Comment by ojeytonwilliams** [comment]
I don't think it's that weird of a pattern. We've been overwriting .env with `SHOW_UPCOMING_CHANGES` for quite some time. It's the same basic principle.

Also, there's nothing to be gained by setting the version with setup-node and .npmrc. The one set by .npmrc is the one that will be used, so I'm not entirely with you.

**Comment by raisedadead** [comment]
It doesn't necessarily mean it's the best way if we have been doing something. So let's remain objective (and specific to our use case).

My question about why we need a `.npmrc` in the first place is not clarified (although I think did not make it clear with my comment). And if it is critical why not something else like `nvmrc`. 

I am asking questions to make sure we have the bases covered.

**Comment by ojeytonwilliams** [comment]
Sure. `.npmrc` configures how `pnpm` behaves in a few ways that are helpful. Specifically:

```
auto-install-peers=true
```
because it's a chore to manually include them all,
```
strict-peer-dependencies=true
```
for reliability: we want to know if they're missing or invalid, since something is likely to break and
```
enable-pre-post-scripts=true
```
because otherwise we have to rewrite a lot of our scripts which rely on them.

I'm sure we could work around them, but they're necessary for now.

---

And now the one we've been discussing here: `use-node-version`. This tells `pnpm` which node version to use when you run scripts or execute shell commands. e.g. `pnpm node -v` will output whatever `use-node-version` is set to.  The nice thing about this is it removes one of the "it works on my machine" issues: all machines will be using the same version.

Why not `.nvmrc`? We could do that, but that means we'd lose the nice things that `use-node-version` gets us. We'd need to use `nvm` again and people and tools would need to remember to `nvm use` to switch the version.

While we do have to use the custom step to use different node versions, that doesn't seem *too* bad.

**Comment by ojeytonwilliams** [comment]
For future reference, we discussed this and concluded that, while convenient, setting the node version via `.npmrc` is a little too rigid. Instead we're going to setup node separately.

**Pull request closed without merging**
