### PR TITLE
fix(i18n): create how-to-work-on-coding-challenges.md in german

### PR DESCRIPTION
**Pull request by Plingooo**
Translate how-to-work-on-coding-challenges.md into german

- [x] I have read [freeCodeCamp's contribution guidelines](https://github.com/freeCodeCamp/freeCodeCamp/blob/master/CONTRIBUTING.md).
- [x] My pull request has a descriptive title (not a vague title like `Update index.md`)
- [x] My pull request targets the `master` branch of freeCodeCamp.
- [x] None of my changes are plagiarized from another source without proper attribution.
- [x] All the files I changed are in the same world language (for example: only English changes, or only Chinese changes, etc.)
- [x] My changes do not use shortened URLs or affiliate links.

Closes #XXXXX

### CODE REVIEW

**Comment by raisedadead** [comment]
Hi @Plingooo same as your previous pull-request can you get this PR reviewed

**Review by martin-gnodtke — CHANGES_REQUESTED** [review]
Did only a few changes to @Plingooo's great translation. Good Job!

**Comment by Plingooo** [comment]
Thank you for reviewing @Squizzi3 !

**Comment by Plingooo** [comment]
@raisedadead 
Why did the Job fail?

**Comment by raisedadead** [comment]
We are still in the process of integrating the Circle CI. You can ignore that check for now. See #37284

**Pull request merged**
