### PR TITLE
Update codemirror

### LINKED ISSUE #8675: Text color of warning and errors while hovering over the marker
The issue is present in the text editor used by FCC site. It's CodeMirror. And I noticed this for a long time that the text color of the warning and errors when hover over were "infotext" on a "infobackground" background color, which was very tough to view, and I had to strain my eye to see the text. I opened an issue in CodeMirror's github repo and they fixed it and closed it. Here's the link to the issue : 

https://github.com/codemirror/CodeMirror/issues/4025

And looks like they also updated their bower component too. But FCC has to update it's bower component too! So I opened this issue so that you update your bower components.

#### Browser Information
Firefox Developer Edition. Ubuntu 64 bit. Desktop.
I think the problem exists in a lot of system.

#### Screenshot
error hover

### LINKED ISSUE #8736: Pressing 'Enter' works wrong with multi select
#### Challenge Name
All challenges in which there is a lot of code

#### Issue Description
When I use multi select Enter key press works only for the first cursor.
But that's actual only for the first key press. Pressing more times works OK.
Please look at video for more details.

#### Video
http://screencast.com/t/UKxxPMyRoH

#### Browser Information
* Browser Name, Version:  Google Chrome Canary 52.0.2743.0 (64-bit)
* Operating System:  Windows 10
* Mobile, Desktop, or Tablet:  Desktop

### PR DESCRIPTION
**Pull request by arialaurel**
This closes #8675 and closes #8736

I didn't spot any regressions but I'd love another set of eyes to install the new version and make sure.

### CODE REVIEW

**Comment by raisedadead** [comment]
Works for me as well.

Thanks @ltegman !

**Comment by raisedadead** [comment]
Keeping this open if anyone wants to check this on Ubuntu, I'll complete checking on it by tomorrow if no one else does it before that

**Comment by atjonathan** [comment]
@ltegman Works fine for me on Ubuntu!
Thanks for the PR :shipit:

**Comment by yamimaio** [comment]
Hi, I'm still having problems with **Repeated problems with cursor, in editor only. #8253** Maybe that issue should be reopened.
Thanks.

**Comment by mnttnm** [comment]
Seeing symptoms of #8253 on https://www.freecodecamp.com/challenges/create-a-text-field page.

Screenshot with cursor:
screen shot 2016-07-16 at 7 22 13 pm

The cursor is always shown at **(last_line -1)** position, for eg in the screenshot it is shown at line no. 46 instead of line 47. If I try to click on line 47 it won't allow. The only way I can go to line 47 is after pressing return key.

**Pull request merged**
