### PR TITLE
fix(curriculum): Strip comments from user code for Use Destructuring Assignment to Extract Values from Objects challenge

### PR DESCRIPTION
**Pull request by RandellDawson**
- [x] I have read [freeCodeCamp's contribution guidelines](https://github.com/freeCodeCamp/freeCodeCamp/blob/master/CONTRIBUTING.md).
- [x] My pull request has a descriptive title (not a vague title like `Update index.md`)
- [x] My pull request targets the `master` branch of freeCodeCamp.
- [x] None of my changes are plagiarized from another source without proper attribution.
- [x] All the files I changed are in the same world language (for example: only English changes, or only Chinese changes, etc.)
- [x] My changes do not use shortened URLs or affiliate links.

This PR fixes a bug related to the issue discussed in [this forum thread](https://www.freecodecamp.org/forum/t/odd-test-behavior-comment-out-does-not-make-test-ignore-lines/350097).  Basically, we needed to strip the comments out of the user's code for the [Use Destructuring Assignment to Extract Values from Objects](https://www.freecodecamp.org/learn/javascript-algorithms-and-data-structures/es6/use-destructuring-assignment-to-extract-values-from-objects) challenge, to prevent false test failures.

### CODE REVIEW

**Comment by ojeytonwilliams** [comment]
@RandellDawson should we hold off on this until you've got the utility functions into the test evaluator?  That's probably the best solution to the failing tests in this PR.

**Comment by RandellDawson** [comment]
@ojeytonwilliams I pushed the fix which removed the stray `</section>` that you identified (Thanks for that observation).  I think we can still go ahead and merge this one once approved.  When I get the global helper functions incorporated we discussed, I will remove all of these stand-alone versions in the same PR.

**Comment by RandellDawson** [comment]
@ojeytonwilliams @Manish-Giri Can this be reviewed?  We are trying to get as many older PRs merged if possible.

**Review by ojeytonwilliams — APPROVED** [review]
LGTM :+1:

**Review by Manish-Giri — APPROVED** [review]
LGTM

**Pull request merged**
