### PR TITLE
Remove extraneous attribute spaces

### PR DESCRIPTION
**Pull request by drguildo**
#### Pre-Submission Checklist

- [x] Your pull request targets the `staging` branch of FreeCodeCamp.
- [x] Branch starts with either `fix/`, `feature/`, or `translate/` (e.g. `fix/signin-issue`)
- [x] You have only one commit (if not, [squash](http://forum.freecodecamp.com/t/how-to-squash-multiple-commits-into-one-with-git/13231) them into one commit).
- [x] All new and existing tests pass the command `npm test`. Use `git commit --amend` to amend any fixes.

#### Type of Change

- [x] Small bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds new functionality)
- [ ] Breaking change (fix or feature that would change existing functionality)
- [ ] Add new translation (feature adding new translations)

#### Checklist:

- [x] Tested changes locally.
- [ ] Closes currently open issue (replace XXXX with an issue no): Closes #XXXX

#### Description

Removed unneeded spaces around the equals sign after some HTML attributes.

### CODE REVIEW

**Comment by drguildo** [comment]
Please forgive the extra commit. :fearful:

**Comment by systimotic** [comment]
Hi @drguildo! Thanks for these changes. ❤️ 
I _am_ going to ask you if you could please squash those two commits into one 😛 
Here's a [wiki article](http://forum.freecodecamp.com/t/how-to-squash-multiple-commits-into-one-with-git/13231) on how to do that.
If you need any help, you can hit us up in the Contributors chat room on Gitter.

**Comment by drguildo** [comment]
> I am going to ask you if you could please squash those two commits into one

Done. :+1:

**Comment by Bouncey** [comment]
## LGTM :+1:

**Pull request merged**
