### PR TITLE
feat(client): Highlight footer links on hover

### LINKED ISSUE #36126: [beta] Footer links' clickable area should fit to their content
**Describe your problem and how to reproduce it:**
At the moment, the clickable area of footer links are spanning the full width of their parent div.  I'm not sure if this is on purpose, but IMHO, they should fit to their content instead, since a user could get navigated to another page if they accidentally click somewhere within the clickable area.

This issue is on https://www.freecodecamp.rocks, but it is down for maintenance at the moment. The screenshot is of my local fCC.

Untitled

### PR DESCRIPTION
**Pull request by ojeytonwilliams**
- [x] I have read [freeCodeCamp's contribution guidelines](https://github.com/freeCodeCamp/freeCodeCamp/blob/master/CONTRIBUTING.md).
- [x] My pull request has a descriptive title (not a vague title like `Update index.md`)
- [x] My pull request targets the `master` branch of freeCodeCamp.
- [x] None of my changes are plagiarized from another source without proper attribution.
- [x] All the files I changed are in the same world language (for example: only English changes, or only Chinese changes, etc.)
- [x] My changes do not use shortened URLs or affiliate links.

Slightly changes the background on hover to indicate that the whole area is a link, and not just the text.  Also fixes the donate link on the front page.  In night mode its text is white on a white background, but should look like this:
DonateLink

Closes #36126

### CODE REVIEW

**Review by moT01 — COMMENTED** [review]
I would still prefer to just make the clickable area where the word is instead of adding the hover effect - but if it's decided to go this route, it LGTM. Here's some pics with the mouse over "donate"

**current:**

Screen Shot 2019-06-06 at 5 21 08 PM

**this PR:**

Screen Shot 2019-06-06 at 5 22 20 PM

**Comment by ojeytonwilliams** [comment]
@moT01 Understood and thanks for the screenshots.  Obviously I prefer this approach and I think it's a common enough UX pattern (Reddit and the BBC use it, for example) that it shouldn't cause confusion.  That said, it's not ubiquitous (Washington Post doesn't), so there's definitely a case for shrinking it.

**Comment by raisedadead** [comment]
I added a more modern outline look instead of the hover. Let me know if this works or I missed anything.

**Comment by ojeytonwilliams** [comment]
@raisedadead looks like it's working fine.

**Review by raisedadead — APPROVED** [review]

**Pull request merged**
