### PR TITLE
fix(test): eslint error in travis

### PR DESCRIPTION
**Pull request by varunzxzx**
#### Pre-Submission Checklist

- [x] Your pull request targets the `staging` branch of freeCodeCamp.
- [x] Branch starts with either `fix/`, `feature/`, or `translate/` (e.g. `fix/signin-issue`)
- [x] You have only one commit (if not, [squash](http://forum.freecodecamp.org/t/how-to-squash-multiple-commits-into-one-with-git/13231) them into one commit).
- [ ] All new and existing tests pass the command `npm test`. Use `git commit --amend` to amend any fixes.

#### Type of Change

- [x] Small bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds new functionality)
- [ ] Breaking change (fix or feature that would change existing functionality)
- [ ] Add new translation (feature adding new translations)

#### Checklist:

- [x] Tested changes locally.
- [ ] Addressed currently open issue (replace XXXXX with an issue no in next line)

#### Description

Invoking `eslint` from `node-modules`.

### CODE REVIEW

**Comment by Nirajn2311** [comment]
No wonder travis was failing. 👍 👍

**Review by raisedadead — APPROVED** [review]

**Comment by raisedadead** [comment]
Hi @varunzxzx 

Thanks for the PR, while the code LGTM, I would be interested to know about the original issue. Was this tracked somewhere? Do we have any screenshots, logs or references?

**Comment by varunzxzx** [comment]
@raisedadead Many PRs including this one was failing before. It showed that `eslint was not found`. But, I don't know how the tests are passing now. #17526 was also failing before. [Here](https://github.com/freeCodeCamp/freeCodeCamp/pull/17526#issuecomment-398031814) is the proof. Is there any chance that all builds are re-triggered?

**Comment by raisedadead** [comment]
Hmm I am not sure if it was a temporary issue. Let's just close this and wait and see if the builds fail again.

Some times the package caching that we have had for speeding up the builds may be a issue and lead to false negatives.

Thanks a lot for the PR though, looking forward to more contributions in future.

**Pull request closed without merging**
