### PR TITLE
fix(docs): remove member name

### PR DESCRIPTION
**Pull request by RandellDawson**
Checklist:

- [x] I have read [freeCodeCamp's contribution guidelines](https://contribute.freecodecamp.org).
- [x] My pull request has a descriptive title (not a vague title like `Update index.md`)
- [x] My pull request targets the `main` branch of freeCodeCamp.
- [x] All the files I changed are in the same world language, for example: only English changes, or only Chinese changes, etc.

Updating the docs.

### CODE REVIEW

**Review by ojeytonwilliams — APPROVED** [review]
I can't say this LGTM, but I know this has to be done.

**Review by raisedadead — APPROVED** [review]
Wishing you the very best for your next role Randy, and thanks for helping us get here.

**Comment by moT01** [comment]
😢

**Comment by RafaelDavisH** [comment]
@RandellDawson It was a pleasure knowing and working with you these past few months. I wish you the best and a successful new journey in your career as Software Engineer.

**Comment by QuincyLarson** [comment]
It's been a blast, @RandellDawson. We'll miss you. Don't be a stranger.

**Comment by scissorsneedfoodtoo** [comment]
Best of luck with everything @RandellDawson. Even though we didn't work together long, I learned a whole lot in that time. Hope to see you around the community, and I'm really looking forward to seeing what's next on the horizon for you.

**Comment by ahmadabdolsaheb** [comment]
Thanks for all you have done for our community, Randy.

**Comment by nhcarrigan** [comment]
You'll definitely be missed Randy, but best of luck in your next adventure! Wherever you go, they'll be lucky to have you. 🙂

**Pull request merged**
