### PR TITLE
fix(curriculum): rework Problem Euler 65

### PR DESCRIPTION
**Pull request by gikf**
- Reworks challenge to use argument in function.
- Adds more tests.
- Adds solution.
- Related to #40896.
- Tested on local fork.

Checklist:

- [x] I have read [freeCodeCamp's contribution guidelines](https://contribute.freecodecamp.org).
- [x] My pull request has a descriptive title (not a vague title like `Update index.md`)
- [x] My pull request targets the `main` branch of freeCodeCamp.
- [x] All the files I changed are in the same world language, for example: only English changes, or only Chinese changes, etc.

### CODE REVIEW

**Review by naomi-lgbt — APPROVED** [review]
With my somewhat limited math knowledge this looks good. 🙂

**Comment by gikf** [comment]
I can explain code side of it and what is where at each point. Why exactly math side works that way I'm not able to (more often that I'd like to).

**Comment by Sembauke** [comment]
> I can explain code side of it and what is where at each point. Why exactly math side works that way I'm not able to (more often that I'd like to).

Would you like to explain? Because this looks good to me.

**Comment by gikf** [comment]
> > I can explain code side of it and what is where at each point. Why exactly math side works that way I'm not able to (more often that I'd like to).
> 
> Would you like to explain? Because this looks good to me.

Challenge needs the sum of digits in numerator of certain convergent of the continued fraction of `e`. For `e` that numerator can be calculated based on previous two numerators. To be exact it's second to last numerator plus last numerator multiplied by a factor. And factor can be basically taken from array `[1, 1, 2k]`, in a way that every 3rd time factor is different than `1` and third element gets increased by `2`.

By writing this I just realized denominator calculation is not needed for anything here. I guess it could stay for a completeness sake. What do you think?

**Review by moT01 — APPROVED** [review]
LGTM 🎉 

Are you referring to the denominator calculation in your solution @gikf? If you want to modify it, that's up to you. I'm fine with it either way.

**Pull request merged**
