### PR TITLE
Clicking certifcate links on the profile or timeline now open in a new tab

### LINKED ISSUE #39127: Audit navigation (opening new tabs only when necessary)
You can go to [my profile](https://www.freecodecamp.org/mot01) and click on one of the certifications - it opens in the current tab. The only way to go back is to use the browsers back button. Seems like those should open in a new tab.

### PR DESCRIPTION
**Pull request by DavidJSykes**
Checklist:

- [x] I have read [freeCodeCamp's contribution guidelines](https://contribute.freecodecamp.org).
- [x] My pull request has a descriptive title (not a vague title like `Update index.md`)
- [x] My pull request targets the `master` branch of freeCodeCamp.
- [x] All the files I changed are in the same world language, for example: only English changes, or only Chinese changes, etc.

Closes #39127

### CODE REVIEW

**Review by PeterF521 — APPROVED** [review]

**Review by raisedadead — CHANGES_REQUESTED** [review]
The `Link` component has a prop to open a link in a new tab. You should use instead of setting this behaviour explicitly.

Also it would be nice to have the tests / linting working. You can verify this by running freeCodeCamp locally or on GitPod. Editing off of GitHub is not the best way.

Goodluck, and if you need help please checkout our contributing guidelines. We have a lot of information about your needs.

**Comment by raisedadead** [comment]
Hey @DavidJSykes not sure why you closed the PR. This was a good start, if you need help you can find us in the  [chat room](https://gitter.im/FreeCodeCamp/Contributors) or [subforum](https://www.freecodecamp.org/forum/c/contributors) for contributors.

**Comment by DavidJSykes** [comment]
@raisedadead I was very confused as to how to modify it and ended up making a right mess, I will be able to give it a proper go again tomorrow after I set it all up locally and do it properly :)

**Comment by raisedadead** [comment]
No worries, we are around to help you. Please reach us via the links I shared in the previous comments. 

Good luck and looking forward to a PR from you.

**Pull request closed without merging**
