### PR TITLE
Fix/add a stricter test for the Add Placeholder Text to a Text Field challenge

### LINKED ISSUE #35543: Need a stricter test for the Add Placeholder Text to a Text Field challenge
This is an issue raised by @huyenltnguyen on PR #26458.

The tests pass even for invalid code (adding the closing </input> tag).  We need to discuss here what the best "fix" is for this issue.  It could be a modification an existing test or adding a new test which checks to make sure the user's code does not have a `</input>` tag after the `<input>` tag. 

Once we finalize what the fix should do, we will attach a `Help Wanted` label on this issue.  Please wait until we have added this label before creating PRs for this issue.

Thank you.

### PR DESCRIPTION
**Pull request by minggas**
- [X] I have read [freeCodeCamp's contribution guidelines](https://github.com/freeCodeCamp/freeCodeCamp/blob/master/CONTRIBUTING.md).
- [X] My pull request has a descriptive title (not a vague title like `Update index.md`)
- [X] My pull request targets the `master` branch of freeCodeCamp.
- [X] None of my changes are plagiarized from another source without proper attribution.
- [X] All the files I changed are in the same world language (for example: only English changes, or only Chinese changes, etc.)
- [X] My changes do not use shortened URLs or affiliate links.

Closes #35543

### CODE REVIEW

**Comment by RandellDawson** [comment]
@minggas Although it is an edge case, if a user puts anything after a valid input, the last test fails.
```
  </ol>
  <input type="text" placeholder="cat photo URL"/>cat 
</main>
```

**Comment by minggas** [comment]
Ok, so the regex should be the same that I use in the new test? That way it only fails if the user put a closing tag.

**Comment by moT01** [comment]
Additionally here, the "The finished input element should have valid syntax." test should pass when there's a closing input tag (`</input>`) - which it does not - see photos.
Screen Shot 2019-07-02 at 9 50 31 AM
Screen Shot 2019-07-02 at 9 51 43 AM

Perhaps, this is out of the issue scope. I'm going to take a look at this since we have not heard back from the author here.

**Comment by moT01** [comment]
I added some changes here - I think it should work good enough.

**Review by RandellDawson — APPROVED** [review]
After @moT01's latest changes, everything seems to work fine now.

**Review by Manish-Giri — APPROVED** [review]
Tested locally, LGTM.

@minggas @moT01 Thank You for your contributions!

**Pull request merged**
