### PR TITLE
feat(/settings): Add warning for uppercase username

### LINKED ISSUE #39697: Capitalized letters in username silently gets converted to lowercase
**Describe the bug**

While writing tests with Cypress, I found that in the `/settings` page when you try to change your username with a capital letter, it silently get's converted to lowercase. For example: if `Quincy` was input, it get's converted to `quincy`.

**To Reproduce**
1. Go to '/setting'
2. Click on the username change input and enter a username with capital letter
3. Click `Save`
4. See the issue

**Expected behavior**

It should show an error message or warn the user that capital letters in name will get converted to lowercase.

### PR DESCRIPTION
**Pull request by Twaha-Rahman**
Checklist:

- [x] I have read [freeCodeCamp's contribution guidelines](https://contribute.freecodecamp.org).
- [x] My pull request has a descriptive title (not a vague title like `Update index.md`)
- [x] My pull request targets the `master` branch of freeCodeCamp.
- [x] All the files I changed are in the same world language, for example: only English changes, or only Chinese changes, etc.

Closes #39697

### CODE REVIEW

**Comment by ojeytonwilliams** [comment]
Would it be possible to have this only show when the validation detects an uppercase character?

**Comment by Twaha-Rahman** [comment]
> Would it be possible to have this only show when the validation detects an uppercase character?

@ojeytonwilliams I don't think it is possible as you can't even type capital characters in the input field as reported [here](https://github.com/freeCodeCamp/freeCodeCamp/issues/39697#issuecomment-699170796).

**Comment by raisedadead** [comment]
Let me get back to you on this.

**Comment by raisedadead** [comment]
Closing this stale for now, for a head branch rename. Thanks for your PR.

**Pull request closed without merging**
