### PR TITLE
fix: Fix navbar break

### LINKED ISSUE #15839: Navbar breaks at 768px to 786px
#### Screenshot

breaks

### PR DESCRIPTION
**Pull request by texas2010**
#### Pre-Submission Checklist

- [x] Your pull request targets the `staging` branch of freeCodeCamp.
- [x] Branch starts with either `fix/`, `feature/`, or `translate/` (e.g. `fix/signin-issue`)
- [x] You have only one commit (if not, [squash](http://forum.freecodecamp.org/t/how-to-squash-multiple-commits-into-one-with-git/13231) them into one commit).
- [ ] All new and existing tests pass the command `npm test`. Use `git commit --amend` to amend any fixes.

#### Type of Change

- [x] Small bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds new functionality)
- [ ] Breaking change (fix or feature that would change existing functionality)
- [ ] Add new translation (feature adding new translations)

#### Checklist:

- [x] Tested changes locally.
- [x] Closes currently open issue (replace XXXX with an issue no): Closes #15839

#### Description

screen shot 2017-09-18 at 6 59 33 pm

### CODE REVIEW

**Comment by texas2010** [comment]
I am not sure if I need to add `and (max-width: 810px)` in the `@media`

**Comment by texas2010** [comment]
I add max-width: 850px

**Comment by QuincyLarson** [comment]
@texas2010 Hm... I'm still encountering a situation where it wraps. 

Could you figure out a way to ensure that it never wraps?

freecodecamp_


I don't understand why the username hex code shows up in the Navbar. @raisedadead do you know what could be causing this?

**Comment by texas2010** [comment]
@QuincyLarson I was playing around with CSS. I could put it on no wraps. Somehow I have an issue with overflow scroll. so it is bad. :(  so I can't figure out what another way is.

I could change padding left and right to 4px in the link of the navbar right. more shrink between links side.

**Comment by raisedadead** [comment]
@QuincyLarson the user hex code shows up because it's added in this file https://github.com/freeCodeCamp/freeCodeCamp/blob/staging/common/app/Nav/Nav.jsx

That said you should probably do a rebase to get the latest copy.

**Comment by QuincyLarson** [comment]
@raisedadead I'm still trying to catch up on everything after the birth of my son last week. In the interest of time and getting @texas2010's PR properly QA'd, would you be interested in QA this? And once any problems are worked out, could you merge it?

**Comment by raisedadead** [comment]
@QuincyLarson sure, I'll test this as soon as I can.

**Review by raisedadead — CHANGES_REQUESTED** [review]
@texas2010 This fix, does not work. Could please take another look at it?

I would also advice if you are unable then, please close  this PR in that case.

**Comment by texas2010** [comment]
Yeah. I agree. more like I would close this PR. I can't figure out how to solve this problem. since there have too many links and unknown char in the username. oh well.

**Pull request closed without merging**
