### PR TITLE
Remove irrelevant and duplicate guides from the php guide

### PR DESCRIPTION
**Pull request by stephangrobler**
There is no PHP related examples in here, AJAX is more a technology that should better suited to go under JS and HTML guides.

- [ x ] I have read [freeCodeCamp's contribution guidelines](https://github.com/freeCodeCamp/freeCodeCamp/blob/master/CONTRIBUTING.md).
- [ x ] My pull request has a descriptive title (not a vague title like `Update index.md`)
- [ x ] My pull request targets the `master` branch of freeCodeCamp.
- [ x ] None of my changes are plagiarized from another source without proper attribution.
- [ x ] My article does not contain shortened URLs or affiliate links.

If your pull request closes a GitHub issue, replace the XXXXX below with the issue number.

Closes #XXXXX

### CODE REVIEW

**Comment by scissorsneedfoodtoo** [comment]
@stephanfx, thank you for taking the time to clean up the PHP section. I just merged a PR that consolidated a few of the articles you're deleting here, so it's causing merge conflicts here. Also, I don't think that deleting the AJAX file is right here. Would you mind moving it to the JavaScript section of the guide?

With all of those things mentioned above it seems like the easiest thing to do is to close this PR and start again. Sorry, I know it's a lot of trouble and I hope you don't mind. It might be easier if you submit two separate PRs next time, one for moving the AJAX article and another for consolidating / deleting the PHP articles. Please go ahead and submit those PRs when you have a chance!

**Comment by stephanfx** [comment]
@scissorsneedfoodtoo Hi, thanks for reviewing this PR, my question now though, should I merge the things you merged into my fork, I should I just re-fork and re-do the changes?

**Comment by scissorsneedfoodtoo** [comment]
@stephanfx, whichever is easier for you! I would recommend starting over from scratch and making sure you are working off of a unique branch. You can take a look at the [How to work on Guide articles](https://github.com/freeCodeCamp/freeCodeCamp/blob/master/docs/how-to-work-on-guide-articles.md) doc for more information. That's not a strict requirement, though.

It seems like you're experienced with Git, though, so you could continue your work here if you would rather do that. To update this PR, first rebase with the newest version of the master branch by running `git pull --rebase upstream master`. Next, fix the merge conflicts and force push back to your branch with `git push -f origin master`. Then we should see your changes reflected here.

**Comment by scissorsneedfoodtoo** [comment]
@stephanfx, thank you for fixing those merge conflicts so quickly!

I'm sorry, but would you mind making one more change? The example and output sections from the [Switch Statement](https://github.com/freeCodeCamp/freeCodeCamp/blob/f8267a257ae6c6b65a9b136bdb57cc35f44002a0/guide/english/php/switch-statement/index.md) article look really good. Would you mind moving both of those sections to the end of the remaining [Switch](https://github.com/freeCodeCamp/freeCodeCamp/blob/f8267a257ae6c6b65a9b136bdb57cc35f44002a0/guide/english/php/switch-statement/index.md) article? Let me know what you think.

**Comment by stephanfx** [comment]
@scissorsneedfoodtoo I think I made a boo boo... may have to start overs anyway... did make the change though, if you can check that, I'll redo if necessary

**Comment by scissorsneedfoodtoo** [comment]
@stephanfx, oh shoot! I've done the same, no worries. It might just be that `git pull upstream master` was run rather than `git pull --rebase upstream master`. Do you know how to use `git reflog` to do a hard reset?

We could try that to see if we can fix things. If not, feel free to close this PR, open a new one with all of your changes, then just ping me from there.

**Comment by scissorsneedfoodtoo** [comment]
@stephanfx, that was fast! Everything LGTM!

That's a good question about the review. I'm really not sure. Might have been automatic?

**Comment by stephanfx** [comment]
@scissorsneedfoodtoo oh, common, now there is conflicts... again?

**Comment by scissorsneedfoodtoo** [comment]
@stephanfx, sorry, I just noticed the merge conflict, too. Hope you don't mind, but I solved it locally and pushed it back to your branch. Also, I ended up restoring the Basic Syntax article because there was some valuable information about case sensitivity that was added recently. Hope to get this merged soon!

**Comment by stephanfx** [comment]
> 
> 
> @stephanfx, sorry, I just noticed the merge conflict, too. Hope you don't mind, but I solved it locally and pushed it back to your branch. Also, I ended up restoring the Basic Syntax article because there was some valuable information about case sensitivity that was added recently. Hope to get this merged soon!

No problem what so ever, just glad to get it in there, feels good to contribute! I will be doing it much smaller and with branches :D

**Pull request merged**
