### PR TITLE
Minor rephrasing of the lesson's description

### PR DESCRIPTION
**Pull request by kevindelsh**
Since we already said in the last lesson that bootstraps col-xs-* classes can be used on all form elements it sounds silly to repeat the exact same phrase in this lesson too.

- [x] I have read [freeCodeCamp's contribution guidelines](https://github.com/freeCodeCamp/freeCodeCamp/blob/master/CONTRIBUTING.md).
- [x] My pull request has a descriptive title (not a vague title like `Update index.md`)
- [x] My pull request targets the `master` branch of freeCodeCamp.
- [x] None of my changes are plagiarized from another source without proper attribution.
- [x] All the files I changed are in the same world language (for example: only English changes, or only Chinese changes, etc.)
- [x] My changes do not use shortened URLs or affiliate links.

### CODE REVIEW

**Comment by RandellDawson** [comment]
@kevindelsh Please review the [Style Guide for Guide Articles](https://github.com/freeCodeCamp/freeCodeCamp/blob/master/docs/style-guide-for-guide-articles.md#point-of-view).  The point of view should be second person.

**Comment by kevindelsh** [comment]
Hey @RandellDawson, thank you for letting me know. Just made the edits. Please, let me know if there are other shortcomings.

**Review by thecodingaviator — APPROVED** [review]
LGTM! 👍

**Review by RandellDawson — CHANGES_REQUESTED** [review]
@kevindelsh Your additions look fine, but I noticed something that has not been correct for quite some time.  The sentence which starts with `Nest all three ...` should actually be in the Instructions section.  Please update the challenge so the Description and Instructions sections look like:
```
## Description
<section id='description'>
  Since Bootstrap's <code>col-xs-*</code> classes are applicable to all <code>form</code> elements, you can use them on your checkboxes too! This way, the checkboxes will be evenly spread out across the page, regardless of how wide the screen resolution is.
</section>

## Instructions
<section id='instructions'>
Nest all three of your checkboxes in a <code>&#60;div class="row"&#62;</code> element. Then nest each of them in a <code>&#60;div class="col-xs-4"&#62;</code> element.
</section>
```

**Comment by kevindelsh** [comment]
Hey @RandellDawson, just made the required changes!

**Review by RandellDawson — APPROVED** [review]

**Comment by RandellDawson** [comment]
I approve of this PR's verbiage change and I have tested it locally to validate it displays correctly.

**Review by ezioda004 — APPROVED** [review]

**Comment by ezioda004** [comment]
Thank you @kevindelsh for your contribution and congratulations on your first PR merge to this repo! 🎉
Hope to see more contributions from you in the future.

**Pull request merged**
