### PR TITLE
Removed an unnecessary word in "Learn HTML by Building a Cat Photo App" - Step 36

### LINKED ISSUE #44618: The challenge description contains an unnecessary word in "Learn HTML by Building a Cat Photo App" - Step 36
## Affected page
(https://www.freecodecamp.org/learn/2022/responsive-web-design/learn-html-by-building-a-cat-photo-app/step-36)

## System

- Device: [Laptop]
- OS: [Kubuntu 21.10 x86]
- Browser: [chrome]

## Additional context

The challenge description contains an unnecessary word:
The input element **~~is allows~~** you several ways to collect data from a web form. 

### The correct way can be:
**Proposal 1**: The input element gives you several ways to collect data from a web form. 
**Proposal 2**: The input element offers you several ways to collect data from a web form. > #44619

I am not a native english speaker. Please let me know if that is an error and if there are other ways to formulate it. Thank you for your patience and your work. 

This is my solution pull request: #44619

### PR DESCRIPTION
**Pull request by senthusiva**
Checklist:

- [x] I have read [freeCodeCamp's contribution guidelines](https://contribute.freecodecamp.org).
- [x] My pull request has a descriptive title (not a vague title like `Update index.md`)
- [x] My pull request targets the `main` branch of freeCodeCamp.
- [x] I have tested these changes either locally on my machine, or GitPod.

Closes #44618

#### Affected page
(https://www.freecodecamp.org/learn/2022/responsive-web-design/learn-html-by-building-a-cat-photo-app/step-36)

The challenge description contains an unnecessary word:
The input element **~~is allows~~** you several ways to collect data from a web form. 

### The correct way can be:
**Proposal 1**: The input element **offers** you several ways to collect data from a web form.

### CODE REVIEW

**Review by jdwilkin4 — CHANGES_REQUESTED** [review]
Hi @senthusiva ! 

I think it works to say, "The input element allows you several ways"

**Comment by senthusiva** [comment]
> Hi @senthusiva !
> 
> I think it works to say, "The input element allows you several ways"

Hello @jdwilkin4 
You are right. I modified the file. 
Thank you for your help :)

**Review by jdwilkin4 — APPROVED** [review]
LGTM 👍

**Comment by gikf** [comment]
Hey @senthusiva

This PR seems to make similar changes as the existing PR #44592. As such, we are going to close this as duplicate.

If you feel you have additional changes to expand upon this PR, please feel free to push your commits and request this PR be reopened.

Thanks again! 😊

---

If you have any questions, feel free to ask questions on the ['Contributors' category on our forum](https://forum.freecodecamp.org/c/contributors) or [the contributors chat room](https://chat.freecodecamp.org/channel/contributors).

**Pull request closed without merging**
