### PR TITLE
feat(prettier): Prettier all the things

### PR DESCRIPTION
**Pull request by Bouncey**
Adds `prettier` and `eslint --fix` to the commit hook. This should reduce failed CI checks due to formatting.

### CODE REVIEW

**Comment by raisedadead** [comment]
Should we be adding the auto formatting to the commit hooks? https://prettier.io/docs/en/precommit.html I have had this on some of my projects, and saves me a ton of time?

**Comment by Bouncey** [comment]
I have it in the precommit, but it is a bit more hacky than what you have pointed out. 

I will refactor

**Comment by raisedadead** [comment]
> I have it in the precommit, but it is a bit more hacky than what you have pointed out.

Oh, I did not know that, can you guide any potential issues that might happen? Or if you would need any help?

**Comment by Bouncey** [comment]
Prittier cannot fix this

```js
  User.definition.rawProperties.rand.default = User.definition.properties.rand.default = function() {
    return Math.random();
  };
```

So `eslint` will throw an error aborting the commit because of the `max-len` rule. 

So manual refactores are required, i. e.

```js
  const randomNumber = () => Math.random();
  User.definition.rawProperties.rand.default = randomNumber;
  User.definition.properties.rand.default = randomNumber;
```

**Comment by BerkeleyTrue** [comment]
@Bouncey How long does this take to run? It might be a hassle to use on precommit. I've had a similar setup on other projects and found it was to slow for precommit. Prepush would be much better, with a push rejection if lint changes creates unstaged changes? Is that doable?

**Comment by BerkeleyTrue** [comment]
Also, it will be easier to get this merged in if you do the actual lint run on a separate PR after this get's merged in. Or wait for a QA before adding a lint run commit.

**Comment by raisedadead** [comment]
Hi @Bouncey I am closing this off for now.

**Pull request closed without merging**
