### PR TITLE
Add forum Topic Id for rosetta code

### LINKED ISSUE #38629: Add forum topic ID to rosetta challenges
I noticed that @NitronR has added a ton of content to mostly the rosetta code section (thanks BTW). You can see a [list of his PR's here](https://github.com/freeCodeCamp/freeCodeCamp/pulls?q=is%3Apr+author%3AnitronR+is%3Aclosed). I did forum search for a couple of the challenges and it looks like guide pages have been created, but I noticed that the `forumTopicId` wasn't added to many of the challenges. We should go through those PR's and add the `forumTopicId` field to the frontmatter and make sure a guide page is created. If the PR is getting large, it might be a good idea to break it up into several.

### PR DESCRIPTION
**Pull request by rajatgupta24**
Checklist:

- [ ] I have read [freeCodeCamp's contribution guidelines](https://contribute.freecodecamp.org).
- [ ] My pull request has a descriptive title (not a vague title like `Update index.md`)
- [ ] My pull request targets the `master` branch of freeCodeCamp.
- [ ] All the files I changed are in the same world language, for example: only English changes, or only Chinese changes, etc.

Closes #38629

### CODE REVIEW

**Review by moT01 — CHANGES_REQUESTED** [review]
See issue

**Comment by moT01** [comment]
Can you add the other 5 challenges I linked in the issue to this @rajatgupta24?

**Review by moT01 — CHANGES_REQUESTED** [review]
- If you added all the same files onto this PR from your other PR, you can close the other PR.
- You should complete the checklist in the PR template, put an `x` in all the `[ ]` if they are true
- something was merged to create conflicts for all these so it can't be merged as-is,
  you should try and fix those conflicts.

Edit: ignore all this here, it belongs on your other PR

**Comment by moT01** [comment]
I have blocked this for now. See the [pinned code freeze issue](https://github.com/freeCodeCamp/freeCodeCamp/issues/38308)

**Comment by raisedadead** [comment]
The source repo is deleted.

**Pull request closed without merging**
