### PR TITLE
feat(interview-prep): Adding Rosetta Code problems

### PR DESCRIPTION
**Pull request by NitronR**
- [ ] I have read [freeCodeCamp's contribution guidelines](https://github.com/freeCodeCamp/freeCodeCamp/blob/master/CONTRIBUTING.md).
- [ ] My pull request has a descriptive title (not a vague title like `Update index.md`)
- [ ] My pull request targets the `master` branch of freeCodeCamp.
- [ ] None of my changes are plagiarized from another source without proper attribution.
- [ ] All the files I changed are in the same world language (for example: only English changes, or only Chinese changes, etc.)
- [ ] My changes do not use shortened URLs or affiliate links.

Closes #XXXXX

### CODE REVIEW

**Comment by NitronR** [comment]
@scissorsneedfoodtoo Added some more Rosetta Code problems. I cleaned the \<p\> tags this time so that you can review these easily. Thank you for your help!

**Comment by scissorsneedfoodtoo** [comment]
@NitronR, sorry for taking so long to review these problems. Everything LGTM! Thank you for all of your hard work and looking forward to whatever is next :+1: :+1:

**Comment by NitronR** [comment]
@scissorsneedfoodtoo Thank you for helping out with this! This was the last set of Rosetta code problems!!

Here's what we got to do next:
1. Convert and move the problems from the feat/interview-prep branch of the curriculum repository. [Here](https://github.com/freeCodeCamp/curriculum/blob/feat/interview-prep/challenges/08-coding-interview-prep/rosetta-code.json) is that particular file.
2. Convert and review the problems from [this](https://github.com/freeCodeCamp/curriculum/pull/322) pull request that was left out in the curriculum repo.
3. [This](https://docs.google.com/spreadsheets/d/1b_wMIaKR-gA0tD6ADQfDjDT5BBWaUsQyIPP0TS6o7is/edit#gid=0) spreadsheet contains the list of Rosetta code challenges. We have to review if any of the excluded problems can be modified so that they can be included.

This should wrap up the Rosetta code part :)
Note: The problems in step 1. are already reviewed by you. Is another review going to be necessary?

**Comment by METALMAN01** [comment]
no

**Comment by scissorsneedfoodtoo** [comment]
@NitronR, nice work! You did a lot to bring all of these problems over. The end is definitely in sight haha.

That sounds great! Doing everything in that order makes the most sense, especially since we already reviewed the problems in step 1. Another review is not totally necessary, but I'd just like to take a quick look at them locally to make sure everything works.

And sorry, but I still have to go back and fix the problems from https://github.com/freeCodeCamp/curriculum/pull/288.

**Comment by NitronR** [comment]
@scissorsneedfoodtoo Great, Let's do this! I will start converting and moving the problems from step 1 then.

**Comment by scissorsneedfoodtoo** [comment]
Cool! Just hit me up whenever you're ready. I'll have a lot more free time over the next couple of weeks so let's knock these challenges out :+1: :+1:

**Pull request merged**
