### PR TITLE
Added Pong Game as a project.

### PR DESCRIPTION
**Pull request by satyamchaudharydev**
#### Pre-Submission Checklist

- [x] Your pull request targets the `staging` branch of freeCodeCamp.
- [ ] Branch starts with either `fix/`, `feature/`, or `translate/` (e.g. `fix/signin-issue`)
- [x] You have only one commit (if not, [squash](http://forum.freecodecamp.org/t/how-to-squash-multiple-commits-into-one-with-git/13231) them into one commit).
- [ ] All new and existing tests pass the command `npm test`. Use `git commit --amend` to amend any fixes.

#### Type of Change

- [ ] Small bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds new functionality)
- [ ] Breaking change (fix or feature that would change existing functionality)
- [ ] Add new translation (feature adding new translations)

#### Checklist:

- [ ] Tested changes locally.
- [ ] Addressed currently open issue (replace XXXXX with an issue no in next line)

#### Description

I have added pong game as a project. I didn't add translation as of yet. Thanks @QuincyLarson for giving me chance to contribute. 😄

### CODE REVIEW

**Comment by scissorsneedfoodtoo** [comment]
Hi @satyamchaudharydev,

Thank you for your submission. Really great work here! Building a pong game is an awesome idea for a project, and I had fun playing your game on Codepen. Your AI really is unbeatable!

I would just like to suggest a few small changes to your code.

First, could you change the id for your challenge? Here's a unique one that works on my computer:

`"id": "5a471f7cb1533218be62dc68",`

Next, let's change the title just a bit:

`"title": "Build a Pong Game",`

Also, let's change a couple of your user stories and add one more about the game score:

`"<strong>User Story:</strong> I can control a paddle.",
        "<strong>User Story:</strong> The computer can control the other paddle.",
        "<strong>User Story:</strong> The computer's paddle is unbeatable. It should never miss the ball.",
        "<strong>User Story:</strong> The game keeps track of the player and computer's score.",`

Finally, I think we'll need a new challengeSeed. Unfortunately, I don't know how to generate one. @BerkeleyTrue and @raisedadead, do you know how to generate a new one?

**Comment by raisedadead** [comment]
Hi @scissorsneedfoodtoo thanks for taking the time to QA this. 

And nice catch about the challenge id. We should probably add a test if not already for checking conflicting challenge id.

To generate a new one in a shell (assuming MongoDB is running separately):

1. Run `mongo` command
2. Run `ObjectId()` command

Output:

```sh
$ mongo
MongoDB shell version v3.6.1
connecting to: mongodb://127.0.0.1:27017
MongoDB server version: 3.4.10
...
$ ObjectId()
ObjectId("5a474d78df58bafeb3535d34")
```

The result is a new id, for example `"5a474d78df58bafeb3535d34"` above.

**Comment by raisedadead** [comment]
@satyamchaudharydev 

Thanks a lot for taking the the time to contribute and preparing this PR.
However, we are going to have to close this as this made over GitHub interface and hence not tested locally, by running the Dev server (`npm run develop`).

We understand that you are doing this for the first time to this code-base, sincerely appreciate the effort.

Please follow our [Guidelines for Contributing](https://github.com/FreeCodeCamp/FreeCodeCamp/blob/staging/CONTRIBUTING.md) to make a fresh request and reach us in [Contributors Chat room](https://gitter.im/FreeCodeCamp/Contributors) for any assistance needed, we are happy to help you through this.

Apart from the code changes done for the new challenge, we need a new id which can be generated like in my earlier comment.

We should update our guide to make this more clear in future.

Thanks and happy contributing!

**Comment by scissorsneedfoodtoo** [comment]
Hi @raisedadead, thank you for your thorough comments!

Yes, maybe some checks for conflicting challenge ids when a pull request is submitted would help prevent future issues. I only caught it when running `npm test` locally.

When testing this challenge I found that the challengeSeed array was the same as an earlier challenge. Is there a way to generate a unique challengeSeed array, too?

@satyamchaudharydev, let us know if you need help editing and testing your challenge!

**Comment by QuincyLarson** [comment]
@satyamchaudharydev Have you had a chance to look at this feedback? You are 90% of the way there, and we're eager to merge this.

I can make these changes for you, but I'd rather you get credit for your contribution. Please let me know if there's anything I can do to help.

**Comment by satyamchaudharydev** [comment]
Been bit busy with the school will make PR today.

**Comment by raisedadead** [comment]
@satyamchaudharydev thanks for updating us. Please make a fresh PR with the feedback above. Hapyy contributing.

**Pull request closed without merging**
