### PR TITLE
feat(learn): Add Challenge "Check if Tree is Binary Search"

### PR DESCRIPTION
**Pull request by candacej97**
- [x] I have read [freeCodeCamp's contribution guidelines](https://github.com/freeCodeCamp/freeCodeCamp/blob/master/CONTRIBUTING.md).
- [x] My pull request has a descriptive title (not a vague title like `Update index.md`)
- [x] My pull request targets the `master` branch of freeCodeCamp.
- [x] None of my changes are plagiarized from another source without proper attribution.
- [x] All the files I changed are in the same world language (for example: only English changes, or only Chinese changes, etc.)
- [x] My changes do not use shortened URLs or affiliate links.

We believe that this challenge is necessary because it ties together the BST challenges and reinforces the principles of indicating a BST from any other tree. We have tested the challenge.

### CODE REVIEW

**Comment by RandellDawson** [comment]
@candacej97 Can you please clean up the commit history?  Also, you are creating a PR from a branch which is not your own and your solution fails one of the tests.

**Comment by candacej97** [comment]
Hi @RandellDawson this branch is from the fork of my open source development course. We're trying to contribute to open source projects.

What do you mean by "clean up the commit history"? Should we be rebasing to our fork's master then try to have it be pulled upstream?

**Comment by RandellDawson** [comment]
Well, you have 36 commits and many of the commits have nothing to do with the files you changed.  You should probably `git --rebase upstream master` and then force push back to clean up the history.  Also, you really should be pushing from your own branch and not someone else's branch.  

Lastly, the solution you wrote fails one of the tests, so you will need to fix that as well.

**Comment by RandellDawson** [comment]
@candacej97 One other thing, an earlier PR (#35825) already adds a solution for this challenge, so you can leave that file off this PR.

**Pull request closed without merging**
