### PR TITLE
fix: stop injecting extra comments into preview

### PR DESCRIPTION
**Pull request by ojeytonwilliams**
Checklist:

- [x] I have read [freeCodeCamp's contribution guidelines](https://contribute.freecodecamp.org).
- [x] My pull request has a descriptive title (not a vague title like `Update index.md`)
- [x] My pull request targets the `main` branch of freeCodeCamp.
- [x] I have tested these changes either locally on my machine, or GitPod.

As mentioned by @bbsmooth in https://github.com/freeCodeCamp/freeCodeCamp/pull/44720 these comments only make it harder to write tests for steps, not easier.

### CODE REVIEW

**Review by ShaunSHamilton — APPROVED** [review]
LGMT 👍 

---

I still really want the gap between our preview and a native browser/dev page to shrink.

Although, I think the next step is to append the `style` tags before the `body` - not within.

**Comment by ojeytonwilliams** [comment]
Does it particularly matter if the scripts go in the head or the body?  AFAIK, those are the only choices and it doesn't seem obvious that we should be choosing one over the other.

**Comment by ShaunSHamilton** [comment]
> Does it particularly matter if the scripts go in the head or the body? AFAIK, those are the only choices and it doesn't seem obvious that we should be choosing one over the other.

Yes, it does matter. Practically, because of priority - for our current _learner workflow_ only affected by browser extensions. Unpractically, it is still an issue, because the Campers do not write it in that order, and it is not standard practice.

**Comment by ojeytonwilliams** [comment]
> for our current learner workflow only affected by browser extensions

Could you elaborate? What changes if you move the script elements around?

> because the Campers do not write it in that order, and it is not standard practice.

Well, modern practice is to put scripts into the head and load them asynchronously, but that's a performance optimisation.  The only thing we require of campers is that they add a script element *somewhere*.  We don't check where, so they're free to write it how they want to.

In principle, if it seems valuable, we can start injecting the script into the body or head of the preview conditionally, depending on where the camper puts it.

**Comment by ShaunSHamilton** [comment]
> Could you elaborate? What changes if you move the script elements around?

Well, moving `script` elements around is a definite "no no", because, unless deferred, the script could try accessing elements which have yet to be attached to the DOM.

But, moving `style` elements around is only a problem when you have multiple sources of stylesheets (either multiple `style` elements, or multiple `link` elements). So, for our learner workflow, we do not generally have this save for the one lesson when we introduce the `styles.css` file, and both exist at the same time. However, I was more mentioning that this behaviour is non-standard.

> In principle, if it seems valuable, we can start injecting the script into the body or head of the preview conditionally, depending on where the camper puts it.

Right. I vote for just mimicking browser behaviour - let the browser handle this. The thing is, we currently force it to be within the `body` tag.

_Remember, I am talking about the `style` element. Not the `script` element_ (I have not tested those). Also, this is not a part of this PR.

**Comment by ojeytonwilliams** [comment]
>  `style` element. 

Well, why didn't you... oh you did say that.  Sorry!  

You're quite right, we should both insert style into the head and, if/when we have more than one, respect the user's order.

**Comment by nhcarrigan** [comment]
> You're quite right, we should both insert style into the head and, if/when we have more than one, respect the user's order. 

Just to confirm, are we looking at that in a separate PR? That is, is this one still good to go?

**Comment by ojeytonwilliams** [comment]
I think there were a few things to discuss, so if this PR is okay we can merge this and circle back to the style element stuff.

**Review by naomi-lgbt — APPROVED** [review]
Let's go ahead and get this in then. 🙂

**Pull request merged**
