### PR TITLE
Feature Use tap-spec in place of tap-nyancat

### PR DESCRIPTION
**Pull request by BerkeleyTrue**

### CODE REVIEW

**Comment by SaintPeter** [comment]
Ahhh, so much faster.

**Comment by SaintPeter** [comment]
BTW, is there a way to reduce the verbosity of tap-spec so it only shows failing tests?

**Comment by ltegman** [comment]
Needed to happen, but I will be sad to see nyan go :(

**Comment by BerkeleyTrue** [comment]
@SaintPeter Not sure. Didn't look into it

**Pull request merged**
