### PR TITLE
fix: Remove unnecessary comments

### PR DESCRIPTION
**Pull request by emerconn**
https://github.com/freeCodeCamp/freeCodeCamp/pull/41612

Checklist:

- [x] I have read [freeCodeCamp's contribution guidelines](https://contribute.freecodecamp.org).
- [x] My pull request has a descriptive title (not a vague title like `Update index.md`)
- [x] My pull request targets the `main` branch of freeCodeCamp.
- [x] All the files I changed are in the same world language, for example: only English changes, or only Chinese changes, etc.

### CODE REVIEW

**Comment by ojeytonwilliams** [comment]
Hi, thanks for creating this PR, but this not a change we will be making at this time.

While we cannot accept this contribution, if you would like to help out, please take a look at our [contributing guide](https://contribute.freecodecamp.org/) for other things you can do.

**Review by moT01 — DISMISSED** [review]
There's one remaining comment - I would prefer to remove it, but I don't think the instructions are clear enough to do that.

If they were changed to something like ```Using dot and bracket notation, set `secondTree` to the second item from the `trees` list of the `myPlants` variable.```

All that said, I would be fine with this PR as-is as well. LGTM 🎉

**Comment by emerconghaile** [comment]
How does this look. @moT01 ?

I removed the remaining comment and changed the wording of the instructions.

**Review by moT01 — APPROVED** [review]
LGTM 🎉

**Review by naomi-lgbt — APPROVED** [review]
Looks good to me.

**Pull request merged**
