### PR TITLE
Grammar improvements for German Contributing.md

### PR DESCRIPTION
**Pull request by Plingooo**
Text improvements regarding uppercase and lowercase.

- [x] I have read [freeCodeCamp's contribution guidelines](https://github.com/freeCodeCamp/freeCodeCamp/blob/master/CONTRIBUTING.md).
- [x] My pull request has a descriptive title (not a vague title like `Update index.md`)
- [x] My pull request targets the `master` branch of freeCodeCamp.
- [x] None of my changes are plagiarized from another source without proper attribution.
- [x] All the files I changed are in the same world language (for example: only English changes, or only Chinese changes, etc.)
- [x] My changes do not use shortened URLs or affiliate links.

Closes #XXXXX

### CODE REVIEW

**Review by martin-gnodtke — APPROVED** [review]
The changes from Plingooo are grammatically correct. Approved by a german native speaker.

**Comment by raisedadead** [comment]
Thanks for your review @Squizzi3 much appreciated.

@Plingooo 

> Would mind updating the guide to its latest as in the english version?

and, when you get a chance please update the title of the PR to be more descriptive.

Thanks once again for the PR.

**Comment by Plingooo** [comment]
Is this title meaningful enough?

**Comment by raisedadead** [comment]
> Is this title meaningful enough?

Perfect. Thanks for contributions.

**Comment by raisedadead** [comment]
One last thing though, as you may have noticed that the german version of the contribution is behind the english version. 

Can you please update the german version to be current with english. Other than that this is good to go.

**Comment by Plingooo** [comment]
I'm not sure I understand you correctly. Do you mean the completion of the guide, if so then I have already started with it. 
See PR #37133, #37130, #37126

**Comment by raisedadead** [comment]
image



The german version of Contributing guide is outdated and is behind its english counter part.

**Comment by raisedadead** [comment]
Awesome work @Plingooo ! 

@Squizzi3 can you give this one more look and we are good to hit the merge :)

**Comment by Plingooo** [comment]
Thanks @Squizzi3 

Fixed your Remarks.

**Comment by raisedadead** [comment]
Nice work folks. @Squizzi3 GitHub has a nicer way of leaving PR reviews (which will count as commits if you do it right). You can learn more about it here:
https://help.github.com/en/articles/reviewing-proposed-changes-in-a-pull-request

**Review by raisedadead — APPROVED** [review]
#### :sparkles: :sparkles: **AWESOME! LGTM.** :sparkles: :sparkles: 

Thanks @Plingooo and @Squizzi3, for this pull request and contributing to the code-base for the first time.
We will be looking forward for more contributions in future.

Cheers and happy contributing!

**Comment by Squizzi3** [comment]
> Nice work folks. @Squizzi3 GitHub has a nicer way of leaving PR reviews (which will count as commits if you do it right). You can learn more about it here:
> https://help.github.com/en/articles/reviewing-proposed-changes-in-a-pull-request

Thanks for your recommendation @raisedadead.
I thought my remarks will count as one single comment with the linenumbers. 

But good to know there are other ways to review better! :smiley:

**Pull request merged**
