### PR TITLE
Corrected challenge tests so they don't give the solution

### PR DESCRIPTION
**Pull request by thecodingaviator**
The tests previously gave away the answer to the challenge without a spoiler alert, this PR corrects that :)

- [x] I have read [freeCodeCamp's contribution guidelines](https://github.com/freeCodeCamp/freeCodeCamp/blob/master/CONTRIBUTING.md).
- [x] My pull request has a descriptive title (not a vague title like `Update index.md`)
- [x] My pull request targets the `master` branch of freeCodeCamp.
- [x] None of my changes are plagiarized from another source without proper attribution.
- [x] All the files I changed are in the same world language (for example: only English changes, or only Chinese changes, etc.)
- [x] My changes do not use shortened URLs or affiliate links.

### CODE REVIEW

**Review by paulywill — APPROVED** [review]
LGTM!

**Comment by RandellDawson** [comment]
LGTM to me too.  @Manish-Giri or @ezioda004 What do you think?

In a separate PR, maybe we should replace the existing single test with two additional tests to test if the user gets the horizontal rows lines part correct or column lines part correct?   That way, it is not an all or nothing test and the user can see how incremental changes not only the actual visual in the preview, but how that relates to seeing the correct numbers in the `grid-area` definition.  Just a thought, but if we agree, then it should definitely go in a separate PR.

**Review by ezioda004 — APPROVED** [review]

**Comment by ezioda004** [comment]
Thank you @thecodingaviator  for your contribution. Looking forward to more contributions from you! 🎉

@RandellDawson I think its fine to split the tests considering theres only 1 test in this challenge.

**Comment by RandellDawson** [comment]
@thecodingaviator OK, you can now make separate PRs for each language converting the `text` above each `testString`.  Thanks for working on this!

**Comment by thecodingaviator** [comment]
@RandellDawson @ezioda004 , PRs #35251 through #35255 make the changes

**Pull request merged**
