### PR TITLE
Regex QA: intro, text edits, assert tests working

### PR DESCRIPTION
**Pull request by HKuz**
#### Pre-Submission Checklist

- [x] Your pull request targets the `feature/curriculum-expansion` branch of FreeCodeCamp - not `staging`.
- [x] Branch starts with either `fix/`, `feature/`, or `translate/` (e.g. `fix/signin-issue`)
- [x] You have only one commit (if not, [squash](http://forum.freecodecamp.com/t/how-to-squash-multiple-commits-into-one-with-git/13231) them into one commit).
- [ ] All new and existing tests pass the command `npm run test-challenges`. Use `git commit --amend` to amend any fixes. Tests not passing in general for the branch.
#### Type of Change

- [x] New feature (non-breaking change which adds new functionality)
#### Checklist:

- [x] Tested changes locally.
#### Description

QA for Regular expressions section. Added intro text and image. Text and formatting changes for consistency. All tests working
Visual Design - edited intro text
Responsive Web Design - swapped out a photo

### CODE REVIEW

**Comment by Bouncey** [comment]
@HKuz Travis has found quite a few syntax errors there (229), but they don't all seem to be coming from RegEx challenges?

**Comment by HKuz** [comment]
@Bouncey - yes, this branch has been triggering the red X since I've started work on it. Some sections (like Basic HTML5 & CSS) with errors aren't changing much with the expansion, so I think they'll get swapped out with the latest right before this goes live. That said, I certainly don't want to be introducing issues in the sections I've worked on, and notice some of them in the report. I *thought* I had a linter running in Atom and it's been saying no issues, I'll need to double check that. For some of these errors, I'm not sure how to interpret them ("Unexpected token <" is coming up a lot in the seed/test-challenges.json for some challenges) - is there a good resource I can check out to better understand these?

**Comment by QuincyLarson** [comment]
@HKuz @Bouncey all the errors I'm getting seem to be React-specific. We can leave this PR open until their fixed, but this isn't something you need to tackle yourself. You can move on to other things :)

**Comment by Bouncey** [comment]
PR on hold.

**Comment by atjonathan** [comment]
@Bouncey, this can be merged. It's not being merged to any production or staging branch yet anyways. The curriculum expansion branch has already got syntax errors.

**Review by ghost — APPROVED** [review]

**Pull request merged**
