### PR TITLE
Add Brazilian Portuguese advanced-bonfires translations

### PR DESCRIPTION
**Pull request by frontendwizard**
#### Pre-Submission Checklist

- [x] Your pull request targets the `staging` branch of FreeCodeCamp.
- [x] Branch starts with either `fix/`, `feature/`, or `translate/` (e.g. `fix/signin-issue`)
- [x] You have only one commit (if not, [squash](http://forum.freecodecamp.com/t/how-to-squash-multiple-commits-into-one-with-git/13231) them into one commit).
- [x] All new and existing tests pass the command `npm test`. Use `git commit --amend` to amend any fixes.

#### Type of Change

- [ ] Small bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds new functionality)
- [ ] Breaking change (fix or feature that would change existing functionality)
- [x] Add new translation (feature adding new translations)

#### Checklist:

- [x] Tested changes locally.
- [ ] Closes currently open issue (replace XXXX with an issue no): Closes #XXXX

#### Description

I did the translation of the session **Advanced Algorithm Scripting** of the Front-End Development Certification to Brazilian Portuguese.

### CODE REVIEW

**Comment by raisedadead** [comment]
@julianorafael Awesome! thanks a lot for helping translate Free Code Camp to Brazilian Portuguese.
Can you get someone to do a peer review (anyone speaks Pt-Br) of the changes?

We will be happy to merge post that, you can post in the forum or look in the chat rooms also, for reviewers.

Let us know. In any case, if you do not find someone willing, we will do a sanity check of the changes and merge the code after 7-10 days.

Thanks once again and happy translating!

**Comment by julianorafael** [comment]
@raisedadead Great. I'll post in the forums to see if I can find someone. I'll do more translations this week to see if I can push the portuguese translation forward.

**Comment by naceabde** [comment]
hello

**Comment by naceabde** [comment]
how are you doing

**Comment by jolawren** [comment]
Hello!!

**Comment by raisedadead** [comment]
@naceabde @jolawren this thread is not for casual chats, please do not spam here.

**Comment by raisedadead** [comment]
@julianorafael did you get a chance to find anyone for a peer review?

**Comment by julianorafael** [comment]
I posted on the forums but no one showed up.

**Comment by raisedadead** [comment]
Sure thing no problem, will do a sanity check and merge, thanks a lot for your hard work.

**Comment by QuincyLarson** [comment]
@julianorafael these look great! Thanks!

**Pull request merged**
