### PR TITLE
feat: add toggle nav 

### LINKED ISSUE #36825: Challenges are not mobile friendly
This wasn't always the case, but right now the formatting for smaller screens isn't great:

Resize

Smaller screens used to have tabs letting you switch between the instructions, editor and so on.  You can see them briefly (in the gif) at medium screen sizes, but not for mobile.

If we still want to support this, I can look into restoring it.

### LINKED ISSUE #37021: Remove the highlight on hover on the nav logo.
image

Remove the highlight on hover on the nav logo.

### PR DESCRIPTION
**Pull request by ahmaxed**
This pr would re-introduce toggle navigation for small screens.
also adjusts the breakpoints for search

Closes #36825
Closes #37021

### CODE REVIEW

**Review by ojeytonwilliams — CHANGES_REQUESTED** [review]
Hey @ahmadabdolsaheb.  It's looking great.

Aside from the css thing, I was wondering if it would be better to redo `handleOutsideClick` like this:

```js
  handleClickOutside(event) {
    if (
      this.state.displayMenu &&
      this.menuButtonRef.current &&
      !this.menuButtonRef.current.contains(event.target) &&
      this.searchBarRef.current &&
      !this.searchBarRef.current.contains(event.target)
    ) {
      this.toggleDisplayMenu();
    }
  }
```
Obviously it would mean passing another ref around, but referencing the `id` directly doesn't seem quite right.  It feels like an implementation detail, to me.  I'm not sure, though, what do you reckon?

**Comment by ojeytonwilliams** [comment]
@ahmadabdolsaheb thanks for making those changes, I can fix the lint errors (seeing as I created them).

As for refs vs id, we don't need to change that here.  If you think it's worth doing, I can do the refactoring in another PR (it's hardly urgent).

**Comment by ahmadabdolsaheb** [comment]
@ojeytonwilliams Thank you for reviewing this pr.
We could change handleClickOutside in another PR if you prefer.

**Review by ojeytonwilliams — APPROVED** [review]
LGTM :+1:

**Pull request merged**
