### PR TITLE
404 page sample for review

### PR DESCRIPTION
**Pull request by mikestratton**
Backlog issue #1504 - Sample 404 page with fire animation over the campfire portion of logo.

### CODE REVIEW

**Comment by bugron** [comment]
@mikestratton this is an interesting idea, **but**,
1. you can get jQuery from Cloudflare CDN and not store it locally,
2. you should move `404_fire_animation` folder into `public` folder,
3. you should actually redirect to your 404 page in `user.js` (function `returnUser`),
3. I don't think that [a blank page with burning logo](http://prntscr.com/8odrpi) is a good 404 page, sorry.

**Comment by mikestratton** [comment]
Hello Arsen,
 
This was not intended to be the complete 404 page. This was just a sample to get some feedback.
 
 
 
 
 
 
Michael A. Stratton
Freelance Web Developer
 
Web: http://www.mikestratton.net
Email: mike@mikestratton.net
Cell: (330)802-0285

 
 
--------- Original Message --------- Subject: Re: [FreeCodeCamp] 404 page sample for review (#3599)

**Comment by mikestratton** [comment]
@bugron In regards to branching - I followed the directions listed here: https://github.com/Kunena/Kunena-Forum/wiki/Create-a-new-branch-with-git-and-manage-branches Did I miss something?

Thanks, Mike Stratton

**Comment by bugron** [comment]
@mikestratton that article is about how to work with branches but you need to read our [Contributing Guidelines](https://github.com/FreeCodeCamp/FreeCodeCamp#contributing) to know how to name them correctly and more. For example, in this case the name of the branch could be something like `feature/implement-404-page`.
Now about the topic itself. Let me know if you will work on this so I'll know close this PR or not. Actually, there are lots of examples of 404 pages in net, so I think there is no need to create a PR to discuss this. Thanks.

**Comment by BerkeleyTrue** [comment]
@bugron has some good points. Although this PR is a response to a request for static pages, so no redirect is need as these will be used with Nginx and not an actual page in our server.

**Comment by BerkeleyTrue** [comment]
@mikestratton Thanks for the work but unfortunately this gives off the impression that the logo is on fire instead of it being a campfire effect which is what i think was intended. I like the idea of the getting campfire going but it needs to be subtle.

Happy Coding!

**Pull request closed without merging**
