### PR TITLE
fix: remove split function to blocklist alphabet

### PR DESCRIPTION
**Pull request by 0o001**
Checklist:

- [x] I have read and followed the [contribution guidelines](https://contribute.freecodecamp.org).
- [x] I have read and followed the [how to open a pull request guide](https://contribute.freecodecamp.org/#/how-to-open-a-pull-request).
- [x] My pull request targets the `main` branch of freeCodeCamp.
- [x] I have tested these changes either locally on my machine, or GitPod.

Description: 
The code will produce the same results even without using the split function and the concat function.

### CODE REVIEW

**Comment by 0o001** [comment]
I hope I can do it now.

**Comment by naomi-lgbt** [comment]
Hello,

Firstly, thank you for submitting this pull request!

As you navigate through the process, we have a PR checklist to ensure consistency and quality in our contributions. We kindly ask that you genuinely follow through with each point. This not only facilitates the review process but also demonstrates a mutual respect for the community's efforts.

If you're unfamiliar with certain aspects, our [contributing guidelines](https://contribute.freecodecamp.org) are a helpful resource to get you up to speed.

<details>
<summary>**Friendly Pointers (click to expand)**</summary>

1. **Editing on GitHub:** While it's possible to edit files directly on GitHub, it's typically better not to. This helps avoid inadvertent mistakes like typos that can disrupt tests.

2. **Linking Issues:** Please ensure you link issues using the designated method. Simply update the `XXXXXX` in the PR description to include the issue number. This keeps our records organized and clear.

3. **Engaging with the Team:** We know you're eager, but kindly keep mentions and review requests limited. Our maintainers are always on the lookout and will attend to PRs in the order they come in.

4. **Branch Management:** It's a good practice not to work directly off your `main` branch. Creating separate branches for different changes allows you to smoothly update your PR even as the main repository progresses.

</details>

Please note, there's no need to close this PR. If you have questions or need guidance refining your contribution, don't hesitate to ask. Our community is here to assist.

Thank you for your enthusiasm in contributing to our project. We eagerly await more contributions from you!

**Happy Contributing!** 🌟

**Comment by 0o001** [comment]
@naomi-lgbt Thank you. I think I've done all that I've been told. Can you tell me if I'm wrong. I'll fix it too :)

**Comment by raisedadead** [comment]
This is just constructive feedback (not something you did wrong, we all start somewhere!):

The main thing is your fork is now soiled because of the changes from the `main` branch. So you will need help if you intend to make contributions next time.

The other thing is you did not test the changes in a local setup or GitPod and have edited off of GitHub again - that's not a geat idea because it can break things inadvertently.

Anyways, someone will review this in due course. Thanks for your patience. I recommend giving the guide and the links in the PR checklist a read. Trust me; they are worth your time.

Thanks for the PR, happy contributing!

**Review by naomi-lgbt — APPROVED** [review]
Poked around with the logic, looks like the result is the same.

**Pull request merged**
