### PR TITLE
Updated contributing.md

### PR DESCRIPTION
**Pull request by psanjay-1**
changed to Do not add the issue number in the PR title or commit message..

#### Pre-Submission Checklist

- [x] Your pull request targets the `staging` branch of FreeCodeCamp.
- [ ] Branch starts with either `fix/`, `feature/`, or `translate/` (e.g. `fix/signin-issue`)
- [x] You have only one commit (if not, [squash](http://forum.freecodecamp.com/t/how-to-squash-multiple-commits-into-one-with-git/13231) them into one commit).
- [ ] All new and existing tests pass the command `npm test`. Use `git commit --amend` to amend any fixes.

#### Type of Change

- [ ] Small bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds new functionality)
- [ ] Breaking change (fix or feature that would change existing functionality)
- [ ] Add new translation (feature adding new translations)

#### Checklist:

- [ ] Tested changes locally.
- [ ] Closes currently open issue (replace XXXX with an issue no): Closes #XXXX

### CODE REVIEW

**Comment by SanjayPatel16** [comment]
@camperbot I'm sorry i didn't understand. Can you explain in detail?

**Comment by raisedadead** [comment]
@SanjayPatel16 If you check at the top of this thread, you will notice that the PR is from a branch named `patch-1` on your fork.

We have guidelines to have it from something like 'fix/some-meaningful-name` 

And apologies, @camperbot can't revert, it's a silly bot (not a person).

**Comment by raisedadead** [comment]
@SanjayPatel16  You should go through the [Guidelines for Contributing](https://github.com/FreeCodeCamp/FreeCodeCamp/blob/staging/CONTRIBUTING.md).

**Comment by raisedadead** [comment]
On that note, I am going to close this in favor of #12152 because it's already under QA. I do understand that your PR came first, and should have been considered, but the changes in the other are looking more relevant.

Please do not be discouraged, we have tons of help wanted issues. And we would love to see your contribution. Thanks a lot for your time and effort!

Happy Fixing!
/cc @dhcodes

**Comment by dhcodes** [comment]
Yeah, sorry I didn't see this one. The form that says "closes current issue #XXXX" connects the PR to the thread so I saw the other one first. My apologies; we look forward to your future contribution @SanjayPatel16

**Pull request closed without merging**
