### PR TITLE
fix(curriculum): added "Helpful Tips" section to sha-1-password-cracker challenge

### PR DESCRIPTION
**Pull request by ninaargade**
Description of changes: Added background information about hashing, sha-1, and salting concepts to "Helpful Tips" section of information security, sha-1-password-cracker challenge. I thought these explanations would help a new learner better understand the relevance and purpose of topics covered in this challenge.

Checklist:

- [x] I have read and followed the [contribution guidelines](https://contribute.freecodecamp.org).
- [x] I have read and followed the [how to open a pull request guide](https://contribute.freecodecamp.org/#/how-to-open-a-pull-request).
- [x] My pull request targets the `main` branch of freeCodeCamp.
- [x] I have tested these changes either locally on my machine, or GitPod.

Closes #XXXXX

### CODE REVIEW

**Review by ambush8055 — COMMENTED** [review]
curriculum/challenges/english/09-information-security/information-security-projects/sha-1-password-cracker.md

**Review by moT01 — COMMENTED** [review]
Thanks for your interest in contributing @ninaargade. I would recommend opening an issue about this so we can discuss if we want to add something like this to this challenge. I don't particularly think this info fits here. Some of the info needed for this project might be missing from the curriculum, but I don't like trying to fit it in a few paragraphs at the bottom like this. I would maybe rather see a link to a youtube video or news article like the other learning material on this page.

**Review by ahmad2shadab — COMMENTED** [review]
What is hashing?
Hashing refers to the process of transforming a key or text (or in this case, password) into another value. This transformation occurs by using a hash function, which is a standardized algorithm that converts the key into a bit string of a fixed size. This transformed value is refered to as a hash and is unique to the original key. The hash is then usually displayed as a 40 digit long hexadecimal number. Hashing is an important concept in information security because it allows for a password to be verified and compared to the stored hash at the time of log-in so that the original password never needs to be stored.

What is SHA-1?
SHA-1 stands for secure hash algorithm 1, which takes a password and produces a 160-bit (or 20 byte hash value). The SHA-1 algorithm was developed by the United States National Security Agency but has not been considered to be secure since 2005. There are other hash algorithms, such as SHA-2, SHA-3, MD2, MD4, and MD5.

What is the purpose of a salt?
If multiple users have the same password, they will also have the same hash. This makes the pool of hashes smaller and more susceptible to an outsider who can now more easily figure out a common password. In order to increase security, we can add a salt. A salt is randomized data (in this case, a string of characters) that is added to the beginning and end of a password at the time of hashing. The action of salting then creates an even more unqiue input than the basic password, which will then result in a more secure hash.

**Comment by ahmad2shadab** [comment]
What is hashing?
Hashing refers to the process of transforming a key or text (or in this case, password) into another value. This transformation occurs by using a hash function, which is a standardized algorithm that converts the key into a bit string of a fixed size. This transformed value is refered to as a hash and is unique to the original key. The hash is then usually displayed as a 40 digit long hexadecimal number. Hashing is an important concept in information security because it allows for a password to be verified and compared to the stored hash at the time of log-in so that the original password never needs to be stored.

What is SHA-1?
SHA-1 stands for secure hash algorithm 1, which takes a password and produces a 160-bit (or 20 byte hash value). The SHA-1 algorithm was developed by the United States National Security Agency but has not been considered to be secure since 2005. There are other hash algorithms, such as SHA-2, SHA-3, MD2, MD4, and MD5.

What is the purpose of a salt?
If multiple users have the same password, they will also have the same hash. This makes the pool of hashes smaller and more susceptible to an outsider who can now more easily figure out a common password. In order to increase security, we can add a salt. A salt is randomized data (in this case, a string of characters) that is added to the beginning and end of a password at the time of hashing. The action of salting then creates an even more unqiue input than the basic password, which will then result in a more secure hash.

**Review by ahmad2shadab — COMMENTED** [review]
✔

**Pull request closed without merging**
