### PR TITLE
Add Transition to become the landing page smooth

### PR DESCRIPTION
**Pull request by MOHAMED-EHAB-DEV**
Checklist:

- [x] I have read [freeCodeCamp's contribution guidelines](https://contribute.freecodecamp.org).
- [x] My pull request has a descriptive title (not a vague title like `Update index.md`)
- [x] My pull request targets the `main` branch of freeCodeCamp.
- [x] I have tested these changes either locally on my machine, or GitPod.

Closes #XXXXX

### CODE REVIEW

**Comment by ieahleen** [comment]
can you add more details on what you changed?
that diff is difficult to comprehend

a screenshot/video/gif of the before/after maybe?

**Comment by Programming-School-Pro-Coding** [comment]
> can you add more details on what you changed? that diff is difficult to comprehend
> 
> a screenshot/video/gif of the before/after maybe?
> 
> and why you made this change?

I add transition to the project to see animations in the site

**Comment by Programming-School-Pro-Coding** [comment]
> Hi @Programming-School-Pro-Coding as Ilenia said, could you give us a demo of the changes you made?
> 
> Also, please could you move the changes into another css file? Modifying bootstrap directly is likely to cause problems and will definitely cause other devs to be confused, because they will assume that it's simply bootstrap.

Ok

**Comment by ieahleen** [comment]
Thank you for opening this pull request.

This is a standard message notifying you that we've reviewed your pull request and have decided not to merge it. We would welcome future pull requests from you.

Thank you and happy coding.

**Pull request closed without merging**
