### PR TITLE
Add: forumTopicId for rosetta code

### LINKED ISSUE #38629: Add forum topic ID to rosetta challenges
I noticed that @NitronR has added a ton of content to mostly the rosetta code section (thanks BTW). You can see a [list of his PR's here](https://github.com/freeCodeCamp/freeCodeCamp/pulls?q=is%3Apr+author%3AnitronR+is%3Aclosed). I did forum search for a couple of the challenges and it looks like guide pages have been created, but I noticed that the `forumTopicId` wasn't added to many of the challenges. We should go through those PR's and add the `forumTopicId` field to the frontmatter and make sure a guide page is created. If the PR is getting large, it might be a good idea to break it up into several.

### PR DESCRIPTION
**Pull request by rajatgupta24**
Checklist:

- [x] I have read [freeCodeCamp's contribution guidelines](https://contribute.freecodecamp.org).
- [x] My pull request has a descriptive title (not a vague title like `Update index.md`)
- [x] My pull request targets the `master` branch of freeCodeCamp.
- [x] All the files I changed are in the same world language, for example: only English changes, or only Chinese changes, etc.

Closes #38629

### CODE REVIEW

**Comment by rajatgupta24** [comment]
Hi,
I made the required changes @moT01 can you please review it.
Thank you

**Review by moT01 — CHANGES_REQUESTED** [review]
- If you added all the same files onto this PR from your other PR, you can close the other PR.
- You should complete the checklist in the PR template, put an `x` in all the `[ ]` if they are true
- something was merged to create conflicts for all these so it can't be merged as-is,
  you should try and fix those conflicts.

**Comment by moT01** [comment]
I have blocked this for now. See the [pinned code freeze issue](https://github.com/freeCodeCamp/freeCodeCamp/issues/38308)

**Comment by raisedadead** [comment]
Limitations removed on Coding Interview Prep Challenges.

**Comment by raisedadead** [comment]
@rajatgupta24 please fill in the checklist in the first post as requested.

**Review by moT01 — CHANGES_REQUESTED** [review]
Looks like there's still one missing @rajatgupta24. https://www.freecodecamp.org/forum/t/freecodecamp-challenge-guide-self-describing-numbers/385289. The last one in [my comment](https://github.com/freeCodeCamp/freeCodeCamp/issues/38629#issuecomment-625418086). Other than that, LGTM

**Review by moT01 — APPROVED** [review]
Thanks @rajatgupta24, LGTM 🎉

**Pull request merged**
