### PR TITLE
chore: replaced `substr` with `substring`

### PR DESCRIPTION
**Pull request by k-rajat19**
Checklist:

- [ ] I have read [freeCodeCamp's contribution guidelines](https://contribute.freecodecamp.org).
- [x] My pull request has a descriptive title (not a vague title like `Update index.md`)
- [x] My pull request targets the `main` branch of freeCodeCamp.
- [x] I have tested these changes either locally on my machine, or GitPod.

`substr` method is deprecated, this method should not be recommended to use.
https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/String/substr

### CODE REVIEW

**Comment by moT01** [comment]
I'm not against this change, but I don't see an issue with leaving it how it is - both of these methods are [equally supported](https://caniuse.com/?search=substr)

Side note: it does look like they have a different syntax:
`substr(start, length)`
`substring(indexStart, indexEnd)`

I'm not sure if that will come into play here - it looks like all of these tests would be compatible, but we would want to make sure.

**Comment by moT01** [comment]
We will give it a look and see what the consensus is 👍

**Review by ShaunSHamilton — APPROVED** [review]
Thank you for changing the title.

I am happy with this change 👍

**Review by naomi-lgbt — APPROVED** [review]
I'm fine with this change.

To touch on @moT01's comments - it may still be supported, but given that it is deprecated that can change at any time.

**Comment by naomi-lgbt** [comment]
Thank you for your contribution to the page! 👍
We are happy to accept these changes and look forward to future contributions. 🎉

**Pull request merged**
