### PR TITLE
Fix incorrect spelling of BCrypt

### PR DESCRIPTION
**Pull request by gmal1**
- [x] I have read [freeCodeCamp's contribution guidelines](https://github.com/freeCodeCamp/freeCodeCamp/blob/master/CONTRIBUTING.md).
- [x] My pull request has a descriptive title (not a vague title like `Update index.md`)
- [x] My pull request targets the `master` branch of freeCodeCamp.
- [x] None of my changes are plagiarized from another source without proper attribution.
- [x] All the files I changed are in the same world language (for example: only English changes, or only Chinese changes, etc.)
- [x] My changes do not use shortened URLs or affiliate links.

Closes #XXXXX

### CODE REVIEW

**Review by thecodingaviator — APPROVED** [review]

**Review by Manish-Giri — COMMENTED** [review]
Since this is a small change, maybe it would be good to fix the typo in the other languages as well - [Russian](https://github.com/freeCodeCamp/freeCodeCamp/blob/12f65a6742d272cc26aba9155f9692a5abfccefb/curriculum/challenges/russian/06-information-security-and-quality-assurance/information-security-with-helmetjs/understand-bcrypt-hashes.russian.md#L25), [Portuguese](https://github.com/freeCodeCamp/freeCodeCamp/blob/2ca3a2093fb9359483442e0fadeda1ea0fefff86/curriculum/challenges/portuguese/06-information-security-and-quality-assurance/information-security-with-helmetjs/understand-bcrypt-hashes.portuguese.md#L21), and [Spanish](https://github.com/freeCodeCamp/freeCodeCamp/blob/7723a592b78e6030ea392005c5dd0099298f3f66/curriculum/challenges/spanish/06-information-security-and-quality-assurance/information-security-with-helmetjs/understand-bcrypt-hashes.spanish.md#L21), in this PR?

**Review by thecodingaviator — CHANGES_REQUESTED** [review]
Please make the changes to files of all languages

**Comment by gmal1** [comment]
@Manish-Giri hey! thanks for reviewing. I fixed the typo in the Portuguese and Spanish translations in PR [#37295](https://github.com/freeCodeCamp/freeCodeCamp/pull/37295) and in Russian in [#37246](https://github.com/freeCodeCamp/freeCodeCamp/pull/37246).

**Comment by RandellDawson** [comment]
@gmal1 You were asked to put all the changes in this PR and not new PRs.  Would you mind closing the others and add your changes to this PR instead?

Thank you.

**Comment by scissorsneedfoodtoo** [comment]
@gmal1, hope you don't mind, but I went in and made the corrections to the other languages. Thank you for your contribution, and looking forward to the next :1st_place_medal: :100:

**Pull request merged**
