### PR TITLE
Typo: Edited Math for finding parent node

### LINKED ISSUE #34635: Data Structures: Insert an Element into a Max Heap
**Describe your problem and how to reproduce it:**
The code works fine, but there is a small typo in this challenge. The math to find the parent elements in a max heap is actually:

Math.floor((i-1)/2)

or in the second example where null is the root:

Math.floor(i/2)

Without using Math.floor(), one of the children's parents will always be undefined.

**Add a Link to the page with the problem:**

https://learn.freecodecamp.org/coding-interview-prep/data-structures/insert-an-element-into-a-max-heap

**Tell us about your browser and operating system:**

* Browser Name: Chrome
* Browser Version: 70.0.3538.110
* Operating System: macOS: 10.14.1

**If possible, add a screenshot here (you can drag and drop, png, jpg, gif, etc. in this box):**
screen shot 2018-12-11 at 09 30 58

### PR DESCRIPTION
**Pull request by mikeshort10**
Math to find parent node now wrapped in Math.floor() - lines 13.4 and 18. Without Math.floor(), the math returns undefined for the left child of each parent.

- [x ] I have read [freeCodeCamp's contribution guidelines](https://github.com/freeCodeCamp/freeCodeCamp/blob/master/CONTRIBUTING.md).
- [x] My pull request has a descriptive title (not a vague title like `Update index.md`)
- [x] My pull request targets the `master` branch of freeCodeCamp.
- [x] None of my changes are plagiarized from another source without proper attribution.
- [x] All the files I changed are in the same world language (for example: only English changes, or only Chinese changes, etc.)
- [x] My changes do not use shortened URLs or affiliate links.

Closes #34635

### CODE REVIEW

**Comment by ezioda004** [comment]
While checking locally the challenge doesnt have any line breaks, I presume its because there is none in the original master file but live challenge have.

Can you guys check it out?
cc: @nikrb @scissorsneedfoodtoo

**Comment by nikrb** [comment]
@ezioda004 I can't find anything in the history that explains the loss of the break points in the text between live and current master. I'll work on an update to replace the breaks, just let me know if you want it pushing.

**Comment by nikrb** [comment]
@ezioda004 any reason the instructions aren't in the instructions section?

**Comment by nikrb** [comment]
ok, well I have an update ready that adds the line breaks and moved the instructions. I have a solution as well which I could add.
Probably best to wait for Valera's input.

**Comment by ValeraS** [comment]
Problem with line breaks presents in all challenges. IMO, it should be resolved on a parsing stage, not in the challenge itself.

Instruction should be moved to the `instructions` section manually.

/cc @Bouncey @raisedadead

**Comment by ValeraS** [comment]
@nikrb @ezioda004 Could you test #34747? It should resolve the issue with lines breaks.

**Comment by raisedadead** [comment]
> Instruction should be moved to the `instructions` section manually.

I agree.

**Comment by scissorsneedfoodtoo** [comment]
@mikeshort10, everything LGTM! Thank you for helping us improve this challenge, and congratulations on your first contribution to freeCodeCamp! Looking forward to your next contribution :+1: :+1:

**Pull request merged**
