### PR TITLE
feat: add RTL language layout

### LINKED ISSUE #48101: RTL layout for freeCodeCamp curriculum
### Is your feature request related to a problem? Please describe.

With 100% of the three Arabic front end libraries proofread in Crowdin, we need to change the pages Layout to account for this.

The layout that need to be changed are as follows:

<details><summary>The Header and Footer layout</summary>

image

</details> 

<details><summary>The home layout</summary>

image

</details> 

<details><summary>the timeline layout</summary>

image

</details> 

<details><summary>the setting layout</summary>

image

</details> 

<details><summary>The donate layout</summary>

image

</details> 

<details><summary>The new test project layout? I think this is similar to the new RWD layout</summary>

image

</details> 

<details><summary>The learn layout</summary>

image

</details> 

<details><summary>the certification introduction layout</summary>

image

</details> 

<details><summary>the new RWD layout</summary>

https://www.freecodecamp.org/learn/2022/responsive-web-design/learn-basic-css-by-building-a-cafe-menu/step-1

image

</details> 

<details><summary>The old JavaScript certification</summary>

image

</details> 

<details><summary>The front end library project certification</summary>

image

</details> 

### Describe the solution you'd like

Change the component and layout to account for RTL Language

### Describe alternatives you've considered

I thought this was possible :rofl:

```css
flex-direction: row-reverse;
direction: rtl;
```

### Additional context

Is there a way to change SubForm layout in the forum?

### Issues

- [x] #48174
- [x] #48347
- [ ] #48348

### PR DESCRIPTION
**Pull request by Sboonny**
Checklist:

- [x] I have read [freeCodeCamp's contribution guidelines](https://contribute.freecodecamp.org).
- [x] My pull request has a descriptive title (not a vague title like `Update index.md`)
- [x] My pull request targets the `main` branch of freeCodeCamp.
- [x] I have tested these changes either locally on my machine, or GitPod.

Closes #48101

### CODE REVIEW

**Review by ojeytonwilliams — DISMISSED** [review]

**Comment by Sboonny** [comment]
after the other PRs are pushed, I will open this for review

**Review by zairahira — APPROVED** [review]
Based on our discussion over the layout in the meeting, these changes look good to me 👍.

**Review by moT01 — COMMENTED** [review]
This looks really good @Sboonny 🎉 I looked over the site pretty good and found a number of, mostly minor, inconsistencies from the LTR layout or other potential issues. I'm going to list them all here - I used Firefox 107.0 for all this:

<details>
  <summary>Highlighted projects have extra padding</summary>
  LTR:
  Screen Shot 2022-12-15 at 5 07 19 PM
  RTL:
  Screen Shot 2022-12-15 at 5 07 39 PM

^ The grey box around the text has extra margin or padding in RTL. It shows up when you hover the project name. This is on the settings page, but it's likely the same on a number of other links/pages that use this hover effect.
</details>
<hr>
<details>
  <summary>English text has wrong font</summary>
  Screen Shot 2022-12-15 at 5 06 19 PM

^ The English text in the RTL layout has the wrong font. This is on the settings page, but it's probably on most pages.
</details>
<hr>
<details>
  <summary>Icon is backward?</summary>


^ This is on the landing page. That icon looks like it might be backwards?


^ Same with this icon in the menu?
</details>
<hr>
<details>
  <summary>Classic editor has extra margin</summary>


^ These are challenges that use the classic editor. Looks like some extra margin or padding in a few spots.
</details>
<hr>
<details>
  <summary>Extra margin + block icon doesn't rotate</summary>
  

^ This is on the map pages with the legacy style blocks. When you click the block to expand it, the icon on the right doesn't rotate. Also, there's some extra margin on the left there relative to LTR
</details>
<hr>
<details>
  <summary>Menu has missing padding</summary>


^ The RTL menu is missing some padding or margin it looks like
</details>
<hr>
<details>
  <summary>Missing padding on donate page</summary>
  
  
^ This is at the top of the donate page. LTR has a margin there.
</details>
<hr>
<details>
  <summary>Misaligned text on donate page</summary>
  

^ This is in the FAQ part on the donate page. The text looks left aligned still or something. Note: that icon does rotate.
</details>
<hr>
<details>
  <summary>Heatmap is cut off</summary>
  
</details>
<hr>
<details>
  <summary>Gatsby 404 page is RTL</summary>
  
  
^ That caught me off guard and I just thought it was kinda funny
</details>
<hr>
A couple other things I noticed.

- The jaws on the new multifile editor are still LTR. I'm sure you are aware, just mentioning it.
- The trending articles in the footer are still LTR.

You may be aware of some of these - many of them might be outside the scope of this PR and maybe some aren't a problem - not sure. I will leave it up to you if you want to do anything with any of it. Maybe we are fine to leave them for the initial release.

**Comment by Sboonny** [comment]
I think the issue in HeatMap is with the component itself. here is the component in the codebase

https://github.com/Sboonny/freeCodeCamp/blob/0c6dc4f909f96697cb413a890a48e4f9d87ec55b/client/src/components/profile/components/heat-map.tsx#L129-L164?plain=1

I will open an issue in it, because it doesn't look good in small screens too, and could use some updates.

---

I will try to resolve margins and padding in second PR, I will apply logical property (`marigin-inline`, and `padding-inline`) and as long there is nothing with `margin: auto` all shall be well, I hope.

---

> That caught me off guard and I just thought it was kinda funny

Ya, I giggled too, I will be honest, I didn't put effort into solving this because there is no class or id to use and change the page styling with it.

---

> The English text is in the wrong font.

Because it requires a lot of work, and applying the font to RTL encoded characters only, or ignore the English encoded characters, Ahmad and I decided this is too much effort for almost no benefit.

---

> The trending articles in the footer are still LTR.

Yeab, the titles for Arabic articles will always be in English, this reminds me, I should open PR in news and fix that section there as well. 📰 

---

> Highlighted projects have extra padding

Nice catch. Unfortunately, this is something in the font itself, as far as I know. I am researching how to edit fonts and plan to do it when I have a week free or so. The font we are using have an issue with spacing too, which I should fix as well. 🤔  👍

**Comment by Sboonny** [comment]
I have opened #48769 for spacing. if it missed something, I will open 3rd PR for that.

**Review by moT01 — APPROVED** [review]
Well, LGTM if you're ready to go with this then @Sboonny 🎉

**Comment by Sboonny** [comment]
🥳 🥳 🥳 🥳 🥳 🥳 😭 😭 😭 😭 😭

**Pull request merged**
