### PR TITLE
FIX Comparison with the Equality Operator

### LINKED ISSUE #8895: "10 == val" should be evaluated regardless of the order of values
Challenge [Comparison with the Equality Operator](https://www.freecodecamp.com/challenges/comparison-with-the-equality-operator#?solution=%0A%2F%2F%20Setup%0Afunction%20testEqual(val)%20%7B%0A%20%20if%20(10%20%3D%3D%20val)%20%7B%20%2F%2F%20Change%20this%20line%0A%20%20%20%20return%20%22Equal%22%3B%0A%20%20%7D%0A%20%20return%20%22Not%20Equal%22%3B%0A%7D%0A%0A%2F%2F%20Change%20this%20value%20to%20test%0AtestEqual(10)%3B%0A) has an issue.
User Agent is: <code>Mozilla/5.0 (Windows NT 6.1; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/50.0.2661.102 Safari/537.36</code>.
Please describe how to reproduce this issue, and include links to screenshots if possible.

My code:
```javascript

// Setup
function testEqual(val) {
  if (12 == val) { // Change this line
    return "Equal";
  }
  return "Not Equal";
}

// Change this value to test
testEqual(12);

```

### PR DESCRIPTION
**Pull request by Bouncey**
#### Pre-Submission Checklist

- [x] Your pull request targets the `staging` branch of FreeCodeCamp.
- [x] Branch starts with either `fix/`, `feature/`, or `translate/` (e.g. `fix/signin-issue`)
- [x] You have only one commit (if not, [squash](https://github.com/FreeCodeCamp/FreeCodeCamp/wiki/git-rebase#squashing-multiple-commits-into-one) them into one commit).
- [x] All new and existing tests pass the command `npm run test-challenges`. Use `git commit --amend` to amend any fixes.
#### Type of Change

- [x] Small bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds new functionality)
- [ ] Breaking change (fix or feature that would change existing functionality)
- [ ] Add new translation (feature adding new translations)
#### Checklist:

- [x] Tested changes locally.
- [x] Closes currently open issue (replace XXXX with an issue no): Closes #8895 
#### Description

New regEx to test for `==`, will not match `===`.

### CODE REVIEW

**Comment by Bouncey** [comment]
@camperbot You're welcome! 

But do you have to be so picky with PR titles? :smile:

**Comment by erictleung** [comment]
@Bouncey yes, we like to have correctly named *branches* for consistency.

Your new regex fails if I put quotes over my numbers and no space between the quote and the `==`.

```js
if ('12'== val) {
    return "Equal";
}
```

Maybe change the regex to just look for `==` within the parentheses.

**Comment by Bouncey** [comment]
Please QA, updated assert test case for test 4.

**Comment by erictleung** [comment]
@Bouncey LGTM! 👍  Thanks for your contribution to FreeCodeCamp! ✨ 🎉 ✨

**Pull request merged**
