### PR TITLE
Animate #testSuite to focus user on errors

### LINKED ISSUE #9148: Animate #testSuite to focus user on errors
#### Challenge Name
This applies to any challenge that has the button [Run tests]

#### Issue Description
For a new user clicking multiple times in the [Run tests] button looks like nothing is happening.
We should animate the div that contains the errors ( #testSuite ) to let the user know that something is wrong

#### Browser Information

* Browser Name, Version: Google Chrome V51
* Operating System: Win 10
* Mobile, Desktop, or Tablet: Desktop

### PR DESCRIPTION
**Pull request by heldersepu**
#### Pre-Submission Checklist

- [x] Your pull request targets the `staging` branch of FreeCodeCamp.
- [x] Branch starts with either `fix/`, `feature/`, or `translate/` (e.g. `fix/signin-issue`)
- [x] You have only one commit (if not, [squash](https://github.com/FreeCodeCamp/FreeCodeCamp/wiki/git-rebase#squashing-multiple-commits-into-one) them into one commit).
- [x] All new and existing tests pass the command `npm run test-challenges`. Use `git commit --amend` to amend any fixes.
#### Type of Change

- [ ] Small bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds new functionality)
- [ ] Breaking change (fix or feature that would change existing functionality)
- [ ] Add new translation (feature adding new translations)
#### Checklist:

- [x] Tested changes locally.
- [x] Closes currently open issue: Closes #9148
#### Description

Very very simple change, just a small JS hide/show trick to bring users attention to the testSuite.
- As soon as the user clicks the button we hide('slow') the div #testSuite
- Then on displayTestResults we show it.

### CODE REVIEW

**Comment by atjonathan** [comment]
@heldersepu, i like the concept, however, the animation is a little clunky. A simple fade might work better?

**Comment by heldersepu** [comment]
Sure, we can replace the show with a fadein

**Comment by atjonathan** [comment]
@heldersepu, lets see what that looks like :smiley:

**Comment by Bouncey** [comment]
As nice as it is, I don't think the animation solves the issue. If I'm only scrolled enough to veiw the test button, I won't see the test suite, no matter what it is doing. 

Is it possible to add a conditional animation like:
```
.notice-me{
     top: -400px;
}

if (testSuite !== inVeiw){

testSuit.addClass('notice-me', setTimeout(2000){
    testSuite.removeClass('notice-me');
    };
}
```

**Comment by heldersepu** [comment]
@Bouncey I see your point, but I think that will be a separate issue...
Your case applies to only some challenges where the contents of div #scroll-locker is longer than the page view. 
Maybe on displayTestResults we should scroll to the bottom of #scroll-locker

**Comment by Bouncey** [comment]
@heldersepu That would work also :+1:

**Comment by heldersepu** [comment]
Here is some info how I noticed the issue and what I'm trying to fix:
I was showing FCC to a friend (telling him all about how easy is to learn with this awesome tool) he was on my Laptop doing one of the challenges:
https://www.freecodecamp.com/challenges/create-a-bootstrap-button

He had some bugs on his code that we didn't noticed and he kept clicking on "Run test" and since nothing changes on the UI he thought that the site was broken, at the time I thought that we might have lost the WiFi connection, but after some troubleshooting we discovered that clicking the "Run test" does what is supposed to, but nothing changes on the page.

**Comment by Bouncey** [comment]
@heldersepu In your terminal use `npm test` to see where the commit failed.

**Comment by heldersepu** [comment]
I see the issue:
https://travis-ci.org/FreeCodeCamp/FreeCodeCamp/builds/138561779
error  Strings must use singlequote  quotes

**Comment by Bouncey** [comment]
LGTM

Please [squash](https://freecodecamp.github.io/wiki/en/git-squash/) your commits into one so we can merge :+1:

**Comment by atjonathan** [comment]
#### **LGTM :+1:**
Thanks for contributing :tada:

**Comment by heldersepu** [comment]
@atjonathan my pleasure!
This was an easy one, if you guys have time take a look at Issue 7847:
https://github.com/FreeCodeCamp/FreeCodeCamp/issues/7847

**Comment by heldersepu** [comment]
@Bouncey I see that this change is already live, that was a quick turnaround!
The scroll to the bottom of #scroll-locker has some side effects on challenges with large contents.
https://www.freecodecamp.com/challenges/comparisons-with-the-logical-or-operator

**Comment by atjonathan** [comment]
@heldersepu, in my opinion it looks fine! What do you think @Bouncey?

**Comment by Bouncey** [comment]
Commenting on #9256

**Pull request merged**
