### PR TITLE
[Guide] Basic JS: Random numbers within range. Enhancements

### PR DESCRIPTION
**Pull request by AdrianSkar**
Added code solution, explanation, resources and other minor fixes.

- [x] I have read [freeCodeCamp's contribution guidelines](https://github.com/freeCodeCamp/freeCodeCamp/blob/master/CONTRIBUTING.md).
- [x] My pull request has a descriptive title (not a vague title like `Update index.md`)
- [x] My pull request targets the `master` branch of freeCodeCamp.
- [x] None of my changes are plagiarized from another source without proper attribution.
- [x] My article does not contain shortened URLs or affiliate links.

### CODE REVIEW

**Review by RandellDawson — CHANGES_REQUESTED** [review]
Looks good so far, but under the Code explanation, remove the bullets for the first items and then make the a, b, c, d, e,  an ordered list.  Currently, those 5 lines are all on the same line.

**Comment by AdrianSkar** [comment]
Sure @RandellDawson. Thank you for pointing that out. 
It showed up on different lines at stackedit.io so I assumed it would work.

**Review by RandellDawson — APPROVED** [review]

**Comment by RandellDawson** [comment]
Thank you for your contribution to the page! 👍
We're happy to accept these changes, and look forward to future contributions. 🎉

**Comment by AdrianSkar** [comment]
@RandellDawson Thank you. I just transformed it in an unordered list including the _a) b) c)_ format because I used the letters to explain the concept (eg: the third one says `a * b = 8.244326990411024`)

**Pull request merged**
