### PR TITLE
fix(curriculum): typos in create RPG game in new JavaScript

### LINKED ISSUE #47660: Typo in Step 121 of Create RPG game project
### Describe the Issue

There is a typo in Step 121, the word `to` is missing in the sentence.

Here is the typo

https://github.com/freeCodeCamp/freeCodeCamp/blob/f80e34a9509f3208c01524ea25dd573fcacbe760/curriculum/challenges/english/15-javascript-algorithms-and-data-structures-22/learn-basic-javascript-by-building-a-role-playing-game/62a8e49f4df7af5ae2d7a616.md#L14

it should be 

> You should use compound assignment to modify the `monsterHealth` variable.

### Additional context

If you would like to fix this issue, please make sure you read [our guidelines for contributing](https://contribute.freecodecamp.org/#/), we prioritize contributors following the instructions in our guides. Join us in [our chat room](https://discord.gg/PRyKn3Vbay) or [the forum](https://forum.freecodecamp.org/c/contributors/3) if you need help contributing, our moderators will guide you through this.

Sometimes we may get more than one pull requests. We typically accept the most quality contribution, followed by the one that is made first.

Happy contributing.

### PR DESCRIPTION
**Pull request by utkershrajvenshi**
Checklist:

- [x] I have read [freeCodeCamp's contribution guidelines](https://contribute.freecodecamp.org).
- [x] My pull request has a descriptive title (not a vague title like `Update index.md`)
- [x] My pull request targets the `main` branch of freeCodeCamp.
- [x] I have tested these changes either locally on my machine, or GitPod.

Closes #47660

### CODE REVIEW

**Comment by ieahleen** [comment]
please follow the contributing documentation on how to open a PR to give a title to this PR
https://contribute.freecodecamp.org/#/how-to-open-a-pull-request?id=prepare-a-good-pr-title

**Review by Sboonny — APPROVED** [review]
#### :sparkles: :tada: **AWESOME!** :tada: :sparkles:

 Hi @utkershrajvenshi, thanks for this pull request and for contributing to the code-base for the first time. We are looking forward to more contributions from you in the future.

 Cheers & happy contributing!

**Comment by utkershrajvenshi** [comment]
Thanks @Sboonny @ieahleen . Will keep these tips in mind for upcoming PRs..

**Review by naomi-lgbt — APPROVED** [review]
banger pr, thanks for contributing!

**Pull request merged**
