### PR TITLE
chore(i18n,learn): processed translations

### PR DESCRIPTION
**Pull request by camperbot**
This PR was opened auto-magically by Crowdin.

### CODE REVIEW

**Review by RandellDawson — APPROVED** [review]
LGTM

**Comment by raisedadead** [comment]
Nice, this one will not merge until one more approval is complete from @nhcarrigan

**Review by raisedadead — APPROVED** [review]
Approving.

**Comment by raisedadead** [comment]
Nah - it doesn't actually wait for the requested person if another person with write access comes along.

**Pull request merged**
