### PR TITLE
Changed the solution to Escaping Literal Quotes in Strings answer to …

### LINKED ISSUE #8183: Typo in Instructions Section missing quotes
Challenge [Escaping Literal Quotes in Strings](https://www.freecodecamp.com/challenges/escaping-literal-quotes-in-strings#?solution=var%20myStr%3B%20%2F%2F%20Change%20this%20line%0A%0AmyStr%3D%22I%20am%20a%20%5C%22double%20quoted%5C%22%20string%20inside%20%5C%22double%20quotes%5C%22%20%22%3B%0A) has an issue.
User Agent is: <code>Mozilla/5.0 (Macintosh; Intel Mac OS X 10_11_4) AppleWebKit/601.5.17 (KHTML, like Gecko) Version/9.1 Safari/601.5.17</code>.
Please describe how to reproduce this issue, and include links to screenshots if possible.

My code:
```javascript
var myStr; // Change this line

myStr="I am a \"double quoted\" string inside \"double quotes\" ";

```
The instructions say the following: 

if you were to print it to the console, you would see:

I am a "double quoted" string inside "double quotes" 

The instructions ask for a phrase that only has quotes around the words "double quoted" and "double quotes," but if you write code that accomplishes this, the answer is marked wrong and the second requirement  appearing in the bottom left corner with a red circled x icon says the entire phrase should be in quotes as follows:

Variable myStr should equal to ("I am a "double quoted" string inside "double quotes"").

screen shot 2016-04-18 at 5 27 18 pm

Note how in screenshot the console output for myStr is identical to what instructions ask for, yet the answer is still marked incorrect.

### PR DESCRIPTION
**Pull request by evannudd**
#### Pre-Submission Checklist

- [x] Your pull request targets the `staging` branch of FreeCodeCamp.
- [x] Branch starts with either `fix/`, `feature/`, or `translate/` (e.g. `fix/signin-issue`)
- [x] You have only one commit (if not, [squash](https://github.com/FreeCodeCamp/FreeCodeCamp/wiki/git-rebase#squashing-multiple-commits-into-one) them into one commit).
- [x] All new and existing tests pass the command `npm run test-challenges`. Use `git commit --amend` to amend any fixes.
#### Type of Change

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] Add new translation (feature adding new translations)
#### Checklist:

- [x] Tested changes locally.
- [x] Closes currently open issue (`Closes #XXXX`): Closes #8183
#### Description

Changed the solution variable to be no longer require that quotes surround the entire thing

### CODE REVIEW

**Comment by raisedadead** [comment]
@evannudd 

The CI fails on this PR. You need to check the tests.

> - [x] All new and existing tests pass the command `npm run test-challenges`. Use `git commit --amend` to amend any fixes.

Did you run this command locally and check if the tests failed or passed?

**Comment by evannudd** [comment]
Sorry! I did a thing wrong with npm and git ( student still learning ) I'll have it fixed with checks and all after my class today.

**Comment by evannudd** [comment]
So I went back into this and made the correct change. Checked it running gulp and it displayed correctly. 
When I run it locally it works fine, but it always crashes the npm test. I get a bunch of yellow \u0000's followed by an error message npm ERR! Darwin 15.0.0


Specifically this is the error, something with the .DS_Store
 error { [SyntaxError: 
/Users/user/Desktop/FreeCodeCamp/FreeCodeCamp/seed/challenges/.DS_Store: Unexpected character '' (1:0)]
      pos: 0,



npm ERR! argv "/Users/user/.nvm/versions/node/v4.2.2/bin/node" "/Users/user/.nvm/versions/node/v4.2.2/bin/npm" "run" "test-challenges"
npm ERR! node v4.2.2
npm ERR! npm  v2.14.7
npm ERR! code ELIFECYCLE
npm ERR! freecodecamp@0.1.0 test-challenges: `babel-node seed/test-challenges.js | tap-spec`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the freecodecamp@0.1.0 test-challenges script 'babel-node seed/test-challenges.js | tap-spec'.
npm ERR! This is most likely a problem with the freecodecamp package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     babel-node seed/test-challenges.js | tap-spec
npm ERR! You can get their info via:
npm ERR!     npm owner ls freecodecamp
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /Users/user/Desktop/FreeCodeCamp/FreeCodeCamp/npm-debug.log
npm ERR! Test failed.  See above for more details.



I'm probably doing something silly but does anyone have any idea's to what's causing all this mess?

**Comment by erictleung** [comment]
@evannudd looks like gulp is getting mad over your `.DS_Store` file, which is located in `/Users/user/Desktop/FreeCodeCamp/FreeCodeCamp/seed/challenges/.DS_Store`. I think if you delete it, that'll fix the error it is showing. I have a Mac as well and I don't believe deleting this file in that directory should do anything bad. You can read more about the [`.DS_Store` file here](https://en.wikipedia.org/wiki/.DS_Store) if you're interested.

**Comment by evannudd** [comment]
@erictleung I thought the same thing, it seems that when ever I delete it though it will re-appear on its own. So I deleted it with the terminal which does successfully remove it. Then it still crashes with (oddly) the same error.

**Comment by raisedadead** [comment]
Closing in favor of #8203

**Pull request closed without merging**
