### PR TITLE
Update babel to 6.0

### PR DESCRIPTION
**Pull request by arialaurel**
Finally figured it out! :+1:

### CODE REVIEW

**Comment by BerkeleyTrue** [comment]
depends on #5871 before it can merged in

**Comment by BerkeleyTrue** [comment]
Sorry @ltegman, I want to get Hikes out before I try test this out.

**Comment by BerkeleyTrue** [comment]
I'm QA's this now

**Comment by BerkeleyTrue** [comment]
Exports not working for React app

**Comment by ltegman** [comment]
Looks like the import for `app$` in a-react.js is coming up `undefined`. May be a bug in the plugin to restore default function exports to babel 6. Looking into it.

**Comment by ltegman** [comment]
Apparently the old version of babel was letting us get away with misusing the `export { x as y } from 'x'` syntax! React app is running well for me now :+1:

**Comment by BerkeleyTrue** [comment]
@ltegman Can you explain that? Seems like this https://github.com/leebyron/ecmascript-more-export-from should still work.

**Comment by ltegman** [comment]
@BerkeleyTrue `default` is not a named export, so you can't call it out to do `export { default as somethingElse } from 'index.js'`. That syntax allows you to pull properties off the exported object and name them something else, but `default` isn't a property of the object, it _is_ the object.

**Comment by ltegman** [comment]
babel has an `_interopRequire` function that it injects into files that could end up referencing a default export but because the `export { x as y }` syntax can't access default exports it no longer injects and uses this function to require in that module, causing it to resolve as `default` as `undefined`

**Comment by ltegman** [comment]
@BerkeleyTrue Updated to the alternate fix we discussed in chat.

**Comment by bugron** [comment]
@ltegman @BerkeleyTrue what's your progress on this PR?

**Comment by ltegman** [comment]
This is ready for QA.

**Comment by BerkeleyTrue** [comment]
Well, I found a bug in /jobs. But then I checked production and it's there as well... :(

Otherwise this looks good. Great work on figuring out all those bugs @ltegman!

**Pull request merged**
