### PR TITLE
Fix : Spelling errors

### PR DESCRIPTION
**Pull request by DipakKumarSingh**
"greyed" should be "grayed"
"revewing" should be "reviewing"

- [x] I have read [freeCodeCamp's contribution guidelines](https://github.com/freeCodeCamp/freeCodeCamp/blob/master/CONTRIBUTING.md).
- [x] My pull request has a descriptive title (not a vague title like `Update index.md`)
- [x] My pull request targets the `master` branch of freeCodeCamp.
- [x] None of my changes are plagiarized from another source without proper attribution.
- [x] My article does not contain shortened URLs or affiliate links.

If your pull request closes a GitHub issue, replace the XXXXX below with the issue number.

Closes #XXXXX

### CODE REVIEW

**Comment by DipakKumarSingh** [comment]
Fix : Spelling errors

**Comment by honmanyau** [comment]
@DipakKumarSingh "Grey" is not a spelling error—it is the preferred spelling in British English whereas "gray" is preferred in British English. I don't think that it should be changed either since it's quoted text. I'll leave that for another reviewer to decide.

Also, as I mentioned in #28529, please combine minor changes of the same type into a single PR instead of submitting multiple PRs for them as you have done. It makes things easier for maintainers and fairer to other contributors.

**Comment by honmanyau** [comment]
@DipakKumarSingh Many apologies for overlooking the fact that you could be new to all of this. You can create a single PR for multiple files by:

1. Navigating to your fork's home page
2. Select a branch that you have created using the drop down menu on (either by creating it yourself or created as a result of editing a file)
3. While under that branch, you can edit other files and commit those changes to the same branch
4. Once you are done editing, navigate back to your fork's home page
5. Make sure that you are still on the branch that you want to submit a PR with
6. Click on "Create Pull Request"

**Comment by DipakKumarSingh** [comment]
I am sorry, but I was not able to follow this. Currently it shows the
following :

[image: image.png]

**Comment by RandellDawson** [comment]
Thank you for opening this pull request.

This is a standard message notifying you that we’ve reviewed your pull request and have decided not to merge it. We would welcome future pull requests from you.

**Reason:** As the other reviewer mentioned, the change of `greyed` to `grayed` is not necessary and the other change has already been resolved in different PR.

If you have other questions relating to how to contribute, please visit our [Gitter channel](https://gitter.im/FreeCodeCamp/Contributors).

Thank you and happy coding.

**Pull request closed without merging**
