### PR TITLE
fix broken speech ballon emoji

### PR DESCRIPTION
**Pull request by kaiguang**
- [x] I have read [freeCodeCamp's contribution guidelines](https://github.com/freeCodeCamp/freeCodeCamp/blob/master/CONTRIBUTING.md).
- [x] My pull request has a descriptive title (not a vague title like `Update index.md`)
- [x] My pull request targets the `master` branch of freeCodeCamp.
- [x] None of my changes are plagiarized from another source without proper attribution.
- [x] My article does not contain shortened URLs or affiliate links.

### CODE REVIEW

**Comment by thecodingaviator** [comment]
@lkaiguang Please use three backticks '   `   ' for specifying a codeblock, right now the changes you made look like normal text

**Comment by lkaiguang** [comment]
@thecodingaviator I have made the changes and put the text into codeblock.

**Review by RandellDawson — CHANGES_REQUESTED** [review]
The warning sign is still not showing correctly. See if you can fix that.

**Review by RandellDawson — APPROVED** [review]

**Comment by RandellDawson** [comment]
Thanks for your PR.  How did you know you could use that warning sign link?  Did you see it referenced in another Guide article?

**Comment by lkaiguang** [comment]
Thank you @RandellDawson . The warning sign link is being used in multiple guides in folder:
freeCodeCamp/client/src/guide/english/certifications/javascript-algorithms-and-data-structures/intermediate-algorithm-scripting/

The link is working okay if you open it in browser, but it is not working in GitHub markdown file, which I find weird. Do you have an answer for this?
https://discourse-user-assets.s3.amazonaws.com/original/2X/2/2d6c412a50797771301e7ceabd554cef4edcd74d.gif

**Comment by RandellDawson** [comment]
@lkaiguang I do not have an answer, but I will try to get one, because I noticed the same issue.

**Comment by honmanyau** [comment]
@Kaiguang @RandellDawson I think this could be an issue specific to the .gif extension and GitHub/camo ([related reference](https://github.com/atmos/camo/issues/17)) based on the following observations:

* The link in question (https://discourse-user-assets.s3.amazonaws.com/original/2X/2/2d6c412a50797771301e7ceabd554cef4edcd74d.gif), when loaded as an image on GitHub, appears to lead to "Non-Image content-type returned" if you inspect the response of the related request.
* The image loads just fine with a markdown previewer the code editor that I use.
* Other image types seem to work just fine (for example, https://s3.amazonaws.com/freecodecamp/landing-icon-community.svg).

On a somewhat related, I'm not sure if adding an image file to any of the guide article directory is a good/bad idea. Before the guide repo was merged with this repo, `index.md` is the only acceptable filename and the previous contributor's guide does note that images should be hosted externally for that reason.

**Comment by honmanyau** [comment]
@Kaiguang I'm honestly not sure what is preferred in this case since (as far as I know) there isn't currently a standard for adding images now that the guide repository has been merged into the, and I think there are advantages to both allowing and disallowing files that are not `index.md` in the guide directory and subdirectories.

I think the best way is to open an Issue about this (maybe it isn't a problem at all!). Do expect a bit of a wait though—Hacktobefest has made things a bit crazy. 😓 I hope that helps!

**Pull request merged**
