### PR TITLE
chore(api): enable exam environment endpoints in prod

### PR DESCRIPTION
**Pull request by ShaunSHamilton**
Checklist:

- [x] I have read and followed the [contribution guidelines](https://contribute.freecodecamp.org).
- [x] I have read and followed the [how to open a pull request guide](https://contribute.freecodecamp.org/how-to-open-a-pull-request/).
- [x] My pull request targets the `main` branch of freeCodeCamp.
- [x] I have tested these changes either locally on my machine, or GitPod.

### CODE REVIEW

**Review by ojeytonwilliams — APPROVED** [review]
LGTM :+1:

**Comment by raisedadead** [comment]
This is blocked till Jan?

**Comment by ShaunSHamilton** [comment]
@raisedadead No. This needs to go in, in order to test the exam environment on `.dev`.

**Comment by raisedadead** [comment]
> @raisedadead No. This needs to go in, in order to test the exam environment on `.dev`.

I hate double negative checks:

```
if (process.env.FREECODECAMP_NODE_ENV !== 'development') {
  assert.notEqual(
    process.env.FCC_ENABLE_EXAM_ENVIRONMENT,
    'true',
    'Exam environment is not ready for production.'
  );
```

**Review by raisedadead — APPROVED** [review]

**Pull request merged**
