### PR TITLE
test(curriculum): use Mocha for tests

### PR DESCRIPTION
**Pull request by ValeraS**
- [x] I have read [freeCodeCamp's contribution guidelines](https://github.com/freeCodeCamp/freeCodeCamp/blob/master/CONTRIBUTING.md).
- [x] My pull request has a descriptive title (not a vague title like `Update index.md`)
- [x] My pull request targets the `master` branch of freeCodeCamp.
- [x] None of my changes are plagiarized from another source without proper attribution.
- [x] My article does not contain shortened URLs or affiliate links.

If your pull request closes a GitHub issue, replace the XXXXX below with the issue number.

Closes #XXXXX

### CODE REVIEW

**Comment by ValeraS** [comment]
@Bouncey  @raisedadead How about adding a check that the tests on a seed data should fail?

**Comment by raisedadead** [comment]
Hi @ValeraS I have adjusted the lockfile by running `npm run bootstrap` from the root of repo. This is typically done when you install new packages in a sub-package.

Although there could be a cleaner way for that.

**Comment by ValeraS** [comment]
When a camper starts a new challenge and presses run the tests, he should see that the tests fail. I suggest checking this behavior with a test script. This can help find errors like this #17856

**Review by raisedadead — APPROVED** [review]
#### :sparkles: :sparkles: **LGTM.** :sparkles: :sparkles: 

Thanks @ValeraS 

Happy Contributing!

**Comment by raisedadead** [comment]
> When a camper starts a new challenge and presses run the tests, he should see that the tests fail. I suggest checking this behavior with ...

Yes please. Could you make a fresh PR, I merged this one.

**Comment by Bouncey** [comment]
✨ :sparkles: :sparkles: :sparkles: :sparkles: :sparkles: :sparkles: :sparkles: :sparkles: :sparkles: :sparkles: :sparkles: :sparkles: :sparkles: :sparkles: :sparkles: :sparkles: :sparkles: :sparkles: :sparkles: :sparkles: :sparkles: :sparkles: :sparkles: :sparkles: :sparkles: :sparkles: :sparkles: :sparkles: :sparkles: :sparkles: :sparkles: :sparkles: :sparkles: :sparkles: :sparkles: :sparkles: :sparkles: :sparkles: :sparkles: :sparkles: :sparkles: :sparkles: :sparkles: :sparkles: :sparkles: :sparkles: :sparkles: :sparkles: :sparkles: :sparkles: :sparkles: :sparkles: :sparkles: :sparkles: :sparkles: :sparkles: :sparkles: :sparkles: :sparkles: :sparkles: :sparkles: :sparkles: :sparkles: :sparkles: :sparkles: :sparkles: :sparkles: :sparkles: :sparkles: 

You read my mind @ValeraS!!!! Thank you!

**Pull request merged**
