### PR TITLE
Removed unnecessary quotes in curriculum/challenges/portuguese files.

### PR DESCRIPTION
**Pull request by LifeVirus**
- [x] I have read [freeCodeCamp's contribution guidelines](https://github.com/freeCodeCamp/freeCodeCamp/blob/master/CONTRIBUTING.md).
- [x] My pull request has a descriptive title (not a vague title like `Update index.md`)
- [x] My pull request targets the `master` branch of freeCodeCamp.
- [x] None of my changes are plagiarized from another source without proper attribution.
- [x] All the files I changed are in the same world language (for example: only English changes, or only Chinese changes, etc.)
- [x] My changes do not use shortened URLs or affiliate links.

Closes #XXXXX

### CODE REVIEW

**Review by RandellDawson — APPROVED** [review]
LGTM

**Comment by RandellDawson** [comment]
Congrats @LifeVirus on your first pull request (PR)! 🎉

Thank you for your contribution to the page! 👍
We're happy to accept these changes, and look forward to future contributions. 📝

**Comment by captaintrips1969** [comment]
I have no idea what your doing or how to help, but I am so thankful someone has finally interested in this evil man. Thank you from my heart, Carey Gallagher (the REAL on)

Sent from Mail<https://go.microsoft.com/fwlink/?LinkId=550986> for Windows 10

________________________________

**Comment by captaintrips1969** [comment]
am I supposed to be doing something?

**Pull request merged**
