### PR TITLE
Reformatted some example programs for consistency

### PR DESCRIPTION
**Pull request by cindydhy**
- [x] I have read [freeCodeCamp's contribution guidelines](https://github.com/freeCodeCamp/freeCodeCamp/blob/master/CONTRIBUTING.md).
- [x] My pull request has a descriptive title (not a vague title like `Update index.md`)
- [x] My pull request targets the `master` branch of freeCodeCamp.
- [x] None of my changes are plagiarized from another source without proper attribution.
- [x] All the files I changed are in the same world language (for example: only English changes, or only Chinese changes, etc.)
- [x] My changes do not use shortened URLs or affiliate links.

Closes #XXXXX

### CODE REVIEW

**Review by theNaut1lus — COMMENTED** [review]
As these are not critical changes, you will have to follow the general process of creating an issue first describing the problem at hand. and then link this PR to it.

**Comment by RandellDawson** [comment]
@co16353sidak There is no reason to create an issue first for this PR.

**Comment by thecodingaviator** [comment]
@RandellDawson As far as I can see, this PR is using three spaces instead of the two that the style guide prescribes

**Comment by RandellDawson** [comment]
@thecodingaviator This is true.  The problem is since the user deleted their branch, we can not "fix" it ourselves at this point.  The original code did not have the two space requirement either, so the user did make an improvement over what was already there.  I say merge it as is and let another PR fix the two space indentation for the entire article.

**Comment by thecodingaviator** [comment]
@RandellDawson Alright, I'd need someone with a bit more experience in C to review it though

**Comment by co16353sidak** [comment]
@thecodingaviator i had reviewed the PR previously when i was going through all C guide related articles.

**Review by theNaut1lus — APPROVED** [review]
LGTM(except for formatting issues) @RandellDawson @thecodingaviator 🎉

**Comment by RandellDawson** [comment]
Congrats @cindydhy  on your first pull request (PR)! 🎉

Thank you for your contribution to the page! 👍
We're happy to accept these changes, and look forward to future contributions. 📝

**Pull request merged**
