### PR TITLE
Update gif showing how to start FreeCodeCamp

### PR DESCRIPTION
**Pull request by vibegui**
To reflect recent UI changes in GitHub (and star count!)
Fixes https://github.com/FreeCodeCamp/FreeCodeCamp/issues/5527

### CODE REVIEW

**Comment by bugron** [comment]
@firstdoit thanks for the PR. Closing it because you've open this PR against our `master` branch and your branch is named `patch-1`. Please, review our [**Guidelines for Contributing**](https://github.com/FreeCodeCamp/FreeCodeCamp/blob/staging/CONTRIBUTING.md) very carefully and then open a new PR, thanks. And, please, do not ignore pull request template when you open a PR or an issue.

**Comment by firstdoit** [comment]
Sorry, @bugron. Opened up a new one.

BTW, the PR template doesn't actually spells out neither the branching name *enforcement*, nor that the target branch must be `staging`. Maybe we should add it there! What do you think?

**Comment by bugron** [comment]
Actually, there is a mention about the branch name (`fix/...` or `feature/...`) but I think we need to mention about `staging` branch too.

**Comment by firstdoit** [comment]
I care to disagree :) The way it's phrased right now makes it sound like a *suggestion* rather than an enforcement. It would be better to say: "Branches MUST be named with descriptive names that start with either `fix/` or `feature/` prefixes. Good examples are: ..."

**Comment by AkiraLaine** [comment]
@firstdoit It clearly says:
>Name the branch something like fix/xxx or feature/xxx where xxx is a short description of the changes or feature you are attempting to add. 

and also says

>Submit a pull request from your branch to Free Code Camp's staging branch.

**Comment by firstdoit** [comment]
Hi, @AkiraLaine! Yes, the `CONTRIBUTING.md` indeed covers this. 

However, we were discussing the **pull request template**, which **does not**:

```
## FreeCodeCamp Pull Request template
Please, go through steps before you submit a PR.

1. Make sure that your PR is not a duplicate.
2. If not then:

  2.1. Make sure you've done your changes in a separate branch, like `fix/signin-issue` or `feature/issue-templates`.

  2.2. You have a descriptive commit message.

  2.3. You have only one commit (if not, [squash](https://github.com/FreeCodeCamp/FreeCodeCamp/wiki/git-rebase#squashing-multiple-commits-into-one) them into one commit).

  2.4. Make sure `npm test` doesn't throw any error. If it does, fix them first and amend your commit.

3. **After** these steps you're ready to open a pull request. ***Don't*** forget to remove this template first.

  3.1. Give a descriptive title to your PR.

  3.2. Provide a description of your changes.

  3.3. Put `closes #XXXX` in your comment to auto-close the issue that your PR fixes (if such).
```

I'll propose a PR to improve this template :)

**Comment by AkiraLaine** [comment]
@firstdoit Right. But if you are contributing, you should read the ```CONTRIBUTING.md```.

**Comment by firstdoit** [comment]
Yes, indeed. My bad! Please have a look at the PR with a proposal for improving the PR template :)

**Pull request closed without merging**
