### PR TITLE
Audit ES Translation of object-oriented-and-functional-programming.json

### LINKED ISSUE #6506: Translation to Spanish: Verify and update translation of object-oriented-and-functional-programming.json
- [x]  Declare JavaScript Objects as Variables
- [x]  Construct JavaScript Objects with Functions
- [x]  Make Instances of Objects with a Constructor Function
- [x]  Make Unique Objects by Passing Parameters to our Constructor
- [x]  Make Object Properties Private
- [x]  Iterate over Arrays with .map
- [x]  Condense arrays with .reduce
- [x]  Filter Arrays with .filter
- [x]  Sort Arrays with .sort
- [x]  Reverse Arrays with .reverse
- [x]  Concatenate Arrays with .concat
- [x]  Split Strings with .split
- [x]  Join Strings with .join

### PR DESCRIPTION
**Pull request by justinian336**
Closes #6506

### CODE REVIEW

**Comment by vtamara** [comment]
@bugron I don't have so much time to review all the pull request related to spanish. Besides the process we have suggested from the spanish team is to announce in the channel for the spanish translators to review when a translator finishes a translation. I already announced there about this PR. @justinian336 thank you for your work, please when you send a PR translating to spanish announce in the channel for spanish translators.

**Comment by justinian336** [comment]
@vtamara sorry that I forgot to announce it to the others! I'll do it next time.

**Comment by vtamara** [comment]
Reviewed. Thanks @justinian336, good job. @bugron thanks for your work. It is possible to merge.

**Comment by bugron** [comment]
@justinian336 @vtamara thanks, merged.

**Pull request merged**
