### PR TITLE
Add method, solution, and reference.

### PR DESCRIPTION
**Pull request by nicholaswin**
- [x] I have read [freeCodeCamp's contribution guidelines](https://github.com/freeCodeCamp/freeCodeCamp/blob/master/CONTRIBUTING.md).
- [x] My pull request has a descriptive title (not a vague title like `Update index.md`)
- [x] My pull request targets the `master` branch of freeCodeCamp.
- [x] None of my changes are plagiarized from another source without proper attribution.
- [x] My article does not contain shortened URLs or affiliate links.

If your pull request closes a GitHub issue, replace the XXXXX below with the issue number.

Closes #XXXXX

### CODE REVIEW

**Review by thecodingaviator — CHANGES_REQUESTED** [review]
remove stub text

**Comment by RandellDawson** [comment]
@thecodingaviator This PR has gone stale and the solution does not pass all of the tests.  I am going to close it.

**Review by RandellDawson — APPROVED** [review]
@thecodingaviator I removed the stub information and tested the solution. LGTM

**Review by thecodingaviator — APPROVED** [review]
LGTM

**Pull request merged**
