### PR TITLE
Update README.md

### PR DESCRIPTION
**Pull request by Varshit07**
Change from the singular noun `project` to plural noun `projects`.

#### Pre-Submission Checklist

- [ ] Your pull request targets the `staging` branch of freeCodeCamp.
- [ ] Branch starts with either `fix/`, `feature/`, or `translate/` (e.g. `fix/signin-issue`)
- [ ] You have only one commit (if not, [squash](http://forum.freecodecamp.org/t/how-to-squash-multiple-commits-into-one-with-git/13231) them into one commit).
- [ ] All new and existing tests pass the command `npm test`. Use `git commit --amend` to amend any fixes.

#### Type of Change

- [x] Small bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds new functionality)
- [ ] Breaking change (fix or feature that would change existing functionality)
- [ ] Add new translation (feature adding new translations)

#### Checklist:

- [ ] Tested changes locally.
- [ ] Addressed currently open issue (replace XXXXX with an issue no in next line)

Closes #XXXXX

### CODE REVIEW

**Review by amandeepmittal — APPROVED** [review]
LGTM! Great catch.

**Review by erictleung — APPROVED** [review]
LGTM! Thanks for checking our grammar! :mag:

**Review by raisedadead — APPROVED** [review]
Hi @Varshit07 

Welcome to contributing to freeCodeCamp.org. Thanks a lot for taking the time to make this change. 

Will you be interested carrying this over to the `next` branch as well?

Happy contributing.

**Comment by eduardoflorendo** [comment]
#36444

**Pull request merged**
