### PR TITLE
Fixed missing closing bracket and deleted variable declared twice in rosetta code greatest-sub-sequential-sum challenge.

### PR DESCRIPTION
**Pull request by nibble0101**
Checklist:

- [x] I have read [freeCodeCamp's contribution guidelines](https://contribute.freecodecamp.org).
- [x] My pull request has a descriptive title (not a vague title like `Update index.md`)
- [x] My pull request targets the `master` branch of freeCodeCamp.
- [x] All the files I changed are in the same world language, for example: only English changes, or only Chinese changes, etc.

Closes #XXXXX

 - In test description 6, a closing bracket was omitted. Changed `maximumSubsequence([ 7, 1, -5, -3, -8, 1 ]` to `maximumSubsequence([ 7, 1, -5, -3, -8, 1 ])`.
- In the solution to the challenge, variable `subsequence` was declared twice. Outside the loop `var subsequence = [];` and inside the loop `var subsequence = population.slice(i, j);`.

### CODE REVIEW

**Review by naomi-lgbt — APPROVED** [review]
LGTM! Congratulations on submitting your first PR! 🥳 
Our workflow requires one additional approval from a team member with write access before this can be merged. 

As an aside, it is generally good practise to work off of a branch in your fork, to avoid [soiling your master branch](https://contribute.freecodecamp.org/#/how-to-setup-freecodecamp-locally?id=making-changes-locally).

**Comment by nibble0101** [comment]
@nhcarrigan Thanks for the feedback. 
> As an aside, it is generally good practise to work off of a branch in your fork, to avoid soiling your master branch.

I will next time.

**Review by RandellDawson — APPROVED** [review]

**Comment by RandellDawson** [comment]
Congrats @nibble0101 on your first pull request (PR)! 🎉

Thank you for your contribution to the page! 👍
We're happy to accept these changes, and look forward to future contributions. 📝

**Comment by nibble0101** [comment]
@RandellDawson  Thank you.

**Pull request merged**
