### PR TITLE
feat(client): rename test.tsx files to kebab-case

### PR DESCRIPTION
**Pull request by kamatheuska**
Checklist:

- [x] I have read [freeCodeCamp's contribution guidelines](https://contribute.freecodecamp.org).
- [x] My pull request has a descriptive title (not a vague title like `Update index.md`)
- [x] My pull request targets the `main` branch of freeCodeCamp.
- [x] I have tested these changes either locally on my machine, or GitPod.

### CODE REVIEW

**Comment by kamatheuska** [comment]
Only found this test files that need renaming
treeClientKebab

Also,.there is many others with naming issues that would require more time to fix, you can see some of them here

Screenshot from 2021-11-23 19-05-45

**Review by moT01 — APPROVED** [review]
LGTM :tada:

The only thing I noticed is that the folders are still capitalized or camel case. We could probably change those. I don't think it needs to be done here, there's quite a few folders across the repo that would need changing.

**Review by ShaunSHamilton — APPROVED** [review]
This LGTM 👍

**Comment by ShaunSHamilton** [comment]
Thank you, for your contribution to the page! 👍
We are happy to accept these changes, and look forward to future contributions. 🎉

**Comment by kamatheuska** [comment]
Nice, first merged PR! :) Happy to help

**Pull request merged**
