### PR TITLE
Add the missing article for eigenvalues

### PR DESCRIPTION
**Pull request by AmilaIndika789**
Add a new article for incomplete topic eigenvalue. Article includes a basic definition about eigenvalues and eigenvectors, how eigenvalues, eigenvalues are found along with a numerical example, and further references.

- [x] I have read [freeCodeCamp's contribution guidelines](https://github.com/freeCodeCamp/freeCodeCamp/blob/master/CONTRIBUTING.md).
- [x] My pull request has a descriptive title (not a vague title like `Update index.md`)
- [x] My pull request targets the `master` branch of freeCodeCamp.
- [x] None of my changes are plagiarized from another source without proper attribution.
- [x] My article does not contain shortened URLs or affiliate links.

If your pull request closes a GitHub issue, replace the XXXXX below with the issue number.

Closes #XXXXX

### CODE REVIEW

**Comment by RandellDawson** [comment]
Closed and Reopened this PR to attempt to resolve a specific Travis build failure.

**Review by Bouncey — CHANGES_REQUESTED** [review]
Hi @AmilaIndika789 

That test output was not due to your pull request, so no need to worry about it.

Could you please find some `https` resources to share (images and links). Also, the article isn't very accessible, the majority of the content is in an image which is not very helpful for a screen reader. Read the article in markdown (without the images) to see what I mean. Alternative text of `alt text` is not very helpful.

**Comment by RandellDawson** [comment]
@Bouncey What should we do about this PR?

**Comment by AmilaIndika789** [comment]
Haven't had time to look again into fixing the PR. You can remove this PR
if you want, I will make another PR when I am able to fix this.

J.A. Amila Indika,
Undergraduate at Department of Computer Engineering (E/14),
University of Peradeniya,
Sri Lanka.

**Pull request closed without merging**
