### PR TITLE
Fix for night mode not persisting in pages other than challenges

### LINKED ISSUE #8650: Night mode is not persisting on any other page except the challenges.
We are storing the Night mode as theme, its not persisting on any page other than the challenges.

Steps to reproduce:

1. Clear browser cache.
2. Visit FreeCodeCamp.com, login
3. toggle night mode (g + t +n)
4. Visit profile, about, settings, email-update, etc.

You can however press (g+t+n) to activate night mode on these pages.

### PR DESCRIPTION
**Pull request by kirushna-kumar**
#### Pre-Submission Checklist

- [x] Your pull request targets the `staging` branch of FreeCodeCamp.
- [x] Branch starts with either `fix/`, `feature/`, or `translate/` (e.g. `fix/signin-issue`)
- [x] You have only one commit (if not, [squash](https://github.com/FreeCodeCamp/FreeCodeCamp/wiki/git-rebase#squashing-multiple-commits-into-one) them into one commit).
- [x] All new and existing tests pass the command `npm run test-challenges`. Use `git commit --amend` to amend any fixes.
#### Type of Change

- [x] Small bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds new functionality)
- [ ] Breaking change (fix or feature that would change existing functionality)
- [ ] Add new translation (feature adding new translations)
#### Checklist:

- [x] Tested changes locally.
- [x] Closes currently open issue (replace XXXX with an issue no): Closes #8650 
#### Description

Minor change in jade templates for displaying pages in night mode based on user preference.
Also fixes night mode for sidebar display (however styling is beyond the scope of this fix)

### CODE REVIEW

**Comment by atjonathan** [comment]
Couple of tweaks needed:

**There is a delay in rendering dark mode for the map.**


**Dark mode is still not displayed on the chat.**


**Dark mode need some css tweaks on wiki.**


Because these aren't technically part of your PR, I can make these changes myself and submit a pull request which is merged alongside this one.

**Comment by flipsyde606** [comment]
@atjonathan Thanks for the review comments.

1. **There is a delay in rendering dark mode for the map.**
Since a new call is made to /map-aside, default background(white) is displayed till it loads. It takes time for jade to render the page. Same delay is scene in default mode but since the default background is also white we don't see the difference. This happens only the first time we open the map. I am not sure how we can circumvent this, maybe we can load the map pre-emptively while the main page loads? Please advise.

2 **Dark mode is still not displayed on the chat.**
Sorry my bad, I was over a private network and firewall blocked chat. Will get it fixed and update the PR later.

3 **Dark mode need some css tweaks on wiki**
Since wiki page is under going a UX overhaul I didn't bother with the CSS (refer issue #8504)

**Comment by atjonathan** [comment]
@flipsyde606, great :smile:, thanks so much for contributing. Keep the comings coming :tada:

**Comment by atjonathan** [comment]
@flipsyde606, you appear to have pulled in some unwanted commits :disappointed:
Using `git rebase -i HEAD~n`, let `squash` be `drop` for the unwanted commits.

**Comment by flipsyde606** [comment]
@atjonathan My apologies. I am a newbie still figuring out git :sob: . Will fix it.

**Comment by atjonathan** [comment]
@flipsyde606, no problem it happens all the time :stuck_out_tongue_winking_eye:

**Comment by raisedadead** [comment]
@atjonathan Is this ready for QA yet?

**Comment by atjonathan** [comment]
@raisedadead, yeh I'll pull it down, and merge if all seems well :tada:

**Comment by atjonathan** [comment]
@flipsyde606, the chat still doesn't have dark mode enabled on it.

**Comment by flipsyde606** [comment]
@atjonathan, the styles applied within the iframe chat are from third-party(gitter sidebar). The same styling from gitter rooms are applied there and I don't think they expose any API to override styling. 
Is night mode for chat absolutely necessary? Any help would be appreciated.

**Comment by raisedadead** [comment]
@flipsyde606 you are correct, we cant' possibly edit the styles of Gitter chat, at least not in a way that is  not a hacky solution. Its best we leave it as it is.

Lets :shipit: this if that's the only pending issue.

**Comment by atjonathan** [comment]
@raisedadead @flipsyde606, cool. Shipping...

**Pull request merged**
