### PR TITLE
Update add-a-text-alternative-to-images-for-visually-impaired-accessi…

### PR DESCRIPTION
**Pull request by 5kytrix**
…bility.portuguese.md

- [ ] I have read [freeCodeCamp's contribution guidelines](https://github.com/freeCodeCamp/freeCodeCamp/blob/master/CONTRIBUTING.md).
- [ ] My pull request has a descriptive title (not a vague title like `Update index.md`)
- [ ] My pull request targets the `master` branch of freeCodeCamp.
- [ ] None of my changes are plagiarized from another source without proper attribution.
- [ ] All the files I changed are in the same world language (for example: only English changes, or only Chinese changes, etc.)
- [ ] My changes do not use shortened URLs or affiliate links.

Closes #XXXXX

### CODE REVIEW

**Comment by RandellDawson** [comment]
@TheSirion Can you validate that `Instructions` section is a good translation of the same section of the [English version of the same challenge](https://github.com/freeCodeCamp/freeCodeCamp/blob/master/curriculum/challenges/english/01-responsive-web-design/applied-accessibility/add-a-text-alternative-to-images-for-visually-impaired-accessibility.english.md#instructions)?

**Comment by TheSirion** [comment]
> @TheSirion Can you validate that `Instructions` section is a good translation of the same section of the [English version of the same challenge](https://github.com/freeCodeCamp/freeCodeCamp/blob/master/curriculum/challenges/english/01-responsive-web-design/applied-accessibility/add-a-text-alternative-to-images-for-visually-impaired-accessibility.english.md#instructions)?

Of course!

**Review by TheSirion — CHANGES_REQUESTED** [review]
Acredito que o texto ficaria melhor assim: "A foto de perfil que ele deseja usar _demonstra_ suas habilidades e _será_ apreciada por todos os visitantes do site. Adicione [...] para explicar que o Camper Cat está praticando _caratê_." 

Acredito que dessa forma o texto fica um pouco mais fluído e fácil de entender. Além disso, é preferível que usemos a grafia de acordo com a definição do VOLP: caratê.

**Comment by RandellDawson** [comment]
@5kytrix See @TheSirion's suggestions.  If you have any questions/concerns feel free to reply back.  If you agree with the suggestions, please use the `Commit suggestion` button so we can get this merged.

Thank you.

**Comment by 5kytrix** [comment]
@RandellDawson can you help me in finding the <code>Commit suggestion</code> button?

Thank you.

**Comment by RandellDawson** [comment]
@5kytrix Sorry for the confusion.  I thought @TheSirion had used the `Suggestion` feature, but he did not.  You will just need to create a new commit and push to the same branch `patch-2` instead.

**Comment by RandellDawson** [comment]
As there has been no response from your end for a while, we are closing this PR.

Feel free to request this PR to be reopened or create a new PR, if you still wish to make the changes you originally added plus any additional change requests asked of you.  Also, remember to update your fork, so you have the latest version of master in case it has changed significantly.

Happy Coding!

**Comment by TheSirion** [comment]
Sorry for disappearing. I really want to help, but I haven't been able to
organize my time in order to dedicate time to the project. Also, I've been
having some trouble with GitHub and its features so I'm constantly worried
I'm doing something wrong.
Therefore I'll be stepping back for a while, but I want to come back
eventually. Sorry and thank you for your patience.

Em qui., 28 de nov. de 2019 às 22:12, Randell Dawson <
notifications@github.com> escreveu:

**Pull request closed without merging**
