### PR TITLE
fix(challenges): Replace camper leaderboard project

### LINKED ISSUE #17450: Replace Camper Leaderboard project with functionally similar project based on forum
#### Describe your problem and - if possible - how to reproduce it

[Camper leaderboard](https://forum.freecodecamp.org/clicks/track?url=https%3A%2F%2Flearn.freecodecamp.org%2Fcoding-interview-prep%2Ftake-home-projects%2Fbuild-a-camper-leaderboard&post_id=433506&topic_id=196990) APIs are broken as provided below:

#### Add a Link to the page with the problem
[https://fcctop100.herokuapp.com/api/fccusers/top/recent](https://fcctop100.herokuapp.com/api/fccusers/top/recent)
[https://fcctop100.herokuapp.com/api/fccusers/top/alltime](https://fcctop100.herokuapp.com/api/fccusers/top/alltime)
#### Tell us about your browser and operating system

* Browser Name: Chrome
* Browser Version: 67
* Operating System:  Windows 7

### PR DESCRIPTION
**Pull request by scissorsneedfoodtoo**
- [x] I have read [freeCodeCamp's contribution guidelines](https://github.com/freeCodeCamp/freeCodeCamp/blob/master/CONTRIBUTING.md).
- [x] My pull request has a descriptive title (not a vague title like `Update index.md`)
- [x] My pull request targets the `master` branch of freeCodeCamp.
- [x] None of my changes are plagiarized from another source without proper attribution.
- [x] All the files I changed are in the same world language (for example: only English changes, or only Chinese changes, etc.)
- [x] My changes do not use shortened URLs or affiliate links.

Closes #17450

### CODE REVIEW

**Comment by RandellDawson** [comment]
@scissorsneedfoodtoo See the following screenshot for some strange formatting for at least one row.

image

**Comment by scissorsneedfoodtoo** [comment]
Sorry about that! Should be fixed now: 
image

And that's a good question. Let me ask around and see if there's an official one.

**Comment by RandellDawson** [comment]
@scissorsneedfoodtoo When browser width is reduced.

image

**Comment by raisedadead** [comment]
We do have an official account that we use and share pens from. @RandellDawson @scissorsneedfoodtoo when you guys have finalised the pen is good to go, I will fork it and share the link here for you to update.

**Comment by RandellDawson** [comment]
> We do have an official account that we use and share pens from.

What is https://codepen.io/freeCodeCamp/ then?

**Comment by scissorsneedfoodtoo** [comment]
@RandellDawson, worked on this a bit over the weekend. Could you take another look?

**Comment by ojeytonwilliams** [comment]
@scissorsneedfoodtoo This looks great!  I did notice one thing - the activity column is displaying the time since the last post, rather than since the last activity.  If you change 
```jsx
<CountField className="activity">{moment(topic.last_posted_at).fromNow(true)}</CountField>
```
to 
```jsx
<CountField className="activity">{moment(topic.bumped_at).fromNow(true)}</CountField>
```
that should sort it out.

**Comment by scissorsneedfoodtoo** [comment]
@ojeytonwilliams, great catch, thank you! I didn't notice that. I'll fix that now.

**Comment by thecodingaviator** [comment]
You'll have to make the changes to testable-projects-fcc as well

**Comment by Ashuanuj** [comment]
i

**Comment by scissorsneedfoodtoo** [comment]
Fixed another bug where clicking on the profile picture opened a dead link. Here's the latest version: https://codepen.io/scissorsneedfoodtoo/pen/BEjvom

**Review by RandellDawson — APPROVED** [review]
@scissorsneedfoodtoo Looks good to me.

**Comment by moT01** [comment]
Looks good to me - nice job @scissorsneedfoodtoo! Should we change this line: `You can get feedback on your project by sharing it with your friends on Facebook.` to point to the forum instead of facebook?

Looks like the pen is ready to be put on the fCC codepen account @raisedadead.

**Comment by scissorsneedfoodtoo** [comment]
@moT01, thanks! I can't take credit for this project, though. It's really a fork of @jgibson02's Pen that I added some styling to.

Pointing to the forum rather than Facebook is a great idea. I'll make that change now.

**Comment by raisedadead** [comment]
The new pen is available at https://codepen.io/freeCodeCamp/pen/JqdoMV

**Review by raisedadead — APPROVED** [review]
#### :sparkles: :sparkles: **LGTM.** :sparkles: :sparkles: 

Thanks @scissorsneedfoodtoo 

Happy Contributing!

**Pull request merged**
