### PR TITLE
fix: remove unnecessary stripe iframes

### LINKED ISSUE #37387: Stripe iframes stack up
**Describe the bug**
As you move between challenges Stripe iframes are added to the page, but are never removed.  I'm not sure how serious this is, but it seems like a bug.

**To Reproduce**
1. Go to https://www.freecodecamp.dev/learn/responsive-web-design/basic-html-and-html5/say-hello-to-html-elements
2. Open dev console, scroll to the bottom
3. There should be two Stripe iframes
4. Navigate to the next challenge (press escape, press n)
5. See that a new iframe has been added and the old ones remain

**Expected behavior**
Stripe iframes from previous pages should be removed

**Screenshots**

StripePileup

### PR DESCRIPTION
**Pull request by scissorsneedfoodtoo**
Remove stripe iframes that stack with each navigation after visiting /donate and loading Stripe. 

This method will still leave two iframes (`__privateStripeMetricsController0` and `__privateStripeController1`) as they may be necessary for Stripe to function normally. While it's possible to remove the previously mentioned iframes, Stripe seems to only load them once when first visiting /donate. Future visits to /donate only load iframes for each of the credit card inputs and not `__privateStripeMetricsControllerX` or `__privateStripeControllerX`.

- [x] I have read [freeCodeCamp's contribution guidelines](https://github.com/freeCodeCamp/freeCodeCamp/blob/master/CONTRIBUTING.md).
- [x] My pull request has a descriptive title (not a vague title like `Update index.md`)
- [x] My pull request targets the `master` branch of freeCodeCamp.
- [x] None of my changes are plagiarized from another source without proper attribution.
- [x] All the files I changed are in the same world language (for example: only English changes, or only Chinese changes, etc.)
- [x] My changes do not use shortened URLs or affiliate links.

Closes https://github.com/freeCodeCamp/freeCodeCamp/issues/37387

### CODE REVIEW

**Comment by ojeytonwilliams** [comment]
Hey @scissorsneedfoodtoo, my first thought is this should either be added early on (in `componentDidMount` of something that will definitely be mounted) and only once or should just be clean-up. If I'm reading this right it'll add an observer every time you leave `donate`.

**Comment by scissorsneedfoodtoo** [comment]
@ojeytonwilliams, yes, I believe you're right, this is probably adding a bunch unnecessary MutationObservers. Really solves one problem while causing another haha.

I'll look for a better place to put this earlier on, perhaps on the landing page or nav.

**Comment by ojeytonwilliams** [comment]
It was a little ironic that it replaced one memory leak with a slightly different memory leak!

Nav makes sense to me, probably the `Header` component.  We'd need to be sure it doesn't get mounted more than once in production.  It does in dev mode if you go to a profile, but I'm 99% sure that's just because of how Gatsby handles 404 pages.  I can't build the site to check, right now, but I think that's worth looking at.

**Comment by scissorsneedfoodtoo** [comment]
Exactly! Very short sighted of me -- thank you for pointing it out.

Good point about checking that it doesn't get mounted more than once in production. I've moved the code into `componentDidMount` in the `Header` component. I can build the site and check whether or not that's the case.

**Comment by ojeytonwilliams** [comment]
The memory leak seems to have been plugged, so that's great.  I did notice the following, though: this MutationObserver kills any new iframes and leaves the old ones intact.  Right now that's fine, since only `/donate` actually uses Stripe, but it could cause problems if we use it on any other routes.  The iframes contain referrer query parameters which depend on which route they were called from, so I assume they do *something*.

So, that's what my commit does (it seemed easier to show you the code than explain, so here it is!).  You're welcome to do whatever you like with that - if it's terrible, just bin in.

I'm not sure what `__privateStripeMetricsController0` does (Stripe's stats, maybe?), but I noticed it's never been updating.  If that turns out to be important, I think we'd need to re-run the script that's downloaded from Stripe or update the referrer, so hopefully it is not important.

**Comment by scissorsneedfoodtoo** [comment]
@ojeytonwilliams, thank you for going through the code and making it much more readable/flexible. Now it's much easier to see what's going on than the original that I copied over from the react-stripe-elements issue. Also, killing the old iframes rather than the new ones with the updated routes is a much better approach, especially if we decide to use Stripe on routes other than donate.

I believe you're right. I also couldn't tell what `__privateStripeMetricsController0` does exactly. The donate page seems to work fine without it, so we might be able to get away with leaving it as is, even if we do have Stripe on other routes in the future.

**Comment by raisedadead** [comment]
I am merging this and pushing a build to .dev, you can find test stripe cards https://stripe.com/docs/testing#cards here.

This is not to be pushed to production until we have confirmed that its all good on dev

**Review by raisedadead — APPROVED** [review]

**Comment by scissorsneedfoodtoo** [comment]
Tested this on .dev. Navigated to the donate page, got redirected to the signin page, then went to several lessons before going back to the donate page to use a test card.

Went through the process several times and was able to donate each time:

image

**Comment by raisedadead** [comment]
Perfect. Pushing to production

**Pull request merged**
