### PR TITLE
fix(learn): clear instructions for Appending Variables to Strings lesson

### LINKED ISSUE #39515: unclear instructions for basic JavaScript: Appending Variables to Strings lesson
**the instruction says: "Set someAdjective and append it to myStr using the += operator."  while it doesn't specify that you should set a string for someAdjective. I find it confusing and I think mentioning this can help newbie coders a lot**

**Link to the lesson: https://www.freecodecamp.org/learn/javascript-algorithms-and-data-structures/basic-javascript/appending-variables-to-strings**

**Tell us about your browser and operating system:**
* Browser Name: chrome 
* Browser Version: 
* Operating System: windows 10

**If possible, add a screenshot here (you can drag and drop, png, jpg, gif, etc. in this box):**

### PR DESCRIPTION
**Pull request by gaurav1620**
Checklist:

- [x] I have read [freeCodeCamp's contribution guidelines](https://contribute.freecodecamp.org).
- [x] My pull request has a descriptive title (not a vague title like `Update index.md`)
- [x] My pull request targets the `master` branch of freeCodeCamp.
- [x] All the files I changed are in the same world language, for example: only English changes, or only Chinese changes, etc.

Closes #39515

### CODE REVIEW

**Review by ShaunSHamilton — APPROVED** [review]
Thank you, for getting this out @gaurav1620 

FYI: It is best to create a branch seperate from your `master` to avoid spoiling it, when changes are made. You can read more about the workflow we recommend when contributing in the [contributors docs](https://contribute.freecodecamp.org/#/)

Otherwise, @RandellDawson I see you posted an alternative solution to fix the issue on the thread, are you still wanting more discussion on that? Or, would you approve of this as is?

**Comment by RandellDawson** [comment]
> Otherwise, @RandellDawson I see you posted an alternative solution to fix the issue on the thread, are you still wanting more discussion on that? Or, would you approve of this as is?

I suppose we could take it as is.  I just was curious what others thought about my suggestion.

**Review by moT01 — APPROVED** [review]
LGTM @gaurav1620 🎉 Congratulations on your first contribution to freeCodeCamp 🎉 We look forward to future contributions 😃

**Comment by moT01** [comment]
In my opinion - your suggestion was good @RandellDawson. This just seemed like a simpler way to fix the issue.

**Pull request merged**
