### PR TITLE
Fix link in use-proptypes-to-define-the-props-you-expect.english.md

### PR DESCRIPTION
**Pull request by ghost**
The page was not able to render properly the following link: [documentation](https://reactjs.org/docs/jsx-in-depth.html#specifying-the-react-element-type). This PR fixes that.

- [x] I have read [freeCodeCamp's contribution guidelines](https://github.com/freeCodeCamp/freeCodeCamp/blob/master/CONTRIBUTING.md).
- [x] My pull request has a descriptive title (not a vague title like `Update index.md`)
- [x] My pull request targets the `master` branch of freeCodeCamp.
- [x] None of my changes are plagiarized from another source without proper attribution.
- [x] All the files I changed are in the same world language (for example: only English changes, or only Chinese changes, etc.)
- [x] My changes do not use shortened URLs or affiliate links.

### CODE REVIEW

**Comment by RandellDawson** [comment]
@rruc Not seeing the problem with the existing site.  Can you please provide a screenshot showing the challenge as it appears on the production site?  Also, please tell us what browser and version you are using.

Thank you

**Comment by rruc** [comment]
@RandellDawson Hi, I'm using Firefox 68.0.2 (64 bit) on a Debian machine, this is how I see it on the production site:
Screenshot from 2019-11-01 21-55-29

**Comment by RandellDawson** [comment]
@rruc Still not seeing what you think is a problem.  I could be just missing something.  Can you highlight the issue?

**Comment by rruc** [comment]
Yes, I highlighted the problem in yellow. This is the production site:

Screenshot from 2019-11-01 21-55-29

This is how the markdown is rendered:

Screenshot from 2019-11-01 22-01-27


This is how the markdown is rendered after my fix:

Screenshot from 2019-11-01 22-04-15

**Comment by RandellDawson** [comment]
@rruc OK, now I understand.  While we are fixing things on this challenge, would you mind adding a blank line between the the last sentence and the Note line?  Currently, the Note is not in its own paragraph.

@ojeytonwilliams I was thinking this `code` bug was fixed a while back. Has something changed?

**Comment by rruc** [comment]
@RandellDawson done!

**Review by RandellDawson — APPROVED** [review]
Everything now looks good on this challenge.

**Comment by RandellDawson** [comment]
@ojeytonwilliams I did a quick check across all challenges which use the markdown link syntax and no other challenge had the `code` tags next to the links, so no other challenges should need to be fixed like this.

**Review by moT01 — APPROVED** [review]
LGTM @rruc 🎉 Thanks for finding this and contributing to freeCodeCamp 🎉 

In the future, it's best to create a separate branch off of master and give it a more descriptive name.

**Comment by ojeytonwilliams** [comment]
@RandellDawson glad to hear it.  I'll try to find the time to fix the inconsistent parsing.

**Pull request merged**
