### PR TITLE
doc fix: update ChineseTrandational to ChineseTraditional

### LINKED ISSUE #50185: Documentation: Languages.ChineseTrandational should be Languages.ChineseTraditional
### Describe the Issue

There are 70 occurrences of the reference ChineseTrandational throughout the documents and TypeScript files. I believe these to be a typographical error which should state ChineseTraditional. A good example of this behavior is on the page located at: [Contribution Docs](https://contribute.freecodecamp.org/#/how-to-work-on-localized-client-webapp?id=testing-the-client-app-in-a-world-language)

I have prepared a pull request for these changes to go with this issue if approved.

### Affected Page

https://contribute.freecodecamp.org/#/how-to-work-on-localized-client-webapp?id=testing-the-client-app-in-a-world-language

### Steps to Reproduce

Visit the page and observe the language contents.

### Recommended fix or suggestions

Correct all 70 occurrences of the typographical error.

### Screenshots

image

### PR DESCRIPTION
**Pull request by th3oth3rjak3**
Checklist:

- [x] I have read and followed the [contribution guidelines](https://contribute.freecodecamp.org).
- [x] I have read and followed the [how to open a pull request guide](https://contribute.freecodecamp.org/#/how-to-open-a-pull-request).
- [x] My pull request targets the `main` branch of freeCodeCamp.
- [x] I have tested these changes either locally on my machine, or GitPod.

Closes #50185

### CODE REVIEW

**Comment by th3oth3rjak3** [comment]
I just wanted to follow-up that I didn't change any of the actual translations, just the English words (enum) that represent the translations.

**Review by naomi-lgbt — CHANGES_REQUESTED** [review]
Thanks for your interest in contributing.

To clarify, you should only make the docs changes in the English documentation files. The i18n files will be updated in the next translation sync after this PR is merged.

**Comment by th3oth3rjak3** [comment]
I misunderstood about the translations. What would be the best way for me to move forward? Should I reset this branch back to main and then redo the updates on only the docs files?

**Comment by naomi-lgbt** [comment]
That could work. You could also run `git checkout main -- docs/i18n`, and commit+push the changes.

**Pull request closed without merging**
