### PR TITLE
Added ; after object initialization

### LINKED ISSUE #14677: Accessing object properties : missing semicolon in example code
#### Challenge Name

https://www.freecodecamp.com/challenges/accessing-objects-properties-with-variables

#### Issue Description

Both of the examples don't have a `;` after the object initialization. 

#### Screenshot

freecodecampbug

### PR DESCRIPTION
**Pull request by amartyaamp**
Not mandatory but adding for the sake of consistency of tutorials.

#### Pre-Submission Checklist

- [ ] Your pull request targets the `staging` branch of freeCodeCamp.
- [ ] Branch starts with either `fix/`, `feature/`, or `translate/` (e.g. `fix/signin-issue`)
- [x] You have only one commit (if not, [squash](http://forum.freecodecamp.com/t/how-to-squash-multiple-commits-into-one-with-git/13231) them into one commit).
- [ ] All new and existing tests pass the command `npm test`. Use `git commit --amend` to amend any fixes.

#### Type of Change

- [x] Small bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds new functionality)
- [ ] Breaking change (fix or feature that would change existing functionality)
- [ ] Add new translation (feature adding new translations)

#### Checklist:

- [ ] Tested changes locally.
- [x] Closes currently open issue : Closes #14677

### CODE REVIEW

**Review by raisedadead — APPROVED** [review]
LGTM

**Comment by raisedadead** [comment]
@amartyaamp Thanks for the pull request.

Since this is done over the GitHub interface, I am assuming that the change was NOT tested locally? 
Please confirm.

We request that contributors fill in the opening post of this pull request correctly for a review.

Kindly add the issue no in the `Closes` tag replacing the `XXXX` with the number.

Thanks again for your interest in helping us out! Goodluck.

**Comment by amartyaamp** [comment]
Did necessary changes  - @raisedadead .

**Comment by raisedadead** [comment]
#### :sparkles: :sparkles: **Awesome.** :sparkles: :sparkles: 

Thanks @amartyaamp and congratulations on your first contribution to freeCodeCamp.

**Pull request merged**
