### PR TITLE
Fix regex test case and description

### PR DESCRIPTION
**Pull request by aviato**
I (hopefully) fixed the the regex to so that it won't look for the "+" symbol anymore. I also tried to update and reformat the description. [Here](http://freecodecamp.com/challenges/waypoint-sift-through-text-with-regular-expressions) is the link to the waypoint in question.

**These issues were all regarding the regex test-case using the '+' token:**
closes [#2357](https://github.com/FreeCodeCamp/FreeCodeCamp/issues/2357)
closes [#2053](https://github.com/FreeCodeCamp/FreeCodeCamp/issues/2053)
closes [#2331](https://github.com/FreeCodeCamp/FreeCodeCamp/issues/2331)
closes [#1938](https://github.com/FreeCodeCamp/FreeCodeCamp/issues/1938)
closes [#2163](https://github.com/FreeCodeCamp/FreeCodeCamp/issues/2163)
closes [#2345](https://github.com/FreeCodeCamp/FreeCodeCamp/issues/2345)

**This issue was about the instructions being vague or wrong on the same waypoint:**
closes [#1997](https://github.com/FreeCodeCamp/FreeCodeCamp/issues/1997)

Let me know if anything is wrong and I'll fix it.

Cheers :beers:

### CODE REVIEW

**Comment by BerkeleyTrue** [comment]
Please change the title to be descriptive of the changes you have made.

Also state which issues, if any, that this PR closes in the description each on its own line. For example: `closes #1337`

**Comment by rsprice** [comment]
@BerkeleyTrue fixed. Would you like me to list all the duplicate issues I can find as well?

**Comment by BerkeleyTrue** [comment]
yes, that way github will autoclose them when this PR is merged.

````
closes #1337
closes #1338
...
```

**Comment by rsprice** [comment]
@BerkeleyTrue hopefully that's good now.

**Comment by abhisekp** [comment]
@rsprice already closed in PR #2490

**Comment by benmcmahon100** [comment]
Hey @rsprice thanks for submitting this fix! We seem to have had another pr that has since fixed the issue but it has not been deployed yet. Happy Coding

**Pull request closed without merging**
