### PR TITLE
Remove unnecessary and inconsistent quotes from curriculum/challenges/russian (Fix for #35481)

### PR DESCRIPTION
**Pull request by roshni-b**
1. Many instances in the Test sections where quotation marks had been used inconsistently (sometimes encapsulating the test strings and sometimes not) - those have been fixed and made consistent.

2. In places where the code tags already highlight the code and quotes are unnecessary, the quotes have been removed.

- [x ] I have read [freeCodeCamp's contribution guidelines](https://github.com/freeCodeCamp/freeCodeCamp/blob/master/CONTRIBUTING.md).
- [x ] My pull request has a descriptive title (not a vague title like `Update index.md`)
- [x ] My pull request targets the `master` branch of freeCodeCamp.
- [x ] None of my changes are plagiarized from another source without proper attribution.
- [x ] All the files I changed are in the same world language
- [ x] My changes do not use shortened URLs or affiliate links.

### CODE REVIEW

**Review by RandellDawson — CHANGES_REQUESTED** [review]
> Many instances in the Test sections where quotation marks had been used inconsistently (sometimes encapsulating the test strings and sometimes not) - those have been fixed and made consistent.

@roshni-b You are removing quotes where it is not needed and with all of these unnecessary changes, you have made this PR much more difficult to review than necessary.  Please review the original issue to figure out exactly what you should be targeting.  You should be making changes to no more than 15-20 files (based on what was changed in the English PR for the same issue).  Also, you should be doing all of this locally and squashing all your commits, so there is only a single commit (not 248 like you have now).

Can you explain what criteria you were using to target and replace this many?

**Comment by roshni-b** [comment]
> Can you explain what criteria you were using to target and replace this many?

This had been done before for the English files, so I removed the unnecessary quotes here as well. The ones in the test section might be redundant. (Reference: https://github.com/freeCodeCamp/freeCodeCamp/pull/18828/commits/d912b1ed1eb8f10d43441a4432e30bbaa0a0cbeb)

> Also, you should be doing all of this locally and squashing all your commits, so there is only a single commit (not 248 like you have now).

Sorry for the mess, shall I delete my local repo and revert the changes?

**Comment by RandellDawson** [comment]
No reason to delete your fork.  However, you should typically not be making changes to your forked master branch.  You should get in the habit of creating a new branch on the fork, so your master stays "clean".  

As far as removing those other quotes.  Let's not do that in this PR.  Just focus on the same changes that PR https://github.com/freeCodeCamp/freeCodeCamp/pull/35493 changes.  This will make it easier to review.  Those other changes will be dealt with by the core team if and when they feel it necessary to do so.

**Comment by RandellDawson** [comment]
Thank you for opening this pull request.

This is a standard message notifying you that we’ve reviewed your pull request and have decided not to merge it. We would welcome future pull requests from you.

**Reason:** You should only be changing maybe 14-16 files as the other PRs have done for the same issue.  I suggest you resync your forked branch and then try again.

Thank you and happy coding.

**Pull request closed without merging**
