### PR TITLE
Rename challenge slice-and-splice to frankensplice

### PR DESCRIPTION
**Pull request by majestic-owl448**
Checklist:

- [x] I have read [freeCodeCamp's contribution guidelines](https://contribute.freecodecamp.org).
- [x] My pull request has a descriptive title (not a vague title like `Update index.md`)
- [x] My pull request targets the `main` branch of freeCodeCamp.
- [ ] I have tested these changes either locally on my machine, or GitPod.

Related to https://github.com/freeCodeCamp/freeCodeCamp/issues/43064#issuecomment-889296023

I hope I managed to do all the right steps

### CODE REVIEW

**Comment by ieahleen** [comment]
ok, I missed one step. commit coming soon

**Comment by moT01** [comment]
I was actually semi joking with that comment @ieahleen - I do think it's a better name, but I'm not sure if we want to actually rename it or not.

**Comment by ieahleen** [comment]
@moT01 😂 should I close it?

**Comment by moT01** [comment]
I think it's fine to leave it open - I think we should discuss whether we want this or not though a little bit.

**Comment by ShaunSHamilton** [comment]
A little funny how this PR came to be...

I think it best not to change the name, though

**Comment by nhcarrigan** [comment]
Renaming files resets their translation progress - IMHO best to avoid unless absolutely needed.

**Pull request closed without merging**
