### PR TITLE
fix: make fcc console dynamic and more informative

### PR DESCRIPTION
**Pull request by ojeytonwilliams**
Previously only challenges with previews would inform the user of syntax errors.  This extends that to all challenges and corrects the output format so all errors are clearer.

Before css change:
image
and after
image

One side-effect is that this makes the debugging challenges even easier - possibly too easy.  I'm not sure how to avoid that, though.

---

Errors thrown during execution will appear in both consoles.  JS: errors and logs from evaluating the user's code will only be reported during the first test, but non-assertion errors thrown during testing will also appear in both consoles.  

---

Now both html and js challenges output console logs and error messages to the fcc console as the user types.

---

Any errors generated once the preview frame has been created will also be logged (if a click listener throws an error, for example).  ~~Console logs are still ignored after the frame is ready~~.

### CODE REVIEW

**Comment by ojeytonwilliams** [comment]
One job remains: stop JS challenges from console.logging each test.

**Comment by RandellDawson** [comment]
@ojeytonwilliams Quick question. wouldn't you want to include other challengeTypes 5 (other JavaScript challenges), 6 (jQuery, React/Redux) and 7 (APIs and Microservices) in addition to challengeType 1 which you are doing below?  I might be missing something.

```js
export function isJavaScriptChallenge({ challengeType }) {
  return challengeType === challengeTypes.js;
}
```

**Comment by ojeytonwilliams** [comment]
@RandellDawson pointed out that, on balance, it's more useful to have the console logs always reported.  While it will be confusing if your code passes the tests with error-throwing code, it's more frustrating not to see the console output when it's failing.  I'll fix that ASAP.

Also, it would be better if the logs only appeared once in the browser console, rather than once in the fcc console and multiple times in the browser.  I'll see what I can do.

**Comment by ojeytonwilliams** [comment]
@raisedadead this PR has been through a bunch of iterations, but I think it's finally worth looking at.

There are a couple of issues remaining

1) there's a brief flash of

```
/**
* Your test output will go here.
*/
```
every time the preview updates.  This is annoying, but it dramatically simplifies the frame code.  If you think it's *too* annoying it can be fixed.

2) if a non-assertion error is thrown during testing, the user gets a report in the fcc console.

Mostly this is beneficial.  Say someone writes

```js
const f = () => {throw Error('whoops')};
```
and the test calls `f()` it's at least somewhat helpful to know that something is throwing an error.  What's less useful is when the tests throw something that's more about the test itself than the user's code.

For example http://localhost:8000/learn/javascript-algorithms-and-data-structures/basic-javascript/understanding-case-sensitivity-in-variables

If you run the tests for this challenge you get:
```
...
// console output

"ReferenceError: STUDLYCAPVAR is not defined"
"TypeError: Cannot read property 'length' of null"
"TypeError: Cannot read property 'length' of null"
```
The first error is useful, but the second two come from 
```js
assert(code.match(/properCamelCase/g).length === 2);
```
and could be confusing.

**Review by raisedadead — APPROVED** [review]
Tested this briefly and I am personally happy. This improves the UX way better than what we have. @RandellDawson when you get a moment, can you approve too?

**Comment by RandellDawson** [comment]
I will take a look at this one today.

**Comment by raisedadead** [comment]
Hi @RandellDawson just a gentle reminder if you have a minute to take a look at this.

**Comment by ojeytonwilliams** [comment]
I wasn't thinking about the projects much while I was doing this and I now realise it breaks the JavaScript Algorithms and Data Structures Projects.  It's probably an easy fix, but I'll do that after a night's sleep.  

The backend ones aren't affected and probably shouldn't be, since they their output isn't helpful and Glitch produces it's own logs. The other projects look to be fine, but I'll double-check tomorrow.

**Comment by ojeytonwilliams** [comment]
Remaining tasks from review:
- [ ] `console.log`s inside `testString`s should appear in the browser console only
- [ ] non-assertion errors thrown during the tests should appear in the browser console only
- [ ] projects without previews (Build a Tribute Page etc.) should not try to build them

@RandellDawson does that cover it?

**Comment by RandellDawson** [comment]
@ojeytonwilliams Yes that covers it.

**Comment by ojeytonwilliams** [comment]
> Though, I don't think there should ever be console.log statements left in testStrings anyway.

Indeed.  I think, given that, it's not a big problem if they appear in the fcc console.  In principle I could restrict that, but it adds needless complexity to the DOM challenges testing code, so perhaps not.

**Review by RandellDawson — APPROVED** [review]
I am satisfied with the trade-offs that are made in this PR.

Once this PR is landed, we need to update [this challenge](https://www.freecodecamp.org/learn/javascript-algorithms-and-data-structures/debugging/understanding-the-differences-between-the-freecodecamp-and-browser-console) to better highlight the differences between the FCC console and the browser console, so users will better understand why they may see differences.

One of the big differences they will quickly notice is the fact that if they add a console.log statement in their code, it will only show in the browser, once `Run Tests` button is clicked and it will end up showing multiple times (once for each test).

**Pull request merged**
