### PR TITLE
Fixed outdated info

### PR DESCRIPTION
**Pull request by hegdenischay**
C++98 wasn't the standard for a long time. gnu++14 is the current standard and this pull request corrects that.

- [x] I have read [freeCodeCamp's contribution guidelines](https://github.com/freeCodeCamp/freeCodeCamp/blob/master/CONTRIBUTING.md).
- [x] My pull request has a descriptive title (not a vague title like `Update index.md`)
- [x] My pull request targets the `master` branch of freeCodeCamp.
- [x] None of my changes are plagiarized from another source without proper attribution.
- [x] My article does not contain shortened URLs or affiliate links.

If your pull request closes a GitHub issue, replace the XXXXX below with the issue number.

Closes #XXXXX

### CODE REVIEW

**Comment by thecodingaviator** [comment]
Please state a source for your changes

**Comment by hegdenischay** [comment]
Here's the source:
https://gcc.gnu.org/onlinedocs/gcc-9.1.0/gcc/Standards.html#Standards

>The default, if no C++ language dialect options are given, is -std=gnu++14.

**Comment by RandellDawson** [comment]
@hegdenischay I believe @thecodingaviator meant for you to properly cite the source in the article. 
 [View Free Code Camp's citation policy](https://github.com/freeCodeCamp/freeCodeCamp/blob/master/docs/style-guide-for-guide-articles.md#attributions)

**Comment by hegdenischay** [comment]
Okay, will do.
I thought that it wasn't necessary since the original didn't cite anything.

**Review by thecodingaviator — APPROVED** [review]
Thanks @hegdenischay !

**Comment by thecodingaviator** [comment]
Thank you for your contribution to the page! 👍
We're happy to accept these changes, and look forward to future contributions. 📝

**Pull request merged**
