### PR TITLE
Fix: challenge map lost

### LINKED ISSUE #16147: New users progress can be wiped unintentionally
#### Issue Description

Many campers are reporting to the forum that all their progress has been wiped: https://forum.freecodecamp.org/search?q=lost%20progress

Steps to replicate:
1. create a new account with email sign-up
2. do not verify your email address (may not be the issue)
3. You’ll need to sign in again as a returning camper to see challenges
4. complete a number of challenges - two is fine
5. sign out
6. clear local storage and cookies
7. sign back in

After that the progress should be lost. It doesn't happen again, as far as I can tell, but can be consistently replicated on a fresh account.

Confirmed by bengitter: https://forum.freecodecamp.org/t/i-think-i-can-replicate-the-lost-all-progress-bug/162323/2?u=jacksonbates

#### Browser Information

* Browser Name, Version: Firefox 57.0.1 (but also reported on Chrome)
* Operating System: Ubuntu 16.04
* Mobile, Desktop, or Tablet: Desktop

### PR DESCRIPTION
**Pull request by BerkeleyTrue**
closes #16147

### CODE REVIEW

**Comment by QuincyLarson** [comment]
This fixes the issue, but seems to introduce a new bug. 

learn_how_freecodecamp_works___freecodecamp

Steps to reproduce:

1) Create a new account
2) Instead of verifying your email, click the "sign in" button again and sign into the account you just created
3) You'll get sent to the first challenge "Learn How freeCodeCamp Works". Complete it and you'll get sent back to it. You can never advance to the subsequent challenge, and the map will show 2 copies of this challenge for some reason (see picture above)

**Comment by raisedadead** [comment]
@QuincyLarson I can confirm that the duplicate challenge as you see above is pre-existing before this PR.

**Comment by QuincyLarson** [comment]
@raisedadead Are we experiencing this in production? Or just locally? I'm unable to reproduce this in production or locally on the backup/master branch.

**Comment by raisedadead** [comment]
Yes, I cannot, see this in production. And local this problem is not visible after a DB Purge. Did we happen to change the challenge id accidentally? Meaning we have duplicate challenges in the DB only?

**Comment by raisedadead** [comment]
This challenge was last modified in https://github.com/freeCodeCamp/freeCodeCamp/pull/15667 

The section 
`seed/challenges/01-front-end-development-certification/gear-up-for-success.json`
was removed.

Its possible, that this is redundant and not removed from the DB.
@BerkeleyTrue is the seed script supposed to NOT remove any challenge?

If that is true, we can safely ignore this issue (and fix up if required on production).

**Comment by QuincyLarson** [comment]
@raisedadead As far as I can tell there are no issues with production. This isn't some duplicate record in a database - this seems to be a new bug I've never seen before. Are you certain you've seen this before and that this PR doesn't introduce this bug? 

Since we're deploying @BerkeleyTrue's code to production, we need to be sure. I'm concerned because this bug seems to make freeCodeCamp unusable.

**Comment by raisedadead** [comment]
> Are you certain you've seen this before and that this PR doesn't introduce this bug?

Yes, I have seen this before. And I haven't even pulled down this PR for a QA. So its unlikely that this is related to this PR.

But, the fact that we both have seen it. We still need investigation. I am awaiting Berkeley's clarification what the seed script does about deleting challenges when we run `node seed`.

BTW, @QuincyLarson did you happen to run `node seed` when you pulled down this PR?

**Comment by BerkeleyTrue** [comment]
Node seed will clear the database of challenges before uploading new ones. This bug is unrelated to this pr

**Comment by raisedadead** [comment]
Tested the PR changes, and it fixes the original issue. I cannot reproduce the issue that Quincy mentions though(any longer).

As Berkeley, confirms the seed script should clean up all challenges, we might need an investigation.

It would be faster to debug on Quincy's setup.

IMHO we should still go forth with merging and deploy. Its still better than the current state of production, and since we do not have a confirmation of this new issue.

**Comment by QuincyLarson** [comment]
@BerkeleyTrue @raisedadead I agree that we should go ahead and deploy this fix. But immediately after we deploy it we should make sure we're not experiencing this issue in production, and I can monitor gitter/twitter to make sure no one else experiences it there either.

**Comment by BerkeleyTrue** [comment]
This is now in production. I don't see any issues with double challenges

**Comment by raisedadead** [comment]
Nice work @BerkeleyTrue 🍻 !!

**Comment by QuincyLarson** [comment]
I can confirm no issue with double challenges or with not being able to advance past the first challenge.

**Pull request merged**
