### PR TITLE
feat: remove github prebuild config

### PR DESCRIPTION
**Pull request by Sboonny**
Checklist:

- [x] I have read and followed the [contribution guidelines](https://contribute.freecodecamp.org).
- [x] I have read and followed the [how to open a pull request guide](https://contribute.freecodecamp.org/#/how-to-open-a-pull-request).
- [x] My pull request targets the `main` branch of freeCodeCamp.
- [x] I have tested these changes either locally on my machine, or GitPod.

this is deprecated in favour of the project tab in `https://gitpod.io/projects/[projectName]-[projectId]/prebuilds`

image

### CODE REVIEW

**Comment by ojeytonwilliams** [comment]
@Sboonny can/have we configured those settings?

**Comment by Sboonny** [comment]
Looking at the [Configuring prebuilds manually](https://www.gitpod.io/docs/configure/projects/prebuilds#configuring-prebuilds-manually) in the docs, we need to add it to their projects to a team, give them permission to integrate, and it will run the main branch for the people in the team.

**Comment by Sboonny** [comment]
closed in favor #51890 51890

**Comment by ShaunSHamilton** [comment]
@Sboonny Sorry. I completely missed this PR. We can reopen this, and close mine.

**Comment by Sboonny** [comment]
Nope, I am happy with you taking it over, and I think you are more rhetoric than me, so your PR should be merged faster 👍.

**Pull request closed without merging**
