### PR TITLE
fix: add tests for exercise tracker

### LINKED ISSUE #37633: Exercise Tracker needs tests
Individual thread for the Exercise Tracker portion of #37185

Trying to get involved, and this seems like as good a place as any to start. I haven't had a chance to get setup locally, but what I've gathered so far from the contribution docs and issues i've looked at is that
- tests are executed in a browser environment (not node)
- chai assertions are available
- tests are stored as a stringified function

I may have missed something important - hopefully not, but please let me know.

For the exercise tracker, something like the below might work. It still needs to be stringified and using `getUserInput` to grab the user's url in the actual test. 

`- text: I can create a user by posting form data username to /api/exercise/new-user and returned will be an object with username and <code>_id</code>.`
```js
fetch( 'https://fuschia-custard.glitch.me'+ '/api/exercise/new-user', {
  method: 'POST',
  headers: { 'Content-Type': 'application/x-www-form-urlencoded' },
  // anything longer fails: 'username too long'
  body: `username=fcc_test_${ Date.now() }`.substr(0, 29)
}).then(res => {
  if (res.ok) { 
    res.json().then(data => {
      assert.exists(data._id); 
      assert.exists(data.username);
    }); 
  } else throw new Error(`${ res.status } ${ res.statusText }`);
}, e => {throw new Error(e)} );
```
Using the truncated current time to produce a unique username seems a bit sketchy though.

`- text: I can get an array of all users by getting api/exercise/users with the same info as when creating a user.`
```js
fetch('https://fuschia-custard.glitch.me' + '/api/exercise/users')
    .then(res => res.json().then(data => assert.isArray(data)), e => { throw new Error(e)});
```

And so on for the others. Am I terribly off track?

### PR DESCRIPTION
**Pull request by PartyLich**
Exercise Tracker portion of #37185

- [x] I have read [freeCodeCamp's contribution guidelines](https://github.com/freeCodeCamp/freeCodeCamp/blob/master/CONTRIBUTING.md).
- [x] My pull request has a descriptive title (not a vague title like `Update index.md`)
- [x] My pull request targets the `master` branch of freeCodeCamp.
- [x] None of my changes are plagiarized from another source without proper attribution.
- [x] All the files I changed are in the same world language (for example: only English changes, or only Chinese changes, etc.)
- [x] My changes do not use shortened URLs or affiliate links.

Closes #37633

### CODE REVIEW

**Review by moT01 — CHANGES_REQUESTED** [review]
Thanks for working on this @PartyLich - these backend projects are kind of a pain. I didn't look into the tests you created to hard, but I am able to submit `google.com` and pass. Which is what we are trying to avoid...
Screen Shot 2019-11-10 at 12 27 11 PM

Let me know if you need more help, I can take a closer look. Seems like you are on the right track - [here's an example of tests](https://github.com/freeCodeCamp/freeCodeCamp/pull/37187/files) I made for one of the projects. Keep in mind that these don't have to be perfect - just something so people can't submit any random URL.

**Comment by PartyLich** [comment]
> Let me know if you need more help, I can take a closer look. Seems like you are on the right track - [here's an example of tests](https://github.com/freeCodeCamp/freeCodeCamp/pull/37187/files) I made for one of the projects. Keep in mind that these don't have to be perfect - just something so people can't submit any random URL.

I think I located my errors. Cleaned up a few inconsistent bits as well. running the local container:
- Fails everything with google.com
- passed with the sample url
- added a test to check that the example url isn't being used (using ojeytonwilliams regex)

**Review by moT01 — APPROVED** [review]
Nice job @PartyLich 🎉 - thanks for all the work on this 🎉 

You added six tests, I will share my findings for reference.

Test 1 => LGTM, doesn't pass with example URL
Test 2 => LGTM, failed with unexpected response, passed with expected
Test 3 => LGTM, failed unless array is returned
Test 4 => Something seems to be wrong with the `deepEqual` I think, I was able to pass with this response...
Screen Shot 2019-11-12 at 8 48 02 PM
But I'm fine with one test passing when it shouldn't for these. Otherwise, feel free to take a look.
Test 5 => LGTM, failed with bad response - passed with expected. Could maybe add a check for the `count` - but not needed
Test 6 => LGTM, failed with bad response - passed with expected.

I'm fine with adding these as is - my biggest concern is that people won't understand the correct routes to build because the instructions aren't clear enough, although the routes are stated - they could be more clear. I'm thinking we just add this and if people start having issues, we can go and make the instructions better.

Edit: I suppose we should probably take a look at that 4th test - probably better to not have it, then have it falsely passing.

More Edits: I guess, I dunno - they're all falsely passing right now. Let me know what you think @PartyLich

**Review by moT01 — CHANGES_REQUESTED** [review]
See comment above

**Comment by PartyLich** [comment]
> Edit: I suppose we should probably take a look at that 4th test - probably better to not have it, then have it falsely passing.

I agree it's better to not have it if it isn't working. I should have a chance tomorrow to chop that test from this commit so we can get the others in, and I/we can add the last test in a later commit. Incremental progress is way better than no progress

>More Edits: I guess, I dunno - they're all falsely passing right now. Let me know what you think @PartyLich
I may be too tired atm, but i'm unclear if you mean 'users are falsely passing all tests right now (deployed version) because the tests dont exist' or 'all the tests I wrote are giving false positives'

**Comment by moT01** [comment]
> i'm unclear if you mean 'users are falsely passing all tests right now (deployed version) because the tests dont exist' or 'all the tests I wrote are giving false positives'

The tests all pass on production because they aren't written.

**Comment by PartyLich** [comment]
Dropped the 4th test content, though i left the text for it in place. So atm it's back to it's current production state.

When i updated my other tests from `fetch(...).then(..)` to `... = await fetch(..)` i apparently missed the one in test 4. So it appears to me the deepEqual wasn't firing at all. After changing it, the dates don't line up. Top of my head I'd assuming that's because client side and server side timezones don't match
image
It's already tomorrow as far as the server is concerned :) Any suggestions on accurately testing a timestamp if that client/server difference is the actual cause? I guess i could specify GMT or whatever glitch's servers are set to. That might be an improvement, but the rare student who self hosts might hit this unfortunate corner anyway. idk

**Comment by moT01** [comment]
how about hard coding a date in there?

**Comment by PartyLich** [comment]
There are/were two problems with test #4 as I see it:
```
fetch(url + '/api/exercise/add', {	
          method: 'POST',	
          headers: { 'Content-Type': 'application/x-www-form-urlencoded' },	
          body: `userId=${_id}&description=${expected.description}&duration=${expected.duration}`	
        }).then(async res => {	
          if (res.ok) {	
            const exercise = await res.json();	
            assert.deepEqual(exercise, expected);	
          } else {	
            throw new Error(`${res.status} ${res.statusText}`);	
          }	
        });
```
The results of this `.then()` block did not seem to be having any effect on the test status. When I ran it tonight in that form with some added console logging, the objects were clearly unequal but the assertion wasn't throwing. As you had called attention to. Changing that to an await resolved that issue:
```
const addRes = await fetch(url + '/api/exercise/add', {
          method: 'POST',
          headers: { 'Content-Type': 'application/x-www-form-urlencoded' },
          body: `userId=${_id}&description=${expected.description}&duration=${expected.duration}`
        });
        if (addRes.ok) {
          const actual = await addRes.json();
          console.table({actual, expected});
          assert.deepEqual(actual, expected);
        } else {
          throw new Error(`${addRes.status} ${addRes.statusText}`);
        }
```
Then the test was failing for the example because the date on the client and the date from the server did not match. Problem 2. So my suggestion for that is to update the `expected` object to UTC
```
const options = { weekday: 'short', year: 'numeric', month: 'short', day: 'numeric', timeZone: 'UTC' };
        const expected = {
          username,
          description: 'test',
          duration: 60,
          _id,
          date: new Date().toLocaleDateString('en-us', options).replace(/,/g,'')
        };
```

Two problems, two fixes, and ideally one properly working test. It sure makes me feel terribly sloppy for submitting the original though

**Comment by moT01** [comment]
What about the issue of the dates not aligning if a server has another time zone? Hard coding a date in there no good?

Also, none of that explains why the test in my picture passed.

And finally, I think I would rather have the test you made there, as long as it doesn't fail when it should pass (which I don't think it does) - or remove the test and text completely. Because just removing the testString area will make let test pass every time.

**Comment by PartyLich** [comment]
Sure. Hard coded date. I was fixated on "If no date supplied it will use current date."

**Review by moT01 — APPROVED** [review]
LGTM 🎉

**Comment by ojeytonwilliams** [comment]
@PartyLich thanks for all your hard work, this is great!  Sorry it took us so long to review it properly.

**Pull request merged**
