### PR TITLE
Fix typo in title

### PR DESCRIPTION
**Pull request by gmacario**
Checklist:

- [x] I have read [freeCodeCamp's contribution guidelines](https://contribute.freecodecamp.org).
- [x] My pull request has a descriptive title (not a vague title like `Update index.md`)
- [x] My pull request targets the `master` branch of freeCodeCamp.
- [x] All the files I changed are in the same world language, for example: only English changes, or only Chinese changes, etc.

Closes #XXXXX

### CODE REVIEW

**Review by naomi-lgbt — DISMISSED** [review]
LGTM! Congratulations on submitting your first pull request! 🥳 

Our workflow requires a second member's approval before this can be merged. Thank you for your patience!

**Comment by Sky020** [comment]
@ojeytonwilliams ,

Can you confirm if we need to change the file name, as well as the meta.json before merging this?

**Review by moT01 — DISMISSED** [review]
Yes, those two things should be changed as well @Sky020 - Pretty sure that should be it, and this would be good.

**Comment by RandellDawson** [comment]
Let's wait until PR #39492 gets merged before merging this PR, so we do not get a merge conflict on the other PR.  It will create a merge conflict on this PR, but that is fine and we can fix it.  I just do not want to hold the other one up waiting on this one.

**Review by RandellDawson — APPROVED** [review]
LGTM now.

**Review by Manish-Giri — APPROVED** [review]
LGTM

**Comment by RandellDawson** [comment]
Congrats @gmacario on your first pull request (PR)! 🎉

Thank you for your contribution to the page! 👍
We're happy to accept these changes, and look forward to future contributions. 📝

**Pull request merged**
