### PR TITLE
Update news search field placeholder

### LINKED ISSUE #5987: Suggestion for improving News page
Suggestion for improving the News page in FCC: Provide other options for sorting the articles, especially to allow sorting by post date. The number of articles is growing quickly, and it's hard to quickly jump to the ones you haven't read since the order changes constantly based on upvotes. If you had the option to sort by post date, then you could quickly skip the ones you've seen.

### PR DESCRIPTION
**Pull request by ghost**
Changed placeholder text from 'Search our links' to 'search term or @username'. Tested locally. closes #5987

### CODE REVIEW

**Comment by bugron** [comment]
@0x0936 nice work. Thanks for posting this PR but it's not closing the issue you've pointed to.

>***
>Please review the [**Guidelines for Contributing**](https://github.com/FreeCodeCamp/FreeCodeCamp/blob/staging/CONTRIBUTING.md), thank you!.
>***

**Comment by 0x0936** [comment]
Can you be a little more specific? This isn't my first PR, and this has followed the same procedure for all prior PRs I've submitted - and I've read that document several times.

**Comment by bugron** [comment]
I understand, but #5987 will only be closed, when @GFore's feature request will be implemented.

**Comment by 0x0936** [comment]
Thanks, that makes sense.

**Comment by bugron** [comment]
@0x0936 why did you close this PR? You just needed to remove `closes #5987` from the description.

**Comment by 0x0936** [comment]
Thanks @bugron. That will be good to know for next time.

**Comment by GFore** [comment]
This doesn't really address my #5987 issue - I'm not so much interested in being able to search for articles submitted by a particular user (can just use the browser search function to do that). I want to be able to sort the list of articles by post date (and possibly by user and topic).

**Pull request closed without merging**
