### PR TITLE
Addsolutionto_commentyourjavascript

### PR DESCRIPTION
**Pull request by MurrayBakerWebDeveloper**

### CODE REVIEW

**Comment by ltegman** [comment]
I don't understand what you're trying to do with this `addsolutionto_commentoutyourjavascript` file that you've added. Plus you've got a merge commit in your commit log. Please view the [contribution guide](https://github.com/FreeCodeCamp/FreeCodeCamp/blob/staging/CONTRIBUTING.md) and visit the [Help Contributors](https://gitter.im/FreeCodeCamp/HelpContributors) chat if you need more help. Thanks!

**Comment by nuku89** [comment]
I wanted to add a solution to a problem. I created the branch, and attempted to make the pull request to staging. When did you see the commit? I don’t see anything from tonight:

Murrays-MacBook-Pro:freecodecamp MurrayBaker89$ git log --graph
*   commit 6936d35c5dccb4773189eaed6fee23947cfbd276
|\  Merge: ee69ff4 37b5784
| | Author: Logan Tegman <ltegman@gmail.com>
| | Date:   Tue Oct 27 19:36:39 2015 -0700
| |
| |     Merge pull request #3944 from mschultz4/fix/typos-intermediate-bonfire
| |
| |     Fixed typos in assert messages
| |
| * commit 37b5784899b3c4fe2eb9f6fea97c6d2e10eee55e
| | Author: mschultz4 <mschultz4@gmail.com>
| | Date:   Tue Oct 27 20:57:48 2015 -0400
| |
| |     Fixed typos in assert messages
| |
* |   commit ee69ff4314e5a1b9ef794d467dd314f0cab51ae0
|\ \  Merge: 17310b0 7605a92
| | | Author: Quincy Larson <QuincyLarson@users.noreply.github.com>
| | | Date:   Tue Oct 27 17:29:38 2015 -0700
| | |
| | |     Merge pull request #3885 from tdugger/fix/3884
| | |
| | |     The word several is repeated in step 11
| | |
:



Thanks
Murray

**Comment by ltegman** [comment]
addsolutionto_commentyourjavascript_by_nuku89_ _pull_request__6074_ _freecodecamp_freecodecamp

**Comment by nuku89** [comment]
What was wrong with the pr?

**Comment by ltegman** [comment]
It had the merge commit I just showed you and it was creating a file called `addsolutionto_commentoutyourjavascript`, which should not be happening.

**Comment by nuku89** [comment]
Can you create a branch without creating a file? Sorry where do I make text changes?

**Comment by ltegman** [comment]
Creating a branch does not create any additional files, it just makes a copy of the current commit history under a new branch. Changes should be occurring in whatever file you are changing (in a well-named branch). You should not be making a PR on your own for before making a PR against FCC's staging, because that is what adds the merge commit we don't want.

**Comment by nuku89** [comment]
Aha, one PR too many. The naming wasn’t right either

**Pull request closed without merging**
