### PR TITLE
refactor: handle certs separately

### PR DESCRIPTION
**Pull request by ojeytonwilliams**
- refactor: split createChallenge into two functions
- refactor: remove certification metas

### CODE REVIEW

**Comment by ShaunSHamilton** [comment]
I assume we can ignore that CodeScanning result, for now?

**Comment by ojeytonwilliams** [comment]
> I assume we can ignore that CodeScanning result, for now?

I've never even seen an uppercase SCRIPT, so I ignored it. Touch lazy, but it seems like such a tiny edge case that I doubt it'll matter.

**Review by naomi-lgbt — DISMISSED** [review]

**Comment by ShaunSHamilton** [comment]
What about the `legacy-` certs?

**Comment by ojeytonwilliams** [comment]
I don't think they need handling separately.  All a certification really needs is a .yml file to define it. Both current and legacy certifications have the same basic logic (have you completed all the projects defined in the yml file?  Okay, you're done)

**Comment by ojeytonwilliams** [comment]
Or rather, any special handling should be (and is) code, not configuration.

**Comment by ShaunSHamilton** [comment]
> Or rather, any special handling should be (and is) code, not configuration.

That is fine, I just do not like the fact that certs are now in different places (have a different number of associated files).

Do we move (add) the Quality Assurance certificate back to this folder, once it becomes legacy?

**Comment by nhcarrigan** [comment]
So can we delete the legacy cert meta?

**Comment by ojeytonwilliams** [comment]
Sorry, I think we were talking at cross purposes.  I just missed those metas, sorry about that!

**Review by ShaunSHamilton — APPROVED** [review]
I am happy there are more deletions than additions 👍

**Review by naomi-lgbt — APPROVED** [review]
Looks good to me. I'm still able to claim a cert, and the map looks to be fine.

**Pull request merged**
