### PR TITLE
feat(curriculum): add more semantic elements to JavaScript certificate projects

### PR DESCRIPTION
**Pull request by Re1nGer**
Checklist:

- [x] I have read and followed the [contribution guidelines](https://contribute.freecodecamp.org).
- [x] I have read and followed the [how to open a pull request guide](https://contribute.freecodecamp.org/#/how-to-open-a-pull-request).
- [x] My pull request targets the `main` branch of freeCodeCamp.
- [x] I have tested these changes either locally on my machine, or GitPod.

Related to #53214

Now tests allow to put ```div```, ```span``` or ```p``` tags to hold the result

### CODE REVIEW

**Review by moT01 — CHANGES_REQUESTED** [review]
I think we should change the test text here too. e.g. on line 63 of the cash register project file - ``You should have a `div`, `span`, or `p` element with an `id` of `"change-due"`.``

Same for the tests in the other projects.

**Comment by moT01** [comment]
Any chance you can add those suggested changes @Re1nGer?

**Comment by Ksound22** [comment]
Hi @Re1nGer 👋🏽

I went through and things look good, but I agree with @moT01 that line 63 of the Cash Register project should be changed to what he suggested.

So, I'll be here to approve once you make that change.

**Comment by Re1nGer** [comment]
Hi @Ksound22 @moT01 , thanks for pointing out suggested changes 
I pushed requested changes just now

**Review by Sembauke — APPROVED** [review]

**Review by Ksound22 — APPROVED** [review]

**Review by moT01 — APPROVED** [review]
LGTM @Re1nGer 🎉 Thanks for contributing to freeCodeCamp 🎉

**Pull request merged**
