### PR TITLE
feat/fix(client): refactor certMap and fix date propType

### PR DESCRIPTION
**Pull request by ShaunSHamilton**
Checklist:

- [x] I have read [freeCodeCamp's contribution guidelines](https://contribute.freecodecamp.org).
- [x] My pull request has a descriptive title (not a vague title like `Update index.md`)
- [x] My pull request targets the `master` branch of freeCodeCamp.
- [x] All the files I changed are in the same world language, for example: only English changes, or only Chinese changes, etc.

### CODE REVIEW

**Comment by Sky020** [comment]
Dev Team, this implementation renders the certs on the settings page in the order provided by their `order` property. However, as it currently is, the legacy certs are not ordered in any particular way.

Is this implementation ok? Or, should it match the current (production) order?

**Comment by ojeytonwilliams** [comment]
Hey Shaun, apologies for the delay getting to this.  Is this PR ready for review?

> Dev Team, this implementation renders the certs on the settings page in the order provided by their order property. However, as it currently is, the legacy certs are not ordered in any particular way.

So, this would just be the order Legacy Front End, Legacy Back End and so on appear (after Legacy Full Stack Certification)?  I don't think that matters much and we can always change their order properties.

**Comment by ojeytonwilliams** [comment]
I was thinking about this PR from an internationalisation perspective.  What I think we we need to do is add some additional properties to the certificates.  The approach here, where properties of the title are used in the logic, is likely to cause problems when the titles are translated.  Could we add more properties to the frontmatter and use those instead?  For instance using `version: 7` and/or `isLegacy: true` as needed would mean the titles could be freely translated without breaking anything.

**Comment by ShaunSHamilton** [comment]
@ojeytonwilliams No, this is not ready for review. I keep pushing it back as changes are made to the associated files.

> I was thinking about this PR from an internationalisation perspective. What I think we we need to do is add some additional properties to the certificates.

Very good point. I will be able to spend some time looking through this kind of this, these holidays. I would like clarification, though, on where and what I can change/add?

I am not a fan of giving some certs/projects properties, and not others. So, could I adjust all files for consistency, or would this be undesirable?

**Comment by ojeytonwilliams** [comment]
> @ojeytonwilliams No, this is not ready for review. I keep pushing it back as changes are made to the associated files.

I'm working on them too, but I'll fix any conflicts (just ping me in chat if I forget).

> I am not a fan of giving some certs/projects properties, and not others. So, could I adjust all files for consistency, or would this be undesirable?

Changing them all is fine by me - there are only 15 certificate files after all.  If we were talking about a change that's only relevant for a small number of challenges, we could consider defaulting when that property is absent.  Since it's a small number, I agree that consistency is the main thing.

**Comment by ojeytonwilliams** [comment]
FYI: one thing I'm trying out is adding info like

```
superBlock: information-security-v7
flag: isInfosecCertV7
```

to the frontmatter.

**Comment by ShaunSHamilton** [comment]
@ojeytonwilliams Before I do any more on this, and need to rework with rebasing, I would prefer to get:
1) https://github.com/freeCodeCamp/freeCodeCamp/pull/40071
2) https://github.com/freeCodeCamp/freeCodeCamp/pull/40225

Both of the above merged, as they touch associated files. Will the above be blocked by this Code Freeze?

**Comment by raisedadead** [comment]
We are going to be doing a head branch rename. I understand this is a high-priority PR. I can stow this on a separate branch on the main repo for now if you all prefer.

**Comment by ShaunSHamilton** [comment]
@raisedadead 
>I understand this is a high-priority PR. I can stow this on a separate branch on the main repo for now if you all prefer.

This is not really _high-priority_. So, I do not mind whether you close this and move it to a separate branch or just close. Once the related PRs are sorted, I can get back to this with a new branch, if need be.

**Comment by raisedadead** [comment]
I have gone ahead and re-targeted this to the main branch that we just created. You may need a rebase before this is actually merged

**Comment by ojeytonwilliams** [comment]
Hi @ShaunSHamilton nice work on the other two PRs :tada: 

I finally got around to converting from .markdown to .yml so there might be a few conflicts.  Turned out the conversion was simply a matter of deleting everything that wasn't already yaml, so it should not be a painful rebase.  If that proves not to be the case, let me know and I'll try and sort it out.

**Comment by ShaunSHamilton** [comment]
@ojeytonwilliams Thank you. The conflicts are minimal, and I will probably merge the current changes from `main` into the `curriculum` challenge files I changed. Once I have time, I will plough through this again, and find a better way to do what I was originally trying.

**Comment by ojeytonwilliams** [comment]
Cool, cool - no rush at all.

We can always hop on a call if there's something you'd like to discuss.  Otherwise, I'm looking forward to the rework.

**Comment by ShaunSHamilton** [comment]
Closing as stale, and would hold back TS migration. Idea still useable, in principle.

**Pull request closed without merging**
