### PR TITLE
use a regexp to make sure user only changes the first line

### PR DESCRIPTION
**Pull request by JoolsMcFly**
#### Pre-Submission Checklist

- [x] Your pull request targets the `staging` branch of freeCodeCamp.
- [x] Branch starts with either `fix/`, `feature/`, or `translate/` (e.g. `fix/signin-issue`)
- [x] You have only one commit (if not, [squash](http://forum.freecodecamp.com/t/how-to-squash-multiple-commits-into-one-with-git/13231) them into one commit).
- [x] All new and existing tests pass the command `npm test`. Use `git commit --amend` to amend any fixes.

#### Type of Change

- [x] Small bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds new functionality)
- [ ] Breaking change (fix or feature that would change existing functionality)
- [ ] Add new translation (feature adding new translations)

#### Checklist:

- [x] Tested changes locally.
- [x] Closes currently open issue (replace XXXX with an issue no): Closes #XXXX

#### Description

Since instructions say to change `0` to get `12` and to only change the first line, this regexp will enforce both:
```
"assert(/var difference\\s*=\\s*45\\s*(?:-\\s*[0-9]*)*;?/.test(code),'message: Only change the first line');",
```

Valid inputs are:
```js
var difference = 45 - 33; // most basic one
var difference = 45 - 33; // most basic one with no semi colon
var difference = 45 - 30 - 3; // because why not
```
Above regexp allows users to type in multiple subtractions to get to `12`, with or without semi colon.

Thanks.

### CODE REVIEW

**Comment by dhcodes** [comment]
If it says to change the 0 (as a test), then we probably shouldn't allow `45-30-3` or we should remove that test. Secondly, you can still use `+` which seems odd, as in `45-40+7`. I think we should either be flexible or fixed but not both. cc @freeCodeCamp/moderators Thoughts?

**Comment by JoolsMcFly** [comment]
You're right. I initially only allowed `33` as valid answer. Then thought of adding multiple subtractions as long as they lead to the expected answer. 
I can also allow additions OR revert to only accept `33`. You guys decide but I like the idea of being able to do whatever arithmetic in the solution.

**Comment by Bouncey** [comment]
I don't think using multiple or mixed operators should be allowed. The instructions state to change only the `0`. This is where the scope for an answer begins and ends. 

I am all for a more rigorous test to ensure the integrity of the answer though. 

This is still early on in curriculum, all we are doing is demonstrating the different operators available in the JavaScript syntax. In my opinion, there is no requirement to go too deep in this challenge.

**Comment by JoolsMcFly** [comment]
OK, sounds good. I'll update so they can only change `0` to `33`.

**Comment by JoolsMcFly** [comment]
Done deal! You can review one more time.

Thanks.

**Comment by dhcodes** [comment]
@JoolsMcFly only issue now is the test doesn't match what is being tested. While I don't love it, I think we should change "Only change the first line" to "Change `0` to `33`" as it more accurately reflects the test.

**Comment by JoolsMcFly** [comment]
Right, if we do that though we give away the answer. I guess it's OK since it's early in the curriculum? It also makes me question the need for testing if camper uses `-` since that's implicitly tested in my PR.

What do you think?

**Comment by dhcodes** [comment]
That's fine. That test can be removed.

**Comment by JoolsMcFly** [comment]
Done. Hopefully the last change?

Thanks.

**Comment by dhcodes** [comment]
The test still needs to have the message changed. Having thought about it, I think the message for your test should read `Only subtract one number from 45.`

**Comment by JoolsMcFly** [comment]
And.... done!

**Comment by dhcodes** [comment]
Tested locally. **LGTM**. Thanks for making all the small changes @JoolsMcFly! 👍 💎 🌮

**Comment by JoolsMcFly** [comment]
Np, thanks for sticking with me on this one.

Till next time!

**Pull request merged**
