### PR TITLE
chore: remove unused api endpoints

### PR DESCRIPTION
**Pull request by ojeytonwilliams**
- chore: remove /refetch-user-completed-challenges
- chore: remove /update-my-theme
- chore: remove /certificate/verify-can-claim-cert

Checklist:

- [x] I have read [freeCodeCamp's contribution guidelines](https://contribute.freecodecamp.org).
- [x] My pull request has a descriptive title (not a vague title like `Update index.md`)
- [x] My pull request targets the `main` branch of freeCodeCamp.
- [x] I have tested these changes either locally on my machine, or GitPod.

### CODE REVIEW

**Comment by moT01** [comment]
Quite sure I remember Mrugesh saying to keep the `/verify-can-claim-cert` endpoint. Not sure if he had a certain amount of time to keep it or the exact reasoning. I suppose it's to be on the safe side or something. There may be similar thinking on the rest of them, not sure.

**Comment by ojeytonwilliams** [comment]
@moT01 yeah it was definitely deliberate.  I assumed it was just "don't delete an api endpoint in the same deploy that removes it from the client".  @raisedadead is that right?  Can we get rid of them now?

**Comment by moT01** [comment]
> don't delete an api endpoint in the same deploy that removes it from the client
ahh, yea that makes sense

**Comment by ojeytonwilliams** [comment]
I think so, but there's no rush.

**Review by ShaunSHamilton — DISMISSED** [review]
This LGTM 👍

**Comment by nhcarrigan** [comment]
Did we confirm that `/verify-can-claim-cert` was good to remove?

**Comment by raisedadead** [comment]
I think we should make these endpoints to a no-op, deploy and then remove them altogether after a while.

**Comment by ojeytonwilliams** [comment]
> I think we should make these endpoints to a no-op

What's a no-op in this context?  If I request a non-existent route at the moment the request drops to the error handler and the browser is redirected to learn.  For example: https://api.freecodecamp.org/nothing-to-see

What behaviour do we want?

**Comment by raisedadead** [comment]
Except we are not talking about non-existent endpoints, you can leave them as is. For the endpoints you are cleaning up, please return a 200 or (better yet a 410) with some apt message of your liking.

**Review by raisedadead — APPROVED** [review]

**Review by ShaunSHamilton — APPROVED** [review]
I am happy with this 👍

**Review by moT01 — APPROVED** [review]

**Pull request merged**
