### PR TITLE
feat(Test): Cypress test suite

### PR DESCRIPTION
**Pull request by Sembauke**
Checklist:

- [x] I have read [freeCodeCamp's contribution guidelines](https://contribute.freecodecamp.org).
- [x] My pull request has a descriptive title (not a vague title like `Update index.md`)
- [x] My pull request targets the `main` branch of freeCodeCamp.
- [x] I have tested these changes either locally on my machine, or GitPod.

### CODE REVIEW

**Review by raisedadead — CHANGES_REQUESTED** [review]
What are the differences between this and the reverted PR https://github.com/freeCodeCamp/freeCodeCamp/pull/42138 

More specifically, we would have wanted to see the behaviour on the test repo first. Can you confirm that has been done already?

**Comment by Sembauke** [comment]
> What are the differences between this and the reverted PR #42138
> 
> More specifically, we would have wanted to see the behaviour on the test repo first. Can you confirm that has been done already?

Yes, this has been tested on the test repo. But the build has not been split yet.

**Comment by raisedadead** [comment]
Can you please add references to the runs, etc.?

**Comment by Sembauke** [comment]
> Can you please add references to the runs, etc.?

Nothing has been changed really, only some tests to make it faster.
Only Firefox has been annoying to work it with timing issues.

https://github.com/freeCodeCamp-dev/freeCodeCamp/tree/test-suit-cypress

**Comment by ojeytonwilliams** [comment]
Hey @Sembauke, I'm probably missing something, but all I see are a couple of merge commits.  What's changed since the last time we tried this?  Apologies if I'm not seeing the obvious!

**Comment by Sembauke** [comment]
> Hey @Sembauke, I'm probably missing something, but all I see are a couple of merge commits. What's changed since the last time we tried this? Apologies if I'm not seeing the obvious!

Hey @ojeytonwilliams,

I made the changes on the test repo, not on this repo. But those changes don't seem to work.

**Comment by raisedadead** [comment]
Could we open a fresh PR when ready instead? That way we avoid the need to keep rebasing and updating this. We really need to dial in the run times before we can attempt this again.

Thanks for your understanding.

**Comment by Sembauke** [comment]
At this time I am waiting on @ojeytonwilliams to split the build. Shouldn't I leave it open so we can merge this in one go?

**Comment by ojeytonwilliams** [comment]
@raisedadead yep, this is waiting for me to update the actions.  Until that's finished (and tested on the other repo) there's nothing to be done here.

What I think we should do is keep this PR open and then, if the action changes are enough, we can merge them and then update this.

**Comment by raisedadead** [comment]
Sure. 

The PR being open for whatever value it serves is fine. 

I just want to strongly reiterate that this is not going to be merged as long as it has not reached 100% of the expected perf requirements we have been deliberating over the several threads we have had (which are starting to get fragmented).

I will defer to the best judgment by you both on this.

**Comment by Sembauke** [comment]
Yep I have been testing since May on the test repo so that's no problem @raisedadead!

**Pull request closed without merging**
