### PR TITLE
fix(client): only debounce if multifile-editor

### PR DESCRIPTION
**Pull request by ShaunSHamilton**
Checklist:

- [x] I have read [freeCodeCamp's contribution guidelines](https://contribute.freecodecamp.org).
- [x] My pull request has a descriptive title (not a vague title like `Update index.md`)
- [x] My pull request targets the `main` branch of freeCodeCamp.
- [x] I have tested these changes either locally on my machine, or GitPod.

Closes #46231 

Maybe closes the above

### CODE REVIEW

**Comment by ShaunSHamilton** [comment]
This does not seem to make a noticeable difference. I am not sure if we want debouncing still, though?

@freeCodeCamp/dev-team Has debouncing actually improved anything? Is this part of the permanent fix?

**Comment by ojeytonwilliams** [comment]
I'd be happy to keep the debouncing in it's current form (i.e. sending immediately, but ignoring extra clicks if someone clicks rapidly).  It should take off some of the pressure if/when the apis are overloaded and it feels snappy when you're using it normally.

**Comment by ahmadabdolsaheb** [comment]
It is a good practice regardless. Although, I would rather we handle the debouncing in the epic.

**Comment by ShaunSHamilton** [comment]
@ojeytonwilliams Sure.

I would prefer to prioritise the batching feature (same files). So, I will add this to my TODOs, and circle back, once that is in.

**Pull request closed without merging**
