### PR TITLE
removed videoUrl from create-a-form-element.english.md issue #39594

### LINKED ISSUE #39594: Remove video link where the video content no longer matches the current version of the challenges
After some discussion on the forum, it was concluded the following challenges need the `videoUrl` removed from the the frontmatter of the challenge files.

* [Create a Form Element](https://github.com/freeCodeCamp/freeCodeCamp/blob/master/curriculum/challenges/english/01-responsive-web-design/basic-html-and-html5/create-a-form-element.english.md)
* [Learn about Tertiary Colors](https://github.com/freeCodeCamp/freeCodeCamp/blob/master/curriculum/challenges/english/01-responsive-web-design/applied-visual-design/learn-about-tertiary-colors.english.md)

### PR DESCRIPTION
**Pull request by AjeethT**
Checklist:

- [x] I have read [freeCodeCamp's contribution guidelines](https://contribute.freecodecamp.org).
- [x] My pull request has a descriptive title (not a vague title like `Update index.md`)
- [x] My pull request targets the `master` branch of freeCodeCamp.
- [x] All the files I changed are in the same world language, for example: only English changes, or only Chinese changes, etc.

Closes #39594

### CODE REVIEW

**Review by RandellDawson — APPROVED** [review]
LGTM

**Review by naomi-lgbt — APPROVED** [review]
LGTM! 🥳 

~~Congratulations on your first PR! As a heads up, our workflow requires at least one more approving review before merging is allowed.~~
EDIT: Randell approved while I was typing 🙂 

On another note, it is generally a good practise to [create a branch on your forked repository](https://contribute.freecodecamp.org/#/how-to-setup-freecodecamp-locally?id=making-changes-locally) and work off that branch, so your master branch remains clean.

**Comment by AjeethT** [comment]
Thank you for your support **@RandellDawson @nhcarrigan** .

**Comment by RandellDawson** [comment]
Congrats @AjeethT on your first pull request (PR)! 🎉

Thank you for your contribution to the page! 👍
We're happy to accept these changes, and look forward to future contributions. 📝

**Pull request merged**
