### PR TITLE
feat(client): use showPoints to hide points instead of mutating the points

### PR DESCRIPTION
**Pull request by Sboonny**
Checklist:

- [x] I have read and followed the [contribution guidelines](https://contribute.freecodecamp.org).
- [x] I have read and followed the [how to open a pull request guide](https://contribute.freecodecamp.org/#/how-to-open-a-pull-request).
- [x] My pull request targets the `main` branch of freeCodeCamp.
- [x] I have tested these changes either locally on my machine, or GitPod.

image

After aligning the types, and removing the mutation of point to null, we can start using `ShowPoints` as a boolean to show the element, instead of changing the value of points, which isn't what point are.

### CODE REVIEW

**Comment by Sboonny** [comment]
I am pushing this into draft, until this PR #49956 is approved

**Review by Sembauke — APPROVED** [review]

**Review by ojeytonwilliams — CHANGES_REQUESTED** [review]
I think this could use better testing.

Ideally, we want to see the actual translated text and to test both `showPoints=false` and 0, 1 and 2 points to make sure that plurals are handled correctly.

Right now they aren't. See https://www.freecodecamp.org/ojeytonwilliams which shows "701 total point".

**Comment by Sboonny** [comment]
Handling plurals correctly is a nightmare because in Arabic 2 isn't plural but a pair which is a different state of plural, and we would have to account for that as well.

I have used the text from `https://github.com/freeCodeCamp/freeCodeCamp/issues/48234`, it should be translated correctly, and it won't be grammerly wrong. here is the text `Number of points: {{count}}`

**Comment by ojeytonwilliams** [comment]
Fair point: it's probably overkill for this, but https://www.i18next.com/translation-function/plurals#languages-with-multiple-plurals exists. It talks about Arabic, so it might be useful at some point.

Anyways, back on topic: could you add a couple of simple tests for how this displays (or doesn't display) the points?

**Review by ojeytonwilliams — APPROVED** [review]

**Review by moT01 — APPROVED** [review]

**Pull request merged**
