### PR TITLE
chore(cypress): migrate to Cypress v6

### PR DESCRIPTION
**Pull request by Twaha-Rahman**
Checklist:

- [X] I have read [freeCodeCamp's contribution guidelines](https://contribute.freecodecamp.org).
- [x] My pull request has a descriptive title (not a vague title like `Update index.md`)
- [x] My pull request targets the `master` branch of freeCodeCamp.
- [x] All the files I changed are in the same world language, for example: only English changes, or only Chinese changes, etc.

Migrate from Cypress v5 to v6.

More info here -> https://docs.cypress.io/guides/references/migration-guide.html#Migrating-to-Cypress-6-0

### CODE REVIEW

**Comment by ojeytonwilliams** [comment]
Hi @Twaha-Rahman, thanks for updating this, it looks good.  I went ahead and updated the action to use `6.0.0` - unfortunately we still need to set that by hand.

**Comment by Twaha-Rahman** [comment]
So... are we ready to go here?

**Comment by ojeytonwilliams** [comment]
> So... are we ready to go here?

Yep, pretty much.  The only oddity I noticed was during the Cypress run:

```
Note: Overriding Cypress cache directory to: /home/runner/.cache/Cypress

      Previous installs of Cypress may not be found.


Cypress 5.3.0 is installed in /home/runner/.cache/Cypress/6.0.0
```

but I suspect that will resolve itself - it's probably a one-time thing.

**Review by ojeytonwilliams — APPROVED** [review]
LGTM :+1:

**Pull request merged**
