### PR TITLE
refactor: use link helper over Gatsby's Link

### PR DESCRIPTION
**Pull request by ojeytonwilliams**
Checklist:

- [x] I have read and followed the [contribution guidelines](https://contribute.freecodecamp.org).
- [x] I have read and followed the [how to open a pull request guide](https://contribute.freecodecamp.org/how-to-open-a-pull-request/).
- [x] My pull request targets the `main` branch of freeCodeCamp.
- [x] I have tested these changes either locally on my machine, or GitPod.

This makes it easier to change all links at once (e.g. for performance testing) as well as simply being more consistent.

### CODE REVIEW

**Review by huyenltnguyen — APPROVED** [review]
Not related to this PR, but I'm wondering how we want to implement the path prefix feature without Gatsby Link.

We previously got a bug in non-English /learn, in that if a link is a plain `a`, it would take the user to the English page instead of that of the selected language.

**Comment by ojeytonwilliams** [comment]
That's a very good point. We would need to render conditionally based on the language. For non-English languages we could either prefix them ourselves or continue to use Gatsby's Link.

**Comment by ojeytonwilliams** [comment]
@moT01 are any updates needed?

**Comment by moT01** [comment]
Nope, my bad. Didn't look at it close enough.

**Review by moT01 — APPROVED** [review]

**Pull request merged**
