### PR TITLE
Create "index.md"

### PR DESCRIPTION
**Pull request by tirannosario**
how to install bash on Windows 10

- [x] I have read [freeCodeCamp's contribution guidelines](https://github.com/freeCodeCamp/freeCodeCamp/blob/master/CONTRIBUTING.md).
- [x] My pull request has a descriptive title (not a vague title like `Update index.md`)
- [x] My pull request targets the `master` branch of freeCodeCamp.
- [x] None of my changes are plagiarized from another source without proper attribution.
- [x] My article does not contain shortened URLs or affiliate links.

If your pull request closes a GitHub issue, replace the XXXXX below with the issue number.

Closes #XXXXX

### CODE REVIEW

**Comment by raisedadead** [comment]
@bouncey this one will break the CI

**Comment by Bouncey** [comment]
I can't remember if I ported over the guide CI checks or if they are configured correctly with all the directory shifting. 

The CI should also have triggered for the lack of frontmatter and Title-Case folder names. I'll take a look

**Comment by nathanhannig** [comment]
@tirannosario  

You can read more about the style guide that needs to be followed for articles
https://github.com/freeCodeCamp/freeCodeCamp/blob/master/docs/how-to-work-on-guide-articles.md

You will need to make these updates.

**Comment by raisedadead** [comment]
The scripts are now behaving correctly. The failed status right now can be resolved with a rebase.

**Comment by RandellDawson** [comment]
I closed/re-opened in an attempt a rebase.

**Comment by RandellDawson** [comment]
**Thanks for this pull request (PR).**

Unfortunately, we believe the article formatting does not meet the guidelines of our [Style guide for writing articles](https://github.com/freeCodeCamp/freeCodeCamp/blob/master/docs/style-guide-for-guide-articles.md).

Also, your PR makes changes/additions which fails to meet one of the following requirements:

1. Folder names must be all lowercase.  
2. Folder names can not have spaces
3. All content must be contained in a file named index.md within a folder.
4. The article must include the `title` key in the following format as the first 3 lines of the file.
5. Contains tiny url links instead full urls.
```
---
title: Your Title
---
```

Once you have confirmed your changes meet these requirements, please submit the changes on a **new PR**.

Thank you for understanding.

**Pull request closed without merging**
