### PR TITLE
Variable Arguments (Varargs) Method

### PR DESCRIPTION
**Pull request by vaibhavs2**
if we need a method in which  number of parameters varies then use this type.

- [x] I have read [freeCodeCamp's contribution guidelines](https://github.com/freeCodeCamp/freeCodeCamp/blob/master/CONTRIBUTING.md).
- [ ] My pull request has a descriptive title (not a vague title like `Update index.md`)
- [ ] My pull request targets the `master` branch of freeCodeCamp.
- [ ] None of my changes are plagiarized from another source without proper attribution.
- [x] My article does not contain shortened URLs or affiliate links.

If your pull request closes a GitHub issue, replace the XXXXX below with the issue number.

Closes #XXXXX

### CODE REVIEW

**Comment by lynxlynxlynx** [comment]
This needs better spelling.

**Comment by vaibhavs2** [comment]
> This needs better spelling.

you mean to say better word or sentence to define them?.

**Comment by lynxlynxlynx** [comment]
Just spelling, your English is not perfect, sorry.

**Comment by vaibhavs2** [comment]
> Just spelling, your English is not perfect, sorry.

yes i know.
i am sorry too

**Pull request merged**
