### PR TITLE
Fix map list icon not toggling and Expand all button issues

### PR DESCRIPTION
**Pull request by bugron**
Fixes issues listed here:
[January 16, 2016 1:31 PM](https://gitter.im/FreeCodeCamp/HelpContributors?at=569a0df504e908d302c3d523)

### CODE REVIEW

**Comment by abhisekp** [comment]
IMHO, it will be nice to have these
- [ ] 1. Move scripts to their own place (script file)
- [ ] 2. Default expand everything so that it's easily searchable using `CTRL+F`
- [ ] 3. If all items are collapsed/expanded, then change state of the collapse/expand toggle button accordingly
- [ ] 4. Remove the "view this map in fullscreeen" button on fullscreen
- [ ] 5. Implement `localStorage` state for individual collapsing items

**Comment by bugron** [comment]
I've marked 1, 2 and 4 as completed.

**Comment by SaintPeter** [comment]
@bugron I agree, item 5 is nice to have, along with automatically expanding to the current location, but not a critical fix.

**Comment by bugron** [comment]
@SaintPeter I actually wanted to add auto-scrolling to the last completed challenge. My bad, didn't mark with `blocked` label.

**Pull request merged**
