### PR TITLE
fix(curriculum): Font Awesome icons wording update

### LINKED ISSUE #50471: Lesson: "Add Font Awesome Icons to all of our Buttons" in Front End Development Libraries Certification
### Describe the Issue

Course: Front End Development Libraries Certification
Section: Bootstrap
Lesson: Add Font Awesome Icons to all of our Buttons

The wording is as follows: "Note: The span element is an acceptable alternative to the i element for the directions below."

The word "below" is wrong. The instructions are above, not below. Switch word "below" with "above". 

### Affected Page

https://www.freecodecamp.org/learn/front-end-development-libraries/bootstrap/add-font-awesome-icons-to-all-of-our-buttons

### Your code

```



```
None/ not applicable to issue. 

### Expected behavior

N/A, not applicable to issue 

### Screenshots

Issue is found within the text of the instructions 

### System

N/a, not applicable 

### Additional context

This is only a grammatical error found in the instructions for the challenge.

### PR DESCRIPTION
**Pull request by AliMora83**
Checklist:

- [x] I have read and followed the [contribution guidelines](https://contribute.freecodecamp.org).
- [x] I have read and followed the [how to open a pull request guide](https://contribute.freecodecamp.org/#/how-to-open-a-pull-request).
- [x] My pull request targets the `main` branch of freeCodeCamp.
- [x] I have tested these changes either locally on my machine, or GitPod.

Closes #50471

**Screenshots**
- Before:
Screenshot 2023-05-24 at 01 27 25

- After:
Screenshot 2023-05-24 at 01 27 48

### CODE REVIEW

**Review by gikf — APPROVED** [review]
LGTM :+1:

**Review by naomi-lgbt — APPROVED** [review]
Okie dokie

**Comment by naomi-lgbt** [comment]
Congrats on your first pull request (PR)! 🎉

Thank you for your contribution to the page! 👍
We are happy to accept these changes and look forward to future contributions. 📝

**Comment by AliMora83** [comment]
So happy to contribute 🥳
Looking forward to an exciting year of code 🥳🥰🤩

**Pull request merged**
