### PR TITLE
minor <code> tag fixes

### PR DESCRIPTION
**Pull request by quinn-codes-synthesis**
Checklist:

- [x] I have read [freeCodeCamp's contribution guidelines](https://contribute.freecodecamp.org).
- [x] My pull request has a descriptive title (not a vague title like `Update index.md`)
- [x] My pull request targets the `master` branch of freeCodeCamp.
- [x] All the files I changed are in the same world language, for example: only English changes, or only Chinese changes, etc.

Closes #XXXXX

While studying this repo for a college course, I found a few spots where code tags were lacking. Some of these were code attributes that should have had code tags and did not, while a handful of others I added because it makes the content a tiny bit clearer/more precise.

### CODE REVIEW

**Review by ojeytonwilliams — APPROVED** [review]
LGTM :+1:

**Comment by ojeytonwilliams** [comment]
The responsive web design section is still subject to the code freeze, so we can't merge this yet.  As soon as that's over, this should be good to go.

**Review by thecodingaviator — APPROVED** [review]

**Review by Manish-Giri — APPROVED** [review]
LGTM

**Review by moT01 — APPROVED** [review]
LGTM @quinn-codes-synthesis 🎉 Congratulations on your first contribution to freeCodeCamp 🎉

**Pull request merged**
