### PR TITLE
fix(docs): fix typo by removing a duplicated word

### PR DESCRIPTION
**Pull request by kelvinsanchez15**
Checklist:

- [x] I have read [freeCodeCamp's contribution guidelines](https://contribute.freecodecamp.org).
- [x] My pull request has a descriptive title (not a vague title like `Update index.md`)
- [x] My pull request targets the `main` branch of freeCodeCamp.
- [x] All the files I changed are in the same world language, for example: only English changes, or only Chinese changes, etc.

Closes #XXXXX

### CODE REVIEW

**Review by naomi-lgbt — APPROVED** [review]
Looks good to me. Nice catch.

**Comment by RandellDawson** [comment]
@nhcarrigan Since we want to make sure the translators have there Editor settings for `HTML tag displaying` set to `Show`, don't we want to tell them if they see numbered tags, to switch their settings like the QA check does now?  I think this whole sentence should discuss changing the settings if they see numbered tags.  What do you think?

**Comment by nhcarrigan** [comment]
This whole file could use some restructuring since we're translating the client bits through Crowdin now.

**Review by raisedadead — APPROVED** [review]

**Comment by RandellDawson** [comment]
@raisedadead We really do need to have the documentation reflect how the users need to set up their Editor settings.

**Pull request merged**
