### PR TITLE
feat(curriculum): restore seed + solution to Chinese

### PR DESCRIPTION
**Pull request by ojeytonwilliams**
This PR does a fair bit, but hopefully the commits should be fairly clear.  In short, it tidies up the English challenges slightly (removing unused markers), adds `dashedName` explicitly and then adds it (and the seed and solutions) to the Chinese.

This does touch the client code, but as far as I could see, the code that was removed was not doing anything.

### CODE REVIEW

**Comment by nhcarrigan** [comment]
Making a note here so I don't lose track... Playing with this locally, it looks like the `isPrivate` boolean is present on certificate files only. 

Applying an `.xor` to the schema seems to work? `  .xor('dashedName', 'isPrivate');`

**Review by naomi-lgbt — DISMISSED** [review]
LGTM~! 🥳 

Thank you for your pull request! We look forward to additional contributions!

**Comment by RandellDawson** [comment]
@ojeytonwilliams I went through all the changes in the all the files except the English curriculum files (@nhcarrigan reviewed those). I am fine merging this PR, but wanted to note a few changes that I am not sure are necessary and a general observation about several Chinese files.

- Were the changes to the following fixture files needed? For one, the fixtures are using the old yaml challenge format  
  - `curriculum/__fixtures__/chinese/challenge-js-comments.md`
  - `curriculum/__fixtures__/chinese/challenge.md`
  - `curriculum/__fixtures__/combined-html-comments.md`

- Not that it changes the appearance, but why does the following appears in the Chinese [24-game]() challenge's description?  Why does it still have the `p` and `code` element tags in it?
```
<p>实现一个以四位数字串为参数的函数，每个数字从1──►9（含），允许重复，并返回一个算术表达式，其值为24。如果不存在这样的解，则返回“没有解决方案。“ </p><p>规则： </p>只允许以下运算符/函数：乘法，除法，加法，减法除法应使用浮点或有理算术等来保留余数。不允许从提供的数字中形成多位数字。 （所以当给出1,2,2和1时，12 + 12的答案是错误的）。给定的数字顺序不必保留。 <p>示例输入： </p>  <code>solve24("4878");</code>  <code>solve24("1234");</code>  <code>solve24("6789");</code>  <code>solve24("1127");</code>  <p>示例输出（字符串）： </p>  <code>(7-8/8)\*4</code>  <code>3\*1\*4\*2</code>  <code>(6\*8)/(9-7)</code>  <code>(1+7)\*(2+1)</code>
```

**Review by RandellDawson — APPROVED** [review]
@ojeytonwilliams I went through all the changes in the all the files except the English curriculum files (@nhcarrigan reviewed those). I am fine merging this PR, but wanted to note a few changes that I am not sure are necessary and a general observation about several Chinese files.

-  I had wondered why the changes to the following fixture files was needed? For one, the fixtures are using the old yaml challenge format.  **Update: You explained in a chat message that these changes are not currently used in tests and that you will revisit these at some point.**
    - `curriculum/__fixtures__/chinese/challenge-js-comments.md`
    - `curriculum/__fixtures__/chinese/challenge.md`
    - `curriculum/__fixtures__/combined-html-comments.md`

- Not that it changes the appearance, but why does the following appears in the Chinese [24-game]() challenge's description?  Why does it still have the `p` and `code` element tags in it?
```
<p>实现一个以四位数字串为参数的函数，每个数字从1──►9（含），允许重复，并返回一个算术表达式，其值为24。如果不存在这样的解，则返回“没有解决方案。“ </p><p>规则： </p>只允许以下运算符/函数：乘法，除法，加法，减法除法应使用浮点或有理算术等来保留余数。不允许从提供的数字中形成多位数字。 （所以当给出1,2,2和1时，12 + 12的答案是错误的）。给定的数字顺序不必保留。 <p>示例输入： </p>  <code>solve24("4878");</code>  <code>solve24("1234");</code>  <code>solve24("6789");</code>  <code>solve24("1127");</code>  <p>示例输出（字符串）： </p>  <code>(7-8/8)\*4</code>  <code>3\*1\*4\*2</code>  <code>(6\*8)/(9-7)</code>  <code>(1+7)\*(2+1)</code>
```

**Comment by RandellDawson** [comment]
@ojeytonwilliams Thanks for all the hard work you put into this PR.

**Comment by ojeytonwilliams** [comment]
The issue with the challenges like `24-game` is that the challenge was already in a pretty weird state before we converted all the challenges to GFM, see https://github.com/freeCodeCamp/freeCodeCamp/blob/dec409a4bd667e4979305cc1e86e0702bbc2c707/curriculum/challenges/chinese/10-coding-interview-prep/rosetta-code/24-game.md

I only found this issue in the rosetta-code section, so at least it's not widespread.

**Pull request merged**
