### PR TITLE
changed last test from 'JUMPED' to 'JUMPS'

### LINKED ISSUE #10365: The test case are incomplete and do not check rotation from 'F' to 'S'
#### Challenge Name

https://www.freecodecamp.com/challenges/caesars-cipher

#### Issue Description

If the solution is complete except for the logic to rotate from 'F' to 'S'  the tests will still pass.

I suggest that instead of using "GUR DHVPX OEBJA QBT WHZCRQ BIRE GUR YNML SBK." for "THE QUICK BROWN DOG JUMPED OVER THE LAZY FOX."  we can use:

"GUR DHVPX OEBJA QBT WHZCF BIRE GUR YNML SBK." for "THE QUICK BROWN DOG JUMPS OVER THE LAZY FOX."

#### Your Code

```js
 
 function rot13(str) { // LBH QVQ VG!
  var result ="";
  var lookup = {
    "A":"N",
    "B":"O",
    "C":"P",
    "D":"Q",
    "E":"R",
    "F":"N",
    "G":"T",
    "H":"U",
    "I":"V",
    "J":"W",
    "K":"X",
    "L":"Y",
    "M":"Z",
    "N":"A",
    "O":"B",
    "P":"C",
    "Q":"D",
    "R":"E",
    "S":"F",
    "T":"G",
    "U":"H",
    "V":"I",
    "W":"J",
    "X":"K",
    "Y":"L",
    "Z":"M"
  };
  for (var i=0; i<str.length;i++){
    var currentVal=str[i];
    var newVal=currentVal;
    if (lookup[currentVal]!=undefined){
      newVal=lookup[currentVal];
    }
   
    result+=newVal;
  }
  
  console.log("result: "+result);
  return result;
}

// Change the inputs below to test
rot13("SERR PBQR PNZC");
rot13("THE QUICK BROWN DOG JUMPS OVER THE LAZY FOX.");
rot13("GUR DHVPX OEBJA QBT WHZCF BIRE GUR YNML SBK.");
 
```

### PR DESCRIPTION
**Pull request by wjhurley**
#### Pre-Submission Checklist

- [x ] Your pull request targets the `staging` branch of FreeCodeCamp.
- [x ] Branch starts with either `fix/`, `feature/`, or `translate/` (e.g. `fix/signin-issue`)
- [x ] You have only one commit (if not, [squash](http://forum.freecodecamp.com/t/how-to-squash-multiple-commits-into-one-with-git/13231) them into one commit).
- [x ] All new and existing tests pass the command `npm run test-challenges`. Use `git commit --amend` to amend any fixes.
#### Type of Change

- [x ] Small bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds new functionality)
- [ ] Breaking change (fix or feature that would change existing functionality)
- [ ] Add new translation (feature adding new translations)
#### Checklist:

- [x ] Tested changes locally.
- [x ] Closes currently open issue (replace XXXX with an issue no): Closes #10365
#### Description

Changed the text on the challenge page and the assertion test per the discussion on this issue. The change alters the test from 'THE QUICK BROWN DOG JUMPED OVER THE LAZY FOX' to 'THE QUICK BROWN DOG JUMPS OVER THE LAZY FOX'.

### CODE REVIEW

**Comment by dhcodes** [comment]
@wjhurley per the conversation, this needs to be changed from:
"The quick brown dog jumped over the lazy fox."

to:

"The quick brown fox jumps over the lazy fox."

per https://en.wikipedia.org/wiki/The_quick_brown_fox_jumps_over_the_lazy_dog 

Please amend the PR to reflect this.

**Comment by wjhurley** [comment]
This is getting ridiculous. If you read the discussion, it is mentioned what the correct pangram is, but the main issue was the 'JUMPED' versus 'JUMPS' because the letter 'S' was not included in the original challenge. My pull request should not have been denied for such a silly issue. I would really like Quincy Larson to review this because I have been more than patient in trying to make my pull requests meet your guidelines and finally this pull request does and it gets denied because you can't read the discussion thoroughly.

**Comment by dhcodes** [comment]
@wjhurley I understand your frustration and I'm not trying to be obtuse. Your PR does meet all the guidelines. I am reading BKinahan's comment as pointing out that not only was the test wrong (which you corrected with this PR) but the phrase should also be changed per my comment above. I'm simply pointing out that we should kill two birds with one stone. As is, another camper will likely open an issue down the road pointing out that it's `the quick brown fox` not `the quick brown dog` and then we'll have to make a new PR for that.

**Comment by dhcodes** [comment]
Assuming you still have the branch, you can make the changes, and then do `git add .`, followed by `git commit --amend` which will open a text editor. If you're on a mac, it will be Vim so just push esc, and then type `:wq`. Finally, do `git push origin fix/caesar-cipher -f` and this PR will be updated.

**Comment by wjhurley** [comment]
Regardless of your reasoning, it still feels like you denied it for an absurd reason. If you want to deny pull requests based on "what if", then you might as well deny all of them going forward. Denying mine because someone may down the road point out that the pangram is incorrect is ridiculous.

**Comment by dhcodes** [comment]
Tested and LGTM 👍 . Thanks for contributing to FCC and sorry for the miscommunications.

**Comment by wjhurley** [comment]
Just out of curiosity, when does the change go live?

**Comment by dhcodes** [comment]
Next time they do a pull from staging. Probably within a couple weeks.

**Pull request merged**
