### PR TITLE
fix(style): changed colors for dark-mode

### PR DESCRIPTION
**Pull request by AlyChloe**
#### Pre-Submission Checklist

- [x] Your pull request targets the `staging` branch of freeCodeCamp.
- [x] Branch starts with either `fix/`, `feature/`, or `translate/` (e.g. `fix/signin-issue`)
- [x] You have only one commit (if not, [squash](http://forum.freecodecamp.org/t/how-to-squash-multiple-commits-into-one-with-git/13231) them into one commit).
- [x] All new and existing tests pass the command `npm test`. Use `git commit --amend` to amend any fixes.

#### Type of Change

- [x] Small bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds new functionality)
- [ ] Breaking change (fix or feature that would change existing functionality)
- [ ] Add new translation (feature adding new translations)

#### Checklist:

- [x] Tested changes locally.
- [x] Addressed currently open issue (replace XXXXX with an issue no in next line)

Closes https://github.com/freeCodeCamp/freeCodeCamp/issues/16243

#### Description
Tweaked CSS background colors for dark mode

### CODE REVIEW

**Comment by AlyChloe** [comment]
Looks like I don't have permission to add labels? Can someone add "work in progress" for me?

**Comment by mstellaluna** [comment]
@AlyChloe I added the in progress label as you requested :)

**Comment by AlyChloe** [comment]
@mstellaluna thank you!!

**Comment by raisedadead** [comment]
Hi @AlyChloe 

Thanks for preparing this PR.

However, there are some unwanted commits which have sneaked in here. 

1. Please squash the commits to one, so we are able to review only your changes.
2. Please rebase this branch against staging, for a cleanup `git pull --rebase upstream staging`

You can refer the workflow in how to maintain your fork section of our
[Guidelines for Contributing](https://github.com/freeCodeCamp/freeCodeCamp/blob/staging/CONTRIBUTING.md)

Hit us in the [Contributors Chat room](https://gitter.im/FreeCodeCamp/Contributors) should you need any assistance.

**Pull request closed without merging**
