### PR TITLE
feat(package): Initial Curriculum separation

### PR DESCRIPTION
**Pull request by Bouncey**
Prep for packaging curriculum for `npm`

### CODE REVIEW

**Comment by Bouncey** [comment]
The package will contain...

package

**Comment by raisedadead** [comment]
I was hoping to get these minified in the process, stripping off the newlines etc. That will reduce the sizes and increase the perfo. I am sure there is package out there that will do this?

I think we can do that by not renaming the challenges to the new location. But instead doing them on the fly. What do you think?

**Comment by Bouncey** [comment]
We could run a build step to minify the json for sure

**Comment by Bouncey** [comment]
I like the clear separation with a packages dir.

**Comment by Bouncey** [comment]
With seed files minified

package

Build step shaved almost 1MB off

**Comment by raisedadead** [comment]
The only concern to me is the file renaming. It will cause us to lose the git history / blame etc. Can we not have the renaming done only during the build step, for the purposes of publishing?

**Comment by Bouncey** [comment]
@raisedadead @QuincyLarson This will require a merge to ensure correct redirects for the `/current-challenge` api.

**Comment by raisedadead** [comment]
I know you are doing stuff both places at the moment. I'll just go ahead and merge this. It should make life easier for you. 

So you need me to publish this for you? I can share the flow with you as well. Let me know which you prefer.

**Pull request merged**
