### PR TITLE
chore(curriculum): validating buidling a piano project

### PR DESCRIPTION
**Pull request by Sboonny**
Checklist:

- [x] I have read [freeCodeCamp's contribution guidelines](https://contribute.freecodecamp.org).
- [x] My pull request has a descriptive title (not a vague title like `Update index.md`)
- [x] My pull request targets the `main` branch of freeCodeCamp.
- [x] I have tested these changes either locally on my machine, or GitPod.

Contribute to #46540

### CODE REVIEW

**Review by ShaunSHamilton — CHANGES_REQUESTED** [review]
We should allow for spaces per spec

**Review by moT01 — DISMISSED** [review]
LGTM 🎉

**Review by moT01 — APPROVED** [review]
LGTM 🎉

Want to give this another quick look @ShaunSHamilton

**Review by ShaunSHamilton — APPROVED** [review]
This LGTM 👍

**Pull request merged**
