### PR TITLE
fix(certificates): general and print styling issues

### LINKED ISSUE #36383: Certificate print styles need updating - many bugs, including missing header
# Issue Description

When printing certificates, the result is very messy. Even when enabling "print background images", the header (including the logo) doesn't appear.

The signature is enormous, and there are also other ~~smiler~~ smaller style issues (e.g. the verification URL in the footer breaks over two lines).

# Sample print results

When printed in landscape mode, broken over two pages :smile: :
certificate print landscape

When printed in portrait mode, stays on one page:
certificate print portrait

# Proposed solution

It seems that the only media query for printing is the default `print.less`, apparently generated by bootstrap. Given the importance of the certificates looking good (especially if printed by a recruiter/employer), I think it might be good to write up a print-specific CSS file for certificates or to extend the print.less stylesheet for the certificates.

### PR DESCRIPTION
**Pull request by jonathan-grah**
Closes #36383

### CODE REVIEW

**Review by ojeytonwilliams — DISMISSED** [review]
Hey @jonathan-grah, I tried printing the certificates and got:

ChromePrint

so it seems to still be too tall for A4 landscape.

**Comment by jonathan-grah** [comment]
@ojeytonwilliams, apologies - I wasn't thinking and forgot to look at how it looked with different printing margins 🤦‍♂ Should be fine now, thanks for reviewing 👍

**Comment by ojeytonwilliams** [comment]
@jonathan-grah no need to apologise!  Anyway, it still wasn't looking quite right on my machine (it was still flowing onto a second page) so I played with the css until it looked fine on Chrome and Firefox - I can't test Edge at the moment.  Firefox was a bit odd, since it didn't like the fact that everything was wrapped in a `100vh` box, for some reason.  

Let me know what you think.  Does everything seem okay?

**Comment by ojeytonwilliams** [comment]
Actually, it looks like I had non-default margins, same as you!  It's now a little on the small side, so I'll fix that in a sec.

**Comment by jonathan-grah** [comment]
### LGTM 👍

Cheers @ojeytonwilliams, I prefer it vertically centred but if there's issues on Firefox then that's no problem. I also had a styling issue with the color of fonts only on Firefox; I've fixed that too.

In regards to Edge, I couldn't get the development user to sign in. Was that the same with you?

**Review by raisedadead — COMMENTED** [review]
Please see original issue comment. As a result, while this is great work, we are unlikely to land this PR anytime soon. I highly recommend closing this and waiting until later.

**Comment by jonathan-grah** [comment]
@raisedadead, completely understand. However, do you not think it's worth merging the PR at the minute, as it doesn't really change that much, but does address this issue (I get asked about this quite a lot). It can easily be changed during the re-styling rerun, just don't see much harm in merging as is.

**Comment by ojeytonwilliams** [comment]
There are still a few outstanding problems I discovered - Firefox doesn't print all the certs on one page, Saxmono is missing and so on. 

I had a fix in the works, but am I right in thinking that problems with the display are worth fixing, but not problems with printing?

**Pull request closed without merging**
