### PR TITLE
fix(curriculum): rework Project Euler 73

### PR DESCRIPTION
**Pull request by gikf**
- Reworks challenge to use argument in function call.
- Adds more tests.
- Adds solution.
- Uses MathJax to improve look of fractions and other math notation.
- Related to #40896.

Checklist:

- [x] I have read [freeCodeCamp's contribution guidelines](https://contribute.freecodecamp.org).
- [x] My pull request has a descriptive title (not a vague title like `Update index.md`)
- [x] My pull request targets the `main` branch of freeCodeCamp.
- [x] I have tested these changes either locally on my machine, or GitPod.

### CODE REVIEW

**Review by moT01 — APPROVED** [review]
LGTM 🎉 

I added this solution to the forum guide article

**Comment by moT01** [comment]
Hey @gikf - just out of curiosity, have you been copy/pasting any of the solutions you have been adding to any of these PR's from elsewhere?

**Comment by gikf** [comment]
@moT01 I have solutions for first hundred saved from when I was solving them on fCC. If it's still working (couple of times, for some reason, they were not efficient enough anymore) I'm using it, after trying to make it more clear and readable. If challenge, to not timeout first, requires using algorithms or math beyond my comprehension, I'm basing code on the solutions made by clever people understanding it, I think I've been adding link to the original solution in comment. For example https://www.mathblog.dk/project-euler-solutions/ has such very math powered (and very efficient) solutions. But again, after trying to make it more readable rather than straight copy/paste.

**Comment by moT01** [comment]
Thanks - yea, that should be fine then 👍

**Review by scissorsneedfoodtoo — APPROVED** [review]
Tested locally and everything LGTM :+1: :+1: 

Thank you for all of your hard work on this and the other Coding Interview Prep challenges, @gikf. The descriptions look much better and more consistent with your use of MathJax. Also, thank you for adding new tests and your solutions.

I've also adapted solutions from https://www.mathblog.dk/ in the past. It shouldn't be an issue as long as we're not straight up copying them.

**Pull request merged**
