### PR TITLE
Changed very last test for the Comparisons with the Logical And Operator Challenge

### LINKED ISSUE #7353: Test check myTest(51) repeated twice
#### Browser Information
* Safari 9.0.3
* Mac OS X 10.1.3

#### Screenshot
http://cl.ly/0j151r3b0B3H

-----
Updated Description:

[Comparisons with the Logical And Operator](http://www.freecodecamp.com/challenges/comparisons-with-the-logical-and-operator) has an issue.

A test cases appears repeated. Haven't checked if these are just the messages or actually the entire test is repeated, either a case should be fixed or extra one should be removed.

Refer Screenshot below:
image

### PR DESCRIPTION
**Pull request by techtolentino**
- file touched : `basic-javascript.json`
- the last test was a repeat, of testing the number 51 and expecting No
- changed the spec to test for the number `80`, and should still return `No`

closes #7353

### CODE REVIEW

**Comment by ltegman** [comment]
:+1:

**Comment by techtolentino** [comment]
@ltegman thanks! 2 merges so far :tada:

**Comment by hgonzales76** [comment]
can you un subscribe me from all notices and email's. im getting
ridiculously a lot of emails

**Comment by techtolentino** [comment]
@hgonzales76 I think you can do that in your own Github settings... Try looking if there are any notification settings or even `unwatch` might help

**Pull request merged**
