### PR TITLE
Add docker-compose.yml file

### PR DESCRIPTION
**Pull request by alxrcs**
This might be useful for small development environments,
continuous integration and/or continuous delivery.

#### Pre-Submission Checklist
- [X] Your pull request targets the `staging` branch of FreeCodeCamp.
- [X] Branch starts with either `fix/`, `feature/`, or `translate/` (e.g. `fix/signin-issue`)
- [X] You have only one commit (if not, [squash](http://forum.freecodecamp.com/t/how-to-squash-multiple-commits-into-one-with-git/13231) them into one commit).
- [X] All new and existing tests pass the command `npm test`. Use `git commit --amend` to amend any fixes.

#### Type of Change
- [ ] Small bug fix (non-breaking change which fixes an issue)
- [X] New feature (non-breaking change which adds new functionality)
- [ ] Breaking change (fix or feature that would change existing functionality)
- [ ] Add new translation (feature adding new translations)

#### Checklist:
- [X] Tested changes locally.
- [x] Closes currently open issue (replace XXXX with an issue no): Closes #XXXX

#### Description
Just adds a docker-compose.yml file.

It allows you to quickly spin up a couple of Node and Mongo containers, 
which might be useful in several scenarios, trying out stuff from scratch
without having to deal with installing MongoDB or cleaning the DB.

It might come in handy for CI/CD testing as well.

Bootstrap with:
```
   docker-compose run --rm server npm install
   docker-compose run --rm server npm run only-once
```

Run with:
```
   docker-compose up
```

### CODE REVIEW

**Comment by raisedadead** [comment]
@alexrcto thanks for the pull request, mind sharing what will be the pre-requisites before using this setup?

**Comment by alexrcto** [comment]
@raisedadead sorry, I forgot to mention that. 

The only requirement is having Docker and docker-compose installed. There should be even no need for either nodejs or mongodb.

Docker's installation guide is available [here](https://docs.docker.com/engine/installation/). It's pretty simple to install on most platforms. Most installation bundles already include docker-compose as well.

Let me know if any issues come up.

**Comment by QuincyLarson** [comment]
@BerkeleyTrue what are your thoughts on this?

**Comment by BerkeleyTrue** [comment]
LTGM

**Comment by isaac5587** [comment]
HelloWorld!

**Comment by QuincyLarson** [comment]
@alexrcto Thanks for your contribution. :1st_place_medal:

**Pull request merged**
