### PR TITLE
fix: replace responsive web dev bitly links

### PR DESCRIPTION
**Pull request by scissorsneedfoodtoo**
Checklist:

- [x] I have read [freeCodeCamp's contribution guidelines](https://contribute.freecodecamp.org).
- [x] My pull request has a descriptive title (not a vague title like `Update index.md`)
- [x] My pull request targets the `main` branch of freeCodeCamp.
- [x] All the files I changed are in the same world language, for example: only English changes, or only Chinese changes, etc.

This PR converts all bit.ly image links in the current Responsive Web Dev challenges and project based curriculum to versions served by our CDN.

Here's a list of the URLs that are being updated:

- https://www.bit.ly/fcc-relaxing-cat --> https://cdn.freecodecamp.org/curriculum/cat-photo-app/relaxing-cat.jpg
- https://bit.ly/fcc-lasagna --> https://cdn.freecodecamp.org/curriculum/cat-photo-app/lasagna.jpg
- https://bit.ly/fcc-cats --> https://cdn.freecodecamp.org/curriculum/cat-photo-app/cats.jpg
- https://bit.ly/smallgooglelogo --> https://cdn.freecodecamp.org/curriculum/applied-visual-design/google-logo.png

This PR **SHOULD NOT BE MERGED / DEPLOYED** before https://github.com/freeCodeCamp/cdn/pull/109 is merged.

### CODE REVIEW

**Comment by scissorsneedfoodtoo** [comment]
Adding the blocked label until we decide how we'll serve static assets from AWS.

**Comment by moT01** [comment]
Was anything ever concluded on that @scissorsneedfoodtoo?

**Comment by scissorsneedfoodtoo** [comment]
Thanks for bringing this up @moT01. I forgot to mention these in our other dev meetings.

No, I don't think so. As far as I remember, the only thing we decided was that we want to remove all shortened links from the curriculum. I believe we were still trying to decide if we would use these S3 links that bit.ly was pointing to, or move everything over to the CDN repo.

**Review by raisedadead — APPROVED** [review]

**Review by moT01 — APPROVED** [review]
LGTM 🎉

**Pull request merged**
