### PR TITLE
fix: failing CI issues

### PR DESCRIPTION
**Pull request by moT01**
Checklist:

- [x] I have read [freeCodeCamp's contribution guidelines](https://contribute.freecodecamp.org).
- [x] My pull request has a descriptive title (not a vague title like `Update index.md`)
- [x] My pull request targets the `main` branch of freeCodeCamp.
- [x] I have tested these changes either locally on my machine, or GitPod.

Closes #XXXXX

### CODE REVIEW

**Review by naomi-lgbt — APPROVED** [review]

**Comment by nhcarrigan** [comment]
For lack of a better solution.

**Review by ojeytonwilliams — APPROVED** [review]
LGTM 👍

**Review by ShaunSHamilton — APPROVED** [review]
I am dev, and I approve this message.

**Review by Sembauke — APPROVED** [review]

**Comment by moT01** [comment]
👍 😄 🎉 ❤️ 🚀

**Comment by raisedadead** [comment]
Seems you all had a party without me.

**Pull request merged**
