### PR TITLE
Added new translation (Russian) and corrected existing

### PR DESCRIPTION
**Pull request by arsts**
- [x] I have read [freeCodeCamp's contribution guidelines](https://github.com/freeCodeCamp/freeCodeCamp/blob/master/CONTRIBUTING.md).
- [x] My pull request has a descriptive title (not a vague title like `Update index.md`)
- [x] My pull request targets the `master` branch of freeCodeCamp.
- [x] None of my changes are plagiarized from another source without proper attribution.
- [x] My article does not contain shortened URLs or affiliate links.

If your pull request closes a GitHub issue, replace the XXXXX below with the issue number.

Closes #XXXXX

### CODE REVIEW

**Comment by arsts** [comment]
Hello, I have a question (want coherent in translation):

Should I translate code cooments INCLUDING storenames, or it is better to leave them in ORIGIN:

ORIGIN:
```javascript
// If we execute the following line in the console:
storeNames("Mulder", "Scully", "Alex Kryceck");
// The output will be { '0': 'Mulder', '1': 'Scully', '2': 'Alex Kryceck' }
```
RUSSIAN:
```
// Если мы выполним следующую строку в консоли: 
storeNames ('Малдер', 'Скалли', 'Алекс Крайчек'); 
// Вывод будет {'0': 'Малдер', '1': 'Скалли', '2': 'Алекс Крайчек'}
```

**Comment by RandellDawson** [comment]
Very good question!  Actually, anything that represents code, should not be translated.  The comments should be translated except where there is code.  The following would be the correct way:
```
// Если мы выполним следующую строку в консоли: 
storeNames("Mulder", "Scully", "Alex Kryceck");
// Вывод будет  { '0': 'Mulder', '1': 'Scully', '2': 'Alex Kryceck' }
```
Can you update your PR title to be more descriptive?  We are currently marking titles with just "update index.md" as invalid and closing them.  I just happen to see you extra comment and removed the invalid label.

**Comment by RandellDawson** [comment]
@greggubarev Can you review this one please?

**Comment by greggubarev** [comment]
@RandellDawson yes

**Comment by greggubarev** [comment]
LGTM

**Pull request merged**
