### PR TITLE
fix(docs): Added missing word to sentence in devops.md

### PR DESCRIPTION
**Pull request by RandellDawson**
Checklist:

- [x] I have read [freeCodeCamp's contribution guidelines](https://contribute.freecodecamp.org).
- [x] My pull request has a descriptive title (not a vague title like `Update index.md`)
- [x] My pull request targets the `main` branch of freeCodeCamp.
- [x] All the files I changed are in the same world language, for example: only English changes, or only Chinese changes, etc.

@raisedadead I believe the sentence I changed was just missing the word "and"?

### CODE REVIEW

**Comment by raisedadead** [comment]
When all requirements are met, that is 2 approvals and all required checks passing, this should auto merge. Trying out the new auto merge feature.

**Review by raisedadead — APPROVED** [review]

**Comment by RandellDawson** [comment]
> When all requirements are met, that is 2 approvals and all required checks passing, this should auto merge. Trying out the new auto merge feature.

What would happen if the following happened on a PR with auto-merge on:

1. Mod 1 approves
2. Mod 2 requests changes
3. Mod 3 approves

**Comment by raisedadead** [comment]
It respects the **requirements** at all times. No second guessing on "what if...".

Two approvals (green approved) & required checks passing is all it needs.

Any deviation dues to fresh changes being pushed or holding up for reviews etc. should hold it. If I am understanding this it's supposed to reduce the time waiting for checks.

A person will have to click the merge button still. 

So, I can approve and hit merge (without waiting for a second person or checks). The next person has the ability to undo my merge if they see something out of ordinary with the "Disable auto-merge".

Ref: https://docs.github.com/en/github/collaborating-with-issues-and-pull-requests/automatically-merging-a-pull-request

**Comment by nhcarrigan** [comment]
So if I approve this, it should merge on it's own?

**Review by naomi-lgbt — APPROVED** [review]

**Comment by raisedadead** [comment]
I am interested in trying out Randy's use cases. Especially when someone has a pending change request.

**Comment by raisedadead** [comment]
> If there are two approvals and one requested change, I want to make sure the auto-merge does not just kick in.

I believe it should be the case already:

image


Note: **the merge kicks in after a user with write access has clicked the merge button.** 

The intent there is they are happy with thee merge and waiting for the requirements to complete, which is additional approvals and passing tests.

That simply means anyone with write access who comes after the first person can request for changes and the merge is held in queue, and more functionally they can undo the merge request too.

So we should be covered here.

**Pull request merged**
