### PR TITLE
updated the method to increment counter as outlined in the original post

### LINKED ISSUE #42208: Challenge implies using anti-pattern which may have unexpected results in real situations
**Affected page**
https://www.freecodecamp.org/learn/front-end-libraries/react/render-conditionally-from-props

The lines 242-246 of the [file](https://github.com/freeCodeCamp/freeCodeCamp/blob/4d024f3e4bcbb0a0016e6a6bce01619c25e54dbc/curriculum/challenges/english/03-front-end-libraries/react/render-conditionally-from-props.md#L242-L246) read:
```js
handleClick() {
  this.setState({
    counter: 0 // Change this line
  });
}
```
This implies that you can increment `counter` as follows: `counter: this.state.counter + 1`.
As already taught at this point of the curriculum, this method can result in unexpected behavior, since React may batch state updates for performance reasons.
AFAIK, the following is the correct way to handle this situation:
```js
handleClick() {
  this.setState(prevState => ({counter: prevState.counter + 1}))
}
```
**Expected behavior**
Right now, both methods of incrementing `counter` are accepted. I suggest we change the provided code and the tests so that only the second method is implied and accepted.

**System:**
 - Device: Laptop
 - OS: Ubuntu 20.4
 - Browser: Opera
 - Version: 76

### PR DESCRIPTION
**Pull request by jimmycngo**
Checklist:

- [x] I have read [freeCodeCamp's contribution guidelines](https://contribute.freecodecamp.org).
- [x] My pull request has a descriptive title (not a vague title like `Update index.md`)
- [x] My pull request targets the `main` branch of freeCodeCamp.
- [x] All the files I changed are in the same world language, for example: only English changes, or only Chinese changes, etc.

Closes #42208

I updated line 243 with the suggested code outlined in the post to get rid of unexpected results.

### CODE REVIEW

**Comment by lasjorg** [comment]
Surely part of this challenge is for the camper to write the `setState` code inside the `handleClick` method.

Also, if the tests remain as they are now and will pass no matter what pattern is used (the current or an updater function) I'm not sure what this change really does?

Do we just want to "encourage" the use of an updater function? Or should the use of an updater function be part of the requirement? If so, we have to test for an updater function, do we not?

Side note: We likely want to update the solution code to use an updater function as well.

**Comment by lasjorg** [comment]
One way we can just encourage the usage would be to have an incomplete updater function in the starting code.

```
handleClick() {
  // complete the setState updater function
  this.setState(prevState => prevState);
}
```

**Comment by suburban-daredevil** [comment]
Hello @lasjorg. As far as I know, the use of updater function in the setState method is kind of recommended when we ARE bothered about the value what the previous state is holding. If the value of the previous state is not important, we could return a new JS object with the setState method. As far as this code is concerned, the change from current setState to updater setState doesn't have an impact on the output. But state in a component ought to be the single source of truth. So the use of the updater setState method is highly recommended. Thanks!!

**Review by ShaunSHamilton — CHANGES_REQUESTED** [review]
Thank you, for taking the time to contribute.

However, as @lasjorg said, this is not the required change to close the issue, because this change causes the answer to be added to the seed code (what the Camper initially starts with). So, they would not need to do anything to pass.

---

Please add a new commit with the change to only refactor the syntax used, and not add the answer within the logic. That is, there should still be a `// Change this line` comment.

Thank you

**Comment by lasjorg** [comment]
Please also update the solution code before making a new commit. It should be using an updater function as well to be in sync with the seed code.

**Comment by jimmycngo** [comment]
Hi, sorry for the delay. I don't think I know enough to do this. Thank you for the opportunity!

**Comment by lasjorg** [comment]
@jimmycngo You can take a look at the other PR https://github.com/freeCodeCamp/freeCodeCamp/pull/42225 as to how it might be done. But if you do not feel comfortable updating this PR that's totally fine, no worries, we can go with the other PR.

Please close this PR if you do not intend to update it. Thank you, for taking the time to contribute, nonetheless.

**Pull request closed without merging**
