### PR TITLE
Map and chat buttons close their respective asides when open

### LINKED ISSUE #6797: Clicking Map button when map is active should slide map shut

### PR DESCRIPTION
**Pull request by alistermada**
The Map and Chat buttons on the nav now toggle their respective side windows open and close. 

closes #6797

### CODE REVIEW

**Comment by hallaathrad** [comment]
:+1: QAing

**Comment by alistermada** [comment]
Added `document.activeElement.blur();` to the collapse functions for the Chat and Map. I first used the id selectors when using blur, but for some reason `$('#nav-map-btn').blur()` wouldn't remove the focus on the Map button unless called twice.

**Comment by hallaathrad** [comment]
The thing as I understand it is that .blur is called when the element goes out of focus, not the other way around. i.e. blur doesn't make it go out of focus. think of it as .on('blur', handle).

**Comment by SaintPeter** [comment]
Looks good, nice fix!

**Pull request merged**
