### PR TITLE
fix(cirriculum) - remove console.log(data) from step 9 and above for the leaderboard project 

### LINKED ISSUE #52746: Building an fCC Forum Leader Board shows wrong test result output on the page.
### Describe the Issue

When putting a join method after map method - some strange output is shown in the window of the pass test result, as depicted on the screenshot attached.
Снимок экрана 2023-12-24 160118

### Affected Page

https://www.freecodecamp.org/learn/javascript-algorithms-and-data-structures-v8/learn-asynchronous-programming-by-building-an-fcc-forum-leaderboard/step-14

### Your code

```
const showLatestPosts = (data) => {
  const { topic_list, users } = data;
  const { topics } = topic_list;
  postContainer.innerHTML = topics.map((item) => {}).join('')
};


```

### Expected behavior

The result of the test must show up, but instead some object is printed out.

### Screenshots

Снимок экрана 2023-12-24 160118

### System

- Device: [e.g. iPhone 6, Laptop]
- OS: [e.g. iOS 14, Windows 10, Ubuntu 20.04]
- Browser: [e.g. Chrome, Safari]
- Version: [e.g. 22]

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by a2937**
Checklist:

- [X] I have read and followed the [contribution guidelines](https://contribute.freecodecamp.org).
- [X] I have read and followed the [how to open a pull request guide](https://contribute.freecodecamp.org/#/how-to-open-a-pull-request).
- [X] My pull request targets the `main` branch of freeCodeCamp.
- [X] I have tested these changes either locally on my machine, or GitPod.

Closes #52746

Everything seems to be in order?

### CODE REVIEW

**Comment by jdwilkin4** [comment]
It looks like you are failing one of the automated tests for detecting upcoming changes.

Looking at the error message it currently says this

 1) Check challenges
       Check challenges (english)
         learn-asynchronous-programming-by-building-an-fcc-forum-leaderboard
           Step 11
             Check tests against solutions
               Solution 1 must pass the tests:
     Check next step for solution!
Test text: <p>You should call <code>showLatestPosts()</code> at the end of your <code>try</code> block.</p>
  AssertionError: expected '<!DOCTYPE html>\n<html lang="en">\n  …' to match /\s*console\.log\(data\);?\s*showLatestPosts\(.*\);??\s*/
      at eval (eval at <anonymous> (http://127.0.0.1:8080/js/frame-runner-8a3afd40d57f4f0aee85.js:2:101998), <anonymous>:1:8)
      at HTMLDocument.<anonymous> (http://127.0.0.1:8080/js/frame-runner-8a3afd40d57f4f0aee85.js:2:101998)
      at l (http://127.0.0.1:8080/js/frame-runner-8a3afd40d57f4f0aee85.js:2:35726)
      at c (http://127.0.0.1:8080/js/frame-runner-8a3afd40d57f4f0aee85.js:2:36028)

You will want to double check that step 11's tests match up with step 12's solution.

You can check this locally by running the following command

```
 FCC_BLOCK='Learn Asynchronous Programming by Building an fCC Forum Leaderboard' pnpm run test:curriculum
```

**Comment by jdwilkin4** [comment]
Also, it looks like you are failing some of the translation automated checks.

Pulling in the latest changes from main should resolve that because that bug was fixed a few days ago.

**Comment by a2937** [comment]
All of the tests pass now.

**Review by jdwilkin4 — APPROVED** [review]

**Review by JoyShaheb — APPROVED** [review]

**Comment by JoyShaheb** [comment]
@a2937, looks good to me, the single line is omitted from relevant files and the tests are passing.

**Review by JoyShaheb — CHANGES_REQUESTED** [review]
You forgot to update the solution files at the last step at file `6465c4cb65beb801543de6e3.md`

**Review by JoyShaheb — APPROVED** [review]

**Comment by JoyShaheb** [comment]
@a2937 looks good, the single line is omitted in related files and the tests are passing as well

**Pull request merged**
