### PR TITLE
fix: update and consolidate quotes

### LINKED ISSUE #38200: Update congratulatory quotes
Refers changes from #37952

The changes from the linked PR should go into the correct file, I believe there are multiple such files.

We need to audit and combine all of them to one, and at the same time move them into the common config location.

### PR DESCRIPTION
**Pull request by rdm100**
Checklist:

- [x] I have read [freeCodeCamp's contribution guidelines](https://contribute.freecodecamp.org).
- [x] My pull request has a descriptive title (not a vague title like `Update index.md`)
- [x] My pull request targets the `master` branch of freeCodeCamp.
- [x] All the files I changed are in the same world language, for example: only English changes, or only Chinese changes, etc.

Closes #38200 

Was tested in gitpod and was working, the .json file is in the utils folder at the top level if you would like me to put it in the config folder I can change it in 2 mins. Leahlee said it was cool if I submitted the pull request because she was stuck anyway.

### CODE REVIEW

**Comment by Ieahleen** [comment]
You have not done the changes requested in #39039, the name of the new file should have been `motivationalQuotes.json`, and it seems you have various quotes duplicated.

**Comment by rdm100** [comment]
at the time there was no decided name for the file I can change that no problem and get rid of any duplicated quotes.

**Comment by Ieahleen** [comment]
it seems you have also decided to discard the call-to-arms, is it because they are not used anywhere?

**Comment by rdm100** [comment]
there was something that he told me to discard because it was not used anywhere but I do not think it was called call-to-arms I searched my project for that and it is not included anywhere where do you see it in the project?

**Comment by Ieahleen** [comment]
It's "calls-to-action" and they were in the `client/src/utils/words.json` file

**Comment by Sky020** [comment]
@rdm100 , your PR has some linting issues. The details are given in the failed build output, but it is much easier to just make sure you have your code editor set up like described here: https://contribute.freecodecamp.org/#/how-to-setup-freecodecamp-locally?id=prepare-your-local-machine

**Comment by rdm100** [comment]
@Sky020 I installed eslint on vscode not sure it changed much, but I pushed up the latest version to the repository. I reran it on gitpod and I do not see any errors. Let me know if that solve the linting issues, if not is there something I am meant to do to run eslint properly on VS code?

@leahleen I have changed the file name as requested and put it in the config folder, I was told to remove "calls-to-action" because it did not seem to be used anywhere. Unless you have found it used somewhere? 

Still checking for duplicate quotes.
I have removed the Churchill quotes as requested on another pull request.

**Comment by rdm100** [comment]
@Sky020 I think my linting test still failed. I have installed eslint on vs code, but do not see any errors there. Any ideas what is going on?

**Comment by Sky020** [comment]
> I think my linting test still failed. I have installed eslint on vs code, but do not see any errors there. Any ideas what is going on?

My understanding (someone correct me) is that the tests are only run, when a commit is made. If you are working straight through your commits (`stage -> commit -> push`), you should see the error at the `commit` stage in your bash terminal. If you are using something like VSCodes automated version control, then the message is either not produced, or is suppressed in the Git output logs.

The linting error will keep arising, unless you reformat the associated file/s.
- Open this file: `client/src/components/FourOhFour/index.js`
- Press `Ctrl + S` (assuming you have automatic formatting on file save)
- See if any formatting changes occur.
- If yes, commit those changes.

If **not**, you will need to do this manually:
- Open above mentioned file
- Type this in:
```
randomQuote:
        words.motivationalQuotes[
        Math.floor(Math.random() * words.motivationalQuotes.length)
        ] 
```
That looks weird, but that is how I am interpreting the error.

**Comment by rdm100** [comment]
@Sky020 I got eslint extension to work in vs code and it shows the error within the editor. I selected the fix suggested by the extension which is formatted similar to what you suggest.

**Comment by rdm100** [comment]
@Sky020 all checks passed so just waiting for code review :)

**Comment by raisedadead** [comment]
There is a simpler way to always ensure that your tests and linting it to the expectation:

1. Change code 
2. Commit
3. Run `npm run lint`
4. Run `npm test` 
5. If edits are required, make them and commit again (or ammend commit).
6. Push
7. Make PR.

**Comment by rdm100** [comment]
@raisedadead yeah I tried running `npm run lint` before and I get this error https://gyazo.com/12d63e0e55aa681e67637374cb48a17c so it's not working from the command line for me. I tried installing using the command line again to see if that would help but it made no difference. Any suggestions on getting lint to run via command line?

but the extension works for linting now.

**Comment by raisedadead** [comment]
> I get this error gyazo.com/12d63e0e55aa681e67637374cb48a17c so it's not working from the command line for me. I tried installing using the command line again to see if that would help but it made no difference. Any suggestions on getting lint to run via command line?

You do not have the tooling installed. 

No disrespect, but did you get a chance to go though all setup instructions? We understand it can be frustrating as a first timer, trust me I have been there. My humble advice is to read (and re-read the guidelines) and understand the significance of each step. Ask questions on why/what is being installed and for what reason 🙂 ?

**Comment by rdm100** [comment]
@raisedadead ah yeah, as I said I couldn't get it set up locally because I have windows 10 home not pro. 

I was doing my version control to github using the command line. I then started running the repository in gitpod and it worked. 

Then for some reason thought I would be able to run `npm run lint` locally via the command line, really stupid as tooling still isn't obviously set up locally, oops!

**Comment by rdm100** [comment]
Anyway works on gitpod now :)

**Comment by raisedadead** [comment]
We are unable to merge this PR as is because it was opened from your master branch. There are a ton of unwanted commits which we would have ideally squahed during the merge.

Since we can't update your master branch, we are going to have to close this. We recommed you move the changes to a non-master branch and open a fresh PR.

Details on why this is needed are available in the local setup section. It also applies if you are using GitPod.

Bottomline always branch to avoid issues like this.

**Comment by raisedadead** [comment]
Additinal reference;

image

**Comment by rdm100** [comment]
@raisedadead sorry about that. So, do I just create a new branch which I have done now and open a new pull request? 

Or do I have to also reset my master branch back to before I made any changes to it?

**Comment by Ieahleen** [comment]
You should have your master branch up to date with the origin
And do any change on branches

If you need any help I think it's best if you ask on the discord server or
gitter chat room, to keep here clean

**Comment by rdm100** [comment]
thanks I have made the new pull request.

**Pull request closed without merging**
