### PR TITLE
Fix(curriculum) accessibility issue with labels in registration form course

### LINKED ISSUE #46593: Accessibility issue with labels in Registration Form course
### Describe the Issue

There are two related issues:

- The label for the file input does not use a `for` attribute and this is causing the NVDA screen reader on Windows and ORCA screen reader on linux to not announce the label text when the user tabs to the input. I have a [codepen demo](https://codepen.io/bbsmooth/pen/WNMBjVK) to illustrate this.
- It is considered a [best practice to use a `for` attribute on a label,](https://www.w3.org/WAI/tutorials/forms/labels/) even when the input is embedded in the label itself, because some screen readers may not read the label correctly without the `for` attribute (as demonstrated in the issue above). This is also noted in [step 30 of the Accessibility Quiz course](https://www.freecodecamp.org/learn/2022/responsive-web-design/learn-accessibility-by-building-a-quiz/step-30).

All of the inputs on the form in this course are embedded in a `label` and none of the labels have a `for` attribute.

### Affected Page

All steps of the Registration Form course that have inputs embedded in labels.

### Your code

Current HTML for file input:

```
<label>Upload a profile picture: <input type="file" name="file" /></label>
```

### Expected behavior

Should be something like:

```
<label for="file-upload">Upload a profile picture: <input id="file-upload" type="file" name="file" /></label>
```

### Screenshots

_No response_

### System

- Device: Desktop
- OS: Windows 11
- Browser: Firefox
- Version: 101
- Screen Reader: NVDA
- Version: 2022.1

### Additional context

I'm only bringing this up because I thought it might be a good opportunity to teach campers that valid HTML isn't always as accessible as it could be and best practices should be followed because they help eliminate these types of edge cases.

### PR DESCRIPTION
**Pull request by JohnathanTWebster**
Checklist:

- [x] I have read [freeCodeCamp's contribution guidelines](https://contribute.freecodecamp.org).
- [x] My pull request has a descriptive title (not a vague title like `Update index.md`)
- [x] My pull request targets the `main` branch of freeCodeCamp.
- [x] I have tested these changes either locally on my machine, or GitPod.

Closes #46593

Adjusted all steps starting from when labels are first introduced to incorporate accessibility formatting.

### CODE REVIEW

**Comment by Sboonny** [comment]
hi @JohnathanTWebster, the file has been changed after you had worked on them, which lead to merge conflict

image

Clicking use the command line will open instruction of how to fix the conflict

image

If you have any questions, feel free to ask questions on the ['Contributors' category on our forum](https://forum.freecodecamp.org/c/contributors) or [the contributors chat room](https://discord.gg/PRyKn3Vbay).

**Comment by JohnathanTWebster** [comment]
Fairly confident I just removed my changes

**Comment by JohnathanTWebster** [comment]
@Sboonny I just adjusted the pull request. Sorry, It wasn't cooperating but this pull should be correct.

**Comment by Sboonny** [comment]
@JohnathanTWebster no worries, I have seen the new pull request there are issues with it, but I am rhetoric enough to describe them well. 

I have contacted another mod, and hopefully they will guide you better

**Pull request closed without merging**
