### PR TITLE
Fix the pintrest clone app

### PR DESCRIPTION
**Pull request by raisedadead**
Updates the URL to HyperDev app by @Em-Ant 

Note: the separate pull request to modify the other challenges to be made including the getting started challenge.

### CODE REVIEW

**Comment by BerkeleyTrue** [comment]
Once react is merged in we can unblock this

**Comment by BerkeleyTrue** [comment]
This will need to be rebase

**Comment by QuincyLarson** [comment]
@raisedadead I noticed you introduce HyperDev quite casually here. I don't think we should mention HyperDev at all until @Em-Ant has finished porting the existing back end challenges to it and we've updated the "get set for backend challenges" section.

**Comment by raisedadead** [comment]
Okay.. closing.. will open new one with recommended comments

**Pull request closed without merging**
