### PR TITLE
Changed test case for Waypoint: target elements by id

### PR DESCRIPTION
**Pull request by jbmartinez**
Campers can pass this waypoint without using `$('#target3')`, as commented on #1854 

jquery

### CODE REVIEW

**Comment by bugron** [comment]
@jbmartinez I've verified that your fix works. Would you mind to remove the semicolons after closing parentheses in your asserts so I can merge your PR? Thanks.

**Comment by jbmartinez** [comment]
Is it better now?

**Comment by bugron** [comment]
@jbmartinez excellent, verified and merged! Thank you for your contribution!

**Comment by jbmartinez** [comment]
I don't now, it was working fine in my local copy. Perhaps they were causing issues for some grunt task

**Comment by bugron** [comment]
@benmcmahon100 for some weird reason I was able to see that semicolons in tests. I mean this: http://prntscr.com/8dh5ip. Then I removed that semicolons and the result was: http://prntscr.com/8dh5ip and tests still work. So i decided to ask @jbmartinez to remove them (I thought it is safe to remove that semicolons, because there is not a semicolon at the end of third assert).

**Pull request merged**
