### PR TITLE
Reducer fundamentals with example

### PR DESCRIPTION
**Pull request by aniketpaul1592**
- [x] I have read [freeCodeCamp's contribution guidelines](https://github.com/freeCodeCamp/freeCodeCamp/blob/master/CONTRIBUTING.md).
- [x] My pull request has a descriptive title (not a vague title like `Update index.md`)
- [x] My pull request targets the `master` branch of freeCodeCamp.
- [x] None of my changes are plagiarized from another source without proper attribution.
- [x] My article does not contain shortened URLs or affiliate links.

If your pull request closes a GitHub issue, replace the XXXXX below with the issue number.

Closes #XXXXX

### CODE REVIEW

**Comment by RandellDawson** [comment]
Thank you for  creating this PR.  However, since it was created, the underlying document has changed.  Can you please review and resolve the current merge conflicts?  It could be the changes to the underlying document are so significant that your changes are no longer relevant.  If the latter is the case, it might be easier to just close this PR and create a new PR with any changes you still feel are important to make.

If you need any assistance or have questions about resolving the merge conflicts, please reply back or contact someone in the [Contributors Room on Gitter](https://gitter.im/FreeCodeCamp/Contributors).

Thank you.

**Comment by moT01** [comment]
This file was moved to the `redux-reducers` folder.

**Comment by RandellDawson** [comment]
@moT01 What PR move this file to the redux-reducers folder?

**Comment by moT01** [comment]
It was actually deleted and not moved in favor of the `redux-reducers` article. https://github.com/freeCodeCamp/freeCodeCamp/pull/20938

**Comment by RandellDawson** [comment]
So how best to fix the merge conflict?

**Comment by moT01** [comment]
Since the file on this PR doesn't exist anymore - and we don't need duplicate articles, I would ask the author to put any wanted changes over on the other article or close this.

**Comment by QuincyLarson** [comment]
Thanks - I'm just going to close this one since we haven't heard from the author in nearly a year.

**Pull request closed without merging**
