### PR TITLE
update(curriculum): Change advanced bash tutorial title to new title

### PR DESCRIPTION
**Pull request by moT01**
Will this create any problems with crowdin? This curriculum file exists in the other languages. I renamed the file - my understanding is that crowdin will get all the english files, create duplicates in the other languages, and translate the known strings. That process would not keep the old files in the other languages. So it should be fine.

Checklist:

- [x] I have read [freeCodeCamp's contribution guidelines](https://contribute.freecodecamp.org).
- [x] My pull request has a descriptive title (not a vague title like `Update index.md`)
- [x] My pull request targets the `main` branch of freeCodeCamp.
- [x] I have tested these changes either locally on my machine, or GitPod.

Closes #XXXXX

### CODE REVIEW

**Comment by raisedadead** [comment]
I do not think so, that said I think we would have to re-arrange the folder naming a bit. 


On a side note, I hate this:
image

I propose we move the certificates up the order with a `00-certificates`, which should allow us to add folders for these new certifications.

**Comment by ieahleen** [comment]
> I propose we move the certificates up the order with a `00-certificates`, which should allow us to add folders for these new certifications.

At that point can I suggest to rename Coding Interview Prep as `99-coding-interview-prep` so it will always be the last one as it is not a certificate by itself?

**Comment by raisedadead** [comment]
Yeah - probably. Just to add, the reorganisation bit can be a part of its own PR, not this.

**Comment by ieahleen** [comment]
@nhcarrigan I think it's worth it, with the suggestion of translating the things in crowdin in order, everything after Interview COding Prep may end be translated after it, and Interview Coding Prep is almost 50% of the curriculum by itself. Maybe not fun for the couple of languages that are already there, but it would streamline everything for the others without too much explanations of what order to do things

**Review by naomi-lgbt — APPROVED** [review]
I think this is fine to land as is, with further discussion taking place on the linked issue.

**Review by raisedadead — APPROVED** [review]

**Pull request merged**
