### PR TITLE
fix(api): reorder certificate early returns

### LINKED ISSUE #47652: Reorder showCert checks
### Describe the Issue

We want to move the `user.name` check [here](https://github.com/freeCodeCamp/freeCodeCamp/blob/main/api-server/src/server/boot/certificate.js#L396) to below the `isLocked` check right below it. See [comment](https://github.com/freeCodeCamp/freeCodeCamp/pull/45562#pullrequestreview-1123751506)

### PR DESCRIPTION
**Pull request by ShaunSHamilton**
Checklist:

- [x] I have read [freeCodeCamp's contribution guidelines](https://contribute.freecodecamp.org).
- [x] My pull request has a descriptive title (not a vague title like `Update index.md`)
- [x] My pull request targets the `main` branch of freeCodeCamp.
- [x] I have tested these changes either locally on my machine, or GitPod.

Closes #47652 

- Re-orders early returns as discussed
- Adds check for `isBanned`. _I am not sure if this was intentionally left out?_

### CODE REVIEW

**Review by Sembauke — APPROVED** [review]

**Review by moT01 — COMMENTED** [review]
I did a little digging and found where the [`isBanned` flag was added.](https://github.com/freeCodeCamp/freeCodeCamp/commit/52fd15284a58dcdc82cde326c71d301d1e72c8bf) It was back in 2016 and it says it's for if "User is banned from posting to camper news". Quite sure we didn't have /news back then, everything was on medium. My best guess is that it was for banning people from posting to that? Although, there's some code in there about "stories" that looks like it let users add stories on our domain or something - so I'm not sure. This feels very legacy and possibly can be removed.

If it was for banning people from posting to medium or this stories - or even if it's the modern news, do we want to block them from viewing certs? I feel like I would leave it out in case someone has that flag and went on to earn certs - now, all of a sudden, they can't view them. Odds are, few to no people have this flag, not sure though. Maybe @raisedadead can shed some light on what this was for.

**Review by naomi-lgbt — APPROVED** [review]
banger pr, thanks for contributing!

**Comment by naomi-lgbt** [comment]
> This feels very legacy and possibly can be removed.

Honestly, I think we might repurpose this for campers who are using inappropriate/illegal content in their projects.

**Comment by raisedadead** [comment]
I agree with @naomi-lgbt

**Pull request merged**
