### PR TITLE
Fix/#35163 broken link in seed code

### LINKED ISSUE #35163: Repetitive Link
**Describe your problem and how to reproduce it:**
If you click "Contact" on the nabar, it duplicates the current page in the smaller window.

**Add a Link to the page with the problem:**
https://learn.freecodecamp.org/responsive-web-design/applied-visual-design/lock-an-element-to-the-browser-window-with-fixed-positioning/

**Tell us about your browser and operating system:**
* Browser Name: Google Chrome
* Browser Version: 72
* Operating System: Windows 10

freecodecamp error

### PR DESCRIPTION
**Pull request by moT01**
- [x] I have read [freeCodeCamp's contribution guidelines](https://github.com/freeCodeCamp/freeCodeCamp/blob/master/CONTRIBUTING.md).
- [x] My pull request has a descriptive title (not a vague title like `Update index.md`)
- [x] My pull request targets the `master` branch of freeCodeCamp.
- [x] None of my changes are plagiarized from another source without proper attribution.
- [x] All the files I changed are in the same world language (for example: only English changes, or only Chinese changes, etc.)
- [x] My changes do not use shortened URLs or affiliate links.

Closes #35163
Two challenges in a row had this problem, this is the fix I came up with. There may be other challenges with the same issue.

### CODE REVIEW

**Comment by RandellDawson** [comment]
@moT01 Are these the only challenges which would have the problem described in #35163?

**Comment by moT01** [comment]
Not sure, I was just looking through them.

**Comment by moT01** [comment]
Looks like there's many more @RandellDawson, most of them are on forms - does what I did look like a good fix for the form action? - there's probably many ways

**Comment by RandellDawson** [comment]
@moT01 Did you mean to close this?

**Comment by moT01** [comment]
Yes, I was going to make a new PR with the rest of the challenges fixed

**Comment by RandellDawson** [comment]
Why not included them on this PR?  Just add more commits as you find them.  We can label this `blocked` and `wip` until you think you have found them all.

**Pull request closed without merging**
