### PR TITLE
Fix(tests): Typo in object tests

### LINKED ISSUE #10966: Assert tests all returning true (Staging and Curr. Exp. Branches)
For the `feature/curriculum-expansion` branch only. When this branch is running locally, the challenge tests are all passing, even when no answer / incorrect code is typed into the editor. The assert messages aren't showing on screen anymore either - it's just the green check mark. This started happening sometime after the Monday, Sept 26th merges for the branch.

Update: confirmed issue on both `feature/curriculum-expansion` and `staging` branches.

#### Browser Information

* Browser Name, Version: Both Chrome (53.0.2785.116 (64-bit)) and Firefox (49.0.1) are showing the same behavior.
* Operating System: Mac OS X 10.11.3
* Mobile, Desktop, or Tablet: Desktop

### PR DESCRIPTION
**Pull request by BerkeleyTrue**
Make sure you reset challenge to verify that tests are actually pulled from challenge instead of from code-storage
closes #10966

### CODE REVIEW

**Comment by dhcodes** [comment]
@BerkeleyTrue I'm not sure this completely fixed it. The test strings (ex. "You should declare myName with the var keyword, ending with a semicolon") now show up on first-run and if you click "Run Tests" they do not pass the first time, but then the test string disappears and if you click "Run Tests" again without changing anything, all the tests pass.

**Comment by BerkeleyTrue** [comment]
Which challenge are you talking about?

**Comment by dhcodes** [comment]
It's not a particular challenge, it's all the challenges I tried. I was just trying to communicate that the test message shows up, but then when you run tests, the string disappears and then if you click run tests again, they all pass. Maybe someone else can test to see what they experience.

**Comment by QuincyLarson** [comment]
I'm experiencing the following issue of test text disappearing:

**Pull request merged**
