### PR TITLE
made semi-colon on basic-javascript challenge optional.

### LINKED ISSUE #36463: Basic Javascript: Assignment with a Returned Value
**Describe your problem and how to reproduce it:**
Solution of
 ``` processed = processArg(7)```
fails the second test, while
```processed = processArg(7);```
passes.

The semicolon at the end should be optional. 

**Add a Link to the page with the problem:**
https://learn.freecodecamp.org/javascript-algorithms-and-data-structures/basic-javascript/assignment-with-a-returned-value/

**Tell us about your browser and operating system:**
* Browser Name:  Chrome, IE11, Edge
* Operating System: Windows 10

**If possible, add a screenshot here (you can drag and drop, png, jpg, gif, etc. in this box):**
image

### PR DESCRIPTION
**Pull request by ashr81**
- [x] I have read [freeCodeCamp's contribution guidelines](https://github.com/freeCodeCamp/freeCodeCamp/blob/master/CONTRIBUTING.md).
- [x] My pull request has a descriptive title (not a vague title like `Update index.md`)
- [x] My pull request targets the `master` branch of freeCodeCamp.
- [x] None of my changes are plagiarized from another source without proper attribution.
- [x] All the files I changed are in the same world language (for example: only English changes, or only Chinese changes, etc.)
- [x] My changes do not use shortened URLs or affiliate links.

Closes #36463

### CODE REVIEW

**Review by ojeytonwilliams — APPROVED** [review]
LGTM :+1:

**Comment by ojeytonwilliams** [comment]
Even though this is a small change, we like to have two people look anything that changes the behaviour of a challenge.  As such, I'll leave this to the next reviewer to merge.

Shouldn't be long!

**Comment by ashr81** [comment]
@ojeytonwilliams  it's great to have multiple reviews on critical part of application. I can wait until second review. No problem. 😀

**Comment by RandellDawson** [comment]
If you are going to make the semi-colon optional, we could also remove the last `\s*`.

**Comment by ashr81** [comment]
@RandellDawson  Great. I updated the pull request with shortened regex.

**Review by RandellDawson — APPROVED** [review]
LGTM

**Comment by RandellDawson** [comment]
Congrats @ashr81 on your first pull request (PR)! 🎉

Thank you for your contribution to the page! 👍
We're happy to accept these changes, and look forward to future contributions. 📝

**Pull request merged**
