### PR TITLE
Update index.md

### PR DESCRIPTION
**Pull request by Harithahhh**
- [x] I have read [freeCodeCamp's contribution guidelines](https://github.com/freeCodeCamp/freeCodeCamp/blob/master/CONTRIBUTING.md).
- [x] My pull request has a descriptive title (not a vague title like `Update index.md`)
- [x] My pull request targets the `master` branch of freeCodeCamp.
- [x] None of my changes are plagiarized from another source without proper attribution.
- [x] My article does not contain shortened URLs or affiliate links.

If your pull request closes a GitHub issue, replace the XXXXX below with the issue number.

Closes #XXXXX

### CODE REVIEW

**Comment by RandellDawson** [comment]
Closed and Reopened this PR in an attempt to attempt to break out of the Travis build pending status.

**Review by Manish-Giri — CHANGES_REQUESTED** [review]
Hi @Harithahhh 

Do you have a reference where these steps are listed and explained further in detail? If so, please add it to the "More Information" section.

**Comment by Harithahhh** [comment]
@Manish-Giri 
yes ofcourse. Thanks for the comment.

**Review by Manish-Giri — COMMENTED** [review]
Hi @Harithahhh 

Please re-open the PR when you are able to add the reference.

Happy Coding!

**Pull request closed without merging**
