### PR TITLE
feat(client): fix the position of flash message

### LINKED ISSUE #48910: Flash messages are out of view
### Describe the Issue

The flash messages are showing up out of view if you are scrolled down the page a small amount.

### Steps to Reproduce

1. Go to your settings page
2. Scroll down any amount more than about a few hundred pixels
3. Change one of the settings in a way that a flash message should appear. Change the `Night Mode` or `Campfire Mode` setting for instance.
4. You won't see the flash message
5. Scroll back to the top.
6. See the message

### Expected behavior

Messages to show no matter the scroll position.

### Screenshots

Jan-03-2023 11-04-36

### PR DESCRIPTION
**Pull request by Sboonny**
Checklist:

- [x] I have read [freeCodeCamp's contribution guidelines](https://contribute.freecodecamp.org).
- [x] My pull request has a descriptive title (not a vague title like `Update index.md`)
- [x] My pull request targets the `main` branch of freeCodeCamp.
- [x] I have tested these changes either locally on my machine, or GitPod.

Closes #48910

### CODE REVIEW

**Review by moT01 — APPROVED** [review]
Not sure if you were having issues with this @Sboonny - you mentioned something in chat about it so I was going to take a look, but it all seemed to be working so I just fixed the failing tests. Everything else LGTM 🎉

**Review by raisedadead — DISMISSED** [review]
The problem is that the header is only available in some layouts, for example, it is not present in the certification views.

This would mean some messages will not reach the audience.

**Comment by Sboonny** [comment]
> Not sure if you were having issues 

If we create a new component using redux, I think we need to restart the environment for it to render. I am assuming because starting new environment ("opening gitpod") fixed the issue.

**Comment by moT01** [comment]
Not sure if this is a great solution, but we could add the header to all the layouts and conditionally show (hide) the nav. So the nav is still hidden on the cert and other views but the flash messages still show. It doesn't feel quite right, but it's not bad.

**Comment by raisedadead** [comment]
> Not sure if this is a great solution, but we could add the header to all the layouts and conditionally show (hide) the nav.

That would be a significant UX change and need signing-off from Quincy and Ahmad. We should check with them.

**Comment by Sboonny** [comment]
Should we revert this PR https://github.com/freeCodeCamp/freeCodeCamp/pull/48861, because this is an urgent issue. I am down to open issue for this PR and the issue in the original PR, and come up with solution there.

**Comment by raisedadead** [comment]
Reverting with https://github.com/freeCodeCamp/freeCodeCamp/pull/48921

**Comment by SanjeevSingh08** [comment]
assign me this issue @Sboonny

**Review by Sembauke — APPROVED** [review]

**Pull request merged**
