### PR TITLE
fix(challenges): Fix `Ctrl + Enter` hotkey for projects

### LINKED ISSUE #16769: [Beta] "Ctrl + Enter" hotkey not working for Projects
### Issue Description
The Project sections mentioned below run tests/submit on pressing <kbd>enter</kbd> not on <kbd>ctrl + enter</kbd>:

- [ ] Front End Libraries Projects
- [ ] Data Visualization Projects
- [ ] Information Security and Quality Assurance Projects
- [ ] Coding Interview Take-home Projects

### Browser Information
* Browser Name, Version: Chrome(64.0.3282.186)
* Operating System: Windows 10 Pro 32 Bit. 
* Mobile, Desktop, or Tablet: Desktop.

### PR DESCRIPTION
**Pull request by ghost**
#### Pre-Submission Checklist

- [x] Your pull request targets the `staging` branch of freeCodeCamp.
- [x] Branch starts with either `fix/`, `feature/`, or `translate/` (e.g. `fix/signin-issue`)
- [x] You have only one commit (if not, [squash](http://forum.freecodecamp.org/t/how-to-squash-multiple-commits-into-one-with-git/13231) them into one commit).
- [ ] All new and existing tests pass the command `npm test`. Use `git commit --amend` to amend any fixes.

#### Type of Change

- [x] Small bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds new functionality)
- [ ] Breaking change (fix or feature that would change existing functionality)
- [ ] Add new translation (feature adding new translations)

#### Checklist:

- [x] Tested changes locally.
- [x] Addressed currently open issue (replace XXXXX with an issue no in next line)

Closes #16769

#### Description

- Add a `keydown` event listener to all project forms.
- Show and focus on the solution input field when the hotkey combination is detected (same behaviour as clicking on the submit button).
- Display OS-specific hotkey hint (unfortunately I have to `setState()` inside `componentDidMount()` because the `navigator` object is not available during server rendering).
- Split `Form.jsx` because ESLint complains about two class components in one file.

Changes do not affect non-project challenges. Tested in Chrome, Firefox, and Safari.

### CODE REVIEW

**Comment by leonfeng** [comment]
`npm test` failed with the following message:

```
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! freecodecamp@0.1.0 test-challenges: `babel-node seed/test-challenges.js | tap-spec`
npm ERR! Exit status 1
```

Since I didn't touch any files under `seed/`, I assumed it wasn't my fault. Let me know if it's otherwise.

**Comment by QuincyLarson** [comment]
@Bouncey Please take a look at this PR - does this code fix the issue? 

@leonfeng Not sure why you're getting an error with `npm test`

**Review by Bouncey — CHANGES_REQUESTED** [review]
Hi @leonfeng, thanks for the PR.

We would need this hot key for both the `fontEndForm` and `BackEndForm`. they can be found in `views/project/Form.jsx`

A more 'react' way of doing it is by using the `ref` API.

```jsx
<Button
  block={ true }
  bsStyle='primary'
  className='btn-big'
  onClick={ isSubmitting ? null : showProjectSubmit }

  ref={ref => { this._frontEndForm = ref; }}

  type={ isSubmitting ? 'submit' : null }
  >
    { buttonCopy } (ctrl + enter)
</Button>
```

By converting them both to classes you can add the `componentDidMount` logic you have here. 

Other points:

1. If you are adding event listeners in `componentDidMount`, be sure to remove them in `componentWillUnmount`.
1. We need to account for the `event.metaKey` which Mac users use instead of the Ctrl key.
1. Instead of simulating a click, dispatch the `submitChallenge` action directly.

Happy Coding!

**Comment by leonfeng** [comment]
@Bouncey Thank you so much for the pointers! Turns out I don't need a ref to the forms after all since I'm no longer messing with the side panel.

I discovered another form (`Back-End.jsx`) that's used in the microservice and infosec projects. Its behaviour is different from the other two forms in that the solution input is initially visible and not cleared when a new challenge arrives. I'm not sure if that's by design, so all I did was select the text in the input. This way the user can still easily paste in a new solution.

To communicate to Mac users that `Cmd + Enter` is now supported, I decided to update the submit button's label. The only way I know how is via `navigator.userAgent`, which has to be accessed after the app is finished rendering. Maybe you know a better way?

I have updated the issue description to reflect the latest code changes. Please let me know if further changes are required.

**Comment by leonfeng** [comment]
Updated all the buttons I could find to say `Cmd + Enter` for Mac users.

**Review by Bouncey — CHANGES_REQUESTED** [review]
I see we are using `isMac` in at least 6 places. Maybe we could track it in redux and then access it where we need it. this was we are not calling `setState` in many places to access essentially the same state.

**Comment by raisedadead** [comment]
Hi @leonfeng,  

Thanks a lot for the pull-request and making the changes, as you may have noticed that we are moving our learning platform to https://github.com/freeCodeCamp/learn which is an effort to break the monolith, and keep the platform fast and easy to contribute to.

The new platform is based of Gatsby and is highly performant.

A few of the issues that you have worked on and fixed are probably on the learn repo. We would request you to take a look at https://learn.freecodecamp.org and give us feedback and fix them there.

Once again thanks a lot for your efforts, and apologies for closing this. This re-architecture is inevitable.

We hope you will understand the keep sending us PRs in future. Please hit us up on the https://forum.freecodecamp.org/t/quick-update-on-beta/186418/20 or the [Contributors Chat room](https://gitter.im/FreeCodeCamp/Contributors) if you have any questions. We will be happy to answer all your queries.

Happy contributing! 

/cc @QuincyLarson @Bouncey

**Pull request closed without merging**
