### PR TITLE
fix(docs): Update challenge guide to recommend code fences

### PR DESCRIPTION
**Pull request by ojeytonwilliams**
- [x] I have read [freeCodeCamp's contribution guidelines](https://github.com/freeCodeCamp/freeCodeCamp/blob/master/CONTRIBUTING.md).
- [x] My pull request has a descriptive title (not a vague title like `Update index.md`)
- [x] My pull request targets the `master` branch of freeCodeCamp.
- [x] None of my changes are plagiarized from another source without proper attribution.
- [x] All the files I changed are in the same world language (for example: only English changes, or only Chinese changes, etc.)
- [x] My changes do not use shortened URLs or affiliate links.

Updates the docs to reflect the changes introduced by #35926.

Sorry about the noise - it's all end of line spaces getting removed. The only real change is the Writing tests section.

### CODE REVIEW

**Comment by RandellDawson** [comment]
@ojeytonwilliams See [this reply](https://github.com/freeCodeCamp/freeCodeCamp/issues/35991#issuecomment-491672848) to a user regarding updating the doc.

**Comment by ojeytonwilliams** [comment]
@RandellDawson Ooops, my mistake.  Obviously that takes precedence, so please close this if it'll be in the way.  Otherwise we can just leave it up, in case @leodaher doesn't end up having time to make their changes.

**Comment by RandellDawson** [comment]
@ojeytonwilliams If we don't see a PR in the next week, then I will just merge this one and let the user know that another PR was created already.  Thanks for understanding.

**Review by thecodingaviator — APPROVED** [review]
LGTM. As Randell said, we'll wait and if we receive no PR, we can have this merged

**Comment by ojeytonwilliams** [comment]
Closing this in favour of #36069

**Pull request closed without merging**
