### PR TITLE
Resolve react-hot-loader error

### PR DESCRIPTION
**Pull request by systimotic**
#### Pre-Submission Checklist

- [x] Your pull request targets the `staging` branch of FreeCodeCamp.
- [x] Branch starts with either `fix/`, `feature/`, or `translate/` (e.g. `fix/signin-issue`)
- [x] You have only one commit (if not, [squash](http://forum.freecodecamp.com/t/how-to-squash-multiple-commits-into-one-with-git/13231) them into one commit).
- [x] All new and existing tests pass the command `npm test`. Use `git commit --amend` to amend any fixes.

#### Type of Change

- [x] Small bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds new functionality)
- [ ] Breaking change (fix or feature that would change existing functionality)
- [ ] Add new translation (feature adding new translations)

#### Checklist:

- [x] Tested changes locally.
- [ ] Closes currently open issue (replace XXXX with an issue no): Closes #XXXX

#### Description

@cmal faced some errors running Free Code Camp, as he shared in [this Gitter message](https://gitter.im/FreeCodeCamp/Contributors?at=582f95d4e712c9a11884ec9c). Today (in my timezone, this is technically the same day 😄), I was installing Free Code Camp with @tearingItUp786, and we faced the same errors. As it now was obvious to me this was definitely not an environment issue or user error, I decided to investigate.
This error prevents all Javascript from loading, which makes it impossible to test out anything you develop.
With the help of @cmal, I found that the cause was in react-hot-loader, and the way it interacts with React. The most recent version of React is `15.4.0`, which is allowed by our package.json (`^15.0.2` takes the most recent `15.x.x`). That had a change that made it incompatible with react-hot-loader version `1.x.x`, which is what we're using.
This change was very recent, and according to Google, more people have struggled with this starting about three days ago.
This is fixed in react-hot-loader v3, but that's still in beta. According to the creator however, it's more stable ([source](https://github.com/gaearon/react-hot-loader/issues/417#issuecomment-260995694)). I decided to try to upgrade to this version and see if things would work. It seems like it does!
I'm not familiar with how the hot reloading used to work. With the current state of things, it's hard for me to find out. From what I can tell, it seems to work as it should, but a thorough test by someone who really knows how this is supposed to work would be much appreciated.
I'm not a fan of using a beta version, but as it's more stable according to the creator, and because currently it just doesn't work completely, I believe that this is the best solution.

I view this bug as quite high priority, as any new contributors can currently not get started.

### CODE REVIEW

**Review by ghost — APPROVED** [review]
### LGTM 👍

**Comment by BerkeleyTrue** [comment]
@systimotic A better option for now is to per React to a lower version until RHL comes out of beta (I bet this fiasco will push it through). RHL may be "stable" according to the author, but if that where true it would not be in beta.

**Comment by systimotic** [comment]
@BerkeleyTrue Got it. The same thought you shouldn't do that, but for the short term it's probably a better solution. Expect an update in half an hour.

**Comment by systimotic** [comment]
As I should've expected, this took longer than expected. Downgrading React caused some issues with peer dependencies. One of them was in react-dom, I managed to fix that one by downgrading that as well. There are two more which I can't manage to fix. They're react-addons-css-transition-group and react-addon-shallow-compare, dependencies of react-css-transition-replace and @BerkeleyTrue's redux-epic respectively. I have not been able to fix these issues. Any suggestions would be appreciated.
I think we could either go with what's currently on this PR, or try [the patch suggested here](https://github.com/gaearon/react-hot-loader/issues/417#issuecomment-261548082).

**Comment by cmal** [comment]
This should close #11675 .

**Comment by BerkeleyTrue** [comment]
@systimotic How are you changing it? There shouldn't be any issue's with pegging React to the previous version.

**Comment by systimotic** [comment]
Currently, the version in the package.json is set to `^15.0.2`. That install `15.4.0`. I changed it to `~15.0.2` which installs `15.0.2`. I get three errors from `UNMET PEER DEPENDENCIES`, from the packages mentioned above. `react-dom` seems to line up versions with react, so I changed the version to match React. I wasn't able to fix the other two as they aren't direct dependencies. 
I might be doing something wrong here. I'm new to React, so if I need to do anything you normally don't have to do with npm packages, I have certainly missed that. Any advice is more than welcome @BerkeleyTrue.

**Comment by BerkeleyTrue** [comment]
Try pegging it to the previous version of React prior to this one

**Comment by systimotic** [comment]
```
npm WARN react-addons-css-transition-group@15.4.0 requires a peer of react@^15.4.0 but none was installed.
npm WARN react-addons-shallow-compare@15.4.0 requires a peer of react@^15.4.0 but none was installed.
```
This results in the same error. 😕 I guess I must be doing something wrong, but I can't figure out for the live of me what that is. Everything but these addons is completely fine with this version. The package.json of redux-epic asks for `^15.0.2`. I'm unaware of how peer dependencies work.

**Comment by BerkeleyTrue** [comment]
@systimotic You are close. Both of those packages are actually auto-generated from the react repo. You will need to peg those as well, just like react and react-dom.

**Comment by systimotic** [comment]
@BerkeleyTrue How would I go about doing that, as they're not direct dependencies?

**Comment by Bouncey** [comment]
@systimotic `npm install` the unmet peer dependencies at the same time

```sh
npm install react@15.3.2 <dependency1>@15.3.2 <dependency2>@15.3.2
```

**Comment by Bouncey** [comment]
did you get this figured out @systimotic ?

**Comment by systimotic** [comment]
Ugh, sorry, no. My ~explode has been heading~ head has been exploding for some reason for the last two weeks, and I can't quite figure out why. 💥
I think some other issue came up that prevents me from running gulp succesfully now, probably just my laptop freaking out. I can't test it out anymore. I'll have to work on attempting to fix that, but the error message isn't very helpful. _To be honest, a restart will probably do the trick, but I haven't had the time to do that yet 😄😢_
As for your suggestion, it did seem to install the proper versions! The question now is how to save that, as they are sub-dependencies and not installed directly from our package.json. Will adding them to our package.json overwrite the other versions? Is that good practice? 😕

**Comment by systimotic** [comment]
Again, sorry for the delay 😞 
With Stuarts help here and on Gitter, this is what I have now.
How's this @BerkeleyTrue?

**Comment by BerkeleyTrue** [comment]
Code LGTM

**Comment by Bouncey** [comment]
Tested :+1: 

Thanks for contributing :tada:

**Pull request merged**
