### PR TITLE
fix(curriculum): Changed "statement" to "expression"

### PR DESCRIPTION
**Pull request by AleksaStevic**
The ternary operator doesn't allow statements, just expressions. I don't know if this is an actual issue per see because this challenge is a beginner level. Maybe it's not necessary to be 100% precise. This is my first time contributing to open source. I apologize if I didn't do something right.

Checklist:

- [x] I have read [freeCodeCamp's contribution guidelines](https://contribute.freecodecamp.org).
- [x] My pull request has a descriptive title (not a vague title like `Update index.md`)
- [x] My pull request targets the `master` branch of freeCodeCamp.
- [x] All the files I changed are in the same world language, for example: only English changes, or only Chinese changes, etc.

Closes #XXXXX

### CODE REVIEW

**Comment by Sky020** [comment]
Hello there,

It is excellent you want to help make the freeCodeCamp content better.

Just to give my understanding: I do not think this should be changed because:
```
const myVariable = isMaybeTrue ? thisValue : anotherValue;
```
In the above, here is the rundown:
- This is an expression: `isMaybeTrue ? thisValue : anotherValue;`
- This is a statement: `const myVariable = isMaybeTrue ? thisValue : anotherValue;`
- This is also a statement: `const myVariable = thisValue;`
- This is also a statement: `const myVariable = anotherValue;`

So, with this PRs change, it suggests `thisValue` and `anotherValue` are _expressions_, when the whole _ternary expression_ (for lack of a better word) is the expression. Simply, an expression needs to be evaluated; a statement just is.

I will leave this for another contributor to comment.

**Comment by AleksaStevic** [comment]
Hi,

To be honest, I don't quite understand what you are saying.

In your example: 
```
const myVariable = isMaybeTrue ? thisValue : anotherValue;
```

`thisValue` and `anotherValue` can't be statements because the result of the whole ternary expression is either the result of `thisValue` or the result of `anotherValue`. As you said, the statement doesn't have a value.

I have a friend who is currently learning to code. I remember, when he was a complete beginner, he thought that he can write this:
```
isMaybeTrue ? (return 2) : (return 3);
```
It's wrong because `return value;` is a statement. Many beginners think that the ternary expression is just a fancy substitution for the if statement, but they are not the same. One difference is that ternary expression doesn't allow statements, but `if statement` allows statements inside.

**Comment by Sky020** [comment]
Fair enough.

I suppose, I would just say:
Here is the statement - `const myVariable = isMaybeTrue ? thisValue : anotherValue;`
Here is the expression - `isMaybeTrue ? thisValue : anotherValue`
`thisValue` could be an expression - `isMaybeTrue ? (anotherCondition ? someValue : null) : anotherValue`
**Or**, `thisValue` could be neither (instead, an object).

So, you are correct in saying `thisValue` cannot be a statement. However, I would not call it an expression (in the lesson's example) 😃

**Comment by ojeytonwilliams** [comment]
I think the idea is that statements include expressions as a subset.  Expressions being statements that return values.  The ternary operator is an expression (it returns a value) that expects three expressions as arguments.

Unless I'm missing something @AleksaStevic is right.

> thisValue could be neither (instead, an object).

Yeah, but object literals are expressions: they return objects.

For example:

```js
var obj = {an: 'object'} ? {an: 'object'} : {another: 'object'} 
```

Each literal returns an object and `obj` ends up as `{an: 'object'}`

**Comment by Sky020** [comment]
Then, to avoid bikeshedding, would you take this change, @ojeytonwilliams ?

**Review by thecodingaviator — APPROVED** [review]

**Comment by thecodingaviator** [comment]
> Hello there,
> 
> It is excellent you want to help make the freeCodeCamp content better.
> 
> Just to give my understanding: I do not think this should be changed because:
> 
> ```
> const myVariable = isMaybeTrue ? thisValue : anotherValue;
> ```
> 
> In the above, here is the rundown:
> 
> * This is an expression: `isMaybeTrue ? thisValue : anotherValue;`
> * This is a statement: `const myVariable = isMaybeTrue ? thisValue : anotherValue;`
> * This is also a statement: `const myVariable = thisValue;`
> * This is also a statement: `const myVariable = anotherValue;`
> 
> So, with this PRs change, it suggests `thisValue` and `anotherValue` are _expressions_, when the whole _ternary expression_ (for lack of a better word) is the expression. Simply, an expression needs to be evaluated; a statement just is.
> 
> I will leave this for another contributor to comment.

What my understanding of JS is, and it might not be the exact technical words, it is that an expression can have sub-expressions as components.

**Comment by ojeytonwilliams** [comment]
> Then, to avoid bikeshedding, would you take this change, @ojeytonwilliams ?

Yeah, I think it makes sense.  We can always revisit this, but I'm happy that this is a positive change.

**Comment by ojeytonwilliams** [comment]
@AleksaStevic Congrats on your first pull request (PR)! 🎉

Thank you for your contribution to the page! 👍
We're happy to accept these changes, and look forward to future contributions. 📝

**Pull request merged**
