### PR TITLE
chore(client): migrate-landing-components

### PR DESCRIPTION
**Pull request by Sembauke**
Checklist:

- [x] I have read [freeCodeCamp's contribution guidelines](https://contribute.freecodecamp.org).
- [x] My pull request has a descriptive title (not a vague title like `Update index.md`)
- [x] My pull request targets the `main` branch of freeCodeCamp.
- [x] I have tested these changes either locally on my machine, or GitPod.

Ref #43778

### CODE REVIEW

**Review by Nirajn2311 — DISMISSED** [review]
The component props don't follow the proper naming syntax of `<ComponentName>Props`

Source: https://contribute.freecodecamp.org/#/codebase-best-practices?id=naming-conventions

**Review by Nirajn2311 — DISMISSED** [review]

**Review by moT01 — COMMENTED** [review]
One typo? I just committed the suggestions to get the tests running.

Other than that, LGTM 🎉

**Review by moT01 — DISMISSED** [review]
No biggie @Sembauke - I don't usually commit things on other people's PR's

Assuming the tests pass, LGTM 🎉

**Review by ShaunSHamilton — CHANGES_REQUESTED** [review]
Something minor:

`pageName` is set to `'landing'` by default in both `/landing/index.js` and ``/landing/components/certifications/tsx`. So, there is never a time in the children it is `undefined`.

**Review by ShaunSHamilton — APPROVED** [review]
LGTM  👍

**Review by naomi-lgbt — APPROVED** [review]
Looks good to me!

**Comment by yashxog** [comment]
I would like to work on this.

**Pull request merged**
