### PR TITLE
feat: functional programming spreadsheet

### PR DESCRIPTION
**Pull request by SomeDer**
- [x] I have read [freeCodeCamp's contribution guidelines](https://github.com/freeCodeCamp/freeCodeCamp/blob/master/CONTRIBUTING.md).
- [x] My pull request has a descriptive title (not a vague title like `Update index.md`)
- [x] My pull request targets the `master` branch of freeCodeCamp.
- [x] None of my changes are plagiarized from another source without proper attribution.
- [x] All the files I changed are in the same world language (for example: only English changes, or only Chinese changes, etc.)
- [x] My changes do not use shortened URLs or affiliate links.

Issue: https://github.com/freeCodeCamp/CurriculumExpansion/issues/118

### CODE REVIEW

**Comment by SomeDer** [comment]
@scissorsneedfoodtoo there are some problems with this project, which was modeled after https://github.com/freeCodeCamp/freeCodeCamp/compare/master...scissorsneedfoodtoo:feat/js-rpg-game-tests.
* Replacing backticks with code tags doesn't work
* Using the user's code in the tests doesn't work
* The preview isn't showing

**Comment by ojeytonwilliams** [comment]
@SomeDer the problem with the backticks is probably related to #36879.  Long story short, you need a blank line before any markdown inside a `<section>`.  So

```html
<section>
Text with `backticks`
</section
```
won't convert the backticks into code, but
```html
<section>

Text with `backticks`

</section
```
should.

Having said all that, code tags should have worked.  Could you point me to the places they failed?

**Comment by SomeDer** [comment]
@ojeytonwilliams sorry I fixed this after https://github.com/freeCodeCamp/CurriculumExpansion/issues/118#issuecomment-536420540 but forgot to push.

Also, code tags do work but I wrote "replacing backticks with code tags" instead of "replacing code tags with backticks" by accident.

**Comment by ojeytonwilliams** [comment]
Ah!  That was a bit mysterious.  Still, if you want to use them, the above approach should work.  The section markdown after a blank line is parsed like Github flavour markdown, so blank lines are needed to start paragraphs etc.

**Comment by scissorsneedfoodtoo** [comment]
@SomeDer, thanks for you patience and for porting all of these problems over. 

Saw your earlier comment about being unable to evaluate the user's code in tests and that the preview isn't showing. This is because `challengeType` is set to 1, or a JavaScript challenge, rather than 0, an HTML/CSS challenge. I could go through and change this for each file if you don't mind me pushing to your branch.

Also, each challenge needs a solution at the bottom of the file to pass the CI tests. We just need to copy and paste the code in each challenge seed into the solution section of the file before it. Here's what the solution of the first file would look like:

image

This is something I can do if you don't mind me updating your branch.

**Comment by SomeDer** [comment]
@scissorsneedfoodtoo, thanks, I've changed the `challengeType`.

Are the solutions really necessary, given that the solution is simply the next file?
If they are, feel free to add them to my branch.

I've noticed that `step-005` doesn't work - it seems that unused anonymous functions result in syntax errors. Despite what I said in https://github.com/freeCodeCamp/CurriculumExpansion/pull/205#discussion_r316269200, it seems that these lessons need to be merged back.

**Comment by scissorsneedfoodtoo** [comment]
@SomeDer, thank you for changing all the `challengeType` flags. Sorry I didn't catch that earlier.

As far as I'm aware the solutions are necessary for now, if only to check against the tests we write for each step. Not sure if that will change in the future for the new platform. I'll go through and add them to your files later today.

**Comment by SomeDer** [comment]
@scissorsneedfoodtoo I fixed the tests, is there anything else I should do?

**Comment by scissorsneedfoodtoo** [comment]
@SomeDer, thank you for your patience. Tested locally and everything LGTM. Thank you for all of your hard work porting this project over. I'm excited for other contributors to try it out locally.

Just need to wait for approval from @raisedadead about the `isBeta` flag to ensure these challenges won't show up in the production build.

**Comment by scissorsneedfoodtoo** [comment]
@SomeDer, thank you for your patience and for all of your hard work writing these tests.

As mentioned in https://github.com/freeCodeCamp/freeCodeCamp/issues/37493#issuecomment-549369717, we'll land these ports in `production-next` for now. Hope you don't mind, but I went ahead and changed the base branch from `master` to the new `production-next` branch and resolved a minor conflict in `blockNameify.js` before merging.

**Pull request merged**
