### PR TITLE
Update informations about PropTypes lib

### PR DESCRIPTION
**Pull request by fjeansilva**
- [x] I have read [freeCodeCamp's contribution guidelines](https://github.com/freeCodeCamp/freeCodeCamp/blob/master/CONTRIBUTING.md).
- [x] My pull request has a descriptive title (not a vague title like `Update index.md`)
- [x] My pull request targets the `master` branch of freeCodeCamp.
- [x] None of my changes are plagiarized from another source without proper attribution.
- [x] My article does not contain shortened URLs or affiliate links.

### CODE REVIEW

**Comment by RandellDawson** [comment]
@fjeansilva Thank for trying to address the error CamperBot identified, but you still have not corrected the issue.  Currently the frontmatter block looks like:
```
title: Typechecking With PropTypes
localeTitle: Checagem de tipo com PropTypes

---
Checagem de tipo com PropTypes
---
```
and it should look like:
```
---
title: Typechecking With PropTypes
localeTitle: Checagem de tipo com PropTypes
---
```

**Comment by fjeansilva** [comment]
@RandellDawson Thank you for notifying.

**Comment by RandellDawson** [comment]
@fjeansilva Looks like you have resolved all the front matter issues.  Now, we just have to wait for one of our Portuguese translation reviewers to get to this PR to review the actual content.

Thanks for you quick response.

**Comment by fjeansilva** [comment]
@RandellDawson welcome.

**Comment by fabiotp91** [comment]
Thank you for your contribution to the FreeCodeCamp Portuguese Translation!

Contributions like yours make millions of users learn programming in their native language!
Hope you continue to help us with more contributions.

**Pull request merged**
