### PR TITLE
Note to tell that spaces between array name and square brackets is not allowed.

### LINKED ISSUE #10819: Valid data does not pass the test.
Challenge [Modify Array Data With Indexes](https://www.freecodecamp.com/challenges/modify-array-data-with-indexes#?solution=%2F%2F%20Example%0Avar%20ourArray%20%3D%20%5B1%2C2%2C3%5D%3B%0AourArray%5B1%5D%20%3D%203%3B%20%2F%2F%20ourArray%20now%20equals%20%5B1%2C3%2C3%5D.%0A%0A%2F%2F%20Setup%0Avar%20myArray%20%3D%20%5B1%2C2%2C3%5D%3B%0A%0A%2F%2F%20Only%20change%20code%20below%20this%20line.%0AmyArray%5B0%5D%20%3D%203%3B%0A%0A) has an issue.
User Agent is: <code>Mozilla/5.0 (Windows NT 10.0; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/53.0.2785.116 Safari/537.36</code>.
Please describe how to reproduce this issue, and include links to screenshots if possible.

My code:
```javascript
// Example
var ourArray = [1,2,3];
ourArray[1] = 3; // ourArray now equals [1,3,3].

// Setup
var myArray = [1,2,3];

// Only change code below this line.
myArray [0] = 3;


```
While `myArray [0]` is valid js syntax this code doesn't pass the tests because the test for use of brackets doesn't allow that space.

recommend /myArray\s+\[0\]\s+=.*/ as a better test that allows for the space but still doesn't allow for the reassignment of the array

### PR DESCRIPTION
**Pull request by karuppiah7890**
#### Pre-Submission Checklist

- [X] Your pull request targets the `staging` branch of FreeCodeCamp.
- [X] Branch starts with either `fix/`, `feature/`, or `translate/` (e.g. `fix/signin-issue`)
- [X] You have only one commit (if not, [squash](http://forum.freecodecamp.com/t/how-to-squash-multiple-commits-into-one-with-git/13231) them into one commit).
- [X] All new and existing tests pass the command `npm run test-challenges`. Use `git commit --amend` to amend any fixes.
#### Type of Change

- [X] Small bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds new functionality)
- [ ] Breaking change (fix or feature that would change existing functionality)
- [ ] Add new translation (feature adding new translations)
#### Checklist:

- [X] Tested changes locally.
- [X] Closes currently open issue (replace XXXX with an issue no): Closes #10819 
#### Description

Added a note to tell campers that spaces between array name and square brackets is not allowed as it is confusing to read code.

### CODE REVIEW

**Comment by karuppiah7890** [comment]
Can I know what the "QA" label means ?

**Comment by Bouncey** [comment]
@karuppiah7890

**Comment by Bouncey** [comment]
@karuppiah7890 

 QA - (Quality Assurance) A fix has been submitted and needs to be reviewed before merging.

A description of all our labels can be found [here](http://forum.freecodecamp.com/t/free-code-camp-issue-labels/19556). It's a little difficult to read, it was formatted for markdown, but our forums do not support markdown just yet.

Hope this helps

**Comment by karuppiah7890** [comment]
Thanks for the info and link! :smile:

**Comment by dhcodes** [comment]
LGTM 👍 . Thanks for contributing 🎉

**Comment by dhcodes** [comment]
@karuppiah7890 could you amend this to remove "Fix for Issue #10819" from the commit message? :)

**Comment by karuppiah7890** [comment]
@dhcodes Sorry, I didn't get you. You want me to change the commit message to "Fix for Issue #10819" ?

**Comment by dhcodes** [comment]
@karuppiah7890 No I meant that you should remove that from your commit message. Your commit message should not include the issue number. 👍

**Comment by karuppiah7890** [comment]
I think you meant change the title of my pull request ? Because my commit message just says 

" Added a note to tell campers that spaces between array name and square brackets is not allowed as it is confusing to read code."

log

**Comment by dhcodes** [comment]
@karuppiah7890 yeah, my bad. Tested and LGTM 👍 . Thanks for contributing! 🎉

**Comment by karuppiah7890** [comment]
@dhcodes Thanks for being patient while answering to my questions! And this was my first contribution to Open Source! Looking forward to contribute more to FreeCodeCamp and other Open Source Projects :smile:

**Pull request merged**
