### PR TITLE
Remove rules from projects

### LINKED ISSUE #11513: Remove rules from projects
Currently each of our project challenges has rules like these: 
```
        "<strong>Rule #1:</strong> Don't look at the example project's code. Figure it out for yourself.",
        "<strong>Rule #2:</strong> Fulfill the below <a href='https://en.wikipedia.org/wiki/User_story' target='_blank'>user stories</a>. Use whichever libraries or APIs you need. Give it your own personal style.",
        "<strong>Rule #3:</strong> You must use both Sass and React to build this project.",
```

I have already replaced all three of these rules on our curriculum expansion branch with the following line, which is the same for every single project challenge:

```
        "Fulfill the below <a href='https://en.wikipedia.org/wiki/User_story' target='_blank'>user stories</a>. Use whichever libraries or APIs you need. Give it your own personal style.",
```

Note that this means there are no "rules" in these challenge descriptions. 

For this issue, note that you should start this pull request by branching off of backup/master. 

Then go in and change these lines in the seed/challenges directory for each of the -projects.json seed files.

To be clear, yes, we are getting rid of the React/D3 requirements for the data visualization certificate. (This has been planned for a long time, and we would have done this on production a long time ago if we had realized how ambitious our  curriculum expansion effort would become.)

Then you'll need to submit two pull requests - one against backup/master and one against staging.

### PR DESCRIPTION
**Pull request by Manish-Giri**
#### Pre-Submission Checklist

- [ ] Your pull request targets the `staging` branch of FreeCodeCamp.
- [x] Branch starts with either `fix/`, `feature/`, or `translate/` (e.g. `fix/signin-issue`)
- [x] You have only one commit (if not, [squash](http://forum.freecodecamp.com/t/how-to-squash-multiple-commits-into-one-with-git/13231) them into one commit).
- [x] All new and existing tests pass the command `npm test`. Use `git commit --amend` to amend any fixes.

#### Type of Change

- [x] Small bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds new functionality)
- [ ] Breaking change (fix or feature that would change existing functionality)
- [ ] Add new translation (feature adding new translations)

#### Checklist:

- [x] Tested changes locally.
- [x] Closes currently open issue (replace XXXX with an issue no): Closes #11513 

#### Description

Removed "rules" from projects. Please review this PR.

Once this PR against `backup/master` is approved, or if the changes here look okay, I'll make a PR against `staging` next.

closes #11513

### CODE REVIEW

**Comment by Manish-Giri** [comment]
@raisedadead Please take a look when you have a moment. In addition to the `-projects.json` seed files (as mentioned in the issue), I also made similar changes to front end projects, which are in `-ziplines.json` files. Not really sure if this is okay, or not required.

**Comment by raisedadead** [comment]
#### :sparkles: :sparkles: **LGTM.** :sparkles: :sparkles: 

Thanks @Manish-Giri, and awesome work as always..!

**Comment by raisedadead** [comment]
Please open a PR against `staging` as requested, you may use the same branch. But it would be messy with so many commits that are ahead of master.

You may either rebase the branch against staging. Or you may create a fresh branch off `staging` and just add your changes.

Let us know in the chat if you need assistance.

**Comment by Manish-Giri** [comment]
@raisedadead Thanks! Glad this PR was okay, I'll begin the next one now.

**Pull request merged**
