### PR TITLE
Changed <div> to <figure> for img container element

### PR DESCRIPTION
**Pull request by kevindelsh**
Changed the container `<div>` to `<figure>` and the caption <div> to `<figcaption>`.

Wrapping images with their caption elements in `<figure>` while the caption is in `<figcaption>` is a semantically best practice.
I thought it's better to start using it from the beginning.

- [x] I have read [freeCodeCamp's contribution guidelines](https://github.com/freeCodeCamp/freeCodeCamp/blob/master/CONTRIBUTING.md).
- [x] My pull request has a descriptive title (not a vague title like `Update index.md`)
- [x] My pull request targets the `master` branch of freeCodeCamp.
- [x] None of my changes are plagiarized from another source without proper attribution.
- [x] All the files I changed are in the same world language (for example: only English changes, or only Chinese changes, etc.)
- [x] My changes do not use shortened URLs or affiliate links.

**EDIT:** See [related PR](https://github.com/freeCodeCamp/testable-projects-fcc/pull/859) on testable-projects repo.

### CODE REVIEW

**Comment by kevindelsh** [comment]
I don't know whether this change breaks the tests or not but if so, while I'm a newbie, I would be happy to assist in amending them.

**Comment by RandellDawson** [comment]
@beaucarnes What are your thoughts on this PR?

**Comment by lynxlynxlynx** [comment]
Does this not have a testable project already? If so the change needs to be done there too.

**Comment by kevindelsh** [comment]
hey @lynxlynxlynx, if there's something I can help with, point me at and I'll be happy to put the time in.

**Comment by lynxlynxlynx** [comment]
Cool, check here: https://github.com/freeCodeCamp/testable-projects-fcc/blob/master/src/project-tests/tribute-page-tests.js

**Comment by thecodingaviator** [comment]
**Mods:** Take note that any changes made under this PR's current scope would have to be made in the test repo too

**Comment by beaucarnes** [comment]
I think this PR is a good idea. We already introduce `figure` and `figcaption` in Applied Accessibility. It makes since to use them in a project.

**Comment by thecodingaviator** [comment]
@kevindelsh Would you be interested in opening a PR on freeCodeCamp/testable-projects-fcc to reflect these changes?

**Comment by kevindelsh** [comment]
hey @thecodingaviator, thank you for asking and sorry for the late reply.
I would be happy to do that.

Is it this one here that @lynxlynxlynx mentioned earlier (and I failed to respond to)?
https://github.com/freeCodeCamp/testable-projects-fcc/blob/master/src/project-tests/tribute-page-tests.js

Or are there more files that need to be edited?

**Comment by thecodingaviator** [comment]
Yes, it is the only file. Please make the required changes

**Comment by kevindelsh** [comment]
Hey @thecodingaviator, [here](https://github.com/freeCodeCamp/testable-projects-fcc/pull/859) are the requested changes:
These changes are **breaking**, as I understand (previous project for the tribute page that don't use `<figure>` and `<figcaption>` won't work anymore.

In addition, I'm still new to git and there are issues with my PR (I've made it here in the github editor). If it's not OK, I'm going to work on it tomorrow.

**Comment by thecodingaviator** [comment]
@kevindelsh Yes, those changes would be considered under breaking. MNore discussion about that on your PR

**Comment by thecodingaviator** [comment]
This PR is blocked till we receive insight from either Quincy or Peter on the linked PR since this would break all existing projects

**Comment by RandellDawson** [comment]
@raisedadead Can we get a definitive answer on whether or not to proceed with this for the current curriculum?

**Comment by thecodingaviator** [comment]
@RandellDawson we are awaiting followup from Quincy on this PR: https://github.com/freeCodeCamp/testable-projects-fcc/pull/859

**Comment by QuincyLarson** [comment]
Thanks for the discussion everyone. I enjoyed reading through it and hearing your various perspectives. In my humble opinion, we should not break the thousands of existing projects out there with passing test suites over what is (in this case literally) a semantic issue.

We would instead need to figure out a way to make existing projects backward-compatible with the newly updated test. I am closing this PR. If someone wants to open a PR with a variant of this where the test passes for both the existing projects and for future projects that will use the `<figure>` syntax, then we can evaluate that.

**Pull request closed without merging**
