### PR TITLE
Declarative/Function solution

### PR DESCRIPTION
**Pull request by stevensacks**
Includes a full explanation and helpful links to learn more.

- [x] I have read [freeCodeCamp's contribution guidelines](https://github.com/freeCodeCamp/freeCodeCamp/blob/master/CONTRIBUTING.md).
- [x] My pull request has a descriptive title (not a vague title like `Update index.md`)
- [x] My pull request targets the `master` branch of freeCodeCamp.
- [x] None of my changes are plagiarized from another source without proper attribution.
- [x] All the files I changed are in the same world language (for example: only English changes, or only Chinese changes, etc.)
- [x] My changes do not use shortened URLs or affiliate links.

### CODE REVIEW

**Comment by RandellDawson** [comment]
While I like your declarative solution, I think the line starting with:
```
Imperative code can be shorter, as evidenced by the other solutions. But, it can also be less flexible and harder to debug.
```
through the line ending with:
```
That said, you could use just our sanitize function and pass its output to one of the other solutions to make them reliable.
```
should not go in this solution as it is more describing a lesson in why to declarative programming.  There are already plenty of examples of imperative solutions, so this feel redundant.  I feel you you read through the Guide and see if you can add a lot of this discussion as to show how something written imperatively could be rewritten decoratively to avoid many of the pitfalls you describe.

**Comment by RandellDawson** [comment]
@stevensacks Can you please see my last comment regarding changes requested?

Thank you.

**Comment by stevensacks** [comment]
I believe that my imperative solution makes it clear how the declarative solution could be written inline top to bottom using the same code. Doing so helps people who are new to declarative programming connect the dots, so to speak. At the very least, the imperative solution is a stepping stone towards a declarative way of thinking about code and the contrast can be helpful. My imperative solution isn't like any of the other imperative solutions, and I'm not suggesting that my imperative solution is the correct solution, just that it's another perhaps more familiar way of looking at the same code.

**Comment by Manish-Giri** [comment]
The proposed changes are more suited for a new lesson on "Declarative vs Imperative" style of programming. With some tweaks, you could very well create a new challenge out of the code in this PR - one that explains the differences between the imperative vs declarative approach (with code samples), and then have the camper convert a simple imperative solution to a declarative one. The "Functional Programming" section sounds like a good place for this new challenge.

As for this particular PR, the Missing Letters challenge already has too many solutions in the guide. Ideally, your proposed code would go under the advanced section, which already has a "Simplified Advanced Code Solution" and an "Advanced Code Solution", along with a basic and an intermediate solution. I don't think this challenge needs 5 solutions.

**Comment by RandellDawson** [comment]
@stevensacks We have decided to close this PR based on the feedback you have been given.  

Please feel free to create a new challenge on "Declarative vs. Imperative" style of programming.  This would be very useful.  See @Manish-Giri's last comment for more information.

**Pull request closed without merging**
