### PR TITLE
add text "7. Resolution" to article

### PR DESCRIPTION
**Pull request by at1faulkner**
- [x ] I have read [freeCodeCamp's contribution guidelines](https://github.com/freeCodeCamp/freeCodeCamp/blob/master/CONTRIBUTING.md).
- [x ] My pull request has a descriptive title (not a vague title like `Update index.md`)
- [x ] My pull request targets the `master` branch of freeCodeCamp.
- [x ] None of my changes are plagiarized from another source without proper attribution.
- [x ] My article does not contain shortened URLs or affiliate links.

If your pull request closes a GitHub issue, replace the XXXXX below with the issue number.

Closes #XXXXX

### CODE REVIEW

**Comment by huyenltnguyen** [comment]
Hey @at1faulkner 

You haven't actually added any content so I will be invalid pull requests this PR and marking it as `invalid`. 😓️

Feel free to open another PR though! 👍

**Comment by Manish-Giri** [comment]
@huyenltnguyen Just curious, but OP did add content to the PR. I did go through this one but left it for someone who is familiar with the Agile process.

**Comment by huyenltnguyen** [comment]
@Manish-Giri Thank you for the second review!

@at1faulkner I apologize for the confusion. It was my mistake. I didn't mean to QA your PR as I'm not familiar with Agile either. My earlier comment was incorrect. I have re-opened your PR and removed the invalid label. I hope your PR will get reviewed soon. Sorry again.

**Comment by cmccormack** [comment]
I couldn't find Resolution as a 7th method on any article I read, and the PR also messes up the existing image, I would recommend closing this and asking the submitter to provide a source and proper formatting in a new PR.

**Comment by huyenltnguyen** [comment]
Hi @at1faulkner, thank you for the PR! The list in the article seems to be from this link: https://en.wikiversity.org/wiki/Crystal_Methods. There is no `Resolution` in the link and we could not find the source for that.

I'm going to close your PR, but feel free to open a new one with @cmccormack's suggestions:
- State the source of your addition
- Follow the [Style Guide](https://github.com/freeCodeCamp/freeCodeCamp/blob/master/docs/style-guide-for-guide-articles.md) and be sure to preview your changes before you submit.

Thank you and sincerely apologize for all the confusion.
Happy coding!

---
@Manish-Giri @cmccormack Thank you! I really appreciate your input!

**Pull request closed without merging**
