### PR TITLE
Changed 'before' to 'after' to reflect the intended image insertion p…

### PR DESCRIPTION
**Pull request by dennis-wolfers**
…oint in the code

- [x] I have read [freeCodeCamp's contribution guidelines](https://github.com/freeCodeCamp/freeCodeCamp/blob/master/CONTRIBUTING.md).
- [x] My pull request has a descriptive title (not a vague title like `Update index.md`)
- [x] My pull request targets the `master` branch of freeCodeCamp.
- [x] None of my changes are plagiarized from another source without proper attribution.
- [x] My article does not contain shortened URLs or affiliate links.

If your pull request closes a GitHub issue, replace the XXXXX below with the issue number.

Closes #XXXXX

### CODE REVIEW

**Comment by lynxlynxlynx** [comment]
How did you determine the intended place? The tests don't care.

**Comment by dennis-wolfers** [comment]
The exercises are building up a web page step-by-step. In the following step, the image is clearly below the h2. Also, space has been left between the main tag and the first p tag, so that's the intuitively obvious place to add the image. In fact, the instruction should probably read "Insert an img tag, below the main element."

**Comment by dennis-wolfers** [comment]
I made the change mentioned in my last comment, and pushed it up to GitHub.

**Comment by lynxlynxlynx** [comment]
LGTM
https://learn.freecodecamp.org/responsive-web-design/basic-html-and-html5/add-images-to-your-website/

**Comment by dennis-wolfers** [comment]
Sorry, I'm new to this process. What is the purpose of your last comment?

**Comment by lynxlynxlynx** [comment]
LGTM is short for looks good to me. I'm helping with the review process in this flood and a common search keyword is extra helpful this time.

**Pull request merged**
