### PR TITLE
chore: migrate Intro, Solution viewer and landing to TS

### PR DESCRIPTION
**Pull request by RobertoMSousa**
Checklist:

- [x] I have read [freeCodeCamp's contribution guidelines](https://contribute.freecodecamp.org).
- [x] My pull request has a descriptive title (not a vague title like `Update index.md`)
- [x] My pull request targets the `main` branch of freeCodeCamp.
- [x] I have tested these changes either locally on my machine, or GitPod.

Closes #XXXXX

This PR comes out of the request on this thread that intends to migrate all the FE components to TS. Changed only a couple of components to prevent overlapping with already exiting migration.

### CODE REVIEW

**Comment by ieahleen** [comment]
Hey @username

We would love to be able to merge your changes but it looks like there is an error with the CI build. ⚠️

Once you resolve these issues, we will be able to review your PR and merge it. 😊

---

Feel free to reference the [contributing guidelines](https://contribute.freecodecamp.org/#/how-to-work-on-coding-challenges?id=testing-challenges) for instructions on running the CI build locally. ✅

**Comment by RobertoMSousa** [comment]
> We would love to be able to merge your changes but it looks like there is an error with the CI build. ⚠️
> 
> Once you resolve these issues, we will be able to review your PR and merge it. 😊
> 
> Feel free to reference the [contributing guidelines](https://contribute.freecodecamp.org/#/how-to-work-on-coding-challenges?id=testing-challenges) for instructions on running the CI build locally. ✅

@ieahleen  Sorry but I forgot to push that yesterday 😓

**Comment by RobertoMSousa** [comment]
Yeah. I did that one before checking the migration pipeline 😅 
This one is not the case but some assignments were done several months ago with no progress, what about those?

**Comment by ShaunSHamilton** [comment]
> This one is not the case but some assignments were done several months ago with no progress, what about those?

We will be updating the original post of the issue, as well as adding a new comment describing the expected contribution flow for remaining files. I suggest keeping an eye out for updates to the original issue, because we will just internally clarify what we want, before doing so, and I do not know when that might happen.

Thank you, for your patience.

**Pull request closed without merging**
