### PR TITLE
fix: campfire volume slider colors

### LINKED ISSUE #52730: Campfire volume slider should support dark theme
### Describe the Issue

The campfire volume slider is hard to see in dark theme.

| Light | Dark |
| --- | --- |
| Screenshot 2023-12-23 at 17 22 58 | Screenshot 2023-12-23 at 17 20 53 |

This doesn't seem to be a regression, but we just haven't supported dark theme. Original implementation: https://github.com/freeCodeCamp/freeCodeCamp/pull/47259/files.

### Affected Page

https://www.freecodecamp.org/settings

### Steps to Reproduce

1. Go to https://www.freecodecamp.org/settings
2. Scroll down and find the Campfire Volume setting

### PR DESCRIPTION
**Pull request by Sembauke**
Checklist:

- [x] I have read and followed the [contribution guidelines](https://contribute.freecodecamp.org).
- [x] I have read and followed the [how to open a pull request guide](https://contribute.freecodecamp.org/#/how-to-open-a-pull-request).
- [x] My pull request targets the `main` branch of freeCodeCamp.
- [x] I have tested these changes either locally on my machine, or GitPod.

image

image

Closes #52730

### CODE REVIEW

**Review by moT01 — COMMENTED** [review]
Here's what I'm seeing:

Chrome 119.0.6045.159 & Safari 17.2.1 :
| Light | Dark |
| --- | --- |
| Screenshot 2024-02-16 at 10 59 55 AM | Screenshot 2024-02-16 at 10 59 47 AM |

This looks good enough I think, but it could probably be a little better. They only have the border on the left, which makes it feel a little weird - and you can't really see it in light mode.

It's a little different on firefox 122.0.1:

| Light | Dark |
| --- | --- |
| Screenshot 2024-02-16 at 10 54 07 AM | Screenshot 2024-02-16 at 10 54 12 AM |

The dark mode is pretty good cause it has the bright borders. Although, the adjuster could maybe be a different color. Light mode is pretty rough - I can't see the borders.

**Review by huyenltnguyen — COMMENTED** [review]
With the suggested changes, the slider would look as follows:

| Browser | Dark | Light |
| --- | --- | --- |
| Firefox | Screenshot 2024-02-16 at 23 40 35 | Screenshot 2024-02-16 at 23 40 26 |
| Chrome | Screenshot 2024-02-16 at 23 41 22 | Screenshot 2024-02-16 at 23 41 14 |
| Safari | Screenshot 2024-02-16 at 23 41 22 | Screenshot 2024-02-16 at 23 42 13 |

---

An option I'm experimenting with is using the primary color for the left side and secondary color for the right side. The rationale is that we use `gray-85` (on light theme) and `gray-05` (on dark theme) to reflect the main/selected values or options, and the use of these colors would match the rest of the page.

Here is the rough visual (I'm still playing around with the color combinations):

| Dark | Light |
| --- | --- |
| Screenshot 2024-02-17 at 00 00 10 | Screenshot 2024-02-17 at 00 00 20 |

Though I think we can get this PR in first to improve the accessibility of the section. The color changes could be in a future iteration 😄

**Comment by moT01** [comment]
I played around with this a bit, here's the best I came up with:

| Light | Dark |
| --- | --- |
| Screenshot 2024-02-16 at 12 16 21 PM | Screenshot 2024-02-16 at 12 16 13 PM |

Looks the same in all browsers. Here's the code that produces it:

```
.soundbar {
  margin: 1em 0 2em;
  width: 100%;
  height: 25px;
  background: var(--tertiary-background);
}

input[type='range'] {
  appearance: none;
  overflow: hidden;
  border: 2px solid var(--secondary-color);
}

/* Special styling for WebKit/Blink */
input[type='range']::-webkit-slider-thumb {
  box-shadow: -2000px 0 0 2000px var(--gray-45);
  -webkit-appearance: none;
  border: 2px solid var(--primary-color);
  height: 25px;
  width: 16px;
  background: var(--primary-background);
  cursor: pointer;
}

/* All the same stuff for Firefox */
input[type='range']::-moz-range-thumb {
  box-shadow: -2000px 0 0 2000px var(--gray-45);
  border: 2px solid var(--primary-color);
  border-radius: 0;
  height: 25px;
  width: 16px;
  background: var(--primary-background);
  cursor: pointer;
}

input[type='range']::-moz-range-progress {
  background: var(--gray-90);
  height: 25px;
}
```

Not sure if that's enough contrast for the accessibility concerns, but I think it looks about as good as I can get it. If we want to go with this, I can push the code. What do you think @huyenltnguyen?

**Comment by moT01** [comment]
Alright, I hope you don't mind @Sembauke, but I pushed the changes discussed here. We can revert if we decide we want to go a different route.

**Review by huyenltnguyen — APPROVED** [review]

**Comment by Sembauke** [comment]
Thanks for the feedback, I forgot to change the colors for Mozilla based browsers. I do like the colors in https://github.com/freeCodeCamp/freeCodeCamp/pull/53765#pullrequestreview-1885540622 though.  (The ones at the bottom of the comment)

**Review by ahmaxed — APPROVED** [review]

**Pull request merged**
