### PR TITLE
chore(client): meta and yml certificate -> certification

### PR DESCRIPTION
**Pull request by ShaunSHamilton**
Checklist:

- [x] I have read [freeCodeCamp's contribution guidelines](https://contribute.freecodecamp.org).
- [x] My pull request has a descriptive title (not a vague title like `Update index.md`)
- [x] My pull request targets the `main` branch of freeCodeCamp.
- [x] I have tested these changes either locally on my machine, or GitPod.

Nothing fancy. From what I know, and can see by these changes, nothing has actually happened - unused files have been renamed 🤷‍♂️ (save for the `.md` file)

### CODE REVIEW

**Comment by moT01** [comment]
A couple of quick thoughts - looks like these are mostly the files in the 00-certificates folder. If none of the values are being displayed, do we need to be putting them on Crowdin to get translated? Seems like it might be okay to just keep them all in English so we don't have to keep re-translating them.

Maybe something to consider with a [curriculum refactor](https://github.com/freeCodeCamp/freeCodeCamp/issues/43114) would be to extract the info from these into a meta file or something and only have one version in English.

**Comment by raisedadead** [comment]
That is actually a good idea, Tom. For now to keep moving forth with the PR I think we should be able to merge this as-is, before we circle around to a decision on the linked issue in your comment above.

**Review by raisedadead — APPROVED** [review]

**Review by majestic-owl448 — APPROVED** [review]

**Comment by ieahleen** [comment]
so this one can be merged?

**Comment by raisedadead** [comment]
Yes - unless anyone else has any objections. @nhcarrigan do you mind taking a look as well?

**Review by Sembauke — APPROVED** [review]

**Review by naomi-lgbt — APPROVED** [review]
Think I'm happy with this. Thanks Shaun.

**Pull request merged**
