### PR TITLE
feat(seed): Adds the json file for css grid challenges

### LINKED ISSUE #16368: [beta] CSS Grid challenges should be added
Hello everyone, 

Right now, the most advanced CSS skill we learn on the beta is the flexbox module.

CSS Grid is a great layout system and I think it will be an important skill for every front end developer in the future.

It would be good for new campers to learn about that.

### PR DESCRIPTION
**Pull request by ahmaxed**
order or json files changed and new css grid challenges json is added

#### Pre-Submission Checklist

- [x] Your pull request targets the `staging` branch of freeCodeCamp.
- [x] Branch starts with either `fix/`, `feature/`, or `translate/` (e.g. `fix/signin-issue`)
- [x] You have only one commit (if not, [squash](http://forum.freecodecamp.org/t/how-to-squash-multiple-commits-into-one-with-git/13231) them into one commit).
- [x] All new and existing tests pass the command `npm test`. Use `git commit --amend` to amend any fixes.

#### Type of Change

- [ ] Small bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds new functionality)
- [ ] Breaking change (fix or feature that would change existing functionality)
- [ ] Add new translation (feature adding new translations)

#### Checklist:

- [x] Tested changes locally.
- [x] Addressed currently open issue (replace XXXXX with an issue no in next line)

Closes #16368

#### Description
Added 22 CSS Grid challenges in a JSON file and change the order of the responsive-web-design-projects.json so the Grid challenges could be numbered properly.

### CODE REVIEW

**Comment by ahmadabdolsaheb** [comment]
@QuincyLarson @moT01. feedback from the previous PR was implemented in this PR.

**Comment by QuincyLarson** [comment]
@ahmadabdolsaheb awesome! Thanks for implementing this and opening the pull request.

@mstellaluna would you be interested in QA'ing this? I think it's a good fit for you.

**Comment by mstellaluna** [comment]
@QuincyLarson Sure, I will gladly QA it.

**Comment by mstellaluna** [comment]
I am done testing them. Great job!! 
this is the only issue I found. 
https://github.com/freeCodeCamp/freeCodeCamp/issues/16839

**Comment by moT01** [comment]
@mstellaluna I think that's one of the flex challenges - And not part of this PR?

**Comment by ahmadabdolsaheb** [comment]
@mstellaluna Thanks for the QA and the feedback.

**Comment by mstellaluna** [comment]
@moT01 yea true hold on something not right....

**Comment by raisedadead** [comment]
Hi @mstellaluna this LGTM, can you hit the approve button and give this a merge, if all is OK?

**Comment by mstellaluna** [comment]
otherwise there were no issues, was a great set of challenges

**Comment by mstellaluna** [comment]
@raisedadead i'll approve and merge and open a separate issue for the visual. it's something minor that shouldn't be holding this up at all..

**Review by mstellaluna — APPROVED** [review]
looks great

**Pull request merged**
