### PR TITLE
feat(curriculum): add animations to block 5.2 of the English Curriculum

### PR DESCRIPTION
**Pull request by DanielRosa74**
Checklist:

- [X] I have read and followed the [contribution guidelines](https://contribute.freecodecamp.org).
- [X] I have read and followed the [how to open a pull request guide](https://contribute.freecodecamp.org/#/how-to-open-a-pull-request).
- [X] My pull request targets the `main` branch of freeCodeCamp.
- [X] I have tested these changes either locally on my machine, or GitPod.

### CODE REVIEW

**Comment by moT01** [comment]
Hey @DanielRosa74, didn't you just upload a new audio file to the CDN for 5.2-3? Won't the timestamps for that be different and you will likely need to adjust all the scenes in that section?

**Comment by DanielRosa74** [comment]
> Hey @DanielRosa74, didn't you just upload a new audio file to the CDN for 5.2-3? Won't the timestamps for that be different and you will likely need to adjust all the scenes in that section?

Yes, @moT01! This was sent prior to that. I did not imagine the file would be ready that fast.

**Comment by moT01** [comment]
Do you want to make those changes on this PR?

**Review by nieldakarla — APPROVED** [review]
LGTM

**Review by naomi-lgbt — APPROVED** [review]

**Pull request merged**
