### PR TITLE
Changed the reference to the path in guplfile.js to allow spaces

### PR DESCRIPTION
**Pull request by dgrcode**
#### Pre-Submission Checklist

- [x] Your pull request targets the `staging` branch of freeCodeCamp.
- [x] Branch starts with either `fix/`, `feature/`, or `translate/` (e.g. `fix/signin-issue`)
- [x] You have only one commit (if not, [squash](http://forum.freecodecamp.com/t/how-to-squash-multiple-commits-into-one-with-git/13231) them into one commit).
- [x] All new and existing tests pass the command `npm test`. Use `git commit --amend` to amend any fixes.

#### Type of Change

- [x] Small bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds new functionality)
- [ ] Breaking change (fix or feature that would change existing functionality)
- [ ] Add new translation (feature adding new translations)

#### Checklist:

- [x] Tested changes locally.
- [ ] Closes currently open issue (replace XXXX with an issue no): Closes #XXXX

#### Description

The version of the repo I forked didn't start if the complete path to my repository had spaces. Using a relative path had conflicts depending on the OS. Using `path.normalize()` instead of `path.join()` solves the problem.

Thanks to @systimotic and @Bouncey for helping me fix it!

### CODE REVIEW

**Review by systimotic — APPROVED** [review]
## LGTM 👍 
Thanks for the PR @dgrcode!
As I helped make this change, I'd appreciate if someone else could review this as well. It worked fine for me on Windows, and I believe Daniel is on Linux. Maybe someone could test on MacOS?

**Comment by dhcodes** [comment]
@systimotic tested on MacOS. works like a charm. **LGTM**

**Comment by dhcodes** [comment]
Thanks for contributing this @dgrcode 👍 💯 🦅 🌮

**Comment by dgrcode** [comment]
My first contribution but surely not my last :)

Thank you @dhcodes and @systimotic for testing the code. By the way, you were right I'm using Linux. I totally forgot to mention it!

**Pull request merged**
