### PR TITLE
fix(client): ensure unmount effect has most recent values

### PR DESCRIPTION
**Pull request by awu43**
Checklist:

- [x] I have read [freeCodeCamp's contribution guidelines](https://contribute.freecodecamp.org).
- [x] My pull request has a descriptive title (not a vague title like `Update index.md`)
- [x] My pull request targets the `main` branch of freeCodeCamp.
- [x] I have tested these changes either locally on my machine, or GitPod.

### CODE REVIEW

**Review by ojeytonwilliams — CHANGES_REQUESTED** [review]
Hey @awu43 this an interesting approach.  Could you elaborate a bit on what problems this solves?

Also, @freeCodeCamp/moderators, we should get https://github.com/freeCodeCamp/freeCodeCamp/pull/43195 merged first.

**Comment by awu43** [comment]
Because the `useEffect` only runs once on mount, the old cleanup uses the initial values of `acceptedPrivacyTerms` and `acceptTerms()`. This fix ensures that the cleanup will always use the latest values. If neither ever changes (which I suspect is the case), then this fix isn't strictly necessary, but it will ensure that the effect continues to work if either does start changing.

**Comment by ojeytonwilliams** [comment]
That makes sense, thanks for explaining.  I agree that this is a bit safer in case of weird behaviour.

Since https://github.com/freeCodeCamp/freeCodeCamp/pull/43195 is in, I rebased this so we can let the new tests run on it.

**Review by ojeytonwilliams — APPROVED** [review]
LGTM :+1:

**Review by moT01 — APPROVED** [review]
LGTM 🎉

**Pull request merged**
