### PR TITLE
Spanish translation of GraphQL stub

### PR DESCRIPTION
**Pull request by s-Hale**
- [x] I have read [freeCodeCamp's contribution guidelines](https://github.com/freeCodeCamp/freeCodeCamp/blob/master/CONTRIBUTING.md).
- [x] My pull request has a descriptive title (not a vague title like `Update index.md`)
- [x] My pull request targets the `master` branch of freeCodeCamp.
- [x] None of my changes are plagiarized from another source without proper attribution.
- [x] All the files I changed are in the same world language (for example: only English changes, or only Chinese changes, etc.)
- [x] My changes do not use shortened URLs or affiliate links.

Translated the GraphQL stub for the guide.

### CODE REVIEW

**Comment by s-Hale** [comment]
The language: english label can be removed. It isn't.

**Comment by RandellDawson** [comment]
@s-Hale You need to revert the changes to the English file as those extra lines will cause extra space when it is actually rendered. The same goes for the Spanish version.  If you can correct those, I can merge your PR today.  Once you have reverted the changes on the English version, your PR should only have one file being changed.

FYI - The English label appeared on this PR because you made changes to an English version of the file.  Also, you did not follow the instructions in the PR body, because PRs should only be changing files of the same language.  Since you mixed English with Spanish, that is why your PR has taken longer to review.

**Comment by s-Hale** [comment]
Thanks for the feedback! I had no idea the spaces had happened, I think that must be Prettier getting involved, and I accidentally saved over the English file while trying to debug the integration test failure (which was down to a lack of localeTitle.) I couldn't think of any English changes I'd made ^^;

Spaces reverted.

**Comment by RandellDawson** [comment]
@s-Hale I mispoke when I said I can get your PR merged.  We have some reviewers who specialize in reviewing Spanish translations which will need to review and merge this one.  We will have to wait for them to get to this PR.

**Review by RandellDawson — APPROVED** [review]

**Comment by RandellDawson** [comment]
Thank you for your contribution to the page! 👍
We're happy to accept these changes, and look forward to future contributions. 🎉

**Pull request merged**
