### PR TITLE
add = "" to make it easier to understand directions

### PR DESCRIPTION
**Pull request by Stoner19**
The instructions on this waypoint are pretty confusing. I've added = next to the vars for the sake of helping clear things up. Several users have joined the glitter chat with the same question & confusion.

### CODE REVIEW

**Comment by ltegman** [comment]
You'll need to escape the double quotes.

**Comment by Stoner19** [comment]
Thank you. fixing that now.

**Comment by ltegman** [comment]
Thanks for the fix! One more request: you'll need to [squash your commits](https://github.com/FreeCodeCamp/FreeCodeCamp/wiki/git-rebase#squashing-multiple-commits-into-one). After that we'll be good to merge :smile:

**Comment by Stoner19** [comment]
looks like I have some other things to correct before this is squashed properly. Let's close this for now and I'll make a new pull request some other day.

**Pull request closed without merging**
