### PR TITLE
Add/FR translation responsive design with bootstrap

### LINKED ISSUE #7532: French translation of Responsive Design with Bootstrap
Just starting translating the Bootstrap part of the curriculum.

### PR DESCRIPTION
**Pull request by N0bl3**
Translation of bootstrap challenges in french.
closes #7532

### CODE REVIEW

**Comment by theflametrooper** [comment]
closes #7625

**Comment by N0bl3** [comment]
Much better. Now the PR is clean.

**Comment by theflametrooper** [comment]
Awesome! @fnonga Could you verify this?

**Comment by AkiraLaine** [comment]
@theflametrooper @N0bl3 This looks good to me. I can wait for @fnonga to QA before merging if you want.

**Comment by theflametrooper** [comment]
Nah, go ahead!

**Comment by AkiraLaine** [comment]
Thanks a ton @N0bl3

**Comment by theflametrooper** [comment]
@N0bl3 Thanks for helping!

**Comment by fnonga** [comment]
good work, thanks !

**Comment by theflametrooper** [comment]
closes #7625

**Comment by sbter79** [comment]
#7631

**Pull request merged**
