### PR TITLE
fix(seed): removed typo from task description

### LINKED ISSUE #17107: Remove typo from task description
#### Challenge Name
[React: Compose React Components ](https://beta.freecodecamp.org/en/challenges/react/compose-react-components)

#### Issue Description
Typo in task description
`...Next, nest the Fruits class component into` ~~the~~ `the TypesOfFood component, `

### PR DESCRIPTION
**Pull request by ghost**
#### Pre-Submission Checklist

- [x] Your pull request targets the `staging` branch of freeCodeCamp.
- [x] Branch starts with either `fix/`, `feature/`, or `translate/` (e.g. `fix/signin-issue`)
- [x] You have only one commit (if not, [squash](http://forum.freecodecamp.org/t/how-to-squash-multiple-commits-into-one-with-git/13231) them into one commit).
- [x] All new and existing tests pass the command `npm test`. Use `git commit --amend` to amend any fixes.

#### Type of Change

- [x] Small bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds new functionality)
- [ ] Breaking change (fix or feature that would change existing functionality)
- [ ] Add new translation (feature adding new translations)

#### Checklist:

- [x] Tested changes locally.
- [x] Addressed currently open issue (replace XXXXX with an issue no in next line)

Closes #17107

#### Description

Removed the "the" typo from the react.json page. Tested locally.

### CODE REVIEW

**Comment by raisedadead** [comment]
Hi @aditya1994 can you confirm the checklist, was this all tested locally, and fill up the stuff? You can click the edit button on the opening post.

Good work with the changes. I would recommend taking a look the complete[Guidelines for Contributing](https://github.com/FreeCodeCamp/FreeCodeCamp/blob/staging/CONTRIBUTING.md)

Thanks.

**Review by raisedadead — APPROVED** [review]

**Comment by raisedadead** [comment]
#### :sparkles: :sparkles: **AWESOME! LGTM.** :sparkles: :sparkles: 

Thanks @aditya1994 , for this pull request and contributing to the code-base for the first time.
We will be looking forward for more contributions in future.

Cheers and happy contributing!

**Comment by aditya1994** [comment]
Thank you! 

Looking forward :)

**Comment by raisedadead** [comment]
Sure, please take a look at https://github.com/freeCodeCamp/learn , we need a lot of assistance on the UI and CSS over there.

**Pull request merged**
