### PR TITLE
Field guide

### PR DESCRIPTION
**Pull request by ghost**

### CODE REVIEW

**Comment by BerkeleyTrue** [comment]
@danraley We are moving field guides to the wiki. Have you added these there yet so I can close this PR?

**Comment by danraley** [comment]
I had not created wikis for since I had submitted the pull request already

**Comment by BerkeleyTrue** [comment]
Ok, can you amend this to remove the changes to .eslintrc?

**Comment by BerkeleyTrue** [comment]
@danraley I can remove it for you if you'd like? Or We can pair if you need help?

**Comment by danraley** [comment]
If you could remove it that would be great. I'm switching computers and
don't have a copy of FCC setup right at the moment.

**Comment by BerkeleyTrue** [comment]
@danraley Looks like we have already moved all field guides to the wiki. Please add these there when you get a chance. Thanks!

**Pull request closed without merging**
