### PR TITLE
Use HTML5 to Require a Field grammar fix

### LINKED ISSUE #12121: Instructions sentence/grammar issue
Challenge [Use HTML5 to Require a Field](https://www.freecodecamp.com/challenges/use-html5-to-require-a-field) has an issue.
User Agent is: <code>Mozilla/5.0 (Windows NT 6.3; WOW64; rv:50.0) Gecko/20100101 Firefox/50.0</code>.
Please describe how to reproduce this issue, and include links to screenshots if possible.

The following paragraph from the instructions is ungrammatical:

"For example, if you wanted to make a text input field required, you can just add the word required within your input element, you would use: <input type="text" required>"

I suggest changing to the following:

"For example, if you wanted to make a text input field required, you can just add the word required within your input element, like this: <input type="text" required>"

### PR DESCRIPTION
**Pull request by GramParallelo**
#### Pre-Submission Checklist

- [x] Your pull request targets the `staging` branch of FreeCodeCamp.
- [x] Branch starts with either `fix/`, `feature/`, or `translate/` (e.g. `fix/signin-issue`)
- [x] You have only one commit (if not, [squash](http://forum.freecodecamp.com/t/how-to-squash-multiple-commits-into-one-with-git/13231) them into one commit).
- [x] All new and existing tests pass the command `npm test`. Use `git commit --amend` to amend any fixes.

#### Type of Change

- [x] Small bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds new functionality)
- [ ] Breaking change (fix or feature that would change existing functionality)
- [ ] Add new translation (feature adding new translations)

#### Checklist:

- [x] Tested changes locally.
- [x] Closes currently open issue (replace XXXX with an issue no): Closes #12121

#### Description

Grammar fix for challenge: Use HTML5 to Require a Field.

### CODE REVIEW

**Review by raisedadead — CHANGES_REQUESTED** [review]
`yarn.lock` :confused: ?
- Remove this file.
- Amend your changes to remove issue no from your commit message.
- Follow the [Guidelines for Contributing](https://github.com/FreeCodeCamp/FreeCodeCamp/blob/staging/CONTRIBUTING.md).
- Hit us on the [Contributors Chat room](https://gitter.im/FreeCodeCamp/Contributors) for any assistance.

**Comment by GramParallelo** [comment]
Oh, snap my B.  (darn yarn).  I will gladly remove the issue from commit message but I didn't find that in the guidelines.  I was aware of not putting it in the PR title but not the commit message.  [Common Steps](https://github.com/FreeCodeCamp/FreeCodeCamp/blob/staging/CONTRIBUTING.md#common-steps)
Is that guideline in the Contributing docs too?

**Comment by dhcodes** [comment]
True, we should probably update the contributing doc so read: 
> Do not add the issue number in the PR title or commit message.

**Comment by GramParallelo** [comment]
@dhcodes First Timer Issue?

**Review by raisedadead — APPROVED** [review]

**Comment by raisedadead** [comment]
#### :sparkles: :sparkles: **LGTM.** :sparkles: :sparkles: 

Thanks @GramParallelo and congrats on your first contribution to Free Code Camp.
Happy fixing!

**Comment by dhcodes** [comment]
@GramParallelo I made an issue regarding the instructions #12140

**Pull request merged**
