### PR TITLE
feat: add Docker build

### PR DESCRIPTION
**Pull request by ojeytonwilliams**
Recreates https://github.com/freeCodeCamp/freeCodeCamp/pull/40593

@raisedadead I know we're considering other options for the client, but I thought I'd put this up anyway.  I wasn't sure how soon you were thinking about shifting the infrastructure, so if you want to use Docker in the interim, here it is.

### CODE REVIEW

**Comment by ojeytonwilliams** [comment]
To get it working locally, use the `fix: add default CLIENT_PORT` commit, since the last one removes the db service.  

Building the client is achieved like so:
```
DOCKER_BUILDKIT=1 docker build --build-arg FREECODECAMP_NODE_ENV=development --build-arg STRIPE_PUBLIC_KEY=pk_from_stripe_dashboard --build-arg HOME_LOCATION=http://localhost:8000 --build-arg API_LOCATION=http://localhost:3000 --build-arg FORUM_LOCATION=https://forum.freecodecamp.org --build-arg NEWS_LOCATION=https://www.freecodecamp.org/news --build-arg CURRICULUM_LOCALE=english --build-arg CLIENT_LOCALE=english --build-arg SHOW_UPCOMING_CHANGES=false --build-arg ALGOLIA_APP_ID=app_id_from_algolia_dashboard --build-arg ALGOLIA_API_KEY=api_key_from_algolia_dashboard --build-arg PAYPAL_CLIENT_ID=id_from_paypal_dashboard --build-arg DEPLOYMENT_ENV=staging -t fcc_client -f ./client.Dockerfile .
```
Yep, it's a silly length, but I'm not sure how else to pass in build args.

The api doesn't have any, so it's much shorter:

```
DOCKER_BUILDKIT=1 docker build -t fcc_api -f ./server.Dockerfile .
```

Once those two have run

```
docker-compose -f docker-compose.api.yml up
```
starts the server and

```
docker-compose -f docker-compose.client.yml up
```
starts the client.

They're configurable via `API_PORT` and `CLIENT_PORT` respectively.

**Comment by nhcarrigan** [comment]
So we could potentially load those build scripts into `.sh` files and add a `package.json` script to run them - that would also allow them to be version controlled and might make things easier to maintain?

**Comment by ojeytonwilliams** [comment]
> So we could potentially load those build scripts into `.sh` files and add a `package.json` script to run them - that would also allow them to be version controlled and might make things easier to maintain?

Yep, that's exactly what https://github.com/freeCodeCamp/freeCodeCamp/pull/41762 will do.  The only real difference is that scripts are inlined as `run` scripts.

**Comment by nhcarrigan** [comment]
Perfect for CI, but I'm wondering about local development too - I know a lot of contributors seem to want a Docker build to work on our codebase locally.

**Comment by ojeytonwilliams** [comment]
> Perfect for CI, but I'm wondering about local development too - I know a lot of contributors seem to want a Docker build to work on our codebase locally.

Oh, fair point. These images would provide a pretty bad developer experience as is, but putting the scripts in .sh files seems reasonable.

**Comment by raisedadead** [comment]
I am merging this in to unblock further work.

**Pull request merged**
