### PR TITLE
fix:regex error in selection sort insertion sort and merge sort

### LINKED ISSUE #39220: Test Error on "Implement Selection Sort"
**Describe your problem and how to reproduce it:**
The tests for this challenge require the user to NOT use the `.sort()` function. The particular testString that checks this uses a regex, but that regex will match an occurrence of the word `sort` (case-sensitive), so using a variable name such as `sortedArray` will cause this test case to fail erroneously.

**Add a Link to the page with the problem:**
[Implement Selection Sort challenge](https://www.freecodecamp.org/learn/coding-interview-prep/algorithms/implement-selection-sort)

**Tell us about your browser and operating system:**
* Browser Name: Chrome
* Browser Version:  83.0.4103.116
* Operating System: Windows 10 Home 1909

**If possible, add a screenshot here (you can drag and drop, png, jpg, gif, etc. in this box):**
Failing Code:
image
Passing Code: 
image
As a note, the code is not mine but was provided by a user when they requested debugging assistance.

### PR DESCRIPTION
**Pull request by ruhci28**
Checklist:

- [x] I have read [freeCodeCamp's contribution guidelines](https://contribute.freecodecamp.org).
- [x ] My pull request has a descriptive title (not a vague title like `Update index.md`)
- [x ] My pull request targets the `master` branch of freeCodeCamp.
- [x ] All the files I changed are in the same world language, for example: only English changes, or only Chinese changes, etc.

Closes #39220 

I edit the regex for checking that sort() function is not in code.

### CODE REVIEW

**Comment by nhcarrigan** [comment]
LGTM! Thanks for taking care of this! 🙂

**Comment by ruhci28** [comment]
Thanks

**Review by ShaunSHamilton — APPROVED** [review]
LGTM 👍

**Review by Manish-Giri — APPROVED** [review]
LGTM 💯

**Review by RandellDawson — APPROVED** [review]

**Comment by RandellDawson** [comment]
Thank you for your contribution to the page! 👍
We're happy to accept these changes, and look forward to future contributions. 🎉

**Pull request merged**
