### PR TITLE
Fixed the typo on Deleting jQuery functions issue #2832

### PR DESCRIPTION
**Pull request by natac13**
There was a double your.... I do think the original issue was about the extra back-slash... I did not want to change that since the linter did not like it. But the double 'your' is gone!

### CODE REVIEW

**Comment by natac13** [comment]
I apologize, as this was first attempt at a pull request. I have not learned yet how to update the my local repo from the original FCC

**Comment by benmcmahon100** [comment]
this command chain should work
git stash
git pull
git stash apply

**Comment by natac13** [comment]
should I do new pull request for this??

**Comment by benmcmahon100** [comment]
@natac13 no you should be able to commit to this one

**Comment by natac13** [comment]
@benmcmahon100 just want to be sure... but no more action is required on my part? I have also setup a upstream remote to track the original repo.

**Comment by benmcmahon100** [comment]
Hmm it's still not happy with the pr. did you push after wards?

**Comment by natac13** [comment]
Probably beat I just do it again lol Now that I have the up to date repo and can make another fix branch. Sorry about this, be 5 mins and Ill fix!

**Pull request closed without merging**
