### PR TITLE
fix(client): remove broken current challenge button

### PR DESCRIPTION
**Pull request by naomi-lgbt**
Checklist:

- [X] I have read [freeCodeCamp's contribution guidelines](https://contribute.freecodecamp.org).
- [X] My pull request has a descriptive title (not a vague title like `Update index.md`)
- [X] My pull request targets the `main` branch of freeCodeCamp.
- [X] I have tested these changes either locally on my machine, or GitPod.

Closes #XXXXX

Too many reports of this button not working. 🙁

### CODE REVIEW

**Review by raisedadead — DISMISSED** [review]

**Review by ShaunSHamilton — CHANGES_REQUESTED** [review]
Are we happy to leave this button in the profile?

**Comment by nhcarrigan** [comment]
Haven't heard anything about that button being broken (I don't even *see* that button on my profile), but happy to remove it too.

**Comment by raisedadead** [comment]
> Are we happy to leave this button in the profile?

To be clear, we are removing it because of the confusion it creates, from reading the complaints on the forum. If it's broken it should go or it should be fixed. Moving it around will not fix it.

**Comment by ShaunSHamilton** [comment]
> Haven't heard anything about that button being broken (I don't even _see_ that button on my profile), but happy to remove it too.

It looks like ancient logic (`isLocked` is involved).

My suggestion: Delete the `CurrentChallengeLink` component, and whatever else touches it.

**Review by ShaunSHamilton — APPROVED** [review]
LGTM 👍

**Review by raisedadead — APPROVED** [review]

**Pull request merged**
