### PR TITLE
fix: corrected spelling errors in APIs and microservices guide

### PR DESCRIPTION
**Pull request by tracer223**
- [x ] I have read [freeCodeCamp's contribution guidelines](https://github.com/freeCodeCamp/freeCodeCamp/blob/master/CONTRIBUTING.md).
- [x ] My pull request has a descriptive title (not a vague title like `Update index.md`)
- [x ] My pull request targets the `master` branch of freeCodeCamp.
- [x ] None of my changes are plagiarized from another source without proper attribution.
- [x ] My article does not contain shortened URLs or affiliate links.

Closes #XXXXX

### CODE REVIEW

**Comment by RandellDawson** [comment]
The change you made to the spelling errors looks fine.  Not sure why you changed `curriculum/package-lock.json`.  That file was recently changed by a core team member 12 hours ago.

@raisedadead Please take a look at this one.

**Comment by Nirajn2311** [comment]
@RandellDawson sometimes when you run `npm install` it automatically changes package-lock.json 

@tracer223 could you remove the package-lock.json file as it is not needed in the PR.

cc - @raisedadead

**Review by raisedadead — APPROVED** [review]
Changes LGTM

**Comment by raisedadead** [comment]
@RandellDawson @Nirajn2311 

Thanks for tagging. Looking at @tracer223 's initial commits, it was kind of valid because the lockfile did need a update on their branch.

Then I realised that they were a tad bit behind the `master` where we did update the file before their PR.

@tracer223 ,

Thanks a lot for taking the time to prepare this PR. I have rebased the branch for your to be in sync.
We are waiting for the CI before getting this merged.

Nice work!

**Comment by tracer223** [comment]
@raisedadead Awesome, thanks! My first pull request, there was bound to be something that didn't go according to plan. Glad to help!

**Pull request merged**
