### PR TITLE
added different types of variables used in Swift 4

### PR DESCRIPTION
**Pull request by agaribovic**
- [x] I have read [freeCodeCamp's contribution guidelines](https://github.com/freeCodeCamp/freeCodeCamp/blob/master/CONTRIBUTING.md).
- [x] My pull request has a descriptive title (not a vague title like `Update index.md`)
- [x] My pull request targets the `master` branch of freeCodeCamp.
- [x] None of my changes are plagiarized from another source without proper attribution.
- [x] My article does not contain shortened URLs or affiliate links.

If your pull request closes a GitHub issue, replace the XXXXX below with the issue number.

Closes #XXXXX

### CODE REVIEW

**Comment by RandellDawson** [comment]
Closed and Reopened this PR to attempt to resolve a specific Travis build failure.

**Review by Manish-Giri — CHANGES_REQUESTED** [review]
Hi @agaribovic 

You can mention the variable types directly, without prepending them with `Swift`. So, `Float`, `Double`, `Bool`, etc should be fine.

Please make these changes and re-submit this PR.

**Comment by agaribovic** [comment]
@Manish-Giri  done

**Review by Manish-Giri — APPROVED** [review]
LGTM. Thank You for your contribution 👍

**Pull request merged**
