### PR TITLE
fix(curriculum): simplify example

### LINKED ISSUE #51872: Confusing example in Cafe Menu Step 21
### Describe the Issue

I am seeing this over and over again in the forum. The example in the instructions uses the selector `#example-id` and for whatever reason people think they need to add `-id` to the end of the `#menu` selector in their solution. And the hint doesn't appear to help much because half the time they will paste the hint verbatim along with their code.

### Affected Page

https://www.freecodecamp.org/learn/2022/responsive-web-design/learn-basic-css-by-building-a-cafe-menu/step-21

### Your code

Example:

```
#example-id {
  width: 250px;
}
```

Camper solution:

```
#menu-id {
  width: 300px;
}
```

### Expected behavior

I think we need to get rid of the dash in the example. I also think we could improve the instructions by making it clearer how to use the `id` selector.

> The goal now is to make the `menu` `div` not take up the entire width of the page. The CSS `width` property is perfect for this.

> You can use the `id` selector to target a specific element by its `id` attribute. An `id` selector is defined by placing a hash symbol in front of the element's `id` value. For example, if an element has the `id` of `cat` then you would select it by its `id` like this: 

```
#cat {
  width: 250px;
}
```

I also think it might be helpful to answer the question "Why use an `id`?" so people know why we are introducing this selector. We do mention that it allows you to "target a specific element" but that doesn't explain why you would want to do that. But I understand that we want to keep reading down to a minimum so I'm not insisting :slightly_smiling_face: 

### Screenshots

_No response_

### System

N/A

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by Yash-Ambekar**
Checklist:

- [done ] I have read and followed the [contribution guidelines](https://contribute.freecodecamp.org).
- [ done] I have read and followed the [how to open a pull request guide](https://contribute.freecodecamp.org/#/how-to-open-a-pull-request).
- [ Yes] My pull request targets the `main` branch of freeCodeCamp.
- [ Not on GitPod] I have tested these changes either locally on my machine, or GitPod.

Closes #51872

I have made the decided changes to the markdown files for English, Portuguese and Italian languages. For Portuguese and Italian languages I used google translate and to reduce any discrepancies in the translation the unchanged lines in the previous version of the description were retained.

### CODE REVIEW

**Comment by naomi-lgbt** [comment]
Our action runners are backed up, so the bot isn't posting the message yet, but you should not change the non-english files through GitHub.

**Comment by Yash-Ambekar** [comment]
> Our action runners are backed up, so the bot isn't posting the message yet, but you should not change the non-english files through GitHub.

Ohh got it. It was naive of me to think that it would be so easy to translate content. Sorry wont happen again, so should I keep the non-English content as is and request review?

**Comment by naomi-lgbt** [comment]
Yes. :3

**Comment by Yash-Ambekar** [comment]
I have restored the non-English content.

**Review by naomi-lgbt — APPROVED** [review]

**Review by gikf — APPROVED** [review]

**Comment by gikf** [comment]
Hi @Yash-Ambekar. Congrats on your first pull request (PR)! 🎉

Thank you for your contribution to the page! 👍
We are happy to accept these changes and look forward to future contributions. 📝

**Pull request merged**
