### PR TITLE
fix(editor): restore syntax highlighting for light theme

### LINKED ISSUE #15704: Syntax highlighting in editor
Currently the beta code editor pane (light theme) doesn't have syntax highlighting.

basic_javascript__word_blanks___freecodecamp_and_word_blanks___freecodecamp

### PR DESCRIPTION
**Pull request by no-stack-dub-sack**
#### Pre-Submission Checklist

- [x] Your pull request targets the `staging` branch of freeCodeCamp.
- [x] Branch starts with either `fix/`, `feature/`, or `translate/` (e.g. `fix/signin-issue`)
- [x] You have only one commit (if not, [squash](http://forum.freecodecamp.org/t/how-to-squash-multiple-commits-into-one-with-git/13231) them into one commit).
- [x] All new and existing tests pass the command `npm test`. Use `git commit --amend` to amend any fixes.

#### Type of Change

- [x] Small bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds new functionality)
- [ ] Breaking change (fix or feature that would change existing functionality)
- [ ] Add new translation (feature adding new translations)

#### Checklist:

- [x] Tested changes locally.
- [x] Addressed currently open issue (replace XXXXX with an issue no in next line)

Closes #15704

#### Description

Is there any reason we can't do this right now? Seems to work and switch between light and night mode just fine (except for the pesky "Something Went Wrong..." message which seemed to exist before this change when switching modes locally).

### CODE REVIEW

**Comment by raisedadead** [comment]
#### :sparkles: :sparkles: **Code LGTM.** :sparkles: :sparkles: 

Thanks @no-stack-dub-sack 

I'l wait for Berkley to approve before a merge.

**Comment by BerkeleyTrue** [comment]
This PR just reverts back to the previous theme. The issue calls for getting syntax highlighting working with a light theme

**Comment by no-stack-dub-sack** [comment]
@BerkeleyTrue this wasn't totally clear to me - the beta light theme and the prod light UI themes are nearly identical, no? If we want an editor theme that does not have a dark background we can pretty easily find one... are there any specific guidelines you have in mind before I make another change?

**Comment by no-stack-dub-sack** [comment]
Here are some choices. Or, we could just keep the old theme which has nice vibrant colors, and just make the editor background white (and change unquoted strings to a different color).

Thoughts @raisedadead @BerkeleyTrue @QuincyLarson? 

default 
image

paraiso-light
image

base-16-llight
image

solarized-light
image

**Comment by BerkeleyTrue** [comment]
@no-stack-dub-sack can you make that comment in the issue and continue the conversion there?

**Comment by no-stack-dub-sack** [comment]
@raisedadead @BerkeleyTrue Ok, all set. There's no need to specify any theme in the codemirror options object in Editor.jsx since we're going with default. And I just updated the CDNs we do need to the latest versions. Here's what it looks like now: 
image

**Comment by texas2010** [comment]
That light theme is nice! i just want to say it XD

**Review by raisedadead — APPROVED** [review]

**Comment by systimotic** [comment]
Nice work @no-stack-dub-sack!

**Comment by no-stack-dub-sack** [comment]
# 🎉 ⭐️ 🌟 🎉 ⭐️ 🌟 🎉 ⭐️ 🌟

**Pull request merged**
