### PR TITLE
Minor typos

### PR DESCRIPTION
**Pull request by YoDebugger**
- [x] I have read [freeCodeCamp's contribution guidelines](https://github.com/freeCodeCamp/freeCodeCamp/blob/master/CONTRIBUTING.md).
- [x] My pull request has a descriptive title (not a vague title like `Update index.md`)
- [x] My pull request targets the `master` branch of freeCodeCamp.
- [x] None of my changes are plagiarized from another source without proper attribution.
- [x] My article does not contain shortened URLs or affiliate links.

### CODE REVIEW

**Comment by lynxlynxlynx** [comment]
Trivial, but mostly ok.

**Comment by RandellDawson** [comment]
Closed and Reopened this PR to attempt to resolve a specific Travis build failure.

**Comment by YoDebugger** [comment]
@lynxlynxlynx @RandellDawson Can you please approve and merge the PR. Thanks.

**Comment by RandellDawson** [comment]
@YoDebugger There are 4 other PRs ahead of yours with changes to the same file.  We review PRs from oldest to newest when there are multiple PRs making changes to the same file.  It could be a while until this PR gets reviewed for its content.   We started with about 11,000 open PRs at the end of November and we are now down to 5400+.  There are only a few reviewers, so it just takes time.  

Thank you for being patient.

**Review by cmccormack — APPROVED** [review]
Looks good to me, and congratulations on your first Pull Request!  🎉🎉🎉
We look forward to future contributions!

**Pull request merged**
