### PR TITLE
Edited test to allow for lowercase hex code

### LINKED ISSUE #13535: [beta] Applied Visual Design: Tertiary Colors Throwing Errors with Correct Hex
See screenshot below for clarification. Correct (given) hex codes are still throwing errors. Have refreshed, restarted, and cleared cache. Please advise as it will not allow me to continue without passing this challenge. 

Thank you! 

Challenge [learn-about-tertiary-colors](http://beta.freecodecamp.com/en/challenges/applied-visual-design/learn-about-tertiary-colors) has an issue.
User Agent is: <code>Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/56.0.2924.87 Safari/537.36</code>.
Please describe how to reproduce this issue, and include links to screenshots if possible.

```html


<style>
  body {
    background-color: #FFFFFF;
  }
  
  .orange {
    background-color: #ff7d00;
  }
  
  .cyan {
    background-color: #00ffff;
  }
  
  .raspberry {
    background-color: #ff007d;
  }
  
  div {
    height: 100px;
    width: 100px;
    margin-bottom: 5px;
  }
</style>
  
<div class="orange"></div>
<div class="cyan"></div>
<div class="raspberry"></div>

```

image

### PR DESCRIPTION
**Pull request by cdrani**
#### Pre-Submission Checklist

- [x] Your pull request targets the `staging` branch of freeCodeCamp.
- [x] Branch starts with either `fix/`, `feature/`, or `translate/` (e.g. `fix/signin-issue`)
- [x] You have only one commit (if not, [squash](http://forum.freecodecamp.com/t/how-to-squash-multiple-commits-into-one-with-git/13231) them into one commit).
- [x] All new and existing tests pass the command `npm test`. Use `git commit --amend` to amend any fixes.

#### Type of Change

- [x] Small bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds new functionality)
- [ ] Breaking change (fix or feature that would change existing functionality)
- [ ] Add new translation (feature adding new translations)

#### Checklist:

- [x] Tested changes locally.
- [x] Closes currently open issue (replace XXXX with an issue no): Closes #13535
#### Description

Changed the tests to allow for uppercase or lowercase hex code values. Ex: #ff7d00 or #FF7D00 as per issue.

### CODE REVIEW

**Comment by dhcodes** [comment]
Assuming we have no problem with uppercase CSS properties, I might recommend that we add the `i` flag to the end of the Regex instead of an 'or' test case. It will allow for the case insensitivity needed both for the Hex codes and for the CSS properties. I will ask if there is any reason not to use the `i` flag and get back to you.

**Comment by systimotic** [comment]
Adding the `i` flag would be problematic in this challenge, as class names are case-sensitive. Demo: http://codepen.io/systimotic/pen/ryLVLG?editors=1100

**Comment by cdrainxv** [comment]
@dhcodes: Yes, I pondered that case as well. Funnily enough, I also had to do a quick fiddle just to make sure. I decided on the or because I  don't think there's any sense in mixing the the cases of the hex code values,  therefore my belief that campers should adopt using either full lowercase (#ff7d00) or full uppercase (#FF7D00), not an amalgam of both. Alas, I am not an authority on this matter, so I will leave it up to you. Thanks.

**Comment by dhcodes** [comment]
@systimotic thanks friend, hadn't thought of that. **LGTM** @cdrainxv Thanks for contributing! 👍 💯 🌮

**Pull request merged**
