### PR TITLE
Fixes incorrect showing MDNlinks on challenges

### LINKED ISSUE #6094: Waypoint: Checkpoint: Stand in Line (Disappearing Helpful Links)
A camper (in main chat) described an issue with an element disappearing (i.e., seeing momentarily on load and then 'element vanishing'). Was able to reproduce on chromium, firefox, midori (linux x64). There is a line 'helpful links:' (just above the run button) that shows momentarily and then disappears (can be reproduced by refreshing page after load as well). 
thisone2

### PR DESCRIPTION
**Pull request by bugron**
Now, it's ready to be QA'd.
Closes #6094.

### CODE REVIEW

**Comment by SaintPeter** [comment]
Works like a charm!

Isn't there some leftover JavaScript that can/should be removed?

**Comment by bugron** [comment]
@SaintPeter nope.

**Comment by SaintPeter** [comment]
Then I am at a loss to understand how the text could display then disappear.   What was the mechanism?

**Comment by bugron** [comment]
@SaintPeter this is the situation, for real.

**Comment by SaintPeter** [comment]
[showJS.jade:101](https://github.com/FreeCodeCamp/FreeCodeCamp/blob/staging/server/views/coursewares/showJS.jade#L101)
[showBonfire.jade:113](https://github.com/FreeCodeCamp/FreeCodeCamp/blob/staging/server/views/coursewares/showBonfire.jade#L113)
```js
if (!!{JSON.stringify(MDNlinks.length)}) {
          $('#MDN-links').addClass('collapse');
      }
```

**Comment by bugron** [comment]
Yes, I was about to comment that))

**Pull request merged**
