### PR TITLE
made output for sum and subtraction consistent with product

### LINKED ISSUE #9481: Inconsistent Output
#### Challenge Name

[Add Two Numbers with JavaScript](https://www.freecodecamp.com/challenges/add-two-numbers-with-javascript)
and
[Subtract One Number from Another with JavaScript](https://www.freecodecamp.com/challenges/subtract-one-number-from-another-with-javascript)

#### Issue Description

The `console.log()` output for these two challenges is inconsistent with [Multiply Two Numbers with JavaScript](https://www.freecodecamp.com/challenges/multiply-two-numbers-with-javascript). See screenshots below.

#### To Fix

This [line](https://github.com/FreeCodeCamp/FreeCodeCamp/blob/6722e2278ef324ad20914e1c1afa52136fb750fe/seed/challenges/01-front-end-development-certification/basic-javascript.json#L296) needs to be changed to:

```js
"(function(z){return 'sum = '+z;})(sum);"
```

And [this line](https://github.com/FreeCodeCamp/FreeCodeCamp/blob/6722e2278ef324ad20914e1c1afa52136fb750fe/seed/challenges/01-front-end-development-certification/basic-javascript.json#L333) needs to be changed to:

```js
"(function(z){return 'difference = '+z;})(difference);"
```

#### Screenshot

Add Two Numbers with JavaScript

image

Subtract One Number from Another with JavaScript

image

Multiply Two Numbers with JavaScript

image

#### To Contributors

Only first time contributors to FreeCodeCamp can attempt this issue. Please first read the [contributing guidelines](https://github.com/FreeCodeCamp/FreeCodeCamp/blob/staging/CONTRIBUTING.md) before taking care of this issue. And feel free to visit the [Contributors Help](https://gitter.im/FreeCodeCamp/HelpContributors) chat room if you have any questions about helping. We're there to help.

### PR DESCRIPTION
**Pull request by aksinghdce**
#### Pre-Submission Checklist

- [x] Your pull request targets the `staging` branch of FreeCodeCamp.
- [x] Branch starts with either `fix/`, `feature/`, or `translate/` (e.g. `fix/signin-issue`)
- [x] You have only one commit (if not, [squash](https://github.com/FreeCodeCamp/FreeCodeCamp/wiki/Git-Squash) them into one commit).
- [x] All new and existing tests pass the command `npm run test-challenges`. Use `git commit --amend` to amend any fixes.
#### Type of Change

- [x] Small bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds new functionality)
- [ ] Breaking change (fix or feature that would change existing functionality)
- [ ] Add new translation (feature adding new translations)
#### Checklist:

- [x] Tested changes locally.
- [x] Closes currently open issue (replace 9481 with an issue no): Closes #9481

### CODE REVIEW

**Comment by aksinghdce** [comment]
Done :)

**Comment by raisedadead** [comment]
Hi @aksinghdce 

Thanks a lot for the fix and the pull request! 

Couple of points to note:

Can you replace the XXXX in the PR description with the issue no 9481.
> Closes currently open issue (replace XXXX with an issue no): Closes #*9481*

This will auto close the issue when this PR is accepted. Also next time do not mention the issue no in the branch name, rather have a short name like `fix/challenge-name`

**Comment by aksinghdce** [comment]
@raisedadead 
I noted your comments and changed the description.
Next time I will use appropriate branch name.

Thanks

**Comment by raisedadead** [comment]
@aksinghdce Thanks a lot for the changes.

#### :sparkles: :sparkles: **LGTM.** :sparkles: :sparkles: 

Congratulations for your first contribution to Free Code Camp, looking forward to more contributions in future.

Happy fixing!

**Pull request merged**
