### PR TITLE
Fix Empty editor and empty device preview

### LINKED ISSUE #12769: Empty editor and empty device preview
Challenge [make-typography-responsive](https://beta.freecodecamp.com/en/challenges/responsive-web-design/make-typography-responsive) has an issue.
User Agent is: <code>Mozilla/5.0 (Macintosh; Intel Mac OS X 10.9; rv:50.0) Gecko/20100101 Firefox/50.0</code>.

I'ts impossible to procede with this (Firefox, Chrome, Safari), i get a empty editor with a 'scan' white line and empty device preview

noway

```html
    
    
<style>

</style>

<h2>Importantus Ipsum</h2>
<p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Vivamus quis tempus massa. Aenean erat nisl, gravida vel vestibulum cursus, interdum sit amet lectus. Sed sit amet quam nibh. Suspendisse quis tincidunt nulla. In hac habitasse platea dictumst. Ut sit amet pretium nisl. Vivamus vel mi sem. Aenean sit amet consectetur sem. Suspendisse pretium, purus et gravida consequat, nunc ligula ultricies diam, at aliquet velit libero a dui.</p>

    ```

### PR DESCRIPTION
**Pull request by BhaveshSGupta**
#### Pre-Submission Checklist

- [x] Your pull request targets the `staging` branch of freeCodeCamp.
- [x] Branch starts with either `fix/`, `feature/`, or `translate/` (e.g. `fix/signin-issue`)
- [x] You have only one commit (if not, [squash](http://forum.freecodecamp.com/t/how-to-squash-multiple-commits-into-one-with-git/13231) them into one commit).
- [x] All new and existing tests pass the command `npm test`. Use `git commit --amend` to amend any fixes.

#### Type of Change

- [x] Small bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds new functionality)
- [ ] Breaking change (fix or feature that would change existing functionality)
- [ ] Add new translation (feature adding new translations)

#### Checklist:

- [x] Tested changes locally.
- [x] Closes currently open issue (replace XXXX with an issue no): Closes #12769

### CODE REVIEW

**Comment by BhaveshSGupta** [comment]
@systimotic

**Review by systimotic — CHANGES_REQUESTED** [review]
@BhaveshSGupta Thanks a lot for fixing this! 
I noticed that this same issue appears on a lot of other challenges. If you do a search in the seed folder for `"<ul>"`, you should find all of them.
I found: 
- Set the Font-size for Multiple Heading Elements
- Set the Font-weight for Multiple Heading Elements
- Make Elements Only Visible to a Screen Reader by Using Custom CSS
- Aligning Elements Using the Justify-content Property
- Aligning Elements Using the Align-items Property
- Using the Flex-wrap Property to Wrap a Row or Column
- The one you already fixed here, Making Typography responsive
- Define a Constructor Function

Could you change this pull request to fix all of these? That would be amazing!
If not, that's OK as well. In that case, let me know, and I'll double check this, merge it, and make sure the rest is taken care of.

**Comment by BhaveshSGupta** [comment]
Sure I would Love to work on them @systimotic

**Comment by BhaveshSGupta** [comment]
Let me create another pull request I have created blunders in this!! :D Sorry

**Comment by systimotic** [comment]
Hi @BhaveshSGupta! This looks great! Here's what I did to fix the git troubles:
- I ran `git pull --rebase upstream staging` to pull in the latest changes from the main repo.
- There were two commits by you left at the top. I squashed them into the top as per [our guide](https://forum.freecodecamp.com/t/how-to-squash-multiple-commits-into-one-with-git/13231)

I would've let you do this yourself, but I wasn't fully confident on whether what I thought you were supposed to do would actually work 🙂
I'll try to check whether all the challenges work correctly later today.

**Comment by systimotic** [comment]
Sorry for the massive delay! I've been having some issues with my local instance.

**Comment by BhaveshSGupta** [comment]
@systimotic its okay,

**Review by systimotic — APPROVED** [review]
# LGTM 🎉 
Thanks a bunch for contributing, for making changing to the PR and for being patient!

There are a couple of problems left:
- the styling of the lists is different
- there are still some empty paragraphs left

However, these are not issues related specifically to this PR. The empty paragraphs also occur for the `<hr>`'s, for example. I will open separate issues for these problems.

**Comment by systimotic** [comment]
Oh, I forgot to mention. Next time please stick to our [branch naming conventions](https://github.com/freeCodeCamp/freeCodeCamp/blob/staging/CONTRIBUTING.md#naming-your-branch). Here's a link with some tips on naming your commits: https://forum.freecodecamp.com/t/writing-good-git-commit-messages/13210

**Pull request merged**
