### PR TITLE
fix(curriculum): fixed the spelling error of 'attribute'

### LINKED ISSUE #49632: [Spelling error] - HTML Registration form project step 41
### Describe the Issue

For the first hint in the registration form project [step 41](https://www.freecodecamp.org/learn/2022/responsive-web-design/learn-html-forms-by-building-a-registration-form/step-41), attribute is spelled incorrectly here

Screen Shot 2023-03-08 at 1 03 20 PM

Here is the file you will need to work with
https://github.com/freeCodeCamp/freeCodeCamp/blob/main/curriculum/challenges/english/14-responsive-web-design-22/learn-html-forms-by-building-a-registration-form/60fad1cafcde010995e15306.md

**Only fix the spelling error in the first hint**

## Correct result
You should give the `input` expecting a first name a `name` attribute. _PS I would have chosen `first-name`_

## How to contribute
This is an easy fix so I am opening this up to `first timers only`

Please make sure you read [our guidelines for contributing](https://contribute.freecodecamp.org/#/), we prioritize contributors following the instructions in our guides. Join us in our discord room or the forum if you need help contributing, our moderators will guide you through this.

Sometimes we may get more than one pull-requests. We typically accept the most quality contribution followed by the one that is made first.

**Please note**
You do not need to ask to be assigned to the issue. It is open to any new contributor to the freeCodeCamp repo

Happy contributing.

### Affected Page

https://www.freecodecamp.org/learn/2022/responsive-web-design/learn-html-forms-by-building-a-registration-form/step-41

### PR DESCRIPTION
**Pull request by Mohwit**
Checklist:

- [ x] I have read and followed the [contribution guidelines](https://contribute.freecodecamp.org).
- [x ] I have read and followed the [how to open a pull request guide](https://contribute.freecodecamp.org/#/how-to-open-a-pull-request).
- [x ] My pull request targets the `main` branch of freeCodeCamp.
- [x] I have tested these changes either locally on my machine, or GitPod.

Closes #49632

### CODE REVIEW

**Review by Sboonny — APPROVED** [review]
#### :sparkles: :tada: **AWESOME!** :tada: :sparkles:

 Hi @Mohwit, thanks for this pull request and for contributing to the code-base for the first time. We are looking forward to more contributions from you in the future.

 Cheers & happy contributing!

**Comment by Mohwit** [comment]
@Sboonny Thanks for your words. I am also looking forward to contribute more soon.

**Review by jdwilkin4 — APPROVED** [review]
Congrats on your first contribution to our repository. 🎉
We look forward to future contributions. 👍

**Comment by Mohwit** [comment]
@jdwilkin4 Thanks!!

**Pull request merged**
