### PR TITLE
Media query solution for Responsive Web Design

### PR DESCRIPTION
**Pull request by Abimzy**
This is in response to the required solution for the challenge solution section.

- [x ] I have read [freeCodeCamp's contribution guidelines](https://github.com/freeCodeCamp/freeCodeCamp/blob/master/CONTRIBUTING.md).
- [x ] My pull request has a descriptive title (not a vague title like `Update index.md`)
- [x ] My pull request targets the `master` branch of freeCodeCamp.
- [ x] None of my changes are plagiarized from another source without proper attribution.
- [x ] My article does not contain shortened URLs or affiliate links.

If your pull request closes a GitHub issue, replace the XXXXX below with the issue number.

Closes #XXXXX

### CODE REVIEW

**Comment by RandellDawson** [comment]
Closed and Reopened this PR to attempt to resolve a specific Travis build failure.

**Comment by RandellDawson** [comment]
@ValeraS The build is failing with this following error, even though the solution you added seems to be correct.
>  1) Check challenges tests
       Create a Media Query
         Check tests against solutions
           Solution 1
             Your <code>p</code> element should have the <code>font-size</code> of 10px when the device <code>height</code> is less than or equal to 800px.:
     Your <code>p</code> element should have the <code>font-size</code> of 10px when the device <code>height</code> is less than or equal to 800px.

When the test runs, I believe test #1 (below) needs to be refactored to a be regular expression to make the determination the correct media query exists, because when the test runs during the build what screen size is being used?  Sounds like we need another PR to fix the test?  What are your thoughts?  I may be missing something obvious.

```
  - text: Your <code>p</code> element should have the <code>font-size</code> of 10px when the device <code>height</code> is less than or equal to 800px.
    testString: assert($('p').css('font-size') == '10px', 'Your <code>p</code> element should have the <code>font-size</code> of 10px when the device <code>height</code> is less than or equal to 800px.');
```

**Comment by ValeraS** [comment]
@RandellDawson In the client app tests run in an iframe, which by default has `width=300` and `height=150` and the test pass correctly. For tests in `nodejs`, we use `jsdom` which has limitations with layout. Because of this, the test can't pass.

we can try to replace `jsdom` with something else. For example, PhantomJS.

Refactor the test can help too but the second test checks for the correct media query.

**Comment by RandellDawson** [comment]
So we can not merge this PR with a solution yet until we figure out how to test it correctly, because it would cause all PRs to fail for this same reason.  Correct?

**Comment by ValeraS** [comment]
@RandellDawson Correct.

PhantomJS development is suspended until further notice. https://github.com/ariya/phantomjs/issues/15344

**Comment by RandellDawson** [comment]
@ValeraS Should I put a block label on this one for now?

**Comment by RandellDawson** [comment]
I have successfully tested the added solution locally.  LGTM

**Review by RandellDawson — APPROVED** [review]

**Review by ezioda004 — APPROVED** [review]

**Comment by ezioda004** [comment]
Thank you @Abimzy for your contribution. Looking forward to more contributions from you! 🎉

**Pull request merged**
