### PR TITLE
fix(curriculum): Fix awkward phrasing

### LINKED ISSUE #49354: rewrite awkward JS course step: escape-sequences-in-strings
### Describe the Issue

In this challenge https://www.freecodecamp.org/learn/javascript-algorithms-and-data-structures/basic-javascript/escape-sequences-in-strings 
The sentences that come before the table are awkwardly phrased. (for eg this one: There are two reasons to use escaping characters.) 
Discussed on discord with @jeremylt and he suggested the following rewrite:
Quotes are not the only characters that can be escaped inside a string. Escape sequences allow you to use characters you may not otherwise be able to use in a string.

(basically this replaces all the text above the table in a concise and still clear way)

### Affected Page

https://www.freecodecamp.org/learn/javascript-algorithms-and-data-structures/basic-javascript/escape-sequences-in-strings

### Your code

```

```

### Expected behavior

replace the text that comes before the table with the suggested string

### Screenshots

_No response_

### System

N/A

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by Sriparno08**
Checklist:

- [x] I have read and followed the [contribution guidelines](https://contribute.freecodecamp.org).
- [x] I have read and followed the [how to open a pull request guide](https://contribute.freecodecamp.org/#/how-to-open-a-pull-request).
- [x] My pull request targets the `main` branch of freeCodeCamp.
- [x] I have tested these changes either locally on my machine, or GitPod.

Closes #49354

### CODE REVIEW

**Review by hbar1st — COMMENTED** [review]
"We learned this.." should be deleted also.

**Comment by Sriparno08** [comment]
Okay, @hbar1st 👍

**Review by jeremylt — APPROVED** [review]
LGTM

**Review by gikf — APPROVED** [review]
LGTM :+1:

**Pull request merged**
