### PR TITLE
Clarify description of change text inside an element using jquery

### LINKED ISSUE #8868: Challenge 109 - Replace Text "replace with." with "replace."
#### Challenge Name

https://www.freecodecamp.com/challenges/change-text-inside-an-element-using-jquery

#### Issue Description

Possible error in diction in text.  Suggest replacing "replace with." with "replace."

#### Browser Information

Not relevant.

* Browser Name, Version: 
* Operating System: 
* Mobile, Desktop, or Tablet: 

#### Your Code

```js
// If relevant, paste all of your challenge code in here

```

### PR DESCRIPTION
**Pull request by WillySchu**
#### Pre-Submission Checklist

- [x] Your pull request targets the `staging` branch of FreeCodeCamp.
- [ ] Branch starts with either `fix/`, `feature/`, or `translate/` (e.g. `fix/signin-issue`)
- [x] You have only one commit (if not, [squash](https://github.com/FreeCodeCamp/FreeCodeCamp/wiki/git-rebase#squashing-multiple-commits-into-one) them into one commit).
- [x] All new and existing tests pass the command `npm run test-challenges`. Use `git commit --amend` to amend any fixes.
#### Type of Change

- [x] Small bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds new functionality)
- [ ] Breaking change (fix or feature that would change existing functionality)
- [ ] Add new translation (feature adding new translations)
#### Checklist:

- [x] Tested changes locally.
- [x] Closes currently open issue (replace XXXX with an issue no): Closes #8868 
#### Description

Edited by @raisedadead

### CODE REVIEW

**Comment by raisedadead** [comment]
@WillySchu thanks for your contribution, looks like this is your first one! So welcome to contributing.

However, we need certain things to be addressed, can you make the PR title a bit more specific:
> Clarify description of change text inside an element using jquery

Next the markup for the issue checklist needs to be completed, you can directly click the check boxes or edit them `[x]` (there is no space in between the brackets)

Also replace the XXXX in the closes tag, this way it will be cross referenced and GitHub will automatically close the issue #8868 when your pull request is merged.

As always, if you need any assistance reach out to the [Contributors Chat room](https://gitter.im/FreeCodeCamp/HelpContributors).

**Comment by raisedadead** [comment]
Most importantly please ensure you test things locally.

**Comment by erictleung** [comment]
@WillySchu thanks again for your PR. Do you mind updating your PR with the suggestions made above? Once you complete those, we'll be able to merge your PR.

**Comment by atjonathan** [comment]
@WillySchu, any update on this?

**Comment by raisedadead** [comment]
@atjonathan please merge after a QA, I have tested locally.

**Comment by atjonathan** [comment]
#### **LGTM :+1:**
Thanks for contributing :tada:

**Pull request merged**
