### PR TITLE
fix(curriculum): changing Charles -> Ada in JavaScript challenge descriptions

### LINKED ISSUE #42262: Minor Naming inconsistency and Clarification
Challenges
---

1) https://www.freecodecamp.org/learn/javascript-algorithms-and-data-structures/basic-javascript/use-bracket-notation-to-find-the-nth-character-in-a-string
2) https://www.freecodecamp.org/learn/javascript-algorithms-and-data-structures/basic-javascript/use-bracket-notation-to-find-the-last-character-in-a-string
3) https://www.freecodecamp.org/learn/javascript-algorithms-and-data-structures/basic-javascript/use-bracket-notation-to-find-the-nth-to-last-character-in-a-string
4) https://www.freecodecamp.org/learn/javascript-algorithms-and-data-structures/basic-javascript/find-the-length-of-a-string

Issue
---
In the first challenge listed (1), we use `Ada Lovelace` as our sample person.
In the second (2) and third (3), we use a non-existent 'Charles Lovelace'. 

**Question 1**:
What do we think about updating (2) and (3) to reference Ada Lovelace instead of this random name?

**Question 2**:
Also, there is at least one camper that got confused and thought we were talking about Linda Lovelace (never heard of her before today).
https://forum.freecodecamp.org/t/varible-name-choice-in-javascript-intro-lesson/462078/2

What do we think about modifying the starter code in all 4 linked challenges to make it painfully obvious that we are *not* talking about a pornographic actress?
```javascript
// Setup
var firstName = "Ada";
var lastName = "Lovelace";

// Only change code below this line
var thirdLetterOfLastName = lastName; // Change this line
```

### PR DESCRIPTION
**Pull request by RebekahKoon**
Checklist:

- [x] I have read [freeCodeCamp's contribution guidelines](https://contribute.freecodecamp.org).
- [x] My pull request has a descriptive title (not a vague title like `Update index.md`)
- [x] My pull request targets the `main` branch of freeCodeCamp.
- [x] I have tested these changes either locally on my machine, or GitPod.

Closes #42262

I changed coding challenge descriptions that use the name "Charles" to "Ada" to improve consistency between the challenges. I tested the changes locally and everything seems to be working correctly.

### CODE REVIEW

**Review by gikf — DISMISSED** [review]
Looks good! :+1:

**Review by PrashantSakre — DISMISSED** [review]
LG 👍

**Comment by Sembauke** [comment]
Hey @gikf, @RebekahKoon,

I think they changed the name from Ada to Charles because the name was too short for the next example. 

This sentence does not make much sense now,

> For example, you can get the value of the third-to-last letter of the `var firstName = "Ada"` string by using `firstName[firstName.length - 3]`

Would just be the first letter

**Comment by RebekahKoon** [comment]
Hi @Sembauke! Yes, that's a good point and I was wondering about that. I just did some research on Ada Lovelace and discovered her full name is Augusta Ada, so for that particular example perhaps firstName could be changed to Augusta?

**Comment by gikf** [comment]
Technically that's not wrong :slightly_smiling_face:, but example with longer name/word indeed might be better for emphasizing the concept. Some other option could be explicitly pointing out, that in the example that's just a first letter.

**Comment by raisedadead** [comment]
Hey @jeremylt, Could you weigh in on this conversation, please?

**Comment by jeremylt** [comment]
Personally, I like the "Agusta Lovelace" approach.

**Comment by Sembauke** [comment]
> Personally, I like the "Agusta Lovelace" approach.

Let's go with that @RebekahKoon

**Comment by RebekahKoon** [comment]
> > Personally, I like the "Agusta Lovelace" approach.
> 
> Let's go with that @RebekahKoon

Okay, thank you! I made a new commit with these changes!

**Review by gikf — APPROVED** [review]

**Review by raisedadead — APPROVED** [review]
#### :sparkles: :sparkles: **AWESOME! LGTM.** :sparkles: :sparkles: 

Thanks, @RebekahKoon, for this pull request and for contributing to the code-base for the first time.

We will be looking forward to more contributions in future.

Cheers and happy contributing!

**Pull request merged**
