### PR TITLE
Fix Bonfire: Find Largest Number in Array - Bad Test

### PR DESCRIPTION
**Pull request by SaintPeter**
There were a couple of problems with the tests on Find Largest Number in Array:
1. Missing expect command.
2. expect().should.eql() was not working

I was ultimately unable to get `expect().should.eql()` working, so I went with `assert.deepEqual`.
I have tested this code against my local install and it seems to be working properly.

I can't figure out how to make my commit history clean, but it's only altering a single file.

### CODE REVIEW

**Comment by SaintPeter** [comment]
Error message is:
'Cannot read a property 'eql' of undefined'

**Comment by abhisekp** [comment]
@SaintPeter nice. @benmcmahon100 suggests to use `assert`.
They're trying to replace `expect` with `assert`.
If you could do that with all the test cases, then we would all be grateful. :smiley:

**Comment by SaintPeter** [comment]
I was unable to get assert to work.  I'll give it another go.

**Comment by natac13** [comment]
I was able to submit a pull request with the assert statement #2885

**Comment by BerkeleyTrue** [comment]
@SaintPeter Can you squash the commit messages? PM if you need help

**Comment by SaintPeter** [comment]
@BerkeleyTrue I cannot, and oh lord I've tried.  I need serious help to get my fork back in order.

@dting submitted #2575, which fixes not only this, but replaces all of the `expect` tests with `assert`.  Better to accept that one and close this out.

**Comment by BerkeleyTrue** [comment]
We will merge this in as it fixes the issue. @benmcmahon100 is going to attempt to clean up the commit messages.

**Pull request closed without merging**
