### PR TITLE
Fixed YouTube broken link in Request Header Parser Microservice

### LINKED ISSUE #9330: Request Header Parser Microservice Video Broken
Challenge [Request Header Parser Microservice](https://www.freecodecamp.com/challenges/request-header-parser-microservice) has an issue.
User Agent is: <code>Mozilla/5.0 (Windows NT 6.1; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/51.0.2704.103 Safari/537.36</code>.
Please describe how to reproduce this issue, and include links to screenshots if possible.

Hi,
Link to video is broken, think its missing an "_" in the parameter v=

Here is a link to screenshot http://pasteboard.co/1U6ADlKp.png

And the link to youtube working video 
https://www.youtube.com/watch?v=_0oqjSkGoHg

Regards

### PR DESCRIPTION
**Pull request by ghost**
#### Pre-Submission Checklist

- [x] Your pull request targets the `staging` branch of FreeCodeCamp.
- [x] Branch starts with either `fix/`, `feature/`, or `translate/` (e.g. `fix/signin-issue`)
- [x] You have only one commit (if not, [squash](https://github.com/FreeCodeCamp/FreeCodeCamp/wiki/git-rebase#squashing-multiple-commits-into-one) them into one commit).
- [ ] All new and existing tests pass the command `npm run test-challenges`. Use `git commit --amend` to amend any fixes.
#### Type of Change

- [x] Small bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds new functionality)
- [ ] Breaking change (fix or feature that would change existing functionality)
- [ ] Add new translation (feature adding new translations)
#### Checklist:

- [ ] Tested changes locally.
- [x] Closes currently open issue (replace XXXX with an issue no): Closes #9330 
#### Description

The challengeseed didn't had the underscore at the start, causing error in embedding youtube video.

Made proper changes adhering to guidelines

### CODE REVIEW

**Comment by DG000gl** [comment]
GL
24.06.2016 1:51 пользователь "pradyumna1" <notifications@github.com>
написал:

**Comment by raisedadead** [comment]
@pradyumna1 thanks for the PR, can you please edit the commit and PR title to remove the issue nos.

> Fixed youtube broken link as mentioned in issue #9330

to

> Fixed YouTube broken link in Request Header Parser Microservice

`git commit --amend` && `git push origin --force`

Also change the PR title, with the Edit option on the top of this page.

Refer : [Guidelines for Contributing](https://github.com/FreeCodeCamp/FreeCodeCamp/blob/staging/CONTRIBUTING.md).

**Comment by pradyumna1** [comment]
Ok Mrugesh, I will do it today evening.

**Comment by QuincyLarson** [comment]
@pradyumna1 excellent - thank you for fixing this!

**Pull request merged**
