### PR TITLE
Translation to spanish of bigonotation

### LINKED ISSUE #6996: Translation to Spanish: Add translation of bigonotation.json
- [x] Big O Notation: What It Is and Why You Should Care
- [x] Big O Notation: A Few Examples

### PR DESCRIPTION
**Pull request by vtamara**
Closes #6996

### CODE REVIEW

**Comment by vtamara** [comment]
Please still don't check this one, because I made mistake and I translated without noticing that @jherna37 had asked to translate this one.  Let's wait 7 days to allow @jherna37 to send his pull request (if he sends I will close this one,).

**Comment by QuincyLarson** [comment]
@vtamara did you hear back from @jherna37? We want to merge this ASAP :)

**Comment by jherna37** [comment]
Hey, sorry about the delay. But I've already submitted the pull request.

**Comment by ltegman** [comment]
@jherna37 You submitted the PR against your own fork. You need to be making a PR against the FCC repo.

**Comment by jherna37** [comment]
So from the new pull request page. the base is "fccimg"? I apologize as I am new to github.

**Comment by ltegman** [comment]
@jherna37 The base fork should be `FreeCodeCamp/FreeCodeCamp` and the base branch should be `staging`

**Comment by jherna37** [comment]
Hopefully now I've performed the proper steps.

**Comment by ltegman** [comment]
@jherna37 You still made the PR against your own fork. Try initiating the PR from the main FreeCodeCamp repo.

**Comment by jherna37** [comment]
I made another attempt from the main repo page. What am I using to compare?

**Comment by vtamara** [comment]
@jherna37 I see in your repo that you tried to translate the HTML instead of translating the sources in JSON. I invite you to the spanish chat room: https://gitter.im/AlexTrapp/FreeCodeCampEspa%C3%B1ol  Also please check how to start a translation at https://github.com/vtamara/fcc_trad/blob/master/Recomendaciones.md

**Comment by BerkeleyFalse** [comment]
@vtamara updated the pull request.

**Comment by BerkeleyFalse** [comment]
@vtamara updated the pull request.

**Comment by ltegman** [comment]
:+1:

**Pull request merged**
