### PR TITLE
chore(i8n,learn): processed translations

### PR DESCRIPTION
**Pull request by RandellDawson**
Latest curriculum translations

### CODE REVIEW

**Comment by RandellDawson** [comment]
@nhcarrigan Why is the `has-translation` action failing?

**Comment by nhcarrigan** [comment]
Possibly one of the suggestions I committed during the review for that flow.

https://github.com/freeCodeCamp/freeCodeCamp/pull/41199 will revert the suggestions and remove the unneeded `if` check in the YAML section, bringing it back to parity with my confirmed working version on my test repo.

**Comment by nhcarrigan** [comment]
@RandellDawson all better - thanks @ojeytonwilliams 😁

**Review by naomi-lgbt — APPROVED** [review]
Looks good to me. Will circle back and merge when CI passes.

**Pull request merged**
