### PR TITLE
fix(curriculum): Challenge: Iterate through an array with a for loop (Make test and requirements stricter)

### LINKED ISSUE #45041: Challenge: Iterate through an array with a for loop (Make test and requirements stricter)
This challenge can be passed with incorrect code. It does not check that the array elements are added to `total`.

```
var total = 0;
for (total; total < 20; total += myArr[0]) { }
```

```
var total = 0;
for (var i = 0; i <= 20; i++) {
  myArr[0];
  total = i;
}
```

```
var total = 0;
for (var i = 0; i <= myArr[3] * 4; i++) {
 total = i;
}
```

The requirements should probably be stricter and expect either `total += myArr[i]` or `total = total + myArr[i]` to be inside the body of the for loop (without forcing the iterator variable name to be `i`).

---

Challenge: https://www.freecodecamp.org/learn/javascript-algorithms-and-data-structures/basic-javascript/iterate-through-an-array-with-a-for-loop

Test: https://github.com/freeCodeCamp/freeCodeCamp/blob/main/curriculum/challenges/english/02-javascript-algorithms-and-data-structures/basic-javascript/iterate-through-an-array-with-a-for-loop.md

Forum post: https://forum.freecodecamp.org/t/iterate-through-an-array-with-a-for-loop-challenge-help/495925

### PR DESCRIPTION
**Pull request by HenMoshe**
Checklist:

- [x] I have read [freeCodeCamp's contribution guidelines](https://contribute.freecodecamp.org).
- [x] My pull request has a descriptive title (not a vague title like `Update index.md`)
- [x] My pull request targets the `main` branch of freeCodeCamp.
- [x] I have tested these changes either locally on my machine, or GitPod.

Closes #45041

changed the bear minimum in order to strict tests while not changing wider editor context. :)

### CODE REVIEW

**Review by gikf — COMMENTED** [review]
I've tried examples from the issue, and some proper solutions. It works for these cases well.

I wonder if it wouldn't be good to still make test slightly more precise. That is:
- `myArr.length` is within `( )` on the line with `for`
- `myArr[` is within `{ }`
- `total +=` or `total = total +` is within `{ }`

**Comment by HenMoshe** [comment]
Hey Buddy, sorry for late response as Ive been very busy lately :) 
I'll work on making it stricter as you requested.
Thank you very much.

**Comment by raisedadead** [comment]
@HenMoshe how is it going? If you are not working on this, please let us know and we will let someone else continue :)

**Comment by Sembauke** [comment]
Hey Thank you for opening this pr, it seems you are no longer working on this. Feel free to reopen the pr if you wish.

Otherwise we will open this to other contributors.

**Pull request closed without merging**
