### PR TITLE
Remove leftover question from JavaScript Lingo challenge

### LINKED ISSUE #6781: Some problems with video challenges
**1.** After answering a question, the answer remains highlighted in the next question.

image

**2.** ~~Reference to Hikes upon challenge completion.~~ [Fixed]

**3.** Large gaps in the video description.

image

**4.** Clicking on "View this challenge" on my code portfolio for one of my completed video challenges redirects me to the map.

### LINKED ISSUE #6826: JavaScript Lingo: MDN and Documentation Question issue.
Going though the new Video Challenge and question 3 on JavaScript Lingo MDN and Documentation doesn't seem to be there. Though clicking true answers it correctly, while false gives me the wrong answers animation.   

screen shot 2016-02-08 at 12 50 34

### LINKED ISSUE #6889: Video Challenges- JavaScript Lingo- Question 3
Video Challenges-
JavaScript Lingo: MDN and Documentation
[Question 3
](http://www.freecodecamp.com/videos/javascript-lingo-mdn-and-documentation)

The title and question for this part only states Question 3 with a passing answer of True. 
Question should be removed or updated.

### PR DESCRIPTION
**Pull request by raisedadead**
This commit removes the leftover question from the JavaScript Lingo challenge
Tested locally.

closes #6826

### CODE REVIEW

**Comment by raisedadead** [comment]
Saw this in one of my earlier PR's, thought to fix while I was at it:

ci

**Comment by W12S12E12** [comment]
master of
https://github.com/kRen0/Q-A-PyroCMS-module/commit/2df12348927ec86f1ff801d07848134c485ab643

2016-02-11 13:25 GMT+01:00 Mrugesh Mohapatra <notifications@github.com>:

**Comment by W12S12E12** [comment]
more in china http://www.codeforge.cn/read/125533/time-challenge.html__html

**Comment by raisedadead** [comment]
Yikes I messed up that merging. On it.

**Comment by raisedadead** [comment]
Reopening

**Comment by raisedadead** [comment]
Done. This PR is good to go.

**Comment by bugron** [comment]
@raisedadead this PR doesn't close `#6781` so I've removed it from your first comment.

**Comment by raisedadead** [comment]
@bugron Apologies, It was an oversight by me. Thanks for pointing out.

**Comment by ltegman** [comment]
:+1:

**Pull request merged**
