### PR TITLE
fix: add tests for header parser microservice project

### PR DESCRIPTION
**Pull request by moT01**
- [x] I have read [freeCodeCamp's contribution guidelines](https://github.com/freeCodeCamp/freeCodeCamp/blob/master/CONTRIBUTING.md).
- [x] My pull request has a descriptive title (not a vague title like `Update index.md`)
- [x] My pull request targets the `master` branch of freeCodeCamp.
- [x] None of my changes are plagiarized from another source without proper attribution.
- [x] All the files I changed are in the same world language (for example: only English changes, or only Chinese changes, etc.)
- [x] My changes do not use shortened URLs or affiliate links.

### CODE REVIEW

**Review by jenlky — APPROVED** [review]

**Review by ojeytonwilliams — APPROVED** [review]
LGTM :+1:

**Comment by RandellDawson** [comment]
@moT01 I have reviewed this PR.  Should we check to make sure the values of each property have something in them or just in case one of them is an empty string (maybe blocked), we still want them to pass?

**Comment by RandellDawson** [comment]
@moT01 Any thoughts regarding my last comment?

**Comment by moT01** [comment]
I changed them around slightly @RandellDawson. Should be a little better anyway.

**Review by RandellDawson — APPROVED** [review]

**Comment by RandellDawson** [comment]
Thank you for your contribution to the page! 👍
We're happy to accept these changes, and look forward to future contributions. 🎉

**Pull request merged**
