### PR TITLE
Corrected wording in refactor global variables challenge

### LINKED ISSUE #17853: Misuse of word `Refactor` in FP lesson
#### Describe your problem and - if possible - how to reproduce it
In the sentence, **"Refactor (rewrite) the code so the global array bookList is not changed inside either function,"** the use of the word "refactor" is incorrect, and should simply be replaced with "rewrite". This is because to "refactor" is:

> Code refactoring is the process of restructuring existing computer code—changing the factoring—without changing its external behavior

But in this instance, you're going from mutability to immutability which does change the external behavior, so as such, I believe that "rewrite" is a better descriptor than "refactor", which are certainly not interchangeable in this case, as per the use of _"(rewrite)"_.

#### Add a Link to the page with the problem
https://learn.freecodecamp.org/javascript-algorithms-and-data-structures/functional-programming/refactor-global-variables-out-of-functions

#### Tell us about your browser and operating system

* Browser Name: Chrome
* Browser Version: Version 67.0.3396.99 (Official Build) (32-bit)
* Operating System: Chrome OS

### PR DESCRIPTION
**Pull request by thecodingaviator**
- [x] I have read [freeCodeCamp's contribution guidelines](https://github.com/freeCodeCamp/freeCodeCamp/blob/master/CONTRIBUTING.md).
- [x] My pull request has a descriptive title (not a vague title like `Update index.md`)
- [x] My pull request targets the `master` branch of freeCodeCamp.
- [x] None of my changes are plagiarized from another source without proper attribution.
- [x] My article does not contain shortened URLs or affiliate links.
If your pull request closes a GitHub issue, replace the XXXXX below with the issue number.

Closes #17853

### CODE REVIEW

**Comment by moT01** [comment]
Thank you for your contribution, but nothing here is incorrect - and this doesn't appear to improve anything.

**Comment by thecodingaviator** [comment]
@moT01 In my opinion, the word refactor means different than rewrite. Refactor is shortening it and making it less redundant while rewriting maybe anything

**Comment by moT01** [comment]
I'm convinced, I think this is better and shorter.

**Review by huyenltnguyen — APPROVED** [review]
@thecodingaviator Thank you for the PR! ✨ 🎉 Happy coding!

**Pull request merged**
