### PR TITLE
feat(tools): use camperbot for commit

### PR DESCRIPTION
**Pull request by naomi-lgbt**
Checklist:

- [X] I have read [freeCodeCamp's contribution guidelines](https://contribute.freecodecamp.org).
- [X] My pull request has a descriptive title (not a vague title like `Update index.md`)
- [X] My pull request targets the `main` branch of freeCodeCamp.
- [X] All the files I changed are in the same world language, for example: only English changes, or only Chinese changes, etc.

Closes #XXXXX

As noted in [the last PR](https://github.com/freeCodeCamp/freeCodeCamp/pull/41617#issuecomment-809350605), there are issues with using the GitHub Actions credentials when creating the commit. The Crowdin GitHub action pre-sets the git config and doesn't accept a flag to change it, so this PR adds a step to the workflow to modify the git config and create the commit manually.

I've added camperbot's email to the repository secrets.

### CODE REVIEW

**Comment by raisedadead** [comment]
I believe you should only be needing to change https://github.com/freeCodeCamp/freeCodeCamp/pull/41659/files#R47 to camperbot's PAT and none of the other changes are required.

**Comment by nhcarrigan** [comment]
That link doesn't seem to point to anything specific on my end.

However, I did test by passing the PAT to the download steps instead of the GitHub Token, and because the Crowdin action has hard-coded git credentials into their workflow it still commits as the Crowdin Bot - that was what caused the auto-approve to revert in the other PR.

**Comment by raisedadead** [comment]
My apologies, I see that we use:

https://github.com/freeCodeCamp/freeCodeCamp/blob/6b4a6a02568b809fc216ea8566ff5df446d1da4e/.github/workflows/crowdin-i18n-curriculum-download.yml#L47

which is the default GitHub actions bot. I am recommending we use the PAT from camperbot instead? I might be mistaken. That way the PR is created by a user account (with write access) and hence has the ability to trigger the CI all the time.

The email credentials do not matter. They should be fine whatever they use on the action.

**Comment by nhcarrigan** [comment]
The action itself doesn't use that token to generate the commit though. It generates with hard-coded credentials.

https://github.com/crowdin/github-action/blob/master/entrypoint.sh#L113

So even when I pass my own bot account's PAT to that value in the action, I still get a commit from the Crowdin Support bot, which doesn't have the write access needed.

**Comment by raisedadead** [comment]
Ah, that's a disappointment - although it does make sense now. Thanks for testing this out though.

**Review by raisedadead — APPROVED** [review]

**Review by ojeytonwilliams — COMMENTED** [review]
Just to confirm I understand the logic.

1. Check out fcc main
2. Download translations
3. Create new branch on fcc/fcc
4. Commit the translations
5. Create a PR from new branch

3\. and 4\. being handled in a new way because the old way failed.

Is that about right?

**Review by ojeytonwilliams — APPROVED** [review]
Great, thanks for confirming.

**Comment by ojeytonwilliams** [comment]
@RandellDawson did you want to take a look before we merge?

**Pull request merged**
