### PR TITLE
[Guide] Functional Programming: Sort an Array Alphabetically using th…

### PR DESCRIPTION
**Pull request by lednhatkhanh**
…e sort Method. Fixes and enhancements.

- [x] I have read [freeCodeCamp's contribution guidelines](https://github.com/freeCodeCamp/freeCodeCamp/blob/master/CONTRIBUTING.md).
- [x] My pull request has a descriptive title (not a vague title like `Update index.md`)
- [x] My pull request targets the `master` branch of freeCodeCamp.
- [x] None of my changes are plagiarized from another source without proper attribution.
- [ ] All the files I changed are in the same world language (for example: only English changes, or only Chinese changes, etc.)
- [x] My changes do not use shortened URLs or affiliate links.

### CODE REVIEW

**Comment by RandellDawson** [comment]
@lednhatkhanh You check the box:
> All the files I changed are in the same world language (for example: only English changes, or only Chinese changes, etc.)

However, your PR affects multiple language files.  I am closing this PR, so that you can create a separate PR for each language.

Thank you.

**Comment by lednhatkhanh** [comment]
@RandellDawson  I checked that by mistake, just unchecked it now, is it ok now?

**Comment by RandellDawson** [comment]
@lednhatkhanh   In general, you should always check every box, because you are telling us that your PR meets all of the requirements. The checkbox is  a double-check for you that you have met all the requirements FCC asks of pull requests.

Technically, every place where you have:
>// Add your code above this line

it should be a translation.  So technically, this PR should be broken into 6 different PRs as that comment should be translated to each language.

**Comment by lednhatkhanh** [comment]
Then I will close this and create a new one.

**Pull request closed without merging**
