### PR TITLE
fix: unreadable text in night mode

### LINKED ISSUE #51785: Unreadable text in a table in Nigth Mode
### Describe the Issue

On the **JavaScript Algorithms and Data Structures** challlenge **Escape Sequences in Strings** 
 https://www.freecodecamp.org/learn/javascript-algorithms-and-data-structures/basic-javascript/escape-sequences-in-strings, a table doent display all the element in Nigth Mode.

### Affected Page

https://www.freecodecamp.org/learn/javascript-algorithms-and-data-structures/basic-javascript/escape-sequences-in-strings

### Your code

```



```
;

### Expected behavior

;

### Screenshots

Dark mode
Ligth mode

### System

- Device: [e.g. iPhone 6, Laptop]
- OS: [e.g. iOS 14, Windows 10, Ubuntu 20.04]
- Browser: [e.g. Chrome, Safari]
- Version: [e.g. 22]

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by FarisKarim**
Checklist:

- [X] I have read and followed the [contribution guidelines](https://contribute.freecodecamp.org).
- [X] I have read and followed the [how to open a pull request guide](https://contribute.freecodecamp.org/#/how-to-open-a-pull-request).
- [X] My pull request targets the `main` branch of freeCodeCamp.
- [X] I have tested these changes either locally on my machine, or GitPod.

Closes #51785 

New look (--tertiary-background):

 
Screenshot_2023-10-05_at_11 36 43_AM
Screenshot_2023-10-05_at_11 36 57_AM

### CODE REVIEW

**Comment by naomi-lgbt** [comment]
Thanks for your interest in contributing.

The linked issue has not been triaged or opened for contribution yet.

**Comment by Sboonny** [comment]
@FarisKarim, the issue has been triaged, if you need help head to our discord.

---

Can you sync this branch with main, a commit that fix the failing test are in place there.

**Comment by lasjorg** [comment]
We still want the striped style right? Not sure if we want it to be the default or what?


`client/src/components/layouts/global.css`

```
.challenge-instructions table tr:nth-of-type(odd) {
  color: var(--secondary-color);
  background-color: var(--tertiary-background);
}
```

**Comment by FarisKarim** [comment]
^^^ Was also wondering that, is the above styles fine or did we want different shades depending on light and night mode. Think someone mentioned `background-quaternary` for night mode and `background-tertiary` for light?

**Comment by lasjorg** [comment]
The color contrast looks good as far as I can tell (Axe DevTools also do not complain).

**Review by WilliamSpanfelner — COMMENTED** [review]
Just applied this rule locally.  It also fixes a similar table issue at: [Cash Register project](https://www.freecodecamp.org/learn/javascript-algorithms-and-data-structures/javascript-algorithms-and-data-structures-projects/cash-register).  This stands to reason as the amendment is to global.css which intuitively, should apply to all tables sharing this styling. Nice work.

**Review by Sboonny — APPROVED** [review]
#### :sparkles: :tada: **AWESOME!** :tada: :sparkles:

 Hi @FarisKarim, thanks for this pull request and for contributing to the code-base for the first time. We are looking forward to more contributions from you in the future.

 Cheers & happy contributing!

**Review by lasjorg — APPROVED** [review]
LGTM

**Pull request merged**
