### PR TITLE
fix(tools): enable eslint for circular dependency check

### LINKED ISSUE #45307: Circular dependency detected
In https://github.com/freeCodeCamp/freeCodeCamp/issues/45277#issuecomment-1056210055 @Jagrutiti found that there are several circular dependencies between the redux sagas and reducers.  Since these can be sources of subtle and confusing bugs, it would be good if these cycles could be broken.

### PR DESCRIPTION
**Pull request by Jagrutiti**
Checklist:

- [x] I have read [freeCodeCamp's contribution guidelines](https://contribute.freecodecamp.org).
- [x] My pull request has a descriptive title (not a vague title like `Update index.md`)
- [x] My pull request targets the `main` branch of freeCodeCamp.
- [x] I have tested these changes either locally on my machine, or GitPod.

Closes #45307

### CODE REVIEW

**Comment by raisedadead** [comment]
This has been sitting here for a while, what is the next conclusive step?

**Comment by ojeytonwilliams** [comment]
We can either allow warnings while we fix this or wait until the circular dependencies are fixed.

We could leave them unfixed, but when they do cause bugs they're confusing ones.

**Comment by Jagrutiti** [comment]
Let me know what you want me to do in this.

**Comment by raisedadead** [comment]
Thanks, @Jagrutiti I am closing this now to clear up the queue because we will not be merging this anytime soon.

We clearly do not want to just see warnings and errors without fixing them at the same time.

Thanks again for your work on this and we look forward to more contributions from you in the future.

Happy Coding.

**Pull request closed without merging**
