### PR TITLE
Fix: add loop-protection to challenges

### PR DESCRIPTION
**Pull request by ojeytonwilliams**
This is https://github.com/freeCodeCamp/freeCodeCamp/pull/37841 MKII.  The original PR failed because anonymous functions were being passed into the `loop-protect` plugin. The old version of `loop-protect` detected anonymous functions by checking if they `toString`ed to `function (`, but our anonymous functions did not have that space (no idea why!).  This broke the plugin and thus the js challenges.

Note for anyone QAing this: the original problem only appeared when the client was built (the dev server does not anonymise the functions).

### CODE REVIEW

**Comment by raisedadead** [comment]
Hi @RandellDawson I would like to confirm if you are happy with this, this time around. We would like to push this up if you are okay. I am planning to land this in the next couple days.

**Review by RandellDawson — COMMENTED** [review]
@ojeytonwilliams I have tested this locally and using GitPod and if I paste the following code in for the Iterate with JavaScript While Loops challenge, it does properly warn about a possible infinite loop.  However, it still does not warn about an infinite loop when the Run the Tests button is click for the same code for the challenge.  One of the main points of the PR was getting the Run the Tests button to still show the same error.  

This really needs to be resolved in such a way, so no matter what machine the same code is written on, it should give repeatable error messages.  Otherwise things will become very confusing for those trying to help and/or those trying to receive the help on the forum.

**Comment by ojeytonwilliams** [comment]
Thanks Randell, you're right. It's not working for 'Iterate with JavaScript While Loops' if the following code is used:
```js
console.log('start');
// Setup
var myArray = [];

// Only change code below this line.
var i = 0;
while(i < 5) {
  myArray.push(1);
  i--;
}

console.log('end');
```

We should see 
```
start
Potential infinite loop detected on line 7. Tests may fail if this is not changed.
end
```
in both consoles, but it's not appearing in the fcc console.  The problem seems to be the test: it tries to use `deepEqual` on a massive array, takes too long and the test times out.  This prevents the logs from appearing, though I don't understand why.

`loop-protect` is doing its job, though, it's just what happens after that's the problem.

@raisedadead I think this PR is a net positive (it does reduce the chance of crashing), but Randell's quite right that the logging is not working as desired.  I will have some time to look at this soon, but I'm not sure how long it will take to fix.

**Comment by RandellDawson** [comment]
@raisedadead After thinking about it a bit more, the main thing this PR will protect against is the browser crashing.  It does that, so I say for now we merge this PR but create a new issue that focuses specifically on the issue of when the `Run Tests` button is clicked, that the applicable infinite loop warning message does not appear.

**Review by raisedadead — APPROVED** [review]

**Comment by RandellDawson** [comment]
[This challenge](https://www.freecodecamp.org/learn/javascript-algorithms-and-data-structures/debugging/understanding-the-differences-between-the-freecodecamp-and-browser-console) will probably need to be updated once this PR is merged.

**Pull request merged**
