### PR TITLE
fix: render editor tabs if SHOW_UPCOMING_CHANGES is 'true'

### PR DESCRIPTION
**Pull request by ahmaxed**
- [x] I have read [freeCodeCamp's contribution guidelines](https://contribute.freecodecamp.org).
- [x] My pull request has a descriptive title (not a vague title like `Update index.md`)
- [x] My pull request targets the `master` branch of freeCodeCamp.
- [x] All the files I changed are in the same world language, for example: only English changes, or only Chinese changes, etc.

Closes #XXXXX

### CODE REVIEW

**Comment by ojeytonwilliams** [comment]
The failing cypress test should be fixed on master and doesn't have anything to do with this PR.

`npm run test` passes locally.

**Comment by raisedadead** [comment]
> The failing cypress test should be fixed on master and doesn't have anything to do with this P

Does that mean this PR needs a rebase?

**Comment by ojeytonwilliams** [comment]
> Does that mean this PR needs a rebase?

@raisedadead kind of.  It's `next-curriculum` as a whole that needs rebasing and this issue should get sorted out by that rebase.

**Comment by raisedadead** [comment]
Ah - sorry, I missed this is targeting next-curriculum. That makes sense.

**Pull request merged**
