### PR TITLE
add tail to waypoint to display variable value

### LINKED ISSUE #5673: Waypoint: Escape Sequences in Strings (probably mini console bug)
Challenge [Waypoint: Escape Sequences in Strings](http://www.freecodecamp.com/challenges/waypoint-escape-sequences-in-strings#?solution=var%20myStr%20%3D%20%22%5C%5C%20%5Ct%20%5Ct%20%5Cr%20%5Cn%22%3B%20%2F%2F%20Change%20this%20line) has an issue.
User Agent is: <code>Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/41.0.2227.0 Safari/537.36</code>.
Please describe how to reproduce this issue, and include links to screenshots if possible.

My code:
```javascript
var myStr = "\\ \t \t \r \n"; // Change this line
```
The point is:
1) if I use the same line for assignment and declaration, i.e. result looks like:
```javascript
var myStr = "\\ \t \t \r \n"; // Change this line
```
, then mini console log (under reset/help/bug buttons) returns: undefined (which is probably a bug)
2) because if I use another line to assign the variable, so that result looks like:
```javascript
var myStr; // Change this line
myStr = "\\ \t \t \r \n";
```
, then mini console returns: \ (which is probably correct)

This does not prevent a user from passing the challenge on Ctrl+Enter, so this issue's probably not substantial.

### PR DESCRIPTION
**Pull request by gasperno**
added tail that returns value of myStr variable if defined. Else returns null to the console.
Tested in chrome. Closes #5673

### CODE REVIEW

**Comment by ltegman** [comment]
Is there a reason you don't just return `myStr` regardless of if it's defined? Returning undefined, which is the true value of `myStr` seems more clear and straightforward than returning `null` instead.

**Comment by gasperno** [comment]
you are right. I was looking at other test cases and could see that they were always checking if a variable is defined or not. So I was returning null.
I will change the PR and update this. Returning myStr as undefined makes more sense.

**Comment by SaintPeter** [comment]
Does this even display in a human readable format?

**Comment by gasperno** [comment]
@SaintPeter what do you mean by human readable format? I couldnot understand.

**Comment by SaintPeter** [comment]
I mean most of those characters are non-printable.  I don't think there is a way to get it to literally print out `\\ \t \t`, etc.

**Comment by gasperno** [comment]
@SaintPeter Last line of the code editor is executed.
Adding tail reduces confusion to campers.
1) `var x` returns undefined
2) `x=2` returns 2. 
You are right that most of those are non-printable.

**Comment by SaintPeter** [comment]
I agree that it will reduce confusion, but I'm concerned that in this case it would increase confusion.  Without writing a function that reads in special characters and displays them as their escaped equivalent, I don't think having a tail function will help in this case.

**Comment by ltegman** [comment]
You can see the escape characters in the output if you `JSON.stringify()` it.

**Comment by gasperno** [comment]
In javascript, "\\ \t \t \r \n" outputs '\ <unnoticeable characters>'
Showing those characters might actually confuse the campers, don't you think?
Or may be we should throw in a better example like 'column1 \t column2 \r new line \n line feed'.
I am equally concerned that it would complicate the example.

**Comment by SaintPeter** [comment]
This works well:
```js
(function(){
if (myStr !== undefined){
return 'myStr = ' + JSON.stringify(myStr);}
else{return null;}})();
```
image

**Comment by gasperno** [comment]
I modified the file as @SaintPeter mentioned. Now it is your call whether to merge this request or not. 
The only purpose of this change is to ensure that `myStr` is printed in mini console.

**Comment by SaintPeter** [comment]
This is fab, appreciate your patience to get it right.

**Pull request merged**
