### PR TITLE
update test wording for undefined fn returns

### PR DESCRIPTION
**Pull request by nemogoc**
- [ X ] I have read [freeCodeCamp's contribution guidelines](https://github.com/freeCodeCamp/freeCodeCamp/blob/master/CONTRIBUTING.md).
- [ X ] My pull request has a descriptive title (not a vague title like `Update index.md`)
- [ X ] My pull request targets the `master` branch of freeCodeCamp.
- [ X ] None of my changes are plagiarized from another source without proper attribution.
- [ X ] All the files I changed are in the same world language (for example: only English changes, or only Chinese changes, etc.)
- [ X ] My changes do not use shortened URLs or affiliate links.

### CODE REVIEW

**Comment by nemogoc** [comment]
I'm helping teach someone code from scratch, with no prior knowledge, using your tools (thanks for them!). She got hung up on the wording here, since the test doesn't indicate the answer should be 8 after both functions are ran, and the functions are ran in the tests, not in the code she could see. We felt this tweak fixed her confusion and thought it would be a good open source lesson to submit this.

**Comment by scissorsneedfoodtoo** [comment]
Hi @nemogoc, thank you for your explanation and contribution. I agree that this challenge could be a bit more clear in its wording and by showing the code that's being run behind the scenes.

Perhaps the wording could be tweaked slightly to `Once both functions have run, <code>sum</code> should be equal to 8`, and the `challengeSeed` could  be changed to something like the following:

```
// Only change code above this line
addThree();
var returnedValue = addFive();
```

This should make it more clear that both the `addThree` and `addFive` functions are being run before checking `sum`.

Let's wait from other contributors before we decide what to do with this challenge.

**Comment by ojeytonwilliams** [comment]
@scissorsneedfoodtoo @nemogoc I agree that it's a bit confusing having the code hidden like this. @scissorsneedfoodtoo's proposal to move everything into plain sight should clear things up.

Also, if we use that seed we can remove the `After Test` section entirely.

What do you think @nemogoc?

**Comment by RandellDawson** [comment]
There is another issue with this challenge.  Even if the changes suggested by @scissorsneedfoodtoo are made and we remove the `After Test` section, someone can still pass the challenge with the following code because the last test is written incorrectly.  
```
var sum = 0;
function addThree() {
  sum = sum + 3;
}

// Only change code below this line

function addFive() {
}

sum += 5;

// Only change code above this line
addThree();
var returnedValue = addFive();
```

To correct the last test, I first believe the wording of the last test's `text` should be:
```
  - text: Inside the <code>addFive</code> function, add <code>5</code> to the <code>sum</code> variable
```
Then, the last test's `testString` should be changed to something like:
```
    testString: assert(addFive.toString().replace(/\s/g, '').match(/sum=sum\+5|sum\+=5/));
```

**Comment by scissorsneedfoodtoo** [comment]
Great catch @RandellDawson. I agree that we should change the text and testString to what you suggest to prevent situations like that.

**Comment by nemogoc** [comment]
Wow, all this from a few word change! Looking great all.

**Comment by RandellDawson** [comment]
@nemogoc Can you make the suggested changes?

**Comment by nemogoc** [comment]
So, I made the changes as suggested, but now a test fails. Presumably that is because we are trying to call a function (`addFive()`) that doesn't yet exist. I could add a check to only run `addFive()` if it exists (my thought is something like the testString from the first test), but that adds a lot of complication to the visible code. 

I'm not a developer either, so am I missing something obvious to fix this issue? Should I add that check I described? Should I stick with the simpler change and not remove the `after test` section?

**Comment by ojeytonwilliams** [comment]
The errors in Travis are a bit messy, unfortunately.  Anyway, the problem is that `sum` is not defined and `addFive` tries to operate on it.  What you should do is put a full, working solution in.

```js
// Example
var sum = 0;
function addThree() {
  sum = sum + 3;
}

// Only change code below this line

function addFive() {
  sum = sum + 5;
}

// Only change code above this line
addThree();
var returnedValue = addFive();
```

That should do the trick.  To be sure, go into the `curriculum` directory and run `npm run test -- -g 'Undefined Value'` i.e. just the tests for that challenge.

**Comment by nemogoc** [comment]
Thanks ojeytonwilliams, got that fixed and the tests are passing now.

**Comment by RandellDawson** [comment]
We don't really need to assign the result of calling `addFive()` to a variable (`returnedValue`) because we do not use it in the test. 
```js
// Only change code above this line
addThree();
var returnedValue = addFive();
```
to simply:
```js
// Only change code above this line
addThree();
addFive();
```
The only issue we have now because of the change in the challenge seed code and solution, is that the last part of the scrimba video needs to be changed too and the  corresponding forum topic needs to be updated.  @beaucarnes Can you create a new video url for this challenge?  I can update the forum topic.

**Comment by nemogoc** [comment]
@RandellDawson I'm happy to make that change if that's the consensus, but I do kind of like it there, just because it would give me the opportunity to ask the student what they think that value would be. That said, I realize that my model of teacher/student isn't the main model FCC uses, so if we think it would just add confusion for the solo learner, I'm happy to remove it.

**Comment by RandellDawson** [comment]
@nemogoc By leaving it in, it seems to imply `returnedValue` is important somehow to solving the challenge.  In reality, it has nothing to do with the tests, so I say remove it.

**Comment by nemogoc** [comment]
That's convincing to me, I'll remove it tonight when I get home unless the other two feel differently.

**Comment by ojeytonwilliams** [comment]
I'm in two minds about this one.  We are supposed to be teaching that functions without `return` statements actually return `undefined`.  As I see it, we don't use that fact - we just modify a global variable.

Unfortunately, something as simple as adding `console.log(returnedValue)` to highlight the fact it's `undefined` doesn't work because of how `console.log` works behind the scenes (it just logs `''`).

We could use `console.log('' + returnedValue)`, but would that be confusing?

Also, @nemogoc if we're removing `returnedValue` entirely (which might be the way to go!) it will also need removing from the seed.  That said, I'd wait to see if @RandellDawson and @scissorsneedfoodtoo have any further thoughts.  I don't want to waste your time while we're still discussing.

**Comment by scissorsneedfoodtoo** [comment]
Hi all, thanks for your patience.

Like @RandellDawson I'm in favor of removing `returnedValue` to simplify things further. While it would be a good opportunity to ask a student what they think the value might be if logged to the console as @nemogoc mentioned, it's not necessary for this challenge. There's nothing stopping a teacher from assigning `addFive` to a variable themselves.

Fortunately the current video doesn't include all of the seed code, just the following:

```js
// Example
var sum = 0;
function addThree() {
  sum = sum + 3;
}

function addFive() {
  sum += 5;
}
```

Given this, I think we can just update the forum post for this challenge.

**Comment by RandellDawson** [comment]
@scissorsneedfoodtoo Just to confirm, you are ok just having the seed code look like the following?
```js
// Example
var sum = 0;
function addThree() {
  sum = sum + 3;
}

// Only change code below this line

// Only change code above this line
addThree();
addFive();
```
and once the PR is merged, we update the corresponding solution on the forum?

**Comment by scissorsneedfoodtoo** [comment]
@RandellDawson, yes, changing the seed to the code you posted should be fine. The video doesn't show the actual function calls.

And yes, once this is merged all we should have to do is update the solution in the forum.

**Comment by RandellDawson** [comment]
@nemogoc Can you please make the recommended changes?

Thank you.

**Comment by nemogoc** [comment]
done pending checks

**Comment by RandellDawson** [comment]
@scissorsneedfoodtoo Should we go ahead and have the example changed from:
```js
var returnedValue = addSum(3); // sum will be modified but returned value is undefined
```
to:
```js
addSum(3); // sum will be modified but returned value is undefined
```

**Comment by scissorsneedfoodtoo** [comment]
@RandellDawson, yes, we should change the example, too. Thank you for catching that.

@nemogoc, could you change the example to what @RandellDawson posted? After that we should be good to go.

**Comment by nemogoc** [comment]
Done

**Review by RandellDawson — APPROVED** [review]

**Comment by scissorsneedfoodtoo** [comment]
@nemogoc, thank you for all of your hard work on this! I'm sure your changes here will make things easier to understand for your student and anyone else who does this challenge.

**Comment by nemogoc** [comment]
Well, thanks to all of you for improving/completely transforming the changes we made!

**Pull request merged**
