### PR TITLE
test(e2e/playwright): added email-signup.spec.ts

### PR DESCRIPTION
**Pull request by lalithasj**
Checklist:

- [x] I have read and followed the [contribution guidelines](https://contribute.freecodecamp.org).
- [x] I have read and followed the [how to open a pull request guide](https://contribute.freecodecamp.org/#/how-to-open-a-pull-request).
- [x] My pull request targets the `main` branch of freeCodeCamp.
- [x] I have tested these changes either locally on my machine, or GitPod.

Related to #51705.

### CODE REVIEW

**Review by naomi-lgbt — CHANGES_REQUESTED** [review]
Hey there,

Looks like you'll need to update the jest snapshots.

**Review by naomi-lgbt — CHANGES_REQUESTED** [review]

**Comment by lalithasj** [comment]
Hi,
Can anyone suggest how to remove previous commits, after git rebase -i HEAD~33 command, I changed the pick to drop in popup file, the repo created more commits and did not remove previous commits. git revert <HASH> also not working. 

Thanks

**Comment by gikf** [comment]
That depends exactly which commits you'd want to keep.

Rough rundown below.

Going back to the first commit before your changes:
```bash
git rebase -i 42a1a6c5ee0156935af584904b0c771ef57a0296
```

- `drop` all commits that were pulled in to this PR and they aren't made by you
- `edit` commit adding `package-lock.json` - that's `d516e16628` https://github.com/freeCodeCamp/freeCodeCamp/pull/52019/commits/d516e1662892c895e3e1eead9aa5707b9a8af9f5
- If there's any merge conflicts - resolve them, stage changed files and commit, then `git rebase --continue` if necessary. See `git status` for information what git expects at the time.
- When rebase stops at `d516e16628` commit. Unstage `package-lock.json` file and delete it. Stage other changed files from that commit and commit, then `git rebase --continue` if necessary.

Once rebasing is complete, unwanted commits should be gone. To further reduce chances for conflicts, rebase to `freeCodeCamp:main`:

```bash
git pull --rebase upstream main
```
Fix and commit any merge conflicts. Finally:
```bash
git push --force origin main
```

Once this PR is merged/closed re-sync your `main` branch with `freeCodeCamp:main`. After that keep `main` brach always in sync - you don't need to update it every time there's new commit merged to `freeCodeCamp:main`, but do not commit your changes to `main` branch on your fork, always work on new branch instead.

**Comment by lalithasj** [comment]
Hi @gikf,
Thanks a lot

**Review by huyenltnguyen — COMMENTED** [review]
The page has a conditional rendering logic using the `isSignedIn` value, so our tests should cover both cases.

**Comment by lalithasj** [comment]
Hi,
Can anyone suggest me how to resolve this conflict. 
Thanks,
Lalitha

**Review by huyenltnguyen — COMMENTED** [review]
Hey @lalithasj, thank you for your contribution and for your patience!

I haven't pulled down the code to test, but I think the timeout issue is because the URL path is not correct. The tests are accessing `/signup` while the path  should be `/email-sign-up`.

My feedback on the tests:
- The "should render" cases should be merged into one case. It is more appropriate to split them if we were writing unit tests, but e2e tests take more resources to setup and tear down, so grouping them would be more efficient.
- We should choose `getByRole` and `getByText` over `getByTestId`. More detail here: https://contribute.freecodecamp.org/#/how-to-add-playwright-tests?id=-identifying-a-dom-element

There is another PR adding tests to the same page: #51887. To speed up the review process, I have merged your changes to the PR and added some improvements myself. The commit for the changes is https://github.com/freeCodeCamp/freeCodeCamp/commit/0b25b24b24d257680e9381b0d5e6952acea6235d. 

One thing I should note is that, we should not make changes directly to our `main` branch. This is the sole reason why I chose the other PR instead of this one, as I'm not comfortable pushing changes to someone else's `main`.

I've added you as a co-author of the commit, and this PR has also been labeled with `hacktoberfest-accepted`, so you still get credit for your effort 🙂 

With that, I'm going to close this PR in favor of #51887. Thank you again for your contribution, and sorry for the delay in reviewing the PR.

Happy coding!

**Pull request closed without merging**
