### PR TITLE
 Fixed ArrayList guide

### PR DESCRIPTION
**Pull request by myluco**
- [x ] I have read [freeCodeCamp's contribution guidelines](https://github.com/freeCodeCamp/freeCodeCamp/blob/master/CONTRIBUTING.md).
- [x ] My pull request has a descriptive title (not a vague title like `Update index.md`)
- [x ] My pull request targets the `master` branch of freeCodeCamp.
- [x ] None of my changes are plagiarized from another source without proper attribution.
- [ x] My article does not contain shortened URLs or affiliate links.

If your pull request closes a GitHub issue, replace the XXXXX below with the issue number.

Closes #XXXXX

### CODE REVIEW

**Comment by cmccormack** [comment]
@myluco thank you for your contribution.  Can you please remove the Portuguese files from this PR and submit with a new PR?  This PR is blocking newer PRs against `guide/english/java/arraylist/index.md` as we have limited Members that speak Portuguese.  Thanks!

**Review by Manish-Giri — CHANGES_REQUESTED** [review]
Hi,

As there has been no response from your end for a while, I am closing this PR.

Feel free to re-open it if you wish to apply the suggested changes.

Happy Coding!

**Comment by myluco** [comment]
Sorry, I never saw the other message before today. Let me know if still need some help.

**Comment by Manish-Giri** [comment]
@myluco Hey! If you wish to create a new PR to submit the change (`names` -> `ages`)  in `guide/english/java/arraylist/index.md`, please feel free to do so. You would need to update your fork of freeCodeCamp to ensure you have the latest changes from the codebase.

You're also welcome to submit changes in the portugese guides, but please do so in separate PRs, so we can review the english PR independently from the portugese ones.

**Pull request closed without merging**
