### PR TITLE
On story submission create unique story URL if slug already exists

### PR DESCRIPTION
**Pull request by ghost**
#283

Also changed Story.find to Story.findOne because if you clicked on a link like "/stories/google" and there was a "/stories/google-1" in the database Story.find would return both and end up sending the user to "/stories/google" then "/stories/google-1". The user would just see "/stories/google-1" since it happens so fast but you can see it in the cli.

Since only 1 result should be returned anyway (`exports.returnIndividualStory`), I figured using findOne would be appropriate.

Quick question: What Is the reason for find using regex on the Story.find?:
 `Story.find({'storyLink' : new RegExp(storyName, 'i')}, function(err, story) {`

### CODE REVIEW

**Comment by QuincyLarson** [comment]
Thank you for quickly addressing this problem. I've QA'd it and like your changes a lot. As for why we're doing a regex search instead of an exact search, I think that was just a mistake. Because these storyLinks are all generated by the same system, there shouldn't be any need for the margin of error that a regular expression affords.

**Comment by QuincyLarson** [comment]
I'll try changing that to an exact string match and verify it works. But I'm going to go ahead and pull in your pull request. Thanks again!

**Comment by QuincyLarson** [comment]
Actually, it did some further QA and it doesn't look like this solution solved the underlying problem. The second entry I submitted with the same name worked, but the subsequent entries did not, and just redirected to the second entry. If you have time to pair with me on it we can try to get this working.

**Comment by jameskopacz** [comment]
I'm on twitch chat!

**Comment by jameskopacz** [comment]
I'm pretty sure I tested it last night and added 'Google' and came out with Google, -1,-2,-3,-4 but I saw on stream it didn't work and then tested the code and it didn't work :( Maybe I was up to late haha

Added a fix: #294

Now when it counts the number of stories with the headline being used it'll also check for previous stories and the proper number will be returned.

Please test!

**Pull request merged**
