### PR TITLE
fix(curriculum): allow hex triplets for red and green colors to pass …

### LINKED ISSUE #38521: Basic CSS: Use Hex Code to Mix Colors
- https://www.freecodecamp.org/learn/responsive-web-design/basic-css/use-hex-code-to-mix-colors

If a hex triplet (i.e. ```#F00```) is used in the bodies of the ```.red-text``` and ```.green-text``` selectors, the tester complains:
```
The hex code for the color red should be used instead of the word red.
The hex code for the color green should be used instead of the word green.
```
Don't penalize learners for being smart!

### PR DESCRIPTION
**Pull request by AshNaz87**
…tests

Checklist:

- [x] I have read [freeCodeCamp's contribution guidelines](https://github.com/freeCodeCamp/freeCodeCamp/blob/master/CONTRIBUTING.md).
- [x] My pull request has a descriptive title (not a vague title like `Update index.md`)
- [x] My pull request targets the `master` branch of freeCodeCamp.
- [x] All the files I changed are in the same world language, for example: only English changes, or only Chinese changes, etc.

Closes #38521

### CODE REVIEW

**Review by Czespo — COMMENTED** [review]
@AshNaz87  ```#FF0``` is yellow, not red!

**Comment by AshNaz87** [comment]
@Czespo Thanks for letting me know. Overlooked

**Comment by AshNaz87** [comment]
Fixed both triplet hex codes. Rebased and pushed

**Review by jordanliu — APPROVED** [review]
All good

**Review by SemperDisco — APPROVED** [review]

**Review by ahmaxed — APPROVED** [review]

**Pull request merged**
