### PR TITLE
[Guide] Basic JS: Greater than operator. Enhancements

### PR DESCRIPTION
**Pull request by AdrianSkar**
From [this PR on the old guide repo](https://github.com/freeCodeCamp/guide/pull/8663).
· Added problem explanation, run code example, code explanation and resources.

- [x] I have read [freeCodeCamp's contribution guidelines](https://github.com/freeCodeCamp/freeCodeCamp/blob/master/CONTRIBUTING.md).
- [x] My pull request has a descriptive title (not a vague title like `Update index.md`)
- [x] My pull request targets the `master` branch of freeCodeCamp.
- [x] None of my changes are plagiarized from another source without proper attribution.
- [x] My article does not contain shortened URLs or affiliate links.

### CODE REVIEW

**Comment by RandellDawson** [comment]
Closed and reopened this PR in an attempt to resolve the following Travis build error:

Error: ValidationError: "0" is not allowed. "1" is not allowed. "2" is not allowed. "3" is not allowed. "4" is not allowed

**Comment by RandellDawson** [comment]
Thank you for your contribution to the page! 👍
We're happy to accept these changes, and look forward to future contributions. 🎉

**Review by AdrianSkar — COMMENTED** [review]
How is this a fix? Is the link broken?

**Comment by RandellDawson** [comment]
We don't allow repl.it or codepen.io links anymore in the guide articles, so I "fixed" it.

**Comment by AdrianSkar** [comment]
I didn't know about that, where is this  change referenced? The [style guide for creating and editing guide articles](https://github.com/freeCodeCamp/freeCodeCamp/blob/master/docs/style-guide-for-guide-articles.md#images) still encourages it.

**Comment by RandellDawson** [comment]
It has not been added yet, but will be soon.  We are just removing them as we see them in open PRs, then once most of the curriculum related article PRs have been merged, we will do some kind of mass removal for any found.

**Comment by AdrianSkar** [comment]
Thank you @RandellDawson, pretty clarifying. 
Sorry about the newb question but do this discussions take place on github issues, mail subs or something similar?

**Comment by RandellDawson** [comment]
The discussion for this particular issue started in the Gitter chat room, but I also created [an issue](https://github.com/freeCodeCamp/freeCodeCamp/issues/35479).  I have already made all the changes locally which removes them from all 6 languages, but will wait till there are fewer oustanding PRs for challenge related articles, before creating the PR for it.

**Pull request merged**
