### PR TITLE
fix(learn): set up a template engine

### LINKED ISSUE #38404: "Advanced Node and Express - Set up a Template Engine" passes as correct despite wrong solution
**Describe your problem and how to reproduce it:**
When setting up Pug for the first time, even though I didn't choose to **render** the index.pug page, but sent it (using app.sendFile), the FCC checker passed my solution as correct.

Code that wrongly passes tests:
```
app.route('/')
  .get((req, res) => {
    res.sendFile(process.cwd() + '/views/pug/index.pug');
  });
```

Actual solution:
```
app.route('/')
  .get((req, res) => {
    res.render(process.cwd() + '/views/pug/index.pug');
  });
```

This is especially confusing for a beginner as the boilerplate comes with res.sendFile as a default, simply changing the path results in the behavior shown in the screenshots below.

**Add a Link to the page with the problem:**
https://www.freecodecamp.org/learn/information-security-and-quality-assurance/advanced-node-and-express/set-up-a-template-engine

**Tell us about your browser and operating system:**
* Browser Name: Firefox
* Browser Version: 74
* Operating System: Linux Mint 19

**If possible, add a screenshot here (you can drag and drop, png, jpg, gif, etc. in this box):**
image

### PR DESCRIPTION
**Pull request by jeremyfiel**
Checklist:

- [x] I have read [freeCodeCamp's contribution guidelines](https://contribute.freecodecamp.org).
- [x] My pull request has a descriptive title (not a vague title like `Update index.md`)
- [x] My pull request targets the `master` branch of freeCodeCamp.
- [x] All the files I changed are in the same world language, for example: only English changes, or only Chinese changes, etc.

CLOSES #38404

### CODE REVIEW

**Comment by raisedadead** [comment]
Thanks for the change, we recommend using conventional commits.

The branch name is for your reference, it can be shorter. The commit and the PR title need not say everything you are doing on the PR.

Instead, you should keep it below 50 chars, and put everything else in the description.

**Comment by jeremyfiel** [comment]
@scissorsneedfoodtoo  this is updated and ready to go. 👍

**Comment by scissorsneedfoodtoo** [comment]
@jeremyfiel, thanks for your patience. Sorry I'm just seeing this and your reply in your last PR now. I'll run this locally and leave any comments if I notice anything.

**Comment by scissorsneedfoodtoo** [comment]
@jeremyfiel, everything LGTM! Thanks again for all of the hard work you put into updating this challenge and the boilerplate. All of your changes are a huge improvement over what we had a couple of weeks ago.

While I was able to pass the third test with `res.reeeee`, as you pointed out in https://github.com/freeCodeCamp/freeCodeCamp/pull/38572, the last test will still fail.

**Review by scissorsneedfoodtoo — APPROVED** [review]

**Pull request merged**
