### PR TITLE
Reordering spanish descriptions to follow changes in english

### PR DESCRIPTION
**Pull request by vtamara**

### CODE REVIEW

**Comment by bugron** [comment]
@vtamara why are you opening and closing your PRs?

**Comment by vtamara** [comment]
Squashing didn't work first time.

Second time I found ortography error.

I hope this one is right

**Comment by bugron** [comment]
Please, make the changes in one PR, there is no need to open a new PR.

**Comment by vtamara** [comment]
Thanks.

**Comment by QuincyLarson** [comment]
Great work, @vtamara - I'm looking forward to talking with you about our Spanish translation effort.

**Pull request merged**
