### PR TITLE
fix typo and add comma

### PR DESCRIPTION
**Pull request by MartinDelille**
latitiude => latitude

### CODE REVIEW

**Comment by ltegman** [comment]
Thanks for the PR - I definitely think some better formatting of this data in the example would be an improvement. However, it looks like without using HTML entities for the `<br>` tag it won't show up in the page. Could you replace the `<br>` with `&lt;br&gt;`? :smile:

**Comment by MartinDelille** [comment]
done

**Comment by MartinDelille** [comment]
Tell me if you want me to squash the commit!

**Comment by ltegman** [comment]
That would be awesome if you could squash them!

**Comment by MartinDelille** [comment]
done

**Comment by bugron** [comment]
@MartinDelille thanks for the PR! Now the result looks better, verified and merged.
I recommend you to read our [**Guidelines for Contributing**](https://github.com/FreeCodeCamp/FreeCodeCamp/blob/staging/CONTRIBUTING.md). Also next time write in the description of your PR something like `closes #4010` of `fix #4010` to auto close the issue which your PR is fixing (if there is an open issue, of course).

**Pull request merged**
