### PR TITLE
Fixes #1878

### LINKED ISSUE #1878: Waypoint: Use Conditional Logic with IfElse Statements - Missing Closing Code Bracket
Challenge http://www.freecodecamp.com/challenges/waypoint-use-conditional-logic-with-ifelse-statements has an issue:
image
It looks to me as if this code is missing a closing code bracket: `</code>`

### PR DESCRIPTION
**Pull request by AryanJ-NYC**
Tested.

### CODE REVIEW

**Comment by benmcmahon100** [comment]
Why the extra code?

**Comment by benmcmahon100** [comment]
The closing tag should be on line 961 i think where the if statement is

**Comment by AryanJ-NYC** [comment]
That would also work. Why are code tags written line by line? Why not write an opening one on 961 and a closing one on 966?

**Comment by benmcmahon100** [comment]
Quincy prefers it line by line. Just pop it up for me to the correct line and i can merge.

**Comment by AryanJ-NYC** [comment]
Thanks for telling me about the convention!

**Comment by benmcmahon100** [comment]
Yeah I used to do it as one large one but the code parses it on a per line basis anyway. Thanks for the fix!

**Pull request merged**
