### PR TITLE
fix(learn): Update demo links

### LINKED ISSUE #40521: [BUG] - Heroku hosted projects are down
The following Heroku hosted projects are down:

- [Chart the Stock Market](https://www.freecodecamp.org/learn/coding-interview-prep/take-home-projects/chart-the-stock-market)
- [Image Search Abstraction Layer](https://www.freecodecamp.org/learn/coding-interview-prep/take-home-projects/build-an-image-search-abstraction-layer)
- [Voting App](https://www.freecodecamp.org/learn/coding-interview-prep/take-home-projects/build-a-voting-app)

It looks like there was a plan to migrate/rebuild these on the `.rocks` domain. These projects are also still hosted on Heroku but are currently up:
- [Nightlife Coordination App](https://www.freecodecamp.org/learn/coding-interview-prep/take-home-projects/build-a-nightlife-coordination-app)

### PR DESCRIPTION
**Pull request by naomi-lgbt**
Checklist:

- [X] I have read [freeCodeCamp's contribution guidelines](https://contribute.freecodecamp.org).
- [X] My pull request has a descriptive title (not a vague title like `Update index.md`)
- [X] My pull request targets the `master` branch of freeCodeCamp.
- [X] All the files I changed are in the same world language, for example: only English changes, or only Chinese changes, etc.

Closes #40521 

Replaces the example project links for the Heroku hosted projects with our `.rocks` projects (generously provided by @moT01).

### CODE REVIEW

**Review by RandellDawson — DISMISSED** [review]
LGTM

**Comment by RandellDawson** [comment]
@nhcarrigan Can you fix the merge conflicts on this PR?

**Comment by nhcarrigan** [comment]
Should be resolved now. 🙂

**Review by moT01 — APPROVED** [review]
LGTM @nhcarrigan 🎉

**Pull request merged**
