### PR TITLE
fix(certs): remove footer and nav from certs

### PR DESCRIPTION
**Pull request by raisedadead**

### CODE REVIEW

**Comment by ValeraS** [comment]
image

Should we delete this https://github.com/freeCodeCamp/freeCodeCamp/pull/35333/files#diff-60da01e813042964fd667cfe1c7ebc89L30?

**Comment by raisedadead** [comment]
Oh wait. That rendered weird on my viewport with it. If I have that `top` I get the cert squished on my viewport.

Looks like we need a much cleaner solution. Thanks for catching.

**Comment by raisedadead** [comment]
And of course looks like the night mode view needs to be removed.

**Comment by raisedadead** [comment]
I have gone ahead and rolled back the white-spacing changes. Lets just handle the whole CSS in a separate PR.

**Comment by ahmadabdolsaheb** [comment]
you could have a media query that adds   `top: calc(100vh / 20);` for screen larger than 1500px, because it looks strange on smaller screens.

**Pull request merged**
