### PR TITLE
fix: remove Coding Interview Prep from audited uk certs

### PR DESCRIPTION
**Pull request by ojeytonwilliams**
Checklist:

- [x] I have read [freeCodeCamp's contribution guidelines](https://contribute.freecodecamp.org).
- [x] My pull request has a descriptive title (not a vague title like `Update index.md`)
- [x] My pull request targets the `main` branch of freeCodeCamp.
- [x] I have tested these changes either locally on my machine, or GitPod.

This will first check that the new job fails, then commit a fix.

### CODE REVIEW

**Review by raisedadead — CHANGES_REQUESTED** [review]
I do not think we need to build every language for sake of linting. This is too much redundancy.

The jobs should and will fail on Azure pipelines in case of malformed config like we are seeing in the case of Ukrainian. This behavior is both by design and expected.

**Comment by ojeytonwilliams** [comment]
I think Cypress' servers agree with you: https://github.com/freeCodeCamp/freeCodeCamp/runs/6096632466?check_suite_focus=true#step:5:53

**Review by raisedadead — APPROVED** [review]

**Review by ShaunSHamilton — COMMENTED** [review]
I am still getting:

```
Error: Missing ukrainian audited challenge for
  04-data-visualization/d3-dashboard/step-001.md
  No audited challenges should fallback to English.
```

EDIT: wait.... I needed to change the env to not build upcoming stuff.

**Review by ShaunSHamilton — APPROVED** [review]
This LGTM 👍 

---

After changing `SHOW_UPCOMING_CHANGES` to `false`, the Uk localisation builds just fine

**Comment by raisedadead** [comment]
Yes - that is the intended condition on the production builds.

**Comment by nhcarrigan** [comment]
https://github.com/freeCodeCamp/freeCodeCamp/issues/45736 somewhat related.

**Pull request merged**
