### PR TITLE
fix: search bar going off screen

### PR DESCRIPTION
**Pull request by achimoraites**
- [x] I have read [freeCodeCamp's contribution guidelines](https://github.com/freeCodeCamp/freeCodeCamp/blob/master/CONTRIBUTING.md).
- [x] My pull request has a descriptive title (not a vague title like `Update index.md`)
- [x] My pull request targets the `master` branch of freeCodeCamp.
- [x] None of my changes are plagiarized from another source without proper attribution.
- [x] My article does not contain shortened URLs or affiliate links.

### Made corrections for search bar to work properly in all screen sizes

**_Note: I have tested the changes locally with the latest updates from the master branch_**

**Bug**

screen shot 2018-12-07 at 09 58 19

### After Fix
screen shot 2018-12-07 at 10 13 44

**Larger screens**
screen shot 2018-12-07 at 10 27 45

Closes #29824

### CODE REVIEW

**Comment by Bouncey** [comment]
@Cyb3rN4u7 Thank you for the PR. There seems to be a merge conflict, could you rebase this PR to clear them please.

**Comment by Cyb3rN4u7** [comment]
@Bouncey i have rebased the PR

**Review by raisedadead — CHANGES_REQUESTED** [review]
Please remove the lockfiles out of this commit.

**Comment by RandellDawson** [comment]
@raisedadead I could be mistaken, but the beta site no longer seems to exhibit this search bar problem.  Maybe another PR was merged which resolved this?

**Comment by Cyb3rN4u7** [comment]
@raisedadead i have removed the lockfiles

**Comment by RandellDawson** [comment]
@Cyb3rN4u7 He did not mean delete them.  He just wanted you to remove any changes to these files from the PR.

**Review by raisedadead — APPROVED** [review]

**Pull request merged**
