### PR TITLE
feat(donation): set donor cookie

### PR DESCRIPTION
**Pull request by ahmaxed**
Checklist:

- [x] I have read [freeCodeCamp's contribution guidelines](https://contribute.freecodecamp.org).
- [x] My pull request has a descriptive title (not a vague title like `Update index.md`)
- [x] My pull request targets the `main` branch of freeCodeCamp.
- [x] I have tested these changes either locally on my machine, or GitPod.

For testing follow these steps:

1. Setting cookie on donation:
   - make a donation
   - check if the isDonor cookie has been set.
2. Setting cookie on fetching user data:
   -  sign out 
   -  delete isDonor cookie
   - sign in
   - heck if the isDonor cookie has been set. (since the user is donating)
 
Note: check if the cookie is being set for non donor accounts.

### CODE REVIEW

**Review by naomi-lgbt — COMMENTED** [review]
Donated, saw cookie:

image

My only concern would be with shared machines - it looks like the cookie persists even if I remove the `isDonating` flag and sign in as a non-donor.

**Review by raisedadead — DISMISSED** [review]
What is the intent of this cookie?

**Review by ojeytonwilliams — APPROVED** [review]
LGTM :+1:

**Review by ojeytonwilliams — COMMENTED** [review]
Re: Naomi's point, we could reset the cookie on userFetchComplete, so it always reflects the last person that logged in.

**Comment by scissorsneedfoodtoo** [comment]
Thanks for your patience @ahmadabdolsaheb. Tested this locally using your instructions and everything LGTM.

Signing in as a non-donor does not set the `isDonor` cookie. Also, if a donor account is signed in to Learn, the `isDonor` cookie is present on News.

@nhcarrigan brings up a good point about shared machines, or cases where we flip the `isDonating` flag to `false` on someone's account in the db. In both cases, a non-donor account signing in would still have the `isDonor` cookie set until they clear their cache / cookies.

I say we go ahead and get this in now. It will only affect the banner text and link on News, and it seems like we have a good way to reset the cookie for anyone who signs in on the same machine as a donor.

**Review by scissorsneedfoodtoo — APPROVED** [review]

**Pull request merged**
