### PR TITLE
feat: nicer formatting for fill in the blank challenges

### PR DESCRIPTION
**Pull request by ojeytonwilliams**
Checklist:

- [x] I have read and followed the [contribution guidelines](https://contribute.freecodecamp.org).
- [x] I have read and followed the [how to open a pull request guide](https://contribute.freecodecamp.org/#/how-to-open-a-pull-request).
- [x] My pull request targets the `main` branch of freeCodeCamp.
- [x] I have tested these changes either locally on my machine, or GitPod.

Before: 
image

After:
image

In order to make use of the changes in this PR, the text in the `## --sentence--` section will need its backticks removing.

### CODE REVIEW

**Comment by moT01** [comment]
I see this on the challenges:

Screenshot 2023-12-15 at 8 32 02 AM

Is the idea that we would not put the sentences in backticks?

**Comment by ojeytonwilliams** [comment]
@naomi-lgbt isn't it possible to hide the strings?

If not, it should be possible to leave them in backticks in the markdown, but strip them before rendering.

**Comment by naomi-lgbt** [comment]
Not in a reliable way, in this case.

I have a couple of options for hiding strings:
- Hide based on the context (e.g. this is a code tag, this is a front-matter string)
- Hide based on string content (I can hide a specific string, for example).

Hiding the strings in a *section* gets trickier, because I can't reliably assert that the order of the strings returned in Crowdin is the order of the strings in the document.

**Comment by ojeytonwilliams** [comment]
Alright, that makes sense.

It sounds like pulling the text out of the code blocks is going to be the easiest one to pull off, so I'll try to implement that.

**Comment by moT01** [comment]
> pulling the text out of the code blocks is going to be the easiest one to pull off

🤦 That was probably the way to go in the first place - instead of trying to add them

**Comment by ojeytonwilliams** [comment]
Okay, I think this does the trick.

Since it's not so obvious that you're doing something wrong, I added a few error messages to help people fix their .md files.

I still need to add the source .md files, (so people can see where the ast files came from), but otherwise this is good to go.

**Review by moT01 — COMMENTED** [review]
This LGTM 🎉 

> still need to add the source .md files

Were you planning to add that on this PR @ojeytonwilliams? Or save it for another?

We probably want to change the styles for the blanks so they don't have the code background anymore. I think we can save that for another PR.

**Comment by ojeytonwilliams** [comment]
> Were you planning to add that on this PR @ojeytonwilliams? Or save it for another?

Sorry, Tom, I meant the files like tools/challenge-parser/parser/__fixtures__/with-fill-in-the-blank-bad-paragraph.md. I added them in the last commit, so I think it's good to go.

**Comment by moT01** [comment]
oh, yea I should have seen that 👍

**Review by moT01 — APPROVED** [review]

**Review by naomi-lgbt — APPROVED** [review]
This looks amazing omg. Thanks for building this!

**Pull request merged**
