### PR TITLE
Revert "feat: add bootcamp cost calc guide"

### PR DESCRIPTION
**Pull request by raisedadead**
Reverts freeCodeCamp/freeCodeCamp#35278

### CODE REVIEW

**Comment by ojeytonwilliams** [comment]
@raisedadead I think it's just a lint error.  If I fix the css, it all seems fine.  Should I put that in a PR?

**Comment by raisedadead** [comment]
Sure, go for it. But the previous PR that got merged by @QuincyLarson also adds unwanted files to the repository. I'll let you decide and make the changes.

**Comment by ojeytonwilliams** [comment]
Oh, okay. If you don't want the files, it seems pointless to fix them.

**Review by ojeytonwilliams — APPROVED** [review]
I'm not sure my review is particularly useful, but it LGTM

**Pull request merged**
