### PR TITLE
Fixed syntax error.

### PR DESCRIPTION
**Pull request by hegdenischay**
Fixed a syntax error in line 55.
Also corrected the indentation.

- [x] I have read [freeCodeCamp's contribution guidelines](https://github.com/freeCodeCamp/freeCodeCamp/blob/master/CONTRIBUTING.md).
- [x] My pull request has a descriptive title (not a vague title like `Update index.md`)
- [x] My pull request targets the `master` branch of freeCodeCamp.
- [x] None of my changes are plagiarized from another source without proper attribution.
- [x] My article does not contain shortened URLs or affiliate links.

If your pull request closes a GitHub issue, replace the XXXXX below with the issue number.

Closes #XXXXX

### CODE REVIEW

**Comment by RandellDawson** [comment]
Closed and Reopened this PR to attempt to resolve a specific Travis build failure.

**Review by Manish-Giri — CHANGES_REQUESTED** [review]
@hegdenischay Thanks for creating this PR.

While your changes are fine in general, the other C++ guides use `using namespace std;`. So for consistency, it would be better if we stick to this.

Please edit your PR to revert this particular change. Remaining changes LGTM.

**Comment by RandellDawson** [comment]
@Manish-Giri This one has gone stale.

**Review by hegdenischay — COMMENTED** [review]
I'm sorry about not doing this earlier. I was kinda busy with exams.

**Review by Manish-Giri — APPROVED** [review]
LGTM. Thank You for your contribution.

**Pull request merged**
