### PR TITLE
Keyboard shortcuts to open/close map and chat

### PR DESCRIPTION
**Pull request by sahat**
I have considered writing key capture logic from scratch, but given how minimal is Mousetrap (2k gzipped and minified) I thought it would be best to use an existing, well-tested tool for this. Perhaps the biggest advantage is cross-browser compatibility.

<kbd>g</kbd> + <kbd>c</kbd> = open chat.
<kbd>g</kbd> + <kbd>m</kbd> = open map.

Fixes https://github.com/FreeCodeCamp/FreeCodeCamp/issues/6379.

untitled_gif_01-24-16

### CODE REVIEW

**Comment by QuincyLarson** [comment]
This looks good. @BerkeleyTrue It looks like the Travis CI failure is due to bower install not running prior to check.
I think a chord hotkey that could be used even when editing code would be superior to g -> c but we can discuss that later. This is definitely an improvement, and mousetrap sounds awesome. Thanks for implementing this, @sahat.

**Comment by BerkeleyTrue** [comment]
@QuincyLarson Travis CI failed because this PR does not pass ESLint due to undefined variables used. In the future please do not merge PR's that do not pass travis.

**Comment by BerkeleyTrue** [comment]
@sahat Please enable ESLint in your editor or use the `npm run test` command to verify you are not introducing bugs.

**Comment by bugron** [comment]
@sahat, please, review our [**Guidelines for Contributing**](https://github.com/FreeCodeCamp/FreeCodeCamp/blob/staging/CONTRIBUTING.md#contribution-guidelines), thank you!

**Comment by sahat** [comment]
Slightly, off-topic, but that is a really good and well documented `contributind.md`. I had a bit of trouble getting FreeCodeCamp to run on my machine, reading that guide first could have saved me a bit of time.

At work, we run linting and unit tests during `pre-commit`, so if a git commit is successful, then you are guaranteed to have passing unit tests and your code doesn't contain lint errors before you check it in.

Something to consider for FreeCodeCamp.

@QuincyLarson if you guys do decide to use a chord hotkey, with Mousetrap it will be a one-line code change. Take a look at https://craig.is/killing/mice for all possibly hotkey types.

**Pull request merged**
