### PR TITLE
feat: certification redesign 

### LINKED ISSUE #50436: Certifications Redesign
### Is your feature request related to a problem? Please describe.

Our goal is to update the design of the certifications to this new format:

New Certification

### Describe the solution you'd like

We should implement this new design following these important aspects:

- The implementation should be responsive.
- The QR Code should take users to the freeCodeCamp certification.
- The URL at the bottom should correspond to the freeCodeCamp certification.
- The implementation should include the digital version of Quincy's signature. 

### Describe alternatives you've considered

To incorporate the feedback provided by the team:
- The QR Code and the blue ribbon with the freeCodeCamp glyph should be approximately the same size. We considered different sizes and if they have approximately the same size, the design looks balanced.

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by estefaniacn**
Checklist:

- [x] I have read and followed the [contribution guidelines](https://contribute.freecodecamp.org).
- [x] I have read and followed the [how to open a pull request guide](https://contribute.freecodecamp.org/#/how-to-open-a-pull-request).
- [x] My pull request targets the `main` branch of freeCodeCamp.
- [x] I have tested these changes either locally on my machine, or GitPod.

closes #50436

### CODE REVIEW

**Comment by naomi-lgbt** [comment]
Are we looking to merge this as is? Or are we implementing the design in this PR?

**Comment by ahmadabdolsaheb** [comment]
We could do both in this PR as one of the svg files is going to be turned into the value of a CSS background property.

**Comment by Sboonny** [comment]
Don't we need to open this PR in the cdn?

What is the deciding factor between opening it cdn or here

**Comment by ahmadabdolsaheb** [comment]
I believe everything is served through a CDN so putting assets in the CDN is not necessary if they are not used anywhere else.

Additionally, the tile assets is going to be removed since it is a property value in CSS. The ribbon asset could be treated similar to other in repo assets.

**Comment by ahmadabdolsaheb** [comment]
@estefaniacn, the next steps:
1.  See which tests are failing
2. adjust the tests to our new changes locally
3. run the tests locally and see if tests pass
4. commit and push your changes

Also the tile file can be removed.

**Comment by estefaniacn** [comment]
I implemented the preview of the certifications that we can see at:
http://localhost:8000/certification/<username>/<certification>

Now I will start working on the printed layout.

**Review by ahmaxed — APPROVED** [review]
LGMT. The SVG background could be added to the print version. If so, that task could be opened to contributors.

**Review by raisedadead — APPROVED** [review]

**Pull request merged**
