### PR TITLE
fix: add missing solutions to last step of practice projects

### PR DESCRIPTION
**Pull request by moT01**
Adds solutions to last step of practice projects that don't have them for the previews shown on the first steps

- [x] I have read [freeCodeCamp's contribution guidelines](https://contribute.freecodecamp.org).
- [x] My pull request has a descriptive title (not a vague title like `Update index.md`)
- [x] My pull request targets the `main` branch of freeCodeCamp.
- [x] I have tested these changes either locally on my machine, or GitPod.

Closes #XXXXX

### CODE REVIEW

**Comment by ShaunSHamilton** [comment]
Um... https://github.com/freeCodeCamp/freeCodeCamp/pull/43971

**Review by naomi-lgbt — APPROVED** [review]
Thanks for taking care of this!

**Comment by moT01** [comment]
Didn't see that one @ShaunSHamilton - We can prioritize that and keep this for now in case we want to use it.

**Review by ShaunSHamilton — APPROVED** [review]
No worries, Tom. I am doing a partial, painful rebase of that one. So, we might as well get this in, and deal with the other PR all together, once the noise is less

**Pull request merged**
