### PR TITLE
fix(challenges): add info about ReactDOM.render

### LINKED ISSUE #17186: React challenge should mention 'ReactDOM.render'
#### Challenge Name
Create a Simple JSX Element
https://beta.freecodecamp.org/en/challenges/react/create-a-simple-jsx-element

#### Issue Description
This is not an error. It is a suggestion for how to improve the description of the challenge. 
The way it is currently written, it seems that the code `const JSX = <div></div>;` automatically updates the website with text. 

However, in reality the following line of code is running in the background (but never mentioned): `ReactDOM.render(JSX, document.getElementById('root'))`.

I think this should be more clear in the description of this challenge so people have a more accurate idea about how this works.

### PR DESCRIPTION
**Pull request by Wojonatior**
- [x] Your pull request targets the `staging` branch of freeCodeCamp.
- [x] Branch starts with either `fix/`, `feature/`, or `translate/` (e.g. `fix/signin-issue`)
- [x] You have only one commit (if not, [squash](http://forum.freecodecamp.org/t/how-to-squash-multiple-commits-into-one-with-git/13231) them into one commit).
- [x] All new and existing tests pass the command `npm test`. Use `git commit --amend` to amend any fixes.

#### Type of Change
- [x] Small bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds new functionality)
- [ ] Breaking change (fix or feature that would change existing functionality)
- [ ] Add new translation (feature adding new translations)

#### Checklist:
- [x] Tested changes locally.
- [x] Addressed currently open issue (replace XXXXX with an issue no in next line)

Closes #17186 

#### Description
I added a small description of the usage/role of `ReactDOM.render` in one of the earlier react challenges.

### CODE REVIEW

**Comment by scissorsneedfoodtoo** [comment]
@Wojonatior, thank you for submitting this PR! I'll review it ASAP.

**Comment by raisedadead** [comment]
@scissorsneedfoodtoo see https://github.com/freeCodeCamp/freeCodeCamp/pull/17471#issuecomment-395914805

**Comment by scissorsneedfoodtoo** [comment]
@Wojonatior, I took a look at the changes you made. Would you be able to update your description of what ReactDOM is doing? I tried to simplify it a bit without being overly technical.

```
"It's worth noting that under the hood the challenges are calling <code>ReactDOM.render(JSX, document.getElementById('root'))</code>. This function call is what places your JSX into React's own lightweight representation of the DOM. React then uses snapshots of its own DOM to optimize updating only specific parts of the actual DOM.",
```

Let me know what you think.

**Review by scissorsneedfoodtoo — CHANGES_REQUESTED** [review]
@Wojonatior, thank you again for submitting this PR. Please update the paragraph a bit and we can get you merged.

**Comment by Wojonatior** [comment]
@scissorsneedfoodtoo Just submitted the update! Thanks for the better description. I didn't have a good idea of the technical level of people approaching this particular lesson.

**Comment by scissorsneedfoodtoo** [comment]
@Wojonatior, thank you for making those changes! I also didn't have a good idea of what was going on with ReactDOM.render and had to read up on it a bit. It was definitely one of those instances where we don't want to overload the user with too much technical information, especially since it's explained in more detail later in the course.

**Comment by scissorsneedfoodtoo** [comment]
:sparkles: :sparkles: :sparkles: Awesome! Congratulations on your first contribution to freeCodeCamp! :sparkles: :sparkles: :sparkles:

Thank you for submitting this PR and for making those changes, @Wojonatior. We all really look forward to your next contribution.

@raisedadead, this one has been merged.

**Pull request merged**
