### PR TITLE
Added solution to this SASS challenge.

### PR DESCRIPTION
**Pull request by paulywill**
I was hoping to add to the hint section but not sure where that is located in the new guide.

- [x] I have read [freeCodeCamp's contribution guidelines](https://github.com/freeCodeCamp/freeCodeCamp/blob/master/CONTRIBUTING.md).
- [x] My pull request has a descriptive title (not a vague title like `Update index.md`)
- [x] My pull request targets the `master` branch of freeCodeCamp.
- [x] None of my changes are plagiarized from another source without proper attribution.
- [x] My article does not contain shortened URLs or affiliate links.

If your pull request closes a GitHub issue, replace the XXXXX below with the issue number.

Closes #XXXXX

### CODE REVIEW

**Review by ezioda004 — APPROVED** [review]

**Comment by ezioda004** [comment]
@paulywill This is the stub in [guide](https://github.com/freeCodeCamp/freeCodeCamp/blob/master/guide/english/certifications/front-end-libraries/sass/use-each-to-map-over-items-in-a-list/index.md).
BTW, you've created this branch in fCC's repo and not in your own fork, can you delete it? Thanks.

**Comment by paulywill** [comment]
@ezioda004 @raisedadead Did my comments cause the failure in this build? 
https://travis-ci.org/freeCodeCamp/freeCodeCamp/builds/445264431

eg..
image
image

**Comment by ezioda004** [comment]
@paulywill Seems like it, I think the travis check was updated a day ago. Also, looks like it expects only 1 solution and in format like [this](https://github.com/freeCodeCamp/freeCodeCamp/blob/master/curriculum/challenges/english/03-front-end-libraries/react/add-inline-styles-in-react.english.md) as example.

**Comment by RandellDawson** [comment]
FYI - In case you are not aware, you can not currently add SASS solutions without causing this error.  It is being worked on, but the fix is do not try to add ANY solution to the SASS challenges.  My recommendation is to wait until we hear a solution has been implemented.

**Comment by raisedadead** [comment]
There a couple of things which are breaking the builds:

1. The SASS challenges aren't ready to have solutions. Right not the challenge test script (that we use with `npm test`) is compatible only for testing JS/HTML/CSS challenges.

2. We can't have multiple solutions to the same challenge.

The comments on the challenge are irrelevant, because the solution section is never rendered to the user. Basically adding comments is futile IMHO. But That does not break builds.

For now, I would advice you to remove the solutions from the SASS challenges with a PR, and wait on the test script to be ready for SASS.

More details in #24688 

/cc @Bouncey

**Comment by raisedadead** [comment]
P.S: Sorry about this trouble. We missed adding the details to the contribution docs that SASS Test Script and Multiple solutions. I will update that shortly.

Thanks.

**Comment by ValeraS** [comment]
@raisedadead test script can work with multiple solutions.

**Comment by raisedadead** [comment]
We would not want multiple solutions? For sake of not having confusions?

**Comment by ValeraS** [comment]
In some case for more robust testing, we need more than one solution. For example in "https://learn.freecodecamp.org/javascript-algorithms-and-data-structures/es6/understand-the-differences-between-import-and-require" tests check two variants with a single and a double quotes:
- import { capitalizeString } from 'string_functions';
- import { capitalizeString } from "string_functions";

**Comment by RandellDawson** [comment]
@ValeraS So I am understand correctly, having multiple solutions is a way to make sure the **unit tests**  which are used validate the user's code works correctly, still work.  So it seems to me, the solutions are meant to double double check the units tests still work? 

If the answer to the last question is yes, then I see multiple solutions as providing two benefits:

1. When first creating a new challenge, you could think of the multiple solutions as checks that any unit test you write still passes for the solutions provided.

2. When modifying a challenge's tests, the multiple solutions double check you did not break anything that should still pass as a valid solution. 

A really good example of a challenge which probably needs many more multiple solutions would be https://learn.freecodecamp.org/javascript-algorithms-and-data-structures/es6/create-strings-using-template-literals.  I remember many contributors kept trying to get the correct regular expression written to allow various solutions.  They would "fix" one test and it would prevent another valid solution from passing.  If they would have had a way to test all known valid solutions against the tests being written, they would have created the correct set of unit tests the first time around.

**Pull request merged**
