### PR TITLE
chore(i18n,client): processed translations

### PR DESCRIPTION
**Pull request by camperbot**
This PR was opened auto-magically by Crowdin.

### CODE REVIEW

**Review by DanielRosa74 — DISMISSED** [review]
LGTM

**Comment by raisedadead** [comment]
@naomi-lgbt do you know how we can execute npm run-script for formatting the files once downloaded from Crowdin? Could this be done as a part of the workflow?

**Comment by raisedadead** [comment]
Also, should the bot have triggered with a misleading message, when it was me who added a commit to the branch? Should it be removed because it doesn't do much.

**Review by majestic-owl448 — APPROVED** [review]

**Comment by naomi-lgbt** [comment]
> Could this be done as a part of the workflow?

Sure - I'll prep a PR.

> Also, should the bot have triggered with a misleading message, when it was me who added a commit to the branch? Should it be removed because it doesn't do much.

That particular automation is helpful because it flags manual PRs that touch translated files. We could remove the comment on these PRs, though.

**Review by naomi-lgbt — APPROVED** [review]

**Pull request merged**
