### PR TITLE
Corrected a typo

### PR DESCRIPTION
**Pull request by sambhujimmi**
Checklist:

- [x] I have read [freeCodeCamp's contribution guidelines](https://contribute.freecodecamp.org).
- [x] My pull request has a descriptive title (not a vague title like `Update index.md`)
- [x] My pull request targets the `main` branch of freeCodeCamp.
- [x] I have tested these changes either locally on my machine, or GitPod.

Closes #XXXXX

### CODE REVIEW

**Comment by gikf** [comment]
Hey @sambhujimmi 

Could you go through checklist and make sure everything is in order?

Thank you and happy coding.

**Review by raisedadead — APPROVED** [review]
#### :sparkles: :sparkles: **AWESOME!** :sparkles: :sparkles: 

LGTM.

Thanks for this pull request, @sambhujimmi, and for contributing to the code-base for the first time.

We will be looking forward to more contributions in the future.

Cheers and happy contributing!

**Review by naomi-lgbt — APPROVED** [review]
Thanks for catching this~!

**Comment by nhcarrigan** [comment]
Congrats on your first pull request (PR)! 🎉

Thank you for your contribution to the page! 👍
We are happy to accept these changes and look forward to future contributions. 📝

**Pull request merged**
