### PR TITLE
feat(enhancement): Add community dialog to main navigation

### LINKED ISSUE #15792: Add "Community" dropdown to production
We want production's navigation to look like beta's. 

Currently in Beta we have this nice dropdown:

learn_to_code_and_help_nonprofits___freecodecamp

It automatically opens when you hover over it, and the width of the dropdown matches the width of the button above it.

Here are what the buttons should say and link to, in this order:
                        a(href='https://forum.freecodecamp.com', target='_blank') Forum
                        a(href='https://medium.freecodecamp.com', target='_blank') Medium
                        a(href='https://youtube.com/freecodecamp', target='_blank') YouTube
                        a(href='https://gitter.im/freecodecamp/home' target='_blank') Chat
                        a(href='https://forum.freecodecamp.com/t/free-code-camp-city-based-local-groups/19574', target='_blank') In your city
                        a(href='/contribute', target='_blank') Contribute
                        a(href='/about', target='_blank') About

### PR DESCRIPTION
**Pull request by adityaparab**
#### Pre-Submission Checklist

- [ ] Your pull request targets the `staging` branch of freeCodeCamp.
- [x] Branch starts with either `fix/`, `feature/`, or `translate/` (e.g. `fix/signin-issue`)
- [x] You have only one commit (if not, [squash](http://forum.freecodecamp.org/t/how-to-squash-multiple-commits-into-one-with-git/13231) them into one commit).
- [x] All new and existing tests pass the command `npm test`. Use `git commit --amend` to amend any fixes.

#### Type of Change

- [ ] Small bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds new functionality)
- [ ] Breaking change (fix or feature that would change existing functionality)
- [ ] Add new translation (feature adding new translations)

#### Checklist:

- [x] Tested changes locally.
- [x] Closes currently open issue (replace XXXX with an issue no): Closes #15792

#### Description
Added Community dropdown in main navigation bar and added styles

### CODE REVIEW

**Comment by QuincyLarson** [comment]
@adityaparab This looks great! 

I have some quick feedback:

1. The caret stands out too much, though. We don't need it, since when people click it they'll see the menu anyway. The caret doesn't communicate much information, but it does break up the flow of the menu. Could you remove the caret and update the width of the drop-down?

2. Could you expand the menu on-hover?

3. On smaller breakpoints, the text is left-adjusted instead of centered: 

learn_to_code_and_help_nonprofits___freecodecamp

Once you update the PR, I'll take another look. I am really excited about getting this into production.

**Comment by adityaparab** [comment]
@QuincyLarson sure.. will update the PR accordingly. However, regarding point 2 -
There is a problem to expand/collapse onhover as mentioned [here](https://github.com/freeCodeCamp/freeCodeCamp/issues/13450) and [here](https://github.com/freeCodeCamp/freeCodeCamp/issues/15844).

I think, on click is the right way. Please confirm.

**Comment by QuincyLarson** [comment]
@adityaparab The issue you linked me to was about the left-adjusted text instead of centered. Instead of having a sub-menu on smaller widths, could you just remove "community" and instead add the different community links below it, so that when the menu is expanded on mobile it look like this:

Map
Donate
Sign In
Forum
Medium
YouTube
Chat
In your city
Contribute
About

**Comment by adityaparab** [comment]
@QuincyLarson : Sure.. Will restructure the menu as per your new request.
Sorry if my previous message wasn't clear enough. My main concern in about when do we expand the menu. onclick or onhover. I prefer onclick.
But as per new structure, that question is void now. Will update the PR once I get off work.

**Comment by BerkeleyTrue** [comment]
@adityaparab Is it possible to do both onclick and onhover?

**Comment by QuincyLarson** [comment]
@adityaparab How is this PR coming along? This is high priority and we would like to merge it as soon as we can.

Since we recently launched the Guide, could we add a "Guide" option that links to https://guide.freecodecamp.org ?

**Comment by adityaparab** [comment]
@QuincyLarson Sure. Now that I'm back, I'll raise the PR tonight. The changes are done, just need to push them now.

**Comment by adityaparab** [comment]
@BerkeleyTrue : Not sure. Will check it today.

**Comment by QuincyLarson** [comment]
@adityaparab Awesome! This will be a big UX improvement, and help raise awareness of a lot of the less-well-known aspects of the freeCodeCamp community.

**Comment by adityaparab** [comment]
@QuincyLarson : I accidentally added 2 extra files that shouldn't be there. I'm a bit in hurry right now so I raised another PR with required changes. Closing this PR. Please follow #15937

**Pull request closed without merging**
