### PR TITLE
Change background color from 'gray' to 'silver'

### LINKED ISSUE #9510: Grey should be acceptable for Gray
For Give a Background Color to a Div Element the color gray could also be done as grey as it is spelled in certain places. Both give the right color to the background.

### PR DESCRIPTION
**Pull request by BKinahan**
#### Pre-Submission Checklist
- [x] Your pull request targets the `staging` branch of FreeCodeCamp.
- [x] Branch starts with `fix/`
- [x] You have only one commit
- [x] All new and existing tests pass the command `npm run test-challenges`. Use `git commit --amend` to amend any fixes.
#### Type of Change
- [x] Small bug fix (non-breaking change which fixes an issue)
#### Checklist:
- [x] Tested changes locally.
- [x] Closes #9510
#### Description

Replaced occurrences of `gray`/`gray-background` in challenge "Give a Background Color to a Div Element" to `silver`/`silver-background` to address `gray`/`grey` ambiguity. This includes occurrences of the English word `gray` in description translations, but each language's word for "gray" is unchanged; "silver" is specified as the correct English word in each case and the silver color is similar enough to gray that this should be a reasonable approximation until each translation is reviewed.

Tested locally.

### CODE REVIEW

**Comment by Bouncey** [comment]
### LGTM :+1:

**Comment by Bouncey** [comment]
A second look, you have missed some instances of `gray` in later challenges.

Please change them for consistency :+1:

**Comment by BKinahan** [comment]
I did see those but the challenges involved don't require the user's attention to the `gray` color (ie setting or changing it), so I left them as they were.

Now that you mention it though, it will be more consistent if the color of that section doesn't change mysteriously as a user progresses, and the lighter shade of the silver looks nicer, so I'll change them now 😄

**Comment by Bouncey** [comment]
#### LGTM :tada: 

Thanks for contributing :+1:

**Pull request merged**
