### PR TITLE
fix(docs): inconsistent spacing in theme_CSS

### PR DESCRIPTION
**Pull request by AirSayy**
Inconsistent Spacing in the code lines.

Checklist:

- [x] I have read [freeCodeCamp's contribution guidelines](https://contribute.freecodecamp.org).
- [x] My pull request has a descriptive title (not a vague title like `Update index.md`)
- [x] My pull request targets the `main` branch of freeCodeCamp.
- [x] I have tested these changes either locally on my machine, or GitPod.

Closes #XXXXX

### CODE REVIEW

**Review by Sboonny — APPROVED** [review]
#### :sparkles: :tada: **AWESOME!** :tada: :sparkles:

 Hi @AirSayy, thanks for this pull request and for contributing to the code-base for the first time. We are looking forward to more contributions from you in the future.

 Cheers & happy contributing!

**Comment by AirSayy** [comment]
> 

Thank you  @Sboonny

**Comment by ShaunSHamilton** [comment]
Thank you for taking the time to contribute.

Please edit your PR title to match our recommended convention: https://contribute.freecodecamp.org/#/how-to-open-a-pull-request?id=prepare-a-good-pr-title

**Comment by AirSayy** [comment]
> Thank you for taking the time to contribute.
> 
> Please edit your PR title to match our recommended convention: https://contribute.freecodecamp.org/#/how-to-open-a-pull-request?id=prepare-a-good-pr-title

ive made the changes

**Comment by Sboonny** [comment]
Hi @AirSayy, the title is `Update _theme.css` which isn't descriptive

**Comment by AirSayy** [comment]
> Hi @AirSayy, the title is `Update _theme.css` which isn't descriptive

kindly confirm my most recent change....

**Comment by Sboonny** [comment]
@AirSayy we follow this formula `<type>([optional scope(s)]): <description>`

So for your pr it can be something like `fix(docs): inconsistent spacing in theme_CSS `

**Comment by AirSayy** [comment]
> @AirSayy we follow this formula `<type>([optional scope(s)]): <description>`
> 
> So for your pr it can be something like `fix(docs): inconsistent spacing in theme_CSS `
> 
> Thank you for your patience and willingness to help

thank you sboonny for your patience too, im new here and its still a bit blur....i hope to be better each time..

**Review by naomi-lgbt — APPROVED** [review]
Let's go ahead and get this in.

__
[sema-logo](https://semasoftware.com/gh) &nbsp;**Summary:** :ok_hand: This code looks good

**Comment by AirSayy** [comment]
> Let's go ahead and get this in.
> 
> __ [sema-logo](https://semasoftware.com/gh) [ sema-logo ](https://semasoftware.com/gh) [ ](https://semasoftware.com/gh)  **Summary:** 👌 This code looks good

thanks naomi!!! i appreciate

**Pull request merged**
