### PR TITLE
Semantic versioning required

### LINKED ISSUE #36068: [curriculum] glitch doesn't allow version "1.0"
I noticed this while looking at another issue. Glitch is giving me an error when using version "1.0" in my package.json file. It only seems to work when I use a third number: "1.0.0" - I'm not sure if this has always been the case since I don't think it threw this error in the past. But [this challenge](https://learn.freecodecamp.org/apis-and-microservices/managing-packages-with-npm/add-a-version-to-your-package-json) suggests to use a two digit version. It should probably be changed if this isn't allowed.

EDIT: actually the project will still run with the invalid version - I thought it was causing the project not to run. But glitch does still give an error about it.

### PR DESCRIPTION
**Pull request by jagzmz**
Invalid version "1.2"

- [x] I have read [freeCodeCamp's contribution guidelines](https://github.com/freeCodeCamp/freeCodeCamp/blob/master/CONTRIBUTING.md).
- [x] My pull request has a descriptive title (not a vague title like `Update index.md`)
- [x] My pull request targets the `master` branch of freeCodeCamp.
- [x] None of my changes are plagiarized from another source without proper attribution.
- [x] All the files I changed are in the same world language (for example: only English changes, or only Chinese changes, etc.)
- [x] My changes do not use shortened URLs or affiliate links.

Closes #36068

### CODE REVIEW

**Review by ojeytonwilliams — APPROVED** [review]
LGTM :+1:

**Comment by ojeytonwilliams** [comment]
@jagzmz Thanks for submitting this.  I just added in the issue it closes, so that will happen automatically if this gets merged.

**Review by RandellDawson — APPROVED** [review]
LGTM

**Comment by RandellDawson** [comment]
Thank you for your contribution to the page! 👍
We're happy to accept these changes, and look forward to future contributions. 🎉

**Pull request merged**
