### PR TITLE
Fix: Typo on motivation json file for spanish

### PR DESCRIPTION
**Pull request by Mikadifo**
Checklist:
- [x] I have read [freeCodeCamp's contribution guidelines](https://contribute.freecodecamp.org).
- [x] My pull request has a descriptive title (not a vague title like `Update index.md`)
- [x] My pull request targets the `main` branch of freeCodeCamp.
- [x] All the files I changed are in the same world language, for example: only English changes, or only Chinese changes, etc.

Fixed missing accents on compliments and motivationalQuotes for spanish.

### CODE REVIEW

**Comment by RafaelDavisH** [comment]
LGTM 🥳
@Mikadifo Thank you for taking care of that.

**Review by RafaelDavisH — APPROVED** [review]
LGTM 🚀

**Review by naomi-lgbt — APPROVED** [review]
Looks good to me.

**Comment by nhcarrigan** [comment]
Thank you for your continued contribution to our project. We have reviewed your pull request and are happy to accept these changes.

Please continue to watch for issues labelled `help wanted`, as these will be additional opportunities to contribute.

**Pull request merged**
