### PR TITLE
fix(curriculum): Decimal to Binary Converter - combine step 103 and 104

### LINKED ISSUE #56587: Decimal to Binary Converter - Step 103 - Using template literal
### Describe the Issue

**Curriculum Name**
- Learn Recursion by Building a Decimal to Binary Converter

**Step**
- 103

**Problem**
Throughout the process, we have consistently passed strings to the getElementById method. On the other hand, the inputVal property in the objects within animationData is an integer. Along the way, we’ve rejected implicit type conversion and have enforced strict equality (===), even going so far as to explicitly convert values to String in some parts of the code. But now, all of a sudden, it’s asking to pass the integer value from the object directly. This doesn’t align with the overall approach we’ve taken so far.

For a seasoned developer, this might not be a problem. However, for someone less experienced, this could become an “unsolvable” issue.

In the previous step, we used backticks (``) to create a string and set the id for the <p> element. Naturally, we would expect to use the same backticks to create a string for getElementById when locating the element.

This process either needs additional explanation or the answer-checking method should be adjusted to improve consistency.

**Challenge Information**
- https://www.freecodecamp.org/learn/javascript-algorithms-and-data-structures-v8/learn-recursion-by-building-a-decimal-to-binary-converter/step-103

### Affected Page

https://www.freecodecamp.org/learn/javascript-algorithms-and-data-structures-v8/learn-recursion-by-building-a-decimal-to-binary-converter/step-103

### Your code

```

 // I write this code as a answer.
document.getElementById(`${obj.inputVal}`); 

// system recognize this as a answer.
document.getElementById(obj.inputVal);

```

### Expected behavior
```

// (1) most case write this because of previous step(literal format) and only use this method with "STRING"
document.getElementById(`${obj.inputVal}`); 

// (2) someone maybe write this code because he converted it to String
document.getElementById(String(obj.inputVal));

// (3) or more explanation needed : about implicitly casting
document.getElementById(obj.inputVal);

```
### Screenshots

_No response_

### System

- Device: Desktop
- OS: Windows 10
- Browser: Firefox
- Version: 131.0

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by altsun**
Checklist:

- [x] I have read and followed the [contribution guidelines](https://contribute.freecodecamp.org).
- [x] I have read and followed the [how to open a pull request guide](https://contribute.freecodecamp.org/how-to-open-a-pull-request/).
- [x] My pull request targets the `main` branch of freeCodeCamp.
- [x] I have tested these changes either locally on my machine, or GitPod.

Closes #56587

### Testing in local
Empty code
image

Code with no `.textContent`
image

Code that set textContents to wrong values
image

Correct code
image

### CODE REVIEW

**Comment by ilenia-magoni** [comment]
maybe the new combined step should have a new id?

**Comment by altsun** [comment]
> maybe the new combined step should have a new id?

I don't know why it's necessary. Could you please explain? Thanks

**Comment by ilenia-magoni** [comment]
Because it's different enough from both the old 103 and 104, it would make sense to register it as a different one instead of the old 104 moved of place

**Comment by altsun** [comment]
@ilenia-magoni Thanks, I've registered a new id

**Review by majestic-owl448 — APPROVED** [review]

**Review by a2937 — APPROVED** [review]

**Comment by a2937** [comment]
Thank you for your contribution to the page! 👍
We are happy to accept these changes and look forward to future contributions. 🎉

**Pull request merged**
