### PR TITLE
fix(a11y): mobile tab navigation

### PR DESCRIPTION
**Pull request by bbsmooth**
Checklist:

- [x] I have read and followed the [contribution guidelines](https://contribute.freecodecamp.org).
- [x] I have read and followed the [how to open a pull request guide](https://contribute.freecodecamp.org/#/how-to-open-a-pull-request).
- [x] My pull request targets the `main` branch of freeCodeCamp.
- [x] I have tested these changes either locally on my machine, or GitPod.

Closes #XXXXX

PR #51361 sort of upset the mobile tab navigation just a little, so this PR is just making it all better.

- Moved the preview pane toggle button out of the tablist. Only tabs should be in the tablist. Also, when focus is on a tab, the `Tab` key should put focus on its associated tabpanel, or the first focusable element in the tabpanel if appropriate. Having the preview pane toggle button in the tablist put it in the tab order between the tabs and the tabpanels and thus if either the code or console tab had focus, hitting `Tab` would put focus on the toggle button instead of the tabpanel. See my original PR #50961 for a more in depth discussion.
- Due to the `forceMount` property on the Preview tab, the Preview tabpanel was not being hidden properly when it was not active and thus it was navigable to screen readers when it shouldn't have been. I manually added the `hidden` property to the Preview tab when it is not active. We could also solve this using CSS `display: none` but I went with the `hidden` attribute since that's what the other tabpanels are using.
- I cleaned up the CSS a little.

### CODE REVIEW

**Comment by mmatsumoto1026** [comment]
I agree with your idea that moving the preview pane toggle button out of the tablist. 
And I would share several issues.

- It seems that the css code below is not working because there is a spase between `#mobile-layout` and `[data-haspreview='true']` so now the preview pane toggle button overlaps the preview tab button.

  ```css
  #mobile-layout [data-haspreview='true'] [role='tablist'] {
    width: calc(100% - 2rem);
  }
  ```

- And actually, the property `position: relative;` in `#mobile-layout` selector now breaks the appropriate positioning of tool panel buttons on mobile devices(e.g. iPhone or Android smart phone) in the challenge such as [JavaScript Algorithms and Data Structures/Basic JavaScript/Comment Your JavaScript Code](https://www.freecodecamp.org/learn/javascript-algorithms-and-data-structures/basic-javascript/comment-your-javascript-code), because the tool panel button is now positioned assuming that the positioning reference is the top left of the window or viewport.
(It seems that this issue will be solved by subtracting the navigation bar(56px) and breadcrumb(44px) height from the formula in `mobile-layout.tsx`, but the code needs to reference these values every time it position a tool panel button.)

- Also, on PC browser(e.g. Chrome, Firefox, edge) and on mobile layout, the tool panel buttons now overlaps the bottom part of test requirement in [the challenge](https://www.freecodecamp.org/learn/javascript-algorithms-and-data-structures/basic-javascript/comment-your-javascript-code). This issue was actually covertly resolved in [another PR](https://github.com/freeCodeCamp/freeCodeCamp/pull/51527), but it is happening again. In another PR, this issue was solved by adding the properties `display: flex;` and `flex-direction: column;` in the `#mobile-layout .tab-content[data-state='active']` selector.

**Comment by bbsmooth** [comment]
> * It seems that the css code below is not working because there is a spase between `#mobile-layout` and `[data-haspreview='true']`

Whoops. Don't know how that happened. Good catch.

**Comment by bbsmooth** [comment]
> the property `position: relative;` in `#mobile-layout` selector now breaks the appropriate positioning of tool panel buttons on mobile devices

Good catch. I didn't quite test enough, did I :slightly_smiling_face: . I have removed relative positioning from `#mobile-layout` and instead just pushed the toggle button down from the top of the view port.

**Comment by bbsmooth** [comment]
I had to override the side padding defaults on the tab buttons. The default was `0.625rem` (using Tailwind's `px-2.5` class). But when you have four tabs plus the preview toggle button then there wasn't enough room for all of them at narrow view port widths because the side padding on the buttons was preventing them from narrowing enough to make room for the preview toggle button. Turning the side padding down to `0.2rem` seems to do the job.

**Comment by bbsmooth** [comment]
> on PC browser(e.g. Chrome, Firefox, edge) and on mobile layout, the tool panel buttons now overlap the bottom part of test requirement

This is currently happening on production, right? If so, then I think this should be addressed in a separate PR since it isn't directly related to the tabs.

Actually, I just checked this in my dev build with this PR and I'm not seeing that issue any more. I don't think I have done anything that would affect this. When you run this PR are you seeing it fixed as well?

**Comment by bbsmooth** [comment]
Also, I just noticed that on production, when you are viewing a JS ADS lesson in mobile view, the preview toggle button is displayed even though there is no preview pane. So this PR also fixes that issue.

**Comment by mmatsumoto1026** [comment]
Thanks for your coding efforts, @bbsmooth.

After testing the code, I think now all issues that I mentioned above, and at the same time original issues you mentioned in description of this PR are solved.

> Actually, I just checked this in my dev build with this PR and I'm not seeing that issue any more. I don't think I have done anything that would affect this. When you run this PR are you seeing it fixed as well?

Sorry, when checking code of this PR, I was comparing the current freeCodeCamp production page and this PR's gitpod page, and at that time I think I saw the issue(the tool panel buttons overlap the bottom part of test requirement) that remained on the production page, but I misunderstood that it recurred in this PR. Now I can not see this issue on the page when I run this PR with gitpod so it was fixed.(I've tested the code on PC, Android simulator, and iPhone SE.)

And the code shown below is really cool as it can avoid that the tab buttons placement being broken in narrow window width(under 340px, maybe), also I would like to suggest that we should follow the [Codebase best practices of fCC](https://contribute.freecodecamp.org/#/codebase-best-practices?id=rtl-support) so we can use `padding-inline: 0.2rem;` to make the code RTL friendly and less.

  ```css
    /* Need to override radix-ui defaults on side padding to allow room for
       four tabs and a preview toggle button at narrow view ports */
    padding-left: 0.2rem;
    padding-right: 0.2rem;
  ```

> Also, I just noticed that on production, when you are viewing a JS ADS lesson in mobile view, the preview toggle button is displayed even though there is no preview pane. So this PR also fixes that issue.

I confirmed this. It seems that the preview pane toggle button does not need if there is no preview pane so I agree this fix.

**Comment by Sboonny** [comment]
There is a misunderstanding of the context of the best practices, it only applies if there is a single padding property applied to a side of the element `padding-right` without `padding-left`, or `padding-right` having different value than `padding-left`, then the best practices should be respected.

Although the PR do leave something to be desired about RTL. In general, it should be ignored, I have added it because I thought that the Arabic language is going to be live soon, but it hasn't and there is no deployed website for it. 

It should be safely ignored, until there is an Arabic or another RTL language in the production.

**Comment by mmatsumoto1026** [comment]
> RTL should be safely ignored, until there is an Arabic or another RTL language in the production.

I blindly thought that I had to add `inline` to `margin` and `padding`, but now I realized the values of `padding-left` and `padding-right` are same. So I agree that my suggestion above should be safely ignored. Sorry for my misunderstanding of the context of the best practices.

**Review by Sboonny — APPROVED** [review]
Thank you for awesome work.

**Review by ojeytonwilliams — APPROVED** [review]
Thanks, @bbsmooth, this LGTM :+1:

**Pull request merged**
