### PR TITLE
Add commitizen and npm commit script

### PR DESCRIPTION
**Pull request by ricmello**
Adds the npm script `commit`, that execute commitizen. The script is described in [README.md](https://github.com/freeCodeCamp/freeCodeCamp/blob/master/docs/README.md) but did not existed in `package.json`.

- [x] I have read [freeCodeCamp's contribution guidelines](https://github.com/freeCodeCamp/freeCodeCamp/blob/master/CONTRIBUTING.md).
- [x] My pull request has a descriptive title (not a vague title like `Update index.md`)
- [x] My pull request targets the `master` branch of freeCodeCamp.
- [x] None of my changes are plagiarized from another source without proper attribution.
- [x] My article does not contain shortened URLs or affiliate links.

### CODE REVIEW

**Comment by raisedadead** [comment]
Hi @ricardo-mello 

Thanks a lot for adding these. We have been using this in the past in the other packages and they are still available in the curriculum package in this lerna monorepo.

We need to move around a lot of the dev tooling.

I'll keep this blocked, until we get around the cleanup. You are of course more than welcome to dig around update this PR making additional changes to help us.

**Comment by RandellDawson** [comment]
@raisedadead What are the next steps for this PR?

**Comment by raisedadead** [comment]
> What are the next steps for this PR?

The dev/build logic and related dev packages have to moved to the root of the repo. This means, revisiting the existing tooling, DX and the logic and cleaning up what we do not need and moving what we do to the repo root or `/tools` where possible.

**Comment by raisedadead** [comment]
This PR is a good place to start and hence left open and blocked.

**Comment by thecodingaviator** [comment]
@raisedadead are we still thinking about landing this sometime?

**Comment by raisedadead** [comment]
Yes.

**Review by Bonniebiotch — APPROVED** [review]

**Pull request closed without merging**
