### PR TITLE
Corrected answer to question re: Moore's Law

### PR DESCRIPTION
**Pull request by MDAWebDev**
Intel confirmed in 2015 that the pace of advancement has slowed, starting at the 22 nm feature width around 2012, and continuing at 14 nm. Brian Krzanich, CEO of Intel, announced that "our cadence today is closer to two and a half years than two.” This is scheduled to hold through the 10 nm width in late 2017.

http://blogs.wsj.com/digits/2015/07/16/intel-rechisels-the-tablet-on-moores-law/

### CODE REVIEW

**Comment by ltegman** [comment]
Please correct your build failure.

**Comment by MDAWebDev** [comment]
Build error? How is that possible? I literally just edited two lines of text. Nothing else was touched.

**Comment by QuincyLarson** [comment]
@MDAWebDev Nice find! I hadn't realized that Moore's law no longer held. We should definitely include it! Yes, you have a build failure (you probably included or omitted a comma where you shouldn't have, breaking the JSON):

```
    error [SyntaxError: /home/travis/build/FreeCodeCamp/FreeCodeCamp/seed/challenges/04-video-challenges/computer-basics.json: Unexpected token 
    ]
```

**Comment by erictleung** [comment]
@MDAWebDev You're ending the string with a single quote instead of a double quote.

**Comment by MDAWebDev** [comment]
Ah, good catch. Should have caught that. I'm still pretty new to this.

**Comment by erictleung** [comment]
No worries. We have to start somewhere. Also, they'll probably ask you to [squash](https://github.com/FreeCodeCamp/FreeCodeCamp/wiki/git-rebase#squashing-multiple-commits-into-one) your commits into one.

**Comment by ltegman** [comment]
Yup! Once you squash your commits though this looks good to go :+1:

**Comment by MDAWebDev** [comment]
Ok, I think I've got it squashed. Do I have to make a new pull request?

**Comment by ltegman** [comment]
@MDAWebDev You've actually added in new merge commits that you won't be able to squash out, so you'll need to revert those and then squash. Although it might be easier to start over on a fresh branch off staging.

**Comment by MDAWebDev** [comment]
So in other words make a new fork, do the edit again, and make a new pull request?

**Comment by ltegman** [comment]
@MDAWebDev That would probably be the easiest way, yes. In the future please do your work from a named branch off `staging` instead of directly on `staging`. This both gives us more informative commits and prevents you from needing to refork if something goes wrong on your forks staging branch.

**Pull request closed without merging**
