### PR TITLE
Add Localization support

### PR DESCRIPTION
**Pull request by takkuumi**
This  is an auto-switch function. 

First, you need to config the `localization.json` file. Add your localization jade file into `localization.json` (like `locals->zh->views`,the view field is an Array).

When you access FreeCodeCamp, the router can get your userAgent.Then, the router will take you to localization page.If there is no this page in the config file,It will be use the english instead.

### CODE REVIEW

**Comment by BerkeleyTrue** [comment]
Instead of duplicating the same view over and over again, can you instead make the logic smart enough in the controller to choose the appropriate language.

**Comment by BerkeleyTrue** [comment]
Also, can you add the new translations in a separate PR?

**Comment by NateLing** [comment]
Yes,I will translate all the challenges into chinese.

**Comment by BerkeleyTrue** [comment]
After a discussion we've decided this is not the way we will go for internationalization. 

Please submit the translations in a separate PR.

**Pull request closed without merging**
