### PR TITLE
feat(curriculum): add spy helpers

### PR DESCRIPTION
**Pull request by awu43**
Checklist:

- [x] I have read [freeCodeCamp's contribution guidelines](https://contribute.freecodecamp.org).
- [x] My pull request has a descriptive title (not a vague title like `Update index.md`)
- [x] My pull request targets the `main` branch of freeCodeCamp.
- [x] I have tested these changes either locally on my machine, or GitPod.

Pinging @ShaunSHamilton. As you may have already seen, while resolving #42522 @ojeytonwilliams brought up how the usual spy/mocking tools aren't available for curriculum tests and the possibility of writing custom replacement(s). Think this is worth looking into?

### CODE REVIEW

**Comment by ojeytonwilliams** [comment]
This looks promising, thanks @awu43. @nhcarrigan do you think this would help with the curriculum tests?

**Comment by ShaunSHamilton** [comment]
Sorry, for only seeing this now. I have not debugged, but this code does not return what I expect:
```javascript
const code = `function ran() {
  return Math.random();
}
ran();
`

console.log(isCalledWithNoArgs('ran', code)) // false
```

**Comment by awu43** [comment]
@ShaunSHamilton I probably should have mentioned that the initial version I posted was an untested idea as a conversation starter, but I believe I've fixed it.

**Comment by ShaunSHamilton** [comment]
> ...spy/mocking tools aren't available for curriculum tests and the possibility of writing custom replacement(s). Think this is worth looking into?

In my opinion, having more helpers for the tests would be excellent, but I would not see the net benefit _re-producing_ a library like Sinon, because the times we might prefer to use it are few and far between. At the end of the day, we have surprisingly few unique tests; we just test for the same thing in so many unique ways.

Summary: More helpers gets a 👍 from me. However, replicating the functionality of Sinon, I do not recommend.

_Side Note: At some point we will need to properly document the helpers, else no one will use them._

**Comment by ojeytonwilliams** [comment]
Just to nail this down and avoid confusion, are you happy with the addition of this helper @ShaunSHamilton?  Correct me if I'm wrong @awu43, but I don't believe the plan to to recreate Sinon, just to create some specific replacements like this.

**Comment by ShaunSHamilton** [comment]
> are you happy with the addition of this helper @ShaunSHamilton?

I would be fine with adding this.

Something to keep in mind is I can only see 2 challenges where this can be used. That is, for future helpers, it might be best taking some time to look at the common things tests check for.

**Comment by ojeytonwilliams** [comment]
Thanks, Shaun, that makes sense.  @awu43 please let us know if you need any further feedback.  Also, if possible, could you update any challenge tests that you think could benefit from this helper?  Presumable create-a-controlled-form.md at least.

**Comment by awu43** [comment]
> Correct me if I'm wrong @awu43, but I don't believe the plan to to recreate Sinon, just to create some specific replacements like this.

That was my understanding, that specific helpers would be created as needed. Definitely not trying to recreate all of Sinon.

**Comment by ojeytonwilliams** [comment]
Perfect.  Do you want to modify the challenge(s) in this PR?  That way we get confirmation that the helper works and a demonstration of how to use it for other challenges.

**Comment by awu43** [comment]
@ojeytonwilliams Apologies for the delay. I've added some tests and also manually tested in the create a controlled form challenge and everything seems to be working as expected. Any other challenges that can use this helper?

**Review by ShaunSHamilton — APPROVED** [review]
To me, this makes sense as is. LGTM 👍 

Thank you, for your work on this.

**Review by ojeytonwilliams — APPROVED** [review]
LGTM :+1: Nice work, @awu43

**Comment by lasjorg** [comment]
Both implementations (current and this PR) using `MyForm.prototype.handleSubmit` does not support arrow function syntax.

```
handleSubmit = (event) => {
  event.preventDefault()
  this.setState({
    submit: this.state.input
  })
}
```

The code will fail the test as the method is not on the prototype ([more info](https://www.charpeni.com/blog/arrow-functions-in-class-properties-might-not-be-as-great-as-we-think)). I didn't test it with this PRs code but I would assume it fails the same as the current implementation does.

Forum post: https://forum.freecodecamp.org/t/test-is-not-read-me-eventpreventdefault/469784

**Comment by awu43** [comment]
Respectfully, I don't believe changes should be made in response to issues that arise when code is changed outside of the given boundaries (converting `handleSubmit()` to an arrow function being one such change).

**Comment by lasjorg** [comment]
I agree that altering the method definitions is outside the scope of the challenge requirements and as such it's not our fault if the tests fail.

I'm simply reporting it because working code with valid syntax is failing. Personally, I would just prefer if the tests didn't fail.

**Comment by ShaunSHamilton** [comment]
@lasjorg Thanks, for reporting this. Ideally, the tests should allow working code to pass.

That being said, as this lesson stands, I would not change the test, because it is abundantly clear what should be changed, and what should not.

Unfortunately, we are going to have to look at the fact that this curriculum is going to be legacy, and the new curriculum is not likely to cover class-based components - arrow functions will be everywhere (my assumption). So, as this helper stands, I cannot see it being used anywhere outside of this one (legacy) lesson.

---

All this to say, we should take some time to refine the approach, and make helpers as useful/robust as possible.

**Comment by lasjorg** [comment]
The methods are on the instance so I would think that might be an option.

`new MyForm().handleSubmit`

**Pull request merged**
