### PR TITLE
[Russian]Improved translate in Standardize Times with the HTML5 datet…

### PR DESCRIPTION
**Pull request by greggubarev**
…ime Attribute

[Russian]Improved translate in Standardize Times with the HTML5 datetime Attribute

- [x] I have read [freeCodeCamp's contribution guidelines](https://github.com/freeCodeCamp/freeCodeCamp/blob/master/CONTRIBUTING.md).
- [x] My pull request has a descriptive title (not a vague title like `Update index.md`)
- [x] My pull request targets the `master` branch of freeCodeCamp.
- [x] None of my changes are plagiarized from another source without proper attribution.
- [x] My article does not contain shortened URLs or affiliate links.

If your pull request closes a GitHub issue, replace the XXXXX below with the issue number.

Closes #XXXXX

### CODE REVIEW

**Comment by greggubarev** [comment]
Content LGTM, but still needs review for frontmatter/filepath syntax.

**Comment by ValeraS** [comment]
1. Why have you replaced `"` by `'`?
1. Do you think it is a natural Russian language?

And I can ask the last question to all your PRs.

**Comment by greggubarev** [comment]
@ValeraS 
1. In some PR it helped me get around the error
2. in my PR, I try to remove significant errors, I think this is the main thing at this stage

**Comment by greggubarev** [comment]
@ValeraS can you or someone else merge this PR? It has been hanging for a long time, and I need to work on earlier ones

**Pull request closed without merging**
