### PR TITLE
Improve readme to avoid setting up confusion

### PR DESCRIPTION
**Pull request by junhaoyap**
Related to #2976

### CODE REVIEW

**Comment by BerkeleyTrue** [comment]
@junhaoyap Thanks but Gulp should fine on first run. If there is a problem it should be fixed. I'll take a look at the issue and try to push a fix.

Happy Coding!

**Comment by ltegman** [comment]
I think the problem (as I've experienced it) is that `node seed/` fails until you've run gulp, but gulp fails until you run `node seed/`, so you have run gulp first, let it fail, and then `node seed/` will work and set you up for a successful gulp.

**Comment by BerkeleyTrue** [comment]
Those two tasks are unrelated

**Comment by BerkeleyTrue** [comment]
@ltegman let's discuss in Gitter

**Pull request closed without merging**
