### PR TITLE
fix (curriculum): added top level label-input pair to challenge

### LINKED ISSUE #41637: Unnecessary for/id attributes in Basic HTML and HTML5
**Describe your problem and how to reproduce it:**

Form challenges in the Basic HTML and HTML5 course suggest using `for` attributes on form labels:

> It is considered best practice to set a `for` attribute on the label element, with a value that matches the value of the `id` attribute of the input element.

However, this is only true when inputs are not nested within labels. When using nesting, this relationship is created implicitly - see https://developer.mozilla.org/en-US/docs/Web/HTML/Element/label

Therefore, the following example in the link below:

```html
<label for="indoor"> 
  <input id="indoor" type="radio" name="indoor-outdoor">Indoor 
</label>
```

should either be removed in favour of keeping only the first example (which features a nested label without explicit association), or replaced with a non-nested version (often preferred in real-world scenarios due to more styling control):

```html
<input id="indoor" type="radio" name="indoor-outdoor">
<label for="indoor">Indoor</label>
```

**Why I feel this is important:**

For a beginner learning HTML, explicit relationships using attributes introduce additional cognitive load and are unnecessary due to the implicit relationship created by nesting. They could also create confusion when the `name` and `value` attributes are introduced later - in the context of forms, `name` or `value` often share the same value with `id`, so they could be mixed up easily by a beginner.

**Additional notes:**

I have tested with VoiceOver on macOS and NVDA on Windows, across Chrome and Firefox (both systems) and Safari (on macOS), and confirmed that input labels are read aloud correctly when using implicit association.

**Add a Link to the page with the problem:**

https://www.freecodecamp.org/learn/responsive-web-design/basic-html-and-html5/create-a-set-of-radio-buttons
(and subsequent form-based challenges)

**Tell us about your browser and operating system:**

Screen reader support for nested labels tested across the following browsers:

```
Browser Name: Google Chrome
Browser Version: 89.0.4389.90 (Official Build) (arm64)
Operating System: macOS Big Sur 11.3 Beta (20E5217a)
```

```
Browser Name: Firefox
Browser Version: 87.0 (64-bit)
Operating System: macOS Big Sur 11.3 Beta (20E5217a)
```

```
Browser Name: Safari
Browser Version: 14.1 (16611.1.21.1.12)
Operating System: macOS Big Sur 11.3 Beta (20E5217a)
```

```
Browser Name: Google Chrome
Browser Version: 89.0.4389.90 (Official Build) (64-bit)
Operating System: Windows 10 Pro 20H2 19042.906
```

```
Browser Name: Firefox
Browser Version: 87.0 (64-bit)
Operating System: Windows 10 Pro 20H2 19042.906
```

**If possible, add a screenshot here (you can drag and drop, png, jpg, gif, etc. in this box):**

See code examples above

### PR DESCRIPTION
**Pull request by hassaanp**
Checklist:

- [x] I have read [freeCodeCamp's contribution guidelines](https://contribute.freecodecamp.org).
- [x] My pull request has a descriptive title (not a vague title like `Update index.md`)
- [x] My pull request targets the `main` branch of freeCodeCamp.
- [x] All the files I changed are in the same world language, for example: only English changes, or only Chinese changes, etc.

Closes #41637

### CODE REVIEW

**Review by ShaunSHamilton — CHANGES_REQUESTED** [review]
As the example immediately below does not show a `parent > child` relationship, I think it is best to change this.

**Comment by raisedadead** [comment]
Hey @hassaanp welcome back! I hope the family and baby girl are healthy and doing great :)

**Comment by hassaanp** [comment]
> Hey @hassaanp welcome back! I hope the family and baby girl are healthy and doing great :)

Thank you @raisedadead, yes they are doing great!
Good to be back :smile:

**Review by ShaunSHamilton — APPROVED** [review]
This LGTM 👍 . Thanks, hassaanp.

**Review by gikf — APPROVED** [review]
LGTM :+1:

**Pull request merged**
