### PR TITLE
Fix test to fail on incorrect input

### LINKED ISSUE #4981: Incorrect input still passes the test
Challenge [Waypoint: Add Font Awesome Icons to our Buttons](http://www.freecodecamp.com/challenges/waypoint-add-font-awesome-icons-to-our-buttons#?solution=%3Clink%20href%3D%22http%3A%2F%2Ffonts.googleapis.com%2Fcss%3Ffamily%3DLobster%22%20rel%3D%22stylesheet%22%20type%3D%22text%2Fcss%22%3E%0A%3Cstyle%3E%0A%20%20h2%20%7B%0A%20%20%20%20font-family%3A%20Lobster%2C%20Monospace%3B%0A%20%20%7D%0A%0A%20%20.thick-green-border%20%7B%0A%20%20%20%20border-color%3A%20green%3B%0A%20%20%20%20border-width%3A%2010px%3B%0A%20%20%20%20border-style%3A%20solid%3B%0A%20%20%20%20border-radius%3A%2050%25%3B%0A%20%20%7D%0A%3C%2Fstyle%3E%0A%0A%3Cdiv%20class%3D%22container-fluid%22%3E%0A%20%20%3Cdiv%20class%3D%22row%22%3E%0A%20%20%20%20%3Cdiv%20class%3D%22col-xs-8%22%3E%0A%20%20%20%20%20%20%3Ch2%20class%3D%22text-primary%20text-center%22%3ECatPhotoApp%3C%2Fh2%3E%0A%20%20%20%20%3C%2Fdiv%3E%0A%20%20%20%20%3Cdiv%20class%3D%22col-xs-4%22%3E%0A%20%20%20%20%20%20%3Ca%20href%3D%22%23%22%3E%3Cimg%20class%3D%22img-responsive%20thick-green-border%22%20src%3D%22https%3A%2F%2Fbit.ly%2Ffcc-relaxing-cat%22%3E%3C%2Fa%3E%0A%20%20%20%20%3C%2Fdiv%3E%0A%20%20%3C%2Fdiv%3E%0A%20%20%3Cimg%20src%3D%22http%3A%2F%2Fbit.ly%2Ffcc-running-cats%22%20class%3D%22img-responsive%22%3E%0A%20%20%3Cdiv%20class%3D%22row%22%3E%0A%20%20%20%20%3Cdiv%20class%3D%22col-xs-4%22%3E%0A%20%20%20%20%20%20%3Cbutton%20class%3D%22btn%20btn-block%20btn-primary%22%20%3ELike%3C%2Fbutton%3E%0A%20%20%20%20%20%20%3Cbutton%3E%3Ci%20class%3D%22fa%20fa-thumbs-up%22%3C%2Fi%3E%3C%2Fbutton%3E%0A%20%20%20%20%3C%2Fdiv%3E%0A%20%20%20%20%3Cdiv%20class%3D%22col-xs-4%22%3E%0A%20%20%20%20%20%20%3Cbutton%20class%3D%22btn%20btn-block%20btn-info%22%3EInfo%3C%2Fbutton%3E%0A%20%20%20%20%3C%2Fdiv%3E%0A%20%20%20%20%3Cdiv%20class%3D%22col-xs-4%22%3E%0A%20%20%20%20%20%20%3Cbutton%20class%3D%22btn%20btn-block%20btn-danger%22%3EDelete%3C%2Fbutton%3E%0A%20%20%20%20%3C%2Fdiv%3E%0A%20%20%3C%2Fdiv%3E%0A%20%20%3Cp%3EThings%20cats%20%3Cspan%20class%3D%22text-danger%22%3Elove%3A%3C%2Fspan%3E%3C%2Fp%3E%0A%20%20%3Cul%3E%0A%20%20%20%20%3Cli%3Ecat%20nip%3C%2Fli%3E%0A%20%20%20%20%3Cli%3Elaser%20pointers%3C%2Fli%3E%0A%20%20%20%20%3Cli%3Elasagna%3C%2Fli%3E%0A%20%20%3C%2Ful%3E%0A%20%20%3Cp%3ETop%203%20things%20cats%20hate%3A%3C%2Fp%3E%0A%20%20%3Col%3E%0A%20%20%20%20%3Cli%3Eflea%20treatment%3C%2Fli%3E%0A%20%20%20%20%3Cli%3Ethunder%3C%2Fli%3E%0A%20%20%20%20%3Cli%3Eother%20cats%3C%2Fli%3E%0A%20%20%3C%2Fol%3E%0A%20%20%3Cform%20fccfaa%3D%22%2Fsubmit-cat-photo%22%3E%0A%20%20%20%20%3Clabel%3E%3Cinput%20type%3D%22radio%22%20name%3D%22indoor-outdoor%22%3E%20Indoor%3C%2Flabel%3E%0A%20%20%20%20%3Clabel%3E%3Cinput%20type%3D%22radio%22%20name%3D%22indoor-outdoor%22%3E%20Outdoor%3C%2Flabel%3E%0A%20%20%20%20%3Clabel%3E%3Cinput%20type%3D%22checkbox%22%20name%3D%22personality%22%3E%20Loving%3C%2Flabel%3E%0A%20%20%20%20%3Clabel%3E%3Cinput%20type%3D%22checkbox%22%20name%3D%22personality%22%3E%20Lazy%3C%2Flabel%3E%0A%20%20%20%20%3Clabel%3E%3Cinput%20type%3D%22checkbox%22%20name%3D%22personality%22%3E%20Crazy%3C%2Flabel%3E%0A%20%20%20%20%3Cinput%20type%3D%22text%22%20placeholder%3D%22cat%20photo%20URL%22%20required%3E%0A%20%20%20%20%3Cbutton%20type%3D%22submit%22%3ESubmit%3C%2Fbutton%3E%0A%20%20%3C%2Fform%3E%0A%3C%2Fdiv%3E%0A) has an issue.
User Agent is: <code>Mozilla/5.0 (Macintosh; Intel Mac OS X 10_11_1) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/47.0.2526.73 Safari/537.36</code>.
Please describe how to reproduce this issue, and include links to screenshots if possible.

My code:
```html
... 
 <div class="row">
    <div class="col-xs-4">
      <button class="btn btn-block btn-primary" >Like</button>
      <button><i class="fa fa-thumbs-up"</i></button>
    </div>
    ...
 

```
As you can see, the code does not really make any sense but can still pass the test and I get 4 "thumbs-up" icons as result.

### PR DESCRIPTION
**Pull request by LenaBarinova**
In 'Waypoint: Add Font Awesome Icons to our Buttons' challenge changed a test to check whether <i> element is within Like button (did it the same way as it is done in 'Waypoint: Add Font Awesome Icons to all of our Buttons' challenge). 
closes #4981

### CODE REVIEW

**Comment by SaintPeter** [comment]
Don't you need to do the prior test as well as the new test?  It looks like you're testing to make sure it's in a button, but now it could be any button, not just the `like` button.

**Comment by LenaBarinova** [comment]
I'm checking the button of a class ```.btn-primary```, which is our ```like``` button's class.

**Comment by SaintPeter** [comment]
Yes, but the example was someone creating a whole new button.  If they could do that, they could create a copy of the button's classes as well.  

Maybe I'm being over sensitive.  @ltegman, @bugron ?

**Comment by bugron** [comment]
Agreed with @SaintPeter. We need both of these tests. You can combine them: `$(\"i.fa-thumbs-up\").parent().text().match(/Like/gi) && $(\".btn-primary > i\").hasClass(\"fa fa-thumbs-up\")` or just left first test case unchanged and add second one with `$(\".btn-primary > i\").hasClass(\"fa fa-thumbs-up\")`. Being more precise is better.

**Comment by bugron** [comment]
@LenaBarinova OK, but now your second test check for the `Link` text too. Remove `$(\"i.fa-thumbs-up\").parent().text().match(/Like/gi) &&` from your second test, then run these commands:
```
git add .
git commit --amend
```
and then force push your branch to your fork: `git push -f YOUR_BRANCH_NAME`.

**Comment by LenaBarinova** [comment]
I've appended the test, didn't create new one, since we are checking the same logical thing - ```fa-thumbs-up``` icon should be located within the Like button.

**Comment by bugron** [comment]
@LenaBarinova oh, yes, sorry, my fault.

**Comment by bugron** [comment]
I've verified that this works. After you [squash](https://github.com/FreeCodeCamp/FreeCodeCamp/wiki/git-rebase#squashing-multiple-commits-into-one) your commits into one I'm ready to merge your PR.

**Comment by LenaBarinova** [comment]
@bugron all done!

**Comment by LenaBarinova** [comment]
@bugron Thanks for the help! It was first commit, I hope further commits will go more smoothly :)

**Pull request merged**
