### PR TITLE
fix: basic-html-and html5 challenge arabic - test

### PR DESCRIPTION
**Pull request by aditijoshi14**
- [X] I have read [freeCodeCamp's contribution guidelines](https://github.com/freeCodeCamp/freeCodeCamp/blob/master/CONTRIBUTING.md).
- [X] My pull request has a descriptive title (not a vague title like `Update index.md`)
- [X] My pull request targets the `master` branch of freeCodeCamp.
- [X] None of my changes are plagiarized from another source without proper attribution.
- [X] All the files I changed are in the same world language (for Arabic)
- [X] My changes do not use shortened URLs or affiliate links.

Closes part of issue #18007 (Language: Arabic)
Associated with #35234

### CODE REVIEW

**Comment by aditijoshi14** [comment]
@boudlal Since you have reviewed other PRs related to Arabic translation, I just wanted to check if you have time to look at this PR. Thank you in advance!

**Comment by aditijoshi14** [comment]
@boudlal Thank you so much improving the quality of translation.

**Comment by RandellDawson** [comment]
@boudlal I can confirm the textString code portion is correct.  This PR duplicates the code used in PR #35441 which has already been tested locally and works.  Go ahead and merge if you are satisfied with the current translation.

**Comment by boudlal** [comment]
@aditijoshi14 Thank you for your contribution

**Pull request merged**
