### PR TITLE
Updated the test case for better flexibility.

### LINKED ISSUE #8586: Use Bracket Notation to Find the First Character in a String
Use Bracket Notation to Find the First Character in a String

https://www.freecodecamp.com/challenges/use-bracket-notation-to-find-the-first-character-in-a-string#?solution=%0A%2F%2F%20Example%0Avar%20firstLetterOfFirstName%20%3D%20%22%22%3B%0Avar%20firstName%20%3D%20%22Ada%22%3B%0A%0AfirstLetterOfFirstName%20%3D%20firstName%5B0%5D%3B%0A%0A%2F%2F%20Setup%0Avar%20firstLetterOfLastName%20%3D%20%22%22%3B%0Avar%20lastName%20%3D%20%22Lovelace%22%3B%0A%0A%2F%2F%20Only%20change%20code%20below%20this%20line%0AfirstLetterOfLastName%20%3D%20lastName%5BlastName.length%20-%20lastName.length%5D%3B%0A%0A

Based on the criterion of the challenge and while not the most concise, this should be an acceptable answer...

```
firstLetterOfLastName = lastName[lastName.length - lastName.length];
```

* Browser Name, Version: Chrome, Version 50.0.2661.94 m
* Operating System: Windows 7
* Mobile, Desktop, or Tablet: Desktop, but replicated on mobile device

image

### PR DESCRIPTION
**Pull request by pranayberry**
#### Pre-Submission Checklist

- [x] Your pull request targets the `staging` branch of FreeCodeCamp.
- [x] Branch starts with either `fix/`, `feature/`, or `translate/` (e.g. `fix/signin-issue`)
- [x] You have only one commit (if not, [squash](https://github.com/FreeCodeCamp/FreeCodeCamp/wiki/git-rebase#squashing-multiple-commits-into-one) them into one commit).
- [x] All new and existing tests pass the command `npm run test-challenges`. Use `git commit --amend` to amend any fixes.
#### Type of Change

- [x] Small bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds new functionality)
- [ ] Breaking change (fix or feature that would change existing functionality)
- [ ] Add new translation (feature adding new translations)
#### Checklist:

- [x] Tested changes locally.
- [x] Closes currently open issue (replace XXXX with an issue no): Closes #8586 
#### Description

Changed the test case which checks for the use of bracket notation. Now it can accept anything within the square bracket such that more complex arithmetic statements can also be accepted within the square brackets.

### CODE REVIEW

**Comment by ltegman** [comment]
This solves the bug perfectly, but would you ever mind changing the test of "Use Bracket Notation to Find the Nth Character in a String" to match this one?

**Comment by pranayberry** [comment]
@ltegman Should I include that also in this PR?

**Comment by ltegman** [comment]
@pranayberry If you don't mind.

**Comment by pranayberry** [comment]
@ltegman Yeah sure

**Comment by ltegman** [comment]
Awesome -- I gave this a test and it looks good. Thanks!

**Comment by pranayberry** [comment]
Thanks :smile:

**Pull request merged**
