### PR TITLE
Contribution to [HACKTOBERFEST 2024] - Git Quiz #56235

### PR DESCRIPTION
**Pull request by farihaNaqvi**
Checklist:

- [ ] I have read and followed the [contribution guidelines](https://contribute.freecodecamp.org).
- [ ] I have read and followed the [how to open a pull request guide](https://contribute.freecodecamp.org/how-to-open-a-pull-request/).
- [x] My pull request targets the `main` branch of freeCodeCamp.
- [x] I have tested these changes either locally on my machine, or GitPod.

### CODE REVIEW

**Comment by farihaNaqvi** [comment]
can you please please remove the spam tag as this was my first time hacktoberfest contribution

**Comment by ilenia-magoni** [comment]
you opened 2 more PRs after the first one was closed, showing you do not pay any attention to feedback received. You need to show changed behaviour.

**Comment by farihaNaqvi** [comment]
Actually it was done in the same period and i thought there was issue from my side this is why i am facing this now. i would be grateful if you help me on this for the last time.
Apologize

**Comment by ilenia-magoni** [comment]
two PR, #56375 and #56379 opened 15 hours ago, then #56402 opened 1 hour ago. That is not the same period, you had 2 PRs closed because you were not following the rules, then you opened a 3rd one 14 hours later also not following the rules. You have showed you do not receive feedback

**Comment by farihaNaqvi** [comment]
I feel quite embarrassed about my actions, but your guidance has helped me understand what I did wrong. Thank you for your support, and I apologize for any trouble I may have caused. I promise to learn from this and ensure it doesn’t happen again.
And i would be grateful if you could help me for the last time.
Thanks

**Comment by ilenia-magoni** [comment]
you should join our [Discord](https://discord.gg/KVUmVXA) server and ask for help in the #contributors channel, continuing to post here will not bring to desired results

**Pull request closed without merging**
