### PR TITLE
Added usages

### PR DESCRIPTION
**Pull request by RyanElliottGit**
Added usages in the style of other files in the directory.

- [x] I have read [freeCodeCamp's contribution guidelines](https://github.com/freeCodeCamp/freeCodeCamp/blob/master/CONTRIBUTING.md).
- [x] My pull request has a descriptive title (not a vague title like `Update index.md`)
- [x] My pull request targets the `master` branch of freeCodeCamp.
- [x] None of my changes are plagiarized from another source without proper attribution.
- [x] My article does not contain shortened URLs or affiliate links.

If your pull request closes a GitHub issue, replace the XXXXX below with the issue number.

Closes #XXXXX

### CODE REVIEW

**Comment by honmanyau** [comment]
@zerandomalt Thank you very much for submitting a pull request (PR)! I think the added commands are fine but it's not immediately clear to a beginner how one would use those commands. I strongly suggest adding a examples for each of the cases before this PR is merged (`chmod +x file1.txt`, `chmod 754 file1.txt` and `chmod -reference=file1.txt file2.txt`). Your thoughts?

**Comment by honmanyau** [comment]
@zerandomalt Thank you very much for taking the time to do this (and apologies for the late response, I must have read the notification when I was in the middle of something and forgot to come back to it).

I have done some basic editing, formatted the markdown file a little, and resolved a merge conflict. I think it's good to be merged, but I have unassigned myself so that some else can review my editing.

In any case, thank you very much again and happy coding! ☀️

**Comment by honmanyau** [comment]
To the next reviewer: the changes I have made are all documented in the commit messages. the merge conflict was resolved by removing effectively all the changes made made in #20213 and #20442, not least because this PR was created much earlier with much better content.

**Comment by MP7373** [comment]
I read over it and it looks fine to me so I merged it.

**Comment by honmanyau** [comment]
@MP7373 Thank you very much for sorting it out! 👍

**Pull request merged**
