### PR TITLE
fix(client): 404 page displays incorrectly

### LINKED ISSUE #35950: Footer needs to be Sticky.
**Expected behavior**
the footer should stick to the bottom of the page when page content is shorter than the viewport height or it should be at the end of the content when content is larger than viewport height;

**Expected:**

Screen Shot 2019-05-02 at 4 19 15 PM

**Current:**

Screen Shot 2019-05-02 at 3 50 29 PM

### LINKED ISSUE #35972: [rocks/beta] Ugly 404 error pages
When you go to a non-existent user profile URL. You get a pretty 404 error page...
https://www.freecodecamp.rocks/asdf
Screen Shot 2019-05-05 at 10 38 08 AM

But if you go to any non-existent URL that is under `learn` or `challenges` and others. You get an ugly error page...
https://www.freecodecamp.rocks/learn/asdf
https://www.freecodecamp.rocks/challenges/asdf
https://www.freecodecamp.rocks/asdf/asdf
Screen Shot 2019-05-01 at 2 56 56 PM
Screen Shot 2019-05-01 at 2 57 14 PM
These error pages are also missing the footer.

### PR DESCRIPTION
**Pull request by ValeraS**
- [x] I have read [freeCodeCamp's contribution guidelines](https://github.com/freeCodeCamp/freeCodeCamp/blob/master/CONTRIBUTING.md).
- [x] My pull request has a descriptive title (not a vague title like `Update index.md`)
- [x] My pull request targets the `master` branch of freeCodeCamp.
- [x] None of my changes are plagiarized from another source without proper attribution.

Closes #35972, closes #35950 

- [x] correctly display 404 page
- [x] always show footer on 404 page

### CODE REVIEW

**Review by ojeytonwilliams — APPROVED** [review]
I couldn't see any obvious change in the appearance of the footer, but it looks good anyway.  The 404 pages all display correctly (including `/learn/not-a-page`).  There's a tiny delay when the 404 page first loads, presumably due to hydration, but that's not caused by this PR.  I just noticed it while reviewing.  Finally, the challenge pages now look good on small screens.

All in all, LGTM :+1:

**Comment by raisedadead** [comment]
Hi @ValeraS can we get a rebase, before I QA this? Thanks.

**Comment by raisedadead** [comment]
image

I am not seeing the footer when I pull this down, is this supposed to come from the other linked PR?

**Comment by ValeraS** [comment]
> I am not seeing the footer when I pull this down, is this supposed to come from the other linked PR?

You do not see footer in develop mode, because of all component wrapped into hot-reload-component. You need to build the client to check it.

**Comment by raisedadead** [comment]
Ah.. right. I need some more coffee. Thanks.

**Review by raisedadead — APPROVED** [review]

**Pull request merged**
