### PR TITLE
componentWillReceiveProps is deprecated

### PR DESCRIPTION
**Pull request by tiagosalema**
Consider removing this lesson from the React tutorial, once this lifecycle method is now deprecated.
In case it isn't, a warning in the beginning should be displayed

- [x] I have read [freeCodeCamp's contribution guidelines](https://github.com/freeCodeCamp/freeCodeCamp/blob/master/CONTRIBUTING.md).
- [x] My pull request has a descriptive title (not a vague title like `Update index.md`)
- [x] My pull request targets the `master` branch of freeCodeCamp.
- [x] None of my changes are plagiarized from another source without proper attribution.
- [x] All the files I changed are in the same world language (for example: only English changes, or only Chinese changes, etc.)
- [x] My changes do not use shortened URLs or affiliate links.

Closes #XXXXX

### CODE REVIEW

**Comment by RandellDawson** [comment]
You are assuming the latest version of React is being used.  You probably should have created an issue first so we could have discussed whether this PR should be introduced.

**Comment by tiagosalema** [comment]
Thank you for the insight. I'm new to GitHub and am still trying to understand the workflow that goes with it. Shall I close this request and open a new issue?

**Comment by RandellDawson** [comment]
No, just leave it as a PR.  In the future, when making changes to the challenges, an issue is better, so it can be discussed before someone spends time creating a PR.

**Review by ojeytonwilliams — APPROVED** [review]

**Review by RandellDawson — APPROVED** [review]

**Comment by RandellDawson** [comment]
Thank you for your contribution to the page! 👍
We're happy to accept these changes, and look forward to future contributions. 🎉

**Pull request merged**
