### PR TITLE
fix(seed/challenges): Change cash register algorithm

### LINKED ISSUE #16083: "Exact Change" algorithm challenge should return single data type.
#### Challenge Name

https://www.freecodecamp.org/challenges/exact-change

#### Issue Description

My own two cents as an experienced developer is that this problem teaches newcomers that it's totally normal and acceptable for your functions to return completely different types depending on arbitrary input conditions. I know javascript is not statically typed, but this is the stuff that bugs are made of. 

I'd suggest having it at least tag the return value with the type in some way, such as `{registerState: 'CLOSED', change: [...]}` or `{registerState: "INSUFFICIENT_FUNDS", change: []}` etc. As-is, the correct solution wouldn't pass code review at any of the places I've worked. Seems in bad taste to teach it to people that are trying to pass interviews someday.

To clarify, I propose that the function *always* return an object containing a `status` key and a `change` key. The `status` is one of `INSUFFICIENT_FUNDS`, `CLOSED`, `OPEN`, and `change` is a 2D array that is described in the original problem. Examples:

```
{status: "INSUFFICIENT_FUNDS", change: []}  // change should probably always be empty list in this case
{status: "CLOSED", change: [["PENNY", 1.01], ["NICKEL", 2.05]]}
{status: "OPEN", change:  [["TEN", 20.00], ["TWENTY", 60.00]]}
```

Discuss.

### PR DESCRIPTION
**Pull request by scissorsneedfoodtoo**
#### Pre-Submission Checklist

- [x] Your pull request targets the `staging` branch of freeCodeCamp.
- [x] Branch starts with either `fix/`, `feature/`, or `translate/` (e.g. `fix/signin-issue`)
- [x] You have only one commit (if not, [squash](http://forum.freecodecamp.org/t/how-to-squash-multiple-commits-into-one-with-git/13231) them into one commit).
- [x] All new and existing tests pass the command `npm test`. Use `git commit --amend` to amend any fixes.

#### Type of Change

- [x] Small bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds new functionality)
- [ ] Breaking change (fix or feature that would change existing functionality)
- [ ] Add new translation (feature adding new translations)

#### Checklist:

- [ ] Tested changes locally.
- [x] Addressed currently open issue (replace XXXXX with an issue no in next line)

Closes #16083

#### Description

Edited the description and tests so that freeCodeCamp users learn to
write functions that return a similar data structure type each time.

### CODE REVIEW

**Comment by QuincyLarson** [comment]
@scissorsneedfoodtoo Thanks for updating this! Will existing solutions still pass this updated challenge?

**Comment by scissorsneedfoodtoo** [comment]
No problem!

Yes, I added a bit to the previous solution and tested it before submitting my last pull request. The solution here should pass the updated challenge just fine. But if someone could check one more time I'd really appreciate it!

**Comment by QuincyLarson** [comment]
@scissorsneedfoodtoo I started QA'ing this, but ran into this problem both on my local computer and on beta.freecodecamp.org: https://github.com/freeCodeCamp/freeCodeCamp/issues/16260

Are you experiencing this as well? I won't be able to finish QA'ing your PR until we've fixed this :( Thanks for your patience!

**Comment by scissorsneedfoodtoo** [comment]
@QuincyLarson I am actually having the same problem on my local computer in both Firefox and Chrome. I came across some other issues that suggested refreshing the page, but that didn't work either. After more searching I just decided to disable loopProtect with //noprotection up above the solution. Then the solution passes, but it's definitely not ideal!

I can do more digging tonight about what's going on with loopProtect.

**Comment by QuincyLarson** [comment]
@scissorsneedfoodtoo I couldn't get the old solutions here to work, even with `//noprotect` on : https://forum.freecodecamp.org/t/freecodecamp-algorithm-challenge-guide-exact-change/16012

Can you confirm whether they work? We shouldn't so radically change the challenge as to break existing solutions.

**Comment by scissorsneedfoodtoo** [comment]
@QuincyLarson Ah, I'm sorry! I see what you're saying now. I thought we were talking about the solution to the problem in the json itself, rather than the ones from the challenge guide?

I was hoping to address issue [16083](https://github.com/freeCodeCamp/freeCodeCamp/issues/16083) and some comments from issue [9657](https://github.com/freeCodeCamp/freeCodeCamp/issues/9657#issuecomment-280932294). In #16083, user johntyree suggests changing the challenge so that the function returns a single data type each time, rather than an array or string depending on the conditions. I was able to change the challenge, tests, and instructions, but unfortunately it means the former solutions will no longer pass all the checks.

I don't mind leaving the challenge as is, so the existing solutions will still work. Or if we update the challenge this way, would I be able to update the challenge guide itself, so new or returning campers can find a working solution?

Also, here's the working solution from the json file for this challenge:

`var denom = [
  { name: 'ONE HUNDRED', val: 100},
  { name: 'TWENTY', val: 20},
  { name: 'TEN', val: 10},
  { name: 'FIVE', val: 5},
  { name: 'ONE', val: 1},
  { name: 'QUARTER', val: 0.25},
  { name: 'DIME', val: 0.1},
  { name: 'NICKEL', val: 0.05},
  { name: 'PENNY', val: 0.01}
];

function checkCashRegister(price, cash, cid) {
  var output = {status: null, change: []};
  var change = cash - price;
  var register = cid.reduce(function(acc, curr) {
    acc.total += curr[1];
    acc[curr[0]] = curr[1];
    return acc;
  }, {total: 0});
  if(register.total === change) {
    output.status = 'CLOSED';
    output.change = cid;
    return output;
  } 
  if(register.total < change) {
    output.status = 'INSUFFICIENT_FUNDS';
    return output;
  }
  var change_arr = denom.reduce(function(acc, curr) {
    var value = 0;
    while(register[curr.name] > 0 && change >= curr.val) {
      change -= curr.val;
      register[curr.name] -= curr.val;
      value += curr.val;
      change = Math.round(change * 100) / 100;
    }
    if(value > 0) {
      acc.push([ curr.name, value ]);
    } 
    return acc;
  }, []);
  if(change_arr.length < 1 || change > 0) {
    output.status = 'INSUFFICIENT_FUNDS';
    return output;
  }
  output.status = 'OPEN';
  output.change = change_arr;
  return output;`

**Comment by QuincyLarson** [comment]
@scissorsneedfoodtoo Awesome - I had forgotten about this discussion but you're right - we should address that issue as well. 

I've confirmed that the solution works. Merging. Thanks for your patience and help!

**Comment by scissorsneedfoodtoo** [comment]
@QuincyLarson No worries! I just saw how long ago that first conversation took place. And I totally understand your concern about changing the challenges too drastically - it's a good policy, especially with so many good guides out there already. About that, I'll look into creating a new guide for this updated challenge. 

Thank you for all of your help and patience, too!

**Comment by QuincyLarson** [comment]
@scissorsneedfoodtoo Would you be interested in helping QA some outstanding pull requests to the Interview Prep section? I think they're right up your alley after refactoring this challenge!

Here are the PRs: 
- https://github.com/freeCodeCamp/freeCodeCamp/pull/15856
- https://github.com/freeCodeCamp/freeCodeCamp/pull/15950
- https://github.com/freeCodeCamp/freeCodeCamp/pull/15952
- https://github.com/freeCodeCamp/freeCodeCamp/pull/15953
- https://github.com/freeCodeCamp/freeCodeCamp/pull/16029
- https://github.com/freeCodeCamp/freeCodeCamp/pull/16079

**Comment by scissorsneedfoodtoo** [comment]
Sure thing! I'll start going through them over the next few days.

**Comment by QuincyLarson** [comment]
@scissorsneedfoodtoo Awesome! Thanks for looking at these! Then, if you're interested, I can fill you in on our long term goals with all these challenges and give you some more context.

**Comment by scissorsneedfoodtoo** [comment]
@QuincyLarson, sure, that all sounds great! I look forward to hearing about your long term goals once I go through these PRs.

**Comment by QuincyLarson** [comment]
@scissorsneedfoodtoo Could you send me an email at quincy at freecodecamp org and we can take it from there? Perhaps we could hop on a quick Hangouts or Skype call and I could learn more about your near-term goals and give you some back-story on the interview prep section?

**Comment by johntyree** [comment]
Glad to see this fixed! Good job @scissorsneedfoodtoo !!

**Comment by scissorsneedfoodtoo** [comment]
Thanks @johntyree! Couldn't have done it without your guidance.

**Comment by gikf** [comment]
Hey @CKL-1989

This is a standard message notifying you that this issue seems to be a request for help. Instead of asking for help here, please click the **"Get Help"** button on the challenge on freeCodeCamp and choose the **"Ask for help"** option, which will help you create a question in the right part of the forum. Volunteers on the forum usually respond to questions within a few hours and can help determine if there is an issue with your code or the challenge's tests.

If the forum members determine there is nothing wrong with your code, you can request this issue to be reopened.

Thank you and happy coding.

**Pull request merged**
