### PR TITLE
chore(UI):move new RWD to top for ES

### PR DESCRIPTION
**Pull request by RafaelDavisH**
Checklist:

- [X] I have read [freeCodeCamp's contribution 
guidelines](https://contribute.freecodecamp.org).
- [X] My pull request has a descriptive title (not a vague title like `Update 
index.md`)
- [X] My pull request targets the `main` branch of freeCodeCamp.
- [ ] I have tested these changes either locally on my machine, or GitPod.

### CODE REVIEW

**Comment by RafaelDavisH** [comment]
@moT01 Thanks for adding the changes needed

**Comment by RafaelDavisH** [comment]
BTW do we have these steps recorded somewhere for reference, like Language lead handbook?

**Comment by moT01** [comment]
We don't really have anything specific for when a new superblock is finished being proofread and how to move it into place. We have this for [when a new language gets added,](https://contribute.freecodecamp.org/#/how-to-enable-new-languages?id=enabling-a-language) which includes some information about that `superOrder` object.

**Comment by RafaelDavisH** [comment]
Thanks @moT01, I did check the docs, but missed that portion. This is helpful

**Review by moT01 — APPROVED** [review]
LGTM 🎉 Congrats @RafaelDavisH & Spanish translators 🎉

**Review by Sboonny — APPROVED** [review]
LGTM 🎉, congratulations! 👍.

**Pull request merged**
