### PR TITLE
fix: typo in a function name

### PR DESCRIPTION
**Pull request by MrBrain295**
Checklist:

- [x] I have read and followed the [contribution guidelines](https://contribute.freecodecamp.org).
- [x] I have read and followed the [how to open a pull request guide](https://contribute.freecodecamp.org/#/how-to-open-a-pull-request).
- [x] My pull request targets the `main` branch of freeCodeCamp.
- [ ] I have tested these changes either locally on my machine, or GitPod.

Closes #XXXXX

Github -> GitHub

### CODE REVIEW

**Comment by bbsmooth** [comment]
How is this a typo?

**Comment by MrBrain295** [comment]
GitHub is spelled with that case.

**Comment by bbsmooth** [comment]
Well, fCC is under no obligation to capitalize the "h" in Github :slightly_smiling_face: 

I certainly wouldn't call this a typo. I'm not sure it improves the code base at all by capitalizing the "h". But I have no objections if others want to approve this.

**Review by naomi-lgbt — APPROVED** [review]
Given that we write "linkedin" as `LinkedIn` here, I think this change is fine.

**Review by raisedadead — APPROVED** [review]
I am going ahead and approving because it is a minor thing and is well intended, but I am going to mention the spirit of open-source and etiquette requires you to:

- Follow the guidelines even if it is a minor typo - editing off of GitHub - just because you can.
- You can't rename symbols like this (you may assume it is minor) because it can and will break things somewhere.

That said we are fine accepting the change. Happy contributing!

**Pull request merged**
