### PR TITLE
Fix(UX): avail-to-hire button labels

### LINKED ISSUE #16175: [beta] Fix UI problem with the available-to-hire button
#### Issue Description
When you sign in to your account on the beta site and navigate to your Setting page by clicking "Update your setting" button, you will see the "Are you available to hire?" button to toggle between "Available" and "Unavailable". However, when you resize your browser window, the label on the button ("Unavailable"/"Available" will be out of the button box. A quick fix I could think of is to change the label into "Yes" and "No" to avoid long texts. Please confirm so I could go ahead and fix this bug.

#### Browser Information

* Browser Name, Version: Chrome 62.0.3202.94
* Operating System: MacOS Sierra 10.12.4
* Mobile, Desktop, or Tablet: Macbook

#### Screenshot
availabletohire-button-ui-issue

Related #16168

### PR DESCRIPTION
**Pull request by anhtran1906**
#### Pre-Submission Checklist

- [X] Your pull request targets the `staging` branch of freeCodeCamp.
- [X] Branch starts with either `fix/`, `feature/`, or `translate/` (e.g. `fix/signin-issue`)
- [X] You have only one commit (if not, [squash](http://forum.freecodecamp.org/t/how-to-squash-multiple-commits-into-one-with-git/13231) them into one commit).
- [X] All new and existing tests pass the command `npm test`. Use `git commit --amend` to amend any fixes.

#### Type of Change

- [X] Small bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds new functionality)
- [ ] Breaking change (fix or feature that would change existing functionality)
- [ ] Add new translation (feature adding new translations)

#### Checklist:

- [X] Tested changes locally.
- [X] Addressed currently open issue (replace XXXXX with an issue no in next line)

Closes #16175 

#### Description

- Changed the label of the available-to-hire button to Yes/No to avoid bad UX
- Updated Node version to 8.2.1 to be able to run the test suites
- Squash 2 commits

### CODE REVIEW

**Review by raisedadead — CHANGES_REQUESTED** [review]
Hi @anhtran1906 

Thanks a lot for the pull request, looks like you have modified the package-lock.json, accidentally?.

Checkout your PR branch:

```
git checkout <branch-name>
```

Reset the **FILE** to original state:

```sh
git checkout staging -- package-lock.json
```

This will reset only the file that is mentioned above.

then amend your commit,

```sh
git commit --amend --no-edit 
```

and finally force push

```sh
git push -f
```

This will automatically update this PR.

In future, just add the files that you intend to commit like so:
Example:

```sh
git add  server/common/models/user.js
```
and repeat the same as may times as necessary for any additional files.

**Comment by anhtran1906** [comment]
@raisedadead Thank you for your comments. I had trouble running the test suite at first and needed to upgrade my node version to 8.2.1 by running nvm install node 8.2.1. Then the code was not working locally for me as it threw errors and could not even show the landing page. Thus I removed node_modules and ran npm install again and it worked. I guess because of this, package-log.json was replaced. I followed your instruction and everything works now and the test suite passes. I'll be more careful next time. Thank you. It's ready for QA!

**Comment by raisedadead** [comment]
Sure thing @anhtran1906 happens all the time, do not worry about it.

**Comment by raisedadead** [comment]
#### :sparkles: :sparkles: **LGTM.** :sparkles: :sparkles: 

Thanks @anhtran1906, for this pull request and contributing to this code-base for the first time. We highly encourage you to keep sending us pull requests in future.

Happy contributing!

**Comment by anhtran1906** [comment]
@raisedadead Awesome! Thank you! Should I now deleted this branch since it's merged?

**Comment by raisedadead** [comment]
Yup, you should do that and sync your fork from staging. For every PR you should start off fresh.

**Pull request merged**
