### PR TITLE
feat: update challenge helpers to handle id filenames

### PR DESCRIPTION
**Pull request by ojeytonwilliams**
As part of the process I 

- Reduced the reliance on mocking
- Simplified the cli
- DRY'd out the code
- Replaced create-step-between with insert-step

The justification for the last one was that it's more intuitive (to me, at least) inserting a step at position n pushes the next steps out the way to make space.

**Old behaviour**

With steps [a,b,c]
```sh
npm run create-step-between start=2
```
we get [a,b,**2**,c]

**New behaviour**

With steps [a,b,c]
```sh
npm run insert-step 2
```
we get [a,**2**,b,c]

This also means that

```sh
npm run insert-step 2
npm run delete-step 2
```
adds and then deletes the same step, as you might expect.

Finally, insert-step uses the previous step's seed code.  This will generally result in the previous step's tests failing.  This is deliberate - I didn't want it to be possible to forget to update the seed for the new step. 

---

This is based off the https://github.com/freeCodeCamp/freeCodeCamp/pull/44747 branch, hence (some of) the mess.

### CODE REVIEW

**Comment by ojeytonwilliams** [comment]
Sorry about the no. of files changed, I meant to remove the debug commit. It's reviewable in this state, but I'll remove that tomorrow.

**Comment by ShaunSHamilton** [comment]
Oliver, what needs to go in before/after this?

**Comment by ojeytonwilliams** [comment]
Just https://github.com/freeCodeCamp/freeCodeCamp/pull/44747, @ShaunSHamilton all being well I'll get that done tomorrow.

**Review by moT01 — COMMENTED** [review]
Only thing I noticed is that `create-next-step` doesn't remove the ERM's as far as I can tell - docs say it does.

Side though - if we use the id's for filenames, would we want to still keep it in the front matter?

Probably most important - we should probably not merge this until we are really ready to move to using the id's as filenames, no? I checked main, and the helper scripts seem to work with the current file structure. If we merge this, they won't work cause the filenames aren't changed - quite sure. So if someone wants to fix/change something in the current RWD beta, the scripts won't be there. Perhaps we could put these ones to work with the id's in their own folder for now so we can keep the old helpers and this PR doesn't sit around forever.

Other than that stuff - this LGTM :tada: they all seemed to be working :+1:

**Comment by ojeytonwilliams** [comment]
> Only thing I noticed is that create-next-step doesn't remove the ERM's as far as I can tell - docs say it does.

Okay, do you (or does anyone) have a preference?  I'm happy to fix it or the docs.

> Side though - if we use the id's for filenames, would we want to still keep it in the front matter?

It's not an obvious call, but I think keep it.  Reason being, as much as possible, we want the data to be in the files, rather than in the file structure.  If we ever port the curriculum over to a db, that process should go smoother if we try to stick to that approach.  Also, pulling it from the filename means more code.

> Probably most important - we should probably not merge this until we are really ready to move to using the id's as filenames, no?

Yeah, we should convert both at once to avoid breaking the helpers.

**Comment by moT01** [comment]
> do you (or does anyone) have a preference

I'm fine with it either way. I suppose they would really never be where you want them, so removing would be better - but it's not difficult to do that manually. Maybe @nhcarrigan or @ShaunSHamilton can weigh in since they did a lot more building of the curriculum that uses these.

**Review by moT01 — APPROVED** [review]

**Review by naomi-lgbt — APPROVED** [review]
Tested against new ID system, looks good.

**Pull request merged**
