### PR TITLE
Fix count a element assertion in 'waypoint-nest-an-anchor-element-within-a-paragraph' to avoid 'undefined is not an object' error

### PR DESCRIPTION
**Pull request by ptsurbeleu**
Adjusted the original "a" element count assertion to be resilient to the case when "a" element is completely missing in the code editor (the previous assertion resulted in 'undefined is not an object' error message under the very same conditions) to fix issue #899.

This snip of how would the original assertion would react upon the missing element (the first one in the list on the left):
screen shot 2015-11-07 at 9 34 14 pm

Here is the snip of how the proposed change would react upon the missing element:
screen shot 2015-11-07 at 9 34 54 pm

And here is the snip of how the proposed change would react upon the completed challenge:
screen shot 2015-11-07 at 9 33 10 pm

Appreciate your feedback very much!

### CODE REVIEW

**Comment by ltegman** [comment]
Good catch and improvement! One suggestion: since your new test looks for an anchor with a link to the full url of `http://www.freecatphotoapp.com` would you mind changing the message to reflect that? Just want to avoid any potential confusion.

**Comment by ptsurbeleu** [comment]
Sure thing, sounds reasonable. Actually, I've originally updated the assertion's message but then pulled it off in the last minute.

**Comment by ltegman** [comment]
Looks great! :+1:

**Comment by ptsurbeleu** [comment]
My pleasure! :-)

**Pull request merged**
