### PR TITLE
fix(challenge): update test to support arrow function

### LINKED ISSUE #35095: "JSON APIs and Ajax: Get JSON with the JavaScript XMLHttpRequest Method" tests don't allow arrow function to be used as onload event handler
**Describe your problem and how to reproduce it:**
The tests for the ["JSON APIs and Ajax: Get JSON with the JavaScript XMLHttpRequest Method"](https://learn.freecodecamp.org/data-visualization/json-apis-and-ajax/get-json-with-the-javascript-xmlhttprequest-method) challenge do not allow an arrow function to be used as the `onload` event handler for the XMLHttpRequest.

When my code looks like this, the tests pass:

```js
const apiRequest = new XMLHttpRequest();
  apiRequest.open( 'GET', '/json/cats.json', true );
  apiRequest.send();
  apiRequest.onload = function() {
    const json = JSON.parse(apiRequest.responseText);
    document.getElementsByClassName( 'message' )[0].innerHTML = JSON.stringify( json );
  };
```

But this causes the tests to fail:

```js
const apiRequest = new XMLHttpRequest();
  apiRequest.open( 'GET', '/json/cats.json', true );
  apiRequest.send();
  apiRequest.onload = () => {
    const json = JSON.parse(apiRequest.responseText);
    document.getElementsByClassName( 'message' )[0].innerHTML = JSON.stringify( json );
  };
```

**Add a Link to the page with the problem:**
https://learn.freecodecamp.org/data-visualization/json-apis-and-ajax/get-json-with-the-javascript-xmlhttprequest-method

**Tell us about your browser and operating system:**
* Browser Name: Firefox Developer Edition
* Browser Version: 66.0b5
* Operating System: Antergos Linux

### This challenge
- #35096
- #35097

### PR DESCRIPTION
**Pull request by lasjorg**
- [x] I have read [freeCodeCamp's contribution guidelines](https://github.com/freeCodeCamp/freeCodeCamp/blob/master/CONTRIBUTING.md).
- [x] My pull request has a descriptive title (not a vague title like `Update index.md`)
- [x] My pull request targets the `master` branch of freeCodeCamp.
- [x] None of my changes are plagiarized from another source without proper attribution.
- [x] All the files I changed are in the same world language (for example: only English changes, or only Chinese changes, etc.)
- [x] My changes do not use shortened URLs or affiliate links.

Updates test for this challenge: https://learn.freecodecamp.org/data-visualization/json-apis-and-ajax/get-json-with-the-javascript-xmlhttprequest-method/

1. Updates test to allow for the use of an arrow function for the onload method.
2. Added solution code.

Tested locally.

@RandellDawson Can you help check my regex that would be awesome.

BTW: Should we update this part of the curriculum to show using fetch?

Closes https://github.com/freeCodeCamp/freeCodeCamp/issues/35095

### CODE REVIEW

**Comment by RandellDawson** [comment]
@lasjorg Working on some earlier PRs right now, but it will definitely be reviewed soon.

Thanks for the contribution.

**Note:**  Solutions added in the solution section should be the full code that was in the challenge seed with any changes to solve the challenge.

**Comment by lasjorg** [comment]
@RandellDawson I see. So the solution should include the event listener and click handler from the challenge seed? Do I remove the "add your code" comments or should they stay as well?

**Comment by RandellDawson** [comment]
> So the solution should include the event listener and click handler from the challenge seed?

Yes

> Do I remove the "add your code" comments or should they stay as well?

This is debatable, but I would approve the PR with them still in it, because it does not affect how the code will work.

The whole point of the solution section is to validate any changes to challenges or new tests still pass with a known full working solution.  It is a way to make sure we don't break anything when adding/changing tests.

**Comment by RandellDawson** [comment]
I should have been clearer, because you need to include all code (HTML, CSS, and JavaScript).

**Comment by lasjorg** [comment]
@RandellDawson I hope I did that right.

Not sure I fully understand how the solution is used, or by what? Does the CI use it, or is it a local build test?

**Comment by RandellDawson** [comment]
The CI uses it and it is used by the local tests when using `npm run test`.

**Review by RandellDawson — APPROVED** [review]
I have tested these changes and believe it now correctly allows arrow function syntax as well as normal function syntax in the `testString`.

**Review by moT01 — APPROVED** [review]
Tested locally - looks good @lasjorg, thanks for contributing to freeCodeCamp!

**Pull request merged**
