### PR TITLE
Added the recommended test

### LINKED ISSUE #5366: add aditional test for area code
Currently on the wiki the second solution `var regex = /^1?\s?(\(\d{3}\)|\d{3})?\s?-?\d{3}-?\s?\d{4}$/;` also allows phone numbers without an area code.

I suggest to add an additional test that invalidates this
```
expect(telephoneCheck("555-5555")).to.equal(false);
```

Alternatively 555-5555 could be added as a valid format in the explanation of this bonfire.

### PR DESCRIPTION
**Pull request by natac13**
The solution from the wiki still is a working solution. Maybe I do
not fully understand the issue. However I have added a test that
will bar any 7 digit number

closes #5366

### CODE REVIEW

**Comment by ltegman** [comment]
You'll need to add another test for `555-5555` or `5555555` or both, in order to invalidate the second solution.

**Comment by natac13** [comment]
@ltegman Hope this is what you asked for.

**Comment by ltegman** [comment]
Those two tests shouldn't have the parentheses around them. Basically, the parentheses makes it so that even the incorrect solution will fail them, but without the parentheses the incorrect solution will pass them. The tests should be
`"assert(telephoneCheck(\"555-5555\") === false, 'message: <code>telephoneCheck(\"555-5555\")</code> should return false.');"`
and 
`"assert(telephoneCheck(\"5555555\") === false, 'message: <code>telephoneCheck(\"5555555\")</code> should return false.');"`

**Comment by bugron** [comment]
@FreeCodeCamp/issue-moderators can you, please, check, why is this PR failing the CI build?

**Comment by SaintPeter** [comment]
The issue with this one is that it's failing two tests:
> Validate US Telephone Numbers: message: <code>telephoneCheck("555-5555")</code> should return false.
> Validate US Telephone Numbers: message: <code>telephoneCheck("555-5555")</code> should return false.

So it looks like the new telephone checks are not working properly.

@natac13 You need to run `npm run test-challenges` to validate.

**Comment by ltegman** [comment]
Closing as stale. Feel free to reopen when this PR is fixed and passing tests. Thanks!

**Comment by natac13** [comment]
I cloud be very wrong with this but as these tests are failing and not broken, plus when I run locally the challenge works, I wanted to ask what 'solution' is being used to run the tests? The issue #5366 was stating that the solution in the wiki allowed for phone numbers with area codes.  Therefore I am thinking that is what is causing the test to fail. 

Sorry I didnt reply sooner. Busy with work.

Let me know if my hypothesis is incorrect. At that point I am unsure what is causing the test to fail.

**Comment by natac13** [comment]
I did some what confirm by changing those two test to expect true and everything passed. Hope this was helpful, If not I am home today for due to bad weather and would be willing to figure this is out if more is needed from myself.

**Pull request closed without merging**
