### PR TITLE
added word-wrap less rule to .test-output

### LINKED ISSUE #11687: CSS issue with 13" (1280 x 659) viewports.
Device:

`Mozilla/5.0 (Macintosh; Intel Mac OS X 10_12_1) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/54.0.2840.98 Safari/537.36`

Viewport : 1280 x 659

Issue :
image

This almost made be believe that the url is actually `.co` instead of a `.com`

### PR DESCRIPTION
**Pull request by chiptus**
#### Pre-Submission Checklist

- [ ] Your pull request targets the `staging` branch of FreeCodeCamp.
By #11687 this should target backup/master
- [X] Branch starts with either `fix/`, `feature/`, or `translate/` (e.g. `fix/signin-issue`)
- [X] You have only one commit (if not, [squash](http://forum.freecodecamp.com/t/how-to-squash-multiple-commits-into-one-with-git/13231) them into one commit).
- [X] All new and existing tests pass the command `npm test`. Use `git commit --amend` to amend any fixes.

#### Type of Change

- [X] Small bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds new functionality)
- [ ] Breaking change (fix or feature that would change existing functionality)
- [ ] Add new translation (feature adding new translations)

#### Checklist:

- [X] Tested changes locally.
- [X] Closes currently open issue (replace XXXX with an issue no): Closes #11687 

#### Description

Added a rule to the .test-output class: word-wrap: break-word.
Closes #11687

### CODE REVIEW

**Comment by atjonathan** [comment]
@chiptus, unfortunately the PR #11705 has already been created before this one. Sorry about this, but we have to accept the first one that comes in! In future, make sure to check that no one has submitted a fix to an issue before fixing it yourself. Thanks for contributing however, and I hope you can find another issue tagged [`help wanted`](https://github.com/FreeCodeCamp/FreeCodeCamp/labels/help%20wanted) 😄

**Comment by systimotic** [comment]
@atjonathan Both pull requests were by @chiptus. As stated (somewhat hidden) in the pre-submission checklist, the issue requested this fix to be submitted against both staging and backup/master. The PR against staging is #11705, this is the PR against backup/master. 😅

**Comment by raisedadead** [comment]
LGTM. thanks @chiptus 

/cc @BerkeleyTrue please release when you have a moment.

**Comment by atjonathan** [comment]
Thanks @chiptus.
@BerkeleyTrue, reminder to release `backup/master` 😜

**Pull request merged**
