### PR TITLE
feat(curriculum): add i18n-curriculum submodule

### PR DESCRIPTION
**Pull request by moT01**
This adds the `i18n-curriculum` submodule to the repo and some conditions to build using it. It's an intermediary step to move the all the i18n curriculum files out of the main repo. It shouldn't affect any of the existing build process.

When you checkout the PR, the `i18n-curriculum` folder will show up in the `curriculum` folder of your file tree - it will be empty. You can build in any language and it will use the existing curriculum files. There's a new `BUILD_WITH_SUBMODULE` env variable, set it to `true` to build using the `i18n-curriculum` submodule folder. Now, if you are building English, it will continue to use the existing curriculum files - but if you change it to any other language, it will use the files in the `i18n-curriculum` folder. It's still empty so building now will fail. Run `git submodule update --init` to download all the curriculum files. Now the i18n builds will work.

Here's the remaining steps to completely move to using the i18n-curriculum repo:

1. Merge this PR
2. Test actions - Run the download workflow on the i18n-curriculum repo, it should create and auto-merge a PR to i18n-curriculum with the curriculum files and create a PR to the main repo to update the submodule
3. Change the tests and pipelines to `BUILD_WITH_SUBMODULE=true` + add command to download i18n-curriculum repo
4. Remove i18n curriculum files from main repo
5. Remove `BUILD_WITH_SUBMODULE` env variable and always build i18n's with i18n-curriculum repo
- Update documentation

Checklist:

- [x] I have read and followed the [contribution guidelines](https://contribute.freecodecamp.org).
- [x] I have read and followed the [how to open a pull request guide](https://contribute.freecodecamp.org/how-to-open-a-pull-request/).
- [x] My pull request targets the `main` branch of freeCodeCamp.
- [x] I have tested these changes either locally on my machine, or GitPod.

Closes #XXXXX

### CODE REVIEW

**Comment by moT01** [comment]
Blocked while I come up with a list of the next steps to finish the process of moving to use the submodule entirely.

**Comment by ojeytonwilliams** [comment]
Hey Tom, this looks great. It's much cleaner than I'd feared!

One thing confused me, though. When I'm using the submodule, should that be the source of truth for everything, including the english? Or is it supposed to be the case that, even though there's english in the i18n-curriculum/curriculum (challenges and dictionaries), it should be using the english from the original curriculum folder?

As the PR stands, it's using a mixture. Challenges use original for english, but the i18n folder for other langs, but dictionaries use the i18n folder for both.

**Comment by moT01** [comment]
English exists in the i18n-curriculum folder cause when we download from crowdin, it needs to know the sources or it doesn't know where to put the downloads or something - which are English and don't exist in the i18n-curriculum repo as they do in the main repo. So we need to download the English sources when downloading. I suppose we could remove them from that repo and the PR's after we download the rest of the i18n's and not commit the English.

So those english files don't align with what's on the main repo - they're aligned with the last crowdin upload. So...

> should that be the source of truth for everything

No, we are still using the main repo for everything English. Everything else, should use the submodule.

> As the PR stands, it's using a mixture. Challenges use original for english, but the i18n folder for other langs, but dictionaries use the i18n folder for both.

I'm not sure that's the case...

```
 const englishDictionaryDir =
    process.env.BUILD_WITH_SUBMODULE === 'true'
      ? path.resolve(DICTIONARIES_DIR)
      : path.resolve(dictionariesDir);
```

`DICTIONARIES_DIR` is the main English, and if !submodule, `dictionariesDir` is also the main English. It's a little goofy because of some of the existing code and tests. I could potentially use a pair up to get another opinion on that.

When using the submodule, it uses the

**Comment by ojeytonwilliams** [comment]
>  I suppose we could remove them from that repo and the PR's after we download the rest of the i18n's and not commit the English.

Unfortunately, no, because we loop over it. There might be another place to put the list of languages, though.

> It's a little goofy because of some of the existing code and tests

Sorry, you're right. If it's alright with you, I'll just push a refactor, since the existing code is bad and shouldn't constrain us.

**Comment by moT01** [comment]
> Unfortunately, no, because we loop over it.

I'm not sure I understand - can you clarify a little? I don't think we do anything with that English folder, but I might be wrong.

**Comment by ojeytonwilliams** [comment]
> I'm not sure I understand - can you clarify a little? I don't think we do anything with that English folder, but I might be wrong.

It's this line:

https://github.com/freeCodeCamp/freeCodeCamp/blob/9b71e7a94095ac81482707c6f8f702be51d9e117/curriculum/get-challenges.js#L47

but, you're right, it doesn't actually matter.

I've made that more explicit, by actively filtering out the `english`, so it's clear that these are the other languages.

Anyways, I think this last commit simplifies things a little, but it's not a huge difference. Feel free to revert it if you don't like the changes.

**Comment by ojeytonwilliams** [comment]
Well, I've made it testable, but it's not nice... and now the tests are failing. That is to say: I struggled too and I think it's probably worse now :/ I'll have one more go, but I'm not confident I'm getting anywhere.

All the problems seem to stem from always using the english from the curriculum folder and never from i18n-curriculum/curriculum. I get that this would be a big change, but I think it's where we're going, right? i.e. the workflow looks something like this:

1. A contributor changes the english curriculum
2. Upload the changes to Crowdin AND create a PR syncing those changes with i18n-curriculum's english
3. Download the changes, creating a second PR
4. Merge both PRs (thereby ensuring english and the rest are in sync)
5. Build entirely from i18n-curriculum

The details of how we keep them in sync are a bit unclear, but that's the gist.

**Comment by moT01** [comment]
No, that is not the workflow I was going for. I was trying to do what the code was doing - use the i18n-curriculum for the i18n curriculum and still use the main repo for English.

The English folder in the i18n-curriculum repo would be in sync with the rest of the languages. I thought we could potentially use those to build so we don't ever have to worry about things being in sync.

The workflow would be:

1. A contributor changes the english curriculum
2. Upload the English to crowdin
3. Run the download on i18n-curriculum - which automatically creates and merges a PR on that repo, and automatically creates a PR on the main repo to update the submodule.
4. Continue using main repo for English builds, use i18n-curriculum for other languages.

**Comment by ojeytonwilliams** [comment]
> The workflow would be:
>
> 1. A contributor changes the english curriculum
> 2. Upload the English to crowdin
> 3. Run the download on i18n-curriculum - which automatically creates and merges a PR on that repo, and automatically creates a PR on the main repo to update the submodule.
> 4. Continue using main repo for English builds, use i18n-curriculum for other languages.

I agree except for 4. We can make our lives simpler if we use the i18n-curriculum for all languages. Reason being, we can always update it such that the english and translations are both based off the same main repo commit, i.e. delegate all syncing responsibilities to it. If its main branch is always synced (i.e. no updating the english without also updating everything else), then it should (almost) always be ready to build.

**Comment by ojeytonwilliams** [comment]
> Want to take a look at those and see if they make sense @ojeytonwilliams - or if you think there's a better way or I'm missing anything or anything.

They sound good to me.

**Comment by moT01** [comment]
> I agree except for 4. We can make our lives simpler if we use the i18n-curriculum for all languages...

I like that idea, but I'm not sure I fully understand how it would work. Wouldn't it be behind main then? What would the workflow look like? Maybe we can discuss tomorrow.

**Comment by naomi-lgbt** [comment]
Oh I get it.

If we upload the English files from the `freecodecamp` repo, but *build from* the English files in the `i18n` repo (which we download from Crowdin), then we eliminate the whole issue where files get out of sync and the tests fail until we do a download.

Because the English build files are pulled directly from Crowdin, they'd have parity with all of the translated files.

**Comment by moT01** [comment]
> build from the English files in the i18n repo

I have floated this idea before. I think we partially didn't want to do it because we wanted the client to have the latest content. Also, I think there was an argument about relying on what comes from crowdin.

**Comment by ojeytonwilliams** [comment]
Yeah, credit where it's due: this is your idea, Tom!

So, I think the delay is fine. People can still work on the latest content, it's just that the builds that will lag and not by much.

As for relying on Crowdin, that needs some thought. I don't think we'll necessarily need to increase our reliance, but we'll still need some way of patching the problematic challenges.

I like the general idea, though.

**Comment by raisedadead** [comment]
> So, I think the delay is fine. People can still work on the latest content,

I believe that approach might lead to confusion. The main purpose of maintaining the curriculum in the main repository is to avoid any ambiguity. Having multiple copies could result in uncertainty about what is live and what is not when merging or pushing to production branches. While we might understand the distinctions, external contributors may not. This could make it even more challenging for them to contribute effectively, as evidenced by our current contribution volumes.

I am open to the idea of using a separate repository for the entire curriculum. However, I am not in favor of maintaining inconsistent copies of the same language.

**Comment by moT01** [comment]
Alright. This should be good to go. I removed the English files from the i18n-curriculum repo. Now there's only the main English files.

**Comment by moT01** [comment]
Look for link to a document with the battle plan in chat

**Comment by raisedadead** [comment]
As per the plan additional coding activity is required right after merging this PR to keep main branch stable for deployments. Blocking the merge until a cleaner path.

**Pull request merged**
