### PR TITLE
Migrating landings/index.js to typescript

### PR DESCRIPTION
**Pull request by StanleyDharan**
Checklist:

- [x] I have read [freeCodeCamp's contribution guidelines](https://contribute.freecodecamp.org).
- [x] My pull request has a descriptive title (not a vague title like `Update index.md`)
- [x] My pull request targets the `main` branch of freeCodeCamp.
- [x] I have tested these changes either locally on my machine, or GitPod.

Reference #43778 (a task from this issue)

This is my first PR so please let me know on anything I can approve I would appreciate it!

### CODE REVIEW

**Comment by Ismailtlem** [comment]
I think you need to remove the line `Landing.propTypes = propTypes;`

Maybe using an interface instead of a type would be better to stay consistant with our guideline https://contribute.freecodecamp.org/#/codebase-best-practices?id=migrating-a-javascript-file-to-typescript

**Comment by ojeytonwilliams** [comment]
@StanleyDharan do you think you'll have a chance to make the changes @Ismailtlem suggested?

**Comment by moT01** [comment]
✅ rebased
❓  conflicts fixed
❓ Tests passed

**Comment by moT01** [comment]
We had several PR's migrating this file. We decided to go with one of the others. Thanks for contributing to freeCodeCamp 🎉

**Pull request closed without merging**
