### PR TITLE
Use "Submit" in test prompt for "Add a Submit Button to a Form"

### PR DESCRIPTION
**Pull request by felixonmars**
The description says the text should be "Submit", but the test shows "submit" (lower cased). Let's try to make them the same :)

### CODE REVIEW

**Comment by bugron** [comment]
@felixonmars thanks for fixing this, merged!
Next time, please follow our [**Guidelines for Contributing**](https://github.com/FreeCodeCamp/FreeCodeCamp/blob/staging/CONTRIBUTING.md), make your changes in a separate branch with a name pointed in that guidelines.

**Comment by felixonmars** [comment]
Ah, sorry. I was too lazy and used the GitHub web interface :P

**Comment by bugron** [comment]
That's OK. Even with GitHub web interface you can create a branch. https://help.github.com/articles/creating-and-deleting-branches-within-your-repository/

**Comment by felixonmars** [comment]
Thanks :D

**Pull request merged**
