### PR TITLE
feat(e2e,playwright):  created test file for donate-page-default.ts

### PR DESCRIPTION
**Pull request by anand-harsh**
Added playwright test file for donate-page-default.ts

Checklist:

- [x] I have read and followed the [contribution guidelines](https://contribute.freecodecamp.org).
- [x] I have read and followed the [how to open a pull request guide](https://contribute.freecodecamp.org/#/how-to-open-a-pull-request).
- [x] My pull request targets the `main` branch of freeCodeCamp.
- [x] I have tested these changes either locally on my machine, or GitPod.

Solves #51705 

Hacktober Fest PR

image

image

### CODE REVIEW

**Comment by anand-harsh** [comment]
@bazingaa

**Review by Ahmadkashif — CHANGES_REQUESTED** [review]
Hi @anand-harsh :wave:

This is a solid attempt from your side :muscle: 

However, I would suggest you take a look at our helper guides for making [your first PR here at FCC](https://contribute.freecodecamp.org/#/how-to-open-a-pull-request) and our [best practices for how to write tests](https://contribute.freecodecamp.org/#/how-to-add-playwright-tests)

To be a little more specific, just double check if you have named your commit messages accordingly and check if you have followed our guidelines on how do we suggest tests should be written.

This would make the PR golden.

**Comment by anand-harsh** [comment]
> Hi @anand-harsh 👋
> 
> This is a solid attempt from your side 💪
> 
> However, I would suggest you take a look at our helper guides for making [your first PR here at FCC](https://contribute.freecodecamp.org/#/how-to-open-a-pull-request) and our [best practices for how to write tests](https://contribute.freecodecamp.org/#/how-to-add-playwright-tests)
> 
> To be a little more specific, just double check if you have named your commit messages accordingly and check if you have followed our guidelines on how do we suggest tests should be written.
> 
> This would make the PR golden.

Sure Sir, so I have to change commit name and remove repetitive codes?

**Comment by Ahmadkashif** [comment]
Yes @anand-harsh 

Apart from the commit messages, take a look at how we suggest you to[ identify the original DOM element ](https://contribute.freecodecamp.org/#/how-to-add-playwright-tests?id=-identifying-a-dom-element) and how to test it, apparently you'll need to make some changes to your approach.

**Comment by anand-harsh** [comment]
> Yes @anand-harsh
> 
> Yes, commit message with proper naming would be nice.
> 
> Apart from the commit messages, take a look at how we suggest you to[ identify the original DOM element ](https://contribute.freecodecamp.org/#/how-to-add-playwright-tests?id=-identifying-a-dom-element) and how to test it, apparently you'll need to make some changes to your approach.

Sure Sir, I will look into the issue and try my best to resolve it.

**Comment by raisedadead** [comment]
Hey @Ahmadkashif, 

Thanks for updating the PR title.

We squash all commits. So, the commit messages are only important in a fast-forward merge, which we do not do these days mostly.

We can review the PR as is.

**Review by raisedadead — APPROVED** [review]

**Comment by anand-harsh** [comment]
@Ahmadkashif Sir, I have modified the code, can you please review the code and suggest if any changes are needed.

**Comment by raisedadead** [comment]
Hello,

Firstly, thank you for submitting this pull request!

As you navigate the process, we have a PR checklist to ensure consistency and quality in our contributions. Please follow through with each point. This facilitates the review process and demonstrates mutual respect for the community's efforts.

If you're unfamiliar with certain aspects, our [contributing guidelines](https://contribute.freecodecamp.org) are a helpful resource to get you up to speed.

<details>
<summary>Friendly Pointers (click to expand)</summary>

1. **Editing on GitHub:** While editing files directly on GitHub is possible, it's strongly discouraged. Please use the recommended setup. This helps avoid unintentional mistakes like typos that can disrupt tests.

2. **Linking Issues:** Please ensure you link issues using the designated method. Simply update the `XXXXXX` in the PR description to include the issue number. This keeps our records organized and clear.

3. **Engaging with the Team:** We know you're eager, but could you limit mentions and review requests? Our maintainers are always on the lookout and will attend to PRs in the order they come in.

4. **Branch Management:** It's a good practice not to work directly off your `main` branch. Creating separate branches for different changes allows you to update your PR even as the central repository progresses smoothly.

</details>

So that you know, there's no need to worry about closing this PR. Feel free to ask if you have questions or need guidance refining your contribution. Our community is here to assist.

Thank you for being so enthusiastic in contributing to our project. We eagerly await more contributions from you!

**Happy Contributing!** 🌟

**Review by raisedadead — CHANGES_REQUESTED** [review]
Thanks for the PR. Please fix the linting. If you need help visit: [contributors chat room](https://discord.com/invite/PRyKn3Vbay) 


**Note to maintainers: This PR has been made directly off of GitHub, and has never been tested locally.**

**Review by Sboonny — COMMENTED** [review]
@anand-harsh, the test shouldn't be looking in the page for an element and filter for specific tests.

You need to use `getByTestId` after adding the needed `data-playwright-test-label`

**Review by Sboonny — CHANGES_REQUESTED** [review]
@anand-harsh, the test shouldn't be looking in the page for an element and its specific text.

You need to use `getByTestId` after adding the needed `data-playwright-test-label`. Ahmad mention how you can do this in this [comment's link](https://github.com/freeCodeCamp/freeCodeCamp/pull/51723#issuecomment-1741992072)

**Comment by anand-harsh** [comment]
ok Sir, I will make the proper changes and will update the PR. Thanks for helping me with this.

**Comment by anand-harsh** [comment]
Sir, Kindly review the new PR #51768 which I have updated properly through Lint.

**Pull request closed without merging**
