### PR TITLE
update guide-text for 'surface-area-of-a-cone'

### PR DESCRIPTION
**Pull request by rusty-electron**
update guide-text for 'surface-area-of-a-cone' with proper-text, expressions and video-link

- [x] I have read [freeCodeCamp's contribution guidelines](https://github.com/freeCodeCamp/freeCodeCamp/blob/master/CONTRIBUTING.md).
- [x] My pull request has a descriptive title (not a vague title like `Update index.md`)
- [x] My pull request targets the `master` branch of freeCodeCamp.
- [x] None of my changes are plagiarized from another source without proper attribution.
- [x] My article does not contain shortened URLs or affiliate links.

If your pull request closes a GitHub issue, replace the XXXXX below with the issue number.

Closes #XXXXX

### CODE REVIEW

**Comment by RandellDawson** [comment]
@raisedadead  Very odd Travis CI failure

**Comment by raisedadead** [comment]
Seems to have passed for me. 
image

**Comment by RandellDawson** [comment]
@raisedadead That is good.  Before it had the something like the following:
```
This job was cancelled because the "Auto Cancellation" feature is currently enabled,
and a more recent build (#XXXXX) for pull request #XXXXX came in while this job was waiting to be processed.
```

**Comment by raisedadead** [comment]
Yes, I have enabled auto cancellation for PRs and branches to avoid the strain on the CI. 

Meaning if a PR is closed without merge or fresh commits were added to the PR, then the previous build if pending will get cancelled. 

This reduces the no of jobs on the CI.

In this case the OP may have accidentally closed and re-opened the PR. This is a corner case, and a restart is required. Which a mod can do when the notice it. So someone did restart it and this all looks good.

Please merge if the changes look good.

**Comment by RandellDawson** [comment]
Hi @rusty-electron. Congrats on your first pull request (PR)! 🎉

Thank you for your contribution to the page! 👍
We're happy to accept these changes, and look forward to future contributions. 📝

**Comment by rusty-electron** [comment]
Thanks.

**Pull request merged**
