### PR TITLE
fix(curriculum): corrected grammar in line 12 of the description section of learn HTML forms.md

### LINKED ISSUE #46854: Bad Grammer
### Describe the Issue

In this challenge the instructions say:

> Go ahead, and give each submittable element a unique name attribute of your choosing. Except for the two radio inputs.

The phrase 'Except for the two radio inputs' is not a complete sentence. 

### Affected Page

https://www.freecodecamp.org/learn/2022/responsive-web-design/learn-html-forms-by-building-a-registration-form/step-36

### Expected behavior

We should use complete sentences.

### Screenshots

_No response_

### System

All

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by oerzn**
Hello, 
In the description, the line "Go ahead, and give each submittable element a unique name attribute of your choosing. Except for the two radio inputs", 
the phase 
"Except for the two radio inputs' is not a complete sentence. 
To make it more Grammarly correct and complete, I change it to a new sentence. 
Please have a look.

Checklist:

- [x] I have read [freeCodeCamp's contribution guidelines](https://contribute.freecodecamp.org).
- [x] My pull request has a descriptive title (not a vague title like `Update index.md`)
- [x] My pull request targets the `main` branch of freeCodeCamp.
- [x] I have tested these changes either locally on my machine, or GitPod.

Closes #46854

### CODE REVIEW

**Comment by oerzn** [comment]
Hello Ieahleen,
I have provided the reason for the change that I made, please have a look.

Thank you

**Comment by ieahleen** [comment]
Thank you for your pull request, please follow the guideline on how to open a PR, so we are sure you are taking contributing seriously :)

**Comment by oerzn** [comment]
Thank you Jeremylt and ieahleen,

I have made the changes suggested by you, please look at it and let me know what else is needed.

**Comment by ieahleen** [comment]
I am pretty sure that the file you wrote is non-existent. Can you please follow the guine on how to give a name to a PR?

**Comment by jeremylt** [comment]
You're looking for

https://contribute.freecodecamp.org/#/how-to-open-a-pull-request?id=prepare-a-good-pr-title

something like:
```
fix(learn): what this pr does
````

**Comment by jdwilkin4** [comment]
HI @oerzn ! 

There seems to be some confusion on this part here:
> Closes https://github.com/freeCodeCamp/freeCodeCamp/pull/46859

It looks like you have linked the PR to itself.
Typically, when you use the closes keyword you want to link a PR to an open issue. 
Then when the PR is merged, the issue is automatically closed. 
Since this PR doesn't seem to address a current open issue, then you don't need that line at all.

You can learn more about linking PR's to issues in the GitHub docs here:
https://docs.github.com/en/issues/tracking-your-work-with-issues/linking-a-pull-request-to-an-issue#linking-a-pull-request-to-an-issue-using-a-keyword

Hope that helps! 👍

**Comment by jeremylt** [comment]
It closes this issue

https://github.com/freeCodeCamp/freeCodeCamp/issues/46854

**Comment by jdwilkin4** [comment]
Oh ok.
Thanks @jeremylt 
Then this is just a case of the wrong issue number being referenced. 
@oerzn if you can update your PR to include the correct number that would be great.

**Comment by oerzn** [comment]
Hi @jdwilkin4,

Sorry for the inconvenience, I have updated the PR number. 
Please have a look.

**Review by Sboonny — APPROVED** [review]
#### :sparkles: :tada: **AWESOME!** :tada: :sparkles:

 Hi @oerzn, thanks for this pull request and for contributing to the code-base for the first time. We are looking forward to more contributions from you in the future.

 Cheers & happy contributing!

**Review by jdwilkin4 — APPROVED** [review]
LGTM! 👍

**Pull request merged**
