### PR TITLE
Feat: add d3 dashboard project to next curriculum

### PR DESCRIPTION
**Pull request by moT01**
- [x] I have read [freeCodeCamp's contribution guidelines](https://github.com/freeCodeCamp/freeCodeCamp/blob/master/CONTRIBUTING.md).
- [x] My pull request has a descriptive title (not a vague title like `Update index.md`)
- [ ] My pull request targets the `master` branch of freeCodeCamp.
- [x] None of my changes are plagiarized from another source without proper attribution.
- [x] All the files I changed are in the same world language (for example: only English changes, or only Chinese changes, etc.)
- [x] My changes do not use shortened URLs or affiliate links.

### CODE REVIEW

**Comment by moT01** [comment]
Well, I think this is ready to go @scissorsneedfoodtoo. I'm convinced the tests are failing from the challenges in one of the other projects. Likely, the calorie counter.

**Comment by raisedadead** [comment]
Can we push a fix to the failing challenge on the `next-curriculum` branch, and then get this rebased

**Comment by raisedadead** [comment]
We essentially want each commit on the `next-curriculum` to be pristine.

**Comment by scissorsneedfoodtoo** [comment]
Awesome, thank you for all of your hard work on this @moT01. Yes, some of the RPG game tests broke with the new loop protection. They were fixed in https://github.com/freeCodeCamp/freeCodeCamp/pull/38128/files.

Seems like everything is passing now that you rebased. I'll pull this down and do a quick check locally before merging.

**Comment by scissorsneedfoodtoo** [comment]
Thanks for your patience and again for all of your hard work @moT01. Tested this locally and ran through about 1/3 of the challenges. Everything LGTM :+1: :+1:

**Pull request merged**
