### PR TITLE
chore(i18n,docs): processed translations

### PR DESCRIPTION
**Pull request by camperbot**
This PR was opened auto-magically by Crowdin.

### CODE REVIEW

**Review by naomi-lgbt — APPROVED** [review]

**Review by ShaunSHamilton — CHANGES_REQUESTED** [review]
Just holding this, until the typos are through: https://github.com/freeCodeCamp/freeCodeCamp/pull/44102

**Comment by raisedadead** [comment]
> Just holding this, until the typos are through:

That doesn't help in any way. The changes from the PR will be synced, via Crowdin regardless.

**Comment by ShaunSHamilton** [comment]
> That doesn't help in any way.

@raisedadead Does it not prevent translators from translating incorrect files? That is, this is not on Crowdin yet, but will be once this is merged, no?

**Comment by raisedadead** [comment]
> Does it not prevent translators from translating incorrect files? That is, this is not on Crowdin yet

The PR is created by a bot pulling changes from Crowdin. These files (with the errors) are on Crowdin and the translators are seeing & translating them (yes with the errors). 

The only reason we hold Crowdin Sync PRs is for a technical bug in the changes being pulled down. This PR has none. You are welcome to hold it if you please, it will get overwritten in a day / or two. 

But as is holding these for content consistency reasons is not going to make any difference.

**Review by ShaunSHamilton — APPROVED** [review]

**Pull request merged**
