### PR TITLE
feat: reduce font size on completed challenge numbers

### LINKED ISSUE #50874: Polish the completed step styles of the grid map in the courses
the current font weight is too big, and could be improved visually.

thumb-Clipboard - June 22, 2023 13_13

Reducing the font weight of non completed to `400`, and the font weight of completed one to `600` or `700` can improve them 
Clipboard - June 22, 2023 14_34

---

@naomi-lgbt suggested adding border, which I like the idea of.

thumb-Clipboard - June 22, 2023 14_47

Generally, I prefer box shadows over borders, but that is personal preference.

Clipboard - June 29, 2023 12_49 PM

---

@bbsmooth, what do you think about polishing the steps?

### PR DESCRIPTION
**Pull request by naomi-lgbt**
Checklist:

- [X] I have read and followed the [contribution guidelines](https://contribute.freecodecamp.org).
- [X] I have read and followed the [how to open a pull request guide](https://contribute.freecodecamp.org/#/how-to-open-a-pull-request).
- [X] My pull request targets the `main` branch of freeCodeCamp.
- [X] I have tested these changes either locally on my machine, or GitPod.

<details>
  <summary>The current style has the numbers at a jarringly larger font size.</summary>

image

</details>

<details>
  <summary>The aim is to retain the visual distinction, but not in such an aggressive manner.</summary>
    
image

</details>

<details>
  <summary>If the smaller font size results in a lack of clarity, I've got a commit I can push that experiments with borders.</summary>
    
image

</details>

Closes: https://github.com/freeCodeCamp/freeCodeCamp/issues/50874

### CODE REVIEW

**Comment by bbsmooth** [comment]
Please bear with me as I try to explain all of the intricacies regarding accessibility here.

The main issue is that we can't rely on just color to distinguish between completed and uncompleted steps ([SC 1.4.1](https://www.w3.org/WAI/WCAG21/Understanding/use-of-color.html)). Of course not even this is as straightforward as it sounds because "color" in WCAG does not really mean what we traditionally think it means. In WCAG, color is actually "hue" and is separate from "lightness". Basically this means that as long as the colors have a different hue and a contrast ratio of at least 3:1 then they meet the SC. A while ago I made a push to change the background colors of the completed steps so they had at least 3:1 contrast with the background (and thus meet SC 1.4.1) but that didn't go anywhere. Thus, since our current background colors do not have enough contrast we have to come up with a non-color alternative. 

Basically, as long as we do something else then we are technically meeting WCAG standards. So even just making the font weight bolder would be enough. Of course there is a difference between technically meeting a standard and actually making sure that what we are doing is accessible to as many people as possible. Thus, I think that increasing the font size also helps make the distinction clearer. How big that font size increase should be is something we would really need to do some testing on to get a good answer. As a test, using your font size change in this PR, while in dark mode, I removed the blue background from the completed steps and to be honest, I could hardly tell a difference. Putting it back up to `1.5rem` was definitely better.

And I really like your border idea. I wouldn't mind seeing that regardless of what we decide with the font size.

So does this PR break accessibility? Technically, no. Could we perhaps do some other things to make the distinction between completed and uncompleted steps better. I think so. I'm tempted to agree that I don't necessarily like the looks of the bigger font size as it is now. But I do think that reducing it could potentially cause issues for some people. I would prefer that if we reduce it we either add the borders or we make the background color on the completed steps at least 3:1 (or perhaps someone has another idea).

**Comment by naomi-lgbt** [comment]
Thanks for all of the insight. I agree 100% that we want to keep things accessible for everyone - but I'd like to do so while still being aesthetically pleasing.

I went ahead and pushed up the border commit if you'd like to take a look.

**Comment by bbsmooth** [comment]
I really like the symbolism of the borders (dashed, or incomplete border vs. solid, or complete borders).

I would like to recommend a change to the focus outline for these if we go with the borders. 

On line 252, change the outline offset for the focus indicator so it is just outside of the border:

```
.map-challenges-grid .map-challenge-title a:focus {
  outline-offset: 1px;
}
```

And then remove the change in outline-color for the completed steps completely by remove the following ruleset on line 290:

```
.challenge-completed:focus-visible {
  outline-color: var(--secondary-color);
}
```

This way the color of the focus indicator will be consistent for all steps and it will allow the user to see the border at all times, even when focus is placed on the step.

**Comment by naomi-lgbt** [comment]
That looks much better.

**Review by bbsmooth — APPROVED** [review]
I really like the added borders. Both improves accessibility and makes it look more like a grid. LGTM!

**Review by moT01 — COMMENTED** [review]
I think this looks really good @naomi-lgbt 👍 to me, it more clearly communicates complete vs incomplete (visually anyway).

I would be fine adding this as-is, but here's some thoughts...

One thing that we could maybe do, is keep the hover effect for completed challenges. On production, hovering completed challenges gives a grey background - this PR has no effect when hovering completed challenges. Perhaps that was intentional.

<details><summary>
The outlines can look a little... dizzying at times</summary>

Screen Shot 2023-06-29 at 11 39 53 AM

This is just an observation. I'm not really sure if this is a problem or not. Here's a potential alternative:

Screen Shot 2023-06-29 at 11 59 05 AM

</details>

<details><summary>
Another potential idea if we keep the dashed borders - make the hovered one solid</summary>

Jun-29-2023 12-04-17

</details>

**Review by Sboonny — DISMISSED** [review]
LGTM

**Comment by naomi-lgbt** [comment]
What if we apply a border *only* to the completed challeenges?

**Comment by moT01** [comment]
I opened this us and played with some more options...

<details><summary>no borders</summary>

Screen Shot 2023-07-07 at 7 21 34 AM

</details>

<details><summary>no margins</summary>

Screen Shot 2023-07-07 at 7 20 17 AM

</details>

<details><summary>borders or no margins</summary>

Screen Shot 2023-07-07 at 7 22 16 AM

</details>

I kind of like the condensed versions.

**Comment by naomi-lgbt** [comment]
I like the no margins option. Looks like a proper grid.

**Comment by moT01** [comment]
One other idea I had was that we could maybe make the borders angled on the right, so it looks like it's pointing to the next number.

**Comment by naomi-lgbt** [comment]
That might get a little too complex, IMHO.

**Comment by ahmaxed** [comment]
I appreciate the symbolism and agree that our layout should be as inclusive as possible. 
Border overlapping and the high contrast border colors bring more attention to the grid than necessary.

I recommend lowering the contrast for the borders and spacing out the grid items to avoid overlaping.

```
map-challenge-title-grid a.map-grid-item {
    justify-content: center;
    border: 1px dashed var(--background-tertiary);
    margin: 2px;
}
```
Since we have a sold border for completed challenges, we could go down to font-weight: 700 (bold) for the challenge-completed span, but I leave it up to you.

Screenshot 2023-07-17 at 12 56 35 PM

**Comment by naomi-lgbt** [comment]
New look:

image

**Review by bbsmooth — COMMENTED** [review]
The important thing is that the solid border on completed steps has enough color contrast to be considered a sufficient technique for conveying the state of the step.

As for the dashed border on the uncompleted steps, to be honest, I can barely see it in light mode and I cannot see it at all in dark mode. The contrast is so weak as to be almost non-existent. It does no harm to leave it like this as we aren't depending on it for accessibility. But I question what the point of it is if a considerable amount of people won't be able to see it.

**Comment by ahmaxed** [comment]
I could up the contrast a notch and it should be perfect.

**Review by ahmaxed — APPROVED** [review]

**Pull request merged**
