### PR TITLE
fix: update German News and forum links

### PR DESCRIPTION
**Pull request by scissorsneedfoodtoo**
Checklist:

- [x] I have read [freeCodeCamp's contribution guidelines](https://contribute.freecodecamp.org).
- [x] My pull request has a descriptive title (not a vague title like `Update index.md`)
- [x] My pull request targets the `main` branch of freeCodeCamp.
- [x] I have tested these changes either locally on my machine, or GitPod.

Closes #XXXXX

This PR updates the German forum link to prevent a redirect, and the News link now that German News is live.

### CODE REVIEW

**Review by Sboonny — DISMISSED** [review]
LGTM 🎉, thank you for your contribution to the page! 👍.

**Review by sidemt — CHANGES_REQUESTED** [review]
The German subforum doesn't have "Backend Development" subforum. So we need to change it to `"Backend Development": "German/programming-help"` in line 29.

**Comment by scissorsneedfoodtoo** [comment]
Awesome, thanks for catching that @sidemt. I didn't see that before.

I'll go in and make that change now.

**Review by Sembauke — APPROVED** [review]

**Review by sidemt — APPROVED** [review]
LGTM!
image

**Pull request merged**
