### PR TITLE
Update user test 13 desc to match changed test

### PR DESCRIPTION
**Pull request by ksalzke**
Refer https://github.com/freeCodeCamp/testable-projects-fcc/issues/933.

This pull request updates the challenge text to reflect the change made to user story 13 (i.e. that the negative sign is included in the calculation where there are multiple operators) by pull request 910 in that repository.

- [x] I have read [freeCodeCamp's contribution guidelines](https://github.com/freeCodeCamp/freeCodeCamp/blob/master/CONTRIBUTING.md).
- [X] My pull request has a descriptive title (not a vague title like `Update index.md`)
- [X] My pull request targets the `master` branch of freeCodeCamp.
- [X] None of my changes are plagiarized from another source without proper attribution.
- [X] All the files I changed are in the same world language (for example: only English changes, or only Chinese changes, etc.)
- [X] My changes do not use shortened URLs or affiliate links.

PS. This is my first (ever) contribution so please let me know if I have done anything incorrectly and I will do my very best to fix it!

### CODE REVIEW

**Review by Steffan153 — CHANGES_REQUESTED** [review]
Looks like you did stuff correctly. I think it's still kind of confusing though, maybe add an example that '6*-6' means '6 * (-6)', or something like that?

**Comment by ksalzke** [comment]
> Looks like you did stuff correctly. I think it's still kind of confusing though, maybe add an example that '6*-6' means '6 * (-6)', or something like that?

Updated as suggested.

**Review by Steffan153 — APPROVED** [review]
Looks good now :)

**Review by ojeytonwilliams — APPROVED** [review]
That's much clearer.  LGTM :+1:

**Comment by RandellDawson** [comment]
@tbushman What do you think about this change?  The testable projects repo would also need to be updated.

**Comment by tbushman** [comment]
The testable project user story was recently changed in this way, but we could also add the example. This LGTM! Thank you @ksalzke !

**Comment by thecodingaviator** [comment]
@tbushman @scissorsneedfoodtoo Can this PR be merged? (Has the work required in the testable-projects-fcc repo completed?)

**Comment by raisedadead** [comment]
Hi @scissorsneedfoodtoo let land this.

**Comment by scissorsneedfoodtoo** [comment]
Sorry I missed the earlier notifications here. Everything LGTM.

**Pull request merged**
