### PR TITLE
feat(client): handle lessons with syntax errors

### LINKED ISSUE #49018: HTML challenges do not warn users or run tests when there are syntax errors
**Describe the bug**
Syntax errors in HTML and multifile challenges stop the tests from running.

**To Reproduce**
1. Go to https://www.freecodecamp.org/learn/2022/responsive-web-design/learn-html-by-building-a-cat-photo-app/step-2
2. Replace code with `<script> ) </script>`
3. Click "Check Your Code..."
4. See nothing

**Expected behavior**

The tests should still run, even with broken syntax. Otherwise challenge creators are overly limited in the kinds of lessons they can write.

This is trickier to do for HTML challenges than pure JS ones, since we first build the frame and then run the test code in it.  When there's a syntax error, that's not possible. Instead we will probably need to create a separate environment for the test to run in.  A JS test runner, perhaps?

@naomi-lgbt is there anything I missed?

### PR DESCRIPTION
**Pull request by ojeytonwilliams**
Checklist:

- [x] I have read and followed the [contribution guidelines](https://contribute.freecodecamp.org).
- [x] I have read and followed the [how to open a pull request guide](https://contribute.freecodecamp.org/#/how-to-open-a-pull-request).
- [x] My pull request targets the `main` branch of freeCodeCamp.
- [x] I have tested these changes either locally on my machine, or GitPod.

Syntax errors in learner code should still generate an error in the console, but now it should be possible to run tests against the code irrespective of whether or not it's syntactically valid.

To test this, the easiest thing to do is to modify a lesson so that it just tests `code` and then go that lesson, create a syntax error and run the tests.

Closes: https://github.com/freeCodeCamp/freeCodeCamp/issues/49018

### CODE REVIEW

**Review by Nirajn2311 — COMMENTED** [review]
The PR's good to go from mobile perspective. Not sure why it got removed.

**Review by jdwilkin4 — COMMENTED** [review]
I tested this locally and it is working well on my end.
This will be a huge help to campers and for us to teach syntax lessons in the debugging projects.

But how do we want to handle this open issue 
https://github.com/freeCodeCamp/freeCodeCamp/issues/52749

We could just close it, since this PR does resolve that issue of the tests not running.

But I am also wondering if it would be good to add an additional generalized message to the console to let them know that they have syntax errors. That was brought up in that issue thread. 

Maybe something like this

```md
Your code has syntax errors. Double check that you are not missing any commas `,` or curly braces `{`. 
```

thoughts?

**Comment by ojeytonwilliams** [comment]
It's a bit tricky to make the console output clear.

As of this PR the console will show the syntax error until the learner runs the tests. At that point it will show test output and any errors raised during the testing. Putting the syntax error into the console as well as all that would make it quite busy and confusing.

How about adding a message to the lower jaw if there's a syntax error and they haven't run the tests?

image

**Comment by jdwilkin4** [comment]
I like that solution 👍

**Review by jdwilkin4 — APPROVED** [review]
Looks good to me.

> How about adding a message to the lower jaw if there's a syntax error and they haven't run the tests?

This could be optional. Nice but non blocking in my opinion 👍

**Review by naomi-lgbt — APPROVED** [review]
This is slick

**Pull request merged**
