### PR TITLE
Created Index.md for std::sort

### LINKED ISSUE #19207: Creating guide for STL-Algorithms under C++

### PR DESCRIPTION
**Pull request by kvmsc**
Sort algorithm from STL-Algorithms Header File

- [x] I have read [freeCodeCamp's contribution guidelines](https://github.com/freeCodeCamp/freeCodeCamp/blob/master/CONTRIBUTING.md).
- [x] My pull request has a descriptive title (not a vague title like `Update index.md`)
- [x] My pull request targets the `master` branch of freeCodeCamp.
- [x] None of my changes are plagiarized from another source without proper attribution.
- [x] My article does not contain shortened URLs or affiliate links.

If your pull request closes a GitHub issue, replace the XXXXX below with the issue number.

Closes #19207

### CODE REVIEW

**Comment by Asjas** [comment]
>I have read freeCodeCamp's contribution guidelines.

**Comment by kvmsc** [comment]
I don't understand. What's wrong? Please help. I'll try to change in my future PR's.

**Comment by Asjas** [comment]
Hi @kvmsc 

Your PR does not conform to the contributing guidelines. You checked the checkbox in your template. Please read it before submitting a future PR.

1. You may not use spaces in folder names.
2. You may only use hyphens `-` to separate words in a folder name.
3. Folder names must be lowercase.
4. The article in a folder must be called `index.md`.
5. Your article must have a `title`.
6. Your article needs to follow the standard structure according to the Article Style Guide. Which is linked from the contributing guidelines.

**Comment by Asjas** [comment]
Yes you can :+1:

**Comment by kvmsc** [comment]
I have created another pull request. Please Review. 
https://github.com/freeCodeCamp/freeCodeCamp/pull/19225

**Pull request closed without merging**
