### PR TITLE
fix(docs): change incorrect link on Contribute page

### LINKED ISSUE #44808: Incorrect links on Contribute page
## Affected page

https://contribute.freecodecamp.org/#/index?id=translations

## To reproduce

The Italian and Portuguese curriculum links in the "Translations" section are both pointing to the Spanish page.

## Recommended fix, suggestions

- Change the Italian link to https://www.freecodecamp.org/italian/learn 
- Change the Portuguese link to https://www.freecodecamp.org/portuguese/learn/
- The file that needs to be updated: https://github.com/freeCodeCamp/freeCodeCamp/blob/main/docs/index.md#translations

### PR DESCRIPTION
**Pull request by urvisinghal**
Checklist:

- [x] I have read [freeCodeCamp's contribution guidelines](https://contribute.freecodecamp.org).
- [x] My pull request has a descriptive title (not a vague title like `Update index.md`)
- [x] My pull request targets the `main` branch of freeCodeCamp.
- [x] I have tested these changes either locally on my machine, or GitPod.

Closes #44808

### CODE REVIEW

**Review by gikf — DISMISSED** [review]
LGTM :+1:

**Review by ShaunSHamilton — CHANGES_REQUESTED** [review]
Hello there,

You have not done anything incorrect. However, I have blocked this until we figure out why:
- https://www.freecodecamp.org/portuguese/learn/   -  Goes to `https://www.freecodecamp.org/learn`
- https://www.freecodecamp.org/portuguese/learn     -  Goes where it should

**Review by raisedadead — CHANGES_REQUESTED** [review]

**Review by raisedadead — APPROVED** [review]
We have moved to a conclusion and this can be unblocked for now.

**Review by ShaunSHamilton — APPROVED** [review]
LGTM 👍

**Comment by ShaunSHamilton** [comment]
Thank you for your contribution to the page! 👍
We are happy to accept these changes, and look forward to future contributions. 🎉

**Pull request merged**
