### PR TITLE
fix(docs): update styling on contributing documentation

### LINKED ISSUE #38589: Update the styles on the contributing documentation
We want to update the styles and theme on the [contributing documentation](https://contribute.freecodecamp.org) site. [Here is a guide](https://contribute.freecodecamp.org/#/how-to-work-on-the-docs-theme) on how to work on the theme and styles.

We would want to:

1. Remove the extraneous CSS 
   - I had shamelessly copied the code from Netflix's awesome pollyjs project [here](https://github.com/Netflix/pollyjs/blob/master/docs/assets/styles.css) while setting up the site.
   - The CSS above depends on the `vue.css` that ships with `docsify`.
2. Write our own theme with [`docsify-themeable`](https://jhildenbiddle.github.io/docsify-themeable/#/).
3. ~Have the Universal Nav~ (already done).
4. Fonts and colors should follow our [design style guide](https://design-style-guide.freecodecamp.org/).
5. Use larger font size similar to our main sites

### PR DESCRIPTION
**Pull request by AshNaz87**
Checklist:

- [x] I have read [freeCodeCamp's contribution guidelines](https://contribute.freecodecamp.org).
- [x] My pull request has a descriptive title (not a vague title like `Update index.md`)
- [x] My pull request targets the `master` branch of freeCodeCamp.
- [x] All the files I changed are in the same world language, for example: only English changes, or only Chinese changes, etc.

Targets #38589

[WIP]

- Ideally the root page should use the `Roboto-Mono` font-family. However, as the documentation uses Markdown, I felt going down the route of targeting classes using attribute selectors may not be the way to go. Hence, I decided on using the `Lato` font-family.
- Also, the `Roboto-Mono` font-family is slightly larger and took up more space in the body. This was more prominent in the left sidebar.

All comments welcome :)

### CODE REVIEW

**Comment by AshNaz87** [comment]
**Update**

Have main the cover page, use the `Roboto` font-family

See screenshots below
Screenshot 2020-04-25 at 23 08 20
Screenshot 2020-04-26 at 03 36 48
Screenshot 2020-04-26 at 03 36 56

**Comment by raisedadead** [comment]
We specify the typography in our design style guide, its linked in the issue.

**Comment by raisedadead** [comment]
Overall, this is a good direction. I am marking it draft while in  WIP. 

As I mentioned in the issue, we would like to have the `docsify-themable` plugin and have our own theme, which should also then let us use the dark/light switch.

**Comment by AshNaz87** [comment]
@raisedadead 

> We specify the typography in our design style guide, its linked in the issue.

Yep. I've taken this into consideration and is reflected in the PR

> As I mentioned in the issue, we would like to have the docsify-themable plugin and have our own theme, which should also then let us use the dark/light switch.

Sure. I wasn't quite sure with regards to creating a separate theme. I may have missed something,  but in the documentation, it specified changing the styling using the `style` tag.

**Comment by raisedadead** [comment]
I haven't gotten a chance to pull this down, but great to know that the changes are along the lines of what we want. I wanted to make sure no to waste your time :)

As for the theme, yes it will live in the `theme.css` but at the minute:

1. The CSS in the `theme.css` is dependent on `vue.css`, something which are including in the `index.html`. This css dependency should be removed. All the CSS that is currently in the `theme.css` will obviously break.
2. Hence we should include the plugin I mentioned. Its already commented in the file for your reference.
3. The `theme.css` should then be re-written override what we need, and make everything nice and clean.
4. Finally we can add the dark/light toggle plugin with the definition that we write.

**Comment by AshNaz87** [comment]
> Hence we should include the plugin I mentioned. Its already commented in the file for your reference.

Sorry, but where is this mentioned?

**Comment by raisedadead** [comment]
Here: https://github.com/freeCodeCamp/freeCodeCamp/issues/38589#issue-603369313 and here: https://github.com/freeCodeCamp/freeCodeCamp/pull/38639#issuecomment-619538161

**Comment by AshNaz87** [comment]
Sorry, when you said "plugin," is this something we have to create on Docsify?

Or should we strictly focus on `theme.css` and remove the `vue.css` dependency?

**Comment by raisedadead** [comment]
> Sorry, when you said "plugin," is this something we have to create on Docsify?

I am not sure what you mean, the plugin for theme is already available (and commented out in the code for your reference). 

Did you get a chance to go through my comments and the index.html? I clarified the requirements here: https://github.com/freeCodeCamp/freeCodeCamp/pull/38639#issuecomment-619548282?

**Comment by RandellDawson** [comment]
@AshNaz87 How's it going with addressing @raisedadead's suggestions?

**Comment by raisedadead** [comment]
I am going to go ahead and close, this. I think @thecodingaviator is working on this.

**Pull request closed without merging**
