### PR TITLE
fix(curriculum): refactor Cat Photo App step 12

### LINKED ISSUE #54767: Refactor step 12 of HTML cat photo app project
### Describe the Issue

We are still getting a ton of questions about how to do step 12 of the cat photo app project.
https://forum.freecodecamp.org/search?q=step%2012%20cat%20photo%20app%20%23html-css

So I am not entirely sure how to best update this.
Maybe there needs to be a different code example?
Maybe the hints need to be updated?

Maybe something else?

There are too many people lost on this step so I should be updated to make it clearer on what needs to be done.
So I am opening this up for discussion

### Affected Page

https://www.freecodecamp.org/learn/2022/responsive-web-design/learn-html-by-building-a-cat-photo-app/step-12

### Your code

see explanation above

### Expected behavior

see explanation above

### Screenshots

_No response_

### System

- Device: [e.g. iPhone 6, Laptop]
- OS: [e.g. iOS 14, Windows 10, Ubuntu 20.04]
- Browser: [e.g. Chrome, Safari]
- Version: [e.g. 22]

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by Supravisor**
Checklist:

- [x] I have read and followed the [contribution guidelines](https://contribute.freecodecamp.org).
- [x] I have read and followed the [how to open a pull request guide](https://contribute.freecodecamp.org/how-to-open-a-pull-request/).
- [x] My pull request targets the `main` branch of freeCodeCamp.
- [x] I have tested these changes either locally on my machine, or GitPod.

Closes #54767

### CODE REVIEW

**Comment by moT01** [comment]
Can you take a look at the failing tests here @Supravisor.

**Comment by Supravisor** [comment]
>Challenge slugs must be unique, but /learn/2022/responsive-web-design/learn-html-by-building-a-cat-photo-app/step-14 already exists.

I think this is due to the insertion of a new step. 

> Please wait for approval before running the sync, it makes review impossible.
https://github.com/freeCodeCamp/freeCodeCamp/pull/54983#issuecomment-2154546016

**Comment by Supravisor** [comment]
Is there anything else I need to do for this PR?

**Comment by a2937** [comment]
You have end to end tests that are failing. You see buddy pieces of code are linked to other pieces of their curriculum in ways that aren't always obvious at first. You see by changing the Cat Photo App solutions, some of the input for the end to end (spelled e2e)  tests need to be updated too. Does that make sense?

**Comment by a2937** [comment]
Do you want me to explain what you need to do to  the end to end tests?

**Comment by Supravisor** [comment]
Yes, please explain how to handle the e2e tests.

e2e tests for practice projects: Step x + step x solution code should equal step x + 1 seed code.

**Comment by a2937** [comment]
Okay the lower-jar.spec.ts and progress-bar.spec.ts files uses the Cat Photo App project to verify if the code submissions are able to go through. As you updated the solutions, the solutions need updated in the test code. 

[One of the tests in the lower-jar.spec.ts that need updated](https://github.com/Supravisor/freeCodeCamp/blob/43e902dd85a1b9526bcc76e2d6330a1624258406/e2e/lower-jaw.spec.ts#L101-L129)

[A test in progress-bar.spec.ts that need updated](https://github.com/Supravisor/freeCodeCamp/blob/43e902dd85a1b9526bcc76e2d6330a1624258406/e2e/progress-bar.spec.ts#L7-L35)

**Comment by Supravisor** [comment]
Not sure what is causing the string error.

image

image

**Comment by a2937** [comment]
Hmm yeah for some odd reason the progress bar test is saying that almost all of the curriculum is completed event though only 0% is supposed to be done.

**Comment by Supravisor** [comment]
Could it have anything to do with this?:

image

**Comment by a2937** [comment]
I found the problem. You see that challenge wasn't added to the seeded user. Unfortunately for the progress bar, it expects the cat photo app to be at 100% completion. As you added a challenge, it wasn't complete any more. 

That does raise the question what other kinds of things aren't in the seed code anymore.

**Comment by a2937** [comment]
Here is roughly where you need to insert content. 

https://github.com/Supravisor/freeCodeCamp/blob/40ad1a6667495efcee362899d843d16856976254/tools/scripts/seed/user-data.js#L4510-L4513 

And the following should be added:

```
 {
        id: '668bae23be54d01f57738a11',
        completedDate: 1689770484197,
        files: []
},
```

This adds the id of your challenge onto the list of completed challenges.

**Comment by ilenia-magoni** [comment]
> Could it have anything to do with this?:

that is not related to the failing test, but you need to solve the merge conflict too

**Review by Supravisor — COMMENTED** [review]
I do not know where the merge conflict is located.

If merge conflict is https://github.com/freeCodeCamp/i18n-curriculum/tree/2f7cff50a959c31fe689a5fcece8eacd808fa324
then they are in another repo.

`Resolve conflicts` button appears faded.
image

**Comment by ilenia-magoni** [comment]
update your branch to be on pair with main branch

you should join our [Discord](https://discord.gg/KVUmVXA) server and ask for help in the `#contributors` channel. That will help other contributors guide you to get your PR ready for a review.

**Comment by a2937** [comment]
I believe this article can also help you understand what you need to do a little bit. https://www.freecodecamp.org/news/the-definitive-guide-to-git-merge/

**Comment by moT01** [comment]
There shouldn't be any changes to the `curriculum/i18n-curriculum` on this PR. Try running `git submodule update --init` when you have your PR checked out.

**Comment by Supravisor** [comment]
> update your branch to be on pair with main branch
> 
> you should join our [Discord](https://discord.gg/KVUmVXA) server and ask for help in the `#contributors` channel. That will help other contributors guide you to get your PR ready for a review.

I am unable to use Discord at the moment.

**Comment by Supravisor** [comment]
> There shouldn't be any changes to the `curriculum/i18n-curriculum` on this PR. Try running `git submodule update --init` when you have your PR checked out.

I ran the code with the PR checked out and committed an empty committ, no joy.

**Comment by moT01** [comment]
I pushed a fix @Supravisor. This is what I did:

cd curriculum/i18n-curriculum
git checkout 2eeff0 (the hash of where the submodule was at when you made this PR)
cd ../.. (back to main freeCodeCamp repo folder)
git add
git commit

**Comment by Supravisor** [comment]
Is this a conflict I can / should resolve?
image

**Comment by ilenia-magoni** [comment]
Thank you for opening this PR, an other PR that solves the issue has been merged.

**Pull request closed without merging**
