### PR TITLE
feat(curriculum): remove reliance on .lang.md extensions

### LINKED ISSUE #38763: Add a test to check that each challenge file ends with .language.md
A number of challenges were added that just have the `.md` extension. I'm not sure if that's a problem, but most challenges end with `.english.md` or `.other-language.md`. We could maybe add a test to check that each file ends with that.

### PR DESCRIPTION
**Pull request by ShaunSHamilton**
Checklist:

- [x] I have read [freeCodeCamp's contribution guidelines](https://contribute.freecodecamp.org).
- [x] My pull request has a descriptive title (not a vague title like `Update index.md`)
- [x] My pull request targets the `master` branch of freeCodeCamp.
- [ ] All the files I changed are in the same world language, for example: only English changes, or only Chinese changes, etc.

Closes #38763

### CODE REVIEW

**Comment by Sky020** [comment]
With the current code, these are the failing tests:
image

**Comment by Sky020** [comment]
This will fail the tests, until the challenges missing the `.language.md` is rectified.

**Comment by ojeytonwilliams** [comment]
Hey Shaun, now that I review this, I'm not sure the `.language.md` extension needs to be there any more.  All the challenges of a given language live in `/curriculum/challenges/language` so the path already contains that information.

That said, when I last looked at this I was thinking about it along the same lines as you:

https://github.com/ojeytonwilliams/freeCodeCamp/blob/c9a814219f3e3a3d2a99626cf0269f5020e185d5/curriculum/getChallenges.js#L177-L183

however, I think my approach was probably wrong and that I should have been using directory structure, not the extension.

So, I need to confirm that https://github.com/freeCodeCamp/freeCodeCamp/pull/38040 can work without the extensions.  If that's true, then all the extensions should be removed.  If it's not true, then this PR is will be necessary.

**Comment by ojeytonwilliams** [comment]
Hey @Sky020, are you still working on this?  I need to redo some of the translation parser and I was wondering if I could build on any work you've done.

**Comment by Sky020** [comment]
Hey @ojeytonwilliams , Yes, I am working through it. I have made very little progress though. So, I can push my latest changes, but you are probably better off writing from scratch. I do not like the current way these tests and functions are laid out, and am looking for a way to restructure some of them.

There are too many functions that do/check the same thing

**Comment by ojeytonwilliams** [comment]
@Sky020 agreed, it is more convoluted than it needs to be.  What I should have done is validate the two challenges exist one time and then just passed the relevant info around.

I don't mind looking at rough code if you want to push what you have.  Up to you.

**Comment by Sky020** [comment]
@ojeytonwilliams I have pushed the most recent changes. `getEnglishPath` is broken. I will get to fixing it, later today. Otherwise, I have most of the tests in a way that should work (only tested quickly)

**Comment by Sky020** [comment]
Current tests appear to show that the chinese curriculum is way behind. So, tests will always fail.

<details>
<pre>
Populate tests.Challenges in both languages must have the same number of tests.
    title: Check For The Presence of an Element With indexOf()
    localeTitle: 使用 indexOf() 检查元素是否存在
⠼ Populate tests.Challenges in both languages must have the same number of tests.
    title: Mutations
    localeTitle: 突变
Change this line does not appear in the comment dictionary
⠴ Populate tests.Challenges in both languages must have the same number of tests.
    title: Repeat a String Repeat a String
    localeTitle: 重复一个字符串重复字符串
Setup does not appear in the comment dictionary
Challenges in both languages must have the same number of tests.
    title: Arguments Optional
    localeTitle: 参数可选
⠦ Populate tests.Challenges in both languages must have the same number of tests.
    title: Add Methods After Inheritance
    localeTitle: 继承后添加方法
Setup does not appear in the comment dictionary
responseFromServer represents a response from a server does not appear in the comment dictionary
Change this line does not appear in the comment dictionary
Change this line does not appear in the comment dictionary
Challenges in both languages must have the same number of tests.
    title: Apply Functional Programming to Convert Strings to URL Slugs
    localeTitle: 应用函数式编程将字符串转换为URL片段
Setup does not appear in the comment dictionary
⠧ Populate tests.The global variable does not appear in the comment dictionary
Setup does not appear in the comment dictionary
Change this line does not appear in the comment dictionary
Change this line does not appear in the comment dictionary
⠇ Populate tests.Setup does not appear in the comment dictionary
Change this line does not appear in the comment dictionary
Change this line does not appear in the comment dictionary
Change this line does not appear in the comment dictionary
Change this line does not appear in the comment dictionary
After passing the challenge experiment with myString and see how the grouping works does not appear in the comment dictionary
Challenges in both languages must have the same number of tests.
    title: Check For Mixed Grouping of Characters
    localeTitle: 检查混合字符组
Setup does not appear in the comment dictionary
Change this line does not appear in the comment dictionary
Change this line does not appear in the comment dictionary
Change this line does not appear in the comment dictionary
Change this line does not appear in the comment dictionary
⠏ Populate tests.The global variable does not appear in the comment dictionary
Setup does not appear in the comment dictionary
Change this line does not appear in the comment dictionary
Change this line does not appear in the comment dictionary
Change this line does not appear in the comment dictionary
Challenges in both languages must have the same number of tests.
    title: Find Characters with Lazy Matching
    localeTitle: 用惰性匹配来查找字符
The global variable does not appear in the comment dictionary
Change this line does not appear in the comment dictionary
Change this line does not appear in the comment dictionary
Setup does not appear in the comment dictionary
Change this line does not appear in the comment dictionary
Change this line does not appear in the comment dictionary
Change this line does not appear in the comment dictionary
Change this line does not appear in the comment dictionary
⠋ Populate tests.Complete the method below and implement the others similarly does not appear in the comment dictionary
Open your browser console. does not appear in the comment dictionary
Use console.log() to print the output variable. does not appear in the comment dictionary
Run the tests to see the difference between the two consoles. does not appear in the comment dictionary
Now, add console.clear() before your console.log() to clear the browser console, and pass the tests. does not appear in the comment dictionary
Challenges in both languages must have the same number of tests.
    title: Understanding the Differences between the freeCodeCamp and Browser Console
    localeTitle: 了解freeCodeCamp和浏览器控制台之间的差异
Change this line does not appear in the comment dictionary
responseFromServer is set to true to represent a successful response from a server does not appear in the comment dictionary
Function that returns a string representing a cup of green tea does not appear in the comment dictionary
Given a function (representing the tea type) and number of cups needed, the
following function returns an array of strings (each representing a cup of
a specific type of tea). does not appear in the comment dictionary
Creates a 2-D array with m rows and n columns of zeroes does not appear in the comment dictionary
</pre>
</details>

**Comment by ojeytonwilliams** [comment]
Hey @Sky020, I ended up re-writing things entirely.  Just to check: is it okay if I force push and erase the existing commit history?

**Comment by Sky020** [comment]
@ojeytonwilliams 
> is it okay if I force push and erase the existing commit history?

Go for it 👍

**Comment by ojeytonwilliams** [comment]
@Sky020 I went through quite a number of iterations before I got here...

@raisedadead this should make translation a little easier.

**Comment by RandellDawson** [comment]
@ojeytonwilliams @raisedadead We should not merge this PR until we get most of the curriculum PRs merged or you will create a host of merge conflicts.  Quincy has asked @moT01 and I to focus on getting as many curriculum PRs (there are 77 of them currently) over the next 2-3 days, so once we do that, you should rerun whatever script you are using to change the extensions and force push to the branch before merging.  Also, by merging all the curriculum PRs we can, this will allow you to move up the timetable on moving to the new curriculum schema, which would for sure create massive merge conflicts for any outstanding curriculum PR.

**Comment by ojeytonwilliams** [comment]
The conflicts should be easy to resolve, because it's just a bunch of renames. Whenever you're ready to merge I'll rerun the script to minimise the conflicts.

**Comment by RandellDawson** [comment]
> The conflicts should be easy to resolve

True for this PR, but for the other open PRs like the Chinese translation ones that have 50+ files a piece, those would be a pain to fix.

**Pull request merged**
