### PR TITLE
feat(search): Add react-freecodecamp-search to Nav

### LINKED ISSUE #16166: [beta] Search Challenges in Map
- [ ] Add Search box on the map similar to previous version.
- [ ] Search should be fuzzy.
- [ ] Search should be available from all pages.

### PR DESCRIPTION
**Pull request by Bouncey**
#### Pre-Submission Checklist

- [x] Your pull request targets the `staging` branch of freeCodeCamp.
- [x] Branch starts with either `fix/`, `feature/`, or `translate/` (e.g. `fix/signin-issue`)
- [x] You have only one commit (if not, [squash](http://forum.freecodecamp.org/t/how-to-squash-multiple-commits-into-one-with-git/13231) them into one commit).
- [x] All new and existing tests pass the command `npm test`. Use `git commit --amend` to amend any fixes.

#### Type of Change

- [ ] Small bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds new functionality)
- [ ] Breaking change (fix or feature that would change existing functionality)
- [ ] Add new translation (feature adding new translations)

#### Checklist:

- [x] Tested changes locally.
- [x] Addressed currently open issue (replace XXXXX with an issue no in next line)

Closes #16166 
#### Description

Search all the things!

### CODE REVIEW

**Comment by QuincyLarson** [comment]
@Bouncey OK - I just tested this locally. It looks great. I have some feedback for how it can be even more intuitive:
1) Drop the description and just show the title - this will be less overwhelming.
2) Suppress stubs from search results. Clicking through to a stub will be a negative user experience.
3) Group similar types of results. For example, Have a single header "Lesson" with the titles below it, then "Blog Articles" or "Guide Articles" or "Videos"
4) Make the text area completely white (#ffffff) instead of gray so it matches the rest of our UI elements
5) Add an magnifying glass symbol inside the search box (font awesome should have a good one) and color it #006400

**Comment by Bouncey** [comment]
So drop the description in favour of an extract that shows the match?

**Comment by Bouncey** [comment]
Suppressing stubs will be at the elasticsearch end of the process

**Comment by QuincyLarson** [comment]
@Bouncey Yes - I think just showing say, the sentence that contains the match - would be fine. We can do this on the Search repo, but I think we can do these styling changes here on this PR first before we merge this.

**Comment by Bouncey** [comment]
Yes, I would need to update styles in the package, then update this PR with the next release

**Comment by QuincyLarson** [comment]
@Bouncey OK - I'm going to go ahead and merge this and we can open another PR to address it next.

**Comment by raisedadead** [comment]
@QuincyLarson @Bouncey Was this reverted? If so, was it handled by something else? In either case the linked issue should have been either re-opened or any other PR which handled this should have been linked.

**Comment by Bouncey** [comment]
@raisedadead I don't understand what you mean? I'm not aware of this being reverted.

**Comment by raisedadead** [comment]
See https://github.com/freeCodeCamp/freeCodeCamp/commit/8485041134aafa1f88259baf98e6f27c68fe0fd3

**Pull request merged**
