### PR TITLE
Fix description explaining hexadecimal numbers

### LINKED ISSUE #4589: Improve definition for "Decimal" in Waypoint: Use Hex Code for Specific Colors
Challenge [Waypoint: Use Hex Code for Specific Colors](http://www.freecodecamp.com/challenges/waypoint-use-hex-code-for-specific-colors) has an issue.

The definition for "Decimal" is . . . pretty bad.  The actual term should probably be "Base 10 Numbers".  Either way, the definition is clunky and needs a tune-up.

Current text:
>Decimal means the numbers zero through nine - the numbers that people use in everyday life. Hexadecimal includes these 10 numbers, plus the letters A, B, C, D, E and F. This means that Hexidecimal has a total of 16 possible values, instead of the 10 possible values that our normal base-10 number system gives us.

Maybe some improved verbiage and a "more info" link to discuss Base-16 numbering systems?

### PR DESCRIPTION
**Pull request by erictleung**
Closes #4589. 

I hope my explanation helps clear up what hexadecimal numbers are, albeit my explanation is a little bit longer. Also, I hope I've correctly coded and escaped the quotations in the link to hexadecimal numbers. I don't have everything set up yet to run a local instance of it to see for myself.

### CODE REVIEW

**Comment by SaintPeter** [comment]
I have confirmed that the formatting is correct and works on local.  I agree, this does go a bit long.  I think it's comprehensive, but I'd be interested in getting some other's opinions.  I'm flagging this for discussion.

**Comment by erictleung** [comment]
Thanks @SaintPeter! Sounds good. I'll try to keep up with the Q&A and make changes if needed.

**Comment by ltegman** [comment]
I personally like it. It feels slightly out of place when you start reading it but I thought it was a really good description that makes it so hexadecimal isn't some meaningless abstract concept like it is to so many programmers. Assuming you haven't thought of any suggested changes @SaintPeter I'd say you should merge this.

**Comment by SaintPeter** [comment]
Thanks @erictleung - I'm glad to see your regular contributions!

**Pull request merged**
