### PR TITLE
Add solution required

### PR DESCRIPTION
**Pull request by CleoAguiar**
01-responsive-web-design/applied-accessibility

- [ x] I have read [freeCodeCamp's contribution guidelines](https://github.com/freeCodeCamp/freeCodeCamp/blob/master/CONTRIBUTING.md).
- [x ] My pull request has a descriptive title (not a vague title like `Update index.md`)
- [ x] My pull request targets the `master` branch of freeCodeCamp.
- [ x] None of my changes are plagiarized from another source without proper attribution.
- [ x] All the files I changed are in the same world language (for example: only English changes, or only Chinese changes, etc.)
- [ x] My changes do not use shortened URLs or affiliate links.

Closes #XXXXX

### CODE REVIEW

**Comment by Ensive** [comment]
@CleoAguiar 
You might want do adjust your text in pull request description, put `x` into `[]` without spaces to get a checkbox.
If this PR doesn't close any particular issue, then feel free to remove "Closes #XXXXX" from the bottom of desc

**Comment by lynxlynxlynx** [comment]
LGTM. There are however 4 or 5 older PRs to the same file still being reviewed, so maybe the change will have been in vain.

**Comment by RandellDawson** [comment]
@lynxlynxlynx It is not in vain, because the other 6 earlier PRs do not add a solution.

**Comment by RandellDawson** [comment]
Congrats @CleoAguiar  on your first pull request (PR)! 🎉

Thank you for your contribution to the page! 👍
We're happy to accept these changes, and look forward to future contributions. 📝

**Pull request merged**
