### PR TITLE
fix: add backslash to path test for windows paths

### LINKED ISSUE #39451: `seed` script fails to run in Windows
**Describe the bug**

The `npm run seed` script used for seeding sample data to the DB fails to run. When the `seed` script is run (after following all the previous steps in the docs), this is the output -

```bash
npm run seed

> @freecodecamp/freecodecamp@0.0.1 seed D:\xampp\htdocs\gitcontributions\deep\freeCodeCamp
> npm-run-all -p seed:*


> @freecodecamp/freecodecamp@0.0.1 seed:auth-user D:\xampp\htdocs\gitcontributions\deep\freeCodeCamp
> cross-env DEBUG=fcc:* node ./tools/scripts/seed/seedAuthUser


> @freecodecamp/freecodecamp@0.0.1 seed:path-migration D:\xampp\htdocs\gitcontributions\deep\freeCodeCamp
> cross-env DEBUG=fcc:* node ./tools/scripts/seed/create-path-migration

(node:2848) DeprecationWarning: current Server Discovery and Monitoring engine is deprecated, and will be removed in a future version. To use the new Server Discover and Monitoring engine, pass option { useUnifiedTopology: true } to the MongoClient constructor.
  fcc:tools:seedLocalAuthUser Connected successfully to mongo +0ms
  fcc:tools:seedLocalAuthUser local auth user seed complete +17ms

```

Then, errors start to get logged for each individual markdown file  -

```bash

(node:6772) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, 
or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 3180)
(node:6772) UnhandledPromiseRejectionWarning: Error: Malformed challenge path, D:\xampp\htdocs\gitcontributions\deep\freeCodeCamp\curriculum\challenges\english\10-coding-interview-prep\project-euler\problem-467-superinteger.english.md unable to parse.
    at getEnglishPath (D:\xampp\htdocs\gitcontributions\deep\freeCodeCamp\curriculum\getChallenges.js:187:11)
    at createChallenge (D:\xampp\htdocs\gitcontributions\deep\freeCodeCamp\curriculum\getChallenges.js:134:29)
    at buildCurriculum (D:\xampp\htdocs\gitcontributions\deep\freeCodeCamp\curriculum\getChallenges.js:89:27)
    at EventEmitter.<anonymous> (D:\xampp\htdocs\gitcontributions\deep\freeCodeCamp\curriculum\getChallenges.js:47:9)
    at EventEmitter.emit (D:\xampp\htdocs\gitcontributions\deep\freeCodeCamp\curriculum\node_modules\eventemitter3\index.js:181:35)
    at Object.filter (D:\xampp\htdocs\gitcontributions\deep\freeCodeCamp\curriculum\node_modules\readdirp-walk\readdirp.js:72:15)
    at processFilter (D:\xampp\htdocs\gitcontributions\deep\freeCodeCamp\curriculum\node_modules\walk-filtered\index.js:23:91)
    at D:\xampp\htdocs\gitcontributions\deep\freeCodeCamp\curriculum\node_modules\walk-filtered\index.js:34:5
    at FSReqCallback.oncomplete (fs.js:169:5)
```

This looks like the DB is working fine cause it successfully seeds user data to the DB.

image

**To Reproduce**
1. Clone forked repo on Windows
2. Run `cp sample.env .env`
3. Run `npm ci`
4. Run `npm run seed`
5. See error

**Expected behavior**

Expected to seed data to the DB. (It seeded data previously to my DB but I recently re-installed Windows so I have a fresh DB installed)

**Desktop (please complete the following information):**
 - OS: Windows 10 (v2004) (64 Bit)
 - Node Version: v12.18.3

**Additional context**

I have previously ran fCC locally (last ran it 3 weeks ago) but can't run it now after a clean install of Windows because seeding fails.

### PR DESCRIPTION
**Pull request by ShaunSHamilton**
Checklist:

- [x] I have read [freeCodeCamp's contribution guidelines](https://contribute.freecodecamp.org).
- [x] My pull request has a descriptive title (not a vague title like `Update index.md`)
- [x] My pull request targets the `master` branch of freeCodeCamp.
- [x] All the files I changed are in the same world language, for example: only English changes, or only Chinese changes, etc.

Closes #39451 

Tested on Windows 10, and WSL: Ubuntu 20.04 -  allows both file paths to be tested.

### CODE REVIEW

**Review by ojeytonwilliams — APPROVED** [review]
LGTM :+1: 

I'd like to wait until https://github.com/freeCodeCamp/freeCodeCamp/pull/39456 is in, if that's okay.  That way we can be more confident our CI works.

**Comment by ojeytonwilliams** [comment]
Actually, I've changed my mind - delaying this to use it for testing was a silly idea.  @Twaha-Rahman @RandellDawson would one of you mind QAing this and we can merge as soon as you're happy?

**Comment by RandellDawson** [comment]
@ojeytonwilliams I am currently unable to test this on Windows, but it should work as written.  Feel free to merge if @Twaha-Rahman is able to test and validate the change does work on Windows.

**Comment by Twaha-Rahman** [comment]
I have been using this PR for a few days and it works flawlessly.

**Comment by RandellDawson** [comment]
@Twaha-Rahman So maybe I should cherry-pick the commits off this PR and apply them to a new branch off my local master to see if the `npm run develop` issue goes away?

**Review by RandellDawson — APPROVED** [review]
I can now validate this fixes the bug when running on Windows.

**Comment by RandellDawson** [comment]
Thank you for your contribution to the page! 👍
We're happy to accept these changes, and look forward to future contributions. 🎉

**Pull request merged**
