### PR TITLE
fix(donate): implement donation settings page

### PR DESCRIPTION
**Pull request by raisedadead**

### CODE REVIEW

**Comment by ahmadabdolsaheb** [comment]
made a donation from year end gift page.
had to refresh the donation settings page to see the new email. 
when clicked on the new email I saw the following. is it expected?

image

**Comment by raisedadead** [comment]
> had to refresh the donation settings page to see the new email.

The refresh required is because the state management is never in sync with the application. The donation setting do not use any state management from what I believe. I am not an expert, please feel free to track in a fresh issue and make a fix.

> when clicked on the new email I saw the following. is it expected?

We need to track all donations, year-end donations are one-time donations. This will be helpful in making the motivational prompts that you will be working on based on the donation data.

The email will be shown in the settings page, they will also have a isDonating status.

The embed is what it ships with servicebot. In this case, they see a pricing plan because:

1. The do not have a recurring donation plan setup.
2. Their most current transaction is a one off donation and servicebot is picking it up instead of their subscription. In either case, this is an issue with the servicebot feature and needs to be taken up with them.

I do not see a way to not have it in the current configuration that they give us.

**Comment by raisedadead** [comment]
The only way I think we can make sure that this page is not confusing to the one-time donations is by auditing the db and adding one more key for one-time donors, and not showing them this page.

**Comment by ahmadabdolsaheb** [comment]
> The only way I think we can make sure that this page is not confusing to the one-time donations is by auditing the db and adding one more key for one-time donors, and not showing them this page.

If the aim is to increase the conversion rate to monthly donors, there should be way to distinguish between monthly and one-time donors. That way we could still display the donation modals in a way.

**Comment by ahmadabdolsaheb** [comment]
Other than that this LGMT.

**Comment by raisedadead** [comment]
Depends on https://github.com/freeCodeCamp/freeCodeCamp/issues/37784

**Pull request closed without merging**
