### PR TITLE
fix: remove unused polyvinyl functions

### PR DESCRIPTION
**Pull request by ojeytonwilliams**
Checklist:

- [x] I have read [freeCodeCamp's contribution guidelines](https://contribute.freecodecamp.org).
- [x] My pull request has a descriptive title (not a vague title like `Update index.md`)
- [x] My pull request targets the `main` branch of freeCodeCamp.
- [x] I have tested these changes either locally on my machine, or GitPod.

As far as I can see, these were in the original vinyl which ours was based off, but we don't use them.

### CODE REVIEW

**Comment by ojeytonwilliams** [comment]
@ahmadabdolsaheb this alone reduces the raw bundle size from 4.09mb to 3.79mb.

before

image

and after

image

rxjs is highlighted

**Comment by ojeytonwilliams** [comment]
As a general note, we were looking to remove/reduce the amount of rxjs in the client because it's a large library.  The reason this took longer to find than it should have is kind of silly - it wasn't in the client directory or in an npm package we've installed.

I still think it's sensible to keep common packages separate from their dependants, but we (or at least I) need to keep this in mind in future.

**Review by raisedadead — DISMISSED** [review]

**Review by ShaunSHamilton — CHANGES_REQUESTED** [review]
`isEmpty` is not used in the codebase. Other than that, this LGTM 👍

**Review by ShaunSHamilton — APPROVED** [review]
This LGTM 👍

**Review by raisedadead — APPROVED** [review]

**Pull request merged**
