### PR TITLE
fix: removed bug in front end library random quote project

### LINKED ISSUE #35459: No line breaks in quote machine description
I'm not sure what happened to the instructions of [this project](https://www.freecodecamp.rocks/learn/front-end-libraries/front-end-libraries-projects/build-a-random-quote-machine), but there aren't any line breaks between the user stories. None of the other front end projects have this problem, but I didn't check any of the other areas.

screen shot 2019-02-25 at 8 03 27 pm

### PR DESCRIPTION
**Pull request by shashank-bairy**
- [x] I have read [freeCodeCamp's contribution guidelines](https://github.com/freeCodeCamp/freeCodeCamp/blob/master/CONTRIBUTING.md).
- [x] My pull request has a descriptive title (not a vague title like `Update index.md`)
- [x] My pull request targets the `master` branch of freeCodeCamp.
- [x] None of my changes are plagiarized from another source without proper attribution.
- [x] All the files I changed are in the same world language (for example: only English changes, or only Chinese changes, etc.)
- [x] My changes do not use shortened URLs or affiliate links.

Closes #35459
Removed the unwanted <codea</code> tag in line #17 which was causing the issue #35459 .

### CODE REVIEW

**Comment by RandellDawson** [comment]
@BA1RY You were not supposed to delete the code, but instead change it to what I said.  See [comment in issue](https://github.com/freeCodeCamp/freeCodeCamp/issues/35459#issuecomment-468376045).

**Comment by BA1RY** [comment]
Sorry about that. Seeing the code in the above lines, i assumed that it is to be removed. My bad. Will do as you say.

**Comment by RandellDawson** [comment]
Closing this one in favor of your other PR #35462.  In the future, just make new commits to the same PR instead of creating a new one.

**Comment by BA1RY** [comment]
Sure. Didn't know I could do that. Thanks for the input.

**Pull request closed without merging**
