### PR TITLE
Update find-one-or-more-criminals-in-a-hunt.portuguese.md to improve readability

### PR DESCRIPTION
**Pull request by Peres22Kbron**
- [X] I have read [freeCodeCamp's contribution guidelines](https://github.com/freeCodeCamp/freeCodeCamp/blob/master/CONTRIBUTING.md).
- [X] My pull request has a descriptive title (not a vague title like `Update index.md`)
- [X] My pull request targets the `master` branch of freeCodeCamp.
- [X] None of my changes are plagiarized from another source without proper attribution.
- [X] My article does not contain shortened URLs or affiliate links.

If your pull request closes a GitHub issue, replace the XXXXX below with the issue number.

Closes #XXXXX

### CODE REVIEW

**Comment by Peres22Kbron** [comment]
Is there anything I can do on my end to resolve the issue above?

**Review by ezioda004 — COMMENTED** [review]
@Peres22Kbron 
I've restarted the build. Hopefully, that'll fix it.

**Comment by RandellDawson** [comment]
Closed and Reopened this PR to attempt to resolve a specific Travis build failure.

**Review by RandellDawson — APPROVED** [review]
LGTM

**Comment by RandellDawson** [comment]
Thank you for your contribution to the page! 👍
We're happy to accept these changes, and look forward to future contributions. 🎉

**Comment by RandellDawson** [comment]
@captaintrips1969 Please refrain from making random comments on our repo that do not add any value to the issue or PR. Thank you.

**Pull request merged**
