### PR TITLE
Responsive Web Design: Added hint to Change a Variable for a Specific…

### PR DESCRIPTION
**Pull request by greggubarev**
… Area

Added hint to Change a Variable for a Specific Area (https://guide.freecodecamp.org/certifications/responsive-web-design/basic-css/change-a-variable-for-a-specific-area)

- [x] I have read [freeCodeCamp's contribution guidelines](https://github.com/freeCodeCamp/freeCodeCamp/blob/master/CONTRIBUTING.md).
- [x] My pull request has a descriptive title (not a vague title like `Update index.md`)
- [x] My pull request targets the `master` branch of freeCodeCamp.
- [x] None of my changes are plagiarized from another source without proper attribution.
- [x] My article does not contain shortened URLs or affiliate links.

If your pull request closes a GitHub issue, replace the XXXXX below with the issue number.

Closes #XXXXX

### CODE REVIEW

**Comment by scissorsneedfoodtoo** [comment]
Sorry, but this doesn't seem to be the correct solution for this challenge. It should be: 

```css
  .penguin {
    --penguin-belly: white;
    position: relative;
    margin: auto;
    display: block;
    margin-top: 5%;
    width: 300px;
    height: 300px;
  }
```

Also, please don't take text from other articles and repeat them in yours. You could put a link to the relevant article instead.

**Comment by greggubarev** [comment]
@scissorsneedfoodtoo sorry - my bad, added wrong solution, now correct.

> Also, please don't take text from other articles and repeat them in yours. You could put a link to the relevant article instead.

I did not quite understand what kind of text - which one is at the beginning? I added links to articles. Need to delete text? It just seemed important to me to communicate this information at the beginning.

**Comment by scissorsneedfoodtoo** [comment]
@greggubarev, great! Thanks for changing the solution so quickly.

It's my understanding that we shouldn't take text from another Guide article, no matter how appropriate, and include them in your own article. I could be completely wrong about this, though. So while the information from the CSS Variables article works well here, I'm not sure if it's okay to repeat it here. What do you think, @raisedadead?

**Comment by moT01** [comment]
Looks good @greggubarev, thank you for contributing!

**Pull request merged**
