### PR TITLE
Fix broken link to Introducing JavaScript Object Notation (JSON)

### LINKED ISSUE #9325: Link broken to Introducing JavaScript Object Notation (JSON)
Challenge [Record Collection](https://www.freecodecamp.com/challenges/record-collection) has an issue.
User Agent is: <code>Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Ubuntu Chromium/50.0.2661.102 Chrome/50.0.2661.102 Safari/537.36</code>.
Please describe how to reproduce this issue, and include links to screenshots if possible.

My code:
```javascript

// Setup
var collection = {
    "2548": {
      "album": "Slippery When Wet",
      "artist": "Bon Jovi",
      tracks: [ 
        "Let It Rock", 
        "You Give Love a Bad Name" 
      ]
    },
    "2468": {
      "album": "1999",
      "artist": "Prince",
      "tracks": [ 
        "1999", 
        "Little Red Corvette" 
      ]
    },
    "1245": {
      "artist": "Robert Palmer",
      "tracks": [ ]
    },
    "5439": {
      "album": "ABBA Gold"
    }
};
// Keep a copy of the collection for tests
var collectionCopy = JSON.parse(JSON.stringify(collection));

// Only change code below this line
function updateRecords(id, prop, value) {

  if (prop == "tracks")

  return collection;
}

// Alter values below to test your code
updateRecords(5439, "artist", "ABBA");


```

### PR DESCRIPTION
**Pull request by qdr**
#### Pre-Submission Checklist

- [x] Your pull request targets the `staging` branch of FreeCodeCamp.
- [ ] Branch starts with either `fix/`, `feature/`, or `translate/` (e.g. `fix/signin-issue`)
- [ ] You have only one commit (if not, [squash](https://github.com/FreeCodeCamp/FreeCodeCamp/wiki/git-rebase#squashing-multiple-commits-into-one) them into one commit).
- [ ] All new and existing tests pass the command `npm run test-challenges`. Use `git commit --amend` to amend any fixes.
#### Type of Change

- [x] Small bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds new functionality)
- [ ] Breaking change (fix or feature that would change existing functionality)
- [ ] Add new translation (feature adding new translations)
#### Checklist:

- [ ] Tested changes locally.
- [x] Closes currently open issue (replace XXXX with an issue no): Closes #9325
#### Description

added the right link; as proposed by Jonathan "notifications@github.com"

https://www.freecodecamp.com/challenges/manipulating-complex-objects

### CODE REVIEW

**Comment by atjonathan** [comment]
@qdr,

> You can change the anchor tag from:
<a href=\"https://www.freecodecamp.com/challenges/**challenge-name**\">**Challenge Name**</a>
to
<a href=\"**challenge-name**\">**Challenge Name**</a>

**Comment by atjonathan** [comment]
@qdr :joy:, I didn't literally mean `<a href=\"**challenge-name**\">**Challenge Name**</a>`, change that to `<a href=\"manipulating-complex-objects\">Manipulating Complex Objects</a>`

**Comment by Bouncey** [comment]
@qdr Please [squash](https://github.com/FreeCodeCamp/FreeCodeCamp/wiki/Git-Squash) your commits into 1

Other than that:

## **LGTM**

**Comment by qdr** [comment]
hi Stuart,

iam sorry,,; to noob for a squashing exercise with git console etc... can
you perhaps take over?

Thanks for your kind help!,
greetings,
D

2016-06-24 0:59 GMT+02:00 Stuart Taylor <notifications@github.com>:

**Comment by raisedadead** [comment]
Tested locally.

#### :sparkles: :sparkles: **LGTM.** :sparkles: :sparkles: 

Thanks for the PR and congratulations on your first contribution.

**Pull request merged**
