### PR TITLE
Add translation to Spanish of basic-bonfires intermediate-bonfires (partial) upper-intermediate-bonfires and advanced-bonfires 

### PR DESCRIPTION
**Pull request by justinian336**
This is a partial translation of the bonfires to Spanish. Most of the
translations of technical terms are taken from
https://developer.mozilla.org/es/docs/Web/JavaScript/Guide

### CODE REVIEW

**Comment by luishendrix92** [comment]
A mí me gusta más la palabra "arreglo", fuera de tecnicismos a la mayoría de los hispanohablantes que programan, novatos o expertos, les he oído decir "arreglo" o "array".

Vector me viene más a la cabeza con la clase std::vector de C++

**Comment by justinian336** [comment]
¡Hola @edgarshurtado, mil gracias por tus comentarios! I will revise my translation taking into account your comments, which seem very accurate. In the case of the word arreglo, I agree with luishendrix92, I've found the word arreglo in many programming websites in Spanish, but I guess we can discuss that with the other translators in the chatroom:

https://gitter.im/AlexTrapp/FreeCodeCampEspañol

By the way, I don't know if I should make the corrections and send another pull request with the corrections, or reverting this one (newbie here).

**Comment by ltegman** [comment]
Normally I would recommend doing:
```
git add .
git commit --amend
git push -f
```
to amend and force push, but since your branch naming doesn't match the guidelines in [Pull Request Contribute](https://github.com/FreeCodeCamp/FreeCodeCamp/wiki/Pull-Request-Contribute) perhaps a new PR from a more informatively named branch would be in order. Really appreciate all the work you're putting into this!

**Comment by justinian336** [comment]
Thanks for the help! I was not aware of the guidelines for naming he PRs. I will make a new one with a better name including the corrections so far.

**Pull request closed without merging**
