### PR TITLE
Brazilian Portuguese translation of Basic Algorithm Scripting

### PR DESCRIPTION
**Pull request by nmdoliveira**
#### Pre-Submission Checklist

- [x] Your pull request targets the `staging` branch of freeCodeCamp.
- [x] Branch starts with either `fix/`, `feature/`, or `translate/` (e.g. `fix/signin-issue`)
- [x] You have only one commit (if not, [squash](http://forum.freecodecamp.com/t/how-to-squash-multiple-commits-into-one-with-git/13231) them into one commit).
- [x] All new and existing tests pass the command `npm test`. Use `git commit --amend` to amend any fixes.

#### Type of Change

- [ ] Small bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds new functionality)
- [ ] Breaking change (fix or feature that would change existing functionality)
- [x] Add new translation (feature adding new translations)

#### Checklist:

- [x] Tested changes locally.
- [ ] Closes currently open issue (replace XXXX with an issue no): Closes #XXXX

#### Description

Reference issue: https://github.com/freeCodeCamp/TranslationExpansion/issues/51

### CODE REVIEW

**Comment by raisedadead** [comment]
Thanks @nmdoliveira for the pull request and translating these challenges. 
Can you try and find someone for a peer review?

Do not worry if you can't. We will wait for a week before merging this PR anyways.

**Comment by nmdoliveira** [comment]
Thanks @raisedadead, I will try to find someone

**Review by Met4tron — APPROVED** [review]
It's great and with an easy understanding for us Brazilians!

**Comment by raisedadead** [comment]
@Met4tron Thanks for the review.

**Review by raisedadead — APPROVED** [review]
#### :sparkles: :sparkles: **LGTM.** :sparkles: :sparkles: 

Thanks @nmdoliveira for the contribution and the hard work!

And Congratulations for your first contribution to freeCodeCamp!

**Comment by nmdoliveira** [comment]
Thanks @Met4tron, @raisedadead :blush:

**Comment by julianorafael** [comment]
Hmm, some of the titles where converted to all lower case. The titles in english are all title case. Is there a reason for the transition?

**Comment by nmdoliveira** [comment]
I tried to keep the titles consistent with only the first word and proper nouns capitalized (except in the "title case" challenge, for demonstration purposes). This is an option that was introduced in the new orthographic agreement to avoid the confusion about what words should or shouldn't be capitalized in titles (more [here](http://www.linguabrasil.com.br/nao-tropece-detail.php?id=417)).

About strings and arrays, I kept them because I think they are more commonly used than they translated versions, same for "loop" and others (I'm using this [glossary](https://docs.google.com/spreadsheets/d/1OFgZp66oopOLeUCN_4_WsQOmt7daon1NdWHpl51iOvQ/edit#gid=0)).

**Comment by julianorafael** [comment]
Fair point. I'm not a translator or anything, but I wanted to headstart this since nothing was happening. I'm finishing a big one this month and I'd love you review on that, @nmdoliveira. I appreciate the corrections and I'll follow the glossary from now on. I didn't there was one.

**Comment by nmdoliveira** [comment]
I'll happy to review your translation!

I was actually a little confused when I started translating and saw that most of it was already translated haha
But since some challenges were missing, I ended up reviewing everything. But your translation made it very easy for me haha :smile: 

I created this glossary myself (because I didn't find one) so feel free to suggest changes!

**Pull request merged**
