### PR TITLE
Feat: multifile multiple editors

### PR DESCRIPTION
**Pull request by ojeytonwilliams**
The last commit was cherry-picked from master, because I realised the output was not working correctly.  If it's too far out of scope, I can pop that in another PR.

Again, there's a debug commit to facilitate testing (I've blocked it to remind myself to remove that after QA).  This time there are three challenges, starting with Create an Ordered List, so you can see how moving between challenges and the 'target editor' work.

### CODE REVIEW

**Comment by RandellDawson** [comment]
@ojeytonwilliams Just tested this out and seems to accomplish highlighting the "file" with the Run the Tests button on page load and reload regardless of which tabs were clicked "on" or not.  I guess the only thing I would like to see is a way to make it clear which tab to go back to (to see the Run the Tests button) if you have clicked on another tab or turned off the tab where the Run the Tests button resides.  Otherwise, a user might get a bit confused  (having to click multiple tabs) to find their way back to the file they really should be working on.

**Comment by ojeytonwilliams** [comment]
I think we discussed this feature and, yes, that would definitely be useful.

**Comment by ahmadabdolsaheb** [comment]
There is a minor issue with resizing the editors, but we could merge this and iterate on it.

**Comment by ahmadabdolsaheb** [comment]
Great job, @ojeytonwilliams.

**Pull request merged**
