### PR TITLE
Fix Get Geolocation Data - jQuery Selector

### LINKED ISSUE #9303: Get Geolocation Data: jQuery selector with single quote won't pass
Challenge [Get Geolocation Data](https://www.freecodecamp.com/challenges/get-geolocation-data#?solution=%0Afccss%0A%20%20%2F%2F%20Only%20change%20code%20below%20this%20line.%0Aif%20(navigator.geolocation)%20%7B%0A%20%20navigator.geolocation.getCurrentPosition(function(position)%20%7B%0A%20%20%20%20%24(%22%23data%22).html(%22latitude%3A%20%22%20%2B%20position.coords.latitude%20%2B%20%22%3Cbr%3Elongitude%3A%20%22%20%2B%20position.coords.longitude)%3B%0A%20%20%7D)%3B%0A%7D%0A%0A%20%20%2F%2F%20Only%20change%20code%20above%20this%20line.%0Afcces%0A%3Cdiv%20id%20%3D%20%22data%22%3E%0A%20%20%3Ch4%3EYou%20are%20here%3A%3C%2Fh4%3E%0A%20%20%0A%3C%2Fdiv%3E%0A) has an issue.
User Agent is: <code>Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/51.0.2704.103 Safari/537.36</code>.
Please describe how to reproduce this issue, and include links to screenshots if possible.

My code:
```html

<script>
  // Only change code below this line.
if (navigator.geolocation) {
  navigator.geolocation.getCurrentPosition(function(position) {
    $('#data').html("latitude: " + position.coords.latitude + "<br>longitude: " + position.coords.longitude);
  });
}

  // Only change code above this line.
</script>
<div id = "data">
  <h4>You are here:</h4>
  
</div>

```

The code is 99% similar with the given example code, except the single quote of jQuery selector.

If I change `$('#data')` to `$("#data")`, the last test case **You should display the users' position within the data div element** can be passed.

Single quote for `string` can be passed, this seems only happen for jQuery selectors.

### PR DESCRIPTION
**Pull request by sthodup1**
#### Pre-Submission Checklist

- [x] Your pull request targets the `staging` branch of FreeCodeCamp.
- [x] Branch starts with either `fix/`, `feature/`, or `translate/` (e.g. `fix/signin-issue`)
- [x] You have only one commit (if not, [squash](https://github.com/FreeCodeCamp/FreeCodeCamp/wiki/git-rebase#squashing-multiple-commits-into-one) them into one commit).
- [x] All new and existing tests pass the command `npm run test-challenges`. Use `git commit --amend` to amend any fixes.
#### Type of Change

- [x] Small bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds new functionality)
- [ ] Breaking change (fix or feature that would change existing functionality)
- [ ] Add new translation (feature adding new translations)
#### Checklist:

- [x] Tested changes locally.
- [x] Closes currently open issue (replace XXXX with an issue no): Closes #9303 
#### Description

Added instructions to use double quotes on jQuery selectors since this is stylistically preferred and FreeCodeCamp's tests don't seem to support double-quote selectors. This change will clarify this issue for learners.

### CODE REVIEW

**Comment by raisedadead** [comment]
@sthodup1 

We have repeated this multiple times and the check list as well says the same, kindly make sure that you test all the changes locally.

`npm run test-challenges`

Please go though the [Guidelines for Contributing](https://github.com/FreeCodeCamp/FreeCodeCamp/blob/staging/CONTRIBUTING.md).

**Comment by sthodup1** [comment]
@raisedadead I actually did run the tests locally this time. I'm not sure why it failed. I'll try again. Sorry for the trouble

**Comment by raisedadead** [comment]
@sthodup1 no issues, please take your time, :sweat_smile:

I am guessing the escaping in the quotes is the point of trouble.

**Comment by atjonathan** [comment]
### **LGTM :+1:**

**Comment by raisedadead** [comment]
@sthodup1 This is weird the PR has made a change to a challenge other than that is mentioned in the original issue.

Are you sure you have tested this locally by actually running the server?

**Comment by sthodup1** [comment]
@raisedadead the issue in the challenge was caused by lack of clarity on single quote usage in selectors in the challenge I modified.  

I've tested it with npm test challenges command. I'm not sure how to actually run the server to test but I'll look into it

**Comment by raisedadead** [comment]
@sthodup1 please re-visit the [Guidelines for Contributing](https://github.com/FreeCodeCamp/FreeCodeCamp/blob/staging/CONTRIBUTING.md). Its all in there.

**Comment by sthodup1** [comment]
@raisedadead Found it! I'll check on the local copy and make any changes as necessary by the end of the day.

**Comment by sthodup1** [comment]
@raisedadead I've tested it on the local copy and it looks good to me

**Comment by raisedadead** [comment]
@sthodup1 

> the PR has made a change to a challenge other than that is mentioned in the original issue.

weren't we adding this to `Get Geolocation Data` challenge and not  `Target HTML Elements with Selectors Using jQuery`

**Comment by sthodup1** [comment]
@raisedadead The poster of the original issue had a problem completing the Get Geolocation Data challenge. However, the cause of the problem was that the poster attempted to use single quotes in a jQuery selector. Using single quotes for selectors could also cause other challenges to fail, and does not follow jQuery style practices. That's why I changed the Target HTML Elements with Selectors Using jQuery challenge. This is the earliest challenge that uses selectors, and it would be the best to tell people to use double quotes here.

**Comment by raisedadead** [comment]
@sthodup1 Can we link this in the Geo Location Challenge in that case?

**Comment by sthodup1** [comment]
@raisedadead I added a link to this change in the Get Geolocation Data challenge. (after some difficulties with git if you can't tell by the number of updates to the PR)

**Comment by raisedadead** [comment]
@sthodup1 thanks a lot for the hard work and time you have invested on this. Will QA and merge soon.

**Comment by Mongues** [comment]
Geico ding is some awesome stuff man but how much good will Google's serves
be in the wake of Microsoft?
On Jun 27, 2016 12:24 PM, "Mrugesh Mohapatra" <notifications@github.com>
wrote:

@sthodup1 <https://github.com/sthodup1> This is weird the PR has made a
change to a challenge other than that is mentioned in the original issue.

Are you sure you have tested this locally by actually running the server?

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub
<https://github.com/FreeCodeCamp/FreeCodeCamp/pull/9391#issuecomment-228813698>,
or mute the thread
<https://github.com/notifications/unsubscribe/AJwcfXJQ6ZBjFHnSaC9ryNurnPWrd5TNks5qQAdBgaJpZM4I-mAe>
.

**Comment by raisedadead** [comment]
#### :sparkles: :sparkles: **LGTM.** :sparkles: :sparkles: 

Thanks.

**Pull request merged**
