### PR TITLE
fix: unneeded scrollbar multi file editor

### PR DESCRIPTION
**Pull request by Sembauke**
Checklist:

- [x] I have read [freeCodeCamp's contribution guidelines](https://contribute.freecodecamp.org).
- [x] My pull request has a descriptive title (not a vague title like `Update index.md`)
- [x] My pull request targets the `main` branch of freeCodeCamp.
- [x] I have tested these changes either locally on my machine, or GitPod.

Ref #39348

For clarification on how to reproduce this issue, 

When viewing the multi-file editor on the Cafe Menu project somewhere around part 60 you should have 2 separate files.
`style.css` and the `index.html` file. While minimizing `index.html` and the project preview pane you should see a scrollbar on the left of your screen (This scrollbar may appear also when other panes are active).

**What caused the bug?**
The bug was caused by the bar above (header) not being included in a `reflexcontainer` . This made the page have unexpected behavior. 
image

**Note:** This fixes number 6 on Randell's list.
This also seems to fix number 7:  When using the Esc hotkey, the page shifts down just slightly, which makes it difficult to click on the tabs (i.e. index.html. styles.css, etc.). (But I am not sure)

### CODE REVIEW

**Comment by ojeytonwilliams** [comment]
Hey @Sembauke, I'm just taking a look at this now.  Would you mind fixing the conflict?

**Review by ojeytonwilliams — CHANGES_REQUESTED** [review]
Nice job, Sem.  There aren't any scrollbars lurking around any more.

I did notice that a small gap has appeared at the top of the editor
image

Could you investigate what's causing this?

**Comment by Sembauke** [comment]
> Nice job, Sem. There aren't any scrollbars lurking around any more.
> 
> I did notice that a small gap has appeared at the top of the editor
> image
> 
> Could you investigate what's causing this?

Good eyes you have Oliver!

**Comment by Sembauke** [comment]
Everything should be good to go

**Review by naomi-lgbt — APPROVED** [review]
This is looking good to me. I'm not able to reproduce the error now, and the gap @ojeytonwilliams noticed seems to be fixed.

**Review by ojeytonwilliams — APPROVED** [review]
LGTM :+1:

Apologies for the delay reviewing and thanks again for all your amazing work :rocket:

**Pull request merged**
