### PR TITLE
fix/unclear-statements

### LINKED ISSUE #7125: Filter Arrays with filter conflicting statements in instructions and test
Challenge [Filter Arrays with filter](http://www.freecodecamp.com/challenges/filter-arrays-with-filter#?solution=var%20oldArray%20%3D%20%5B1%2C2%2C3%2C4%2C5%2C6%2C7%2C8%2C9%2C10%5D%3B%0A%0A%2F%2F%20Only%20change%20code%20below%20this%20line.%0A%0Avar%20newArray%20%3D%20oldArray.filter(function(val)%7B%0A%20%20return%20val%20%3C%206%3B%0A%7D)%3B%0A) has an issue.
User Agent is: <code>Mozilla/5.0 (Macintosh; Intel Mac OS X 10_11_2) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/48.0.2564.109 Safari/537.36</code>.
Please describe how to reproduce this issue, and include links to screenshots if possible.

screen shot 2016-02-18 at 8 30 22 pm 2

Conflicting statements instructions say 

Use filter to create a new array with all the values from oldArray which are less than 6.
oldArray should not change.

Test say 
You should have filtered out all values from the array that are greater than 5.

My code:
```javascript
var oldArray = [1,2,3,4,5,6,7,8,9,10];

// Only change code below this line.

var newArray = oldArray.filter(function(val){
  return val < 6;
});

```

### PR DESCRIPTION
**Pull request by kirbyblox**
closes #7125

### CODE REVIEW

**Comment by bugron** [comment]
Rename the title to be descriptive to your changes.

**Comment by bugron** [comment]
Note that https://github.com/FreeCodeCamp/FreeCodeCamp/pull/7152 follows guidelines so you may want to close this one.

**Comment by JoshFisk** [comment]
@bugron I just wanted to say I am not associated with @kirbyblox, and do not know why he copied my closed commit.

**Comment by bugron** [comment]
Hmm. Well then, closing this PR in favor of https://github.com/FreeCodeCamp/FreeCodeCamp/pull/7152.

**Pull request closed without merging**
