### PR TITLE
Replace iPhone image with pure CSS version

### PR DESCRIPTION
**Pull request by ahstro**
This replaces the iPhone image used to frame the content in the HTML/CSS/jQuery challenges with an iPhone frame created in pure CSS. The CSS was generated by [Pure CSS Apple](http://purecssapple.com)

This is the result of a discussion in #1737, and using a pure CSS solution was requested by @BerkeleyTrue, so I'll leave it up to him to figure out whether using Ömer's generated code is legal or not.

The solution feels a bit hacky imo (less hacky than the previous one, since I got to remove some code, but hacky nonetheless.) I would've preferred to put the iframe inside the `.pca-inner` and let it size itself, but that made it impossible to use the `.hidden-xs` and `.hidden-sm` classes on `.pca-hold` without also hiding the iframe on small screens.

Also, here's a screenshot, because screenshots are fun:

P.S. I've tested this in the latest versions of Firefox and Chromium, but I'd appreciate if someone else got a local copy running and played around a bit as well. My laptop screen is 1366x768 and I'm not at home, so I haven't been able to check any resolutions above that.

### CODE REVIEW

**Comment by BerkeleyTrue** [comment]
Nice! @ahstro Thanks a lot. I'll be QA it in a bit. Hmm... I thought it was MIT license... I can't seem to find his license anywhere.

**Comment by ahstro** [comment]
No problem :) Yeah, it feels weird to have a site like that and not have a permissive license. Might have to contact him directly though.

**Comment by QuincyLarson** [comment]
Hi @ahstro I am closing this as well as the issue. Berkeley and I discussed this and we feel the small image looks better than a pure CSS solution.

**Comment by ahstro** [comment]
Shame to hear, I felt like the CSS version mixed better with the rest of the layout. Updating it to the iPhone 6 would've been trivial.

**Comment by garyc60674** [comment]
Why are yall messing with my phone?  My life is jacked up all to shit as it
is. Please stop.

**Pull request closed without merging**
