### PR TITLE
Fixing some Spanish translations

### PR DESCRIPTION
**Pull request by Maluzzz**
- [x] I have read [freeCodeCamp's contribution guidelines](https://github.com/freeCodeCamp/freeCodeCamp/blob/master/CONTRIBUTING.md).
- [x] My pull request has a descriptive title (not a vague title like `Update index.md`)
- [x] My pull request targets the `master` branch of freeCodeCamp.
- [x] None of my changes are plagiarized from another source without proper attribution.
- [x] My article does not contain shortened URLs or affiliate links.

I've changed a translation in spanish that's not correct.
The word "well" doesn't sound good like "pozo" a better translation would be "caja"

### CODE REVIEW

**Comment by tchaffee** [comment]
@Maluzzz someone else merged another PR before yours and now there are merge conflicts. Could you please fix the merge conflicts?

**Comment by scissorsneedfoodtoo** [comment]
@Maluzzz, I hope you don't mind, but I tried to solve as many of your merge conflicts as possible. As @tchaffee mentioned, there were other PRs merged before yours, along with the directory/file locations being moved around that caused the conflicts. I tried to preserve as many of your updated translations as possible, but there were a couple of cases where someone else updated the same paragraph. In those cases I went with their translation since it was merged first.

Would you mind taking a look at the files changed [here](https://github.com/freeCodeCamp/freeCodeCamp/pull/18866/files) to see if I got everything? And please feel free to make more changes to the translation if you think it's necessary.

**Comment by Maluzzz** [comment]
I think it's ok thanks for your help :D

**Comment by scissorsneedfoodtoo** [comment]
:sparkles: :sparkles: :sparkles: Awesome! Congratulations on your first contribution to freeCodeCamp! :sparkles: :sparkles: :sparkles:

Thank you for helping us improve all of these articles and challenges, @Maluzzz. We're all really looking forward to your next contribution :+1: :+1:

**Pull request merged**
