### PR TITLE
Wrong punctuation sign

### PR DESCRIPTION
**Pull request by MyOctagon**
This isn't  a question but a question mark sign(?) was used by mistake which I replaced with  a full stop (.)

Checklist:

- [ x] I have read [freeCodeCamp's contribution guidelines](https://contribute.freecodecamp.org).
- [x ] My pull request has a descriptive title (not a vague title like `Update index.md`)
- [ x] My pull request targets the `main` branch of freeCodeCamp.
- [ x] All the files I changed are in the same world language, for example: only English changes, or only Chinese changes, etc.

Closes #XXXXX

### CODE REVIEW

**Comment by RandellDawson** [comment]
I believe the intent and the way it is worded, it is a question.

**Comment by MyOctagon** [comment]
It was just my personal opinion, I might  be wrong. I apologize for my
wrong proposal.

**Comment by RandellDawson** [comment]
Not necessarily saying your wrong.  We may need to restructure the sentence if we do not want a question or if we want a question, make it more clear?

**Comment by MyOctagon** [comment]
Now that I rethought the sentence, I think  its alright, At first sight I
thought it was instructing me to see how the form notifies me,  But now I
get it,  it's just asking me if I saw how the form notifies me.
Hope I'm clear enough.

**Pull request closed without merging**
