### PR TITLE
fix: first mongo challenge description

### PR DESCRIPTION
**Pull request by moT01**
Checklist:

- [x] I have read [freeCodeCamp's contribution guidelines](https://contribute.freecodecamp.org).
- [x] My pull request has a descriptive title (not a vague title like `Update index.md`)
- [x] My pull request targets the `main` branch of freeCodeCamp.
- [ ] I have tested these changes either locally on my machine, or GitPod.

Closes #XXXXX

Related to https://github.com/freeCodeCamp/freeCodeCamp/issues/46885

Cannot be merged until the boilerplate PR is ready.
The boilerplate PR should be merged when this gets deployed.

### CODE REVIEW

**Review by lasjorg — APPROVED** [review]
LGTM

**Review by RandellDawson — APPROVED** [review]
I am fine with these changes.

**Comment by RandellDawson** [comment]
@lasjorg @moT01 Let's wait to merge this once all the Node JS boilerplate PRs have been merged.

**Comment by moT01** [comment]
We should be good to get this in when the boilerplate PR is approved.

**Comment by RandellDawson** [comment]
The boilerplate for this section of challenges was merged, so I am merging this one.  Until the next build is completed, it might be a little confusing for users, since we already added the correct Mongodb and Mongoose packages to the `package.json`, but it is easy to explain on the forum if it comes up.

**Pull request merged**
