### PR TITLE
fix: some editor edge cases

### PR DESCRIPTION
**Pull request by ojeytonwilliams**
- fix: handle erm on line zero
- refactor: fix eslint errors
- fix: prevent crash on zero height editable region

Closes: https://github.com/freeCodeCamp/freeCodeCamp/pull/43235

### CODE REVIEW

**Comment by ojeytonwilliams** [comment]
With this PR it should be possible to put `--fcc-editable-region--` markers wherever makes sense and the editor should Just Work.

**Review by ShaunSHamilton — COMMENTED** [review]
This works, provided the ERM is not on the last line:
image

**Comment by ojeytonwilliams** [comment]
What's the markdown that created this?  I probably should have said "Not crash" rather than "Just Work", though.

**Comment by ShaunSHamilton** [comment]
> What's the markdown that created this? I probably should have said "Not crash" rather than "Just Work", though.

````markdown
## --seed-contents--

```html
--fcc-editable-region--

--fcc-editable-region--

```
````

**Comment by ojeytonwilliams** [comment]
Okay, I'm not sure why I was confused.  

What you've shown is to be expected.  The improvement is that the editor is now usable, even if it does not look as it should.

**Review by ShaunSHamilton — APPROVED** [review]
This LGTM 👍 . Prevents crashes. So, less annoying to develop with.

**Review by naomi-lgbt — APPROVED** [review]
Looks good to me!

**Pull request merged**
