### PR TITLE
fix(client): add debounce to challenge submission

### PR DESCRIPTION
**Pull request by ShaunSHamilton**
Checklist:

- [x] I have read [freeCodeCamp's contribution guidelines](https://contribute.freecodecamp.org).
- [x] My pull request has a descriptive title (not a vague title like `Update index.md`)
- [x] My pull request targets the `main` branch of freeCodeCamp.
- [x] I have tested these changes either locally on my machine, or GitPod.

Adds a temporary debounce to the submission of challenges **using the button**. If this is not a debounce, then I do not know 🤷‍♂️

### CODE REVIEW

**Review by Nirajn2311 — COMMENTED** [review]
LGTM and tested it locally 👍

**Review by Nirajn2311 — DISMISSED** [review]

**Comment by Nirajn2311** [comment]
Clicked the wrong button the first time 😅

**Review by scissorsneedfoodtoo — DISMISSED** [review]
Tested locally and everything LGTM :+1: :+1: 

There does seem to be a slight but almost unnoticeable debounce whenever I spam the "Run the Tests (Ctrl + Enter)" button.

**Review by Nirajn2311 — APPROVED** [review]
No more console errors so LGTM 👍

**Review by Sembauke — APPROVED** [review]

**Pull request merged**
