### PR TITLE
Fix/minor issues

### PR DESCRIPTION
**Pull request by ValeraS**
- [x] I have read [freeCodeCamp's contribution guidelines](https://github.com/freeCodeCamp/freeCodeCamp/blob/master/CONTRIBUTING.md).
- [x] My pull request has a descriptive title (not a vague title like `Update index.md`)
- [x] My pull request targets the `master` branch of freeCodeCamp.
- [x] None of my changes are plagiarized from another source without proper attribution.

### CODE REVIEW

**Review by ojeytonwilliams — APPROVED** [review]
Tried this out locally.  The bogus warnings have gone and you can look at your public profile now.  LGTM :+1:

**Comment by raisedadead** [comment]
Not related to this PR but I see, two footers on the profile page for some reason. Maybe due to merging a recent PR. If it's all the same, can you take a look and fix it in this one?

image

**Comment by ojeytonwilliams** [comment]
@raisedadead I don't believe this is a real bug, just an artifact of Gatsby's way of showing 404s in development.  It should be fine once the site has been built.

Here's what it looks like when I go to a non-existent page, `donate/asgasdg`, after running 
* `npm run develop`
Dev404
and the same page after going to `client` and running 
* `npm run build` 
* `node node_modules/gatsby-cli/lib/index serve`
Build404

You get the same behaviour for pages like `not-a-user`, too. 

Development 404 pages on the guide really show what's going on:

Guide404
Guide404Shown

Again this goes away once you build.

These screenshots are of the [current master](https://github.com/freeCodeCamp/freeCodeCamp/tree/43fa451a386b6cf1c436305399b0ac16aa2a6efd).

**Review by raisedadead — APPROVED** [review]

**Comment by raisedadead** [comment]
Okay, thanks for confirming that @ojeytonwilliams I have merged this and will see how this behaves in the staging environment, that I am working hard to bring forward soon.

**Pull request merged**
