### PR TITLE
Fix-Corrected and maintained uniformity in title-casings of adv-bonfires

### PR DESCRIPTION
**Pull request by iammangod96**
#### Pre-Submission Checklist

- [x] Your pull request targets the `staging` branch of FreeCodeCamp.
- [ ] Branch starts with either `fix/`, `feature/`, or `translate/` (e.g. `fix/signin-issue`)
- [x] You have only one commit (if not, [squash](http://forum.freecodecamp.com/t/how-to-squash-multiple-commits-into-one-with-git/13231) them into one commit).
- [x] All new and existing tests pass the command `npm run test-challenges`. Use `git commit --amend` to amend any fixes.
#### Type of Change

- [x] Small bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds new functionality)
- [ ] Breaking change (fix or feature that would change existing functionality)
- [ ] Add new translation (feature adding new translations)
#### Checklist:

- [x] Tested changes locally.
- [ ] Closes currently open issue (replace XXXX with an issue no): Closes #XXXX
#### Description

Maintaining the uniformity of previous challenge title-casings, the new titles were cased correctly with title-cases to important words in titles.

### CODE REVIEW

**Comment by BerkeleyTrue** [comment]
@iammangod96 You have two PR's open with the same title. Did you accidentally create duplicate PR's or are they two PR's with the same title?

**Comment by iammangod96** [comment]
@BerkeleyTrue They are for different challenges. This one is for advanced bonfires and other is for basic bonfires.
If you want I can close both the pull requests and do both in a single pull request.
Thank you.

**Comment by systimotic** [comment]
@iammangod96 I am in favor of combining both into one. I really like the change you made!

**Comment by BerkeleyTrue** [comment]
@iammangod96 They can stay as is.

In the future, they can be combined under one PR.

**Comment by raisedadead** [comment]
LGTM.

@iammangod96 thanks a lot for the changes, looking forward to more in future. Just make sure to go through the [Guidelines for Contributing](https://github.com/FreeCodeCamp/FreeCodeCamp/blob/staging/CONTRIBUTING.md). 

Preferably make a changes from a local copy of you fork.

**Pull request merged**
