### PR TITLE
Add new video challenge stubs

### PR DESCRIPTION
**Pull request by QuincyLarson**
I'd like to list the video challenges that are "coming soon" - both to reassure campers that we plan to create video challenges to cover these subjects, and to jump start development of projects for these subjects.

### CODE REVIEW

**Comment by SaintPeter** [comment]
There is one problem:  If I complete the last "Real" video challenge before the "Coming Soon" challenges, it forwards me to a "blank" video challenge.

I'm going to hold off on merging these until we figure out if that's an issue or not.

**Comment by QuincyLarson** [comment]
@SaintPeter Nice discovery. I'm looping in @BerkeleyTrue to see if he can write this logic, since he's most familiar with the video challenge code.

**Comment by bugron** [comment]
@QuincyLarson @SaintPeter @BerkeleyTrue any updates on this?

**Comment by BerkeleyTrue** [comment]
Rebased off staging and filtering out video challenges fixes the issue.

There is still a flash before the redirect to the map happens but I'm hoping to fix that in the react-challenges branch

**Comment by raisedadead** [comment]
#### :sparkles: :sparkles: **LGTM.** :sparkles: :sparkles: 

Thanks @QuincyLarson @BerkeleyTrue .

**Pull request merged**
