### PR TITLE
fix: add message about third-party cookies

### PR DESCRIPTION
**Pull request by moT01**
I played around with a few ideas - alerts, modals - this seemed pretty good...

Screen Shot 2022-04-11 at 3 54 32 PM 1

Not sure if it's what we want. It might be a little much for a button, but it ensures that users see it.

- [x] I have read [freeCodeCamp's contribution guidelines](https://contribute.freecodecamp.org).
- [x] My pull request has a descriptive title (not a vague title like `Update index.md`)
- [x] My pull request targets the `main` branch of freeCodeCamp.
- [x] I have tested these changes either locally on my machine, or GitPod.

Related to: https://github.com/freeCodeCamp/CodeAlly-CodeRoad-freeCodeCamp/issues/42 and https://github.com/freeCodeCamp/freeCodeCamp/issues/45553

### CODE REVIEW

**Comment by nhcarrigan** [comment]
It does seem a little much for a button. Why not the blue info box?

**Comment by bbsmooth** [comment]
Agreed, it does seem a little much for a button, the third-party cookies warning should probably be pulled out into a separate container. But I do think it might be a good idea to programmatically associate that warning with the button just in case a screen reader user jumped to the button and missed the warning. You can do this by giving the warning container an `id` and then using `aria-describedby="id"` on the button. 

Also, I would avoid using "click here" in the button text. I would just have it say "Start the course".

**Comment by moT01** [comment]
New look:
Screen Shot 2022-04-12 at 7 39 26 AM

**Review by naomi-lgbt — APPROVED** [review]
This looks good to me.

**Review by raisedadead — APPROVED** [review]

**Pull request merged**
