### PR TITLE
feature(challenges): load current challenge on first visit

### LINKED ISSUE #9587: [beta] add current-challenge route

### PR DESCRIPTION
**Pull request by BerkeleyTrue**
closes #9587

### CODE REVIEW

**Comment by raisedadead** [comment]
@BerkeleyTrue there is a crash with this pull request.
Stack is available here https://gist.github.com/raisedadead/69672aeea9df8b590814b35df52798b2

Steps to reproduce:
1. Open localhost:3001/en/
2. Click Sign in
3. Use the map visit a random challenge
4. Sign out
5. Click NAV logo

**Comment by raisedadead** [comment]
An update this http://localhost:3001/en/challenges/current-challenge route seems to be not working when I am logged out.

**Comment by BerkeleyTrue** [comment]
@raisedadead can you double check that your database is properly seed?

**Comment by raisedadead** [comment]
Yup, I can confirm that the database was seeded. But never mind the last commit on this pull request fixed the crash.

Thanks.

**Pull request merged**
