### PR TITLE
Add a period at the end of an ul tag

### LINKED ISSUE #42479: Missing period at the end of the third sentence.
**Affected page**
https://www.freecodecamp.org/learn/responsive-web-design/basic-html-and-html5/create-a-bulleted-unordered-list

**Your code**
Copy and paste the code from the editor that you used in between the back-ticks below:

```




```

**Expected behavior**
There should be a period at the end of the third sentence (Finally ...).

**Screenshots**
Screen

**System (please complete the following information):**
 - Device: [e.g. iPhone6, Laptop]
 - OS: [e.g. iOS 14, Windows 10, Ubuntu 20.4]
 - Browser: [e.g. chrome, safari]
 - Version: [e.g. 22]

**Additional context**

### PR DESCRIPTION
**Pull request by deveshrane**
Add a period at the end of an ul tag at line number 14.

Checklist:

- [X] I have read [freeCodeCamp's contribution guidelines](https://contribute.freecodecamp.org).
- [X] My pull request has a descriptive title (not a vague title like `Update index.md`)
- [X] My pull request targets the `main` branch of freeCodeCamp.
- [X] I have tested these changes either locally on my machine, or GitPod.

Closes #42479

### CODE REVIEW

**Review by raisedadead — DISMISSED** [review]
@deveshrane thanks for the PR. Could you edit the OP (the first comment/post) in the thread and add the issue no. real quick. That would close the linked issue when this PR is merged.

**Review by Sembauke — APPROVED** [review]
Hey @deveshrane,

Thank you for taking this on 🥇 
We hope to see more of you in the future 😄 

Happy contributing

**Review by raisedadead — APPROVED** [review]

**Comment by deveshrane** [comment]
Hey @raisedadead, I am sorry I was unavailable for the change you requested, to be honest this was my first contribution to the open source community and @Sembauke thanks for updating the OP because I didn't know how to do that. Thank you very much for merging my request. I personally have learnt from freeCodeCamp and I love it. I'll definitely contribute to open source.

**Comment by Sembauke** [comment]
> Hey @raisedadead, I am sorry I was unavailable for the change you requested, to be honest this was my first contribution to the open source community and @Sembauke thanks for updating the OP because I didn't know how to do that. Thank you very much for merging my request. I personally have learnt from freeCodeCamp and I love it. I'll definitely contribute to open source.

Great to hear @deveshrane

**Comment by raisedadead** [comment]
Hey @deveshrane, sure, do not worry about it. 

We understand contributors are busy, and we are always grateful for all contributions. As for this community, we really do not have any deadlines, so feel free to work on something that interests you. We have several help-wanted topics that could use help. 

Also, other than this community, Noje.js & Gatsby are particularly open and welcoming to new contributors. You should check them out too.

Good luck and happy contributing.

**Pull request merged**
