### PR TITLE
Updated index with Gitpod and Bug Fix introduction

### PR DESCRIPTION
**Pull request by jaywangjhw**
Updated index with Gitpod and Bug Fix introduction

Checklist:

- [x] I have read [freeCodeCamp's contribution guidelines](https://contribute.freecodecamp.org).
- [x] My pull request has a descriptive title (not a vague title like `Update index.md`)
- [x] My pull request targets the `main` branch of freeCodeCamp.
- [x] I have tested these changes either locally on my machine, or GitPod.

Closes #XXXXX

### CODE REVIEW

**Comment by raisedadead** [comment]
Thanks for contributing, however, I am not sure of these changes. 

I understand you trying to add more documentation around contributing, but could you elaborate on the needs, your pain points and steps that are probably missing from our current docs.

**Comment by jaywangjhw** [comment]
The needs and steps that are missing from current documents is a walk though for new users on how to set up for contribution

**Comment by raisedadead** [comment]
Yes - I understand that. My question is can you elaborate in detail on the pain points though, so we can discuss and consider documentation around it?

**Comment by raisedadead** [comment]
Thank you for opening this pull request.

This is a standard message notifying you that we’ve reviewed your pull request and have decided not to merge it. We would welcome future pull requests from you.

Please read our [Guidelines for Contributing](https://contribute.freecodecamp.org) for more.

Thank you and happy coding.

**Pull request closed without merging**
