### PR TITLE
docs: updated Additional Guides to support mongodb setup on m1 Apple …

### PR DESCRIPTION
**Pull request by JesseZelaya**
…devices

Checklist:

- [x] I have read [freeCodeCamp's contribution guidelines](https://contribute.freecodecamp.org).
- [x] My pull request has a descriptive title (not a vague title like `Update index.md`)
- [x] My pull request targets the `main` branch of freeCodeCamp.
- [x] I have tested these changes either locally on my machine, or GitPod.

Closes #XXXXX

Added support for mongodb installation and launching on Ventura OS for Apple devices with an M1 chip. This details how to install Homebrew using Rosetta and changes that need to be made to the mongodb config file for it to run smoothly on these systems.

### CODE REVIEW

**Review by raisedadead — CHANGES_REQUESTED** [review]
Why not use a docker-based container? Install Docker (or Docker Desktop) and run MongoDB from within docker. It is pretty straight than doing all this?

P.S: I am on M1 & macOS 13, if you are wondering.

**Comment by raisedadead** [comment]
We are officially on Node.js 18 now. We have changed the merge requirements accordingly.

You will need to rebase this PR against the main branch OR Click the "Update branch" button to get the new checks going.

Thanks for your contribution.

**Comment by JesseZelaya** [comment]
> Why not use a docker-based container? Install Docker (or Docker Desktop) and run MongoDB from within docker. It is pretty straight than doing all this?
> 
> P.S: I am on M1 & macOS 13, if you are wondering.

When going through all of MongoDB’s support and other M1 guides I never saw that as a solution. I haven’t had much luck in running any VMs for running intel based installations.

**Comment by raisedadead** [comment]
That is correct. It's best to use a docker-based installation for MongoDB because

1. It standardizes the installation process and gives you easy upgrades when we change versions.
2. Our servers (the final target you are writing code for) run on Linux and x86. 

So it's a wasted effort trying to install things natively on mac. The performance difference (only valid argument for a native install) when "working locally" is not even noticeable.

Please adjust the PR accordingly.

**Comment by raisedadead** [comment]
Hi, 

We are closing old issues/pull requests that we think are stale. If you still need help or are fixing this, please open a new issue/pull request.

Thanks for your understanding. 

Happy contributing.

**Pull request closed without merging**
