### PR TITLE
fix(curriculum): corrected wrong usage of it's contraction

### PR DESCRIPTION
**Pull request by jctello**
Checklist:

- [X] I have read [freeCodeCamp's contribution guidelines](https://contribute.freecodecamp.org).
- [X] My pull request has a descriptive title (not a vague title like `Update index.md`)
- [X] My pull request targets the `main` branch of freeCodeCamp.
- [X] I have tested these changes either locally on my machine, or GitPod.

Description:
Inspired by this issue: https://github.com/freeCodeCamp/freeCodeCamp/issues/48238
I decided to systematically look for all uses wrong uses of the contraction `it's` when the correct is to indicate the possessive  `its` throughout the repository.

This PR intentionally ignores the two typos corrected by https://github.com/freeCodeCamp/freeCodeCamp/pull/48239

However this will generate an easy to fix conflict given that one of the lines contained in that PR has another similar typo.

This PR fixes the issue observed in the subfolders of all languages for which the individual challenges have been copied.

### CODE REVIEW

**Comment by ieahleen** [comment]
As a new contributor, we encourage you to read our [contributing guidelines](https://contribute.freecodecamp.org).

We expect our contributors to be aware of the process specific to this project. Following the guidelines religiously earns you the respect of fellow maintainers and saves everyone time.

Some examples of this are:

1. Do not edit files directly through GitHub – while you can, it's not a good idea.
2. Make sure you follow the PR checklist and not just tick things off; otherwise, we won't take you seriously.
3. Use the correct way to link issues in the description of the PR by updating the `XXXXXX`. Do not just add issue numbers everywhere and anywhere you feel like.
4. Keep mentions and review requests to a minimum. We understand you are excited about contributing, and our maintainers will get back to you as soon as they get a chance.
5. Do not work directly off your `main` branch - create a new branch for the changes you are working on.
6. Do not change curriculum files in languages other than English.

We appreciate you taking the time to help us, and we hope to see more contributions from you.

Happy Contributing.

**Comment by jctello** [comment]
I fixed the mistake of editing the non-English files reverting them to their prior state. 
Please let me know if I should do this in a different way.

**Comment by ieahleen** [comment]
make sure you give the PR a name that follows the guidelines!

**Comment by jctello** [comment]
Changed the title to follow the [guidelines](https://contribute.freecodecamp.org/#/how-to-open-a-pull-request?id=prepare-a-good-pr-title).

**Review by majestic-owl448 — APPROVED** [review]
Thank you for your PR!

**Comment by jctello** [comment]
Great! thank you for taking the time to review it. 
Let me know if anything else is necessary on my part. 
If merging cannot be done in the next few days I would really appreciate it if the `hacktoberfest-accepted` label would be added.

**Review by Sembauke — APPROVED** [review]

**Pull request merged**
