### PR TITLE
missing global object element: Array

### PR DESCRIPTION
**Pull request by halmosigabor**
- [x] I have read [freeCodeCamp's contribution guidelines](https://github.com/freeCodeCamp/freeCodeCamp/blob/master/CONTRIBUTING.md).
- [x] My pull request has a descriptive title (not a vague title like `Update index.md`)
- [x] My pull request targets the `master` branch of freeCodeCamp.
- [x] None of my changes are plagiarized from another source without proper attribution.
- [x] My article does not contain shortened URLs or affiliate links.

If your pull request closes a GitHub issue, replace the XXXXX below with the issue number.

Closes #XXXXX

### CODE REVIEW

**Comment by RandellDawson** [comment]
@halmosigabor I made the changes suggested by camperBot on your behalf.

**Comment by halmosigabor** [comment]
@RandellDawson thank you! I'm still learning how to use github. Should I do something, or is it OK now?

**Comment by RandellDawson** [comment]
@halmosigabor Now that the error has been resolved, you will just have to wait for a review to be made of your actual content.  It may be a while, because we still have a large backlog from Hacktoberfest.

**Comment by RandellDawson** [comment]
Thank you for opening this pull request.

This is a standard message notifying you that we’ve reviewed your pull request and have decided not to merge it. We would welcome future pull requests from you.

Reason:  Your changes are just a duplication of the content found at https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Array.  We do not allow plagiarized content in our Guide.

Thank you and happy coding.

**Pull request closed without merging**
