### PR TITLE
fix(curriculum): update test to accept array destructuring

### LINKED ISSUE #46728: Tests are not passing when using new JS syntax (const [LOGIN, LOGOUT] = ['LOGIN', 'LOGOUT'])
### Describe the Issue

Test doesn't pass even, if variables are declared using `const`. It's totally correct and it's working, but tests doesn't pass. Variables are `const`, but are made using the new syntax which I think tests doesn't support.

### Affected Page

https://www.freecodecamp.org/learn/front-end-development-libraries/redux/use-const-for-action-types

### Your code

```
const [LOGIN, LOGOUT] = ['LOGIN', 'LOGOUT']

const defaultState = {
  authenticated: false
};

const authReducer = (state = defaultState, action) => {


  switch (action.type) {
    case LOGIN:
      return {
        authenticated: true
      }
    case LOGOUT:
      return {
        authenticated: false
      }

    default:
      return state;

  }

};

const store = Redux.createStore(authReducer);

const loginUser = () => {
  return {
    type: LOGIN
  }
};

const logoutUser = () => {
  return {
    type: LOGOUT
  }
};
```

### Expected behavior

Tests should pass.

### Screenshots

Screenshot 2022-06-30 at 17-22-58 freeCodeCamp org

### System

- Device: [e.g. iPhone 6, Laptop]
- OS: [e.g. iOS 14, Windows 10, Ubuntu 20.04]
- Browser: [e.g. Chrome, Safari]
- Version: [e.g. 22]

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by lulululu12345**
- [x] I have read [freeCodeCamp's contribution guidelines](https://contribute.freecodecamp.org).
- [x] My pull request has a descriptive title (not a vague title like `Update index.md`)
- [x] My pull request targets the `main` branch of freeCodeCamp.
- [x] I have tested these changes either locally on my machine, or GitPod.

Closes #46728

I'm pretty new to writing regex - not sure that what I've written is the cleanest it could be. Please let me know if there are any changes I should make.

### CODE REVIEW

**Review by Sboonny — APPROVED** [review]
LGTM 🎉, thank you for your contribution to the page! 👍.

**Review by raditotev — COMMENTED** [review]
@lulululu12345 your regex works fine but I am concerned the assertion is somewhat complicated and difficult to read. May I suggest to update, so that the test is checking if there are variables `LOGIN` and `LOGOUT` and their values are respectively `'LOGIN'` and `'LOGOUT'`. In doing so the test will look like this:
```js
assert(
  LOGIN === 'LOGIN' && LOGOUT === 'LOGOUT'
);
```
And since we don't do text comparison we don't need this line:
```js
const noWhiteSpace = __helpers.removeWhiteSpace(code);
```
@Sboonny what do you think about my proposal?

**Comment by raditotev** [comment]
I just thought of another scenario. What if a user decides to use object destructuring, e.g..:
```js
const {LOGIN, LOGOUT} = {LOGIN: 'LOGIN', LOGOUT: 'LOGOUT'}
```
This is valid and the challenge should pass but it won't with current regex. Further extending the regex to cover this case will make things even more complicated.

**Comment by Sboonny** [comment]
> the test is checking if there are variables LOGIN and LOGOUT and their values are respectively 'LOGIN' and 'LOGOUT'
 
 The challenge is talking about the using `const`, so I don't see why it should check if the variable is `const` and if the variable value is `LOGIN`.
 
@raditotev I like the idea of breaking this test into two, one that check if the variables `LOGIN`, and `LOGOUT` are consts, and a second that check their values. But @lulululu12345 mentioned he is new to regex, so I suggest passing this as is, and creating a new issue for said suggestions.

**Comment by lulululu12345** [comment]
`assert(
  ((/constLOGIN/.test(noWhiteSpace) &&
    /constLOGOUT/.test(noWhiteSpace)) ||
    /const\[(LOGIN|LOGOUT),(?!\1)(LOGIN|LOGOUT)\]/.test(noWhiteSpace) ||
    /const\{(LOGIN|LOGOUT),(?!\1)(LOGIN|LOGOUT)\}/.test(noWhiteSpace)) &&
    LOGIN === 'LOGIN' && LOGOUT === 'LOGOUT'
);`

How about something like this? Not sure if this is the cleanest/most efficient way to go about it, but I believe it covers all the issues mentioned and the regex is more readable than my initial solution.

**Review by raditotev — APPROVED** [review]
This PR fixes the related issue and @lulululu12345 has done a sterling job updating the regex in the test. If user decides to use one of the following the test will pass now:
```js
const LOGIN = 'LOGIN', LOGOUT = 'LOGOUT'
```
or
```js
const [LOGIN, LOUGOUT] = ['LOGIN', 'LOGOUT']
```
However if user decides to use different way of assigning the two variables tests will fail again, even though the code will be correct. For example:
```js
const [LOGOUT, LOGIN] = ['LOGOUT', 'LOGIN']
```
I had a suggestion for the assertion but as @Sboonny rightly pointed out it wasn't testing user is using an immutable `const` variable. I have tried to cover for this test case with reassigning the variables and expecting an error but this didn't work as well:
```js
assert.throws(() => {LOGIN = 'some value'}, TypeError, 'Assignment to constant variable.')
```
For some reason the JS test runner allows constants to change.

Considering all that, I believe @lulululu12345 solutions is the best we have for now.

**Comment by raditotev** [comment]
>I don't see the point in that line as well
>>const noWhiteSpace = __helpers.removeWhiteSpace(code);

@Sboonny this helper removes all white space from the code under test, so that it doesn't have to be taken into consideration within the regex.

**Comment by raditotev** [comment]
> ```
> assert(
>   ((/constLOGIN/.test(noWhiteSpace) &&
>     /constLOGOUT/.test(noWhiteSpace)) ||
>     /const\[(LOGIN|LOGOUT),(?!\1)(LOGIN|LOGOUT)\]/.test(noWhiteSpace) ||
>     /const\{(LOGIN|LOGOUT),(?!\1)(LOGIN|LOGOUT)\}/.test(noWhiteSpace)) &&
>     LOGIN === 'LOGIN' && LOGOUT === 'LOGOUT'
> );
> ```
> 
> How about something like this? Not sure if this is the cleanest/most efficient way to go about it, but I believe it covers all the issues mentioned and the regex is more readable than my initial solution.

I am sorry @lulululu12345, I must have missed your comment. You suggestion is sound and it will further increase the reliability of the test but in my opinion there will always be edge cases where this test will fail unless we move away from regex.
Thanks again for your contribution 👍

**Pull request merged**
