### PR TITLE
Fixes issue with background-color and background being interpreted differently

### PR DESCRIPTION
**Pull request by thecodingaviator**
- [x] I have read [freeCodeCamp's contribution guidelines](https://github.com/freeCodeCamp/freeCodeCamp/blob/master/CONTRIBUTING.md).
- [x] My pull request has a descriptive title (not a vague title like `Update index.md`)
- [x] My pull request targets the `master` branch of freeCodeCamp.
- [x] None of my changes are plagiarized from another source without proper attribution.
- [x] My article does not contain shortened URLs or affiliate links.

Fixes issue #17836

@scissorsneedfoodtoo , #19720

### CODE REVIEW

**Comment by scissorsneedfoodtoo** [comment]
@thecodingaviator, thank you for taking the time to create a new PR for this. But it's still not triggering the build for some reason! Maybe it has something to do with the commit history? @raisedadead, do you know what's going on here?

**Comment by thecodingaviator** [comment]
Funny, none of my other PRs are triggering a build as well. I think you guys should check with Travis CI?

**Comment by lynxlynxlynx** [comment]
The challenge is called "Adjust the background-color Property of Text", so this change looks spurious. The exercise's intent is to teach background-color, not any possible way to change the background color. It's mentioned several times in the description.

The background family deserves more separate lessons and then a "shorthand" one to tie them  together. Would also better fit into the basic css section rather than accessibility:
https://learn.freecodecamp.org/responsive-web-design/basic-css/give-a-background-color-to-a-div-element/

**Comment by lynxlynxlynx** [comment]
I think it's explicit enough, but you can add a discussion tag, so others take a look.

**Comment by thecodingaviator** [comment]
@lynxlynxlynx I don't have the ability to add them

**Comment by scissorsneedfoodtoo** [comment]
@lynxlynxlynx brings up a very good point about the challenge name and the possibility of the new testString causing some confusion. Also, the suggestion to create more lessons to properly teach the various background properties is great, but maybe a bit outside of the scope of this particular PR. Definitely something to keep in mind in the future and perhaps something you can help us with later, @thecodingaviator?

Maybe the best solution is to change the test in question to the following:

```
  - text: Your code should add a <code>background-color</code> property to the <code>h4</code> element set to <code>rgba(45, 45, 45, 0.1)</code>.
    testString: assert(code.match(/(background-color|background):\s*?rgba\(\s*?45\s*?,\s*?45\s*?,\s*?45\s*?,\s*?0?\.1\s*?\);/gi), 'Your code should add a <code>background-color</code> property to the <code>h4</code> element set to <code>rgba(45, 45, 45, 0.1)</code>. Be sure to use a <code>;</code> after your property declaration.');
```

This way the test will still pass if the user decides to use the background shorthand property, but won't explicitly be told that it's an option when looking over the tests. What do you think, @thecodingaviator?

**Comment by thecodingaviator** [comment]
@scissorsneedfoodtoo You're right, changes done

**Pull request merged**
