### PR TITLE
Fix for font issues on linux machines

### LINKED ISSUE #6661: Text Overlapping On Map Page
It appears that there is some overlapping of the module/section names over the estimated completion time. This does not happen on Chome when I tested it, only on Firefox Dev Edition and regular Firefox.
Common issue? Or my own browsers?

My dimensions are:
Browser window width:	1920
Browser window height:	905
Screen width:	1920
Screen height:	1080

screenshot from 2016-02-01 16 42 14

### PR DESCRIPTION
**Pull request by justincorrigible**
It's been noticed a few times, and being on linux (Ubuntu, particularly) seems to cause the same issue with the font bundles defaulting to the sans-serif.

This patch changes locally hosted lato ttfs for google font hosted woff2, with extended latin subsets. (which may also be the issue, due to localisations).

Closes #6661

### CODE REVIEW

**Comment by BerkeleyTrue** [comment]
@hallaathrad Thanks but we can't use Google as a hosting platform as it is blocked in China.

**Comment by hallaathrad** [comment]
right... how about I fix this so we have the woff2 locally instead?

**Comment by hallaathrad** [comment]
I've amended the PR to host the woff2 files in the server (if this works, I'll remove the ttf)... 
improved the css for (non-extended) latin characters.

**Comment by BerkeleyTrue** [comment]
woff2 is not supported in IE/EDGE, or Safari

**Comment by hallaathrad** [comment]
Trying a different approach: browser specific font CSS.

**Pull request closed without merging**
