### PR TITLE
Fix challenge type for data structure and ES6 challenges

### LINKED ISSUE #12667: Javascript not compiling in ES6 challenges (Beta site)
The javascript is not compiling or have any syntax highlighting in ES6 challenges.

#### Challenge Name
[ES6 challenges](http://beta.freecodecamp.com/en/map#ES6)

#### Issue Description
The issues happen when starting the ES6 coding challenges 

#### Browser Information

* Chrome, 55.0.2883.95 (64-bit): 
* MacOS Sierra 10.12.2: 
* Desktop: 

#### Screenshot
screenshot

### PR DESCRIPTION
**Pull request by systimotic**
#### Pre-Submission Checklist
- [x] Your pull request targets the `staging` branch of freeCodeCamp.
- [x] Branch starts with either `fix/`, `feature/`, or `translate/` (e.g. `fix/signin-issue`)
- [x] You have only one commit (if not, [squash](http://forum.freecodecamp.com/t/how-to-squash-multiple-commits-into-one-with-git/13231) them into one commit).
- [x] All new and existing tests pass the command `npm test`. Use `git commit --amend` to amend any fixes.

#### Type of Change
- [x] Small bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds new functionality)
- [ ] Breaking change (fix or feature that would change existing functionality)
- [ ] Add new translation (feature adding new translations)

#### Checklist:
- [x] Tested changes locally.
- [x] Closes currently open issue (replace XXXX with an issue no): Closes #12667

#### Description
As discussed in the issue, these sections had the wrong challenge type. This PR fixes that.

/cc @HKuz

### CODE REVIEW

**Comment by no-stack-dub-sack** [comment]
## LGTM

**Comment by HKuz** [comment]
Just ran this locally and LGTM, too! Thanks @systimotic  👍 ✨ 

@no-stack-dub-sack - you reviewed first, you get merging honors 😄

**Comment by no-stack-dub-sack** [comment]
@HKuz Thanks! First time I'm clicking this button for FCC! 🎉

**Comment by systimotic** [comment]
@no-stack-dub-sack I'm still anxious every single time I click it 😅

**Comment by no-stack-dub-sack** [comment]
Haha, no kidding! This one was so simple I felt pretty good about it, and that revert button also gives me comfort lol

**Comment by systimotic** [comment]
@no-stack-dub-sack It does! In the past three months I've only merged two or three pull requests, so I'm also still just getting used to it. 🙂

**Comment by gracegalos2016** [comment]
Am 21.01.2017 16:23 schrieb "Timo" <notifications@github.com>:

Pre-Submission Checklist

   - Your pull request targets the staging branch of freeCodeCamp.
   - Branch starts with either fix/, feature/, or translate/ (e.g.
   fix/signin-issue)
   - You have only one commit (if not, squash
   <http://forum.freecodecamp.com/t/how-to-squash-multiple-commits-into-one-with-git/13231>
   them into one commit).
   - All new and existing tests pass the command npm test. Use git commit
   --amend to amend any fixes.

Type of Change

   - Small bug fix (non-breaking change which fixes an issue)
   - New feature (non-breaking change which adds new functionality)
   - Breaking change (fix or feature that would change existing
   functionality)
   - Add new translation (feature adding new translations)

Checklist:

   - Tested changes locally.
   - Closes currently open issue (replace XXXX with an issue no): Closes
   #12667 <https://github.com/freeCodeCamp/freeCodeCamp/issues/12667>

Description

As discussed in the issue, these sections had the wrong challenge type.
This PR fixes that.

/cc @HKuz <https://github.com/HKuz>
------------------------------
You can view, comment on, or merge this pull request online at:

  https://github.com/freeCodeCamp/freeCodeCamp/pull/12689
Commit Summary

   - Fix challenge type for data structure and ES6 challenges

File Changes

   - *M* seed/challenges/02-javascript-algorithms-and-data-
   structures/basic-data-structures.json
   <https://github.com/freeCodeCamp/freeCodeCamp/pull/12689/files#diff-0>
   (38)
   - *M* seed/challenges/02-javascript-algorithms-and-data-
   structures/es6.json
   <https://github.com/freeCodeCamp/freeCodeCamp/pull/12689/files#diff-1>
   (50)

Patch Links:

   - https://github.com/freeCodeCamp/freeCodeCamp/pull/12689.patch
   - https://github.com/freeCodeCamp/freeCodeCamp/pull/12689.diff

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on
<https://github.com/freeCodeCamp/freeCodeCamp/pull/12689>GitHub und, or mute
the thread

**Comment by texas2010** [comment]
@gracegalos2016 
looks like you may have accidentally subscribed to all notifications for the [FreeCodeCamp](https://github.com/FreeCodeCamp/FreeCodeCamp) repository. To stop receiving notifications please visit the [subscriptions page](https://github.com/FreeCodeCamp/FreeCodeCamp/subscription) and select "Not watching". Additionally, you can visit the [GitHub Help page on managing notification delivery methods](https://help.github.com/articles/managing-notification-delivery-methods/) for more help.

We are sorry for your inconvenience!

**Pull request merged**
