### PR TITLE
feat(navbar): Improvement in button and navbar

### LINKED ISSUE #16946: [Beta] Required improvements in Panel control buttons and Navigation bar
### Issue Description
**Issues with panel control buttons:**

- [ ] During night mode the buttons look like they are disabled.
night mode 01

- [ ] On disabling more than one panel it is not reflected in button's UI i.e. all the disabled panel buttons should grey out but only one button is greyed out not the others. 

- [ ] During loading on slow networks the buttons should not be clickable. 
- [ ] On enabling a panel it still looks like disabled until we click somewhere on the screen. (Related to #16942) 
- [ ] On hovering over the button, the background blends with the navigation bar, it should look a bit lighter than dark green. Setting rgba value to (0, 100, 0, 0.4) will fix it. 

**Issue with navigation bar:**
- [ ] There is a very large amount extra whitespace at the right end of the navigation bar.
capture
- [ ] The search bar's width should be increased so that the placeholder text is properly visible. 
search bar nav

### Browser Information
* Browser Name, Version: Chrome(65.0.3325.181) and Firefox(59.0.1). 
* Operating System: Windows 10 Pro 32 Bit. 
* Mobile, Desktop, or Tablet: Desktop.

### PR DESCRIPTION
**Pull request by love1024**
Closes #16946

feat(navbar): improvement in navbar and panel button

Closes #16946

#### Pre-Submission Checklist

- [x] Your pull request targets the `staging` branch of freeCodeCamp.
- [x] Branch starts with either `fix/`, `feature/`, or `translate/` (e.g. `fix/signin-issue`)
- [x] You have only one commit (if not, [squash](http://forum.freecodecamp.org/t/how-to-squash-multiple-commits-into-one-with-git/13231) them into one commit).
- [x] All new and existing tests pass the command `npm test`. Use `git commit --amend` to amend any fixes.

#### Type of Change

- [ ] Small bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds new functionality)
- [ ] Breaking change (fix or feature that would change existing functionality)
- [ ] Add new translation (feature adding new translations)

#### Checklist:

- [x] Tested changes locally.
- [x] Addressed currently open issue (replace XXXXX with an issue no in next line)

Closes #16946 

#### Description

imp

### CODE REVIEW

**Comment by raisedadead** [comment]
Hi @love1024 

Do you mind sharing some screenshots? Of course we will pull this down too. But some screenshots will help give any initial feedback.

Thanks.

**Comment by love1024** [comment]
@raisedadead  I have added a screenshot. You can see search bar is more wide, now button disable can persist & navbar links are moved to right side.

**Review by raisedadead — COMMENTED** [review]
#### :sparkles: :sparkles: **LGTM.** :sparkles: :sparkles: 

Thanks @love1024 

Happy Contributing!

**Comment by love1024** [comment]
@raisedadead Welcome Sure.

**Pull request merged**
