### PR TITLE
fix: Stop <strong> from being displayed in tests

### PR DESCRIPTION
**Pull request by thecodingaviator**
- [x] I have read [freeCodeCamp's contribution guidelines](https://github.com/freeCodeCamp/freeCodeCamp/blob/master/CONTRIBUTING.md).
- [x] My pull request has a descriptive title (not a vague title like `Update index.md`)
- [x] My pull request targets the `master` branch of freeCodeCamp.
- [x] None of my changes are plagiarized from another source without proper attribution.
- [x] All the files I changed are in the same world language (for example: only English changes, or only Chinese changes, etc.)
- [x] My changes do not use shortened URLs or affiliate links.

The PR intends to stop the strong tags from showing if any test fails. See https://github.com/freeCodeCamp/freeCodeCamp/pull/35774#discussion_r273383987

### CODE REVIEW

**Comment by RandellDawson** [comment]
@thecodingaviator Since https://github.com/freeCodeCamp/freeCodeCamp/issues/35800 is discussing a way to deal with any tag and not just strong tags, I think we should wait for a more robust solution to this issue or we will keep having to replace more tags.

**Comment by thecodingaviator** [comment]
@RandellDawson Maybe for now we can do this and once we come up with a way to do it on #35800 , we can go ahead and just remove these 4-5 lines from here

**Comment by RandellDawson** [comment]
@thecodingaviator Out of curiosity, why did you not use the regex I suggested (see below) on PR #35774 for the `replace`?
```
/<(wbr|\/?strong)>/g;
```

**Comment by thecodingaviator** [comment]
> @thecodingaviator Out of curiosity, why did you not use the regex I suggested (see below) on PR #35774 for the `replace`?
> 
> ```
> /<(wbr|\/?strong)>/g;
> ```

Didn't notice that, I got carried away with how it was done in Valeriy's PR. Do you want me to change this?

**Comment by RandellDawson** [comment]
I will leave that up to you.

**Comment by thecodingaviator** [comment]
I'm going to leave it like this for now with added comments so that the replace regex does not get very long in case we have to do it this way and #35800 takes a long time

**Comment by moT01** [comment]
I think this can probably be close as https://github.com/freeCodeCamp/freeCodeCamp/pull/35857 looks like it will solve the issues related here.

**Comment by RandellDawson** [comment]
@moT01 I agree.

**Comment by thecodingaviator** [comment]
I've edited the other PR to close this when merged

**Pull request closed without merging**
