### PR TITLE
fix: use env.json in both client and server

### PR DESCRIPTION
**Pull request by ojeytonwilliams**
Rather than having the server use env.js and the client use env.json, we can just use env.json everywhere.  I've also renamed env.js to read-env.js so it's distinct from env.json.

Edit: completely changed from original approach.

### CODE REVIEW

**Review by naomi-lgbt — DISMISSED** [review]
> and break the client.

Can't break the client if you don't have a client to break 🙃 

Looks good to me!

**Comment by ojeytonwilliams** [comment]
> Can't break the client if you don't have a client to break 

and for my next trick...

**Review by raisedadead — CHANGES_REQUESTED** [review]
If I am not mistaken, this still requires us to **"remember"** import `env-data.json`? 

IMHO we should rename the `env.js` to something that makes it explicit when someone is importing files that it's not the one to be imported.

I am fine with this current change, but I honestly think it doesn't solve the issue you are trying to address.

**Comment by ojeytonwilliams** [comment]
> IMHO we should rename the env.js to something that makes it explicit when someone is importing files that it's not the one to be imported.

> I am fine with this current change, but I honestly think it doesn't solve the issue you are trying to address.

:facepalm: Yeah, you're completely right, I "solved" the problem backwards.  I'll rename `env.js` to `generate-env` and leave `env.json` alone.

**Review by raisedadead — APPROVED** [review]

**Review by ShaunSHamilton — APPROVED** [review]
This LGTM 👍

**Pull request merged**
