### PR TITLE
Add semicolon to end of console.log();

### PR DESCRIPTION
**Pull request by AustinThornley**
Checklist:

- [x ] I have read [freeCodeCamp's contribution guidelines](https://contribute.freecodecamp.org).
- [x ] My pull request has a descriptive title (not a vague title like `Update index.md`)
- [x] My pull request targets the `main` branch of freeCodeCamp.
- [x] I have tested these changes either locally on my machine, or GitPod.

### CODE REVIEW

**Comment by Sembauke** [comment]
Thank you for opening this pull request.

This is a standard message notifying you that we've reviewed your pull request and have decided not to merge it. We would welcome future pull requests from you.

Thank you and happy coding.

**Comment by AustinThornley** [comment]
Hello,

Is there a reason why this was closed and not merged?

**Comment by ieahleen** [comment]
You have not added any content with this PR

**Comment by AustinThornley** [comment]
Hello, sorry I am new to this. But I did add a semicolon in the code snippet that was needed.

**Pull request closed without merging**
