### PR TITLE
different casing of "sentence" variable (Update declare-a-read-only-v…

### PR DESCRIPTION
**Pull request by Harkirat155**
…ariable-with-the-const-keyword.english.md)

"sentence" variable is cased differently in solution and challenge seed, resulting in an error even for the current implementation.

- [ ] I have read [freeCodeCamp's contribution guidelines](https://github.com/freeCodeCamp/freeCodeCamp/blob/master/CONTRIBUTING.md).
- [ ] My pull request has a descriptive title (not a vague title like `Update index.md`)
- [ ] My pull request targets the `master` branch of freeCodeCamp.
- [ ] None of my changes are plagiarized from another source without proper attribution.
- [ ] All the files I changed are in the same world language (for example: only English changes, or only Chinese changes, etc.)
- [ ] My changes do not use shortened URLs or affiliate links.

Closes #XXXXX

### CODE REVIEW

**Comment by RandellDawson** [comment]
@Manish-Giri What do you think about this PR?

**Comment by Manish-Giri** [comment]
@RandellDawson I think the idea is right, the challenge does indeed not pass if you try to use the default lowercase `sentence` variable in the seed.

However, instead of updating the **description**, **challenge seed** and **tests** to match a lowercase `sentence`, it's probably better to just update the challenge seed to an uppercase `SENTENCE`.

Along with requiring minimal changes, this would also follow the convention described in the challenge - 

> A common practice when naming constants is to use all uppercase letters, with words separated by an underscore.

The tests and challenge description are already in place to handle `SENTENCE` correctly.

**Comment by thecodingaviator** [comment]
I agree with @Manish-Giri , we should just update the seed

**Comment by RandellDawson** [comment]
@Manish-Giri, @thecodingaviator I read through the original challenge description again today and honestly can not see why anything needs to change.  The challenge description already states:
>A common practice when naming constants is to use all uppercase letters, with words separated by an underscore.

The existing instructions are clear to me they expect the user to change `sentence` to `SENTENCE` since it   states "Also, rename variables declared with `const` to conform to common practices, meaning constants should be in all caps".  In this case, `sentence` is meant to be a constant so it will be declared with `const` and it will need to be in all uppercase letters as `SENTENCE`.

I say the existing challenge seed, solution, and description/instructions do not need to change and this PR should be closed.

**Comment by thecodingaviator** [comment]
You're right actually, on second look, it looks like the challenge is just fine. I suggest we close the PR too.

**Comment by Manish-Giri** [comment]
@RandellDawson True. The existing test cases on the left already make it clear that `SENTENCE` is to be used.

PR can be closed.

**Comment by RandellDawson** [comment]
@Harkirat155 Per the discussion above, we are closing this PR.

We would welcome future pull requests from you.

Thank you and happy coding.

**Pull request closed without merging**
