### PR TITLE
fix(curriculum): remove unnecessary `*/` from description of Basic JavaScript: Delete Properties from a JavaScript Object

### PR DESCRIPTION
**Pull request by cdadityang**
Checklist:

- [x] I have read [freeCodeCamp's contribution guidelines](https://contribute.freecodecamp.org).
- [x] My pull request has a descriptive title (not a vague title like `Update index.md`)
- [x] My pull request targets the `master` branch of freeCodeCamp.
- [x] All the files I changed are in the same world language, for example: only English changes, or only Chinese changes, etc.

Closes NA

In the lesson at https://www.freecodecamp.org/learn/javascript-algorithms-and-data-structures/basic-javascript/delete-properties-from-a-javascript-object , there is unnecessay `*/` code line at the last.

image

This PR removes this line.

### CODE REVIEW

**Review by moT01 — APPROVED** [review]
LGTM @cdadityang 🎉

**Review by ShaunSHamilton — APPROVED** [review]
LGTM 👍

**Review by moT01 — APPROVED** [review]
🎉 Congratulations on your first contribution to freeCodeCamp @cdadityang 🎉

**Comment by cdadityang** [comment]
@moT01 Thank you so much...

**Pull request merged**
