### PR TITLE
chore(.github): optimise workflow usage

### PR DESCRIPTION
**Pull request by ShaunSHamilton**
Prevents multiple of the same job on the same pull request

### Before this PR:
1. Open PR 100
    - Action 1 starts to run or is queued
2. Immediately push new commit to PR 100
    - Action 2 starts to run or is queued
3. Action 1 finishes
4. Action 2 finishes

### After this PR:

1. Open PR 100
    - Action 1 starts to run or is queued
2. Immediately push new commit to PR 100
    - Action 1 is cancelled [^1]
    - Action 2 starts to run or is queued
3. Action 2 finishes

[^1]: Technically, action 2 starts before action 1 is cancelled, because action 2 causes action 1 to cancel. https://docs.github.com/en/actions/writing-workflows/choosing-what-your-workflow-does/control-the-concurrency-of-workflows-and-jobs

### CODE REVIEW

**Comment by ShaunSHamilton** [comment]
Closing, because something weird is happening with the actions.

**Comment by ShaunSHamilton** [comment]
Turns out, workflows with the same name cause this to freak out.

**Review by raisedadead — APPROVED** [review]

**Comment by raisedadead** [comment]
MERGE THIS NOW!

**Review by raisedadead — APPROVED** [review]

**Comment by raisedadead** [comment]
Okay - Seriously we should add this to all of our GitHub actions.

**Review by majestic-owl448 — APPROVED** [review]

**Pull request merged**
