### PR TITLE
chore(client): migrate Tool-Panel component to ts 

### PR DESCRIPTION
**Pull request by sitek94**
Checklist:

- [x] I have read [freeCodeCamp's contribution guidelines](https://contribute.freecodecamp.org).
- [x] My pull request has a descriptive title (not a vague title like `Update index.md`)
- [x] My pull request targets the `main` branch of freeCodeCamp.
- [x] I have tested these changes either locally on my machine, or GitPod.

Is part of #43778

Migrated Tool-Panel component to TypeScript.

### CODE REVIEW

**Comment by RobertoMSousa** [comment]
The PR looks good but why did you change the file name? Nothing against it, just curious 🙂

**Comment by sitek94** [comment]
> The PR looks good but why did you change the file name? Nothing against it, just curious 🙂

Thanks for taking a look at the PR! 🙏 

In the requirements, I saw the following line:

> Take a look at the Codebase Best Practices - kebab-case file names

And I assumed that the files should be both **lower** and **kebab** case. Of course, if that's not the case (pun intended) I can change it back to `Tool-Panel.tsx` :)

**Review by ojeytonwilliams — CHANGES_REQUESTED** [review]
Cheers, @sitek94. Tiny nitpick aside, this looks good!

**Review by ojeytonwilliams — DISMISSED** [review]
Thanks for the quick update.

LGTM 👍

**Review by EugeneGohh — DISMISSED** [review]

**Comment by sitek94** [comment]
@nhcarrigan, conflicts resolved ✅

**Review by ojeytonwilliams — APPROVED** [review]

**Review by naomi-lgbt — APPROVED** [review]
Looks good to me!

**Pull request merged**
