### PR TITLE
Add test to Counting Cards

### LINKED ISSUE #7728: Wrong solution being accepted
https://www.freecodecamp.com/challenges/counting-cards

For a below test case my code returns "1 Hold" which is wrong.. still my solution is accepted

### My code
var count = 0;

function cc(card) {
  // Only change code below this line
  
  var result = 0;
 if(card >1 && card< 7){
   result = ++count;
   return (result +" "+"Bet");
 }
  
  else if (card >6 && card <10){
     //result = 0;
    if(count>0){
      return count+" Bet";
    }
     return (count +" " +"Hold");
  }else{
     result = --count;
   return (result +" "+"Hold");
  }
   
  // Only change code above this line
}

cc(2); cc(2); cc(10);

### PR DESCRIPTION
**Pull request by BKinahan**
Adds a test to Counting Cards for cases when last drawn card decreases Count but Count is still positive, to address problem discussed in issue closed below.

Closes #7728

### CODE REVIEW

**Comment by BerkeleyTrue** [comment]
Hey @BKinahan do you mind rebasing. We've fixed travis on current staging.

**Comment by alistermada** [comment]
@BKinahan Using the code in  #7728, `cc(2); cc(2); cc("K");` would also return "1 hold" and `cc(10); cc(10); cc(2);` would return "-1 bet".

Perhaps there should be a broader test to check that a positive number is followed by " bet" and a negative number or 0 is followed by " hold".

**Comment by ameymhatre** [comment]
Also a test case for negative score could be added.. for Eg. cc("K") ;cc("K");cc(2) should return -1 hold

**Comment by raisedadead** [comment]
@BKinahan Any thoughts on updating this?

**Comment by BKinahan** [comment]
@raisedadead Not particularly, no. The incorrect outputs mentioned by @alistermada using the code from the original issue don't cause that code to be able to pass the new test case, and I don't believe a broader check for an association between output number's negativity and the betting decision is needed given the current test cases. I'd be happy to take another look if someone can devise code which passes all the test cases (including the new one) with incorrect outputs.

Also @ameymhatre's concern regarding a test case for negative score is already met by three of the original test cases.

If I'm overlooking something obvious here, please let me know.

**Comment by alistermada** [comment]
@BKinahan Ah, my mistake. You're right. Disregard my comments.

**Comment by raisedadead** [comment]
@BKinahan @alistermada Thanks for the clarifications.

**Comment by raisedadead** [comment]
#### :sparkles: :sparkles: **LGTM.** :sparkles: :sparkles: 

Thanks @BKinahan !

**Pull request merged**
