### PR TITLE
chore: cleanup (prettier/git)ignore

### PR DESCRIPTION
**Pull request by ojeytonwilliams**
Checklist:

- [x] I have read and followed the [contribution guidelines](https://contribute.freecodecamp.org).
- [x] I have read and followed the [how to open a pull request guide](https://contribute.freecodecamp.org/#/how-to-open-a-pull-request).
- [x] My pull request targets the `main` branch of freeCodeCamp.
- [x] I have tested these changes either locally on my machine, or GitPod.

### CODE REVIEW

**Review by huyenltnguyen — APPROVED** [review]

**Review by naomi-lgbt — APPROVED** [review]
You make these changes just to watch me suffer, don't you :3

**Comment by ojeytonwilliams** [comment]
@naomi-lgbt in all seriousness, I'm fine with keeping the ignores around if it's causing havoc in your workflows. Just pop them in a "legacy" section and I'll leave them alone. At least for a little bit 👿

**Comment by naomi-lgbt** [comment]
Haha it's only an issue when I'm reviewing PRs based on outdated branches

**Comment by ojeytonwilliams** [comment]
Okay. Well, it's always an option!

**Pull request merged**
