### PR TITLE
chore(tools): update import statement

### PR DESCRIPTION
**Pull request by huyenltnguyen**
Checklist:

- [x] I have read [freeCodeCamp's contribution guidelines](https://contribute.freecodecamp.org).
- [x] My pull request has a descriptive title (not a vague title like `Update index.md`)
- [x] My pull request targets the `main` branch of freeCodeCamp.
- [x] I have tested these changes either locally on my machine, or GitPod.

Addresses the following Storybook warning in the console:

Screen Shot 2022-02-01 at 18 29 07

### CODE REVIEW

**Comment by ojeytonwilliams** [comment]
Silly question, probably, where was the warning?

**Comment by huyenltnguyen** [comment]
Ah sorry, we can reproduce it by running `npm run storybook` and check the browser console of the Storybook tab.

**Review by ojeytonwilliams — APPROVED** [review]
No apology necessary, I just completely missed it :cold_sweat:

**Review by naomi-lgbt — APPROVED** [review]
Looks good to me.

**Pull request merged**
