### PR TITLE
Translation of the "Responsive Web Design Principles" section into pt-br

### PR DESCRIPTION
**Pull request by vkorbes**
#### Pre-Submission Checklist

- [x] Your pull request targets the `staging` branch of freeCodeCamp.
- [x] Branch starts with either `fix/`, `feature/`, or `translate/` (e.g. `fix/signin-issue`)
- [x] You have only one commit (if not, [squash](http://forum.freecodecamp.com/t/how-to-squash-multiple-commits-into-one-with-git/13231) them into one commit).
- [x] All new and existing tests pass the command `npm test`. Use `git commit --amend` to amend any fixes.

#### Type of Change

- [ ] Small bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds new functionality)
- [ ] Breaking change (fix or feature that would change existing functionality)
- [x] Add new translation (feature adding new translations)

#### Checklist:

- [x] Tested changes locally.
- [ ] Closes currently open issue (replace XXXX with an issue no): Closes #XXXX

#### Description

The title is self explanatory. I've translated the "Responsive Web Design Principles" section into Brazilian Portuguese.

This is my first time doing this, let me know if I messed something up :)

### CODE REVIEW

**Review by Greenheart — COMMENTED** [review]
@ellenkorbes My Portuguese is a bit too bad for saying anything about the content, but the format looks good! :smile:

**Review by ghost — COMMENTED** [review]
@ellenkorbes, please get someone else that speaks Brazilian Portuguese to confirm this translation, and then we can merge 😃

**Review by frontendwizard — APPROVED** [review]
LGTM.

**Comment by Greenheart** [comment]
@julianorafael Thanks for the review! I'll get this ready and merge shortly :blush:

There was a merge conflict that I resolved by looking at the current format of [translations of the introduction to freeCodeCamp](https://github.com/freeCodeCamp/freeCodeCamp/blob/6bc82a7d11d698b97f5dac5b57c580e4a9d5a343/seed/challenges/00-getting-started/getting-started.json#L88-L626). Now I just need to squash this to a single commit.

**Comment by atjonathan** [comment]
### **LGTM :+1:**
Thank-you for contributing @ellenkorbes 💪

**Comment by Greenheart** [comment]
@atjonathan I wanted to squash these changes into a single commit before merging, but failed.

I guess it didn't matter then :wink:

**Comment by atjonathan** [comment]
@Greenheart, because you don't have push access to @ellenkorbes's fork, you wouldn't have been able to. You can use the built in pull-request squash function however ❗️

**Comment by Greenheart** [comment]
@atjonathan Yeah I've used it for other projects, but as no one used it here (apparently we like merge commits), I haven't used it yet. Will do if I end up in this situation in the future :smile:

**Pull request merged**
