### PR TITLE
refactor(client): togglebutton's layout from float to flex

### LINKED ISSUE #49459: Refactor the togglebutton from float layout to flex
In the setting page, there are buttons that have svg in them, and these buttons use `float` to position the svg.

image

Although it looks fine in normal layout, it is broken in RTL layout. The position is reverted

image

Here is the CSS file https://github.com/freeCodeCamp/freeCodeCamp/blob/main/client/src/components/helpers/toggle-button.css

And here is the HTML file, if you needed https://github.com/freeCodeCamp/freeCodeCamp/blob/main/client/src/components/helpers/toggle-button.tsx

Refactoring it to flex should fix the weird positioning in the RTL layout.

---

## Additional Context

- Why not Grid?

Browsers has different way of rendering the SVG size with Grid, although I think the `height` and `weight` will render the SVG with the desired look, it may change based on how browser decided how to render SVG in the future. 

If you want to create a grid that works in safarri, firefox and chrome, go for it. 

- Do I need to be mindful of how it looks in the RTL layout?

No, refactoring it to flex is good enough, if there is weird behavior accruing in the RTL layout, I will fix it in another PR.

----

If you would like to fix this issue, please make sure you read [our guidelines for contributing](https://contribute.freecodecamp.org/#/), we prioritize contributors following the instructions in our guides. Join us in [our chat room](https://discord.gg/PRyKn3Vbay) or [the forum](https://forum.freecodecamp.org/c/contributors/3) if you need help contributing, our prolific contributors will guide you through this.

### PR DESCRIPTION
**Pull request by xarcode**
Checklist:

- [x] I have read and followed the [contribution guidelines](https://contribute.freecodecamp.org).
- [x] I have read and followed the [how to open a pull request guide](https://contribute.freecodecamp.org/#/how-to-open-a-pull-request).
- [x] My pull request targets the `main` branch of freeCodeCamp.
- [x] I have tested these changes either locally on my machine, or GitPod.

Closes #49459

image

### CODE REVIEW

**Comment by xarcode** [comment]
Are these changes sufficient? Please let me know if more changes are needed and I will gladly do so.

**Review by Sboonny — COMMENTED** [review]
Thank you, you don't have to worry about RTL. 

---

Code from 53 to 77 can go, because there is no position property that float value can affect.

**Comment by xarcode** [comment]
Alright ! Should I remove the code from lines 53 to 77 and open a new PR? I am a little confused on what else I need to do to get this merged! @Sboonny

**Comment by Sboonny** [comment]
There is no reason to open new PR, unless you want to fix a different issue.

**Comment by xarcode** [comment]
Did as told! Please review these changes and let me know if anything else needs to be done :)

**Review by Sboonny — APPROVED** [review]
#### :sparkles: :tada: **AWESOME!** :tada: :sparkles:

 Hi @xarcode, thanks for this pull request and for contributing to the code-base for the first time. We are looking forward to more contributions from you in the future.

 Cheers & happy contributing!

**Review by ojeytonwilliams — APPROVED** [review]
Thanks, @xarcode, this LGTM :+1:

**Pull request merged**
