### PR TITLE
refactor: replace Col component

### PR DESCRIPTION
**Pull request by Sboonny**
Checklist:

- [x] I have read and followed the [contribution guidelines](https://contribute.freecodecamp.org).
- [x] I have read and followed the [how to open a pull request guide](https://contribute.freecodecamp.org/#/how-to-open-a-pull-request).
- [x] My pull request targets the `main` branch of freeCodeCamp.
- [x] I have tested these changes either locally on my machine, or GitPod.

### CODE REVIEW

**Comment by ahmaxed** [comment]
Screenshot 2023-08-24 at 10 07 16 AM

**Comment by Sboonny** [comment]
I haven't updated the test, because I am in conflict about the donation page. 

it's broken because of misuse of `relative` and `float-left`, but there is no other place that these properties useful for as far as I have seen.

Can I fix it in the client side, adding `flex` and such? because if I fix it in ui-component, I have to add `relative float-left` to specific properties, and it doesn't warn the user of the ui-component that these properties are different from the other ones.

**Comment by ahmaxed** [comment]
from our chat:
Please look into the bootstrap 5 as a reference.
Then decide on doing one of the followings:
1. Alter Col component to make it more comprehensive.
2. Alter the /donate styles to keep the Col component simple.

**Comment by Sboonny** [comment]
The current bootstrap [implementation](https://react-bootstrap.github.io/docs/layout/grid) doesn't align with our future usage of the components, `col` is acting as a way to add certain values for the flex display. Although it looks similar to grid and should act similar to grid, if we move to that direction we will be flex that act as a grid, which remind me of old issue in layout we have.

in hopes to not repeat that issue and in hope to lower the abstraction that will be in the way of the future implementation of the component, I am going to add the styles to donation page.

**Comment by ahmaxed** [comment]
Thanks for the fix, here is what I noticed going through the website:
1) there are no right/left padding for the columns on donate page
2) the picture on donate page does not have sufficient padding on the top

Other than that, this should be good to go.

**Review by ahmaxed — APPROVED** [review]

**Comment by ahmaxed** [comment]
nitpicks:
1) donate page col is wider on small screen in this pr than production.
2) Cols should always be wrapped in a row
3) if the right and left side of the page are wrapped in different columns, there would not be a need for styling the figure directly : .donate-page-wrapper figure.

**Comment by Sboonny** [comment]
> Cols should always be wrapped in a row

I am against adding `Row` when the negative margin isn't needed, for these reasons:

- keep the code modular, so maintainers don't need to check 1 more page, if the `Row` component changes in the ui-component.
- the negative margin cause issue, maybe outline on interactive element or flowing in a page, I don't fully remember to be honest🧓, which I needed to delete the `Row` to fix it.

> if the right and left side of the page are wrapped in different columns, there would not be a need for styling the figure directly : .donate-page-wrapper figure.

we will need to add a `@media` query that adds `display: none` to it, because the padding will still be there.
image

**Comment by ahmaxed** [comment]
To standardize spacing across all pages/layouts, we need to establish a unified usage pattern.
Since we are replicating styles from the bootstrap component library, I suggest following their structure.
Based on their documentation, columns are wrapped in rows that are wrapped in a container. 

I understand that issues might arise from each component's implementation ( negative margin ). That should usually be addressed by changing the styles of the contents of the layout.

Let me know if you need help with the donate page.

**Comment by Sboonny** [comment]
> To standardize spacing across all pages/layouts, we need to establish a unified usage pattern.

The `Row` and `Col` are bad components for this, because `Row` have negative margin that makes people deal with the margin collapse nightmare, and `Col` is using percentage width, so it is annoying to use in flex.

if combined, we will need to add position to make sure the people use it aren't annoyed when using `flex` or `gird`, because `Col` will follow the percentage of the `Row` not the `Container`.

> Since we are replicating styles from the bootstrap component library, I suggest following their structure.
> Based on their documentation, columns are wrapped in rows that are wrapped in a container.

For me ignore it, as ignoring it is the best option for freeCodeCamp, the bootstrap 3 is old and doesn't account for solutions that are currently used in codebase, trying to mimic it will just lead to more unnecessary work for the contributors and maintainers.

And to be fair to bootstrap, they are putting it as an example, I think there is a misunderstanding on your part, they never mention that you have to use it.

> That should usually be addressed by changing the styles of the contents of the layout.
> 
> Let me know if you need help with the donate page.

I can think of multiples way to solve this, my issue isn't the lack of solution, my issue is we are following a concept that force us to come up with a solution without reaping any benefit from it, I can't think of a good reason that the concept "`Col` should always be wrapped in a `Row`" should ever be a rule that freeCodeCamp should follow. 

It would have been more understandable if we are creating something similar to bootstrap 5, which we need the `Row` component because it has `display: flex` on it

**Comment by ahmaxed** [comment]
Thank you for your detailed review. I will incorporate your suggestions either in this, or upcoming PRs.
I have discussed your consideration regarding the donate button with our consultant, and basically we would not know the true effect unless this change is tested and iterated on.

**Comment by ahmaxed** [comment]
Thanks for the detailed explanation. As you have previously stated, the float needs to be set for multiple columns to work in a row.

We do want to keep our implementation persistent with bootstrap for the time being, so I re added the row component to the page again and adjusted the styles for that specific instance for learn's client.

Here are the links to bootstrap's related documentation for our reference: [5.3](https://getbootstrap.com/docs/5.3/layout/grid/#how-it-works), [3.3](https://getbootstrap.com/docs/3.3/css/#grid)

Since you have the most context of the issue, could you please create an issue for adding multi-col functionality when we update our grid system to flexbox or grid right after we move away from react/bootstrap 3?

**Comment by ahmaxed** [comment]
@huyenltnguyen, the component library is somehow block on this. I was wondering if you could give it a look.

**Review by huyenltnguyen — APPROVED** [review]
LGTM overall.

I don't have enough context on the improvement in the implementation of `Col` or the recommended usage (within or not within Row), so I'll trust your judgement here 😄 I have a feeling the `ui-components` library will need to have round of major implementation changes after we have migrated off of Bootstrap.

---
Just a small nit though: We probably should `.trim()` the result of `Col`'s class name concatenation, as it causes empty whitespaces in some places:

https://github.com/Sboonny/freeCodeCamp/blob/5175c42d3302bb9bde00d77e69332388f98650d9/client/src/components/profile/__snapshots__/profile.test.tsx.snap#L172

(There is a [classnames](https://www.npmjs.com/package/classnames) lib that we can use if we don't want to handle the class names manually.)

**Comment by Sboonny** [comment]
> Just a small nit though: We probably should `.trim()` the result of `Col`'s class name concatenation, as it causes empty whitespaces in some places:
> 
> https://github.com/Sboonny/freeCodeCamp/blob/5175c42d3302bb9bde00d77e69332388f98650d9/client/src/components/profile/__snapshots__/profile.test.tsx.snap#L172
> 
> (There is a [classnames](https://www.npmjs.com/package/classnames) lib that we can use if we don't want to handle the class names manually.)

Yeab, we should trim them.

I have been delaying working on this until the modal component is merged, because it's the last component needed for the issue, and we can define a utility helper that compute the classes for every component in one go.

that being said, I may be overthinking delaying it, and if a helper is created, I would happily force the new standard in the following PRs.

About the library, I prefer using [clsx](https://www.npmjs.com/package/clsx), it's a lightweight version of classnames.

**Pull request merged**
