### PR TITLE
feat[client] Adding React Suspense and Lazy loading 

### LINKED ISSUE #49151: Use react suspense to load the element when it's ready, instead of JavaScript
We are using JavaScript to wait for API to be ready, then render some components, this isn't the React way to do things.

Example:

```ts
     if (showLoading) {
        return <Loader fullScreen={true} />;
      }
      return <FourOhFour />;
```

https://github.com/Sboonny/freeCodeCamp/blob/240655ecd4c4ead1906c3c07ba10e4ad28af4622/client/src/client-only-routes/show-profile-or-four-oh-four.tsx#L74-L84?plain=1

```ts
  if (showLoading) {
    return <Loader fullScreen={true} />;
  }
```

https://github.com/Sboonny/freeCodeCamp/blob/240655ecd4c4ead1906c3c07ba10e4ad28af4622/client/src/client-only-routes/show-settings.tsx#L149-L151?plain=1

React provides a better way of doing things, https://beta.reactjs.org/reference/react/Suspense#caveats. we can use this instead to provide a better experience for the campers.

For example, there is two searchbars, one optimized and the other isn't. we can use suspense to display the optimized one, while the other one is loading.

```ts
        <Media minWidth={MAX_MOBILE_WIDTH + 1}>
          <Suspense fallback={<SearchBarOptimized />}>
            <SearchBar />
          </Suspense>
        </Media>
```

Here is branch, if you want to mess with the searchBar https://github.com/Sboonny/freeCodeCamp/tree/lazyload/searchbar

This will result in the searchbar being displayed in homepage, and if it take too long to load it display the optimize one.

---

If we do this we can add `Errorbondary` later one https://github.com/bvaughn/react-error-boundary, to have fault tolerance in our codebase, which will allow us to display 3rd component if the API fails, may display a button for camper that refresh the page or a function that ask the API to rerun.

### PR DESCRIPTION
**Pull request by Vansh-Baghel**
Checklist:

- [x] I have read and followed the [contribution guidelines](https://contribute.freecodecamp.org).
- [x] I have read and followed the [how to open a pull request guide](https://contribute.freecodecamp.org/#/how-to-open-a-pull-request).
- [x] My pull request targets the `main` branch of freeCodeCamp.
- [x] I have tested these changes either locally on my machine, or GitPod.

Closes #49151

* Added Suspense and lazy loading in /show-profile-or-four-oh-four.tsx file.
* Checked other files where loading is used, but didn't find any file where we could replace the Javascript way of handling with React way as everywhere its used as an if condition, and the content which would appear after load is not imported.
* Only import components could be handled as lazy loading IMO using lazy of react.

This is the way its implemented in other files which IMO couldn't be replaced.
image

### CODE REVIEW

**Comment by Vansh-Baghel** [comment]
> Thanks for working on this @Vansh-Baghel 👍 There's a lot of tests failing here - those need to be passing.

Not sure why is that so

**Comment by shynonagons** [comment]
> > Thanks for working on this @Vansh-Baghel 👍 There's a lot of tests failing here - those need to be passing.
> 
> Not sure why is that so

Looks like you need to update some snapshots https://github.com/freeCodeCamp/freeCodeCamp/actions/runs/4755298813/jobs/8449385384?pr=50107#step:9:3211

**Comment by Sboonny** [comment]
@Vansh-Baghel, your current branch is dirty because you didn't create it from main but from spacer branch.

run 
```console
git checkout -b backup/suspense
git checkout suspense
git reset --soft HEAD~<number of commits>
```

disregard the spacer commits and push the suspense commits.

**Comment by Vansh-Baghel** [comment]
Closing this one, and opened a new PR #50117 to avoid the mess.

**Pull request closed without merging**
