### PR TITLE
fix(learn): issue tracker test text error message

### PR DESCRIPTION
**Pull request by scissorsneedfoodtoo**
Checklist:

- [x] I have read [freeCodeCamp's contribution guidelines](https://contribute.freecodecamp.org).
- [x] My pull request has a descriptive title (not a vague title like `Update index.md`)
- [x] My pull request targets the `master` branch of freeCodeCamp.
- [x] All the files I changed are in the same world language, for example: only English changes, or only Chinese changes, etc.

Closes #XXXXX

This PR fixes a minor typo for an error message described in one of the user stories.

Seems like this is already live with the recent updates here: https://github.com/freeCodeCamp/demo-projects/pull/34/files#diff-ac7b9bdd432ec919d1c67080412daf02b852610595c4126ae4623651bf61e0ffR116

### CODE REVIEW

**Review by naomi-lgbt — APPROVED** [review]
LGTM~! 🥳 Nice catch!

**Comment by scissorsneedfoodtoo** [comment]
Thanks for taking a look at this, @nhcarrigan. And I wouldn't have caught this on my own -- actually a support email that came in over the weekend pointed it out :)

**Review by ShaunSHamilton — APPROVED** [review]
This LGTM 👍 

Thanks, for the quick fix, Kris. I will leave for Randell to once-over, and merge

**Review by moT01 — APPROVED** [review]
LGTM 🎉

**Pull request merged**
