### PR TITLE
fix: SASS challenge and code indentation

### LINKED ISSUE #17018: [BETA]: Possible typo in "Sass: Use @if and @else" Lesson.
#### Challenge Name
https://beta.freecodecamp.org/en/challenges/sass/use-if-and-else-to-add-logic-to-your-styles

#### Issue Description
I believe there is a typo that can lead to confusion in the first code block in the lesson:
```
@mixin make-bold($bool) {
  @if $bool == bold { font-weight: bold; }
}
```
I believe `$bool` should be a boolean, for clarity and code legibility, and is probably just a typo.

**Proposed Solution:**
I believe the code block should be rewritten as follows:
```
@mixin make-bold($bool) {
  @if $bool { font-weight: bold; }
}
```

#### Browser Information
* Browser Name, Version: Firefox 59.0.2
* Operating System: Win 8.1, 64-bit
* Mobile, Desktop, or Tablet: Desktop

### PR DESCRIPTION
**Pull request by varunzxzx**
#### Pre-Submission Checklist

- [x] Your pull request targets the `staging` branch of freeCodeCamp.
- [x] Branch starts with either `fix/`, `feature/`, or `translate/` (e.g. `fix/signin-issue`)
- [x] You have only one commit (if not, [squash](http://forum.freecodecamp.org/t/how-to-squash-multiple-commits-into-one-with-git/13231) them into one commit).
- [x] All new and existing tests pass the command `npm test`. Use `git commit --amend` to amend any fixes.

#### Type of Change

- [x] Small bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds new functionality)
- [ ] Breaking change (fix or feature that would change existing functionality)
- [ ] Add new translation (feature adding new translations)

#### Checklist:

- [x] Tested changes locally.
- [x] Addressed currently open issue (replace XXXXX with an issue no in next line)

Closes #17018 

#### Description

Fixed the mistyped block of code. Also, properly indented the block of code.

### CODE REVIEW

**Comment by mstellaluna** [comment]
I am currently working on this PR

**Review by mstellaluna — CHANGES_REQUESTED** [review]
invalid/incomplete SASS code

**Comment by mstellaluna** [comment]
@varunzxzx I have reviewed your PR and suggest the following change(s).
Your proposed solution does not work as you intended it. Your current code will always evaluate to true making no matter what the value of $bool is and will always apply the bold font-weight as it is no longer checking the value of $bool unless it is explicitly set to false. The lesson is to test against a specific case. You can see the behavior in the following codepen: https://codepen.io/mstellaluna/pen/XEyorv?editors=1100

You would either need to:
1) add the value of $bool to the top of the code block such as it appears as the example below:
`
$bool == bold

@mixin make-bold($bool) {
  @if $bool { font-weight: bold; }
}
`
2) Please revert back to the original code which is showing the specific case checking

Thanks !

**Comment by varunzxzx** [comment]
@mstellaluna But, $bool represents a boolean value. This may confuse the user a bit. We can do something like this
```sass
@mixin make-bold($bool) {
  @if $bool == true {
    font-weight: bold;
  }
}
```
Does it makes sense?

**Comment by mstellaluna** [comment]
On hold for secondary review

**Comment by Asjas** [comment]
@varunzxzx The checking of the value of `$bool` to the word `bold` is definitely confusing if `$bool` is to be a boolean. It will either need to check for true or false rather than a word.

Something like this would be easier to read.

```
@mixin make-bold($bool) {
  @if $bool == true { font-weight: bold; }
}

p {
  @include make-bold(true);
}
```

@mstellaluna Can you comment if this makes more sense if it is used as shown above?

**Comment by mstellaluna** [comment]
@Asjas yes that makes more sense. thank you for the secondary review.

**Comment by mstellaluna** [comment]
@varunzxzx Hello, I am approving the changes. Thank you for your contribution. Happy Coding

**Review by mstellaluna — APPROVED** [review]

**Pull request merged**
