### PR TITLE
fix(challenges): Change misleading variable name in example

### LINKED ISSUE #16165: Variable name in challenge description is misleading.
#### Basic JavaScript: Understanding Case Sensitivity in Variables
https://beta.freecodecamp.org/en/challenges/basic-javascript/understanding-case-sensitivity-in-variables

#### Issue Description
In the example code, there is a variable named "thisVariableNameIsTooLong".  If taken literally, this sounds like the variable name is unacceptable due to some character limit.  As this is not the case, I suggest changing the name to "thisVariableNameIsSoLong" to avoid confusion (but maintain the joke).

### PR DESCRIPTION
**Pull request by colinthornton**
#### Pre-Submission Checklist

- [x] Your pull request targets the `staging` branch of freeCodeCamp.
- [x] Branch starts with either `fix/`, `feature/`, or `translate/` (e.g. `fix/signin-issue`)
- [x] You have only one commit (if not, [squash](http://forum.freecodecamp.org/t/how-to-squash-multiple-commits-into-one-with-git/13231) them into one commit).
- [x] All new and existing tests pass the command `npm test`. Use `git commit --amend` to amend any fixes.

#### Type of Change

- [x] Small bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds new functionality)
- [ ] Breaking change (fix or feature that would change existing functionality)
- [ ] Add new translation (feature adding new translations)

#### Checklist:

- [x] Tested changes locally.
- [x] Addressed currently open issue (replace XXXXX with an issue no in next line)

Closes #16165 

#### Description

Changed variable named "thisVariableNameIsTooLong" to "thisVaribaleNameIsSoLong" in the beta challenge "Basic JavaScript: Understanding Case Sensitivity in Variables".

### CODE REVIEW

**Comment by raisedadead** [comment]
Hi @colinthornton 

Thanks a lot for the pull request, looks like you have modified (deleted the package-lock.json, accidentally?).

Checkout your PR branch:
```
git checkout fix/grammer
```
Reset the **FILE** to original state:

```sh
git checkout staging -- package-lock.json
```

This will reset only the file that is mentioned above.

then amend your commit,
```sh
git commit --amend --no-edit 
```

and finally force push
```sh
git push -f
```

This will automatically update this PR.

In future, just add the files that you intend to commit like so:
Example:
```sh
git add  seed/challenges/02-javascript-algorithms-and-data-structures/basic-javascript.json
```
and repeat the same as may times as necessary for any additional files.

**Review by raisedadead — CHANGES_REQUESTED** [review]
Please remove the unintended change from the file.

**Comment by colinthornton** [comment]
@raisedadead Sorry about that, just made the changes.  Thanks for the walkthrough.

**Comment by raisedadead** [comment]
@colinthornton awesome! Nicely done. 

Don't worry about it, we are always happy to help, reach us in the [Contributors Chat room](https://gitter.im/FreeCodeCamp/Contributors), to hang out. Looking forward to more contributions in future.

Happy fixing!

**Review by raisedadead — APPROVED** [review]

**Pull request merged**
