### PR TITLE
fix(curriculum): clarify element in role-playing-game

### LINKED ISSUE #48822: Missing hashtag(s) in step 45 of the new js course (build an rpg)
### Describe the Issue

Step 45 of the new build an rpg in JS course seems to be missing multiple hashtags. For eg: The following seems to be missing a hashtag in front of the word text (the one in backticks).

Now you need to modify your display text. Change the `innerText` of the `text` to be `You enter the store.`.

The word text in backticks seems to be referring to an element whose id is text. So I believe it should use a hashtag as in #text.

If this is correct, then there are multiple places to be fixed in this step. 

### Affected Page

curriculum/challenges/arabic/15-javascript-algorithms-and-data-structures-22/learn-basic-javascript-by-building-a-role-playing-game/62a7bfabe119461eb13ccbd6.md

### Your code

```

```

### Expected behavior

All references to an element whose id is text should be clarified either with a hashtag in front of the id value or by explicitly referring to the text element.

### Screenshots

_No response_

### System

N/A

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by Sriparno08**
Checklist:

- [x] I have read [freeCodeCamp's contribution guidelines](https://contribute.freecodecamp.org).
- [x] My pull request has a descriptive title (not a vague title like `Update index.md`)
- [x] My pull request targets the `main` branch of freeCodeCamp.
- [x] I have tested these changes either locally on my machine, or GitPod.

Closes #48822

I have changed `text` to `#text` in multiple places as it is referring to an element whose id is text.

### CODE REVIEW

**Review by Sembauke — APPROVED** [review]

**Review by Sembauke — DISMISSED** [review]
You made the changes to the Arabic version of the curriculum not the English version. This should be changed.

**Comment by Sriparno08** [comment]
Hey @Sembauke, should I make changes to the English version instead?

**Comment by Sboonny** [comment]
yeab, other files that aren't English should only be changed by translating them in Crowdin 👍.

**Comment by Sriparno08** [comment]
Alright, @Sboonny 👍

**Comment by Sriparno08** [comment]
I have made changes to the English version, maintainers! Have a look!

**Review by ShaunSHamilton — DISMISSED** [review]
Blocking, as the issue has not been triaged.

---

For future reference an issue with the https://github.com/freeCodeCamp/freeCodeCamp/labels/help%20wanted or https://github.com/freeCodeCamp/freeCodeCamp/labels/first%20timers%20only label is open for contribution. The first comprehensive PR created will be reviewed and merged. We typically do not assign issues to anyone other than long-time contributors.

If you would like to contribute, and have not read the contributors docs, please do so here: https://contribute.freecodecamp.org/#/

If you have any issues with contributing, be sure to join us on the [contributors channel](https://discord.com/channels/692816967895220344/715074489422970962), or on the [contributors sub-forum](https://forum.freecodecamp.org/c/contributors/3)

**Comment by Sriparno08** [comment]
Updated the PR! Have a look!

**Review by gikf — APPROVED** [review]
LGTM :+1: 

Addresses suggested change from issue.

**Review by Sboonny — APPROVED** [review]
LGTM 🎉, thank you for your contribution to the page! 👍.

**Comment by Sriparno08** [comment]
Thanks, maintainers 👍

**Pull request merged**
