### PR TITLE
chore(client): typescript migration - utils/frame.js

### LINKED ISSUE #43778: TypeScript Migration
## Co-ordination

As discussed in the last contributors [meeting](https://forum.freecodecamp.org/t/office-hour-contributors-may-13-2021/458257/4) we're looking to migrate our client to TypeScript. 

No files will be assigned

**PRs will be prioritised by quality, then by date opened**

## Guidelines

Take a look at the [Codebase Best Practices](https://contribute.freecodecamp.org/#/codebase-best-practices) - **kebab-case file names**

### Small is beautiful

If a file can be migrated on its own, that's perfect.  That makes the PR incredibly easy to review and minimises the chance we break anything.

### PropTypes can go

None of the components in the client directories are intended to be consumed by JavaScript components - eventually everything will be `tsx`.  With that in mind static type checking should be enough.

### React Guidelines

So, we're all on the same page: https://github.com/typescript-cheatsheets/react#readme has some useful advice.  Mostly the linters will warn us, but this is definitely worth a look.

### un-typed packages

If the package does not come with types attached, then please `npm i` the definitions (if they exist) from DefinitelyTyped.  Usually they're just published as `@types/name-of-package`.

### Do Not Ignore Linting, Unless **Absolutely** Necessary

We hope to leverage the type-safety that comes with TypeScript. So, do not ignore the compiler's warnings/errors. If you are stuck, feel free to reach out for help.

### Keeping Git History

Sometimes changing the file from `<filename>.js` -> `<filename>.tsx?` causes the original file to be deleted, and a new one created, and other times the filename just changes - in terms of Git. Ideally, we want the file history to be preserved.

The best bet at achieving this is to:
1) Rename the file
2) Commit with the flag `--no-verify` to prevent husky from complaining about the errors
3) Refactor to TS for migration, in a separate commit.

**Note:** _Editors like VSCode are still likely to show you the file has been deleted and a new one created. If you use the CLI to `git add .`, then VSCode will show the file as renamed in stage_

### Tests are running

We will not be merging any PRs with failing tests.

### Files that should not be migrated (yet)

- `gatsby-node.js`
- `gatsby-config.js` and related
- `redux/*`

To finish migrating the client, we would need additional tooling to handle gatsby-config, gatsby-node and files they import. This could either be an extra tsc compilation step or potentially via ts-node. However, I'm not sure if ts-node would integrate nicely with gatsby develop or gatsby build, so the compilation approach is probably easier.

Before going ahead with this, we should profile gatsby develop and gatsby build to make sure that the time to develop and build the site do not increase too much.

### More guidelines may get added

As we do this, chances are we'll revise the approach.  Any thoughts/comments/critiques are welcome, but I wanted to keep this straightforward for now.

**List of Files To Migrate**

- [ ] /client/src/templates/Challenges/utils/worker-executor.js
- [ ] /client/src/templates/Challenges/utils/worker-executor.test.js
- [ ] /client/src/templates/Challenges/rechallenge/transformers.js
- [ ] /client/src/\_\_mocks\_\_/react-i18next.js

### PR DESCRIPTION
**Pull request by raditotev**
Checklist:

- [x] I have read [freeCodeCamp's contribution guidelines](https://contribute.freecodecamp.org).
- [x] My pull request has a descriptive title (not a vague title like `Update index.md`)
- [x] My pull request targets the `main` branch of freeCodeCamp.
- [x] I have tested these changes either locally on my machine, or GitPod.

Closes #43778

### CODE REVIEW

**Comment by raditotev** [comment]
Apologies for not being able to keep the git history of the file. I have followed the steps but I have missed the point saying changed files should be added from the cli and not from VS code.

**Comment by raditotev** [comment]
Tests are failing with this error. I have checked type definitions and the `tsconfig` configuration and everything seems to be as it should be. I don't have a clue as to what the problem might be.
```
Error: Cannot find module './frame'
Require stack:
- /Users/radi.totev/Projects/freeCodeCamp/client/src/templates/Challenges/utils/build.js
- /Users/radi.totev/Projects/freeCodeCamp/curriculum/test/test-challenges.js
    at Function.Module._resolveFilename (node:internal/modules/cjs/loader:933:15)
    at Function.Module._load (node:internal/modules/cjs/loader:778:27)
    at Function.Module._load (/Users/radi.totev/Projects/freeCodeCamp/node_modules/mock-require/index.js:30:22)
    at Module.require (node:internal/modules/cjs/loader:1005:19)
    at require (node:internal/modules/cjs/helpers:102:18)
    at Object.<anonymous> (/Users/radi.totev/Projects/freeCodeCamp/client/src/templates/Challenges/utils/build.js:6:1)
    at Module._compile (node:internal/modules/cjs/loader:1103:14)
    at Module._compile (/Users/radi.totev/Projects/freeCodeCamp/node_modules/pirates/lib/index.js:136:24)
    at Module._extensions..js (node:internal/modules/cjs/loader:1155:10)
    at Object.newLoader [as .js] (/Users/radi.totev/Projects/freeCodeCamp/node_modules/pirates/lib/index.js:141:7)
    at Module.load (node:internal/modules/cjs/loader:981:32)
    at Function.Module._load (node:internal/modules/cjs/loader:822:12)
    at Function.Module._load (/Users/radi.totev/Projects/freeCodeCamp/node_modules/mock-require/index.js:30:22)
    at Module.require (node:internal/modules/cjs/loader:1005:19)
    at require (node:internal/modules/cjs/helpers:102:18)
    at Object.<anonymous> (/Users/radi.totev/Projects/freeCodeCamp/curriculum/test/test-challenges.js:32:5)
    at Module._compile (node:internal/modules/cjs/loader:1103:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1155:10)
    at Module.load (node:internal/modules/cjs/loader:981:32)
    at Function.Module._load (node:internal/modules/cjs/loader:822:12)
    at ModuleWrap.<anonymous> (node:internal/modules/esm/translators:168:29)
    at ModuleJob.run (node:internal/modules/esm/module_job:195:25)
    at async Promise.all (index 0)
    at ESMLoader.import (node:internal/modules/esm/loader:337:24)
    at importModuleDynamicallyWrapper (node:internal/vm/module:437:15)
    at formattedImport (/Users/radi.totev/Projects/freeCodeCamp/node_modules/mocha/lib/nodejs/esm-utils.js:7:14)
    at Object.exports.requireOrImport (/Users/radi.totev/Projects/freeCodeCamp/node_modules/mocha/lib/nodejs/esm-utils.js:48:32)
    at Object.exports.loadFilesAsync (/Users/radi.totev/Projects/freeCodeCamp/node_modules/mocha/lib/nodejs/esm-utils.js:103:20)
    at singleRun (/Users/radi.totev/Projects/freeCodeCamp/node_modules/mocha/lib/cli/run-helpers.js:125:3)
    at Object.exports.handler (/Users/radi.totev/Projects/freeCodeCamp/node_modules/mocha/lib/cli/run.js:374:5)
```

**Comment by ojeytonwilliams** [comment]
The issue is that frame is used in two contexts, the client and the tests.  While the client can parse TypeScript, the tests are just run in node, so can't.  

Ideally we should migrate `test-challenges.js` to TS, but that's a long job.  In the mean time we have two options:

1. Move frame out of client into utils, so that it gets compiled into JS
2. Run mocha through ts-node

Neither is ideal, but 2. seems preferable, because frame.ts really does belong in the client and utils seems like a confusing place to put it.

So, I'd recommend trying replacing the current curriculum test script with `ts-node ../node_modules/mocha/bin/mocha --delay --exit --reporter progress --bail` and seeing how that goes!

**Comment by raditotev** [comment]
@ojeytonwilliams thanks for your help 👍 . I've tested suggested script and it worked fine locally. I'll push the changes now.

**Review by ojeytonwilliams — APPROVED** [review]
Really nice job @raditotev. This looks great!

**Review by Sembauke — APPROVED** [review]

**Pull request merged**
