### PR TITLE
feat(curriculum): localStorage and CRUD Quiz

### LINKED ISSUE #56213: [HACKTOBERFEST 2024] - localStorage and CRUD Quiz
> [!IMPORTANT]
> This issue is part of our 2024 Hacktoberfest initiative. If you are interested in working on this issue, refer to our [top-level tasks](https://github.com/freeCodeCamp/freeCodeCamp/issues/56170) to see if this issue is claimed, or to claim it if it is not.

This issue is to create the localStorage and CRUD quiz.

The file you should be working on is found in `/curriculum/challenges/english/25-front-end-development/quiz-localstorage-and-crud`.

**All quiz questions need to relate to one of these topics:**

- What is CRUD, how do Create, Read, Update, Delete work
- localStorage and Web Storage API
- sessionStorage
- JSON and property access
- JSON.parse() and JSON.stringify()
- cookies
- cache API
- client-side storage negative patterns (e.g. tracking/fingerprinting)
- using cookies to store arbitrary data
- IndexedDB
- Cache/Service workers and Progressive Web Apps

> [!CAUTION]
> Questions which do not fall under these topics will be rejected.

You are welcome to include code blocks in your questions, but please keep them short (four lines or less).

Please do NOT open a pull request until you have completed all questions. Your quiz should have **exactly 20 questions**.

### PR DESCRIPTION
**Pull request by AaryanProthi**
Checklist:

- [x] I have read and followed the [contribution guidelines](https://contribute.freecodecamp.org).
- [x] I have read and followed the [how to open a pull request guide](https://contribute.freecodecamp.org/how-to-open-a-pull-request/).
- [x] My pull request targets the `main` branch of freeCodeCamp.
- [x] I have tested these changes either locally on my machine, or GitPod.

Closes #56213

### CODE REVIEW

**Review by naomi-lgbt — APPROVED** [review]
This looks great! Nice job!

**Comment by AaryanProthi** [comment]
Thank you so much @naomi-lgbt, means a lot!

**Review by zairahira — APPROVED** [review]

**Comment by zairahira** [comment]
Thank you for your contribution @AaryanProthi 🎉

**Comment by AaryanProthi** [comment]
Thank you @zairahira, I finally have an open source contribution 🥳

**Pull request merged**
