### PR TITLE
feat: split odin project block in two

### PR DESCRIPTION
**Pull request by ojeytonwilliams**
- feat: split odin project block into two blocks
- refactor: remove redundant isOdinProject checks
- fix: revert checkbox outline changes

Checklist:

- [x] I have read and followed the [contribution guidelines](https://contribute.freecodecamp.org).
- [x] I have read and followed the [how to open a pull request guide](https://contribute.freecodecamp.org/#/how-to-open-a-pull-request).
- [x] My pull request targets the `main` branch of freeCodeCamp.
- [x] I have tested these changes either locally on my machine, or GitPod.

Since the Odin project has both practice challenges and full projects it makes sense to keep them separate. This also removes the need for a special case when deciding if the block should be collapsible.

The outline change is a little out of scope, but an extra PR for a single css change seemed excessive.  @Sembauke this isn't the prettiest, but I think it's important that keyboard users can keep track of which element has focus.

### CODE REVIEW

**Comment by moT01** [comment]
I glanced at TOP curriculum when looking at the other PR a little - I may be wrong, but it seemed like they have projects scattered throughout their curriculum similar to our new RWD. So I'm wondering if each project should be its own block and we can display them more like we have our RWD.

**Comment by Sembauke** [comment]
Yeah I will be contacting Quincy if it makes sense to create a new superblock for this.

**Comment by moT01** [comment]
When I look at [this part of their site,](https://www.theodinproject.com/paths/foundations/courses/foundations) it looks like you've done the whole `HTML Foundations` section, is that correct @Sembauke? What else are we planning on doing of theirs? I'm guessing we want to at least do the CSS and JS parts on that page. Is there more than that? It looks like there's a `Full Stack JavaScript` area we may want to do some of as well - not sure.

I'm going to double-down on the idea that each project needs to be its own block since the projects are scattered, like I mentioned. This layout looks quite similar to Ed's math stuff that I may need to create some layouts for. Perhaps we can pair up a little and come up with some new map layouts.

And it does kind of feel like this should be it's own superblock. It's really not "coding interview prep", there's a lot of foundational stuff - and it's split up nicely to have blocks of `HTML Foundations`, `CSS Foundations`, etc.

**Comment by Sembauke** [comment]
Hey @moT01 

I got permission from Quincy to make it it's own superblock. Which we will be doing in an other pr than this one.

Talking about the courses, I am planning the CSS part of the Foundation course right now. I plan to do the rest of the courses like the Full stack javascript.

**Review by Sembauke — APPROVED** [review]

**Comment by ojeytonwilliams** [comment]
Thanks for the fix, @Sembauke

Not that it matter for this PR, but isn't `HTML-CSS` a better help category? At least for the lessons you've added so far.

**Comment by Sembauke** [comment]
Yeah for this block it makes more sense for HTML and CSS. You can change that if you want.

**Review by scissorsneedfoodtoo — APPROVED** [review]
Everything LGTM 👍 

This looks much better broken up into separate blocks, and will be even better once all this content is in its own superblock to control the order of projects like Tom mentioned.

**Pull request merged**
