### PR TITLE
docs: Add styling syntax for challenge solutions in Styling Guide for the guide

### LINKED ISSUE #35453: The hint and solution articles for curriculum challenges need some guidelines
The purpose of this issue is to brainstorm some ways we could simplify the structure of the Guide articles in the `certifications` folder and recommend some basic guidelines which should be followed, so contributors understand what qualifies as an "acceptable" change/addition to these specific articles.  These articles are what a camper sees when clicking on the `Get a Hint` button on each challenge, so I feel it is important the camper's experience when viewing the articles is consistent across all of them.

Below are what I consider the minimum requirements for such a Guide article:

* Two headers (Hints and Solutions)
* For Hints section, there can be zero up to 3-5 hints maximum
* Move away from classifying solutions using subjective terms of Basic, Intermediate, and Advanced.  Instead, the solutions would display the solution's Time Complexity and Space Complexity.  As far as order is concerned, we can sort them in terms of Time Complexity
* Where multiple solutions can exist (i.e. algorithm challenges), only allow a max of 2-3 solutions within the same Time Complexity/Space Complexity classification.  This will prevent the article from showing the same basic algorithm but only differing in syntax or some logic order (i.e using higher order functions instead of for or while loops). 
* There should be as few images as possible unless they are critical to a hint or solution explanation.  Currently, the current design has too many icons and distracts from the content.
* All solutions should be full working solutions and include all Seed Code, so that a camper could simply copy/paste entire solution into editor and see it pass all tests. A nice to have would be to put each solution in a Disclosure Summary element like below so the solutions are hidden upon entering the page in case a user just wants a hint and not see the full solution right away.  For example, the following syntax:
````html

<details><summary>Example #1 (Click to Unhide)</summary>

```js
function myFunc() {
  console.log('Hello World!');
}
```

</details>
````
would produce the following effect:

<details><summary>Example &#35;1 (Click to Unhide)</summary>

```js
function myFunc() {
  console.log('Hello World!');
}
```

</details>
<br>

* Remove all links to replt.it, Codepen, jsFiddle, etc. as the camper can always copy/paste the solution into the FCC code editor to see the code works.
* Make code explanations optional.  Maybe a valid solution is enough and then if others want to make improvements and add code explanations in other PRs, that would be fine too. 
---
I think the above points gets us started.  These are just my opinions based on reviewing hundreds of PRs concerning changes to the challenge solutions in this hint section.  Would like to hear from mods and contributors on this issue.

### PR DESCRIPTION
**Pull request by thecodingaviator**
- [x] I have read [freeCodeCamp's contribution guidelines](https://github.com/freeCodeCamp/freeCodeCamp/blob/master/CONTRIBUTING.md).
- [x] My pull request has a descriptive title (not a vague title like `Update index.md`)
- [x] My pull request targets the `master` branch of freeCodeCamp.
- [x] None of my changes are plagiarized from another source without proper attribution.
- [x] All the files I changed are in the same world language (for example: only English changes, or only Chinese changes, etc.)
- [x] My changes do not use shortened URLs or affiliate links.
- [x] Does what it says on the label

Closes #35453

### CODE REVIEW

**Comment by RandellDawson** [comment]
@thecodingaviator Based on what I originally proposed, we want the solutions to be hidden by using summary/details blocks.  I propose instead of:
````
<section id='hints'>
  <div class='hint'>
    Hint goes here
  </div>
  <div class='hint'>
    Hint goes here
  </div>
</section>

<section id='solutions'>
  <div class='solution'>
    ```js
    function myFunc() {
      console.log('Hello World!');
    }
    ```
    #### Code Explanation
    Code explanation goes here
  </div>
</section>
````
you do show it as the following.  Notice I am not indenting the code sections.  We want the code to be as far to the left as possible.  Also, I think we keep it as simple as possible structure-wise and not worry about having the `section` and `div` elements.  Since all of this is moving to the forum anyway, it will be easier to manage without the extra html elements.
````
# Challenge Name Goes Here

## Hints

### Hint #1
Hint goes here

###  Hint #2
Hint goes here

## Solutions

<details><summary>Solution #1 (Click to Unhide)</summary>

```js
function myFunc() {
  console.log('Hello World!');
}
```

#### Code Explanation
* Code explanation goes here
* Code explanation goes here

#### Relevant Links
* [Link Text](link_url_goes_here)
* [Link Text](link_url_goes_here)

</details>

<details><summary>Solution #2 (Click to Unhide)</summary>

```js
function myFunc() {
  console.log('Hello World!');
}
```

#### Code Explanation
* Code explanation goes here
* Code explanation goes here

#### Relevant Links
* [Link Text](link_url_goes_here)
* [Link Text](link_url_goes_here)

</details>
````
Using my proposal above, these articles would look like below:

# Challenge Name Goes Here

## Hints

### Hint #1
Hint goes here

###  Hint #2
Hint goes here

## Solutions

<details><summary>Solution #1 (Click to Unhide)</summary>

```js
function myFunc() {
  console.log('Hello World!');
}
```

#### Code Explanation
* Code explanation goes here
* Code explanation goes here

#### Relevant Links
* [Link Text](link_url_goes_here)
* [Link Text](link_url_goes_here)

</details>

<details><summary>Solution #2 (Click to Unhide)</summary>

```js
function myFunc() {
  console.log('Hello World!');
}
```

#### Code Explanation
* Code explanation goes here
* Code explanation goes here

#### Relevant Links
* [Link Text](link_url_goes_here)
* [Link Text](link_url_goes_here)

</details>

**Comment by thecodingaviator** [comment]
@RandellDawson better?

**Comment by ojeytonwilliams** [comment]
@RandellDawson, even though the guide's back on the forum, this is still useful, isn't it?

**Comment by ojeytonwilliams** [comment]
My thinking was just that this would still be relevant as discourse uses Markdown.  Are there gotchas that I'm missing?

Regardless, I entirely agree that the docs need to reflect the new state of the guide!

**Comment by thecodingaviator** [comment]
@RandellDawson like this?

**Comment by thecodingaviator** [comment]
Closing in favour of #36735 and #36816

**Comment by RandellDawson** [comment]
@thecodingaviator @raisedadead I think the changes here should somehow be incorporated into https://github.com/freeCodeCamp/freeCodeCamp/pull/36816, because it outlines what the template should look like for the hints/solutions forum topics.  In PR #36816, these changes would appear somewhere in the `Curriculum Challenge Hints and Solutions` section of the `docs/how-to-work-on-coding-challenges.md` file.

**Comment by RandellDawson** [comment]
I have pushed some changes to #36816 which incorporate the changes that were on this PR.

**Pull request closed without merging**
