### PR TITLE
fix(curriculum): Update title and text of rest elements challenge

### LINKED ISSUE #47473: Update title and text from rest parameter to rest property (or element)
### Describe the Issue

A rest parameter would involve parameters.

The MDN article on [rest parameter](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Functions/rest_parameters) only has function parameter examples and it links to the function definition part of the specs. The only instance I can find of the words "rest parameter" in the specs is under the [Parameter Lists](https://tc39.es/ecma262/multipage/ecmascript-language-functions-and-classes.html#sec-parameter-lists) section.

MDN calls it [a rest property](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Operators/Destructuring_assignment#rest_property) when `...rest` is used with a destructuring assignment.

The specs do seem to have two versions of it if I read it correctly, the `AssignmentRestElement` used with arrays and the `AssignmentRestProperty` used with objects.

[13.15.5.2 Runtime Semantics: DestructuringAssignmentEvaluation](https://tc39.es/ecma262/multipage/ecmascript-language-expressions.html#sec-runtime-semantics-destructuringassignmentevaluation)

```
ObjectAssignmentPattern : { AssignmentPropertyList , AssignmentRestProperty }

ArrayAssignmentPattern : [ AssignmentElementList , Elision AssignmentRestElement ]
```

While "rest element" might be more correct with an array I don't think using "rest property" for both arrays and objects as MDN does is the end of the world.

### Affected Page

https://www.freecodecamp.org/learn/javascript-algorithms-and-data-structures/es6/use-destructuring-assignment-with-the-rest-parameter-to-reassign-array-elements

### Your code

```
const [one, two, ...restElement] = [1, 2, 3, 4, 5];

const { name, age, ...restProperty } = {
  name: 'John',
  age: 30,
  email: 'example@john.com',
  address: 'Sesame Street',
};
```

### Expected behavior

The correct technical definition should be used.

### Screenshots

_No response_

### System

- Device: [e.g. iPhone 6, Laptop]
- OS: [e.g. iOS 14, Windows 10, Ubuntu 20.04]
- Browser: [e.g. Chrome, Safari]
- Version: [e.g. 22]

### Additional context

This PR https://github.com/freeCodeCamp/freeCodeCamp/pull/35496 changed it from rest operator to rest parameter.

### PR DESCRIPTION
**Pull request by roygav**
Checklist:

- [x] I have read [freeCodeCamp's contribution guidelines](https://contribute.freecodecamp.org).
- [x] My pull request has a descriptive title (not a vague title like `Update index.md`)
- [x] My pull request targets the `main` branch of freeCodeCamp.
- [x] I have tested these changes either locally on my machine, or GitPod.

Closes #47473

### CODE REVIEW

**Comment by raisedadead** [comment]
We are officially on Node.js 18 now. We have changed the merge requirements accordingly.

You will need to rebase this PR against the main branch OR Click the "Update branch" button to get the new checks going.

Thanks for your contribution.

**Comment by roygav** [comment]
Thanks @raisedadead. Updated.

**Review by naomi-lgbt — APPROVED** [review]
banger pr, thanks for contributing!

**Review by Sembauke — APPROVED** [review]

**Comment by Sembauke** [comment]
Hi @roygav,
Congrats on your first pull request (PR)! 🎉

Thank you for your contribution to the page! 👍
We are happy to accept these changes and look forward to future contributions. 📝

**Pull request merged**
