### PR TITLE
fix(curriculum): clarify instructions for accessibility-quiz step-57

### LINKED ISSUE #48743: Accessibility Quiz Step 57 instructions not clear
### Describe the Issue

The only way to pass this step is to create a new ruleset that targets both `.info input` and `.info label` and add the `display` property to that new ruleset. But the instructions do not make this clear and the alternative solution of adding the `display` property separately to the existing `.info input` and `.info label` rulesets is being rejected. 

Yes, the hint does explain that a new ruleset should be created, but I think this should be made clear in the instructions since I think a lot of people are going to assume that they should just use the existing rulesets. 

### Affected Page

https://www.freecodecamp.org/learn/2022/responsive-web-design/learn-accessibility-by-building-a-quiz/step-57

### Your code

```
.info input {
  width: 50%;
  text-align: left;
  display: inline-block;
}

.info label {
  width: 10%;
  min-width: 55px;
  display: inline-block;
  text-align: right;
}
```

This does not pass the step even though it accomplishes the goal of the step. 

### Expected behavior

Rewrite the instructions to make it clear that a new ruleset targeting both elements should be created.

> To align the input boxes with each other, create a new ruleset that targets all `input` and `label` elements within an `.info` element and set the `display` property to `inline-block`.

Or

> To align the input boxes with each other, set the `display` property to `inline-block` for all `input` and `label` elements within an `.info` element by creating one new ruleset.

### Screenshots

_No response_

### System

N/A

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by spiritanand**
Checklist:

- [x] I have read and followed the [contribution guidelines](https://contribute.freecodecamp.org).
- [x] I have read and followed the [how to open a pull request guide](https://contribute.freecodecamp.org/#/how-to-open-a-pull-request).
- [x] My pull request targets the `main` branch of freeCodeCamp.
- [x] I have tested these changes either locally on my machine, or GitPod.

Closes #48743

I have made the description more clear by explicitly saying campers to create a new ruleset.

### CODE REVIEW

**Comment by spiritanand** [comment]
hey maintainers, what went wrong with my code? did i make a mistake?

**Comment by ShaunSHamilton** [comment]
> hey maintainers, what went wrong with my code? did i make a mistake?

Why do you ask? This PR needs to be reviewed by maintainers of the repository, before it can be merged.

**Review by ShaunSHamilton — APPROVED** [review]
This LGTM 👍 

Thank you for taking the time to contribute 🚀

**Comment by spiritanand** [comment]
I saw that a cypress test failed. I was unable to understand what went wrong.

**Comment by ShaunSHamilton** [comment]
> I saw that a cypress test failed. I was unable to understand what went wrong.

That was an external error - connection error with NPM:

<details>
  <summary>Error</summary>

```bash
npm ERR! code FETCH_ERROR
npm ERR! errno FETCH_ERROR
npm ERR! invalid json response body at https://registry.npmjs.org/type-fest reason: Invalid response body while trying to fetch https://registry.npmjs.org/type-fest: aborted

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/runner/.npm/_logs/2023-01-30T11_28_52_040Z-debug-0.log
Error: The process '/opt/hostedtoolcache/node/18.13.0/x64/bin/npm' failed with exit code 1
```

</details>

No need to worry. Hope this clarifies 🙂

**Review by Sboonny — APPROVED** [review]
#### :sparkles: :tada: **AWESOME!** :tada: :sparkles:

 Hi @spiritanand, thanks for this pull request and for contributing to the code-base for the first time. We are looking forward to more contributions from you in the future.

 Cheers & happy contributing!

**Pull request merged**
