### PR TITLE
fix: swap out raw HTML syntax for semantic/idiomatic markdown

### PR DESCRIPTION
**Pull request by lionel-rowe**
Per this: https://www.freecodecamp.org/forum/t/forum-suggestion-unformatted-code-warning/134857/24 (conflict with unformatted code detector theme component).

`<code>` tags are not the semantically/idiomatically correct way to format code on Discourse. For example, `<code><span></span></code>` renders as that exact HTML, when the intention was almost certainly to render `<code>&lt;span&gt;&lt;/span&gt;</code>` instead.

- [x] I have read [freeCodeCamp's contribution guidelines](https://github.com/freeCodeCamp/freeCodeCamp/blob/master/CONTRIBUTING.md).
- [x] My pull request has a descriptive title (not a vague title like `Update index.md`)
- [x] My pull request targets the `master` branch of freeCodeCamp.
- [x] None of my changes are plagiarized from another source without proper attribution.
- [x] All the files I changed are in the same world language (for example: only English changes, or only Chinese changes, etc.)
- [x] My changes do not use shortened URLs or affiliate links.

### CODE REVIEW

**Comment by raisedadead** [comment]
Hi @lionel-rowe thanks for this PR. 

This fix also has to be made against our `production-legacy-2018` as a hotfix, to resolve the issue on the current platform. The `master` branch is our upcoming version of freeCodeCamp. 

Can you please open the fix against the `production-legacy-2018` as well, if its all the same?

We would still need this PR for master as well, so thanks for working on this.

**Comment by lionel-rowe** [comment]
@raisedadead The corresponding file doesn't exist on `production-legacy-2018`, though it does exist on `production-current`. Should I open this against `production-current`?

**Comment by raisedadead** [comment]
Hi @lionel-rowe apologies, my bad. I failed to point that our production learn app is still on a different repo. To be precise this file here: https://github.com/freeCodeCamp/learn/blob/master/src/templates/Challenges/redux/create-question-epic.js

Thanks for your PR. Can you possibly make the change there. I will have this deployed to fix the issue on the forum.

**Comment by lionel-rowe** [comment]
The corresponding PR is here: https://github.com/freeCodeCamp/learn/pull/327

Opened against `master` in that repo, as it does't seem to have a `production-legacy-2018` branch. Should I also open against `next`?

**Comment by raisedadead** [comment]
Nope, you have made the PR on the correct branch. And sorry about the confusion with the branch names, I promise all this to become more streamlined once we release the mono-repo. Thanks for the PRs.

**Comment by raisedadead** [comment]
I just merged you production PR. It should be live in about ~30 mins of this comment. Please test it out and let me know how it goes. Thanks once again.

**Comment by lionel-rowe** [comment]
Yep, it's live and everything working correctly now. :grin:

**Review by raisedadead — APPROVED** [review]
#### :sparkles: :sparkles: **LGTM.** :sparkles: :sparkles: 

Thanks @lionel-rowe 

Happy Contributing!

**Pull request merged**
