### PR TITLE
Changed message on user not found when giving brownie points

### PR DESCRIPTION
**Pull request by ghost**
#### Pre-Submission Checklist
- [x] Your pull request targets the `staging` branch of FreeCodeCamp.
- [x] Branch starts with either `fix/`, `feature/`, or `translate/` (e.g. `fix/signin-issue`)
- [x] You have only one commit (if not, [squash](https://github.com/FreeCodeCamp/FreeCodeCamp/wiki/Git-Squash) them into one commit).
- [x] All new and existing tests pass the command `npm run test-challenges`. Use `git commit --amend` to amend any fixes.
#### Type of Change

- [x] Small bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds new functionality)
- [ ] Breaking change (fix or feature that would change existing functionality)
- [ ] Add new translation (feature adding new translations)
#### Checklist:

- [ ] Tested changes locally.
- [x] Closes currently open issue (replace XXXX with an issue no): Closes https://github.com/FreeCodeCamp/camperbot/issues/26

### CODE REVIEW

**Comment by raisedadead** [comment]
Thanks for the pull request, but IMHO this has to be handled in the camperbot's code. 
The main repo is currently aiming to have pure API's. 

Hence will this fix works, it's better keeping the return logic on that repo. 

Refer https://github.com/FreeCodeCamp/camperbot/issues/26#issuecomment-189576119

**Comment by QuincyLarson** [comment]
@atjonathan I agree with @raisedadead - we should keep this logic on Camperbot. I will close this issue. Can you find and fix https://github.com/FreeCodeCamp/camperbot/issues/26#issuecomment-189576119 ?

**Comment by atjonathan** [comment]
@QuincyLarson @raisedadead, this is the message that is used when the user isn't found. Unless we just refactor it to just use the camperbot repo.

**Comment by raisedadead** [comment]
> The main repo is currently aiming to have pure API's. 

This means the code in camperbot's repo should handle this message i.e receive the current message,  modify and return the appropriate string as needed/suitable for the end application which is chat in this case, in future it could extend to some other app with a different use case.

**Comment by atjonathan** [comment]
Sounds good, I will look into this :+1:

**Pull request closed without merging**
