### PR TITLE
Improved readability of Description

### PR DESCRIPTION
**Pull request by ElienVissers**
Added a br element in front of the 'Note' to start it on a new line.

- [x ] I have read [freeCodeCamp's contribution guidelines](https://github.com/freeCodeCamp/freeCodeCamp/blob/master/CONTRIBUTING.md).
- [x ] My pull request has a descriptive title (not a vague title like `Update index.md`)
- [x ] My pull request targets the `master` branch of freeCodeCamp.
- [x ] None of my changes are plagiarized from another source without proper attribution.
- [x ] My article does not contain shortened URLs or affiliate links.

If your pull request closes a GitHub issue, replace the XXXXX below with the issue number.

Closes #XXXXX

### CODE REVIEW

**Comment by nikrb** [comment]
successfully tested locally

**Comment by RandellDawson** [comment]
The only thing added was a colon.  I think there needs to be an additional `<br>` above the `Note:`.

**Comment by nikrb** [comment]
@RandellDawson #34747 may affect this? I've just tested this pr with 34747 and looks like we don't need the `<br>`.
Should we block this till 34747 is merged?

**Comment by RandellDawson** [comment]
@nikrb Sounds like a good idea.

**Comment by RandellDawson** [comment]
@nikrb #34747 has been merged, so if you update your local master and view the challenge without any of the changes made in this PR (mine included), it looks like it does on the production learn platform, so I believe we can close this PR as not needed.

**Comment by nikrb** [comment]
@ElienVissers Since submission of this pr we have updated compilation of challenges and line breaks no longer require `<br>` tags.

Thanx for your contribution and we look forward to future contributions :balloon:

**Pull request closed without merging**
