### PR TITLE
Revert "Update history to version 4.4.0 🚀"

### PR DESCRIPTION
**Pull request by ghost**
Unseen flaw with version boost. Unable to fix the problem by changing code. Will take deeper look in future.

### CODE REVIEW

**Comment by raisedadead** [comment]
@atjonathan you might want to open the original PR once again. So we don't forget about it. 

It's okay if we close it as not needed. But merge/revert closes an open topic.

**Comment by atjonathan** [comment]
@raisedadead, you can't reopen merged PR's. It's fine, the new version couldn't be supported easily as far as me and @Bouncey could see.

**Comment by Bouncey** [comment]
@raisedadead It would need quite a refactor, the api has changed that much (over 2 versions), it even broke things inside `react-router` once we resolved the original issue

**Review by yedyed63 — COMMENTED** [review]
Ww

**Pull request merged**
