### PR TITLE
Add default value for justify-content

### PR DESCRIPTION
**Pull request by ggurbet**
According to the standard, the default value for justify-content if it is not specified is flex-start.
Source: https://www.w3schools.com/cssref/css3_pr_justify-content.asp

- [X] I have read [freeCodeCamp's contribution guidelines](https://github.com/freeCodeCamp/freeCodeCamp/blob/master/CONTRIBUTING.md).
- [X] My pull request has a descriptive title (not a vague title like `Update index.md`)
- [X] My pull request targets the `master` branch of freeCodeCamp.
- [X] None of my changes are plagiarized from another source without proper attribution.
- [X] My article does not contain shortened URLs or affiliate links.

### CODE REVIEW

**Comment by RandellDawson** [comment]
LGTM

**Review by RandellDawson — APPROVED** [review]

**Review by Manish-Giri — COMMENTED** [review]
LGTM.

@RandellDawson On a related note, I think there should be a change to this section - 

> But first, there is some important terminology to understand before reviewing those options. [Here is a useful image showing a row to illustrate the concepts below.](https://www.w3.org/TR/css-flexbox-1/images/flex-direction-terms.svg)

Instead of having a link point to an external image, I think the image should be embedded in the challenge description itself. Having a picture right in the challenge would help users grasp the presented concepts better, rather than going back and forth between an external link and the challenge.

---
Update - I'll create a separate PR to make this change.

**Review by RandellDawson — APPROVED** [review]
Everything looks fine after the new changes.

**Comment by RandellDawson** [comment]
Thank you for your contribution to the page! 👍
We're happy to accept these changes, and look forward to future contributions. 🎉

**Pull request merged**
