### PR TITLE
Clarify Pig Latin input strings are all lowercase

### LINKED ISSUE #9576: Pig Latin challenge does not test for the vowels when they are upper case
#### Challenge Name

https://www.freecodecamp.com/challenges/pig-latin

#### Issue Description

The test case should include another test such as ` translatePigLatin("Eight"); ` since in the present scenario, some of the codes get cleared. 

#### Browser Information

* Browser Name, Version: 
* Operating System: 
* Mobile, Desktop, or Tablet: 

#### Your Code

```
function translatePigLatin(str) {
 //first version 
  if ('aeiou'.match(str[0])) { 
    return str + "way";
  } else {
    var translated = str;
    for (var i = 0; i < str.length; i++) {
      if ('aeiou'.match(str[i]) === null) {
        translated += str[i];
        translated = translated.slice(1);
      } else {
        break;        
      }
    }
    return translated + "ay";
  }  
}
 translatePigLatin("Eight"); 
```

### PR DESCRIPTION
**Pull request by BKinahan**
#### Pre-Submission Checklist
- [x] Your pull request targets the `staging` branch of FreeCodeCamp.
- [x] Branch starts either `fix/`
- [x] You have only one commit
- [x] All new and existing tests pass the command `npm run test-challenges`.
#### Type of Change
- [x] Small bug fix (non-breaking change which fixes an issue)
#### Checklist:
- [x] Tested changes locally.
- [x] Closes #9576
#### Description

Clarify Pig Latin instructions to indicate that input strings are guaranteed to be English words in all lowercase to address concerns about handling case when solving the challenge.

### CODE REVIEW

**Comment by Bouncey** [comment]
@BKinahan Can you please repeat for the translations as well? I think a google translate would be sufficient :+1:

**Comment by BKinahan** [comment]
@Bouncey I'd rather not, I know firsthand how poorly google translate works for certain languages 😄 

Is that how changes are normally implemented in translations? I'd think a separate issue for translators would be more effective.

**Comment by Bouncey** [comment]
@BKinahan Certainly.

Can you raise the issues for each respective translation and reference this PR please.

If the new text isn't complicated, then yes. For whole challenges / complicated sentence structure / concept descriptions then they are translated by a human.

**Comment by BKinahan** [comment]
@Bouncey 👍

**Comment by Bouncey** [comment]
#### Thanks for contributing :tada:

**Pull request merged**
