### PR TITLE
fix(client): update report user verbiage and link

### LINKED ISSUE #38919: Update "Report This User" link
On the profile page, we should change the text from "Report This User" to "Flag This User's Account for Abuse".

Also, we should change the email address it sends an alert to from team@freecodecamp.org to support@freecodecamp.org.

Cc @QuincyLarson for feedback on the text.

### PR DESCRIPTION
**Pull request by matthewbub**
Checklist:

- [x] I have read [freeCodeCamp's contribution guidelines](https://contribute.freecodecamp.org).
- [x] My pull request has a descriptive title (not a vague title like `Update index.md`)
- [x] My pull request targets the `master` branch of freeCodeCamp.
- [x] All the files I changed are in the same world language, for example: only English changes, or only Chinese changes, etc.

Closes #38919

- updated "Report This User" text to "Flag This User's Account for Abuse"
- updated mailto forwarding link from 'team@freecodecamp.org' to 'support@freecodecamp.org'.

### CODE REVIEW

**Comment by raisedadead** [comment]
Thanks for the PR. Please fix the linting errors. Details are available in our [guidelines for contributing](https://contribute.freecodecamp.org)

**Comment by raisedadead** [comment]
Getting closer, you would need to update the tests as well.

**Comment by hi-matbub** [comment]
@raisedadead thank you, apologies for submitting before confirming all tests.

**Review by huyenltnguyen — APPROVED** [review]
LGTM 👍

**Review by raisedadead — APPROVED** [review]

**Pull request merged**
