### PR TITLE
Fix/make test accept jsx comment same line as div

### LINKED ISSUE #34697: Add Comments in JSX
**Describe your problem and how to reproduce it:**
On the "React: Add Comments in JSX" page instructions are: 
"Add a comment somewhere within the provided div element, without modifying the existing h1 or p elements."

And So I entered
```
const JSX = (
  <div> {/*test*/}
    <h1>This is a block of JSX</h1>
    <p>Here's a subtitle</p>
  </div>
);
```

This doesn't affect the h1 or p tags, and yet it fails to pass the test.  

**Add a Link to the page with the problem:**
https://learn.freecodecamp.org/front-end-libraries/react/add-comments-in-jsx

**Tell us about your browser and operating system:**
* Browser Name: Chrome
* Browser Version: Latest
* Operating System: MacOSX

**If possible, add a screenshot here (you can drag and drop, png, jpg, gif, etc. in this box):**
image

### PR DESCRIPTION
**Pull request by ghost**
- [x] I have read [freeCodeCamp's contribution guidelines](https://github.com/freeCodeCamp/freeCodeCamp/blob/master/CONTRIBUTING.md).
- [x] My pull request has a descriptive title (not a vague title like `Update index.md`)
- [x] My pull request targets the `master` branch of freeCodeCamp.
- [x] None of my changes are plagiarized from another source without proper attribution.
- [x] All the files I changed are in the same world language (for example: only English changes, or only Chinese changes, etc.)
- [x] My changes do not use shortened URLs or affiliate links.

Closes #34697 
---
In this [lesson](https://learn.freecodecamp.org/front-end-libraries/react/add-comments-in-jsx), if the user inserts a JSX comment `{/**/}`that is on the same line as `<div>`, the solution will not be accepted; the test seems to think that the user has modified the `h1` and `p` elements. It's possible that the comment is considered as the first child of `JSX` (pure speculation on my part).

The behavior, as in the comment is considered a child, is not the same if the comment is inserted in between `h1` and `p`, as the solution is accepted in this case.

Another issue is normal JS comment `/**/` is accepted when only JSX `{/**/}` should be accepted. 

I've modifed the test to fix both of the above issues (credit goes to @richb999git for his suggestions).

One issue that I can't fix is any comment outside of the `div` will be accepted. In fact, a comment that is outside the `JSX` variable passed the test as well.

### CODE REVIEW

**Comment by RandellDawson** [comment]
@paulywill Have you tried testing this fix?

**Comment by paulywill** [comment]
@RandellDawson Not yet, first thing tomorrow am... and any other PRs you want me to look at.

**Review by paulywill — APPROVED** [review]
Tested locally, tests pass.

**Comment by RandellDawson** [comment]
@wanzulfikri, @paulywill This PR does not close the original issue for a number of issues:
 
* The additions of the `||` in the 2nd and 3rd test would allow a different positioning of the original `h1` and `p` elements and allow the following to pass the 2nd and 3rd tests.

```jsx
const JSX = (
  <div>
    <p>Here's a subtitle</p>
    <h1>This is a block of JSX</h1>
    <p>Here's a subtitle</p>
  </div>
);
```

* The comment could be located outside the JSX `div` element and still pass (see below).

```jsx
const JSX = (
  <div>
    <h1>This is a block of JSX</h1>
    <p>Here's a subtitle</p>
  </div>
);
{/* comment  but not in JSX */}
```

* The `includes` method used would not allow a spaces between the `{` and `/*` or the `*/` and `}`, so variations of the following would fail incorrectly.
```jsx
const JSX = (
  <div>
    <h1>This is a block of JSX</h1>
    { /* valid comment */ }
    <p>Here's a subtitle</p>
  </div>
);
```

I am working on a PR which should fix the original issue plus make sure the original elements are not modified.

**Comment by wanzulfikri** [comment]
Good points. And I think I mentioned the potential unsolved issues in my PR
writeup. Sadly. I wasn’t able to solve those issues.

It’s been a while since I submitted this and I don’t remember exactly what
I tried to fix. Please close this PR if you can submit a better one.

**Comment by RandellDawson** [comment]
@wanzulfikri, @paulywill - Feel free to pull down this PR and test it locally to see if I achieved what I say.  Hopefully, this will take care of most edge cases.

**Comment by RandellDawson** [comment]
I am going to go ahead and close this PR due to it not achieving the desired goal, but if for some reason my PR does not get accepted, feel free to request this PR be reopened to add some more commits.  Also, feel free to create a new PR with different changes.

**Pull request closed without merging**
