### PR TITLE
fix: code block styling escapes parent

### LINKED ISSUE #41418: Code Block Styling Escapes Parent
Page with issue: https://www.freecodecamp.org/learn/data-visualization/data-visualization-projects/visualize-data-with-a-bar-chart

I think there were some recent CSS changes, and they might have caused this:
image

I am going to open this up to first timers, as it should be a small change to a `code` element within the `#description` element.

An issue with the _help wanted_ or _first timers only_ label is open for contribution. The first comprehensive PR created will be reviewed and merged. We typically do not assign issues to anyone other than long-time contributors.

If you would like to contribute, and have not read the contributors docs, please do so here: https://contribute.freecodecamp.org/#/

If you have any issues with contributing, be sure to join us on the [contributors channel](https://chat.freecodecamp.org/channel/contributors), or on the [contributors sub-forum](https://forum.freecodecamp.org/c/contributors/3)

### PR DESCRIPTION
**Pull request by PatrickFranz**
This fixes issue #41418 
Add overflow-wrap to code styling

Checklist:

- [x] I have read [freeCodeCamp's contribution guidelines](https://contribute.freecodecamp.org).
- [x] My pull request has a descriptive title (not a vague title like `Update index.md`)
- [x] My pull request targets the `main` branch of freeCodeCamp.
- [x] All the files I changed are in the same world language, for example: only English changes, or only Chinese changes, etc.

Closes #41418

### CODE REVIEW

**Review by ShaunSHamilton — CHANGES_REQUESTED** [review]
Thank you, for getting this PR out.

However, I have added another related issue. Would you mind adding it to this PR?
Link to comment: https://github.com/freeCodeCamp/freeCodeCamp/issues/41418#issuecomment-794600611

@ahmadabdolsaheb Are you ok with the proposed change? It means code will wrap:
image

As opposed to the current:
image

**Comment by ojeytonwilliams** [comment]
Hey @PatrickFranz the bot shouldn't be warning you here.  It's a false positive because some extra commits made it into the branch history.   Sorry about that!

**Comment by ahmadabdolsaheb** [comment]
> Thank you, for getting this PR out.
> 
> However, I have added another related issue. Would you mind adding it to this PR?
> Link to comment: [#41418 (comment)](https://github.com/freeCodeCamp/freeCodeCamp/issues/41418#issuecomment-794600611)
> 
> @ahmadabdolsaheb Are you ok with the proposed change? It means code will wrap:
> image
> 
> As opposed to the current:
> image

It should scroll vertically instead of wrapping similar to https://www.freecodecamp.org/learn/scientific-computing-with-python/python-for-everybody/dictionaries-common-applications

**Comment by ShaunSHamilton** [comment]
> It should scroll vertically instead of wrapping similar to https://www.freecodecamp.org/learn/scientific-computing-with-python/python-for-everybody/dictionaries-common-applications

@ahmadabdolsaheb I do not see it scrolling vertically? I see it scrolling horizontally.

**Pull request closed without merging**
