### PR TITLE
Reverts recent API decoupling

### PR DESCRIPTION
**Pull request by raisedadead**

### CODE REVIEW

**Review by naomi-lgbt — DISMISSED** [review]
Looks good to me.

Does this also revert the DRY certification config Ahmad had put together?

**Comment by raisedadead** [comment]
> Does this also revert the DRY certification config Ahmad had put together?

No - it should not. Did you happen to see something that is off?

**Comment by nhcarrigan** [comment]
image

Restoring this file is what caught my eye. I could be wrong, but I thought that was removed in the cert PR?

**Comment by raisedadead** [comment]
Ah - that makes sense, those files are now unused and were removed in Ahmad's PR. Anyways I added a commit removing them again.

Thanks for catching these.

**Review by naomi-lgbt — APPROVED** [review]
Re-approving to enable merge when CI passes. Everything else looks correct to me.

**Comment by raisedadead** [comment]
Thanks for the quick QA Nick, I have merged this and now pushing to staging.

**Pull request merged**
