### PR TITLE
Updated links for certificate samples

### LINKED ISSUE #8858: Create new sample certificates with fixed date format
We need to capture new certificates with the updated format, and reapply our sample watermark.

### PR DESCRIPTION
**Pull request by Trion129**
#### Pre-Submission Checklist

- [x] Your pull request targets the `staging` branch of FreeCodeCamp.
- [x] Branch starts with either `fix/`, `feature/`, or `translate/` (e.g. `fix/signin-issue`)
- [x] You have only one commit (if not, [squash](https://github.com/FreeCodeCamp/FreeCodeCamp/wiki/git-rebase#squashing-multiple-commits-into-one) them into one commit).
- [x] All new and existing tests pass the command `npm run test-challenges`. Use `git commit --amend` to amend any fixes.
#### Type of Change

- [x] Small bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds new functionality)
- [ ] Breaking change (fix or feature that would change existing functionality)
- [ ] Add new translation (feature adding new translations)
#### Checklist:

- [x] Tested changes locally.
- [x] Closes currently open issue (replace XXXX with an issue no): Closes #8858
#### Description

Changed the links of old samples to new sample screenshots of the certificates with updated date format.

### CODE REVIEW

**Comment by raisedadead** [comment]
Thanks and this refers #8858 but does not close it, as per ongoing discussion about the certificate re-naming, which will happen around Aug, 2016.

**Comment by atjonathan** [comment]
@raisedadead, shouldn't we close that issue, and make a new one about the the renaming. They don't seem related.

**Comment by raisedadead** [comment]
Yup. We could do that.

**Comment by raisedadead** [comment]
#### :sparkles: :sparkles: **AWESOME!** :sparkles: :sparkles: 

Thanks @Trion129. And Congratulations on your first contribution to Free Code Camp.

**Pull request merged**
