### PR TITLE
fix(curr) : Added id to label and input field of quiz radio button

### LINKED ISSUE #46997: Building a quiz step-30: Missing ids on input elements
### Describe the Issue

It doesn't seem intended as the following step has specific for/id attributes.

https://www.freecodecamp.org/learn/2022/responsive-web-design/learn-accessibility-by-building-a-quiz/step-30
https://www.freecodecamp.org/learn/2022/responsive-web-design/learn-accessibility-by-building-a-quiz/step-31

https://github.com/freeCodeCamp/freeCodeCamp/blob/main/curriculum/challenges/english/14-responsive-web-design-22/learn-accessibility-by-building-a-quiz/6145e6eeaa66c605eb087fe9.md

### Affected Page

https://www.freecodecamp.org/learn/2022/responsive-web-design/learn-accessibility-by-building-a-quiz/step-30

### Your code

```

```

### Expected behavior

The starting codes `input` elements should have the ids used in the following step.

### Screenshots

_No response_

### System

- Device: [e.g. iPhone 6, Laptop]
- OS: [e.g. iOS 14, Windows 10, Ubuntu 20.04]
- Browser: [e.g. Chrome, Safari]
- Version: [e.g. 22]

### Additional context

https://forum.freecodecamp.org/t/learn-accessibility-by-building-a-quiz-step-30/532944

### PR DESCRIPTION
**Pull request by Doraemon23**
Checklist:

- [x] I have read [freeCodeCamp's contribution guidelines](https://contribute.freecodecamp.org).
- [x] My pull request has a descriptive title (not a vague title like `Update index.md`)
- [x] My pull request targets the `main` branch of freeCodeCamp.
- [x] I have tested these changes either locally on my machine, or GitPod.

Closes #46997 

The input and label were missing id and for tags which linked them, I have added those.

### CODE REVIEW

**Review by majestic-owl448 — CHANGES_REQUESTED** [review]
Please see the [How to open a Pull Request (PR)](https://contribute.freecodecamp.org/#/how-to-open-a-pull-request?id=how-to-open-a-pull-request-pr) documentation and adjust your PR accordingly

**Comment by ieahleen** [comment]
The PR does not fix the issue — adding the solution to the seed code of the challenge is not the way to go

**Comment by Doraemon23** [comment]
this what what I was able to infer from the discussion in the issue, if you can tell what should be the solution I willbe able to solve it.

**Comment by ieahleen** [comment]
I would say this is the comment that summarise things better, splitting the current step into 2 (so adding a new step) https://github.com/freeCodeCamp/freeCodeCamp/issues/46997#issuecomment-1229008630

And useful links to documentation here https://github.com/freeCodeCamp/freeCodeCamp/issues/46997#issuecomment-1228977972

**Comment by Doraemon23** [comment]
I get the point that the information needs to be added but there is no steps section in the file , am I supposed to make one and add the details there?

**Comment by ieahleen** [comment]
I suggest familiarizing a bit with the codebase and reading the documentation before attempting to contribute. You can rach out in our [chat room](https://discord.gg/PRyKn3Vbay) or our [forum](https://forum.freecodecamp.org/c/contributors/3) if you need help contributing.

**Comment by ieahleen** [comment]
Will you continue working on this PR @Doraemon23?

**Comment by Doraemon23** [comment]
For the time being, I am unable to work on the issue, sorry for the time loss

**Pull request closed without merging**
