### PR TITLE
feat: universal navbar 

### LINKED ISSUE #36724: Universal navigation needs to be added to learn
User stories:
- [x] users should see projects (/learn), forum, radio, news, portfolio (/settings), donate in the nav bar
- [x] users should land on settings page after clicking the portfolio button
- [x] unauth users should be prompted to sign in when clicking on portfolio or donate buttons
- [x] unauth users should see a button "sign in to save your progress" when visiting projects (/learn)

### PR DESCRIPTION
**Pull request by ahmaxed**
Closes #36724

### CODE REVIEW

**Comment by QuincyLarson** [comment]
Hi @ahmadabdolsaheb I just tinkered with it. It looks amazing. On some resolutions, though, the "Donate" button is not far enough to the left, and may even get partially cut off:

Looks great at 1500 pixels:
Learn_to_code___freeCodeCamp_org

But below that...
Learn_to_code___freeCodeCamp_org

**Comment by QuincyLarson** [comment]
@ahmadabdolsaheb One minor change we should make to the search box should be the inclusion of a magnifying glass icon to the left of the "Search 5,000+ tutorials" text.

Even though we don't use icons anywhere else in our navigation, I think this will help convey to users "this is a search bar - you can type search queries here".

Any generic magnifying glass icon will do - we can just load a small SVG one if we don't have Font Awesome in scope here.

**Comment by ahmadabdolsaheb** [comment]
This should be ready for review.
The magnifier svg is handled in Kris's pr.

**Comment by raisedadead** [comment]
image

I am not sure this is a good design choice, IMHO. Since the portfolio always links  to `/settings`, it shows the sign prompt as expected. As a user it took me a while to realise that I have to click the big CTA button on the page now.

IMHO, it should be more intuitive by going to `/signin` instead when we do not have a session.

**Comment by ojeytonwilliams** [comment]
A couple of things seemed a little counter-intuitive to me.

Where do I go if I want to look at my account/profile?  'Portfolio' doesn't seem like the obvious place to look.  Perhaps 'Profile' instead, as it's reasonable to expect your portfolio to be on your profile, but not the reverse.

On medium screens/tablets the menu button and the menu it expands are on opposite sides of the screen.  
MenuOniPad
I think something like
MenuRightAligned
or
CenteredMenu
would look better.

**Comment by raisedadead** [comment]
Action items remaining on this PR as of last dev meeting:

- [ ] Remove forum and news.
- [ ] Remove coderadio.
- [ ] Add the light/dark theme toggle.
- [ ] Portfolio to link to user's public portfolio.
- [ ] Remove Donate (but keep it behind the auth still).

**Review by raisedadead — CHANGES_REQUESTED** [review]
Action items remaining on this PR as of last dev meeting:

- [x] Remove forum and news.
- [x] Remove coderadio.
- [x] Add the light/dark theme toggle.
- [x] Portfolio to link to user's public portfolio.
- [x] Remove Donate (but keep it behind the auth still).

**Pull request merged**
