### PR TITLE
Adjusted links to use the .org domain and HTTPS.

### PR DESCRIPTION
**Pull request by thehonkinggoose**
This updates the links to use the freecodecamp.org domain name as opposed to the old freecodecamp.com domain name, links also use HTTPS now.

#### Pre-Submission Checklist

- [x] Your pull request targets the `staging` branch of freeCodeCamp.
- [ ] Branch starts with either `fix/`, `feature/`, or `translate/` (e.g. `fix/signin-issue`)
- [x] You have only one commit (if not, [squash](http://forum.freecodecamp.com/t/how-to-squash-multiple-commits-into-one-with-git/13231) them into one commit).
- [ ] All new and existing tests pass the command `npm test`. Use `git commit --amend` to amend any fixes.

#### Type of Change

- [ ] Small bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds new functionality)
- [ ] Breaking change (fix or feature that would change existing functionality)
- [ ] Add new translation (feature adding new translations)

#### Checklist:

- [ ] Tested changes locally.
- [ ] Closes currently open issue (replace XXXX with an issue no): Closes #XXXX

### CODE REVIEW

**Comment by QuincyLarson** [comment]
@nsuchy Thanks for fixing this!

**Comment by QuincyLarson** [comment]
@nsuchy Also, congratulations on getting your first PR merged. Just one more milestone in all that you're doing for the community!

**Comment by nsuchy** [comment]
@QuincyLarson Sorry about the branch name being wrong - I did this from the web editor because it was a tiny non-breaking change and didn't realize it'd just use patch-1. I'll clone my repo locally next time to avoid that issue.

Anyways happy to have my first PR in the main freeCodeCamp repo merged :)

**Comment by QuincyLarson** [comment]
@nsuchy OK - sounds good. Thanks again!

**Pull request merged**
