### PR TITLE
feat(client): remove gitHash from api requests

### PR DESCRIPTION
**Pull request by ojeytonwilliams**
Checklist:

- [x] I have read and followed the [contribution guidelines](https://contribute.freecodecamp.org).
- [x] I have read and followed the [how to open a pull request guide](https://contribute.freecodecamp.org/#/how-to-open-a-pull-request).
- [x] My pull request targets the `main` branch of freeCodeCamp.
- [x] I have tested these changes either locally on my machine, or GitPod.

The motivation was to avoid having to include the .git folder during the docker build process, but also adding gitHash was always intended to be a temporary measure.

### CODE REVIEW

**Comment by naomi-lgbt** [comment]
Did we ever identify where the errors with this endpoint were coming from?

**Comment by ojeytonwilliams** [comment]
No, but it doesn't seem to be us. None of the errors I checked (though I wasn't that thorough) had either query param.

**Comment by ojeytonwilliams** [comment]
Or did you mean "why does it create an error"?

**Review by naomi-lgbt — APPROVED** [review]
Okie dokie.

Though, it might not hurt to use some sort of identifier across all of our requests so we can track what is (or isn't) coming from our application. 🤔

**Comment by naomi-lgbt** [comment]
> Or did you mean "why does it create an error"?

Nope - I was mostly just confirming that this has outlived its usefulness.

**Review by ShaunSHamilton — APPROVED** [review]
MREMB :thumbsup:

**Comment by ShaunSHamilton** [comment]
> The motivation was to avoid having to include the .git folder during the docker build process

Are we having completely different configs for dev and build?

**Comment by ojeytonwilliams** [comment]
> Are we having completely different configs for dev and build?

Nope. At least, no more than currently. Why?

**Pull request merged**
