### PR TITLE
fix(curriculum): typo in js rpg challenge

### LINKED ISSUE #48119: Typo in new JavaScript make an RPG game
### Describe the Issue

There is a typo in Step 156, the word `or` is used to refer to the `AND` operator.

Here is the typo

https://github.com/freeCodeCamp/freeCodeCamp/blob/2f841a56dbe06a8f374d6eff6669664f000993c5/curriculum/challenges/english/15-javascript-algorithms-and-data-structures-22/learn-basic-javascript-by-building-a-role-playing-game/62aa234322d4ad3e8bce42cc.md#L10

it should be `AND`

Can you change the lowercase `and` that refers to the operator in the file, to uppercase **`AND`**, as well? to follow the docs of Mozilla https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Operators/Logical_AND

### Additional context

If you would like to fix this issue, please make sure you read [our guidelines for contributing](https://contribute.freecodecamp.org/#/), we prioritize contributors following the instructions in our guides. Join us in [our chat room](https://discord.gg/PRyKn3Vbay) or [the forum](https://forum.freecodecamp.org/c/contributors/3) if you need help contributing, our moderators will guide you through this.

Sometimes we may get more than one pull requests. We typically accept the most quality contribution, followed by the one that is made first.

Happy contributing.

### PR DESCRIPTION
**Pull request by myankpraksh**
Checklist:

- [x] I have read [freeCodeCamp's contribution guidelines](https://contribute.freecodecamp.org).
- [x] My pull request has a descriptive title (not a vague title like `Update index.md`)
- [x] My pull request targets the `main` branch of freeCodeCamp.
- [ ] I have tested these changes either locally on my machine, or GitPod.

Closes #48119

Fixed typo in line 10 from "or" to "AND"

FIxed lowercase "and" to uppercase "AND" wherever it was referring to AND operator.

### CODE REVIEW

**Review by naomi-lgbt — APPROVED** [review]
banger pr, thanks for contributing!

**Review by gikf — APPROVED** [review]
LGTM :+1:

**Comment by gikf** [comment]
Hi @myankpraksh. Congrats on your first pull request (PR)! 🎉

Thank you for your contribution to the page! 👍
We are happy to accept these changes and look forward to future contributions. 📝

**Comment by myankpraksh** [comment]
Thanks @gikf @naomi-lgbt for reviewing and merging my PR. I am really happy to start my open-source journey with freeCodeCamp, the very place where I started my web development journey. 😁

**Pull request merged**
