### PR TITLE
docs(common steps): Clarify PR instructions

### LINKED ISSUE #16477: Clarify instructions to raise a PR to Base Repo instead of Local Fork.
#### Target File
**CONTRIBUTING.md**

#### Issue Description
There is a scenario where I raise a PR to my local copy of FreeCodeCamp instead of the Base Repository. 
If i merge my commits in the PR (since it is my local copy), my local fork of FCC gets the changes while the Base repository still remains unchanged.

**This can seem confusing (especially to First Timers), as it might seem to you that even though i made my changes, my changes are not getting updated in the Base Repository.**   

#### What needs to be updated ?

The updated instructions should be along the lines of : 

> Make sure that your **Base Fork** is set to **freeCodeCamp/freeCodeCamp** when raising a Pull Request

#### Screenshot

Keeping the Base Repo to freeCodeCamp/freeCodeCamp

#### Additional Instructions :

You can refer the official Github Documentation for raising a PR to a forked repository here : 
https://help.github.com/articles/creating-a-pull-request-from-a-fork/

#### What's the Fix if i already encountered this issue ?

Thanks to @raisedadead , you can follow the instructions below to rewind the changes : 

> For fixing the head if accidental commits are made to the staging branch of ones own fork via pull-request, etc.:

> On your local machine
> 
> git checkout staging
> git fetch upstream staging
> git reset --hard upstream/staging
> git push --force origin staging
> 
> where your remotes [git remote -v] are:
> 
> origin	https://github.com/USERNAME/freeCodeCamp.git (fetch)
> origin	https://github.com/USERNAME/freeCodeCamp.git (push)
> upstream	https://github.com/freeCodeCamp/freeCodeCamp.git (fetch)
> upstream	https://github.com/freeCodeCamp/freeCodeCamp.git (push)

### PR DESCRIPTION
**Pull request by SavaVuckovic**
Added additional instruction on step 2 of common steps.

BREAKING CHANGE: N/A

Closes #16477

#### Pre-Submission Checklist
- [x] Your pull request targets the `staging` branch of freeCodeCamp.
- [x] Branch starts with either `fix/`, `feature/`, or `translate/` (e.g. `fix/signin-issue`)
- [x] You have only one commit (if not, [squash](http://forum.freecodecamp.org/t/how-to-squash-multiple-commits-into-one-with-git/13231) them into one commit).
- [x] All new and existing tests pass the command `npm test`. Use `git commit --amend` to amend any fixes.

#### Type of Change
- [x] Small bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds new functionality)
- [ ] Breaking change (fix or feature that would change existing functionality)
- [ ] Add new translation (feature adding new translations)

#### Checklist:
- [x] Tested changes locally.
- [x] Addressed currently open issue 

Closes #16477

#### Description
This change was made to clarify the process of making a pull request to first timers.
The intention is to alert them to make sure they make a PR against the base repo, instead of their own fork.
Here is how it looks with an image attached. I noticed that CONTRIBUTING.md file has no images and was unsure whether to upload one.

fixone

Otherwise, this is the final version committed with this PR, without using an image:

fixtwo

### CODE REVIEW

**Comment by raisedadead** [comment]
Hi @SavaVuckovic I think this looks clear with the image, can you capture a fresh image, and be able to add it? The new one should have a little more padding on the top and left sides (I know, it just sets off my OCD, :wink: )

**Comment by SavaVuckovic** [comment]
@raisedadead of course! How does this image look?

cleanimage

Also, how should I go about displaying the image in CONTRIBUTING.md file? Do I upload the image somewhere on the web and reference, or do I push it with the codebase itself and use relative path?
Thanks! ^^

**Comment by raisedadead** [comment]
Yup, looks good. You could just create a dir `docs/images` and add it there.

**Review by raisedadead — APPROVED** [review]

**Comment by raisedadead** [comment]
Thanks @SavaVuckovic

**Pull request merged**
