### PR TITLE
fix(curriculum): grammatical error

### LINKED ISSUE #50888: Grammatical error in building a quiz - step 8
### Describe the Issue

The word "to" is repeated one after the other on the instructions:

Scale the image using its id as a selector, and setting the width **to to** be the maximum of 100px or 18vw.

### Affected Page

https://www.freecodecamp.org/learn/2022/responsive-web-design/learn-accessibility-by-building-a-quiz/step-8

### Your code

```



```

### Expected behavior

it should be: 
Scale the image using its id as a selector, and setting the width to be the maximum of 100px or 18vw.

### Screenshots

image

### System

- Device: [Laptop lenovo]
- OS: [Windows 10]
- Browser: [Chrome]

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by Avyukth1C**
fix(curriculum) : Grammatical errors corrected.

Checklist:

- [x] I have read and followed the [contribution guidelines](https://contribute.freecodecamp.org).
- [x] I have read and followed the [how to open a pull request guide](https://contribute.freecodecamp.org/#/how-to-open-a-pull-request).
- [x] My pull request targets the `main` branch of freeCodeCamp.
- [x] I have tested these changes either locally on my machine, or GitPod.

Closes #50888

### CODE REVIEW

**Comment by gikf** [comment]
Hi there, 

Thanks for creating this pull request.

Please ensure you follow the PR checklist and not just tick things off; otherwise, we won't take you seriously. Respect the requirements to earn the respect of your fellow maintainers. You will also save everyone time :)

Since you are new here, please slow down and read our [contributing guidelines](https://contribute.freecodecamp.org), as we see that you may still need to catch up on a few things.

<details>
<summary>Here are some examples (expand)</summary>
 
1. Do not edit files directly on GitHub – while you can, it's not a good idea. 

   Typos and formatting errors can break the tests.

2. Use the correct way to link issues. 

   Add the issue number only in the description of the PR by updating the `XXXXXX`. Do not just add issue numbers everywhere and anywhere you feel like.

4. Keep mentions and review requests to a minimum. 

   We understand you are excited about contributing, and our maintainers will get back to you when they can.

5. Do not work directly off your `main` branch. 

   You can always create a new branch for the changes you are working on. That way, you can sync change to your PR branch as the main repository moves ahead while your PR is waiting in the merge queue.

</details>

Don't worry. You don't have to close this PR. Feel free to ask specific queries on improving your PR here; someone will guide you.

We are happy you are excited to contribute and appreciate you taking the time to help us. Looking forward to more contributions!

Happy Contributing.

**Comment by Avyukth1C** [comment]
Hello,

Thanks for mentioning the shortcomings in my PR.

As mentioned I went through the referred part of the article. I am not able to figure out what exactly I have overlooked. But still I rephrased my PR description. I would request you to please have a look at it. I would like your feedback on it.

I apologize for the inconvenience caused in advance and thank you for being patient enough to help me out with issue.

Thanks in advance.

**Comment by jeremylt** [comment]
You put the title in a place that isn't the title. I updated it for you.

**Comment by Avyukth1C** [comment]
Is "fix(curriculum) : Grammatical errors corrected." supposed to be after the line "Closes #50888" ??

**Comment by jeremylt** [comment]
Nope, its supposed to be in the title
image
up top in this picture

**Comment by Avyukth1C** [comment]
Thank you very much!!!

Got it. I will make sure I put the correct title.

So is the PR good to be merged into the main branch??

**Review by jeremylt — APPROVED** [review]
LGTM

**Comment by Avyukth1C** [comment]
Thank you very much for all the help.

is it fine if I check the second line in my PR checklist?

**Review by gikf — APPROVED** [review]

**Comment by gikf** [comment]
Hi @Avyukth1C. Congrats on your first pull request (PR)! 🎉

Thank you for your contribution to the page! 👍
We are happy to accept these changes and look forward to future contributions. 📝

**Pull request merged**
