### PR TITLE
feat: Rework Nutrition Label practice project

### LINKED ISSUE #46675: Nutrition Label Ex 35-36: Should use Flexbox, not Float
### Describe the Issue

I was helping a camper with this challenge today and they were confused about the need to add `overflow: hidden` to the `h1` element.  I was too, until I did some research and remembered that [containers don't clear floats automatically](https://css-tricks.com/containers-dont-clear-floats/) unless you use `overflow: hidden`.  This is very counter-intuitive and is not explained at all in the challenge.

Additionally, in the next challenge you have to add a "magic number" to the h1 to get it to optically align. I don't think this scales well (literally), because if you increase your font size it's going to break.

### Affected Page

https://www.freecodecamp.org/learn/2022/responsive-web-design/learn-typography-by-building-a-nutrition-label/step-35

### Your code

```html
<div class="calories-info">
        <div class="left-container">
          <p class="bold sm-text">Amount per serving</p>
            <h1>Calories</h1>
          </div>
        <h1 class="right">230</h1>
      </div>          
```
```css
.calories-info {
  display: flex;
  justify-content: space-between;
  align-items: flex-end;
}

.left-container {
  display: flex;
  flex-direction: column;
}
```

### Expected behavior

It seems to me that there is a better, much cleaner solution to be had by applying another wrapper around the "Amount Per Serving" and "Calories" elements and using a flex column, then using flex on the `.calories-info` div with `justify-content: space-between` and `align-items: flex-end`;  

No magic numbers needed, both the markup and css are cleaner - although you do need one more containing element.

I've added a screenshot which shows the layout of the elements in my example.

### Screenshots

image

### System

N/A

### Additional context

In general, the given solution feels very "old school" to me.  Flexbox has been available on most platforms for a number of years now.  We really shouldn't be teaching people to support IE11 (especially since it has reached the end of it's support life, recently).

I know this is a big change, it just bugs me to see this being taught in what is supposed to be a modern course on the web.

### LINKED ISSUE #48043: hint for Learn Typography by Building a Nutrition Label - Step 50 needs a space between class names
### Describe the Issue

The first hint shown in step 50 of Learn Typography by Building a Nutrition Label places two class names together without any space in between so it is hard to read.
The hint is shown if we do not enter any code and simply click on the Check Your Code button.

>Hint
> You should create a new p element at the end of your .daily-value.sm-text element.

### Affected Page

https://www.freecodecamp.org/learn/2022/responsive-web-design/learn-typography-by-building-a-nutrition-label/step-50

### Your code

N/A

### Expected behavior

Need to have a single space in between the two class names for better readability.

### Screenshots

_No response_

### System

N/A

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by majestic-owl448**
Checklist:

- [x] I have read [freeCodeCamp's contribution guidelines](https://contribute.freecodecamp.org).
- [x] My pull request has a descriptive title (not a vague title like `Update index.md`)
- [x] My pull request targets the `main` branch of freeCodeCamp.
- [x] I have tested these changes either locally on my machine, or GitPod.

* Closes #46675
* Related to https://github.com/freeCodeCamp/freeCodeCamp/issues/46358 (Class names refactor)
	* lg -> large
	* md -> medium
	* sm -> small
	* dbl -> double

* Closes https://github.com/freeCodeCamp/freeCodeCamp/issues/48043
	* I've only updated the hint text and not the tests to the new value. Both are programmatically the same but the text was harder to read for some users

### CODE REVIEW

**Comment by bbsmooth** [comment]
I left my comments in the issue.

**Comment by ieahleen** [comment]
I am leaving this to you, @Nirajn2311.

This PR aims to rework the Nutrition Label practice project to use flexbox instead of float, and proper hierarchy for `h1`/`h2` elements. The steps 1-38 still need to be changed, and probably some adjustements will need to be done in steps from 39 to the end.
Issues https://github.com/freeCodeCamp/freeCodeCamp/issues/46358 and https://github.com/freeCodeCamp/freeCodeCamp/issues/48043 are also about the Nutrition Label, so if the issues can be closed with this PR that would be awesome.

Thank you for taking this up, happy coding!

**Comment by Nirajn2311** [comment]
Things todo:
- [ ] Create new challenges(somewhere between 31-34) for the `.calories-info` related CSS

**Comment by raisedadead** [comment]
We are officially on Node.js 18 now. We have changed the merge requirements accordingly.

You will need to rebase this PR against the main branch OR Click the "Update branch" button to get the new checks going.

Thanks for your contribution.

**Comment by Nirajn2311** [comment]
Is there any change required in here other than updating the branch for the new checks? Asking as I see the PR has a https://github.com/freeCodeCamp/freeCodeCamp/labels/status%3A%20waiting%20update label

**Comment by raisedadead** [comment]
Yes - This could use a quick rebase, I think. That should resolve the checks.

**Comment by raisedadead** [comment]
Clicking the update button will not rebase the PR. You want a full rebase because this is a really old PR and branch.

**Comment by Nirajn2311** [comment]
IIRC I asked a query on this and the reason the localised tests are breaking is because of the new challenges in English which are not found in the other languages. @moT01 idea was to merge the PR, then do a quick sync-up with Crowdin.

**Comment by moT01** [comment]
> merge the PR, then do a quick sync-up with Crowdin

Yes, that's our process for the moment when new challenges are added/deleted. Is this ready to go then @Nirajn2311?

**Comment by Nirajn2311** [comment]
@moT01 Yes, this PR is good to go

**Review by moT01 — APPROVED** [review]
This looked good to me. I just ran through the project again to review it. Found a few minor issues and pushed fixes.

Note that the l10n tests won't pass on this PR. We need to do a crowdin sync asap after it gets merged so deployments aren't blocked.

**Review by raisedadead — APPROVED** [review]

**Pull request merged**
