### PR TITLE
Gitter chat embed fix

### LINKED ISSUE #182: Gitter embed not working
I'm not sure why but the gitter chat embed is not working. My only guess is that they prevent embeds, but I know very little about iframes so I don't know.

img

I recommend removing it, or even considering replacing it with a simple proprietary chat.

###### P.S., One is already available by us. :)

### PR DESCRIPTION
**Pull request by ghost**
Added https://*.gitter.im to 'frameSrc' CSP

Fixes #182

### CODE REVIEW

**Comment by BerkeleyTrue** [comment]
Chat embed works for me. Does not seem to be blocked by helmet.

**Comment by jameskopacz** [comment]
Does it work for you in Firefox? I see this in Firefox: http://i.imgur.com/xuUEnw2.png and I'm seeing this in the console which lead me to helmet: http://i.imgur.com/4SMFRhb.png

**Comment by BerkeleyTrue** [comment]
Yes it is not loading in FF for me either. But I am seeing a different error message 

console_-_http___www_freecodecamp_com_chat

@jameskopacz Have you tested this locally to verify it works.

Seems like it still works in chrome if I change the embed link to http.

**Comment by jameskopacz** [comment]
Weird. I'm seeing that message but above it is the CSP error. 

Adding the fix does work locally: http://i.imgur.com/RnRBbRs.png

**Comment by FreeCodeCamp** [comment]
@jameskopacz Wow, I had no idea this was caused by Helmet, but you're right. This fixes it. Thanks for fixing this!

**Pull request merged**
