### PR TITLE
fix: only test mobile curriculum on english

### PR DESCRIPTION
**Pull request by ojeytonwilliams**
Checklist:

- [x] I have read [freeCodeCamp's contribution guidelines](https://contribute.freecodecamp.org).
- [x] My pull request has a descriptive title (not a vague title like `Update index.md`)
- [x] My pull request targets the `main` branch of freeCodeCamp.
- [x] I have tested these changes either locally on my machine, or GitPod.

Closes nothing, but should make the tests less flaky.

### CODE REVIEW

**Review by raisedadead — DISMISSED** [review]

**Comment by raisedadead** [comment]
I re-ran those failed jobs and I think they are just flaky for some reason.

**Comment by ojeytonwilliams** [comment]
Yeah, irony thy name is our testing suite.

**Comment by ojeytonwilliams** [comment]
@raisedadead I'll stop it running on `SHOW_UPCOMING_CHANGES`, too.

**Review by wongruiyang — DISMISSED** [review]

**Comment by Sembauke** [comment]
I see you beet me to it #45559

**Review by wongruiyang — APPROVED** [review]

**Review by raisedadead — APPROVED** [review]

**Review by naomi-lgbt — APPROVED** [review]

**Pull request merged**
