### PR TITLE
Removed Image links and added text commands & text tables

### LINKED ISSUE #35518: SQL Guide files invalid
The file [SQL Guide - ALTER TABLE](https://github.com/freeCodeCamp/freeCodeCamp/blob/master/guide/english/sql/sql-alter-table-statement/index.md) is totally messed up since the user removed the images, a PR #30349 made changes to it which makes it better, but not fixes it.

We want the whole file to have statements like that we have now for `Remove a column:`

Additionally, we want the PR to be formatted properly, such as each of these:
- image
- image

to be put in a list form

And this warning note:
image
to be moved to a new line

# EDIT:
On a closer look, this problem is in many SQL challenges which are there. Examples:

- [1](https://github.com/freeCodeCamp/freeCodeCamp/blob/master/guide/english/sql/sql-create-table/index.md)
- [2](https://github.com/freeCodeCamp/freeCodeCamp/blob/master/guide/english/sql/sql-server-convert-function/index.md)
In (2), the images should be removed, we do not want to host them on GitHub

We can either have just the text command or text tables like in: [here](https://github.com/freeCodeCamp/freeCodeCamp/blob/master/guide/english/sql/sql-where-clause/index.md)

### PR DESCRIPTION
**Pull request by umasankar1999**
- [x] I have read [freeCodeCamp's contribution guidelines](https://github.com/freeCodeCamp/freeCodeCamp/blob/master/CONTRIBUTING.md).
- [x] My pull request has a descriptive title (not a vague title like `Update index.md`)
- [x] My pull request targets the `master` branch of freeCodeCamp.
- [x] None of my changes are plagiarized from another source without proper attribution.
- [x] All the files I changed are in the same world language (for example: only English changes, or only Chinese changes, etc.)
- [x] My changes do not use shortened URLs or affiliate links.

Closes #35518

### CODE REVIEW

**Review by thecodingaviator — DISMISSED** [review]
@umasankar1999 I believe this issue is in more files than just this one. For example: https://github.com/freeCodeCamp/freeCodeCamp/blob/master/guide/english/sql/sql-create-table/index.md and https://github.com/freeCodeCamp/freeCodeCamp/blob/master/guide/english/sql/sql-server-convert-function/index.md . Please check all SQL files and make the changes in all of them

**Comment by umasankar1999** [comment]
Thanks for the review @thecodingaviator.  I will find all the files which are like this and I will update it accordingly.  Require some time to Update PR because I have to check and update all the files.

**Comment by RandellDawson** [comment]
@thecodingaviator Once the PR is to your liking, we should still have the user clean up the git history (`git rebase -i`.

**Comment by umasankar1999** [comment]
@thecodingaviator  , checked and updated all files in Sql files .

**Comment by thecodingaviator** [comment]
@umasankar1999 Please squash all the commits into one single commit using how @RandellDawson has said above. If you need more help on that, use Google

**Comment by umasankar1999** [comment]
Sure ! @thecodingaviator

**Comment by umasankar1999** [comment]
I am extremely sorry @RandellDawson  @thecodingaviator , I think , I am messed up somewhere . I will fix it.

**Comment by umasankar1999** [comment]
@RandellDawson , @thecodingaviator . It would be a great help if you given any suggestions or directions for squashing.

**Comment by RandellDawson** [comment]
You need to first run `git pull --rebase upstream master`.  

Then, validate if you run `log -n 5 --color --pretty=format:'%Cred%h%Creset -%C(yellow)%d%Creset %s %Cgreen(%cr) %C(bold blue)<%an>%Creset' --abbrev-commit` and you should see something like:
```bash
10973684e - (HEAD -> umasankar1999-master) Removed images and added text tables (15 seconds ago) <Uma Sankar>
f39e4bb7d - Removed Images and added text tables & commands . (16 seconds ago) <Uma Sankar>
d514d9861 - Fixed Case sensitive error (17 seconds ago) <Uma Sankar>
40581e3d6 - Removed Images and added the text (18 seconds ago) <Uma Sankar>
5b32e98c4 - (upstream/master, origin/master, origin/HEAD, master) fix(curriculum): Add solutions to Applied Visual Design challenges (#35815) (22 minutes ago) <Huyen Nguyen>
```
The key is you should see 4 commits with your username as the last 4 commits.  If you see that, then you can squash all of them, but running `git rebase -i HEAD~04`.  This will open your editor where you `pick` the first one in the list and `squash` the other 3 three.  Once you save the editor file another editor will pop up and let you edit the actual commit message for the now single commit you will have.  I would recommend keeping only the one commit message "Removed images and added text tables" and deleting the rest, but you can do what you want at this step.  Once you save the commit message, then you will need to `git push --force` so the PR gets the changes.

**Comment by umasankar1999** [comment]
Thanks a lot ! @RandellDawson . It  worked .
@thecodingaviator  Checked and Updated all Sql files .

**Comment by umasankar1999** [comment]
@thecodingaviator,  Squashed all commits  into single commit.

**Comment by umasankar1999** [comment]
@thecodingaviator  , I am asking out of curiosity , What is it meant by status : ready for QA and  what  is the procedure we are gonna follow ?

**Comment by thecodingaviator** [comment]
@umasankar1999 We're gonna have a look at the files and get the PR merged as its turn comes

**Comment by umasankar1999** [comment]
@thecodingaviator  Okay !

**Review by RandellDawson — APPROVED** [review]

**Comment by RandellDawson** [comment]
Congrats @umasankar1999 on your first pull request (PR)! 🎉 We really appreciate all your hard work on this PR!

Thank you for your contribution to the page! 👍
We're happy to accept these changes, and look forward to future contributions. 📝

**Comment by umasankar1999** [comment]
@RandellDawson Thanks !

**Pull request merged**
