### PR TITLE
Improved mobile layouts to map page

### LINKED ISSUE #8254: Map header too tall for mobile landscape view
A camper just emailed me about this, and after testing it out on my iPhone 5 in both mobile Chrome and Safari, I concur. The map header element is too tall. Here's a photo from my iPhone 5:

I think we should either 
1) make the map less tall on xs and sm sized viewports or
2) make the map less tall in general

### PR DESCRIPTION
**Pull request by dlwebdev**
#### Pre-Submission Checklist

- [x] Your pull request targets the `staging` branch of FreeCodeCamp.
- [x] Branch starts with either `fix/`, `feature/`, or `translate/` (e.g. `fix/signin-issue`)
- [x] You have only one commit (if not, [squash](https://github.com/FreeCodeCamp/FreeCodeCamp/wiki/git-rebase#squashing-multiple-commits-into-one) them into one commit).
- [x] All new and existing tests pass the command `npm run test-challenges`. Use `git commit --amend` to amend any fixes.
#### Type of Change

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] Add new translation (feature adding new translations)
#### Checklist:

- [x] Tested changes locally.
- [x] Closes currently open issue (`Closes #8254`): Closes 
#### Description

Closes #8254

When viewing the map in mobile mode, especially landscape, there just wasn't much space allotted to view the panes.

In landscape mode, I made the buttons float next to each other and also moved up the text regarding challenges for certifications.

Also corrected spacing of the stylesheet for a few previous rules to make things more consistent.

### CODE REVIEW

**Comment by dlwebdev** [comment]
@hallaathrad here are those changes I mentioned I'd address. Feel free to suggest another method or just reject it outright. 

Here are some screen shots.

new-portrait
new_landscape

**Comment by dlwebdev** [comment]
I'd like to get your thoughts on the floating of the inputs in landscape mode specifically. Maybe give the "Collapse all challenges" button less space than the input box since it's just a button?

**Comment by atjonathan** [comment]
@dlwebdev, here is what some specific viewports look like:



Could you make these inputs shrink responsively on different viewports?

**Comment by hallaathrad** [comment]
My two cents: if the elements shall be inline, I'd switch the search to be on the left, and then the collapse button. And then perhaps some appropriate space in between so it's clear one does not operate on the other. But I do like the idea of taking that extra row away.

**Comment by dlwebdev** [comment]
Those buttons are now responsive as well.

**Comment by dlwebdev** [comment]
No problem @hallaathrad, will toggle the order of those buttons.

**Comment by dlwebdev** [comment]
Order of the inputs has been toggled when that row is collapsed.
order_swapped

**Comment by dlwebdev** [comment]
Needs a little spacing as commented, so will also add that.

**Comment by dlwebdev** [comment]
Padding added when row is collapsed as requested.

padding-added

**Comment by atjonathan** [comment]
@hallaathrad, how does this look now?

**Comment by atjonathan** [comment]
### **LGTM :+1:**
@dlwebdev, you need to adjust styling for the map aside:

**Comment by dlwebdev** [comment]
Will address.

**Comment by dlwebdev** [comment]
So the map-aside is being served in an iframe which treats it as it's own viewport, etc. Therefore, my mobile specific media queries are being applied to it. 

Just to make sure I'm going down the right path here, we should leave it as it currently is in production when it's in the map-aside window correct? 

I'm not even able to open the nav-aside in mobile views, it just takes you straight to the map page, which makes sense since there isn't room to use it.

**Comment by dlwebdev** [comment]
Here's a screen shot of the map-aside keeping the buttons on one line.
map-aside

**Comment by atjonathan** [comment]
@dlwebdev 

> Just to make sure I'm going down the right path here, we should leave it as it currently is in production when it's in the map-aside window correct? i.e. these mobile specific style rules not applied to it.
I'm not even able to open the nav-aside in mobile views, it just takes you straight to the map page, which makes sense since there isn't room to use it.

Correct, let's keep the styles as they are for the aside.

**Comment by dlwebdev** [comment]
Map aside is now styled as it originally was.

**Comment by atjonathan** [comment]
#### **LGTM :+1:**
Thanks for contributing :tada:

**Pull request merged**
