### PR TITLE
use jsbins loop detect

### LINKED ISSUE #4865: Help me progress
Challenge [Waypoint: Use Hex Code for Specific Colors](http://www.freecodecamp.com/challenges/waypoint-use-hex-code-for-specific-colors?solution=%3Cstyle%3E%0A%20%20body%20%7B%0A%20%20%20%20background-color%3A%20%23000000%3B%0A%20%20%7D%0A%3C%2Fstyle%3E%0A) has an issue.
User Agent is: <code>Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/46.0.2486.0 Safari/537.36 Edge/13.10586</code>.
Please describe how to reproduce this issue, and include links to screenshots if possible.

My answer is correct but wrongly flagged as erroneous.
My code:
```html
<style>
  body {
    background-color: #000000;
  }
</style>

```

### LINKED ISSUE #4873: in every js lesson page i have `TypeError: Object.assign is not a function`
in every link from the "basic javascript" section i go(and the later Javascipt lessons, not jQuery lessons or anything else), i have a 
```TypeError: Object.assign is not a function```
two days ago these links worked and i already have completed these lessons but now they're not working. all of them.

- i did reset the code  
- made a hard refresh using the F5 key
- deleted localStorage
- tried the incognito mode    
**still i have the same error.**

and this error is in my console too. 

i tried with my Galaxy Note 4:
in Dolphin browser, i have the error.
but in chrome there is no error!

### LINKED ISSUE #4882: error: plugin failed to initialize free code camp
Can't run code because of this error error: plugin failed to initialize  it is showing in the lower left corner.  Tried different browsers, computer, and devices same error.  Have a really slow internet connection

### LINKED ISSUE #4885: No matter what and how I write it, it still says there's an error in my code.
Challenge [Waypoint: Use Clockwise Notation to Specify the Padding of an Element](http://www.freecodecamp.com/challenges/waypoint-use-clockwise-notation-to-specify-the-padding-of-an-element?solution=%3Cstyle%3E%0A%20%20.injected-text%20%7B%0A%20%20%20%20margin-bottom%3A%20-25px%3B%0A%20%20%20%20text-align%3A%20center%3B%0A%20%20%7D%0A%0A%20%20.box%20%7B%0A%20%20%20%20border-style%3A%20solid%3B%0A%20%20%20%20border-color%3A%20black%3B%0A%20%20%20%20border-width%3A%205px%3B%0A%20%20%20%20text-align%3A%20center%3B%0A%20%20%7D%0A%0A%20%20.yellow-box%20%7B%0A%20%20%20%20background-color%3A%20yellow%3B%0A%20%20%20%20padding%3A%2020px%2040px%2020px%2040px%3B%0A%20%20%7D%0A%20%20%0A%20%20.red-box%20%7B%0A%20%20%20%20background-color%3Ared%3B%0A%20%20%20%20padding%3A%2020px%2040px%2020px%2040px%3B%0A%20%20%7D%0A%0A%20%20.green-box%20%7B%0A%20%20%20%20background-color%3A%20green%3B%0A%20%20%20%20padding%3A%2040px%2020px%2020px%2040px%3B%0A%20%20%7D%0A%3C%2Fstyle%3E%0A%3Ch5%20class%3D%22injected-text%22%3Emargin%3C%2Fh5%3E%0A%0A%3Cdiv%20class%3D%22box%20yellow-box%22%3E%0A%20%20%3Ch5%20class%3D%22box%20red-box%22%3Epadding%3C%2Fh5%3E%0A%20%20%3Ch5%20class%3D%22box%20green-box%22%3Epadding%3C%2Fh5%3E%0A%3C%2Fdiv%3E%0A) has an issue.
User Agent is: <code>Mozilla/5.0 (Windows NT 6.1; WOW64; rv:42.0) Gecko/20100101 Firefox/42.0</code>.
Please describe how to reproduce this issue, and include links to screenshots if possible.

My code:
```html
<style>
  .injected-text {
    margin-bottom: -25px;
    text-align: center;
  }

  .box {
    border-style: solid;
    border-color: black;
    border-width: 5px;
    text-align: center;
  }

  .yellow-box {
    background-color: yellow;
    padding: 20px 40px 20px 40px;
  }
  
  .red-box {
    background-color:red;
    padding: 20px 40px 20px 40px;
  }

  .green-box {
    background-color: green;
    padding: 40px 20px 20px 40px;
  }
</style>
<h5 class="injected-text">margin</h5>

<div class="box yellow-box">
  <h5 class="box red-box">padding</h5>
  <h5 class="box green-box">padding</h5>
</div>

```

What am I doing wrong???

### PR DESCRIPTION
**Pull request by BerkeleyTrue**
This pr removes the dependency on web workers and handles infinite loops for/while loops. Handles most recursion loops but not perfectly. It does as good as the current implementation.

The benefit of moving away from web workers is it allows us to use whatever library in the iFrame without require to mock it in the web worker environment which has no DOM.

The drawbacks are that we can't shutdown a iframe like we could a web worker. This actually doesn't apply to use because we only used web workers in some situation, but we ran code in the main thread most of the time.

closes #4882
closes #4873

closes #4865
closes #4885

### CODE REVIEW

**Comment by BerkeleyTrue** [comment]
A PR removing unused files should come after this is in production

**Comment by ltegman** [comment]
From my testing it appears this will also close the new bug #4885 and it does indeed close #4865

**Comment by BerkeleyTrue** [comment]
Nice!

**Comment by BerkeleyTrue** [comment]
Wait, #4885?

**Comment by ltegman** [comment]
Yup -- the solution works perfectly in Chrome but not in Firefox in prod, but with this PR it works in both.

**Comment by ltegman** [comment]
@BerkeleyTrue Is there a reason you're including loopProtect in the repo instead of grabbing it from bower or npm?

**Comment by BerkeleyTrue** [comment]
Those versions are not the same. Plus the original one is out of date as well and hasn't had any movement in over a year. I figured we would need to make changes to it anyway might as well vender it.

**Comment by ltegman** [comment]
Pretty sure the problem is test display stems from https://github.com/FreeCodeCamp/FreeCodeCamp/blob/staging/client/iFrameScripts.js#L26 but I'm not clever enough to fix it right now which means it's my bed time. Hopefully someone else cracks it shortly!

**Comment by bugron** [comment]
#4882, #4873, #4865, #4885 are fixed for me, but the code from #4881 still is not passing the test in FF (no errors in console, works in Chrome),

**Comment by ltegman** [comment]
It looks like the replace at https://github.com/FreeCodeCamp/FreeCodeCamp/blob/staging/client/commonFramework/display-test-results.js#L16 will need to be changed to `replace(/\'\);?$/g, '')` because something about this change has made it so the `;` is sometimes missing when it gets there, causing the regex to leave in the `')`

**Comment by BerkeleyTrue** [comment]
@bugron This should now work with Firefox (fingers crossed)

**Comment by ltegman** [comment]
Looks good to me and has @SaintPeter's approval as well! Merging! :+1:

**Comment by bugron** [comment]
Reported issues are fixed for me, awesome!

**Pull request merged**
