### PR TITLE
fix(api): use challenge helper to update completed challenges

### PR DESCRIPTION
**Pull request by ojeytonwilliams**
- **test: completedDate should not update**
- **fix: use helper in /project-completed**
- **refactor: use helper function for trophy route**
- **fix: stop mutating some argument properties**
- **refactor: simplify updateUserChallengeData**
- **fix: de-deprecate helper**

Checklist:

- [x] I have read and followed the [contribution guidelines](https://contribute.freecodecamp.org).
- [x] I have read and followed the [how to open a pull request guide](https://contribute.freecodecamp.org/#/how-to-open-a-pull-request).
- [x] My pull request targets the `main` branch of freeCodeCamp.
- [x] I have tested these changes either locally on my machine, or GitPod.

Splitting this functionality into separate helpers was a mistake. It makes it more likely that we have inconsistent behaviour between the various submission endpoints.

Since I think we should keep using (some form of) the helper, I cleaned it up a little and fixed a bug caused by the fact it modified its input.

### CODE REVIEW

**Review by moT01 — APPROVED** [review]
LGTM 🎉

**Review by ShaunSHamilton — COMMENTED** [review]
This is fine for now, but I would prefer the logic going into each endpoint instead of a function with so many branches.

We have a lot we could improve about the current set up, but I do not think this `updateUserChallengeData` function is improving anything - it is preventing optimised db queries, and is still not preventing "inconsistent behaviour". Case being the `needsModeration` logic.

Unfortunately, other than "rip out the function", I have no useful/actionable suggestions.

LTSTM :thumbsup:

**Review by ShaunSHamilton — APPROVED** [review]

**Review by ShaunSHamilton — APPROVED** [review]

**Comment by ojeytonwilliams** [comment]
I see what you're saying, but "updating the user's completed challenges" is something we need to handle consistently. https://github.com/freeCodeCamp/freeCodeCamp/actions/runs/9300126530/job/25596137178?pr=54546 shows how this can matter (the difference between pushing a new challenge and overwriting the challenge array).

Also, what's wrong with `needsModeration`? Do we have an issue tracking that?

**Comment by ShaunSHamilton** [comment]
> Also, what's wrong with needsModeration?

It is required to be correctly set before the call to `updateUserChallengeData`, which can easily be forgotten.

> Do we have an issue tracking that?

We discussed this a bit in one meeting about the schema. We might want to re-think the entire use-case. I am hesitant to open an issue, because it will just go stale from a lack of need to do anything with it yet.

**Comment by ojeytonwilliams** [comment]
Okay, no worries. We can revisit it if we need the feature or when we're doing some housekeeping.

**Pull request merged**
