### PR TITLE
Add Solution For Bonfire: Where Do I Belong 

### LINKED ISSUE #4112: incorrect solution added for issue #3836
Solution on line 668 of seed/challenges/basic-bonfires.json reads: `"function where(arr, num) {\n  // Find my place in this sorted array.\n  return num;\n}\n\nwhere([40, 60], 50);\n"`
It should read `"function where(arr, num) {\n  var i = -1;\n  while (++i < arr.length) {\n    if (arr[i] >= num) {\n      return i;\n    }\n  }\n  return i;\n}\n\nwhere([40, 60], 50);\n"`

### PR DESCRIPTION
**Pull request by krantzinator**
apologies on the new PR -- still learning the git magic
should close #4112

### CODE REVIEW

**Comment by bugron** [comment]
@krantzinator thanks for the PR. Please, remove the issue number from the title (the same applies to commit messages and branch names).

**Comment by ltegman** [comment]
@krantzinator The build step now actually has a testing framework that will let you know when a challenge solution doesn't pass all the tests. You can run it locally with `npm run test-challenges`. In this case it's not passing because `i` is not defined in the loop. If you put `var` in front of `i` inside the loop initialization it should pass the tests.

**Comment by SaintPeter** [comment]
@krantzinator This looks good, but could you please squash your commits?  If you do `rebase -i HEAD^^` you should be able to change the second commit's entry to "squash", so it will just be a single commit.

**Comment by ltegman** [comment]
Looks good, thanks! :smile:

**Pull request merged**
