### PR TITLE
fix(curriculum): consistent function parenthesis checking

### PR DESCRIPTION
**Pull request by gikf**
Checklist:

- [x] I have read and followed the [contribution guidelines](https://contribute.freecodecamp.org).
- [x] I have read and followed the [how to open a pull request guide](https://contribute.freecodecamp.org/#/how-to-open-a-pull-request).
- [x] My pull request targets the `main` branch of freeCodeCamp.
- [x] I have tested these changes either locally on my machine, or GitPod.

- - -
- Scope limited to optional (or not) parenthesis when defining function with single parameter.

### CODE REVIEW

**Comment by jdwilkin4** [comment]
It looks like some of the tests are failing.
maybe one of the changes accidentally broke something

**Comment by Ksound22** [comment]
Hi @gikf 👋🏽

Could you please tell me more about what this PR does?

**Comment by Ksound22** [comment]
> @Ksound22 most of these are changing regex regarding arrow function parenthesis, ie. for function having `param` as parameter name - from `\(?\s*param\s*\)?` to `(\(\s*param\s*\)|param)`.
> 
> Reason for it is, current regex allows invalid code:
> 
> ```
> (param
> ```
> 
> Or
> 
> ```
> param)
> ```
> 
> Changes make sure allowed are only:
> 
> ```
> (param)
> ```
> 
> Or
> 
> ```
> param
> ```
> 
> With any number of spaces between `(` or `)` and the parameter name.

Thanks. I'm on it now.

**Review by JoyShaheb — APPROVED** [review]

**Review by Ksound22 — APPROVED** [review]
LGTM 👍🏾

**Pull request merged**
