### PR TITLE
feat(client): refactor propTypes to TS types

### PR DESCRIPTION
**Pull request by ShaunSHamilton**
Checklist:

- [x] I have read [freeCodeCamp's contribution guidelines](https://contribute.freecodecamp.org).
- [x] My pull request has a descriptive title (not a vague title like `Update index.md`)
- [x] My pull request targets the `main` branch of freeCodeCamp.
- [x] I have tested these changes either locally on my machine, or GitPod.

Related to #42256 

If you are wondering why there are seemingly unrelated TS conversions, it is because, originally, I put in some work to start the Redux conversion, but realised it was going nowhere small. So, quite while this PR was still manageable.

### CODE REVIEW

**Review by ojeytonwilliams — APPROVED** [review]
Just to check, the idea behind this is that we'll subsequently be able to drop the exported PropTypes in favour of types?  

LGTM :+1: regardless.

**Comment by ahmadabdolsaheb** [comment]
nitpick: maybe we should establish a naming convention for the ts types and either add the "type" at the end of the name of each type or not.

**Comment by ojeytonwilliams** [comment]
> nitpick: maybe we should establish a naming convention for the ts types and either add the "type" at the end of the name of each type or not.

I'd rather we didn't add it, since it's redundant.

**Comment by ShaunSHamilton** [comment]
@ahmadabdolsaheb In my personal projects I follow a convention to add `Type` to the end of a `type` or `interface`, and `Enum` to the end of an `enum`. So, I would prefer that. Although, as Oliver said, this is largely redundant.

For this PR, it makes sense, because we still are using/defining the PropType variables, but, once those are gone, TS will remind us if we try to use a type for anything other than typesetting.

**Review by ahmaxed — APPROVED** [review]

**Review by ojeytonwilliams — APPROVED** [review]
LGTM :+1: 

Re: naming, I'd be happy with `ComponentProps`.  So, we'd be writing:

```js
function Component({ prop1, prop2 }: ComponentProps): JSX.Element {
```

I think that's nice and clear while minimising repetition.

**Comment by ShaunSHamilton** [comment]
@ojeytonwilliams Is this ok to be merged? It would come in handy for most of the TS migration.

**Pull request merged**
