### PR TITLE
fix: block-cta-wrapper breaking the layout in mobile view. 

### LINKED ISSUE #41266: 'help us translate' badge link is breaking the layout on mobile/smaller screens
**Describe the bug**
The link to the i18n contribution docs is breaking the layout on mobile/smaller screens.

**To Reproduce**
Steps to reproduce the behavior (Try this on a mobile device or change your window viewport to a smaller one):
1. Go to https://www.freecodecamp.org/espanol/learn/javascript-algorithms-and-data-structures/
2. Scroll down to 'Cursos'
3. See how 'Ayúdanos a traducir' link is breaking the layout

**Expected behavior**
It shouldn't break the layout. In that breakpoint the usual thing is that each element remains on a different line.

**Screenshots**
image

### PR DESCRIPTION
**Pull request by tegardp**
Checklist:

- [x] I have read [freeCodeCamp's contribution guidelines](https://contribute.freecodecamp.org).
- [x] My pull request has a descriptive title (not a vague title like `Update index.md`)
- [x] My pull request targets the `main` branch of freeCodeCamp.
- [x] All the files I changed are in the same world language, for example: only English changes, or only Chinese changes, etc.

Closes #41266

### CODE REVIEW

**Review by ahmaxed — APPROVED** [review]

**Comment by ahmadabdolsaheb** [comment]
Screen Shot 2021-03-04 at 3 01 02 PM
Screen Shot 2021-03-04 at 3 01 12 PM

**Comment by ahmadabdolsaheb** [comment]
@tegardp, thanks for the PR :) This should resolve our issue with the translation cta button.

**Review by naomi-lgbt — APPROVED** [review]
This looks good to me. Pulled down locally, got the same results as Ahmad's screenshots above. Appears to resolve the linked issue.

**Comment by nhcarrigan** [comment]
Congrats on your first pull request (PR).

Thank you for your contribution to the page. We are happy to accept these changes and look forward to future contributions.

**Pull request merged**
