### PR TITLE
feat(learn): split InforSec and QA into individual certs

### PR DESCRIPTION
**Pull request by beaucarnes**

### CODE REVIEW

**Comment by raisedadead** [comment]
We need to confirm a few things before we can land this:

1. Since we have split the certifications, the older cert should still be valid and displayed.
2. Should people be able to claim two certs? Should we instead have an announcements, since the projects are all same, they get to claim two certs.
3. We should add some tests in place for consistency amongst the user records.

**Comment by raisedadead** [comment]
How is this coming along?

**Comment by scissorsneedfoodtoo** [comment]
Sorry for the delay @raisedadead. 

Things are going well. I've added the descriptions for the new projects and am testing claiming the new certifications. 

In my meeting with @beaucarnes and @QuincyLarson we discussed having a new Legacy Information Security and Quality Assurance certificate to handle cases where people are working on or have already completed the current certificate IS&QA certificate. I'm looking into how we can add that now.

**Comment by scissorsneedfoodtoo** [comment]
@raisedadead, I was able to add a legacy infosecQa certificate. Did some tests claiming all the new certificates and they're working. 

The only problem now is that, while you can claim the legacy infosecQa certificate from the profile page, the button doesn't change to "Show certificate" like it does for the other legacy certs. Instead you have to manually navigate to `/certification/userName/legacy-information-security-and-quality-assurance` to view the certificate, or go to the public profile page and click on the button there.

Do you know why this might be happening?

**Comment by raisedadead** [comment]
Thanks for the updates, I will try and check when this is ready for a merge.

**Comment by scissorsneedfoodtoo** [comment]
@raisedadead, pulled in the recent changes from #38271 to resolve the conflicts here and reduce the number of changed flies. Should be ready to QA now.

**Comment by raisedadead** [comment]
Thanks @scissorsneedfoodtoo I had been meaning to do that. Good to know that you have gotten it cleaned up.

I will land this even if it has minor bugs like you mentioned earlier.

**Pull request merged**
