### PR TITLE
feat(interview-prep): Transfering Rosetta problems from Curriculum

### PR DESCRIPTION
**Pull request by NitronR**
- [ ] I have read [freeCodeCamp's contribution guidelines](https://github.com/freeCodeCamp/freeCodeCamp/blob/master/CONTRIBUTING.md).
- [ ] My pull request has a descriptive title (not a vague title like `Update index.md`)
- [ ] My pull request targets the `master` branch of freeCodeCamp.
- [ ] None of my changes are plagiarized from another source without proper attribution.
- [ ] All the files I changed are in the same world language (for example: only English changes, or only Chinese changes, etc.)
- [ ] My changes do not use shortened URLs or affiliate links.

Closes #XXXXX

### CODE REVIEW

**Comment by NitronR** [comment]
@scissorsneedfoodtoo Hey! I have transferred some challenges from the curriculum repository. A challenge is failing a test here. Can you please help out with this?

**Comment by ezioda004** [comment]
@scissorsneedfoodtoo FYI - we already have a doubly linked list [challenge](https://learn.freecodecamp.org/coding-interview-prep/data-structures/create-a-doubly-linked-list) and this PR adds a similar challenge.

**Comment by scissorsneedfoodtoo** [comment]
@NitronR, sure, let me take a look and see where there are duplicates. Thanks for the heads up, @ezioda004! We might be able to use this PR to remove the sorting algorithm duplicates discussed in https://github.com/freeCodeCamp/freeCodeCamp/issues/34776, too.

**Comment by ezioda004** [comment]
@NitronR I'm afraid aside from checking manually we dont have an automated tool to find duplicates.
What I'd suggest is before adding a new challenge, search the challenge name at https://search.freecodecamp.org/. You'll be able to find any existing similar challenge, and can decide based on that.

**Comment by NitronR** [comment]
@ezioda004 Thanks for helping out with this. I will do this when adding challenges.

**Comment by scissorsneedfoodtoo** [comment]
@NitronR, sorry, I tried to edit the Google sheet with all of the Rosetta Code challenges but don't have access. Will try to make a list here of duplicates instead.

**Comment by NitronR** [comment]
@scissorsneedfoodtoo Yeah, looks like I do not have permission to give edit access. I think that adding people to the spreadsheet can only be done by the creator of the spreadsheet. However, you can make a duplicate of the spreadsheet itself. Or you can simply make a list here. Whatever you think is best.

**Comment by scissorsneedfoodtoo** [comment]
Hey @NitronR, sorry for the delay!

Just a few things I noticed. First, I think we're going to have to remove the Doubly Linked List challenge here. I think we can remove the other Rosetta Code challenges that are repeats of already existing challenges in another PR.

I'll just leave as review comments for the other things I noticed.

**Comment by NitronR** [comment]
@scissorsneedfoodtoo I have removed the Doubly Linked List challenge. May I know which PR are you referring to?

**Comment by scissorsneedfoodtoo** [comment]
Gah, sorry! My earlier review comments didn't end up going through.

By another PR I mean we can just remove some of the Rosetta Code sorting challenges we added in #34634 that are similar to challenges that already exist in the curriculum. Speaking of which, I went through the entire list in that spreadsheet, but I'll take another look soon to make sure I didn't miss anything.

**Comment by NitronR** [comment]
@scissorsneedfoodtoo Sorry for the delay. I have done the changes. Please let me know of any other changes that may be required. Thank you for the review!!

**Comment by scissorsneedfoodtoo** [comment]
@NitronR, no worries! I should be the one apologizing -- my reviews are always coming so late. Everything LGTM! Just going to ask if anyone else can take a look at these before we merge them.

**Comment by NitronR** [comment]
@scissorsneedfoodtoo Sounds great!! I will get the next set of problems ready for now. Is it OK if I send you the names of these problems to check for duplicates? I will perform the checking but just to be sure.

**Comment by scissorsneedfoodtoo** [comment]
@NitronR, yes, please send me the names of the next set of problems and I'll see if there are any duplicates.

Also, I just took another look at these problems and they seem fine. Merging now! Thanks again for all of your hard work and patience with this PR :+1: :+1:

**Pull request merged**
