### PR TITLE
Fix assert message formatting

### PR DESCRIPTION
**Pull request by arialaurel**
This prepends `message:` to any assert messages that were missing it.

### CODE REVIEW

**Comment by SaintPeter** [comment]
Can you please squash your commits, sir?  ;)

**Comment by ltegman** [comment]
Something has gone crazy with my local repo, one sec while I fix this.

**Comment by ltegman** [comment]
Okay, this should be much better now.

**Comment by SaintPeter** [comment]
Looking good.  :+1:

**Pull request merged**
