### PR TITLE
fix(curriculum): standardize fill-in-the-blank format and typos

### PR DESCRIPTION
**Pull request by scissorsneedfoodtoo**
This PR changes the format of earlier fill-in-the-blank questions/answers to the one used in later questions. It also fixes a few typos.

Checklist:

- [x] I have read [freeCodeCamp's contribution guidelines](https://contribute.freecodecamp.org).
- [x] My pull request has a descriptive title (not a vague title like `Update index.md`)
- [x] My pull request targets the `master` branch of freeCodeCamp.
- [x] All the files I changed are in the same world language, for example: only English changes, or only Chinese changes, etc.

Closes #XXXXX

### CODE REVIEW

**Comment by scissorsneedfoodtoo** [comment]
@Sky020, would you mind reviewing this when you get a chance?

**Review by ShaunSHamilton — APPROVED** [review]
LGTM 👍 

I would prefer the highlighting to be consistent, but I assume this will be fixed by a separate PR.

**Comment by ojeytonwilliams** [comment]
@Sky020 which highlighting are you referring to?

**Comment by Sky020** [comment]
> @Sky020 which highlighting are you referring to?

I assume it the same discussion in [insert issue I can no longer find], where there is inconsistency between the style of answers like: https://www.freecodecamp.dev/learn/information-security/python-for-penetration-testing/developing-a-banner-grabber

Compared to: https://www.freecodecamp.dev/learn/data-analysis-with-python/data-analysis-with-python-course/reading-data-csv-and-txt

Personally, I prefer the second, where the code is not highlighted with a different background.

Also, the lack of highlighting for this section throws me off: https://www.freecodecamp.dev/learn/data-analysis-with-python/data-analysis-with-python-course/reading-data-introduction

**Comment by Sky020** [comment]
@ojeytonwilliams , I realise this is merged, but this is the issue I was thinking of: #38942

**Comment by scissorsneedfoodtoo** [comment]
@Sky020, thanks for your review here, and I agree that things can be more consistent.

I think what's happening is that some of the questions here and in your first link use simple code blocks with single backticks (`), while the one in your second link use triple backticks and a language (```py).

Once https://github.com/freeCodeCamp/freeCodeCamp/pull/38730 is merged we should have proper code highlighting for all the Python code blocks.

**Pull request merged**
