### PR TITLE
fix(curriculum): remove outdated text

### LINKED ISSUE #44293: Broken link on Scientific Computing with Python project pages
## Affected pages
The link to the Learn Python Video Course is broken on these  pages:

* [Arithmetic Formatter](https://www.freecodecamp.org/learn/scientific-computing-with-python/scientific-computing-with-python-projects/arithmetic-formatter)
* [Time Calculator](https://www.freecodecamp.org/learn/scientific-computing-with-python/scientific-computing-with-python-projects/time-calculator)
* [Budget App](https://www.freecodecamp.org/learn/scientific-computing-with-python/scientific-computing-with-python-projects/budget-app)
* [Polygon Area Calculator](https://www.freecodecamp.org/learn/scientific-computing-with-python/scientific-computing-with-python-projects/polygon-area-calculator)
* [Probability Calculator](https://www.freecodecamp.org/learn/scientific-computing-with-python/scientific-computing-with-python-projects/probability-calculator)

## Your code

```




```

## Expected behavior

When a user clicks on the link "Learn Python Video Course", the home page for the course should be displayed. 

## Screenshots

Screen Shot 2021-11-26 at 8 30 44 AM

## System
- Device: laptop
- OS: macOS Catalina 10.15.7
- Browser: Chrome
- Version: 96.0.4664.55

### LINKED ISSUE #45069: Link is incorrect.
## Affected page

https://www.freecodecamp.org/learn/scientific-computing-with-python/scientific-computing-with-python-projects/arithmetic-formatter

The second link "Learn Python Video Course (10 hours)" unfortunately goes nowhere. A 404 page appears.

## Your code

```




```

## Expected behavior

It should open the page to the mentioned video course.

## Screenshots

image

### PR DESCRIPTION
**Pull request by HenMoshe**
Checklist:

- [x] I have read [freeCodeCamp's contribution guidelines](https://contribute.freecodecamp.org).
- [x] My pull request has a descriptive title (not a vague title like `Update index.md`)
- [x] My pull request targets the `main` branch of freeCodeCamp.
- [x] I have tested these changes either locally on my machine, or GitPod.

Closes #45069
Closes #44293

changed to a working link from freecodecamp video courses section

### CODE REVIEW

**Review by raisedadead — DISMISSED** [review]

**Comment by HenMoshe** [comment]
@gikf @raisedadead sorry havent seen the earlier issue. i'll remove the link from affected pages and ask for another review.

**Comment by raisedadead** [comment]
Yeah - that would be ideal @HenMoshe - please do not apologize, we are grateful for your contributions. I had no idea about the existing discussion either :)

**Comment by gikf** [comment]
@HenMoshe thanks for including also other projects. One more thing though, from my understanding of https://github.com/freeCodeCamp/freeCodeCamp/issues/44293#issuecomment-988845198, intent is to remove both links and the paragraph above them.

You can also edit first post, to close both issues when PR is merged.

**Comment by HenMoshe** [comment]
@gikf @raisedadead Hey guys so the second time it was my bad for not noticing this comment. i've commited the last change and now changing this to close the other issue as well. thx!

**Review by gikf — APPROVED** [review]
Looks good! :+1:

**Review by raisedadead — APPROVED** [review]

**Pull request merged**
