### PR TITLE
Fix Mixin box-shadow english file

### PR DESCRIPTION
**Pull request by ivanfranco502**
Checklist:

- [X] I have read [freeCodeCamp's contribution guidelines](https://github.com/freeCodeCamp/freeCodeCamp/blob/master/CONTRIBUTING.md).
- [X] My pull request has a descriptive title (not a vague title like `Update index.md`)
- [X] My pull request targets the `master` branch of freeCodeCamp.
- [X] All the files I changed are in the same world language, for example: only English changes, or only Chinese changes, etc.

Closes #XXXXX

### CODE REVIEW

**Comment by moT01** [comment]
Is there an issue for this/these @ivanfranco502? Or any discussion anywhere on why it needs changing?

**Comment by ivanfranco502** [comment]
@moT01 there isn’t any issue, cause it’s a typo.

When we are specifying in the mixin `box-shadow` each css rule, we are using commas as a separator between parameters instead of just spaces.

If you need, I could create an issue but accordingly to the FCC Contribution Guide, if it’s a typo, we can create a PR directly.

**Comment by moT01** [comment]
No, I don't think we need an issue at this point. I misread the diff a little bit before and thought all the green was added.

**Review by moT01 — APPROVED** [review]
LGTM 🎉  Congratulations on your first contribution to freeCodeCamp @ivanfranco502 🎉

**Pull request merged**
