### PR TITLE
Removes broken link in terms of service.

### LINKED ISSUE #7171: Broken link in Terms of Service
The link "reblogging function", poiting to `en.support.freecodecamp.com` is broken. Do FCC still have a support site?

#### Screenshot
broken-fcc-link

### PR DESCRIPTION
**Pull request by afr114**
Removed the following language from the terms of service: "(the reblogging function on FreeCodeCamp.com does this automatically!)"

closes #7171

### CODE REVIEW

**Comment by BerkeleyFalse** [comment]
@afr114 thanks for the PR.
Do not include issue numbers and following [keywords](https://help.github.com/articles/closing-issues-via-commit-messages/#keywords-for-closing-issues) in pull request's title.
Please, review our [**Guidelines for Contributing**](https://github.com/FreeCodeCamp/FreeCodeCamp/blob/staging/CONTRIBUTING.md), thank you!.

**Comment by ltegman** [comment]
As BerkeleyBot has pointed out please remove the issue number from the PR title and add `closes #7171` into the body of the PR. In the future please follow our branch naming conventions.

**Comment by afr114** [comment]
Update per the Bot's request and guidelines.

**Comment by raisedadead** [comment]
:+1: 

Thanks @afr114

**Pull request merged**
