### PR TITLE
fix: restore missing reset button

### LINKED ISSUE #54360: Reset Code Button Missing
### Describe the Issue

The "reset" button went missing on the projects editor

### Affected Page

Any page with older style editor
https://www.freecodecamp.org/learn/javascript-algorithms-and-data-structures-v8/build-a-palindrome-checker-project/build-a-palindrome-checker

### Expected behavior

The reset button should be present.

### System

All

### PR DESCRIPTION
**Pull request by a2937**
Checklist:

- [X] I have read and followed the [contribution guidelines](https://contribute.freecodecamp.org).
- [X] I have read and followed the [how to open a pull request guide](https://contribute.freecodecamp.org/#/how-to-open-a-pull-request).
- [X] My pull request targets the `main` branch of freeCodeCamp.
- [X] I have tested these changes either locally on my machine, or GitPod.

Closes #54360

While it is not technically open for contribution yet, it does fix the final projects.

### CODE REVIEW

**Review by raisedadead — COMMENTED** [review]
Since this fixes a regression, can we add a quick test (jest is fine)?

**Comment by a2937** [comment]
Yeppers, but I would like to see the current tests we use for the client templates so I put this new one in the right folder.

**Comment by a2937** [comment]
image

Especially considering that even a simple screenshot is hardly enough to prove that this won't happen again.

**Comment by naomi-lgbt** [comment]
I'd playwright it, tbh.

**Comment by mmatsumoto1026** [comment]
It seems that help button's contents is wrapping onto two lines in small devices so the [two scroll bar issue in mobile devices](https://github.com/freeCodeCamp/freeCodeCamp/issues/48183) recur. (with viewport width <= 320px)

If the `get-help-dropdown` button's has the width which is more than 89px, the issue may be able to become avoidable.
<details>
<summary>preview of tool panel buttons in small device</summary>

help_button_contents_wrap_into_two_lines
</details>

**Comment by a2937** [comment]
Why did my test randomly fail in Chromium in regards to continuous integration? My playwright test and changes should be ready.

**Comment by naomi-lgbt** [comment]
Flaky test.

**Review by naomi-lgbt — APPROVED** [review]

**Review by Sembauke — APPROVED** [review]

**Pull request merged**
