### PR TITLE
fix(curriculum): improve wording

### LINKED ISSUE #44782: Suggested edit for step 18 in Learn basic CSS by Building a Cafe Menu project in Responsive Web Design(Beta)
## Affected page

The prompt currently says:

"So the styling of the page looks similar on mobile as it does on a desktop or laptop, you need to add a meta element with a special content attribute."

I think it it makes more sense to say:

"For the styling of the page to look similar on mobile as it does on a desktop or laptop, you need to add a meta element with a special content attribute."

Here is the link to the lesson:

https://github.com/freeCodeCamp/freeCodeCamp/blob/main/curriculum/challenges/english/14-responsive-web-design-22/learn-basic-css-by-building-a-cafe-menu/step-018.md

## Screenshots
Screenshot 2022-01-14 at 6 07 51 PM

### PR DESCRIPTION
**Pull request by SaarthakMaini**
Checklist:

- [x] I have read [freeCodeCamp's contribution guidelines](https://contribute.freecodecamp.org).
- [x] My pull request has a descriptive title (not a vague title like `Update index.md`)
- [x] My pull request targets the `main` branch of freeCodeCamp.
- [x] I have tested these changes either locally on my machine, or GitPod.

Closes #44782

### CODE REVIEW

**Review by deniselemonaki — COMMENTED** [review]
Hey, @SaarthakMaini , your pull request looks great. 

I probably didn't make it clear in the issue, but the code blocks for `meta` and `content` didn't need to be removed.

If you could add those back again, that would be great!

Thanks

**Comment by SaarthakMaini** [comment]
Yes , working on it

**Comment by SaarthakMaini** [comment]
I have made the required changes.  Thank you for your patience.

**Review by deniselemonaki — APPROVED** [review]
Looks great, thanks!

**Comment by SaarthakMaini** [comment]
This is my first time on an open-source contribution. Is there anything else that I have to do? Thank you

**Comment by deniselemonaki** [comment]
No, you're all good 👍

**Comment by SaarthakMaini** [comment]
Great! Thank you. Just one last question, when can I expect this to be merged?

**Review by huyenltnguyen — APPROVED** [review]
LGTM 👍

@SaarthakMaini Thank you for the PR and congratulations on your first contribution to this repo ✨ 🎉

We look forward to your next. Happy contributing!

**Comment by huyenltnguyen** [comment]
> Just one last question, when can I expect this to be merged?

@SaarthakMaini Just now 😛 

Thanks again for your contribution!

**Pull request merged**
