### PR TITLE
Modify tests in Bonfire - Diff Two Arrays

### PR DESCRIPTION
**Pull request by abhisekp**
Challenge: http://www.freecodecamp.com/challenges/bonfire-diff-two-arrays

Replace `assert.includeMembers` with `assert.deepEqual`

`assert.includeMembers` method gives faulty test for the challenge.
`assert.includeMembers` checks if the return superset value has the given subset.

This means that `[10, 1, "calf", 3, "piglet", 7, "filly", 5]` as superset will include the given subset `[1, "calf", 3, "piglet", 7, "filly"]`.
But rather it should check if the former is equal to the later value (not a subset of it).

The following code

``` js
function diff(arr1, arr2) {
  var newArr = [];
  // Same, same; but different.
  return [10, 1, "calf", 3, "piglet", 7, "filly", 5];
}
```

passes the following test 

``` js
assert.includeMembers(diff([1, "calf", 3, "piglet"], [7, "filly"]), [1, "calf", 3, "piglet", 7, "filly"], 'message: <code>[1, "calf", 3, "piglet"], [7, "filly"]</code> should return <code>[1, "calf", 3, "piglet", 7, "filly"]</code>.');
```

which it shouldn't.

### CODE REVIEW

**Comment by BerkeleyTrue** [comment]
This will force the output from diff to have to conform to what is defined in the test. While you case state above might pass one test it will not pass all tests.

**Comment by abhisekp** [comment]
@BerkeleyTrue Yes. You're right about passing one test and not all but that test case itself is not correct. So it needs corrections.

**Comment by BerkeleyTrue** [comment]
There is nothing wrong with the individual test. It has the desired effect. You haven't address the fact that this will force users to conform to the order of the array in the solution instead of getting the desired result of an array diffing algorithm.

**Comment by abhisekp** [comment]
@BerkeleyTrue why a **blocked** label?

Actually, you're right about **confirming the order**. The solution need not confirm the order. And using the **deepEquals** seems so wrong in this challenge. I think all tests should be using `includeMembers`. Shall I modify all the test cases to use `includeMembers` and make a PR?

**Comment by abhisekp** [comment]
@BerkeleyTrue But using the `includeMembers` has a problem. If there are duplicate values in one of the arrays, then the output should also show the duplicate values. So basically, the output should include the members and also their frequency of repeated values.

https://github.com/FreeCodeCamp/FreeCodeCamp/issues/3758
https://github.com/FreeCodeCamp/FreeCodeCamp/pull/3579

**Comment by BerkeleyTrue** [comment]
You keep looking at individual test cases as having to cover the whole solution space.

A solution must pass ALL the test cases. So if a single test is passable by some method other than the intended solution it is ok as long as it is caught by another test case. 

Can you provide a solution that passes all the test cases but shouldn't?

**Comment by abhisekp** [comment]
@BerkeleyTrue what I'm trying to say is the assert methods trying to solve the same problem (i.e. same kind of tests) should be consistent i.e. either use `deepEqual` or `includeMembers`. So either we use all `deepEqual` or all `includeMembers` but not mix them (a mess!?).

**Comment by BerkeleyTrue** [comment]
Again, can you provide a solution that passes all the test cases but shouldn't that this PR is intended to solve? If not then there is no reason to move to only use one or the other.

**Comment by SaintPeter** [comment]
@abhisekp I honestly can't tell what you're trying to say here.  
The tests AS A WHOLE test the functionality of the bonfire.  No individual test can test the whole scope of functionality in a Bonfire.  I agree that there are some Bonfires that have odd side cases or allow for alternate and wrong solutions, but I don't think this is one.

Technically, almost every single Bonfire could be "hard coded" to the tests.  I've seen some innocent attempts at that in the /Help channels, which I've cleared up.  I can't imagine someone going through and hard coding ALL of the Bonfires and then turning around and being able to do the Ziplines.

**Comment by BerkeleyTrue** [comment]
Closing. 

Thanks @abhisekp but this wouldn't improve the test suite for the challenge.


Happy Coding!

**Comment by abhisekp** [comment]
:cry: No one understood my feelings for this PR. :worried:

**Pull request closed without merging**
