### PR TITLE
fix(curriculum): typos in BETA  City Skyline section

### PR DESCRIPTION
**Pull request by Kernix13**
Checklist:

- [x] I have read [freeCodeCamp's contribution guidelines](https://contribute.freecodecamp.org).
- [x] My pull request has a descriptive title (not a vague title like `Update index.md`)
- [x] My pull request targets the `main` branch of freeCodeCamp.
- [x] I have tested these changes either locally on my machine, or GitPod.

Steps 22 & 24:  Changed the word `by` to `below` in the phrases `by the other one` for Step 22 and `by the other ones` for Step 24.

### CODE REVIEW

**Review by moT01 — COMMENTED** [review]
I don't think this change is particularly necessary, it seems clear to me what you are supposed to do. Sometimes it's not bad to be a little vague to let users figure it out. That said, this would work too, and I would be fine adding it if others are.

**Comment by Kernix13** [comment]
What I was thinking is that `by` implies `alongside`, which means on the same row. It's a minor change, I just thought that it was supposed to say `below`. It's definitely a minor change though. I can set it back if the original is preferred.

**Review by Sembauke — APPROVED** [review]

**Comment by Sembauke** [comment]
This sounds better to be honest

**Review by ShaunSHamilton — APPROVED** [review]
Thank you, for taking the time to contribute.

This LGTM 👍 

We look forward to even more contributions in the future!

**Pull request merged**
