### PR TITLE
Basic JS challenge: use-prototype-properties link added

### LINKED ISSUE #36754: Issue in JS Challenge Description of: Use Prototype Properties to Reduce Duplicate Code...
**Describe your problem and how to reproduce it:**
On the 3rd paragraph in the challenge description frame on the left a **prototype** is defined as an object. While this may be true for true object oriented languages like C#.net it may not be true in this context and confuse the reader.

The paragraph in question is given below and I added the necessary addition in bold:
"A better way is to use Bird’s prototype. The prototype is an object **property** that is shared among ALL instances of Bird. "

**Add a Link to the page with the problem:**
https://learn.freecodecamp.org/javascript-algorithms-and-data-structures/object-oriented-programming/use-prototype-properties-to-reduce-duplicate-code/

**Tell us about your browser and operating system:**
* Browser Name: Google Chrome
* Browser Version: Version 76.0.3809.132 (Official Build) (64-bit)
* Operating System: Windows 10

**If possible, add a screenshot here (you can drag and drop, png, jpg, gif, etc. in this box):**
prototype_is_a_property

### PR DESCRIPTION
**Pull request by Kbarias**
- [ x] I have read [freeCodeCamp's contribution guidelines](https://github.com/freeCodeCamp/freeCodeCamp/blob/master/CONTRIBUTING.md).
- [ x] My pull request has a descriptive title (not a vague title like `Update index.md`)
- [ x] My pull request targets the `master` branch of freeCodeCamp.
- [ x] None of my changes are plagiarized from another source without proper attribution.
- [ x] All the files I changed are in the same world language (for example: only English changes, or only Chinese changes, etc.)
- [ x] My changes do not use shortened URLs or affiliate links.

Closes #36754

I saw this issue and thought that there should be a clearer explanation of JavaScript prototypes. However, given that you don't want to put all this information about prototypes in the challenge description, I thought it made sense to have a link on where to learn more about them. This is done in a similar fashion to [this challenge](https://github.com/freeCodeCamp/freeCodeCamp/blob/master/curriculum/challenges/english/02-javascript-algorithms-and-data-structures/basic-javascript/increment-a-number-with-javascript.english.md).

### CODE REVIEW

**Comment by Kbarias** [comment]
Hello @raisedadead , I saw that you added the curriculum label to this issue a while back, was wondering if you could give me some input on how you would want to solve this?

**Comment by RandellDawson** [comment]
@Kbarias In general, we really want to avoid external links when possible inside the challenge.  This kind of information would be better place in the Hints section of the [Guide topic for this challenge](https://www.freecodecamp.org/forum/t/freecodecamp-challenge-guide-use-prototype-properties-to-reduce-duplicate-code/301336).

**Review by moT01 — CHANGES_REQUESTED** [review]
I agree with @RandellDawson here, external links in descriptions are supposed to try and be avoided. I am fine with having it in the forum hint, but that doesn't exactly solve the issue. 

I vote to change the sentence in the issue to this.. 
`Properties in the prototype are shared among ALL instances of Bird`

If @RandellDawson agrees, this PR can be changed to make that modification instead of the link added.

**Comment by RandellDawson** [comment]
@Kbarias I like @moT01's suggestion above.

**Review by RandellDawson — APPROVED** [review]

**Comment by RandellDawson** [comment]
@moT01 What do you think?

**Review by moT01 — APPROVED** [review]
Looks good @Kbarias - thank you for contributing to freeCodeCamp! 🎉

**Comment by Kbarias** [comment]
Thank you both for getting back to me so timely. I will be creating a GitHub issue as @RandellDawson suggested about what to do with links found in coding challenges.

**Pull request merged**
