### PR TITLE
Fix/rewrite-instructions

### LINKED ISSUE #8934: Rewrite of "Where do I belong" instructions
#### Where do I belong

https://www.freecodecamp.com/challenges/where-do-i-belong

#### Issue Description
I tried passing all the test cases and the output are supposed to be accepted but...

#### Browser Information

* Browser Name, Version: Google Chrome, 51.0.2704.79 m (64-bit)
* Operating System: Windows 7
* Mobile, Desktop, or Tablet:  Desktop

#### My Code
function getIndexToIns(arr, num) {
  // Find my place in this sorted array.
  arr.push(num);
  arr.sort(function(a, b){
    return a - b;
  });
  for(var i in arr){
    if(arr[i] == num){
      return i;
    }
  }
}

getIndexToIns([2, 20, 10], 19);

untitled

### PR DESCRIPTION
**Pull request by colorblast**
#### Pre-Submission Checklist

- [x] Your pull request targets the `staging` branch of FreeCodeCamp.
- [x] Branch starts with either `fix/`, `feature/`, or `translate/` (e.g. `fix/signin-issue`)
- [x] You have only one commit (if not, [squash](https://github.com/FreeCodeCamp/FreeCodeCamp/wiki/git-rebase#squashing-multiple-commits-into-one) them into one commit).
- [ ] All new and existing tests pass the command `npm run test-challenges`. Use `git commit --amend` to amend any fixes.
#### Type of Change

- [x] Small bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds new functionality)
- [ ] Breaking change (fix or feature that would change existing functionality)
- [ ] Add new translation (feature adding new translations)
#### Checklist:

- [x] Tested changes locally.
- [x] Closes currently open issue (replace XXXX with an issue no): Closes #8934 
#### Description

Clarify Where Do I Belong to return positive val.

Edited by @raisedadead

### CODE REVIEW

**Comment by erictleung** [comment]
@JonW27 above, please replace the `XXXX` in `Closes #XXXX` with `8934` so it reads `Closes #8934`. Also, the `[ ]` should only not have any spaces when you put an `x` so it should be `[x]`. Please make these changes before we can merge in your changes. Looks good otherwise!

**Comment by hopkinsju** [comment]
👍

**Comment by erictleung** [comment]
@JonW27 please squash your commits to just one. A link on how to squash commits is in your PR up above.

**Comment by Bouncey** [comment]
@JonW27 Do you need help with squashing your commits?

**Pull request merged**
