### PR TITLE
Added Developed By and the programming language used in development

### PR DESCRIPTION
**Pull request by mayank-khare**
- [x] I have read [freeCodeCamp's contribution guidelines](https://github.com/freeCodeCamp/freeCodeCamp/blob/master/CONTRIBUTING.md).
- [x] My pull request has a descriptive title (not a vague title like `Update index.md`)
- [x] My pull request targets the `master` branch of freeCodeCamp.
- [x] None of my changes are plagiarized from another source without proper attribution.
- [x] My article does not contain shortened URLs or affiliate links.

If your pull request closes a GitHub issue, replace the XXXXX below with the issue number.

Closes #XXXXX

### CODE REVIEW

**Comment by ArielLeslie** [comment]
You ignored a list of requirements including "My pull request has a descriptive title (not a vague title like `Update index.md`)". Descriptive titles and good explanations of changes are necessary for a well maintained codebase. Free Code Camp is choosing to relax some of its requirements to help people reach their Hacktoberfest goals, but this PR would normally be rejected. In the future, please help repository maintainers by providing useful titles and do not ignore contributing guidelines or requirements.

**Comment by RandellDawson** [comment]
Closed and Reopened this PR to attempt to resolve a specific Travis build failure.

**Review by moT01 — DISMISSED** [review]
Thanks for the PR @mayank-khare, but this doesn't really flow - [here's what your additions look like](https://github.com/freeCodeCamp/freeCodeCamp/blob/7da7134df2d5c309430fefbbf99e7b272db77559/guide/english/bsd-os/index.md) - maybe add a period? or make it flow a little better somehow?

**Review by huyenltnguyen — APPROVED** [review]
LGTM 👍 

@mayank-khare Thank you for the PR ✨ 🎉 We're happy to accept these changes and look forward to your future contributions.

Happy coding!

**Pull request merged**
