### PR TITLE
fix: make docs links relative

### LINKED ISSUE #38532: Broken links in README.md in docs
There are two links README.md in docs. Following are the two links 
1.  how to work on coding challenges.
2. set up freeCodeCamp locally
I am also adding screenshot to show more clearly that which links are broken.
image

so when we click on these links in README in docs it shows page not found

### PR DESCRIPTION
**Pull request by ojeytonwilliams**
Checklist:

- [x] I have read [freeCodeCamp's contribution guidelines](https://github.com/freeCodeCamp/freeCodeCamp/blob/master/CONTRIBUTING.md).
- [x] My pull request has a descriptive title (not a vague title like `Update index.md`)
- [x] My pull request targets the `master` branch of freeCodeCamp.
- [x] All the files I changed are in the same world language, for example: only English changes, or only Chinese changes, etc.

docsify has the base url of /docs/ while Github uses /
This makes the links relative so the links will work in both.

Closes #38532

### CODE REVIEW

**Review by raisedadead — APPROVED** [review]

**Comment by raisedadead** [comment]
I still think we should make it more obvious that the documentation will be available at the dedicated site? The readme in the docs directory could be renamed?

**Comment by ojeytonwilliams** [comment]
Yeah, that's configurable.  How about `contribute-homepage.md`?

**Comment by raisedadead** [comment]
Cool, I will make the change.

**Comment by ojeytonwilliams** [comment]
@raisedadead I went ahead, did that and then saw your message.

**Pull request merged**
