### PR TITLE
fix max heap insert function

### LINKED ISSUE #43138: Remove an Element from a Max Heap
## Affected page

https://www.freecodecamp.org/learn/coding-interview-prep/data-structures/remove-an-element-from-a-max-heap
## Your code

```
var MaxHeap = function() {
  this.heap = [null];
  this.insert = (ele) => {
    var index = this.heap.length;
    var arr = [...this.heap];
    arr.push(ele);
    while (ele > arr[Math.floor(index / 2)] && index > 1) {
      arr[index] = arr[Math.floor(index / 2)];
      arr[Math.floor(index / 2)] = ele;
      index = arr[Math.floor(index / 2)];
    }
    this.heap = arr;
  }
  this.print = () => {
    return this.heap.slice(1);
  }
  // Only change code below this line

  // Only change code above this line
};



```

## Expected behavior

insert method to add according to maxheap rules
## System

- Device: laptop [e.g. iPhone6, Laptop]
- OS: Windows 10[e.g. iOS 14, Windows 10, Ubuntu 20.4]
- Browser: chrome [e.g. chrome, safari]
- Version: [e.g. 22]

## Additional context

change line 10
      index = arr[Math.floor(index / 2)];
to
      index = Math.floor(index / 2);

### PR DESCRIPTION
**Pull request by anshul2807**
## Checklist:

- [X] I have read [freeCodeCamp's contribution guidelines](https://contribute.freecodecamp.org).
- [X] My pull request has a descriptive title (not a vague title like `Update index.md`)
- [X] My pull request targets the `main` branch of freeCodeCamp.
- [X] I have tested these changes either locally on my machine, or GitPod.

Closes #43138

## Before changes --
insert function not working according to max heap properties
## After changes --
insert function works according to max heap  properties

### CODE REVIEW

**Comment by ieahleen** [comment]
I've edited your post so that the PR is linked to the issue. That is done using [one of the keywords](https://docs.github.com/en/issues/tracking-your-work-with-issues/linking-a-pull-request-to-an-issue), "closes" is one of those

**Comment by anshul2807** [comment]
> I've edited your post so that the PR is linked to the issue. That is done using [one of the keywords](https://docs.github.com/en/issues/tracking-your-work-with-issues/linking-a-pull-request-to-an-issue), "closes" is one of those

Thanks Mate.

**Review by gikf — CHANGES_REQUESTED** [review]
Thanks for the PR @anshul2807. There's few details that might need changing. Could you take a look at the notes below?

Notes:
- Implementation moves also the initial first element in the heap (`null`), I don't think that should happening. Because of this behavior this version also wouldn't pass the previous challenge with heap (which also should be changed).
- It's a bit verbose. That's not necessarily a disadvantage on it own, but when code is just a part of the starting code for challenge, there's no need to add anything more than what's absolutely required. This includes comments as well, as generally only those from https://github.com/freeCodeCamp/freeCodeCamp/blob/main/curriculum/dictionaries/english/comments.json file should be used in the seed code.
- Could you use two spaces as an indentation per level? That's suggested indentation the per formatting guidelines.

**Comment by anshul2807** [comment]
> Thanks for the PR @anshul2807. There's few details that might need changing. Could you take a look at the notes below?
> 
> Notes:
> 
> * Implementation moves also the initial first element in the heap (`null`), I don't think that should happening. Because of this behavior this version also wouldn't pass the previous challenge with heap (which also should be changed).
> * It's a bit verbose. That's not necessarily a disadvantage on it own, but when code is just a part of the starting code for challenge, there's no need to add anything more than what's absolutely required. This includes comments as well, as generally only those from https://github.com/freeCodeCamp/freeCodeCamp/blob/main/curriculum/dictionaries/english/comments.json file should be used in the seed code.
> * Could you use two spaces as an indentation per level? That's suggested indentation the per formatting guidelines.

Sure, I will do that.

**Comment by anshul2807** [comment]
> Thanks for the PR @anshul2807. There's few details that might need changing. Could you take a look at the notes below?
> 
> Notes:
> 
> * Implementation moves also the initial first element in the heap (`null`), I don't think that should happening. Because of this behavior this version also wouldn't pass the previous challenge with heap (which also should be changed).
> * It's a bit verbose. That's not necessarily a disadvantage on it own, but when code is just a part of the starting code for challenge, there's no need to add anything more than what's absolutely required. This includes comments as well, as generally only those from https://github.com/freeCodeCamp/freeCodeCamp/blob/main/curriculum/dictionaries/english/comments.json file should be used in the seed code.
> * Could you use two spaces as an indentation per level? That's suggested indentation the per formatting guidelines.

Done.

**Review by gikf — COMMENTED** [review]
It's still a bit long for a starter code... scrolling is needed to see the whole, including the comments where put new method.
image

`print` method won't work properly without the `null` being at the start of heap array.

**Comment by anshul2807** [comment]
> It's still a bit long for a starter code... scrolling is needed to see the whole, including the comments where put new method.
> image
> 
> `print` method won't work properly without the `null` being at the start of heap array.

I fix the print method.
It was sill typo... I forget to add `,` this.

And for the *new method* , I can insert the comment at the top?

**Review by gikf — COMMENTED** [review]
What do you think about removing methods that are not used?

For the print function:
```js
const test = new MaxHeap();
test.insert(5);
test.insert(15);

console.log(test.print()) // [ 5 ]
```

**Comment by anshul2807** [comment]
@gikf 
> # Commit in this Push --:
- [x] remove extra functions
- [x] Fix Print function
- [x] Reduce the size of the code

**Review by gikf — COMMENTED** [review]
I've tried it with few examples, logic seems to be correct.

Below are few suggestions for some formatting changes for consistency.

**Review by gikf — APPROVED** [review]
Looks good! :+1: 

Note for future - it's recommended to use separate branch for making changes, instead of using the `main` branch of fork. You can read more about it in step 3 of https://contribute.freecodecamp.org/#/how-to-setup-freecodecamp-locally?id=making-changes-locally.

**Review by Sembauke — APPROVED** [review]

**Pull request merged**
