### PR TITLE
Update instructions for Stand in Line Challenge

### LINKED ISSUE #12067: Update instructions for Stand in Line Challenge
Challenge [Stand in Line](https://www.freecodecamp.com/challenges/stand-in-line#?solution=%0Afunction%20nextInLine(arr%2C%20item)%20%7B%0A%20%20%2F%2F%20Your%20code%20here%0A%20%20%0A%20%20return%20item%3B%20%20%2F%2F%20Change%20this%20line%0A%7D%0A%0A%2F%2F%20Test%20Setup%0Avar%20testArr%20%3D%20%5B1%2C2%2C3%2C4%2C5%5D%3B%0A%0A%2F%2F%20Display%20Code%0Aconsole.log(%22Before%3A%20%22%20%2B%20JSON.stringify(testArr))%3B%0Aconsole.log(nextInLine(testArr%2C%206))%3B%20%2F%2F%20Modify%20this%20line%20to%20test%0Aconsole.log(%22After%3A%20%22%20%2B%20JSON.stringify(testArr))%3B%0A) has an issue.
User Agent is: <code>Mozilla/5.0 (Windows NT 6.1; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/54.0.2840.99 UBrowser/5.6.12860.7 Safari/537.36</code>.
Please describe how to reproduce this issue, and include links to screenshots if possible.

My code:
```javascript

function nextInLine(arr, item) {
  // Your code here
  
  return item;  // Change this line
}

// Test Setup
var testArr = [1,2,3,4,5];

// Display Code
console.log("Before: " + JSON.stringify(testArr));
console.log(nextInLine(testArr, 6)); // Modify this line to test
console.log("After: " + JSON.stringify(testArr));

```

### PR DESCRIPTION
**Pull request by DarrenfJ**
#### Pre-Submission Checklist

- [x] Your pull request targets the `staging` branch of FreeCodeCamp.
- [x] Branch starts with either `fix/`, `feature/`, or `translate/` (e.g. `fix/signin-issue`)
- [x] You have only one commit (if not, [squash](http://forum.freecodecamp.com/t/how-to-squash-multiple-commits-into-one-with-git/13231) them into one commit).
- [ ] All new and existing tests pass the command `npm test`. Use `git commit --amend` to amend any fixes.

#### Type of Change

- [x] Small bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds new functionality)
- [ ] Breaking change (fix or feature that would change existing functionality)
- [ ] Add new translation (feature adding new translations)

#### Checklist:

- [ ] Tested changes locally.
- [x] Closes currently open issue (replace XXXX with an issue no): Closes #12067

#### Description

Update instructions for Stand in Line Challenge

Change instructions from 1 line to 3 (new paragraphs)
line 2747

### CODE REVIEW

**Comment by DarrenfJ** [comment]
Ah! I get it! I thought when you said you wanted to branch to be `fix/short-fix-description` you wanted the fix described in the first part but you 'literally' just want the word 'fix/'. 

Ha! d'oh... Apologies guys. Next time.

D

**Comment by raisedadead** [comment]
Thanks for the pull request @DarrenfJ !

Yes, except for the branch name the changes look neat. Just have a look at our contributing guidelines.

> Most importantly, please test your code locally and run the `npm test` on a command line. This is very important to know if anything is not broken by your change.

Happy fixing.

**Review by raisedadead — APPROVED** [review]
Code LGTM

**Comment by raisedadead** [comment]
Tested locally.

#### :sparkles: :sparkles: **LGTM.** :sparkles: :sparkles: 

Thanks and congrats @DarrenfJ on your first contrinution to Free Coce Camp!

**Comment by DarrenfJ** [comment]
Thanks guys! Looking forward to more.

**Pull request merged**
