### PR TITLE
Removed backslash. When I just removed the one the linter did not lik…

### PR DESCRIPTION
**Pull request by natac13**
When I just removed the one the linter did not like this so I replace with &#125 for right curly brace. 

I was also able to learn how mongodb and using gulp for first time! Thanks

### CODE REVIEW

**Comment by bugron** [comment]
@natac13 you omitted a semicolon in you HTML entity, i.e. `&#125&#41;` but it should be `&#125;&#41;`.

**Comment by natac13** [comment]
@bugron Thanks!

**Comment by bugron** [comment]
Nice fix!

**Comment by natac13** [comment]
@bugron Also thank you for telling me about how to auto close the issues by those key words in the commit message. I will do this from now on. My apologies

**Pull request merged**
