### PR TITLE
Fix es6 scopes challenge

### PR DESCRIPTION
**Pull request by Atomk**
#### Pre-Submission Checklist

- [x] Your pull request targets the `staging` branch of freeCodeCamp.
- [x] Branch starts with either `fix/`, `feature/`, or `translate/` (e.g. `fix/signin-issue`)
- [x] You have only one commit (if not, [squash](http://forum.freecodecamp.com/t/how-to-squash-multiple-commits-into-one-with-git/13231) them into one commit).
- [x] All new and existing tests pass the command `npm test`. Use `git commit --amend` to amend any fixes.

#### Type of Change

- [x] Small bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds new functionality)
- [ ] Breaking change (fix or feature that would change existing functionality)
- [ ] Add new translation (feature adding new translations)

#### Checklist:

- [x] Tested changes locally.
- [ ] Closes currently open issue (replace XXXX with an issue no): Closes #XXXX

#### Description

Added a "var" keyword to the challenge "[compare scopes of the var and let keywords](http://beta.freecodecamp.com/en/challenges/es6/compare-scopes-of-the-var-and-let-keywords)", which has to be changed to "let" by the user to successfully pass the challenge.

I also took the chance to add a bit of spaces here and there, I'm not sure if I'm a grammar/syntax freak or some people just don't care about looks when writing code.

### CODE REVIEW

**Comment by dhcodes** [comment]
@Atomk grammar/spacing issues look good. I'm fairly certain the second instance of `i` doesn't need `var` because the challenge is showing global vs. local scope so it is defined outside the function. Perhaps I'm mistaken though?

**Comment by Atomk** [comment]
@dhcodes If you declare `i` just at the top of the function, the other assignment to `i` will just overwrite its value and at the end the output will always be "block scope". Creating two variables, using `var` the result is the same, but by changing both to `let` the local variable in the `if` will not overwrite the function's one, because it's considered a different variable even if it has the same name. At least this is what seems to happen to me...

**Comment by dhcodes** [comment]
@Atomk right, but I think the point of the code at load is to show that the `i` within the if statement *does* override the value of the initial declaration. So that if the camper leaves the initial `var i` and only adds `let` to the `i` in the if `if` statement, the scope changes and the challenge passes. 

Also, in my testing adding `var` to the `i` declaration in the `if` statement doesn't change the output result. In other words, I think it's functioning as intended. I could definitely be wrong though so please another set of eyes @freeCodeCamp/moderators

**Comment by t3h2mas** [comment]
IMO If the challenge's goal is to show the scope of both let and var, then I have to agree with @dhcodes. Adding let to the variable in the IF passes the challenge and exemplifies this scope behavior. Using let as the first declaration works as well but doesn't show the difference in scoping between var and let.

**Comment by dhcodes** [comment]
@Atomk any update on this? You'll need to rebase and then remove the changes discussed above. The grammar and spacing issues are a go.

**Comment by dhcodes** [comment]
Closing as stale. Please reopen if you plan to make the updated changes.

**Comment by Atomk** [comment]
Sorry for bringing this up again, looking at the challenge I still don't think this is clear. I'll try a different approach.
The initial code is:
```javascript
function checkScope() {
  var i = "function scope";
  if (true) {
    i = "block scope";
    console.log("Block scope i is: ", i);
  }
  console.log("Function scope i is: ", i);
  return i;
}
```

The challenge instructions say:
> Fix the code so that `i` **declared** in the if statement is a separate variable than `i` declared in the first line of the function.

The fact is the `i` in the if statement is not a declaration, it is simply an assignment. To make it a declaration, you'd have to add `var` or `let` before it. I believe the author of the challenge forgot to declare the second variable, that is what confused me and this is why I made this pull request.

**Comment by no-stack-dub-sack** [comment]
@Atomk @dhcodes I agree with @dhcodes that the original intent of the challenge is to have the user declare the second `i` as let, and that `var` was not left off. Rather, it's probably just a misuse of the word "declared". I think we can probably leave the challenge code alone, but maybe fix the instructions instead, being careful about the semantics of the word "declare".

e.g. newly proposed instructions:

> Fix the code, using the ES6 `let` keyword, so that the second `i` within the `if` statement is declared as a separate variable that will not overwrite the first `i` declared in the first line of the function. Be certain not to use the `var` keyword anywhere in your code.

**Pull request closed without merging**
