### PR TITLE
fix(curriculum): don't block fragment links

### LINKED ISSUE #46244: Navigating to a fragment counts as an external link
### Describe the Issue

I assume the idea of the link alert is to avoid the camper accidentally navigating away from the challenge page. But it would be nice if fragment links would work as expected.

Something like this seems to work.

`https://github.com/freeCodeCamp/freeCodeCamp/blob/main/client/src/templates/Challenges/utils/frame.ts`

```
if(element && element.nodeName === 'A' && new URL(element.href).hash === '') {
  e.preventDefault();
  window.parent.window.alert('Normally this link would bring you to another website! It works!' + ' This is a link to: ' + '(' + element.href + ')');
}
```

Is there any reason not to do this?

### Affected Page

Any page with a fragment link

### Your code

```

```

### Expected behavior

A fragment link should scroll the page and not give an alert.

### Screenshots

_No response_

### System

- Device: [e.g. iPhone 6, Laptop]
- OS: [e.g. iOS 14, Windows 10, Ubuntu 20.04]
- Browser: [e.g. Chrome, Safari]
- Version: [e.g. 22]

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by lasjorg**
Checklist:

- [x] I have read [freeCodeCamp's contribution guidelines](https://contribute.freecodecamp.org).
- [x] My pull request has a descriptive title (not a vague title like `Update index.md`)
- [x] My pull request targets the `main` branch of freeCodeCamp.
- [x] I have tested these changes either locally on my machine, or GitPod.

Closes #46244 

Fix for fragment links counting as external links blocking the fragment navigation.

### CODE REVIEW

**Comment by raisedadead** [comment]
Hey Lasse, mind sending me a DM on Chat or forum?

**Comment by lasjorg** [comment]
@raisedadead I send you a PM on the forum.

I'm not really sure which chat you are referring to and I don't really use the ones I know about. Is it all on Discord now?

**Review by raisedadead — APPROVED** [review]
LGTM.

**Review by ojeytonwilliams — APPROVED** [review]
LGTM :+1:

**Pull request merged**
