### PR TITLE
feat(client): make UX changes to be aligned for release

### LINKED ISSUE #35102: Improvements to Footer
**Expected behavior**
Please see attached screenshot for more details.

Basically: 
- [x] "Contact email" should be "Email Us"
- [x] We should get rid of the outbound link icons
- [ ] The footer should always go below the tallest element. Currently on the Guide, it seems to go under the least tall element.

**Screenshots**

echo_and_print___freecodecamp_guide

### PR DESCRIPTION
**Pull request by raisedadead**
Hi Everyone! 

One of our goals is to make our challenge (learn) views into a single column layout.

But, we have come the conclusion that tweaking the UI every few weeks, will confuse the users. We should instead do it only once.

That said, refactoring the UX will make master's release a potential show-stopper. This will also cascade to tons of fixes that we have already done since our last major release. We want to push all those changes out with minimal friction. The most notable being hundreds of fixes to coding challenges.

To push master towards production, we are reverting some of the UX changes that we have done recently. 

Please note, we are not throwing away all the hard work that has gone into the UX. Instead we are going to branch off on a dedicated UX branch and keep moving further. 

We are planning for the second release of master while we are still finalising on the first release.

If you have worked on something related to the UX, and see this PR revert some of it, please do not feel disappointed. We are simply aligning our priorities in the best interest of the users.

We will make our best efforts, and preserve changes on a separate branch for one of the upcoming releases.

Thanks for your hard work and valued contribution.

Currently our immediate aim is to:

- Make the UX of the master same as of current production.
- Add footer views only on pages other than Learn.
- Updates the Nav and Links to Change "Curriculum" to "Learn" as a Label.
  Note: Curriculum will still be used in other verbiage like a welcome greeting.

Reverts #35209
Closes #35235
Closes #35102

### CODE REVIEW

**Comment by raisedadead** [comment]
@QuincyLarson once the dev team has reviewed the code, you should come back to this PR and have a quick look on the version.

**Comment by ahmadabdolsaheb** [comment]
Thanks for the update that is great news which allows us to design, implement,  and test the new components better before we ship them to campers.

the PR LGTM. 

Note: since the curriculum map page is part of learn, the footer does not appear in there either. I was not sure if that was intended or not. In any case, we could improve on conditional rendering and custom rendering the footer in the future iterations.

**Comment by raisedadead** [comment]
> Note: since the curriculum map page is part of learn, the footer does not appear in there either. I was not sure if that was intended or not. In any case, we could improve on conditional rendering and custom rendering the footer in the future iterations.

Yes, it is intentional. The map is to be made simpler too. So, its best we leave it for now.

**Review by Bouncey — CHANGES_REQUESTED** [review]
You made some changes to formatting that are not required in ` client/src/templates/Challenges/components/Tool-Panel.js` if you could undo that.

The rest of the PR looks good to me.

**Comment by raisedadead** [comment]
Can you confirm these unwanted changes are present in https://github.com/freeCodeCamp/freeCodeCamp/commit/dcae207aadff10226e7351f119712e04ac4c8b59?

**Review by Bouncey — APPROVED** [review]

**Pull request merged**
