### PR TITLE
fix(curriculum): typos in BETA Balance Sheet section

### PR DESCRIPTION
**Pull request by Kernix13**
Checklist:

- [x] I have read [freeCodeCamp's contribution guidelines](https://contribute.freecodecamp.org).
- [x] My pull request has a descriptive title (not a vague title like `Update index.md`)
- [x] My pull request targets the `main` branch of freeCodeCamp.
- [x] I have tested these changes either locally on my machine, or GitPod.

Step 34 Removed the word `the` from the phrase ` within the :not()`, though keeping `the` and adding `pseudo-class` after `not()` would also work. I think the latter would be better since pseudo selectors if the focus of this section.
Step 46 Changed `:active` to `:focus` since that is the required CSS selector for the lesson.
Step 50 Removed the last comma in the 2nd paragraph
Step 51 Removed `-` and added a period then capitalized  `create`

### CODE REVIEW

**Comment by Kernix13** [comment]
If anyone sees this, should I wait for this to be resolved? Is there something I should do on my end?

**Review by naomi-lgbt — APPROVED** [review]
This looks good to me!

**Review by ShaunSHamilton — APPROVED** [review]
LGTM 👍

**Comment by ShaunSHamilton** [comment]
Thank you for your contribution to the page! 👍
We are happy to accept these changes, and look forward to future contributions. 🎉

**Pull request merged**
