### PR TITLE
REMOVED comments

### PR DESCRIPTION
**Pull request by supzi-del**
Fixes(added comments) freeCodeCamp/freeCodeCamp#40903

### CODE REVIEW

**Comment by nhcarrigan** [comment]
Hey there,

Thank you for submitting this PR. However, as discussed in the issue, rather than adding comments to this challenge we want to remove them entirely.

**Comment by supzi-del** [comment]
Oh okay, will do!

**Review by naomi-lgbt — APPROVED** [review]
Looks good to me.

**Review by RandellDawson — APPROVED** [review]

**Comment by RandellDawson** [comment]
Congrats @supzi-del on your first pull request (PR)! 🎉

Thank you for your contribution to the page! 👍
We're happy to accept these changes, and look forward to future contributions. 📝

**Pull request merged**
