### PR TITLE
Add Missing full stops/periods in Registration Form project instructi…

### LINKED ISSUE #46195: New RWD: Missing full stops/periods in Registration Form project instructions.
### Describe the Issue

Please add full stops/periods to the sentences in the Registration Form project! This is like the written word equivalent of not closing tags! :rofl:

This affects Step 6 and Step 24.

“Please fill out this form with the required information.”
“I accept the terms and conditions.”

### Affected Page

https://www.freecodecamp.org/learn/2022/responsive-web-design/learn-html-forms-by-building-a-registration-form/step-6, https://www.freecodecamp.org/learn/2022/responsive-web-design/learn-html-forms-by-building-a-registration-form/step-24

### Steps to Reproduce

None. Visit affected pages at https://www.freecodecamp.org/learn/2022/responsive-web-design/learn-html-forms-by-building-a-registration-form/step-6
and
https://www.freecodecamp.org/learn/2022/responsive-web-design/learn-html-forms-by-building-a-registration-form/step-24

### Recommended fix or suggestions

Step 6: “Please fill out this form with the required information.” instead of “Please fill out this form with the required information”
Step 24: “I accept the terms and conditions.” instead of "I accept the terms and conditions"

### Screenshots

_No response_

### PR DESCRIPTION
**Pull request by Aarushi5g**
Checklist:

- [x] I have read [freeCodeCamp's contribution guidelines](https://contribute.freecodecamp.org).
- [x] My pull request has a descriptive title (not a vague title like `Update index.md`)
- [x] My pull request targets the `main` branch of freeCodeCamp.
- [x] I have tested these changes either locally on my machine, or GitPod.

Closes #46195

### CODE REVIEW

**Comment by lynxlynxlynx** [comment]
As was mentioned in the issue, you need to update all occurrences, so as not to create more confusion for learners.

**Review by majestic-owl448 — CHANGES_REQUESTED** [review]
as this text is directly checked by the tests, we can't change this without changing the tests

also, all subsequent challenges would also the seed code of all subsequent challenges would need to be updated for consistency

**Comment by moT01** [comment]
As @ieahleen mentioned, the tests need changing, along with the seed code for all the steps after each of these two that are changed here. I really don't think these changes are necessary, they seem pretty inconsequential to me and, I think, not as the designer intended - so I would vote not to make this change.

**Comment by raisedadead** [comment]
Thanks for taking the time everyone, I checked the issue and we can close this.

**Pull request closed without merging**
