### PR TITLE
feat: create modal component with radix-ui

### LINKED ISSUE #52922: [UI Components] Create Modal component
This issue is to track the implementation of the new Modal component in the `ui-components` library. The issue is actually created after the fact, and the PR for the implementation is https://github.com/freeCodeCamp/freeCodeCamp/pull/51070.

I'm using this issue to document the technical design and decision as I'm reviewing the PR.

### Behaviors

- Closes on Escape press

### Styling

- Has 30px top and bottom margin on large screen size (`min-width: 768px`)
- Has 10px margin on all sides on smaller screen size
- The height grows with the content
- The width follows the Bootstrap sizes ([ref](https://github.com/twbs/bootstrap/blob/f17f882df292b29323f1e1da515bd16f326cee4a/less/variables.less#L616-L618)):
  - `lg` or `large`: 900px wide
  - `md`: 600px wide
  - `sm` or `small`: 300px wide
- Has a 1px solid border on all sides (set by the `modal-content` class)
- Header:
  - The text is centered
  - `margin: 0`
  - `line-height: 1.42857143`
  - Has a 1px solid bottom border
- Body:
  - The content is centered
- Footer: 
  - Has a 15px padding on all sides and a 1px solid top border
  - The content is centered
- When the modal opens, a backdrop with `background-color: #000` and `opacity: 0.5` appears and sits on top of the background content
- Has default and danger variants
  - Default:
    - The border color is `--secondary-color`
    - The background color of the header, body, and footer is `--secondary-background`
    - The color of the text content is `--secondary-color`
    - The variant of the primary and secondary buttons is `primary`
  - Danger:
    - The border color is `--secondary-color`
    - The background color of the header is `--danger-background`
      - Note that this is only for some danger modals (`reset-modal` is an example), though in the new Modal version we should apply this styling to all danger modals for consistency
    - The color of the text content is `--danger-color`
    - The primary button has the `danger` variant
    - The secondary button is optional, and has the `primary` variant
    - If both the primary and secondary buttons are present, display the secondary button first then primary (see #52615)

#### Modal variants 

<detail>
  <summary>Modal variants with screenshots</summary>

| Variant | Theme | Screenshot |
| --- | --- | --- |
| Default | Light | Screenshot 2024-01-23 at 17 23 47 |
| Default | Dark | Screenshot 2024-01-23 at 17 17 02 |
| Danger | Light | Screenshot 2024-01-23 at 17 24 42 |
| Danger | Dark | Screenshot 2024-01-23 at 17 14 06 |

</detail>

#### Modal position on different screen sizes

<detail>

<summary>Modal position on different screen sizes with screenshots</summary>

| Screen size | Screenshot |
| --- | --- |
| Width being 768px or above | Screenshot 2024-01-24 at 16 38 06 |
| Width being less than 768px | Screenshot 2024-01-24 at 16 37 57 |

</detail>

### Components

- `Modal`
- `Modal.Header`
- `Modal.Title`
- `Modal.Body`
- `Modal.Footer`

### Props interface

This section contains props that are used in our codebase. The information of the props is copied from https://react-bootstrap-v3.netlify.app/components/modal/#modals-props.

#### `Modal`

| Prop | Type | Required | Default | Description |
| --- | --- | --- | --- | --- |
| `animation` | boolean | | `true` | Open and close the Modal with a slide and fade animation. |
| `backdrop` | `'static'` \| `true` \| `false` | | | Include a backdrop component. Specify `'static'` for a backdrop that doesn't trigger an `onHide` when clicked. |
| `bsSize` | `'lg'` \| `'large'` \| `'sm'` \| `'small'` |  |  | Component size variations. |
| `dialogClassName` | | | | A css class to apply to the Modal dialog DOM node. |
| `keyboard` | boolean | | | Close the modal when escape key is pressed. | 
| `onExited` | function | | | Callback fired after the Modal finishes transitioning out. |
| `onHide` | function | | | A callback fired when the header close button or non-static backdrop is clicked. Required if either are specified. |
| `show` | boolean | | | When `true` the modal will show itself. |

**Notes**:
- `bsSize` has the follow values ([ref](https://github.com/twbs/bootstrap/blob/f17f882df292b29323f1e1da515bd16f326cee4a/less/variables.less#L616-L618)):
  - `lg` or `large`: 900px wide
  - `md`: 600px wide
  - `sm` or `small`: 300px wide
- `SignoutModal` passes `onClose` to `Modal`, but this prop appears to be ineffective/redundant as `react-bootstrap` doesn't have this prop listed in the prop table
    https://github.com/freeCodeCamp/freeCodeCamp/blob/720af416174cf1d3c150b69ecafdaa9546b53342/client/src/components/signout-modal/index.tsx#L57
- `ExamResultsModal` passes `size` to `Modal`, but this prop appears to be ineffective/redundant as `react-bootstrap` doesn't have this prop listed in the prop table
    https://github.com/freeCodeCamp/freeCodeCamp/blob/720af416174cf1d3c150b69ecafdaa9546b53342/client/src/components/SolutionViewer/exam-results-modal.tsx#L60
- `ProjectModal` passes `size` to `Modal`, but this prop appears to be ineffective/redundant as `react-bootstrap` doesn't have this prop listed in the prop table
    https://github.com/freeCodeCamp/freeCodeCamp/blob/720af416174cf1d3c150b69ecafdaa9546b53342/client/src/components/SolutionViewer/project-modal.tsx#L32
- `StagingWarningModal` passes `onClose` to `Modal`, but this prop appears to be ineffective/redundant as `react-bootstrap` doesn't have this prop listed in the prop table
    https://github.com/freeCodeCamp/freeCodeCamp/blob/720af416174cf1d3c150b69ecafdaa9546b53342/client/src/components/staging-warning-modal/index.tsx#L27
- `CompletionModal` passes `onKeydown` to `Modal`. This prop isn't listed in the `react-bootstrap`'s prop table but appears to be needed / in effect
    https://github.com/freeCodeCamp/freeCodeCamp/blob/720af416174cf1d3c150b69ecafdaa9546b53342/client/src/templates/Challenges/components/completion-modal.tsx#L176

#### `Modal.Header`

| Prop | Type | Required | Default | Description |
| --- | --- | --- | --- | --- |
| `closeButton` | boolean | | `false` | Specify whether the component should contain a close button. |

#### `Modal.Title`

| Prop | Type | Required | Default | Description |
| --- | --- | --- | --- | --- |
| `children` | `ReactNode` | | | Title of the modal. |

#### `Modal.Body`

| Prop | Type | Required | Default | Description |
| --- | --- | --- | --- | --- |
| `children` | `ReactNode` | | | Content of the modal. |

#### `Modal.Footer`

| Prop | Type | Required | Default | Description |
| --- | --- | --- | --- | --- |
| `children` | `ReactNode` | | | Footer of the modal, usually is a button or a group of buttons. |

---

### Dependencies

We will use the `Dialog` component of `radix-ui`. 

Doc: https://www.radix-ui.com/primitives/docs/components/dialog.

### Components and sub-components

Sub-components:
- `Close`: The "x" button
- ~~`Trigger`: The button that triggers/opens the modal~~
  - We don't need this at the moment since we've been triggering dialogs via redux
- `Description`: The body of the modal
- `ModalLayer`: The `Portal` that the modal is rendered in
  - Note: The portal must be rendered under an element with the class `light-palette` or `dark-palette` in order to be themed properly
- `ModalTitle`: The title of the modal
- `ModalHeader`: The header of the modal. This section includes `ModalTitle` and `Close`
- `ModalFooter`: The footer of the modal. This section includes buttons for the actions

We will expose a single `Modal` component, which encapsulates sub-components. 

Public components are:
- `Modal`
- `Modal.Header`
- `Modal.Title`
  - We are exporting this component to ease the migration process. But in the future, I think we could turn this into a `title` prop of `Modal.Header` and only use `Modal.Header` to compose modal
- `Modal.Body`
- `Modal.Footer`

#### `Modal`

| Prop | Type | Required | Default | Description |
| --- | --- | --- | --- | --- |
| `size` | `'large'` \| 'medium' |  | 'medium' | Component size variations. |
| `variant` | `'default'` \| `'danger'` |  |  | Component style variations. |
| `onExited` | function | | | A callback fired after the Modal finishes transitioning out. |
| `open` | boolean | | | When `true` the modal will show itself. |
| `onClose` | function | | | A callback responsible for the close action. |

Notes:
- We should build the Bootstrap's `animation` and `backdrop` behaviors into the Modal component, so that the modal display is consistent
- We should build the Bootstrap's `keyboard` behavior into the Modal component to ensure the component is accessible

#### `Modal.Header`

| Prop | Type | Required | Default | Description |
| --- | --- | --- | --- | --- |
| `children` | `ReactNode` | | | Content of the header, usually the modal title, rendered by the `Modal.Title` component. |
| `showCloseButton` | `boolean` | | `true` | Whether the header should contain a close button. |

Note: We are currently using `Modal.Header` with `closeButton={true}` in all modals, except for `donation-modal`. Setting the default value to `true` would improve the DX a little as we don't have to specify this prop in most cases.

#### `Modal.Title`

| Prop | Type | Required | Default | Description |
| --- | --- | --- | --- | --- |
| `children` | `ReactNode` | | | Title of the modal. |

#### `Modal.Body`

| Prop | Type | Required | Default | Description |
| --- | --- | --- | --- | --- |
| `children` | `ReactNode` | | | Content of the modal. |

#### `Modal.Footer`

| Prop | Type | Required | Default | Description |
| --- | --- | --- | --- | --- |
| `children` | `ReactNode` | | | Footer of the modal, usually is a button or a group of buttons. |

## Usage example

```tsx
const MyModal = () => (
  <Modal show={show}>
    <Modal.Header>
      <Modal.Title>Modal title</Modal.Title>
    </Modal.Header>

    <Modal.Body>
      // content
    </Modal.Body>

    <Modal.Footer>
      <Button>Button one</Button>
      <Button>Button two<Button>
    </Modal.Footer>
  </Modal>
)
```

## References

- Bootstrap Modal documentation: https://react-bootstrap-v3.netlify.app/components/modal/
- Bootstrap Modal styling: https://github.com/twbs/bootstrap/blob/f17f882df292b29323f1e1da515bd16f326cee4a/less/modals.less

### PR DESCRIPTION
**Pull request by Sboonny**
Checklist:

- [x] I have read and followed the [contribution guidelines](https://contribute.freecodecamp.org).
- [x] I have read and followed the [how to open a pull request guide](https://contribute.freecodecamp.org/#/how-to-open-a-pull-request).
- [x] My pull request targets the `main` branch of freeCodeCamp.
- [x] I have tested these changes either locally on my machine, or GitPod.

Closes #52922

### CODE REVIEW

**Comment by ahmaxed** [comment]
@Sboonny, is this ready for review? let me know if you would like me to take it from here.

**Comment by Sboonny** [comment]
Not yet, the styles need more fixing.

BTW, take a look at https://github.com/freeCodeCamp/freeCodeCamp/pull/51070/commits/2178edf17ca81c4a5888599548f1be6ac8ba2aea, because Radix dialog is different from the bootstrap, and will require refactoring in the codebase, the transition from the components isn't smooth, are you okay with that?

**Comment by ahmaxed** [comment]
The transition is fine, but the modal needs to have a way to open from the sagas as a lot of the logic lives there.

**Comment by ahmaxed** [comment]
Refactoring the open modal logic from the sagas will take more time than creating a bootstrap modal clone.
So if radix modals(dialog), can be triggered using a prop from outside the modal component, we should be able to have multiple modal components similar to the current implementation and pop them based on redux state. Is that correct?

**Comment by Sboonny** [comment]
is the issue time?

Btw, it's possible, idk if it's the right approach, idk what happens to the focus when lost, so this will need to tested as well.

**Comment by ahmaxed** [comment]
> is the issue time?

Essentially that is why we are using radix/headlessui.

> Btw, it's possible, idk if it's the right approach, idk what happens to the focus when lost, so this will need to be tested as well.

Well noted. I can take a look into it. Focus might be tricky as you mentioned.

**Comment by Sboonny** [comment]
if the issue is time, I will leave it to you how it is handled then, whether the refactoring is done in the following PR to reduce the complexity, or moved to contributors to handle it.

**Comment by ahmaxed** [comment]
I added your modal to the completion modal, and it is working nicely 9a8c3e8a97a518017ef69389efd762267048f7f0.  😎 
The footer/header get misplaced and the styles need some work, but the component is functional.

Since you have the most context about the component, I was wondering if you could finalize it if possible?

**Comment by Sboonny** [comment]
I will finalize it in the weekend 👍

**Comment by Sboonny** [comment]
I have misused `Modal.Content`, it should have replaced how the old `Modal` looks, now we have the old Modal through `Modal.Layer`, and the ability to trigger it in local scope through `Modal`, `Modal.Trigger`, and `Modal.Close`. 👍

**Comment by joinGitHub-space** [comment]
> Checklist:
> 
> * [x]  I have read and followed the [contribution guidelines](https://contribute.freecodecamp.org).
> * [x]  I have read and followed the [how to open a pull request guide](https://contribute.freecodecamp.org/#/how-to-open-a-pull-request).
> * [x]  My pull request targets the `main` branch of freeCodeCamp.
> * [x]  I have tested these changes either locally on my machine, or GitPod.
> 
> Closes #52922

https://github.com/freeCodeCamp/freeCodeCamp/pull/51070#issue-1824547112

**Review by joinGitHub-space — COMMENTED** [review]
pnpm-lock.yaml

**Comment by ahmaxed** [comment]
Glad to hear that. Looking forward to see how it looks in learn 🙌

**Pull request closed without merging**
