### PR TITLE
ci(azure): Set up CI with Azure Pipelines

### PR DESCRIPTION
**Pull request by raisedadead**

### CODE REVIEW

**Comment by kaylangan** [comment]
I'm a Program Manager on Azure Pipelines. I realize this PR is closed, but let me know if you have any questions or suggestions. I'm happy to help!

**Comment by raisedadead** [comment]
Hi there,

Thanks for reaching out. 

Please ignore the PR. This was just a small spike. I was just testing out some things on the Azure Pipelines.

Going forth, we will be using the pipelines for our deployments. 

As for this PR itself, we figured out the visual editor on Pipelines is a rather great feature and sufficient for our needs at the minute. We might add the configurations to source control in future, if the needs change.

Thanks again, will definitely reach out to you with queries.

**Comment by willsmythe** [comment]
@raisedadead - awesome to hear that you are planning to use Azure Pipelines! I work with Kayla and was playing around with getting freeCodeCamp (next) building in Pipelines and visualizing the test results so that users don't have to dig through the logs when a test fails.

Here's an example (I injected a change to force a test to fail):

image

You can access the build I defined here:
https://dev.azure.com/willsmythe/freeCodeCamp/freeCodeCamp%20Team/_build?definitionId=22&_a=summary

I currently only publish "client" test results, but it wouldn't take much to add server, tools, etc. For client, the `jest-junit` reporter is used to produce a junit.xml file that gets published as a step in the build.

For the build configuration, I created a simple [azure-pipelines.yml](https://github.com/willsmythe/freeCodeCamp/blob/next/azure-pipelines.yml) (although I agree the visual designer is a great feature):

```
pool:
  vmImage: 'Ubuntu-16.04'

steps:
- task: NodeTool@0
  inputs:
    versionSpec: '8.x'
  displayName: 'Install Node.js'

- script: |
    npm ci
  displayName: 'npm ci'

- script: |
    npm run test-ci
  displayName: 'npm run test-ci'

- task: PublishTestResults@2
  condition: always()
  inputs:
    testResultsFormat: 'JUnit'
    testResultsFiles: 'client/junit.xml' 
    testRunTitle: 'Client'
```

The one "extra" step I took, which wasn't required but made the test results easier to view, was some tweaks to the `client/jest.config.js` mainly because of the way title, classname (filename), etc were getting set (or not) for your Enzyme test results:

```
{
  reporters: [ 
    [ 'default', {} ],
    [ 'jest-junit', {
        classNameTemplate: "{filepath}",
        ancestorSeparator: " > ",    
        titleTemplate: (vars) => {      
          return (vars.classname ? vars.classname + " " : "") + vars.title;
        },
        suiteNameTemplate: (vars) => {
          return vars.title || vars.filename;
        }
      }
    ]
  ]
}
```

If you're interested, here's my fork: https://github.com/willsmythe/freeCodeCamp

Let us know if you have any questions ... we're here to help.

**Comment by raisedadead** [comment]
@willsmythe 

Awesome! Thanks a lot for taking the time to prepare this spike for us. This definitely looks promising. We will add this to config, and probably into the version control, when we go live. BTW, we are in the middle of a re-architecture, before using pipelines for all 6 production environments. So yes we will have questions.

If its all the same, can I reach you guys somewhere other than this tracker? If thats okay, can you drop me a mail at `mrugesh at freecodecamp dot org` saying hi?

I'll get back to you with our queries.

Thanks.

**Comment by willsmythe** [comment]
@raisedadead - sent. Looking forward to chatting more when you're ready.

**Pull request closed without merging**
