### PR TITLE
Remove Double If Statement

### PR DESCRIPTION
**Pull request by adamisntdead**
#### Pre-Submission Checklist

- [x] Your pull request targets the `staging` branch of FreeCodeCamp.
- [x] Branch starts with either `fix/`, `feature/`, or `translate/` (e.g. `fix/signin-issue`)
- [x] You have only one commit (if not, [squash](https://github.com/FreeCodeCamp/FreeCodeCamp/wiki/Git-Squash) them into one commit).
- [x] All new and existing tests pass the command `npm run test-challenges`. Use `git commit --amend` to amend any fixes.
#### Type of Change

- [x] Small bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds new functionality)
- [ ] Breaking change (fix or feature that would change existing functionality)
- [ ] Add new translation (feature adding new translations)
#### Checklist:

- [x] Tested changes locally.
#### Description

The Regex Test was running twice, so changed to an 'If Else' Statement, so that there is only one regex test running.

### CODE REVIEW

**Comment by Bouncey** [comment]
@adamisntdead Was this raised in reference to an issue?

If not, can you provide more information on what issue this resolves?

**Comment by erictleung** [comment]
@Bouncey it's based on a conversation in the HelpContributors room :point_up: [July 5, 2016 10:30 AM](https://gitter.im/FreeCodeCamp/HelpContributors?at=577beecf64f940856a123855). Looks like @BerkeleyTrue has [okayed](https://gitter.im/FreeCodeCamp/HelpContributors?at=577c56f664f940856a184b4c) it.

**Comment by BerkeleyTrue** [comment]
This is fine. Not really sure why I did it that way so a QA is in order.

**Comment by atjonathan** [comment]
#### **LGTM :+1:**
Thanks for contributing :tada:

**Pull request merged**
