### PR TITLE
Reset previous commit, kept Step 23 change

### PR DESCRIPTION
**Pull request by Kernix13**
Checklist:

- [x] I have read [freeCodeCamp's contribution guidelines](https://contribute.freecodecamp.org).
- [x] My pull request has a descriptive title (not a vague title like `Update index.md`)
- [x] My pull request targets the `main` branch of freeCodeCamp.
- [x] I have tested these changes either locally on my machine, or GitPod.

I don't know what I am doing. I was trying to delete this branch but I used `git push --set-upstream origin fix/registrationform-typos` because I could not delete the branch locally. Can you delete this PR? 

I keep getting this message 

> warning: deleting branch 'fix/registrationform-typos' that has been merged to
         'refs/remotes/origin/fix/registrationform-typos', but not yet merged to HEAD.
Deleted branch fix/registrationform-typos (was edcaaa6ae0).

But when I do `git branch -a` it is still there.

### CODE REVIEW

**Comment by gikf** [comment]
Why create new PR, this is already merged? Once PR was merged to `freeCodeCamp:main`, you can safely remove local branch. If `git branch -d <pr-branch>` results in error that it was not yet merged, you can use `git branch -D <pr-branch>` to force deletion.

**Comment by Kernix13** [comment]
> Why create new PR?

It was an accident. For some reason, I can't delete the branches on my machine.

**Comment by gikf** [comment]
Yes, you can safely delete `fix/registrationform-typos` branch on your fork, and locally. I've shortly explained above what can be done to delete local branch.

Please try to avoid making PRs when you are unsure about outcome. If you have questions regarding contributing please feel free reach out on chat and/or forum.

**Comment by Kernix13** [comment]
I did try `-D` and that didn't work either - sorry about the extra work.

**Comment by gikf** [comment]
Come on chat or post on forum and we'll try to figure it out.

**Comment by Kernix13** [comment]
I'll go to the chat next time for sure. There must be a delay because the branch was gone this morning. But then I console wouldn't load - it was blank. I had to reload VS Code. I did what I did because I thought I was pushing to my clone copy on GitHub. I'm reading up on the difference between upstream and origin and main and...

**Pull request closed without merging**
