### PR TITLE
Updated Numerical Properties doc

### PR DESCRIPTION
**Pull request by joesvetz**
Fixed type-os, corrected incorrect information, cleaned up grammar, added explanations, standardized formatting.

- [x] I have read [freeCodeCamp's contribution guidelines](https://github.com/freeCodeCamp/freeCodeCamp/blob/master/CONTRIBUTING.md).
- [x] My pull request has a descriptive title (not a vague title like `Update index.md`)
- [x] My pull request targets the `master` branch of freeCodeCamp.
- [x] None of my changes are plagiarized from another source without proper attribution.
- [x] My article does not contain shortened URLs or affiliate links.

If your pull request closes a GitHub issue, replace the XXXXX below with the issue number.

Closes #XXXXX

### CODE REVIEW

**Comment by RandellDawson** [comment]
**Hi,**

**Thanks for this pull request (PR).**

**Unfortunately, we are marking this PR invalid for hacktoberfest. We believe it does not follow the recommended guidelines:**

> ### Quality Standards 
> In line with Hacktoberfest value `#2` (Quantity is fun, Quality is key), we have provided examples of the quality standards we encourage. This applies mainly to beginners.
>
> * PRs that are automated e.g. scripted opening PRs to remove whitespace / optimize images.
> * PRs that are disruptive e.g. taking someone else's branch/commits and making a PR.
> * PRs that are regarded by a project maintainer as a hindrance vs. helping.
> * Something that's clearly an attempt to simply +1 your PR count for October.

Learn more at https://hacktoberfest.digitalocean.com/details

**Comment by joesvetz** [comment]
Hi Randell,

Thanks for your feedback on this. Would it be possible to get some more information as to why this PR was marked invalid? I corrected a number of errors in this doc as well as adding more commentary. It was definitely not disruptive or an attempt to +1 my PR count, so it seems like it was either taking someone else's branch/commits and making a PR (which would have been completely unintentional as I don't fully understand how I would do it, but I apologize if I did so), or it was a hindrance vs. helping, in which case, I would like to understand why so I don't do it again.

Either way, glad to be getting involved.

Joe

**Comment by RandellDawson** [comment]
Sure.  You deleted the title metadata:
```
---
title: Basic Number Properties Associative, Commutative, and Distributive
---
```
If you take a look at the [Style Guide](https://github.com/freeCodeCamp/freeCodeCamp/blob/master/docs/style-guide-for-guide-articles.md) for the articles, you will see it is required to be at the top for all articles.

**Comment by joesvetz** [comment]
Got it - thank you for the info! I had read a style guide, but it was different and I missed the title part. I have now resubmitted the PR - hopefully it will be passable.

**Pull request closed without merging**
