### PR TITLE
feat(interview-prep): Porting Rosetta Problem: Sort Disjoint

### PR DESCRIPTION
**Pull request by NitronR**
- [ ] I have read [freeCodeCamp's contribution guidelines](https://github.com/freeCodeCamp/freeCodeCamp/blob/master/CONTRIBUTING.md).
- [ ] My pull request has a descriptive title (not a vague title like `Update index.md`)
- [ ] My pull request targets the `master` branch of freeCodeCamp.
- [ ] None of my changes are plagiarized from another source without proper attribution.
- [ ] My article does not contain shortened URLs or affiliate links.

If your pull request closes a GitHub issue, replace the XXXXX below with the issue number.

Closes #XXXXX

### CODE REVIEW

**Comment by nikrb** [comment]
@RandellDawson successfully tested locally

**Comment by scissorsneedfoodtoo** [comment]
Hey @NitronR. Did some testing locally and found that the solution didn't work as expected. I modified it a bit and this should pass:

```js
function sortDisjoint(values, indices) {
  let sublist = [];

  indices.sort(function (a, b) { return a - b; });
  
  for (let i = 0; i < indices.length; i++) {
    sublist.push(values[indices[i]]);
  }
  
  sublist.sort((a, b) => { return a - b; });
  
  for (let i = 0; i < indices.length; i++) {
    values[indices[i]] = sublist[i];
  }

  return values;
}
```

Let me know what you think!

**Comment by scissorsneedfoodtoo** [comment]
Also, just noticed, but could you add an indent to the tests?

```js
tests:
  - text: <code>sortDisjoint</code> should be a function.
    testString: assert(typeof sortDisjoint=='function','<code>sortDisjoint</code> should be a function.');
```

**Comment by nikrb** [comment]
just tested this locally again and the solution doesn't seem to be recognised:
```
  Check challenges tests
    Sort disjoint sublist
      ✓ Common checks
      ✓ Test suite must fail on the initial contents (1185ms)
      - Check tests. No solutions
```

**Pull request merged**
